### ISSUE TITLE
Sorting by "price" products including taxes does not work

### ISSUE THREAD

**Issue by pascal-boisselier** [magento/magento2#26283]
### Preconditions (*)
**Summary of the issue**
In the list of products (category, search etc..) we can't sort correctly by price if we show prices including taxes. The sort is only based on prices excluding taxes. In New Caledonia but also in different countries in Europe, we have, for a same category of product different taxes. That's why this is a very common error on websites same if we are using the latest version of Magento.

**Information on your environment**
 - On our project Magento 2.3.2 / 150 000 products / Multi-Store configuration / 6 levels of taxes
 - I also reproduced it using latest version of Magento 2.3.3 / Mysql 5.7 / Ubuntu / Php 7.2.24 / Luma theme without any customisation

### Steps to reproduce (*)
**Steps to reproduce**
1.Install Magento 2.3.3
2.Create 2 or 3 different Taxe Rules  - (Store / Taxe Rules => Add New Tax Rule) and apply it to Product Class
3.Create 5 to 10 Products with their price and apply different taxes - create a category and put all products inside
4.In store / configuration / sales / tax change Price Display Settings to display "Including and Excluding tax"
5.Clean cache and reindex
6.Go on your front-end / in your category / sort by price

### Expected result (*)
**Expected results**
Expected : a list of product sort by price including taxes (I wrote the number in red to help visualize.)
![Sélection_031](https://user-images.githubusercontent.com/11149224/71872512-c5a14480-3170-11ea-9521-57f35905b757.jpg)

### Actual result (*)
**Actual result**
Result : a liste of product sort by price excluding taxes which is wrong for the customer who use the website
![Sélection_031](https://user-images.githubusercontent.com/11149224/71872362-4b70c000-3170-11ea-9b8c-cfc7d79d7e5e.png)

**Comment by pascal-boisselier** [comment]
Based on your recommandation, I tryed and reproduced on the 2.4-develop branch up to date.
@rammohan-krish , please let me know if you have any information about this issue.

![screencapture-magento2-4-local-product-categ-1-html-2020-01-13-15_56_30](https://user-images.githubusercontent.com/11149224/72233747-4652bb80-361d-11ea-9d4b-bb466c62b04b.png)

**Comment by pascal-boisselier** [comment]
@rammohan-krish any idea ?
Did you find something to help us ?

**Comment by engcom-Bravo** [comment]
Hello @pascal-boisselier 

Thank you for your report. I could easily reproduce this behavior on my instance
![sort](https://user-images.githubusercontent.com/51680745/75874521-8adb2600-5e1a-11ea-8b48-667a9da4563d.png)

**BUT** this expected to _Sort By_ Original Price (Excluding tax).
The tax rules may apply differently for each Country, even region. 
That is why, in Magento, Sorting works by the _Original Price_ (Excluding tax) 

We have to close this issue. Please feel free to comment. Or if you ever face any issues with Magento, please feel free to create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you for your collaboration

**Comment by pascal-boisselier** [comment]
Thank you @engcom-Bravo  for your analyse. You perfectly explain this issue, but it means that Magento manage multiple Region / State / Country / Taxes / Currencies  and works very well for specific cases in Search / customer navigation /  Cart etc.. but not for this specific sorting ?

This issue was in other old tickets, it means that a lot of countries is impacted by this error. Do you want to discuss about it - to list all cases together and  increase the quality of the sorting results ?

**Comment by edward-simpson** [comment]
It's disappointing that Magento don't see this as an issue, this effectively makes price sort useless for a lot of stores (and is a change in behaviour between M1>M2).  I accept that tax rules can change by region, but the storefront already manages to calculate price for product listings (based on default country/region I presume), so why shouldn't it correctly take this into account when it comes to sort order?  You mention that sorting works by _original price_, but it never states this in the admin panel, whenever price listing is mentioned it's referred to as 'Price', not 'Original Price' (yes I know this comes from the attribute name) - this isn't even mentioned at all in either the dev docs or user guide.

Overall this feels like a very lazy response from the Magento team, trying to palm off a bug as a feature.
