### ISSUE TITLE
Total shipment amount is included in partial invoice even if shipment amount is applied per item

### ISSUE THREAD

**Issue by nandigowda-zz** [magento/magento2#26286]
**Preconditions (*)**

1. Magento Community version 2.3.3
2. Php 7.3
3. Stores -> Configurration -> Sales -> Shipping methods -> Flat Rate -> Type is set to "Per Item"

**Steps to reproduce (*)**

1. Place an order with 2 different simple products priced '**item 1 price**' and '**item 2 price**' and '**total shipping amount**' flat rate shipping, that include '**item 1 shipping amount**' and '**item 2 shipping amount**'.
2. Create Partial invoice for item 1
3. Create Partial invoice for item 2

 **Actual result (*)**

1. Item 1 partial invoice amount is '**item 1 price**' + '**item 1 shipping amount**' + '**item 2 shipping amount**'.
2. Item 2 partial invoice amount is '**item 2 price**'

 **Expected result (*)**

1. Item 1 partial invoice amount should be '**item 1 price**' + '**item 1 shipping amount**'.
2. Item 2 partial invoice amount is '**item 2 price**' + '**item 2 shipping amount**'.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26286-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26286-2-4-develop.instances.magento-community.engineering/admin](https://i-26286-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nandigowda-zz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nandigowda. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nandigowda, here is your [Magento instance](https://i-26286-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26286-2-4-develop.instances.magento-community.engineering/admin](https://i-26286-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-26286-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26286-2-4-develop.instances.magento-community.engineering/admin_48cf](https://i-26286-2-4-develop.instances.magento-community.engineering/admin_48cf)
Login: `810b7e13` Password: `73adc26fead9`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @sdzhepa 
can you please check this issue with the product owner for what will be the actual result for this issue .. 
It seems issue for flat rate if setting is per item but it will not be issue for other custom shipping methods

**Comment by snez** [comment]
This is still a problem on Magento 2.4. Partial invoices force-include the full order shipping amount, whereas in certain cases, the merchant may wish to invoice a lesser shipping amount.

**Comment by mbaysinger** [comment]
This is still a problem in Magento 2.4.5 as well. I raised this issue with our Adobe Commerce rep and Adobe Commerce support, and they confirmed that this is expected behavior, with no plans to fix it.
