### ISSUE TITLE
Incorrect Tax showing for online Credit Memo

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#26284]
### Preconditions (*)

1. latest Magento version
2. online payment method require like Braintree or PayPal
3. create an order with at least two items
4. place an order and create invoice separately
5. create a credit memo from one of the invoice ( make sure online credit memo)

### Steps to reproduce (*)

1. place an order with two products and online payment method. each product has tax. 
https://www.screencast.com/t/POREIL81nvOZ
2. create two invoices for individual products.
3. now click create credit memo from one of invoice.

### Expected result (*)

1.  credit memo should include tax of that particular item only.

### Actual result (*)

1. invoice showing tax correct but credit memo calculating tax of whole order.
https://www.screencast.com/t/i8cIiuWvt
https://www.screencast.com/t/WLMGPPvtzTy

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-26284-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26284-2-4-develop.instances.magento-community.engineering/admin](https://i-26284-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @sunilit42,
Please let me know this issue is related to the below issues or not.
https://github.com/magento/magento2/issues/23938
https://github.com/magento/magento2/issues/10982

Thanks.

**Comment by sunilit42** [comment]
Here is proof :
Component: 
Screenshot of Invoice

![image](https://user-images.githubusercontent.com/2923438/71875922-8280aa80-314b-11ea-97f9-f88fd7182a71.png)

when go to credit memo screen:-

![image](https://user-images.githubusercontent.com/2923438/71875954-9cba8880-314b-11ea-9366-10504b056316.png)

on the above screenshot, you will see item wise tax is :$8.25 but showing total tax into credit memo total

Reproduced on : latest magento version

**Comment by magento-engcom-team** [comment]
@sunilit42 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by sunilit42** [comment]
> Hello @sunilit42,
> Please let me know this issue is related to the below issues or not.
> #23938
> #10982
> 
> Thanks.

it is similar but a little bit different.

**Comment by ajijshekh123** [comment]
> > Hello @sunilit42,
> > Please let me know this issue is related to the below issues or not.
> > #23938
> > #10982
> > Thanks.
> 
> it is similar but a little bit different.

Okay @sunilit42

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30246` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30246` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by marcusirgens** [comment]
Confirming we're seeing this issue on 2.3.2 when trying to create an offline memo as well:
![Order](https://i.imgur.com/EBLdmbL.png)

When trying to credit memo:
![Credit memo](https://i.imgur.com/Obis1tE.png)
