### ISSUE TITLE
Jump Datepicker in  Catalog Price Rule

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26289]
### Summary

Jump Datepicker in  Catalog Price Rule

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Login to Backend
2. Go to Marketing => Promotions => Catalog Price Rule
3. Click on Datepicker

### Expected result

1. Datepicker does not jump in Catalog Price Rule
![expected](https://user-images.githubusercontent.com/23443991/71888744-c7660a80-3166-11ea-9e71-c83a44dbac70.gif)

### Actual result

1. Jump Datepicker in Catalog Price Rule
![actual](https://user-images.githubusercontent.com/23443991/71888743-c7660a80-3166-11ea-8de2-b8b88d93fe0c.gif)

**Comment by hitesh-wagento** [comment]
I am working on this issue.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26289-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26289-2-4-develop.instances.magento-community.engineering/admin](https://i-26289-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@hitesh-wagento - This is a UI effect not an issue.

**Comment by hitesh-wagento** [comment]
> @hitesh-wagento - This is a UI effect not an issue.

But it looks like issue not UI effect.

**Comment by ajijshekh123** [comment]
Okay @hitesh-wagento

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30247` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26290 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [557247fcd9c55119dcf97bc4804366aefe2274b4](https://github.com/magento/magento2/commit/557247fcd9c55119dcf97bc4804366aefe2274b4)

The fix will be available with the upcoming 2.4.0 release.
