### ISSUE TITLE
Can not save catalog image again after the first save

### ISSUE THREAD

**Issue by ngtuan96lc** [magento/magento2#26282]
### Preconditions (*)

1. Magento version 2.3.3

### Steps to reproduce (*)

1. Open Catalog > Categories > Click into a category
2. Tab Content > upload a " Category Image" > Click button "Save"
3. After page reloads > Click button "Save" again

### Expected result (*)

1. The category image still displays, not disappear

### Actual result (*)

1. The category image is disappear.

### Note
I saw a diffirence between version 2.3.3 and other version. Please check line: 
Magento/Catalog/Model/Category/Attribute/Backend/Image.php:128
$imageName = $this->checkUniqueImageName($imageName);
After run this line code, the $imageName was changed. I thinks, it's cause. 
![image](https://user-images.githubusercontent.com/22560466/71867104-5e1cd200-313b-11ea-9a5f-81287b286767.png)

Thanks so much.

**Comment by krishprakash** [comment]
Hi @ngtuan96lc.
Issue is duplicate to #25099
Issue will be fixed in next 2.3.4 release
You can review the feedback from above given issue link.
Thanks.
