### ISSUE TITLE
Checkout Agreements - Modal does not show a title

### ISSUE THREAD

**Issue by chequille** [magento/magento2#26280]
Modal Window does not show the title which is set in checkout-agreements.js:

showContent: function (element) {
    this.modalTitle(element.checkboxText);
....

### Preconditions (*)
1. Magento Version 2.3.3
2. Magento 2.4-develop

### Steps to reproduce (*)
1. Create at least one agreement and click on this in checkout. Modal appears, but without a title

### Expected result (*)
1. Modal should have a title as it is set in checkoout-agreements.js

### Actual result (*)
1. modTitle is not shown

### Additional Information:
 Suggestion is add an additional field for the agreements, which is only for the title of the modal.

**Comment by Serializator** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Serializator, here is your [Magento instance](https://i-26280-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26280-2-4-develop.instances.magento-community.engineering/admin](https://i-26280-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Serializator** [comment]
I can confirm that the "Checkbox Text" of a "Terms and Condition" is not used as the title of the modal.

Though I can confirm that the original statement in the issue is correct, I can't confirm that this is actually the expected behaviour. I'd say that I wouldn't want the "Checkbox Text" to be used as the title of the modal.

If I have a "Checkbox Text" of "I agree with the Terms and Condition", the title of the modal would be "I agree with the Terms and Condition" instead of something like "Terms and Condition" which seems like more of a title than the other in my opnion.

**Comment by Serializator** [comment]
It seems that the `modalTitle` observable in the UI component that renders the `view/frontend/web/template/checkout/checkout-agreements.html` is never used in the template.

It updates the observable but the observable is simply never used.

**Comment by chequille** [comment]
Hi Julian,
thanks for doing the test on vanilla.

I agree, that using the checkbox Text is not really a title as I want it in the modal.
Therefore, I would suggest to have an additional field for the agreements, which is only for the title of the modal.
This would make sense.
What do you think?

Best regards,
Chequille

**Comment by Serializator** [comment]
@chequille, an additional field in the "Terms and Condition" for the title seems like a good option to me. I also think that the default styling from the modal component is already enough.

<img width="1904" alt="Screenshot 2020-01-06 at 19 58 54" src="https://user-images.githubusercontent.com/7153670/71841269-4dc71180-30bf-11ea-9e35-7b1a0b3d517e.png">

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26280-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26280-2-4-develop.instances.magento-community.engineering/admin](https://i-26280-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pawan** [comment]
@chequille , @Serializator @magento-engcom-team 
Should I use existing text as title Or Should Add a new field to add Title in admin ?
Please Update label accordingly.

**Comment by Serializator** [comment]
@pawankparmar, I'd suggest adding a new field for this.
I can't seem to add or change labels.

**Comment by chequille** [comment]
Hi,
I think as well adding an extra filed would make more sense, as the label is often a sentence f.e. like "Yes, I agree privacy" and this is not a good title for the modal.

Regards,
Chequille

**Comment by engcom-Delta** [comment]
Hi @chequille thank you for your report. I checked issue in 2.4-develop and I am not sure this is an issue. We can customize Checkout Agreements using html tags if `Show Content as` is `HTML`
**Result:**
![image](https://user-images.githubusercontent.com/51681379/103402807-88d71600-4b56-11eb-8aed-ff619ce9d679.png)

Are html tags not enough to set title in your case?

**Comment by chequille** [comment]
@engcom-Delta
Hi,
long time ago that somebody looked at this.
You are right, that this is not a real bug, but something inconsistent to other behaviours of modals where modTitle is used.
The difference of using html tags and the correct use of modTitle is, that the title is shown below the line and not above.
![grafik](https://user-images.githubusercontent.com/15807794/103405105-4281b700-4b56-11eb-8dce-fbf0a21e1f2c.png)

I thing, that if something is there as a feature (in this case showing the agreements text as modal) it should offer all parts of it, as well modTitle.

I don't care about this at the moment, because a lot of other more important bugs are in 2.4.1 which should be solved.
Therefore, if you do not see it as important to have a field which is used for modTItle as suggested in previous comments, forget it!!!

Take care and have a happy new year 2021
Chequille

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40759` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chequille** [comment]
I would say: if you are not willing to improve magento code, leave it as it is.

But a modal does have a title and therefore the modals from the agreements should have it as well.

My opinion !!!

**Comment by OvalMedia** [comment]
Unstaling

**Comment by engcom-Bravo** [comment]
Hi @chequille,

Thanks for your reporting and collaboration.

As per this Magento devdocs https://experienceleague.adobe.com/en/docs/commerce-admin/stores-sales/point-of-purchase/checkout/terms-and-conditions#step-1-enable-terms-and-conditions-for-checkout it is working as expected.Hence we are closing this issue as expected behaviour.

Thanks.
