### ISSUE TITLE
Image transparency no more exist nor displaying correctly after uploading image as a product image.

### ISSUE THREAD

**Issue by Kindlebit-Kbs** [magento/magento2#26291]
### Summary (*)
after uploading an image as a product image from admin it looses its original transparency and create an new image with specific height and width.    

### Examples (*)
Here is an image I want to upload for front end product image. My original image will look like this:  [
![image](https://user-images.githubusercontent.com/59607065/71894371-17979980-3174-11ea-998e-7e99edc24fdd.png)
](url) 

But After uploading it as a product base image it will shown like this on frontend: [
![image](https://user-images.githubusercontent.com/59607065/71894453-4e6daf80-3174-11ea-8371-77b6c0ebafe5.png)
](url)

### Proposed solution
Please suggest a better solution for it. Thank You.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26291-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26291-2-4-develop.instances.magento-community.engineering/admin](https://i-26291-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@Kindlebit-Kbs - Please give me this attached product image.

**Comment by Kindlebit-Kbs** [comment]
I have already attached both images in above issue.

**Comment by ajijshekh123** [comment]
@Kindlebit-Kbs - Please send original image. This attached image is related to browser image.

**Comment by Kindlebit-Kbs** [comment]
![crew_front](https://user-images.githubusercontent.com/59607065/71894887-7c9fbf00-3175-11ea-8eb7-0e92db91061b.png)
![crew_front_after_uploading](https://user-images.githubusercontent.com/59607065/71894915-96410680-3175-11ea-87b7-ea29027d4ee8.png)

**Comment by ajijshekh123** [comment]
Thanks @Kindlebit-Kbs

**Comment by ajijshekh123** [comment]
@Kindlebit-Kbs - In Frontend view, Product image is proper to display which is added by your end but If this image opens in a new tab, Product image is not displayed properly.
**Please check the below URL:**
https://i-26291-2-4-develop.instances.magento-community.engineering/simple-product-1.html

Currently, Product image color is black displaying but I have uploaded the White Background image.

Let me confirm this issue and the Developer will fix the issue.

**Comment by Kindlebit-Kbs** [comment]
@ajijshekh123  Yeah, I need to edit the background for this image, but because of this problem I am enable to do same. Please let me know when it will fixed. thanks.

**Comment by ajijshekh123** [comment]
@Kindlebit-Kbs , Fixed by the Development Team in Next Updation. 
If I will confirm the issue, Developer will work on this issue and fixed it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30248` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Kindlebit-Kbs** [comment]
Hello @ajijshekh123 , any updates.?

**Comment by ajijshekh123** [comment]
Hello @Kindlebit-Kbs ,
Magento Development Team Or Any of the Magento developers will fix this issue and update it. 
I am Magento QA Maintainer so I can't able to fix this issue.

Thanks.

**Comment by Kindlebit-Kbs** [comment]
ok @ajijshekh123 , Can you please check for the possible estimate for fixing this issue.?

**Comment by Kindlebit-Kbs** [comment]
hello @ajijshekh123 , Any Updates..?

**Comment by magento-engcom-team** [comment]
Hi @Kindlebit-Kbs. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30248` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
