### ISSUE TITLE
Customer data AJAX request is executed on every cart page reload when subtotal is set to be displayed including tax.

### ISSUE THREAD

**Issue by diwipl** [magento/magento2#26294]
### Preconditions (*)
1. Magento 2.3.3
2. Product that can be added to cart

### Steps to reproduce (*)
1. Create tax zone and rule so products in shop are taxed
2. Set Stores -> Configuration -> Sales -> Tax -> Shopping Cart Display Settings -> Display subtotal to "Including Tax"
3. Refresh caches
4. Go to storefront
4. Add product to cart
5. Visit cart page
6. Open browser Network tab to see requests done by browser

### Expected result (*)

1. customer data cart section AJAX request is executed only once when entering cart page for the first time, after refreshing page data is not reloaded

### Actual result (*)
1. customer data cart section AJAX request is executed on every cart page refresh

When setting tax configuration to display prices including tax (common scenario for European shops) code from vendor/magento/module-checkout/view/frontend/web/js/model/totals.js file:
```javascript
    var quoteItems = ko.observable(quote.totals().items),
        cartData = customerData.get('cart'),
        // quoteSubtotal = parseFloat(quote.totals().total_segments.find(total => total.code === 'subtotal').value),
        quoteSubtotal = parseFloat(quote.totals().subtotal),
        subtotalAmount = parseFloat(cartData().subtotalAmount);

    quote.totals.subscribe(function (newValue) {
        quoteItems(newValue.items);
    });

    if (quoteSubtotal !== subtotalAmount) {
        customerData.reload(['cart'], false);
    }
```

is constantly invalidating cart customerData section. 

The reason is that `subtotalAmount` variable always contains subtotal without tax.
 `quoteSubtotal` contains value that depends on Magento tax configuration (including or excluding tax depending on setting mentioned in Steps to reproduce).

**Comment by diwipl** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @diwipl. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @diwipl, here is your [Magento instance](https://i-26294-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26294-2-3-3.instances.magento-community.engineering/admin](https://i-26294-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by diwipl** [comment]
Instance configured according to issue description is invalidating customer section cart on every cart page reload:
![image](https://user-images.githubusercontent.com/3406741/71904431-5cb4cf00-3166-11ea-9021-f2906698413a.png)

**Comment by magento-engcom-team** [comment]
@krzksz Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krzksz 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30275` were created

**Issue Available**: @krzksz, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
I will fix this issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by jampolm** [comment]
@magento give me 2.4.3 instance
