### ISSUE TITLE
Inconsistent Dynamic SKU behavior with multi-select Customizable options

### ISSUE THREAD

**Issue by Morgon** [magento/magento2#26297]
Magento's SKU builder for Customizable Options behaves inconsistently. It ignores empty values for single selections, but then concatenates multiple empty values when evaluated from an Option array, such as a Checkbox or Multi-select Option.

This behavior is defined in
[`Magento\Catalog\Model\Product\Option\Type\Select::getOptionSku`](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Model/Product/Option/Type/Select.php#L279-L292)

### Preconditions (*)
1. Magento 2.2.10
2. PHP 7.2

### Steps to reproduce (*)
1. Create any simple product
2. Add a Checkbox or Multi-Select Customizable Option
3. Configure at least two options (of any Title and Price), leaving the SKU fragments empty.
4. On the frontend, add this product to your cart, selecting both custom options.
5. In the `quote_item` table (or within the order after checkout), observe the SKU.

### Expected result (*)
1. Because we have not configured any SKU fragments, the SKU should not be altered - a base product SKU of "TEST_SKU" should remain so.

### Actual result (*)
1. Quote/Order Item has a SKU of "TEST_SKU--", a result of concatenating the SKU with the array of concatenated Options containing (empty) SKU fragments.

**Comment by Morgon** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Morgon. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Morgon, here is your [Magento instance](https://i-26297-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26297-2-4-develop.instances.magento-community.engineering/admin](https://i-26297-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Morgon** [comment]
Behavior confirmed on 2.4-develop

![Screen Shot 2020-01-07 at 11 45 48 AM](https://user-images.githubusercontent.com/879077/71912371-5fea9380-3143-11ea-872a-3b52e6a59e6d.png)

**Comment by gibkigonzo** [comment]
Hello :) I'm not sure, but in this line [L819](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L819) you pass to `getOptionSku` as second parameter  `$skuDelimiter`. So here [L802](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L802) as `$sku` we have value from `$skuDelimiter` which is `'-'` [L804](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L804). Maybe solution will be to pass empty string, so it will get sku from product in [L806](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L806)?

**Comment by Morgon** [comment]
We don't want to explicitly pass an empty string in `AbstractType`, because we still want defaults for legitimate SKU updates. 

I currently believe the best course of action is for `Type\Select` to simply use something like `array_filter($skus)` after [building the options array](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Model/Product/Option/Type/Select.php#L292). Empty array, empty string.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30446` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
