### ISSUE TITLE
Attribute with multiple option   is not saving in admin, magento 2.3.3

### ISSUE THREAD

**Issue by euNatan** [magento/magento2#26300]
Hi, I am using Magento 2.3.3, and when I try save a new  attribute values in multiple options, it is not saving, I  read that issue has been fixed, but not here. Could you help me please

**Comment by mrtuvn** [comment]
I can't reproducible your issue in 2.4-develop

**Comment by Zyles** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Zyles, here is your [Magento instance](https://i-26300-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26300-2-3-3.instances.magento-community.engineering/admin](https://i-26300-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26300-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26300-2-3-3.instances.magento-community.engineering/admin](https://i-26300-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @euNatan 
I checked it .. this issue is also not reproducible at magento 2.3.3 instance

**Comment by euNatan** [comment]
Hi, I Will check If some module cause this issue.
Thank you

Em qua, 8 de jan de 2020 10:58, Shikha Mishra <notifications@github.com>
escreveu:
