### ISSUE TITLE
MFTF: Verify if all the <createData> has also corresponding <deleteData>

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26307]
### Summary (*)
After running several MFTF tests, you have a huge mess in your Category Structure:
![image](https://user-images.githubusercontent.com/1639941/71974298-75c68a00-3211-11ea-82e1-712d1d441ae7.png)

We should introduce verification for having corresponding `<deleteData>` for each `<createData>`.

### Examples (*)
N/A

### Proposed solution
I'm not sure if XSD is able to handle that, but static analysis tools should be able to perform such verification.

**Comment by engcom-Delta** [comment]
@lbajsarowicz thank you for your report. I am not sure that having corresponding `<deleteData>` for each `<createData>` would be a good idea, for example, creation [configurable product ](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Test/Mftf/Test/StorefrontClearAllCompareProductsTest.xml#L38). 
For particular case you are free to create pull request.

Marked as **Future Request** for further discussion

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.

**Comment by dverkade** [comment]
@lbajsarowicz  why are you closing issues which are "ready for confirmation"?

**Comment by lbajsarowicz** [comment]
@dverkade  After 1,5 years, I'm no longer able to maintain the issue.
