### ISSUE TITLE
Update Attributes For Products Not Working

### ISSUE THREAD

**Issue by cerebrum-opensource** [magento/magento2#26309]
Hi,

I am using  Magento ver. 2.3.3

When I go to Catalog->Products and Select any Product for Mass Update Attributes, then the Attributes screen does not load.

![Screenshot from 2020-01-08 17-22-42](https://user-images.githubusercontent.com/24713440/71976124-93104e00-323b-11ea-86b1-5d204acd0fff.png)

So after some debugging, I went to file /vendor/magento/module-catalog/Block/Adminhtml/Product/Edit/Action/Attribute/Tab/Attributes.php

And then on line number 84, there is code $attributes = $this->getAttributes(); which fetches all the attributes from file \Magento\Catalog\Helper\Product\Edit\Action\Attribute and function named getAttributes() and pass them into $this->_setFieldset($attributes, $fieldset, $this->getFormExcludedFieldList());

If I do not load the Attributes from this function, and initialize the $attributes as an empty array, then the screen appears and Attributes does not appear, obviously because I am initialilized as empty, But other 2 tabs for Inventory and  Websites appear fine.

So just to cross verify that the Helper function for getting the Attributes is working on not, I went to that function and sent the count of Attributes over my Email and count is coming fine i.e 98.

Expected Result is All Attributes which can be mass edited should appear in the list but not working.

I have tried the same on my Local system as well but not working there as well.

Please help...

**Comment by krishprakash** [comment]
Hi @cerebrum-opensource. Can not reproduce the issue as provided steps by you.
Refer below link for reference.
https://www.screencast.com/t/1b2FhGYoSl
Please provide more details to reproduce this issue 
Thanks.

**Comment by krishprakash** [comment]
Hi @cerebrum-opensource. 
Feel free to reopen the issue once you update the reproducible steps.
Due to inactivity closing this ticket
Thanks
