### ISSUE TITLE
Magento 2.2.4 - Migrated working code from AWS to Google Cloud and not able to run the website - website not working so ran setup:upgrade and static content deploy and getting error in compilation command gto following error

### ISSUE THREAD

**Issue by shansari25** [magento/magento2#26316]
Summary of the issue

Migrated working code from AWS to Google Cloud and not able to run the website - website not working so ran setup:upgrade and static content deploy and getting error in compilation command
gto following error

[InvalidArgumentException] Plugin class Magento\ConfigurableProduct\Model\Quote\Item\QuantityValidator\Initializer\Option\Plugin\ConfigurableProduct doesn't exist

Information on your environment

Magento 2.2.4

Steps to reproduce

php -dmemory_limit=5G bin/magento setup:di:compile
Compilation was started.
Expected and actual results

[InvalidArgumentException] Plugin class Magento\ConfigurableProduct\Model\Quote\Item\QuantityValidator\Initializer\Option\Plugin\ConfigurableProduct doesn't exist

**Comment by shansari25** [comment]
yes issue is reproducible

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/magento/magento2/issues/26315
