### ISSUE TITLE
after installation magento 2 not working panel admin

### ISSUE THREAD

**Issue by wrackful** [magento/magento2#2631]
i found a solved
go to database mysql and find core_config_data then change value congifid(1,2) to 127.0.0.1/magento2 and clear cash
restart wamp or xamp

**Comment by daim2k5** [comment]
@wrackful is this a bug? localhost or only 127.0.0.1 is not a valid domain

**Comment by wonderfan** [comment]
It is better to use 127.0.0.1 like magento one

**Comment by daim2k5** [comment]
@wrackful i close the issue because you didn't responded after 2 weeks :-(
