### ISSUE TITLE
"SameSite" field of a cookie, which can be either  "None", "Lax" or "Strict" in Google Chrome

### ISSUE THREAD

**Issue by anziv** [magento/magento2#26310]
### Preconditions (*)
1. Any Magento versions

### Steps to reproduce (*)

1. Incrementally Better Cookies ("SameSite") will be released on February 2020 by Google Chrome team 
2. More info is here: https://www.youtube.com/watch?v=VnN8NwTeXAc

### Expected result (*)

1. Should be provided solution/workaround added to repo for all Magento2 vesrions so cookie  will not stopped to work on sites running with magento 2 starting February 2020.

### Actual result (*)

1. From February 2020 will no any cookie work like it should in Google Chrome for Magento2 sites if SameSite not be fixed

**Comment by devchris79** [comment]
I think this relates to Googles cookies (probably the ReCaptcha security). I think the security issue is with cross-site resources (coming from Googles server).

**Comment by rodde177** [comment]
@devchris79 most ecommerce shops use some sort of third party cookie, so unfortunately most sites will be affected.
PHP only supports SameSite attribute from 7.3 https://www.php.net/manual/en/function.setcookie.php#refsect1-function.setcookie-changelog

**Comment by DavaGordon** [comment]
> 
> 
> I think this relates to Googles cookies (probably the ReCaptcha security). I think the security issue is with cross-site resources (coming from Googles server).

This has to do with all cookies which do not originate from the same URL not just google. this will have a massive impact on everyone. not long until it is rolled out and could have massive implications if people have not prepared. this change will affect user session cookies, payment gateway sessions and so much more

**Comment by devchris79** [comment]
@DavaGordon I was actually referring to the likely culprit for the Magento 2 core files. I realise the issue extends to other modules and any potential cross site cookie.

**Comment by engcom-Charlie** [comment]
Hello @anziv @sdzhepa
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!

**Comment by DavaGordon** [comment]
@engcom-Charlie I wouldnt say this was a feature more of an essential as this is going to have a big impact on how people are going to be able to process orders as if the session cookies are not passed it is going to make it impossible to pass back data to magento

**Comment by rodde177** [comment]
@engcom-Charlie feature?
From february 4th it will definitely be a bug when chrome 80 is released.

https://www.chromestatus.com/features/schedule

You can simulate with chrome://flags/ this functionality today.
Enable:
**Cookies without SameSite must be secure**

**Comment by diazwatson** [comment]
Closing this issue to centralise all the discussion in https://github.com/magento/magento2/issues/26377
Please reopen if needed.

**Comment by MaalyALkaraki** [comment]
Is there any update on this ? we are struggling to fix this  and it is affecting all our Magento2 customer ,we apply all the fixes and unfortunately nothing is working .
