### ISSUE TITLE
Can not share product if only out of stock product in wish list

### ISSUE THREAD

**Issue by renard123** [magento/magento2#26324]
Can not share product if only out of stock product in wish list

### Preconditions (*)
Magento: 2.3.3

### Steps to reproduce (*)
-> Login into front end
-> Add product at admin and make it out of stock
-> Set show out of stock product at front end from 
Admin - Stores > Configuration > Catalog > Inventory > Stock  Options. Display Out of Stock Products: Choose Yes
-> Add product to wish list
-> My wish list - click on share wish list

### Expected result (*)
It should work fine

### Actual result (*)
Page reload and nothing happen

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26324-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26324-2-4-develop.instances.magento-community.engineering/admin](https://i-26324-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30310` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Related PR is In progress #26185

**Comment by gulshanchitransh** [comment]
I am working on this issue #mm20in

**Comment by sdzhepa** [comment]
Issue cannot be reproduced and seems it was fixed and delivered in https://github.com/magento/magento2/pull/26185
