### ISSUE TITLE
404 error page not found for the creating the new configurable product. 

### ISSUE THREAD

**Issue by Datta** [magento/magento2#26326]
### Preconditions (*)

1. Magento version 2.3.2 

### Steps to reproduce (*)
1. create new configurable product
2. enter required field values
3. create configurations
4. select any attribute (in my case size),select attribute values
5. Apply unique quantity by attribute to each SKU
6. select sources 
7. generate products then Hit "Save"  to save your changes.

### Expected result (*)
1. product should be saved 
2. page reload the newly created configurable product

### Actual result (*)
1. Page makes a POST request with all the  data to 
http://abc.com.au/admin/catalog/product/validate/type/configurable/store/0/set/14/key/bf71c17ac808e40388dbaab5f237110b9937e4a849fc77812f1349d028a60acb/?isAjax=true
but it seems that request gets a blank/empty response. 404 error: Page not found ?
http://abc.com.au/admin/catalog/product/save/type/configurable/store/0/set/14/key/8af044777c7e40375c80b27c31a597eb7a26e99a2a322cefd45ec4ee80895566/back/edit
![2020-01-08_1837](https://user-images.githubusercontent.com/356098/72045935-5a28b580-32dd-11ea-9c3d-e98582bc35ec.png)

**Comment by Datta** [comment]
@krishprakash : if you want i can provide the video of the issue so you will have more clarification about the issue. please let me know.

**Comment by krishprakash** [comment]
Hi @Datta. It works fine here as provided steps by you.
Please share the video so it will helpful
Thanks.

**Comment by Datta** [comment]
hi 
i have checked i am getting the issue. please check the below link for more information. 
https://www.screencast.com/t/EEdwqh85KVz

**Comment by Datta** [comment]
steps: 
Step 1: Select Attributes
At the bottom of Product Details, expand the Configurations section. Then, tap Create Configurations.

Configurations

Mark the checkbox of each attribute that is to be used as a configuration.
If you need to add a new attribute, tap Create New Attribute. Complete the attribute properties, and tap Save Attribute. Then, mark the checkbox to select the attribute.
In the upper-right corner, tap Next.

Select Attributes

Step 2: Enter Attribute Values
Mark the checkbox of each variation of the product.
To add a new value, click Create New Value. Then, enter the new value in the input box, and tap the Enter arrow.
Repeat these steps for each attribute that is included as a configuration.

You can rearrange the list of attributes by dragging the box in the upper-left corner to a new position.

In the upper-right corner, tap Next.

Step 3: 
Apply Different Quantity by Attribute

If the quantity is the different for each SKU, select Apply unique quantity by attribute to each SKU.
Enter the Quantity for each.
Different Quantities per Attribute

When complete, tap Next in the upper-right corner.

Step 4: Generate the Product Configurations
Wait a moment for the list of products to appear. When you are ready to add the products to your catalog, tap Generate Products.

The product variations now appear at the bottom of Product Details in the Configuration section.

If you want to edit any of the settings, tap Edit Configurations.

Generate Products

Step 5: Publish the Products
If you are ready to publish the products in the catalog, set the Product Online switch to the “On” position. Otherwise, leave the switch in the “Off” position until the product is ready to publish.
When complete, on the Save menu and it gives the error 404 page not found to save the product.

**Comment by krishprakash** [comment]
Hi @Datta. Looks issue is related to MSI.
It works fine in latest magento 2.4 instance without MSI integrated.
MSI feature is not a part of Magento Open Source.
So please report the issue at it's separate repository.
https://github.com/magento/inventory/issues
Thanks.

**Comment by krishprakash** [comment]
Closing this ticket.
Thanks for your report !

**Comment by Datta** [comment]
ok 
i am reporting to the repository.
https://github.com/magento/inventory/issues
