### ISSUE TITLE
Unable sent welcome email/password reset and cannot save customer error message

### ISSUE THREAD

**Issue by danielmx98** [magento/magento2#26334]
### Preconditions (*)

1.Magento 2.3.3
2.Use bitnami stack, php 7.2
3.Spanish language set

### Steps to reproduce (*)

1.Fresh installation use bitnami stack
2.Installed magaplaza social login and SMTP extension.
3.create customer show up : Cannot save the user , but in the backend customer was already create and able to login. At meantime , there no welcome email sent ,and not able to reset customer password.
4.Test email was perform well without issue, also customer are able to receive invoices(order related) email without issue.
5. I also performed admin password reset, the admin able to receive reset password.

### Expected result (*)

1. Customer can register account without error notices
2.Customer able to reset password.
3.New Customer able to receive welcome email or password reset email.

### Actual result (*)

1. Customer registration encountered : "Cannot save the customers" error message 
2. Customer unable to reset the password. Both frontend and backend.
3.New customers are not able to receive email (account related not working, order related working well)

**Comment by danielmx98** [comment]
@magento give me {$2.3.3} instance

**Comment by danielmx98** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @danielmx98. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @danielmx98, here is your [Magento instance](https://i-26334-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26334-2-3-3.instances.magento-community.engineering/admin](https://i-26334-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @danielmx98 thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.4-develop seems like this related to your custom modules.
Result:
1. :heavy_check_mark: Customer can register account without error notices
![image](https://user-images.githubusercontent.com/51681379/72524007-a9389280-3869-11ea-8c28-0767f2ae8e6c.png)

2. :heavy_check_mark: Customer able to reset password.
![image](https://user-images.githubusercontent.com/51681379/72524591-e05b7380-386a-11ea-9177-f5ff4da266a0.png)

3. :heavy_check_mark: New Customer able to receive welcome email or password reset email.
![image](https://user-images.githubusercontent.com/51681379/72524626-f10be980-386a-11ea-8569-92a987f70cba.png)

![image](https://user-images.githubusercontent.com/51681379/72524675-13056c00-386b-11ea-8ffd-f353a9ac289b.png)


If you'd like to update the issue, please reopen it.
