### ISSUE TITLE
Theme translation is not respected in rest requests

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#26333]
# Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)
1. configure de_DE als store language
2. **add de_DE.csv to template localization (app/design/Vendor/base/i18n/de_DE.csv)**
3. Add "The coupon code isn't valid. Verify the code and try again.","Der Gutscheincode ist nicht gültig. Überprüfen Sie den Code und versuchen Sie es erneut." to de_DE.csv
4. Add a product to cart
5. goto checkout page
6. enter an invalid coupon code

### Expected result (*)

1. the error message should be in german
2.

### Actual result (*)

1. the error message is english
2. If the translation is in a module folder (app/code/Vendor/Package/i18n/de_DE.csv) the translation work.
3. Also the translation of an language package works

**Comment by bernd-reindl** [comment]
i confirm

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30382` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
Same here. M 2.3.2

**Comment by stkrelax** [comment]
Same here. M 2.3.3

**Comment by mrtuvn** [comment]
@bernd-reindl i have tested in luma theme in 2.4-develop branch
The coupon 
![Screenshot from 2020-04-05 12-29-52](https://user-images.githubusercontent.com/1908873/78467696-70f27300-7739-11ea-9850-83431f3debb4.png)
text translated correctly

**Comment by duckchip** [comment]
@magento-encom-team When can this ticket be picked up?

**Comment by BTL-UG** [comment]
Just a workaround but you can force the theme translations by using the frontend store emulation with the force param set to true. This way the translations are reloaded with the respective theme.

`$this->emulation->startEnvironmentEmulation($store, 'frontend', **true**);`

**Comment by cyildirim** [comment]
Cart request on checkout is coming from web api. So theme translation is not in the scope of API. You can either add the translation under some other module or you can add it to under `app/i18n/de_DE`

**Comment by sactor** [comment]
This issue is still relevant. I want to use the Finnish language pack, but there are a lot of translations in it that are non-translated (they are still English to English) and because they exist in the language pack, I can't override them in a module. I can override them in theme, but as mention earlier, API requests don't use translations from a theme.

I _could_ copy the language pack and modify it manually, but that's going to make it very cumbersome to update it later.

I have already submitted all the translation changes I need via the usual channels to update the language packs, but it seems the language pack updating process is basically dead as well.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by clicks-kodet** [comment]
Still valid on `2.4.3`

**Comment by TomashKhamlai** [comment]
@stale

**Comment by TomashKhamlai** [comment]
@magento-probot-user

**Comment by TomashKhamlai** [comment]
@magento-probot-user unstale

**Comment by Minirock** [comment]
Seems to be still valid in 2.4.1. 

Any updates ?

**Comment by AngelBS** [comment]
Any update on this one? we are having the same issue on 2.4.2, two years with the same issue....

**Comment by igi8819** [comment]
same error on 2.4.3... :(

**Comment by Lain818** [comment]
Is there anyone who could offer a fix for this problem?

**Comment by Lain818** [comment]
> To me it makes sense that a REST request does not use theme translations, because a theme has nothing to do with a REST request, no? A REST request is aware of a storeview, but not about themes, because that makes little sense.
> 
> If you want custom translations that are loaded both by the theme and the REST api, it will probably work when you put them in `app/i18n/...` like [explained over here](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/localization.html#create-directories-and-files) or like @cyildirim [already suggested earlier](https://github.com/magento/magento2/issues/26333#issuecomment-672824407).

got it - thanks!! Its finally translated.

**Comment by jellesiderius** [comment]
Just dropping this here...

```
--- Model/CouponManagement.php
+++ Model/CouponManagement.php
@@ -25,15 +25,22 @@
      */
     protected $quoteRepository;

+    /**
+     * \Magento\Store\Model\App\Emulation
+     */
+    protected $emulation;
+
     /**
      * Constructs a coupon read service object.
      *
      * @param \Magento\Quote\Api\CartRepositoryInterface $quoteRepository Quote repository.
      */
     public function __construct(
-        \Magento\Quote\Api\CartRepositoryInterface $quoteRepository
+        \Magento\Quote\Api\CartRepositoryInterface $quoteRepository,
+        \Magento\Store\Model\App\Emulation $emulation
     ) {
         $this->quoteRepository = $quoteRepository;
+        $this->emulation = $emulation;
     }

     /**
@@ -73,7 +80,9 @@
             );
         }
         if ($quote->getCouponCode() != $couponCode) {
+            $this->emulation->startEnvironmentEmulation($quote->getStoreId(), 'frontend', true);
             throw new NoSuchEntityException(__("The coupon code isn't valid. Verify the code and try again."));
+            $this->emulation->stopEnvironmentEmulation();
         }
         return true;
     }

```

**Comment by engcom-Dash** [comment]
Hi @bernd-reindl 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducable.

We are seeing the error message in german.

Please refer the screenshots attached , please verify the issue in latest magneto instance and let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-03-06 at 2 40 04 PM" src="https://github.com/magento/magento2/assets/60198592/c7f186eb-a784-4441-b298-35a02eacb47d">

**Comment by engcom-Dash** [comment]
Hi @bernd-reindl 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by webloft** [comment]
@engcom-Dash Did you test this with V1/carts/mine/totals-information too?

A theme translation is not working there. A translation from app/i18n does.

**Comment by hostep** [comment]
@webloft, have you read the discussion? Like these comments for example:
- https://github.com/magento/magento2/issues/26333#issuecomment-672824407
- https://github.com/magento/magento2/issues/26333#issuecomment-1219467460

**Comment by webloft** [comment]
@hostep yes we read that. We just not agree.

The request is loaded into a theme by default operation in frontend, so it has to deal with translations by the theme too. It can see the storefront, so where is the problem?

**Comment by Eddcapone** [comment]
We have the same problem. Will there be a solution for it?

**Comment by hostep** [comment]
@Eddcapone, there is nothing to fix here, see https://github.com/magento/magento2/issues/26333#issuecomment-2361117064
