### ISSUE TITLE
Custom Address Attribute dropdown shows attribute code rather than selected option

### ISSUE THREAD

**Issue by abbaseg** [magento/magento2#26336]
### Preconditions (*)

1. Magento 2.3.3 Commerce

### Steps to reproduce (*)

1. Go to admin panel
2. Stores -> Attributes -> Customer Address. Then create the dropdown attribute 
![Selection_210](https://user-images.githubusercontent.com/59718206/72123528-e5b94980-33a4-11ea-80b4-26b196ead37b.png)
![Selection_211](https://user-images.githubusercontent.com/59718206/72123552-fa95dd00-33a4-11ea-85da-169e26c07be4.png)
3. Click Save Attribute and flush the cache
4. Go to frontend -> login -> Make sure there should be alrady at least one address in your address book
5. Add any product to your cart -> Go to checkout -> click + New Address button -> Add new address and also select country code
![Selection_212](https://user-images.githubusercontent.com/59718206/72123784-d2f34480-33a5-11ea-9f70-bc4f38be7cc5.png)

### Expected result (*)

![Selection_213](https://user-images.githubusercontent.com/59718206/72123877-1cdc2a80-33a6-11ea-904b-76fef1707c32.png)

### Actual result (*)

![Selection_213](https://user-images.githubusercontent.com/59718206/72123800-e6061480-33a5-11ea-8615-7cbadc9a012c.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26336-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26336-2-4-develop.instances.magento-community.engineering/admin](https://i-26336-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @abbaseg,
This issue I have to reproduce in the Latest Enterprise Magento instance. 
Good issue reproduced @abbaseg :)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30326` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by abbaseg** [comment]
> Hello @abbaseg,
> This issue I have to reproduce in the Latest Enterprise Magento instance.
> Good issue reproduced @abbaseg :)
> 
> Thanks.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by SakeraVora** [comment]
I am working on this issue
