### ISSUE TITLE
Update zendframework to laminas

### ISSUE THREAD

**Issue by mlambley** [magento/magento2#26335]
#  Summary of the issue
Please see in the latest dev branch https://github.com/magento/magento2/blob/ad9e1f08a07fa318a997958c6ecb86f2cddce134/composer.json#L55

You'll notice that, in all branches of this repository, it still refers to `zendframework` in spite of that package being abandoned. This results in a `composer install` which looks like:
```
Package zendframework/zend-barcode is abandoned, you should avoid using it. Use laminas/laminas-barcode instead.
Package zendframework/zend-captcha is abandoned, you should avoid using it. Use laminas/laminas-captcha instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
```

I've seen another ticket for this [here](https://github.com/magento/magento2/issues/25567), but it was promptly closed since the dev could not replicate the issue. But the issue is plainly visible in the most recent `composer.json` file. Magento needs to recognise that zend is being transitioned to laminas and update its dependencies accordingly.

# Information on your environment
Ubuntu 18, Magento 2.3, although the issue can be seen in the source code for 2.4 as well.

### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
Run a `composer install` on any version of Magento

### Expected result (*)
Expect to see no `abandoned` messages.

### Actual result (*)
```
Package zendframework/zend-barcode is abandoned, you should avoid using it. Use laminas/laminas-barcode instead.
Package zendframework/zend-captcha is abandoned, you should avoid using it. Use laminas/laminas-captcha instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
```
![image](https://user-images.githubusercontent.com/51681379/72522967-7a212180-3867-11ea-9316-ea75730a874b.png)

**Comment by matthew-muscat** [comment]
This relates to Zend's announcement moving the Zend Framework to be hosted under the linux foundation — the announcement post regarding this change can be found here — https://framework.zend.com/blog/2019-04-17-announcing-laminas.html

A determination needs to be made as to whether Magento will be moving to utilise Laminas, and if so, how to proceed with migrating the Zend Components to the Laminas namespace.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30481` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
I had opened a feature request ticket for this a few days ago btw, with some possible suggestions, linking it for reference: https://github.com/magento/community-features/issues/229

**Comment by ihor-sviziev** [comment]
This issue was already fixed by https://github.com/magento/magento2/commit/892dee45e4f80ae7df04b4ce550971e5a0453eff
I’m closing this issue
