### ISSUE TITLE
CSS and JS files not loading - 404 Error- Magento 2 Nightmares 

### ISSUE THREAD

**Issue by rajeshmukkala** [magento/magento2#2634]
Hi Devs,

Kindly provide exact solution to JS and CSS files 404 errors. I followed installation guide and did 5 times installation still not able to fix the problem. Only bare pages are loading. Also please note many people struggling with the same issue https://community.magento.com/t5/Installing-Magento-2/bd-p/installing-magento-2. Appreciate proper guide on fixing 404 errors.

**Comment by thienphucvx** [comment]
Hi,
  You can fix it by doing this command in your web directory :
 php bin/magento setup:static-content:deploy

**Comment by rajeshmukkala** [comment]
Looks like Ownership and permission issue. I have applied 777 for testing and it is working fine. thanks @oshanrube

**Comment by daim2k5** [comment]
Hi @rajeshmukkala http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html#install-update-depend-user-over. I close the Ticket now, if you have the feeling that is wrong please feel free to reopen.

**Comment by gosteev** [comment]
@thienphucvx thanks! it worked

**Comment by elangosundar** [comment]
1. Goto below path
```
sudo nano /etc/apache2/apache2.conf
```
and edit below one

```
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride all
        Require all granted
</Directory>
```
2. Enable apache rewrite module and restart the server
```
sudo a2enmod rewrite
sudo service apache2 restart
```
3. Clear the magento cache
```
php bin/magento cache:clean 
php bin/magento cache:flush
```

**Comment by nelsonpoon** [comment]
@ elangovanshanthi it works!  i am apache2.2 , i change the syntex to 
<Directory /var/www/>
        Order allow,deny
        Allow from all
</Directory>

**Comment by Flyiii** [comment]
nginx的解决方法
