### ISSUE TITLE
Products go out of stock while backorder is enabled

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#26344]
### Preconditions (*)
1. Magento 2.3.3
2. Default stock and source

### Steps to reproduce (*)
1. Create a product with 0 or 1 quantity in stock
2. Set global settings in system->catalog->inventory to Manage stock and Backorders set to Allow qty below 0 and Out of stock threshold to 0.
3. Make sure this settings are also set on product level.

### Expected result (*)
1. When product is bought item to be still In stock and quantity decreased.

### Actual result (*)
1. Item goes Out of stock and quantity is decreased.

Screenshots of my settings:

![Schermafbeelding 2020-01-10 om 11 38 13](https://user-images.githubusercontent.com/7294081/72147281-74769800-339e-11ea-8e79-3288e7ce03ec.png)

![Schermafbeelding 2020-01-10 om 11 36 52](https://user-images.githubusercontent.com/7294081/72147280-74769800-339e-11ea-9b4e-fdb5cc6dc031.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26344-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26344-2-4-develop.instances.magento-community.engineering/admin](https://i-26344-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@jorgb90 I have followed your steps and created the product and changed the settings. After placing the order Item is in stock and quantity is decreased . It is working as expected so please provide more details with screenshots/video link

**Comment by jorgb90** [comment]
@sudheers-kensium 

I can see you do not have MSI enabled? I have stores -> inventory and running on the default stock and source.

![Schermafbeelding 2020-01-10 om 13 54 56](https://user-images.githubusercontent.com/7294081/72154396-d0e2b300-33b0-11ea-9c87-f79d945a1984.png)

So probably if I disable the MSI modules in Magento 2 its solved for now?

**Comment by jorgb90** [comment]
I have disabled the MSI modules for now to see if that solves it for now. Will update.

Edit:

Didn't solve my problem :(

Edit 2:

Maybe its caused by other products which are set to No Backorder?

Edit 3:

@sudheers-kensium 

I think its an indexer causing the products go Out of stock. It doesn't directly happen when checking out.

**Comment by jorgb90** [comment]
@sudheers-kensium I found out it only occurs when checking out at the frontend. Placing the order in the backend doesn't trigger it.

**Comment by sudheers-kensium** [comment]
@jorgb90 I am closing this issue. Feel free to reopen if you have any issue.

**Comment by AlexandrKozyr** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @AlexandrKozyr. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AlexandrKozyr, here is your [Magento instance](https://i-26344-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26344-2-3-3.instances.magento-community.engineering/admin_9750](https://i-26344-2-3-3.instances.magento-community.engineering/admin_9750)
Login: `16deaab7` Password: `2bcaa03a7561`
Instance will be terminated in up to 3 hours.

**Comment by techzilla** [comment]
Please status update

**Comment by pmonosolo** [comment]
Yes I can confirm this issue happens on reindex of indexes. I'm not sure which ones yet, but it does happen.

**Comment by SolsWebdesign** [comment]
This is still an issue (on 2.4.4), we need msi (have 2 stock sources) and indexer sets products to isSalable false. We have debugged the code but there are so many plugins it is nearly impossible. We finally gave up and wrote a plugin afterIsSalable that sets backorder products to salable.

**Comment by adarshkhatri** [comment]
We had this issue and I have this solution, seems like working not fully tested though
Create a `after` plugin for  `Magento\InventorySales\Model\ResourceModel\IsStockItemSalableCondition\ReservationsCondition` class:
````
<?php
namespace NameSpace\ModuleName\Plugin\InventorySales\Model\ResourceModel\IsStockItemSalableCondition;

use Magento\CatalogInventory\Api\StockConfigurationInterface;
use Magento\InventoryConfigurationApi\Api\Data\StockItemConfigurationInterface;
use Magento\InventorySales\Model\ResourceModel\IsStockItemSalableCondition\ReservationsCondition as MagentoReservationsConditions;

class ReservationsCondition
{
    /**
     * @param StockConfigurationInterface $configuration
     */
    public function __construct(
        private StockConfigurationInterface $configuration
    ){}

    public function afterExecute(MagentoReservationsConditions $subject, $return, $select)
    {
        $globalBackorders = (int)$this->configuration->getBackorders();
        $itemBackordersCondition = 'legacy_stock_item.backorders <> ' . StockItemConfigurationInterface::BACKORDERS_NO;
        $useDefaultBackorders = 'legacy_stock_item.use_config_backorders';

        $isBackorderEnabled = $globalBackorders === StockItemConfigurationInterface::BACKORDERS_NO
            ? $useDefaultBackorders . ' = ' . StockItemConfigurationInterface::BACKORDERS_NO . ' AND ' .
            $itemBackordersCondition
            : $useDefaultBackorders . ' = ' . StockItemConfigurationInterface::BACKORDERS_YES_NONOTIFY .
            ' OR ' . $itemBackordersCondition;


        return (string) $select->getConnection()
        ->getCheckSql(
            $isBackorderEnabled,
            1,
            $return
        );
    }
}
````

**Comment by aimsjigar** [comment]
We had same issue so I Have applied below solution to fix it. I have override `Magento\InventorySales\Model\ResourceModel\IsStockItemSalableCondition\ReservationsCondition` This file using preference .

![image](https://github.com/magento/magento2/assets/100894075/afc340cf-ddb3-4cdc-930c-0a93578252d4)

**Comment by ihns** [comment]
This bug still exists.

- It only occurs when you select "Allow qty below 0 and notify customer".
- If you set it to "Allow qty below 0", the behavior is as expected.

This should be easy to reproduce, please try. Just place an order for an item with 0 stock, and it will go to "Out of stock" if "Allow qty below 0 and notify customer" is selected.
