### ISSUE TITLE
2fa on 2.4-develop

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26346]
Two-factor on 2.4. Where is it?

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Install Magento 2.4-develop
2. Try to find 2fa

### Expected result (*)

2fa support.

### Actual result (*)

No 2fa support.

**Comment by Leland** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leland. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leland, here is your [Magento instance](https://i-26346-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26346-2-4-develop.instances.magento-community.engineering/admin](https://i-26346-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Foxtrot** [comment]
Hello, @Zyles.
Currently, Magento Two-Factor Authentication (2FA) is not bundled out-of-the-box in the Magento 2 GitHub repository. But you can get it in [MSP TwoFactorAuth repository](https://github.com/magento/magespecialist_TwoFactorAuth). Please refer to its README.md for the installation instructions.
