### ISSUE TITLE
404 page when opening import page.

### ISSUE THREAD

**Issue by LucasEasy** [magento/magento2#26347]
When i trie to open the import page a 404 error appears.

I work on a plesk server with magento version 2.1.0

Steps i take: system>Data Transfer>Import>404 page error

Expected result is the import page where i can choose what i want to import.

Actual result is a 404 error page

![error 404 pn](https://user-images.githubusercontent.com/58982864/72157923-52d6da00-33b9-11ea-8157-dbcba3ba8a22.PNG)

**Comment by krishprakash** [comment]
Hi @LucasEasy.
Magento GitHub issue tracker is intended for Magento core issues only.
Please connect community forum or Magento stack exchange to discuss about this
Thanks
