### ISSUE TITLE
DevOps / CI: Lack of information about Functional Tests generation failure

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26349]
### Preconditions (*)
1. Pull Request created to one of Magento repositories
2. Syntax error or Reference error in MFTF Test

### Steps to reproduce (*)
1. Cause XML syntax error in one of Action Groups
2. Create Pull Request to `magento/magento2` repository

### Expected result (*)
1. Functional Tests fail and there's information provided about the error happened.

**OR**

1. Functional Tests fail and Unit Tests report failure.

#### Source of Error Message
Using `STDERR` from `vendor/bin/mftf generate:tests -r` command.
![image](https://user-images.githubusercontent.com/1639941/72193200-a91f3980-3408-11ea-9497-6114642def46.png)

### Actual result (*)
1. ![image](https://user-images.githubusercontent.com/1639941/72193164-84c35d00-3408-11ea-995d-c31e2ad1465b.png)

### Example
* https://github.com/magento/partners-magento2ee/pull/119/checks?check_run_id=381348090

**Comment by DanielRuf** [comment]
That's my main problem. We don't see what happens in the background. Only the final report is provided.

**Comment by engcom-Echo** [comment]
Hi, @lbajsarowicz. Thank you for your report.
So there really are such issues. Work is underway on these issues.
Example: https://github.com/magento/magento2/pull/25622

Can we close your issue? Thank you collaboration!

**Comment by lbajsarowicz** [comment]
PR you referred is completely unrelated.
I'm not sure if I get your point 😕

**Comment by sivaschenko** [comment]
@lbajsarowicz thanks for reporting this issue, `Console Error logs` have been added to the test results to handle it. See the test PR: https://github.com/magento/magento2/pull/31029
