### ISSUE TITLE
Full Page Cache expires after 12 hours

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26341]
### Preconditions (*)

1. Magento 2.3.3 & 2.4-develop
2. Varnish 6.2 with default VCL supplied by Magento 2.3.3 with TTL for public content set for 1 week.
3. SSL enabled
4. Nginx with default nginx configuration  file supplied by Magento 
### Steps to reproduce (*)

1. Visit a category page or product so that it enters the cache.
2. Note down TTFB with and without cache(In my case it was 70 ms with cache hit and 800 ms without cache)
2. After 12 hours or next day visit the same page and you will that the TTFB is 800 ms even though the cache hasn't been flushed.

### Expected result (*)

1. Page to remain in cache

### Actual result (*)

1. Page is not in cache

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30648` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by robolmos** [comment]
@monotheist Out of curiosity, how did you override the default TTL?

**Comment by monotheist** [comment]
@robolmos From the magento admin. See below please.
![Screenshot 2020-02-12 at 11 23 29 AM](https://user-images.githubusercontent.com/16968205/74306969-20d6e000-4d8a-11ea-885d-3a9e9beee1b5.jpg)

**Comment by sdzhepa** [comment]
Based on previous comment https://github.com/magento/magento2/issues/26341#issuecomment-585042767
it seems configuration issue
