### ISSUE TITLE
Products in stock in the admin but out of stock on the frontend

### ISSUE THREAD

**Issue by jamie-selesti** [magento/magento2#26340]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.3

### Steps to reproduce (*)

1. Go to a simple product which belongs to a configurable product
2. Check the stock status
3. Go to the frontend and check if simple product option is shown

### Expected result (*)

1. Product to be shown in the configurable dropdown in the frontend as it's marked in stock in the admin. Below are screenshots of the admin 
![image](https://user-images.githubusercontent.com/1398649/72138332-89dec880-3384-11ea-8161-406fbf420d2e.png)
![image](https://user-images.githubusercontent.com/1398649/72138368-96fbb780-3384-11ea-978c-08e4daa77d0f.png)

### Actual result (*)

1.  The product does not show on the frontend
2. If I run the query
 `SELECT * FROM cataloginventory_stock_item WHERE product_id = '9346');`
 I get
![image](https://user-images.githubusercontent.com/1398649/72138058-de357880-3383-11ea-95dd-6d7b5164f4be.png)
3. If I run the query 
`SELECT * FROM cataloginventory_stock_status WHERE (product_id = '9346');` 
I get 
![image](https://user-images.githubusercontent.com/1398649/72138158-189f1580-3384-11ea-82c9-450b4279e798.png)
4. Therefore it looks as though the item is in stock in the admin but in the database, it looks as though it's out of stock

**Comment by samikshakrish** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish, here is your [Magento instance](https://i-26340-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26340-2-4-develop.instances.magento-community.engineering/admin_bb81](https://i-26340-2-4-develop.instances.magento-community.engineering/admin_bb81)
Login: `7559990c` Password: `a7a1b795c679`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @jamie-selesti 

Thank you for your report 

I have just rechecked this on Magento 2.4-develop with Sample Data
I used, for example, the product _Chaz Kangeroo Hoodie-XL-Orange_ which is a simple product, part of a Configurable.
![id_67_product_grid](https://user-images.githubusercontent.com/51680745/77430599-1aee0900-6de4-11ea-9b47-5738eb63ba92.png)

The settings are the same as on the screenshots you've attached 
![id_67_product](https://user-images.githubusercontent.com/51680745/77430614-20e3ea00-6de4-11ea-8d45-422b7f10265e.png)
Advanced Inventory 
![id_67_product_advanced inventory](https://user-images.githubusercontent.com/51680745/77430625-25a89e00-6de4-11ea-8995-c0bf21651f8a.png)

The Stock status, in the database, does always display the correct status. **1** - if the product is **In Stock**, **0** - if the product is **Out-of Stock**
![id_67_product_db](https://user-images.githubusercontent.com/51680745/77430953-a5cf0380-6de4-11ea-9cdc-2e9d9762179f.png)

Can you please help us by answering the following questions:
- does this happen with this particular product on your instance or on several?
- Are you using MSI Module?

Thank you in advance

**Comment by krishprakash** [comment]
Hello @jamie-selesti
Closing this ticket due to inactivity 
Feel free to reopen/comment with reproducible steps 
Thanks!!

**Comment by RonakParmar** [comment]
I have same issue in Magento Adobe Commerce ver. 2.4.5-p7. 

Does this happen with this particular product on your instance or on several?
--> Mostly every configurable products have this issue.

Are you using MSI Module?
--> Yes, we are using the MSI modules. 


Can anyone help to resolve this issue?

**Comment by RonakParmar** [comment]
@krishprakash  Please open this issue so other can check and work on it.
