### ISSUE TITLE
Urgent: Unable to send emails using SMTP in Magento 2.3.3

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26352]
It is not possible to send email in 2.3.3 using SMTP.

**DO NOT BOTHER TESTING ON 2.4-develop**

This **NEEDS** to be fixed on 2.3.3.

### Preconditions (*)

1. Magento 2.3.3
2. Postfix 3.3.0

### Steps to reproduce (*)

1. Install Magento 2.3.3
2. Apply backward patch for email `EmailMessageInterface_2.3.3_backward_compatibility_github-2019-10-14-03-45-36.patch`
3. Place new order

### Expected result (*)

Working order email.

### Actual result (*)

Unable to send working order emails.

Error in `/var/log/mail.log`:
`postfix/smtp[11536]: 2D38248AE42: to=<my@email.com>, relay=email-smtp.eu-west-1.amazonaws.com[63.34.216.252]:587, delay=0.82, delays=0.02/0.02/0.4/0.38, dsn=5.0.0, status=bounced (host email-smtp.eu-west-1.amazonaws.com[63.34.216.252] said: 554 Transaction failed: Expected disposition, got = (in reply to end of DATA command))`

**Comment by Zyles** [comment]
Applied patch:
https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6

Removes the `Expected disposition, got` error.

But now the order emails are garbled and unreadable with content:

`=0A= =0A=0A=0A=0A=0A`

**Comment by Zyles** [comment]
Found the issue. The problem after patching the bugs is the `Mageplaza_PdfInvoice` module.

**Comment by rejoe** [comment]
Please share the patch applied in the Mageplaza_PdfInvoice module

**Comment by Zyles** [comment]
> Please share the patch applied in the Mageplaza_PdfInvoice module

Email their support.

**Comment by rejoe** [comment]
We are not using there module but we have implemented a PDF attachment functionality in a custom email, which triggers after place order. Now the order emails are not generating. Getting the following error in maillog  status=bounced (host email-smtp.us-east-1.amazonaws.com[3.226.108.202] said: 554 Transaction failed: Expected disposition, got = (in reply to end of DATA command)) 
We are using Magento version 2.3.4.

**Comment by Zyles** [comment]
https://github.com/mageplaza/magento-2-smtp/issues/199#issuecomment-572391180

**Comment by bscbodyscience** [comment]
I am getting the same error on Magento 2.3.4 . I am not using any mentioned modules.

**Comment by bscbodyscience** [comment]
@rejoe Did u manage to solve this?
