### ISSUE TITLE
Paypal Payments Pro on Mobile redirect to homepage on payment success

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#26351]
I have only recorded this issue when placing orders on iPhone (may be other mobile devices). Desktop browsers have the correct result. Can be reproduced using chrome desktop browser with iPhone X emulation enabled. 

I have replicated the issue on a clean Magento 2.3.3 install 

### Preconditions (*)

1. Magento 2.3.3 
2. Safari or Chrome browser (latest) on iPhone
3. Merchant Country UK
4. Website Payments Pro Hosted Solution payment method
5. 3D Secure enabled
6. Order value £0.40 for test purpose

### Steps to reproduce (*)

1 Browse to website on mobile device (tested on iPhone X). 
2. Add item to cart checkout as guest - Order value £0.40 for test purpose
3. Place order using card method on Paypal Paymets Pro Hosted
4. Continue checkout steps including embedded 3D secure window
5. The issue occurs when a password is not required but only when you have to click 'continue' on the 3D Secure window
5. See screenshot: https://prnt.sc/qnku1k

### Expected result (*)

1. Once card details entered and clicked next
2. An embedded 3D secure window opens
3. Once click 'continue' in 3D secure window should then redirect to magento Success page on successful payment

### Actual result (*)

1. Once clicking confirm in 3D secure window
2. User is redirected to homepage rather than success page with error messgae 'Invalid Key Form Refresh page'
3. Order is still placed but customer does no reach success page

**Comment by nadroj467** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-26351-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26351-2-3-3.instances.magento-community.engineering/admin](https://i-26351-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nadroj467** [comment]
Exact same issue noted in this ticket 
https://github.com/magento/magento2/issues/19712

**Comment by ashikp** [comment]
as seen the Issue for paypal module. It's a simple bug over there. Just Replace some controller that will do the work. CSRF Function is not added those file and you must need to upgrade your paypal account to pro. update the php_input_vars: 159200
Folder Location: vendor/magento/module-paypal/Controller
replace all the file with this file download from here https://github.com/ashikp/magento2.3paypalissuefixed

**Comment by nadroj467** [comment]
@ashikp resolution solved the problem for us replacing with files suggested. This seems to be a core bug
