### ISSUE TITLE
Paypal Credit button offset by transparent PNG

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#26350]
### Preconditions (*)

1. 2.3.3, 2.4-develop

### Steps to reproduce (*)

1. Enable PP Credit in config
2. Enable In-Context Checkout Experience - set "No"

### Expected result (*)

1. Buttons render without offset

### Actual result (*)

![20200110_153843](https://user-images.githubusercontent.com/2926266/72193716-87e62b00-33bf-11ea-99a4-ecea4a619c1c.png)

![image](https://user-images.githubusercontent.com/51681435/72897308-590a7600-3d2a-11ea-8d5d-f5e833114ae7.png)

The PP Credit button is offset because a it renders a link with a transparent png after the button. The image in question is hardcoded in `vendor/magento/module-paypal/Block/Bml/Shortcut.php` line 152

This is the image: `https://www.paypalobjects.com/webstatic/en_US/btn/btn_bml_text.png`

If you visit the URL you will see that this just links to a transparent PNG.

**Comment by engcom-Echo** [comment]
Hi @MichaelThessel. Thank you for your report.

Unfortunately, I am not able to reproduce these issues.
Please specify in which area or block the buttons are incorrectly displayed.

**Comment by engcom-Echo** [comment]
Hi @MichaelThessel 
Please provide your configuration render display buttons PP.

**Comment by MichaelThessel** [comment]
```
mysql> select * from core_config_data where path like '%bml%';
+-----------+----------+----------+--------------------------------------------------+---------+---------------------+
| config_id | scope    | scope_id | path                                             | value   | updated_at          |
+-----------+----------+----------+--------------------------------------------------+---------+---------------------+
|     13383 | default  |        0 | payment/paypal_express_bml/active                | 1       | 2019-10-09 11:32:56 |
|     13384 | default  |        0 | payment/paypal_express_bml/publisher_id          | NULL    | 2019-10-09 11:32:56 |
|     13385 | default  |        0 | payment/paypal_express_bml/homepage_display      | 0       | 2019-10-09 11:32:56 |
|     13386 | default  |        0 | payment/paypal_express_bml/homepage_position     | 0       | 2019-10-09 11:32:56 |
|     13387 | default  |        0 | payment/paypal_express_bml/homepage_size         | 190x100 | 2019-10-09 11:32:56 |
|     13388 | default  |        0 | payment/paypal_express_bml/categorypage_display  | 0       | 2019-10-09 11:32:56 |
|     13389 | default  |        0 | payment/paypal_express_bml/categorypage_position | 0       | 2019-10-09 11:32:56 |
|     13390 | default  |        0 | payment/paypal_express_bml/categorypage_size     | 190x100 | 2019-10-09 11:32:56 |
|     13391 | default  |        0 | payment/paypal_express_bml/productpage_display   | 0       | 2019-10-09 11:32:56 |
|     13392 | default  |        0 | payment/paypal_express_bml/productpage_position  | 0       | 2019-10-09 11:32:56 |
|     13393 | default  |        0 | payment/paypal_express_bml/productpage_size      | 190x100 | 2019-10-09 11:32:56 |
|     13394 | default  |        0 | payment/paypal_express_bml/checkout_display      | 1       | 2019-10-09 16:32:30 |
|     13395 | default  |        0 | payment/paypal_express_bml/checkout_position     | 0       | 2019-10-09 11:32:56 |
|     13396 | default  |        0 | payment/paypal_express_bml/checkout_size         | 234x60  | 2019-10-09 11:32:56 |
|     13397 | default  |        0 | payment/payflow_express_bml/active               | 0       | 2019-10-09 11:32:56 |
|     14006 | default  |        0 | payment/wps_express_bml/active                   | 0       | 2019-10-09 11:32:56 |
|     22646 | websites |        1 | payment/payflow_express_bml/active               | 0       | 2019-10-16 06:06:59 |
|     22650 | websites |        1 | payment/wps_express_bml/active                   | 0       | 2019-10-16 06:06:59 |
|     22813 | websites |        3 | payment/payflow_express_bml/active               | 0       | 2019-10-16 06:36:11 |
|     22817 | websites |        3 | payment/wps_express_bml/active                   | 0       | 2019-10-16 06:36:11 |
+-----------+----------+----------+--------------------------------------------------+---------+---------------------+
```

**Comment by engcom-Echo** [comment]
Hi, @MichaelThessel. Thank you for your report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30652` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
