### ISSUE TITLE
Create customer's token in swagger UI not working properly

### ISSUE THREAD

**Issue by marcoaacoliveira** [magento/magento2#26356]
When trying to use Swagger UI to login you are blocked by retrieve by email step. I could reproduced that in 2.4, but I'm afraid the older versions has the same problem.

### Preconditions (*)
1. Use Swagger UI to login
2. Magento 2.4

### Steps to reproduce (*)
1. Register a customer in Magento registration form (site);
2. Try to login with that customer through swagger UI (http://yourwebsite.com/swagger);

### Expected result (*)
1. Magento creates a token for the given user;

### Actual result (*)
1. Magento doesn't find the user in the given website (swagger's website is handled as 0, the same as the admin);
2. Magento return an authentication error.

**Comment by pmclain** [comment]
@marcelo-monteiro This is possible by specify in the desired store code as a query parameter in the swagger request as documented https://devdocs.magento.com/guides/v2.3/rest/generate-local.html#generate-a-full-rest-reference-locally

`http://<magento_host>/swagger?store=<store_code>` Specifying the store code of the customer will allow the request to succeed.
