### ISSUE TITLE
often Need to css preprocessing  

### ISSUE THREAD

**Issue by kanasagraj** [magento/magento2#2635]
I am magento developer.
In magento 2.
when i change any style in less file so then its not reflect on frontend but when i generate "Preprocessed" then its work perfectly. but its take a time and developer change to often css style. so thats not a good for developer so please tell me have you any fast way for Me.

Thanks,

**Comment by zanilee** [comment]
Hi, @Kanasagra-Jaydip!

To make styles development faster, in Magento2 there are Grunt commands for styles compilation. You can find the instructions how to use them [here](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
