### ISSUE TITLE
Admin | Customers - Cant Preform action on all selected customers ( entire data )

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#26358]
### Preconditions (*)
1. Magento 2.3.1
2. php 7.2
3- Ubuntu Server 16

### Steps to reproduce (*)
1. Gog to Admin > Customers
2. Select all ( All Customers )
3- Preform any action from the drop down ( for example subscribe to mailing list )

### Expected result (*)

1. it should affect the entire selected records

### Actual result (*)

1. it will only affect the visible records ( for example if 20 of 6000 it will only affect the 20 visible ones ), to workaround this i have to view 900 customers per page and preform the action ( page by page ) until i am done with all the customers

**Comment by krishprakash** [comment]
Hi @salehawal. Issue is already fixed in latest magento.
You can review at #22004
PR #22704
