### ISSUE TITLE
 Magento 2.3.0  - After adding to cart, cart page showing empty

### ISSUE THREAD

**Issue by wajahatbashir** [magento/magento2#26369]
I'm adding products to cart page, after successfully product added, then when i check mini cart and cart pages  there are showing nothing any item. Using Magento 2.3.0

I could not found any solution, I have spend too much time on this issue but could not get any help.

![Screenshot_1](https://user-images.githubusercontent.com/11786908/72254863-ad24a480-361e-11ea-8812-7f9a3975a7b9.jpg)

**Comment by krishprakash** [comment]
Hi @wajahatbashir
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
