### ISSUE TITLE
Klarna payment fails if company is entered

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#26366]
### Preconditions (*)

1. Magento 2.3.3
2. Merchant country: DE, default country: DE, currency: EUR
3. Klarna configured and enabled (Klarna EU)
4. Klarna debug log enabled

### Steps to reproduce (*)

1. As guest, go to checkout and enter a company into shipping address form
2. Select klarna payment and place the order

### Expected result (*)

1. Order is placed successfully

### Actual result (*)

1. Order is not placed, an error message is shown "Unable to authorize this order"

In klarna debug log, the following error is logged:

```
[2020-01-13 08:43:14] klarnaDebugLogger.DEBUG: {
    "RESPONSE": {
        "is_successful": false,
        "response_status_code": 409,
        "response_status_message": "Conflict",
        "error_code": "BAD_VALUE",
        "error_messages": [
            "Not matching fields: [billing_address.organization_name, shipping_address.organization_name]"
        ],
```

**Comment by domeglic** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @domeglic, here is your [Magento instance](https://i-26366-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26366-2-3-3.instances.magento-community.engineering/admin](https://i-26366-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by domeglic** [comment]
There is no option for Klarna in the test instance so I cannot confirm it, but it is a bundled extension so this is still a Magento issue.

**Comment by sdzhepa** [comment]
Due to the response from Klaran, it is not a bug but expected behavior. Related internal jira `BUNDLE-2770` 
The filed company is not supported during guest checkout.
Also when user tries  to use it notification message is shown
![qweqweqweqweq](https://user-images.githubusercontent.com/3409584/95243758-b4a46300-07d6-11eb-8370-14e1aa779379.jpg)
