### ISSUE TITLE
Grouped Product can't add any item to cart if any other item is out of stock

### ISSUE THREAD

**Issue by tondoit** [magento/magento2#26363]
https://magento.stackexchange.com/questions/216626/grouped-product-cant-add-any-item-to-cart-if-any-other-item-is-out-of-stock

My understanding of Grouped Products is a little limited, but as I understand it, a Grouped Product is simply a listing of products that I want to show to customers on one page.

If one or more items are added to the cart from that Grouped Product, they are added as individual line items.

Why then, would I not be able to add ANY individual line items to my cart from a Grouped Product page if ANY of the listed products are out of stock?

Example: a Grouped Product with 20 individual products listed on the page - one of those listed items is out of stock. This means I am unable to add any item on that page to the cart, with the message "This product is out of stock." displayed if I try.

If I add the out of stock product into stock and then try the same process again, I can add items to the cart just fine.

Still reproducing in 2.2 and 2.3.0

**Comment by tondoit** [comment]
yes

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26363-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26363-2-4-develop.instances.magento-community.engineering/admin](https://i-26363-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @tondoit.
This is expected behavior of magento.
You can add the group product if any individual product is out of stock.
Also you can add add to cart individual product.
Refer below screencast for information:
https://www.screencast.com/t/2FhtXf6det
closing this ticket.
