### ISSUE TITLE
how to disable the Paypal Credit payment method in magento2?

### ISSUE THREAD

**Issue by ramsampathi** [magento/magento2#2636]
Hi,
Magento 2 Enabled the paypal express checkout payment method in my site  but in front end product view page,cart page,checkout payment information it  displayed paypal express checkout and Paypal credit options.How to disable the paypal credit payment method in magento2?
![paypal](https://cloud.githubusercontent.com/assets/7812791/11651465/d5259c0a-9db6-11e5-8657-56ee98fbd145.png)

Thanks,
Ram Sampathi

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
