### ISSUE TITLE
There was no Home CMS page configured or found.

### ISSUE THREAD

**Issue by Mark-Techmall** [magento/magento2#26367]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
Hi @Mark-Techmall. To move ahead verification process please update the precondition,Steps to reproduce,Actual and expected result.
And it's working fine at latest magento
![image](https://user-images.githubusercontent.com/46617848/72254376-dc8cde80-3629-11ea-981c-4aca03ec7b6c.png)
Thanks.
