### ISSUE TITLE
Unable to create widget

### ISSUE THREAD

**Issue by vpatidar009** [magento/magento2#2637]
Hello,

I am unable to create widget in admin as getting some jquery errors when select CMS page, Category etc under ' Widget Options ' tab.

![](http://s3.amazonaws.com/awesome_screenshot/9182699?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1449632327&Signature=3qL6n06eov0GABn%2BVsSZupPI81s%3D)

**Comment by davidalger** [comment]
@vpatidar009 The screenshot you gave only shows the form validation issue, not the jquery errors you reference. Could you post details on what jQuery errors you are getting along with a note on how to reproduce them?

**Comment by vpatidar009** [comment]
Hello David,

Please watch the video, I hope It will clear everything.
[out.ogv.zip](https://github.com/magento/magento2/files/59411/out.ogv.zip)

Thanks

**Comment by vkholoshenko** [comment]
@vpatidar009, could you please confirm that the issue still reproduces on stable 2.0.0 ?

**Comment by davidalger** [comment]
@vpatidar009 I cannot reproduce the issue in an M2 stable 2.0.0 install with sample data. The UI functions and allows me to select the category just fine. Can you confirm the version you're running on is stable 2.0.0 and also open the inspector and post the actual JS errors here so we can see what's going awry?

**Comment by vpatidar009** [comment]
Hello Guys,

Sorry for delay.

I have download magento from here http://awesomescreenshot.com/05b5hogbd7 .

Console's screenshot attached
![console-screenshot](https://cloud.githubusercontent.com/assets/16207791/11866165/3403c62e-a4cf-11e5-9126-b61314bfc88d.png)

Thanks,
Vishal

**Comment by davidalger** [comment]
@vpatidar009 Thanks for that screenshot! The info there shows the static asset URLs are including `pub` when the site not have that in the URL. I believe this is the same issue as #2711. I'm going to try creating a reproducible test case causing `pub` to be wrongly included in the URLs built in the admin.

**Comment by davidalger** [comment]
Oh…one thing you might try for now…install the site directly on the IP / hostname vs in a sub-directory. I.e. so it doesn't have `ashishmagento2` in the URL. It may help.

**Comment by vpatidar009** [comment]
Ok, let me install the site directly on the IP / hostname.

Thanks,
Vishal

**Comment by vpatidar009** [comment]
Ok, let me install the site directly on the IP / hostname.

Thanks,
Vishal

**Comment by vkholoshenko** [comment]
Hi, @vpatidar009! Do you have any updates?

**Comment by davidalger** [comment]
Closing as duplicate of #2711 and lack of response from OP
