### ISSUE TITLE
UNABLE TO CHANGE QUANTITY FROM BACKEND. receiving error Tier prices data should be array, but actually other type is received

### ISSUE THREAD

**Issue by sunbeamshawls** [magento/magento2#26379]
### Preconditions (*)

1. magento 2.3.3
2. Different price tier for wholesale customers 

### Steps to reproduce (*)
1. catalog>product>select the product
2. trying to change the quantity but facing error Tier prices data should be array, but actually other type is received

### Expected result (*)
1. Quantity should be updated when i click save button from the backend

### Actual result (*)
1. not able to save as it shows error "Tier prices data should be array, but actually other type is received" 
![tier prices data error](https://user-images.githubusercontent.com/53515140/72337301-5be0e780-36e8-11ea-80a2-b1b1f6e7f022.png)

**Comment by sunbeamshawls** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunbeamshawls. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunbeamshawls, here is your [Magento instance](https://i-26379-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26379-2-4-develop.instances.magento-community.engineering/admin](https://i-26379-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26379-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26379-2-4-develop.instances.magento-community.engineering/admin](https://i-26379-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26379-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26379-2-3-3.instances.magento-community.engineering/admin](https://i-26379-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hello @sunbeamshawls , I checked this issue at magento 2.4-develop instance as well as on magento 2.3.3 instance but not able to reproduce this issue. It seems it is coming on your local instance due some customisations .. Please check at your end also if you still able to reproduce this issue on any of the step please update here.

**Comment by arvin-narvaez** [comment]
i get same issue can you give me updates for this issue thanks

**Comment by arvin-narvaez** [comment]
@magento-cicd3 i got same issue please give me 2.3.3 instance

**Comment by PSalvatore** [comment]
As identified in this related issue https://github.com/magento/magento2/issues/21738, the error can be replicated by adding a row to the `catalog_product_entity_decimal` table like so:
`INSERT INTO catalog_product_entity_decimal (attribute_id, store_id, row_id, value) VALUES (279, 0, 1224, 45.00);`

The `attribute_id` here corresponds to "tier_prices" attribute_id which can be found by: 
`SELECT * FROM eav_attribute WHERE attribute_code = 'tier_price';`

The `row_id`  here corresponds to the row_id of the product you want to introduce the error for. This can be found by doing a lookup of the SKU in the `catalog_product_entity` table


It is not clear to me what the purpose of the `catalog_product_entity_decimal` table is or what causes rows to be added to it, but technically speaking you can remove the entries from this table with the row_ids that correspond to the affected products and it will relieve the issue for that product. Although I don't recommend using this method unless you understand what the `catalog_product_entity_decimal` table is for. Hopefully someone that knows can shed some light on that
