### ISSUE TITLE
Default order template results in blank email body in latest Thunderbird 68.0

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#26373]
### Preconditions (*)

1. Magento 2.3.3
2. Thunderbird 68.0
3. Default email templates

### Steps to reproduce (*)

1. Complete an order and attempt to read the email with Thunderbird 68.0

### Expected result (*)

1. Usual thanks for the order email

### Actual result (*)

1. Email appears with a blank body and email.html as an attachment

The default email template appears to have issues with the "Textual attachments not being displayed inline" change. I can adjust this setting for my edition of Thunderbird by going to : Tools/Options/Advanced/General/Config. editor and then changing preference mail.inline_attachments.text 
The email will then display correctly.

[Thunderbird 68.0 release notes](https://www.thunderbird.net/en-US/thunderbird/68.0/releasenotes/) note the change to Textual attachments.

I am concerned by what the customers might get though, it would be better to get a email template that would read normally without this issue. It might also start to be a factor for other email clients.

**Comment by gwharton** [comment]
Pretty sure this has been fixed in latest codebase by removing content disposition: inline header.

**Comment by devchris79** [comment]
@gwharton Thanks I will give that a try, it may be that the template has been inherited from older versions.

**Comment by gwharton** [comment]
The fix is in the codebase, not the templates. I can post link later but currently mobile.

**Comment by devchris79** [comment]
Thanks @gwharton I think I found the issue #25076, now applying the header fix.
