### ISSUE TITLE
Magento\Framework\DataObject::__call() - print_r() is dangerous

### ISSUE THREAD

**Issue by josephmcdermott** [magento/magento2#2638]
This method throws an exception on failure:

```
new \Magento\Framework\Phrase('Invalid method %1::%2(%3)', [get_class($this), $method, print_r($args, 1)])
```

If the $args array contains an object / objects, this will consume a huge amount of memory (to the point it kills my instance locally). For example I discovered this whilst attempting to call a method which did not exist and passed a Product instance as an argument.

**Comment by shiftedreality** [comment]
Hi @josephmcdermott 

Thank you for pointing this issue. I created internal ticket MAGETWO-47881

**Comment by vzabaznov** [comment]
Hi @josephmcdermott , issue was closed and delivered, please check the fresh magento version
