### ISSUE TITLE
Magento2: Checkout shipping address validation not working in step1

### ISSUE THREAD

**Issue by sudheers-kensium** [magento/magento2#26385]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a new Customer with default sipping/billing addresses in address book
2. Go to My Account > Address Book
3. Add an default address without country
4. Go to Admin -> Stores -> Configuration -> Customers -> Customer Configurations -> Name And Address Options -> Show Company Set to Required and Save
5. Add product to cart and go to checkout 
6. select shipping method
7. Click NEXT button 

### Expected result (*)

1. Error message should be display "Company is required "and stop moving to Step2. 

### Actual result (*)

1. Error message not displaying and moving to Step2. 
2. When we click on Place Order button error message is showing "Please check shipping address information".

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26385-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26385-2-4-develop.instances.magento-community.engineering/admin](https://i-26385-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30411` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Zyles** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Zyles, here is your [Magento instance](https://i-26385-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26385-2-4-develop.instances.magento-community.engineering/admin](https://i-26385-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
We ran into a similar issue. I'm attaching the patch we have in place for this issue. It may or may not be the best solution...
[fix-checkout-form-validation.txt](https://github.com/magento/magento2/files/4060889/fix-checkout-form-validation.txt)

**Comment by KrishnaK-Z** [comment]
@sudheers-kensium Try to validate quote before saving the address in saveAddressInformation method (this is an API call made while clicking the "NEXT" button). Works for me.

Try the following,

`submitQuoteValidator->validateQuote($quote)`
So, while clicking the next button in the first step you will be getting the expected error message

> Please check the shipping address information. "company" is required. Enter and try again.

But even after editing the address by adding the company field in the address book, i.e., the address associated with the quote. We are not allowed to proceed to checkout.

You can see it in the database.
`SELECT * FROM `quote_address` WHERE email like "%<email>%"`
here you can see the company field is NULL.

Note: But, the solution u asked for, i.e., to display error msg in 1st step can be done as earlier mentioned.
