### ISSUE TITLE
MSI: assignStatusToProduct for multi stocks is getting the wrong stock id

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#26387]
Hello,

I found this problem when I was working on magento EE. I know this github is for CE but I don't where to post this. Maybe someone could move this topic on the right place.

### Preconditions (*)

1. magento/project-enterprise-edition 2.3.0
2.

### Steps to reproduce (*)

1. Enable multi stocks
2. Set quantity from product to stock A = 0 and stock B = 10
3. Store 1 should use stock A and Store 2 should use stock B
2. Create a product from an order item
2. Set product store id from order store id which was stock B
3. Check isSalable 

```
  $product = $this->_objectManager->create(Product::class)
                    ->setStoreId($order->getStoreId())
                    ->load($orderItem->getProductId());

                if ($product->isSalable()) {
                    $unavailableProducts[] = $orderItem->getSku();
                }
```

### Expected result (*)

1. isSalable should return true

### Actual result (*)

1. isSalable is false
2. Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php is looking for stock id of current website which is not the website from the product.

So product availability in admin is calculate upon wrong website.

**Comment by lbajsarowicz** [comment]
As far as I know - Inventory (former MSI) is a part of Magento Community.

**Comment by vahir2016** [comment]
Hello lbajsarowicz,

I didn't find the file "vendor/magento/module-inventory-catalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php" in magento2 github. I also checked magento/inventory github.

Then, I tried to find from which module the file depends. I looked in composer.lock trying to find which one was required and it leads me to "magento/project-enterprise-edition". So I thought it was EE but also I thought MSI is a part of Magento Community so I don't know ?

**Comment by lbajsarowicz** [comment]
Is that what you are looking for?
https://github.com/magento/inventory/blob/1.2-develop/InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php

**Comment by vahir2016** [comment]
I guess it is ! Thanks you !

Should I close this topic and open a new one in magenot inventory github ?

**Comment by lbajsarowicz** [comment]
I think it's good idea! :-)

**Comment by vahir2016** [comment]
Move this topic to magento inventory github.
