### ISSUE TITLE
Security issue: exposed admin url by going to {{base_url}}/0

### ISSUE THREAD

**Issue by willtran** [magento/magento2#26382]
### Preconditions (*)
1. Magento 2.3, 2.4-develop

### Steps to reproduce (*)
1. On any version of Magento, configure the following:
2. admin/url/use_custom_path = 1
3. admin/url/custom_path to any value (valid url)
4. Navigate to site url /0 ( https://www.example.com/0 )

### Expected result (*)
1. 404 page

### Actual result (*)
1. 302 Redirect to admin/url/custom_path

### More info:
If `admin/url/use_custom_path` is not set, instead of 404 page, the homepage will be show

**Comment by willtran** [comment]
Cause of the problem:

\Magento\Framework\App\AreaList::getCodeByFrontName is responsible for setting area.

```

On line 73 it makes a call to \Magento\Backend\App\Area\FrontNameResolver::getFrontName
This function will return false if the condition described above is met (see \Magento\Backend\App\Area\FrontNameResolver::isHostBackend)

**false** is then compared to **0** and return true at line 75 \Magento\Framework\App\AreaList:

```
if ($areaInfo['frontName'] == $frontName) {
                return $areaCode;
            }
```

This result in adminhtml area being selected and redirect to the login page. (see \Magento\Backend\Model\AdminPathConfig::getDefaultPath)

If the configuration for customer admin url is not set, the area code set to frontend (by default). Then the homepage will be show (see \Magento\Store\Model\PathConfig::getDefaultPath) which is not correct but is a different issue.

**Comment by DanielRuf** [comment]
Please responsibly report this to the relevant people, not in the public issue tracker. Please send an email to securityinfo@magento.com.
