### ISSUE TITLE
Watermark is breaking product page when size is not set

### ISSUE THREAD

**Issue by paliarush** [magento/magento2#26389]
### Preconditions

1. Simple product is available on the storefront

### Steps to reproduce

1. Navigate to theme configuration in `Content -> Design -> Configuration -> <some theme> -> Product Image Watermarks`
2. Upload a new watermark. Specify opacity and DO NOT specify Image size
   
![image](https://user-images.githubusercontent.com/10828073/72382368-bd9c5400-36de-11ea-9e7c-31e446a9b9c0.png)

3. Save configuration, clear caches
4. Navigate to product page (within the same theme that was used for watermarks)

### Expected result

1. Product page is displayed with no errors

### Actual result

1. Fatal error: `TypeError: explode() expects parameter 2 to be string, null given`
2. Cause of the error seems to be due to the change https://github.com/magento/magento2/pull/25528:
![image](https://user-images.githubusercontent.com/10828073/72382536-153abf80-36df-11ea-8228-a899c3b69fe5.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26389-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26389-2-4-develop.instances.magento-community.engineering/admin_bd87](https://i-26389-2-4-develop.instances.magento-community.engineering/admin_bd87)
Login: `0bc48df7` Password: `f4b79ecea90b`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30484` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by folektoras** [comment]
@magento-engcom-team @paliarush this issue is resolved already in the 2.4-develop branch. As you can see here a (string) cast is added.

![Screenshot 2020-01-30 at 11 36 02](https://user-images.githubusercontent.com/25661926/73446542-df3f4180-4354-11ea-9dd8-ad6c01694539.png)
