### ISSUE TITLE
Cannot run PHPUnit in 2.3.3 due to Mcrypt deprecation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26380]
Attempting to run PHPUnit under Magento 2.3.3 on PHP 7.1.33 and I get

`PHPUnit\Framework\Exception: Deprecated: Function mcrypt_module_open() is deprecated in /var/www/src/public/vendor/magento/framework/Encryption/Adapter/Mcrypt.php:55.`

In Mcrypt.php, the mcrypt functions are prepended already with the error suppressor.

I tried adding `error_reporting(E_ALL & ~E_DEPRECATED);` into the PHPUnit bootstrap file, but it had no effect.

**Comment by engcom-Echo** [comment]
HI, @paul-gene. Thank you for your report.
Unfortunately, I could not reproduce this behavior.
Example:
![image](https://user-images.githubusercontent.com/51681435/72504800-38807e80-3847-11ea-97e4-74ba8d645f33.png)

Most likely this is due to the settings of your PНP.
Thanks for your collaboration!

**Comment by ghost** [comment]
@engcom-Echo what version of PHP did you use?

**Comment by engcom-Echo** [comment]
> @engcom-Echo what version of PHP did you use?

PHP 7.1.33

**Comment by ghost** [comment]
1. Make a dummy module
2. Create an integration test (simple `assertTrue()`)
3. Run PHPUnit using the `phpunit.xml.dist` config from `dev/tests/integration`

**Comment by engcom-Echo** [comment]
Hi @paul-gene.

I did for your case, tests run is Ok.
![image](https://user-images.githubusercontent.com/51681435/72526707-b22c6280-386f-11ea-8de7-d02d36d8cf6f.png)
![image](https://user-images.githubusercontent.com/51681435/72526715-b8bada00-386f-11ea-8f7e-0a956bd555a3.png)

**Comment by ghost** [comment]
@engcom-Echo and that's from a fresh, stock 2.3.3 install?

I got the error on a fresh, stock 2.3.3 install, and I know the mcrypt library has been an issue with PHP 7.1.x.

Why would I get the error, but you aren't?

**Comment by engcom-Echo** [comment]
Hi, @paul-gene thank you for your report, this issue has already fixed in 2.4-develop branch and 2.3-develop branch.
https://github.com/magento/magento2/issues/5880

**Comment by ghost** [comment]
@engcom-Echo so there is an issue?!

The 2.3-develop branch doesn't exist anymore.

Seeing as 2.3.3 does in fact support PHP 7.1, this needs to be addressed for 2.3.x

**Comment by engcom-Golf** [comment]
Hi @paul-gene thank you for you report, magento 2.3.3 and the closed 2.3-branch not support php 7.1, https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html 
```
Supported PHP versions:

~7.2.0

~7.3.0
```

You could use php 7.2 as well to run tests, feel free to reopen if issue is still exist even if you would use php 72

**Comment by paul-gene** [comment]
@engcom-Golf sorry, but you are mistaken.

2.3.3 **does** support PHP 7.1 https://github.com/magento/magento2/blob/2.3.3/composer.json

**Comment by engcom-Golf** [comment]
@paul-gene what is PHPUnit version you used ?

**Comment by paul-gene** [comment]
> @paul-gene what is PHPUnit version you used ?

The one included in 2.3.3, https://github.com/magento/magento2/blob/2.3.3/composer.json#L94

**Comment by engcom-Golf** [comment]
@paul-gene problem that you have, occurs because your php.ini allow to show deprecated errors,
![DeepinScreenshot_select-area_20200225165307](https://user-images.githubusercontent.com/51681547/75258448-20f5c780-57ef-11ea-84fc-1d32ac09b6aa.png)
You can change this setting like in screen above, but i'm afraid that this never be fixed as 2.3-develop branch was deleted, so this issue can appear here for a years.

**Comment by engcom-Golf** [comment]
@paul-gene so can we close this one ?

**Comment by engcom-Golf** [comment]
i'm closing this one as, problem related with php.ini configuration, and there is nothing to fix in magento code.
