### ISSUE TITLE
Catalog Prices incl. Tax results wrong item prices with Custom Price

### ISSUE THREAD

**Issue by seppoviuh** [magento/magento2#26394]
### Preconditions (*)

1.  Install Magento 2.3.3 with sample data
2.  Set Tax-> Calculation Settings-> Catalog Prices-> Including Tax
3.  Set Tax-> Shopping Cart Display Settings-> Display Prices-> Incl. & Excl. Tax

### Steps to reproduce (*)

1. Go to the backend
2. Sales-> Orders-> Create New Order
3. Select customer with tax ( Veronica Costello)
4. Add Product with tax (Wayfarer Messenger Bag)
5) Tick the Custom Price checkbox and add an amount 48.71
![image](https://user-images.githubusercontent.com/39083752/72417249-c2ade180-3778-11ea-9a2a-88ba955c8eba.png)
6) Press the Update Items And Quantities

### Expected result (*)
1. Price Incl. Tax: €48.71
2. Price Excl. Tax: €45.00

### Actual result (*)
1. Price Incl. Tax: €52.73
2. Price Excl. Tax: €48.71
 ![image](https://user-images.githubusercontent.com/39083752/72418151-985d2380-377a-11ea-80b9-dd356fc04e55.png)

This issue will lead to wrong order totals.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30483` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by daancart2quote** [comment]
Also the tax setting: `Calculation Settings > Apply Tax On > Custom price if available` is not respected. 
I can't find when this issue is introduced, but I'd guess it is in 2.3.2.

**Comment by magento-engcom-team** [comment]
Hi @seppoviuh. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30483` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
