### ISSUE TITLE
Unable to create table with name more than 64 characters long using db_schema

### ISSUE THREAD

**Issue by galanis-a** [magento/magento2#26404]
### Preconditions (*)
1. Magento 2.3.3 & 2.4-develop
2. PHP 7.2.26

### Steps to reproduce (*)
1. Create a new Magento 2 module
2. Create db_schema.xml in Vendor/Module/etc folder
3. In db_schema.xml declare a table with name more than 64 characters long

### Expected result (*)
1. setup:upgrade command should finish successfully and create the new table

### Actual result (*)
1. This error is thrown and the new table is not created
![image](https://user-images.githubusercontent.com/6358839/72449916-201a5080-37c2-11ea-8769-55e27e4d7941.png)

The issue is in \Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder line 251 when it tries to get the table name \Magento\Framework\Setup\Declaration\Schema\Dto\Schema "passes" the table from \Magento\Framework\DB\ExpressionConverter::shortenEntityName and the table name is shorten. But in SchemaBuilder when the table is create and added to the $tables array its added with the full name in result not being to find a table with the short name returned from Schema class.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30477` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by periwalbhanu** [comment]
Hi @galanis-a 
I have created this issue at my end using the provided steps by you. As per my findings, MySQL does not allow you to create table with name more than 64 characters. 

![identifiers_limit](https://user-images.githubusercontent.com/51773732/72661368-07e34500-39ff-11ea-9176-017264fccd41.png)

**Comment by periwalbhanu** [comment]
Hi @galanis-a
I have created this issue at my end using the provided steps by you. As per my findings, MySQL does not allow you to create a table with name more than 64 characters.

![identifiers_limit](https://user-images.githubusercontent.com/51773732/72661436-036b5c00-3a00-11ea-9dc8-6d166f97d694.png)

**Comment by galanis-a** [comment]
Hi @periwalbhanu sorry for my late response.
I am aware of the MySQL limitation you mention and that's not the issue i am reporting.

The issue is that before db_schema.xml, when you created a mysql table and its name had more than 64 characters Magento was handling it correctly and shorten the name to be able to create the table and reference it correctly. Now with db_schema.xml it doesn't and setup:upgrade command fails.

Please check my initial report for more info about the issue.

Best.
