### ISSUE TITLE
Default themes in Magento2 CE contain EE styling

### ISSUE THREAD

**Issue by ivanweiler** [magento/magento2#2640]
Hello all,

Blank and Luma theme in Magento 2.0.0. CE include some styling from EE modules, for example:
https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/luma/Magento_Rma/web/css/source/_module.less

From commit it seems it's some kind of fix for EE https://github.com/magento/magento2/commit/2d189deb01d58025204dd926520705fa273a3a2c 
but now generated css files in CE contain styling that is never used :(

Regards, Ivan

**Comment by alankent** [comment]
This one deserves a blog post - there is a reason why, but I also would love feedback/ideas on how to make it better. I will try to get a blog post up and post the link here "shortly".

**Comment by davidalger** [comment]
@alankent I'd be curious to hear the why behind this one as well. It seems rather odd and feels that surely there's got to be _some_ way, right? But I think I may know the reason behind it without even asking. Maybe EE should ship with a coupe themes which use the CE themes as parent so it can have working theme examples in addition to the core module css? :)

**Comment by alankent** [comment]
I have written up some things and ideas in this area on my blog at http://alankent.me/2015/12/09/even-better-themes-for-magento-2-seeking-feedback/ - in summary, putting some of the EE styles into Luma was the less evil solution, until we get a little more functionality into themes. Feedback welcome!

**Comment by maksek** [comment]
Hi @ivanweiler, do you want keep the topic or we are ok to close it?

**Comment by ivanweiler** [comment]
Hello Max,

It's not really solved since unneeded styling is still part of CE, now we only know why it is there (mentioned less evil solution) :) I don't know if something is changed in latest commits, but I see that EE less files are still in CE themes, so they're most likely still compiled in final CE css.

If it's not doable at this point maybe this should be feature request or similar, since it should be solved on the long run. Number of EE modules is growing, so eventually there will be more and more unused css in CE.

Regards, Ivan

**Comment by tomislavbilic** [comment]
Issue of "removing unnecessary styling" should not, by all means, fit into "undoable" category. :)

**Comment by pboisvert** [comment]
Chuck--passing this one to you as unused code though small is a performance issue especiqlly if it grows over time.

**Comment by MomotenkoNatalia** [comment]
Hi all!

We have an internal ticket regarding this problem - MAGETWO-62161.

**Comment by magento-engcom-team** [comment]
@ivanweiler, thank you for your report.
We've created internal ticket(s) MAGETWO-62161 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @ivanweiler thank you for your report. Reported issue does not affect product functionality. But this is good improvement to have. We are closing the issue for now, but feel free submit a pull request with improvement
