### ISSUE TITLE
Bundle Product Including Simple products with special price or tier pricing showing incorrect price. 

### ISSUE THREAD

**Issue by alxanthony** [magento/magento2#26408]
When creating and order in the admin, if you add a bundle product that includes a simple product and the simple product has a tier price or special price set up.  and then click on the configure button the price doubles and there is no way to go back to the original price. and if you keep clicking on the configure button and close the pop up that opens up,  the price just  keeps increasing. 

This also happens in the front end. when you are in the cart and click the edit button on the bundle product. but it's easier to replicate in the backend. 

Expected Result: No price changes if closing the box without adding quantities. 

### Preconditions (*)

Magento 2.3.3 (Vanilla installation no third party modules installed. )
Php 7.3
Ubuntu 18.04 LTS
NGINX
Mysql

### Steps to reproduce (*)

1. Create a simple product,  add price  and special price for it. 
2. Create a bundle product
3. Add  the simple product to the bundle product. 
4. Create New Order
5.- Add bundle product to Order
6.  Click  on the configure button under the product name. 
7. close the configure button
8,  price went up and  it shouldn't  have.  and now there  is no way to go back to the original price unless you delete the product from the cart. and add it again. 

### Expected result (*)

1. [Screenshots, logs or description]
2. if just closing the configure popup, nothing should happen no price changes.
3. If adding a qty in the configure screen the price should increment by that qty not just increase the whole bundle price 
4. if you select qty 1 the bundle should go back to the original price and it  doesn't
5.- everything works great as long as there is no  special price on the simple product. 
### Actual result (*)

1. [Screenshots, logs or description]
2. Instead when you close the box the price doubles for no reason.
3. And no matter what quantities you put in there the price just keeps going up everytime you open and close the pop up of configure

**Comment by ptomi** [comment]
@magento I am working on it

**Comment by alxanthony** [comment]
We hired an independent developer for this issue and he was able to provide a patch that fixed the issue, we tested a few different scenarios and everything seemed to work, we didn't do extensive testing so you might want to run a few more test scenarios before considering this as fixed or using the patch.  But if anybody else is having this problem (which since it's a core bug we assume everybody does) I'm attaching the patch provided that fixed it on Magento CE 2.3.2 nd 2.3.3 
[magento_module_quote_model_quote.patch.txt](https://github.com/magento/magento2/files/4104364/magento_module_quote_model_quote.patch.txt)

**Comment by engcom-Bravo** [comment]
Hello @alxanthony 

Thank you for your report and for your contribution

I have rechecked this on Magento 2.4-develop and it seems to be fixed 
![special price](https://user-images.githubusercontent.com/51680745/75880879-ca0f7400-5e26-11ea-8167-6b07a1d64632.gif)

Please correct my steps if I performed incorrect steps for reproducing  

If the issue is not reproducible on 2.4-develop, it will be closed 

Thank you in Advance
