### ISSUE TITLE
Unable to create RMA's for Orders with Bundle products

### ISSUE THREAD

**Issue by andyvr** [magento/magento2#2642]
Below is the issue I'm having when I create a return for an order with a Bundle product.
Steps I'm taking:
1. I have an order with just one bundle product that has 2 child (simple) products. The bundle product is set to "Ship Bundle Items: Together" (Products -> Catalog -> Edit (a product) -> Product Details -> Ship Bundle Items).
   ![screen1](https://cloud.githubusercontent.com/assets/1934794/11666929/e6f04ee8-9dbc-11e5-8162-fd4ddb9f42ac.jpg)
2. When I create a shipment for it Magento creates a shipment for the parent, but not for children. That's logical because it's "Ship Bundle Items: Together". When I invoice the order I see only children are invoiced, not the parent.
   ![screen2](https://cloud.githubusercontent.com/assets/1934794/11666956/0c39bb76-9dbd-11e5-966a-420d465d69e0.jpg)
3. When I try to create a return either from admin or a customer dashboard I get an error: We can't save this RMA. No items were specified. And I don't see any items in the list to select.
   ![screen3](https://cloud.githubusercontent.com/assets/1934794/11666966/16c8238e-9dbd-11e5-8515-b3a38dd244b6.jpg)

**Comment by NadiyaS** [comment]
The GitHub issue tracker is intended for technical issues of CE edition only. 
Please refer to [EE customer support](https://magento.com/support/enterprise-edition)
To create ticket need to  click on 'Open ticket' button.

**Comment by molinainat** [comment]
Does this have a solution? Can ship bundle -> separetely help to display the items when creating a return?
