### ISSUE TITLE
[BUG] ApiFunctional TestFramework GraphQL Client Parses Headers Improperly

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#26425]
### Preconditions (*)
Magento v2.3.3

### Steps to reproduce (*)
1. Make a call with the `GraphQlAbstract::graphQlQueryWithResponseHeaders`
2. Have a header in the response like: `Access-Control-Allow-Origin: https://www.example.com`
3. See that the header does NOT show up in the headers array

### Expected result (*)
1. Have a header in the headers array like: `['Access-Control-Allow-Origin'] => 'https://www.example.com'`

### Actual result (*)
See above.

This is due to a failed `preg_split` logic in:

https://github.com/magento/magento2/blame/6b4a82b8554917ba78f7bc84ada8ea05a85aca92/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php#L210

```php
/**
     * Parse response headers into associative array
     *
     * @param string $headers
     * @return array
     */
    private function processResponseHeaders(string $headers): array
    {
        $headersArray = [];

        $headerLines = preg_split('/((\r?\n)|(\r\n?))/', $headers);
        foreach ($headerLines as $headerLine) {
            $headerParts = preg_split('/: /', $headerLine);
            if (count($headerParts) == 2) {
                $headersArray[trim($headerParts[0])] = trim($headerParts[1]);
            } elseif (preg_match('/HTTP\/[\.0-9]+/', $headerLine)) {
                $headersArray[trim('Status-Line')] = trim($headerLine);
            }
        }

        return $headersArray;
    }
```

It should `preg_split` with a limit of `2`:

```php
$headerParts = preg_split('/: /', $headerLine, 2);
```

cc: @danielrenaud @danmooney2

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30844` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Hello @damienwebdev 

Thank you, for your report.

Can you please create a pull request on this issue?

Thank you for collaboration
