### ISSUE TITLE
Customer switches to Default Store After Login/Register for multistore views

### ISSUE THREAD

**Issue by arsalanworld** [magento/magento2#26422]
### Summary
Customer switches to default store view after login/register page for multi-stores view when `store code` is enabled for base url.
### Preconditions (*)

1. Magento 2.4-develop
2. Add a new store view under existing/default store, if you don't have multi-store views. (lets call it Arabic store view) 
3. Enable caches and Set Environment to `Production`, if set to developer or default
4. Enable `Add Store Code to Urls` from *admin* > *STORES* > *Configuration* > *General* > *Web* and clean your store cache.

### Steps to reproduce (*)

1. Navigate to customer account login page with default store view.
2. Now switch your store to other store view.
3. Once page reloaded, enter your credentials and hit login button
4. If still not reproduce, try in `incognito` window

### Expected result (*)

1. The customer should login with correct store view.

### Actual result (*)

1. The customer logs in default store view which is not expected.

**Comment by arsalanworld** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @arsalanworld. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @arsalanworld, here is your [Magento instance](https://i-26422-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26422-2-4-develop.instances.magento-community.engineering/admin_9af0](https://i-26422-2-4-develop.instances.magento-community.engineering/admin_9af0)
Login: `511a2a65` Password: `32cc47573973`
Instance will be terminated in up to 3 hours.

**Comment by arsalanworld** [comment]
@magento-engcom-team I was able to reproduce this issue on vanilla Magento instance using steps I described and it appears with the developer mode as well.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30517` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @arsalanworld 

Could you please clarify
- What value you have for [Account Sharing Options](https://docs.magento.com/user-guide/customers/account-scope.html)
- what exact Expected result should be? what does mean correct store
- why current behavior is incorrect?

Share Customer Accounts
--




Share Customer Accounts
--

**Comment by arsalanworld** [comment]
@sdzhepa sure:
**1**. What value you have for Account Sharing Options --> **Per Website**
**2**. what exact Expected result should be?  --> The store view should stay same after login, it should not change back to default store view. For instance there are 2 stores on a website en(default store view) and fr. At login page customer changes from en store view to FR. and enters credentials and try logging in. **Expected result**: Customer should proceed to dashboard with FR store view. 
**3**. what does mean correct store --> the store view that was switched at login page i.e FR
**4**. why current behavior is incorrect? --> because customer switches back to default store view i.e EN instead of required FR store view.

**Comment by desaiuttam** [comment]
@magento give me 2.4-develop instance

**Comment by desaiuttam** [comment]
@magento I am working on this.

**Comment by desaiuttam** [comment]
@magento add to contributors team

**Comment by desaiuttam** [comment]
@magento I am working on this.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
