### ISSUE TITLE
Magento 2.0 CE not working on LocalHost

### ISSUE THREAD

**Issue by najeebputhiyallam** [magento/magento2#2643]
- WIndows 10 Pro - XAMPP 3.2.2

I downloaded CE V2.0 with Sample Data .tar.gz
Extracted to /localhost/magento
Added DB mangentoDB
Run  /localhost/magento - Setup Finishes Successfully
But when i try to open in Chrome both front end n backend is keeps loading and in firefox the front end and backend loading but i cant able to navigate also css n js not loading some fonts and js are missing that is 404 response

Please some one help me i am trying this for last 3 days

[debug.txt](https://github.com/magento/magento2/files/55983/debug.txt)
[install.txt](https://github.com/magento/magento2/files/55984/install.txt)
[system.txt](https://github.com/magento/magento2/files/55985/system.txt)

![console](https://cloud.githubusercontent.com/assets/1217672/11667163/8f21b7d6-9e09-11e5-9a30-259ca6b3e6ed.jpg)
![dash](https://cloud.githubusercontent.com/assets/1217672/11667165/8f26f3d6-9e09-11e5-95ad-8125323b1b58.jpg)
![home page](https://cloud.githubusercontent.com/assets/1217672/11667166/8f28f488-9e09-11e5-9fab-e988ea72c2f3.png)

**Comment by mazhalai** [comment]
It is suggested not to use localhost as domain name since Chrome has trouble with cookies set by localhost. Regarding broken js and css files, please run  'bin/magento setup:static-content:deploy`

**Comment by najeebputhiyallam** [comment]
Thanks alot. 

http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html

**Comment by SyedMuneebb** [comment]
Maybe you did something wrong. Well, here's a guide to install Magento 2 on localhost: [Magento 2 xampp ](https://magenticians.com/install-magento-2-on-localhost-using-xampp/)

**Comment by davidalger** [comment]
@SyedMuneebb That is not an official guide. Cookies do not work correctly on localhost, so regardless of whether or not there is a guide out there on the net for installing on localhost, there will be issues. Please don't propagate that guide, it will only cause others trouble. Much better to run on a magento.local or magento.dev domain with an entry in your hosts file pointing it to 127.0.0.1.
