### ISSUE TITLE
Custom Option with Percent price is converted to a currency twice

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#26432]
### Preconditions (*)

1. Magento 2.4-develop
2. PHP 7.2

### Steps to reproduce (*)

1. Add custom option of type Field, Radio, Checkbox or Date to a product
2. Set price to be of type percent
3. Add another currency to a shop
4. On a product page change a currency to different from shops base currency so that magento converts the prices.

### Expected result (*)

1. Price of custom option should be a percent of products price but in current currency.

### Actual result (*)

1. Percent price is converted twice.

Magento\Catalog\Pricing\Price\CustomOptionPriceCalculator::getOptionPriceByPriceCode():
in case of a percent, is getting price from product's PriceInfo which is converted to a selected currency.
However then on a block levels there different methods for different types of custom options, that end up in CustomOptionPrice::getCustomAmount() that does convertAndRound on already converted amount in case of percent custom option price.

 ### Additional information
-detailed steps with screens https://github.com/magento/magento2/issues/26432#issuecomment-649813348

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30626` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30626` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nimitagajera** [comment]
I am working on it
#mm20in

**Comment by sdzhepa** [comment]
Verified this issue on the lates `2.4-develop`

### Steps
1. Create a Simple product for test with base price 100 and custom option 50%

![2020-06-25_15-47-23](https://user-images.githubusercontent.com/3409584/85794327-0d566100-b6fc-11ea-8fbd-328f9ea1cb58.jpg)

2. Enable additional currency e.g. Euro

![2020-06-25_15-49-14](https://user-images.githubusercontent.com/3409584/85794381-25c67b80-b6fc-11ea-9b12-aef27993a6c3.jpg)

3. For testing purposes, I applied custom  Currency Rates.


![2020-06-25_15-49-39](https://user-images.githubusercontent.com/3409584/85794473-51496600-b6fc-11ea-9d54-4321c11d074f.jpg)


4. Go to the Product details page and switch between currencies 
![2020-06-25_15-50-08](https://user-images.githubusercontent.com/3409584/85794539-6cb47100-b6fc-11ea-907f-b90e2b8f48b0.jpg)

**Comment by solwininfotech** [comment]
@magento I am working on this

**Comment by solwininfotech** [comment]
#dmcdindia2020
