### ISSUE TITLE
Custom price into offline order not showing into admin sidebar in magento 2.2.5

### ISSUE THREAD

**Issue by Snippets-2023** [magento/magento2#26431]
### Preconditions (*)

1. Magento 2.2.5 / 2.2.5 Open Source.

### Steps to reproduce (*)

1. login to admin then go to sales > click on create new order button.
2. Then click on Add Products button and Select any product from the list then click on Add Selected Product(s) to Order button above.
3. Now you'll be able to see those products which you have added from the list.
4. Now try to click on Custom Price checkbox and add any other amount into the custom price box. Then select an option from the select box below Action label.
5. Then click on Button Update Items and Quantities and this will reflect under the left sidebar under selected in the Action table section.
6. This will now display into the left sidebar but the strange thing is that you'll see the normal base price, not custom entered price.

### Expected result (*)

1. Custom entered price should show, Not base price.

### Actual result (*)

1. But it's showing base price, not custom added price.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26431-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26431-2-4-develop.instances.magento-community.engineering/admin_d573](https://i-26431-2-4-develop.instances.magento-community.engineering/admin_d573)
Login: `abaad31b` Password: `27eab674464a`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @ashishi-law ,

I have verified this issue in the Default Magento 2.4 Instance. Now it is working fine in the latest Magento instance.
If you have found this issue in the latest Magento 2.4 instance. Please let me know.

Thanks.

**Comment by ajijshekh123** [comment]
Hi @ashishi-law, Please update your thought.

**Comment by ajijshekh123** [comment]
Hi @ashishi-law ,
If you are facing this issue again you can open it. Now I am closing this issue.

Thanks.
