### ISSUE TITLE
No changes are visible on frontend after adding _theme.less file to custom theme

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#2644]
After doing [this example](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css-practice.html) from the Frontend Dev Guide, no changes are visible when my custom theme is applied.

I've already created a new theme and set Blank as parent.

WAMP installation on developer mode.

**Comment by wonderfan** [comment]
Do you clear the caches?

**Comment by jibrandlr** [comment]
After deleting all files in the following directories: - pub/static/frontend/<Vendor/Theme and var/view_preprocessed/css now I can see the changes.

**Comment by wonderfan** [comment]
congratulation
