### ISSUE TITLE
One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by najeebputhiyallam** [magento/magento2#2645]
WIndows 10 Pro 
XAMP 3.2.2 
Magento CE V2.0
Loaded Configuration File = C:\xampp\php\php.ini
Magento Path: C:/Users/Projects/M

Basically I am a Designer / Frontend Developer and i am familiar with Cron Job in Cpanel

I read this http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-bkg  

i tried everything possible. please someone. this gonna help me alot

![cron](https://cloud.githubusercontent.com/assets/1217672/11672062/7bcc7582-9e26-11e5-933f-732749a6dd53.jpg)

![cron2](https://cloud.githubusercontent.com/assets/1217672/11672215/f075eb1a-9e27-11e5-8392-90b3d64d2f57.jpg)

**Comment by buskamuza** [comment]
Hi @najeebputhiyallam ,

[Cron](https://en.wikipedia.org/wiki/Cron) is a *nix tool. It does not exist on Windows as is. You can look at this thread http://stackoverflow.com/questions/132971/what-is-the-windows-version-of-cron to find a Windows alternative.
The goal is to configure your cron alternative to run this command every 1 minute `php -c <ini-file-path> <your Magento install dir>/bin/magento cron:run`.

A temporary quick solution to "fix" the indexes would be to run the same command manually:
`php -c <ini-file-path> <your Magento install dir>/bin/magento cron:run`
This approach will require from you manual actions every time you need to get indexes refreshed.

**Comment by wonderfan** [comment]
you can use cygwin

**Comment by wonderfan** [comment]
another solution is to create scheduler task in the window. In your task body, use php to run the codes

**Comment by victorgugo** [comment]
This issue is related to local environment. Closed as not related to Magento itself.
