### ISSUE TITLE
Unable to unserialize value when enable redis cache backend in 2.4-dev

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#26453]
### Preconditions (*)

1. Magento 2.4-develop
2. php 7.3.11
3. redis enabled in container of docker enviroment

### Steps to reproduce (*)

1. bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis
2. 

### Expected result (*)

1. Page load without problem
2.

### Actual result (*)

1. Error InvalidArgumentException: Unable to unserialize value
#0 /var/www/magento2ce/app/code/Magento/Config/App/Config/Type/System.php(252): Magento\Framework\Serialize\Serializer\Serialize->unserialize('') #1 /var/www/magento2ce/lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php(69): Magento\Config\App\Config\Type\System->Magento\Config\App\Config\Type\{closure}() #2 /var/www/magento2ce/app/code/Magento/Config/App/Config/Type/System.php(261): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('SYSTEM_CONFIG', Object(Closure), Object(Closure), Object(Closure)) #3 /var/www/magento2ce/app/code/Magento/Config/App/Config/Type/System.php(195): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default') #4 /var/www/magento2ce/app/code/Magento/Config/App/Config/Type/System.php(169): Magento\Config\App\Config\Type\System->getWithParts('default/newreli...') #5 /var/www/magento2ce/lib/internal/Magento/Framework/App/Config.php(132): Magento\Config\App\Config\Type\System->get('default/newreli...') #6 /var/www/magento2ce/lib/internal/Magento/Framework/App/Config.php(80): Magento\Framework\App\Config->get('system', 'default/newreli...') #7 /var/www/magento2ce/lib/internal/Magento/Framework/App/Config.php(93): Magento\Framework\App\Config->getValue('newrelicreporti...', 'default', NULL) #8 /var/www/magento2ce/app/code/Magento/NewRelicReporting/Model/Config.php(94): Magento\Framework\App\Config->isSetFlag('newrelicreporti...') #9 /var/www/magento2ce/app/code/Magento/NewRelicReporting/Plugin/HttpPlugin.php(49): Magento\NewRelicReporting\Model\Config->isNewRelicEnabled() #10 /var/www/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(121): Magento\NewRelicReporting\Plugin\HttpPlugin->beforeCatchException(Object(Magento\Framework\App\Http\Interceptor), Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) #11 /var/www/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) #12 /var/www/magento2ce/generated/code/Magento/Framework/App/Http/Interceptor.php(39): Magento\Framework\App\Http\Interceptor->___callPlugins('catchException', Array, Array) #13 /var/www/magento2ce/lib/internal/Magento/Framework/App/Bootstrap.php(266): Magento\Framework\App\Http\Interceptor->catchException(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) #14 /var/www/magento2ce/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #15

**Comment by mrtuvn** [comment]
seem not related with magento. This problem come from faults in redis configuration

**Comment by JiyaadDolly** [comment]
@mrtuvn 
How did you manage to resolve this?
Facing the same issue with redis
