### ISSUE TITLE
Setup Issue on New Installation Magento 2.3.3 

### ISSUE THREAD

**Issue by afavata** [magento/magento2#26465]
Environment
Ubuntu 18.04.3 LTS
Apache/2.4.29 (Ubuntu)
PHP 7.3.13
mysql  Ver 8.0.19

I installed all the source file for Magento 2.3.3  using composer command. 
Composer command ended with no issue
Configured apache2 host server and PHP
Configured mysql and created a new database DbMagento
Accessed through Browser to Magento Setup
Filled all the information requested and reached the last step:
1 - Readiness Check = no issue
2 - Add a Database = no issue
3 - Web Configuration = no issue
4 - Customize your store = no issue
5 - Create Admin Account = no issue
6 - install = ISSUE

During the last step "6" relating to install ... system performs initial installation and then stops ... see console Log herewith

```
`Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_AdminAnalytics':

Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Amqp':

Module 'Magento_AmqpStore':

Module 'Magento_Config':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_AuthorizenetGraphQl':

Module 'Magento_Search':

Module 'Magento_Backup':

Module 'Magento_AdminNotification':

Module 'Magento_BraintreeGraphQl':

Module 'Magento_Indexer':

Module 'Magento_Authorization':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_Cms':

Module 'Magento_Catalog':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\Catalog\Setup\Patch\Schema\EnableSegmentation for module Magento_Catalog. Original exception message: Invalid column data type "" in /var/www/magento/vendor/magento/framework/Setup/Patch/PatchApplier.php:241
Stack trace:
#0 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(1004): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Catalog')
#1 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(832): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#3 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)
#4 /var/www/magento/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#6 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /var/www/magento/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/magento/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /var/www/magento/setup/index.php(39): Zend\Mvc\Application->run()
#14 {main}`
```

**Comment by afavata** [comment]
Any fast workaround to resolve this issue?

**Comment by engcom-Hotel** [comment]
Hello @afavata 
The problem is your MySql version, Magento 2.3.3 supports only MySql 5.6, 5.7.
![image](https://user-images.githubusercontent.com/51681618/72893075-dcbf6500-3d20-11ea-9ae3-14bdfacf3b38.png)
You can read more about Magento technology stack requirements  [here](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#database).

So i have to close this issue.

Thanks for your report and collaboration!

**Comment by LucasMaliszewski** [comment]
I have mysql  Ver 15.1 Distrib 10.2.30-MariaDB, for osx10.15 (x86_64) using readline 5.1 and I'm still seeing this error.

**Comment by LucasMali** [comment]
> Hello @afavata
> The problem is your MySql version, Magento 2.3.3 supports only MySql 5.6, 5.7.
> ![image](https://user-images.githubusercontent.com/51681618/72893075-dcbf6500-3d20-11ea-9ae3-14bdfacf3b38.png)
> You can read more about Magento technology stack requirements [here](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#database).
> 
> So i have to close this issue.
> 
> Thanks for your report and collaboration!

I have mysql  Ver 15.1 Distrib 10.2.30-MariaDB, for osx10.15 (x86_64) using readline 5.1 and I'm still seeing this error.

Tried with mysql  Ver 14.14 Distrib 5.7.29, for osx10.15 (x86_64) using  EditLine wrapper and still seeing the error.

**Comment by LucasMali** [comment]
> Environment
> Ubuntu 18.04.3 LTS
> Apache/2.4.29 (Ubuntu)
> PHP 7.3.13
> mysql Ver 8.0.19
> 
> I installed all the source file for Magento 2.3.3 using composer command.
> Composer command ended with no issue
> Configured apache2 host server and PHP
> Configured mysql and created a new database DbMagento
> Accessed through Browser to Magento Setup
> Filled all the information requested and reached the last step:
> 1 - Readiness Check = no issue
> 2 - Add a Database = no issue
> 3 - Web Configuration = no issue
> 4 - Customize your store = no issue
> 5 - Create Admin Account = no issue
> 6 - install = ISSUE
> 
> During the last step "6" relating to install ... system performs initial installation and then stops ... see console Log herewith
> 
> ```
> `Starting Magento installation:
> File permissions check...
> 
> Required extensions check...
> 
> Enabling Maintenance Mode...
> 
> Installing deployment configuration...
> 
> Installing database schema:
> Schema creation/updates:
> Module 'Magento_AdminAnalytics':
> 
> Module 'Magento_Store':
> 
> Module 'Magento_AdvancedPricingImportExport':
> 
> Module 'Magento_Directory':
> 
> Module 'Magento_Amqp':
> 
> Module 'Magento_AmqpStore':
> 
> Module 'Magento_Config':
> 
> Module 'Magento_Theme':
> 
> Module 'Magento_Backend':
> 
> Module 'Magento_Variable':
> 
> Module 'Magento_Eav':
> 
> Module 'Magento_Customer':
> 
> Module 'Magento_AuthorizenetGraphQl':
> 
> Module 'Magento_Search':
> 
> Module 'Magento_Backup':
> 
> Module 'Magento_AdminNotification':
> 
> Module 'Magento_BraintreeGraphQl':
> 
> Module 'Magento_Indexer':
> 
> Module 'Magento_Authorization':
> 
> Module 'Magento_BundleImportExport':
> 
> Module 'Magento_CacheInvalidate':
> 
> Module 'Magento_Cms':
> 
> Module 'Magento_Catalog':
> [ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\Catalog\Setup\Patch\Schema\EnableSegmentation for module Magento_Catalog. Original exception message: Invalid column data type "" in /var/www/magento/vendor/magento/framework/Setup/Patch/PatchApplier.php:241
> Stack trace:
> #0 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(1004): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Catalog')
> #1 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(832): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
> #2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
> #3 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)
> #4 /var/www/magento/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
> #5 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
> #6 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
> #7 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
> #8 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
> #9 /var/www/magento/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
> #10 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
> #11 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
> #12 /var/www/magento/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
> #13 /var/www/magento/setup/index.php(39): Zend\Mvc\Application->run()
> #14 {main}`
> ```

Did you ever find a fix for this?

**Comment by metalleg** [comment]
Also running into this issue.

Clean M2.3.3 installation onto macOS Catalina.
php 7.1.3.3
mySql 5.7.29

**Comment by afavata** [comment]
Hello @LucasMaliszewski 
thanks for the info... 
I'm trying to downgrade MySQL from 8.0 to 5.7 but MySQL is giving many errors and doesn't start

**Comment by engcom-Hotel** [comment]
@metalleg @afavata 
Magento 2 is not supported on MacOS:
![image](https://user-images.githubusercontent.com/51681618/73346552-b8b6d300-428e-11ea-8d67-4aff99130094.png)

**Comment by afavata** [comment]
Hello @engcom-Hotel 

I'm not running Magento on Windows or MAC... 
It is installed on Ubuntu 18.04

thanks

**Comment by engcom-Hotel** [comment]
@afavata but your mySql version is wrong

**Comment by afavata** [comment]
yes... You are right.... Mysql is wrong ... I'm trying to downgrade it but It's painful

**Comment by metalleg** [comment]
Really good eye - didn't even consider that compatibility based on guides I'd read. I'm operating through MAMP as an intermediary and all is well. Thank you!

Edit: Nope, ultimately ran into the same issue when trying to run setup:upgrade. Magento installed and ran fine but the magento commands are a no go. Perhaps it is just macOS.

**Comment by nik4152** [comment]
Hi @afavata @LucasMaliszewski 
you can add the code in file
vendor/magento/framework/DB/Adapter/Pdo/Mysql.php
line 1846
after line 
`case 'smallint':`
add            
`case 'smallint unsigned':`
and 
after line 
`case 'int':`
add
"case 'int unsigned':"

or full method code
```
    protected function _getColumnTypeByDdl($column)
    {
        switch ($column['DATA_TYPE']) {
            case 'bool':
                return Table::TYPE_BOOLEAN;
            case 'tinytext':
            case 'char':
            case 'varchar':
            case 'text':
            case 'mediumtext':
            case 'longtext':
                return Table::TYPE_TEXT;
            case 'blob':
            case 'mediumblob':
            case 'longblob':
                return Table::TYPE_BLOB;
            case 'tinyint':
            case 'smallint':
            case 'smallint unsigned':
                return Table::TYPE_SMALLINT;
            case 'mediumint':
            case 'int':
            case 'int unsigned':
                return Table::TYPE_INTEGER;
            case 'bigint':
                return Table::TYPE_BIGINT;
            case 'datetime':
                return Table::TYPE_DATETIME;
            case 'timestamp':
                return Table::TYPE_TIMESTAMP;
            case 'date':
                return Table::TYPE_DATE;
            case 'float':
                return Table::TYPE_FLOAT;
            case 'decimal':
            case 'numeric':
                return Table::TYPE_DECIMAL;
        }
    }
```
Please let me know if works

**Comment by alex-vk** [comment]
@nik4152 , your solution helped, thanks a lot.
Next the installation process may generate additional errors. In my case it was something like "You do not have the SUPER privilege and binary logging is enabled", so, the best solution is to downgrade mysql version.

**Comment by dalu** [comment]
in v2.3.4 this file is found at `lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php`

**Comment by kunjesh** [comment]
Hello @afavata 
I had installed mysql version 8.0.x and the same issue I have faced. But when I uninstalled mysql 8.0.x and reinstalled mysql version 5.7.28, than patch was easily installed. So its an issue with mysql version.

**Comment by djbolya** [comment]
> Hi @afavata @LucasMaliszewski
> you can add the code in file
> vendor/magento/framework/DB/Adapter/Pdo/Mysql.php
> line 1846
> after line
> `case 'smallint':`
> add
> `case 'smallint unsigned':`
> and
> after line
> `case 'int':`
> add
> "case 'int unsigned':"
> 
> or full method code
> 
> ```
>     protected function _getColumnTypeByDdl($column)
>     {
>         switch ($column['DATA_TYPE']) {
>             case 'bool':
>                 return Table::TYPE_BOOLEAN;
>             case 'tinytext':
>             case 'char':
>             case 'varchar':
>             case 'text':
>             case 'mediumtext':
>             case 'longtext':
>                 return Table::TYPE_TEXT;
>             case 'blob':
>             case 'mediumblob':
>             case 'longblob':
>                 return Table::TYPE_BLOB;
>             case 'tinyint':
>             case 'smallint':
>             case 'smallint unsigned':
>                 return Table::TYPE_SMALLINT;
>             case 'mediumint':
>             case 'int':
>             case 'int unsigned':
>                 return Table::TYPE_INTEGER;
>             case 'bigint':
>                 return Table::TYPE_BIGINT;
>             case 'datetime':
>                 return Table::TYPE_DATETIME;
>             case 'timestamp':
>                 return Table::TYPE_TIMESTAMP;
>             case 'date':
>                 return Table::TYPE_DATE;
>             case 'float':
>                 return Table::TYPE_FLOAT;
>             case 'decimal':
>             case 'numeric':
>                 return Table::TYPE_DECIMAL;
>         }
>     }
> ```
> 
> Please let me know if works

Thanks a lot!

**Comment by lasdou** [comment]
Hi all,

Is there a PR to push the @nik4152 suggested and confirmed correction on the current magento version ?

**Comment by djbolya** [comment]
I think that this was very helpful

**Comment by nackie99** [comment]
When you get to this error "You do not have the SUPER privilege and binary logging is enabled", you can fix it by:

mysql -u root_USERNAME -p
set global log_bin_trust_function_creators=1;

Install seems to have finished on Mysql 8, no idea if thee will be problems down the line though
