### ISSUE TITLE
No QR code when initialising 2FA

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#26466]
### Preconditions (*)

1. 2.3.3
2. Enable 2FA

### Steps to reproduce (*)

1. Stores > Configuration > Security > 2FA
2. Enable Two Factor Auth: Yes
3. Force providers: none
4. Enable Google Authenticator
5. System > All Users
6. Enable Google Authenticator for an account
7. Login to said account

### Expected result (*)

1. Should be shown a QR code to initialise 2FA

### Actual result (*)

![image](https://user-images.githubusercontent.com/13659750/72792232-94287e80-3c30-11ea-8ea8-e3a29cd4587d.png)

No QR code - no login! Tried with two different admin accounts in two different browsers with Magento cache and browser cache flushed.

Module MSP_TwoFactorAuth is enabled (standard in M2.3.x)

No errors logged in any Magento or PHP error logs. No error logged in browser console. Just not working.

**Comment by sdzhepa** [comment]
Duplicate of #26467
