### ISSUE TITLE
Can't edit product page if attribute with input type Swatch Text has no options

### ISSUE THREAD

**Issue by sedax90** [magento/magento2#26461]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Create a new attribute with Input type: swatch visual
2. Don't creare any attribute options and click Save
3. Add this attribute to default attribute set
4. Try to create a new product

### Expected result (*)
1. Product edit form should be visibile with a message or something similar

### Actual result (*)
1. Exception is returned:
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\\Framework\\View\\Element\\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/sefyro.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 222 and defined in /var/www/sefyro.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:174\nStack trace:\n#0 /var/www/sefyro.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(222): Magento\\Framework\\View\\Element\\UiComponentFactory->argumentsResolver('con_cricchetto', NULL)\n#1 /var/www/sefyro.com/public_html/vendor/magento/module-ui/Component/Form/Field.php(85): Magento\\Framework\\View\\Element\\UiComponentFactory->create('con_cricchetto', 'swatch_text', Array)\n#2 /var/www/sefyro.com/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\\Ui\\Component\\Form\\Field->prepare()\n#3 /var/www/sefyro.com/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): in /var/www/sefyro.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 174, referer: https://www.sefyro.com/admin/catalog/product/index/key/249adff8d8f5485c918361a30eb1c26b0aba818ba0e7612c5a397b3701a4e966/

**Comment by sedax90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CRYX2. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CRYX2, here is your [Magento instance](https://i-26461-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26461-2-4-develop.instances.magento-community.engineering/admin_073d](https://i-26461-2-4-develop.instances.magento-community.engineering/admin_073d)
Login: `8e5ce0aa` Password: `9d1ec165f018`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26461-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26461-2-4-develop.instances.magento-community.engineering/admin_0000](https://i-26461-2-4-develop.instances.magento-community.engineering/admin_0000)
Login: `51d07d98` Password: `7e68e5f7a568`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @CRYX2 
thank you for reporting this issue . 
I tried reproducing this issue at 2.4 develop instance but not able to reproduce . Let me know if it requires any additional steps to reproduce this issue

**Comment by megabike** [comment]
I am able to reproduce it with 2.3.5p1
- Create an attribute with type: visual text swatch 
- DONT create any options
- Save the attribute
- Add attribute to default attribute-set

go to Catalog -> Products
- create new product -> error message

I recognized it, while programming an import-extension. My InstallSchema.php creates the attribute and I am also able to import products - the options are created, when the import is running.
But I was not able to "open" an imported product (got the same error message).
It starts working after I open the attribute (now populated with some options) and click save.

**Comment by jonathansergio** [comment]
Was some solution found for this issue?
