### ISSUE TITLE
2FA no QR code on first login

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#26467]
### Preconditions (*)

1. 2.3.3
2. Enable 2FA

### Steps to reproduce (*)

1. Stores > Configuration > Security > 2FA
2. Enable Two Factor Auth: Yes
3. Force providers: none
4. Enable Google Authenticator
5. System > All Users
6. Enable Google Authenticator for an account
7. Login to said account

### Expected result (*)

1. Should be shown a QR code to initialise 2FA

### Actual result (*)

![image](https://user-images.githubusercontent.com/13659750/72793160-051c6600-3c32-11ea-9bb6-8a71fc22b2dc.png)

No QR code - no login! Tried with two different admin accounts in two different browsers with Magento cache and browser cache flushed.

Module MSP_TwoFactorAuth is enabled (standard in M2.3.x)

No errors logged in any Magento or PHP error logs. No error logged in browser console. Just not working.

**Comment by adamlavery** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @adamlavery. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @adamlavery, here is your [Magento instance](https://i-26467-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26467-2-4-develop.instances.magento-community.engineering/admin_cbed](https://i-26467-2-4-develop.instances.magento-community.engineering/admin_cbed)
Login: `ac855082` Password: `579035e85375`
Instance will be terminated in up to 3 hours.

**Comment by Zyles** [comment]
This is a problem if you upgraded to 2.3.3. Not re-producable on new installs for me.

**Comment by adamlavery** [comment]
Hmm, instance created in the middle of (my) night that only lasts for 3hrs! Instances should last at least 24hrs, or preferably 72hrs if created on a Friday. It's no longer available.

@Zyles - so you are able to reproduce on upgraded M2.3.x but not fresh installs? Given most active sites will have been upgraded many times to get to 2.3.3, and there's no clues to the cause in any logs, any solution?

I say again, just because an issue is not reproducible on a vanilla install does not mean that there's not an issue that has been caused by new Magento releases. Most issues we're encountering nowadays are down to breaking changes in even minor Magento core releases or failures to handle the upgrade properly.

**Comment by Zyles** [comment]
Yes we had the same problem upgrading from 2.3.1 to 2.3.3.

I had to pay to get it fixed. Not sure what the problem was except that is has to do with the XML layout files that were incorrect somehow.

M2 devs should fix it, because they screwed up like the usually do since there is no QA done on any releases.

**Comment by adamlavery** [comment]
@Zyles - thanks for the confirmation. Any chance the devs that fixed it for you could give a pointer as to where the issue lies? Would be helpful to all not to have to redo the analysis on what mistake the core team have made this time.

> M2 devs should fix it, because they screwed up like the usually do since there is no QA done on any releases.

Absolutely with you on this.  Seems just about every new Magento release is now requiring a mail to my client apologising for Magento's mistakes and telling them its going to cost for either me or affected 3rd party extension providers to find and fix the issue. They're seriously questioning the decision to use Magento as there seems to be no end in sight of these constant core issues. We could expect these kind of issues in M2.0, but we shouldn't be getting them in 2.3!

**Comment by Zyles** [comment]
Sadly I can not. They are freelancers not employees and I have no ongoing contact.

All I know the problem lies in the layout XML files for the extension.

**Comment by engcom-Bravo** [comment]
Hello @adamlavery 

Thank you for your report.

Unfortunately, we are not able to reproduce the reported issue.
We have tried several scenarios:
- Clean Magento 2.4-develop
- Clean Magento 2.3.3 composer version
- Magento 2.1.17 composer version upgraded to 2.3.3 composer
- Magento 2.2 composer version with installed [2FA](https://devdocs.magento.com/guides/v2.2/security/two-factor-authentication.html) and upgraded to 2.3.3
- In all cases, tried with two different accounts, Admin rights, and custom User Role assigned

In all these cases, the _Authentication_ window with QR code and Authenticator code field appeared
![auth_code](https://user-images.githubusercontent.com/51680745/73251211-2b597d00-41c1-11ea-9e10-ddf24496b258.png)

Can you please provide us with more info to help us to reproduce the issue? 

- is your instance upgraded?
- is it a develop instance?
- does the _Authentication_ window not appear for all users you enable **Google Authenticator** ?
![gauth](https://user-images.githubusercontent.com/51680745/73251916-83dd4a00-41c2-11ea-9017-b60b226cf2f7.png)

Thank you for your collaboration

**Comment by adamlavery** [comment]
Hi Anton, 

Tested with two different accounts and same results on both. Yes, enabled Google Authenticator. It knows it should be giving the QR code, just isn't, This is on the dev site, the live site is still running 2.3.1. I've just tested 2FA on that too. Also fails but slightly differently giving this page...

![image](https://user-images.githubusercontent.com/13659750/73256672-45439180-41ba-11ea-9888-d97332b7b279.png)

Trying to change password gives the same result. This particular site went from 2.2.1 > 2.2.3 > 2.2.6 > 2.2.8 > 2.3.1 then 2.3.3 (dev). We've had other issues when upgrading that have been related to going from one specific version to another (and not reproducible on a vanilla install).

Does Zyles pointer to an XML issue help? Suggests something in one of the upgrade scripts is missing something that affects 2FA or doing something it shouldn't.

I guess without access to a faulty install this is going to be difficult to trace. Trouble is I'm an independent dev and at this point my client is somewhat opposed to stumping up the cost of investigating and fixing what looks to be a Magento core issue. I could perhaps give you access to the dev site?

**Comment by adamlavery** [comment]
Ok, so password message just because I hadn't disabled the password expiry. Now done and same result as on dev site. Suggests something happened (or didn't) during the 2.3.1 upgrade. Don't have the 2.2.8 version of the site to see if it worked then.

**Comment by engcom-Bravo** [comment]
@adamlavery Thank you for the quick response.

We would like to ask you for one more detail. 
The 2FA became a Core Bundled Extension since 2.3.x 
When the M2 instance was 2.2.x, did you [install 2FA separately](https://devdocs.magento.com/guides/v2.2/security/two-factor-authentication.html)  and used it, or did you start using it only after upgrade to 2.3.x ?

Thank you

**Comment by adamlavery** [comment]
Hi Anton, first time we tried to enable 2FA was in 2.3.3. We have never installed an independent 2FA module.

**Comment by engcom-Bravo** [comment]
@adamlavery Thank you for the quick response.

We would like to ask you for one more detail, if you don't mind. 
The 2FA became a Core Bundled Extension since 2.3.x 
When the M2 instance was 2.2.x, did you [install 2FA separately](https://devdocs.magento.com/guides/v2.2/security/two-factor-authentication.html)  and used it, or did you start using it only after the upgrade to 2.3.x ?

Thank you

**Comment by adamlavery** [comment]
???

**Comment by engcom-Bravo** [comment]
You've mentioned several upgrades 
_This particular site went from 2.2.1 > 2.2.3 > 2.2.6 > 2.2.8 > 2.3.1 then 2.3.3 (dev)._
When using 2.2.1 for example, before the upgrade, did this site use 2FA ?

**Comment by adamlavery** [comment]
If it wasn't in the core in 2.2x then no, we didn't add anything to any 2.2.x for 2FA. We have only tried to enable as of 2.3.x, and it's there as standard.

**Comment by ueltonVeslei** [comment]
This works for me: 
https://medium.com/adobetech/configuring-tfa-on-magento-2-4-0-admin-panel-with-google-authenticator-dbf8801da4c3

**Comment by Zyles** [comment]
> This works for me:
> https://medium.com/adobetech/configuring-tfa-on-magento-2-4-0-admin-panel-with-google-authenticator-dbf8801da4c3

Stop spamming. Nobody here needs your tutorial on how to install 2fa.

**Comment by markvds** [comment]
For anyone that runs into this issue: The problem is indeed somewhere in the layout files. I didn't dive into it too deep, but found  that the block name `content` in all login layout files of Msp_TwoFactorAuth interferes with some other block in the layout. Maybe it's another Magento module, maybe it's some external module.

Renaming the block names to something different (like `twofactorauth.content`) solves the problem. Use a composer patch file to persist the changes to the module.

**Comment by tschirmer** [comment]
This also happens under role restricted users.
