### ISSUE TITLE
Issue with Paypal Payment

### ISSUE THREAD

**Issue by smjrifle** [magento/magento2#26485]
I am trying this on Magento version 2.3.2 and 2.3.3. All the payments are working properly, I am using Paypal Express and while trying to make payments via Paypal I am facing issues, if I use card payment on Paypal Express it works with out error.

Looking over console log. I found genericError.dust%3AblockNonDomesticShipping while making the paypal request. Then I edited vendor/magento/module-paypal/Model/Api/Nvp.php and set $request['ADDROVERRIDE'] to 0. Now I get Invalid Shipping address error.

With $request['ADDROVERRIDE'] to 1

Things Don’t Appear to be Working at the Moment. Please Try Again Later.
<img width="408" alt="Screen Shot 2020-01-22 at 12 13 52" src="https://user-images.githubusercontent.com/1078556/72870584-ad086100-3d10-11ea-9b35-cb17f2f02abf.png">

With $request['ADDROVERRIDE'] to 0
<img width="879" alt="Screen Shot 2020-01-22 at 11 58 43" src="https://user-images.githubusercontent.com/1078556/72869844-94974700-3d0e-11ea-960a-7c6f4f7fd596.png">

<img width="1237" alt="Screen Shot 2020-01-22 at 11 59 18" src="https://user-images.githubusercontent.com/1078556/72869865-a37df980-3d0e-11ea-8c3e-427684ca0c8c.png">

**Comment by engcom-Golf** [comment]
Hi @smjrifle thank you for you report, this related to your address configuration, City/State/ZIP don't match, also related to this https://github.com/magento/magento2/issues/16556
