### ISSUE TITLE
Unable to remove default text swatch value and value automatically assigning

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26481]
When creating a new text swatch, if you click "Is default" you can not undo it and having a blank value is no longer possible. That causes a problem for products where the swatch is optional.

That value will then automatically assign itself to any old products if they are saved, even if you did not select any text swatch value.

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Add new text swatch attribute with 3 options
2. Values Required = No
3. Do NOT click any "Is Default"
4. Save attribute
5. Assign attribute to attribute set Default
6. Create new product. You can see that the swatch selection is BLANK = CORRECT
7. Edit the attribute again and select "Is Default" on any selection
8. Save attribute
9. Try to edit attribute again, now it is impossible to remove the default option
10. Create a new product again, the default selection is prefilled and you have to manually select "blank" even if the value is supposed to be OPTIONAL with "Values Required"

This also causes a VERY annoying side-bug:

1. Create ANOTHER text swatch attribute
2. Values Required = No
3. Add 3 options and click "Is Default" on any
4. Save attribute and add to attribute set
5. Clear Cache etc.
6. Go into an old product added in previous steps and look at the new swatch value, it should still be blank = correct
7. Save product without doing any changes.
8. Look at the new swatch value. Suddenly it has a value assigned! BY ITSELF!

This causes MAJOR problems.

If you edit an attribute set with a new text swatch. The "default value" will be assigned on ALL products automatically when that product is edited without the intent of the catalog manager.

In fact ANY edit to the product will make it change to the default text swatch value even if you want it to be blank.

### Expected result (*)

A text swatch value should not assign its default value by itself without the catalog managers input.

### Actual result (*)

Text swatch value is assigned by itself, even if left blank upon product save when new attributes are added to the attribute group.

![issue_26481_1](https://user-images.githubusercontent.com/3409584/84920610-0474e800-b089-11ea-9d7f-6ede8ed01515.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30656` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Alex7Lem** [comment]
Solution of the problem:
Create a new value for the attribute.
Set the new attribute value to the default.
Remove new attribute value.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by Zyles** [comment]
Closing a bunch of tickets does not solve them and does not make Magento 2 a better product just FYI. The problems are still there and the platform is in a very buggy sad state.

But we don't care anymore, we are dropping Magento 2 in a month for a better platform and getting off this trainwreck.
