### ISSUE TITLE
Magento/Store/Model/Store uses missing interface

### ISSUE THREAD

**Issue by fooman** [magento/magento2#2649]
The class Magento\Store\Model\Store includes the following method

```
public function setExtensionAttributes(
    \Magento\Store\Api\Data\StoreExtensionInterface $extensionAttributes
) {
    return $this->_setExtensionAttributes($extensionAttributes);
}
```

which references `\Magento\Store\Api\Data\StoreExtensionInterface` which seems to be absent.

**Comment by okorshenko** [comment]
@fooman , `\Magento\Store\Api\Data\StoreExtensionInterface` (`*ExtensionInterface` ) is autogenerated interface. Please, see https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Api/Code/Generator/ExtensionAttributesInterfaceGenerator.php

**Comment by fooman** [comment]
Thanks for the hint. The problem that I encountered was that I used this in my unit test

```
    $storeMock = $this->getMockBuilder('Magento\Store\Model\Store')
        ->disableOriginalConstructor()
        ->getMock();
```

which then fails with 

> Cannot mock Magento\Store\Model\Store::setExtensionAttributes() because a class or interface used in the signature is not loaded

Will check what I need to amend in my tests.

**Comment by Vinai** [comment]
I don't have any issues mocking the store, even if the interface does not exist.
I also removed the generated interface manually before running the test, just to be sure.
The following runs fine for me, which is pretty much the same you have:

``` php
<?php

namespace Example\Mock\Test\Unit;

use Magento\Store\Model\Store;

class SomethingWithStoreTest extends \PHPUnit_Framework_TestCase
{
    public static function setUpBeforeClass()
    {
        $path = BP . '/var/generation/Magento/Store/Api/Data/StoreExtensionInterface.php';
        if (file_exists($path)) {
            unlink($path);
        }
    }

    public function testSomething()
    {
        $mockStore = $this->getMockBuilder(Store::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->assertInstanceOf(Store::class, $mockStore);
    }
}
```

Are you using the Magento bootstrap? Are you using the PHPUnit version that comes with Magento?

**Comment by fooman** [comment]
Thanks @Vinai - the difference is probably that I currently have Magento modules sitting under vendor. This works for another [extension](https://github.com/fooman/sameorderinvoicenumber-m2/blob/master/composer.json#L18) but fails on this autogenerated interface for a different extension.

Will post back here once I have it figured out.

**Comment by peterjaap** [comment]
Update on this @fooman ?

**Comment by fooman** [comment]
@peterjaap haven't found a solution to this yet apart from running the unit tests as part of a full M2 install

**Comment by fooman** [comment]
Just a further update I have now uploaded to github my set up. 

What I am currently trying to get to work is to be able to only require the Magento modules our extension uses and then be able to run just our unit tests (it all works if I copy my files into a full install of Magento). This is my folder structure:

src/ 
tests/ 
vendor/

and I would simply run `composer install` then `phpunit`.

This approach works well for [Same Order Invoice Number](https://github.com/fooman/sameorderinvoicenumber-m2) see [Travis](https://travis-ci.org/fooman/sameorderinvoicenumber-m2/builds/109518428)

Doing the very same for [Print Order Pdf](https://github.com/fooman/printorderpdf-m2) causes the missing autogenerated interface - see [here](https://travis-ci.org/fooman/printorderpdf-m2/jobs/111936744) 

I have also tested using `magento/magento2ce` as a dependency with a modified vendor path in `vendor/magento-community-edition/app/etc/autoload.php` with the same result.

One thing that I noticed in my research so far is that the Magento framework composer.json file [here](https://github.com/magento/magento2/blob/2.0.2/lib/internal/Magento/Framework/composer.json) seems incomplete. As a minimum I would have expected the Zend framework in there.

Will take a look next where the ExtensionAttributesInterfaceGenerator is set up and why it's not loaded with the above approach.

Further interesting bits:
The `ObjectManager` used in tests `Magento\Framework\TestFramework\Unit\Helper\ObjectManager` is different to what would be created via `Magento\Framework\App\ObjectManagerFactory`. The `\Magento\Framework\ObjectManager\DefinitionFactory` is what will provide the `\Magento\Framework\Code\Generator\Autoloader` for the code generator but this is absent from the `Unit\Helper\ObjectManager`.

**Comment by fooman** [comment]
FYI for any one stumbling across this I have started https://github.com/fooman/magento2-dev-bootstrap to be able to use Magento 2's bootstrap process without needing to install a full Magento 2.
