### ISSUE TITLE
Magento2 Customer Group Change in a custom registration form

### ISSUE THREAD

**Issue by phanikumar111** [magento/magento2#2650]
I am developing a custom form for wholesale group customers, i am able to successfully registered as wholesaler in my custom form. after enabling address fields customer not assigned to wholesale group.

I know we can change the customer group in admin panel, but still i want add additional features. i am trying to build a module it will be helpful for B2B customers. please help 

I am trying to change the customer group id in my custom form using hidden input field in wholesaleregistration.phtml

```
<input type="hidden" name="group_id" id="group_id" value="2" />
```

and also overridden controller class to change the customer group while registering

```
 <?php

namespace Exinent\WholesaleRetail\Controller\Index;

class Account extends \Magento\Customer\Controller\Account\CreatePost

 {


protected function extractAddress()
{
    if (!$this->getRequest()->getPost('create_address')) {
        return null;
    }

    $addressForm = $this->formFactory->create('customer_address', 'customer_register_address');
    $allowedAttributes = $addressForm->getAllowedAttributes();

    $addressData = [];

    $regionDataObject = $this->regionDataFactory->create();
    foreach ($allowedAttributes as $attribute) {
        $attributeCode = $attribute->getAttributeCode();

        $value = $this->getRequest()->getParam($attributeCode);

        if ($value === null) {
            continue;
        }
        switch ($attributeCode) {
            case 'region_id':
                $regionDataObject->setRegionId($value);
                break;
            case 'region':
                $regionDataObject->setRegion($value);
                break;
            default:
                $addressData[$attributeCode] = $value;
        }
    }

    $addressDataObject = $this->addressDataFactory->create();
    $this->dataObjectHelper->populateWithArray(
        $addressDataObject,
        $addressData,
        '\Magento\Customer\Api\Data\AddressInterface'
    );
    $addressDataObject->setRegion($regionDataObject);


   $addressDataObject->setIsDefaultBilling(
        $this->getRequest()->getParam('default_billing', true)
    )->setIsDefaultShipping(
        $this->getRequest()->getParam('default_shipping', true)
    );
    return $addressDataObject;
}



 public function execute($coreRoute = null)
    {


     $resultRedirect = $this->resultRedirectFactory->create();
    if ($this->session->isLoggedIn() || !$this->registration->isAllowed()) {
        $resultRedirect->setPath('*/*/');
        return $resultRedirect;
    }

    if (!$this->getRequest()->isPost()) {
        $url = $this->urlModel->getUrl('*/*/create', ['_secure' => true]);
        $resultRedirect->setUrl($this->_redirect->error($url));
        return $resultRedirect;
    }

    $this->session->regenerateId();  

    try {

               $address = $this->extractAddress();

                $addresses = $address === null ? [] : [$address];


        $customer = $this->customerExtractor->extract('customer_account_create', $this->_request);
        //echo $this->getRequest()->getParam('group_id');die();


        $customer->setAddresses($addresses);

  $customer->setGroupId($this->getRequest()->getParam('group_id'));

        $password = $this->getRequest()->getParam('password');
        $confirmation = $this->getRequest()->getParam('password_confirmation');
        $redirectUrl = $this->session->getBeforeAuthUrl();
       // $this->session->setCustomerGroupId($this->getRequest()->getParam('customer_group_id'));
        $this->checkPasswordConfirmation($password, $confirmation);
        $customer = $this->accountManagement
            ->createAccount($customer, $password, $redirectUrl);



        if ($this->getRequest()->getParam('is_subscribed', false)) {
            $this->subscriberFactory->create()->subscribeCustomerById($customer->getId());
        }



        $this->_eventManager->dispatch(
            'customer_register_success',
            ['account_controller' => $this, 'customer' => $customer]
        );

        $confirmationStatus = $this->accountManagement->getConfirmationStatus($customer->getId());





            $this->session->setCustomerDataAsLoggedIn($customer);


            $this->messageManager->addSuccess($this->getSuccessMessage());



                  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->create('Magento\Customer\Model\Session');
            //echo $this->getRequest()->getParam('customer_group_id');

   //echo $this->getRequest()->getParam('customer_group_id');die();

            //$resultRedirect = $this->accountRedirect->getRedirect();
    }
    catch (StateException $e) {
        $url = $this->urlModel->getUrl('customer/account/forgotpassword');
        // @codingStandardsIgnoreStart
        $message = __(
            'There is already an account with this email address. If you are sure that it is your email address, <a href="%1">click here</a> to get your password and access your account.',
            $url
        );
        // @codingStandardsIgnoreEnd
        $this->messageManager->addError($message);
    } catch (InputException $e) {
        $this->messageManager->addError($this->escaper->escapeHtml($e->getMessage()));
        foreach ($e->getErrors() as $error) {
            $this->messageManager->addError($this->escaper->escapeHtml($error->getMessage()));
        }
    } catch (\Exception $e) {
        $this->messageManager->addException($e, __('We can\'t save the customer.'));
    }

        //return $resultRedirect;
    return parent::execute($coreRoute);
}


}
```

**Comment by phanikumar111** [comment]
The issue is i am able to register as wholesale group customer with my form. After enabling address fields in my custom form its registering as a General Group Customer.

Hope you will understand the question

**Comment by phanikumar111** [comment]
This call causing to set the customer group to General after enabling address fields

```
<?php

namespace Exinent\WholesaleRetail\Controller\Index;

class Account extends \Magento\Customer\Controller\Account\CreatePost

{
 protected function extractAddress()
{
 $addressDataObject->setIsDefaultBilling(
        $this->getRequest()->getParam('default_billing', true)
    )->setIsDefaultShipping(
        $this->getRequest()->getParam('default_shipping', true)
    );
```

Enabled address fields in the wholesale registration form 

```
<?php $this->setShowAddressFields(true); ?> 
<?php if ($block->getShowAddressFields()): ?>
```

**Comment by phanikumar111** [comment]
Issue#
 I am able to register as wholesale group customer with my form. After enabling address fields in my custom form its registering as a General Group Customer.

I just want and trying to change the customer group while registering by not using magento2 default customer group change settings.

I am trying to develop a customer activation module.

Hope you will understand the question

#### Thanks for the Magento Team for Great support always

**Comment by phanikumar111** [comment]
i am setting the customer group id by calling 

```
 $customer->setGroupId($this->getRequest()->getParam('group_id'));
```

**Comment by phanikumar111** [comment]
and also trying to add few additional fields in the customer form

                                                                                                                                                                     $customer->setAccountsPaybleEmailAddress($this->getRequest()->getParam('accounts_payble_email_address'));
            $customer->setWebsiteURL($this->getRequest()->getParam('website_url'));

**Comment by phanikumar111** [comment]
and also trying to add few additional fields in the customer form. can we set fields using magic method like below. its throwing an error. How to add custom fields and save them in database.

```
$customer->setWebsiteURL($this->getRequest()->getParam('website_url'));
$customer->setAccountsPaybleEmailAddress($this->getRequest()->getParam('accounts_payble_email_address'));
```

I created customer attributes using UpgradeData.php script 

```
 $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);
        $customerSetup->addAttribute(
            Customer::ENTITY,
            'accounts_payble_email_address',
            [
                'label' => 'Accounts Payble Email Address',
                'required' => 0,
                'system' => 0, // <-- important, otherwise values aren't saved.
                               // @see Magento\Customer\Model\Metadata\CustomerMetadata::getCustomAttributesMetadata()
                'position' => 100
            ]
        );
        $customerSetup->getEavConfig()->getAttribute('customer', 'accounts_payble_email_address')
            ->setData('used_in_forms', ['adminhtml_customer'])
            ->save();


        $customerSetup->addAttribute(
            Customer::ENTITY,
            'website_url',
            [
                'label' => 'Website (Must have a URL)',
                'required' => 0,
                'system' => 0, // <-- important, otherwise values aren't saved.
                               // @see Magento\Customer\Model\Metadata\CustomerMetadata::getCustomAttributesMetadata()
                'position' => 100
            ]
        );
        $customerSetup->getEavConfig()->getAttribute('customer', 'website_url')
            ->setData('used_in_forms', ['adminhtml_customer'])
            ->save();
```

Throwing error 

```
Fatal error: Call to undefined method Magento\Customer\Model\Data\Customer::setAccountsPaybleEmailAddress() in /var/www/demos/magento2ce/app/code/Exinent/WholesaleRetail/Controller/Index/Account.php on line 92
```

**Comment by Vinai** [comment]
The github issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by devamitbera** [comment]
This is not the only issue in Magento  **Custom registration form** , also the issue exists in  **Default registration form**.If we passing any group_id from default registration form then that customer group does not set for that customer it always takes store default group_id
For in case of _default registration form_  Issue in [Magento\Customer\Model\CustomerExtractor] c(https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L92) class.
Even , i enabled attribute  **group_id** in customer registration form using 

`INSERT INTO `customer_form_attribute` (`form_code`, `attribute_id`) VALUES ('customer_account_creat', '10');`

But still is does not work bcoz...

Logic issue in [  if ($isGroupIdEmpty) {](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L92)

Means,
 instead of enabling **group_id**   for customer registration form and sending this field   value from , Magento **forcefully set Customer group as the default group .**

That is the problem.

## Solution:

Solution  is that, we need to modify condition

1.  don't execute [$customerDataObject->setGroupId(](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L93) when **_group_id_** is enable for  registration form 

2. execute  [$customerDataObject->setGroupId(](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L93)  when  **_group_id_** is  **not enable for  registration form**  

3. execute  [$customerDataObject->setGroupId(](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L93)  when  **_group_id_** is  **enable for  registration form *  but group id **does not selected** from form  



So. my suggestion change `if ($isGroupIdEmpty) {`

to

```
if (!$isGroupIdAllow || ($isGroupIdAllow &&(is_null($customerDataObject->getGroupId()))) ) {
            $customerDataObject->setGroupId(
                $this->customerGroupManagement->getDefaultGroup($store->getId())->getId()
            );
        }
```

Also for use developer perspective change variable name
[$isGroupIdEmpty ](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L83)

to 

`isGroupIdAllow`
