### ISSUE TITLE
"Something went wrong with processing the default view and we have restored the filter to its original state." and then the red never goes away and i cant refresh the page to add more content

### ISSUE THREAD

**Issue by shischrum1994** [magento/magento2#26515]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by engcom-Bravo** [comment]
Hello @shischrum1994,

Thank you for your report.

Unfortunately, from the provided description, we can not reproduce the issue and start to work on fixing it. Can you please provide the steps, and possibly screenshots, which lead to the _"Something went wrong with processing the default view and we have restored the filter to its original state."_ error message   

Thank you for collaboration

**Comment by engcom-Golf** [comment]
Hi @shischrum1994 thank you for you report, please provide additional description and steps to reproduce. feel free to open new issue.

**Comment by boranuk** [comment]
Preconditions - Magento 2.3.4 and items in catalog_product_entity where SKU is NULL
Steps to reproduce - Add keyword filter to admin products grid
Expected result - Filtered product grid
Actual result - Message "Something went wrong..." displayed at top of page and loading mask displayed, data does not load

**Comment by Grumag** [comment]
This happens in 2.3.4 for sure, happened two times for me. It seems to be happening when you search for a SKU number that has been deleted.   There is a StackExchange post about this that has been viewed 11,000+ times.  Google error message to confirm it. Solution is to empty ui_bookmark table.
It is a rather annoying bug that is obviously affecting a  LOT of people.

**Comment by SewHappy58** [comment]
It also happens on Magento 2.3.5-p  It's very random and you have to clear cache to get it to go away.  It didn't happen on 2.3

**Comment by SolsWebdesign** [comment]
This also happened in a custom module: it happens when one of the columns contains a "null" value (the column does not have to be filterable for this to happen!). And when it happens, you get an entry in the 'ui_bookmark' table that contains the user_id of the user that tried to filter and a namespace of the module and a config containing something like "this_is_a_column":{"visible":true,"sorting":false} for each column and if a column contains a null value this entry produces this error.  In my case it was sufficient to avoid all null entries (even in not filterable columns!) but with the product grid this cannot be avoided, especially if the Magento store contains migrated data :-(
A quick fix is to remove the entry from the ui_bookmark table. Cache clear did not work for me.

**Comment by sugaryusuf** [comment]
> This also happened in a custom module: it happens when one of the columns contains a "null" value (the column does not have to be filterable for this to happen!). And when it happens, you get an entry in the 'ui_bookmark' table that contains the user_id of the user that tried to filter and a namespace of the module and a config containing something like "this_is_a_column":{"visible":true,"sorting":false} for each column and if a column contains a null value this entry produces this error. In my case it was sufficient to avoid all null entries (even in not filterable columns!) but with the product grid this cannot be avoided, especially if the Magento store contains migrated data :-(
> A quick fix is to remove the entry from the ui_bookmark table. Cache clear did not work for me.

I am facing the same issue.  How did you solve it?

**Comment by parween-talat** [comment]
facing same issue

**Comment by SolsWebdesign** [comment]
@sugaryusuf @parween-talat There are several things you can do depending on the situation.

Open up the adminhtml developer tools (for instance in Chrome or Firefox) and look for the GET that goes wrong, it will be something like GET https......admin..../mui/index/renderer... and open the Json Response Payload:
![image](https://user-images.githubusercontent.com/4403221/111778763-7b0f7200-88b5-11eb-9868-d91a2639ac22.png)

It will point you in the right direction.

If it is a custom module (as in my case) have a look at the Vendor\YourModule\Ui\Component\Grid\Column\YourSpecificColumn.php and the function prepareDataSource. If it contains something

`public function prepareDataSource(array $dataSource)
{
  if (isset($dataSource['data']['items'])) {
    foreach ($dataSource['data']['items'] as & $item) {
      $name = $this->getData('name');
      if (isset($item['entity_id'])) {
         $item[$name] = $this->mySpecialFunction($item['imei_id']);`

then replace it with a try catch and fill the catch with something like $item[$name] = $item['imei_id'].' not found '; (so no null value).

Also in your grid you can add the sortable fals like mentioned above.  For example:

`
<column name="your_specific_value" class="Vendor\YourModule\Ui\Component\Grid\Column\YourSpecificColumn">
  <settings>
     <sortable>false</sortable>
  </settings>
  <argument name="data" xsi:type="array">
     <item name="config" xsi:type="array">
       <item name="filter" xsi:type="string">text</item>
       <item name="label" xsi:type="string" translate="true">Our Specific Value</item>
     </item>
  </argument>
</column>`

Don't forget to remove the user id from the ui_bookmark table (in below example user has userID 22):

`DELETE FROM ui_bookmark WHERE namespace = 'table_that_gives_you_trouble' AND identifier = 'current' AND user_id = '22';`
