### ISSUE TITLE
Array param type missing from \Magento\Quote\Model\Quote\Item::addOption

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26513]
### Preconditions (*)
1. Magento 2.4-develop
------------------------------------------
The method `addOption` does indeed allow an array to be passed. The very first piece of logic is
```
if (is_array($option)) {
    $option = $this->_itemOptionFactory->create()->setData($option)->setItem($this);
} ...
```
### Steps to reproduce (*)
1. Check `addOption`method in `Magento\Quote\Model\Quote\Item` class
 
### Expected result (*)
Array is allowed
```
@param \Magento\Quote\Model\Quote\Item\Option|\Magento\Framework\DataObject|array $option
```

### Actual result (*)
However, the `@param` docblock only states
```
@param \Magento\Quote\Model\Quote\Item\Option|\Magento\Framework\DataObject $option
```

------------------------------------------
An array type needs to be added at the end.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30871` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
I am working on this issue at #MM20IN
