### ISSUE TITLE
Issue with configurable product in multi address checkout.

### ISSUE THREAD

**Issue by dev-ajaysaini** [magento/magento2#26518]
After order place with multiaddress with configurable product and simple product in cart, order view page at customer end show 2 items for single configurable product (parent and it's associate).

![image](https://user-images.githubusercontent.com/42237032/73047865-3f3d7000-3e9d-11ea-9143-aeb63af7fccd.png)

### Preconditions (*)

1. Magento version: 2.3.3
2. Php version: 7.2.14

### Steps to reproduce (*)

1. Add Simple and configurable Products in cart.
2. Choose Check Out with Multiple Addresses.
3. Choose different-2 shipping address for all the products.
4. Process all the steps and finally Place Order, it will create multiple orders.
5. Open placed orders and check.
![image](https://user-images.githubusercontent.com/42237032/73048117-1bc6f500-3e9e-11ea-98f2-ebaf26b4c77b.png)
![image](https://user-images.githubusercontent.com/42237032/73048147-2b463e00-3e9e-11ea-9ff9-9f58c098a9cc.png)

### Expected result (*)

1. It should show single product instead of Parent and it's associate in order which has configurable product.
![image](https://user-images.githubusercontent.com/42237032/73048374-ea9af480-3e9e-11ea-9bb3-643e7cfaeef6.png)

### Actual result (*)

1. Display Parent and it's associate in order which is wrong.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26518-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26518-2-4-develop.instances.magento-community.engineering/admin_510a](https://i-26518-2-4-develop.instances.magento-community.engineering/admin_510a)
Login: `c9967969` Password: `88a6d180fe14`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @webkul-ajaysaini,
I can't able to place the order which steps provide by you.
Can you please let me know which steps are missing on my end. 
See attached the video and Update me.

![PlaceOrder_Issue](https://user-images.githubusercontent.com/24711761/73050801-030f0d00-3ea7-11ea-8f3b-c154a7680cd3.gif)

Thanks.

**Comment by dev-ajaysaini** [comment]
@ajijshekh123 kindly check your address.
Can you please check with magento2.3.3

**Comment by dev-ajaysaini** [comment]
Give me @magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini, here is your [Magento instance](https://i-26518-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26518-2-3-3.instances.magento-community.engineering/admin_4814](https://i-26518-2-3-3.instances.magento-community.engineering/admin_4814)
Login: `ca3a4365` Password: `87363b0136e6`
Instance will be terminated in up to 3 hours.

**Comment by dev-ajaysaini** [comment]
I have checked with 2.3.3 instance this issue is exist.

**Comment by ajijshekh123** [comment]
Okay, Let me check the Magento 2.3.3 instance and update you.

**Comment by ajijshekh123** [comment]
Issue reproduced in Magento 2.3.3 Instance.

**Comment by Usik2203** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [Magento instance](https://i-26518-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26518-2-4-develop.instances.magento-community.engineering/admin_98c8](https://i-26518-2-4-develop.instances.magento-community.engineering/admin_98c8)
Login: `0453f547` Password: `d2a0524a3a91`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by GovindaSharma** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-26518-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26518-2-4-develop.instances.magento-community.engineering/admin_7a95](https://i-26518-2-4-develop.instances.magento-community.engineering/admin_7a95)
Login: `8b4295df` Password: `945f26169d06`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment]
#MM20IN

**Comment by engcom-Delta** [comment]
Hi @webkul-ajaysaini . Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop
![#26518issue](https://user-images.githubusercontent.com/51681379/85371333-b81e2200-b538-11ea-8ece-5326c05294fd.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
