### ISSUE TITLE
Product and Category pages purged from Varnish daily at 1AM local time

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#26516]
### Issue Overview
I'm working with a merchant who has configured the Varnish FPC lifetime to 7 days. We discovered that every day around 1AM Eastern (6AM UTC), the Varnish memory usage would drop to nearly zero. This is being caused by the `catalogrule_apply_all` CRON (that is scheduled at 6AM UTC) resulting in a request similar to this being sent to Varnish (using `curl` to easily demonstrate what's happening):
```
curl -H 'X-Magento-Tags-Pattern: ((^|,)cat_c(,|$))|((^|,)cat_p(,|$))' -X PURGE http://127.0.0.1:6081/
```

Essentially all product and category pages that are cached in Varnish are being purged every day at 1AM (based on the timezone configured in "STORES > General > Locale Options > Timezone") because of [the `catalogrule_apply_all ` CRON job](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/etc/crontab.xml#L11).

This is the line of code that is triggering this: https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/AbstractIndexer.php#L72

### Preconditions
1. Install Magento 2.3.3 Open Source with Sample Data
2. Ensure Varnish is installed and configured and all caches are enabled
3. Install [n98-magerun2](https://github.com/netz98/n98-magerun2)

### Steps to reproduce
1. Flush the cache to ensure all FPC entries have been removed from Varnish:
   
       bin/magento cache:flush
2. Check the Varnish memory usage using a command like this:
   
       $ varnishstat -1 | egrep '.g_(space|bytes)' | grep outstanding
       SMA.s0.g_bytes                         17329          .   Bytes outstanding
3. Visit at least 10 product detail and/or category pages, so that they get added to the Varnish cache. View the response headers on at least one of those pages to ensure it's a Varnish cache HIT.
4. Check Varnish memory usage again and you'll see that the memory usage has increased:
   
       $ varnishstat -1 | egrep '.g_(space|bytes)' | grep outstanding
       SMA.s0.g_bytes                           277795          .   Bytes outstanding
5. Manually run the `catalogrule_apply_all` CRON:
   
       n98-magerun sys:cron:run catalogrule_apply_all
6. Manually run the `indexer_reindex_all_invalid` CRON (this step is necessary as it's ultimately what flushes the Varnish cache):
   
       n98-magerun sys:cron:run indexer_reindex_all_invalid

### Expected result
1. The Varnish memory level should remain the same as it was after you visited the 10+ frontend pages.
2. The pages you visited in step 3 above should still be cache HITs.

### Actual result
1. The Varnish memory level will drop, since all of the category and product pages will be flushed from Varnish. On a large site with tens of thousands of pages in the Varnish FPC, we've seen Varnish memory usage drop from ~300MB to ~15MB after the two CRON jobs run.
2. The pages you visited in step 3 above will be cache MISSes.

### Additional notes

If you look at the [history of the code that is causing this behavior](https://github.com/magento/magento2/blame/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/AbstractIndexer.php#L71..L87), you'll see it was implemented to fix the opposite problem, where cache was not being flushed even when it's supposed to. Whatever the solution is to fix this, you should ensure you don't cause a regression of these issues:
* https://github.com/magento/magento2/commit/93aaf4e39b0e2f6341522edbd651d1c0308948a1
* https://github.com/magento/magento2/commit/ff86fb9ef0dfdd5bac9716695be872e086ab1add

There is also an open issue right now (#13325) related to the cache invalidation and Catalog Price Rules.

### More technical details

If you have debug logs enabled, you'll see entries like this in your `var/log/debug.log` file when this issue occurs:

```
www-data@php-fpm:10:06 PM:/var/www/html$ grep '"cat_c"' var/log/debug.log
[2020-01-23 22:00:05] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cat_c","cat_p","BLOCK_HTML"],"mode":"matchingAnyTag"}} []
[2020-01-23 22:00:06] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cat_c","cat_p"],"mode":"matchingAnyTag"}} []
```

Hopefully you can come up with an elegant solution to only invalidate the products/categories affected by a Catalog Price Rule. This problem is certainly [one of the hard things](https://martinfowler.com/bliki/TwoHardThings.html).

**Comment by fooman** [comment]
This could indeed get tricky. Would be interesting to see if the applied rules ids (or a digest) is part of the cache identity tags.

Odd that this is being run at 6am.

**Comment by erikhansen** [comment]
@fooman Yeah, I expect it won't be trivial to solve.

Right before you posted your comment, I updated the task description clarify the time the CRON runs (it's 1AM in the timezone configured in "STORES > General > Locale Options > Timezone").

**Comment by duffner** [comment]
@erikhansen, are there any programmatic updates occurring to the catalog each day, such as pricing updates?

**Comment by GuiltyNL** [comment]
I can confirm we have the exact same issue here on 2.3.3

We do not have pricing updates or changes, but we see the same cache tags being flushed whikr this cron is running.

**Comment by GuiltyNL** [comment]
This 'stale' thing is stupid. The problem is still here, don't close tickets  when they are not solved. The Magento team should put more efford in reviewing and solving this tickets themselves instead of the community.

**Comment by LeanderFS** [comment]
Still reproducible on 2.4.7-p3. This issue is killing our cache hit ratio. Is there any update on this issue?

**Comment by jesperbrejning** [comment]
We have the same issues on 2.4.7-p3.

This issue is faced in Adobe Commerce 2.4.2 release notes 
https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/adobe-commerce/2-4-2

Product and catalog caches now expire as scheduled. Previously, caches expired daily because сron ran the catalogrule_apply_all task once daily, which re-indexed all catalog rules and dependent indexers, and cleared the cache for all products and categories.

But we have see this issue in 2.4.7-p3.
