### ISSUE TITLE
setup payment module on store level

### ISSUE THREAD

**Issue by eversunsoft** [magento/magento2#2651]
suppose there's a franchise business, with different physical locations, each location have multiple languages. So I create a website to represent the franchise business; then create one store(group) for each physical location, under each store there will be store views to present different languages. Currently, the payment module setup is only available on the store view level,  how can one physical location(corresponds to one group_id) have one payment module setup, so each store view will simply load the payment module configuration from the store level rather than creating it's own payment module configuration? 

p.s. this topic was raised on the Magento forum earlier, Alan suggested to raise an issue here

**Comment by alankent** [comment]
(For internal folks - this is a product feature suggestion for the PMs to take into consideration.)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/setup-payment-module-on-store-level/idi-p/44774).
