### ISSUE TITLE
Unable to translate inline for checkout

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2652]
See screenshots, all area's marked in yellow, we are unable to translate inline:

![2015-12-09_11h52_22](https://cloud.githubusercontent.com/assets/13572447/11683719/efd5ba24-9e6c-11e5-8cd8-f19cb96432c4.png)

![2015-12-09_11h56_29](https://cloud.githubusercontent.com/assets/13572447/11683724/f80b2b70-9e6c-11e5-99ec-3aff44146bf3.png)

![2015-12-09_11h57_17](https://cloud.githubusercontent.com/assets/13572447/11683727/fb4f5626-9e6c-11e5-97f3-b4dea9f270a0.png)

**Comment by asemenenko** [comment]
Created an issue MAGETWO-46696

**Comment by asemenenko** [comment]
@ishakhsuvarov it seems that issue can be closed?

**Comment by ishakhsuvarov** [comment]
@asemenenko Not all issues linked to `MAGETWO-46696` are closed, so ticket may remain open for now.

**Comment by ishakhsuvarov** [comment]
@SidneyBilliet Closing this ticket for now, as issues related to inline translation in checkout seem to be fixed. Please feel free to reopen if you have any questions.

**Comment by SidneyBilliet** [comment]
Still having the same issues with parts that cannot be translated. When translating them inline, and clearing cache storage the entered translations do not appear.
Using Magento 2.0.2
This ticket needs to be reopend.
![2016-04-25_14h51_12](https://cloud.githubusercontent.com/assets/13572447/14784664/008bed4c-0af7-11e6-8815-293c8a4ce1d9.png)

Same issues on checkout step 2
![2016-04-25_15h01_50](https://cloud.githubusercontent.com/assets/13572447/14784705/3827845a-0af7-11e6-9f8f-bc67d492046e.png)
