### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26524]
### Description (*)
I would like some performance to be added to magento so my day of developing magento webshops doesn't mainly consist of waiting. 

### Expected behavior (*)
that I won't have to run setup:di:compile every time I make a oneliner change, get coffee and then to come back to see that magento requires more babysitting and has ran into some new permissions problem.

### Benefits
Because after maybe a 40 - 60 times speedup, Magento 2 will be worth using. 

### Additional information
Google stopped using a language because of the speed of the compiler. and that was with GCC. the speed of your disasterous compiler is beyond unbelievable. I sure wonder how anyone managed to create anything beyond "hello world" in it.

**Comment by bartoszkubicki** [comment]
Magento could be faster, but..
 
[First take a look at this](https://devdocs.magento.com/guides/v2.3/config-guide/bootstrap/magento-modes.html) - on developer mode you shouldn't have to make di compile every time. 
Permissions problem don't happen unless you execute you commands from wrong user.

**Comment by engcom-Hotel** [comment]
I agree with @bartoszkubicki . In developer modeyou have not to run `set:di:compile` for every change.
If you make changes in non-cached file you can just refresh the page and new added code will be run. 
So i have to close this issue as non-issue. 

Thanks for your report!
