### ISSUE TITLE
The country / region of mail sent from the admin panel is translated into the admin locale.

### ISSUE THREAD

**Issue by Taku-Yamashita** [magento/magento2#26521]
### Preconditions (*)

1.  Magento2.3.3
2. PHP7.2
3.  Two stores (JP & EN)
4.  Admin user locale is ja_JP
### Steps to reproduce (*)

1. place order  in EN store.
2. send order Email from admin panel using admin user locale ja_JP.

### Expected result (*)
Displayed in English.

<img width="171" alt="スクリーンショット 2020-01-24 17 48 39" src="https://user-images.githubusercontent.com/27942145/73056202-c99fc700-3ed1-11ea-9daf-e7f179650233.png">

### Actual result (*)
Country is Displayed in Japanese (admin user locale) even though this order is placed on EN store.

<img width="182" alt="スクリーンショット 2020-01-24 17 48 32" src="https://user-images.githubusercontent.com/27942145/73056222-d8867980-3ed1-11ea-8ef0-c2b240e87c3e.png"> 

if I change admin panel locale to en_US from ja_JP , it will work fine.

When sending mail from admin panel, Magento\Backend\Model\Locale\Resolver::setLocale method is used. And it force to set admin user local to county & region .

**Comment by Taku-Yamashita** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Taku-Yamashita. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Taku-Yamashita, here is your [Magento instance](https://i-26521-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26521-2-4-develop.instances.magento-community.engineering/admin_e831](https://i-26521-2-4-develop.instances.magento-community.engineering/admin_e831)
Login: `9c9f1517` Password: `2e8c375a74bc`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30798` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ilnytskyi** [comment]
The country is not translated in async mailing mode too. 
e.g. enable async sending; use a few stores with different locales; see that translation falls to default store locale

**Comment by shikhamis11** [comment]
I am working on this issue at #MM20IN

**Comment by Emanuel-23** [comment]
I can confirm this. When changing the admin locale to EN all email transactions use the EN country string instead of the german one, even though the store/storeview has correctly been set to DE (german).

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment]
Hi @Taku-Yamashita. Thank you for your report. 
The issue has been fixed in magento/magento2#31875 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [c0d11778a646ed160aed39f95ba8fff908f803be](https://github.com/magento/magento2/commit/c0d11778a646ed160aed39f95ba8fff908f803be)
 - [e971004d32752f53fc7733bf724a4ffe5e601176](https://github.com/magento/magento2/commit/e971004d32752f53fc7733bf724a4ffe5e601176)

The fix will be available with the upcoming 2.4.3 release.
