### ISSUE TITLE
Braintree GraphQL Create Token 

### ISSUE THREAD

**Issue by guoni** [magento/magento2#26529]
### Preconditions (*)
 "magento/product-community-edition": "2.3.3",
  "paypal/module-braintree": "^3.4"

### Steps to reproduce (*)
1. GraphQL Request with this query 
```graphql
mutation {
    createBraintreeClientToken
}
```
### Expected result (*)
1. braintree client token
```json
 {
    "data": {
        "createBraintreeClientToken": "********************"
    }
}
```
### Actual result (*)
Response:
```json
{
    "errors": [
        {
            "debugMessage": "Argument 1 passed to Magento\\Braintree\\Model\\Adapter\\BraintreeAdapterFactory::create() must be of the type array, integer given, called in /var/www/vendor/magento/module-braintree-graph-ql/Model/Resolver/CreateBraintreeClientToken.php on line 68",
            "message": "Internal server error",
            "category": "internal",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "createBraintreeClientToken"
            ]
        }
    ]
}
```

Code: 
```php
// vendor/magento/module-braintree-graph-ql/Model/Resolver/CreateBraintreeClientToken.php
...
 68       return $this->adapterFactory->create($storeId)->generate($params);
...
```

The adapter need (optionally) an array as parameter (int given).

StoreId is retrieve in the paypal/module-braintree by another way (see vendor/paypal/module-braintree/Model/Adapter/BraintreeAdapter.php > vendor/paypal/module-braintree/Model/StoreConfigResolver.php )

Thanks

**Comment by engcom-Echo** [comment]
Hi, @guoni. Thank you for your report.
Unfortunately I could not repeat it
Make sure that your modules are configured correctly.
I got the correct result: 
![image](https://user-images.githubusercontent.com/51681435/73538045-a2e21300-4432-11ea-8311-1aaecb5f5526.png)

Maybe you can specify more detailed steps for reproducing.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by guoni** [comment]
Thanks @engcom-Echo.

I have found the problem and it concern the module "paypal/module-braintree": "^3.4".

Explanations : 
paypal/module-braintree replace the module magento/module-braintree and the BraintreeAdapterFactory is missing so Magento 2 create automatically the file in generate/code folder with the default parameter $data = []  (the "original" method optionally need a $storeId = null)

```
src: generated/code/Magento/Braintree/Model/Adapter/BraintreeAdapterFactory.php
public function create(**array $data = []**)
{
      return $this->_objectManager->create($this->_instanceName, $data);
}
```

I am sorry for the inconvenience. I will notice the Paypal Braintree module developers. 

Best,
Guillaume
