### ISSUE TITLE
Klarna Payment Causes Blank Checkout for Free Products (Downloadable)

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#26531]
On Magento 2.2.8, Klarna Payments breaks the checkout, causing a blank screen when a downloadable product is selected, and a Cart Price rule gives 100% discount. 

### Preconditions (*)

1. Magento 2.2.8
2. Klarna Payments Enabled
3. Category Price Rule, giving 100% discount to specific products.

### Steps to reproduce (*)

1. Create Cart Price Rule Giving 100% Discount for Specific products. Ours is based on specific categories, and only applies to specific customer groups, downloadable products.
<img width="888" alt="Screen Shot 2020-01-24 at 1 06 35 PM" src="https://user-images.githubusercontent.com/36938969/73092327-68183200-3eaa-11ea-8786-887a676c83a1.png">
2. Enable Klarna Payments.
3. Create downloadable product that cart price rule applies to.
4. Purchase downloadable product. 

### Expected result (*)

1. Checkout displays no payment options and allows you to place the order for free.

### Actual result (*)

1. Checkout screen is blank minus the header.

**Comment by gulshanchitransh** [comment]
I am working on this issue #mm20in

**Comment by sdzhepa** [comment]
Hello @nickpiro 

We are not able to reproduce this issue on the 2.4 version.
Seems it was fixed.
