### ISSUE TITLE
Order status not translated

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26539]
Making custom order statuses will not translate in the order grid when using multiple store views.

### Preconditions (*)

1. Magento 2.3.3
2. Multiple store views
3. Multiple languages

### Steps to reproduce (*)

1. Create mutliple store views
2. Install a second language pack
3. Create custom order status and enter translation for both
4. Assign language setting for admin user
5. View order grid. Status name is still in english.

### Expected result (*)

Order status in selected language.

### Actual result (*)

Order status is not translated and shows up in english.

**Comment by engcom-Hotel** [comment]
Hello @Zyles 
This is expected behavior. If you add your new order status you have to manually add translation in e.g. de_DE language pack. 
You can do it here(if you are using Mageplaza language packs):
![image](https://user-images.githubusercontent.com/51681618/73175427-d2cba680-4112-11ea-870b-13eab2225d73.png)

Hope it helps.

So i have to close this issue as non-issue.

Thanks for your report!

**Comment by Zyles** [comment]
Then what is the point of "Store View Specific Labels" option?

**Comment by Zyles** [comment]
Please explain what these fields are for:

![image](https://user-images.githubusercontent.com/1741593/73351839-26afca00-4290-11ea-802d-e75637140a84.png)

**Comment by Zyles** [comment]
Still awaiting response. Should I file a new ticket?

**Comment by engcom-Hotel** [comment]
Hello @Zyles 
"Store View Specific Labels" option renaming a name of attribute for some store view.

**Comment by Zyles** [comment]
@engcom-Hotel 
> Hello @Zyles
> "Store View Specific Labels" option renaming a name of attribute for some store view.

No this is not on an attribute, this is on ORDER STATUS.

Again, what is the point of this if it is not used?

**Comment by aadmathijssen** [comment]
Store view specific order status labels are in use. In fact, when looking at the code of the [\Magento\Sales\Model\Order\Status::getStoreLabel](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Sales/Model/Order/Status.php#L144-L159) they actually have preference over CSV translations. See my [comment](https://github.com/magento/magento2/issues/26785#issuecomment-663574853) in issue #26785 for details.
