### ISSUE TITLE
Install magento 2.0 successfully but backend and frontend  getting error

### ISSUE THREAD

**Issue by karthik-bgdins** [magento/magento2#2654]
Hi, 
I have setup magento 2.0 successfully but when i login on backend and frontend. i can't click on anything. there are many bugs on console relate to js and css.
![dashboard](https://cloud.githubusercontent.com/assets/16151115/11685087/75fe80ca-9e9c-11e5-8f2c-5abed2458bb1.png)

![homepage](https://cloud.githubusercontent.com/assets/16151115/11685125/c5d0b10e-9e9c-11e5-8b96-8f5a19084a88.png)

**Comment by ninepointsvn** [comment]
You may need to run 

```
grunt refresh
```

in magento directory after installation.
