### ISSUE TITLE
Order status pending payment not changing to processing after invoicing

### ISSUE THREAD

**Issue by shyam100379** [magento/magento2#26541]
Order status is not getting updated from pending payment to processing once invoice is generated. When a customer choose payment option and click order, he/she will be redirected to payment gateway making that order as pending payment. Somehow the order is not fulfilled and order stays as pending payment.

### Preconditions (*)
1. Magento 2.3.2
2. Single store
3. Payment method which makes redirect to that corresponding payment gateway once order is clicked.

### Steps to reproduce (*)
1. Customer comes to checkout page and fills all needed information. 
2. Once clicking order, Magento sets pending payment as order status. 
3. Somehow customer didnt completed order, store user contact them personally and arrange cod or something, the invoice is generated.
4. Pending payment status not changing to processing or complete even after invoice and shipment is generated.

### Expected result (*)
1. Pending payment status need to change to processing once invoice is generated.
2. Processing turns complete once shipment is generated.

### Actual result (*)
1. Order status stays as pending payment even after shipment is generated

**Comment by shyam100379** [comment]
Hi didnt anybody checked the mentioned issue. Its seems their is a bug in the system, order status from pending payment not getting updated even if that order is marked as complete. Please advise.

**Comment by sedonik** [comment]
Hi

Cause I didn't reproduce moment when after Payment Getaway it lefts status "pending_payment'. I've only changed status in DB. Here is a screenshot where should be set (in item #26541).

![pending_payment](https://user-images.githubusercontent.com/5873715/74853150-2f9f3300-5346-11ea-88fa-f7412b0f9362.jpg)

**Comment by aqdennis** [comment]
Facing the same problem in versions 2.3.2.  
We use Mollie Payments as our PSP and after successful payment status remains on Pending, hence neither we nor the client will receive a confirmation e-mail....
I've tried the fix as described in https://github.com/magento/magento2/issues/18148, but without result.

**Comment by woutersamaey** [comment]
I also have a store facing this issue. The invoice is created + marked as paid. The total due amount drops to 0, but status stays "pending payment".

My case is with a custom built payment module that extends the now deprecated \Magento\Payment\Model\Method\AbstractMethod

Perhaps this is related somehow to the deprecation of this model?

**Comment by ihor-sviziev** [comment]
Hi @woutersamaey,
This issue duplicates https://github.com/magento/magento2/issues/25659 that was already fixed.
I'm closing this issue as duplicate
