### ISSUE TITLE
Managing quantity at website level in magento 2.3.2

### ISSUE THREAD

**Issue by MeenaMonika** [magento/magento2#26555]
We have created two websites (website_A and website_B). We want to manage quantity at the website level. In website_A, quantity is set to be 200 and website_B, quantity is set to be 300. I want to set each and every product quantity on the website level. How can I manage that in Magento2?

### Preconditions (*)

Tested on Magento2.3.2 version.

### Steps to reproduce (*)

1. Create multi-website Website_A and Website_B.
2. Save the product quantity at the website level. Website_A product quantity is set to be 200 and Website_B product quantity is set to be 300.

### Expected result (*)

We need Website_A Quantity is 200 and Website_B quantity is 300.

### Actual result (*)

Quantity is managed at the Global level. The last updated quantity affects the entire product.

**Comment by shikhamis11** [comment]
Hi @MeenaMonika 
In latest magento versions magento has provided feature for MSI .. with that you can create stocks for website and can assign sources in that and at product level you can assign products into sources .. in this way you can handle quantity at website level .. you can ave more details about MSI by below link 
https://devdocs.magento.com/guides/v2.3/inventory/
