### ISSUE TITLE
Product Image is not generated from cache in product list page but is available in the product main page

### ISSUE THREAD

**Issue by Mathanagopal97** [magento/magento2#26556]
### Summary of the issue
I was implementing attributes as swatches(both visual and text based) for the configurable products. I have separate set of images for the attributes in every product. I also made sure that the swatches are visible in the product listing page. When I select the swatches from the product listing I am not getting a image from the cache. But when I click on the product and go to its main page, I get the images from the swatches. What is the reason behind this? Is there something wrong in my system?

### Preconditions (*)

1.  Magento ver. 2.3.3
2.  PHP 7.3.11-0ubuntu0.19.10.2 (cli)
3.  mysql  Ver 8.0.18-0ubuntu0.19.10.1 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce (*)

1. Create a new configurable product with product attributes on your own (Eg. Shirt with size and color)
2. Create the configurations and provide separate images.
3. Make sure that the product attributes are of type swatch and it is visible in the product listing
![Catalog input type for store owner](https://i.imgur.com/oGglE93.png)
![Used in product listing](https://i.imgur.com/XK0OiMX.png)
### Expected result (*)

1. I should be able to view the image change on the product listing page. But I am not getting that result

### Actual result (*)

1. In the product Listing page the swatches are visible for a particular product
![Step 1](https://i.imgur.com/CUWZX2I.png)
2.  When I click on the swatches the image is not updated. Instead I get a predefined magento image.
![Step 2](https://i.imgur.com/RDYrYkQ.png)
3. But when I go to the product page and select the required swatches, the image is updating.
![Step 3](https://i.imgur.com/ZNFJhsK.png)

**Comment by Mathanagopal97** [comment]
When I did some debugging on my own I found that the images are delivered from the cache and I think the following screenshots should explain more clearly than my words.
1. Look at the files generated in the pub/media/catalog/product/cache in the first page load
![Files at the beginning of the page load](https://i.imgur.com/6g798os.png)
2. The image is loaded from a cache folder whose name starts with d6574be
![Image from a cache](https://i.imgur.com/Zggtw1r.png)
3. Selecting the swatches
![Imgur](https://i.imgur.com/y7QdeAA.png) 
4. When I click on the swatches a new cache folder is generated whose name starts with 3a332
![New cache folder](https://i.imgur.com/BRpahnz.png)
5. And the image is loaded from the folder whose name starts with 3a332
![Imgur](https://i.imgur.com/uECWgAI.png)

When I went and searched for the folder that starts with "3a332" in pub/media/catalog/product/cache it is not present there. But rest of the files and folder are present there.

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97, here is your [Magento instance](https://i-26556-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26556-2-4-develop.instances.magento-community.engineering/admin_6e2b](https://i-26556-2-4-develop.instances.magento-community.engineering/admin_6e2b)
Login: `91eef5bc` Password: `46b28be59dac`
Instance will be terminated in up to 3 hours.

**Comment by Mathanagopal97** [comment]
> Hi @Mathanagopal97, here is your [Magento instance](https://i-26556-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-26556-2-4-develop.instances.magento-community.engineering/admin_6e2b
> Login: `91eef5bc` Password: `46b28be59dac`
> Instance will be terminated in up to 3 hours.

Instance not working time - 14:23:00 IST Tuesday, 28 January 2020

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97, here is your [Magento instance](https://i-26556-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26556-2-4-develop.instances.magento-community.engineering/admin_24a2](https://i-26556-2-4-develop.instances.magento-community.engineering/admin_24a2)
Login: `54c629f1` Password: `99351c5c9328`
Instance will be terminated in up to 3 hours.

**Comment by Mathanagopal97** [comment]
@magento-engcom-team how to reindex in magento 2.4 instance provided by you?

**Comment by Mathanagopal97** [comment]
@magento how to reindex in magento 2.4 instance provided by you?

**Comment by Mathanagopal97** [comment]
I am unable to add any product in the instance provided by you. The magento indexer is not working properly. Please look into it.

**Comment by Mathanagopal97** [comment]
I am not able to reproduce the this issue in magento 2.4. Going to check in a new version of magento 2.3

**Comment by Mathanagopal97** [comment]
> I am not able to reproduce the this issue in magento 2.4. Going to check in a new version of magento 2.3

It is working fine in the fresh version of magento 2.3. I am closing this issue.
