### ISSUE TITLE
Ajax pagination issue with Varnish

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26557]
### Preconditions (*)

1. Magento 2.3.3
2. Varnish 6
3. Amasty layered navigation extension uses ajax calls for next page and previous pages
4. SSL enabled
5. Redis

### Steps to reproduce (*)

1. After setting up above configuration, navigation through category pages. Previous and next page clicks via Ajax calls works fine.
2. Next day no response after clicking previous and next category pages.

### Expected result (*)

1. Next page and previous page clicks via Ajax should work fine.

### Actual result (*)

1. Next page and previous page clicks via Ajax is not working. Issue disappears after clearing page cache.

**Comment by TimQSO** [comment]
@monotheist What version of Amasty Improved Layered Navigation are you using? We have a live setup like yours only with Varnish 5, without this issue.

**Comment by monotheist** [comment]
@GuiltyNL We are using version 2.13.1. Could please post your Redis config part from env file? Below is what I have in my file.

```
'MAGE_MODE' => 'production',
    'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '/var/run/redis/redis.sock',
            'port' => '0',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '0',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '1',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000'
        ]
    ],
    'cache_types' => [
        'config' => 1,
        'layout' => 1,
        'block_html' => 1,
        'collections' => 1,
        'reflection' => 1,
        'db_ddl' => 1,
        'eav' => 1,
        'customer_notification' => 1,
        'full_page' => 1,
        'config_integration' => 1,
        'config_integration_api' => 1,
        'translate' => 1,
        'config_webservice' => 1,
        'compiled_config' => 1,
        'amasty_shopby' => 1,
        'google_product' => 1,
        'vertex' => 1
    ],
    'install' => [
        'date' => 'Tue, 17 Oct 2017 22:15:39 +0800'
    ],
    'cache' => [
        'frontend' => [
            'default' => [
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => '/var/run/redis/redis.sock',
                    'database' => '1',
                    'port' => '0',
                    'compression_threshold' => '2048',
                    'compression_library' => 'gzip',
                    'log_level' => '1',
                    'max_concurrency' => '6',
                    'break_after_frontend' => '5',
                    'break_after_adminhtml' => '30',
                    'first_lifetime' => '600',
                    'bot_first_lifetime' => '60',
                    'bot_lifetime' => '7200',
                    'disable_locking' => '0',
                    'min_lifetime' => '60',
                    'max_lifetime' => '2592000'
                ],
                'id_prefix' => '537_'
            ],
            'page_cache' => [
                'id_prefix' => '537_'
            ]
        ]
    ],
```

**Comment by TimQSO** [comment]
Note, we have session locking disabled because of a performance issue in our checkout.

```
'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '/var/run/redis/redis.sock',
            'port' => '0',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '2',
            'compression_threshold' => '2048',
            'compression_library' => 'lzf',
            'log_level' => '1',
            'max_concurrency' => '600',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '1',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000'
        ]
],
```

```
'cache' => [
        'frontend' => [
            'default' => [
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => '/var/run/redis/redis.sock',
                    'port' => '0',
                    'database' => '0',
                    'connect_retries' => '2',
                    'compress_data' => '0'
                ],
                'id_prefix' => '105_'
            ],
            'page_cache' => [
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => '/var/run/redis/redis.sock',
                    'port' => '0',
                    'database' => '1',
                    'connect_retries' => '2',
                    'compress_data' => '0'
                ],
                'id_prefix' => '105_'
            ]
        ]
    ],
```

**Comment by monotheist** [comment]
@GuiltyNL Noted. Thanks. I see that your redis frontend configuration is split into two sections. Default and Page_cache. While mine is missing Page_cache. Would this have any impact on caching performance?

**Comment by TimQSO** [comment]
You should change it to my settings. If you don't have Varnish, you are missing FPC in your setup.

**Comment by monotheist** [comment]
> You should change it to my settings. If you don't have Varnish, you are missing FPC in your setup.

@GuiltyNL I do have Varnish 6 running.

**Comment by TimQSO** [comment]
Sorry wasn't paying attention. :(

**Comment by monotheist** [comment]
Would you mind disclosing the theme that you are using on your store? I am using Ultimo but now the author has stopped updating.

**Comment by TimQSO** [comment]
We are using a complete custom made theme. :/

**Comment by GuiltyNL** [comment]
@monotheist We may have a related issue.

Here we get 404 errors on several category pages when they are served from Varnish. At first the cached pages work well and after some time they are giving a 404 until we clear the cache.

**Comment by pavlots** [comment]
@GuiltyNL 
Have you found solution with you 404 on category page? Faced with same issue

**Comment by engcom-Alfa** [comment]
Hi @monotheist . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop instance. Everything works as expected. 

**_Preconditions:_**

1. Magento 2.4-develop;
2. Varnish 6
3. Redis
![Screenshot from 2021-02-01 16-01-07](https://user-images.githubusercontent.com/51679138/106468849-218ae980-64a7-11eb-9409-63f2b22fa790.png)

**Manual testing scenario:**
 After setting up the above configuration, navigate through category pages. Previous and next page clicks via Ajax call works fine;

**Actual Result:** :heavy_check_mark:  The next day we received a response after clicking the pages of the previous and next category.

![Peek 2021-02-01 16-13](https://user-images.githubusercontent.com/51679138/106469805-6d8a5e00-64a8-11eb-8a4f-03df45b80382.gif)

Probably the problem may be related to Amasty layered navigation extension.

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
