### ISSUE TITLE
"Number of Products to Display" doesn't work for the Catalog Products Widgets

### ISSUE THREAD

**Issue by densen45** [magento/magento2#26564]
The setting `Number of Products to Display` for catalog products widgets has no effect, i.e. the amount of products shown by the widget is not limited to the provided value. Instead it shows all products passing the `Conditions`.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

Create a new CMS page with a product list widget.
 
1. Adminhtml: Content > Pages > Add New Page
2. Enter a `Page Title`, e.g. `Product List`
2. Add a widget to the content section
3. Choose `Catalog Products List` for `Widget Type` (can be reproduced with `Catalog New Products List` as well)
4. Set `Number of Products to Display` to e.g. 5
5. Create a `Condition` that is met by at least 6 product
6. Insert the widget
7. Set the `URL Key` under `Search Engine Optimization` e.g. to `product-list`
8. Save the page
9. Enter `your.domain/product-list` in your browser

### Expected result (*)

1. Only 5 products are shown (or whatever `Number of Products to Display` you set to)

### Actual result (*)

1. All products that pass the condition you configured in the widget are shown

### Further Information
I cannot reproduce this issue in Magento 2.3.2.

**Comment by densen45** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @densen45, here is your [Magento instance](https://i-26564-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26564-2-3-3.instances.magento-community.engineering/admin_e4c8](https://i-26564-2-3-3.instances.magento-community.engineering/admin_e4c8)
Login: `3761dbfa` Password: `c9a1c2c3b384`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26564-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26564-2-4-develop.instances.magento-community.engineering/admin_641b](https://i-26564-2-4-develop.instances.magento-community.engineering/admin_641b)
Login: `8750ae65` Password: `7b7ba8cff2aa`
Instance will be terminated in up to 3 hours.

**Comment by Mathanagopal97** [comment]
@ajijshekh123 how to reindex in magento 2.4 instance provided by @magento-engcom-team ?

**Comment by ajijshekh123** [comment]
Hello @densen45,
The issue is not reproduced in the Magento 2.3.3 and Magento 2.4 Instance. 
Thanks.

**Comment by densen45** [comment]
Hey @ajijshekh123,
you are right, I cannot reproduce the issue in the provided Magento 2.3.3 instance either. Therefore I close this issue. Many thanks for your investigation!
