### ISSUE TITLE
Magento CMS module haven't dispatches like Catalog module

### ISSUE THREAD

**Issue by mediclab** [magento/magento2#26567]
### Summary (*)
Magento CMS module haven't needed event dispatches for creating observers to controller actions. Catalog module also have few dispatches for a work, but it has a _controller_action_catalog_product_save_entity_after_ event.

### Examples (*)
Let's see **Magento\Cms\Controller\Adminhtml\Page\Save**
```php
public function execute()
    {
        ....

            $model->setData($data);

            $this->_eventManager->dispatch(
                'cms_page_prepare_save',
                ['page' => $model, 'request' => $this->getRequest()]
            );

            try {
                $this->pageRepository->save($model);
                $this->messageManager->addSuccessMessage(__('You saved the page.'));
                return $this->processResultRedirect($model, $resultRedirect, $data);
            } catch (LocalizedException $e) {
                $this->messageManager->addExceptionMessage($e->getPrevious() ?: $e);
            } catch (\Exception $e) {
                $this->messageManager->addExceptionMessage($e, __('Something went wrong while saving the page.'));
            }
     ....
```
### Proposed solution
I want it to be like this
```php
public function execute()
    {
        ....

            $model->setData($data);

            $this->_eventManager->dispatch(
                'cms_page_controller_save_before_save',
                ['page' => $model, 'request' => $this->getRequest()]
            );

            try {
                $this->pageRepository->save($model);
                $this->messageManager->addSuccessMessage(__('You saved the page.'));
                $this->_eventManager->dispatch(
                  'cms_page_controller_save_after_save',
                  ['page' => $model, 'request' => $this->getRequest()]
                );
                return $this->processResultRedirect($model, $resultRedirect, $data);
            } catch (LocalizedException $e) {
                $this->messageManager->addExceptionMessage($e->getPrevious() ?: $e);
            } catch (\Exception $e) {
                $this->messageManager->addExceptionMessage($e, __('Something went wrong while saving the page.'));
            }
     ....
```
This also applies **Magento\Cms\Controller\Adminhtml\Block**

Summary: It's very bad when there is no code unity with modules. And also very bad when code haven't have enough event to dispatch

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [Magento instance](https://i-26567-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26567-2-4-develop.instances.magento-community.engineering/admin_b669](https://i-26567-2-4-develop.instances.magento-community.engineering/admin_b669)
Login: `8cf0d654` Password: `35c2e6375278`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment]
#MM20IN

**Comment by gsomoza** [comment]
@Medic84 have you considered whether Plugins (Interceptors) can help you do what you want in this case? You could consider creating a Plugin for `PageRepository::save()` in this case, which would probably cover your use-case and would not require updating the core. 

In M2, Plugins are generally preferable over Observers for several reasons (performance and flexibility). Events are specifically useful when firing from private methods (which could raise the question of whether the method should be private in the first place) but that's not the case here.

**Comment by Medic84** [comment]
I need an event to understand where the model was saved from. User-side or programmatically save.

**Comment by gsomoza** [comment]
You can still use a Plugin for that: 

1. The plugin would only exist in the adminhtml area (etc/adminhtml/di.xml)
2. Your logic would only execute if the request is a web request, you can even check the request type  and the module name it was routed to. To do that, you can inject `Magento\Framework\App\RequestInterface` into the plugin to make some basic checks and check if it's an instance of `Magento\Framework\App\HttpRequestInterface` if you want to check for request method.

.. or you could submit a PR to launch a new event: I'm not saying that's not an option, I'm just saying there are other ways that _might_ be preferable. FYI I'm not a core maintainer: just trying to help triage.
