### ISSUE TITLE
"Save" button doesn't work

### ISSUE THREAD

**Issue by oldoldowl** [magento/magento2#26571]
### Preconditions (*)
Magento ver. 2.3.3 is installed

### Steps to reproduce (*)
1. Open System-->Integrations in the menu on the left side
2. Select "Add New Integration"
3. Fill in the required fields "Name" and "Password"
4. Try to save with "Save" button --> the button doesn't work. Nothing happening

### Expected result (*)
The save button should work when I press on it.

### Actual result (*)
The save button doesn't work. The New Integration isn't created

**Comment by oldoldowl** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oldoldowl. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oldoldowl, here is your [Magento instance](https://i-26571-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26571-2-4-develop.instances.magento-community.engineering/admin_e8cf](https://i-26571-2-4-develop.instances.magento-community.engineering/admin_e8cf)
Login: `54d56fad` Password: `63d8bddb9c03`
Instance will be terminated in up to 3 hours.

**Comment by oldoldowl** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oldoldowl. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by srsathish92** [comment]
@oldoldowl Issue is not reproducible in `2.4-develop` branch & `v2.3.3`. So I close the issue.
![integration](https://user-images.githubusercontent.com/18184256/73333409-b43eea00-428f-11ea-968b-6f21ae0dade8.png)
