### ISSUE TITLE
_wrapEsi() should always return http:// URLs

### ISSUE THREAD

**Issue by boldhedgehog** [magento/magento2#2657]
I'm trying to configure the frontend to be SSL only. So all my links start with https://

**Magento\PageCache\Observer\ProcessLayoutRenderElement::_wrapEsi()** generates URLs starting with https:// 

``` HTML
<esi:include src="https://magetwo.local/page_cache/block/esi/blocks/[%22catalog.topnav%22]/handles/[%22default%22,%22cms_index_index%22,%22cms_page_view%22,%22cms_index_index_id_home%22]/"/>
```

As I understand, Varnish has no SSL functionality, so this include is not processed.

Can the method **_wrapEsi()** be changed that way, so it always returns http:// links?

**Comment by bgkavinga** [comment]
@boldhedgehog we resolved this issue by starting varnish with **-p feature=+esi_ignore_https** option

**Comment by boldhedgehog** [comment]
Thanks, I'm going to try this

**Comment by moderncodes** [comment]
How can I start varnish with -p feature=+esi_ignore_https?

**Comment by erikhansen** [comment]
@moderncodes See this Stack Exchange answer for how to start Varnish with `esi_ignore_https` enabled: http://magento.stackexchange.com/a/100128/2142

Be aware that this option is only available in Varnish 4 (not Varnish 3).
