### ISSUE TITLE
Not Generating Auto Generate coupons Code and getting this - Message is added to queue, wait to get your coupons soon

### ISSUE THREAD

**Issue by iindranil** [magento/magento2#26589]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.2

### Steps to reproduce (*)

1. Create a Cart Price Rule.
2. Coupon option "Specified Coupon"
3. Checked the Auto-Generated checkbox.
4. Under the "Manage Coupon Code", Enter Coupon Qty 2 and Enter discount details then click on the Generate Button.

### Expected result (*)

1. It should add two rows with generated coupon detail. 

### Actual result (*)

1. Getting this success message - Message is added to the queue, wait to get your coupons soon.

I've configured cron correctly from the server-side as per Magento [documentation](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-overview). That's why other cron related functionality is working as expected.

Please note, I've already tried these. See below.

1. Ran Magento cron command manually from ssh after getting above message.
    `bin/magento cron:run`
2. Checked server file permission, user permission.
3. Checked log files and found nothing related to this issue.

**Comment by engcom-Echo** [comment]
Hi, @iindranil. Thank you for your report.

You can able to process all codegeneratorProcessor queue items with the next command:

> $ bin/magento queue:consumers:start codegeneratorProcessor

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by iindranil** [comment]
Hello @engcom-Echo, Thank you for your suggestion.

> $ bin/magento queue:consumers:start codegeneratorProcessor

I've run this comment via SSH and getting this error: 

```
In State.php line 136:
                            
  Area code is already set  
                            
queue:consumers:start [--max-messages MAX-MESSAGES] [--batch-size BATCH-SIZE] [--area-code AREA-CODE] [--pid-file-path PID-FILE-PATH] [--] <consumer>
```

Please suggest what I need to do next,

Thank you again!
Indranil

**Comment by iindranil** [comment]
Hello @engcom-Echo,

I got the issue and I confirmed that this is not related to Magento core. 

This is happening due to one thrid party extension where they have used function `setAreaCode`  in the wrong format.

Thank you for your answer!

**Comment by alexvais** [comment]
What module caused that issue?

**Comment by MadonnaRagu** [comment]
Yes, which module caused this issue???

**Comment by MadonnaRagu** [comment]
@iindranil - Could you please let us know which module caused the issue? Thanks!

**Comment by peterjaap** [comment]
@MadonnaRagu run this in your project root to find 3rd party extensies that use `setAreaCode` to find the culprit;

`find vendor -type f | xargs grep setAreaCode | grep -v vendor/magento/`

**Comment by MadonnaRagu** [comment]
> @MadonnaRagu run this in your project root to find 3rd party extensies that use `setAreaCode` to find the culprit;
> 
> `find vendor -type f | xargs grep -n10 setAreaCode | grep -v vendor/magento/`
> 
> and
> 
> `find app/code -type f | xargs grep -n10 setAreaCode | grep -v vendor/magento/`
> 
> `setAreaCode` should be called in the `execute` method, not in the `__construct` or `configure`.

Thank you so much! )

**Comment by techzilla** [comment]
> 
> 
> @alexvais @MadonnaRagu run this in your project root to find 3rd party extensies that use `setAreaCode` to find the culprit;
> 
> `find vendor -type f | xargs grep -n10 setAreaCode | grep -v vendor/magento/`
> 
> and
> 
> `find app/code -type f | xargs grep -n10 setAreaCode | grep -v vendor/magento/`
> 
> `setAreaCode` should be called in the `execute` method, not in the `__construct` or `configure`.

Isn't this only applicable to code in a Console/ directory?

**Comment by techzilla** [comment]
I found the cause, it was the command/console module in weltpixel pearl theme, setting area code in an included class, the included class set it within the constructor.  Explains this problem, fixed it.

**Comment by ctadlock** [comment]
> I found the cause, it was the command/console module in weltpixel pearl theme, setting area code in an included class, the included class set it within the constructor. Explains this problem, fixed it.

Where exactly was the problem in the WeltPixel code and what did you change?

**Comment by alitopaloglu** [comment]
Same issue happened to me today, found a 

$state->setAreaCode(Area::AREA_ADMINHTML);

in one of my custom commands constructor.

Moved that code from constructor to the execute method and issue is fixed.
