### ISSUE TITLE
Ability to modify Design Package/Theme field after widget creation.

### ISSUE THREAD

**Issue by ajithkumar-maragathavel** [magento/magento2#26585]
### Description (*)

Navigate to **Content -> Elements -> Widgets** and click **Add Widget** button.
Select Type in the widget settings and select Design Theme in widget settings and click continue. 
After creating a widget for a specific theme, the **Design Theme filed becomes non-editable**. 
There is no way for admin user to change the widget Design  Theme configuration after creating a widget.

### Expected behavior (*)

It would be really useful for admin users if they can edit the Design Theme configuration after creating the widget.

### Benefits

If these features are available, then the admin user can easily change the Design Theme configuration for an already created widget for any theme.

### Additional information

I would like to know why the Design Theme configuration setting is non-editable once, the widget is created. 
Really curious to know the reason behind it.

**Comment by ajithkumar-maragathavel** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-26585-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26585-2-4-develop.instances.magento-community.engineering/admin_9bba](https://i-26585-2-4-develop.instances.magento-community.engineering/admin_9bba)
Login: `e88a05f1` Password: `8ed0c7405382`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Echo** [comment]
Hi, @ajithkumar-maragathavel. Thank you for your report.
A twain of settings "Type" and "Design Package/Theme" determine the possible options for further widget settings.
For different "Type" and different "Design Package/Theme" further settings may differ.
Changing these parameters can lead to incorrect behavior after saving the widget.
Example: 

![screenshot](https://user-images.githubusercontent.com/51681435/73532806-21848380-4426-11ea-9059-ccf5918438bc.png)

![screenshot_1](https://user-images.githubusercontent.com/51681435/73532816-25b0a100-4426-11ea-8808-1c1121014f7a.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by sazo17** [comment]
Hello, recently I was interested in this topic and I want to consult to settle all the possible doubts of the community,

Understanding that these changes can break the scheme and functions of Widgets in conjunction with Themes

but

If there was the possibility of changing them and these changes made correctly, would this work correctly?

And if so, why not add the possibility of doing it with a warning of its use?
