### ISSUE TITLE
getExistsStoreValueFlag() in catalog product model returns wrong data

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#26581]
The getExistsStoreValueFlag function in \Magento\Catalog\Model\Product returns wrong information, if it is used on different products during one request.

### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Use  #26601 to create integration test
2. Run integration test with `../../../vendor/bin/phpunit testsuite/Magento/Catalog/Model/ProductTest.php` in directory `dev/tests/integration`
3. 

### Expected result (*)

1. All tests succeed

### Actual result (*)

1. Test testExistsStoreValueFlagForMultipleProducts fails

**Comment by engcom-November** [comment]
Hello @ochnygosch,

Thank you for the report and collaboration!

Looking at the PR, this issue can be confirmed.
