### ISSUE TITLE
Product tier price not getting calculated properly when MSRP is applied

### ISSUE THREAD

**Issue by Mathanagopal97** [magento/magento2#26587]
### Preconditions (*)

1. Magento 2.4-develop
2. Also in Magento 2.3.3

### Steps to reproduce (*)

1. Enable MSRP in 
    Store -> Configuration -> Sales -> Minimum Advertised Price
    Set Display Actual price on gesture
2. Create a new simple product. Set it's price, quantity and weight(optional)

- Price=100$
3. Go to advanced pricing and add a special price, add 2 or more tier pricing of your choice(All groups is preferred)
- ![image](https://user-images.githubusercontent.com/51681379/85772099-32ab9500-b725-11ea-846a-3729718a8ec5.png)

4. Save the product

### Expected result (*)

1. Exact price to be displayed when "Click for price is triggered".
2. Customer group price should be same as without MSRP
![image](https://user-images.githubusercontent.com/51681379/85742868-45fe3680-b70c-11ea-9620-ccf421c8b80e.png)

### Actual result (*)

1. Irregular price is being displayed
2. Price not properly render and is same for **Buy 2 for** and **Buy 3 for**
![Peek 2020-06-25 17-46](https://user-images.githubusercontent.com/51681379/85742618-0fc0b700-b70c-11ea-8a1f-60861e9183af.gif)

Here are the [Screenshots](https://imgur.com/a/7F0JRkM)

Note: Extension of the issue numbered #26583

**Comment by Mathanagopal97** [comment]
Yes, I was able to reproduce the issue on vanilla Magento instance 2.4. Check my screenshots

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97, here is your [Magento instance](https://i-26587-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26587-2-4-develop.instances.magento-community.engineering/admin_c3e3](https://i-26587-2-4-develop.instances.magento-community.engineering/admin_c3e3)
Login: `dec8c8af` Password: `fd77026fb90b`
Instance will be terminated in up to 3 hours.

**Comment by chirag-d-wagento** [comment]
I'm working on this issue. #MM20IN

**Comment by Mathanagopal97** [comment]
@chirag-d-wagento Were you able to reproduce the issue in magento 2.4-develop?

**Comment by chirag-d-wagento** [comment]
Yes I was able to reproduce this issue in 2.4-develop branch

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31033` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment]
Reproduced on 2.4-develop

**Actual Result:**
![test](https://user-images.githubusercontent.com/51679138/73653731-8f34e780-4692-11ea-9718-8f8cabbf9bcc.gif)

**Comment by ihor-sviziev** [comment]
Hi @Mathanagopal97 and @engcom-Alfa,
Why do you think it's an issue?

According to calculations - we have two tier prices:
1. 2 and more products - fixed price - $40
2. 3 and more products - discount 36% from regular price: $100 - $36 (36% from %100)= $64. 

According to prices that we got above - the lowest price was taken ($40), that's looks quite logical for me.

Don't you think so?

Related to https://github.com/magento/magento2/issues/26583#issuecomment-585112523

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35477` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
