### ISSUE TITLE
Edit Order doesn't bring over existing ordered products

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2659]
Current action:
- Click Edit Order
- This creates new order from existing order
- Products aren't brought over into new order

Desired action:
- Products are carried over to new order from existing order

v 2.0.0

**Comment by NadiyaS** [comment]
Hi @markoshust ,
thank you for reporting this issue. Current Magento version does not already have this bug.
Feel free to reopen this issue if you still have the same problem on the latest Magento version.
