### ISSUE TITLE
Composer dependency issue with 2.3.4

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#26592]
Trying to run `composer require magento/product-community-edition 2.3.4` is running into dependency issues:

- magento/product-community-edition 2.3.4 **requires magento/framework 102.0.4** -> satisfiable by magento/framework[102.0.4].
- magento/module-backend 100.2.4 **requires magento/framework 101.0.***

**Comment by mrtuvn** [comment]
modify your composer.json

add the line below in replace attribute (or add new if you don't have)
replace: {
"magento/module-backend": "101.0.4"
}

**Comment by engcom-Bravo** [comment]
> modify your composer.json
> 
> add the line below in replace attribute (or add new if you don't have)
> replace: {
> "magento/module-backend": "101.0.4"
> }

Hello @nbennett25 

Did this help to resolve your issue?

Thank you

**Comment by hostep** [comment]
@mrtuvn, @engcom-Bravo, please don't give such advise, that's really bad.

@nbennett25: have you tried running `composer require --no-update magento/product-community-edition 2.3.4` followed by `composer update`? Maybe that solves it, there is a bug in composer where it doesn't try it's very best to solve all dependencies when running `require`.

You could also try running `composer why-not magento/product-community-edition 2.3.4` that might give some hints as well.

If nothing helps here, can you give us a little bit more information, for example show the contents of your `composer.json` file?

**Comment by nbennett25** [comment]
@engcom-Bravo, @mrtuvn  - ultimately we were able to get this working by removing `sebastian/phpcpd` - it was requiring `phpunit/phpunit` which requires `php 7.0`, and M2.3.4 requires 7.1+
