### ISSUE TITLE
customer save performance issue 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#26603]
### Preconditions (*)

1. latest Magento
2. customer contains 50 address

### Steps to reproduce (*)

1. try to save customer
2. on save customer why Magento check each address and updating

### Expected result (*)

1. it should be saved address if anything change related to address

### Actual result (*)

1. on every customer save, it is calling each address and save it

More info for this:-
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php#L263

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30973` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ProkopovVitaliy** [comment]
I will work on it.

**Comment by sunilit42** [comment]
Any update on this?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
