### ISSUE TITLE
Create Order should force shipping selection before submission

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2660]
Current action:
- I can click Submit Order without selecting a shipping method. 

![screen shot 2015-12-09 at 11 44 37 am](https://cloud.githubusercontent.com/assets/437029/11691722/489061bc-9e6a-11e5-8fd5-c009327f599d.png)

Desired action:
- I should not be able to click Submit Order until a shipping method is selected.

Additional Notes:
- If a shipping method is selected, I do receive an error after the form submission that a shipping method wasn't selected. However, this is undesired as it requires a full page refresh and resubmission.

v2.0.0

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Create-Order-should-force-shipping-selection-before-submission/idi-p/45772).
