### ISSUE TITLE
Outdated Composer Packages - product-community-edition

### ISSUE THREAD

**Issue by jonathan-martz** [magento/magento2#26605]
### Preconditions (*)
1. a simple Magento2 Shop with Community Edition

### Steps to reproduce (*)
1. Update Magento2 from 2.3.3 to 2.4.3
2. use Proxy like Toran which uses repo.magento.com as source of package
3. clean composer cache
4. Run Composer update

### Expected result (*)
1. updates every package

### Actual result (*)
1. Doesnt find a possible package of versions, because of Missing Version of 2.3.4

### Error Message
Problem 1  - The requested package magento/product-community-edition 2.3.4 exists as magento/product-community-edition[2.0.5, 2.0.6, 2.0.7, 2.1.0-rc1, 2.1.0-rc2, 2.1.0-rc3, 2.1.0, 2.0.8, 2.0.9, 2.1.1, 2.0.10, 2.1.2, 2.1.3, 2.0.11, 2.1.4, 2.0.12, 2.1.5, 2.0.13, 2.1.6, 2.1.7, 2.0.14, 2.0.15, 2.1.8, 2.2.0-rc20, 2.2.0-rc21, 2.2.0-rc22, 2.2.0-rc23, 2.2.0-rc30, 2.1.9, 2.0.16, 2.2.0, 2.0.17, 2.2.1, 2.1.10, 2.1.11, 2.2.2, 2.0.18, 2.1.12, 2.2.3, 2.1.13, 2.2.4, 2.2.5, 2.1.14, 2.1.15, 2.2.6, 2.1.16, 2.2.7, 2.3.0, 2.1.17, 2.3.1, 2.2.8, 2.1.18, 2.3.2, 2.2.9, 2.3.3, 2.2.10, 2.3.2-p2, 2.0.0, 0.42.0-beta7, 2.0.1, 2.0.2, 2.0.3, 2.0.4] but these are rejected by your constraint.

Maybe releated to https://github.com/magento/magento2/issues/26604

**Comment by jonathan-martz** [comment]
Strange, for my colleague it works.
On my local machine it doesnt work and on the dev server it doesnt work.

Try it on a few Dev Servers with my composer token, cleaned composer cache and removed vendor, but nothing works, always version not found.

**Comment by sudheers-kensium** [comment]
@jonathan-martz I am able to upgrade using package magento/product-community-edition 2.3.4 without any issue. So I am closing this issue. Still you are facing an issue feel free to reopen and provide more details.
