### ISSUE TITLE
Sending shipping tracking info to customer should log to Shipping History

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2661]
After sending tracking number information for a shipment to a customer, it should log that the tracking information was emailed to the customer below the Submit Comment button just like a standard shipping history record.

![screen shot 2015-12-09 at 11 52 47 am](https://cloud.githubusercontent.com/assets/437029/11691972/6476be7a-9e6b-11e5-8b66-1ad174429156.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Sending-shipping-tracking-info-to-customer-should-log-to/idi-p/45771).
