### ISSUE TITLE
MFTF: AdminAddingNewOptionsWithImagesAndPricesToConfigurableProductTest is failing in CI process

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26610]
### Summary (*)
When working with https://github.com/magento/magento2/pull/26454 - I faced the failing test `AdminAddingNewOptionsWithImagesAndPricesToConfigurableProductTest`. Test outcome was completely unclear:
![image](https://user-images.githubusercontent.com/1639941/73534118-a66c9e80-4420-11ea-9cd9-6be2948fdf10.png)

Also, ScreenShot wasn't helpful at all:
![image](https://user-images.githubusercontent.com/1639941/73534152-b5ebe780-4420-11ea-8679-e75fbf3081b4.png)

I started to investigate with adding full Exception message to the Notification:
![image](https://user-images.githubusercontent.com/1639941/73534223-dcaa1e00-4420-11ea-8995-663016973f12.png)

As you see - it's trying to remove Product with ID = 5. But (!) the test hasn't created any Product with ID = 5:
![image](https://user-images.githubusercontent.com/1639941/73534267-04998180-4421-11ea-9e8b-dde4b5f30249.png)

So I got deeper - why it's actually trying to remove product ID = 5 and noticed that it's actually filtering product to remove:
![image](https://user-images.githubusercontent.com/1639941/73534306-1f6bf600-4421-11ea-884b-a1d6a8976809.png)

... by product name that is **empty**!
![image](https://user-images.githubusercontent.com/1639941/73534336-2e52a880-4421-11ea-9321-dbe5104d66f7.png)

That bug is caused by invalid handler introduced by Magento QA team and exists on other tests too - but by coincidence, the it's not overlapping with other test operating on the same data:

![image](https://user-images.githubusercontent.com/1639941/73534704-0a439700-4422-11ea-98ef-effb0bd3f3ce.png)

### Examples (*)
- https://github.com/magento/magento2/runs/415703140

### Proposed solution
C'mon, fix it :-)

**Comment by slavvka** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26611 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [b29cdcd238ded56050308d54aa22df3bc7672a43](https://github.com/magento/magento2/commit/b29cdcd238ded56050308d54aa22df3bc7672a43)

The fix will be available with the upcoming 2.4.0 release.
