### ISSUE TITLE
Color swatch tooltip arrow position is not proper on the Product detail page

### ISSUE THREAD

**Issue by tejash-wagento** [magento/magento2#26624]
### Summary
Color swatch attribute options tooltip arrow position is not proper on the Product detail page

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

On the Product detail page

### Expected result

![image](https://user-images.githubusercontent.com/15318347/73602948-1c4c4380-45a2-11ea-8bb5-29266ec8873e.png)

### Actual result

![image](https://user-images.githubusercontent.com/15318347/73602973-8e248d00-45a2-11ea-8b4d-60fa58e7f636.png)

**Comment by tejash-wagento** [comment]
#mm20in

**Comment by tejash-wagento** [comment]
Same issue on the category list page
solved on #26625

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31013` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tejash-wagento** [comment]
I have created Pull request in #26624

**Comment by desaiun** [comment]
give me 2.4-develop instance

**Comment by desaiun** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @desaiun. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @desaiun, here is your [Magento instance](https://i-26624-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26624-2-4-develop.instances.magento-community.engineering/admin_5363](https://i-26624-2-4-develop.instances.magento-community.engineering/admin_5363)
Login: `e4b6c205` Password: `c975ad509ff6`
Instance will be terminated in up to 3 hours.

**Comment by desaiun** [comment]
@tejash-wagento I have Check with Several Browser but not reproduce this issue in 2.4-develop branch.


![Screenshot-2020-2-29 Configurable Products Color Switch](https://user-images.githubusercontent.com/34401807/75604239-a97cac80-5afc-11ea-934b-6924877fc25e.png)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
