### ISSUE TITLE
Shipment date missing from Shipping details page

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2662]
No place to find out when the shipment took place from the shipping detail page:

![screen shot 2015-12-09 at 11 55 30 am](https://cloud.githubusercontent.com/assets/437029/11692069/d3e369c0-9e6b-11e5-9e92-4a7e33397c6e.png)

It should show the same date on other tabs/list views as so:

![screen shot 2015-12-09 at 11 56 23 am](https://cloud.githubusercontent.com/assets/437029/11692089/eb0952e0-9e6b-11e5-9f95-8543dc345948.png)

**Comment by NadiyaS** [comment]
Hi @markoshust,
thank you for your proposition of such future request. 
It will be queued for review according to other features' priority. 
Or you can do PR with implemented feature.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Shipment-date-missing-from-Shipping-details-page/idi-p/44772).
