### ISSUE TITLE
There should be a faster way to generate code on dev mode

### ISSUE THREAD

**Issue by degaray** [magento/magento2#2663]
When calling setup:di:compile it runs several processes to create all the code needed in all the application. This usually takes several minutes. There should be a a way to not run it in dev mode and let the code generate other code on the run.

**Comment by davidalger** [comment]
@degaray Were you running into a problem before running that command while in dev mode? The code generation in developer mode is all done on the fly, and so you shouldn't have to run this except when running in production mode.

**Comment by degaray** [comment]
I have tested it and it is working as you said. I had an error in my code and that is why it was not generating correctly.
