### ISSUE TITLE
ExtensionAttributesProcessor is stripping two characters arbitrarily

### ISSUE THREAD

**Issue by degaray** [magento/magento2#2664]
I am having an issue with `Magento\Framework\Reflection\ExtensionAttributesProcessor::buildOutputDataArray` it is stripping two characters arbitrarily in line 122 `$arrayElementType = substr($returnType, 0, -2);`. Consequently my code is braking. I guess those two characters are intended to strip `[]` from class name, however if they are not added, it strips the last two letters of the class giving an unexpexted error. It should check this and throw an exception instead of removing the `[]`.

**Comment by degaray** [comment]
It is fixed if brackets `[]` are added in extension_attributes.xml `<attribute type='some/class'` so it looks like this `<attribute type='some/class[]'` however I still think it should throw an exception after checking if the last two characters are brackets.

**Comment by okorshenko** [comment]
@degaray , thank you for reporting the issue. Internal ticket MAGETWO-46678

**Comment by arkadiych** [comment]
@degaray, could you give a code example, where the method doesn't work correctly?

**Comment by okorshenko** [comment]
Closing. @degaray , please, let us know if you still have an issue.
