### ISSUE TITLE
Table bottom border color different then thead and tbody border color

### ISSUE THREAD

**Issue by tejash-wagento** [magento/magento2#26648]
### Summary
Table bottom border color different then thead and tbody border color
On table footer border color : #e4e4e4
![image](https://user-images.githubusercontent.com/15318347/73605784-91327400-45c8-11ea-9f46-7590b02e8d2d.png)

But table other row border color: #CCCCCC 
![image](https://user-images.githubusercontent.com/15318347/73605849-76143400-45c9-11ea-93d4-d372a733fa73.png)

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

Recent Orders on My account page
Additional Address Entries on Address Book page

### Expected result

Additional Address Entries on Address Book page
![image](https://user-images.githubusercontent.com/15318347/73605591-26803900-45c6-11ea-8e96-96d994f1dfed.png)

Recent Orders on My account page
![image](https://user-images.githubusercontent.com/15318347/73605617-70691f00-45c6-11ea-9370-e36f57977846.png)

### Actual result

http://Your-Magento-Url/index.php/customer/address/index/
![image](https://user-images.githubusercontent.com/15318347/73605507-33505d00-45c5-11ea-858d-936385a65c6b.png)

http://Your-Magento-Url/index.php/customer/account/
![image](https://user-images.githubusercontent.com/15318347/73605517-5d098400-45c5-11ea-80da-f097063c702f.png)

**Comment by tejash-wagento** [comment]
#mm20in

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26648-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26648-2-4-develop.instances.magento-community.engineering/admin_fa60](https://i-26648-2-4-develop.instances.magento-community.engineering/admin_fa60)
Login: `5ca01748` Password: `ec368bb86ca3`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31069` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by desaiun** [comment]
give me 2.4-develop instance

**Comment by desaiun** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @desaiun. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @desaiun, here is your [Magento instance](https://i-26648-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26648-2-4-develop.instances.magento-community.engineering/admin_c67c](https://i-26648-2-4-develop.instances.magento-community.engineering/admin_c67c)
Login: `d7c026eb` Password: `28b470cf3bd3`
Instance will be terminated in up to 3 hours.

**Comment by desaiun** [comment]
Hi @tejash-wagento issue has been resolved?

**Comment by magento-engcom-team** [comment]
Hi @tejash-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26649 by @tejash-wagento in 2.4-develop branch
Related commit(s):
 - [3a5cc24f5e1537b4da4abb63ecbdd01c7c29865e](https://github.com/magento/magento2/commit/3a5cc24f5e1537b4da4abb63ecbdd01c7c29865e)

The fix will be available with the upcoming 2.4.0 release.
