### ISSUE TITLE
In the minicart edit and remove icon is not aligned.

### ISSUE THREAD

**Issue by chirag-wagento** [magento/magento2#26652]
### Summary
In the minicart edit and remove icon is not aligned with a qty input box.
### Preconditions
1. Magento 2x - This issue reproduce in all version.
### Steps to reproduce
 Add any item in the cart and check minicart edit and remove icon is not aligned with a qty input box.

### Expected result

![image](https://user-images.githubusercontent.com/15214167/73605984-33ebf200-45cb-11ea-85a2-ed09e58115f1.png)

### Actual result

![image](https://user-images.githubusercontent.com/15214167/73605978-25053f80-45cb-11ea-8b76-c61fda3db350.png)

**Comment by chirag-wagento** [comment]
#mm20in

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31018` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#27493 by @vasilii-b in 2.4-develop branch
Related commit(s):
 - [bbc6abca6ed62419c3e8759672f32541c1dfa476](https://github.com/magento/magento2/commit/bbc6abca6ed62419c3e8759672f32541c1dfa476)

The fix will be available with the upcoming 2.4.0 release.
