### ISSUE TITLE
Is changing store_Id in quote possible?

### ISSUE THREAD

**Issue by SergioMordente** [magento/magento2#26664]
In Magento 2.3.3 I have two stores and I use the API to create a cart and add the products with a Java application. This quote / cart is created using the client's token for / rest / V1 / carts / mine with store_id from the main store, until then everything worked perfectly. In the step of defining the delivery method I need to change the store_id for the store that will fulfill the order, and then my problem begins.
Connect to / rest / V1 / carts / cart_id with admin token and step customerId and storeId as parameter and return
{"message": "The customer cannot be added to the cart because the cart is not anonymous."}.
If I use the same token that created the quote the message is
{"message": "The consumer is not authorized to access% resources.", "parameters": {"resources": "Magento_Cart :: manage"}}.
Another alternative that I tried was to create a cart as a visitor but to proceed with checkout, I would have to convert it to the definitive cart, where as I understand it I could insert the customer and the store but I haven't yet defined the store, as it is defined by the method Of delivery.

Can you point me to where I'm going wrong or if what I need is not possible in the standard Magemto API?
### Summary (*)

Tenho

**Comment by engcom-Echo** [comment]
Hi, @SergioMordente, Thank you for your report.

You create a quote for an individual store using parameter /rest/<store_id>/V1/carts/mine.
Change "store_id" for the created quote impossible.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by rahimimo** [comment]
Acutally I managed changing the customer cart locale using 
/rest/en/V1/carts/mine

and the payload as 
```
{
    "quote":
    {
    "id": 23673,
    "customer": {
        "id": 92,
        "email": "ccc+33@gmail.com",
        "extension_attributes": {
            "is_subscribed": false
        },
        "custom_attributes": [
        ]
    },
    "store_id": 1
}
}
```
Could not find a way yet for guest-cart changing the cart.
