### ISSUE TITLE
Magento 2.3.1 problem z GA

### ISSUE THREAD

**Issue by Mirat-pl-eu** [magento/magento2#26666]
Hello,
Help, Magento 2.3.1 doesn't count my transactions.
What's the problem?

**Comment by engcom-Delta** [comment]
Hi @Mirat-pl-eu 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
