### ISSUE TITLE
One Step Checkout Billing Fails To Load With Virtual Items and No Default Shipping Address

### ISSUE THREAD

**Issue by bap14** [magento/magento2#26671]
### Preconditions (*)
1. Magento 2.3.4
2. PHP 7.3
3. Found in production

### Steps to reproduce (*)
1. Create new store running Magento 2.3.4
2. Enable One Step Checkout
3. Create virtual item (simple product, no weight)
4. Create customer account on frontend
5. Create address for customer, set only as "Default Billing Address"
6. Add virtual product to cart and proceed to checkout
7. If not logged in, log in
8. See two (2) steps in checkout but payment details form fails to load

### Expected result (*)
1. Billing address form appears OR default billing address with "Edit" button shows

### Actual result (*)
1. No form displays
2. Javascript error complaining about quote.getShippingAddress().canUseForBilling() is failing

### Extra Information

This appears related to #24131. My immediate solution to this, as it was a javascript error, is to add an extra condition to the logic on line 91 of `Magento_Checkout/js/view/billing_address.js`:

```
        this.isAddressSameAsShipping(
            newAddress != null &&
            quote.shippingAddress() && // Added to fix virtual item checkout with no shipping address
            newAddress.getCacheKey() == quote.shippingAddress().getCacheKey() //eslint-disable-line eqeqeq
        );
```

**Comment by bap14** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bap14. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bap14, here is your [Magento instance](https://i-26671-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26671-2-4-develop.instances.magento-community.engineering/admin_3868](https://i-26671-2-4-develop.instances.magento-community.engineering/admin_3868)
Login: `e4627a51` Password: `111843dd7b50`
Instance will be terminated in up to 3 hours.

**Comment by bap14** [comment]
With the development instance provided I was not able to reproduce this issue. Will close this issue as invalid as I can't reproduce it in the test environment.
