### ISSUE TITLE
Uncaught TypeError: resolver is not a function

### ISSUE THREAD

**Issue by adesigner2** [magento/magento2#2667]
After installation Magento 2 via git, if I'm going to Product Grid or Order Grid - I get 'Uncaught TypeError: resolver is not a function' in browser console and load spinner does not disappear.

/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/grid/provider.js:125 Uncaught TypeError: resolver is not a function

How to make standard products, orders grid work?

![screen shot 2015-12-10 at 10 37 18](https://cloud.githubusercontent.com/assets/13090498/11713253/278b6f8c-9f2a-11e5-8593-aea6839de4ee.png)

**Comment by michelsteege** [comment]
Same here, one moment it was working and then out of nowhere this error came up and it stopped...

**Comment by michelsteege** [comment]
And to make it more confusing, i have this on one pc but not on a different one...

**Comment by anton-huz** [comment]
Hi  michelsteege,
Looks like on on PC you have cached version of JS assets.
Try to open same page in in same browser, but in _Incognito mode_. If error absent, please flush cache in browser.

**Comment by michelsteege** [comment]
Thanks guz-anton it was cache, when i opened it in incoginto mode i got the same error but after manually clearing the (browser) cache it was gone!

**Comment by anton-huz** [comment]
Thanks Michel for your attention to this issue.

Dear adesigner2,
fill free to comment if you still has such issue.

**Comment by pwastack** [comment]
It beacause duplicated jQuery load. The plugin loaded into different jQuery instance. You need to remove the duplicate jquery load and wrap the function into a requirejs. I got the same problem when try to install Porto theme to Magento2. See more detail at http://magento2developer.com/blog/javascript-error-with-magento-porto-theme.html to fix the bug.
