### ISSUE TITLE
Magento UI Library markup removed from product text

### ISSUE THREAD

**Issue by digitalbricklayer** [magento/magento2#26678]
### Preconditions (*)

1. Magento 2.3.4 open source
2.

### Steps to reproduce (*)

1. Edit a product. Put the product text into HTML mode. Place ```<i class="fa fa-times" aria-hidden="true"></i>``` (from the Magento UI library) inside the product description.
2. Save & Close the product
3. Examine the product in the frontent. The "x" will be displayed on the product page
4. Edit the product again in HTML mode, the text will not have the ```<i class="fa fa-times" aria-hidden="true"></i>``` text. Somewhere down the line, probably when the product text is loaded and put into the wysiwyg,  Magento removed the ```<i class="fa fa-times" aria-hidden="true"></i>``` text.

### Expected result (*)

1. The ```<i class="fa fa-times" aria-hidden="true"></i>``` should not be removed from the product text.
2.

### Actual result (*)

1. The ```<i class="fa fa-times" aria-hidden="true"></i>``` was removed from the product text. I either now have to embed an image or use regular text instead.
2.

**Comment by digitalbricklayer** [comment]
@magento give me 2.3.4 instance-26678

**Comment by magento-engcom-team** [comment]
Hi @digitalbricklayer. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @digitalbricklayer, here is your [Magento instance](https://i-26678-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26678-2-3-4.instances.magento-community.engineering/admin_45da](https://i-26678-2-3-4.instances.magento-community.engineering/admin_45da)
Login: `f51cd798` Password: `e3cff4aaac02`
Instance will be terminated in up to 3 hours.

**Comment by digitalbricklayer** [comment]
I have managed to reproduce using the Magento instance provided except that the cross was not displayed on the product page. It was present in the HTML source code but was not displayed in the browser, presumably because Font Awesome was not available.

**Comment by engcom-Bravo** [comment]
Hello @digitalbricklayer 

Thank you for your report.

We had this issue opened earlier and closed it as _"not an issue"_ 
Wysiwyg will cut all empty HTML.

Please see the related issue and comments to it
https://github.com/magento/magento2/issues/21602

We have to close this. 

If you'll ever experience any issues with Magento, please fill free to create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 

Thank you for collaboration
