### ISSUE TITLE
Display Out of Stock configurable product options

### ISSUE THREAD

**Issue by seb-jean** [magento/magento2#26673]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. A configurable product with only one attribute for variant (just size, not color)
2. 3 simple products with attribute size : XL (stock 0) L (stock 100), S (stock 100).
3. Go to the product page

### Expected result (*)

1. Have the product with the 3 sizes displayed (XL, L, XS)

### Actual result (*)

1. I have the product with sizes L and S and not XL

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26673-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26673-2-4-develop.instances.magento-community.engineering/admin_0a98](https://i-26673-2-4-develop.instances.magento-community.engineering/admin_0a98)
Login: `1f8786df` Password: `c6d01d0a76fa`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @seb-jean,
I have verified this issue as per your steps and review the Actual and Expected result.
I didn't reproduce this issue in Default Magento 2.4 Instance.
Please review attached the screenshot and Let me know Should I close this issue or not? 
If you have added an extension or library please let me know.

**Admin_Screenshot:**
![AdminScreenshot](https://user-images.githubusercontent.com/24711761/73641444-061faf80-4696-11ea-96cd-c5e9233b17a0.png)

**Front end_Screenshot:**
![Frontend](https://user-images.githubusercontent.com/24711761/73641472-12a40800-4696-11ea-8f02-ca4119867260.png)

Thanks.

**Comment by seb-jean** [comment]
I see that you have the same problem: XL is not displayed.

**Comment by ajijshekh123** [comment]
Okay, I understand @seb-jean, It should be there on the front end and when the user selects the XL option, "Out of stock" status should be displayed.
Am I Right @seb-jean?

**Comment by seb-jean** [comment]
You are right :)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31017` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hello @seb-jean,
Thank you for report.
This issue is duplicate to #16069 and already discussed many times.
You can track the conversation from above issue id.

**Comment by seb-jean** [comment]
So in fact this is normal behavior?
