### ISSUE TITLE
Show by not working at one stage in address book

### ISSUE THREAD

**Issue by renard123** [magento/magento2#26677]
Show by not working at one stage in address book

### Preconditions (*)
Magento: 2.3.3

### Steps to reproduce (*)
- Register into store
- Address Book
- Add billing/shipping address
- Additional addresses -> Add 11 addresses
- Click on Show by to 20 (Working fine)
- Revert to Show by to 10 (Working fine)
- Click on 2nd pagination (Working fine)
- Repeat the process
- Click on Show by to 20 (Issue at one stage)

### Expected result (*)
Show by feature should work fine

### Actual result (*)
Can not show by selected value

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26677-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26677-2-4-develop.instances.magento-community.engineering/admin_18ac](https://i-26677-2-4-develop.instances.magento-community.engineering/admin_18ac)
Login: `78837715` Password: `8c4064b970ed`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @renard123. Thank you for your report.
Not able to reproduce the issue as provided steps by you.
Feel free to reopen with video attachment if you phase this issue again
