### ISSUE TITLE
Permission Issue for Admin User

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#26670]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)

1. Create an User
2. Add permission to 
   a. view order
    b. add comment
    c. edit order

### Expected result (*)

1. Admin user should have Order view/edit/add comment permission.

### Actual result (*)

1. Doesn't allow to add comment. No comment form in order view page.
2. Doesn't allow to edit order billing/shipping address

**Comment by adarshkhatri** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-26670-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26670-2-3-3.instances.magento-community.engineering/admin_c067](https://i-26670-2-3-3.instances.magento-community.engineering/admin_c067)
Login: `46ed7a9d` Password: `764b529fe3d1`
Instance will be terminated in up to 3 hours.

**Comment by adarshkhatri** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-26670-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26670-2-3-3.instances.magento-community.engineering/admin_eb68](https://i-26670-2-3-3.instances.magento-community.engineering/admin_eb68)
Login: `1c578f91` Password: `15039cbaba2c`
Instance will be terminated in up to 3 hours.

**Comment by adarshkhatri** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-26670-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26670-2-3-3.instances.magento-community.engineering/admin_a883](https://i-26670-2-3-3.instances.magento-community.engineering/admin_a883)
Login: `0f2f82c3` Password: `fc1514975669`
Instance will be terminated in up to 3 hours.

**Comment by adarshkhatri** [comment]
@magento give me 2.4 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance
