### ISSUE TITLE
Disabled products not being removed from existing customer carts

### ISSUE THREAD

**Issue by ngreimel-lt** [magento/magento2#26680]
### Preconditions (*)

1. Magento 2.3.2 (Upgrade from 2.2.6)
2. Magento Cloud environment

### Steps to reproduce (*)

1. Start logged in session for customer 1.
2. Add a product A to customer 1's cart.
3. As an admin, disable product A.
4. Return to customer 1's session.
5. Add product B to customer 1's cart.
6. View cart

### Expected result (*)

1. Expect to see product B in the cart.
2. Expect not to see product A in the cart, and a message indicating product A is unavailable.
3. Expect product A to be removed from the customer's quote, and proceed to checkout as an option.

### Actual result (*)

1. Product B is visible in the cart. PASS
2. Product A is not visible in the cart, and a message indicates there is an out of stock product. PARTIAL PASS
3. Product A still exists in the customer's quote. Proceed to checkout is disabled. FAIL

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26680-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26680-2-4-develop.instances.magento-community.engineering/admin_fdf3](https://i-26680-2-4-develop.instances.magento-community.engineering/admin_fdf3)
Login: `a05e4ef1` Password: `39d8842b4b74`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @ngreimel-lt,
I have verified this issue as per your steps to be reproduced. 
Product A is automatically removed after disabling the product on the admin section and Added Product B is not displayed on the shopping cart page.

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31068` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lalvesoliveira** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lalvesoliveira. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lalvesoliveira, here is your [Magento instance](https://i-26680-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26680-2-4-develop.instances.magento-community.engineering/admin_1d4a](https://i-26680-2-4-develop.instances.magento-community.engineering/admin_1d4a)
Login: `21211e71` Password: `6dbc4e8b69f9`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @lalvesoliveira

Are you still working on this issue?
If not please remove yourself from the assignment list, other guys ready to work on this issue.

Thank you in advance!

**Comment by lfluvisotto** [comment]
@sdzhepa I tested this issue on branch 2.4-develop and it isn't reproducible, once the product is disabled and saved via admin, product is deleted/removed from customer's shopping cart.

**Comment by sdzhepa** [comment]
Thank you @lfluvisotto  for verification and confirmation!

Close this issue as already fixed in the `2.4-develop`
