### ISSUE TITLE
Empty attribute value constant not seting null the atribute

### ISSUE THREAD

**Issue by adrianalin89** [magento/magento2#26696]
### Preconditions (*)

1. Magento version 2.3.3
2.

### Steps to reproduce (*)

1. Create a csv whit sku custom_atrr ( must be type select )
2. In the csv use the Empty attribute value constant __EMPTY__VALUE__

### Expected result (*)

1. Expect to have no more attribute option on that product
2. Expect in the db in the table catalog_product_entity_int on that product and that attribute id to have null or not be in the table 

### Actual result (*)

1. Result are that nothing happens the product steel have the attribute set

in magenot/module-catalog-import-export/model/import/product.php line 1801 

`$rowData = $productTypeModel->prepareAttributesWithDefaultValueForSave(
                    $rowData,
                    !$this->isSkuExist($rowSku)
                );`
$rowData will be a empty array.
 
the function is located in magenot/module-catalog-import-export/model/import/product/type/abstractType line 527

the only workaround i had is in this image 
I've added the read square code.
https://ibb.co/YWN8CNp

**Comment by engcom-Delta** [comment]
Hi @adrianalin89 , thank you for your report. I am not able to reproduce issue by steps you described on clean 2.4-develop.

**Steps to reproduce:**

- Create dropdown attribute and add it to Default Attribute set
![image](https://user-images.githubusercontent.com/51681379/74027127-3d50d200-49b0-11ea-8e7e-2db20e880192.png)

- Create simple product and set some value for dropdown attribute
[exported_product.csv.txt](https://github.com/magento/magento2/files/4170621/exported_product.csv.txt)

![image](https://user-images.githubusercontent.com/51681379/74027671-43937e00-49b1-11ea-9031-262e2a503c1a.png)

- Change attribute value to `__EMPTY__VALUE__` in csv file
- Import changed csv file
[import_product.csv.txt](https://github.com/magento/magento2/files/4170608/import_product.csv.txt)

**Result:**
:heavy_check_mark: Attribute value is unset on that product
:heavy_check_mark: In the db in the table `catalog_product_entity_int` `attribute id` has `null` value
![image](https://user-images.githubusercontent.com/51681379/74027945-e2b87580-49b1-11ea-8a88-f3115f430ab2.png)

If you'd like to update the issue, please reopen it.
