### ISSUE TITLE
Store view // product attribute / "Use default value" not working

### ISSUE THREAD

**Issue by mwieschke** [magento/magento2#26694]
### Preconditions (*)
1. Magento 2.3.3 installed from zip file. Updated using composer update
2. Multiple store mode
3. Multiple stores created
4. Multiple store views for one store

### Steps to reproduce (*)
1. create product on website level with name "test"
2. edit product attribute on store view level (attribute: name with value "test store view")
3. set checkbox "Use Default Value" for attribute name on store view level and save
4. after page reload name has value "test store view", checkbox is unchecked

### Expected result (*)
1. Attribute value in StoreView reset to value of website level -> "test"
2. Checkbox "Use default value" is checked
3. Database entry in table "catalog_product_entity_varchar" deleted for this store view

### Actual result (*)
1. Attribute value in StoreView is still the same
2. Checkbox "Use default value" is not checked
3. Database entry in table "catalog_product_entity_varchar" still exists for this store view

It seems to be a javascript issue regarding the toggle event ticking the checkbox.

Tracked this down to file:
vendor/magento/module-catalog/Controller/Adminhtml/Product/Initialization/Helper.php:204
The POST var $useDefaults = (array)$this->request->getPost('use_default', []); is empty.

Same function edition categories on store view level works without any problems.

**Comment by mwieschke** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mwieschke. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mwieschke, here is your [Magento instance](https://i-26694-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26694-2-4-develop.instances.magento-community.engineering/admin_dd8c](https://i-26694-2-4-develop.instances.magento-community.engineering/admin_dd8c)
Login: `6470dc28` Password: `86b9497cdb00`
Instance will be terminated in up to 3 hours.

**Comment by mwieschke** [comment]
The issue is not reproducible on the vanilla Magento instance.

**Comment by sudheers-kensium** [comment]
> The issue is not reproducible on the vanilla Magento instance.

@mwieschke Maybe this issue is fixed in latest Magento Version. So can I close this issue?

**Comment by mwieschke** [comment]
We double check this with 2.3.4 in the next hours.

**Comment by mwieschke** [comment]
The issue is not reproducible on Magento 2.3.4 - bug seems to be fixed.
