### ISSUE TITLE
Slow initial page load speed

### ISSUE THREAD

**Issue by thijsvanwinden** [magento/magento2#2669]
Hi, 

I'm at the moment busy with reviewing magento2 CE edition(for now) to be used in one of our future projects. This project involves a large amount of products. Now we tried doing a test with 40.000 products. 

The biggest problem here is, that the initial page load of a page is +2 minutes. In my test setup I extended the time limit, but this does not seem to help. Mostly it results in a timeout and sometimes I get the html page. 

The strange thing however is, that once I try again on the same page the response time is less than 
600 ms. 

Then we tried to run a profiler(xdebug) to determine which functions/components cause  this slowness. However these logs turn out to be 15 gb and cannot be opened by any program, because they all crash on the memory. 

The questions are therefore:
1. What is the cause of this behaviour? I tried to identify this myself by using the profiler and outputting stack traces. However it always timeouts on the stack traces.
2. In the documentation there is a large part on using varnish as a reverse proxy cache. However this cache can miss or partly miss, due to non static parts in the content. Also it needs to be warmed up. So I'm not so sure if this would be a solution to this problem. What else can you recommend?
3. Any tips what I else could be used to determine this?
4. Once a paged is hit once, it seems to be cached afterwards. However when I empty the cache it is not consistently slow. Some pages remain fast. What could cause this?
5. I have read in the documentation that magento calculates a lot upfront (prices, taxes, delivery etc) and loads from storage (database/cache). Could this proces cause this slowness?

In this setup I tried already a few things. 
- Enable/Disable caching
- Enable/Disable indexing
- Enable/Disable opcode caching
- Various php versions(5.6, 5.5, 7.0)
- Tests with file cache, memcached, redis (both using phpredis and non-native)
- Various new installs, new static file compilations and di compilations
- Both deployment modes

Some information about the setup
- LAMP stack based on centos 6
- Using php 5.6 fpm
- Using MariaDb 10.0.22
- Using Redis 3.0.5
- Memcached 1.4.4
- Apache 2.2

I post this here and not in the stackexchange, because I'm pretty sure this is not about the setup. It seems that there is something in the architecture that takes very long. And I hope some can tell my why or help me identify what. 

Kind Regards,

Thijs van Winden

**Comment by SantyagoSeaman** [comment]
Hello!
Can you provide results of execution

``` sql
show variables like '%innodb%';
show variables like '%cache%';
```

Did you turn on Mysql slow query log?

**Comment by okobchenko** [comment]
Please try next flow for running M2 in production mode:
- Cloning / Installation
- Activating client side performance features (optional for your case and is not root of 2m response)
  - JS bundling
  - JS minification
  - CSS minification
  - HTML minification
- Activating caches
  System (Admin) -> Cache management -> Enable on all
- Running of static content deploy command (this could be the reason of slow response)

```
php bin/magento setup:static-content:deploy
```
- Running code compiler (will save 10-15% on page response)

```
php bin/magento setup:di:compile
```
- Setting production mode in .htaccess

```
SetEnv MAGE_MODE production
```
- Re-indexing your catalog

```
php bin/magento indexer:reindex
```
- Cleaning all caches

```
php bin/magento cache:flush
php bin/magento cache:clean
```

We also suggest to de-activate xdbug module in order to ge up to 20% improvement on response page.

After flow is executed if there are no environment specific limitations (lack of memory, disks limitations) your Magento should response in 100-300ms (600-800ms on non-warmed page cache).

In terms of profiling we recommend to use Z-Ray by Zend, that now can be launched without Zend Server installation and already contains M2 specific plugin in gallery with ability to view profiling data directly in browser bar.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by thijsvanwinden** [comment]
We applied all the above advices, but the problem remained. However one thing changed during our testing. The initial load is terribly slow, but after that an html copy of the page is saved and it loads in 150 ms. 
The initial load however remains more than 20 seconds.

I know that the github issue tracker is used for technical issues, however I felt that this is both a technical issue and a configuration issue and wanted to write down my findings for people with similar problems. 

After some profilling I have narrowed it down to this query which results in 44000 rows.

``` sql
SELECT `catalog_category_entity_varchar`.`entity_id`, `catalog_category_entity_varchar`.`attribute_id`, `catalog_category_entity_varchar`.`value` FROM `catalog_category_entity_varchar` WHERE (entity_id IN (* LONG LIST OF IDS*)) AND (attribute_id IN ('43', '51')) AND (store_id = 0) UNION ALL SELECT `catalog_category_entity_text`.`entity_id`, `catalog_category_entity_text`.`attribute_id`, `catalog_category_entity_text`.`value` FROM `catalog_category_entity_text` WHERE (entity_id IN (* LONG LIST OF IDS*)) AND (attribute_id IN ('54')) AND (store_id = 0);
```
- LONG LIST OF IDS \* Corresponds to list of more than 22000 category id's 

I'm not sure what it tries to load here, but my feeling is that navigation menu which is in this case quite deep, because I purposely enabled visibility on all levels. This is the case because the webshop must be able to grow to possibly 400.000 products 

Whenever I decrease my menu depth to for example 1 level, the uncached page speed reduces to 800 ms, which is high, but acceptable for me at the moment. However increasing the menu depth to for example 3, (which means around 1500 categories) remains slow. 

Questions remaining:
What is was wondering is why it is necessary to rebuild the page menu on every page? Is it not possible to cache this?  Or are these considered tasks for the userland/module builders?

**Comment by kandy** [comment]
@thijsvanwinden, We have  improved performance of TopMenu rendering for big trees, can I ask you to check it?

**Comment by thijsvanwinden** [comment]
I will check after the weekend, do you have an commit/branch for me where the problem is fixed?

**Comment by Techytt** [comment]
Yea we are also facing slowness for the uncached pages, specifically configurable PDP pages.
We are using latest M2.3.4 with AWS server and only having single color configurable option, 
Please help us to fox this code Magento issue?

**Comment by goivvy** [comment]
Here is what I would do when faced with a slow Magento 2 site:

- Use a code profiler to see what code block is slowing down the site. Try tideways, it's an online code profiler, similar to newrelic but much better in my opinion. it has a two weeks trial period, it should be enough
- Do you use php-fpm workers? Try switching to a static distribution and have as many initial workers as you could, usually 1 per cpu core.
- From my experience, most performance issues come from poorly coded 3rd-party extensions. Do a plugin audit. Turn off all custom modules and see if it makes any difference. If it does, turn them on one by one and see which one ruins the site speed.
- Are you using a custom theme? Switch to a default luma theme and see if it makes a difference. If it does, dive deeper into theme files and see what's going on.

I wrote a whole article on how to [speed up Magento 2 sites](https://www.goivvy.com/blog/speed-up-magento-2) - check it out.
