### ISSUE TITLE
Wrong api

### ISSUE THREAD

**Issue by nagel1217** [magento/magento2#26705]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by krishprakash** [comment]
Hi @nagel1217. Please update all the details Precondition,Steps to reproduce,expected and actual result for the issue 
Thanks.

**Comment by krishprakash** [comment]
Hi @nagel1217.
Feel Free to reopen after update all the details.
Thanks.
