### ISSUE TITLE
Wrong customer group assigned to an order. 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#26719]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create 2 new customer groups
2. Create new customer, assign it to Customer Group 1
3. Create an order
4. Edit created customer and change it's customer group to Customer Group 2
5. Create another order using "Reorder" feature in admin panel. 

### Expected result (*)

1. Newly created order should have a new customer group assigned

### Actual result (*)

1. Newly created order has old customer group assigned

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26719-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26719-2-4-develop.instances.magento-community.engineering/admin_a4bc](https://i-26719-2-4-develop.instances.magento-community.engineering/admin_a4bc)
Login: `bf2e4cf2` Password: `96e47e752a8b`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
The issue is verified as per your scenario and steps.
If the admin wants to change the customer group on the reordering section, Admin can update it.
"Group 2" should be there on the Order block if the admin has already changed the customer group.

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31169` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by prashantbarot** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prashantbarot. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prashantbarot, here is your [Magento instance](https://i-26719-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26719-2-4-develop.instances.magento-community.engineering/admin_ed98](https://i-26719-2-4-develop.instances.magento-community.engineering/admin_ed98)
Login: `8239b5d8` Password: `db1a7d4c8b6f`
Instance will be terminated in up to 3 hours.

**Comment by swapnilT2jcommerce** [comment]
@magento I am working on this
--

**Comment by j-robin-hunter** [comment]
Hi,

We have been looking into a problem where new group assignments have not been applied to an order, ie old group is still being used, and this looks like it is this same issue.

The difference is that we are not using re-order but just creating an new order after the group has been changed.

Looking at the customer_entity in the database this has clearly been changed to the new group but on the order \Magento\SalesModel\Order or the \Magento\Quote\Model\Quote is we use the getCustomerGroupId() function we get the old groupId not the new one.

**Comment by Dharmeshvaja91** [comment]
@magento I am working on this issue

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
