### ISSUE TITLE
When upgrading to 2.3.4 with encrypted drive, seeing "File name too long" error

### ISSUE THREAD

**Issue by iamsophiesk** [magento/magento2#26728]
### Preconditions
Issue when upgrading from Magento 2.3.3 -> 2.3.4.
Using Ubuntu 16.04 (possibly 18.04?) with encrypted home directory, and Magento installed in home directory (eg in `~/projects/magento`)

### Steps to reproduce
Perform upgrade from Magento 2.3.3 -> 2.3.4 and run commands as outlined on https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html 

### Expected result
The upgrade to run successfully.

### Actual result
Had the following error: 
```
error: cannot create /home/$USER/projects/magento/vendor/composer/9318cb01/Test/Mftf/Test/StorefrontBackordersEnabledOnConfigurationPageAndAppliedFromHomepageToWithConfigurableProductWithDropDownAttributeAndVariablesAssignedToNonDefaultSourceTest.xml
File name too long
```

---

I upgraded Magento 2.3.3 to 2.3.4 locally with no problems, running Ubuntu 18.04. When my colleague tried to update, running 16.04 with an encrypted home directory (where the project was installed), the update failed with the error above.

From http://www.linfo.org/file_name.html :
> ... modern Unix-like systems support long file names, usually up to 255 bytes in length. 

This file name is 160 characters, but the maximum number of characters allowed for a filename in an encrypted drive is 143: https://askubuntu.com/a/728525 

The workaround we've found is to install project in a different directory, but this seems like an oversight.

**Comment by Tawreh** [comment]
It looks like this has been reported on StackOverflow but with no resolution: https://magento.stackexchange.com/questions/302528/magento-2-3-4-composer-update-file-name-too-long 

Maybe it's worth noting that we are using Docker/Docksal for our development, but this seems to be an issue with the host computer rather than Docksal, as my colleague was able to get it working in a directory outside of his home

**Comment by engcom-Bravo** [comment]
Hello @Tawreh 

Thank you for your report. 

This is a valid issue, but not for this repository.
The mentioned test file is a part of the Magento Inventory. Please open an issue in this repository https://github.com/magento/inventory/issues

We have to close this issue.

Thank you for collaboration
