### ISSUE TITLE
Qty decimals allowed on configurable product even when setting set to 'no'

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#26726]
### Preconditions (*)

1. Magento CE 2.2.10 (actual for `2.4-develop`)

### Steps to reproduce (*)

1. Add simple product having 'Qty Uses Decimals' = 'No' (default)
2. Add configurable product having 'Qty Uses Decimals' = 'No' (default)
3. Link simple to configurable
4. Go to PDP and add '1.x' (ie 1.5) to cart

### Expected result (*)

1. Behaviour like simple products - floored qty is added to cart

### Actual result (*)

1. Decimal qty is added to cart

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26726-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26726-2-4-develop.instances.magento-community.engineering/admin_d5d4](https://i-26726-2-4-develop.instances.magento-community.engineering/admin_d5d4)
Login: `54f0b3f4` Password: `1745dcecef57`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@rikwillems - I didn't properly get to exact issue. Can you please update me on what exactly you want?

**Comment by rikwillems** [comment]
@ajijshekh123 - If the setting 'Qty Uses Decimals' on a configurable product is set to 'no' you should not be able to add a qty with decimals to cart. You can do this now by adding 1.5 of a certain configurable to the cart.

**Comment by ajijshekh123** [comment]
Yes, @rikwillems. The issue reproduced on Magento 2.4 Instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31176` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rikwillems. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-31176` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
