### ISSUE TITLE
Configurable product disabled after being added to the cart make cart unusable

### ISSUE THREAD

**Issue by alepane21** [magento/magento2#26739]
### Preconditions (*)

1. Magento 2.2, 2.3 and 2.4

### Steps to reproduce (*)

1. add a configurable product and another simple product to cart;
2. disable the configurable product but not simple product.

### Expected result (*)

1. the product should be deleted by the cart.

### Actual result (*)

1. the cart will be set as not checkout-able, but no product will be shown.

**Comment by alepane21** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @alepane21. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alepane21, here is your [Magento instance](https://i-26739-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26739-2-4-develop.instances.magento-community.engineering/admin_34a9](https://i-26739-2-4-develop.instances.magento-community.engineering/admin_34a9)
Login: `e332d0df` Password: `30cbd5372058`
Instance will be terminated in up to 3 hours.

**Comment by alepane21** [comment]
@magento give me 2.3 instance

**Comment by alepane21** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @alepane21. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @alepane21, here is your [Magento instance](https://i-26739-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26739-2-3-4.instances.magento-community.engineering/admin_9fac](https://i-26739-2-3-4.instances.magento-community.engineering/admin_9fac)
Login: `df630ed6` Password: `df369bc1d031`
Instance will be terminated in up to 3 hours.

**Comment by alepane21** [comment]
Lol, fixed in https://github.com/magento/magento2/commit/41565f0f7b702136668189eb5a2ecfa1d6b82d69
