### ISSUE TITLE
Question : import product gallery (fotorama) to my custom module

### ISSUE THREAD

**Issue by quienti** [magento/magento2#2673]
Hi!

I need to add the same gallery on my custom module
But, I don't know how import all js/css and html and I don't find any idea to resolve my problem :/

Anybody to help me please ?

Thank you

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
