### ISSUE TITLE
Backorders still active when switching product to manage_stock no

### ISSUE THREAD

**Issue by mzenner1** [magento/magento2#26735]
Magento 2.3.4

When converting a product back to manage stock = no, the options present when stock was on still take effect.  Specifically, backorders.

1. Set a product to manage stock
2. Set stock amount to zero
3. Uncheck the "use config settings" box for backorders and set a value
4. Save the product
5. On reload turn stock off for the product

### Expected result (*)
1. Stock would no longer be managed on product

### Actual result (*)
1. Add item to shopping cart
2. Says the item is backordered even though manage stock is off

Fixing this is just a simple matter of turning stock back on for the product, re-checking use config for backorders, then turning stock off and saving the product.  However, when stock is set to not be used, the backorder logic should not be firing at all.

**Comment by shikhamis11** [comment]
hi @mzenner1 
I checked this issue is not reproducible at magento 2.4-develop instance 
It seems this issue is already fixed .. 
let me know if you are still able to reproduce this issue at 2.3-develop instance also please share screenshots
