### ISSUE TITLE
Product flat table - Incorrect data

### ISSUE THREAD

**Issue by tranhoangthien1990** [magento/magento2#26749]
We're current facing an issue that the product data has been inserted to an incorrect flat table. 

### Preconditions (*)
1. Magento version 2.3.3 with Sample Data
2. Enable Catalog Product Flat.
3. Index mode for Catalog Product Flat: Update on save

### Steps to reproduce (*)
1. Create 2 new websites, for each website, create one store view (let say the store view id for website 1 is 2, store view id for website 2 is 3).
2. Come to any product detail, try to assign this product to website 1, then click Save.

### Expected result (*)
1. Product information just insert to flat table of the website that product is assigned to (in this case, this table is catalog_product_flat_2)

### Actual result (*)
1. Product information has been inserted for all product flat table (in this case, include catalog_product_flat_3)

After i run `php bin/magento indexer:reindex catalog_product_flat` all invalid data has been removed (in this case, this product information has been removed in catalog_product_flat_3 ).
Please help to check it again.
Thanks.

**Comment by engcom-Bravo** [comment]
Hello @tranhoangthien1990 

We confirm that this is reproducible on Magento 2.4-develop
And we also confirm that after running ```php bin/magento indexer:reindex catalog_product_flat```, the data from the table _catalog_product_flat_3_ is removed 

Thank you for your report

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31436` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
The issue has been fixed: #27365
