### ISSUE TITLE
cms-page-specific layouts are not applied if FullActionName differs from page_view

### ISSUE THREAD

**Issue by Tripuls-Magento** [magento/magento2#26758]
### Preconditions (*)
1.  magento 2.3.4 
2. create cms-specificlayout file in your module/theme for home 

### Steps to reproduce (*)
1.  Add a cms_page_view_selectable_home_somechanges.xml as described in https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html 
2. Edit the home page in the backend to use the specifc Layout (CMS->Pages->home>edit->design->select "somechanges" ..) 
3. Save. 
4. Clear layout-cache
5. Refresh home page

### Expected result (*) 
1. Specific layout changes from cms_page_view_selectable_home_somechanges.xml should be applied

### Actual result (*) 
1.  Changes have no effect

## Workaraund: 
Place a second file **cms_index_index**_selectable_home_somechanges.xml in your theme/module and the changes are applied. 

## Backgraund: 
The DefaultLayoutHandle differs on the homepage from regular CMS_Page_View, since the full action name is cms_index_index 
\Magento\Framework\View\Result\Page::addPageLayoutHandles
(\Magento\Framework\View\Result\Layout::getDefaultLayoutHandle)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31374` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MageSuper** [comment]
@Tripuls-Magento  I just had this issue, and thank god you outlined the workaround :D 

Thank you.

**Comment by rdudhara** [comment]
I am working on these issues.

**Comment by magento-engcom-team** [comment]
Hi @Tripuls-Magento. Thank you for your report. 
The issue has been fixed in magento/magento2#27131 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [53c78d534063efa1d8275e27f9cd019dfd9000dc](https://github.com/magento/magento2/commit/53c78d534063efa1d8275e27f9cd019dfd9000dc)

The fix will be available with the upcoming 2.4.0 release.

**Comment by IbrahimS2** [comment]
@magento-engcom-team Why this still a problem in 2.3.6?
