### ISSUE TITLE
Product images in category not updating, showing placeholder/wrong image

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26757]
Sometimes the store gets stuck on the images and deleting an image does not remove the product category thumbnail version, so you can have two completely different product images in category and product page. And uploading a new product image does not generate a new one leaving the product category image version with a placeholder.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

Don't know. Happens randomly like most other Magento 2 functionality.

### Expected result (*)

Category product image should update.

### Actual result (*)

Category product image does not update, showing old version.

**Comment by krishprakash** [comment]
Hi @Zyles.
Issue is duplicate to #25099
Issue is fixed in next 2.3.4 release
You can review the feedback from above given issue link.
Thanks.

**Comment by Zyles** [comment]
It is not a duplicate.

This is for PRODUCT IMAGES in a category.

Not the category image itself.

**Comment by Zyles** [comment]
Re-open please.

**Comment by heyepic** [comment]
I was banging my head against a wall while setting up a new category and images not working.  On the frontend, category images were duplicating the file path. The backend meanwhile was fine. 

Reverting to the 2.3.2 version of /vendor/magento/module-catalog/Model/Category/Attribute/Backend/Image.php fixed this. 

Please include this in the next release!

**Comment by rommelfreddy** [comment]
i found a similar issue. I am not sure, if it is the same issue.
After you add an image (or multiple) to a product, and the product page got NOT requested, the product image got not replaced on the category page.
After you have requested the product page the image will appear on the category page (if you activated full_page cache: clear full_page cache)

**Comment by rommelfreddy** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rommelfreddy. Thank you for your request. I'm working on Magento 2.3-develop instance for you
