### ISSUE TITLE
Admin order creation fails when "Include Tax In Order Total" set to yes

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2675]
## Steps to reproduce issue:
1. Install Magento CE 2.0.0 with sample data.
2. Ensure that developer mode is turned on.
3. Go to **Stores > Configuration > SALES > Tax > Shopping Cart Display Settings** and change the "Include Tax In Order Total" value to "Yes".
4. Go to **Sales > Orders > Create New Order**
5. You will see this error: `Notice: Undefined index: tax in vendor/magento/module-sales/Block/Adminhtml/Order/Create/Totals/Grandtotal.php on line 77` Full backtrace available [here](https://gist.github.com/erikhansen/42be285307c2ce0f3aea)

This problem occurs because the \Magento\Tax\Model\Sales\Total\Quote\Tax::collect collector only returns a value if there are items in a quote. And since the quote won't contain any items, the "tax" collector isn't present in the totals array. I'll be submitting a PR to fix this shortly.

**Comment by tang-yu** [comment]
This issue has been fixed in internal ticket MAGETWO-46808. Thanks for submitting the defect.
