### ISSUE TITLE
Sorting by Websites column breaks products grid pagination

### ISSUE THREAD

**Issue by antoinekociuba** [magento/magento2#26759]
When sorting by _Websites_ column from admin area products grid, the pagination is broken (1 record found only, only one page, even if more products available).

### Preconditions (*)
- Magento Version : CE 2.3.4 or CE 2.3.3 or CE 2.3.2
- PHP version : PHP 7.3.14-6+ubuntu16.04.1+deb.sury.org+1 or 7.2.
- MySQL version : mysql Ver 14.14 Distrib 5.7.29

### Steps to reproduce (*)
1. Go on admin area products grid
2. Sort by _Websites_ column
3. Check number of records/pagination

### Expected result (*)
Sort by _Websites_ column should be working fine and not break grid pagination.

### Actual result (*)
Sort by _Websites_ column breaks products grid pagination.

<img width="1337" alt="Capture d’écran 2020-02-07 à 21 27 15" src="https://user-images.githubusercontent.com/1146677/74064030-08656f00-49f2-11ea-8279-c494d794bc3e.png">

**Comment by antoinekociuba** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @antoinekociuba. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @antoinekociuba, here is your [Magento instance](https://i-26759-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26759-2-4-develop.instances.magento-community.engineering/admin_ba50](https://i-26759-2-4-develop.instances.magento-community.engineering/admin_ba50)
Login: `56f7d0df` Password: `331f1704921a`
Instance will be terminated in up to 3 hours.

**Comment by antoinekociuba** [comment]
Actually, it is fixed on 2.4-develop branch. I managed to find corresponding fix, if it can help someone: https://github.com/magento/magento2/commit/3056027889eb89fb63341af79217d9ff34af17ec
