### ISSUE TITLE
GraphQL. Query: categoryList. Returns wrong category image URL

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#26766]
### Preconditions (*)

1. Create a new category on the back-end side
2. Upload an image for this category. Use the next image name - `Screen_Shot_2019-09-08_at_1.11.46_PM.png`

### Steps to reproduce (*)

1. Open any GraphQl tool
2. Run the next query to retrieve a category image:

```
{
    categoryList(
      filters : {
        ids: {eq: "ENTITY_ID_OF_CATEGORY"}
      }
    )
    {
        image
    }
}

```
### Expected result (*)

1. Category image URL is correct: 

<img width="1021" alt="expected" src="https://user-images.githubusercontent.com/13585327/74071471-9e0df800-4a0c-11ea-827c-140fbd9960af.png">

### Actual result (*)

1. Category image URL is incorrect: 

<img width="1187" alt="actual" src="https://user-images.githubusercontent.com/13585327/74071478-a6663300-4a0c-11ea-8c95-c71d5eebc105.png">

Thank you!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31300` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lenaorobei** [comment]
Fixed by internal team.
