### ISSUE TITLE
When Magento 2 can compatible with Mysql 5.6.0?

### ISSUE THREAD

**Issue by ramseyjiang** [magento/magento2#2677]
I try to install Magento 2, but on the second step, it show me "Sorry, but we support MySQL version 5.6.0 or later."

Who knows when Magento 2 can support that?

**Comment by mazhalai** [comment]
@ramseyjiang What is your version of Mysql? Magento 2 requires MySql 5.6 as a minimum requirement

**Comment by ramseyjiang** [comment]
Sorry, MySQL version is 5.5, I will upgrade my MySQL, Thank you for your reply.

**Comment by ohabash** [comment]
how do i upgrade my mysql? I am using phpmyadmin with mamp locally

**Comment by ghost** [comment]
[Try this](https://dev.mysql.com/doc/refman/5.6/en/upgrading-from-previous-series.html). Be sure you're aware of upgrade issues (with MySQL).

Do you know where you got your 5.5 package from? Most likely the same repo has 5.6.
