### ISSUE TITLE
Magento 2.3.4 - infinite loop on checkout buttons

### ISSUE THREAD

**Issue by jackrevate** [magento/magento2#26774]
### Preconditions (*)

1. 2.3.4
2. checkout

### Steps to reproduce (*)

1. click Continue to Paypal
2. click Place Order

### Expected result (*)

1. Checkout successfully.

### Actual result (*)

1. Error Message: "INTERNAL ERROR. DETAILS ARE AVAILABLE IN MAGENTO LOG FILE. REPORT ID: WEBAPI-5E3EFDD394AD"
2. [2020-02-08 13:11:36] main.CRITICAL: Report ID: webapi-5e3eb38834d5a; Message: Infinite loop detected, review the trace for the looping path {"exception":"[object] (Exception(code: 0): Report ID: webapi-5e3eb38834d5a; Message: Infinite loop detected, review the trace for the looping path at /vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): Infinite loop detected, review the trace for the looping path at /vendor/magento/module-checkout/Model/Session.php:241)"} []

**Comment by jackrevate** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jackrevate. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jackrevate, here is your [Magento instance](https://i-26774-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26774-2-4-develop.instances.magento-community.engineering/admin_aa12](https://i-26774-2-4-develop.instances.magento-community.engineering/admin_aa12)
Login: `9a17d919` Password: `112d090a93fa`
Instance will be terminated in up to 3 hours.

**Comment by VVNPradeep** [comment]
Hi There,

You can reproduce the issue with COD Payment method as well. Its been effected on all the payment method.

**Comment by shikhamis11** [comment]
Hi @jackrevate 
I am not able to reproduce this issue on magento 2.4 instance. also @VVNPradeep Please share the steps to reproduce this issue with Cash On Delivery

**Comment by jackrevate** [comment]
False flag.

Stripe was the issue, a third party extension.

Hope this helps others, sorry for not testing properly.

**Comment by kapil-infobeans** [comment]
Hey, Folks, 

I am getting the same issue, We do not have stripe payment gateway.

**Comment by paul-sysint** [comment]
Hey,

I have just updated to Magento 2.3.5-p1 on a development domain using default Braintree Payment method and I am getting "Infinite Loop" detected as well

**Comment by kapil-infobeans** [comment]
Folks, I got to know about the root cause of this issue from one of my colleague, It is due to some of the plugged in method in code calling an event and on event call it again goes to the plugged in method. So it become a infinite loop.

I would suggest check all plugins in code & use xdebugger to trace where the error is coming from, You will definitely find it and cab apply a fix.

**Comment by paul-sysint** [comment]
The Problem I found on Magento 2.3.5 using default Braintree Payment system seemed to be in the 
 /vendor/magento/module-checkout/Model/Session.php file on line 240 `if ($this->isLoading) { `

The `$isLoading` variable is set to true on line 243 but it never gets to this as the if loop is above the setting of the variable.

I solved by uploading the Session.php file from version 2.3.3 and testing the checkout this appears to work so far.

**Comment by kapil-infobeans** [comment]
@paul-sysint , cool. Can you put a log inside method: getQuote method and check how much time control goes there?

**Comment by paul-sysint** [comment]
kapil-infobeans, after adding a call to the logger function in the v2.3.3 Session.php file. It appears to call the `getQuote` method about 125 times whilst placing 1 order through Braintree on the site. but  the  order does now complete successfully on the Braintree sandbox account. 

With the v2.3.5 Session.php file the ajax loader just keeps spinning it never finishes,  the "Infinite loop detected, review the trace for the looping path" message is shown in the background behind ajax loader.

**Comment by kapil-infobeans** [comment]
@paul-sysint I suspected the same. So, as you can see v2.3.5 they have fixed this multiple calling issue, The actual is the plugin or event causing this looping, But that can differ based on custom code implementation or may be some third party module code has that bug.

Right now using v2.3.3 Session.php file may work for you, but as your database will increase, it will take more resources and break in future. So it would be good to debug it in parallel to the temporary solution.

**Comment by paul-sysint** [comment]
@kapil-infobeans, cheers I thought it was too easy. I'll keep looking until I find the issue before publishing update to live site. cheers for the help.

**Comment by roshanyadav89** [comment]
Any solution for the same I am facing the same issue after m2.3.3 upgrade 2.3.5 EE

**Comment by paul-sysint** [comment]
The issue I originally had was caused by a 3rd party extension conflicting with Braintree. I ended up disabling all 3rd party extensions and re-enabling 1 at a time recompiling and redeploying each time until I found the offending module.  

I would start by checking all 3rd party modules are compatible with 2.3.5.

**Comment by roshanyadav89** [comment]
Magento 2.3.5 [EE] same issue as mentioned trying to find the solution for the same, I disabled all 3rd party extensions Only COD enabled then also facing the same issue.
