### ISSUE TITLE
Magento 2.3.4 Checkout Infinite loop detected

### ISSUE THREAD

**Issue by nazimwibsoft** [magento/magento2#26786]
### Preconditions (*)

1. Add product to cart and go to checkout page
2. Select any payment method and try to checkout

### Steps to reproduce (*)

1. Add product to cart and go to checkout page
2. Select any payment method and try to checkout
3. Web Browser console will show 500 Internal Server Error

### Expected result (*)

1. Order placed successful 

### Actual result (*)

1. Error received: main.CRITICAL: Report ID: webapi-5e3d62454a015; Message: Infinite loop detected, review the trace for the looping path {"exception":"[object] (Exception(code: 0): Report ID: webapi-5e3d62454a015; Message: Infinite loop detected, review the trace for the looping path at ...\\vendor\\magento\\framework\\Webapi\\ErrorProcessor.php:208, LogicException(code: 0): Infinite loop detected, review the trace for the looping path at ..\\vendor\\magento\\module-checkout\\Model\\Session.php:241)"} []

### Bug in Code File of 2.3.4
1. /app/code/Magento/Checkout/Model/Session.php line 240 code is a bug
2. On line 240 we have the code: if ($this->isLoading) { ... which throw this exception. The private member $isLoading is set to false by default and is only set to true on line number 243 in the Session.php the code will never reach this line as the Quote is not already created and need to be created at line number 244 but we are throwing an error one line 241 which breaks the script. No matter what we select in payment method the code always breaks.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26786-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26786-2-4-develop.instances.magento-community.engineering/admin_bb50](https://i-26786-2-4-develop.instances.magento-community.engineering/admin_bb50)
Login: `57631fc1` Password: `234686a4fc9c`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @nazimwibsoft.
Not able to reproduce the issue as provided steps by you. Please review below link for reference:
https://nimb.ws/JYGxjv
Please provide more detail to reproduce this issue
Thanks.

**Comment by krishprakash** [comment]
Hi @nazimwibsoft. It should be 3rd party module issue.
Please review the issue #26774 
Please provide the video if this is default issue and please confirm on provided automated instance.

**Comment by nazimwibsoft** [comment]
@krishprakash Thanks for the update and prompt response on this, we have Paypal, and Stripe Payment methods installed on the site which were working fine with 2.3.3 , and after upgrade to 2.3.4 it started this issue of infinite loop message

**Comment by nazimwibsoft** [comment]
The issue was with the Stripe Payment Integration extension, after updating that to latest 1.5.2 resolved the issue for me. Thanks.

We can install the latest version from here: https://stripe.com/docs/plugins/magento/install

**Comment by nabilrizvi** [comment]
**_Infinite loop detected, review the trace for the looping path while checking out for paypal or strip both.._**
do we have any solution to fix this in Magento 2.3.4??

**Comment by rahulthakral38** [comment]
Infinite loop detected, review the trace for the looping path in Payment gateways on checkout.

do we have any solution to fix this in Magento 2.3.4??
Any Solution will be helpful.

**Comment by rahulthakral38** [comment]
**Infinite loop detected, review the trace for the looping path in Payment gateways on checkout.
![magento-payment-checkout](https://user-images.githubusercontent.com/17290393/84237458-041f9e80-ab17-11ea-98e1-36e21c2a43a6.png)
**

**Any soltion or any information for this issue patch released..??**

**Comment by walterbak** [comment]
@rahulthakral38 check in your custom code if there is at least one observer on a quote load event (in my case 'payment_method_is_active') that try to load quote from \Magento\Checkout\Model\Session (i.e. in __construct function). In this case the __constructor of your custom observer try to load quote inside ->getQuote session function, and generate this infinite loop error. So try to load quote from your $observer object (in my case $observer->getQuote()) to solve the problem.
It works for me.

**Comment by ihorvansach** [comment]
In my case this error was related to the custom extension that was installed on the Magento instance. 
The easiest way to find the the source of the issue is to print backtrace in file 
vendor/magento/module-checkout/Model/Session.php right before the line
throw new \LogicException("Infinite loop detected, review the trace for the looping path");

to detect what plugin/observer/rewrite creates a loop.

**Comment by roshanyadav89** [comment]
Any solution for the same?

**Comment by roshanyadav89** [comment]
Any solution for the same I am facing the same issue after m2.3.3 upgrade 2.3.5 EE

**Comment by Amit-Hariyani** [comment]
change in file vendor/magento/module-checkout/Model/Session.php

This error comes in 2.3.4 or later versions because of

if($quote->getTotalsCollectedFlag() === false) { $quote->collectTotals(); }

Here, $quote->collectTotals(); generates error because of recursive call

so, by commenting $quote->collectTotals(); or whole if condition it will not go in infinite and code will work properly.

Actually there is no need of $quote->collectTotals(); in this file.

**Comment by KnK123** [comment]
Thanks Amit-Hariyaniz
We have faced the same issue on one of the project yesterday as per your suggestion commented respected line in session.php and issue has been fixed in 2.3 EE.

Thanks

**Comment by moElwan** [comment]
Hello @Amit-Hariyani Please [refer to the original commit](https://github.com/magento/magento2/commit/29f0417a28ad71d4dd42485b88da125ccd960a2e#diff-7121f9347f904d6e8d34fccea7ec743790dc3ec97faf6b34b0960f9d68a4abd6) and you can see why the code is added and how commenting it would affect some cases when products are unavailable 
Unused code should be removed, If you're still sure it won't affect anything please open a PR removing the condition
Such suggestion to edit core file with the assumption it won't affect anything is really dangerous!
Regards

**Comment by danielpugh** [comment]
just come across this issue on 2.4.3-p1.
the problem occurred because using the mageworx delivery date module and the adyen payment method together.
i do not want to edit core files, but this does seem to fix the issue.
confused why it has been fixed in EE, (i.e. implying identified as a bug), but not the community edition??

**Comment by atIOCrON** [comment]
We came across this error on community v2.4.3-p1. Why is this issue "closed" if it still exists? Can anyone point me to a patch? We don't want to comment out lines in core files as there could be serious unintended consequences.

**Comment by alimurtaza026** [comment]
Facing it on 2.4.2 why still exists?

**Comment by PietroFantini** [comment]
yes this garbage still exist

**Comment by kwilliams-concentrix** [comment]
Still exists in 2.4.5-p2. Can we get an update and reopen?

**Comment by KoolAndTheHamiltonGang** [comment]
Hi all,

I confirm it still exist on Magento 2.4.6 EE

**Comment by creativebay** [comment]
Hi All,

the issue still exists in 2.4.6-p2

**Comment by ravindra0054** [comment]
hi this issue on magneto2.4.7-p1
![Screenshot 2024-07-29 151057](https://github.com/user-attachments/assets/51883d7a-9102-42b0-847c-c95c57b02c93)

**Comment by r1tt3r** [comment]
this issue still exists on 2.4.7-p2

**Comment by kennylawrence** [comment]
This just started happening to us yesterday on 2.4.6-p8 and nothing changed in months since the last update, as far as I know unless it was something in the hosting environment. I had two customers say they can't place an order, but I'm able to do it without any issues at all on my side. I ended up making an order through the backend for one of them.
Why did it just start when I've never seen this exception before?

**Comment by adi3009** [comment]
I noticed the error when a customer had a product in the cart but didn't checkout and a later time the product was disabled.
