### ISSUE TITLE
Order status labels serve no purpose

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26785]
The store view labels for order statuses serve no purpose.

According to https://github.com/magento/magento2/issues/26539 you need to translate order statuses using a language file.

So might as well remove the GUI fields if they are useless.

### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Create a second store view
1. Create new order status
1. Translate order statuses using the GUI
1. Nothing

### Expected result (*)

Translations to work.

### Actual result (*)

Useless:

![73351839-26afca00-4290-11ea-802d-e75637140a84 1](https://user-images.githubusercontent.com/1741593/74112525-aba6b780-4b9d-11ea-9b7f-eb457f2a1441.png)

**Comment by aadmathijssen** [comment]
The Store View Specific Labels do serve a purpose, in fact they are in used in the following places:
* Frontend account pages: search for `order->getStatusLabel()` to find all occurrences.
* Sales update emails: search for `order->getFrontendStatusLabel()` to find all occurrences.

Following the code paths, they both end up calling the [`\Magento\Sales\Model\Order\Status::getStoreLabel`](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Sales/Model/Order/Status.php#L144-L159) method.

This method takes first checks whether there is a store view specific label set for the order status, and returns that label. If it is not set, the default label is translated using the `__` function.

Note that all calls to the `getStoreLabel` do not specify a `$store` argument, effectively setting it to its default value of `null`. Also the `__` function determines the store view based on the current context. In the frontend account pages, these two hidden dependencies seems to work out fine (at least in my experience), but this goes wrong when sending sales update emails from the admin for orders placed non-default store views. For that, I created GitHub issue #29263.
