### ISSUE TITLE
`sales_order_state_change_before` Event should give access to order object

### ISSUE THREAD

**Issue by simonrl** [magento/magento2#26789]
### Summary
When placing an observer on `sales_order_state_change_before`, it's not possible to get any data from the actual order object.

### Examples
see `\Magento\Sales\Model\Service\OrderService->setState()`:

Current code is:
`$this->eventManager->dispatch(
            'sales_order_state_change_before',
            ['order' => $this, 'transport' => $transport]
        );`

Because `$this` is passed to the observer, and not `$order`, there's no way to get order data in the observer.

### Proposed solution
Change event dispatch either to `'order' => $order`, or add `'order_object'` to have it backwards compatible.

`$this->eventManager->dispatch(
            'sales_order_state_change_before',
            ['order' => $this, 'transport' => $transport, 'order_object' => $order]
        );`

**Comment by manavluhar** [comment]
I am able to reproduce the issue @engcom-Hotel 
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @manavluhar,

We are reopening this issue for further analysis.

Thanks
