### ISSUE TITLE
Archive order not working with Async grid order

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#26794]
Hello,

I enable "Archiving" of orders, invoices, shipments and credit memos. It seems to work because items from "sales_order_grid" are moved to "magento_sales_order_grid_archive".

But I have also "dev/grid/async_indexing" enabled (also on production and I don't know if it's really required) which leads to a problem because "async_indexing" rebuild sales_order_grid with orders already archived.

### Preconditions (*)

1. version 2.3.0

### Steps to reproduce (*)

1. Enable "dev/grid/async_indexing"
2. Enable "Archiving" sales
3. Run "magento_salesarchive_archive_orders"
4. Run cron "sales_grid_order_async_insert"

### Expected result (*)

1. Orders will be archived in "magento_sales_order_grid_archive"
2. Archived orders should be removed from "sales_order_grid"

### Actual result (*)

1. Orders will be archived in "magento_sales_order_grid_archive"
2. Archived orders are still in"sales_order_grid" after cron "sales_grid_order_async_insert"

I have a look and I discover that in "src/vendor/magento/module-sales/Model/ResourceModel/Provider/UpdatedIdListProvider.php:39" file :

getIds function doesn't handle archived orders :

`SELECT `sales_order`.`entity_id` FROM `sales_order` LEFT JOIN `sales_order_grid` ON sales_order.entity_id = sales_order_grid.entity_id WHERE (sales_order_grid.entity_id IS NULL);`

**Comment by engcom-Bravo** [comment]
Hello @vahir2016 

Thank you for your report.

Can you please help us to reproduce this issue by answering the following question?

- Are you using Magento Enterprise Edition?
- Does your Magento instance has any extensions installed? 
- Can you please provide full commands you are using in steps 3 and 4?

Thank you for collaboration

**Comment by vahir2016** [comment]
Hello,

> "Are you using Magento Enterprise Edition?"

Yes

> "Does your Magento instance has any extensions installed?"

Yes, and I also hacked magento native archive order script to add a limit (I have a lot of orders which leads to issues). But orders are not in "sales_order_grid" after cron "magento_salesarchive_archive_orders"

But I didn't hack magento cron "sales_grid_order_async_insert". I think this cron should not get all orders which have been *already archived*.

This cron is getting his orders with this query :
"SELECT sales_order.entity_id FROM sales_order LEFT JOIN sales_order_grid ON sales_order.entity_id = sales_order_grid.entity_id WHERE (sales_order_grid.entity_id IS NULL);"


> "Can you please provide full commands you are using in steps 3 and 4?"


Sure. I am using n98-magerun2.phar to run cron separately :

sudo -u www-data ./n98-magerun2.phar sys:cron:run magento_salesarchive_archive_orders

sudo -u www-data ./n98-magerun2.phar sys:cron:run sales_grid_order_async_insert

**Comment by engcom-Echo** [comment]
Hi, @vahir2016. Thank you for your report.

Unfortunately, I do not reproduce it.

Cron "sales_grid_order_async_insert" work with "Only orders created/updated since the last method call will be added."

Invoices/Shipment/Creditmemo tied to orders also remain?

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
