### ISSUE TITLE
error if i want to upgrade

### ISSUE THREAD

**Issue by FANSELY** [magento/magento2#26806]
# php bin/magento setup:upgrade
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to alloc
ate 32768 bytes) in C:\xampp\htdocs\MagentoEbenezer\vendor\donatj\phpuseragentpa
rser\src\UserAgentParser.php on line 128

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 3
2768 bytes) in C:\xampp\htdocs\MagentoEbenezer\vendor\donatj\phpuseragentparser\
src\UserAgentParser.php on line 128

**I use magento 2.3.3**

**please everyone how do you solve this?**

**Comment by sudheers-kensium** [comment]
@FANSELY You need to increate the memory_limit in php.ini  OR run below command 

php -dmemory_limit=-1 bin/magento setup:upgrade

This is not magento issue,  so I am closing this issue
