### ISSUE TITLE
Upgrade to 2.3.4 problem:  yotpo conflict in composer after version 2.3

### ISSUE THREAD

**Issue by venture-travels** [magento/magento2#26808]
@magento give me 2.4-develop instance - upcoming 2.4.x release

Upgrading to version 2.3.4 is giving a conflicht with yotpo.
Since yotpo is standard part of M2 somewhere after version 2.3, actually it has become a module instead of an extension. 
When yotpo was installed as an extension before, it is in the composer file and in the extension-list in the 'system - web setup wizzard' of backend. From there, there is a notice yotpo needs to be updated first before running the upgrade to 2.3.4. This cannot be done because yotpo is already installed as a M2 module.
When checking dependencies when upgrading to 2.3.4 or latest yotpo version there is a confilct.

Solution: you need to remove arond the lines 17 in 'composer.json' in your M2 root before you can upgrade to version 2.3.4.

It would be very helpful if the upgrade automatically removes the lines in the composer.json file. Yotpo should also no longer be in the extension-list after version 2.3. I do not know how to resolve these issues though.

**Comment by sdzhepa** [comment]
Unfortunately, we are not able to reproduce this issue.
Extension yotpo was updated multiple times on the marketplace (current version is 3.1.2) and probably it was already fixed.
Also through this public report, we can deliver/collaborate a PR with fix only to 2.4.x  Magento.
