### ISSUE TITLE
Magento 2 API Categories return null values

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#26807]
### Expected result (*)

`{
  "id": 2,
  "parent_id": 1,
  "name": Name of category,
  "is_active": null,
  "position": 1,
  "level": 1,
  "product_count": null,
  "children_data": [
    {
      "id": 3,
      "parent_id": 2,
      "name": Name of category,
      "is_active": null,
      "position": 1,
      "level": 2,
      "product_count": null,
      "children_data": []
    },`

### Actual result (*)
`{
  "id": 2,
  "parent_id": 1,
  "name": null,
  "is_active": null,
  "position": 1,
  "level": 1,
  "product_count": null,
  "children_data": [
    {
      "id": 3,
      "parent_id": 2,
      "name": null,
      "is_active": null,
      "position": 1,
      "level": 2,
      "product_count": null,
      "children_data": []
    },`

**Comment by oefterdal** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oefterdal, here is your [Magento instance](https://i-26807-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26807-2-4-develop.instances.magento-community.engineering/admin_690f](https://i-26807-2-4-develop.instances.magento-community.engineering/admin_690f)
Login: `88ef7d8e` Password: `a25c4d0487a7`
Instance will be terminated in up to 3 hours.
