### ISSUE TITLE
Authorize.net module not visible on front end

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#26802]
It does not appear that the frontend of 2.3.4 recognizes Authorize.net as a Payment Method.

### Preconditions (*)
1. Magento 2.3.4
2. Magento 2 Authorize.net Marketplace module installed

### Steps to reproduce (*)

1. Enable Authorize.net module in admin
2. Enable 'Credit Card' payment method within Authorize.net

### Expected result (*)
1. User can see 'Credit Card' payment method in checkout, which uses the Authorize.net gateway

### Actual result (*)

1. Credit card method is not visible

**Comment by nbennett25** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @nbennett25. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nbennett25, here is your [Magento instance](https://i-26802-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26802-2-3-4.instances.magento-community.engineering/admin_3459](https://i-26802-2-3-4.instances.magento-community.engineering/admin_3459)
Login: `a817cdd3` Password: `aab50d118eef`
Instance will be terminated in up to 3 hours.

**Comment by nbennett25** [comment]
@magento unable to install authnet module.

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26802-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26802-2-3-4.instances.magento-community.engineering/admin_bf88](https://i-26802-2-3-4.instances.magento-community.engineering/admin_bf88)
Login: `e4e306c2` Password: `94e3721466e9`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @nbennett25 
I am not able to reproduce this issue at magento 2.4 instance 
I enabled `Authorize.net` from magento backend payment method the filled required details 
and  `Credit Card (Authorize.Net) ` is displaying at frontend 
![Screenshot from 2020-02-11 09-30-07](https://user-images.githubusercontent.com/25526037/74210422-b5214400-4cb1-11ea-8c49-75735731a16a.png)

**Comment by nbennett25** [comment]
Thx @shikhamis11  - is this with the auth.net provided module, or the deprecated Magento core Auth.net module? Can you reproduce it with 2.3.4?

**Comment by shintusingh** [comment]
It still gives error Failed to load the "AuthorizeNet_CreditCard/js/view/payment/method-renderer/creditcard" component after installing the module authorize.net from the marketplace because authorize.net is deprecated in 2.3.4. 
![image](https://user-images.githubusercontent.com/61272772/80795312-c34c7580-8bb9-11ea-9ad8-69f8d6273eae.png)
