### ISSUE TITLE
W3C error:  A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2680]
W3C error on fresh Magento 2 installation :

A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

FOLLOW"/>↩<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>↩<meta

W3C not compliant.

**Comment by MomotenkoNatalia** [comment]
@WebCenterShop-com Thanks for reporting this issue! Internal ticket - MAGETWO-46965

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-46965 is closed and delivered to mainline. Please let us know if you still have an issue

**Comment by minhluan259** [comment]
When I've added `<meta http-equiv="x-ua-compatible" content="ie=edge" />` to head (default_head_blocks.xml) (magento 2.1.1)
w3c error : Bad value  for attribute name on element meta: Must not be empty.
`<meta name="" content="ie=edge"/>`
It seem remove attribute `http-equiv="x-ua-compatible"`

**Comment by RedEnzian** [comment]
@minhluan259 Did you find a solution for this problem? Iam facing the same problem at the moment.
