### ISSUE TITLE
Timeout after amending price of product in cart

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#26819]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Add product to cart
2. Amend price of product in Magento admin
3. Refresh cart

### Expected result (*)

1. Cart loads and product price is updated

### Actual result (*)

1. Nginx timeout due to SQL query loop

**Comment by itwebdev2** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-26819-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26819-2-4-develop.instances.magento-community.engineering/admin_3049](https://i-26819-2-4-develop.instances.magento-community.engineering/admin_3049)
Login: `d9e1c299` Password: `140aa0f9ce75`
Instance will be terminated in up to 3 hours.

**Comment by itwebdev2** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-26819-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26819-2-3-3.instances.magento-community.engineering/admin_7465](https://i-26819-2-3-3.instances.magento-community.engineering/admin_7465)
Login: `12d3181c` Password: `bbea82326b03`
Instance will be terminated in up to 3 hours.

**Comment by itwebdev2** [comment]
Closing issue - unable to replicate because this repo doesn't have MSI.
Will log on MSI repo.

**Comment by itwebdev2** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-26819-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26819-2-3-3.instances.magento-community.engineering/admin_f0ff](https://i-26819-2-3-3.instances.magento-community.engineering/admin_f0ff)
Login: `05825c64` Password: `d773c1e740ad`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
@magento give me 2.3.7-p2 instance
