### ISSUE TITLE
heartbeats and keepalives in Stream.io not used - rabbitmq connection broken

### ISSUE THREAD

**Issue by bjorn-vdc** [magento/magento2#26815]
@nuzil 
Looks like that Magento implementation of amqp does not use heartbeats and keepalives, so I we see this quite often;

In StreamIO.php line 228:
                   
 Broken pipe or closed connection

In system.log
 report.ERROR: Broken pipe or closed connection
#0 /php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(369): PhpAmqpLib\Wire\IO\StreamIO->write(‘\x01\x00\x01\x00\x00\x00\r\x00<\x00Z\x00\x00\x00\x00...‘)
#1 /php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(493): PhpAmqpLib\Connection\AbstractConnection->write(‘\x01\x00\x01\x00\x00\x00\r\x00<\x00Z\x00\x00\x00\x00...’)
#2 /php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(244): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1319): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /magento/framework-amqp/Queue.php(164): PhpAmqpLib\Channel\AMQPChannel->basic_reject(‘73’, false)
#5 /magento/module-asynchronous-operations/Model/MassConsumerEnvelopeCallback.php(120): Magento\Framework\Amqp\Queue->reject(Object(Magento\Framework\MessageQueue\Envelope), false, ‘Connection rese...’)
#6 /magento/framework/Interception/Interceptor.php(58): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback->execute(Object(Magento\Framework\MessageQueue\Envelope))
#7 /magento/framework/Interception/Interceptor.php(138): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor->___callParent(‘execute’, Array)
#8 /magento/module-amqp-store/Plugin/AsynchronousOperations/MassConsumerEnvelopeCallback.php(96): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\MessageQueue\Envelope))
#9 /magento/framework/Interception/Interceptor.php(135): Magento\AmqpStore\Plugin\AsynchronousOperations\MassConsumerEnvelopeCallback->aroundExecute(Object(Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor), Object(Closure), Object(Magento\Framework\MessageQueue\Envelope))
### Preconditions (*)

1.
2.

### Steps to reproduce (*)
Running consumers with with either cron, or by cli magento queue:consumers:start asyn.operations.all

### Expected result (*)
Consumer running without error

### Actual result (*)
In StreamIO.php line 228:
                   
 Broken pipe or closed connection

In system.log
 report.ERROR: Broken pipe or closed connection
#0 /php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(369): PhpAmqpLib\Wire\IO\StreamIO->write(‘\x01\x00\x01\x00\x00\x00\r\x00<\x00Z\x00\x00\x00\x00...‘)
#1 /php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(493): PhpAmqpLib\Connection\AbstractConnection->write(‘\x01\x00\x01\x00\x00\x00\r\x00<\x00Z\x00\x00\x00\x00...’)
#2 /php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(244): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1319): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /magento/framework-amqp/Queue.php(164): PhpAmqpLib\Channel\AMQPChannel->basic_reject(‘73’, false)
#5 /magento/module-asynchronous-operations/Model/MassConsumerEnvelopeCallback.php(120): Magento\Framework\Amqp\Queue->reject(Object(Magento\Framework\MessageQueue\Envelope), false, ‘Connection rese...’)
#6 /magento/framework/Interception/Interceptor.php(58): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback->execute(Object(Magento\Framework\MessageQueue\Envelope))
#7 /magento/framework/Interception/Interceptor.php(138): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor->___callParent(‘execute’, Array)
#8 /magento/module-amqp-store/Plugin/AsynchronousOperations/MassConsumerEnvelopeCallback.php(96): Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\MessageQueue\Envelope))
#9 /magento/framework/Interception/Interceptor.php(135): Magento\AmqpStore\Plugin\AsynchronousOperations\MassConsumerEnvelopeCallback->aroundExecute(Object(Magento\AsynchronousOperations\Model\MassConsumerEnvelopeCallback\Interceptor), Object(Closure), Object(Magento\Framework\MessageQueue\Envelope))

**Comment by Flowlance** [comment]
I see the same issue.
Running this command
`/usr/bin/php bin/magento queue:consumers:start async.operations.all --batch-size 100`

results in

```
In StreamIO.php line 227:
  Broken pipe or closed connection
```

From the rabbitmq side, I see the following error

```
2020-02-12 13:01:01.932 [error] <0.20269.164> closing AMQP connection <0.20269.164> (XX.XXX.XX.XXX:10634 -> XX.XXX.XX.XXX:5672):
{writer,send_failed,{error,timeout}}
```

The connection is broken at exactly 30 seconds every time.

**Comment by Ian410** [comment]
I had this issue and tracked it down to` \Magento\Framework\Amqp\Config::createConnection()`.
In a previous version the SSL check was just `(bool) $this->getValue(self::SSL)`. It was changed to be a strict comparison against the string "true" (not the boolean).

Current: `$sslEnabled = trim($this->getValue(self::SSL)) === 'true';`

I was able to fix this with no code changes by updating env.php and changing `ssl' => true,` to `ssl' => 'true',`

**Comment by nuzil** [comment]
Hi @Ian410 , thanks for info.
I'm closing this issue then.

**Comment by bartoszkubicki** [comment]
> I had this issue and tracked it down to` \Magento\Framework\Amqp\Config::createConnection()`.
> In a previous version the SSL check was just `(bool) $this->getValue(self::SSL)`. It was changed to be a strict comparison against the string "true" (not the boolean).
> 
> Current: `$sslEnabled = trim($this->getValue(self::SSL)) === 'true';`
> 
> I was able to fix this with no code changes by updating env.php and changing `'ssl' => true,` to `'ssl' => 'true',`

I would like to add, it is not solved issue. On newly installed Magento 2.4 with rabbit not working not over ssl (local env) I get the same error. In order to solve it I had to add `ssl => 'false`. It is not that intuitive basing on docs - https://devdocs.magento.com/guides/v2.4/install-gde/prereq/install-rabbitmq.html - you CAN add ssl support, but who will mark ssl as false? I think this needs fix in code (if there is no argument ssl, we just put false here -> vendor/magento/framework-amqp/Config.php:143

**Comment by matutetandil** [comment]
Same here... I'm on localhost, not secure connection (If I add 'ssl' => 'true', it doesn't connect to the queue. The weird thing is that only fails when there is something to log in the console. If there is nothing to log, then works great.

**Comment by trinhpham** [comment]
@nuzil 
I am not using `ssl`, intentionally set it to `false` doesne't help (seems the same to @matutetandil )
My Magento CE version is 2.4.0.

Therefore I think we should re-open this issue

**Comment by kenit** [comment]
I also have this issue on my Magento 2.4.0. Is there any workaround solution to solve it temporary?

**Comment by krzysztofkuzniar** [comment]
In Magento 2.4.2 this issue still exist.

**Comment by bhupendravgroup** [comment]
This is due to the permssion issue while connecting with rabbitmq 
1) create a user in rabbitmq using below command
rabbitmqctl add_user username password
2) set this user as admin 
rabbitmqctl set_user_tags username administrator
3) you will see that this user does not have any permission 
rabbitmqctl list_user_permissions username
4) Assign this user all permssions
rabbitmqctl set_permissions -p /  username "^username -.*" ".*" ".*"

Now use this user in you env.php save the file and now run the bin/magento queue:consumers:start async.operations.all

It works for me, Best of Luch

**Comment by bhupendra-mehra** [comment]
This is due to the permssion issue while connecting with rabbitmq

create a user in rabbitmq using below command
rabbitmqctl add_user username password
set this user as admin
rabbitmqctl set_user_tags username administrator
you will see that this user does not have any permission
rabbitmqctl list_user_permissions username
Assign this user all permssions
rabbitmqctl set_permissions -p / username "^username -." "." ".*"
Now use this user in you env.php save the file and now run the bin/magento queue:consumers:start async.operations.all

It works for me, Best of Luck

**Comment by xt3r4m** [comment]
Magento 2.4.0 Same issue , any workaround/solution to resolve this issue.

**Comment by gaurav-webscale** [comment]
we had exactly the same issue. we resolved the issue by adding `--max-messages=5000` in the bin/magento command.

**Comment by madalinignisca** [comment]
I found myself also in this situation with 2.4.3 and noticed that consumers need explicit to have --max-messages=[some value you like] or will fail when a message comes in.
