### ISSUE TITLE
Adding/updating image using API will not create thumbnail for admin products grid

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26825]
Updating or adding a new image to a product will not create a thumbnail in the admin products grid. The admin products grid will have a placeholder.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create product
2. Upload image to product using the rest API
3. Visit the products grid in backend

### Expected result (*)

A thumbnail for the product should be rendered in the products grid.

### Actual result (*)

A placeholder for the product is rendered in the products grid.

### Additional information
When the product image is added from Admin, the **Image Roles** are displayed. Base, Small, Thumbnail, Swatch
![base_small](https://user-images.githubusercontent.com/51680745/74345584-fa7b6980-4db6-11ea-8d51-8bf9b15b9354.png)

![image_detail](https://user-images.githubusercontent.com/51680745/74345830-5a721000-4db7-11ea-8d47-45e8777a5e26.png)

If the product image is added using API, there are no image roles. 
![image_details_no](https://user-images.githubusercontent.com/51680745/74346247-f439bd00-4db7-11ea-852a-891b4d48b41f.png)

And as a result - no thumbnails 
![no_thumbnails](https://user-images.githubusercontent.com/51680745/74346576-71fdc880-4db8-11ea-9050-8fa4a79d8d17.png)

**Comment by engcom-Bravo** [comment]
Reproducible on Magento 2.4-develop 

When the product image is from Admin, the **Image Roles** are displayed. Base, Small, Thumbnail, Swatch
![base_small](https://user-images.githubusercontent.com/51680745/74345584-fa7b6980-4db6-11ea-8d51-8bf9b15b9354.png)

![image_detail](https://user-images.githubusercontent.com/51680745/74345830-5a721000-4db7-11ea-8d47-45e8777a5e26.png)

If the product image is added using API, Swagger in my case, there are no image roles. 
![image_details_no](https://user-images.githubusercontent.com/51680745/74346247-f439bd00-4db7-11ea-852a-891b4d48b41f.png)

And as a result - no thumbnails 
![no_thumbnails](https://user-images.githubusercontent.com/51680745/74346576-71fdc880-4db8-11ea-9050-8fa4a79d8d17.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31442` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#27170 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [960732ab38a0346feb41661c9989c992219f8a4a](https://github.com/magento/magento2/commit/960732ab38a0346feb41661c9989c992219f8a4a)

The fix will be available with the upcoming 2.4.0 release.
