### ISSUE TITLE
Category Product List issue 2.3.4

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#26826]
I have 14 Product in category ,
and i have setiing Per page 12, but it's showing all products

### Summary (*)
shwing all products in list,
![image](https://user-images.githubusercontent.com/50168477/74298804-ce3cfa00-4d70-11ea-837d-a859c5b1d9b7.png)

is only bug in 2.3.4 or something else

**Comment by niku0911** [comment]
Preconditions (*)
Magento 2.3.4 
PHP 7.2.27
MySQL 5.7

Steps to reproduce (*)
1) Fresh Install Magento 2.3.4
2) add category and add 14 Product assign to that category,
3) Frontside go and check that category product list showing all 14 products

![image](https://user-images.githubusercontent.com/50168477/74299402-86b76d80-4d72-11ea-99fd-66f5568c3653.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4 instance

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26826-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26826-2-4-develop.instances.magento-community.engineering/admin_08dc](https://i-26826-2-4-develop.instances.magento-community.engineering/admin_08dc)
Login: `cde3bfb6` Password: `c3e14502bf4c`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4 instance

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26826-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26826-2-3-4.instances.magento-community.engineering/admin_772d](https://i-26826-2-3-4.instances.magento-community.engineering/admin_772d)
Login: `9c909719` Password: `35c98248cb4c`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @niku0911 
I checked the issue at 2.4 instance I am not able to reproduce this issue .. 
by default It is 12 products per page on category pages and It is working correctly on 2.4 instance
. It seems this issue is at your end may be due to some additional customizations or setting changes . 
![Screenshot from 2020-02-12 09-43-17](https://user-images.githubusercontent.com/25526037/74302402-6d1b2380-4d7c-11ea-9607-808fe88640c8.png)

**Comment by niku0911** [comment]
Thanks for review ,

but i changed nothing in customizastion, i changed 12 to 9 now its working perfect.

**Comment by chrisastley** [comment]
I have this issue on 2 sites which have just been updated from 2.3.3 to 2.3.4, but have also successfully updated several sites without the issue appearing. I have tried changing the pagination size as @niku0911 suggested but no joy.

**Comment by niku0911** [comment]
i have an issue with Elastic Search module so i disabled them and , Reindex and clear cache.

so may be it's one of your extension are causing magento 2 default functionality.

**Comment by AaronONeill** [comment]
I too am seeing this on one upgraded site (-> 2.3.4), others were not affected.

**Comment by AaronONeill** [comment]
> I too am seeing this on one upgraded site (-> 2.3.4), others were not affected.

Just to follow up on this one, our issue was a node in a custom catalog_category_view.xml within the theme. We had the following in the file:

`<block class="Magento\Catalog\Block\Product\ListProduct" name="name.here"  template="Magento_Catalog::product/templatename.phtml"/>`

Defining the class as **Magento\Catalog\Block\Product\ListProduct** was causing the category to load all products on initial load. In our case we didn't actually need to use this class and we instead changed this to **Magento\Framework\View\Element\Template**, which resolved the issue.
