### ISSUE TITLE
W3C warning:  Element nav does not need a role attribute.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2682]
W3C warning on fresh Magento 2 installation :

content">↩<nav class="navigation" role="navigation">↩    <

W3C not compliant.

**Comment by MomotenkoNatalia** [comment]
@WebCenterShop-com  you are completely right! We will fix this. Internal ticket: MAGETWO-46933
Thanks!

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-46933 is closed and delivered to mainline. Please let us know if you still have an issue.
