### ISSUE TITLE
Deleting a configurable child breaks cart and checkout pages that contained it.

### ISSUE THREAD

**Issue by drew7721** [magento/magento2#26824]
### Preconditions (*)

1. Magento 2.3.4 | 2.3.3 | 2.2.10 (reproduces on these versions)
2. PHP 7.2.27
3. MySQL 5.7

### Steps to reproduce (*)

1. Fresh install of Magento 2 (with sample data if needed)
2. Add a configurable product to the cart ( the simple child product will be added https://i.imgur.com/vBVqHNY.png )
3. Go to the Admin panel and **delete** the child product that you added to the cart in step 2.
4. Note that deleting the product changed the database table `quote_item` from 
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/9411699/74274672-7b1b6680-4ce0-11ea-831a-adab157ed25c.png"> to 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/9411699/74274808-bcac1180-4ce0-11ea-83b3-4274f8f16688.png">
5. See how the parent configurable is still in the `quote_item` table.
6. The checkout/cart and checkout page are broken and return a blank white page.

#### 1. Sales rule condition

The problem is that the product is no longer found. So the sales rule condition is breaking the page. 
For instance, if this line *(68)* would be set to `$validated = true; //$cond->validate($item);` https://github.com/magento/magento2/blob/8628eb8b346ea7adceca720f04f04d9f5474da7c/app/code/Magento/SalesRule/Model/Rule/Condition/Product/Found.php#L67-L70  we would then get this page 
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/9411699/74275542-09dcb300-4ce2-11ea-90fb-de066a7b2517.png">

#### 2. Database
Note that this also leaves lots of data in the database. not only does it not clean the `quote_item` table properly but it does not remove the linked data from the `quote_item_option` table either.
This causes these tables to be very large for no reason. In my case more than 1.5M rows could be deleted.

#### 3. Quote Plugin
https://github.com/magento/magento2/blob/8628eb8b346ea7adceca720f04f04d9f5474da7c/app/code/Magento/Quote/Model/Product/QuoteItemsCleaner.php#L26-L32

This plugin does is responsible for cleaning the table but does a half job since the parent configurable product will not be removed from the quotes and hence the cause of this bug. In my opinion, this delete should be done by `sku` so that *all* the product get removed. In this case, an index would be required on the `sku` column.

#### 4. Foreign Keys and Cascade
A better fix for this would be to add a foreign key constraint on the `quote_item` table with the `catalog_product_entity` table and cascade on delete. That would completely remove the need for that plugin and all the code that it involves. I'm curious to see comments regarding this. I'm really asking myself why the decision was made to use a plugin in this case.

Also, some third party vendors bypass the plugins and events thrown by this method and hence leave an even bigger mess in the db. For instance, using a module such as RapidFlow to remove products will not trigger the plugins nor the event thrown by this method.
https://github.com/magento/magento2/blob/8628eb8b346ea7adceca720f04f04d9f5474da7c/app/code/Magento/Catalog/Model/ResourceModel/Product.php#L369-L377
One more reason why I believe this should be fixed with a database foreign key and probably an additional index on the `sku` column.

### Expected result (*)
1. It should show the cart and it should properly clean the quotes to not maintain *dead data* in the `quote_item` table.
2. At least, it should show the cart with the error message so that the customer can remove the item from the cart or edit the configuration options.
3. It should remove the parent configurable products from the quote as well and not leave outdated data in the quote tables.

### Actual result (*)

1. Cart and Checkout pages are broken
2. Database quote tables are polluted with deprecated data.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31571` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drew7721** [comment]
After looking into this, it seem that the same issue was happening with the wishlist.
[See first release note for 2.3.1](https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.html#wishlist)

I assume this could be fixed in the same way. Looking for the commit that fixed that. For some reason there is no link in the release notes.

**Comment by hostep** [comment]
@drew7721: just a hint, if you look in the source code of the release notes, you'll find the ticket number: `MAGETWO-95311`. If you then search for commits in a clone of this git repo using something like: `git log origin/2.4-develop --grep 'MAGETWO-95311'`, you'll find 2 commits:
- 4333c92bf37af3c9e50fd953a46e904f0a1c2b05 (the fix)
- 6b14118933380d3d80d2efcb9a3e6095a93cb6b1 (the merge commit)

Not sure if this will be helpful here, but now you learned how to find fixes from the release notes in the git repository 🙂

**Comment by drew7721** [comment]
Great hint @hostep ! That will be very handy! Thanks!

**Comment by KonstantinZhidkovskiy** [comment]
@magento I’m working on it

**Comment by KonstantinZhidkovskiy** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by nickpiro** [comment]
We're still seeing this exact issue on 2.3.6! Why is this closed!?

In our case, we've been converting old Configurable products to new products using swatches. The parent is changed but the child/simple is the same as the old. 

if a customer had the original item in their cart not only does the parent stay but so does the child. We've been able to track this by keeping old parents with SKUs ending in -OLD.

Any information on this @magento-engcom-team or @drew7721 did you get a fix for this?
