### ISSUE TITLE
Product Image Watermarks Not Displaying 2.3.0

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#26828]
We just upgraded from 2.2.8 to 2.3.0 and product image watermarks have disappeared! 

### Preconditions (*)

1. Magento 2.3.0
2.

### Steps to reproduce (*)

1. Magento 2.3.0
2. Add product watermark

### Expected result (*)

1. Prouduct image watermark.

### Actual result (*)

1. No product image watermark!

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26828-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26828-2-4-develop.instances.magento-community.engineering/admin_c6b5](https://i-26828-2-4-develop.instances.magento-community.engineering/admin_c6b5)
Login: `5f77da96` Password: `289f2143c0ff`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @nickpiro.
Can not able to reproduce the issue in latest magento instance
Please review below screenshot for same
![image](https://user-images.githubusercontent.com/46617848/74510916-c759e700-4f2a-11ea-916d-2dbe1d9d75af.png)
Feel free to reopen the issue if you find this issue in latest magento 2.3.4
Thanks !!
