### ISSUE TITLE
W3C warning: The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2683]
W3C warning on fresh Magento 2 installation :

The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.

age-main"><a id="contentarea" name="contentarea" tabindex="-1"></a>↩<

W3C not compliant.

**Comment by odubovyk** [comment]
Thank you for your question.
Talking about "name" attribute I imply that it is about Forms.
The "name" attribute is used when sending data from form controls to a server in a form submission.
Also it is used to group form controls like radio buttons.

Please specify more clearly the issue, if you implied something different, and my response was not sufficient.

**Comment by odubovyk** [comment]
Sorry, I didn't get your point promptly.
Yes, there is such issue, and we will consider it carefully.
After that we will notify you about our further steps on this issue.

**Comment by MomotenkoNatalia** [comment]
Internal ticket: MAGETWO-47214

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-47214 is closed and delivered to mainline. Please let us know if you still have an issue.
