### ISSUE TITLE
Error while logging out

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26834]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.3
3. Varnish
4. Redis
5. SSL enabled

### Steps to reproduce (*)

1. Go to store frontend and Login and logout.

### Expected result (*)

1. No errors

### Actual result (*)

1. ```
2020/02/12 16:07:06 [error] 1871#1871: *68511 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /home/site/web/site.com/public_html/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php:44
Stack trace:
#0 /home/site/web/site.com/public_html/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php(44): strpos(NULL, '</body')
#1 /home/site/web/site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Theme\Controller\Result\JsFooterPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#2 /home/site/web/site.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}()
#3 /home/site/web/site.com/public_html/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Int" while reading response header from upstream, client: 127.0.0.1, server: site.com, request: "GET /amazon/logout?_=1581503823299 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "www.site.com", referrer: "https://www.site.com/customer/account/logoutSuccess/"

```

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26834-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26834-2-4-develop.instances.magento-community.engineering/admin_fad9](https://i-26834-2-4-develop.instances.magento-community.engineering/admin_fad9)
Login: `1e6589dd` Password: `c50c74ce8461`
Instance will be terminated in up to 3 hours.

**Comment by monotheist** [comment]
> Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

How are you going to reproduce using above instance? You need the setup I mentioned.

**Comment by sudheers-kensium** [comment]
@monotheist I am not able to reproduced in Magento 2.4-develop instance

**Comment by GuiltyNL** [comment]
@monotheist 

Take a look here:

https://community.magento.com/t5/Magento-2-x-Technical-Issues/JsFooterPlugin-php-Error/m-p/376068#M12165

**Comment by monotheist** [comment]
@GuiltyNL Thank you.

**Comment by bst2002git** [comment]
@monotheist see my comment #25438 (bottom)
