### ISSUE TITLE
Attributes API returns wrong options values for swatch texts attributes

### ISSUE THREAD

**Issue by vincentteyssier** [magento/magento2#26836]
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Create a swatch text attribute in admin ui
![swatch](https://user-images.githubusercontent.com/16136533/74331704-87f99200-4d94-11ea-9f56-b2e7bca4416a.PNG)

2. Retrieve this attribute details via API:
/index.php/rest/default/V1/products/attributes/shipsfrom

```
{
    "is_wysiwyg_enabled": false,
    "is_html_allowed_on_front": true,
    "used_for_sort_by": false,
    "is_filterable": false,
    "is_filterable_in_search": false,
    "is_used_in_grid": true,
    "is_visible_in_grid": true,
    "is_filterable_in_grid": true,
    "position": 0,
    "apply_to": [],
    "is_searchable": "0",
    "is_visible_in_advanced_search": "0",
    "is_comparable": "0",
    "is_used_for_promo_rules": "0",
    "is_visible_on_front": "0",
    "used_in_product_listing": "0",
    "is_visible": true,
    "scope": "global",
    "attribute_id": 197,
    "attribute_code": "shipsfrom",
    "frontend_input": "select",
    "entity_type_id": "4",
    "is_required": true,
    "options": [
        {
            "label": " ",
            "value": ""
        },
        {
            "label": "N2",
            "value": "5450"
        },
        {
            "label": "China",
            "value": "5448"
        }
    ],
    "is_user_defined": true,
    "default_frontend_label": "shipfrom",
    "frontend_labels": [],
    "backend_type": "int",
    "source_model": "Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table",
    "default_value": "5448",
    "is_unique": "0",
    "validation_rules": []
}

```
### Expected result (*)
Options would show the swatch values: `N2` and `China`

### Actual result (*)
Options show the label internal id: `5450` and `5448`

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26836-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26836-2-4-develop.instances.magento-community.engineering/admin_d2c7](https://i-26836-2-4-develop.instances.magento-community.engineering/admin_d2c7)
Login: `0e29a6fc` Password: `a162e962de9b`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38958` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @vincentteyssier,

I believe that is expected behavior, the values that are inserted on admin are actually labels, so that is why the API returns on that format, the ID is the value and it would facilitate to build select HTML component.

Closing this as it doesn't seem to be an issue.
