### ISSUE TITLE
lib flder

### ISSUE THREAD

**Issue by r32rf** [magento/magento2#26832]
hello i a,m supposed to comit lib folder in git ????????? i no having of a clue. in commit any i make it always has done big show of making big change and i do not want 99999999999999999 terragigglebytes in my server for repository. how do fix if i want make have do my comit and work ?????? 

tank you of the very much!

**Comment by engcom-Alfa** [comment]
Hi @r32rf 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by r32rf** [comment]
????
