### ISSUE TITLE
Hitting enter on create folder in media gallery refreshes the page

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26847]
When creating a new folder in the media gallery, if you hit enter after naming instead of using mouse to click on "Ok", the page will refresh, all changes during the editing process will be lost because it was not saved.

Bad UX and bad intent.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Open the media gallery by inserting an image
2. Click on a directory and click "Create Folder"
3. Type in directory name and hit Enter

### Expected result (*)

Enter should do the same action as clicking OK with the mouse.

### Actual result (*)

Page is refreshed, potential changes made in the editor is lost.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26847-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26847-2-4-develop.instances.magento-community.engineering/admin_fed0](https://i-26847-2-4-develop.instances.magento-community.engineering/admin_fed0)
Login: `baf777b9` Password: `a6d8c60620b0`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31455` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#27029 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [21afe21644fe586b83654344d56b6651a3279873](https://github.com/magento/magento2/commit/21afe21644fe586b83654344d56b6651a3279873)

The fix will be available with the upcoming 2.4.0 release.
