### ISSUE TITLE
Bundle Product Issue

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#26845]
### Preconditions (*)

1. On vanilla magento instance the magento CollectionFactory doesn't list bundle product after update the bundle product via default magento import in csv format. (Only show newly added product).

### Steps to reproduce (*)

1. Create new bundle product and assign to some categories. The Product listed in the CollectionFactory correctly. 
2. After that i export the product sheet via default magento feature and add new product and upload it again.

### Expected result (*)

1. The result show number of older product would be updated and newer product be added.
2. The CollectionFactory would return all the product (Including older and newly added product).

### Actual result (*)

1. But, the older product could disappear from CollectionFactory.

### Additional info

I use custom page to display all the bundle product and i use productCollectionFactory to load the product in that page.

EX Code :
$Products = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection'); $ProCollection = $Products ->addAttributeToSelect('*')->addAttributeToFilter('type_id','bundle'); print_r($ProCollection->getData());

Output on first import of product :

Array ( [0] => Array ( [entity_id] => 2719 [attribute_set_id] => 13 [type_id] => bundle [sku] => B_388_1064_532990 [has_options] => 1 [required_options] => 1 [created_at] => 2020-02-12 08:12:59 [updated_at] => 2020-02-12 16:10:50 [row_id] => 2719 [created_in] => 1 [updated_in] => 2147483647 ) )

After i update the same bundle product name and import the output should look like :

Array ()

**Comment by engcom-Bravo** [comment]
Hello @vijay-prevaj 

We tried to reproduce this issue on Magento 2.4-develop 
After the Import of .csv file, the message appeared _Created 1, Updated 7_, as expected
![created_updated](https://user-images.githubusercontent.com/51680745/74445771-9bcdf280-4e7f-11ea-8bc2-ff968bdfd737.png)

We also tried to update only the Bundle product by adding another, already existing product to the bundle option.

No products disappeared and no bundle option disappeared.

Can you please confirm that you are facing this issue on Magento 2.4-develop? If yes, please, provide more details so we could start fixing the issue? 

Thank you in advance

**Comment by vijay-prevaj** [comment]
I use custom page to display all the bundle product and i use productCollectionFactory to load the product in that page.

**EX Code :** 
`$Products = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
$ProCollection = $Products ->addAttributeToSelect('*')->addAttributeToFilter('type_id','bundle');
print_r($ProCollection->getData());`

**Output on first import of product :**

`Array
(
    [0] =>; Array
        (
            [entity_id] =>; 2719
            [attribute_set_id] =>; 13
            [type_id] =>; bundle
            [sku] =>; B_388_1064_532990
            [has_options] =>; 1
            [required_options] =>; 1
            [created_at] =>; 2020-02-12 08:12:59
            [updated_at] =>; 2020-02-12 16:10:50
            [row_id] =>; 2719
            [created_in] =>; 1
            [updated_in] =>; 2147483647
        ) 
)`

**After i update the same bundle product name and import the output should lool like :**

`Array
()`

**Comment by vijay-prevaj** [comment]
And also i noticed that in **cataloginventory_stock_status** table the value for the bundle item is removed when i run reindex so the collection become empty.

**Comment by engcom-Bravo** [comment]
Hello @vijay-prevaj 

Thank you for your quick response 

I was able to reproduce this with your code. After exporting, the previously added Bundle product disappeared from Storefront

We are confirming this issue on Magento 2.4-develop.

Thank you for collaboration

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31534` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vijay-prevaj** [comment]
Thank you for confirming this working this issue. And also we found solution to this issue.

Here is the patch we developed to resolve the issue.

https://drive.google.com/open?id=1W-htVQ0CckS6275otpegEt7SrZO3YXlj

**Comment by CarmineDamore78** [comment]
@magento I'm working on this

**Comment by CarmineDamore78** [comment]
hi @magento-admin. I tried to replicate the issue on M2.4-develop without success
I followed the procedure and after the import I had the array populated
`Array ( [0] => Array ( [entity_id] => 45 [attribute_set_id] => 11 [type_id] => bundle [sku] => 24-WG080 [has_options] => 1 [required_options] => 1 [created_at] => 2020-05-22 12:59:22 [updated_at] => 2020-05-22 12:59:22 ) [1] => Array ( [entity_id] => 2047 [attribute_set_id] => 4 [type_id] => bundle [sku] => Test Bundle [has_options] => 1 [required_options] => 1 [created_at] => 2020-05-22 13:55:39 [updated_at] => 2020-05-22 14:20:23 ) [2] => Array ( [entity_id] => 2048 [attribute_set_id] => 4 [type_id] => bundle [sku] => Test Bundle 2 [has_options] => 0 [required_options] => 0 [created_at] => 2020-05-22 14:20:23 [updated_at] => 2020-05-22 14:20:23 ) )`
`
On M2.4-develop this bug is fixed.

**Comment by sdzhepa** [comment]
Hello @CarmineDamore78 

Thank you for confirmation that it fixed in the latest `2.4-develop` code.
Closed as fixed
