### ISSUE TITLE
URL re-writes only work when is_autogenerated is set to 1

### ISSUE THREAD

**Issue by mswaidan** [magento/magento2#2684]
Was having trouble getting URL rewrites to work for my products, then noticed that one was working. That one was  auto-generated. Looked at the url_rewrite table, and only rewrites that had is_autogenerated = 1 worked. Changing the value from 0 to 1 for manually generated rewrites makes them function correctly. Is this a bug or some idiosyncratic error on just my install?

**Comment by veloraven** [comment]
@mswaidan is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
