### ISSUE TITLE
New account registration email not sent v2.3.1, 2.3.3, 2.3.4

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#26849]
Hi,

We've recently upgraded our store in staging from 2.3.1 to 2.3.4 and experienced problems with transactional emails not being sent (order confirmation, etc). We fixed this by applying the patch mentioned in ticket https://github.com/magento/magento2/issues/25338 and then upgrading to 2.3.4.

However, we discovered new account registration emails are not being sent still (no welcome emails). We also discovered the same issue is happening on our production site, which is v2.3.1.

Any ideas?

Thanks,
Michael Mussulis

**Comment by xtremevision** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @xtremevision. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @xtremevision, here is your [Magento instance](https://i-26849-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26849-2-4-develop.instances.magento-community.engineering/admin_83a7](https://i-26849-2-4-develop.instances.magento-community.engineering/admin_83a7)
Login: `cb172599` Password: `a21a38e72074`
Instance will be terminated in up to 3 hours.

**Comment by xtremevision** [comment]
I tried reproducing the issue on 2.4-dev, and I'm not getting any emails. I tried playing around with the backend settings, but I don't know if I it's a problem in 2.4-dev or your instance is not setup to send emails, or my smtp is rejecting them due spf/dmarc rules. I tried gmail and still nothing.

**Comment by xtremevision** [comment]
Steps to reproduce:

- Click on Create Account link
- Fill out the form and submit
- Wait for the welcome email

**Comment by FadyEffat** [comment]
I'm having the same issue with 2.3.3 and 2.3.4

**Comment by sfritzsche** [comment]
Do you have checked the 
https://github.com/magento/magento2/issues/25542
https://github.com/magento/magento2/issues/25076
issues ?

These are for us the typical problems when sending emails (magento 2.3.3). Issue "25542" is related to error message "Invalid header value detected" in system.log.

**Comment by engcom-Delta** [comment]
Hi @xtremevision I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Welcome email is sent after customer was registered
![image](https://user-images.githubusercontent.com/51681379/99305403-674af500-285c-11eb-817b-3e68597186fa.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
