### ISSUE TITLE
Fatal error sending ship after deleted product.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26848]
How to reproduce.
Place an order
Delete the product of the order
Send ship in back end.

Magento 2.3.4.

**Comment by shikhamis11** [comment]
Hi @Thumper85 
You can reproduce this issue while generating shipment through api ..
Also please correct the issue reporting format 
Please check [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines )
