### ISSUE TITLE
[FEAT] Token Revocation Call in REST API

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#26859]
### Description (*)
As a user, when I log out, I want to guarantee that my token is revoked. Currently, with the REST API, there's no known way to do this.

The GraphQL api supports this:
https://devdocs.magento.com/guides/v2.3/graphql/mutations/revoke-customer-token.html

### Expected behavior (*)
I can securely revoke my authentication token.

### Benefits
Basic security improvement for customers.

### Additional information
cc: @zetlen

**Comment by shikhamis11** [comment]
Hi @damienwebdev 
Thank you for reporting this issue . This issue will move faster if you will create this issue at [Magento Feature request](https://github.com/magento/community-features) repository.
Please do so . 
thanks
