### ISSUE TITLE
Wrong gallery behavior when query url param configurable product

### ISSUE THREAD

**Issue by sergiy-v** [magento/magento2#26858]
Wrong gallery behavior for preselected option by query url param for configurable product.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Create a configurable product (the `color` attribute uses for example) with associated products:
- product with 'Black' color
- product with 'White' color 

2. Add image and video for each products like on the screenshot below.
<img width="1783" alt="Screen Shot 2020-02-13 at 11 36 56 AM" src="https://user-images.githubusercontent.com/1982263/74421129-3533df00-4e55-11ea-8ef9-3b607424b1df.png">

3. Add needed params to product URL to preselected option.
For example 
- `http://store.com/configurable-b.html#93=4` where 93 - is `color` attribute id and 4 - 'white' option id
- `http://store.com/configurable-b.html#93=5` where 93 - is `color` attribute id and 5 - 'black' option id 

### Expected result
1. For URL with query to preselect 'white' option.
<img width="935" alt="Screen Shot 2020-02-13 at 2 03 43 PM" src="https://user-images.githubusercontent.com/1982263/74433749-ad0c0480-4e69-11ea-8eb0-6d5cc83f467e.png">

2. For URL with query to preselect 'black' option.
<img width="934" alt="Screen Shot 2020-02-13 at 2 01 08 PM" src="https://user-images.githubusercontent.com/1982263/74433824-d462d180-4e69-11ea-85dd-ccee39af9f84.png">

### Actual result
1. For URL with query to preselect 'white' option.
<img width="932" alt="Screen Shot 2020-02-13 at 1 55 56 PM" src="https://user-images.githubusercontent.com/1982263/74433240-b34db100-4e68-11ea-8b91-a6f72c340f2c.png">

2. For URL with query to preselect 'black' option.
<img width="921" alt="Screen Shot 2020-02-13 at 1 53 42 PM" src="https://user-images.githubusercontent.com/1982263/74433085-6cf85200-4e68-11ea-9aa5-617041668f63.png">

**Comment by Leandry** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-26858-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26858-2-4-develop.instances.magento-community.engineering/admin_6afb](https://i-26858-2-4-develop.instances.magento-community.engineering/admin_6afb)
Login: `4f18cd1e` Password: `8f208541171f`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31480` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, here is your [Magento instance](https://i-26858-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26858-2-4-develop.instances.magento-community.engineering/admin_e54d](https://i-26858-2-4-develop.instances.magento-community.engineering/admin_e54d)
Login: `b8fa97fb` Password: `b6c25bc07745`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v. Thank you for your report. 
The issue has been fixed in magento/magento2#26560 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [54f93e22ae3d9387d5a8c259d6933efbcd5461e8](https://github.com/magento/magento2/commit/54f93e22ae3d9387d5a8c259d6933efbcd5461e8)

The fix will be available with the upcoming 2.4.0 release.
