### ISSUE TITLE
Wrong gallery main image and active preview after updating for configurable products.

### ISSUE THREAD

**Issue by sergiy-v** [magento/magento2#26856]
Wrong gallery main image and active preview after gallery data updating for configurable products.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Create a configurable product (the `color` attribute uses for example) with associated products:
- product with 'Black' color
- product with 'White' color 

2. Add image and video for each products like on the screenshot below.
<img width="1783" alt="Screen Shot 2020-02-13 at 11 36 56 AM" src="https://user-images.githubusercontent.com/1982263/74421129-3533df00-4e55-11ea-8ef9-3b607424b1df.png">

### Expected result
1. Expected result for case when the `color` attribute has 'Dropdown' type.
<img width="1852" alt="Screen Shot 2020-02-13 at 11 49 44 AM" src="https://user-images.githubusercontent.com/1982263/74422278-0a4a8a80-4e57-11ea-8c26-dfe533bc26f6.png">

2. Expected result for case when the `color` attribute has 'Visual Swatch' type.
<img width="1879" alt="Screen Shot 2020-02-13 at 12 05 47 PM" src="https://user-images.githubusercontent.com/1982263/74423615-3bc45580-4e59-11ea-93c8-86812e64dc9f.png">

### Actual result
1. Actual result for case when the `color` attribute has 'Dropdown' type. Wrong main image and active preview for 'Black' option.
<img width="1857" alt="Screen Shot 2020-02-13 at 11 45 04 AM" src="https://user-images.githubusercontent.com/1982263/74421907-75e02800-4e56-11ea-8654-ba310ba71caa.png">

2. Actual result for case when the `color` attribute has 'Visual Swatch' type. Wrong main image and active preview for 'White' option. Swatch logic always use first image after gallery updating.
<img width="1872" alt="Screen Shot 2020-02-13 at 11 55 47 AM" src="https://user-images.githubusercontent.com/1982263/74422944-1b47cb80-4e58-11ea-93ec-0cc81fe1ed24.png">

**Comment by Leandry** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-26856-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26856-2-4-develop.instances.magento-community.engineering/admin_989a](https://i-26856-2-4-develop.instances.magento-community.engineering/admin_989a)
Login: `75a38337` Password: `b6581c639d16`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Leandry Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31478` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v. Thank you for your report. 
The issue has been fixed in magento/magento2#26560 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [54f93e22ae3d9387d5a8c259d6933efbcd5461e8](https://github.com/magento/magento2/commit/54f93e22ae3d9387d5a8c259d6933efbcd5461e8)

The fix will be available with the upcoming 2.4.0 release.
