### ISSUE TITLE
500 Internal Server Error upon clicking SAVE button of product record adding/editing

### ISSUE THREAD

**Issue by protodevsystems** [magento/magento2#2686]
Admin Panel loads and allows me to login right after installation. But when I try to add a Simple Product and click on save, a 500 Internal Server Error page comes up. What should I do? Is this a permission issue? Same with editing a product: click on a product, then SAVE, 500 error.

I tried to follow this: 
http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html for Centos
and still same problem.

On my Vesta Control Panel, error log shows:

[error] 31806#0: _4321 upstream prematurely closed connection while reading response header from upstream, client: *__._**.**_._**, server: ****************_.com, request: "POST /**_*************_/catalog/product/save/id/1/key/3d7eb4f2a74643f3800f2aa95186299ee71c64f8ce9af0dddbd276a34d94f06d/back/edit/active_tab/product-details/ HTTP/1.1", upstream: "http://**_*************_:8080/**_**_/catalog/product/save/id/1/key/3d7eb4f2a74643f3800f2aa95186299ee71c64f8ce9af0dddbd276a34d94f06d/back/edit/active_tab/product-details/", host: "www.**_**_.com", referrer: "http://www.**_**_.com/**_***/catalog/product/edit/id/1/key/d46603a1c1ef83c89a01c3929063102f4e5672c3b5105e91acc2be9588027e3a/"

Any ideas guys? Excited to use M2 but this is hindering me in deploying the site...Thanks in advance!

**Comment by protodevsystems** [comment]
Seems immediately after installing, I've ignored the required indexing and cron job setup and tried to add a product right after setup. After setting up cron and manually reindexing from ssh, then it doesn't give the error anymore upon saving. So I guess this one's solved. But any explanations would be better if there's any, guys? thanks!

**Comment by sidolov** [comment]
Hi @protodevsystems. Thank you for your report. 
The issue has been fixed in magento/magento2#18733 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [a4b5cc1106f69325ab21774c0b5d86653101a2a0](https://github.com/magento/magento2/commit/a4b5cc1106f69325ab21774c0b5d86653101a2a0)

The fix will be available with the upcoming 2.3.1 release.
