### ISSUE TITLE
Configurable product disable configurations not working properly

### ISSUE THREAD

**Issue by Mathanagopal97** [magento/magento2#26872]
When I disable a generated simple product in a configurable product, rest of the products in the configuration is not getting displayed.
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create an attribute set named shirt and add colour and size as the product attributes. Colour contains blue and black. Size contains Small and Large. Both of them are dropdown.
2. Create a configurable product Pant and create the configurations based on the attribute set (Refer images).
3. Save the product.
4. Come back to the configurable product page (Pant) and disable any generated simple product.
### Expected result (*)

1. Only that product getting disabled and rest of the sizes get displayed.

### Actual result (*)

1. All the sizes are disappearing from frontend for that colour.

![Screenshot from 2020-02-14 12-36-27](https://user-images.githubusercontent.com/29875835/74509708-2b2ee080-4f28-11ea-9b2c-c6f5db36e596.png)

![Screenshot from 2020-02-14 12-36-34](https://user-images.githubusercontent.com/29875835/74509745-439efb00-4f28-11ea-8f5e-4767111e38d7.png)

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97, here is your [Magento instance](https://i-26872-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26872-2-4-develop.instances.magento-community.engineering/admin_90ea](https://i-26872-2-4-develop.instances.magento-community.engineering/admin_90ea)
Login: `a4644bcf` Password: `9902eafd9f4f`
Instance will be terminated in up to 3 hours.

**Comment by Mathanagopal97** [comment]
Looks like the magento instance provide is not secure. 
![Screenshot from 2020-02-14 12-53-04](https://user-images.githubusercontent.com/29875835/74510069-f707ef80-4f28-11ea-8b4e-a57591851970.png)

**Comment by Mathanagopal97** [comment]
@ajijshekh123 You can use the provide instance if you want.

**Comment by ajijshekh123** [comment]
@Mathanagopal97 - Click on Advance and Click on the footer of the link.

**Comment by Mathanagopal97** [comment]
> @Mathanagopal97 - Click on Advance and Click on the footer of the link.

Thanks man.

**Comment by ajijshekh123** [comment]
Hello @Mathanagopal97,
I have verified this issue as per your steps and screenshot. But I can't reproduce this issue in the Default Magento 2.4 Instance.
Please see attached below issue video:
![ConfigProduct_Issue](https://user-images.githubusercontent.com/24711761/74511917-17d24400-4f2d-11ea-834d-dd62e54115de.gif)

Let me know your feedback.

Thanks.

**Comment by Mathanagopal97** [comment]
Ok fine. I'll close this one.

**Comment by bugbuster2** [comment]
Did you manage to resolve this problem at the end? Because I have the same problem, where if I disable one configurable option, the rest disappears from the drop down menu instead of the one that has been disabled.
