### ISSUE TITLE
API Functional Tests not using "test database" when running data fixtures.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26875]
### Preconditions (*)

1. Magento 2.3.3-p1
2. PHP 7.1
3. Default DB
4. API Functional Test DB
5. Configure API Functional Test phpunit.xml and install-config-mysql.php (set this to use the API DB)

### Steps to reproduce (*)

1. Create API Test
2. Use @magentoApiDataFixture (order_with_customer.php)

### Expected result (*)

1. Test should run data fixture against API DB

### Actual result (*)

1. Default DB is used instead
2. Data is deleted from Default DB due to usage of default_rollback in data fixture file

**Comment by gwharton** [comment]
Does it use the functional test database instead if you set the 

`<const name="TESTS_MAGENTO_INSTALLATION" value="disabled"/>` 

entry to enabled in the phpunit config?

**Comment by paul-gene** [comment]
> Does it use the functional test database instead if you set the
> 
> `<const name="TESTS_MAGENTO_INSTALLATION" value="disabled"/>`
> 
> entry to enabled in the phpunit config?
> 
> In my installation if this is set to disabled, the tests are run using the normal database for the installation. However if you set to enabled, it installs a fresh database and uses that instead.

It's actually set to `disabled` by default, however, if you read the comment above that setting; "Defines if Magento should be installed before tests execution" I don't think that should be the cause of it using the "live" database instead of the one defined in the mysql config

**Comment by gwharton** [comment]
but without magento being installed into a new database, what option has it got? Its gotta either use the 'live' database for that instance, or an isolated database. i.e that setting.

More worryingly, i've just set it to enabled and run the api-functional tests and although it did install into a new database to run the api-functional, it also resulted in the dropping of all tables from the 'live' database.

**Comment by gwharton** [comment]
The config that is defined in the mysql config file, is only used if that setting is set to enabled. It defines the "temporary clean" database that is used if the setting is enabled. Otherwise it uses whatever is defined in the instance config.

Atleast thats my take on it.

**Comment by paul-gene** [comment]
> but without magento being installed into a new database, what option has it got? Its gotta either use the 'live' database for that instance, or an isolated database. i.e that setting.

Because I copied my live DB manually and configured the functional test mysql file to use the copy.

> Atleast thats my take on it.

Do you know that to be fact?
