### ISSUE TITLE
CMS/Static Blocks not migrating

### ISSUE THREAD

**Issue by devriles** [magento/magento2#2688]
Upon completion of migration the CMS and Static Block pages, the migration did not grab these from the Magento 1.9.x DB.

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment]
Hi, @mreilly82 thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
