### ISSUE TITLE
Tax is not showing in authorize.net panel for orders with Authorize.net (not directpost)

### ISSUE THREAD

**Issue by ramu15061987** [magento/magento2#26893]
### Preconditions (*)

1. Magento version 2.4-develop, Magento 2.3.4
2. Configured Authorize.net  not direct post

### Steps to reproduce (*)

1. Placed an order with Authorize.net and tax not showing in authorize.net panel
2. We enabled debug and observed tax related params are not exist in request

### Expected result (*)

Tax should appear in authorize.net

### Actual result (*)

 tax related params are not exist in request

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31711` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ramu15061987** [comment]
Any update on this issue?

**Comment by srsathish92** [comment]
@ramu15061987 Authorize.net module seems deprecated from 2.3.4.
FYI: https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445
In that blog says, in 2.4.0 - 'authorize.net' will be completely removed. so please use the official [extension](https://marketplace.magento.com/authorizenet-magento-module-authorizenet.html) from marketplace instead.

Also it was already removed yesterday from 2.4-develop: https://github.com/magento/magento2/commit/e344d30855ba12d48625c7daf08f3fbc65b65cdd

@magento-engcom-team @engcom-Alfa I think this issue should be closed. please confirm

**Comment by sdzhepa** [comment]
Thank you @srsathish92 

Yes, I can confirm based on doc [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

Authorize.net will be 
> Will be completely removed. starting from 2.4.0 
> Use the [official extension](https://marketplace.magento.com/authorizenet-magento-module-authorizenet.html) from marketplace instead

We can close this issue
