### ISSUE TITLE
Only X left Threshold is not working in configurable product

### ISSUE THREAD

**Issue by surelockrich** [magento/magento2#26896]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Stores --> catalog --> inventory --> Stock options : Only X left Threshold= 3
### Expected result (*)

1.It is working with a simple product but not working with configurable product
![stock-left](https://user-images.githubusercontent.com/25629588/74648556-f038e100-51a3-11ea-86d9-6f885b48440e.JPG)

2. It is not working with the configurable product where stock is less than 2
![stock-left-01](https://user-images.githubusercontent.com/25629588/74648658-1f4f5280-51a4-11ea-9af8-d0ca1e022856.JPG)

### Actual result (*)

1. In configurable product, if we have selected the size if it is less then 3 than it has to show quantity left

**Comment by surelockrich** [comment]
I have Explained in best simple way if you still find difficulties. I will share the video for better information.

Thank You

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26896-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26896-2-4-develop.instances.magento-community.engineering/admin_e393](https://i-26896-2-4-develop.instances.magento-community.engineering/admin_e393)
Login: `db94f4bb` Password: `6a20970a4858`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31593` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by surelockrich** [comment]
Hello team,

Can you inform me about this issue, How much time it will take to solve?

@krishprakash @magento-engcom-team  

Thank you

**Comment by deepaksnair** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @deepaksnair. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @deepaksnair, here is your [Magento instance](https://i-26896-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26896-2-4-develop.instances.magento-community.engineering/admin_5ac2](https://i-26896-2-4-develop.instances.magento-community.engineering/admin_5ac2)
Login: `6ad6edba` Password: `0a95a8ae52e7`
Instance will be terminated in up to 3 hours.

**Comment by surelockrich** [comment]
Hello Team,

Can you update me about this issue?

Thank You

**Comment by gigulinu** [comment]
Any update for this matter? Still exist in magento 2.3.5-p1

**Comment by robsoned** [comment]
Hey guys!
Is it going to be released only on magento 2.4.x or it will be also available in one of the magento 2.3.x versions. Thanks

**Comment by engcom-Hotel** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
This issue is fixed on MSI and it should be transferred to CE in the next minor release.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by surelockrich** [comment]
Hello,
I have test the same issue on 2.4.1 as well, more over i have seen website made on Magento 2 in which it doesn’t happen

Thanks & Regards

Sent from my iPhone
Please excuse typos and brevity

**Comment by paradigmecommerce** [comment]
Anyone got any resolution for the same. This issue is there in Magento 2.4.2 as well

**Comment by enyceedanny** [comment]
Same here. Showing 0 left for configurable products.

**Comment by surelockrich** [comment]
Hello Magento Team,

Is there any solution to this issue?

Regards,

SHAIKH SARFARAZ ALI

**Comment by spraxis** [comment]
Why is this closed? I'm still getting 0 left for configurable products on Magento 2.4.3-p1.

**Comment by surelockrich** [comment]
@spraxis @enyceedanny Is this issue is solved or should i Reopen this issue.
