### ISSUE TITLE
Saving an entit on Console Command generate a deadlock exception on url_rewrite table

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#26905]
### Preconditions (*)

1. Magento 2.3.3 on developer mode
2. Magento 2.3.4 on developer mode

### Steps to reproduce (*)
1. Create a new Console Command class like bellow
`class Test extends Command
{
    /**
     * @var CategoryFactory
     */
    private $categoryFactory;

    public function __construct(
        CategoryFactory $categoryFactory
    ) {
        $this->categoryFactory = $categoryFactory;

        parent::__construct();
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this->setName('testabc');
        parent::configure();
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->categoryFactory->create()
            ->setName('testabc')
            ->setUrlKey('testabc')
            ->save();
    }
}`
2. Run the command

### Expected result (*)
The category should be saved

### Actual result (*)
I get 3 error log

> [Magento\Framework\DB\Adapter\LockWaitException]                                                                                                                                                         
>   SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT  INTO `url_rewrite` (`redirect_type`,`is_autogenerated`,`metadata`,`description`,`store_  
>   id`,`entity_type`,`entity_id`,`request_path`,`target_path`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)

> [Zend_Db_Statement_Exception]                                                                                                                                                                            
>   SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT  INTO `url_rewrite` (`redirect_type`,`is_autogenerated`,`metadata`,`description`,`store_  
>   id`,`entity_type`,`entity_id`,`request_path`,`target_path`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)  
                                                        
>   [PDOException]                                                                               
>   SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

### Another case (*)
1. I tried with the App/State to set the area as adminhtml/frontend + emulate the areas.
1. I tried to save by using the resource model.

**Comment by vincent-le89** [comment]
Hi @alexmtch 

I tried on source code Magento 2.3.4 but it doesn't happen error like yours.
Try code:
1. File: app/code/Niteco/ChangeCategory/etc/di.xml
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Console\CommandListInterface">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="create_category" xsi:type="object">Niteco\ChangeCategory\Console\Command\Category</item>
            </argument>
        </arguments>
    </type>
</config>`
2. File: app/code/Niteco/ChangeCategory/Console/Command/Category.php
`<?php

namespace Niteco\ChangeCategory\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Catalog\Model\CategoryFactory;

/**
 * Class ChangeCategory
 * @package Niteco\ChangeCategory\Console\Command
 */
class Category extends Command
{
    /**
     *
     * @var CategoryFactory
     */
    private $categoryFactory;

    public function __construct(
        CategoryFactory $categoryFactory
    )
    {
        $this->categoryFactory = $categoryFactory;

        parent::__construct();
    }

    /**
     *
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this->setName('testabc');
        parent::configure();
    }

    /**
     *
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $url = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $url->get('\Magento\Store\Model\StoreManagerInterface');
        $mediaurl= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $state = $objectManager->get('\Magento\Framework\App\State');
        $state->setAreaCode('frontend');
/// Get Website ID
        $websiteId = $storeManager->getWebsite()->getWebsiteId();
        echo 'websiteId: '.$websiteId." ";

/// Get Store ID
        $store = $storeManager->getStore();
        $storeId = $store->getStoreId();
        echo 'storeId: '.$storeId." ";

/// Get Root Category ID
        $rootNodeId = $store->getRootCategoryId();
        echo 'rootNodeId: '.$rootNodeId." ";
/// Get Root Category
        $rootCat = $objectManager->get('Magento\Catalog\Model\Category');
        $cat_info = $rootCat->load($rootNodeId);

        $categorys=array('Levis-test00001'); // Category Names
        foreach($categorys as $cat)
        {

            $name=ucfirst($cat);
            $url=strtolower($cat);
            $cleanurl = trim(preg_replace('/ +/', '', preg_replace('/[^A-Za-z0-9 ]/', '', urldecode(html_entity_decode(strip_tags($url))))));
            $categoryFactory=$objectManager->get('\Magento\Catalog\Model\CategoryFactory');
/// Add a new sub category under root category
            $categoryTmp = $categoryFactory->create();
            $categoryTmp->setName($name);
            $categoryTmp->setIsActive(true);
            $categoryTmp->setUrlKey($cleanurl);
            $categoryTmp->setData('description', 'description');
            $categoryTmp->setParentId($rootCat->getId());
            $mediaAttribute = array ('image', 'small_image', 'thumbnail');
            $categoryTmp->setImage('/m2.png', $mediaAttribute, true, false);// Path pub/meida/catalog/category/m2.png
            $categoryTmp->setStoreId($storeId);
            $categoryTmp->setPath($rootCat->getPath());
            $categoryTmp->save();
        }
    }
}`
It create a new category normally.
![image](https://user-images.githubusercontent.com/49143689/74729708-78d48180-5277-11ea-9e36-5668d1d7fe2c.png)

**Comment by alexmtch** [comment]
Hello @vincent-le89 , you cannot reproduce because you doesn't follow the steps to reproduce.

It seems that when we use my process implementing the same as you but the CategoryFactory model is loaded by the dependency injection it won't works. Watch out this

```
/** @var CategoryFactory */
    private $categoryFactory;
    public function __construct(
        CategoryFactory $categoryFactory
    ) {
        $this->categoryFactory = $categoryFactory;

        parent::__construct();
    }

    /** {@inheritdoc} */
    protected function configure()
    {
        $this->setName('import:entity');
        parent::configure();
    }

    /** {@inheritdoc} */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // not works
        $this->categoryFactory->create()
        ->setName('testabc')
        ->setIsActive(true)
        ->setUrlKey('testabc')
        ->save();

        // works
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $categoryFactory = $objectManager->get(CategoryFactory::class);
        $categoryTmp = $categoryFactory->create();
        $categoryTmp->setName('toto');
        $categoryTmp->setIsActive(true);
        $categoryTmp->setUrlKey('toto');
        $categoryTmp->save();
    }
```

**Comment by vincent-le89** [comment]
Hi @alexmtch 

Sorry for reply late because I was busy with some personal works. I tried to use the dependency mechanism as you mentioned but the result wasn't different.
Refer my record: https://vimeo.com/393395840

This is my new code 
1. File: app/code/Niteco/ChangeCategory/Console/Command/Category.php
```
<?php

namespace Niteco\ChangeCategory\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Catalog\Model\CategoryFactory;

/**
 * Class Category
 * @package Niteco\ChangeCategory\Console\Command
 */
class Category extends Command
{
    /**
     * @var CategoryFactory
     */
    private $categoryFactory;

    /**
     * @var \Magento\Store\Model\StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var \Magento\Framework\App\State
     */
    protected $appState;

    /**
     * Category constructor.
     * @param \Magento\Framework\App\State $appState
     * @param CategoryFactory $categoryFactory
     * @param \Magento\Store\Model\StoreManagerInterface $storeManager
     */
    public function __construct(
        \Magento\Framework\App\State $appState,
        CategoryFactory $categoryFactory,
        \Magento\Store\Model\StoreManagerInterface $storeManager
    )
    {
        $this->categoryFactory = $categoryFactory;
        $this->storeManager = $storeManager;
        $this->appState = $appState;
        parent::__construct();
    }

    /**
     *
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this->setName('testabc');
        parent::configure();
    }

    /**
     *
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->appState->setAreaCode('frontend');
        // Get Website ID
        $websiteId = $this->storeManager->getWebsite()->getWebsiteId();
        echo 'websiteId: ' . $websiteId . " ";

        // Get Store ID
        $store = $this->storeManager->getStore();
        $storeId = $store->getStoreId();
        echo 'storeId: ' . $storeId . " ";

        // Get Root Category ID
        $rootNodeId = $store->getRootCategoryId();
        echo 'rootNodeId: ' . $rootNodeId . " ";
        // Get Root Category
        $rootCat = $this->categoryFactory->create();
        $rootCat->load($rootNodeId);

        $categorys = array('Levis-test00001'); // Category Names
        foreach ($categorys as $cat) {
            $name = ucfirst($cat);
            $url = strtolower($cat);
            $cleanurl = trim(preg_replace('/ +/', '', preg_replace('/[^A-Za-z0-9 ]/', '', urldecode(html_entity_decode(strip_tags($url))))));
            // Add a new sub category under root category
            $categoryTmp = $this->categoryFactory->create();
            $categoryTmp->setName($name);
            $categoryTmp->setIsActive(true);
            $categoryTmp->setUrlKey($cleanurl);
            $categoryTmp->setData('description', 'description');
            $categoryTmp->setParentId($rootCat->getId());
            $mediaAttribute = array('image', 'small_image', 'thumbnail');
            $categoryTmp->setImage('/m2.png', $mediaAttribute, true, false);// Path pub/meida/catalog/category/m2.png
            $categoryTmp->setStoreId($storeId);
            $categoryTmp->setPath($rootCat->getPath());
            $categoryTmp->save();
        }
    }
}
```
Please feel free to let me know if you have any questions.
Best Regards
Vincent Le

**Comment by vincent-le89** [comment]
This issue doesn't happen on Magento version 2.4-develop. So I temporarily close it and will open if it happens in the future
