### ISSUE TITLE
Cart rule coupon expiration date not getting saved in salesrule_coupon Magento 2.3.4

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26919]
It is working properly in 2.3.0, I guess some newer releases have affected this.

### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a cart rule with expiration date from backend.

### Expected result (*)

1. In salesrule_coupon table expiration_date should have value

### Actual result (*)

1. In salesrule_coupon table expiration_date has NULL value

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26919-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26919-2-4-develop.instances.magento-community.engineering/admin_cf7d](https://i-26919-2-4-develop.instances.magento-community.engineering/admin_cf7d)
Login: `7f00802b` Password: `cc7fd0692886`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Issue not produced.
See attached the screenshot:

![CouponCode_Date_Issue](https://user-images.githubusercontent.com/24711761/75215545-18819a80-57b7-11ea-85ae-a9a19fbc44b7.png)

If you have found this issue again, Please share the video and open the issue.

Thanks.

**Comment by kubertechnolabs** [comment]
@ajijshekh123 Its updated on Admin panel but on on **salesrule_coupon** this table. When we save the rule after update the expiration date it will date only in **salesrule**
