### ISSUE TITLE
Magento 2.3.4 order confirmations showing up as attachements to email clients

### ISSUE THREAD

**Issue by extremeskillz** [magento/magento2#26913]
Magento 2.3.4 (upgrade from 2.3.3)
Ubuntu 16.04LTS

Just did a fresh upgrade to 2.3.4 and the order confirmations from client order placed are not showing up at HTML anymore. They are showing up as attachements to emails. This impacts thunderbird and outlook email clients. Mobile email clients like seem to be fine. This needs to be address as its confusing clients when they reset passwords or sign up.  This issue seems to still be a carry over issue from magento2.3.3. All other aspects of the magento platform seem to be fine.

**Comment by devchris79** [comment]
Actually the fix for this should be in 2.3.5, here is the discussion:
#25076

and the commit:
6976aabdfdab91a9d06e412c2ed619538ed034b6

**Comment by gwharton** [comment]
In my opinion that commit is not the proper fix. All it does is remove the content disposition inline header. The correct fix should be to fix the zend framework bug which incorrectly utf-8 encodes the content disposition header if present. That is the real reason for the issue.

**Comment by extremeskillz** [comment]
I'm in agreement with gwharton. The should have been fixed by now with the 2.3.4 role out. I saw the tickets mentioning this but unless its fix in the stock code I don't consider that production.

**Comment by gwharton** [comment]
Magento had included the content disposition inline header since day 1 but was never an issue because zend framework 1 didnt have the bug. It only became a problem recently when magento moved to zend framework 2 which contains the bug. I dont know what other effects renoving the disposition inline header will have.

**Comment by extremeskillz** [comment]
The other thing to is I upgraded using composer, not the archive so the the temp fix mentioned is not in the same locations mentioned.  The original 2.2.2 install was from archive but all upgrades have been with the cli using composer. I'm using the Luma theme.

**Comment by manju-Cue** [comment]
I also faced this issue in Magento2.3.3. I was considering it will be fixed in new release magento2.3.4 but unfortunately, it's still there.
And, I'm also in agreement with gwharton that it should be fixed in Zend framework.

**Comment by Cahoo** [comment]
I've faced issue with =0A=0A=0A=0A=0A=0

![image](https://user-images.githubusercontent.com/17934645/75173299-563ede80-5737-11ea-82c7-8b6a9a042912.png)

**Comment by extremeskillz** [comment]
fixed in the latest releases.
