### ISSUE TITLE
Changes to _extend.less file do not take effect unless Static Files Cache is flushed in admin

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#2691]
As suggested in [this page](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html) from the Fronted Dev Guide, I set up Grunt to streamline the process of applying and debugging styles.

According to the last parapragh from that page:

"If you have LiveReload installed, run the grunt watch command, and the flow is even simpler:

After you customize the content of any .less file, changes are applied and the page reloads automatically. **No additional changes are required.**"

The page reloads automaticalley after saving the .less file, however the changes do not take effect unless I flush the Static Files Cache in admin and reload the page again.

**Comment by zanilee** [comment]
Hi, @lgarridoj!

There could be a problem with permissions while running `grunt watch`
Try to run `sudo grunt watch`

**Comment by MomotenkoNatalia** [comment]
@lgarridoj Any updates on this?

**Comment by jibrandlr** [comment]
@MomotenkoNatalia  The problem was LiveReload extension for Chrome had not been installed correctly. Now it is working ok
