### ISSUE TITLE
When database is on another server, the setup page is not being displayed.

### ISSUE THREAD

**Issue by leroy0211** [magento/magento2#2692]
My use case is when no database is installed on the webserver, the setup page is not being displayed. It's just blank. 
With the CLI I should be able to install magento, but haven't tested that yet.

**Comment by magenx** [comment]
ok page is blank, but what error you see exactly in the log?

**Comment by mazhalai** [comment]
@leroy0211 Please check permissions on your webserver. It does not matter if database is ready or not, setup should show up. Please check your browser's developer console for error message if any. Additionally, you can turn on developer mode for more information `bin/magento deploy:mode:set developer`

**Comment by daim2k5** [comment]
Hi @leroy0211 i close the issue because you didn't answered @mazhalai after 2 weeks. If you have still the error please feel free to reopen the issue.
