### ISSUE TITLE
endless loading in checkout page

### ISSUE THREAD

**Issue by cidarco** [magento/magento2#26922]
Hello there,
I do have a problem in my website which is, after filling all shipping informations and pressing "Update" button, the website stuck on an endless loading then customers could not place an order.

I have this issu for both payment methods. [https://www.cidar.co/checkout/#payment](url)

Also I have a problem with shipping page for the products that contains just one option (1 size, 1 color) the checkout page looking differnt, and there is no "Next" button on shipping information page. [https://www.cidar.co/checkout/#shipping](url)

How can I solve these issues ???

**Comment by krishprakash** [comment]
Hi @cidarco.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the[ Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
