### ISSUE TITLE
Magento 2.3.4 Product Export error

### ISSUE THREAD

**Issue by maniramav** [magento/magento2#26925]
### Preconditions (*)

When I select **Products** from **Entity Type** list, It should show **Entity Attributes** with Attribute Filters. It is not showing the list, when I click **Continue** , error is showing up as **

> Please correct the data sent value.

**

This issue started happening after I updated my Magento from 2.3.2 to 2.3.4

### Steps to reproduce (*)

![Annotation 2020-02-19 104828](https://user-images.githubusercontent.com/11077689/74829132-4030b880-5308-11ea-8230-834191b29e46.jpg)

### Expected result (*)

Export Product List

### Actual result (*)

![Annotation 2020-02-19 104900](https://user-images.githubusercontent.com/11077689/74829123-3ad36e00-5308-11ea-8b11-94402619917a.jpg)

**Comment by maniramav** [comment]
There is another tread similar to this, [https://github.com/magento/magento2/issues/17320#issuecomment-409862037](url)

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26925-2-4-develop.instances.magento-community.engineering/admin_408e](https://i-26925-2-4-develop.instances.magento-community.engineering/admin_408e)
Login: `59faf9d6` Password: `2e6f24cb87ff`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @maniramav ,
In Default Magento 2.4 Instance It is working fine. It is not displayed any of the errors when I have exported the Product attribute.
If you have upgraded the version it may be some configuration or database-related issue.
Please provide me a video so I can verify this issue.

Thanks.

**Comment by maniramav** [comment]
The issue have been fixed. The issue cased be attributed created during magento update. The particular attribute was created using SQL. That was causing the issue. Once I deleted those attribute and recreated in magento admin page fixed the issue.

**Comment by barryvdh** [comment]
@maniramav any idea how to find which attribute?

**Comment by Jeeva-Rathinam** [comment]
Anyone have solution?

**Comment by barryvdh** [comment]
Try to increase your error reporting, or look for attributes with models from packages that aren't installed anymore.

**Comment by Jeeva-Rathinam** [comment]
@barryvdh ANy help thanks https://github.com/magento/magento2/issues/15117

**Comment by yoritomoto** [comment]
I am having this issue on 2.3.5, can anyone translate the following into simple terms?
 
from @maniramav : _The issue have been fixed. The issue cased be attributed created during magento update. The particular attribute was created using SQL. That was causing the issue. Once I deleted those attribute and recreated in magento admin page fixed the issue._

**Comment by amirmdp** [comment]
Hi I have exactly same issue as soon as I select any option among Entity Type to export and click continue, the page returns with a notice "Please correct the data sent value." without showing any Entity Attributes. Please help I am new in magento.
environment: Plesk
PHP 7.4
Magento ver. 2.4.2

**Comment by amirmdp** [comment]
> That was causing the issue. Once I deleted those attribu

Hi I have exactly issue as soon as I select any option among Entity Type to export and click continue, the page returns with a notice "Please correct the data sent value." without showing any Entity Attributes. Please help I am new in magento.
environment: Plesk
PHP 7.4
Magento ver. 2.4.2
Can you please elaborate in detail the steps taken to resolve this issue?
