### ISSUE TITLE
Cannot ship product if user doesn't have permission to edit Source configurations

### ISSUE THREAD

**Issue by jsdupuis** [magento/magento2#26938]
### Preconditions (*)

1. Magento Open Source 2.3.3
2. Php 7.2
3. Using MSI (Multiple Source Inventory). Website has 1 stock made of 2 sources.

### Steps to reproduce (*)

1. Have a product with 2 sources and with quantity 1+ in both sources
2. Have a user/role that doesn't have permission to edit store configurations
2. Have that user open an order that contains this product and click "Ship"

### Expected result (*)

1. User goes to the Source Selection screen to decide from which source to deduct the product

### Actual result (*)

1. User get "Sorry you need permission to view this content" error message

The temporary solution is to give all your users all permissions under Stores --> Inventory, even though only Admins at higher level should see these settings.

**Comment by naydav** [comment]
This bug should be moved to
https://github.com/magento/inventory/issues

**Comment by engcom-Bravo** [comment]
Hello @jsdupuis  

Thank you for your report

This looks like a valid issue, but not for this repository. 
Please, open a similar issue for [MSI](https://github.com/magento/inventory/issues) repository

Thank you for your collaboration

**Comment by jsdupuis** [comment]
I'm not familiar with repositories. I just clicked on "Report an issue" link in the back end of Magento.

**Comment by engcom-Bravo** [comment]
Please, go to this repository https://github.com/magento/inventory/issues
Click **New Issue** - **Get started** in Bug report section

Thank you
