### ISSUE TITLE
\Magento\Persistent\Observer\SynchronizePersistentInfoObserver is subscribed on the absent event «controller_front_send_response_after», and so it is never called

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2693]
https://mage2.pro/t/287

See also https://github.com/magento/magento2/issues/2678

**Comment by ishakhsuvarov** [comment]
@dfediuk Thank you for reporting this issue.
We have created an internal ticket `MAGETWO-46922` to fix it.

**Comment by ishakhsuvarov** [comment]
@mage2pro Closing the ticket as the fix for the issue has been delivered to the `develop` branch in the scope of the linked commit.
Please reopen if you have any additional questions.
