### ISSUE TITLE
Admin Action log doesn't log before change value?

### ISSUE THREAD

**Issue by shashank9044** [magento/magento2#26943]
# Preconditions (*)
Magento 2.3.4 vanilla installation, we faced issue in Action Logging, Action Log only shows the result after change column not in before change column, before change column it shows N/A. 

The values in the column **Value Before Change**  always have **N/А** values regardless of whether this is the first change or the next, or when the default value is returned.

### Steps to reproduce (*)
1. Login to admin 
2. Stores ->configuration ->save any config entry from configuration page for example : 
    Customers->Password option -> Password Reset type protection ->select email  
3. Save the configuration.
4. Then Click System-> Under Action and log section ->click on Reports->Click latest save Action ->view 
5. Here you can see before change value is missing which shows N/A
 
### Expected result (*)
1. Expected is to show before change value as  After change value shown already .

### Actual result (*)

1.Actually before change value always shows showing N/A.
<img width="1560" alt="Screenshot 2020-02-20 at 13 51 27" src="https://user-images.githubusercontent.com/25247490/74935197-2666a280-53e8-11ea-91e3-a057995c4bee.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31717` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-26943-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26943-2-4-develop.instances.magento-community.engineering/admin_ea59](https://i-26943-2-4-develop.instances.magento-community.engineering/admin_ea59)
Login: `7c0e8d42` Password: `1345b57de2af`
Instance will be terminated in up to 3 hours.
