### ISSUE TITLE
"Add to Cart" button appear on category pages for "Out of Stock" products

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#26942]
### Preconditions (*)
1. Magento 2.3.4 CE

### Steps to reproduce (*)
1. Enable MSI.
2. Set configuration in admin panel Stores->Settings->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products = Yes
3. Add product to cart with maximum available qty.
4. Place order.
5. Flush cache.

### Expected result (*)
1. On category page fully sold product has status "Out of Stock" and "Add to Cart" button does not appear.
![category_after_process_order](https://user-images.githubusercontent.com/22025597/74935463-937a3800-53e8-11ea-8207-56e23a0ff521.png)

### Actual result (*)
1. On category page fully sold product has button "Add to Cart".
![category](https://user-images.githubusercontent.com/22025597/74934675-084c7280-53e7-11ea-81a2-35959620e2dc.png)

2. On product details page everything is fine. We can see "Out of Stock" status and "Add to Cart" button does not appear.
![pdp](https://user-images.githubusercontent.com/22025597/74934690-0f738080-53e7-11ea-85e2-59e79ae7cb38.png)

### Additional Information
Problem also exists in sections like "cross-sell", "up-sell" and "related" where product data is get from products collection. Product stock status comes from column "is_salable" of specified "inventory_stock_*" table. That table is populated during reindex process but it does not care of reservations.

On product details page problem does not exist because stock status is assigned in plugin Magento\InventoryCatalog\Plugin\CatalogInventory\Helper\Stock\AdaptAssignStatusToProductPlugin and it take care of reservations.

**Comment by naydav** [comment]
Potentially Index (Stock) could be stored in dedicated data storage not related to SourceItems(reservations) at all.

That's segregation between Read and Command which provide ability to scale Read and Write infrastructure independently.

Maybe make sense to create a separate module for cases when system is not supposed to be split.
But it should be approved by Product Owner.

**Comment by jaivikpatel** [comment]
I also facing the same problem in my Magento 2.3.4 system.
Any Patch or solution for that?

**Comment by sumeetmagento** [comment]
Anyone know how to solve this issue ?
facing same issue on Magento 2.3.5-p1

**Comment by eBusinessAtlantique** [comment]
Same issue on 2.3.6
I don't understand this behaviour. This is not convenient for the end-user.
How to deal with that ?
Thanks

**Comment by ashvinimarwal** [comment]
Same issue on 2.3.1
my findings
We are using 6 sources that are integrated from ERP. There is a mismatch in the inventory.

**Comment by jaivikpatel** [comment]
Please Re-Open this issue.
Why it is closed before resolved?
It's a very annoying issue.
please Magento team look into it to resolve.

**Comment by Becky1992j** [comment]
Update
My findings

_If the source has 10 qty and the total salable qty is zero_
then add to cart button will show on the category page but the product page will show out of stock

_If the source has 0 qty and the total salable qty is zero_
Out of stock button will show on both category and product page

**Comment by silversil** [comment]
This is a HUGE issu that could be fixed! I don't understand why it's been closed.
