### ISSUE TITLE
The date in To field can be set older than date in From field (Date filters) 

### ISSUE THREAD

**Issue by chalov-anton** [magento/magento2#26957]
### Preconditions (*)

Magento 2.4-develop
Created Order and Customer
 
### Steps to reproduce (*)
1. From admin Go to _Sales - Orders_
2. Click **Filters**, Set **Purchase Date** _from_, for example Todays date
3. Try to set, **Uploaded Date** or **Modification Date** _to_, for example, a day before
4. Click **Apply Filters**

### Expected result (*)
1. There should not be an ability to select a date **To** older than the date in **From**
Like for example in _Marketing -  Cart Price Rules_. The older date is dimmed 
![filters_in_catalog price rule](https://user-images.githubusercontent.com/45624059/71469961-60923a00-27d3-11ea-8d60-990f2bc600e2.gif)

### Actual result (*)
1. The Filter is Applied  
![filters_in_media_gal](https://user-images.githubusercontent.com/45624059/71469607-68051380-27d2-11ea-96d0-5caf6716663e.gif)

Additional info 
- this issue has transferred adobe-stock-integration repository as a Magento Core issue
- also reproducible on _Customers - All Customers_ page

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-26957-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26957-2-4-develop.instances.magento-community.engineering/admin_de32](https://i-26957-2-4-develop.instances.magento-community.engineering/admin_de32)
Login: `0c4a0165` Password: `f8576a2000ea`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31872` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sivaschenko** [comment]
@Usik2203 are you working on this issue?

**Comment by Usik2203** [comment]
@sivaschenko I unassigned myself from this issue.

**Comment by magento-engcom-team** [comment]
Hi @chalov-anton. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-31872` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
