### ISSUE TITLE
Magento 2.3.4 showing both Authorize.net Payments options as Depreciated

### ISSUE THREAD

**Issue by extremeskillz** [magento/magento2#26950]
### Description (*)
I just upgraded my magento 2.3.3 install to magento 2.3.4 and now we are seeing both Authorize.net options marked as depreciated. We are using the normal Authroize.net and not the Direct Post but what is going on with these plugins being depreciated? Authorize.net is the defacto standard for payments and would be nice to know what is the replacement since many of us use it as it part of the magento platform for as long as we been using the platform. 

The plugin isn't broken yet but I feel as I continue upgrading Magento we are going to loose capabilities that should have a replacement in future upgrades. Please advise. Not many are using the other payments options.

**Comment by duffner** [comment]
Authorize.Net exists as AcceptJS implementation, which supersedes all previous implementations.   Authorize.net is not gone. :). Don’t worry

**Comment by VigneshVenkatesan154** [comment]
@extremeskillz The Magento has deprecated the Authortize .net from 2.3.4 and completely removed in upcoming 2.4 release. So this is not valid and reproducible in Magento in 2.4-develop instance. Hence closing the issue.

![image](https://user-images.githubusercontent.com/60877551/83737059-22495280-a670-11ea-94ea-07f4fd75a3ef.png)
![image](https://user-images.githubusercontent.com/60877551/83737315-705e5600-a670-11ea-89cc-610522e2927a.png)
