### ISSUE TITLE
Queue_topology.xml queue declaration

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#26969]
### Summary (*)

There are a few issues about queue declaration in file `queue_topology.xml`.
First of all queues are side-effect of exchange and binding declaration. It is higly unintuituve. If we use [lib](https://github.com/php-amqplib/php-amqplib) laying underneath, we declare exchange, queue, and we bind them together, which is much more clear. It is worth noticing that queue, once declared can be bound to multiple exchanges, so it should be declared explicitly. It also limits queue configuration possibilities. You are not able to set arguments on queue level.

Secondly, taking first point into notice, if we have multiple bindings sharing same queue, which is declared with arguments, in the same file, we have to copy-paste around those arguments. If we won't do, it one definition of queue will be used, and arguments gets redeclared or even erased.
Merging definitions should be possible, but on module level.

Although, to start we following issues has to be fixed:
https://github.com/magento/magento2/pull/26966
https://github.com/magento/magento2/pull/26967

### Examples (*)

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/queue_topology.xsd">
    <exchange name="test.job" type="topic" connection="amqp">
        <binding id="TestCreateJob" topic="job.create" destinationType="queue"
                 destination="test_create_job">
            <arguments>
                <argument name="x-dead-letter-exchange" xsi:type="string">test.job.dead_letter</argument>
            </arguments>
        </binding>
    </exchange>

    <exchange name="test.job.dead_letter" type="topic" connection="amqp">
        <binding id="TestCreateJobDeadLetter" topic="#" destinationType="queue"
                 destination="test_job_dead_letter">
            <arguments>
                <argument name="x-dead-letter-exchange" xsi:type="string">test.job.retry</argument>
                <argument name="x-message-ttl" xsi:type="number">36000</argument>
            </arguments>
        </binding>
    </exchange>

    <exchange name="test.job.retry" type="topic" connection="amqp">
        <binding id="TestCreateJobRetry" topic="job.create" destinationType="queue"
                 destination="test_create_job">
            <arguments>
                <argument name="x-dead-letter-exchange" xsi:type="string">test.job.dead_letter</argument>
            </arguments>
        </binding>
    </exchange>
</config>
```
If we would remove arguments section for binding `TestCreateJobRetry`, queue `test_create_job` is created without any arguments and whole set up won't work at all.

This code works only if PRs attached to this issue will be fixed (I have patched it locally). For now arguments for queues are not used.

### Proposed solution

Queues should be declared explicitly, so arguments are clear. I don't maybe, they even should have their separate xml. Maybe they also should be matched with unique id. Binding element will use queue id, so binding are created.

**Comment by bartoszkubicki** [comment]
Yes I can confirm that this issue is reproducible in vanilla magento instance. Some related issues may be fixed.

**Comment by bartoszkubicki** [comment]
Yes I can confirm that this issue is reproducible in vanilla magento instance. Some related issues may be fixed.

**Comment by bartoszkubicki** [comment]
Still an issue

**Comment by engcom-Hotel** [comment]
Hi @bartoszkubicki ,

We have checked this issue on Magento version 2.4-develop but this is not reproducible. The issues mentioned in the ticket has been already merged with 2.4-develop. 

Please check the issue with the version 2.4-develop and let us know if you found any issue.

**Comment by epolish** [comment]
Hello @bartoszkubicki !
Just upgrade magento2 to 2.4 and recreate the queue topology via setup:upgrade (previous queues can be cleaned via rabbitmq management tool)

**Comment by engcom-Hotel** [comment]
Hi @bartoszkubicki,

We are still waiting for your reply. Please confirm if you are still facing the issue in 2.4.x version.

**Comment by bartoszkubicki** [comment]
@engcom-Hotel I didn't  have time recently to check it again. I am going to examine that in two next week, so you can reopen this one.

**Comment by engcom-Hotel** [comment]
Hi @bartoszkubicki,

Have you got chance to try to reproduce the issue in 2.4.x version?

Thanks

**Comment by bartoszkubicki** [comment]
Not yet, on my todo list

**Comment by engcom-Hotel** [comment]
Hello @bartoszkubicki,

We have waited for your response regarding reproducing the issue in the 2.4-develop branch for more than 14 days, but we are not able to get a response. Hence we are closing this issue for now. 

If you still facing the issue, either you can reopen it or create a new ticket.

Thanks
