### ISSUE TITLE
Backend Create Order: Configure Product Shows Two Stars For Required Custom Options

### ISSUE THREAD

**Issue by sprankhub** [magento/magento2#26962]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Create a product with a required custom option.
2. Start to create an order in the backend.
3. Click on the "Configure" link for the product with the required custom option.

### Expected result (*)
One red star is shown to indicate that the option is required:

![image](https://user-images.githubusercontent.com/930199/75030352-393ead00-54a4-11ea-9ac8-f000922411a6.png)

### Actual result (*)
Two red stars are shown:

![image](https://user-images.githubusercontent.com/930199/75030398-4fe50400-54a4-11ea-8934-4ae1a7cdbdd4.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26962-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26962-2-4-develop.instances.magento-community.engineering/admin_27f8](https://i-26962-2-4-develop.instances.magento-community.engineering/admin_27f8)
Login: `12892e79` Password: `0e6acb8ed2be`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26962-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26962-2-3-4.instances.magento-community.engineering/admin_a11d](https://i-26962-2-3-4.instances.magento-community.engineering/admin_a11d)
Login: `3825d7f9` Password: `45a0c864b1a8`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @sprankhub 
I checked this issue is reproducible at magento 2.3.4 but not reproducible at magento 2.4-develop instance . 
It seems it is already fixed at magento 2.4-develop instance.

**Comment by sprankhub** [comment]
You are right, @shikhamis11. As a reference, this has been fixed in https://github.com/magento/magento2/commit/91b8378752e5a29f8a8d99537dc1827e9e87bdfa.
