### ISSUE TITLE
Tests are failing when they are running at 00:00 

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#26975]
### Summary

- Created a new PR: https://github.com/magento/magento2/pull/26972
- PR didn't include any DB changes, so these test should not fail. 
- Tests are failing due to them running and comparing results between 2 different dates: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/26972/4b011829bf88bf9a4456d5585652a609/DatabaseCompare/ee-skip-sd-db-compare-report.html

### Examples

![image](https://user-images.githubusercontent.com/1058480/75082513-cbf14300-54c8-11ea-968d-727c5c839c8c.png)

### Proposed solution

- Don't use current date when adding items to the DB.

**Comment by lbajsarowicz** [comment]
@slavvka That's something I've mentioned plenty of times on Maintainers chat.

Low-hanging fruits are:
1. Set the custom date and time for the testing environment
1. Do not run tests less than an hour before midnight.

More complicated is to avoid using current time in tests (I assume it's part of Tests Best Practices - isn't it @Vinai ?), but then we'll have to rewrite most of the tests.

**Comment by engcom-Hotel** [comment]
Hello @dverkade,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @dverkade,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by dverkade** [comment]
This should be checked and not automatically be closed.

**Comment by dverkade** [comment]
The steps to reproduce are at the top / initial description of the ticket.
