### ISSUE TITLE
Guest cart assignToCustomer REST Api merges carts without checking for stock quantity / product eligibility.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26981]
**Additional information**
When the customer places the order, a cart item quantity error is thrown.
`"message": "The requested qty is not available",` and long calls trace, which is correct. 
The issue is: **The customer is forced to guess what cart item has not enough stock quantity or to update qty / delete the cart item accordingly.**

### Preconditions (*)
1. Magento 2.4
2. All steps are intended with REST api calls
3. Example: Product SKU-1 (or any SKU) with stock available qty: 1 and no backorders possible
4. Two products are created with qty 1

### Steps to reproduce (*)
1. Customer ID 1 logs in
2. Add products from preconditions to cart
3. Log out
4. Guest customer adds SKU-1 to cart
5. Guest customer logs in as Customer ID 1
6. Rest api PUT for merging guest is called (/V1/guest-carts/:cartId)
7. Carts are merged, SKU-1 total item quantity in cart is now 2, as per lines 2392 and 2393 in \Module_Quote\Model\Quote.php ($quoteItem->setQty($quoteItem->getQty() + $item->getQty());)

### Expected result (*)
1. When carts are merged, available stock qty for each product should be checked, according to the current stock / backorder configuration.
2. The sum of the 2 quantities should be set at the maximum available / eligible qty.
3. In the described case, the SKU-1 total item quantity should be 1.

### Actual result (*)
1. The sum of the 2 quantities does not take into consideration the current stock / backorder configuration.
2. In the described case, the SKU-1 total item quantity is 2.

When the customer places the order, a cart item quantity error is thrown.
`"message": "The requested qty is not available",`
 The customer is forced to guess what cart item has not enough stock quantity or to update qty / delete the cart item accordingly.

**Comment by AnemosGroup** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @AnemosGroup. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnemosGroup, here is your [Magento instance](https://i-26981-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26981-2-3-4.instances.magento-community.engineering/admin_7364](https://i-26981-2-3-4.instances.magento-community.engineering/admin_7364)
Login: `1ea907be` Password: `26cb559148dd`
Instance will be terminated in up to 3 hours.

**Comment by AnemosGroup** [comment]
@magento-engcom-team I confirm that I were able to reproduce the issue on vanilla Magento instance following steps to reproduce.

**Comment by engcom-Lima** [comment]
Hello @AnemosGroup  @sdzhepa
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!
