### ISSUE TITLE
admin downloadable type product js error "TypeError: scopeTitle.up(...).down(...) is undefined"

### ISSUE THREAD

**Issue by webkul** [magento/magento2#2698]
When we are trying to add links and samples in a particular store view then getting js error- "TypeError: scopeTitle.up(...).down(...) is undefined" at browser console .

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by anton-huz** [comment]
Dear @webkul, please fill free to comment if you still faced with issue. It would be handy if you point Magento version and a little bit more info about environment.

Currently issue not actual any more due to rework of Product edit page in Admin area. I close issue.
