### ISSUE TITLE
install magento2.0 sucessfully  local how to add new page in menu bar

### ISSUE THREAD

**Issue by karthik-bgdins** [magento/magento2#2699]
Hi:

I have installed magento2.0 local sucessfully. i cannot added new page in menu bar. how to fix the problem please help me.

**Comment by ahmadhattab** [comment]
try bin/magento setup:upgrade

**Comment by mazhalai** [comment]
@karthik-bgdins can you please be more specific about what you are trying to do?

**Comment by daim2k5** [comment]
Hi @karthik-bgdins  i close the issue because you didn't answered @mazhalai after 2 weeks. If you have still the error please feel free to reopen the issue.
