### ISSUE TITLE
Product bulk update is not working.even cron job is running as per magento standard.

### ISSUE THREAD

**Issue by santosh-ks153** [magento/magento2#27002]
### Preconditions (*)

1.  Magento 2.3.2
2.  Php 7.2
3.  Mysql 5.6

### Steps to reproduce (*)

1. Bulk products not updated.
2. The cron job is running properly as per Magento standards

### Expected result (*)

I want to update the product.

### Actual result (*)

![screenshot-elifeguard-cw920e8cvsqhnbxp mojostratus io-2020 02 25-14_48_31](https://user-images.githubusercontent.com/55832852/75232855-f0596200-57dd-11ea-9b9b-bfad7cca8512.png)

**Comment by GuiltyNL** [comment]
Could you try to disable Magento_Amqp and Magento_AmqpStore modules and after that add a new bulk job to the queue?

There are some reports that disabling these modules would solve the hanging jobs.

**Comment by santosh-ks153** [comment]
okay let me try this.

**Comment by santosh-ks153** [comment]
Magento_AmqpStore is not available in Magento 2.3.2.
and I did disable the Magento_Amqp but still not working.

**Comment by santosh-ks153** [comment]
also, I did this step with no luck.
https://magento.stackexchange.com/questions/281723/magento-2-bulk-actions-not-starting

Is it core bugs?

**Comment by devchris79** [comment]
Our site kept getting stuck cron jobs and high ram usage due to stuck processes, this appears to have been solved by adding the code below to env.php:

```
,
'cron_consumers_runner' => [
        'cron_run' => false,
        'max_messages' => 1000,
        'consumers' => [
            'async.operations.all'
        ]
    ] 
```

This does presume you are not using RabbitMQ though.

**Comment by santosh-ks153** [comment]
We did this step as well.

**Comment by devchris79** [comment]
It may also be worth checking you ram usage

**Comment by santosh-ks153** [comment]
I don`t think its ram usage issue but let me try with that.

**Comment by GuiltyNL** [comment]
I don't think it is a general bug, because bulk updates are working here. However, we are on 2.3.3

**Comment by santosh-ks153** [comment]
yes, that why I m asking it core bugs with 2.3.2?

**Comment by hostep** [comment]
It should also be working on Magento 2.3.2, I've tested this quite extensively.

@santosh-ks153: you'll probably need to do a bit of debugging, maybe this helps: https://github.com/magento/magento2/issues/23450#issuecomment-520134243

**Comment by santosh-ks153** [comment]
I did every possible solution available on Google with no luck.

**Comment by sudheers-kensium** [comment]
@santosh-ks153 run php bin/magento queue:consumers:start product_action_attribute.update

**Comment by sudheers-kensium** [comment]
Hi @santosh-ks153 ,

I am closing this issue. Feel free to reopen still you are facing issue.

Thanks

**Comment by VivekShingala** [comment]
Truncating cron_schedule table manually fixed the issue for me.
