### ISSUE TITLE
Label translation missing in product compare list

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#27006]
### Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)
1. Login as Customer
2 Add some products to the compare list
3. Go to "https://www.example.de/catalog/product_compare/index/"
4. Check if Labels on the left are getting translated

### Expected result (*)
Labels are getting translated.

![image](https://user-images.githubusercontent.com/16349349/75247168-9d79ad80-57d1-11ea-8de5-131905249755.png)

### Actual result (*)
Labels are not getting translated

![image](https://user-images.githubusercontent.com/16349349/75247220-b8e4b880-57d1-11ea-8647-294782158053.png)

**Comment by eduard13** [comment]
Hi @Eddcapone, thank you for opening this issue, however not sure that is a real issue, as soon as you are able to set different labels per stores for each attribute individually (check the below image).
![image](https://user-images.githubusercontent.com/15868188/75353655-6defa180-58b4-11ea-9051-3bdaddc5f031.png)
After doing this, we can see the configured label on Product page, Compare page, etc.
![image](https://user-images.githubusercontent.com/15868188/75354026-fa9a5f80-58b4-11ea-8054-aa8cd7c5a294.png)

Please let me know if you have any other questions.
Thank you.

**Comment by Eddcapone** [comment]
@eduard13 Hello, I was not aware of this. Where can I set this? If you look at the code I have changed, then you see that there is a ternary operator and if it lands in the else part, then it is also translated. I let you decide.

**Comment by eduard13** [comment]
@Eddcapone, you can set a separate label on the attribute configs.
1. Navigate to `Stores / Product [Attributes]`
2. Select the attribute (description in your case)
3. Open the `Manage Labels` tab
4. Set the labels for your available stores
![image](https://user-images.githubusercontent.com/15868188/75357965-d8a3db80-58ba-11ea-9725-d1fe2f5b79c7.png)

**Comment by eduard13** [comment]
Closing as being a non issue.
Thank you.

**Comment by Eddcapone** [comment]
But does this mean, that I will have to manually translate it myself for each store view? It totally looks like an issue for me.
