### ISSUE TITLE
How to contribute a fix?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#27003]
I found a mini bug in **\vendor\magento\module-catalog\view\frontend\templates\product\compare\list.phtml**, which is easy to fix.

So I created a fork and cloned it. Then I executed **composer update**, but there are only a few folders in **vendor/magento**

How am I supposed to fix this bug if the files are not even there?

**Comment by hostep** [comment]
@Eddcapone: Magento's git repository uses a different structure, most of Magento's code is in one large git repository as it's easier to manage this way probably.

You can find the file you are searching for in `app/code/Magento/Catalog/view/frontend/templates/product/compare/list.phtml`

You can associate `vendor/magento/module-catalog` in a real project with `app/code/Magento/Catalog` in the git repo (the same thing counts for most of the other Magento modules).

Hope this helps and thanks for trying to contribute!

**Comment by Eddcapone** [comment]
I see, thank you!
