### ISSUE TITLE
Magento CLI setup:config:set not accepting hyphens or dash "-"

### ISSUE THREAD

**Issue by smaadjahangir** [magento/magento2#2700]
Below is an example:

@>  magento setup:config:set --http-cache-hosts="123-abc.com"
Invalid http cache hosts '123-abc.com'
[InvalidArgumentException]
Parameter validation failed

Regards,
Maad

**Comment by mazhalai** [comment]
@smaadjahangir Thank you for reporting, we have created ticket MAGETWO-46858 to fix it.

**Comment by smaadjahangir** [comment]
@mazhalai How can i follow your mentioned ticket? Can you provide me the link to access it.

**Comment by mazhalai** [comment]
@smaadjahangir It is for internal purposes only.

**Comment by mazhalai** [comment]
@smaadjahangir A fix has been merged. Please try on the `develop` branch.
Closing this issue since it has been resolved. Please feel free to open a new one in case you run into any more issues.
