### ISSUE TITLE
Invoice pdf year in date increasing on Magento 2.3.4

### ISSUE THREAD

**Issue by will-wright1** [magento/magento2#27008]
The date on the invoice pdf increases year by year every time you create a new invoice.

### Preconditions (*)
1. Magento 2.3.4
2. Both Nginx and Apache Servers

### Steps to reproduce (*)
1. Create an order.
2. Create a second order.
3. Sales > Invoices > View Invoice for order 1 > Print 
4. Sales > Invoices > View Invoice for order 2 > Print 
5. The year on the date of the two invoice pdf's will be different.

### Expected result (*)
1. The year on the date is the year of the invoice

### Actual result (*)
1. When you print an invoice the year on the date increases every time you create a new invoice

![Screenshot 2020-02-25 at 12 37 01](https://user-images.githubusercontent.com/22942523/75248486-2988d680-57cc-11ea-84ea-7b6d84610696.png)

![Screenshot 2020-02-25 at 12 41 47](https://user-images.githubusercontent.com/22942523/75248511-35749880-57cc-11ea-8327-e57464e52573.png)

**Comment by webamondo** [comment]
I think this has maybe been fixed in 2.4 via this PR https://github.com/magento/magento2/pull/26701

**Comment by krishprakash** [comment]
Hi @webamondo. Yes issue is fixed in 2.4.
It will reflect in next 2.4 release.
Thanks!!

**Comment by webamondo** [comment]
@krishprakash does it not need fixing in 2.3?

**Comment by krishprakash** [comment]
Hi @webamondo. You can review the #26701 PR for your fixes.
It will be fixed on 2.4 as it not released yet.
Thank you for your feedback !!
