### ISSUE TITLE
Quote Item class incorrectly extending VersionControl AbstractDb

### ISSUE THREAD

**Issue by ghost** [magento/magento2#27011]
The class `vendor/magento/module-quote/Model/ResourceModel/Quote/Item.php` is seemingly incorrectly extending `Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb` and it should extend `Magento\Framework\Model\ResourceModel\Db\AbstractDb`

The VersionControl AbstractDb relies on snapshots and fails to assert that an object has been modified when it cannot find a snapshot.

**Comment by engcom-Echo** [comment]
Hi Ghost,

Can you please specify the version of Magento on which this issue is reported.

Thanks

**Comment by engcom-Hotel** [comment]
Hi Ghost,

It seems that your issue has been resolved. Since we have not received any comment from your side after more than 14 days, we are closing this issue.
