### ISSUE TITLE
Upgrading from Magento 2.2.4 to 2.3.4 paypal credit card problem

### ISSUE THREAD

**Issue by rakeshdonga** [magento/magento2#27022]
### Preconditions (*)

1. Magento CE 2.3.4
2.  php version 7.1.33

### Steps to reproduce (*)

1. Product add in cart
2. and customer place order via paypal creditcard and redirect to cart page and nothing any error showing in logs
3. i have also tested in magento default theme in vanila but still same issue

### Expected result (*)

1. Before old version it's working fine in magento 2.2.4
2.  and successful order placed

### Actual result (*)

1.
![paypal-issue](https://user-images.githubusercontent.com/26105920/75325854-8f925e00-589f-11ea-907a-21db34a74aec.png)
2. Redirect to cart page after all paypal credit card details filled and nothing any error showing

**Comment by rakeshdonga** [comment]
any update?

**Comment by rakeshdonga** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rakeshdonga. Thank you for your request. I'm working on Magento 2.4-develop instance for you
