### ISSUE TITLE
Paypalflow pro: Generic processor error: 10481-PaymentAction of Authorization is not allowed with Unilateral and Non-Credentialed authentication

### ISSUE THREAD

**Issue by pilardo** [magento/magento2#27028]
### Preconditions (*)

1. 2.3.3
2. 

### Steps to reproduce (*)

1. create  paypalflow pro sanbox account
2. set configurations in admin
3. test order 

### Expected result (*)

1. complete order

### Actual result (*)

1. Generic processor error: 10481-PaymentAction of Authorization is not allowed with Unilateral and Non-Credentialed authentication
2. 'url' => 'https://pilot-payflowpro.paypal.com/transaction',
  'DoExpressCheckoutPayment' => 
  array (
    'TENDER' => 'P',
    'TOKEN' => 'EC-5NF28122MW790934W',
    'PAYERID' => 'QQQFSTGM458GN',
    'AMT' => '110.24',
    'CURRENCY' => 'USD',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'NOTIFYURL' => 'https://someurl.com/paypal/ipn/',
    'FREIGHTAMT' => '0.00',
    'TAXAMT' => '10.25',
    'L_NAME0' => 'Marble Table Lamp ',
    'L_QTY0' => 1,
    'L_COST0' => '99.99',
    'BUSINESS' => 'test',
    'EMAIL' => 'test@test.com',
    'FIRSTNAME' => 'test',
    'LASTNAME' => 'test',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRY' => 'US',
    'STATE' => 'CA',
    'CITY' => 'Glendora',
    'STREET' => '510 S Grand Ave Ste 306',
    'ZIP' => '91741-4207',
    'PHONENUM' => '123456789',
    'SHIPTOCOUNTRY' => 'US',
    'SHIPTOSTATE' => 'CA',
    'SHIPTOCITY' => 'Glendora',
    'SHIPTOSTREET' => '510 S Grand Ave Ste 306',
    'SHIPTOZIP' => '91741-4207',
    'SHIPTOPHONENUM' => '123456789',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'test test',
    'ADDROVERRIDE' => 1,
    'TRXTYPE' => 'A',
    'ACTION' => 'D',
    'PARTNER' => '****',
    'USER' => '****',
    'VENDOR' => '****',
    'PWD' => '****',
  ),
  'response' => 
  array (
    'RESULT' => '1000',
    'PNREF' => 'B9PP0D1432F9',
    'RESPMSG' => 'Generic processor error: 10481-PaymentAction of Authorization is not allowed with Unilateral and Non-Credentialed authentication.',
    'AVSADDR' => 'Y',
    'AVSZIP' => 'Y',
  ),
) [] []

**Comment by pilardo** [comment]
@magento give me 2.3.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pilardo. Thank you for your request. I'm working on Magento 2.3.3-develop instance for you

**Comment by pilardo** [comment]
closing this issue. It was the zip code that generates the warning.
