### ISSUE TITLE
nau suckchs fail or darectary

### ISSUE THREAD

**Issue by r32rf** [magento/magento2#27023]
hello i ain dire need af help for you to me again i have made symlink in high power superduperfast lunix server 4 magneto 2 website and now new upload with da new version not work i get error pub/static/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262/version1582635262): No such file or directory
 pls help i no have clue what to do help magneto 2 needs help 

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Marfjeh** [comment]
Found your problem, Don't use this absolute overengineerd php disaster.

**Comment by r32rf** [comment]
@Marfjeh pls do a help for me why directory not exist hyper super lunix server has full power mode on and i not of a knowing do have a idea do I have? why path so ugly i need to have do a know of why path ugly??? 
magento 2 needs help
