### ISSUE TITLE
infinite loop adminhtml The page isn’t redirecting properly

### ISSUE THREAD

**Issue by iambaljitdhanoa** [magento/magento2#27045]
Hello

When we click on admin custom extension menu redirect not properly
Page redirected to
bareportsystem/report/settlementreport/key/0ce43850c077ac628054fc1dac193438ab83159a817eebe2356f74e334cd1f44/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard

Please let me know how can fix this problem

**Comment by eduard13** [comment]
Hi @iambaljitdhanoa, could you please update the issue description, it will help us to reproduce the issue. You may check the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). Also, could you please make sure you get this issue using the latest Magento version?

Thank you.

**Comment by eduard13** [comment]
Hi @iambaljitdhanoa, please feel free to reopen the issue with an updated description.
Thank you.
