### ISSUE TITLE
Downgrade Magento from 2.3.4 to 2.3.3

### ISSUE THREAD

**Issue by AjayKrP** [magento/magento2#27046]
### Summary (*)
Hi, I've upgraded Magento from 2.3.3 to 2.3.4. On doing that I was not able to edit the CMS page in the admin panel. So I decided to revert it back to 2.3.3. But on downgrading to 2.3.3 it was throwing error like LayoutProcessor doesn't exist and every page is breaking. So how can I revert it back to 2.3.3 properly?

### Proposed solution
I followed this [ https://magento.stackexchange.com/questions/120098/magento2-how-to-downgrade-properly](https://magento.stackexchange.com/questions/120098/magento2-how-to-downgrade-properly) for downgrading. But in the solution, it says that you have to copy your older database again. But I don't have a copy of the older database and I have uploaded thousands of products on the 2.3.4 version platform. I don't want to lose these products. So please help me to downgrade.

**Comment by dmytro-ch** [comment]
Hello @AjayKrP, the GitHub issue tracker is intended for Magento Core issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.

Thank you!
