### ISSUE TITLE
"We can not created empty shipment" during creation of the Shipment and Invoice for payment which does not support partial capture.

### ISSUE THREAD

**Issue by ant-workaholic** [magento/magento2#27042]
### Preconditions (*)
1. Use Payment method with <can_capture_partial>0</can_capture_partial> option. The payment method should not have an ability to perform partial capture.
2. Specify payment action  as (authorize).
2. Place order with the payment.

### Steps to reproduce (*)
1. Navigate to Sales -> Operations -> Orders and choose the placed order.
2. Click on "Invoice" link.
3. On the "New Invoice" page, under shipping information choose "Create Shipment" by clicking on checkbox.

![shipment](https://user-images.githubusercontent.com/5689348/75375990-eae04280-58d7-11ea-8611-1e47aca54d22.jpg)

4. Then click "Submit Invoice"

### Expected result (*)

1. Page reloaded with success message.
2. Invoice and shipment created.

### Actual result (*)

1. Page reloaded with error message message. 
 
![shipment_error](https://user-images.githubusercontent.com/5689348/75376405-a99c6280-58d8-11ea-8df6-9331300c54cd.jpg)

I found that the main reason of the issue is that in the template 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/templates/order/invoice/create/items/renderer/default.phtml#L21 in the else statement input element was replaced with just value and the data doesn't trasfer to the controller. 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Save.php#L102

I propose to add a hidden field to the template https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/templates/order/invoice/create/items/renderer/default.phtml#L21

`        
<input type="hidden"
               name="invoice[items][<?= (int) $_item->getOrderItemId() ?>]"
               value="<?= (int) $_item->getQty() ?>"/>
`

The issue reproducable for Community and Commerce Edition.

**Comment by vincent-le89** [comment]
Hi @ant-workaholic 
I can't reproduce your issue on Magento ver 2.4-develop. Maybe it was fixed.
Please take a look at my record:https://vimeo.com/394118636

**Comment by ant-workaholic** [comment]
> Hi @ant-workaholic
> I can't reproduce your issue on Magento ver 2.4-develop. Maybe it was fixed.
> Please take a look at my record:https://youtu.be/XDpEMKykomk

Could you make sure that shipment is exists ? Please verify also for guest user. For real customer I got the same success message but my shipment wasn't created, but for not logged in user I got error. I tested on magento 2.3 on my custom payment but I am pretty sure that this is Magento issue. Thank you.

**Comment by ant-workaholic** [comment]
@vincent-le89  Please, make sure that the issue is not reproducable. Verify that the shipment was created. Because for me the shipment was not created even in case of success message.

**Comment by ant-workaholic** [comment]
@vincent-le89  Yes, it seems it was fixed in 2.4-develop but not in "2.3.3". So, yes, the issue could be closed.
