### ISSUE TITLE
Product Page Custom Options are not sorted by title in the admin area.  Version 2.3.2

### ISSUE THREAD

**Issue by alimurtaza026** [magento/magento2#27055]
I was using Magento 1 for my store. The custom options are in sorted format. I can edit them easily. But, In Magento 2 custom options are not in sorted format in admin area. In customer side, the code was provided. We just uncommented the provided code and options are displaying in sorted format to customers.  But in back-end  these options are not sorted.
They should be in sorted in Magento 2 as it was in Magento 1 
I do not want to do this manually. 
See image below, 
<img width="1436" alt="Screenshot 2020-02-27 at 9 01 38 PM" src="https://user-images.githubusercontent.com/18608625/75461306-68718480-59a4-11ea-80bb-5b59812abb19.png">

These options should be in sorted order whenever I want to edit them automatically managed by magento. 

### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
1. Create a Configurable product 
2. Expand Customizable Options and Add Option with Title - _Title_ Type - _Checkbox_
3.  Add two values. First value with Title - _z_ , second value with Title - _a_
4. Save the Product
5. Open the products Customizable options and verify if the values are sorted by name

### Expected result (*)
The values are sorted by name, like in Magento 1. Can not be sorted via drag and drop
![mage1](https://user-images.githubusercontent.com/51680745/75983629-87669e00-5ef1-11ea-8d8f-fee46307f13c.png)

### Actual result (*)
The values are not sorted by name. But could be sorted via drag and drop
![mage2](https://user-images.githubusercontent.com/51680745/75983639-8afa2500-5ef1-11ea-8684-2949db01d27b.png)

**Comment by engcom-Bravo** [comment]
@sdzhepa 
I have added the description and screenshots. Can you please move this issue to the **feature request** repository?

Thank you in advance
