### ISSUE TITLE
install extension in M2.3.3(windows)

### ISSUE THREAD

**Issue by LiangCyu1990** [magento/magento2#27052]
I have installed in Magento 2.3.3  since then I am not able to install any extension. I am keep getting an error message that Check Component Dependency.
Please help me.
![issues](https://user-images.githubusercontent.com/60872168/75438485-ff354580-5992-11ea-8043-6c8c0fd4f003.png)

**Comment by GuiltyNL** [comment]
This is a file permission issue. I suspect your permissions are not correct in the folders.

**Comment by LiangCyu1990** [comment]
Thanks for reply.
I want exactly your answer. I think window 10 don't have permission problem.
Please help me.

**Comment by GuiltyNL** [comment]
It is generally a bad idea to run PHP sites on a Windows server, the PHP performance on Windows is very poor compared to a Linux machine.

But please double check this one:

https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html

**Comment by LiangCyu1990** [comment]
Thanks for the reply.
issue isn't fix.
