### ISSUE TITLE
BUG: Single EAV attribute update results in multiple scope-specific entries

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27065]
### Preconditions (*)
1. Magento 2.4-develop
1. Requests performed with REST API

### Steps to reproduce (*)
1. Create Category
1. Create the `Second Store`
1. REST: Send a request to update `url_key` for `Second Store`
1. Verify contents of `catalog_category_entity_{type}`

### Expected result (*)
1. Single entry in `catalog_category_entity_varchar` should be for `Second Store`

### Actual result (*)
1. Scope-specific values are created in `catalog_category_entity_varchar` (and in others):
  * `url_key`
  * `url_path`
  * `name`
  * `default_sort_by`

### Comments

Skipped API Functional Test was provided as a part of #27035

**Comment by lbajsarowicz** [comment]
Can you verify if #26484 resolved the issue?

**Comment by engcom-Bravo** [comment]
Hello @lbajsarowicz 
Can you please provide an example of a request changing the store url?

Thank you in advance
