### ISSUE TITLE
Tax calculation 19% = 16%

### ISSUE THREAD

**Issue by CooperDevon** [magento/magento2#27060]
I have some trouble with Magento CE 2.3.3
Magento calculates the tax completely wrong. I added 19% (Germany) to the tax class and having products show the prices including tax.

But at the cart and checkout Magento displays the including Tax not with the correct 19% value, it displays the Tax with only 16%.

Tried on 2 Magento installations (2.3.3) one which was previously updated from another version and one fresh install with no extensions installed.

In both cases only the vat for 16% is displayed. There is only 1 entry in Tax Zone for Germany (19%) no other zones.  

Magento CE 2.3.3
PHP 7.3.15

**Comment by AnnaShepa** [comment]
@CooperDevon thank you for the report. Please check your configuration and country, selected on checkout, additionally you can try to create order via API to check calculations on every step (after billing address filling, after shipping address filling and order placing). I have a lot of german shops and never got such issue.
