### ISSUE TITLE
In cart page, the shipping method label and calculation are happening before choosing the shipping method in checkout, Is there a way to fix this issue 

### ISSUE THREAD

**Issue by saranaltius** [magento/magento2#27069]

**Comment by krishprakash** [comment]
Hi @saranaltius. 
Could you please provide more details about how we can reproduce this issue on the clear Magento instance? 
Thank you!!

**Comment by saranaltius** [comment]
Hi,

Below I have attached the screenshot where issue is occurring

[image: cart_newone.PNG]

choosing shipping method is display in the checkout page only, before that
shipping method is showing in cart page and it's get affected in total, If
in some case if shipping method has value it's get added to order total.
Can I know is there any way to fix this issue?

**Comment by krishprakash** [comment]
Hi @saranaltius. 
Can not reproduce the issue on latest magento instance
Also GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the[ Community Forums](https://community.magento.com/) or the [Magento Stack Exchange site](https://magento.stackexchange.com/) for advice or general discussion about this.
Thank You.
