### ISSUE TITLE
Unable to redirect to external domain in action execute()

### ISSUE THREAD

**Issue by sethsnel** [magento/magento2#27067]
### Preconditions (*)
1. Magento ver. 2.3.4
2. Bitnami deploy on Azure environment

### Steps to reproduce (*)

1. Custom Controller/Action in module
2. return _redirectUrl() with external domain in execute() function (in my case a https:// domain)
3. Have enabled secret admin keys (when this is disabled, the redirect functions properly)

### Expected result (*)

1. Redirect to external domain

### Actual result (*)

1. You get redirected to admin dashboard instead of the provided external domain.

I need to be able to redirect the user to an external domain for a Magento 2 module I'm building.

I've tried to do this in two ways. In My class I have:

```
use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\Controller\Result\RedirectFactory;

class Link extends Action implements HttpGetActionInterface
{
    protected $resultRedirectFactory;

    public function __construct(
        Context $context,
        RedirectFactory $resultRedirectFactory
    ) {
        parent::__construct($context);

        $this->resultRedirectFactory = $resultRedirectFactory;
    }

    public function execute()
    {
        //return $this->_redirectUrl('https://app.easyads.eu/link/magento?');
        $resultRedirect = $this->resultRedirectFactory->create();
        $redirectLink = 'https://example.com/link/magento?'; 
        $resultRedirect->setUrl($redirectLink);
        return $resultRedirect;
    }
}
```
As you can see I've both tried the ```_redirectUrl``` function on the base Action. As well as trying to redirect with ```RedirectFactory```. Both ways work perfect when I have disabled secret key. (Stores -> Configuration -> Advanced -> Admin -> Security -> Add secret keys to urls)

This might be an awkward bug, or I'm overlooking something.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31996` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by singhvivek64** [comment]
Hi i am working on this issue

**Comment by sethsnel** [comment]
Who is working on the issue now? @singhvivek64 or @nirmalraval18 ?
Can I assist in anyway?
It is no problem for me to modify magento core code and run setup:di:compile if needed for testing.

**Comment by Rus0** [comment]
@sethsnel is this a frontend controller?? If it is you should change:

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;

for:

use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;

And only extend to Action:
class Link extends Action

**Comment by sethsnel** [comment]
@Rus0 Sorry for my late response. But I'm doing a backend (admin) redirect action. So not frontend. My action redirects from an admin to page to an external domain.
