### ISSUE TITLE
Discount amount is zero when using catalog price rules

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#27076]
If you discount a product using catalog price rules, the discount amount will always be zero on an order since it only uses "special_price" attribute to calculate the discount.

This is misleading and bad user experience.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Discount a product using catalog price rules
2. Place an order with discounted products
3. View order

### Expected result (*)

Row discounts should show the amount of the discount, same as when using special_price.

### Actual result (*)

Discount amount is always zero.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27076-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27076-2-4-develop.instances.magento-community.engineering/admin_f094](https://i-27076-2-4-develop.instances.magento-community.engineering/admin_f094)
Login: `9a1b6f96` Password: `26d039873a36`
Instance will be terminated in up to 3 hours.

**Comment by vishvesshah** [comment]
@magento I am working on it

**Comment by vishvesshah** [comment]
@Zyles , This is native behaviour of Magento. 

Please review the below screenshots. Both having the zero as discount, Discount prices will only appear with the Cart Price Rules. 

- Order with catalog Special prices

![Screenshot from 2020-02-29 14-48-53](https://user-images.githubusercontent.com/13507925/75604794-a1c00680-5b02-11ea-9c3f-379576f96eaf.png)

- Order with catalog price rule

![Screenshot from 2020-02-29 14-48-24](https://user-images.githubusercontent.com/13507925/75604796-a2f13380-5b02-11ea-891c-79e02613be30.png)

**Comment by Zyles** [comment]
Yes this is native Magento behavior, also known as bad design.

Why would the discount amount be zero, when there is a discount?

**Comment by krishprakash** [comment]
@Zyles , We can not consider this as an issue.
As as per catalog price rule discount should calculate directly on product/category.
You need to add cart price rule for same
This is native magento behavior.
Thanks!!
