### ISSUE TITLE
In checkout page while I'm switching the address the shipping method is not get updated Is there any way to fix the issue ?

### ISSUE THREAD

**Issue by saranaltius** [magento/magento2#27070]

**Comment by krishprakash** [comment]
Hi @saranaltius.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange site](https://magento.stackexchange.com/) for advice or general discussion about this.
Thank You.
