### ISSUE TITLE
Report Value doesn't matching -  "Year-To-Date Starts"

### ISSUE THREAD

**Issue by vishvesshah** [magento/magento2#27086]
Report Value doesn't matching -  "Year-To-Date Starts".

### Preconditions (*)

1. Magento 2.3.4,2.3.3

### Steps to reproduce (*)

1. Login to Adminpanel.
2. Go to Stores >> Configuration >> General >> Reports
3. From Dashboard tab >> Select "Year-To-Date Starts".

### Expected result (*)

1. It should select the correct value, if I have selected month 12 then it should select 12 only.

### Actual result (*)

1.  If you have selected 12  then it will take the month "1", if 11 then it will select month 12

Please see the screenshot below. You will be able to see the issue with enabling the developer toolbar from browser only.

![image](https://user-images.githubusercontent.com/13507925/75602236-43d2f500-5ae9-11ea-9405-31f34fa38d6f.png)

**Comment by Priya-V-Panchal** [comment]
Hi

@magento please give me 2.4-develop instance.

Thanks

**Comment by Priya-V-Panchal** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Priya-V-Panchal. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Priya-V-Panchal, here is your [Magento instance](https://i-27086-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27086-2-4-develop.instances.magento-community.engineering/admin_2358](https://i-27086-2-4-develop.instances.magento-community.engineering/admin_2358)
Login: `782f09ab` Password: `b5909a680f3f`
Instance will be terminated in up to 3 hours.

**Comment by samikshakrish** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish, here is your [Magento instance](https://i-27086-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27086-2-4-develop.instances.magento-community.engineering/admin_86fe](https://i-27086-2-4-develop.instances.magento-community.engineering/admin_86fe)
Login: `d073e204` Password: `cdb56e4d4d4c`
Instance will be terminated in up to 3 hours.

**Comment by samikshakrish** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish, here is your [Magento instance](https://i-27086-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27086-2-4-develop.instances.magento-community.engineering/admin_13cd](https://i-27086-2-4-develop.instances.magento-community.engineering/admin_13cd)
Login: `62e1d8fe` Password: `bb111f3785d3`
Instance will be terminated in up to 3 hours.

**Comment by samikshakrish** [comment]
Verified the issue  on latest instance .

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32028` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vishvesshah. Thank you for your report. 
The issue has been fixed in magento/magento2#27088 by @Priya-V-Panchal in 2.4-develop branch
Related commit(s):
 - [d03d8e1e2a705e8677e680f01f0e04e899daa305](https://github.com/magento/magento2/commit/d03d8e1e2a705e8677e680f01f0e04e899daa305)
 - [2ec8bf5d59cc858979e83d3786b7cb7ee563ad1b](https://github.com/magento/magento2/commit/2ec8bf5d59cc858979e83d3786b7cb7ee563ad1b)
 - [2410cbb760e1e88fa5c0681fa35baaf3686dd64a](https://github.com/magento/magento2/commit/2410cbb760e1e88fa5c0681fa35baaf3686dd64a)
 - [a2a865c499ba8eed3c2ea24975d3c8f4a037d475](https://github.com/magento/magento2/commit/a2a865c499ba8eed3c2ea24975d3c8f4a037d475)

The fix will be available with the upcoming 2.4.0 release.
