### ISSUE TITLE
quote_address.shipping_discount_amount does not get converted to current currency

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2708]
## Explanation of issue

When a store is configured to use a different currency than the **Base Currency** and a discount is applied to the shipping, the `quote_address.shipping_discount_amount` field will _not_ be multiplied by the currency conversion rate, even though it should be.
## Steps to reproduce issue
1. Install Magento CE 2.0.0 with sample data.
2. Configure the store to use a non-USD currency. Something like this:
   ![configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/129031/11790824/51d775ec-a263-11e5-970d-b3fbda6044f0.png)
3. Go to **Stores > Currency Rates** and ensure that conversion rates have been imported for your selected rate.
4. Setup a "10% off" shopping cart price rule. Configure the rule to apply discount to shipping amount.
5. Ensure that a shipping method (like flat rate) is configured.
6. On the frontend, add a product to cart. 
7. In the "Estimate Shipping and Tax" section of the cart, enter a country/region/postal code. When a shipping method is selected, the cart total should update.
8. Apply the 10% off coupon your created earlier.
9. Look at the `quote_address.shipping_discount_amount` and `quote_address.base_shipping_discount_amount` fields for your current quote. They will be the same value, even though the `shipping_discount_amount` should be multiplied times the currency conversion ratio.

You should be able to reproduce this issue by following the steps listed above, but if you are not, let me know and I can provide more exact steps. I noticed that this behavior is inconsistent. It happens on the cart and when you place an order, but on the final step of the checkout, the price is different because the `shipping_discount_amount` field is being multiplied by the conversion rate.

**Comment by ishakhsuvarov** [comment]
@erikhansen Thank you for reporting this.
We have created an internal ticket `MAGETWO-46924` to investigate and fix the problem.

**Comment by erikhansen** [comment]
@ishakhsuvarov Thanks.

**Comment by SerhiyShkolyarenko** [comment]
@erikhansen I guess you configure "Apply to Shipping Amount" = "Yes" on step 4.

**Comment by erikhansen** [comment]
@SerhiyShkolyarenko Yes, that is what I meant. I updated the issue description accordingly. Thanks.

**Comment by MomotenkoNatalia** [comment]
@erikhansen  Internal ticket MAGETWO-46924 is closed and delivered to mainline. Please let us know if you still have an issue.
