### ISSUE TITLE
Magento CE 2.3.X the swagger interface api named integrationCustomerTokenServiceV1 http scheme valid customer acess details entered and execute still  server response is 401

### ISSUE THREAD

**Issue by ajaykumar03** [magento/magento2#27098]
### Preconditions:

- Magento 2.4-develop
- Swagger/Postman https scheme integrationCustomerTokenServiceV1
- Customer is created

### Steps to reproduce

1) Open the default magento Swagger http schemes or use this same api in postman.
2) Open integrationCustomerTokenServiceV1 interface to generate token for customers.
3) Enter the integrationCustomerTokenServiceV1CreateCustomerAccessTokenPostBody as registered customer acess details  to generate token for customer.
4) Verify the response the valid respose token should be generated for the valid registered customer acess details as entered.

### Expected result :
When in swagger/postman interface to generate customer acess details is entered the valid respose code should be generated for the valid customer details as entered.

### Actual result :
When in swagger/postman interface to generate customer acess details is entered the valid respose code was not getting  generated for the valid customer details as entered and the respose was as: "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later"

![swagger issue](https://user-images.githubusercontent.com/38529140/75606488-54986080-5b13-11ea-9b37-2c64b51791e1.png)

**Comment by baranada** [comment]
I confirm that this problem exist when shared account not on. if you turn on customer shared account on Account Sharing Options, it return correct token.
I think I could fix this by iterating all websites login when it occurs.
I don't see any ticket created this problem. I will follow up when this need to be developed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35510` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ajaykumar03. Thank you for your report. 
The issue has been fixed in magento/magento2#28822 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [a209c510716a054efd8eab17374e85cb84f8a2e0](https://github.com/magento/magento2/commit/a209c510716a054efd8eab17374e85cb84f8a2e0)

The fix will be available with the upcoming 2.4.1 release.
