### ISSUE TITLE
Magento 2.3.4 Store Switcher Tooltip Link Redirect 400 Bad Request

### ISSUE THREAD

**Issue by RHapani** [magento/magento2#27094]
### Preconditions (*)

In Magento 2.3.4 admin, go to dashboard and click on store switcher tooltip. It will redirect to 400 bad request page.

### Steps to reproduce (*)

1. Install Magento 2.3.4 version
2. Login to admin and go to dashboard.
3. Click on tooltip on store switcher
![Screenshot from 2020-02-29 16-18-18](https://user-images.githubusercontent.com/56859210/75606082-4a746300-5b0f-11ea-84e5-cd1581e548b4.png)

### Expected result (*)

It should be redirect on scope configuration page of Magento official devdocs.

### Actual result (*)

400 Bad Request
![Screenshot from 2020-02-29 16-21-09](https://user-images.githubusercontent.com/56859210/75606124-bce54300-5b0f-11ea-9a49-0a6cd3e5b793.png)

**Comment by samikshakrish** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish, here is your [Magento instance](https://i-27094-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27094-2-4-develop.instances.magento-community.engineering/admin_9c5e](https://i-27094-2-4-develop.instances.magento-community.engineering/admin_9c5e)
Login: `39af44a6` Password: `e85562be5a92`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @RHapani. Closing this issue as it works fine here
Thanks you for your report !!
