### ISSUE TITLE
Who is the sorry mfer that ruined Magento?

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#27102]
Was it a group effort or any single individual that choose to release a bunch of bloatware that's so over populated with everyone's BS that's it's now beyond usability. It's so slow at trying to do simple tasks like open a product page or category that it not only kills a persons position in the search engine it's guaranteed to make you hate the system just working with it. 

I could go on about the issues with this system but I think I'm done wasting my time. 

One warning to anyone new considering Magento. If you want to achieve anything online, use another system. This system will ruin you. Even if you remove all the bullshit extension that bloat the system it's still unusable. 

I'm done with this system. I have built, hosted and supported multiple of store owners for YEARS that have left or are leaving Magento because if this one main issue. YOU WILL NEVER ACHIEVE A POSITION IN THE SEARCH ENGINE Therefor you will never gain sales. PERIOD.

**Comment by gfxguru** [comment]
I figured you would just close this issue. That's fine, I'll just write a public article describing the issues with Magento and why it's a bad choice to use and see if you can close that one.

**Comment by gwharton** [comment]
This is the first issue you've raised on magento in over a year. If you have a problem, try raising a technical issue and seeing if we can help. Resorting to offensive rants will get you nowhere.
