### ISSUE TITLE
Not able to update the theme in Magento 2.3

### ISSUE THREAD

**Issue by Sanjeevkalia74** [magento/magento2#27113]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by Sanjeevkalia74** [comment]
> Hi @Sanjeevkalia74. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Sanjeevkalia74 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

![Image 01-03-20 at 2 49 PM](https://user-images.githubusercontent.com/57901953/75622974-d2b83e00-5bcb-11ea-8102-75dc5882a399.jpg)
I am facing these issues

**Comment by magento-engcom-team** [comment]
Hi @Sanjeevkalia74. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sanjeevkalia74, here is your [Magento instance](https://i-27113-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27113-2-4-develop.instances.magento-community.engineering/admin_3574](https://i-27113-2-4-develop.instances.magento-community.engineering/admin_3574)
Login: `ee39963f` Password: `3b8881064147`
Instance will be terminated in up to 3 hours.

**Comment by Sanjeevkalia74** [comment]
thanks, @magento-engcom-team,  have loged in its a empty site what do i need to do next

**Comment by gwharton** [comment]
This is not a bug in the magento code. Please ask for help in stack exchange to resolve your issues.
