### ISSUE TITLE
Magento 2 core JS not following new pattern for loading jQuery UI modules

### ISSUE THREAD

**Issue by jlczapski** [magento/magento2#27120]
### Preconditions (*)

1. Magento v2.3.4
2. On any page where *'jquery/ui'* has been loaded via JS

### Steps to reproduce (*)

1. When page loads, a warning is thrown in console saying *Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site.*
2. 

### Expected result (*)

1. ![Screenshot 2020-03-02 at 10 42 58 (2)](https://user-images.githubusercontent.com/16479189/75669270-adcad600-5c72-11ea-81fe-db98c4197891.png)
2. Only required jQuery UI modules should be loaded. Since jQuery UI modules are now split into separate files, using *'jquery/ui'* will load all modules unnecessarily, leading to poorer page load times.

### Actual result (*)

1. ![Screenshot 2020-03-02 at 10 38 22 (2)](https://user-images.githubusercontent.com/16479189/75668992-19607380-5c72-11ea-937a-bba8fb72cd22.png)
2. For example, when creating a widget, the require statement should be using the new pattern of *'jquery-ui-modules/widget'* instead of *'jquery/ui'*

**Comment by jlczapski** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jlczapski. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jlczapski, here is your [Magento instance](https://i-27120-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27120-2-4-develop.instances.magento-community.engineering/admin_576e](https://i-27120-2-4-develop.instances.magento-community.engineering/admin_576e)
Login: `333a3983` Password: `d7ed83ca6e59`
Instance will be terminated in up to 3 hours.

**Comment by jlczapski** [comment]
Could not reproduce on 2.4-develop and looks like it has been fixed in JS files, so guessing this will be part of the release?

**Comment by sunilit42** [comment]
@magento give me 2.2.11 instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` and `2.4` release line

**Comment by engcom-Bravo** [comment]
Hello @jlczapski 

Thank you for your report

Yes, this fix will be a part of the upcoming 2.3.5 release

If you'll ever face any issues with Magento, please, feel free create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you for collaboration

**Comment by onepack** [comment]
@engcom-Bravo 
What changes are included for this fix for the 2.3.5 release?
Any references?
