### ISSUE TITLE
Issues while trying to allow order products out of stock

### ISSUE THREAD

**Issue by NeilofSteel** [magento/magento2#27123]
Hey,
the out of stock products in my Magento 2 shop did not get a "add-to-cart" button. I already had selected the settings which displays products out of stock and allows backorders. Now I updated my migration tool and run a setup:upgrade and now every product has a "in stock" status. So magento throws true on "$_product->isAvailable()" everytime if the product is out of stock and if it is in stock.
Does anyone know the problem?

(Magento 2 version 2.3.4)

**Comment by AnnaShepa** [comment]
@NeilofSteel thank you for the report. I would kindly ask you to follow the template and provide steps to reproduce in issue reports, to make it easier to reproduce and fix the problem. 
Please check not only your configuration inside the product, but global configuration as well:
![Screenshot 2020-03-03 at 14 55 22](https://user-images.githubusercontent.com/24183408/75782332-10999b80-5d5f-11ea-9b91-0a0f8d57d1a2.png)
After enabling that setting I got back the "Add to cart" button

**Comment by NeilofSteel** [comment]
@AnnaShepa that was the first what I did ^^
I realised it only doesn't work for configurable (child)products. I can add single products to cart but not the childs of configurable products if they're out of stock. On some point the data var 'is_salable' is setting to 0 and throws false in Magento\Catalog\Model\Product\Type line 350 (function 'isSalable').
In the Image you can see, that you can't select the swatches of the configurable product which are out of stock.
![Swatches](https://user-images.githubusercontent.com/58559388/75977517-dc4be980-5edc-11ea-8632-0ef560708716.PNG)

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-27123-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27123-2-4-develop.instances.magento-community.engineering/admin_04b6](https://i-27123-2-4-develop.instances.magento-community.engineering/admin_04b6)
Login: `3dacb821` Password: `cf8528e4fee3`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@NeilofSteel  during next 3 hours you can check products created by me on dev magento instance. I managed to create configurable product with one preorder option, for that I just 
1. enabled preorders globally in settings
2. enabled preorder in the simple product 
3. set stock status for the product "In Stock" (please note that you have to set it after the 2nd step, otherwise with qty 0 it will be automatically set to "Out of stock")

**Comment by NeilofSteel** [comment]
@AnnaShepa so I have to set the stock status to "In Stock" manually everytime if a product is out of stock? Is there no other possibility to make childproducts salable if they are out of stock?

**Comment by NeilofSteel** [comment]
@AnnaShepa ah well like your description I think it wouldn't change the stockstatus after the two changes but is it not enaugh to set only the globally settings?

**Comment by AnnaShepa** [comment]
@NeilofSteel  correct, if you set global setting before product creation, then you don't have to do anything more: by default new product will be available for preorder and once qty going below 0, stock status will not be changed automatically 
![Screenshot 2020-03-05 at 13 54 31](https://user-images.githubusercontent.com/24183408/75983646-2d61da80-5ee9-11ea-9810-b4379b19e6be.png)

**Comment by NeilofSteel** [comment]
okay thank you very much @AnnaShepa :)
