### ISSUE TITLE
PUT /V1/carts/{cartId}/items/{itemId} No such entity with cartId = null

### ISSUE THREAD

**Issue by pborges** [magento/magento2#2713]
Actual url

```
PUT /V1/carts/81/items/1
```

Post body 

```
{
    "cartItem":{
        "qty":1
    }
}
```

Response

```
{
  "message": "No such entity with %fieldName = %fieldValue",
  "parameters": {
    "fieldName": "cartId",
    "fieldValue": null
  }
}
```

**Comment by ishakhsuvarov** [comment]
@pborges Thank you for reporting this.
Please try adding a `quoteId` param to the request body, e. g:

```
PUT /V1/carts/81/items/1
{
    "cartItem": {
        "qty": 10,
        "quoteId": 81
    }
}
```

We have an internal ticket with id `MAGETWO-46732` to fix id duplication in such cases.

**Comment by pborges** [comment]
That did not work for me, this is the error I get now

```
{
  "message": "Cart %1 doesn't contain item  %2",
  "parameters": [
    "81",
    1
  ]
}
```

It looks like its trying to display that item rather than attach?
I am using a PUT request

**Comment by ishakhsuvarov** [comment]
@pborges `PUT /V1/carts/:cartId/items/:itemId` is used to update the item.
If you wish to add another item to the cart please refer to `POST /V1/carts/:cartId/items`.

**Comment by pborges** [comment]
Ok, I will try that. However the swagger documentation says

```
Put /V1/carts/{cartId}/items/{itemId}
description: "Adds the specified item to the specified cart."
operationId: "quoteCartItemRepositoryV1SavePut"
```

**Comment by ishakhsuvarov** [comment]
@pborges Thanks, we will check and fix documentation on this topic.

**Comment by userException** [comment]
@pborges did you manage to solve this via post ? It give same response with post, as if it is trying to update the product

**Comment by ishakhsuvarov** [comment]
@pborges @userException
To add an item to the existing cart you may use the following:
`POST /V1/carts/:cartId/items`

``` javascript
{
    "cartItem": {
        "sku": "simple",
        "quoteId": 1,
        "qty": 1
    }
}
```

**Comment by pborges** [comment]
@userException post worked perfectly providing the item is "In Stock"

**Comment by userException** [comment]
@pborges @ishakhsuvarov  This worked for me..

Also, I was trying to update the product in the cart. How can I decrease the quantity? I tried sending -1 in "qty" parameter via a PUT request but it increased the quantity.

And deleting the product removes the whole product and does not decrease the quantity, which is correct. But what can be used for updating a product in the cart.

**Comment by ishakhsuvarov** [comment]
@userException To update the item in cart please try the following:
`PUT /V1/carts/:cartId/items/:itemId`

``` javascript
{
    "cartItem": {
        "itemId": 1,
        "qty": 10,
        "quoteId": 1
    }
}
```

You may obtain the list of items and their `itemId` for the specific cart using `GET /V1/carts/:cartId/items`.

**Comment by userException** [comment]
@ishakhsuvarov  @pborges  Thanks this solved my issue ! Can you help me with this one: https://github.com/magento/magento2/issues/2773

**Comment by mstumpf818** [comment]
@ishakhsuvarov the documentation here http://devdocs.magento.com/swagger/index.html still says "Implementation Notes Add the specified item to the specified cart." for the PUT method

**Comment by akashrajguru** [comment]
how can we add configurable or bundle product to cart ?

**Comment by amnotafraid** [comment]
Is there any update with this?  I am working with Magento ver. 2.1.7.
If I try  PUT  '/V1/carts/{cartId}/items/10 with this body:
```
{
    "cartItem":{
        "qty":1,
        "quoteId": 70
    }
}
```
I get 
```
{
    "message": "Cart %1 does not contain item %2",
    "parameters": [
        "70",
        10
    ]
}
```
PUT '/V1/carts/70/items/10' with this body:
```
{
    "cartItem":{
        "qty":1
    }
}
```
gets me this:
```
{
    "message": "No such entity with %fieldName = %fieldValue",
    "parameters": {
        "fieldName": "cartId",
        "fieldValue": null
    }
}
```
POST '/V1/carts/70/items/10' with this body:
```
{
    "cartItem": {
        "sku": "TRAINING-MAGENTO-STOREMG",
        "qty": 1
    }
}
```
gets me this:
```
{
    "message": "No such entity with %fieldName = %fieldValue",
    "parameters": {
        "fieldName": "cartId",
        "fieldValue": null
    }
}
```
So, basically, I haven't discovered a way to add an item to a cart.

**Comment by mbelyamani** [comment]
In Post you need to include quoteId

**Comment by amnotafraid** [comment]
Thanks for your help.  What I had to do was:

1. Create a cart
2. Put the item in the cart

## Details - Create Cart

POST '/V1/guest-carts'
(no body)

It returns something I will call a `sCartKey`.  Mine looks like this:  `8ea31b655a5ea0be566b9722f831b77a`

## Details - Add Item to Cart

To put `iQty` item(s) with the sku `sSku` in the cart:

POST '/V1/guest-carts/{sCartKey}/items'

with this body:

```
{
 "cartItem": {
   "sku" : sSku,
   "qty" : iQty,
   "quote_id" : sCartKey
 }
}
```

**Comment by chhillarakul** [comment]
Hi I am still encountering the above error. I am using POST request with the following parameters in the body section
`{"data":{"cartItem":{"productOption":{"extensionAttributes":{"customOptions":[]}},"qty":1,"quote_id":"1507026","sku":"FTW122019B3541","price":225}},"cartId":"1507026"}`

And I get the following output
`{
    "message": {
        "message": "No such entity with %fieldName = %fieldValue",
        "parameters": {
            "fieldName": "cartId",
            "fieldValue": null
        }
    }
}`

Any help?

**Comment by akulchhillar** [comment]
Hi I am still encountering the above error. I am using POST request with the following parameters in the body section
{"data":{"cartItem":{"productOption":{"extensionAttributes":{"customOptions":[]}},"qty":1,"quote_id":"1507026","sku":"FTW122019B3541","price":225}},"cartId":"1507026"}

And I get the following output
{ "message": { "message": "No such entity with %fieldName = %fieldValue", "parameters": { "fieldName": "cartId", "fieldValue": null } } }

Any help?

**Comment by ashishc2503** [comment]
Hi, was anyone able to find a solution here? I'm hitting POST /carts/{cart}/items/{itemId} to add an item to the cart for a logged-in user with quote Id and qty in the request body. But I get a `"message": "Request does not match any route."` response.
