### ISSUE TITLE
Magento 2.3.3 to 2.3.4 Upgrade Issue: Invalid argument supplied for foreach() in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185

### ISSUE THREAD

**Issue by Jawwadiftikhar** [magento/magento2#27140]
Hi Guys,
I've just upgraded my site from Magento 2.3.3 to 2.3.4. I'm using MGS Claue theme.
After the upgrade, I'm not able to edit the Products in the Admin. 
It shows this error when I edit a product: **Warning: Invalid argument supplied for foreach() in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185**

![issue](https://user-images.githubusercontent.com/24936449/75780871-f91ddb00-5d7d-11ea-8152-0eeff9614357.png)

I've used composer for upgrade and followed the procedure from Magento Guide: https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html

Any help would be really appreciated.

**Comment by bigbanne2004** [comment]
I have the same error after i upgrade from Magento 2.3.3 to 2.3.4

**Comment by b2bdokter** [comment]
Same here, magento 2 keep including 3rth party software , no doubt they will pay you good. This will F up the webshop of your customers  but who cares ? Great job again this magento 2.3.4 update ! Issue cannot be reproduced haha , well done !

**Comment by jigar48** [comment]
I got same error in the magento 2.3.5-p1 

![Screenshot_1](https://user-images.githubusercontent.com/16815711/81464929-9a446a00-91e3-11ea-883f-33d4e73b609c.png)

**Comment by advcha** [comment]
I found this variable `$this->mapProviders` is empty. not sure what happened. I solved this problem by modifying the core magento file in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php. In `getMap` function, add this after `if (!$types) {...}`. So it'd be:
```
public function getMap(array $products, array $types): array
{
    if (!$types) {
        throw new \InvalidArgumentException('Types are required');
    }
   //FIX Warning: Invalid argument supplied for foreach() in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185
    if (!(is_array($this->mapProviders))) {
        $this->mapProviders = array(
            ObjectManager::getInstance()->create(LinkedMapProvider::class)
        );
    }
   ...
```

I know this fix not clean as magento way. let me know if there is a better fix.

**Comment by jigar48** [comment]
@magento-engcom-team any solution ?

**Comment by moni921** [comment]
I got same after upgrading to 2.4

Any solution,  how to fix it

**Comment by moni921** [comment]
@advcha , please help us
