### ISSUE TITLE
Price cached on the Redis server.

### ISSUE THREAD

**Issue by drew7721** [magento/magento2#27146]
### Preconditions (*)

1. Magento 2.3.2 and above
2. Need to have multiple instances that have independent Redis servers on each instance.
3. Say using something similar to this https://devdocs.magento.com/common/images/cloud_stack-diagram.png

### Steps to reproduce (*)

1. Change a product price.
2. Only the Redis cache on the admin instance will be flushed, not the Redis caches on the other instances.

### Expected result (*)

1. Flush caches on all redis instances like it's done for varnish.

### Actual result (*)

1.  The price does not change on all instances.

This was introduced by this commit https://github.com/magento/magento2/commit/1d9b1ba0981f2084c6e6da180c8dcf0c2e78f7da and all the other commits related to it. 
Based on the commit message it's fixing some *MC-6273* issue that has to do with the queries to the `url_rewrite` table. Don't see how the commit message is relevant with the code changes.

I really don't see the need to cache the product price_box html once more in Redis when we have the full_page cache for that.

How many layers of caching are needed?

Instead of fixing bugs caused by caches such as https://github.com/magento/magento2/issues/3625 this is now adding more caches that will just cause more issues down the line.

**Comment by drew7721** [comment]
To reproduce this you need an environment that runs multiple instances of the code and the Redis cache server.

**Comment by danemacmillan** [comment]
After doing a bit more research into this, I found the commit that is responsible for this problem:

https://github.com/magento/magento2/pull/19897

I also commented about the problem this introduces:

https://github.com/magento/magento2/pull/19897#issuecomment-594708046

**Comment by ihor-sviziev** [comment]
Hi @drew7721 @danemacmillan,
As I understood - you have own redis server on each web node? If so - it's wrong configuration as the web nodes not shares the cache that leads to higher load on each node and issues like you described above.

Could you explain more your use case?

**Comment by devendrant** [comment]
@igorwulff did you find any solution to this issue? we're facing the same issue.

**Comment by igorwulff** [comment]
@devendrant  we were provided this patch which should solve the issue apparently. I haven't tested it yet.
[ACSD-47850_2.4.4.patch.txt](https://github.com/magento/magento2/files/11051538/ACSD-47850_2.4.4.patch.txt)

**Comment by hostep** [comment]
The patch @igorwulff mentions corresponds with this commit: [ACP2E-1321: L2 cache save not working](https://github.com/magento/magento2/commit/c893715a4e6002e86a9c5f6e3a53fbcc26ca9183) which is included in Magento 2.4.6

Just FYI.
