### ISSUE TITLE
Product Media Gallery Update Response (bool)

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#27147]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. PUT {{baseUrl}}/V1/products/:sku/media/:entryId

### Expected result (*)
1. Return new EntryId (similar to POST)

### Actual result (*)
1. Response is "true" or error in JSON format

**Comment by engcom-Echo** [comment]
Hi, @Stoyvo. Thank you for your report.

PUT updates a resource. If you have replaced an object, you will already have all the latest data in your data (for example EntryId). PUT does not need any other behavior.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by Stoyvo** [comment]
@engcom-Echo PUT on a media gallery creates a new ID for the updated image - Magento does not keep the same ID as before, that is the problem.
