### ISSUE TITLE
Percentage discount on Shipping amount is not working correctly

### ISSUE THREAD

**Issue by wajihkm** [magento/magento2#27152]
### Preconditions (*)

1. Magento 2.1.1.6

### Steps to reproduce (*)

1. Create new "Cart price rule"
2. select "Percent of product price discount"
3. check "Apply to Shipping amount"
4. Save
5. add Items to the Cart
6. on checkout page, the price summary will be coorect
7. After select "Check/Money order" and "Place Order"
8. if done, view the Order summary and check  how the price is different from the "Checkout page"

### Actual result (*)

1. ![magento2116-ec-bug](https://user-images.githubusercontent.com/18402145/75873170-e6141500-5e28-11ea-9485-e9793f14f6a4.jpg)
2. ![magento2116-ec-bug-2](https://user-images.githubusercontent.com/18402145/75873191-ef04e680-5e28-11ea-8716-a3446cf645ac.jpg)

**Comment by wajihkm** [comment]
@magento give me 2.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wajihkm. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` and `2.4` release line

**Comment by wajihkm** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wajihkm. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wajihkm, here is your [Magento instance](https://i-27152-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27152-2-4-develop.instances.magento-community.engineering/admin_af29](https://i-27152-2-4-develop.instances.magento-community.engineering/admin_af29)
Login: `b42cb68d` Password: `55c7f71d3de4`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@wajihkm - Please follow the below Magento issue reporting process. If you do not follow the process "Format is not valid" tag will not be removed.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Thanks.

**Comment by ajijshekh123** [comment]
Hi @wajihkm,
I have reviewed this issue in the default Magento 2.4 instance as per your steps, expected result and actual result but not able to reproduce this issue.
Please see attached the screenshot:
 
![1](https://user-images.githubusercontent.com/24711761/75886682-a2340680-5e4e-11ea-89df-82970c0b67a5.png)

![2](https://user-images.githubusercontent.com/24711761/75886686-a3fdca00-5e4e-11ea-981a-be3833863188.png)

![Rule](https://user-images.githubusercontent.com/24711761/75886688-a4966080-5e4e-11ea-8741-a9b8f8b228d8.png)

Please send me a video if you have reproduced this issue again.

Thanks.

**Comment by wajihkm** [comment]
Hi @ajijshekh123 
Thanks for your time, 
It appears on Magento 2.1.1.6 version, It does not appear on newer versions.
So I just want to know if it is a bug from Magento system.
Thanks

**Comment by ajijshekh123** [comment]
Hello @wajihkm,
If this issue is not available in the latest version so I can't able to confirm this issue.
I have suggestion to you, Please update the Magento 2.4 instance and verify it. If this issue is again raised you can open this ticket.
Now I am close to this ticket.

Thanks.
