### ISSUE TITLE
Compare List does not show attribute values of type Boolean (Yes/No)

### ISSUE THREAD

**Issue by homecoded** [magento/magento2#27155]
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.2.26-1+ubuntu18.04.1+deb.sury.org+1

### Steps to reproduce (*)

1. Create product attribute of type Boolean (Yes/No), make sure the attribute is visible on compare page
2. Add attribute to "Default" attribute set
3. Edit existing product (or create new product) and set the attribute to "Yes"
4. Find the product in catalog frontend, and add it to the compare list
5. Open compare list

### Expected result (*)

1. The attribute is shown in a separate line
2. The attribute value is shown as string (Yes or No)

### Actual result (*)

1. The line of the attribute is shown
2. The attribute value is missing (empty table cell)

![magento_demoshop-magento2-daily_catalog_product_compare_index_](https://user-images.githubusercontent.com/565020/75879410-adba0a00-5e1b-11ea-8d05-8e4cdd03a1c4.png)

**Comment by homecoded** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @homecoded. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @homecoded, here is your [Magento instance](https://i-27155-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27155-2-4-develop.instances.magento-community.engineering/admin_f27a](https://i-27155-2-4-develop.instances.magento-community.engineering/admin_f27a)
Login: `ab9a02a9` Password: `1d2104b651d4`
Instance will be terminated in up to 3 hours.

**Comment by homecoded** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @homecoded. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by homecoded** [comment]
Could not reproduce on 2.4, trying 2.3

**Comment by homecoded** [comment]
Was able to reproduce issue on http://demoshops.splendid-internet.de/magento/demoshop-magento2-daily/

**Comment by homecoded** [comment]
I created a patch that can be applied via composer.json

```
"extra": {
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/module-catalog": {
                "Magento Catalog - Compare List (Boolean attributes not shown) ": "patches/magento2-27155-compare-list-does-not-show-attribute.patch.txt"
            }
        }
    }```

[magento2-27155-compare-list-does-not-show-attribute.patch.txt](https://github.com/magento/magento2/files/4287358/magento2-27155-compare-list-does-not-show-attribute.patch.txt)

**Comment by krishprakash** [comment]
Hi @homecoded,
Seems issue has been fixed on latest instance
So clsoing this ticket as can not reproduce
![image](https://user-images.githubusercontent.com/46617848/75984404-5a75b380-5f10-11ea-8e83-d82bee9367a6.png)
Thank you !!
