### ISSUE TITLE
Magento 2.2 version 

### ISSUE THREAD

**Issue by amolbhandari** [magento/magento2#27156]
Preconditions (*)
1) Magento version is 2.2 CE

Steps to reproduce (*)
1) I get this in my exception.log in var/log folder . the log is 
2) [2020-03-04 11:27:30] main.CRITICAL: Class does not exist {"exception":"[object] (InvalidArgumentException(code: 0): Class does not exist at /home/portresttrailcom/public_html/vendor/magento/module-rule/Model/ConditionFactory.php:50)"} []
Expected result (*)
1) need to get rid of this isssue
2) Not gettign any clue why this is causes

**Comment by engcom-Delta** [comment]
Hi @amolbhandari .
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
