### ISSUE TITLE
Magento 2.2 bug log regarding Apptrian module

### ISSUE THREAD

**Issue by amolbhandari** [magento/magento2#27157]
Preconditions (*)
1) Magento 2.2

Steps to reproduce (*)
1) I am using Apptrian image optimizer module 2.2.3
2) The site runs fine but i get below error in the exception.log in var/log folder
3) [2020-03-04 11:15:05] main.CRITICAL: Your image index is corrupted at line 1. {"exception":"[object] (Exception(code: 0): Your image index is corrupted at line 1. at /home/portresttrailcom/public_html/app/code/Apptrian/ImageOptimizer/Helper/Data.php:749)"} []

Expected result (*)
1) No error should be logged.
2) whats the actual cause of this.

**Comment by engcom-Delta** [comment]
Hi @amolbhandari 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
