### ISSUE TITLE
Payment object / information is NULL and not added to order repository

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#27158]
### Preconditions (*)

1. Magento 2.3.3 / 2.3.4

### Steps to reproduce (*)

1. Create code which will fetch order information using searchCriteriaBuilder and order repository (code below)
2. Create 3 products
3. Create user account
4. Create at least 2 orders containing product nr 3
5. Try to fetch customer orders, status complete 

```
$filters = $this->searchCriteriaBuilder
            ->addFilter(Order::CUSTOMER_ID, $customer->getId())
            ->addFilter(Order::STATE, Order::STATE_COMPLETE)
            ->create();

$customerOrders = $this->orderRepository->getList($filters)->getItems();
```

6. Try to iterate through all orders (example code) containing productId  = 3

```
// just some funciton to summarize total purchases of certain product
foreach($customerOrders as $order) {
            foreach($order->getItems() as $orderItem) {
                if($orderItem->getProductId() == 3) {
                    $ordersValue += $orderItem->getRowTotal();
                }
            }
        }
```

### Expected result (*)

1. No issue

### Actual result (*)

1. Code error: `PHP Fatal error:  Uncaught Error: Call to a member function getAdditionalInformation() on null in [...]vendor/magento/module-sales/Model/OrderRepository.php:182\
`
2. Issue is here, payment object is null
![image](https://user-images.githubusercontent.com/4256191/75880355-659be700-5e1d-11ea-8347-88407011fed6.png)

**Comment by zcuric** [comment]
Issue on present on 2.4.1.

**Comment by Den4ik** [comment]
@qsolutions-pl Thanks for the report. Unfortunately I can't reproduce problem with provided steps.

https://user-images.githubusercontent.com/1129623/117139302-c1148c80-adb4-11eb-94f4-0ff67215c869.mp4


Please add more details for reproducing the problem and fill free to reopen issue.
Thanks.
