### ISSUE TITLE
Cart unit item price is shown in wrong currency if custom_price is used

### ISSUE THREAD

**Issue by borriglione** [magento/magento2#27161]
### Preconditions

1. Magento 2.3.4
2. Multi-Currency Setup
3. quote_item.custom_price is used

### Steps to reproduce (*)

1. Install Magento 2.3.4
2. Deploy sample data
3. Default currency is already US-Dollar (USD)
4. Add 2nd allow currency f.e. EURO (EUR)
5. Set rate f.e. 1 USD = 1.5 EUR
6. Switch to EUR by currency switcher in frontend
7. Add product with qty 2 in cart.
7. Set a custom item price by observer or in the database quote_item.custom_price
8. Open cart page

Sample:
```
$item->setCustomPrice(10)
$item->setOriginalCustomPrice(10)
```

### Expected result (*)

I would expect to see:
- Item unit price: **15** EUR
- Row subtotal: 30 EUR

### Actual result (*)

- Item unit price: **10** EUR
- Row subtotal: 30 EUR

It seems that `quote_item.custom_price` is currently always stored in base currency which is then not converted during cart item output.

### Suggestion

Best practice would be to have 4 columns for quote_item

- base_custom_price
- custom_price
- base_original_custom_price
- original_custom_price

### Additional info from engcom

- _Stores - Currency - Currency Rates_
![eurotousd](https://user-images.githubusercontent.com/51680745/76743760-cd3a2680-677b-11ea-88dc-d098214d611c.png)

- Magento 2 Database, _quote_item_ table ```custom_price``` set to **10**
![quote_cust_price](https://user-images.githubusercontent.com/51680745/76743974-2904af80-677c-11ea-8b69-6fed5de33bb0.png)

- Storefront, 2 itmes added to Cart
![10x2](https://user-images.githubusercontent.com/51680745/76743680-ac71d100-677b-11ea-9cf7-db80089b7556.png)

**Comment by engcom-Bravo** [comment]
Hello @borriglione 

Thank you for your report.

We are able to reproduce this behaviour on Magento 2.4-develop

**Comment by kiennt1989** [comment]
Hi @borriglione 
I think this issue is false case testing. relate to :
https://github.com/magento/magento2/issues/12493

**Comment by alexryall** [comment]
Took me a while to figure out but vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php:692

`$quoteItem->setCustomPrice($baseItemTaxDetails->getPrice());`

should be:

`$quoteItem->setCustomPrice($itemTaxDetails->getPrice());`

**Comment by koushikch7** [comment]
@magento give me 2.4-develop instance

**Comment by zexperto** [comment]
I could find a solution for this using currency convert function in this class [ \Magento\Directory\Model\Currency ]

$currency is instance of  \Magento\Directory\Model\Currency 
$correct_price = $currency->convert({your price}, {current store currency}); 

then 

 $quoteItem->setCustomPrice($correct_price);
 $quoteItem->setOriginalCustomPrice($correct_price);

this was not working on 2.3.x but now it looks working on 2.4.3

**Comment by maheshmakwana-code** [comment]
I fixed the issue. Please check this : https://github.com/magento/magento2/issues/33134#issuecomment-1724410098

**Comment by araujophillips** [comment]
> I fixed the issue. Please check this : [#33134 (comment)](https://github.com/magento/magento2/issues/33134#issuecomment-1724410098)

The core bug it's not solved with this. It's more a workaround.

Please check out my comments here: [https://github.com/magento/magento2/issues/33134#issuecomment-1785162585](https://github.com/magento/magento2/issues/33134#issuecomment-1785162585)
