### ISSUE TITLE
MSRP price is not updated when using dropdown instead of swatch

### ISSUE THREAD

**Issue by ashokadewit** [magento/magento2#27166]
### Preconditions

1. Magento 2.4

### Steps to reproduce

1. Enable MAP (Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).
2. Create a configurable product
3. Create variations for two attributes. One of type "swatch", one of type "dropdown".
4. Assign different MSRP for the variations.
5. Go to product on the frontend click the swatches and change the dropdown.

### Expected result

1. MSRP gets updated when clicking on a swatch.
2. MSRP gets updated when the dropdown is changed.

### Actual result

1. The MSRP is only updated when a swatch is clicked. Not when the dropdown is changed.

### Additional Information 
**Note 1:**
Need to click swatch twice after changing a value in the dropdown
- First click UN-select swatch = price will for dropdown value only
- second click select swatch again = price will be updated for dropdown+swatch

See the record in https://github.com/magento/magento2/issues/27166#issuecomment-627678921

**Note 2:**
- this case works as expected if MSRP is disabled. Price is changed if choose a different value of dropdown  with selected swatch

**Comment by ashokadewit** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ashokadewit. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ashokadewit, here is your [Magento instance](https://i-27166-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27166-2-4-develop.instances.magento-community.engineering/admin_ad80](https://i-27166-2-4-develop.instances.magento-community.engineering/admin_ad80)
Login: `40fea045` Password: `70cbad1f42ca`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Need to click swatch twice after changing a value in the dropdown
- First click UN-select swatch = price will for dropdown value only
- second click select swatch again = price will be updated for dropdown+swatch

![issue_27166](https://user-images.githubusercontent.com/3409584/81759456-65a60c00-948a-11ea-9142-ee7c393da4bb.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34269` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
