### ISSUE TITLE
List of GET request parameters in magento 2.0

### ISSUE THREAD

**Issue by userException** [magento/magento2#2716]
I have the list of 1.x version: https://github.com/magento/devdocs/blob/develop/guides/m1x/api/rest/get_filters.html

Link to 2.0 GET filters??

**Comment by Vinai** [comment]
You can find a list of API GET parameters in the [Swagger API Reference](http://devdocs.magento.com/swagger/index.html).
However, the Github issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2. Thank you.
