### ISSUE TITLE
"You already have an account" when none exists after failed checkout

### ISSUE THREAD

**Issue by mattf10** [magento/magento2#27173]
### Preconditions (*)

1.  2.3.4
2.  System info:
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1
OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

### Steps to reproduce (*)

1.  Checkout as guest.  Transaction doesn't complete for whatever reason (bad credit card number etc).  
2. Go back to checkout and below email is a password form with the message "You already have an account with us. Sign in or continue as guest.".  However, no such account exists in the backend because it was never created.  

### Expected result (*)

1. The password box should not appear since the user does not have an account.
2.

### Actual result (*)

1. Password box and "you have an account" message appear when no such account exists
2.

<img width="532" alt="Screenshot 2020-03-05 at 09 57 57" src="https://user-images.githubusercontent.com/21988717/75964682-ed3e3000-5ec7-11ea-8c98-57f62116eb29.png">

Admin area, showing the account doesn't exist
<img width="584" alt="Screenshot 2020-03-05 at 09 58 28" src="https://user-images.githubusercontent.com/21988717/75964692-f29b7a80-5ec7-11ea-8904-abbcd8ad6d82.png">

**Comment by mattf10** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mattf10. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mattf10, here is your [Magento instance](https://i-27173-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27173-2-4-develop.instances.magento-community.engineering/admin_1717](https://i-27173-2-4-develop.instances.magento-community.engineering/admin_1717)
Login: `0d4b70b0` Password: `7324afdcf5f2`
Instance will be terminated in up to 3 hours.

**Comment by mattf10** [comment]
The development instance doesn't work (problem with indexers, can't find newly added product) so I cannot say whether it's reproduceable.  If you have a working test instance, I will try there.

This issue should remain open

**Comment by krishprakash** [comment]
Hi @mattf10. Thank you for your report.
Seems similar issue is added here #26903 and already open.
So closing this ticket.
