### ISSUE TITLE
Add to cart on product page empties the cart

### ISSUE THREAD

**Issue by mdesplenter** [magento/magento2#27177]
When adding a product to the cart from the detail view, it removes the other products in the cart and only shows the new product. When adding products from the overview page (direct add) this is not the case.

# Preconditions (*)
1. Magento 2.3.4
2. Local new installation (without varnish) and a live website (with varnish)
3. Simple and configurable products

### Steps to reproduce (*)
1. Go to an overview page
2. Add a product to the cart
3. Product is added to the cart
4. Go back to the overview
5. Click a product
6. Now add this product to your cart

### Expected result (*)
1. The second product should be added

### Actual result (*)
1. Cart is now only showing the new product

**Comment by mdesplenter** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by mdesplenter** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter, here is your [Magento instance](https://i-27177-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27177-2-4-develop.instances.magento-community.engineering/admin_2dc4](https://i-27177-2-4-develop.instances.magento-community.engineering/admin_2dc4)
Login: `89e25aa2` Password: `526630e0ea3a`
Instance will be terminated in up to 3 hours.

**Comment by mdesplenter** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by mdesplenter** [comment]
I cannot reproduce this in 2.4

**Comment by mdesplenter** [comment]
I found my error. To speed up the Magento shops we removed module-persistent. Removing this will result in above behaviour.
