### ISSUE TITLE
Wishlist -> Add All to Cart  500 Internal Server Error

### ISSUE THREAD

**Issue by Totarenx** [magento/magento2#2717]
Cant move two same bundle products with options to cart

/wishlist/index/allcart/?qty[10]=1&qty[11]=1

**Comment by davidalger** [comment]
@Totarenx Would you be able to provide complete information on what is happening when you attempt to do this? I.e. what error and/or unexpected behavior is occurring. Also, if you would post details on what environment you're running Magento 2 in as well as the installation method, that would be great. This will help the team diagnose the underlying cause.

**Comment by Totarenx** [comment]
No problem. You need to create a bundle product, add two of them to cart with some options(unequal), move to withlist. When you've got something like that
![1](https://cloud.githubusercontent.com/assets/14783879/11933198/7a3095f2-a80b-11e5-9fcf-1ca346ef6f5d.jpg)
click Add All to Cart.
As result: 500 Internal Server Error, cart is empty, wishlist has only one bundle item( the second one).
All logs are empty too.

Magento ver. 2.0.0 Publication with sample data, using the command line.
Also tried to do this on Magento ver. 1.0.0-beta without sample data installed through Setup Wizard and got the same error.

**Comment by sevos1984** [comment]
Hi @Totarenx, this was fixed in MAGETWO-45429 (internal id MAGETWO-47379) and soon will be delivered. Thanks for reporting

**Comment by slavvka** [comment]
Hi @Totarenx. The fix has been delivered to mainline. Please look at f56e20b. Feel free to reopen it once you still have problems.
