### ISSUE TITLE
Existing customers can't checkout after upgrade AmazonPay

### ISSUE THREAD

**Issue by will-wright1** [magento/magento2#27174]
Just upgraded to 2.3.4 but existing customers can't move from step 1 in the checkout to step 2.

You need to be logged in as a customer that existed on 2.3.3.

Error 500 on /rest/STORE/V1/carts/mine/shipping-information

"Fatal Error: 'Uncaught Error: Call to a member function getAmazonOrderReferenceId() on null in \/srv\/public_html\/vendor\/amzn\/amazon-pay-module\/Plugin\/ShippingInformationManagement.php:85\nStack trace:\n#0 \/srv\/public_html\/ven$

### Preconditions (*)
1. Magento 2.3.4
2. Apache and Nginx

### Steps to reproduce (*)
1. Have Amazon pay enabled
2. Create customer in 2.3.3 with addresses
3. Upgrade to 2.3.4
4. Login as an existing customer
5. Go to checkout
6. Can't get passed Shipping method 

### Expected result (*)
1. Customer should be able to select a previously used address and move to the payment method

### Actual result (*)
1. Customer can't get passed the shipping methods
2. Error 500 on /rest/STORE/V1/carts/mine/shipping-information

**Comment by sdzhepa** [comment]
Hello @webamondo 

We are not able to reproduce the issue on the latest 2.4.x version.
Seems it was fixed

**Comment by tuyennn** [comment]
@sdzhepa Here the ref issue https://github.com/amzn/amazon-payments-magento-2-plugin/issues/610
I'm freaking confusing while Magento injected multiple bloat wares and made our clients sites unstable at all, times to times after upgrading.
