### ISSUE TITLE
Magento search result core functional issue

### ISSUE THREAD

**Issue by surelockrich** [magento/magento2#27171]
### Preconditions (*)

1.Magento 2.3.3
2.MySQL

### Steps to reproduce (*)

1. I cannot reproduce in a better way so we have shared a demo you can verify
2. ref: Reproduce
[Reproduce.zip](https://github.com/magento/magento2/files/4291574/Reproduce.zip)
.zip

### Expected result (*)

1. Search should show only that result which is requested by that keyword 
2. [Reproduce.zip](https://github.com/magento/magento2/files/4291574/Reproduce.zip)
.zip

### Actual result (*)

1. ref: Reproduce.zip
2. [Reproduce.zip](https://github.com/magento/magento2/files/4291574/Reproduce.zip)
.zip

**Comment by AnnaShepa** [comment]
Hi @surelockrich , sorry, but I didn't get any problem from your video, please describe steps to reproduce and expected/actual result

**Comment by surelockrich** [comment]
ok will share details

**Comment by surelockrich** [comment]
Hello,
Kindly check this one I have made a new video. hope you will get the issue.

[Reproduce.zip](https://github.com/magento/magento2/files/4297955/Reproduce.zip)

Thank You

**Comment by surelockrich** [comment]
Have you checked?

**Comment by AnnaShepa** [comment]
Hi @surelockrich  sorry for long time answer. Yes, now I see your problem, but cannot reproduce it. Please try to reproduce it yourself on clean magento instance.  Are you using ElasticSearch?
