### ISSUE TITLE
Magento 2 Coupon Code Scheduler not working 

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/magento2#27186]
### Preconditions (*)

1. Magento EE 2.3.4

### Steps to reproduce (*)

1. Created coupon with Scheduled time along with coupon code and price rules
2. Applying coupon code on as end user & coupon code applied on non-Scheduled time

### Expected result (*)

1. Expected Scheduled coupon code shouldn't work on non-Scheduled time but coupon codes on non-Scheduled time 

### Actual result (*)

1.  Please find the attached below screen shots 

![Screenshot from 2020-03-06 09-53-57](https://user-images.githubusercontent.com/16919356/76051514-124aa580-5f91-11ea-9883-333ecaa8eb4e.png)

![Screenshot from 2020-03-06 09-55-53](https://user-images.githubusercontent.com/16919356/76051519-15de2c80-5f91-11ea-828a-682a89311eb0.png)

**Comment by krishprakash** [comment]
@sdzhepa Kindly move this issue to Enterprise repository

**Comment by Fencix** [comment]
Hi!
I have a similar problem but with the 2.3.2 Magento. I cannot generate coupons automatically. when I try appears a message "Message is added to queue, wait to get your coupons soon". But the coupons do not generate.
![cupones](https://user-images.githubusercontent.com/61866408/76080143-8fcce080-5fa6-11ea-927d-26e32743943d.JPG)

**Comment by hoangnm89** [comment]
@allamsettiramesh i think you don't understand how does "Schedule New Update" work?
as your case, i think should do like this:
the rule should be Disabled(in main form) and on Schedule form select start/end time then you turn rule on(Enable). When time come, rule will be active.
BTW, this feature requires crontab.

**Comment by luancschmitz** [comment]
> Hi!
> I have a similar problem but with the 2.3.2 Magento. I cannot generate coupons automatically. when I try appears a message "Message is added to queue, wait to get your coupons soon". But the coupons do not generate.
> ![cupones](https://user-images.githubusercontent.com/61866408/76080143-8fcce080-5fa6-11ea-927d-26e32743943d.JPG)
> 
> Can someone help me? How can I do to solve this? I would like to create a campaign.

I have Same Problem in Magento Cloud Production Environmnet.

**Comment by engcom-Alfa** [comment]
Hi @allamsettiramesh 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop. Everything works as expected.

**Manual testing scenario:**

1. Create a non Active Cart Price Rule with Coupon Code;
![2020-10-23_15-48](https://user-images.githubusercontent.com/51679138/97006882-2b688c80-1549-11eb-99e1-8425fd3e573b.png)

2. Click on the **Schedule New Update** button;
3. Specify the period when this rule should be active and click on **Enable** switcher

![2020-10-23_15-40](https://user-images.githubusercontent.com/51679138/97007066-7aaebd00-1549-11eb-9ca8-4fecaf2f02bc.png)
_Note:_ In my case, the rule will be active between 7:40 and 7:50. After 7:50 the rule will be inactive

5. Click on the **Save** button;
6. Apply Coupon Code in the period between 7:40-50;

**Actual Result:** :heavy_check_mark:  Coupon code is successfully applied

![Screenshot from 2020-10-23 15-46-31](https://user-images.githubusercontent.com/51679138/97007510-3112a200-154a-11eb-86fb-8a0720c48a97.png)

7. Apply Coupon Code after 7:50;

**Actual Result:** :heavy_check_mark:  Coupon code isn't applied

![Screenshot from 2020-10-23 15-43-11](https://user-images.githubusercontent.com/51679138/97007588-52738e00-154a-11eb-8cb8-3e6a2690f7b2.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. 
Thanks for your report!
