### ISSUE TITLE
magento error emails sending orders

### ISSUE THREAD

**Issue by ferryzz** [magento/magento2#27188]
Preconditions (*)
1. Magento 2.2.4

Steps to reproduce (*)
1. Go to an Order
2. Press Send Mail
I imagine you can create a customer and place an order manually, but I'm doing it on real orders.

The strange thing is that it shows me a message that the mail has been sent correctly but the status of the mail tells me that "it could not be sent".

Expected result (*)
1. No exception logs should be there
2. Receive Mail

Actual result (*)
1. exception.log: main.CRITICAL: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1 {"exception":"[object] (Exception(code: 2): DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1 at /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Escaper.php:77)"} []

Red is lane 77:
![image](https://user-images.githubusercontent.com/36172179/76069626-75d5d280-5f93-11ea-88c2-1e4dd4dbf6f7.png)

2. View from Magento's backend.
![image](https://user-images.githubusercontent.com/36172179/76069016-83d72380-5f92-11ea-869f-8897f3c6ea36.png)

**Comment by Pavel-Fekete** [comment]
Not reproducible on the latest 2.4-develop

**Steps to reproduce:**

1. Go to the store and create an order as customer
![Order](https://user-images.githubusercontent.com/67371013/98795251-acad9380-2412-11eb-8683-8d14f00d3dc6.png)
2. Go to admin panel and open previously created order
3. Press _Send Mail_ button
![Order in admin](https://user-images.githubusercontent.com/67371013/98795541-feeeb480-2412-11eb-8c72-3bd6189a88fa.png)

**Actual Result:** 
Order information mail was sent successfully, exception not occurred
![Mail was sent](https://user-images.githubusercontent.com/67371013/98795909-77ee0c00-2413-11eb-8993-2d2572def08e.png)
![mail](https://user-images.githubusercontent.com/67371013/98795940-83d9ce00-2413-11eb-91f6-226fff23e432.png)

**Comment by engcom-Bravo** [comment]
Hello @ferryzz 

Thank you for your report.

This issue is already fixed in the latest Magento 2.4-develop.

So we are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you
