### ISSUE TITLE
Documentation for **lib-css()** is not correct. Using false does not work.

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#27189]
### Summary (*)

Magento 2.3.4

Documentation for **lib-css()** is not correct. Using false does not work.

It says

> If the variable is set to false, the .lib-css() mixin will add nothing to the code.

I tested it, but it does not work at all.

### Examples (*)

I try to remove the **box-shadow** of a button in the customer area. 

https://i.stack.imgur.com/i2AF5.png

I found the code in

**vendor\magento\theme-frontend-luma\web\css\source\\_extends.less**:

    //
    //  Secondary button
    //  ---------------------------------------------
    
    & when (@media-common = true) {
        .abs-revert-to-action-secondary {
            &:extend(.abs-revert-secondary-color all);
            .lib-css(border-radius, @button__border-radius);
    
            &:not(:focus) {
                .lib-css(box-shadow, @button__shadow);
            }
    
            &:active {
                .lib-css(box-shadow, @button__shadow-active);
            }
        }
    }

I added my override to a new file 

**THEME\web\css\source\lib\extend\\_overrides.less**

    //
    //  Secondary button
    //  ---------------------------------------------
    
    & when (@media-common = true) {
        .abs-revert-to-action-secondary {
            &:extend(.abs-revert-secondary-color all);
            .lib-css(border-radius, @button__border-radius);
    
            &:not(:focus) {
                .lib-css(box-shadow, false);
            }
    
            &:active {
                .lib-css(box-shadow, false);
            }
        }
    }

I used **false** in `lib-css()` because in the Magento UI Library Documentation (lib/web/css/docs/utilities.html) it says:

> The **.lib-css()** mixin is used to set any css property if there is a
> value passed to it by a variable. Also .lib-css() can add -ms-,
> -webkit- and -moz- prefixes if needed.
> 
> If the variable is set to **false**, the .lib-css() **mixin will add nothing
> to the code**.

Then I imported the file into

**THEME\web\css\source\\_extend.less** 

    @import 'lib/extend/_overrides';

But the original code is still getting loaded from the following file and my override does not get applied: 

**/pub/static/frontend/hausfux/base/de_DE/css/source/_extends.less**

https://magento.stackexchange.com/questions/306356/magento-2-how-to-override-less-code-from-extends-less/306371#306371

### Proposed solution

Fix documentation entry and remove claim that using false will add nothing to the code.

I had to use `none` instead of `false`

**Comment by mrtuvn** [comment]
actually it work but your changes will not apply. Magento take over the previous property defined
If you want to override boxshadow why not use lib-css(box-shadow, none) instead of use lib-css(box-shadow, false) false flag will ignored
