### ISSUE TITLE
Wrong link in question mark on magento2 dashboard

### ISSUE THREAD

**Issue by itsolon** [magento/magento2#27193]
### Preconditions (*)
2.3.4 Magento 2.3.4 on php 7.3 and nginx mariadb

### Steps to reproduce (*)
1. klick on question mark on top of the dashboard beside the scope dropdown
![question-mark](https://user-images.githubusercontent.com/10437947/76095161-1ba13580-5fc4-11ea-8dcd-dc96f846252c.PNG)
![bad-request](https://user-images.githubusercontent.com/10437947/76095171-2065e980-5fc4-11ea-9a5d-3e4af8ee0c62.PNG)

### Expected result (*)
Show some info

### Actual result (*)
404 not found
because of an %s wich is inside the url i think this should be filled prior to delivery

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27193-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27193-2-4-develop.instances.magento-community.engineering/admin_2c90](https://i-27193-2-4-develop.instances.magento-community.engineering/admin_2c90)
Login: `f5e7cb27` Password: `da1fea70d91e`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @itsolon.
Can't able to reproduce the issue on latest instance
Thanks

**Comment by itsolon** [comment]
perhaps on 2.4 but it is on 2.3.4

**Comment by itsolon** [comment]
i can confirm that on 2.4 develop the issue is gone.
please excuse my question, are reports for 2.3.4 not important anymore?

**Comment by itsolon** [comment]
i installed fresh 2.3.4 with composer and the error is still there! 
new installation
please use 2.3.4 instead of 2.4
