### ISSUE TITLE
Unable to set loading order of css / scripts

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#27192]
Magento 2.3.4

You can't set the order in which CSS / Scripts are getting loaded.

For example I try to load "bootstrap" at the first place, otherwise if it will load later then it will override other CSS e.g. it changes the color of **a** (anchor tag) to blue and similar.

There is a module which tries to solve this, but does not work in my case.
https://github.com/quickshiftin/mage2-ordered-assets

**Comment by sdzhepa** [comment]
Hello @Eddcapone 

Thank you for feedback and proposal!

Based on the description [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) feel free to raise this topic on the next resources:

> Before creating an issue, please do the following:
> ...
>  * Make sure, that information you are about to report is a technical issue, please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for technical questions, feature requests, etc. These reports are not guaranteed to be processed within GitHub issue tracker.

**Comment by Eddcapone** [comment]
"Make sure, that information you are about to report is a technical issue"

It is obviously a technical issue.
