### ISSUE TITLE
Incorrect behave "Discard subsequent rules" and "Priority"  for the cart price rule

### ISSUE THREAD

**Issue by omaxmo** [magento/magento2#27202]
### Preconditions (*)

1. 2.3.4

### Steps to reproduce (*)

1. Create the first cart price rule:
        Rule Information:
            Active: Yes
            Coupon: No Coupon
            Priority: **0**
        Condition:
           Apply the rule only if the following conditions are met:
                if ALL  of these conditions are TRUE :
                       Subtotal  equals or greater than  200 
        Actions
            Apply: Percent of product price discount
            Discount Amount: 20
            Maximum Qty Discount is Applied To: 0
            Discount Qty Step (Buy X): 0
            Apply to Shipping Amount: No
            Discard subsequent rules: **No**
2. Create the second cart price rule
        Rule Information:
            Active: Yes
            Coupon: Specific Coupon
            Coupon Code: 777
            Priority: **1**
       Actions
            Apply: Fixed amount discount
            Discount Amount: 5
            Maximum Qty Discount is Applied To: 0
            Discount Qty Step (Buy X): 0
            Apply to Shipping Amount: No
            Discard subsequent rules: **Yes**
3. Add to cart products. Subtotal should be equals or greater than 200.
    The first rule was applying.
        Subtotal: $295.00
        Discount: -$59.00

4. Apply Discount Code: 777
    The first and second rules were applying
     Subtotal: $295.00
     Discount: -$84.00

### Expected result (*)

1. Only one rule should be applied

Based on documentation:
To stop processing other rules after this rule is applied, set Discard Subsequent Rules (Option toggle) to Yes. This setting prevents multiple discounts from being applied to the same product.

Prevents any other pricing rules that may apply to a product from being applied. Discarding subsequent rules means that, in the event that multiple pricing rules apply to the same product, only the pricing rule with the highest defined priority (in a rule’s Priority field) will be applied to the qualifying product. This prevents multiple pricing rules from stacking and providing unintended additional discounts.

The Priority setting is important when two cart rules/coupon codes are valid for the same product at the same time. The rule with the highest Priority setting (1 being the highest) will control the cart action. See Discard Subsequent Price Rules in the Define the Actions step.

### Actual result (*)

1. The first and second rules were applying

**Comment by omaxmo** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @omaxmo. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @omaxmo, here is your [Magento instance](https://i-27202-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27202-2-4-develop.instances.magento-community.engineering/admin_35a0](https://i-27202-2-4-develop.instances.magento-community.engineering/admin_35a0)
Login: `5a3e575e` Password: `719782c8f53f`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32346` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nidheesh-eglobeits** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nidheesh-eglobeits. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nidheesh-eglobeits, here is your [Magento instance](https://i-27202-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27202-2-4-develop.instances.magento-community.engineering/admin_979e](https://i-27202-2-4-develop.instances.magento-community.engineering/admin_979e)
Login: `3b98051c` Password: `461712ba89ba`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Foxtrot** [comment]
@omaxmo, this is not an issue. The first rule priority is higher than the second rule priority (0 < 1). Seems like documentation is not very clear. "The rule with the highest Priority setting (1 being the highest) will control the cart action." means priority 1 is higher than 2, 3, 4, etc.
