### ISSUE TITLE
Cannot create account when customer has no password, store id and website id set

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#27208]
### Preconditions (*)
1. Magento/product-community-edition 2.3.4
2. Custom theme without password required on registration form
3. Set Add Store Code to Urls to Yes in Configuration > Web

### Steps to reproduce (*)
1. Create account without password
2. Create account in default store view without store code in url

### Expected result (*)
1. Account is created

### Actual result (*)
1. Account creation fails because no store view is assigned to customer

Due to [this line of code](https://github.com/magento/magento2/blob/cac512ffe55578d41c33146c6fe03ef6bdf851ee/app/code/Magento/Customer/Model/AccountManagement.php#L886), it is impossible to create a customer account in the default store view without a password required in the registration form.

The store view is unset in the storemanager and requested right after, this obviously fails when creating a new account.

**Comment by gigadesign1** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gigadesign1. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gigadesign1, here is your [Magento instance](https://i-27208-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27208-2-4-develop.instances.magento-community.engineering/admin_64f8](https://i-27208-2-4-develop.instances.magento-community.engineering/admin_64f8)
Login: `e8b822b6` Password: `3f38c6dcfe43`
Instance will be terminated in up to 3 hours.

**Comment by gigadesign1** [comment]
Unable to reproduce on a vanilla Magento instance because it is not possible to disable required passwords on the registration form, but this feature is still available for custom themes.

**Comment by engcom-Delta** [comment]
Hi @gigadesign1 thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.4-develop as there is not possibility create customer without password from storefront. 
Seems like this issue is related to your custom modules.

If you'd like to update the issue with additional steps or code snippets, please reopen it.
