### ISSUE TITLE
"Add new group" enter button has different behavior then "OK"

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#27206]
### Preconditions (*)
1.  Having an attribute set

### Steps to reproduce (*)
1. Open the attribute set
2. press "Add new group"
3. Enter a name
4. press ENTER instead of using the mouse to press "OK"

### Expected result (*)
Same behavior as pressing "OK".

### Actual result (*)
The dialog is closed but the new groups is not added.
Same as pressing "cancel"

**Comment by YiffyToys** [comment]
How to answer the "yes"/"no" question?
The provided checkboxes can obviously not be clicked.

**Comment by eduard13** [comment]
Hi @YiffyToys, thank you for reporting this issue, but I think it's a duplicate of #26847 issue, as it is related to confirm widgets, and will be fixed in scope of #27029.
Thank you.

**Comment by YiffyToys** [comment]
Thanks. I did not find #26847 when searching because I was only focused on product attributes.
