### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by dhivya-picco** [magento/magento2#27207]
While i'm trying to create the google map using php and jquery. IT shows unexpected error
![locationtrack](https://user-images.githubusercontent.com/54543382/76201418-3a4c3a00-6219-11ea-9e4d-71dc421cdb3d.png)

**Comment by sudheers-kensium** [comment]
@dhivya-picco This is not core Magento error. So I am closing this issue.
