### ISSUE TITLE
I found no " Design" under my backend of the Magento2 about  |Stores | Configuration |General |

### ISSUE THREAD

**Issue by zhushaolei** [magento/magento2#27201]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
Hi @zhushaolei.
Could you please update all the details pre condition, steps to reproduce, expected and actual result.
Thanks

**Comment by krishprakash** [comment]
Hi @zhushaolei feel free to reopen the issue once you update all the necessary details
Thanks
