### ISSUE TITLE
Dependency php-amqplib/php-amqplib vs php extension sockets causes inconsistent composer.lock file

### ISSUE THREAD

**Issue by hostep** [magento/magento2#27200]
### Preconditions (*)
1. Magento 2.4-develop branch
2. PHP installation without the `sockets` extension installed

### Steps to reproduce (*)
1. Clone the 2.4-develop branch (I'm using commit 90012f2920a)
2. Run `composer install` => notice it doesn't work:
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-amqplib/php-amqplib v2.10.1 requires ext-sockets * -> the requested PHP extension sockets is missing from your system.
    - php-amqplib/php-amqplib v2.10.1 requires ext-sockets * -> the requested PHP extension sockets is missing from your system.
    - Installation request for php-amqplib/php-amqplib v2.10.1 -> satisfiable by php-amqplib/php-amqplib[v2.10.1].
```
3. Run `composer update php-amqplib/php-amqplib` => notice now it suddenly works:
```
$ composer update php-amqplib/php-amqplib
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 40 updates, 0 removals
  - Downgrading php-amqplib/php-amqplib (v2.10.1 => v2.7.3): Loading from cache
...
```

-- 

Now use a PHP installation which does have the `sockets` extension installed and try again:

1. Clone the 2.4-develop branch (I'm using commit 90012f2920a)
2. Run `composer install` => notice it works

### Expected result (*)
1. Since the php extension `sockets` at this time [is not required](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#required-php-extensions) for a Magento installation, I would expect that we can install Magento without it installed

### Actual result (*)
1. Can only install Magento without the `sockets` extension installed when running `composer update`, not when running `composer install`

### Discussion
1. The big problem is that we now have the following constraint defined: `"php-amqplib/php-amqplib": "~2.7.0||~2.10.0",` in the [`composer.lock` file](https://github.com/magento/magento2/blob/90012f2920a784a2f814a6e820dfc12ac96ebb19/composer.json#L48)
2. `php-amqplib/php-amqplib` version 2.7 does not need `sockets`, version 2.10 does need `sockets`
3. `php-amqplib/php-amqplib` requires the `sockets` extension [since version 2.8.1](https://github.com/php-amqplib/php-amqplib/pull/610/commits/d24fe0957d6294a03ee70ca5635f84909d33c961)

### Solutions

Here are some possible solutions:
1. Document that the `sockets` extension is required in the documentation and remove the constraint `~2.7.0||` from the `composer.json` file
2. If we don't want the `sockets` extension to become required for Magento, we should change the constraint to: `~2.7.0`
3. Make all developers of Magento use the exact same PHP installation (I know this is not realistic), so that when they run`composer update` it doesn't suddenly upgrade `php-amqplib/php-amqplib` to a version which might not work on other people's installations
(it was corrected in https://github.com/magento/magento2/commit/3d223517139#diff-1da2c7edc898c70e5a79a9997c98ceccL1392 and then changed again in https://github.com/magento/magento2/commit/9f14f895ac616d8a9c4aa5ed1cf2a657eff24814#diff-1da2c7edc898c70e5a79a9997c98ceccL1393)

**Comment by melnikovi** [comment]
Sorry for the delay in response. I think that it's ok to add dependency on `ext-sockets`. We already updated documentation to highlight this. Do you have anymore concerns or this issue can be closed?

**Comment by hostep** [comment]
Hi @melnikovi 

Yes, if `ext-sockets` becomes required, we should remove the version constraint `~2.7.0` for the `php-amqplib/php-amqplib` dependency in the [`composer.json` file](https://github.com/magento/magento2/blob/63a6786bd0c5bd18ecc75f42dbaa229708a4b8b3/composer.json#L73).

Otherwise when some Magento developer/contributor does not have `ext-sockets` installed and executes `composer update` it would downgrade the `php-amqplib/php-amqplib` again which leads to all unnecessary diffs in the `composer.lock` file and automatic tests suddenly using a different versions of that dependency again.

Do you agree?
I can send in a PR for this if you want.

**Comment by melnikovi** [comment]
Agree. Could you please submit PR to 2.4-develop branch? Thank you!

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35127` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lenaorobei** [comment]
Commit was cherry-picked and merge to 2.4.0 is in progress.

**Comment by hostep** [comment]
Closing since this was fixed in Magento 2.4.0, even though the `magento/framework-amqp` module still references the old constraints: `"php-amqplib/php-amqplib": "~2.7.0||~2.10.0"` but that doesn't really matter here.

Thanks @lenaorobei!

**Comment by Elamurugan-Nallathambi** [comment]
I understand this ticket closed, just posting this here so I don't have to define the issue again as duplicate issue. 
Am facing this problem in Magento 2.3.4 with php 7.3 environment. Is there a fix or patch that I can apply?

**Comment by hostep** [comment]
@Elamurugan-Nallathambi: what issue do you have exactly? Running `composer update` or `composer update php-amqplib/php-amqplib` will probably fix it.

**Comment by zackha** [comment]
Open the `php.ini` file, probably located in i.e. `xampp\php` or `wamp\bin\php\phpX.XX (where XX is version number)`

Search for `;extension=sockets` uncomment it (by removing the ; in front of it)
