### ISSUE TITLE
Issue with modules encoded by ioncube .

### ISSUE THREAD

**Issue by mihalkordowsky** [magento/magento2#27204]
### Preconditions (*)
    1. Magento/product-community-edition 2.3.4
    2. PHP 7.3
    3. ionCube 10.3.9

### Summary (*)
When I'm using ionCube Encoder for encoding of custom modules then Magento not generating classes correctly.
### Steps to reproduce (*)
    `sudo php bin/magento setup:di:compile`
### Examples (*)

I have few type of errors.

When I trying to extent \Magento\Framework\DB\Adapter\Pdo\Mysql

` public function query($sql, $bind = []) {
...
`
then I got error

`
PHP Fatal error: Declaration of Vendor\ModuleName\Framework\DB\Adapter\Pdo\Mysql\Interceptor::query($sql, $bind) must be compatible with Vendor\ModuleName\Framework\DB\Adapter\Pdo\Mysql::query($sql, $bind = ) in /var/www/magento/generated/code/Vendor/ModuleName/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php on line 7
`
The interceptor has incorrect function declaration .
`
/** * {@inheritdoc}
*/
public function query($sql, $bind) {
$pluginInfo = $this->pluginList->getNext($this->subjectType, 'query');
if (!$pluginInfo) {
return parent::query($sql, $bind);
} else {
return $this->___callPlugins('query', func_get_args(), $pluginInfo);
}
}
`

And second issue with injection of dependencies (Magento 2.*).

I'm trying to inject dependency into
Vendor\ModuleName\Block\Adminhtml\Form\Field\CustomFile

`
public function _construct(
\Magento\Backend\Block\Template\Context $context,
array $data = [] ,
\Vendor\ModuleName\Helper\License $license
) {
$this->_license = $license;
parent::_construct( $context, $data );
}
`

And I see this string in the logs.
`
main.CRITICAL: Missing required argument $data of Vendor\ModuleName\Block\Adminhtml\Form\Field\CustomFile. [] []
`

**Comment by bartoszkubicki** [comment]
I find this issue ridiculous. You want to obscure OPEN SOURCE code? Really? I don't know your motivation, but if you try to sell this module later, congratulations. Someone will get not fully functional module (there is no way to extend it or fix it if it is broken).

**Comment by gabrielmds85** [comment]
I had the same problem, but unfortunately this is not a Magento 2 issue, but instead an IonCube issue.
IonCube will not provide an accurate result for ReflectionParameter::isOptional() and ReflectionParameter::isDefaultValueAvailable() for functions inside encoded files before they're actually decoded and if the encoded file was not encoded with --allow-reflection-all option and if the caller file is not an encoded file.

Probably not the scope for this, but for anyone having this problem, a quick workaround:
-for block constructor-
remove "array" type from the parameter, leave only the parameter like `$data = []`
create the default value before calling the parent function:
`if ($data === null){ $data = []; }`

-for interception generation-
use a <preference for="Magento\Framework\Interception\Code\Generator\Interceptor"
overload method _getDefaultConstructorDefinition() and change parameters according to your needs like:
`foreach ($parameters as &$parameter)
{
	if (&& isset($parameter['type']) && $parameter['type'] == 'array' && !isset($parameter['defaultValue']))
	{
		$parameter['defaultValue'] = new \Zend\Code\Generator\ValueGenerator([], \Zend\Code\Generator\ValueGenerator::TYPE_AUTO);
	}
}`
