### ISSUE TITLE
[Question] Preference not working in di.xml 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2720]
Hi,

I have a custom module where I'd like to extend the Base Handler

```
<preference for="Magento\Framework\Logger\Handler\Base" type="Custom\Foo\Handler\DefaultHandler" />
```

Strangewise this does not work in this specifc case, while other preferences are working fine like

```
<preference for="Psr\Log\LoggerInterface" type="Custom\BarFoo\Handler\BaseLog" />
```

Thanks for clarification

Best

**Comment by Vinai** [comment]
See https://github.com/magento/magento2/issues/2674 for an explanation of why it isn't working.  

Also, the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.  
Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by ghost** [comment]
Hi Vinai,

thans for the response. I was not sure if this was a bug, thats why I flagged it with question, but the reference you send is exactly what I was looking for

Thanks a lot

**Comment by Vinai** [comment]
In future it probably would be best to first ask in the forums or on stackexchange, and then, should it look like it actually is a bug, to open an issue here on github.
I'm aware that currently this process has not yet been established, but we have been asked to help to get there as best as we can.
All the best!
