### ISSUE TITLE
Simple products not associated to config, shows up as options on the frontend

### ISSUE THREAD

**Issue by WinstonN** [magento/magento2#27219]
**Preconditions:**
Default Magento 2.3.3

**Description:**
When you remove a simple product via the admin panel, from a config product, the option for that simple product remains visible in list of options for the configurable

**Steps to reproduce:**
1. Default Magento 2.3.3
2. Log into admin and find any configurable
3. Remove a simple associated product from the configurable
4. Save
5. Run all indexes, clear all caches
6. BUG: The simple product option will still be displayed on the frontend when visiting the config product. The option will not be available but that is beside the point. The option should now show up in the list of options, in the first place

The same is true when you disable that simple product
**Actual Result:**
![image](https://user-images.githubusercontent.com/1143789/76275530-67b3e900-62e8-11ea-9608-d9cb0d4404b8.png)
![image](https://user-images.githubusercontent.com/1143789/76275543-6da9ca00-62e8-11ea-9d88-275eaed5fb56.png)
![image](https://user-images.githubusercontent.com/1143789/76275550-739fab00-62e8-11ea-9fc1-3d5fa6f6f078.png)

Expected result:
![image](https://user-images.githubusercontent.com/58288685/82652664-97ae2f80-9c3b-11ea-8766-82e547a57f33.png)

**Comment by WinstonN** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @WinstonN. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @WinstonN, here is your [Magento instance](https://i-27219-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27219-2-4-develop.instances.magento-community.engineering/admin_db86](https://i-27219-2-4-develop.instances.magento-community.engineering/admin_db86)
Login: `fadf62df` Password: `70c64ee66328`
Instance will be terminated in up to 3 hours.

**Comment by fooman** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fooman. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fooman, here is your [Magento instance](https://i-27219-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27219-2-4-develop.instances.magento-community.engineering/admin_3f63](https://i-27219-2-4-develop.instances.magento-community.engineering/admin_3f63)
Login: `504ff7fd` Password: `6ba1d896be12`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-27219-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27219-2-4-develop.instances.magento-community.engineering/admin_0f28](https://i-27219-2-4-develop.instances.magento-community.engineering/admin_0f28)
Login: `6192631f` Password: `2bf34a95993d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@WinstonN: Issue is not reproducible in Magento 2.4 develop instance
Please find the attachments below for your reference:

**Comment by swathishs** [comment]
Hi @WinstonN, thank you for your report. According to contributor's guide Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.
