### ISSUE TITLE
Allow the phpdoc type array

### ISSUE THREAD

**Issue by mlambley** [magento/magento2#27220]
### Preconditions (*)
Exists in Magento 2.4-develop. Note that phpdoc type `array` is not being included as an array type.
https://github.com/magento/magento2/blob/cac512ffe55578d41c33146c6fe03ef6bdf851ee/lib/internal/Magento/Framework/Reflection/TypeProcessor.php#L394-L397

### Steps to reproduce (*)
Create a class with a member variable with type `array` such as
```php
/** @var array */
protected $street;
```
Then try to encode/decode it using DataObjectProcessor/ServiceInputProcessor.

### Expected result (*)
I would expect it to be parsed as an array. Perhaps a sane default would be `string[]`.

### Actual result (*)
```
Class array does not exist

#0 magento/framework/Webapi/ServiceInputProcessor.php(242): ReflectionClass->__construct('array')
#1 magento/framework/Webapi/ServiceInputProcessor.php(480): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('array', Array)
#2 magento/framework/Webapi/ServiceInputProcessor.php(277): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, 'array')
#3 magento/framework/Webapi/ServiceInputProcessor.php(480): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('MyNamespace\\My...', Array)
```

**Comment by lbajsarowicz** [comment]
This is correct behaviour.
You need to explain what kind of data it has to expect inside (eg. array of strings, array of objects). With just `array` it's unclear for parser.
