### ISSUE TITLE
Uncaught TypeError in Customer Section config

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#27228]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Add to the body following code to the homepage content:
```html
<script>
    require(['jquery'], function (jQuery) {
        jQuery.ajax({
            url: window.location.protocol + '//' + window.location.hostname + '/',
            method: 'POST',
            data: {}
        });
    });
</script>
```

2. Navigate to homepage, with opened developer console

### Expected result (*)
1. We shouldn't have any JS errors

### Actual result (*)

1. We have `Uncaught TypeError: Cannot read property '*' of undefined` error in the console

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-27228-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27228-2-4-develop.instances.magento-community.engineering/admin_0c9f](https://i-27228-2-4-develop.instances.magento-community.engineering/admin_0c9f)
Login: `1a451655` Password: `b34b74506c41`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
Seems like not reproducing anymore on 2.4-develop branch. Fixed by https://github.com/magento/magento2/pull/25764
