### ISSUE TITLE
First approach issues (can't create Pages, Products or Design Configuration)

### ISSUE THREAD

**Issue by effettidesigns** [magento/magento2#27225]
I've always developed websites by using Wordpress+Woocommerce, now I'm trying to build a Magento2 website, so I'm new to this app.
Actually I've installed the latest version to this domain **magento.effettiadventure.com**
Later on I've installed this theme **Athlete2** https://themeforest.net/item/athlete2-strong-magento-2-theme/23693737
by copying the app and pub files into the app and pub directories.
Then I proceeded running into the hosting Terminal these lines:

`php magento.effettiadventure.com/bin/magento setup:upgrade
php magento.effettiadventure.com/bin/magento setup:di:compile
php magento.effettiadventure.com/bin/magento setup:static-content:deploy -f
php magento.effettiadventure.com/bin/magento cache:clean
php magento.effettiadventure.com/bin/magento cache:flush`

I had to increase  php memory limit from 128MB to 512MB.

Now in the backend the theme seems installed but when I check into Design Configuration, it looks empty without any information.
I can't even create pages or products and the overall loading of the panels seems a bit slow.

Can someone please help me better understand how Magento2 installation and configuration works and fix these beginner issues?

Thank you

**Comment by effettidesigns** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @effettidesigns. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @effettidesigns, here is your [Magento instance](https://i-27225-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27225-2-4-develop.instances.magento-community.engineering/admin_dbdd](https://i-27225-2-4-develop.instances.magento-community.engineering/admin_dbdd)
Login: `5d37ea51` Password: `b1e13ea8c7e8`
Instance will be terminated in up to 3 hours.

**Comment by effettidesigns** [comment]
> Hi @effettidesigns, here is your [Magento instance](https://i-27225-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-27225-2-4-develop.instances.magento-community.engineering/admin_dbdd
> Login: `5d37ea51` Password: `b1e13ea8c7e8`
> Instance will be terminated in up to 3 hours.

What should I do with this access?

**Comment by krishprakash** [comment]
Hi @effettidesigns. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Please refer [Magento stack exchange](https://magento.stackexchange.com/) or [Community forum](https://community.magento.com/) to discuss about this
Thank you !!
