### ISSUE TITLE
Search result page throws error on changing the URL

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#27232]
### Preconditions (*)

1. Magento 2.3.3 with sample data (or at least have some products in the site)
2. Elastic Search 6 installed in server and configured to use it in **Stores > Configuration > Catalog > Catalog > Catalog Search > Search Engine**

### Steps to reproduce (*)

1.  Visit the link: http://domain.com//catalogsearch/result/index/?color=black&q=jacket
2. http://domain.com//catalogsearch/result/index/?color=49&q=jacket

### Expected result (*)

1. Either link should not throw the error.
2. Should return products as per searched query.

### Actual result (*)

1. The first link throws an error, since **color=black** is not expected. Magento sends the value **black** to the elastic search and elastic search expects it to be **int** value.

### Suggested Solution
1. Magento should find the id of that **black** (which is 49) and then only send the request to elastic search
2. If above is not possible then Magento should simply return an empty result.

**Comment by adarshkhatri** [comment]
@magento give me 2.3.3-p1 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.3.3 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.3 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment]
@magento give me 2.4.1 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @adarshkhatri , I'm not able to reproduce issue by steps you described on 2.4-develop with sample data and Elastic Search 7
**Result:**
:heavy_check_mark: No errors per search query
![27232](https://user-images.githubusercontent.com/51681379/98565550-67744f00-22b6-11eb-9a13-ef2bd2f265cf.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
