### ISSUE TITLE
GitHub test instances have a broken search

### ISSUE THREAD

**Issue by fooman** [magento/magento2#27234]
### Summary (*)
Test instances have a broken search

### Examples (*)
1. request a test instance from Magento via github comment
2. enter a search term
3. note failure
![image](https://user-images.githubusercontent.com/455508/76372369-0b150480-63a2-11ea-9fc3-96f02bb1441e.png)

### Proposed solution
Not sure what the underlying error is.

**Comment by krishprakash** [comment]
Hi @fooman. This is not the magneto core issue.We only confirm issue which are reproduced on latest magento 2.3.4 and here it's issue with automated instance so will raise the query to community team and update you.Thank you for report !!

**Comment by sdzhepa** [comment]
Hello @fooman and @krishprakash 

Thank you for contribution and collaboration!

This issue is not related to Magento code but it related to Community Engineering team MDS(Magento Deploy System) tools,
It seems something went wrong during installation or post configuration.


I am going to investigate it right now. If it is possible to fix quickly, I will do it if not - will create an internal ticket into EngCom Jira backlog

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27234-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27234-2-4-develop.instances.magento-community.engineering/admin_e8c1](https://i-27234-2-4-develop.instances.magento-community.engineering/admin_e8c1)
Login: `ee4b9caf` Password: `0a1b18c817ce`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27234-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27234-2-4-develop.instances.magento-community.engineering/admin_7567](https://i-27234-2-4-develop.instances.magento-community.engineering/admin_7567)
Login: `e4a25256` Password: `efa1a6b32793`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
fyi: @fooman @krishprakash 
hotfix successfully applied
![qwe](https://user-images.githubusercontent.com/3409584/76439551-8b2f7000-638a-11ea-8200-34ce222a31e6.png)
