### ISSUE TITLE
 _typography.less gives error

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2723]
Attempting to build a theme using the UI library. Per the instructions on http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/using-fonts.html I have created a _typography.less file for custom fonts. This fails with the following.

```
Compilation from source:

frontend/mytheme/theme/en_US/css/styles-m.less

.font-face is undefined in /var/www/html/magento2/var/view_preprocessed/css/frontend/mytheme/theme/en_US/css/source/_typography.less
```

 _typography.less includes

```
.font-face(
  @family-name: 'latoregular',
  @font-path: '@{baseDir}fonts/lato/lato-regular-webfont',
  @font-weight: normal,
  @font-style: normal
);

.font-face(
  @family-name: 'latomedium',
  @font-path: '@{baseDir}fonts/lato/lato-medium-webfont',
  @font-weight: normal,
  @font-style: normal
);
```

**Comment by zanilee** [comment]
Hi, @jupiter01!

The documentation article is outdated a little bit. We've renamed all Magento UI library mixins and added "lib-" prefix to them. 

So try to use `.lib-font-face` instead of just `.font-face`

And we'll update the documentation, thank you. Internal ticket: MAGETWO-46947

**Comment by ghost** [comment]
Thank you.
