### ISSUE TITLE
Magento 2.3.4 .action-close broken when Multiselect is used in a modal

### ISSUE THREAD

**Issue by joris-ati4** [magento/magento2#27240]
### Preconditions (*)

1. Magento 2.3.4 and the default Magento Backend theme

### Steps to reproduce (*)

1. Create a modal form in the admin section with insertForm and add a multiselect uiComponent in the form
2. When the modal opens, add an element to the multiselect.

### Expected result (*)

1. The close button has to be next to the item name and included in the item element.

![Capture d’écran 2020-03-11 à 12 18 48](https://user-images.githubusercontent.com/11993569/76411682-95ee0300-6392-11ea-8edf-7c7d9495d853.png)

### Actual result (*)

1. The action-close button is broken because it inherits the CSS of the .action-close button of the modal

![Capture d’écran 2020-03-11 à 12 08 55](https://user-images.githubusercontent.com/11993569/76411537-50c9d100-6392-11ea-9b61-2885aa0ddc4e.png)

I will open a PR with the fix for this issue shortly

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42502` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
