### ISSUE TITLE
Checkout UI does not display discount based on payment method

### ISSUE THREAD

**Issue by kassner** [magento/magento2#2724]
Hi,

If you have a shopping cart rule that gives discount based on the payment method, when you're in the checkout frontend, changing the payment method won't update the right sidebar (the review block), so the user won't see the real grand total. The placed order has the right amount though. I couldn't find a javascript action to reload the review block.

Looks like this is a known issue since RC2, #2347 in `Cart price rule is not applied` section already mentioned that.

Thanks!

**Comment by ishakhsuvarov** [comment]
@kassner Thank you for reporting this issue.
We have internal ticket `MAGETWO-45339` to fix it.

**Comment by YevSent** [comment]
Fixed on develop branch and fix should be available in Magento 2.1.8.
