### ISSUE TITLE
 Whitelist Generation of tables and columns that are allowed to be edited by the declaration installer Log Errors

### ISSUE THREAD

**Issue by immuhammad** [magento/magento2#27241]
### Description (*)
 Whitelist Generation of tables and columns that are allowed to be edited by the declaration installer doesn't log any errors. The **db_whitelist_schema.json** file is not created automatically when running the `bin/magento setup:db-declaration:generate-whitelist --module-name=Vendor_Modulename` command because there’s an error in the etc/db_schema.xml file of the module.

### Expected behavior (*)
It should log or throw the error in the console 
### Benefits
1. The developer will know what is the error in its db_schema.xml file of the module.
2. The developer can fix the error easily.

### Additional information
Steps to produce:
1. Create a module **Vendor/Module**
2. Create a **db_schema.xml** file with an error
3. Run Command `bin/magento setup:db-declaration:generate-whitelist --module-name=Vendor_Modulename`
4. The command will be executed successfully **no error was logged or given in console**.

**Comment by malikahmed1996** [comment]
Hi there, I have submitted a PR for this feature. [Schema Log file](https://github.com/magento/magento2/pull/27243)

**Comment by malikahmed1996** [comment]
It already being done in Magento 2.4.x Magento/Developer/Console/Command/TablesWhitelistGenerateCommand.php Line-86
