### ISSUE TITLE
setup/*.xml Config Files Not Read During Setup

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#2725]
Some areas of the core code have config files defined for the "setup" area.  E.g., Magento_CmsUrlRewrite/etc/setup/events.xml.  However, these config files are not read during the command-line setup:upgrade operation.

Reproduction steps:
1. Create a module data upgrade script that saves a new CMS page.
2. Run "magento setup:upgrade".
3. Observe that, in the database, a new record exists in cms_page for the new page, but no new record exists in url_rewrite (which would normally occur when saving a new page in the admin).

The logic that is responsible for saving this URL rewrite record is in an observer defined in Magento_CmsUrlRewrite/etc/adminhtml/events.xml and Magento_CmsUrlRewrite/etc/setup/events.xml.  This works fine for the adminhtml area, but no setup area is ever loaded.

Areas are defined in di.xml in the "areas" argument of Magento\Framework\App\AreaList.  There are no di.xml files defining a "setup" item in this argument.  I have confirmed that, when running "magento setup:upgrade", the result of Magento\Framework\Config::getCurrentScope (which returns "frontend" when the area context is "frontend") is "global".

**Comment by mazhalai** [comment]
@CNanninga Thank you, we have created MAGETWO-46966 to fix it.

**Comment by mazhalai** [comment]
@CNanninga This issue has been fixed by the commits referenced above. 
Thank you for reporting this problem, please feel free to open a new issue if problems persist.
