### ISSUE TITLE
Dashboard lifetime sales incorrect

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#27251]
Lifetime sale totals are simply incorrect.

Even after updating lifetime statistics and trying "Reload data".

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Make sales
2. Check dashboard

### Expected result (*)

Accurate numbers.

### Actual result (*)

Incorrect numbers.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27251-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27251-2-4-develop.instances.magento-community.engineering/admin_6e41](https://i-27251-2-4-develop.instances.magento-community.engineering/admin_6e41)
Login: `77db2c3c` Password: `adbecd8bf684`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27251-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27251-2-4-develop.instances.magento-community.engineering/admin_1787](https://i-27251-2-4-develop.instances.magento-community.engineering/admin_1787)
Login: `0bf124e1` Password: `e2034242154c`
Instance will be terminated in up to 3 hours.

**Comment by nitish-ranjan05** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05, here is your [Magento instance](https://i-27251-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27251-2-4-develop.instances.magento-community.engineering/admin_797a](https://i-27251-2-4-develop.instances.magento-community.engineering/admin_797a)
Login: `66c17e88` Password: `b460a24b0b66`
Instance will be terminated in up to 3 hours.

**Comment by nitish-ranjan05** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05, here is your [Magento instance](https://i-27251-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27251-2-4-develop.instances.magento-community.engineering/admin_6451](https://i-27251-2-4-develop.instances.magento-community.engineering/admin_6451)
Login: `36b50dfb` Password: `3e8776a1ea19`
Instance will be terminated in up to 3 hours.

**Comment by nitish-ranjan05** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by sdzhepa** [comment]
Hello @engcom-Oscar 

Could you please recheck this issue on the latest `2.4-develop` code.
It seems as a misconfiguration issue or so but its not possible to define based on the description.
If the issue not actual for `2.4-develop` it should be closed

cc: @Zyles

**Comment by engcom-Oscar** [comment]
Hello @Zyles, thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Please, notice, that according https://docs.magento.com/user-guide/stores/admin-dashboard.html, Dashboard lifetime sales displays only summary of all completed orders.  
If you have some more details how to reproduce this issue on latest 2.4 Magento, feel free to update the description and reopen it.
