### ISSUE TITLE
Email template preview return 404 page

### ISSUE THREAD

**Issue by Jitheesh** [magento/magento2#27258]
### Preconditions (*)

1. Magento version 2.3.4
2. PHP version 7.2

### Steps to reproduce (*)

1. Create Email template
2. Click Preview button

### Expected result (*)

1. Email template preview should be displayed on popup if we click from grid
2. Email template preview  should be displayed on new tab

### Actual result (*)

1. Return 404 content on both pop-up and new tab

**Comment by Jitheesh** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh, here is your [Magento instance](https://i-27258-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27258-2-4-develop.instances.magento-community.engineering/admin_ef76](https://i-27258-2-4-develop.instances.magento-community.engineering/admin_ef76)
Login: `422367e2` Password: `65c721655373`
Instance will be terminated in up to 3 hours.

**Comment by Jitheesh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by toddhainsworth** [comment]
Hey @Jitheesh and @sdzhepa did you find a resolution for this? I suspect based on the activity that it's reproducible in 2.3 but not 2.3 - is that correct?
