### ISSUE TITLE
customer group is getting reset in Account Information page in the frontend

### ISSUE THREAD

**Issue by mahmood537** [magento/magento2#27254]
### Preconditions (*)
1. Magento 2.3.4
2. I am testing using Magento 2.3.4 with sample data

### Steps to reproduce (*)
1. In Magento admin: This value is set to 'General':
Stores > Configuration > Customers > Customer Configuration > Create New Account Options > Default Group
2. In Magento admin, I changed customer group for roni_cost@example.com to 'Wholesale'
3. I logged in to the frontend using roni_cost@example.com and then went to 'Account Information' page. I changed the name and then clicked 'Save'. Customer group for roni_cost@example.com was changed to the default group 'General'. That shouldn't happen. default customer group should only be set in create account page.

### Expected result (*)
1. Customer group should not change when a customer edit their information in account information page in the frontend.

### Actual result (*)
1. Customer group is changing to default group when a customer edits their information in account information page in the frontend. That shouldn't happen. default customer group should only be set in create account page.

**Comment by krishprakash** [comment]
Hi @mahmood537. Thank you for your report, seems issue is duplicate to #26908 and already open so closing this
