### ISSUE TITLE
StoreResolverInterface->getCurrentStoreId() taking huge amount of time to resolve current store ID in StoreManager.php

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#27256]
I'm seeing an issue where files being served via `pub/static` are each taking upwards of 12 seconds to load. 

I profiled the delay and discovered the `store.resolve` profiler event is taking an extremely long time to resolve the current store ID inside the file `vendor/magento/module-store/Model/StoreManager.php`:
![Screenshot](https://i.stack.imgur.com/5BjCo.png)

### Preconditions (*)

1. Magento 2.3.4
2. Migrated from Magento 1.9 with 1 active store and 3 other inactive/disabled stores

### Steps to reproduce (*)

1. Migrate from Magento 1.9 with 1 active store and 3 other inactive/disabled stores
2. Enable all caches but make sure you immediately delete/flush all cached assets
3. Try to fetch an un-cached file (e.g. JavaScript) from your theme via a `pub/static` URL
4. Watch the performance profiler and see performance suffer at the `store.resolve` event

### Expected result (*)

1. Page or file is served quickly without undue delay

### Actual result (*)

1. File takes over 12 seconds to be served due to huge delay with `store.resolve`  
Screenshot: ![Screenshot](https://i.stack.imgur.com/5BjCo.png)

**Comment by diamondavocado** [comment]
Some more information from brief research:

Looking at the code, this event is located in the `Magento\Store\Model\StoreManager` class:

        public function getStore($storeId = null)
        {
            if (!isset($storeId) || '' === $storeId || $storeId === true) {
                if (null === $this->currentStoreId) {
                    \Magento\Framework\Profiler::start('store.resolve');
                    $this->currentStoreId = $this->storeResolver->getCurrentStoreId();
                    \Magento\Framework\Profiler::stop('store.resolve');
                }
                $storeId = $this->currentStoreId;
            }
            if ($storeId instanceof \Magento\Store\Api\Data\StoreInterface) {
                return $storeId;
            }
    
            $store = is_numeric($storeId)
                ? $this->storeRepository->getById($storeId)
                : $this->storeRepository->get($storeId);
    
            return $store;
        }


  [1]: https://i.stack.imgur.com/5BjCo.png

`storeResolver` is an instance of `Magento\Store\Api\StoreResolverInterface`, the direct usage of which I notice has been [deprecated](https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/) by Magento, maybe because of performance issues.

Following the code further, it looks like Magento tries to determine the current store code from the current HTTP request, eventually ending up in `Magento\Store\App\Request\StorePathInfoValidator->getValidStoreCode()`.

However I haven't been able to find out why the performance is so poor.

**Comment by mrtuvn** [comment]
Not sure about this but i heard from internal core team already merged some commits fix performance issue after upgrade to 2.3.4. The fixes related with config module
Not availables in 2.3.4. Only in 2.4-develop
Not sure that can related to resolve store or not

**Comment by bencarlson** [comment]
I'm having a similar issue, over 30 seconds on store.resolve. Were you able to find a resolution to this? 
Thanks!

-Ben

**Comment by xpoback** [comment]
It's not 12 seconds in my case, but 500 ms for the home page in Magento 2.3.5 instead of 80 ms in Magento 2.2.10 are quite noticeable, and most of that time is consumed by store.resolve.

**Comment by GuillaumeBrook** [comment]
For other persons finding this issue even if its closed...

Actually store.resolve is the first `$resource->getConnection()` ever made by Magento.
It means that the connection to your DB takes time for some reason.
