### ISSUE TITLE
intl extension

### ISSUE THREAD

**Issue by devzer01** [magento/magento2#27267]
Let me first state that I am on Developer preview (Beta) version of Catelina `10.15.4 Beta` 

```the git branch 2.3```

running composer install on MacOS Catelina `10.15.4 Beta ` with php 7.3.11 builtin (not homebrew)
```composer install ```

Suggests that I should install/enable `intl` extension.

from what I see here http://pecl.php.net/intl that intl extension has been deprecated for a while. 

https://www.php.net/manual/en/book.intl.php

this is a bit confusing not only on the Magento side of the documentation but also on the PHP side of documentation, it's clear that intl ext was dropped from PHP 7 and superseded by another set of built-in functions. (I haven't used PHP in the last 6 years so excuse me if there is some ignorance on this matter on my part here) but can you please explain  Why is `ext-intl` is specified in composer.json if the intl support is now built into php7? This is a bit confusing. 

see here https://community.magento.com/t5/Installing-Magento-2-x/Missing-PHP-extension-intl-2019/td-p/135445 some suggest disabling it. Someone else has managed to install intl extension on 7.2 

I am not sure how they went past, 

```
/private/var/tmp/pear/temp/intl/intl_error.h:24:10: fatal error: 'ext/standard/php_smart_str.h' file not found
#include <ext/standard/php_smart_str.h>
```

because that is a clear not good for php7 error.

Once again for the sake of simplicity,

**Comment by devzer01** [comment]
This is a developer question I will try joining the slack group. thanks

**Comment by krishprakash** [comment]
Hi @devzer01 
The GitHub issue tracker is intended for Magento core technical issues only.
Please raise question at community forum or magento stack exchange about general discussion about this
Thanks!!
