### ISSUE TITLE
Configurable product, simple products not showing when 1 product is disabled

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#27262]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by dverkade** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dverkade, here is your [Magento instance](https://i-27262-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27262-2-4-develop.instances.magento-community.engineering/admin_6938](https://i-27262-2-4-develop.instances.magento-community.engineering/admin_6938)
Login: `78191695` Password: `70df14e8deaf`
Instance will be terminated in up to 3 hours.

**Comment by dverkade** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @dverkade, here is your [Magento instance](https://i-27262-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27262-2-3-4.instances.magento-community.engineering/admin_a2ff](https://i-27262-2-3-4.instances.magento-community.engineering/admin_a2ff)
Login: `22378c60` Password: `880f0c632738`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@dverkade - Can you please provide the Steps, Actual result and Expected result? I want to verify the issue.

**Comment by dverkade** [comment]
Verified this is not an issue on clean Magento installations.

**Comment by dverkade** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by dverkade** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3.4 instance for you
