### ISSUE TITLE
Dimension fields missing from new product

### ISSUE THREAD

**Issue by gabrielxavila** [magento/magento2#27272]
Hello I’m having issues when I create new products, and duplicate products, they do not show dimensions fields (length, width, or height). Image attached below for reference. 

Preconditions:
When creating new or duplicate products in Magento 2.3.3 dimensional fields, typically found under weight field, is missing. 

Steps to reproduce:
In Magento 2.3.3 admin page under catalog/products/add new products dimensional fields are missing. 

Expected result:
Expecting dimension attribute values for new products to appear when editing or creating new products
![3B69948E-C0FA-4027-8A5E-2A162244F4C1](https://user-images.githubusercontent.com/62120124/76572312-f22a5300-6476-11ea-99ed-6f0742a38826.png)

Actual result:
![C9E83B16-4DFC-41BD-A2F9-91CA00865B18](https://user-images.githubusercontent.com/62120124/76571684-492f2880-6475-11ea-9fb5-9d39b275f8ed.png)

**Comment by shikhamis11** [comment]
hello @gabrielxavila 
for showing any attribute on product creation It must be assigned in selected product's attribute set .. Please check once also reproduce the issue on magento instance and shre screenshots of magento instance

**Comment by gabrielxavila** [comment]
> hello @gabrielxavila
> for showing any attribute on product creation It must be assigned in selected product's attribute set .. Please check once also reproduce the issue on magento instance and shre screenshots of magento instance

Hello, and thank you for your input. Below is a screenshot of the attributes assignment page confirming that they are assigned. Thank you in advance for your help 
![B534B8EF-C517-411C-B5AF-C450445E571D](https://user-images.githubusercontent.com/62120124/76674664-2e40df00-656f-11ea-9c5e-22d0c48cd4fb.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27272-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27272-2-4-develop.instances.magento-community.engineering/admin_2f60](https://i-27272-2-4-develop.instances.magento-community.engineering/admin_2f60)
Login: `84b76d0e` Password: `d10f973fe13c`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @gabrielxavila 
I checked the issue on sample data magento installation the attributes are not displaying at product form as these attributes visibility are set to no

**Comment by gabrielxavila** [comment]
Products have been set to “yes” and still experiencing the issue.

**Comment by gabrielxavila** [comment]
> hi @gabrielxavila
> I checked the issue on sample data magento installation the attributes are not displaying at product form as these attributes visibility are set to no

Good afternoon, thank you for looking into the issue. I have turned the products data to visible and I am still not able to see the text fields on any of my products. Please advise
