### ISSUE TITLE
shop administrators cannot edit translations in production mode

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#27278]
### Preconditions (*)
1. Magento any version 2.3.4
2. Switch to production mode

### Steps to reproduce (*)
1. Switch magento to production mode
2. Try to activate inline translation. 

### Expected result (*)
1. The administrator is allowed to switch inline translation on. 

### Actual result (*)
Because the website is in production mode the developer tab is hidden from the administrator. Therefore he's unable to turn inline translation on. 

In my opinion this is more of a flaw than a designed feature even though Magento 2 has it designed like this. That's why I'm opening here instead of the feature requests area. I'm basing my assumption in the following that most people will agree on:

- merchants should have the ability to edit the text that appears on their website freely
- not all merchants are developers and they sometimes have very little knowledge about computers
- not all merchants have a developer employee in their workplace as the cost is high
- magento allows multilingual functionality out of the box
- it's entirely possible that they have an employee who speaks multiple languages and want to allow the employee just to handle translations. That's impossible to do if providing ftp access to edit translation files as there's no real ACL
- giving FTP access to an employee to edit csv files is not safe 
- switching the eshop back and forth from production mode to developer mode for translating text is very tedious and causes downtime that's unnecessary and also annoying the users. 
- it's not ethically correct to force merchants to pay web agencies hours of work because the merchant wants to try changing a few buttons in uppercase, title or lowercase for marketing purposes. We've heard a lot of ranting about this and as a developer I agree with the merchants in this. I always tell them they're correct, but there's nothing I can do and it puts me in a tough spot. 

### Suggestion
I would propose that the inline translation section settings should be moved to admin area or system area which is accessible to the admins or allow access to it in production mode at the current area. Magento 1 was a lot more user friendly than Magento 2 in this regard, so the current status feels like a downgrade rather than upgrade regarding multilingual capabilities.

Please see another issue that arose from this behaviour #18015 . I've had this happen to me as well because a junior dev forgot to turn it off. In that case the administrator cannot do anything about it.

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr, here is your [Magento instance](https://i-27278-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27278-2-4-develop.instances.magento-community.engineering/admin_b41b](https://i-27278-2-4-develop.instances.magento-community.engineering/admin_b41b)
Login: `3c41d5de` Password: `dc00906f2305`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment]
Cannot replicate on demo instance because it's not in production mode but default mode probably.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-27278-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27278-2-4-develop.instances.magento-community.engineering/admin_35a0](https://i-27278-2-4-develop.instances.magento-community.engineering/admin_35a0)
Login: `fe4fc531` Password: `aea2172b975f`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@ioweb-gr : Since the issue described is like a feature request because in production mode Inline translation is hidden.
Please refer the doc:  [Magento  user guide](https://docs.magento.com/user-guide/system/translate-inline.html)
Production mode:
![image](https://user-images.githubusercontent.com/58288685/85858033-85925480-b7d8-11ea-863f-d36af0e350bf.png)

Hello @sdzhepa:
This issue looks like a feature request. Could you transfer this issue to the Feature requests repository?

**Comment by swathishs** [comment]
@ioweb-gr : Thank you for your contribution and collaboration!
This issue is like a feature request.
So it is not for this tracker. for fast processing of this issue please create this on Community feature repository.
https://github.com/magento/community-features
