### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getTypeId() Magento 2.3.0

### ISSUE THREAD

**Issue by rk610** [magento/magento2#27282]
**Preconditions (*)**
Magento 2.3.0
Show Error after click ship only one product

![shi](https://user-images.githubusercontent.com/55425682/76616820-e0b27b00-654a-11ea-97d2-d22233291684.png)

**Actual result (*)**

> Fatal error: Uncaught Error: Call to a member function getTypeId() on null in /var/www/vhosts/xyz.com/httpdocs/vendor/magento/module-inventory-shipping-admin-ui/Model/IsOrderSourceManageable.php:71 Stack trace: #0 /var/www/vhosts/xyz.com/httpdocs/vendor/magento/module-inventory-shipping-admin-ui/Observer/NewShipmentLoadBefore.php(81): Magento\InventoryShippingAdminUi\Model\IsOrderSourceManageable->execute(Object(Squareup\Omni\Model\Sales\Order\Interceptor)) #1 /var/www/vhosts/xyz.com/httpdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryShippingAdminUi\Observer\NewShipmentLoadBefore->execute(Object(Magento\Framework\Event\Observer)) #2 /var/www/vhosts/xyz.com/httpdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\InventoryShippingAdminUi\Observer\NewShipmentLoadBefore), Object(Magento\Framework\Event\Observer)) #3 /var/www/vhosts/xyz.com/httpdoc in /var/www/vhosts/xyz.com/httpdocs/vendor/magento/module-inventory-shipping-admin-ui/Model/IsOrderSourceManageable.php on line 71

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27282-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27282-2-4-develop.instances.magento-community.engineering/admin_4d2f](https://i-27282-2-4-develop.instances.magento-community.engineering/admin_4d2f)
Login: `db8f785c` Password: `30c930c09ba5`
Instance will be terminated in up to 3 hours.

**Comment by rk610** [comment]
> @magento give me 2.4-develop instance

Hi

**Comment by magento-engcom-team** [comment]
Hi @rk610. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rk610, here is your [Magento instance](https://i-27282-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27282-2-4-develop.instances.magento-community.engineering/admin_44c4](https://i-27282-2-4-develop.instances.magento-community.engineering/admin_44c4)
Login: `45c3174f` Password: `70996d0119c0`
Instance will be terminated in up to 3 hours.

**Comment by rk610** [comment]
> Hi @rk610. Thank you for your request. I'm working on Magento 2.4-develop instance for you

@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rk610. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rk610, here is your [Magento instance](https://i-27282-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27282-2-4-develop.instances.magento-community.engineering/admin_f287](https://i-27282-2-4-develop.instances.magento-community.engineering/admin_f287)
Login: `e1390058` Password: `9fce6e7631f0`
Instance will be terminated in up to 3 hours.

**Comment by rk610** [comment]
> Hi @rk610. Thank you for your request. I'm working on Magento 2.4-develop instance for you
error https://prnt.sc/rgykp3

**Comment by uabassguy** [comment]
Also having this issue. Was anything done on this?

**Comment by yanncharlou** [comment]
Same problem here. Any news ?

**Comment by yanncharlou** [comment]
I've found what's happening : 
In some case, product may not exists. Typically when product was ordered then deleted from catalog.
In such case, in /vendor/magento/module-inventory-shipping-admin-ui/Model/IsOrderSourceManageable.php:71 , $orderItem->getProduct() return NULL.

It should be safe to update /vendor/magento/module-inventory-shipping-admin-ui/Model/IsOrderSourceManageable.php:71 from 

```php
            $productType = $orderItem->getProduct()->getTypeId();
            if (!$this->isSourceItemManagementAllowedForProductType->execute($productType)) {
                continue;
            }
```
to
```php
            $product = $orderItem->getProduct();
            if (is_null($product) || !$this->isSourceItemManagementAllowedForProductType->execute($product->->getTypeId())) {
                continue;
            }
```
The immediate and emergency workaround was to find the order_item in database with :
```sql
select * from sales_order_item soi
left join catalog_product_entity p on p.entity_id = soi.product_id 
where soi.order_id = 45;
```
and set product_id to an existing product id. (the missing one just recreated for example).

Hope it can help.

**Comment by yanncharlou** [comment]
@magento-engcom-team Can you reoppen issue ?
There is the way to reproduce :

- Place an order with at least one product from frontend
- Confirm payement from backend
- Delete one of the products ordered from catalog
- Try to ship order from backend. (It will fail)

Explanations of what's happening and patch proposal here : https://github.com/magento/magento2/issues/27282#issuecomment-639521590

Best regards,
Yann

**Comment by iphigenie** [comment]
This bug also prevents OPENING an old order in the admin, for example if orders were migrated using data migration tool
