### ISSUE TITLE
Custom category layout update not affecting products

### ISSUE THREAD

**Issue by codedge** [magento/magento2#27285]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a custom layout update

I created a file `catalog_category_view_selectable_276_noindexnofollow.xml` in `app/design/frontend/<VENDOR>/<THEME>/Magento_Catalog/layout`. That file should set noindex, nofollow for a certain category.

```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    </head>
</page>
```
So we imagine we have a category with ID `276`, named _Shirts_.

2. In Admin got to the category with ID `276` and select this update via the **Custom Layout update** dropdown. Please see that I also set **Apply Design to Products**.

![layout_update](https://user-images.githubusercontent.com/4409904/76662677-f80b5b80-657e-11ea-90f1-281fed0a5f76.png)

3. Go to a sub category of this former category and enable **Use parent category settings**. Additionally I enabled **Apply Design to Products** for this category as well.

This is a subcategory of _Shirts_, named _Soccer Shirts_.

![layout_update_sub](https://user-images.githubusercontent.com/4409904/76663067-29385b80-6580-11ea-94e8-a7276638d4ce.png)

4. In the frontend check  the `head` section of this three pages:

* Category page _Shirts_
* Category page _Soccer shirts_
* Product page of category _Soccer shirts_

### Expected result (*)

1. :heavy_check_mark: The category page _Shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`: 
2. :heavy_check_mark:  The category page _Soccer shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`
3. :heavy_check_mark:  The product page of a product of _Soccer shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`:

### Actual result (*)

1. :heavy_check_mark:  The two category pages do have the entry  `<meta name="robots" content="NOINDEX,NOFOLLOW">`
2. :x: The product page of the sub category _Soccer shirts_ does not have this entry

**Comment by codedge** [comment]
I don't know how I should reproduce this in a demo instance as I cannot create a custom XML layout file there.

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/issues/26901

**Comment by mrtuvn** [comment]
Not stale
I also can reproduced issue like description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40736` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by yangshuqiugithub** [comment]
Is this method used for custom CMS pages? What if you want to create multiple CMS pages with the same layout
