### ISSUE TITLE
Missing `customer_address_id` for Shipping Addresses in `sales_order_address`

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27280]
### Preconditions (*)
I'm not sure about the pattern when this occurs, yet. Trying to reproduce/investigate.

1. Magento 2.3.2

### Steps to reproduce (*)
_I Don't have clear steps to reproduce_

### Expected result (*)
1. When Customer place an order using the same address for Billing and Shipping, I expect that both will have the same `customer_address_id` entry for that order in `sales_order_address` table.

### Actual result (*)
1. Billing Address is set properly (`entity_id` from `customer_address_entity`)
2. Shipping Address have all data exactly the same that Billing Address has, except the fact `customer_address_id` is `null`.

### Comments
The Quotes assigned to the problematic orders also have `null` as `customer_address_id`, so the problem starts to appear on the stage of creating a new quote/updating quote.

**Comment by swathishs** [comment]
Hello @lbajsarowicz,
Thank you for your report.
This issue is duplicate to #https://github.com/magento/magento2/issues/28793 and already in rev for dev stage

Hence closing the issue
