### ISSUE TITLE
MFTF: Missing Test implementation

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27286]
### Preconditions (*)
All Magento Functional Testing Framework tests that are in repository `magento/magento2` should be implemented and working.

### Steps to reproduce (*)
N/A

### Expected result (*)
N/A

### Actual result (*)
Missing implementations for tests

https://github.com/magento/magento2/blob/cf29d0de077caae296bfc6151aecd4a9fd082d5a/app/code/Magento/AdminAnalytics/Test/Mftf/Test/TrackingScriptTest.xml#L11-L21

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz  thank you for your report. This test is not present in 2.4-develop
Closed as **Fixed**
