### ISSUE TITLE
Image role not set up when uploading image to a product vbia REST API

### ISSUE THREAD

**Issue by vincentteyssier** [magento/magento2#27293]
### Preconditions (*)
1. Magento 2.3.4
2. PHP 7.3

### Steps to reproduce (*)
1. Use the REST API to upload a image to a product as follow:
POST /V1/products/123456/media

```
{
"entry": {
    "media_type": "image",
    "label": "test",
    "position": 0,
    "disabled": true,
    "types": ["image"],
    "file": "test.png",
    "content": {
        "base64_encoded_data": 
 "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        "type": "image/png",
        "name": "test.png"
    }
}
}
```

Also tried with Disabled = false

### Expected result (*)
Image is assigned the "image" type in the backend and frontend

### Actual result (*)
No type is assigned to the image in frontend, however the get method returns the right type for that image.

Result from GET method :
{
        "id": 133,
        "media_type": "image",
        "label": "test",
        "position": 0,
        "disabled": true,
        "types": [
            "image"
        ],
        "file": "/t/e/test.png"
    }

Result in admin panel (no role is selected in the image details and the thumbnail in product image does not have any role assigned:
![image2](https://user-images.githubusercontent.com/16136533/76698178-2fbdf480-66a0-11ea-9aa2-878ddd9c5b3b.PNG)
![type](https://user-images.githubusercontent.com/16136533/76698181-351b3f00-66a0-11ea-9494-130b10752a4e.PNG)

I also try reindexing and flush cache but no luck

**Comment by vincentteyssier** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vincentteyssier. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vincentteyssier, here is your [Magento instance](https://i-27293-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27293-2-4-develop.instances.magento-community.engineering/admin_c524](https://i-27293-2-4-develop.instances.magento-community.engineering/admin_c524)
Login: `1b4ef16b` Password: `2e5ccd9bced5`
Instance will be terminated in up to 3 hours.

**Comment by vincentteyssier** [comment]
Not reproductible in 2.4-develop
