### ISSUE TITLE
Date filter in Sales > Orders does nothing

### ISSUE THREAD

**Issue by DaveSkirrow** [magento/magento2#27290]
### Preconditions (*)

1. 2.3.4

### Steps to reproduce (*)

1. In Sales > Orders, click filter. Then select a to and from date/ 
2. Click apply

### Expected result (*)

1. The orders displayed should only be between the dates selected

### Actual result (*)

1. Orders aren't filtered at all
![2020-03-14_1610](https://user-images.githubusercontent.com/61794963/76685817-909cec80-660e-11ea-855c-1fb3e96abd48.png)

**Comment by DaveSkirrow** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DaveSkirrow. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DaveSkirrow, here is your [Magento instance](https://i-27290-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27290-2-4-develop.instances.magento-community.engineering/admin_ae97](https://i-27290-2-4-develop.instances.magento-community.engineering/admin_ae97)
Login: `ba46b0a0` Password: `1d21efd9c04c`
Instance will be terminated in up to 3 hours.

**Comment by DaveSkirrow** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @DaveSkirrow. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @DaveSkirrow, here is your [Magento instance](https://i-27290-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27290-2-3-4.instances.magento-community.engineering/admin_2129](https://i-27290-2-3-4.instances.magento-community.engineering/admin_2129)
Login: `bf30a1c8` Password: `da0c9e9221f8`
Instance will be terminated in up to 3 hours.

**Comment by DaveSkirrow** [comment]
can't replicate on magento community server so I'm guessing it's a problem with my server
