### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in /home/viscodiesel/public_html/vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185

### ISSUE THREAD

**Issue by TheLaughingThird** [magento/magento2#27303]
### Preconditions (*)
Magento 2.3.3   (php 7.3 apache 2.4)

1. start with Magento 2.3.3   (php 7.3 apache 2.4)
2. Upgrade to 2.3.4 (php 7.3 apache 2.4)
3. Upgrading using composer CLI

### Steps to reproduce (*)

1. upgrade 2.3.3 to 2.3.4

List of disabled modules:
Magento_GoogleShoppingAds
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryRequisitionList
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryShippingAdminUi
Magento_InventoryGraphQl
Dotdigitalgroup_Email
Dotdigitalgroup_Chat
Klarna_Core
Klarna_Ordermanagement
Klarna_Kp

2. With these conditions
Upgrade to 2.3.4 (php 7.3 apache 2.4)
Upgrading using composer CLI

3. Go to Catalog -> Products    * Click on EDIT product*

### Expected result (*)
Editing screen will open

### Actual result (*)

1. When editing a product you get the message: 

Warning: Invalid argument supplied for foreach() in 
/vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185

**Comment by b2bdokter** [comment]
@magento give me 2.3.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @b2bdokter. Thank you for your request. I'm working on Magento 2.3.3-develop instance for you

**Comment by b2bdokter** [comment]
@magento-engcom-team

My issue is similiar to , but not exactly the same since my issue issue persistant regardless if Temando_shipping is active or disabled.
 https://github.com/magento/magento2/issues/25430

**Comment by advcha** [comment]
I found this variable `$this->mapProviders` is empty in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php file. This caused the problem. not sure what happened. I solved this problem by modifying the core magento file in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php. In `getMap` function, add this after `if (!$types) {...}`. So it'd be:

```
public function getMap(array $products, array $types): array
{
    if (!$types) {
        throw new \InvalidArgumentException('Types are required');
    }
   //FIX Warning: Invalid argument supplied for foreach() in /vendor/magento/module-catalog/Model/ProductLink/CollectionProvider.php on line 185
    if (!(is_array($this->mapProviders))) {
        $this->mapProviders = array(
            ObjectManager::getInstance()->create(LinkedMapProvider::class)
        );
    }
   ...
```
You need to import a few files as well on the top of this file:

```
use Magento\Catalog\Model\ProductLink\CollectionProvider\LinkedMapProvider;
use Magento\Framework\App\ObjectManager;
```
I know this fix is not clean as magento way. let me know if there is a better fix.
