### ISSUE TITLE
Wrong total calculation for multiple Bundle products with child with special price

### ISSUE THREAD

**Issue by Aquarvin** [magento/magento2#27305]
### Preconditions

1. Magento 2.3.3
2. PHP 7.2.22
3. Bundle product with children with special data

### Steps to reproduce

1. Create 3 simple products and set Special Price for them. Price - $10, special - $2
2. Create a Bundle product and add mentioned above 3 simple products as options
3. Go to the frontend to the Bundle Product page.
4. Check the price, should be $6
![Test Bundle product](https://user-images.githubusercontent.com/6350153/76807490-35752080-67ed-11ea-97bb-a70f11a2b391.png)
5. Add Bundle Product triple times. 
4. **IMPORTANT** Do not edit the Qty! Add one Bundle product to the cart, then one more time, then add bundle product the third time.

### Expected result

1. The cart shows One bundle product with qty 3, price $6, total $18.
2. Quote has 4 quote items: 1 bundle product and 3 simple products

### Actual result 

1. The cart shows One Bundle product with qty 3, but price $18, total $54
![Cart](https://user-images.githubusercontent.com/6350153/76807483-2aba8b80-67ed-11ea-991d-0b4a14d96e82.png)
2. Quote has 10 items: 1 bundle product and 9 simple products.
![Quote](https://user-images.githubusercontent.com/6350153/76807583-8258f700-67ed-11ea-81d3-e9c7922c6dc3.png)

### Investigation
`\Magento\Quote\Model\Quote::getItemByProduct($product)` returns false, so that create a new items, while it should.  Deeper investigation shows that `quote_item_option` saves the `value` of `bundle_selection_attributes`  as
 `{"price":"2.000000","qty":1,"option_label":"option 1","option_id":"12"}` . 
The wrong value here is the string type price value, it should be float. 
As a result, `\Magento\Quote\Model\Quote\Item::representProduct` returns false, since 
`$this->compareOptions($itemOptions, $productOptions)` fails. 
`{"price":"2.000000","qty":1,"option_label":"option 1","option_id":"12"}` is not equal to `{"price":2,"qty":1,"option_label":"option 1","option_id":"12"}`

Item has float value until collactTotals occurred. 
In `\Magento\Quote\Model\Quote\Address\Total\Subtotal::_initItem` at line 111 it calculates `$finalPrice`. And this value is being set as a string, not float.
I hope it helps to fix this.

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Aquarvin** [comment]
I can confirm the issue is not reproducible at least Magento 2.3.4 cloud
![image](https://user-images.githubusercontent.com/6350153/77315753-c3329d80-6d10-11ea-895a-f584acbf2b2d.png)

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-27305-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27305-2-4-develop.instances.magento-community.engineering/admin_9800](https://i-27305-2-4-develop.instances.magento-community.engineering/admin_9800)
Login: `c27d7235` Password: `13bc563ea6aa`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
On 2.4 it is not reproducible as well
