### ISSUE TITLE
Default Customer Group Ignored In Backend Customer Create

### ISSUE THREAD

**Issue by sprankhub** [magento/magento2#27318]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Create a new customer group with the name "10 test".
2. In the backend, go to Customers > All Customers.
3. Push "Add New Customer" button.

### Expected result (*)
1. Default customer group configured in `customer/create_account/default_group` is respected. In a default installation, the General customer group should be pre-selected in the customer form:

![image](https://user-images.githubusercontent.com/930199/76900179-221f8f00-6899-11ea-897d-5fde5f19e6c8.png)

### Actual result (*)
1. The newly created "10 test" customer group is pre-selected:

![image](https://user-images.githubusercontent.com/930199/76900223-395e7c80-6899-11ea-958e-9445f05da886.png)

Interestingly enough, if you create a new customer during the order-create-workflow, the right default customer group is pre-selected.

**Comment by sprankhub** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sprankhub. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by maheshWebkul721** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27318-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27318-2-4-develop.instances.magento-community.engineering/admin_fed8](https://i-27318-2-4-develop.instances.magento-community.engineering/admin_fed8)
Login: `2e6348df` Password: `20670f5a88cf`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @sprankhub. Not able to reproduce the issue as provided steps by you
Kindly provide more details to reproduce this issue
Thanks

**Comment by sprankhub** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sprankhub. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sprankhub, here is your [Magento instance](https://i-27318-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27318-2-4-develop.instances.magento-community.engineering/admin_7cb1](https://i-27318-2-4-develop.instances.magento-community.engineering/admin_7cb1)
Login: `35979b84` Password: `b59f02a1e7e6`
Instance will be terminated in up to 3 hours.

**Comment by sprankhub** [comment]
@magento give me 2.3 instance

**Comment by sprankhub** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @sprankhub. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sprankhub, here is your [Magento instance](https://i-27318-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27318-2-3-4.instances.magento-community.engineering/admin_88c2](https://i-27318-2-3-4.instances.magento-community.engineering/admin_88c2)
Login: `1732610a` Password: `12bff793fc1c`
Instance will be terminated in up to 3 hours.

**Comment by sprankhub** [comment]
Just reproduced on 2.3.4 and confirmed that it is fixed in 2.4-develop. https://github.com/magento/magento2/commit/9b178d0fbb4f3722680cb9f5c98c3a5ce99c878c#diff-5a84acef3517c087a0e6a164d0e2a9d1 seems to be the fix. This could be backported, but since it is not too critical, I close this now.
