### ISSUE TITLE
[TEST] DO not process. Testing internal tools

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#27317]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @VladimirZaets 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32502` were created

**Issue Available**: @VladimirZaets, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by nwmagento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nwmagento. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by nwmagento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nwmagento. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nwmagento, here is your [Magento instance](https://i-27317-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27317-2-4-develop.instances.magento-community.engineering/admin_0cce](https://i-27317-2-4-develop.instances.magento-community.engineering/admin_0cce)
Login: `10b8d7f7` Password: `3d2a5af65884`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27317-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27317-2-4-develop.instances.magento-community.engineering/admin_7aa2](https://i-27317-2-4-develop.instances.magento-community.engineering/admin_7aa2)
Login: `487330f3` Password: `abbe9c7af788`
Instance will be terminated in up to 3 hours.
