### ISSUE TITLE
Maximum Qty Allowed in Shopping Cart can be bypassed

### ISSUE THREAD

**Issue by gondas33** [magento/magento2#27326]
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. Go to a product -> Advanced Inventory -> set the value of 1 for Maximum Qty Allowed in Shopping Cart
2. Set quantity of 1 on the frontend product page and click add to cart multiple times( the qty will keep incrementing itself)

### Expected result (*)

1. This should force the customer to only be able to buy 1 qty of that product.
2. Error message shows when trying to increase the qty but nothing shows when clicking add to cart with the QTY set of 1.
3. https://prnt.sc/ri9cjc -> picture of the error when trying to increase qty

### Actual result (*)

1. I'm able to buy the same product 10 times or more, even if the maximum qty allowed in shopping cart is set to 1.
2.  https://prnt.sc/ri9dlo -> picture with qty of 3 when the maximum is set to 1 after pressing add to cart multiple times.

**Comment by an4rei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @an4rei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by an4rei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @an4rei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @an4rei, here is your [Magento instance](https://i-27326-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27326-2-4-develop.instances.magento-community.engineering/admin_3eaf](https://i-27326-2-4-develop.instances.magento-community.engineering/admin_3eaf)
Login: `f5be0319` Password: `4427ac757ac9`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27326-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27326-2-4-develop.instances.magento-community.engineering/admin_194b](https://i-27326-2-4-develop.instances.magento-community.engineering/admin_194b)
Login: `fc0c55d6` Password: `da5064df8f37`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @an4rei ,
I have verified this issue in the Latest Magento 2.4 Instance but not able to reproduce this issue in different scenario.
This issue may be related to the 2.3 Magento Instance.
**Please verify the below attached the video:**

![MagentoIssue](https://user-images.githubusercontent.com/24711761/77283577-b3a45c00-6cf2-11ea-8917-ad1b98fede0d.gif)

Thanks.

**Comment by ajijshekh123** [comment]
@an4rei - Please update your thought and verify this issue on latest Magento Instance.

**Comment by an4rei** [comment]
give me 2.4-develop instance

**Comment by an4rei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @an4rei. Thank you for your request. I'm working on Magento 2.4-develop instance for you
