### ISSUE TITLE
Base image not updating properly in image gallery

### ISSUE THREAD

**Issue by PurushothamanKrishnamoorthy** [magento/magento2#27329]
### Preconditions (*)

1. Magento 2.3.4
2. Create a configurable product with custom attribute _color_ of type "Visual swatch".

### Steps to reproduce (*)

1. Create a configurable product.
2. Assign base, thumbnail, and swatch to any of the simple product assigned to the configurable product.
3. Alter the base image for the simple product and reindex and flush the cache.

### Expected result (*)

1. The base image for the simple product should reflect the base image configured in backend.
2. Reference: https://drive.google.com/file/d/1jqIW4yVd0rfTm-yV1GBMm1P3Uhbhiowu/view

### Actual result (*)

1. The simple product retains the initially assigned base image.

**Comment by ajijshekh123** [comment]
Hi @PurushothamanKrishnamoorthy,
I have reproduced this issue as per your steps and video.
Thanks.

**Comment by XxXgeoXxX** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [Magento instance](https://i-27329-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27329-2-4-develop.instances.magento-community.engineering/admin_b3b2](https://i-27329-2-4-develop.instances.magento-community.engineering/admin_b3b2)
Login: `d74fd8ac` Password: `d1cc5c7bfaca`
Instance will be terminated in up to 3 hours.

**Comment by XxXgeoXxX** [comment]
I amn't able to reproduce this issue anymore on 2.4-develop branch.

**Comment by sdzhepa** [comment]
Based on https://github.com/magento/magento2/issues/27329#issuecomment-609008844

It s not possible to reproduce this issue on the latest `2.4-develop`
Probably issue was already fixed
