### ISSUE TITLE
Configurable product not showing all available options on PDP when a simple product is disabled

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#27330]
### Preconditions (*)
1. Magento 2.3.* (currently on 2.3.4)
2. PHP 7.2 and 7.3

### Steps to reproduce (*)
1. Make use of non-swatch color and non-swatch size attributes. (Default Magento comes with swatches attributes), basically change their type to Dropdown.
2. Add a configurable product with the following options:
- Color: Red
- Size: S, L and XL
3. You end up with 1 configurable product and 3 simple products.
4. Enable the S and XL simple product and set it to "In stock" with a quantity of 1 or higher.
5. Disable the L simple product.
6. Go to the product detail page.
7. Select the color Red, and attempt to select the size.

### Expected result (*)
1. All the sizes that are enabled are shown: S and XL.

### Actual result (*)
1. Only the size S is shown, XL is skipped due to an error of an undefined available product option that is still being passed partially for the size L.

### Also note
The options need to be sorted correctly, if L comes later than XL it will load S and XL which means it won't reproduce the error.
But if it follows alphabetical sorting it will attempt to load S, then L and then XL (in which loading L throws a javascript error and prevents the loading of subsequent options).

### Additional information (Edit of the original ticket)
Although this is a different situation in terms of steps to reproduce compared to the ones above this situation also gives the exact same error:

1. Make use of non-swatch color and non-swatch size attributes. (Default Magento comes with swatches attributes), basically change their type to Dropdown.
2. Add a configurable product with the following options:
- Color: Blue, Green, Red
- Size: S, L and XL
3. You end up with 1 configurable product and 9 simple products.
4. Enable all the simple products and set it to "In stock" with a quantity of 1 or higher.
5. Remove/unlink the simple product 'Blue' with the size S from the configurable product.
6. Remove/unlink the simple product 'Green' with the size L from the configurable product.
7. Remove/unlink the simple product 'Red' with the size XL from the configurable product.
8. Go to the product detail page.
7. Select the color Blue and attempt to select the size. (nothing is shown)
8. Select the color Green and attempt to select the size. (Only S is shown).
9. Select the color Red and attempt to select the size. (Only S and L are shown).

In short, what goes wrong is that in the following code an error occurs during selection of the color attribute: vendor/magento/module-configurable-product/view/frontend/web/js/configurable.js
Line 445 ~ 446: 
`                for (i = 0; i < options.length; i++) {
                    allowedProducts = prevConfig ? allowedProductsByOption[i] : options[i].products.slice(0);`
This code seems to assume that if a configurable product has a size of lets say S (0th element in the array of the 'options' variable) it should have a 0th element in allowedProductsByOption.
However this is not the case, as i showed in my above example, where Blue does not have S.

The reason this is NOT an issue when you make use of swatch attributes, is because the above file is not loaded/used.
Stranger though, is that if you make use of mixed dropdowns/swatches it will also not use the above file but only the swatch logic.
This would suggest that file that contains swatch logic also contains logic to work with dropdowns, and which in turn would suggest that the configurable.js is obsolete (merely my assumption).

**Comment by dverkade** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by stephan-cream** [comment]
Updated my initial post with an additional scenario and information after some more debugging.

**Comment by cdru** [comment]
This is the same issue as in #27482 and #26991 

Fix, though no elegant, is simple and can be found [here](https://github.com/magento/magento2/issues/26991#issuecomment-597709544)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @stephan-cream. Looks like issue has been fixed in 2.4 develop instance 
Kindly refer below screenshots as per issue scenario

![image](https://user-images.githubusercontent.com/46617848/94533347-a4cbd280-025c-11eb-828e-c1f5dbe330f5.png)

![image](https://user-images.githubusercontent.com/46617848/94533495-d2188080-025c-11eb-9ce7-64878b5d6c6e.png)

Also refer issue #26991 for more clarification
Please feel free to comment, reopen or create new ticket if you are still facing this issue on the latest 2.4-develop branch. Thank you for collaboration.
