### ISSUE TITLE
GET /V1/products/attributes/{attributeCode}/options only returns label value for Default View

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#2733]
When i request
/V1/products/attributes/{attributeCode}/options
It only returns label and value for Default View

``` json
[
 {
  "label":"abc",
  "value":"123"
 }
 {
  "label":"abcd",
  "value":"1233"
 }
]
```

In the documentation at http://devdocs.magento.com/swagger/
it should return something like this:

``` json
[
  {
    "label": "string",
    "value": "string",
    "sortOrder": 0,
    "isDefault": true,
    "storeLabels": [
      {
        "storeId": 0,
        "label": "string"
      }
    ]
  }
]
```

/Thomas

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @thomasnordkvist thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Comment by oefterdal** [comment]
I get the same in M 2.3.3 @vzabaznov
