### ISSUE TITLE
change logo size in cms page Layout Update XML textarea .

### ISSUE THREAD

**Issue by mayhem-ahmad** [magento/magento2#2734]
I'm trying to change the logo height and width from the cms page Layout Update XML textarea in the admin panel , by adding the following code But it's not working .

![screenshot from 2015-12-16 15 15 44](https://cloud.githubusercontent.com/assets/7792892/11841739/0e861978-a408-11e5-8686-51a1c13ad7c4.png)

your help is much appreciated .

Thanks!

**Comment by zanilee** [comment]
Hi, @mayhem-ahmad!

Thank you for reporting this issue! Internal ticket MAGETWO-46936

**Comment by magento-engcom-team** [comment]
@mayhem-ahmad, thank you for your report.
We've created internal ticket(s) MAGETWO-46936 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@mayhem-ahmad, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
