### ISSUE TITLE
Adminhtml - Too many mage-translation-file-version cookies

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#27355]
### Preconditions (*)
1. Magento 2.3.4 or 2.4-develop
2. Enable "Add Secret Key to URLs" in Stores > Configuration > Advanced > Admin > Security (enabling this option recommended for production env, it increases issue reproducing)

### Steps to reproduce (*)
1. Login into the admin
2. Go to few different pages
3. Open Chrome developer console, Network
4. Refresh the page
5. Select "document" request, see "Cookies" tab on the right side
6. check "show filtered out request cookies"
7. See list of cookies 

### Expected result (*)
1. Maximum one cookie `mage-translation-file-version` and `mage-translation-storage` should be created

### Actual result (*)
1. Almost for all admin URLs were created separate cookie `mage-translation-file-version` and `mage-translation-storage` because each of them has own path:
![image](https://user-images.githubusercontent.com/1873745/77143833-fb29ae80-6a8c-11ea-8ed3-866f178ccaf8.png)

### Additional info
After some time of navigation on the admin and frontend - browser reaches limit per domain (in chrome 180 cookies per domain) and drops older cookies. In my case it started dropping 2fa auth cookie, and I have to put 2fa code all the time when I log in into the admin

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

Pleeeese

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-27355-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27355-2-4-develop.instances.magento-community.engineering/admin_1b4f](https://i-27355-2-4-develop.instances.magento-community.engineering/admin_1b4f)
Login: `817f9294` Password: `e5c0db9f4785`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
Just updated issue description and added screenshot of reproducing this issue on test instance, to make issue more clear.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33896` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#27364 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [72567f6b7388a4e762da3ad9c3d96733b8f01e62](https://github.com/magento/magento2/commit/72567f6b7388a4e762da3ad9c3d96733b8f01e62)

The fix will be available with the upcoming 2.4.1 release.
