### ISSUE TITLE
Github issues were incorrectly closed and need to be re-opened

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#27368]
Posting this here because there's no other visible way to provide feedback or to contact the "moderators" of this repository.

Two issues have been incorrectly closed and at least one of them needs to be re-opened as they are still valid bugs in Magento 2.4:

1. https://github.com/magento/magento2/issues/10454 was closed because @engcom-Charlie could not reproduce the issue. However the issue is still present. They need to try reproducing the issue using the suggestions posted in the thread (using configurable product with only one configurable attribute). See #15047 below for more info.

2. https://github.com/magento/magento2/issues/15047 was closed because a now-deleted account said it was a "duplicate" of #10454, above. It may be the same issue but it is not a duplicate; it provides the instructions which @engcom-Charlie asked for; i.e. test a product with only one configurable attribute.

Some common sense is all that's needed here! 

As a Magento 2 developer I am finding it incredibly frustrating to work on this platform, finding bug after bug after bug, and then coming to this Github to find that bugs have been closed for the wrong reasons! It's maddening.

**Comment by ihor-sviziev** [comment]
@diamondavocado thank you so much for raising these issues again!
In both cases author of the issue should be able to re-open the issue if he/she not agree with person who tested it.

Were you able to reproduce this issue on test instance?
Will you be able to update this issue description with all needed details? Also I believe it's really hard to understand issue without screenshots / video. Will you be able do add some?

**Comment by ihor-sviziev** [comment]
@diamondavocado I've re-opened https://github.com/magento/magento2/issues/15047 and tried to reproduce it. Seems like this is expected result how it works right now.

Could you review my comment https://github.com/magento/magento2/issues/15047#issuecomment-602444182 and give your feedback?

I'm closing this issue.
