### ISSUE TITLE
Discount Amount not set for Quote Items

### ISSUE THREAD

**Issue by EmilsM** [magento/magento2#27366]
### Preconditions (*)

1. Magento Community 2.3.3

### Steps to reproduce (*)

1. Create a simple product, add it to a category, enable it and set it to be in stock
2. Add a special price to the product
3. Go to the frontend, find the product and add it to the cart

### Expected result (*)

1. In cart summary, to show a "Discount" field with the discount amount

### Actual result (*)

1. It assumes the Special price to be the base price
2. No "Discount" field in the cart summary
3. http://i.imgur.com/HzKimY1.png

**Comment by EmilsM** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @EmilsM. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @EmilsM, here is your [Magento instance](https://i-27366-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27366-2-4-develop.instances.magento-community.engineering/admin_a5fc](https://i-27366-2-4-develop.instances.magento-community.engineering/admin_a5fc)
Login: `520c3016` Password: `96a6ffa7a9c7`
Instance will be terminated in up to 3 hours.

**Comment by EmilsM** [comment]
Confirmed to be an issue on 2.3.3 and 2.4.x.

**Comment by aligent-lturner** [comment]
I don't think this is an issue. The discount amounts are used for promotions (e.g. cart price rules), and are subtracted from the price of the item, which in this case would be the special price.
For example, in this screenshot:
![image](https://user-images.githubusercontent.com/40189797/77125802-e94d0900-6a96-11ea-8881-4eb3c01754a5.png)

The product has a price of $29.99, and a special price of $19.99.
There is also a discount of $1.00 from a cart price rule, which makes the row total $18.99

**Comment by krishprakash** [comment]
Hi @EmilsM. Thank you for your report.
This is default magento behavior and not an issue. Discount should display once you apply cart price rule. You can see the discounted price in product view page
