### ISSUE TITLE
Magento 2.3.4 Display Stock (Only X Left) Even when Negative

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#27361]
### Preconditions (*)

1. Magento 2.3.4
2.

### Steps to reproduce (*)

1.Add Product and Set Inventory to 0 or Negative
2.Navigate to Stores->Configuration->Catalog->Inventory
3.Display Out of Stock Products->Yes
4.Only X left Threshold->10000
5.Display Products Availability in Stock on Storefront-> Yes
6. Manage Stock->Yes
7.Backorders->Allow Qty Below 0 and Notify Customer

### Expected result (*)

1. When Product Inventory is 0 or Negative, Product is switched to Out of Stock, but the customer can still order since Backorders are allowed

### Actual result (*)

1. Product is still listed as In Stock, but a notification on the Cart page says it will be backordered.

I would prefer to have the Only X Left displayed even when the Inventory is Negative. Or the product listed as Out of Stock but still be able to order the products with Backorders allowed.

**Comment by mohanelamurugan** [comment]
So what's expected behaviour ?
To have only the X Left displayed even when the Inventory is Negative. 
(Or) 
The product listed as Out of Stock but still to be able to order the products with Backorders allowed.

**Comment by trucatchtraps** [comment]
Ideally either or both would work, which let the customer know that the product is Out of Stock and more will need to be produced/procured before shipment.

**Comment by mohanelamurugan** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mohanelamurugan. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mohanelamurugan, here is your [Magento instance](https://i-27361-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27361-2-4-develop.instances.magento-community.engineering/admin_bf76](https://i-27361-2-4-develop.instances.magento-community.engineering/admin_bf76)
Login: `27d3855a` Password: `3426cac21188`
Instance will be terminated in up to 3 hours.

**Comment by mohanelamurugan** [comment]
Reproduced on 2.4.x

**Comment by trucatchtraps** [comment]
Correct, but I feel that is too late for the notification. The customer should know before they click Add to Cart. Otherwise, when they get to the Cart page, they may second guess the purchase based on the product now being on backorder. It is very confusing seeing a product listed as In Stock but yet it is backordered.

**Comment by mohanelamurugan** [comment]
So Instead of Instock, It would be ideal to show "Backorder" ?

**Comment by trucatchtraps** [comment]
It would probably be easier to have it switch from In Stock to Out of Stock based on the current code, like it does if you do not allow backorders. But have the Add to Cart button available if you allow backorders. Adding Backorder as a Stock option would likely be a more involved change.

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27361-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27361-2-4-develop.instances.magento-community.engineering/admin_caa4](https://i-27361-2-4-develop.instances.magento-community.engineering/admin_caa4)
Login: `a9125d0b` Password: `ec1f0da4ee97`
Instance will be terminated in up to 3 hours.

**Comment by mohanelamurugan** [comment]
@sudheers-kensium I have been working on this issue and gonna PR soon.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33015` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mohanelamurugan** [comment]
With MSI, Even the normal Only X left threshold doesn't work.

**Comment by magento-engcom-team** [comment]
Hi @trucatchtraps. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33015` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
