### ISSUE TITLE
Can't change design of store view in "configuration"

### ISSUE THREAD

**Issue by bossbom** [magento/magento2#2737]
All new store view have same design of "Default store view" on frontend.

I install a fresh Magneto CE2 with sample data downloaded on magento.com
I create a new store view named "French". Now I have two store view : "Default store view", "French"
I disable all cache.
I go to "Stores" -> "Configuration" -> "Design", change design of "French" to "Mangento/Blank", change design of "Default store view" to "Magento/luma".
Go to homepage and change store to "French" but it show "Magento/luma" theme.
If you change "Default store view", "French" store will follow it on frontend.

**Comment by antboiko** [comment]
Hello @bossbom , I've tried to reproduce this issue but no success. What is the result with enabled cache? Could you please provide me with screenshots of "Design Theme" section for both store views you have?

Thanks.

**Comment by bossbom** [comment]
Hi antboiko,

I setup a demo on this link: 
http://45.63.123.198/magento2/
http://45.63.123.198/magento2/admin
user: admin
pass: demo123
This is a fresh install with sample data.

**Comment by MomotenkoNatalia** [comment]
@bossbom Any updates on this?

**Comment by antboiko** [comment]
Hi @bossbom, could you please give us an update on this?

Thanks,
Anton.

**Comment by MomotenkoNatalia** [comment]
As there are no new updates from reporter, issue can be closed.
