### ISSUE TITLE
Customer can place order simple product which has visibility: Not Visible Individually 

### ISSUE THREAD

**Issue by KiuNguyen** [magento/magento2#27380]
### Preconditions (*)

1. Magento 2.3.4, Magento 2.4-develop
2. A simple product which has visibility: Catalog, Search

### Steps to reproduce (*)

1. Login customer
2. Go to the product page, add to cart a simple product
3. Logout
4. Go to admin, change product visibility: Not Visible Individually 
5. Login customer again, go to shopping cart

### Expected result (*)

1. When customer go to the shopping cart, they should see the error message: "product not available"

### Actual result (*)

1. customer can checkout and place order simple product which has visibility: "Not Visible Individually" with no error

**Comment by KiuNguyen** [comment]
@magento I am working on it

**Comment by KiuNguyen** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @KiuNguyen. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @KiuNguyen, here is your [Magento instance](https://i-27380-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27380-2-4-develop.instances.magento-community.engineering/admin_1814](https://i-27380-2-4-develop.instances.magento-community.engineering/admin_1814)
Login: `0c388c06` Password: `5a5faf262964`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27380-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27380-2-4-develop.instances.magento-community.engineering/admin_df70](https://i-27380-2-4-develop.instances.magento-community.engineering/admin_df70)
Login: `7796c9c5` Password: `b48f1e615456`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @KiuNguyen. This is expected and correct behavior of magento not an issue
So closing this as non issue
