### ISSUE TITLE
Magento 2.3.4 decimals in wishlist not showing

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#27389]
### Preconditions (*)

1.  Magento 2.3.4

### Steps to reproduce (*)

1.  Go to product and make quantity 1,3
2.  Add product to wishlist

### Expected result (*)

1. Wishlist item qty 1,3

### Actual result (*)

1. Wishlist item qty 1

**Comment by Jilco** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-27389-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27389-2-3-4.instances.magento-community.engineering/admin_4fa6](https://i-27389-2-3-4.instances.magento-community.engineering/admin_4fa6)
Login: `03bbba4d` Password: `883a0b5457cc`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
Figured out that it was in a custom module
