### ISSUE TITLE
Configurable product - can not use custom options

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#2739]
it shows 'We can't save custom-defined options with price type "percent" for configurable product.' even when the price type is 'fixed'. Please check this.

**Comment by tanya-soroka** [comment]
Hello @dexteritycc , thanks for reporting this issue. Could you please tell us which version do you use?

**Comment by dexterityzx** [comment]
Magento 2 (Community Edition) 2.0.0

**Comment by dexterityzx** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/13892193/11874364/377b5028-a4ad-11e5-9595-51dd2b0f1600.png)

**Comment by jialing1000** [comment]
I'm on Magento 2 (Community Edition) ver.2.0.2, has the same issue. 

I have to work around it by removing the configurations of that product, let it turned back to simple product. Then, apply the custom options beforehand, then, to update it to configurations.

**Comment by davidverholen** [comment]
we have the same Problem on Magento 2.0.4.

Our Customer created a simple Product with Custom Options. After that he created Configurations and the Product became a configurable Product.

Now when opening the Custom Options tab, we get this error Message:

> We can't save custom-defined options with price type "percent" for configurable product.

When I try to save the Product, the following Error Message is shown:

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db-3`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DELETE C), query was: UPDATE `catalog_product_entity` SET `attribute_set_id` = ?, `type_id` = ?, `sku` = ?, `has_options` = ?, `required_options` = ?, `created_at` = '2016-04-27 09:17:59', `updated_at` = '2016-04-28 08:38:26' WHERE (`entity_id`=46)

Edit: The second Problem actually seems to be another issue. It's trying to update attribute_set_id to 0 which does not exist. I'll try to invesitgate and add a new issue for this

**Comment by vzabaznov** [comment]
Please try to check fresh magento version.
If the problem still actual, please, specify it and create new bug.

**Comment by vzabaznov** [comment]
Hi, @dexteritycc thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Comment by gesell** [comment]
Hi. I also have this issue in CE 2.1.0. Will Percentage Price be available in future for config. products?

Regards

**Comment by sumihiro** [comment]
Hi, @vzabaznov 
I have same issue in CE 2.0.9.
When I try to update my configurable item, I get "We can't save custom-defined options with price type "percent" for configurable product." error.

<img width="982" alt="2016-08-29 13 41 51" src="https://cloud.githubusercontent.com/assets/98380/18040967/5f32078c-6dee-11e6-8d26-ea314eb49ff6.png">

How can I update it?

**Comment by pboisvert** [comment]
@gesell @sumihiro i have reopened the ticket but we will need someone to provide full information per the reporting guidelines to allow us to reproduce the issue.

**Comment by sumihiro** [comment]
@pboisvert thanks, please give a link to the reporting guidelines.

**Comment by pboisvert** [comment]
@sumihiro when you click the "New issue" button you will see placeholder text that is intended as a template for bug reporting including preconditions and steps to reproduce.

**Comment by sumihiro** [comment]
@pboisvert This is my report.

### Preconditions




1. Amazon Linux AMI
2. PHP 5.6.24
3. MySQL 5.6.30 MySQL Community Server
4. (by composer info) magento/magento2-base 2.0.9 Magento 2 Base (Community Edition)

### Steps to reproduce
1. Create an attribute set with attribute with color, named "Test Color".
   <img width="766" alt="2016-08-29 14 00 55" src="https://cloud.githubusercontent.com/assets/98380/18041262/d3f5c722-6df1-11e6-8d1e-fcf8a10e6358.png">
2.  Create a New Product, and select "Test Color" attribute set.
   <img width="972" alt="2016-08-29 14 07 50" src="https://cloud.githubusercontent.com/assets/98380/18041273/14431460-6df2-11e6-844e-f9d111203b80.png">
3. Make Configurations with "color" attribute.
   <img width="999" alt="2016-08-29 14 01 41" src="https://cloud.githubusercontent.com/assets/98380/18041291/38056d6c-6df2-11e6-811b-853c045a1935.png">
4. Add a custom option, set "Input Type" to "Area".
   <img width="982" alt="2016-08-29 14 00 23" src="https://cloud.githubusercontent.com/assets/98380/18041300/4c78cc62-6df2-11e6-95c7-a22c9807e660.png">
5. Push "Save" button.

### Expected result
1. This product will be saved.

### Actual result
1. Custom option got error message, "We can't save custom-defined options with price type "percent" for configurable product.". And never be saved.

<img width="982" alt="2016-08-29 13 41 51" src="https://cloud.githubusercontent.com/assets/98380/18041338/ac7ddac6-6df2-11e6-880f-8835445d730f.png">

**Comment by sumihiro** [comment]
@pboisvert  Oops, I fix my report.
The Product is saved, but never updated with error message, "We can't save custom-defined options with price type "percent" for configurable product.".

**Comment by artem-dryha** [comment]
I facing that issue too. Now trying to set up custom options for configurable product and even with price type "fixed" I get the message "Invalid Option Value".

Currently using 2.1.1 version

**Comment by TomoNZ** [comment]
Does anyone actually fix these issues? There seems to be hundreds of unresolved issues on this forum for MAgento2. Maybe it's too early to migrate from Magento1 to Magento 2!!!

**Comment by HugoRojasExplogic** [comment]
Same issue here, after a product it's edited and updated. 
There's no way to add custom option. The product has to be deleted and re-created in order to get all product properties desired

**Comment by magento-engcom-team** [comment]
@dexterityzx, thank you for your report.
We've created internal ticket(s) MAGETWO-82379 to track progress on the issue.

**Comment by vishalnyati** [comment]
Hello Team ,
We are using Magento v2.2.1  and still getting the same issue . Can we expect any solution soon. 
Issue is still open even after more than year.
![picture998-1](https://user-images.githubusercontent.com/5891042/35195943-2560d804-fef1-11e7-8c9c-166018538344.png)

**Comment by pbaum83** [comment]
I found another thread with I believe to be the same or similar issue:
https://github.com/magento/magento2/issues/2989

Using Magento Enterprise 2.2.2 and are experiencing problems after creating a product.

**Comment by simonmaass** [comment]
is there a solution yet - having the same issue in magento 2.2.5 - a configurable product with variations and if u try to create customizable options in the configrable product you get the following error:

![unbenannt](https://user-images.githubusercontent.com/32599710/43518696-2111fb92-958d-11e8-8c40-45f3e7dc5141.png)

**Comment by ghost** [comment]
We were not able to reproduce this issue. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation

**Comment by kennysinkeler** [comment]
Does anyone have a (quick) fix?
I have the same problem on 2.4.2
