### ISSUE TITLE
Magento 2.3.4 ad item to wishlist with default value below 1

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#27396]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Add product with default value 0,5 (eg. meters) - Minimum Qty Allowed in Shopping Cart
2. Log in with account in frontend
3. Go to product and add to wishlist

### Expected result (*)

1.  Quantity in wishlist is 0,5

### Actual result (*)

1. Quantity in wishlist is 1

![stap1](https://user-images.githubusercontent.com/23727130/77299640-14309a80-6ced-11ea-9fbe-f776da482874.jpg)
![stap2](https://user-images.githubusercontent.com/23727130/77299661-1a267b80-6ced-11ea-8f0c-307951aa9751.jpg)

**Comment by Jilco** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-27396-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27396-2-3-4.instances.magento-community.engineering/admin_a0e6](https://i-27396-2-3-4.instances.magento-community.engineering/admin_a0e6)
Login: `12cce795` Password: `165098b0d860`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
Reproduced
![stap1](https://user-images.githubusercontent.com/23727130/77299640-14309a80-6ced-11ea-9fbe-f776da482874.jpg)
![stap2](https://user-images.githubusercontent.com/23727130/77299661-1a267b80-6ced-11ea-8f0c-307951aa9751.jpg)

**Comment by Jilco** [comment]
Also when adjusting default value to 1,5 a amount lower than 1,5 is not in wishlist, like 1,2
![stap3](https://user-images.githubusercontent.com/23727130/77300077-c36d7180-6ced-11ea-8ff1-90d80e49fb3c.jpg)
![stap4](https://user-images.githubusercontent.com/23727130/77300087-c700f880-6ced-11ea-8dfa-59359579ce65.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32643` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Jilco** [comment]
Is there some progress? Because the wishlist is not useable now :-(

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
