### ISSUE TITLE
add canonical tag als to CMS and BLOG pages (actually all pages)

### ISSUE THREAD

**Issue by seansan** [magento/magento2#274]
Add canonical tag als to CMS and BLOG pages (actually all pages)

Duplicate content is not very good for seo. Would be good if Magento could actually ALWAYS on every page check for the base url and use the canonical tag. 

We can already set the canonical tag for products and categories, but not yet for other pages. Now we see duplicate content for these pages

http://magefox.com/blog/adding-canonical-url-to-cms-pages.html
http://magentoportico.com/blog/website-design/add-canonical-urls-to-magento-cms-pages/
http://www.mathewporter.co.uk/magento-canonical-meta-tag-on-cms-pages/
http://www.magentocommerce.com/wiki/adding_canonical_url_to_cms_pages

How about we add this to core? Magento 1.8 and/or2.0

**Comment by verklov** [comment]
According to the new procedure, we are closing the ticket here that has a related ticket in out internal tracker. We are having this improvement on our radar.
ID: MAGETWO-23730

**Comment by sankalpshekhar** [comment]
Not sure, where we currently are over this request, but this definitely is a feature needed when we have multi-website setup, and CMS pages are shared across them.

**Comment by tkacheva** [comment]
We are having this improvement in our CMS backlog. Follow the updates.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/add-canonical-tag-als-to-CMS-and-BLOG-pages-actually-all-pages/idi-p/46866).
