### ISSUE TITLE
`/V1/inventory/stock-source-links` API endpoint requires `ALL` Resource Access 

### ISSUE THREAD

**Issue by vbyno** [magento/magento2#27402]
Magento 2.3.1

### Summary (*)
`GET /V1/inventory/stock-source-links` REST endpoint is not allowed by `Catalog` or `Stores` permissions.

### Examples (*)
Here is the set of permissions I have:
![image](https://user-images.githubusercontent.com/2923624/77335353-b3c24d00-6d2e-11ea-84c8-b267bea3b071.png)

On retreiving the endpoint `GET /V1/inventory/stock-source-links` I'm getting this exception:
```
The consumer isn't authorized to access %resources.","parameters":{"resources":"Magento_InventoryApi::stock_source_link"}
```
I'm getting the expected responce only when I grant "all" Resource Access.

### Proposed solution
Either add required permission to the documentation, or control the endpoint by `Stores -> Inventory` permission

**Comment by vbyno** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vbyno. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vbyno, here is your [Magento instance](https://i-27402-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27402-2-4-develop.instances.magento-community.engineering/admin_b55c](https://i-27402-2-4-develop.instances.magento-community.engineering/admin_b55c)
Login: `8e01c20d` Password: `50fd545925b0`
Instance will be terminated in up to 3 hours.

**Comment by vbyno** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vbyno. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vbyno, here is your [Magento instance](https://i-27402-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27402-2-4-develop.instances.magento-community.engineering/admin_5e01](https://i-27402-2-4-develop.instances.magento-community.engineering/admin_5e01)
Login: `2fc49d19` Password: `f7a3725d1334`
Instance will be terminated in up to 3 hours.

**Comment by vbyno** [comment]
It is not reproducable on Magento 2.3.4.
