### ISSUE TITLE
Category Page Sorting does not work if a custom block uses Magento\Catalog\Block\Product\ListProduct.php 

### ISSUE THREAD

**Issue by arptg** [magento/magento2#27401]
### Preconditions (*)
1. Magento2.3.4 
2. Magento 2.4-develop

### Steps to reproduce (*)
1. Add a custom block which uses or extends Magento\Catalog\Block\Product\ListProduct.php. 
2. For the template get all the products using $block->getLoadedProductCollection();

- layout - catalog_category_view.xml

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="content">
            <block class="Magento\Catalog\Block\Product\ListProduct" name="product.detail.sorttest" template="Vendor_Module::schema.phtml" before="-"/>
        </referenceContainer>
    </body>
</page>
```

- contents of the block file.

```
<?php $products = $block->getLoadedProductCollection();
echo "already here"; ?>
<?php  if($products->count()) : ?>
    <?php foreach($products as $product): ?>
        <div> <?php echo $product->getId(); ?> </div>
    <?php endforeach; ?>
<?php endif; ?>

```

### Expected result (*)
1. Product Sorting in category page should work.

### Actual result (*)
1. Product Sort does not work.
![Peek 2021-01-05 13-55](https://user-images.githubusercontent.com/51681379/103643722-cc1df400-4f5d-11eb-8bff-719c1ee33ba2.gif)

This used to work on Magento 2.1.10 .
 
I am using the given method to get all the products currently visible in the category page. Can anyone suggest any other method instead ?

**Comment by arptg** [comment]
> Hi @arptg. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [* ]  Summary of the issue
> * [ *]  Information on your environment
> * [ *]  Steps to reproduce
> * [ *]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @arptg do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ *]  yes
> * [ ]  no
>

**Comment by magento-engcom-team** [comment]
Hi @arptg. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by arptg** [comment]
> Hi @arptg. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @arptg do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @arptg. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @arptg, here is your [Magento instance](https://i-27401-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27401-2-4-develop.instances.magento-community.engineering/admin_5019](https://i-27401-2-4-develop.instances.magento-community.engineering/admin_5019)
Login: `2c66b51b` Password: `b2982b704e5e`
Instance will be terminated in up to 3 hours.

**Comment by AleksLi** [comment]
@magento I am working on it

**Comment by AleksLi** [comment]
@arptg hello. I couldn't reproduce the issue. Should I do something inside my custom class? I tried on default 2.4-develop instance and cannot reproduce the issue.

Could you give more instructions about how to extend the Magento\Catalog\Block\Product\ListProduct class

**Comment by arptg** [comment]
layout - catelog_product_view.xml

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="content">
            <block class="Magento\Catalog\Block\Product\ListProduct" name="product.detail.sorttest" template="Vendor_Module::schema.phtml" before="-"/>
        </referenceContainer>
    </body>
</page>
```

contents of the block file.
```
<?php $products = $block->getLoadedProductCollection();
echo "already here"; ?>
<?php  if($products->count()) : ?>
    <?php foreach($products as $product): ?>
        <div> <?php echo $product->getId(); ?> </div>
    <?php endforeach; ?>
<?php endif; ?>

```
@AleksLi 
hope this helps. I don't know about magento 2.4 but in magento 2.3.4 this breaks product sort.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40290` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
