### ISSUE TITLE
Only variables can be passed by reference in [file path]

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#2742]
Hi,

After authenticating in backend, the following exception appears:
<i>
<b>Fatal error</b>: Only variables can be passed by reference in <b>/var/www/magentos/community/2.0.0/html/app/code/Magento/Backend/view/adminhtml/templates/system/search.phtml</b> on line <b>31</b>
</i>

Thanks,

Tiago

**Comment by tiagosampaio** [comment]
The same thing occurs with the following file:

<i>
<b>Fatal error</b>: Only variables can be passed by reference in <b>/var/www/magentos/community/2.0.0/html/app/code/Magento/Catalog/view/adminhtml/templates/product/edit/attribute/search.phtml</b> on line <b>27</b>
</i>

Thanks,

Tiago

**Comment by anton-huz** [comment]
Please verify PHP settings: Magento expects `asp_tags = Off`.
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
