### ISSUE TITLE
"As low as" price display doesn't consider advanced pricing

### ISSUE THREAD

**Issue by Pictick** [magento/magento2#27439]
### Preconditions (*)

Magento 2.3.4 and `2.4-develop`

### Steps to reproduce (*)

1. Add a product configurable product
2. add and connect two or more virtual products
3. use quantity prices in advanced pricing for Bothe virtual products
4. visit the catalog view of the category 

### Expected result (*)

1. You will see the the cheapest "As low as" price (the cheapest quantity price in the advanced pricing)

### Actual result (*)

1. The overview shows the normal "As low as" price of the cheapest virtual product (not the one of the advanced pricing)

![Bildschirmfoto 2020-03-25 um 18 38 54](https://user-images.githubusercontent.com/62657535/77567998-3af6f880-6ec8-11ea-82ef-b7722baab61e.png)

![Bildschirmfoto 2020-03-25 um 18 39 22](https://user-images.githubusercontent.com/62657535/77568009-3f231600-6ec8-11ea-8d58-bee1adfe4951.png)

![Bildschirmfoto 2020-03-25 um 18 40 13](https://user-images.githubusercontent.com/62657535/77568015-41857000-6ec8-11ea-8702-0540154b26b9.png)

### Additional information
https://github.com/magento/magento2/issues/27439#issuecomment-627626141

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27439-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27439-2-4-develop.instances.magento-community.engineering/admin_60e7](https://i-27439-2-4-develop.instances.magento-community.engineering/admin_60e7)
Login: `a92a6b69` Password: `a9f54a9d07c7`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27439-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27439-2-4-develop.instances.magento-community.engineering/admin_0a99](https://i-27439-2-4-develop.instances.magento-community.engineering/admin_0a99)
Login: `98655b43` Password: `b0dc422d37fa`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32859` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tna274** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tna274. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tna274, here is your [Magento instance](https://i-27439-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27439-2-4-develop.instances.magento-community.engineering/admin_a5f9](https://i-27439-2-4-develop.instances.magento-community.engineering/admin_a5f9)
Login: `e25a5f02` Password: `cfa77553d6d6`
Instance will be terminated in up to 3 hours.

**Comment by tna274** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tna274. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tna274, here is your [Magento instance](https://i-27439-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27439-2-4-develop.instances.magento-community.engineering/admin_a558](https://i-27439-2-4-develop.instances.magento-community.engineering/admin_a558)
Login: `b027f5c6` Password: `f2b1919fffb3`
Instance will be terminated in up to 3 hours.

**Comment by ProkopovVitaliy** [comment]
@mageho I'll work on the issue

**Comment by sdzhepa** [comment]
To check and confirm this issue I used next test products and prices

**Simple Product 1**
- Price = 10; Tier Price = "Buy 2 for $5.00 each"

**Virtual product**
- Price = 10; Tier Price = "Buy 2 for $5.00 each"

**test_configurable_2virtuals**
- Virtual1; Price = 10; Tier Price = "Buy 2 for $5.00 each"
- Virtual2; Price = 10; Tier Price = "Buy 2 for $5.00 each"

**test_configurable_with_1simple**
- SimpleRed; Price = 10; Tier Price = "Buy 2 for $5.00 each"

Here is the result on Storefront 
And seems that behavior for configurable should be the same as for Simple and Virtual
![issue_27439](https://user-images.githubusercontent.com/3409584/81750685-9f1f4d00-9473-11ea-89b2-0029c1c46ec0.png)
