### ISSUE TITLE
[TEST] Do not process

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#27441]

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @VladimirZaets 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32802` were created

**Issue Available**: @VladimirZaets, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
