### ISSUE TITLE
Not able to fetch my custom fields data from customer view in admin.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2744]
I have created a tab in Admin customer view with custom fields by phtml. But when saving customer, i am not able to get data in observer.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
