### ISSUE TITLE
Meta description does not save from YoastSEO

### ISSUE THREAD

**Issue by edwardbatchelor** [magento/magento2#27440]
I am super frustrated.  Every time I try and save a Meta description does not save from YoastSEO in Magento it fails to save.  It saying you "saved the category" successfully but then it is actually not saving.  This issue occurs in both category and products.  Makes it impossible to have metra descriptions.  Please help.

**Comment by engcom-Delta** [comment]
Hi @edwardbatchelor thank you for your report, I'm not able to reproduce issue on clean 2.4-develop and it is related to your custom modules.
Please, refer to YoastSEO support

**Comment by edwardbatchelor** [comment]
Vasyl,

 

I don’t know what your talking about.  Everytime we try and save meta descriptions they fail to save.  We need a solution or your product becomes useless to us because we can’t have an SEO strategy on the platform.

 

Ed

**Comment by engcom-Delta** [comment]
Hi @edwardbatchelor , I mean that likely you have installed 3-rd party SEO extension not present in vanilla magento.
Please, try to reproduce your issue on vanilla Magento instance using command `@magento give me 2.4-develop instance`  - instruction [here](https://github.com/magento/magento2/issues/27440#issuecomment-604044079)

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.
