### ISSUE TITLE
Can't set stock for diferents scopes

### ISSUE THREAD

**Issue by agallart** [magento/magento2#27449]
### Preconditions (*)

1. Magento 2.3.3
2. enable Inventory Management

### Steps to reproduce (*)

1.create Websites

![image](https://user-images.githubusercontent.com/16067982/77633171-5eb15180-6f4f-11ea-8691-543a612e4e23.png)

2.create Source
![image](https://user-images.githubusercontent.com/16067982/77633063-2f9ae000-6f4f-11ea-951d-cc613a2d75f1.png)

3.create Stocks
![image](https://user-images.githubusercontent.com/16067982/77633139-4e997200-6f4f-11ea-9971-65bc13378022.png)

4.create product

![image](https://user-images.githubusercontent.com/16067982/77633266-80aad400-6f4f-11ea-93f8-b1e1fe7c6f81.png)

add qty into source

![image](https://user-images.githubusercontent.com/16067982/77633336-991aee80-6f4f-11ea-8f2d-bd39bb699346.png)

### Actual result (*)

I expect diferents qty for diferents scopes but return same result 
![image](https://user-images.githubusercontent.com/16067982/77634253-f499ac00-6f50-11ea-8741-e424aa675f80.png)

![image](https://user-images.githubusercontent.com/16067982/77634332-109d4d80-6f51-11ea-9b21-cad87883a80f.png)

i try to change stock_id with error

![image](https://user-images.githubusercontent.com/16067982/77634415-3296d000-6f51-11ea-8331-f1741be7752a.png)

### Expected result (*)

1. Diferent stock for diferents scopes

**Comment by agallart** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @agallart. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @agallart, here is your [Magento instance](https://i-27449-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27449-2-4-develop.instances.magento-community.engineering/admin_2ab3](https://i-27449-2-4-develop.instances.magento-community.engineering/admin_2ab3)
Login: `6f5e07a2` Password: `c6794a71f9d7`
Instance will be terminated in up to 3 hours.

**Comment by agallart** [comment]
can't reproduce without MSI ..
![image](https://user-images.githubusercontent.com/16067982/77635546-0714e500-6f53-11ea-8c2b-1254c4c7864c.png)

**Comment by swathishs** [comment]
Hi @agallart,2 all issue specific for MSI should be reported in the MSI repo

fyi: @sidolov @smoskaluk @sdzhepa

It seems this issue MSI specific and should be fixed in the MSI repository.

EngCom team, please confirm and transfer this issue to the https://github.com/magento/inventory/issues

Closing this issue
