### ISSUE TITLE
SimpleDirective regex filters everything after lowercase as parameter

### ISSUE THREAD

**Issue by wahidnory** [magento/magento2#27450]
### Summary (*)
I was trying to migrate some old templates to the new directive format as described here: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-email-migration.html
But to my surprise {{lifetime_spend}} never got rendered inside the email.

This was performed on the latest Magento installation 2.3.4. No error messages were shown, simply the value wasn't being rendered inside the email.

### Examples (*)

If you follow the tutorial https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/templates/template-email-migration.html step by step and include the {{lifetime_spend}} you'll see that it never is rendered and is being displayed as {{lifetime_spend}}
But I'll give examples of what happened to me.
So I started to look as to why this could be happening, because in my case I was simply printing out text but the use-case is the same as the tutorial. 
Inside the SimpleDirective class there's a function that handles the regular expression: 
```
public function getRegularExpression(): string
{
        return '/{{'
        . '(?P<directiveName>[a-z]+)(?:[\s\t]*)'
        . '(?:\s*(?P<quoteType>[\'"])(?P<value>(?:(?!\k\'quoteType\').)*?)(?<!\\\)\k\'quoteType\')?'
        . '(?P<parameters>.*?)'
        . '(?P<filters>(?:\|[a-z0-9:_-]+)+)?'
        . '}}'
        . '(?:(?P<content>.*?){{\/(?P=directiveName)}})?'
        . '/si';
}
```
What happens is that everything after the lowercase is considered a parameter and not a directive name.
So in this case the example goes as follow: {{lifetime_spend}} as 'lifetime' being the directive name and 'spend' being the parameter. 
Inside the ProcessorPool class (Magento\Framework\Filter\SimpleDirective\ProcessorPool) it tries to find the name here:
```
public function get(string $name): ProcessorInterface
{
        if (empty($this->processors[$name])) {
            throw new \InvalidArgumentException('Processor with key "' . $name . '" has not been defined');
        }

        return $this->processors[$name];
}
```
But lifetime != lifetime_spend, so this throws error which is being caught inside the SimpleDirective. 
```
public function process(array $construction, Template $filter, array $templateVariables): string
{
        try {
            $directiveParser = $this->processorPool
                ->get($construction['directiveName']);
        } catch (\InvalidArgumentException $e) {
            // This directive doesn't have a SimpleProcessor
            return $construction[0];
}
```
And afterwards it's never rendered.

### Proposed solution

I think the best solution is to include the lowercase inside the regex for example like this. 
```
public function getRegularExpression(): string
{
        return '/{{'
        . '(?P<directiveName>[a-z:_]+)(?:[\s\t]*)'
        . '(?:\s*(?P<quoteType>[\'"])(?P<value>(?:(?!\k\'quoteType\').)*?)(?<!\\\)\k\'quoteType\')?'
        . '(?P<parameters>.*?)'
        . '(?P<filters>(?:\|[a-z0-9:_-]+)+)?'
        . '}}'
        . '(?:(?P<content>.*?){{\/(?P=directiveName)}})?'
        . '/si';
}
```
This fixes the issue and lifetime_spend is rendered again.

**Comment by wahidnory** [comment]
Yes I was being able to reproduce this on a vanilla Magento Instance with sampledata.
This was done as a module, so I'm not sure on how to test this in the cloud instance.

Any ideas or input from anybody is appreciated.

**Comment by celorodovalho** [comment]
This should not be close. It's still a bug that should be fixed.
It's impossible with the current document to create a custom directive or a custom filter
```
\Magento\Framework\Filter\DirectiveProcessor\Filter\FilterPool
\Magento\Framework\Filter\SimpleDirective\ProcessorPool
```

**Comment by Swiftless** [comment]
We are also running into this issue since attempting to upgrade from Magento 2.3.3 to 2.4.2 and the proposed regex seems to work.

**Comment by hostep** [comment]
Hey @sidolov, @sdzhepa: can we have somebody investigate this? It seems like the stalebot closed it prematurely before the issue could get looked into. Thanks!

**Comment by wahidnory** [comment]
Will get back to you on this.

**Comment by engcom-Hotel** [comment]
Dear @wahidnory,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by pkarsai** [comment]
Thank you! This thread saved me a couple of hours of debugging. I made this patch to add uppercase letters and underscores to the list of accepted characters in directive names:

```diff --git a/vendor/magento/framework/Filter/DirectiveProcessor/SimpleDirective.php b/vendor/magento/framework/Filter/DirectiveProcessor/SimpleDirective.php
index ff1c53253..8d70267f4 100644
--- a/vendor/magento/framework/Filter/DirectiveProcessor/SimpleDirective.php
+++ b/vendor/magento/framework/Filter/DirectiveProcessor/SimpleDirective.php
@@ -94,7 +94,7 @@ class SimpleDirective implements DirectiveProcessorInterface
     public function getRegularExpression(): string
     {
         return '/{{'
-        . '(?P<directiveName>[a-z]+)(?:[\s\t]*)'
+        . '(?P<directiveName>[a-zA-Z_]+)(?:[\s\t]*)'
         . '(?:\s*(?P<quoteType>[\'"])(?P<value>(?:(?!\k\'quoteType\').)*?)(?<!\\\)\k\'quoteType\')?'
         . '(?P<parameters>.*?)'
         . '(?P<filters>(?:\|[a-z0-9:_-]+)+)?'
```
