### ISSUE TITLE
Braintree Payment Method Card Type Logo Fails to Change

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#27453]
### Preconditions (*)

1. Magento CE 2.3.4 with sample data
2. Braintree payment method is set up

### Steps to reproduce (*)

1. Sales > Orders > Create New Order
2. Choose products, complete the addresses and choose a delivery method
3. In the Braintree payment method enter an AMEX card number. The card type dropdown will switch to AMEX and the AMEX logo will display.
4. Now enter a MasterCard card number instead. The card type dropdown will change to MasterCard, however, the logo remains as AMEX

### Expected result (*)

The credit card type dropdown and logo should switch to whatever card number is entered.

### Actual result (*)

The credit card type dropdown switches, however, the logo gets stuck on the previous card type.

### Additional Information (*)

I asked my developer and he said:

"They are only appending the class name to the field of the card being used, so never changes once the first one is entered."

![github](https://user-images.githubusercontent.com/19744729/77640559-b501ad00-6fae-11ea-9aeb-51dd0d4ad34c.jpg)

**Comment by sudheers-kensium** [comment]
@atIOCrON I am not able to reproduced this issue on Magento give me 2.4-develop instance. Can you please provide more details/payment settings Or if you install any custom module please disable and check.

**Comment by atIOCrON** [comment]
@sudheers-kensium settings attached. Did you test on 2.3.4?

![braintree-settings](https://user-images.githubusercontent.com/19744729/77973141-1aeb8d00-733f-11ea-92b8-c5a52163afd8.jpg)

**Comment by sudheers-kensium** [comment]
@atIOCrON I have verified on Magento 2.3.4.

![image](https://user-images.githubusercontent.com/50358141/77993213-45404900-7345-11ea-9167-3dc9fe3155dc.png)
![image](https://user-images.githubusercontent.com/50358141/77993223-4a9d9380-7345-11ea-9559-049991f77e87.png)
![image](https://user-images.githubusercontent.com/50358141/77993252-5d17cd00-7345-11ea-8dad-7966924dc927.png)

**Comment by atIOCrON** [comment]
@sudheers-kensium , your screenshots show once again that you've failed to follow my steps to reproduce the issue. You've attempted on the frontend checkout, which is NOT what my steps say to do.

Please re-open this issue and unassign yourself so that someone else who can read directions can take a look. You're wasting my time closing all of my issues without following the steps to reproduce.

**Comment by atIOCrON** [comment]
Hi @sudheers-kensium, please re-open this issue and unassign yourself so someone else can work on it.

**Comment by atIOCrON** [comment]
Hi @sudheers-kensium , could you remove the tag "Progress: done" please?

**Comment by atIOCrON** [comment]
Yes, bot, this issue still persists. No one has looked into it. Please have someone fix the bug, thanks.

**Comment by engcom-Delta** [comment]
Hi @atIOCrON thank you for your report. 
Starting from `2.4.0` release, code related to this payment was removed from Magento code-base:
[Magento Open Source 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html)
> The core Braintree module has been removed from the code base. The Braintree Payments module now provides the same feature set. See [Braintree Payments](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.190658731.163879255.1612162480-1157872356.1605459366).

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

If you'd like to update the issue, please reopen it.
