### ISSUE TITLE
Braintree Payment Method AMEX 3-digit CVV Error From Admin

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#27452]
### Preconditions (*)

1. Magento CE 2.3.4 with sample data
2. Braintree payment method is set up with AMEX enabled

### Steps to reproduce (*)

1. Sales > Orders > Create New Order
2. Choose products, complete the addresses and choose a delivery method
3. In the Braintree payment method enter an AMEX card number with a valid expiry date and enter 3 digits for the CVV
4. Press Place Order

### Expected result (*)

An error should be shown stating that the CVV for AMEX must be 4-digits.

### Actual result (*)

"Please wait..." loading spinner is stuck on the page obstructing an "Attention - Some payment input fields are invalid" message" and neither message can be closed.

### Additional information (*)

I asked my developer to check this and he said:

"It's just poor error handling & is missing clearing the loader."

<img width="2436" alt="Screen Shot 2020-03-26 at 9 57 25 pm" src="https://user-images.githubusercontent.com/19744729/77639694-3eb07b00-6fad-11ea-969e-9fcffc10f19b.png">

**Comment by atIOCrON** [comment]
Yes

**Comment by sudheers-kensium** [comment]
@atIOCrON  I am not able to reproduced this issue. Can you please provide more details/payment settings.

**Comment by sudheers-kensium** [comment]
@atIOCrON For Amex card cvv is 4 digits

**Comment by atIOCrON** [comment]
Hi @sudheers-kensium, can you please share a screenshot showing that you were unable to reproduce the issue?

**Comment by atIOCrON** [comment]
@sudheers-kensium settings attached.

![braintree-settings](https://user-images.githubusercontent.com/19744729/77973156-2b036c80-733f-11ea-869c-d5854e80316f.jpg)

**Comment by sudheers-kensium** [comment]
@atIOCrON Please check the screenshots.
![image](https://user-images.githubusercontent.com/50358141/77993110-10cc8d00-7345-11ea-8284-d44304bb0e21.png)
![image](https://user-images.githubusercontent.com/50358141/77993124-175b0480-7345-11ea-85f9-c554ff115067.png)

**Comment by atIOCrON** [comment]
@sudheers-kensium, your screenshot shows that you didn't follow the instructions I gave to reproduce this issue.

The issue is faced if you attempt to enter a 3-digit CVV for AMEX.

Since a 3-digit CVV for AMEX is invalid it would be impossible for you to place an order if you'd followed my directions.

Please follow the steps I gave exactly under "Steps to reproduce (*)" and send a screenshot of your result to verify if you face the same issue.

Thanks

**Comment by sudheers-kensium** [comment]
@atIOCrON We need to use 4 digit cvv no For AMEX card

**Comment by atIOCrON** [comment]
@sudheers-kensium, do you understand the issue? The issue here is that the Magento error handling of an invalid CVV causes the page to be frozen.

If you use a 3-digit CVV for AMEX, the page should NOT freeze, it should show an error, that is all.

Here is what I wrote initially but it seems you didn't read or understand it:

Expected result (*)
An error should be shown stating that the CVV for AMEX must be 4-digits.

Actual result (*)
"Please wait..." loading spinner is stuck on the page obstructing an "Attention - Some payment input fields are invalid" message" and neither message can be closed.

Please confirm what is not clear about this for you. The Magento error handling is causing this issue.

**Comment by atIOCrON** [comment]
@sudheers-kensium , please re-open this issue and unassign yourself so that someone else who can read directions can take a look. You're wasting my time closing all of my issues without following the steps to reproduce.

**Comment by atIOCrON** [comment]
Hi @sudheers-kensium , could you remove the tag "Progress: done" please?

**Comment by atIOCrON** [comment]
Yes, bot, this issue still persists. No one has looked into it. Please have someone fix the bug, thanks.

**Comment by engcom-Delta** [comment]
Hi @atIOCrON thank you for your report.
Starting from `2.4.0` release, code related to this payment was removed from Magento code-base:
[Magento Open Source 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html)
> The core Braintree module has been removed from the code base. The Braintree Payments module now provides the same feature set. See [Braintree Payments](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.190658731.163879255.1612162480-1157872356.1605459366).

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

If you'd like to update the issue, please reopen it.

**Comment by atIOCrON** [comment]
Even though this issue was marked closed without any progress, someone at Magento has fixed the bug.

If you follow the steps to reproduce in this bug report on Magento v2.4.3-p1 it shows a popup warning:

"Please correct the problems with the Credit Card fields."

It's not descriptive that the issue is the CVV, however, it's better than the previous bug where the page would break.
