### ISSUE TITLE
I will help you with anything related to magento 1x and 2x

### ISSUE THREAD

**Issue by wilberronwilber** [magento/magento2#27457]
Hello to all!
I have been following this forum for a long time, but just registered now.
The fact is that over the past year I have been actively learning to work with Magento. Now I can surely help each of you! If anyone needs an assistant or service, please contact!
I do any type of work on your Magento eCommerce website following the recommended best practices!
Including:
• Customizing your theme
• Installing extensions
• Setting up your product's attributes
• Changing your blocks layout
• Updating/Inserting products
• Bulk import of products and customers
• Solving any kind of issues
Please contact me on Fiverr here - [https://www.fiverr.com/hacpires/](https://bit.ly/2xpFeEw)

**Comment by krishprakash** [comment]
Hi @wilberronwilber.
GitHub issue tracker is intended for magento core technical issues only 
This is not the marketing site for magento
So kindly post related to this.I hope you understand
Thanks !!
