### ISSUE TITLE
2 error messages in Cart when product is out of stock 

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#27469]
### Preconditions (*)
Magento 2.3.3, CatalogInventory Modules and MSI Modules enabled
1. You need a product
2. you must be able to change qty of that product

### Steps to reproduce (*)
1. put product in Cart
2. change qty to 0 and outofstock
3. press f5 in cart

### Expected result (*)
1. one message stating that the product is out of stock appears in the list of the cartitems

### Actual result (*)
1. two message stating that the product is out of stock appear
This product is out of stock. --> from CatalogInventory
There are no source items with the in stock status --> from Magento_InventorySales

![grafik](https://user-images.githubusercontent.com/48922246/77731492-51ee3580-7003-11ea-83e8-3a992ea4a05e.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27469-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27469-2-4-develop.instances.magento-community.engineering/admin_9211](https://i-27469-2-4-develop.instances.magento-community.engineering/admin_9211)
Login: `86df0572` Password: `502a99e4d5a9`
Instance will be terminated in up to 3 hours.

**Comment by stkrelax** [comment]
@sudheers-kensium thank for having a look. Any questions than just ask i will try to answer immediatly

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32861` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by stkrelax** [comment]
Adittional notice : 
there is also a case where this happens when you have a product instock and qty 1 
and inventory reservation totals -2 when cart qty is 1
Same case but other Messages.

**Comment by gwharton** [comment]
https://github.com/magento/magento2/issues/24191

**Comment by neerajchand** [comment]
@magento I am working on it

**Comment by madhurajawat** [comment]
@magento I need to fork MSI directory. Can you please provide the permission
Thanks.

**Comment by madhurajawat** [comment]
@stkrelax  There is code added in InventorySales module di.xml. with this code getting 2 errors. 

 

<item name="is_any_source_item_in_stock" xsi:type="array">
	<item name="required" xsi:type="boolean">true</item>
	<item name="object" xsi:type="object">Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsAnySourceItemInStockCondition</item>
</item>

We can remove this code.

**Comment by stkrelax** [comment]
@madhurajawat will have a look at it

**Comment by stkrelax** [comment]
sry we decided to disable msi. Other oversale reasons are the cause.

**Comment by jtomaszewski** [comment]
??? Has it been fixed? If not, why did this issue has been closed?

It stills occurs at our Magento, 2.4.1 version.

**Comment by jtomaszewski** [comment]
One of the errors is produced by this:

![image](https://user-images.githubusercontent.com/1862580/103290467-e863e300-49e9-11eb-9b45-bdd507fefe4b.png)

And the other by this:

![image](https://user-images.githubusercontent.com/1862580/103290479-f31e7800-49e9-11eb-9892-0fff350b216f.png)

The fix would probably be:

- consolidate those validators into one, so that only one of them is fired (or there is one validator that does the job of both of them), or
- when adding "this product is out of stock" error message, do not add it, if one is already existant on it.

**Comment by NachoVidalGolosinas** [comment]
Anyone know any way to fix this?

**Comment by sprajapat770** [comment]
@NachoVidalGolosinas run this command in your database terminal.

INSERT IGNORE INTO inventory_source_item (source_code, sku, quantity, status)
select 'default', sku, qty, stock_status from (cataloginventory_stock_status as lg join catalog_product_entity as prd on((lg.product_id = prd.entity_id)))
