### ISSUE TITLE
Autoselecting configurable product options does not work with the swatches module enabled

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#2746]
**Preconditions**: 
- magento v2.0.0 installed
- catalog module version:
  - 2.0.3 in module.xml
  - 100.0.2 in composer.json
- configurable products module version:
  - 2.0.0 in module.xml
  - 100.0.2 in composer.json
- swatches module version:
  - 2.0.0 in module.xml
  - 100.0.2 in composer.json
- full sample data installed (this is not mandatory)

**Steps to reproduce**
- visit a configurable product page with a hash to autoselect the options: product.phtml#{attribute_id}={option_id}. 
- example in sample data: `orion-two-tone-fitted-jacket.html#90=49`. This should select the color black automatically

**Expected result**
- the color swatch black should be selected  
  ![](http://i.imgur.com/vjFpwe6.png)

**Actual result**
- nothing is selected  
  ![](http://i.imgur.com/YVkAWvm.png)

**Additional information**
- Disabling the `Magento_Swatches` module makes the page behave as expected:
  ![](http://i.imgur.com/9aToCbP.png)

**Comment by tanya-soroka** [comment]
Hello @tzyganu , thanks for reporting this issue. Internal ticket has been created: MAGETWO-47023.

**Comment by tigerx7** [comment]
I dug into SwatchRenderer.js and from the looks of it, this isn't a bug. Magento2 just handles the autoselecting differently.

In M1, it used the # parameter, which in itself was odd, but in M2, it's actually looking for a query. Also, the attribute id expectation has been changed to an attribute code.

So what normally might have looked like:
orion-two-tone-fitted-jacket.html#90=49

should now look like:
orion-two-tone-fitted-jacket.html?color=49

I've been able to successfully autoselect on configurable products with swatches using ?{attribute_code}={option_id}

**Comment by tzyganu** [comment]
@tigerx7 But it still works as I expect it to work when I disable the swatch module. If this is not a bug it's at least an inconsistency.

**Comment by mslabko** [comment]
@tzyganu, Issue has been fixed in commit https://github.com/magento/magento2/commit/0416e64437bfa09ee762585b7fe5fd5af1a40e42
Thank you for reporting!

**Comment by am-wtw** [comment]
I am facing the same issue in 2.2.1.
Anyone has any idea how to resolve it in 2.2.1.
