### ISSUE TITLE
Magento 2.3 - Square Payments Module not working

### ISSUE THREAD

**Issue by shaLVerma** [magento/magento2#27472]
HI,

I have installed and configured Square Payments M2 (https://marketplace.magento.com/square-module-squareup-omni.html) in my website. All things working fine except checkout page. When I filled card details and place order. I am getting this error in checkout page console

{"message":"User Deprecated Functionality: \u001b[33mCalling deprecated API: TransactionsApi.charge\u001b[0m in \/public_html\/vendor\/square\/connect\/lib\/Api\/TransactionsApi.php on line 191","trace":"#0 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(1310, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(1310, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))\n#3 \/public_html\/generated\/code\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#4 [internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(1310, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))\n#5 \/public_html\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#6 \/public_html\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#7 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#9 \/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/public_html\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#11 \/public_html\/vendor\/magento\/framework\/App\/Http.php(137): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/public_html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#13 \/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(261): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#14 \/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#15 {main}"} 

I have replaced this file TransactionsApi.php with updated version file (https://github.com/square/connect-php-sdk/blob/master/lib/Api/TransactionsApi.php). 

It this Magento issue or Square Module issue. Square support team said "all API functions are operated and managed by Magento."

**Comment by hostep** [comment]
@shaLVerma: this doesn't sound like a core Magento issue, but an issue with the "Square Payments" module, so I have to close it.
Can you contact the owner of the module and try to get it sorted out in that way?
If you check the Q & A section, it looks like this is a known problem:
<img width="726" alt="Screenshot 2020-03-28 at 12 31 12" src="https://user-images.githubusercontent.com/85479/77822127-344aca00-70f0-11ea-9e11-79eef7da53e0.png">


Thanks!

**Comment by shaLVerma** [comment]
> Hi @shaLVerma. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @shaLVerma do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

thanks.

**Comment by magento-engcom-team** [comment]
Hi @shaLVerma. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shaLVerma, here is your [Magento instance](https://i-27472-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27472-2-4-develop.instances.magento-community.engineering/admin_e313](https://i-27472-2-4-develop.instances.magento-community.engineering/admin_e313)
Login: `737a0cdc` Password: `fc0487721b3e`
Instance will be terminated in up to 3 hours.
