### ISSUE TITLE
Order data issue in observers

### ISSUE THREAD

**Issue by wkaminsk** [magento/magento2#2748]
Hi,
I tried to push orders data to 3rdParty webservice. I created observer for event sales_order_place_after - order Id is missing here. I believe it's not a bug - order is not saved in database.
So then I've tried to use sales_order_save_after gives empty array of items, no payment method information. Tried to load it again with `ordermodel->load(id_of_order)` but it gives empty data again.
I'm pretty sure, the order save event is raised before address, payment and other order stuff is saved.
How I can proceed it ?

Thanks,
Wojtek.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
