### ISSUE TITLE
Duplicate mails are coming on order confirmation

### ISSUE THREAD

**Issue by deepakpant91** [magento/magento2#27484]
### Preconditions (*)

1. Magento version 2.3.3
2. Website url https://kindercanteen.in/

### Steps to reproduce (*)

1. When you go to checkout and place the order using cod then customer gets two duplicate emails of order confirmation.
2. Cod is available after order amount is above 500.

### Expected result (*)

1. After order place only one confirmation mail will be sent to customer.
2.

### Actual result (*)

1. When we add a product into cart then  go to checkout and place the order using cod then customer gets two duplicate emails of order confirmation.
2.

**Comment by sudheers-kensium** [comment]
@deepakpant91 this not core Magento issue, maybe issue with your custom or third-party modules. Please disable custom/third-party modules and check once.

**Comment by sudheers-kensium** [comment]
Closing, because this is not a core bug of Magento.

**Comment by deepakpant91** [comment]
@sudheers-kensium i have disabled all extensions but duplicate emails are still coming

**Comment by DavidEu000** [comment]
I am also facing this issues as I have tried to place order with built-in or 3rd payment gateway, which are received the email confirmation twice with the same content.

Anyone could help me to fix?

**Comment by barryvdh** [comment]
I'm facing the same issue with Klarna (from Stripe), but not from any other payments. Any ideas how you solved this?
