### ISSUE TITLE
magento2.3.4 installation has been stuck at 99% 

### ISSUE THREAD

**Issue by vini1996** [magento/magento2#27480]
### Preconditions (*)

1. magento 2.3.4
2. php 7.3.16

### Steps to reproduce (*)

1. installing a fresh magento setup

### Expected result (*)

1. it should display success message after installation completes 

### Actual result (*)

1. Installation is stuck at 99% displaying Installing admin user
![stack](https://user-images.githubusercontent.com/39683802/77818645-09fe0a00-70fa-11ea-89c6-389189add2f9.png)

2.

**Comment by sudheers-kensium** [comment]
@vini1996 Maybe that will take some to complete, this is not an issue. I have installed without any issue in my local system.

**Comment by sudheers-kensium** [comment]
@vini1996 Maybe that will take some to complete, this is not an issue. I have installed without any issue in my local system.
