### ISSUE TITLE
Configurable products issue Magento 2.3.4.

### ISSUE THREAD

**Issue by lebigmaque** [magento/magento2#27482]
### Preconditions (*)
Magento 2.3.4 php 7.2

### Steps to reproduce (*)
The problem occurs in the frontend for configurable products.
It only affects configurable products with several selectable attributes.
Almost always no options are displayed in the second or third dropdown menu. However, there are matching products with stock and visibility that are correctly added to the configurable item in the backend. 
The problem occurs only after updating from 2.3.3 to 2.3.4.

### Expected result (*)
We expect many options in several drop down menus.
e.g. 
1. colours: red, green blue
2. size: 1, 2, 3 for red, size: 1, 2, 3, 4 for green and size: 1, 2 for blue

### Actual result (*)
The drop-down menus offer few or no selections.
1. red, green, blue
2. no size options, if red was selected before, nothing for green, for blue: 1, 2

**Comment by jmendozac** [comment]
Hi Everybody,

Same error here. 

Magento 2.3.4 PHP Version 7.2.29. New Installation. No migration from previous versions.
Simple products loaded through System Data Transfer Import. Configurable products are being added through Admin Catalog Products panel.

At Frontend, on Product Page, right after one click on the first product attribute dropdown menu, you get the following error message in Chrome's Inspect Console:

**Uncaught TypeError: Cannot read property '0' of undefined
    at $.<computed>.<computed>._fillSelect (configurable.js:449)
    at $.<computed>.<computed>._fillSelect (widget.js:100)
    at $.<computed>.<computed>._configureElement (configurable.js:271)
    at $.<computed>.<computed>._configureElement (widget.js:100)
    at HTMLSelectElement._configure (configurable.js:254)
    at HTMLSelectElement.<anonymous> (widget.js:100)
    at HTMLSelectElement.dispatch (jquery.js:5232)
    at HTMLSelectElement.elemData.handle (jquery.js:4884)**

You won't get this error when the configurable product has one option only in the second attribute (color & size, in my case) but its value won't be correctly saved when added to shopping cart. That is, color is correctly saved (first attribute) but size value (second attribute) is not saved.

Thanks in advance for your help.

**Comment by hewgim** [comment]
How does a bug like this slip through testing. Just migrated a store from Magento 1 to a Magento development environment and found this bug in the first five of minutes of testing.

**Comment by krishprakash** [comment]
Hi @lebigmaque. Thank you for your report.
Issue is looks similar to #27330
You can track the progress from above issue link.
