### ISSUE TITLE
The meta description for products allows up to 255

### ISSUE THREAD

**Issue by powerhousefitness** [magento/magento2#2749]
Hi

The meta description for products allows up to 255 characters and google only allows a max of 115.

The meta title should also be limited to 55 characters. 

Thanks
John

**Comment by powerhousefitness** [comment]
Just a note that Bing has a different limit so may be worthwhile looking at all search engines to see the max we should allow.

Regards
John

**Comment by antboiko** [comment]
Hi @powerhousefitness , thank you for reporting this issue. We have created an internal ticket MAGETWO-47025 to apply suggested limit.

**Comment by davidalger** [comment]
Throwing my two cents here, but Magento should not limit the meta title based solely on what search engines include in their index. Might affect what merchants want to store in there? Sure…but a merchant might include this meta title to a bunch of different feeds with variable max lengths, including internal search feeds.

**Comment by antboiko** [comment]
@davidalger thank you for your input regarding meta title, makes sense.

**Comment by powerhousefitness** [comment]
Yes sorry title should not be included as it used for page title. ty chaps

**Comment by rgoncharuk** [comment]
Closed as delivery already happened

**Comment by seansan** [comment]
And now the max is back to 320 chars!
