### ISSUE TITLE
The store logo is missing when using the Magento_blank theme

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#27496]
### Preconditions (*)
1. Magento 2.4-develop
2. Access to the admin area

### Steps to reproduce (*)

1. Go to the admin area
2. Go to the Content -> Design -> Configuration
3. Open the global store and set the default theme to be `Magento_blank`.
4. The other store configuration should be intact.
5. Flush the caches
6. Open the storefront (Homepage)
7. See the logo is not visible

### Expected result (*)

The default store logo (Magento) is visible on the storefront when the `Magento_blank` theme is used.

### Actual result (*)

The store logo is not visible on the storefront. Starting from mobile to desktop devices.

| Desktop | Tablet | Mobile |
| -------- | ------- | ------ |
| ![desktop](https://user-images.githubusercontent.com/13456702/77904038-84f72a00-728c-11ea-89b0-a56d33388004.jpg) |  ![tablet](https://user-images.githubusercontent.com/13456702/77904094-9c361780-728c-11ea-8b1d-81fffd5a8962.jpg) |  ![mobile](https://user-images.githubusercontent.com/13456702/77904123-a9eb9d00-728c-11ea-8ce9-218d3cba936a.jpg) |

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27496-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27496-2-4-develop.instances.magento-community.engineering/admin_9efc](https://i-27496-2-4-develop.instances.magento-community.engineering/admin_9efc)
Login: `2a0650e5` Password: `4774dad1f8a2`
Instance will be terminated in up to 3 hours.

**Comment by vasilii-b** [comment]
@magento give me 2.3 instance

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by vasilii-b** [comment]
I'll work on the issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32895` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
The issue has been fixed in magento/magento2#27497 by @vasilii-b in 2.4-develop branch
Related commit(s):
 - [100d6f148c7dcf2f3fffdaa3991febbb4454a611](https://github.com/magento/magento2/commit/100d6f148c7dcf2f3fffdaa3991febbb4454a611)

The fix will be available with the upcoming 2.4.0 release.
