### ISSUE TITLE
Can't change customer group when placing an admin order

### ISSUE THREAD

**Issue by magedev218** [magento/magento2#27490]
When ordering in the admin, we can't change the customer group when creating a new customer while creating an order.

**Preconditions**
- Magento 2.3.4
- Several Customer Groups created

**Steps to reproduce**
- In Admin System > Configurations > Customers > Customer Configurations > Create New Account Options > Enable Automatic Assignment to Customer Group >> Select YES
- In Admin Sales > Orders.
- Select Create New Order
- Select Create New Customer
- Under Account Information, change the group.

**Expected result**

- Selected customer group stays selected in select box.
- Product prices are updated for the group.

**Actual result**

- Wait overlay comes up, twice.
- Customer group goes back to the default.
- Product prices stay the same.

Note: this issue is similiar to #7974 and #6162 and #21144

I have also tried to apply the patch but didnt work for me.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27490-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27490-2-4-develop.instances.magento-community.engineering/admin_0f13](https://i-27490-2-4-develop.instances.magento-community.engineering/admin_0f13)
Login: `bcd8c681` Password: `0232603667ac`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32889` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by vseager** [comment]
We also have this issue on v2.3.4-p2

**Comment by engcom-Alfa** [comment]
The issue is reproducible on fresh 2.4-develop

![Peek 2020-07-20 18-54](https://user-images.githubusercontent.com/51679138/87958693-827a4380-caba-11ea-8b69-570f848d2c67.gif)

**Comment by engcom-Alfa** [comment]
Hi @magedev218 . Thanks for collaboration. This PR was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the[ link](https://www.youtube.com/watch?v=4dFuALJ0L4I&t=395s)

**Comment by TonyRutherford1** [comment]
@engcom-Alfa Any update on this issue? Also have this issue.

**Comment by JD-HSP** [comment]
Any updates on this fix yet?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @magedev218. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-32889` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
