### ISSUE TITLE
"base_tax_amount" is inaccurate for Credit Memo items

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2751]
## Explanation of issue

When a store is configured to use a different currency than the **Base Currency** and multiple credit memos are created for an order, credit memo items will have an inaccurate "base_tax_amount" value. I've solved this issue in this one-line PR: #2753 
## Steps to reproduce issue
1. Install Magento CE 2.0.0 with sample data.
2. Configure the store to use a non-USD currency. Something like this:
   ![51d775ec-a263-11e5-970d-b3fbda6044f0](https://cloud.githubusercontent.com/assets/129031/11884672/016e555a-a4e1-11e5-8f51-4f6ecb0f691b.png)
3. Go to **Stores > Currency Rates** and ensure that conversion rates have been imported for your selected rate. I manually set my conversion rate to 2.00 to make troubleshooting easy.
4. Go to **Stores > Configuration > SALES > Tax** and change the settings to this:
   ![image](https://cloud.githubusercontent.com/assets/129031/11884736/896d8246-a4e1-11e5-8d1e-0e3bf83957fa.png)
5. Place an order for a QTY of greater than 1 for any item. Use a shipping address that will cause tax to be calculated for your order (the roni_cost@example.com user has a Michigan address that should cause tax to be applied).
6. Once you have placed the order, go to the backend and create an invoice for the order.
7. Create a credit memo for _one_ of the items in the order. View the credit memo. You should see that the base_tax_amount (top) and tax_amount (bottom) values are correct:
   ![view_memo___operations___sales___magento_admin](https://cloud.githubusercontent.com/assets/129031/11884778/d67f55c8-a4e1-11e5-90e9-b25f73eb9045.png)
8. Now create another credit memo for another _one_ of the items. If you view that credit memo, you'll see that the "base_tax_amount" value is inaccurate:
   ![view_memo___operations___sales___magento_admin](https://cloud.githubusercontent.com/assets/129031/11884804/1719b498-a4e2-11e5-8dfe-e05091a2a9e9.png)

**Comment by tang-yu** [comment]
The PR has been merged.
