### ISSUE TITLE
When using the api method "salesShipOrderV1", the order data is not included in the email template.

### ISSUE THREAD

**Issue by kms-engineer** [magento/magento2#27513]
### Summary (*)
When using the api method "salesShipOrderV1", the order data is not included in the email template. If you specify "notify": true.

### Proposed solution
My hot fix: 
Created observer on "email_shipment_set_template_vars_before" event.

class ShipmentEmailSenderObserver implements ObserverInterface
{
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $transportObject = $observer->getEvent()->getData('transportObject');
        $transport = $transportObject->getData();

        if (!isset($transport['order_data'])) {
            if (isset($transport['order'])) {
                $order = $transport['order'];
                $transport['order_data'] = [
                    'customer_name' => $order->getCustomerName(),
                    'is_not_virtual' => $order->getIsNotVirtual(),
                    'email_customer_note' => $order->getEmailCustomerNote(),
                    'frontend_status_label' => $order->getFrontendStatusLabel()
                ];
                $transportObject->setData($transport);
            }
        }
    }
}

You can add this to the class "Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php". How do you add this to the class "Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php"

**Comment by mykyta-kotenko** [comment]
Yes

**Comment by andrew-ebsco** [comment]
I can confirm this is still happening in 2.3.5-p1. The class at vendor/magento/module-sales/Model/Order/Shipment/Sender/EmailSender.php does not include the `order_data` array in the template variables object.
