### ISSUE TITLE
Filtering by url_key doesn't work in GraphQL Products Query

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#27518]
### Preconditions
1. Magento 2.3.4

### Steps to reproduce 
1. Create a product and set the url key to 'my-test-product'
2. Submit the following Graph QL query:
```
{
  products(
    filter: {
    	url_key: {
          eq: "my-test-product"
        }
    }
  ) {
    total_count,
    items {
      id,
      sku,
      url_key,
      name
    }
  }
}
```

### Expected result
Only that single product should be returned in the items

### Actual result
All products are returned. url_key is completely ignored.

**Comment by paul-blundell** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](https://i-27518-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27518-2-3-4.instances.magento-community.engineering/admin_0b63](https://i-27518-2-3-4.instances.magento-community.engineering/admin_0b63)
Login: `ea2f7963` Password: `111562a3dcf7`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
Unable to reproduce on the fresh instance.

This must be an issue somewhere in my local install.

**Comment by paul-blundell** [comment]
If anyone runs into this same issue, it would appear to be a problem with the M1 migration tool. The product url_key attribute had the Use in Search value set to No. Changing this to Yes fixed my issue.
