### ISSUE TITLE
2.2.3 - 'Send Order Email Copy To' field just sent with the first email

### ISSUE THREAD

**Issue by yesman2104** [magento/magento2#27511]
**Preconditions (*)**
Magento 2.2.3
Send order email copy after order success

**Steps to reproduce (*)**
Stores->configuration->sales->Order-> Input value like this "a@example.com,b@example.com,c@example.com"
 for "Send Order Email Copy" field 

**Expected result (*)**
All email input in field need to receive email order confirmation .

**Actual result (*)**
Just only send email confirm to The first Email, Another mail **separated-comma** not receive

**Comment by shikhamis11** [comment]
Hi @yesman2104 
thank you for reporting this issue . It seems this issue is already as I am not able to reproduce this issue at magento 2.4 instance. Please check the issue at latest version and let us know if issue persist
