### ISSUE TITLE
Which files to push VCS (i.e. git)

### ISSUE THREAD

**Issue by bnymn** [magento/magento2#27514]
### Summary (*)

When we create a new project with composer, Magento brings a lot of files and folders to the table.  If we use the default Magento .gitignore, we push a lot of files to the version control system. It is ~150MB. However, based on my experiences, I can say that we never need to change any files except `app/code`, `app/design`, `composer.json` and `composer.lock`.

Do we really need to push that much code to the VCS? Can't we use a .gitignore files like this?

### Examples (*)

1. Install Magento with composer
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2
```
2. Measure the folder.

### Proposed solution

We have the following .gitignore for our projects:
```
/*
!.gitignore
!/app
/app/*
!/app/*/
!/app/code/**
!/app/design/**
!/app/etc/config.php
!/app/i18n/**
!/composer.json
!/composer.lock
!/nginx.conf
```

Magento Cloud has the following .gitignore file.
https://github.com/magento/magento-cloud/blob/2.3.4/.gitignore

EDIT 1:
I am proposing to change the `.gitignore` file coming from the fresh Magento installation with one of the above.

**Comment by lbajsarowicz** [comment]
Have you tried Google?
https://www.google.com/search?q=magento+gitignore+file

- https://gist.github.com/yireo/744edcb4c70d33514ca35ebb14902056
- https://inchoo.net/magento/programming-magento/git-ignore-gitignore-file-for-magento-project/
- https://github.com/davidalger/warden-env-magento2/blob/develop/.gitignore

**Comment by bnymn** [comment]
Hi @lbajsarowicz,

Yes, of course, I have tried Google. I have also put a reference to `.gitignore` file from Magento Cloud.

I have created this issue to update the default `.gitignore` file coming from the fresh Magento installation.
