### ISSUE TITLE
No "inventory" section in menu [2.4-develop instance]

### ISSUE THREAD

**Issue by vbyno** [magento/magento2#27524]
2.4-develop instance

### Preconditions (*)

Magento 2.4-develop instance (vanilla installation)

### Steps to reproduce (*)

1. Go to Stores in main menu

### Expected result (*)

Inventory section to be present
![image](https://user-images.githubusercontent.com/2923624/78108914-ecce8180-7400-11ea-82eb-c034bf23b029.png)

### Actual result (*)

No inventory section
![image](https://user-images.githubusercontent.com/2923624/78108946-f9eb7080-7400-11ea-8e1a-a95eab649af9.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27524-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27524-2-4-develop.instances.magento-community.engineering/admin_2b69](https://i-27524-2-4-develop.instances.magento-community.engineering/admin_2b69)
Login: `0234f0de` Password: `28e742e99472`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32978` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by KonstantinZhidkovskiy** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @KonstantinZhidkovskiy. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @KonstantinZhidkovskiy, here is your [Magento instance](https://i-27524-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27524-2-4-develop.instances.magento-community.engineering/admin_d8f7](https://i-27524-2-4-develop.instances.magento-community.engineering/admin_d8f7)
Login: `643220f8` Password: `a7a440c40403`
Instance will be terminated in up to 3 hours.

**Comment by KonstantinZhidkovskiy** [comment]
Hi @vbyno, this Inventory section not included in current 2.4-develop branch, to get it you need additionally install this meta package https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide, after doing this Strores > Inventory will be enabled

**Comment by vbyno** [comment]
@KonstantinZhidkovskiy , will MSI module be included in 2.4 installation out of the box?

**Comment by gomesrafael** [comment]
@magento give me 2.4-develop instance
