### ISSUE TITLE
Reviews summary not showing in Products List widget

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#2752]
While the CatalogWidget::product/widget/content/grid.phtml template should be displaying a reviews summary, this is not part of the output.  From preliminary investigation, getRatingSummary on the product objects returns nothing in this context.

**Comment by hellozach** [comment]
Any fixes for this yet? Trying to solve this for way too long now.

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @CNanninga thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Comment by coatesjonathan** [comment]
Hi, i'd like to reopen as I am having this issue on 2.1.7

**Comment by ghost** [comment]
Yes, same issue on 2.1.7.

If you set the displayIfNoReviews flag to true it shows properly however.

So i guess as a workaround in your template [grid.phtml](https://github.com/magento/magento2/blob/2.1/app/code/Magento/CatalogWidget/view/frontend/templates/product/widget/content/grid.phtml#L63) add true as a third parameter

`<?= $block->getReviewsSummaryHtml($_item, $templateType, true) ?>`
