### ISSUE TITLE
Order confirmed and confirmation email also sent to recipient before payment gateway redirection

### ISSUE THREAD

**Issue by karthickms** [magento/magento2#27533]
Before payment gateway redirection, user receives order confirmation email and also order was confirmed. It works like COD method instead of payment gateway method.

Please give me your hands

**Comment by shikhamis11** [comment]
@karthickms please correct the format of issue reporting . You can take help from 
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Also please share additional information about the issue

**Comment by shikhamis11** [comment]
Also with current description It seems that order is placed before redirect so it looks like more of an issue of the Payment Method. Please check

**Comment by shikhamis11** [comment]
@karthickms I am closing this issue due to in activity . Please open your issue once you wish to update description and check details as per my previous comment
