### ISSUE TITLE
Media Gallery In Magento 2 Blog

### ISSUE THREAD

**Issue by Terryh1949** [magento/magento2#27532]
I can't seem to delete a duplicate image in the Magento 2 media gallery blog.

**Comment by Terryh1949** [comment]
I can't believe it is this hard to get an answer to a simple question

**Comment by sudheers-kensium** [comment]
@Terryh1949 Kindly update all the details for reproduce the issue

**Comment by sudheers-kensium** [comment]
Feel free to reopen once you update all necessary details
Thanks

**Comment by Terryh1949** [comment]
There are no details. All I wanted was an answer to a question as to why under the Magento Blog Extension I could not delete a photo that I had uploaded which was a duplicate.

To have to sign up for GitHub and all that is way beyond what I am up to after almost 30 years of blogging and computer expertise.


Terry


[cid:ffc4debb-202b-420a-baf2-b7d937aecf9a]

Terry Henry - Global Workshop Coordinator, Cheap Joe's Art Stuff

828-263-5454 • www.cheapjoes.com


________________________________
