### ISSUE TITLE
Payment status remains pending after successful payment

### ISSUE THREAD

**Issue by aqdennis** [magento/magento2#27534]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.1.33
3. 1 store, 3 store views

### Steps to reproduce (*)

1. Create order and go to checkout
2. Checkout redirects to PSP, choose method to pay directly
3. Automatically return to success page in webshop
4. Check order in backend -> status is "Payment Pending"

### Expected result (*)

1. I expected the status to be "Payment received"

### Actual result (*)

1. Status is "Payment Pending"
2. When I open the order I can let it recheck the status and then it becomes Payment Received.....unfortunately it doesn't send the order confirmation anymore then.

### Note (*)
1. I tried the solution given in #18148, but without success.
2. It worked fine in Magento 2.2 .... the problem occurs now after updating to 2.3.2

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-27534-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27534-2-4-develop.instances.magento-community.engineering/admin_463e](https://i-27534-2-4-develop.instances.magento-community.engineering/admin_463e)
Login: `41f36247` Password: `c1dec0a2b488`
Instance will be terminated in up to 3 hours.

**Comment by aqdennis** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @aqdennis. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aqdennis, here is your [Magento instance](https://i-27534-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27534-2-4-develop.instances.magento-community.engineering/admin_fe81](https://i-27534-2-4-develop.instances.magento-community.engineering/admin_fe81)
Login: `332b75c5` Password: `37f3c0797bad`
Instance will be terminated in up to 3 hours.

**Comment by aqdennis** [comment]
The development version as far as I can see doesn't allow me to go to an external PSP, hence it cannot be tested whether on return the payment status is correctly set.
