### ISSUE TITLE
CookieManager is not used the first time the session cookie PHPSESSID is set

### ISSUE THREAD

**Issue by johnorourke** [magento/magento2#27531]
### Preconditions (*)

1. Seen in Magento 2.3.1, 2.3.4 and 2.4-develop
2. We are using a custom CookieManager to work around issue #26377 - https://github.com/Veriteworks/CookieFix
3. We discovered that the Magento session manager does not use CookieManager to set the PHPSESSID cookie, if it was not there before
4. This prevents Magento from setting custom options on the session cookie, if the user did not already have a session cookie
5. If the page makes any AJAX requests, the session cookie is set for those, so the CookieManager is then used and your session cookie will be updated with your custom options.

### Steps to reproduce (*)

1. Take a 2.4-develop instance
2. Create a custom cookie manager (eg. install veriteworks/CookieFix)
3. Visit the store front, then clear your cookies
4. Visit the store home page, and view the requests in the developer window
5. Observe that your custom option is not set in the response headers on the first request, but is set on requests after that

### Expected result (*)

1. The session cookie will always be written by the CookieManager class

### Actual result (*)

When you visit the front end without a session cookie:
1. `\Magento\Framework\Session\SessionManager->start()` is called
2. `\Magento\Framework\Session\SessionManager->start()` calls $this->initIniOptions to run ini_set for every session.xxxx setting
3. `\Magento\Framework\Session\SessionManager->start()` runs `session_start()` - at this point, PHP creates a session ID internally
4. `\Magento\Framework\Session\SessionManager->start()` runs `$this->renewCookie(...)`, but passes a blank session ID
5. `\Magento\Framework\Session\SessionManager->renewCookie(...)` does nothing because the session ID is blank
6. before it exists, PHP notices that the session cookie does not exist, and writes it out using only the options defined by ini_set() earlier.  The Magento CookieManager is not used.

### Possible fixes:
* in SessionManager::renewCookie, allow it to default to `session_id()`
* in SessionManager::start(), add `$sid = session_id();` after `session_start()` to ensure `renewCookie` works

**Comment by johnorourke** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @johnorourke. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @johnorourke, here is your [Magento instance](https://i-27531-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27531-2-4-develop.instances.magento-community.engineering/admin_9869](https://i-27531-2-4-develop.instances.magento-community.engineering/admin_9869)
Login: `43e96f4a` Password: `a9d49cf21b15`
Instance will be terminated in up to 3 hours.
