### ISSUE TITLE
Double country region in checkout

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#27546]
### Preconditions (*)

1. M2.3.4

### Steps to reproduce (*)
1. Run this query: 
```
select default_name, country_id from directory_country_region
group by default_name
having count(default_name) > 1
```
2. Or go to checkout and check every region for countries.
3. If you migrated from M1, you'll find find double regions for country AU, CH, MX allot!
4. If you have a new M2 installation you'll find 1 double region for CH: Jura

### Expected result (*)
1. Don't have double regions showing up in checkout:
![fixed_double_regions_checkout_MX](https://user-images.githubusercontent.com/17834386/78239792-73a55c00-74de-11ea-9798-d506d7579a91.png)

### Actual result (*)
1. Double regions showing up in checkout: ![double_regions_checkout](https://user-images.githubusercontent.com/17834386/78227614-cde9f100-74cd-11ea-86b8-39028f9313f5.png)

**Comment by PascalBrouwers** [comment]
If you have been affected by this, you can run this query to fixup your data in the database:
```
update quote_address,
(select min(region_id) as 'min',  max(region_id) as 'max', default_name from (select * from directory_country_region where default_name IN
(select default_name from directory_country_region
group by default_name
having count(default_name) > 1)) as t2
group by t2.default_name
) as t3
set region_id = min where region_id = max

update sales_order_address,
(select min(region_id) as 'min',  max(region_id) as 'max', default_name from (select * from directory_country_region where default_name IN
(select default_name from directory_country_region
group by default_name
having count(default_name) > 1)) as t2
group by t2.default_name
) as t3
set region_id = min where region_id = max

update customer_address_entity,
(select min(region_id) as 'min',  max(region_id) as 'max', default_name from (select * from directory_country_region where default_name IN
(select default_name from directory_country_region
group by default_name
having count(default_name) > 1)) as t2
group by t2.default_name
) as t3
set region_id = min where region_id = max


delete from directory_country_region where region_id IN (select region_id from (select max(region_id) as 'region_id', default_name from (select * from directory_country_region where default_name IN
(select default_name from directory_country_region
group by default_name
having count(default_name) > 1)) as t2
group by t2.default_name) as t3)
```
Updates the records to set the region_id to the lowest value of the double region for quote_address, sales_order_address, and customer_address_entity then it deleted the highest double value of the region in directory_country_region.
These queries have to run a couple of times depending on how many double regions you have. In my instance I had regions that were double 3 times, so I had to run these set of queries 3 times.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27546-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27546-2-4-develop.instances.magento-community.engineering/admin_20dc](https://i-27546-2-4-develop.instances.magento-community.engineering/admin_20dc)
Login: `41a536ca` Password: `a0b287650b00`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @PascalBrouwers 
I checked the issue on magento 2.4developn instance  I found `If you have a new M2 installation you'll find 1 double region for CH: Jura`
`Jura` region exist twice for with different country codes 

![image](https://user-images.githubusercontent.com/25526037/78457335-14567000-76c7-11ea-851d-dd774eea3e65.png)

**Comment by shikhamis11** [comment]
hi @PascalBrouwers 
I am closing this issue due to not activity 
feel free to open this issue
