### ISSUE TITLE
Guest checkout - No such entity with cartId = 0

### ISSUE THREAD

**Issue by abude** [magento/magento2#27542]
Guest checkout is not working when creating an order from admin or frontend with the following error:
`main.ERROR: No such entity with cartId = 0 [] []`
Breaking the session at the same time, requiring the admin to login again after pressing "place order" 

i already applied this: https://github.com/magento/magento2/pull/25307, doesn't seem to fix the issue.

### Preconditions (*)
1. Magento 2.3.4
2. PHP 7.2.28
3. **no extensions installed**

### Steps to reproduce (*)
[front-end]
1. go to frontend and add a product to cart as guest
2. go to checkout and fill in all the information
3. choose payflow pro  credit card to pay

[admin]
1. go and create an order
2. don't choose a customer, create a customer for guest checkout
3. select a product and add it to cart, fill all the information for a guest email
4. add credit card payflow pro, and press place order

### Expected result (*)
1. Transaction accepted or declined

### Actual result (*)
[front-end]
1. spinner shows on the screen and doesn't go off
2. error in the system.log 
`main.ERROR: No such entity with cartId = 0 [] []`
3. browser console, shows payflow/response 500 error

[admin]
1. error in the system.log:
`main.ERROR: No such entity with cartId = 0 [] []`
2. logs out the admin.
3. browser console, shows payflow/response 500 error

**Comment by abude** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @abude. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @abude, here is your [Magento instance](https://i-27542-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27542-2-4-develop.instances.magento-community.engineering/admin_4b2d](https://i-27542-2-4-develop.instances.magento-community.engineering/admin_4b2d)
Login: `2e4c6e93` Password: `7f5a2487551d`
Instance will be terminated in up to 3 hours.

**Comment by abude** [comment]
Honestly, i have no idea how can i test this using valid sandbox credentials on PayFlow Pro. without using the real data i have for my account. any ideas?

**Comment by dark2y** [comment]
This might be related to https://github.com/magento/magento2/issues/26840

**Comment by krishprakash** [comment]
Hi @abude. Thank you for your report.
Issue is similar to #26840 as commented by _dark2y_ and it will fixed in next 2.4.0 release
You can track the conversion from above link

**Comment by nitaipanda** [comment]
Guest checkout - No such entity with cartId.

![image](https://user-images.githubusercontent.com/20333565/91294059-96e6e580-e7b6-11ea-84b8-725f50831871.png)

**Comment by nitaipanda** [comment]
Guest checkout - No such entity with cartId = 141
![image](https://user-images.githubusercontent.com/20333565/91294412-15438780-e7b7-11ea-8d74-bc091618349d.png)

how to solve this issue.i have use magento 2.3.5

**Comment by nitaipanda** [comment]
Please help me i can not find the solution.please help me

**Comment by nitaipanda** [comment]
![image](https://user-images.githubusercontent.com/20333565/91294714-9569ed00-e7b7-11ea-8330-89af7bab04bc.png)

**Comment by portchris** [comment]
Be sure to check your theme directories for any mis-use of `Magento_Customer/js/customer-data` I have found on multiple occasions when debugging that many devs opt to manipulate customer data to achieve things. Here was one I found recently in the `placeOrder: function () {` method of a third-party payment gateway integration that had been internally manipulated within the theme:
```js
var clearData = {
  'selectedShippingAddress': null,
  'shippingAddressFromData': null,
  'newCustomerShippingAddress': null,
  'selectedShippingRate': null,
  'selectedPaymentMethod': null,
  'selectedBillingAddress': null,
  'billingAddressFromData': null,
  'newCustomerBillingAddress': null
};
customerData.set('checkout-data', clearData);
``` 
So search `app/design/frontend` for `Magento_Customer/js/customer-data` and see what naughties pop-up!

**Comment by atty31** [comment]
I'm getting the issue as @nitaipanda , just with another payment method. Any clue ? I have Magento  2.3.4

**Comment by pppwu** [comment]
@atty31 
please check my comment here https://github.com/magento/magento2/issues/5847#issuecomment-919747038
hope this will help.
