### ISSUE TITLE
Catalog ImageUploader will not return the new file name

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#27558]
### Preconditions (*)

1. Magento version 2.3.*

### Steps to reproduce (*)

1. Use the method `\Magento\Catalog\Model\ImageUploader::moveFileFromTmp` as part of a file uploader,
2. Have it upload of a file with a name that is already on the system,

### Expected result (*)

1. Image name returned should be that of the new image path e.g. image_1.jpeg when a new image name is needed,

### Actual result (*)

1. The original image name is returned,

Note: I have not tested this with the category image upload but looking at the code I would assume if the category image name already exists then it would happen in the same way.

**Comment by lampham2141993** [comment]
Hi, @magento-engcom-team
I tested on magento2 2.4-develop and can not replicate
Image before:
![before](https://user-images.githubusercontent.com/62533128/78343752-7fb81900-75c5-11ea-9d20-b53ac7d7fb18.png)

Image after:
![after](https://user-images.githubusercontent.com/62533128/78343771-89da1780-75c5-11ea-8645-580846db4040.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27558-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27558-2-4-develop.instances.magento-community.engineering/admin_15d8](https://i-27558-2-4-develop.instances.magento-community.engineering/admin_15d8)
Login: `6a115b82` Password: `cd245db6061b`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
Hi, @dmanners I am not able to reproduced on Magento 2.4-develop instance.

![image](https://user-images.githubusercontent.com/50358141/78348487-bd19a800-75bf-11ea-826d-413b6eb5038b.png)
![image](https://user-images.githubusercontent.com/50358141/78348500-c440b600-75bf-11ea-90eb-26b24c6377f2.png)
