### ISSUE TITLE
Product sort by SKU

### ISSUE THREAD

**Issue by Parrotdise** [magento/magento2#27555]
Each time I attempt to sort product by SKU this error message _[Something went wrong with processing the default view and we have restored the filter to its original state]_ appears and I can not access any products.   That is the error message is always on the admin product page whether I log out or refresh.

I am using Magento 2.3.4, multi-store and advance custom products.

If anyone else logs into the administrator they can access the products so the only way I can fix this is to delete my user profile and create a new one.

Has anyone else experienced this problem?

**Comment by lampham2141993** [comment]
Hi @magento-engcom-team I can't replicate on Magento 2.4-develop with sample database (2048 items).

**Comment by Parrotdise** [comment]
Summary of the issue:
Sorting and now filtering on products in admin produces this error message [Something went wrong with processing the default view and we have restored the filter to its original state] and thereafter the page locks and can not access any products. That is; the error message is always on the admin product page whether I log out or refresh.  So far,  the only way to fix this is to delete the user profile and create a new one, however; all user profiles are now locked out of the products.

Information on your environment:
Magento 2.3.4 Ubuntu with multi-store and advance custom products extensions.

Steps to reproduce:
Search on products or sort on SKU

Expected and actual results:
Should get list of products upon search but the screen freezes with the message above. 

Can you provide detailed instructions for this?  "Please make sure that the issue is reproducible on the vanilla Magento"

**Comment by AnnaShepa** [comment]
Hi @Parrotdise  thank you for the report. Unfortunately I cannot reproduce the problem, so far as I understood for you it was only one user with the problem, so looks like some accidental issue. 

> Can you provide detailed instructions for this? "Please make sure that the issue is reproducible on the vanilla Magento"

You can write in comment to the ticket `@magento give me 2.4-develop instance` and check if you can reproduce it on clean last version of magento

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by alex38** [comment]
I have this issue as well, sorting on SKU. 

@Parrotdise - for what it's worth, I have an alternative to abandoning those user accounts altogether. There seem to be several different sorting/filtering/searching combinations that kill Magento 2 list pages on products and cms pages. The list page is then essentially locked and permanently broken to that user.

You can "fix" it by deleting all entries in the ui_bookmark database table for that specific user, like:
`DELETE FROM ui_bookmark WHERE user_id = 2;`
