### ISSUE TITLE
Youtube Background problem & Cannot upload any video to library

### ISSUE THREAD

**Issue by mchansrsw** [magento/magento2#27556]
Hi, I have been troubled by this problem for quite some time. 

I made a slider with youtube video background, at first it ran smooth but after a few trial, i could see the youtube video name on top of it and then some featured content / suggestions at the bottom, these bugs all flashes for 1 sec and then gone, it is so annoying. 

Then I moved on to HTML5 video, I've prepared a mpg / mpeg video and this time it says ERROR. 

Is there any solution to the above problems? Thanks.

**Comment by sudheers-kensium** [comment]
Hi @mchansrsw Kindly update all the details for reproduce the issue
