### ISSUE TITLE
Order item currency price is overridden with base price in the Webapi

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#27562]
### Preconditions

1. Magento 2.3.4
2. **Website 1** has default currency **EUR**
3. **Store 1** (which related to **Website 1**) has default currency **USD**

### Steps to reproduce

1. Create order in **Store 1** 
2. Get information about order via API: `/v1/order/%number%`

### Expected result

1. Order currency is set to `EUR` ✅
2. Order item attribute `base_price` contains **base item price (in EUR)** ✅
3. Order item attribute `base_price_incl_tax` contains **base item price (in EUR) + tax (if applied)** ✅
4. Order item attribute `price` contains **converted to store currency item price (in USD)** ✅
5. Order item attribute `price_incl_tax` **contains converted to store currency item price (in USD) + tax (if applied)** ✅

### Actual result 

1. Order currency is set to `EUR` ✅
2. Order item attribute `base_price` contains **base item price (in EUR)** ✅
3. Order item attribute `base_price_incl_tax` contains **base item price (in EUR) + tax (if applied)**
4. Order item attribute `price` contains **base item price (in EUR)** ❌
5. Order item attribute `price_incl_tax` **contains converted to store currency item price (in USD) + tax (if applied)** ✅

### Additional information
- Possibly related issue #22215
- In the `quote_item` table `price` is already contains base price instead of calculated, so this value is copied to order item as well.

I believe this issue should be fixed because it seems strange when only in the API attribute `price` doesn't cover order item price currency convertations while even `price_inc_tax` does.

**Comment by AltayAkkus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AltayAkkus, here is your [Magento instance](https://i-27562-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27562-2-4-develop.instances.magento-community.engineering/admin_9e8c](https://i-27562-2-4-develop.instances.magento-community.engineering/admin_9e8c)
Login: `4a5b050a` Password: `5f2dbb244a52`
Instance will be terminated in up to 3 hours.

**Comment by johnorourke** [comment]
I had a similar issue where custom_price was being changed from quote currency to base currency.

It's likely fixed by this change released in 2.4.0: https://github.com/magento/magento2/commit/c1e9091d0e2cb6f9bafca030373bce8b023b3870
