### ISSUE TITLE
Duplicate address by order from admin

### ISSUE THREAD

**Issue by TadeuRodrigues** [magento/magento2#27568]
### Preconditions (*)
1. magento 2.3.4 or 2.4

### Steps to reproduce (*)
1. Create a new order from admin.

### Expected result (*)

1. A new order only without any address change.

### Actual result (*)
1. A new address to each order I made.

**Comment by TadeuRodrigues** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27568-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27568-2-4-develop.instances.magento-community.engineering/admin_cfb7](https://i-27568-2-4-develop.instances.magento-community.engineering/admin_cfb7)
Login: `0729e43d` Password: `fd6540a1728b`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi, @TadeuRodrigues,
I have Place order throw the admin as per your steps. This step is not enough to reproduce the issue.
So can you please provide me the steps of reproducing in detail or send me the video?

Thanks.

**Comment by TadeuRodrigues** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TadeuRodrigues. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TadeuRodrigues, here is your [Magento instance](https://i-27568-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27568-2-4-develop.instances.magento-community.engineering/admin_01ca](https://i-27568-2-4-develop.instances.magento-community.engineering/admin_01ca)
Login: `0a32c290` Password: `83e300b9804a`
Instance will be terminated in up to 3 hours.

**Comment by TadeuRodrigues** [comment]
@ajijshekh123 
![Captura de tela de 2020-04-10 12-48-16](https://user-images.githubusercontent.com/1669081/79003871-e7bcb100-7b29-11ea-8d07-a28093d53b64.png)

After made a order by admin area
![Captura de tela de 2020-04-10 12-49-49](https://user-images.githubusercontent.com/1669081/79003916-0622ac80-7b2a-11ea-9d17-6ac7731a7a2d.png)

I just made a order by admin, let's try talk on slack.

**Comment by danielpugh** [comment]
this is happening to us - just had to delete 50 duplicate addresses for a single customer
