### ISSUE TITLE
Error during uninstall

### ISSUE THREAD

**Issue by smoskaluk** [magento/magento2#27565]
### Preconditions (*)

1. Magento 2.4 develop

### Steps to reproduce (*)

1. Run CLI command <setup:uninstall>2.

### Expected result (*)

1. Uninstall successful

### Actual result (*)

![image](https://user-images.githubusercontent.com/27818516/78369512-f9ec9b80-75cd-11ea-927c-8ddf0979d8b1.png)

**Comment by sdzhepa** [comment]
Hello @smoskaluk 

Thank you for your report.

Unfortunately, I am not able to reproduce this issue on the latest `2.4-develop` branch by provided steps from the description.

I suppose some important preconditions or steps are missed.

Let me describe what exactly I did to reproduce it:

**Preconditions**
1. Clone the latest Magento code from `2.4-develop` from git
```
git clone https://github.com/magento/magento2.git
```
2. Install Magento. I used CLI installation

**CASE 1**
I tried to execute CLI expect that you specified in the description
```
/instance_2# setup:uninstall2
bash: setup:uninstall2: command not found
```
Result:
```
bash: setup:uninstall2: command not found
```

**CASE 2**
I tried to execute 
```
php bin/magento setup:uninstall2
```

Result:
```
Command "setup:uninstall2" is not defined.

  Did you mean one of these?
      cron:install
      i18n:uninstall
      module:uninstall
      setup:backup
      setup:config:set
      setup:cron:run
      setup:db-data:upgrade
      setup:db-declaration:generate-patch
      setup:db-declaration:generate-whitelist
      setup:db-schema:upgrade
      setup:db:status
      setup:di:compile
      setup:install
      setup:performance:generate-fixtures
      setup:rollback
      setup:static-content:deploy
      setup:store-config:set
      setup:uninstall
      setup:upgrade
      theme:uninstall
```

**CASE 3**
I tried to execute uninstall command as described in DevDocs: https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-uninstall.html#instgde-install-uninstall

```
php bin/magento setup:uninstall
```

Result:
```
Are you sure you want to uninstall Magento?[y/N] y

Starting Magento uninstallation:
Cache cleared successfully
Cleaning up database `magento_i1`
File system cleanup:
/var/www/magento/instance_2/var/cache
/var/www/magento/instance_2/var/composer_home
/var/www/magento/instance_2/var/log
/var/www/magento/instance_2/var/page_cache
/var/www/magento/instance_2/app/etc/config.php
/var/www/magento/instance_2/app/etc/env.php
[SUCCESS]: Magento uninstallation complete.
```
