### ISSUE TITLE
Currency rates import service is loading all rate for activated currencies.

### ISSUE THREAD

**Issue by praful-rajput** [magento/magento2#2757]
Its loading rate only of EUR & USD. Is there any bug ?
![curerncy-import](https://cloud.githubusercontent.com/assets/648859/11896627/361079aa-a5ae-11e5-9f41-492d0571e01f.png)

**Comment by paliarush** [comment]
Thanks for reporting this issue! Internal ticket MAGETWO-47492

**Comment by daim2k5** [comment]
Hi @paliarush any update on this?

**Comment by arkadiych** [comment]
Seems WebserviceX Currency Convertor is out of order.

Related stackexchange issue http://magento.stackexchange.com/questions/91292/currency-rate-not-importing-correctly-from-webservicex.

**Comment by arkadiych** [comment]
@vasuscoin, @daim2k5  Fixer.io as additional currency converter service has been added.

**Comment by daim2k5** [comment]
Thanks @arkadiych

**Comment by redboxmarcins** [comment]
fixer.io has very limited number of currencies - for example there is no AED

**Comment by daim2k5** [comment]
@redboxmarcins please don't comment on closed issues. If you know a better service maybe you can open a new issue (so we can discuss this) or even a PR?
