### ISSUE TITLE
Enhanced E-commerce | Wrong block_name defined so no impressions are pushed to DataLayer

### ISSUE THREAD

**Issue by jasperzeinstra** [magento/magento2#2759]
In `vendor/magento/module-google-tag-manager/view/frontend/layout/catalog_category_view.xml` the `block_name` is defined as `category.products.list`. But in `vendor/magento/module-google-tag-manager/view/frontend/templates/js.phtml` there's a for each that uses `product_list`. The value `category.products.list` should also be used in `js.phtml`. This is the correct name of the block.

**Comment by davidalger** [comment]
@jasperzeinstra The google tag manager is an EE only module. Please report this to the enterprise support team and work with them to get a solution. Thanks!
