### ISSUE TITLE
Downloadable Product links not available for mixed orders (downloads & shipping products) after payment

### ISSUE THREAD

**Issue by plastikschnitzer** [magento/magento2#27590]
### Preconditions (*)

1. Magento CE 2.3.4 on Ubuntu 18.04 LAMP stack migrated from Magento 1.9.4.1

### Steps to reproduce (*)

1. Place an order with downloadable products **and** shipping products
2. Choose any online direct payment method such as credit card or paypal
3. Customer gets the email with download links
2. Go to customer account and try to download the products

### Expected result (*)

1. Download links should be available for download right after payment.

### Actual result (*)

1. Cannot download products, "Link not available".
The order is on status processing, invoice created with status "paid" which is the precondition to make downloads available.

### Additional details
confirmation in multiple scenarios: https://github.com/magento/magento2/issues/27590#issuecomment-609464544 

### Further observations

If I click on "ship order" and the order changes the status to status "complete" links are activated! Its a bad workaround as customers expect their downloads to be available right after payment.

If I purchase digital products only, the order status is directly on "complete" and links are available.

I guess it must be a bug in the order status scheme in relation to download products availability, my expected behavior is the exact way it works in Magento 1 and also what I read from the devdocs for Magento 2. 

Please note there is another bug with downloadable products and order status in case of zero subtotal orders which end on status closed: https://github.com/magento/magento2/issues/25177
So it looks to me like the whole magento_downloadable module is still buggy, maybe this ticket is related in some way?

**Comment by plastikschnitzer** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @plastikschnitzer. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @plastikschnitzer, here is your [Magento instance](https://i-27590-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27590-2-4-develop.instances.magento-community.engineering/admin_11b8](https://i-27590-2-4-develop.instances.magento-community.engineering/admin_11b8)
Login: `91a8b15c` Password: `aef91407edff`
Instance will be terminated in up to 3 hours.

**Comment by pevik** [comment]
@plastikschnitzer I'm sorry, that was me who terminated your login. I logged out immediately.

**Comment by plastikschnitzer** [comment]
@pevik no problem ;-)

@magento-engcom-team thank you very much for offering the testing instance. 

Due to timeout I could only test a part of it, so @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @plastikschnitzer. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @plastikschnitzer, here is your [Magento instance](https://i-27590-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27590-2-4-develop.instances.magento-community.engineering/admin_47e9](https://i-27590-2-4-develop.instances.magento-community.engineering/admin_47e9)
Login: `20631899` Password: `4f1a6fb57e7c`
Instance will be terminated in up to 3 hours.

**Comment by plastikschnitzer** [comment]
@m2-assistant yes I was able to reproduce the issue on the povided magento testing instance.

I run a number of tests, see my result of all test cases:

### 1. Place an order with simple and downloadable product and payment by paypal website payment standard payment:

## Expected result:
Order Status processing, invoice created, download  available
## Actual result:
Order Status processing, invoice created, download **not** available
If shipping is created, download is available

### 2. Place an order with simple and downloadable product and payment with check money order and manual invoice creation:

## Expected and Actual result:
Order status processing, download is available

### 3. Place an order with downloadable product only and payment with PayPal website payment standard

## Expected and actual result:
Order status processing, download is available

### Conclusion:
In case of combined orders it seems to be a difference if the invoice creation is triggered by an extenal payment platform such as PayPal (in my own shop I can also confirm the bug with the Stripe.com payment gateway) or if the invoice is created manually in Magento admin.

I have not tested all other possible combinations of product types in one order (grouped, virtual, bundle)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33836` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by maynard321** [comment]
The file \vendor\magento\module-downloadable\Observer\SetLinkStatusObserver.php has the correct logic to do this
in 2.3.5:
```
            foreach ($order->getAllItems() as $item) {
                if ($item->getProductType() == \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE
                    || $item->getRealProductType() == \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE
                ) {
                    if ($order->isCanceled() || in_array($item->getStatusId(), $expiredStatuses)) {
                        $downloadableItemsStatuses[$item->getId()] = $linkStatuses['expired'];
                    } else {
                        $downloadableItemsStatuses[$item->getId()] = $linkStatuses['avail'];
                    }
                }
            }
```
But there is a problem: $item=>getId() returns null, and so the logic fails because the $downloadableItemsStatuses array is useless

**Comment by maynard321** [comment]
> 
> 
> The file \vendor\magento\module-downloadable\Observer\SetLinkStatusObserver.php has the correct logic to do this
> in 2.3.5:
> 
> ```
>             foreach ($order->getAllItems() as $item) {
>                 if ($item->getProductType() == \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE
>                     || $item->getRealProductType() == \Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE
>                 ) {
>                     if ($order->isCanceled() || in_array($item->getStatusId(), $expiredStatuses)) {
>                         $downloadableItemsStatuses[$item->getId()] = $linkStatuses['expired'];
>                     } else {
>                         $downloadableItemsStatuses[$item->getId()] = $linkStatuses['avail'];
>                     }
>                 }
>             }
> ```
> 
> But there is a problem: $item=>getId() returns null, and so the logic fails because the $downloadableItemsStatuses array is useless

Ignore that, SetLinkStatusObserver is called in the purchase process but does nothing because the items have not been saved.
SaveDownloadableOrderItemObserver is where the fix lies.
Changing:
```
                $linkStatus = \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_PENDING;
                if ($orderStatusToEnableItem == \Magento\Sales\Model\Order\Item::STATUS_PENDING
                    || $orderItem->getOrder()->getState() == \Magento\Sales\Model\Order::STATE_COMPLETE
                ) {
                    $linkStatus = \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_AVAILABLE;
                }
```
to
```
                $linkStatus = \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_PENDING;
                if ($orderStatusToEnableItem == \Magento\Sales\Model\Order\Item::STATUS_PENDING
                    || $orderItem->getOrder()->getState() == \Magento\Sales\Model\Order::STATE_PROCESSING   // added line
                    || $orderItem->getOrder()->getState() == \Magento\Sales\Model\Order::STATE_COMPLETE
                ) {
                    $linkStatus = \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_AVAILABLE;
                }
```
seems to work.
An order will only be PROCESSING when it has been invoiced, so it makes sense to allow the download. $orderStatusToEnableItem can only be PENDING or PROCESSING.

**Comment by zaximus84** [comment]
@maynard321 
I have a [PR for this issue](https://github.com/magento/magento2/pull/28378). I modified the same area you did, but I removed the reference to order state and replaced it with a check of the item state. This should be a lot more reliable than trying to identify valid order states, especially if there are future core changes or customizations around order state.

**Comment by plastikschnitzer** [comment]
Dear bot, issue is still relevant. Please respect labels that are put in place by your other bot-friends around here ;-)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
