### ISSUE TITLE
Wishlist add to cart quantity

### ISSUE THREAD

**Issue by alexey-svistunov** [magento/magento2#2760]
Can't set product qty adding product to cart. If you set number in qty field and click "add to cart" button only one product is added to cart. 

![Whishlist issue preview 1](http://i.imgur.com/SnYzmmW.png)

As you can see qty field is set to add 5 products but only 1 product is added.

![Whishlist issue preview 2](http://i.imgur.com/K7TcJQd.png)

It's not quite intuitive to have to click "Update wishlist" button to save qty.

**Comment by ilol** [comment]
That is by design. Agree, that is controversial behavior, but not a bug.

**Comment by smdevdk** [comment]
This is absolutely ridiculous.
