### ISSUE TITLE
The Rating Stars are now showing on Upsell and Related Products

### ISSUE THREAD

**Issue by choma828** [magento/magento2#2761]
I'm making a magento 2 theme.

I added below code for showing rating stars on upsell and related products, but it doesn't show the rating stars in /app/design/frontend/Vendor/ThemeName/Magento_Catalog/templates/product/list/items.phtml file.

```
... ...
case 'upsell':
... ...
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
... ...
```

Is this bug or what am I missing?

Anyone know how to show the rating stars for upsell and related products?

Regards

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by sivajik34** [comment]
@choma828 have you got solution for this? same thing i need.

**Comment by phuocpro1326** [comment]
change:
case 'related':
....
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
----
and 
<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
to 
<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>

**Comment by thaddeusmt** [comment]
Thanks @phuocpro1326 
That 3rd boolean parameter of `getReviewsSummaryHtml()` is called `$displayIfNoReviews`, so silly me, I thought it could stay `false`. But nope, if you want to display the rating when there IS a rating ("reviews") you still need to set `$displayIfNoReviews` to `true`. Huh.
