### ISSUE TITLE
Issue with creating Ui component form in customer edit section

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2762]
Hi,

layout file is:customer_index_edit.xml

``` xml
<?xml version="1.0"?>
<!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
    <body>
        <referenceContainer name="content">
            <uiComponent name="seller_form"/>
        </referenceContainer>   
    </body>
```

base/ui_component/seller_form.xml

in this file below lines giving error that " Element with ID 'tabs_nav' already exists."

``` xml
<item name="layout" xsi:type="array">
        <item name="type" xsi:type="string">tabs</item>
        <item name="navContainerName" xsi:type="string">left</item>
</item>
```

Please help

**Comment by slavvka** [comment]
Hi @rajawat02, could you please give us more details on what you're doing. What are the full paths for files specified? What are you trying to do with those files?

**Comment by ghost** [comment]
Hi @slavvka  Actually i am trying to add a new tab containing Form fields in Admin customer edit section. I have created tab successfully  with form. But when i am submitting save Customer or Save and Continue button, I am not able get the record of my form Neither in Customer Save Controller nor in Observer.

Thanks

**Comment by slavvka** [comment]
Could you please give us all changed and introduced files as it is hard to understand the problem.

**Comment by vzabaznov** [comment]
Hi, @rajawat02 thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
