### ISSUE TITLE
Magento 2 mode maintenance is not working Load Balancer of AWS

### ISSUE THREAD

**Issue by luanpereira** [magento/magento2#27626]
Hello,
when I use the command to enable maintenance mode with an exception parameter of ip and yet my instance is below an AWS load balancer this does not work.

However, if I remove the load balancer and start pointing directly to the magento instance, it works exception parameter of ip.

### Preconditions 
1. Magento 2.3.4
2. AWS with load balancer classic

### Steps to reproduce
1. bin/magento maintenance:enable --ip=xxx.xxx.xxx.xxx
2. cat var/.maintenance.ip >>> xxx.xxx.xxx.xxx

### Expected result
1. Magento goes into maintenance mode except for the origin of my ip.

### Actual result
1. If I have the load balancer magento goes into maintenance mode even on my ip.
2. The exception of origin of my ip only works if I access the site directly through the AWS instance

**Comment by luanpereira** [comment]
no, because it depends on the cloud where magento is hosted.

**Comment by ihor-sviziev** [comment]
@luanpereira did you add reading IP address from X-Forwarded-For header?
Related PR https://github.com/magento/magento2/pull/23219

**Comment by luanpereira** [comment]
is the same @ihor-sviziev, thanks for the help.
