### ISSUE TITLE
When creating new customerin magento version 2.3.4 its throwing an error invalid form key

### ISSUE THREAD

**Issue by ravichandrarv** [magento/magento2#27629]
### Preconditions (*)

1. Magento version 2.3.4
2. Php version 7.2
3. Mysql version 8

### Steps to reproduce (*)

1. Install magento with composer by specifiying version 2.3.4
2. After successful magento installation please try to create customer account
3. After filling required and  mandatory fields click on create an account.
4. Page will reload and throws an error.

### Expected result (*)

1. It should allow to create new customer account.

### Actual result (*)

1. Page will reload and throws an error message " invalid form key".

![magento_new_customer_create_error](https://user-images.githubusercontent.com/15813454/78504621-09b1de80-778c-11ea-903b-4d04e777ba60.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27629-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27629-2-4-develop.instances.magento-community.engineering/admin_ba5d](https://i-27629-2-4-develop.instances.magento-community.engineering/admin_ba5d)
Login: `00e6f201` Password: `2da810c99fc2`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @ravichandrarv. Thank you for your report.
Can not reproduce the issue in vanilla magento instance
Feel free to reopen the issue if you confirm the issue in latest vanilla instance
