### ISSUE TITLE
Full page cache clearing auto after few minutes

### ISSUE THREAD

**Issue by vipin12117** [magento/magento2#27632]
### Preconditions (*)
Any product or category page save in full page cache. Try after few minutes it clear all cache automatically. Another way to test, save any core config setting in admin. Magento show notification in top about to clear cache. Keep it few minutes and login back to admin. You will see cache cleared.
1. Login to Magento 2.3.4 admin and save any config.
2. You will see cache clear warning on top.
3. Wait for few minutes and login back to admin.
4. You will see cache cleared and there is no more any cache warning message.

### Steps to reproduce (*)
1. Login to Magento 2.3.4 admin and save any config.
2. You will see cache clear warning on top.
3. Wait for few minutes and login back to admin.
4. You will see cache cleared and there is no more any cache warning message.

### Expected result (*)

1. Cache should not clear automatically until do it manually.

### Actual result (*)

1. Caching clearing automatically which is creating lots of issues.

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-27632-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27632-2-4-develop.instances.magento-community.engineering/admin_af77](https://i-27632-2-4-develop.instances.magento-community.engineering/admin_af77)
Login: `7b7b23e9` Password: `e349a2e807d4`
Instance will be terminated in up to 3 hours.

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-27632-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27632-2-4-develop.instances.magento-community.engineering/admin_42f8](https://i-27632-2-4-develop.instances.magento-community.engineering/admin_42f8)
Login: `165e44fc` Password: `d792c01c01cc`
Instance will be terminated in up to 3 hours.

**Comment by vipin12117** [comment]
Just for update, I am facing that issue on 2.3.4.

**Comment by VigneshVenkatesan154** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VigneshVenkatesan154. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VigneshVenkatesan154, here is your [Magento instance](https://i-27632-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27632-2-4-develop.instances.magento-community.engineering/admin_3e87](https://i-27632-2-4-develop.instances.magento-community.engineering/admin_3e87)
Login: `40cfd4ec` Password: `32afa321e779`
Instance will be terminated in up to 3 hours.

**Comment by VigneshVenkatesan154** [comment]
@vipin12117 The issue is not reproducing. Firstly I enabled the cash on delivery option and checked the full page cache is disabled and the warning message gets displayed. After 15 minutes I logged in back to admin checked the message and full-page cache both remains the same as before
