### ISSUE TITLE
Product alert not working when backorders are enabled

### ISSUE THREAD

**Issue by studio16** [magento/magento2#27639]
### Preconditions (*)

Magento 2.3.4
Edit/Create a product,
Set Manage Stock to "Yes",
Set Qty to "0",
Enable Backorders
Set Stock Status to "In Stock".
store->config->catalogue->catalogue
Set catalog_productalert_allow_stock to Yes 

### Steps to reproduce (*)
1.Visit the product page

### Expected result (*)

1.  "Notify me when this product is in stock" link

### Actual result (*)

1.  No link there

The link only shows when "is_in_stock" is set to no, tehrefor backorders not working.
So u can't have both out of the box.
By doing a module override and showing the link based on the actual stock quantity instead of the "is_in_stock" attribute front-end users can actually subscribe themselves. 

Next issue.... the trigger of sending the actual email seems to be that same "is_in_stock" field causing emails to be send even when the stock quantity is still 0 because.....again....is_in_stock needs to be true if u want to use backorders.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27639-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27639-2-4-develop.instances.magento-community.engineering/admin_6f53](https://i-27639-2-4-develop.instances.magento-community.engineering/admin_6f53)
Login: `f42c76bf` Password: `f1c045352360`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @studio16. Thank you for your report.
Seems this is expected behavior of magento. Once back order is enabled then notify link should not be display and when product in out of stock then display the Notify link

**Comment by studio16** [comment]
what does backorders have to do with the fact that I as a shopper wants to know when a product is in stock again?

**Comment by studio16** [comment]
Actually this is part of the other issue not being able to use backorders in combination with is_in_stock set to false which makes more sense than having is_in_stock set to true while in fact stock = 0 which was discussed here:
https://github.com/magento/magento2/issues/10304
and was closed for no apparent reason

**Comment by krishprakash** [comment]
Hi @studio16. Refer the _[Link](https://docs.magento.com/m2/ce/user_guide/catalog/inventory-backorders.html)_ for Back order understanding and Yes, as per your given link this is expected behavior not an issue.Thank you !!

**Comment by studio16** [comment]
Again what does the "Allow Alert When Product Comes Back in Stock"  has to do with being able to have backorders?

**Comment by studio16** [comment]
shopper A may want to place an order anyway -> backorder
shopper B who perhaps needs to pay in advance wants to wait till the product is in stock again and wants to get notified when it does instead of paying not knowing when the product ever will arrive.

**Comment by krishprakash** [comment]
Kindly refer below link for back in stock alert:
https://docs.magento.com/m2/ce/user_guide/catalog/inventory-product-alerts.html
Thank you !!

**Comment by studio16** [comment]
"The Sign up to get notified when this product is back in stock message appears only when Inventory Stock Options - Display Out of Stock Products is set to Yes."

it's set to yes and still no link
