### ISSUE TITLE
Product attribute Text swatch only shows admin store value instead of current store value

### ISSUE THREAD

**Issue by yash-patadia** [magento/magento2#27635]
This issue precise on the product page, mini-cart, cart page & checkout order summary

### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Add two stores, store-one, store-two
2. Create a product attribute with text-swatch type (i.e text_swatch)
3. Add attribute option **admin value: test**, **store value: store-test**
![image](https://user-images.githubusercontent.com/58852103/78563449-9a45f880-7838-11ea-9faa-0abca8c82a46.png)
4.Assign text_swatch attribute value to any product

### Expected result (*)

1. Product Page, on selection of **store-test** option label should be **store-test** not **test**

### Actual result (*)

1. Product Page
![image](https://user-images.githubusercontent.com/58852103/78563673-fc066280-7838-11ea-9e52-e69f74c6276e.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27635-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27635-2-4-develop.instances.magento-community.engineering/admin_db22](https://i-27635-2-4-develop.instances.magento-community.engineering/admin_db22)
Login: `ca0a74b2` Password: `5f3015f03203`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@yash-patadia Please add value description, that description will display on frontend .
![image](https://user-images.githubusercontent.com/50358141/78571884-5fe25880-7844-11ea-9f68-1c15c0f9e979.png)

**Comment by yash-patadia** [comment]
@sudheers-kensium thanks.

Apologies for wasting team's time for such a silly issue.
