### ISSUE TITLE
Stock status inconsistency: product table vs. product edit mode

### ISSUE THREAD

**Issue by Notranslator** [magento/magento2#27631]
### Summary (*)
Preconditions:
1. Magento CE 2.2.3 is installed.
2. Shop is working fine except the problem below.

Steps to reproduce:
1. Create a simple product, quantity = 1 and stock status = 1.
2. Verify that the product is visible in the shop and can be ordered.
3. Order the product.

Expected result:
1. Quantity = 0
2. Stockstatus = 0 ("out of stock").
3. When applying the filter for stock status in the layered navigation, the item will not be showed any more.

Actual result:
1. Quantity = 0.
2. Stockstatus = 0 in product edit mode, but Stockstatus = 1 in product table overview.
3. When applying the filter for stock status in the layered navigation, the item is still being displayed but with status "Out of stock".

### Examples (*)
After I placed the order:
![AfterPlacingOrder](https://user-images.githubusercontent.com/4790836/78538862-f6395e80-77f1-11ea-9d0c-959329c3f034.JPG)
Then I apply the filter "In stock"
![AfterPlacingOrderAfterApplyingFilter](https://user-images.githubusercontent.com/4790836/78538918-0b15f200-77f2-11ea-89a2-c2a56a96fa88.JPG)
It filters out only two of the three items that are not in stock. One is still there which is the product which I ordered.
When I look at the producttable for this product, I see "In stock":
![producttable](https://user-images.githubusercontent.com/4790836/78539045-3c8ebd80-77f2-11ea-9d96-748254596b34.JPG)
When I click to edit the product, I see it is out of stock:
![ProductEdit](https://user-images.githubusercontent.com/4790836/78539107-529c7e00-77f2-11ea-8f86-100d724f6903.JPG)

### Proposed solution
1. Tell me in which table Magento is looking for the stockstatus that is displayed in the product table.
2. What is causing the inconsistency in stock status between the product table and the product edit mode?
3. Most important, how to get the correct stock status in the product table? I guess this will also be used for filtering in the layered navigation and solves the problem there.
4. If it is a (known) bug, please let me know.

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-27631-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27631-2-4-develop.instances.magento-community.engineering/admin_8e96](https://i-27631-2-4-develop.instances.magento-community.engineering/admin_8e96)
Login: `54438d9c` Password: `9e55bb95f84b`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
Hi @magento-engcom-team  
This issue is not reproducible on 2.4-develop.
I followed the procedure described @Notranslator  but after I created an order the stock status changed from "In Stock" to "Out of Stock"

**Comment by Notranslator** [comment]
Hi, thanks for testing.
Can you confirm that the status both in the product table AND when editing the product has "out of stock" status?

**Comment by Notranslator** [comment]
I found some more about this issue. The index has not been refreshed. I expected this query to yield zero results:

SELECT * FROM `mg_catalog_product_index_eav` 
Join mg_cataloginventory_stock_status on product_id = entity_id
where attribute_id= 115 and store_id =1
and value <> stock_status  

Even after refreshing all indexes in the Magento backend, I still get results from this query.
It looks like that after an order the index is not updated (setting in backend is "update on save").

Anyone can help?

**Comment by Notranslator** [comment]
php bin/magento indexer:reindex
does not do the trick either

Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Product Flat Data index has been rebuilt successfully in 00:00:04
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:01
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:01
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:08
