### ISSUE TITLE
500 error in order view with configurable products & sales rule

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#27641]
### Preconditions (*)

1. Magento 2.3.3 / 2.3.4

### Steps to reproduce (*)

1. Create a configurable product with few options
2. Create a sales rule which works on this configurable product 
3. Buy that product using that sales rule

### Expected result (*)

1. You can view the order

### Actual result (*)

1. 500 error in this file

`vendor/magento/module-configurable-product/Plugin/SalesRule/Model/Rule/Condition/Product.php`

`$childProduct = current($model->getChildren())->getProduct();`

this peace of code returns a boolean type value:
`$current($model->getChildren())`

and breaks the order view

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27641-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27641-2-4-develop.instances.magento-community.engineering/admin_6cc6](https://i-27641-2-4-develop.instances.magento-community.engineering/admin_6cc6)
Login: `c56f9298` Password: `bf5c256481dc`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@qsolutions-pl I am not able to reproduced on Magento 2.4-develop instance. Please check below.

Frontend:
![image](https://user-images.githubusercontent.com/50358141/78678488-a5fff080-7906-11ea-831a-040a0aeacec7.png)

Admin:
![image](https://user-images.githubusercontent.com/50358141/78678530-b1ebb280-7906-11ea-81b1-e5e5ab4277dc.png)

**Comment by Perzonallica** [comment]
Hello,

we had the same issue: 

`Fatal error: Uncaught Error: Call to a member function getProduct() on bool in /var/www/magento-v2/vendor/magento/module-configurable-product/Plugin/SalesRule/Model/Rule/Condition/Product.php:61`

But interestingly not during simple checkout, but when someone wanted to remove an item during **Check Out with Multiple Addresses**.

@qsolutions-pl I managed to "solve" it though... I ran indexer:reindex in terminal, removed all items from my cart and re-added them and it just started to work.

@sudheers-kensium Maybe would be good to put there some check which prevents to load product from a null?

**Comment by panthar1** [comment]
I believe the reason this error occurs is if you or a customer has a product in the "shopping cart" that has been deleted/no longer exists.

**Comment by hammockvienna** [comment]
> I believe the reason this error occurs is if you or a customer has a product in the "shopping cart" that has been deleted/no longer exists.

No, the issue exists also if you use an inkognito browser.
