### ISSUE TITLE
Magento2 dashboard does not respond.

### ISSUE THREAD

**Issue by aalve1964** [magento/magento2#2764]
Hi guys I am newbie here, and I am having dificulties with admin login. Sorry if this issue is already old.
Magento2 installed successful but can't login at all with Chrome (I know there are some cookie problems give me eror too many redirects) but with Mozilla I am experience this issue:I can login with admin link but dashboard is not responsive  for any choices : sales, products, customers, content, report, marketing, system, when clicking does nothing! Only my account from dashboard page works but save does nothing ! 
I followed this installation https://www.youtube.com/watch?v=TmyRQtJDypU
1) Installed xampp latest installation control panel v3.2.2 (mariaDB) on my Dell 7737 notebook windows 10 x64
2) Installed composer (no errors)
3) Copied and extracted zip file from git repository to a folder c:\xampp\htdocs\rcm
4) Installed composer at c:\xampp\htdocs\rcm\composer.json
5) I did create a Mysql db 
6) i have installed magento2 which ends with a successful installation but..
Could you help me please?

**Comment by deepthi743** [comment]
I am facing the same issues ..i tried clearing var/cache and also cleared the cookies of chrome but nothing works..the page remains unresponsive and icons doesn't appear properly..
If anyone knows to correct them please reply..

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
