### ISSUE TITLE
can not access admin page,  broken links

### ISSUE THREAD

**Issue by yulijia** [magento/magento2#2765]
Dear all,
I have searched a lot of solutions about this problem(issue #2272 #2614 ), but all of the solutions didn't help me solve the problem. So I open an issue at here.
If you can try click the website link, you can get an 404 error on the page.

[http://123.56.234.155/magento/index.php/admin_mvmx20/](http://123.56.234.155/magento/index.php/admin_mvmx20/)

```
 The requested URL /magento/admin_mvmx20/admin/index/index/key/7cc06ff901ad095388290f025ef0d80bd6d7483d6d8843022a2f5be04229aa08/ was not found on this server.
Apache/2.4.7 (Ubuntu) Server at 123.56.234.155 Port 80
```

The debug.log shows:

```
[2015-12-19 14:59:59] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://123.56.234.155/magento/index.php/admin_mvmx20/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
```

Hope that can help you to find the problem.

Thanks.

**Comment by yulijia** [comment]
I  try those command several times and it works!

```
bin/magento cache:clean
bin/magento cache:flush
magento setup:static-content:deploy 'zh_Hans_CN'
```

However, there is another bug. I install magento 2 with Chinese language, the frontend show the correct links, like    

> pub/static/frontend/Magento/luma/zh_Hans_CN/mage/calendar.css

But, the admin page shows the wrong links.

> pub/static/adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.css

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
