### ISSUE TITLE
Magneto 2.3.4 - Invalid input date time format of value (locale AU)

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#27654]
### Preconditions (*)

1. Magento version 2.3.4
2. Australia locale in admin
3. PHP ver 7.1
4. CLOUDLINUX 6.10

### Steps to reproduce (*)

1. Create or edit product
2. Change date field for new from to anything
3. Click Save

### Expected result (*)

1. Product Saves with new from date
2. 

### Actual result (*)

1. Error occurs stating Invalid input datetime format of value '21/04/2020'
2. Screenshot 1 - https://prnt.sc/rvd3o8
3. Screenshot 2 - https://prnt.sc/rvd42u

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27654-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27654-2-4-develop.instances.magento-community.engineering/admin_0b3d](https://i-27654-2-4-develop.instances.magento-community.engineering/admin_0b3d)
Login: `6cd1b012` Password: `a39d54a046c3`
Instance will be terminated in up to 3 hours.

**Comment by gilbertsohal** [comment]
Is there anyone who can help me?

**Comment by gilbertsohal** [comment]
Error occurs stating Invalid input date time format of value '21/04/2020'  with dd/mm/yyyy

Screenshot 1
https://prnt.sc/rvd3o8

Screenshot 2
https://prnt.sc/rvd42u

**Comment by engcom-Delta** [comment]
Hi @gilbertsohal thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
![Peek 2020-04-30 15-20](https://user-images.githubusercontent.com/51681379/80709652-4efcce00-8af6-11ea-80c8-4858aae4410e.gif)

If you'd like to update the issue, please reopen it.

**Comment by frilogg** [comment]
hi @gilbertsohal  did you find any solution to your problem ?
