### ISSUE TITLE
2.3.4 GraphQl Aggregation Attribute labels and attribute option labels are not or incorrectly translated.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#27657]
### Preconditions (*)

1. Magento 2.3.4
2. 2 Storeviews
3. Demo data

### Steps to reproduce (*)

1. Pick an attribute and configure it so its available as an aggregation in graphql (I chose "size")
2. Set the attribute label for both storeviews
![Screenshot from 2020-04-08 17-01-43](https://user-images.githubusercontent.com/22170051/78799926-19fbd080-79bb-11ea-840b-3f3fb5651d0e.png)
3. Set the attribute option labels for both storeviews
![Screenshot from 2020-04-08 17-01-49](https://user-images.githubusercontent.com/22170051/78799939-1ff1b180-79bb-11ea-95f2-206a8b329137.png)
4. Run the following GraphQl query for both storeviews:
```
query products {
    products (filter: {
      category_id: {eq: "2"}
    } 
    ) {
        aggregations {
          attribute_code
          label
          options{
            count
            label
            value
          }
        }
    }
}
```
### Expected result (*)

For default storeview
 ```
...
              {
                    "attribute_code": "size",
                    "label": "default",
                    "options": [
                        {
                            "count": 1,
                            "label": "55 cm default",
                            "value": "5518"
                        },
                        {
                            "count": 1,
                            "label": "65 cm default",
                            "value": "5519"
                        },
                        {
                            "count": 1,
                            "label": "default",
                            "value": "5520"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5521"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5522"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5523"
                        },
                        {
                            "count": 97,
                            "label": "XS default",
                            "value": "5594"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5595"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5596"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5597"
                        },
                       {...}
                    ]
                },
...
```

### Actual result (*)

For default storeview
```
...
               {
                    "attribute_code": "size",
                    "label": "Size",
                    "options": [
                        {
                            "count": 1,
                            "label": "55 cm notdefault",
                            "value": "5518"
                        },
                        {
                            "count": 1,
                            "label": "65 cm notdefault",
                            "value": "5519"
                        },
                        {
                            "count": 1,
                            "label": "notdefault",
                            "value": "5520"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5521"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5522"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5523"
                        },
                        {
                            "count": 97,
                            "label": "XS notdefault",
                            "value": "5594"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5595"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5596"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5597"
                        },
                       {...}
                    ]
                },
...
```
What is happening is that the attribute label is never translated. And the attribute option labels pick the last entry in the database for each label. In my case "notdefault" because I entered those last.
I checked the code and at no point is the $storeId checked in the queries that gather the results.

**Comment by Hexmage** [comment]
The code for this is unchanged between 2.3.4 and 2.4

**Comment by Hexmage** [comment]
`app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php`
Is the class in which this happens.

**Comment by bharat1811** [comment]
It is the main issue is not managed **$storeId** in attribute builder. I dig the issue and I get to manage the issue with a temporary solution by overriding following file in my custom module using preference type,

**vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php**

First for **Attribute.php** I changed below functions to mange **$storeId**,

public function build(AggregationInterface $aggregation, ?int $storeId): array
    {
        
        **$attributeOptions = $this->getAttributeOptions($aggregation, $storeId);**

        // build layer per attribute
        $result = [];
        foreach ($this->getAttributeBuckets($aggregation) as $bucket) {
            $bucketName = $bucket->getName();
            $attributeCode = \preg_replace('~_bucket$~', '', $bucketName);
            $attribute = $attributeOptions[$attributeCode] ?? [];

            $result[$bucketName] = $this->layerFormatter->buildLayer(
                $attribute['attribute_label'] ?? $bucketName,
                \count($bucket->getValues()),
                $attribute['attribute_code'] ?? $bucketName
            );

            foreach ($bucket->getValues() as $value) {
                $metrics = $value->getMetrics();
                $result[$bucketName]['options'][] = $this->layerFormatter->buildItem(
                    $attribute['options'][$metrics['value']] ?? $metrics['value'],
                    $metrics['value'],
                    $metrics['count']
                );
            }
        }

        return $result;
    }

private function getAttributeOptions(AggregationInterface $aggregation, **$storeId**): array
    {
        $attributeOptionIds = [];
        $attributes = [];
        foreach ($this->getAttributeBuckets($aggregation) as $bucket) {
            $attributes[] = \preg_replace('~_bucket$~', '', $bucket->getName());
            $attributeOptionIds[] = \array_map(
                function (AggregationValueInterface $value) {
                    return $value->getValue();
                },
                $bucket->getValues()
            );
        }

        if (!$attributeOptionIds) {
            return [];
        }        
        **return $this->attributeOptionProvider->getOptions(\array_merge(...$attributeOptionIds), $attributes, $storeId);**
    }

_* For **attributeOptionProvider** (vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php) I manged by creating in my custom module and initiated in Attribute.php to use._

I did changes in follwoing function in custom **AttributeOptionProvider.php** as below,

_#load  \Magento\Catalog\Model\ResourceModel\ProductFactory $productFactory in you __construct()_

 public function getOptions(array $optionIds, array $attributeCodes = [], **$storeId**): array
    {
        if (!$optionIds) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['a' => $this->resourceConnection->getTableName('eav_attribute')],
                [
                    'attribute_id' => 'a.attribute_id',
                    'attribute_code' => 'a.attribute_code',
                    'attribute_label' => 'a.frontend_label',
                ]
            )
            ->joinLeft(
                ['options' => $this->resourceConnection->getTableName('eav_attribute_option')],
                'a.attribute_id = options.attribute_id',
                []
            )
            ->joinLeft(
                ['option_value' => $this->resourceConnection->getTableName('eav_attribute_option_value')],
                'options.option_id = option_value.option_id',
                [
                    'option_label' => 'option_value.value',
                    'option_id' => 'option_value.option_id',
                ]
            );

        $select->where('option_value.option_id IN (?)', $optionIds);

        if (!empty($attributeCodes)) {
            $select->orWhere(
                'a.attribute_code in (?) AND a.frontend_input = \'boolean\'',
                $attributeCodes
            );
        }

         **return $this->formatResult($select, $storeId);**
    }


    private function formatResult(\Magento\Framework\DB\Select $select, **$storeId**): array
    {           
        $statement = $this->resourceConnection->getConnection()->query($select);

        $result = [];
        **$poductReource=$this->productFactory->create();**
        
        while ($option = $statement->fetch()) {
                
            **if($poductReource->getAttribute($option['attribute_code'])->getStoreLabel($storeId)){
                $attributeLabel = $poductReource->getAttribute($option['attribute_code'])->getStoreLabel($storeId);    
            }else{
                $attributeLabel = $option['attribute_label'];
            }
            
            $attribute = $poductReource->getAttribute($option['attribute_code']);
            if ($attribute->usesSource()) {
              $option_Text = $attribute->getSource()->getOptionText($option['option_id']);
            }**            
          
            if (!isset($result[$option['attribute_code']])) {              
                $result[$option['attribute_code']] = [
                    'attribute_id' => $option['attribute_id'],
                    'attribute_code' => $option['attribute_code'],
                    **'attribute_label' =>  $attributeLabel,**
                    'options' => [],
                ];
            }            
                
            **$result[$option['attribute_code']]['options'][$option['option_id']] = $option_Text;**
        }
      
        return $result;
    }

 Here, in format result() function I have managed such a way that if it's not set attribute and option label store wised then it will be fall back and returns default label.

**Comment by Hexmage** [comment]
@bharat1811 I did something similar to fix it for me locally. Changes to vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php were identical.

For attributeOptionProvider I did the following.
```
    public function getOptions(array $optionIds, array $attributeCodes = [], $storeId): array
    {
        if (!$optionIds) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                ['a' => $this->resourceConnection->getTableName('eav_attribute')],
                [
                    'attribute_id' => 'a.attribute_id',
                    'attribute_code' => 'a.attribute_code',
                    'attribute_label' => 'a.frontend_label',
                ]
            )
            ->joinLeft(
                ['options' => $this->resourceConnection->getTableName('eav_attribute_option')],
                'a.attribute_id = options.attribute_id',
                []
            )
           ** ->joinLeft(
                ['label' => $this->resourceConnection->getTableName('eav_attribute_label')],
                'a.attribute_id = label.attribute_id',
                [
                    'attribute_translated_label' => 'label.value'
                ]
            ) **
            ->joinLeft(
                ['option_value' => $this->resourceConnection->getTableName('eav_attribute_option_value')],
                'options.option_id = option_value.option_id',
                [
                    'option_label' => 'option_value.value',
                    'option_id' => 'option_value.option_id',
                ]
            );

        $select->where('option_value.option_id IN (?)', $optionIds)**->where('option_value.store_id = (?)', $storeId)->where('label.store_id = (?)', $storeId)**;

        if (!empty($attributeCodes)) {
            $select->orWhere(
                'a.attribute_code in (?) AND a.frontend_input = \'boolean\'',
                $attributeCodes
            );
        }

        return $this->formatResult($select);
    }

    private function formatResult(\Magento\Framework\DB\Select $select): array
    {
        $statement = $this->resourceConnection->getConnection()->query($select);

        $result = [];
        while ($option = $statement->fetch()) {
            if (!isset($result[$option['attribute_code']])) {
                $result[$option['attribute_code']] = [
                    'attribute_id' => $option['attribute_id'],
                    'attribute_code' => $option['attribute_code'],
                    'attribute_label' => **$option['attribute_translated_label'] ??** $option['attribute_label'],
                    'options' => [],
                ];
            }
            $result[$option['attribute_code']]['options'][$option['option_id']] = $option['option_label'];
        }

        return $result;
    }
```
But I think your solution is better, because mine assumes that every store has translated values (which is true in my case).

**Comment by Hexmage** [comment]
I just noticed that this also happens for the Price attribute but @bharat1811 's pull request wont fix that. Since Price has it's own LayeredNavigation Builder and the label is hardcoded in there.

**Comment by bharat1811** [comment]
> I just noticed that this also happens for the Price attribute but @bharat1811 's pull request wont fix that. Since Price has it's own LayeredNavigation Builder and the label is hardcoded in there.

@Hexmage  you are right price and category are individual parts than the attributes section also labels are hardcoded. But as per my solution, it will work for product attributes that are dynamic for layered navigation

**Comment by cpartica** [comment]
Fixed in https://github.com/magento/magento2/issues/28568
