### ISSUE TITLE
2.3.4 Invoice always sent (if exist) when order placed.

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#27656]
### Preconditions (*)
related to attempt to fix 
https://github.com/magento/magento2/issues/13466

commit 
https://github.com/magento/magento2/commit/5ccd367ebc628b588a77cb2032faeabd6005b039
1. # h3. Steps to reproduce (*)
1. Place order with a payment method that instantly generates an invoice
1. The module/code that generated an invoice now is responsible for checking it's state and send to customer
1. but here https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR72 magento checks if invoice exist and send it to customer
1. If so, pleas give the possibility to disable this in `sales*model_service_quote_submit*success` without code modifying or changing `\Magento\Quote\Observer\SubmitObserver::execute` or its dependencies

### Expected result (*)
1. Invoice Sending is managed by modules that created this invoice and should be configurable
1. Invoice is not sent the same time the order placed
1. or this feature is disabled and can be configured

### Actual result (*)
1. Invoice is always sent if exists https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR7
1. The original intention to fix https://github.com/magento/magento2/issues/13466 if so **the PayPal module is responsible for sending its invoice NOT MAGENTO QUOTE MODULE**

**Comment by ilnytskyi** [comment]
@magento-engcom-team @StasKozar @viktym

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33893` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by zakdma** [comment]
We discussed this task and made decision we'll create separate observer for invoice emails so isolate invoice email sending from order email sending. Developer can disable the observer following the documentation instructions https://devdocs.magento.com/guides/v2.4/extension-dev-guide/events-and-observers.html
Also invoice email sending will depend on **sales_email/invoice/enabled** configuration (**Yes** by default)
So functionality will work as before but there is possibility to change it behaviour as developer need.

**Comment by magento-engcom-team** [comment]
Hi @ilnytskyi, @ilnytskyi, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33893` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
