### ISSUE TITLE
Wrong parameters name passed to widgets after generation

### ISSUE THREAD

**Issue by aelmizeb** [magento/magento2#27650]
### Preconditions (*)

On magento 2.3.4, after creating a widget, in the frontend the data contains a wrong parameters name. the parameters names contains a '+' char.

### Steps to reproduce (*)

1. Create a widget with parameters in the backend
2. go to the frontend and try to get the parameters

### Expected result (*)

1. Parameters name are correct 
2. You can get the value of the parameters by the name of the parameters

### Actual result (*)

1. Parameter contains '+' char

Its related to a change on the framework in the Magento v 2.3.4, the function setString() on the Magento\Framework\Filter\Template\Tokenizer\AbstractTokenizer have changed.

From :
`/**
     * Set string for tokenize
     *
     * @param string $value
     * @return void
     */
    public function setString($value)
    {
        $this->_string = urldecode($value);
        $this->reset();
    }`

To :
`
/**
     * Set string for tokenize
     *
     * @param string $value
     * @return void
     */
    public function setString($value)
    {
        $this->_string = rawurldecode($value);
        $this->reset();
    }
`

rawurldecode generate parameters with '+' chars

**Comment by sudheers-kensium** [comment]
Hi @aelmizeb Kindly update all the required details for reproduce the issue

**Comment by aelmizeb** [comment]
> Hi @aelmizeb Kindly update all the required details for reproduce the issue

Hi @sudheers-kensium the details was updated

**Comment by sudheers-kensium** [comment]
@aelmizeb Can you please provide more details how you created widget and provide screenshots. It will help to reproduce the issue.

**Comment by sudheers-kensium** [comment]
@aelmizeb I am not able to reproduced the issue with the above details.
Kindly update all the details for reproduce the issue.
Feel free to reopen once you update details.
Thanks
