### ISSUE TITLE
محسن چاوشی

### ISSUE THREAD

**Issue by dodangehpor** [magento/magento2#27665]
محسن چاوشی#

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by krishprakash** [comment]
Hi @dodangehpor. Kindly update all the details pre condition, steps to reproduce, expected and actual result in English only

**Comment by krishprakash** [comment]
Closing this as added unnecessarily
