### ISSUE TITLE
When programatically creating a CMS block, it cannot be assigned to "All store views"

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#27667]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. In a patch setup script, run the following:

        $block = $this->blockFactory->create();
        $block
            ->setTitle('Foo')
            ->setIdentifier('foo')
            ->setContent('<p>Hello world</p>')
            ->setStoreId(0);

        $this->blockRepository->save($block);

### Expected result (*)

1. CMS block is assigned to "All store views" 
2. in `cms_block_store` table, the block ID is assigned to store_id 0

### Actual result (*)

1. CMS block is assigned to a single store view (I'm not exactly sure how it pick a single store view from the context of a setup script, but it seems random, or it picks the first store view ID).

**Comment by erfanimani** [comment]
Also reproduced on 2.4-develop, see this line here: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/BlockRepository.php#L114

Creating a PR would be easy as it involves changing the `empty` check to a null check, but I'm not sure what consequences this has, or why empty was chosen. Should I go ahead and check if tests pass?

**Comment by sudheers-kensium** [comment]
Hi @erfanimani , I have used below code to create CMS block. 

$block = $blockFactory->create();
 $block
     ->setTitle('Foo')
     ->setIdentifier('foo')
     ->setContent('<p>Hello world</p>')
     ->setStoreId(0)->save();

**Comment by erfanimani** [comment]
@sudheers-kensium ah thanks, yes that works. However, we're discouraged form using the save method directly on models and instead encouraged to use repositories (interfaces if possible).

**Comment by sudheers-kensium** [comment]
@erfanimani I am closing this issue. 
Feel free to reopen if you have any issue.

**Comment by erfanimani** [comment]
Thanks @sudheers-kensium , I still think this is an issue. Using save on the model directly is bad practice and should not be used. Repository should have the same behaviour as calling save directly, therefore I still think this is a bug.

**Comment by amarroni** [comment]
Hi @erfanimani seen to be not a issue. Please try way. As you can see store_id is waiting for array.
$data = [
'title' => "test",
'identifier' => "zzzzzzzzzz",
'is_active' => "1",
'store_id' =>[0],
'content' => "test"];

$block = $this->blockFactory->create()->addData($data);
$this->blockRepository->save($block);

**Comment by erfanimani** [comment]
Thanks @amarroni, that works — I must have listened too well to the method signature ;)

    /**
     * CMS block model
     *
     * @method Block setStoreId(int $storeId)
     * @method int getStoreId()
     */
    class Block extends AbstractModel implements BlockInterface, IdentityInterface
