### ISSUE TITLE
checkout frozen by throwing error

### ISSUE THREAD

**Issue by Gabriel-Bruno** [magento/magento2#27660]
### Preconditions (*)

1. magento 2.3.4
2.

### Steps to reproduce (*)

1.after product adding to cart and clicking on the checkout page
2.checkout page start to load, but its frozen,and keep frozen.

### Expected result (*)

1. it should be load the checkout page successfully to add the shipping and payment detail.
2.

### Actual result (*)

1. its keep frozen and throing error - console error picture-> https://ibb.co/t3LjnCC
2. * if refresh the page it will be proceed, (with the error).

i hope someone can help hope to fix this issue.

Best Regards,
Gabriel

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27660-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27660-2-4-develop.instances.magento-community.engineering/admin_cffa](https://i-27660-2-4-develop.instances.magento-community.engineering/admin_cffa)
Login: `d6dd2c0e` Password: `91ff428e4430`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @Gabriel-Bruno. Thank you for your report.
Can not able to reproduce the issue on latest magento instance
Kindly provide more detailed steps about this issue

**Comment by Gabriel-Bruno** [comment]
Hi @krishprakash 
the process as normal add to cart item then click on checkout bottom.
https://www.loom.com/share/6ef930acf96a463a8faab0cff321f353

Regards,
Gabriel

**Comment by krishprakash** [comment]
Hi @Gabriel-Bruno. 
Can not to reproduce the issue as you see in video and described here.
It may be any of your custom module issue
Kindly refer community forum or magento stack exchange to discuss about your concern as github issue tracker is intended for magento core technical issue only.
Thank you !!
