### ISSUE TITLE
DI does not validate arguments from `di.xml`

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27661]
### Preconditions (*)
1. `di.xml` enables you to provide arguments to the `__construct()` method

### Steps to reproduce (*)
1. Create `<virtualType>` or `<type` reference
2. Add `<arguments>` to ↑ with `<argument name="thisOneDoesNotExist" xsi:type="string">ShouldCauseFailure</argument>`

### Expected result (*)
1. Neither `setup:upgrade` nor `setup:di:compile` should pass.
1. We should expect `InvalidArgumentException`

### Actual result (*)
1. `setup:di:compile` and `setup:upgrade` pass without any issues.
1. You are not aware that 3rd party vendor changed the constructor argument name

**Comment by Vinai** [comment]
Sorry @lbajsarowicz, I disagree with this assessment.
Removing a required argument should be a backward compatible change. This argument validation makes that a backward breaking change.

**Comment by lbajsarowicz** [comment]
@Vinai How about having that in Developer mode only?

**Comment by kandy** [comment]
@lbajsarowicz Maybe best solution will be written static integrity test 
see `\Magento\Test\Integrity\Di\CompilerTest` as example

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.
