### ISSUE TITLE
Admin Customer edit form fails on date validation

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27673]
### Preconditions (*)
![image](https://user-images.githubusercontent.com/1639941/78888246-88936980-7a61-11ea-8dec-0a3958961ebe.png)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by devchris79** [comment]
Sounds like #27027

**Comment by lbajsarowicz** [comment]
You are right, @devchris79
