### ISSUE TITLE
Tax is calculated incorrectly when Catalog Prices calculation setting is "including tax"

### ISSUE THREAD

**Issue by vbyno** [magento/magento2#27675]
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. Add a Tax rate (10%) (Stores->Tax zones and Rates-> Add new tax Rate
![image](https://user-images.githubusercontent.com/2923624/78894979-bafb9180-7a76-11ea-953c-93c31a68ef54.png)

and create a tax rule  (Stores -> Tax rules -> Add new Tax rule)
![image](https://user-images.githubusercontent.com/2923624/79095097-30f74580-7d62-11ea-8114-999f7d2d811a.png)

2. Create a product ($2)
![image](https://user-images.githubusercontent.com/2923624/78895081-e1b9c800-7a76-11ea-8610-004ab31a227c.png)

3. Configure Store to Calculate prices including tax (Stores --> Configuration --> Sales --> Tax --> Calculation Settings)
![image](https://user-images.githubusercontent.com/2923624/78895243-25accd00-7a77-11ea-9e3e-adc735350f9f.png)

4. Create an order
![image](https://user-images.githubusercontent.com/2923624/78895490-a370d880-7a77-11ea-94a8-07bae59a7778.png)

### Expected result (*)
I expect the grand total cost to be **$20**, since the tax is included in the item's price

### Actual result (*)
The grand total is **20.30.**. The displayed item price and tax are incorrect. 
![image](https://user-images.githubusercontent.com/2923624/78895682-efbc1880-7a77-11ea-95b9-56979f133e22.png)

**Comment by vbyno** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vbyno. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vbyno, here is your [Magento instance](https://i-27675-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27675-2-4-develop.instances.magento-community.engineering/admin_14fa](https://i-27675-2-4-develop.instances.magento-community.engineering/admin_14fa)
Login: `243dae7d` Password: `6d925686cfee`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27675-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27675-2-4-develop.instances.magento-community.engineering/admin_d341](https://i-27675-2-4-develop.instances.magento-community.engineering/admin_d341)
Login: `2022aabd` Password: `098fafc86cf6`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@vbyno Are you able to reproduced in Magento 2.4-develop instance?

**Comment by vbyno** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vbyno. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vbyno, here is your [Magento instance](https://i-27675-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27675-2-4-develop.instances.magento-community.engineering/admin_1ded](https://i-27675-2-4-develop.instances.magento-community.engineering/admin_1ded)
Login: `4b24b9c2` Password: `1423bae55181`
Instance will be terminated in up to 3 hours.

**Comment by vbyno** [comment]
@sudheers-kensium , I can not reproduce it on Magento 2.4-develop instance. Seems like the bug is fixed now. Thank you!
![image](https://user-images.githubusercontent.com/2923624/79095309-bed33080-7d62-11ea-9f85-74fd684459f8.png)

**Comment by vbyno** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vbyno. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vbyno, here is your [Magento instance](https://i-27675-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27675-2-4-develop.instances.magento-community.engineering/admin_8174](https://i-27675-2-4-develop.instances.magento-community.engineering/admin_8174)
Login: `6dbd2d32` Password: `2107796b05d6`
Instance will be terminated in up to 3 hours.

**Comment by paugnu** [comment]
Hi,

I'm sorry to comment in a closed issue: but is this a confirmed bug in Magento 2.3.4? I'm experiencing exactly the same issue described by @vbyno and I would like to fix this in this release instead of waiting for 2.4. Is it not a blocker issue? Basically all tax calculations are wrong because of this :( (or maybe I'm missing something)
