### ISSUE TITLE
Adminarea order view bug customizable product options not showing

### ISSUE THREAD

**Issue by ikdekker** [magento/magento2#27679]
### Preconditions (*)

1. Magento 2.3.3
2. Have some configurable product with customizable options present.

### Steps to reproduce (*)
1. Configure the configurable product with some custom options added (I used a multiple-select config)
2. Add to cart, proceed to checkout and order.
3. Navigate to the CMS > sales > orders > click the created order
4. Check the Items Ordered list

### Expected result (*)
1. Get a product name with the configurable option and all customizable options.

### Actual result (*)
1. Only the configurable options are listed in the name column.
2. Configurable options are listed twice.

The items inside the product are properly set, there are two items listed in the order. First is the configurable product, which is being shown. Second is the simple product, having the correct customizable options on its product options. The second however, is not shown.

The parent_item_id of the simple product does refer to the parent id inside the order, but is not handled correctly.

We can see [here](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/templates/order/view/items.phtml#L26) that any simple products are skipped if a parent product is found on the order item.

Furthermore, [this](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/templates/items/column/name.phtml) name phtml file uses this [getOrderOptions](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Block/Adminhtml/Items/Column/DefaultColumn.php#L69) on the Block to aggregate options and attributes.

To my knowledge this is wrong behaviour, and the orderoptions should be fetched from the child item?

**Comment by ikdekker** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ikdekker. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ikdekker** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @ikdekker. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ikdekker** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @ikdekker. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ikdekker, here is your [Magento instance](https://i-27679-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27679-2-4-develop.instances.magento-community.engineering/admin_c6b9](https://i-27679-2-4-develop.instances.magento-community.engineering/admin_c6b9)
Login: `20c2ae91` Password: `dbafeeb556fd`
Instance will be terminated in up to 3 hours.

**Comment by ikdekker** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ikdekker. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ikdekker** [comment]
@magento give me 2.3instance

**Comment by ikdekker** [comment]
@magento give me 2.3 instance

**Comment by ikdekker** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @ikdekker. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ikdekker, here is your [Magento instance](https://i-27679-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-27679-2-3-3.instances.magento-community.engineering/admin_94d1](https://i-27679-2-3-3.instances.magento-community.engineering/admin_94d1)
Login: `e5f7043f` Password: `1a819a6ca3bf`
Instance will be terminated in up to 3 hours.

**Comment by ikdekker** [comment]
Could not reproduce. I'll test some more and see where the problem comes from. Will close this within 1 day if no reproducable steps are found.
