### ISSUE TITLE
Method getGalleryOptions() missing in block class gallery.php

### ISSUE THREAD

**Issue by clion007** [magento/magento2#27687]
### Preconditions (*)

1. Magento version: 2.* latest;
2. PHP 7.1.29;
3. MySQL 5.7.26.

### Steps to reproduce (*)

1. I found in the module of catalog, the template of <block class="Magento\Catalog\Block\Product\View\Gallery" name="product.info.media.image" template="product/view/gallery.phtml"/> has an error, because a method missing in  Magento\Catalog\Block\Product\View\Gallery.php. this will get a Fatal error when send requests to get products images.
2. In line 46 and 47 of the gallery.phtml file, the code init js options, code as below:
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
the block method getGalleryOptions() is does not exist in Gallery.php, so there should be a bug.
3. I found the method getOptionsJson() and getFSOptionsJson() is existed in file Magento\Catalog\Block\Product\View\GalleryOptions.php. So I think it should add method getGalleryOptions() in Gallery.php to call above two methods or fix it in the gallery.phtml to call.
4. In additional, there sames a js error. There is an error in console log, when request send as below:
Uncaught TypeError: Cannot read property 'caption' of undefined in fotorama.js line 2424
This sames because when code run to this line, the property 'caption' still not complete init.

### Expected result (*)

Fix the Fatal error and js error.

### Actual result (*)

Errors as above.

**Comment by gwharton** [comment]
The galleryoptions class is injected to gallery.php using di in etc/di.xml

**Comment by gwharton** [comment]
Closing as non issue. Third party themes must ensure they inject the relevant class in di.

**Comment by clion007** [comment]
> The galleryoptions class is injected to gallery.php using di in etc/di.xml

Ok! I will check it again. Thanks!

**Comment by clion007** [comment]
I found in magento 2.4, it not injected using di in etc/di.xml, but use layout xml in catalog_product_view.xml. Thanks again anyway!

**Comment by clion007** [comment]
In magento 2.4, it not injected using di, but using catalog_product_view.xml layout.
