### ISSUE TITLE
CSS and JavaScript break when category is configurable.

### ISSUE THREAD

**Issue by lukpheakdey** [magento/magento2#27684]
### Preconditions (*)

1. Magento version 2.3.8

### Steps to reproduce (*)

1. CSS and JavaScript break when category is configurable product
![Screen Shot 2020-04-09 at 4 53 00 PM](https://user-images.githubusercontent.com/10406702/78944281-25b2ca00-7a83-11ea-85cf-eb71f6976123.png)
2. We use this code below in this problem.
![Screen Shot 2020-04-09 at 4 54 33 PM](https://user-images.githubusercontent.com/10406702/78944320-3a8f5d80-7a83-11ea-89a5-97972956538d.png)

3. When changing categoryId = 4 is simple product, CSS and JavaScript are working.
![Screen Shot 2020-04-09 at 5 08 00 PM](https://user-images.githubusercontent.com/10406702/78945155-35331280-7a85-11ea-818d-881781889e99.png)

4. We use this code below and there are not break css
![Screen Shot 2020-04-09 at 5 09 55 PM](https://user-images.githubusercontent.com/10406702/78945496-108b6a80-7a86-11ea-9501-2ebe904d6622.png)

*** When filter category in sample and configuarable product. It was working fine in Page 1 - 4 but It will be break css in page number 5 because page number 5 is configurable product.
![Page1-4](https://user-images.githubusercontent.com/10406702/78942292-01ed8500-7a7f-11ea-8258-18d02492ebe5.png)
![Screen Shot 2020-04-09 at 3 59 45 PM](https://user-images.githubusercontent.com/10406702/78942364-32352380-7a7f-11ea-8426-e3080008690d.png)

3. We use code below in this problem
![Screen Shot 2020-04-09 at 5 24 19 PM](https://user-images.githubusercontent.com/10406702/78945898-05850a00-7a87-11ea-90a3-3f13671e23f6.png)

Note: We run all command, but It's still not working
- m -rf generated/*
- rm -rf var/cache/*
- rm -rf var/view_preprocessed/*
- php bin/magento setup:static-content:deploy -f 
- php bin/magento setup:upgrade
- php bin/magento cache:flush

### Expected result (*)

It will not lose css in page number 5 like page 1 - 4
![Page1-4](https://user-images.githubusercontent.com/10406702/78942039-75db5d80-7a7e-11ea-8c37-709bece7d0a3.png)

### Actual result (*)

There will not lose css when click till page number 5.

Source code:
[ProductCustomDemo.zip](https://github.com/magento/magento2/files/4458981/ProductCustomDemo.zip)

**Comment by mrtuvn** [comment]
Thanks for your report but i found couple thing i should note here
#1 Seem this problem related with customises and not relate with magento thing
#2 You should avoid use resultPage in controller like demo
Instead use resultPage->create please use view->getLayout

**Comment by lukpheakdey** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lukpheakdey. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lukpheakdey, here is your [Magento instance](https://i-27684-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27684-2-4-develop.instances.magento-community.engineering/admin_ea85](https://i-27684-2-4-develop.instances.magento-community.engineering/admin_ea85)
Login: `074207d5` Password: `7d0139268b96`
Instance will be terminated in up to 3 hours.

**Comment by lukpheakdey** [comment]
@magento give me test instance

**Comment by lukpheakdey** [comment]
@mrtuvn I try to avoid using resultPage and did not use Controller, but I still have problem.
Do you have how to deploy my code to vanilla Magento instance?

**Comment by mrtuvn** [comment]
@engcom-Alfa can you deploy sample code zip to instance for test purpose ?

**Comment by lukpheakdey** [comment]
@engcom-Alfa @mrtuvn Yes, I just want to test only to make sure what is the problem.

**Comment by lukpheakdey** [comment]
@engcom-Alfa @mrtuvn do you any solution or guide line for me to solve this problem?

**Comment by lukpheakdey** [comment]
@mrtuvn @engcom-Alfa: I am waiting your response. Please response me for any solution.

**Comment by mrtuvn** [comment]
i'm not a part of magento team so i can't help you 
Seem this problem related with customises and not related with magento code
I'm not sure what you are going to do here

Tested in my setup local (clean magento 2.4-develop + sample data) no use any additional code
category women/tops-women/jackets-women.html (all products is configurable)
Grid mode default
Products per Page on Grid Allowed Values 2,5,12,24,36

But i can't reproduce issue with paging like your describe

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @lukpheakdey  thank you for your report. 
Unfortunately, we are not able to reproduce this issue on a clean 2.4-develop instance. 
Seems the problem connected with custom module.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
