### ISSUE TITLE
Magento 2 backend is not responsive, so it is uncomfortable to use on smartphones

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2768]
Some screenshots on iPhone 6 (667x375 resolution): https://mage2.pro/t/306

**Comment by alankent** [comment]
Correct - the Admin was not designed to be responsive at this stage. It is tablet friendly, but not phone friendly.

**Comment by magenx** [comment]
you dont have to check it on iPhone 6, probably it is easier to check css instead.
