### ISSUE TITLE
`theme_theme_id` missing in `design_config_grid_flat`

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27699]
### Preconditions (*)
1. Magento 2.3.4
2. Theme changed using Data Patch:
  ```php
    public function apply()
    {
        $theme = $this->getThemeByPath(self::THEME_PATH);
        $website = $this->getWebsiteByCode(self::WEBSITE_CODE);

        $this->configWriter->save(
            self::CONFIG_PATH_THEME_ID,
            $theme->getId(),
            ScopeInterface::SCOPE_WEBSITES,
            $website->getId()
        );

        $this->eventManager->dispatch('assigned_theme_changed', ['theme' => $theme]);
    }
```

### Steps to reproduce (*)
1. Execute patch

### Expected result (*)
1. :heavy_check_mark: Value of `design/theme/theme_id` for specified `websites` scope should reflect the `theme_id` from `theme` table
2. :x: Value of `theme_theme_id` in `design_config_grid_flat` should reflect `theme_id` in `theme` table
3. Website should load with new Theme

### Actual result (*)
![image](https://user-images.githubusercontent.com/1639941/79009582-1786ab80-7b60-11ea-92de-789e42311eef.png)

1. `theme_theme_id` in `design_config_grid_flat` is empty (not null)
2. Website is loading default theme.

**Comment by mrtuvn** [comment]
any update on this ?
@lbajsarowicz Not sure but my issue may related with this. First setup i have no use theme sample data (no use magento theme). Just create product normal and setup my theme instead default magento theme for test. But after success setup magento sample data. My theme was overrided by magento ! My thought i need re-config in admin but not sure why my theme lost after install sample data. Luma theme with sample set over my theme

**Comment by lbajsarowicz** [comment]
I reviewed the events that are executed after saving the Configuration changes. I recommend the same path to begin with. You'll find the funny part about Magento way of handling Theme change 💯

**Comment by mrtuvn** [comment]
path `design/theme/theme_id` in table core_config_data seem has been set with new id after run install theme sampledata
scope default and scope id 0

**Comment by mrtuvn** [comment]
Is this related with wrong save store ? I'm aware maybe we have problem while save config theme relate store id

**Comment by mrtuvn** [comment]
cc: @lbajsarowicz do you still able reproduce issue or catch up this issue

**Comment by ZIPITRO** [comment]
Also had this issue, but since version 2.4.2 this error didn't show up in my case, which version of Magento are you running currently?

**Comment by engcom-Oscar** [comment]
Hi @lbajsarowicz ! Thank you for your report.
May you please recheck if this issue reproducible on latest 2.4-develop code?

**Comment by engcom-Hotel** [comment]
Dear @lbajsarowicz,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards
