### ISSUE TITLE
Propose to make the «config» param optional for the \Magento\Framework\Data\Form\AbstractForm::addField() method

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2772]
https://github.com/magento/magento2/blob/2.0.0/lib/internal/Magento/Framework/Data/Form/AbstractForm.php#L144-L159

**Comment by davidalger** [comment]
@dfediuk Please provide some context and an argument for why you would like them to make this change. This will help the core team evaluate the value of such a change, and understand how it may benefit others.

**Comment by dmitrii-fediuk** [comment]
This is because the `$config` is used to pass additional parameters to a form element's construtor.
None ot these parameters are required for a generic form element.

**Comment by davidalger** [comment]
@dfediuk Thanks for the additional context. This is now on the Magento team to evaluate and accept/reject the suggestion.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
