### ISSUE TITLE
Using the V1/search API to get the list of SKU's 

### ISSUE THREAD

**Issue by userException** [magento/magento2#2773]
I need a text based search to get the names and SKU's of the magento products. While using V1/products API, the response is too much. I just need the name and the SKU, just like google suggestions come up when you type something. 

I tried wit the V1/search api but received but no luck: 
http://192.168.1.180/magento/index.php/rest/V1/search?searchCriteria[requestName]=sku&searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=%Nike%&searchCriteria[filter_groups][0][filters][0][condition_type]=like

**Comment by userException** [comment]
@ishakhsuvarov can you help with this one?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
