### ISSUE TITLE
Display issue for product configuration (Admin)

### ISSUE THREAD

**Issue by alexey-svistunov** [magento/magento2#2774]
At the product edit page in Magento admin there is a z-index issue with product configurations. If you disable simple configuration product and click on the actions menu is is displayed wrong. 

![image](https://cloud.githubusercontent.com/assets/4942588/11927093/8a94b6dc-a7d2-11e5-9134-d0042ec4650d.png)

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @alexey-svistunov thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
