### ISSUE TITLE
Lorem ipsum articles can't be deleted

### ISSUE THREAD

**Issue by smamonto** [magento/magento2#27831]
### Preconditions (*)

1. I've already deleted the lorem ipsum articles, but they still show up on the website.
2. ![Screen Shot 2020-04-12 at 10 08 09 PM](https://user-images.githubusercontent.com/63550680/79072245-2dd06b00-7d0a-11ea-8ca8-e04516b2414e.png)

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. All lorem ipsum articles are deleted
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by mrtuvn** [comment]
Do you try to clear caches ?
seem problem not related with magento

**Comment by krishprakash** [comment]
Hi @smamonto.GitHub issue tracker is intended for mangento core technical issues only kindly refer[ magento community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this
Thank you !!
