### ISSUE TITLE
Data in Order information page is not trimming before comparring

### ISSUE THREAD

**Issue by themystery404** [magento/magento2#27837]
### Preconditions (*)

1. Magento CE 2.3.4

### Steps to reproduce (*)

1. Place order
2. Go to http://example.com/sales/guest/form/
3. Try to find order with additional space in the end of "Billing Last Name" or "Billing ZIP Code"

Another case:
1. Place order with additional space in Billing Last Name
2. Go to http://example.com/sales/guest/form/
3. Try to find order without space in the end of Billing last Name

### Expected result (*)

1. Show order information
![expected-result](https://user-images.githubusercontent.com/13555241/79112263-d6bcab80-7d86-11ea-9c3d-e5f2a8ce316a.png)

### Actual result (*)

1. Error: You entered incorrect data. Please try again.
![error-trimmimg-data-on-order-information-page](https://user-images.githubusercontent.com/13555241/79112062-67df5280-7d86-11ea-9726-366d85cb971e.png)

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27837-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27837-2-4-develop.instances.magento-community.engineering/admin_5efd](https://i-27837-2-4-develop.instances.magento-community.engineering/admin_5efd)
Login: `5ca49599` Password: `7ac658b208e0`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @themystery404,
In Billing Last name and Zip code field, Trimming functionality is not applied.

**See attached the screenshot:**
![Orders and Returns](https://user-images.githubusercontent.com/24711761/79189348-22cb2700-7e3f-11ea-8750-74d278addd1e.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33340` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
