### ISSUE TITLE
 Unable to apply patch Magento\Catalog\Setup\Patch\Schema\EnableSegmentation for module Magento_Catalog.

### ISSUE THREAD

**Issue by jhakamlesh** [magento/magento2#27836]
### Preconditions (*)

1. **Magento 2.4-develop**
> Server version: Apache/2.4.41 (Ubuntu)
> Server built:   2019-08-14T14:36:32
> PHP 7.3.11-0ubuntu0.19.10.3 (cli) (built: Feb 12 2020 15:22:33) ( NTS )
> mysql  Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce (*)

1. Just Initated the installation and proceed after providing database credentials. 

### Expected result (*)

1. It should be showing a success message that i have done with my magento setup.

### Actual result (*)

Module 'Magento_Catalog':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\Catalog\Setup\Patch\Schema\EnableSegmentation for module Magento_Catalog. Original exception message: Invalid column data type "" in /var/www/html/magento2/lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php:247
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(1021): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Catalog')
#1 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(839): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#3 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(371): call_user_func_array(Array, Array)
#4 /var/www/html/magento2/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/html/magento2/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#6 /var/www/html/magento2/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/magento2/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/magento2/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(115): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/magento2/vendor/laminas/laminas-mvc/src/DispatchListener.php(117): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/html/magento2/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/magento2/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/magento2/vendor/laminas/laminas-mvc/src/Application.php(339): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/magento2/setup/index.php(39): Laminas\Mvc\Application->run()
#14 {main}

**Comment by eugene-shab** [comment]
@jhakamlesh What is your version of MySQL?

**Comment by jhakamlesh** [comment]
@eugene-shab mysql Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))

I already have mentioned above.

**Comment by raksbisht** [comment]
> @eugene-shab mysql Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))
> 
> I already have mentioned above.

Try installing Mysql Version 5.7.10. It will work.

**Comment by dalu** [comment]
What I find amazing is that despite a previous version having a soltion for MySQL 8 compatibility, it's not been included in the codebase. https://github.com/magento/magento2/issues/26465

**Comment by aemm2016** [comment]
the solution is, to install mysql 5.7.10 ??
really ?

everytime I have to play with magento installations, there's something really odd, and I get headaches from too much headshaking during googling the odd solutions to the problems, which try to block me from the installations. In the beginning I thought magento2 is new, it will become better. But, no, its like magento1, its a hopeless broken system... I cannot understand why magento - devs have so less opinion about the quality of their work.  I will warn everyone who ask for consult if magento is useful in their IT-Shop-Strategy, that it is not and they should keep their hands off.

**Comment by prabhatkumar0** [comment]
@jhakamlesh  how you solved it i am also getting this error alson tyried with 5.7 mysql version but no success.
i have installed php 7.1.33, mysql 8.0.21,windows 10, apache 2.4.46
