### ISSUE TITLE
Never utilised this part of code

### ISSUE THREAD

**Issue by syedsaleem086** [magento/magento2#27835]
https://github.com/magento/magento2/blob/86515dd16f7039d67a6e5bb3155b403cb86f5de0/app/code/Magento/CatalogInventory/Model/ResourceModel/Stock.php#L347

**Comment by gwharton** [comment]
$where is used at line 355???

**Comment by krishprakash** [comment]
Hi @syedsaleem086. Thank you for your report and hope you got the answer.
Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this topic.
