### ISSUE TITLE
Rendering Placement Issue -Shopping Cart Items After Container in Widget

### ISSUE THREAD

**Issue by ajithkumar-maragathavel** [magento/magento2#27833]
### Preconditions (*)

1. Goto _Content -> Elements -> Blocks -> Click Add New Block_ , Create and save a new cms block with any content.
2. Goto _Content -> Elements -> Widgets -> Click Add Widget_, Create a widget with the following options and layout updates.

**Type** -> _CMS Static Block_
**Display on** -> _Specified Page_
**Page** -> _Shopping Cart_
**Container** -> _Shopping Cart Items After_
**Block** -> _Select the cms block created in the above step._

### Steps to reproduce (*)

1. Create a new CMS Block with any content.
2. Create a new Widget with the conditions specified in the preconditions.
3. Add any product to the cart and navigate to the shopping cart page.
4. Widget is rendered above the shopping cart items section.

### Expected result (*)

Since I have selected **Shopping Cart Items After** in the widget configuration, the widget should be rendered below the shopping cart items section.
![ss2-expected](https://user-images.githubusercontent.com/47966038/79076066-cb309c80-7d14-11ea-954d-5ef7bfb369d4.png)

### Actual result (*)

But the widget is rendered above the shopping cart items section. Please see the below attachment.
![ss-1-actual](https://user-images.githubusercontent.com/47966038/79076095-f9ae7780-7d14-11ea-85d0-d5dae16c5141.png)

**Comment by ajithkumar-maragathavel** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-27833-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27833-2-4-develop.instances.magento-community.engineering/admin_77eb](https://i-27833-2-4-develop.instances.magento-community.engineering/admin_77eb)
Login: `7f504185` Password: `8209a4625495`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27833-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27833-2-4-develop.instances.magento-community.engineering/admin_a873](https://i-27833-2-4-develop.instances.magento-community.engineering/admin_a873)
Login: `d73d386b` Password: `3496b05de060`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33343` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel. Thank you for your report. 
The issue has been fixed in magento/magento2#27834 by @ajithkumar-maragathavel in 2.4-develop branch
Related commit(s):
 - [a11126d08eae713e49b547f3cd27aeaccf6c0b53](https://github.com/magento/magento2/commit/a11126d08eae713e49b547f3cd27aeaccf6c0b53)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel, @ajithkumar-maragathavel. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33343` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
