### ISSUE TITLE
Refactor ReCaptcha to improve Google Page Speed score

### ISSUE THREAD

**Issue by extroniks** [magento/magento2#27844]
### Preconditions (*)

1. Magento 2.3.X
2. ReCaptcha enabled and configured

### Steps to reproduce (*)

1. Enable google recaptcha
2. Run google lighthouse audit

### Expected result (*)

1. Minimal impact on page speed score
2. Load / preload the required assets without blocking main thread

### Actual result (*)

1. Assets are loaded within components with mage init, delaying execution
2. Causes bad lighthouse score

![image](https://user-images.githubusercontent.com/16757761/79132130-0a5cfd00-7daa-11ea-9d40-a76fcbb472f2.png)
![image](https://user-images.githubusercontent.com/16757761/79132150-15179200-7daa-11ea-84ca-201156a69db9.png)

**Comment by prasannachelladurai90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90, here is your [Magento instance](https://i-27844-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27844-2-4-develop.instances.magento-community.engineering/admin_9907](https://i-27844-2-4-develop.instances.magento-community.engineering/admin_9907)
Login: `8e9557e2` Password: `b82f67b1bfb8`
Instance will be terminated in up to 3 hours.

**Comment by prasannachelladurai90** [comment]
@magento give me 2.3.5p1 instance

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.3.5p1 instance for you

**Comment by davidwindell** [comment]
A vote from me for this! Although I'm not sure if https://github.com/magento/security-package/pull/191 might have solved it in 2.4?

**Comment by engcom-Delta** [comment]
@extroniks @davidwindell  I checked issue on magento 2.4-develop + [security-package 1.0-develop](https://github.com/magento/security-package) and I didn't have such decrease of page load.
**Manual testing scenario:**
- Install magento 2.4-develop with [security-package 1.0-develop](https://github.com/magento/security-package)
- Enable recapthca for Contact Us and Newsletter Subscription
![image](https://user-images.githubusercontent.com/51681379/99155197-7005c480-26be-11eb-8394-b75365061a90.png)
- Go to Contact Us page
- Run google lighthouse audit

**Result:**
Reduce JavaScript execution time is 1.5 s
![image](https://user-images.githubusercontent.com/51681379/99155276-1baf1480-26bf-11eb-95d5-0382c332be63.png)


I close this issue as recaptcha is not part of magento code base
Please feel free to create issue in [security-package repo](https://github.com/magento/security-package/issues) for further investigation if it is still reproducible on the latest magento version

**Comment by xpoback** [comment]
Any idea whether this ever will be fixed for Magento 2.3.x?

**Comment by WebKenth** [comment]
@engcom-Delta this is most certainly a Magento issue

You have chosen in your module to not allow the javascript to be deferred which would solve the entire issue -.-'

**Comment by WebKenth** [comment]
> @engcom-Delta this is most certainly a Magento issue
> 
> You have chosen in your module to not allow the javascript to be deferred which would solve the entire issue -.-'

Not to mention you have decided to split the module into 17 different modules....

When all the recaptcha module is supposed to do is load one single javascript file and appending the api keys....

This is one hell of a bloated module

Sure from an architectural standpoint it's nice that all the features are split out, but be real here, when are you ever going to only use one of the modules?

Surely the 17 modules could have been reduces to maybe 3 modules?

The small performance drops each module adds is enough to question why the split is even necessary 

I mean come on...

module-re-captcha-admin-ui
module-re-captcha-checkout
module-re-captcha-contact
module-re-captcha-customer
module-re-captcha-frontend-ui
module-re-captcha-migration
module-re-captcha-newsletter
module-re-captcha-paypal
module-re-captcha-review
module-re-captcha-send-friend
module-re-captcha-ui
module-re-captcha-user
module-re-captcha-validation
module-re-captcha-validation-api
module-re-captcha-version-2-checkbox
module-re-captcha-version-2-invisible
module-re-captcha-version-3-invisible
