### ISSUE TITLE
how do Reuse template 'Images and Videos' tab in catalog_product_edit?

### ISSUE THREAD

**Issue by xanka** [magento/magento2#2784]
I'm trying create Custom module upload image. In custom module i want use template like this.
![capture](https://cloud.githubusercontent.com/assets/13864969/11950679/26b4bcca-a8bd-11e5-965d-bc4418f2c6de.JPG)
thanks :)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
