### ISSUE TITLE
You already have an account validation fails after reloading the Checkout page for guest users.

### ISSUE THREAD

**Issue by ajithkumar-maragathavel** [magento/magento2#27856]
### Preconditions (*)

1. Add one or two products to the cart
2. Please take an email id that doesn't have an account with the Magento.

### Steps to reproduce (*)

1. Add one or two products to the cart.
2. Navigate to the checkout page as a guest user.
3. Enter the email id _(which does not have an account with the Magento)_ in the **Email Address** field.
4. After entering the email id, Click Tab button or Click First Name field or Click in the empty area.
5. AJAX call will execute in the background to check the given email id is present in Magento.
6. Since the given email id is not present in Magento, It will not prompt you to log in.
7. **Reload the checkout page**, Magento says the given email id already exists. But the email is not present in Magento.

### Expected result (*)

1. Since the given email id is not present in Magento, after reloading the checkout page, It should not show login form in checkout. Please see the screenshot below:
![guest-user](https://user-images.githubusercontent.com/47966038/79249512-fc3ad980-7e9a-11ea-8ef5-5abc5bb96b98.png)

### Actual result (*)

1. But Magento shows that the given email id already exist. Please login message after reloading the checkout page. Please see the screenshot below.
![guest-user-error](https://user-images.githubusercontent.com/47966038/79249630-2d1b0e80-7e9b-11ea-976f-b93c34b17940.png)

**Comment by ajithkumar-maragathavel** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-27856-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27856-2-4-develop.instances.magento-community.engineering/admin_bd49](https://i-27856-2-4-develop.instances.magento-community.engineering/admin_bd49)
Login: `40e4edde` Password: `8c09a4a8645f`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@ajithkumar-maragathavel Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by mrtuvn** [comment]
Duplicated with https://github.com/magento/magento2/issues/26903
