### ISSUE TITLE
Limit in Compare product list 

### ISSUE THREAD

**Issue by nitin19** [magento/magento2#27851]
Hello,
I am working with one project using Magento 2.3.3. I want to functionality like user can add maximum 'x' number of products in compare list.
For ex. Admin will set maximum number 3 of product for compare list. Then user will add 4th product then there will display a message like 'You can add only 3 products.'

If we will add more products in the compare list then there is design very messy in desktop and mobile devices. So If this functionality is available then it will be resolved the default.

If anyone has an idea let me know.

Thanks

**Comment by ajijshekh123** [comment]
Hello @nitin19 ,
Please follow the Magento Add Issues process. Add the issue as per the Magento standard format.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Thanks.

**Comment by ajijshekh123** [comment]
@nitin19 - Any update?

**Comment by ajijshekh123** [comment]
@nitin19 - Let me close this issue now. If you want to reopen this issue please follow the Magento Issue reporting guidelines.

Thanks.
