### ISSUE TITLE
Unable to add extension attribute for Order Address

### ISSUE THREAD

**Issue by MTheProgrammer** [magento/magento2#27859]
### Preconditions (*)
1. Magento 2.3.4 OS
2. PHP 7.3.10

### Steps to reproduce (*)
1.Create module with extension_attributes.xml file:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Sales\Api\Data\OrderAddressInterface">
        <attribute code="my_attribute" type="string"/>
    </extension_attributes>
</config>
```
2. Run magento cache:clean && magento setup:di:compile

### Expected result (*)
1. Interface Magento\Sales\Api\Data\OrderAddressExtensionInterface has two new methods: getMyAttribute(): string and setMyAttribute(string $value)

### Actual result (*)
1. Generated interface does not have any methods.

**Comment by vpashovski** [comment]
I have same issue.
When we deploy to server and run `setup:di:compile` Extension attribute methods are not generated.
The module exists in `app/etc/config.php`.

To generate the methods we have to run `setup:di:compile` again.
The directory where the deployment is happening is empty and we need to generate all files in this directory and then run `setup:upgrade` and switch the symlink to this directory.
