### ISSUE TITLE
Switching between store views gives "404 Not Found" when the customer is logged in and there is a difference in the URL key between the store views Magento 2.3.x #27852

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#27853]
### Preconditions (*)

1. Magento Open Source Version 2.3.3 and Magento Open Source Version 2.3.4

### Steps to reproduce (*)

1. Install Magento 2.3.4
2. Create Second Store Views (French)
3. Rename the code of English store view to 'en'
4. Rename the code of Frenchstore view to 'fr'
5. Modify the configuration to add store code to the URL
6. Create new simple product (use below data)
        - Name : Simple Product English
	- SKU : simple-product-test
	- **Click on Save**
7. Switch to the French store view and edit the name and url_key
	- Name : Simple Product French
	- URL Key: simple-product-french
	- **Click on Save**
8. Now open the product page by going to {url}/en/simple-product-english.html
9. Switch 3-4 times between those two store views (English and French)
10. everything is okay and we can see the products in the two store views with the correct URL for each store
11. Now Create a customer from the frontend
12. Login using this customer
13. Go back to the product page
14. Try to switch between the store views (English/French) in the product page 3-4 times
15. **Bom**: you will start see the 404 Not found

### Expected result (*)

1. We expected to see the product page with the correct URL for all store views

### Actual result (*)

1.  we are getting "404 Not Found"

**Comment by zexperto** [comment]
@magento give me 2.3.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @zexperto. Thank you for your request. I'm working on Magento 2.3.4-develop instance for you

**Comment by zexperto** [comment]
The bug is exist in Magento 2.3.x, Cannot reproduce it in Magento 2.4

**Comment by krishprakash** [comment]
Hi @zexperto. Thank you for your report.
Issue is not reproduce it in Magento 2.4 latest version so we can not confirm this as per community guidelines.
Same issue to #27680
