### ISSUE TITLE
Storeswitcher from default pages

### ISSUE THREAD

**Issue by TheLaughingThird** [magento/magento2#27862]
Magento 2 in 2020 just want to know if its not a complete joke ..After all the adjustments, the stuff they put in in every update to make your system crash, and all the paid crap nobody asks for...

If I get this right , you can create storeviews for your languages , but when SWITCHING to these storeviews you get the DOMAINNAME/stores/store/switchrequest/ error...

So a CMS system thats redisgned to Magento 2 does not have actual functionality to serve the right pages to your customer in 2020 ? 

Summary of the issue

Install magento 2.3.3. and make different storeviews

Information on your environment

Php 7.3 Magento 2.3.3 Apache Centos 7 server

Steps to reproduce

Just make the storeviews for 2 ore more languages and go to a default page like customer/account/create/ 
THEN
Switch storeview from Netherlands to English and let the bullshit begin

Expected and actual results

Expected for a CMS system in 2020 that there would be fucntionality in it to serve the right page to the customer. Actuall result is the stores/store/switchrequest/ page

**Comment by b2bdokter** [comment]
Summary of the issue

Install magento 2.3.3. and make different storeviews

 Information on your environment

Php 7.3 Magento 2.3.3 Apache  Centos 7 server


 Steps to reproduce

Just make to storeviews and go to a default page like  **customer/account/create/**

Switch storeview from Netherlands to English and let the bullshit begin

 Expected and actual results

Expected for a CMS system in 2020 that there would be fucntionality in it to serve the right page to the customer. Actuall result is the stores/store/switchrequest/ page

**Comment by b2bdokter** [comment]
@magento-engcom-team Why its not valid ?

**Comment by mrtuvn** [comment]
@b2bdokter not valid because your template not follow default base template
When report bugs magento  required Preconditions, Steps to reproduce, Expected, Actual Result
More details that you provide will help maintainers easier to reproduce exactly your problem

**Comment by b2bdokter** [comment]
**Summary of the issue**

Install magento 2.3.3. and make different storeviews

**Information on your environment**

Php 7.3 Magento 2.3.3 Apache Centos 7 server

**Steps to reproduce**

Just make to storeviews and go to a default page like customer/account/create/

Switch storeview from Netherlands to English and let the bullshit begin

**Expected and actual results**

Expected for a CMS system in 2020 that there would be fucntionality in it to serve the right page to the customer. Actuall result is the stores/store/switchrequest/ page

**Comment by b2bdokter** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @b2bdokter. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @b2bdokter, here is your [Magento instance](https://i-27862-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27862-2-4-develop.instances.magento-community.engineering/admin_afb3](https://i-27862-2-4-develop.instances.magento-community.engineering/admin_afb3)
Login: `7919aac9` Password: `dade73333b39`
Instance will be terminated in up to 3 hours.

**Comment by manishgoswamig** [comment]
Hi @b2bdokter did you check the issue ?

**Comment by engcom-Delta** [comment]
Hi @b2bdokter thank you for your report. Please update issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Could you reproduce your issue on magento instance? Use command from https://github.com/magento/magento2/issues/27862#issuecomment-613957307

**Comment by krishprakash** [comment]
Hi @b2bdokter Feel free to reopen/comment the issue once you update the issue as per issue reporting guidelines
and also confirm the issue on magento instance once
Thanks!!
