### ISSUE TITLE
Cannot run composer install due to PHP Fatal error (Undefined class constant 'PRE_COMMAND_RUN')

### ISSUE THREAD

**Issue by bnymn** [magento/magento2#27867]
I cannot run `composer install` in a fresh 2.4-develop branch.

### Preconditions (*)

1. Ubuntu 18.04
2. PHP 7.2.29
3. Composer 1.6.3

### Steps to reproduce (*)

1. `git checkout 2.4-branch`
2. `composer install`

### Expected result (*)

1. I expect the composer to install all dependencies

### Actual result (*)

1. I got a fatal error as shown here:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 8 installs, 82 updates, 0 removals
  - Installing laminas/laminas-dependency-plugin (1.0.3): Loading from cache
PHP Fatal error:  Uncaught Error: Undefined class constant 'PRE_COMMAND_RUN' in /home/bunyamin/Project/magento2/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php:63
Stack trace:
#0 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(378): Laminas\DependencyPlugin\DependencyRewriterPlugin::getSubscribedEvents()
#1 /usr/share/php/Composer/Plugin/PluginManager.php(239): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#3 /usr/share/php/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage) in /home/bunyamin/Project/magento2/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php on line 63

Fatal error: Uncaught Error: Undefined class constant 'PRE_COMMAND_RUN' in /home/bunyamin/Project/magento2/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php:63
Stack trace:
#0 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(378): Laminas\DependencyPlugin\DependencyRewriterPlugin::getSubscribedEvents()
#1 /usr/share/php/Composer/Plugin/PluginManager.php(239): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#3 /usr/share/php/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage) in /home/bunyamin/Project/magento2/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php on line 63
```
![image](https://user-images.githubusercontent.com/3506402/79357262-14186900-7f40-11ea-9f23-abab0291e345.png)

**Comment by bnymn** [comment]
This is happening because of the composer version. If you use the following composer version, the issue will not happen.
- Composer 1.9.1

**Comment by SerhiyShkolyarenko** [comment]
I had the same issue, but Magento 2.4 installation works fine with latest(1.10.5) composer.

**Comment by narendra0087** [comment]
This issue is with pulgins in M2 under /var/www/html/magento/vendor/ just remove the vendor directory from the magento root directory and rerun the composer update.

**Comment by xantek-imc** [comment]
Encountered this issue upgrading to Magento 2.3.5-p1 and self-update composer to the latest version (1.10.6) solved.

**Comment by Eddcapone** [comment]
Run `composer self-update`

**Comment by medigeek** [comment]
If this happens on Ubuntu 18.04, you probably have an outdated version that doesn't even support self-update unfortunately. 
So here's a oneliner to install the latest version in /usr/local/bin:

```
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
```

Check:
```
which -a composer
/usr/local/bin/composer --version
```

**Comment by usman786cs** [comment]
Thanks @medigeek it worked for me

**Comment by mayankzalavadia** [comment]
It's just because of the composer's old version.

You need to install the new version: Composer version 1.10.10

First check your composer version if it's 1.10.10 then run `composer self-update` Command it'll solve your issue. If it's older version the follow below steps:
```
composer -V
sudo apt remove composer
cd /tmp
wget http://getcomposer.org/download/1.10.5/composer.phar

php composer.phar -V
sudo mv composer.phar /usr/bin/composer
sudo chmod 750 /usr/bin/composer
composer -V
```

Now if your composer's version is 1.10.10 then run `composer self-update` and after that run `composer update`

**That's it!!**

**Comment by pianistchopin** [comment]
Great
@bnymn 

I had ever faced with this error but I had got you , so I can fix this error

->
"-  update version as composer 1.10.3 "

Thank you so much!

**Comment by andy-igoo** [comment]
> This issue is with pulgins in M2 under /var/www/html/magento/vendor/ just remove the vendor directory from the magento root directory and rerun the composer update.

Unless you're upgrading Magento (as outlined in the docs), `composer update` should never be run. Use `composer install` only to reinstall modules otherwise this can cause issues and the module versions are changed.
