### ISSUE TITLE
async.magento.catalog.api.specialpricestorageinterface.update.post - operations report different result than sent in message

### ISSUE THREAD

**Issue by bjornmeat** [magento/magento2#27865]
### Preconditions (*)

1. Magento Commerce 2.3.4
2. Magento async api endpoint for async.magento.catalog.api.specialpricestorageinterface.update.post 

### Steps to reproduce (*)
1. Multiple different updates sent for different skus to : /rest/all/async/V1/products/special-price
2. In Magento db operation table and in detailed status for bulk/asynk in API we see the original message.
3. After message is processed. A different sku / message is processed and added to operation table.
### Expected result (*)

1. The proper message and result should be saved in Magento operation table.

### Actual result (*)

1. Message saved in Magento operation and result from bulk status api endpoint.

{
    "operations_list": [
        {
            "id": 927,
            "bulk_uuid": "74bf51dc-60ea-4815-8e7c-047f7a7bdfbb",
            "topic_name": "async.magento.catalog.api.specialpricestorageinterface.update.post",
            "serialized_data": "{\"entity_id\":null,\"entity_link\":\"\",\"meta_information\":\"{\\\"prices\\\":[{\\\"price\\\":198,\\\"store_id\\\":0,\\\"sku\\\":\\\"175025\\\",\\\"price_from\\\":\\\"2020-04-18 00:00:00\\\",\\\"price_to\\\":\\\"2020-04-18 23:59:00\\\"}]}\"}",
            "result_serialized_data": null,
            "status": 4,
            "result_message": null,
            "error_code": null
        }
    ],
    "user_type": 1,
    "bulk_id": "74bf51dc-60ea-4815-8e7c-047f7a7bdfbb",
    "description": "Topic async.magento.catalog.api.specialpricestorageinterface.update.post",
    "start_time": "2020-04-15 09:45:27",
    "user_id": 2,
    "operation_count": 1
}

2. Result after message processed by queue consumer. (Note bulk id and SKU in result.)
{
    "operations_list": [
        {
            "id": 927,
            "bulk_uuid": "74bf51dc-60ea-4815-8e7c-047f7a7bdfbb",
            "topic_name": "async.magento.catalog.api.specialpricestorageinterface.update.post",
            "serialized_data": null,
            "result_serialized_data": "[{\"message\":\"Future Update already exists in this time range. Set a different range and try again.\",\"parameters\":[\"138.6\",\"154170\",\"0\",\"2020-04-18 00:00:37\",\"2020-04-18 23:59:38\"]},{\"message\":\"The product that was requested doesn't exist. Verify the product and try again. Row ID: SKU = 117890, Store ID: 0, Price From: 2020-04-18 00:00:00, Price To: 2020-04-18 23:59:00.\",\"parameters\":[\"117890\",\"0\",\"2020-04-18 00:00:00\",\"2020-04-18 23:59:00\"]},{\"message\":\"The product that was requested doesn't exist. Verify the product and try again. Row ID: SKU = 117890, Store ID: 0, Price From: 2020-04-18 00:00:00, Price To: 2020-04-18 23:59:00.\",\"parameters\":[\"117890\",\"0\",\"2020-04-18 00:00:00\",\"2020-04-18 23:59:00\"]},{\"message\":\"The product that was requested doesn't exist. Verify the product and try again. Row ID: SKU = 117890, Store ID: 0, Price From: 2020-04-18 00:00:00, Price To: 2020-04-18 23:59:00.\",\"parameters\":[\"117890\",\"0\",\"2020-04-18 00:00:00\",\"2020-04-18 23:59:00\"]},{\"message\":\"The product that was requested doesn't exist. Verify the product and try again. Row ID: SKU = 117890, Store ID: 0, Price From: 2020-04-18 00:00:00, Price To: 2020-04-18 23:59:00.\",\"parameters\":[\"117890\",\"0\",\"2020-04-18 00:00:00\",\"2020-04-18 23:59:00\"]}]",
            "status": 1,
            "result_message": "Service execution success Magento\\Catalog\\Model\\Product\\Price\\SpecialPriceStorage::update",
            "error_code": null
        }
    ],
    "user_type": 1,
    "bulk_id": "74bf51dc-60ea-4815-8e7c-047f7a7bdfbb",
    "description": "Topic async.magento.catalog.api.specialpricestorageinterface.update.post",
    "start_time": "2020-04-15 09:45:27",
    "user_id": 2,
    "operation_count": 1
}

**Comment by bjornmeat** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bjornmeat. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bjornmeat, here is your [Magento instance](https://i-27865-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27865-2-4-develop.instances.magento-community.engineering/admin_232e](https://i-27865-2-4-develop.instances.magento-community.engineering/admin_232e)
Login: `cbf39616` Password: `70a57e5239eb`
Instance will be terminated in up to 3 hours.

**Comment by bjornmeat** [comment]
Some screenshots from db tables magento_operation and magento_bulk
![Screenshot 2020-04-22 at 21 53 02](https://user-images.githubusercontent.com/1308059/80140863-e28b4780-85a8-11ea-8bd6-893740570ab1.png)
![Screenshot 2020-04-22 at 21 52 55](https://user-images.githubusercontent.com/1308059/80140873-e5863800-85a8-11ea-8369-3974aecb833b.png)

**Comment by bubasuma** [comment]
Internal Magento team is working on this issue right now.

**Comment by bubasuma** [comment]
Hi @bjornmeat.

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into magento/magento2:2.4-develop branch(es).
Related commit(s):
60df223978e203a31811e626f983df5ae045aa9c

The fix will be available with the upcoming 2.4.1 release.
