### ISSUE TITLE
Free shipping for physical and virtual products with table rate not working correctly

### ISSUE THREAD

**Issue by SteveMcC71** [magento/magento2#27861]
### Preconditions (*)

1. Magento 2.3.4
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Create table rate file 
![image](https://user-images.githubusercontent.com/51681379/99841954-a6888700-2b77-11eb-953a-f836216ec124.png)
2. Stores -> Configuration -> Sales -> Shipping Methods -> Table Rates  "Price vs. Destination"  
3. Include Virtual Products in Price Calculation as "No"
![image](https://user-images.githubusercontent.com/51681379/99841724-4c87c180-2b77-11eb-9c57-996abc140077.png)
4. Create a Simple Product with price 40$ 
5. Create a Virtual Product with price 20$
6. Navigate to Storefront and add both products to the Cart 

### Expected result (*)

1. If a customer adds a physical product AND a virtual or downloadable product to their cart, the cost of the downloadable or virtual product should not be used to calculate the free shipping threshold (in our example 20$)
2. Shipping price should 20$ according simple product price 40$

### Actual result (*)

1. If we have both a virtual and physical product in our cart and the total value exceeds our threshold of € 20 the shipping is free because it considers both types of product rather than excluding the virtual product from the calculation as expected.
![image](https://user-images.githubusercontent.com/51681379/99841906-92dd2080-2b77-11eb-939c-decc43c61a6f.png)

2. With JUST virtual products in the cart the calculation is correct, or with JUST physical products in cart the calculation is correct.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39292` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @SteveMcC71. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39292` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by tsfanning21** [comment]
> Hi @SteveMcC71.
> 
> Thank you for your report and collaboration!
> 
> The related internal Jira ticket `MC-39292` was closed as `Fixed`.
> 
> The fix will be available with the upcoming `2.4.3` release.

I do not believe the scope of this fix was correct.  It does not include fixes to the Freeshipping carrier in the module-offline-shipping where the free shipping threshold is calculated.  This may be intentional as more than likely any change here would require another configuration setting (I.E. ignore virtual items) but it seems incorrect to assume that virtual items would be included in the free shipping threshold check.
