### ISSUE TITLE
Plugin for ProductRepositoryInerface save method is not working.

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#27872]
### Summary (*)
Plugin for ProductRepositoryInerface save method is not working. I have tried all types for plugin, like afterSave, beforeSave, and aroundSave. Nothing is working. Plugin against other methods of ProductRepository is working fine. afterGetById, beforeGetById and aroungGetById is working fine.

I am using magento 2.3.4 CE with sample data.

### Examples (*)
di.xml file
```xml <?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
<type name="Magento\Catalog\Api\ProductRepositoryInterface">
    <plugin name="testname_example_product" type="Testname\PluginExample\Plugin\Product"/>
</type>
</config>
```

Plugin class code.
```php
public function beforeSave(ProductRepositoryInterface $subject, ProductInterface $product, $saveOptions = false)
    {
        $this->logger->info('Before Save Product');
        return null;
    }
    public function aroundSave(ProductRepositoryInterface $subject, callable $proceed, ProductInterface $product, $saveOptions = false){
        $this->logger->info('before Around save');
        $productResult = $proceed($product, $saveOptions);
        $this->logger->info('After Around save');
        return $productResult;
    }
```

**Comment by baltechies** [comment]
@magento-engcom-team  any suggestion?

**Comment by engcom-Echo** [comment]
Hi, @baltechies. Thank you for your report.

An example of using a plugin for this method can be found in Magento.
![image](https://user-images.githubusercontent.com/51681435/79837852-c32ec780-83ba-11ea-9b1d-4d68b804c86a.png)
![image](https://user-images.githubusercontent.com/51681435/79837906-d6419780-83ba-11ea-8e7a-b9284a9e2eca.png)

**Comment by baltechies** [comment]
@engcom-Echo  Yes, I know the steps for plugin into. I had installed a fresh magento 2.3.4 with sample data. Plugin on other repositories like customerReposistoryInterface aroundSave is working fine. But this is not working against ProductReposistoryInterface save method.

**Comment by engcom-Echo** [comment]
Hi @baltechies. For example, provide me your plugin. I'll try a check.

**Comment by baltechies** [comment]
@engcom-Echo Please check this.
[Soscodes.zip](https://github.com/magento/magento2/files/4562931/Soscodes.zip)

**Comment by baltechies** [comment]
@engcom-Echo Also there is an error temando account ID error in exception file. I am using magento 2 sample data. 
 [2020-05-01 07:45:54] temando.CRITICAL: "accountId" is required. Enter and try again. {"exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): \"accountId\" is required. Enter and try again. at /Users/apple/Sites/m2-practice/vendor/magento/framework/Exception/InputException.php:91)"} []

**Comment by engcom-Echo** [comment]
Hi @baltechies. Thanks for your report.
I checked your code and that works fine.
For creating a product I used Endpoint: POST <host>/rest/default/V1/products
[Step 3. Create the simple products](https://devdocs.magento.com/guides/v2.3/rest/tutorials/configurable-product/create-simple-products.html)

Result : 
![image](https://user-images.githubusercontent.com/51681435/80946070-ebc0b380-8df5-11ea-9846-51062d055328.png)

Did you mean another way to create a product?

**Comment by baltechies** [comment]
@engcom-Echo I had used n98-magerun2.phar dev console for product update. 
![Screen Shot 2020-05-04 at 3 01 34 PM](https://user-images.githubusercontent.com/13519944/80953026-597dd700-8e18-11ea-90d0-6ee275860583.png)

Then I check it by adding/updating product from admin panel.

I will check it by re-installing magento again.

**Comment by baltechies** [comment]
Hi @engcom-Echo,
I tried it by installing latest magento version and I need to run reindex for its working.
One thing I also noticed that Magento\Catalog\Model\ProductRepository class is used for save product from API. For admin controller  Magento\Catalog\Model\Product.php is used. 
So I need apply plugin into different class (Product.php or Controller Class) for admin save product functionality.

But I don't know why magento use 2 different classes to save product.

**Comment by engcom-Echo** [comment]
Hi @baltechies. Thank you for your investigation.
I think we close the issue because the description does not address the issue.
I think it is better to open a new question in the context of the last comment to improve understanding of the issue in the future.
