### ISSUE TITLE
Empty folders in magento2-base should contain empty file

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#2787]
Hi,
I was trying to setup a [Satis](https://github.com/composer/satis) server for Magento2 packages, the package `magento/magento2-base` is causing problem for setup.

Thing is that the package `magento/magento2-base` contains empty folders:
`app/code/Magento`
`app/design/adminhtml/Magento`
`app/design/frontend/Magento`

these folder should ideally contain an `empty` file or `.gitkeep` as now when the satis server runs a build and re-zips package to is local dist folder it uses "Phar::buildFromIterator()" which ignores those empty folder and hence causes a error during the composer setup for Magento2 project (when post setup script runs) and throws an error for folders not found.

Thanks.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by atishgoswami** [comment]
Hi,

I totally agree that it is not a technical issue, but still wanted to mention as most of us might be setting up local composer package servers, [Satis](https://github.com/composer/satis) being more likely, to serve there magento2 setups.

Anyways thanks for the links, and appreciate the feedback.

Thanks
