### ISSUE TITLE
Duplicated keys for Weight

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27883]
### Preconditions (*)
Resource Models use `const` to avoid typos and represent reusable element across the application.

https://github.com/magento/magento2/blob/eab4eba4809e866c55527fd2cbe63ab9b488a6b7/app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate/CSV/ColumnResolver.php#L11-L28

You can notice that 2 `const`s are using the same value, which is developer's mistake.

The result of such mistake is fact, that just after - in `nameToPositionMap` - one position is overridden by another :facepalm: 
![image](https://user-images.githubusercontent.com/1639941/81227735-2d677f00-8fed-11ea-8c1a-4b8bccaf2bb5.png)

But when you scan the Module, you notice that there is actually field for Package Weight (destination):

https://github.com/magento/magento2/blob/95c176af90e7e9775cf01414f1fe3b2cdba1990b/app/code/Magento/OfflineShipping/Model/Carrier/Tablerate.php#L229-L240

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by sdzhepa** [comment]
Hello @lbajsarowicz 

Could you please provide more details in the description.
It is not clear 
- what exactly wrong
- what expected result should be
- any information about the consequences of this issue. How it affects users and/or developers

Thank you in advance!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34113` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by thomas-kl1** [comment]
Don't stale

**Comment by thomas-kl1** [comment]
sdfs

**Comment by lbajsarowicz** [comment]
<3

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-34113` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
