### ISSUE TITLE
Use default value not working on custom admin form

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#27881]
### Introduction 
In scope of MC-18153, the [following html element](https://github.com/magento/magento2/commit/7caf49278aa88391decae5d1a6a5afe4427e6ad9#diff-a7a8af13cbad18dd607f30a5ea391642R65) got stronger escaping.

```
diff --git a/app/code/Magento/Catalog/view/adminhtml/templates/catalog/form/renderer/fieldset/element.phtml b/app/code/Magento/Catalog/view/adminhtml/templates/catalog/form/renderer/fieldset/element.phtml
index cbda491a6474..ac18504d15dd 100644
--- a/app/code/Magento/Catalog/view/adminhtml/templates/catalog/form/renderer/fieldset/element.phtml
+++ b/app/code/Magento/Catalog/view/adminhtml/templates/catalog/form/renderer/fieldset/element.phtml
@@ -62,7 +62,7 @@ $fieldAttributes = $fieldId . ' class="' . $block->escapeHtmlAttr($fieldClass) .
                             class="use-default-control"
                             id="<?= $element->getHtmlId() ?>_default"
                             <?php if ($block->usedDefault()) :?> checked="checked"<?php endif; ?>
-                            onclick="<?= $block->escapeHtmlAttr($elementToggleCode) ?>"
+                            onclick="<?= $block->escapeHtmlAttr($block->escapeJs($elementToggleCode)) ?>"
                             value="<?= $block->escapeHtmlAttr($block->getAttributeCode()) ?>"/>
                     <span class="use-default-label"><?= $block->escapeHtml(__('Use Default Value')) ?></span>
                 </label>
```
### Preconditions (*)

1. 2.3.4 CE

### Steps to reproduce (*)

1. Create a custom Admin form in a page with scoping enabled.

### Expected result (*)

1. Try to uncheck the "Use default value" checkbox
2. Specific field should be editable.

### Actual result (*)

1. Error is thrown in the console log
<img width="1848" alt="Screen Shot 2020-04-17 at 12 57 53" src="https://user-images.githubusercontent.com/9752966/79562538-907b8b00-80ab-11ea-8cc1-9508c18f500f.png">
<img width="1057" alt="Screen Shot 2020-04-17 at 12 57 45" src="https://user-images.githubusercontent.com/9752966/79562541-91142180-80ab-11ea-881d-d0ee9c81b69b.png">

2. Field stays disabled

### Solution 
If this change gets reverted, the checkbox works again but I don't know if this is the correct solution.

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27881-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27881-2-4-develop.instances.magento-community.engineering/admin_8d32](https://i-27881-2-4-develop.instances.magento-community.engineering/admin_8d32)
Login: `97517293` Password: `e8ecddcd47cb`
Instance will be terminated in up to 3 hours.

**Comment by koenner01** [comment]
You will not be able to reproduce this on 2.4-develop branch as "MC-18153: Correct phtml templates" (https://github.com/magento/magento2/commit/7caf49278aa88391decae5d1a6a5afe4427e6ad9#diff-a7a8af13cbad18dd607f30a5ea391642) was never merged into 2.4-develop

**Comment by sudheers-kensium** [comment]
@duckchip I am closing this issue. Feel free to reopen if you are having issue on latest Magento instance.

**Comment by hostep** [comment]
@sudheers-kensium: you shouldn't close this issue just because for an unknown reason Magento forgot to forward port MC-18153 to 2.4-develop. We should first figure out why that didn't happen and only then we can decide if we can close this. Could you try to figure this out by asking around and re-open the issue please?
