### ISSUE TITLE
Products per Page on Grid Allowed Values

### ISSUE THREAD

**Issue by ABDUL-RAQEEB** [magento/magento2#27894]
### Preconditions (*)

1. We want to display products like **12,24,36,48, All** but unable to do this. Below we have attached two screenshots one is expected and the other which is right now.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. 
![store view issue-expected](https://user-images.githubusercontent.com/15211627/79679120-81681a80-821c-11ea-9936-a24a12c89517.JPG)

### Actual result (*)

1. 
![store view issue](https://user-images.githubusercontent.com/15211627/79679086-44038d00-821c-11ea-8cf7-ea0b5f559662.JPG)

**Comment by shikhamis11** [comment]
@ABDUL-RAQEEB please share magento version

**Comment by manishthummar111** [comment]
Hi @ABDUL-RAQEEB .
I've checked and not found an issue in Magento 2.3.4
To get your expected result need to the following config
![2020_04_21_config](https://user-images.githubusercontent.com/19949807/79832414-fe36f800-83c6-11ea-8c76-fd97ca4f4c4b.png)

I've got on frontend All option
![2020_04_21_frontend](https://user-images.githubusercontent.com/19949807/79832455-1b6bc680-83c7-11ea-88b0-d6ebbfa0d506.png)

**Comment by shikhamis11** [comment]
@ABDUL-RAQEEB Please check comment of @manishthummar111 
the issue is not at magento instance
