### ISSUE TITLE
Configurable Product: Custom Options make a discount percent of Tier Price error

### ISSUE THREAD

**Issue by noxin911** [magento/magento2#279]
![Untitled](https://f.cloud.github.com/assets/1251903/372717/c8462ecc-a369-11e2-9bad-f4d934089785.png)
Dear Devs,

like you can read here there is a bug for simple products maybe fixed right now:
http:/www.magentocommerce.com/boards/viewthread/284007/

But if I set a tier price for the product when I add a "configurable product" and then I added size option in the “Custom Options” in the product edit page the front page show me the wrong discount percent.

The frontend page show all tier price just like “Buy 5 for $16.99 each and save 100% “. The discount percent of all tier price shows “100%”

I'm using magento 1.7.0.2.

Change in file /js/varien/product.js Line 748:
Replace

for (var i = 0; i < this.tierPrices.length; i++) {

with

for (var i = 0; i > this.tierPrices.length; i++) {

fixed the error on the frontpage BUT i'm sure that this is not a GOOD solution. Hopefully some one can fix this error in a right way.

Best

**Comment by kadniki** [comment]
I don't know whether it's perfect solution or not, but you saved lot of my trouble.
Your solutions did work for me like a dream.

I believe, It's just value printing and nothing else. So reversing loop to get correct output is the right method.

Thanks a ton anyways.
You rock.
