### ISSUE TITLE
USPS Free Shipping Pre-Selected

### ISSUE THREAD

**Issue by todssmith** [magento/magento2#27901]
### Description (*)

"Select Method" USPS Free Shipping $0 is not pre-selected and defaulted for the consumer. This is a time when qualified free shipping purchases should be given priority for convenience.

It seems that Paypal allows you to bypass "Select Method" selection, but Amazon Pay doesn't. It's unknown why it's coded this way.

### Expected behavior (*)

Consumer gets to click next to continue to payment without consideration.

### Benefits

Faster checkout, most users will take free shipping over pay options.

### Additional information

Bug?

Last use M2 2.34

**Comment by chandru-199** [comment]
@magento Give me 2.4-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @chandru-199. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chandru-199, here is your [Magento instance](https://i-27901-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27901-2-4-develop.instances.magento-community.engineering/admin_df15](https://i-27901-2-4-develop.instances.magento-community.engineering/admin_df15)
Login: `0bd02e8a` Password: `40fe1528595e`
Instance will be terminated in up to 3 hours.

**Comment by chandru-199** [comment]
@magento I am working on this
