### ISSUE TITLE
Updating Customer through rest/all/V1/customers/:id resets custom attributes if the custom attributes are not passed in payload

### ISSUE THREAD

**Issue by Wohlie** [magento/magento2#27909]
Hi, we upgrade from 2.3.0 to 2.3.3-p1 and now have the following issue. Maybe also other REST api endpoints are effected by this problem.

### Preconditions (*)
1. 2.3.3-p1
2. Add at least one customer custom attribute with data type `int` e.g. type select and yes-no source model:
```php
[
    'type'           => 'int',
    'unsigned'       => true,
    'nullable'       => false,
    'default'        => 0,
    'label'          => 'Customer is whitelisted.',
    'required'       => false,
    'input'          => 'select',
    'source'         => Noyes::class, //We use here a no-yes source model, so the default value for the admin area is "no". This should not be relevant for this issue.
    'adminhtml_only' => true,
    'system'         => false,
    'position'       => 150,
    'is_visible'     => false,
]
```

### Steps to reproduce (*)
1. Register a customer in the frontend
2. Go to the admin panel and edit the new customer
3. Set the new custom attribute to `1` (`Yes`) and save the customer
4. Perform a REST call to get the customer data e.g:
```http
GET {BASE-URL}/rest/V1/customers/1
Content-Type: application/json
Authorization: Bearer ...
```
5. The new custom attribute must be `1` e.g.:
```json
...
  "custom_attributes": [
    {
      "attribute_code": "is_whitelisted",
      "value":          "1"
    }
  ]
...
```
5. Perform a customer update within the REST api with minimal data e.g.:
```json
PUT {BASE-URL}/rest/V1/customers/1
Content-Type: application/json
Authorization: Bearer ...

{
  "customer": {
    "id":                        1,
    "dob":                       "1993-09-17",
    "email":                     "foo@example.com",
    "firstname":                 "Bar",
    "lastname":                  "Baz",
    "prefix":                    "Herr",
    "store_id":                  1,
    "website_id":                1
  }
}
```
6. Perform a REST call to get the customer data e.g:
```http
GET {BASE-URL}/rest/V1/customers/1
Content-Type: application/json
Authorization: Bearer ...
```

### Expected result (*)
1. The custom attributes should be not changed:
```json
...
  "custom_attributes": [
    {
      "attribute_code": "is_whitelisted",
      "value":          "1"
    }
  ]
...
```

### Actual result (*)
1. The custom attributes was set to "0"
```json
...
  "custom_attributes": [
    {
      "attribute_code": "is_whitelisted",
      "value":          "0"
    }
  ]
...
```

Also the customer group will lost in the customer update which is related and confirmed in https://github.com/magento/magento2/issues/14663.

**Comment by sgigliotti** [comment]
I had the same problem.

I have noticed that all the custom attributes with a default value were being reset.
Setting the default value to NULL solved the problem for me.

**Comment by zyukov** [comment]
Check \Magento\Customer\Model\Plugin\UpdateCustomer::getUpdatedCustomer() CUSTOM_ATTRIBUTES should be merged.

**Comment by Zaahed** [comment]
@magento I'm working on this

**Comment by jokeputs** [comment]
We have the same problem on 2.4.7

**Comment by raldea** [comment]
We also have the same issue. Same with @sgigliotti, the issue only happens when the custom attribute has a default value. Do we have a fix for this?

**Comment by brosenberger** [comment]
@rerlinger the issue with your patch is the direction of the merge, it now copies the original customer values over the new set ones, i changed the values now to:

`$value = array_merge($originCustomer->getCustomAttributes(), $customer->getCustomAttributes());`

and setting values via rest api works as expected
