### ISSUE TITLE
Can't use alias in referenceBlock

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#27907]
### Preconditions (*)

1. Magento 2.3.4
2. Linux Server @ Rackspeed

### Steps to reproduce (*)

I tried to inject an argument to the Block **category.products.list** (_vendor\magento\module-catalog\view\frontend\layout\catalog_category_view.xml_) by calling _referenceBlock_ from my themes layout file **app\design\frontend\company\base\Magento_Catalog\layout\catalog_category_view.xml**
by using the alias **product_list** instead of the block name.

```
    <referenceBlock name="product_list">
        <arguments>
            <argument name="is_product_new" xsi:type="helper" helper="Company\Base\Helper\Product::isProductNew" />
        </arguments>
    </referenceBlock>
```

I placed `exit("test");` into the first line of my helper method isProductNew.

### Expected result (*)

It should render an empty page with the text "test".

### Actual result (*)

No exit, page loads normally.

If I use the full block name **category.products.list** instead of the alias, then it works as expected.

```
    <referenceBlock name="category.products.list">
        <arguments>
            <argument name="is_product_new" xsi:type="helper" helper="Company\Base\Helper\Product::isProductNew" />
        </arguments>
    </referenceBlock>
```

**Comment by mrtuvn** [comment]
You can use referenceBlock and referenceContainer with name only

**Comment by engcom-Alfa** [comment]
Hi, @Eddcapone. Thank you for your report!

You can use _**referenceBlock**_ and _**referenceContainer**_ with block `name="..."` attribute only, as described in dev docs in [this](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_ref) part.
An alias name serves as an identifier in the scope of the parent element.
So, we have to close it.
Thanks!
