### ISSUE TITLE
Magento test modules cause setup:di:compile to fail 

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27908]
```
PHP Fatal error:  Uncaught TypeError: rtrim() expects parameter 1 to be string, bool given in /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php:95
Stack trace:
#0 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php(95): rtrim(false, '\\')
#1 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php(286): Magento\Setup\Module\Di\Code\Scanner\PhpScanner->getSourceClassName('int', 'ExtensionInterf...')
#2 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php(152): Magento\Setup\Module\Di\Code\Scanner\PhpScanner->shouldGenerateClass('int', 'ExtensionInterf...', '/var/www/html/a...')
#3 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php(184): Magento\Setup\Module\Di\Code\Scanner\PhpScanner->_fetchMissingExtensionAttributesClasses(Object(ReflectionClass), '/var/www/html/a...')
#4 /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/ApplicationCodeGenerator.php(77): Magento\Setup\Module\Di\Code\Scanner\PhpS in /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php on line 95
```

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by sudheers-kensium** [comment]
@lbajsarowicz I have executed the setup:di:compile without any issue.

Please follow the Magento Add Issues process to add the issues.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by kamal02mittal** [comment]
I am facing the same issue after upgrading to Magento2.4.2-p1. I did some analysis on this and got the reason for this error.
Actually, Magento installed some new modules like Magento_TestModuleAsyncAmqp, Magento_TestModuleExtensionAttributes etc.
When you go to file 

> app/code/Magento/TestModuleExtensionAttributes/Api/Data/FakeExtensibleTwoInterface.php

you will see 

    /**
         * test incorrect return type
         *
         * **@return int**
         */
        public function getExtensionAttributes();

So, here it is asking to provide class as return type instead of `@return int`
If you will add below class as return type then it should work.

> \Magento\TestModuleExtensionAttributes\Api\Data\FakeExtensibleTwoExtensionInterface|int

Try to provide class here and then run di:compile again after clearing cache, generation etc

**Comment by nwcasebolt** [comment]
@kamal02mittal:

> So, here it is asking to provide class as return type instead of `@return int` If you will add below class as return type then it should work.
> 
> > \Magento\TestModuleExtensionAttributes\Api\Data\FakeExtensibleTwoExtensionInterface|int
> 
> Try to provide class here and then run di:compile again after clearing cache, generation etc

I ran into this problem today for the first time, and this got me around the problem. Thank you.
