### ISSUE TITLE
integrity constraint violation in sales_clean_orders cron job

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#27918]
### Preconditions (*)

1. Magento 2.3.4 (but also Magento 2.3.5)

### Steps to reproduce (*)

1. Create a catalog price rule with coupon.
2. Add product to cart and apply the coupon.
3. Start placing an order. Choose a credit card payment method, or any payment method that allows transitioning the order to the `pending_payment` status works.
4. Do not finish the payment, so that the order stays with the `pending_payment` status.
5. Wait for the `sales_clean_orders` cron job to process this order.

### Expected result (*)

1. The cron job `sales_clean_orders` runs smoothly and the unfinished order should now be cancelled.

### Actual result (*)

1. The cron job `sales_clean_orders` runs into an exception:
  ```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (salesrule_customer, CONSTRAINT SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID FOREIGN KEY (rule_id) REFERENCES salesrule (rule_id) ON DELETE CASCADE), query was: INSERT INTO salesrule_customer () VALUES ()
  ```

### Observations and Fix
The problem lies in the class `Magento\SalesRule\Model\Coupon\UpdateCouponUsages` in method `updateCustomerRuleUsages()`. The problem occurs if no sales rule/customer relation (`$ruleCustomer`) exists (`$ruleCustomer->getId() == false`) and if `$increment == 0`. In that case the method will try to save the sales rule/customer relation `$ruleCustomer` without any data being set on it. In particular the field `rule_id` will be `null`, which than causes the foreign key constraint violation.

The problem can be easily fixed by adding an `else` clause to the `if/elseif` instruction:
```
        else {
            return;
        }
```
This will cause the sales rule/customer relation to not be saved.

**Comment by ktruehl** [comment]
The `yes` checkbox in the bot questionaire doesn't work. I cannot check it. But yes, I do confirm that it can be reproduced on a vanilla Magento instance.

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-27918-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27918-2-4-develop.instances.magento-community.engineering/admin_3eeb](https://i-27918-2-4-develop.instances.magento-community.engineering/admin_3eeb)
Login: `b5c6dfa8` Password: `0a949c0e9b1d`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
Hi @ktruehl I wasn't enable to reproduce the issue on M2.4 develop and M.2.3.4 
Can you give me more details on how reproduce the issue?

Thanks

**Comment by ktruehl** [comment]
Hi @CarmineDamore78,

You won't be able to reproduce the issue on a Magento instance that lasts only 3 hours. The default setting for the delay for cleaning out orders is 8 hours. So you would have to create an order, wait for at least 8 hours without touching the order, then check the result of the `sales_clean_orders` cron job in the `cron_schedule` table.

**Comment by ivanweiler** [comment]
Similar problems here, I think this is related to:

https://github.com/magento/magento2/issues/16779
https://github.com/magento/magento2/issues/19230

It seems this is really old issue that was never properly fixed.

**Comment by ivanenkoaleksei** [comment]
I have the same issue on Magento version 2.4.1
