### ISSUE TITLE
Our Customers are not getting Order Confirmation Email

### ISSUE THREAD

**Issue by ABDUL-RAQEEB** [magento/magento2#27919]
### Steps to reproduce (*)

We are using **Magento ver. 2.3.4**
We are facing the Order Confirmation Email issue. Our customers are continuously blaming us that they are not receiving email as they punch order on our portal. Please fix this issue.

### Expected result (*)

We want that our customers must be getting their **ORDER CONFIRMATION EMAIL** as they punched order on our portal.
We are using system default configuration right now.

### Actual result (*)

This time customers are not getting the order confirmation email. 

Here is the Screenshot of it.
![Order confirmation](https://user-images.githubusercontent.com/15211627/79861397-c98a6700-83ed-11ea-82c4-e683788b9822.JPG)

**Comment by shikhamis11** [comment]
@ABDUL-RAQEEB this issue is not reproducible at magento 2.3.4 instance. Please ask your server provider to check if mail server setup on your server or it may be issue due to custom extension or customisation at your server
