### ISSUE TITLE
Error editor content page, block

### ISSUE THREAD

**Issue by quockhanh91** [magento/magento2#2792]
Hello,
Button Show / Hide Editor no action, button Insert Widget..., Insert Image..., Insert Variable... in content editor page, block no show, display = none.
<img width="1280" alt="screen shot 2015-12-23 at 11 52 53 am" src="https://cloud.githubusercontent.com/assets/14105484/11971231/6126aed6-a96c-11e5-8b43-7c3b310c9cff.png">
<img width="1280" alt="screen shot 2015-12-23 at 11 49 58 am" src="https://cloud.githubusercontent.com/assets/14105484/11971232/6182b7c6-a96c-11e5-87e6-96f0abef6753.png">

**Comment by Nas1k** [comment]
Hello @quockhanh91 can you show in Console tab when page loaded. I think it's can be some js error.
What are magento version do you install|?
You can try remove cache and static content. Please run:

``` shell
rm -rf var/* pub/static/*
```

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
