### ISSUE TITLE
In the photorama zoomed view, vertical movement of images is faster than horizontal

### ISSUE THREAD

**Issue by devranowski** [magento/magento2#27924]
### Preconditions (*)

1. A Magento 2.3.x or 2.4-develop
2. At least one product with at least two images.
3. Ideally, it should be tested on a physical device - a touchscreen smartphone.

### Steps to reproduce (*)

1. Go to mobile PDP.
2. Tap on an image and zoom in.

### Expected result (*)

1. When moving a picture up/down in the zoomed view on mobile PDP, the movement speed should be the same as when moving the picture left/right.

### Actual result (*)

1. When moving a picture in the zoomed view on mobile PDP, the vertical movement is faster than horizontal.
2. https://drive.google.com/file/d/1VIXtDVigFxurmyThbiU1zAXtDcIQxbX1/view?usp=sharing

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-27924-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27924-2-4-develop.instances.magento-community.engineering/admin_3566](https://i-27924-2-4-develop.instances.magento-community.engineering/admin_3566)
Login: `a09c55cb` Password: `6d77422ef112`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34166` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-27924-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27924-2-4-develop.instances.magento-community.engineering/admin_6acf](https://i-27924-2-4-develop.instances.magento-community.engineering/admin_6acf)
Login: `cc381f64` Password: `37370666de08`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
Hi @jkbdbrnwsk . Thanks for collaboration. This PR was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the [link](https://www.youtube.com/watch?v=4dFuALJ0L4I&t=145s)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by mrtuvn** [comment]
Reopen this because it's closed by stale when it's actually issue! @devranowski can you confirm still reproduce problem at 2.4.6

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @devranowski,

Thank you for reporting and collaboration.

We have verified the issue in Latest Magento 2.4-develop instance using touch screen smartphone and we are not able to reproduce the issue.

Could you please try to reproduce the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @devranowski,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
