### ISSUE TITLE
We need only mouse over preview for Color Palettes

### ISSUE THREAD

**Issue by ABDUL-RAQEEB** [magento/magento2#27922]
### Description (*)

**We are using Magento Ver 2.3.4**
Our color palettes are working fine like below screenshot when we click on any color palette it opened in Images preview frame which we don't want. Please suggest.
**We want the only mouse over preview for our COLOR PALETTES** 

![color palettes](https://user-images.githubusercontent.com/15211627/79864526-0c9b0900-83f3-11ea-948d-324279d6db94.png)

### Benefits

It will show our product images and color palettes as well. Right now if color palettes are opened in 
image preview than its product images is hidden. 
Please suggest how we can stop color palettes not to display on the image preview frame.

**Comment by VigneshVenkatesan154** [comment]
@ABDUL-RAQEEB Please provide more insights on this ticket

**Comment by VigneshVenkatesan154** [comment]
Closing this issue as no inputs from @ABDUL-RAQEEB
