### ISSUE TITLE
Checkout: Placing an order using the enter key causes a redirect to the checkout

### ISSUE THREAD

**Issue by vestman** [magento/magento2#27925]
### Preconditions (*)

1. Tested on Magento 2.3.2, 2.3.3, 2.3.4 and 2.3.5
2. At least one product enabled
3. Enable "Purchase Order" as a payment method, or any other payment method where one or more input fields needs to be filled out

### Steps to reproduce (*)

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field

### Expected result (*)

1. form should be submitted (and validated) on keyboard Enter. Order is placed

### Actual result (*)

1. The checkout page reloads
![magento-issue--27925](https://user-images.githubusercontent.com/564243/80070559-6ad70180-8543-11ea-8e31-6d4700746bf0.gif)

**Comment by vestman** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vestman. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vestman, here is your [Magento instance](https://i-27925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27925-2-4-develop.instances.magento-community.engineering/admin_5c30](https://i-27925-2-4-develop.instances.magento-community.engineering/admin_5c30)
Login: `f87617b8` Password: `60b2fb6c03ff`
Instance will be terminated in up to 3 hours.

**Comment by vestman** [comment]
> Hi @vestman, here is your [Magento instance](https://i-27925-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-27925-2-4-develop.instances.magento-community.engineering/admin_5c30
> Login: `f87617b8` Password: `60b2fb6c03ff`
> Instance will be terminated in up to 3 hours.

Confirmed behavior on the vanilla Magento instance provided above.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27925-2-4-develop.instances.magento-community.engineering/admin_4076](https://i-27925-2-4-develop.instances.magento-community.engineering/admin_4076)
Login: `375ebddb` Password: `fb2152b818c4`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27925-2-4-develop.instances.magento-community.engineering/admin_f2ce](https://i-27925-2-4-develop.instances.magento-community.engineering/admin_f2ce)
Login: `96574240` Password: `a03f91ac3f9f`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33618` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by CarmineDamore78** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-27925-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27925-2-3-4.instances.magento-community.engineering/admin_ee5c](https://i-27925-2-3-4.instances.magento-community.engineering/admin_ee5c)
Login: `5add296c` Password: `c915e6761b0f`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
Hi @vestman 
I was unabled to riproduce the issue on M2.3.4

**Comment by vestman** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @vestman. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @vestman, here is your [Magento instance](https://i-27925-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27925-2-3-4.instances.magento-community.engineering/admin_83a3](https://i-27925-2-3-4.instances.magento-community.engineering/admin_83a3)
Login: `05068f8d` Password: `566437dd4bf6`
Instance will be terminated in up to 3 hours.

**Comment by vestman** [comment]
@CarmineDamore78 
![magento-issue--27925](https://user-images.githubusercontent.com/564243/80070559-6ad70180-8543-11ea-8e31-6d4700746bf0.gif)

**Comment by chandru-199** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chandru-199. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chandru-199, here is your [Magento instance](https://i-27925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27925-2-4-develop.instances.magento-community.engineering/admin_0b3c](https://i-27925-2-4-develop.instances.magento-community.engineering/admin_0b3c)
Login: `4c6379ec` Password: `01ff55536c2c`
Instance will be terminated in up to 3 hours.

**Comment by chandru-199** [comment]
@magento assign me this issue.

**Comment by dhairya-shah** [comment]
I am working on this issue.

**Comment by sdzhepa** [comment]
Hello @vestman 
fyi: @dhairya-shah, @shikhamis11  

This issue has been reviewed by Magento team during the internal triage meeting.

Based on feedback from Product Managers and UX expected result should be changed.


**Expected Result**
- The order should NOT be placed and after push "Enter" button
- The page should not be reloading

I updated issue description

**Comment by vestman** [comment]
@sdzhepa 

Thanks for reviewing the issue. May I ask what led you to come to the conclusion that the form should *not* be submitted on enter keypress when the input field has focus? I'm all for a discussion, so I'll start...

If you have focus in a textbox and hit enter, the form will be submitted automatically. This behavior is consistent across all browsers and is known as implicit submission. It's a common way to submit forms and I dare to say that many (most?) of the end users will expect it to work like that. And let's not forget about accessibility. Let's quote the html5 spec:
> There are pages on the Web that are only usable if there is a way to implicitly submit forms, so user agents are strongly encouraged to support this.
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

**Comment by sdzhepa** [comment]
Hello @vestman 
fyi: @dhairya-shah, @shikhamis11

Thank you for your detailed feedback, explanation, and proof links.

I raised this issue again at the triage meeting. 
After additional discussion and detailed analysis by UX specialist, quote
> In this case, I recommend that the form should be submitted (and validated) on keyboard Enter

I will update the expected results for Issue and related PR

Thank you again and sorry for inconveniences

**Comment by schmengler** [comment]
Thanks for involving the UX team :+1:

**Comment by magento-engcom-team** [comment]
Hi @vestman. Thank you for your report. 
The issue has been fixed in magento/magento2#28172 by @vestman in 2.4-develop branch
Related commit(s):
 - [4fd92e7edc9a62c3e09f7ed0461da4f36aba4d27](https://github.com/magento/magento2/commit/4fd92e7edc9a62c3e09f7ed0461da4f36aba4d27)
 - [cf5d73b89648c31fa0832fc6a1957f13b338a512](https://github.com/magento/magento2/commit/cf5d73b89648c31fa0832fc6a1957f13b338a512)
 - [9173df72586e897d4a624a59cc7465b5fbfb23bd](https://github.com/magento/magento2/commit/9173df72586e897d4a624a59cc7465b5fbfb23bd)
 - [2dee5655c8acce78a3fd146e34b2581215786324](https://github.com/magento/magento2/commit/2dee5655c8acce78a3fd146e34b2581215786324)
 - [d59c837b3b790e51cd7abcb8ee7b3da94195a537](https://github.com/magento/magento2/commit/d59c837b3b790e51cd7abcb8ee7b3da94195a537)
 - [16fdccbe0b12d8383b2c66d680498fe24ad18432](https://github.com/magento/magento2/commit/16fdccbe0b12d8383b2c66d680498fe24ad18432)
 - [08e7e4faffca9330aaed009dbe6ddebb9f6c70ee](https://github.com/magento/magento2/commit/08e7e4faffca9330aaed009dbe6ddebb9f6c70ee)
 - [cfcd91da079114993362bbc0799b9e7b61bca8bc](https://github.com/magento/magento2/commit/cfcd91da079114993362bbc0799b9e7b61bca8bc)
 - [b97c6c3c4b63e6dc14f996dfcbf34d24051a6bd0](https://github.com/magento/magento2/commit/b97c6c3c4b63e6dc14f996dfcbf34d24051a6bd0)
 - [eb468d0e9d34692ef19ac5def5482aa16cdb4a74](https://github.com/magento/magento2/commit/eb468d0e9d34692ef19ac5def5482aa16cdb4a74)
 - [2778f768d4ede5d5d1c4ea009daac8f3264e5d58](https://github.com/magento/magento2/commit/2778f768d4ede5d5d1c4ea009daac8f3264e5d58)
 - [afbdb27c2e1b2f4c690f5574ea7605aa8f658289](https://github.com/magento/magento2/commit/afbdb27c2e1b2f4c690f5574ea7605aa8f658289)

The fix will be available with the upcoming 2.4.2 release.
