### ISSUE TITLE
Custom attribute default value not set by the api

### ISSUE THREAD

**Issue by thokiller** [magento/magento2#27937]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. go to the backend and create a product attribute with a default value. My case: multi-select, not required, 4 options 2 selected as is default and attribute code: test_default_value
2. Add this attribute to the attribute set to use it.
3. Get token for the REST API.
4. Create a new product with the REST API. (do not send the created attribute)
My payload:
`{
    "product": {
        "attribute_set_id": "4",
        "price": "4.9500",
        "sku": "test2",
        "status": "1",
        "type_id": "simple",
        "visibility": "4",
        "weight": null,
        "name": "Test 2"
    }
}`

### Expected result (*)

1. attribute is filled for created product with as value the default value. (This happens under same conditions Magento 2.1.18) 
`"custom_attributes": [
        {
            "attribute_code": "test_default_value",
            "value": "4,6"
        }
    ]`
![result_M2118](https://user-images.githubusercontent.com/35527212/79973125-4b829a80-8497-11ea-8d81-0bb4db494cf6.png)
### Actual result (*)

1. Attribute is not set to the product with the default value. In the backend no options are selected
![result_M234](https://user-images.githubusercontent.com/35527212/79973128-4c1b3100-8497-11ea-824b-43943ffa316d.png)

**Comment by lewisvoncken** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken, here is your [Magento instance](https://i-27937-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27937-2-4-develop.instances.magento-community.engineering/admin_ca84](https://i-27937-2-4-develop.instances.magento-community.engineering/admin_ca84)
Login: `7c48cffe` Password: `3125f77225ca`
Instance will be terminated in up to 3 hours.

**Comment by lewisvoncken** [comment]
@shikhamis11 this has been tested on a vanilla Magento instance.
cc @thokiller
