### ISSUE TITLE
Translation of UI components doesn't works

### ISSUE THREAD

**Issue by lucalbert** [magento/magento2#2793]
Hello,

I work on the French language pack.

I recovered all the strings to be translated with the command "`i18n:collect-phrases`".

It already seems that a lot of chains are missing, mainly those UI components templates.

But even by adding strings in my translation file, they are not taken into account.

Example on the [minicart](https://github.com/magento/magento2/blob/3b6c4971dc08fee147e91f19a84a275772d79901/app/code/Magento/Checkout/view/frontend/web/template/minicart/content.html#L56), "Go to Checkout" and "View and edit cart" is impossible to translate (I cleaned the cache, generated DI and deployed static files).

Thank you

**Comment by scholtz** [comment]
i think this issue is copy of #2630

**Comment by lucalbert** [comment]
Sorry, I think too.

I close this issue, the #2630 is being processed.
