### ISSUE TITLE
Special price styling of configurations not shown if the first configuration doesn't have a special price defined

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#27936]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1.  Create a configurable product with two configurations
2. Only set a special price on the last configuration
3. Visit the product detail page

### Expected result (*)

1. Configuration has the special price and the special price styling (old price striked through) 

### Actual result (*)

1. Configuration doesn't have the special price styling

**Comment by duckchip** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [Magento instance](https://i-27936-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27936-2-4-develop.instances.magento-community.engineering/admin_7a78](https://i-27936-2-4-develop.instances.magento-community.engineering/admin_7a78)
Login: `5183ef5e` Password: `98a5f7b42f81`
Instance will be terminated in up to 3 hours.

**Comment by duckchip** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [Magento instance](https://i-27936-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27936-2-3-4.instances.magento-community.engineering/admin_2fb2](https://i-27936-2-3-4.instances.magento-community.engineering/admin_2fb2)
Login: `0f4dcd63` Password: `b270f80b45bb`
Instance will be terminated in up to 3 hours.

**Comment by duckchip** [comment]
could not reproduce on 2.4-develop and 2.3.4. Closing this issue.

**Comment by duckchip** [comment]
This is issue is still present in Magento 2.3.3 but was fixed in commit: https://github.com/magento/magento2/commit/76b348d90f74b8f4857829b84d4f736acdbf186c

**Comment by davirs** [comment]
@duckchip I have exactly same issue at magento 2.4.0:
![image](https://user-images.githubusercontent.com/4355062/105775355-78437100-5f45-11eb-998d-06d9f9e8dcb1.png)

![image](https://user-images.githubusercontent.com/4355062/105775422-8beed780-5f45-11eb-9c66-b1be5038d6d3.png)

The issue is not finished...
