### ISSUE TITLE
The constructor of the class \Magento\Framework\View\TemplateEngine\Xhtml\ResultFactory can be shortened by using PHP 5.5 class name resolution via ::class

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2794]
https://mage2.pro/t/310

**Comment by shiftedreality** [comment]
Hi, @dfediuk 

We have many places with possible use of ::class notations. This is not issue and will be improved in future.

**Comment by piotrekkaminski** [comment]
Closing in favor of more generic https://github.com/magento/magento2/issues/4068
