### ISSUE TITLE
Level 3rd level top navigation is not working

### ISSUE THREAD

**Issue by amanuni** [magento/magento2#27945]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Create top navigation at least 3rd level (Top->Level1->Level2)

### Expected result (*)
1. When i hover on top level it will drop-down 2nd Level and when i hover to 2nd Level it should drop-down 3rd level and able to click on 3rd level menu items.

### Actual result (*)
1. When i am hovering on 2nd level its opening 3rd level but when i moving mouse to 3rd level its disappearing. Before selecting or clicking on any menu item.

**Comment by amanuni** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amanuni. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amanuni, here is your [Magento instance](https://i-27945-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27945-2-4-develop.instances.magento-community.engineering/admin_4716](https://i-27945-2-4-develop.instances.magento-community.engineering/admin_4716)
Login: `20390246` Password: `c4a9de8c5ec5`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @amanuni,
This issue is relevant to the below issues.
https://github.com/magento/magento2/issues/14930
https://github.com/magento/magento2/issues/25589
This issue already fixed and closed that's why I have to close this issue.

Thanks.
