### ISSUE TITLE
Elastic search giving error when filtering  attribute at Layered navigation 

### ISSUE THREAD

**Issue by santosh-gaggle** [magento/magento2#27941]
Elastic search giving error when filtering  attribute at Layered navigation 

### Preconditions (*)

using Magento 2.3.3 
Elasticsearch 6.0+ 

### Steps to reproduce (*)
On the category page when filtering the attribute like color,size etc. 
it's giving the error and not getting and product 

### Expected result (*)

it's should be given the filtered result with the product

### Actual result (*)

 main.CRITICAL: {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [finset]","line":1,"col":232}],"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [finset]","line":1,"col":232},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [finset]\",\"line\":1,\"col\":232}],\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [finset]\",\"line\":1,\"col\":232},\"status\":400} at /var/domains/caminada-caminadabeenmode.nl/application/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636)"} []

**Comment by VivekShingala** [comment]
Hi @santosh-gaggle 

How did you fix it?
