### ISSUE TITLE
Missing store_name in GraphQl Resolver

### ISSUE THREAD

**Issue by sunel** [magento/magento2#27952]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Request for store_name in storeConfig Query

### Expected result (*)

1. Return store name 
```json
{
  "data":{
       "storeConfig":{
               "root_category_id":2,
               "store_name": "Magento"
        }
}
```

### Actual result (*)

```json
{
  "data":{
       "storeConfig":{
               "root_category_id":2,
               "store_name": null
        }
}
```

As Mentioned in schema 'store_name' can be queried 

https://github.com/magento/magento2/blob/d4a90989db911a27af3aa9ce81c1f6d9f7b1f0f4/app/code/Magento/StoreGraphQl/etc/schema.graphqls#L33

But in `StoreConfigDataProvider.php` its not resolved

https://github.com/magento/magento2/blob/d4a90989db911a27af3aa9ce81c1f6d9f7b1f0f4/app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php#L71-L94

**Comment by yogeshkarodiya** [comment]
I am working on this issue
