### ISSUE TITLE
magento2.3.4 can't open the product detail page

### ISSUE THREAD

**Issue by ATA-ERA** [magento/magento2#27950]
I use the porto theme. I add a simple product. The homepage is normal. I can see the new product and the category is also normal. I click in the product detail page. It seems like loading page all the time.
![image](https://user-images.githubusercontent.com/64180350/80053985-c3f96200-8550-11ea-8871-9d87c1b083ce.png)

**Comment by ATA-ERA** [comment]
Yes

**Comment by ATA-ERA** [comment]
> 嗨@ ATA-ERA。感谢您的报告。
> 为了帮助我们处理此问题，请确保您提供了以下信息：
> 
> * [ ]  问题摘要
> * [ ]  有关您的环境的信息
> * [ ]  重现步骤
> * [ ]  预期和实际结果
> 
> 请按照以下**步骤进行操作**，以确保在Magento实例上可复制该问题。要在我们的环境中部署香草Magento实例，请对此问题添加评论：
> 
> `@magento give me 2.4-develop instance` -即将发布的2.4.x版本
> 
> 有关更多详细信息，请查阅[Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist)文档。
> 
> @ ATA-ERA您是否确认能够按照复制步骤在香草Magento实例上复制该问题？
> 
> * [ ]  是
> * [ ]  没有
> 
> * 加入[Magento Community Engineering Slack，](https://opensource.magento.com/slack)并在[#github](https://magentocommeng.slack.com/messages/C7KB93M32)频道中[提问](https://magentocommeng.slack.com/messages/C7KB93M32)。

Yes

**Comment by magento-engcom-team** [comment]
Hi @ATA-ERA. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ATA-ERA, here is your [Magento instance](https://i-27950-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27950-2-4-develop.instances.magento-community.engineering/admin_0c76](https://i-27950-2-4-develop.instances.magento-community.engineering/admin_0c76)
Login: `145e35ae` Password: `dbce9381e507`
Instance will be terminated in up to 3 hours.

**Comment by ATA-ERA** [comment]
> 嗨@ ATA-ERA。感谢您的报告。
> 为了帮助我们处理此问题，请确保您提供了以下信息：
> 
> * [ ]  问题摘要
> * [ ]  有关您的环境的信息
> * [ ]  重现步骤
> * [ ]  预期和实际结果
> 
> 请按照以下**步骤进行操作**，以确保在Magento实例上可复制该问题。要在我们的环境中部署香草Magento实例，请对此问题添加评论：
> 
> `@magento give me 2.4-develop instance` -即将发布的2.4.x版本
> 
> 有关更多详细信息，请查阅[Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist)文档。
> 
> @ ATA-ERA您是否确认能够按照复制步骤在香草Magento实例上复制该问题？
> 
> * [ ]  是
> * [ ]  没有
> 
> * 加入[Magento Community Engineering Slack，](https://opensource.magento.com/slack)并在[#github](https://magentocommeng.slack.com/messages/C7KB93M32)频道中[提问](https://magentocommeng.slack.com/messages/C7KB93

> 嗨，@ ATA-ERA，这是您的[Magento实例](https://i-27950-2-4-develop.instances.magento-community.engineering)。
> 管理员访问权限：[https](https://i-27950-2-4-develop.instances.magento-community.engineering/admin_0c76) : [//i-27950-2-4-develop.instances.magento-community.engineering/admin_0c76](https://i-27950-2-4-develop.instances.magento-community.engineering/admin_0c76)
> 登录：`145e35ae`密码：`dbce9381e507`
> 实例将在3个小时内终止。

I need magento2.3.4

**Comment by magento-engcom-team** [comment]
Hi @ATA-ERA. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ATA-ERA** [comment]
> 嗨@ ATA-ERA。感谢您的要求。我正在为您开发Magento 2.4开发实例

I don't need2.4

**Comment by magento-engcom-team** [comment]
Hi @ATA-ERA, here is your [Magento instance](https://i-27950-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27950-2-4-develop.instances.magento-community.engineering/admin_1356](https://i-27950-2-4-develop.instances.magento-community.engineering/admin_1356)
Login: `fe52293e` Password: `8c14a16d53a2`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @ATA-ERA, 
Can not able to reproduce on latest instance
It should be your porto theme issue or any of your custom module issue.
Kindly connect their for further assistance
Thank you !!
