### ISSUE TITLE
Moving Magento to new server

### ISSUE THREAD

**Issue by nkarthickannan** [magento/magento2#2796]
Hi,

I have a Magento 2 website in our server. I want to setup a local copy of the website in my system. In Magento 1, we usually take a complete backup of the files and DB and place them in the target system. Then we would remove the app/etc/local.xml file which will proceed the installation again.

What is the equivalent for Magento 2 for the same process?

Thanks

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
