### ISSUE TITLE
Plugins in \Magento\Framework namespace

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27962]
### Preconditions (*)
One of Magento Architects contacted me in private message blaming me for [introducing Plugin to the Core](https://github.com/magento/magento2/tree/2.3.4/lib/internal/Magento/Framework/App/Action/Plugin) that is not allowed in Magento and couldn't have been done by Magento Employees due to Quality Standards.

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/App/Action/Plugin/Design.php#L6-L10

lol.

As I've introduced another 2 plugins and renamed existing one to follow the naming convention, there are 3 plugins in the `\Magento\Framework` namespace. As the architect wasn't so nice to tell me where outside \Magento\Framework` I should put these plugins, I create issue to satisfy "Quality Standards" of Magento.

The plugins to be moved:
https://github.com/magento/magento2/tree/2.4-develop/lib/internal/Magento/Framework/App/Action/Plugin

#### Before you continue, please remember that plugins in `\Magento\Framework` were never allowed!

:facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: 

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php#L6-L18
https://github.com/magento/magento2/blob/892dee45e4f80ae7df04b4ce550971e5a0453eff/app/etc/di.xml#L1805-L1807
https://github.com/magento/partners-magento2ee/blob/6d49dacca99f5276f09bbddd50866440f3d3fccc/app/code/Magento/ScalableCheckout/etc/di.xml#L34-L36
https://github.com/magento/magento2/blob/ae9962561509ff5e0c74b17551f90640e155db2b/app/code/Magento/Amqp/etc/di.xml#L9-L17
https://github.com/magento/magento2/blob/4b66b00c574a0e092597f1603ede7bfcb8a95ed2/app/code/Magento/Eav/etc/di.xml#L108-L110
https://github.com/magento/magento2/blob/d938e7bcab3f4620d5d0facb23a05ab81304e988/app/code/Magento/Store/etc/di.xml#L36-L38

### Steps to reproduce (*)
N/A

### Expected result (*)
Magento Framework shouldn't contain any plugins

### Actual result (*)
1. Magento Framework contains plugins, that should be misplaced in different modules, see description

**Comment by magento-engcom-team** [comment]
@ihor-sviziev Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33718` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lbajsarowicz** [comment]
Fixed the `ActionInterface` plugins. If you @maghamed care about the other plugins - assign it internally, otherwise close the ticket.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27965 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [d938e7bcab3f4620d5d0facb23a05ab81304e988](https://github.com/magento/magento2/commit/d938e7bcab3f4620d5d0facb23a05ab81304e988)
 - [ae58f560edad58b8c9b6fd01f9460b7c37fd2895](https://github.com/magento/magento2/commit/ae58f560edad58b8c9b6fd01f9460b7c37fd2895)
 - [02aae13792fc648c00f6f8e153e208dc0d00c67d](https://github.com/magento/magento2/commit/02aae13792fc648c00f6f8e153e208dc0d00c67d)
 - [a84633e0b01bb2778418274d97d22758f534b008](https://github.com/magento/magento2/commit/a84633e0b01bb2778418274d97d22758f534b008)
 - [7ff60630b48733141b471bc5c9eeb5c8412fc7b5](https://github.com/magento/magento2/commit/7ff60630b48733141b471bc5c9eeb5c8412fc7b5)

The fix will be available with the upcoming 2.4.1 release.

**Comment by DmitryFurs** [comment]
I also found 2 plugins in the commerce edition, and they are exactly the same

**vendor/magento/module-scalable-checkout/etc/di.xml**
```xml
<type name="Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor">
    <plugin name="object_constraints_resolver" type="Magento\Framework\ForeignKey\ObjectRelationProcessor\Plugin" />
</type>
```

**vendor/magento/module-scalable-oms/etc/di.xml**
```xml
<type name="Magento\Framework\Model\ResourceModel\Db\ObjectRelationProcessor">
    <plugin name="object_constraints_resolver" type="Magento\Framework\ForeignKey\ObjectRelationProcessor\Plugin" />
</type>
```

**Comment by ihor-sviziev** [comment]
@DmitryFurs feel free to fill the separate issue in corresponding repository and / or create Pull Request

**Comment by DmitryFurs** [comment]
@ihor-sviziev this applies to **commerce** edition. Is this the right place to create a issue?

**Comment by ihor-sviziev** [comment]
@sidolov @gabrieldagama could you help with reporting issue to Commerce version?

**Comment by lbajsarowicz** [comment]
@DmitryFurs As long as you are Magento partner, you are able to access:
- https://github.com/magento/partners-magento2ee
- https://github.com/magento/partners-magento2b2b

If you don't have access, working with Magento partner, please reach out to @magento/community-engineering-team
