### ISSUE TITLE
Exclude the certain product from Google search

### ISSUE THREAD

**Issue by Sharmilasrini95** [magento/magento2#27968]
### Description (*)
Exclude the certain product from Google search
1. I have added the below.
catalog->product->Edit product->Migration_Design(Tab)->Layout Update XML

<head>
    <meta name="robots" content="NOINDEX,NOFOLLOW"/>
</head>
2. Add 'product url  ' (product file name ) in robots.txt file which is under root file of the project folder 

### Expected behavior (*)
Google should not be scroll the url.

### Additional information
But it is not reflecting. Is there any possibility to do this. Please suggest

**Comment by Sharmilasrini95** [comment]
Description (*)
Exclude the certain product from Google search

I have added the below.
catalog->product->Edit product->Migration_Design(Tab)->Layout Update XML
2. Add 'product url ' (product file name ) in robots.txt file which is under root file of the project folder
Expected behavior (*)
Google should not be scroll the url.

Additional information
But it is not reflecting. Is there any possibility to do this. Please suggest

**Comment by engcom-Alfa** [comment]
Duplicate of #27970
