### ISSUE TITLE
Sampledata not imported for Configurable Products.

### ISSUE THREAD

**Issue by kishennagaraju** [magento/magento2#27979]
### Issue Description/Summary (*)

After installing the magento 2.3.4, when I run the command to install the sampledata i.e., "php bin/magento sampledata:deploy", the data for configurable products are not imported into the database. Only 52 products are imported in the database table "catalog_product_entity".

### Preconditions (*)
**1.) My LAMP Environment:**
    A.) Apache 2.4
    B.) PHP 7.3
    C.) MySQL 5.7
**2.) SYSTEM CONFIGS:**
    
![Screenshot 2020-04-24 at 11 05 11 PM](https://user-images.githubusercontent.com/41683536/80240789-16856c00-8680-11ea-8ee2-0d29049733d7.png)

**3.) DOCKER PREFERENCES (USING LAMP IN DOCKER):**

![Screenshot 2020-04-24 at 11 06 45 PM](https://user-images.githubusercontent.com/41683536/80240934-4fbddc00-8680-11ea-81c2-6bb828514891.png)

### Steps to reproduce (*)

1.) Run the command in Mac Terminal - 
    **composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition m2community**

2.) Enter the magento public and private key when asked.

3.) After the setup is done, install magento by running the command - 
    **php bin/magento setup:install --backend-frontname="admin" --db-host="127.0.0.1" --db-name="magento" --db-user="root" --db-password="root" --language="en_US" --currency="USD" --timezone="Asia/Kolkata" --use-rewrites=1 --use-secure=0 --base-url="http://m2community.loc" --admin-user=admin --admin-password=admin@123 --admin-email=admin@newmagento.com --admin-firstname=admin --admin-lastname=user --cleanup-database**

4.) Run the command to deploy the sampledata as mentioned below:
            **php bin/magento sampledata:deploy**

5.) Run the command to import the sampledata in the database.
            **php bin/magento setup:upgrade**

### Expected result (*)

1. All the sample data including the data for configurable products must be imported without an issue as depicted below:

![Screenshot 2020-04-24 at 11 06 45 PM](https://user-images.githubusercontent.com/41683536/80241861-fce52400-8681-11ea-8d89-9bdb9957bc0d.png)

### Actual result (*)

1. Data for configurable products and other parts of sample data is not being imported.

**FRONT-END SCREENSHOT:**

![Screenshot 2020-04-24 at 11 20 32 PM](https://user-images.githubusercontent.com/41683536/80242077-5baa9d80-8682-11ea-9aff-730c1e499f25.png)

**DATABASE SCREENSHOT:**

![Screenshot 2020-04-24 at 11 22 37 PM](https://user-images.githubusercontent.com/41683536/80242219-a4625680-8682-11ea-9d0d-8dd898fb4bb5.png)

Please advice regarding this. Any help will be greatly appreciated.

Regards,
Kishen.

**Comment by engcom-Delta** [comment]
Hi @kishennagaraju thank you for your report. I'm not able to reproduce issue by steps you described on 2.4-develop and on the latest composer version 2.4.1 - sample data is successfully deploy
Please see [Magento 2.4 system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)

If you'd like to update the issue, please reopen it.
