### ISSUE TITLE
free shipping shopping cart rule not applied in cart page,when cart rule  has shipping country/state/Postcode based condition

### ISSUE THREAD

**Issue by kishorekumarkesavan** [magento/magento2#27974]
Preconditions (*)

1. Magento 2.4

Steps to reproduce (*)

1. In Store > configurations > sales > shipping > select the origin
2. Enable 'free shipping' shipping method along with any other shipping method
3. Create shopping cart rule, with condition based on shipping country/state/Postcode and  cart rule's action 'Free shipping' is enabled with the 'for shipment with matching items' condition.
![rulecondition](https://user-images.githubusercontent.com/56116915/80219867-b03d2100-8660-11ea-9aa9-31f1d4577d63.png)
![ruleactionapplied](https://user-images.githubusercontent.com/56116915/80219903-bcc17980-8660-11ea-8656-b4cf41d5063a.png)
4. Add matching products, apply the shopping cart rule.

Expected result (*)
1. Shopping rule should be applied and 'Free shipping' shipping method is selected

Actual result (*)
1. Shopping rule  not applied

![rulesnotapplied](https://user-images.githubusercontent.com/56116915/80220077-f5615300-8660-11ea-9dde-40d51d59d603.png)

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27974-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27974-2-4-develop.instances.magento-community.engineering/admin_b84d](https://i-27974-2-4-develop.instances.magento-community.engineering/admin_b84d)
Login: `244b6e92` Password: `674fd54ca9cf`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @kishorekumarkesavan,
I have verified this issue as per your steps to reproduce and screenshot.
This issue I have found in Latest Magento 2.4 Instance.
**See attached screenshot:**

![1](https://user-images.githubusercontent.com/24711761/80449776-9d1aa180-893d-11ea-8337-77f466d6b97e.png)

![2](https://user-images.githubusercontent.com/24711761/80449779-a0159200-893d-11ea-837b-88a037a5b83a.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33800` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
