### ISSUE TITLE
Privacy and Cookie Policy link not display as active on current page.

### ISSUE THREAD

**Issue by RHapani** [magento/magento2#27985]
### Preconditions (*)

Install Magento 2.3.4

### Description (*)
Go to the footer and click on the "**Privacy and Cookie Policy**" link. After the redirect, It's not displayed as active link as like other footer links.

### Steps to reproduce (*)
Go to footer and click on the "**Privacy and Cookie Policy**" link

### Expected result (*)

It should be displayed as an active link when the "**Privacy and Cookie Policy**" page is open.

### Actual result (*)

It's not displayed as an active link when the "**Privacy and Cookie Policy**" page is open.

![2020-04-29_18-33-01](https://user-images.githubusercontent.com/3409584/80657190-94fb5880-8a48-11ea-8e46-a516527142a7.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-27985-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27985-2-4-develop.instances.magento-community.engineering/admin_bf87](https://i-27985-2-4-develop.instances.magento-community.engineering/admin_bf87)
Login: `dc18c05b` Password: `89c2ab8b95f3`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33752` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27985-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27985-2-4-develop.instances.magento-community.engineering/admin_02f2](https://i-27985-2-4-develop.instances.magento-community.engineering/admin_02f2)
Login: `3bd61110` Password: `cd4af8bf6385`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @RHapani. Thank you for your report. 
The issue has been fixed in magento/magento2#28004 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [d5cc8cb120da0072dee54c7cc850241319b9c2c1](https://github.com/magento/magento2/commit/d5cc8cb120da0072dee54c7cc850241319b9c2c1)
 - [331ce388f1cf5f24d8667081e37641928d0c159e](https://github.com/magento/magento2/commit/331ce388f1cf5f24d8667081e37641928d0c159e)

The fix will be available with the upcoming 2.4.1 release.
