### ISSUE TITLE
Mini cart  'View and Edit Cart" link not in alignment issue  

### ISSUE THREAD

**Issue by Dharmeshvaja91** [magento/magento2#27987]
### Preconditions (*)

1. Magento version 2.3.4 
2.

### Steps to reproduce (*)

1.Add product into cart 
2.click on mini cart button 

### Expected result (*)

1. "View and Edit Cart" link should be vertically aligned.  

2.
 ![minicart-fix](https://user-images.githubusercontent.com/43463281/80280248-8a775100-8720-11ea-880d-3cb2c50e350a.png)

### Actual result (*)

1. 
![minicart-issue](https://user-images.githubusercontent.com/43463281/80280279-b266b480-8720-11ea-8082-c18c6aa97c77.png)

2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33753` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by santosh-gaggle** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @santosh-gaggle. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by mrtuvn** [comment]
@Dharmeshvaja91 Issue seem has been fixed in PR https://github.com/magento/magento2/pull/27988

**Comment by AbdulRahmanAbouzaid** [comment]
@Dharmeshvaja91 Can you check @mrtuvn's [comment](https://github.com/magento/magento2/issues/27987#issuecomment-619478276) and approve the fix ?

**Comment by kishorenagalingam** [comment]
@magento i'm working on this

**Comment by madhurajawat** [comment]
@magento give me an instance

**Comment by madhurajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @madhurajawat. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by madhurajawat** [comment]
@magento i'm working on this

**Comment by madhurajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @madhurajawat. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91, @mrtuvn. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33753` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
