### ISSUE TITLE
Data migration tool issues

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#2798]
My issues in the data migration tool repo seem to get ignored and it's actually preventing me from doing much...

https://github.com/magento/data-migration-tool-ce/issues/31

https://github.com/magento/data-migration-tool-ce/issues/21

https://github.com/magento/data-migration-tool-ce/issues/32

https://github.com/magento/data-migration-tool-ce/issues/33

https://github.com/magento/data-migration-tool-ce/issues/37

**Comment by cscd98** [comment]
@ishakhsuvarov Any updates on this? Do I need to create these as separate issues here to be dealt with?

**Comment by ilol** [comment]
Hi @craigcarnell, we are working already. Thank you for your active position. Will keep you informed. Soon I will put internal bug tickets.

**Comment by cscd98** [comment]
Thank you. I have additional issues:

https://github.com/magento/data-migration-tool-ce/issues/34
https://github.com/magento/data-migration-tool-ce/issues/39

**Comment by cscd98** [comment]
@ilol When will you update the data-migration-tool?

**Comment by ilol** [comment]
This week, @craigcarnell.

**Comment by hws47a** [comment]
@ilol looking forward to this update

**Comment by hws47a** [comment]
Sorry @ilol, do you have updated info about a release date?

**Comment by ilol** [comment]
Hi, unfortunately I missed with date. Give us more one week.

**Comment by cscd98** [comment]
Can you have a look at?

https://github.com/magento/data-migration-tool/issues/26
