### ISSUE TITLE
EU VAT number validation not working

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#27998]
### Preconditions (*)

1. Magento 2.2.11
2.

### Steps to reproduce (*)

1. In the admin go to Stores -> Configurstion -> General -> General -> Store Information
2. Fill in a valid EU VAT-number (You can check at https://ec.europa.eu/taxation_customs/vies/)
3. Press "Validate VAT-number"

### Expected result (*)

Message that the VAT-number is valid

### Actual result (*)

Error message: Error during verification of the VAT number

**Comment by lbajsarowicz** [comment]
Already fixed #27886

**Comment by lbajsarowicz** [comment]
Already fixed #27886, you can apply patch to your code: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/27886.patch
