### ISSUE TITLE
GET - /rest/all/V1/carts/mine says customerId is required.

### ISSUE THREAD

**Issue by cruz94** [magento/magento2#27991]
### Preconditions (*)

Magento(2.3.4)

### Steps to reproduce (*)

GET : http://localhost/magento2/rest/all/V1/carts/mine
 gives an error 
"{
    "message": "\"%fieldName\" is required. Enter and try again.",
    "parameters": {
        "fieldName": "customerId"
    }
}"

### Expected result (*)

 It should provide the latest cart created by that user at least.

### Actual result (*)
 
![Screenshot from 2020-04-25 23-22-10](https://user-images.githubusercontent.com/17508899/80286892-c378eb00-874b-11ea-8555-a068acd9b42f.png)

**Comment by niravkrish** [comment]
hi @cruz94,

This is not an issue you used wrong URL.

may be your request URL is wrong.

Please check guide for getting request URL or endpoints.

you can try below URL.

GET : http://localhost/magento2/rest/all/V1/carts/mine // wrong
GET : http://localhost/magento2/rest/V1/carts/mine // right

you can get all rest api endpoint by below URL in your project.
http://magento_project.local/swagger

Thank you,
Nirav Patel
