### ISSUE TITLE
New Sales chart is wrong on the dashboard

### ISSUE THREAD

**Issue by ShelburneCountryStore** [magento/magento2#27995]
Since we updated to Magento 2.3.4 the new sales chart on the dashboard has been driving us crazy.
I know this is not the most pressing issue of our day, but it is like a mis-spelling that keeps showing up as mis-spelt.

Why does the chart show low sales as fractional sales?  If I have 1 sale at 5:00, the chart should show 1, but instead the chart shows 1.5 sales.  So is 3 sales 3@1per or 2@1.5 per?
![Sales-Chart](https://user-images.githubusercontent.com/4283803/80314862-1d1bfc80-87c2-11ea-9b7e-2ad16b7b42eb.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27995-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27995-2-4-develop.instances.magento-community.engineering/admin_7ccd](https://i-27995-2-4-develop.instances.magento-community.engineering/admin_7ccd)
Login: `dda54069` Password: `e7d50febd65c`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27995-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27995-2-4-develop.instances.magento-community.engineering/admin_b6dc](https://i-27995-2-4-develop.instances.magento-community.engineering/admin_b6dc)
Login: `9d741386` Password: `3355560ff913`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @ShelburneCountryStore 
I tried reproducing this issue at 2.4-develop instance but it seems the chart view is changed on 2.4-develop instance also it is showing correct quantity there 
![image](https://user-images.githubusercontent.com/25526037/80830831-51028200-8c07-11ea-8b7d-e434cf96bd17.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-27995-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27995-2-3-4.instances.magento-community.engineering/admin_f75d](https://i-27995-2-3-4.instances.magento-community.engineering/admin_f75d)
Login: `2bcc3d69` Password: `991792607e4f`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
but I got the same type issue at 2.3.4 instance 
![image](https://user-images.githubusercontent.com/25526037/80831851-27e2f100-8c09-11ea-998d-dd477585ad8c.png)

**Comment by engcom-Lima** [comment]
Hello @ShelburneCountryStore 
Unfortunately, I'm not able to reproduce issue by steps you described on 2.4-develop and 2.3.5-p1. 

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
