### ISSUE TITLE
Shipping/Payment page keeps showing spinner as if it's loading

### ISSUE THREAD

**Issue by aqdennis** [magento/magento2#27992]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.3

### Steps to reproduce (*)

1. In One Page Checkout follow checkout procedure
2. At both Shipping and Payment page the loading spinner remains, though checkout can be completed

### Expected result (*)

1. Payment page without loading spinner

### Actual result (*)

1. No error message, payment page functions. But spinner remains which users find confusing
![image](https://user-images.githubusercontent.com/48013601/80306218-2f963600-87c2-11ea-8ba1-f9ef5d133711.png)

**Comment by aqdennis** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @aqdennis. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aqdennis, here is your [Magento instance](https://i-27992-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27992-2-4-develop.instances.magento-community.engineering/admin_2245](https://i-27992-2-4-develop.instances.magento-community.engineering/admin_2245)
Login: `1ba1ccd8` Password: `f67bb14b1e73`
Instance will be terminated in up to 3 hours.

**Comment by aqdennis** [comment]
Can't reproduce it in the 2.4-develope branch. 
The loading spinner in this branch takes a long time to disapper (up to 30 seconds), but does disappear in the end.

**Comment by aqdennis** [comment]
Changed my own site to the bare minimum checkout : only Flat rate shipping and Money Order payment. But spinner remains. Hence, it doesn't seem to be in one of the third party shippers or PSPs.

**Comment by aqdennis** [comment]
Occasionally I even have 2 spinners (see below).  A refresh page makes the top left disappear again.

![image](https://user-images.githubusercontent.com/48013601/80306823-f2cc3e00-87c5-11ea-8e38-ed7080e929e0.png)

**Comment by aqdennis** [comment]
In de console I see the warning "Expected to start loader but did not find one in the dom" ,.... It sounds like that has something to do with it, but I don't know how....

**Comment by aqdennis** [comment]
Solved!
My theme overrides "onepage.phtml"  but has an incomplete checkout-loader <div>

`<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" >`

Changed it to 

`<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>`

And now spinning wheel disappears shortly after page is loaded.
