### ISSUE TITLE
Some bug in $product->load($id) method for some products

### ISSUE THREAD

**Issue by mantonuk** [magento/magento2#2800]
yoyo
The users can get error if store have attribute of product like 'stock_status'
"mysql> select \* from eav_attribute where attribute_id = 364;
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-----------------------------------+-------------+-----------------+---------------+-----------+------+
| attribute_id | entity_type_id | attribute_code | attribute_model | backend_model | backend_type | backend_table | frontend_model | frontend_input | frontend_label | frontend_class | source_model                      | is_required | is_user_defined | default_value | is_unique | note |
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-----------------------------------+-------------+-----------------+---------------+-----------+------+
|          364 |              4 | stock_status   | NULL            | NULL          | int          | NULL          | NULL           | select         | Stock Options  | NULL           | eav/entity_attribute_source_table |           0 |               1 |               |         0 |      |
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-----------------------------------+-------------+-----------------+---------------+-----------+------+
1 row in set (0.00 sec)"

**Comment by mantonuk** [comment]
var_dump($stockStatus); == option_id of dropdown

main.CRITICAL: exception 'Exception' with message 'Notice: Undefined variable: status in ---vendor/magento/module-catalog-inventory/Helper/Stock.php on line 86' in ---vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 ---vendor/magento/module-catalog-inventory/Helper/Stock.php(86): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined varia...', '/chroot/home/po...', 86, Array)
#1 ---vendor/magento/module-catalog-inventory/Observer/AddInventoryDataObserver.php(40): Magento\CatalogInventory\Helper\Stock->assignStatusToProduct(Object(Magento\Catalog\Model\Product\Interceptor), **'3676'**)
#2 ---vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\CatalogInventory\Observer\AddInventoryDataObserver->execute(Object(Magento\Framework\Event\Observer))
#3 ---vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogInventory\Observer\AddInventoryDataObserver), Object(Magento\Framework\Event\Observer))
#4 ---vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#5 ---var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
#6 ---vendor/magento/framework/Model/AbstractModel.php(561): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)

**Comment by le0n4eg** [comment]
Thanks for reporting this issue! Internal ticket MAGETWO-47431

**Comment by mslabko** [comment]
Hi @mantonuk,
the issue was fixed in  https://github.com/magento/magento2/commit/a831bd148f9f79014a77af3809c3ae09875aa2a6
Thank you for reporting.
