### ISSUE TITLE
Magento 2.2.6 customers excel export not working 

### ISSUE THREAD

**Issue by lnagys** [magento/magento2#28003]
### Preconditions (*)
<!---
1. version 2.2.6

### Steps to reproduce (*)
1. Login to Admin
2.Customers
3. Export
4. Select CSV or Excel XML
5. Export

### Expected result (*)
1. File exports

### Actual result (*)
1. Error is received

Error received= Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/store.smalley.com/htdocs/vendor/magento/framework/View/Element/UiComponentFactory.php on line 220 and defined in /var/www/store.smalley.com/htdocs/vendor/magento/framework/View/Element/UiComponentFactory.php:172 Stack trace: #0 /var/www/store.smalley.com/htdocs/vendor/magento/framework/View/Element/UiComponentFactory.php(220): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('b2b_activasion_...', NULL) #1 /var/www/store.smalley.com/htdocs/vendor/magento/module-ui/Component/Listing/Columns/Column.php(77): Magento\Framework\View\Element\UiComponentFactory->create('b2b_activasion_...', 'varchar', Array) #2 /var/www/store.smalley.com/htdocs/vendor/magento/module-ui/Component/MassAction/Filter.php(182): Magento\Ui\Component\Listing\Columns\Column->prepare() #3 /var/www/store.smalley.com/htdocs/vendor/magento/module-ui/Component in /var/www/store.smalley.com/htdocs/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172

**Comment by lbajsarowicz** [comment]
1. There is no description for the issue
2. Magento 2.2 is not supported anymore
