### ISSUE TITLE
Magento 2.3.3-p1: Error during VAT Number verification

### ISSUE THREAD

**Issue by mrkimmok** [magento/magento2#28008]
### Preconditions (*)

1. Magento Community Edition v. 2.3.3-p1
2. Updated from v.2.2.10 > 2.3.3 > 2.3.3-p1 (updated with composer installation method)

### Steps to reproduce (*)

1. From backend go to Store > Configuration > General > General > Store Information.
2. Try to validate a valid VAT Number by pressing the **Validate VAT Number** button

### Expected result (*)

1. VAT Number validation succeeds

### Actual result (*)

1. An error message "Error during VAT Number verification" is shown

**Comment by ambkimmok** [comment]
As a side note, here's a screenshot of the same VAT Number being validated straight from the VIES VAT number validation service:

![image](https://user-images.githubusercontent.com/54927315/80470949-6186d400-894b-11ea-9cf0-bba710a04830.png)

**Comment by krishprakash** [comment]
Already fixed #27886 , you can apply patch to your code: [https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/27886.patch](https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/27886.patch)

**Comment by Giuliano69** [comment]
Confirm the ERROR  in /app/code/Magento/Customer/Model/Vat.php
is still present ALSO in Magento ver. 2.3.5-p1 CE
Same fix works flawlessly.... 
(non only Magento 2.3.3-p1 as the subject)

Consider a mege of the PR in the master branch

**Comment by drinkingsouls** [comment]
Magento 2.4.3-p1
The fix is packaged into code but I still get "Error during VAT Number verification."
