### ISSUE TITLE
magento 2.3.3 payment pending status

### ISSUE THREAD

**Issue by deepakpant91** [magento/magento2#28006]
### Preconditions (*)

1. Magento version ( 2.3.3) 
2. Manual order creation from admin

### Steps to reproduce (*)

1. Go to orders and create and order and select any online payment method.
2. Then after creating order you can see there is no change option for order status rather then pending payment.

### Expected result (*)

1. Go to orders and create and order and select any online payment method.
2. Then after creating order you i want there will be all status listing to change order status.

### Actual result (*)

1. Go to orders and create and order and select any online payment method.
2. Then after creating order you can see there is no change option for order status rather then pending payment.Means there is only one option in order status that is pending payment but on order creation i choose net banking so then there will be other status options also,.

**Comment by Mohan2594** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594, here is your [Magento instance](https://i-28006-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28006-2-4-develop.instances.magento-community.engineering/admin_a7d3](https://i-28006-2-4-develop.instances.magento-community.engineering/admin_a7d3)
Login: `51335e70` Password: `673ccbad3a73`
Instance will be terminated in up to 3 hours.

**Comment by Mohan2594** [comment]
@deepakpant91 once an order is placed using check/money order or bank transfer payment the status is pending only and drop down does not lists any other options. But after generating invoice the status changes to processing and lists suspected fraud option as well in the drop down. After submitting shipment the status changes to complete. If an order placed using credit card or paypal the order status will be processing and cannot change status until or unless invoice or shipment is raised,this is how it works.

**Comment by Mohan2594** [comment]
issue not reproducible in 2.4.Once an order is placed using check/money order or bank transfer payment the status is pending only (not pending payment) and drop down does not lists any other options. But after generating invoice the status changes to processing and lists suspected fraud option as well in the drop down. After submitting shipment the status changes to complete. If an order placed using credit card or paypal the order status will be processing and cannot change status until or unless invoice or shipment is raised,this is how it works.

**Comment by Mohan2594** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594, here is your [Magento instance](https://i-28006-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28006-2-3-5-p1.instances.magento-community.engineering/admin_c0f7](https://i-28006-2-3-5-p1.instances.magento-community.engineering/admin_c0f7)
Login: `dc45aaee` Password: `70b0530a702c`
Instance will be terminated in up to 3 hours.

**Comment by Mohan2594** [comment]
![kh6EuFeSsh](https://user-images.githubusercontent.com/54931737/83745634-786fc300-a67b-11ea-9f8c-b34068d649a1.png)


same with 2.3.5-p1

**Comment by deepakpant91** [comment]
If ou choose any online payment option from admin then it is always shows
pending payment

**Comment by Mohan2594** [comment]
which online payment to be exact?

**Comment by deepakpant91** [comment]
If I create a order from admin using any online option .

**Comment by Mohan2594** [comment]
did u try paypal?

**Comment by deepakpant91** [comment]
No, I am using Paytm and razorpay.

**Comment by deepakpant91** [comment]
I have fixed the issue already.thank you for working in it.but there is
another problem with advance reporting.advance reporting goes to 404.

**Comment by Mohan2594** [comment]
ok,ticket#?

**Comment by deepakpant91** [comment]
I have not created any ticket for it but can you have any solution in it?

**Comment by adityag186** [comment]
Hi @deepakpant91  - Could you tell how you fixed order status problem. I created an order from admin panel with paytm gateway. I have invoiced the order but order status still says payment pending. I need to mark it as processing.

**Comment by shashank141097** [comment]
> ![PeVKoM2SCq](https://user-images.githubusercontent.com/54931737/83744394-b1a73380-a679-11ea-8e45-3d0bc0f466de.png)
> issue not reproducible in 2.4.Once an order is placed using check/money order or bank transfer payment the status is pending only (not pending payment) and drop down does not lists any other options. But after generating invoice the status changes to processing and lists suspected fraud option as well in the drop down. After submitting shipment the status changes to complete. If an order placed using credit card or paypal the order status will be processing and cannot change status until or unless invoice or shipment is raised,this is how it works.



> ![PeVKoM2SCq](https://user-images.githubusercontent.com/54931737/83744394-b1a73380-a679-11ea-8e45-3d0bc0f466de.png)
> issue not reproducible in 2.4.Once an order is placed using check/money order or bank transfer payment the status is pending only (not pending payment) and drop down does not lists any other options. But after generating invoice the status changes to processing and lists suspected fraud option as well in the drop down. After submitting shipment the status changes to complete. If an order placed using credit card or paypal the order status will be processing and cannot change status until or unless invoice or shipment is raised,this is how it works.

@Mohan2594 so how can we know that customer did payment or not? which order status informs that order's payment is successful?
