### ISSUE TITLE
Magento Layout cache contains unnecessary characters

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#28001]
### Preconditions (*)
It's more and more often reported that Magento misuse the caching mechanisms (too many requests, too much space used etc). I reviewed the requests that are being sent to REDIS and I'm not a Redis expert, but according to what I see on the screen - we cache not only the necessary XML data, but also the effect of "beautification" (formatting) of the XML output. I mean `\n` and whitespace:
```
1587994150.458175 [0 192.168.224.9:54290] "HMSET" "zc:k:792_LAYOUT_ADMINHTML_STORE1_32C857DA9AD039A9E5BA1A8DE0F556F19_PAGE_LAYOUT_MERGED" "d" "{\"pageLayout\":\"admin-1column\",\"layout\":\"<body>\\n   <referenceContainer name=\\\"after.body.start\\\">\\n      <block class=\\\"Magento\\\\Ui\\\\Block\\\\Wysiwyg\\\\ActiveEditor\\\" name=\\\"theme.active.editor\\\" template=\\\"Magento_Ui::wysiwyg\\/active_editor.phtml\\\"\\/>\\n   <\\/referenceContainer>\\n<\\/body>\\n<head>\\n   <title>Magento Admin<\\/title>\\n   <meta name=\\\"viewport\\\" content=\\\"width=1024\\\"\\/>\\n   <meta name=\\\"format-detection\\\" content=\\\"telephone=no\\\"\\/>\\n   <link src=\\\"requirejs\\/require.js\\\"\\/>\\n   <css src=\\\"extjs\\/resources\\/css\\/ext-all.css\\\"\\/>\\n   <css src=\\\"extjs\\/resources\\/css\\/ytheme-magento.css\\\"\\/>\\n<\\/head>\\n<body>\\n   <attribute name=\\\"id\\\" value=\\\"html-body\\\"\\/>\\n   <block name=\\\"require.js\\\" class=\\\"Magento\\\\Backend\\\\Block\\\\Page\\\\RequireJs\\\" template=\\\"Magento_Backend::page\\/js\\/require_js.phtml\\\"\\/>\\n   <referenceContainer name=\\\"global.notices\\\">\\n      <block class=\\\"Magento\\\\Backend\\\\Block\\\\Page\\\\Notices\\\" name=\\\"global_notices\\\" as=\\\"global_notices\\\" template=\\\"Magento_Backend::page\\/notices.phtml\\\"\\/>\\n   <\\/referenceContainer>\\n   <referenceContainer name=\\\"header\\\">\\n      <block class=\\\"Magento\\\\Backend\\\\Block\\\\Page\\\\Header\\\" name=\\\"logo\\\" before=\\\"-\\\">\\n         <arguments>\\n            <argument name=\\\"show_part\\\" xsi:type=\\\"string\\\">logo<\\/argument>\\n            <argument name=\\\"edition\\\" translate=\\\"true\\\" xsi:type=\\\"string\\\">Community Edition<\\/argument>\\n            
```

### Steps to reproduce (*)
1. `rediscli monitor | grep SET`
2. Watch the output, when saving CMS Page / CMS Block

### Expected result (*)
1. The XML output should be optimized to avoid redundant data.

### Actual result (*)
1. The XML output sent to Redis to keep in cache contains redundant whitespace / newlines.

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Install redis `Redis server v=6.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=371d6c175f084b2a`
- Configure redis for magento page and default cache
https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html
- Configure redis for session storage
https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html
- Run `rediscli monitor | grep SET`
- Save CMS Page or CMS Block


**Result:**
No new output in console when command `rediscli monitor | grep SET` was run

Is this issue still actual on 2.4-develop?

**Comment by lbajsarowicz** [comment]
I won't be able to review those. Let's close the issue as "Cannot reproduce" then.
