### ISSUE TITLE
Download link in order email shows incorrect escaped link

### ISSUE THREAD

**Issue by barryvdh** [magento/magento2#28014]
### Preconditions (*)
Magento 2.4-develop
Php 7.3

### Steps to reproduce (*)
1. Create a simple product with **File** customizable option;
![Screenshot from 2020-04-29 16-13-29](https://user-images.githubusercontent.com/51679138/80601195-290ff480-8a36-11ea-97fb-8a0202c1552a.png)

2. Go to Storefront;
3. Add created before the product to Cart;
![Screenshot from 2020-04-29 16-21-52](https://user-images.githubusercontent.com/51679138/80601314-52c91b80-8a36-11ea-873d-fd481fd86ed0.png)
4. Finish the order and look at the mail

### Expected result (*)

1. The mail provides a readable  link to the download

### Actual result (*)

:heavy_multiplication_x:  The attribute value is encodes, so it shows the raw HTML instead of a formatted link.
![screenshot_1](https://user-images.githubusercontent.com/51679138/80601469-886e0480-8a36-11ea-9ece-0db093abf0c0.png)

This was introduced by escaping the attribute value. A similar bug was encountered for the minicart. This is fixed by checking the type and then rendering it raw (see https://github.com/magento/magento2/pull/24237) . This should probably be done similarly for the emails.

This escaping happens here, but probably in more emails (credit, invoice etc): https://github.com/magento/magento2/blob/f442fa9a1f10cc566053e60ed6ae099a1664e61a/app/code/Magento/Sales/view/frontend/templates/email/items/order/default.phtml#L24
When the type is file, it should not escape.

**Comment by barryvdh** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @barryvdh. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @barryvdh, here is your [Magento instance](https://i-28014-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28014-2-4-develop.instances.magento-community.engineering/admin_0d6c](https://i-28014-2-4-develop.instances.magento-community.engineering/admin_0d6c)
Login: `b43882c3` Password: `d9cd71bcb265`
Instance will be terminated in up to 3 hours.

**Comment by barryvdh** [comment]
Thanks, I've submitted an order but don't receive any email. How can I test transactional emails with the test instance?

**Comment by engcom-Alfa** [comment]
The issue is reproducible on fresh 2.4-develop

**Manual testing scenario:**

1. Create a simple product with **File** customizable option;
![Screenshot from 2020-04-29 16-13-29](https://user-images.githubusercontent.com/51679138/80601195-290ff480-8a36-11ea-97fb-8a0202c1552a.png)

2. Go to Storefront;
3. Add created before the product to Cart;
![Screenshot from 2020-04-29 16-21-52](https://user-images.githubusercontent.com/51679138/80601314-52c91b80-8a36-11ea-873d-fd481fd86ed0.png)
4. Finish the order and look at the mail

**Actual Result:** :heavy_multiplication_x: shows the raw HTML instead of a formatted link
![screenshot_1](https://user-images.githubusercontent.com/51679138/80601469-886e0480-8a36-11ea-9ece-0db093abf0c0.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33840` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by niravkrish** [comment]
@magento I am working on it

**Comment by barryvdh** [comment]
Thank you. This issue is also present in the latest 2.2 and 2.3 releases, in case Magento is willing to fix older releases too.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
