### ISSUE TITLE
Fulltext search with double quote doesn't work well in the Backoffice grid

### ISSUE THREAD

**Issue by weiweiouyang** [magento/magento2#28016]
### Preconditions (*)
1. The bug is reproducible in Magento 2.4-develop, v2.3.4 and v2.2.11
2. It worked in Magento v2.2.2 and v2.2.4

### Steps to reproduce (*)
1. Go to the Backoffice Admin Panel
2. Go to grid Customers --> All Customers
3. In the fulltext search bar (with the placeholder : Search by keyword) type any existing email with **double-quote** for example "roni_cost@example.com"

### Expected result (*)
1. The customer with this exact email address shows in search results. (Magento v2.2.4)
![image](https://user-images.githubusercontent.com/9372525/80490107-2a232200-8961-11ea-9fc4-1b640b5ef9bb.png)

### Actual result (*)
1. No search has been found (Magento v2.3.4) with the same customer in the database.
![image](https://user-images.githubusercontent.com/9372525/80490059-1677bb80-8961-11ea-8cfb-657166e22ed6.png)

### Additional Information 
I found the changes from the commit history
https://github.com/magento/magento2/commit/01b546fe244246dbe033217918e4d0e6c294b2d2
https://github.com/magento/magento2/commit/a1776a267caf3911ee3e75b888b0ed0c07b359b5

la latest one made it impossible to search something using double quotes for a perfect match.
and it removes special characters in double-quotes as well.
Technically speaking, we SHOULD NOT change the words in the double-quotes to make sure the perfect match work as before.

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-28016-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28016-2-4-develop.instances.magento-community.engineering/admin_5a6c](https://i-28016-2-4-develop.instances.magento-community.engineering/admin_5a6c)
Login: `d9dc4164` Password: `e9584845cefe`
Instance will be terminated in up to 3 hours.

**Comment by weiweiouyang** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @weiweiouyang. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @weiweiouyang, here is your [Magento instance](https://i-28016-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28016-2-4-develop.instances.magento-community.engineering/admin_6d54](https://i-28016-2-4-develop.instances.magento-community.engineering/admin_6d54)
Login: `19d3b910` Password: `13f447c47f67`
Instance will be terminated in up to 3 hours.

**Comment by weiweiouyang** [comment]
> 
> 
> Hi @weiweiouyang. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [x]  Summary of the issue
> 
>     * [x]  Information on your environment
> 
>     * [x]  Steps to reproduce
> 
>     * [x]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @weiweiouyang do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [x]  yes
> 
>     * [ ]  no
> 
> 
>     * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @weiweiouyang. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @weiweiouyang, here is your [Magento instance](https://i-28016-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28016-2-4-develop.instances.magento-community.engineering/admin_d313](https://i-28016-2-4-develop.instances.magento-community.engineering/admin_d313)
Login: `d2661277` Password: `55091d3cd5f3`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33867` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @weiweiouyang 

After internal triage was decided 
Need to confirm the Expected result for this case with Product Manager responsible for this functionality

**Comment by weiweiouyang** [comment]
Hello @sdzhepa ,
Would you need my update for the excepted result or your Product Manager will be in charge of it?
I'm not sure to fully understand the previous message.

**Comment by sdzhepa** [comment]
Hello @weiweiouyang 

Sorry for the delays. No update from you required.
I wrote an email to Magento Product Manager who owns(responsible) this functionality.

still waiting for response

**Comment by weiweiouyang** [comment]
> 
> 
> Hello @weiweiouyang
> 
> Sorry for the delays. No update from you required.
> I wrote an email to Magento Product Manager who owns(responsible) this functionality.
> 
> still waiting for response

Good, thank you for your reply. Hoping that we get the feedback from the PM soon.

Best Regards,

**Comment by rmanor1** [comment]
Hi all, PM team here. We're discussing internally and will get an answer back here as soon as we can.

**Comment by sdzhepa** [comment]
Hello @rmanor1 

Do you have any updates?
Could you suggest Severity and Priority for this issue?

**Comment by rmanor1** [comment]
Sorry for delay, is it possible to split this issue? I would put higher (P2, next release) priority on the exact search issue as it currently returns nothing. And a lower (P3, future release) priority fix on the '+' operator splitting queries, since it returns the expected result (if not others as well).

**Comment by weiweiouyang** [comment]
@sdzhepa @rmanor1 Hello, thank you for your reply.
I've removed the part for '+' operator, so that we only have to fix the perfect match in this issue.
I'll open another issue for it later.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
