### ISSUE TITLE
Admin Customer Default Address Needs Break after Street

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#28023]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Login to Admin
2. Navigate to Customers -> All Customers
3. Add New Customer
4. Fill in Required Information
5. Save and Continue Edit
6. Navigate to Addresses Tab
7. Add New Address
8. Fill in Required Information and Select as Default Billing and Shipping Address
9. Save

### Expected result (*)

1. The Address information should be in a default format similar to rest of Magento
2. Example below:

ryan tegantvoort
company (if any)
123 test drive
city, Alabama, 12345
United States
T: 123-456-7890

### Actual result (*)

1. See Screenshot
![Annotation 2020-04-28 152053](https://user-images.githubusercontent.com/16922585/80539512-dca8b400-8964-11ea-84ed-ad9a5d3f059b.jpg)
2. Would require removing the comma after street and adding a break after street. 
3. If this is considered to be correct, feel free to close this issue I guess

**Comment by Vigneshmuthusamy** [comment]
We can achieve it using the configuration of Magento admin as shown below:
![Configuration   Settings   Stores   Magento Admin](https://user-images.githubusercontent.com/11820699/80563620-2f3bac00-8a09-11ea-9ef1-3424f78d16ef.png)
Goto Stores->Configuration -> CUSTOMERS -> Customer Configuration -> Address Templates

**Comment by trucatchtraps** [comment]
@Vigneshmuthusamy - Please explain which section, I had default settings still configured in Address Templates. And addresses look correct in all sections but the Customer Address tab in admin. According to the default settings in Address Templates section, there should be a break after the street

**Comment by trucatchtraps** [comment]
And looking at module-customer/view/adminhtml/web/template/default-address.html there should be a break after street as well.
Developer console information from address tab section in admin:
![Annotation 2020-04-29 083609](https://user-images.githubusercontent.com/16922585/80608769-82efca80-89f4-11ea-954e-dfbab22a6193.jpg)
Or at the very least a comma after the street I guess:
![Annotation 2020-04-29 083804](https://user-images.githubusercontent.com/16922585/80608950-c6e2cf80-89f4-11ea-9832-ef6102a2a483.jpg)

**Comment by Vigneshmuthusamy** [comment]
Ah sorry man, I misunderstood it. However, we cannot classify it as a bug, but you can contribute it as an improvement. Also make sure you handle it wherever it's referenced in admin like sales orders, invoices etc.,
