### ISSUE TITLE
System Upgrade Using Web Wizard

### ISSUE THREAD

**Issue by orbisunom** [magento/magento2#28025]
## Preconditions (*)
Magento 2.3.4 

## Steps to reproduce (*)
1. Click System - > Web Setup - > System Up
2. Follow the usual 4 step for upgrade

### Expected result (*)
1. Magento ver. 2.3.5 p1 (Admin Area Footer )

### Actual result (*)
1. Still Magento ver. 2.3.4 
![actual-image-not-change-234instead235p1](https://user-images.githubusercontent.com/16284743/80549688-7bc6bd80-89f0-11ea-84c9-c9ce616a98cc.PNG)

**Comment by engcom-Lima** [comment]
Hello @orbisunom 
Unfortunately, I'm not able to reproduce issue by steps you described. I use Php 7.3
 
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
