### ISSUE TITLE
Product is displayed as "in stock" for non logged in users when salable quantitiy is 0

### ISSUE THREAD

**Issue by achleitner** [magento/magento2#28024]
1. Magento 2.3.4

### Steps to reproduce (*)
1. Buy product via bank transfer which has salable quantitiy 1
2. Product should appear as out of stock for both logged in and non logged in users

### Expected result (*)
1. Product should appear as out of stock for both logged in and non logged in users

### Actual result (*)
1. Non logged in users are displayed the product as "in stock"
2. Logged in users are displayed the product as "out of stock"

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28024-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28024-2-4-develop.instances.magento-community.engineering/admin_430e](https://i-28024-2-4-develop.instances.magento-community.engineering/admin_430e)
Login: `a0b90463` Password: `cfe349d20033`
Instance will be terminated in up to 3 hours.

**Comment by achleitner** [comment]
Hello,
whatever happened to the "salable quantitiy"? Is it deprecated in Magento 2.4?

**Comment by engcom-Alfa** [comment]
Hi @achleitner  thank you for your report. This is [MSI](https://github.com/magento/inventory) related issue. 
Please refer to appropriate [repository](https://github.com/magento/inventory/issues) for further investigation
