### ISSUE TITLE
Sitemap generation in wrong folder when vhost is connected to pub folder

### ISSUE THREAD

**Issue by jasperzeinstra** [magento/magento2#2802]
In my case my domain (vhost) is connected to the pub folder instead of the root folder, for security reasons. Now when I try to generate a sitemap.xml in te root of the url. www.mydomain.com/sitemap.xml I need to fill in `/` as path. But the sitemap is created in the root folder now, instead of the pub folder. And when I set `/pub/` as my path I get the URL www.mydomain.com/pub/sitemap.xml returned in the backend. This is an incorrect URL.

**Comment by antboiko** [comment]
Hi @jasperzeinstra Thanks for reporting this issue. We've created an internal ticket MAGETWO-47607 to process it.

**Comment by navarr** [comment]
A good work around for this would be to create a symbolic link pointing to the root sitemap.xml from pub, but if you are creating multiple sitemaps that will get unwieldy fast.

**Comment by hostep** [comment]
Duplicate - https://github.com/magento/magento2/issues/1146

**Comment by okorshenko** [comment]
Fixed in #9094

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67054
