### ISSUE TITLE
Some of magento/module-* are outdated after run composer update

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#28037]
### Preconditions (*)
PHP: 7.3.17
Composer version: 1.10.5
"magento/product-enterprise-edition": "2.3.5-p1"

### Steps to reproduce (*)
run commands

1. composer update (to download latest versions of all vendors)
2. composer outdated

### Expected result (*)
no outdated magento/module-*

### Actual result (*)
```
[...]
magento/module-advanced-sales-rule         100.3.4 100.3.4-p2 N/A
magento/module-advanced-search             100.3.4 100.3.4-p2 N/A
magento/module-authorization               100.3.4 100.3.4-p2 Authorization module provides access to Magento ACL functionality.
magento/module-bundle-staging              100.3.4 100.3.4-p2 N/A
magento/module-catalog-inventory-staging   100.3.4 100.3.4-p2 N/A
magento/module-catalog-permissions         100.3.4 100.3.4-p2 N/A
magento/module-catalog-url-rewrite-staging 100.3.4 100.3.4-p2 N/A
magento/module-checkout-staging            100.3.4 100.3.4-p2 N/A
magento/module-cms-staging                 100.3.4 100.3.4-p2 N/A
magento/module-downloadable-staging        100.3.4 100.3.4-p2 N/A
magento/module-gift-card-staging           100.3.4 100.3.4-p2 N/A
magento/module-gift-message                100.3.4 100.3.4-p2 N/A
magento/module-google-optimizer            100.3.4 100.3.4-p2 N/A
magento/module-message-queue               100.3.4 100.3.4-p2 N/A
magento/module-mysql-mq                    100.3.4 100.3.4-p2 N/A
magento/module-new-relic-reporting         100.3.4 100.3.4-p2 N/A
magento/module-release-notification        100.3.4 100.3.4-p2 N/A
magento/module-reminder                    101.1.4 101.1.4-p2 N/A
magento/module-reward-staging              100.3.4 100.3.4-p2 N/A
magento/module-sales-rule-staging          100.3.4 100.3.4-p2 N/A
magento/module-sales-sequence              100.3.4 100.3.4-p2 N/A
magento/module-scalable-inventory          100.3.4 100.3.4-p2 N/A
magento/module-scheduled-import-export     101.1.4 101.1.4-p2 N/A
magento/module-send-friend                 100.3.4 100.3.4-p2 N/A
magento/module-support                     101.1.4 101.1.4-p2 N/A
magento/module-variable                    100.3.4 100.3.4-p2 N/A
magento/module-weee-staging                100.3.4 100.3.4-p2 N/A
magento/module-widget                      101.1.4 101.1.4-p2 N/A
[...]
```

**Comment by hostep** [comment]
Hmm good point indeed!

I [noticed](https://magentocommeng.slack.com/archives/CANPJTBC5/p1587125756040900) during the 2.3.4-p1 pre-release period that they updated some modules with newer versions which wasn't necessary because the modules contained zero changes. I assume they did the same for 2.3.4-p2 but then didn't do it for 2.3.5 or 2.3.5-p1.

This is very confusing indeed!

**Comment by rvitaliy** [comment]
yes, but it's strange that compose don't pull latest tag.
example if i do: `composer why magento/module-advanced-sales-rule` output is
```
magento/module-sales-rule-staging   100.3.4   requires  magento/module-advanced-sales-rule (100.3.*)  
magento/product-enterprise-edition  2.3.5-p1  requires  magento/module-advanced-sales-rule (100.3.4)
```

so the problem is that `magento/product-enterprise-edition  2.3.5-p1` require exactly `magento/module-advanced-sales-rule (100.3.4)` i think that to fix this we must change require to `100.3.*` or in `100.3.4|100.3.4-p1|100.3.4-p2` or if other tags is not supported to `100.3.4-p2`

**Comment by nathanjosiah** [comment]
Yes, `2.3.5-p1` does require strict versioning:

```
"magento/module-sales-rule-staging": "100.3.4",
```

**Comment by nathanjosiah** [comment]
Hello @rvitality! Thank you for opening, we are investigating this.

**Comment by ihor-sviziev** [comment]
Issue is reproducible, but it's not related to dev. version, issue inside release.

**Comment by engcom-Delta** [comment]
@rvitaliy @ihor-sviziev I check issue on latest composer version 2.4.1 and it is not reproducible: no magento modules is shown in outdated list

If you'd like to update the issue, please reopen it.
