### ISSUE TITLE
The variables of the mails appear as [object object] in the section of creating templates of the mails

### ISSUE THREAD

**Issue by Hanhan1989** [magento/magento2#28038]
### Preconditions (*)

1. Magento 2.3.4
2. Linux
3. Php: 7.3
4. Apache: 2.4
5. Mysql: 5.7

### Steps to reproduce (*)

1. Go to the admin
2. Go to Marketing > Email Templates 
3. Click Add New Templates
4. Click Insert Variable

### Expected result (*)

The variables should appear

### Actual result (*)

1. Result in the admin 
![object-object](https://user-images.githubusercontent.com/11807165/80587302-96139200-8a16-11ea-8e24-bf362829aa18.png)
2. Result in the console debugger
File: vendor/magento/module-variable/view/adminhtml/web/variables.js
The html variable contains objects. I think it should contain string type values
![error_mail](https://user-images.githubusercontent.com/11807165/80587310-9ca20980-8a16-11ea-8c39-b5fe8ea43616.png)

**Comment by Hanhan1989** [comment]
It's solved.  The problem is that we added <update handle="editor"/>. For this reason, two urls appear (variables.js). Each one belongs to different modules
1. Magento_Variable
2. Magento_Email

In the section of creating new templates, the file variables.js of the Magento_Email module is used.
If the Magento_Variable module file also appears, it steps on it. That is why it gives error.

The change of using variables.js of the module Magento_Email was made in this commit

![image](https://user-images.githubusercontent.com/11807165/80650056-7494c380-8a73-11ea-9db6-40d3d656dd73.png)

![image](https://user-images.githubusercontent.com/11807165/80650017-5d55d600-8a73-11ea-8f5d-54892342caa4.png)

**Comment by Perzonallica** [comment]
@Hanhan1989 Hi!

Unfortunately this issue is still present in version **2.3.5-p1**. I have the _"Magento_Email/js/variables"_ line in the "edit.phtml", but doesn't seems to be helpful.

What is more interesting, that if I run a setup:upgrade, di:compile and I reload the email template admin page, then on **first try**, the variables are there, with no problem. After that, I go back to Dashboard and I open the _Marketing->Email Templates->Add new Template_ page, and the variable selector modal throws only [object Object],[object Object]... errors.

**Comment by actionis** [comment]
I'm experiencing this issue still in 2.3.5-p1.

**Comment by drinkingsouls** [comment]
Same issue in 2.4.1.
Insert variable reads:
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

**Comment by Martin-DAN** [comment]
Experiencing this issue also in 2.4.5-p1.

**Comment by drinkingsouls** [comment]
I'm still experiencing this 2 years on from my last comment. 
Magento 2.4.4-p2

**Comment by drinkingsouls** [comment]
Was there any solution for this?
I have the "Magento_Email/js/variables" line in the "edit.phtml" but it still doesn't function correctly.
As @Perzonallica said, when I run setup:upgrade, di:compile and I reload the email template admin page, then on first try, the variables are there. After that they return to [object Object]
