### ISSUE TITLE
Translate Magento 2 using Translate Inline Tool, Checkout process doesn't finish

### ISSUE THREAD

**Issue by SistemasTroyStone** [magento/magento2#28046]
### Steps to reproduce (*)
When I try to continue with the purchase process, I fill in all the necessary fields but never proceed in view of the checkout / success.
1. Translate Inline - Enabled for Storefront.
2. I try to continue with the purchase process

### Expected result (*)
I got the next issue:
1.
![image](https://user-images.githubusercontent.com/55449744/80619060-c6a0ff00-8a09-11ea-8f31-1bf3837c4999.png)

### Actual result (*)
1.even though the process apparently does not complete, the order does register successfully. but I can't access the checkout to create a different view with more information and policies that I need.

**Comment by engcom-Delta** [comment]
Hi @SistemasTroyStone  I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Enable developer mode
- Set Translate Inline according [docs](https://docs.magento.com/user-guide/system/translate-inline.html)
- Go to storefront
- Add product to cart
- Place order

**Result:**
:heavy_check_mark: Order is placed without errors
![Screenshot from 2020-11-27 14-57-22](https://user-images.githubusercontent.com/51681379/100451954-eb08ab00-30c0-11eb-972f-0764d980e9fd.png)
![Screenshot from 2020-11-27 14-51-52](https://user-images.githubusercontent.com/51681379/100451968-ef34c880-30c0-11eb-8d34-fab3d98ab224.png)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
