### ISSUE TITLE
Can not create a new attribute

### ISSUE THREAD

**Issue by SteveBench** [magento/magento2#2804]
I installed magento 2 using composer taking the code from the magento2 github page. I then used the migration tool to bring my attributes across from my magento 1 store.

I can not now create attributes. When I try and save a new attribute I get the following error:

Class Magento\Indexer\Model\IndexerRegistry does not exis

I'm running this locally using wamp.

Any help would be appreciated.

Thanks

**Comment by vzabaznov** [comment]
Hi @SteveBench 
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.
And try to check folder permission to var in magento root

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
