### ISSUE TITLE
Magento 2.3.4 Wrong Tax Calculation

### ISSUE THREAD

**Issue by mrixwan-407** [magento/magento2#28057]
### Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)
1-On the Admin Panel, Stores > Tax Zones and Rates. Create a Tax Zone and Rate
 create tax zone and enter tax percentage amount. 
2- On the Admin panel, Stores > Tax  Rules> Product Tax Classes.
    Hit the Add New button and create a  VAT Standard class:
    Add Tax Zone and rate class in Tax Rule
3-Add Tax Class to products in Catalog.
4- Go to Stores -> Configuration ->Sale -> Tax
    Select Tax Class and Enable for cart with 
    Set up Tax Calculation
![Screenshot_2020-04-30 Configuration Settings Stores Magento Admin](https://user-images.githubusercontent.com/28755232/80690819-6cbf3880-8ae0-11ea-8723-12646e3a8701.png)

### Expected result (*)

1. I set 5% tax and the expected result should be 
5 % of row total but giving a static nubmer in tax 
2. this is magento 2.1 with same configuration
![Screenshot_2020-04-30 Shopping Cart](https://user-images.githubusercontent.com/28755232/80691441-4fd73500-8ae1-11ea-9db9-f562e6315d4e.png)

### Actual result (*)

1.On Cart Page magento 2.3.4
2.
![Screenshot_2020-04-30 Shopping Cart(1)](https://user-images.githubusercontent.com/28755232/80691840-d9870280-8ae1-11ea-8858-cafafc2401f7.png)

**Comment by mrixwan-407** [comment]
yes

**Comment by mrixwan-407** [comment]
@magento give me 2.3.4 instance
--

**Comment by magento-engcom-team** [comment]
Hi @mrixwan-407. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mrixwan-407, here is your [Magento instance](https://i-28057-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-28057-2-3-4.instances.magento-community.engineering/admin_2e01](https://i-28057-2-3-4.instances.magento-community.engineering/admin_2e01)
Login: `75f8384a` Password: `8f04280b2316`
Instance will be terminated in up to 3 hours.

**Comment by mrixwan-407** [comment]
@magento-engcom-team I did Not produce issue on  vanilla Magento instance . Actually I upgraded magento2.1 to Magento 2.3.4 so its giving issue due to invalid data. I fixed it just delete all tax rules and classes and create fresh Tax rules and classes which are working correctly.
