### ISSUE TITLE
set and read product attributes

### ISSUE THREAD

**Issue by fohnbit** [magento/magento2#28056]
Hello,

I try to write, update and read product attributes and faced in some problems

### Preconditions (*)
Magento 2.3.5-p1 (updated from 2.3.3)

### Steps to reproduce (*)
1. POST to https://comp.com/rest/V1/products/attributes/
payload:
`{
    "attribute": {
        "is_wysiwyg_enabled": false,
        "is_html_allowed_on_front": true,
        "used_for_sort_by": true,
        "is_filterable": true,
        "is_filterable_in_search": true,
        "is_used_in_grid": true,
        "is_visible_in_grid": true,
        "is_filterable_in_grid": true,
        "position": 100,
        "apply_to": [],
        "is_searchable": "1",
        "is_visible_in_advanced_search": "0",
        "is_comparable": "1",
        "is_used_for_promo_rules": "0",
        "is_visible_on_front": "1",
        "used_in_product_listing": "1",
        "is_visible": true,
        "scope": "global",
        "attribute_code": "test_specs",
        "frontend_input": "swatch_text",
        "entity_type_id": "4",
        "is_required": false,
        "options": [
            {
                "label": "2 cm (Admin)",
                "value": "2cm",
                "sort_order": 2,
                "is_default": false,
                "store_labels": [
                    {
                        "store_id": 1,
                        "label": "2 cm (Store 1)"
                    },
                    {
                        "store_id": 2,
                        "label": "2 cm (Store 2)"
                    }
                ]
            }
        ],
        "is_user_defined": true,
        "default_frontend_label": "Test Specs",
        "frontend_labels": [
            {
                "label": "Test Specs",
                "store_id": 0
            }
        ],
        "backend_type": "int",
        "source_model": "Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table",
        "is_unique": "1",
        "validation_rules": []
    }
}`

### Expected result (*)
Add a text swatch attribute with one option

### Actual result (*)
I get the text swatch, but the swatch fields are empty and not able to add more options via API, before save it again in admin:
![image](https://user-images.githubusercontent.com/5511404/80683255-3bd10a80-8ac4-11ea-9f4a-e543e3653657.png)

### When I add a new option
https://comp.com/rest/V1/products/attributes/test_specs/options
payload:
{
    "option": {
        "label": "red",
        "value": "red_default",
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "red en"
            },
            {
                "store_id": 2,
                "label": "red de"
            }
        ]
    }
}

**I get the error:**
{
    "message": "Das Attribut \"%1\" funktioniert nicht mit Optionen.",
    "parameters": [
        "test_specs"
    ]
}

### Workaround for the second issue
I open in admin the attribute and only save it, without any changes .. then I can run the POST command above again and then its working and add a new swatch option.
I get an ID back:
![image](https://user-images.githubusercontent.com/5511404/80683729-efd29580-8ac4-11ea-8422-194bf3348466.png)

But when I read the attribute, I get only the ID and not the swatch text:
https://comp.com/rest/V1/products/attributes/test_specs/options
result:
[
    {
        "label": " ",
        "value": ""
    },
    {
        "label": "red en",
        "value": "5489"
    },
    {
        "label": "2 cm (Store 1)",
        "value": "5488"
    }
]

So how can Ii get from ID 5489 the swatch text "red_default"

**Comment by fohnbit** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fohnbit. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fohnbit, here is your [Magento instance](https://i-28056-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28056-2-4-develop.instances.magento-community.engineering/admin_6ae5](https://i-28056-2-4-develop.instances.magento-community.engineering/admin_6ae5)
Login: `ea0eeec4` Password: `4e355a9bd252`
Instance will be terminated in up to 3 hours.

**Comment by fohnbit** [comment]
I can confirm the issue on vanilla Magento instance:
after create the text swatch:
![image](https://user-images.githubusercontent.com/5511404/80685244-2c06f580-8ac7-11ea-98bc-77657fdaf692.png)

after creating, add a new option via API:
{
    "message": "The \"%1\" attribute can't be saved.",
    "parameters": [
        "test_specs"
    ]
}

This is not possible ... in 2.3.5-p1 I could add more text swatches
