### ISSUE TITLE
Fixed Price Bundle Products taxed incorrectly under certain circumstances

### ISSUE THREAD

**Issue by navarr** [magento/magento2#28051]
### Preconditions (*)
1. Magento 2.4
2. Vertex not installed
3. entire state of PA configured to be 6% taxable
4. Customer "Bob Saget" with address:
    525 N Allen St
    State College, PA 16803-3503
    USA
    (any phone number)
5. Incl/Excl tax display enabled for all fields
6. "Apply Tax On" configured to "Original price only"

### Steps to reproduce (*)
1. Create a bundle product
2. Set dyanmic price to No
3. Set price to $61
4. Create a required radio option w/ a price of 23 and quantity of 1
5. Create a required radio option w/ a price of 5 and quantity of 1
6. Save bundle product
7. Go to create new order in admin
8. Select Bob Saget as customer
9. Add fixed bundle product to order, configured with 1 of each required option and total quantity 3
10. "Add selected products to order"
11. Select fixed shipping method

### Expected result (*)

1. Order Grid:
    Price Excl Tax: $89
    Price Incl Tax: $94.34
    Subtotal Excl Tax: $267
    Subtotal Incl Tax: $283.02
2. Order Totals
    Subtotal Excl Tax: $267
    Subtotal Incl Tax: $283.02
    Tax: $16.02

### Actual result (*)

1. Order Grid:
    Price Incl Tax: $92.66
    Subtotal Incl Tax: $277.98
2. Order Totals:
    Subtotal Incl Tax: $277.98
    Tax: $10.98

**Comment by engcom-Delta** [comment]
Hi @navarr thank you for your report. Seems like result described in Actual result is not issue, but it is expected result
**Manual testing scenario:**

- Create tax rate for PA state  to 6% and add it to tax rule
![image](https://user-images.githubusercontent.com/51681379/98243433-9c129e80-1f76-11eb-8964-04d011c5426d.png) 

- Customer "John Doe" with address:
- - 525 N Allen St
- - State College, PA 16803-3503
- - USA
- - (any phone number)
- Incl/Excl tax display enabled for next fields:
![image](https://user-images.githubusercontent.com/51681379/98243536-c2d0d500-1f76-11eb-8756-3bc6af37074d.png)
![image](https://user-images.githubusercontent.com/51681379/98243620-de3be000-1f76-11eb-9c7b-b8d06d5b3abd.png)
- "Apply Tax On" configured to "Original price only"
- Create a bundle product
- Set dynamic price to No
- Set price to $61
- Create a required radio option price of 23 and quantity of 1
- Create a required radio option price of 5 and quantity of 1
![image](https://user-images.githubusercontent.com/51681379/98243844-3246c480-1f77-11eb-839e-46f96946a262.png)
![image](https://user-images.githubusercontent.com/51681379/98243877-3e328680-1f77-11eb-8a22-f7d22b945ef6.png)
- Save bundle product
- Go to create new order in admin
- Select John Doe as customer
- Add fixed bundle product to order, configured with 1 of each required option and total quantity 3
- "Add selected products to order"
- Select fixed shipping method

**Result:**
:heavy_check_mark: Bundle price is correct as tax is 61*0.06 = 3.66:
Excl. Tax: $89.00 (61+23+5)
Incl. Tax: $92.66 (61+23+5+3.66)
:heavy_check_mark: Subtotal is correct as tax for 3 bundle product is 3.66*3=10.98:
Excl. Tax: $267.00 (61+25+5)*3
Incl. Tax: $277.98 (61+25+5)*3 + (3*3.66)
![image](https://user-images.githubusercontent.com/51681379/98245025-00366200-1f79-11eb-890b-a719e18edfd8.png)
:heavy_check_mark: Order Totals are correct:
Subtotal (Excl. Tax) $267.00
Subtotal (Incl. Tax) $277.98
Grand Total $292.98
![image](https://user-images.githubusercontent.com/51681379/98245249-50adbf80-1f79-11eb-92e1-7aaf026ec11e.png)

Could you clarify why such result is not expected(wrong)?

**Comment by navarr** [comment]
@engcom-Delta: The expectation is that the original price includes the bundle options, the original price being the price the product was before/without a custom price set on it.

So instead of expecting a tax of $3.66, the expectation would be a tax of $5.34

**Comment by engcom-Delta** [comment]
@navarr I could get price and tax you expect to see when "Apply Tax On" configured to`Custom Price if available`
![image](https://user-images.githubusercontent.com/51681379/98386860-62669400-2059-11eb-9696-63fab328a43c.png)
![image](https://user-images.githubusercontent.com/51681379/98386901-701c1980-2059-11eb-95ee-69cd93d959af.png)

When "Apply Tax On" configured to `Original price only`, tax is applied only for bundle price and bundle option's prices are ignored that seems like expected behavior

**Comment by navarr** [comment]
@engcom-Delta If that expectation is correct, than there is no issue.  That was not my expectation.

My expectation would be that configured options are part of the "original price" and that the "custom price" is specifically a custom price provided by an admin in the admin panel.

**Comment by navarr** [comment]
This issue is blocked by a definitive answer to the question above.

**Comment by navarr** [comment]
Blocked awaiting response form Magento

**Comment by engcom-Delta** [comment]
@magento give me magento 2.4 instance

**Comment by engcom-Delta** [comment]
@magento give me magento 2.4  Develop instance

**Comment by engcom-Delta** [comment]
Hi @navarr ,

Issue is not reproducible in Magento 2.4 Develop. Hence closed.

**Comment by navarr** [comment]
@magento give me magento 2.4 instance

**Comment by navarr** [comment]
@magento give me 2.4-develop instance

**Comment by navarr** [comment]
@engcom-Delta This is still reproducible as described in the initial ticket.

**Comment by engcom-Delta** [comment]
Hi @navarr,
Verified this issue on Magento 2.4 Develop latest branch. getting different error while "Add selected products to order" at step # 11.
Kindly request to confirm the error displayed.
![Error got](https://user-images.githubusercontent.com/51681379/139536163-8255c04f-11b6-4192-b341-1fdb436f0dd6.JPG)
![ApplyTaxon_precondition](https://user-images.githubusercontent.com/51681379/139536168-f57daf1d-4a89-4938-ac3f-217b9962319e.JPG)
![Bundle_productCreated](https://user-images.githubusercontent.com/51681379/139536174-79789aaa-fc85-4878-94a4-b5f60adb6989.JPG)
![quantity_3](https://user-images.githubusercontent.com/51681379/139536183-46b16827-bba7-4242-8efa-3c40f78efd0a.JPG)
![OrderTotal](https://user-images.githubusercontent.com/51681379/139536188-9f645eb1-ddfa-4871-9f44-1d56caeb1865.JPG)
![OrderTotal](https://user-images.githubusercontent.com/51681379/139536194-63d85d53-d161-4392-b580-75fea2b895dd.JPG)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
