### ISSUE TITLE
Eliminate plugins for ActionInterface in Framework

### ISSUE THREAD

**Issue by buskamuza** [magento/magento2#28050]
### Summary (*)
Magento 2.4-develop
Eliminate plugins for `\Magento\Framework\App\ActionInterface` under `lib/internal/Magento/Framework/App/Action/Plugin`
Reason: plugins should be used to customize behavior of one module from another module. In this case, plugins that belong to Framework customize class behavior of the same Framework.

### Examples (*)

The problem is in the code and execution flow being more complex than it could be.

### Proposed solution

It is suggested to add desired behavior directly to the place where it's expected to execute. Consider `\Magento\Framework\App\FrontController::dispatch()` part of the framework as the place to inject necessary behavior.

**Comment by lbajsarowicz** [comment]
There are still Plugins in Framework namespace.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40313` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
