### ISSUE TITLE
Showing only one price option for price filter on category page

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#28060]
### Summary (*)

price filter not showing more option on the category page, it shows only single value.
I am using Magento 2.3.5 
### Examples (*)

![ttt](https://user-images.githubusercontent.com/2478037/80706357-cf76fb00-8b05-11ea-96fa-667305d2c2bb.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-28060-2-3-5.instances.magento-community.engineering).
Admin access: [https://i-28060-2-3-5.instances.magento-community.engineering/admin_3b8a](https://i-28060-2-3-5.instances.magento-community.engineering/admin_3b8a)
Login: `da36fd22` Password: `7394a57563e0`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @hemendraajmera 
I checked this issue at 2.3.5 instance but not able to reproduce this issue. 
Please check 
![image](https://user-images.githubusercontent.com/25526037/80829028-fae00f80-8c03-11ea-9b49-d11afa69eb2c.png)
