### ISSUE TITLE
Magento2 Export not working 

### ISSUE THREAD

**Issue by udittakwani** [magento/magento2#28067]
### Preconditions (*)

1.Magento version 2.3.5-p1 
2.Having More than 2.5 lakhs products

### Steps to reproduce (*)

1.Exporting the product using magneto export function
2.It is showing "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file"

### Expected result (*)

1. After run Cron command from CLI it should show CSV for download
2.

### Actual result (*)

1. Nothing is happening  table i showing blank only 
2.I checked var folder also it is blank 

I ran php bin-magento cron:run & also php bin/magento queue:consumers:start exportProcessor but no result is obtained

**Comment by udittakwani** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @udittakwani. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @udittakwani, here is your [Magento instance](https://i-28067-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28067-2-4-develop.instances.magento-community.engineering/admin_e400](https://i-28067-2-4-develop.instances.magento-community.engineering/admin_e400)
Login: `7ec92e71` Password: `6344cf73249b`
Instance will be terminated in up to 3 hours.

**Comment by udittakwani** [comment]
I am new to all this thing i tried exporting the csv using the magneto instance provided btu how can i run cron for it since i am not able to see it exported on that page

**Comment by engcom-Delta** [comment]
Hi @udittakwani thank you for your report, I'm not able to reproduce issue on clean 2.4-develop.
**Steps to reproduce:**

- Generate some products
- Install cron: `php bin/magento cron:install`
- Go to System->Export
- Choose Entity Type=Products
- Click Continue button

**Result:**
:heavy_check_mark: File with exported products is shown in grid
![Peek 2020-05-12 14-57](https://user-images.githubusercontent.com/51681379/81688141-1815a900-9462-11ea-89af-8b931ae452f1.gif)

If you'd like to update the issue, please reopen it.

**Comment by abude** [comment]
This is still not working on 2.3.5-p1 

running the consumer command doesn't fix it and i see no way now to force it to create the export file.

Any updates on this?

**Comment by dukir** [comment]
2.3.5-p2 the issue still exists.
Already tried to run cron:run\install & queue:consumers:start exportProcessor with no results... Any ideas?

**Comment by udittakwani** [comment]
Still not working in 2.4.1 any help?

**Comment by TheZyppi** [comment]
Sorry do i miss understood everything here? Is it true that product export doesn't work since version 2.3.5 ?
And no one think this is a major bug?!

**Comment by jigar48** [comment]
Not working on Magento 2.4.1

**Comment by nathanjosiah** [comment]
@magento give me 2.3.5 instance

**Comment by hunainaslam** [comment]
@magento has this issue fixed in 2.3.6? I'm still facing this issue? Thanks

**Comment by hostep** [comment]
@hunainaslam: this has never been a bug as far as I know. It's most likely that your installation is somehow not able to run the the `exportProcessor` consumer that is responsible for handling the export.

This consumer gets started up via one of the cronjobs in Magento, so make sure the `bin/magento cron:run` executes every minute.
If that doesn't help, then check your `app/etc/env.php` file and see if `cron_consumers_runner` is defined, if it isn't, then all is good, if it is defined, then make sure that `cron_run` is set to `true` and also that the `consumers` array is either empty or has at least the `exportProcessor` consumer defined.
More info about this configuration section can be found in [the documentation](https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html#configuration).

If this still doesn't help, then I would advise you to go searching for help on https://magento.stackexchange.com/ or https://community.magento.com/

Good luck! 🙂
