### ISSUE TITLE
Getting issue if a simple product already added in cart and making that configurable product from back-end and proceed for checkout to that added product.

### ISSUE THREAD

**Issue by webkul-dhananjay** [magento/magento2#28071]
### Preconditions (*)

- Magento 2.4.0
- Magento version 2.3.5p1
- Php- 7.3.14
- Simple product is created

### Steps to reproduce (*)

1. Add the previously created simple product to cart
2. Click on the "Proceed to Checkout" button via mini-cart
3. Wait until "Shipping Address" page loaded
4. Go to Admin Panel and open the simple product for editing  
5. Add configurations to the product (type of the product will change to configurable)
6. Save the product and flush all caches
7. Go back to the "Shipping Address" page on the store view
8. Reload the page

### Expected result (*)
Error message "Product is not available" or so

### Actual result (*)
Product isn`t remove from cart
Showing page with text - "Estimate Shipping and Tax"
![2020-06-30 13-54](https://user-images.githubusercontent.com/60198022/86118684-de643480-bad9-11ea-9f5c-5654a777ded2.gif)

---------------------------------------------
![screenshot_52](https://user-images.githubusercontent.com/50043146/80815812-f0b21700-8beb-11ea-9ebb-a526493723f1.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-28071-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28071-2-4-develop.instances.magento-community.engineering/admin_6bcc](https://i-28071-2-4-develop.instances.magento-community.engineering/admin_6bcc)
Login: `f62a9dd1` Password: `085d48080eca`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33934` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima, here is your [Magento instance](https://i-28071-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28071-2-4-develop.instances.magento-community.engineering/admin_85c6](https://i-28071-2-4-develop.instances.magento-community.engineering/admin_85c6)
Login: `2756835f` Password: `93c28135c334`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Lima** [comment]
@magento give me 2.3.5-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima. Thank you for your request. I'm working on Magento 2.3.5-develop instance for you

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-33934).

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
