### ISSUE TITLE
Magento 2.3.5-p1 Free shipping method does not count digital amount

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#28076]
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Make shipping method Free Shipping with minimum order amount 50
2. Make product that use decimals and is 12,95 per unit
3. Order 4,5 of it

### Expected result (*)

1. Free shipping has to be vissible in cart and checkout

### Actual result (*)

1. Free shipping is not visible
2. When amount is 5 the method is vissible

**Comment by Jilco** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-28076-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28076-2-3-5-p1.instances.magento-community.engineering/admin_07ef](https://i-28076-2-3-5-p1.instances.magento-community.engineering/admin_07ef)
Login: `08678882` Password: `aee91cb02cdf`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
Reproduced

![Order-amount](https://user-images.githubusercontent.com/23727130/80858140-a6ff1600-8c57-11ea-8cad-49f0f35f0eb9.jpg)
![no-free-shipping](https://user-images.githubusercontent.com/23727130/80858144-ac5c6080-8c57-11ea-8ca1-4dbcdd16debd.jpg)

**Comment by Jilco** [comment]
Figured out that it does not calculates the tax in the shipping method. So the amount excluding tax has to be 50 (and thats not correct, the amount included tax has to be 50)

**Comment by engcom-Delta** [comment]
Hi @Jilco thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop

**Steps to reproduce:**

- Create simple product:
- - Price=12.95
- - Advanced Inventory->Qty Uses Decimals=Yes
- Configure Free Shipping method
 ![image](https://user-images.githubusercontent.com/51681379/81396785-b803c780-912e-11ea-9ef1-a00e755c0736.png)
- Order 4,5 of it

**Result:**
:heavy_check_mark: Free shipping is visible in cart and checkout
![Peek 2020-05-08 13-17](https://user-images.githubusercontent.com/51681379/81397002-28124d80-912f-11ea-84ca-275dc0a55415.gif)


If you'd like to update the issue, please reopen it.
