### ISSUE TITLE
'illegal offset type' warning in MutableScopeConfig

### ISSUE THREAD

**Issue by vovayatsyuk** [magento/magento2#28075]
### Preconditions (*)

1. All magento versions. I used Magento 2.3.4.

### Description

The problem is that [MutableScopeConfig::getValue](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/MutableScopeConfig.php#L32) may [receive](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/Config.php#L70) `\Magento\Framework\App\ScopeInterface` as a scopeCode but uses it as array key:

~~~php
$this->data[$scope][$scopeCode][$path]
~~~

https://www.php.net/manual/en/language.types.array.php:

> Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.

### Steps to reproduce (*)

1. Run this code:
 
 ~~~php
        $result = \Magento\Framework\App\ObjectManager::getInstance()
            ->create(\Magento\Store\Model\Store::class)
            ->load(1)
            ->getFrontendName();
        echo $result;
        die;
~~~

2. Depending on your PHP settings you'll see a notice in the error log because [getFrontendName](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/Store.php#L1351-L1352) pass an object as scopeCode.

### Expected result (*)

1. Store name without php warnings

### Actual result (*)

1. Php warning 'illegal offset type'  is generated

### Possible solutions
1. Normalize scopeCode before use: I’ve made a PR while ago, but it was closed: https://github.com/magento/magento2/pull/27259
2. Do not pass object as scopecode and remove existing code that [allows to do that](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/Config.php#L70)

**Comment by engcom-Delta** [comment]
Hi @vovayatsyuk thank you for your report. Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop: I get result `Main Website Store` without any errors.

If you'd like to update the issue, please reopen it.

**Comment by vovayatsyuk** [comment]
Well, I can only ask you to look at this code simplified code lines:

1. Pay attention to the third argument:

```
$this->_config->getValue($arg1, $arg2, $this);
```

2. Pay attention to the third argument again:

```
    public function getValue($arg1, $arg2, $arg3) {
        if (isset($this->data[$arg2][$arg3][$arg1])) {
```

The third argument is **used as an array key**. Yes, it's the same `$this` passed from the code 1.

> Arrays and objects can not be used as keys. Doing so will result in a warning: Illegal offset type.

p.s. 
Code block 1 in magento: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/Store.php#L1351-L1352
Code block 2 in magento: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/MutableScopeConfig.php#L27-L32

**Comment by engcom-Delta** [comment]
I rechecked again and I am not able to get an issue you mentioned using code from **Steps to reproduce** 
Here https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/MutableScopeConfig.php#L27-L32 I get `$scopeCode` as object but i didn't enter in to `if` condition, and than object was correctly processed by `parent::getValue`
![image](https://user-images.githubusercontent.com/51681379/81403698-a6292100-913c-11ea-92cb-2edfc9243ca5.png)

Here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/Store.php#L1351-L1352 I get empty `$storeGroupName` and string `$this->_frontendName` from condition
![image](https://user-images.githubusercontent.com/51681379/81403265-affe5480-913b-11ea-8dee-94a075fc000a.png)

**Comment by vovayatsyuk** [comment]
I assume your PHP error reporting is set to ignore warnings.

Here is an abstract case:

```
$b = [];
$a = new stdClass();
if (isset($b[$a])) {
}
die;
```

My result of running this code:

```
Warning: Illegal offset type in isset or empty in index.php on line 23
```
