### ISSUE TITLE
How to add item to cart using rest API?

### ISSUE THREAD

**Issue by cruz94** [magento/magento2#28088]
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

**POST** http://localhost/magento2/rest/V1/carts/mine/items
Bearer Token <customer's token>
req body 
```
{
  "cartItem": {
    "sku": "WP01-28-Black",
    "qty": 1,
    "quote_id": "4"
  }
}
```
### Expected result (*)

```
{
  "item_id": 7,
  "sku": "WP01-28-Black",
  "qty": 1,
  "name": "Radiant Tee-M-Black",
  "price": 19.99,
  "product_type": "simple",
  "quote_id": "4"
}
```

### Actual result (*)

{
    "message": "Current customer does not have an active cart."
}

**Comment by engcom-Delta** [comment]
Hi @cruz94 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
![image](https://user-images.githubusercontent.com/51681379/81274346-d4353500-9058-11ea-9ac8-148fb0f5a91c.png)

Could be usefull: https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-add-items.html

If you'd like to update the issue, please reopen it
