### ISSUE TITLE
Error during upgrade 2.3.3 - Topic "inventory.source.items.cleanup" is not configured.

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#28090]
Preconditions
Magento 2.3.0
PHP 7.3

Steps to reproduce
Production Mode
Single Store Mode
Upgrade to 2.3.3
Run bin/magento setup;upgrade

Expected result
Upgrade should complete successfully

Actual result
Upgrade did not complete, error received: 
Topic "inventory.source.items.cleanup" is not configured.

....
Module 'Yotpo_Yotpo':
Installing schema... Upgrading schema...
Schema post-updates:
Module 'Magento_AdminAnalytics':
Module 'Magento_Store':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Amqp':
Topic "inventory.source.items.cleanup" is not configured.

**Comment by deepakbbob** [comment]
Facing the same issue. Can anyone help?

**Comment by digikeijs** [comment]
Same issue here, upgrading from magento 2.3.4 to magento 2.3.5 and when running setup:upgrade I have the same issue. 
When I do php bin/magento queue:consumers:list I get the same

In Config.php line 39:

  Topic "inventory.source.items.cleanup" is not configured.

queue:consumers:list
