### ISSUE TITLE
NumberFormatter

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#28097]
### Preconditions (*)
1. Magento 2.3.5-p1
2. PHP 7.2.27
3. Intl. version 1.1.0 | ICU version 50.1.2 | ICU Data version: 50.1 | ICU TZData version: 2012j | ICU Unicode version

### Steps to reproduce (*)
1. Configure CHF as Currency

### Expected result (*)
1. Price in product detail view (frontend) should have an precision of 2

### Actual result (*)
1. Price in product detail view (frontend) has an precision of 1
2.![precision-CHF](https://user-images.githubusercontent.com/2369089/80992153-5fd07b00-8e39-11ea-814d-d20aca28ae61.jpg)

### Additional Info

This happens, because $format = $formatter->getPattern(); in \Magento\Framework\Locale\Format at row 124 returns "#,##0.05 ¤" when currency is CHF. If the currency is EUR it returns "#,##0.00 ¤".
I don´t know what the five in the format means. But in row 132 the preg_replace removes the five. So only one decimal is left.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-28097-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28097-2-4-develop.instances.magento-community.engineering/admin_4165](https://i-28097-2-4-develop.instances.magento-community.engineering/admin_4165)
Login: `1180b305` Password: `8b1a2a679166`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @bernd-reindl thank you for your report. Unfortunatelly,  I'm not able to reproduce issue by steps you described on clean 2.4-develop

**Steps to reproduce:**

- CHF was set as default Currency:

![image](https://user-images.githubusercontent.com/51681379/81297186-94cc1000-907b-11ea-81d6-317f036f4000.png)

**Result:**
:heavy_check_mark: Price in product detail page has an precision of 2
![image](https://user-images.githubusercontent.com/51681379/81297309-bd540a00-907b-11ea-9544-313edacd6ef8.png)

![image](https://user-images.githubusercontent.com/51681379/81297362-ccd35300-907b-11ea-92a0-1b19713bf473.png)

**Comment by bernd-reindl** [comment]
> Hi @bernd-reindl thank you for your report. Unfortunatelly, I'm not able to reproduce issue by steps you described on clean 2.4-develop
> 
> **Steps to reproduce:**
> 
> * CHF was set as default Currency:
> 
> ![image](https://user-images.githubusercontent.com/51681379/81297186-94cc1000-907b-11ea-81d6-317f036f4000.png)
> 
> **Result:**
> ✔️ Price in product detail page has an precision of 2
> ![image](https://user-images.githubusercontent.com/51681379/81297309-bd540a00-907b-11ea-9544-313edacd6ef8.png)
> 
> ![image](https://user-images.githubusercontent.com/51681379/81297362-ccd35300-907b-11ea-92a0-1b19713bf473.png)
> 
> If you'd like to update the issue, please reopen it

Hi @engcom-Delta,
the result is depending on the installed intl version on the server.

If you run this code:
        ```
$formatter = new \NumberFormatter(
            'de_DE@currency=CHF',
            \NumberFormatter::CURRENCY
        );
        print_r([$formatter->getPattern()]);
```
And you get "#,##0.05 ¤" as result, the precision is one.
Older intl versions return "#,##0.00 ¤" and this works correct.

Can you run this code on your test machine?

Best regards
Bernd

**Comment by bernd-reindl** [comment]
Hi @engcom-Delta ,

how can i reopen this Issue. It isn't solved.

**Comment by engcom-Delta** [comment]
Hi @bernd-reindl I rechecked on php 7.2 and looks like issue is connected with your php configuration.
I am not able to reproduce issue with my setttings
I have ICU version => 64.2 by default for php 7.2.27
![image](https://user-images.githubusercontent.com/51681379/81934432-9c4d6500-95f7-11ea-9be9-d2d577248b13.png)
![image](https://user-images.githubusercontent.com/51681379/81934456-a5d6cd00-95f7-11ea-8046-6f1fbb0a939b.png)

**Comment by bernd-reindl** [comment]
ok. it seems it depends on the intl version.

Intl. version 1.1.0 | ICU version 50.1.2 | ICU Data version: 50.1 | ICU TZData version: 2012j | ICU Unicode version: 6.2
-> "#,##0.05 ¤" -> results in 1 digit for currency CHF


Intl. version 1.1.0 | ICU version 52.1 | ICU Data version: 52.1 | ICU TZData version: 2013g | ICU Unicode version: 6.3
-> "#,##0.00 ¤" -> results in 2 digits for currency CHF

So all user of version 50.1 have this bug. Others not.

**Comment by borishinzer** [comment]
I can confirm this issue with PHP-FPM 7.2 and 7.3 on a CentOS7 machine with PHP from Plesk-Repos:
PHP 7.3:
ICU version => 50.1.2
ICU Data version => 50.1
ICU TZData version => 2018e
ICU Unicode version => 6.2

PHP 7.2:
ICU version => 50.1.2
ICU Data version => 50.1
ICU TZData version => 2018e
ICU Unicode version => 6.2
