### ISSUE TITLE
Error while calling $product->getFinalPrice() method on catalog_product_save_after Observer

### ISSUE THREAD

**Issue by Jitheesh** [magento/magento2#28095]
### Preconditions (*)

1. Magento 2.3.5 Commerce 
2. PHP 7.2

### Steps to reproduce (*)

1. Create an Observer for catalog_product_save_after event
2. Call $product->getFinalPrice() method on that Observer

### Expected result (*)

1. Final Price should return for $product->getFinalPrice()

### Actual result (*)

1. Error warning  strtotime() expects parameter 1 to be string, object given in /var/www/vendor/magento/framework/Stdlib/DateTime/Timezone.php on line 275
2. magento 2 Recoverable Error: Object of class DateTime could not be converted to string in /vendor/magento/framework/Stdlib/DateTime.php on line 73

### More Info
-  There is no special from/to date fields on EE catalog product edit page  ( #5984 )
But it still validating special from/to dates here https://github.com/magento/magento2/blob/b1ef766d69780896a0b58e393b6b98a5d85f8279/app/code/Magento/Catalog/Model/Product/Type/Price.php#L647

- Above code expect $specialPriceFrom & $specialPriceTo as string, but on this Observer event it is instanceof DateTimeInterface

- Issue with function declaration and definition 
https://github.com/magento/magento2/blob/b1ef766d69780896a0b58e393b6b98a5d85f8279/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L252
This function accepts $dateFrom & $dateTo parameters as null, and pass those variables into   strtotime method.
$fromTimeStamp = strtotime($dateFrom);
$toTimeStamp = strtotime($dateTo); ( in our case $dateTo is null )

Passing null value to strtotime() will end with error warning.

**Comment by lampham2141993** [comment]
Hi @magento-engcom-team,
I can't replicate it on Magento 2.3.4-develop.
Infrastructure:
+ Magento 2.3.4-develop
+ PHP 7.2
+ Sample data
![final_price](https://user-images.githubusercontent.com/62533128/81804522-71093e00-9543-11ea-8360-8a51f075eda8.png)

**Comment by Jitheesh** [comment]
Hi @lampham2141993 That's strange, but I'm facing issues on Commerce project.

Could you please check these two file locations

https://github.com/magento/magento2/blob/b1ef766d69780896a0b58e393b6b98a5d85f8279/app/code/Magento/Catalog/Model/Product/Type/Price.php#L647

https://github.com/magento/magento2/blob/b1ef766d69780896a0b58e393b6b98a5d85f8279/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L252

Note: In commerce version, we don't have special from/to price,  So that those values will be empty or atleast special to date will be empty.


If you check this function declaration https://github.com/magento/magento2/blob/b1ef766d69780896a0b58e393b6b98a5d85f8279/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L252 you can see the chance of this error.
