### ISSUE TITLE
How can i add Order Comment on Print Order Pdf? Magento 2.3

### ISSUE THREAD

**Issue by rushikeshsolanki93** [magento/magento2#28101]
![abc](https://user-images.githubusercontent.com/20556034/81036935-91d7f080-8ebe-11ea-80be-7522beddeb4e.png)
here is the image that, shows comment and print order

**Comment by Rushikesh786** [comment]
![abc](https://user-images.githubusercontent.com/20556034/81036905-7967d600-8ebe-11ea-899e-355d8676c565.png)

**Comment by krishprakash** [comment]
Hi @Rushikesh786. 
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discussion about this
Thank You !!
