### ISSUE TITLE
Adding products to wishlist with custom options

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#28103]
### Preconditions (*)

1. Magento 2.4-develop
2.

### Steps to reproduce (*)

1. Create a simple product
2. Add a custom option (Dropdown/text field)
3. Save the product
4. Create an account on the Storefront
5. Go to simple product
6. Select the custom option value
7. Add the product to wishlist

### Expected result (*)

1. The wishlist page should be rendered without any errors

### Actual result (*)

1. Getting a fatal error
![Xnip2020-05-05_10-22-03](https://user-images.githubusercontent.com/15868188/81043344-be8a0900-8eba-11ea-85a7-fffbb71d90aa.jpg)

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-28103-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28103-2-4-develop.instances.magento-community.engineering/admin_bb30](https://i-28103-2-4-develop.instances.magento-community.engineering/admin_bb30)
Login: `10442ff2` Password: `3bd3f4b45138`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@eduard13 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34027` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment]
Getting the same on test instance. 
![image](https://user-images.githubusercontent.com/15868188/81043908-e88ffb00-8ebb-11ea-904f-627fcbe9ce37.png)

**Comment by ProkopovVitaliy** [comment]
I'm working on it.

**Comment by eduard13** [comment]
Closing this issue based on the following [comment](https://github.com/magento/magento2/pull/28259#issuecomment-634472654).
