### ISSUE TITLE
When duplicate product, new products inherits 'unwanted' attribute with default value

### ISSUE THREAD

**Issue by martijnhovinga** [magento/magento2#2810]
Magento 2.0
I have two attribute sets: 'mat' and 'education'
Mat contains product attributes 'size' and 'thickness' but does not contain the attribute 'discipline' which is part of the education attribute set.
However when I duplicate a product with attribute set mat, the resulting product receives a field discipline containing the default value.
The work around is to add products only and not to duplicate them.

**Comment by devhn** [comment]
Same as issue [#4111](https://github.com/magento/magento2/issues/4111)

**Comment by piotrekkaminski** [comment]
Possibly related to internal issue MAGETWO-53444

**Comment by vzabaznov** [comment]
Hi @martijnhovinga issue was closed and delivered, please check latest magento version, thanks for contributing
