### ISSUE TITLE
Cannot add children to empty configurable products

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#28119]
### Preconditions (*)
1. Magento 2.3.4 
2. A dropdown global attribute  

As for the use case please refer to this question https://magento.stackexchange.com/questions/312073/magento2-can-i-import-configurable-products-without-their-variations

### Steps to reproduce (*)
1. Create in the backend an attribute for configurable products (in my case `io_installation`)
2. Add two options `Horizontal` and `Vertical` 
3. Create a csv import file which will create 1 configurable product and 2 simple products. The configurable product is created plain, without any variations at this point. 

```
sku,store_view_code,attribute_set_code,product_type,product_websites,name,description,short_description,weight,product_online,tax_class_name,visibility,price,special_price,special_price_from_date,special_price_to_date,url_key,meta_title,meta_keywords,meta_description,created_at,updated_at,new_from_date,new_to_date,display_product_options_in,map_price,msrp_price,map_enabled,gift_message_available,custom_design,custom_design_from,custom_design_to,custom_layout_update,page_layout,product_options_container,msrp_display_actual_price_type,country_of_manufacture,additional_attributes,qty,out_of_stock_qty,use_config_min_qty,is_qty_decimal,allow_backorders,use_config_backorders,min_cart_qty,use_config_min_sale_qty,max_cart_qty,use_config_max_sale_qty,is_in_stock,notify_on_stock_below,use_config_notify_stock_qty,manage_stock,use_config_manage_stock,use_config_qty_increments,qty_increments,use_config_enable_qty_inc,enable_qty_increments,is_decimal_divided,website_id,related_skus,related_position,crosssell_skus,crosssell_position,upsell_skus,upsell_position,additional_image_labels,hide_from_product_page,custom_options,bundle_price_type,bundle_sku_type,bundle_price_view,bundle_weight_type,bundle_values,bundle_shipment_type,associated_skus,configurable_variations,configurable_variation_labels,has_options,required_options
test-config-no-variations,,Default,configurable,base,test-config-no-variations,,,2222.000000,1,Taxable Goods,"Catalog, Search",,,,,test-config-no-variations,Air tank galvanized,Air tank galvanized,Air tank galvanized ,"3/9/20, 5:26 PM","3/9/20, 5:27 PM",,,Block after Info Column,,,,Use config,,,,,,,Use config,,"am_hide_price_customer_gr=NOT LOGGED IN|General|Retailer|Wholesale,am_hide_price_mode=Yes,featured=0,ts_packaging_type=None",0.0000,0.0000,1,0,0,1,1.0000,1,10000.0000,1,1,1.0000,1,1,1,1,1.0000,1,0,0,0,,,,,,,",",,,,,,,,,,,,1,1
test-config-no-variationshorizontal,,Default,simple,base,test-config-no-variationshorizontal,,,2222.000000,1,Taxable Goods,"Catalog, Search",4,,,,test-config-no-variationshorizontal,Air tank galvanized,Air tank galvanized,Air tank galvanized ,"3/9/20, 5:26 PM","3/9/20, 5:27 PM",,,Block after Info Column,,,,Use config,,,,,,,Use config,,"am_hide_price_customer_gr=NOT LOGGED IN|General|Retailer|Wholesale,am_hide_price_mode=Yes,featured=0,ts_packaging_type=None,io_installation=Horizontal",0.0000,0.0000,1,0,0,1,1.0000,1,10000.0000,1,1,1.0000,1,1,1,1,1.0000,1,0,0,0,,,,,,,",",,,,,,,,,,,,0,0
test-config-no-variationsvertical,,Default,simple,base,test-config-no-variationsvertical,,,2222.000000,1,Taxable Goods,"Catalog, Search",5,,,,test-config-no-variationsvertical,Air tank galvanized,Air tank galvanized,Air tank galvanized ,"3/9/20, 5:26 PM","3/9/20, 5:27 PM",,,Block after Info Column,,,,Use config,,,,,,,Use config,,"am_hide_price_customer_gr=NOT LOGGED IN|General|Retailer|Wholesale,am_hide_price_mode=Yes,featured=0,ts_packaging_type=None,io_installation=Vertical",0.0000,0.0000,1,0,0,1,1.0000,1,10000.0000,1,1,1.0000,1,1,1,1,1.0000,1,0,0,0,,,,,,,",",,,,,,,,,,,,0,0
```
4. In your code inject `\Magento\ConfigurableProduct\Model\LinkManagement`
5. Try to add one simple product as child to the configurable product 

```php
        $this->linkManagement->addChild(
          'test-config-no-variations',
          'test-config-no-variationshorizontal'
        );
```

This will throw an error at `vendor/magento/module-configurable-product/Model/LinkManagement.php:131` that  `The parent product doesn't have configurable product options.`

6. By this logic I try to create a configurable product option  and set it to the configurable product.

```php
        $configurableOption = $this->optionInterfaceFactory->create();
        $configurableOption->setAttributeId(
          $this->attributeHelper->getAttributeIdByCode('io_installation')
        );
        $configurableOption->setLabel(
          $this->attributeHelper->getAttributeByCode('io_installation')
            ->getDefaultFrontendLabel()
        );
         $configurable->getExtensionAttributes()->setConfigurableProductOptions([$configurableOption]);

```

But I hit another bump at `vendor/magento/module-configurable-product/Model/OptionRepository.php:295` that the `Option values are not specified.`

7. So I have to create an option value for the configurable even though it won't use it yet before I link the child product or the link fails

```php
        //extra loading of the product because the optionValue needs to have a value_index so I'm using the `optionId` as the unique system reference
        $optionId = $child1->getData('io_installation');     
        $optionValue = $this->optionValueInterfaceFactory->create();
        $optionValue->setValueIndex($optionId);
        $configurableOption->setValues([]);
```

8. Save the configurable product so that the options are saved 

```php
    $configurable->getExtensionAttributes()->setConfigurableProductOptions([$configurableOption]);
    $this->productRepository->save($configurable);
```

9. After steps 6-8 performed once, at this point I can link any number of child products based on the 'io_installation' attribute using the `LinkManagementInterface` to the configurable product without defining an option value like I had to do for the first product linked or any option and I don't have to resave the configurable product before linking.

#### I think that the steps 6 - 9 are pretty incosistent for this and not to mention undocumented and let me explain my points:

To define the configurable option for the configurable product before linking a product we need to add three things `attribute_id`, `option_label`, `option_values` or it throws an error. 

#### Option Label
For one `option_label` we can define multiple `option_values` so I think the `attribute_label` is the best choice for this because all options_values will for all purposes become the attribute's option values. 

I guess it could have a use-case if we create configurable products based on the same attribute in multiple dimensions but I can't see any real life example. Maybe a product with 2 colors? I'm not sure it's possible within the backend to do this with the same attribute. You'd have to create 2 attributes. 

So If we're going to use the attribute_label anyways, I think this step could be optional since we have the attribute_id. We can load the label from the attribute_id if not specified instead of throwing an error at `vendor/magento/module-configurable-product/Model/OptionRepository.php:292` that the `Option label is not specified.` 

#### Option Values
If we omit the check for `Option values are not specified.` 
The product can saved with just passing an empty array as option values and it works perfectly fine for linking new products. 
I don't see why we should define an option value before linking the first product. Just the attribute should be fine. Could someone elaborate on why this check is needed?

```php
    public function validateNewOptionData(OptionInterface $option)
    {
        $inputException = new InputException();
        if (!$option->getAttributeId()) {
            $inputException->addError(__('Option attribute ID is not specified.'));
        }
        if (!$option->getLabel()) {
            // I think this can be loaded from the attribute id. No need to throw an error. 
            $inputException->addError(__('Option label is not specified.')); 
        }
        //an empty array seems to work fine. Maybe change it to $option->getValues !== null ? 
        if (!$option->getValues()) {
            $inputException->addError(__('Option values are not specified.')); 
        } else {
            foreach ($option->getValues() as $optionValue) {
                if (null === $optionValue->getValueIndex()) {
                    $inputException->addError(__('Value index is not specified for an option.'));
                }
            }
        }
        if ($inputException->wasErrorAdded()) {
            throw $inputException;
        }
    }
```

### Expected result (*)
1. The child product is linked even if the original configurable product doesn't have a specific option or variation defined. 
2. We should only have to declare based on which attribute ID the configurable product will be configured before linking the child products. 

### Actual result (*)
1. I've documented all the errors I passed through in the description of the issue as well as what I think should change. 

Sorry for the long issue, I've been trying to get a grip of what is happening in this use case for a few days now and I do think things could be simplified a bit.

**Comment by ioweb-gr** [comment]
I cannot reproduce on demo instance without access so someone else will have to verify it there.

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [Magento instance](https://i-28119-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28119-2-4-develop.instances.magento-community.engineering/admin_7e1f](https://i-28119-2-4-develop.instances.magento-community.engineering/admin_7e1f)
Login: `8e7a6af1` Password: `725382effd18`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment]
This is bug that still exists, it's not stale.

**Comment by ioweb-gr** [comment]
not stale

**Comment by ioweb-gr** [comment]
@magento give me 2.3.1 instance

**Comment by engcom-Bravo** [comment]
Hi @ioweb-gr ,

Could you please explain steps 1 and 4 in detail to help us reproduce the issue?

**Comment by ioweb-gr** [comment]
Sure, let me know what you don't understand so that I can explain it. The first 3 steps tell you to create a global drop-down attribute to create configurable products with and provide a csv file's contents to insert 3 products. 1 configurable and two variations which are the prerequisite for the issue.

With these products in place you can proceed to step 4 which tells you to use constructor dependency injection to use the following code sample which should work but doesn't

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Have you made a custom module for this? If yes can you please share it here so that we can look into it? Also please share your use case for this.

Thanks

**Comment by ioweb-gr** [comment]
Hi this was during development of a custom ERP synchronization module. In order to function you'd need an active ERP. I tried to be very thorough in explaining the relevant code pieces though

**Comment by engcom-Lima** [comment]
Hi @ioweb-gr,

Can you please try and reproduce this error on 2.4-develop branch ? We would be happy to check the same develop instance and work directly with you on this issue which you are facing.

Thanks

**Comment by engcom-Lima** [comment]
Hi @ioweb-gr,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
