### ISSUE TITLE
Don't want to show child product's images on configurable product page

### ISSUE THREAD

**Issue by merlin-18** [magento/magento2#28118]
Preconditions (*)

    Using Magento 2.3.4. I want to change the Magento 2 default functionality on this

Steps to reproduce (*)

    1) Create a configurable products with child products having some images
    2) Select any option (here i have the color attribute as options)

Expected result (*)

    1) Only the main product image changes
    2) Only show the parent products images

Actual result (*)

    1) main product image changes as we needed
    2) child product's images are getting appending to the parent images.

Additional Information (*)
   
   1) In view.xml it has an option for this.

    2) here only the values i know are prepend and replace. But i dont want to show the child products images on configurable products.

### Additional info from Engcom
Reproducible on 2.4-develop

### Steps to reproduce:

1. Create a configurable product with child products having some images (with color attribute as options)
2. Go to Store and select previously created product
3. Verify that the main product image displayed
4. Select any other option and verify that only parent product image is shown

Actual Result: Child product image is getting appending to the parent images.
![products images](https://user-images.githubusercontent.com/51680745/95748236-5a0d7a00-0ca2-11eb-84f8-a1435eb87385.gif)

**Comment by merlin-18** [comment]
yes the issue is reproducible.

**Comment by magento-engcom-team** [comment]
Hi @merlin-18. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by merlin-18** [comment]
ok, Thank you

**Comment by merlin-18** [comment]
Hi,
Is there any update on the module requirement. Actually it's very urgent for me.

Thank you

**Comment by engcom-Bravo** [comment]
Reproducible on 2.4-develop

### Steps to reproduce:

1. Create a configurable product with child products having some images (with color attribute as options)
2. Go to Store and select previously created product
3. Verify that the main product image displayed
4. Select any other option and verify that only parent product image is shown

Actual Result: Child product image is getting appending to the parent images.
![products images](https://user-images.githubusercontent.com/51680745/95748236-5a0d7a00-0ca2-11eb-84f8-a1435eb87385.gif)

Added additional info to description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38352` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Update:
Internal Jira ticket related to this issue was closed as "Won't fix".

Described steps to reproduce is expected result.
This option can be configured in the admin panel  
- Swatch attributes (Admin > Stores > Attributes > Product) have a setting `Update Product Preview Image`. If set to `No` will simply prevent swatches from updating product images. This setting is only available for the input type of Visual/ Text Swatch only.

Also, seems this option was missed in public documentation which potentially causes this report.
Update documentation currently in progress and should be available soon
