### ISSUE TITLE
Conditions to the Catalog Products List Widget not saving

### ISSUE THREAD

**Issue by ayushman2013** [magento/magento2#2811]
Hi,

I am using Magento2 in my local Ubuntu envirnment. I have configured the server as per Magento 2 requirement and everything working find. But, when tried using Widget got issue. I tried to install a widget "Catalog Product List" and tried to setup the condition but it is not saying. I set and click save and didn't find the effect in the website. Then, while investigating found out condition applied on the widget is not saving.

How to fix this issue?

Regards,
Ayushman

**Comment by shiftedreality** [comment]
Hi @ayushman2013 

I have created internal issue MAGETWO-47932 to investigate this issue

**Comment by jonsaf** [comment]
I am experiencing the same issue.  I see that this was an acknowledged bug, but is there a fix?

**Comment by hezide** [comment]
I have got the same issue, is there a fix for this?

**Comment by ghost** [comment]
Can confirm this seems to still exist in 2.1.6

**Comment by magento-engcom-team** [comment]
@ayushman2013, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@ayushman2013, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@ayushman2013, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@ayushman2013, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
