### ISSUE TITLE
Magento_CSP 'script-src' policy with a nonce value is not compatible with stock Magento's inline <script>'s

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#28111]
### Preconditions (*)
1. 2.4-develop
2. Add a CSP policy that contains a nonce value for script-src.

Example module containing the necessary policy addition included [here](https://www.gwharton.com/temp/CSPTestModule.zip)

### Steps to reproduce (*)
1. Enable Developer Tools
2. Browse to home page

### Expected result (*)
1. Homepage loads successfully with no CSP warnings.

### Actual result (*)
1. Warnings are displayed for ALL inline scripts

![image](https://user-images.githubusercontent.com/30697781/81096622-93c1a400-8efe-11ea-88e0-9f4d32ecc780.png)

The error message notifies **"Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list."** Therefore, none of the inline scripts would be processed if it was enforcing the policy. Using a nonce, as is required if you are going to implement a CSP policy for Google Tag Manager/Adwords/Analytics is not possible with stock Magento.

**Comment by gopal2k6** [comment]
Dear Team,

We are facing same issue  in Magento ver. 2.3.5-p1. 

Kindly resolved this issue soon as possible.

http://prntscr.com/sbgx8q

Regards
Gopal Gautam

**Comment by gwharton** [comment]
@gopal2k6 Yours is a slightly different issue. You just need to add the relevant csp_whitelist.xml whitelist entries for the blocked entries. Although I see you are using google, so you'll soon want to add a nonce value to CSP, when you will run into the above issue.

**Comment by gwharton** [comment]
As an aside to this issue, Magento should really have an inbuilt method of creating the nonce values and adding it to the CSP policy by default, and then providing a mechanism for modules to access and include the nonce value in a non cacheable way in their script tags.

**Comment by gopal2k6** [comment]
Ok but this is  New Feature added in New Version.  Is there any option how to remove or disable this feature,

**Comment by gwharton** [comment]
You could try disabling module magento_csp. Also they are only warnings as the policies are not enforced, but it does look bad to customers i agree.

**Comment by peterjaap** [comment]
You can just disable `Magento_Csp` entirely since in its current state it gives a false sense of security. See https://maxchadwick.xyz/blog/magento-2-3-5-csp-fools-errand + https://maxchadwick.xyz/blog/magento-disable-csp for more info.

**Comment by gwharton** [comment]
In its current state, Magento_Csp does not give any sense of security at all as it doesn't actually enforce anything in 2.3.x, it just spits out a load of warnings.

As mentioned in the link you posted, a more secure way than using unsafe-inline is to use a nonce. This issue is about exactly that. If you use a nonce, unsafe-inline is ignored by clients, and the inline scripts would not be run. Ok, theres more to fix than inline javascripts, but it is one thing that needs to be fixed in order to proceed with CSP.

**Comment by andrei-vdc** [comment]
You can enable the security by setting the report_only to false in a config.xml file:

    <default>
        <csp>
            <mode>
                <storefront>
                    <report_only>0</report_only>
                </storefront>
                <admin>
                    <report_only>0</report_only>
                </admin>
            </mode>
        </csp>
    </default>

However, I'm facing the same issue with whitelisted sources not working in any way so I guess doing so will only break a site for now

**Comment by gwharton** [comment]
I'm going to close this as unsafe-inline is due to be removed in 2.4.1

**Comment by GamesmenJordan** [comment]
> I'm going to close this as unsafe-inline is due to be removed in 2.4.1

Is it worthwhile reopening this issue as `unsafe-inline` is still in use in 2.4.3 and there is no indication that it will be removed any time soon. The lack of support for `nonce` for inline scripts is a significant issue that undermines the entire purpose of having CSP in the first place. It's well and good to block unauthorised external scripts being loaded, but injecting those same scripts into the page is as, if not more, significant as an attack vector.

**Comment by engcom-Hotel** [comment]
Hello @GamesmenJordan,

Thanks for reopening the issue!

Can you please update us with the latest steps to reproduce for this issue?

Thanks

**Comment by GamesmenJordan** [comment]
Hi, I didn't actually reopen the issue, but regardless nothing has changed from the original issue. Any CSP that enforces script hash or nonce will not work because Magento 2 doesn't generate either hash or nonce values for inline scripts.

It's part issue, part feature request.

Firstly it's an issue because it is a primary attack vector for XSS.

Secondly it's a feature request because it requires the development of some subsystem for generating hash or nonce values on script tags and the ability to fetch the generated nonce on script tags regardless of where the tag is created (layout xml, template phtml, generated in php functions, etc.).

This is definitely not a small task and would also require a concerted effort to push third-party modules to adopt the practice for their own modules - hence the need for a standardized way to generate and fetch the required nonce.

**Comment by engcom-Hotel** [comment]
Hello @gwharton,

We have tried to reproduce the issue in 2.4-develop branch with the module attached in main description. But the issue is now able to reproducible at our end.

We request you please try to reproduce it in 2.4-develop branch and let us know if you are able to reproduce it.

Thanks

**Comment by GamesmenJordan** [comment]
@engcom-Hotel What do you mean by "not able to reproduce"?

**Comment by engcom-Hotel** [comment]
Hello @GamesmenJordan,

I mean we are not able to see such errors in the console as mentioned in the main description. Maybe the issue has been fixed already. So I am requesting reproduction in Magento 2.4-develop.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @GamesmenJordan,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
