### ISSUE TITLE
TEST ISSUE

### ISSUE THREAD

**Issue by VladimirZaets** [magento/magento2#28125]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Sutharsan27 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34090` were created

**Issue Available**: @Sutharsan27, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
