### ISSUE TITLE
Contradiction in the devdoc

### ISSUE THREAD

**Issue by bardon-bicarbonate** [magento/magento2#28123]
### Summary (*)
I believe there is contradicting information in the dev docs

### Preconditions (*)
None

### Steps to reproduce (*)

1. Go to [this devdoc](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.html#override-module-styles), at the "Override module styles" paragraph

### Expected result (*)

![image](https://user-images.githubusercontent.com/32772726/81165749-ccab5880-8f92-11ea-8ff4-747346abfd35.png)

                       |-- _module.less

matches the given example `<your_theme_dir>/Magento_Review/web/css/source/_module.less.`

### Actual result (*)

![image](https://user-images.githubusercontent.com/32772726/81165067-a89b4780-8f91-11ea-8778-79ab3981c201.png)
does not match the given example
`    <your_theme_dir>/Magento_Review/web/css/source/_module.less.`

**Comment by engcom-Delta** [comment]
Hi @bardon-bicarbonate , thank you for your report
Please, open issue in appropriate [repo](https://github.com/magento/devdocs)
