### ISSUE TITLE
GraphQl Order and Invoice Emails are not send on quoteSubmit.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#28124]
### Preconditions (*)

1. Magento 2.3.4
2. sales_email/order/enabled is set to Yes.

### Steps to reproduce (*)

1. Create Cart through GraphQl
2. Add simple product to cart through GraphQl
3. Set Guest email to cart through GrahpQl
4. Set Billing and Shipping addresses through GraphQl
5. Set a Payment method through GrahpQl
6. Place order through GrahQl

### Expected result (*)

1. I receive an order email on the email address set in step 3.

### Actual result (*)

1. No email.

### Solution

Add the "sales_model_service_quote_submit_success" event to GraphQl as well.

**Comment by noglitchyo** [comment]
I experience the same, using the same version.

**Comment by Hexmage** [comment]
The fix is duplicating the Magneto/Quote/etc/frontend/events.xml to Magento/QuoteGraphQl/etc/graphql/events.xml

**Comment by cyildirim** [comment]
I was able to reproduce and tested the solution that @Hexmage suggested. It works fine.

**Comment by cyildirim** [comment]
@magento I am working on this

**Comment by cyildirim** [comment]
accepted

**Comment by magento-quality-patches** [comment]
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-30444: Fixes the issue where no confirmation email is sent for orders placed using GraphQL.
 
**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.0 - 2.4.0
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-30444`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)
