### ISSUE TITLE
[BUG] Product Importer Attributes decimal type and localization Error

### ISSUE THREAD

**Issue by ACodeManiac** [magento/magento2#28136]
### Preconditions (*)
1. Magento Version: 2.3.4
2. Magento Product Importer

### Steps to reproduce (*)
1. Upload CSV file with products in importer

### Expected result (*)
Importer should handle the attribute type 'decimal' correctly. For example if I am creating a csv file with product prices in Germany the default decimal separator is ',' not '.' like in US regions.

Magento product importer should detect this based on the current locale setting in the administration backend and automatically convert all decimal attribute separators (eg. ',') values to the standard '.'

### Actual result (*)
1. Importer throws errors on every attribute with datatype 'decimal' (because separator is not a dot) and uploading the csv is impossible.

**Comment by engcom-Delta** [comment]
Hi @GGMCarl thank you for your report. I checked issue on 2.4-develop. Seems like this behavior is not an issue as price `10.56` is converted into `10,56`, in my case, if admin panel locale is German. 
**Manual testing scenario:**
- Set admin Interface Locale=German
- Import scv file with decimal separator is '.'
[import.csv.txt](https://github.com/magento/magento2/files/5638481/import.csv.txt)


**Result:**
:heavy_check_mark: Product price has decimal separator is ',' after import
![image](https://user-images.githubusercontent.com/51681379/101077618-bfe4f680-35ad-11eb-8721-02ec7d98bc25.png)

If you'd like to update the issue, please reopen it.
