### ISSUE TITLE
Reset password send mail but click on link it expired

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#28133]
### Preconditions (*)
 Using Magento 2.3.5-p1
1. 
2.

### Steps to reproduce (*)

1. send reset password email from admin panel , user received email and click on link it showing Your password reset link has expired. 
2.  when i am using forgot password link from website it still not showing some time showing Your password reset link has expired or sometime showing Invalid Form Key. Please refresh the page. 

### Expected result (*)

1. emailed lik should work and customer can reset password
2. using forgot password link it also send email and customer can reset password

### Actual result (*)

1. emailed link it showing Your password reset link has expired. 
2.  when i am using forgot password link from website it still not showing some time showing Your password reset link has expired or sometime showing Invalid Form Key. Please refresh the page.

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera, here is your [Magento instance](https://i-28133-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28133-2-4-develop.instances.magento-community.engineering/admin_81d6](https://i-28133-2-4-develop.instances.magento-community.engineering/admin_81d6)
Login: `eabbe1be` Password: `08bb25b3b80d`
Instance will be terminated in up to 3 hours.

**Comment by hemendraajmera** [comment]
any email from above mentioned environment not received

**Comment by shikhamis11** [comment]
Hi @hemendraajmera 
I checked this issue on 2.3.5-p1 
I am not able to reproduce this issue , I am able to reset password from reset link send from website as well as admin

**Comment by Jazzz09** [comment]
I am also getting the same issue in 2.3.5-p3 admin for the password reset. It seems the Password Reset Confirmation email contains an incorrect email because of which we are getting this issue. In vendor/magento/module-user/view/adminhtml/email/password_reset_confirmation.html 
`{{store url="admin/auth/resetpassword/" _query_id=$user.id _query_token=$user.rp_token _nosid=1}}`

Try using below one instead of above:

**Comment by NORDCOMPCZ** [comment]
The very same issue on 2.4.1

**Comment by NORDCOMPCZ** [comment]
There are to RP tokens being saved into DB

**Comment by royalkaroma** [comment]
hi i tray every thing propose to me nothing work rest link exoired for clinet 
 Mot de passe oublié ?
"email" est requis. Entrez et réessayez.
Le lien de réinitialisation de mot de passe a expiré.
Veuillez entrer votre adresse email ci-dessous pour recevoir un lien de réinitialisation de mot de passe.

**Comment by asannikov** [comment]
In my case, the old patch in composer changed the name of the "content" XML block here vendor/magento/module-user/view/adminhtml/layout/adminhtml_auth_resetpassword.xml and as a result, the content block was not readable here: vendor/magento/module-user/Controller/Adminhtml/Auth/ResetPassword.php.

I summed up the key entry points, where you can check it:
```
vendor/magento/module-user/Controller/Adminhtml/Auth/ResetPasswordPost.php::execute
vendor/magento/module-user/view/adminhtml/templates/admin/resetforgottenpassword.phtml
vendor/magento/module-user/Controller/Adminhtml/Auth/ResetPassword.php::execute
```
