### ISSUE TITLE
Elastic Search Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc in product names

### ISSUE THREAD

**Issue by scottbolasevich** [magento/magento2#28135]
Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc

Preconditions
magento 2.3.4 and elastic search 6+ on nexcess

Magento Version : 2.3.4

ElasticSuite Version : 6.0

Environment : production

Third party modules : no

Steps to reproduce
1.https://www.goinggreensolutions.com.au/
2. search "eco max"
3. you can see here https://prnt.sc/s8v1k7

Expected result
normal search results
{
"title": "Eco",
"num_results": "242"
},
Actual result
[Screenshot, logs] sql error
https://www.goinggreensolutions.com.au/search/ajax/suggest/?q=eco+max&_=1588277353486
{
"title": "eco max brush' AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 EN",
"num_results": "267"
}
https://prnt.sc/s8v1k7

FYI i dont need a test box or anything either. .this problem is all over the internet look at all the sites with this issue.. it must be from a special character in the product title/name or something not being escaped properly

https://prospecelectronics.com/search/ajax/suggest/?q=prv
http://www.northfalmouthrentals.com/catalogsearch/ajax/suggest/?q=EKGQ
https://noti.nu/catalogsearch/ajax/suggest/?q=car

i mean there are literally hunderds of sites with this problem i can use google like a scanner and just give you a ton of results.. you can see here also effecting there front end https://prnt.sc/s8vai5

so this is likley a wide spread problem on like every installation of elastic search either that or ALOT of people including myself have it misconfigured?? any info here would be great

**Comment by denchev** [comment]
@scottbolasevich I was not able to reproduce the problem on the following setup:

- Magento 2.4-develop
- Elasticsearch 7.9
- Added products that have word "max" and "count" in the name
- Reindex

When I search for any of the words "max" or "count" I get a proper autocomplete.

**Comment by engcom-Delta** [comment]
Hi @scottbolasevich , I'm not able to reproduce issue by steps you described on clean 2.4-develop and elasticsearch 7.x
**Result:**
:heavy_check_mark: Search results are shown without errors
![image](https://user-images.githubusercontent.com/51681379/100068407-29436780-2e40-11eb-860e-f338fc5808b4.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
