### ISSUE TITLE
Propose to enable CSS source map generation while using the Oyejorge Less compiler in the Developer mode

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2813]
https://github.com/oyejorge/less.php#source-maps

**Comment by AddoSolutions** [comment]
+1

**Comment by barego** [comment]
+1

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Propose-to-enable-CSS-source-map-generation-while-using-the/idi-p/45758).
