### ISSUE TITLE
Configuration  menu not work 

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#2814]
![configuration_error](https://cloud.githubusercontent.com/assets/16436069/12002534/36762f2a-ab26-11e5-9f20-7771a7509a7d.png)

Configuration menu not work i can change All store then not work this menu. pliz replay.....

**Comment by srenon** [comment]
Are you still having this issue? 

This should be a side effect of your previous issue  https://github.com/magento/magento2/issues/2815

**Comment by mitulispace** [comment]
yes  side effect of  my previous issue #2815

**Comment by mitulispace** [comment]
But solve

**Comment by MomotenkoNatalia** [comment]
@mitulispace do you still have an issue?

**Comment by mitulispace** [comment]
MomotenkoNatalia      No Issue..... It's  Solve  Thank You For reply
