### ISSUE TITLE
Qual versão Magento é mais instavel ? estou com a 2.2.0 será que a versão 2.3.5 ta tudo ok ?

### ISSUE THREAD

**Issue by vilmarmoreno** [magento/magento2#28146]
<!---Qual versão Magento é mais instavel ? estou com a 2.2.0 será que a versão 2.3.5 ta tudo ok ?

**Comment by krishprakash** [comment]
Hi @vilmarmoreno. 
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discussion about this
Thank You !!
