### ISSUE TITLE
In cart, Estimate Shipping display bug when changing the quantity of an item

### ISSUE THREAD

**Issue by Thomas-gt3** [magento/magento2#28145]
**Preconditions :**
- PHP 7.2 with Debian/Plesk
- Varnish is not installed
- Magento 2.3.5p1 and Magento 2.4 development

**Steps to reproduce :**
1) Install Magento 2 with sample data
2) Configuration > Checkout > Allow Guest Checkout: No
3) Configuration > Shipping Methods > Free Shipping > Enabled: Yes
4) Configuration > Shipping Methods > Free Shipping > Minimum Order Amount : 50
5) Configuration > Shipping Methods > Table Rates > Enabled : No
6) Flush Magento Cache

7) Go to Frontend and Create an Account
8) Go to Address Book for Create Adress and Save

9) Go add "Zing Jump Rope" in cart and click on "View and Edit Cart"
10) Click on "Proceed to Checkout" and select first line "$0.00 Free Free Shipping"
11) Return on Shopping Cart

10) Make vary the quantity of the product between 4 and 5 and update with button several times
11) Now, watch Shipping line

**Expected result :**

Qty 4 --> Shipping (Flat Rate - Fixed)	$20.00
Qty 5 --> Shipping (Free Shipping - Free)	$0.00

 **Actual result :**

Continue to vary the quantity (and update with button) until you see the bug : 

Qty 4 --> Shipping (Free Shipping - Free)	$0.00

Screenshot : 

![1](https://user-images.githubusercontent.com/57117461/81346417-89e4a000-90ba-11ea-998a-6e1418b13dd3.png)

If I refresh with F5, the value becomes correct again :

![2](https://user-images.githubusercontent.com/57117461/81346617-dfb94800-90ba-11ea-9e36-719699842571.png)

**Comment by Thomas-gt3** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by Thomas-gt3** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by Thomas-gt3** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by Thomas-gt3** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Thomas-gt3. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Thomas-gt3, here is your [Magento instance](https://i-28145-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28145-2-4-develop.instances.magento-community.engineering/admin_ce87](https://i-28145-2-4-develop.instances.magento-community.engineering/admin_ce87)
Login: `d2b45935` Password: `085f2a98de70`
Instance will be terminated in up to 3 hours.

**Comment by Thomas-gt3** [comment]
I reproduced:

![Screenshot_2020-05-23 Shopping Cart](https://user-images.githubusercontent.com/57117461/82737004-0966a600-9d2e-11ea-8141-150e7e0abd5d.png)

If I refresh with F5, the value becomes correct again :

![Screenshot_2020-05-23 Shopping Cart(1)](https://user-images.githubusercontent.com/57117461/82737008-0f5c8700-9d2e-11ea-9fe0-9ff1505750ff.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@magento give me 2.3.5p1

**Comment by sambath1293** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by sambath1293** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by sambath1293** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-28145-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28145-2-4-develop.instances.magento-community.engineering/admin_fc3d](https://i-28145-2-4-develop.instances.magento-community.engineering/admin_fc3d)
Login: `5012a086` Password: `485597a34bab`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @Thomas-gt3  thank you for your report, I'm not able to reproduce issue by steps you described on 2.4-develop
![Peek 2020-08-12 15-41](https://user-images.githubusercontent.com/51681379/90016808-413d1400-dcb3-11ea-87dc-0d685242c6fb.gif)

If you'd like to update the issue, please reopen it.

**Comment by t-eichmann** [comment]
We can reproduce this in Magento 2.4.2-p2 and Magento 2.4.3
