### ISSUE TITLE
Save Config Button Not work

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#2815]
Any Solution i think .js Error  but how to solve..... 
![download](https://cloud.githubusercontent.com/assets/16436069/12003027/4b7cb6ea-ab36-11e5-90b1-e9fab18dfd0e.png)

![error_config](https://cloud.githubusercontent.com/assets/16436069/12003042/c5adc1d4-ab36-11e5-934c-2e7943b4410e.png)

**Comment by srenon** [comment]
You seem to have  404 issue on your static files.

Try ssh into your server and check the owner/permission on 

{magentoRoot}/pub
{magentoRoot}/pub/static

Then try

`magento setup:static-content:deploy <lang> ... <lang> [--dry-run]`

ie
`{magentoRoot}/bin/magento setup:static-content:deploy en_US`

See http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html

**Comment by mitulispace** [comment]
SRENON Thank you  reply...   Correct Solution

**Comment by mitulispace** [comment]
Otherwise Re-installation  Your Magento 2

**Comment by mitulispace** [comment]
http://itsolutionphp.blogspot.in/2015/12/save-config-button-not-work-in-magento-2.html

**Comment by qasimali786** [comment]
Save Config Button Not work in magento 2

**Comment by qasimali786** [comment]
All Chages Configuration Button not save
