### ISSUE TITLE
Magento 2 backend incorrectly renders the nested fieldsets: adds nested TR tags with the same id

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2817]
https://mage2.pro/t/330

**Comment by shiftedreality** [comment]
Hi @dfediuk 

Thank you for reporting. Created internal ticket MAGETWO-47869 for investigation.

**Comment by arkadiych** [comment]
@dfediuk , could you give an example, where this bug is reproducible?

**Comment by mazhalai** [comment]
@mage2pro closing this as non-reproducible.
