### ISSUE TITLE
Added new image for product not showing on category page but it showing on product page

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#28182]
Magento Environment 2.3.5-p1
### Summary (*)

1. Edit product
2. uploaded new image and set base, small and thumbnail that image 
3. save product
4. navigate on category page 
5. for that product image not showing and open image path in new tab , image not found but
6. when open product in new tab, it showing that image on product detail page. i also open path in new tab it working and showing image.
7. compare both category page product image path and product page image path both are not same.
8. category page showing old hash in url and product detail showing new hash in URL, as per my understanding

### Examples (*)

![image](https://user-images.githubusercontent.com/2478037/81544595-5d1fd980-9395-11ea-817a-2049a8ffdf2c.png)

### Proposed solution

product image should be showing on category page whenever changed

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by hemendraajmera** [comment]
Without running command 
php bin/magento catalog:image:resize
 it should be showing updated image on category page as well on product page.
every time uploading new image i will not process with this resize command to show images on pages.
If i run the php bin/magento catalog:image:resize command and provide permission permission it working fine.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by SyedWaqasNabi** [comment]
Hi I am facing similar issue . Is there any solution available for this?

**Comment by lmg-LL** [comment]
I am facing a similar issue, was there a solution for it?

**Comment by dimdimich** [comment]
We still have same issue for several clients. Please provide Magento instance so we can recreate it.
