### ISSUE TITLE
Should we import namespaces?

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#28185]
Question about Magento 2 coding standards. Should we (as developers) full namespaces or short namespaces with use keyword?

**Comment by andrewbess** [comment]
Hello @madonzy 
I think you can ask about it in [Magento Community Engineering Slack](https://magentocommeng.slack.com/).
It shouldn't be an issue on this repository.
Come join us.

**Comment by madonzy** [comment]
@andrewbess I'm not able to log in, because I don't have accounts @magento.com, @divante.pl, @divante.co, @webvisum.de, or @adobe.com

**Comment by engcom-Echo** [comment]
Hi @madonzy. Thank you for your report.

I think you find an answer to your question here: [Coding Standards](https://devdocs.magento.com/guides/v2.3/coding-standards/bk-coding-standards.html)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by madonzy** [comment]
@engcom-Echo, unfortunately, there's no information about using full or import namespaces. The only info is that we should use constants and not string literals.
