### ISSUE TITLE
[Issue] Admin product grid for drop-down/multi-select attributes use wrong values 

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#28183]
The product grid in admin does not show the same values as the product edit screens do, or the filters.

I suspect is could be a similar pattern to #19221 

Fixed in 2.4.4

### Preconditions (*)

1. Tried on 2.3.3 and 2.3.4 - up to 2.4.3-p1 (fixed in 2.4.4) also
2. A dropdown or multiselect attribute with different admin values from front end store view values
3. Set the attribute to be visible in admin grid and usable for filtering

There are reasons to have a different value in admin than on frontends:
- the language of team working on site
- the values displayed on the front end are long and wordy and this makes a painfully wide drop down list and grid column
- an attribute has a long list of options, and admin values are set to be easier to scan and jump around in by key press

### Steps to reproduce (*)

1. Go to product admin grid
2. Select  multi select attribute (eg: "my color")
3. Enable filters for that attribute
4. set the website value and admin value to be different
5. Go to the product grid filter and open the drop down

### Expected result (*)

1. The drop down should contain the admin values of the options, as it does in product edit and elsewhere in admin

### Actual result (*)

1. The drop down contains the default site view values of the options

I suspect this change was made so the grid entries showed the frontend value but if people have taken the time to set a different admin value and frontend value for an attribute it is likely because they want to see the admin value in admin. That's the point of it, no

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by iphigenie** [comment]
1 day without instance deployment I have tested it on a vanilla install elsewhere and can reproduce the same behaviour

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iphigenie, here is your [Magento instance](https://i-28183-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28183-2-4-develop.instances.magento-community.engineering/admin_b766](https://i-28183-2-4-develop.instances.magento-community.engineering/admin_b766)
Login: `b4d1313f` Password: `0e7191fc2817`
Instance will be terminated in up to 3 hours.

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by iphigenie** [comment]
any day now...

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by iphigenie** [comment]
@magento-engcom-team I can hope :)

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iphigenie, here is your [Magento instance](https://i-28183-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28183-2-4-develop.instances.magento-community.engineering/admin_bfb2](https://i-28183-2-4-develop.instances.magento-community.engineering/admin_bfb2)
Login: `895943ce` Password: `10a6cdd548f8`
Instance will be terminated in up to 3 hours.

**Comment by iphigenie** [comment]
Reproduced using the "my color" attribute

Different attribute option label values:

![documenting1](https://user-images.githubusercontent.com/1055826/87510618-ce1c8f80-c66b-11ea-8c4a-6ff4fad1ce07.PNG)

Product admin correctly uses the admin value:

![documenting3](https://user-images.githubusercontent.com/1055826/87510687-ef7d7b80-c66b-11ea-9ba0-cff6c0b2db05.PNG)

Grid uses default site view values - it should use admin values too

![documenting2](https://user-images.githubusercontent.com/1055826/87510726-03c17880-c66c-11ea-9542-895bd88e8130.PNG)

**Comment by iphigenie** [comment]
> Hi @iphigenie. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x ]  Summary of the issue
> * [ x]  Information on your environment
> * [ x]  Steps to reproduce
> * [ x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @iphigenie do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iphigenie, here is your [Magento instance](https://i-28183-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28183-2-4-develop.instances.magento-community.engineering/admin_fcf2](https://i-28183-2-4-develop.instances.magento-community.engineering/admin_fcf2)
Login: `70ca139b` Password: `3cbafb5fb1aa`
Instance will be terminated in up to 3 hours.

**Comment by iphigenie** [comment]
how do i get help for triage on this?

**Comment by iphigenie** [comment]
@magento add to contributors team

**Comment by iphigenie** [comment]
@magento I am working on this

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iphigenie, here is your [Magento instance](https://i-28183-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28183-2-4-develop.instances.magento-community.engineering/admin_0881](https://i-28183-2-4-develop.instances.magento-community.engineering/admin_0881)
Login: `58409647` Password: `10b1d326d40f`
Instance will be terminated in up to 3 hours.

**Comment by iphigenie** [comment]
This issue is still happening on 2.4.1

**Comment by Pavel-Fekete** [comment]
I can confirm that issue is reproducible on 2.4.1
![241](https://user-images.githubusercontent.com/67371013/102088542-bbc59e00-3e23-11eb-8f54-9ebfb56d4e7c.png)

But not reproducible on 2.4-develop, drop down contain the admin values of the options
![develop](https://user-images.githubusercontent.com/67371013/102088625-d7c93f80-3e23-11eb-810f-a1ccf8f7f752.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39910` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by iphigenie** [comment]
This issue is still happening in the current branch

**Comment by iphigenie** [comment]
The issue also affects date fields - they are shown using the front end site locale settings and not shown in the same way as they are shown on the product admin

Admin display should be consistent, one shouldn't see it differently on edit form as in grid

**Comment by cdbessig** [comment]
This issue is affecting us on 2.4.3

**Comment by iphigenie** [comment]
I'll check 2.4.4 and if that's still affected then will create a ticket again

**Comment by cdbessig** [comment]
If it is, post a link here.  We might have a pull request for it.  I know someone on our team wrote a module to address.

**Comment by iphigenie** [comment]
It seems fine on 2.4.4
The sort order of attribute values on front end is still messed up on the other hand
