### ISSUE TITLE
Wrong price in the tracking information email

### ISSUE THREAD

**Issue by chaikivskyi** [magento/magento2#28180]
### Preconditions (*)
Magento  2.3.4
Magento 2.4-develop

### Steps to reproduce (*)
1. Create bundle product:
![image](https://user-images.githubusercontent.com/51681379/107948442-7e54cc80-6f9c-11eb-8a74-13aa53911b6f.png)
![image](https://user-images.githubusercontent.com/51681379/107948466-87459e00-6f9c-11eb-88ac-311f01d476a8.png)

2. Add bundle product to cart
3. Change price for a simple product in the admin panel that is in the cart.(e.x., from $89 to $95)
4. Make order
5. Create shipment for order and add tracking code
6. Send tracking information email

### Expected result (*)

1. The product price Should be $95 in the email. Same price as in order

### Actual result (*)

1. In the email customer will see the old price, that is different from price in order

- Product price in order:
![image](https://user-images.githubusercontent.com/51681379/107948179-2ae27e80-6f9c-11eb-93b6-efd108b454cb.png)

- Product price in shipment:
![image](https://user-images.githubusercontent.com/51681379/107948303-56656900-6f9c-11eb-9d96-2ee2d776edb6.png)

**Note:** In customer My Account->My Orders product price in shipment is also old:
![image](https://user-images.githubusercontent.com/51681379/107949496-04bdde00-6f9e-11eb-9684-b3b9d21e2a6b.png)

**Comment by engcom-Alfa** [comment]
Hi @chaikivskyi. Thank you for your report.

Why do you think that after the change in the price of the product from the admin, the price should not be changed in the basket?

Thanks!

**Comment by chaikivskyi** [comment]
> Hi @chaikivskyi. Thank you for your report.
> 
> Why do you think that after the change in the price of the product from the admin, the price should not be changed in the basket?
> 
> Thanks!

Because the price does not change for other types of products and it is incorrect in tracking information email when the price changes.

**Comment by chaikivskyi** [comment]
Yes, is still relevant.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40895` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
