### ISSUE TITLE
Custom admin URL not used for redirects

### ISSUE THREAD

**Issue by indefinitedevil** [magento/magento2#28187]
### Preconditions (*)

1. Magento 2.3.4-p1
2. PWA Frontend

### Steps to reproduce (*)

1. Enable custom admin URL in Admin / Admin Base URL
2. Set a custom admin URL in Admin / Admin Base URL that is different from the frontend base URL but still functions (or set the admin base URL to the frontend base URL and change the frontend one to something else): http://magento-backend.com/
3. Clear all caches, etc
4. Save a product

Frontend base URL: http://magento-frontend.com/
Admin base URL: http://magento-backend.com/

### Expected result (*)

1. Product saved
2. Remain on product edit page: http://magento-backend.com/admin/catalog/product/edit/id/5501/set/4/key/7a2a40a3b7a94bb5a343210dd5398ffd7a8b383c1707d1739edb3ff2a5175a18/type/simple/store/0/back/edit/

### Actual result (*)

1. Product saved
2. Redirected to frontend base URL: http://magento-frontend.com/admin/catalog/product/edit/id/5501/set/4/key/7a2a40a3b7a94bb5a343210dd5398ffd7a8b383c1707d1739edb3ff2a5175a18/type/simple/store/0/back/edit/

The reason that this is a particular issue for us is that the frontend URL in this case is a PWA and can't process Magento admin URLs.

**Comment by indefinitedevil** [comment]
admin/url/custom is only used in Magento\Backend\App\Area\FrontNameResolver

Magento\Framework\Url::getBaseUrl() always uses Magento\Store\Model\Store::getBaseUrl() which never references the custom admin URL.

**Comment by rsargsyan-incomm** [comment]
> ### Preconditions (*)
> 1. Magento 2.3.4-p1
> 2. PWA Frontend
> 
> ### Steps to reproduce (*)
> 1. Enable custom admin URL in Admin / Admin Base URL
> 2. Set a custom admin URL in Admin / Admin Base URL that is different from the frontend base URL but still functions (or set the admin base URL to the frontend base URL and change the frontend one to something else): http://magento-backend.com/
> 3. Clear all caches, etc
> 4. Save a product
> 
> Frontend base URL: http://magento-frontend.com/ Admin base URL: http://magento-backend.com/
> 
> ### Expected result (*)
> 1. Product saved
> 2. Remain on product edit page: http://magento-backend.com/admin/catalog/product/edit/id/5501/set/4/key/7a2a40a3b7a94bb5a343210dd5398ffd7a8b383c1707d1739edb3ff2a5175a18/type/simple/store/0/back/edit/
> 
> ### Actual result (*)
> 1. Product saved
> 2. Redirected to frontend base URL: http://magento-frontend.com/admin/catalog/product/edit/id/5501/set/4/key/7a2a40a3b7a94bb5a343210dd5398ffd7a8b383c1707d1739edb3ff2a5175a18/type/simple/store/0/back/edit/
> 
> The reason that this is a particular issue for us is that the frontend URL in this case is a PWA and can't process Magento admin URLs.

I am experiencing the same issue, was this resolved ?
