### ISSUE TITLE
We get an error everytime we select ship or print in magento and have to hit ok twice everytime to clear the error

### ISSUE THREAD

**Issue by bigjvt4** [magento/magento2#28190]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
Hello @bigjvt4,

I have reviewed the issue in the front end and admin section but I am not able to reproduce this issue.
Can you please share the video or send the proper steps to be reproduced?
I am not getting any of the errors on the ship or print in Magento.

Thanks.
