### ISSUE TITLE
Graphql products query returns only ids for dropdows or multiselect fields

### ISSUE THREAD

**Issue by maximilianmikus** [magento/magento2#28200]
### Preconditions (*)

1. 2.3.5-p1 with sample data

### Steps to reproduce (*)

1. u can use this magento instance (https://magento2.kask.at/graphql) or your own testing instance with sample data. query /graphql for a product that has the gender attribute (multiselect) e.g. "dual-handle-cardio-ball"
2. 
```
query productDetail($url_key: String) {
  productDetail: products(filter: {url_key: {eq: $url_key}}) {
    items {
      name
      url_key
      gender
    }
  }
}
```
variables:
```
{
  "url_key": "dual-handle-cardio-ball"
}
```

### Expected result (*)

1. 
I would expext the result to contain the labels

```
{
  "data": {
    "productDetail": {
      "items": [
        {
          "name": "Dual Handle Cardio Ball",
          "url_key": "dual-handle-cardio-ball",
          "gender": ["Men","Women","Unisex"]
        }
      ]
    }
  }
}
```

### Actual result (*)

1. 
the response only returns the value ids.

```
{
  "data": {
    "productDetail": {
      "items": [
        {
          "name": "Dual Handle Cardio Ball",
          "url_key": "dual-handle-cardio-ball",
          "gender": "5507,5508,5511"
        }
      ]
    }
  }
}
```

**Comment by maximilianmikus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by maximilianmikus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by maximilianmikus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by maximilianmikus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maximilianmikus. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maximilianmikus, here is your [Magento instance](https://i-28200-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28200-2-4-develop.instances.magento-community.engineering/admin_b3e5](https://i-28200-2-4-develop.instances.magento-community.engineering/admin_b3e5)
Login: `cf115cc0` Password: `32c908c14326`
Instance will be terminated in up to 3 hours.

**Comment by maximilianmikus** [comment]
I can confirm this happens on 2.4-develop

the query:
```
query productDetail($url_key: String) {
  productDetail: products(filter: {url_key: {eq: $url_key}}) {
    items {
      name
      url_key
      mycolor
      mysize
    }
  }
}
```
with variables
```
{
  "url_key": "simple-product-28"
}
```
yields
```
{
  "data": {
    "productDetail": {
      "items": [
        {
          "name": "Simple Product 28",
          "url_key": "simple-product-28",
          "mycolor": 6,
          "mysize": 9
        }
      ]
    }
  }
}
```
It should actually contain the labels. "my yellow" and "my large"

**Comment by mslabko** [comment]
It's really a good improvement however, unfortunately, it will bring breaking changes, so we cannot accept it for 2.4. (unless it will be approved)

Maybe we can do the following: mark all dynamic product attributes as deprecated and introduce an object that will hold all dynamic product attributes, something like 

```
dynamic_attributes: [
    {
       code
       value
       type // is it useful for rendering UI?
    }
]
```
Only one drawback that we need to support different types like texts, lists, float.. (we can see them in Admin => Store => Attributes => Product) and we can agree to have "value" as an array of strings which will cover all cases, however on the client-side we need to have something like value[0] each time for one-value attributes.

@DrewML what do you think about it?

**Comment by DrewML** [comment]
This is an interesting one! I believe we've discussed before that, ideally, we'd get rid of attributes as fields, since it makes breaking change detection and multi-store frontends difficult to do.

I believe the general idea has been to go with something like you've recommended @mslabko. Will probably take a little bit of back and forth, though, to flesh out the right design.

In the meantime, it seems like this reported issue (a `String` returning a comma-delimited list of IDs) certainly has to be a bug, which _may_ make it ok so fix in a non-major release.

Thoughts @nrkapoor?

**Comment by maximilianmikus** [comment]
I would like to kindly ask to make this high priority please - its really important otherwise product-information is not correctly displayed in the frontend. Could you maybe create a patch with some preliminary fix or something of the sort, while you sort out the better solutions. I tried doing this but lack deeper inside into the codebase to make it work.

**Comment by theshreyas** [comment]
For anyone stuck here, try [this quickfix](https://github.com/theshreyas/magento-2-quickies/tree/main/Graphql/DynamicAttributesGraphql) till its resolved in the core.

**Comment by maximilianmikus** [comment]
there was a typo in the link: https://github.com/theshreyas/magento-2-quickies/tree/main/GraphQl/DynamicAttributesGraphql

**Comment by hanxiangwu** [comment]
Hi there, is there a patch or solusion for this now? Thanks

**Comment by maximilianmikus** [comment]
/push

please set this to higher prio 🚀

**Comment by marwan-corals** [comment]
hello, any idea on this issue and when its expected to be fixed ?

**Comment by engcom-Charlie** [comment]
@cpartica, as you mentioned in JIRA [comment](https://jira.corp.magento.com/browse/AC-2796), that we need an approved schema for this one, and alignment with the pwa metapackage schema. This will take time and moving it to 2.4.6.

Hence moving the associated [PR](https://github.com/magento/magento2/pull/31622) to on Hold, until the further updates on JIRA.

**Comment by hanxiangwu** [comment]
Hi there, is there a patch or solusion for this now? Thanks

**Comment by GamesmenJordan** [comment]
Over 2 years and counting and still no good support for two entire fundamental attribute data types and the can continues to be kicked down the road.

**Comment by engcom-Charlie** [comment]
As mentioned in above https://github.com/magento/magento2/issues/28200#issuecomment-1134530825, we are doing follow up with team. We are waiting for the PO's input on the same. Once will get the clarity on that, we will proceed further on this.

Thank you!
