### ISSUE TITLE
Why I haven't Magento Connect ?

### ISSUE THREAD

**Issue by rokity** [magento/magento2#2820]
I want to install a extension from Magento Connect Marketplace in my Magento Community Edition.
Why I can't install an extension?? How can I install it ? I havent Magento Connect on my community edition.

**Comment by ghost** [comment]
We now have the Component Manager available from the Admin: see [the documentation](http://devdocs.magento.com/guides/v2.0/comp-mgr/compman-start.html).

However, Magento Marketplace (the new name for Magento Connect) is not generally available yet. In the meantime, you can probably install your Magento 2 extension by extracting it to app/code like you would a Magento 1 extension. Run `php bin/magento setup:upgrade` afterward to create any database tables.

Let us know if it works.

**Comment by rokity** [comment]
Component Manager doesnt work . I dont know why it doesnt work .
I already added some extension from https://www.magentocommerce.com/magento-connect/ and after this I synced Component Manager on my local server but it doesnt work.
