### ISSUE TITLE
Currency switcher not working with full page cache

### ISSUE THREAD

**Issue by flakerimi** [magento/magento2#28204]
### Preconditions (*)

1.Magento ver. 2.3.4
2. Theme: SM MARKET 

### Steps to reproduce (*)

1. Use product Listing block on Homepage
2. Add 2 currencies
3. Try to switch currency

### Expected result (*)

1. Change currency and price

### Actual result (*)

1. [Screenshots, logs or description]
2.<img width="592" alt="Screenshot 2020-05-13 at 00 02 54" src="https://user-images.githubusercontent.com/871482/81750067-21783300-94ad-11ea-9402-ce4275a0534d.png">

**Comment by flakerimi** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by flakerimi** [comment]
@magento give me 2.3 instance

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by flakerimi** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by flakerimi** [comment]
@sudheers-kensium 

If I make cache_lifetime 1

```
 protected function _construct()
    {
        parent::_construct();
        $this->addData(
            [
            'cache_lifetime' => 1,
            'cache_tags' => [self::CACHE_TAGS]]
        );
    }
```
it works but then block its not cached and it makes page slow.

**Comment by sudheers-kensium** [comment]
It is working as expected. Maybe issue with your custom theme, disable your custom theme check again.

**Comment by flakerimi** [comment]
Its not about theme, same in Luma, its about custom block when you enable cache
Create a custom block, get some products from category 

Add cache to Block

``` protected function _construct()
    {
        parent::_construct();
        $this->addData(
            [
            'cache_lifetime' => 1,
            'cache_tags' => [self::CACHE_TAGS]]
        );
    }
```

**Comment by flakerimi** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @flakerimi. Thank you for your request. I'm working on Magento 2.3-develop instance for you
