### ISSUE TITLE
Click on "Purchase Order" cause error in discount section

### ISSUE THREAD

**Issue by vovayatsyuk** [magento/magento2#28208]
### Preconditions (*)

1. Magento 2.3.5

### Steps to reproduce (*)

1. Enable "purchase order" and "check/money" payment methods
2. Navigate to checkout
3. Proceed to payment step and expand the discount block section
4. Change payment to "Purchase order"
5. An error will be added to the discount sectiton.

### Expected result (*)

1. I expect no errors at all because I just wanted to change payment method.

### Actual result (*)

1. Error is shown

<img width="607" alt="Знімок екрана 2020-05-13 о 16 45 58" src="https://user-images.githubusercontent.com/306080/81820404-40bca200-9539-11ea-8740-1aca35012636.png">

### Explanation
The issue is caused by the 'setPaymentInformationAction' request added to fix per-payment coupon discount: https://github.com/magento/magento2/commit/b6880b20e8cd7049d69f67cb5c8fb60e092384db#diff-aa8b012e2fbfb8f3c2904b7ea0504606

### Possible Solution
We need some "lightweight" version of [savePaymentInformation](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L118-L139) method that will work with minimum data and will not trigger any errors.

**Comment by vovayatsyuk** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by sudheers-kensium** [comment]
Issue is reproduced on Magento 2.3.5 and after few seconds error message is disappearing.
 
![image](https://user-images.githubusercontent.com/50358141/81833102-eb928780-955c-11ea-8059-e336bb5ae8cc.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34290` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by CarmineDamore78** [comment]
Issue not reproduced on Magento 2.3.4

**Comment by sudheers-kensium** [comment]
Issue is reproduced on Magento 2.3.5p1.

**Comment by balaji-pinpoint** [comment]
@magento I am working on this

**Comment by balaji-pinpoint** [comment]
@magento I am working on this

**Comment by engcom-Alfa** [comment]
The issue is reproducible on fresh 2.4-develop

![Peek 2020-08-03 14-22](https://user-images.githubusercontent.com/51679138/89177891-11945a80-d595-11ea-9780-4914df2afd2c.gif)

**Comment by monikav-dckap** [comment]
@magento give me 2.3.5.-p1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @monikav-dckap. Thank you for your request. I'm working on Magento 2.3.5.-p1-develop instance for you

**Comment by Surabhi-Cedcoss** [comment]
@magento i am working on this.

**Comment by Surabhi-Cedcoss** [comment]
#dmcdindia2020

**Comment by vovayatsyuk** [comment]
This issue is still relevant.

Additional note: when agreements are enabled you'll see the error about agreements when trying to change the selected payment method.

![image](https://user-images.githubusercontent.com/306080/107624501-a7efba00-6c63-11eb-899b-5219d7155246.png)

**Comment by vovayatsyuk** [comment]
This issue is still relevant. https://github.com/magento/magento2/issues/28208#issuecomment-777341425

**Comment by vovayatsyuk** [comment]
.

**Comment by engcom-Bravo** [comment]
Hi @vovayatsyuk,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/7a819a4f-d233-4073-bc71-64e80a811e6c



We are able to change the payment method.

Hence We are closing this issue.

Thanks
