### ISSUE TITLE
Tax_class_id won't update

### ISSUE THREAD

**Issue by jhouedanou** [magento/magento2#28203]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Go to Catalog > Products 
2. Select all the products
3. Click on actions 
4. Click on update attributes
5. Click on "tax class", change
6. Set it to "None"

### Expected result (*)

1.  All the product should have the tax class "None" 

### Actual result (*)

1.  Two products have the default tax  class . In the frontend they appear while one filters by the Tax Class and select "Taxable Goods" . On the database they have "2" as an value for the tax_class_id in the catalog_product_index_price table
![Annotation 2020-05-12 200508](https://user-images.githubusercontent.com/1837389/81740104-ef0a0e00-948b-11ea-9372-6383ef8fc924.jpg)

**Comment by lampham2141993** [comment]
Hi, @jhouedanou @magento-engcom-team,
I checked it on Magento 2.4-develop, and I can't replicate it.
@jhouedanou 
When you save for 'Update Attributes', one queue will be added to queue_message table

**Comment by jhouedanou** [comment]
Hi , so i've been trying the command to no avail. 

I've also tried

`php bin/magento cron:run`

All the attributes are modified, except those for the 2 products i've mentioned before. 
Is there anyway to harcode the 'tax_class_id" into the database ?  

I've tried to change the value of tax_class_id in the database 

UPDATE `catalog_product_index_price` SET `tax_class_id` = 0 WHERE `tax_class_id` = 2;
UPDATE `catalog_product_index_price_idx` SET `tax_class_id` = 0 WHERE `tax_class_id` = 2;
UPDATE `catalog_product_index_price_tmp` SET `tax_class_id` = 0 WHERE `tax_class_id` = 2;


```
But it goes back from 0 to 2.

**Comment by engcom-Delta** [comment]
Hello @
Hello @jhouedanou @lampham2141993 
Could you provide more details for reproduce this issue?
How many products do you have?
Did this issue occur after the upgrade?

Thank you!

**Comment by jhouedanou** [comment]
Hello @engcom-Delta 
How are you ?

Could you provide more details for reproduce this issue?

- _Go to Catalog > Products
- Select all the products
- Click on actions
- Click on update attributes
- Click on "tax class", change
- Set it to "None"_
- 
I've also tried
php n98-magerun2.phar sys:cron:run consumers_runner
 and a reindex,

and also 
php bin/magento cron:run

All the attributes are modified, except those for the 2 product.
I've tried to change the value of tax_class_id in the database

UPDATE catalog_product_index_price SET tax_class_id = 0 WHERE tax_class_id = 2;
UPDATE catalog_product_index_price_idx SET tax_class_id = 0 WHERE tax_class_id = 2;
UPDATE catalog_product_index_price_tmp SET tax_class_id = 0 WHERE tax_class_id = 2;

How many products do you have?

_392 products. Only 3 products are concerned by this issue_

Did this issue occur after the upgrade?

No, it happened on magento 2.3.4

Quick question  : 
Is there anyway to harcode the 'tax_class_id" into the database ?

**Comment by engcom-Delta** [comment]
Hello @jhouedanou 
Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop.
I using RabbitMQ.
I`m run this commands as described [here](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-queue.html):

`bin/magento queue:consumers:list`
`bin/magento queue:consumers:start async.operations.all &`
Also clear cache and run cron (twice)

**Comment by krishprakash** [comment]
Hello @jhouedanou. Feel free to reopen the issue once you confirm that issue is reproduce on latest 2.4-develop instance
Thanks!!
