### ISSUE TITLE
Error on setup, /setup/index.php/navigation 404 not found

### ISSUE THREAD

**Issue by novazz** [magento/magento2#28217]
The setup page doesn't display correctly, it's almost blank. The browser console tells me:
/setup/index.php/navigation
/setup/index.php/navigation/side-menu
/setup/index.php/navigation/header-bar
/setup/index.php/session/prolong
not found
this issue: https://github.com/magento/magento2/issues/2504 doesn't seem to work for me
and i really don't know how to modify nginx.conf even if i copy configurations from nginx.conf.sample
can anyone help? this problem almost drive me crazy

magento: 2.3.5p1
centos7
php7.3
nginx1.16.1

**Comment by magento-engcom-team** [comment]
@magento-engcom-team Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@magento-engcom-team Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by novazz** [comment]
i hvae solved this problem by changing upstream from unix:/var/run/***fpm.sock to 127.0.0.1:9000
i don't know how can others configure such upstream, i search my entire disk and found no any *fpm.sock file
