### ISSUE TITLE
Feature Request: Static Asset Application: 404 Text for Production Mode

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2821]
If Magento 2 is in production mode, and a user requests a static asset file that does not exist

```
$ curl -i 'http://magento.example.com/static/frontend/Magento/blank/en_US/Pulsestorm_FrontendTutorial1/hello.js'
HTTP/1.1 404 Not Found
Date: Sun, 27 Dec 2015 20:30:30 GMT
Server: Apache/2.4.10 (Unix) PHP/5.6.16
X-Powered-By: PHP/5.6.16
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: text/html; charset=UTF-8
```

Magento 2 will correctly return a 404 header.  **However**, Magento 2 also returns a **blank** HTML page.  

Magento 2, in addition to returning the correct `404 header`, should also return some sort of standard "Error 404" text.  It's very common for end-users to debug missing Javascript/CSS files by loading them in the browser (which doesn't display obvious status headers), and most web servers are configured (even in production mode) to return an appropriate human readable response.  A blank page will read as a PHP error to most developers, and will create a lot of wasted time/frustration when learning and/or debugging the system.

**Comment by pboisvert** [comment]
@piotrekkaminski Piotr--passing to you as this seems like a dev experience issue. If not please reassign as needed.

**Comment by piotrekkaminski** [comment]
The bug is now in the backlog as MAGETWO-52671.

**Comment by astorm** [comment]
No update here since May.  Assuming this developer experience issue isn't a priority and closing out.
