### ISSUE TITLE
production mode (both with/without compilation) doesnt load css and js 

### ISSUE THREAD

**Issue by gonorovsky** [magento/magento2#2822]
After installing Magento 2 with "One click image" on Digital Ocean (Ubuntu 14.04, Apache 2.4) cant bring it to PR mode: without compilation - doesnt load  CSS and JS (console: Failed to load resource: the server responded with a status of 404 (Not Found)); with compilation - 500 server error (sys log: magento2 Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively).
Dev mode works fine.

**Comment by ishakhsuvarov** [comment]
@gonorovsky Please try to deploy static view files using `bin/magento setup:static-content:deploy` CLI command.

You may find more information on this in the [Deploy static view files](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html) section of the developer documentation.

**Comment by gonorovsky** [comment]
I did it hundred times, with differentorders.

**Comment by gonorovsky** [comment]
Thanks for support. it started working after solving the issue with ownership and rights.
