### ISSUE TITLE
Tier Price import runs too long

### ISSUE THREAD

**Issue by DarthFly** [magento/magento2#28225]
### Preconditions (*)

1. Magento 2.4-develop
1. Magento 2.3.5-p1 or probably any version.
2. Assuming that we importing a lot of tier prices. I have a file with 32k rows, but for test reasons, we can use any file with more than 100 values.

### Steps to reproduce (*)

1. Take import file and try to run import on it - System > Data Transfer > Import > Advanced Prices.
2. Behaviour - append.
3. If you can use debugger set breakpoint at vendor/magento/module-advanced-pricing-import-export/Model/Import/AdvancedPricing.php:417. Line should be this:
`$this->saveProductPrices($tierPrices, self::TABLE_TIER_PRICE);`

### Expected result (*)

1. Import is run and finished in the same amount of time

### Actual result (*)

1. Import takes ~14h for 32k rows file.

If you have setup breakpoint as suggested you can validate how several bunches are generated. After first bunch `$tierPrices` variable will contain some amount of skus. After the second bunch - same variable will contain same sku + new skus from previous bunch, growing again and again in each iteration, even when previous bunch was already saved and inserted. Inside `saveProductPrices` magento iterate inside this array, so it repeat iteration around 10 million times for me.
Reason: because magento never clear $tierPrices array inside iteration.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40257` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dverkade** [comment]
Confirmed issues can't be closed automatically.
