### ISSUE TITLE
Graphql request setShippingAddressOnCart fails when sending customer_address_id

### ISSUE THREAD

**Issue by leroynas** [magento/magento2#28228]
### Preconditions (*)

1. Magento 2.3.4(release)

### Steps to reproduce (*)

1. [graphql] create cart
2. [graphql] create customer token
2. [graphql] create customer address
3. [graphql] run setShippingAddressOnCart with the address id (`customer_address_id`)

### Expected result (*)

1. Success message

### Actual result (*)

```
{
    "errors": [
        {
            "message": "\"regionId\" is required. Enter and try again.",
            "extensions": {
                "category": "graphql-input"
            }
        }
    ],
    "data": {
        "store": null
    }
}
```

According to the graphql docs "regionId" is depricated.

**Comment by leroynas** [comment]
I reproduced this issue on a clean Magento 2.3.4 installation.

**Comment by leroynas** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @leroynas. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @leroynas, here is your [Magento instance](https://i-28228-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28228-2-4-develop.instances.magento-community.engineering/admin_bdba](https://i-28228-2-4-develop.instances.magento-community.engineering/admin_bdba)
Login: `4d08ae86` Password: `ac44d23ba950`
Instance will be terminated in up to 3 hours.
