### ISSUE TITLE
Initial Page Slowness for Configurable products

### ISSUE THREAD

**Issue by Techytt** [magento/magento2#28226]
### Summary (*)

Hello Team,
We are experiencing the following critical core Magento performance issue.
Issue: Redirection taking more time from listing page to PDP page
Detail: Navigating from PLP to PDP taking average 11-17 sec on first load for the configurable products only.
Note: We have configurable products which has average 7-10 child associated
Kindly share thought to improve performance in this case

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @Techytt thank you for your report. I checked issue on 2.4-develop and  I get next results:

- Time of first product detail page load is 2.63s.
![image](https://user-images.githubusercontent.com/51681379/102996117-2a44e300-452b-11eb-80a0-31a3c679901d.png)


- Time of first product detail page load is 1.34s if configurable is without images
![image](https://user-images.githubusercontent.com/51681379/102999481-bd811700-4531-11eb-883b-c0ae4e5289a9.png)

Looks like there is no performance issue that you describe on 2.4-develop.

Do you experience this issue on 2.4-develop?

**Comment by Techytt** [comment]
@engcom-Delta Can you please check with more child options?
We have around 10-12 child products.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@Techytt I rechecked page load with 30 child products of configurable product but didn't get such perfomance degradation you mention in issue
**Manual testing scenario:**

- Create configurable product with two attributes (with 5 options and 6 options)
![image](https://user-images.githubusercontent.com/51681379/105847332-27378980-5fe6-11eb-9473-26e0bafdf7f1.png)

- Flush cache
- Open category page with configurable product
- Go to configurable product detail page

**Result:**
:heavy_check_mark: Page load is 1.21s
![image](https://user-images.githubusercontent.com/51681379/105847174-ee97b000-5fe5-11eb-80f5-e6a809a8db63.png)

Are you able to reproduce this issue on the vanilla Magento instance?

**Comment by ParimalSigma** [comment]
Hello @engcom-Delta,

I have checked this in vanila magento and I am able to reproduce this issue, please see this screenshot for reference:

![slowness](https://user-images.githubusercontent.com/19204773/107315098-0843f780-6abc-11eb-852b-23a81c629ce9.png)

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@ParimalSigma Did you check page loading with disable cache?

**Comment by ParimalSigma** [comment]
@engcom-Delta no, I am checking by enabling cache only
