### ISSUE TITLE
Product import: Only the first additional image is validated

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#28236]
### Preconditions (*)
1. Magento 2.3.5
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Import a product with multiple additional_images set where the second image is invalid (has spaces or parentheses)
- file contains broken path of second image `/1/1/1 11*2.jpg` instead of correct `/1/1/111*2.jpg`

[import*break_add_image.csv.txt](https://github.com/magento/magento2/files/5638527/import_break_add*image.csv.txt)

### Expected result (*)

1. All additional images should be validated

### Actual result (*)

1. Only the first image is validated because the loop exists after the first pass
![image](https://user-images.githubusercontent.com/51681379/101078987-8c0ad080-35af-11eb-9e04-85bd6ff5cf05.png)

This is the cause of problem: https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php#L118
Only the first additional image gets validated because the loop has a `break;` at the end. It should probably just be removed.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28236-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28236-2-4-develop.instances.magento-community.engineering/admin_a227](https://i-28236-2-4-develop.instances.magento-community.engineering/admin_a227)
Login: `2be2dc49` Password: `7d7bac35c4ee`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me a 2.3.5-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39609` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
