### ISSUE TITLE
facing issue while installing extension 

### ISSUE THREAD

**Issue by AsadAli2567** [magento/magento2#28233]
this is the issue i am facing i have purchased new extension i want to install that  but before this i had used this (m2-weltpixel -quickview ) extension with different account  but now it makes me trouble its  not letting me install new extension  

Command "show" failed: In Git.php line 379: Failed to execute git clone --mirror 'git@github.com:rusdragos/m2-weltpixel -quickview.git' '/var/www/html/var/composer_home/cache/vcs/git-github.com-r usdragos-m2-weltpixel-quickview.git/' show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [--ignore IGNORE] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package> [<version>]]

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by sudheers-kensium** [comment]
@AsadAli2567 This is not related to the Magento core issue. Please contact your extension vendor customer support.

I am closing this issue.
