### ISSUE TITLE
The $productId variable in the final_price.phtml is declared but never used

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2823]
https://mage2.pro/t/353

**Comment by liam-wiltshire** [comment]
PRs https://github.com/magento/magento2/pull/2829 and https://github.com/magento/magento2/pull/2828

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
