### ISSUE TITLE
Update endroid/qr-code constraint in msp/twofactorauth for PHP 7.3

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#28234]
When running Magento 2.3.5-p1 on PHP 7.3, the `friendsofphp/php-cs-fixer` package cannot be installed.

This is because [its constraint](https://packagist.org/packages/friendsofphp/php-cs-fixer) on `symfony/options-resolver` is `^3.0 || ^4.0 || ^5.0`.

But Magento also depends on `msp/twofactorauth`, which depends on `endroid/qr-code:^2.5`. endroid/qr-code 2.5.1 in its turn relies on `symfony/options-resolver:^2.7`, see [here](https://packagist.org/packages/endroid/qr-code#2.5.1).

So if we update the version constraint in `msp/twofactorauth` to use `endroid/qr-code:^3.0`, we can again install `friendsofphp/php-cs-fixer` while running PHP 7.3.

This problem does not occur on PHP 7.2 since `friendsofphp/php-cs-fixer:^2.2` is compatible with PHP 7.2, see [here](https://packagist.org/packages/friendsofphp/php-cs-fixer#v2.2.20).

**Comment by srsathish92** [comment]
@sidolov Facing the same issue in 2.3.5-p2
