### ISSUE TITLE
Occasionally getting JSON strings on category pages

### ISSUE THREAD

**Issue by dyuk1987** [magento/magento2#28237]
We have encountered this issue on a few different Magento projects. We understand we may not have sufficient information or very clear procedures for reproducing the issue, but as this turned out to be quite annoying and we have no clue about the root cause at all, we still decided to raise this here. And we have seen similar issues on StackOverflow.
1. https://magento.stackexchange.com/questions/296351/magento-2-intermittent-cache-issue-showing-a-json-code-instead-of-homepage
2. https://magento.stackexchange.com/questions/296944/magento2-category-page-cached-as-json-data-in-varnish

### Preconditions (*)

**Case 1:**
1. Magento 2.2.10 on AWS
2. Varnish 4.0.5

**Case 2:**
1. Magento 2.2.5 on Azure
2. Varnish 4.0.5

### Steps to reproduce (*)

1. Browse any category page
2. Reach a cached page with JSON strings **occasionally**

### Expected result (*)

1. Show a normal category page

### Actual result (*)

1. Reach a cached page with JSON strings **occasionally**

![varnish_bug](https://user-images.githubusercontent.com/28293734/82027265-8bb7f000-96c6-11ea-9184-915965967799.jpeg)

It happened (seemingly) randomly, and after restarting the varnish service, the issue would be gone.

**Comment by jbclaudio** [comment]
I've exact the same issue at some specific category pages. Has anyone find a solution?

**Comment by pinedamg** [comment]
I'm experiencing the same issue here, I thought it was the Amasty Extension Layered Navigation, but is still happening without the extension, definitely is something related with Varnish and Magento Core, and clearly this happens on a random way, and there is not a pattern or clue about how to reproduce it.

Does someone have any clue about it? thank you very much in advance.

![Selection_039](https://user-images.githubusercontent.com/818713/89448846-92d32500-d72e-11ea-8b4d-b9556561c021.png)

**Comment by jbclaudio** [comment]
I have found the cause and the solution. The cause is that when Varnish is cleared and a user comes to a filtered page first, the JSON is cached. I have excluded this for Varnish and this solved the problem.

**Comment by dyuk1987** [comment]
> I have found the cause and the solution. The cause is that when Varnish is cleared and a user comes to a filtered page first, the JSON is cached. I have excluded this for Varnish and this solved the problem.

@jbclaudio 
O-M-G finally someone came up with a solution!
That's some amazing findings there mate.
Do you mind sharing the VCL rules you have added?

**Comment by ZIPITRO** [comment]
> I have found the cause and the solution. The cause is that when Varnish is cleared and a user comes to a filtered page first, the JSON is cached. I have excluded this for Varnish and this solved the problem.

Wow, great job! Would you please share with us your VCL rules?

**Comment by pinedamg** [comment]
> I have found the cause and the solution. The cause is that when Varnish is cleared and a user comes to a filtered page first, the JSON is cached. I have excluded this for Varnish and this solved the problem.

@jbclaudio That sounds great, but I'm curious because I've tried disabling Varnish and this still happening, are you completely sure is fixed? Did you were able to reproduce the issue to verify if the fix is real? I would like to think that you are our savior in this very rare issue :P, and as our bug-mates said, please could you show us that portion of the VCL file?, thanks

**Comment by dyuk1987** [comment]
> I have found the cause and the solution. The cause is that when Varnish is cleared and a user comes to a filtered page first, the JSON is cached. I have excluded this for Varnish and this solved the problem.

On second thought, I could not figure out the relationship between the filtered page and the unfiltered page.
Aren't those filtered pages standalone cache entries in Varnish?

And I tried to follow your findings, but still could not find a way to 100% reproduce the issue as well.
Could you please also advise how you could do that?

**Comment by jbclaudio** [comment]
I've added this to the .vcl file:
```
    if (req.url ~ "shopbyAjax") {
        return (pass);
    }
```

This project uses the Amasty Shopby module. It adds the parameter to the filter pages, which I could use. You may be able to use another parameter that Magento itself adds.

After this has been added to the .vcl file, the problem no longer occurs.

**Comment by TJEliot** [comment]
I just encountered this and was able to quickly resolve it, so I thought I would share my solution here: I just reran the `catalog_product_category` and `catalog_category_product` indexers

**Comment by dwestvik** [comment]
This happened, today, on our site and don't have Amasty.

**Comment by Daniel304** [comment]
Same here... I do found out that it is a combination of google pagespeed and varnish in my case.. and it is only on specific category pages... Really strange behaviour

**Comment by jsamhall** [comment]
Encountered this issue today on a category with many products. Clearing block_html cache resolved the issue.

We are NOT using Varnish and instead just Magento built-in FPC, so the issue is not specific to Varnish, nor the Amasty ShopBy module.

We are however, using Smile's ElasticSuite which results in all categories being treated as Layered Navigation categories.

Perhaps layered navigation, Elasticsearch and Magento's FPC are the culprit here?

Very scary issue to encounter "randomly" with no means of testing / troubleshooting / workaround besides from regularly cleaning of block cache.... obviously not desirable for performance.... but the lesser of two evils for sure!!!

**Comment by Claudiusdev** [comment]
I've he same issue at some specific category pages. Has anyone find a solution?

**Comment by kronthto** [comment]
The JSON response can be triggered by requesting the category-page with the header `X-Requested-With:
XMLHttpRequest` only, no other parameters. 
The response includes a `Content-Type: application/json` but no `Vary` for that, this in theory allows a cache to use it in place for the same URL requested as html.
Built-in FPC likely adheres to similar rules.

**Comment by aaubets** [comment]
> The JSON response can be triggered by requesting the category-page with the header `X-Requested-With: XMLHttpRequest` only, no other parameters. The response includes a `Content-Type: application/json` but no `Vary` for that, this in theory allows a cache to use it in place for the same URL requested as html. Built-in FPC likely adheres to similar rules.

This is the key!

I've the same issue after enabling multiple currencies in my site (2.3.5 + varnish + apache), randomly this error appears in random categories.

Adding:

`if (req.http.X-Requested-With) {
        hash_data(req.http.X-Requested-With);
}`

to vcl_hash solve the problem for me.
