### ISSUE TITLE
Customer login aur add cart link some time working sometime showing invalid form key issue

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#28243]
### Preconditions (*)

1. Magento 2.3.5-p1
2. my site url like http://ip-address/~test/stage

### Steps to reproduce (*)

1. tried to login as customer but not working and showing message Invalid Form Key. Please refresh the page.
2. tired to add to cart but it showing Invalid Form Key. Please refresh the page.

### Expected result (*)

1. [Screenshots, logs or description]
2. it should be login as customer and add to cart button add product always in any condition.

### Actual result (*)

1. [Screenshots, logs or description]
2.Invalid Form Key. Please refresh the page. showing

**Comment by shikhamis11** [comment]
@hemendraajmera thank you for reporting this issue. On your website did you install any additional caches? Also try to reproduce the issue at magento instances and share screenshots

**Comment by hemendraajmera** [comment]
I tried couple of times on same. and i haven't installed new caches or extension on instance.

**Comment by hemendraajmera** [comment]
Any updates on issue

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera, here is your [Magento instance](https://i-28243-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28243-2-4-develop.instances.magento-community.engineering/admin_9aef](https://i-28243-2-4-develop.instances.magento-community.engineering/admin_9aef)
Login: `eb448276` Password: `ba6524c05916`
Instance will be terminated in up to 3 hours.

**Comment by hemendraajmera** [comment]
@shikhamis11 any updates on issue or intermediate solution ASAP

**Comment by shikhamis11** [comment]
Hi @hemendraajmera , the root cause of the issue is that the top level domain is missing at Magento installation url

**Comment by shikhamis11** [comment]
Also can you let me know which browser you are using ? 
Try with firefox as I experienced same issue with chrome but that works fine with firefox

**Comment by hemendraajmera** [comment]
Okay, I am trying chrome but it not working.
 I already using a domain name instead of an IP address.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @hemendraajmera thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Admin is able to login as customer without errors
:heavy_check_mark: Admin is able to add products into cart as logged customer without errors
![Peek 2021-01-04 20-35](https://user-images.githubusercontent.com/51681379/103567823-28850300-4ecd-11eb-8147-7939e17b792d.gif)

If you'd like to update the issue, please reopen it.
