### ISSUE TITLE
[NOT READY] GraphQL fields shouldn't optional in schema.

### ISSUE THREAD

**Issue by paales** [magento/magento2#28257]
### Preconditions (*)
1. Latest dev branch.

### Steps to reproduce (*

Take a look at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls

### Expected result (*)

For example:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L86
`id: Int!`

This is happening all over the codebase and should be changed by making all nonnullable fields actually nonnullable.

### Actual result (*)
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L86
`id: Int`

I'm using GraphQL Code Generator to create typescript definitions from the codebase, but this is causing major issues when using the endpoint.

**Comment by paales** [comment]
@cpartica Great to see you're picking this up!

I think you should change something like:

'Same service' fields:

These fields come directly from the service and will not be distributed to multiple services.

- All 'Same service' fields should be required (e.g. https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L86)
- Relation fields should be required: (e.g. https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L109) `[Website!]!`

'Related service' fields:

These fields may be delegated to a different service somewhere in the future.

- All other service fields should be optional
- Relation lists should be optional, but strict in type (e.g. https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/WeeeGraphQl/etc/schema.graphqls#L10), should become `[FixedProductTax!]`

Does that make sense?

**Comment by DrewML** [comment]
Thanks for opening this up @paales! @cpartica and I were talking on Slack a bit about this earlier, because the question of nullability has come up _a lot_ lately in PR reviews between myself and @paliarush.

I've been meaning to throw up a document for review with some rough guidelines for us to follow moving forward - at least as a starting place. This issue pushed me to finally get that going

https://github.com/magento/architecture/pull/392

Would appreciate your review and input - it seems like we have pretty similar thoughts!

**Comment by cpartica** [comment]
While I did not actually worked on this, but Git said I was, found this interesting comment that explains some situations why we should not add mandatory non nullable to anything [FixedProductTax!] or [Website!]!
Also good for extensibility
https://github.com/magento/architecture/pull/381#discussion_r431408317

**Comment by engcom-Hotel** [comment]
Hello @paales,

Thank you for your report.

We have checked line no 86 mentioned in the main description, but it seems that the attached file has been updated. We request you to please review the description.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @paales,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
