### ISSUE TITLE
Problem setting payment method using REST Api

### ISSUE THREAD

**Issue by pcobas** [magento/magento2#2825]
We’re not being able to set a payment method for a cart using the REST API.

After creating the quote and adding items, and setting shipping information, we call the method to get the available payment methods for the quote ( /rest/V1/carts/26/payment-methods )

Then we call the method to select the payment method (/rest/V1/carts/26/selected-payment-method ) , but is responding that the payment method is not available.

I’ve checked the configuration for the payment method and is enabled and available for all countries.

Any idea why this happens?

Response from GET /rest/V1/carts/26/payment-methods

[

```
{

    "code": "checkmo",

    "title": "Check / Money order"

},

{

    "code": "free",

    "title": "No Payment Information Required"

}
```

]

Request to PUT /rest/V1/carts/26/selected-payment-method

{

  "cartId":26,

  "method": {"method":"free"}   

}

Response from PUT /rest/V1/carts/26/selected-payment-method

{

  "message": "The requested Payment Method is not available.",

  "trace": "#0 /home/www/test2/vendor/magento/module-quote/Model/PaymentMethodManagement.php(68): Magento\Quote\Model\Quote\Payment->importData(Array)\n#1 [internal function]: Magento\Quote\Model\PaymentMethodManagement->set(26, Object(Magento\Quote\Model\Quote\Payment))\n#2 /home/www/test2/vendor/magento/module-webapi/Controller/Rest.php(265): call_user_func_array(Array, Array)\n#3 /home/www/test2/vendor/magento/module-webapi/Controller/Rest.php(160): Magento\Webapi\Controller\Rest->processApiRequest()\n#4 /home/www/test2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))\n#5 /home/www/test2/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#6 /home/www/test2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()\n#7 /home/www/test2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))\n#8 {main}"

}

**Comment by ishakhsuvarov** [comment]
@pcobas Payment method `Free` may only be used for carts with zero total. Please try same scenario with another payment method like `Check / Money order` or apply discounts to the quote, which will bring total to 0.

**Comment by pcobas** [comment]
Thanks, it worked.
