### ISSUE TITLE
Graphql createCustomerAddress mutation region mandatory

### ISSUE THREAD

**Issue by leroynas** [magento/magento2#28253]
I would expect region to not be mandatory on the createCustomerAddress mutation. When submitting this mutation without region, there is no issue. When you try to run the setShippingAddressesOnCart mutation, with the just created customerAddress (keep in mind to use the `customer_address_id` param and submit the Authorization header) it should work. The result is actually an error message stating: "regionId is required. Enter and try again.".

### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Run createCustomer mutation
2. Run createCustomerAddress mutation (leave region out)
3. Run createEmptyCart mutation (with auth header)
4. Run addSimpleProductsToCart mutation (with auth header)
5. Run setShippingAddressesOnCart mutation (with auth header)

### Expected result (*)

1. Since the customer address is exists I would expect the customer address to be added to the cart (same result as with region).

### Actual result (*)

1. Error message stating: "regionId is required. Enter and try again."

**Comment by leroynas** [comment]
Yes this issue is present on the magento 2.4-develop branch

**Comment by marciomaciel** [comment]
@nrkapoor Are you also creating the backport for 2.3 or just the fix for 2.4?

**Comment by michalderlatka** [comment]
@nrkapoor I'm not able to reproduce this issue on 2.4-develop.
If country has defined regions, createCustomerAddress fails when no region_id is passed
If country has no regions, it is possible to pass empty region

setShippingAddressesOnCart works properly on both scenarios
