### ISSUE TITLE
Our Daily Counts will not load

### ISSUE THREAD

**Issue by cfriedm** [magento/magento2#28258]
### Preconditions (*)

1. when i click on REPORTS and try to run our DAILY COUNTS i am getting nothing
2. i have cleared all CACHES but that has not worked

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by cfriedm** [comment]
hello.

I need to generate the DAILY REPORTS report, but get a blank screen when I select today’s date.

I have a good connection to wifi.

Something needs to be done on the back end.

I want to generate the report.

thanks.

				
Cleetus Friedman		•		Executive Chef		
t. 312.402.0221		|		e. cleetus@kitchfix.com <mailto:cleetus@kitchfix.com>				
 <http://www.facebook.com/cjkfoods>		 <http://www.twitter.com/kitchfix>		 <http://www.instagram.com/kitchfix>

**Comment by magento-engcom-team** [comment]
Hi @cfriedm. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cfriedm, here is your [Magento instance](https://i-28258-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28258-2-4-develop.instances.magento-community.engineering/admin_0139](https://i-28258-2-4-develop.instances.magento-community.engineering/admin_0139)
Login: `2750f462` Password: `18fc4528ddf9`
Instance will be terminated in up to 3 hours.

**Comment by cfriedm** [comment]
Thank you for this, but I can’t view our reports with this login information
				
Cleetus Friedman		•		Executive Chef		
t. 312.402.0221		|		e. cleetus@kitchfix.com <mailto:cleetus@kitchfix.com>				
 <http://www.facebook.com/cjkfoods>		 <http://www.twitter.com/kitchfix>		 <http://www.instagram.com/kitchfix>

**Comment by engcom-Delta** [comment]
Hello @
Could you provide more details for reproduce this issue?
Please add steps to reproduce and version of magento. 
Do you use third-party extensions for reporting?

Thank you!

**Comment by krishprakash** [comment]
Hi @cfriedm. Thank you for your report.
Feel free to reopen once you update reproducible steps and other all require details to reproduce this issue
