### ISSUE TITLE
Admin, product edit , tab Configurations, pagination 

### ISSUE THREAD

**Issue by majidiyan** [magento/magento2#28265]
Hello
I found a bug in Magento 2.3.5 and want to report it.
I created a configuration product with 200 child products.
The bug is in admin product page, when I wanted to use configurable product pagination.
I put "20 products per page".
The first page is showing 20 first products, this is ok, but when I clicked next arrow, it showed me all reminder 180 products and it takes so many times and my browser crashed for three times.

Please improve this bug.

Best regards !

**Comment by ajijshekh123** [comment]
@majidiyan - Please add your bugs in the below Magento Issue reporting guidelines.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-28265-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28265-2-4-develop.instances.magento-community.engineering/admin_6e4f](https://i-28265-2-4-develop.instances.magento-community.engineering/admin_6e4f)
Login: `7027ed62` Password: `683e0e1e3b2c`
Instance will be terminated in up to 3 hours.

**Comment by majidiyan** [comment]
Hello
If you make a configurable product with 200 children , then you will see the pagination works incorrectly.

**Comment by majidiyan** [comment]
For example: I made a  configurable product by the name of "test1" and  used 2 product attributes:
majidian_color, majidian_size.
Please go to admin and see this configurable product and check the pagination (Configurations tab)

**Comment by rswitala** [comment]
We have the same bug on versions 2.3.3, 2.3.4 and 2.3.5
On clean Magento installations

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment]
Hello @majidiyan,
I have reviewed this issue as per your details. 
**Scenario 1:**
When I have to Update the Pagination "20" to "200" products count My browser is stuck for few minutes and I can't able to any action for this page but after few seconds it works normally.
**Scenario 2:**
I have to change the Pagination "20" to "5" and review the product list. It's working fine on the latest Magento 2.4 instance.
See attached the video:

![Untitled_ May 27 2020 12_41 PM](https://user-images.githubusercontent.com/24711761/82989479-64431a80-a018-11ea-9b40-b5a7bed12761.gif)

Thanks.

**Comment by ajijshekh123** [comment]
Hello @majidiyan,
This issue is not reproduced in the Latest Magento Instance as per the given steps, actual result and expected result.
please update description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)  and we will reopen it"

Thanks.

**Comment by majidiyan** [comment]
The problem in on left arrow and right arrow of the pagination.
Make 200 children in a configuration product, put number of show in a page on 20 and try to come from page one to page two, you will see it is so slow and crashes your browser.

**Comment by majidiyan** [comment]
> We have the same bug on versions 2.3.3, 2.3.4 and 2.3.5
> On clean Magento installations
> ![grid](https://user-images.githubusercontent.com/9656885/82558465-fad19080-9b6d-11ea-942f-dae48f0cb4f5.gif)

Dear friend, please explain them what I'm saying, they refused my ticket.

**Comment by majidiyan** [comment]
> We have the same bug on versions 2.3.3, 2.3.4 and 2.3.5
> On clean Magento installations
> ![grid](https://user-images.githubusercontent.com/9656885/82558465-fad19080-9b6d-11ea-942f-dae48f0cb4f5.gif)

Dear friend, please explain them what I'm saying, they refused my issue.

**Comment by ajijshekh123** [comment]
Hello @majidiyan,
I am talking about the Magento Issue format. Please follow the Magento Issue reporting guideline.
See the link:
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Let me verify this issue again and update you.
Thanks for the Update.
