### ISSUE TITLE
Add to cart Doesn't work on Magento 2.3.4 RTL - ar language

### ISSUE THREAD

**Issue by nerminleap13** [magento/magento2#28263]
I have Magento 2.3.4 With two store view for two language the English one working well but in Ar view the Add to cart button doesn't work, I think the issue doesn't related to the RTL but its related to the language ar_SA please advice
### Preconditions (*)

1. Magento v : 2.3.4
2. RTL
3. Language ar_SA
4. PHP 7.3
5. Use RTL Pro Theme and choose ar_SA locale option
6. I have to store view en_US & ar_SA

### Steps to reproduce (*)

1. Open Category page and click on Add to cart button.
2. Open Product Page (simple/configurable) Add to cart button.
3. Trying different widget with different product list and click on Add to cart 

### Expected result (*)

1. Adding the product to my shop cart
2. Cart Icon has 1 product to be like the n store Its added to en_US store view and going to my cart fond new product added
![Add to cart issue](https://user-images.githubusercontent.com/49684695/82224614-59a3c980-9924-11ea-8777-d03f8c903c01.png)

### Actual result (*)

1. the page loading without any response 
![Comfy_Bag_Punto_Leather_](https://user-images.githubusercontent.com/49684695/82227645-5c082280-9928-11ea-8ea7-0bbd62d418ec.png)

2.

**Comment by andrewbess** [comment]
Hello @nerminleap13 
Are you sure that this problem is the Magento problem and not third-party theme problem?

**Comment by nerminleap13** [comment]
Hello,
Theme support told me that is an issue on Magento 2.3.4 and I should open an issue on Github, could you advice me please.

**Comment by nerminleap13** [comment]
Hello,
Its fixed, It was something wrong on my editing the currency view 
Thank you
