### ISSUE TITLE
Sales > order not updating automatically

### ISSUE THREAD

**Issue by muzzamal** [magento/magento2#28267]
My magento 2.3 sales > orders are not updating automatically. I have to run cron:run command and than refresh sales > orders page to see the new orders.

**Comment by engcom-Delta** [comment]
Hi @muzzamal reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are facing this issue on the latest `2.4-develop` branch. 
Thank you for collaboration.
