### ISSUE TITLE
Out of Stock Configurable Products Show in Catalog & Search (MSI)

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#28269]
### Preconditions (*)

1. Magento 2.3.5-p1
2. Set Magento to not show out of stock products
3. MSI should be enabled

### Steps to reproduce (*)

1. Create a configurable product with a child (simple) product in stock
2. Place an order that will cause the child (simple) product to have 0 salable quantity
3. Keep the order in processing mode so the source store still has quantity in stock (salable quantity will remain 0) 

### Expected result (*)

1. The configurable product should not show in the catalog (category pages) since it has no salable quantity (out of stock)
2. The configurable product should not show in search since it has no salable quantity (out of stock)

### Actual result (*)

1. The configurable product shows in the catalog
2. The configurable product shows in search

P.S. If you open the product page then it does show correctly as out of stock product.

**Comment by engcom-Delta** [comment]
Hi @uandiweb , thank you for your report. Please, create issue in [MSI repo](https://github.com/magento/inventory/issues) for further investigation
