### ISSUE TITLE
Rest API only updates 1 store view. But there are multiple store views on a single store site?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#28274]
Store id 0 is admin
Store id 1 is default

Updating a product using rest api by all or default will only update 1 of these values not both (as you would expect with just / or all/ infact why are there even two different values for everything e.g. catalog_product_entity_varchar, option titles etc.

So if you only update the front end one, the admin details are wrong and if only updating the admin one the front end details are wrong.
Such that products might not be enabled/disabled properly or show the correct name and custom options.

I think related to: https://github.com/magento/magento2/issues/7877

### Preconditions (*)
Magento 2.3.2 but could be others e.g. 2.2.0 and 2.3.0

1. Have existing product.
2. Singlepage site store is enabled.

### Steps to reproduce (*)
1.Post with rest api v1 to all or default store some change like the product name.

### Expected result (*)
1. Data should be updated everywhere e.g. admin and frontend should have same product name.

### Actual result (*)
1. Frontend and admin have different values for the same product.

![image](https://user-images.githubusercontent.com/1968109/82292595-4b76ab80-99ff-11ea-9794-be08e38644c3.png)
![image](https://user-images.githubusercontent.com/1968109/82292534-33069100-99ff-11ea-936d-0cbe23062312.png)

**Comment by LiamKarlMitchell** [comment]
I'll try on 2.4 later if I get time.
How do I access the SQL and Rest API on these test instances?

**Comment by lbajsarowicz** [comment]
#8897 related.

**Comment by LiamKarlMitchell** [comment]
Maybe related, but not 100% sure it is as it is to do with the options getting deleted and re-created it should keep the same id for unchanged options.

**Comment by LiamKarlMitchell** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell, here is your [Magento instance](https://i-28274-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28274-2-4-develop.instances.magento-community.engineering/admin_512c](https://i-28274-2-4-develop.instances.magento-community.engineering/admin_512c)
Login: `86f1899f` Password: `92e6f6f1d7b5`
Instance will be terminated in up to 3 hours.

**Comment by LiamKarlMitchell** [comment]
Made and activated integration for Access Token key.

Consumer Key
aorfd12o7nijo3gqdjhcvkzfkv5dwpyk
Consumer Secret
mo8jkk43zkj6n5irvh1lo67qks1noq3b
Access Token
qovcyf4155fekaxoolmflbinksintbgj
Access Token Secret
lz4918cxb5nebv0oic07uicbjrf1hig1

Rest API Endpoint:
https://i-28274-2-4-develop.instances.magento-community.engineering/rest/V1

Will test Manual via Admin interface on Simple Product 1 id 1 SKU product_dynamic_1

Edit product product_dynamic_1 and Add Customizable Option

Option Title: Test
Option Type: Drop-down
Required: Checked

Add Value
Title: 1
Title: 2


View product on front end.
https://i-28274-2-4-develop.instances.magento-community.engineering/category-1/category-1-1/simple-product-1.html

Inspect select dom for ID's.
I ran it through an HTML formatter to make it easier to read.

Save a change to the product and check the dom again.
I changed products price to 10 from 9.99 this did not trigger a update/save of the Customizable Options.
I then tried again by changing the option Test, 1's price to $1


After first save via admin:
```html
<select name="options[1]" id="select_1" class=" required product-custom-option admin__control-select" title="" data-selector="options[1]" aria-required="true">
   <option value="">-- Please Select --</option>
   <option value="1" price="0">1</option>
   <option value="2" price="0">2</option>
</select>
```

After saving more from via admin:
```html
<select name="options[1]" id="select_1" class=" required product-custom-option admin__control-select" title="" data-selector="options[1]">
   <option value="">-- Please Select --</option>
   <option value="1" price="0.72">1 +$0.72</option>
   <option value="2" price="0">2</option>
</select>
```

So it does not happen from admin save.


Testing with Rest save to update product.

I'll use Swagger for this.
https://i-28274-2-4-develop.instances.magento-community.engineering/swagger#

Expand: catalogProductRepositoryV1
Expand GET /V1/products/{sku}

Click Try it Out
Enter in product sku: product_dynamic_1
Click Execute

Copy the response body.


Expand POST /V1/products
Click Try it out
Adapt the body for catalogProductRepositoryV1SavePostBody with the previous response body from the get.

```json
{
    "product": {
          // Replace this object with the previous response body.
     }
}
```

Unable to reproduce it via rest api on 2.4-develop, maybe it is fixed?

Note: The option needs to have the corresponding option_id.
"option_id": 1,

And each of the values need to have the corresponding option_type_id.
"option_type_id": 1

But in Magento 2.2.0, the option_id and option_type_id were seemingly being ignored.
Possibly due to the multiple store thing?

Also the rest API posts to rest/all if that makes any difference I think the importer that uses the rest API was just using rest/V1 or maybe default.

https://i-28274-2-4-develop.instances.magento-community.engineering/rest/all/V1/products

**Comment by LiamKarlMitchell** [comment]
So I think there should only be 1 store view.
How can I get rid of default/admin and just have 1 for both?

**Comment by LiamKarlMitchell** [comment]
Still having weird issues with the rest API, can't seem to disable product from Default store view or update its name.

**Comment by LiamKarlMitchell** [comment]
Yeah confirming that this is still a problem in 2.3.0

Price being website scope is fine (should add a store view scope as an option as well by the way).
But when I'm updating products using the rest api via an extension to a PIM system its only updating the Default price even though website scope is set...

**Comment by engcom-Alfa** [comment]
Hi @LiamKarlMitchell . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop. Looks like the problem has already been fixed.

**Actual Result:** Frontend and admin have the same product name.
Are you able to reproduce it on clean 2.4-develop?
Thanks!
