### ISSUE TITLE
git clone --branch staging magento 2

### ISSUE THREAD

**Issue by neroshin** [magento/magento2#28273]
Hi support , I got some issue on migration of magento 2 there's no "Bin" folder after I clone it , I am newbie on magento hope someone can help me , it  can help much better if have a best instruction for migration from the magento 2 cloud via git repo

![image](https://user-images.githubusercontent.com/4207793/82289288-0b9bce00-99d7-11ea-966d-70a14df02655.png)

**Comment by lbajsarowicz** [comment]
All the runtime directories are being created during `composer install`.
