### ISSUE TITLE
install of the big fail no work pls fix

### ISSUE THREAD

**Issue by r32rf** [magento/magento2#28277]
Unable to apply patch Magento\Catalog\Setup\Patch\Schema\EnableSegmentation for module Magento_Catalog. Original exception message: Invalid column data type ""

**Comment by engcom-Echo** [comment]
Hi @r32rf. Thank you for your report.

Please provide more information to reproduce the issue.

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
