### ISSUE TITLE
Braintree invalid credit card number error handling Braintree

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#28272]
### Preconditions (*)

1. Magento CE 2.3.4 with sample data
2. Braintree payment method is set up with Visa and MasterCard enabled

### Steps to reproduce (*)

1. Sales > Orders > Create New Order
2. Choose products, complete the addresses and choose a delivery method
3. In the Braintree payment method enter a valid card number except for one digit (so the card number is actually incorrect) with a valid expiry and CVV
4. Press Place Order

### Expected result (*)

1. An error should be shown stating that the card number is invalid or some other type of error handling

### Actual result (*)

1. A "Please wait..." loader appears, freezing the page with "Attention - Some payment input fields are invalid" on the screen but unable to be clicked.

![2020-05-19-0010](https://user-images.githubusercontent.com/19744729/82287731-3b050780-99e4-11ea-9b7e-8ad0c8debae6.jpg)

**Comment by atIOCrON** [comment]
FYI, our developers wrote code to fix this on our site but it should be fixed in the Magento core:

They said:

"We've modified the Braintree payment method to give better error messages. We've also fixed it so that the loader is closed and lets you change the details properly."

It's disappointing that error handling by the core Braintree payment method is so poor.

**Comment by lbajsarowicz** [comment]
@atIOCrON You can contribute with your solution to Magento core, if your solution is viable.

**Comment by atIOCrON** [comment]
@lbajsarowicz our developers just created a quick fix. Someone else should look into this bug in more depth.

**Comment by lbajsarowicz** [comment]
@atIOCrON You can actually work on the final fix and contribution would be appreciated.

**Comment by atIOCrON** [comment]
@lbajsarowicz I'm not a developer., unfortunately, I'm just the store owner. If I was, I'd love to work on the fix.

**Comment by ajijshekh123** [comment]
Hello @atIOCrON,
In Default Magento 2.4 Instance Braintree Payment method is not available so I can't able to review this issue in the Latest Magento Instance.

Thanks.

**Comment by prasannachelladurai90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90, here is your [Magento instance](https://i-28272-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28272-2-4-develop.instances.magento-community.engineering/admin_8290](https://i-28272-2-4-develop.instances.magento-community.engineering/admin_8290)
Login: `5cbc94bf` Password: `fe5db2b3a84b`
Instance will be terminated in up to 3 hours.

**Comment by atIOCrON** [comment]
Yes, bot, this issue still persists. No one has looked into it. Please have someone fix the bug, thanks.

**Comment by engcom-Delta** [comment]
Hi @atIOCrON thank you for your report.
Starting from `2.4.0` release, code related to this payment was removed from Magento code-base:
[Magento Open Source 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html)
> The core Braintree module has been removed from the code base. The Braintree Payments module now provides the same feature set. See [Braintree Payments](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.190658731.163879255.1612162480-1157872356.1605459366).

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

If you'd like to update the issue, please reopen it.
