### ISSUE TITLE
Magento 2.3.4 - On customer creation, existing subscriber's subscription to newsletter is withdrawn

### ISSUE THREAD

**Issue by adeelq** [magento/magento2#28275]
### Preconditions (*)

1. Magento 2.3.4 vanilla

### Steps to reproduce (*)

1. Subscribe to Magento newsletter using example email test@test.com
2. Confirm above user has become subscriber. 
3. Create new account using same email as mentioned in point 1. Do not select "Sign Up for Newsletter" checkbox while creating customer account. 
4. Confirm new account is created. 

### Expected result (*)

1. New customer is created with subscription to Newsletter checked. 

### Actual result (*)

1. New customer is created where customer subscription to Newsletter is withdrawn on customer creation.
2. Before 2.3.4 this issue does not exist.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28275-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28275-2-4-develop.instances.magento-community.engineering/admin_4afb](https://i-28275-2-4-develop.instances.magento-community.engineering/admin_4afb)
Login: `deca245a` Password: `7f94ff64b1fd`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @adeelq.
Not able to reproduce the issue on latest vanilla instance as provided steps to by you
here it is working fine
![image](https://user-images.githubusercontent.com/46617848/82438659-0746e200-9ab7-11ea-9113-e172287dc6fb.png)
