### ISSUE TITLE
Magento 2.3.5-p1 No ‘Secure’ Attribute in frontend

### ISSUE THREAD

**Issue by mugua** [magento/magento2#28280]
### Preconditions (*)

1.Magento 2.3.5-p1
2.php 7.3.x
3:nginx

### Steps to reproduce (*)

1: force http to https
2: set secure website
3: set HttpOnly to Yes
4: add a samesite=none attribute from @HirokazuNishi 's fix
### Expected result (*)

1. will show the httponly and secure attribute in frontend
2. BTW, I add a samesite=none attribute from @HirokazuNishi 's fix.
3: then the chrome and firefox won't show the warning...

### Actual result (*)

1. just only httponly attribute
2. no secure attribute.
![1](https://user-images.githubusercontent.com/15046097/82313270-b5408680-99fa-11ea-8875-1cc161715b2f.png)
![2](https://user-images.githubusercontent.com/15046097/82313286-b8d40d80-99fa-11ea-85b2-815b9ef46231.png)
![3](https://user-images.githubusercontent.com/15046097/82313298-bc679480-99fa-11ea-98fd-c227315e1c50.png)

**Comment by mugua** [comment]
@magento give me 2.3.5-p1 instance, Thanks.

**Comment by magento-engcom-team** [comment]
Hi @mugua. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you
