### ISSUE TITLE
Adding and Removing 100FREE Coupon code in last checkout step does not let me checkout anymore

### ISSUE THREAD

**Issue by amenk** [magento/magento2#28294]
*WIP Ticket*
### Preconditions (*)

1. Create FREE code, to 100% discount and apply to shipping fee
2. Enable Second payment method

### Steps to reproduce (*)
1. Go to checkout
2. Last step
3. Choose  First payment method
4. Add FREE code
5. Go back to shipping
6. Go forward
7. Remove FREE code

### Expected result (*)
works

### Actual result (*)
1. JS error

**Comment by amenk** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amenk, here is your [Magento instance](https://i-28294-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28294-2-4-develop.instances.magento-community.engineering/admin_19c8](https://i-28294-2-4-develop.instances.magento-community.engineering/admin_19c8)
Login: `6518c8e2` Password: `8cef1b9e5b3f`
Instance will be terminated in up to 3 hours.

**Comment by amenk** [comment]
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by amenk** [comment]
Not reproduced on develop-2.4 will try on 2.3.5 . On the Splendid Demo shop I was able to reproduce.

**Comment by amenk** [comment]
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by amenk** [comment]
was an issue on our side, sorry for the noise
