### ISSUE TITLE
Configurable shows simple products which are no longer assigned to the website

### ISSUE THREAD

**Issue by amenk** [magento/magento2#28291]
### Preconditions (*)
1. Magento 2.4-develop testinstance

### Steps to reproduce (*)

1. Create additional website, store, storeview "other" in backend
2. Create Configurable with Options, assign to both websites

![i-28291-2-4-develop instances magento-community engineering_admin_0154_catalog_product_new_set_4_type_configurable_ (1)](https://user-images.githubusercontent.com/1087128/82411540-3edf6b00-9a72-11ea-9366-7065d5574f93.png)

3.  Set Quantity and in stock for each option in backend
4. Check that all 3 options are there in the frontend as expected

![image](https://user-images.githubusercontent.com/1087128/82411499-2a02d780-9a72-11ea-861a-27680025e941.png)

5. Disable option 1 in the "main website"

![image](https://user-images.githubusercontent.com/1087128/82411473-1ce5e880-9a72-11ea-90c4-6b6f380efa83.png)

6. Flush caches

### Expected result (*)

1. The option 1 should disappear in the Frontend

### Actual result (*)
1. Option 1 is still there

![image](https://user-images.githubusercontent.com/1087128/82411466-18213480-9a72-11ea-9522-b01e5bd345cf.png)

### Remarks

I do not know how to reindex the test instance, so I am not sure if it is a indexer problem

### Additional information 
 >  I do not know how to reindex the test instance, so I am not sure if it is a indexer problem

Tested on local env. Was done full reindex and flush cache = option 1 still available on website 1

**Comment by amenk** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amenk, here is your [Magento instance](https://i-28291-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28291-2-4-develop.instances.magento-community.engineering/admin_0154](https://i-28291-2-4-develop.instances.magento-community.engineering/admin_0154)
Login: `b7a346f6` Password: `e82c798245de`
Instance will be terminated in up to 3 hours.

**Comment by amenk** [comment]
Successfully reproduced on 2.4-develop instance. See above for steps and screenshots.

**Comment by krishprakash** [comment]
Hi @amenk.
It works fine here after re-indexing
You can re-index from System -> Tools -> Index Management -> Update on save all
Refer below screenshot:
![image](https://user-images.githubusercontent.com/46617848/82414885-5b40cf00-9a95-11ea-97d9-a6dfc926d1e7.png)
So closing this issue

**Comment by amenk** [comment]
@krishprakash  I think there is a misunderstanding. You seem to get a 404 for the configurable. But I un-assigned only one simple and expect the option to disappear. It's not about un-assigning the full configurable. 

Please retest and reopen.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34444` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ProkopovVitaliy** [comment]
I will work on this issue.

**Comment by kate-kyzyma** [comment]
I will cover it by MFTF test.

**Comment by amenk** [comment]
Was this solved? in which commits?

**Comment by sdzhepa** [comment]
Hello @amenk 

Sorry for any inconvenience. 
The issue was closed by bot too early by mistake...

As I can see this issue was fixed by Magento team and delivered with internal PR
Related commits can be found using search based on internal ticket key `MC-34444`
https://github.com/magento/magento2/search?q=MC-34444&type=commits
