### ISSUE TITLE
[2.3.5] Unable to add Euro (€) and accent characters into widget text field inside a CMS Page.

### ISSUE THREAD

**Issue by daniDLL** [magento/magento2#28298]
### Preconditions (*)
1. Magento EE 2.3.5 (composer installation)

### Steps to reproduce (*)
1. Create a new CMS page (Content > Pages > Add New Page)
2. Inside "Content" tab insert an element of type "Text" (content-type) to add a new "Widget".
3. Hover this "Text" (content-type) element and wait until the tinymce show its dialog.
4. Click on "Insert Widget"
5. Select the widget "Catalog Product List"
6. Fill the title parameter with characters with accents and specials, for example a Spanish phrase: "Envío gratis a partir de 10€"
7. Fill the rest of the parameters with sample data
8. Save the widget
9. Save the page

### Expected result (*)
1. The component load as a "Text" content-type and show the widget recently saved:
![image](https://user-images.githubusercontent.com/14359715/82452367-73254c80-9aaf-11ea-9e51-d8defb05dfd9.png)
2. Editing the "widget" correctly loads the parameters already saved:
![image](https://user-images.githubusercontent.com/14359715/82454058-9d780980-9ab1-11ea-93fd-29e61efbc183.png)

### Actual result (*)
1. The component load as a "HTML" content-type instead of the "Text" content-type:
![image](https://user-images.githubusercontent.com/14359715/82452196-3f4a2700-9aaf-11ea-804d-7e0f0c483b6e.png)
2. This causes that once a "Widget" with special characters is saved on the page, it cannot be edited within its content type "Text"
3. If special characters like the Euro are not included, and we only use accents, the letters come out incorrect and the widget can't load its options:
![image](https://user-images.githubusercontent.com/14359715/82453197-84228d80-9ab0-11ea-88cb-49ed9a098b0c.png)
4. When the widget tries to load its options, Magento returns an error when trying to decode the Json: 
```
{
  "0": "Decoding failed",
  "1": "Magento\\Framework\\Json\\Decoder->decode() called at [vendor\/magento\/framework\/Json\/Helper\/Data.php:60]\n#2 Magento\\Framework\\Json\\Helper\\Data->jsonDecode() called at [vendor\/magento\/module-widget\/Controller\/Adminhtml\/Widget\/LoadOptions.php:36]\n#3 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#4 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#5 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#6 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#7 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#8 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#9 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Widget\/Controller\/Adminhtml\/Widget\/LoadOptions\/Interceptor.php:26]\n#11 Magento\\Widget\\Controller\\Adminhtml\\Widget\\LoadOptions\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:162]\n#12 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:98]\n#13 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#16 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#18 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#19 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n",
  "url": "\/admin\/admin\/widget\/loadOptions\/key\/761521e47d2cc9b5d8aa1bbd6a7d7ac68a790a572d47e260c810da24d5fe08a9\/?isAjax=true",
  "script_name": "\/index.php",
  "report_id": "ee0d6af10cc1959a8ed9c7208938cd226022c900decd04214b1ca9611841e20f"
}
```

**Comment by daniDLL** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @daniDLL. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by PedroPinto2005** [comment]
Any update on the issue. Able to replicate on Magento EE  2.3.5-p1

**Comment by daniDLL** [comment]
Hi @PedroPinto2005,

In our case the origin of the issue was an encoding error in the Page Builder module. Magento gave us a patch to solve this error.

The error is in this file: `vendor/magento/module-page-builder/view/adminhtml/web/js/utils/editor.js`

Simply change this line:

`var image = (0, _jquery)("<img />").prop("id", btoa(match).replace(/\+/g, ":").replace(/\//g, "_").replace(/=/g, "-")).prop("src", imageSrc);` 

to this one:

`var image = (0, _jquery)("<img />").prop("id", Base64.idEncode(match)).prop("src", imageSrc);`

I hope is useful to you and others.

**Comment by PedroPinto2005** [comment]
Thank you! We were able to fix the issue with the patch.
