### ISSUE TITLE
Propose the specify the RAM requirements per a PHP process (768M) in the official «System requirements» page

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2830]
I propose to specify it here: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html
For now, there are not so clear mentions on a particular Unintu and CentOS pages:
- http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone
- http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html#instgde-prereq-timezone

**Comment by srenon** [comment]
Try editing https://github.com/magento/devdocs/blob/develop/guides/v2.0/install-gde/system-requirements.md and create a PR

**Comment by ghost** [comment]
@dfediuk Are you certain that this is a requirement and not a recommendation? Will it work for everyone? Is it necessary for everyone? I hesitate to add a "requirement" that is merely a guideline.

Also, what is not clear about the Ubuntu and CentOS recommendations?

**Comment by dmitrii-fediuk** [comment]
That is because a lot of people try to install Magento 2 on 128M hostings because they are not aware of the real Magento 2 memory requirements, the page http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html has no any mentions about it.

**Comment by andimov** [comment]
RAM requirements was updated.
