### ISSUE TITLE
full tax summary not working

### ISSUE THREAD

**Issue by jaydeepvs** [magento/magento2#28313]
display full tax summary is not working  i have opted Yes too but it did not work

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
Hello @jaydeepvs,
I didn't get exactly this issue. Can you please elaborate on this issue in proper steps, actual result and the expected result? 

Thanks.

**Comment by ajijshekh123** [comment]
Hi @jaydeepvs,
Nothing update from your end. 
Let me close the issue. If you have reproduced this issue again. You can reopen the issue with proper description, Magento instance and steps.

Thanks.
