### ISSUE TITLE
Magento1.9 | One Page Checkout Issue for Guest

### ISSUE THREAD

**Issue by rittukumar20016** [magento/magento2#28314]
### Preconditions (*)
1. Version: Magento 1.9
2. Using OnePageCheckout. Enabled guest checkout.
3. Using Fortis Extension
4. Using iwd extension
5. Using Amasty Extension

### Steps to reproduce (*)
1. Open the website. Purchase a product without login.
2. Select the product from the category
3. Add the product to cart.
4. Continue to Checkout page
5. Enter the Billing address section: 
             First name, Last name, Company, Email, Street, Suburb, State, Country, Telephone, Fax
6. Shipping to this address. Checkbox checked.
7. entering the payment details 
8. Cliking on Place Order.
9. After sometime we are getting a error message telling. "Please check the billing address information. Please enter the first name. Please enter the last name. Please enter the street. Please enter the street. Please enter the city. Please enter the telephone number. Please enter the Pin/Postal code"

Even though all the information we entered we are getting this error.

### Expected result (*)

1. After clicking on Place Order, by entering all the required fields. 
2. The order should get processed and new Order had to be generated.

### Actual result (*)

1. Throwing the error message "Please check the billing address information. Please enter the first name. Please enter the last name. Please enter the street. Please enter the street. Please enter the city. Please enter the telephone number. Please enter the Pin/Postal code"
2.
![billing address _issue](https://user-images.githubusercontent.com/65701811/82531894-d8377b80-9b5d-11ea-9642-dc66319ed566.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

Severity: S1

**Comment by rittukumar20016** [comment]
Please go ahead

**Comment by maheshWebkul721** [comment]
@rittukumar20016, you can only raise issues related to default Magento features, not third party modules issues.

**Comment by lbajsarowicz** [comment]
Magento 1 is not supported
