### ISSUE TITLE
Changing URL rewrite setting not reflected in admin interface

### ISSUE THREAD

**Issue by StuartAndertonGM** [magento/magento2#28317]
### Preconditions (*)

1. 2.3.5-p1

### Steps to reproduce (*)

1. Go to /admin/system_config/edit/section/web/
2. Change Use Web Server Rewrites from No to Yes
3. Save

### Expected result (*)

1. Use Web Server Rewrites shows Yes

### Actual result (*)

1. Use Web Server Rewrites shows No
Howver looking in mySQL the values have been updated:
![image](https://user-images.githubusercontent.com/55199433/82561281-03749780-9b6b-11ea-834d-778a8f6d7b8d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by CarmineDamore78** [comment]
@mageento give me 2.4-develop instance

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-28317-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28317-2-4-develop.instances.magento-community.engineering/admin_a0a2](https://i-28317-2-4-develop.instances.magento-community.engineering/admin_a0a2)
Login: `5cb72824` Password: `d39e5725bd77`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
@magento issue not reproducible on M2.4-develop

**Comment by lbajsarowicz** [comment]
The reported issue looks like the issue with config cache on user's instance. Please make sure that you have configured your caches

**Comment by engcom-Delta** [comment]
Hello @StuartAndertonGM 
Hi @webkul-ajaysaini . Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop and 2.3.5-p1. 
All my indexes are seted to "Update on Save"
"Use Web Server Rewrites" seted to "Yes" by default.

**Comment by engcom-Delta** [comment]
Issue is not reproducible on the latest 2.4-develop
**Result:**
:heavy_check_mark: Appropriate values are shown in `core_config_data` table
- "Use Web Server Rewrites"=Yes for `Main Website`(ID:1)
- "Use Web Server Rewrites"=No for `New Website`(ID:2)

![image](https://user-images.githubusercontent.com/51681379/99082914-76684380-25cd-11eb-82a1-26fd90396184.png)
