### ISSUE TITLE
Customers grid is empty

### ISSUE THREAD

**Issue by syntaxwanderer** [magento/magento2#2831]
I try to to add new a customer programmatically. But after I can not see any users in admin panel. Ok, I used registration form. And it does not work too. I tested it for 2 stores with magento 2 latest version. All ok for my older instalation of magento ver. 1.0.0-beta.

**Comment by syntaxwanderer** [comment]
So sorry I got it. php bin/magento indexer:reindex helped. But reindex in Admin panel does not helped.

**Comment by IceReaper** [comment]
Same problem here - but reindexing did not help. Version 2.0.2

**Comment by sevos1984** [comment]
What do you mean by reindex in Admin panel?

**Comment by slavvka** [comment]
@ArniXXX Is this issue still actual?

**Comment by aayushivadhva** [comment]
Hi, 
We are using magento 2.0.2 and we are also facing the same problem.
when we run command for reindexing it got stuck in Customer Grid and show its status as "Processing".

**Comment by slavvka** [comment]
@aayushivadhva, can you repoduce it on the latest code. If not please update your codebase

**Comment by vzabaznov** [comment]
Close as not updated more than 14 days

**Comment by ghost** [comment]
This is a real issue, maybe fixed in later versions but if the status in the indexer_state is stuck to working the customer grid won't reindex properly, have to set it to invalid manually.
