### ISSUE TITLE
display full tax summary is not working

### ISSUE THREAD

**Issue by jaydeepvs** [magento/magento2#28312]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
@jaydeepvs - This is a duplicate issue.
https://github.com/magento/magento2/issues/28313
Let me close this issue.

Thanks.
