### ISSUE TITLE
How to remove type="text/javascript attribute from script tag in magneto 2.3.1

### ISSUE THREAD

**Issue by parag1810** [magento/magento2#28327]
Hi,
I want to remove **type="text/javascript** attribute from script tag in magneto 2.3.1, as in w3 validator it is showing warning "The type attribute is unnecessary for JavaScript resources".
I go through when I search for this on google and I got one similar issue of it but that post was very old "https://github.com/magento/magento2/issues/2187"
Please can anyone help me out with it?

Thanks!!

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @Damikooo. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this topic.
