### ISSUE TITLE
Product having zero salable quantity results in stock in product list page and out of stock in view page.

### ISSUE THREAD

**Issue by maharzan86** [magento/magento2#28325]
Preconditions (*)

 1. Magento 2.3.5-p1(MSI enabled)

Steps to reproduce (*)

1. Create a simple product with qty = 1
2. Place an order that will cause the product to have 0 salable quantity
3. The Salable Quantity drops to zero, while the Quantity remains at 1.

Expected result (*)

1. The product, having Salable Quantity 0, should display out of stock label in both product list page and product view page.

Actual result (*)

1. The product remains in stock in product list page and out of stock in view page.

P.S. If you open the product page then it does show correctly as out of stock product.

admin panel stock
![スクリーンショット 2020-05-22 12 18 16](https://user-images.githubusercontent.com/45053620/82627899-6f680600-9c26-11ea-99cf-0c3828d91e04.png)

product list page
![スクリーンショット 2020-05-22 12 11 27](https://user-images.githubusercontent.com/45053620/82627566-a0940680-9c25-11ea-85db-aa558ac7c5c1.png)
product view page

![スクリーンショット 2020-05-22 12 12 09](https://user-images.githubusercontent.com/45053620/82627570-a25dca00-9c25-11ea-9c68-9917d55268ca.png)

**Comment by maharzan86** [comment]
@ajijshekh123 @m2-assistant  any updates...

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-28325-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28325-2-4-develop.instances.magento-community.engineering/admin_e319](https://i-28325-2-4-develop.instances.magento-community.engineering/admin_e319)
Login: `b3dbe885` Password: `da1af70eb12a`
Instance will be terminated in up to 3 hours.

**Comment by wallacehao** [comment]
Hi Sir, 
Can give me the ticket of Dev commit.
Thanks

**Comment by swathishs** [comment]
Hi @maharzan86,2 all issue specific for MSI should be reported in the MSI repo

fyi: @sidolov @smoskaluk @sdzhepa

It seems this issue MSI specific and should be fixed in the MSI repository.

EngCom team, please confirm and transfer this issue to the https://github.com/magento/inventory/issues

Closing this issue
