### ISSUE TITLE
DHL Gateway URL

### ISSUE THREAD

**Issue by Lucky9821** [magento/magento2#28328]
Hello, I cannot find DHL gateway URL on Magento 2.3.2. Anyone found the same issue and how to solve?

![DHL Gateway URL](https://user-images.githubusercontent.com/65758090/82644905-43577f80-9c3c-11ea-97c3-ffc2675fa443.jpg)

**Comment by devchris79** [comment]
We use 2.3.4 and its not there despite it appearing in the [documentation](https://docs.magento.com/user-guide/shipping/dhl.html)

Its not been a problem for us though as we use the default gateway (you don't need to specify the default).

**Comment by krishprakash** [comment]
@Lucky9821 Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
