### ISSUE TITLE
Attribute value was duplicated after upgrade magento from 2.1 to 2.3

### ISSUE THREAD

**Issue by thanhdv2811** [magento/magento2#28326]
### Preconditions (*)

1. Our Database was migrated from magento 1 to magento 2.1 few years ago
2. All the site is running normally in the version 2.1

### Steps to reproduce (*)

1. Composer update from magento 2.1.17 to magento 2.3.4
2. Disable all the 3rd party extension
3. Run Magento command setup:upgrade

### Expected result (*)

1. The attribute value in the table catalog_product_entity_datetime, catalog_product_entity_decimal, catalog_product_entity_int should be the same as before
2.This is an example data of product 7120 in the table catalog_product_entity_datetime.
![Selection_043](https://user-images.githubusercontent.com/20705278/82633578-a4c02400-9c25-11ea-8aa6-aa6a98284f9c.png)

### Actual result (*)

1. After the update command, those data were duplicated 
2. This is an example data of product 7120 after update command in the table catalog_product_entity_datetime
![Selection_044](https://user-images.githubusercontent.com/20705278/82633668-dcc76700-9c25-11ea-952e-64659864f78f.png)

As I checked in the Magento code, magneto added a patch to upgrade website attribute vendor/magento/module-catalog/Setup/Patch/Data/UpgradeWebsiteAttributes.php
This patch inserts the attribute value by store view for this table list
```
private $tableMetaDataClass = [
        'catalog_category_entity_datetime' => CategoryInterface::class,
        'catalog_category_entity_decimal' => CategoryInterface::class,
        'catalog_category_entity_int' => CategoryInterface::class,
        'catalog_category_entity_text' => CategoryInterface::class,
        'catalog_category_entity_varchar' => CategoryInterface::class,
        'catalog_product_entity_datetime' => ProductInterface::class,
        'catalog_product_entity_decimal' => ProductInterface::class,
        'catalog_product_entity_int' => ProductInterface::class,
        'catalog_product_entity_text' => ProductInterface::class,
        'catalog_product_entity_varchar' => ProductInterface::class,
    ];
```

![Selection_045](https://user-images.githubusercontent.com/20705278/82633796-48113900-9c26-11ea-90e1-11672b67455a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by eduardoPavon** [comment]
I have the same problem. Any update on this issue?

**Comment by hostep** [comment]
We also ran into this, see https://github.com/magento/magento2/issues/32283
A fix for this is pending here: https://github.com/magento/magento2/pull/32286

But it will only prevent this from happening again in the future and won't fix the duplicated entries you already have in your database.
