### ISSUE TITLE
2.3.5-p1 Contact Form No Longer Including ReplyTo address

### ISSUE THREAD

**Issue by AJHopper** [magento/magento2#28320]
### Preconditions (*(

1. Running Magento 2.3.5-p1
2. Litespeed Web Server
3. PHP 7.2

### Steps to reproduce (*)

1. Upgrade from Magento 2.3.2 to 2.3.5-p1
2. fill in contact form and submit

### Expected result (*)

1. Prior to the upgrade an email would be submitted with a ReplyTo email address, would expect the same behavior

### Actual result (*)

1. email is submitted successfully but now only has To, and From emails and is missing the ReplyTo.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Have stepped through debugging this and it is moving though the standard module-contact/Model/Mail.php file so no extensions are messing with it. Is hitting the below code and the $replyTo value is correct however the setReplyTo() function doesnt seem to correctly persist the data.

![image](https://user-images.githubusercontent.com/24913406/82595711-fc1ab180-9b9d-11ea-9714-40de7e592721.png)

have temporarily worked around this by simply passing through $replyTo as a parameter to an extended sendMessage() version, and then directly setting the replyTo on the ZendMessage object which seems to work however since I can see the flow of the form is only touching a few core modules, none overridden by any extensions I feel this should be working by default.

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-28320-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28320-2-4-develop.instances.magento-community.engineering/admin_6167](https://i-28320-2-4-develop.instances.magento-community.engineering/admin_6167)
Login: `073c33ec` Password: `1307629bd077`
Instance will be terminated in up to 3 hours.

**Comment by Serializator** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Serializator** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Raffail** [comment]
Hi!
Magento 2.4.3-p1 still has this issue with missing reply-to header.
Is there a fix that can be implemented by user with low programming skills, please?
Thank you.
