### ISSUE TITLE
Vimeo videos are note stored

### ISSUE THREAD

**Issue by jstuardo** [magento/magento2#2833]
Hello...

I add vimeo videos to a product. Videos appear in backend, but when i save the product, product is actually saved, however, when I go to edit the product again, videos are not there, and in fact, videos are not shown in front end.

Please check it.
Thanks

**Comment by le0n4eg** [comment]
Thanks for reporting this issue! Internal ticket MAGETWO-47490

**Comment by mslabko** [comment]
Hello @jstuardo 

On current mainline this issue is not reproduced. Could you provide additional steps?
Also, could you provide version, where you reproduced this issue?

**Comment by MomotenkoNatalia** [comment]
@jstuardo  Any updates on this?

**Comment by katmoon** [comment]
Closing the issue as it can't be reproduced and there's no response has been received from the reporter.
@jstuardo Please feel free to reopen if you still experience the issue.
