### ISSUE TITLE
Unable to save the value of custom field for customer module.

### ISSUE THREAD

**Issue by suneet-magento** [magento/magento2#2834]
I have created a new filed in customer_entity table and unable to save the value of newly created field. Can you please suggest me something on this?

**Comment by slavvka** [comment]
Hi @SnVan. Could you please provide more details? How did you create a new field? Did you add it as a static EAV attribute? How do you try to save a value? Do you use model or data object?

**Comment by SnVan** [comment]
Hi @slavvka, no I didn't add it as a static EAV attribute, I just add a new column in customer_entity table. I'm trying to save/retrieve the value of this custom field through getter setter. Can you please suggest the right way to save it?

**Comment by suneet-magento** [comment]
Hi @slavvka, I have added the static EAV attribute and I'm able to save it from Magento backend but not from the frontend. Can you please suggest how can I save it from frontend?

**Comment by hitendraebiz** [comment]
Hi @slavvka,  I have same problem for customer attribute save from backend but not saved script .Customer model load by id and set attribute value but attribute not saved in database and replace with blank value.Can you please provide me if you have any solutions for it ?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by techguysourav** [comment]
I made text field attribute to backend customer form. The Field is showing is ok but value is not saving in tables. Attribute is showing in eav_attribute , customer_eav_attribute tables.

**Comment by sarfaraj-php** [comment]
@mage-sourav , i have same problem value is not save to database and not able to get that attribute in frontend header file.
