### ISSUE TITLE
Braintree credit memo for partial invoice tax amount incorrect

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#28347]
### Preconditions (*)

1. Magento CE 2.3.4 with sample data
2. Braintree payment method is set up with "Payment Action" set to "Authorize":

<img width="895" alt="Screen Shot 2020-05-24 at 6 02 36 pm" src="https://user-images.githubusercontent.com/19744729/82748889-c74e6a80-9de8-11ea-968a-62e7d2597fb7.png">

3. Stores > Configuration > Sales: Tax > Tax Classes setup like below:

<img width="1123" alt="Screen Shot 2020-05-24 at 5 53 51 pm" src="https://user-images.githubusercontent.com/19744729/82748721-90c42000-9de7-11ea-90f3-8316953e8c72.png">

4. Stores > Configuration > Sales: Tax > Calculation Settings setup like below:

<img width="1132" alt="Screen Shot 2020-05-24 at 5 54 24 pm" src="https://user-images.githubusercontent.com/19744729/82748728-9f123c00-9de7-11ea-89c5-e4105160a77f.png">

5. Stores > Configuration > Sales: Tax > Orders, Invoices, Credit Memos Display Settings setup like below:

<img width="1121" alt="Screen Shot 2020-05-24 at 5 54 55 pm" src="https://user-images.githubusercontent.com/19744729/82748745-b18c7580-9de7-11ea-950e-77f587ec6170.png">

6. Stores > Taxes: Tax Zones and Rates setup a tax rate like below:

<img width="1317" alt="Screen Shot 2020-05-24 at 5 57 41 pm" src="https://user-images.githubusercontent.com/19744729/82748804-16e06680-9de8-11ea-97d4-6f59ff32a6ea.png">

7. Stores > Taxes: Tax Rules setup a rule like below:

<img width="1314" alt="Screen Shot 2020-05-24 at 5 56 38 pm" src="https://user-images.githubusercontent.com/19744729/82748779-f1535d00-9de7-11ea-9604-c6395e4602fa.png">

### Steps to reproduce (*)

1. Place a new order for multiple products using the Braintree payment method (Visa, MasterCard, AMEX)
2. Invoice one of the products on the order

![01](https://user-images.githubusercontent.com/19744729/82748559-41c9bb00-9de6-11ea-9a45-b8b16c6d46cc.jpg)

3. Invoice the remaining products on the order

![02](https://user-images.githubusercontent.com/19744729/82748561-45f5d880-9de6-11ea-84ad-f2199c90b79d.jpg)

4. Open any of the invoices and click credit memo

![06](https://user-images.githubusercontent.com/19744729/82748928-1a282200-9de9-11ea-83c9-9d9a019f776c.jpg)

![07](https://user-images.githubusercontent.com/19744729/82748932-1d231280-9de9-11ea-8af0-66cf57134dc8.jpg)

### Expected result (*)

The tax amount of the credit memo should match the credit memo items (e.g. it should match the invoice)

### Actual result (*)

The tax amount matches the entire order, not the items being credited only. The grand total of the credit memo is higher than the invoice.

![05](https://user-images.githubusercontent.com/19744729/82748660-36c35a80-9de7-11ea-82ea-2367d0e9217b.jpg)

If you try to create the credit memo you will get the error:

<img width="196" alt="Screen Shot 2020-05-24 at 6 01 02 pm" src="https://user-images.githubusercontent.com/19744729/82748869-92421800-9de8-11ea-8735-10029e8d3880.png">

---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by Serializator** [comment]
@magento I'm working on this

**Comment by Serializator** [comment]
@magento I'm working on this

**Comment by krishprakash** [comment]
Hi @atIOCrON. Issue is duplicate to #26284 and already in open state
so closing this issue
Thanks!!
