### ISSUE TITLE
The fields with type='checkbox' are misaligned in the backend «Stores» → «Configuration» section

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2835]
https://mage2.pro/t/332

**Comment by MomotenkoNatalia** [comment]
@dfediuk  Thanks for reporting this issue! Internal ticket MAGETWO-48492

**Comment by vil11** [comment]
@mage2pro We can't find "Show ID instead of SKU" check-box on "Stores > Configuration" Admin form. Please specify the full path to this panel & your Magento version.

:sunny: Dmytro Vilchynskyi, M2 QA engineer.

**Comment by MomotenkoNatalia** [comment]
Closing the issue as it cannot be reproduced and there is no response has been received from the reporter.
@mage2pro please feel free to reopen if you feel that issue could be reproduced.
