### ISSUE TITLE
New order status setting for Zero Subtotal Checkout does not have an effect

### ISSUE THREAD

**Issue by amenk** [magento/magento2#28359]
### Preconditions
1. Add item with 0$ and free shipping to the catalog, so can check out for free
2. Configurage "Zero Subtotal checkout" to status "processing", do not invoice items

![step_001](https://user-images.githubusercontent.com/1087128/82821612-b4996b80-9ea4-11ea-9ec8-8cabbdb686d4.png)

### Steps to reproduce
1. buy this item

![step_002](https://user-images.githubusercontent.com/1087128/82821622-b9f6b600-9ea4-11ea-9c7c-f7cb112ecf67.png)
![step_003](https://user-images.githubusercontent.com/1087128/82821632-bc591000-9ea4-11ea-99de-29a7da4d642a.png)

### Expected result
1. Order status is processing

### Actual result
1. Order status is pending
![step_004](https://user-images.githubusercontent.com/1087128/82821648-c24ef100-9ea4-11ea-91eb-865d217c5a89.png)

**Comment by amenk** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amenk, here is your [Magento instance](https://i-28359-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28359-2-4-develop.instances.magento-community.engineering/admin_767e](https://i-28359-2-4-develop.instances.magento-community.engineering/admin_767e)
Login: `834a343e` Password: `51f3c1a26d50`
Instance will be terminated in up to 3 hours.

**Comment by amenk** [comment]
Confirmed on above test instance

**Comment by krishprakash** [comment]
Hi @amenk. 
Seems issue is already reported and in open status
You can track the conversation from [#12671](https://github.com/magento/magento2/issues/12671)
Thank you for your report !!
