### ISSUE TITLE
Check Component Dependency

### ISSUE THREAD

**Issue by cyberbloke** [magento/magento2#28353]
Hello All,
I have just installed Magento 2.3.5.p.l version. 

I tried to install new component and theme and when doing that, the system gets an error:

Component Dependency Check Fails. Though I have tried to look around on google and did try few fixes on composer.json -- to no avail.

Can you help me with this one as its an urgent issue for us.

Thanksl
![Magento-Error](https://user-images.githubusercontent.com/6697262/82763745-d7aa1980-9dd7-11ea-80aa-d237e152ecb9.png)

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @cyberbloke, try to update php memory limits in .htaccess and .user.ini files in Magento root directory from 765MB to 2G as they override system php limits.

**Comment by krishprakash** [comment]
Hi @cyberbloke. Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this problem
