### ISSUE TITLE
Product save issue

### ISSUE THREAD

**Issue by sainialpana** [magento/magento2#28364]
I am having issue when saving the product after import customizable options, the error comes "No such entity"

**Comment by swathishs** [comment]
@sainialpana: Thank you for your report. Could you please update the step to reproduce and attach the actual result and expected result. So that I could able to validate the ticket.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28364-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28364-2-4-develop.instances.magento-community.engineering/admin_7d92](https://i-28364-2-4-develop.instances.magento-community.engineering/admin_7d92)
Login: `49b5380a` Password: `366f4a1cb78e`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
Hi @sainialpana:
Feel free to reopen once you update all the details with reproducible steps
Thanks !!
