### ISSUE TITLE
Warning: A non-numeric value encountered when adding 2nd price attribute and sorting in layered nav

### ISSUE THREAD

**Issue by matthew99** [magento/magento2#28360]
### Preconditions (*)
1. Magento 2.3.5
2. PHP error reporting DEV (show all)

### Steps to reproduce (*)
1. Create new attribute with input type  'price', called 'number'
2. Make it filterable with results
3. Create or edit product, enter a number  '12345' in newly created attribute 'number'
3. Reindex, refresh cache, go to frontend, category with product
4. Click in layered nav on attribute 'number' and item '12345 and up'

### Expected result (*)
1. Show the product with the 'number' attribute

### Actual result (*)

1. Exception screen.
Warning: A non-numeric value encountered in [path]/module-catalog-search/Model/Layer/Filter/Decimal.php on line 147
<pre>#1 Magento\CatalogSearch\Model\Layer\Filter\Decimal->renderRangeLabel(1950, 0) called at [vendor/magento/module-catalog-search/Model/Layer/Filter/Decimal.php:83]
#2 Magento\CatalogSearch\Model\Layer\Filter\Decimal->apply(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/module-layered-navigation/Block/Navigation.php:70]
#3 Magento\LayeredNavigation\Block\Navigation->_prepareLayout() called at [vendor/magento/framework/View/Element/AbstractBlock.php:286]
#4 Magento\Framework\View\Element\AbstractBlock->setLayout(&Magento\Framework\View\Layout\Interceptor#000000000f0934d50000000045d31abc#) called at [vendor/magento/framework/View/Layout/Generator/Block.php:149]
#5 Magento\Framework\View\Layout\Generator\Block->process(&Magento\Framework\View\Layout\Reader\Context#000000000f0932c50000000045d31abc#, &Magento\Framework\View\Layout\Generator\Context#000000000f0932ad0000000045d31abc#) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:81]
#6 Magento\Framework\View\Layout\GeneratorPool->process(&Magento\Framework\View\Layout\Reader\Context#000000000f0932c50000000045d31abc#, &Magento\Framework\View\Layout\Generator\Context#000000000f0932ad0000000045d31abc#) called at [vendor/magento/framework/View/Layout.php:352]
#7 Magento\Framework\View\Layout->generateElements() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Framework\View\Layout\Interceptor->___callParent('generateElements', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Framework\View\Layout\Interceptor->___callPlugins('generateElements', array(), array(array('layout-model-cac...', 'core-session-dep...', 'customer-session...', 'catalog-session-...', 'persistent-sessi...', 'checkout-session...', 'tax-session-depe...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:91]
#11 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#12 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#13 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#14 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:224]
#15 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:237]
#16 Magento\Framework\View\Page\Config->publicBuild() called at [vendor/magento/framework/App/View.php:170]
#17 Magento\Framework\App\View->loadLayoutUpdates() called at [vendor/magento/framework/App/View.php:114]
#18 Magento\Framework\App\View->loadLayout(NULL) called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:166]
#19 Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult(&Magento\CatalogSearch\Helper\Data#000000000f0932fd0000000045d31abc#, &Magento\Search\Model\Query#000000000f0932cf0000000045d31abc#, NULL) called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:110]
#20 Magento\CatalogSearch\Controller\Result\Index->execute() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:24]
#21 Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#22 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:39]
#26 Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/App/FrontController.php:162]
#27 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#, &Magento\CatalogSearch\Controller\Result\Index\Interceptor#000000000f0934610000000045d31abc#) called at [vendor/magento/framework/App/FrontController.php:99]
#28 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#31 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000000f09378e0000000045d31abc#, &Closure#000000000f09376f0000000045d31abc#, &Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#33 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000000f09378e0000000045d31abc#, &Closure#000000000f09376f0000000045d31abc#, &Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php:32]
#35 Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000000f09378e0000000045d31abc#, &Closure#000000000f09376f0000000045d31abc#, &Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#36 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#37 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#), array(array('mstCoreDispatch'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#38 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000000f0936290000000045d31abc#) called at [vendor/magento/framework/App/Http.php:116]
#39 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#40 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#41 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000000f09363e0000000045d31abc#) called at [index.php:39]
</pre>

---- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by matthew99** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @matthew99. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @matthew99, here is your [Magento instance](https://i-28360-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28360-2-4-develop.instances.magento-community.engineering/admin_29d9](https://i-28360-2-4-develop.instances.magento-community.engineering/admin_29d9)
Login: `2945f643` Password: `fdc8b332c5a4`
Instance will be terminated in up to 3 hours.

**Comment by matthew99** [comment]
Changed product to attribute set 'default', did as above. First product is added to category 1-1 and has attribute test_number_price, '12345'
How can I force re-indexing on dev instance

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@matthew99: The issue is not reproducible on Magento 2.4 develop instance.

Please refer the attachment below:
1. **New attribute**:
![image](https://user-images.githubusercontent.com/58288685/83038461-9bd2b680-a05a-11ea-9aa2-52af9c9d091e.png)
2. **New product with number attribute**:
![image](https://user-images.githubusercontent.com/58288685/83038547-b7d65800-a05a-11ea-9363-17446d854623.png)
3. **Click in layered nav on attribute 'number'** :
https://drive.google.com/file/d/15WrntW0OB99CASeN7De1pl8G0XfZur2w/view?usp=sharing

**Comment by swathishs** [comment]
Hi @matthew99, thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.
