### ISSUE TITLE
Queue consumers issue when we install multi website instance in same server

### ISSUE THREAD

**Issue by pradeeprcs** [magento/magento2#28368]
### Preconditions (*)

1.  Version :- Magento 2.3.4
2.  Install two M2 website (not multi website). 2 different instance.
3.  Setup cron for both website (website1 and website2)
4.  in both website env.php consumer will run by cron  
'cron_consumers_runner' => [
        'cron_run' => true
    ]
5. Nginx + Ubuntu 

### Steps to reproduce (*)

1. Make sure cron is running for both website
2. Make sure consumer queue is properly setup

### Expected result (*)

1.  should run consumer queue for both website

### Actual result (*)

1. Consumer queue  process is running for only one website
2. If consumer queue is started for website1 then it will not start for website2 
3. If we install 2 website in one server it will not init or start consumer queue  process for both website

### Finding  
I am assuming its a core Magento bug , if i modify below code it will init or start consumer queue  process in both website

If i run "ps -ef|grep consumer" it will start or show a process for only one website 

### Fix
vendor\magento\framework\Lock\Backend\Database.php::getPrefix()   (line no around 185)
if we change  
if ($this->prefix === null) {
to
if (empty($this->prefix)) {

it works fine

**Comment by pradeeprcs** [comment]
@magento I am working on this

**Comment by pradeeprcs** [comment]
issue is in the vanilla Magento

**Comment by pradeeprcs** [comment]
@magento I am working on this

**Comment by SamJUK** [comment]
Can confirm this is happening also on `Mage CE 2.3.4-p2` where the installs shares the same Mysql host.

On our UAT env I've disabled the cron consumers, and replaced with custom crontab entries that start the multithreaded versions instead since they don't trigger the lock. And seems to be operation fine so far.

```
*/30 * * * * /usr/bin/php /var/www/bin/magento queue:consumers:start product_action_attribute.update
*/30 * * * * /usr/bin/php /var/www/bin/magento queue:consumers:start product_action_attribute.website.update
*/30 * * * * /usr/bin/php /var/www/bin/magento queue:consumers:start exportProcessor
*/30 * * * * /usr/bin/php /var/www/bin/magento queue:consumers:start codegeneratorProcessor
```
