### ISSUE TITLE
When creating new module in magento 2....issues occur

### ISSUE THREAD

**Issue by klongithub** [magento/magento2#2836]
Hello,

When I create a new module in magento 2 & then when I visit frontend or admin then it gives this error:  
Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Hello schema: current version - none, required version - 0.0.1
Magento_Hello data: current version - none, required version - 0.0.1

Though schema & setup version both given as - 0.0.1

Now when hitting this command -> bin/magento setup:upgrade
It gives another 2 errors :-
1) [Zend_Db_Adapter_Exception]  
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '  
  /var/run/mysqld/mysqld.sock' (2) 

2)  [PDOException]  
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '  
  /var/run/mysqld/mysqld.sock' (2)

In search of the solution to this I found this :-
search mysqld.sock you can search it using command : find -name "mysqld.sock" then right click on it and copy link then paste it under /var/run/mysqld/ and rename it to mysqld.sock if there is no directory name "mysqld" in /var/run/ then create it

Now the thing is when I search mysqld.sock like this -> find -name "mysqld.sock" then it gives :-
find: `./.dbus': Permission denied
find:`./.gvfs': Permission denied
find: `./.cache/dconf': Permission denied
also I do not have mysqld folder inside var/run so I created it manually as suggested but then what? mysqld.sock file? do I also need to create it manually?

What to do now? I can't understand why this is so in magento 2 stable version. It should be like when we create module & when run frontend or admin then all these procedure should be automatically done.

Any Solution for this please?

Thank You.

**Comment by mrkhoa99** [comment]
<p>The GitHub issue tracker is intended for technical issues only. Please refer to the <a href="https://community.magento.com" target="_blank">Community Forums</a> or <a href="http://magento.stackexchange.com/" target="_blank">Magento Stack Exchange</a> site for technical questions. In your case, the <a href="https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2" target="_blank">programming questions forum</a> is likely the most appropriate.</p>

**Comment by klongithub** [comment]
Thanks mrkhoa99 :)

Yes I am going to post in programming questions forum.

Thanks Again :)
