### ISSUE TITLE
Updating CMS page via api should NOT remove related URL rewrites

### ISSUE THREAD

**Issue by SzabKel** [magento/magento2#28370]
### Preconditions (*)

1. Magento ver. 2.3.3 (I tested this on two different environments, one is our hosted magento solution, other one is a [bitnami virtual machine.](https://bitnami.com/stack/magento/virtual-machine) )
3. Setup an integration for the rest api, allow CMS actions

### Steps to reproduce (*)

1. Add a new CMS Page, magento will automatically add a rewrite for each language (according to your URL-Key / Identifier field)
![IMG](https://i.imgur.com/Lrpxkyv.png)
2. Manually add a rewrite from any URL pointing to the CMS Page
![IMG](https://i.imgur.com/wCVfHp9.png)
3. Run a request using the rest api and update the CMS Page's content:
```
curl --location --request PUT 'http://.../rest/V1/cmsPage/7' \
--header 'Authorization: Bearer ****' \
--header 'Content-Type: application/json' \
--data-raw '{
	"page": {
		"id": 7,
		"title": "test",
		"identifier": "test",
		"content": "content updated"
	}
}'
```
The title field is required. I also tried to update without the identifier field specified in the request, but I get the same result.

### Expected result (*)

The previously added rewrite should be still active. Maybe if the identifier is changed, the rewrites should be updated.

### Actual result (*)

**The rewrites are deleted and a new rewrite is added for the CMS page**. This is easy to see, because every time I do an update, the default rewrite's id is incremented.

### Connected
[This issue seems related.](https://github.com/magento/magento2/pull/14751)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** I think? The user's data is deleted and you can't do anything against it, but there is a workaround (posted in a comment)

**Comment by SzabKel** [comment]
Update (and workaround):

Magento only deletes the URL Rewrite, if it is added using the "For CMS Page" menu. If I manually add a rewrite and I type in the target as "cms/page/view/page_id/<page_id>", the rewrite won't be deleted!

**Comment by engcom-Delta** [comment]
Hi @SzabKel  I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
1. Create additional store view:
![image](https://user-images.githubusercontent.com/51681379/100071276-87be1500-2e43-11eb-8a65-42a1606bf90e.png)
2. Create CMS page
3. Add a rewrite to the CMS Page for additional store view
![image](https://user-images.githubusercontent.com/51681379/100071417-b6d48680-2e43-11eb-9012-6697256d8acf.png)
4. Run PUT /V1/cmsPage/{id}:
![Screenshot from 2020-11-24 11-01-45](https://user-images.githubusercontent.com/51681379/100072083-7c1f1e00-2e44-11eb-9f98-b01cd2c86959.png)


**Result:** 
:heavy_check_mark: Previously added rewrite are not changed and still active
![image](https://user-images.githubusercontent.com/51681379/100071943-4aa65280-2e44-11eb-9e96-25b388e066f5.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by SzabKel** [comment]
@engcom-Delta It only deletes the rewrites, if the use the "For CMS page" menu when you add the rewrites. 
It is also possible this already got solved since I reported it.
