### ISSUE TITLE
Mage::getSingleton('cataloginventory/stock')->registerItemSale($orderItem) registerItemSale to reduce stock in magento when order in magento2?

### ISSUE THREAD

**Issue by tranductrong92** [magento/magento2#2838]
Mage::getSingleton('cataloginventory/stock')->registerItemSale($orderItem). registerItemSale to reduce stock in magento when order in magento2 ?

**Comment by kandy** [comment]
\Magento\CatalogInventory\Model\StockManagement::registerProductsSale method used in M2 to reduce stock on order placement.

**Comment by kandy** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
