### ISSUE TITLE
Table is not being saved correctly in Database after Installing an extension. 

### ISSUE THREAD

**Issue by 09eric09** [magento/magento2#28396]
Hello, 

I have an extension I am trying to install on Magento 2.3.4 and when I enable it via SSH, it seems the prefix is ignored in the database table. . 

**Preconditions (*)**
Magento 2.3.4
Mage StoreReward Points Extension version 1.2.0.

**Steps to reproduce (*)**
I've tried manually adding the prefix, but it does not fix the issue.
I have also ran the command php bin/magento setup:upgrade

**Expected result (*)**

The extension is expected to work after installation and add the table prefix automatically.

**Actual result (*)**

Here is the error message 

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magestore_Rewardpoints schema: current version - none, required version - 1.2.0.5
Magestore_Rewardpoints data: current version - none, required version - 1.2.0.5

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magestore_Rewardpoints schema: current version - none, required version - 1.2.0.5
Magestore_Rewardpoints data: current version - none, required version - 1.2.0.5
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005fb9e466000000003d5be9ad#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#2 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000005fb9e5c8000000003d5be9ad#, &Closure#000000005fb9e5a9000000003d5be9ad#, &Magento\Framework\App\Request\Http#000000005fb9e466000000003d5be9ad#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#3 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005fb9e466000000003d5be9ad#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000005fb9e466000000003d5be9ad#), array(array('page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'), array('front-controller...'), 'requestPreproces...')) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#5 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000005fb9e466000000003d5be9ad#) called at [vendor/magento/framework/App/Http.php:116]
#6 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#7 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#8 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000005fb9e410000000003d5be9ad#) called at [index.php:39]
</pre>

**Comment by engcom-Delta** [comment]
Hi @09eric09 thank you for your report
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
