### ISSUE TITLE
/carts/mine/shipping-information rest Api subtotal error

### ISSUE THREAD

**Issue by ldc321** [magento/magento2#28405]
### Preconditions (*)

1.Magento 2.3.4 php 7.2.18
2.

### Steps to reproduce (*)

1.use discount code
2.set tax
3. call rest api /carts/mine/shipping-information

### Expected result (*)

1.  To get the correct subtotal

### Actual result (*)

1. subtotal error
2.
![image](https://user-images.githubusercontent.com/57743360/83137902-8625c580-a11c-11ea-935f-157b32e03f5a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@ldc321: The issue is not reproducible in Magento 2.4 develop instance
Please find the attachment below:
1. Front end : 
![image](https://user-images.githubusercontent.com/58288685/83751403-6ba39d00-a684-11ea-8e75-3d0c514ce78e.png)

2. Response:
{
    "payment_methods": [
        {
            "code": "checkmo",
            "title": "Check / Money order"
        },
        {
            "code": "banktransfer",
            "title": "Bank Transfer Payment"
        }
    ],
    "totals": {
        "grand_total": 77.63,
        "base_grand_total": 78.43,
        "subtotal": 30.7,
        "base_subtotal": 30.7,
        "discount_amount": -3.07,
        "base_discount_amount": -3.07,
        "subtotal_with_discount": 27.63,
        "base_subtotal_with_discount": 27.63,
        "shipping_amount": 50,
        "base_shipping_amount": 50,
        "shipping_discount_amount": 0,
        "base_shipping_discount_amount": 0,
        "tax_amount": 0.8,
        "base_tax_amount": 0.8,
        "weee_tax_applied_amount": null,
        "shipping_tax_amount": 0,
        "base_shipping_tax_amount": 0,
        "subtotal_incl_tax": 31.59,
        "shipping_incl_tax": 50,
        "base_shipping_incl_tax": 50,
        "base_currency_code": "USD",
        "quote_currency_code": "USD",
        "coupon_code": "discount10",
        "items_qty": 10,
        "items": [
            {
                "item_id": 165,
                "price": 3.07,
                "base_price": 3.07,
                "qty": 5,
                "row_total": 15.35,
                "base_row_total": 15.35,
                "row_total_with_discount": 0,
                "tax_amount": 0.4,
                "base_tax_amount": 0.4,
                "tax_percent": 2.9,
                "discount_amount": 1.54,
                "base_discount_amount": 1.54,
                "discount_percent": 10,
                "price_incl_tax": 3.16,
                "base_price_incl_tax": 3.16,
                "row_total_incl_tax": 15.8,
                "base_row_total_incl_tax": 15.8,
                "options": "[]",
                "weee_tax_applied_amount": null,
                "weee_tax_applied": null,
                "name": "Simple Product 129"
            },
            {
                "item_id": 166,
                "price": 3.07,
                "base_price": 3.07,
                "qty": 5,
                "row_total": 15.35,
                "base_row_total": 15.35,
                "row_total_with_discount": 0,
                "tax_amount": 0.4,
                "base_tax_amount": 0.4,
                "tax_percent": 2.9,
                "discount_amount": 1.53,
                "base_discount_amount": 1.53,
                "discount_percent": 10,
                "price_incl_tax": 3.16,
                "base_price_incl_tax": 3.16,
                "row_total_incl_tax": 15.79,
                "base_row_total_incl_tax": 15.79,
                "options": "[]",
                "weee_tax_applied_amount": null,
                "weee_tax_applied": null,
                "name": "Simple Product 159"
            }
        ],
        "total_segments": [
            {
                "code": "subtotal",
                "title": "Subtotal",
                "value": 30.7
            },
            {
                "code": "discount",
                "title": "Discount (discount10)",
                "value": -3.07
            },
            {
                "code": "shipping",
                "title": "Shipping & Handling (Flat Rate - Fixed)",
                "value": 50
            },
            {
                "code": "tax",
                "title": "Tax",
                "value": 0.8,
                "extension_attributes": {
                    "tax_grandtotal_details": [
                        {
                            "amount": 0.8,
                            "rates": [
                                {
                                    "percent": "2.9",
                                    "title": "US-CO"
                                }
                            ],
                            "group_id": 1
                        }
                    ]
                }
            },
            {
                "code": "grand_total",
                "title": "Grand Total",
                "value": 78.43,
                "area": "footer"
            }
        ]
    }
}

**Comment by swathishs** [comment]
@ldc321: The issue is not reproducible in Magento 2.3.5p1 instance.

1. Frontend:
![image](https://user-images.githubusercontent.com/58288685/83893662-dc72b400-a76d-11ea-9061-59239eff81b7.png)

2. Response:
{
    "payment_methods": [
        {
            "code": "checkmo",
            "title": "Check / Money order"
        }
    ],
    "totals": {
        "grand_total": 34.49,
        "base_grand_total": 35.06,
        "subtotal": 21.66,
        "base_subtotal": 21.66,
        "discount_amount": -2.17,
        "base_discount_amount": -2.17,
        "subtotal_with_discount": 19.49,
        "base_subtotal_with_discount": 19.49,
        "shipping_amount": 15,
        "base_shipping_amount": 15,
        "shipping_discount_amount": 0,
        "base_shipping_discount_amount": 0,
        "tax_amount": 0.57,
        "base_tax_amount": 0.57,
        "weee_tax_applied_amount": null,
        "shipping_tax_amount": 0,
        "base_shipping_tax_amount": 0,
        "subtotal_incl_tax": 22.29,
        "shipping_incl_tax": 15,
        "base_shipping_incl_tax": 15,
        "base_currency_code": "USD",
        "quote_currency_code": "USD",
        "coupon_code": "test",
        "items_qty": 3,
        "items": [
            {
                "item_id": 162,
                "price": 7.22,
                "base_price": 7.22,
                "qty": 3,
                "row_total": 21.66,
                "base_row_total": 21.66,
                "row_total_with_discount": 0,
                "tax_amount": 0.57,
                "base_tax_amount": 0.57,
                "tax_percent": 2.9,
                "discount_amount": 2.17,
                "base_discount_amount": 2.17,
                "discount_percent": 10,
                "price_incl_tax": 7.43,
                "base_price_incl_tax": 7.43,
                "row_total_incl_tax": 22.29,
                "base_row_total_incl_tax": 22.29,
                "options": "[]",
                "weee_tax_applied_amount": null,
                "weee_tax_applied": null,
                "name": "Simple&Product 1"
            }
        ],
        "total_segments": [
            {
                "code": "subtotal",
                "title": "Subtotal",
                "value": 21.66
            },
            {
                "code": "discount",
                "title": "Discount (test)",
                "value": -2.17
            },
            {
                "code": "shipping",
                "title": "Shipping & Handling (Flat Rate - Fixed)",
                "value": 15
            },
            {
                "code": "tax",
                "title": "Tax",
                "value": 0.57,
                "extension_attributes": {
                    "tax_grandtotal_details": [
                        {
                            "amount": 0.57,
                            "rates": [
                                {
                                    "percent": "2.9",
                                    "title": "US-CO"
                                }
                            ],
                            "group_id": 1
                        }
                    ]
                }
            },
            {
                "code": "grand_total",
                "title": "Grand Total",
                "value": 35.06,
                "area": "footer"
            }
        ]
    }
}

**Comment by swathishs** [comment]
Hi @ldc321 , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop and 2.3.5p1 develop an instance
If you'd like to update the issue, please reopen it.
