### ISSUE TITLE
No products-import under CMS > system > import > Entity Type

### ISSUE THREAD

**Issue by prejauw** [magento/magento2#2840]
My version of Magento is ver.2.0.0. I would like to import an CSV with products data.

Like I have seen earlier in tutorials, there is an option "product" to pick from in system > Import > Entity Type.

But I only see": - Advance Pricing - Customers and Addresses - Customer and Main file - Customer Addresses

**Comment by andimov** [comment]
@prejauw

Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
We will close this issue as not updated more than 2 weeks if this issue still reproducible please feel free to create the new one.
