### ISSUE TITLE
Bundle product import with multiple options

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#28404]
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. In backend go to System -> Import, select product import and import bundle product using the attached file (rename to csv)
[catalog_product.txt](https://github.com/magento/magento2/files/4695155/catalog_product.txt)
2. Check that product is created with 3 options:
![Sprite_Yoga_Strap_Fixed_Bundle_Products_Inventory_Catalog_Magento_Admin](https://user-images.githubusercontent.com/8502721/83135608-ba828d00-a0ee-11ea-9a35-dbcd882e2c1a.png)
3. Run reindex, clean cache
4. Search product on frontend - product is present:
![Zoekresultaten_voor_‘Sprite_Yoga’](https://user-images.githubusercontent.com/8502721/83136007-66c47380-a0ef-11ea-9732-2aaac1274c44.png)
5. Now import the same file second time, run reindex and clean cache
6. Check search result on frontend

### Expected result (*)

Bundle product is present on search result page as on step 4

### Actual result (*)

Bundle product is gone from search result page:
![Zoekresultaten_voor_‘Sprite_Yoga’ (1)](https://user-images.githubusercontent.com/8502721/83136395-126dc380-a0f0-11ea-95a7-987f7fb4cd25.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28404-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28404-2-4-develop.instances.magento-community.engineering/admin_e0eb](https://i-28404-2-4-develop.instances.magento-community.engineering/admin_e0eb)
Login: `f825f3df` Password: `4c9ad6c38662`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@lyusya-nnn: The issue is not reproducible in the 2.4-develop instance

Please find the attachment below:
1. **Bundle product**:
![image](https://user-images.githubusercontent.com/58288685/83152868-ed8f4580-a11b-11ea-9d41-8f4761cebfc6.png)

2. **Frontend**:
![image](https://user-images.githubusercontent.com/58288685/83152954-07308d00-a11c-11ea-91c2-493e5c990db5.png)

3. **Second-time file imported**:
![image](https://user-images.githubusercontent.com/58288685/83153027-19aac680-a11c-11ea-89d4-6fa4073787ba.png)

4. **Search page after second import**:
![image](https://user-images.githubusercontent.com/58288685/83154089-562af200-a11d-11ea-841b-6df8e0578338.png)

**Comment by swathishs** [comment]
@magento give me 2.3.5p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5p1 instance for you

**Comment by swathishs** [comment]
Hi @lyusya-nnn, thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.
