### ISSUE TITLE
login page stops working - redis sessions

### ISSUE THREAD

**Issue by mariojacobo** [magento/magento2#28410]
### Summary (*)

We are running Magento2 on EKS and have been seeing some issues we just cannot explain. At rest, everything is working fine, no errors, no latency, lgin page works just fine. As soon as we start stress testing with 100s of users and the cluster scales up, we see some initial latency to REDIS and MySQL(which is pretty normal I'd say due to scaling time and what not). 15-20 min into the test, when all autoscaling finishes and it stabilizes, all values return to normal and the latency/slowness is gone. 

The behavior we cannot explain happens right after that. All of a sudden, the /customer/account/login page stops working. We are able to view the page, add the login credentials, but it never returns anything and after 2-3 min approx, we get "ERR_HTTP2_PROTOCOL_ERROR".  

**The fix** is to flush all the sessions in Redis, which bring back the login page and our orders skyrocket. This works for a little bit, until we have to flush again. 

In terms of resources, CPU barely hits 5% and RAM is not even at 50%. Connections are also on the low end, 150-200/s an nothing else stands out. 

### Preconditions (*)

1. Magento version 2.3.5 
2. PHP 7.2.3
3. Redis 5.0  and ElastiCache (tried both with the same result)
4. Aurora DB 

Traffic flow:    NGINX Ingress > Varnish > AWS Internal ALB (for least connection algorithm)>Frontend (NGINX+PHP-FPM in separate containers in the same POD) > Redis/MySQL

### Steps to reproduce (*)

N/A 

### Expected result (*)

We would expect to not have to flush redis user sessions at all. 

### Actual result (*)
Approx every 30+/- min or so, we need to flush the redis user sessions. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Hexmage** [comment]
@mariojacobo This sounds like your redis sessions is reaching its memory cap. Which means no new sessions can be made which stops logging in.

**Comment by mariojacobo** [comment]
@Hexmage  that's the first thing we looked at and we are nowhere near the memory cap. with magento out of the box, we couldnt replicate the issue, so it's some custom module that's giving us issues. the hard part is tracking down which module is blocking us, as the issue is only triggered under high stress

**Comment by krishprakash** [comment]
Hi @mariojacobo. This should be any of your custom module issue.
GitHub issue tracker is intended for magento core technical issues only kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) to general discuss about this problem
