### ISSUE TITLE
Magento 2.3.2-p2 upgrade to latest security patch

### ISSUE THREAD

**Issue by vDeggial** [magento/magento2#28411]
Hi there, 

We are currently running Magento 2.3.2-p2 on our client's live store. We have been holding off on upgrades to 2.3.3 and 2.3.4 as those had issues that would affect functionality of our client's store and that is not an option

Is there a way to upgrade our 2.3.2-p2 store to latest security patch 2.3.5-p1 without upgrading to the 2.3.5 functionality (essentially keeping it 2.3.2 but with latest security fixes) making sure that all the modules still work the same way as they do now and don't break?

Thanks in advance

**Comment by krishprakash** [comment]
Hi @vDeggial,
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discussion about this. You will surely get any solution
Thank You !!
