### ISSUE TITLE
Magento 2 Setup folder

### ISSUE THREAD

**Issue by rokity** [magento/magento2#2841]
Hi 

In Magento 2 module the "Setup" folder exist or is deprecated?
I want to know this because I want to know if when magento install the module , that runs the php file inside "Setup" folder.

Thank

**Comment by mrkhoa99** [comment]
You can find under root folder: _root_folder/setup_

![setup folder](https://cloud.githubusercontent.com/assets/6185767/12053649/d4e98ff0-af4d-11e5-840e-d0a80e96d97c.png)

**Comment by mrkhoa99** [comment]
<p>The GitHub issue tracker is intended for technical issues only. Please refer to the <a href="https://community.magento.com" target="_blank">Community Forums</a> or <a href="http://magento.stackexchange.com/" target="_blank">Magento Stack Exchange</a> site for technical questions. In your case, the <a href="https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2" target="_blank">programming questions forum</a> is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.</p>
