### ISSUE TITLE
Newsletter subscription confirmation email never sent again

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#28422]
### Preconditions (*)
1. Magento 2.4-develop
### Steps to reproduce (*)
1. Enable newsletter subscription confirmation ("Need to Confirm" option)
2. Log in with an account which is not subscribed to the newsletter
3. Subscribe to the newsletter from My account > Newsletter Subscription
4. An email asking for subscription confirmation is received.
5. Imagine the user does not confirm, deletes the email, forgets it or anything else, but he does not confirm his newsletter subscription
6. He comes back some time later and wants to subscribe to the newsletter, so he does the process again
7. Subscribe to the newsletter from My account > Newsletter Subscription

### Expected result (*)
1. The confirmation email is sent again

### Actual result (*)

1. The confirmation email is never sent again.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VincentMarmiesse** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse, here is your [Magento instance](https://i-28422-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28422-2-3-5-p1.instances.magento-community.engineering/admin_0ac6](https://i-28422-2-3-5-p1.instances.magento-community.engineering/admin_0ac6)
Login: `a2fc3d31` Password: `07b624bcd9fb`
Instance will be terminated in up to 3 hours.

**Comment by VincentMarmiesse** [comment]
Test instance does not seem to send any email so I can't test it.

**Comment by sambath1293** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sambath1293, here is your [Magento instance](https://i-28422-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28422-2-4-develop.instances.magento-community.engineering/admin_44da](https://i-28422-2-4-develop.instances.magento-community.engineering/admin_44da)
Login: `4430e10d` Password: `a648179ed92c`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36520` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by konarshankar07** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-28422-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28422-2-4-develop.instances.magento-community.engineering/admin_27fe](https://i-28422-2-4-develop.instances.magento-community.engineering/admin_27fe)
Login: `17bddc17` Password: `99f245bab3d8`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for your report. 
The issue has been fixed in magento/magento2#29510 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [1a7c8cd619b4936fd544ac669bf4f5e66bcc7d34](https://github.com/magento/magento2/commit/1a7c8cd619b4936fd544ac669bf4f5e66bcc7d34)
 - [6e53e0d90b3cbc86ee368c35605615d713fe9682](https://github.com/magento/magento2/commit/6e53e0d90b3cbc86ee368c35605615d713fe9682)
 - [ea584f9815ec3b119e9ac73ccc773435c7727960](https://github.com/magento/magento2/commit/ea584f9815ec3b119e9ac73ccc773435c7727960)
 - [ab3db167e1594e935350d4be6494ce1f56c48b4f](https://github.com/magento/magento2/commit/ab3db167e1594e935350d4be6494ce1f56c48b4f)

The fix will be available with the upcoming 2.4.2 release.
