### ISSUE TITLE
Logic failed for arrays in CatalogSearchModel/ResourceModel/Fulltext/Collection::addFieldToFilter 

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#2842]
CatalogSearchModel/ResourceModel/Fulltext/Collection::addFieldToFilter 

``` php
public function addFieldToFilter($field, $condition = null)
    {
        if ($this->queryResponse !== null) {
            throw new \RuntimeException('Illegal state');
        }
        if (!is_array($condition) || !in_array(key($condition), ['from', 'to'])) {
            $this->requestBuilder->bind($field, $condition);
        } else {
            if (!empty($condition['from'])) {
                $this->requestBuilder->bind("{$field}.from", $condition['from']);
            }
            if (!empty($condition['to'])) {
                $this->requestBuilder->bind("{$field}.to", $condition['to']);
            }
        }
        return $this;
    }
```

In IF condition it is checking !in_array(key($condition), ['from', 'to']), which evaluate to FALSE if $condition is a array.  
Eg:
$condition=[12,13];
!in_array(key($condition), ['from', 'to']) is evaluate to FALSE because key($condition) return 0 and in_array(0,['from','to']) returns TRUE since 0 is the index of 'from'. Because of this any array passed as the $condition will not be bind to the RequestBuilder except this ['from'=>'','to'=>'']

**Comment by kandy** [comment]
Internal ticket created MAGETWO-48445

**Comment by magento-engcom-team** [comment]
@bgkavinga, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by stkrelax** [comment]
### Reopening
Problem still exists.

### Clearifying Issue:

1. create 10 products
2. create decimal attribute volume
3. set volume to 2 on one product
4. make volume filterable
5. go to product list an filter volume "0 and more"

### Expected Result
- only product with the volume set should be shown
### Actual Result
- all 10 products are shown

### Reason
volume with filter "-" will be ignored by addFildToFilter here
https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php#L364
https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php#L369


Connected Pullrequest from someone.
#5291
Connected INTERNAL TICKETS
MAGETWO-56736
