### ISSUE TITLE
$store.getFrontendName variable in Order Confirmation email wrong

### ISSUE THREAD

**Issue by rickcj** [magento/magento2#28423]
### Preconditions (*)
Magento 2.3.5
Just upgraded from 2.3.4 to 2.3.5 on staging site and noticed difference after placing test order.

The $store.getFrontendName is now getting the Store Name from the stores->store name not General Configuration -> Store Name:
{{trans "Thank you for your order from %store_name." store_name=$store.getFrontendName()}}

If I insert the Store Name variable in Email Templates it inserts:
{{config path="general/store_information/name"}}

This produces the expected Company Name.

### Steps to reproduce (*)
Place order and receive confirmation email.

### Expected result (*)
Order confirmation email to contain the Store Name:
Subject: Your Company Name order confirmation
Content includes: Thank you for your order from Company Name. 

### Actual result (*)
Order confirmation email contains wrong details:
Subject: Your Main Website Store order confirmation
Content includes: Thank you for your order from Main Website Store.

**Comment by rickcj** [comment]
@magento give me 2.3.5-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rickcj. Thank you for your request. I'm working on Magento 2.3.5-develop instance for you

**Comment by rickcj** [comment]
How long for develop instance?

**Comment by rickcj** [comment]
@magento how long for develop instance?

**Comment by rickcj** [comment]
@magento give me 2.3.5-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rickcj. Thank you for your request. I'm working on Magento 2.3.5-develop instance for you
