### ISSUE TITLE
Issue installing magento 2.3.5p1 on local server stuck at 51%

### ISSUE THREAD

**Issue by hsmuhammad12** [magento/magento2#28429]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
Hi @hsmuhammad12. Closing this issue as you already added same #28430
