### ISSUE TITLE
Issue installing magento 2.3.5p1 on local server stuck at 51%

### ISSUE THREAD

**Issue by hsmuhammad12** [magento/magento2#28430]
### 
I'm stuck at 51% while installing magento 2.3.5p1
![magento error](https://user-images.githubusercontent.com/66122550/83285153-3831c000-a1f7-11ea-8401-ebdac2afdd70.png)``

Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_AdminAnalytics':

Module 'Magento_Store':

Module 'Magento_AdobeIms':

Module 'Magento_AdobeImsApi':

Module 'Magento_AdobeStockAdminUi':

Module 'Magento_MediaGallery':

Module 'Magento_AdobeStockAssetApi':

Module 'Magento_AdobeStockClient':

Module 'Magento_AdobeStockClientApi':

Module 'Magento_AdobeStockImage':

Module 'Magento_AdobeStockImageAdminUi':

Module 'Magento_AdobeStockImageApi':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Amqp':

Module 'Magento_AmqpStore':

Module 'Magento_Config':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_AuthorizenetGraphQl':

Module 'Magento_Search':

Module 'Magento_Backup':

Module 'Magento_AdminNotification':

Module 'Magento_BraintreeGraphQl':

Module 'Magento_Indexer':

Module 'Magento_Authorization':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_Quote':

Module 'Magento_Security':

Module 'Magento_GraphQl':

Module 'Magento_EavGraphQl':

Module 'Magento_StoreGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':

Module 'Magento_CatalogRule':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_CatalogGraphQl':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreementsGraphQl':

Module 'Magento_Sales':

Module 'Magento_CmsGraphQl':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CmsUrlRewriteGraphQl':

Module 'Magento_User':

Module 'Magento_Checkout':

Module 'Magento_ConfigurableProduct':

Module 'Magento_QuoteGraphQl':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_Csp':

Module 'Magento_CurrencySymbol':

Module 'Magento_Captcha':

Module 'Magento_Integration':

Module 'Magento_Downloadable':

Module 'Magento_CustomerGraphQl':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_DirectoryGraphQl':

Module 'Magento_DownloadableGraphQl':

Module 'Magento_CustomerDownloadableGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_CardinalCommerce':

Module 'Magento_CatalogCustomerGraphQl':

Module 'Magento_AdvancedSearch':

Module 'Magento_Elasticsearch':

Module 'Magento_Elasticsearch7':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAdwords':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GoogleShoppingAds':

Module 'Magento_BundleGraphQl':

Module 'Magento_PageCache':

Module 'Magento_GroupedProduct':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedCatalogInventory':

Module 'Magento_GroupedProductGraphQl':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Bundle':

Module 'Magento_InstantPurchase':

Module 'Magento_Analytics':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryAdvancedCheckout':

Module 'Magento_InventoryApi':

Module 'Magento_InventoryBundleProduct':

Module 'Magento_InventoryBundleProductAdminUi':

Module 'Magento_InventoryCatalog':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryCatalogSearch':

Module 'Magento_InventoryConfigurableProduct':

Module 'Magento_InventoryConfigurableProductAdminUi':

Module 'Magento_InventoryConfigurableProductIndexer':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryDistanceBasedSourceSelection':

Module 'Magento_InventoryDistanceBasedSourceSelectionAdminUi':

Module 'Magento_InventoryDistanceBasedSourceSelectionApi':

Module 'Magento_InventoryElasticsearch':

Module 'Magento_InventoryExportStockApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventorySalesApi':

Module 'Magento_InventoryGroupedProduct':

Module 'Magento_InventoryGroupedProductAdminUi':

Module 'Magento_InventoryGroupedProductIndexer':

Module 'Magento_InventoryImportExport':

Module 'Magento_InventoryCache':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_Reports':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryProductAlert':

Module 'Magento_InventoryRequisitionList':

Module 'Magento_InventoryReservations':

Module 'Magento_InventoryReservationCli':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventoryExportStock':

Module 'Magento_InventorySalesAdminUi':

Module 'Magento_CatalogInventoryGraphQl':

Module 'Magento_InventorySalesFrontendUi':

Module 'Magento_InventorySetupFixtureGenerator':

Module 'Magento_InventoryShipping':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelection':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_AdobeStockAsset':

Module 'Magento_MediaGalleryApi':

Module 'Magento_MediaStorage':

Module 'Magento_MessageQueue':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_MsrpConfigurableProduct':

Module 'Magento_MsrpGroupedProduct':

Module 'Magento_Multishipping':

Module 'Magento_MysqlMq':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_GraphQlCache':

Module 'Magento_Authorizenet':

Module 'Magento_Vault':

Module 'Magento_Paypal':

Module 'Magento_PaypalGraphQl':

Module 'Magento_PaypalCaptcha':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_AuthorizenetAcceptjs':

Module 'Magento_QuoteAnalytics':

Module 'Magento_ConfigurableProductGraphQl':

Module 'Magento_RelatedProductGraphQl':

Module 'Magento_ReleaseNotification':

Module 'Magento_InventoryLowQuantityNotificationAdminUi':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_AuthorizenetCardinal':

Module 'Magento_CheckoutAgreements':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesGraphQl':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Braintree':

Module 'Magento_UrlRewrite':

Module 'Magento_Elasticsearch6':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_SendFriendGraphQl':

Module 'Magento_InventoryShippingAdminUi':

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_InventoryGraphQl':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_Webapi':

Module 'Magento_SwaggerWebapi':

Module 'Magento_SwaggerWebapiAsync':

Module 'Magento_Swatches':

Module 'Magento_SwatchesGraphQl':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxGraphQl':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogCmsGraphQl':

Module 'Magento_ThemeGraphQl':

Module 'Magento_Tinymce3':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogUrlRewriteGraphQl':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_CatalogRuleConfigurable':

Module 'MSP_ReCaptcha':

Module 'Magento_VaultGraphQl':

Module 'Magento_Version':

Module 'Magento_Swagger':

Module 'Magento_WebapiAsync':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':

Module 'Magento_WeeeGraphQl':

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':

Module 'Magento_WishlistAnalytics':

Module 'Magento_WishlistGraphQl':

Module 'Amazon_Core':

Module 'Amazon_Login':

Module 'Amazon_Payment':

Module 'Dotdigitalgroup_Email':

Module 'Dotdigitalgroup_Chat':

Module 'Klarna_Core':

Module 'Klarna_Ordermanagement':

Module 'Klarna_Kp':

Module 'Magento_PaypalReCaptcha':

Module 'MSP_TwoFactorAuth':

Module 'Temando_ShippingRemover':

Module 'Vertex_Tax':

Module 'Vertex_AddressValidation':

Module 'Yotpo_Yotpo':

Schema post-updates:
Module 'Magento_AdminAnalytics':

Module 'Magento_Store':

Module 'Magento_AdobeIms':

Module 'Magento_AdobeImsApi':

Module 'Magento_AdobeStockAdminUi':

Module 'Magento_MediaGallery':

Module 'Magento_AdobeStockAssetApi':

Module 'Magento_AdobeStockClient':

Module 'Magento_AdobeStockClientApi':

Module 'Magento_AdobeStockImage':

Module 'Magento_AdobeStockImageAdminUi':

Module 'Magento_AdobeStockImageApi':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Amqp':
Running schema recurring...

Module 'Magento_AmqpStore':

Module 'Magento_Config':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_AuthorizenetGraphQl':

Module 'Magento_Search':

Module 'Magento_Backup':

Module 'Magento_AdminNotification':

Module 'Magento_BraintreeGraphQl':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Authorization':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_Cms':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Quote':

Module 'Magento_Security':

Module 'Magento_GraphQl':

Module 'Magento_EavGraphQl':

Module 'Magento_StoreGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_CatalogRule':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_CatalogGraphQl':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':
Running schema recurring...

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreementsGraphQl':

Module 'Magento_Sales':

Module 'Magento_CmsGraphQl':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CmsUrlRewriteGraphQl':

Module 'Magento_User':

Module 'Magento_Checkout':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_QuoteGraphQl':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':
Running schema recurring...

Module 'Magento_Csp':

Module 'Magento_CurrencySymbol':

Module 'Magento_Captcha':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_Downloadable':

Module 'Magento_CustomerGraphQl':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_DirectoryGraphQl':

Module 'Magento_DownloadableGraphQl':

Module 'Magento_CustomerDownloadableGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_CardinalCommerce':

Module 'Magento_CatalogCustomerGraphQl':

Module 'Magento_AdvancedSearch':

Module 'Magento_Elasticsearch':

Module 'Magento_Elasticsearch7':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAdwords':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GoogleShoppingAds':

Module 'Magento_BundleGraphQl':

Module 'Magento_PageCache':

Module 'Magento_GroupedProduct':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedCatalogInventory':

Module 'Magento_GroupedProductGraphQl':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_InstantPurchase':

Module 'Magento_Analytics':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryAdvancedCheckout':

Module 'Magento_InventoryApi':

Module 'Magento_InventoryBundleProduct':

Module 'Magento_InventoryBundleProductAdminUi':

Module 'Magento_InventoryCatalog':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryCatalogSearch':

Module 'Magento_InventoryConfigurableProduct':

Module 'Magento_InventoryConfigurableProductAdminUi':

Module 'Magento_InventoryConfigurableProductIndexer':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryDistanceBasedSourceSelection':

Module 'Magento_InventoryDistanceBasedSourceSelectionAdminUi':

Module 'Magento_InventoryDistanceBasedSourceSelectionApi':

Module 'Magento_InventoryElasticsearch':

Module 'Magento_InventoryExportStockApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventorySalesApi':

Module 'Magento_InventoryGroupedProduct':

Module 'Magento_InventoryGroupedProductAdminUi':

Module 'Magento_InventoryGroupedProductIndexer':

Module 'Magento_InventoryImportExport':

Module 'Magento_InventoryCache':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryProductAlert':

Module 'Magento_InventoryRequisitionList':

Module 'Magento_InventoryReservations':

Module 'Magento_InventoryReservationCli':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventoryExportStock':

Module 'Magento_InventorySalesAdminUi':

Module 'Magento_CatalogInventoryGraphQl':

Module 'Magento_InventorySalesFrontendUi':

Module 'Magento_InventorySetupFixtureGenerator':

Module 'Magento_InventoryShipping':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelection':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_AdobeStockAsset':

Module 'Magento_MediaGalleryApi':

Module 'Magento_MediaStorage':

Module 'Magento_MessageQueue':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_MsrpConfigurableProduct':

Module 'Magento_MsrpGroupedProduct':

Module 'Magento_Multishipping':

Module 'Magento_MysqlMq':
Running schema recurring...

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_GraphQlCache':

Module 'Magento_Authorizenet':

Module 'Magento_Vault':

Module 'Magento_Paypal':

Module 'Magento_PaypalGraphQl':

Module 'Magento_PaypalCaptcha':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Magento_AuthorizenetAcceptjs':

Module 'Magento_QuoteAnalytics':

Module 'Magento_ConfigurableProductGraphQl':

Module 'Magento_RelatedProductGraphQl':

Module 'Magento_ReleaseNotification':

Module 'Magento_InventoryLowQuantityNotificationAdminUi':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_AuthorizenetCardinal':

Module 'Magento_CheckoutAgreements':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesGraphQl':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Braintree':

Module 'Magento_UrlRewrite':

Module 'Magento_Elasticsearch6':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_SendFriendGraphQl':

Module 'Magento_InventoryShippingAdminUi':

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_InventoryGraphQl':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_Webapi':

Module 'Magento_SwaggerWebapi':

Module 'Magento_SwaggerWebapiAsync':

Module 'Magento_Swatches':

Module 'Magento_SwatchesGraphQl':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxGraphQl':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogCmsGraphQl':

Module 'Magento_ThemeGraphQl':

Module 'Magento_Tinymce3':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogUrlRewriteGraphQl':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_CatalogRuleConfigurable':

Module 'MSP_ReCaptcha':

Module 'Magento_VaultGraphQl':

Module 'Magento_Version':

Module 'Magento_Swagger':

Module 'Magento_WebapiAsync':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_WeeeGraphQl':

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_WishlistAnalytics':

Module 'Magento_WishlistGraphQl':

Module 'Amazon_Core':

Module 'Amazon_Login':

Module 'Amazon_Payment':

Module 'Dotdigitalgroup_Email':
Running schema recurring...

Module 'Dotdigitalgroup_Chat':

Module 'Klarna_Core':

Module 'Klarna_Ordermanagement':

Module 'Klarna_Kp':

Module 'Magento_PaypalReCaptcha':

Module 'MSP_TwoFactorAuth':

Module 'Temando_ShippingRemover':

Module 'Vertex_Tax':

Module 'Vertex_AddressValidation':

Module 'Yotpo_Yotpo':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [compiled_config] => 1 [eav] => 1 [customer_notification] => 1 [config_integration] => 1 [config_integration_api] => 1 [google_product] => 1 [full_page] => 1 [config_webservice] => 1 [translate] => 1 [vertex] => 1 )

Installing data...
Data install/update:
Disabling caches:
Current status:
Array ( [layout] => 0 [block_html] => 0 [full_page] => 0 )
Module 'Magento_AdminAnalytics':

Module 'Magento_Store':

Module 'Magento_AdobeIms':

Module 'Magento_AdobeImsApi':

Module 'Magento_AdobeStockAdminUi':

Module 'Magento_MediaGallery':

Module 'Magento_AdobeStockAssetApi':

Module 'Magento_AdobeStockClient':

Module 'Magento_AdobeStockClientApi':

Module 'Magento_AdobeStockImage':

Module 'Magento_AdobeStockImageAdminUi':

Module 'Magento_AdobeStockImageApi':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Amqp':

Module 'Magento_AmqpStore':

Module 'Magento_Config':

Module 'Magento_Theme':

**Comment by krishprakash** [comment]
Hi @hsmuhammad12.
Seems issue is already added and in open state #28055 
You can track the conversation from above issue link
Thanks !!
