### ISSUE TITLE
UI experience improvement for Template Insert Variable popup

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#28436]
### Summary (*)
Design update as per the Magento 2 standard UI experience improvement on Email template Insert Variable popup.

**To reach follow path :** 
Admin - Marketing - Communications - Email Templates -  Add New Template - Template Information Section -  click on Insert Variable button. 

### Examples (*)

Please follow current screenshot : 
![image](https://user-images.githubusercontent.com/43603387/83323044-c3539a00-a279-11ea-80f8-9df0ea98a1ea.png)

Updated screenshot 
![image](https://user-images.githubusercontent.com/43603387/83323052-d9615a80-a279-11ea-829e-6f61e9fe275e.png)

### Proposed solution

Design update as per the Magento 2 standard UI experience improvement on Email template Insert Variable popup.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-28436-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28436-2-4-develop.instances.magento-community.engineering/admin_4b4f](https://i-28436-2-4-develop.instances.magento-community.engineering/admin_4b4f)
Login: `791f1cf7` Password: `e3a51b28a828`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @abrarpathan19,
I have verified the default Magento Email template Insert variable popup. It's looking fine But If you want to improve the popup UI. You can work on it and update the Popup UI as per the Magento Theme.

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34769` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @abrarpathan19 

In general, literally, your statement sounds quite logical: _"Update design to be alignment with Magento 2 standard UI"_

But after reviewing the result, it looks not very friendly for users. Especially on a big screen(resolution), a lot of contrast lines(dark and white)...

After the additional discussion was decided to leave the design as is now for this exceptional case.

Thank you for your contribution and effort but I have to close it.
