### ISSUE TITLE
require js error in admin dashboard breaking catalog, order view

### ISSUE THREAD

**Issue by brendanmckeown** [magento/magento2#2843]
My repo is up to date on the 2.0 branch.  Some of the admin dashboard areas (product/catalog, sales/orders) are broken (endless loading spinner) due to a JS error occurring in require.js because a request for `/pub/static/adminhtml/Magento/backend/en_US/rjsResolver.js` is returning a 404 error.  I've checked, and this file does not exist.  I've tried clearing the contents of the `pub/static` directory but it keeps happening once the files are regenerated.

**Comment by brendanmckeown** [comment]
I ran `bin/magento setup:static-content:deploy` without any errors, but the problem persists.

**Comment by ghost** [comment]
does this occure after installation directly?
try delete /pub/static/frontend && /pub/static/adminhtml manualy and run ´´´ bin/magento setup:static-content:deploy ´´´ again. Also run ´´´bin/magento cache:clean´´´

some resources 
http://magento.stackexchange.com/questions/48894/missing-css-and-js-files-in-magento2-git-repository

http://magento.stackexchange.com/questions/64857/css-and-javascript-files-are-not-loading-after-magento-2-installation

hope this helped

**Comment by brendanmckeown** [comment]
@xhallix, 
Thanks for the response.  Yes, this occurs immediately after installation.  I've tried the following steps but still see the same error.
- Manually remove `pub/static/frontend` and `pub/static/adminhtml` 
- Run `bin/magento setup:static-content:deploy` in the Magento root directory
- Run `bin/magento cache:clean` 

All directories inside `pub` have permissions of `770` and files have `660`.  The group is the web server (in my case in Ubuntu, `www-data`).

Unlike the links you posted, it's only the one static JS file that is missing.  All the others, even those in the same `/pub/static/adminhtml/Magento/backend/en_US` directory, are loading fine.  Here's what I'm seeing in the admin dashboard under products/catalog:

![screen shot 2015-12-31 at 9 13 07 am](https://cloud.githubusercontent.com/assets/1933201/12065287/7885def8-afa2-11e5-8713-3bf493982aa8.png)

**Comment by brendanmckeown** [comment]
I experienced this same issue with two different installation methods: clone from the [git repo](https://github.com/magento/magento2) and `composer create-project`.

However, I just tried installing from the archive package [found here](https://www.magentocommerce.com/download) – and I'm not seeing the issue.

**Comment by anton-huz** [comment]
Hi Brendan,
As about

> `/rjsResolver.js` is returning a 404 error

There is no such file. [rjsResolver is just an alias](https://github.com/magento/magento2/blob/develop/app/code/Magento/Theme/view/base/requirejs-config.js#L13). Web page should load `/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/resolver.js`.

When such error occurs on your instance it means that requirejs-config.js was not generated properly or was not loaded in browser.

**Comment by brendanmckeown** [comment]
@guz-anton do you have any suggestions for how to fix this then?

**Comment by slug23** [comment]
I have this same problem when using chrome. Safari works fine. The cart popup won't work and I see "GET /pub/static/frontend/Magento/luma/en_US/rjsResolver.js HTTP/1.1" 404 0 in the logs.

Similarly for the admin products catalog page Safari works, but Chrome will not. Chrome gets a "GET /pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/grid/filters/field.html HTTP/1.1" 404 0

The behavior was the same for the archive package, git -b 2.0 , and composer installs.

**Comment by degaray** [comment]
I have the same thing

**Comment by hgpit** [comment]
I have just experienced the same issue after installing M2CE by downloading the developer.zip version from GitHub and installing it via Composer.

I have installed it about 10 times previously (M2EE & M2CE) from the official downloads and didn't see this problem once.

**Comment by cchamikara** [comment]
I have the same issue with magento 2 installation downloaded from official archive package

**Comment by lgt** [comment]
is there a workaround for this having the same issue on backend/frontend

**Comment by lutpiero** [comment]
I am having the same issue, some page on the backend not loading.

**Comment by lgt** [comment]
it seems to be a permission issue if I `chmod -R 777 pub` folder than everything works fine

**Comment by lutpiero** [comment]
I have successfully resolved this problems. I'am comparing the successful instalation in one of my box.
by adding a line on this file vendor/magento/module-theme/view/adminhtml/requirejs-config.js
the code was:

`"rjsResolver":          "mage/requirejs/resolver"`

**Comment by lucas-santos-chaordic** [comment]
I have the same issue. I tried everything i found in the web, but anything seems to fix this problem. I even tried a new installation from scratch... but the same problem happens, every time. 

The only way i found to fix the problem was editing the requirejs-config.js file. I needed to put the base url reference, and everything started working fine. 

require.config({"baseUrl":"http://<your domain>/pub/static/frontend/Magento/luma/en_US"});

Now i need to understand why this nase url is not being configured automatically. Any ideia?

**Comment by anton-huz** [comment]
Hi folks,
I see huge pool of message that you faced with _"rjsResolver.js is returning a 404 error"_. But you should understand that this an _environment issue_ not _Magento itself_.

So if you, guys, still faced with or you want to help us identify the problem we need:
- How you installed Magento
- What version of Magento
- If you do _upgrade_ than both version of old one and newer
- Environment configuration: what server, what versions
- Browser that you are using for. (Try to retest with new Private window at first)

Without such info I will be forced to close issue as _Cannot reproduce_.

**Comment by stamster** [comment]
How come it's not Magento issue?! Of course it is, those JS files are in adminhtml core, i.e. not in third party modules or so.

I have experienced this issue after doing migration from one dir onto another (`cp -rv`). Using latest Magento v2.1. In 2.0.x releases I had no such issues when moving app from development to staging environment. 
Using nginx as a web server, PHP 5.6.x as standalone app server and MariaDB for DB.

SOLUTION:
just clear the browser cache. How stupid is this, that your server-side app fails if your browser had a cached copy of static files?! After clearing the local cache, the adminhtml doesn't even request rjsResolver.js at all?!

**Comment by anton-huz** [comment]
Just a notice: investigation should be complete under MAGETWO-55348, internal ticket.

**Comment by vijaygupta108** [comment]
Hi Guys,
Have you got solution of this issue **Error: Script error for: rjsResolver** ?
Please reply, Thanks

**Comment by stamster** [comment]
@vijaygupta108 just clear the browser cache.

**Comment by vijaygupta108** [comment]
Hello Stamster,
Thanks for reply, 
I tried after clear browser cache and also checked on another system but its not working...
Please guess what may be issue..
Thanks

**Comment by tookuul-owner** [comment]
I experienced the same exact problem. Clean install of Magento Magento-CE-2.1.1_sample_data-2016-08-29-06-38-09.zip. 

No issues or alerts during installation.

Right after install images, js and css missing from frontend and backend. Backend becomes completely broken.

I executed steps recommended before:
- Manually remove pub/static/frontend and pub/static/adminhtml
- Run bin/magento setup:static-content:deploy in the Magento root directory
- Run bin/magento cache:clean

And it is working now.

Clearly an issue with Magento.

**Comment by tookuul-owner** [comment]
The same problem occurs with the plain installation (without sample data) from Magento-CE-2.1.1-2016-08-29-05-30-40.zip, and it gets solved with the same steps.

**Comment by anton-huz** [comment]
Not a bug. See [comment](https://github.com/magento/magento2/issues/6409#issuecomment-252253591) to #6409;

**Comment by fullstackdev0421** [comment]
Hi,tookuul-owner
I think that you didn't run command after Magento-CE-2.

you must run this command after magento install.
php bin/magento setup:static-content:deploy
