### ISSUE TITLE
Magento 2.3.5 -Customer group changing to "General" if customer change password from My Account

### ISSUE THREAD

**Issue by bojandavkov** [magento/magento2#28439]
### Preconditions (*)

Magento CE 2.3.5 with sample data is installed.

### Steps to reproduce (*)

Register new customer by creating a new account (/customer/account/create/)
Go to the admin panel and change the customer group from general to retailer and save the changes
Login at storefront with newly created user
After login go to the edit account page at the dashboard. (/customer/account/edit/)
Change the password and save changes

### Expected result (*)

The user remains in retailer group

### Actual result (*)

The user changes to general user group

@magento give me 2.3.5 instance

**Comment by krishprakash** [comment]
Hi @bojandavkov,
Seems issue is already added and still in Open state #26908 
You can review the conversation from given issue id 
So closing this as duplicate issue 
Thank you for your report !!
