### ISSUE TITLE
Parse error: syntax error, unexpected 'PDO' (T_STRING), expecting ',' or ')'

### ISSUE THREAD

**Issue by hsmuhammad12** [magento/magento2#28447]
i have facing this issue since magento is `installed, plz guide me how to fix it.
try {
            $this->_connection = new PDO(
                $dsn,
                $this->_config['username'],
                $this->_config['password'],
                $this->_config['driver_options']PDO->_construct('mysql:dbname=in...', 'root', '', Array)
            }

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by lbvaimo** [comment]
@magento i'm working on it

**Comment by engcom-Delta** [comment]
Hi @hsmuhammad12 thank you for your report. Looks like you have typo in your code
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
