### ISSUE TITLE
Not prepared data when exporting order grid

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#28448]
# Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)
1. Go to Sales order grid
2. Export to xml/csv
3. Field value, for example, **Status** is represented exactly like in DB (ex. in the grid the value is **Pending Payment**, bun in exported document is **pending_payment**.)

### Expected result (*)
1. I expect that the exported document would be the same as the grid.

### Actual result (*)

1. Fileds are represented  exactly like in DB without any preparation

Do you know how can I implement that?

**Comment by mack4hack** [comment]
@magento I am working on this

**Comment by mack4hack** [comment]
@magento I am working on this

**Comment by mack4hack** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @mack4hack. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mack4hack, here is your [Magento instance](https://i-28448-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-28448-2-3-4.instances.magento-community.engineering/admin_70f0](https://i-28448-2-3-4.instances.magento-community.engineering/admin_70f0)
Login: `f275933a` Password: `036b8623d029`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28448-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28448-2-4-develop.instances.magento-community.engineering/admin_8e8e](https://i-28448-2-4-develop.instances.magento-community.engineering/admin_8e8e)
Login: `27362f99` Password: `354bbf8751e2`
Instance will be terminated in up to 3 hours.

**Comment by mack4hack** [comment]
@madonzy its default behaviour of Magento. 

If you check this file vendor/magento/module-ui/Model/Export/ConvertToCsv.php, you will get more idea about it. When you export sales order data, the data provider is **sales_order_grid_data_source**
So it exports data from sales_order_grid table.

For Order Status Magento save "status code" in the table, that's why you seeing "payment_pending" instead of "Payment Pending"
 
Same is for Payment Method.

**Comment by swathishs** [comment]
@mack4hack: Hi mack for your kind information if the ticket is already assigned by someone you should not take that ticket and test. Since I already assigned the ticket and I am testing on it.

**Comment by madonzy** [comment]
@mack4hack yeah, I saw that file, but I reported a bug, because I don't see any cons for this approach and it makes difficult to extend the grid.

**Comment by mack4hack** [comment]
@swathishs sorry for the same. Will not happen again.

**Comment by swathishs** [comment]
@mack4hack: Hey no need of sorry just thought to share the information. So that next time you can check and assign the ticket.

**Comment by swathishs** [comment]
@madonzy: Thank you for your contribution and collaboration. Since this is the default behavior of Magento. I think your issue can be approved only like a feature request.
So it is not for this tracker.
Hello @sdzhepa . Could you transfer this issue to the feature requests repository?
