### ISSUE TITLE
Wrong calculation of total fields limit for mapping for Elasticsearch

### ISSUE THREAD

**Issue by kdebski** [magento/magento2#28454]
In Elasticsearch for some Magento attributes there are created two fields (eg. for text attributes) - raw field to perform full text search and keyword field to perform aggregations and sorting.
Currently calculating number of fields in elastic search doesn't take this into consideration, but is rather simple (app/code/Magento/Elasticsearch/module-elasticsearch/Model/Adapter/Elasticsearch.php):

`
    private function getMappingTotalFieldsLimit(array $allAttributeTypes): int
    {
        return count($allAttributeTypes) + self::MAPPING_TOTAL_FIELDS_BUFFER_LIMIT;
    }
` 

### Preconditions (*)

1. Magento Commerce Edition and Open Source Edition version 2.3.5
2. Installed module-elasticsearch 100.3.5
3. Installed ElasticSearch 7
4. Set up Elasticsearch as a search backend
5. More than 1000 attributes in products. 

### Steps to reproduce (*)

1. Create more than 1000 attributes for products. In my scenario there are numerous attribute sets specific for product families.
2. Create products for each family.
3. Run indexer.

### Expected result (*)

1. All products available in elasticsearch index.

### Actual result (*)

1. Elasticsearch error:
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Limit of total fields [3000] in index [magento2_product_2_v11] has been exceeded"}],"type":"illegal_argument_exception","reason":"Limit of total fields [3000] in index [magento2_product_2_v11] has been exceeded"},"status":400}`
2. New product wasn't indexed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JelleGe** [comment]
We are facing the same issue. What is the current status of this issue? The problem also occurs on Magento 2.4

**Comment by JelleGe** [comment]
Any updates about this issue? We still face this issue on Magento 2.4.1 with Elasticsearch 7

**Comment by dvolkering** [comment]
We're facing the same issue, also with magento 2.4.1 and Elasticsearch 7.6 (on Cloudways)

**Comment by JelleGe** [comment]
Problem in our case was solved by the Magento 2 patch; https://support.magento.com/hc/en-us/articles/360050423891-MDVA-30284-Magento-Patch-Elasticsearch-7-Limit-of-total-fields-XXXXX-in-index-has-been-exceeded

**Comment by dvolkering** [comment]
@JelleGe Thanks, I can confirm this resolves the issue.
