### ISSUE TITLE
Magento 2 Product  Page Image  Loading ever

### ISSUE THREAD

**Issue by mubasherahmed** [magento/magento2#28453]
Hi,
First of all, I would like to tell you that I am new I Magento.
I am facing an issue and i have tried all the suggestions available on the internet aa far as i know.
I have uploaded some products but when I tried to click on the products, products page loading forever as well as I cant press add to cart button and any button on this page.
Attached you can see the images 

![image](https://user-images.githubusercontent.com/62843932/83363723-d8284e80-a39b-11ea-8144-29894822cf29.png)
![image](https://user-images.githubusercontent.com/62843932/83363733-f0986900-a39b-11ea-8066-a6176159e164.png)

**Comment by sureshp1000** [comment]
Hi @mubasherahmed 

I believe you have installed Porto theme and the issue you are facing seems theme related issue.
Please check with Luma theme first.

Below steps may resolve your issue:
1. Install all the patches available from Porto theme.
 - For example: 2.3.x patch from Porto theme to your Magento installation.
2. If you have latest version of Magento then you may need to install patch for 2.3.3 and above if available with Porto theme.
3. Run command from SSH: php bin/magento setup:upgrade
4. Then run command: php bin/magento setup:static-content:deploy -f
5. Check on the front-end product page, the issue must be resolved now.

Note: If the issue still occurs then please contact to Porto theme support team.

Or let me know if above steps resolved your issue.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @mubasherahmed I'm not able to reproduce issue by steps you described on clean 2.4-develop.
![Peek 2020-11-06 16-09](https://user-images.githubusercontent.com/51681379/98375275-94bcc500-204a-11eb-9475-f79954a67444.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
