### ISSUE TITLE
Homepage url with store_code not working

### ISSUE THREAD

**Issue by zakaria-jnh** [magento/magento2#28458]
### Preconditions
1. Magento version: 2.3.4 CE installation with multiple stores configuration

### Steps to reproduce
1. Enable 'Add Store Code to Urls' setting in Admin
2. Set up multiple stores nginx configuration

### Expected result

1. the url {{base_url}}/store_code should be accessible and pointing to the cms home page

### Actual result

1. {{base_url}}/store_code/home url works but {{base_url}}/store_code generate this error:

`Fatal error: Uncaught Error: Maximum function nesting level of '4000' reached, aborting! in /vendor/magento/framework/Cache/Frontend/Adapter/Zend.php:147 Stack trace: #0 /vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(147): getmypid() #1 /vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(55): Magento\Framework\Cache\Frontend\Adapter\Zend->getFrontEnd() #2 /vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\Cache\Frontend\Adapter\Zend->load('resolved_stores...') #3 /vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\Cache\Frontend\Decorator\Bare->load('resolved_stores...') #4 /vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\Cache\Frontend\Decorator\Bare->load('resolved_stores...') #5 /vendor/magento/framework/App/Cache/Type/AccessPro in /vendor/magento/framework/Cache/Frontend/Adapter/Zend.php on line 147`

**Comment by engcom-Delta** [comment]
Hi @zakaria-jnh thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
Manual testing scenario:
1. Create additional website, store, view in Stores / All Stores 
![image](https://user-images.githubusercontent.com/51681379/99089943-a10aca00-25d6-11eb-9334-c298eb9d9981.png)
2. Enable "Add Store Code to Urls"  under Stores / Configuration /  Web /  Url Options 
3. Navigate to additional website home page

**Result:**
:heavy_check_mark: The urls {{base_url}}/store_code and  {{base_url}}/store_code/home open cms home page without errors
![Peek 2020-11-13 17-37](https://user-images.githubusercontent.com/51681379/99090420-4c1b8380-25d7-11eb-94f4-a7fd87329af0.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.
