### ISSUE TITLE
ElasticSearch storing admin value for Catalog Search index with cron job

### ISSUE THREAD

**Issue by aunik** [magento/magento2#28455]
When a product attribute(Select Type / Visual Swatch) has different values for admin and store , and Catalog Search(fulltext) index is executed by cron job , ElasticSearch stores the admin option value instead of store value .  If you run the Catalog Search index from CLI (bin/magento indexer:reindex ) you got correct store value 

### Preconditions (*)

1. Magento ver. 2.3.2-p2.
2.  ElasticSearch 6.7
3.  FullText / Catalog Search index mode : UPDATE BY SCHEDULE 
4.  Single store mode 
5. 550K  SKUs including 10K configurable SKUs / products 
6. 6 Attribute sets with 130 product attributes (including OOTB attributes)
7. 7 customer groups 
8. EAV index is disa

### Steps to reproduce (*)

(Reproduced in Magento ver. 2.3.2-p2 and 2.3.5
With Demo store Data)
1. Go to attribute config for the Color attribute properties. 
- Catalog Input Type for Store Owner : Visual Swatch

2. In “Manage Swatch (Values of Your Attribute)” section set different value for admin and Default Store .  
i.e Admin: Black_admin  ||  Default Store : Black
 _Admin_: Red_admin  ||  _Default Store_ : Red
![image](https://user-images.githubusercontent.com/3022280/83380593-4a089400-a3ac-11ea-9a82-5cc62397f613.png)

3. Now run indexer from CLI : _**“  bin/magento indexer: reindex  catalogsearch_fulltext “**_
4. When the index is done, review the ElasticSearch Document. You will get the correct store  value in the document 
![image](https://user-images.githubusercontent.com/3022280/83380625-5d1b6400-a3ac-11ea-89b1-4ccb98152203.png)

5. Now , invalidated/reset the catalog  search index **_“  bin/magento indexer: reset catalogsearch_fulltext “_**

6. Wait for the OOTB cron job to process the Category Search index by schedule. 
Review the product document in Elasticsearch. you will see it added admin value instead of store value 

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/3022280/83380692-889e4e80-a3ac-11ea-80f2-a8f11ff883d0.png)

color_value  in Elasticsearch document [Black , Purple , Red ]

### Actual result (*)

 color_value  in Elasticsearch document [Black_admin , Purple_admin , Red_admin ] , while index is executed by cron job
![image](https://user-images.githubusercontent.com/3022280/83380719-9d7ae200-a3ac-11ea-9c0c-2c964817848b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aunik** [comment]
In addition, the position_category_<n> is always 0 in ElasticSearch when the full-text index is processed by cron . but with CLI processed full-text index set correct value in ElasticSearch

**Comment by nrkapoor** [comment]
@aunik Thanks for reporting the issue. We are currently triaging the issue and will update the issue as we collect more information.
