### ISSUE TITLE
The #review-form fragment identifier is not added to the browser location after the review link is clicked, so it breaks the reverse navigation

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2845]
https://mage2.pro/t/351

**Comment by andimov** [comment]
Could you please add the description of steps, actual result and expected result to this ticket? It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
