### ISSUE TITLE
Shipping of invoiced Bundled Product  closes order 

### ISSUE THREAD

**Issue by j-robin-hunter** [magento/magento2#28468]
### Preconditions (*)

1. Magento CE 2.3.4

### Steps to reproduce (*)

1. Create bundle product
2. Successfully order and pay for product to put order in processing state
3. Ship order

### Expected result (*)

1. Shipped and paid for bundled order should become a COMPLETE

### Actual result (*)

1. Shipped and paid for bundled order marked as CLOSED

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by j-robin-hunter** [comment]
This issue is also related to #25177 which results in closed zero value virtual products

**Comment by j-robin-hunter** [comment]
#25177 has an extract of the code from the Order class which is causing class State check() to close the order

**Comment by swathishs** [comment]
@j-robin-hunter: I have tested the issue in 2.4 develop instance the issue is not reproducible 
Please refer the attachments:
1.Created bundle product
![image](https://user-images.githubusercontent.com/58288685/83490713-250c4200-a4ce-11ea-85b6-fa2d90cf4ef8.png)
2. Order placed:
![image](https://user-images.githubusercontent.com/58288685/83490771-43723d80-a4ce-11ea-8e9b-306b475f4aa8.png)
3. Ship order and status changed to complete:
![image](https://user-images.githubusercontent.com/58288685/83490809-52f18680-a4ce-11ea-92ce-ff91b8e48cea.png)

**Comment by j-robin-hunter** [comment]
In Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save controller the shipment is 'registered' and all items are marked as shipped. This results in the check() function in Magento\Sales\Model\ResourceModel\Order\Handler\State checking the canShip() status while the order is still in the PROCESSING state.

Since all items are now marked as shipped the order cannot now be shipped and test results in the order status being marked as CLOSED

**Comment by swathishs** [comment]
@j-robin-hunter: I have tested the step what you have suggested in 2.4 develop instance 

Please find the attachments:
1. **Order placing:**
![image](https://user-images.githubusercontent.com/58288685/83494171-808cfe80-a4d3-11ea-8c66-02e1bdd13b91.png)

2. **Admin order grid( Status- pending):**
![image](https://user-images.githubusercontent.com/58288685/83494249-9d293680-a4d3-11ea-9172-8e4f6839f316.png)

3. **Invoice the order(Status- processing):**
![image](https://user-images.githubusercontent.com/58288685/83494300-b03c0680-a4d3-11ea-96db-1aabe8a0aad1.png)

4.**Shipped the order(Status- Completed):**
![image](https://user-images.githubusercontent.com/58288685/83494346-c2b64000-a4d3-11ea-81ac-25dc8f35fa1e.png)

5. **Frontend** :
![image](https://user-images.githubusercontent.com/58288685/83494386-d19cf280-a4d3-11ea-8c83-dd0c1a25bab1.png)

Note : I am testing it in 2.4 develop instances. May i know which version are you testing

**Comment by j-robin-hunter** [comment]
We are using 2.3.4

**Comment by swathishs** [comment]
Ok, then I will check in 2.3.5p1 instance and let you know the status of the ticket. These two instances Magento recommends to test.
I used the bank transfer payment method in 2.4 develop instances. In 2.3.5 p1 instance will use Paypal method and test it

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by j-robin-hunter** [comment]
I have just tried the process you did using cash on delivery - it still ends up in the CLOSED state

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28468-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28468-2-3-5-p1.instances.magento-community.engineering/admin_0c53](https://i-28468-2-3-5-p1.instances.magento-community.engineering/admin_0c53)
Login: `702c1710` Password: `ac85f716690d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
okay I will try with cash on delivery

**Comment by swathishs** [comment]
I have tried in 2.3.5 p1 instances and the issue is not reproducible. You can check in the above instance for your reference

**Payment method** - cash on delivery 

Please find the attachments:

1. **Order admin( Status pending ):**
![image](https://user-images.githubusercontent.com/58288685/83497927-d4e6ad00-a4d8-11ea-8cd8-c3fc5f966e86.png)

2. **Invoiced (Status -processing**):
![image](https://user-images.githubusercontent.com/58288685/83498016-f5af0280-a4d8-11ea-99f6-7d39b706a5c1.png)

3. **Ship(Status - completed):**
![image](https://user-images.githubusercontent.com/58288685/83498120-1d9e6600-a4d9-11ea-8461-a847bf0c004d.png)

Could you let me know whether you can reproduce the issue in the above instance

**Comment by j-robin-hunter** [comment]
I have tried with the test instance and get an even worse result. With the Braintree payment, using card 4111111111111111 as a test card I get the order to go to the PROCESSING state, which is what I would expect.

When I then try to ship the order I get a message saying that the shipment has been created but ...... the shipment page remains in place and the order stays in PROCESSING

![Screenshot 2020-06-02 at 10 09 47 - Display 2](https://user-images.githubusercontent.com/35486530/83502330-51699380-a4b9-11ea-8310-20209b7a8103.png)

**Comment by swathishs** [comment]
You have missed invoicing the order so only your were shown status as"Processing "after shipment. I have gone and checked the order and made the order to invoiced and the status now came correctly as "completed".
![image](https://user-images.githubusercontent.com/58288685/83504121-bf29b580-a4e1-11ea-99f0-5a2e587f547a.png)

Order workflow:
![image](https://user-images.githubusercontent.com/58288685/83504221-dff20b00-a4e1-11ea-97bc-12a47d9ec34d.png)

**Comment by swathishs** [comment]
Hi @j-robin-hunter, thank you for your report. According contributor's guide Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch and 2.3.5p1 instance.
If you'd like to update the issue, please reopen it.
