### ISSUE TITLE
missing validation for admin grid filters

### ISSUE THREAD

**Issue by niravkrish** [magento/magento2#28464]
### Preconditions (*)

1. Magento - 2.3.x
2. PHP - 7.2

### Steps to reproduce (*)

1. Login to Magento 2 admin 
2. Go to Admin > catalog> products

### Expected result (*)

1. Validation should be work perfectly even in the filter also.

### Actual result (*)

1. There is only one example mentioned in the screenshot but there is also from date to date validation is not working.

![screenshot-127 0 0 1-2020 06 01-21_32_09](https://user-images.githubusercontent.com/44108490/83428283-bb4d5300-a44f-11ea-84b5-c1e87e3c0469.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28464-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28464-2-4-develop.instances.magento-community.engineering/admin_82f6](https://i-28464-2-4-develop.instances.magento-community.engineering/admin_82f6)
Login: `ade72f86` Password: `d466080c0b45`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@niravkrish: If the customer has two to three websites and there is a possibility of setting characters as prefixes for increment ID to differentiate there order ID. There is no from & to fields for order id in the latest version. So I think this bug is invalid. If not could you give me more information on it

Note: Magento is giving the "Magento 2 Custom Order Number" extension.
Please refer to this link: https://bsscommerce.com/magento-2-custom-order-number-extension.html

**Comment by swathishs** [comment]
@niravkrish: Since the bug is not valid. Hence closing the ticket. If you'd like to update the issue, please reopen it.

**Comment by swathishs** [comment]
Since the step to reproduce steps was wrong. We have to check the issue in the product grid in admin to reproduce the bug. Hence reopening the issue.

**Comment by swathishs** [comment]
The issue is reproducible in 2.4 develop instances. I have updated the step to reproduce the steps.

Please find the attachment :

![image](https://user-images.githubusercontent.com/58288685/83505715-cbaf0d80-a4e3-11ea-9643-4339cac52e05.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34799` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by syed-ziffity** [comment]
@magento I am working on this

**Comment by niravkrish** [comment]
Also validation not working for date range from and to date. 

Form date to date validation working fine with block grid but it is not working in ui grid.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
