### ISSUE TITLE
Swagger custom_attributes type is string but not all attributes allow string

### ISSUE THREAD

**Issue by juhanihaapala** [magento/magento2#28463]
### Preconditions (*)

1. Tested with Magento 2.3.1 and 2.3.4, 2.4-develop
2. Swagger says the value for custom attribute is "string" 
![image](https://user-images.githubusercontent.com/60198413/94437371-565bfc80-01a6-11eb-8b68-160d281bdcd6.png)

![image](https://user-images.githubusercontent.com/60198413/94437119-fe24fa80-01a5-11eb-8939-a083c0bb6f51.png)

### Steps to reproduce (*)

1. Made 'PUT" call for endpoint /V1/products/{sku} and set in call body  custom_attributes where attribute_code: `category_ids` and value `"1,2,3"`
![image](https://user-images.githubusercontent.com/3079827/83525699-03bb4e00-a4ee-11ea-95e4-e731c3242411.png)

### Expected result (*)

1. Product is saved with category ids 1,2,3

### Actual result (*)

1. 400 Bad request with error message Error occurred during "custom_attributes" processing. Attribute "category_ids" has invalid value. Invalid type for value: "string". Expected Type: "int[]".

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-28463-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28463-2-4-develop.instances.magento-community.engineering/admin_ceed](https://i-28463-2-4-develop.instances.magento-community.engineering/admin_ceed)
Login: `f4edaf70` Password: `815f4af7596d`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @juhanihaapala,
I have verified this issue in the latest Magento 2.4 instance with the proper steps, actual result and expected result.
I am not able to reproduce this issue. Please refer attached the below video:

![Untitled_ Jun 2 2020 6_43 PM](https://user-images.githubusercontent.com/24711761/83524815-c2cd3480-a501-11ea-9d6e-5b033497bdc1.gif)

Please update me if I have anything is missing from my end.

Thanks.

**Comment by juhanihaapala** [comment]
Ok, it seems I was not clear on describing the issue. Issue comes when trying to add/update product through rest api where you have category_ids custom_attribute data as string for example payload like this:
![image](https://user-images.githubusercontent.com/3079827/83525699-03bb4e00-a4ee-11ea-95e4-e731c3242411.png)

And the issue is swagger says the value is string while with category_ids it doesn't allow string.

**Comment by ajijshekh123** [comment]
Sorry @juhanihaapala, I can't able to review this issue throw the API. This issue needed developer experience. I am QA Contributor so I am not able to reproduce this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38028` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
