### ISSUE TITLE
[2.3.5p2] Incorrect tax calculations when custom price is set in non-base currency

### ISSUE THREAD

**Issue by snez** [magento/magento2#28462]
### Preconditions (*)

1. Magento 2.3.5p2
-- Repro on 2.4-develop - NO
-- Repro on 240 - NO 
2. Create Tax Rule for retailer customers group for Michigan state with tax rate 8.25%
3. Create retailer customer with address in Michigan
4. Set Euro as allowed currency in Configuration

### Steps to reproduce (*)

1. Create an order from the Admin area
2. From the sidebar, switch to a currency that is not the base currency (example EUR, USD-to-EUR Rate = 0.7067)
3. Add a product to the cart (example product price $10 / €14.13)
4. Set a custom price for the product (example €10)
5. Select a billing / shipping address which has a tax rate (example Michigan, US, 8.25% tax)
6. Select free shipping so that it does not interfere with tax calculations

### Expected result (*)

1. A tax of 8.25% on a €10 product should be €0.83

### Actual result (*)

1. An incorrect tax is calculated at €1.17 which is based on the €14.13 product price

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by snez** [comment]
Temporarilly closing, more details needed

**Comment by snez** [comment]
Ticket updated

**Comment by Mohan2594** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594, here is your [Magento instance](https://i-28462-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28462-2-4-develop.instances.magento-community.engineering/admin_f051](https://i-28462-2-4-develop.instances.magento-community.engineering/admin_f051)
Login: `39862ba6` Password: `ec525ac48d06`
Instance will be terminated in up to 3 hours.

**Comment by Mohan2594** [comment]
@snez tax is not applying by default

**Comment by Mohan2594** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mohan2594, here is your [Magento instance](https://i-28462-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28462-2-3-5-p1.instances.magento-community.engineering/admin_c7d8](https://i-28462-2-3-5-p1.instances.magento-community.engineering/admin_c7d8)
Login: `15d27949` Password: `3d68ed7f0f47`
Instance will be terminated in up to 3 hours.

**Comment by Mohan2594** [comment]
@snez tax is not being applied by default in both 2.4 and 2.3.5

**Comment by snez** [comment]
@Mohan2594 as per bullet point 5, please use an address that has a tax rate set up. The Michigan, US tax of 8.25% is the one that is set up with the Magento sample data, so please make sure that either the sample data are installed on the instance, or that a tax rate has been manually configured for the billing address used.

**Comment by snez** [comment]
@magento

**Comment by snez** [comment]
@Mohan2594 are you still working at Magento? If so, can you re-assign to someone who cares to have a look at this?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36822` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @snez

Thank you for your report and collaboration!
 
Based on confirmation result this issue related to 2.3.x release and does not exist in 2.4.
2.3.x branch is not available in this public repository so we are not able to process PR and provide updates here.

An internal ticket was created and added to the backlog for prioritization and future processing `MC-36822`
