### ISSUE TITLE
Customer can order less than minimum quantity allowed in shopping cart

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#28461]
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Create Product
2. Under Advanced Inventory set Minimum Quantity Allowed in Shopping Cart to 12
3. Also Enable Quantity Increments
4. Set Quantity Increments to 12

### Expected result (*)
1. The minimum amount of the product allowed in the cart should be 12
2. You can only add a minimum of 12 to the cart
3. Should not be able to change the quantity to a number less than Minimum Quantity Allowed in Shopping Cart.

### Actual result (*)
1. You can only add a minimum of 12 to the cart but
2. If you proceed to the cart, you can change the quantity and no restriction is in place.
3. For instance, change quantity to 9 and you are still able to checkout
4. Should be some sort of restriction not allowing you to change the quantity below the Minimum Quantity Allowed in Shopping Cart. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28461-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28461-2-4-develop.instances.magento-community.engineering/admin_57af](https://i-28461-2-4-develop.instances.magento-community.engineering/admin_57af)
Login: `bc9194c2` Password: `a380c6bab471`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
The issue is not reproducible  in Magento 2.4-develop instance

Please find the attachment below for your reference:

1. Admin config:
![image](https://user-images.githubusercontent.com/58288685/83417518-d44e0800-a43f-11ea-919a-16f4826514bf.png)
2. Cartpage
![image](https://user-images.githubusercontent.com/58288685/83417544-dd3ed980-a43f-11ea-8fbd-83c026329c45.png)

**Comment by swathishs** [comment]
Hi @trucatchtraps, thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.
