### ISSUE TITLE
Backend doesn't work after changing Custom Admin URL

### ISSUE THREAD

**Issue by indigoflow** [magento/magento2#28475]
### Summary (*)

Hello guys!
Magento ver. 2.3.1
Custom Admin URL was the default (checkbox checked: 'Use system value') 
After adding 'Custom Admin URL': https://www.gigispa.com/admin/
the backend stops to work properly doesn't load CSS and JS yet
I'm trying to connect Putty via IP: 34.216.107.95:22 or via hostname www.gigispa.com:22
It gives 'Network error - Connection timed out'
Please help me to switch this setting back any possible way.
Regards,
Maxim

### Examples (*)

![Magento2](https://user-images.githubusercontent.com/61367057/83532330-c4ddc600-a4f6-11ea-96fc-2ea05fdd9f41.jpg)
![image](https://user-images.githubusercontent.com/61367057/83532398-dde67700-a4f6-11ea-9e57-9a2c2be3d9d5.png)

### Proposed solution

I think it is possible to change it back by using the command line but I can't connect to the server.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @indigoflow . Thank you for your report!

According to the Magento [documentation](https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html):

![Screenshot from 2020-12-30 12-46-08](https://user-images.githubusercontent.com/51679138/103346569-063e5000-4a9d-11eb-9267-bc7091f86fc1.png)

In case you have set an invalid Admin URL or an Admin Path and lost access to the backend, there is a way to fix this from the command line.

_Execute this command to revert to the default Admin URL_

`php bin/magento config:set admin/url/use_custom 0`

_Execute this command to revert to the default Admin Path (set in the app/etc/env.php as described in the Method 2)_

`php bin/magento config:set admin/url/use_custom_path 0`

Use one of the following methods to clear the Magento cache:

On the Admin sidebar, go to _System > Tools > Cache Management_. Then, click **Flush Magento Cache**.
On the server, execute the following:

` php bin/magento cache:flush`

If that doesn't solve the problem please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for technical questions, feature requests, etc. 

Thank you!
