### ISSUE TITLE
How to add css to head via observer

### ISSUE THREAD

**Issue by Vincenkt** [magento/magento2#2847]
In magento 1, I have used addCss function to add css file to head. However, I don't see this fucntion in magento 2. Can you help me?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by alankent** [comment]
Hi @Vincenkt - http://magento.stackexchange.com/questions/86527/how-do-add-css-js-in-customview-phtml-in-view-magento2 might help. Have a read up on the `<css>` element I layout files, but also consider if you want a new CSS file or merge into existing files via Less includes.

**Comment by Vincenkt** [comment]
Hi @alankent Thanks for your help. The addPageAsset method has solved my problem. https://mage2.pro/t/topic/140
