### ISSUE TITLE
Incorrect Currency Symbol has been used for Base Currency in grand-total.html when Display Currency and Base Currency is different

### ISSUE THREAD

**Issue by monocircus** [magento/magento2#28474]
### Preconditions (*)

1.Magento Open Source 2.3.4 
2.In my case, set Base Currency : JPY  and make store view with Default Display Currency : USD

### Steps to reproduce (*)

1. add a product and go to checkout page
2.

### Expected result (*)

1. Base Currency price value will be displayed below Grand Total price
2. I can find the code in /app/code/Magento/Tax/view/frontend/web/template/checkout/summary/grand-total.html

```
<!-- ko if: isBaseGrandTotalDisplayNeeded() && isDisplayed() -->
<tr class="totals charge">
    <th class="mark" data-bind="i18n: basicCurrencyMessage" scope="row"></th>
    <td class="amount">
        <span class="price" data-bind="text: getBaseValue(), attr: {'data-th': basicCurrencyMessage}"></span>
    </td>
</tr>
<!-- /ko -->
```

### Actual result (*)

1. Base Currency price value is correct however It is shown with USD Currency Symbol.
It should be JPY Currency Symbol in my case.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by monocircus** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @monocircus. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @monocircus, here is your [Magento instance](https://i-28474-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28474-2-4-develop.instances.magento-community.engineering/admin_c42d](https://i-28474-2-4-develop.instances.magento-community.engineering/admin_c42d)
Login: `fa931a1a` Password: `2999f4b272dc`
Instance will be terminated in up to 3 hours.

**Comment by monocircus** [comment]
Hi I could not reproduce the issue.
but I remember I have been using currency formatter module to remove the decimal of JPY price.
this module might be causing the issue.

In 2.4-develop instance, the Decimal of JPY was removed without module.

Can someone tell me where I could find decimal setting in code?

If 2.3.4 version already have this function, I could disable the module.

thank you
