### ISSUE TITLE
Static Files Not loading when changing the Language (Both admin panel and front end view)

### ISSUE THREAD

**Issue by Greko2017** [magento/magento2#28478]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Greko2017** [comment]
Summary of the issue:
Some static file are not loading after changing the language in the Magneto 2 back end

Information on your environment:
PHP Version 7.2.31,
Apache 2.0 Handler,
10.0 build 18362 (Windows 10) 64bit
XAMP Server, 
,
Steps to reproduce:
Whe you change the admin and front end language it seems to change some files location adding /fr_FR/ in it (in my case I changed to french) 

Expected and actual results:
I expected to have my site translated to french both the front and Back end.

The solution that I foud was to add fr_FR and de and of the static-deploye script on bin\magento

`php bin/magento setup:static-content:deploy -f fr_FR

D:\xampp\htdocs\magento2>php bin/magento setup:static-content:deploy -f fr_FR

Deploy using quick strategy
adminhtml/Magento/backend/fr_FR         2263/2263           ============================ 100%   8 secs
frontend/Magento/blank/fr_FR            2248/2248           ============================ 100%   8 secs
frontend/Magento/luma/fr_FR             2265/2265           ============================ 100%   6 secs`

**That solved my problem later**

**Comment by engcom-Delta** [comment]
Hi @Greko2017 thank you for your report, I'm not able to reproduce issue by [steps](https://github.com/magento/magento2/issues/28478#issuecomment-638106116) you described on clean 2.4-develop
**Manual testing scenario:**
- Install german language pack
- Magento mode is developer
- Open admin panel
- Navigate to `Stores > Configuration > General > Locale Options`
- Choose German(Germany) and click on Save Config
- Flush cache
- Go to storefront

**Result:**
:heavy_check_mark: German locale is applied for storefront
![image](https://user-images.githubusercontent.com/51681379/100083440-294c6300-2e52-11eb-99b9-7edeed356200.png)

If you'd like to update the issue, please reopen it.
