### ISSUE TITLE
Showing extra spacing in top navigation sub menu 2.3.5 issue

### ISSUE THREAD

**Issue by renard123** [magento/magento2#28484]
Showing extra spacing in top navigation sub menu 2.3.5 issue

### Preconditions (*)
Magento 2.3.5

### Steps to reproduce (*)
1. Review the top navigation menu sub menu

### Expected result (*)
![image](https://user-images.githubusercontent.com/50658701/83621097-db922480-a5ab-11ea-8a48-61afb72e9d46.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/83620869-8fdf7b00-a5ab-11ea-9eca-54f8ec9ab597.png)

**Comment by krishprakash** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28484-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28484-2-3-5-p1.instances.magento-community.engineering/admin_f834](https://i-28484-2-3-5-p1.instances.magento-community.engineering/admin_f834)
Login: `3557c38c` Password: `b4a4f0e714c5`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28484-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28484-2-4-develop.instances.magento-community.engineering/admin_5f74](https://i-28484-2-4-develop.instances.magento-community.engineering/admin_5f74)
Login: `d6d00da6` Password: `4315c35a2070`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34826` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
**Note:**
Issue is only reproduce only on 2.3.5-p1 instance but not in 2.4-develop instance

**Comment by sdzhepa** [comment]
Hello @renard123 and @krishprakash 

I just checked this issue on the lates **2.3.5-p2** code - this version will be released and public available soon.

This issue is not reproduced and seems was fixed.
Please confirm it after release **2.3.5-p2** or reopen this issue

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34826).
