### ISSUE TITLE
GraphQl. updateCustomer allows to set any INT value in gender argument

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#28481]
### Preconditions (*)

1. Magento with a sample data

### Steps to reproduce (*)

1. Generate a customer token

```
mutation {
  generateCustomerToken(
    email: "roni_cost@example.com",
    password: "roni_cost3@example.com"
  ) {
    token
  }
}
```

2. Set a `gender` value for a customer

```
mutation {
  updateCustomer(
    input: {
      gender: 13
    }
  ) {
    customer {
      firstname
      gender
    }
  }
}
```

### Expected result (*)

1. Customer `gender` attribute may have one of the following values:

- Male (1)
- Female (2)
- Not specified (3)

### Actual result (*)

```
{
  "data": {
    "updateCustomer": {
      "customer": {
        "firstname": "Veronica",
        "gender": 13
      }
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by atwixfirster** [comment]
Working on this issue.

**Comment by atwixfirster** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34837` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment]
Confirming.
Request response:
```text
{
  "data": {
    "updateCustomer": {
      "customer": {
        "gender": 18
      }
    }
  }
}
```
