### ISSUE TITLE
Feature request: a '--no-progress' switch for certain cli commands would be nice

### ISSUE THREAD

**Issue by hostep** [magento/magento2#2848]
Hi guys

I'm setting up a deployment process using capistrano to publish a new version to a production server.
But when running for example the `setup:static-content:deploy` script, we get a lot of lines in our output, like this snippet:

```
...
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com]
 ** [out :: example.com] Successful: 1843 files; errors: 0
 ** [out :: example.com] ---
 ** [out :: example.com]
 ** [out :: example.com] === Minify templates ===
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
 ** [out :: example.com] .
...
```

An option to get rid of the progress would be handy to keep the output a bit more clean. I do like the information messages, so only the '.' output should be removed by that switch.
I know there is a `--quiet` switch, but this won't output anything at all.

So something similar as [composer](https://getcomposer.org/doc/03-cli.md#install) uses:
`--no-progress: Removes the progress display that can mess with some terminals or scripts which don't handle backspace characters.`

Possible command candidates:
- setup:di:compile
- setup:di:compile-multi-tenant
- setup:static-content:deploy
- ...

I'm most likely forgetting some

Thanks!

**Comment by piotrekkaminski** [comment]
Closing as duplicate in favor of #3692 that has more active discussion.
