### ISSUE TITLE
Incorrect invoice date Magento 2.3.4

### ISSUE THREAD

**Issue by ghost** [magento/magento2#28490]
### Preconditions (*)

1. Magento 2.3.4
2.

### Steps to reproduce (*)

1. Go to Sales
2. Go to invoices
3. View any invoice
4. Click on Print
5. Open invoice. You can see an invoice date like "Order Date: 9 nov. 2022"

### Expected result (*)

1. [Screenshots, logs or description]
2. I expect the normal date of order

### Actual result (*)

1. "Order Date: 9 nov. 2022"
2. 

---
I tested some other posts, but none of them works.
I have Magento 2.3.4 and installed a Dutch language pack.
After order the customer gets an incorrect invoice/order date. Way in the future. Today they get  "Order Date: 9 nov. 2022" 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sambath1293** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sambath1293, here is your [Magento instance](https://i-28490-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28490-2-4-develop.instances.magento-community.engineering/admin_4c29](https://i-28490-2-4-develop.instances.magento-community.engineering/admin_4c29)
Login: `b040aa5c` Password: `06a7e2e82a30`
Instance will be terminated in up to 3 hours.

**Comment by sambath1293** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sambath1293, here is your [Magento instance](https://i-28490-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-28490-2-3-4.instances.magento-community.engineering/admin_e04c](https://i-28490-2-3-4.instances.magento-community.engineering/admin_e04c)
Login: `c393cd12` Password: `732cf97d7168`
Instance will be terminated in up to 3 hours.

**Comment by JustICTNL** [comment]
On the Magento instance of sambath1293 there is no issue with the order date.

**Comment by sambath1293** [comment]
@JustICTNL- I was tried to recreate in both Magento-2.4 develop instance and Magento-2.3.4 instance I was seeing the order placed the date on the both invoice
See the below reference:
Magento 2.4 Develop instance
![2 4instace](https://user-images.githubusercontent.com/60879885/83645567-43f2fd00-a5d0-11ea-9965-d72660187fe7.png)
Magento 2.3.4 instance
![2 3 4instance](https://user-images.githubusercontent.com/60879885/83645677-5ec57180-a5d0-11ea-874a-a7802d793a9e.png)

so closing this issue, if you want to reopen this issue you can go-ahead with reference video or screenshots.

**Comment by JustICTNL** [comment]
Is there not any other solution to fix this?

**Comment by JustICTNL** [comment]
There should be a fix on this topic:
https://github.com/magento/magento2/issues/26675
