### ISSUE TITLE
To add default filter to grid?

### ISSUE THREAD

**Issue by ReginaLisa** [magento/magento2#2849]
I have created one custom module with title & status field attribute in admin grid.

Grid collections in **module_test_grid_block.xml**

```
         <arguments>
             <argument name="id" xsi:type="string">testGrid</argument>
              <argument name="dataSource" xsi:type="object">Namespace\Module\Model\ResourceModel\test\Collection</argument>
              <argument name="default_sort" xsi:type="string">id</argument>
              <argument name="default_dir" xsi:type="string">desc</argument>                             
              <argument name="grid_url" xsi:type="url" path="*/*/grid"><param name="_current">1</param></argument>
        </arguments>
```

I just want to show the datas which are enabled.Have any option to **add default filter in admin grid collections**?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
