### ISSUE TITLE
Checkbox and Radio renderer, strict check

### ISSUE THREAD

**Issue by michsk** [magento/magento2#2850]
Is there any reason we have strict checks for single values and not strict for array values?

```
module-backend/Block/Widget/Grid/Column/Renderer/Radio.php::render()
line 78
        if (is_array($values)) {
            $checked = in_array($value, $values) ? ' checked="checked"' : '';
        } else {
            $checked = $value === $this->getColumn()->getValue() ? ' checked="checked"' : '';
        }
```

The same is used for the Checkbox renderer. Maybe just keep it strinct and use `in_array($value, $values, true)` to be consistent?

**Comment by andimov** [comment]
@Michal-sk 
Sorry for the late reply. 
 If the problem still actual, please, provide the used version and description according to the template. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used. It's allow us research this issue.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
