### ISSUE TITLE
Issue with removing gift card code

### ISSUE THREAD

**Issue by giangvdm15** [magento/magento2#28507]
### Preconditions (*)

1. Magento EE 2.3.5-p1

### Steps to reproduce (*)

1. Create a gift card code, make sure to give it a generous balance (in my case it gave it $1000).
2. In storefront, proceed to checkout a cart with total value below the balance of the gift card code just created (in my case it's $106).
3. Apply the gift card code. Once succeeds, payment method is changed to "free" and cart total is 0.
4. Then proceed to remove the gift card code.

### Expected result (*)

1. The gift card code is removed from cart.
2. Customer should be able to take other actions (apply another gift card code, select a different payment method, confirm checkout,...).

### Actual result (*)

1. The gift card code is removed from cart.
2. Forever load, the console says ```TypeError: paymentMethod is null``` @ ```select-payment-method-mixin.js:26:25```, customer cannot take any further action on the page.
Screen record: https://www.loom.com/share/623ddd645851437aa35d566b235aca86

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28507-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28507-2-3-5-p1.instances.magento-community.engineering/admin_c60a](https://i-28507-2-3-5-p1.instances.magento-community.engineering/admin_c60a)
Login: `51cfcf69` Password: `f8c6e2938044`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
Since Magento CE does not have gift card option and the issue can be tested in EE

Hi @giangvdm15,2 all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue-specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue to https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Comment by giangvdm15** [comment]
Hi @swathishs , thank you for having a look at this issue.
Yes this issue is specifically for Magento EE (as I mentioned in the Precondition section). Do I have to take any action in order to transfer this issue to EE repo, or this will be done by the Magento support team?
Thanks.

**Comment by swathishs** [comment]
@giangvdm15 : This action will be taken by Magento support team

**Comment by giangvdm15** [comment]
@swathishs Okay got it, thank you very much.

**Comment by sdzhepa** [comment]
Hello @giangvdm15

Thank you for contribution and collaboration!

I moved this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
