### ISSUE TITLE
Product is oversold when multiple people purchase same product at the same time

### ISSUE THREAD

**Issue by secomm-dev** [magento/magento2#28508]
### Preconditions (*)

1. Magento 2.3.x
2. A product with QTY = 1, Saleable-QTY = 1
3. Any payment method, any shipping method
4. Any environment (standard LAMP following Magento recommendation)

### Steps to reproduce (*)

1. Multiple people add the product into cart. E.g. 10 people working on 10 different devices
2. Proceed to Checkout
3. Enter all required information: shipping address, shipping method, payment method
4. At the very same time (millisecond), all people hit Submit button  

### Expected result (*)

1. Only 1 Order should be created
2. QTY remains 1
3. Saleable-QTY becomes 0

### Actual result (*)

1. Multiple orders are created (it's a random number, but definitely more than 1)
2. QTY remains 1
3. Saleable-QTY becomes a negative number which equal to the number of orders that should have not been created (but have been)

### Additional Information
- If we remove MSI related modules, the issue is gone. Orders are created and stocks are reduced correctly. Therefore, I think this issue is related to MSI workflows and algorithm.
- We have experienced this issue on both live and development environments. 
- On live environment, this issue is likely to happen when there is high traffic with some products are on promotion in limited period, which attract customers to purchase same product(s) at the same time.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by sambath1293** [comment]
Hi @secomm-dev The issue specific for MSI should be reported in the MSI repo

fyi: @sidolov @smoskaluk @sdzhepa

It seems this issue MSI specific and should be fixed in MSI repository.

EngCom team, please confirm and transfer this issue to the https://github.com/magento/inventory/issues

Closing this issue

**Comment by secomm-dev** [comment]
Hi @sambath1293 thank you.

I have moved the issue to Inventory repository.
