### ISSUE TITLE
Failed to load the components errors on checkout/cart page after upgrading magento

### ISSUE THREAD

**Issue by muzamalhafiz422** [magento/magento2#28509]
After upgrading Magento 2.2.3 to 2.3.5, I faced the list of these errors on my checkout cart page. Order summary details are also missing. I disable all the custom modules and extensions. Can any help me with this problem?
### Preconditions (*)

1. I am currently using Ubuntu 18.04
2. php7.3
3. MYSQL Workbench
4. Magento 2.3.5

### Steps to reproduce (*)

1. add any product to cart and go to the cart page,
2. the order summary is missing
3. 

### Expected result (*)

the order summary should visible
1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]
![error](https://user-images.githubusercontent.com/38692334/83746970-54ab7d80-a679-11ea-8836-23e5efe2af18.png)

**Comment by muzamalhafiz422** [comment]
I also get an error when I upgraded the Magento on the checkout page and that was "_report.CRITICAL: Unable to serialize value_". I fixed it in this way.
**In vendor/magento/framework/Serialize/Serializer/JsonHexTag.php**
```
public function serialize($data): string
{
    $data = $this->utf8convert($data); ////////// Added this line
    $result = json_encode($data, JSON_HEX_TAG);
    if (false === $result) {
        throw new \InvalidArgumentException('Unable to serialize value.');
    }
    return $result;
}
//////////// Added this function
public function utf8convert($mixed, $key = null)
{
    if (is_array($mixed)) {
        foreach ($mixed as $key => $value) {
            $mixed[$key] = $this->utf8convert($value, $key);
        }
    } elseif (is_string($mixed)) {
        $fixed = mb_convert_encoding($mixed, "UTF-8", "UTF-8");
        return $fixed;
    }
    return $mixed;
}
```
ann In **vendor/magento/framework/Serialize/Serializer/Json.php**
```
public function serialize($data)
{
    $result = json_encode($this→utf8ize($data)); /// Add this line of code
    if (false === $result) {
        throw new \InvalidArgumentException("Unable to serialize value. Error: " . 			json_last_error_msg());
    }
    return $result;
}
// Add this function
public function utf8ize($mixed)
{
    if (is_array($mixed))
    {
        foreach ($mixed as $key => $value)
        {
            $mixed[$key] = $this->utf8ize($value);
        }
    }
    elseif (is_string($mixed)) {
        return mb_convert_encoding($mixed, "UTF-8", "UTF-8");
    }
    return $mixed;
}
```
after changing this, this error has fixed.

**Comment by muzamalhafiz422** [comment]
I think there was an issue with json_encoding. When I debug the program, I found that there is a method called `$block->getSerializedCheckoutConfig()` in vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml which returned false and due to this an error occurred which is _**window.checkoutConfig = ; syntax error**_  and the components unable to load. So when I replaced the line `return json_encode($this->jsLayout, JSON_HEX_TAG);` in _vendor/magento/module-checkout/Block/Cart/Shipping.php_ with `return  $this->serializer->serialize($this->getCheckoutConfig());` this syntax error removed and js components loaded and order summary data shows. Please tell me if this change is correct or not?

**Comment by matteobaro** [comment]
> I also get an error when I upgraded the Magento on the checkout page and that was "_report.CRITICAL: Unable to serialize value_". I fixed it in this way.
> **In vendor/magento/framework/Serialize/Serializer/JsonHexTag.php**
> 
> ```
> public function serialize($data): string
> {
>     $data = $this->utf8convert($data); ////////// Added this line
>     $result = json_encode($data, JSON_HEX_TAG);
>     if (false === $result) {
>         throw new \InvalidArgumentException('Unable to serialize value.');
>     }
>     return $result;
> }
> //////////// Added this function
> public function utf8convert($mixed, $key = null)
> {
>     if (is_array($mixed)) {
>         foreach ($mixed as $key => $value) {
>             $mixed[$key] = $this->utf8convert($value, $key);
>         }
>     } elseif (is_string($mixed)) {
>         $fixed = mb_convert_encoding($mixed, "UTF-8", "UTF-8");
>         return $fixed;
>     }
>     return $mixed;
> }
> ```
> 
> ann In **vendor/magento/framework/Serialize/Serializer/Json.php**
> 
> ```
> public function serialize($data)
> {
>     $result = json_encode($this→utf8ize($data)); /// Add this line of code
>     if (false === $result) {
>         throw new \InvalidArgumentException("Unable to serialize value. Error: " . 			json_last_error_msg());
>     }
>     return $result;
> }
> // Add this function
> public function utf8ize($mixed)
> {
>     if (is_array($mixed))
>     {
>         foreach ($mixed as $key => $value)
>         {
>             $mixed[$key] = $this->utf8ize($value);
>         }
>     }
>     elseif (is_string($mixed)) {
>         return mb_convert_encoding($mixed, "UTF-8", "UTF-8");
>     }
>     return $mixed;
> }
> ```
> 
> after changing this, this error has fixed.
> Maybe it also occurred due to this?

Hello @muzamalhafiz422 ,
it's working
you have saved my life
thank you so much

**Comment by miteshdhaduk** [comment]
> I also get an error when I upgraded the Magento on the checkout page and that was "_report.CRITICAL: Unable to serialize value_". I fixed it in this way.
> **In vendor/magento/framework/Serialize/Serializer/JsonHexTag.php**
> 
> ```
> public function serialize($data): string
> {
>     $data = $this->utf8convert($data); ////////// Added this line
>     $result = json_encode($data, JSON_HEX_TAG);
>     if (false === $result) {
>         throw new \InvalidArgumentException('Unable to serialize value.');
>     }
>     return $result;
> }
> //////////// Added this function
> public function utf8convert($mixed, $key = null)
> {
>     if (is_array($mixed)) {
>         foreach ($mixed as $key => $value) {
>             $mixed[$key] = $this->utf8convert($value, $key);
>         }
>     } elseif (is_string($mixed)) {
>         $fixed = mb_convert_encoding($mixed, "UTF-8", "UTF-8");
>         return $fixed;
>     }
>     return $mixed;
> }
> ```
> 
> ann In **vendor/magento/framework/Serialize/Serializer/Json.php**
> 
> ```
> public function serialize($data)
> {
>     $result = json_encode($this→utf8ize($data)); /// Add this line of code
>     if (false === $result) {
>         throw new \InvalidArgumentException("Unable to serialize value. Error: " . 			json_last_error_msg());
>     }
>     return $result;
> }
> // Add this function
> public function utf8ize($mixed)
> {
>     if (is_array($mixed))
>     {
>         foreach ($mixed as $key => $value)
>         {
>             $mixed[$key] = $this->utf8ize($value);
>         }
>     }
>     elseif (is_string($mixed)) {
>         return mb_convert_encoding($mixed, "UTF-8", "UTF-8");
>     }
>     return $mixed;
> }
> ```
> 
> after changing this, this error has fixed.
> Maybe it also occurred due to this?

A perfect solution for now...!!!

**Comment by moElwan** [comment]
For me the solution was to set the values `recaptcha_frontend/type_recaptcha/public_key`, `recaptcha_frontend/type_recaptcha/private_key` to null in db and flushing the caches including redis
