### ISSUE TITLE
Sample data bug: cms styles.css is installed twice

### ISSUE THREAD

**Issue by hostep** [magento/magento2#2853]
Hi guys

I just noticed after installing Magento 2 including the sample data, the file pub/media/styles.css has 2 times exact the same content.
It is the contents from the file: Magento_CmsSampleData::fixtures/styles.css

I think the error comes from the installer in the theme-sample-data, it installs the styles.css file from the cms-sample-data, instead of its own, see:
https://github.com/magento/magento2-sample-data/blob/6ca3ecfc0b1c7625ee04822060d9fd0e081354d9/app/code/Magento/ThemeSampleData/Setup/Installer.php#L52

**Comment by le0n4eg** [comment]
Thanks for reporting this issue! Internal ticket MAGETWO-47676
