### ISSUE TITLE
Configurable product - can not save product when required attribute is an option

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#2854]
Magento v2.0.0
The "flavor_type" is an required attribute and it is an option for customers in configurable product. I can not save any product when required attribute is an option.
![magento2-configurable product](https://cloud.githubusercontent.com/assets/13892193/12066528/1ab183da-afb7-11e5-92b5-145a612673cc.JPG)
![magento2-configurable product2](https://cloud.githubusercontent.com/assets/13892193/12066560/b7e5e376-afb7-11e5-85ba-46c10e2bd1a1.JPG)

**Comment by katmoon** [comment]
Hi,
Thanks for reporting the issue. 

Internal ticket is MAGETWO-47601

**Comment by EyeWeb** [comment]
I've experienced this same issue.

**Comment by jason-vivid** [comment]
I'm having a similar issue.  Using the workaround from this (https://github.com/magento/magento2/issues/2567) In order to create a configurable product.  

I cannot select:

![image](https://cloud.githubusercontent.com/assets/10146532/12152391/64f90876-b482-11e5-81fd-f79b508fe931.png)

And cannot save:

![image](https://cloud.githubusercontent.com/assets/10146532/12152413/8977e672-b482-11e5-9df7-91030581b61d.png)

**Comment by vzabaznov** [comment]
Hi @dexteritycc, thank you for reporting, issue was closed and delivered, if you feel that issue was not fixed, please write here or open new one.

**Comment by PascalBrouwers** [comment]
Stil have this issue in 2.0.4

**Comment by sammarcus** [comment]
@PascalBrouwers are you still experiencing this on 2.0.5?

**Comment by PascalBrouwers** [comment]
I'll update to 2.0.5 and see if this problem still exists.

**Comment by PascalBrouwers** [comment]
Just updated to 2.0.5. I still have the issue.
Note that I migrated my data from Magento 1.x to 2.0.2 and updated to 2.0.5

![image](https://cloud.githubusercontent.com/assets/17834386/15322399/e1bbbfa8-1c3c-11e6-8b50-2d7d359edf4f.png)

**Comment by ozgeekmum** [comment]
Still an issue on 2.0.6. 
Typical.

**Comment by sammarcus** [comment]
Is this still an issue in 2.1?

**Comment by veloraven** [comment]
Internal ticket for ver. 2.0 - MAGETWO-63211
Issue has been fixed for ver. 2.1

**Comment by korostii** [comment]
Hi @veloraven,
Can you please point out the exact 2.1.x version in which this fix was released? Or at least please reference the particular corresponding commits.

**Comment by magento-engcom-team** [comment]
@dexterityzx, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@dexterityzx, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
