### ISSUE TITLE
Category not being updated in Product Edit page Admin

### ISSUE THREAD

**Issue by nayanserver** [magento/magento2#28557]
I have migrated Magento 1.9.3.7 to 2.3.5-p1 after migration everything seems fine but when I have edit product selected category not displayed and category field blank. Even after setting new category or new product not able to save it. It displays the success message but actually category not saved. I can see the product in correct category in frontend and even in category page in backend but not in the product edit page.

### Preconditions (*)

1. Magento CE 2.3.5-p1
2. PHP 7.2

### Steps to reproduce (*)

1. Edit any Product
2. Select Category
3. Saved Product message displayed but category field blank

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![category-issue](https://user-images.githubusercontent.com/7785811/83880831-6bc39b80-a75d-11ea-989c-1c5813878d75.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28557-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28557-2-3-5-p1.instances.magento-community.engineering/admin_7405](https://i-28557-2-3-5-p1.instances.magento-community.engineering/admin_7405)
Login: `d1b9811c` Password: `3699cbd14d87`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@nayanserver: Issue is not reproducible in Magento  2.3.5-p1 instance

Please find the attachment below:

1. Admin:
![mE0dSTln5r](https://user-images.githubusercontent.com/58288685/83883623-5e101500-a761-11ea-9548-e835f417476b.gif)

2. Frontend:
![image](https://user-images.githubusercontent.com/58288685/83883468-21dcb480-a761-11ea-9932-6289fd1be886.png)

**Comment by nayanserver** [comment]
@swathishs Its working in new installation but not working after migration from 1.9.3.7

**Comment by swathishs** [comment]
@nayanserver: Since this issue occurs when migrated from Magento 1.9.3.7 to 2.3.5-p1. Hence I think someone else can take this ticket to replicate as your steps and test.

**Comment by krishprakash** [comment]
Hi @nayanserver. Thank you for your report.
Data migration from magento 1 should be reported to its separate repository
https://github.com/magento/data-migration-tool/issues
Kindly report the issue their
