### ISSUE TITLE
B2B Purchase order details

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28555]
As a Magento Developer,

I want to expose B2B purchase order details via GraphQL

So that customers can use a more flexible and performant API technology.

**Related issues**
https://github.com/magento/partners-magento2b2b/issues/331 
https://github.com/magento/partners-magento2b2b/issues/332
https://github.com/magento/partners-magento2b2b/issues/333

**Related branch**
https://github.com/magento/partners-magento2b2b/compare/28555_purchase_order_details

**Example of the query done so far**
https://github.com/magento/partners-magento2b2b/blob/0ac04c4c567ad364558039aeccbd2f35a83577f3/dev/tests/api-functional/testsuite/Magento/GraphQl/PurchaseOrder/Customer/PurchaseOrderTest.php

**Acceptance Criteria**

- GraphQL exposes only storefront B2B purchase order details 
- GraphQL respects user permissions for all storefront operations.
- WebAPI test coverage
- All builds are green

**Schema PR**
https://github.com/magento/architecture/pull/418

**Comment by munkhulzii** [comment]
Related PR: https://github.com/magento/partners-magento2b2b/pull/444

**Comment by sivaschenko** [comment]
GraphQL API coverage for Purchase Order was merged to the mainline and should be available in v2.4.6.
