### ISSUE TITLE
Related Products not working with Marketing Rules

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28566]
Queries for Related Products like the one below only return values if the Related Products are added from the Product Settings. However, it is not accounting for Marketing Rules and it returning empty arrays. (Marketing / Related Products Rules) – This is how Related Products are set with Luma stock sample-data.

```java
query ProductQuery {
  product: products(filter: \{ url_key: { eq: "chaz-kangeroo-hoodie" } }, pageSize: 1) {
    items {
      id
      related_products {
         id
         name
         url_key
      }
    }
  }
}
```

Response:
```java
{
  "data": {
    "product": {
      "items": <
        {
          "id": 70,
          "related_products": []
        }
      >
    }
  }
}
```
Luma Theme:

!image-2020-06-02-16-10-01-234.png|width=1336,height=761!

**Comment by fnhipster** [comment]
I want to add that this applies to Marketing Rules applied for **Related Products,** **Upsell Products**, **Cross-sell Products**, and the new **Recommended Products**. Marketing Rules are a Commerce-Only feature.

**Comment by munkhulzii** [comment]
With this ticket it will be implemented GraphQl for Related, UpSell and CrossSell Products from Marketing Rule.

**Comment by slackerzz** [comment]
Is this issue fixed? I've found the same problem with Magento Commerce 2.4.3-p1
