### ISSUE TITLE
Integration Authentication must be disabled in GraphQL

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28562]
OauthUserContext authentication is used for Integrations (which is equivalent to admin users) and must not be enabled in GraphQL.
 
![image-2019-10-09-15-36-10-566](https://user-images.githubusercontent.com/4700273/83883377-01810b80-a709-11ea-8ea9-cf301ea1954c.png)

**Comment by michalderlatka** [comment]
Looks like it was already done in 4dcf4366112eda56257dcb7a736986aee17d5693 in 2.4-develop branch
