### ISSUE TITLE
GraphQL Schema for createCustomer does not match validation requirements

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28570]
The schema for the createCustomer mutation shows the input object as a whole as required but it does not show the individual required fields. For example, I tried to make an account passing ONLY the email and password but received an error after submission that said first name and last name were required.

https://i.gyazo.com/baffd808d33594f6aa1f9ef785cac540.png

After checking the schema, it does not look like any of the props within the input object are listed as required. Fixing the schema will help catch errors ahead of time and during development of features.

https://i.gyazo.com/47babb76479f71ee87e5e46051c9b42e.png

**Comment by michalderlatka** [comment]
@magento I am working on this

**Comment by michalderlatka** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#28888 by @michalderlatka in 2.4-develop branch
Related commit(s):
 - [1943018094edcedddc73463a5e703a9a76653ad8](https://github.com/magento/magento2/commit/1943018094edcedddc73463a5e703a9a76653ad8)
 - [887f19109e9ecac0c15af7f2ddbbbf9ec7d360b3](https://github.com/magento/magento2/commit/887f19109e9ecac0c15af7f2ddbbbf9ec7d360b3)
 - [b5208cd5800bcdf14644c65847ecb4781e05ef8a](https://github.com/magento/magento2/commit/b5208cd5800bcdf14644c65847ecb4781e05ef8a)
 - [0f7d805b24f35a8c9650b1fa61e6048d14fd7a27](https://github.com/magento/magento2/commit/0f7d805b24f35a8c9650b1fa61e6048d14fd7a27)
 - [592f5de3a50cd80fe26a1c40534de9b92516a927](https://github.com/magento/magento2/commit/592f5de3a50cd80fe26a1c40534de9b92516a927)
 - [3a4cfa1fd0a05e040875ff51afe1d74a124fe211](https://github.com/magento/magento2/commit/3a4cfa1fd0a05e040875ff51afe1d74a124fe211)
 - [2e77e2292e15588086ba4358798be2185a68c44c](https://github.com/magento/magento2/commit/2e77e2292e15588086ba4358798be2185a68c44c)

The fix will be available with the upcoming 2.4.1 release.
