### ISSUE TITLE
GraphQL returns original image URLs for resized ones

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28576]
Preconditions:
1. A simple product (with name "Test") with an image is created
1. The image is marked as "small"

 

Steps:
1. Execute GraphQL query
```java
{
  products (search: "Test") {
    items {
      id,
      name,
      image {
        url
      },
      small_image {
        url
      },
      swatch_image,
      media_gallery {
        url,
      }
    }
  }
} ```

1. Expected: "image" and "small_image" URLs are different and point to images with expected image sizes (check current theme's view.xml for the sizes).
1. Actual: "image" and "small_image" URLs are the same.

**Comment by munkhulzii** [comment]
@magento I am working on this

**Comment by nrkapoor** [comment]
@danielrenaud As per our discussion yesterday this doesn't look like an issue.

**Comment by OleksiyOleksiyovych** [comment]
@nrkapoor @danielrenaud Could you, please, explain why it's not an issue?
How can I get different images for 'image', 'small_image', and for 'thumbnail'?

**Comment by danielrenaud** [comment]
@OleksiyOleksiyovych Different images are returned, i.e. the image you define as the thumbnail, or small_image, or main image is returned correctly. But GraphQl does not return the resized image because that is part of the theme, not GraphQl layer

**Comment by OleksiyOleksiyovych** [comment]
@danielrenaud  thank you for explaining. I agree, this is logical, but not what you expect when you do GraphQl query.
Do I must load big images and crop it on the frontend to the small if I need thumbnails? So the frontend theme on React or Vue must handle it, is it correct?

**Comment by zkriahac** [comment]
I think this didnt managed yet, strange @OleksiyOleksiyovych right should be managed
