### ISSUE TITLE
DependencyTest does not analyze GraphQL schema files

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28579]
Steps to reproduce:
* Add new GraphQl module which will extend existing schema
* Add dependencies to the module.xml
* Only schema refers to dependencies

(/) Test is green
(-) Test fails with `Redundant dependencies found!`

**Comment by cpartica** [comment]
Soft dependencies:
- a module that contain a *.graphqls file shouldn't be dependent on Graphql module
- a *.graphqls file that extends (redeclares) an existing type declared in another module SHOULDN't be dependent on the Graphql module that declared the same type

Hard dependencies:
- a *.graphqls file that implements an existing interface declared in another module SHOULD be dependent on the Graphql module that declared the same type
