### ISSUE TITLE
GraphQL- preview for a disabled product returns empty response

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28575]
Steps to reproduce:
1. Create a product that is in stock, assigned to a category, and set the status to disable 
2. Create an update for the product that enables it
3. Run the below query with  authorization token and preview-version header
```
{
   products
   (filter:{sku:{eq:"disabled-simple"}})
    {
      items{
        sku
        name
        stock_status
        price_range{
          maximum_price{
            final_price{value}
            regular_price{value}
        }
        minimum_price{
          final_price{value}
          regular_price{value}
        }
      }
    }
  }
}
```

#####Expected Result:
Product data is returned 

#####Actual Result:
Product data is empty

**Comment by alfredsgenkins** [comment]
I believe this is related to `Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CollectionProcessor\StockProcessor` class.

For some reason it seems to return wrong value, despite adding only following lines to SQL QUERY:

```mysql
... INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 ... AND (stock_status_index.stock_status=1)
```

I did reindex after disabling product, which did not help. Maybe my observations are wrong :)

**Comment by alfredsgenkins** [comment]
Maybe disabled products do not appear in `cataloginventory_stock_status`? I can only see `1` in `stock_status` column.

**Comment by danielrenaud** [comment]
Caused by core functionality that can not be fixed at this time
