### ISSUE TITLE
Adding separate query for products by id in GraphQL different from search

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28578]
In order to load a Template, one must make a query to the *urlResolver* to obtain the **id*, *uid* and *type** of the content.

*i.e.*

```
urlResolver(url: "/breathe-easy-tank") {
  id
  uid
  type
}
{code}


{code}
{
  "data": {
    "urlResolver": {
      "id": 1
      "uid": "fhdjksfhdsf8dsf89sdf"
      "type": "PRODUCT"
    }
  }
}
{code}

Then using that information, one could load a template using the type. In this case, PRODUCT where and run a second GraphQL Query requesting the product id. However, ***id*** doesn't seem to be in the filter criteria. 

{code}
  productsByID(uids: < "uid1", "uid2"], id: [1,2,3> ) {
    items {
      id
      name
    }
  }
```
Note: This is the flow for loading the other two types: CMS_PAGE and CATEGORY.

AC:
New query must be added this scenario is not going to use Search API.
Query must support tagging a caching
Multiple IDs can be passed to the filter to obey some scenarios in which we need to display multiple products like:  product compare, or multiple specific products, etc

Check the attached PR as a solution and add additional changes

**Comment by nrkapoor** [comment]
@serhiyzhovnir @rogyar @paliarush This is another issue for this PR https://github.com/magento/magento2/pull/28316

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by cpartica** [comment]
instead of adding a specific query for product by Id we want to do this: https://github.com/magento/architecture/pull/477

**Comment by engcom-Hotel** [comment]
@magento-engcom-team & @cpartica As we have PR to address this issue, can we close this issue.

**Comment by engcom-Hotel** [comment]
Dear @magento-engcom-team & @cpartica,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
