### ISSUE TITLE
GraphQL module has undeclared dependency on Webapi module

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28577]
GraphQL module relies on Webapi module for authentication and if Webapi module is disabled - some GraphQL queries will become inaccessible.

Ideally, dependency should be fixed or at least declared as 'required' instead of 'suggest'.

Severity is not critical because it is unlikely that someone will disable Webapi module, but in the future it should be possible to set up GraphQL-only instance.

 !image-2019-10-09-15-41-21-970.png!

**Comment by sasha19957099** [comment]
@magento I am working on this

**Comment by sasha19957099** [comment]
@magento I am working on this
