### ISSUE TITLE
Category query does not handle fragments

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28584]
Category query does not return correct response when using fragments

Steps to reproduce:
- Create some categories
- Run Query:
```
{
  categoryList(filters: {ids: {eq: "10"}}) {
    ... on CategoryTree {
      id
      name
      url_path
    }
  }
}
```

Actual Response: 
```
{
  "data": {
    "categoryList": [
      {
        "id": 10,
        "name": null,
        "url_path": null
      }
    ]
  }
}
```

Expected response (should match response without using fragment)
```
{
  "data": {
    "categoryList": [
      {
        "id": 10,
        "name": "Sweaters",
        "url_path": "venia-tops/venia-sweaters"
      }
    ]
  }
}
```

**Comment by munkhulzii** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @munkhulzii. Thank you for your request. I'm working on Magento 2.4-develop instance for you
