### ISSUE TITLE
Cache not being flushed saving Admin settings with multiple stores

### ISSUE THREAD

**Issue by js-pellsoftware** [magento/magento2#28589]
### Preconditions (*)
1. Magento CE 2.3.3 is installed
2. There is one website setup
3. Multiple stores are created

### Steps to reproduce (*)
1. Login to admin
2. Click Stores > Configuration
3. Pick any ship method and toggle the 'Enabled for Checkout', e.g. If set to 'Yes' set to 'No'
4. Click 'Save Config'
5. The 'Enabled for Checkout' setting won't update and will go back to whatever it was before you changed it, e.g. 'Yes' after you set it to 'No'
6. To get the setting to update, enter admin 'Cache Management' and clicking 'Flush Cache Storage' or running magento/bin cache:flush in CLI will set the 'Enabled for Checkout' field to 'No'

### Expected result (*)
Changing a setting in admin and clicking 'Save Config' should flush the cache and display the correct config value

### Actual result (*)
Changing a setting and clicking 'Save Config' doesn't appear to be flushing the cache and displaying the correct setting value

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28589-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28589-2-3-5-p1.instances.magento-community.engineering/admin_c9d0](https://i-28589-2-3-5-p1.instances.magento-community.engineering/admin_c9d0)
Login: `9d34f4f0` Password: `1d961b89cde3`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@jstrzz: Issue is not reproducible in Magento 2.4 develop instance 
Please find the attachment below:
1. **Store view:**
![image](https://user-images.githubusercontent.com/58288685/83994482-33e27100-a974-11ea-9713-bffe8559a1fa.png)

2. Before setting "Enabled to checkout"- "No":
![image](https://user-images.githubusercontent.com/58288685/83994559-6a1ff080-a974-11ea-92a5-fd93e9ac3f0a.png)

3. After Setting "Enabled to checkout" - "Yes":
![image](https://user-images.githubusercontent.com/58288685/83994611-92a7ea80-a974-11ea-9330-abb701e03ef6.png)

**Comment by swathishs** [comment]
@jstrzz: Issue is not reproducible in Magento 2.3.5-p1 instance
Please find the attachment below:

1. **Store view:**
![image](https://user-images.githubusercontent.com/58288685/83994851-3db8a400-a975-11ea-8fa9-78fbecda05f7.png)

2. **Before setting "Enabled to checkout"- "YES":**
![image](https://user-images.githubusercontent.com/58288685/83994877-532dce00-a975-11ea-847c-46e9fbad803d.png)

3. **After Setting "Enabled to checkout" - "NO"**:
![image](https://user-images.githubusercontent.com/58288685/83994896-68a2f800-a975-11ea-9bf4-8b57ca93b90c.png)

**Comment by jstrzz** [comment]
Your examples are 2.4, and 2.3.5 but I'm working with Magento CE 2.3.3

**Comment by swathishs** [comment]
Hi @jstrzz , According contributor's guide Magento is focusing development efforts on v2.4.

**Comment by swathishs** [comment]
Hi @jstrzz , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch and 2.3.5 p1.

If you'd like to update the issue, please reopen it
