### ISSUE TITLE
Issue in Image Attribute Type , error while in edit 

### ISSUE THREAD

**Issue by imbhupendra41** [magento/magento2#2858]
I am trying to create product attribute of image type. I have already created one custom attribute group and image type attribute. Image attribute saving the image in the proper the folder but while we edit the product the URL of the product show the different path so that why it is displaying Nothing. Code working with category. 

![01-01-2016 11-31-32](https://cloud.githubusercontent.com/assets/5947187/12069968/c7c5aa22-b07c-11e5-9ae7-93df4759dad1.png)

**Comment by mslabko** [comment]
Hello @imbrj,
Could you please provide the hash of commit where you got this issue?

**Comment by vzabaznov** [comment]
@imbrj  thanks for reporting, our functionality has been changed and bug cannot be reproduced
Fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved

**Comment by imbhupendra41** [comment]
Hello @vzabaznov 
Please find the issue and solution for the same in below URL
http://magento.stackexchange.com/questions/95619/create-product-image-attribute-in-magento2

**Comment by vzabaznov** [comment]
Hi @imbrj , thank you for reporting
Our product page had a lot of changes last months, could you please provide the hash of commit where you got this issue, and try to reproduce this problem on latest magento version.
