### ISSUE TITLE
[GraphQL] False positive behavior of testQueryCustomAttributeField 

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28580]
## Steps to reproduce
* debug test \Magento\GraphQl\Catalog\ProductViewTest::testQueryCustomAttributeField 
* set breakpoint into fixture Catalog/*files/product_simple_with_custom*attribute.php on line with the following code $product->setCustomAttribute($attribute->getAttributeCode(), 'customAttributeValue');
* \Magento\Framework\Model\AbstractExtensibleModel::setCustomAttribute in this method 
```
if (in_array($attributeCode, $customAttributesCodes)) {
{code}
this condition returns false and custom attribute is not set into product, as result product doesn't contain given custom attribute and further saved without it.
* test \Magento\GraphQl\Catalog\ProductViewTest::testQueryCustomAttributeField passed because GraphQL returns result even if attribute*code*custom is null.
{code}
...
attribute*code*custom: null
...
```
this test doesn't have any data check of product attribute (at least need to check value that was set), it has validation of structure of response and amount of nodes.

(/) Expected

* product must be saved with custom attribute
* add assert that value of set attribute is equal to result from requests (attribute*code*custom)

(x) Current 
* custom attribute is not set for a product
* response returns nullable result for product attribute, but test passes. Test should fail, because attribute was not set into product

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).

**Comment by pmarjan** [comment]
The above mentioned AbstractExtensibleModel will ignore all attributes that are not relevant to the product. One reason for that to happen is that the attribute has not been assigned to the attribute set that the product is assigned to.

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-23769).
