### ISSUE TITLE
GraphQL: GiftRegistry Docs

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28586]
Atwix PR review and delivery

Arch schema: 

<https://github.com/magento/architecture/pull/448] 

[https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/customer/gift-registry.graphqls] 

[https://github.com/magento/architecture/pull/383]

[https://github.com/magento/partners-magento2ee/pull/280>

**Comment by eduard13** [comment]
Hi @prabhuram93, looks like registrants was not included as input when creating a new gift registry. Any reasons of doing so?
If we check the frontend, we might see that the `registrant` can be used on creating.
![Xnip2020-10-06_09-21-13](https://user-images.githubusercontent.com/15868188/95201078-14573a00-07e8-11eb-8f73-da685e8df3f6.jpg)
Current schema: https://github.com/magento/architecture/pull/383/files#diff-3299aa604e57ca73029c832d00c1d5d0R81-R90

**Comment by nrkapoor** [comment]
> Hi @prabhuram93, looks like registrants was not included as input when creating a new gift registry. Any reasons of doing so?
> If we check the frontend, we might see that the `registrant` can be used on creating.
> ![Xnip2020-10-06_09-21-13](https://user-images.githubusercontent.com/15868188/95201078-14573a00-07e8-11eb-8f73-da685e8df3f6.jpg)
> Current schema: https://github.com/magento/architecture/pull/383/files#diff-3299aa604e57ca73029c832d00c1d5d0R81-R90

@eduard13 here is the final schema https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/customer/gift-registry.graphqls

**Comment by eduard13** [comment]
Thanks @nrkapoor for the final schema, will review it. As per my understanding, we'll be adding the registrants within a separate mutation `addGiftRegistryRegistrants` 😕.

**Comment by prabhuram93** [comment]
@eduard13 I see your point. I think we should have the ability to add registrant while creating a registry. I will work on updating the schema. Please reach out to me if you already have some suggestions. Thanks!

**Comment by prabhuram93** [comment]
@eduard13 created a proposal for the above here https://github.com/magento/architecture/pull/448, this should work. We can discuss concerns, if any, there. Thanks!
