### ISSUE TITLE
MyAccount :: Order Details :: Deprecate customerOrder query

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28582]
Deprecate customerOrder query

**Comment by ralbin** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ralbin. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ralbin** [comment]
@magento I am working on this

**Comment by ralbin** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @ralbin, here is your [Magento instance](https://i-28582-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28582-2-4-develop.instances.magento-community.engineering/admin_a2f0](https://i-28582-2-4-develop.instances.magento-community.engineering/admin_a2f0)
Login: `9d299fc6` Password: `07e856709cb5`
Instance will be terminated in up to 3 hours.

**Comment by ralbin** [comment]
@nrkapoor I found If I deprecate this, the CustomerOrders will have issues. I decided to unassign this for now until I find a better way or maybe another dev can complete it before I get back to it.

**Comment by nrkapoor** [comment]
@ralbin We are working on customer orders that will be a part of the customer object. here is the schema.  https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/customer-orders.md

**Comment by nrkapoor** [comment]
@ralbin If you have already done the work please submit a PR and we will review.
