### ISSUE TITLE
Search Terms causing memory exhausted

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#28591]
### Preconditions (*)

1. Magento 2.3
2. ElasticSearch 6

### Steps to reproduce (*)

1. To have 20k different searches per day
2. Access **Marketing > SEO & Search > Search Terms**

### Expected result (*)

1. See the searched terms.

### Actual result (*)

1. The session in break and we're redirected to the login page every time that we try to access the Search Terms.

## Stack trace

```
…lled at /app/mdhksik627pps/vendor/magento/framework/Session/
SessionManager.php (150)
in Magento\Framework\Session\SessionManager::writeClose called at ? (?)
```
## MySQL Query

<img width="773" alt="Screen Shot 2020-06-05 at 3 09 43 PM" src="https://user-images.githubusercontent.com/610598/83916538-5a6d9580-a743-11ea-83d7-e2da4248f7ea.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sivaschenko** [comment]
See the proposed solution: https://github.com/magento/magento2/issues/28592

**Comment by engcom-Hotel** [comment]
Hello @rafaelstz 
I have generated about 100k records and haven't able to reproduce the issue.
PHP 7.3
Elasticsearch 6.8.13
Magento ver. 2.3.3
Could you please provide more details?
Thank you.

**Comment by engcom-Hotel** [comment]
![search_terms_elastic_6 8_m2 3 4](https://user-images.githubusercontent.com/51681618/98679365-94813a00-2368-11eb-8e78-0dcb99196875.png)

**Comment by engcom-Hotel** [comment]
Hello @rafaelstz ,
Closing the issue due to inactivity. Feel free to reopen it if you can provide any additional information to reproduce the issue.
