### ISSUE TITLE
Magento give ERR_EMPTY_RESPONSE error when making customer segments

### ISSUE THREAD

**Issue by aliejaz55** [magento/magento2#28596]
### Preconditions (*)

1. Magento Version 2.3.0
2. Registered Customer count 8 million
3. Custom Attributes applied on customers

### Steps to reproduce (*)

1. Go to Customer Segments, Create New Segment.
2. Add Required Information for new segment.
3. Save the created segment.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/22393364/83953101-123f9780-a857-11ea-916e-99702e9db6e1.png)

2. While saving the segment, Keeps loading to save that segment and need to wait for around 20 mins may be more. And after that, application gives an error. All the values in php.ini are updated.

### Expected result (*)

1.  It should save the segment and load the all matched customer with condition.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28596-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28596-2-4-develop.instances.magento-community.engineering/admin_ae34](https://i-28596-2-4-develop.instances.magento-community.engineering/admin_ae34)
Login: `ab0e1392` Password: `1c605971c739`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
Since the customer segment option is not available in Magento CE. Hence the issue should be tested on Magento EE

Hi @aliejaz55 , all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue too-
 https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Comment by aliejaz55** [comment]
Yes this is issue is on magento commerce.

**Comment by sdzhepa** [comment]
Hello @aliejaz55 

Thank you for contribution and collaboration!

I moved this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
