### ISSUE TITLE
Error selecting payment method as discount rule

### ISSUE THREAD

**Issue by pedrohenrique1986** [magento/magento2#28593]
Magento 2.34p2
PHP 7.2

When we are going to add a cart promotion rule, there is no option to choose the payment method as a rule option.

Magento 234p2 with error
![magenteo-erro-1](https://user-images.githubusercontent.com/13370384/83924994-6d409400-a75c-11ea-981e-df288d3f0643.PNG)

In the Magento 233 version it works
![magenteo-erro-2](https://user-images.githubusercontent.com/13370384/83924991-6a45a380-a75c-11ea-9efc-fa794c762160.PNG)

**Comment by krishprakash** [comment]
Hi @pedroohsolucoes. 
Kindly provide all the details steps to reproduce,actual result,expected result to reproduce this issue 
Like what kind of rule you have created and how we can reproduce this issue
Thanks

**Comment by krishprakash** [comment]
Hi @pedroohsolucoes.
Feel free to reopen once you update all the details 
Thank you !!
