### ISSUE TITLE
Pagination arrows in Admin confugurable product edit, configurations tab

### ISSUE THREAD

**Issue by majidiyan** [magento/magento2#28598]
### Preconditions (*)

1. A configurable product with about 200 children
2. Per page dropdown on 20

### Steps to reproduce (*)

1. Using pagination by left and right arrows, try to navigate from first page to second page
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. I expect the second 20 children be shown

### Actual result (*)

1. [Screenshots, logs or description]
2. First 20 is shown correctly but the second 20 children crashed the browser. when children of product is few for example less that 100 the left and right arrows works fine, but when you have more than 120 children and "Per page dropdown" is on 20, the problem appears

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-28598-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28598-2-4-develop.instances.magento-community.engineering/admin_d360](https://i-28598-2-4-develop.instances.magento-community.engineering/admin_d360)
Login: `0426f5bb` Password: `f8ff56ea623c`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
Hi @majidiyan thank you for the report. I tried to reproduce your case and managed to navigate between more than 1000 children, so it looks like performance problem on your machine

**Comment by majidiyan** [comment]
I checked, It now works fine, please give me changed codes you commited. ))

**Comment by majidiyan** [comment]
> Hi @majidiyan thank you for the report. I tried to reproduce your case and managed to navigate between more than 1000 children, so it looks like performance problem on your machine

We installed new version 2.4.0, but this bug has still remained.
