### ISSUE TITLE
Magento Connect Menu is not appearing 

### ISSUE THREAD

**Issue by sachan-amit** [magento/magento2#2860]
I have installed magento 2.0 in digital ocean with prebuild magento image. When I try admin account to install some extensions, I am unable to see magento connect menu under system section

**Comment by mazhalai** [comment]
@pavanuec is it no longer Magento connect, it is Magento Marketplace. And it should be under `System->Web Setup`

**Comment by sachan-amit** [comment]
Thanks Mazalai, How would one install any extension using market place. Do we need to use integration?

**Comment by mazhalai** [comment]
@pavanuec it is still work in progress. For starters, you can install sample data via the marketplace. Go to `System->Web Setup->Component Manager`. Sign in using your magento.com account and set up authentication with public(username) and private(password). For now sample data components show up. Eventually, all extensions purchased via marketplace will be available. Use check boxes to select which components to install, and click install. Follow all the steps. _Note_, this works only if you deployed via `composer create-project ....` or downloaded the zip from magento.com.

**Comment by ghost** [comment]
Reported solution on one of our chats:

I search on google for Magento Connect 2 extensions
I found this
https://www.magentocommerce.com/magento-connect/magento-2
and I download one of this for a test
unzipped on app/code
and after I prompt on command line php bin/magento setup:upgrade
and after this in component manager I saw that plugin is installed

**Comment by sachan-amit** [comment]
Thanks Mazhalai & Steve, I get this now.

**Comment by mazhalai** [comment]
@pavanuec thank you for your response. Closing this issue.
