### ISSUE TITLE
[2.3.5-p2 only] Special price range settings (from/to dates) is not  work correctly for administrator accounts using a Korean locale.

### ISSUE THREAD

**Issue by rakhi98** [magento/magento2#28618]
### Preconditions (*)
- Repro on 2.3.5-p2 - YES
- Repro on `2.4-develop` - NO
- Repro on 2.4.0 - NO

### Steps to reproduce (*)

- System->Permission->All user->Open admin account ->update Interface Locale to->Korean(South Korea).
![image](https://user-images.githubusercontent.com/51681379/90517659-5b249e00-e16e-11ea-8b0c-43b0f308d528.png)

- Now come to new product form or edit product form and fill the Special Price From/To dates.
![image](https://user-images.githubusercontent.com/51681379/90517927-c1112580-e16e-11ea-8c0b-2559cde88107.png)

- On saving it throws an exception ->Invalid Input Datetime

### Expected result (*)
Product is saved without error

### Actual result (*)
Error message "Invalid input datetime format of value '2020. 8. 18.'"
![image](https://user-images.githubusercontent.com/51681379/90517840-9d4ddf80-e16e-11ea-9382-e609ae49836c.png)

:warning: **Notice:** Issue is not reproducible on 2.4-develop

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36829` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @rakhi98 

Thank you for your report and collaboration!
 
Based on confirmation result this issue related to 2.3.x release and does not exist in 2.4.
2.3.x branch is not available in this public repository so we are not able to process PR and provide updates here.

An internal ticket was created and added to the backlog for prioritization and future processing `MC-36829`
