### ISSUE TITLE
Product stock is accepting negative Number in Product Form

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#28613]
### Preconditions (*)

1.  Magneto 2.3.5-p1
2.  Apache2
3.  PHP 7.2
4.  Ubuntu 16.04

### Steps to reproduce (*)

1. Log in to Admin Dashboard 
2. Catalog -> Product -> Add New Product -> Add Product with Quantity -20

### Expected result (*)

1. It Should Give A Validation Error that Stock cannot be a Negative Number

### Actual result (*)

1. Product is Saving with Stock = -20

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ .] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @TheRealHunzik. This is native magento behavior not an issue.
Admin should set the negative number for out of stock threshold
https://docs.magento.com/user-guide/catalog/inventory-backorders.html#out-of-stock-threshold
https://github.com/magento/magento2/issues/9139
Kindly refer above links
Thanks !!
