### ISSUE TITLE
Email template type not working

### ISSUE THREAD

**Issue by subash-natarajan** [magento/magento2#28611]
### Preconditions (*)

1. Magento 2.3.3p1

### Steps to reproduce (*)

1. Create a custom email template using email_templates.xml
2. Set the template type as text in email_templates.xml.
`<template id="order_email_template"
              label="Order Email"
              file="orders_email_template.html"
              type="text"
              module="xxx_yyy"
              area="adminhtml"
    />`

### Expected result (*)

1. The content-type of the email sent should be in text/plain format.

### Actual result (*)

1. But the content-type of the email sent in text/html format.

**Comment by swathishs** [comment]
@subash-natarajan: Issue is not reproducible in Magento 2.4-develop instance

Please find the attachment below:
![image](https://user-images.githubusercontent.com/58288685/85249028-437fb080-b470-11ea-9490-3310fdb8f240.png)

Hence closing the issue
