### ISSUE TITLE
WEBAPI: Missing shipping address details in salesOrderRepositoryV1GetResponse

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#2861]
When I place an order with a different shipping address other than the billing, the shipping address details are not included in the response XML. Only a section with billingAddress.

**Comment by ericahoekerd** [comment]
tested again on 2.01 still no shipping address in the response

**Comment by rohitgupta4** [comment]
Is there a rough ETA on when this would be supported?

**Comment by choukalos** [comment]
Known issue - tracking as (MAGETWO-46720) internally, scheduled for 2.0.3 patch release.  Patch release is TBD.  Dup of #2628

**Comment by ericahoekerd** [comment]
when will the 2.0.3 released? We have a lot of customers waiting to start with Magento 2.0 but now we recommend them to wait until this is fixed. Otherwise all the orders cannot be shipped to the right address

**Comment by karanbhomiagit** [comment]
Hey guys, any ETA for 2.0.3 patch to be released?

**Comment by srinivasanithin** [comment]
Hey @choukalos,

I am getting same shipping address for all orders when I am using GET:/V1/Orders Rest API. is this issue also tracked with number. If Yes, Can you please let me know the ETA of this bug fix release?

**Comment by NadiyaS** [comment]
Hi @srinivasanithin,
issue about returning the same shipping address for different orders was fixed and delivered to develop branch.
See details in #4019.
This issue is closed as resolved. Feel free to open new issue if you find some problems with shipping address.
Thanks
