### ISSUE TITLE
Magento 2 admin Uncaught TypeError: this.linksFieldset(…).visible is not a function

### ISSUE THREAD

**Issue by sumeet-mis** [magento/magento2#28616]
### Preconditions (*)

1. Magento : 2.3.5
2. Fresh install of M2

### Steps to reproduce (*)

1.When we edit product from admin then its loader continue showing and also getting this error
`"Uncaught TypeError: this.linksFieldset(...).visible is not a function"`
is showing error in console. For others product opens without any error.

### Expected result (*)

1. Admin product edit page will open without continue loader and without console error.

### Actual result (*)

1. Admin Product page show console error
`"Uncaught TypeError: this.linksFieldset(...).visible is not a function"`
and continue loader is showing.
Please check screenshot - 
![admin_product_console](https://user-images.githubusercontent.com/66507940/84033252-32399d00-a9b6-11ea-8f64-f3c5defe1637.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sumeet-mis** [comment]
@krishprakash Did you checked ?
Is there any update regarding the same ?

**Comment by sumeet-mis** [comment]
for @all
When i change attribute set directly from database "default to our attribute set(changed attribute_set_id from 4 to 9(database - catalog_product_entity))" then page is open without console error

**Comment by krishprakash** [comment]
Hi @sumeet-mis. 
Feel free to reopen the issue once you confirm that issue is reproduce on 2.4-develop instance 
Thanks!!
