### ISSUE TITLE
WEBAPI: Missing method to download the websites and storeviews configuration

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#2862]
At the moment there is no method available to download the store and website setup from Magento into ERP. 

In mag 1.9 we had webservice storeList for this. Can you add this back in Magento 2?

**Comment by choukalos** [comment]
Checkout http://devdocs.magento.com/swagger/index.html ; in particular storeGroupRepository and storeConfigRepository.  Do those address your needs?

**Comment by choukalos** [comment]
Re-assigning to Mark Brinton.

**Comment by ericahoekerd** [comment]
yes this is exactly what we need! thanks for bringing this new methods in! Good Job!
