### ISSUE TITLE
Critical CSS path feature does not match stylesheets

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#28624]
### Preconditions (*)

1. Magento 2.3.5-p1
2. Enable critial CSS path feature dev/css/use_css_critical_path

### Steps to reproduce (*)

1. Enable critial CSS path feature dev/css/use_css_critical_path
2. Add critical.css to theme
3. Clear chaches, deploy, etc,
4. Open a random page of the shop

### Expected result (*)

1. Critical CSS is inlined
2. all <link rel="stylesheet" ..> tags are moved from head before body end tag and are changed to 'preload' to work asynchronously

### Actual result (*)

1. Critical CSS is successfully inlined
2. link tags are not moved

### Reason 

In `vendor/magento/module-theme/Controller/Result/AsyncCssPlugin.php` line 51 the regex expects the `link` tag to end with a slash. However this is not the case. In HTML5 the closing slash can be ommited, and this is indeed the case. 

This is a sample output:
`<link rel="stylesheet" type="text/css" media="all" href="https://.../de_DE/css/styles-m.min.css">`

However, it is allowed to use a closing slash, so it should work both ways. I suggest changing the regex to:

`@<link\b.*?rel=("|')stylesheet\1.*?>@`

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by mrtuvn** [comment]
duplicated issue The first raise already here 
https://github.com/magento/magento2/issues/26498

**Comment by HenKun** [comment]
It's a different issue, but the PR seems to fix  anyways.

**Comment by krishprakash** [comment]
Closing this issue as it fixed by Pull request #28480
