### ISSUE TITLE
Not possible to see reviews for configurable products

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#28620]
### Preconditions (*)

1. Magento Enterprise 2.3.5-p1
2. Luma default Theme, Fresh Shop with migrated data from M1 shop (migrated by using the official tool)

### Steps to reproduce (*)

1. Add a review to a configurable product
2. Approve the review.
3. Reload product site
4. Try to find the review

![image](https://user-images.githubusercontent.com/16349349/84053991-00730700-a9b3-11ea-8670-e2280fecc0c8.png)

5. Click on the "Reviews" link (red arrow in screenshot above)
6. Nothing happens

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-28620-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28620-2-4-develop.instances.magento-community.engineering/admin_1f8a](https://i-28620-2-4-develop.instances.magento-community.engineering/admin_1f8a)
Login: `65227837` Password: `739eed0e12f1`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@Eddcapone thank you for your report, I tried to reproduce according to your description, but I can see all reviews 
![Screenshot 2020-06-12 at 12 28 56](https://user-images.githubusercontent.com/24183408/84493695-783d7c00-aca8-11ea-96e5-bfc55d529b62.png)

**Comment by Eddcapone** [comment]
Thank you for testing, so I guess the error is resolved in 2.4
