### ISSUE TITLE
Unable to remove product from minicart 

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#28630]
### Preconditions (*)

1. Using Magento 2.3.5-p1
2.

### Steps to reproduce (*)

1. added product from category page 
2. remove the product  from mini cart popup 

### Expected result (*)

1. product removed from popup and update cart counter
2. 

### Actual result (*)

1. not removed product from mini cart
2.  Checked in developer tool URL checkout/sidebar/removeItem/ status 302

![image](https://user-images.githubusercontent.com/2478037/84117045-8b550f80-aa4e-11ea-8407-f9197a248c45.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hemendraajmera, here is your [Magento instance](https://i-28630-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28630-2-4-develop.instances.magento-community.engineering/admin_01e4](https://i-28630-2-4-develop.instances.magento-community.engineering/admin_01e4)
Login: `a77dd8dc` Password: `0e4585618d0d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@hemendraajmera : Issue is not reproducible in  Magento 2.4 develop instance.

 Please find the attachment below:
1. **Console:**
![image](https://user-images.githubusercontent.com/58288685/84121739-2a7d0580-aa55-11ea-9e11-a8ceb862cd07.png)

2. **Remove cart from the mini cart:**
![hBJbnjE0f8](https://user-images.githubusercontent.com/58288685/84121895-4f717880-aa55-11ea-9fdc-a4279ccef0c0.gif)

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by swathishs** [comment]
@hemendraajmera : The issue is not reproducible in Magento 2.4 develop instance.

Please find the attachment below:

1. Console:
![image](https://user-images.githubusercontent.com/58288685/84157771-beb49000-aa88-11ea-9dd9-bb385fb4c0e4.png)

2. Remove cart from the mini cart:
![jBQRx80Ytr](https://user-images.githubusercontent.com/58288685/84157955-ee639800-aa88-11ea-8975-be888ccef79e.gif)

**Comment by swathishs** [comment]
@hemendraajmera :  I have tested the issue with the step described above in both 2.4 develop instances and 2.3.5 p1 instance . The issue is not reproducible. Could you please let me know whether I should follow any other step to create the issue.

**Comment by swathishs** [comment]
Hi @hemendraajmera , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.
