### ISSUE TITLE
Invalid response line returned from server: HTTP/2 200 when i try to connect to the magento market place with my public and private key

### ISSUE THREAD

**Issue by Faruqsd** [magento/magento2#28637]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hello @saadfaruq 
Could you provide more details for reproduce this issue?
Please add steps to reproduce and version of magento.

Thank you!

**Comment by krishprakash** [comment]
Hi @saadfaruq. Feel free to reopen once you update all the details as per issue reporting guidelines.
Thanks!!
