### ISSUE TITLE
WEBAPI: index is not updated after API call, modus is set to 'On save'

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#2863]
Altough the index modus is set to 'on save' the indexes are not realtime updated after different Web API requests, for example these ones:  
- catalogProductRepositoryV1SaveRequest
- configurableProductLinkManagementV1AddChildRequest
- catalogAttributeSetManagementV1CreateRequest
  and all other API methods which are storing data in the database

**Comment by andimov** [comment]
@tinxit  thank you for reporting.
Please fill description according to the template and specify magento version.

**Comment by ericahoekerd** [comment]
default Magento deliverse, no custom template

**Comment by ericahoekerd** [comment]
version2.01

**Comment by andimov** [comment]
@tinxit, thank you for response!
Here you can see template for bugs https://github.com/magento/magento2/issues/new
Description must contains **Steps to reproduce**, **Expexted** and **Actual** result.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
