### ISSUE TITLE
catalog.csv typing error

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#2865]
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/i18n/en_US.csv
1. line
   "Something went wrong saving the URL rewite."

rewite?

**Comment by alankent** [comment]
Weally? You weally want to pick on a paw developah who can't ponounce there 'R's? What is the wowld coming to!
(Thanks for pointing it out! ;-)

**Comment by MomotenkoNatalia** [comment]
@ideirj Thanks for reporting this issue. Trifles make perfection, and perfection is no trifle ;) Currently translation files are inconsistent with the code. We have task to fix this problem. Internal ticket: MAGETWO-47595

**Comment by wert2all** [comment]
Fixed
