### ISSUE TITLE
Installation is incomplete.(win7 + php7.2 + nginx)

### ISSUE THREAD

**Issue by zhican** [magento/magento2#28655]
![image](https://user-images.githubusercontent.com/26996587/84215565-3e7a4300-aaf9-11ea-9aa8-374caae1641d.png)

**Comment by engcom-Delta** [comment]
Hi @zhican 
Could you provide more details for reproduce this issue?
Please add version of magento.

Thank you!

**Comment by krishprakash** [comment]
Hi @zhican. Feel free to reopen the issue once you update additional steps/details to reproduce the issue.
Thanks!!
