### ISSUE TITLE
Reflection Exception: Interceptor Class Does Not Exist during Installation

### ISSUE THREAD

**Issue by ashwinshenoi99** [magento/magento2#28673]
### Summary (*)

Reflection Exception: Interceptor Class Does Not Exist during Installation

### Examples (*)

CLI install using bin/magento setup:install
On checking the webpage, error is reported

`An error has happened during application run. See exception log for details.`

Exception.log shows:

```
main.CRITICAL: Class Magento\Framework\App\Http\Interceptor does not exist {"exception":"[object] (ReflectionException(code: -1): Class Magento\\Framework\\App\\Http\\Interceptor does not exist at /var/www/html/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:24)"} []
```

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kamzata** [comment]
Same error here, therefore Magento 2.4.0 cannot be executed.

My config:

- Debian 10
- Apache 2.4.38
- PHP 7.4.8
- MariaDB 10.4.13
- Composer 1.10.10

I tried also using PHP 7.3.20 but nothing's changed.

**Comment by kamzata** [comment]
I got this to be accurate:
`main.CRITICAL: Class Magento\Framework\App\Http\Interceptor does not exist {"exception":"[object] (ReflectionException(code: -1): Class Magento\\Framework\\App\\Http\\Interceptor does not exist at /var/www/magento/vendor/magento/framework/Code/Reader/ClassReader.php:26)"} []`

**Comment by gcampedelli** [comment]
I had the same error after installing showed me an error from missing composer.json file in var/composer_home folder. 
So I placed an auth.json file with my keys to magento repo, reinstalled it and issue was solved. Let me know if this help you.

**Comment by cljk** [comment]
Same here - fresh project based on `2.4.0`

Ubuntu 20.04 (in WSL2)
* composer 1.9.0
* PHP  7.4.3

`exception.log` after first time calling web interface
```
[2020-09-25 09:24:44] main.CRITICAL: Class Magento\Framework\App\Http\Interceptor does not exist {"exception":"[object] (ReflectionException(code: -1): Class Magento\\Framework\\App\\Http\\Interceptor does not exist at /home/cljk/workspaces/company/web/shop-ng/vendor/magento/framework/Code/Reader/ClassReader.php:26)"} []
```

**Comment by cljk** [comment]
follow up: I downgraded to PHP `7.3` and magento `2.3.5` and got the same error 🤔

Found out you can run

```
php bin/magento setup:di:compile
```
😶🙄

Seems to generate the files

**Comment by engcom-Delta** [comment]
Hi @ashwinshenoi99  Unfortunatelly, I'm not able to reproduce issue by steps you described with clean 2.4-develop. Installation is done successfully

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by luciandex** [comment]
If you run in Docker container, clear cache with `php bin/magento cache:clean` from bitnami\magento directory.
After that, `stop `and `start `again the container. 
That's what worked for me.
