### ISSUE TITLE
Import product Not Display in Front Side magento 2

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#2868]
i upload CSV  file import then product Add in  Database(Catalog)  But  Front Side Not Display  

How To solve....

**Comment by daim2k5** [comment]
@mitulispace Do you see the products in the backend? Reindex? Maybe you can provide a sample csv?

**Comment by christinenikaki** [comment]
Same thing happening to me. I see the products in the backend. I also tried exporting them and import again. The file exported had different encoding and more fields than my original one, but still no luck.
[catalog_product_20160106.zip](https://github.com/magento/magento2/files/79950/catalog_product_20160106.zip)

**Comment by davidalger** [comment]
Closing due to no reply from OP
