### ISSUE TITLE
Marketplace not work  in magento 

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#2869]
Marketplace Not working I chacked  All Setting  and public key and private key Not Work 
Click on  Sign in 

![component](https://cloud.githubusercontent.com/assets/16436069/12073637/5afc9c70-b14e-11e5-82fa-2e4dd3414732.png)

![ssl](https://cloud.githubusercontent.com/assets/16436069/12073636/4bb3683e-b14e-11e5-8ffa-7cb74f6288d3.png)

**Comment by ghost** [comment]
Instead of doing it that way, click the **System Config** option and enter your keys there. Let us know if it works.

**Comment by ishakhsuvarov** [comment]
@mitulispace Closing the ticket for now, please reopen if the issue persists.
