### ISSUE TITLE
What is the recommended approach to enable CORS to access Magento REST APIs for localhost development?

### ISSUE THREAD

**Issue by thesurenk** [magento/magento2#28690]
### Summary (*)

How to use Magento REST API's from a developer machine running web applications on their localhost when Magento server to be used is on their intranet or external.

With more emphasis on developing applications using REST APIs and headless, enabling dev teams accessing external Magento's APIs would be very helpful.

Often they come across CORS issues and had to go about fixing/allowing them on Apache/Nginx where Magento is running, instead of focusing on using the APIs.

I have not seen any official docs on CORS work around from Magento https://devdocs.magento.com/guides/v2.4/config-guide/bk-config-guide.html  

Would like to see something that works and official from Magento team for dev teams to use and extend.

### Examples (*)

1. Install and configure Magento on a server allowing it be available on an IP or domain (internal to org or public)
2. Develop any sample application that can consume REST API's and let it run on developer local machine (for example: http://localhost)
3. Try to access the above magento's REST API from within the application developed in (2).

An example in Angular:

```
export const environment = {
  production: false,
  apiBase: 'http://1.2.3.4/rest/V1', # magento installed and available here
  authorization: 'xxxx'
};
...
...
 public getAllProducts(): Observable<any> {
      const httpHeaders = new HttpHeaders ({
        'Content-Type':  'application/json',
        'Authorization': `Bearer ${environment.authorization}`,
      });

      console.log(httpHeaders);

    return this.http.get<any>(`${environment.apiBase}/products?searchCriteria[pageSize]=5`, {headers: httpHeaders});
  };
```

### Proposed solution

There are several suggestions and solutions suggested, some of them 
1. Add headers (like below) to .htaccess files (but there are several varied options):
```
<IfModule mod_headers.c>
   Header always set Access-Control-Allow-Origin "*"
   Header set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
   Header set Access-Control-Allow-Headers "Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization"
```
2. Use a 3rd party module like https://github.com/graycoreio/magento2-cors 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment]
Allow origin * effectively turns off cors as it allows everywhere which defeats the point of cors. Personally i prefer to manage cors in apache/nginx config and not in magento. If someone hacks and gains access to your admin, the last thing you want is them modifying cors hosts and opening up your shop. I keep my cors config in apache config and requires root to modify.

**Comment by ksurendra** [comment]
Yes @gwharton , allowing cors can only be done in Apache/Nginx. But was looking at a more recommended way. And yes "*" is not secure. Developers may forget that on stage/prod servers.

I was able to solve this on our dev server ( https://community.magento.com/t5/Magento-2-x-Hosting-Performance/Accessing-Magento-REST-APIs-from-localhost-Blocked-by-CORS/m-p/449304#M1581 ) but had to go through lots of asking-around and research.

**Comment by damienwebdev** [comment]
Resolved by https://github.com/graycoreio/magento2-cors
