### ISSUE TITLE
backend usability is slowed down when working with multiple tabs

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#28701]
### Preconditions (*)
1. Magento 2.3.4+
2. Firefox

### Steps to reproduce (*)
1. Open multiple tabs (x5 at least) using middle wheel click or ctrl + click 
2. Wait for the tabs to load

### Expected result (*)
1. All tabs load in the backround and I can work as soon as I switch to them

### Actual result (*)
1. It seems knockout ui components do not load entirely if the tab is out of focus. 
2. As soon as I switch to the tab the elements begin loading. 

This is kind of preventing the user from working fast. Sometimes I know I need to edit 5 products so I will middle click the 5 edit links so while I'm editing one product, the other 4 are ready to work on. 

Or sometimes I need to do some configuration and load the category and product listing too so I'll open all 3 tabs at the same time and when I save my config I want to switch to the other tabs.

Every single time the other tabs are not ready for work because they seem to lazy load. 

---
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @ioweb-gr thank you for your report.
Seems like this behavior is not Magento Core technical issue
Please feel free to open issue in [community-features](https://github.com/magento/community-features/issues) repo for further discussion

**Comment by ioweb-gr** [comment]
As a sidenote @engcom-Delta I'm just relaying the complaints from many customers here. All our Magento 2 customers that came from Magento 1 are wondering about this and why it's happening so I would very much appreciate if you could explain to us what you mean by this response so we can explain to them further. 

As I see it, it's a core usability issue.
