### ISSUE TITLE
Page builder wont safe content if the content was copied from another page builder element

### ISSUE THREAD

**Issue by JelleGroenendal** [magento/magento2#28706]
### Preconditions (*)
1. Magento 2 EE 2.3.5-p1

### Steps to reproduce (*)
1. Create CMS page
2. Create a text element with page builder
3. Create a header element with page builder
4. Copy content of header element in to text element
5. Safe

### Expected result (*)
1. Page builder content is saved

### Actual result (*)
1. Infinite loading on save
2. Content is not saved
3. Console log error:
[ERROR] Page Builder was rendering for 5 seconds without releasing locks.

First h2 in this image is a h2 created in a text element
Second h2 is a copy from a header element.
![image](https://user-images.githubusercontent.com/30628171/84496900-141db680-acae-11ea-9e86-9854b084969a.png)

Note:
If a page was already saved in a previous Magento version the page cannot be edited unless the fault is removed from the content. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28706-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28706-2-4-develop.instances.magento-community.engineering/admin_effc](https://i-28706-2-4-develop.instances.magento-community.engineering/admin_effc)
Login: `65aa4622` Password: `bb129ed21e4d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
Hi @JelleGroenendal, all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue too-
https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Comment by jasperzeinstra** [comment]
@JelleGroenendal I'm running in to the same issue. Can't find a issue report at https://github.com/magento/partners-magento2ee/issues. Did you already resolve this issue? It looks like it's stuck on this piece of code

`Magento_PageBuilder/js/form/form-mixin.js`
```
timeout = setTimeout(function() {
    consoleLogger.error('Page Builder was rendering for 5 seconds without releasing locks.');
}, 5000);
$('body').trigger('processStart');
$.when.apply(null, this.pageBuilderInstances.map(function(instance) {
    locks = instance.stage.renderingLocks;
    return locks[locks.length - 1];
})).then(function() {
    $('body').trigger('processStop');
    clearTimeout(timeout);
    submit();
});
```

**Comment by yesman2104** [comment]
Hello , I have problem same here . Description of Product can't update after I try add a new content for it with Page Builder . Pls Help me !!! I'm using Magento EE 2.3.5p2

**Comment by dino6213221** [comment]
Hello. I have the same issue while saving CMS page on M2.4.2-p1. Is there any temporary fix for this?

**Comment by Ealuad** [comment]
Issue can still be replicated on EE M2.3.4-p2.

**Comment by anjali25021995** [comment]
page builder was rendering for 5 seconds without releasing locks

We are getting the issue magento 2.4.7-p2, can you please anyone give me the solution
