### ISSUE TITLE
Region select field stays disabled after switching back from country without regions

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#28702]
### Preconditions (*)

1. 2.3.5-p1 (B2B)

### Steps to reproduce (*)

1. Go to "company/account/create" (should also work if you enter an address in the checkout)
2. Select country "Germany" => select box with regions is visible (Berlin etc.)
3. Select country "Georgia" => select box is hidden, country input field is shown
4. Select country "Germany" again

### Expected result (*)

1. I can select my region

### Actual result (*)

1. The region select field is disabled

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AnnaShepa** [comment]
Hi @sippsolutions thank you for your report. I tried to reproduce your case, but every time dropdown list properly has been changed to text field and back. It looks like cache issue, please check your installation and cache settings. Althernahtivity you can try to reproduce the issue on clean magento installation and may be add some details how to reproduce the issue.
