### ISSUE TITLE
Cart Price Rules based on Payment Method condition has wrong logic on cart page.

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#28700]
### Preconditions (*)

1.magento 2.3.5-p1

### Steps to reproduce (*)

1. Offline payment available, for instance, Bank transfer. 
2. Another available payment method, such as paypal.
3. Generate a cart rule
```
Conditions setting like this :
 If **ALL**  of these conditions are **TRUE** :
Payment Method  **is**  Bank Transfer Payment  
```
Actions setting like this :
![actions](https://user-images.githubusercontent.com/45879513/84476143-50f2a900-acc0-11ea-950e-271c469a2004.png)
4. Add items to cart then go to cart page.

### Expected result (*)

We shouldn't see any discount information on cart page as discounts are only available with the specified payment method. customers will be very confused because the discount won't be applied when checkout.

### Actual result (*)

1. Set bank transfer as default payment method, discount will be applied on cart page
![image](https://user-images.githubusercontent.com/45879513/84476845-50a6dd80-acc1-11ea-975f-0c617f4602dc.png)
But we've set minimal order amount at 600 USD in bank transfer payment method. So when we go to checkout, it will show like this : 
![image](https://user-images.githubusercontent.com/45879513/84477020-8f3c9800-acc1-11ea-933e-c76768a4f1d9.png)
then, we select paypal , the discount disapear. 
![image](https://user-images.githubusercontent.com/45879513/84477059-9e234a80-acc1-11ea-87a3-46348289f52a.png)

Then go to cart page again, stranger things happened. 
![image](https://user-images.githubusercontent.com/45879513/84477168-cdd25280-acc1-11ea-8034-4e73262acbc5.png)
discount disappear now.

Discount which depends on payment method should only be calculated on checkout/#payment page, not on cart page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-28700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28700-2-4-develop.instances.magento-community.engineering/admin_ff21](https://i-28700-2-4-develop.instances.magento-community.engineering/admin_ff21)
Login: `ca2d1dac` Password: `2a4f9371c1fb`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @Yuwei9291,
I have verified this issue as per steps to be reproduced, actual result and expected result.
I think you are right, Discount should be calculated on checkout as per select the payment not in the Cart page.

**Cart image (Default Bank Transfer) Payment Method:**
![cart](https://user-images.githubusercontent.com/24711761/85414849-41117980-b58a-11ea-8d39-b77daa00b2c9.png)

**Select the Bank Transfer Payment:**
![Checkout_BankTransfer](https://user-images.githubusercontent.com/24711761/85414886-4bcc0e80-b58a-11ea-9c5b-17c3b9be6950.png)

**Select the PayPal Payment:**
![Checkout_PayPal](https://user-images.githubusercontent.com/24711761/85414890-4cfd3b80-b58a-11ea-8b13-440d4e2cec15.png)

**Again Navigate the Cart page after select the PayPal Payment method:**
![cart_Again](https://user-images.githubusercontent.com/24711761/85414892-4d95d200-b58a-11ea-867e-ef314eb247b7.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35386` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Echo. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Echo, here is your [Magento instance](https://i-28700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28700-2-4-develop.instances.magento-community.engineering/admin_5fae](https://i-28700-2-4-develop.instances.magento-community.engineering/admin_5fae)
Login: `cc5a9e29` Password: `b56db6a71227`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Echo** [comment]
Hi,  @ajijshekh123 @Yuwei9291. Unfortunately, I'm can't reproduce this issue, please provide more detailed steps to reproduce an issue. 
I get the next result as per steps to be reproduced :
1) Generate a cart rule
2) Use offline payment available, for instance, Bank transfer or(and)
Another available payment method, such as paypal.

![Peek 2020-06-26 12-23](https://user-images.githubusercontent.com/51681435/85842282-261c5080-b7a8-11ea-8ef9-08e5433d977d.gif)

**Comment by ferdiusa** [comment]
I was able to reproduce the issue with enabled manual "Terms and Conditions". Setting these to "automatic" or disabled" applies the cart rule just fine!

**Comment by engcom-Delta** [comment]
@ferdiusa @Yuwei9291  Are you able to reproduce issue on the latest 2.4-develop?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
