### ISSUE TITLE
Unique Key on  eav_attribute_option_value expected. Not in Release 2.3.5-p1

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#28703]
### Preconditions (*)
#24718 
1. as in the comments this fix was released in 2.3.4 
https://github.com/magento/magento2/issues/24718#issuecomment-537933827
2. use magento 2.3.5-p1 composer installed

### Steps to reproduce (*)
1. have a look if the commits are there 

https://github.com/magento/magento2/commit/502146f7f2d086b3a1beaea41de3edc488f78b3c

### Expected result (*)
1. Commits are there and so is the unique key 

### Actual result (*)
1. it is not there

---
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by ihor-sviziev** [comment]
Fix was reverted in https://github.com/magento/magento2/commit/e1958fece28f2726d2d7cb6a48b1b25cb5b3862e. 
@lenaorobei @slavvka could you add more info why it was reverted?

**Comment by stkrelax** [comment]
Thx for finding that @ihor-sviziev and yes i am very courious about the why part...
@lenaorobei @slavvka  same question as @ihor-sviziev why ?
because i think it would be a necessary feature...

**Comment by lenaorobei** [comment]
@ihor-sviziev internal ticket says that it was reverted due to backward incompatible change that was not approved.

**Comment by stkrelax** [comment]
@ihor-sviziev  Okay Thanks

**Comment by ihor-sviziev** [comment]
Hi @stkrelax thank you for raising this issue!

I just re-opened original issue.
