### ISSUE TITLE
CSS/LESS Error when editing attribute

### ISSUE THREAD

**Issue by cod3gen** [magento/magento2#2871]
As can be seen in image below, settings is not in their correct place. Using M2 Development package downloaded/installed two weeks ago.

![screenshot_1](https://cloud.githubusercontent.com/assets/14929298/12076559/22744cf0-b1b1-11e5-8ab9-409a7bcb6c17.png)

**Comment by zanilee** [comment]
Hi, @cod3gen!

Can you please specify, what browser do you use?

**Comment by cod3gen** [comment]
Hi @zanilee 

Sorry for my late answer, have been busy these days.
Browser with issue is Opera 34.0 on Windows 10.
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2036.25

However, i removed browser cache, and now the issue is gone and dropdown works as it supposed to for some wierd resons.

Tested fine with Chrome
