### ISSUE TITLE
how to debug magento ..?

### ISSUE THREAD

**Issue by EngPeterMaged** [magento/magento2#28722]
please i need to debug magento ..?
how to debug modules and web pages ..?
what is the tools the i need to debug magento 2.3.3 ?

**Comment by krishprakash** [comment]
Hi @EngPeterMaged. 
GitHub issue tracker is intended for magento core technical issues only 
Kindly refer [magento community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this
Thanks !!
