### ISSUE TITLE
The fields with type='checkbox' are not saved in the backend «Stores» → «Configuration» section

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2872]
https://mage2.pro/t/333

**Comment by palamar** [comment]
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
