### ISSUE TITLE
Allow dynamic date variable in Theme > Footer > Copyright

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#28732]
### Description (*)
The ability to pass a year variable via the Theme Footer configuration

### Expected behavior (*)
1. Go to Content > Configuration > [ Select Theme ] > Click Edit > Footer > Copyright
2. Insert copy like 'Copyright {{date_Y}} Store Name, Inc.'
3. View the footer on the front end rendered as 'Copyright 2020 Store Name, Inc'

### Benefits
I would say most if not all stores require a copyright notification that needs to be updated annually, and there is built in php functionality to render the year via the `date()` method - can we simply marry the two and allow the date to be populated dynamically in the footer?

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-28732-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28732-2-4-develop.instances.magento-community.engineering/admin_0638](https://i-28732-2-4-develop.instances.magento-community.engineering/admin_0638)
Login: `e5ce57b2` Password: `4d9955047dd6`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @nbennett25 
for fast processing of this issue please create this  on Community feature repository.
Thanks
https://github.com/magento/community-features

**Comment by niraligajera** [comment]
I have created a new module for a dynamic year for copyright. might be it will help you for quick changes,

**https://github.com/niraligajera/copyright**
