### ISSUE TITLE
Web scraping

### ISSUE THREAD

**Issue by sportmma** [magento/magento2#28731]
If I have created a module that will send a lot of inquiries to the warehouse about stock levels, prices, etc. magento 2 will be too burdened? I mean Web scraping module. It will download photos, descriptions, stocks, prices. It is better for the application to work as a magento 2 module or as a separate website?

**Comment by swathishs** [comment]
@sportmma: Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion
