### ISSUE TITLE
Incorrect Item count on product listing

### ISSUE THREAD

**Issue by MarianMates** [magento/magento2#28741]
### Preconditions (*)

1. Magento 2.3.5
2. Elasticsearch 6.8.6
3. Stores -> Configuration -> Catalog -> Catalog Search -> Search Engine = Elasticsearch 6.0+

### Steps to reproduce (*)

1. Create a bundle product without assigned options
2. Assign the product to a category
3. On the frontend, go to that category

### Expected result (*)

The bundle product is not displayed because it does not have options, price or stock, which is correct. The product should not be counted in the toolbar's "# items" and the layered navigation.

### Actual result (*)

The product is counted in the toolbar and layered navigation, thus # items showing more than the actual number of available items.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by matthewhaworth** [comment]
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth, here is your [Magento instance](https://i-28741-2-3-5.instances.magento-community.engineering).
Admin access: [https://i-28741-2-3-5.instances.magento-community.engineering/admin_968d](https://i-28741-2-3-5.instances.magento-community.engineering/admin_968d)
Login: `8a27a083` Password: `52b5e40e3a23`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@matthewhaworth: Issue is not reproducible in Magento 2.3.5-p1 instance. 
Please find the attachment below:

1. **Bundle product :**
![image](https://user-images.githubusercontent.com/58288685/84770236-cded8d80-aff4-11ea-8aed-4ed4e53af182.png)

2. Frontend:
![image](https://user-images.githubusercontent.com/58288685/84770302-f1183d00-aff4-11ea-9b1c-6dc1306b37ee.png)

Could you please update me with more accurate step to recreate the issue. Can you add a screenshot?

**Comment by MarianMates** [comment]
One of the preconditions is using ElasticSearch as a search engine, I have updated the initial post for more clarity. 
Stores -> Configuration -> Catalog -> Catalog Search -> Search Engine is using MySQL by default and needs to be changed for this issue.

**Comment by swathishs** [comment]
@MarianMates : I have changed search engine -  Elasticsearch 7.0+ which was working in Magento 2.3.5p1 instance

Attachments:
![image](https://user-images.githubusercontent.com/58288685/84775726-2e80c880-affd-11ea-9794-c1b9ebbd4caf.png)
![image](https://user-images.githubusercontent.com/58288685/84775768-37719a00-affd-11ea-8cec-068f30af8b40.png)
![image](https://user-images.githubusercontent.com/58288685/84775785-3b9db780-affd-11ea-8eff-52bce8506343.png)

Can you check with this instance : 
Admin access: https://i-28742-2-3-5-p1.instances.magento-community.engineering/admin_e87c
Login: 9c10c339 Password: 1092453e9202

**Comment by MarianMates** [comment]
Yes, I have check it and the issue is not reproducing. Possibly an ElasticSearch 6+ problem, will investigate more and upgrade if necessary. Thank you.
