### ISSUE TITLE
Vertex_AddressValidation breaks checkout on IE11 due to the use of Object.entries

### ISSUE THREAD

**Issue by mattijv** [magento/magento2#28742]
### Preconditions (*)
1. M2.3.5-p1 (untested on other versions).
2. Vertex_AddressValidation enabled.
3. IE11 as the browser.

### Steps to reproduce (*)
1. Add an item into the cart.
2. Navigate to checkout.

### Expected result (*)
1. Checkout works without errors in the console.

### Actual result (*)
1. Error in the console "Object doesn't support property or method 'entries'".

### Notes
This is due to the usage of `Object.entries` in `vertex/module-address-validation/view/frontend/web/js/view/validation-message.js` which is not supported on IE11. As IE11 regrettably remains a supported browser, and the Vertex module is bundled with Magento, this probably should be fixed.

Severity S1 due to the problem affecting checkout.

---

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28742-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28742-2-3-5-p1.instances.magento-community.engineering/admin_e87c](https://i-28742-2-3-5-p1.instances.magento-community.engineering/admin_e87c)
Login: `9c10c339` Password: `1092453e9202`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance with vertex setting

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by brigitschroeder** [comment]
I had the same issue and was able to get around it using a polyfill.
app/code/Vendor/Module/view/frontend/web/js/ie11polyfill.js
`define([],function(){
    if (!Object.entries)
        Object.entries = function( obj ){
            var ownProps = Object.keys( obj ),
                i = ownProps.length,
                resArray = new Array(i); // preallocate the Array
            while (i--)
                resArray[i] = [ownProps[i], obj[ownProps[i]]];

            return resArray;
        };

    return Object.entries;
});
`
Then add it as a dependency for the validation js that's having issues.
in requirejs-config.js
`var config = {
    shim: {
        'Vertex_AddressValidation/js/view/validation-message': {
            deps: ['Vendor_Module/js/ie11polyfill']
        }
    }
};`
Hope this helps anyone who's having the same issue.

**Comment by mattijv** [comment]
@brigitschroeder Great workaround, thanks for posting! Luckily for me, I could just disable the Vertex modules and not worry about it.

**Comment by navarr** [comment]
An internal ticket, BUNDLE-2583 exists for this issue.  If needed, you can use the patch here: [BUNDLE-2583.patch](https://gist.githubusercontent.com/navarr/0bd8377996c65a1a7ad72b4d8962956a/raw/314e67ef8850b5b5b3aa4adacdb41d0d4ae088b7/BUNDLE-2583.patch)

**Comment by drabikowy** [comment]
@navarr regarding the patch you provided, will **let** actually work in ie11? 🤔  I think it should be **var** instead.
```
+            for (let key in object) {}
```

**Comment by krzksz** [comment]
@navarr The patch you posted is not correct and excessive. After analyzing the code, it would be sufficient to replace all `Object.entries` with `Object.keys` because we are only trying to figure out if said object is empty or not so the outcome would be the same.

**Comment by sdzhepa** [comment]
The Issue has been fixed and included in the 2.3.6 Magento release.
