### ISSUE TITLE
Customer not properly notified when back-ordering a product

### ISSUE THREAD

**Issue by cs-media** [magento/magento2#28758]
### Preconditions (*)
1. Magento v2.3.2 & v2.3.5 p1 (not tested between these versions)

### Steps to reproduce (*)
1. Blank install of v2.3.5 p1
2. Add a product, set to "in stock", quantity 0.
3. In advanced inventory, set back-orders to "Allow Qty Below 0 and Notify Customer"

### Expected result (*)
1. When adding that product to the basket, you should receive a warning about the stock level and that it is being back-ordered, perhaps something like, "The item you have added isn't currently in stock, but we will back-order it for you" with an orange alert warning or red error alert styling?
2. On the checkout page, the customer should be notified again to ensure it is clear that the product will be on back-order and may take a little longer to be shipped.

### Actual result (*)
1. The product added to basket notice is "You added *product* to your shopping cart" in Green.
2. The back-order message is hidden, unless you click the little drop down link on the order summary. This means the customer can add a product to the cart, go through checkout and not even notice that the product wasn't in stock.
 2b. The warning "We don't have as many quantity as you requested, but we'll back-order the remaining 1." doesn't really read right. Would something like : "We don't have the quantity that you requested in stock, but we'll back-order the remaining 1." or "The requested quantity of *product* isn't in stock. The remaining *1* will be back-ordered." sound any better?

**Comment by gwharton** [comment]
This has been fixed in 2.4.

**Comment by gwharton** [comment]
I concur that the backorder message appears on the shopping cart, does NOT appear on the minicart, does NOT appear in checkout and does NOT appear on the product page add to cart confirmation message. I had to add these bits myself for my store.

**Comment by krishprakash** [comment]
Hi @cs-media. Reviewed in 2.4-develop instance and
Messages are showing in Mini cart, Shopping cart and checkout pages but yes we can update the message text as per your request so approve this as per suggested changes

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38054` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Surabhi-Cedcoss** [comment]
@magento i am working on this

**Comment by Surabhi-Cedcoss** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Hi @cs-media. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-38054` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
