### ISSUE TITLE
Web Setup Wizard not working if root directory is set to pub/

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#28753]
### Preconditions (*)

1. Magento 2.3.5-p1 
2. Apache
3. [This](https://devdocs.magento.com/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.html) instruction to configure the magento 2 root directory - pub / folder

### Steps to reproduce (*)

1. Install magento 2
2. Configure your webserver so that root directory of magento 2 is pub/ folder
3. Login to backend
4. System -> Tools: Web Setup Wizard

### Expected result (*)

1. Web Setup Wizard page is opened

### Actual result (*)

1. 404 site
![Peek 2020-07-15 15-18](https://user-images.githubusercontent.com/60198022/87544143-a3075f80-c6ae-11ea-8b9c-ed4b30c70608.gif)

### Proposed solution (*)
It does not work because the setup directory is not inside the **pub** directory

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hello @Eddcapone 
Could you provide more details for reproduce this issue?
Do you use [this](https://devdocs.magento.com/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.html) instruction to configure the magento 2 root directory - pub / folder?

Thank you!

**Comment by Eddcapone** [comment]
Hello @engcom-Lima, we are hosted on www.rackspeed.de and I set the root directory via the cPanel to the pub folder.

**Comment by engcom-Lima** [comment]
Hello @Eddcapone 
Do you have access to the Command Line?
If don't than refer to your host support.

According to the [magento documentation](https://docs.magento.com/user-guide/system/web-setup-wizard.html):
> The Web Setup Wizard is being deprecated in Magento 2.3.6 and will be removed in Magento 2.4.0. After it is removed, you must use the command line to install or upgrade Magento, as well as extensions.

**Comment by Eddcapone** [comment]
Yes I have access to the command line.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35897` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone ,
Thank you for your report!
Support of web wizard was deprecated in 2.3.x and dropped in Magento 2.4.0, you can see it was shown in the docs for 2.3.x version https://docs.magento.com/user-guide/v2.3/system/web-setup-wizard.html
![image](https://user-images.githubusercontent.com/1873745/92564757-5ab98780-f282-11ea-9220-c73eb96ef730.png)

As alternative you could install Magento using CLI https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli.html

As this functionality was already removed, I'm closing this issue as not relevant anymore.
