### ISSUE TITLE
Unable to Create Order with Grand Total = $0.00 in Magento Admin

### ISSUE THREAD

**Issue by PromInc** [magento/magento2#28763]
### Preconditions (*)

1. Magento Version 2.3.4-p2
2. Vertex is Enabled, configured, and tested to be working (Stores -> Configuration -> Sales -> Tax -> Vertex Settings)
3. Simple product is created with price > $0.00
4. A customer account exists
5. The customer account has a saved address in a state that charges tax (ie. Minnesota, USA)

### Steps to reproduce (*)
1. In the Magento Admin, navigate to **Sales -> Orders**
2. Click **Create New Order**
3. Select an existing customer who has a saved address in a taxed state (ie. Minnesota, USA)
4. Click **Add Products**
5. Check the _Select_ checkbox for a product and click the **Add Selected Product(s) to Order** button
6. Check the **Custom Price*** check box for the added product
7. Enter **0.00** in the Custom Price text box
8. Click the **Update Items and Quantities** button

### Expected result (*)
1. ![image](https://user-images.githubusercontent.com/7319505/84924886-c37fd200-b08e-11ea-91bf-05dc13efdf25.png)
2. ![image](https://user-images.githubusercontent.com/7319505/84924952-dbefec80-b08e-11ea-99ee-f1d20572ea6b.png)
3. No error message
4. No tax applied on the order

### Actual result (*)
1. ![image](https://user-images.githubusercontent.com/7319505/84924690-84ea1780-b08e-11ea-8a31-58a8d4a59a86.png)
2. An error response is thrown in the messages area
3. Error thrown in `var/log/system.log`:
`[2020-06-17 16:32:58] main.CRITICAL: Exception message: Notice: Undefined index: product_and_shipping in /path/to/mage/install/vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php on line 782
Trace: <pre>#1 Magento\Tax\Model\Sales\Total\Quote\CommonTaxCollector->convertAppliedTaxes() called at [vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php:652]
#2 Magento\Tax\Model\Sales\Total\Quote\CommonTaxCollector->processAppliedTaxes() called at [vendor/magento/module-tax/Model/Sales/Total/Quote/Tax.php:133]
#3 Magento\Tax\Model\Sales\Total\Quote\Tax->collect() called at [vendor/magento/module-quote/Model/Quote/TotalsCollector.php:274]
#4 Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals() called at [vendor/magento/module-quote/Model/Quote/TotalsCollector.php:148]
#5 Magento\Quote\Model\Quote\TotalsCollector->collect() called at [vendor/magento/module-quote/Model/Quote.php:1995]
#6 Magento\Quote\Model\Quote->collectTotals() called at [vendor/magento/module-sales/Model/AdminOrder/Create.php:459]
#7 Magento\Sales\Model\AdminOrder\Create->saveQuote() called at [vendor/magento/module-sales/Controller/Adminhtml/Order/Create.php:283]
#8 Magento\Sales\Controller\Adminhtml\Order\Create->_processActionData() called at [vendor/magento/module-sales/Controller/Adminhtml/Order/Create.php:142]
#9 Magento\Sales\Controller\Adminhtml\Order\Create->_processData() called at [vendor/magento/module-sales/Controller/Adminhtml/Order/Create/LoadBlock.php:58]
#10 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#11 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#12 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#15 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/LoadBlock/Interceptor.php:26]
#18 Magento\Sales\Controller\Adminhtml\Order\Create\LoadBlock\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:168]
#19 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:101]
#20 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#21 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#24 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#25 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#26 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre> [] []
`

### Additional information

- Tested both options of the **Summarize Tax By** setting - **Product and Shipping** and **Jurisdiction**

> Stores -> Configuration -> Sales -> Tax -> Vertex Settings -> Summarize Tax by

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by PromInc** [comment]
My proposed solution:

File: `vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php`

Line: 782

Change:
`$baseAppliedTax = $baseAppliedTaxes[$taxId];`
To:
`$baseAppliedTax = ( isset( $baseAppliedTaxes[$taxId] ) ? $baseAppliedTaxes[$taxId] : 0 );`

**Comment by navarr** [comment]
Hi @PromInc, thank you for your report.  I'm sorry you experienced this issue.

Internal Ticket: BUNDLE-2660

**Comment by navarr** [comment]
@PromInc: I also encourage opening a support ticket with Vertex directly if possible.  They like to track these issues and it'll help ensure it gets properly prioritized.

**Comment by PromInc** [comment]
@navarr I appreciate the suggestion.  Do you have a recommendation as to how/where I open a ticket with them?  Through my client admin or do they have a repo/support channel for the Magento portion?

**Comment by PromInc** [comment]
Also of note, I tested with a 2nd customer who has one saved address in California - a non-taxed state for our Vertex configuration.  That customer did not have issues.

In this block of code:
```
       ## vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php

       if (!$appliedTaxes || !$baseAppliedTaxes) {
            return $appliedTaxesArray;
        }
```

_Customer 1_ Billing Address is a **non**-taxable state:
```
count( $appliedTaxes ) = 1
count( $baseAppliedTaxes) = 0
```


_Customer 2_ Billing Address is a taxable state:
```
count( $appliedTaxes ) = 1
count( $baseAppliedTaxes) = 1
```

Change Billing Address for _Customer 2_ to a **non**-taxable state:
```
count( $appliedTaxes ) = 1
count( $baseAppliedTaxes) = 0
```

**Comment by navarr** [comment]
@PromInc:

Please send as much detail as possible to cloudsupport@vertexinc.com; include your company name (the Vertex customer) and contact information.

Thank you for that additional detail.  It looks like somehow we're not setting baseAppliedTaxes when we should be.  Is your Magento configuration setup to charge tax based on the original price or the custom price?

**Comment by PromInc** [comment]
Thank you for the support contact info.

I am configured for **Custom price if available**

```
mysql> SELECT * FROM core_config_data WHERE path LIKE '%apply_tax_on%';
+-----------+---------+----------+------------------------------+-------+---------------------+
| config_id | scope   | scope_id | path                         | value | updated_at          |
+-----------+---------+----------+------------------------------+-------+---------------------+
|       759 | default |        0 | tax/calculation/apply_tax_on | 0     | 2019-12-19 16:01:56 |
+-----------+---------+----------+------------------------------+-------+---------------------+
1 row in set (0.00 sec)
```

![image](https://user-images.githubusercontent.com/7319505/85606699-073b8400-b619-11ea-8127-228f05a2561b.png)

**Comment by navarr** [comment]
Fixed in Magento 2.3.6

**Comment by navarr** [comment]
@PromInc Do you want a patch?

**Comment by PromInc** [comment]
@navarr yes a patch file would be appreciated.  Thank you.

**Comment by navarr** [comment]
@PromInc Please find the patch here: https://gist.githubusercontent.com/navarr/646de78ee83ed6822209836e7034821c/raw/db0cdb6472eb2adcab9349e432a41129b6dd3037/VRTX-788-2.3.4-p2.patch

I'm sorry for the delay.  After this patch is applied, $0 orders will be processed by Vertex

**Comment by navarr** [comment]
@PromInc Are you able to confirm the patch solved your issue?

**Comment by PromInc** [comment]
@navarr sorry no I haven't had a chance to test the patch yet.  A 3rd party developer provided a solution for us that we are using currently.

Regarding the patch file, how can I apply the patch is a safe way?  The patch modifies a file in the `vendor` directory which is controlled by composer.  A `composer install` or `composer update` will wipe out the patch.

Thanks.

**Comment by navarr** [comment]
@PromInc If using Magento Cloud or ECE Tools during deployment, you can place it in m2-hotfixes

Otherwise, I recommend using the [cweagans/composer-patches plugin](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#composer)
