### ISSUE TITLE
Shogun Free Page Builder is not free, just deceive the customers

### ISSUE THREAD

**Issue by marciommm** [magento/magento2#28760]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
@marciommm - Please add proper steps to be reproduced, actual result and expected result.

**Comment by ajijshekh123** [comment]
Hello @marciommm,
Now, Let me close this issue. After added proper details you can reopen this issue again.
Thanks.
