### ISSUE TITLE
GraphQL Rewards Points :: Monolith Implementation - Customers query

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28769]
As a Headless Commerce Magento Merchant,

I want to offer a reward points feature in MyAccount to my end customers via GraphQL

so that

they can receive reward points on purchase and other site actions. 

**Acceptance Criteria**

- Customers can retrieve reward points details. 
- Customers can see the reward history in their accounts.

**Schema** 

https://github.com/magento/architecture/blob/e1e39e869595aeed0f7decedd72602d0c148f6be/design-documents/graph-ql/coverage/reward-points.graphqls

**Comment by danielrenaud** [comment]
Pull Request: https://github.com/magento/partners-magento2ee/pull/277

**Comment by cpartica** [comment]
we need to find a unique way to link EE PRs
