### ISSUE TITLE
Incorrect error when saving a dropdown attribute - global

### ISSUE THREAD

**Issue by xkerkhof** [magento/magento2#2876]
Thes error appears when adding a new attribute. 

I gave it a name - Select dropdown - Global and add two options to it. I gave it a label and altered the storeview options to my desire.

When hitting save it shows "This is a required field" under "Manage Options (values of your attribute)". I have entered two options though. So I can't save the attribute now.

_Workaround, awfull_
When I inspect the hidden input type, make it a text input and add 2. It does save.

**Comment by xkerkhof** [comment]
I know see, that it depends if you set the setting "Value required" to Yes. 

With no selected it works

**Comment by katmoon** [comment]
Hi,

Is this a customer attribute or a product attribute?
Could you attach a screenshot with the error, please?

Thanks,
Kateryna.

**Comment by xkerkhof** [comment]
It;s a product attribute
- Store -› Attributes -› Product.
- Add new attribute

![example_attr_error](https://cloud.githubusercontent.com/assets/15209284/12199039/5a0ccc92-b615-11e5-8956-d6e24535ad27.jpg)

**Comment by katmoon** [comment]
I see you found a workaround for this issue, though it's awful.
Could you clear browser cache just in case, reproduce it and paste the content of `<table class="admin__control-table">` element here?

Which version of Magento do you use?

Thanks,
Kateryna.

**Comment by xkerkhof** [comment]
Cleared the cache, doesn't work. Using Magento 2.0.0 (is there an other?).

<div id="manage-options-panel">
        <table class="admin__control-table">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th">Is Default</th>
                                            <th>English</th>
                                            <th>Admin</th>
                                            <th>Nederlands</th>
                                            <th>Deutsch</th>
                                        <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate ui-sortable"><tr>
            <td class="col-draggable">
                                    <div data-role="draggable-handle" class="draggable-handle" title="Sort Option"></div>

```
                            <input data-role="order" type="hidden" name="option[order][option_0]" value="1">
        </td>
        <td class="col-default control-table-actions-cell">
            <input class="input-radio" type="radio" name="default[]" value="option_0" checked="">
        </td>
                    <td class="col-option_0"><input name="option[value][option_0][1]" value="" class="input-text" type="text"></td>
                    <td class="col-option_0"><input name="option[value][option_0][0]" value="" class="input-text required-option" type="text"></td>
                    <td class="col-option_0"><input name="option[value][option_0][2]" value="" class="input-text" type="text"></td>
                    <td class="col-option_0"><input name="option[value][option_0][3]" value="" class="input-text" type="text"></td>
                    <td id="delete_button_container_option_0" class="col-delete">
            <input type="hidden" class="delete-flag" name="option[delete][option_0]" value="">
                                <button id="delete_button_option_0" title="Delete" type="button" class="action- scalable delete delete-option">
                    <span>Delete</span>
                </button>
                        </td>
    </tr></tbody>
        <tfoot>
        <tr>
            <th colspan="7" class="validation">
                <input type="hidden" class="required-dropdown-attribute-entry valid" name="dropdown_attribute_validation">
            </th>
        </tr>
        <tr>
            <th colspan="7" class="col-actions-add">
                                        <button id="add_new_option_button" title="Add Option" type="button" class="action- scalable add">
                         <span>Add Option</span>
                    </button>
                                </th>
        </tr>
        </tfoot>
    </table>
    <input type="hidden" id="option-count-check" value="" class="required-options-count" aria-invalid="true" aria-describedby="option-count-check-error"><label for="option-count-check" generated="true" class="mage-error" id="option-count-check-error">This is a required field.</label>
</div>
```

**Comment by katmoon** [comment]
Value for `<input name="option[value][option_0][0]" value="" class="input-text required-option" type="text">` is not set for some reason.

Magento can be installed in 3 ways, see http://devdocs.magento.com/guides/v2.0/install-gde/continue.html
The freshest version is available on Github.

**Comment by mageman** [comment]
You can also add a new temporary attribute value, and then delete it.  Then you will be allowed to submit the form.

**Comment by vzabaznov** [comment]
Looks like this bug cannot be reproduced on current version, @xkerkhof could you check it please with the fresh magento version from github

**Comment by vzabaznov** [comment]
Closing the issue as it cannot be reproduced and there is no response has been received from the reporter.
@xkerkhof please feel free to reopen if you feel that issue could be reproduced.

**Comment by MarcelMaru** [comment]
Magento 2.0.4 / Installed from tar.gz and command line
Apache 2 / Ubuntu

I got this bug too. Can't create the dropdown attribute.
![seleccion_026](https://cloud.githubusercontent.com/assets/4304919/14506637/6f73a7bc-0184-11e6-8aeb-8c6b182b1f4a.png)

**Comment by zinittest** [comment]
@xkerkhof Thanks for workaround. Really saved my time. I've experienced this issue on CE 2.0.4. BTW, must be related to #3765.

**Comment by tomfree** [comment]
Have the same issue with MAgento 2.0.7 CE that I downloaded from Github this Monday. Also when I select Values Required= Yes it does not work. With Value No it works.

**Comment by xkerkhof** [comment]
I think there is enough proof to open this issue again? Can't find how myself.

**Comment by billcornell** [comment]
This is still a bug.  When you create a multi-select attribute and add values, then save the product, the attribute values do not appear afterwards.  They're hidden.

**Comment by billcornell** [comment]
I see the JS code below in the source.  Why are these attribute option values not appearing in the page?

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": [{"checked":"","intype":"checkbox","id":"4","sort_order":"0","store1":"Billerica","store0":"Billerica"},{"checked":"","intype":"checkbox","id":"5","sort_order":"0","store1":"Chelsea","store0":"Chelsea"},{"checked":"","intype":"checkbox","id":"6","sort_order":"0","store1":"Dorchester","store0":"Dorchester"},{"checked":"","intype":"checkbox","id":"7","sort_order":"0","store1":"Lynn","store0":"Lynn"},{"checked":"","intype":"checkbox","id":"8","sort_order":"0","store1":"Randolph","store0":"Randolph"},{"checked":"","intype":"checkbox","id":"9","sort_order":"0","store1":"West Boylston","store0":"West Boylston"},{"checked":"","intype":"checkbox","id":"16","sort_order":"1","store1":"Chicopee","store0":"Chicopee"},{"checked":"","intype":"checkbox","id":"17","sort_order":"1","store1":"Gardner","store0":"Gardner"}],
                    "isSortable":  1,
                    "isReadOnly": 0                }
            }
        }
    </script>

**Comment by billcornell** [comment]
<pre>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": [{"checked":"","intype":"checkbox","id":"4","sort_order":"0","store1":"Billerica","store0":"Billerica"},{"checked":"","intype":"checkbox","id":"5","sort_order":"0","store1":"Chelsea","store0":"Chelsea"},{"checked":"","intype":"checkbox","id":"6","sort_order":"0","store1":"Dorchester","store0":"Dorchester"},{"checked":"","intype":"checkbox","id":"7","sort_order":"0","store1":"Lynn","store0":"Lynn"},{"checked":"","intype":"checkbox","id":"8","sort_order":"0","store1":"Randolph","store0":"Randolph"},{"checked":"","intype":"checkbox","id":"9","sort_order":"0","store1":"West Boylston","store0":"West Boylston"},{"checked":"","intype":"checkbox","id":"16","sort_order":"1","store1":"Chicopee","store0":"Chicopee"},{"checked":"","intype":"checkbox","id":"17","sort_order":"1","store1":"Gardner","store0":"Gardner"}],
                    "isSortable":  1,
                    "isReadOnly": 0                }
            }
        }
    </script>
</pre>

**Comment by pboisvert** [comment]
@billcornell if this issue is still present as described in the original description please re-open the bug. If a new issue please file a new issue with steps needed to reproduce the error. thanks

**Comment by Jmarles** [comment]
Can we re-open this bug please?  Magento ver. 2.1.10.  When you create a dropdown attribute and add values, then save the product, the attribute values do not appear afterwards. They're hidden.  I am still able to add new options to the attribute, and I can see the values within edit product page but I can't see any previously saved options within the edit attribute page.
