### ISSUE TITLE
Incorrect order status when concurrent order save

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#2877]
**Example**
- PSP updates order status
- Delivery management module updates delivery information

When both modules load and save an order then last one overwrite changes from previous save.
This problem can be actual even if PSP module is working only.
Such problems are expensive to investigate and fix and, of course, are not acceptable for E-commerce solution.

**Preferable solution**

Implement read/write modes for entity load where "write" mode will guarantee lock.
It can be third parameter
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public function load($modelId, $field = null, $mode = 'r')
or additional function
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public function loadForSave($modelId, $field = null)
or flag (preferable one because will looks the same as for collection)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$model->setLoadForSave(true)

**Conditions**
- If entity was opened for read only, "save" method should throw exception
- LoadForSave should be able to wait amount of seconds for a lock
- If lock wait timeout, exception should be thrown
- Lock wait timeout exception should have information who locked the entity for a long time, most useful will be the full back-trace of successful lock taking
- If save method has been created new entity lock should be arranged before entity commit into database and removed in case of rollback.
- MySQL GET_LOCK should be used
- Lock release should be implemented in the destructor to release the lock when object is removed by gc
- If loadForSave can be called several times for the same model instance then lock release should be also added right in loadForSave function or exception should be thrown so that new instance should be created for a new entity load
- Collections also should support load mode, it can be done by a flag like $collection->setLoadForSave(true)

**Comment by andimov** [comment]
@vesan-83 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
