### ISSUE TITLE
Advanced Price - From & To Dates do not format correctly in any non-English locale.

### ISSUE THREAD

**Issue by DanielRiezebos** [magento/magento2#28801]
### Preconditions (*)

1. Magento ver. 2.3.4-p2 | `2.4-develop`
2. PHP 7.3 (Although I suspect this to be on the JavaScript/jQuery side)

### Steps to reproduce (*)

1. Log into the Magento admin with an account that uses any non-English locale.
2. Open/Create a Product with an advanced price.
3. Open said advanced price and look at the dates in the "Special Price From" & "To" fields.

### Expected result (*)

1. A date, perfectly formatted to the installed locale.

### Actual result (*)

A date, incorrectly formatted with very strange results. The product price dates you see below are from a product that has a **From** date of 01-06-2020 and a **To** date of 30-06-2020. This was displayed with a Dutch locale:
![pricebug](https://user-images.githubusercontent.com/42472960/85026755-5ac15400-b179-11ea-989b-91d8a55f6c34.png)

As a test I had set my locale to Arabic (Morocco) and discovered this following:
![prijsbug_marrokaans](https://user-images.githubusercontent.com/42472960/85028132-fef7ca80-b17a-11ea-9aef-f68e09b760dd.png)

Obviously this should not be like this.
I've looked around in the calendar.js file, the uiComponent class etc. but to no avail. 
I could not understand how these dates are formatted so strangely.

### Workaround
We have told our client to set their admin language to English for the time being, so that these dates will be formatted correctly. Though this hinders them a bit in their workflow of course.

### Additional information
- more detailed steps and screens https://github.com/magento/magento2/issues/28801#issuecomment-646432010

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DanielRiezebos** [comment]
@magento give me 2.3.4-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRiezebos. Thank you for your request. I'm working on Magento 2.3.4-p2 instance for you

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28801-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28801-2-4-develop.instances.magento-community.engineering/admin_a908](https://i-28801-2-4-develop.instances.magento-community.engineering/admin_a908)
Login: `0edf8afe` Password: `7702edfca0b7`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@DanielRiezebos: The issue is reproducible on Magento 2.4 develop instance. 
Step to change non-English locale:
1. Go to admin
2. Click on Account Settings from the dropdown in the right coroner
![image](https://user-images.githubusercontent.com/58288685/85097649-c9ec8600-b215-11ea-8806-d382da54e745.png)
3. Scroll to Interface Locale 
4. Change to Arabic (Morocco) 

Please find the attachment.
1. non-English locale to  Arabic (Morocco) 
![image](https://user-images.githubusercontent.com/58288685/85097539-72e6b100-b215-11ea-980d-a49db82eefc7.png)

2. Product special price date format:
![image](https://user-images.githubusercontent.com/58288685/85097570-83972700-b215-11ea-8e5b-2aaaec6a7647.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35312` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by DanielRiezebos** [comment]
@swathishs thank you for taking the time to investigate this. :)

**Comment by kaktusAtAdvox** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
