### ISSUE TITLE
Magento Upgrade Issue

### ISSUE THREAD

**Issue by cba-records** [magento/magento2#28808]
### Preconditions (*)

1. PHP 7
2. Magento 2

### Steps to reproduce (*)

Upgrade issue:

An abstract factory could not create an instance of magentoframeworkappdeploymentconfig(alias: Magento\Framework\App\DeploymentConfig).

### Expected result (*)

1. Upgrade through CLI

### Actual result (*)

1. Error message detailed above

**Comment by premier-web-design** [comment]
@magento I am working on this
