### ISSUE TITLE
Minimum Advertised Price "show on Gesture" does not work for CMS pages other than Homepage and when the same product appears twice on a page

### ISSUE THREAD

**Issue by hannahnida** [magento/magento2#28814]
When "Catalog Products List" widget (or others with products) contains a product set to show MAP option "on Gesture" and is set to show up on CMS Page other than Homepage
the MAP modal/tooltip does not work when clicking on "Click for price".

Also when a page (for example Homepage/Catalog Category Page) has two containers with Product Listing in which the same product with MAP setting "on Gesture" is visible, MAP modal/tooltip only works for the first product on a page. 

MAP modal/tooltip works (except CMS pages) when the product is appearing only once on a page.

### Preconditions (*)

1. Magento `2.4-develop`
2. Magento_Msrp module enabled, MAP setting enabled, MAP set on product with "on Gesture" option selected

### Steps to reproduce (*)

1. Add MAP with "on Gesture" option selected to a product.
2. Add a widget with that product to a CMS page other than Homepage.
3. Notice that MAP modal/tooltip does not work.
4. Add layout update to the widget to show it on the same category as the product already has.
5. Navigate to category.
6. Notice that only one of product MAP modal/tooltips work.

### Expected result (*)

1. MAP "on Gesture" modal works for CMS pages.
2. MAP "on Gesture" modal works when the same product appears on a page twice.

### Actual result (*)

1. MAP "on Gesture" modal does not work.

### Additional Information
- more detailed steps and screens  https://github.com/magento/magento2/issues/28814#issuecomment-647971012
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28814-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28814-2-4-develop.instances.magento-community.engineering/admin_9b74](https://i-28814-2-4-develop.instances.magento-community.engineering/admin_9b74)
Login: `dcd5a685` Password: `fbed81fe0cca`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@hannahnida : Issue is reproducible in Magento 2.4 develop instance.

Step to reproduce:
1. On the Admin sidebar, go to Stores > Settings > Configuration.
2. In the left panel, expand Sales and choose Sales underneath.
3. Expand the Minimum Advertised Price section.
4. Set Enable MAP to Yes.
5. Go to any product and click on edit
6. Click on advance pricing 
7. Enter MAP
8. Display actual price - Gesture
9. Save 
10. Go to content-page
11. Create on content and insert widget - Product listing and save
12. Now go to frontend and enter the URL and go to the cms page
13. Click on price link doesn't work

Please find the attachment s below:

1. Advance pricing : 
![image](https://user-images.githubusercontent.com/58288685/85375104-72bb1e00-b553-11ea-983d-d6a2a9ce63d3.png)

2. Cms page:
![image](https://user-images.githubusercontent.com/58288685/85375188-8fefec80-b553-11ea-8402-df5ed3a8686b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35371` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by srsathish92** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @hannahnida, @zaximus84. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-35371` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
