### ISSUE TITLE
Customer is asked for password of not existing account after browser refresh in Guest Checkout

### ISSUE THREAD

**Issue by hannes011** [magento/magento2#28813]
In certain conditions a guest customer may be confused by mandatory password field in checkout: they will be requested for a password of a account which does not exist after refreshing browser.

The bug was created by commit https://github.com/magento/magento2/commit/0861a3077135f40d9728dc1e6cfec3ab7387f3a3
 
### Preconditions (*)

1. Issue was introduced in 2.3.x https://github.com/magento/magento2/commit/0861a3077135f40d9728dc1e6cfec3ab7387f3a3

### Steps to reproduce (*)

1. make sure you have a clean session (otherwise checkoutData.getCheckedEmailValue() might not be empty anymore)
2. add product to cart
3. start guest checkout 
4. enter email which does NOT belog to any customer account
5. select another field, so the entered email will be checked if there is any matching account (at this point the password field will NOT yet show up)
6. refresh browser
7. now there is a mandatory password field asking for a password which does not exist

### Expected result (*)

1. after refresh the password field must stay hidden -> resolveInitialPasswordVisibility() must return false

### Actual result (*)

1. after refresh the password field was shown and will only remove after adjusting email field -> resolveInitialPasswordVisibility() returns true

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28813-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28813-2-4-develop.instances.magento-community.engineering/admin_9f23](https://i-28813-2-4-develop.instances.magento-community.engineering/admin_9f23)
Login: `732d6949` Password: `0e51bd97a159`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @hannes011. Thank you for your report.
Seems similar issue is added here #26903 and already open.
So closing this ticket.

**Comment by krishprakash** [comment]
@swathishs Kindly do not reopen the issue as it already duplicated.
Thank you !!

**Comment by swathishs** [comment]
@krishprakash  :  I am not reopening the ticket. If someone assigns the ticket for testing .Please don't come and close the ticket

**Comment by krishprakash** [comment]
@swathishs As I already verified the same kind of issue previously that's why I'm closing the ticket.
Hope you understand :)
Thank you !!
