### ISSUE TITLE
a validation rule for Qty uses decimal should be added

### ISSUE THREAD

**Issue by mohamedalichelbi** [magento/magento2#28817]
### Preconditions (*)

1. Magento ver. 2.3.5-p1

### Steps to reproduce (*)

1. set Qty uses decimal to "no" for some product
2. go to the product's page and give a decimal value in the qty input field
3. click on add to cart

### Expected result (*)

1. an error should pop up on the screen, just like errors given when choosing 0 for the quantity or a number that's bigger than max Quantity// less than min Quantity.

### Actual result (*)

1. i was redirected to checkout with the quantity field empty

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28817-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28817-2-4-develop.instances.magento-community.engineering/admin_a0ad](https://i-28817-2-4-develop.instances.magento-community.engineering/admin_a0ad)
Login: `3c6c5afc` Password: `f317915364da`
Instance will be terminated in up to 3 hours.

**Comment by mohamedalichelbi** [comment]
any updates on the issue please ??

**Comment by krishprakash** [comment]
Hi @mohamedalichelbi. Thank you for your report.
Not able to reproduce the issue. Refer the screenshot below:

![image](https://user-images.githubusercontent.com/46617848/94551011-4c073480-0272-11eb-848b-a16ae93db78d.png)

Feel free to reopen the issue once you confirm the issue is reproduce on 2.4-develop branch

Thanks!!
