### ISSUE TITLE
Return to the previous URL after logging in to the admin panel

### ISSUE THREAD

**Issue by astleyclarke** [magento/magento2#28819]
### Description (*)
After logging in to the admin panel, the user should be taken to the previously-requested URL instead of being taken to the default (dashboard) page.

### Expected behavior (*)
1. Log out from your existing admin session, if required
2. Visit an admin panel URL (e.g. `https://www.example.com/admin/example/catalog_product/`)
3. You will be redirected to the log in form and required to log in. Log in now.
4. After logging in, you should be taken to the required URL `https://www.example.com/admin/example/catalog_product/`. Currently, this does not happen.

### Benefits
This would reduce frustration and wasted time in making repeated requests for the same page.

### Additional information
This also happens if your admin session times out while you're using an admin page and you need to re-log-in.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28819-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28819-2-4-develop.instances.magento-community.engineering/admin_2188](https://i-28819-2-4-develop.instances.magento-community.engineering/admin_2188)
Login: `1b45a61c` Password: `c4d58c9c4187`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@astleyclarke.
Thank you for reporting this issue. As per the step given above tested in Magneto 2.4 develop instance the user been taken to the default (dashboard) page rather than previously-requested URL.
I think your issue can be approved only like a feature request. Please transfer this issue to  [Magento Feature request](https://github.com/magento/community-features) repository.
Thanks
