### ISSUE TITLE
Typos on code

### ISSUE THREAD

**Issue by pgrimaud** [magento/magento2#28829]
### Preconditions (*)

1. 2.4-develop (and before I guess)

### Steps to reproduce (*)

1. Just read the method here : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/ResourceModel/Address/Grid/Collection.php#L260

### Expected result (*)

1. Method should be named `getRegionNameExpression`

### Actual result (*)

1. Method is named `getRegionNameExpresion`

Must check for occurrences and fix it too.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pgrimaud** [comment]
@magento I am working on this

Gonna check if I could find other typos 😄

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35522` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @pgrimaud. Thank you for your report. 
The issue has been fixed in magento/magento2#28832 by @pgrimaud in 2.4-develop branch
Related commit(s):
 - [ae076d67f481df6093ccd603809de5c1b99c09eb](https://github.com/magento/magento2/commit/ae076d67f481df6093ccd603809de5c1b99c09eb)

The fix will be available with the upcoming 2.4.1 release.
