### ISSUE TITLE
Install button not coming up

### ISSUE THREAD

**Issue by rajab12** [magento/magento2#28820]
### Summary (*)
Trying to setup the Magento 2 in the XAMPP of my windows machines. Got the source code from the Github here. Tried to launch after pasting the source code folder in htdocs of XAMPP. 

The install button is not coming up. Added the version number in composer.json, verified the php.ini, restarted the Apache. But the Install button is not coming. 

Tried downloading through composer. Same result. Allow me to share the screenshot. 

![image](https://user-images.githubusercontent.com/9885953/85216980-e93bfe00-b350-11ea-805a-f68fa4473728.png)

Couldn't find any turnaround in the public forums. Hope somebody can guide me through. Thanks.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
[](url)

**Comment by swathishs** [comment]
@rajab12 : 
Thank you for your report. 
GitHub issue tracker is intended for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

**Comment by rajab12** [comment]
@swathishs Sure will reach out to the Community group. Stack exchange didn't help much.
