### ISSUE TITLE
The \Magento\Config\Block\System\Config\Form\Field::_renderValue() method generates unnecessary empty HTML tags for a backend config field's comment when the field XML declaration contains an empty <comment><![CDATA[]]></comment> tag (and my fix)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2883]
https://mage2.pro/t/179

**Comment by andimov** [comment]
@mage2pro thank you for reporting.
Please fill description according to the template and specify magento version here.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
