### ISSUE TITLE
Cart Rule for Payment Methods - Stored Card Braintree broken in 2.3.5

### ISSUE THREAD

**Issue by ghost** [magento/magento2#28837]
### Preconditions (*)

1. Magento 2.3.5 EE
2. Customer account with 1 or more stored cards
3. Cart Rule enabled for "Payment Method  is  Stored Cards (Braintree)", coupon code is optional

### Steps to reproduce (*)

1. Login to customer account
2. Add item to cart
3. Go to checkout
4. Enter shipping address and select shipping, continue to payment
5. Select a stored card
6. (Optionally add the coupon code and submit)

### Expected result (*)

1. Cart rule applied for selected payment method

### Actual result (*)

1. Cart rule not applied for selected payment method

I believe the issue is due to the fact that the Braintree stored cards have a method name of "braintree_cc_vault_1", "braintree_cc_vault_2" etc, instead of just "braintree_cc_vault" - which is the payment method code that the cart rule checks for.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hello @paul-gene 
Thank you for contribution and collaboration!

This is related with Braintree is third party extension and not included in magento EE by default.
Please refer to the [Braintree support](https://help.braintreepayments.com/), for advice or general discussion about this issue.

So I have to close this issue.
Thanks for your report!
