### ISSUE TITLE
GraphQL Rewards Points :: Monolith Implementation - Store Configuration

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#28835]
The store config query should be able to return configuration from the magento_reward general and points sections.

**Acceptance Criteria**

When querying for the config, additional configuration for the magento_reward is available in the response

**Schema** 

https://github.com/magento/architecture/blob/e1e39e869595aeed0f7decedd72602d0c148f6be/design-documents/graph-ql/coverage/reward-points.graphqls

**Comment by cpartica** [comment]
please link the PR as this is PR In Progress  status

**Comment by gallyamov** [comment]
PR: https://github.com/magento/partners-magento2ee/pull/284

**Comment by magento-engcom-team** [comment]
Hi @pmarjan, @gallyamov. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33920` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
