### ISSUE TITLE
GraphQL Rewards Points :: Monolith Implementation - Cart query

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#28833]
As a Headless Commerce Magento Merchant, I want to offer a reward points feature in my Cart query.

Acceptance Criteria

- Cart query returns applied_reward_points too.

Schema 

https://github.com/magento/architecture/blob/e1e39e869595aeed0f7decedd72602d0c148f6be/design-documents/graph-ql/coverage/reward-points.graphqls

**Comment by cpartica** [comment]
please link the PR as this is PR In Progress status

**Comment by gallyamov** [comment]
PR: https://github.com/magento/partners-magento2ee/pull/281
