### ISSUE TITLE
GraphQL Rewards Points :: Monolith Implementation - Apply and Remove reward points from cart

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#28834]
As a Headless Commerce Magento Merchant,

I want to be able to apply and remove reward points to and from the cart.

Acceptance Criteria

Reward points can be applied to cart, so that new total adding discount is available.
Reward points can be removed from the cart, assuming they were previously applied.
Reward points are always applied all, there is NO partial redemption available.

Schema 

https://github.com/magento/architecture/blob/e1e39e869595aeed0f7decedd72602d0c148f6be/design-documents/graph-ql/coverage/reward-points.graphqls

**Comment by pmarjan** [comment]
PR: https://github.com/magento/partners-magento2ee/pull/285

**Comment by danielrenaud** [comment]
Merged in https://github.com/magento/partners-magento2ee/pull/285
