### ISSUE TITLE
Magento2 - Product PNG Image is resizing as Transparent due to which it's showing as blank on Product/Category/Product Admin Grid Page

### ISSUE THREAD

**Issue by robertbaum** [magento/magento2#28846]
### Preconditions (*)

1. Magento 2.3.3
2. upload a PNG image to the product 

### Steps to reproduce (*)

1. upload a PNG image to any product with any size 
2. you will see that the product image at the cache directory blank (transparent)

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/46323639/85388317-a182c580-b54e-11ea-98be-62f985ee3de0.png)

### Actual result (*)

1. there is no error log related

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28846-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28846-2-4-develop.instances.magento-community.engineering/admin_44e5](https://i-28846-2-4-develop.instances.magento-community.engineering/admin_44e5)
Login: `0893f334` Password: `3bde234fda5c`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@robertbaum : Issue is not reproducinle in magento 2.4 devlop instance

Please find the attachments:

1. Product admin:
![image](https://user-images.githubusercontent.com/58288685/85392164-c8e68c00-b568-11ea-9a90-795c6911cc63.png)

2. Product grid:
![image](https://user-images.githubusercontent.com/58288685/85392491-398da880-b569-11ea-9df5-508fb79fd78e.png)

**Comment by swathishs** [comment]
Hi @robertbaum , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.

**Comment by robertbaum** [comment]
but the issue happened on some m2.3.3 not all, how can I check the reason

**Comment by swathishs** [comment]
@robertbaum : We can check in 2.3.5 -p1 develop instance in this Github. Since this GitHub concentrate only on 2.4 develop instance

**Comment by robertbaum** [comment]
ok thanks
