### ISSUE TITLE
Product Edit: Make Save and Close the default action

### ISSUE THREAD

**Issue by seansan** [magento/magento2#28844]
### Description (*)
Product Edit: Make Save and Close the default action

### Expected behavior (*)
https://magento.stackexchange.com/questions/315487/how-can-i-make-save-close-the-default-action-instead-of-save

### Benefits
Make Save and CLose the default action everywhere. It is just not logical to just save? and stay on the page

### Additional information
Explained in full here https://magento.stackexchange.com/questions/315487/how-can-i-make-save-close-the-default-action-instead-of-save

**Comment by engcom-Lima** [comment]
Hello @seansan, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

**Comment by seansan** [comment]
Please take this More serious
