### ISSUE TITLE
Footer social icons always become too big on page regardless of editing

### ISSUE THREAD

**Issue by AlivreL** [magento/magento2#28848]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by swathishs** [comment]
@AlivreL: Could you please update the issue please make sure that you provided the following information to recreate the issue :
Summary of the issue
Information on your environment
Steps to reproduce
Expected and actual results

**Comment by swathishs** [comment]
Hi @AlivreL 
Feel free to reopen once you update all the details with reproducible steps
Thanks !!
