### ISSUE TITLE
Admin Menu in M2, should hover not be enough? Why the extra click to open a menu

### ISSUE THREAD

**Issue by seansan** [magento/magento2#28849]
### Description (*)
Admin Menu in M2, should hover not be enough to open a menu? Why the extra click to open a menu

### Expected behavior (*)
On hover open menu

### Benefits
Work faster, reduce clicks

### Additional information

![image](https://user-images.githubusercontent.com/652395/85395140-f541de80-b54f-11ea-967f-8b7bb85c6b3a.png)

**Comment by mrtuvn** [comment]
actually this case we should use click instead hover
Change to hover can do with a few change in css/js Hover is possible but i don't see better benefits than click approach
In mobile first hover is no need because user will need touch anyway

Menus should open when the user has made a clear decision to open it

**Comment by seansan** [comment]
Reduce clicks where possible. And this case is about desktop. Hover to show
content why else would you point the mouse to left nav?

**Comment by engcom-Lima** [comment]
Hello @seansan, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

**Comment by seansan** [comment]
Please don’t understand not close feature requests. What’s the use of this
process other ways?

Customer feedback please take it more serious.

**Comment by engcom-Lima** [comment]
Hello @seansan 
I am serious as never. [This](https://github.com/magento/community-features/issues) repo was created especially for cases like this. Please create issue there.
Thanks
