### ISSUE TITLE
 File Permission Check Error 

### ISSUE THREAD

**Issue by Khushik** [magento/magento2#2885]
![capture](https://cloud.githubusercontent.com/assets/16103149/12115003/604c3e86-b3d0-11e5-9cd6-61a0f43ab43b.JPG)
Could you please help me to fix this error. All permission were granted but no results.

**Comment by mazhalai** [comment]
@Khushik Are there any errors in your brower's console? Also, please give details about your environment like OS, Server, PHP version etc.

**Comment by ghost** [comment]
In addition, it could be a problem with ownership. You should NOT set 777 permissions on anything.

Please refer to [ownership and permissions documentation](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/zip_install.html#zip-perms)

**Comment by Khushik** [comment]
My environment:
CentOS 7
MySQL 5.6.28
Apache 2.4.6
PHP 5.6.16
Zend Engine 2.6.0
No any errors in browser's console. The following commands I have run but also no results:

chown -R :apache .
find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento

**Comment by mazhalai** [comment]
@Khushik is the logged in user (the one running command on prompt) in the same group as apache as mentioned in @xcomSteveJohnson's doc link?

**Comment by anaxmedia** [comment]
If the correct owner and file permissions are set, it's most likely SELinux.

You can try setting SELinux to permissive mode to see if that's the issue:

`setenforce 0`

If that does work, you can either leave SELinux in permissive mode or enable it and grant SE permissions on just the directory:

`setenforce 1 // set SELinux back to active enforcing mode`

`chcon -R -h -t httpd_sys_script_rw_t /var/www/yourwebsitedir/html/* // grant SE script RW priveleges to our web directory`

**Comment by Khushik** [comment]
It is a bit better, now i get the following error:
![capture](https://cloud.githubusercontent.com/assets/16103149/12162294/cd9563da-b521-11e5-8eff-e87849303c18.JPG)

**Comment by anaxmedia** [comment]
If you're seeing only 1 directory with setenforce 0 it's not SELinux, it's either the owner or file permissions. Try chown -R :apache magento2/var and setting file permissions on the magento2/var directory again.

**Comment by Khushik** [comment]
Finally I have launched my magento 2 test site. Thank you so much for your speed replies.

**Comment by suthzy** [comment]
Thank you. Setting the SELinux to permissive mode fixed this for me. I'm installing Magento 2.1 on PHP 7.0.6 on OpenLogic centos 7 all running on Windows Azure. I suggest the docs at http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html#perms-private get updated. Thanks once again @anaxmedia. took me a while to find out what I was doing wrong.

**Comment by Blueblazer172** [comment]
sad to hear that only chmod -R 0777 whole-magento-folder/ worked for me
