### ISSUE TITLE
Magento 2.3.4 graphql Notice: Undefined index: option_value in /var/www/html/mg234/vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php on line 62

### ISSUE THREAD

**Issue by prabhakaran777** [magento/magento2#28860]
### Preconditions (*)

1. Magento 2.3.4
2. Config product with custom options

### Steps to reproduce (*)

1. Create config product with custom options
2. Add product to cart (addConfigurableProductsToCart) using this mutation

```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "IkzvsoUeXwvb6g2jrdqVNmuXPqmznAqI"
      cart_items: [
        {
          parent_sku: "config-sku"
          data: {
            quantity: 1
            sku: "config-sku-White"
          }
        customizable_options:[	
          {
            id:2
            value_string:"4"
          }
        ]        }      ]
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
            value_label
            value_id
          }
         customizable_options {
            label
            values {
              value
            }
          }        }      }
    }
  }
}
```

### Expected result (*)

1. Configurable product will add to cart

### Actual result (*)

1. 
```
{
  "errors": [
    {
      "debugMessage": "Notice: Undefined index: option_value in /var/www/html/oxygen/vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php on line 62",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 36,
          "column": 11
        }
      ],
      "path": [
        "addConfigurableProductsToCart",
        "cart",
        "items",
        0,
        "configurable_options"
      ]
    }
  ],
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "items": [
          null
        ]
      }
    }
  }
}

```

**Comment by Serializator** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Serializator, here is your [Magento instance](https://i-28860-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28860-2-4-develop.instances.magento-community.engineering/admin_766c](https://i-28860-2-4-develop.instances.magento-community.engineering/admin_766c)
Login: `e3f87154` Password: `55ea7d3052fb`
Instance will be terminated in up to 3 hours.

**Comment by Serializator** [comment]
I was able to successfully reproduce thisin the 2.4-develop branch.

@magento I am working on this

**Comment by Serializator** [comment]
I seem to be able to reproduce this without any customisable options as well, simply with the configurable options.

**Comment by rhoerr** [comment]
I investigated this error for a customer.

Debugging, ​the problem is `vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php:61` expects an `$option['option_value']` to ​contain the custom option value ID, but no such value exists. `$option` is generated at `vendor/magento/module-catalog/Helper/Product/Configuration.php:113`, but `$itemOption->getValue()` is never added to the result array.
​
I believe the best fix would be adding the ID to the array in getCustomOptions:

                    $options[] = [
                        'label' => $option->getTitle(),
                        'value' => $group->getFormattedOptionValue($itemOption->getValue()),
                        'print_value' => $group->getPrintableOptionValue($itemOption->getValue()),
                        'option_id' => $option->getId(),
                        'option_type' => $option->getType(),
    +                   'option_value' => $itemOption->getValue(),
                        'custom_view' => $group->isCustomizedView(),
                    ];
​
I can't speak to what further ramifications that might have.

**Comment by indefinitedevil** [comment]
Can confirm issue still present in 2.3.5-p2.

**Comment by indefinitedevil** [comment]
Can also confirm that 

> I investigated this error for a customer.
> 
> Debugging, ​the problem is `vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php:61` expects an `$option['option_value']` to ​contain the custom option value ID, but no such value exists. `$option` is generated at `vendor/magento/module-catalog/Helper/Product/Configuration.php:113`, but `$itemOption->getValue()` is never added to the result array.
> ​
> I believe the best fix would be adding the ID to the array in getCustomOptions:
> 
> ```
>                 $options[] = [
>                     'label' => $option->getTitle(),
>                     'value' => $group->getFormattedOptionValue($itemOption->getValue()),
>                     'print_value' => $group->getPrintableOptionValue($itemOption->getValue()),
>                     'option_id' => $option->getId(),
>                     'option_type' => $option->getType(),
> +                   'option_value' => $itemOption->getValue(),
>                     'custom_view' => $group->isCustomizedView(),
>                 ];
> ```
> 
> ​
> I can't speak to what further ramifications that might have.
> 
> Still unresolved as of 2.3.5-p2 and 2.4.0.

Can also confirm that this fix does not work. If you have a string value, it conflicts with the int expectation in GraphQL.

$itemOption->getId() may be better? Really not sure.

**Comment by jesse-deboer** [comment]
> I investigated this error for a customer.
> 
> Debugging, ​the problem is `vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php:61` expects an `$option['option_value']` to ​contain the custom option value ID, but no such value exists. `$option` is generated at `vendor/magento/module-catalog/Helper/Product/Configuration.php:113`, but `$itemOption->getValue()` is never added to the result array.
> ​
> I believe the best fix would be adding the ID to the array in getCustomOptions:
> 
> ```
>                 $options[] = [
>                     'label' => $option->getTitle(),
>                     'value' => $group->getFormattedOptionValue($itemOption->getValue()),
>                     'print_value' => $group->getPrintableOptionValue($itemOption->getValue()),
>                     'option_id' => $option->getId(),
>                     'option_type' => $option->getType(),
> +                   'option_value' => $itemOption->getValue(),
>                     'custom_view' => $group->isCustomizedView(),
>                 ];
> ```
> 
> ​
> I can't speak to what further ramifications that might have.
> 
> Still unresolved as of 2.3.5-p2 and 2.4.0.

This does seem to work for me, the issue is resolved when adding this line!

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Bug
