### ISSUE TITLE
B2B Company Mutations

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28867]
As a Magento Developer,

I want to expose B2B company storefront functionality via GraphQL

So that 

customers can use a more flexible and performant API technology.

### Sub tickets
- Create and Update Company (https://github.com/magento/magento2/issues/29074)
- Create, Update and Delete Company User (https://github.com/magento/magento2/issues/29093)
- Create, Update and Delete Company Role (https://github.com/magento/magento2/issues/29094)
-  Update company hierarchy (https://github.com/magento/magento2/issues/29095)
- Create, Update and Delete Team (https://github.com/magento/magento2/issues/29092)

### Acceptance Criteria

GraphQL exposes only storefront B2B company functionality
GraphQL respects user permissions for all storefront operations.
WebAPI test coverage
All builds are green

### Approved Schema
https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/company.md

### Scope
All B2B Company mutations as per the schema https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/company.md

**Comment by munkhulzii** [comment]
Company mutations will be splited into smaller parts. 
I have created an issue for "Create and Update Company Mutation":  https://github.com/magento/magento2/issues/29074

**Comment by sasha19957099** [comment]
@magento I'm working on this
