### ISSUE TITLE
B2B Company Queries

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28866]
As a Magento Developer, 

I want to expose B2B company storefront functionality via GraphQL

So that customers can use a more flexible and performant API technology. 

**Acceptance Criteria**

> GraphQL exposes only storefront B2B company functionality 
> GraphQL respects user permissions for all storefront operations.
> WebAPI test coverage
> All builds are green

**Scope**
All B2B Company queries as per the schema https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/company.md

**Comment by cpartica** [comment]
reopening as this issue needs an additional PR to fix some cases
