### ISSUE TITLE
Allow handling POSIX signals (ie. SIGTERM for graceful termination)

### ISSUE THREAD

**Issue by michael-bouvy** [magento/magento2#28870]
### Description (*)

Magento is currently not able to handle POSIX signals, for instance `SIGTERM` that may be received from a controller (ie. within Kubernetes cluster).

Therefore, those signals can not be handled gracefully, and the process may be killed with a `SIGKILL` signal, causing an immediate stop, without calling `__destruct` methods for instance.

### Expected behavior (*)

Since PHP 7.1, signals can be received without overhead using the `pcntl_async_signals(true)` function call.

Signals can subsequently be handled using something like:

```php
pcntl_signal(SIGTERM, function () {
    // Do something that will cause graceful shutdown of process
});
```

Calling the `exit()` PHP function within this handler causes the `__destruct` class methods to be called, which is desirable.

#### Example script

```php
`<magento-root>/signal.php`
<?php
use Magento\Framework\App\Bootstrap;

require __DIR__ . '/app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();
$resourceConnection = $objectManager->create('Magento\Framework\App\ResourceConnection');

class Signal
{
    public function run()
    {
        while (true) {
            echo date('Y-m-d H:i:s') . PHP_EOL;
            sleep(1);
        }
    }

    public function __destruct()
    {
        echo __METHOD__ . PHP_EOL;
    }
}

pcntl_async_signals(true);

pcntl_signal(SIGTERM, function () {
    echo 'Caught SIGTERM' . PHP_EOL;
    exit(1);
});

(new Signal())->run();
```

When sending a `SIGTERM` signal to the process, we get the following output:

```
$ php signal.php
2020-06-24 11:06:11
Caught SIGTERM
Signal::__destruct
```

ℹ️   Without these `pcntl_*` functions, the script runs indefinitely, until killed with a `SIGKILL` signal.

**Magento should therefore call `pcntl_async_signals(true)`, at least for cron and consumers.**

### Benefits

Such signal handling would be useful to handle graceful termination of long-running processes (cron, consumers): process current message and exit, close database connection, etc.

For consumers, this achieves the same goal as _poison pill_, but with an immediate effect, not requiring to wait for the message to be processed.

### Additional information

**Comment by engcom-Lima** [comment]
Hello @michael-bouvy, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

**Comment by michael-bouvy** [comment]
Done, thanks @engcom-Lima: https://github.com/magento/community-features/issues/280
