### ISSUE TITLE
File Path Too Long

### ISSUE THREAD

**Issue by bp612** [magento/magento2#28873]
### Summary (*)

The following file path is exceptionally long and causes errors in my Windows environment:
app/code/Magento/UrlRewrite/Test/Mftf/Test/AdminCheckUrlRewritesCorrectlyGeneratedForMultipleStoreviewsDuringProductImportTest/AdminUrlRewriteMultipleStoreviewsProductImportWithConfigTurnedOffTest.xml

### Proposed solution

Please review the naming and consider shortening this to something more Windows friendly.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@brianpittvps : Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

**Comment by swathishs** [comment]
@brianpittvps : Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

Hence closing the issue

**Comment by viratraaz** [comment]
@magento I am working on this
Environment - windows 10 64-bit
problem occurs while unziping zipped file downloaded from https://magento.com/tech-resources/download 
file version - 2.4.2
format -  zip
Include sample data - No

![image](https://user-images.githubusercontent.com/10795973/108189585-e808de00-7136-11eb-96c8-c946aba3cb00.png)
