### ISSUE TITLE
Youtube videos on simple products of configurable products cannot be played

### ISSUE THREAD

**Issue by Quinten** [magento/magento2#28875]
### Preconditions (*)

Magento Version 2.3.3
with Magento Blank Theme

### Steps to reproduce (*)

1. Create a configurable product with swatches.
2. Add a youtube video to at least 2 of the simple products derived from the configurable product.
3. Go to the product detail page of the configurable product.
4. Click on the first swatch. This adds a video thumb to the gallery.
5. Click the thumb and play the video.
6. Click on the second swatch. The gallery is updated with a new video thumb.
7. Click that video thumb and try to play the video.

### Expected result (*)

There should be a play button over the video, so the video can be played.

### Actual result (*)

There is no play button over the video, so the video cannot be played.

[Screen Recording 2020-06-24 at 16.54.42.zip](https://github.com/magento/magento2/files/4826182/Screen.Recording.2020-06-24.at.16.54.42.zip)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28875-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28875-2-4-develop.instances.magento-community.engineering/admin_bbfc](https://i-28875-2-4-develop.instances.magento-community.engineering/admin_bbfc)
Login: `b59ad243` Password: `7091ca18a39e`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@Quinten : The issue is not reproducible in Magento 2.4 develop instance. Please find the attachment below:
![2diX5p7Jrv](https://user-images.githubusercontent.com/58288685/85675028-fc4d2600-b6e2-11ea-8259-1b940889b35a.gif)

**Comment by Quinten** [comment]
@swathishs Thank you!

I will have to look further then...
