### ISSUE TITLE
How can we document factories to enforce code quality

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#28883]
Hi Magento 2 community.

I can't find a way to provide documentation for factories in Magento 2. They are generated classed, which mean that at source-level, we can use them reliably since we don't know what they implements, what they returns and how they are named.

Is there a way to document them? In their current state, they are unusable since they can't be tested as part of a code quality process.

**Comment by swathishs** [comment]
@ericmorand : Thank you for your report .For GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

**Comment by ericmorand** [comment]
@swathishs , this is a dev experience issue.

And the issue is deeply linked to the Magento framework, not some good practice.

The question remains: how can we ensure code quality with classes that you recommend to use and that don't exist?

**Comment by swathishs** [comment]
@ericmorand : Hi, for any discussion. Magento development/process improvement please use the Forum link https://github.com/magento/magento2/wiki/Issue-reporting-guidelines. I'm sorry this is the best I could do and your ticket cannot be addressed in here.

Please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/) for technical questions, feature requests, etc. These reports are not guaranteed to be processed within the GitHub issue tracker.
