### ISSUE TITLE
Magneto 2.3 unable to subscribe to newsletter

### ISSUE THREAD

**Issue by ghost** [magento/magento2#28882]
I'm using Ubuntu 18.04 using php 7.3.15 and my Magneto 2 version is 2.3.3

Users that try to subscribe to our newsletter get the error: "Something went wrong while saving your subscription." Same error occurs for both logged in users and not logged in users.

The wierd thing is that I can add them from the Admin Panel.

I have tried disabling all modules and our custom theme but it stil gives the same error. 

I tried the "Disable Email Communications" to yes in Magento 2 ( Stores > Configuration > Advanced > System > Mail Sending Settings > Disable Email Communications). But without success.

I also used an SMTP module  to fill in: 
Authentication method : Login
SSL Type: TLS
But it didn't either work. 

How do I fix this? Thanks.

From my var/logs I have received this

`
Trace:

#1 Magento\Newsletter\Model\Subscriber\Interceptor->subscribe('niklas.johns...') called at [vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php:156] [vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php:156]

#2 Magento\Newsletter\Controller\Subscriber\NewAction->execute() called at [generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php:24]

#3 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]

#4 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:58]

#5 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]

#6 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [app/code/Aheadworks/Ca/Plugin/Controller/FrontActionPlugin.php:97]

#7 Aheadworks\Ca\Plugin\Controller\FrontActionPlugin->aroundDispatch(&Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor#00000000553be799000000004912d0c6#, &Closure#00000000553be7f7000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]

#8 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:153]

#9 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#), array(array('storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php:39]

#10 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/App/FrontController.php:159]

#11 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#, &Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor#00000000553be799000000004912d0c6#) called at [vendor/magento/framework/App/FrontController.php:98]

#12 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:58]

#13 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]

#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]

#15 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000553be5e5000000004912d0c6#, &Closure#00000000553be5cc000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]

#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]

#17 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000553be5e5000000004912d0c6#, &Closure#00000000553be5cc000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]

#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:153]

#19 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]

#20 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/App/Http.php:137]

#21 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]

#22 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]

#23 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000553be467000000004912d0c6#) called at [index.php:40]

[2020-06-24 14:15:49] main.DEBUG: cache_invalidate:  {"method":"POST","url":"root/newsletter/manage/save/","invalidateInfo":{"identifier":"notification_update_customer_session_215"}} []`

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28882-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28882-2-4-develop.instances.magento-community.engineering/admin_46c1](https://i-28882-2-4-develop.instances.magento-community.engineering/admin_46c1)
Login: `ebe9cb49` Password: `7605fb2824c5`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @NickeGilbert. Thank you for your report.
Not able to reproduce the issue as you mentioned, It should be any of your custom module issue. 
GitHub issue tracker only intended for magento core technical issues only, Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) to general discuss about this.
