### ISSUE TITLE
Not all files are pre-compiled

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#2888]
After setup:di:compile, at least, following files still are generated at run-time
- var/generation/Magento/Framework/Message/Session/Proxy.php
- var/generation/Magento/Framework/Reflection/ExtensionAttributesProcessor/Proxy.php
- var/generation/Magento/Framework/View/Layout/File/Collector/Aggregated/Proxy.php 

This gives 2 issues
- It doesn't allow to restrict web-server to write PHP files in order to provide a hight level of security on production server
- It's impossible to prepare integral package for production

Could it be fixed?

**Comment by melnikovi** [comment]
Thank you for reporting this issue. JIRA ticket created MAGETWO-47639

**Comment by astorm** [comment]
@vesan-83 Not a Magento core team member here, so I can't help you directly **but** if you could provide a few more details it might help @melnikovi and the core team track this one down.
1. Does `setup:di:compile` finish running?  Can you include its output here?
2. Is your system actually running in production mode when the classes are generated?
3. Which pages are you loading and/or commands are you running to trigger generation of those classes. (be specific, even if you think it's a general problem)

That sort of information will help the core team track down the problem.

**Comment by vesan-83** [comment]
1. Yes, see di-compile.log and di-compile.png
2. Yes, see .htaccess from pub folder
3. Home page, steps:
   - rm -rf var/cache var/di var/generation var/page_cache var/view_preprocessed pub/static/*
   - bin/magento setup:di:compile
   - bin/magento setup:static-content:deploy
   - find var/generation -type f (see files-after-compile.txt)
   - visit home page
   - find var/generation -type f (see files-after-home-page.txt, it shows 9 new files)

https://github.com/magento/magento2/files/79596/attachments.zip

**Comment by vesan-83** [comment]
The issue is fixed,
Thanks
