### ISSUE TITLE
EE - Company Address validation wrong process on region_id validation

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#28887]
### Preconditions (*)

1. Magento EE 2.3.4-p2
2. Enable B2B features and Company registrations

### Steps to reproduce (*)

1. Create a company account without set the region (as the region field is not required)

### Expected result (*)

1. The account is created

### Actual result (*)

1. This error is printed : Invalid value of "" provided for the region_id field.

### How to fix
In the file vendor/magento/module-company/Model/SaveValidator/CompanyAddress.php
We could see in the getRegions method that the regions are not retrieved if the general/region/display_all config is set as false. It's a wrong logic because this config works on displaying. So in the case of the field is not required but displayed, the check will be done.

A good workaround (before the patch) could be to replace the \Magento\Directory\Helper\Data with another helper extending it and implementing the isShowNonRequiredState method where you check the required status of the field. You could also make an around plugin of the execute method.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
Hi @alexmtch . Since we should enable  B2B features is available in Magento EE.So all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue too-
https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Comment by sdzhepa** [comment]
Hello @alexmtch 

Thank you for your contribution and collaboration!

I moved this issue into  [Magento Commerce(b2b) private repository](https://github.com/magento/partners-magento2b2b/issues) where it could be fixed and delivered by Solution Partners Contribution Program.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
