### ISSUE TITLE
Add new order atrtibute contains_bo to list orders that do or dont contain at least 1 backordered item

### ISSUE THREAD

**Issue by seansan** [magento/magento2#28886]
### Description (*)
Backorders did not work correctly in 2.3.x versions related to this issue https://github.com/magento/inventory/pull/2452. As a result backorder items (inside an order) are not distinguisable. As a further result orders that do or dont contain backorders cannot be filtered in the order grid. Orders that do and do-bot contain backorder items are treated *differently* in any ecommerce environment. Therefore it is logical to idenityf the one or the other. 

Required elements
- Add new order attribute contains_bo to no, add index
- Add order observer that filters order items, if at least 1 backordered item is found then set contains_bo to yes and break
- Add new attribute to order grid, hidden by default

### Expected behavior (*)
If an order contains at least 1 backorder item then mark the order as contains_bo = yes.

### Benefits
This is necessary as part of the complete implementation of backorders in M2. Admins can now list backorder orders and process them accordingly.

**Comment by gwharton** [comment]
There is bug where orders containing backordered items are not marked as such in the sales order screen. It should say "backordered" instead of invoiced in order screen. It is fixed in 2.4 develop. Don't know if it's possible to have it in grid. Would be a very easy mod to make.

**Comment by seansan** [comment]
Is your suggestion a new state? Or a new status?

Even then. The situation should be re evaluated every time
- on new order
- on new order then a part crest memo
- on new order and another part credit memo
With and without msi

Out main use case is as described: backorder orders follow a different
business process.

It starts with the order time knowing it is a backorder but the order
should also know
