### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#28897]
Hi, PHP 8.0 is planned for release in november 2020. It would be nice to see Magento 2.4 support it on release date.
Today the alpha1 is already available, so we can start to test it in CI tests.

https://wiki.php.net/todo/php80
https://twitter.com/official_php/status/1276198231714783232?s=20

**Comment by swathishs** [comment]
@rvitaliy : Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer to Community [Forums](https://community.magento.com/ )  or [Magento Stack Exchange](https://magento.stackexchange.com/) for technical questions, feature requests, etc.

**Comment by rvitaliy** [comment]
This is a technical problem, in November we could not use the new version of PHP because your platform will be obsolete again.

I see that time passes but your bad habits don't change. see https://github.com/magento/magento2/issues/27227
If this is your approach to troubleshooting, I can't wait to stop using Magento.

Good job, bya!

**Comment by sdzhepa** [comment]
Hello @rvitaliy 

Thank you for your question!

Let me please provide some clarification.

For now, I have not heard during internal meetings and discuss any future plans for PHP 8.0 support.

But I am sure as soon as Magneto will have any roadmap/plans for this track, it will be announced through public media channels.

This public GitHub issue tracker is aimed at issues/bugs/improvements that ready to work - something that can be taken by any community member and fixing(creating PR).

This issue report looks like an open question that should be discussed.
I mean,  it does not just task that ready to work but big and complex Story/Epic.

I would recommend to raise this topic/question and discuss in  the next channels first:
- [Community Forums](https://community.magento.com/)
- [Magento Stack Exchange](https://magento.stackexchange.com/)
- or in public [Magento Slack Channels](https://github.com/magento/magento2/wiki/Slack-Channels)


Also, I do not see any reason to keep this issue report open.
Because it will be not possible to share updates about this track in time as a comment or links here. As I mentioned such news will be announced using other channels.

**Comment by bryanveIoso** [comment]
> This is a technical problem, in November we could not use the new version of PHP because your platform will be obsolete again.
> 
> I see that time passes but your bad habits don't change. see #27227
> If this is your approach to troubleshooting, I can't wait to stop using Magento.
> 
> Good job, bya!

I think Magento LTS (OpenMage) will support PHP 8 first as it's more active. Or just use WooCommerce instead. M2 updates is kinda slow and until today PHP 7.4.4 is still not supported. O___O

**Comment by maghamed** [comment]
Hi there, let me provide additional input here. 

We are seriously considering PHP 8.0 support for Magento, and some of the features would be especially handy for Magento.
Now we are trying to fit compatibility with PHP 8.0 to our very tight product backlog :)

Currently, we support PHP 7.4 / 7.3, and taking into account that active support of 7.3 will end soon, we switched our CI/CD infrastructure towards 7.4.* 

Usually in Magento when we release a major version of the platform we keep supporting throughout all patch releases (in the scope of that major version) all the PHP versions which were actively supported at the time when Magento major release was out. This is done to prevent possible BiC for patch release upgrades. 

Also, we separate "support" and "compatibility" in terms of Magento. 
Support - is when you are able to use version-specific features, which did not exist before
Compatibility - is when we make sure that everything works as expected, but we don't use features that appeared only in this version and were previously absent. 

So, if we would find a way to introduce "Compatibility" of Magento 2.4 with PHP 8.0 - we would definitely do this. Moreover, we really encourage you to help us finding a way of doing this. Thus, all the PRs which provide this compatibility for Magento 2.4 will have a very high priority for us, and we will consider them thoroughly. 

@bryanveIoso  I did not hear anything about problems with PHP 7.4.4 - could you provide more background here?

**Comment by hostep** [comment]
@maghamed: @bryanveIoso commented on 7 July before Magento 2.4.0 was released (20 July), at that time no Magento versions were out with support for PHP 7.4 😉 

Thanks for the extra information though!

**Comment by ihor-sviziev** [comment]
I will re-open this issue, as it wasn't resolved yet, there is no php 8 support.

**Comment by ilnytskyi** [comment]
Has anyone here already tried to setup a preload feature from 7.4 ?

**Comment by ihor-sviziev** [comment]
Update: we already have [php 8.0 beta3](https://www.php.net/archive/2020.php#2020-09-03-3), would be good at least to try run magento on it.

@ilnytskyi no, I don't, but would be good to see some info about it!

**Comment by rvitaliy** [comment]
FYI: https://www.php.net/ChangeLog-8.php#8.0.0

**Comment by Alex88-hub** [comment]
I've tested PHP 8 performance on Magento 2 and compare the results with PHP 7.3. Here it is 

https://onilab.com/blog/php-7-vs-php-8/

The bottomline: the PHP 8 JIT is far from being useful in terms of improving the Magento 2 web application performance. However, it is fair to say that the feature perfectly copes with its tasks on simple code.

**Comment by rvitaliy** [comment]
@Alex88-hub 
It's not just about performance!
With PHP 8, several improvements have been introduced in the language syntax that help improve the maintainability of the code.
For more information: https://stitcher.io/blog/new-in-php-8

I think it's a real shame that we can't take advantage of them yet.

**Comment by markshust** [comment]
FYI I just published a new Docker image for PHP 8.0 at https://github.com/markshust/docker-magento/tree/master/images/php/8.0

You can use the standard docker-compose setup at https://github.com/markshust/docker-magento and install Magento as usual. After it's installed, update the `docker-compose.dev.yml` file to use the new image/tag:
`markoshust/magento-php:8.0-fpm-develop`

I hope this helps out those who want to test Magento 2 on PHP 8. It should be very easy & simple to get an instance up & running that is easily replicable to diagnose/test issues.

**Comment by sandeep-mukherjee** [comment]
https://www.mconnectmedia.com/blog/using-latest-php-version-benefits-for-magento/

**Comment by AlphaTeknovaAdmin** [comment]
I still feel like they may wait for Magento 3... Typing everything is a lot of work and the core codebase is sprawling at this point.

**Comment by EmperorKonstantin** [comment]
I still feel like they may wait for Magento 3... Typing everything is a lot of work and the core codebase is sprawling at this point.

**Comment by JosephLeedy** [comment]
@EmperorKonstantin Rector would probably help with that.

**Comment by EmperorKonstantin** [comment]
I'm not familiar with Rector, but I also hope that they use TypeScript in Magento 2 PWA Studio.

**Comment by EmperorKonstantin** [comment]
@JosephLeedy I'm not familiar with Rector, but I also hope that they use TypeScript in Magento 2 PWA Studio.

**Comment by hostep** [comment]
They are working on it on this branch should you be curious: https://github.com/magento/magento2/tree/php8-develop

**Comment by EmperorKonstantin** [comment]
@hostep You're a champ! Yay! I see types!

**Comment by ihor-sviziev** [comment]
This definitely should be open, as magento already have php 8 project.
/cc @sivaschenko

**Comment by rvitaliy** [comment]
don't forget to allow php 8.1 🙏🚀 
release date Nov 25 2021
https://wiki.php.net/todo/php81

**Comment by hostep** [comment]
Out of curiosity: Magento 2.4.4 will ship with [support for PHP 8.1](https://community.magento.com/t5/Magento-DevBlog/BREAKING-NEWS-2-4-4-beta-releases-are-coming-soon/ba-p/484310), but will it also still be compatible with older versions of PHP, like 8.0 and 7.4? Based on the commit mentioned above, I would assume it will?
