### ISSUE TITLE
Separation between logic and data to persist

### ISSUE THREAD

**Issue by miguelaeh** [magento/magento2#28899]
### Summary (*)

Hi,
I am a bitnami developer and I would like to know a bit more about the data directories. This is not actually an application issue, but a design question.
Some time ago we found some issues in our docker image because of the use of symlinks to persist some directories like the themes. Looking to the docs we didn't find references about the separation between the logic and the data of the application (please if there is a guide we would appreciate if you can share it). The data and logic separation is one of the principles to work with applications in a cloud environment. Taking a look at the official Magento container, it seems that the full application is persisted, we followed that approach to fix our issues with symlinks, but now, as we are persisting the full application, it is not possible to upgrade it just by replacing the image tag, so it is needed to exec into the container and run manual steps.
So, in short, the question is: Is it guaranteed that persisting those specific folders (var, design, etc and code) will be enough to perform the upgrades properly? Is there any kind of guide where we can read more about this? Or, are there any plans to make this application cloud-native?

### Proposed solution

If those directories are enough to perform the upgrades it would be possible to mount a volume per directory that will solve the upgrades issues, so it will be possible to upgrade Magento just changing the image tag.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @miguelaeh  
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
