### ISSUE TITLE
Reduce usage of jQuery

### ISSUE THREAD

**Issue by lumnn** [magento/magento2#28907]
### Description (*)
jQuery was a standard across many websites. It's understandable why Magento is depending on this library.

However, the jQuery "lost" it's power due to browser supporting many of the jQuery functionalities out of the box with the standard DOM API. 

Other issue, is that this large dependency on jQuery causes a difficulties with upgrading jQuery. Magento 2.4 uses a version (1.12.4) which was released on 20th May 2016 (4 years ago). I'm aware of the effort to update jQuery to recent version, but this issue is not about it.

According to [browser support documentation page](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements_browsers.html) the officially supported browsers are quite new, which in my opinion shouldn't cause many issues with writing new code or updating existing one without need of jQuery.

This issue is mostly created to raise an awareness of unneeded jQuery dependency in some modules. Perhaps maybe changing contribution requirements for new code to avoid jQuery wherever it is possible.

Example of files which could get easily upgraded:

- `app/code/Magento/Ui/view/base/web/js/block-loader.js`
- `lib/web/mage/common.js`

### Expected behavior (*)
Exactly same, but using much less jQuery API in favour of default DOM API.

### Benefits
Short term I can imagine performance optimizations due to less code involved to perform needed actions.

Long term, I believe Magento may get to a point where jQuery will no longer be a dependency. At the moment, it doesn't seem to be possible without making a major release or changing direction towards PWA solutions (which at the moment seem to be far from production ready).

Lastly, I believe nowadays no web developer learns jQuery because he wants to. More likely jQuery is learned because of projects started in the past that are still supported. With reducing usage of jQuery Magento may also reduce a learning curve for newcommers.

### Purpose of this issue

I created this issue mostly to:

- Ask whether maintainers wants less jQuery usage?
- Update documentation to guide developers to avoid jQuery API
- Find and recommend a way to create a reusable replacement solution for jQuery widgets
- Track a progress of this initiative

I've searched for similar issues or PR-s, however I didn't find much apart from a request to upgrade jQuery to latest version.

**Comment by swathishs** [comment]
@lumnn : Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer to Community Forums or Magento Stack Exchange for technical questions, feature requests, etc.

**Comment by hostep** [comment]
@swathishs: the correct links for feature requests and architectural decisions should be https://github.com/magento/community-features/issues & https://github.com/magento/architecture/pulls.
I'm pretty sure these type of discussions will not be monitored by Magento core devs on the community forums or on stack exchange (but I might be wrong?)
