### ISSUE TITLE
Reset Password Throw 404 (cms_noroute_index)

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#28909]
### Preconditions (*)

* Magento2.3.5 instance.

### Steps to reproduce (*)

* Create a Customer login and logout.
* At login page  Click Forgot Your Password will take to .../customer/account/forgotpassword/
* Fill required details click Reset My Password. Will take to  .../customer/account/forgotpasswordpost/

### Expected result (*)
Success message !

### Actual result (*)
 Gives 404.

Loading URL **/customer/account/forgotpasswordpost/** directly in the browser and Printing `print_r($request->getFullActionName());die;` Gives: `cms_noroute_index ` 

At **/customer/account/forgotpassword/** Gives ActionName: `customer_account_forgotpassword `

**Comment by Serializator** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Serializator, here is your [Magento instance](https://i-28909-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28909-2-4-develop.instances.magento-community.engineering/admin_c6cf](https://i-28909-2-4-develop.instances.magento-community.engineering/admin_c6cf)
Login: `aba47f49` Password: `b8d729bb74d5`
Instance will be terminated in up to 3 hours.

**Comment by Serializator** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @Serializator. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Serializator, here is your [Magento instance](https://i-28909-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28909-2-3-5-p1.instances.magento-community.engineering/admin_4533](https://i-28909-2-3-5-p1.instances.magento-community.engineering/admin_4533)
Login: `a4c7fecf` Password: `e4fb55c47e14`
Instance will be terminated in up to 3 hours.

**Comment by lano-vargas** [comment]
Thank you  @Serializator! @magento-engcom-team  Here is the result
![Screen Shot 2020-06-27 at 12 51 16](https://user-images.githubusercontent.com/3495481/85921558-f424f000-b874-11ea-8a58-f304a92a8687.png)

**Comment by Serializator** [comment]
Hi @lano-vargas, weirdly enough I wasn't able to reproduce the issue on either the 2.4-develop nor the 2.3.5-p1 instance. What exact steps do you take to reproduce this? 

**What I tried**
- Create an account like you described in your first step to reproduce the issue
- Logout
- Navigate to the "Forgot Your Password" page
- Enter the e-mail I used and captcha
    - Submitted the form by clicking on "Reset My Password"
    - Submitted the form by pressing enter

**Comment by lano-vargas** [comment]
@Serializator  Then your step should have taken you to https://i-28909-2-3-5-p1.instances.magento-community.engineering/customer/account/forgotpasswordpost/  which gives 404.

**Comment by lano-vargas** [comment]
hmmm I've just double check on my localhost instance 2.2.2 when I load the post url directly in the url ../customer/account/forgotpasswordpost/ it redirects to customer/account/forgotpassword/  as it's empty but on my 2.3.5 it just give a 404 instead of redirecting, but is this another should it redirect ?

**Comment by Serializator** [comment]
@lano-vargas, I think this is because `Magento\Customer\Controller\Account\ForgotPasswordPost` implements `Magento\Framework\App\Action\HttpPostActionInterface` and not `Magento\Framework\App\Action\HttpGetActionInterface` which is the request method your browser uses when navigating to a page.

`Magento\Framework\App\Action\HttpPostActionInterface` was (it seems) introduced in Magento 2.3 through the commit below. I don't know if this has anything to do with the cause of your issue as I still haven't been able to reproduce your issue.

https://github.com/magento/magento2/commit/df2784b6dec6fe841c72223705974231c246a465

_I haven't registered as many accounts **ever** as I have today 😂_

**Comment by lano-vargas** [comment]
@Serializator I think  I've got a little bit confused with the 404 on the 2.3 in my case and I may not have explained the issue properly😅 . And Thanks for the info good to know. I am closing this as it's the expected behaviour. 👍

Thank you!
