### ISSUE TITLE
 Integral support for EDI messages PRICAT (Price / Sales Catalogue)

### ISSUE THREAD

**Issue by shirtsofholl** [magento/magento2#2890]
Would it be an idea to support  EDI messages PRICAT (Price / Sales Catalogue) from the core? or EANCOM?

To choose and order assortments, the retailer normally receives master data about the
entire assortment from the supplier detailed in the EDI messages PRICAT (Price / Sales
Catalogue). 

This would allow for a far better vertical integration in fashion and set the standard for all other platforms

References: https://www.gs1.nl/sites/default/files/Mode_CFB_BusinessModelsForTheFashionSector.pdf
http://www.gs1.org/docs/EDI/eancom/2012/ean02s3/part2/pricat/toc.htm
http://www.gs1.org/eancom/syntax-4

**Comment by choukalos** [comment]
Hi @shirtsofholl - At this time supporting EDI in core is not on our Radar.  Our strategy is first to service layer Magento 2 ( ie make all the functionality in Magento essentially an API and use it internally - is coverage ), Support Mobile APIs, and 3rd making it as client friendly as possible.  The majority of our customer base prefers REST style web APIs with a small but vocal hold out using SOAP.  I'd like to introduce EDI connectors to Magento but believe at this time they're more appropriate as extensions.

It should be relatively straight forward to create the various EDI services and leverage internal Magento services to provide the data that's being transformed and shared via EDI.  That would be suitable for a low volume data integration ( M2 apis run about 0.5 to 1 second response time ) and should be pretty easy to maintain.  I think for an EDI adapter to be adopted by large businesses though it would need to support SFTP based file transfer and import/export as usually the data volume is quite large.  That would involve filling in some gaps in our import/export feature set plus plugging into that framework to address.

I'd be interested in learning more about your business and your usage of EDI.  If you have some time please email me (check my profile) with some date / times (I'm in the US on CST) you'd be free to chat and I'll setup a meeting.

-Chuck

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Integral-support-for-EDI-messages-PRICAT-Price-Sales-Catalogue/idi-p/44770).
