### ISSUE TITLE
Sitemap in robots.txt not store specific

### ISSUE THREAD

**Issue by medialoungeml** [magento/magento2#28901]
### Preconditions (*)

1. Magento CE 2.3.3
Magento 2.4 and 2.3.5-p1

### Steps to reproduce (*)

1. Create Second Web Site, Store and Store View
2. Go to Stores -> Configuration -> General -> Web 
3. Set "Add Store Code to Urls" = "Yes" -> Save
4. Go to Stores -> Configuration -> Catalog -> XML Sitemap
5. Expand "Generation Settings" section
6. Set "Enabled" = "Yes"
7. Expand "Search Engine Submission Settings" section
8. Set "Enable Submission to Robots.txt" = "Yes" -> Save
9. Run `php bin/magento cron:run` and `php bin/magento c:f`
10. Go to Marketing -> Site Map
11. Create 2 Site Maps (one for Default site and another one for second with different "Filename" 
![Screenshot_14](https://user-images.githubusercontent.com/60198022/86654322-87d18b80-bfee-11ea-8c38-3b9f8f91feff.png)
12. Save & Generate
13. Run `php bin/magento cron:run` and `php bin/magento c:f`
14. Go to store view and open Default store (http://youredomain.local/robots.txt)
15. Then in new tab open Second store (http://youredomain.local/de/robots.txt)

### Expected result (*)

Site Maps should be different (because of different Filename)
 The Sitemap: property should be retrieved within the context of the store

### Actual result (*)

Site Maps are the same
![Screenshot_13](https://user-images.githubusercontent.com/60198022/86649591-91f18b00-bfea-11ea-8f4b-0dfd12aedff5.png)

### Proposed Solution
The Sitemap value is retrieved in Magento\Sitemap\Block\Robots::_toHtml() and within this function the \Magento\Store\Model\StoreManagerInterface::getDefaultStoreView() is called to get the list of store ids to generate the sitemap for, this results in the value for the default store only ever being returned.
[Here](https://github.com/magento/magento2/issues/28901#issuecomment-650195689) is comment with posible fix the issue

**Note** In Content -> Design -> Configuration you can configure the file settings robots.txt 

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alex-james** [comment]
For anyone who encounters this issue, the workaround I have used is here: https://github.com/cogensoft-uk/magento-siite-specific-sitemap/tree/master/Cogensoft/Sitemap

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35674).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35674` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35674).

**Comment by slavvka** [comment]
Hi @medialoungeml. Thank you for your report. 
The issue has been fixed in magento/magento2#29331 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [b1054ad172e5537b7ef8fbca6595de2b7de62ee2](https://github.com/magento/magento2/commit/b1054ad172e5537b7ef8fbca6595de2b7de62ee2)
 - [2020e98ae2e4303f8f95c9f2206faf3f5e16997b](https://github.com/magento/magento2/commit/2020e98ae2e4303f8f95c9f2206faf3f5e16997b)
 - [1563ef2855ed6625d01f7288ac27b0eff9215a7a](https://github.com/magento/magento2/commit/1563ef2855ed6625d01f7288ac27b0eff9215a7a)

The fix will be available with the upcoming 2.4.1 release.

**Comment by rl-akjaer** [comment]
Why was the label for "Reproduced on 2.3.5p2" tag removed? It's certainly a reproducible bug in the 2.3 branch.

Will this be yet another bug that's not going to be fixed in 2.3.6...?
