### ISSUE TITLE
Add whitelist field to Magento_CSP module's backend configuration.

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#28914]
### Description (*)

If you want to add a domain to the CSP whitelist, then you have to program a custom module, even though there is a CSP module which is useless at the moment, because it does not provide a whitelist field in the backend. There should be a whitelist field!

### Expected behavior (*)

Add a whitelist field to allow adding domains to the CSP whitelist.

### Benefits

The Magento_CSP module becomes actually useful and you don't have to code a custom module.

### Additional information

Enterprise 2.3.5-p1
Linux Server

**Comment by ihor-sviziev** [comment]
Duplicates https://github.com/magento/magento2/issues/28363

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
This issue duplicates https://github.com/magento/magento2/issues/28363, so I'm closing this issue.
