### ISSUE TITLE
Change Magentp Backorder Threshold when approaching 0

### ISSUE THREAD

**Issue by seansan** [magento/magento2#28918]
### Description (*)
Assume 2 products
- Product A: MSI stock: 2 & BO Min Qty THreshold = -1 (thus salable qty = 3)
- Product B: MSI stock: 2 & BO Min Qty THreshold = 0 (thus salable qty = 2)

If we now buy 3 product A then product A goes out of stock

If we now buy 2 product B then product B _does not!_ goes out of stock

### Expected behavior (*)
There should be some way that product B goes out of stock in the case above. We cannot sell infinity.

- Either change the setting that if BO Min Qty (Threshold) = 0 is respected as zero and no longer means infinity

- Or add a new config flag, Zero BO Min Qty (Threshold) means out of stock

### Benefits
It creates an impossible situation, this should be fixed for Backorders to fully function.

### Additional information
It is clear how to resolve this manually on a 1 product basis

Not if you manage 100.00+ items

It is a strange design concept. Zero is zero when it reaches zero by
orders. Not if you set it yourself. Also the whole in stock and out of
stock flags are rather obsolete since the new definition and introduction
of salable qty

There should be a different app at to set backorders to unlimited. Think :
enter a dash. Or enter null (empty). Or create a new setting.

**Comment by seansan** [comment]
Issue format is valid

**Comment by gwharton** [comment]
Then turn backorders off for product B and out will go out of stock when 2 are sold. Setting threshold to zero enables unlimited backorders for product B

**Comment by gwharton** [comment]
Product A goes out of stock because you have limited it to sell only 1 backordered item, whereas product B will never go out of stock as threshold is zero.

**Comment by seansan** [comment]
It is clear how to resolve this manually on a 1 product basis

Not if you manage 100.00+ items

It is a strange design concept. Zero is zero when it reaches zero by
orders. Not if you set it yourself. Also the whole in stock and out of
stock flags are rather obsolete since the new definition and introduction
of salable qty

There should be a different app at to set backorders to unlimited. Think :
enter a dash. Or enter null (empty). Or create a new setting.

**Comment by engcom-Lima** [comment]
Hello @seansan, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

**Comment by seansan** [comment]
This feels like M1 again ... everybody off-managing tickets ... 

THe request is for Magento and every type of MAgento
