### ISSUE TITLE
Cannot open minicart on iPad

### ISSUE THREAD

**Issue by aqdennis** [magento/magento2#28929]
### Preconditions (*)

1. Magento 2.3.2
2. iPad with Opera or Firefox

### Steps to reproduce (*)

1. Add product to cart -> minicart icon shows amount of products
2. Click on minicart to open it

### Expected result (*)

1. Would expect the minicart to open and show summary of products and buttons to go to cart or checkout

### Actual result (*)

1. Nothing happens. Minicart doesn't open. Customers can't go to checkout.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

There is a workaround for the user to manually type the url "<webshop>/checkout " but it cannot be expected from users to know that..... 

### Remark (*)
1. It has been reported by several of our customers. However, I do now own an iPad so I cannot check it myself.
2. We use custom theme, but I would expect this to be more a problem on the Ajax side then our theme

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by aqdennis** [comment]
Is there any conclusion or progress on this?

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @aqdennis. Thank you for your report.
Not able to replicate issue on latest magento 2.4-develop instance.
![image](https://user-images.githubusercontent.com/46617848/101619538-6d865880-3a39-11eb-87ef-8bc2068a5259.png)
Feel free to reopen once you confirm the issue reproduce on 2.4-develop instance
