### ISSUE TITLE
Apply shopping cart rule to a single bundle item

### ISSUE THREAD

**Issue by MilanFrajt** [magento/magento2#28921]
### Preconditions (*)
Magento ver. 2.3.5-p1

### Steps to reproduce (*)
1. Create a bundle product with two option each contain two product in it
2. Create one option as main as the title with two simple product (a&b) - (Dropdown)
3. Create the second option as a sub as the title with two simple product(c&d)- (Checkbox)
4. Create a shopping cart rule 
5. Select a "percent of product price discount" 
6. Add 10 % to the discount amount 
7. We should add the main option two product in the rule like( SKU is one of (a&b)
8. Apply the rule 
9. Go to the frontend
10. Select one SKU from the dropdown of the main simple product and checkbox one sub simple product 
11. Add to cart
12. Go to cart page
13. Check the discount is applied total of two product

### Expected result (*)
10% discount is applied ONLY on BUNDLE child product SKU001 (this behavior worked faultless on Magento 1.8.X)
The discount should be applied only for the main simple product 
### Actual result (*)
10% discount is applied on BUNDLE parent product, thus both of simple products are discounted...
![bundle_issue](https://user-images.githubusercontent.com/6410007/86008556-3c7d1300-ba19-11ea-94cc-ec47da57f30b.png)

Additional information
more detailed steps and screens #28921 ([Comment1](https://github.com/magento/magento2/issues/28921#issuecomment-651136449)) ([comment 2](https://github.com/magento/magento2/issues/28921#issuecomment-651167895))

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28921-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28921-2-4-develop.instances.magento-community.engineering/admin_9c53](https://i-28921-2-4-develop.instances.magento-community.engineering/admin_9c53)
Login: `76702ff3` Password: `9a2130d75bea`
Instance will be terminated in up to 3 hours.

**Comment by MilanFrajt** [comment]
Tested on https://i-28921-2-4-develop.instances.magento-community.engineering/, working exactly same way as described in issue: 

Created BUNDLE product ID: 1201 with 4 simples under 2 option_groups https://i-28921-2-4-develop.instances.magento-community.engineering/test-bundle.html
MainOption (SKUs: product_dynamic_6, product_dynamic_8)
SubOption (SKUs: product_dynamic_1, product_dynamic_2)
![TEST_BUNDLE_Google Chrome_2020-06-29_15-38-43](https://user-images.githubusercontent.com/6410007/86012838-bf549c80-ba1e-11ea-98f8-9f5f546ea30a.png)

Rule ID: 41 BundeTestRule
Conditions: BLANK
Actions: 10% of product price discount to cart items matching the following conditions: SKU  is one of  product_dynamic_6,product_dynamic_8
![BundeTestRule_Google Chrome_2020-06-29_15-43-24](https://user-images.githubusercontent.com/6410007/86013626-a39dc600-ba1f-11ea-93d5-d6104a433aa2.png)

Added to the sopping cart BUNDLE consists from:
MainOption1 x Simple Product 6 $418.53
SubOption1 x Simple Product 1 $100.00

**Expected result: 10% discount on  Simple Product 6 = $41.85**

**Actual result: 10% discount on BOTH simple products = $51.85**

![ShoppingCartGoogle Chrome_2020-06-29_15-51-49](https://user-images.githubusercontent.com/6410007/86014376-89b0b300-ba20-11ea-980c-b11cc74116ab.png)

**Comment by swathishs** [comment]
Issue is reproducible in Magento 2.4 develop instance

Please find the attachment below:

1.  Two option for bundle product:
    (Main & Sub option)
![image](https://user-images.githubusercontent.com/58288685/86018113-829a9c80-ba42-11ea-924d-1022c7a17a98.png)

2. Rule ( Applicable only for the main simple product):
![image](https://user-images.githubusercontent.com/58288685/86018176-980fc680-ba42-11ea-831a-02489ecb7a7f.png)

3. Cart page:
![image](https://user-images.githubusercontent.com/58288685/86018257-b4136800-ba42-11ea-94f0-bc9ed7482de3.png)

Excepted Result :
Subtotal =$ 200
Discount= $10
Shipp = $5
Total=$195

Actual:
![image](https://user-images.githubusercontent.com/58288685/86018559-27b57500-ba43-11ea-9d1e-c87ecb5b7f14.png)

**Comment by swathishs** [comment]
Issue is reproducible in Magento 2.4 develop instance

Please find the attachment below:

Two option for bundle product:
(Main & Sub option)
![image](https://user-images.githubusercontent.com/58288685/86019806-b37bd100-ba44-11ea-9cc9-12a5243f6390.png)

Rule ( Applicable only for the main simple product):
![image](https://user-images.githubusercontent.com/58288685/86019861-c8586480-ba44-11ea-9d3e-a3b20e64e306.png)

Cart page:
![image](https://user-images.githubusercontent.com/58288685/86020034-05bcf200-ba45-11ea-8c6b-596a4bcd7477.png)

**Excepted Result** :
Subtotal =$ 200
Discount= $10
Shipp = $5
Total=$195

**Actual:**
![image](https://user-images.githubusercontent.com/58288685/86020105-1a998580-ba45-11ea-9a57-c9ebcb014a7a.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35548` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zhartaunik** [comment]
To proceed issue fix I need to clarify several tips with the architect. As the fix I suppose is expected here implies a total change of quote_item calculation of bundle product. Which is in my opinion works with bugs.

Have a look at \Magento\GraphQl\Sales\RetrieveOrdersWithBundleProductByOrderNumberTest::testGetCustomerOrderBundleProductWithTaxesAndDiscounts

This test creates following fixture:
     * @magentoApiDataFixture Magento/Bundle/_files/bundle_product_two_dropdown_options.php

If you have a look at this fixture you may see following:
Parent product (Bundle) has price: $10.00
It's children have prices: $1.00 and $2.00

If we add to cart this product we may notice in quote table following state:

Item name | qty | price | raw_total
---|---|---|---
Bundle | 4 | 15 | 60
Simple1 | 1 | null | null
Simple2 | 2 | null | null

In my opinion, the desired result should be the following:

Item name | qty | price | raw_total
---|---|---|---
Bundle | 4 | 10 | 4 items * $10.00 = 40
Simple1 | 1 | 1 | 1 item * $1.00 * 4 parent qty = 4
Simple2 | 2 | 2 | 2 items * $2.00 * 4 parent qty = 16

And when we create an order we should use the sum of all raw_totals (parent and its children). But it smells like total Bundle product refactoring.

**Comment by bubasuma** [comment]
@zhartaunik this issue was fixed in 71bb134ba3cd0b45da7d7e7c857ae2cdd412b05b

**Comment by bubasuma** [comment]
All products
<img width="1832" alt="Screen Shot 2020-07-29 at 10 27 54 AM" src="https://user-images.githubusercontent.com/8973208/88819870-3304d900-d186-11ea-991a-a927dc3bcb53.png">

Bundle product
<img width="1836" alt="Screen Shot 2020-07-29 at 10 21 08 AM" src="https://user-images.githubusercontent.com/8973208/88819898-3bf5aa80-d186-11ea-89b8-aca51ebfd483.png">

Cart Price Rule
<img width="1814" alt="Screen Shot 2020-07-29 at 10 29 55 AM" src="https://user-images.githubusercontent.com/8973208/88820087-78c1a180-d186-11ea-9447-59b8febe5dc7.png">

Shopping cart
<img width="1920" alt="Screen Shot 2020-07-29 at 10 25 54 AM" src="https://user-images.githubusercontent.com/8973208/88820153-8d9e3500-d186-11ea-8d72-3abbd989a25c.png">

Discount as expected: -1.00 NOT -1.50

**Comment by zhartaunik** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @zhartaunik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @zhartaunik, here is your [Magento instance](https://i-28921-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28921-2-4-develop.instances.magento-community.engineering/admin_2022](https://i-28921-2-4-develop.instances.magento-community.engineering/admin_2022)
Login: `19e1ffec` Password: `b2a0d4094a31`
Instance will be terminated in up to 3 hours.

**Comment by zhartaunik** [comment]
@bubasuma thanks, I can confirm that the issue does not occur anymore. I wrongly updated my fork and worked with the wrong version.
I prepared MFTF test for this scenario, should we merge it or just remove?

**Comment by magento-engcom-team** [comment]
Hi @MilanFrajt. Thank you for your report. 
The issue has been fixed in magento/magento2#29348 by @zhartaunik in 2.4-develop branch
Related commit(s):
 - [e6aca3b93d6b56357f70b92c47d521acc88102f5](https://github.com/magento/magento2/commit/e6aca3b93d6b56357f70b92c47d521acc88102f5)
 - [7abc82f5a2e1e76d6fd4155daedd96050fbb68c2](https://github.com/magento/magento2/commit/7abc82f5a2e1e76d6fd4155daedd96050fbb68c2)

The fix will be available with the upcoming 2.4.2 release.

**Comment by poojapawar12** [comment]
I am getting the same issue on amgenot 2.4.6 p2  cloud instance

**Comment by nicolaspernot** [comment]
@magento give me 2.4-develop instance
