### ISSUE TITLE
Elastic Search Suggestion Score Sorting inverted 2.3.5-p1

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#28933]
### Preconditions (*)
1. magento 2.3.5-p1
2. elasticsearch6 as searchadapter
3. enabled suggestions to be displayed on search site

### Steps to reproduce (*)
1. search for like "bambuss" instead of "bambus"
2. Debug the Result from ES in Class

```Magento\Elasticsearch\Model\DataProvider\Base\Suggestions```

at method 
```private function getSuggestions(QueryInterface $query)```

### Expected result (*)
1. krsort is used so that Results with high scores are first
![grafik](https://user-images.githubusercontent.com/48922246/86113478-989f7000-bac9-11ea-8c5b-63881e4966a9.png)

2. closer debug -> after krsort and before array_slice (sorry no idea how to toggle such big images here)
![grafik](https://user-images.githubusercontent.com/48922246/86113626-cd132c00-bac9-11ea-98df-d039eed406ce.png)

### Actual result (*)
1. ksort is used so that weak scores come fist
![grafik](https://user-images.githubusercontent.com/48922246/86113170-321a5200-bac9-11ea-9fbd-2c42449bf3f2.png)

2. closer debug -> after ksort and before array_slice (sorry no idea how to toggle such big images here)
![grafik](https://user-images.githubusercontent.com/48922246/86113081-10b96600-bac9-11ea-9bdb-abd2a73a6d2a.png)

- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

### Fix
 use krsort instead of ksort

**Comment by rparsi-boxycharm** [comment]
The sorting can be done in elasticsearch via `"sort"` included in the request along side `"query"`, ie
```
GET /bank/_search
{
  "query": { "match_all": {} },
  "sort": [
    { "account_number": "asc" }
  ]
}
```

There's no point in doing the sorting in php.

**Comment by stkrelax** [comment]
no interest anymore
