### ISSUE TITLE
A performance issue: setup:di:compile-multi-tenant takes 11 munites to finish

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2893]
- https://community.magento.com/t5/Admin-Configuration-Questions/magento-setup-di-compile-take-too-long-to-compile/m-p/25505
- https://mage2.pro/t/190

**Comment by joanhe** [comment]
@mage2pro Thank you for reporting this issue. After careful evaluation of Multi-tenant compiler, Magento decided to remove Multi-tenant compiler in any post 2.0.x releases. I will close this issue.
