### ISSUE TITLE
NOT READY Extend an existing GraphQL schema not working for product dropdown type attributes

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#28937]
### Summary (*)

By using this documentation I have extended product attributes value in **products** query. but it's not working if I change "Use in Layered Navigation "  value to "Filterable (with results)"

But getting **"message": "Field \"color\" of type \"Int\" must not have a sub selection.",** error

### Examples (*)

My Code for schema.graphqls file is as below
interface ProductInterface {
    color: AttributeValue
        @resolver(class: "\\Vodacom\\CatalogGraphql\\Model\\Resolver\\ProductLabelResolver")
}
type AttributeValue {
    label: String @doc(description: "Attribute label.")
    value: String @doc(description: "Value for attribute")
}

### Proposed solution

It should return data like "color": {
                        "label": "Yellow",
                        "value": "5433"
                    },

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rani-webkul** [comment]
@ihor-sviziev could you please help me to fix this issue?

**Comment by ihor-sviziev** [comment]
Hi @rani-webkul,
Sorry, but I don't have expertise in GraphQL, someone else could help you

**Comment by engcom-Hotel** [comment]
Hello @rani-priya,

We request you to please try to reproduce the issue in Magento 2.4-develop branch and let us know if it is still reproducible for you.

We also need more information if it is reproducible like below:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @rani-priya,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by konstantins90** [comment]
@rani-priya Hello, did you find a solution for your problem? I have the same problem, can you help me?
thanks
