### ISSUE TITLE
FPT not applied on configurable products (children) in checkout summary

### ISSUE THREAD

**Issue by rpajalunga** [magento/magento2#28931]
### Preconditions (*)

1. Fresh installation of Magento 2.3.5-p1
2. Updated installation up to 2.3.5-p1
3. also repro on `2.4-develop`

### Steps to reproduce (*)

1. Enable FPT - Stores - sales -tax- Enable fixed product tax
2. Create a new attribute (code: dynamic_weight_rate / type: fixed product tax)
3. Create a new "attribute set" and assign an attribute to it
4. Assign attribute set to a configurable product (previously created or a new one)
5. Update FPT information on each simple product related to configurable one
6. On frontend side login and make an order using configurable products
7. See FPT row on summary order

### Expected result (*)

1. FPT should fullfilled as sum of each assigned FPT to items

### Actual result (*)

1. FPT result as sum of value defined in parent product (configurable) only

### Additional Information
- Issue was confirmed on the lates `2.4-develop` steps and details here https://github.com/magento/magento2/issues/28931#issuecomment-651902582 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Additional information**:
more detailed steps and screens #28931 ([comment](https://github.com/magento/magento2/issues/28931#issuecomment-651902582))

**Comment by rpajalunga** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rpajalunga. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rpajalunga, here is your [Magento instance](https://i-28931-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28931-2-4-develop.instances.magento-community.engineering/admin_7a9a](https://i-28931-2-4-develop.instances.magento-community.engineering/admin_7a9a)
Login: `765ee2ae` Password: `46a87cec1194`
Instance will be terminated in up to 3 hours.

**Comment by rpajalunga** [comment]
I was able to reproduce the issue on a vanilla Magento instance;

FPT Sum
Expected (0.10+0.20+0.30+0.40)=1.00
Real 0.40 (0.10 per item i suppose)

![20200630-Frontend-Cart](https://user-images.githubusercontent.com/58708812/86114817-61ca5980-bacb-11ea-8271-a232fdc89430.png)
![20200630-Product-Child-FPT-100gr](https://user-images.githubusercontent.com/58708812/86114819-6262f000-bacb-11ea-9be0-cf6d42b00fa1.png)
![20200630-Product-Child-FPT-150gr](https://user-images.githubusercontent.com/58708812/86114823-62fb8680-bacb-11ea-992e-5eb177fbc3e2.png)
![20200630-Product-Child-FPT-200gr](https://user-images.githubusercontent.com/58708812/86114826-62fb8680-bacb-11ea-8979-33666cdfa9e5.png)
![20200630-Product-Child-FPT-250gr](https://user-images.githubusercontent.com/58708812/86114827-63941d00-bacb-11ea-812e-27449ff07623.png)
![20200630-Product-Parent](https://user-images.githubusercontent.com/58708812/86114830-63941d00-bacb-11ea-9d5f-8985ac82b9af.png)
![20200630-Product-Parent-Setup](https://user-images.githubusercontent.com/58708812/86114832-642cb380-bacb-11ea-9ef6-c61e1ffd7cf0.png)

**Comment by rpajalunga** [comment]
@magento Reproduced in 2.4.x

**Comment by rpajalunga** [comment]
@magento I am working on this

**Comment by rpajalunga** [comment]
@magento add to contributors team

**Comment by rpajalunga** [comment]
I'm unable to assign labels... could i use bot to assign them?

**Comment by swathishs** [comment]
@rpajalunga : Tested the issue in 2.4 develop instance.
Testproduct: FPT-0.5
![image](https://user-images.githubusercontent.com/58288685/86150420-00ca7200-bb1b-11ea-9f55-9908b727f4e9.png)

1. Test product-test1 : FPT-0.10
![image](https://user-images.githubusercontent.com/58288685/86150098-8863b100-bb1a-11ea-8180-21e2ff429777.png)

2. Testproduct-test2: FPT-0.20
![image](https://user-images.githubusercontent.com/58288685/86150305-dd9fc280-bb1a-11ea-9a51-bc1bd3f73f31.png)

3. Testproduct-test3: FPT-0.30
![image](https://user-images.githubusercontent.com/58288685/86150360-ee503880-bb1a-11ea-9899-9cd2920cf063.png)

Test product( Confi product) - FPT-0.5
Test product-test1 : - FPT-0.10
Testproduct-test2:- FPT-0.20
Testproduct-test3:- FPT-0.30

But FPT is calcualted from main Test product (0.5+0.5+0.5 = 1.5)

**Cart page**:
![image](https://user-images.githubusercontent.com/58288685/86150543-2b1c2f80-bb1b-11ea-8535-fc77fbce1d9a.png)

If I am not setting FPT for the Test product
![image](https://user-images.githubusercontent.com/58288685/86151239-1a1fee00-bb1c-11ea-9c86-aeb978e4249a.png)

Then FPT is not displayed in  cart page:
![image](https://user-images.githubusercontent.com/58288685/86151239-1a1fee00-bb1c-11ea-9c86-aeb978e4249a.png)

Conclusion: FPT not applied to configurable products (children)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35572` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madhurajawat** [comment]
@magento add to contributors team

**Comment by madhurajawat** [comment]
@magento add to contributors team

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by Echron** [comment]
@rpajalunga Did you ever find a solution for this?

**Comment by Quentin-Sch** [comment]
Hello, it's a very important bug. Why is this archived ????

**Comment by Amadeco** [comment]
This issue is still reproducible on Magento 2.4.4. This issues must be reactivated !
