### ISSUE TITLE
ZMW Currency option

### ISSUE THREAD

**Issue by nitininerun** [magento/magento2#28945]
### Description (*)
We are using Magento 2.3.4 version. While configuring currency for Zambia its picks up ZMK (1968-2012). 

### Expected behavior (*)
Magento can send ZMW instead of ZMK to payment gateway.
### Benefits
However in order to integrate the payment gateway, we need ZMW as an additional drop-down, so magento can send ZMW instead of ZMK to payment gateway.

### Additional information
![Currency Dropdown](https://user-images.githubusercontent.com/67676400/86208452-2f356500-bb8e-11ea-92ff-6fb46caf72ba.png)
![Currency Picked](https://user-images.githubusercontent.com/67676400/86208453-30ff2880-bb8e-11ea-94a4-5ff2c649fa42.png)

**Comment by engcom-Lima** [comment]
Hello @nitininerun, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.
