### ISSUE TITLE
default country in cart sidebar issue

### ISSUE THREAD

**Issue by gonorovsky** [magento/magento2#2894]
In admin configuration the default country is set for Ukraine (same as origin country). But when you open the cart (http://bezkryshi.com/checkout/cart/) it start to evaluate shipping and taxes for US ( but this country is disabled in admin).

**Comment by ishakhsuvarov** [comment]
@gonorovsky Thank you for reporting this issue. We have created an internal ticket `MAGETWO-47653` to fix the problem.

**Comment by gonorovsky** [comment]
Is there any temporary solution (for ex: disable shippment calculation in
cart)?

**Comment by gonorovsky** [comment]
This bug appeared on table rates shipping method.

**Comment by ishakhsuvarov** [comment]
@gonorovsky Checkout and Cart pages use `Default Country` setting from **System > Configuration > Sales (Tax section) > Default Tax Destination Calculation > Default Country**.
Please try this solution and let us know if it helped.

**Comment by gonorovsky** [comment]
Yes it helped. I ve already found this. Thank you.

Пн, 25 січ. 2016 16:32 Ievgen Shakhsuvarov notifications@github.com пише:

> @gonorovsky https://github.com/gonorovsky Checkout and Cart pages use Default
> Country setting from _System > Configuration > Sales (Tax section) >
> Default Tax Destination Calculation > Default Country_.
> Please try this solution and let us know if it helped.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/2894#issuecomment-174511201.
> 
> ## 
> 
> Regards,
> Volodymyr Gonorovskyi

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by ishakhsuvarov** [comment]
@gonorovsky Closing this issue for now. Please reopen if there are any additional questions.

**Comment by pradeepnew** [comment]
After adding default country from System > Configuration > Sales (Tax section) > Default Tax Destination Calculation > Default Country

In checkout page it is showing error "Please enter zip code".
if I enter zip code with default country (System > Configuration > Sales (Tax section) > Default Tax Destination Calculation > Default Country), It is showing this zip code.
Please check and revert
