### ISSUE TITLE
Payment Transaction Failed Notification - Spam?

### ISSUE THREAD

**Issue by SmooreMB** [magento/magento2#28940]
### Preconditions (*)

1. Magento 2.3
2. 

### Steps to reproduce (*)

1. Received email notification of customer payment transactions failing 
2. Google mail suspects it may be spam
3. 

### Expected result (*)

1. Not sure if notifications are valid, or if customers are receiving errors during transactions

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/55757553/86164293-87615e00-badf-11ea-8a95-f345972a0226.png)
2. I'm not sure if notifications are valid, or if customers are receiving errors during transactions. Is this normal?

**Comment by gwharton** [comment]
Probably more likely due to bad from address, bad reply to address, bad dkim signature, bad SPF setup.

**Comment by krishprakash** [comment]
Hi @SmooreMB. Not able to replicate the issue as you mentioned 
It maybe due to bad from address, bad reply to address, bad dkim signature, bad SPF setup as answered by @gwharton 
Thanks!!
