### ISSUE TITLE
Multi-store GraphQL functionality doesn't follow Magento storefront logic

### ISSUE THREAD

**Issue by isydorenko** [magento/magento2#28953]
### Preconditions (*)

1. Magento 2.3.5 without the sample date is installed.
2. Single website with a single store and two store views is configured.

### Steps to reproduce (*)

1. Set the first store view code to the "Store" request header.
2. Initialize an empty cart via createEmptyCart mutation.
3. Add a simple product to cart via addSimpleProductsToCart mutation 
4. Set the second store view code to the "Store" request header.
5. Get cart via cart query.

### Expected result (*)

I would expect to have a mutation for changing `quote`.`store_id` value in DB. Another option - follow Magento storefront logic and change `quote`.`store_id` automatically if we pass a new store view code by "Store" header, but I do not think it is a good idea to update DB via GraphQL query.

### Actual result (*)

Currently, I get the exception below since Magento GraphQL doesn't offer any opportunity to change `quote`.`store_id` DB value:
`[2020-06-23 09:59:29] report.ERROR: Wrong store code specified for cart "QEpSuu6F8zikQ3OBDeDGHZQiNqfwckcl" {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Wrong store code specified for cart \"QEpSuu6F8zikQ3OBDeDGHZQiNqfwckcl\" at /app/vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\GraphQl\\Exception\\GraphQlNoSuchEntityException(code: 0): Wrong store code specified for cart \"QEpSuu6F8zikQ3OBDeDGHZQiNqfwckcl\" at /app/vendor/magento/module-quote-graph-ql/Model/Cart/GetCartForUser.php:81)"} []`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rogyar** [comment]
I would propose adding a separate mutation for changing cart store ID for such cases. In that way, we will handle this behavior explicitly without introducing side-effects for queries.

**Comment by huykon** [comment]
I am facing with this problem. How can I fix this?

**Comment by mauragcyrus** [comment]
hi @isydorenko @rogyar @huykon there is another issue opened for this here: https://github.com/magento/magento2/issues/30100 which is tied to an internal Adobe ticket that will be fixed in 2.4.2 so I closed this one as its duplicate.
