### ISSUE TITLE
Consumer is not authorized to access %resources during Call API

### ISSUE THREAD

**Issue by Aungyetun991990** [magento/magento2#28952]
### Summary (*)
can't able to  call Magento API  
I always got response "Consumer is not authorized to access %resources"
### Examples (*)

![image](https://user-images.githubusercontent.com/47961353/86234885-9b7b8d00-bbbd-11ea-97dd-2be8dcc6ae34.png)

Pls give advice to me how to solve it 
Thanks

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28952-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28952-2-4-develop.instances.magento-community.engineering/admin_634d](https://i-28952-2-4-develop.instances.magento-community.engineering/admin_634d)
Login: `a46770c6` Password: `658abf6f7dac`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@Aungyetun991990 : You can try this and check.

**First, u need to get an admin token :**
 Method: Post
 Url: {Baseurl}/rest/V1/integration/admin/token
 Body: {"username":"", "password":""}

Response : We will get token id
![image](https://user-images.githubusercontent.com/58288685/86238501-3cb51400-bbbb-11ea-92b2-6f9ad364482f.png)

If u need to call any API u should put the token id in Authorization
![image](https://user-images.githubusercontent.com/58288685/86238627-72f29380-bbbb-11ea-87dc-88c50671d0a9.png)

Refer this doc for API: https://devdocs.magento.com/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.html

Note:  This GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ or https://github.com/magento/community-features/issues  for general discussion & feature request

**Comment by Aungyetun991990** [comment]
hello Morning
I tried and follow your instructions but I'm not Ok yet 
Pls help me how to solve it 
![image](https://user-images.githubusercontent.com/47961353/86309971-fb684700-bc42-11ea-8e66-771b533425d0.png)
thanks

**Comment by swathishs** [comment]
HI, In URL why you are adding index.php?
