### ISSUE TITLE
GraphQl. Mutation: customerOrders query and gift_message attribute

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#28957]
### Preconditions (*)

Error `Can't load gift message for order` is returned when order does not have a `gift_message`:

<img width="1114" alt="001" src="https://user-images.githubusercontent.com/13585327/86249206-a03d4280-bbb7-11ea-80ec-2faa89caeb28.png">

### Steps to reproduce (*)

1. Magento (2.4-develop) with a sample data
1. Generate customer token:

```
mutation {
  generateCustomerToken(
    email: "roni_cost@example.com"
    password: "roni_cost3@example.com"
  ) {
    token
  }
}
```

1. Retrieve customer orders:

```
query {
    customerOrders {
        items {
            order_number
            gift_message {
                to
                from
                message
            }
        }
    }
}
```

### Expected result (*)

We do not need to have a `Can't load gift message for order` error in the response when an order does not have `gift_message`.

### Actual result (*)

There is a `Can't load gift message for order` error in the response when an order does not have `gift_message`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35620` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Bug
