### ISSUE TITLE
Magneto 2.3.4 - order increment id is not continuous

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#28964]
### Preconditions (*)

1. Magneto 2.3.4
2. PHP 7.3

### Steps to reproduce (*)

1. Order increment id is not continuous on my live website
2.

### Expected result (*)

1. Screenhot 1 - https://prnt.sc/ta4dpm
2.

### Actual result (*)

1. Order increment id should be continuous
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28964-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28964-2-4-develop.instances.magento-community.engineering/admin_e882](https://i-28964-2-4-develop.instances.magento-community.engineering/admin_e882)
Login: `ec7ad287` Password: `5dbc081d638a`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @gilbertsohal. 
Not able to reproduce the issue as you mentioned, It should be any of your custom module issue
So kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this
Thank you !!
