### ISSUE TITLE
Consumer is not authorized to access %resources during Call API

### ISSUE THREAD

**Issue by Aungyetun991990** [magento/magento2#28965]
Refer Ticket 28952 

### Summary (*)
I followed and tried your instructions in Ticket 28952  But I'm Not Ok yet.
I get same issue.Pls give me advice how to solve it 
### Examples (*)
![image](https://user-images.githubusercontent.com/47961353/86311535-9d3d6300-bc46-11ea-8fb7-9850f92aa603.png)

### Proposed solution
Do I Need to settle setting in Magento Admin Panel ?

**Comment by krishprakash** [comment]
Hi @Aungyetun991990. Thank you for your report !!
GitHub issue tracker is intended for magento core technical issues only 
Kindly refer [magento stock exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this
Also refer the link below:
https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html
