### ISSUE TITLE
Store View Drop down in Admin - unable to scroll to bottom

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#2896]
Hi,

I am viewing the admin products->categories section and when I try to use the Store View drop down I am unable to get to the bottom options if you have a lot of stores.

So If you open the drop down, you need to scroll the page to see the other options. Unfortunately this then closes the drop down, so I am unable to change to the bottom ones!

This is on Firefox or Chrome (latest).

**Comment by odubovyk** [comment]
Initial ticket MAGETWO-48386

**Comment by elenleonova** [comment]
@craigcarnell thanks for reporting the issue to us. If it doesn't take much of your time, can you share the screenshot on the problem you're seeing or provide the number of stores that you have in your configuration? Thanks

**Comment by vzaporozhets** [comment]
This issue is reproduced. Unless Store View is visible - it is possible to scroll down page. However as soon as selector is going out of visible area - drop down disappears. Screenshots will be added to internal ticket.

**Comment by MomotenkoNatalia** [comment]
@craigcarnell Internal ticket MAGETWO-48386 is closed and delivered to mainline. Please let us know if you still have an issue.
