### ISSUE TITLE
Query enabled and disabled categories with Graphql.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#28979]
### Description (*)
Would like to be able to get disabled categories using Graphql.
Either by default (Could be a breaking change for some) or a filter to allow disabled categories to come through.
E.g. ```filter: { status: { in: [1,2] } }``` could default to enabled to retain current behaviour.

Example Query:
```graphql
{
  category(id: 2) {
    id
    name
    children {
      id
      name
      children {
        id
        name
        children {
          id
          name
        }
      }
    }
  }
}
```

### Expected behavior (*)
Return all categories even disabled ones.
A separate field for disabled or status can be used to check if it is active...

### Benefits
Helpful for product/category sync tool to import from third party retail systems.
Allows to import but have category disabled for web admin to enable manually as they wish.

### Additional information
Related: This was originally seen as a bug and was fixed, but would be good to be able to query them.
https://github.com/scandipwa/catalog-graphql/issues/7
https://github.com/magento/graphql-ce/issues/724

**Comment by mauragcyrus** [comment]
@LiamKarlMitchell the use cases described are geared towards administrative API, rather than a storefront API, and you would be better off using the REST APIs for admin-level operations.
