### ISSUE TITLE
NDB Cluster 7.4.* Support

### ISSUE THREAD

**Issue by rsidhaarth** [magento/magento2#28970]
Hi Team,

I am trying to migrate the mysqldump data to NDB cluster 7.4 and I am getting error with Fulltext.

As I can see that, M2 support NDB Cluster 7.4 but when trying to create a table on NDB cluster it fails as they dont support FULLTEXT.

So whats the solution here?

`CREATE TABLE catalogsearch_fulltext_scope1(entity_idint(10) unsigned NOT NULL COMMENT 'Entity ID',attribute_idint(10) unsigned NOT NULL COMMENT 'Attribute_id',data_index longtext COMMENT 'Data index', PRIMARY KEY (entity_id,attribute_id), FULLTEXT KEY FTI_FULLTEXT_DATA_INDEX (data_index) ) ENGINE=NDB DEFAULT CHARSET=utf8 COMMENT='catalogsearch_fulltext_scope1_tmp';`

**Comment by krishprakash** [comment]
Hi @rsidhaarth. Thank you for your report !!
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this
