### ISSUE TITLE
please do an add of how to css sass add bootstrap code devdocs?

### ISSUE THREAD

**Issue by r32rf** [magento/magento2#28971]
helo today i want to ask you do an add of how to use the bootstrap framework in the magento 2 dcoumentation it is currently not of the clear how to use the bootstrap css  sass code in magento 2 docs on css empty please do an add of how to use the container css sass and code in the magento 2 framwork?

**Comment by r32rf** [comment]
@m2-assistant ??

**Comment by krishprakash** [comment]
Hi @r32rf. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
