### ISSUE TITLE
After migration configurable Products not showing Associated products

### ISSUE THREAD

**Issue by gitpramos** [magento/magento2#2897]
After migration configurable products are not showing associated products in Admin panel.

**Comment by palamar** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
