### ISSUE TITLE
Cannot publish an associative array to a configured queue

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#28984]
### Preconditions (*)
Magento EE 2.3.5-p1
PHP: 7.3.18

### Steps to reproduce (*)
1 configure queue like:

file: communication.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Communication/etc/communication.xsd"
>
    <topic name="queue.name" request="string" />
</config>
```

file: queue_consumer.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/consumer.xsd"
>
    <consumer name="queue.name"
              queue="queue.name"
              connection="db"
              consumerInstance="Magento\Framework\MessageQueue\Consumer"
              handler="My\Class\Consumer::execute"
    />
</config>
```
file: queue_publisher.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/publisher.xsd"
>
    <publisher topic="queue.name"">
        <connection name="db" exchange="my-exchange-db" disabled="false"/>
    </publisher>
</config>
```
file: queue_topology.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/topology.xsd"
>
    <exchange name="my-exchange-db" type="topic" connection="db">
        <binding id="queue.name"
                 topic="queue.name"
                 destinationType="queue"
                 destination="queue.name"
        />
    </exchange>
</config>
```
### Expected result (*)
try to publish a message:

```
<?php

declare(strict_types=1);

namespace My\App\Service\Amqp;

use Magento\Framework\MessageQueue\PublisherInterface;

class MyPublisher
{
    /**
     * @var PublisherInterface
     */
    private $publisher;

    public function __construct(PublisherInterface $publisher)
    {
        $this->publisher = $publisher;
    }

    public function execute(int $salesOrderId): void
    {
        $this->publisher->publish(
            'queue.name',
            [
                'salesOrderId' => $salesOrderId,
            ]
        );
    }
}
```
### Actual result (*)
call `MyPublisher::execute(123);`
this generate error `"Notice: Undefined offset: 0 in \/srv\/vendor\/magento\/framework-message-queue\/MessageValidator.php on line 123"`

### Proposed Solution (*)
I try to disable validation in `vendor/magento/framework-message-queue/Publisher.php::L79` but the value in `$data = $this->messageEncoder->encode($topicName, $data);` is wrong encoded expected data is: `{"salesOrderId":123}` got `[123]`
NB: i'm currently change my code to `json_encode` message before call `PublisherInterface::publish` and it's pass validation and obviously is correct in my message.body. But our interface accept only `array|object`, so i think it's not safe to pass a string to this method. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hello @rvitaliy, thank you for your report.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

**Comment by rvitaliy** [comment]
:confused: :question:

**Comment by engcom-Lima** [comment]
Hello @rvitaliy [This](https://www.youtube.com/watch?v=2UNmN54K_PE&list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj&index=3) 
 video discusses this software issue with PO.

**Comment by VladimirZaets** [comment]
Hi @rvitaliy. Your request looks like the feature, not a bug. We have approach to use objects instead of associative arrays. If you think that we need to use associative arrays in this case you can create the issue in "community-features" repository and discuss it with our architects

**Comment by rvitaliy** [comment]
Hi @VladimirZaets !
I tried to search documentation or examples but i didn't found anything.
Can you provide an example of how this implementation work on publish and on consuming of message?

**Comment by dudzio12** [comment]
Well @rvitaliy I think you have wrong request type in `communication.xml`. You should use `<topic name="queue.name" request="array" />`.

My problem is that I use associative array too, but with request type `string` and json encoded data. The problem in that configuration is with json_encode fired twice - once by me to achieve string data type, second time by Magento to convert whatever data to json to make it compatible with queue (RabbitMQ in my case). 

Well.. there is no option than do some additional classes ;)

**Comment by mrtuvn** [comment]
Any reason we change type data from array|object to mixed ? So we can pass any kind type for data in publisher queue

**Comment by guvra** [comment]
Still not possible in 2.4.5, if you specify `request="array"` in communication.xml, you get the following error message:

```
Request schema definition for topic "xxx" should reference existing service class. Given "array"
```

Seems like only simple arrays are allows, like `string[]` or `int[]`.
Temporary workaround is to create a dummy class that contains the array, and use an instance of this class as the message data.
