### ISSUE TITLE
Text Swatch doesn't save 0 (zero) value.

### ISSUE THREAD

**Issue by giantdev** [magento/magento2#28987]
### Preconditions (*)

1. Magento version 2.3.3

### Steps to reproduce (*)

1. Go to Admin > Attributes > Product and click one of text swatch attribute.
2. Try to add new swatch with zero(0) value.

### Expected result (*)

1. [Screenshots, logs or description]
2. zero(0) value should be saved

### Actual result (*)

1. [Screenshots, logs or description]
2. No error messages and issues, but it just doesn't save the value. It just leaves blank.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by giantdev** [comment]
I found this:

module-swatches/Model/Plugin/EavAttribute.php

Method: processTextualSwatch
Line: 345

I think
if (!$value) {
     $value = $defaultSwatchValue;
}
Should be
if (!isset($value) || $value != "") {
     $value = $defaultSwatchValue;
}

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment]
Hello @giantdev,
I have verified this issue with Steps to be reproduced, Actual result and Expected result.
Not reproduce this issue.
Please provide me video if you have.

Thanks.

**Comment by ajijshekh123** [comment]
@giantdev - Any Update. If this issue is fixed Please let me know so I will close this issue.

**Comment by giantdev** [comment]
@ajijshekh123 I still have the issue. I am just wondering if the issue has been fixed on 2.3.5

**Comment by ajijshekh123** [comment]
@giantdev - It may be fixed on the next Magento release. Please upgrade the Magento version. 
If this issue found in the new Magento version you can message here.

**Comment by ajijshekh123** [comment]
Hi @giantdev,
if you have reproduced this issue on the latest Magento instance. please reopen it.

Thanks.
