### ISSUE TITLE
Merge CSS en JS shows blank

### ISSUE THREAD

**Issue by gitpramos** [magento/magento2#2898]
Merge CSS en JS shows blank shop

**Comment by zanilee** [comment]
Hi, @gitpramos!

Could you please provide steps to reproduce this issue?

**Comment by gitpramos** [comment]
Actually the problem relies in merging .css files, after doing the merge i get a 500 error on admin panel and in front end is blank. Merging .js en bundling has no efect. 

Minify .js i can see a lot of min.js but not bundling as I expected. 

Firstly i'done it in one time and it blows the all system and recovered in the db. But also done one for one and refreshing cache I get the same problem. 

Thanks in advance.

**Comment by palamar** [comment]
@gitpramos 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
