### ISSUE TITLE
Password prompt shows for unregistered user

### ISSUE THREAD

**Issue by zichicc** [magento/magento2#28988]
### Preconditions (*)

1. Magento 2.3.5
2. Magento 2.4.0
3. Luma template

### Steps to reproduce (*)

1. Put item into the cart and proceed to checkout
2. fill in email address and shipping address forms at Shipping step and go to Review & Payment page
3. go back to shipping address step either by clicking on "Shipping" or using "Back" navigation button of the browser
4. reload the page

### Expected result (*)

1. "You can create an account after checkout." text shown under email address form
2. http://snpy.in/frEnkn

### Actual result (*)

1. Password prompt is shown below email address form even if the user is not registered
2. http://snpy.in/zQNinJ

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
duplicate with this https://github.com/magento/magento2/issues/26903

**Comment by swathishs** [comment]
@christianzichichi : Since this issue is duplicate .Hence closing the issue. You can refer this ticket for further details.
Ticket ID: #26903
