### ISSUE TITLE
Filters option is not working for "Color"

### ISSUE THREAD

**Issue by Rishabh-e-Zest** [magento/magento2#28983]
When using core API to filter product in magento as per the filter option showed in below image.
![image-2020-01-13-17-31-41-941](https://user-images.githubusercontent.com/67787398/86464800-eaf0c300-bd4d-11ea-8a56-c9b77692722a.png)
 Unable to find any product even that product exsist in Magento.
Filter works fine on web but not on mobile.

I am using this criteria:
http://127.0.0.1/local-setup/rest/V1/products/?searchCriteria[filterGroups][0][filters][0][field]=category_id&searchCriteria[filterGroups][0][filters][0][value]=172&searchCriteria[filterGroups][2][filters][0][field]=salon_id&searchCriteria[filterGroups][2][filters][0][value]=1&searchCriteria[filterGroups][2][filters][0][conditionType]=finset&searchCriteria[filterGroups][3][filters][0][field]=visibility&searchCriteria[filterGroups][3][filters][0][value]=4&searchCriteria[pageSize]=5

**Comment by swathishs** [comment]
@Rishabh-e-Zest  : Could you please update step to reproduce to recreate the issue and if any screenshot available

**Comment by Rishabh-e-Zest** [comment]
I run the api to filter configurable product depends on their attribute:
http://127.0.0.1/local-setup/rest/V1/products/?searchCriteria[filterGroups][0][filters][0][field]=category_id&searchCriteria[filterGroups][0][filters][0][value]=172&searchCriteria[filterGroups][2][filters][0][field]=salon_id&searchCriteria[filterGroups][2][filters][0][value]=1&searchCriteria[filterGroups][2][filters][0][conditionType]=finset&searchCriteria[filterGroups][3][filters][0][field]=visibility&searchCriteria[filterGroups][3][filters][0][value]=4&searchCriteria[pageSize]=5

i am using visibility = 4 while the configurable sub product has visibility = not visible individualy.
i am not getting how to filter out those product in my app.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Rishabh-e-Zest** [comment]
Hi @swathishs , do you find any solutions for this?

**Comment by swathishs** [comment]
@Rishabh-e-Zest : Hi I am a tester I will be testing your issue in 2.4 develop instances and if it's recreated then I will approve the ticket. Since there is issue in the Magento instance so still pending to recreate the issue.

**Comment by Rishabh-e-Zest** [comment]
@swathishs  ok
