### ISSUE TITLE
Rollback function for database not working (terminal&backend)

### ISSUE THREAD

**Issue by nordcomputer** [magento/magento2#28997]
### Preconditions (*)

1. Docker Environment with Magento ver. 2.3.5-p1
2. MariaDB 10.0 (container image: mariadb:10)
3. PHP 7.1 Apache (container image: webdevops/php-apache:7.1)

### Steps to reproduce (*)
1. Create Database backup (doesnt matter if from backend or from terminal)
2. Backup gets listed (in backend and in terminal with `bin/magento info:backups:list`)
2. Rollback Database Backup

### Expected result (*)

1. Backup should be restored via rollback function

### Actual result (*)

1. when trying to rollback the backup in Backend, it results in an error simply saying: "Error at rollback"
2. when trying to rollback the backup from terminal, it results in this:

```
bin/magento setup:rollback -d 1593939061_db_foobar.sql
Enabling maintenance mode
You are about to remove current code and/or database tables. Are you sure?[y/N]y
Do you want to keep the backups?[y/N]y
DB rollback is starting...
Multiple queries can't be executed. Run a single query and try again.
Disabling maintenance mode
```

---

- [ x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you
