### ISSUE TITLE
There are no sensitive configurations to fill

### ISSUE THREAD

**Issue by oviliz** [magento/magento2#28994]
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
Unable to use `config:sensitive:set` at all. Works fine with `config:set`. E.g.:
```
$ bin/magento config:sensitive:set contact/email/recipient_email 'sensitive@email.com'
There are no sensitive configurations to fill
$ bin/magento config:set contact/email/recipient_email 'sensitive@email.com'
Value was saved.
```
```
$ bin/magento config:sensitive:set msp_securitysuite_recaptcha/general/private_key 'RanDOm-Sensitive-KeY-'
There are no sensitive configurations to fill
$ bin/magento config:set msp_securitysuite_recaptcha/general/private_key 'RanDOm-Sensitive-KeY-'
Value was saved.
```

### Expected result (*)
The command should return:
`There are no sensitive configurations to fill. The config:sensitive:set command is applicable only after app:config:dump command has been applied.`

### Actual result (*)
The command returns:
`There are no sensitive configurations to fill.`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38359` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cjohansson** [comment]
Is it possible to set sensitive configuration via terminal and store it in database? It seems impossible at the moment. bin/magento app:config:dump will force storage of configuration into files.

**Comment by hostep** [comment]
@cjohansson: could you try the `config:store:set --encrypt <path> <value>` command from [magerun2](https://github.com/netz98/n98-magerun2/#set-store-config)? It sounds like that might be the way to do it.

**Comment by cjohansson** [comment]
@hostep I tried this in Magento 2.4.3 but it says
```
There are no commands defined in the "config:store" namespace.
```

Is it a Commerce-only feature perhaps? I'm using Community Edition

**Comment by cjohansson** [comment]
Aha you mean from magerun, missed that part :+1:

**Comment by slavko98** [comment]
Hi all, is there any progress/update on this one? I was reading about the `config:sensitive:set` command on the Magento official docs, and trying to figure out how it works, but it fails with this `There are no sensitive configurations to fill` error message. Not meaningful at all :/

I'm trying to set a sensitive configuration field for a custom module (field of type `obscure`, and additionally added to `Magento\Config\Model\Config\TypePool` as `sensitive`).

Did anyone get this working "the Magento way"?

**Comment by cjohansson** [comment]
> Hi all, is there any progress/update on this one? I was reading about the `config:sensitive:set` command on the Magento official docs, and trying to figure out how it works, but it fails with this `There are no sensitive configurations to fill` error message. Not meaningful at all :/
> 
> I'm trying to set a sensitive configuration field for a custom module (field of type `obscure`, and additionally added to `Magento\Config\Model\Config\TypePool` as `sensitive`).
> 
> Did anyone get this working "the Magento way"?

magerun is the only way
