### ISSUE TITLE
Settings for Search Engine Optimization don't work as suposed

### ISSUE THREAD

**Issue by gitpramos** [magento/magento2#2899]
Settings for Search Engine Optimization "Configuration > Catalog > Search Engine Optimization >"

Use Categories Path for Product URLs
Use Canonical Link Meta Tag For Categories
Use Canonical Link Meta Tag For Products

**Comment by antboiko** [comment]
Hello @gitpramos , thanks for your inquiry. Could you please provide more details about issue you have?

**Comment by vzabaznov** [comment]
Closing the issue as it is no response has been received from the reporter.
@gitpramos  Please feel free to reopen if you feel that issue could be reproduced.
