### ISSUE TITLE
Cannot insert widgets in CMS page or static block

### ISSUE THREAD

**Issue by chequille** [magento/magento2#29005]
Do not know if it is a bug or not, but I kindlly ask you for help on that, because it is a backend issue and therefore could not be a problem of my theme development.

Using: Version 2.3.5-p1
PHP: 7.2.x

Problem:
Editiing a static block and trying to insert a widget by pressing "Insert Widget" Button is not showing the window to insert a widget but the 404 error page of the backend!!!
![grafik](https://user-images.githubusercontent.com/15807794/86589539-24b00c80-bf8e-11ea-8743-f6f58c0eb12c.png)

If I pressed the button, I am getting this (see screenshot)
![grafik](https://user-images.githubusercontent.com/15807794/86589653-56c16e80-bf8e-11ea-943b-a853a5737f50.png)

In the log files I am getting the following error messages

[2020-07-02 21:48:14] main.DEBUG: URI '/admin/cms/page/edit/page_id/6/key/9cda62bd1db41b6a327d51c1b2b9abb85a93b75f938498bdf2b8b897c40b9247/widget_target_id/cms_page_form_content/mode/new?isAjax=true'' cannot be accessed with POST method (Magento\Cms\Controller\Adminhtml\Page\Edit) [] [] [2020-07-02 21:48:14] main.DEBUG: Request validation failed for action "Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at D:\\WebMagentoAktuell\\vendor\\magento\\framework\\App\\Request\\HttpMethodValidator.php:69)"} []

Can somebody have a look at this please. I do have no idea what could be wrong.
THanks and BR
Chequille

**Comment by chequille** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @chequille. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by chequille** [comment]
@krishprakash 
Hi,
are you testing this or why did I not get an instance yet?
BR
Chequille

**Comment by krishprakash** [comment]
Hi @chequille. Sorry for inconvenience, There is some issue with automated instance. will be sort out soon.
Thanks !!

**Comment by chequille** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @chequille. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by chequille** [comment]
What is going on with this?
No instance set yet?
By the way, it would not help to get a 2.4 instance if the error is on 2.3.5!!!!
I am a little bit angry currently.

**Comment by tgamanov** [comment]
Hello @chequille.
I have tested the described issue on fresh 2.3.5-p1 with PHP 7.2.32 and wasn't able to reproduce it. Please see attached screenshots.
![WidgetInBlock](https://user-images.githubusercontent.com/11708989/89018420-8876ec80-d324-11ea-9a70-2c4d5064d562.png)
![WidgetInPage](https://user-images.githubusercontent.com/11708989/89018423-89a81980-d324-11ea-9625-d9bb2b81bf5f.png)

Could you please check it on a fresh instance of Magento and provide more details on how to reproduce it.
Thank you.

**Comment by chequille** [comment]
@tgamanov 
What happens if you click on the button "Insert Widget"?
I get this erroir when doing so.
This is the problem.
of course if I know the syntax of the widget I can insert it into the page.

**Comment by chequille** [comment]
Hi again,
I just tested it in a fresh 2.3.5-p2 and when clicking on insert widget the modal window appear as it should.
![grafik](https://user-images.githubusercontent.com/15807794/89085433-80a16180-d391-11ea-8dc6-095eca1effa6.png)

I had a look at the code of the "Insert Widget" Button and saw the following:
![grafik](https://user-images.githubusercontent.com/15807794/89086972-d75b6b00-d392-11ea-8905-a734d99fcd64.png)

This is the one not working. In the onclick function widgetTools.openDialog there is only written widget_target_id/cms_page_form_content/ and the rest of the Url is not there.

The working example from fresh installation looks like this. The parameter includes as well the complete URL to the page: 
![grafik](https://user-images.githubusercontent.com/15807794/89087177-a92a5b00-d393-11ea-88c9-c2dca44f09f5.png)

This is the only difference I see. I guess this is the problem.
Do you have any idea what causes this difference?
Both versions are on the same server , same PHP and same database server.

PLease let me know if you a´have any idea.

Best regards,
Chequille

**Comment by chequille** [comment]
At least I found the code where this is going wrong.
It is in framwork/data/Form/Element/editor.php
When building the buttons the path is generated for the widget using
$this->getPluginConfigOptions('magentowidget', 'window_url')
But this is empty, therefore the path is not there.
Any ideas why this is empty?

**Comment by chequille** [comment]
Oh my god!
THe solution was at the end easy.
In my config, there was TinyMCE Version 3 selected and this causes the problem.
Changed to TinyMCE 4 and now it is working.

**Comment by luismiguelyangehuaman** [comment]
@chequille can you tell me in details about how your change the version of TinyMCE, I don't see configuration in Magento admin. thanks

**Comment by chequille** [comment]
Hi,
here a screenshot.
![grafik](https://user-images.githubusercontent.com/15807794/99579738-dea89200-29de-11eb-9fc4-046cd75f3097.png)

Ok, it is translated but I think it is under general-> cms
Hope you find it.

**Comment by kamephis** [comment]
Unfortunately that did not solve the problem for me. The only editor available is TinyMCE 4. I am on 2.4.2 CE.
