### ISSUE TITLE
Gift Card Get "Please specify a gift card amount" Error

### ISSUE THREAD

**Issue by alexgao-tinyme** [magento/magento2#29028]
### Preconditions (*)

1. Magento Commerce 2.3.5
2. Set Gift card as "invoiced" type and only enable gift card's open amount. do not set predefined amount for gift card product in admin 

### Steps to reproduce (*)

1. purchase a gift card with custom amount you put in the input field
2. use adyen or credit card checkout checkout payment method, do not use paypal. 

### Expected result (*)

1. Users are supposed to purchase this product successfully without any error

### Actual result (*)

1. get error "Please specify a gift card amount."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by swathishs** [comment]
Hi @alexgao-tinyme , all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue too-
https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Comment by sdzhepa** [comment]
Hello @alexgao-tinyme 

Thank you for your contribution and collaboration!

I moved this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
