### ISSUE TITLE
Trying Magento2.4.0 Could not install

### ISSUE THREAD

**Issue by abhinavaggarwal8** [magento/magento2#29027]
I was trying to install latest magento2.4.0
![ss](https://user-images.githubusercontent.com/10917770/86859202-c7c46b80-c0df-11ea-8cc4-7a0e078b3b43.jpg)

composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.4.0 html

Could not find package magento/project-enterprise-edition with version 2.4.0

**Comment by swathishs** [comment]
@abhinavaggarwal8 : Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ or https://github.com/magento/community-features/issues  for general discussion & feature request
