### ISSUE TITLE
Ability to Reset All Filters in Orders Page

### ISSUE THREAD

**Issue by thorrrr** [magento/magento2#29021]
### Description (*)

We use the order screen all day and apply filters. For some reason this page does not have a reset all filters option!
But you other search areas do!
We have to click each filter individually to remove it which results in a full page refresh.
Having just moved from M1 i feel like i have gone back 10 years with the speed its painfully slow to refresh.
But if i have 3 to 5 filters this takes a long time.
### Expected behavior (*)

I would expect a standard reset all filters button
### Benefits

Efficiency and speed of use it just needs one not sure how it was ever missed out

**Comment by krishprakash** [comment]
Hi @thorrrr. Thank you for your report.
Please, create issue in [community-features repo](https://github.com/magento/community-features/issues) for further discussion.
