### ISSUE TITLE
Product images not showing after upgrade

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#29025]
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Products and images were importe in Magento 2.3.4
2. Productimages were showing correctly in Magento 2.3.4
3. I upgraded magento to 2.3.5-p1
4. Poductimages are not showing of products that are not manually saved before.
5. When I check the databasetable catalog_product_entity_media_gallery_value it is missing entries for all products that are not manually saved.
6. Problem can be solved by manually opening and closing the product in admin, but is not workable with 1000+ products.

### Expected result (*)

1. I expect product images to show.

### Actual result (*)

1. Product images are not showing

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @mtjweb thank you for your report, I'm not able to reproduce issue by steps you described after upgrade on 2.4.1
Were checked cases with upgrade from the latest 2.3.x realese (2.3.6) to the latest 2.4.x (2.4.1) and upgrade from 2.4.0 to 2.4.1
**Manual testing scenario:**

- Create simple product with images
- For each images add `Alt Text`
![image](https://user-images.githubusercontent.com/51681379/104924670-6fcbc300-59a6-11eb-9724-57c31236c54d.png)

- Upgrade to 2.4.1 according [docs](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
- Go to catalog page and product detail page
- 

**Result:**
:heavy_check_mark: Product images are shown on pages
:heavy_check_mark: Records from `catalog_product_entity_media_gallery_value` contains entries for products
![image](https://user-images.githubusercontent.com/51681379/104925642-c5549f80-59a7-11eb-9a2f-0236c54b56b7.png)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
