### ISSUE TITLE
Unsupported platform is mentioned in 'backup successful' message

### ISSUE THREAD

**Issue by EustaceCS** [magento/magento2#29026]
### Preconditions (*)
Install Magento by any supported means suitable.

### Steps to reproduce (*)
Make a backup through CLI successfully.

### Expected result (*)
Unsupported platforms (see #28055 for the 'why') are not mentioned.

### Actual result (*)
![Capture](https://user-images.githubusercontent.com/29461793/86834744-dc830e00-c0a3-11ea-9093-667f0b93fde7.PNG)
I believe, it's from https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Backup/Block/Adminhtml/Grid/Column/Renderer/Download.php#L25 .

---

Can't provide Severity using current Severity definitions - it's S4, S1 and S2 altogether, if evaluating 'as written'.

**Comment by hostep** [comment]
Why shouldn't you be able to uncompress an archive file on Windows? Not sure if this has anything to do with Magento not being supported on Windows, this is about uncompressing an archived file, not about Magento itself, no? 😛

**Comment by engcom-Delta** [comment]
Hi @EustaceCS thank you for your report
Looks like it is not an issue but additional recommendation for users who used web service stack on Windows OS 

If you'd like to update  the issue, please reopen it.
