### ISSUE TITLE
Unable to run unit tests on Alpine PHP 7.3 / 7.4 - errors thrown

### ISSUE THREAD

**Issue by cpini** [magento/magento2#29036]
### Preconditions (*)
1. Magento 2.3.5 (and 2.4-develop)
2. Docker image: php:7.3-fpm-alpine (also tested on php:7.4-fpm-alpine)
3. Default composer install > allure-framework/allure-phpunit:~1.2.0  (installs 1.2.4)
4. Also Manually upgraded to allure-framework/allure-phpunit:~1.3.0 (installs 1.3.1)

### Steps to reproduce (*)
/usr/local/bin/php -d memory_limit=2048M /var/www/html/./vendor/phpunit/phpunit/phpunit 

1. Running the above with allure-framework 1.2.4 results in the GLOB_BRACE error
_Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74._

2. Running the above with allure-framework 1.3.1 results in class _does not exist_ error
_Class "Yandex\Allure\Adapter\AllureAdapter" does not exist_

### Expected result (*)
1. Unit Tests to execute without error

### Actual result (*)
1. Execution dies with error

---

- [ ] Severity: **S2** _- Affects QA process and Ci/CD pipelines for users deploying with Alpine ._

**Comment by fredden** [comment]
This looks like a duplicate of #24635
