### ISSUE TITLE
core error -  indexing error 

### ISSUE THREAD

**Issue by bkristl** [magento/magento2#2903]
[boštjan.txt](https://github.com/magento/magento2/files/80059/bostjan.txt)
In attached file is error trace when creating a product 

When i run 
php bin/magento indexer:reindex

i get following error:

Catalog Search indexer process unknown error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.category_ids' in 'field list', query was: SELECT STRAIGHT_JOIN `e`.`entity_id`, `e`.`type_id`, `e`.`category_ids`, `e`.`sku` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_website` AS `website` ON website.product_id = e.entity_id AND website.website_id = '2' WHERE (e.entity_id > 0) ORDER BY `e`.`entity_id` ASC LIMIT 100

Also i can not add any new product through web GUI.

Best regards,
Bostjan

**Comment by mazhalai** [comment]
@bkristl can you please give us more information about your environment? How did you deploy magento : via git, via composer create-project or downloaded a zip from magento.com? Also, is this a fresh install?

**Comment by bkristl** [comment]
This is fresh install of magento version 2.0 but i think is downloaded via zip magento.com. I have use all installation possibilities, so i am not 100% sure. Are there some difference of installation (different version of files) ?

If you need the whole code with database i can send you. 

I have research that the problem come when is using full text search. 
The problem is in file
app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Action/Full.php 
in function 
getSearchableProducts

at line: 404

where is array_merge(['entity_id', 'type_id'], $staticFields)

input var $staticFields for function getSearchableProducts is:

array(2) {
  [0]=>
  string(12) "category_ids"
  [1]=>
  string(3) "sku"
}

but category_ids is not part of table catalog_product_entity

If you need any additional information just ask. If you need faster response, i am available at skype: bostjan_81

Best regards,
Bostjan

**Comment by ghost** [comment]
Are you using MySQL Full-Text or Solr?

**Comment by mazhalai** [comment]
Also, what version of PHP, OS, and server?

**Comment by bkristl** [comment]
I have test this problem in 2 different environment:
In both i use MySQL Full-Text, but later we want to integrate Apache Solr
As server you mean web server, if i am wrong please correct me. So for server i will provide you info for web server.

---

1) 
OS:  Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux (debian 8.2 - jessie)

MYSQL: Ver 14.14 Distrib 5.7.10, for Linux (x86_64) using  EditLine wrapper

PHP 5.6.14-0+deb8u1 (fpm) with  with Zend OPcache v7.0.6-dev

WEBSERVER: nginx/1.8.0
built by gcc 4.9.2 (Debian 4.9.2-10) 
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_spdy_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' --with-ipv6

---

2) 
OS: Linux template 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux

MYSQL: Ver 14.14 Distrib 5.7.10, for Linux (x86_64) using  EditLine wrapper

PHP 7.0.0 (cli) (built: Dec  2 2015 12:19:00) ( NTS )
with Xdebug v2.4.0rc1 
with Zend Extension Manager v8.0.0
with Zend Data Cache v8.5.0
with Zend Job Queue v8.5.0
with Zend Utils v8.5.0
with Zend OPcache v7.0.6-dev
with Zend Code Tracing v8.5.0
with Zend Server Z-Ray v8.5.0
with Zend Monitor v8.0.0
with Zend Page Cache v8.5.0

WEBSERVER: Apache/2.4.10 (Debian) build Aug 28 2015 16:28:08

---

**Comment by bkristl** [comment]
Also when i was want to look at content of:
variable $select 
in function getSearchableProducts 
of class Full ( namespace Magento\CatalogSearch\Model\Indexer\Fulltext\Action )
in file: app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Action/Full.php
and save to file i was getting content bigger then 2GB, after that i was stop the execution.
There must be too much loop...

**Comment by mazhalai** [comment]
@bkristl thank you for your update. We have created ticket MAGETWO-47705 to investigate.

**Comment by kandy** [comment]
@bkristl, Can you provide screenshot of Storefront Properties Tabs for product attribute `category_ids`?

**Comment by bkristl** [comment]
![category_ids-storefront](https://cloud.githubusercontent.com/assets/4640143/12229777/c67f12c0-b842-11e5-9279-d5867f26f2bd.png)

**Comment by kandy** [comment]
Please set "Used for Sorting in Product Listing" to No for "category_ids" attribute. Because "category_ids" is multi value attribute, sorting by it do not make sense. This field currently editable by mistake.

**Comment by vzabaznov** [comment]
Hi @bkristl, thak you for reporting, issue was fixed and delivered, please check and if you will that not, please feel free to reopen this one or add new.
