### ISSUE TITLE
Product attribute: Storefront Properties Tab is disappearing while editing attributes

### ISSUE THREAD

**Issue by jvinzens** [magento/magento2#29033]
### Preconditions (*)

1. Magento 2.4-develop
2. Disable/enable product attributes to use in search

### Steps to reproduce (*)

1. Navigate to Stores -> Attributes ->Product in Backend
2. Try to edit the "image" attribute for example;
3. After a few seconds, the "Storefront Properties" tab is disappearing

### Expected result (*)

1. When editing existing product attributes, the Storefront Properties tab should not disappear.

### Actual result (*)

1. When editing product attributes, the Storefront Properties tab disappears after a few seconds. The css attribute "display:none" is added in the source code for this specific tab.
![Peek 2020-07-29 12-13](https://user-images.githubusercontent.com/51679138/88781361-f7bdd680-d194-11ea-8a7e-caa0dc46c6be.gif)

![2020-07-29_11-50](https://user-images.githubusercontent.com/51679138/88781132-a9a8d300-d194-11ea-97dc-55ce47b1809d.png)

For example, if we enable one of the options, like "Visible on Catalog Pages on Storefront", as a result, we can see information on the Additional Information tab of the product page

![2020-07-29_12-16](https://user-images.githubusercontent.com/51679138/88781718-67cc5c80-d195-11ea-92bd-c78f85943068.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36261` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
