### ISSUE TITLE
how to disable the tooltip on the navigation bar Magento 2

### ISSUE THREAD

**Issue by mdy9888** [magento/magento2#29030]
### Summary (*)
I want to disable tooltip show out in navigation bar and anywhere. How to do it?

### Examples (*)
I try to go Stores ->Configuration ->Catalog ->Catalog ->Storefront ->Show Swatch Tooltip then I selected "NO" but still show.

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @mdy9888 . Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
