### ISSUE TITLE
Catalog Import: Product Links for skipped rows get always deleted

### ISSUE THREAD

**Issue by theCapypara** [magento/magento2#29040]
### Preconditions (*)
1. Have a catalog import file and prepare it to be imported with a behaviour that is not "append".
2. Make sure that this import file contains at least one critical error, that will cause all other rows of the import to be skipped, such as a duplicate URL key
3. Make sure that other rows in the import file have product links and that those products also already have links in the database

### Steps to reproduce (*)

1. With an import file as described in the pre-conditions, run the catalog import.

### Expected result (*)

1. Magento reports that the import contained at least one critical error and it reports it skipped the products with links (as described in Preconditions 3.)
2. The product links for those products should still be as they were before (see table `catalog_product_link`)

### Actual result (*)

1. Magento reports that the import contained at least one critical error and it reports it skipped the products with links (as described in Preconditions 3.)
2. All product links for all skipped products in the import file are deleted.

### Background information
The issue is the method `saveLinksData` in `Magento\CatalogImportExport\Model\Import\Product`.
It deletes all links for all product IDs provided, which are all products in the import bunch. After this it would re-import the product links as set in the import file, but since the row was skipped, the data is empty, so no links are imported.

The method should not delete links for rows that were skipped because of the validation.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Parakoopa** [comment]
Upon digging into this a bit more, it seems that my initial observations were incorrect. I also can't get this issue to reproduce anymore, I'll put some more testing into this and re-open if I find proper steps to reproduce.
