### ISSUE TITLE
Catalog price rule scheduled changes end date not working properly

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#29046]
### Preconditions (*)

1. Magento enterprise edition : 2.3.4

### Steps to reproduce (*)

1. create a price rule
2. then create scheduled changes with start date and end date
3. then check for end date of price rule at fronend it's ending after 24 hrs of end date 

### Expected result (*)

1. It should end at the end of scheduled date

### Actual result (*)

1. it's ending after 24 hrs of scheduled end date

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rani-webkul** [comment]
@ajijshekh123 did you checked the issue?

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by hostep** [comment]
Even if this is considered a bug, it might be not a good idea to change this, since a lot of Magento users will be used to this behavior and if this changes all of the sudden in a new version that might be very unexpected and cause a lot of harm.

Maybe a Product Owner should decide here first if this can be tackled or not?

Just my 2 cents 🙂

**Comment by rani-webkul** [comment]
@hostep did you mean it's not a bug right?

**Comment by ajijshekh123** [comment]
@rani-webkul - I can't able to verify this issue right now because of there is some issue on Magento Instance.

**Comment by hostep** [comment]
@rani-webkul, it might be a bug, I'm not sure. But if it's considered a bug we should be very careful to change this behavior as Magento users might rely on their previous knowledge about how it behaved. Therefore the opinion of the product owner would be appreciated here.

**Comment by ajijshekh123** [comment]
@rani-webkul - I have verified this issue as per your steps, expected result and actual result. After 24 hours, The code is not accepted and it's showing an error like "The coupon code isn't valid. Verify the code and try again."
@rani-webkul - Can you please update me about the cart rule details?

Thanks

**Comment by ajijshekh123** [comment]
@rani-webkul - Any update?

**Comment by ajijshekh123** [comment]
Hi @rani-webkul,
This is not an issue. This is a Feature. If you want to add this feature in the latest Magento Instance You can create the ticket in the Magento Feature list.

Thanks.
