### ISSUE TITLE
Braintree 3D Secure verification assumes address has region code

### ISSUE THREAD

**Issue by theloveofcode** [magento/magento2#29049]
### Preconditions (*)

1. Magento Open Source or Commerce version 2.3.5 p-1

### Steps to reproduce (*)

1. Checkout using an address for which there is no state/province dropdown, such as Papua New Guinea
2. Use Braintree Credit Card with 3D Secure enables as the payment method

### Expected result (*)

1. In app/code/Magento/Braintree/view/frontend/web/js/view/payment/3d-secure.js the property options.additionalInformation should be set and sent to self.threeDSecureInstance.verifyCard

### Actual result (*)

1. In app/code/Magento/Braintree/view/frontend/web/js/view/payment/3d-secure.js the property options.additionalInformation is not set because this.isValidShippingAddress(shippingAddress) fails due to treating shippingAddress.regionCode as a requirement.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by theloveofcode** [comment]
Is anyone working on this?

**Comment by Dren7755** [comment]
I have an Magento 2.4.1 and "paypal/module-braintree-core":"4.2.0"
It's working ok for me when region is empty 
![image](https://user-images.githubusercontent.com/19759530/104926265-9ab71680-59a8-11eb-9577-230f2c46d8e4.png)
