### ISSUE TITLE
Add price including tax to `CartItemPrices` in GraphQL API

### ISSUE THREAD

**Issue by TimonVS** [magento/magento2#29057]
### Description (*)

I'd like to be able to show the price of an individual item including taxes. Currently, you can only retrieve the row total including tax or the price of an individual item excluding tax.

### Expected behavior (*)

Add a field `price_including_tax` to `CartItemPrices`:

```graphql
query {
  cart(cart_id: "<cart id here>") {
    items {
      id
      quantity
      prices {
        # excluding tax
        price {
          currency
          value
        }
        # new field
        price_including_tax {
          currency
          value
        }
        row_total_including_tax {
          currency
          value
        }
      }
    }
  }
}
```

### Benefits

Shopping carts usually show the price of an individual item including taxes, even the default theme in Magento does that.

**Comment by TimonVS** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TimonVS. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TimonVS, here is your [Magento instance](https://i-29057-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29057-2-4-develop.instances.magento-community.engineering/admin_1605](https://i-29057-2-4-develop.instances.magento-community.engineering/admin_1605)
Login: `be5793dd` Password: `f0c0d6c26ec2`
Instance will be terminated in up to 3 hours.

**Comment by mauragcyrus** [comment]
@TimonVS the use cases described seem gear towards administrative API, rather than a storefront API, and you would be better off using the REST APIs for admin-level operations.

**Comment by engcom-Hotel** [comment]
Hello @TimonVS,

We have tried to reproduce the issue in Magento 2.4-develop branch and it is reproducible for us. The amount including tax does not show in the `cart` query through graphql. Hence confirming this issue with label `feature request`.

As per you below statement, I would like to tell you that on the frontend with the Magento Luma theme, the cart is showing price without tax:
> Shopping carts usually show the price of an individual item including taxes, even the default theme in Magento does that.

Please have a look at the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/142007291-5e1acb79-34e8-44e6-8451-8851bdf4a788.png)

Thanks

**Comment by Morgy93** [comment]
"Thankfully" I came across this issue.

The docs state:

>The price of the item before any discounts were applied. The price that might include tax, depending on the configured display settings for cart
>https://devdocs.magento.com/guides/v2.4/graphql/interfaces/cart-item-interface.html#CartItemPrices

But I cannot confirm, the response doesn't change with applied settings.

**Comment by nuzil** [comment]
Maybe this will be usefull
https://github.com/comwrap/Comwrap_GraphQlCartPrices

**Comment by cpartica** [comment]
> "Thankfully" I came across this issue.
> 
> The docs state:
> 
> > The price of the item before any discounts were applied. The price that might include tax, depending on the configured display settings for cart
> > https://devdocs.magento.com/guides/v2.4/graphql/interfaces/cart-item-interface.html#CartItemPrices
> 
> But I cannot confirm, the response doesn't change with applied settings.

but it should

**Comment by cpartica** [comment]
similar issue https://github.com/magento/magento2/issues/33848

**Comment by engcom-Alfa** [comment]
Hi @TimonVS ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest 2.4-develop to retest the case.
In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
