### ISSUE TITLE
Error at reorder for order with no longer existing customer group id.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#29059]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Fresh install
2. Create customer (via Admin Panel)
3. Create customer group 
4. Associate customer (step 2) with recently created customer group (step3)
5. Place order for customer (step 2) (via Admin Panel)
6. Delete customer group (step 3)
7. Reorder order (step 5) (via Admin Panel)

### Expected result (*)

1. After deleting customer group (step 6) customer (step 2) is assigned to default customer group
2. At reorder current customer group is used

### Actual result (*)

1. After deleting customer group (step 6) customer (step 2) is assigned to default customer group
2. At reorder customer group from previous order (which no longer exists) is used
3. Error when quote is saved
![Screenshot_16](https://user-images.githubusercontent.com/60198022/87279570-8249d900-c4f9-11ea-8e55-40132d37364d.png)

### Additional information(*)
Issue is from 

`\Magento\Sales\Model\AdminOrder\Create::initFromOrder` 

More specifically this line here

`$this->getQuote()->setCustomerGroupId($order->getCustomerGroupId());
`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35806` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
Hi, @victortodoran.  Thank you for your report.
Same the problem has already fixed after the merge (https://github.com/magento/magento2/pull/28902).
Discussion of the issue here (https://github.com/magento/magento2/pull/29220)

Please reopen and update if you wish to continue.
Thank you for your collaboration.
