### ISSUE TITLE
Required product attribute cannot be selected in the configurable product

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#2905]
Hello... I think this is a bug.

I have created a configurable product. Then, I added a required dropdown attribute. So far no problem... configurable product and virtual products were added correctly.

However, if I need to edit configurable product (not the virtual ones), the attribute dropdown appears disabled with an empty value, and when I click on "Save", a validation error is shown telling that this value is required. in conclusion, I cannot save the product.

Please correct it. Thanks.

Regards
Jaime

**Comment by Karl456** [comment]
This has already been reported and acknowledged: https://github.com/magento/magento2/issues/2854

**Comment by katmoon** [comment]
Closing as a dupe.
