### ISSUE TITLE
Create configurations: not all configurable attributes are visible

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#29055]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by krishprakash** [comment]
Hi @dverkade.
Kindly provide all the details to reproduce the issue
Preconditions
Steps to Reproduce
Expected and Actual Result

**Comment by dverkade** [comment]
Hi @krishprakash 

I created this ticket and assigned it to me so that I can check that this is reproducible on a clean Magento 2.3 instance. Please don't assign tickets to yourself which are assigned to someone else. Thanks!

**Comment by krishprakash** [comment]
Hi @dverkade. Thank you for your response !!
All details are necessary to verify any issue and as Quality Maintainer of community engineering that's my duty to follow the community guidelines

**Comment by dverkade** [comment]
Yeah, that's why it's assigned to me, because I need to verify it myself and create the description of it. Once I've verified and describe the issue it will be unassigned.

**Comment by dverkade** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3-develop instance for you
