### ISSUE TITLE
upload gif image for product 

### ISSUE THREAD

**Issue by raindropsinfotech** [magento/magento2#29051]
### Preconditions (*)
Magento 2.4

### Steps to reproduce (*)

1. Create a product 
2. Add some gif as an image to the created product 
3. Fill in all required fields -> Save

### Expected result (*)
Gif is shown with animation not as an image not only in admin but in store view also 

### Actual result (*)
Gif is shown as an image without animation 
![Peek 2020-07-14 13-55](https://user-images.githubusercontent.com/60198022/87418171-f22f9080-c5d9-11ea-824c-e5dfbc3aec60.gif)

**Additional Information:**
I have just notice that when i upload product image with gif extension than it show propely in admin but in frontend when cache generate for image it will not show properly i attached some screen shoot look it
![bug-image-gif2](https://user-images.githubusercontent.com/9049432/87018444-de0d1d00-c1ee-11ea-9101-16fb3c18ad63.png)

![bug-image-gif1](https://user-images.githubusercontent.com/9049432/87018450-dfd6e080-c1ee-11ea-81f8-3d63d4df29c4.png)
![Peek 2020-07-14 13-53](https://user-images.githubusercontent.com/60198022/87417908-81887400-c5d9-11ea-8b5f-d28e53c955c3.gif)
**Proposed solution**
Delete cache directory from the image path (only if it`s gif extension)

**Comment by engcom-Lima** [comment]
Hello @raindropsinfotech @sdzhepa
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!
