### ISSUE TITLE
Magento 2.3.4 Advance Reporting Giving 404 Error

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#29065]
### Preconditions (*)

    - Summary - Magento 2.3.4. Advance reporting is not working. It is enabled from the configuration. When I open the advance reporting tab it gives a 404 error. I have satisfied all requirements of advance reporting like public domain, memory, SSL, etc. 
     - Magento 2.3.4, Nginx, MySQL 5.6
     - Login to Admin, Click on Advance Reporting
     - Expected Results - Advance reporting tab opens
     - Actual Result - Receive 404 Error 
1. 
2. 

### Steps to reproduce (*)

1. Login to Admin Dashboard
2. Navigate to Advance Reporting
3. Get 404 Error

### Expected result (*)

1. Advance Reporting should load

### Actual result (*)

1. 404 Error
![image](https://user-images.githubusercontent.com/16966313/87100461-7ec50200-c21a-11ea-8eee-73419e0a99db.png)

**Comment by swathishs** [comment]
@adityag186 -Since the  issue is a duplicate of #24180
Hence moving this ticket to closed.

**Comment by adityag186** [comment]
Hi @swathishs ,

This issue has not been resolved. I have tried it in Magento 2.3.5 according to magento documentation for advance reporting but it still does not work. We have a single currency store on a public url, we have waited several days, cron is running. We have satisfied all documentation for advance reporting but it still does not work
Please assist.
