### ISSUE TITLE
Cart | Freezing for some customers

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#29072]
### Preconditions (*)

1. magento 2.3
2. php 7.2

### Steps to reproduce (*)

1. login
2. add to cart or view cart

### Expected result (*)

1. item to be added to cart
2. cart to ve viewed

### Actual result (*)

1. app or web freez due to no response from server request

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by salehawal** [comment]
i did found a fix for this problem using the below SQL:

`UPDATE quote set is_active = 1 where is_active = 0;`

it works but the issue comes again and i keep fixing it forever, i can do this as a cron job to be run everyday but looking for more professional solution

**Comment by engcom-Delta** [comment]
Hi @salehawal 
Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. 
Thank you for collaboration.
