### ISSUE TITLE
Magento 2.3.3 - freshly installed admin page is disabled and showing a spinner forever

### ISSUE THREAD

**Issue by eakenbor** [magento/magento2#29079]
### Preconditions (*)

1.  Magento 2.3.3
2.  PHP 7.1
3. XAMPP on Windows 10 localhost

### Steps to reproduce (*)

After a fresh Magento 2.3.3 install, login to the admin dashboard. 
I have tried the following workarounds but all failed:
```
php bin/magento setup:upgrade
php bin/magento setup:di:compile    
php bin/magento setup:static-content:deploy -f
php bin/magento c:f    
php bin/magento c:c
```

```
php bin/magento config:set web/secure/use_in_adminhtml 1
```

### Expected result (*)

 I expect the admin page to be accessible and not disabled.

### Actual result (*)

There is a spinning element that appears over the admin dashboard page while the entire page is disabled.
![Dashboard _ Magento Admin (1)](https://user-images.githubusercontent.com/30095266/87223386-daa79c00-c37c-11ea-8da1-0c05d45439bb.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment]
Check browser developer tools console for error message and failed Ajax calls.

**Comment by engcom-Delta** [comment]
Hello @eakenbor 
According to the [Magento requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html) 
Also Magento recommends using PHP 7.3
> Magento is not supported on:
> - Windows OS
> - Mac OS

But you can use a [Virtual Machine](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/optimal-dev-environment.html) and then use Magento as usual.
So I close it.
Thanks for your report!
