### ISSUE TITLE
catalogrule_apply_all locks  indexer_reindex_all_invalid and keeps catalogsearch_fulltext constantly processing, hanging Cron Job

### ISSUE THREAD

**Issue by matthew99** [magento/magento2#29070]
### Preconditions (*)

1. Magento 2.3.5 in developer mode
2. php 7.2 elasticsearch 6.5, mysql 5.6, varnish, redis (also for sessions)(cloudways/digital ocean instance 4GB/2Core)
3. Mirasvit Elasticsearch Ultimate module 
4. Crons configured correctly
5. 2 websites, total of 5 store views, about 1800 products

### Steps to reproduce (*)

1. Everyday at 0:00 catalogrule_apply_all is run (default). Or add it manually to cron_schedule to trigger.

### Expected result (*)

1. catalogrule_apply_all is executed on cron (or trigger manually)
2. product prices are updated, indexes may be reset
3. catalogsearch_fulltext runs once (maybe for all products if default behavior)
4. consequent crons run normally, indexer_reindex_all_invalid should just run
5. consequent reindexation only for items marked 'invalid'
6. Memory useage normal about 2GB

### Actual result (*)

1. catalogrule_apply_all is executed on cron
2. Indexer_reindex_all_invalid is executed in the next minute cron, invalidating all product/category index tables in mysql. Some from debug.log:
2020-07-02 23:00:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"DB_PDO_MYSQL_DDL_catalog_category_product_index_store1_1"}} []
[2020-07-02 23:00:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"DB_PDO_MYSQL_DDL_catalog_category_product_index_store1_2"}} []
[2020-07-02 23:00:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"DB_PDO_MYSQL_DDL_catalog_category_product_index_store1_3"}} []
[2020-07-02 23:00:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"DB_PDO_MYSQL_DDL_catalog_category_product_index_store1_4"}} []
etc. lot of lines.
No error messages.

3. Catalogsearch_fulltext will auto start indexing all products
4. Magento cron:run seems to hang(?)
5. On the following cron runs, all cron schedules are run correctly except indexer_reindex_all_invalid: error in debug.log

main.WARNING: Could not acquire lock for cron job: indexer_reindex_all_invalid [] []
These errors pile up in the hours following. Indexer_reindex_all_invalid will not run again, untill a manual reset.

Then, few minutes below
[2020-07-02 23:32:13] main.WARNING: Could not acquire lock for cron job: indexer_update_all_views [] []
but a while later:
main.INFO: Cron Job indexer_update_all_views is run [] []
this update_all_view **does continue** to run.

Consequent launces of indexer_reindex_all_invalid cause these errors:

[2020-07-02 23:32:13] main.ERROR: Cron Job indexer_reindex_all_invalid has an error: Call to a member function setData() on boolean. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":61079552,"emalloc_start":59318032} [] []

[2020-07-02 23:32:13] main.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /[PATH]/public_html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:362, Error(code: 0): Call to a member function setData() on boolean at /PATH]/public_html/vendor/magento/module-catalog/Block/Product/ListProduct.php:419)"} []
Indexer_reindex_all_invalid will not run again, untill a manual reset.

6. Catalogsearch_fulltext is in a loop, reindexing again and again, 1 after the other (each run takes 8 minutes for me)
7. I notice 'version_id' in table 'mview_state' for row 'catalogsearch_fulltext' no longer incrementing
8. I notice Elasticsearch eating up system resources. Memory >3 GB
9. New products (or product updates) are (as a consequence) not showing in frontend or search.
10. After I manually reset the indexation system, all crons run fine untill the next launch of catalogrule_apply_all

If I then do
  ps aux | grep bin/magento   
I see two stuck cron:run jobs, one always at 0:00, the other > 30 minutes running time)

Workarounds / additional info
Disabling/Reenabling Elasticsearch on server seems to clear the stuck cron jobs.
I can manually reset and reindex from CLI
I can reset the entire indexation by clearing _cl tables and resetting version_id's in mview_state.

I don't know have a clue how or where to fix this. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by matthew99** [comment]
I can't test this on an instance because I can't install extension. Any hint or help is appreciated, as I have no clue what the initial cause is (be it a bug, or not).

**Comment by davidandersson1** [comment]
Hi @matthew99 I have same issue with magento version 2.3.5 with around 400k products and daily night when cron "catalogrule_apply_all" run then after "catalogrule_rule" will take around 7 hours.

Recently I assigned all products to another website, after this issue started, with main website, catalog rule index  taken only 6-7 minutes. but somehow after assigned products to another website, index timing is dramatically increase (especially catalog_rule).

However I can't see any error on logs. really do not know its core bug or how.

Anybody please help! 

Thanks in advance!
David

**Comment by sarjangautam** [comment]
We have recently upgraded to 235 P1 from 233 P1 and this is happening a lot for us. Our trading/online team are making changes in categories and they need to save multiple categories for promotional activities. However, whenever they do so we start getting issue with indexes and products start disappearing from categories in frotend and search. 

During this time we get messages like `report.WARNING: Could not acquire lock for cron job: indexer_update_all_views` and soon product start loosing this products in frontend. This is giving us lot of problem as this is not good customer experience.

**Comment by matthew99** [comment]
Still looking for solution. I keep track of my steps in my blog https://www.vannoortproductions.nl/magento-2-indexer-stuck-at-processing/

**Comment by pmonosolo** [comment]
Having the same issue here. Magento 2.3.3 with large catalog.

**Comment by pmonosolo** [comment]
There is another github issue that might be related:
https://github.com/magento/magento2/issues/26516

**Comment by matthew99** [comment]
I updated my post on  https://www.vannoortproductions.nl/magento-2-indexer-stuck-at-processing/ today.
This is what I wrote

Fingers crossed, I think all works now. This issue seems to have resolved itself and/or after a few actions I did:

- Update to Magento v2.3.6 and extensions to latest versions (Mirasvit Elasticsearch Ultimate 1.0.151)
- Updated to Elasticsearch 7
- Reset & cleared the Elasticsearch indexes in Magento backend (@Mirasvit settings) and changed the Elasticsearch Index Prefix, to be sure that I was working on/monitoring newly generated indexes
- Then I discovered two cron job settings that were still left over from M1 migration in table core_config_date: crontab/default/jobs/log_clean/schedule/cron_expr, crontab/default/jobs/log_clean/run/model
- Since these leftover cron entries were generating errors in cron_schedule, I decided to remove those rows from core_config_data. 

After upgrading, compiling and generating content I once again found my logs flooding with:
_Environment emulation nesting is not allowed error_
Since Mirasvit’s change log mentioned something about the CMS page related to this error, I decided to:

- turn off the search index for CMS (Mirasvit -> Search -> Search Indexes), after that reindex all from cli.
- turn back on the search index for CMS, after that reindex all from cli.

Cleared all cache and behold… no more errors, catalogsearch_fulltext index on ready. Server performance came back as it should be. Don't know what did the trick, but anyway: this seems to have worked for me, I hope it does for you.

**Comment by pmonosolo** [comment]
If anybody is still looking for a solution.

There is a patch for 2.4.3 that supposedly addresses this issue. But it doesnt.

The only way I was able to unstuck it is to kill the indexer process that gets stuck.

I created a Bash script that runs via crontab and kills the stuck indexer. 

`#!/bin/bash
# This script will kill Indexing process which is running for more than 2.5 hours

(PIDS="`ps aux | grep "group=index" | awk '{print $2}'`"

for i in ${PIDS};
do
{
    time="`ps -p $i -o etimes= | awk '{print $1}'`";

    now=$(date +"%T");

    echo "trying to kill $i";

    if [[ $time -gt 12600 ]] ; then
        echo "---------------------------";
        echo "Killing $i";
        echo "Process running for $time";
        echo "Current time : $now";
        kill -9 $i;
    fi
}
done;)|tee -a "/var/www/site/var/log/indexkiller.log"
`

After the indexer is killed, the reindex runs correctly and finishes up. 

Modify the time to match your catalog size.

**Comment by pmonosolo** [comment]
If anybody still looking for solution besides the process killer, they should try this:
https://developer.adobe.com/commerce/php/development/components/indexing/#using-application-lock-mode-for-reindex-processes

This is the only mention of this fix anywhere:
"In case of a failure during the reindexing of a certain indexer, having this mode enabled will return a more accurate status of the indexer. The status can be obtained from the indexer grid in the Admin or through the bin/magento indexer:status command in the CLI."

env.php

`<?php
return [
    'indexer' => [
        'use_application_lock' => true
    ]
];`

+ Add

`MAGE_INDEXER_THREADS_COUNT=(whatever your CPU is capable of)`

**Comment by pmonosolo** [comment]
There is also a good slideshow about indexers in general from Christian Munch:
https://speakerdeck.com/cmuench/magento-2-indexer

**Comment by hammockvienna** [comment]
@pmonosolo Did the "use_application_lock" solve that issue in your instances?
