### ISSUE TITLE
Minicart product name - not covered cases

### ISSUE THREAD

**Issue by Januszpl** [magento/magento2#29075]
### Preconditions (*)
Magento 2.3.5, 2.4

Related to: https://github.com/magento/magento2/pull/13802

### Steps to reproduce (*)

1. Add product with special characters to cart
2. remove ifnot condition (or trigger usage of it in other way) in template https://github.com/magento/magento2/blob/024625e61887a252df56f027e42347d20860b253/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L24-L32
3. open minicart

Issue:
If you use `text: product_name` in https://github.com/magento/magento2/blob/024625e61887a252df56f027e42347d20860b253/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L30 when product name has special characters like double quotes it will render them wrongly.

By default in most cases template will use html binding if product has url.

But this should be replaced by `<span data-bind="html: product_name"></span>` or removed.

### Expected result (*)
![](https://i.gyazo.com/c82e65035817d58420707fa69a695fd2.png)

### Actual result (*)
![](https://i.gyazo.com/ab74848a64622b0ba1b8a5a2db7e81cc.png)

---
Severity: S2/3 ?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37115` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @Januszpl. Thank you for your report. 
The issue has been fixed in magento/magento2#29794 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [9df9db2d742feb1f1e28e9394a437c13a2b5a054](https://github.com/magento/magento2/commit/9df9db2d742feb1f1e28e9394a437c13a2b5a054)

The fix will be available with the upcoming 2.4.2 release.
