### ISSUE TITLE
File js-translation.json is loaded slower or later than other javascript file which contains some texts need to translate so at this time translated texts still not push to storage.

### ISSUE THREAD

**Issue by oxochenxa** [magento/magento2#29088]
Hello,

File js-translation.json is loaded slower or later than other javascript file which contains some texts need to translate so at this time translated texts still not push to storage. When the a.js is loaded it will be parsed and call translate function. translate function will look into storage then find text to translate. Because the translation text still not push to storage so translate function will get nothing then use original text. 
![image](https://user-images.githubusercontent.com/31264868/87287699-9fe06800-c524-11ea-963b-5790065e696e.png)
I must reload page, it translate.
When i want to test, i clear data on local storage
![image](https://user-images.githubusercontent.com/31264868/87287900-d9b16e80-c524-11ea-8be7-4f8009e91b26.png)
How to fix it? I using version 2.3.3

**Comment by krishprakash** [comment]
Hi @oxochenxa. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
