### ISSUE TITLE
Magento not loading layout XML updates added to a subtheme of a global parent theme 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#29084]
I have a Main Theme based on Magento/luma. It is correctly recognized. I configure it to be 'global' under the Admin > Content > Design > Configuration. I have created two websites. I want each website to have its own subtheme based on my Main Theme. I created subtheme1 and subtheme2. They are correctly recognized and I configure them for each website respectively under Admin > Content > Design Configuration.

HOWEVER, if I add xml files changes to my subthemes only, for example in subtheme2/Magento_Theme/layout/default.xml, then these changes are NOT loaded. Magento loads only the main theme set to 'global', it does not load the website-specific themes at all. It does work if I move the default.xml to the maintheme/Magento_Theme/layout/default.xml. Then it works, but the changes cascade to ALL subthemes. 

So the problem is, I can't make SUBthemes to have unique layout XML changes specific to their website. I can only make GLOBAL theme layout changes from the main theme. This defeats the whole purpose of having subthemes! It forces you to create a separate Magento installation instead of doing multi-site.

### Preconditions (*)
1. Magento ver. 2.3.5-p1
2. Ubuntu 18.04, PHP 7.3.19

### Steps to reproduce (*)
1. Clean install
2. Create a theme in /app/design/frontend/MyVendor/mytheme, with a composer.json, registration.php, and theme.xml
3. Make sure to set the parent of this theme as `<parent>Magento/luma</parent> `
4. Go to Admin > Content > Design > Configuration and set the new theme as the global theme
5. Create additional websites, stores and storeviews
6. Create a separate theme for each website, e.g. in /app/design/frontend/MyVendor/mysubtheme1, mysubtheme2
7. Make sure the subthemes have `<parent>Vendor/mytheme</parent>` (i.e., your main theme is the parent of the subthemes)
8. Go to Admin > Content > Design > Configuration and set the new subthemes for the website (see as in Screenshot)
9. Try to make XML changes by adding a default.xml file in your subtheme's folder under Magento_Theme/layout/default.xml

### Expected result (*)
1. The expected result is that XML layout file changes I add to my subthemes should show up for my subthemes
2. Magento should read the XML changes for the website-specific subtheme

### Actual result (*)

1. In practice, only the XML layout changes made to the global theme show up (but they cascade to ALL subthemes; I should be able to make website-specific XML changes, instead of always global. What is the point of having subthemes if you cannot actually use them to make SUB themes?)
2. Magento only reads XML changes for the installation-wide global theme, but not for the website-specific subthemes

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

![subtheme](https://user-images.githubusercontent.com/33515225/87280255-3b0c1a00-c4f2-11ea-83ca-fe9b426e0368.png)

**Comment by Appmerce** [comment]
Additional info: this presumably has something to do with a multi-domain setup. When I install a new site with all websites on a single domain, there's no problem. But if I split the websites accross separate domain (single Magento install), I get the aforementioned problem.

**Comment by kerlama** [comment]
I can confirm the same issue on 2.4

**Comment by fschwan** [comment]
Same issue on 2.4.3-p1 installation with 2 stores (domainA.com = base & domainB.com = child).
Layout updates to child theme doesn't take affect.
Is there any solution or workaround?

**Comment by magefast** [comment]
Seems bug exist with version 2.4.5-p5

fix https://www.pauldonnelly.net/article/2020/how-to-fix-magento-2-theme-layout-xml-not-working

Also, _code of theme_ now is -  **My/theme** 
NOT old **My_theme**
