### ISSUE TITLE
Magento 2.4 instance

### ISSUE THREAD

**Issue by achleitner** [magento/magento2#29086]
Hello,
sorry if I'm not following the rules here but how can I get a dev instance to test something?

give me 2.4-develop instance

**Comment by achleitner** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @achleitner. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by achleitner** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @achleitner. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by achleitner** [comment]
give me 2.4-develop instance
