### ISSUE TITLE
Can I change tittle of custom options based on store view

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#2908]
I´ve add another language in store, and when change for a particular store view language, then custom options products fails (All store views works fine), and can´t chane anything.
![custom_options_store_view](https://cloud.githubusercontent.com/assets/16081377/12156170/a709c7c2-b4c9-11e5-8a6f-1be6e35637b9.jpg)

**Comment by katmoon** [comment]
Hi,

Thanks for reporting the issue.
Internal ticket is MAGETWO-47698

**Comment by GeromeF** [comment]
Same problem for me running 2.0.2, no fix available at this time ??

**Comment by katmoon** [comment]
Hi @GeromeF 

I think the issue should be fixed approximately within a month.

**Comment by mktudock** [comment]
Is this issue still not fixed?

**Comment by gaurangjadav** [comment]
Hello 

Does this issue get fixed , or what could be the easy fix from code please help..!
we running live website with Magento 2.0.6.

Thanks

**Comment by audexpro** [comment]
Any news on this issue?

**Comment by veloraven** [comment]
This issue has already been fixed in develop branch.
Internal ticket for ver. 2.1 - MAGETWO-57153 - fix will be available in one of the nearest releases.
We were not able to reproduce this issue for ver. 2.0.

**Comment by veloraven** [comment]
I'm closing this issue as a duplicate for #5885 - as there are more comments and info in that one.
