### ISSUE TITLE
The frontend product zoom has a poor usability with the small images on a wide PC screen

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2909]
![](https://mage2.pro/uploads/default/original/1X/8351bbea69827cb70bc23eb923dad0613a42b16f.png)

**Comment by belbiy** [comment]
@dfediuk , can you be more specific about "poor usability" remark? Did you wanted that small image to scale, or something else?

**Comment by MomotenkoNatalia** [comment]
@dfediuk could you please clarify the information you provided considering @belbiy question?

**Comment by MomotenkoNatalia** [comment]
As there are no new updates from reporter, issue will be closed.
