### ISSUE TITLE
Contact Email not send to the store email address

### ISSUE THREAD

**Issue by chequille** [magento/magento2#29096]
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Using contact standard form to send a email to the store owner from frontend
2. URL: domain/contact

### Expected result (*)

1. The email should be sent to store owner (EMail address set in General Email Address I think) 

### Actual result (*)

1. Email is only sent to the email address customer is giving in the contact form.
2. EMail to store owner is not sent. Maybe it its one of the other email addresses which can be set for the store, but as all of them are the same, I can say, that the email is definetely not sent.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Serializator** [comment]
Hi @chequille,

I wasn't able to reproduce the issue.

I locally used an empty Magento 2.3.5-p1 installation to try and reproduce the issue. I did this locally so that I could use MailHog to verify the e-mail was sent.

When I submitted the contact form and checked MailHog I saw that the e-mail was successfully sent from Magento.

**To:** hello@example.com ("Stores > Configuration > General > Contacts > Send Emails To")
**From:** custom2@example.com ("Stores > Configuration > General > Store Email Addresses > Custom Email 1 > Sender Email")
**Reply To:** julian@weprovide.com

<img width="1792" alt="Screenshot 2020-07-13 at 17 46 46" src="https://user-images.githubusercontent.com/7153670/87324797-e9cf4b00-c530-11ea-9d40-fb40c287dba7.png">

**Comment by chequille** [comment]
Hi,
yes this is correct, it is sent to the email address which you type in the contact form, but it is not sent to custom2@example.com.

The contact form is a requiry to the shop and of course the shop should get this inquiry as well and not only the visitor on the webpage.

Is it clear now?

**Comment by chequille** [comment]
WIth other words. 
Two emails must be sent by this.

One as a kind of confirmation to the user filling the form with his request and the second one must go the the shop people to be able to take care about this request.

And exactly the second email to the shop stuff is not sent.

**Comment by Serializator** [comment]
Hi @chequille,

"it is sent to the email address which you type in the contact form", this is false. "hello@example.com" is the e-mail configured under "Stores > Configuration > General > Contacts > Send Emails To", not the e-mail which was submitted by the user.

Looking at the implementation of the form submission I can't say that it is expected to send two e-mails (the e-mail to the store owner and a confirmation e-mail to the user).

Is this a feature request then?

Kind regards,
Julian

**Comment by engcom-Delta** [comment]
Hi @chequille thank you for your report.
When customer submit contact form, email is send mail that was set in `Send Emails To`. And form from contact us page is sent from mail that was set in `Email Sender`
Here is my results same as [here](https://github.com/magento/magento2/issues/29096#issuecomment-657641682):

- Set `Send Emails To` 
![image](https://user-images.githubusercontent.com/51681379/105005507-17480480-5a3e-11eb-97da-fd23914c7430.png)

- `Email Sender` is without changes and is `custom2@example.com`
![image](https://user-images.githubusercontent.com/51681379/105005711-57a78280-5a3e-11eb-9114-34691cd79c61.png)

- Customer `maguser@yopmail.com` submit contact us form
![image](https://user-images.githubusercontent.com/51681379/105005808-773eab00-5a3e-11eb-821c-7afbf85ed0b5.png)

**Result:**
:heavy_check_mark: Email sent to the `mage2contact@yopmail.com`("Stores > Configuration > General > Contacts > Send Emails To") from `custom2@example.com`("Stores > Configuration > General > Store Email Addresses > Custom Email 2 > Sender Email")
:heavy_check_mark: Email contains `Reply To` section with customer email
![image](https://user-images.githubusercontent.com/51681379/105006227-077cf000-5a3f-11eb-8ae7-8a07aa3ba133.png)
![image](https://user-images.githubusercontent.com/51681379/105006277-19f72980-5a3f-11eb-86d6-8121bd9c95c7.png)


This behavior is not an issue but it could be improved
Please feel free to create new ticket in [feature request repo](https://github.com/magento/community-features/issues) for further discussion
