### ISSUE TITLE
[MFTF] Group: Edit Customer addresses

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29106]
Need to cover with MFTF tests next manual test cases from "[Login As Customer](https://studio.cucumber.io/projects/163172)" project in Cucumber(HipTest):
**UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)

1. ["Admin user login as customer and edit customer's address"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4196870) - depends on https://github.com/magento/magento2-login-as-customer/issues/54, https://github.com/magento/magento2-login-as-customer/issues/57
2. **(Only part related to this case)** ["Verify that 'Login as customer Log'  record information about using 'Login as customer' functionality properly"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4184870) - depends on https://github.com/magento/magento2-login-as-customer/issues/54, https://github.com/magento/magento2-login-as-customer/issues/57

**Note 1**: Manual test cases could be changed after this task https://github.com/magento/magento2-login-as-customer/issues/36

**Note 2:** _Due to HipTest(Cucumber Studion) workflow and specific each new user should be invited first. If you want to have access please ping @sdzhepa here with a comment or directly in community slack [@SerDzh ](https://magentocommeng.slack.com/archives/DDBDB070W)_

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Done
PR https://github.com/magento/magento2-login-as-customer/pull/107
