### ISSUE TITLE
If multiple stores exist under a specific website, user is logged into the default website for that store

### ISSUE THREAD

**Issue by naydav** [magento/magento2#29101]
### Update on June 24 2020
After triaging and discussion with Product Manager all cases from
- One WebSite but several stores: https://github.com/magento/magento2-login-as-customer/issues/58#issuecomment-645346480
- Several Websites: https://github.com/magento/magento2-login-as-customer/issues/58#issuecomment-645436814

Were defined new requirements that should help to fix and clarify expected results
1. Only Store Level(not store view) should be available in Manual-Selector for Admin 
_note: Admin should be logged on the selected store, store-view he/she can select from Storefront UI_
2. If Website/Store is not allowed by any reason for Customer to log in on Storefront - Manual-Selector should not allow to select/click this option

---

Original description https://github.com/magefan/module-login-as-customer/issues/8
When multiple stores exist under a specific website, user is logged into the default store instead of the correct store.

###  Preconditions
- Magento 2.4-develop installed with Login as Customer
- A website with multiple stores
- Login as Customer is enabled:
- - Store View To Login To=Auto-Detection/Manual Selection
- Stores->Configuration->Web->Url Options->Add Store Code to Urls=No
- A Customer attached to a different store than the default in the Website

###  Steps to reproduce
- Go to Admin -> Customers -> All Customers
- Click "Login as Customer" on the Customer with a different store than the default

###  Expected result
 Customer is logged in on the front end in the correct store

###  Actual result
Customer is logged into the default store for the Website (one with the lowest sort order)

### Additional Information
Detailed use cases and results:
- One WebSite but several stores: https://github.com/magento/magento2-login-as-customer/issues/58#issuecomment-645346480
- Several Websites: https://github.com/magento/magento2-login-as-customer/issues/58#issuecomment-645436814

**Comment by engcom-Foxtrot** [comment]
Fixed in https://github.com/magento/magento2-login-as-customer/pull/179 and merged in https://github.com/magento/magento2ce/pull/5993.
