### ISSUE TITLE
[MFTF] Group: Permissions and ACl

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29108]
Need to cover with MFTF tests next manual test cases from "[Login As Customer](https://studio.cucumber.io/projects/163172)" project in Cucumber(HipTest):

**UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)

Depends on dev task: https://github.com/magento/magento2-login-as-customer/issues/55 will be changed only Text/labels

1.[ "Login into Magento Admin panel as user that does not have access to 'Login as customer' button"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4169464) - depends on https://github.com/magento/magento2-login-as-customer/issues/54
2. ["Login into Magento Admin panel as user that does not have access to 'Login as customer' section in System Configuration"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4183982) - depends on https://github.com/magento/magento2-login-as-customer/issues/55
3. ["Change admin user's access to 'Login as customer Log'"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4184074) - depends on https://github.com/magento/magento2-login-as-customer/issues/55, https://github.com/magento/magento2-login-as-customer/issues/54
4. ["Change Admin user's access to 'Login as customer' button"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4184644)	- depends on https://github.com/magento/magento2-login-as-customer/issues/55, https://github.com/magento/magento2-login-as-customer/issues/54

**Note 1**: Manual test cases could be changed after this task https://github.com/magento/magento2-login-as-customer/issues/36

**Note 2:** _Due to HipTest(Cucumber Studion) workflow and specific each new user should be invited first. If you want to have access please ping @sdzhepa here with a comment or directly in community slack [@SerDzh ](https://magentocommeng.slack.com/archives/DDBDB070W)_

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Done
PR https://github.com/magento/magento2-login-as-customer/pull/107
