### ISSUE TITLE
[MFTF] Group: Availability of UI elements if module enable/disable

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29102]
Need to cover with MFTF tests next manual test cases from "[Login As Customer](https://studio.cucumber.io/projects/163172)" project in Cucumber(HipTest):

1.  ["Verify that UI elements are not shown if 'Login as customer' functionality is disabled"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4149567)
2. ["Verify that 'Login As Customer Log' not shown if 'Login as customer' functionality is disabled"]( https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4150296)
3. ["Verify that UI elements are present and links are working if 'Login as customer' functionality enabled"](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4155456) - depends on:
https://github.com/magento/magento2-login-as-customer/issues/15
https://github.com/magento/magento2-login-as-customer/issues/17

**Note 1**: Manual test cases could be changed after this task https://github.com/magento/magento2-login-as-customer/issues/36

**Note 2:** _Due to HipTest(Cucumber Studion) workflow and specific each new user should be invited first. If you want to have access please ping @sdzhepa here with a comment or directly in community slack [@SerDzh ](https://magentocommeng.slack.com/archives/DDBDB070W)_

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Done
PR https://github.com/magento/magento2-login-as-customer/pull/107
