### ISSUE TITLE
[MFTF] Group: Notification message about admin actions for order Admin/Strorefront

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29103]
Need to cover with MFTF tests next manual test cases from "[Login As Customer](https://studio.cucumber.io/projects/163172)" project in Cucumber(HipTest):

Will be defined after: https://github.com/magento/magento2-login-as-customer/issues/36

Depends on dev task: https://github.com/magento/magento2-login-as-customer/issues/28

**UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)

1. [Admin actions are logged and available in Admin Panel on Order Review page (notification section)](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4484362) - depends on https://github.com/magento/magento2-login-as-customer/issues/28
2. [Admin actions are logged and available on Storefronted from Customers My Account (notification section)](https://studio.cucumber.io/projects/163172/test-plan/folders/1204738/scenarios/4484515) - depends on https://github.com/magento/magento2-login-as-customer/issues/28

**Note 1:** _Due to HipTest(Cucumber Studion) workflow and specific each new user should be invited first. If you want to have access please ping @sdzhepa here with a comment or directly in community slack [@SerDzh ](https://magentocommeng.slack.com/archives/DDBDB070W)_

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Done
PR https://github.com/magento/magento2-login-as-customer/pull/107
