### ISSUE TITLE
 Message about choosing options for item is shown on "Thank you for your purchase!" page

### ISSUE THREAD

**Issue by engcom-Lima** [magento/magento2#29115]
This bug is not in LaC functionality but in Magento core.
Can be repro without LaC if disable caches and place order with Configurable

### Preconditions (*)

1. Magento 2.4-develop
2. Login as Customer enabled
3. Customer 'John Doe' is created
4. Configurable product is created (Drop-down attribute type)

### Steps to reproduce (*)

1. Go to Magento Admin -> Customers -> All Customers and open customer 'John Doe' account to edit
2. Click on Login as Customer (twice)
3. Open Category page with configurable product
4. Click "Add to Cart" button on the configurable product
5. Select options -> Add to Cart
6. Place Order

### Expected result (*)

No message about choosing options

### Actual result (*)
Message about choosing options for item is shown on "Thank you for your purchase!" page

![Login](https://user-images.githubusercontent.com/60198022/83901155-f955ba00-a762-11ea-8373-c92f0c6e16e4.png)

**Edit:** Gift Cart with configurations  has the same problem

**Comment by engcom-Delta** [comment]
Issue is not reproducible on the latest 2.4-develop according testing scenario from [comment](https://github.com/magento/magento2/issues/29115#issuecomment-646081743)
**Result:**
:heavy_check_mark: No message about choosing options on "Thank you for your purchase!" page
![Peek 2021-02-25 16-21](https://user-images.githubusercontent.com/51681379/109167070-0c436b00-7786-11eb-89b3-d05ab414c374.gif)
