### ISSUE TITLE
"Login as Customer" functionality should be enabled by default 

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29112]
### Preconditions (*)

1. Install clear Magento instance with "Login as Customer" functionality

### Steps to reproduce (*)

1. Login to Admin Panel
2. Go to _STORES > Configuration > CUSTOMERS >Login as Customer_
3. Open section "Login as Customer Settings"

### Expected result (*)

1. Functionality is Enabled by default
2. Enable Extension = YES

### Actual result (*)

1. Functionality is DISABLED by default
2. Enable Extension = NO

**Comment by naydav** [comment]
Merged with https://github.com/magento/magento2-login-as-customer/pull/194
