### ISSUE TITLE
Admin cannot login as customer in two different customers account 

### ISSUE THREAD

**Issue by engcom-Lima** [magento/magento2#29119]
### Preconditions (*)

1. Magento 2.4 CE
2. Login as Customer enabled
3. Two customers are created

### Steps to reproduce (*)

1. Go to Magento Admin -> Customers -> All Customers and open the first customer`s account to edit
2. Click on Login as Customer (twice)
3. Admin redirected to store view and login as the customer
4. Go to Magento Admin -> Customers -> All Customers and open the second customer`s account to edit
5. Click on Login as Customer (twice)

### Expected result (*)

1. Admin redirected to store view and login as the customer

### Actual result (*)

1. Admin redirected to store view and not login as Customer because redirected on the "Customer Login" page
![bandicam-2020-06-26-15-03-34-219(1)](https://user-images.githubusercontent.com/60198022/85860353-532c2b80-b7c7-11ea-8e54-949a02147453.gif)

**Comment by naydav** [comment]
Merged with https://github.com/magento/magento2-login-as-customer/pull/193

**Comment by CUTTRHOAT** [comment]
@naydav greetings, can you provide an updated link for the PR? this one seems outdated.
Thanks
