### ISSUE TITLE
 Customers should be able  to enable/disable Admin "remote shopping assistance"

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29113]
As a merchant I want to require my customers to choose if Login as Customer can be used on their account so that I can respect their preferences for their online account.

[MoSCoW](https://en.wikipedia.org/wiki/MoSCoW_method)
Must have

**Current State**
The ability to Login as Customer can be restricted via Admin Roles for particular admin users. Using the Admin Roles it can also be restricted to particular websites in a multi-store configuration. However, it is not possible to disable Login as Customer on a per-customer basis.

**Business Value**
For a variety of reasons, customers may not want merchant admin users to log in to their storefront account. To respect the privacy and choices of these users, the ability to log in to a customer's account should be an opt-in permission.

**UX design/mockups**
- [Intro 8: chapter Opt-in/out](https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/444b7f22-78d1-4461-8e6a-802fa2a879f6/Intro-8)

**AC**
* When creating a New Customer Account from the storefront, the user is prompted to opt-in for Login as Customer permission
  * Default state of checkbox is unchecked (customer does not give permission)
  * Tooltip appears next to option with additional explanation shown if user clicks/taps on tooltip
  * User can click/tap a second time to hide tooltip from view
* When viewing 'Account Information' menu item in My Account as a logged-in customer, user can change opt-in setting
  * Tooltip appears next to option with additional explanation shown if user clicks/taps on tooltip
  * User can click/tap a second time to hide tooltip from view
  * User must click 'Save' button to save any changes to opt-in setting 
* When viewing a customer account from the admin panel, admin user can change opt-in setting under 'Account Information' tab
  * Tooltip appears next to option with additional explanation shown if user clicks/taps on tooltip
  * User can click/tap a second time to hide tooltip from view
* When admin user with permission to Login as Customer clicks 'Login as Customer' link in the admin panel and the customer has not opted-in, a modal window appears with information on why the admin user cannot login to this customer account
  * Window can be closed by clicking X in top right of modal or clicking 'Close' link in the modal
* Merchant can adjust title for setting and wording used in tooltip in admin settings
  * Under `Stores>Configuration>Customers>Login as Customer`
  * Title and tooltip are two different settings
  * Settings are responsive to website scope
  * Use System Value is checked by default
* Title of option, tooltip, and admin modal window are all translatable strings
* Opt-in permission state can be viewed and modified using Customer API
  * `GET    /V1/customers/:customerId`
  * `POST   /V1/customers`
  * `PUT    /V1/customers/:customerId`
  * `PUT    /V1/customers/me`
  * `GET    /V1/customers/me`
* ACL with permission should be added for this option. It should be available as a child for "Login as Customer" ACL resources in tree
  * [ ] "Change customer opt-in preference"

**Out of Scope**
* Opt-in setting does not affect orders placed from the admin panel. Admin users with permission to place customer orders from the admin panel can place orders for any customer

**Exact Wording for Options**
* Opt-in permission: `Allow remote shopping assistance`
* Tooltip text: `This allows merchants to "see what you see" and take actions on your behalf in order to provide better assistance.`
* Modal title: `Login as Customer not enabled`
* Modal text: `The user has not enabled the “Allow remote shopping assistance” functionality. Contact the customer to discuss this user configuration.`
* Modal action button: `Close`
* Name of title setting in admin panel: `Title for Login as Customer opt-in checkbox`
* Name of tooltip setting in admin panel: `Login as Customer checkbox tooltip`

**Comment by keharper** [comment]
Does this affect the GraphQL mutations for creating/updating a customer? (createCustomerV2 and updateCustomerV2 in 2.4.1.)

**Comment by onepack** [comment]
Please, with all due respect but this function is only used when customers are stuck. Most of these customers have no idea and now you have to talk them through a list of steps to get this setting done.
By the way I just got a new customer that has a bought theme that doesn't have this setting present in the frontend for customers.
So you-re stuck unless you enter their ID directly into the database.

I will log a new request to make this a system setting.
Make Login as Customer:
Drop down: Opt-in/ opt-out/ Available/ Not Available.

**Comment by Eddcapone** [comment]
Our data protection officer told us that this feature is very questionable from a data protection perspective. I don't know the reason though, im just the developer. Is there a easy way to completly remove it?

**Comment by broeder** [comment]
How can I remove this ?

**Comment by Eddcapone** [comment]
There is an option in Shop -> Configuration -> Customer -> Login as Customer

**Comment by prashantvictory** [comment]
When we remove it from "There is an option in Shop -> Configuration -> Customer -> Login as Customer" it starts giving error on the front-end register form, see attached. 
<img width="608" alt="Screenshot 2021-06-04 at 12 20 19" src="https://user-images.githubusercontent.com/297915/120758504-8fb3eb80-c52f-11eb-8ed0-969a77c9a466.png">

In this theme file: /static/version1622786918/theme/frontend/en_GB/Magento_LoginAsCustomerAssistance/js/opt-in.js

How we can fix this?

**Comment by robbielove** [comment]
It would be beneficial to introduce a setting to bypass the "Login as Customer" feature entirely for development purposes. This feature, while useful, can hinder the testing process when developers need to impersonate specific customers, particularly when testing with numerous customer accounts. It's crucial for Magento to acknowledge the diverse needs of its user base by offering an option to disable this feature globally without having to toggle the setting for each customer individually.

Moreover, the current opt-in setup may pose a challenge for customers seeking assistance but struggle to locate and enable this option. Having this feature enabled by default could alleviate such hurdles, allowing for immediate support, while tech-savvy customers would likely find it straightforward to opt-out if desired. This approach strives for a balanced solution, catering to both ends of the user spectrum, in contrast to the existing setup which doesn't favor either. This amendment would not only enhance the user experience but also expedite the development and testing processes, urging a reconsideration of the current configuration
