### ISSUE TITLE
Incorrect position of Login as Customer Log

### ISSUE THREAD

**Issue by VasylShvorak** [magento/magento2#29111]
### Preconditions (*)

1. Magento 2.4-develop
2. Login as Customer is enabled

### Steps to reproduce (*)

1. Go to backend

### Expected result (*)

1. https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/87f8df4a-baae-4830-8080-04b7bda23670/Log-admin-3
![image](https://user-images.githubusercontent.com/26908019/81053564-f484b880-8ecd-11ea-8dd9-7b9b0527ddf6.png)

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/26908019/81053397-ac659600-8ecd-11ea-8ea0-6fe42c68d929.png)

**Comment by gulshanchitransh** [comment]
#dmcdindia2020

**Comment by engcom-Bravo** [comment]
Hi @VasylShvorak,

 As per this comment https://github.com/magento-commerce/magento2-login-as-customer/pull/141#discussion_r423658590 We are closing this issue.

Thanks.

**Comment by andrewbess** [comment]
> Hi @VasylShvorak,
> 
> As per this comment https://github.com/magento-commerce/magento2-login-as-customer/pull/141#discussion_r423658590 We are closing this issue.
> 
> Thanks.

Hello @engcom-Bravo 
The community don't see information by provided link
Could you please add screenshot
Thank you in advance.
