### ISSUE TITLE
Magento\Authorization\Model\ResourceModel\Rules missing update method

### ISSUE THREAD

**Issue by adeptofvoltron** [magento/magento2#29128]
Basically in [Rules Model](https://github.com/magento/magento2/blob/fa6d291646b1ca0ebc0ebd3798ec8aaae634d486/app/code/Magento/Authorization/Model/Rules.php#L61) is used "update" method from the resouceModel. However it was never declared in [Rules Resource Model](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/ResourceModel/Rules.php)

### Preconditions (*)

I discovered in on magento 2.3. But is still appear in Magento 2.4
Magento 2.4-develop

### Steps to reproduce (*)

just use anywhere "update" method from Rules Model

### Expected result (*)

Not having a fatal error would be nice

### Actual result (*)

PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Authorization\Model\ResourceModel\Rules::update() in /var/www/magento/vendor/magento/module-authorization/Model/Rules.php:61

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adeptofvoltron** [comment]
Easiest way to remove an issue? remove `\Magento\Authorization\Model\Rules::update`, probably no module use it as far as it is broken anyway.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38993` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
