### ISSUE TITLE
WEBAPI: option to create an individual address for customer and return 1 addressId (request)

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#2912]
When we send a new address (billing or shipping to Magento (by SOAP api)  for a customer we store the addressId in the ERP system. 

With the new functions it is not possible anymore to create one specific address for a customer and get 1 addressId returned. Can you add this back again?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/WEBAPI-option-to-create-an-individual-address-for-customer-and/idi-p/44769).
