### ISSUE TITLE
js-translation.json only digests phrases that are set on $|jQuery as jquery variable and not when requirejs defines something else for jquery 

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#29125]
### Preconditions (*)

1. affected version  2.3 , 2.4 

### Steps to reproduce (*)

1. add any localisation to a js file where jquery is assigned to any other variable named $ or jQuery (for example jquery or any random string developers imagine) . For example  change  $.mage.__('phrase to localise'),  jquery.mage.__('phrase to localise'), 
2. add a string to locale file either in module or in theme context 
3. clear cache,  var/view_preprocessed and also all pub/static/*/*/js-translation.json files (As those are not cleared automatically )   
4. see the part in frontend you expect to be localised , it's not 

reason for this is that locale string patter defines the library prefix variable as a part of the pattern where it should be enough to just match .mage.__( as a prefix pattern 

https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/app/code/Magento/Translation/etc/di.xml#L69

### Expected result (*)

1. developer expects to have freedom to name their requirejs dependencies how they please or even require multiple versions of jquery (or any other lib)  at the same time etc 

### Actual result (*)

1.  localisation is not applied

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by karangar** [comment]
Same problem I am facing in the 2.4.0

**Comment by mrtuvn** [comment]
Seem this problem still need more discuss for properly solutions! I can admit translate in magento still too overwhelmed and sometimes  we can't predictable how it should work
