### ISSUE TITLE
Magento 2.3.5 - Configurable product detail page showing blank page on frontend if product have 1000+ associate products.

### ISSUE THREAD

**Issue by iovistainc** [magento/magento2#29124]
### Preconditions (*)

1. Magento Version:2.3.5-p1
2. MySQL 5.7
3. Apache Webserver
4. Elasticsearch engine 7.x

### Steps to reproduce (*)

1. Create Configurable Product and add more then 1000+ associate simple/virtual products.
2. Go to Product detail page for that product.

### Expected result (*)

1. Product details page showing properly with all options.

### Actual result (*)

1. Blank product page showing.
2. If I remove option wrapper from layout file then the Product page is showing properly.
3. There isn't any error showing in log file.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hello @iovistainc 
Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop and 2.3.5-p1
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/60198022/87804565-b8ba8780-c85c-11ea-9d41-dd38e74bedf6.png)
Please check memory_limit in php.ini
It would be great if you could add a screenshot of a blank product page

**Comment by iovistainc** [comment]
Hello @engcom-Lima,

I have attached a link of the screenshot of blank product page and memory_limit is set to 756M.

https://tinyurl.com/yy4xxrvh

**Comment by engcom-Lima** [comment]
Hello @iovistainc 
Try to set `memory_limit` to 2G and also increase `max_execution_time` to 3000. It works for me

**Comment by iovistainc** [comment]
Hello @engcom-Lima 

I have set `memory_limit` to 4096M and set `max_execution_time` to 18000 and still not working.
Also, there isn't any error log into Apache, MySQL, and Magento itself.
Is there any way I can print any kind of error log?

**Comment by engcom-Lima** [comment]
@iovistainc 
In this case, `memory_limit` can be set to 4G
Also make sure the value is changed in .user.ini

> Is there any way I can print any kind of error log?

Yes. Set `error_reporting` to `E_ALL` and `display_errors` to` 1`` in `php.ini`. Save and restart Apache
Make sure that the debug mode is enabled in the backend. Go to Stores -> Configuration -> Advanced -> Developer -> Debug and set “Yes” to Log to File. 
Set Magento store in [developer mode.](https://devdocs.magento.com/guides/v2.4/config-guide/bootstrap/magento-modes.html)
There many ways to do it. More info [here](https://devdocs.magento.com/cloud/project/log-locations.html)

**Comment by hostep** [comment]
@iovistainc: we had a similar issue and https://github.com/magento/magento2/commit/3b611a7cc0040c9e5731cbc8e2080c2adb205d86 solved it for us, maybe this helps in your case as well?

**Comment by engcom-Lima** [comment]
Hello @iovistainc @hostep I cannot reproduce this issue on 2.4-develop. 
@iovistainc Try to use https://github.com/magento/magento2/commit/3b611a7cc0040c9e5731cbc8e2080c2adb205d86 Maybe it helps you to solve the issue

**Comment by hostep** [comment]
@engcom-Lima, in our particular case, I think it only happened when you use Apache with php-fpm. If I remember correctly, the issue has something to do with the explanation written on [this blogpost](https://maxchadwick.xyz/blog/http-response-header-size-limit-with-mod-proxy-fcgi).
https://github.com/magento/magento2/commit/3b611a7cc0040c9e5731cbc8e2080c2adb205d86 is reducing the amount of headers sent from Magento to the webserver, so in our case it helped fixing this issue.

**Comment by iovistainc** [comment]
@hostep, @engcom-Lima 

In my staging instance, this issue is solved by turning off Move JavaScript To Page Bottom, and in my staging site it's working properly after turning off this setting but in My live site after turning off this setting still, this issue is not resolved. And I already tried https://github.com/magento/magento2/commit/3b611a7cc0040c9e5731cbc8e2080c2adb205d86 patch but still nothing happens.

**Comment by engcom-Lima** [comment]
@iovistainc I cannot reproduce this issue on 2.3.5-p1. 
Have you try to run cron and reindex `php bin/magento index:reindex`
![Screenshot_44](https://user-images.githubusercontent.com/60198022/88061868-bfa10d00-cb70-11ea-87f6-0dad2756ca2d.png)
![Peek 2020-07-21 16-35](https://user-images.githubusercontent.com/60198022/88062074-00992180-cb71-11ea-9f50-376cb02acc6f.gif)

What is written in your logs?

**Comment by iovistainc** [comment]
Hello @engcom-Lima 

I have solved this issue as this issue is causing by one of our third-party extensions which is used for Javascript Defer.

Thanks for your help.

**Comment by engcom-Lima** [comment]
@iovistainc Closed according to the [comment](https://github.com/magento/magento2/issues/29124#issuecomment-662303825)
