### ISSUE TITLE
No order comments are created when admin is logged in as customer and place order with Multiple Addresses

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#29122]
### Preconditions (*)

1. Magento 2.4-develop(branch module-login-as-customer)
2. Login as Customer is enabled
3. Customer is created with two addresses
4. Simple product is created

### Steps to reproduce (*)

1. Go to Magento Admin -> Customers -> All Customers and open customer account to edit
2. Click Login as Customer link
3. Click Login as Customer button in pop-up window
4. Add simple product with Qty=2 to cart
5. Go to Shopping Cart page
6. Click Check Out with Multiple Addresses
7. Choose different addresses for Send To on Ship to Multiple Addresses page
8. Place order
9. Open last created orders

### Expected result (*)

1. Section About Your Order is shown with note "Order Placed by Store Administrator" 

### Actual result (*)

1. No comment that order was placed by admin
![Peek 2020-07-03 11-22](https://user-images.githubusercontent.com/51681379/86452034-60e03480-bd24-11ea-9adc-9402a7e348d6.gif)

Note: No comments in Notes for this Order section for appropriate orders in admin panel
![image](https://user-images.githubusercontent.com/51681379/86452351-d6e49b80-bd24-11ea-9a3d-29ec4a17f3bc.png)

**Comment by naydav** [comment]
Merged with https://github.com/magento/magento2-login-as-customer/pull/192
