### ISSUE TITLE
Integrated Magento xml/csv

### ISSUE THREAD

**Issue by sportmma** [magento/magento2#29131]
How better to send products to magento 2? By using the API through a external application that only sends parameters that have changed when updating products to magento? Or by xml/csv? My xml file updates every 15 minutes. Is Magento more overloaded when updating via xml/csv than with an external application? Are the parameters that have changed only updated? Ultimately, Magento will be connected to 10-15 wholesalers, so I want to avoid overloading Magento when all wholesalers start updating every 15-30min.

**Comment by krishprakash** [comment]
Hi @sportmma. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
