### ISSUE TITLE
404 error getting product

### ISSUE THREAD

**Issue by bas24** [magento/magento2#29132]
### Summary (*)

Hi,
Have some lines in stripe logs which have problems to debug.

200 OK    POST   /v1/products   7/14/20, 12:50:06
200 OK    DELETE    /v1/products/prod_He9d4RyWqaIzLX    7/14/20, 12:50:06 PM
404   GET /v1/products/prod_He9d4RyWqaIzLX  7/14/20, 12:50:07 PM

As I understand plugin creates temporaly the product for cart, but delete it in a moment, than trying to get created product and receives 404 error. With test environment works great without any errors. Nothing in logs related to Stripe.
Environment is live, webhooks accessible and Live Webhooks Signing Secret is placed.
Let me know please any ideas how to find what is wrong

Magento version is 2.3.5
Stripe addon installed with Composer

**Comment by krishprakash** [comment]
Hi @bas24. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
