### ISSUE TITLE
Cannot extract database .gz file created by scheduled backup

### ISSUE THREAD

**Issue by brendanmckeown** [magento/magento2#2915]
I have scheduled backups enabled, with the "database and media" type selected.  On schedule, the system creates a backup file in the `/var/backups` directory, e.g. `1452176641_media.tgz`.  When I extract this file on the command line, using: `tar -xzf 1452176641_media.tgz`, I see a `pub` and `var` directory. `pub` contains the media files as expected.  `var` contains what looks like an archive of the database, e.g. `1452176641_db.gz`.  However, when I try to extract this file using `gzip -d var/1452176641_db.gz`, gzip throws an error: `gzip: var/1452176641_db.gz: not in gzip format`.  How can I extract this database file?

**Comment by marvincaspar** [comment]
Just rename the file to `1452176641_db.sql` and open it in a text editor

**Comment by brendanmckeown** [comment]
@mc388,
Thanks, that works!  Why is it given a `.gz` extension in the first place?

**Comment by marvincaspar** [comment]
I don't know but I had the same issue a few month ago. Maybe the fix this in the future

**Comment by mazhalai** [comment]
Reopening, since we have to fix this internally, in ticket MAGETWO-47687 to fix this.

**Comment by mazhalai** [comment]
@brendanmckeown thank you for reporting. We have merged a fix in the develop branch, hence closing this ticket. Please create a new ticket if issues still arise.

**Comment by mc388** [comment]
Thanks for fixing this issue but would it even better if you realy gzip the file to minimize the file size? If you hold about 10 backups of a big database you waste disc storage and it is faster to transfer the backup to an other location.
