### ISSUE TITLE
Special Price display not working on Product View

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#29157]
### Preconditions (*)

1. Magento 2.3.5-p1
2. PHP 7.2

### Steps to reproduce (*)

1. Create product
2. Add Special Price & schedule it to be visible

### Expected result (*)

1. Special price visible on the Product Page per the [documentation](https://docs.magento.com/user-guide/catalog/product-price-special.html#use-a-simple-start-and-end-date)

### Actual result (*)

1. Product page only displays regular price

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by nbennett25** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @nbennett25. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nbennett25, here is your [Magento instance](https://i-29157-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29157-2-4-develop.instances.magento-community.engineering/admin_70f4](https://i-29157-2-4-develop.instances.magento-community.engineering/admin_70f4)
Login: `e3b2918a` Password: `01a00fabb25a`
Instance will be terminated in up to 3 hours.

**Comment by nbennett25** [comment]
Hm - working as expected on 2.3.4.

@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @nbennett25. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nbennett25, here is your [Magento instance](https://i-29157-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-29157-2-3-3.instances.magento-community.engineering/admin_44ae](https://i-29157-2-3-3.instances.magento-community.engineering/admin_44ae)
Login: `59f64b14` Password: `60ddf0348e39`
Instance will be terminated in up to 3 hours.

**Comment by nbennett25** [comment]
Hm - working as expected on 2.3.3 as well. Closing.

**Comment by maksek** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @maksek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maksek, here is your [Magento instance](https://i-29157-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29157-2-4-develop.instances.magento-community.engineering/admin_a5b1](https://i-29157-2-4-develop.instances.magento-community.engineering/admin_a5b1)
Login: `0ba3f251` Password: `eb01320c1fa9`
Instance will be terminated in up to 3 hours.
