### ISSUE TITLE
issue with translate-inline

### ISSUE THREAD

**Issue by bohdan-berezhniy** [magento/magento2#29155]
### Preconditions (*)
1. Magento 2.4-develop
2. Disable all shipping methods
3. Create simple product
### Steps to reproduce (*)
1. Go to the Stores -> Configuration -> ADVANCED -> Developer -> Translate Inline -> Enabled for Storefront = Yes
2. Create a new (not English) store view (or use another one if exists)
3. Add simple product to cart
4. Change the store view to the one created in step 2
5. Click on the "Proceed to Checkout" button via mini-cart
6. Go to frontend and create translate for text:  "Sorry, no quotes are available for this order at this time". (for example into ukrainian language)
![Screenshot_56](https://user-images.githubusercontent.com/60198022/88376904-fb251c80-cda6-11ea-8c06-c1b5d5401780.png)
![Screenshot_57](https://user-images.githubusercontent.com/60198022/88376918-0415ee00-cda7-11ea-9674-7aec558968aa.png)
7. Go to the Home page (click on the site Logo)
8. Click on the "View and Edit Cart" button via mini-cart
9. Expand the "Estimate Shipping and Tax" section 
![Screenshot_58](https://user-images.githubusercontent.com/60198022/88377798-7dfaa700-cda8-11ea-8bb7-6849fbc1d13f.png)

### Expected result (*)
It`s possible to translate the text

### Actual result (*)
It's impossible translate the text

![Screenshot_59](https://user-images.githubusercontent.com/60198022/88378609-03cb2200-cdaa-11ea-92c8-92a8514b936b.png)

**Additional information**
It happens because in method  _loadDbTranslation that in file vendor/magento/framework/Translate.php
calls method    $data = $this->_translateResource->getTranslationArray(null, $this->getLocale());
that has not set store id and set null as strore id (if we change null on store id - all will works fine)

**Comment by engcom-Lima** [comment]
Hello @bohdan-berezhniy 
Could you provide more details for reproduce this issue?
Please add version of magento.

Thank you!

**Comment by bohdan-berezhniy** [comment]
Hello, 2.3.2
Magento version is not important (required version 2 and upper)

ср, 22 лип. 2020 о 15:26 Viktoriia Sekeresh <notifications@github.com> пише:

**Comment by engcom-Lima** [comment]
Hello @bohdan-berezhniy 
Could you please add a screenshot of the page that shows this text "Sorry, there are currently no offers for this order.". I mean in the DOM
By default it displays as none.
![Screenshot_51](https://user-images.githubusercontent.com/60198022/88274629-acaf4980-cce4-11ea-8828-09547f1aab2f.png)
But if I change display to block - the text shown. But this invalidate case. So I can't translate it inline
![Screenshot_52](https://user-images.githubusercontent.com/60198022/88274772-e8e2aa00-cce4-11ea-929e-92066b16b9b6.png)

**Comment by bohdan-berezhniy** [comment]
Hello
For me, it happens when I choose a country that not supported by the
shipping method.
Just remove display none and try to translate that text, or you can adjust
the shipping method to get this message.

чт, 23 лип. 2020 о 13:14 Viktoriia Sekeresh <notifications@github.com> пише:

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36143` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by themew** [comment]
Would really like to reopen this issue.  There is still no way to translate edit or translate "**_Sorry, no quotes are available for this order at this time"_**.
