### ISSUE TITLE
Login with unconfirmed account shows escaped anchor in error message

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#29158]
### Preconditions (*)

1. Magento 2.3.5-p1
2. Does not reproduce on 2.4-develop
   Does reproduce on 2.3.5-p1
### Steps to reproduce (*)

1. Create Customer via store front and log out
2. Go to Admin > Stores > Configuration > Customers > Customer Configuration > Create New Account Options
3. Set Require Emails Confirmation to Yes
4. Save Configuration
5. Clear Cache
6. Try to login with created customer (login and password must be correctly)

### Expected result (*)

1. See error message after login post with clickable section Click here
![Screenshot from 2020-07-17 16-12-17](https://user-images.githubusercontent.com/60198022/87790095-b5b59c00-c848-11ea-82a1-76870a474adf.png)

### Actual result (*)

1. Error message is displayed with anchor element escaped
![image](https://user-images.githubusercontent.com/25669334/87568964-2769da80-c6cf-11ea-8bdd-d8946079693a.png)
**Additional information**
On 2.4-develop customer logged in successfully
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by victortodoran** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @victortodoran. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @victortodoran, here is your [Magento instance](https://i-29158-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29158-2-4-develop.instances.magento-community.engineering/admin_9c29](https://i-29158-2-4-develop.instances.magento-community.engineering/admin_9c29)
Login: `891149e3` Password: `3f3ec56ccc08`
Instance will be terminated in up to 3 hours.

**Comment by victortodoran** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @victortodoran. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @victortodoran, here is your [Magento instance](https://i-29158-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29158-2-3-5-p1.instances.magento-community.engineering/admin_9f6a](https://i-29158-2-3-5-p1.instances.magento-community.engineering/admin_9f6a)
Login: `8f5b5d2b` Password: `1b58a49404b3`
Instance will be terminated in up to 3 hours.

**Comment by victortodoran** [comment]
Does not reproduce on 2.4-develop
Dos reproduce on 2.3.5-p1
![image](https://user-images.githubusercontent.com/25669334/87570409-4b2e2000-c6d1-11ea-8e33-9f244bde07d8.png)

**Comment by engcom-Lima** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima, here is your [Magento instance](https://i-29158-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29158-2-3-5-p1.instances.magento-community.engineering/admin_d6d3](https://i-29158-2-3-5-p1.instances.magento-community.engineering/admin_d6d3)
Login: `c57331c4` Password: `252f88c02934`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35973` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment]
Fixed in 2.4 https://github.com/magento/magento2/pull/27662
