### ISSUE TITLE
Filtering configurable product by availability of related simple products doesn't work.

### ISSUE THREAD

**Issue by mgroensmit** [magento/magento2#29166]
### Preconditions (*)

1. Magento 2.4-develop
2. Configuration value for 'Display out of stock products' is set to 'no'
3. Configuration value for 'Backorders' is set to 'no backorders'
![2020-07-27_11-58](https://user-images.githubusercontent.com/51679138/88523393-8e0cc380-d000-11ea-964c-ddb621eff3bc.png)

### Steps to reproduce (*)

1. Create a configurable product with two configurable attributes. In the example I used the Magento sample data with the 'color' and 'size' options.
2. Set one of the simple products to be out of stock, and set the rest to be in stock.
3. Filter the product listing on the frontend and select the filters for both the configurable attributes to values that should result in the configurable product being out of stock.

### Expected result (*)

1. The product doesn't show up in the listing.

### Actual result (*)

1. The 'olivia 1/4 light zip jacket' in the screenshot below is not available with the combination of 'size xs' and 'color purple', but it shows up in the listing when the filters are applied.
![image](https://user-images.githubusercontent.com/53430364/87649690-eb775980-c750-11ea-934e-e625c43ee234.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mgroensmit** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mgroensmit. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mgroensmit, here is your [Magento instance](https://i-29166-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29166-2-4-develop.instances.magento-community.engineering/admin_d4ce](https://i-29166-2-4-develop.instances.magento-community.engineering/admin_d4ce)
Login: `a9344479` Password: `9f683b042459`
Instance will be terminated in up to 3 hours.

**Comment by mgroensmit** [comment]
Issue is reproducible on Magento 2.4
![image](https://user-images.githubusercontent.com/53430364/87654733-a276d380-c757-11ea-98b5-ee5e440710a5.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36167` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Kilo** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Kilo. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Kilo, here is your [Magento instance](https://i-29166-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29166-2-4-develop.instances.magento-community.engineering/admin_c9ec](https://i-29166-2-4-develop.instances.magento-community.engineering/admin_c9ec)
Login: `879bfd77` Password: `13731613a1a3`
Instance will be terminated in up to 3 hours.

**Comment by tgamanov** [comment]
Hello @mgroensmit.
Trying to reproduce the described issue and not able to do it.
Please have a look at the gif
![29166_not _able_to_reproduce](https://user-images.githubusercontent.com/11708989/89776985-90e4d980-db13-11ea-9a9a-1581e047b414.gif)
and provide more additional information.
Thank you in advance.

**Comment by mgroensmit** [comment]
> Trying to reproduce the described issue and not able to do it.

@tgamanov the issue is with the filtering in the layered navigation, not with the swatches in the listing. If you apply the filters for both color and size and select a combination of values that is not available, you will still see the product in the listing as long the color or the size filter don't individually filter the product.

In my example in the original post, the 'Olivia' jacket is not available in the combination 'xs' and 'purple', but it still shows up in the listing when those filters are set because there are other color options available for the 'xs' size and other size available for the color 'purple'.

The swatches do reflect the 'out-of-stock' status of this product, but this issue is nevertheless problematic because configurable products can be created with attributes that are not swatches, giving no visual indication to the out-of-stock status of the product on the Category View page.

**Comment by tgamanov** [comment]
Hello @mgroensmit.
I got your point. Let me check it.
Thank you for the additional information.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by matthewhaworth** [comment]
I think this is still an issue.

@magento give me 2.4-develop instance

**Comment by matthewhaworth** [comment]
Curious to see if this used to happen with the MySQL adapter in 2.3, or whether it's elasticsearch causing it as per #20593

https://github.com/magento give me 2.3 instance

**Comment by matthewhaworth** [comment]
Curious to see if this used to happen with the MySQL adapter in 2.3, or whether it's elasticsearch causing it as per https://github.com/magento/magento2/issues/20593

@magento give me 2.3 instance
