### ISSUE TITLE
Data transfer->Input fails on windows

### ISSUE THREAD

**Issue by matteojob** [magento/magento2#29167]
### Preconditions (*)
1. Magento 2.3.4
2. Apache 2.4
3. Windows Server 2012 R2
4. mySQL 5.7.31
5. Imported site and db from linux server

### Steps to reproduce (*)
1. Go to system -> data transfer -> import
2. Basically, every csv I try to import, throw me "Sorry, but the data is invalid or the file is not uploaded."; checked permissions (also I've tried to upload an image, with success). Even if I try to upload the sample file (obtained with the link "Download simple file"), I get the same error.

**Comment by engcom-Lima** [comment]
Hello @matteojob 
See logs. 
According to the [devdocs](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)

> Magento is not supported on:
> 
> Windows OS
> Mac OS

As far as working Magento on Linux, the import works fine. But it`s possible to use [VM] (https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/optimal-dev-environment.html#installation) (Magento 2.4-develop branch)
