### ISSUE TITLE
Tier prices filtering in GraphQl - prices for different customer group but same quantity are not filtered out

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#29168]
Execute this query, to search for product that already meets the pre-conditions below

`products(search: "[Product-name]"){
	items {    
    price_tiers {
     	final_price {
        currency
        value
      }
      quantity
     }
	  }
	}`

Preconditions, expected results and actual results, are all based on an example with colliding ALL CUSTOMER GROUPS with NOT LOGGED IN. 
Nevertheless, the problem is still present when colliding ALL CUSTOMER GROUPS group with any other group.

### Preconditions (*)

1. Have a product created that has tier prices set as
a. Website: All Websites, Group: All Groups, Quantity: 3, Price: Fixed, Value: 3
b. Website: All Websites, Group: Not Logged In, Quantity: 3, Price: Fixed, Value: 3.5

### Steps to reproduce (*)

1. Execute the query and watch for response

### Expected result (*)

1. There is only one "final_price" with "quantity" = 3 in the response
2. The lower price value for the given quantity is displayed only

### Actual result (*)

1. Quantity 3 is listed twice for the both customer groups

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Usik2203** [comment]
@magento I am working on this
