### ISSUE TITLE
Can't access admin (backend) after setting up custom Admin URL via backend

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29169]
### Preconditions (*)

1. Magento 2.3.5-p1 Enterprise

### Steps to reproduce (*)

I changed the custom admin URL via the admin. 

I've set **Stores -> Settings: Configuration -> Advanced: Admin -> Admin Base URL -> Use Custom Admin URL** to **Yes**

I've set **Stores -> Settings: Configuration -> Advanced: Admin -> Custom Admin URL -> Custom Admin URL** to **adminxyz**

but just after saving it showed me the 404 site.

![image](https://user-images.githubusercontent.com/16349349/87666561-1b325b80-c769-11ea-8969-978f4092f4c5.png)

Now I can't access the admin (backend) anymore.

So I opened phpMyAdmin and noticed that in the table `core_config_data` the entries with path **web/unsecure/base_url** and **web/secure/base_url** changed to **adminxyz**.

So I changed them back to my domain **https://www.example.com/**

I also set the path **admin/url/use_custom** from **1** to **0**.

But I still can't login in the backend.

I already flushed the cache and reindexed.

If I execute `php bin/magento info:adminuri` then I get:

    Admin URI: /adminxyz

I even made this entry in my **app/etc/env.php**:

    <?php
    return [
        'backend' => [
            'frontName' => 'adminxyz'
        ],

### Expected result (*)

1. Admin login form should show

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/16349349/87666561-1b325b80-c769-11ea-8969-978f4092f4c5.png)

The bug exists since Magento 1. I found issues on stackoverflow about this from 2011

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone , thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.4-develop.

**Manual testing scenario:**
- Create additional virtualhost for url `http://admin.magento2dev.loc`. 
- Set Admin Base URL
 ![image](https://user-images.githubusercontent.com/51681379/88920082-e0561a80-d274-11ea-8f81-f42438fb539a.png)
- Save Config
- Login into Admin Panel

**Result:**
:heavy_check_mark: Successfully logged into admin
![image](https://user-images.githubusercontent.com/51681379/88920193-15626d00-d275-11ea-94fe-30526a954c83.png)
![image](https://user-images.githubusercontent.com/51681379/88920533-b18c7400-d275-11ea-93b3-3f4d59f63503.png)

**Note:** For disabling Custom Admin URL and Custom Admin Path you could use CLI commands:
`bin/magento config:set admin/url/use_custom_path 0`
`bin/magento config:set admin/url/use_custom 0`

DevDocs for configure Custom Admin URL: https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html

If you'd like to update  the issue, please reopen it.
