### ISSUE TITLE
magento 2.3.5 not connecting to marketplace

### ISSUE THREAD

**Issue by scooper5569** [magento/magento2#29163]
### Preconditions (*)

1. magent0 2.3.5 pt 1
2.

### Steps to reproduce (*)

1. clean install on sub domain 
2.

### Expected result (*)

1. Magento 2 is not connecting to marketplace
2. Access key has been added to magento

### Actual result (*)

1. Extentions are not showing up in Extension Manager
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @scooper5569 you for your report, issue is not reproducble on latest composer version 2.4.0 as [Removed the Extension Manager section of the Software Update Guide and redirected it to the CLI installation.](https://devdocs.magento.com/whats-new.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Extension%20Manager)
Please take a look docs about [extension](https://devdocs.magento.com/extensions/install/)
