### ISSUE TITLE
Product Media Drag and Drop in Backend for Firefox

### ISSUE THREAD

**Issue by corewaysolution** [magento/magento2#29175]
### Preconditions (*)

1. Product Detail Page Backend Medial Gallery Drag and Drop not perfect work in Firefox 78.0.1
2. Modal Popup open When I Drag & Drop Image
3. In other Browser Modal popup not open when I Drag & Drop

### Steps to reproduce (*)

1. Open Magento Backend in Firefox
2. Open Product Detail Page and then Open Images and Video Tab
3. Upload more than one Image
4. and then try to drag and drop

### Expected result (*)

1. when image drag and drop at that time image detail popup not needed
2. just product image drag and drop as needed

### Actual result (*)

1. Image Detail Popup open when I try to Drag and Drop Image

**Comment by corewaysolution** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @corewaysolution. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @corewaysolution, here is your [Magento instance](https://i-29175-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29175-2-4-develop.instances.magento-community.engineering/admin_2afe](https://i-29175-2-4-develop.instances.magento-community.engineering/admin_2afe)
Login: `52f6c7d8` Password: `6755921e4274`
Instance will be terminated in up to 3 hours.

**Comment by corewaysolution** [comment]
@magento I am working on this

**Comment by corewaysolution** [comment]
@magento add to contributors team

**Comment by corewaysolution** [comment]
@magento I am working on this
can you please assign this to me

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29175-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29175-2-4-develop.instances.magento-community.engineering/admin_9bb0](https://i-29175-2-4-develop.instances.magento-community.engineering/admin_9bb0)
Login: `172a5fb2` Password: `8b5d52b76e23`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @corewaysolution,
I have verified this issue with the Default Magento 2.4 Instance.  Drag and Drop functionality is working fine.
Can you please send me the video if you face this issue again?

Thanks.
