### ISSUE TITLE
Magento still loads settings from old storeviews after changing to single store mode

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29178]
### Preconditions (*)

1. Magento 2.3.5-p1
**Doesn`t reproducible on 2.4**

### Steps to reproduce (*)

1. Admin (Backend): Content -> Design: Configuration
![image](https://user-images.githubusercontent.com/16349349/87696496-2a2d0400-c791-11ea-8425-2870373f1d80.png)

2. Edit all three and add a font-awesome script to **Content -> Design: Configuration -> Other Settings -> HTML Head -> Scripts and Style Sheets**

` <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous"> `

3. Put store in "single store mode" (**Stores -> Settings: Configuration -> General: General -> Single Store Mode -> Enable Single Store Mode -> Yes**)
4. Flush Cache
5. Open Home page
6. Go to Admin (Backend): Content -> Design: Configuration
7. Notice that there is only one design left
![image](https://user-images.githubusercontent.com/16349349/87696954-d5d65400-c791-11ea-9b73-b80f65ac21f5.png)
8. Edit it
9. Remove the previously added font-awesome script from "**Content -> Design: Configuration -> Other Settings -> HTML Head -> Scripts and Style Sheets**"
10. Flush Cache
11. Reload frontend (flush cache) and inspect source
12. Notice that font-awesome script is still there.
13. Notice that it is still getting loaded from **store view / default view**
14. Delete font-awesome script directly from database
15. Flush Cache
16. Reload frontend and insepect source
17. Note that font-awesome script is not getting loaded anymore

### Expected result (*)

1. If store is put in single store mode, then settings should not get loaded from  **store view / default view** anymore, since they are not even showing in the backend anymore and you can't remove data from it.

### Actual result (*)

1. Old settings are still getting loaded

Putting magento in **single store mode** after you already made settings in other views / default view does not work, you have to do this from the very start.

**Additional information**

On 2.4, the behavior is different:
Step 9-11: Removed the font-awesome script and it will removed from frontend
![Screenshot_48](https://user-images.githubusercontent.com/60198022/88175407-7f07c900-cc2e-11ea-853d-42e7f0c6dcdc.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36078` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment]
Issue is not reproducible on magento 2.4-develop, 2.4.0, 2.3.5-p2
Closed as fixed
