### ISSUE TITLE
Swatches Image is duplicated after change base image order in backend

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#29182]
### Preconditions
1. Magento CE 2.3.4 with sample data

### Steps to reproduce
1. Login to admin panel
2. Go to Catalog > Products
3. Choice one configurable product and edit it (Ex: Chaz Kangeroo Hoodie)
4. Scroll down to tab Images And Videos
5. Drag and drop base/small/thumbnail image to last place like [this](https://imgur.com/6XqFhwW)
6. Save product
7. Visit product page in storefront
8. Choice color which refer to base/small/thumbnail like [this](https://imgur.com/yGcSNcj)

### Expected result (*)

1. Swatch Image should not duplicate

### Actual result (*)

1. Swatch Image is duplicated [https://imgur.com/yGcSNcj](https://imgur.com/yGcSNcj)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mack4hack** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mack4hack. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mack4hack, here is your [Magento instance](https://i-29182-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29182-2-4-develop.instances.magento-community.engineering/admin_f976](https://i-29182-2-4-develop.instances.magento-community.engineering/admin_f976)
Login: `752b9ae2` Password: `aff48641a948`
Instance will be terminated in up to 3 hours.

**Comment by mack4hack** [comment]
@kamui23 not able to reproduce on 2.4-develop instance

**Backend**
![Screenshot from 2020-07-17 11-58-04](https://user-images.githubusercontent.com/11089409/87755664-0915f300-c825-11ea-9e1f-63a956e01fe2.png)

**Frontend**
![Screenshot from 2020-07-17 11-58-51](https://user-images.githubusercontent.com/11089409/87755672-0ca97a00-c825-11ea-9705-10e18b30a1f8.png)

You can verify again, till the instance is running.

**Comment by kamui23** [comment]
@mack4hack https://imgur.com/khzPOOt
Link verify: https://i-29182-2-4-develop.instances.magento-community.engineering/configurable-product-1.html
It is still here

**Comment by kamui23** [comment]
Step 1: Choice first option Dynamic Attribute ca_1_631447041 
Step 2: Choice first option Dynamic Attribute ca_2_631447041 (Select)

**Comment by mack4hack** [comment]
@kamui23 Able to reproduce on reproduce on 2.4-develop instance, previously I haven't selected the option.

![image](https://user-images.githubusercontent.com/11089409/87756653-eab0f700-c826-11ea-99f4-726388d35eb4.png)

**Comment by swathishs** [comment]
Hi @kamui23 , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
If you'd like to update the issue, please reopen it.

**Comment by kamui23** [comment]
@swathishs thank for your confirmation.
