### ISSUE TITLE
Magento2.3.5-p1 version automatically sending invoice mail even if "Email Copy of Invoice checkbox" not selected

### ISSUE THREAD

**Issue by kamal02mittal** [magento/magento2#29186]
If we create invoice from admin and we have not selected "Email Copy of Invoice" checkbox, then invoice email should not be sent. But it is sending the mails.

### Preconditions (*)

1. Magento2.3.5-p1
2. PHP Version 7.2.27

### Steps to reproduce (*)

1. Create order from admin with any payment method like cash on delivery or check money order.
2. Create an invoice from admin and don't select "Email Copy of Invoice" checkbox.
3. Click on Submit Invoice button

### Expected result (*)

1. If the "Email Copy of Invoice" checkbox is not selected during the creation of the invoice from admin, then invoice email should not be sent.

### Actual result (*)

1. Invoice email is automatically sent even if we have not selected  "Email Copy of Invoice" checkbox
2. Checked core code in the class Magento\Sales\Controller\Adminhtml\Order\Invoice\Save
![image](https://user-images.githubusercontent.com/68422773/87774044-a8e17a00-c841-11ea-9600-cd07a681e8e3.png)

---
- [ ] Severity: **S2**

**Comment by krishprakash** [comment]
Hi @kamal02mittal. 
Seems issue is already reported #28511 
So no need to open same issue
