### ISSUE TITLE
Validate class not found from basename 'StringLength'

### ISSUE THREAD

**Issue by chat2vignesh** [magento/magento2#2919]
Hi,

When i try to update the customer or product attributes i am getting this error message. 

Validate class not found from basename 'StringLength'

It seems like namespace not working with this class file..?

Any one got same problem please  reply me. 

Thanks,

**Comment by daim2k5** [comment]
@chat2vignesh did you use a clean m2 installation? Do you get this error in your own extension?

**Comment by chat2vignesh** [comment]
Dear Friend,

Thank you very much for your reply, 

Yes, it is happen in the clean magneto installation.  I am installed the magento with sample data only. 
There is no other extension or themes installed.

This issue showing when i try to save Product Attribute or Save customer from admin side.

Error showing: Validate class not found from basename 'StringLength'

Thanks,

**Comment by sevos1984** [comment]
This looks like environment issue, try updating your mysql as said here https://community.magento.com/t5/Polish/StringLength-ERROR/td-p/4434

**Comment by okorshenko** [comment]
@chat2vignesh , please, let us know if you still have an issue

**Comment by mbhuva** [comment]
Hello,

  I am also facing same issue when trying to create product attribute.

if any solution please let me known.

Thanks,

**Comment by chat2vignesh** [comment]
Hi,

Yes, i found the solution for this. Big i hack the core file. 

Thanks,

**Comment by daim2k5** [comment]
@chat2vignesh ok thx. So i close the issue

**Comment by magento2q** [comment]
Hi @chat2vignesh, what core file(s) did you edit? 

I'm having the same issue with 'NotEmpty' with a clean installation too, when going to checkout.

**Comment by Kipperlenny** [comment]
I had to change my include_path from "." to ".:/var/www/[WHERE_EVER_YOUR_PAGE_IS]/vendor/magento/zendframework1/library"

**Comment by nikidexa** [comment]
I have the same issue... so if you solved this issue please let us konw how....

**Comment by emadha** [comment]
I noticed i'm getting this issue because of Litespeed, when i switch back to Apache it runs normal. i think it's because Litespeed runs php in a different way than apache.

It's a server related issue (in my case) and not magento.
