### ISSUE TITLE
Field "Number of Symbols" in CAPTCHA settings has missing range validation 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#29198]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. System->Configuration, Advanced->Admin
3. FIeld CAPTCHA -> "Number of Symbols", fill out of the range . Ex: 3-9

![image](https://user-images.githubusercontent.com/8234209/87876917-59e44200-ca05-11ea-8ec5-4b23680a2cca.png)

### Expected result (*)

1. Can not save, the validation message

### Actual result (*)

1. Save normally with incorrect range

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-29198-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29198-2-4-develop.instances.magento-community.engineering/admin_4d5e](https://i-29198-2-4-develop.instances.magento-community.engineering/admin_4d5e)
Login: `7e3818d4` Password: `e98193018fab`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36006` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#29199 by @edenduong in 2.4-develop branch
Related commit(s):
 - [8176ad5acc5b317005b90426ac10a5060b18e415](https://github.com/magento/magento2/commit/8176ad5acc5b317005b90426ac10a5060b18e415)
 - [0d94aba47b40c0bfc29e257b8d032f8fed34380b](https://github.com/magento/magento2/commit/0d94aba47b40c0bfc29e257b8d032f8fed34380b)

The fix will be available with the upcoming 2.4.1 release.
