### ISSUE TITLE
Unable to create the cart

### ISSUE THREAD

**Issue by melwinlobo18** [magento/magento2#29195]
### Preconditions (*)
Magento ver. 2.3.4

### Steps to reproduce (*)
> POST https://\<host\>/index.php/rest/default/V1/carts/mine
> 
> Content-Type: application/json
> Authorization: Bearer \<customer token\>

### Expected result (*)
The response is the quoted: \<id\>

### Actual result (*)
```
{
    "message": "The quote can't be created."
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hello @melwinlobo18 
I tried to create a client via API and via store view.
Unfortunately, I'm not able to reproduce issue by steps you described on clean 2.4-develop
![Screenshot_39](https://user-images.githubusercontent.com/60198022/88035035-37a80c80-cb4a-11ea-9c49-0b8dea4c79f0.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Comment by melwinlobo18** [comment]
Hey @engcom-Lima , thank you for your response. So, as I have mentioned above the request should successfully create a Cart for the customer but I have no idea why I am getting that error. Do you have any idea why this error might occur?

**Comment by engcom-Lima** [comment]
@melwinlobo18 I don`t use the 

`index.php`
in `/index.php/rest/default/V1/carts/mine`
My request is 
`https://youredomain.com/rest/default/V1/carts/mine`

**Comment by melwinlobo18** [comment]
I have tried without the index.php. Same error :(

**Comment by melwinlobo18** [comment]
https://dev.sofiqe.com/rest/default/V1/carts/mine

Token: sepfa1e096gnrwlhqo83nb88lljmol7z

**Comment by engcom-Lima** [comment]
> https://dev.sofiqe.com/rest/default/V1/carts/mine
> 
> Token: sepfa1e096gnrwlhqo83nb88lljmol7z

@melwinlobo18  I see this message:
`The consumer isn't authorized to access %resources.` When open the link

**Comment by engcom-Lima** [comment]
@melwinlobo18 New token needed.

**Comment by melwinlobo18** [comment]
@engcom-Lima 8dj899frlkfbsdxlp7rmzmx0lnevge8d

**Comment by engcom-Lima** [comment]
@melwinlobo18 What written in your logs?

**Comment by melwinlobo18** [comment]
@engcom-Lima You mean the Log in the Report section of the Admin Panel?

I checked the debug, exception, and system log. Nothing is written to the log regarding to this request.

**Comment by engcom-Lima** [comment]
@melwinlobo18 I mean what in the system log. 
Please, remember what you did before you ran into this issue? It can help me reproduce this issue

**Comment by engcom-Lima** [comment]
@melwinlobo18 Give more information about a customer
Is it possible to create a new customer? 
Is it possible to place order with this customer through browsing store view? via admin?

**Comment by melwinlobo18** [comment]
@engcom-Lima 
It's possible to create a new customer.

When I click on **Create Order** for the customer in admin panel following error is being recorded in the System Log

``` [2020-07-22 02:50:28] main.ERROR: Validate class not found from basename 'Magento\Framework\Validator\EmailAddress' [] [] ```

**Comment by engcom-Lima** [comment]
@melwinlobo18 See this issue: [20783](https://github.com/magento/magento2/issues/20783)
