### ISSUE TITLE
Product Qty not update in decimal value in cart update page 

### ISSUE THREAD

**Issue by darpanpatel2018** [magento/magento2#29192]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. Product Qty not update in decimal value in cart update page even i have choose product increase in decimal value in listing time 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
Hi @darpanpatel2018,
Please add Proper Pre Conditions, Steps to be reproduced, Actual result and Expected result.

**Comment by ajijshekh123** [comment]
@darpanpatel2018 Any Update??

**Comment by ajijshekh123** [comment]
Hi @darpanpatel2018,
if you have reproduced this issue on the latest Magento instance. please add proper details and reopen this issue.

Thanks.

**Comment by darpanpatel2018** [comment]
dear sir,
I have used 2.3.5-p1 version. and when I was select qty increment in decimal value after that I added product in add to cart after that I was trying to update product qty in decimal value that time one message created ( please enter valid value).
for example, I have added 1.2 product qty and after that, I tried to update 1.5 that time not updated qty value.
