### ISSUE TITLE
Two-step checkout breaks after visiting multiple address checkout page

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2920]
# Explanation of issue

I've encountered a really odd bug. When a logged in user with multiple address in their customer account visits the "Multiple Address Checkout" page and then progresses to the normal checkout, each time they progress from _Shipping_ to _Review & Payments_, the shipping address in quote_address gets duplicated. Because of this, when the user tries to place the order, the order can't be placed and the user gets redirected back to the cart with no error message.
# Steps to reproduce
1. Install Magento 2.0.0 with sample data
2. Go to /customer/account/login and login with the `roni_cost@example.com` user (this user has two addresses in their account so it is perfect for reproducing this issue).
3. Add the `/beaumont-summit-kit.html` product to your cart.
4. Got to `/checkout/cart/`
5. Click "Check Out with Multiple Addresses" to visit the multiple address checkout page.
6. Click "Back to Shopping Cart".
7. Click "Proceed to Checkout"
8. Select any shipping method and click "Next":
   ![checkout](https://cloud.githubusercontent.com/assets/129031/12178376/bf74ad32-b536-11e5-9ec6-16ccc2f1f90f.png)
9. Once you get to the "Review & Payments" step, connect to the database for your Magento installation. Find your current quote by looking at the `quote` table. Then, look at the `quote_address` table for all addresses associated with that quote. After following the steps above, my `quote_address` table has THREE addresses for the quote ID of 3 (should only be two).
10. Switch back to your browser and click on the "Shipping" step and click "Next" again to progress back to the "Review & Payments" step. Look back at the `quote_address` table. You'll see that there are now 4 quotes addresses. Every time you progress to the "Review & Payments" step, a new quote address will be created. Example screenshot:
    ![issue](https://cloud.githubusercontent.com/assets/129031/12178571/c7585f5c-b537-11e5-9ca7-067b64e622a3.png)
11. Now, click the "Place Order" button. You'll be redirected back to cart with no error message.

**Comment by ishakhsuvarov** [comment]
@erikhansen Thank you for reporting this issue.
Which branch are you using to reproduce the issue? We could partly reproduce it (steps 9 and 10) but order is placed successfully on the `develop` branch. 
We have created an internal ticket `MAGETWO-47748` to investigate and fix the issue.

**Comment by erikhansen** [comment]
@ishakhsuvarov Sorry, I just saw your comment. I am using the 2.0.0 release of _Enterprise_. Steps 9 and 10 are the most critical. If you fix that, I expect I will not be able to reproduce step 11.

**Comment by ishakhsuvarov** [comment]
@erikhansen Fix for this issue had been delivered to the `develop` branch with the commit [c5c922a6714237ce2f6897ffc99782e71185acca](https://github.com/magento/magento2/commit/c5c922a6714237ce2f6897ffc99782e71185acca).
Closing this issue for now. Please feel free to reopen if you think something is wrong.
