### ISSUE TITLE
getFormattedShippingAddress / getFormattedBillingAddress

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#29209]
### Preconditions (*)
1. M 2.3.5-p1, 2.4-develop
2. English and German locale

### Steps to reproduce (*)
1. Create an order in english store
2. Go to order in backend with an german locale (de_DE) set in admin account profile
3. Resend the order E-Mail

### Expected result (*)

1. The formatted address in the E-Mail should contain an english country name
![image](https://user-images.githubusercontent.com/51681379/88788853-96026a00-d19e-11ea-8251-3bb244f86a8f.png)

### Actual result (*)

1. The formatted address in the E-Mail contains a german country name
![image](https://user-images.githubusercontent.com/51681379/88788811-8a16a800-d19e-11ea-8dfd-3c54b4147916.png)

The problem:
The function \Magento\Sales\Model\Order\Email\Sender\OrderSender::prepareTemplate() is called before \Magento\Email\Model\AbstractTemplate::applyDesignConfig() starts store emulation. So prepareTemplate() uses the locale and config for adminhtml. Not frontend.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bernd-reindl** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bernd-reindl. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bernd-reindl, here is your [Magento instance](https://i-29209-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29209-2-4-develop.instances.magento-community.engineering/admin_57e5](https://i-29209-2-4-develop.instances.magento-community.engineering/admin_57e5)
Login: `44aaae2a` Password: `28ebd1d8e8e8`
Instance will be terminated in up to 3 hours.

**Comment by bernd-reindl** [comment]
@magento-admin unfortunately i didn't receive the order mails in the 2.4-develop instance. So i can't validate the bug in 2.4-dev.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36269` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @bernd-reindl, @zaximus84. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-36269` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
