### ISSUE TITLE
Cannot mass update Enable Qty Increments & Qty Increments attributes

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#29215]
### Preconditions (*)
1.  2.3.4
2.  2.3.5

### Steps to reproduce (*)
1.  Go to Admin > Catalog > Products

2.  Check 1 or more products

3.  Select dropdown Actions > Update attributes

4.  Under Advanced Inventory > Enable Qty Increments
Check Change, uncheck Use Config Settings and change to Yes

5.  Under Advanced Inventory > Qty Increments
Check Change, uncheck Use Config Settings and change to 2

6.  Hit Save button

7.  Page is redirected back to Products list and message is generated "Message is added to queue"

### Expected result (*)
1.  Attribute Enable Qty Increments would be updated to Yes for all selected products.
2.  Attribute Qty Increments would be updated to 2 for all selected products.

### Actual result (*)
1.  Neither attribute is updated.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stevekem** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @stevekem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @stevekem, here is your [Magento instance](https://i-29215-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29215-2-4-develop.instances.magento-community.engineering/admin_a63a](https://i-29215-2-4-develop.instances.magento-community.engineering/admin_a63a)
Login: `3f7b6ca6` Password: `9e61762d5841`
Instance will be terminated in up to 3 hours.

**Comment by stevekem** [comment]
@magento I am working on this

**Comment by stevekem** [comment]
@magento add to contributors team

**Comment by stevekem** [comment]
Bug is reproducible in vanilla instance.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29215-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29215-2-4-develop.instances.magento-community.engineering/admin_984e](https://i-29215-2-4-develop.instances.magento-community.engineering/admin_984e)
Login: `df1300af` Password: `ad283676efd6`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @stevekem,
I have verified this issue in the latest Magento 2.4 instance. This issue is not reproduced on the latest Magento 2.4 Instance.
PFA:
![QtyIncrement](https://user-images.githubusercontent.com/24711761/88015318-88b20380-cb3e-11ea-937d-9d242438ab21.gif)

Please upgrade your Magento Instance. It will automatically fix this issue.
Thanks

**Comment by stevekem** [comment]
@ajijshekh123 It will work if you directly update the attribute for each product like you tested but it will NOT work if you follow the Steps to reproduce I listed above and update these 2 attributes in bulk using Actions > Update attributes from Admin > Catalog > Products. Please let me know if you need anymore clarification. Thanks!

**Comment by stevekem** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @stevekem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @stevekem, here is your [Magento instance](https://i-29215-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29215-2-4-develop.instances.magento-community.engineering/admin_d661](https://i-29215-2-4-develop.instances.magento-community.engineering/admin_d661)
Login: `40588b55` Password: `cdf427db38ec`
Instance will be terminated in up to 3 hours.

**Comment by stevekem** [comment]
Here is a screengrab:
[https://drive.google.com/file/d/1hGk9v4IFMzbIWkMPyHScedeTtNIp8bL8/view](url)

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29215-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29215-2-4-develop.instances.magento-community.engineering/admin_a07f](https://i-29215-2-4-develop.instances.magento-community.engineering/admin_a07f)
Login: `2154330f` Password: `dce2ec0f9700`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @stevekem,
Thanks for providing the video and proper details.
This issue is confirmed and reproduce in the Latest Magento 2.4 Instance.

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36062` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @stevekem 
cc: @ajijshekh123 

Based on issue description and attached recording it seems not a bug but configuration issue.
As we can see in the notification message "Message is added to queue". It means this mass-action processed not just after clicking Save button but the task was added to queue and will be processed by appropriate consumer.
So, server/machine with Magneto should have installed and configured all required soft to work with the message queue e.g. RabbitMQ.

Please see official Magento documentation related to this topic:
- [Message Queues](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/message-queues.html) chapter and related pages
- [how to install RabbitMQ and Magento configuration](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/install-rabbitmq.html)

**Comment by stevekem** [comment]
@sdzhepa We are hosting with Nexcess and can confirmed Rabbit MQ is installed and configured. I should note that "Enable Qty Increments" and "Qty Increments" seem to be the only attributes we have noticed that will not update.  We haven't tested every single one but all of our attributes are updating using Mass Update feature except these 2 attributes. Can you please reopen this issue?

**Comment by torhoehn** [comment]
@sdzhepa I don't think that you're right. It's true that the notification message "Message is added to queue" appears, but you'll not find any entry in your Bulk Actions Log. If there would be any configuration problem with RabbitMQ you would see the message with status "Not Started".

For us it seems to be an issue with all attributes in the "Advanced Inventory" tab. "Attributes" and "Websites" are working fine.

**Comment by torhoehn** [comment]
@sdzhepa For me it looks like that "Advanced Inventory" is not processed in the controller: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Action/Attribute/Save.php#L123

**Comment by engcom-Oscar** [comment]
Hi @torhoehn!
I was not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket (with properly cron installed) - 
"Enable Qty Increments" and "Qty Increments"  updated via mass action well.

**Actual Result:** :heavy_check_mark: 
![Screenshot from 2021-03-25 12-15-20](https://user-images.githubusercontent.com/60198413/112456835-ccab7700-8d63-11eb-825b-f9b3a8c722a6.png)

Can you recheck the issue on the latest 2.4-develop instance please?

**Comment by lucianopeluso10** [comment]
reproduced in 2.3.5-p1
