### ISSUE TITLE
Backorders unable to order products out of stock.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#29216]
Please reopen #10304 

Sorry, not sure how else to ask for it to be reopened.

(Qty <= 0 but > threshold unless threshold is 0)
Manage Stock: Yes

Customer is not notified.

![image](https://user-images.githubusercontent.com/1968109/88010228-7e0c6400-cb68-11ea-8fc2-433dede260fc.png)

Suggested solution is to set Stock Status to In Stock which is misleading as the product is actually out of stock.
But a re-order is going to happen.

Suggest to allow a product attribute to set a date when the product is expected to be in stock again.

**Comment by mverstegen** [comment]
i'm on 2.4.1, still not fixed, anyone knows a quick fix for this problem?

**Comment by thomas-thaulow** [comment]
Issue should definately be opened. The mentioned issue, were clearly not understood by the product owner evaluating it.

**Comment by sandy6666** [comment]
@magento-engcom-team please reopen this issue

**Comment by sandy6666** [comment]
@magento I am working on this

**Comment by sandy6666** [comment]
@magento please reopen this issue
