### ISSUE TITLE
Prefix and Suffix Translation

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#29217]
### Preconditions (*)
1. M2.3.5-p1, 2.4-develop
2. English (default) and german store view

### Steps to reproduce (*)
1. Set "Show Prefix" to "Required" in Stores/Configuration/Customers/Customer Configuration/Name and Address Options
2. Set "Mr.;Ms." for "Prefix Dropdown Options"
3. Add a german locale file which translate "Mr." to "Herr" and "Ms." to "Frau"
"Mr.","Herr"
"Ms.","Frau"

### Expected result (*)
1. Every occurrence of the prefix should translated
![image](https://user-images.githubusercontent.com/51681379/88800957-9b1ce480-d1b1-11ea-9a46-2ffb90d126ab.png)
![image](https://user-images.githubusercontent.com/51681379/88800912-8dfff580-d1b1-11ea-8e0f-e69775ced786.png)

### Actual result (*)
1. Only the prefix in frontend address form is translated

vendor/magento/module-customer/view/frontend/templates/widget/name.phtml
![image](https://user-images.githubusercontent.com/2369089/88020259-ad50b000-cb2b-11ea-8a3b-ba1d366929dd.png)

2. Other occurrence are not translated

![image](https://user-images.githubusercontent.com/51681379/88800755-52fdc200-d1b1-11ea-86f3-e40abfa6809c.png)
![image](https://user-images.githubusercontent.com/51681379/88800809-69a41900-d1b1-11ea-8ca9-9bf12a446167.png)
![image](https://user-images.githubusercontent.com/51681379/88800871-7f194300-d1b1-11ea-957f-407629a85089.png)

So i have added the translation to prefix and suffix in this files: 

Magento\Customer\Helper\View::getCustomerName()
![image](https://user-images.githubusercontent.com/2369089/88020854-bbeb9700-cb2c-11ea-95a8-354b3d65291c.png)

Magento\Customer\Block\Address\Renderer\DefaultRenderer::renderArray()
![image](https://user-images.githubusercontent.com/2369089/88020928-e0477380-cb2c-11ea-9ec3-c05545112c3f.png)

Magento\Customer\Model\Options::prepareNamePrefixSuffixOptions()
![image](https://user-images.githubusercontent.com/2369089/88021022-079e4080-cb2d-11ea-8773-f10315c04375.png)

Magento\Customer\Model\Address\AbstractAddress::getName()
![image](https://user-images.githubusercontent.com/2369089/88021092-269cd280-cb2d-11ea-8bb5-9040770a568b.png)

Magento\Sales\Model\Order\Address::getName()
![image](https://user-images.githubusercontent.com/2369089/88021181-5946cb00-cb2d-11ea-8199-6c45303f9d30.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36272` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by solwininfotech** [comment]
@magento I am working on this

**Comment by jitendra-cedcoss** [comment]
@magento I am working on it.

**Comment by jitendra-cedcoss** [comment]
#dmcdindia2020

**Comment by solwininfotech** [comment]
@jitendra-cedcoss I am working on it and will push the branch in next 1 hour
