### ISSUE TITLE
Setup di compile fail because of missing class

### ISSUE THREAD

**Issue by Minirock** [magento/magento2#29211]
I'm trying to add the Colissimo magentix module to my Magento 2 website : https://colissimo.magentix.fr/magento-2/documentation.html

In order to install the module there is a set of 4 dependencies to add into the `composer.json` file

### Steps to reproduce (*)
1. Add the dependencies to composer.json
2. Update composer
3. Activate all the 4 module (here is one line for the example) `php bin/magento module:enable Colissimo_Rule`
4. Update the db status : `php bin/magento setup:db:status`
5. Run `bin/magento setup:upgrade`
6. Run `bin/magento setup:di:compile`

### Preconditions (*)
1. I'm running Magento 2.3.2 version.
2. Theses are the dependencies version : 
        "colissimo/module-shipping": "^100.9",
        "colissimo/module-expeditor": "^100.3",
        "colissimo/module-label": "100.5",
        "colissimo/module-rule": "^100.4"

### Expected result (*)

1. I expect the setup di to work

### Actual result (*)

1. I got the error : 

> Compilation was started.
> Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 68.0 MiB
> Fatal error: Class 'Magento\Shipping\Model\Rate\CarrierResult' not found in /var/www/html/vendor/colissimo/module-shipping/Model/Shipping/Rate/CarrierResult.php on line 18

**Comment by victortodoran** [comment]
This is a 3rd party integration issue. It has nothing to do with core features. You should address your issue with the 3rd party vendor from which you acquired your extension.

**Comment by Minirock** [comment]
Indeed, but the error being a not found core Magento class, I still came here in order to know if this is due to some kind of evol from magento where the class rwould have been enamed from `CarrierResult` to `Result` ?

**Comment by mrtuvn** [comment]
i think you are using wrong version of 3rd party named colissimo. This mean 3rd party not compatible with your magento version.
Colissimo try to call Magento\Shipping\Model\Rate\CarrierResult but it not available in your magento version

Solution: Choose correct colissimo work with your magento 2.3.2
Or update your magento

**Comment by Minirock** [comment]
For this one the issue was indeed in the version.
