### ISSUE TITLE
M2 ignoring session time out

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#2922]
Please can anyone help with Magento not honouring the time-outs set for cookies, when importing products via CSV?

We start with a clean system:
- rm -f /var/lib/php/session/*
- rm -f /var/www/<magentosite>/var/session/*
- Clear all browser cookies.
- Reboot server.

Then I try to import a 77,000 record product CSV file. Magento successfully checks it and we continue with the import.
After, between 25~28 minutes, the HTTPD process stalls and we get "Service Temporarily Unavailable (503)" in the browser's console.

We have quadruple checked all our PHP/Magento settings, rebooted dozens of times, ran everything we can think of to clean the environment between attempts, but guaranteed, _something_ causes a time-out.
If I inspect all the cookies in my browser, the expiry times are correct as per my PHP/Magento settings (see below), but still, something appears to be overriding them server side (like there is a cookie clean-up similar to PHP's session.gc_maxlifetime) but for M2's cookies.

**Setup & Config**
CentOS 6.7
Apache 2.2.15
PHP 5.6
MariaDB 10.0.23

**php.ini**
session.gc_maxlifetime = 28800
max_execution_time = 14400
memory_limit = 2048M
post_max_size = 64M
upload_max_filesize = 64M

**/var/www/<magentosite>/.htaccess**
    php_value memory_limit 2048M
    php_value max_execution_time 14400

**MAGENTO SETTINGS**
Stores  > Configuration > Web > Default Cookie Settings > Cookie Lifetime = 14400
Admin   > Security      > Admin Session Lifetime (seconds) = 14400   

**No errors in:**
/var/www/<magentosite>/var/log/debug.log
/var/www/<magentosite>/var/log/system.log
/var/log/httpd/<magentosite>/error_log
/var/log/httpd/<magentosite>/access_log

All permissions are correct for all Magento files and all cron jobs run without incident.

Are we missing some other important session/cookie timeout setting, or does M2 just ignore all these settings and have 25~28 minutes hard-coded somewhere!?

Thank you

Elliot

**Comment by mazhalai** [comment]
@hgpit thank you for reporting, we have created MAGETWO-47691 to investigate.

**Comment by hgpit** [comment]
I think I have nailed this issue down to a database setting.
MySQL/MariaDB setting 'max_allowed_packet ' needed to be increased from its default 1MB.

It would be good if Magento had some way of reporting/warning a user that huge product imports would generate insanely huge SQL statements.
