### ISSUE TITLE
index reindexer

### ISSUE THREAD

**Issue by lksharma8** [magento/magento2#29229]
how do I reindex in magento 2 in aws lightsail instance through SSH. what are the commands I have to use to reindex

**Comment by krishprakash** [comment]
Hi @lksharma8. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
