### ISSUE TITLE
Has it any sense to display the stock status on the frontend product views for the virtual products?

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2923]
![](https://mage2.pro/uploads/default/original/1X/ac21c16e53395e007eaacd4061d8713cb115253c.png)

https://mage2.pro/t/196

Related to: https://github.com/magento/magento2/issues/2314, https://github.com/magento/magento2/issues/2359, https://github.com/magento/magento2/issues/2012

**Comment by pboisvert** [comment]
passing this one to you Anton since you own product creation. Seems like a bug to have front-end display stock status so best to have logic to hide for this product type

**Comment by antboiko** [comment]
Internal ticket MAGETWO-49913 have been created #2314. 

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Has-it-any-sense-to-display-the-stock-status-on-the-frontend/idi-p/48472).
