### ISSUE TITLE
Unable to remove compare.js

### ISSUE THREAD

**Issue by onepack** [magento/magento2#29232]
### Summary (*)

Magento 2.3.5-p1
PHP 7.3

I try to remove compare.js like explained here:
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css_remove

### Examples (*)

Default_head_blocks,xml

`    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <remove src="Magento_Catalog::js/compare.js" />
    </head>`

The JS should not load on frontend in theme after setup:update in Developent.

Result in Chrome after reload:
https://domain.com/pub/static/version1595369080/frontend/Vendor/theme/en_US/mage/utils/compare.js

It's still there after setup:upgrade, clearing caches and refreshing.
Nothing works

How should this js and other redundant JS files be removed so that loading can be faster.

### Proposed solution

Clear documentation with working examples on how to remove LIB js, UI js and more.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [S4] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
well seem problem with remove with js! Unable to remove file with layout xml approach

**Comment by mrtuvn** [comment]
First module catalog doesn't have any file in js/compare so you remove by tag is useless. It's only work if origin js added via layout so you can remove it from custom theme or another custom module via layout

**Comment by ihor-sviziev** [comment]
Hi @onepack,
The documentation clearly shows:
> If js files are called via the RequireJS approach: by declaring in the require/define sections, **we cannot remove it from the layout.**

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css_remove

If it still not clear - feel free to create a Pull Request to devdocs repository in order to improve it. 

As this is basically expected result - i'm closing this issue.
