### ISSUE TITLE
Error setup:upgrade after upgrade to magento2.3.5-p1 

### ISSUE THREAD

**Issue by JMLucas96** [magento/magento2#29234]
I updated magento2.1.8 to 2.3.5-p1  and when run setup:upgrade with Magento_Amqp and Magento_MysqlMq enabled can't perform `setup:upgrade`.

### Preconditions (*)

1.Upgrade magento 2.1.8 to 2.3.5-p1 from [https://devdocs.magento.com/cloud/project/project-upgrade.html](https://devdocs.magento.com/cloud/project/project-upgrade.html)
2.Environment: Windows, php7.2.3, apache

### Steps to reproduce (*)

1.Once upgrade is succeed run `setup:upgrade`

### Expected result (*)

1. Success message notifying `Nothing to import`

### Actual result (*)

1. Error occurred `Type Error occurred when creating object: Magento\Framework\Communication\Config\Data`
2.
![image](https://user-images.githubusercontent.com/47561465/88174326-685c7480-cc24-11ea-81b3-ab39b5d096fb.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JMLucas96** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @JMLucas96. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by JMLucas96** [comment]
@magento I am working on this

**Comment by JMLucas96** [comment]
@magento add to contributors team

**Comment by magento-engcom-team** [comment]
Hi @JMLucas96, here is your [Magento instance](https://i-29234-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29234-2-4-develop.instances.magento-community.engineering/admin_624a](https://i-29234-2-4-develop.instances.magento-community.engineering/admin_624a)
Login: `db1d07a4` Password: `f332e2781f88`
Instance will be terminated in up to 3 hours.

**Comment by JMLucas96** [comment]
Solution!

Create a custom module to extends `Magento\Framework\Reflection\TypeProcessor`.

Contents of `di.xml`

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\Reflection\TypeProcessor" type="MyModule\CustomName\Framework\Reflection\TypeProcessor" />
</config>
```

Contents of `TypeProcessor.php`

```
<?php
/**
 * Created by Compsaonline.
 * User: Joan Marc - Compsaonline
 * Date: 22/07/2020
 * Time: 14:43
 */

namespace Compsaonline\CommunicationError\Framework\Reflection;


use Magento\Framework\Reflection\TypeProcessor as Original;
use Zend\Code\Reflection\ParameterReflection;
use Zend\Code\Reflection\DocBlock\Tag\ParamTag;


class TypeProcessor extends Original
{
    /**
     * Get the parameter type
     *
     * @param ParameterReflection $param
     * @return string
     * @throws \LogicException
     */
    public function getParamType(ParameterReflection $param)
    {
        $type = $param->detectType();
        if ($type === 'null') {
            throw new \LogicException(sprintf(
                '@param annotation is incorrect for the parameter "%s" in the method "%s:%s".'
                . ' First declared type should not be null. E.g. string|null',
                $param->getName(),
                $param->getDeclaringClass()->getName(),
                $param->getDeclaringFunction()->name
            ));
        }
        if ($type === 'array') {
            // try to determine class, if it's array of objects
            $paramDocBlock = $this->getParamDocBlockTag($param);
            $paramTypes = $paramDocBlock->getTypes();
            $paramType = array_shift($paramTypes);

            $paramType = $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $paramType);

            return strpos($paramType, '[]') !== false ? $paramType : "{$paramType}[]";
        }

        return $type;
    }

    /**
     * Gets method's param doc block.
     *
     * @param ParameterReflection $param
     * @return ParamTag
     */
    private function getParamDocBlockTag(ParameterReflection $param): ParamTag
    {
        $docBlock = $param->getDeclaringFunction()
            ->getDocBlock();
        $paramsTag = $docBlock->getTags('param');
        return $paramsTag[$param->getPosition()];
    }
}
```

After that run `setup:upgrade` and get the following result:

![success_setup_upgrade](https://user-images.githubusercontent.com/47561465/88179017-89749380-cc2b-11ea-8645-04c909503000.png)


[Source](https://stackoverflow.com/questions/57720302/upgrade-magento-2-2-2-3-2-type-error-occurred-when-creating-object-magento#answer-57720303)
