### ISSUE TITLE
Imágenes productos 

### ISSUE THREAD

**Issue by lucia24597** [magento/magento2#29233]
No me deja adjuntar imágenes para cada producto.
Me informa: "Se necesita especificar el tipo de imagen y la información para cada vista de tienda"
Actualmente estoy usando la versión 1.9.2.4
![image](https://user-images.githubusercontent.com/68645125/88172695-ab691880-cc21-11ea-9e9c-e0219d2dc569.png)

**Comment by lucia24597** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lucia24597. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by lucia24597** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lucia24597. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lucia24597, here is your [Magento instance](https://i-29233-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29233-2-4-develop.instances.magento-community.engineering/admin_474a](https://i-29233-2-4-develop.instances.magento-community.engineering/admin_474a)
Login: `7d93a248` Password: `9296479f5c07`
Instance will be terminated in up to 3 hours.

**Comment by lucia24597** [comment]
@magento I am working on this

**Comment by lucia24597** [comment]
@magento add to contributors team

**Comment by krishprakash** [comment]
Hi @lucia24597. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic

Also refer some below links:
- https://community.magento.com/t5/Magento-1-x-Programming/Image-type-and-information-need-to-be-specified-for-each-store/td-p/2626
- https://magento.stackexchange.com/questions/32234/images-not-showing-in-admin-product-information-page-for-some-admin-users
