### ISSUE TITLE
Related product rules are not working for newly created custom product attribute with comma separated values in condition

### ISSUE THREAD

**Issue by kiranmaipappu** [magento/magento2#29239]
### Preconditions (*)
1. The issue is reproducible in EE 2.3.3 & EE 2.3.5
2. There are no dependencies modules. Verified in EE 2.3.3 & EE 2.3.5with sample data.
3. Verified in the UAT environment with an existing client environment. The issue is reproducible.

### Steps to reproduce (*)

**_Product attribute creation:_** 

1. Created a product attribute named "Test" as a Global attribute with type as "Text Filed", scope "Global".

![test-Product-Attributes-Attributes-Stores-Magento-Admin](https://user-images.githubusercontent.com/3583368/88254856-3276c900-ccd4-11ea-9adc-0fdf0f3b48f7.png)
![test-Product-Attributes-Attributes-Stores-Magento-Admin -1](https://user-images.githubusercontent.com/3583368/88254858-34d92300-ccd4-11ea-8cbb-e3d9dacaf63b.png)

**_Creating a Related Product Rule:_**

1. Open Magento admin, and navigate to Marketing->Promotions->Related Product Rules
2. Click on Add Rule
3. Provide the information like below
	
**Tab: Rule Information**

		1. Rule Name like "Testing"
		2. Status like "Active"
		3. Apply to "Related Products"
		4. From "07/1/2020"

![Testing-Related-Products-Rule-Promotions](https://user-images.githubusercontent.com/3583368/88255485-1aa04480-ccd6-11ea-8c2f-e566d8f8745b.png)

		
**Tab: Products to Match**
	
		If All of these conditions are True
		
		1. "Test" (product attribute) **is** MAGT2NA_Test3

![Testing-Related-Products-Rule-Promotions-Marketing-Magento-Admin (1)](https://user-images.githubusercontent.com/3583368/88254873-47535c80-ccd4-11ea-80fd-303edbfe74eb.png)

		
**Tab: Products to display**

		If All of these conditions are True
		
		1. "Test" (product attribute) **is one of Constant Value** 24-MB02,701644329389M
		

![Testing-Related-Products-Rule-Promotions-Marketing-Magento-Admin (2)](https://user-images.githubusercontent.com/3583368/88254882-4d493d80-ccd4-11ea-9e76-4ac675856c02.png)

**Click on Save or Save & Continue Edit**

### Expected result (*)

1.  The rule should apply for product "MAGT2NA_Test3", and the corresponding products 24-MB02, 701644329389M should display as related products.

### Actual result (*)

1. The products (24-MB02,701644329389M) are not displaying in related products for "MAGT2NA_Test3" on the PDP page.  The product is displaying as a "Related product" when we assign only one product in the **Product to display tab** instead of two with comma-separated.

![Testing-Related-Products-Rule-Promotions-Marketing-Magento-Admin (1)](https://user-images.githubusercontent.com/3583368/88255050-e415fa00-ccd4-11ea-9675-2cf15433250b.png)

![Testing-Related-Products-Rule-Promotions-Marketing-Magento-Admin (2)](https://user-images.githubusercontent.com/3583368/88255573-50ddc400-ccd6-11ea-904a-4b28c59e8021.png)

![Push-It-Messenger-Bag](https://user-images.githubusercontent.com/3583368/88255026-d3658400-ccd4-11ea-9fa6-b465ff1ac82b.png)

![Testing-Related-Products-Rule-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/3583368/88255092-0a3b9a00-ccd5-11ea-95d9-59503318a48d.png)
![Push-It-Messenger-Bag1](https://user-images.githubusercontent.com/3583368/88255357-cf863180-ccd5-11ea-820c-230b3f543b75.png)

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @kiranmaipappu , I'm not able to reproduce issue by steps you described on clean 2.4-develop EE
**Manual testing scenario:**
- Created a product attribute named "Test" as a Global attribute with type as "Text Filed", scope "Global".
![image](https://user-images.githubusercontent.com/51681379/98727839-42103f80-23a1-11eb-9cd0-bc7765be1ff3.png)
![image](https://user-images.githubusercontent.com/51681379/98727878-518f8880-23a1-11eb-8d7f-cf8eb58819d1.png)
- Create products and add value to `Test` attribute
![image](https://user-images.githubusercontent.com/51681379/98728111-b1862f00-23a1-11eb-89cb-71eef4eb1658.png)
- Create a Related Product Rule
![image](https://user-images.githubusercontent.com/51681379/98727994-7edc3680-23a1-11eb-904f-75730def7c17.png)
![image](https://user-images.githubusercontent.com/51681379/98728023-88659e80-23a1-11eb-8b9a-cb8dfdc24848.png)
![image](https://user-images.githubusercontent.com/51681379/98728038-91567000-23a1-11eb-9c07-5d3dfedbd3cc.png)
- Go to storefront

**Result:**
:heavy_check_mark: The rule is appled for `Simple1` product with `Test`="MAGT2NA_Test3", and the `Simple2` and `Simple3` products  with `Test`="24-MB02" and `Test`="701644329389M" are displayed as related products.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
