### ISSUE TITLE
PayPal Express Checkout button is not displayed with PayPal Braintree by Gene

### ISSUE THREAD

**Issue by sergey-ctrl** [magento/magento2#29243]
### Preconditions (*)

1.Magento ver. 2.4.0-beta2
2.Configure PayPal Express Checkout payment method
https://i.imgur.com/PDenw9M.png
3.Configure Braintree Payments (by GENE Commerce), Enable PayPal through Braintree
https://i.imgur.com/9qBDM3i.png

### Steps to reproduce (*)

1. Go to Checkout, step 2

### Expected result (*)

1. The PayPal Express Checkout button is displayed

### Actual result (*)

1. The PayPal Express Checkout button is not displayed https://i.imgur.com/W38YRDZ.png

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by sergey-ctrl** [comment]
A month has passed, is there any information?

**Comment by namluu** [comment]
Do you have any updates on this, please?

**Comment by jsamhall** [comment]
@namluu @sergey-ctrl Like you I have been waiting for an update on this important problem, so I thought you might appreciate what I found.

We have encountered this problem in our live web store where we wish to use Braintree to process credit cards, and PayPal Express Checkout as another payment option, and specifically NOT using Braintree for PayPal.

I found that when PayPal Express and Braintree Card Payments are both enabled, the `window.paypal` version conflict / already defined error occurs. 

I found that `/vendor/paypal/module-braintree-core/view/frontend/web/js/view/payment/adapter.js` specifies `https://www.paypalobjects.com/api/checkout.js` as a RequireJS dependency, therefore this remote file is fetched and executed regardless of whether or not "Enable PayPal through Braintree" is set to "YES" in Braintree system configuration (therefore, it is needless overhead as Braintree CC processing does not require PayPal SDK). As you will see by viewing that file, it is responsible for assigning `window.paypal` and specifies version `4.0.318`. 

Continuing on with my investigation and findings, when PayPal Express Checkout is enabled as a Payment Method, `vendor/magento/module-paypal/view/frontend/web/js/in-context/paypal-sdk.js` is loaded and retrieves the PayPal JS SDK from `paypal.com/sdk/js?client-id=.....params` which loads the PayPal JS SDK at version `5.0.186` (at least at the time of writing)

As a means of proving my theory, I simply removed the `https://www.paypalobjects.com/api/checkout.js` from `/vendor/paypal/module-braintree-core/view/frontend/web/js/view/payment/adapter.js`, enabled PayPal Express Checkout, and proceeded to checkout. As I expected, version `5.0.186` of the PayPal JS SDK is successfully loaded and the Braintree Credit Card Form functions perfectly alongside the PayPal Express Checkout method.  

There are various ways in which you can address this problem for your own store, so I'll defer that decision to you. I hope this information helps you make that decision!

**Comment by jsamhall** [comment]
AFAIK this issue has yet to be resolved and therefore should not be marked as stale.

**Comment by Kishorchhugani** [comment]
https://drops.meetanshi.com/suokfl

I am Facing Same issue while using paypal braintree and paypal Express Checkout
