### ISSUE TITLE
Orders Lost

### ISSUE THREAD

**Issue by gethubbavv** [magento/magento2#29247]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]
![Magento Order Snip NCWP](https://user-images.githubusercontent.com/68699192/88306048-161c6180-ccbf-11ea-89fc-be87a996d29b.JPG)

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by devchris79** [comment]
I think you are going to need to give more details than a picture of the orders page with a couple of active filters....

What is displayed when the filters are turned off?

![Untitled](https://user-images.githubusercontent.com/43850303/88310425-9070d400-cd07-11ea-9d18-e89559ee828a.png)

**Comment by ajijshekh123** [comment]
Hi @gethubbavv,
Can you please enter the Steps to be reproduced, Actual results and Pre-conditions for this issue? 
Thanks.

**Comment by ajijshekh123** [comment]
Hi @gethubbavv,
Nothing update from your end. So I have closed this issue.
If you have reproduced this issue again please provide proper steps, actual result and expected results and reopen the issue.

Thanks
