### ISSUE TITLE
Magento does not send emails with Content-Disposition: inline headers anymore

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#29258]
Right from the beginning, Magento has always sent emails with Content-Disposition: inline set as a header. This was the default implementation of MIME encoded emails provided by Zend Framework 1. Magento never needed to do anything as it was handled within ZF1.

When Magento moved its mail handling routines to Zend Framework 2, the content-disposition header, along with other functionality, such as mime encoding text based emails so they can be UTF-8 encoded was lost during the transition (This functionality was previously provided by ZF1 by default, but with ZF2 it was now Magento's responsibility to implement). I patched these missing items back around July 2019 with a series of commits (https://github.com/magento/magento2/commit/fa030f284662ea698ea149b1b5de50cc9ea10e68, https://github.com/magento/magento2/commit/226009e90bba3af2c1d2b0ddb3ad9fc5c2b8f362).

Unbeknown to me at that time, ZF2 contained a bug which caused the Content-Disposition: inline header to be UTF-8 encoded which caused some problems with some mail clients adding the body of the message as an attachment.

Because of this issue, another commit was made (https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6) which removed the Content-Disposition: inline header, as removing the header altogether made the email clients that previously had trouble with the incorrectly UTF-8 encoded header, now work.

Laminas-Mail have now fixed the issue in release v2.11.0 so this can now be looked at again, and the Content-Disposition: inline header reintroduced, as it always has been in previous Magento releases.

See for further discussion

https://github.com/magento/magento2/issues/26913
https://github.com/mageplaza/magento-2-smtp/issues/227
https://github.com/magento/magento2/issues/25076
https://github.com/laminas/laminas-mail/issues/2

### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
1. Configure the store in any way you like and trigger an email to be sent

### Expected result (*)
1. Email should be received and have the "Content-Disposition: inline" header, and it should not be UTF-8 encoded.

### Actual result (*)
1. "Content-Disposition: inline" header is not present at all.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40522` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
Grrrrr
