### ISSUE TITLE
Terms and Conditions - Popup Content doesn't respect blockDirective

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#29252]
### Preconditions (*)
1. M 2.3.5-p1

### Steps to reproduce (*)
1. Add a blockDirective  (e.g. {{block class="Magento\\Cms\\Block\\Block" block_id="gtc"}}) to a "Terms and Conditions" (Stores/Terms and Conditions) content.

### Expected result (*)

1. The "Terms and Conditions" popup, shown in frontend checkout should show the content of block "gtc".

### Actual result (*)

1. The popup shows "{{block class="Magento\\Cms\\Block\\Block" block_id="gtc"}}" as text.

Sollution:
This can easily solved by adding a \Magento\Cms\Model\Template\FilterProvider to \Magento\CheckoutAgreements\Model\AgreementsConfigProvider constructor and the content is filtered in getAgreementsConfig().
![image](https://user-images.githubusercontent.com/2369089/88372898-1b4cdf80-cd97-11ea-9862-9c3dd55dbf45.png)
![image](https://user-images.githubusercontent.com/2369089/88373238-c65d9900-cd97-11ea-9e00-3f91af86ab6e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by plastikschnitzer** [comment]
I tried the code @bernd-reindl proposed but for me it ends up with a white checkout page (Magento 2.3.5-p1).

However this feature would really help a lot as Terms and conditions are used in multiple places (CMS pages, Checkout, other extensions)
