### ISSUE TITLE
PHP Fatal error:  Call to a member function getTargetPath() 

### ISSUE THREAD

**Issue by sachan-amit** [magento/magento2#2926]
PHP Fatal error:  Call to a member function getTargetPath() on a non-object in /var/www/html/magento/vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php on line 286, referer: https://xyz.com/admin_irgyjq/admin/import/index/key/efcc5ba93429fea26fde0ec4a8656e3125945d01982f5db2c2549059d7ba8614/

**Comment by katmoon** [comment]
Hi,

Could you provide some additional information such as:
- which action caused the exception
- content of var/log/exception.log if available?

Thanks,
Kateryna.

**Comment by sachan-amit** [comment]
When I am trying to import catalog, I get this error. Validation process is completed successfully but could not import records due to above exception.

**Comment by sachan-amit** [comment]
```
[Sun Jan 24 00:52:09.194471 2016] [:error] [pid 25891] [client 122.177.140.255:54662] PHP Fatal error:  Call to a member function getTargetPath() on a non-object in /var/www/html/magento/vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php on line 266, referer: https://128.199.175.75/admin_yfbuew/admin/import/index/key/8fa97800146d98631ef5adfcb489b971bf8591c1c896274c7cd8ccbedca9171a/
```

**Comment by Fel1xx** [comment]
Seems the issue comes from method AfterImportDataObserver::currentUrlRewritesRegenerate(). It calls two methods - generateForAutogenerated() and generateForCustom(). Both of them are returning an array containing rewrite object. However currentUrlRewritesRegenerate adds this array into returned array (see line 362), as a result getting an array of array which is processed in a loop in caller method generateUrls() and trying to call getTargetPath() method of an array.

I've created a pull request with a quick fix, see https://github.com/magento/magento2/pull/3143

**Comment by shuaiZend** [comment]
```
<b>Fatal error</b>:  Uncaught Error: Call to a member function getTargetPath() on array in /home/wwwroot/mysite.com/vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php:266
Stack trace:
#0 /home/wwwroot/mysite.com/vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php(142): Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver-&gt;generateUrls()
#1 /home/wwwroot/mysite.com/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver-&gt;execute(Object(Magento\Framework\Event\Observer))
#2 /home/wwwroot/mysite.com/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault-&gt;_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver), Object(Magento\Framework\Event\Observer))
#3 /home/wwwroot/mysite.com/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault-&gt;dispatch(Array, Object(Magento\Framework\Event in <b>/home/wwwroot/mysite.com/vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php</b> on line <b>266</b><br />
```

**Comment by katmoon** [comment]
Thank you for the details!

We have created internal ticket `MAGETWO-50678` for further investigation.

**Comment by vkublytskyi** [comment]
Issue [already fixed](https://github.com/magento/magento2/commit/76968a8)

**Comment by katmoon** [comment]
Closing the ticket as fixed.
