### ISSUE TITLE
Changes to Bundle indexer in 2.3.5 cause index failure

### ISSUE THREAD

**Issue by davidwindell** [magento/magento2#29264]
After upgrading from Magento 2.3.4-p2 to 2.3.5-p1 on our store an integrity constraint happens when the price index runs. This in turn prevents certain (not all!) fixed price bundles from appearing on the front-end. I think it is very unlikely I'll be able to easily reproduce this on a vanilla instance.

The problem seems to be caused by [this commit](https://github.com/magento/magento2/commit/7fa6b5ee674b838e8e1c707d3ad37074af3b1691). @mastiuhin-olexandr are you able to bring this up with whoever was responsible for MC-25251?

Changing line [519](https://github.com/magento/magento2/commit/7fa6b5ee674b838e8e1c707d3ad37074af3b1691#diff-72d9599f5038053ef419be94c49948d5R519) like so fixes the issue as the insertFromSelect applies `ON DUPLICATE KEY UPDATE`.

```
$query = $select->insertFromSelect($this->getBundleSelectionTable());
//$query = $select->crossUpdateFromSelect($this->getBundleSelectionTable());
```

### Preconditions (*)

1. Magento 2.3.5-p1 (
2. Bundle products with fixed price mode

### Steps to reproduce (*)
1. Create a bundle product with fixed price mode
2. Run `bin/magento indexer:reindex catalog_product_price`
3. Index fails and products are missing from front-end

### Expected result (*)
1. Index should complete.

### Actual result (*)
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3002-0-1' for key 'PRIMARY', query was: UPDATE `catalog_product_index_price_bundle_sel_tmp`
 INNER JOIN `catalog_product_index_price_bundle_tmp` AS `i`
 INNER JOIN `catalog_product_entity` AS `parent_product` ON parent_product.entity_id = i.entity_id
 INNER JOIN `catalog_product_bundle_option` AS `bo` ON bo.parent_id = parent_product.entity_id
 INNER JOIN `catalog_product_bundle_selection` AS `bs` ON bs.option_id = bo.option_id
 INNER JOIN `catalog_product_bundle_selection_price` AS `bsp` ON bs.selection_id = bsp.selection_id AND bsp.website_id = i.website_id
SET `catalog_product_index_price_bundle_sel_tmp`.`entity_id` = `i`.`entity_id`, `catalog_product_index_price_bundle_sel_tmp`.`customer_group_id` = `i`.`customer_group_id`, `catalog_product_index_price_bundle_sel_tmp`.`website_id` = `i`.`website_id`, `catalog_product_index_price_bundle_sel_tmp`.`option_id` = `bo`.`option_id`, `catalog_product_index_price_bundle_sel_tmp`.`selection_id` = `bs`.`selection_id`, `catalog_product_index_price_bundle_sel_tmp`.`group_type` = IF(bo.type = 'select' OR bo.type = 'radio', 0, 1), `catalog_product_index_price_bundle_sel_tmp`.`is_required` = `bo`.`required`, `catalog_product_index_price_bundle_sel_tmp`.`price` = LEAST(IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty, IFNULL((IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)), IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty)), `catalog_product_index_price_bundle_sel_tmp`.`tier_price` = IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)
WHERE (i.price_type=1)
```

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by davidwindell** [comment]
Duplicating the bundle product `3002` that was causing this error and deleting the original version seems to have solved this for now, so I will close - but I would still be good to have your thoughts on the potential cause.

**Comment by romainruaud** [comment]
Same issue here, I think that's a valid one, seems to appear randomly.

I'll check replacing the crossUpdateFromSelect by insertFromSelect since it also appears that the crossUpdateFromSelect is dramatically slow on my version of MariaDB. It also appears to be slow with other DB versions as described in #31219

**Comment by sky-hub** [comment]
@romainruaud , you may want to check this also: https://github.com/magento/magento2/issues/31219#issuecomment-1541639283
