### ISSUE TITLE
Allow updating/creating multiple product attribute values at once.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#29260]
### Summary (*)
I would like to update/create multiple catalog product attribute options at once with a single PUT (Or it seems I have to use POST)

But the API only lets me specify option: {} not options: [].

### Examples (*)
PUT /V1/products/attributes/{attributeCode}/options

```json
{
  options: [
    { label: "NewOptionValueExample" },
    { label: "UpdateExample", value: "8" }
  ]
}
```

Does the Magento 2 Rest API have POST and PUT the wrong way around??
https://www.soapui.org/learn/api/rest-request-method-verbs/

### Proposed solution
Let us use options: []
PUT should update if already exist based on value (As option value id.)
POST should create, if already exist should error invalid data or allow it?

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by LiamKarlMitchell** [comment]
I can't seem to update existing attribute option values even if I set the value to a string of the id.

**Comment by engcom-Delta** [comment]
This possibility should be discussed in the scope of **Feature Request**
For now POST endpoint for /V1/products/attributes/{attributeCode}/options does not provide possibility to create multiple options per request
