### ISSUE TITLE
Inconsistent js-translation.json generation between versions of libicu (used by php intl)

### ISSUE THREAD

**Issue by Luwdo** [magento/magento2#29268]
### Preconditions (*)

1. Fresh Magento 2.3.5
2. Load application source into a machine with an older version of libicu (for my test I used centos/php-73-centos7)
3. Load same application source into machine running newer version of libicu (for my test I used php:7.3-cli-stretch)

### Steps to reproduce (*)

1. run static:content:deploy in both machines and extract the source for comparison
2. and do a diff -qr centos_compiled_folder ubunutu_compiled_folder

### Expected result (*)

1. pub/static and var/view_preprocessed should be identical between environments

### Actual result (*)

1. the following js-translation.json files differ

```
Files centos7/pub/static/adminhtml/Magento/backend/en_US/js-translation.json and ubuntu/pub/static/adminhtml/Magento/backend/en_US/js-translation.json differ
Files centos7/pub/static/frontend/Magento/blank/en_US/js-translation.json and ubuntu/pub/static/frontend/Magento/blank/en_US/js-translation.json differ
Files centos7/pub/static/frontend/Magento/luma/en_US/js-translation.json and ubuntu/pub/static/frontend/Magento/luma/en_US/js-translation.json differ
Files centos7/var/view_preprocessed/pub/static/adminhtml/Magento/backend/en_US/js-translation.json and ubuntu/var/view_preprocessed/pub/static/adminhtml/Magento/backend/en_US/js-translation.json differ
Files centos7/var/view_preprocessed/pub/static/frontend/Magento/blank/en_US/js-translation.json and ubuntu/var/view_preprocessed/pub/static/frontend/Magento/blank/en_US/js-translation.json differ
Files centos7/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json and ubuntu/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json differ

```

every file differs in the exact same way
```
diff --git a/centos7/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json b/ubuntu/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json
index 29d55c8..9ac1e6b 100644
--- a/centos7/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json 
+++ b/ubuntu/var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/js-translation.json
@@ -1 +1 @@
-{"Securely login into our website using your existing Amazon details.":"Securely login to our website using your existing Amazon details.","There are {placeholder} messages requires your attention.":"There are {0} messages requires your attention."}
\ No newline at end of file
+{"Securely login into our website using your existing Amazon details.":"Securely login to our website using your existing Amazon details."}
\ No newline at end of file
```

 This new phrase is being read from: [vendor/magento/module-ui/view/base/web/js/grid/editing/editor.js:525](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/app/code/Magento/Ui/view/base/web/js/grid/editing/editor.js#L524)

The reason its showing up is because the translate logic is getting a different value out of the translate call then what it passed in, even when no arguments are passed and no translations are actually done.

I have determined how and why this happens:
in [vendor/magento/module-translation/Model/Js/DataProvider.php](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/app/code/Magento/Translation/Model/Js/DataProvider.php#L110)
 calls ```$this->translate->render()``` this calls [vendor/magento/framework/Phrase/Renderer/Composite.php](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/lib/internal/Magento/Framework/Phrase/Renderer/Composite.php#L46) which calls the following renders in this order:

1. Magento\Framework\Phrase\Renderer\Composite
2. Magento\Framework\Phrase\Renderer\Translate
3. Magento\Framework\Phrase\Renderer\MessageFormatter
4. Magento\Framework\Phrase\Renderer\Placeholder
5. Magento\Framework\Phrase\Renderer\Inline

there is a debug output from this particular phase being run on the centos system:
```result: 0
phrases: Array
(
    [0] => You have successfully saved your edits.
    [1] => There are {placeholder} messages requires your attention.
)

class: Magento\Framework\Phrase\Renderer\Composite
translated phrase: You have successfully saved your edits.
render class: Magento\Framework\Phrase\Renderer\Translate
translation result: Array
(
    [0] => There are {placeholder} messages requires your attention.
    [1] => There are {placeholder} messages requires your attention.
)

formater locality: en_US
render class: Magento\Framework\Phrase\Renderer\MessageFormatter
translation result: Array
(
    [0] => There are {placeholder} messages requires your attention.
    [1] => There are {placeholder} messages requires your attention.
    [2] => There are {0} messages requires your attention.
)

render class: Magento\Framework\Phrase\Renderer\Placeholder
translation result: Array
(
    [0] => There are {placeholder} messages requires your attention.
    [1] => There are {placeholder} messages requires your attention.
    [2] => There are {0} messages requires your attention.
    [3] => There are {0} messages requires your attention.
)

render class: Magento\Framework\Phrase\Renderer\Inline
translation result: Array
(
    [0] => There are {placeholder} messages requires your attention.
    [1] => There are {placeholder} messages requires your attention.
    [2] => There are {0} messages requires your attention.
    [3] => There are {0} messages requires your attention.
    [4] => There are {0} messages requires your attention.
)
```

you can see that when it hits [Magento\Framework\Phrase\Renderer\MessageFormatter](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/lib/internal/Magento/Framework/Phrase/Renderer/MessageFormatter.php#L43) it transforms to remove the labeled placeholder with a '0'.

The function that is doing this is the call to
```
$result = \MessageFormatter::formatMessage($this->translate->getLocale(), $text, $arguments);
```
in : [Magento\Framework\Phrase\Renderer\MessageFormatter](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/lib/internal/Magento/Framework/Phrase/Renderer/MessageFormatter.php#L43)

this function comes from php intl, which on centos systems:
```
php -r "echo \MessageFormatter::formatMessage('en_US', 'There are {placeholder} messages requires your attention.', []);"
```
returns:
```
There are {0} messages requires your attention
```

and on ubuntu
returns:
```
There are {placeholder} messages requires your attention
```

This is a pretty minor issue however in the [vendor/magento/module-ui/view/base/web/js/grid/editing/editor.js:525](https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/app/code/Magento/Ui/view/base/web/js/grid/editing/editor.js#L524)

you have the following:
```
        countErrorsMessage: function () {
            return $t('There are {placeholder} messages requires your attention.')
                .replace('{placeholder}', this.countErrors());
        },
```

on centos systems that 'placeholder' won't exist once js translations are run because static content deploy usage of messageFormat has transformed it to a '0'

if you run ```php --ri intl``` on both systems you will see the libicu versions are different.

After some experimentation I found that libicu is not so simple to update for centos 7 in-fact its not a recommended thing to do outside of updating the OS to centos 8.

I am not sure if if the best solution is to update the message formatter to detect if the placeholder has been transformed and restore the named placeholders or maybe if we are translating with no arguments its not needed to run it through the messageFormat function at all.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by orbitrod** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @orbitrod. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @orbitrod, here is your [Magento instance](https://i-29268-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29268-2-4-develop.instances.magento-community.engineering/admin_ef59](https://i-29268-2-4-develop.instances.magento-community.engineering/admin_ef59)
Login: `23e98ea3` Password: `662abe20e391`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
this is not stale
