### ISSUE TITLE
Customer unable to place order with new address

### ISSUE THREAD

**Issue by martynas-al** [magento/magento2#29288]
### Preconditions (*)

1. Magento version: 2.3.5-p1
2. Customer object needs to have extension attribute data

### Steps to reproduce (*)

1. Log in as a customer which has extension attribute data
2. Add product to cart
3. In checkout step add new shipping address and add checkbox to save it.
4. Place an order with newly added address.

### Expected result (*)

1. Order created successfully

### Actual result (*)

1. I get "Invalid state change requested" error message

I did some digging around and basically figured out why this happens.
Magento calls `Magento\Quote\Model\ChangeQuoteControl::isAllowed` before quote is saved and performs a check to see if `customer_id` in quote and in user's context match and it doesn't if customer added new shipping address which needs to be saved.

The `customer_id` doesn't match because a couple of steps before `Magento\Quote\Model\Quote::setCustomer` is called.
In this method customer object is beeing flattened and the flattened values are set as quote values.
While customer flattening happens, `Magento\Framework\Convert\ConvertArray::toFlatArray` is called and this is where the issue happens. If your customer object has extension attributes which have `id` field in them, then after flattening customer object's id becomes the id value of the last processed extension attribute's ID. Basically, because of recursive calls `array_merge` overrides previously set values.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MeCapron** [comment]
Hello,

I reopen this issue as I bump into this earlier.

To add a bit explanations just look at : 

```php
    public function toFlatArray(
        ExtensibleDataInterface $dataObject,
        $skipCustomAttributes = [],
        $dataObjectType = null
    ) {
        $dataObjectArray = $this->toNestedArray($dataObject, $skipCustomAttributes, $dataObjectType);
        return ConvertArray::toFlatArray($dataObjectArray);
    }
```

in `magento/framework/Api/ExtensibleDataObjectConverter.php`

Having the same attribute name as customer one in your extension attribute will result in your extension attribute overriding customer one.

Example : 

```json
{
    "id": "172",
    "extension_attributes": {
         "posts": [
               {
                    "id": "187",
                    "desc": "test"
               }
         ]
    }
}
```

Will give the customer with the wrong ID, 187 in this case.

I think that the "ConvertArray::toFlatArray" method must skip extension attributes in its transform process.

Can we have any help on this?

Thanks you
