### ISSUE TITLE
 Add URL Rewrite for a Category from admin - blank page

### ISSUE THREAD

**Issue by bhavin88** [magento/magento2#2929]
Hello,

When i try to add url rewrite for a category from admin, i get a blank page. See attached.

Thanks,
Bhavin Bhalodia.
![category_add_url_rewrite_from_admin](https://cloud.githubusercontent.com/assets/12870148/12197370/8718e9e8-b62c-11e5-88b4-330302e884da.png)

**Comment by katmoon** [comment]
Hi,

Are there any errors in the browser console or `var/log/` folder?
Which [Magento mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) do you use?

Thanks,
Kateryna

**Comment by bhavin88** [comment]
Hello,

Error in console
SyntaxError: JSON.parse: unterminated string at line 1 column 354 of the JSON data
data: JSON.parse(data)
File : http://127.0.0.1/magento2/pub/static/adminhtml/Magento/backend/en_US/mage/apply/main.js

Thanks,
Bhavin Bhalodia.

**Comment by katmoon** [comment]
Are there any similar errors on other pages in Admin?
Could you clear browser cache and Magento cache `rm -rf var/* pub/static/*` and check if the error reproduces, please?

Thanks,
Kateryna.

**Comment by bhavin88** [comment]
I have deleted all the files from rm -rf var/\* pub/static/\* and now no any new files generated inside that folder. 
So now no any css and js are loaded in my frontend and backend.

Please help.

![frontend](https://cloud.githubusercontent.com/assets/12870148/12470677/28eb51d6-c01c-11e5-8dd7-1936023bf48c.png)

**Comment by katmoon** [comment]
You can try to deploy static files manually using
`bin/magento setup:static-content:deploy`
Read more here: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html

Again, which Magento mode do you use?

**Comment by bhavin88** [comment]
I am using the default mode. Still i am getting error in console.
Now all the files are generated again. Thank you very much.

**Comment by katmoon** [comment]
Thanks for posting the issue, Bhavin.
Internal ticket is MAGETWO-48218

**Comment by katmoon** [comment]
Hi, Bhavin,

Could you clear browser cache and recheck if the error reproduces?

How did you [install Magento](http://devdocs.magento.com/guides/v2.0/install-gde/continue.html): from github, composer or downloaded from Magento site?

**Comment by mslabko** [comment]
Hi @bhavin88 ,
the issue was fixed in  https://github.com/magento/magento2/commit/0b9e64a8cf5130de28333aac1afcb1ff36bcbaf8
Thank you for reporting.
