### ISSUE TITLE
UI component could not be rendered because of system exception

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#29293]
### Preconditions (*)

1. Magento 2.3.5-p1
2.php 7.2.3

### Steps to reproduce (*)

1. Upgrade magento from 2.3.1 to 2.3.5-p1
2. open order grid and choose to filter by allocated sources.

### Expected result (*)

1. It should filter by that field.
2.

### Actual result (*)

1. Returns error UI component could not be rendered because of system exception
2.

after looking in logs found following: 
main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allocated_sources' in 'order clause', query was: SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` ORDER BY allocated_sources ASC
 LIMIT 20 {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allocated_sources' in 'order clause', query was: SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` ORDER BY allocated_sources ASC

it seem column was not made when magento was upgraded. setup:upgrade doesn't make new database fields.

running command setup:db:status it gives me following:
Declarative Schema is not up to date
Run 'setup:upgrade' to update your DB schema and data.

after running setup:upgrade and checking status it still returns same status as before:
Declarative Schema is not up to date
Run 'setup:upgrade' to update your DB schema and data.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mtsmtyuta** [comment]
Had the same issue here and this error freezes up the admin sales page. I manually added the column in sales_order_grid to solve the error temporarily so I could click on another column.

**Comment by vmartins** [comment]
I have the same problem:
```
main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allocated_sources' in 'order clause', query was: SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` ORDER BY allocated_sources ASC LIMIT 50 {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allocated_sources' in 'order clause', query was: SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` ORDER BY allocated_sources ASC LIMIT 50 at /path/to/magento/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allocated_sources' in 'order clause' at /path/to/magento/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
```

This happened after I tried to sort by the column "Allocated sources" on the order screen.

**Environment**
- Magento 2.4.0 (migrated from 1.9.x)
- PHP 7.4

**Comment by jbrada** [comment]
Hello,

I've just reproduced the issue on 2.4.1 Open Source.

**Environment**
- Magento 2.4.1
- PHP 7.4

**Comment by an4rei** [comment]
Issue reproduced on magento 2.4.2. Fixed with @vmartins above.
