### ISSUE TITLE
PHP build-in webserver readme cmd line installation command is outdated

### ISSUE THREAD

**Issue by progreg** [magento/magento2#29299]
### Preconditions (*)

Since ElasticSearch is required from 2.4 version we need to update README for a build-in webserver. 

There are missing ElasticSearch params that are required by default. Also, I'm also confused because copy-paste of installation command is not working, new line glue character should be added.

### Examples (*)
1. Missing ES params result:
https://prnt.sc/tpj4op

2. No glue character result:
https://prnt.sc/tpj62o

**Steps to reproduce:**
Open phpserver/README.MD
copy How to install Magento command and paste into the terminal

**Actual Result:**

**Expected Result:**
The installation must be successful

### Proposed solution
https://github.com/magento/magento2/pull/29300

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36471` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @progreg. Thank you for your report. 
The issue has been fixed in magento/magento2#29300 by @progreg in 2.4-develop branch
Related commit(s):
 - [80f41958e039e3275488f034bba4b5d874d0da9c](https://github.com/magento/magento2/commit/80f41958e039e3275488f034bba4b5d874d0da9c)
 - [0747383b91da67909ab823434f434dae1b465f5e](https://github.com/magento/magento2/commit/0747383b91da67909ab823434f434dae1b465f5e)
 - [91cffc078091c8e30ea429c206d2e3a786813dd6](https://github.com/magento/magento2/commit/91cffc078091c8e30ea429c206d2e3a786813dd6)

The fix will be available with the upcoming 2.4.1 release.
