### ISSUE TITLE
Magneto 2.3.4 - Disk Usage getting full

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#29296]
### Preconditions (*)

1. Magneto 2.3.4
2. CLOUDLINUX 6.10 vmware
3. 8Gb ram
4. 3 core CPU
5. Crazy Domain VPS server

### Steps to reproduce (*)

1. My server disk getting full
Screenshot
https://prnt.sc/tpak37

2.

### Expected result (*)

1. Server has to work normally without full disk
2.

### Actual result (*)

1. My server disk getting full
Screenshot
https://prnt.sc/tpak37

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @gilbertsohal , thank you for your report

The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
