### ISSUE TITLE
When creating a shipment or an Invoice, in different store view, payment information has been overwritten with default store view.

### ISSUE THREAD

**Issue by francescorm** [magento/magento2#29304]
### Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)
1. Create 2 store view with different payment information on banktransfer
2. Place an order.
3. on order view, payment information are okey.
4. create a shipment or an invoice.
5. payment information change with the default store view.

### Expected result (*)

Payment information are associated with the store view

### Actual result (*)
Payment information are overwritten

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by francescorm** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @francescorm. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @francescorm, here is your [Magento instance](https://i-29304-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29304-2-4-develop.instances.magento-community.engineering/admin_c3de](https://i-29304-2-4-develop.instances.magento-community.engineering/admin_c3de)
Login: `45d3d73f` Password: `63e6309c8281`
Instance will be terminated in up to 3 hours.

**Comment by thompalstra** [comment]
Are you using different or the same increment ID's for the different stores?

**Comment by francescorm** [comment]
Yes

**Comment by engcom-Delta** [comment]
Hi @francescorm thank you for your report, I'm not able to reproduce issue by steps you described on 2.4-develop
**Result:**
![Peek 2020-08-14 15-54](https://user-images.githubusercontent.com/51681379/90251722-e9cfad00-de46-11ea-8bfa-bd8b71b9dad0.gif)

If you'd like to update the issue, please reopen it.
