### ISSUE TITLE
Bad source.csv file when downloading translation

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#2930]
I don't know if this the right place to post this, but I don't know where to report this bug.

I am a contributor for magento 2 Spanish language, so I am translating all texts in https://crowdin.com/project/magento-2/es-ES system.

So far, so good. However, when I download resulting source.csv file I realized it is completely wrong.

As an example. Translation for "Create an account" is set as "Crear una cuenta" in the crowdin interface, but the resulting source.csv file shows translation as "Default Billing Address"

Another sample, this is the part of the file:

"All","Todo","module","Magento_AdminGws,Magento_Catalog,Magento_CatalogSearch,Magento_CustomerSegment,Magento_Integration,Magento_Sitemap,Magento_User,Magento_Widget"
"None","Ninguno","module","Magento_AdminGws,Magento_Bundle,Magento_Catalog,Magento_CustomerCustomAttributes,Magento_Dhl,Magento_Eav,Magento_Fedex,Magento_GiftRegistry,Magento_GiftWrapping,Magento_$
"Allowed Scopes","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to delete this item(s): %1.","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to apply some of the rule updates.","Ámbitos permitidos","module","Magento_AdminGws"
"Please assign this entity to a store view.","Ámbitos permitidos","module","Magento_AdminGws"
"You can create orders only in an active store.","Ámbitos permitidos","module","Magento_AdminGws"
"Please assign this item to a store view.","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to save this item.","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to delete this item.","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to view this item.","Ámbitos permitidos","module","Magento_AdminGws"
"Please specify at least one website or one store group.","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to set All Scopes to a Role.","Ámbitos permitidos","module","Magento_AdminGws"
"Incorrect website ID: %1","Ámbitos permitidos","module","Magento_AdminGws"
"You need more permissions to access website ""%1"".","Ámbitos permitidos","module","Magento_AdminGws"

As you see, this is complete wrong.

Please help.
Jaime

**Comment by ghost** [comment]
How did you create `source.csv`?

**Comment by jaimestuardo** [comment]
I did not create it directly. I have just downloaded the generated file from https://crowdin.com/project/magento-2/es-ES which is supposed to be the official translation site for Magento 2.

**Comment by cspruiell** [comment]
@ jaimestuardo , thank you for reporting the issue. Internal ticket MAGETWO-48346

**Comment by wert2all** [comment]
Ticket MAGETWO-48346 was closed
