### ISSUE TITLE
Input type of customizable option doesn't get returned through GraphQL

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2#29302]
### Preconditions

Github branches `magento2/2.4-develop` and `architecture/master`

### Steps to reproduce

The GraphQL type `SelectedCustomizableOption` is used in multiple places across the Magento GraphQL modules to get the currently selected customizable option of a product through GraphQL. There are various field types for this such as text, textarea, select, multiselect, checkbox, etc. Currently, there's no way for a frontend using GraphQL to know how to render the SelectedCustomizableOption. Yes, the format varies according to different types, but the format is the same for input types of the same category. I believe there's no way to differentiate between a text and a textarea of `SelectedCustomizableOption`. Same with the different select input types. 

The associated resolver class _does_ return the 'type of input' from Magento (ref: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/CustomizableOption.php#L60), but the associated GraphQL schema does not define a field for the same (ref: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L346) and hence the 'type of input' doesn't get returned. 

Upon some searching, the GraphQL coverage docs did have the 'type of input' as a field in `SelectedCustomizableOption` a couple of months ago (ref: https://github.com/magento/architecture/blob/673438109bbf63d819e96c373ef7622206ff7f9b/design-documents/graph-ql/coverage/add-items-to-cart/AddSimpleProductToCart.graphqls#L59) until the new coverage docs (ref: https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/Cart.graphqls#L114) was matched according to the current GraphQL schema and was thus, removed. 

### Expected result

Consistency.

Is the field `type` required to render the input type on the frontend?
-  If yes, we need to add the field back to the schema.
-  If not, we need to remove it from the resolver for consistency and to avoid confusion for developers in the future.

### Actual result

The field `type` was removed from the QuoteGraphQl module in this commit: https://github.com/magento/magento2/commit/1315577e2099637207f02deec48607d81f7cde46#diff-795a33fde881f18aba5165a5a8c7513fL317 and from the architecture coverage docs a couple months ago and now the code is inconsistent and causes confusion for developers.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by munkhulzii** [comment]
@nrkapoor For me, no clear definition of the expected result was given here. Consistency yes, but should I remove the field or add it everywhere?

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by dineshvb** [comment]
@magento add to contributors team

**Comment by dineshvb** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, @dineshvb. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37414` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by drpayyne** [comment]
Hi @magento-engcom-team, why was neither the PR, nor the issue updated with the existence and the status of an internal issue and PR? This is counterproductive of having an open source repository... almost two months of the linked PR work is useless now?
