### ISSUE TITLE
Unable to log into Admin after clean install (without SMTP)

### ISSUE THREAD

**Issue by DigitalStartupUK** [magento/magento2#29312]
### Preconditions (*)

1. Apache 2.4
2. PHP 7.4
3. MySQL 8
4. Elasticsearch 7
5. Magento 2.4.0

### Steps to reproduce (*)

1. Clean install of Magento 2.4 (via composer)
2. Creation of admin account via CLI (part of setup:install command)

### Expected result (*)

1. Logging into Magento 2.4 for the first time allows immediate Google 2FA setup

### Actual result (*)

1. Logging into Admin for the first time presents a warning "Failed to send the message. Please contact the administrator. You need to configure Two-Factor Authorization in order to proceed to your store's admin area An E-mail was sent to you with further instructions". An email is required to complete 2FA. Without an SMTP enabled server, there is no way of retrieving the link to complete 2FA.

![Failed without SMTP enabled](https://i.stack.imgur.com/QOeN0.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

<hr>

If an SMTP enabled server is required to send a 2FA link to allow for an Admin to complete a first time login, then I feel this should be added as a [prerequisite](https://devdocs.magento.com/guides/v2.4/install-gde/install-resource-diagram.html)

However, if there is a way to get to the 2FA QR page without the need to receive an email then this should be documented more clearly.

I am aware of the [Two-Factor Authentication (MFTF)](https://devdocs.magento.com/guides/v2.4/security/two-factor-authentication.html) documentation. Stating that you could bypass this by creating a "Base32-encoded string for the shared secret value" and then "Use the following key to add the encoded value to the MFTF .credentials file."

However, the documentation doesn't provide enough details on the requirements to do this. It also insinuates that this procedure is preferable for a Testing environment and not Development/Production.

If it turns out that these MFTF steps are considered "safe" to complete in a Development/Product environment then it would definately improve QoL if these variables could be set through the `bin/magento setup:install` values as stated in the [Install the Magento software](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-install.html#instgde-install-cli-magento) Documentation.

**Comment by speedupmate** [comment]
It's not directly related as this issue talks that smtp should be a documented requirement but current workaround for dev environments (that don't need to have smtp set up) is simply to disable 2fa 

`bin/magento mo:di Magento_TwoFactorAuth `

**Comment by DigitalStartupUK** [comment]
But at some point, 2FA needs to be enabled during Development/Production. And there is probably an argument that states "well, surely in a Development/Production environment you would have an SMTP enabled server." But speaking from experience, myself and many others use 3rd party SMTP providers - Which are normally configured in the Admin Backend. It just seems like a really overlooked part of the installation/setup process. What's the point of enforcing 2FA on installation to only immediately disable it? 

**I'd simply prefer a simple CLI `config:set` command to generate the same URL that gets sent in the Email. Or even better, have the URL output with the Admin Backend URL notification that you see on successful install.**

I'm trying not to sound negative and whiny, but this lack of clarity is frustrating.

**Comment by ketby** [comment]
Hi, i'am exactly on the same point ... same error, same step ... i will try another solution

**Comment by PawelP1977** [comment]
Hi,
What is another solution?

**Comment by MichaelThessel** [comment]
What a nightmare. Same issue here. This is the first time I encountered a 2fa setup situation that requires email. Usually you log into admin, enable 2fa and then set up the token logged into admin.

Does anyone know how to re-trigger that email? I didn't have SMTP set up on my dev install when I tried to log in the first time. 

In addition the readme (`vendor/magento/module-two-factor-auth/README.md`)  that comes with the module has incorrect instructions.:

```
If you messed up with two factor authentication you can disable it from command-line:    
                                                                                     
`php bin/magento msp:security:tfa:disable`  
```

This command doesn't exist.

```
Table `core_config_data`:                                                            
* `msp/twofactorauth/enabled`: Set to zero to disable 2fa globally              
```

This doesn't work.

I don't just want to disable the module because I have config.php in source control.

**Comment by MichaelThessel** [comment]
In case anyone needs a temporary workaround to get this working without having SMTP set up:

**Comment by MichaelThessel** [comment]
In case anyone needs a temporary workaround to get this working without having SMTP set up:
1. navigate to /admin and log in
2. you should see the 2FA screen now
3. add `var_dump($url);die;` on line 86 in `vendor/magento/module-two-factor-auth/Model/EmailUserNotifier.php`
4. refresh /admin
5. copy the URL that is displayed
6. remove the var_dump
7. use the URL copied earlier to navigate to the 2FA setup

**Comment by isaacBats** [comment]
A great Magento MX developer has created a module to disable double authentication.
This is the repo [Module_EnableDisableTFA](https://github.com/wolfsellers/module-enabledisabletfa).
You can also install it from composer `composer require wolfsellers/module-enabledisabletfa`

by @Rus0

**Comment by sudhanshu-bajaj** [comment]
Temporary solution to kick start your development, just disable **Magento_TwoFactorAuth** module. It worked for me.

`bin/magento module:disable Magento_TwoFactorAuth`

**Comment by phanku** [comment]
Great security feature added for that administration login section of Magento however I have also ran into another weird issue that personally has stopped me from being able to set up 2FA on a fresh install. My issue is that magento does not use the domain name set for the outgoing email when sending the email out to set up 2FA on a fresh install instead it sends the email from `owner@example.com`. I know normally that might not be a big issue but when sending emails from a server on a more security conscious Enterprise network that email may never actually go to the intended target because of the email domain of `@example.com`. 

I have now disabled the Magento_TwoFactorAuth module as described above and have managed to login to the admin interface but I am now in the process of figuring out how to reenable/set up 2FA.

**Comment by EstebanAorta** [comment]
Did you get it to work?

**Comment by w0d4** [comment]
I see the same problem. I cannot get 2FA to work, since the mail is sent from owner@example.com
Since I'm working with a more secure mailserver, I cannot sent mails from example.com domain.
I suggest to add a parameter during installation to set the owners E-Mail adress.

**Comment by oviliz** [comment]
Speechless @magento-admin ...

**Comment by xekon** [comment]
Dropping this here for anyone that might be having trouble setting up the bare minimum to get mail sending and to also override the address owner@example.com:
```
===============================================================================
configure mail
===============================================================================
sudo apt install -y mailutils
sudo dpkg-reconfigure postfix

  Internet Site
  shop.YourDomain.com
  (blank)
  localhost.YourDomain.com, localhost, shop
  no synchronous updates
  127.0.0.0/8
  0
  +
  ipv4

sudo nano /etc/postfix/main.cf

myhostname = shop.YourDomain.com
mydestination = localhost.YourDomain.com, localhost, shop
inet_interfaces = loopback-only
masquerade_domains = YourDomain.com

sudo nano /etc/hosts
-------------------------------------------
127.0.1.1 shop.YourDomain.com shop
-------------------------------------------

sudo systemctl restart postfix

echo "magento postfix test" | mail -s "Testing magento postfix" xekon@YourDomain.com

  check status:
sudo postqueue -p

  if it broke, read the error then delete it:
sudo postsuper -d ALL

-------------------------------------------------------------------------------
If having problems, like app trying to send mail with non existing account
such as owner@example.com, you can overwrite the address like this:
-------------------------------------------------------------------------------
sudo nano /etc/postfix/generic
-------------------------------------------
owner@example.com    owner@YourDomain.com
-------------------------------------------

sudo nano /etc/postfix/main.cf
-------------------------------------------
smtp_generic_maps = hash:/etc/postfix/generic
-------------------------------------------

sudo postmap /etc/postfix/generic
sudo /etc/init.d/postfix reload

At this point, I logged back out of Magento admin, then back in again,
the email was successfully received.
===============================================================================
```

**Comment by fj-sfd** [comment]
Same issue with me while following [Installation quick reference (tutorial)](https://devdocs.magento.com/guides/v2.4/install-gde/install-quick-ref.html) from Magento

for now I have disabled module (until I setup SMTP), as suggested by @speedupmate 
bin/magento mo:di Magento_TwoFactorAuth

**Comment by xekon** [comment]
Dropping this here for anyone having trouble configuring their mail in order to activate the 2FA.
To clarify, you do this on your Magento2 host, not your mail server.
Once finished just log out of Magento2 WebUI, then log back, you should receive the email.
```
===============================================================================
configure postfix to be able to send mail
===============================================================================
sudo apt install -y mailutils
  (after this first line, sudo is active, can paste entire block below)

echo "${HOSTNAME}.YourDomain.com" | sudo tee /etc/mailname
echo "/.+/ admin@YourDomain.com" | sudo tee /etc/postfix/sender_canonical
echo "/.+/ admin@YourDomain.com" | sudo tee /etc/postfix/recipient_canonical
#echo "/.*root.*/ admin@YourDomain.com" | sudo tee /etc/postfix/recipient_canonical
#echo "/.*asterisk.*/ admin@YourDomain.com" | sudo tee --append /etc/postfix/recipient_canonical
echo "myhostname = ${HOSTNAME}.YourDomain.com" | sudo tee /etc/postfix/main.cf
echo "mydestination = localhost.YourDomain.com, localhost, ${HOSTNAME}" | sudo tee --append /etc/postfix/main.cf
echo "masquerade_domains = YourDomain.com" | sudo tee --append /etc/postfix/main.cf
echo "smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)" | sudo tee --append /etc/postfix/main.cf
echo "sender_canonical_maps = regexp:/etc/postfix/sender_canonical" | sudo tee --append /etc/postfix/main.cf
echo "recipient_canonical_maps = regexp:/etc/postfix/recipient_canonical" | sudo tee --append /etc/postfix/main.cf
echo "biff = no" | sudo tee --append /etc/postfix/main.cf
echo "append_dot_mydomain = no" | sudo tee --append /etc/postfix/main.cf
echo "alias_maps = hash:/etc/aliases" | sudo tee --append /etc/postfix/main.cf
echo "alias_database = hash:/etc/aliases" | sudo tee --append /etc/postfix/main.cf
echo "relayhost =" | sudo tee --append /etc/postfix/main.cf
echo "mynetworks = 127.0.0.0/8" | sudo tee --append /etc/postfix/main.cf
echo "inet_interfaces = loopback-only" | sudo tee --append /etc/postfix/main.cf
echo "recipient_delimiter = +" | sudo tee --append /etc/postfix/main.cf
echo "compatibility_level = 2" | sudo tee --append /etc/postfix/main.cf
echo "myorigin = /etc/mailname" | sudo tee --append /etc/postfix/main.cf
echo "mailbox_size_limit = 0" | sudo tee --append /etc/postfix/main.cf
echo "inet_protocols = ipv4" | sudo tee --append /etc/postfix/main.cf
sudo postmap /etc/postfix/recipient_canonical
sudo postmap /etc/postfix/sender_canonical
sudo systemctl restart postfix
echo "${HOSTNAME} postfix test" | sudo mail -s "${HOSTNAME} Testing postfix configuration" YourName@YourDomain.com
sudo rm -rf /var/mail/root
sleep 1 && sudo postqueue -p

  if it broke, read the error then delete it:
sudo postsuper -d ALL

  (don't bother changing this, because PVE overrides it, but it can be checked)
sudo cat /etc/hosts


In the above block you will see two lines commented out, they are relevant to what is discussed below:
-------------------------------------------
The Regex in /etc/postfix/recipient_canonical can be adjusted
This line takes any and all destinations and changes them to goto admin@YourDomain.com,
mail delivery is guaranteed to work but you cannot send mail to other recipients
Perfectly Fine for Standalone services that ONLY need to mail one address.
-------------------------------------------
/.+/ admin@YourDomain.com

-------------------------------------------
It can be customized to only catch certain recipients such as root, etc:
-------------------------------------------
/.*root.*/ admin@YourDomain.com

For Magento2, you can just comment out the line for recipient_canonical_maps in your /etc/postfix/main.cf after you have 2FA configured.
```

**Comment by hgati** [comment]
> Other workaround (https://devdocs.magento.com/guides/v2.4/security/two-factor-authentication.html): bin/magento config:set twofactorauth/general/force_providers google bin/magento config:set twofactorauth/google/otp_window 60 bin/magento security:tfa:google:set-secret <admin_user> <Base32-encoded_string_for_the_shared_secret_value>
> 
> Base32: https://emn178.github.io/online-tools/base32_encode.html

What mean ? <Base32-encoded_string_for_the_shared_secret_value>
Is this mean "encoded_string of <admin_user>" ?

**Comment by oviliz** [comment]
@hgati no, the admin username (`<admin_user>`) is before the shared secret (see the linked Magento doc).
The `<Base32-encoded_string_for_the_shared_secret_value>` must be the encoded string of a chosen key you create manually in Google Authenticator.
