### ISSUE TITLE
Invoice Tab is not Showing in Admin > Sales > Orders > view

### ISSUE THREAD

**Issue by DanielIconate** [magento/magento2#29323]
### Preconditions (*)

1. 2.3.4
2. Unix Apache Sever 

### Steps to reproduce (*)

1. Order a Product and go to Admin > Sales > Orders > view
2. Pay the order in Sandbox mode

### Expected result (*)

1. the Invoice tab to be shown
2. like in the documentation https://docs.magento.com/user-guide/sales/invoice-create.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=invoic&_ga=2.205501840.1674600680.1595843331-875026625.1593612603

### Actual result (*)

1. [Screenshots, logs or description]
<img width="1170" alt="Bildschirmfoto 2020-07-29 um 12 59 27" src="https://user-images.githubusercontent.com/62563245/88805674-bc7cd100-d1af-11ea-947d-ebe061d07c7b.png">

2. the Invoice tab is missing in the Header

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29323-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29323-2-4-develop.instances.magento-community.engineering/admin_aca3](https://i-29323-2-4-develop.instances.magento-community.engineering/admin_aca3)
Login: `851e9fc8` Password: `1d74e2695551`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @DanielIconate,
I have verified this issue as per your steps, actual result and expected result.
Place order using the PayPal payment method in Sandbox mode on the front end view. 
In Admin > Sales > Orders > Order details, Invoice tab is showing.
PFA:

![Invoice](https://user-images.githubusercontent.com/24711761/88836060-c3c5ce00-d1f3-11ea-89f3-958d696edc67.png)

Please update me on proper steps or videos.

Thanks

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-29323-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29323-2-4-develop.instances.magento-community.engineering/admin_9bbc](https://i-29323-2-4-develop.instances.magento-community.engineering/admin_9bbc)
Login: `598f6d93` Password: `ab7e4434ec98`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @DanielIconate,
I have verified this issue in Magento 2.3.5-p2 Instance. Not able to reproduce this issue.
PFA:
![Invoice](https://user-images.githubusercontent.com/24711761/89705951-2e5ad480-d97f-11ea-85b0-7a72bb28b160.png)

![Order-000000002](https://user-images.githubusercontent.com/24711761/89705952-30249800-d97f-11ea-9d81-ba44777aca96.png)

Thanks

**Comment by ajijshekh123** [comment]
@DanielIconate - If you have reproduced this issue again you can reopen it with Magento Instance details and Payment method which you are using to reproduce this issue.
