### ISSUE TITLE
Tier Prices do not show up for child products with same price as configurable product. 

### ISSUE THREAD

**Issue by webmaiatec** [magento/magento2#29321]
### Preconditions (*)

1. Magento version 2.3.5-p1

### Steps to reproduce (*)

1. Create a configurable product with swatch attributes.
2. While creating child products, keep prices same as parent product & save.
3. Edit any one child product & add tier prices.
4. Go to product page on frontend.
5. Select swatch options which has tier prices.

### Expected result (*)

1. Tier prices should show

### Actual result (*)

1. Tier prices do no show up

### Result of Debugging (*)
- The issue happens due to bug in swatch_renderer.js in Magento_Swatches module. 
- Function "_getNewPrices" logic fails to take tier prices in consideration while finding the difference between base price & option price.
- When child product price is changed in admin then it successfully shows the tier prices in frontend.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by ajijshekh123** [comment]
Hi @webmaiatec,
Not able to reproduce your issue as per your steps, actual result and expected result in Magento 2.4 Instance.
The child product price is updated on the front end view. 
**PFA:**

![1](https://user-images.githubusercontent.com/24711761/88837051-50bd5700-d1f5-11ea-9737-8f7ab082549b.png)

![2](https://user-images.githubusercontent.com/24711761/88837190-86fad680-d1f5-11ea-8be5-93e97cd5668d.png)

Thanks

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29321-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29321-2-3-5-p1.instances.magento-community.engineering/admin_2451](https://i-29321-2-3-5-p1.instances.magento-community.engineering/admin_2451)
Login: `785b809b` Password: `5a157cb9fbb6`
Instance will be terminated in up to 3 hours.

**Comment by webmaiatec** [comment]
@ajijshekh123 The issue is with the product with swatch attribute & not with drop-down. Also it is about tier price block not main product price. Please see the steps to reproduce again & try.

**Comment by ajijshekh123** [comment]
@webmaiatec - Please verify the Qty on the Tier price section. Please add Qty and Enter the price. 
Tier price should be the effect by entered Qty.
PFA:
![3](https://user-images.githubusercontent.com/24711761/88840333-ed81f380-d1f9-11ea-909b-1ee762cc2c7e.png)

![4](https://user-images.githubusercontent.com/24711761/88840342-efe44d80-d1f9-11ea-9c68-4a7f9b84527f.png)

If anything steps missing from my end. you can update me.
Thanks

**Comment by webmaiatec** [comment]
@ajijshekh123 ,

It is not about tier price not being applied. It is about visibility of available tier prices on the option selection. & Please pay attention to the word "swatch" here. You are checking wrong product with wrong settings. Again, please read the steps.

**Comment by ajijshekh123** [comment]
Hello @webmaiatec,
I have verified this issue in the Magento 2.4 Instance and Magento 2-3-5-p1 Instance.
This issue found in Magento 2-3-5-p1 Instance but not found in Magento 2.4 Instance.
**PFA:**
Issue reproduced Magento 2-3-5-p1 Instance :
![2 3 5 Instance_Issue](https://user-images.githubusercontent.com/24711761/89163089-b3667800-d592-11ea-9e23-95556e730c59.png)

Issue not reproduced Magento 2.4 Instance:
![2 4 Instance_Issue](https://user-images.githubusercontent.com/24711761/89163107-ba8d8600-d592-11ea-8a7b-a633ccaa5035.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36421` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment]
@webmaiatec - Please update Magento 2.4 Instance.

**Comment by webmaiatec** [comment]
Hello @ajijshekh123 

Thanks for the verification. It is fixed in 2.4. So closing the issue for now.

**Comment by webmaiatec** [comment]
Hello,

Please note that the swatch js fix is not included in Magento 2.3.5-p1 or 2.4.0. I see it fixed in 2.4-dev branch. So probably it will included 2.4.1.
