### ISSUE TITLE
Billing and shipping same not working while checkout 

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#29326]
### Preconditions (*)

1. Magento 2.3.3 CE
2. Mysql Apache2

### Steps to reproduce (*)

1. Add new address to account as default for billing and shipping address
2. Add product to cart and go to checkout
3. Add shipping step add new address and choose to ship there
4. Payments and review step choose COD and check checkbox to add my billing and shipping address as same
5. Place order

![shippingAndBilling](https://user-images.githubusercontent.com/36662131/88899623-e72c5f80-d26b-11ea-84cc-e961d289cd2a.gif)

### Expected result (*)

1. In order billing and shipping address should be similar as the one which added at shipping step

### Actual result (*)

1. Shipping address is correct but billing is not updated, Showing same as previous one even after checking checkbox.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29326-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29326-2-4-develop.instances.magento-community.engineering/admin_f62e](https://i-29326-2-4-develop.instances.magento-community.engineering/admin_f62e)
Login: `0ac25ab7` Password: `eb181f703a6a`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @VZeroCool,

Not able to reproduce this issue in the Latest Magento 2.4 Instance.
**PFA:**
![Order-000000002](https://user-images.githubusercontent.com/24711761/88929174-64b99500-d297-11ea-8226-1c743dd98637.png)

Thanks.

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29326-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29326-2-3-5-p2.instances.magento-community.engineering/admin_e623](https://i-29326-2-3-5-p2.instances.magento-community.engineering/admin_e623)
Login: `11af1d63` Password: `eee8e12312fa`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29326-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29326-2-3-5-p2.instances.magento-community.engineering/admin_d881](https://i-29326-2-3-5-p2.instances.magento-community.engineering/admin_d881)
Login: `e24c8b20` Password: `28d58d93c89b`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @VZeroCool,
I have verified this issue in Magento 2.3.5-p2 instance. Not able to reproduce this issue.
**PFA:**

![Checkout](https://user-images.githubusercontent.com/24711761/89705458-3284f300-d97b-11ea-81da-b064b7a164ca.png)

![Order-000000001](https://user-images.githubusercontent.com/24711761/89705459-344eb680-d97b-11ea-8ae2-eecda6d918a9.png)

Can you please let me know which Magento Version you have used?

Thanks.

**Comment by ajijshekh123** [comment]
@VZeroCool - If you have reproduced this issue again you can reopen it with Magento Instance details and Screenshot or videos.
