### ISSUE TITLE
Values assigned to a Template under the "dictionary" key are overwritten by the PHP Template Engine

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#29325]
### Preconditions (*)

1. Magento 2.3.5

### Steps to reproduce (*)

1. Create a custom Block, inheriting from Magento\Framework\View\Element\Template
2. In its _toHtml() function, assign a value under the key "dictionary" (using $this->assign('dictionary', '...');
3. In its phtml template, output the value of $dictionary

### Expected result (*)
1. The output value of $dictionary is the value assigned to the Block under the name `dictionary`.

### Actual result (*)
1. The output value of $ditionary is some random data that are not by any mean what was assigned to the Block under the name `dictionary`.

### Why is it happening?

In `\Magento\Framework\View\TemplateEngine\Php.php::fetchView()`, the PHTML template is included after the value of the passed parameter $dictionary is extracted into discrete variables, skipping existing values:

```php
public function render(BlockInterface $block, $fileName, array $dictionary = [])
    {
        ob_start();
        try {
            $tmpBlock = $this->_currentBlock;
            $this->_currentBlock = $block;
            extract($dictionary, EXTR_SKIP); // HERE the content of $dictionary is extracted skipping existing values
            include $fileName;
            $this->_currentBlock = $tmpBlock;
        } catch (\Exception $exception) {
            ob_end_clean();
            throw $exception;
        }
        /** Get output buffer. */
        $output = ob_get_clean();
        return $output;
    }
```

Since the `$dictionary` variable already exist - as parameter of the function, it is not replaced by the value of an eventual key named `dictionary`.

I assume that `$block` and `$fileName` are alos concerned by the issue. The fix is quite simple: extract should be passed the `EXTR_OVERWRITE` parameter instead of `EXTR_SKIP`. Without this, it is not guaranteed that data assigned to a Block are available into its template. And it leads to an unexpected result in the end.

**Comment by mrtuvn** [comment]
Just wonder why do you use specific variable `$dictonary` ? Why no use something else ?

**Comment by ericmorand** [comment]
Because it is the name of the property in the specification of the product.

**Comment by mrtuvn** [comment]
When use data in block i usually use setData('variable') instead. Also magento allow pass view model object in layout and call it later in template

**Comment by mrtuvn** [comment]
`<p><?php echo $dictionary['dictionary']; ?></p>`
Show correct value assign in Block class

**Comment by engcom-Lima** [comment]
Hi @ericmorand, we analysed your ticket. it seems, it is not an issue. Whenever we do customisations then make sure new variable should be define based on scope and should not overwrite. Hence, we are closing this ticket.

If you have any doubts or query you can feel free to raise the new ticket with reproducible steps and required details.

Thanks for the understanding!
