### ISSUE TITLE
Scheduled Import/Export Not Showing in Magento 2.3 Commerce

### ISSUE THREAD

**Issue by strainer85** [magento/magento2#29332]
### Preconditions (*)

1. Newly installed Magento Commerce version 2.3.5p-1
2. Installed through Softalicious installer app via CPanel

### Steps to reproduce (*)

1. Uninstalled and reinstalled Mageno Commerce version 2.5.5p-1 via Softalicious from CPanel
2. 

### Expected result (*)

1. When going to System ->Data Transfer I expect to see Scheduled Imports/Exports per Magento's documentation(see image below)
![image](https://user-images.githubusercontent.com/69009142/88952113-f9ef6600-d264-11ea-848d-87c91d44c9c6.png)

### Actual result (*)

1. Actual result is the menu option for Scheduled Imports / Exports is not shown in the menu
![image](https://user-images.githubusercontent.com/69009142/88952036-d7f5e380-d264-11ea-8948-f5a3d4b9097a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Filocava99** [comment]
Having the same issue. Any data?
