### ISSUE TITLE
Upload product images and drag product images doesn't work

### ISSUE THREAD

**Issue by gitpramos** [magento/magento2#2934]
Upload product images and drag product images doesn't work.

Trying with images .png, .jpg with 500 kb and less it does nothing and sometimes it can be seen the loader but it doesn't upload or accept image to upload.

**Comment by mrkhoa99** [comment]
@gitpramos possibly check _pub/media_ permissions? Do you have a complete stack trace? Or Any console errors log from browser? What's browser you used?

**Comment by veloraven** [comment]
@gitpramos thank you for your request.
Please provide information if this issue is still actual and for which version if it is.
Please also follow the template for description, including steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
