### ISSUE TITLE
Cancel coupon results in javascript error and blocks the checkout process

### ISSUE THREAD

**Issue by stefliekens** [magento/magento2#29342]
After applying a coupon which results in a grand total of 0.0 and 

### Preconditions (*)
1. Magento 2.3.5-p1
2. PHP 7.3.16

### Steps to reproduce (*)

1. Create a new price cart rule with a coupon code. E.g. 100EUR with action "fixed amount discount" and amount of "100"
2. Add product to your basket with a price less then 100 EUR. 
3. Go to payment step in checkout
4. Enter the discount/coupon code
5. The free payment method "No Payment Information Required" is shown
6. Cancel the coupon

### Expected result (*)
1. The coupon is removed from the cart
2. The free payment method "No Payment Information Required" will be hidden
3. Other payment methods will be visible again

### Actual result (*)
1. The coupon is removed from the cart
![js-spinner](https://user-images.githubusercontent.com/3245491/89016827-aab73d00-d319-11ea-8db1-c2ad0b350200.png)
![js-select-payment-error](https://user-images.githubusercontent.com/3245491/89016830-abe86a00-d319-11ea-979e-ba6287d25b32.png)
2. A spinner is shown and a Javascript error occurred
3. The payment methods aren't refreshed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stefliekens** [comment]
@magento I am working on this

**Comment by stefliekens** [comment]
Seems to be fixed in 2.4 develop branch. 
https://github.com/magento/magento2/commit/e5cd82d87c7254503b4c9b6a7ff17017413dd016#diff-aa8b012e2fbfb8f3c2904b7ea0504606

**Comment by engcom-Delta** [comment]
Hi @stefliekens  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
![Peek 2020-08-14 10-58](https://user-images.githubusercontent.com/51681379/90227486-546bf300-de1d-11ea-80cf-3a42195e64c6.gif)

If you'd like to update the issue, please reopen it.
