### ISSUE TITLE
Magento 2.4.0 - JS Console errors

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#29340]
### Preconditions (*)

1. Magento Commerce 2.4.0
2. PHP 7.4.8
3. MySQL 8.0.21

### Steps to reproduce (*)

1. Setup vanila Magento (in developer mode)
2. Go to `/customer/account/create/`
3. Open JS Console, look for errors

### Expected result (*)

1. No errors in JS Console, all files present

### Actual result (*)

1. New account only: `require.js:1895 GET https://acme.local/static/frontend/Magento/luma/en_US/newsletterSignUp.js net::ERR_ABORTED 404`
2. Any page: `require.js:1895 GET https://acme.local/static/frontend/Magento/luma/en_US/cookieStatus.js net::ERR_ABORTED 404`

![image](https://user-images.githubusercontent.com/44395593/88972580-149dfb00-d2b6-11ea-9a9c-2a74de657d14.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, here is your [Magento instance](https://i-29340-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29340-2-4-develop.instances.magento-community.engineering/admin_8fcb](https://i-29340-2-4-develop.instances.magento-community.engineering/admin_8fcb)
Login: `675a9419` Password: `745c8294b80f`
Instance will be terminated in up to 3 hours.

**Comment by lbajsarowicz** [comment]
@maciej-orba Could you give more hints about your environment?
Both locally and with Magento-provided environment, I cannot reproduce it.

![image](https://user-images.githubusercontent.com/1639941/89016952-dafedb80-d319-11ea-9698-4c016c782a0c.png)
![image](https://user-images.githubusercontent.com/1639941/89017057-0a154d00-d31a-11ea-9940-da0eea78bcfd.png)

Have you turned on any of bundling / modification?

**Comment by maciej-orba** [comment]
Hello Łukasz!

1. Developer mode, no bundling signing etc
  CONFIG__DEFAULT__DEV__JS__ENABLE_JS_BUNDLING: 0
  CONFIG__DEFAULT__DEV__JS__MINIFY_FILES: 0
  CONFIG__DEFAULT__DEV__JS__MERGE_FILES: 0
  CONFIG__DEFAULT__DEV__STATIC__SIGN: 0
2. Works fine in production mode, after SCD
3. Env installed via composer:
```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "magento/product-community-edition": "2.4.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "friendsofphp/php-cs-fixer": "~2.16.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": ">=0.12.3 <=0.12.23",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "~5.0.0",
        "squizlabs/php_codesniffer": "~3.5.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "version": "2.4.0",
    "minimum-stability": "stable",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "local": {
            "type": "path",
            "url": "packages/*",
            "options": {
                "symlink": true
            }
        }
    },
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by maciej-orba** [comment]
Issue seems to be connected with some browser caches.
Tested on other browser, incognito mode and after cache clean and no issue.
Thanks for your engagement!

**Comment by lbajsarowicz** [comment]
Thank you for the update!

**Comment by ayasoftware** [comment]
I can confirm that the issue is still in Magento 2.4.1 - not in JS console but in nginx error logs.
