### ISSUE TITLE
Special price still showing with empty field

### ISSUE THREAD

**Issue by gitpramos** [magento/magento2#2935]
Special price still showing in front-end with empty field in back-end and all cache renewed.

Also it shows "was $price"

**Comment by okorshenko** [comment]
@gitpramos could you please update issue description using the following format:

## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...

## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...

## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
