### ISSUE TITLE
Magento 2.4.0 requires php7.4 but php-cs-fixer requires php < 7.3

### ISSUE THREAD

**Issue by TonyMerlin** [magento/magento2#29350]
### Preconditions (*)

1. Upgrading from Magento 2.3.5-p1 to Magento 2.4.0 using composer

### Steps to reproduce (*)

1. composer require magento/product-community-edition=2.4.0 --no-update
2. composer update
3. Advised to upgrade PHP to 7.4 to continue
4. Upgraded to PHP 7.4
5.  Composer update 

### Expected result (*)

1. Installation to complete without error

### Actual result (*)

1. Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.2 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.1 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer ~2.13.0 -> satisfiable by friendsofphp/php-cs-fixer[v2.13.0, v2.13.1, v2.13.2, v2.13.3].

2. [***@*********-dev-server2 html]$ composer update --no-dev
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.2 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.1 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.8) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer ~2.13.0 -> satisfiable by friendsofphp/php-cs-fixer[v2.13.0, v2.13.1, v2.13.2, v2.13.3].

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by hostep** [comment]
@TonyMerlin, you need to update the version constraints of your dev-dependencies in your `composer.json` file as well before attempting the upgrade, here's the diff between a generated `composer.json` file from 2.3.5-p1 and 2.4.0:

```diff
--- magento235-p1-test/composer.json	2020-04-22 09:47:54.000000000 +0200
+++ magento24-test/composer.json	2020-07-20 11:13:04.000000000 +0200
@@ -11,22 +11,23 @@
         "sort-packages": true
     },
     "require": {
-        "magento/product-community-edition": "2.3.5-p1"
+        "magento/product-community-edition": "2.4.0",
+        "magento/composer-root-update-plugin": "~1.0"
     },
     "require-dev": {
         "allure-framework/allure-phpunit": "~1.2.0",
         "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
-        "friendsofphp/php-cs-fixer": "~2.14.0",
+        "friendsofphp/php-cs-fixer": "~2.16.0",
         "lusitanian/oauth": "~0.8.10",
         "magento/magento-coding-standard": "*",
-        "magento/magento2-functional-testing-framework": "~2.6.4",
-        "pdepend/pdepend": "2.5.2",
+        "magento/magento2-functional-testing-framework": "^3.0",
+        "pdepend/pdepend": "~2.7.1",
         "phpcompatibility/php-compatibility": "^9.3",
-        "phpmd/phpmd": "@stable",
-        "phpstan/phpstan": "^0.12.2",
-        "phpunit/phpunit": "~6.5.0",
-        "sebastian/phpcpd": "~3.0.0",
-        "squizlabs/php_codesniffer": "~3.4.0"
+        "phpmd/phpmd": "^2.8.0",
+        "phpstan/phpstan": ">=0.12.3 <=0.12.23",
+        "phpunit/phpunit": "^9",
+        "sebastian/phpcpd": "~5.0.0",
+        "squizlabs/php_codesniffer": "~3.5.4"
     },
     "conflict": {
         "gene/bluefoot": "*"
@@ -63,7 +64,7 @@
             "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
         }
     },
-    "version": "2.3.5-p1",
+    "version": "2.4.0",
     "minimum-stability": "stable",
     "repositories": [
         {
```

**Comment by TonyMerlin** [comment]
Hi again ok I can confirm modifying the composer.json allows the update to continue, and running setup:upgrade works fine too  but then when trying to compile

I am getting the following error...

php bin/magento setup:di:compile 
Compilation was started.
Area configuration aggregation... 5/8 [=================>----------]  62% 54 secs 466.0 MiB
In ClassReader.php line 43:

  Class Magento\InventoryLowQuantityNotificationAdminUi\Model\SourceItemsConfigurationProcessor does not exist


In ClassReader.php line 36:

  Class Magento\InventoryLowQuantityNotificationAdminUi\Model\SourceItemsConfigurationProcessor does not exist


setup:di:compile

**Comment by jrson83** [comment]
Same issue. I can't update to 2.4.0 because of the error. I tried `composer update --ignore-platform-reqs`. It worked but if run `bin/magento setup:upgrade` which results a error message from elasticsearch: No alive nodes found in your cluster

**Comment by hostep** [comment]
@jrson83: please read the entire thread, the correct answer is in it. (and Elasticsearch has nothing to do with this issue. It should be running and Magento should be able to connect to it since it became a hard requirement for Magento 2.4.0 and higher)

Also Github isn't a general "please help me with this random problem I got" platform. Please refer to https://magento.stackexchange.com/ or https://community.magento.com/ for further help.

Somebody should close this issue btw. Unfortunately Magento Community Engineering Team took away my powers to do so, so I can't do it myself anymore ...

**Comment by scommercemage** [comment]
Try removing composer.lock file

**Comment by legaciespanda** [comment]
### Upgrading Magento 2.3.5 to Magento 2.4 Requirement:

Magento 2.4 support PHP 7.4 as per its offical document so before going to upgrade set require php version.

If you are planning to upgrade Magento 2.3.5-p1 to Magento 2.4, there are few changes that you need to do in your composer.json

Run below command step by step to upgrade Magento 2.3.5 to Magento 2.4:
1)  `cp composer.json composer.json.bak`  (this command create backup of composer.json)

2) `composer require magento/product-community-edition=2.4.0 --no-update`

Now open composer.json file and do following required changes in version manually:

(a) `"friendsofphp/php-cs-fixer": "~2.16.0"`

(b) `"magento/magento2-functional-testing-framework": "^3.0"`

(c) `"pdepend/pdepend": "~2.7.1"`

(d) `"phpmd/phpmd": "^2.8.0"`

(e) `"phpstan/phpstan": ">=0.12.3 <=0.12.23"`

(f) `"phpunit/phpunit": "^9"`

(g) `"sebastian/phpcpd": "~5.0.0"`

(h) `"squizlabs/php_codesniffer": "~3.5.4"`


(4) Last and final step run following command:

    `composer update`

After completing this command, you have to run Magento setup upgrade, di compile , deploy command also .

**TESTED AND WORKING PROPERLY WITHOUT ERRORS**

If you get any issue in upgrade, please comment below so I can help you.

**Comment by justgh252** [comment]
@legaciespanda i followed your instruction to upgrade my magento from version 2.2.7 to 2.4.0. Everything works fine until i try to run command php bin/magento setup:upgrade and i am getting following error message. can you provide a solution? (before the upgrade, we actually have removed all the extensions.)

Notice: Undefined index: core_store in /chroot/home/html/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 153

thanks very much for the instruction again!

**Comment by justgh252** [comment]
@legaciespanda i should also mention that when i go to website frontend, i am seeing following error message:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magento_GoogleShoppingAds schema: current version - none, required version - 4.0.1
Magento_GoogleShoppingAds data: current version - none, required version - 4.0.1
Magento_Securitytxt schema: current version - none, required version - 1.0.0
Magento_Securitytxt data: current version - none, required version - 1.0.0
PayPal_Braintree schema: current version - none, required version - 4.4.0
PayPal_Braintree data: current version - none, required version - 4.4.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magento_GoogleShoppingAds schema: current version - none, required version - 4.0.1
Magento_GoogleShoppingAds data: current version - none, required version - 4.0.1
Magento_Securitytxt schema: current version - none, required version - 1.0.0
Magento_Securitytxt data: current version - none, required version - 1.0.0
PayPal_Braintree schema: current version - none, required version - 4.4.0
PayPal_Braintree data: current version - none, required version - 4.4.0
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#2 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#3 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#5 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#6 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#7 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#8 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
