### ISSUE TITLE
Logo not resizing in magento 2.4

### ISSUE THREAD

**Issue by gelanderosh** [magento/magento2#29361]
Logo not resizing in frontend

### Preconditions (*)
1. Php 7.4
2. Apache 2.4 nginx
3. Magento 2.4 new installation

### Steps to reproduce (*)
1. Install a new magento 2.4 instance.
2. Change the logo thru the admin and set it's size different from 170px width.

### Expected result (*)
1. Logo showing in frontend according to the size set in the admin.

### Actual result (*)
1. Logo always set to 170px width and auto height.

Comments:
Probably has to do with the blank theme layout file setting logo width to 170px. Fixed it removing that line from the default.xml layout file.

**Comment by MexMade** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MexMade. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MexMade, here is your [Magento instance](https://i-29361-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29361-2-4-develop.instances.magento-community.engineering/admin_44ef](https://i-29361-2-4-develop.instances.magento-community.engineering/admin_44ef)
Login: `c84d9b47` Password: `cd2b80d970d8`
Instance will be terminated in up to 3 hours.

**Comment by MexMade** [comment]
@magento I am working on this

**Comment by MexMade** [comment]
@magento add to contributors team

**Comment by MexMade** [comment]
@magento I am working on this
