### ISSUE TITLE
Error saving no-route page

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#2936]
This error occurs only with no-route page, when saving:

"Forbidden

You don't have permission to access /_admin136/cms/page/save/key/823f71317503a38f22a83cc145503668502d0f7dc0c6dff5e7b818f11b1ef944/active_tab/main_section/ on this server."

**Comment by shiftedreality** [comment]
Hi, @jaimestuardo 

Are you still able to reproduce current issue on latest developer brunch?
Also, could you please provide more details about your environment, version of PHP, Server and OS?

**Comment by jaimestuardo** [comment]
I am using Magento version 2.0.0. This site is a production site so I think it is risky to install a developer branch. Is there a possible date when a new stable version will be available?

i have 2 magento sites in the same server, and the same happens. When trying to save no-route page, an error occurs. This does not happen when saving other CMS pages.

**Comment by jaimestuardo** [comment]
I have Magento 2.0.2 and the problem still persists! I cannot save any CMS page! Finally I need to update it directly in database, but that is absolutely not the idea.

**Comment by jaimestuardo** [comment]
No solution to this yet? I have version 2.0.4 now:

Just the page loaded:

![image](https://cloud.githubusercontent.com/assets/9195659/15289618/cd51d8ca-1b49-11e6-8000-cb0a91041ce9.png)

Immediately press "Save Page":

![image](https://cloud.githubusercontent.com/assets/9195659/15289628/e1e6e1ea-1b49-11e6-8a33-53f3a39b3f40.png)

**Comment by veloraven** [comment]
@jaimestuardo is this issue still actual?
It seems that permissions are not configured correctly on your server.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
