### ISSUE TITLE
FME photogallery 

### ISSUE THREAD

**Issue by uttam-dhameliya** [magento/magento2#29378]
It was good to know and use this extension but now somehow i;m getting error/issue on it. 

### Summary (*)

it shows "The "**gallery_schedule_block1" block threw an exception, and it can't be rendered.**" eoor on new photo gallery creation page on backed of magento 2

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @uttam-dhameliya. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
