### ISSUE TITLE
Issue with configurable products in widgets, not added to cart

### ISSUE THREAD

**Issue by AndaIonescu** [magento/magento2#29371]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Create a product attribute, for example Size with several values (S, M and L). This attribute must have property "use in product listing" set to Yes.
![image](https://user-images.githubusercontent.com/51681379/90142299-deb44880-dd84-11ea-8401-5f960f3ca34f.png)
![image](https://user-images.githubusercontent.com/51681379/90142317-e70c8380-dd84-11ea-9e92-254518e9ebdb.png)
2. Create a product that uses this attribute with a configuration setting. Define different quantities for each values. Set this product as new for the current month.
3. Create a block with a widget for new products (choose the grid template) and add this block at any page.
![image](https://user-images.githubusercontent.com/51681379/90142005-854c1980-dd84-11ea-9624-e00dd40686c0.png)
4. On this page click on Add to cart (from a computer, not smartphone) for this new product.

### Expected result (*)
User should see the product attributes in a grid with the possibility to choose and add to card fast

### Actual result (*)
No options for configurable product are shown in widget block 
![Peek 2020-08-13 16-20](https://user-images.githubusercontent.com/51681379/90142195-c2b0a700-dd84-11ea-8b18-c95451cf699a.gif)

Links to it. https://www.doarcrap.ro/test-cf.html
https://www.doarcrap.ro/produse.html?p=3

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36704` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
