### ISSUE TITLE
Newsletter - queue time changes after save 

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#2937]
I set a time for sending newsletters to subscriber. But after I saved it, the time changed. I have checked the server's tim zone and the database's timezone. It all consists with the timezone before I save it. Is there anyone having the same issue?

before save.
![capture-timazone1](https://cloud.githubusercontent.com/assets/13892193/12210138/e710284a-b625-11e5-8729-ffa2e66589e2.JPG)
after save.
![capture-timazone2](https://cloud.githubusercontent.com/assets/13892193/12210141/e8b7cd92-b625-11e5-8685-87faa3546e37.JPG)

**Comment by kgvconsulting** [comment]
@dexteritycc 
@MomotenkoNatalia 
@yaronish 
@vladimir-k 

The same issue with me, any luck or respond how to fix that? 

Magento v 2.0.6

The queue never execute and send the emails, after assigning the date and time and safe the queue the date stay the same but the start time changes always 4 hours back from selected one?

**Comment by Ctucker9233** [comment]
Same issue on Magento 2.1. I opened a new issue about it. My problem is that it sets the time back 7 hours.

**Comment by veloraven** [comment]
@dexteritycc please provide the used Magento version.
Internal ticket MAGETWO-56349 is already created for the issue #5943 which is a duplicate for this one.

**Comment by dexterityzx** [comment]
magento 2.0.7

**Comment by magento-engcom-team** [comment]
The issues already fixed and will be available with release 2.2.0 very soon
