### ISSUE TITLE
responsiveness

### ISSUE THREAD

**Issue by Fabiojose2041** [magento/magento2#29374]
### Description (*)

I have a problem with the responsiveness of my website where the images are cutting on my cell phone

**Comment by krishprakash** [comment]
Hi @Fabiojose2041. 
Kindly update all the necessary details with precondition,steps to reproduce,expected and actual result to reproduce this issue

**Comment by krishprakash** [comment]
Hi @Fabiojose2041.
Feel free to reopen the issue once you update all the necessary details 
Thanks !!
