### ISSUE TITLE
turning on minify js errors out product detail page

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2938]
There is a specific library which bombs out when turning on minification of javascript files. See screenshot.

![screen shot 2016-01-08 at 5 10 00 pm](https://cloud.githubusercontent.com/assets/437029/12210845/fd1cbf4a-b62a-11e5-912f-6cd6498fc37f.png)

**Comment by Pakkapao** [comment]
I also got the same javascirpt errors when turning on javascript minification. It still remains in Magento 2.0.1...

**Comment by nigelcopley** [comment]
You can fix the recurring file permission issues which cause your JS to fail by changing a couple of lines in this file. Not ideal as it's core files so you'll need to make a note of it when upgrading etc

vendor/magento/framework/Filesystem/DriverInterface.php

Changing 770 to 755 and 660 to 644 has worked for my php environment

Hope this helps someone and I hope magento fixes this.

**Comment by okorshenko** [comment]
@markoshust could you please update issue description using the following format:

## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...

## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...

## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by anton-huz** [comment]
Currently not reproducible on Magento 2.0.5.
