### ISSUE TITLE
Uncaught Error: Class 'DOMDocument' not found in Magento 2.4 CE

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#29387]
### Preconditions (*)

1.Magento 2.4 CE
2.Apache 2.4.41 (Ubuntu)
3.PHP 7.4.8 (cli)
4.mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)
5.Ubuntu 20.04 LTS
6.Installed PHP extensions 
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```
7. i have tried to enable `xml` extension using `phpenmod -v 7.4 xml`

### Steps to reproduce (*)

1.Download Latest version of   [Magento CE](https://magento.com/tech-resources/download)
2.Extract and copy to `/var/www/html/magento24`
3.Grant 777 permission usng command `sudo chmod -R 777 magento24`
4.Go to browser and submit url 'http://127.0.0.1/magento24/'

### Expected result (*)

1. Magento Installation Setup should Start

### Actual result (*)

1. Gave an error on 
2. enable display error found `Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/html/magento24/vendor/magento/framework/Config/Dom.php:449 `

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without a workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look, and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@TheRealHunzik seems like you don't have installed `dom` php extension.
You can see that there is dependency declared in composer.json.
https://github.com/magento/magento2/blob/ec098d26e7735528beb8ef338b1eeb25eab3a1a1/composer.json#L18

Also should should have such error in case if you'll run composer install.

**Comment by sdzhepa** [comment]
Hello @TheRealHunzik 

Did you have a chance to check https://github.com/magento/magento2/issues/29387#issuecomment-669209489 ?
Based on the description it seems some kind of configuration/env issue.

Could you please provide an update?

Also, be aware that Web Install Wizard has been removed from Magento starting from 2.4.0 release.
Now it can be installed only using CLI https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli.html

**Comment by ihor-sviziev** [comment]
Hi @TheRealHunzik,
As we didn't get any response for a long time - we'll close this issue due to inactivity.
Feel free to write any comments or re-open this issue if this it still not resolved for you.

**Comment by georgittanchev** [comment]
I am receiving the same error on 2.3.5 installed via Magento-CLI, composer install  works fine, however, the error log provides the following output:

[14-Jun-2023 18:17:06 UTC] PHP Fatal error:  Uncaught Error: Class "DOMDocument" not found in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php:449Stack trace:
#0 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php(116): Magento\Framework\Config\Dom->_initDom()#1 /home/bumbinguglies/public_html/vendor/magento/framework/ObjectManager/Config/Reader/Dom.php(70): Magento\Framework\Config\Dom->__construct()#2 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(151): Magento\Framework\ObjectManager\Config\Reader\Dom->_createConfigMerger()#3 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles()#4 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(279): Magento\Framework\Config\Reader\Filesystem->read()#5 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(140): Magento\Framework\App\ObjectManagerFactory->_loadPrimaryConfig()#6 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(211): Magento\Framework\App\ObjectManagerFactory->create()
#7 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(126): Magento\Framework\App\Bootstrap->__construct()#8 /home/bumbinguglies/public_html/index.php(36): Magento\Framework\App\Bootstrap::create()
#9 {main}  thrown in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php on line 449

PHP extensions enabled:
[PHP Modules]
bcmath
clos_ssa
Core
ctype
date
dom
filter
ftp
hash
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

Magento is installed with the following command:
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.5 magento2

It looks like the dom extension is completely installed on PHP 7.1, yet Magento 2.3.5 is looking for it for some reason as it is not there, what may the reason be for that?
