### ISSUE TITLE
The shipping information is not saved in ver. 2.2.9

### ISSUE THREAD

**Issue by Erickhdez** [magento/magento2#29382]
### Preconditions (*)

1. Magento ver. 2.2.9
2. Checkout (shipping)

### Steps to reproduce (*)

1. When registering the shipping information and selecting the shipping method, an error is displayed with "Unable to save shipping information. Please check the data entered".
2. ![image](https://user-images.githubusercontent.com/69058884/89304788-7acaab00-d633-11ea-939f-59282e27870e.png)

### Expected result (*)

1. We hope that the shipping information is saved correctly and the order is confirmed correctly
2.

### Actual result (*)

1. The shipping information is not saved and the payment method option is not displayed
2. ![image](https://user-images.githubusercontent.com/69058884/89304871-9635b600-d633-11ea-85d3-715b959f89f6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Erickhdez thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop.
![Peek 2020-08-12 14-44](https://user-images.githubusercontent.com/51681379/90011566-7d1fab80-dcaa-11ea-95a5-d177bcd04355.gif)

If you'd like to update the issue, please reopen it.
