### ISSUE TITLE
What does it take to get an issue past the bots and into triage so one can work on it?

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#29397]
I have a few contributions to the migration tool but both with inventory and here I have reported issues.
The bots kick in, confirm format valid.
I request an instance and can replicate the bug
but the bug is still not workable because it needs to go through triage. 

I see many bugs stuck in limbo, what is needed so it can be moved forward?

For example one is over a month old but still there - i suspect with a touch of input from people more familiar with the knockout side I can figure it out and fix it.

**Comment by krishprakash** [comment]
Hi @iphigenie. Thank you for your report !!
GitHub issue tracker is intended for magento core technical issues only
You can reach on Slack channel to ask regarding this
