### ISSUE TITLE
Instant Purchase on product page not working Braintree properly magento 2.4

### ISSUE THREAD

**Issue by haunguyen1989** [magento/magento2#29390]
### Preconditions (*)

1. Install magento 2.4 EE
2. Linux Ubuntu 20.04 LTS
### Steps to reproduce (*)

1. Config payment method Braintree:
Merchant ID, Public Key, and Private Key
Set Enable this Solution to Yes.
If applicable set Enable PayPal through Braintree to Yes.
Set Vault Enabled to Yes.
**Enable Instant Purchase:** Sales - > Sales -> Instant Purchase
Set Enabled to Yes.

2. Login and place order success with Braintree(card saved)

3. Go product detail any.  Don't display button "Instant Purchase"

### Expected result (*)

1. Display button "Instant Purchase"

### Actual result (*)

1. Don't display button "Instant Purchase"

**Comment by sdzhepa** [comment]
@haunguyen1989 

as was mentioned in this blog post: https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445
and in the [Release notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html):

> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

This module/functionality has been removed from the Magento code base.
It means we are not able to fix through this repository or provide any status updates. 

Please contact Extention owner Support on the Market place to report issues or aks question

**Comment by haunguyen1989** [comment]
> @haunguyen1989
> 
> as was mentioned in this blog post: https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445
> and in the [Release notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html):
> 
> > With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.
> 
> This module/functionality has been removed from the Magento code base.
> It means we are not able to fix through this repository or provide any status updates.
> 
> Please contact Extention owner Support on the [Marketplace](https://marketplace.magento.com/extensions.html) to report issues or aks question

thank @sdzhepa

**Comment by serhiideliiev** [comment]
I don't actually understand how this information is related to the issue. I'm using Braintree sandbox and following all the requirements to use instant purchase however result is the same as topic-starter described.

Could you please advise?
