### ISSUE TITLE
Unable to Proceed with Magento2.4.0 Installation on XAMPP localhost

### ISSUE THREAD

**Issue by ashwanichandra** [magento/magento2#29395]
I'm not able to proceed ahead with the Magento 2.4.0 open source installation on Localhost XAMPP on Windows 10. I just get the landing page but there is no buttons to proceed ahead. Please see the screenshot
<img width="600" alt="magento issue" src="https://user-images.githubusercontent.com/69243279/89402825-0e37d500-d735-11ea-88c1-bfbc735d2a57.png">

**Comment by hostep** [comment]
@ashwanichandra: the setup wizard was removed in Magento 2.4.0, you can now only install Magento using the commandline: `bin/magento setup:install ...`

See the [release notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html):
> Deprecation and removal of the Web Set Up Wizard. You must use the command line to install or upgrade Magento 2.4.0. See [Install Magento](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli.html).
