### ISSUE TITLE
Propose to add the possibility to set a fieldset-specific renderer to the fieldset elements

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2940]
https://mage2.pro/t/228

**Comment by veloraven** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
