### ISSUE TITLE
Javascript String Internationalisation not working

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#2941]
I've noted that there is something not working with the translation of javascript strings.

I've set up a demo site: http://mage2-test.vanderboon.net

If you add a product to the cart. Click the button "Toevoegen aan Winkelwagen" (Add to Cart in Dutch), after you click, you will see "Adding..." and "Added" And "Add to Cart".

The three last messages are not translated.

In the catalog-add-to-cart.js the following strings are defined:

```
        addToCartButtonTextWhileAdding: $t('Adding...'),
        addToCartButtonTextAdded: $t('Added'),
        addToCartButtonTextDefault: $t('Add to Cart')
```

But for some reason the translated texts are not displayed in JavaScript. I notice more JavaScript strings which are not translated correctly

I 've added the following lines to my nl_NL.csv

Adding...,Toevoegen...,module,Magento_Catalog
Added,Toegevoegd,module,Magento_Catalog
"Add to Cart","Toevoegen aan Winkelwagen",module,Magento_Catalog

---

My language file is here: http://www.vanderboon.net/magento-translation/dutch.csv (> 95% complete)

The language file was installed the following way: http://www.vanderboon.net/wiki/Install_Test_Magento_2_Translation

**Comment by chicgeek** [comment]
I have also reported this in issue https://github.com/magento/magento2/issues/2056.

As a workaround for this specific instance until a fix is released, you can specify your options in the template that calls `catalogAddToCart` and rely on PHP translation instead of JS translation. For example in `list.phtml`:

```
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "addToCartButtonTextDefault": "<?php echo __('Add to Cart'); ?>",
            "addToCartButtonTextWhileAdding": "<?php echo __('Adding...'); ?>",
            "addToCartButtonTextAdded": "<?php echo __('Added'); ?>"
        }
    }
}
</script>
```

**Comment by 11mb** [comment]
I have the same problem. Also the texts in the checkout popover and the javascript texts of some external modules won't translate. This is in version 2.0.4.

**Comment by hshar7** [comment]
Hey guys this issue was fixed not too long ago in scope of: https://github.com/magento/magento2/commit/690cae8e9fbffe3e74b7036083b6f2898547ee9a
