### ISSUE TITLE
Magento 2.3.4 - Order don't get recorded in admin

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#29419]
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.3
3. Braintree Gene 4.0.4
4. Default Onepage Checkout 

### Steps to reproduce (*)

1. Add an item in cart and place orders
2. Magento sends confirmation email
3. Order don't get recorded in magento admin
4. This happens 1 in 10 order 

### Expected result (*)

1. Magento sends confirmation email
2. Order get recorded in Magento admin i can view the order

### Actual result (*)

1. Magento sends confirmation email
2. Order don't get recorded in magento admin
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gilbertsohal** [comment]
Is there Someone who can help me without upgrade to 2.4 ?

**Comment by gilbertsohal** [comment]
Is there a magento developer who can help me? We have newly upgraded to magento 2 website. I am facing issues with order and payments. Which i never faced in M1

1) With the below order number, the order never got recorded in magento nor i received a confirmation email. But braintree deducted the payment. 
1000002100

2) With the below order numbers, the amount, details and sku are same. Braintree processed this as three separate orders and deducted the payment thrice. 
1000002094
1000002095
1000002096

3) The order increment is getting skipped. Please check the screenshot, and further details can be provided. 
Screenshot 
https://prnt.sc/u0oxz6

This is a serious issue, still pending in magento 2. Please look into the matter, and suggest what can be done.

**Comment by sdzhepa** [comment]
Hello @gilbertsohal 

It's very sad that you faced such issue...
But according to rules [Code Contributions:Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)
> v2.4 Contribution Notice: Magento is focusing development efforts on v2.4, so we are no longer accepting pull requests to the v2.3, v2.2, v2.1, and v2.0 release lines.

This means here we can process, assist, and deliver issues related to 2.4+ version only. 

And starting from `2.4.0` release code related to this payment was removed for Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.


So, this issue candidate to be closed but let's keep it open for a couple of days. Probably someone from the community also had the same problem and can help or at least advice here or in https://magento.stackexchange.com/questions/319944/magento-2-3-4-order-dont-get-recorded-in-admin
