### ISSUE TITLE
Url API /rest/V1/products/:sku not require authentication authtoken

### ISSUE THREAD

**Issue by jruzafa** [magento/magento2#2943]
Access to the url api /rest/V1/products/:sku does not require authentication authtoken, attached screenshot:

![screen shot 2016-01-09 at 20 06 03](https://cloud.githubusercontent.com/assets/209403/12217817/8948bcbc-b70c-11e5-8937-4110736658cc.png)

**Comment by choukalos** [comment]
Hi @jruzafa You can call the product API with out an authorization token and essentially see the same data  a customer can see (basically everything but inventory).  If you call with an admin token or system token you'll get inventory status.  This is as designed to support AJAX / Angular JS type of solutions.
