### ISSUE TITLE
Modifying the Maintenance screen.

### ISSUE THREAD

**Issue by LiamTrioTech** [magento/magento2#29432]
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

![image](https://user-images.githubusercontent.com/68578009/89596427-406b4300-d8ab-11ea-9e2f-f71b5c1fbb95.png)

### Description (*)
Can this page show store contact details or be edited in some way?

Showing during Maintenance mode.

**Comment by tgamanov** [comment]
Hello @LiamTrioTech.
Please check Magento documentation page
https://devdocs.magento.com/guides/v2.4/comp-mgr/trouble/cman/maint-mode.html
Is it what you need?

**Comment by LiamTrioTech** [comment]
Thanks @tgamanov, yes that does help.
But I wonder if it should show the store contact details from the general section by default, or a button/page in magento 2's admin screens to edit the maint page.

Like under the Content | Pages menu.

**Comment by sivaschenko** [comment]
@LiamTrioTech The purpose of the maintenance page is to display static content while the services might not be operational. So I don't think it would be a good idea to query the database for the contact information to display while maintenance mode is enabled.

If you'd like to display any specific information (including the contacts) please follow the documentation on creating custom maintenance page: https://devdocs.magento.com/guides/v2.4/comp-mgr/trouble/cman/maint-mode.html

**Comment by LiamTrioTech** [comment]
It could be static html generated by magento admin page. But yeah easy enough to do manually

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
