### ISSUE TITLE
Checkout issue on Elasticsearch search breakdown

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#29448]
### Preconditions (*)
1. Magento 2.4-develop;
1. Elasticsearch v7.8.1;

### Steps to reproduce (*)
1. Add any product to cart;
1. Proceed to checkout;
1. Turn OFF Elasticsearch instance ( `service elasticsearch stop` for ex.);
1. Click on the **Place Order** button;
### Expected result (*)
Either order should be placed & success should be shown to the customer
 or 
order shouldn't be created at all & error should be shown to the user

### Actual result (*)
1. User got error **" An error occurred on the server. Please try to place your order again."**
2 . Order get placed in admin panel & customer's card is charged as well

![Peek 2020-08-10 18-27](https://user-images.githubusercontent.com/51679138/89800348-568d3380-db37-11ea-89f5-4ce7499faf40.gif)

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- <x] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36585` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by geeta07** [comment]
#dmcdindia2020

**Comment by geeta07** [comment]
@magento I am working on it

**Comment by geet07** [comment]
@magento I am working on it

**Comment by geet07** [comment]
@magento give me 2.4-develop instance

**Comment by geet07** [comment]
@magento give me 2.4-develop instance

**Comment by geet07** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @rav-redchamps ,

This issue not reproducible in latest 2.4-develop. Hence, closing this issue.
PR link:: https://github.com/magento/magento2/pull/36241
Commit link:: https://github.com/magento/magento2/commit/fdf18ee6a4f51280cf9fe4ead2733015670cee8a

Thanks
