### ISSUE TITLE
Problem with magento

### ISSUE THREAD

**Issue by ajay09Payal** [magento/magento2#2944]
I am trying to install magento 2.0 from github. I am using shared server (aws ubuntu 14.04) and i am getting an error as

[ERROR] exception 'LogicException' with message 'Unknown module in the requested list: 'Magento_BundleSampleData'' in /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php:401
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(362): Magento\Setup\Model\Installer->readListOfModules(Array, Array, 'enable_modules')
#1 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(323): Magento\Setup\Model\Installer->createModulesConfig(Array)
#2 /var/www/html/magento2/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#3 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/html/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#14 {main}

**Comment by jruzafa** [comment]
I happened to me this same error and restart the mysql service and it worked

**Comment by CountZakula** [comment]
Neither restarting MySQL or Apache has fixed this for me

**Comment by mazhalai** [comment]
@CountZakula  @ajay09Payal  did you have a previous installation? Looks like you had sample data earlier, but dont anymore. If you dont mind losing data that is existing in the db, please run `bin/magento setup:uninstall` and try installing again. or else run `bin/magento setup:backup --db` to create a backup and then the uninstall command.

**Comment by bnzo** [comment]
@ajay09Payal @CountZakula I had the same issue, tried to restart Apache and MySQL without success. I tried the wizard setup with another browser and it worked. So I guess it is browser cache related. Try to empty your cache or use another browser.

**Comment by dehghanfar** [comment]
for me it was only browser cache, just change the browser, it will fix the problem

**Comment by rahulvramesh** [comment]
Worked For Me In Another Browser /  Private Window .

**Comment by turnipjs** [comment]
Switched to a different account in chrome and worked for me. Thanks @bnzo !

**Comment by mikenk2010** [comment]
Right, work for me in incognito....why !!!!
