### ISSUE TITLE
Return types incompatibile with generate code

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#29457]
### Preconditions (*)
1. Magento 2.4.0
2. PHP 7.3

### Steps to reproduce (*)
1. Rewrite a module which has a function with a return type declaration
E.g: vendor/magento/module-quote/Model/Cart/CartTotalRepository.php
2. Rewrite the function `public function get($cartId): QuoteTotalsInterface`.
3. Run `bin/magento setup:di:compile`.

### Expected result (*)
1. The following success message is thrown:
`Compilation was started.
Interception cache generation... 7/7 [============================] 100% 2 mins 454.0 MiB
Generated code and dependency injection configuration successfully.`
2. Compilation finishes correctly

### Actual result (*)
1. The following error is thrown:
`Compilation was started.
Repositories code generation... 1/7 [===>------------------------]  12% 2 secs 72.0 MiB
Fatal error: Declaration of Vendor\Module\Model\Cart\CartTotalRepository::get($cartId) must be compatible with Magento\Quote\Model\Cart\CartTotalRepository::get($cartId): Magento\Quote\Api\Data\TotalsInterface in /project/app/code/Vendor/Module/Model/Rewrite/Cart/CartTotalRepository.php on line 0`
2. Compilation does not finish

---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
The only way to workaround this issue is to employ Plugins rather than rewrites.
However when faced with protected/private methods that needs to be rewritten or is being called within the desired function that is rewritten, it is impossible to do this with a Plugin.
As such this becomes an enormous blocker when rewriting.
This becomes much more of a blocker when upgrading to Magento 2.4.0 whilst having multiple private or third party modules installed.
Most modules rewrite core Magento code in some way, and this completely breaks the installation as compilation of generated code is no longer possible.

### Example of rewritten code:
```
<?php

namespace Vendor\Module\Model\Cart;

use Magento\Quote\Api;
use Magento\Quote\Api\CartRepositoryInterface;
use Magento\Catalog\Helper\Product\ConfigurationPool;
use Magento\Framework\Api\DataObjectHelper;
use Magento\Quote\Model\Cart\Totals\ItemConverter;
use Magento\Quote\Api\CouponManagementInterface;
use Magento\Framework\Api\ExtensibleDataInterface;
use Magento\Quote\Model\Cart\TotalsConverter;
use Magento\Quote\Model\Cart\CartTotalRepository as MagentoTotalRepository;
use Magento\Quote\Api\Data\TotalsInterface as QuoteTotalsInterface;

class CartTotalRepository extends MagentoTotalRepository
{
    /**
     * Cart totals factory.
     *
     * @var Api\Data\TotalsInterfaceFactory
     */
    private $totalsFactory;

    /**
     * Quote repository.
     *
     * @var \Magento\Quote\Api\CartRepositoryInterface
     */
    private $quoteRepository;

    /**
     * @var \Magento\Framework\Api\DataObjectHelper
     */
    private $dataObjectHelper;

    /**
     * @var ConfigurationPool
     */
    private $itemConverter;

    /**
     * @param Api\Data\TotalsInterfaceFactory $totalsFactory
     * @param CartRepositoryInterface $quoteRepository
     * @param DataObjectHelper $dataObjectHelper
     * @param CouponManagementInterface $couponService
     * @param TotalsConverter $totalsConverter
     * @param ItemConverter $converter
     */
    public function __construct(
        Api\Data\TotalsInterfaceFactory $totalsFactory,
        CartRepositoryInterface $quoteRepository,
        DataObjectHelper $dataObjectHelper,
        CouponManagementInterface $couponService,
        TotalsConverter $totalsConverter,
        ItemConverter $converter
    ) {
        parent::__construct(
            $totalsFactory,
            $quoteRepository,
            $dataObjectHelper,
            $couponService,
            $totalsConverter,
            $converter
        );

        $this->totalsFactory = $totalsFactory;
        $this->quoteRepository = $quoteRepository;
        $this->dataObjectHelper = $dataObjectHelper;
        $this->itemConverter = $converter;
    }

    /**
     * @inheritdoc
     */
    public function get($cartId): QuoteTotalsInterface
    {
        ...
        // Do something different than the parent
        ...
    }
}
```

**Comment by stephan-cream** [comment]
For more information, this issue was also present before 2.2, however it was fixed in https://github.com/magento/magento2/issues/6106.
The issue seems to have come back ever since Zend_Framework has been replaced with Lamias.
As for why this hasn't garnered much attention before this, is most likely because before 2.4.0 most functions did not use a return type declaration.
However in 2.4.0 a lot of functions now have a return type declaration.

**Comment by dverkade** [comment]
Comment to follow and track changes for this ticket as I want to be notified of this as well.

**Comment by dverkade** [comment]
Issues should not automatically close. Posting this comment to keep it active.

**Comment by dverkade** [comment]
Issues should not automatically close. Posting this comment to keep it active.

**Comment by hostep** [comment]
@sidolov: can we get somebody to review this? This sounds quite important to me, thanks!

**Comment by engcom-Foxtrot** [comment]
Hello, @stephan-cream. Unfortunately, I can reproduce such an issue neither on the 2.4-dev branch nor on the 2.4.0 release. I've attached my test module. If you have some updates, please let me know.
[Example_Rewrite.zip](https://github.com/magento/magento2/files/6350320/Example_Rewrite.zip)

**Comment by stephan-cream** [comment]
It would seem to no longer be an issue, although it does seem several Lamias modules have been updated since the time of my report so perhaps this had been fixed there.

**Comment by engcom-Foxtrot** [comment]
@stephan-cream thanks for the fast answer. I'm closing this issue. Feel free to reopen if needed.
