### ISSUE TITLE
Null get destination city

### ISSUE THREAD

**Issue by Mhd-Emad** [magento/magento2#2945]
Hi All,

When I'm  trying to get  Shipping destination city in collectRates(RateRequest $request) method to create my own shipping module it's still return null value, $request->getDestCity()
i can retrieve country code but city not, can you advice me please?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
