### ISSUE TITLE
Customer country list not correct

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#2946]
I was just migrating my data to Magento 2.0 and found this issue.

When there are different configurations for available countries in store views, in the admin section I only get the countries that are available in the _default store view_ of the website, but not the store view the customer is assigned to.

In my case: we have a website for Europe. This website has store views for different countries, for example France. France is not available in other store views of this website.
The default store view for the website is the UK store view.
When I open a customer in the admin section, I cannot select France as country for their address, even though the account is created in the French store view where France is available as a country.

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-48425

**Comment by okorshenko** [comment]
@gigadesign1 Thank you for reporting the issue. Fix for MAGETWO-48425 merged to develop branch.

**Comment by slavvka** [comment]
The fix has been also ported to 2.1

**Comment by Ctucker9233** [comment]
@slavvka Great! Where can we find it?

**Comment by slavvka** [comment]
In the latest mainline and it will be delivered in the nearest 2.1 patch release. Commits you can see above.

**Comment by AntonEvers** [comment]
@slavvka thank you. Is there already a planned release date of the next patch release?

**Comment by Ctucker9233** [comment]
Yes, is there an estimate of when the next patch will be available?
