### ISSUE TITLE
Magento 2 REST API end point is not return response

### ISSUE THREAD

**Issue by ziyaindia** [magento/magento2#29464]
Hi All,

My URL is 

https://{base_url}/index.php/rest/V1/configurable-products/:sku/children

When I am calling above URL getting following response. Not getting any clue to fix it.

![Screenshot from 2020-08-11 10-24-25](https://user-images.githubusercontent.com/8448843/89858782-17092a80-dbbd-11ea-86ad-2dfb4f58c115.png)

_Originally posted by @ziyaindia in https://github.com/magento/magento2/issues/20366#issuecomment-671724794_

Thanks in Advance

**Comment by engcom-Delta** [comment]
Hi @ziyaindia thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
![image](https://user-images.githubusercontent.com/51681379/90133670-92630b80-dd78-11ea-9dee-1a03e9aca7b9.png)

If you'd like to update the issue, please reopen it.

**Comment by ziyaindia** [comment]
My Magento Version is  Magento ver. 2.3.2

Please check following URL:
https://www.eventgift.net/rest/V1/configurable-products/MO5001/children
