### ISSUE TITLE
PayPal Express Checkout error "Failed address validation: %1"

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#29473]
### Preconditions (*)

1. Magento 2.4-develop
2. PayPal Express Checkout configured with option "Skip Order Review Step" to "No"
3. Setting "Store > Configuration > Customers > Customer Configuration > Enable Automatic Assignment to Customer Group" to "Yes"

### Steps to reproduce (*)

1. Add any product to cart
2. Go to Checkout & Proceed as a guest user
3. Choose PayPal Express Checkout & Hit Place Order
4. After returning from PayPal, you will be redirected to review step
5. Click 'Place Order' button from there. You will see the  "Failed address validation: %1" error

### Expected result (*)

Order should have been created.

### Actual result (*)

Error appears  "Failed address validation: %1"

<img width="1428" alt="Screenshot 2020-08-11 at 5 01 34 PM" src="https://user-images.githubusercontent.com/5336201/89892561-7898bb80-dbf4-11ea-9f14-9990f1f07c7f.png">

### Developer Information

The problem occurs from below line of code in the file 
**vendor/magento/module-quote/Observer/Frontend/Quote/Address/CollectTotalsObserver.php at line# 139**

`$quote->setCustomer($customer);`

This replaces `customer_email` property in quote object will `null` value

system.log
![Screenshot from 2020-08-12 14-58-09](https://user-images.githubusercontent.com/51679138/90012612-60847300-dcac-11ea-98b5-0519de65bf9b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36663` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mjoraid** [comment]
> 2\. PayPal Express Checkout configured with option `"Skip Order Review Step"` to `"No"`

Does switching "Skip Order Review Step" to "Yes" help work around the issue? 

Or is it just the `Enable Automatic Assignment to Customer Group` what causing the issue?

**Comment by JemspSavani** [comment]
" Enable Automatic Assignment to Customer Group " only causing the issue
