### ISSUE TITLE
Returns :: GraphQL Implementation

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#29479]
As a developer,

I want to create a flexible returns schema that can be added to the customer's account

so 

the end customer can view and manage their returns.  

**Acceptance Criteria** 

The new schema accommodates flexible returns management.
An approved and merged architecture PR for the schema.
A merged and approve code PR(s).

**Schema PR**
https://github.com/magento/architecture/pull/397

**Schema Updates**
Please update the following type and change the field name from id to uid. 

EnteredCustomAttributeInput
Return
ReturnItem
CustomAttribute
ReturnComment
ReturnShippingCarrier
ReturnShippingTracking
Attribute
AttributeOption

**Comment by sasha19957099** [comment]
@magento run all tests
