### ISSUE TITLE
Configurable products: tier prices and attributes

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#2947]
Improvement suggestion.

I use a lot of configurable products in combination with tier prices.
The configuration of prices used to be in the configurable product in Magento1.

Now in Magento2 when I want to update the tier prices of my product, I have to edit every single simple product.
Since we have a product in 32 different colors and 3 sizes (so 96 simple products), this is not really user-friendly.

The default price can be configured by selecting a attribute in the configurable product.
It would be great if tier prices can be configured there too!
Or at least through mass-updates of attributes.

**Comment by antboiko** [comment]
Hi @gigadesign1 , we have created a ticket MAGETWO-47848 in our internal tracker for this improvement and put it into the backlog. Thank you for this request!

**Comment by mswaidan** [comment]
It would be really fantastic if tiered pricing could be applied to configurable products. I want to be able to offer pricing tiers based on total quantities of a configurable product, not just quantities of individual products. E.g. if there is t-shirt available in red, yellow, blue, I want to be able to offer a discount based on 10 shirts of any color, not just 10 red shirts or 10 yellow shirts. There was an extension available for magento 1 to do this, but no solution for 2 yet that I'm aware of.

**Comment by ritschi72** [comment]
Hi everybody, I've got the same problem with tier prices, I also got lots of configurable products where I want to update tier prices without going into every simple product. 
Does somebody have an idea where I can find an extension or any other way to solve this problem?

**Comment by dougkozar** [comment]
Please consider resurrecting tiered pricing on reconfigurable products in Magento 2

**Comment by ChrisCarterIO** [comment]
There are no extension to add this functionality either.  Please bring it back!

**Comment by ajones16** [comment]
I also have this issue with over 300 products with 90% having multiple options, we use Tiered Pricing for everything.
It would be great if there was a way on the main configurable product to enter the base price for the product and then on the configurable options use an option of either a +/- pricing structure for attributes OR setting a base price for the attribute that uses the same percentage difference as the base product.
i.e. base product QTY 1 = 16.67 , QTY 2 = 13.34 (20%), QTY 10 = 13.02 (22%)
Automatically next option = +$4.00 and therefore QTY 1 = $20.67 and AUTO QTY 2 = 16.54
OR
base Product QTY 1 = 16.67 , QTY 2 = 10% (15.00), QTY 10 = 15% (14.17)
Next Option = +$4 and therefore QTY 1 = 20.67 , QTY 2 = 10% (18.60) , QTY 10 = 15% (17.57)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-products-tier-prices-and-attributes/idi-p/46183).
