### ISSUE TITLE
Can't use livereload anymore because of new CSP policy

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29488]
### Summary (*)

I am using a tool called livereload, which helps to fasten the workflow when working with LESS.
The script does not work anymore since magento added a new module (Magento_CSP).
I get:

> Refused to load the script 'http://www.company.de:35729/livereload.js' because it violates the following Content Security Policy directive ... Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."

Note that I get this message, even though the script is hosted on my own server.
How can I whitelist this?

### Examples (*)

-

### Proposed solution

Make it possible to whitelist scripts loaded from own server.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
I posted a question on stackoverflow:
https://magento.stackexchange.com/questions/319636/magento-2-how-to-allow-livereload-in-csp-whitelist

**Comment by vahir2016** [comment]
Hello,

You can already whitelist scripts, you should read : https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html

Personally, I use flancer32/csp to create rules from database.

Regards

**Comment by mrtuvn** [comment]
IMO the quickest way to bypass is disable module Magento_Csp

**Comment by Eddcapone** [comment]
> Hello,
> 
> You can already whitelist scripts, you should read : https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html
> 
> Personally, I use flancer32/csp to create rules from database.
> 
> Regards

It is not described how to whitelist a script from your own server though. How can I do it and why does magento not even trust my own server?

**Comment by vahir2016** [comment]
> It is not described how to whitelist a script from your own server though. How can I do it and why does magento not even trust my own server?

By default, Magento CSP is on "report-only" he can't block your custom script. It only shows warnings in browser's console. Are you sure your problem is related to CSP ?

**Comment by Eddcapone** [comment]
Yes it is. If I disable the module Magento_Csp then it works and I am already in report only mode.
