### ISSUE TITLE
Wrong product URL rewrites in Multistore setting

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#29481]
### Preconditions (*)

1. Magento 2.3.5-p1
2. Multiple scopes

### Steps to reproduce (*)

1. In admin open a product
2. Change scope. For example Default (Dutch) => German
3. Delete URL key and save product

### Expected result (*)

1. URL key in german scope should be made from the German product name

### Actual result (*)

1. URL key in german scope keeps the same as the default scope

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @mtjweb Hello @justinwatkins
I am not able to reproduce this issue  by provided steps. Tested on the latest 2.4-develop and 2.3.5-p2 branches. 
Could you check my steps are correct?  
*Testing scenario:*

*Steps to reproduce:*

1. Create new store view
2. Set to German locale 
3. Create simple product
4. Open a product for editing 
5. Change scope. For example Default (Dutch) => German
6. Change Product Name
7. Expand the "Search Engine Optimization" section
8. Delete URL key and save product

**Result:**
URL key in german scope consists of the German product name
![Peek 2020-08-25 18-46](https://user-images.githubusercontent.com/51681379/91197417-f59f5700-e703-11ea-95fe-7e7a7dfa2b8e.gif)
![Peek 2020-08-25 18-07](https://user-images.githubusercontent.com/51681379/91197448-fd5efb80-e703-11ea-8b98-c17a32ec0e95.gif)

**Comment by mtjweb** [comment]
That's the right way to reproduce. But the URL rewrite isn't created. You can check this under Marketing -> URL Rewrite and also check this in the front end when switching scope when you are on a product page.

**Comment by engcom-Delta** [comment]
![Peek 2020-08-26 11-12](https://user-images.githubusercontent.com/51681379/91281252-83c11f00-e790-11ea-9995-aa3632815829.gif)

**Comment by engcom-Delta** [comment]
@mtjweb 
Please check if enable [Automatic Redirects](https://docs.magento.com/user-guide/marketing/url-redirect-product-automatic.html)
In the admin panel
![Screenshot_123](https://user-images.githubusercontent.com/51681379/91283510-5b86ef80-e793-11ea-9768-395a6839955f.png)

**Comment by mtjweb** [comment]
Yes, that's enabled.
![Schermafbeelding 2020-08-26 163831](https://user-images.githubusercontent.com/16004337/91317712-acf6a500-e7ba-11ea-8bb8-bff7b4a7f2ef.png)

**Comment by engcom-Delta** [comment]
@mtjweb 
As you can see from my comments above, it works for me

**Comment by engcom-Delta** [comment]
mtjweb Issue was rechecked on latest 2.4-develop and it is not reproducible
**Result:**
URL key in specific scope is made from the product name in this specific scope
![image](https://user-images.githubusercontent.com/51681379/95753253-06069380-0caa-11eb-881b-a84e74ba78da.png)
Feel free to recheck issue in magento instance (here is command to [deploy](https://github.com/magento/magento2/issues/29481#issuecomment-672016648)) and update it if something was missed
