### ISSUE TITLE
Where'is code folder 

### ISSUE THREAD

**Issue by Tibaus** [magento/magento2#2948]
Hello, in magento 1.x version the folder 'app/code' was enable, but in 2.x version this folder is not valid, where can i input the module? 
Thanks!
Sorry if i'm saying something wrong

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.
