### ISSUE TITLE
B2B GraphQL :: Login as Customer

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#29480]
As a developer,

I want to create a flexible login as a customer schema that can be added to the graph

so 

a merchant or merchant admin can log into an end customer's account to assist them with their account.  

**Acceptance Criteria** 

> The new schema accommodates flexible login as a customer functionality.
> Only requests with an admin token can be successful.
> An approved and merged architecture PR for the schema.
> A merged and approve code PR(s).

**Schema PR**
https://github.com/magento/architecture/pull/414

**fixes**
https://github.com/magento/magento2/pull/30130

**Comment by KrishnaK-Z** [comment]
@magento I am working on this

**Comment by mauragcyrus** [comment]
@magento confirm issue
