### ISSUE TITLE
UI : Time field element in admin

### ISSUE THREAD

**Issue by sankalpshekhar** [magento/magento2#29496]
The CSS class for limited width doesn't gets applied after CSP port.

Tested on :
1. Google Chrome : Version 84.0.4147.125 (64-bit)
2. Firefox : 79.0 (64-bit)

### Preconditions (*)

1. Magento 2.4 Installed with Sample data
2.

### Steps to reproduce (*)

1. Install M2.4.0 with Sample Data
2. Login to Admin/Backend.
3. Navigate to following path Store > Configuration > Catalog > XML Sitemap > Generation Settings
4. Switch the value on 'Enabled' field to 'Yes'

### Expected result (*)

![image](https://user-images.githubusercontent.com/1021508/90031548-f99e9400-dc82-11ea-8ac2-366bdf33db08.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/1021508/90031450-dd025c00-dc82-11ea-9afa-6cd17de25398.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36669` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by magento-engcom-team** [comment]
Hi @sankalpshekhar. Thank you for your report. 
The issue has been fixed in magento/magento2#29511 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [23b5a2488586c0ed493a834a04669e5c410ca85a](https://github.com/magento/magento2/commit/23b5a2488586c0ed493a834a04669e5c410ca85a)
 - [3723b61e6ec9a3dea7265f8cafae692d60bd2b69](https://github.com/magento/magento2/commit/3723b61e6ec9a3dea7265f8cafae692d60bd2b69)

The fix will be available with the upcoming 2.4.1 release.
