### ISSUE TITLE
Some of the admins panel tab not loading.

### ISSUE THREAD

**Issue by geekizaidi** [magento/magento2#29495]
### Preconditions (*)

1. Magento version: Magento 2.3.3
2. Live server

### Steps to reproduce (*)

1. Not exactly why the problem came to me
2. I was installing some extensions but most of the time the panel was fine

### Expected result (*)

1. 
![Screenshot (161)](https://user-images.githubusercontent.com/44756985/90027572-1f9f5500-dcd2-11ea-9e02-f034bdf30e47.png)
![Screenshot (162)](https://user-images.githubusercontent.com/44756985/90027601-262dcc80-dcd2-11ea-9da9-6211a08ad993.png)

2. Only some tabs not showing up

### Actual result (*)

1. I did static content deploy command and no error is shown till now
2. I just want the tabs work fine

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
Hello @geekizaidi 

Could you please provide more details?
Without exact steps to reproduce and actually expected results, it almost not possible to replicate and fix this issue.

Also, if you are Magento Commerce user, I would recommend report this problem to the Magento Support portal associated with your account.

**Comment by geekizaidi** [comment]
> 
> 
> Hello @geekizaidi
> 
> Could you please provide more details?
> Without exact steps to reproduce and actually expected results, it almost not possible to replicate and fix this issue.
> 
> Also, if you are Magento Commerce user, I would recommend report this problem to the Magento Support portal associated with your account.

I don't know what exactly the cause is. After installing all of my required extensions i then setup my shipping methods etc and few days when i'd to change the shipping cost i visit the shipping sections but some of tabs were not loading. There is no error in the logs nor in the console. 
I report the issue in magento community still waiting for any response there.

**Comment by krishprakash** [comment]
Hi @geekizaidi. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](community forum) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this problem
