### ISSUE TITLE
 Swatches from disabled items visible on store front

### ISSUE THREAD

**Issue by ved1585** [magento/magento2#29499]
1. Createed configurable product
2. Added 10 child with different color variant 
3. 5 child in disabled mode.
4. on PLP and PDP  displaying 10 color swatches 
5. Expected  5 color swatch should be display on PLP and PDP

 - Information on your environment, Magento2.3.3 , PHP 7.3.3

**Comment by engcom-Delta** [comment]
Hi @ved1585 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
![Peek 2020-08-14 09-47](https://user-images.githubusercontent.com/51681379/90221690-52049b80-de13-11ea-878e-9a6815e059b2.gif)

If you'd like to update the issue, please reopen it.
