### ISSUE TITLE
Add custom URL rewrites using the Rest API?

### ISSUE THREAD

**Issue by LiamTrioTech** [magento/magento2#29509]
Can this be done?
Resource Access is All but I can't seem to see the endpoint in Swagger?

Magento 2.3.2

**Comment by krishprakash** [comment]
Hi @LiamTrioTech. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic

**Comment by LiamTrioTech** [comment]
Feature request.
