### ISSUE TITLE
suggestion for other locales and options!

### ISSUE THREAD

**Issue by sIiiS** [magento/magento2#2950]
Can anything be done to define "decimals, precision, etc" or force the script to automatically detect "options" based on the locale during setup?

For example in Persian:
precision is "0" not "2" ... ex. 5 is correct not 5.00
decimals is "0" not "4" ... ex. 20 is correct not 20.0000
script is "Arabext" not "Latn",
currency position is "Right" not "Left",
etc!

**Comment by antboiko** [comment]
Hello @sIiiS, sorry for the delay with response. Thanks for your inquiry. We've created internal ticket MAGETWO-52680 for this feature and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/suggestion-for-other-locales-and-options/idi-p/46180).
