### ISSUE TITLE
upgrading from 2.3.3 to 2.4.0 causes category widget cms page to display Error filtering template: Notice: Array to string conversion

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#29505]
### Preconditions (*)

1.install 2.3.3 
2.load up a child theme to luma 
3. upgrade to 2.4.0 
4. centos 7. 

### Steps to reproduce (*)

1.install 2.3.3 
2.load up a child theme to luma 
3. setup a cms page to display the products via widget for a specific category. 
4. upgrade to 2.4.0 
5. check cms page afterwards. 

### Expected result (*)

1. should show the products from that category.
2.

### Actual result (*)

1.Error filtering template: Notice: Array to string conversion in /home/examplesite/public_html/vendor/magento/framework/Escaper.php on line 261

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @dmcmillin . Unfortunately, we are not able to reproduce this issue.

**Manual testing scenario:**

1. Install Magento 2.3.3 composer;
2. Load up custom child theme to **Luma**;
3. Go to Admin -> Content -> Pages and Add New Page;
4. Fill title (**test** for example) field and click on **Insert Widget...** button;
5. Select **Catalog Category Link** from drop-down menu and select any category with products;

![Screenshot from 2020-08-14 15-50-36](https://user-images.githubusercontent.com/51679138/90251283-2058f800-de46-11ea-9ff4-4f49147fdd67.png)
6. Click on Save button;
7. Upgrade Magento to 2.4.0 version;
8. Go to Storefront and check created before page

**Actual Result:** :heavy_check_mark: Products in this category are displayed

![Peek 2020-08-14 16-05](https://user-images.githubusercontent.com/51679138/90252534-59926780-de48-11ea-9306-29bf6bf16db6.gif)

Maybe we missed some details. Could you provide us with more details to reproduce this issue?

Thanks!

**Comment by dmcmillin** [comment]
@engcom-Alfa - What could I provide so you see what I am encountering? All plugins are magento only. All I did was upgrade from 2.3.3. to 2.4 and now its displaying that error.

**Comment by mlaurense** [comment]
@engcom-Alfa I am experiencing the same error, but not with the **Catalog Category Link** widget, but the **Catalog Products List** widget.

1. Open CMS page (e.g. home)
2. Add a Catalog Products List widget
3. Enter a title, choose Products Grid Template
4. Conditions: SKU is (choose any existing SKU)

Result is the error @dmcmillin is also experiencing. If you re-read his error report, he already described it:
"setup a cms page to display the products via widget for a specific category"
You just created a link to an existing category which is not the same.

**Comment by mlaurense** [comment]
Turns out the error is originating from the call to getImage:
```<?= $block->getImage($_item, $image)->toHtml() ?>```
Further investigation leads to a theme override of vendor/magento/module-catalog/view/frontend/templates/product/image_with_borders.phtml which was heavily modified in 2.4.0. Disabling this override fixes the problem.

**Comment by gitd-eystudios** [comment]
> Turns out the error is originating from the call to getImage:
> `<?= $block->getImage($_item, $image)->toHtml() ?>`
> Further investigation leads to a theme override of vendor/magento/module-catalog/view/frontend/templates/product/image_with_borders.phtml which was heavily modified in 2.4.0. Disabling this override fixes the problem.
