### ISSUE TITLE
Can't add script with ampersant (&) symbol in url

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29514]
### Preconditions (*)

1. Magento 2.3.5-p2

### Steps to reproduce (*)

1. Create fresh theme
2. Add this script to *Magento_Theme\layout\default_head_blocks.xml*:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <css src="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" src_type="url"/>
    </head>
</page>
```

### Expected result (*)

1. Script should get included

### Actual result (*)

1. Script does not appear in head section of html source code.

If I remove `&display=swap` then it works.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@Eddcapone you have a mistake. In the xml patameters ampersand symbol need to be replaced to escaped value `&amp`, so your file should look like this:
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <css src="https://fonts.googleapis.com/css2?family=Open+Sans&amp;display=swap" src_type="url"/>
    </head>
</page>
```

**Comment by Eddcapone** [comment]
Thank you, but it looks still like a bug to me, since no one can know this. I also did not found it in the documentation. Can you show me the entry?

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
This is special character in all XML files, not only in magento.
You can see it https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

Is suggested solution works fine for you?

**Comment by mrtuvn** [comment]
you should use link instead css tag 
Example
<link src="https://fonts.googleapis.com/css2?family=Inter&amp;display=swap" rel="stylesheet" src_type="url"/>

**Comment by Eddcapone** [comment]
@mrtuvn what is the difference?
