### ISSUE TITLE
Can't add script from external sources

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29513]
### Preconditions (*)

1. Magento 2.3.5-p2

### Steps to reproduce (*)

1. Create theme
2. Add the following code to **Magento_Theme\layout\default_head_blocks.xml**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous"
              src_type="url"
              type="text/css"
        >

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"
                src_type="url"
        >
        </script>
    </head>
</page>
```

3. Flush cache
4. Load site and inspect source code
5. Notice that the scripts are not showing anywhere in the head section.

### Expected result (*)

1. Scripts should get rendered in head html section.

### Actual result (*)

1. Scripts are not showing at all.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
I also removed the attributes `integrity` and `crossorigin` because I thought they are maybe not supported by magento 2, but it still fails. I executed `grunt clean` to clear the cache.

**Comment by mrtuvn** [comment]
Have you try this
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css

**Comment by Eddcapone** [comment]
I had to use `css` instead of `link` and I had to change `href` to `src`
