### ISSUE TITLE
Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file

### ISSUE THREAD

**Issue by rreid2020** [magento/magento2#29521]
I receive this error when trying to export products in Magento 2.3.  Is there a solutions to this issue?

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @rreid2020. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
