### ISSUE TITLE
Install Magento 2.4 : could not validate a connection to elasticsearch. no alive nodes found in your cluster

### ISSUE THREAD

**Issue by garihogar** [magento/magento2#29534]
Hi, I'm having the same problem you reported on GitHub in the Magento 2.4 installation

In SearchConfig.php line 81:

Could not validate a connection to Elasticsearch. No alive nodes found in y

our cluster  

I've got elasticserarch running locally, I've got kibana, brain and enterprise-search hooked up and they're all communicating smoothly and reporting a green health status.

My version of elastic search is 7.8.1

at elasticsearch.yml I now have these rules active

cluster.name: ga+++++r

xpack.security.enabled: true

xpack.security.authc.api_key.enabled: true

path.data: /var/lib/elasticsearch

path.logs: /var/log/elasticsearch

network.host: localhost

network.publish_host: 127.0.0.1

network.bind_host: 127.0.0.1

http.port: 9200

transport.tcp.port: 9300

discovery.type: single-node

My installation command is:

bin/magento setup:install \

--base-url=https://++++++++.de \

--db-host=localhost \

--db-name=G+++++++bd \

--db-user=G++++++++++0 \

--db-password=@+++++++++++@ \

--admin-firstname=J++++n \

--admin-lastname=W++++r \

--admin-email=jw++++++++++ail.com \

--admin-user=j++++++++s \

--admin-password=B+++++++++k \

--language=en_US \

--currency=USD \

--timezone=America/Chicago \

--use-rewrites=1 \

--search-engine=elasticsearch7 \

 --elasticsearch-host=https://127.0.0.1:9200 \

--elasticsearch-port=9200 \

--elasticsearch-enable-auth=1 \

--elasticsearch-username=elastic \

--elasticsearch-password=@el++++++++++++++gar#

Someone has had this problem and managed to solve it or knows how to solve it.

I need help.

**Comment by garihogar** [comment]
when you run the installation command:
bin/magento setup:install \
--base-url=https://++++++++.de \
--db-host=localhost \
--db-name=G+++++++bd \
--db-user=G++++++++++0 \
--db-password=@+++++++++++@ \
--admin-firstname=J++++n \
--admin-lastname=W++++r \
--admin-email=jw++++++++++ail.com \
--admin-user=j++++++++s \
--admin-password=B+++++++++k \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1 \
--search-engine=elasticsearch7 \
--elasticsearch-host=https://127.0.0.1:9200 \
--elasticsearch-port=9200 \
--elasticsearch-enable-auth=1 \
--elasticsearch-username=elastic \
--elasticsearch-password=@el++++++++++++++gar#

the installation stops with the error:

In SearchConfig.php line 81:
Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

My system configuration:
Centos 8
Apache/2.4.37 (centos)
PHP 7.4.9 (cli)
Zend Engine v3.4.0
Zend OPcache v7.4.9
Elasticsearch 7.8.1
mysql  Ver 15.1

Steps to reproduce it:
Installation of centos8+LAMP
Installation of Elasticsearch+Config elasticsearch.yml

---------

cluster.name: garihogar
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: localhost
network.publish_host: 127.0.0.1 (also tested with the following options http://127.0.0.1  | https://127.0.0.1 | http://localhost | http://127.0.0.1:9200 | http://localhost:9200 | http://0.0.0.0:9200 )
network.bind_host: 127.0.0.1 (also tested without this command)
http.port: 9200 
transport.tcp.port: 9300 (also tested without this command)
discovery.type: single-node (also tested without this command)

--------
 


Install composer and run composer command for Magento 2.4
Access the Magento folder in Httpd
Execute installation command

bin / magento: instalar \
--base-url = https: //++++++++.de \
--db-host = localhost \
--db-name = G +++++++ bd \
--db-user = G ++++++++++ 0 \
--db-password = @ +++++++++++ @ \
--admin-firstname = J ++++ n \
--admin-lastname = W ++++ r \
--admin-email = jw ++++++++++ ail.com \
--admin-user = j ++++++++ s \
--admin-password = B +++++++++ k \
--language = en_US \
--divisa = USD \
--zona horaria = América / Chicago \
--use-rewrites = 1 \
--search-engine = elasticsearch7 \
 --elasticsearch-host = https://127.0.0.1:9200 \  (Tested with the different ip options used)
--elasticsearch-port = 9200 \
--elasticsearch-enable-auth = 1 \
--elasticsearch-username = elastic \
--elasticsearch-password = @ el ++++++++++++++ gar #

**Comment by garihogar** [comment]
The only thing I doubt is the Elasticsearch version. Version 7.8.1 is compatible with Magento 2.4?
I understand it's version 7.6 or higher. No?

**Comment by garihogar** [comment]
Error detected.
I cloned the server, uninstalled Elasticsearch and reinstalled it this time without the authentication enabled and it installed without problem.

I think the bug is in using username and password in localhost

Someone can check what I explain to provide a solution

**Comment by camelscript** [comment]
Got the same issue and could not install even with Auth Basic disabled. Elasticsearch is running and i can $curl and see "200 OK" and the JSON that Elasticsearch provides but still an error during isntallation.

**Comment by mandarmorye** [comment]
Also try `--elasticsearch-host='127.0.0.1' --elasticsearch-port='80'`

**Comment by Eddcapone** [comment]
I have the same problem. I entered valid credentials but I still get the error! Magento 2.4.0 has too many bugs.

**Comment by Eddcapone** [comment]
I had the same problem because I accidentially entered a wrong port number.

**Comment by bartoszkubicki** [comment]
It works if you add --elasticsearch-host=<host> --elasticsearch-port=<port> to installation command. It should be mentioned in docs

**Comment by jcellon** [comment]
Make sure your --elasticsearch-host=<domain> and --elasticsearch-port=<port> query, matches your elasticsearch configurations <domain> and <port>. In my case: --elasticsearch-host=localhost --elasticsearch-port=9200 which you can verify by going to http://localhost:9200/
It should work! I hope it helps.

**Comment by tuyennn** [comment]
Has same issue, pretty sure I didn't touch to any configuration, just do the deployment but the problem found

**Comment by Eddcapone** [comment]
Please check if you have `--search-engine = elasticsearch7` in your install command. Also check what happens if you enter the URL in the browser.

So if your host and port is set to this:

```
--elasticsearch-host = https://127.0.0.1 \
--elasticsearch-port = 9200
```

Then enter `https://127.0.0.1:9200` in the browser. If it works, then a javascript object should show.
If you need authentication, then you also have to use this:

```
--elasticsearch-enable-auth=1 \
--elasticsearch-username=xxxxx \
--elasticsearch-password=yyyyy
```

**Comment by bartoszkubicki** [comment]
Still an issue

**Comment by elharony** [comment]
Still facing it. Any suggestions?

**Comment by engcom-Bravo** [comment]
Hi @garihogar ,

Please let us know if you are still facing this issue.

**Comment by engcom-Delta** [comment]
There  has no update from reporter and it has been ~14 days. Hence closing the ticket.
Kindly log new ticket if required or re-open the existing issue.

**Comment by Urviwd** [comment]
https://www.fosstechnix.com/how-to-install-elastic-stack-on-ubuntu-22-04/

uninstall the last elasticsearch files and follow above link
