### ISSUE TITLE
Newsletter queue start date is not working properly in magento 2.3.4

### ISSUE THREAD

**Issue by nuntapon-hir** [magento/magento2#29532]
### Preconditions (*)
Hi guys , can anyone help me on this. Basically am using Magento 2.3.4-p2 and am here trying to send newsletter . After saving the newsletter queue the queue start date is changing from Thailand standard time to some other format . I was already set the Timezone in magento2

Thank you.

### Steps to reproduce (*)

1. Create Newsletter Templates
2. Select 'Action' create 'Queue' for created Newsletter Templates in the Grid
3. For field 'Queue Date Start' select 'Go today' to set present time and date

### Expected result (*)

1. The Newsletter Queue send by queue start time that we set

### Actual result (*)

1. The Newsletter Queue didn't set and queue start time always change the time zone

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37647` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
