### ISSUE TITLE
Store view creation fails when we have two cms pages with different scopes

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#29538]
### Preconditions (*)
1. Two store views
![image](https://user-images.githubusercontent.com/1873745/90235599-4375ae80-de2a-11ea-9459-c75460c53e4c.png)

2. two CMS pages with the same identifier "home", one assigned to "default store view", 2nd has assigned to "second store view"
![image](https://user-images.githubusercontent.com/1873745/90235625-4ec8da00-de2a-11ea-8393-67ad20232835.png)

### Steps to reproduce (*)
1. Go to Admin > Stores > All Stores
2. Click "Create Store View", put it in the same store as "Default Store View"
3. Click "Save" button

### Expected result (*)
1. Store view should be created without any issues

### Actual result (*)
1. Store view creating fails
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-29538-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29538-2-4-develop.instances.magento-community.engineering/admin_d9ef](https://i-29538-2-4-develop.instances.magento-community.engineering/admin_d9ef)
Login: `d7d4e474` Password: `37c62d164482`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
Can't reproduce on clean magento installation .Can't create CMS page with the same identifier for specific store view.

**Comment by ihor-sviziev** [comment]
Duplicate of https://github.com/magento/magento2/issues/28357, it was already fixed.
