### ISSUE TITLE
Date time ui component is not taking the time which we give it is converting the time to GMT

### ISSUE THREAD

**Issue by sandy6666** [magento/magento2#29533]
In Magento backend in a custom form date, time picker is converting time for GMT instead of using the server timezone specified.
### Preconditions (*)

1. In Magento 2.3.5-p2

### Steps to reproduce (*)

1. create a date time picker UI component
2. Click on save

### Expected result (*)

1. [Screenshots, logs or description]
2. It should take the timezone which is given in server while saving in DB

### Actual result (*)

1. [Screenshots, logs or description]
2. It is saving time as per GMT timezone

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sandy6666** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @sandy6666. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sandy6666, here is your [Magento instance](https://i-29533-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29533-2-4-develop.instances.magento-community.engineering/admin_46e4](https://i-29533-2-4-develop.instances.magento-community.engineering/admin_46e4)
Login: `92a0548b` Password: `a372e24f8e73`
Instance will be terminated in up to 3 hours.

**Comment by sandy6666** [comment]
@magento I am working on this

**Comment by sandy6666** [comment]
@magento add to contributors team

**Comment by sandy6666** [comment]
@magento I am working on this

**Comment by sandy6666** [comment]
It is correct when it comes to multi website timezones
