### ISSUE TITLE
Catalog Product Website Link Repository V1  SOAP API All Store Views Only remove role from image

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#29545]
### Preconditions (*)
1.Magento2.2.2

### Steps to reproduce (*)

2. Create configurable product either manually or VIA API add at least one image on all store view and assign all the roles to it.
3. Create simple product and assign to the configurable just created (not really necessary but this is what I have ).
4. Via any tool  like postman (in my case). send the following.

**POST:** https://magento2/soap/all?services=catalogProductWebsiteLinkRepositoryV1

**BODY:**
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="https://magento2/soap/all?services=catalogProductWebsiteLinkRepositoryV1">
    <soap:Body>
        <def:catalogProductWebsiteLinkRepositoryV1SaveRequest>
            <productWebsiteLink>
                <sku>product-sku</sku>
                <websiteId>1</websiteId>
            </productWebsiteLink>
        </def:catalogProductWebsiteLinkRepositoryV1SaveRequest>
    </soap:Body>
</soap:Envelope>
```
### Expected result (*)

1. <result>true</result>
2.

### Actual result (*)

1. <result>true</result> 
2.Everything looks good but when look in the backend image role has been removed/ and frontend category image has default image instead.

This was tested on 2 separate version on 2.2.2 all replicable.

What I notice if change store view and add role to images then if send the API again with store view 1 image role stay intact.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @lano-vargas thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Create second website
![image](https://user-images.githubusercontent.com/51681379/98961457-4017bf00-250e-11eb-9a65-06d14279cf46.png)
- Create configurable product with two configurations
![image](https://user-images.githubusercontent.com/51681379/98961166-ef07cb00-250d-11eb-8d3d-142076e02ab6.png)
![image](https://user-images.githubusercontent.com/51681379/98961188-f7f89c80-250d-11eb-8279-3e660cb8c83e.png)
- Add image configurable product and assign all the roles to it
- POST: https://magento2/soap/all?services=catalogProductWebsiteLinkRepositoryV1
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://magento2dev.loc/soap/all?services=catalogProductWebsiteLinkRepositoryV1">
    <soap:Body>
        <def:catalogProductWebsiteLinkRepositoryV1SaveRequest>
            <productWebsiteLink>
                <sku>conf1</sku>
                <websiteId>2</websiteId>
            </productWebsiteLink>
        </def:catalogProductWebsiteLinkRepositoryV1SaveRequest>
    </soap:Body>
</soap:Envelope>
```

**Result:**
:heavy_check_mark: Response is true
:heavy_check_mark: Image roles stay same
![Peek 2020-11-12 17-47](https://user-images.githubusercontent.com/51681379/98962578-7275ec00-250f-11eb-94b1-778cf5d5398e.gif)

If you'd like to update the issue, please reopen it.
