### ISSUE TITLE
Magento 2 Api Integration Not Working

### ISSUE THREAD

**Issue by pkhutal** [magento/magento2#2954]
Hello,
  I have done Magento 2.0 Installation but when trying  to generate API keys from admin panel system-->Integration-->add New Integration-->save .I get infinite please wait  processing bar.Please help me for this issue.

**Comment by mazhalai** [comment]
@pkhutal can you please give more information about your environment? OS, versions of php, mysql and server?

**Comment by pkhutal** [comment]
Windows 7 Webserver
PHP 7.0
mysql is 5.5

**Comment by mazhalai** [comment]
@pkhutal minimum mysql version is 5.6.  How did you install Magento2? Also, looks like this is similar to #2955

**Comment by pkhutal** [comment]
ok...thank you.

**Comment by daim2k5** [comment]
@pkhutal hopfully its now working for you. If not please feel free to reopen the issue
