### ISSUE TITLE
Cart is being dropped on a non-cached page when Persistent cart module is uninstalled

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#29562]
### Preconditions (*)
1. Goal: **decomposition of modules** - Being able to disable one module without side effects
2. Uninstalled **Persistent** module
3. Enabled Full Page Cache (does not matter if Varnish or built-in)

### Steps to reproduce (*)
1. Make sure that your FPC is enabled, and Persistent module is uninstalled
2. Add product to cart
3. Expect Minicart to contain the product
3. Open a non-cached page

### Expected result (*)
1. You should still have your cart
2.

### Actual result (*)
1. The cart is unassigned from your session.
2. Cart Items are still in database (thus it's not being purged)

### Additional information
The problem occurs during Full Page Cache management, but I wasn't able, due to limited time, to find exact place what makes the code fail. It does not occur when you are loading previously cached page.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lbajsarowicz** [comment]
Related: https://github.com/magento/magento2/issues/21614

**Comment by lbajsarowicz** [comment]
Related: https://github.com/magento/magento2/issues/17973

**Comment by lbajsarowicz** [comment]
@jissereitsma Do you have any updates on whether the issue was sorted already?

**Comment by jissereitsma** [comment]
@lbajsarowicz You mean with the composer replacement tricks? Because the issue itself does not ring a bell?

**Comment by lbajsarowicz** [comment]
@jissereitsma Yes, the issue with "hidden" coupling of Magento Sales depending on Persistent module (thus, when you removed Persistent module, Shopping Cart stopped working)

**Comment by lbajsarowicz** [comment]
@jissereitsma You see, problem solved :-D

**Comment by hostep** [comment]
https://github.com/magento/magento2/issues/21614 is still open luckily, one day, maybe one day, maybe it will get fixed ...
