### ISSUE TITLE
Unable to add products to cart, M2.3.4

### ISSUE THREAD

**Issue by zedlockuk** [magento/magento2#29561]
We are unable to add products to the shopping cart (URL: zedlock.com). The timer icon appears next to the cart but nothing else happens:
![Zedlock shopping basket issue](https://user-images.githubusercontent.com/69712533/90308882-32d14100-dedb-11ea-93ca-bedb42dbea41.png)

In addition, from Admin we are denied access to the 'Products' area:
![Zedlock Error page 13 Aug](https://user-images.githubusercontent.com/69712533/90308875-1e8d4400-dedb-11ea-98a1-2c9766fcb4e0.png)

Severity: **S1**
@magento give me 2.4-develop instance - upcoming 2.4.x release
@magento I am working on this

Any ideas much appreciated!

**Comment by engcom-Delta** [comment]
Hi @zedlockuk thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop seems like this related to your custom modules.
![image](https://user-images.githubusercontent.com/51681379/90389581-833ecf00-e092-11ea-8190-a82e623bd0a6.png)

If you'd like to update the issue, please reopen it.
