### ISSUE TITLE
Media Uploader Issues

### ISSUE THREAD

**Issue by Khaleel** [magento/magento2#2958]
Hi

I want to raise some issues on the hideous and bloated Media uploader for Magento 2 and shoot the person who built this pile of crap.
- Cannot upload SVG images
- Poor UI and UX
- No indication of uploaded content
- Firefox has thousands of issues including JS issues with not allowing the upload option to show
- The upload button is text and should be made to a button
- No history tracking

It does not even work half the time in Chrome or Firefox. Since the last update the design has also broken and why does it scale full screen to to the right?

**Comment by Khaleel** [comment]
![screen shot 2016-01-11 at 3 28 20 pm](https://cloud.githubusercontent.com/assets/355336/12232444/002cf2e6-b878-11e5-941f-00de3a61c195.png)

Should be a button ^

![screen shot 2016-01-11 at 3 28 10 pm](https://cloud.githubusercontent.com/assets/355336/12232448/0c30a880-b878-11e5-9e5b-d508fc1a588d.png)

Why does it scale to the right half the screen?

Is is possible to use another Image or File Manager; OpenCart has a better manager than this.

**Comment by benmarks** [comment]
> "...and shoot the person who built this pile of crap."

That's **_completely**_ unnecessary and unprofessional, @Khaleel.

**Comment by Khaleel** [comment]
If no emotion is shown then how can we progress.

**Comment by benmarks** [comment]
> *"If no emotion is shown then how can we progress."

The answer is simple: we're professionals, a fact demonstrated by the issues resolved in this channel without (or in spite of) emotional appeal. Note that there is a massive difference between expressing frustration and threatening violence (which you did). Do not make that mistake again please. It adds nothing of merit to the report (which in itself is quite valuable), and similar conduct in the future would render you unwelcome for continued participation. Feel free to express frustration if you must, but do so in a civil manner.

We're all developers here, and we know how frustrating it is to encounter bugs. Our aim is to move the software forward with the help of the folks using it.

**Comment by Khaleel** [comment]
Hi
Your comments are fair and yes we are all developers and we should try to work better via communication.

So, is there any updates of improving the media uploader - adding search, history and better archiving and UI and UX folder structures. Support for SVG - adding Arabic and other language support via UTF due to charset issues..

Thanks

**Comment by pboisvert** [comment]
@antboiko Anton--does this fall under product creation ownership? if so please accept and route as either issues or feature requests as applicable

**Comment by BenGlassAtlas** [comment]
I was just creating an issue for the SVG point and saw this, so I'll put my info here:

**SVGs can't be uploaded through the admin.**

## Steps to reproduce
1. Create a static block
2. Add an image
3. Try to upload an SVG

## Expected result
1. SVG is uploaded and can be added through the WYSIWYG editor

## Actual result
1. 'Please wait' spinner appears, then nothing has changed.

## Notes
- Other image formats are working fine, just not SVGs
- No related errors are given and nothing related in the logs
- Magento 2.0.4

**Comment by Khaleel** [comment]
This applies anywhere inside of M2 - even the latest GA releases; you cannot upload any form of SVG

**Comment by BenGlassAtlas** [comment]
Seems a rather odd choice as Magento 2 is attempting to push forward with up to date technologies.

**Comment by Khaleel** [comment]
@BenSpace48 Precisely I have tested on an Nginx build too. SVG work fine in the server - just cannot upload them!

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-52993 to address SVG file upload.

**Comment by piotrekkaminski** [comment]
Hello. We will fix the error messages to make it more clear in scope of MAGETWO-52993 but allowing upload of SVG files will take more time. SVG files are not currently supported by GD library used by Magento. We would have to move to another library (ImageMagick?) and it requires more changes. The full work is tracked in scope of MAGETWO-53778.

**Comment by BenGlassAtlas** [comment]
Thank you for the update! 😄

**Comment by KrystynaKabannyk** [comment]
Hello @Khaleel, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by piotrekkaminski** [comment]
@Khaleel @BenSpace48 The seems to be a lot of interest in SVG file upload. The problem is security. SVG format can include JavaScript and there are no good protections for it. The only solutions would be to convert it to something (JPEG/PNG) by external process and only then use, but i assume it doesn't make sense to use SVG anymore. It's highly unlikely we will add support for it unless there is major reason.  Can you tell me what is reason to use SVG for image upload for you?

**Comment by BenGlassAtlas** [comment]
@piotrekkaminski That's a good point, I presume that's also why Github doesn't support uploading SVGs to comments.

For our use case we needed to use SVGs for responsive reasons and consistency with the skin icons (all skin icons are SVG). There are quite a few advantages to using SVG over JPG/PNG, just a few are:
- Small size. SVG image elements take up much less space than their twins created in raster format
- Flexibility, SVGs can easily be animated/changed
- Scalability without changing the image quality. It is widely used for devices with screens Retina and those close to them

We had to resort to using a JPG which obviously did work but doesn't have the same quality as an SVG.

**Comment by Khaleel** [comment]
Thanks for the answers @BenSpace48. Also SVG are generally becoming more and more secure. You could possible drop the poor WYSIWYG editor and replace it with one the that validates them better. I noticed TinyMCE has issues with Arabic and other languages.

I agree though, SVG is really the way to go with Front End Development; beyond retina the quality is superior and it is being adopted across the web. @piotrekkaminski it seems your more of a Back End Developer as you would have placed them in by default.

**Comment by Ctucker9233** [comment]
I look forward to being able to use SVG's. It's a must have for quality responsive design.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Media-Uploader-Issues/idi-p/46160).

**Comment by amenk** [comment]
Trying my luck on an extension... https://magento.stackexchange.com/questions/182535/how-can-i-upload-svg-files-as-magento-product-images/182617#182617

**Comment by amenk** [comment]
Here is the extension I made: https://github.com/iMi-digital/magento2-module-svg-product-images - pull requests are welcome

**Comment by ghost** [comment]
@amenk I have used the extension which you made to allow SVG images on Magento 2 but it's not working as expected. I would like to upload the product images as SVG format. 
Could you please suggest me what should I do to allow SVG images on Magento 2?

**Comment by amenk** [comment]
It's best if you create a detailed issue on our github repo

**Comment by SivakumarTNS** [comment]
@amenk I have created an issue on github repo.

**Comment by ghost** [comment]
@amenk I have installed the extension which is allow to upload SVG on product images [https://github.com/iMi-digital/magento2-module-svg-product-images](https://github.com/iMi-digital/magento2-module-svg-product-images) as per your suggestion. Also I installed Imagemagick on my Xampp but still can't upload SVG images. 

Please comment.

**Comment by Prasad2706** [comment]
getting error for upload image from static block 
![error-image-upload](https://user-images.githubusercontent.com/46341163/55956465-a4630480-5c81-11e9-898c-554657991b94.png)
Magento Version 2.3.0
