### ISSUE TITLE
The constructor of the class \Magento\Framework\View\Result\LayoutFactory can be shortened by using PHP 5.5 class name resolution via ::class

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2962]
https://mage2.pro/t/topic/338

Similar to https://github.com/magento/magento2/issues/2794

**Comment by shiftedreality** [comment]
Hi @dfediuk 

This is minor issue and will be fixed in future. You can help by creating pull request.

**Comment by piotrekkaminski** [comment]
Closing in favor of more generic https://github.com/magento/magento2/issues/4068
