### ISSUE TITLE
Why does magento try to compile inactive themes?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29628]
### Summary (*)

I have two themes, company_base and company_fresh. I am only using **company_fresh** and company_base is just laying around atm.
If I execute `php bin/magento setup:static-content:deploy` then I often get errors from my inactive corrupted experimental theme `company_base` for example:

```
Compilation from source: /home/company/company.de/app/design/frontend/company/base/web/css/source/lib/extend/catalog/product/view.less
variable @dunkelgrau is undefined in file /home/company/company.de/var/view_preprocessed/pub/static/frontend/company/base/de_DE/css/source/lib/extend/catalog/product/view.less in view.less on line 6, column 16
4|     .h {
5|         font-family: os-semi-bold;
6|         color: @dunkelgrau;
7|         margin-bottom: 20px;
8|     }
9|     /* Mixins End ------------------------------ */
```

Why does magento even try to compile it?

### Examples (*)

Create a second theme beside your active one and make a mistake in a LESS file in it, on purpose, so that it will thrown an error.
Then call `php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy`. 
You should see an error during the compilation.

### Proposed solution

Ignore inactive themes.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@Eddcapone: quick fix - execute `bin/magento setup:static-content:deploy --theme=company_fresh`

I'd strongly recommend you to read the help so you are aware of all possible options of that command: `bin/magento setup:static-content:deploy --help`

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
As @hostep said, by default Magento executes static content on all themes. If you want to deploy only one theme - you can just specify it.

In addition to that recently we introduce a way to deploy then only the needed theme, without all parent themes in https://github.com/magento/magento2/pull/30090. AFAIK this change still not included in a stable release, so you could wait for the next release OR apply it as a patch.

As we don't have any issues there that need to be fixed - I'm closing this issue.
