### ISSUE TITLE
URL Rewrites Filter is not showing right result

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29625]
### Preconditions (*)

1. EE 2.3.5-p2

### Steps to reproduce (*)

1. Login to Backend
2. Open: Marketing -> SEO & Search: Url Rewrites
3. Set Filter for ID and search for a ID of a existing product, for example 5

### Expected result (*)

1. It should show the record with ID 5 if it exists.

### Actual result (*)

1. It shows all records which contains the number 5 in their ID

![image](https://user-images.githubusercontent.com/16349349/90490751-47ae0e80-e13f-11ea-84ae-d520663bf214.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
This is expected behavior I believe, searching in admin grids is supposed to work "fuzzy". Let's imagine you type `test` in the "request path" column, would you expect to only get one exact match? Or the two matches which are shown in your screenshot? In my opinion it should the second, it's much more user friendly.

The question then becomes: should filtering on an ID column differ and only return exact matches? I'm afraid I don't know the answer to that ...

**Comment by Eddcapone** [comment]
@hostep Yes. It makes sense for the *request path*  column, but not for the ID column

**Comment by engcom-Oscar** [comment]
Hello @Eddcapone 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.
If you have some more details how to reproduce this issue on latest 2.4 Magento, feel free to update the description and reopen it.

**Comment by Eddcapone** [comment]
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
@engcom-Oscar, I tried to reproduce it with the Magento Instance which the deployment service gave me, but there is a bug in URL Rewrites and it just loads forever and nothing happens.

**Comment by Eddcapone** [comment]
@engcom-Oscar, I testet again from another instance. Now it worked. Looks like the issue was resolved. Thank you.
