### ISSUE TITLE
how to fill  One-to-many model with just 1 SQL?

### ISSUE THREAD

**Issue by videni** [magento/magento2#29626]
# One to many relation

A  parent has muitple children. Let's say we want to query all parents with its children.

# Related classes

ParentModel, ChildModel , both are instance of Magento\Framework\Model\AbstractModel.

ParentCollection is an instane of \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection

# Question 

how can we get all parents that are filled with its children using just one SQL statement ?

Let's  assume 1 parent with 5 children.  the following will have 5 records which will be treated as ParentModel, but it is ChildModel.

```
class ParentCollection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init(
            \Vendor\A\Model\ParentModel::class, 
            \Vendor\A\Model\ResourceModel\ParentModel::class);
    }

     /**
     * Join plate_option table
     *  
     * @return self
     */
    public function withOptions(): self
    {
        $this->getSelect()
            ->joinLeft(
                [
                    'child' => $this->getTable("child")
                ], 
                'main_table.id= child.parent_id'
            );

        return $this;
    }
}
```

I check the source code of AbtrationCollection , it seems imposible to do this.

**Comment by krishprakash** [comment]
Hi @videni. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
