### ISSUE TITLE
[2.3.5-p2] GraphQl Special Price Ignore's special price from to dates.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#29631]
### Preconditions (*)

1. Magento 2.3.5-p2

### Steps to reproduce (*)

1. Create a product with a price of 100 and a special price of 50
2. Set a special from date of 1-1-1999, set a special to date of 1-1-2000
3. Run the following GraphQl query with the sku of the product created in step 1:
````query productDetail($sku: String) {
    productDetail: products(filter: { sku: {eq: $sku } }) {
        items {
            price_range {
                minimum_price {
                    regular_price {
                        currency
                        value
                    }
                    final_price {
                        currency
                        value
                    }
                }
                maximum_price {
                    regular_price {
                        currency
                        value
                    }
                    final_price {
                        currency
                        value
                    }
                }
            }
        }
    }
}
````

### Expected result (*)

Final price and regular price are identical.

### Actual result (*)

![Screenshot from 2020-08-18 14-01-59](https://user-images.githubusercontent.com/22170051/90510729-c2852280-e15b-11ea-9054-19f9c84bc8f9.png)
The Special from and to dates are never checked and thus the incorrect final price is returned.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Hexmage** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Hexmage. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Hexmage, here is your [Magento instance](https://i-29631-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29631-2-4-develop.instances.magento-community.engineering/admin_eddf](https://i-29631-2-4-develop.instances.magento-community.engineering/admin_eddf)
Login: `915d91dc` Password: `c72f060cd535`
Instance will be terminated in up to 3 hours.

**Comment by Hexmage** [comment]
Still an issue in 2.4

**Comment by rogyar** [comment]
Supposed to be fixed within the scope of https://github.com/magento/magento2/pull/30623
