### ISSUE TITLE
Not Able to get Destination City in CollectRate Method.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2967]
I am trying to get destination city in our custom shipping module in collectRates() Method but its giving blank from request.
Here is my collectRates() method code:

   public function collectRates(\Magento\Quote\Model\Quote\Address\RateRequest $request)
    {
      if ($request->getDestCity()) {
            $r->setDestCity($request->getDestCity());
        }
   }

I have tried my best to find the destination city , but not able to find in quote session.

Please provide me the solution or fix this issue.

Thanks

**Comment by ishakhsuvarov** [comment]
<p>The GitHub issue tracker is intended for technical issues only. Please refer to the <a href="https://community.magento.com" target="_blank">Community Forums</a> or <a href="http://magento.stackexchange.com/" target="_blank">Magento Stack Exchange</a> site for technical questions. In your case, the <a href="https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2" target="_blank">programming questions forum</a> is likely the most appropriate.</p>

**Comment by ahmadalkaid** [comment]
Hi @ishakhsuvarov,

I face the same issue, and when I try to look into the shipping extensions with the same Magento vender, we sow that these extensions are built to get the zip code not the city and the street fields. So could you please give it a look and come back to us?

Best.
