### ISSUE TITLE
Shipping step in checkout showsState/Province select box on initial page load even if configured not to do so

### ISSUE THREAD

**Issue by t-eichmann** [magento/magento2#29678]
### Preconditions (*)

1. Install a clean Magento 2.4 system with sample data

### Steps to reproduce (*)

1. In the backend, go to Stores -> Configuration -> General -> General, open the State Options and select one country, for example Afghanistan, in the "State is Required for" field
2. Set "Allow to Choose State if It is Optional for Country" to No, Save the settings
3. Put something in the cart and proceed to checkout until you come to the Shipping step

### Expected result (*)

1. For the default Country "USA" there should be no select box for "State/Province", since we just disabled showing it for that country

### Actual result (*)

1. The select box for "State/Province" is shown
2. Once you select a different country and then go back to the initial country the select box does not reappear, so this bug only appears on initial load of the page.
![Peek 2020-08-27 14-16](https://user-images.githubusercontent.com/51681379/91436060-0967cc00-e870-11ea-9cac-7ee57b8a94b8.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37116` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Surabhi-Cedcoss** [comment]
@magento i am working on this.

**Comment by Surabhi-Cedcoss** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by HenKun** [comment]
@t-eichmann did you find any solution for this issue?  It seems due to the fact that the region selector is rendered after the country selector, and hence, gets not updated initially with the set country.
