### ISSUE TITLE
Multi Source Inventory - Product not visible in the category and search with multi website and multi source

### ISSUE THREAD

**Issue by lokeshvnaik** [magento/magento2#29683]
**Preconditions (*)**
	

1. Magento 2.3.3
2. Multi website
- a) base website (Country: US)
- b) canada website (Country: Canada)
5. Root category same for both websites
6. Stores > Configuration > Catalog > Inventory > Stock Options > Set Display Out of Stock Products to No

**Steps to reproduce (*)**

1. Create a simple product which is mapped to both websites (us and canada) and assign them to a category for. eg. Bags
2. Under Stores > Inventory > Sources
- a) Create an inventory source for US website as (Name: US, Code: us)
- b) Create an inventory source for Canada website as (Name: Canada, Code: canada)
5. Under Stores > Inventory > Stocks
- a) Create an inventory stock as (Name: US, Sales Channel: US website, Sources: US created in step 2a)
- b) Create an inventory stock as (Name: Canada, Sales Channel: Canada website, Sources: Canada created in step 2b)
8. Now set different qty for the product created in step 1 for each source (US & Canada except default source)
9. Reindex, clear cache
10. Now open US website URL and check the category to which the product was assigned in Step 1 
11. Now open Canada website URL and check the category to which the product was assigned in Step 1

**Expected result (*)**

1. Product should show in both the websites in the assigned category or search page
2. Qty should get updated with website_id in cataloginventory_stock_item and cataloginventory_stock_status tables

**Actual result (*)**

1. Product is not visible in the category
2. Qty not getting updated with website_id in cataloginventory_stock_item and cataloginventory_stock_status. The website id in these tables is always 0. Therefore the product not visible in the category or search page
3. Product visible if you hit the product URL directly but not in category or search page

**Comment by engcom-Oscar** [comment]
Hello @lokeshvnaik  

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` Magento branch with MSI modules installed. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento installation and confirm?

Notice: MSI modules keep products qty and status in inventory_source_item table
