### ISSUE TITLE
Incorrect return type asset file

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#29696]
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Asset/File.php#L204

class Magento\Framework\View\Asset\File.php

Take a look at method getContext

current return value is File\Context but i think we should correct type return to ContextInterface

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
This problem still not resolve at my point of view

**Comment by engcom-Delta** [comment]
Hi @mrtuvn  thank you for your report. 
Do you have a case that leads to the issue with return value for function `getContext`?

**Comment by mrtuvn** [comment]
Maybe related with my reported issue here
https://github.com/magento/magento2/issues/27949
