### ISSUE TITLE
[2.3.5-p2] Total due is not updated when order is completed with canceled items

### ISSUE THREAD

**Issue by shahriar-vdc** [magento/magento2#29698]
### Preconditions (*)
1. Magento 2.3.5-p2
**Doesn`t reproducible on 2.4-develop**

### Steps to reproduce (*)
1. Place an order with items where the quantity is more than 1
2. Create an invoice & shipment for the order _partially_
3. Cancel the rest of the order items by canceling the order

### Expected result (*)
1. **Total due** should be 0 since the order status is 'complete'
2. **Grand total** and **other relevant fields** should also reflect the price difference

### Actual result (*)
1. **Total due** shows the remaining unpaid amount even though the order status is 'complete'
2. **Grand total** remains same

Please see the screenshot below:
![image](https://user-images.githubusercontent.com/59009669/90763459-07899000-e2e7-11ea-9ff2-919dc543d26c.png)

**Additional information** 
On 2.4-develop "Total due" was replaced to "Total Canceled"
![Screenshot_122](https://user-images.githubusercontent.com/51681379/91159992-86a90a80-e6d1-11ea-84d0-efb916756228.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36990` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amitvishvakarma** [comment]
@magento I am working on it.

**Comment by amitvishvakarma** [comment]
#dmcdindia2020

**Comment by engcom-Golf** [comment]
Hi @shahriar-vdc 
The latest Magento version as of now is 2.4.2 and moving forward we will be focusing on the 2.4 and 2.5 release lines. As a result of such an approach, we will be parking the delivery of bug fixes or features for the 2.3 line and only delivering security fixes to it.
More details on https://community.magento.com/t5/Magento-DevBlog/Let-s-Keep-the-Magento-2-Backlog-Clean-Part-2/ba-p/462599 
Thank you for report. I will close this issue.

**Comment by magento-engcom-team** [comment]
Hi @shahriar-vdc, @engcom-Golf. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-36990` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
