### ISSUE TITLE
When adding New Product Attribute

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#2969]
When adding New Product Attribute it will not save, Under Manage Options (values of your attribute) it always comes up "This is a required field" even though there is something there.
![new product attribute](https://cloud.githubusercontent.com/assets/16354206/12268852/9461d8f6-b91c-11e5-9a0e-6472b333a0b3.PNG)

**Comment by Deji69** [comment]
Also having this problem. Would be nice to see a response on the only fitting Google result...

**Comment by palamar** [comment]
@zamboni084
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by zamboni084** [comment]
Sorry I am no longer using magento 2
