### ISSUE TITLE
Submit search button in form-mini should be disabled until minimum search length is reached

### ISSUE THREAD

**Issue by markshust** [magento/magento2#29704]
### Preconditions (*)

1. Base install of Magento 2.4.0 with sample data installed.
2. The issue is prevalent on every operating system and browser.

### Steps to reproduce (*)
1. Focus on form-mini search box.
2. Type one or two alphanumeric characters in search box.

### Expected result (*)
- Submit button (magnifying glass) remains disabled until minimum search length is reached:
![Screen Shot 2020-08-20 at 2 34 09 PM-disabled](https://user-images.githubusercontent.com/437029/90811626-ed55af00-e2f2-11ea-94fb-709f686a243b.png)

### Actual result (*)
- Submit button (magnifying glass) becomes enabled even if minimum search length is not reached:
![Screen Shot 2020-08-20 at 2 34 09 PM](https://user-images.githubusercontent.com/437029/90811216-3bb67e00-e2f2-11ea-8922-9fc32526cdaf.png)

### Additional Info
Minimum search length is defined in the related component at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Search/view/frontend/web/js/form-mini.js#L33

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-29704-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29704-2-4-develop.instances.magento-community.engineering/admin_d0b2](https://i-29704-2-4-develop.instances.magento-community.engineering/admin_d0b2)
Login: `8cc91991` Password: `5246ac252660`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36904` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by sivaschenko** [comment]
Hi @markshust. Thank you for your report. 
The issue has been fixed in magento/magento2#29724 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [f230257dceda451d27031100441c675ee5fa48d5](https://github.com/magento/magento2/commit/f230257dceda451d27031100441c675ee5fa48d5)
 - [1973efbde04dbc5b3081755c071cbf9e6d707532](https://github.com/magento/magento2/commit/1973efbde04dbc5b3081755c071cbf9e6d707532)
 - [50b83bef10fa63a85ca8f82271f22d7887f57395](https://github.com/magento/magento2/commit/50b83bef10fa63a85ca8f82271f22d7887f57395)
 - [268277ee79b3f8ed5a10a9645671d416342c3dfe](https://github.com/magento/magento2/commit/268277ee79b3f8ed5a10a9645671d416342c3dfe)

The fix will be available with the upcoming 2.4.2 release.
