### ISSUE TITLE
Test content integration

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29702]
1. 1
1. 2
1. 3

<!---
Please review our guidelines before adding a new issue: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with (*) are required. Please don't remove the template.
--]

### Preconditions (*)
[!---
Provide the exact Magento version (example: 2.4.0) and any important information on the environment where bug is reproducible.
--]
1. # h3. Steps to reproduce (*)
[!---
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
--]
1. # h3. Expected result (*)
[!--- Tell us what do you expect to happen. --]
1. [Screenshots, logs or description]
1. h3. Actual result (*)
[!--- Tell us what happened instead. Include error messages and issues. --]
1. [Screenshots, logs or description>
1. h2. 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36888` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
