### ISSUE TITLE
Font format incorrect import in theme

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#29719]
### Preconditions:

Magento 2.4-develop

Default magento font import lib-font-face use type woff or woff2. In real case when user use another font type such as true type. Font import will work incorrect if add format truetype

Example in less define custom font

`.lib-font-face(
    @family-name: 'Inter-Light',
    @font-path: '@{baseDir}fonts/Inter-Light',
    @font-format: 'ttf',
    @font-weight: normal,
    @font-style: normal,
    @font-display: auto
);
`

will generate css font-face

`
@font-face {
    font-family: 'Inter-Light';
    src: url('../fonts/Inter-Light.ttf') format('ttf');
    font-weight: normal;
    font-style: normal;
    font-display: auto;
}
`
format font src seem incorrect in the case truetype. Reference in this doc

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

src: url('../fonts/Inter-Light.ttf') format('ttf') should be 

src: url('../fonts/Inter-Light.ttf') format('truetype');

### Steps to Reproduce:

1. Tested with font added with /web/css/source/_typography.less inside luma/blank theme or custom theme
2. Use custom font non-default from magento (ttf, eot)
3. use format specific while import font
4. Also use type font specific too
5. Make sure output css render and page load without problem. Font render correctly

**Actual Result:** :heavy_multiplication_x: 

Font not render properly
![font_before_change](https://user-images.githubusercontent.com/1908873/95092657-1a024080-0752-11eb-807a-385bae3bbd74.png)

styles-m.css render with font 
![Screenshot from 2020-10-05 21-26-58](https://user-images.githubusercontent.com/1908873/95092898-5897fb00-0752-11eb-9b4b-6ab59d9dd69f.png)

**Expected Result:** :heavy_check_mark: 

import
![font_after_import](https://user-images.githubusercontent.com/1908873/95094400-0fe14180-0754-11eb-9180-beb118b89ac9.png)
render styles-m.css
![font_render_after](https://user-images.githubusercontent.com/1908873/95094452-1ff92100-0754-11eb-9bcd-65b9eba4ecab.png)
web font request
![font_after_change](https://user-images.githubusercontent.com/1908873/95094490-2ab3b600-0754-11eb-86c9-949b93356861.png)
### Proposed solution

--- Update mixin font with new type font argument in order import correct type
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38231` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your report. 
The issue has been fixed in magento/magento2#29726 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [9e48f91c7f3e67b8d49195fd2f6a3b3e03bc7025](https://github.com/magento/magento2/commit/9e48f91c7f3e67b8d49195fd2f6a3b3e03bc7025)

The fix will be available with the upcoming 2.4.2 release.
