### ISSUE TITLE
[EE] Admin is not able log in as customer registered on restricted website when Share Customer Accounts=Global

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#29710]
### Preconditions (*)

1.Magento 2.4-develop
2.Login as Customer module related
3.Second website is created
![image](https://user-images.githubusercontent.com/51681379/90273765-28c22a80-de68-11ea-9599-bd1da0a12ebe.png)
4. Add Store Code to Urls=Yes
5. Customer is registered on additional website (e.g., `New Website`)
![image](https://user-images.githubusercontent.com/51681379/90881561-1473b580-e3b3-11ea-9012-2905c9ae6c14.png)

### Steps to reproduce (*)

1. Set Restriction Mode=Website Closed for additional website (e.g., `New Website`)
![image](https://user-images.githubusercontent.com/51681379/90886565-4b4dc980-e3bb-11ea-86bf-36a4186fa580.png)
2. Set Stores->Configuration->Customers->Customer Configuration->Account Sharing Options->Share Customer Accounts=Global
3. Set Stores->Configuration->Customers->Login as Customer->Store View To Login To=Auto Detection
3. Go to customer edit page 
4. Click Login as Customer
5. Click Login as Customer button in `You are about to Login as Customer` modal window

### Expected result (*)

1. Admin is login as customer on default website (e.g., `Main Website`)

### Actual result (*)

1. Admin is not logged in as customer 
2. Error message `Login as Customer cannot be logged in restricted website.` is shown
![image](https://user-images.githubusercontent.com/51681379/90886910-02e2db80-e3bc-11ea-9857-efa13cf17502.png)

Additional Information
Related PR https://github.com/magento/partners-magento2ee/pull/301
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @engcom-Delta 
Getting logged in as customer successfully to the default website without any issues, based on the given steps successfully.

**Comment by engcom-Alfa** [comment]
Since it is an internal reporter's ticket and being not reproducible, the issue is being closed!
