### ISSUE TITLE
Magento 2.4 | Cron job getting missed multiple times

### ISSUE THREAD

**Issue by rakeshsigma** [magento/magento2#29713]
### Preconditions (*)

1. Magento 2.4
2. PHP 7.4
3. Elasticsearch 7.8
4. Apache2

### Steps to reproduce (*)

Please review the attached screenshot.

After upgrading Magento with the latest version, we are facing this issue with cron. Cron getting missed multiple times. We have followed the below steps but still the same result.

Updated the cron timing.
Disabled third party extension crons.
Disabled the third-party extensions as well.
Updated server memory limit.
Please let us if anyone has faced the same issue before. Thanks in advance.

### Expected result (*)

1. Cron should work expected
2. The product should display properly in the list page.
3. The server is getting crushed 

### Actual result (*)

1. Cron getting missed and never-ending

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Cron issue._
![Screenshot from 2020-08-21 19-09-30](https://user-images.githubusercontent.com/19852287/90900026-6b46b280-e3e6-11ea-8aa9-21989ad021cd.png)

**Comment by hirensoni2005** [comment]
Do we have any update on this, as I am facing the same issue on M 2.4.1 too.

**Comment by ayoubelabassi** [comment]
is there any updates about this issue i'm facing the same problem

**Comment by angelflo** [comment]
same problem with last version 2.4.3 ...

**Comment by rudracomputech** [comment]
I am also getting same problem with version 2.4.3. Any body have solution ?

**Comment by magentoprasad** [comment]
2.4.4 V also have same issue of cron missing

**Comment by hemendrametawolf** [comment]
I am using 2.4.4-p1 still facing high cpu usages.
