### ISSUE TITLE
GraphQl products query returns missing items on using `category_id` filter with `in` array

### ISSUE THREAD

**Issue by MeeGz** [magento/magento2#29720]
### Preconditions (*)

1. creating 2 categories as subcategories of the root one (test1 and test2)
2. creating 2 products 1 for each created category (product1 for test1 and product2 for test2)

### Steps to reproduce (*)

1. using graphql client running this query
```
{
  products(filter: {category_id: {in: ["3","4"]}}) {
    total_count
    items {
      name
      categories {
        id
        name
      }
    }
  }
} 
```

### Expected result (*)

1. getting the `total_count` = 2
2. getting 2 products into `items` property

### Actual result (*)

1. getting correct `total_count` = 2
2. getting **_only 1 product_** of last value in `in` filter array (in this case `category_id` = 4)
<img width="1440" alt="Screen Shot 2020-08-23 at 12 29 30 PM" src="https://user-images.githubusercontent.com/15185278/90976369-b70b7000-e53c-11ea-9bfb-e7da13e4a97a.png">

without applying any filters
<img width="1440" alt="Screen Shot 2020-08-23 at 12 39 39 PM" src="https://user-images.githubusercontent.com/15185278/90976478-bf17df80-e53d-11ea-8f5f-3409ff5ad2d1.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by daniel-jarzebowski-accenture** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @daniel-jarzebowski-accenture. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @daniel-jarzebowski-accenture, here is your [Magento instance](https://i-29720-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29720-2-4-develop.instances.magento-community.engineering/admin_bd1e](https://i-29720-2-4-develop.instances.magento-community.engineering/admin_bd1e)
Login: `56ec47fe` Password: `09b5281d6a62`
Instance will be terminated in up to 3 hours.
