### ISSUE TITLE
Formulario de contacto Magento 1.9.4.2

### ISSUE THREAD

**Issue by lmn00005** [magento/magento2#29725]
Una vez relleno el formulario de contacto con los datos cuando le doy a enviar la página refresca pero no llega nada a mi correo.
El formulario es el que viene por defecto

**Comment by krishprakash** [comment]
Hi @lmn00005. GitHub issue Tracker is intended for magento 2 core technical issues only.
Kindly refer community forum Or Stack exchange for general discuss about this topic
Thanks!!
