### ISSUE TITLE
recently viewed not seen in version 2.3.5

### ISSUE THREAD

**Issue by kimpi33** [magento/magento2#29732]
After updating magento from to 2.3.5, keeping the widget settings, the widget disappears

### Preconditions (*)

1. Magento 2.3.x
2. Correct active widget in background

### Steps to reproduce (*)

1.Upgrade to Magento 2.3.5

### Expected result (*)

![image](https://user-images.githubusercontent.com/70173628/91095712-ccf75e80-e62a-11ea-9af8-9fd0b13f61c6.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/70173628/91095768-e13b5b80-e62a-11ea-8e07-023ec58e7945.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @kimpi33 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and 2.4.0 with sample data
**Manual testing scenario:**
- Go to Content->Widgets
- Click Add Widget
- Set Storefront Properties
![image](https://user-images.githubusercontent.com/51681379/92096485-9d411700-eddf-11ea-9e6e-cd13082e6a2a.png)
- Set Widget Options
![image](https://user-images.githubusercontent.com/51681379/92096524-aaf69c80-eddf-11ea-85a1-c48c37016f26.png)
- Save widget
- Go to storefront and view products as registered customer


**Result:**
- 2.4-develop - widget is corectly displayed
![image](https://user-images.githubusercontent.com/51681379/92096172-3f143400-eddf-11ea-8dc5-21f89a6ecc3e.png)

- 2.4.0 - widget is corectly displayed
![image](https://user-images.githubusercontent.com/51681379/92096047-1ee47500-eddf-11ea-90ed-e81adc665c5b.png)

If you'd like to update  the issue, please reopen it.
