### ISSUE TITLE
Missing support for security feature "integrity" | Element 'css', attribute 'integrity': The attribute 'integrity' is not allowed.

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29737]
### Preconditions (*)

1. Enterprise 2.4.0

### Steps to reproduce (*)

1. Create a theme
2. Add file THEME\Magento_Theme\layout\default_head_blocks.xml with following content:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <css src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
             src_type="url"
             integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
             crossorigin="anonymous"
        />

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
                src_type="url"
                integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
                crossorigin="anonymous"
        ></script>

        <css src="https://use.fontawesome.com/releases/v5.14.0/css/all.css" src_type="url" />
        <css src="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;800&amp;display=swap" src_type="url" />
    </head>
</page>
```
3. Clear cache
4. Reload frontend.

### Expected result (*)

1. Frontend should load

### Actual result (*)

1. Element 'css', attribute 'integrity': The attribute 'integrity' is not allowed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
This is still relevant.

**Comment by hostep** [comment]
Looks like it's coming in: https://github.com/magento/magento2/pull/32455#issuecomment-800728650

**Comment by Eddcapone** [comment]
I still get the error on Magento 2.4.2 on scripts for example:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	<head>
		<!--Remove default jquery, or it will cause conflict-->
		<remove src="lib\web\jquery.js"/>
		<!--Include CDN-->
		<script
			  src="https://code.jquery.com/jquery-3.2.1.min.js"
			  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			  crossorigin="anonymous" src_type="url"></script>
	</head>
</page>
```
