### ISSUE TITLE
Magento2 Admin is not working

### ISSUE THREAD

**Issue by ranaraj1983** [magento/magento2#2973]
Hi, I have installed Magento2 successfully in my laptop, windows-7 xampp, I can login to admin but only dashboard is working none of other option are working. and I can see one warning in top of the admin page but I can not see the message,. Could you please help me to troubleshoot what is the issue.

![capture](https://cloud.githubusercontent.com/assets/1684280/12273636/077d48f0-b98d-11e5-9a5a-e75df205fd77.JPG)

**Comment by gigadesign1** [comment]
Try running bin/magento setup:static-content:deploy

You seem to be missing Javascript files. I had the same problem earlier.

**Comment by ranaraj1983** [comment]
Hi Mark,

THanks for you reply, It works.

Thanks,
/Rana

On Wed, Jan 13, 2016 at 12:55 AM, Mark van der Werf <
notifications@github.com> wrote:

> Try running bin/magento setup:static-content:deploy
> 
> You seem to be missing Javascript files. I had the same problem earlier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/2973#issuecomment-171023993.

## 

## Regards,

/Rana Das
