### ISSUE TITLE
Add product to wishlit without registering gives error 404 Page not found

### ISSUE THREAD

**Issue by chdzma** [magento/magento2#29731]
Adding a product to the wishlist without being registered gives error 404 after confirming account.

### Preconditions (*)

1. Magento version: 2.3.5
2. Nginx
3. Php 7.2

### Steps to reproduce (*)

1. Enable account parameter "Require Emails Confirmation"
2. Without being logged in, add a product to the wishlist. This will redirect you to account creation.
3. Create an account and confirm email.

### Expected result (*)

1. Finish adding product to wishlist

### Actual result (*)

1. Error: 404 Page not found

![image](https://user-images.githubusercontent.com/24399312/91092007-b0bde680-e657-11ea-9f51-6b66214dff01.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hello @chdzma 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.
If you have some more details how to reproduce this issue on latest 2.4 Magento, feel free to update the description and reopen it.

**Comment by samvens** [comment]
@chdzma what was the issue behind wishlist 404 page? I'm facing exactly same issue. I spent so much time but couldn't find the solution. Please let me know if you can give me some advice.

Thank you!
