### ISSUE TITLE
After enable staging feature, how load sales rule by rule id

### ISSUE THREAD

**Issue by xiangkundavis** [magento/magento2#29749]
### Preconditions (*)
1.  Mgaento EE 2.3.5p1

### Steps to reproduce (*)
1.  Create a new cart price rule and the status is "disable". This rule id is **37**
2.  Click "Schedule New Update" to add a new schedule and enable this cart price rule
3. Go to table salesrule, there will be 3 more records which rule_id is **37**
4. Use the code below to load the sales rule which rule id is 37
<<<
        $ruleId = 37;
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $rule = $objectManager->create('Magento\SalesRule\Model\Rule')->load($ruleId);

>>>

### Expected result (*)
Should load the rule which status is "enable"

### Actual result (*)
Load the sales rule which status is "disable"

It seems only load the first record from table salesrule which rule id is 37

**Comment by shikhamis11** [comment]
hi @davissuperman for `salesrule` table`rule_id` doesn't seems to be the `primary_key` so the you need to check for the `primary key` for the table  which is `row_id` 
also github is intended for bugs in core functionalities for discussion and development related issues you can refer [Magento Stack Exchange](https://magento.stackexchange.com) & [Magento Community Forum](https://community.magento.com/)
