### ISSUE TITLE
Add fields on Widgets for adding extra css classes/styling.

### ISSUE THREAD

**Issue by LiamTrioTech** [magento/magento2#29744]
### Summary (*)
Unable to select widget's static block element to style it with CSS.

### Examples (*)
```html
<div class="widget block block-static-block">Content here...</div>
```

Then the static block contents of the widget could be styled with CSS.

### Proposed solution
Similar to the example given here, extending cms/widget_block template to add getBlockId() into css class names,, but as a field for class names in the admin widget edit form.
https://magento.stackexchange.com/questions/75374/adding-block-and-creating-unique-class-id

An input box such as
Additional CSS Class Names: 'some-class'

```html
<div class="widget block block-static-block some-class">Content here...</div>
```

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

Magento 2.3.0

**Comment by LiamTrioTech** [comment]
Reopen please.

**Comment by amcguireweb** [comment]
I don't get how this isn't already a thing. Makes no sense.
