### ISSUE TITLE
Can't change load order of scripts / css files

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29741]
I've added bootstrap 4 to magento 2. But bootstrap is overriding basic CSS of magento 2, e.g. it changes the font-size in body to 1rem and so on.

We could easily solve it, by loading bootstrap 4 before styles-l.css and styles-m.css. So I tried the new `order` attribute and setting it to 0, but it is still getting loaded after style-m.css and style-l.css

https://github.com/magento/magento2/issues/1821

### Preconditions (*)

1. Enterprise 2.3.5-p2

### Steps to reproduce (*)

1. Create Theme
2. Create file **THEME/Magento_Theme/layout/default_head_blocks.xml**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

        <css src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" src_type="url" order="0"/>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" src_type="url" order="1"></script>

        <css src="https://use.fontawesome.com/releases/v5.14.0/css/all.css" src_type="url" />
        <css src="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;800&amp;display=swap" src_type="url" />
    </head>
</page>
```
3. Clear cache
4. Reload Frontend
5. Inspect source code

### Expected result (*)

1. Bootstrap should get loaded before style-l.css and style-m.css

### Actual result (*)

1. Bootstrap gets loaded after style-l.css and style-m.css

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
I was able to make a temporary [workaround](https://magento.stackexchange.com/a/320730/66769).

**Comment by mrtuvn** [comment]
do you try add bootstrap like this in link below
https://gist.github.com/mrtuvn/34ae6f5bce175872e72520c29bcc3b03

magento current not work order in css tag in xml. Move bootstrap styles before base styles magento

in my opinion i don't like bootstrap include in . Some feature you can write your own in case you need (grids, col system, gap..). All the rest feature magento support already (flexbox full support)

**Comment by Eddcapone** [comment]
I already tried the code from your first link. But it does not solve the problem. Bootstrap still gets loaded after style-m and style-l

**Comment by mrtuvn** [comment]
Yeah tried again but not work! I'm not sure why order attribute not work when magento allow its via xml but current this is all we have. In the end you can't order css load

**Comment by Eddcapone** [comment]
This is still relevant.

**Comment by mrtuvn** [comment]
Have you try add CSS via layout in custom module ? See my previous reply

**Comment by kirill533** [comment]
Workaround: 

1. Rename bootstrap.css into bootstrap.less.
2. Includ bootstrap.less as a regular less file as part of the theme at the start of the _sources.less file.
