### ISSUE TITLE
[Urgent] All Products and design gone on front end Magento 

### ISSUE THREAD

**Issue by magentodev1** [magento/magento2#29745]
Some may know but there is a thing called "Yotpo" it basically puts a review widget or something of some sort on each product. it came preinstalled with my Porto template. I made a copy of the yotpo file and put it on my local directory. then edited the copy and put it back into the yotpo file and my website now no longer shows any product.

### Preconditions (*)

1. Magento 2
2. Core ftp
3. Porto Template 
### Steps to reproduce (*)

1. I wanted to remove yotpo services so I went to the core ftp and from there public_html>vendor>yotpo
2. Now I copied the original file for backup and basically edited and put it back but it didnt so anything so I deleted the copy I put back in and let it be so it was as when I first saw the yotpo file. So its the original 

### Expected result (*)

1. I expected the website to go back to normal as if I had edited nothing.

### Actual result (*)

1. When I went back to my website it showed no products and design is gone. Only said this on the homepage "We're sorry, an error has occurred while generating this content." 
![Capture1](https://user-images.githubusercontent.com/70251320/91256040-4c248980-e734-11ea-9bf3-407c3ff7e765.PNG)

2. when i checked the admin panel it showed this 
![Capture](https://user-images.githubusercontent.com/70251320/91255886-eb954c80-e733-11ea-8c76-da1c236650bd.PNG)

3. Now I am stuck here not sure what to do, Ik I am  a newbie at this and shouldn't have touched a file without knowing what I am doing  

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Check log so you can reveal some caused problem. In case you want to remove yotpo update composer with this below to removes optional modules
https://github.com/yireo/magento2-replace-bundled

**Comment by mrtuvn** [comment]
"We're sorry, an error has occurred while generating this content." is meaning something went wrong . Take a look at folder var/log in root magento folder

**Comment by magentodev1** [comment]
Alright guys, I solved my problem simply by manually running the cron jobs and re indexing. Although I was not able to delete the The extremely headache of a module more as a virus "Yotpo" I am just glad the website is working. I'll look into the links provided and see what I can do with Yotpo. Really held me far back from putting the website into production
