### ISSUE TITLE
exported CSV permissions fix

### ISSUE THREAD

**Issue by elbasri** [magento/magento2#29759]
Hi
i have a magento 2 installation using version 2.3.5-p

### Expected result (*)

download exported files using magento admin

### Actual result (*)
when export products (for example) from system=>data transfer=>export
all is going well, the export message added to the cron, and the exported csv is saved to magento_install_dir/var/export
but its saved under permissions 0644 
bu result, i cant download the file using magento admin (runing by www-data apache user).

how to slove this?

**Comment by engcom-Delta** [comment]
Hi @elbasri thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and on 2.3.5-p2
![Peek 2020-08-31 16-36](https://user-images.githubusercontent.com/51681379/91726088-57e6d480-eba8-11ea-8eb0-71fe02df1654.gif)

Please take a look for [File systems access permissions](https://devdocs.magento.com/guides/v2.4/config-guide/prod/prod_file-sys-perms.html)

If you'd like to update the issue, please reopen.

**Comment by elbasri** [comment]
> 
> 
> Hi @elbasri thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and on 2.3.5-p2
> ![Peek 2020-08-31 16-36](https://user-images.githubusercontent.com/51681379/91726088-57e6d480-eba8-11ea-8eb0-71fe02df1654.gif)
> 
> Please take a look for [File systems access permissions](https://devdocs.magento.com/guides/v2.4/config-guide/prod/prod_file-sys-perms.html)
> 
> If you'd like to update the issue, please reopen.

Thank you for reply,
the problem is that magento cron save exported file with permissions 0644 (even if the export folder have 0777 permissions), is there any ressources about this?

**Comment by moni921** [comment]
Any solution to this. I am also facing same issue

**Comment by pramodjadhav1419** [comment]
Any Solution for this issue because i am still facing this issue. The csv generated inside var/export is generated with root owner.
