### ISSUE TITLE
Magento is removing custom attributes for meta tags

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#2975]
Hello, I have just found that Magento is filterring some attributes for meta tags.

For example, I need to put this:

<meta name="fb-image" property="og:image" content="http://www.vtrack.cl/pub/media/social/gps303g_fb.png" />

I have added it in vendor/magento/theme-frontend-luma/Magento_Theme/layout/default_head_blocks.xml

And when loaded the web page, the property attribute is removed from the meta tag.

Where do I need to modify to solve it?

**Comment by zanilee** [comment]
Hi, @jaimestuardo!

Thank you for reporting this issue. Internal ticket MAGETWO-48402

**Comment by shiftedreality** [comment]
Fix was merged. Closed.
