### ISSUE TITLE
Magento 2.2.7 Issue

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#29766]
### Preconditions (*)

1. Magento 2.2.7
2. LFD emails

### Steps to reproduce (*)

1.Not Sure

### Expected result (*)

1. Just all of the sudden i started receiving these email from server 

Time:         Thu Aug 27 05:00:38 2020 +0200
Account:     (Example Domain Name)
Resource:     Process Time
Exceeded:     155197 > 1800 (seconds)
Executable:   /usr/local/cpanel/bin/jailshell
Command Line: jailshell (Domain name) [init] ell -c PATH=.:/usr/local/bin:/usr/bin; export PATH; cd /home/Domain/public_html/pub/media;  php-fpm: pool www  2>&1  1>/dev/null &  # ROSELOVER
PID:          2925 (Parent PID:2915)
Killed:       No

### Actual result (*)

1. Everything was working fine this just started happening all of sudden
2. Contacted VPS support and was told its something to with cron job but all the cron jobs are working fine
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [**S0** ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround.

**Comment by krishprakash** [comment]
Hi @terrybakshi. Kindly contact your server team to review into this
This is not any default magento problem so closing this as non issue
Also you can raise this at [mangento stack exchange](https://magento.stackexchange.com/) Or [community forum](https://community.magento.com/) to help further
