### ISSUE TITLE
Store View should be replace to Store

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#29760]
### Preconditions (*)

1. Magento 2.4.1
2. Login as Customer module related

### Steps to reproduce (*)

1. According https://github.com/magento/magento2/issues/29101
2.

### Expected result (*)

1. `Store View` should be replace to `Store`

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/51681379/91323836-05816e80-e7ca-11ea-95c6-40a6c7730434.png)
2. 
![image](https://user-images.githubusercontent.com/51681379/91323941-26e25a80-e7ca-11ea-8906-1e11bd876b29.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rakhi98** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40276` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by artskirk** [comment]
Issue already fixed on 2.4-develop

![image](https://user-images.githubusercontent.com/57759456/179190406-b0a4a678-ae92-40ee-aba4-1198241bffb3.png)
