### ISSUE TITLE
Tax handling on credit notes still faulty in Magento 2 

### ISSUE THREAD

**Issue by Overlap88** [magento/magento2#29765]
Summary of the issue - Magento Tax handling when you add an adjustment fee is incorrect
    Information on your environment - Magento 2.3.4 (but was like this on 1.9)
    Steps to reproduce - issue a credit on any invoice and add adjustment fee to reproduce
    Expected and actual results - VAT total should change to reflect the credit but it doesn't 

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

Magento ver. 2.3.4

Hi 
this bug was reported many years ago, and I assumed it would be fixed in Magento2 having put up with it in Magento 1.
It is simply the tax handling when making a credit. 
e.g

Customer buys a product that costs  Excl. VAT: £307.49
Incl. VAT: £368.99 
VAT Amount is £61.50

If they return the product and you charge 20% restocking fee they get back £295.19. inc vat. Net amount £245.99. The VAT element of the refunded amount is £49.20

Now for what happens if you do this on Magento 1 and 2 

Subtotal (Excl.Tax) | £307.49
Subtotal (Incl.Tax) | £368.99
Adjustment Refund | £0.00
Adjustment Fee | £73.79 (20% handling fee)
Grand Total (Excl.Tax) | £233.70
Tax | £61.50
Grand Total (Incl.Tax) | £295.20

The tax figure is incorrect - if you charged a 20% handling fee on £368.99 you would deduct £73.79 in total. This includes 20% VAT - the net amount is therefore £61.49 and VAT makes up £12.30
Therefore the overall VAT should be reduced. As you can see above the VAT has stayed at £61.50.

What Magento should be doing is asking for an Adjustment refund before VAT and then accounting for the VAT correctly.

Hope this helps!
thanks
Julian

**Comment by Overlap88** [comment]
not sure what else to add - I edited the original post to add the required information.

**Comment by engcom-Oscar** [comment]
dublicate https://github.com/magento/magento2/issues/23938

**Comment by Overlap88** [comment]
sorry to be a dumbass - but does this mean it's going to be fixed? thanks. Julian
