### ISSUE TITLE
Full Page Cache is active when Authorization header is send, but Authorization Bearer is never used

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#29775]
### Problem short description
Full page cache is expected to be ignored for any GET graphQl cacheable requests that do send Authorization header.
But, this is not the case. GET graphQl requests are still cached leading to sending wrong data when customer group dependent data is expected.

### Problem long description
When GET requests are made on cacheable queries, such as "categories, products, categoryList" for example, the Authorization Bearer serves no purpose - is NOT considered at all.

This pulls a consequence that if 
- One makes two consecutive GET requests one after the other with the same payload, but using different Authorization Tokens for each request, one will always get the same results.

There are situations where different Authorization Tokens should yield different results for the same query. 

An example is when the two different users that are represented by different tokens, may be allowed different catalog permissions, as in EE Catalog permissions feature, or B2B shared catalogs, or, in general any functionality that should distinguish results on a customer group level, like tier prices.

Another angle of the same problem is that a query can be cached for a not logged in group, and then no matter for which customer one wants results (represented by its authorization token and targeting specific customer group), one would see what a not logged in user sees. 

### Preconditions (*)

1. Have FPC enabled
2. Have two customers: A and B. 
3. They are assigned to two different customer groups, named "Group A" and "Group B". 
4. Have the catalog set that it has

- "Category A" that allows "Browsing Category" for "Group A", denies for all other groups
- "Category B" that allows "Browsing Category" for "Group B", denies for all other groups

This scenario can be set for EE, or, B2B - using shared catalogs for example.

### Steps to reproduce (*)

1. Make a GET request using Authorization bearer that has been generated for Customer A.
`categories: categories(filters: {name: {match: "Category"}}){items{id name}}`
2. You should get in response "Category A"
3. Change the Authorization bearer to one that has been generated for Customer B.
4. Run the same GET request
5. You should get in response the "Category B", but you still see "Category A"

### Expected result (*)

1. The categories that customer B is allowed to browse are visible
2.

### Actual result (*)

1. The categories that customer A is allowed to browse are visible

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cpartica** [comment]
this behavior is intentional and documented in devdocs

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project PWA as Story

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by cpartica** [comment]
in 2.4.1 we actually don't cache anything that has Authorization Bearer in the headers. so this issue is a problem prior to 2.4.1
We will have to cache customer queries in the future and take into account Authorization Bearer. but for now this issue is not a problem in the current version at the time of me writing this comment meaning 2.4.2
