### ISSUE TITLE
Customizable Options throw undefined offset error upon updating the Type.

### ISSUE THREAD

**Issue by Mathanagopal97** [magento/magento2#29788]
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Create a Simple product and assign categories.
2. Add two custom options of type Radio Button and add values (Minimum of two values).
3. Save the product.
4. View the product in the front end.
5. Make sure that the product has stock and status is In-stock.
6. Got to the product edit page.
7. Without deleting the custom options, change the type of one option from radio button to file.
8. Save the product and view it in the front end

### Expected result (*)
1.Product View page should be visible.

### Actual result (*)
1. Undefined offset Error.

---

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Mathanagopal97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Mathanagopal97, here is your [Magento instance](https://i-29788-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29788-2-4-develop.instances.magento-community.engineering/admin_730f](https://i-29788-2-4-develop.instances.magento-community.engineering/admin_730f)
Login: `32cce500` Password: `c64f16ca8b8e`
Instance will be terminated in up to 3 hours.

**Comment by Mathanagopal97** [comment]
Issue is not reproduced. I am closing this issue.
