### ISSUE TITLE
Unable to unassign product from a category [Visual Merchandiser]

### ISSUE THREAD

**Issue by hkvega01** [magento/magento2#29787]
### Preconditions (*)

1. magento 2.4 commerce edition

### Steps to reproduce (*)

1. assign a product into a category
2. click unassign in category tab to unassign product

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/4374758/91520900-11377700-e929-11ea-9d97-cbf5068702d6.png)
click unassign

### Actual result (*)

1. refresh the page, the product is still exist in the category

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29787-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29787-2-4-develop.instances.magento-community.engineering/admin_1837](https://i-29787-2-4-develop.instances.magento-community.engineering/admin_1837)
Login: `ffcbaa98` Password: `fae1e38c08be`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @hkvega01,
Verified this issue in the latest Magento 2.4 Instance in the below steps:
1. Admin > Catalog > Categories
2. Create a new category and Assign the product then click on Save button
3. The product is assigned properly.
4. Again Reassign the product and click on save button.
5. Product is removed on the selected categories.

Working fine in the Magento 2.4 Instance.
@hkvega01 - If anything is missing from my end please let me know.

Thanks.

**Comment by ajijshekh123** [comment]
Hi @hkvega01,
If you reproduced this issue. Please add proper steps or attached videos so I will reproduce this issue and confirm it.

Thanks
