### ISSUE TITLE
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#2979]
please Help me 
![error](https://cloud.githubusercontent.com/assets/16436069/12284906/4427feec-b9da-11e5-8b78-2baf3a049535.png)

**Comment by mitulispace** [comment]
my local  to live  trasfer then this Error Show How  to solve

**Comment by marvincaspar** [comment]
Check the configuration in `app/etv/env.php`.

And this looks like magento 1 not magento 2

**Comment by alankent** [comment]
I suggest you visit the Magento forums and ask for help there. It is not a Magento 2 issue, so not relevant to this ticketing system. (And if you want a random guess, make sure you don't use "localhost" as the host name for the socket connection to MySQL. MySQL is hard coded to look for that string and not use network in that case (as an optimization). Try 127.0.0.1 to force a network connection. Your server might not be listening on the named pipe the client code is trying to use).
