### ISSUE TITLE
Invalid form key when try to login or add to cart from any page

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#29791]
### Summary (*)

I am trying to log in as customer account with details, it showing invalid form key, please refresh the page. I tried a couple of times but facing the same issue.
### Examples (*)

check form key is visible on-page.
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendraajmera** [comment]
I am using 2.3.5-p1 version

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @hemendraajmera thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Customer is successfully logged in, no errors are shown
![Peek 2020-12-23 10-40](https://user-images.githubusercontent.com/51681379/102977302-78e28500-450b-11eb-95ad-2a2544085c90.gif)


If you'd like to update the issue, please reopen it.
