### ISSUE TITLE
No payment methods in checkout, although have 3 methods enabled. Magento 2.3.5-p2

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#29802]
### Preconditions (*)

1. Magento 2.3.5-p2 (Upgraded from 2.3.0)
2. PHP 7.2.33
3. CentOS 7 x64
4. Apache 2.4.6

### Steps to reproduce (*)

1. Enable payment methods: Bank Transfer and Cash On Delivery. We also have MobilPay module installed, for credit cards. Payment methods are configured for ALL countries.
2. Add product to cart
3. Go to checkout
4. No payment methods displayed

### Expected result (*)

1. Payment methods to be displayed, all three
2. Reproduced problem with default Magento Checkout as well as MagePlaza Onestepcheckout module

### Actual result (*)

1. [checkout actual result](https://user-images.githubusercontent.com/6533394/91621027-a7868f80-e95f-11ea-8116-6685bfcb3e42.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xtremevision** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @xtremevision. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @xtremevision, here is your [Magento instance](https://i-29802-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29802-2-4-develop.instances.magento-community.engineering/admin_a4a7](https://i-29802-2-4-develop.instances.magento-community.engineering/admin_a4a7)
Login: `76fb1b69` Password: `b8f87cfc6237`
Instance will be terminated in up to 3 hours.

**Comment by xtremevision** [comment]
Placed order successfully on vanilla instance 2.4.

**Comment by shikhamis11** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-29802-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29802-2-3-5-p2.instances.magento-community.engineering/admin_7892](https://i-29802-2-3-5-p2.instances.magento-community.engineering/admin_7892)
Login: `05f24093` Password: `32bdaaf5abc1`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @xtremevision 
I checked the mentioned issue at 2.3.5-p2 instance , the issue is not reproducible there .
![image](https://user-images.githubusercontent.com/25526037/91638984-f7815700-ea30-11ea-8087-10637da8db2a.png)

 It seems it is on your instance may be due to some customisation or 3rd party module .
