### ISSUE TITLE
Elasticsearch//No Alive Nodes Found In Your cluster // Magento 2.4.0  New Error 

### ISSUE THREAD

**Issue by bdevi** [magento/magento2#29801]
![2020-08-28 (2)](https://user-images.githubusercontent.com/66864122/91587223-179f1080-e974-11ea-8b35-385a062f403b.png)

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by bdevi** [comment]
i Have Upgrated to magento 2.4.0 but there is a problem in admin dashboard eLasticsearch has not working on cofiger it shows this massage
![2020-08-29 (2)](https://user-images.githubusercontent.com/66864122/91628034-8bbfcf80-e9d9-11ea-811b-d89ae4e059a6.png)

**Comment by mrtuvn** [comment]
seem related with same problem https://github.com/magento/magento2/issues/29462
Make sure you setup properly elastic search
In your case maybe magento can't connect or see elastic service

**Comment by bdevi** [comment]
hiii,
MRTUVN
ELASTICSEARCH SETUP IS PRE INSTALL AND CONFIGERED IN MY CASE 
I USE CPANEL FOR INSTALLTION  MAGENTO 2.4.0 BUT IT SHOWS THAT I HAVE NO NODES  AVAILABLE IN MY CLUSTER, WHAT IS THIS **CLUSTER**  ISS
PLEASE HELP IF YOU CAN.....
THANKS

**Comment by mrtuvn** [comment]
https://devdocs.magento.com/guides/v2.4/config-guide/elasticsearch/es-overview.html
 Have u check this ? Almost case come from misconfigured . Try ping or cluster health check with corresponding your ser er type

**Comment by bdevi** [comment]
SORRY I CANT UNDERSTAND **Try ping or cluster health check elastic with corresponding your server type** 
I THINK I HAVE TO MAKE NODES IN MY CLUSTER  BUT HOW ?

**Comment by krish-vivek** [comment]
Problem in your elasticsearch configuration 'elasticsearch.yml' file,

First You have to run below command to check your elasticsearch running in your system,
**curl localhost:9200**
if above command gives result like below string
{
  "name" : "XXXX-PC",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "aK3eUvikR9O2kke16TZiDw",
  "version" : {
    "number" : "7.9.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "a479a2a7fce0389512d6a9361301708b92dff667",
    "build_date" : "2020-08-11T21:36:48.204330Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

this means elasticsearch is successfully running in your system.

and if it gives error then go to " etc > elasticsearch > elasticsearch.yml" file and uncomment/change require configuration.
more information you can find in below link.

https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

**Comment by bdevi** [comment]
> Problem in your elasticsearch configuration 'elasticsearch.yml' file,
> 
> First You have to run below command to check your elasticsearch running in your system,
> **curl localhost:9200**
> if above command gives result like below string
> {
> "name" : "XXXX-PC",
> "cluster_name" : "elasticsearch",
> "cluster_uuid" : "aK3eUvikR9O2kke16TZiDw",
> "version" : {
> "number" : "7.9.0",
> "build_flavor" : "default",
> "build_type" : "deb",
> "build_hash" : "a479a2a7fce0389512d6a9361301708b92dff667",
> "build_date" : "2020-08-11T21:36:48.204330Z",
> "build_snapshot" : false,
> "lucene_version" : "8.6.0",
> "minimum_wire_compatibility_version" : "6.8.0",
> "minimum_index_compatibility_version" : "6.0.0-beta1"
> },
> "tagline" : "You Know, for Search"
> }
> 
> this means elasticsearch is successfully running in your system.
> 
> and if it gives error then go to " etc > elasticsearch > elasticsearch.yml" file and uncomment/change require configuration.
> more information you can find in below link.
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

Thanks Will Inform you further

**Comment by Pavel-Fekete** [comment]
Hello @bdevi 
Elasticsearch configuration solved your problem ?

**Comment by bdevi** [comment]
Sorry not solved yet

**Comment by mrtuvn** [comment]
From my experience this issue may not related to magento. 
Maybe causes wrong configuration from user
@bdevi are you sure following setup guides ?
If you not familiars with elasticsearch you should ask for help by system admin or web hosting provider
Properly setup elasticsearch may got response from port 9200. If you can't get response from that it's mean something go wrong

**Comment by suryadevsearce** [comment]
Hello, I have installed magento and Elasticseach in two different servers, the communication is up on port 9200 i.e able to ping and telnet. the elasticsearch service is up and running as well, but when I go to the magento admin console and update the elasticsearch host to the elasticsearch server's IP, I still get the `no nodes alive` error. Please help.

**Comment by kartikasodariya17** [comment]
Hello @suryadevsearce 
I have found the solution and you will get the success after apply this process.

edit config/elasticsearch.yml
Pls, change the network.host: 0.0.0.0
After changing the config pls restart the apps
Don't forget to uncomment network host

Enjoy!

**Comment by bdevi** [comment]
Uncommont host mean sir

**Comment by kartikasodariya17** [comment]
By default network.host: line is comment with # just remove it. Hope you understand.

**Comment by engcom-November** [comment]
Hi @bdevi,
We are closing this issue as this is not a Magento bug.
FYI.. Please refer to the [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) for specific version upgrades/installations if you are still facing issues.
Thank you.
