### ISSUE TITLE
Magento 2.3.3 View Order not working after PayU integration.

### ISSUE THREAD

**Issue by nbhat705** [magento/magento2#29813]
Not able to open any orders post payu integration
     - Magento 2.3.3, Linux server (cloud)
     - Integrate payu (via composer or command line or using web wizard)
     - Go to Sales>Order(s)>View the particular  order records should be opened in view mode.
     

### Preconditions (*)
 
1. Magento 2.3.3
2. Php 7.2

### Steps to reproduce (*)
 
1. Download the PayuIndia plugin for magenton 2.3.3 (this was given directly by the payu support team)
2. Install via composer/command line/web wizard etc. (end the result  remained  same.)
3. Admin Dashboard>Stores>Configuration>Sales>Payment Methods> enable payu gateway
4. Add products to cart, checkout using payu payment gateway
5. Go to Admin Dashboard>Sales>Order click on any order

### Expected result (*)
 
1. The order details/view page should appear.

### Actual result (*)
 
   Fatal error: Uncaught Error: Class 'PayUIndia\Payu\Block\Adminhtml\Order\View\Tab\Verify' not found in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116 Stack trace: #0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('PayUIndia\\Payu\\...', Array) #1 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('PayUIndia\\Payu\\...', Array) #2 /var/www/html/vendor/magento/framework/View/Element/BlockFactory.php(46): Magento\Framework\ObjectManager\ObjectManager->create('PayUIndia\\Payu\\...', Array) #3 /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php(268): Magento\Framework\View\Element\BlockFactory->createBlock('PayUIndia\\Payu\\...', Array) #4 /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php(248): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('PayUIndia\ in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instanc

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-29813-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29813-2-4-develop.instances.magento-community.engineering/admin_6634](https://i-29813-2-4-develop.instances.magento-community.engineering/admin_6634)
Login: `58f52827` Password: `902403b86d5f`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @nbhat705 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop seems like this related to your custom modules.
Please refer to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
