### ISSUE TITLE
Magento CE 2.3.4 Same cron jobs scheduled in bunch of 20 - 30. 

### ISSUE THREAD

**Issue by anuprasadkummali** [magento/magento2#29810]
Magento CE 2.3.4 Same cron jobs scheduled in bunch of 20 - 30. Causing a swarm of cron jobs in the server most going to pending state. Causing high CPU issue on server through php-fpm process.

This is my new production server, noticed after debugging high CPU issue.
### Preconditions (*)

1. Install Magento 2.3.4 CE
2.Check the corn_scheduler table

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. The same cron jobs should not be duplicated to run 10 -20 times in a bunch.

### Actual result (*)

1.
![image](https://user-images.githubusercontent.com/41773949/91642500-71bdd580-ea49-11ea-81fb-e7b9a3bd63f2.png)

See the scheduler ID , astronomical.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment]
This is the correct and expected behaviour. See Store->Configuration->Advanced->System->Cron (Scheduled Tasks) to define/configure how far ahead items are scheduled.
