### ISSUE TITLE
Problem with Klaviyo integration

### ISSUE THREAD

**Issue by IvanCyber** [magento/magento2#29818]
Hi all,

I tried to add Klaviyo integration in Magento ver. 2.3.5.
Once I accessed System -> Web Setup Wizard and accessed Extension Manager, I got the following infinite loop:
https://gyazo.com/c5948ac30991a432aff3efbb069db7be

I need this for setting up coupons that I will use in Klaviyo works - related to my Magento store. I was following this help article: https://help.klaviyo.com/hc/en-us/articles/115005254348-Integrate-with-Magento-2-x-CE-and-EE-

Can someone give a hand on this?

**Comment by IvanCyber** [comment]
Hi all,

I cannot provide more details, since I am not the owner of the Magento account and the marketplace as well. Can that be the cause of my issue?

Thank you.

**Comment by andrewbess** [comment]
Hello @IvanCyber 
Could you provide information from browser dev tools, please?

Thank you in advance.

**Comment by IvanCyber** [comment]
Sure @andrewbess 
please check this screen. Can you please advice on this issue? https://gyazo.com/68457788e12fac4466a49d65e407ce0b

Thank YOU in advance :)

**Comment by engcom-Delta** [comment]
Hi @IvanCyber Issue is not reproducible on 2.4-develop. According [docs](https://docs.magento.com/user-guide/system/tools.html) the Web Setup Wizard was removed:
> Starting with Magento 2.4.0, the Web Setup Wizard is removed, and you must use the command line to install or upgrade Magento, as well as modules and extensions.
