### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by tommoholmes** [magento/magento2#2983]
Hai I want to install magento2 but  when I running I get blank page
http://i.imgur.com/XJBrAkl.png
please help me

**Comment by mrkhoa99** [comment]
You check permission and owner files? http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by tommoholmes** [comment]
I have been set my permession
I set 777

**Comment by mrkhoa99** [comment]
You need to read document about about installing Guide: http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html
If you use Apache, don't forget to enable and _.htaccess_ rewrite: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html#apache-help-rewrite

**Comment by mrkhoa99** [comment]
<p>The GitHub issue tracker is intended for technical issues only. Please refer to the <a href="https://community.magento.com" target="_blank">Community Forums</a> or <a href="http://magento.stackexchange.com/" target="_blank">Magento Stack Exchange</a> site for technical questions. In your case, the <a href="https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2" target="_blank">programming questions forum</a> is likely the most appropriate.</p>

**Comment by mazhalai** [comment]
Closing since this is not a bug.
