### ISSUE TITLE
Can't upload product image after upgrade to magento 2.3.5-p2

### ISSUE THREAD

**Issue by clion007** [magento/magento2#29849]
### Preconditions (*)

1. Magento version:2.3.5-p2
2. PHP version:7.1, Mysql 5.7

### Steps to reproduce (*)

1. In the page of product edit, I test upload images in backend at the tab Images and videos. I found it couldn't upload and there is no any error message in the page and log. Only alert an error widow notice that file was not uploaded, wrong file,
2. I found in the latest version of magento 2, the seesion param is not used for the url of image uploader controller. Anyone can tell me how to fix the issue?

### Expected result (*)

1. [Screenshots, logs or description]
2. image upload normal.

### Actual result (*)

1. [Screenshots, logs or description]
2. *.jpg was not uploaded, wrong file.
3. Only one time there is error log said that the request method of controller catalog/product/gallery/upload is get, I guess it should post. But I don't know where is the request method set? And why it's get method if it should post.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @clion007 thank you for your report.
I`m not able to reproduce this issue. Tested on latest 2.4-develop and on 2.4.0 after upgrade from 2.3.5-p2

**Manual testing scenario:**
1. Upgrade 2.3.5-p2 to 2.4.0 - [instruction](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
2. Open simple product to edit
3. Expand "Images and videos" section
4. Upload few images (.jpg, .gif and .png)

**Result:**
- Images are uploaded successfully. 
![Peek 2020-09-02 12-30](https://user-images.githubusercontent.com/51681379/92079088-06b52b80-edc8-11ea-807a-bb73d66530e0.gif)

If you'd like to update the issue, please reopen it.

**Comment by clion007** [comment]
> Hi @clion007 thank you for your report.
> I`m not able to reproduce this issue. Tested on latest 2.4-develop and on 2.4.0 after upgrade from 2.3.5-p2
> 
> **Manual testing scenario:**
> 
> 1. Upgrade 2.3.5-p2 to 2.4.0 - [instruction](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
> 2. Open simple product to edit
> 3. Expand "Images and videos" section
> 4. Upload few images (.jpg, .gif and .png)
> 
> **Result:**
> 
> * Images are uploaded successfully.
>   ![Peek 2020-09-02 12-30](https://user-images.githubusercontent.com/51681379/92079088-06b52b80-edc8-11ea-807a-bb73d66530e0.gif)
> 
> If you'd like to update the issue, please reopen it.

If I don't like to update magento 2.4 right now, how should I fix this issue?

**Comment by clion007** [comment]
I found this issue is same as [https://github.com/magento/magento2/issues/28055](url) and not changed in the latest version 2.4.0, since 2.3.4-p2 is exist.

**Comment by clion007** [comment]
Because I use phpstorm IDE, so develop magento in windows.
