### ISSUE TITLE
What is the rationale behind making BaseTestCase::setUp() public

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#2985]
In https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/lib/internal/Magento/Framework/TestFramework/Unit/BaseTestCase.php#L23

the protected defined `setUp()` method is implemented as public.

What is the rationale of making it part of the public interface of the test-case type?

**Comment by mazhalai** [comment]
Yes, agree it that it should be protected. It would be nice to get it fixed in all tests. Would you like to submit a PR to fix this?

**Comment by tkn98** [comment]
I won't provide a fix for all tests, that's your matter. However, I could consider to write a patch for that file making the setUp() method protected _and_ making the class abstract. Please let me know if you would pull that in.

**Comment by Vinai** [comment]
To fix the tests in one go run

``` bash
$ find lib/internal app/code/Magento -name '*.php' -exec sed -i '' -e 's/public function setUp(/protected function setUp(/' {} \;
```

**Comment by mazhalai** [comment]
@tkn98 yes! We welcome community contributions. Please do submit a PR. Instructions [here](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html).
Also, Thank you @Vinai!!

**Comment by ktomk** [comment]
@mazhalai please find the patch in #3029

**Comment by mazhalai** [comment]
Closing since the related PR has been accepted.
