### ISSUE TITLE
Minicart height not calculated correctly under certain circumstances

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#29859]
### Preconditions (*)

1. 2.4.0

### Steps to reproduce (*)

1. Create 3 test products, all with 0 stock, all with backorders enabled with notify
2. Go to frontend and add 5 of each to your basket

### Expected result (*)

1. Minicart should be sized appropriately

![image](https://user-images.githubusercontent.com/30697781/91888470-4410a080-ec84-11ea-9816-500d7722aff5.png)

### Actual result (*)

1. There is a large margin at the bottom of the minicart. It grows the more items there are in the cart.

![image](https://user-images.githubusercontent.com/30697781/91888432-36f3b180-ec84-11ea-841f-9c092c8222a4.png)

### Investigation
The problem is happening because in the sidebar.js function calculateHeight, as the height of the minicart area is 0 (height hasnt been caluculated yet) the scroll bar is enabled. This reduces the width of the minicart by a small amount. However it is just enough to cause the backorder messages to go onto 3 lines. This means that the height that gets calculated is too large. When the minicart is ready to be displayed, the scroll bar disappears and the minicart drawable area becomes slightly wider and the backorder messages only take up 2 lines. The minicart height is set to the correct height for the slightly narrower minicart draw area including scrollbar, thus there ends up being a big whitespace area at the base.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29859-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29859-2-4-develop.instances.magento-community.engineering/admin_b03b](https://i-29859-2-4-develop.instances.magento-community.engineering/admin_b03b)
Login: `27539f6b` Password: `84258787d4d1`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @gwharton,
Verified this issue in the latest Magento 2.4 Instance with the above steps to be reproduced, actual result and expected result.
**PFA:** 
![Cart_Magento_Issue](https://user-images.githubusercontent.com/24711761/91895592-20b21980-ecb5-11ea-909a-c9502b1ef86f.png)

Thanks.

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37290` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
The effect is much more pronounced if the product name is short enough so that the backorder message goes onto two lines without scrollbar and onto three lines with the scrollbar.

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-29859-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29859-2-4-develop.instances.magento-community.engineering/admin_a008](https://i-29859-2-4-develop.instances.magento-community.engineering/admin_a008)
Login: `2558e2ce` Password: `10e6a0dc9491`
Instance will be terminated in up to 3 hours.

**Comment by gwharton** [comment]
Not stale

**Comment by gwharton** [comment]
Still not stale.

**Comment by Melnychuk-Alexandr** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @gwharton,

Thanks for your reporting and collaboration,

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.



![Home-Page](https://github.com/magento/magento2/assets/51680745/7926df4f-a0d4-4ce2-bf70-d1ab7e787271)



Minicart is sized appropriately.

Hence we are closing this issue.


Thanks.
