### ISSUE TITLE
Website Indexing Problem:

### ISSUE THREAD

**Issue by sarvang01** [magento/magento2#29855]
Hello All,

I am new in this platform. My Website base is Magento 2 - Since last some days I am trying to index my website on google, but it's not going to index.

I have submitted a website in Google console and try to submit sitemap.xml but it shows a 403 error.

I couldn't identify proper solution for the same. here I am attaching the necessary screens to understand this case.

Please suggest a necessary solution for WordPress and Magento Default setting.

![2](https://user-images.githubusercontent.com/70587979/91863097-5d1d4f80-ec8c-11ea-8175-9eb8182d94cb.jpg)
![1](https://user-images.githubusercontent.com/70587979/91863158-6f978900-ec8c-11ea-982a-9b665221d9ba.jpg)
![3](https://user-images.githubusercontent.com/70587979/91863056-4f67ca00-ec8c-11ea-8dc1-535d5073fa96.jpg)

**Comment by DavaGordon** [comment]
I have looked at your website and can confirm that this isn't a magento bug but more an issue a hosting issue. possible an issue with your .htaccess file. you can confirm this by using https://www.dotcom-tools.com/ and the solution would be to contact your hosting company / developer to get this resolved

**Comment by krishprakash** [comment]
Hi @sarvang01. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only 
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
