### ISSUE TITLE
Can't login to frontend after upgrading to 2.4.0

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29865]
### Preconditions (*)

- Shop in Developer mode
- PHP 7.4.9
- PHP Module "Sodium" is installed.
- libsodium is installed with version 1.0.18

### Steps to reproduce (*)

1. Upgrade shop from EE 2.3.5-p2 to EE 2.4.0
2. Disable Module "Magento_TwoFactorAuth" (not sure if it makes a difference, but I mention all steps I made)
3. Try to login to frontend as customer.

### Expected result (*)

1. Login should work

### Actual result (*)
1. Notice: Undefined offset: 2 in /home/x/y/vendor/magento/framework/Encryption/Encryptor.php on line 591
2. An unspecified error occurred. Please contact us for assistance.

![image](https://user-images.githubusercontent.com/16349349/92947580-79717700-f458-11ea-9394-e50af3f77158.png)

Appearing after modifying _vendor\magento\module-customer\Controller\Account\LoginPost.php_ to make it show more details by adding this code:

    $message = $e->getMessage();
    $this->messageManager->addError($message);

before

```
$this->messageManager->addErrorMessage(
     __('An unspecified error occurred. Please contact us for assistance.')
);
```

I tried clearing the browser cache and cookies, but it did not helped.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
I noticed that the array `$hasVersionMap` in the file *vendor\magento\framework\Encryption\Encryptor.php* is missing an entry which causes the bug.

So I changed it from

    /**
     * @var array map of hash versions
     */
    private $hashVersionMap = [
        self::HASH_VERSION_MD5 => 'md5',
        self::HASH_VERSION_SHA256 => 'sha256'
    ];

to 

    /**
     * @var array map of hash versions
     */
    private $hashVersionMap = [
        self::HASH_VERSION_MD5 => 'md5',
        self::HASH_VERSION_SHA256 => 'sha256',
        self::HASH_VERSION_ARGON2ID13 => 'argon2id13'
    ];

But now I get **This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP**

**Comment by Eddcapone** [comment]
I noticed that the problem disapears after changing back to PHP 7.3.21 so it must have something to do with missing support for PHP 7.4

**Comment by mrtuvn** [comment]
Undefined offset: 2 in .../vendor/magento/framework/Encryption/Encryptor.php on line 591
May related with https://github.com/magento/magento2/issues/23511
@hostep can you give some suggestion

**Comment by hostep** [comment]
@mrtuvn: no idea, we are holding off with upgrading to Magento 2.4.0 / PHP 7.4 until Magento becomes a bit more stable. We'll probably start using it when 2.4.1 or 2.4.2 is out, it's too unstable now to start using it in my opinion.

If I run into this within some months, I can take a look, but it sounds like Eddcapone is already debugging it a bit, so maybe he'll find the root cause.

**Comment by Eddcapone** [comment]
I gave up and just changed to PHP 7.3.21 again. I am also waiting until the core team adds full PHP 7.4 support. Maybe my version (7.4.9) is not supported yet.

**Comment by ihor-sviziev** [comment]
@Eddcapone could you provide output of the following command?
```
php -r 'var_dump(PHP_VERSION, password_hash("password", PASSWORD_ARGON2ID));'
```

I have following output and seems like everything works fine:
```
string(5) "7.4.9"
string(97) "$argon2id$v=19$m=65536,t=4,p=1$uqEvaot8X3H0SerCB6wX9w$3K/Tu3q79mEpUMWgMjUtce9dN4uzeKBh8oYsUrLX+H0"
```

**Comment by Eddcapone** [comment]
I get:

```
string(5) "7.4.9"
bool(false)
bool(false)

```

I just changed back to PHP 7.4.9 in cpanel (rackspeed server) but now `php -m | grep sodium` gives no output anymore. Looks like rackspeed removed the module... As I tested it was in my modules. I will contact the rackspeed admins and report back if I tested it with sodium enabled.

**Comment by Eddcapone** [comment]
The admins just installed sodium, now I get:

```
string(5) "7.4.9"
bool(true)
bool(true)
```
But the login still fails with

> Notice: Undefined offset: 2 in /home/x/y/vendor/magento/framework/Encryption/Encryptor.php on line 591
> An unspecified error occurred. Please contact us for assistance.

![image](https://user-images.githubusercontent.com/16349349/92947580-79717700-f458-11ea-9394-e50af3f77158.png)

**Comment by ihor-sviziev** [comment]
@sidolov seems like this issue should have priority p1, could you check it?

**Comment by sidolov** [comment]
@ihor-sviziev it looks like an environment configuration issue to me

**Comment by ihor-sviziev** [comment]
@sidolov maybe, but definitely we need to understand why it happened and what to do in such cases.
@Eddcapone i believe composer install isn’t failing on that environment?

**Comment by sidolov** [comment]
@ihor-sviziev you know, a few months ago I had exactly the same issue after migration to PHP 7.4. It's a shame that I don't remember what exactly helped me but it was definitely an env config issue related to sodium extension.

**Comment by Eddcapone** [comment]
@ihor-sviziev , I get **Nothing to install or update** if I execute `composer install` in this project. 
@sidolov I can share my config with your if you like, where is it located? How can I give you the necessary informations?

The error in line 591 makes perfect sense to me. Magento tries to access an undefined offset, because `$hashVersionMap` has only two entries and it tries to access the third one. But why does it not trigger the same error with PHP 7.3 then?

**Comment by ihor-sviziev** [comment]
Are you using developer magento mode ?

**Comment by Eddcapone** [comment]
Yes I am in developer mode

**Comment by ihor-sviziev** [comment]
@Eddcapone I believe if you'll switch to production mode - it will work for you, also this mode is recommended for production env. Hope this workaround will work for you. Will try to check this issue myself when will have a time

**Comment by Eddcapone** [comment]
@ihor-sviziev Thats no option because it is a developer environment and I would need to deploy static files every time.
But I stay at PHP 7.3 until it is fixed.

**Comment by ihor-sviziev** [comment]
@Eddcapone one more workaround - you could add following param to your env.php, and it will generate static files automatically, similar to developer mode :)
```php
return array(
   ...
   'static_content_on_demand_in_production' => 1,
   ...
);
```

**Comment by Eddcapone** [comment]
@ihor-sviziev I just tested it in production mode, and it works.
But I have to switch back, otherwise js/css is getting compressed and minified... But Im sure it gets solved in the future.

**Comment by Eddcapone** [comment]
@ihor-sviziev I changed back to developer and the error is gone here too now :)

**Comment by ihor-sviziev** [comment]
@Eddcapone if we don't really have exact steps to reproduce - can we close this issue?

**Comment by Eddcapone** [comment]
Yes, the solution/workaround is to switch to production and then to developer (or to stay on production)

**Comment by hostep** [comment]
This makes no sense, there should be no difference in hashing algorithm behavior between developer and  production mode.

----

> I believe if you'll switch to production mode - it will work for you

@ihor-sviziev: out of curiosity: on what is this statement based?

**Comment by ihor-sviziev** [comment]
@hostep in developer mode all notices are treated as exception, while in production doesn’t. Interesting thing that we still don’t have clear instruction how to reproduce this issue on clean magento installation, maybe some extension caused this issue.
If you have any - let us know

**Comment by hostep** [comment]
Ok thanks for the info Ihor!

@Eddcapone: based on your [previous comment](https://github.com/magento/magento2/issues/29865#issuecomment-691179083), if i have to guess, the sysadmins installed the sodium php extension but probably forgot to restart php-fpm (or your webserver), hence why php-cli reported it was installed but when using php in the webserver context it still didn't see it.
A better way to verify if it was installed, is to create a dummy php file with `<?php phpinfo();` as contents and requesting it via the webserver. Then see if sodium is being reported as installed (and make sure libsodium is at least version 1.0.13).
Should show you something like this:
<img width="998" alt="Screenshot 2020-09-17 at 16 03 05" src="https://user-images.githubusercontent.com/85479/93481855-571ba580-f8ff-11ea-9f9f-a140c441401b.png">

**Comment by Eddcapone** [comment]
Thats what I did from the start, as you can see in my original question I wrote:

> libsodium is installed with version 1.0.18

I checked that by executing `php -i | grep libsodium`

**Comment by hostep** [comment]
Yes, but that's using php-cli, not php invoked by the webserver, which can give you different results 🙂

**Comment by Eddcapone** [comment]
@hostep Oh, I see. Thx! 👍
