### ISSUE TITLE
Product attribute options management uses scopes inconsistently

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#29862]
### Preconditions

1. Clean Magento 2.3.5-p1, 2.4-develop is installed

### Steps to reproduce

1. Get list of "color" attribute values using /rest/V1/products/attributes/color/options GET method (in default Magento installation it shows empty list what is expected) eg.:

```
curl --location --request GET 'https://magento23.test/rest/V1/products/attributes/color/options' \
--header 'Authorization: Bearer <add token here>' 
```

2. add "red" color using /rest/V1/products/attributes/color/options POST method

```
curl --location --request POST 'https://magento23.test/rest/V1/products/attributes/color/options' \
--header 'Authorization: Bearer <add token here>' \
--header 'Content-Type: application/json' \
--data-raw '{"option":{"label":"red","sort_order":0}}'
```

3. Get list of "color" attribute values again (see "red" on the list what is expected)
4. In the admin backend, set "Default Store View" label for "red" color to "Blue"
5. Get list of "color" attribute values again (see "Blue" on the list)
6. As "red" value looks as not existing on the list, try adding "red" color using api POST again (error occurs)

It looks that both API requests use scope inconsistently - "add" action validates against global scope and adds value for global scope. Then "list" action returns values from default scope (website).

Note that If I explicitly set scope to global by using "all" parameter, it returns proper values, I consider is as a workaround:

```
curl --location --request GET 'https://magento23.test/rest/all/V1/products/attributes/color/options' \
--header 'Authorization: Bearer <add token here>' 
```

### Expected result

1. Both API requests used to manage product attribute value use scope consequently.

### Actual result

1. Each API request used to manage product attribute value uses different scope

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wojtekn** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wojtekn, here is your [Magento instance](https://i-29862-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29862-2-4-develop.instances.magento-community.engineering/admin_81b3](https://i-29862-2-4-develop.instances.magento-community.engineering/admin_81b3)
Login: `556398ec` Password: `a37721e69201`
Instance will be terminated in up to 3 hours.

**Comment by wojtekn** [comment]
I reproduced issue using provided vanilla 2.4 instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37693` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
