### ISSUE TITLE
Late Static Binding on private constants in Magento\Catalog\ViewModel\Product\Breadcrumbs

### ISSUE THREAD

**Issue by Cheeerd** [magento/magento2#29879]
### Preconditions (*)

1. Magento 2.4.0
2. PHP 7.4.9

### Steps to reproduce (*)

1. Create a plugin for Magento\Catalog\ViewModel\Product\Breadcrumbs
2.

### Expected result (*)

1. All works
2.

### Actual result (*)

1. Interceptor class can't get access to private [constants ](https://github.com/magento/magento2/blob/40f9a4ba50532d45caee7246e019fd4d95d973ff/app/code/Magento/Catalog/ViewModel/Product/Breadcrumbs.php#L23) through [late static bindings](https://github.com/magento/magento2/blob/40f9a4ba50532d45caee7246e019fd4d95d973ff/app/code/Magento/Catalog/ViewModel/Product/Breadcrumbs.php#L74)
2. Error: Undefined class constant 'XML_PATH_CATEGORY_URL_SUFFIX' in /var/www/magento2/public_html/vendor/magento/module-catalog/ViewModel/Product/Breadcrumbs.php:74 Stack trace: #0

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by toxix** [comment]
@magento I am working on this

**Comment by toxix** [comment]
This bug is the same category than this here https://github.com/magento/magento2/issues/28981 and resolved in this pullrequest: https://github.com/magento/magento2/pull/28797

Already checked an analog solution locally and it works, will open a pullrequest with the fix.

**Comment by toxix** [comment]
@Cheeerd  you might want to check if my change is fixing your issue.

**Comment by brideo** [comment]
yeah I came across #28981 after, might be worth closing this one as it's a duplicate I guess.

**Comment by magento-engcom-team** [comment]
Hi @Cheeerd. Thank you for your report. 
The issue has been fixed in magento/magento2#29925 by @toxix in 2.4-develop branch
Related commit(s):
 - [2d1d097b39bdd94ef6e929c34fc721113a3505ea](https://github.com/magento/magento2/commit/2d1d097b39bdd94ef6e929c34fc721113a3505ea)

The fix will be available with the upcoming 2.4.2 release.
