### ISSUE TITLE
 There are no commands defined in the "setup:cron" namespace after upgrading to magento 2.4.0

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29872]
### Preconditions (*)

1. Enterprise

### Steps to reproduce (*)

1. Upgrade from 2.3.5-p2 to 2.4.0 by using composer.
2. Make sure that you are using at least PHP 7.3

### Expected result (*)

1. Upgrade succeeds without problems

### Actual result (*)

1. I am receiving alot of e-mails saying that a cron job failed with "There are no commands defined in the "setup:cron" namespace"
2. Also calling `php bin/magento setup:cron:run` throws error:

  There are no commands defined in the "setup:cron" namespace.

>   Did you mean one of these?
>       setup
>       setup:config
>       setup:db
>       setup:db-data
>       setup:db-declaration
>       setup:db-schema
>       setup:di
>       setup:performance
>       setup:static-content
>       setup:store-config

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
Looks like they have removed the command. I deleted the cron job now the error is gone.

**Comment by onepack** [comment]
@Eddcapone , how do you mean "They have removed the command" . I have the message on 4 different installs.
How can I solve this as I have been looking for the source of this for some time now.

**Comment by hostep** [comment]
@onepack: as far as I'm aware, the `setup:cron:run` command was part of the web setup wizard. That thing [has been removed](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html#infrastructure-improvements) in 2.4.0, so it's no longer needed to put the `setup:cron:run` call in your crontab. You can safely remove it from there if you are using Magento 2.4.0 and higher.
You can also remove the entry `update/cron.php` from your crontab, that appears to have been removed as well in 2.4.0.

**Comment by onepack** [comment]
@hostep Thank you! I was going through all modules thinking it was a bug. I was completely overlooking this part.
I adjusted the cron and got immediate result.
Cheers!

**Comment by Eddcapone** [comment]
It is just sad that magento does not point this out in the changelog

**Comment by perfpcs** [comment]
I have this same problem in my logs and it is sad Magento actually causes this problem! When you do a:
bin/magento cron:install

It adds 3 lines to your crontab including these 2 that you are saying are nor needed. Why does Magento always make a mess of things???

So what should a crontab look like these days with M 2.4?? 1 line????

* * * * * /usr/bin/php7.4  ............/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >>......../var/log/magento.cron.log &> /dev/null

Is that it? Change crontab to this 1 line??

**Comment by hostep** [comment]
Exactly, Magento 2.4.x only needs the `bin/magento cron:run` line in your crontab

The [documentation](https://github.com/magento/devdocs/pull/7944) is currently being updated to add more warnings around this.

**Comment by perfpcs** [comment]
@hostep ..thank you Sir!  Yes please update the docs and fix the install command that sets the 3 lines in your crontab.

**Comment by hostep** [comment]
@perfpcs: are you sure that `bin/magento cron:install` installs those 3 lines? I've just tested this on a clean Magento 2.4.1 installation (will be available to the public on 15 October) and it only adds 1 line. I haven't tested it on 2.4.0 though...

**Comment by perfpcs** [comment]
@hostep , yes I'm sure it added the 3 lines for me because previously the lines in the crontab were:

/usr/bin/php

then after we changed the server environment to php 7.4 when I ran the install command it added 3 lines all starting with:

/usr/bin/php7.4

**Comment by hostep** [comment]
Hi @perfpcs!

Just tested with a clean Magento 2.4.0, and it also only writes one line to the crontab.

Just FYI, the lines which are written to the crontab are defined in the file `vendor/magento/module-cron/etc/di.xml`.
- In Magento 2.3.5-p2 it looks like this: https://github.com/magento/magento2/blob/2.3.5-p2/app/code/Magento/Cron/etc/di.xml#L66-L79 (3 tasks, meaning 3 lines)
- In Magento 2.4.0, it looks like this: https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Cron/etc/di.xml#L66-L71 (1 task, meaning 1 lines)

Can you verify if that file is correct in your case? If it isn't, then the upgrade to 2.4.0 might not have been done like it was supposed to. If that file is correct in your case, then I have no idea. I would just manually remove all the lines from your crontab and try `cron:install` again and see how it behaves.

**Comment by perfpcs** [comment]
Hi @hostep , my di.xml file does only have the one line so I dont understand why it added the 3 but I'm sure it happened.
I did manually remove the 2 extra lines and now no more errors in my system.log.
Thank you very much for your help and input.

**Comment by fj-sfd** [comment]
Hi @hostep , Thank You for pointing it out clearly. 
I have updated my crontab.

**Comment by webkul-ajaysaini** [comment]
This issue can be fixed by running the following commands.
bin/magento cron:remove
bin/magento cron:install

**Comment by Ylmzef** [comment]
_Any reference to update/cron.php and bin/magento setup:cron:run should also be removed from the crontab_
https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html
