### ISSUE TITLE
Refresh index chokes

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#2987]
Actually this problem is actual for Magento 1 but I see it's still not fixed for Magento 2.
Refresh index is based on queue which is filled by triggers which adds entities to the queue even if entity values were not updated.
Lot of projects have custom modules like product import and other modules which do something with product attributes, for example, disable products without images so that SQL query match many rows but change only few of them so that triggers can generate queue faster than refresh index manage it.
It can be fixed easily by adding to the triggers "IF !(NEW.value <=> OLD.value)" condition.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Refresh-index-chokes/idi-p/45755).

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70883
