### ISSUE TITLE
Composer Update - EE 2.3.5 > 2.4.0 - Failed

### ISSUE THREAD

**Issue by DavaGordon** [magento/magento2#29871]
### Preconditions (*)

1. Composer Update 2.3.5 > 2.4.0
2. PHP 7.3.19

### Steps to reproduce (*)

Running composer update from command line seems to complain about version mismatch of PHP also incompatible version of module-paypal-on-boarding also issues with locked versions. 

commands performed so far each one with the same result also tried after deleting vendor and composer.lock to see if it makes a difference.

`composer update`
`composer require magento/magento-cloud-metapackage:>=2.3.4`
`composer require magento/magento-cloud-metapackage:2.4.0`

### Expected result (*)

1. All packages to update without any sort of issues

### Actual result (*)

Problem 1
    - magento/framework 100.0.2 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.3 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.4 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.5 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.6 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.7 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.8 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.9 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.0-rc1 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.0-rc2 requires php ~5.5.22|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.0-rc3 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.10 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.11 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.12 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.13 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.14 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.15 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.16 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.17 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.0-rc21 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.0-rc22 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.0-rc23 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.0-rc30 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.18 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.19 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.0.20 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.16 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.0 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.17 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.1 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.8 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 100.1.18 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.9 requires php ~7.0.13|~7.1.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.10 requires php ~7.0.13|~7.1.0|~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.2-p2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 101.0.11 requires php ~7.0.13||~7.1.0||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - Can only install one of: magento/framework[102.0.5-p2, 103.0.0].
    - Can only install one of: magento/framework[102.0.4-p2, 103.0.0].
    - Can only install one of: magento/framework[102.0.5, 103.0.0].
    - Can only install one of: magento/framework[102.0.4-p1, 103.0.0].
    - Can only install one of: magento/framework[102.0.3-p1, 103.0.0].
    - Can only install one of: magento/framework[102.0.4, 103.0.0].
    - Can only install one of: magento/framework[102.0.3, 103.0.0].
    - Can only install one of: magento/framework[103.0.0, 102.0.5-p2].
    - magento/module-paypal-on-boarding 100.4.0 requires magento/framework 103.0.* -> satisfiable by magento/framework[103.0.0].
    - magento/magento-cloud-metapackage 2.4.0 requires magento/module-paypal-on-boarding ~100.4.0 -> satisfiable by magento/module-paypal-on-boarding[100.4.0].
    - magepal/magento2-enhanced-ecommerce 1.4.0 requires php ~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.1.3|~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - Installation request for magento/magento-cloud-metapackage >=2.4.0 -> satisfiable by magento/magento-cloud-metapackage[2.4.0].

**Comment by DavaGordon** [comment]
This issue was down to an old package being required in the base composer file. this is now resolved

**Comment by jignesh-baldha** [comment]
Hello @DavaGordon
How did you fix this issue?

**Comment by DavaGordon** [comment]
> Hello @DavaGordon
> How did you fix this issue?

If you look in your composer for `magento/module-url-rewrite-import-export` and remove it this should resolve the issue with upgrading.
