### ISSUE TITLE
Getpricetype always return NULL

### ISSUE THREAD

**Issue by giordhano** [magento/magento2#29877]
https://github.com/magento/magento2/blob/b87f1dfa84d7726e1824c11caa4d741710119d9a/app/code/Magento/Quote/Model/Quote/Item/AbstractItem.php#L629

The error produces an inconsistency in the quote_item table when the price of a configurable product is updated and the user re-enters at checkout

this comes from **_**Magento\Quote\Model\Quote\Address\Total\Subtotal**_**  

![image](https://user-images.githubusercontent.com/823663/92021745-d5812080-ed1f-11ea-9379-ffeacbf3cb19.png)

**Preconditions**
Create configurable product with at least one option

**Steps to reproduce**

* Add a configurable product to cart
* Update the price of the simple product added to cart
* Re enter to checkout

**Actual results**

In the table quote_item the row of simple product has the old price, the configurable row is ok
This is visible when we use endpoint /orders

**Expected results**

Both, simple and configurable rows should have the same price

**Comment by engcom-Oscar** [comment]
Hi @giordhano, Thank you for your contribution.
I've been testing this issue according your  description and have got different result.

Precondition:
Basic Magento 2.4-develop installed

Steps:
1. Add a configurable product to cart
2. Open the table 'quote_item' in DB and check records for your cart
3. Update in admin the price of the configurable option - simple product which added to your cart
4. Re-enter to checkout
5. Open the table 'quote_item' in DB and check records for your cart

Result:
Before and after changes of the price of the configurable option - simple product which added to your cart in the 'quote_item'  table I saw that price of the simple option is 'zero', only price of parent is present, and it correctly updated

Before update
![image](https://user-images.githubusercontent.com/60198413/92474951-4ecbb800-f1e5-11ea-86ce-db8818101f29.png)

after update
![image](https://user-images.githubusercontent.com/60198413/92475113-8aff1880-f1e5-11ea-9601-b5e601f64267.png)
