### ISSUE TITLE
ERR_INVALID_RESPONSE after changing from production mode to developer or default mode

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29882]
### Preconditions (*)

1. EE 2.4.0
2. Production Mode

### Steps to reproduce (*)

1. Change from production mode to developer mode `php bin/magento deploy:mode:set developer`
2. Reload frontend

### Expected result (*)

1. Frontend should load.

### Actual result (*)

1. ERR_INVALID_RESPONSE

![image](https://user-images.githubusercontent.com/16349349/92110264-bb604480-edea-11ea-86f5-2dcf1d4eff97.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
@magento I am working on this

**Comment by Eddcapone** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Eddcapone. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Eddcapone, here is your [Magento instance](https://i-29882-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29882-2-4-develop.instances.magento-community.engineering/admin_3260](https://i-29882-2-4-develop.instances.magento-community.engineering/admin_3260)
Login: `be0170d4` Password: `fa7a484def2f`
Instance will be terminated in up to 3 hours.

**Comment by Eddcapone** [comment]
@magento-engcom-team How can I connect to this instance via SSH so I can test it?

**Comment by Eddcapone** [comment]
Static files are not generated properly anymore since I tried to change to developer mode! I am facing the same issue as this user on [magento.stackexchange](https://magento.stackexchange.com/questions/321234/update-styling-magento-2-in-production-mode?noredirect=1#comment460596_321234) now, ironically after trying to help him.

I made a change in my theme and pushed it into production, then I tried to generate the static files with 

    bin/magento setup:upgrade --keep-generated && php bin/magento setup:di:compile && bin/magento setup:static-content:deploy && bin/magento setup:static-content:deploy de_DE && php bin/magento c:f

but the changes are not getting applied. I even flushed the whole redis cache with `redis-cli flusall` (caution: will delete all session, if you are storing them in redis)

**Comment by Eddcapone** [comment]
I have executed `grunt refresh` and then `php bin/magento setup:di:compile && bin/magento setup:static-content:deploy && bin/magento setup:static-content:deploy de_DE` now it works again

**Comment by engcom-Delta** [comment]
Hi @Eddcapone thank you for your report, I'm not able to reproduce issue by steps you described on clean Magento EE 2.4-develop
**Result:**
![Screenshot from 2020-11-24 21-16-05](https://user-images.githubusercontent.com/51681379/100140926-4c9b0080-2e9a-11eb-9e17-7114ff093eee.png)


Could you provide additional steps? Do you use redis for the Magento page and default cache?

**Comment by engcom-Delta** [comment]
Hi @Eddcapone thank you for your report, I'm not able to reproduce issue by steps you described on clean Magento EE 2.4-develop
**Result:**
![Screenshot from 2020-11-24 21-16-05](https://user-images.githubusercontent.com/51681379/100140926-4c9b0080-2e9a-11eb-9e17-7114ff093eee.png)


Could you provide additional steps? Do you use redis for the Magento page and default cache?

**Comment by Eddcapone** [comment]
Yes I am using redis, but im not sure on which of my environments I tested it. I also have one environment without redis maybe i tested it on that one. Sorry

**Comment by engcom-Delta** [comment]
@Eddcapone I am not able to reproduce issue on magento EE 2.4-develop with configured redis for [page-cache](session) and [session](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html#config-redis-config)
**Result:**
:heavy_check_mark: Home page is loaded
:heavy_check_mark: No errors when change from production mode to developer mode `php bin/magento deploy:mode:set developer`

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
