### ISSUE TITLE
Configurable Product Cannot Add/Edit Configurations!

### ISSUE THREAD

**Issue by mageman** [magento/magento2#2988]
After creating a configurable product with 1 generated associated product, saving to a new attribute set, then re-open the configured product. and click on edit configuration:

There are options to add an attribute whose type is not a dropdown, i.e. yes/no or text field, but after submitting these changes, the values do not appear in the new configuration!

Furthermore, the new attribute is not being added to the attribute set!

It seems wrong that non-dropdown attributes cannot be added. Why is it not possible to add these types?

I am recommending the following:

Despite the fact that the magento manual states that only dropdown types are supported, I am requesting **support** for attribute types other than dropdown, rather than the removal of options that are not supported.  This would make working in the admin pages a-lot easier.  For example, I could have a numerical or boolean attribute that I can generate associated products for.  I was hoping to have the same user experience here in many ways similar to M 1.9.

**Comment by Krapulat** [comment]
I'm also interested in this feature.

For example if you have the attribute "size" set to "Text Swatch" you can't add new attribute values when adding/editing configurations of a product.

**Comment by antboiko** [comment]
Hi @mageman, thanks for your inquiry. I've created internal ticket MAGETWO-51965 to cover this improvement and placed it into our backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-Product-Cannot-Add-Edit-Configurations/idi-p/46156).
