### ISSUE TITLE
Custom Options not working after editing product

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#2989]
Custom Options not working after editing product.
I had to remove some Custom Options witch are colors, so i removed two of the colors and saved and closed. Then I realized i mist one, went back to edit and just the two buttons load no options and they do nothing.
![custom options](https://cloud.githubusercontent.com/assets/16354206/12303009/2c570616-b9f6-11e5-94c7-b31bf8c397f7.PNG)
![custom options bad](https://cloud.githubusercontent.com/assets/16354206/12303012/2f904e0a-b9f6-11e5-8d57-6a77e5f0d1d5.PNG)

Thank you

**Comment by zamboni084** [comment]
I exported the products and notice that the products that i edited the custom options on the custom_options column are now incomplete. 

Before:
name=Color,type=checkbox,required=1,price=,price_type=fixed,sku=_BK,option_title=Black|name=Color,type=checkbox,required=1,price=,price_type=fixed,sku=_YL,option_title=Yelow|

After:
name=Color,type=checkbox,required=1,price=,price_type=fixed,sku=,option_title=

**Comment by katmoon** [comment]
Are there any errors in the browser console?

**Comment by zamboni084** [comment]
No errors.

**Comment by kandy** [comment]
@zamboni084, Could you please tell us which version do you use, from composer or from git?

**Comment by zamboni084** [comment]
Nexcess.net installed it for me.

**Comment by kandy** [comment]
We have created ticket MAGETWO-48760 to fix issue.

**Comment by FoxtrotOscar2** [comment]
1 comment, 1 question:
Comment: exact same issue here - custom product options no longer showing up in product admin page AFTER I created an export. Reproduced this on another clean install (Add product --> add Custom Options --> save --> export, product options gone).

Question: Where can I find information on follow-ups/resolution for MAGETWO-48760?

**Comment by mslabko** [comment]
Hello @zamboni084 ,
Issue will be fixed in one of next patch release.

**Comment by giafrata** [comment]
Any news about this issue?

**Comment by KrystynaKabannyk** [comment]
Hello @zamboni084, the reported issue has been fixed in 2.0.5 patch release that's why I'm closing it. Thanks for your help! If you have additional questions or information feel free to create another issue!

**Comment by santhakumarvenkattappan** [comment]
Hi,

  I have the same problem in may magento site existing product custom options I can't edit or add but new product I can add new custom options 
Note: no errors are shown they show **Product has been saved**

please how to find the issue

thanks,
santha

**Comment by cizgidekiadam** [comment]
Same in 2.1.2

Add custom option via rest api, refresh caches.
When entered edit page in backend, error message shown.
<pre>
Custom options with price type "percent" is not available for configurable product.</pre>

Implementation:
<pre>
$option["option"]=[
                "product_sku"=>{PRODUCTSKU},
                "title"=>"Custom Option",
                "type"=>"checkbox",
                "sort_order"=>0,
                "is_require"=> false,
                "price"=>0,
                "price_type"=>"fixed",
                "sku"=>{OPTIONSKU},
                "values"=>[
                    [
                    "title"=>"Option 1",
                    "sort_order"=>0,
                    "price"=>0,
                    "price_type"=>"fixed",
                    "sku"=>{VALUESKU},
                    ],
                    [
                        "title"=>"Option 2",
                        "sort_order"=>0,
                        "price"=>0,
                        "price_type"=>"fixed",
                        "sku"=>{VALUESKU},
                    ]
                ]
            ];
        }
        postRest('product/options',$option);
</pre>

**Comment by pbaum83** [comment]
Hello,

I've been trying to track down this problem and this is labeled fixed, but has a fix been released already or is it still pending until 2.3? As of right now on 2.2.2 I'm still experiencing this issue.

We have a large number of configurable SKUs and are migrating from 1.x currently and this is a very important feature for our product managers.

**Comment by simonmaass** [comment]
I am having the same problem in magento 2.2.5
