### ISSUE TITLE
Category position not coming as per backend in category query graphql

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#29900]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Add some categories and it's children at backend
2. then check for category query with children queries
`{
  category(id: 2){
    products {
      total_count
    }
    children_count
    children {
      id
      level
      name
      path
      image
      hover_image_url
    products {
      total_count
    }
    children_count
      children {
        id
        level
        name
        path
        image
        hover_image_url
        products {
            total_count
        }
      }
    }
  }
}`
3. then match the same with backend category positions

### Expected result (*)

 ![image](https://user-images.githubusercontent.com/44425160/92203571-1a7f9100-ee9f-11ea-8d76-f8e983ae6fc3.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/44425160/92203695-6df1df00-ee9f-11ea-99d4-410edcaf819e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance
