### ISSUE TITLE
User locale interface doesnt affect admin language

### ISSUE THREAD

**Issue by elbasri** [magento/magento2#29917]
Hello,
recently we turned in a problem in admin panel 
its get the locale default language, not the user interface locale choosed in thier profile (what its has to be)
by result, all admin users get the admin interface in one language (choosed in stores=>configuration=>generale=>locale) whanever thier profiles languages !
is there any other places/files i should search for to resolve this problem?

**Comment by engcom-Delta** [comment]
Hi @elbasri 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
You could change language for admin panel here: admin->Account Settings(admin)
![Screenshot_141](https://user-images.githubusercontent.com/51681379/92613401-9d4f8400-f2c3-11ea-8491-359ba7d33f95.png)
![Screenshot_140](https://user-images.githubusercontent.com/51681379/92613393-9a549380-f2c3-11ea-9419-5173c9acda83.png)

**Comment by elbasri** [comment]
> 
> 
> Hi @elbasri
> The GitHub issue tracker is intended for Magento Core technical issues only.
> Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
> You could change language for admin panel here: admin->Account Settings(admin)
> ![Screenshot_141](https://user-images.githubusercontent.com/51681379/92613401-9d4f8400-f2c3-11ea-8491-359ba7d33f95.png)
> ![Screenshot_140](https://user-images.githubusercontent.com/51681379/92613393-9a549380-f2c3-11ea-9419-5173c9acda83.png)

Hi, thank you but it not the solution... i already mentioned that even changing the profile locale (from account settings) it doesnt affect the lang at all !

**Comment by engcom-Delta** [comment]
@elbasri Also appropriate language pack should be installed
