### ISSUE TITLE
Customer segment as Identifier should be send as separate header key in GraphQL requests

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#29910]
As a Magento administrator 
I want to be able to send an extra header key in the request header (e.g. Customer Segment Id)
so that I can see a response that matches what a particular customer would see.

Story is not final, is in progress

Background:
Current functionality allows for an admin token to be send and a preview version.
However, any catalog related entities that will be returned - are in fact the ones that the guest customer would see.
Technically, the admin in this case is considered a guest since no customer group can be extracted.

Ideally, when sending an extra header key, we should be able to display catalog values that are specific to a given customer segment, or, to a specific shared catalog.

### AC
Yet to be defined
### Approved Schema
Current schema would suffice - no edits or new elements needed

**Comment by engcom-Oscar** [comment]
Hello @pmarjan 
Thank you for contribution and collaboration!

@sdzhepa could you please move this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.
[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by sdzhepa** [comment]
Hello @engcom-Oscar 
As you can see the issue has a label "Project: GraphQL"
It means this issue related to the additional project, which has its own workflow, issue processing, working with the backlog and delivery etc.

Our process for the Issue Confirmation process is applicable only for community reports which do not have a "Project: XXXX" label. The responsible team(s)/person(s) assigned to this project will work on collaboration and processing "Project: xxx" related issue reports
 
fyi: @pmarjan

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by cpartica** [comment]
closing this because we fixed this in another way - we encode customer segment into the cache key then we hash everything with store and currency - so customer segment won't be public knowledge
