### ISSUE TITLE
CustomerToken type should contain token expired time

### ISSUE THREAD

**Issue by codynguyen1** [magento/magento2#29922]
*As a developer I want to get the expired time for customer token so that when it's expired, I can revoke it and log out to avoid permission issues with the cart APIs.*

### Approved Schema
type CustomerToken {
    token: String @doc(description: "The customer token")
    expired_time: Int @doc(description: "Token expired time")
}

If this is approved, I will create a PR to update it.

**Comment by gabrieldagama** [comment]
https://github.com/magento/magento2/pull/29935#issuecomment-802110459
