### ISSUE TITLE
feature request - previous and next buttons

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#2992]
Previous and next buttons on the product page in admin. So you don't have to exit to the fist page of the catalog every time.

Like this:

![capture](https://cloud.githubusercontent.com/assets/16354206/12308385/040aacea-ba13-11e5-8127-ce127a9c945d.PNG)

**Comment by hgpit** [comment]
I would also like to see this.

**Comment by antboiko** [comment]
Hi @zamboni084, thanks for your inquiry. I've created internal ticket MAGETWO-52488 for this feature and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/feature-request-previous-and-next-buttons/idi-p/46152).
