### ISSUE TITLE
2.4 AbstractAddress on checkout causes CRITICAL error on checkout "Array to string conversion" (correctly?)

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#29928]
Testing upgrading my site to 2.4 and checkout address stage fails

### Preconditions (*)

1. 2.4 updated from 2.3?

running php 7.3.21

I have a checkout module but disabling it and reverting to normal checkout produces the same error

### Steps to reproduce (*)

checkout process

### Expected result (*)

address is saved and the system moves on to shipping options

### Actual result (*)

address is not processed

the user receives no shipping options

javascript api calls to shipping-method and estimate-shipping-method fail with error 500

error appears on page `Internal Error. Details are available in Magento log file. Report ID: webapi-...`

The error in logs is 

`main.CRITICAL: Report ID: webapi-...; Message: Notice: Array to string conversion in vendor/magento/module-customer/Model/Address/AbstractAddress.php on line 341`

I first looked at my installed extensions but actually when I look at line 341 it indeed does flatten an array back into the variable that contained the array

`$value = trim(implode("\n", $value));`

Perhaps I have settings on my server where I should disable such notices?

---

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by iphigenie** [comment]
I am puzzled this creates a critical error as it seems the intent of the code

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iphigenie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iphigenie, here is your [Magento instance](https://i-29928-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29928-2-4-develop.instances.magento-community.engineering/admin_28c3](https://i-29928-2-4-develop.instances.magento-community.engineering/admin_28c3)
Login: `a77a6b1c` Password: `941f5f186304`
Instance will be terminated in up to 3 hours.

**Comment by iphigenie** [comment]
not reproduced - it must be installation relative then
