### ISSUE TITLE
Issue when you apply discount code in review & payment tab and if this affects shipping method which is selected one step before.

### ISSUE THREAD

**Issue by mehmetuygun** [magento/magento2#29938]
### Preconditions (*)

1.Magento 2.3.3

### Steps to reproduce (*)

1. create a free shipping method with condition min order value 25 ( for example)
2. Create a discount code gives any percent off (%25)
3. Add product to cart
4. proceed to checkout, fill address, then select the free shipping option.
5. proceed to payment. Hold On. Apply discount code make sure now the total value is less than what free shipping requires.
6. try to go any payment.
7. Now you are getting an error "Something went wrong with your request. Please try again later"

### Expected result (*)

1. Redirect back, and tell the customer to select the available shipping methods.

### Actual result (*)

1. ![Screenshot from 2020-09-08 11-28-32](https://user-images.githubusercontent.com/4094099/92465870-1f0db780-f1c7-11ea-89ec-82e095ee672e.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ - ] Severity: **S0** _- Affects critical data or functionality and leaves users without a workaround._
- [ -] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ - ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ - ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ - ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @mehmetuygun, thank you for your report. 
I have tested this issue on latest Magento 2.4-develop branch, following steps you described in the ticket, but got a bit different result. When I applied coupon on Payment page during checkout, my shipping method got status from 'Free shipping' into 'Not yet calculated'. When I tried to place order, I got message: 'The shipping method is missing. Select the shipping method and try again.' 
![image](https://user-images.githubusercontent.com/60198413/92603489-09c48600-f2b8-11ea-9ac2-84ee020e5e1d.png)

Can you please recheck the issue on latest 2.4-develop and update description if you will have the same result as me.

**Comment by nayembwip** [comment]
Hey, any fix for this issue? I am experiencing this on 2.3.3

**Comment by ldc321** [comment]
Hey, any fix for this issue? I am experiencing this on 2.3.4

**Comment by victortodoran** [comment]
@magento give me 2.4.2 instance

**Comment by emiliatereanu** [comment]
@magento give me 2.4.1 instance

**Comment by emiliatereanu** [comment]
@magento give me 2.4.3 instance

**Comment by rahimimo** [comment]
I am having this issue in coupon magento2.4.2 via rest API

**Comment by rahimimo** [comment]
@engcom-Oscar why this issue is marked as closed?

**Comment by agoyal-tactacam** [comment]
@engcom-Oscar Why this issue is closed as this is still happening in 2.4.6

**Comment by agoyal-tactacam** [comment]
@mehmetuygun Were you able to find any solution for this?
