### ISSUE TITLE
Should Authorize.Net Direct Post be logging a critical exception on declined transactions?

### ISSUE THREAD

**Issue by tigerx7** [magento/magento2#2993]
Having an issue where Authorize.Net Direct-Post is logging critical exceptions on declined transactions:

> main.CRITICAL: exception 'Magento\Framework\Exception\LocalizedException' with message 'Gateway error: The transaction has been declined because of an AVS mismatch. The address provided does not match billing address of cardholder.' in /var/www/magento/vendor/magento/module authorizenet/Model/Directpost.php:633

On that particular transaction, the customer did enter an incorrect zip code in checkout, so the gateway error is correct. But it's being logged as an exception and the stack trace is being outputted into exception.log. In addition, not sure if this is the correct flow (not familiar with Magento 1), but on declined transactions, the order is marked as canceled and on the re-attempt, another order is created. Is this normal? or should re-attempts be made against the first order created?

**Comment by alena-marchenko** [comment]
Hi,

Magento creates an order in "Pending Payment" status before sending request to Authorize.net and then order's status is changed to "Processing" or "Canceled" depending on response from Authorize.net.  In case of error received from Authorize.net customer will see general error only and admin user can find detailed gateway error description.
Please take a look at our [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and do not hesitate to contact us if you have further issues.

**Comment by tigerx7** [comment]
@alena-marchenko Thank you for the followup and clarification on order status flow. However, my issue was a two-part question.

Primarily, I understand it's good to have somewhere in the logs the response from authorize.net. However, I don't think having it being thrown as an exception is the best method for it. Ideally, an exception should be representative of something that's broken or didn't function correctly. We keep an eye on the exception log to spot any fatal errors or issues with the Magento store that may not make it to a report in production.

Having Authorize.net DPM generate an exception for a common expected result (credit card declined) is a bit misleading. Instead of throwing an exception with a stack trace, perhaps the debug log may be a better fit?

**Comment by collinanderson** [comment]
Shouldn't the AVS error be presented to the user?
