### ISSUE TITLE
EU VAT Settings - not showing correct price on PDP

### ISSUE THREAD

**Issue by janssensjelle** [magento/magento2#29942]
When we follow the documentation, we expect the price on the product page/category page to be the same as in the cart. The cart is in this case correct. We set up a different storeview specifically for this, as per the instructions in the documentation.

Example: we got a product with the price 24,75 euros (6%). For Belgian VAT this is correct. For VAT rules in Netherlands, this product should cost 25,45 euros (9%). The cart has the correct price. The product/category page does not. 

In the price index, calculation is also incorrect

### Preconditions (*)

1. Magento version: 2.3.4-p2
2. Follow settings like: https://docs.magento.com/user-guide/v2.3/tax/guidelines-eu.html

### Steps to reproduce (*)
1. Set up everything according to https://docs.magento.com/user-guide/v2.3/tax/guidelines-eu.html
2. Go to PDP/Category page

### Expected result (*)
1. Correct price showing

### Actual result (*)
1. Default value showing 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by janssensjelle** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @janssensjelle. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @janssensjelle, here is your [Magento instance](https://i-29942-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29942-2-4-develop.instances.magento-community.engineering/admin_b4a0](https://i-29942-2-4-develop.instances.magento-community.engineering/admin_b4a0)
Login: `5c893a00` Password: `0fe738587647`
Instance will be terminated in up to 3 hours.

**Comment by janssensjelle** [comment]
Seems to be fixed by applying this: https://github.com/magento/magento2/issues/26014#issuecomment-565699329
