### ISSUE TITLE
test confirmation j status

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29948]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37482` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance
with edition B2B
without extension magento/inventory, magento/magento2-page-builder

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance
with edition B2B
without extension magento/inventory

**Comment by slavvka** [comment]
@magento give me 2.4 instance

**Comment by slavvka** [comment]
@magento give me 2.4.0 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37482` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
