### ISSUE TITLE
Order saving error: 'salesrule_customer' Magento 2.3.x

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#29949]
Hi, we're suddenly having an issue with random customer accounts. We're receiving this error when creating an order on the backend. Any idea what could be causing this!?

### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)

1. Create Order

### Expected result (*)

1. Order Successful

### Actual result (*)

1. Receive error message : Order saving error: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT INTO 'salesrule_customer' ('rule_id', 'customer_id', 'times_used') VALUES (?,?,?)

**Comment by engcom-Oscar** [comment]
Hi @nickpiro, can you please provide more details about this issue? Like do you have any 3rd part extensions installed, do  you have any sales rules created in your instance, details of the customer like customer groups and so on.

**Comment by nickpiro** [comment]
Hi @engcom-Oscar , so I discovered that this seems to have been caused by me disabling a Free Shipping rule based on Customer Group. I made the Free Shipping rule inactive but not deleted. Once I re-enabled it, I was able to place the order. Very odd behavior.

**Comment by engcom-Oscar** [comment]
Hi @nickpiro 

I still can't reproduce this issue on 2.4-develop code. I check it by next scenario:

1. Create Cart Price Rule for specific Customer Group (e.g. Retailer) with Action - Free shipping
2. Create customer and set the same Customer group for him
3. Disable Cart Price Rule in Admin
4. Run cron twice to apply changes in the rule
5. Create order from admin with created customer
As result - order was placed successfully. 

Could you please look and if we missing some steps - update description?
