### ISSUE TITLE
"Magento\PageBuilder\Plugin\Filter\TemplatePlugin" mismatching strict type

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29945]
### Additional information
This issue was originally reported by @Serializator in https://github.com/magento/magento2/issues
Then it was transferred into private repo related to page-builder
After the investigation was found that the issue should be fixed not in page-builder but in CE code.
Quote by @bluemwhitew :
> Attempted to fix this as suggested, but ran into issues where this method is called elsewhere.
I would recommend re-raising this issue in the Magento 2 repository with a view to implementing strict types on the original method.

Due to not possible to transfer issue from private to the public repo, I create a new one. The full discussion and history of original issue in https://github.com/magento/magento2/issues/29945#issuecomment-688991656

### Preconditions (*)
1. Magento 2.3.5-p1 and latest `2.4-develop`
2. Page Builder
### Steps to reproduce (*)
Invoke `Magento\Framework\Filter\Template->filter(...)` with `null` as value
### Expected result (*)
An empty string, at least not a type error if strict types aren't used for the invoked method
### Actual result (*)
> TypeError: Uncaught exception 'TypeError' with message 'Argument 2 passed to Magento\PageBuilder\Plugin\Filter\TemplatePlugin::afterFilter() must be of the type string, null given, called in .../vendor/magento/framework/Interception/Interceptor.php on line 146' in .../vendor/magento/module-page-builder/Plugin/Filter/TemplatePlugin.php:71
### Cause
It is caused by the `Magento\PageBuilder\Plugin\Filter\TemplatePlugin` which uses strict types in the after plugin which does not match with any strict types on the original method.
---
It's kinda a double-edged sword. I think this is a bug because a plugin should match the arguments of the method which it is bound to, on the other side it isn't really a bug as much as not checking the data you pass before invocation.
PHPDocs clearly state that the argument should be a string, which is then in-directly enforced by the strict type in the plugin.
What I rather see is that this type is strictly enforced by the method itself directly, but that would be a backwards incompatible change (and the class is annotated with `@api`).
- Use the null coalescing operator (or an if) to turn `null` into an empty string
- Remove the strict types from the plugin in Page Builder (my personal least favourite)
If you think this isn't a bug and should be closed because it should be the the responsibility of the developer to check their stuff, I kinda agree actually

**Comment by sdzhepa** [comment]
![original_content](https://user-images.githubusercontent.com/3409584/92502748-f20cd500-f1c5-11ea-957c-8ac09c6efae3.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37476` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by o-iegorov** [comment]
Internal team start working in the issue

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37476` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37476` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37476` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by khnaim** [comment]
Hello,

I have the problem on **Magento ver. 2.3.4-p2**, I did not find the patch to apply to fix this problem

Could you give me the link/commit of this patch please ? 

With kind regards

**Comment by atty31** [comment]
Can someone please share the fix or patch for this issue ? Thanks

**Comment by phpdev-m** [comment]
I tried it and it worked for me
`    public function afterFilter(\Magento\Framework\Filter\Template $subject, $result) : string
    {
        return $this->templateFilter->filter((string) $result);
    }`
    in Magento\PageBuilder\Plugin\Filter\TemplatePlugin
