### ISSUE TITLE
Trailing slash for `base_url`

### ISSUE THREAD

**Issue by jkristoffer** [magento/magento2#2994]
I'm using `develop branch - commit 3991d65ea5b4c91b39f130ceadac7e413233ada6`.  I installed using the CLI with `--base-url={{base_url}}` and all the links on the website have a trailing slash at the end of the base URL. 

I checked the `core_config_data` table and found the following record:

```
+-----------+---------+----------+-------------------------------+----------------------------------+
| config_id | scope   | scope_id | path                          | value                            |
+-----------+---------+----------+-------------------------------+----------------------------------+
|         1 | default |        0 | web/unsecure/base_url         | {{base_url}}/                    |
|         2 | default |        0 | general/locale/code           | en_US                            |
|         3 | default |        0 | general/locale/timezone       | Asia/Singapore                   |
|         4 | default |        0 | currency/options/base         | SGD                              |
|         5 | default |        0 | currency/options/default      | SGD                              |
|         6 | default |        0 | currency/options/allow        | SGD                              |
|         7 | default |        0 | general/region/display_all    | 1                                |
|         8 | default |        0 | general/region/state_required | AT,BR,CA,CH,EE,ES,FI,LT,LV,RO,US |
|         9 | default |        0 | catalog/category/root_id      | NULL                             |
+-----------+---------+----------+-------------------------------+----------------------------------+
```

The base_url has a trailing slash appended to it. Is this the expected behavior for the Magento CLI?

I tried omitting `--base-URL` when installing using the CLI and no more trailing slash.

**Comment by jkristoffer** [comment]
The issue seems to be similar to #2149 but there was no follow-up and it got closed

**Comment by veloraven** [comment]
@jkristoffer is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
