### ISSUE TITLE
Propose to make the \Magento\Framework\App\Config\ScopePool::_getScopeCode() public because it is useful to calculate cache keys based on a scope (like \Magento\Framework\App\Config\ScopePool::getScope() does)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2995]
https://mage2.pro/t/359

**Comment by andimov** [comment]
@mage2pro
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
