### ISSUE TITLE
Don't make XML paths private. 

### ISSUE THREAD

**Issue by brideo** [magento/magento2#29951]
### Summary (*)

I don't believe constants should be private as other implementations sometimes need to use them rather than redefining.

### Examples (*)
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\Theme\Block\Html;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\View\Element\Template;
use Magento\Store\Model\ScopeInterface;

/**
 * Html page title block
 *
 * @method $this setTitleId($titleId)
 * @method $this setTitleClass($titleClass)
 * @method string getTitleId()
 * @method string getTitleClass()
 * @api
 * @since 100.0.2
 */
class Title extends Template
{
    /**
     * Config path to 'Translate Title' header settings
     */
    private const XML_PATH_HEADER_TRANSLATE_TITLE = 'design/header/translate_title';  // Why is this hidden? 

    /**
     * @var ScopeConfigInterface
     */
    private $scopeConfig;

    /**
     * Own page title to display on the page
     *
     * @var string
     */
    protected $pageTitle;

    /**
     * Constructor
     *
     * @param Template\Context $context
     * @param ScopeConfigInterface $scopeConfig
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        ScopeConfigInterface $scopeConfig,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->scopeConfig = $scopeConfig; // Can this be gotten from the $context object
    }

    /**
     * Provide own page title or pick it from Head Block
     *
     * @return string
     */
    public function getPageTitle()
    {
        if (!empty($this->pageTitle)) {
            return $this->pageTitle;
        }

        $pageTitle = $this->pageConfig->getTitle()->getShort();

        return $this->shouldTranslateTitle() ? __($pageTitle) : $pageTitle;
    }

    /**
     * Provide own page content heading
     *
     * @return string
     */
    public function getPageHeading()
    {
        $pageTitle = !empty($this->pageTitle) ? $this->pageTitle : $this->pageConfig->getTitle()->getShortHeading();

        return $this->shouldTranslateTitle() ? __($pageTitle) : $pageTitle;
    }

    /**
     * Set own page title
     *
     * @param string $pageTitle
     * @return void
     */
    public function setPageTitle($pageTitle)
    {
        $this->pageTitle = $pageTitle;
    }

    /**
     * Check if page title should be translated
     *
     * @return bool
     */
    private function shouldTranslateTitle(): bool
    {
        return $this->scopeConfig->isSetFlag(
            static::XML_PATH_HEADER_TRANSLATE_TITLE, // Why is this accessed using static if the constant is private?
            ScopeInterface::SCOPE_STORE
        );
    }
}
```

### Proposed solution

* do not make constants private 
* If constants are private, access them through `self::` rather than `static::`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
seem related with issue https://github.com/magento/magento2/issues/29879

**Comment by hostep** [comment]
@brideo means that the const declaration should be public as it's a constant defining an xml path which can be of use to other modules to fetch configuration values. Right now you can't use the const outside of this class and you have to redefine it in your own module, which can be annoying.

I agree that all consts which define an xml path to a configuration should be public so we can easily access those from other modules.
If that really can't happen for some reason, then maybe every module in Magento which has one or more configuration settings should have public method(s) which can be used to fetch the particular configuration setting (but that will be a looooot of work).

**Comment by brideo** [comment]
I am running 2.4.0, which doesn't work because of this exact issue. I assume it can be closed because of #28981 which is this is kind of a of.

**Comment by brideo** [comment]
Actually no sorry I'm wrong, I just looked through the commits. Why are we choosing to make constants unaccessible? They're useful for third party vendors, in fact I always thought it was best practise to access these values using constants?

**Comment by ihor-sviziev** [comment]
Hi @brideo,
Thank you for you report!
Currently we need to make such newly added constants as private for classes marked as `@api` due to backward compatibility.

Example: in some api marked class we’ll add a public constant and you as extension developer will start using it, also you would expect that your code should work fine on earlier magento versions, as you’re using the only the api classes. Unfortunately it will not work as the constant wasn’t present in earlier magento versions.

For newly created classes we should use public instead of private.

I hope I clearly described why it’s done in this way and we can close this issue.

**Comment by ihor-sviziev** [comment]
Hi @brideo,
I believe I clearly described above the issue. The exact case you've described was already fixed in https://github.com/magento/magento2/pull/28797. If you'll find any other - let us know.
