### ISSUE TITLE
Cancel order is not working properly using Magento 2 Rest API

### ISSUE THREAD

**Issue by wgamazonapi** [magento/magento2#29953]
### Preconditions (*)
1. Magento ver. 2.3.1

### Steps to reproduce (*)
1. Configure the postman
2. Make an API call using the below details
API : rest /V1/orders
Request : {"entity": {"entity_id": 89,"status": "canceled","increment_id": "000000074"}}
Method : POST

### Expected result (*)

1.  The order MUST be cancelled and the cancel status should be shown on orders page and  order details details 

### Actual result (*)

1. On orders page status is shown cancelled 
![image-20200902-214307](https://user-images.githubusercontent.com/54639289/92573794-e8599f00-f2a3-11ea-9b9a-5f3c20e4b35c.png)

**2. The order status is showing Pending Status instead of cancelled.** 
![image-20200902-214503](https://user-images.githubusercontent.com/54639289/92574008-2bb40d80-f2a4-11ea-9967-5b40a18f278d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37517` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wgamazonapi** [comment]
Can we expedite it. its been while since last update.

**Comment by amitvishvakarma** [comment]
@magento I am working on it.

**Comment by amitvishvakarma** [comment]
#dmcindia2020

**Comment by amitvishvakarma** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
