### ISSUE TITLE
Order captured in payment gateway but order didn't save into Magento 2

### ISSUE THREAD

**Issue by buituanbg** [magento/magento2#29963]
### Preconditions (*)

1. Magento 2.2.0 - 2.3.5 - 2.3.5-p1 - 2.3.5-p2 - 2.4
2. nginx, Mysql, PHP7.2, varnish, redis
3. Server Intel Xeon E5-2630 V4
CPU: 10 Cores @ 2.2 GHz
1TB SSD (RAID)
64GB RAM

### Steps to reproduce (*)

1. The sales_order_item table got more than 2Gb and my site had about 4-500k orders
2. Customer purchase use credit card or PayPal 
3. This happens with almost payment gateway(Braintree, Authorize.net, PayPal ...)

### Expected result (*)

1. Order have to complete and go to the success page
2. Order captured in Payment Gateway
3. Order saved in database with order detail

### Actual result (*)

1. Order captured in Payment Gateway and returned all information to Magento site
2. Order didn't save in Database
3. Log: 
`main.CRITICAL: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `sales_order_item` (`order_id`, `quote_item_id`, `store_id`, `product_id`, `product_type`, `product_options`, `weight`, `is_virtual`, `sku`, `name`, `description`, `applied_rule_ids`, `additional_data`, `is_qty_decimal`, `qty_backordered`, `qty_invoiced`, `qty_ordered`, `base_cost`, `price`, `base_price`, `original_price`, `base_original_price`, `tax_percent`, `tax_amount`, `base_tax_amount`, `tax_invoiced`, `base_tax_invoiced`, `discount_percent`, `discount_amount`, `base_discount_amount`, `discount_invoiced`, `base_discount_invoiced`, `row_total`, `base_row_total`, `row_invoiced`, `base_row_invoiced`, `row_weight`, `base_tax_before_discount`, `tax_before_discount`, `price_incl_tax`, `base_price_incl_tax`, `row_total_incl_tax`, `base_row_total_incl_tax`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `discount_tax_compensation_invoiced`, `base_discount_tax_compensation_invoiced`, `free_shipping`, `gift_message_id`, `gift_message_available`, `weee_tax_applied`, `weee_tax_applied_amount`, `weee_tax_applied_row_amount`, `weee_tax_disposition`, `weee_tax_row_disposition`, `base_weee_tax_applied_amount`, `base_weee_tax_applied_row_amnt`, `base_weee_tax_disposition`, `base_weee_tax_row_disposition`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"exception":"[object] (Magento\\Framework\\DB\\Adapter\\DeadlockException(code: 1213): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `sales_order_item` (`order_id`, `quote_item_id`, `store_id`, `product_id`, `product_type`, `product_options`, `weight`, `is_virtual`, `sku`, `name`, `description`, `applied_rule_ids`, `additional_data`, `is_qty_decimal`, `qty_backordered`, `qty_invoiced`, `qty_ordered`, `base_cost`, `price`, `base_price`, `original_price`, `base_original_price`, `tax_percent`, `tax_amount`, `base_tax_amount`, `tax_invoiced`, `base_tax_invoiced`, `discount_percent`, `discount_amount`, `base_discount_amount`, `discount_invoiced`, `base_discount_invoiced`, `row_total`, `base_row_total`, `row_invoiced`, `base_row_invoiced`, `row_weight`, `base_tax_before_discount`, `tax_before_discount`, `price_incl_tax`, `base_price_incl_tax`, `row_total_incl_tax`, `base_row_total_incl_tax`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `discount_tax_compensation_invoiced`, `base_discount_tax_compensation_invoiced`, `free_shipping`, `gift_message_id`, `gift_message_available`, `weee_tax_applied`, `weee_tax_applied_amount`, `weee_tax_applied_row_amount`, `weee_tax_disposition`, `weee_tax_row_disposition`, `base_weee_tax_applied_amount`, `base_weee_tax_applied_row_amnt`, `base_weee_tax_disposition`, `base_weee_tax_row_disposition`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) at /home/site/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:585, Zend_Db_Statement_Exception(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `sales_order_item` (`order_id`, `quote_item_id`, `store_id`, `product_id`, `product_type`, `product_options`, `weight`, `is_virtual`, `sku`, `name`, `description`, `applied_rule_ids`, `additional_data`, `is_qty_decimal`, `qty_backordered`, `qty_invoiced`, `qty_ordered`, `base_cost`, `price`, `base_price`, `original_price`, `base_original_price`, `tax_percent`, `tax_amount`, `base_tax_amount`, `tax_invoiced`, `base_tax_invoiced`, `discount_percent`, `discount_amount`, `base_discount_amount`, `discount_invoiced`, `base_discount_invoiced`, `row_total`, `base_row_total`, `row_invoiced`, `base_row_invoiced`, `row_weight`, `base_tax_before_discount`, `tax_before_discount`, `price_incl_tax`, `base_price_incl_tax`, `row_total_incl_tax`, `base_row_total_incl_tax`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `discount_tax_compensation_invoiced`, `base_discount_tax_compensation_invoiced`, `free_shipping`, `gift_message_id`, `gift_message_available`, `weee_tax_applied`, `weee_tax_applied_amount`, `weee_tax_applied_row_amount`, `weee_tax_disposition`, `weee_tax_row_disposition`, `base_weee_tax_applied_amount`, `base_weee_tax_applied_row_amnt`, `base_weee_tax_disposition`, `base_weee_tax_row_disposition`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) at /home/site/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/site/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
`

**This happens randomly and not easy to reproduce my site got once a week or twice a week.**

**Comment by buituanbg** [comment]
@magento I am working on this

**Comment by buituanbg** [comment]
@magento add to contributors team

**Comment by buituanbg** [comment]
@magento I am working on this

**Comment by engcom-Oscar** [comment]
Hello @buituanbg 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento 2.4 installation and confirm?

**Comment by engcom-Delta** [comment]
@buituanbg thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Generate 4k orders
![image](https://user-images.githubusercontent.com/51681379/105339555-77c57600-5be5-11eb-955b-cdb16e45e45f.png)

- Configure PayPal Payflow Pro
- Place order with  Credit Card (Payflow Pro)/PayPal Credit (Payflow Express Bml)/PayPal Express Checkout Payflow Edition payments methods

**Result:**
:heavy_check_mark: Order is placed, no errors in logs.
![Peek 2021-01-21 12-24](https://user-images.githubusercontent.com/51681379/105339924-e6a2cf00-5be5-11eb-942a-ce638ea599c3.gif)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.

**Comment by kanevbg** [comment]
To reproduce the problematic scenario the table `sales_order_item` should be locked during order placement, which likely happens during concurrency

**Comment by dbashyal** [comment]
The same issue is in version 2.4.3-p3 cloud as well. We have received payments but we can't find the orders. Lots of orders are missing so getting disputes.

**Comment by iboCloudlab** [comment]
having the same issue on 2.4.3-p3. Any findings on the issue?

**Comment by arunkbps** [comment]
I have been experiencing with order placement on Magento 2.4.6-p1 platform. This issue occurs sometimes, happening once a month or week.

Upon thorough investigation, I have discovered that the problem arises specifically when a deadlock issue occurs during the order placement process. Consequently, while some orders are successfully placed, there are instances where orders fail to be processed due to deadlock error.

**Comment by shane-clickingmad** [comment]
Why is this closed?

**Comment by dbashyal** [comment]
There should be some kind of queuing system for failed orders, so they are retried if we have already received payment.
