### ISSUE TITLE
product qty decimal value not update on cart page 

### ISSUE THREAD

**Issue by darpanpatel2018** [magento/magento2#29969]
dear sir,
I have used 2.3.5-p1 version. and when I was select qty increment in decimal value after that I added product in add to cart after that I was trying to update product qty in decimal value that time one message created ( please enter valid value).
for example, I have added 1.2 product qty and after that, I tried to update 1.5 that time not updated qty value.

_Originally posted by @darpanpatel2018 in https://github.com/magento/magento2/issues/29192#issuecomment-674974796_

**Comment by krishprakash** [comment]
Hi @darpanpatel2018. Kindly update all necessary details precondition,steps to reproduce, expected and actual results as per issue reporting guidelines
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks!!

**Comment by krishprakash** [comment]
Hi @darpanpatel2018. 
Feel free to reopen the issue once you update all the details as per issue reporting guidelines 
Thanks!!
