### ISSUE TITLE
Wrong order status showing in case customer has ordered 3 qty of one product, and admin invoiced2 refunded 1,shipped 1 and cancelled 1

### ISSUE THREAD

**Issue by bhanu-webkul** [magento/magento2#29973]
### Preconditions (*)

1. magento v 2.4.0
2.

### Steps to reproduce (*)

1.place an order of 3 qty of any product, create invoice for 1 qty from admin then generate refund for that 
2.then again create invoice for 1 qty and do shipment
3.then cancel the order
like this - https://prnt.sc/uepp9g 

### Expected result (*)

1. order status should be completed in this situation
2.

### Actual result (*)

1.showing processing - https://prnt.sc/uepbdj
2. If it is correct then how,please explain 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@bhanu-webkul Please share magento version in issue description 
also try to reproduce the same on magento instances you can refer to [this](https://github.com/magento/magento2/issues/29973#issuecomment-690026511)

**Comment by bhanu-webkul** [comment]
@shikhamis11 
Magento version is 2.4.0

**Comment by bhanu-webkul** [comment]
@magento  give me 2.4-develop instance to reproduce the issue

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37573` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
Hi @engcom-Oscar 
as per the issue description I created an order with one product with 3 quantity and followed further steps 
what I got in the end Please check screenshot 
![image](https://user-images.githubusercontent.com/25526037/92919922-fe579300-f44e-11ea-83cd-e5a4891ea3e8.png)

As I think the Invoiced Item can not be **cancelled**  so I think the Current **Item** as well as **Order status** is correct. 
Can you please share your explanation too why it isn't correct

**Comment by magulin** [comment]
@magento-engcom-team Which version is this fixed in? It has no references to any commits.
