### ISSUE TITLE
Unable to synchronize all media files because sync process run only of 5 minutes.

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#29975]
### Preconditions 
1. Magento 2.3.5-p2
2. Have around 30.000 images and 75 GB of images data stored in Magento
3. Ticket #29138 is related but was closed. 

### Steps to reproduce 
1. Login into Magento admin 
2. Go to Stores > Settings > Configuration
3. Expand 'Advanced' section and choose 'system'
4. Select 'Storage Configuration for Media' and choose 'Database' from the "Media Storage' dropdown
5. Click the synchronise button

### Expected result 
1. Media synchronises to the database

### Actual result
1. Timeout occurs after 5 minutes.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment]
Issues should not be closed automatically. Posting comment to keep it active.

**Comment by dverkade** [comment]
Issues should not automatically close. Posting this comment to keep it active.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42618` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by xtremevision** [comment]
It is happening also on v 2.4.6 with 1.55Gb of images uploading to R2 CloudFlare. I simply press the button to synchronize, watch the log file and see files uploading, everything is running fine - but at some point the exception log throw an error and the ajax sync status disappears. The error is:

[2023-06-26T00:02:17.567277+00:00] main.CRITICAL: Magento\Framework\Exception\LocalizedException: The timeout limit for response from synchronize process was reached. in htdocs/vendor/magento/module-media-storage/Controller/Adminhtml/System/Config/System/Storage/Status.php:86
Stack trace:
#0 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status->execute()
#1 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->___callParent()
#2 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->Magento\Framework\Interception\{closure}()
#3 htdocs/generated/code/Magento/MediaStorage/Controller/Adminhtml/System/Config/System/Storage/Status/Interceptor.php(23): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->___callPlugins()
#4 htdocs/vendor/magento/framework/App/Action/Action.php(111): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->execute()
#5 htdocs/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#6 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#7 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->___callParent()
#8 htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->Magento\Framework\Interception\{closure}()
#9 htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#10 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->Magento\Framework\Interception\{closure}()
#11 htdocs/generated/code/Magento/MediaStorage/Controller/Adminhtml/System/Config/System/Storage/Status/Interceptor.php(32): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->___callPlugins()
#12 htdocs/vendor/magento/framework/App/FrontController.php(245): Magento\MediaStorage\Controller\Adminhtml\System\Config\System\Storage\Status\Interceptor->dispatch()
#13 htdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#14 htdocs/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#15 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#16 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#17 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#19 htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#20 htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#21 htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#22 {main} {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The timeout limit for response from synchronize process was reached. at htdocs/vendor/magento/module-media-storage/Controller/Adminhtml/System/Config/System/Storage/Status.php:86)"} []

Using php 8.1 and Magento 2.4.6 CE.

**Comment by engcom-Bravo** [comment]
Hi @dverkade,

Thanks for your reporting and collaboration.

As per the Magento devdocs https://experienceleague.adobe.com/en/docs/commerce-admin/config/advanced/system#storage-configuration-for-media The database media storage method has been deprecated as of Adobe Commerce and Magento Open Source

Hence we are closing this issue.

Thanks.
