### ISSUE TITLE
magento connect manager

### ISSUE THREAD

**Issue by amitmca09** [magento/magento2#2997]
magento connect manager not showing for ver 2.0 in admin URL

**Comment by GMPFashion** [comment]
I have the very same issue. Magento Connect is not on the System > Extensions menu.

**Comment by bmishra5bestincity** [comment]
I have same problem

**Comment by ghost** [comment]
There is no Magento Connect Manager in 2.0; it's replaced by the [Component Manager and System Upgrade[(http://devdocs.magento.com/guides/v2.0/comp-mgr/bk-compman-upgrade-guide.html) utilities.

To run it, go to **System** > **Web Setup Wizard**. Let us know if this solves the issue.

**Comment by bmishra5bestincity** [comment]
thanks Steve, But I have tried to install new extension, I think I will see new purchase in component manager , but nothing happened and all extension support upto Magento 1.9.2 , Is there any help how to install a extension from marketplace

**Comment by ghost** [comment]
@cymbalrare I believe we're working on a communication about this now. See if [this](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/dev_add-update.html) works for you and let us know.

**Comment by bmishra5bestincity** [comment]
hi xcomSteveJohnson , Thank you... But when I try as mentioned in your link , I get this error.

Problem 1
    - The requested package **vendor**/**module** could not be found in any version, there may be a typo in the package name.

For example I try to install this  
composer require ASchroder/SMTPPro:2.0.7 

Only success I get with this 
composer require ashsmith/magento2-controller-module:2.0.*

Is there any way to install module extension which is compatible for 1.92 , because I found no where magento 2 module or extension
 only few in https://www.magentocommerce.com/magento-connect/magento-2

**Comment by omerts** [comment]
same problem would be glad to be able to install older extension on magento 2 (if that is possible in any way), using magento connect's extension keys

**Comment by tanya-soroka** [comment]
Hello, for the purchasing and installation extensions, please use https://marketplace.magento.com/. 
if you want to submit the extension, please send email to marketplace@magento.com and team will be able to send you instruction.

**Comment by agjalpm** [comment]
This is really embarrassing me.

Can anybody tell me how to install/add an extension from _extension key_ in Magento 2 stepwise?

**Comment by liquidia** [comment]
they made it even more complex. hey magento core team here is simple suggestion make it simple everyone who uses it is not a hardcore programmer .. there is something to learn from WordPress i.e simplicity.

**Comment by piotrekkaminski** [comment]
@cymbalrare Magento 1 extensions are not compatible with Magento 2 and cannot be installed. You can buy/register Magento 2 extensions on https://marketplace.magento.com/ and they will show up in the component manager.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/magento-connect-manager/idi-p/44757).
