### ISSUE TITLE
[GraphQl bug] Couldn't re-order in in different store

### ISSUE THREAD

**Issue by huykon** [magento/magento2#29974]
### Preconditions (*)

**1. Create order by graphql (pwa-studio)
2. Magento 2.4.0**

### Steps to reproduce (*)

I have 2 store (English, Arabic).
1. Login as customer account
2. Create an order at English storeview
3. After order complete, switch to Arabic storeview then navigate to: Customer account -> order history
4. Try to re-order item.
5. I received the message: **_Order number "%1" doesn't belong to the current customer_**

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @huykon,

We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know if this issue is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @huykon,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
