### ISSUE TITLE
Copy & Pasting text from multiple page builder elements on a site build with page builder, into a text node, leads to failed saving and infinite load screen, after attempting to save

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29977]
### Preconditions (*)

1. Enterprise 2.4.0

### Steps to reproduce (*)

1. Create a new CMS site (test-foo) by using the page builder. Create 4 columns like seen here:

![image](https://user-images.githubusercontent.com/16349349/92716820-a1c97a80-f35f-11ea-8d04-1cc88b511813.png)

2. Save.
3. Open your CMS site in the frontend in another tab, the one which you created earlier (test-foo)
4. Mark the text like seen in the following screenshot and copy it:
![image](https://user-images.githubusercontent.com/16349349/92717075-f4a33200-f35f-11ea-897d-e6df1943b8da.png)
5. Create another CMS site (test-bar). Add a column and put a text node inside it.
6. Paste the content which you copied in step 4, into the text node (into tinyMCE WYSIWYG editor).
7. Save

### Expected result (*)

1. It should save.

### Actual result (*)

1. A load spinner appears and stays forever
2. The following error is getting logged into the developer console of the browser:

**[ERROR] Page Builder was rendering for 5 seconds without releasing locks.**

### Additional information
1. Repeat steps, but don't save this time (dont execute step 7).
2. Hover over the text note and click on the configure icon (cog).
3. Inspect the HTML code
4. You will see that the HTML contains alot of page-builder stuff, which obviously causes the bug.

```
<div class="pagebuilder-column-group" data-content-type="column-group" data-grid-size="12" data-element="main">
<div class="pagebuilder-column" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main">
<div data-content-type="text" data-appearance="default" data-element="main">
<h2>Was sind RAL-Farben?</h2>
</div>
</div>
<div class="pagebuilder-column" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main">&nbsp;</div>
</div>
<div class="pagebuilder-column-group" data-content-type="column-group" data-grid-size="12" data-element="main">
<div class="pagebuilder-column" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main">
<div data-content-type="text" data-appearance="default" data-element="main">
<p>RAL ist ein europäisches, weltweit genutztes Farbabstimmungssystem, das Farben für Anstriche, Beschichtungen und Kunststoffe definiert. Sie haben Fenster oder Türen in ausgefallenen Farben und brauchen die passenden Insektenschutz-Profile, Alu-Außenfensterbänke oder Zubehörteile? Kein Problem, teilen Sie uns einfach den normierten RAL-Farbcode ihrer benötigten Produkte mit und wir beschichten diese passend für Ihre Anforderungen.</p>
</div>
</div>
</div>
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @Eddcapone , thank you for your report. I couldn't reproduce this issue on the latest 2.4-develop branch of Magento. May please provide more details in the description, please or recheck on 2.4-develop branch.

**Comment by Eddcapone** [comment]
Hello @engcom-Oscar, I already gave all possible details. I will try it myself on a fresh instance.
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
@engcom-Oscar , the @magento-deployment-service bot gave me a Community Editon, I need Enterprise to test it.

**Comment by sdzhepa** [comment]
Hello @Eddcapone 
fyi: @engcom-Oscar 

Due to the response from the internal page-builder team - this bug was already fixed and delivered. It should be available in **2.3.6** and **2.4.1**. It was done in the scope of jira ticket `MC-35220` if you have access to the Commerce code you can use this number to find commits.

Also, let me remind that
[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by Eddcapone** [comment]
Where can I find the repository for Enterprise? And how can I get permission?

**Comment by sdzhepa** [comment]
To have access to the repository for Enterprise need to be a participant of [Magento Solution Partners Contribution Program](https://github.com/magento/magento2/wiki/Magento-Solution-Partners-Contribution-Program)
