### ISSUE TITLE
Installation problem...

### ISSUE THREAD

**Issue by NenadTrajkovic** [magento/magento2#2998]
Hello,
I am a novice in programming, therefore I'm sorry for bothering you with my beginner's problems.
I have problem that is repeating constantly, where do I wrong?! Thank you! 

[RuntimeException]
  Failed to clone git@github.com:zendframework/Component_ZendStdlib.git via git, https, ssh protocols, aborting.
- git://github.com/zendframework/Component_ZendStdlib.git
  Cloning into 'C:\xampp\htdocs\magento2-master\vendor\zendframework\zend-stdlib\Zend\Stdlib'...
  fatal: remote error:
    Repository not found.
- https://github.com/zendframework/Component_ZendStdlib.git
  Cloning into 'C:\xampp\htdocs\magento2-master\vendor\zendframework\zend-stdlib\Zend\Stdlib'...
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/zendframework/Component_ZendStdlib.git/'
- git@github.com:zendframework/Component_ZendStdlib.git
  Cloning into 'C:\xampp\htdocs\magento2-master\vendor\zendframework\zend-stdlib\Zend\Stdlib'...
  Host key verification failed.
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.

**Comment by mrkhoa99** [comment]
When installing Magento 2, did it ask you the personal Github access token? You can read more here:http://www.appseconnect.com/how-to-install-magento-2-on-xampp-server-localhost/

**Comment by NenadTrajkovic** [comment]
It didn't, it just run installation and after few minutes stuck... I have created tokens, messing with gitbash, zend frameworks, xampp, composer.

**Comment by NenadTrajkovic** [comment]
I did it, thank you mrkhoa99!

**Comment by jamescowie** [comment]
@NenadTrajkovic This sounds more like you have resolved the issue as well as being more of a question than bug report. If you require more help please use the Magento forums so we can offer more help and assistance.
