### ISSUE TITLE
Some search terms return no-results in some strange cases

### ISSUE THREAD

**Issue by aurensistemas** [magento/magento2#29999]
### Preconditions (*)

1. Magento 2.3.2
2. Own products with own attributes.
3. Search configuration:
![imagen](https://user-images.githubusercontent.com/70579283/92918992-33a0b880-f430-11ea-93ff-cf2ccff0311a.png)
4. Attributes that are visible for search: name, sku, description and some others.
5. Using a Porto Theme 3.1.8 (modified)

### Steps to reproduce (*)

1. Search "G7" in the top right search bar.
2. No results are found.
3. Search "G7 led" or "Bombilla G7" and some results are shown.
4. Seach "G" and some results are shown.

### Expected result (*)

1. "G7" search may show some results.

### Actual result (*)

1. No results for that seach is returned
![imagen](https://user-images.githubusercontent.com/70579283/92918207-80d05a80-f42f-11ea-8d5c-cd49241a52e2.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment]
Hello @aurensistemas 

Thank you for your report.
Unfortunately, we are not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release.
Could you please recheck it on clean Magento installation and confirm?

![image](https://user-images.githubusercontent.com/60198413/93323461-57437480-f81d-11ea-8b8e-614cece752fb.png)
