### ISSUE TITLE
The header checkbox is selected on all remaining pages

### ISSUE THREAD

**Issue by soleksii** [magento/magento2#29996]
### Preconditions (*)

1. Magento 2.4-develop
2. Php v.7.3

### Steps to reproduce (*)

- Have at least 2 pages with customers in the grid

1. Go to Admin->Customers->All Customers;
2. Select all records on the current page by clicking the header checkbox;
3. Go to the second page;

### Expected result (*)

:heavy_check_mark: On the next page, the title checkbox should be empty 

![2020-09-11_13-10](https://user-images.githubusercontent.com/44244273/92909952-4915e280-f430-11ea-9d88-dadd852b6565.png)

### Actual result (*)

:heavy_multiplication_x: You will see that the header checkbox is selected on all remaining pages

![after2](https://user-images.githubusercontent.com/51679138/75232144-5f738e00-57bf-11ea-910c-7281ba7aeb9f.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @stoleksiy,
Verified this issue on latest Magento 2.4 instance with above steps and actual result.

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37595` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy, @sarfarazbheda. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37595` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
