### ISSUE TITLE
Frontend product view undesirable wraps the 5-digit prices with a space as a thousand separator

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3000]
![](https://mage2.pro/uploads/default/original/1X/4acb6069aab2122d354b744fbb90cde8a5214c2d.png)

**Comment by ktomk** [comment]
isn't that a representation issue that can be easily (and properly) handled in CSS?

**Comment by MomotenkoNatalia** [comment]
@dfediuk  Thanks for reporting this issue! Internal ticket MAGETWO-48236

**Comment by MomotenkoNatalia** [comment]
@dfediuk Internal ticket MAGETWO-48236 is closed and delivered to mainline. Please let us know if you still have an issue.
