### ISSUE TITLE
Swagger UI > Content Security Policies > [Report Only] Refused to load the image ...

### ISSUE THREAD

**Issue by lfluvisotto** [magento/magento2#30015]
### Preconditions (*)

Branch 2.4-develop

### Steps to reproduce (*)

1. Open swagger page > http://<magento_host>/swagger
2. On the browser it'll see some error messages: [Report Only] Refused to load the image ...

![image](https://user-images.githubusercontent.com/535626/92986208-92494f00-f48f-11ea-95b1-df46a34a8c07.png)

### Expected result (*)

Without messages: [Report Only] Refused to load the image ... on browser console.

### Actual result (*)

With messages: [Report Only] Refused to load the image ... on browser console.

### Pull Request

#30016 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lfluvisotto** [comment]
@magento I'm working on it

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37670` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Hi @lfluvisotto,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshot.


<img width="1427" alt="Screenshot 2024-05-29 at 11 42 46" src="https://github.com/magento/magento2/assets/51680745/3dc8c1c5-a3b8-41c7-9cc3-fc0b52613bf4">



There were no errors in the console.

Hence We are closing this issue.

Thanks.
