### ISSUE TITLE
Modal content with bad message format for newlines

### ISSUE THREAD

**Issue by lfluvisotto** [magento/magento2#30013]
### Preconditions (*)

Branch 2.4-develop

### Steps to reproduce (*)

1. Authenticate / log in admin / backend
2. Go to : System > Permissions > User  #Roles
3. Select any role
4. Click on : "Roles Users" on left sidebar
5. Click on any user listed on the grid

![image](https://user-images.githubusercontent.com/535626/92984998-08948400-f485-11ea-8921-058aad20ce26.png)

### Expected result (*)

Modal content with good message format for newlines.

![image](https://user-images.githubusercontent.com/535626/92985011-21049e80-f485-11ea-95fb-69b77246c379.png)

### Actual result (*)

Modal content with bad message format for newlines.

![image](https://user-images.githubusercontent.com/535626/92985005-0df1ce80-f485-11ea-9822-fb3e488f2c05.png)

### Pull request

#30014

---

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lfluvisotto** [comment]
@magento I'm working on it

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37629` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto. Thank you for your report. 
The issue has been fixed in magento/magento2#30014 by @lfluvisotto in 2.4-develop branch
Related commit(s):
 - [de91c2ba7a3449858e9f464c720e3a3870797c7a](https://github.com/magento/magento2/commit/de91c2ba7a3449858e9f464c720e3a3870797c7a)

The fix will be available with the upcoming 2.4.2 release.
