### ISSUE TITLE
Quote collectTotals() may be easily looped during order place

### ISSUE THREAD

**Issue by michael1986** [magento/magento2#30029]
### Summary (*)

The issue in the project appeared since Magento 2.3.4 where the following code was added:
https://github.com/magento/magento2/commit/29f0417a28ad71d4dd42485b88da125ccd960a2e
This leads to an unpredictable behavior when calling *getQuote()* method from **vendor/magento/module-checkout/Model/Session.php:235** can trigger collecting of totals inside already run collection process and as a result, we get 2 times re-collected totals with its attendant problems.

I had the issue with Gift Cards in my project, the Gift Card balance is validated twice and totals are not validated properly the second time throwing an exception to the front-side, but this issue also can be easily introduced unconsciously (or by 3-rd party module) just getting a quote in an inappropriate moment.

### Examples (*)

1. Click on the final button "Place Order" on Checkout.
2. During next steps, we are looking in code.
3. Saving payment info is run:
`$this->savePaymentInformation($cartId, $email, $paymentMethod, $billingAddress);`
at **vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php:93**
4. Quote totals flag is reset:
`$quote->setTotalsCollectedFlag(false);`
at **vendor/magento/module-quote/Model/PaymentMethodManagement.php:56**
5. Collecting of totals is run:
`$quote->collectTotals();`
at **vendor/magento/module-quote/Model/Quote/Payment.php:187**
6. During collecting of totals, any call of
`$this->checkoutSession->getQuote()`
inside plugins, observers or any other place leads to re-collecting of totals again as **totals_collected_flag** is still false in Quote data meaning that there is no possibility of any quote modification without a workaround.

\* Please note, Quote has not been loaded yet in **vendor/magento/module-checkout/Model/Session.php** during this flow.

### Proposed solution

Quick workaround can be:
1. Create an Observer for event `sales_quote_collect_totals_before`
2. Add the following code to the Observer.
```php
    /**
     * @param Observer $observer
     */
    public function execute(Observer $observer)
    {
        $observer->getEvent()->getQuote()->setTotalsCollectedFlag(true);
    }
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gabrieldagama** [comment]
Hi @michael1986, thanks for your report. I believe if you are using a plugin or observer that will be running during the `collectTotals()` you should get the quote from the `$subject` or the `$event` instead of getting from the session, you are right, the scenario described will cause problems.

I believe the proposed solution may cause other problems, and possibly the `collectTotals()` not being run at all, since you set a flag that the totals have been collected before that actually happens. A solution for this would be possibly a bigger refactor on that process. 

I will be closing this issue, but please, feel free to reopen it anytime. I'm happy to further discussion if needed.

Thanks!

**Comment by sufyaniksula2** [comment]
Is there a good workaround if we want to load quotes in plugin. I am using an after plugin for `Magento\Shipping\Model\Rate\Result::getAllRates()` and need to load quote there. 

@michael1986 solution of event observer is working for me but I would like to know if there is a better workaround just in case.

**Comment by hostep** [comment]
Another way to workaround this problem in case you can't get the quote from the `$subject`, is to fetch the quote id from the session, then load the quote using a QuoteFactory. That way it also circumvents an infinite loop.

**Comment by ahsan-horani-folio** [comment]
The right solution is to load quote by quote repository and then perform any actions and perform collectTotals()

If you are getting quote from session, it will create problems for you. See examples below

`// Load the full quote by ID to ensure we’re working with the most up-to-date data
        $quote = $this->checkoutSession->getQuote();
        $quoteId = $quote->getId();
        $quote = $this->quoteRepository->get($quoteId); // Reload the full quote from the repository`

And then do this for recalculation and saving quote

` // Collect totals to update the cart with the prices of all items, including add-ons
            $quote->collectTotals();

            // Save the quote to ensure all changes are persisted
            $this->quoteRepository->save($quote);`
