### ISSUE TITLE
How to get billing address and shipping address in Magento 2 Invoice API?

### ISSUE THREAD

**Issue by Gagan557** [magento/magento2#30024]
Preconditions
Magento 2.3.5
Steps to reproduce
Method: Get
Url: http://127.0.0.1/jaipur/rest/V1/invoices/1

Any options to get billing address and shipping address in magento2 rest api. I want to get billing address and shipping address in invoice api.
Method: Get
Url: http://127.0.0.1/jaipur/rest/V1/invoices/1

**Comment by krishprakash** [comment]
Hi @Gagan557. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchang](https://magento.stackexchange.com/)e or [community forum](https://community.magento.com/) for general discuss about this topic
