### ISSUE TITLE
Extra headers X-XSS-Protection, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options, etc

### ISSUE THREAD

**Issue by magenx** [magento/magento2#3002]
X-XSS-Protection
X-Frame-Options
Strict-Transport-Security
X-Content-Type-Options

please remove these headers from magento core. 
keep it only in server config, like htaccess httpd.conf and nginx

these headers must be set at server level not application...

**Comment by veloraven** [comment]
@magenx is this issue still actual?
If it is please describe it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
