### ISSUE TITLE
Magento 2 table rate works on cart page but not on checkout page

### ISSUE THREAD

**Issue by Xaviera7** [magento/magento2#30041]
### Preconditions (*)

1.magento 2,3.4
2.

### Steps to reproduce (*)

When I check the shipping via table rate for products ordered in the cart page in my magento 2.3.4 site, it comes out fine but on the checkout page, I get the errors in the image below.
I have reviewed the table rates and the configuration , all checks out fine. the cart rules are all fine.

In the checkout page, when I insert the post code and the rest of the address fields, I keep getting the same error for both the FLAT RATE and TABLE RATE.

### Expected result (*)
i exxpect the table rate to function in the checkout page as well

### Actual result (*)

1.   see image below
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force user
![Capture table rate Xi](https://user-images.githubusercontent.com/30527362/93111242-3dcfea80-f6ae-11ea-8c5d-f65b452cddea.JPG)
s to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Xaviera7** [comment]
Please assist

**Comment by Stepa4man** [comment]
@Xaviera7 seems like you use custom checkout. Please check that this error can be reproduced on Vanilla Magento instance.
I can recommend asking the custom checkout module provider about this issue.
In case if you are sure it's reproducible with Vanilla Magento - please provide more info about what table rates do you use.
