### ISSUE TITLE
Creating Custom/New theme is really confusing 

### ISSUE THREAD

**Issue by pankaj-asp** [magento/magento2#3004]
Hello All,

Is it me only or someone else also found creating new theme in Mag2 confusing?

I followed everything as shown in official docs but still not able to get a new/custom theme.

Is it advisable to copy paste Magento/Blank theme > to Mytheme/Blank-new, of-course I will change the name in theme.xml and registration.php?

 I need to make adjustment in header.phtml need to add some div, need to remove others, I tried creating all of them folder-wise but nothing helped, is there any step by step tutorial? 

What is the exact way to create a new theme in magento2?

**Comment by alankent** [comment]
Not necessarily helpful right now, but I am working on a book for CSS/Less and HTML aspects of themes. It has lots of little working examples to copy. Probably 70% done. (This is s private after work project, I am guessing a month off release - but no guarantee.) Some of this is forcing internal discussions to get clearer external communication about the model of themes and less. I might try a blog to get some concepts out faster to help.

**Comment by pankaj-asp** [comment]
Thanks for reply @alankent still how should I create a new theme,the structure which is shared on internet is really confusing, just curious how come everybody is making new theme and I am messing with folders here :(

I was trying to override templates, I copied them into my theme folder, but they all are still coming from vendor folder.

is that normal?

**Comment by alankent** [comment]
Have you looked through https://github.com/magento/magento2-samples/tree/master/sample-module-theme? 

But I have also found the trickiest thing myself to work out is the right path name to use in a module vs theme as they are a little different. I would love to see a debug flag or similar to show the exact list of paths tried to locate a file, just to make it a bit clearer. (Yes, I am chief architect, but we have a backlog we work through so I don't get every change I want done either! ;-). Or a CLI commands...

**Comment by pankaj-asp** [comment]
Hello @alankent 

Thanks for your reply, I am trying to grab everything.

However this is my new theme structure.
but this never shows up, and in-fact it shows error of "
![theme-pro](https://cloud.githubusercontent.com/assets/16722742/12370648/9dbfd360-bc3e-11e5-8a75-b4a8edcf4a64.jpg)

Autoload error

'frontend/Magento/blank' component already exists
"

I must be doing something silly :(

**Comment by mrkhoa99** [comment]
Hello,

You should check your _registration.php_, should be use _frontend/flo/fa_

<pre>
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::THEME,
    'frontend/flo/fa',
    __DIR__
);
</pre>

**Comment by pankaj-asp** [comment]
@mrkhoa99 I am using the same.

**Comment by pankaj-asp** [comment]
@mrkhoa99 If I delete the 'blank' theme from Magneto > blank the errors goes away and I can see the home page of luma theme. though it is not there in frontend Magento folder, its coming from vendor folder.

So I just need to make some changes in header/footer and need to change the entire design, what should I do, there is no phtml files I have in my theme folder, it is taking from parent but I want this to take everything from my theme folder, not from any parent folder. 

I am so lost now, hope above make sens.

**Comment by mrkhoa99** [comment]
@pankaj-asp 

You take a look two Magento themes _blank_ and _luma_: 
+_vendor/magento/theme-frontend-blank_
+_vendor/magento/theme-frontend-luma_

If you want to change the entire design, you can copy templates and layouts from _blank_ or _luma_ to your custom theme. For example: you can copy all files under _vendor/magento/theme-frontend-blank/Magento_Banner_ to your custom theme _app/design/frontend/flo/fa/Magento_Banner_

**Comment by alankent** [comment]
You should never delete the "blank" theme that we provide. Rather, in most circumstances you should inherit from it instead.

Generally I would also not recommend copying the existing themes and editing, for the same reason. If you are going to inherit from blank then your new theme should only contain things that are different to blank. So copying the blank theme is somewhat counterproductive. If you have not done so already, I would recommend reading through the devdocs.magento.com "Frontend Developer Guide". If that is not sufficient, please visit the Magento forums on magento.com.

Please note, this area on GitHub is intended for bug reports to the code base. General requests for guidance should be made in the Magento forums. You can also consider contacting Magento University for training. I believe there is already on online course for Magento 2 if you cannot make in person training.

**Comment by pankaj-asp** [comment]
Okay @alankent I am moving to support forums, thanks for your reply @mrkhoa99  thanks :)

**Comment by pankaj-asp** [comment]
@mrkhoa99 

I have seen the path from template hint and it says below

vendor/magento/module-theme/view/frontend/templates/html/header.phtml

I copied paste the same on my theme which is like this 

app/frontend/flo/fa/module-theme/view/frontend/templates/html/header.phtml

I also tried 
app/frontend/flo/fa/view/frontend/templates/html/header.phtml

but still the path is coming from 

vendor/magento/module-theme/view/frontend/templates/html/header.phtml

**Comment by mrkhoa99** [comment]
Hello,

You try _app/design/frontend/flo/fa/Magento_Theme/templates/html/header.phtml_
Read more here: _http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/bk-frontend-dev-guide.html_

**Comment by pankaj-asp** [comment]
@mrkhoa99 thanks, still not coming from theme folder, I made changes in vendor one that is why it was showing :(

**Comment by mrkhoa99** [comment]
We should follow @alankent guide: 
"Please note, this area on GitHub is intended for bug reports to the code base. General requests for guidance should be made in the Magento forums. You can also consider contacting Magento University for training. I believe there is already on online course for Magento 2 if you cannot make in person training."
Please close this issue and move to support forum.

**Comment by SyedMuneebb** [comment]
It is highly recommended to create a custom theme rather than editing core files. Here's a step by step guide on it: https://magenticians.com/create-custom-theme-magento-2/
