### ISSUE TITLE
Delivery Methods Missing from User Roles

### ISSUE THREAD

**Issue by Vishrootways** [magento/magento2#30053]
**Preconditions:**
1. Magento 2.4.0

**Steps to reproduce**
1. Login to the Magento admin
2. Go to SYSTEM > Permissions > User Roles
3. Add/Edit Role.
4. Go to "Role Resources" from left side tab.
5, Select "Custom" from "Resource Access" drop down.

**Expected result**
1. "Delivery Methods" should be display under the Resources and admin can creates a user role to allows the access of "Delivery Methods" ("Shipping Methods" before 2.4.0) page only.

**Actual result**
1. "Delivery Methods" is missing under the Resources. "Shipping methods section" is there but if we checked it and save the role, it will not allow the access of Delivery Method or Shipping Method page to the admin user in which this Role is assigned.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @Vishrootways & @sdzhepa,
After the update the admin roles permission I can't able to access the default admin configuration and not able verify the issue.
See attached the screenshot:
![image](https://user-images.githubusercontent.com/24711761/93425326-5c64fa00-f8d7-11ea-8751-464d40957d16.png)

@sdzhepa - Can you please verify this issue on your end Or Allow to edit the admin user permission?

Thanks.

**Comment by mam08ixo** [comment]
This is an MSI bug: https://github.com/magento/inventory/issues/3298
