### ISSUE TITLE
Sorry, but something went wrong When order by braintree

### ISSUE THREAD

**Issue by neulhoangtran** [magento/magento2#30051]
### Preconditions (*)

1. got "Sorry, but something went wrong" message when order by braintree

### Steps to reproduce (*)

1. When i create an order with braintree payment i got "Sorry, but something went wrong" message https://prnt.sc/uhjcko
2.

### Expected result (*)

1. order success

### Actual result (*)

1. https://prnt.sc/uhjcko 
2.

---
please help me with this issues. i installed on other servers , it normally works

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @HoangTN96,
Braintree Payment method is not available on Default Magento 2.4 Instance so not able to verify this issue.
Thanks.

**Comment by HoangTN96** [comment]
Thank @ajijshekh123 
i've fixed this issues. the reason from my client inputted an incorrect field on backend 
![image](https://user-images.githubusercontent.com/47875208/93730396-9cd3b900-fbf2-11ea-92bc-d27ae2d65c83.png)
Thank for your support.
