### ISSUE TITLE
proxy_­fcgi:­error  when try to add new product with PHP7

### ISSUE THREAD

**Issue by tcmouse** [magento/magento2#3005]
While saving the new product in admin, I am getting the  error Failed to read FastCGI header in the apache error logs was appending with PHP version 7.0.1 installed.

Show in the browser
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Show in the error log
[Fri Jan 15 09:10:23.705975 2016] [proxy_fcgi:error] [pid 17053:tid 140323109947136] [client 0.0.0.0] AH01067: Failed to read FastCGI header, referer: http://www.xxxxxxxxxxxxxxxxxx.com/admin/catalog/product/new/set/4/type/simple/key/8119da20410415e9f9c3e1258b9f74e7f44626b5df7a91b73930d9c48d3081e/
[Fri Jan 15 09:10:23.706004 2016] [proxy_fcgi:error] [pid 17053:tid 140323109947136](104)Connection reset by peer: [client 0.0.0.0] AH01075: Error dispatching request to : , referer: http://www.xxxxxxxxxxxxxxxxxx.com/admin/catalog/product/new/set/4/type/simple/key/8119da20410415e9f9c3e1258b9f74e7f44626b5df7a91b73930d9c48d3081e/

We enabled a trace with xdebug and found the application would stop after the following line:

[root@757676-app1 tmp]# tail trace.23728.xt
    2.1926   39833808                                                                                                                                           -> Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:861
    2.1926   39833808                                                                                                                                           -> Zend_Db_Adapter_Pdo_Abstract->_quote() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:906
    2.1926   39833808                                                                                                                                             -> addcslashes() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:296
    2.1926   39833840                                                                                                                                             -> Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:297
    2.1926   39833840                                                                                                                                             -> PDO->quote() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:298
    2.1926   39833840                                                                                                                                         -> implode() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:875
    2.1926   39833416                                                                                                                                       -> str_replace() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:931
    2.1926   39833448                                                                                                                                   -> Zend_Db_Select->where() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/framework/DB/Select.php:107
    2.1926   39833448                                                                                                                                     -> Zend_Db_Select->_where() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Select.php:477
    2.1926   39833448                                                                                                                                       -> count() /var/www/vhosts/xxxxxxxxxxxxxxxxxx.com/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Select.php:1001

**Comment by mazhalai** [comment]
@tcmouse did you try on the latest [2.0.1 tag](https://github.com/magento/magento2/tree/2.0.1)? We have some fixes related to php 7 in there.

**Comment by katmoon** [comment]
@tcmouse I'm closing the ticket since there is no response for more than 2 weeks.
Please feel free to reopen if you have any questions.
