### ISSUE TITLE
How to solved CSS revert Back Issue

### ISSUE THREAD

**Issue by raghav111jain** [magento/magento2#30078]
### Preconditions (*)

1.Magento 2.3.5
2.php 7.3

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Magento 2.3 - CSS changes revert after running “ php bin/magento setup upgrade=====php bin/magento setup:static-content:deploy -f ”**

**Comment by krishprakash** [comment]
Hi @raghav111jain. 
GitHub issue tacker is intended for Magento core technical issues only
 Kindly refer community forum or Magento stack exchange for discuss about this topic
Thanks!!
