### ISSUE TITLE
[GraphQl bug] query Products in category is wrong price when set catalog price rule promotion for specific customer group

### ISSUE THREAD

**Issue by huykon** [magento/magento2#30083]
### Preconditions (*)

1. Magento 2.4.0

### Steps to reproduce (*)

1. Setup catalog price rule promotion with condition only customer login group for category A. The rule will discount 10% price for all products on this category.
2. Try to query graphql [products](https://devdocs.magento.com/guides/v2.4/graphql/queries/products.html) to get all product of category A with 2 situation:
- Not login
- Logged as customer
3. The data return as same with both. The price have not discounted with customer logged in yet

### Expected result (*)

1. The price of all products on category A will discount 10% with customer login request that query
2. 

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
The issue has been fixed with [this commit](https://github.com/magento/magento2/commit/e6e5c738eb47a982d90aef8e9a087cb3fd9bcacf) by the internal team.

Hello @rogyar 
Could you please close this issue?

Thank you in advance.
