### ISSUE TITLE
Not showing Products 

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#3008]
Not showing any product with id above 2999 on the front end or in the Category Products tab in admin
![no id](https://cloud.githubusercontent.com/assets/16354206/12366115/0c8d2c18-bba7-11e5-9b9c-908852e17b40.PNG)
Thanks

**Comment by katmoon** [comment]
It looks like this is the last product in the list of category products.
What happens when you assign an additional product with id > 2999 to the category?

**Comment by zamboni084** [comment]
In the picture there were another 100 products in the category. But for some reason it took 3 days to show up. Now everything is working i create a product it show right away in the front end.
