### ISSUE TITLE
Mobile: Error message is not visible fully if enter 0 qty of products in the Cart on phones with small screen

### ISSUE THREAD

**Issue by dnahirna** [magento/magento2#30089]
### Preconditions 
1. Magento CE 2.0.0 without sample data is installed
2. Test category is set up
3. Test Product is created and assigned to the Test Category
4. Use Mobile phone with small screen (iPhone 5s, iPhone6)

### Steps to reproduce 
1. Add any product to the Cart
2. Open minicart and tap on 'View and Edit Cart'
3. Enter '0' in 'Qty' field and tap on 'UPDATE SHOPPING CART' button
4. Look at the error message under 'Qty' field

### Expected result 
'Please enter a number greater than 0 in this field.' error message should be visible fully 

### Actual result 
'Please enter a number greater than 0 in this field.' error message is not visible fully 

---
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @dnahirna.Thank you for your report.
You need to scroll horizontally for view full validation message as intentionally set the scroll bar for small screen
Refer Screenshot below

![image](https://user-images.githubusercontent.com/46617848/93477469-ac17e580-f918-11ea-9f8d-d47517bba8b3.png)

**Comment by krishprakash** [comment]
Closing this as non issue
