### ISSUE TITLE
Braintree | PaymentInstrumentType::COINBASE_ACCOUNT | constant is missing

### ISSUE THREAD

**Issue by indunil15** [magento/magento2#30084]
### Steps to reproduce (*)

1. Setup the Magento 2.4
2. Log into the Admin
3. Navigate to Reports -> Sales -> Braintree Statement 

### Expected result (*)

1. Should show Admin grid

### Actual result (*)

1. Shows an error page
`Error: Undefined class constant 'COINBASE_ACCOUNT' in /app/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php:47 Stack trace: #0 /app/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php(29): PayPal\Braintree\Ui\Component\Report\Listing\Column\PaymentType->getAvailablePaymentTypes() #1 /app/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(67): PayPal\Braintree\Ui\Component\Report\Listing\Column\PaymentType->toOptionArray() #2 /app/vendor/magento/module-ui/Component/Filters/Type/Select.php(70): Magento\Ui\Component\Form\Element\AbstractOptionsField->prepare() #3 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\Ui\Component\Filters\Type\Select->prepare() #4 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Filters\Type\Select)) #5 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Filters)) #6 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Container)) #7 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(142): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing)) #8 /app/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'braintree_repor...', Array, Object(Magento\Framework\View\Layout\Interceptor)) #9 /app/vendor/magento/framework/View/Layout/GeneratorPool.php(81): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #10 /app/vendor/magento/framework/View/Layout.php(352): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context),`

The error was due to themagento/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php constant on line 47  `PaymentInstrumentType::COINBASE_ACCOUNT`

I cannot find the specific constant under the magento/vendor/braintree/braintree_php/lib/Braintree/PaymentInstrumentType.php

Then I try to find the constant under the https://github.com/braintree/braintree_php/blob/master/lib/Braintree/PaymentInstrumentType.php, But the constant cannot be found on the master and the other public available tags.

To resolve this issue I can think of a patch for removing 
`            PaymentInstrumentType::COINBASE_ACCOUNT => __(PaymentInstrumentType::COINBASE_ACCOUNT),
`

The patch might be like this:
`--- magento/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php
+++ magento/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php
@@ -44,7 +44,6 @@
         // @codingStandardsIgnoreStart
         return [
             PaymentInstrumentType::PAYPAL_ACCOUNT => __(PaymentInstrumentType::PAYPAL_ACCOUNT),
-            PaymentInstrumentType::COINBASE_ACCOUNT => __(PaymentInstrumentType::COINBASE_ACCOUNT),
             PaymentInstrumentType::EUROPE_BANK_ACCOUNT => __(PaymentInstrumentType::EUROPE_BANK_ACCOUNT),
             PaymentInstrumentType::CREDIT_CARD => __(PaymentInstrumentType::CREDIT_CARD),
             PaymentInstrumentType::APPLE_PAY_CARD => __(PaymentInstrumentType::APPLE_PAY_CARD),`
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance
