### ISSUE TITLE
Breadcrumbs on product page not showing catgories if category is set to "Show in Menu = No"

### ISSUE THREAD

**Issue by chequille** [magento/magento2#30098]
### Preconditions (*)
1. Version 2.3.5-p2, 2.4-develop

### Steps to reproduce (*)
1. Just set a category to Show in Menu No
2. Look at the breacrumbs on the product page of a product within this category

### Expected result (*)
1. Breadcrumbs should show category even if category is set to "Not show in Menu"

### Actual result (*)
1. Breadcrumbs only show "Home - Product name"

**Comment by chequille** [comment]
Additional Information and thought about this:

Setting the categories to not show in menu is sometimes necessary because of some layout and design reasons. 
Nevertheless, they are active categories containing products.

I do access these categories with a link to it. On the category page itself, the breadcrumb is showing the category name. At this point everything is ok. But when a product is selected breadcrumbs not showing the category anymore.

This makes absolutely no sense and in my point of view it is a BUG.

Please have a look and tell us here what can be changed to the category in the breadcrumbs.

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 instance

**Comment by ajijshekh123** [comment]
Hi @chequille,
I have verified this issue on the latest Magento 2.4 Instance. I have verified the configuration as per the define steps to be reproduced. But not able to reproduce the issue on Magento 2.4 Instance.
Please update your Magento Instance. Magento doesn't provide 2.3.5-p2 Instance.
PFA:
![image](https://user-images.githubusercontent.com/24711761/93663539-62e5a400-fa86-11ea-9a4d-d604d7a9cbb3.png)

![image](https://user-images.githubusercontent.com/24711761/93663543-65e09480-fa86-11ea-851d-cb24a5196c21.png)

Thanks.

**Comment by chequille** [comment]
Hi,
as I see in your screenshots you are on the category page, not on a product page. 
The breadcrumbs are correct there but you have to click on a product now and look how the breadcrumbs look than.
Please try this.

**Comment by chequille** [comment]
As well, as of our picture, you disbaled the category tops under category women but your forntend site shows men.

**Comment by chequille** [comment]
@magento give me 24.0 instance

**Comment by chequille** [comment]
@magento give me 2.4.0 instance

**Comment by chequille** [comment]
Here it is: Set Tops not in Menu
![grafik](https://user-images.githubusercontent.com/15807794/93668854-b9a3ab80-fa8f-11ea-9126-c0a2e7f2b713.png)
Go to the category page with direct link .../men/tops-men.html and ou will see this page, where the category tops is in the breadcrumb.
![grafik](https://user-images.githubusercontent.com/15807794/93668933-7eee4300-fa90-11ea-860b-320d40d326ba.png)
Now click on the product Chaz Kangeroo Hoodie and you will see, that the category tops is not shown anymore in the breadcrumbs.
![grafik](https://user-images.githubusercontent.com/15807794/93668969-bbba3a00-fa90-11ea-86c8-38e1960cf699.png)
This is the bug I claim here and as you see it is still within 2.4.0, so no change.

**Comment by chequille** [comment]
Rendering the breadcrumbs is different for catalog page and product page. I want to know where the difference is and how can I change it maybe with an own module. Nevertheless it makes no sense for me to show the categories in the catalog page but not in the product page if the category is set to "Show in Menu= No".

I hope it is clear now and yu can verify this as well.
Looking forward to hearing fro you soon.
Best regards,
Chequille

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37763` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chequille** [comment]
Let me please ask something. Could somebody explain why you are using scrippt insertion of the breadcrumbs and not like for the catalog page jszt with normal phtml file and php code?

I made some changes in Magento_Catalog/templates/product/breadcrumbs.phtml and it is working. Second advantage of doing it there is, that the breadcrumbs are displayed immedialty and not after a second or so. 

Magento is using enough scripts and I think it should be as less as possible, because scripts do need performance as well on the users pc:

Would like to get an answer where I can understand the reason for it.

If somebody knows where this bug can be fixed (meaing in which file it can be corrected) I would like to know it, because I would write an own module for it if there is a reason to do it with scripts. I cannot wait till Magento fixed it.

Thanks and best reagrds,
Chequille

**Comment by jitendra-cedcoss** [comment]
@magento I am working on it.

**Comment by jitendra-cedcoss** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by chequille** [comment]
Unbelievable, it was reproduced on 2.4.x and nobody cares.

**Comment by Rickertje** [comment]
This is still a bug in 2.3.7-p1. And indeed it's unbelievable that this was closed. I see this happening with many reported issues. @chequille can you publish your fix for Magento_Catalog/templates/product/breadcrumbs.phtml ?

**Comment by Rickertje** [comment]
https://magento.stackexchange.com/a/233023 works (for me). It also adds a breadcrumb for a product found using the search function.
