### ISSUE TITLE
url_rewrite table is hardcoded and that stops saving configuration

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#3009]
Got the below error when trying to save the configuration after removing the search engine optimization prefix and suffix under catalog.

Something went wrong while saving this configuration: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.url_rewrite' doesn't exist, query was: UPDATE url_rewrite SET request_path = ? WHERE (url_rewrite_id = 62)

Refer this thread for more details

http://magento.stackexchange.com/questions/97130/magento2-unable-to-save-catalog-config

**Comment by voleye** [comment]
related issue #3013

**Comment by mslabko** [comment]
Hello @malaiselvan ,
Issue was fixed for develop branch in https://github.com/magento/magento2/commit/42f74ccf60874034536a4311ad4eac7d531e34ce and will be ported for 2.\* as soon as possible

**Comment by vzabaznov** [comment]
Thank for reporting.
Issue was ported to develop branch
@malaiselvan if you feel that  your issue has not been resolved, you can either leave a comment  or open a new GitHub issue.
