### ISSUE TITLE
Products per Page on Grid Default Value

### ISSUE THREAD

**Issue by steved1982** [magento/magento2#30091]
### Preconditions (*)

1. Magento 2.4
2. PHP 7.4.10
3. Elastic Search 7+

### Steps to reproduce (*)

1. Create 18 simple products inside 1 category
2. Set Products per Page on Grid mode to be 9

### Expected result (*)

1. You would see 9 items on one page on the front of the site
2. You would see 2 pages in the navigation

### Actual result (*)

1. You see ALL 18 products on the page
2. You see 2 pages in the navigation that when clicked do not return page 2 of items

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by steved1982** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by krishprakash** [comment]
Hi @steved1982.
I'm not able reproduce the issue on latest 2.4-develop instance as provided steps by you
Refer screenshot below: 
![image](https://user-images.githubusercontent.com/46617848/93481139-dc14b800-f91b-11ea-8787-38a2d8f5b6c1.png)
Could you please review in 2.4-develop instance and let me know if you reproduce the issue and update the steps if you will reproduce
Thanks!!

**Comment by krishprakash** [comment]
Hi @steved1982.
Feel free to reopen the issue once you confirm the issue is reproduce on 2.4-develop instance
Thanks!!

**Comment by dvershinin** [comment]
@steved1982 we're having the same issue on 2 unrelated stores with different themes; the only common is some Mirasvit modules...

**Comment by souzapsl** [comment]
@magento give me 2.4.6 instance

**Comment by souzapsl** [comment]
@magento give me 2.4.6-p2 instance
