### ISSUE TITLE
File Permission Check Error

### ISSUE THREAD

**Issue by smartperf** [magento/magento2#3010]
![image](https://cloud.githubusercontent.com/assets/10887546/12368770/687d2e46-bba3-11e5-9b10-88e689d12a51.png)

[magento_user@lnxdev01 magento2]$ groups apache
apache : apache magento_user

-rw-rw----.  1 magento_user apache 434532 Jan 14 18:34 CHANGELOG.md
-rw-rw----.  1 magento_user apache   3425 Jan 14 18:34 CONTRIBUTING.md

/var/www/html/magento2 and its subfolders and files have ownership as  magento_user is in group apache

All permissions are granted. 

My environment:
CentOS 7
MySQL 5.5.44
Apache 2.4.6
PHP 5.6.16
Zend Engine 2.6.0

The solutions in https://github.com/magento/magento2/issues/2885 like 
[magento_user@lnxdev01 magento2]$ sestatus | grep -i mode
Current mode:                   enforcing
Mode from config file:          enforcing
[magento_user@lnxdev01 magento2]$ chcon -R -h -t httpd_sys_script_rw_t /var/www/html/magento2/app/etc
seems not work for my case.

Please advise.

**Comment by magenx** [comment]
php running as another user or folder magento2 is not writable for apache group?

**Comment by smartperf** [comment]
thanks, magenx,

I have run this
find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento

I also run 
chmod 777 /var/www/html/magento2/app/etc
chmod 777 /var/www/html/magento2/var
chmod 777 /var/www/html/magento2/pub/media
chmod 777 /var/www/html/magento2/pub/static

So I think all files and folders are writable for apache group.

Based on http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html#install-update-depend-user-over, I thought it is recommended to have a user like magento_user as the owner of the files

Thanks,

**Comment by magenx** [comment]
read my question. thank you

**Comment by mazhalai** [comment]
@smartperf any update? Has this issue been resolved?

**Comment by mazhalai** [comment]
@smartperf closing as non-responsive.
