### ISSUE TITLE
GraphQL mutations on customers cart fails when using multiple store views

### ISSUE THREAD

**Issue by oscarpas** [magento/magento2#30100]
### Preconditions (*)
1. Magento 2.4.0
2. Magento is setup with one website which has two store views
3. A customer account is created

### Steps to reproduce (*)
1. Retrieve a customer token for the created customer via generateCustomerToken mutation
2. Retrieve customers cart id via customerCart query
3. Add a product to the customer cart via addSimpleProductsToCart mutation. Use token in Authorization header and the first store view code in the Store header.
4. Repeat step 3 but use the second store view code in the Store header.

### Expected result (*)
1. Both mutatations, using different Store headers, should successfully add the product to the customer cart. This is the behavior we see in the regular M2 frontend.

### Actual result (*)
1. One of the mutations succeeds, the other one fails with message: "Wrong store code specified for cart"

### Some additional notes
- Querying the customerCart using different Store headers successfully returns the same cart
- All mutations on the customer cart will fail for one of the store views, not just addSimpleProductsToCart example
- When authorized as a customer createEmptyCart will always return the existing cart, for both store views. This is probably intended behavior but makes a workaround impossible at the moment (if we could create different carts per store view for logged in customers we could work around the "Wrong store code specified for cart" error).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nrkapoor** [comment]
@melnikovi @prabhuram93 Can you take a look and see if we need to fix this issue?

**Comment by mauragcyrus** [comment]
Looks like this is the same issue reported here: https://github.com/magento/magento2/issues/28953

**Comment by sasha19957099** [comment]
@magento I am working on this

**Comment by Zifius** [comment]
Hi @mauragcyrus @cpartica! Should we close then one of the issues as duplicate?

I'm willing to work on the issue if there is no progress on it

**Comment by mauragcyrus** [comment]
https://github.com/magento-commerce/magento2ce/pull/6383 and https://github.com/magento-commerce/magento2ee/pull/2699 covered a fix for this (cc: @cspruiell)

**Comment by nuzil** [comment]
Hi @mauragcyrus 
Any estimated time when we can get the fix? cause links you posted are in another repository and I cannot get a code out of it.
Thanks
