### ISSUE TITLE
Magento 2.4 CE: the translate inline tool doesn't work

### ISSUE THREAD

**Issue by d-consulting** [magento/magento2#30116]
### Summary (*)
1. Magento 2.4 CE with simple data is installed
2. Developer mode is set
3 Three type of cache are disabled: blokks, html output, page cache, translations
4 Go to Store -> Configuration -> Advanced -> Devolepor and enable for store front Translate Inline
5 Save config. Refresh cache (leaving disabled the previous three type of cache)
6 Open in a new browser window the store
7 Select text to translate
8 Make translation and click on submit
9 After submitted translation appears
10 Refresh the page: no change appears

Here attached steps screenshots:
![1 developer mode set](https://user-images.githubusercontent.com/16258177/93672334-7c98e280-faaa-11ea-9df6-bf5f1ce94a21.jpg)
![2 disabled cache](https://user-images.githubusercontent.com/16258177/93672338-802c6980-faaa-11ea-9d67-70f1d14781b4.jpg)
![3 translate inline enabled for storefront for default config](https://user-images.githubusercontent.com/16258177/93672346-83bff080-faaa-11ea-948a-2d1c5e7e55d0.jpg)
![4 refreshed cache](https://user-images.githubusercontent.com/16258177/93672351-86224a80-faaa-11ea-8651-ef41643d1103.jpg)
![6 Translation attempt](https://user-images.githubusercontent.com/16258177/93672355-891d3b00-faaa-11ea-9102-6d71d06bba74.jpg)
![7 refreshed page no translation made](https://user-images.githubusercontent.com/16258177/93672359-8b7f9500-faaa-11ea-8e07-c06248679e07.jpg)
![8 change submitted](https://user-images.githubusercontent.com/16258177/93672360-8de1ef00-faaa-11ea-8156-4279beb55f6a.jpg)

**Comment by engcom-Delta** [comment]
Hi @d-consulting thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Changes are applied after submit and after reload page
![#30116](https://user-images.githubusercontent.com/51681379/99975830-5eea4100-2dab-11eb-8abc-f24f852f87ad.gif)
