### ISSUE TITLE
Facing an issue to installing Magento 2.4.0

### ISSUE THREAD

**Issue by taha-abdulghani** [magento/magento2#30112]
Hello, 

@magento I am working on this
i'm trying to install magento 2 and i'm facing an issue to installation by using this code
`php bin/magento setup:install --base-url="http://magtest/magento2"--db-host=localhost --db-name="dbmagento24" --db-user="root" --db-password="" --admin-firstname="admin" --admin-lastname="admin" --admin-email="user@example.com" --admin-user="admin" --admin-password="admin123" --use-rewrites="1" --backend-frontname="admin"`

and this error occurs

> Failed to initialize global composer: Composer could not find the config file: C:/xampp/htdocs/magento24/var/composer_home/composer.json

Kindly help Thank You
![Untitled](https://user-images.githubusercontent.com/55913189/93649887-782ae600-fa26-11ea-97c7-3c587bd2e903.png)

**Comment by krishprakash** [comment]
Hi @taha-abdulghani.
GitHub issue tacker is intended for Magento core technical issues only.
Kindly refer community forum or Magento stack exchange for general discuss about this topic
Thanks!!
