### ISSUE TITLE
Cart on site not working

### ISSUE THREAD

**Issue by JOLIESALES** [magento/magento2#30121]
### Preconditions (*)
<!---
The cart on my website is not showing active on most browsers - but does on some - why?

**Comment by krishprakash** [comment]
Hi @JOLIESALES. Kindly update all the details for issue as per reporting [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by krishprakash** [comment]
Hi @JOLIESALES. Feel free to reopen once you update all the details
Thanks!!
