### ISSUE TITLE
Magento search for url_rewrite instead of PREFIX_url_rewrite

### ISSUE THREAD

**Issue by lorenaramonda** [magento/magento2#3013]
During the installation, Magento lets you specify a prefix for all table in the database. When I try to change the SEO settings in catalog return me this error:

Something went wrong while saving this configuration: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'balume_magento2.url_rewrite' doesn't exist, query was: UPDATE `url_rewrite` SET `request_path` = ? WHERE (`url_rewrite_id` = 15)

I think it's because it searches for url_rerwrite instead of PREFIX_url_rewrite.

**Comment by voleye** [comment]
Hi @lorenaramonda, thank you for your contribution to M2!

We have created an internal ticket MAGETWO-48083 to track the issue.

**Comment by mslabko** [comment]
Hello @lorenaramonda,
Issue was fixed for develop branch in https://github.com/magento/magento2/commit/42f74ccf60874034536a4311ad4eac7d531e34ce and will be ported for 2.\* as soon as possible

**Comment by lorenaramonda** [comment]
Thank you soo much!
