### ISSUE TITLE
Configurable product graphql doesn't accept string option values

### ISSUE THREAD

**Issue by drc0** [magento/magento2#30137]
I have a custom attribute source that works with the default theme Luma but not with a pwa (magento pwa for example or scandipwa) that uses the graphql endpoint defined in configurable-product-graph-ql schema, because value_index expects an Int https://github.com/magento/magento2/blob/390505a93555198c93331ed9159664fbccb70cd9/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L20

Also changing that value_index to be String, the attribute appears as selectable on frontend but adding the product to cart leads to another error that I'm not sure how to debug.

Can those graphql endpoints support string option values?

Here is the attribute source I'm using as example

```
<?php
namespace Vend\ModuleModel\Config\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\InventoryApi\Api\SourceRepositoryInterface;

class MachineOptions extends AbstractSource
{
    public function __construct(SourceRepositoryInterface $magentoSourceRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder) {
        $this->magentoSourceRepository = $magentoSourceRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
    }
    /**
     * Get all options
     *
     * @return array
     */
    public function getAllOptions()
    {
        if (null === $this->_options) {
            $this->_options = [
                ['label' => '', 'value' => '']
            ];
            $sources = $this->magentoSourceRepository->getList();
            foreach($sources->getItems() as $source) {
                $this->_options[] = [
                    'label' => $source->getName() . ' - ' . $source->getDescription(),
                    'value' => $source->getSourceCode()
                ];
            }
        }
        return $this->_options;
    }

}

```
### Preconditions (*)
1. magento 2.4
2. a custom attribute option source that defines string values and not integers
3. something that queries the graphql configurable produc attributes

### Steps to reproduce (*)
1. create custom attribute source
2. add a configurable product and a single product for one of those custrom attribute option value
3. query the graphql for configurable product 

### Expected result (*)
1. Ability to use string option values and not only int

### Actual result (*)
1. Product detail page returns this exception on the graphql to get the configurable product `debugMessage	Expected a value of type "Int" but received: custom_machine_source_code-123
message	Internal server error
extensions	{…}
category	internal
path	[…]
0	products
1	items
2	0
3	configurable_options
4	0
5	values
6	0
7	value_index`
2. Changing the graphql schema here https://github.com/magento/magento2/blob/390505a93555198c93331ed9159664fbccb70cd9/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L20 to accept Strings like this

```
20c20
<     value_index: String @doc(description: "A unique index number assigned to the configurable product option")
---
>     value_index: Int @doc(description: "A unique index number assigned to the configurable product option")
37c37
<     value_index: String @doc(description: "A unique index number assigned to the configurable product option")
---
>     value_index: Int @doc(description: "A unique index number assigned to the configurable product option")
```

I can get rid of the error 1. but instead I get a new error when adding the product to cart: `{"JSON":{"errors":[{"message":"Variable \"$parentSku\" of required type \"String!\" was not provided.","extensions":{"category":"graphql"},"locations":[{"line":1,"column":91}]}]},"Payload risposta":{"EDITOR_CONFIG":{"text":"{\"errors\":[{\"message\":\"Variable \\\"$parentSku\\\" of required type \\\"String!\\\" was not provided.\",\"extensions\":{\"category\":\"graphql\"},\"locations\":[{\"line\":1,\"column\":91}]}]}","mode":"application/json"}}}
`

**Comment by zakdma** [comment]
Issue still exists in 2.4.7
Custom source with string values not allowed by GraphQl but working fine with classic Magento frontend.
Why did you close it even not checked?
