### ISSUE TITLE
Configurable product shows $0 when out of stock

### ISSUE THREAD

**Issue by thundercat1** [magento/magento2#30138]
### Preconditions (*)
1. Magento 2.3.5

### Steps to reproduce (*)
1. Create a simple product with zero quantity, but nonzero price
2. Create a configurable product that includes the simple product as child

### Expected result (*)
1. Configurable product should show out of stock, but the price from the simple product
2.

### Actual result (*)
1. Configurable product shows out of stock, $0 price

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thundercat1** [comment]
@magento give me 2.3.5 instance

**Comment by thundercat1** [comment]
@magento give me 2.3 instance

**Comment by thundercat1** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @thundercat1,

I have reviewed the Issue in the Default Magento 2.4 Instance with your steps, actual result and expected result.
In Configurable Product, The user not able to add the simple product in Configurable products. so not verify this issue in the latest magento Instance.
After verify Magento 2.3 instance I will confirm the issue.

Thanks.

**Comment by ajijshekh123** [comment]
Hi @dverkade,
The issue is not reproduced in the Latest Magento Instance. I have covered all the steps, actual result and expected result but do not reproduce the latest Magento 2.4 Instance.
All delivery to the 2.3.x release line can be done only by Magento's internal teams. Magento team is working based on the internal backlog priority.

Thanks.
