### ISSUE TITLE
Special character ' not showing correct in product grid

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#30145]
### Preconditions
1. Magento 2.3.5
2. Install the sample data

### Steps to reproduce
1. Edit a product and change the name of the product and add an apostrophe to the name of the product. Example product name: heating'
2. Save the product.
3. Product has been saved correctly. Showing the product name as "heatin'" in the product edit screen.
4. Return to the product overview page / product grid page. 
5. Product name is shown as: "heatin&#039;" 

### Expected result
1. Product name should be shown as "heating'" in the product grid.

### Actual result

1. Product name is shown as "heatin&#039;" in the product grid.

![image](https://user-images.githubusercontent.com/1058480/93879858-ca952c80-fcdc-11ea-9a6a-3150643ae7af.png)
![image](https://user-images.githubusercontent.com/1058480/93879915-e1d41a00-fcdc-11ea-99be-dbda76a1e4de.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-develop instance

**Comment by ajijshekh123** [comment]
Hi @dverkade,
Verified the issue Default Magento 2.4 Instance. Product name is showing properly on Product Grid, Edit Product and Front end product page. You can review all attached the screenshot:

![image](https://user-images.githubusercontent.com/24711761/93890226-bd416780-fd07-11ea-8aec-e035c09e2aab.png)

![image](https://user-images.githubusercontent.com/24711761/93890355-e3670780-fd07-11ea-927a-50e2e5af7008.png)

![image](https://user-images.githubusercontent.com/24711761/93890248-c5010c00-fd07-11ea-9004-3add62afc246.png)

Let me try to verify the issue Magento 2.3.5 Instance and update it.

Thanks.

**Comment by ajijshekh123** [comment]
Hi @dverkade,
The issue is not reproduced in the Latest magento Instance. I have cover all the steps, actual result and expected result but do not reproduce the latest Magento 2.4 Instance.
All delivery to the `2.3.x` release line can be done only by Magento internal teams. Magento team is working based on the internal backlog priority.

Thanks.
