### ISSUE TITLE
SKU is not affected on Product Update API request

### ISSUE THREAD

**Issue by wassuupp** [magento/magento2#30143]
### Summary (*)
When user tries to change "sku" using Product Update API request, Magento ignores "sku" value.
If there should be ability to change "sku", this ability needs to be implemented.
It no, so should be some error message that sku changing is deprecated.

### Examples (*)
Make PUT request on this endpoint /V1/products/{sku1}
Body example:
{
    "product":
        {
            "sku": "sku2",
            "name": "Test changes name"
        }
}
Name will be changed, but "sku" - no. And also no information provided that "sku" was not changed.

### Proposed solution
Make an exception in case if "sku" field is included in request body or implement sku changing.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37949` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37950` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amitvishvakarma** [comment]
@magento I'm working on this

**Comment by amitvishvakarma** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Hi @wassuupp. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37950` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @wassuupp. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37949` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
