### ISSUE TITLE
Order containing unavailable product cannot be edited

### ISSUE THREAD

**Issue by MartinSchillinger** [magento/magento2#30147]
### Preconditions (*)
 
1. Magento 2.4.0 CE
2. PHP 7.4
3. MariaDB 10.4

### Steps to reproduce (*)

1. Create an order with any sample product
2. Set global quantity of that specific product to 0
3. Try to edit the order

### Expected result (*)

1. Order is editable so that you can at least remove the unavailable product

### Actual result (*)

1. Page reloaded showing "This product is out of stock." error.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @MartinSchillinger. Thank you for your report.
This is default magento behavior to show the message like This product is out of stock
You need to select **_Remove_** from Action drop down and Update Items and Quantities so that product has been removed from the order
Refer the screenshot below:
![image](https://user-images.githubusercontent.com/46617848/94009431-14a40e00-fdc2-11ea-9969-96af3c669b93.png)

**Comment by pemann** [comment]
@magento give me 2.3.5 instance

**Comment by LusienGG** [comment]
> Hi @MartinSchillinger. Thank you for your report. This is default magento behavior to show the message like This product is out of stock You need to select **_Remove_** from Action drop down and Update Items and Quantities so that product has been removed from the order Refer the screenshot below: ![image](https://user-images.githubusercontent.com/46617848/94009431-14a40e00-fdc2-11ea-9969-96af3c669b93.png)

Actualy the problem is that the person is not even seeing the edit page. Page is reloading and popin up "This product is out of stock.". 

I face the same issue now 2 years later.
