### ISSUE TITLE
Graphql Related Product Map Id Not Exit In Related Search Result

### ISSUE THREAD

**Issue by haimagento2** [magento/magento2#30142]
Preconditions (*)

1. Magento 2.3.5

Steps to reproduce (*)

1. Create a simple product with some related products
2.Set a related product form in stock to out stock or set quantity to 0 or disable a related product

Expected result (*)
1. 
![fix_related_graphql](https://user-images.githubusercontent.com/48465499/93868179-4babee00-fcf4-11ea-9c14-b775fd5a562a.png)

Actual result (*)
1. 
![related_issues](https://user-images.githubusercontent.com/48465499/93868231-5cf4fa80-fcf4-11ea-89b6-e5383c02a52c.png)

Fix(*):
Set right search able related ids Array
![fixed](https://user-images.githubusercontent.com/48465499/93868482-b0ffdf00-fcf4-11ea-9450-0672cb8ec4de.png)

**Comment by haimagento2** [comment]
this is path file
vendor/magento/module-related-product-graph-ql/Model/Resolver/Batch/AbstractLikedProducts.php

**Comment by codynguyen1** [comment]
This problem seems to be fixed since the commit #a57dbd6d2032 (https://github.com/magento/magento2/commit/a57dbd6d2032), @sidolov  please close this issue if it's true.

**Comment by sidolov** [comment]
Closed according to @codynguyen1 comment. Thank you!
