### ISSUE TITLE
magento2 cart displays incorrect image for product attributes

### ISSUE THREAD

**Issue by miketsl** [magento/magento2#3014]
If you create a product with attributes, lets say color and size, and then add custom images for each color, magento2 will then allow the display of the custom images on the product detail page.  When someone selects the new color, it will show the product in that color (so far so good)...

When someone adds this product combination to the cart however, the image in the cart will be the base image for the product, ... not the base image for the product and attribute combination they selected.

For example:  You create a product thats a watch.  You have 5 colors, each color is created with with its own images.  The base image for the entire product is a black watch.  Someone clicks on it, and then on the product details page selects red.  Magento shows the red watch as expected.  Awesome.  Then they click add to cart.  Now... in the cart, is the picture of a black watch, with the words "Color: Red" next to it.  

Shouldn't the cart be showing the base image of the individual item that is selected?  in this case, a red watch with its own skew and base image?

Mike

**Comment by kandy** [comment]
Magento has a configuration witch image to show in Shopping Cart. See Configuration > Checkout > Shopping Cart > Configurable Product Image
![image](https://cloud.githubusercontent.com/assets/100289/12379029/aedab630-bd59-11e5-82af-d9bd1f549a6f.png)

**Comment by kandy** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for questions.Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by miketsl** [comment]
Sorry to be dense. But I don't see that in the Magento 2.0.0 administration
interface. Maybe you can enlighten me

**Comment by Sato-oz** [comment]
Thanks a bunch Kandy. I had the same challenge, and your guide solved it

**Comment by Sato-oz** [comment]
miketsl. Go to Stores > Configuration > Sales > Checkout > Shopping cart. Then you will see the page Kandy described above.
