### ISSUE TITLE
validate-clean-url regex is broken?

### ISSUE THREAD

**Issue by LiamTrioTech** [magento/magento2#30152]
### Preconditions (*)
Magento 2.4-develop
For example filtering a URL of `https://example.co.nz`

If I take the JS Regex rules and run them manually you can see.
```js
[
/^(http|https|ftp):\/\/(([A-Z0-9][A-Z0-9_-]*)(\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test('https://example.com'),
/^(www)((\.[A-Z0-9][A-Z0-9_-]*)+.(com|org|net|dk|at|us|tv|info|uk|co.uk|biz|se)$)(:(\d+))?\/?/i.test('https://example.com')
]
```
Results in
```js
[false, false]
```

Which would output the message such as:
```Please enter a valid URL. For example http://www.example.com or www.example.com.```

### Steps to reproduce (*)
1. Have an input that uses the validation validate-clean-url
2. Enter in ```https://example.co.nz``` for example.

### Expected result (*)
Should be a valid URL

### Actual result (*)
Invalid

![image](https://user-images.githubusercontent.com/68578009/93967004-46b17200-fdba-11ea-89d5-c1bc77d10335.png)

Unless this is supposed to be for something else? validate-url seems to work okay.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40345` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gixid192** [comment]
I think the regex is always wrong when it comes to url that has port.
The reason is the use of `$` meaning end of the line, but then it append `\d+` right after `$`, makes that `$` non-scene
