### ISSUE TITLE
Can't install Magento 2.4 - Could not validate a connection to Elasticsearch. null

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30157]
### Preconditions (*)

-

### Steps to reproduce (*)

Try to install magento 2.4.0 like this.

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.4.0 .

2.

```
        php -d memory_limit=-1 bin/magento setup:install \
        --base-url=http://local.company.m2/ \
        --db-host=localhost \
        --db-name=fresh_m2 \
        --db-user=fresh_m2 \
        --db-password=xyz\
        --admin-firstname=Hans\
        --admin-lastname=Volksen\
        --admin-email=hans@company.de \
        --admin-user=vhans \
        --admin-password=xyz \
        --language=de_DE \
        --currency=EUR \
        --timezone=Europe/Berlin \
        --use-rewrites=1 \
        --backend-frontname="adminlogin" \
        --elasticsearch-host=es-company.rackspeed-cloud.de \
        --elasticsearch-port=9200 \
        --elasticsearch-enable-auth=1 \
        --elasticsearch-index-prefix=company_dev_ \
        --elasticsearch-username=elasticsearch \
        --elasticsearch-password=xyz
```

**NOTE:** I replaced some sensitive data with xyz

### Expected result (*)

It should work, because if I test the exact same credentials in Amasty Elastic Search Extension and press on the test button, then I get "Connection successfull", and if I enter the elasticsearch host in the browser, then a login appears and if I enter my credentials, then I get a json object, so it should work.

### Actual result (*)

1.  Could not validate a connection to Elasticsearch. null

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Shubham0492** [comment]
@magento give me 2.4-develop instance

**Comment by wagento-rajan** [comment]
@magento give me 2.4-develop instance

**Comment by wagento-rajan** [comment]
@magento I am working on this

**Comment by wagento-rajan** [comment]
Please follow the below steps to setup Elastic Search:

Run the below command to Install Elasticsearch In locally.
Download and install the public signing key :

`wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -`

You may need to install the apt-transport-https package on Debian before proceeding :

`sudo apt-get install apt-transport-https`

Save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list :

`echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list`

You can install the Elasticsearch Debian package with :

`sudo apt-get update && sudo apt-get install elasticsearch`

Elasticsearch is not started automatically after installation.
`ps -p 1`

Use the update-rc.d command to configure Elasticsearch to start automatically when the system boots up :

`sudo update-rc.d elasticsearch defaults 95 10
`
Elasticsearch can be started and stopped using the service command :

```
sudo -i service elasticsearch start

sudo -i service elasticsearch stop

```
Configure Apache and Elasticsearch : Set up a proxy (Set up a proxy for Apache 2.4)

Enable mod_proxy as follows :

`a2enmod proxy_http or sudo a2enmod proxy_http`

Use a text editor to open /etc/apache2/sites-available/000-default.conf

Add the following directive at the top of the file :

`Listen 8080
`
Add the following at the bottom of the file :

```
<VirtualHost *:8080>
ProxyPass "/" "http://localhost:9200/"
ProxyPassReverse "/" "http://localhost:9200/"
</VirtualHost>

```
Restart Apache :

service apache2 restart or sudo service apache2 restart

Verify the proxy works by entering the following command :

For example, if your proxy uses port 8080:

`curl -i http://localhost:8080/_cluster/health`

If curl request success then messages display like below :

```
HTTP/1.1 200 OK
Date: Sun, 23 Aug 2020 06:05:56 GMT
Server: Apache/2.4.18 (Ubuntu)
content-type: application/json; charset=UTF-8
content-length: 389

{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}

```

After all of this RUN the below command:

        php -d memory_limit=-1 bin/magento setup:install \
        --base-url=http://local.company.m2/ \
        --db-host=localhost \
        --db-name=fresh_m2 \
        --db-user=fresh_m2 \
        --db-password=xyz\
        --admin-firstname=Hans\
        --admin-lastname=Volksen\
        --admin-email=hans@company.de \
        --admin-user=vhans \
        --admin-password=xyz \
        --language=de_DE \
        --currency=EUR \
        --timezone=Europe/Berlin \
        --use-rewrites=1 \
        --backend-frontname="adminlogin" \
        --elasticsearch-host=localhost \
        --elasticsearch-port=8080 \
        --elasticsearch-engine=Search Engine7

**Comment by wagento-rajan** [comment]
#dmcdindia2020

**Comment by ptchau2003** [comment]
+1 for AWS ES 
AWS ES working fine
`curl -X GET -u '<username@password' https://XXXXXXXXXXXXXXXXXXXX.com/_cluster/health                                                                                           {"cluster_name":"286894466481:mangento","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"active_primary_shards":2,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}`

`magento setup:install --base-url=XXXXXXXXXXXXXXXXXXXXXXXXX \
--db-host=localhost --db-name=Magento --db-user=magento --db-password=magento \
--admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com \
--admin-user=admin --admin-password=admin123 --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine=elasticsearch7 --elasticsearch-host=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \
--elasticsearch-port=443 \
--elasticsearch-enable-auth true \
--elasticsearch-username=XXXXXXX --elasticsearch-password=XXXXXXXXXXXXXXXX`

[Progress: 410 / 842]
Module 'Magento_WebapiAsync':
[Progress: 411 / 842]
Module 'Magento_WebapiSecurity':
[Progress: 412 / 842]
Module 'Magento_Weee':
Running schema recurring...
[Progress: 413 / 842]
Module 'Magento_WeeeGraphQl':
[Progress: 414 / 842]
Module 'Magento_CatalogWidget':
[Progress: 415 / 842]
Module 'Magento_Wishlist':
Running schema recurring...
[Progress: 416 / 842]
Module 'Magento_WishlistAnalytics':
[Progress: 417 / 842]
Module 'Magento_WishlistGraphQl':
[Progress: 418 / 842]
[Progress: 419 / 842]
Installing search configuration...

In SearchConfig.php line 81:

  Could not validate a connection to Elasticsearch. null

**Comment by ptchau2003** [comment]
> Please follow the below steps to setup Elastic Search:
> 
> Run the below command to Install Elasticsearch In locally.
> Download and install the public signing key :
> 
> `wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -`
> 
> You may need to install the apt-transport-https package on Debian before proceeding :
> 
> `sudo apt-get install apt-transport-https`
> 
> Save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list :
> 
> `echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list`
> 
> You can install the Elasticsearch Debian package with :
> 
> `sudo apt-get update && sudo apt-get install elasticsearch`
> 
> Elasticsearch is not started automatically after installation.
> `ps -p 1`
> 
> Use the update-rc.d command to configure Elasticsearch to start automatically when the system boots up :
> 
> `sudo update-rc.d elasticsearch defaults 95 10 `
> Elasticsearch can be started and stopped using the service command :
> 
> ```
> sudo -i service elasticsearch start
> 
> sudo -i service elasticsearch stop
> ```
> 
> Configure Apache and Elasticsearch : Set up a proxy (Set up a proxy for Apache 2.4)
> 
> Enable mod_proxy as follows :
> 
> `a2enmod proxy_http or sudo a2enmod proxy_http`
> 
> Use a text editor to open /etc/apache2/sites-available/000-default.conf
> 
> Add the following directive at the top of the file :
> 
> `Listen 8080 `
> Add the following at the bottom of the file :
> 
> ```
> <VirtualHost *:8080>
> ProxyPass "/" "http://localhost:9200/"
> ProxyPassReverse "/" "http://localhost:9200/"
> </VirtualHost>
> ```
> 
> Restart Apache :
> 
> service apache2 restart or sudo service apache2 restart
> 
> Verify the proxy works by entering the following command :
> 
> For example, if your proxy uses port 8080:
> 
> `curl -i http://localhost:8080/_cluster/health`
> 
> If curl request success then messages display like below :
> 
> ```
> HTTP/1.1 200 OK
> Date: Sun, 23 Aug 2020 06:05:56 GMT
> Server: Apache/2.4.18 (Ubuntu)
> content-type: application/json; charset=UTF-8
> content-length: 389
> 
> {"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
> ```
> 
> After all of this RUN the below command:
> 
> `php bin/magento setup:install --base-url=http://127.0.0.1/magento2/ --db-host=localhost --db-name=contribute --db-user=root --db-password=root --admin-firstname=test --admin-lastname=test --admin-email=test@test.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --cleanup-database --session-save=db --use-rewrites=0 --backend-frontname="admin" --elasticsearch-host=localhost --elasticsearch-port=8080 --elasticsearch-engine=Search Engine7 `

Should we use external ElasticSearch?

**Comment by Eddcapone** [comment]
I solved it. The reason was, that you have to specify the search engine. 

I added this `--search-engine=elasticsearch7 \` before `--elasticsearch-host` now it worked.
