### ISSUE TITLE
Attribute type text field: magento cuts text if it is longer than 255 chars without any error message showing

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30159]
### Preconditions (*)
- dev-2.4-develop (instance given by magento deployment bot)

### Steps to reproduce (*)
1. Create new product attribute with type "Text field"
2. Assign Attribute to a attribute set
3. Open a product which has the attribute set assigned.
4. Enter a value with more than 300 chars into the field.
5. Save

### Expected result (*)
1. It should break saving and show a message saying that the value is too big for the text field and that it can't save it.

### Actual result (*)
1. It just saves but trims the value to 255 chars, without the user noticing it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @Eddcapone,
I have verified this issue as per your steps, actual result and expected result.
New assign attribute values has been trim and after 255 characters text is removed without any of the warning or error message.
**Ex:**
I have enter the below 300 characters text 
"A while back I needed to count the amount of letters that a piece of text in an email template had (to avoid passing any character limits). Unfortunately, I could not think of a quick way to do so on my macbook and I therefore turned to the Internet. I could not think of a quick way to do so on mine"

After save the product, Text is trim it is showing below text characters length
"A while back I needed to count the amount of letters that a piece of text in an email template had (to avoid passing any character limits). Unfortunately, I could not think of a quick way to do so on my macbook and I therefore turned to the Internet. I co"
**PFA:**
![image](https://user-images.githubusercontent.com/24711761/94258732-ee5daa00-ff4a-11ea-87a8-b19a101dc8c6.png)


Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37944` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Sweetyagarwal** [comment]
@magento I am working on it.

**Comment by Sweetyagarwal** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by relagio** [comment]
> Hi @Eddcapone, I have verified this issue as per your steps, actual result and expected result. New assign attribute values have been trim and after 255 characters text is removed without any of the warning or error message. **Ex:** I have entered the below 300 characters text "A while back I needed to count the amount of letters that a piece of text in an email template had (to avoid passing any character limits). Unfortunately, I could not think of a quick way to do so on my macbook and I therefore turned to the Internet. I could not think of a quick way to do so on mine"
> 
> After saving the product, the Text is trim it is showing below text characters length "A while back I needed to count the amount of letters that a piece of text in an email template had (to avoid passing any character limits). Unfortunately, I could not think of a quick way to do so on my macbook and I therefore turned to the Internet. I co" **PFA:** ![image](https://user-images.githubusercontent.com/24711761/94258732-ee5daa00-ff4a-11ea-87a8-b19a101dc8c6.png)
> 
> We can count as a feature, not an issue as per my thoughts.
> 
> Thanks.

of course this is an issue and not a feature.

**Comment by Eddcapone** [comment]
It is also beyond me how this is seen as a feature and not as a bug.

**Comment by Eddcapone** [comment]
Please reopen.

**Comment by monvelweb** [comment]
they will never fix it. stubborn and ignorant, that is what the core team is and that is why magento 2 loses ground every year.
