### ISSUE TITLE
URL Rewrites not loading - Cannot read property 'getData' of undefined

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30156]
### Preconditions (*)

1. dev-2.4-develop (instance given by magento deployment bot)

### Steps to reproduce (*)

1. Open Admin Backend.
2. Go to: Marketing -> SEO & Search: Url Rewrites

### Expected result (*)

1. should load

### Actual result (*)

It just loads forever and nothing happens.

I get this in the browser console:

```
provider.js:121 Uncaught TypeError: Cannot read property 'getData' of undefined
    at UiClass.reload (provider.js:121)
    at invoke (resolver.js:90)
    at Array.forEach (<anonymous>)
    at resolve (resolver.js:100)
    at resolver.js:145
    at later (underscore.js:821)
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @Eddcapone. Not able to reproduce the issue as you mentioned 
Here it works fine and also verified in my local 2.4-develop instance

![image](https://user-images.githubusercontent.com/46617848/94008532-cc382080-fdc0-11ea-9aee-39d6a3027553.png)

Thanks !!

**Comment by Eddcapone** [comment]
@krishprakash Maybe the instance I received from magento bot was damaged. I try again:

@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
@krishprakash I can confirm that it works. Seems like the instance which I received from magento deployment service bot was damaged.

**Comment by danmooney2** [comment]
We are aware of this race condition issue and are working on it internally https://jira.corp.magento.com/browse/MC-39333
