### ISSUE TITLE
When product add to wishlist and then add to cart then related products do not add to cart?

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#30155]
### Preconditions (*)
   Magento Version 2.3.5p2 and `2.4-develop`

  
1.I am adding product to wishlist from PDP and go to wishlist and edit the product then select or checked related products to go with main product but when i add to cart then only the main product goes in cart no related product adds in cart.

2.I checked with default does not work on that also.

### Steps to reproduce (*)

1.Go to PDP 
2. add product to Wishlist 
3. Edit Product in Wishlist 
4. Now on PDP 
5. Select or click on check box of related products 
6. Now Click on Add to Cart 
7. It will only add the main product not related product in cart.

### Expected result (*)

1. It should add all the products in cart main and related products.

### Actual result (*)

1. It is adding only main product not related product in cart/

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thinksys-charul** [comment]
Hi @magento-engcom-team @ajijshekh123 @jaywilliams ,
I found a fixed for the above bug. Below is the fix

I created a patch for the file vendor/magento/module-wishlist/Controller/Index/Cart.php in function execute after line 180 i put the below code and it fixed this bug.

`$related = $this->getRequest()->getParam('related_product');
           if (!empty($related)) {
               $this->cart->addProductsByIds(explode(',', $related));
            }`

**Comment by ajijshekh123** [comment]
Hi @thinksys-dev,

I have verified this issue with steps to be reproduced, actual result and expected result.
**PFA:**

![image](https://user-images.githubusercontent.com/24711761/94260790-66799f00-ff4e-11ea-9427-8957e53fb760.png)

![NewIssue](https://user-images.githubusercontent.com/24711761/94260867-890bb800-ff4e-11ea-812c-988a32f60bb0.png)

Thanks

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37945` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Sweetyagarwal** [comment]
@magento I am working on it.

**Comment by Sweetyagarwal** [comment]
#dmcdindia2020

**Comment by Sweetyagarwal** [comment]
#dmcdindia2020

**Comment by Sweetyagarwal** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
