### ISSUE TITLE
work as the docs, i got an warning report when set timezone = false|true

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#30151]
### Preconditions (*)
1. M2.4.0
2. PHP7.4
3. Docs: https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-datecolumn.html

### Steps to reproduce (*)
1. Create custom UI Listing with a date type column
2. Or try modify core UI Listing (eg: sales_order_grid.xml, column created_at) 
3. Add config timezone as docs: **`<timezone>false</timezone>`** like this

```
<column name="created_at" class="Magento\Ui\Component\Listing\Columns\Date" component="Magento_Ui/js/grid/columns/date">
    <settings>
        <filter>dateRange</filter>
        <dataType>date</dataType>
        <label translate="true">Purchase Date</label>
        <sorting>desc</sorting>
        <timezone>false</timezone>
    </settings>
</column>
```

4. Clear cache, reload page
5. Open Inspect, tab Console

### Expected result (*)
1. No warning report in Console tab

### Actual result (*)
1. Got an console warning: _moment-timezone-with-data.js:6 Moment Timezone has no data for false. See http://momentjs.com/timezone/docs/#/data-loading/_
2. SS [https://imgur.com/rW7GdFV](https://imgur.com/rW7GdFV)

### Note
By the momentjs docs: https://momentjs.com/timezone/docs/
moment.tz() should take a param as region timezone as string instead of bool type (ex: Europe/Madrid)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ilnytskyi** [comment]
We got similar issue on customer_listing.
@kamui23 have you managed to find any workaround ?

**Comment by ilnytskyi** [comment]
I think that in
`vendor/magento/module-ui/view/base/web/js/grid/columns/date.js`
this patch would work
```
            if (!this.timezone) {
                this.timezone = this.storeTimeZone;
            }
```

**Comment by aarontalcott** [comment]
```
--- a/vendor/magento/module-ui/view/base/web/js/grid/columns/date.js	(date 1608163508332)
+++ b/vendor/magento/module-ui/view/base/web/js/grid/columns/date.js	(date 1608163508332)
@@ -48,7 +48,7 @@

             date = moment.utc(this._super());

-            if (!_.isUndefined(this.timezone)) {
+            if (!_.isUndefined(this.timezone) && moment.tz.zone(this.timezone) !== null) {
                 date = date.tz(this.timezone);
             }



```

**Comment by ilnytskyi** [comment]
Another problem with this is that method
```
\Magento\Ui\Component\Listing\Columns\Date::prepareDataSource
```
tires to convert time on backend. Then module-ui/view/base/web/js/grid/columns/date.js would convert that time to UTC and apply the timezone, so we got wrong time on UI grids.

Workarounund to modify \Magento\Ui\Component\Listing\Columns\Date::prepareDataSource method 

```
    public function getConfiguration()
    {
        $config = parent::getConfiguration();

        if (!isset($config['timezone'])) {
            $config['timezone'] = 'UTC';
        }
        return $config;
    }
```

that would also fix problem in JS or just revert JS file to M2.3.4 version

**Comment by ilnytskyi** [comment]
Up

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41877` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by xtremevision** [comment]
Same here, Magento 2.4.3-p1, happens in the admin customer grid, and a custom listing. The customer grid is no longer sorting the records ascending/descending, regardless of which column I click on.

**Comment by MatthijsBreed** [comment]
For whoever this helps, I've had the same issue after adding a custom customer attribute of the type date.
However, after adding the following as view/adminhtml/ui_component/customer_listing.xml in my module, it works again:
`<columns name="customer_columns">
    <column name="customer_first_order" class="Magento\Ui\Component\Listing\Columns\Date" component="Magento_Ui/js/grid/columns/date" sortOrder="320">
        <settings>
            <timezone>false</timezone>
            <dateFormat>MMM d, y</dateFormat>
            <skipTimeZoneConversion>true</skipTimeZoneConversion>
            <filter>dateRange</filter>
            <dataType>date</dataType>
            <label translate="true">Customer First Order</label>
            <visible>false</visible>
        </settings>
    </column>
</columns>
`
