### ISSUE TITLE
Impossible to upgrade database after upgrading to Magento 2.4 - Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30161]
### Preconditions (*)

1. Fresh Magento 2.3.5-p2

### Steps to reproduce (*)

1. Change magento version in composer.json to 2.4.0
2. composer update
3. Login to Backend
4. You get "**There has been an error processing your request**" and a error log record number.
5. Lookup error message:

"Please upgrade your database"

6. Try to upgrade database with `bin/magento setup:upgrade`
7. Upgrade fails with `Could not validate a connection to Elasticsearch. No alive nodes found in your cluster`

Can't do anything, since you also cant use the magento backend to enter elasticsearch credentials, until you upgraded the database.

### Expected result (*)

1. Upgrade should work

### Actual result (*)

1. Upgrade fails with `Could not validate a connection to Elasticsearch. No alive nodes found in your cluster`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by KonstantinZhidkovskiy** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone 
Seems like you didn’t configured elasticsearch before upgrading.
Could you look on the following article https://community.magento.com/t5/Magento-DevBlog/Elasticsearch-is-the-default-catalog-search-engine-in-Magento-2/ba-p/447968 ?

**Comment by Eddcapone** [comment]
@ihor-sviziev , Thanks, I was not aware of this, maybe point such important information out in a place where everyone can see, for example the changelog.

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
I see that we have a notice one the Upgrade Magento page for 2.4 version. I think it's good enough.
![image](https://user-images.githubusercontent.com/1873745/94417064-48977e80-0188-11eb-8360-de9ff66e67d3.png)

**Comment by Eddcapone** [comment]
Oh thanks, somehow totally missed that.
