### ISSUE TITLE
Add ability to search by multiple keywords in Media Gallery

### ISSUE THREAD

**Issue by chalov-anton** [magento/magento2#30163]
### Description (*)
Now, _Search by keywords_ in Media Gallery can only find images by one single word. 
But what if I have a thousand images in the Media Gallery, and my search request by one word matches several images
![search_by_keywords](https://user-images.githubusercontent.com/45624059/82996229-589e2680-a00d-11ea-97ed-58e9be53bd28.png)

What if I would like to specify my search request simply by adding not one, but two or more keywords
![two_keywords](https://user-images.githubusercontent.com/45624059/82996490-b6327300-a00d-11ea-9f91-605d075b8bc9.png)

Now there is no ability to search by multiple keywords because such search request does not match any keyword

### Expected behavior (*)
Add the ability to search by multiple keywords in order user could specify his search

### Benefits
The easier and faster search of assets in the media gallery

### Additional information
Each additional work in search box should narrow down the results

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37867` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sivaschenko** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Hi @chalov-anton. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37867` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
