### ISSUE TITLE
FEATURE REQUEST: base configurable product uses one attribute product as the default

### ISSUE THREAD

**Issue by miketsl** [magento/magento2#3017]
Is it possible (easily) to make one of the attribute products the default for the base configurable product?  In other words, if I have black, red, and green watches.... someone clicks on the watch product, and the product details screen automagically shows a configurable default color.  Also, if someone hits "add cart" from the catalog grid, it adds the configurable default color item.

**Comment by antboiko** [comment]
Hello @miketsl , sorry for the delayed response. We've created internal ticket MAGETWO-53090 for this feature and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/FEATURE-REQUEST-base-configurable-product-uses-one-attribute/idi-p/46149).
