### ISSUE TITLE
Wrong product ratings showing at list view of product listing page

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#30196]
Wrong product ratings showing at list view of product listing page 

### Preconditions (*)
1. Magento 2.4
2. with sample data

### Steps to reproduce (*)
1. Product listing page like women/tops-women/jackets-women.html
2. Review the ratings at grid and same review at list view 
3. It shows the wrong ratings stars on list view 

### Expected result (*)
Correct rating star should be display at list view 

### Actual result (*)

Grid View:
![image_2020_09_26T06_50_04_203Z](https://user-images.githubusercontent.com/28681937/94332550-e3128900-fff3-11ea-8704-c2fd201bded4.png)

List View:

![image_2020_09_26T06_50_29_116Z](https://user-images.githubusercontent.com/28681937/94332556-e73ea680-fff3-11ea-955e-f6059bb76755.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37999` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by somat-211** [comment]
@magento I am working on this.

**Comment by somat-211** [comment]
@magento add to contributors team

**Comment by mrtuvn** [comment]
Still have one another place incorrect 
"In your review"
![Screenshot from 2020-09-29 23-28-36](https://user-images.githubusercontent.com/1908873/94586657-b1c3e280-02ab-11eb-9bc1-54e54394fedc.png)

**Comment by vikalps4** [comment]
#dmcdindia2020

**Comment by vikalps4** [comment]
@magento I am working on this.

**Comment by amitjoc** [comment]
Magento core team is working on this issue. 
We will deliver changes according to our internal process.
