### ISSUE TITLE
main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query:

### ISSUE THREAD

**Issue by developer-macrew** [magento/magento2#30194]
### Preconditions (*)

1.Magento version 2.4.0
2.Elasticsearch version 7

### Steps to reproduce (*)

1.After loading the page I am getting this error in exception log and system.log
2.

### Expected result (*)

1. Page should be loaded without any error
2.

### Actual result (*)

1. [2020-09-25 12:32:43] main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: For input string: \"114,190,192,448,465,467,468,470,473,474,478,481\"","index_uuid":"W8u0kMu7Sw6M_AGdbIF4uw","index":"magento2_product_1_v8"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v8","node":"KxBL7Iw8SV69LuPY3yto-A","reason":{"type":"query_shard_exception","reason":"failed to create query: For input string: \"114,190,192,448,465,467,468,470,473,474,478,481\"","index_uuid":"W8u0kMu7Sw6M_AGdbIF4uw","index":"magento2_product_1_v8","caused_by":{"type":"number_format_exception","reason":"For input string: \"114,190,192,448,465,467,468,470,473,474,478,481\""}}}]},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query: For input string: \\\"114,190,192,448,465,467,468,470,473,474,478,481\\\"\",\"index_uuid\":\"W8u0kMu7Sw6M_AGdbIF4uw\",\"index\":\"magento2_product_1_v8\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"magento2_product_1_v8\",\"node\":\"KxBL7Iw8SV69LuPY3yto-A\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query: For input string: \\\"114,190,192,448,465,467,468,470,473,474,478,481\\\"\",\"index_uuid\":\"W8u0kMu7Sw6M_AGdbIF4uw\",\"index\":\"magento2_product_1_v8\",\"caused_by\":{\"type\":\"number_format_exception\",\"reason\":\"For input string: \\\"114,190,192,448,465,467,468,470,473,474,478,481\\\"\"}}}]},\"status\":400} at /home/ahogucak/www/ahogucak.myhostpoint.ch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632)"} []
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @developer-macrew  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
No errors on page when it is loaded
![Peek 2020-10-05 16-45](https://user-images.githubusercontent.com/51681379/95087592-8f5a1b00-072a-11eb-90ae-88e5624e4e0c.gif)

**Comment by developer-macrew** [comment]
Hello @engcom-Delta 

This error I am getting in exception.log and system.log. I have contacted the hosting support but they said that there is no problem in elastic search. It is a problem in Magento. Magento not sending the valid request to elastic search.

**Comment by josiahglassone** [comment]
I am also getting this same error. Magento 2.4.0, Elasticsearch 7.

**Comment by Lach1222** [comment]
Also, get this error Magento 2.4.1 ES 7

**Comment by developer-macrew** [comment]
Hi @magento-engcom-team 
Why this issue closed without providing the solution?

**Comment by shuaiZend** [comment]
Also, get this error Magento 2.3.5-p1 ES 7

**Comment by JakobKjoller** [comment]
I am having the same issues on ver. 2.4.1 + Elastic 7.

**Comment by igormatkovic** [comment]
Same issue: 2.4.1 + Elastic 7

**Comment by TOIVI291** [comment]
Same issue for me with Magento 2.4.1 + Elasticsearch 7

**Comment by igormatkovic** [comment]
Did anybody try this with magento 2.4.2?

**Comment by tuyennn** [comment]
Shame magento where is your solution? bugs fix

**Comment by JonathanHelvey** [comment]
We are receiving an error similar to this in magneto 2.3.5 pt 2 + ES 7

**Comment by vitmarks** [comment]
same here

**Comment by siliconalchemy** [comment]
Hint: Magento don't care about closed issues, and they close them as quickly as they can (suspect they get paid by closed issue!).  No point bumping closed issues, raise new ones.
This is also covered in #30540.

**Comment by jamie-selesti** [comment]
as per #30540 I'm getting this issue on 2.4.2-p1 - This fixed it for me https://github.com/betagento/magento2_search_fixing

**Comment by DuySexy** [comment]
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Magento-2-4-1-ElasticSearch-7-9-1-not-working-suddenly/td-p/461464 this solution worked for me.

p/s: need clear cache and reindex
