### ISSUE TITLE
Showing exception while proceed to checkout

### ISSUE THREAD

**Issue by zarnaparekh03** [magento/magento2#30197]
**Preconditions (*)**
1. Magento version 2.4.0

**Steps to reproduce (*)**
1) Login into account and add more than one product to cart
2) go to view and edit cart
3) Check Out with Multiple Addresses
4) enter new address
5) select different adresses for product added to cart
6) go to shipping information
7) select different shipping methods for product added to cart
8) go to billing information
9) go to home page
10) from cart select proceed to checkout

**Expected result (*)**
1. User should redirect on checkout page

**Actual result (*)**
![magento2 4_checkout](https://user-images.githubusercontent.com/71920319/94335297-3c7cb700-fff8-11ea-9880-f29dd2580d26.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38000` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zarnaparekh03** [comment]
@magento I am working on this

**Comment by engcom-Oscar** [comment]
Fixed https://github.com/magento-tsg/inventory/tree/MC-38000

**Comment by sdzhepa** [comment]
The issue was fixed and delivered into the inventory repo
here is the public available link https://github.com/magento/inventory/commit/99c2f48f0c3313edb13feecc1704aa7024e3bcdc
