### ISSUE TITLE
Bug - Blank value for field type password/obscure when switching store view in store config

### ISSUE THREAD

**Issue by srenon** [magento/magento2#3019]
![sc-1](https://cloud.githubusercontent.com/assets/1415141/12380161/171bd9ec-bd3a-11e5-8ce4-454ffd9a1bf3.png)
![sc-2](https://cloud.githubusercontent.com/assets/1415141/12380162/171cbd08-bd3a-11e5-9112-03b28a9fdc5f.png)

**Comment by mazhalai** [comment]
@srenon thank you for reporting, we have created MAGETWO-48100 to investigate.

**Comment by wert2all** [comment]
Fixed
