### ISSUE TITLE
Magento 2.3.4 Error: The file was not uploaded. Error code 666

### ISSUE THREAD

**Issue by GENIOUS123** [magento/magento2#30207]
### Preconditions (*)

1. Php Vesion 7.3
2.

1.
2.

### Expected result (*)
When Im trying to upload any image from system ajax error code 666 come
1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @GENIOUS123. Can you please explain the issue with all details like Steps to Reproduce,Expected and Actual Result
As without any of these details we can not move forward to verify this issue and will closed the issue
Thanks!!

**Comment by GENIOUS123** [comment]
Hi actually
I sorted out the problem
basically since there was no any exception throws by ajax so  it was
difficult to point the real issue
The issue was in my server php.ini file upload_temp_file was removed by any
means
So when i search for php info()
I found the bug  I JUST ADD temp folder location in my php.ini and give
permission 755
It was a very small bug but it was strange that I cannot find any to the
point solution in web

Thank you so much

**Comment by krishprakash** [comment]
That's great!! Closing this issue as non issue
Thanks!!
