### ISSUE TITLE
My Wish list: Product options not display in wish list once select it and added from product listing page

### ISSUE THREAD

**Issue by renard123** [magento/magento2#30201]
My Wish list: Product options not display in wish list once select it and added from product listing page

### Preconditions (*)
1. Magento 2.4 sample data

### Steps to reproduce (*)
1. Login into account
2. Product listing page -> Select product option and click on wish list
3. Review at My wish list page

### Expected result (*)
Product should be added into wish list

### Actual result (*)
Product not added into wishlist 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @renard123. Thank you for your report.
Issue is duplicate to #24091
