### ISSUE TITLE
after install MSG Protabs extension admin backend error please help Me out 

### ISSUE THREAD

**Issue by raghav111jain** [magento/magento2#30200]
1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 12

Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 12

<pre>#1 Magento\Framework\Acl\Builder\Proxy->getAcl() called at [vendor/magento/module-backend/Model/Auth/Session.php:229]
#2 Magento\Backend\Model\Auth\Session->processLogin() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:102]
#11 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor#0000000028f3fc3e0000000054109f20#, &Closure#0000000028f3fc210000000054109f20#, &Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [app/code/Webkul/Marketplace/Plugin/App/Action/Context.php:54]
#13 Webkul\Marketplace\Plugin\App\Action\Context->aroundDispatch(&Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor#0000000028f3fc3e0000000054109f20#, &Closure#0000000028f3fc210000000054109f20#, &Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#), NULL) called at [generated/code/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:39]
#16 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/App/FrontController.php:162]
#17 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#, &Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor#0000000028f3fc3e0000000054109f20#) called at [vendor/magento/framework/App/FrontController.php:98]
#18 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000028f3fe710000000054109f20#) called at [vendor/magento/framework/App/Http.php:116]
#23 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#24 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#25 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000028f3fe620000000054109f20#) called at [index.php:39]
</pre>

**Comment by krishprakash** [comment]
Hi @raghav111jain. It should be from 3rd party issue
GitHub issue tracker is intended for magento core technical issues only.
Kindly refer [magento stack exchange](https://magento.stackexchange.com/) or [community forum](https://community.magento.com/) for general discuss about this topic
Thank You!!
