### ISSUE TITLE
Bundles: tax class wrong when using fixed price

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#30204]
### Preconditions (*)

1. Magento 2.4.0

### Steps to reproduce (*)

1. create a bundle product
2. set "Dynamic Price" to "No"
3. Choose a tax class or leave at "none", does not matter
4. add at least 2 products with different tax class ids to bundle (e.g. 16% and 7%)
5. open product in frontend
6. add product/bundle with mixed tax classes to cart

### Expected result (*)

1. The resulting cart contents should have mixed tax classes taken from the bundle's options

### Actual result (*)

1. The cart's content only refers to one tax class which is the fixed class set in the bundle product instead of the mixed classes

Since a bundle is basically only "a bunch" of separate products each of those products in cart should be calculated with their own respective tax class.

**This behaviour does not apply when using dynamic pricing instead.**

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by OvalMedia** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment]
Hi @OvalMedia ,
Thank you for your report.
Described behavior of applying tax class for bundle product with fixed (non dynamic) price is as it have to be according documentation, so I'm closing this ticket as non issue: https://docs.magento.com/user-guide/catalog/product-create-bundle.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=bundl 
![image](https://user-images.githubusercontent.com/60198413/94426623-87343580-0196-11eb-960d-52eb35bc8cd2.png)

**Comment by OvalMedia** [comment]
The documentation may say so but it still does not make any sense. In my case I am selling a book (7%) and another hardware item (16%) together. Both are simple products that you can buy as stand alone as well. Why should their respective tax class depend on how I put them into the shopping cart?

How do you justify the forced tax class (from the bundle product) just because their bundled prices are fixed? What difference does it make from them being priced dynamically?

**Comment by OvalMedia** [comment]
Really? That's it? "It's in the docs, so there is no need to question it"?

**Comment by ahsan-horani-reviver** [comment]
That's not an appropriate answer @engcom-Oscar. This doesn't make any sense. Is there any work around for that? This does not fit the business requirements

**Comment by ahsan-horani-reviver** [comment]
Also, please mention the reason why do we have such limitation in Magento

**Comment by OvalMedia** [comment]
Thank you!

**Comment by ahsan-horani-reviver** [comment]
@OvalMedia - Have you found any solution?

**Comment by OvalMedia** [comment]
I have not. I filed this under "Magento/Adobe does not give an F".

**Comment by navarr** [comment]
The problem here is likely that, at least in the states, taxing bundles is complicated.

For example, most states rule that if you have a bundle and its a combination of taxable and non-taxable items, the entire bundle is taxed.

As such, there's no "good way" for Magento to natively handle these scenarios.
