### ISSUE TITLE
Install sample data using the command line: Too many arguments

### ISSUE THREAD

**Issue by jkristoffer** [magento/magento2#3021]
I'm on `develop` branch on commit `3991d65ea5b4c91b39f130ceadac7e413233ada6`

I tried installing sample data using the Magento CLI from the [documentation](http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data-cli.html) and this is the result

```
[root@f6d354ebfaa4 magento2]# ./bin/magento sampledata:deploy magento/module-bundle-sample-data



  [RuntimeException]   
  Too many arguments.  



sampledata:deploy
```

**Comment by DavideLitrico** [comment]
I have the same problem

**Comment by ghost** [comment]
If you installed Magento 2 by cloning, you must also install sample data by cloning and you cannot use the `sampledata:deploy` command.

Instead, try [this](http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data-clone.html)

**Comment by DavideLitrico** [comment]
I installed magento 2 with composer

**Comment by ghost** [comment]
OK, my apologies but I learned yesterday that sampledata:deploy has no arguments. I updated the documentation. Sorry for the trouble.

**Comment by mazhalai** [comment]
@jkristoffer @DavideLitrico Since this was a doc issue, which has been fixed, closing this ticket.
