### ISSUE TITLE
Purchase order date filter rectrieves next day date orders as well for admin order grid

### ISSUE THREAD

**Issue by arsalanworld** [magento/magento2#30214]
### Summary
Purchase Order date filter is retrieving additional data from next day orders which were placed at 3 hours at the beginning of the day. 
### Preconditions (*)

1. Magento 2.4-develop
2. Make sure you have selected your store timezone other than UTC
3. Your local time is between 12AM - 3AM (or try changing manually).

### Steps to reproduce (*)

1. Make sure your local time is set between day first 3 hours i.e 12AM to 3AM.
2. Place an order from magento frontend.
3. Login to your magento admin panel and navigate to sales > orders.
4. Filter the purchase date between the dates which are between one day before newly placed order. If order was placed on 28 Sep morning 2AM, then try to filter the range between 26Sep 2020 - 27 Sep 2020.
5. Filter the results now and in results you will notice the additional order is also included.

### Expected result (*)

1. The filter should correctly fetch data between two specified dates, for example: 26 Sep 2020 - 27 Sep 2020
2. No additional data should be included in results from next day

### Actual result (*)

1. We get Additional data from next day as well.
2. The filtered data range is not exact.

![order_grid_2](https://user-images.githubusercontent.com/7779579/94413285-505d2000-0194-11eb-96b3-ce47592d3f7c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by arsalanworld** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38020` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by tuanpt-0634** [comment]
@arsalanworld Hi, we have same issue, did you solve it?

The commit introduce this bug is: https://github.com/magento/magento2/commit/f5a7ac98dadb79e5c994fee06a5e03b8346e1671#diff-a77f91c3444a6de1de363aee3ec34916d30641fe4d3831c7d1b759a570017fb1L114

```diff
-            $dateObj = $this->localeDate->date($date, $this->getLocale(), true);
+            $dateObj = $this->localeDate->date($date, $this->getLocale(), false);
```

But we cannot know the reference issue on that commit

@magento-engcom-team Could you check this?

**Comment by HenKun** [comment]
@arsalanworld @tuanpt-0634 Is the issue solved for anyone? This is simply a bug. Should we reopen the issue or open a new one?

**Comment by ia-gaurav** [comment]
can this be fixed in later release ?

**Comment by dtamajon** [comment]
I confirm the bus as explained by @tuanpt-0634. 

I don't know the effect of rolling back the change in that particular line for the whole project but for filtering orders works properly.

**Comment by tuanpt-0634** [comment]
Hi @HenKun @dtamajon @ia-gaurav 
FYI, I think it is fixed by this commit https://github.com/magento/magento2/commit/aa38466d5222ea0923a339922a185098a661b490
