### ISSUE TITLE
Validation pool type Availability not working before checkout renders

### ISSUE THREAD

**Issue by JeffersonTeixeira** [magento/magento2#30211]
### Summary (*)
I'm developing a Payment Module in Magento 2.4.0 (Using Facade). I'm having problem with Validation Pool as described by title. I'm following the documentation: https://devdocs.magento.com/guides/v2.4/payments-integrations/base-integration/facade-configuration.html#validators_pool

Validators of type Country and Currency are called with no problem before the checkout renders, so if the method validate: `return $this->createResult(false)`  //not valid
**(\Magento\Payment\Gateway\Validator\AbstractValidator)**
The radio button of payment method is not rendered, as expected. But for the type **availability** its not working. 

### Examples (*)
Forcing the availability validator method to return false currently makes the payment method renders but when user click in place order shows an error informing that the payment is not available ("The requested Payment Method is not available.") once the second time the method getInfoInstance() doesn't return null anymore.
Once I think is not desired that user lost time filling all fields to get know only after place order that payment method is not available I'm reporting this issue.

### Proposed solution
I've been debugging and the reason I guess, is because the method `$this->getInfoInstance()` is returning null at first call (before checkout render payment methods) in the file Magento\Payment\Model\Method\Adapter at method isAvailable() [line 289].
 My Virtual type in di.xml:

`    <virtualType name="CcValidatorPool" type="Magento\Payment\Gateway\Validator\ValidatorPool">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="availability" xsi:type="string">Jcustom\Pagseguro\Gateway\ValidatorPool\CcEnabled</item>
            </argument>
        </arguments>
    </virtualType>
`

---
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JeffersonTeixeira** [comment]
@magento give me 2.4-develop instance

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instanc

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by chiragrajput** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
@chiragrajput thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by JeffersonTeixeira** [comment]
The issue stills present but I was not able to fix it. I someone want to... I won't work on it anymore.

**Comment by ksenia-zlotin** [comment]
Hi @JeffersonTeixeira  - I have been working on Magento applications for a little under 2 years now - hardly an expert. I was experiencing the exact issue you were - getInfoInstance() being null and therefore not running my custom payment method validators. However, I believe I found a way to implement a custom validator (in my case - availability) while using the recommended payment facades approach to implement the many different custom payment methods I needed to implement:
- Instead of using type Adapter in the facade I used a custom type that **extends** the core Adapter
di.xml
```
<virtualType name="CustomFacade" type="Vendor\Module\Model\Method\CustomAdapter">
        <arguments>
            <argument name="code" xsi:type="const">Vendor\Module\Model\Ui\Custom\ConfigProvider::CODE</argument>
            <argument name="formBlockType" xsi:type="string">Magento\Payment\Block\Form\Cc</argument>
            <argument name="infoBlockType" xsi:type="string">Magento\Payment\Block\Info</argument>
            <argument name="valueHandlerPool" xsi:type="object">CustomValueHandlerPool</argument>
            <argument name="validatorPool" xsi:type="object">CustomValidatorPool</argument>
            <argument name="commandPool" xsi:type="object">CustomCommandPool</argument>
        </arguments>
    </virtualType>
    <virtualType name="CustomValidatorPool" type="Magento\Payment\Gateway\Validator\ValidatorPool">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="country" xsi:type="string">CustomCountryValidator</item>
                <item name="availability" xsi:type="string">Vendor\Module\Gateway\Custom\Validator\AvailabilityValidator</item>
            </argument>
        </arguments>
    </virtualType>
    <virtualType name="CustomCountryValidator" type="Magento\Payment\Gateway\Validator\CountryValidator">
        <arguments>
            <argument name="config" xsi:type="object">CustomConfig</argument>
        </arguments>
    </virtualType>
```

Then the custom Adapter class looks like
```
class CustomAdapter extends \Magento\Payment\Model\Method\Adapter
{
    /**
     * @var AvailabilityValidator
     */
    protected $availabilityValidator;

    public function __construct(
        ManagerInterface $eventManager,
        ValueHandlerPoolInterface $valueHandlerPool,
        PaymentDataObjectFactory $paymentDataObjectFactory,
        $code,
        $formBlockType,
        $infoBlockType,
        AvailabilityValidator $availabilityValidator,
        CommandPoolInterface $commandPool = null,
        ValidatorPoolInterface $validatorPool = null,
        CommandManagerInterface $commandExecutor = null,
        LoggerInterface $logger = null
    ) {
        parent::__construct(
            $eventManager,
            $valueHandlerPool,
            $paymentDataObjectFactory,
            $code,
            $formBlockType,
            $infoBlockType,
            $commandPool,
            $validatorPool,
            $commandExecutor,
            $logger
        );

        $this->availabilityValidator = $availabilityValidator;
    }

    /**
     * Check whether payment method can be used
     *
     * @param \Magento\Quote\Api\Data\CartInterface|Quote|null $quote
     * @return bool
     */
    public function isAvailable(\Magento\Quote\Api\Data\CartInterface $quote = null)
    {
        return parent::isAvailable($quote) && $this->availabilityValidator->validate([])->isValid();
    }
}
```
