### ISSUE TITLE
Magento 2.3.4 - (/dev/shm) tmpfs folder getting full

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#30225]
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.3

### Steps to reproduce (*)

1. 
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. tmpfs (7.8G) disk getting full and website crashing 
2. The below error appears when the site crashes.

SQLSTATE[HY000]: General error: 1021 Disk full (/dev/shm/#sql_2e1b28_7.MAI); waiting for someone to free some space... (errno: 28 "No space left on device"), query was: SELECT main_table.* FROM eav_attribute AS main_table
INNER JOIN eav_entity_type AS entity_type ON main_table.entity_type_id = entity_type.entity_type_id
LEFT JOIN eav_entity_attribute ON main_table.attribute_id = eav_entity_attribute.attribute_id
INNER JOIN catalog_eav_attribute AS additional_table ON main_table.attribute_id = additional_table.attribute_id WHERE (entity_type_code = 'catalog_product') AND ((additional_table.is_used_in_grid = 1)) GROUP BY main_table.attribute_id

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @gilbertsohal.
The error is provided by your SQL server, You have to make space in server side, it doesn't have free space and can't execute any queries.
GitHub issue tacker is intended for Magento core technical issues only
Kindly refer community forum or Magento stack exchange for general discuss about this topic.
