### ISSUE TITLE
Not possible to override knockoutjs template located in base folder, from my module

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30228]
### Summary (*)
I need to change the value of the maxinput field in the knockoutjs template **vendor\magento\module-ui\view\base\web\templates\form\element\input.html**.

The file is the template for input fields in the admin backend, for example in the product view:

![image](https://user-images.githubusercontent.com/16349349/94558966-da72ba80-0260-11eb-9417-eaedf285149d.png)

 so I have to replace the template with my own template loaded from my module `app\code\Company\Base\view\base\web\templates\form\element\input.html`.

### Examples (*)

So I created a **requirejs-config.js** file in my module and tried to override the original knockoutjs file:

**app\code\Company\Base\view\frontend\requirejs-config.js**:

    var config = {
        map: {
            '*': {
                'Magento_Ui/templates/form/element/input':'Company_Base/templates/form/element/input'
            }
        }
    };

I even tried the full path:

```
var config = {
    map: {
        '*': {
            'Magento_Ui/view/base/web/templates/form/element/input':'Company_Base/view/base/web/templates/form/element/input'
        }
    }
};
```

...then I cleared the cache, but it is still loading the original template instead of mine.
I've also tried to move the requirejs-config.js file into **app\code\Company\Base\view\base\** but it doesn't work either.

I couldn't find a documentation entry about how to override knockoutjs files either.

### Proposed solution
I have no idea. I also asked on [magento.stackexchange](https://magento.stackexchange.com/questions/323215/magento-2-override-knockoutjs-template-located-in-base-folder), but no one has a clue yet. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
You should use mixin if you want to add additional logic or rewrite some path from original component. For template you should copy to theme. Depends on how change you want

**Comment by Eddcapone** [comment]
> "You should use mixin if you want to add additional logic or rewrite some path from original component"

Can you show me where this is described in the documentation please? Where can I find out how that works?

> For template you should copy to theme

I need the template in my module though, does it not work in module?

**Comment by mrtuvn** [comment]
https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_mixins.html

**Comment by Eddcapone** [comment]
@mrtuvn , I have read through the documentation entry but it does describe how to add more functionality to existing javascript files, it does not show how to override a template. Can you explain why you suggested mixins? It makes no sense to me.

**Comment by mrtuvn** [comment]
But seem you are doing wrong reference to js component in file requirejs-config.js
This should be
`var config = {
    map: {
        '*': {
            'Magento_Ui/js/form/element/abstract':'Company_Base/js/form/element/abstract-ext'
        }
    }
};`
This will use Company_Base/js/form/element/abstract-ext instead default

OR you can define extended component extend origin with mixin like below

`var config = {
    config: {
        mixins: {
            'Magento_Ui/js/form/element/abstract': {
                'Company_Base/js/form/element/abstract-ext': true,
            }
        },
    }
};`

**Comment by Eddcapone** [comment]
But I don't want to override `Magento_Ui/js/form/element/abstract`, I want to override `Magento_Ui/templates/form/element/input`

**Comment by mrtuvn** [comment]
abstract component hold template relate with the template that you want to modify

**Comment by Eddcapone** [comment]
So I have to override abstract.js in my own template? Then how can I override the template input.html from it with my own?

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/form/element/abstract.js#L26

**Comment by Eddcapone** [comment]
But what do I have to put instead of `elementTmpl: 'ui/form/element/input',` ?

**Comment by Eddcapone** [comment]
If I change the line to `elementTmpl: 'ui/form/element/foobar123',` then the inputs for example in product view in backend, still works. So this file does not have something to do with the input as it seems.

**Comment by mrtuvn** [comment]
For such case i think you should create your own component but extend from abstract component `Magento_Ui/js/form/element/abstract` In this new component you can define elementTmpl to your file template
Should not modify directly to core component
Is this template work in backend or frontend ?

**Comment by Eddcapone** [comment]
@mrtuvn first I like to thank you that you are still helping me! Appreciate it! :) 👍 
I added a screenshot to my question at the very top:

![image](https://user-images.githubusercontent.com/16349349/94558966-da72ba80-0260-11eb-9417-eaedf285149d.png)

The template is controling the input fields in the backend, for example in product view.

> For such case i think you should create your own component but extend from abstract component Magento_Ui/js/form/element/abstract In this new component you can define elementTmpl to your file template
> Should not modify directly to core component

But even replacing the line in the core abstract.js does not work, so overriding abstract.js wont work too.

**Comment by mrtuvn** [comment]
first i don't think you can replace template inside file requirejs-config like your top describe

second if you only want to change file template you can copy file to theme admin with this path
app/design/adminhtml/Magento/backend/Magento_Ui/web/templates/form/element/input.html <= this one will replace with file with same path in app/code/Magento/Ui

If you don't want that way you can place files in custom module with custom js and custom template <= this is best option here

**Comment by Eddcapone** [comment]
Hello @mrtuvn , we are one big step further now, thx! I moved the _input.html_ to **view\adminhtml\web\template\form\element\input.html**, now it loads if I replace `elementTmpl: "ui/form/element/input"` with `elementTmpl: "Company_Base/form/element/input"` in `vendor\magento\module-ui\view\base\web\js\form\element\abstract.js`

But I restored the core abstract.js to its original state and added your file `app\code\Company\Base\view\adminhtml\web\js\form\element\abstract-ext.js` instead:

```
/*
 * In this file I override the template 'vendor\magento\module-ui\view\base\web\templates\form\element\input.html'
 * with my own under 'view\adminhtml\web\template\form\element\input.html' 
 */

define(['ko'], function(ko) {
   'use strict';

   return function (Abstract) {
       return Abstract.extend({
           defaults: {
               elementTmpl: "Hausfux_Base/form/element/input"
           },

           initialize: function() {
               this._super();

               return this;
           }
       });
   };
});
```
But then it loads the original input.html again.

**Comment by Eddcapone** [comment]
I finally solved it by using this **requirejs-config.js** ...:

**app\code\Company\Base\view\base\requirejs-config.js**:

```
var config = { 
    config: {
        mixins: {
            'Magento_Ui/js/form/element/abstract': {
                'Company_Base/js/form/element/abstract-ext': true
            }
        }
    }
};
```
...and this **app\code\Company\Base\view\adminhtml\web\js\form\element\abstract-ext.js**:


```
define(['uiElement'], function(uiElement) {
    'use strict';

    return function (uiElement) {
        return uiElement.extend({
            defaults: {
                elementTmpl: "Company_Base/form/element/input"
            },

            initialize: function() {
                this._super();

                return this;
            }
        });
    };
});
```


Credits to @mrtuvn for pointing me in the right direction!!
