### ISSUE TITLE
Feature ... Duo (or Google Authenticator) ... Two Factor Authentication Support for Magento2

### ISSUE THREAD

**Issue by MonteShaffer** [magento/magento2#3022]
I am swimming around the code for magento-backend (within Model and App), trying to figure out how in the world I would hook into Magento2 authentication for creating my own Duo Two Factor Support.

isLoggedIn ??

Sentry Human Element developed one for the OLD CE 1.9
http://www.human-element.com/sentry-two-factor-authentication-documentation/

And if you look at their code, they are really using a library from the DUO website itself...
https://github.com/duosecurity/duo_php

Certainly other authenticators (like Google) could easily be introduced.

Of note, there needs to be some backend-manually recovery if the DUO fails.... some file in the folder structure with a force bypass.

e.g.,

bypass-duo = true;

So the admin tool would have a toggle (enable/disable DUO, just for backend), and if DUO is enabled in the system, but this text file is true, it would disable, allowing admins into the system.

An example of Wordpress plugin ...
https://wordpress.org/plugins/duo-wordpress/

This increases security tremendously.

Anyway, I believe this should be a core feature (as a system->configuration->option), so I am proposing this as a feature.

**Comment by piotrekkaminski** [comment]
This is internally tracked as MAGETWO-35358 and tentatively scheduled for early next year.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Duo-or-Google-Authenticator-Two-Factor-Authentication/idi-p/46146).
