### ISSUE TITLE
Feature ... Captcha variants

### ISSUE THREAD

**Issue by MonteShaffer** [magento/magento2#3023]
I have noticed that the Captcha plugin is available, and I have implemented in my Magento 2 store.

However, in the past, I have used much simpler Captcha plugins, and am curious why this version is considered the core, without the option to choose from one of several Captcha plugins.  A little counter-intuitive to the abstraction goals of Magento 2.

For example, Visual Captcha ... drag and drop an icon ... or click on an icon to prove you are a human.

https://github.com/emotionLoop/visualCaptcha-PHP

**Comment by MonteShaffer** [comment]
Google's recaptcha is another solution, with a RESTFUL API
https://www.google.com/recaptcha/intro/index.html
https://github.com/google/recaptcha
https://developers.google.com/recaptcha/docs/start?hl=en

**Comment by MonteShaffer** [comment]
What does PROD label mean?

**Comment by mazhalai** [comment]
PROD label means it needs to be address by the Product team.

**Comment by pboisvert** [comment]
adding @piotrekkaminski as security PM owner

**Comment by piotrekkaminski** [comment]
This is on the roadmap, tentatively scheduled for next year. Internal ticket MAGETWO-46399.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Captcha-variants/idi-p/46139).
