### ISSUE TITLE
setup:di:compile error LinkedProductSelectBuilderComposite::build($productId)

### ISSUE THREAD

**Issue by xgiovio** [magento/magento2#30233]
### Preconditions (*)

1.magento 2.4.0
2.php 7.3

### Steps to reproduce (*)

1. bin/magento setup:di:compile

### Expected result (*)

1. compilation completed

### Actual result (*)

1. Fatal error:  Declaration of Magento\ConfigurableProduct\Model\ResourceModel\Product\LinkedProductSelectBuilderComposite::build($productId) must be compatible with Magento\Catalog\Model\ResourceModel\Product\LinkedProductSelectBuilderInterface::build(int $productId, int $storeId): array in /var/www/vhosts/****/****/vendor/magento/module-configurable-product/Model/ResourceModel/Product/LinkedProductSelectBuilderComposite.php on line 18

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by hostep** [comment]
Strange, the `LinkedProductSelectBuilderComposite` class was [removed](https://github.com/magento/magento2/commit/76b348d90f74b8f4857829b84d4f736acdbf186c#diff-b579662857d6e88cebf736d22b58dd09) in Magento 2.3.4

How come the file `vendor/magento/module-configurable-product/Model/ResourceModel/Product/LinkedProductSelectBuilderComposite.php` exists if you are running Magento 2.4.0? It shouldn't be there ...

**Comment by xgiovio** [comment]
interesting. Maybe during the rsync i forgot the --delete tag. Let me see and thank you for the answer. Upgrading manually, what files can be retained between updates?

**Comment by xgiovio** [comment]
solved resetting vendor folder. Problem was relative to a vanilla installation without removing the vendor folder. My fault.
