### ISSUE TITLE
Error While - Advance Js Bundling

### ISSUE THREAD

**Issue by ravibhalodia** [magento/magento2#30246]
### Preconditions (*)

1. Magento version 2.4.0
2. Running commands for Advance JS Bundling from https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html

### Steps to reproduce (*)

1. Steps till part #1 is fine
2. In Part #2 - Generate Bundles - 

Step 2.1 and 2.2 - Generate static store sites & Move the static store content to a temp directory are working fine.  

But with step 2.3 - Run the r.js optimizer with command 

**r.js -o build.js baseUrl=pub/static/frontend/Magento/luma/en_US_tmp dir=pub/static/frontend/Magento/luma/en_US** 

throws the error. 

### Expected result (*)

This command generates bundles in a bundles subdirectory of the target directory, which in this case results in pub/static/frontend/Magento/luma/en_US/bundles.

### Actual result (*)

> Tracing dependencies for: requirejs/require
> 
> Tracing dependencies for: bundles/default
> Error: ENOENT: no such file or directory, open '/var/www/vhosts/mage24/webroot/pub/static/frontend/Magento/luma/en_US/jquery-ui-modules/resizable.js'
> In module tree:
>     Magento_Ui/js/core/app
>       Magento_Ui/js/lib/knockout/bootstrap
>         Magento_Ui/js/lib/knockout/bindings/bootstrap
>           Magento_Ui/js/lib/knockout/bindings/resizable
> 
> Error: Error: ENOENT: no such file or directory, open '/var/www/vhosts/mage24/webroot/pub/static/frontend/Magento/luma/en_US/jquery-ui-modules/resizable.js'
> In module tree:
>     Magento_Ui/js/core/app
>       Magento_Ui/js/lib/knockout/bootstrap
>         Magento_Ui/js/lib/knockout/bindings/bootstrap
>           Magento_Ui/js/lib/knockout/bindings/resizable
> 
>     at Object.fs.openSync (fs.js:646:18)

**Comment by gwharton** [comment]
Imho advanced bundling should be deprecated in favour of magepack which does the same, but without the headache.

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Lima** [comment]
Hi @ravibhalodia,

I tried to reproduce the issue but no luck in Magento v.2.4-develop. When i ran - r.js -o build.js baseUrl=pub/static/frontend/Magento/luma/en_US_tmp dir=pub/static/frontend/Magento/luma/en_US

I got the error - "command not found: r.js"
 
Can you please provide the reproducible steps in magento 2.4-develop with screenshots or details?

**Comment by hostep** [comment]
@engcom-Lima: r.js can be downloaded here: https://requirejs.org/docs/download.html#rjs, maybe you should first read the documentation around advanced js bundling and download [the requirements for it](https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html#required-tools)?

**Comment by engcom-Lima** [comment]
Hi @ravibhalodia,

I went through the document and followed all the steps:
- Installed the nodejs
- installed the npm
- Installed the requirejs
- Created the build.js file in magento root folder
- Ran the r.js -o build.js baseUrl=pub/static/frontend/Magento/luma/en_US_tmp dir=pub/static/frontend/Magento/luma/en_US
- Above command ran successfully without any error.

Can you please check your build.js file? Everything should be align properly. or you can share the code of build.js file i will review and try to resolve for you.

Thanks

**Comment by gwharton** [comment]
https://github.com/magento/magento2/issues/30246#issuecomment-748596781 :smile:

**Comment by engcom-Lima** [comment]
Hi,

We have tried with all the required steps as provided in the documentation for Advanced JS Bundling and were able to generate bundles as expected.

For more detailed explanation, please refer:
https://github.com/magento/magento2/issues/30246#issuecomment-863325213

Due to inactivity from the contributor after the explanation, closing this ticket.
