### ISSUE TITLE
Improvement: Allow custom error message when logging in

### ISSUE THREAD

**Issue by hiephm** [magento/magento2#3024]
Although Magento 2 allows hooking to event when logging in to add additional validations (just like Magento 1), there is no way to change the error message if those validation failed (e.g by throwing Exception) since a default message is used for general Exception: 

``` php
# \Magento\Customer\Controller\Account\LoginPost::execute()
                ...
                } catch (\Exception $e) {
                    $this->messageManager->addError(__('Invalid login or password.'));
                }
```

In the other hand, the same logic in Magento 1 is more customizable:

``` php
# \Mage_Customer_AccountController::loginPostAction()
                    switch ($e->getCode()) {
                        ...
                        default:
                            $message = $e->getMessage();
                    }
                    $session->addError($message);
```

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improvement-Allow-custom-error-message-when-logging-in/idi-p/45343).
