### ISSUE TITLE
The count of ratings is not matching with ratings displayed

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30258]
###### steps
* Install Magento with sample data
* Create 2 websites
* Create a new admin user with access only to the 2nd website
* Login as the new user
* Open Stores > Attribute > Rating
* see records found

**Actual Result**: 4 records found but one rating displayed

**Expected* *Result:** Count of  records should match with ratings displayed

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37145

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37145` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by solwininfotech** [comment]
@magento I am working on this

**Comment by Shubham0492** [comment]
@magento I am working on this

**Comment by Shubham0492** [comment]
@magento give me 2.4-develop instance

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-37145` was closed as `Fixed`.
Related commits can be found by search https://github.com/magento/magento2/search?q=MC-37145&type=commits

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-37145` was closed as `Fixed`.
Changes was delivered into Magento Commerce(EE) repository.
If you are partner of have access to Magento Commerce(EE) code base,
Related commits can be found by search https://github.com/magento/partners-magento2ee/search?q=MC-37145&type=commits
