### ISSUE TITLE
Unexpected unchecking of "Append Comments" check-box

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30256]
Preconditions
1. Create simple product  

1. Create Customer with address
* First Name: John
* Last Name: Doe
* Email Address: john.doe@example.com(use real mail)
* Company: Magento
* Address: 6161 West Centinela Avenue
* City: Culver City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 555-55-555-55
 

Steps:
1. Go to admin -> sales -order -> create new order -> select customer
* Add Products => simple product
* add comments in Order Comments textarea
* Append Comments => yes
* Email Order Confirmation => yes
* click Get shipping methods and rates -> select shipping method 

(/) Expected result
"Append Comments" check-box should be checked

(x) Actual result
"Append Comments" check-box is unchecked

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37385

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37385` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
@magento I am working on it

**Comment by gulshanchitransh** [comment]
I am working on this @magento 
#dmcdindia2020

**Comment by gulshanchitransh** [comment]
@magento I am working on it

**Comment by gulshanchitransh** [comment]
@magento give me 2.4-develop instance

**Comment by SmVladyslav** [comment]
@magento I am working on this.
