### ISSUE TITLE
[GraphQL] Product query returns products in a different order between 2.40 and 2.4.1

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30254]
Query Used :
query {
    products(filter: \{ url_key: { eq: "gold-veritas-cuff-set" } }) {
        items {
            __typename
            id
            name
            sku
            url_key
        }
    }
}
 

Seeing an difference between 2.4.0 and 2.4.1 >  access any simple product which is part of group or bundled product  - example -  /gold-veritas-cuff-set.html
 2.4.0 returns simple product first and then grouped product  but in 2.4.1 its in reverse order so displaying Bundled/Grouped  instead of simple.
 2.4.0 - backend <https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/>
 2.4.1-alpha4 -backend  [https://staging-5em2ouy-mfwmkrjfqvbjk.us-4.magentosite.cloud](https://staging-5em2ouy-mfwmkrjfqvbjk.us-4.magentosite.cloud/) or <https://mcstaging-jnz3dtiuj77ca.dummycachetest.com/> 

!image (8).png!

!image (7).png!

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37618

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37618` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37618` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
