### ISSUE TITLE
Html tag <br> visible in message

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30251]
**Precondition:**

Install Magento 2.4.1

Create a simple product

Go to System->Export;

Select Entity TypeProducts and click "Continue";

Run php bin/magento cron:run;

Download the created export file;

**Step to Reproduced:**

Open the file with exported product and delete it's SKU. Save it

Go to **System -> Import**

Fill required fields and select exported file to import.
* **Entity Type:** Products;
* **Import Behavior:** Add/Update

Click on **Check Data**

**(/) Expected Result:**

Html tag **<br>** not visible

**(x) Actual Result:**

Html tag **<br>** visible in message

![image](https://user-images.githubusercontent.com/3409584/94734226-8afac000-032e-11eb-8091-dc0d89d982b5.png)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37922

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37922` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by irshadcedcoss** [comment]
https://github.com/magento/magento2/issues/30251

**Comment by irshadcedcoss** [comment]
@magento I am working on this

**Comment by irshadcedcoss** [comment]
@magento give me 2.4.1 develop instance

**Comment by irshadcedcoss** [comment]
#dmcdindia2020

**Comment by niravkrish** [comment]
@magento give me 2.4-develop instance

**Comment by niravkrish** [comment]
Hello,

I am not able to reproduce the issue in the 2.4-develop instance.
see screenshot for more details.
![screenshot-d5f8d8a0a0412c651cd0ce8581902edf-2-4-develop instances magento-community engineering-2020 10 19-11_01_20](https://user-images.githubusercontent.com/44108490/96405396-d3edb800-11fa-11eb-98b5-9b8a67e03ed6.png)

Thanks & Regards,
Nirav Patel

**Comment by sergiy-v** [comment]
@magento I am working on this

**Comment by zakdma** [comment]
@sergiy-v we are working on this task now.
Actually it on QA fase. Sorry for didn't assigned on our developer.

**Comment by sergiy-v** [comment]
@zakdma thanks for the info.

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by zakdma** [comment]
@magento add to contributors team

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37922` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.
