### ISSUE TITLE
Shopping cart is empty after adding simple product if another product was removed from Multiple Addresses checkout before

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30259]
**Preconditions**
* Magento EE 2.4.1 is installed and should be actual for CE
* A Customer account is created
* A Simple Product is created

**Steps to Reproduce:**
* Go to the storefront as the created Customer
* Add to card any simple product
* Select View and Edit card and go to Check Out with Multiple Addresses
* Remove previously added item
* Add to card any simple product from category page again

**(/) Expected results:**
* Simple product added to card

**(x) Actual results:**
* Shopping cart is empty

![mc_37120](https://user-images.githubusercontent.com/3409584/94736209-7a981480-0331-11eb-90f3-572223d1e274.gif)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37120

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37120` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Fixed in https://github.com/magento/magento2/search?q=MC-37120&type=commits
