### ISSUE TITLE
Test Issue: update issue confirmation validation 

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#30253]
### Preconditions (*)

 
1. h3. Steps to reproduce (*)

1. h3. Expected result (*)

1. <Screenshots, logs or description]
1. h3. Actual result (*)

[!--- Tell us what happened instead. Include error messages and issues. --]
1. [Screenshots, logs or description>
1. h2.  

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
 - < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38119` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
