### ISSUE TITLE
Order Details Page Shows Incorrect Total Number Of Products For Configurable, Bundle, Grouped Products

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30264]
#### Issue
If an order has over 20 products, then a customer's Order Details page will have pagination. At the top of the order, it tells the user how many products are on the current page & in total in the order. Configurable products, bundled products, grouped products, & their child products are counted in this total. This results in the total being off by 1 for each of those product types. The actual total is correct (it's just the counter text that is wrong). See screenshots

### Preconditions
magento 2.4-develop

### Expectations
1. Total count text matches actual count. Only count child products of grouped, bundled, & configurable products

### Steps to Reproduce
1. Login on storefront
1. Add 20 different (unique) simple products to your cart
1. Add 1 customizable product to your cart
1. Checkout (note that cart page & order summary pages indicate that you are buying 21 products)
1. After checkout, go to Order Details page on storefront
1. Note issue

### Actual Result
![image](https://user-images.githubusercontent.com/3409584/94738946-cb117100-0335-11eb-9b17-2a9cf059c322.png)

![image](https://user-images.githubusercontent.com/3409584/94738965-cfd62500-0335-11eb-96f2-57b2a2b9c0be.png)

![image](https://user-images.githubusercontent.com/3409584/94738975-d4024280-0335-11eb-859f-02ef8f62ff4b.png)

### Expected result
The product pagination is correct. 20 products on the first page, 1 product on the second page

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36553

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36553` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gauravagarwal1001** [comment]
@magento I am working on this

**Comment by gauravagarwal1001** [comment]
#dmcdindia2020

**Comment by engcom-Alfa** [comment]
Closing the issue based on the [comments here](https://github.com/magento/magento2/pull/30398#issuecomment-1092780083).
