### ISSUE TITLE
“Wish list” section of the “Manage Shopping Cart” disappears after a customer add a product to the Wish list

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30269]
**Preconditions:**
* Magento EE, CE  2.4-develop, 2.4.1
* Reports are enabled (Stores → Configuraion →General -> Reports → General Options -> Enable Reports = “Yes”)
* A Customer account is created
* Create 2 or more simple products

**Steps to Reproduce:**
* Go to Magento Admin → Customers → All Customers →
 Select created Customer → click on the “Edit” link → click on the “Manage Shopping Cart” button → verify that “Wish list” section exists (“Wish list (0)”)
* Go to the storefront as the created Customer
* Add the created Product to the Wish List
* Refresh “Manage Shopping Cart” page in Magento Admin

**(/) Expected results:**

The name of “Wish list” section should display the number of the added product (for example, “Wish list (1)” )
 The name of the added products, their prices and quantities should be displayed in the grid of the section (see, the attached picture)

**(x) Actual results:**

The “Wish list” section is disappeared 

(!) If created only one product in the catalog, bug is not reproduce

Note: Please unskipp \Magento\AdvancedCheckout\Block\Adminhtml\Manage\Accordion\WishlistTest::testGetItemsCollection after bug fixing

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36307

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36307` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment]
@magento I am working on this.

**Comment by mallikaverma** [comment]
#dmcdindia2020

**Comment by engcom-Echo** [comment]
![Peek 2020-11-16 11-58](https://user-images.githubusercontent.com/51681435/99252553-cd615900-2817-11eb-8c9c-941aece8808c.gif)

I checked it again, and now this issue can't reproduce. So all that remains is to restore the mentioned above test.
Thank you for your collaboration.
