### ISSUE TITLE
getSalesOrderCollection not working? 

### ISSUE THREAD

**Issue by wiizzeer** [magento/magento2#3026]
Hello i try to get OrderCollection but this function ( getSalesOrderCollection() ) return NULL every time. in Magento/Sales/Model/Order.php

**Comment by Mulderua** [comment]
Hi @wiizzeer, \Magento\Sales\Model\Order::getSalesOrderCollection is not public function and cannot be called. You have to use \Magento\Sales\Model\OrderRepository.
