### ISSUE TITLE
SAFARI: endless deploy when admin try to add product in order

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30265]
**UPDATE**: this issue is not related to split database & is reproducible on a standard magento install using configuration from: MC-36141

Install Magento 240-p1 with split database and small data set (generate data).

You should have Safari browser.
1. Go admin - Sales - Create New Order
1. Select any customer from grid
1. Click Add Products
1. Select any Product, enter quantity
1. Click add "selected products to order" button 

**(x) Actual Result:**

Product is added to order

(/) **Expected result:**

Endless deploy icon appears.

**Workaround**: Refresh page.

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36543

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36543` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gauravagarwal1001** [comment]
#dmcdindia2020

**Comment by gauravagarwal1001** [comment]
@magento I am working on this

**Comment by gauravagarwal1001** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#31022 by @zaximus84 in 2.4-develop branch
Related commit(s):
 - [d01898822c090f5a04d616271bd94c8ae3679672](https://github.com/magento/magento2/commit/d01898822c090f5a04d616271bd94c8ae3679672)

The fix will be available with the upcoming 2.4.3 release.
