### ISSUE TITLE
Product still present in the Wish List after added to order

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30260]
Preconditions:
 1. Magento2ee 2.4.0-p1 with b2b is installed and should be actual for CE
 2. Create simple product
 3. Create Customer
 Steps:

1. Go to admin -> sales -> orders -> Created New Order -> Select Customer
 2. Add simple product to the Order
 3 Select Action => Move to Wish List
 4. click Update Items and Quantities button
 5. select checkbox 'Add To Order' => yes
 6. click Update Changes click

(/) Expected Result:
 Product moved to Order
 Wish List is empty

(x) Actual Result:
 Product moved to Order
 Wish List is not empty

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36779

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36779` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment]
@magento I am working on it

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario

1. Go to admin -> sales -> orders -> Created New Order -> Select Customer
2. Add simple product to the Order
3. Select Action => Move to Wish List
4. Click Update Items and Quantities button
![1](https://user-images.githubusercontent.com/67371013/101769701-0a0b3200-3af0-11eb-84f2-dd544111df3e.png)
5. Select checkbox 'Add To Order' => yes
6. Click Update Changes button
![2](https://user-images.githubusercontent.com/67371013/101769842-3fb01b00-3af0-11eb-998f-810b892ac06a.png)

**Before applying fix:**
The product has been added to Cart but still remained in the _Wish List_
![wish_list_before](https://user-images.githubusercontent.com/51680745/101770819-b7cb1080-3af1-11eb-91b1-308d1eb9007e.png)

**After applying fix**
Product moved to Order, wish List is empty
![3](https://user-images.githubusercontent.com/67371013/101770069-987fb380-3af0-11eb-8dad-122c6202abbc.png)
