### ISSUE TITLE
Shopping cart is not empty after order through Admin Panel in Customer

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30262]
**Precondition:**

Install Magento 2.4.0, 2.4.0-p1 EE,CE with **table_prefix**

Create Customer

Create a product

**Step to Reproduced:**

1. Go to Storefront and login the customer

2. Add Product to cart

3. Go to **Admin -> Customers -> All Customers**

4. Select the customer and click **Edit**

5. Click button **Manage Shopping Cart* and click the button *Create Order**

6. Fill required fields and click button **Submit Order**

7. Go to Storefront and Logout customer

8. Login customer

9. Go to Shopping Cart

**(/) Expected Result:**

Shopping cart is empty

**(x) Actual Result:**

Shopping cart is not empty

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36703

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36703` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
@magento I am working on this.

**Comment by vikalps4** [comment]
#dmcdindia2020

**Comment by SmVladyslav** [comment]
@magento I am working on this.

**Comment by SmVladyslav** [comment]
@magento add to contributors team

**Comment by SmVladyslav** [comment]
@magento I am working on this.
