### ISSUE TITLE
Unexpected behavior when an Admin is adding product to the Shopping cart by SKU if the custom website is set as default

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30263]
**Preconditions:**
* Magento EE,CE 2.4.0, EE,CE 2.4.0-p1{color} is installed
* Two websites are created (at least, one store and one view for each website) https://jira.corp.magento.com/browse/MC-10639
* The "New Test Website" is set as Default ( Stores > All Stores > click the "New Test Website" > check the "Set as Default" checkbox)
* A Simple Product is created (Product in Websites = Main Website,
 New Test Website)
* A Customer Account is created (Account Created In = Default Store View)

**Steps to Reproduce:**
* Go to the Magento Admin Panel > Customers> All Customers
* Select the created Customer
* Click the{color:#0747a6} "Edit" link
* Click the "Manage Sopping Cart" button
* Expand the "Add to Shopping Cart by SKU" section
* Enter the created Product SKU into the "SKU number" input field
* Enter some valid quantity into the "Qty" input field
* Click "Add selections to my cart" button
* Click the "Create New Order" button

**(/) Expected results:**
* Admin should stay in the Magento-Admin panel
* Created Product should appear in the "Shopping Cart Items" section grid

**(x) Actual results:**

Admin is redirected to the Storefront page = \`unsecure*base_url`websites/test*website/

*(see the attached file EE 2.4.0-p1. ADMIN ADD BY SKU CUSTOM SITE AS DEFAULT. mp4 )*

**(i) NOTE:** 
 Clicking browser "go back" button (left arrow) return an Admin to the Shopping Cart page
 Created Product appears in the "Shopping Cart Items" section grid

[mc-36685.zip](https://github.com/magento/magento2/files/5308188/mc-36685.zip)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36685

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36685` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36685` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
The issue was closed by mistake.
at this moment Magento team has fixed it, internal PR is ready(CR and QA passed) but not merged into the main code-base.
As soon as it will be merged related commits can be found using search based on internal ticket key MC-36685
Example: https://github.com/magento/magento2/search?q=MC-36685&type=commits

Sorry for inconvenience

**Comment by zakdma** [comment]
Internal ticket MC-36685 merged into mainline

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-36685` was closed as `Fixed`.
Related commits can be found by search https://github.com/magento/magento2/search?q=MC-36685&type=commits
