### ISSUE TITLE
“Product Reviews” can not be sorted by Admin on the Product page

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30270]
**Preconditions**:
* Magento EE 2.3.5-p2, EE 2.4.0, EE 2.4.1, EE 2.4.2-alpha1 is installed, should be actual for CE
* A Simple Product is created

**Steps to Reproduce:**
* Go to the Storefront as a guest
* Go to the created Product page
* Add at least 2 reviews
* Go to Magento Admin > Marketing > Pending Reviews
* Approve the added reviews
* Go to Magento Admin > Ctalog > Products
* Select the created Product
* Click the “Edit” link
* Open the “Product Reviews” section
* Sort “Product Reviews” for example, by ID, clicking the “ID” cell

**(/) Expected results:**

All records of “Product Reviews” grid should be sorted by selected parameter

**(x) Actual results:**

Records of “Product Reviews” grid are not sorted

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36265

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36265` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Chandresh22** [comment]
@magento add to contributors team

**Comment by Chandresh22** [comment]
@magento I am working on it

**Comment by Sweetyagarwal** [comment]
@magento I am working on it.

**Comment by Sweetyagarwal** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#30477 by @Chandresh22 in 2.4-develop branch
Related commit(s):
 - [4c5a1303fe4c7826024fd0d2119cec4de2a77d26](https://github.com/magento/magento2/commit/4c5a1303fe4c7826024fd0d2119cec4de2a77d26)
 - [4e80ef94826eb709bc5b8d96ad46f13f6fc4fe74](https://github.com/magento/magento2/commit/4e80ef94826eb709bc5b8d96ad46f13f6fc4fe74)
 - [c1eb748449eeac8a2549274f0306385bab394945](https://github.com/magento/magento2/commit/c1eb748449eeac8a2549274f0306385bab394945)
 - [1c6672ebaa52e4bf8c4e3cca1028a49c9883638d](https://github.com/magento/magento2/commit/1c6672ebaa52e4bf8c4e3cca1028a49c9883638d)
 - [9bd848ace10de40c7842ba222f208c873427152a](https://github.com/magento/magento2/commit/9bd848ace10de40c7842ba222f208c873427152a)
 - [f18ab233414717a5d6ac1168372470ace1552681](https://github.com/magento/magento2/commit/f18ab233414717a5d6ac1168372470ace1552681)
 - [da7bb72de5b630bc42ee59313f2f2dc953f9ecdd](https://github.com/magento/magento2/commit/da7bb72de5b630bc42ee59313f2f2dc953f9ecdd)
 - [379027f80007472cee9419684871ac157ff9c8db](https://github.com/magento/magento2/commit/379027f80007472cee9419684871ac157ff9c8db)
 - [be1d79a98253081ceb9bcf36f84fe6132f13a5b9](https://github.com/magento/magento2/commit/be1d79a98253081ceb9bcf36f84fe6132f13a5b9)
 - [3eb35534049555fa7730a54d996c4ba2afa4975f](https://github.com/magento/magento2/commit/3eb35534049555fa7730a54d996c4ba2afa4975f)
 - [998555278fd21a38525de2ff8d9006d7fa76591c](https://github.com/magento/magento2/commit/998555278fd21a38525de2ff8d9006d7fa76591c)

The fix will be available with the upcoming 2.4.3 release.
