### ISSUE TITLE
2.4.0 Can't edit attributes possible Temando Shipping related

### ISSUE THREAD

**Issue by haxor211** [magento/magento2#30277]
### Preconditions (*)

1. 2.4.0
2. Stores>Attributes>Product>Click attribute
3. I have upgraded from 2.3.4

### Steps to reproduce (*)

1. When clicking on attribute receiving an error, my wild guess its related to Temando Shipping being removed in 2.3.5
2. It happens with all attributes whether its default attributes or custom attributes.
3. It happens also if you click "Add attribute"

### Expected result (*)

1. [Screenshots, logs or description]
2. Edit attribute window

### Actual result (*)

1. [Screenshots, logs or description]
2. Getting this error 

`Call to undefined method Magento\Framework\Json\Helper\Data::getAttributeHiddenFields() in /data/www/pneumatig/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml:216`

**Comment by wagento-rajan** [comment]
@magento give me 2.4-develop instance

**Comment by wagento-rajan** [comment]
#dmcdindia2020

**Comment by peterjaap** [comment]
Running into the same problem.

The `getAttributeHiddenFields` method does not exist in the JSON helper, but it does exist in the `Magento\Catalog\Helper\Data` helper. This helper was used in 2.3.6; https://github.com/magento/magento2/blob/2.3.6/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml#L205

But in 2.4.0 this was changed to the JSON helper; https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml#L216

Changing this line;

`foreach ($jsonHelper->getAttributeHiddenFields() as $type => $fields):`

into:

`foreach ($this->helper(Magento\Catalog\Helper\Data::class)->getAttributeHiddenFields() as $type => $fields):`

fixes it.

**Comment by peterjaap** [comment]
Here's a patch I created to use with `vaimo/composer-packages`;

```
Fix can't edit product attributes due to missing method getAttributeHiddenFields

@package magento/module-catalog
@level 0
@link https://github.com/magento/magento2/issues/30277

diff --git view/adminhtml/templates/catalog/product/attribute/js.phtml view/adminhtml/templates/catalog/product/attribute/js.phtml
index 8dde701..81abb96 100644
--- view/adminhtml/templates/catalog/product/attribute/js.phtml
+++ view/adminhtml/templates/catalog/product/attribute/js.phtml
@@ -213,7 +213,7 @@ function switchDefaultValueField()
             setRowVisibility('frontend_class', false);
         break;
 script;
-foreach ($jsonHelper->getAttributeHiddenFields() as $type => $fields):
+foreach ($this->helper(Magento\Catalog\Helper\Data::class)->getAttributeHiddenFields() as $type => $fields):
             $scriptString .= <<<script
             case '{$block->escapeJs($type)}':
                 var isFrontTabHidden = false;

```

**Comment by engcom-Delta** [comment]
Hi @haxor211  thank you for your report, I'm not able to reproduce issue after upgrade on 2.4.1
**Manual testing scenario:**
- Install magento 2.3.4
- Upgrade to 2.4.1 using [docs](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
- Go to Stores->Product
- Click Add New Attribute

**Result:**
:heavy_check_mark:  New Product Attribute window is opened
:heavy_check_mark: No errors are shown
:heavy_check_mark: Previously created attribute is edited without errors

Also was checked this scenario after upgrade from 2.3.6 to 2.4.1

If you'd like to update the issue, please reopen it.

**Comment by antoniocarboni** [comment]
Same error migrating from 2.4.1 to 2.4.2.
I solved with @peterjaap patch. (Thank you :)
However the inconsistency on the class position  is evident with a quick glance.
The error appears only if Magento_Swatches module is disabled. This module override the wrong template with his own (which is correct).

**Comment by mayankzalavadia** [comment]
Thank @antoniocarboni Your answer is helpful for me. Its solve my issue.

**Comment by sermagnus** [comment]
I confirm that the problem is related to Magento_Swatches when disabled:
Thanks to @antoniocarboni

**Comment by mobweb** [comment]
Can also confirm that this issue occurred for me in 2.4.2 and I was also able to solve it by re-enabling _Magento_Swatches_.

**Comment by xsanz** [comment]
Hello,

Also facing same Issue here with 2.4.2-p2. But I don't agree solution is to re-enable Magento_Swatches.
Disabling a secondary module, like Magento_Swatches, shouldn't make crash the whole thing.

In my opinion, apply @peterjaap patch is best solution.

**Comment by xsanz** [comment]
Hello @peterjaap 

After appyling your patch despite being able to enter attribute to Edit, or click Add button to add new attribute,
I'm facing a 'getfronttab().show();' Javascript error that makes me unable to save attribute.

Someone else is having same problem?

Thank you

**Comment by darthbit** [comment]
problem still persists.. fix this, why is whole thing crashing when you disable 1 module, that should absolutelly not happen

**Comment by nahall** [comment]
I can confirm this issue. I have never had Temando Shipping installed but have the same error when Magento_Swatches is disabled. Enabling Magento_Swatches fixes it, but why should Magento_Swatches need to be enabled?

**Comment by marvinhinz** [comment]
Can confirm this issue still exists in 2.4.6-p3, when disabling the Magento_Swatches module.

**Comment by twosg** [comment]
With `Magento_Swatches` disabled, still alive in 2.4.7.

**Comment by iqbalhafizi** [comment]
the issue also exists on 2.4.5-p10 when the module_swatch is disabled
