### ISSUE TITLE
Favicon in admin panel

### ISSUE THREAD

**Issue by vpashovski** [magento/magento2#30273]
### Preconditions (*)

1. Magento ver. 2.3.5

### Steps to reproduce (*)
1. Upload Favicon for Default Store from Content -> Design -> Configurations -> HTML Head -> Favicon Icon

### Expected result (*)
1. To see Magento default favicon in Admin panel

### Actual result (*)
1. Favicon from default store is shown in Admin panel

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @vpashovski,
I have verified this issue in default Magento 2.4 Instance. After uploading the icon on the HTML HEAD > Favicon icon section, the Proper icon is showing on the admin panel.

**PFA:**

![image](https://user-images.githubusercontent.com/24711761/95042596-0e822b80-06f8-11eb-8e8a-86cfa233d0ab.png)

Issue not reproduced in Magento 2.4 Instance. So let me close this issue. If you have found this issue again you can reopen it.

Thanks.

**Comment by vpashovski** [comment]
Hi @ajijshekh123,
I can see that the Favicon from Default Store View is showing in admin panel from your image.
I'm expecting to see Magento default favicon in admin panel, not the one uploaded for Default Store View. This store view is for storefront not backend.
Correct me if I'm wrong but I think don't have to see storefront favicon in admin panel.

Thanks :)

**Comment by ajijshekh123** [comment]
Hi @vpashovski,
Let me verify again the Default Magento document and Magento Configuration. If this issue is faced with your expectation I will reopen the issue and confirm it.

Thanks :)

**Comment by vpashovski** [comment]
Hi @ajijshekh123 ,
Is there any progress with the verification :)
