### ISSUE TITLE
An error occurs when an Admin submits an order on behalf of a Customer in the Store View where the Customer is not registered

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30271]
**Preconditions:**
* Magento EE 2.4.0{color} is installed
* Two websites are created (at least, one store and one view for each website) https://jira.corp.magento.com/browse/MC-10639
* B2B is installed
* All B2B features are enabled
* A Simple Product is created (Product in Websites = Main Website,
 New Test Website)
* A Customer Account with Shipping and Billing address is created (Account Created In = Default Store View)

**Steps to Reproduce:**
* Go to the Magento Admin Panel > Sales > Orders
* Click the “Create New Order” button
* Select the created Customer
* Select “New Test Store View” option
* Click “Add Products” button
* Select the created Products
* Fill all required fields
* Click “Submit Order” button

**(/) Expected results:**
* Order should be created
* The second Customer Account for the created Customer should be created (Account Created In = New Test Store View)

**(x) Actual results:**
* Error message
 “There has been an error processing your request
 Exception printing is disabled by default for security reasons.”
 appears
* Using a “go back”browser button twice lead to the “Orders” page
* Error message {color:#de350b}“Invalid customer address id <Created Customer id>”{color}
* Order is created
* The Customer Account for the created Customer is created (Account Created In = New Test Store View)
 (*see the attached EE 2.4.0 ADMIN ORDER CUSTOM WEBSITE.mp4 and EE 2.4.0 ADMIN ORDER CUSTOM WEBSITE.png* )

**(!) NOTE: is not fully reproducible on EE 2.3.5-p2**
* Admin stays on the “Create New Order”
* Error message {color:#de350b}” Invalid customer address id <Created Customer id>”
 appears
* Order is created
* The Customer Account for the created Customer is created (Account Created In = New Test Store View)
 *(see the attached EE 2.3.5-p2 ADMIN ORDER CUSTOM WEBSITE.mp4)*

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36186

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36186` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rakhi98** [comment]
@magento I am working on this

**Comment by rakhi98** [comment]
@magento add to contributors team

**Comment by rakhi98** [comment]
@magento I am working on this

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-36186` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
