### ISSUE TITLE
Сannot activates an integration of Magento 2.4 with my application on the localhost environment

### ISSUE THREAD

**Issue by Goldeo** [magento/magento2#30272]
### Summary (*)

Сannot activates an integration of Magento 2.4 with my application on the localhost. I want to activate Magento integration for testing OAuth-based authentication, but I get the message:

"The attempt to post data to consumer failed due to an unexpected error. Please try again later."

### Examples (*)

https://i.stack.imgur.com/e00kV.png
https://i.stack.imgur.com/HNN2u.png
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@Goldeo I believe you don't have valid SSL certificate on your local machine? I think this is the reason for such behavior

**Comment by Goldeo** [comment]
> @Goldeo I believe you don't have valid SSL certificate on your local machine? Does callback and identity URLs are opening successfully in your browser? I think this is the reason for such behavior

Thanks for the tip. My application needs the HTTPS protocol (chrome warns about invalid SSL certificate but app opens in the browse). But for test Magento, I just run my React app with the HTTP protocol. I think if configure the SSL certificate, then everything will work as expected.

**Comment by ihor-sviziev** [comment]
@Goldeo so issue is solved? Can we close this issue?

**Comment by Goldeo** [comment]
> @Goldeo so issue is solved? Can we close this issue?

Yes. Thank you)
