### ISSUE TITLE
POST http://tool.local/rest/default/V1/inventory/source-items create item for non existing sku

### ISSUE THREAD

**Issue by pdpavel** [magento/magento2#30274]
### Preconditions (*)
Magento ver. 2.3.5-p1 EE

### Steps to reproduce (*)

1. ### check that product doesn't exist 000000000000010003
GET http://tool.local/index.php/rest/V1/products/000000000000010003
return will be {
  "message": "The product that was requested doesn't exist. Verify the product and try again."
}
2.  POST http://tool.local/rest/default/V1/inventory/source-items
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "sourceItems": [
    {
      "sku": "000000000000010003",
      "source_code": "10",
      "quantity": 1,
      "status": 1
    }]
}
In return you will get empty array []
3. check that source items exists
GET http://tool.local/index.php/rest/default/V1/inventory/source-items?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=000000000000010003&searchCriteria[filter_groups][0][filters][0][condition_type]=eq
Content-Type: application/json
Authorization: Bearer {{auth_token}}

You will get in return:
{
  "items": [
    {
      "sku": "000000000000010003",
      "source_code": "10",
      "quantity": 1,
      "status": 1
    }
  ],
  "search_criteria": {
    "filter_groups": [
      {
        "filters": [
          {
            "field": "sku",
            "value": "000000000000010003",
            "condition_type": "eq"
          }
        ]
      }
    ]
  },
  "total_count": 1
}

### Expected result (*)

1. to the 2d request get error, that product doesn't exist for provided sku and don't create source-item

### Actual result (*)

1. empty array returned []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pdpavel** [comment]
+ jack

**Comment by engcom-Alfa** [comment]
Hi @pdpavel . 
Looks like this issue related to MSI functionality. 
@sdzhepa Could you move this ticket to the Inventory repository?
Thanks!

**Comment by pdpavel** [comment]
It seems it is not possible to login to  https://edd4d74165c885bda5d5296011a09eb6-2-4-develop.instances.magento-community.engineering I see this https://drive.google.com/file/d/16jdoegUqZ0-UTikP299ZbdGwNYeT6LaN/view?usp=drivesdk
