### ISSUE TITLE
Bug in typography for different @font-format from woff and woff2

### ISSUE THREAD

**Issue by PierW** [magento/magento2#30288]
### Preconditions (*)

1. Magento 2.3.5

### Steps to reproduce (*)

1. Import a custom font  **.ttf, .eot or .otf** in your theme (not woff or woff2)
2. Import the font by the **.lib-font-face()** in less with @font-format **.ttf, .eot or .otf** like the [doc](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.html)

### Expected result (*)

1. That our new font is loaded and see that on the inspector (tab Network -> font)

### Actual result (*)

1. The font is not loaded. (I've fixed it, please see the pull request)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
i have same pr for this https://github.com/magento/magento2/pull/29726

**Comment by engcom-Alfa** [comment]
Duplicate of #29719

**Comment by PierW** [comment]
Fixed with PR #29726
The fix will be available with the upcoming 2.4.2 release.
