### ISSUE TITLE
do not search unless a button is pressed.  

### ISSUE THREAD

**Issue by jdubyaw** [magento/magento2#30280]
### Preconditions (*)

1. when open page it does a research on previous search
2. it does it every time and waists minutes when it does

### Steps to reproduce (*)

1. open page from a previous search and it will immediately search
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @jdubyaw. Issue is not clear from provided description.
Can you please provide more information with magento version,Steps to Reproduce,Expected and Actual Result as per [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) so it will helpful to reproduce the issue

**Comment by krishprakash** [comment]
Hi @jdubyaw, Feel free to reopen the issue once you update all the necessary details to reproduce this issue
Thanks!!
