### ISSUE TITLE
Price range of a Bundle Product is displayed incorrectly in the case of options with tier price

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30284]
**Preconditions:**
* Magento CE, EE 2.3.5-p1, CE, EE 2.4.0-beta1
* Two Simple Products are created:

               -TEST SIMPLE 1, Price = $100; Advanced Pricing: Quantity =2, Price = Discount = 50%;
                -TEST SIMPLE 2, Price = $200; Advanced Pricing: Quantity =2, Price = Discount = 50%;
* A Bundle Product is created:

Dynamic SKU = Yes, Dynamic Price = Yes, Ship Bundle Items = Together, Option Title = OPTION 1, Input Type = Drop-down, Required; use TEST SIMPLE 1 and TEST SIMPLE 2, Default Quantity = 2
* A Category is created
* All created products are assigned to the Category

**Steps to Reproduce:**
* Go to the Storefront as the guest
* Go to the created Category
* Go to the created Bundle Product page

**(/) Expected results:**

The price range of the Product should be: From **$100.00* To *$200.00**

**(x) Actual results:**

The price range of the Product is: From **$200.00* To *$400.00**

**(i)  NOTE1:**  The price of the option is displayed correctly  in the Shopping Cart

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-35725

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35725` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Amit-Hariyani** [comment]
@magento I am working on this
