### ISSUE TITLE
Can't remove seconde added Layout Update

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30286]
**Steps to reproduce:**
1. Go to Content - Widget and "Add Widget"
1. Select any "Type", "Design Package/Theme" and click "Continue"
1. On Widget Storefront Properties click "Add Layout Update"
1. Select some item from "Display on" and "Container" dropdowns
1. Click "Add Layout Update"
1. Click "Remove Layout Update" button on previously added Layout

**(x) Actual result:**  Can't remove Layout Update

(/) **Expected result:**  Layout Update can be removed

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-35716

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35716` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zaximus84** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
Seem this issue duplicated of https://github.com/magento/magento2/issues/29936

**Comment by bhaveshpp** [comment]
## Magento 2.4
I am facing the same issue in my project.
The console is clear there is no error in the console
https://drive.google.com/file/d/1EEhxFnAlPUu_-4srQGkQOP_iVtlLxIm6/view

Did anyone found any solution to this issue?

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#30992 by @zaximus84 in 2.4-develop branch
Related commit(s):
 - [54788a81bbe47a963d68d4de0e2ed3732d5fda51](https://github.com/magento/magento2/commit/54788a81bbe47a963d68d4de0e2ed3732d5fda51)
 - [1921d68f1d57924e089d794ae72e4724107383b0](https://github.com/magento/magento2/commit/1921d68f1d57924e089d794ae72e4724107383b0)
 - [3f81a915a25c122d2617e668a61052b1f4f512ca](https://github.com/magento/magento2/commit/3f81a915a25c122d2617e668a61052b1f4f512ca)
 - [c7ee4fb0c3e1814f00aee3b7a103836b08ea889e](https://github.com/magento/magento2/commit/c7ee4fb0c3e1814f00aee3b7a103836b08ea889e)
 - [942656ca2601ae3f1093c8dc08e8de9eba4b1feb](https://github.com/magento/magento2/commit/942656ca2601ae3f1093c8dc08e8de9eba4b1feb)

The fix will be available with the upcoming 2.4.3 release.
