### ISSUE TITLE
Loading spinner is never dismissed if Paypal checkout is canceled to quickly

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30287]
1. Go to Product Detail Page
 2. Click Paypal button then close popup immediately

(x) Popup closed then another popup display with loading non-stop

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-35428

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35428` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
@magento I am working on it

**Comment by engcom-Bravo** [comment]
Hi,

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence we are closing this issue.

Thanks.
