### ISSUE TITLE
Can't search products in admin using special characters

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30298]
Steps to reproduce:
1. Create a simple product with name including a special character (example: 'LumaTech™ T-Shirt')
1. Filter product grid for keyword including special character: 'LumaTech™'

(-) Actual: No results returned
(/) Expected: Product is returned in results

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-29958

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29958` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
@magento I am working on it

**Comment by vikalps4** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29958` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
