### ISSUE TITLE
Fatal error if admin enters wrong values for some customer attribute and uploads file

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30295]
If Admin tries to save customer entering not valid values for some attribute which has Input Validation set up, and uploads file at the same time he gots fatal error.

**Please note:** if you just enter wrong value for some attribute XOR upload file you will not get fatal.

**Steps to Reproduce:**
1. Create new Customer attribute for URL (Stores -> Attributes -> Customer):
# * Input Type = Text Field
# * Values Required = Yes
# * Default Value = www.google.com
# * Input Validation = URL

1. Create new Customer attribute for file:
# * Input Type = File
# * Values Required = Yes

1. Create new customer:
# * URL field - leave default value
# * File attribute - upload some image

1. Fill all other required fields
1. Click Save button

**Actual Result:**
 (-) Fatal Error
 **Note:** if you click back button in browser or open some other page in backend you will see error messages about field which had wrong values

**Expected Result:**
 (/) Error message appears for each field which has wrong value

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-33687

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33687` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Yash-Bhayani** [comment]
@magento I am working on this

**Comment by Yash-Bhayani** [comment]
@magento add to contributors team

**Comment by Yash-Bhayani** [comment]
@magento add to contributors team

**Comment by Yash-Bhayani** [comment]
@magento I am working on this
