### ISSUE TITLE
Importer Error report bug

### ISSUE THREAD

**Issue by Michael-073** [magento/magento2#30291]
### Preconditions (*)

1.Magento 2.4.0

### Steps to reproduce (*)

1. Log into the back end
2. Go to System ->Import
3. Set entity type to "products"
4. Import behavior = "Add/Update"
5. Upload a file that will result in an error
6. Click the "Check Data" button
7. Click the "Download full report" link

### Expected result (*)

1. The expected result should be that the error report is downloaded to the client's machine.

### Actual result (*)

1. The page navigates to the "Import History" page with no file being downloaded.
2. The following error appears in the exception log file: `[2020-09-30 21:32:49] main.CRITICAL: Path "/var/www/production/var/importexport//vCQggh7rTbGGXjfZvACZWz3ce0XATgLC.csv" cannot be used with directory "/var/www/production/pub/media/" {"exception":"[object] (Magento\\Framework\\Exception\\ValidatorException(code: 0): Path \"/var/www/production/var/importexport//vCQggh7rTbGGXjfZvACZWz3ce0XATgLC.csv\" cannot be used with directory \"/var/www/production/pub/media/\" at /var/www/production/vendor/magento/framework/Filesystem/Directory/PathValidator.php:63)"} []`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Michael-073  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
![Peek 2020-10-02 17-16](https://user-images.githubusercontent.com/51681379/94933612-4e1bfe00-04d3-11eb-943c-e93d30ec50ed.gif)

If you'd like to update the issue, please reopen it.

**Comment by Michael-073** [comment]
I found that the error reports were not being generated while investigating the download process.
I resolved the by copying the working code from the repository and updating the file "vendor\magento\module-import-export\Model\Report\Csv.php"

Inside the csv.php file is the method createReport. I replaced the contents of this method with the following code obtained from the current magento repository

```
$outputCsv = $this->outputCsvFactory->create();

$sourceCsv = $this->createSourceCsvModel($originalFileName);
$columnsName = $sourceCsv->getColNames();
$columnsName[] = self::REPORT_ERROR_COLUMN_NAME;
$outputCsv->setHeaderCols($columnsName);

foreach ($sourceCsv as $rowNum => $rowData) {
	$errorMessages = $this->retrieveErrorMessagesByRowNumber($rowNum, $errorAggregator);
	if (!$writeOnlyErrorItems || ($writeOnlyErrorItems && $errorMessages)) {
		$rowData[self::REPORT_ERROR_COLUMN_NAME] = $errorMessages;
		$outputCsv->writeRow($rowData);
	}
}

$directory = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);
$outputFileName = $this->generateOutputFileName($originalFileName);
$directory->writeFile(Import::IMPORT_HISTORY_DIR . $outputFileName, $outputCsv->getContents());

return $outputFileName;
```
