### ISSUE TITLE
Qty desync on product edit when purchased

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30297]
1. create simple product with qty 100
1. save product
1. open product for editing again, change product title for example
1. in another tab open product on storefront 
1. add 10 items to cart
1. checkout cart to complete purchase
1. switch back to backend tab with edited product
1. click save

(-) Actual: product is saved, qty=100
(/) Expected: product is saved, qty=90

This is a generic commerce issue that leads to excessive orders and reduces quality of merchant's services.
Possible solution: submit qty adjustment diff instead of exact amount. Webapi: introduce new field qty_adjust.

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-31011

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31011` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Ronak-Bhatti** [comment]
@magento I am working on it

**Comment by Ronak-Bhatti** [comment]
@magento add to contributors team

**Comment by Ronak-Bhatti** [comment]
@magento add to contributors team

**Comment by Ronak-Bhatti** [comment]
@magento I am working on it

**Comment by Ronak-Bhatti** [comment]
Can you check the following steps

1) Store->Settings->Configuration->Catalog->inventory->Stock Options->set "Decrease Stock When Order is Placed" to YES

2) When you add new product set the Quantity -> Advanced Inventory -> Mange Stock to YES 

3) Cache Management

**Comment by engcom-Delta** [comment]
Hi ,

Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , this is a default magento functionality.
You can refer to @Ronak-Bhatti's comment.
hence, closing the ticket.

Thanks.
