### ISSUE TITLE
Guest can not checkout if customer address has custom attributes of different types

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30290]
**Steps to Reproduce:**
1. Login to Admin
1. Add custom customer address attributes of all possible types (Store -> Attributes -> Customer Address):
-- text field
--  text area
--  multiple line
--  date
--  dropdown (with values)
-- multiple select (with values)
--  yes/no
--  file
--  image
1. Add product to cart
1. Start checkout process as guest
1. Fill all values at shipping information step
1. Pass to next step

**Actual result:**
(-) Some attributes have normal values
(-) Some attributes have some ids instead of values
(-) <object Object> is shown in some cases
![image](https://user-images.githubusercontent.com/3409584/94850047-fce50f00-03eb-11eb-9029-a59037ae9b7c.png)

**Expected Result:**
(/) Values for all attributes are shown correctly

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-33705

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33705` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Krishna-Rajyaguru** [comment]
add to contributors team

**Comment by Krishna-Rajyaguru** [comment]
@magento add to contributors team

**Comment by Krishna-Rajyaguru** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33705` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
