### ISSUE TITLE
[2.3.6] strange vendor directory is added to var directory

### ISSUE THREAD

**Issue by hostep** [magento/magento2#30292]
### Preconditions (*)
1. Have access to Magento 2.3.6

### Steps to reproduce (*)
1. Setup a new Magento 2.3.6 installation using `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.6 ...`
2. Look at the contents of the `var` directory

### Expected result (*)
1. Not finding a `vendor` directory in the `var` directory

### Actual result (*)
1. Finding a `vendor` directory in the `var` directory with the following structure:
```
var/vendor
├── autoload.php
├── bin
│   ├── composer
│   ├── jsonlint
│   └── validate-json
├── composer
│   ├── ClassLoader.php
│   ├── LICENSE
│   ├── autoload_classmap.php
│   ├── autoload_files.php
│   ├── autoload_namespaces.php
│   ├── autoload_psr4.php
│   ├── autoload_real.php
│   ├── autoload_static.php
│   ├── ca-bundle
│   ├── composer
│   ├── installed.json
│   ├── semver
│   ├── spdx-licenses
│   └── xdebug-handler
├── justinrainbow
│   └── json-schema
├── magento
│   └── composer-root-update-plugin
├── psr
│   ├── container
│   └── log
├── seld
│   ├── jsonlint
│   └── phar-utils
└── symfony
    ├── console
    ├── filesystem
    ├── finder
    ├── polyfill-ctype
    ├── polyfill-intl-grapheme
    ├── polyfill-intl-normalizer
    ├── polyfill-mbstring
    ├── polyfill-php73
    ├── polyfill-php80
    ├── process
    ├── service-contracts
    └── string
```

This is very strange and unexpected behavior.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xmav** [comment]
Hi!
This folder created by https://github.com/magento/composer-root-update-plugin which is bundled in 2.3.6

**Comment by hostep** [comment]
Okay, I can see it in the source code of that composer plugin indeed. Very strange, I wasn't expecting this.

So, this becomes yet another Magento package we'll be adding to our lis of packages not to install on our shops.
We are capable of manually changing the composer.json file in between different Magento versions, that has never been a problem for us so we don't need this module (although I can see the benefits for other less-technically skilled users of Magento)
