### ISSUE TITLE
Wrong ip value in send friend_log table

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30296]
**Proconditions:**
* Create a product
* Email to Friend set to "Enabled" in configurations
* Limit Sending By set to "IP address"
* Allow for Guests set to "Yes" (not nessesary but if you don't you have create customer before.)

**Steps To Reproduce:**
* Go to storfront to the product page
* Click on send email to friend icon
* Fill all required fields and click "Send" button
* Check sendfriend_log table

(/) **Expected Result:**
Ip value should be converted to biginteger value

(x) **Actual Result:**
Ip value is not converted properly and it cuted. F.e. If your ip value 127.0.0.1 it will be cutted to 1270.

(!) **Notice:**
It can cause problems with sendFriend IP validation if different customers will have similar IP addresses  

(!) **Issue caused by:**
\Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress method does not work corectly. Because if it cahced the value one time it will always return cached value despite input parameter

(!)**Notice:** 
Bug blocked this test \Magento\SendFriend\Model\SendFriendTest::testisExceedLimitByIp please unskip after bug fixing

Note from comments:
{quote}Once issue with 'Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress' will be fixed please remove ip2long conversion in \Magento\SendFriend\Model\ResourceModel\SendFriend::addSendItem and make sure this case covered with integration tests{quote}

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-31968

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31968` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#30355 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [ccc83b21a25aee282be830891b5708017e992211](https://github.com/magento/magento2/commit/ccc83b21a25aee282be830891b5708017e992211)
 - [bc53649c4aaa7cf51ab32dc7fa1000c79263d4ec](https://github.com/magento/magento2/commit/bc53649c4aaa7cf51ab32dc7fa1000c79263d4ec)

The fix will be available with the upcoming 2.4.2 release.
