### ISSUE TITLE
Configure Product Modal has duplicated quantity field

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30306]
Reproducible steps:
1. Create a bundle product
1. Create a new order from admin
1. Add the bundle product to the order
1. Click "Configure" link of the bundle product in the "Please select products" grid
1. Configure Product modal opens
1. Check the Quantity field

**Expected result:**

Only one "Quantity" field with one text input field in the modal

**Actual result:**

Two "Quantity" fields, one with one text input field enabled, one with one text input field disabled in the modal. *See attachment for example*

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-23459

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23459` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by engcom-Echo** [comment]
This is expected behaviour.
