### ISSUE TITLE
Erro em compra

### ISSUE THREAD

**Issue by 45lailson** [magento/magento2#30309]
### Preconditions (*)

1. Colocou o Produto No carrinho
2. Adicionou as informações da compra e como ia ser o pagamento

### Steps to reproduce (*)

1. Tentou Realizar uma Compra pelo Cartão
2.

### Expected result (*)

1. Compra Realizada com Sucesso.
2.

### Actual result (*)

1. code: 500
message: "Erro interno do servidor. See details in report api/350747660069"
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @45lailson thank you for your report 
Please create issue according [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
