### ISSUE TITLE
"As low as" category page does not display the lowest price for the selected swatch

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30302]
It is either a regression or related bug to MC-19683

**Description:**

"As low as" price on catalog page does not display the lowest price per the selected Color attribute.

**Steps to reproduce:**
1. Create a configurable product with two swatch attributes Color and Size.
1. Create a combination of options with Black Red White and S, M , L attribute values
1. Change price of the product this way:

|name|price|
|test product for min price-Black-S|200|
|test product for min price-Black-L|100|
|test product for min price-Black-M|200|
|test product for min price-White-S|200|
|test product for min price-White-L|200|
|test product for min price-White-M|180|
|test product for min price-Red-S|170|
|test product for min price-Red-L|200|
|test product for min price-Red-M|200|

4. Open Stores->Attributes->Product

5. Open Size attribute:  set Visible on Catalog Page to "Yes" ; set "Use In product Listing" to **No**.

6. Check product on store front

7. Click on color Black

**Actual result:** "As low as" price for Black is 200.

**Expected:** "As low as" price for Black is 100

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-24038

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-24038` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Kanchi1695** [comment]
@magento I am working on it

**Comment by Kanchi1695** [comment]
@magento add to contributors team

**Comment by Kanchi1695** [comment]
@magento add to contributors team

**Comment by Kanchi1695** [comment]
@magento I am working on it

**Comment by Kanchi1695** [comment]
i follow the same step which you mention,but i doesn't face the issue. When I select black color on catalog page As low as price display 100 as your Expected result.

https://drops.meetanshi.com/6g34n4

**Comment by magento-engcom-team** [comment]
The related internal Jira ticket `MC-24038` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
