### ISSUE TITLE
inline translation on checkout does not persist on page reload

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30303]
**Preconditions:**
1. Magento installed
1. Several products and a customer is created
1. Add product to cart on storefront
1. Login to admin area
1. Go to stores > Configuration > Advanced > Developer > Translate Inline
1. Set **Enabled for Storefront* option to *Yes** and save configuration
1. Flush Cache

 

Steps to reproduce:
1. Edit mini*cart as shown on image*01
![image](https://user-images.githubusercontent.com/3409584/94860389-9f58be80-03fb-11eb-809f-4fa2278917e4.png)
1. Flush cache and reload page

 

(/) Expected Result: MiniCart retains translated labels as shown above

(x) Actual Result: MiniCart does not show labels above

!image*01*after.png|width=277,height=364!
![image](https://user-images.githubusercontent.com/3409584/94860415-a8499000-03fb-11eb-95d6-23c6c61f6f03.png)

Translations seem to update unintended sections however

Note the Qty(translated) label below:

!image01_after2.png|width=316,height=528!
![image](https://user-images.githubusercontent.com/3409584/94860449-b0a1cb00-03fb-11eb-8924-f0a4659fb8a8.png)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-23544

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23544` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by irshadcedcoss** [comment]
@magento I am working on this

**Comment by Amit-Hariyani** [comment]
@magento I am working on it

**Comment by Amit-Hariyani** [comment]
@magento add to contributors team

**Comment by engcom-Echo** [comment]
Unfortunately, can't reproduce this issue.
As for 1-2 steps can't reproduce:

![Peek 2020-12-29 15-55](https://user-images.githubusercontent.com/51681435/103289315-91610c80-49ef-11eb-9bd8-91b841203151.gif)

As for "Translations seem to update unintended sections however". "Translate inline"  it translates phrases. For this created .json file where include translate phrases. In your case phrase - "Qty" uses in two blocks and accordingly it will be translated in both.
[Update the Text](https://docs.magento.com/user-guide/system/translate-inline.html#step-3-update-the-text)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23544` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
