### ISSUE TITLE
[CustomerAddressAttribute]Attribute code and option_id are displayed on Shipping address form once it's updated on storefront

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30305]
##### Description of the issue:

Attribute code and option_id are displayed on Shipping address form once customer custom attribute is updated on storefront instead of the option value
#### Pre-Conditions:

CE and EE installed
(!) B2B not to be installed

create a registered customer with same shipping and billing address

Go to Stores > Attributes > Customer Address and add a new attribute
 Choose input type as Dropdown
 Values Required = No
 Show on Storefront = Yes
 Forms to Use in = (select both)
 Select the sort order =60

 Navigate to Manage Options tab and add couple options to the attribute
##### Steps to Reproduce:

Add a product to the cart and checkout as a registered customer
 Edit the existing address and fill in the value for the attribute Click Save
 Now, go to the checkout page ( Verify that the address displays the new attribute value on the shipping address ( if shipping address and billing address are same) )
 Now, uncheck the checkbox next to "My billing and shipping address are the same" on the payment page
 Select "New Address " from the drop down menu
 Fill in a different value for the attribute and hit update.
 Notice that the instead of the option value, both the option*id and attribute*code are being displayed
##### Expected Result:

Address shows the value of the attribute
###### Actual Result:

Address shows the attribute code and option_id instead

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-23461

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23461` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sanjay-wagento** [comment]
@magento I am working on it

**Comment by sanjay-wagento** [comment]
#dmcdindia

**Comment by sanjay-wagento** [comment]
@magento give me 2.4-develop instance

**Comment by sanjay-wagento** [comment]
@magento I am unable to reproduce the issue on Magento commerce 2.4.0

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-23461` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
