### ISSUE TITLE
User with custom permissions can not save Vimeo videos to products

### ISSUE THREAD

**Issue by theGC** [magento/magento2#3031]
After setting up a new user role we found that users assigned it are unable to save Vimeo videos within products unless they are granted:

Resource Access : all

Any custom permissions, even checking everything, prevents the user from being able to save Vimeo videos.

**Comment by xmav** [comment]
Hi @theGC, thanks for reporting this issue. Internal ticket MAGETWO-58228 was created.

Thanks,
Maksym

**Comment by magento-engcom-team** [comment]
@theGC, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
