### ISSUE TITLE
Export data from Grid to XML Excel

### ISSUE THREAD

**Issue by ricaragao** [magento/magento2#30310]
### Preconditions (*)

1. Magento 2.3 or 2.4

### Steps to reproduce (*)

1. Export any data from grids  to XML/Excel format

### Expected result (*)

1. XML exported to be imported in the Excel

### Actual result (*)

1. The XML exported, when we have many records, don't have xml completed. My analysis is that problem is because all XML is being wrote in the same line, then this over the max allowed to one line in the text file.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ x ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @ricaragao thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result** with export 200 customers:
![image](https://user-images.githubusercontent.com/51681379/94927974-a9e28900-04cb-11eb-8df2-323b23e07d09.png)
[export.csv.txt](https://github.com/magento/magento2/files/5318227/export.csv.txt)
[export.xml.txt](https://github.com/magento/magento2/files/5318228/export.xml.txt)
:heavy_check_mark: All 200 customers are present in exported files

If you'd like to update the issue, please reopen it.

**Comment by ricaragao** [comment]
@engcom-Delta , I downloaded your XML and it has more chars than mine. Do you think that are some config in Magento or PHP or OS to export work fine? Because I tested in two Magento's 2.3 here and both truncate the XML.
