### ISSUE TITLE
2.4.0 with price index taken too long compare to 2.3.5

### ISSUE THREAD

**Issue by davidandersson1** [magento/magento2#30315]
Hello,

We have upgraded magento version from 2.3.5 to 2.4.0 + PHP 7.2 to 7.4 + MySQL 5.7 to 8.0 + nginx server.

We have around 400k products on the shop and after switched latest version 2.4.0 product price index time increase from around 5 mins to 35 mins which is really a huge different in terms of time.

We are using Smile elastic suite modules but we disabled it completely then after check the indexer time but still its taken same time.

So curious to know how index time is increased with latest version 2.4.0.

Thanks,
David Andersson

**Comment by davidandersson1** [comment]
Hello,

Now I can confirm here, with all same setting as per my above question but just switched back to MySQL 5.7 and performed catalog_product_price reindex and it finished within 5-6 mins only with 2 store views.

So here real issue is MySQL latest version 8.0

Means Magento 2.4.0 + PHP 7.4 + MySQL 5.7 + nginx server performance is much better than MySQL 8.0

So if we keep MySQL latest version 8.0 then "catalog_product_price" reindex time is really bad and another end magento suggested us to use MySQL 8.0 with magento 2.4 version, so really confused we must to use MySQL 8.0 even with bad index performance or good to use 5.7 with good index performance.

Anybody please help and provide your view for the same.

Thanks in advance,
David

**Comment by davidandersson1** [comment]
I can confirm that above issue (price index taking too long with MySQL 8.x) even with magento 2.4.1

If anybody faced same issue with large catalog + 2.4 + MySQL 8.0 and found any solution then please share here.

**Comment by davidandersson1** [comment]
Do some investigation and found that due to bundle products catalog_product_price reindex time has been increased. we have around 600 bundle products. 
catalog_product_price reindex time with bundle products = 38-40 mins
without bundle only 2-3 mins

**Comment by davidandersson1** [comment]
Hello,

Is there any update for us? really waiting from long time to resolve the issue!

Anybody please help!

**Comment by Flyingmana** [comment]
@davidandersson1 probably not much of help, but have you checked in MySql Performance Schemas if there appears any notable difference between using this two mysql versions?

The first bigger difference which comes to mind, is the Query Cache, which is removed in MySql 8, which is easy to validate, by disabling it in 5.7 and checking, if the performance now matches what you see in MySql 8.

**Comment by northdakota** [comment]
I have the same problem on 2.4.2-p2.
Full price reindex is fast, but partial reindex is very slow. 

Found such query in slow log 
```
SELECT
    `le`.`entity_id`,
    `i`.`customer_group_id`,
    `i`.`website_id`,
    MIN(final_price),
    MAX(final_price),
    MIN(tier_price)
FROM
    `catalog_product_index_price` AS `i`
        INNER JOIN `catalog_product_super_link` AS `l` ON l.product_id = i.entity_id
        INNER JOIN `catalog_product_entity` AS `le` ON le.entity_id = l.parent_id
        INNER JOIN `cataloginventory_stock_item` AS `si` ON si.product_id = l.product_id
        INNER JOIN `inventory_stock_1` AS `stock_parent` ON stock_parent.sku = le.sku
        LEFT JOIN `cataloginventory_stock_item` AS `si_parent` ON si_parent.product_id = l.parent_id
WHERE
    (si.is_in_stock = 1) OR (IFNULL(si_parent.is_in_stock, stock_parent.is_salable) = 0)
    AND (le.entity_id IN (235108,235111,294166,294172,226831,271278,226834,226837))
GROUP BY
    `le`.`entity_id`,
    `customer_group_id`,
    `website_id`
```
These 8 products are configurable. Each of them contains 2 simple products. 
However result of the query is around 15000 records

looks like there are brackets missed in the where condition  

WHERE
    **(**(si.is_in_stock = 1) OR (IFNULL(si_parent.is_in_stock, stock_parent.is_salable) = 0)**)**
    AND (le.entity_id IN (235108,235111,294166,294172,226831,271278,226834,226837))

**Comment by hostep** [comment]
@vzabaznov: you might be interested in the comment above

**Comment by sunilit42** [comment]
I found same issue

price reindex with mysql 8 taking huge time and some time temp issue

and then i switch to mysql 5.7 reindex time only 30 mins wow!!! 

so something issue with mysql 8 , i already applied patch of temp create table

**Comment by sunilit42** [comment]
@hostep @davidandersson1 do you have solution with mysql 8?

**Comment by davidandersson1** [comment]
@sunilit42 nope, i haven't found any specific reason behind it, but in my case, huge time due to dynamic bundle products, so if your catalog including bundle then I would suggest that temporary disabled all bundle products and perform price reindex with mysql 8.x.x so you will get more idea.

**Comment by sunilit42** [comment]
@davidandersson1 
https://github.com/magento/magento2/issues/31219#issuecomment-1087471280
