### ISSUE TITLE
Trying to access array offset on value of type null in /data/www/vendor/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 40

### ISSUE THREAD

**Issue by haxor211** [magento/magento2#30319]
When using bulk product edit this error happens.

Magento 2.4.0
php as required in docs

`Trying to access array offset on value of type null in /data/www/pneumatig/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 40`

**Comment by shubham-cedcoss** [comment]
@magento I am working on it

**Comment by shubham-cedcoss** [comment]
@magento add to contributors team

**Comment by shubham-cedcoss** [comment]
@magento I am working on it
