### ISSUE TITLE
Search autocomplete does not show product

### ISSUE THREAD

**Issue by hongtran90** [magento/magento2#30323]
Hi Guys,

i installed magento v2.3.3, and enabled elastic search 6+. but Search autocomplete does not show product.
i checked vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
$this->searchResult->getItems() is null.

can you please check it?
Cheers!

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @hongtran90 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Autocomplete in quick search field works
![image](https://user-images.githubusercontent.com/51681379/103409345-0c046600-4b6f-11eb-8022-2a09e31a713b.png)


If you'd like to update the issue, please reopen it.
