### ISSUE TITLE
Login As Customer Log - Logged In must be DateRange Filter instead of Text filter, Date display wrong timezone

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#30328]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Customer -> Login as customer log

### Expected result (*)

1.

..
![image](https://user-images.githubusercontent.com/8234209/94980456-1d2fdd80-0554-11eb-848e-85e416e66b97.png)

2. Time zone converted
![image](https://user-images.githubusercontent.com/8234209/94980517-c7a80080-0554-11eb-964f-875cd8eaeb8d.png)

### Actual result (*)

1. Date Range

![image](https://user-images.githubusercontent.com/8234209/94980467-3df83300-0554-11eb-8938-154b5c695c38.png)

2. ALways GMT TIme in data

![image](https://user-images.githubusercontent.com/8234209/94980607-67658e80-0555-11eb-91e4-828e6912fe70.png)

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38192` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
