### ISSUE TITLE
Backend less-parser fails on files containing only mixins

### ISSUE THREAD

**Issue by homecoded** [magento/magento2#3032]
In lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php:88

```
if (trim($content) === '') {
    $errorMessage = PHP_EOL . self::ERROR_MESSAGE_PREFIX . PHP_EOL . $path;
    $this->logger->critical($errorMessage);

    throw new ContentProcessorException(new Phrase($errorMessage));
}
```

... the less processor checks if a file was compiled successfully by checking if the content is not an empty string.
If you include the less version of Twitter-Bootstrap into a theme or extenion the build process fails because of that. 

_explanation:_

Magento tries to build all of the file separately. When it comes across a mixin file the result will be empty because all mixins are resolved to an empty string by the less parser. See vendor/oyejorge/less.php/lib/Less/Visitor/toCSS.php:31

```
public function visitMixinDefinition($mixinNode){
    // mixin definitions do not get eval'd - this means they keep state
    // so we have to clear that state here so it isn't used if toCSS is called twice
    $mixinNode->frames = array();
    return array();
}
```

_workaround:_

A temporary workaround is to add a bogus CSS definition into mixin files like:

```
#bogus { display: none }    
```

_possible solution:_

Empty results of less-files should not be treated as an error. A warning would surely suffice. I can propose a PR if this is a valid solution.

**Comment by MomotenkoNatalia** [comment]
@homecoded Thanks for reporting this issue. We will do fixes under MAGETWO-55546

**Comment by homecoded** [comment]
@MomotenkoNatalia Awesome. Thanks.

**Comment by magento-engcom-team** [comment]
@homecoded, thank you for your report.
We've created internal ticket(s) MAGETWO-55546 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@homecoded , thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
