### ISSUE TITLE
[PAP] Product filter with "category_id: {in: [...]}" does not work as expected

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30349]
Steps to reproduce:
- Create 2 categories with 1 product each
- run query to fetch products in those categories
```
{
  products(filter: {category_id: {in: <"<cat1>", "<cat2>">}}) {
    items {
      sku
      name
    }
    total_count
  }
}
```

Expected:
total_count should be 2, and items should contain 2 products

Actual:
total_count is 2, but items only contains 1 products

Some investigation:
Changes to \Magento\CatalogGraphQl\Model\Resolver\Products\SearchCriteria\CollectionProcessor\FilterProcessor\CategoryFilter::apply() cause the product collection to be filtered by only the last category id in the array used for "in".
see $collection->addCategoryFilter($category); on line 64

Tests failed to catch this because they check total_count but not actual count of items
need to fix test: \Magento\GraphQl\Catalog\ProductSearchTest::testFilteringForProductsFromMultipleCategories()

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-35355

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35355` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Issue was closed by mistake

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35355` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
