### ISSUE TITLE
Magento 2.3.2 don't want connect to Magento Marketplace. (or vice versa)

### ISSUE THREAD

**Issue by LDmnfx** [magento/magento2#30344]
### Preconditions (*)

1. version 2.3.2

### Steps to reproduce (*)

1. Make an account on https://marketplace.magento.com
2. Log in and buy any extension you want to use
3. Go to my profile > access keys > create a new access key 
4. Log in to Magento backend 
5. Go to system > web setup wizard > extension manager > submit
6. Copy paste the access keys created in step 3 and submit
7. always stays "0 extensions ready to install"

### Expected result (*)

1. Expectation is that there are extensions ready to install. That it doesn't stay on 0
2. 

### Actual result (*)

1.  https://we.tl/t-mcsIjb5RFS (= screenshots)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

Affects critical functionality as we can not provide our webshop from a payment system or shipment system. So we cannot go live with our site until this is solved..

**Comment by engcom-Delta** [comment]
Hi @LDmnfx thank you for your report. According [documentation](https://docs.magento.com/user-guide/system/tools.html):

> Starting with Magento 2.4.0, the Web Setup Wizard is removed, and you must use the command line to install or upgrade Magento, as well as modules and extensions.

Closed as **non-issue**
