### ISSUE TITLE
New customers not shown

### ISSUE THREAD

**Issue by ivandelaros** [magento/magento2#3034]
Hi everyone,
im in the testing mode on localhost and i dont see the new registered customers, both if are entered manually in backend and with the frontend procedure, and with rest api request.

In reality are created but are not shown in the customer grid.
In fact if i follow the link:
localhost/magento2/admin/customer/index/edit/id/{NEW_CUSTOMER_ID}/key/...
i can manage the new customer info and save.

Before this issue i have correctly created two or more customer

Is it a bug or some setting I'm missing?!

Thank you.

**Comment by slavvka** [comment]
Hi @ivandelaros. If a customer isn't in the customer grid but is accessible in the form, customer_grid_indexer is probably outdated. You can reindex it manually using bin/magento indexer:reindex customer_grid. In order to do this operation automatically you need to set up cron

**Comment by ivandelaros** [comment]
Thank you very much @slavvka 

I had not yet understood this process in magento2. thankss

**Comment by rbncha** [comment]
@slavvka, for me manual reindexing isn't solving the issue. in the backend, the customers were imported from version 1.9.1.0 using data migration tool from magento. Customers are in eav format (customer_entity) and not in customer_grid_flat.

**Comment by franckgarnier21** [comment]
The customer grid update by schedule is broken in Magento 2.1.12 and maybe other versions.
You need to set the reindex mode on Save for customer grid.
