### ISSUE TITLE
When creating product configuration, if adding new attribute fails, no error is shown

### ISSUE THREAD

**Issue by jas8522** [magento/magento2#30354]
### Preconditions (*)

Magento 2.4.0. There must be some problem with product attributes such that adding new ones fails. In my case there were duplicate attributes.

### Steps to reproduce (*)
1. Create a product attribute set called "size"
2. Add any number of attributes to this set and ensure that there is at least one duplicate (probably due to migration)
3. Ensure the attribute shows up when creating a new product and create a new product
4. Add configurations to this product that use the size attribute, but rather than selecting existing sizes, add a new one (my example had two sizes, but just one should exhibit the same issue)
5. Configure the rest of your product configuration however you like (defaults will work)
6. Magento will create the new products, but the size attribute will not be set. This is because it never created the sizes, but also never warned you that the sizes couldn't be created because of the duplicates.

If you then go to Stores > Attributes > Product > "size" (edit) > Save Attribute, an error about the duplicates will appear. I could then remove the duplicates (since I now know what the issue is) and save new attributes without any problems.

This report isn't about the duplicate attributes (that was likely an issue from migration that has nothing specifically to do with this report), rather it's about the lack of appropriate error when attributes cannot be created.

### Expected result (*)

When I'm creating a new product configuration that's tied to a *newly entered* attribute, if the attribute cannot be created, I expect to be provided with a similar error that I get when adding a new attribute under Stores > Attributes > Product. That error is:

```
The value of Admin must be unique. (_CSV of duplicate values here_)
```

It might be nice if it was prepended with something like "Error creating attribute: ". It would also be nice if it would provide a link to edit the attribute set so I can fix it right away.

### Actual result (*)
Instead of providing an error about the attribute set having duplicates, it returns me to the master product editing screen and my configurations do not appear. It's like I did nothing.

If you search for the product title in the catalog, you'll find that it did actually create the configuration products, but since they don't have the size attribute specified, they do not appear as configurations of the master product.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wagento-rajan** [comment]
@magento give me 2.4-develop instance

**Comment by wagento-rajan** [comment]
#dmcdindia2020

**Comment by wagento-rajan** [comment]
The issue is not reproducible in the latest version.

**Comment by jas8522** [comment]
Hi @wagento-rajan,

Can you be more specific? What error did you receive when attempting to add the new attributes while creating an configurable product?

**Comment by wagento-rajan** [comment]
Hi @jas8522 

I didn't face any issue based on the client's comment.
