### ISSUE TITLE
Is there a way to extend "Magento_Sales/order/create/scripts" (adminhtml) using mixins?

### ISSUE THREAD

**Issue by freakpol** [magento/magento2#30353]
I-ve tried the usual way of using mixins for that particular file with no success.
Is there any reason that file can not "mixin"ed???

I-m using Magento 2.3.5

**Comment by krishprakash** [comment]
Hi @freakpol. 
GitHub issue tacker is intended for Magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [Magento stack exchange](https://magento.stackexchange.com/) for discuss about this topic
Thanks!!
