### ISSUE TITLE
Selecting "Product -- Full width" in select "Layout" in Section "Design" causes informations to get shown below each other

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30364]
### Preconditions (*)

1. Enterprise 2.4.0
1. Theme: Magento Luma

### Steps to reproduce (*)

1. Open a product in the frontend.
The information container should look like this:

![image](https://user-images.githubusercontent.com/16349349/95348313-33280000-08be-11eb-903c-775f267f5926.png)

2. Open the product in backend and edit it.
3. Go to section "Design".
4. Choose "Product -- full width" in Layout select.

![image](https://user-images.githubusercontent.com/16349349/95348295-2e634c00-08be-11eb-811a-28311e9ba160.png)

5. Save
6. Clear Magento Cache
7. Load Product Site in Frontend.

It looks like this:

![image](https://user-images.githubusercontent.com/16349349/95348449-58b50980-08be-11eb-888c-3b593cfa7120.png)

Is this intended or is it a bug?

### Expected result (*)

See above

### Actual result (*)

See above

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
I tested it on the Instance above, but the field "Product -- Full Width" is not in the dropdown.

**Comment by mrtuvn** [comment]
yes it's correct

> I tested it on the Instance above, but the field "Product -- Full Width" is not in the dropdown.
> I am using Enterprise 2.4, maybe it does not exist in open source?

yes its correct

**Comment by ajijshekh123** [comment]
Right @Eddcapone, This functionality may be available in the Enterprise version.
You can discuss this issue with the Magento Support team.

Thanks
