### ISSUE TITLE
Redirect to the store view when trying to save attribute on product creation page

### ISSUE THREAD

**Issue by Viktorja1** [magento/magento2#30362]
### Preconditions (*)

Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Catalog -> Products -> Add New Product
2. Click on the "Add Attribute" button (Upper right corner)
3. Click on the "Create New Attribute" button
4. Close the opened window
5. Click on the "Create New Attribute" button again
6. Close the opened window
7. Click on the "Create New Attribute" button again
8. Enter "Attribute Label", set type to drop-down and add two values -> Save

### Expected result (*)

No redirect. Attribute is saved.

### Actual result (*)

Redirect to the Home Page if trying to save a attribute on product creation page. Attribute isn`t saved
![Peek 2020-10-07 15-50](https://user-images.githubusercontent.com/30689417/95333312-48e4f780-08b5-11eb-884d-a2100962d1e7.gif)

**Additional information**
May be related to [30361](https://github.com/magento/magento2/issues/30361)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Viktorja1** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
#dmcdindia2020

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38331` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@magento I am working on this

**Comment by Viktorja1** [comment]
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment]
Hi @Viktorja1. Thank you for your report. 
The issue has been fixed in magento/magento2#30400 by @shikhamis11 in 2.4-develop branch
Related commit(s):
 - [6ffb8b1b5ec4919f40684b575120bca4e9707152](https://github.com/magento/magento2/commit/6ffb8b1b5ec4919f40684b575120bca4e9707152)
 - [87d870cc9a54641a1d830d1b85a8edc7aadcd3de](https://github.com/magento/magento2/commit/87d870cc9a54641a1d830d1b85a8edc7aadcd3de)
 - [3b0b7ca0bfc78359367c1fe1f2ad62a4945defd5](https://github.com/magento/magento2/commit/3b0b7ca0bfc78359367c1fe1f2ad62a4945defd5)

The fix will be available with the upcoming 2.4.2 release.

**Comment by shikhamis11** [comment]
@magento give me 2.4.2-beta3 instance

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance
