### ISSUE TITLE
Non-unique id warning during checkout

### ISSUE THREAD

**Issue by gototags-duncan** [magento/magento2#30369]
### Preconditions (*)

1. Magento version 2.3.5-p2
2. Chrome version 85.0.4183.121 (Official Build) (64-bit)

### Steps to reproduce (*)

1. Add items to cart
2. Go to checkout view
3. Look in inspector
4. Notice they're are multiple `non-unique id` warnings 

**Note: this may not happen on the first try but consistently happens when you revisit the checkout.**
**Note: The warnings look to be from multiple auth forms being loaded somewhere off screen or possible hidden.**

### Expected result (*)

1. The console should be free of these warnings
2. ![Capture](https://user-images.githubusercontent.com/72526123/95388265-da993880-08a6-11eb-98ce-fef3dd8ade7b.PNG)

### Actual result (*)

1. The console has several `non-unique id` warnings
2. ![Capture](https://user-images.githubusercontent.com/72526123/95388187-ade52100-08a6-11eb-9e28-24303f91d192.PNG)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @gototags-duncan,
I tried multiple times to navigate the checkout page with the guest user and logged user.  I have faced a single time issue.
See attached the screenshot: 
![image](https://user-images.githubusercontent.com/24711761/95476626-0c90c480-09a5-11eb-8928-205f33898e1c.png)

@gototags-duncan Can you please update which types of scenarios you have followed?

Thanks.

**Comment by gototags-duncan** [comment]
Hello @ajijshekh123 , thank you for your prompt attention to this issue.

Looks like you requested version `2.4-develop`, we are actually running on `2.3.5-p2`, I wonder if this is why the console is different in your case. 

Here are screen shots of the steps taken to reproduce the warnings:

1) add an item to the cart:
  - <img width="1442" alt="Capture" src="https://user-images.githubusercontent.com/72526123/95484978-fb649b00-0945-11eb-86f5-ced8da22dc4c.PNG">

2) checkout:
  - <img width="1443" alt="Capture" src="https://user-images.githubusercontent.com/72526123/95485093-1a632d00-0946-11eb-8b55-c3a5b8d02a5b.PNG">

3) on checkout page notice warning in the console:
  - <img width="1922" alt="Capture" src="https://user-images.githubusercontent.com/72526123/95485220-49799e80-0946-11eb-8de3-91e876b5aa47.PNG">

Thank you,

Duncan

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 instance

**Comment by ajijshekh123** [comment]
Hi @gototags-duncan,
Thanks for the Update. This issue is fixed in the latest Magento 2.4 Instance that's why this issue is not happening in the latest Magento.  I recommended to you please upgrade your Magento Version and Review the issue. If you have a face again this issue in the latest Magento Instance You can update me I will verify and confirmed the issue.
Right now, Magento doesn't provide me with a 2.3.5-p2  Magento instance that's why I can't able to test it.

I will waiting for your next reply to the next update.

Thanks
Ajij Shekh

**Comment by gototags-duncan** [comment]
Hello @ajijshekh123,

Sound like this is fixed in the latest version. We are using the Amasty plugin, I'm wondering if they are both rendering the same form, or at least 2 forms with the same ids.

Thank you,
Duncan

**Comment by ajijshekh123** [comment]
Hi @gototags-duncan,
Thank you for the update. Let me close the issue.
