### ISSUE TITLE
Order item column is blank in customer information

### ISSUE THREAD

**Issue by NTK-2016** [magento/magento2#30371]
Hi ,
I'm to see the item ordered by customer under sales-->order i.e customer information section ,even migrated order is not display items in this column  and neither get shipping and billing information,items ,date time in email content
Please help Thanks 
![image](https://user-images.githubusercontent.com/24722367/95436173-29aba000-0971-11eb-801e-83647eeed70c.png)

**Comment by krishprakash** [comment]
@NTK-2016 Something issue with migration process.GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or  [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this topic

**Comment by NTK-2016** [comment]
hi @krishprakash ,
 It is an issue because I have configured the migrated database with another magento 2.3.4, then, I have got all the data , when back original domain it is not working even I vendor directory

**Comment by NTK-2016** [comment]
HI @krishprakash  , it's not issue with migration . It;s  third party extension which we are using i.e YourPay payment gateway
