### ISSUE TITLE
Error composer install

### ISSUE THREAD

**Issue by edsonjuniorwbj** [magento/magento2#30379]
### Preconditions (*)
Magento version 2.3.5-p1

### Environment (*)
Ubuntu 20
Docker
PHP 7.3

### Steps to reproduce (*)
1. git clone <repository>
2. composer install

### Actual result (*)
`- Installing magento/module-customer-balance (100.3.5): Downloading (connectinDownloading (failed)       
                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://repo.magento.com/archives/magento/module-customer-balance/mage  
  nto-module-customer-balance-100.3.5.0.zip" file could not be downloaded (HT  
  TP/1.1 404 Not Found)  `

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by edsonjunior2021** [comment]
Sorted out. I put the wrong keys in auth.
