### ISSUE TITLE
Add tracking numbers in the shipment mail template

### ISSUE THREAD

**Issue by frenci8** [magento/magento2#30373]
Hi,

I would like to send an email to the buyer/user when a new shipment has been created for the order and I would like the order to contain all the possible tracking numbers (sometimes more than 1 per order) for that specific order. 

I know how to create an email template and select it for the shipment in stores -> configuration -> sales -> sales emails, but my problem is when I am creating the template, there is no variable for tracking numbers in the mail template page. How can I add the tracking numbers?

Thank you

**Comment by engcom-Delta** [comment]
Hi @frenci8 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
