### ISSUE TITLE
Checkout Session Locks Blocking Requests

### ISSUE THREAD

**Issue by SamJUK** [magento/magento2#30383]
On a few checkout actions (most noticeable on shipping -> billing step change) session locking ends up blocking quite a few requests extending their load time as they need to wait for the other requests to end & release the locks. These requests are just wasting FPM connections while they wait for the session lock, reducing the number of actual requests the server can handle. I've been seeing the session_start call take anywhere from 500ms to 1500ms to load, and this adds up quite quickly during sales events where you have a few users on the checkout.

### Preconditions (*)
1. Magento 2.3.5-p2
2. Redis Session Storage (Same issue with files too)
3. Profiler able to monitor AJAX requests (https://github.com/mirasvit/module-profiler)

### Steps to reproduce (*)
1. Add an item to the cart and head to the shipping step of the checkout.
2. Open Dev tools & clear the network tab
3. Continue to billing step. 
4. Review the profiling results of the AJAX Requests & Devtools network tab

### Expected result (*)
1. All Ajax requests to load quickly and not be blocked by any other request

### Actual result (*)
1. Estimate shipping methods request locks the user's session
2. Shipping information request has to wait for the session lock to complete
3. Same for the totals information having to wait for the shipping information request.
<img width="988" alt="Screenshot 2020-10-09 at 10 03 18" src="https://user-images.githubusercontent.com/7872420/95565099-9aa59300-0a17-11eb-87ab-34b418004d61.png">
<img width="1680" alt="Screenshot 2020-10-09 at 10 05 00" src="https://user-images.githubusercontent.com/7872420/95565184-b741cb00-0a17-11eb-89c7-2fba7a0d4762.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hirensolanki38** [comment]
@magento add me to repo.
