### ISSUE TITLE
Error stopping credit memo email sending

### ISSUE THREAD

**Issue by chrisbadley** [magento/magento2#30380]
### Preconditions (*)
Magento Version 2.3.5 p-2
NGINX 1.16.1
PHP 7.3.20 

### Steps to reproduce (*)

1. Create a credit memo against any existing order
2. Observe cron logs

### Expected result (*)

1. Customer receives an email notification when a credit memo has been generated against their order

### Actual result (*)
1. No Credit memos email notifications are sent to customer.
2. Following error can be found in cron logs: Error(code: 0): Call to a member function formatPrice() on null at /var/www/vhosts/XXX/htdocs/var/view_preprocessed/pub/static/vendor/magento/module-weee/view/frontend/templates/email/items/price/row.phtml:1)"} []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @chrisbadley thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
Could you provide additional details about emails configuration in magento?

**Comment by ananth-iyer** [comment]
@magento give me 2.4-develop instance

**Comment by ananth-iyer** [comment]
@magento give me 2.3-develop instance

**Comment by ananth-iyer** [comment]
@chrisbadley Can you let me know the product type? that credit memo having this issue.

**Comment by chrisbadley** [comment]
> @chrisbadley Can you let me know the product type? that credit memo having this issue.

The product type would be Configurable.

**Comment by engcom-Delta** [comment]
@chrisbadley I tried to reproduce issue with Asynchronous sending=Enable/Disable and issue is not reproducible on 2.4-develop
**Manual testing scenario:**
**_Case 1:_**
- Set Stores->Configuratio->Sales->Sales Emails->General Settings->Asynchronous sending=Disable
- Create configurable product 
- Place order with configurable product
- Create invoice and credit memo for this order
- Go to Sales->Credit Memos
- Open created creditmemo
- Click Send Email

**Result:**
:heavy_check_mark: Customer receive email with credit memo information
![image](https://user-images.githubusercontent.com/51681379/102321211-02330e00-3f86-11eb-86a2-02566181da22.png)


**_Case 2:_**
- Set Stores->Configuratio->Sales->Sales Emails->General Settings->Asynchronous sending=Enable
- Create configurable product 
- Place order with configurable product
- Create invoice and credit memo for this order
- Go to Sales->Credit Memos
- Open created creditmemo
- Click Send Email
- Run `cron:run` twice

**Result:**
:heavy_check_mark: Customer receive email with credit memo information
![image](https://user-images.githubusercontent.com/51681379/102321405-4b835d80-3f86-11eb-8ec1-94ff5f061ddc.png)

If you'd like to update the issue, please reopen it.
