### ISSUE TITLE
Design Issue on Checkout page 

### ISSUE THREAD

**Issue by aryancedcoss** [magento/magento2#30399]
### Description (*)
Design Issue on Checkout page 
### Preconditions (*)
1. php version : 7.3.23
2. Magento version: 2.4
3. Viewport : Desktop

### Steps to reproduce (*)
1. Add product to cart 
2. Proceed to Checkout

### Expected result (*)

1. If user is not logged in
![checkout_alignment_resolved](https://user-images.githubusercontent.com/53182467/95648836-da43ac00-0af7-11eb-9bc4-617be7480303.png)

2.  If user is logged in
![checkout2_resolved](https://user-images.githubusercontent.com/53182467/95648841-e6c80480-0af7-11eb-93b2-2365013fc956.png)

### Actual result (*)

1. 
![checkout_alignment](https://user-images.githubusercontent.com/53182467/95648745-4a9dfd80-0af7-11eb-8656-3eac200f413c.png)

2.
![checkout2](https://user-images.githubusercontent.com/53182467/95648776-7faa5000-0af7-11eb-8ef9-b0308a6acf4c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
#dmcdindia2020

**Comment by ajijshekh123** [comment]
@aryancedcoss - Please attach the screenshot for the actual result and expected result

**Comment by aryancedcoss** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
@aryancedcoss thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ajijshekh123** [comment]
Thanks @aryancedcoss

**Comment by aryancedcoss** [comment]
> @aryancedcoss - Please attach the screenshot for the actual result and expected result

Yes Sir, I have updated Screenshot with issue.
Please check

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment]
@magento give me test instance

**Comment by gabrieldagama** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @aryancedcoss,
You are already logged other issues related to this issue.
Let me closed the issue.
Related Issue: https://github.com/magento/magento2/issues/30425

Thanks.
