### ISSUE TITLE
Design issue in category page , in Shopping Options dropdown, the count value alignment is not right.

### ISSUE THREAD

**Issue by saumya1998** [magento/magento2#30397]
*Design issue in category page , in Shopping Options dropdown, the count value alignment is not right.*

### Preconditions (*)
1. PHP 7.4.11
2. magento2-2.4

### Steps to reproduce (*)
1) Open magento base url.
2) Go to category page.
3) Go to Shopping Options on left side of page.
4) Open any CATEGORY/PRICE dropdown.
5) Check count design.

### Expected result (*)
https://user-images.githubusercontent.com/50991251/95648439-c8acd500-0af4-11eb-9517-0108d76889f6.png

### Actual result (*)
https://user-images.githubusercontent.com/50991251/95648477-1d505000-0af5-11eb-956c-154f3bf1c189.png

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by saumya1998** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
@saumya1998 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ajijshekh123** [comment]
#dmcdindia2020

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @saumya1998,
The issue found on the latest Magento 2.4 Instance.
**PFA:**

![image](https://user-images.githubusercontent.com/24711761/95707302-c83c4780-0c76-11eb-85c2-597444f02c5a.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38341` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
