### ISSUE TITLE
New Shippment for Guest User : No such entity with customerId = 

### ISSUE THREAD

**Issue by reshadzazai** [magento/magento2#30395]
### Summary
While creating New Shippment for an order which is placed by Guest User (Customer Group: NOT LOGGED IN), I get the error `No such entity with customerId =` 
I had the same issue in Magento 2.2.6 so I have upgraded it to Magento ver. 2.3.5-p2 but I still get the error.

### Preconditions (*)
1. Magento ver. 2.3.5-p2
2. PHP 7.2.33

### Steps to reproduce (*)
1. Placed order as Guest User and tired to create a New Shipment for the order.

### Expected result (*)

1. The Shipment had to be created

### Actual result (*)

1. The Shipment is not created and I get the error: `No such entity with customerId =`
![Screenshot_1](https://user-images.githubusercontent.com/20941245/95647317-bb3b1f00-0ae3-11eb-8776-a47b351b7819.jpg)

**Comment by PayalrPatel** [comment]
@magento I am working on this

**Comment by jaydolphinweb** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
@jaydolphinweb thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Shubham0492** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @reshadzazai  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop. Issue is not reproducible after upgrade from latest 2.3.x release(2.3.6) to latest 2.4.x release (2.4.1) also
**Manual testing scenario:**
- Create simple product
- Place order with this product as guest
- Go to admin panel
- Go to Sales->Orders
- Click View on order
- Click Ship

**Result:**
:heavy_check_mark: No errors on New Shipment page
![image](https://user-images.githubusercontent.com/51681379/102625459-335e3a80-414e-11eb-8e61-77a5e8cce84a.png)
:heavy_check_mark: No errors after shipment creation
![image](https://user-images.githubusercontent.com/51681379/102626305-50dfd400-414f-11eb-97f3-389b30e84b49.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.
