### ISSUE TITLE
extra spacing from bottom in minicart.

### ISSUE THREAD

**Issue by saumya1998** [magento/magento2#30414]
### Preconditions (*)
1. magento2-2.4-develop, magento2.3
2. PHP 7.4.11

### Steps to reproduce (*)
1) open magento base url.
2) open product page
3) add product to your cart.
4) open minicart in header top right corner.
5) check spacing below View and Edit Cart link.

### Expected result (*)
https://user-images.githubusercontent.com/50991251/95651481-5a720d80-0b08-11eb-8519-4b844940d060.png

### Actual result (*)
https://user-images.githubusercontent.com/50991251/95651490-68c02980-0b08-11eb-9521-9e576ae3fb7a.png

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by saumya1998** [comment]
#dmcdindia2020

**Comment by krishprakash** [comment]
Hi @saumya1998. Thank you for your report.
Seems issue is already added and in open status #27987
So closing this as duplicate issue
