### ISSUE TITLE
"State is Required for" multiselect must have at least one option selected and should not

### ISSUE THREAD

**Issue by csmarvz** [magento/magento2#3042]
Stores > Configuration > General > State Options

If you unselect everything and Save Config, the old selections will be there again.

Branch 2.0

**Comment by palamar** [comment]
@csmarvz
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
