### ISSUE TITLE
State/Province field is still required in checkout shipping address after being set optional in the config

### ISSUE THREAD

**Issue by csmarvz** [magento/magento2#3043]
How to reproduce:
1. Go to Stores > Configuration > General > State Options
2. Remove Switzerland from the multiselect
3. Save
4. Add items to the cart and go to the checkout page
5. Fill the fields, select the country Switzerland but don't select a State
6. Proceed and see the message "Please select an option"

**Comment by ishakhsuvarov** [comment]
@csmarvz Thank you for reporting the issue. Which branch are you using for your installation? This seems to be already fixed in the `develop` branch.

**Comment by csmarvz** [comment]
@ishakhsuvarov Ah nice! I'm using the full release, which I think comes from the branch 2.0.
Could you please point me to the code that fixes it so I can use it before the next release? thanks

**Comment by ishakhsuvarov** [comment]
@csmarvz You may try to use this fix: [721496e9219297ef09a518e67290dd729b6c3f01](https://github.com/magento/magento2/commit/721496e9219297ef09a518e67290dd729b6c3f01), however we can not be totally sure that fix will solve the issue completely.
Please check your exact case using latest code from the `develop` branch if it is possible.

**Comment by csmarvz** [comment]
@ishakhsuvarov thanks for the fix.
Applied it to the official full release and worked
