### ISSUE TITLE
Why language Chinese doesn't work at all? Still in English mode.

### ISSUE THREAD

**Issue by Mike20201011** [magento/magento2#30439]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @Mike20201011. 
GitHub issue tacker is intended for Magento core technical issues only
Kindly refer community forum or Magento stack exchange for general discuss about this topic
Thanks
