### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.queue_poison_pill' doesn't exist

### ISSUE THREAD

**Issue by ninjacoder30** [magento/magento2#30438]
**PHP VERSION :  7.3.22
Magento2-2.3.5-p2**

[Progress: 177 / 361]
Module 'Magento_Wishlist':
Running schema recurring...
[Progress: 178 / 361]
[Progress: 179 / 361]
Installing user configuration...

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.queue_poison_pill' doesn't exist, query was: SE
  LECT `queue_poison_pill`.`version` FROM `queue_poison_pill`

In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.queue_poison_pill' doesn't exist

**Comment by ihor-sviziev** [comment]
Hi @ninjacoder30,
I wasn't able to reproduce this issue.
Could you add steps to reproduce of this issue?

Did you installed magento as described here https://devdocs.magento.com/guides/v2.4/install-gde/composer.html#install-magento? If no - please install it at first.
