### ISSUE TITLE
Design Issue of select box (text is cutting from bottom) on Admin

### ISSUE THREAD

**Issue by aryancedcoss** [magento/magento2#30440]
Design Issue of select box (text is cutting from bottom) on Admin

### Preconditions (*)

1. Magento version : Magento 2.4
2. Php version : 7.3.23
3. Viewport : Desktop

### Steps to reproduce (*)

1. Login to Magento Admin
2. Goto Stores > Configuration > Advanced > Admin

### Expected result (*)
1. 
![field_solved](https://user-images.githubusercontent.com/53182467/95674448-f6198180-0bcd-11eb-8e92-f3981eccfc3c.png)

### Actual result (*)

1.
![field](https://user-images.githubusercontent.com/53182467/95674455-03cf0700-0bce-11eb-9ff9-414b917a50d5.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @aryancedcoss. Thank you for your report.
Not able to replicate the issue as per shared the screenshot by you
![image](https://user-images.githubusercontent.com/46617848/95676233-33840c00-0bda-11eb-9d11-7ca9a3a20acc.png)
Feel free to reopen the issue if you confirm that issue reproduce on 2.4-develop instance

**Comment by aryancedcoss** [comment]
Hello Sir,
### I am using:
Operating System: Linux Mint 19.1
Architecture: x86-64
Browser: Firefox
Browser version: 69.0.1 (64-bit)

I have checked Instance as well but still getting issue
