### ISSUE TITLE
What's the good shared hosting provider for Magento 2 (Not Cloud) ? 

### ISSUE THREAD

**Issue by AYElsharif** [magento/magento2#3044]
Hi,

I want new hosting for my next Magento 2 project, What is the Best,Stable,Trusted hosting ?

**Comment by restaurantsupply** [comment]
I would recommend nexcess (https://www.nexcess.net/). They are very easy to work with and know a lot about Magento 2.0. When and if you run into issue they can help solve them.

**Comment by ghost** [comment]
Yeah, +1 for Nexcess. Only been hosting with them for a week (as Site5 have no plans to update their MySQL to the level needed for Magento 2 support) and they've been fantastic! Helpful, knowledgeable and determined when it comes to solving problems too. Credit where it's due, right? :p

**Comment by alankent** [comment]
Sorry, this issue tracking is for reporting code issues, not general discussions. Please use the Magento forums for this sort of discussion. Thank you!
