### ISSUE TITLE
customer grid

### ISSUE THREAD

**Issue by antuz88** [magento/magento2#3045]
Hi,
i have migrated my db from magento 1.8.0 to 2.0.
My orders,product and customers was migrated correctly but in customer grid i receive empty results with message: We couldn't find any records.
If i try to edit a customers from an order i can do it.

EDIT: my table customer_entity is populated but customer_grid_flat is empty. If i add manually in db a record on customer_grid_flat i can display the record on magento backend.

Another issues, when i try to add new customer i receive a blank page and the log is:

PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 79 bytes) in /var/www/magetest/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php on line 486

i have set in .htaccess and php.ini the php_value to 2048M but not solved it.

Someone can help me?

Thanks

**Comment by mazhalai** [comment]
Since this is a migration related question, it should be posted here https://github.com/magento/data-migration-tool-ce
