### ISSUE TITLE
[NOT READY] Customer/customer address EAV in GraphQL

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#30464]
As a Magento Developer,

I would like to improve GraphQL by supporting EAV for customer and customer address

so that

it is easier for merchants to extend customer/customer address objects in admin and have those changes flow to GraphQL schema.

**Acceptance Criteria**

> A merged architecture PR.
> All schema and implementation changes are non-breaking.

**Comment by engcom-Hotel** [comment]
Hello @nrkapoor,

Thanks for posting this issue!

We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know in case you are able to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nrkapoor,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
