### ISSUE TITLE
Gift Message is not showing

### ISSUE THREAD

**Issue by nfishbane** [magento/magento2#3046]
Hi- enabled in backend.
But its not showing in frontend - anyone got this to work?

**Comment by ishakhsuvarov** [comment]
@nfishbane Thank you for reporting this issue. Could you please specify more precise steps you used to reproduce the problem?

**Comment by nfishbane** [comment]
Hi,
I went to backend store->configuration->sales->gift options and set Allow Gift Messages on Order Level to yes, and Allow Gift Messages for Order Items to yes, (saved and cleared the cache) still gift messages are not available during checkout process

**Comment by ishakhsuvarov** [comment]
@nfishbane Gift messages should be available only on the Shopping Cart page, please verify.

**Comment by nfishbane** [comment]
yes I see it on cart - Thanks

Also I'm not sure what was the logic about moving it from checkout as it was in Magento 1, since we have the option to skip the cart page abd go directly to checkout

**Comment by asemenenko** [comment]
By default "Proceed to Checkout" button goes straight to checkout page however the link can be changed to navigate to the shopping cart. The logic behind it is the fact that checkout process should be lightweight keeping additional options selected previously - you may notice similar approach in many popular web-stores where gift options/in-store pickup etc are configured in shopping cart. I think to avoid confusion we should adjust configuration option accordingly.
