### ISSUE TITLE
Magento 2.3.5-p2 cannot run setup:upgrade on empty database with existing env.php

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2#30462]
### Preconditions (*)

vanilla Magento 2.3.5-p2 OpenSource and Commerce Edition

### Steps to reproduce (*)

1. Install Magento 2.3.5-p2 with setup:install
2. delete all tables from the database
3. rerun installation with setup:upgrade

### Expected result (*)

Magento should create all tables and run all setup scripts/patches again.

### Actual result (*)

```
SQLSTATE[42S02]: Base table or view not found: 1146 
Table 'magento.core_config_data' doesn't exist, 

query was: 
SELECT main_table.* FROM core_config_data AS main_table
```

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Additional information

1. Triggered by `\Magento\Setup\Console\Command\UpgradeCommand::execute()`
2. calling `\Magento\Setup\Model\Installer::updateModulesSequence()`
3. calling `\Magento\Setup\Model\Installer::cleanCaches()`
4. iterating over all cache types and for … `$type = full_page` …
5. calling `\Magento\PageCache\Model\Cache\Type::clean()`
6. calling `$this->eventManager->dispatch('adminhtml_cache_refresh_type');`
7. which triggers
8. `\Magento\CacheInvalidate\Observer\FlushAllCacheObserver::execute()`
9. calling `\Magento\Framework\Cache\LockGuardedCacheLoader::lockedLoadData()`
10. because it needs the config value for `default/system/full_page_cache/caching_application`
11. which results in
12. `\Magento\Framework\App\Config\ConfigSourceAggregated::get()` loading a collection from the database table …
13. which does not (yet) exist
14. 💥

**Comment by engcom-Delta** [comment]
Hi @riconeitzel thank you for your report. According [docs](https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=setup%3Aupgrade#setupupgrade) it is not proper way to use of command described in issue.
According docs command should be used in [next cases](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-db-upgr.html#instgde-cli-db-upgr)

If you'd like to update  the issue, please reopen it.
