### ISSUE TITLE
[Atwix]Make the destination_cart_id argument optional in the mergeCarts mutation

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30469]
## Why

**PR** 
https://github.com/magento/magento2/pull/30633 

This came up in a discussion with [@sirugh](https://github.com/sirugh] from the [`pwa-studio`|https://github.com/magento/pwa-studio) team.

When a user logs in (creates a new token), one of the first things the UI needs to do is merge the current guest cart (if items are present) into the customer account's cart.

If `destination*cart*id` is required, this requires 3 round trips:
1. Call for `Mutation.generateCustomerToken`
1. Call for `Query.cart` to get customer cart ID
1. Call for `Mutation.mergeCarts` to merge guest cart ID into customer cart

Because a customer can only have a single cart, and this API only works for authenticated users, `destination*cart*id` is an unnecessary requirement here. If we make it optional, the login <ins> cart upgrade for UI can happen in a single request:
```java
1. Mutations run serially, in-order. So `mergeCarts` will only execute
1. if `generateCustomerToken` succeeds
mutation LoginAndMergeCarts($email: String!, $password: String!, $guestCartID: String!) {
    generateCustomerToken(email: $email, password: $password) {
        token
    }
    mergeCarts(source*cart*id: $guestCartID) {
        ID
    }
} {code}
## Proposed Change

 
{code:java}
type Mutation {
-    mergeCarts(source*cart_id: String!, destination_cart*id: String!): Cart!
</ins>    mergeCarts(source*cart_id: String!, destination_cart*id: String): Cart!
} ```
<ins>**Approved Design**</ins>
 <https://github.com/magento/architecture/blob/mergeCarts-optional-destination/design-documents/graph-ql/coverage/mergeCarts-optional-destination.md>

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37413

**Comment by andrewbess** [comment]
@magento I am working on this
