### ISSUE TITLE
Products positions are not updated in GraphQL query result

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30467]
#### Precondition
Use GET to submit GraphQL query in order for query result to be cached. see [GraphQL Caching](https://devdocs.magento.com/guides/v2.4/graphql/caching.html)

#### Steps to reproduce
1. Create at least 2 products
1. Create category and assign products created in step.1 and save category
1. Execute the query below
1. Check that products are ordered correctly
1. Change products positions in the category and save changes
1. Execute the query below

#### Query
```java
query getProducts { 
  products( 
    filter: {
      category_id: 
        { eq: "<category ID>" } 
    } 
    sort:
    	{position:ASC} 
  ) 
  { 
  total_count 
    items { 
      name 
      sku 
    } 
    page_info { 
      page_size 
      current_page 
    } 
  } 
}
```
#### (x) Actual result

Products positions are not updated.
#### (/) Expected result

Products positions are updated.

#### (i) Notice
This issue is reproducible only if GraphQL query result is cached. the cache is not invalidated when products positions changed within a category. However this works with regular category page (PLP).

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-38078

**Comment by Zifius** [comment]
@magento I am working on this
