### ISSUE TITLE
REST API: catalogCategoryLinkManagement error if same product in multiple subcategories of parent

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#30461]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Create a category with 2 sub categories
![image](https://user-images.githubusercontent.com/51681379/95845356-baf48b00-0d52-11eb-8cc2-ab7585d0ed16.png)
2. Assign same product to both sub categories
![image](https://user-images.githubusercontent.com/51681379/95845435-d52e6900-0d52-11eb-9f6f-8dbf8081a767.png)
3. Call /V1/categories/{categoryId}/products with the parent category id

### Expected result (*)

1. List of all products assigned to parent category

### Actual result (*)

1. "Internal Error. Details are available in Magento log file. Report ID: **webapi-5f8579e37db54**"
![image](https://user-images.githubusercontent.com/51681379/95846092-b11f5780-0d53-11eb-8935-c8d42d034c80.png)

2. main.CRITICAL: Report ID: webapi-5f8579e37db54; Message: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-5f8579e37db54; Message: Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento2dev/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento2dev/lib/internal/Magento/Framework/Data/Collection.php:408)"} []

### Notes

1. It should be noted the same thing happens if you assign a product to a parent category and a sub category of that parent.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38413` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pmcnamaracpc** [comment]
Which pull request was this done in? All these status updates are nice, but don't make it clear which release this is going in or pull request addressed it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38413` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@pmcnamaracpc @nthurston 

The issue was closed by mistake.
at this moment Magento team has fixed it, internal PR is ready(CR and QA passed) but not merged into the main code-base.
As soon as it will be merged related commits can be found using a search based on internal ticket key `MC-38413`
Example: https://github.com/magento/magento2/search?q=MC-38413&type=commits

Sorry for inconvenience

**Comment by pmcnamaracpc** [comment]
Thanks for the clarification

**Comment by zakdma** [comment]
Internal ticket MC-38413 merged into mainline

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-38413` was closed as `Fixed`.
Related commits can be found by search https://github.com/magento/magento2/search?q=MC-38413&type=commits
