### ISSUE TITLE
[Atwix]Fix naming conventions and optional/required fields for company schema

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30466]
As a developer I want GraphQL schema for a company to follow naming conventions and have consistent optional/required fields so the schema is easy to use.

AC
* Fields follow naming convention and have consistent optional/required, see https://github.com/magento/architecture/pull/447

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-38187

**Comment by andrewbess** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, @andrewbess. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-38187` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.2` release.
