### ISSUE TITLE
[PAP] Dynamic Blocks Implementation

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#30463]
As a GraphQL Consumer, 

I would like to get the dynamic blocks defined in Magento admin

so that

I can dynamically build content pages by customer segments.

**Acceptance Criteria**

> Dynamic blocks can be queried specifying one more criterion as defined in the schema.
> Dynamic blocks should also return associated pricing rules if asked by the client application.

**Proposed Schema**
https://github.com/magento/architecture/pull/451

**Comment by sasha19957099** [comment]
@magento I am working on this

**Comment by sasha19957099** [comment]
propesed schema changes 
https://github.com/magento/architecture/pull/472
