### ISSUE TITLE
Add Web-Api functional tests for B2B bugs

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30475]
List of bugs that do not have test coverage: 

https://github.com/magento/partners-magento2b2b/issues/260 need to test that only necessary permissions returned

For the following issues need to test that user doesn't have access to the resources of other companies
https://github.com/magento/partners-magento2b2b/issues/262
https://github.com/magento/partners-magento2b2b/issues/263
https://github.com/magento/partners-magento2b2b/issues/264

The bugs are fixed. But tests that need to accompany the fixes yet to be done.

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37527

**Comment by sasha19957099** [comment]
@magento I am working on this
