### ISSUE TITLE
Page layouts are hard-coded in Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#30471]
### Preconditions (*)

Magento 2.3.5

### Steps to reproduce (*)

Have a look at the code source of `Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container`.

### Expected result (*)

The function `getPageLayouts()` should return the actual list of page layouts declared by the different modules.

### Actual result (*)

The function `getPageLayouts()` only returns the one provided by Magento_Theme, and they are hard-coded in the file:

```php
    /**#@+
     * Frontend page layouts
     */
    const PAGE_LAYOUT_1COLUMN = '1column-center';
    const PAGE_LAYOUT_2COLUMNS_LEFT = '2columns-left';
    const PAGE_LAYOUT_2COLUMNS_RIGHT = '2columns-right';
    const PAGE_LAYOUT_3COLUMNS = '3columns';
    /**#@-*/

   [...]

  /**
     * Retrieve page layouts
     *
     * @return array
     */
    protected function getPageLayouts()
    {
        return [
            self::PAGE_LAYOUT_1COLUMN,
            self::PAGE_LAYOUT_2COLUMNS_LEFT,
            self::PAGE_LAYOUT_2COLUMNS_RIGHT,
            self::PAGE_LAYOUT_3COLUMNS,
        ];
    }
```

### Workaround

I may be possible to override `Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container` and to inject an instance of `Magento\Framework\View\Model\PageLayout\Config\BuilderInterface` to grab the list of available page layouts from there. Untested though.

### Thoughts

Basically, it makes any container with Label declared in a non-Magento Theme page layout not selectable from the back-office to inject widgets. But the simple fact that Magento_Widget assumes that some page layouts exist is concerning. This concern is actually confirmed by the fact that one of the four hard-coded page layouts doesn't even exist: `1column-center`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ericmorand** [comment]
I can now confirm that overriding the class works perfectly:

```php
<?php


namespace [Vendor]\[Theme]\Block\Adminhtml\Widget\Instance\Edit\Chooser;


class Container extends \Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container
{
    /** @var \Magento\Framework\View\Model\PageLayout\Config\BuilderInterface */
    protected $_pageLayoutConfigBuilder;

    public function __construct(
        \Magento\Framework\View\Element\Context $context,
        \Magento\Framework\View\Layout\ProcessorFactory $layoutProcessorFactory,
        \Magento\Theme\Model\ResourceModel\Theme\CollectionFactory $themesFactory,
        \Magento\Framework\View\Model\PageLayout\Config\BuilderInterface $pageLayoutConfigBuilder,
        array $data = []
    ) {
        $this->_pageLayoutConfigBuilder = $pageLayoutConfigBuilder;

        parent::__construct($context, $layoutProcessorFactory, $themesFactory, $data);
    }

    protected function getPageLayouts()
    {
        $pageLayoutsConfig = $this->_pageLayoutConfigBuilder->getPageLayoutsConfig();

        return array_keys($pageLayoutsConfig->getPageLayouts());
    }
}
```

This Container returns the actual list of page layouts instead of the hard-coded and wrong one of the core implementation.

**Comment by mrtuvn** [comment]
This issue still quite important at my pow

**Comment by ihor-sviziev** [comment]
@ericmorand @mrtuvn, could you explain the use cases when these values need to be changed/customized?

**Comment by mrtuvn** [comment]
Should `getPageLayouts` get all layout instead return fixed value array ? Example i create custom page layout somewhere else in theme Should magento update that too ?

**Comment by ihor-sviziev** [comment]
@mrtuvn yeah. Make sense! I think it should be marked with S3 P2.
@sidolov @sivaschenko @gabrieldagama, what do you think?

Hi @ericmorand,
Could you create a pull request with suggested changes from the following comment https://github.com/magento/magento2/issues/30471#issuecomment-707374116 ?

**Comment by sivaschenko** [comment]
Added to [Public Triage Meeting](https://github.com/magento/magento2/wiki/Public-Triage-Meeting) agenda on Thursday.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @gabrieldagama 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40669` were created

**Issue Available**: @gabrieldagama, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ericmorand** [comment]
@ihor-sviziev , thanks a lot for taking care of this. Much appreciated.

To give a little bit of context on this issue and a most of the other issues I've opened related to layouts, widgets and themes, we had to work on a custom design for a customer, based on the job from a creative agency. We didn't want to base our work on an existing Magento 2 theme (too much to _undo_) but still wanted to propose to our client to benefit fully from the themes, widgets, layout and per-product/per-category customization of Magento 2.

We then went to full custom way, providing two themes, custom page layouts and an extensive set of widgets. But equally important, we wanted to provide our customer with a taylor-made back-office where only what was supported by our themes was available to the webmasters. So, we wanted to have only the page layouts supported by our themes visible in the back-office, for example.

We had to cusotmize a lot of things and implement some "separation of concerns" strategy that were not provided by Magento 2 (at least from the documentation) like preventing modules from providing page layouts (letting the themes being fully responsible about that) or having a separate project based on Twig / ES6 / SASS for our frontend developers, writing specification for _every_ templates used by our Blocks, forbiding sending anything else than primitives variables to the templates (no classes, no functions, no helpers), and so on.

The final result was above our expectations in product quality, project quality (the maintainablity of the thing is leagues above everything we did with Magento 2 in the past), budget and delay.

My own personal conclusion about Magento 2 after that experience is that the framework is amazing (it allowed us to implement everything that we wanted easily even though our approach was quite disruptive, which says a lot of the quality of a framework) but that the documentation and the "recommended way of doing things" is quite dated. About that last point, we had to fight a lot against legacy Magento 2 developers and architects that didn't believe in our approach and threw the "not a good practice" argument to our faces. :D

It was worth it:

https://www.girard-perregaux.com/

Plus we now have an extensive understanding of the whole page rendering process of Magento 2, end-to-end. :D

**Comment by mrtuvn** [comment]
Thanks for your sharing such care
in my opinion magento 2 is great framework. Now you can do a lot with current tools. headless approach with magento only as backend and much more. No limited. But magento also keep bigger and bigger. Implements a lot new business logic. But I think adobe should more listen on developers experience instead focus on they business. Avoid break changes to lowest as possible. I still believe current community can keep strong and expand to more
