### ISSUE TITLE
Update company query to include company credit

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30476]
Update the company query to include company credit and credit history.

Related tickets

https://jira.corp.magento.com/browse/MC-37604

<https://github.com/magento/partners-magento2b2b/pull/247]

[https://github.com/magento/partners-magento2b2b/pull/191] 

Devdocs PR: https://jira.corp.magento.com/browse/MC-37625

[https://github.com/magento/devdocs/pull/7984>

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37627

**Comment by mauragcyrus** [comment]
Closing this here to open in devdoc 
@keharper

**Comment by keharper** [comment]
This work is being tracked in https://github.com/magento/devdocs/issues/7989
