### ISSUE TITLE
[Atwix] CMS Hierarchy child pages URL Key response

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30474]
**ISSUE:**

GrapghQL URL Resolver not working for CMS Hierarchy

**STEPS TO REPLICATE:**
* Create new nodes for page hierarchy (ex: Name: Graph Parent, URL: graph-parent)
* Add a CMS page to the node created. You can see "test page" CMS page is assigned to the "Graph Parent" node. 
* This CMS page can be accessed from browser without any issue using this URL "graph-parent/test-page"

!image-2020-07-21-10-43-03-444.png|width=321,height=343!
* Do a GrapghQL request to the url resolver and check the response "https://devdocs.magento.com/guides/v2.4/graphql/queries/url-resolver.html"

```
{
  urlResolver(url: "graph-parent/test-page") {
    id
    relative_url
    redirectCode
    type
  }
}
```
**ACTUAL RESULTS:**
```
{
  "data": {
    "urlResolver": null
  }
}
```
 

**EXPECTED RESULTS:**

Resolved URL data should be returned

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36037

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by andrewbess** [comment]
@magento I'm working on this

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release
