### ISSUE TITLE
[Atwix]Category images are broken with SEO disabled

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30473]
Cloning this ticket as its the same fix but it needs to also enable for when a customer has URL rewrites turned **off** (right now it only works if they have it turned on)

Seems like we introduced a bug change to 2.3.4 when we updated the category image source. It was changed from file name to the actual url but doesn't seem to work as the path returned is not the actual path for existing images. Only new images created after the migration work correctly. 

Test instance - <https://adobe-starter.dummycachetest.com/graphql/> 

Query 
 {
 category(id: 21)

{ id name url*path image product_count children*count }

}

Expected output 
```java
{
  "data": {
    "category": {
      "id": 31,
      "name": "Tops",
      "url_path": "venia-tops",
      "image": "https://adobe-starter.dummycachetest.com/media/catalog/category/outside.jpg",
      "product_count": 0,
      "children_count": "2"
    }
  }
} {code}
Actual output
{code:java}
 { "data": { "category": { "id": 31, "name": "Tops", "url*path": "venia-tops", "image": "https://adobe-starter.dummycachetest.com/media/outside.jpg", "product_count": 0, "children*count": "2" } } } ```

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-38407

**Comment by ProkopovVitaliy** [comment]
@magento I am working on this
