### ISSUE TITLE
Enterprise Edition: Db splits are not included in backups

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3047]
I am using M2 EE and setup the [split database performance solution](http://devdocs.magento.com/guides/v2.0/config-guide/multi-master/multi-master.html). Now I want to create a db backup by running `bin/magento setup:backup --db`.

This command will only update the `default` db conenction. There is no option to choose a connection between default, checkout and sales.

My prefered solution would be to choose a db conncetion which will be backuped, e.g. `bin/magento setup:backup --db sales`.

**Comment by mazhalai** [comment]
@mc388 Please do not post EE related issues on github. Please use partner portal for this request.
