### ISSUE TITLE
Getting error deploying static content in production mode

### ISSUE THREAD

**Issue by aktaruzzamancse** [magento/magento2#30478]
The contents from the "~/pub/static/adminhtml/Magento/backend/en_US/requirejs-min-resol
  ver.min.js" file can't be read. Warning!file_get_contents(~/pub/static/adminhtml/Magent
  o/backend/en_US/requirejs-min-resolver.min.js): failed to open stream: No such file or directory

**Comment by engcom-Delta** [comment]
Hi @aktaruzzamancse  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: No errors when deploying static content in production mode
![image](https://user-images.githubusercontent.com/51681379/99371505-abbfaa80-28c7-11eb-8331-9cbc539f26e2.png)

If you'd like to update the issue, please reopen it.
