### ISSUE TITLE
On edit order process, coupon code didn't expire, after order cancel and partial order create

### ISSUE THREAD

**Issue by muneshj99** [magento/magento2#30489]
**Preconditions**
Magento 2.3.5p1.

**Steps to reproduce:**
Create the coupon code from price rule, discount 10$, fixed amount for whole cart, select one time use, select all group of customer, apply this coupon on checkout place an order, in admin panel edit the order, and submit that order, it create the new partial order and cancel the original order from order grid, as like magento2 normal behavior, the cancel order expire the coupon code and it doesn't apply again o checkout.

**Expected result:**
The coupon doesn't apply again once the order is cancel, by manually or my edit order process.

**Actual result:**
The coupon is applied even after the order is cancel through the edit order process, it can use-able for multiple time, and that's not the normal behavior.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38530` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @muneshj99. Thank you for your report.

Below steps are performed while verifying this issue:

1. Create the cart price rule for 1 time use
![image](https://user-images.githubusercontent.com/46617848/96448882-a4a66d80-1231-11eb-916a-9bf765b89a41.png)

2. Front end: Add product to cart
3. Checkout page -> Apply coupon code 
![image](https://user-images.githubusercontent.com/46617848/96449110-fea73300-1231-11eb-838d-25bda19ff68c.png)

4. Place order
![image](https://user-images.githubusercontent.com/46617848/96449171-1a123e00-1232-11eb-8c0d-8848867cfceb.png)

5. Admin -> Sales -> Orders -> View Order 
![image](https://user-images.githubusercontent.com/46617848/96449359-56de3500-1232-11eb-9960-a1018054360e.png)

6. Edit that order -> Without update any submit that order
![image](https://user-images.githubusercontent.com/46617848/96449557-a4f33880-1232-11eb-904d-696a5a199452.png)

7. Now checking newly created order -> Coupon not applied here 
![image](https://user-images.githubusercontent.com/46617848/96449789-fef3fe00-1232-11eb-8e6e-3f9edb2eb2a4.png)

8. Try to apply coupon again on front end and it applied successfully but does't apply any discount
![image](https://user-images.githubusercontent.com/46617848/96450608-12539900-1234-11eb-8531-d22fa5c06de9.png)

**Comment by zakdma** [comment]
According to conversation with PO it is expected behaviour. If you cancel order coupon became available again. Reorder is the sequence of **cancel order** and **create new order** operations. So **cancel order** operation make coupon active again. Then you can reuse it in create new order.
