### ISSUE TITLE
Swatch Pre-select issue

### ISSUE THREAD

**Issue by surelockrich** [magento/magento2#30485]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a configurable product with multiple attributes as of now we have 2 attributes. (color and size )
2. Select both attributes on a catalog page.
3. Then click on the product.
![swatch_iss](https://user-images.githubusercontent.com/25629588/75750664-b4c51780-5d4a-11ea-996e-674f5d0f3b54.JPG)

4. Then we have Re-select the same value.
![swatch_iss-01](https://user-images.githubusercontent.com/25629588/75749336-97427e80-5d47-11ea-8960-55fe3e0e16d1.JPG)

### Expected result (*)

1. Select both attributes on a catalog page.
2. Then click on the product.
3. No need to select the same value as it has been selected in the product page
![swatch_iss-02](https://user-images.githubusercontent.com/25629588/75749370-a6293100-5d47-11ea-9ab8-4e26c8909396.JPG)

### Actual result (*)

1. This is what we are getting after, We have selected the give attributes
![swatch_iss-01](https://user-images.githubusercontent.com/25629588/75749437-d53fa280-5d47-11ea-9bdf-0d414335e99c.JPG)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38418` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
