### ISSUE TITLE
WYSIWYG add_images config option does't work properly

### ISSUE THREAD

**Issue by 0m3r** [magento/magento2#30495]
Reproduced at 2.3.5
the same code in 2.4 

if I try to hide "Insert Image(s)" 
https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-wysiwyg.html
```xml
<field name="wysiwyg_example" sortOrder="50" formElement="wysiwyg">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="wysiwygConfigData" xsi:type="array">
                        <item name="add_images" xsi:type="boolean">false</item>
```
it don't hide because
add_images option set at line 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Wysiwyg/Config.php#L202
 will be always overwritten at
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Wysiwyg/Config.php#L207
```php 
        if (is_array($data)) {
            $config->addData($data);
        }

        if ($this->_authorization->isAllowed('Magento_Cms::media_gallery')) {
            $this->configProvider->processGalleryConfig($config);
```

Possible solution 
https://github.com/magento/magento2/blob/bc8e51d18cbd327dc09b9e3813b7d1032dd9d959/app/code/Magento/Cms/Model/Wysiwyg/Gallery/DefaultConfigProvider.php#L86

```php 
$addImages = (bool) $config->hasData('add_images') ? $config->getData('add_images') : true;
return $config->addData(
            [
                'add_images' => $addImages,
```

**Comment by sumalicarter** [comment]
This is still an issue: found on enterprise M2 version 2.4.4
