### ISSUE TITLE
When creating a product, depending on the product type, only attribute sets assigned to a specific product type should be displayed

### ISSUE THREAD

**Issue by loid345** [magento/magento2#30490]
This is a suggestion to significantly improve the user experience when selecting a set of attributes eliminating errors in selecting a set of attributes

This problem occurs when you select a set of attributes when creating different product types. Each product type has its own unique set of attributes. For example, creating a downloadable product is different from creating a simple product. If the number of attribute sets is more than one hundred, it is difficult for the user to understand which set of attributes created by the administrator is necessary for a particular type of product. This makes it difficult to select an attribute set and degrades the user experience. What if there are more than a thousand attribute sets and the attribute sets was created by one user and other users create products?
If the platform operates in multi-vendor mode and vendors create products through the merchant dashboard, or if there are additional product types, such as reservations, then vendors are always confused in the attribute set. The administrator creates a set of attributes, but the vendor or Manager does not know what type of product it belongs to.
Therefore, when creating a product, depending on the product type, only attribute sets assigned to a specific product type should be displayed.

To resolve this error, when creating and editing an attribute set, you must enter an additional multiple-choice drop-down list that specifies which attribute set the product type is assigned to.
![2020-10-14_12-51-03](https://user-images.githubusercontent.com/20200970/95974005-0a06f280-0e1d-11eb-85a5-3320ab0fa177.png)
![2020-10-14_12-59-46](https://user-images.githubusercontent.com/20200970/95974487-b648d900-0e1d-11eb-8ccc-45d110c5e0e1.png)
Also, when you select an product type when creating a product, you should filter only the attribute sets selected for a specific product type.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38957` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by volanar** [comment]
The problem is relevant because there is no relationship between the product set and the product type

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
