### ISSUE TITLE
"Something went wrong with processing the default view and we have restored the filter to its original state." But this is not happening, still hanging..

### ISSUE THREAD

**Issue by In2lect** [magento/magento2#30491]
<!
Magento hangs when you sort the columns differently. The articles are no longer shown. Nothing seems to reverse this. A big problem.
-->

### Preconditions (*)

1. Magento 2.3.5
2. Catalogue > Products 

### Steps to reproduce (*)

1. Go to catalogue > Products (show 20 items/page)
2. Click on a random column to sort the the articles by this value. 

### Expected result (*)

1. Error: "Something went wrong with processing the default view and we have restored the filter to its original state." This happened when trying to filter the columns of the articles. But now the page lingers and it is not showing the articles anymore.  
2. Clicking OK is not helping. Log off/ log in again is not helping. 
![Schermafbeelding 2020-10-14 om 15 04 08](https://user-images.githubusercontent.com/72870428/95992867-b7cecd00-0e2e-11eb-85f5-f5369cc323bd.png)

### Actual result (*)

1. [Screenshots, logs or description]
2. No records found anymore and no restoring of the page...

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @In2lect. Thank you for your report.
Not able to reproduce the issue as per provided steps to by you
Feel free to reopen the issue once you confirm that issue is reproduce on 2.4-develop instance
