### ISSUE TITLE
API authentication token routes should be secure

### ISSUE THREAD

**Issue by brendanmckeown** [magento/magento2#3049]
Both of the API routes in `module-integration/etc/webapi.xml` to get an authentication token work over http.  These routes should be secure and only acceptable over https, because you are passing sensitive account information in the request body.  This can be achieved by adding `secure="true"` to each `<route>` node:

```
    <route url="/V1/integration/admin/token" method="POST" secure="true">
        <service class="Magento\Integration\Api\AdminTokenServiceInterface" method="createAdminAccessToken"/>
        <resources>
            <resource ref="anonymous"/>
        </resources>
    </route>
    <route url="/V1/integration/customer/token" method="POST" secure="true">
        <service class="Magento\Integration\Api\CustomerTokenServiceInterface" method="createCustomerAccessToken"/>
        <resources>
            <resource ref="anonymous"/>
        </resources>
    </route>
```

If this was an intentional decision, is there a way I can override this route in a custom module and enforce this behavior?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/API-authentication-token-routes-should-be-secure/idi-p/45342).
