### ISSUE TITLE
Adding required custom options to simple product removes it from parent composite products without warning

### ISSUE THREAD

**Issue by magento2pl** [magento/magento2#30492]
### Steps to reproduce
1. Login to the Magento Admin panel
2. Create a configurable or group product
3. Create a simple product and add it to configurable or group product
4. Edit simple product and add a required custom option
5. Save

### Expected result
A simple product should not be saved. A warning should be displayed to the admin user: "Required custom options cannot be added to a simple product that is a part of a composite product"

### Actual result
A simple product is saved. It is unassigned from parent composite products. No warning is displayed to the admin user.

### Additional Info

Moreover there is problem with those simple product custom options. When simple product has custom option and You are in configurable product page and You choose simple product ( configurable attribute ) there should also be possibility to choose product simple custom option.

**Comment by magento-engcom-team** [comment]
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38439` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38439` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ansari-krish** [comment]
I am working on this issue

**Comment by sivaschenko** [comment]
@ansari-krish please use `@magento I am working on this` comment exactly to self-assign to an issue

**Comment by amanverma52555** [comment]
> ### Steps to reproduce
> 1. Login to the Magento Admin panel
> 2. Create a configurable or group product
> 3. Create a simple product and add it to configurable or group product
> 4. Edit simple product and add a required custom option
> 5. Save
> 
> ### Expected result
> A simple product should not be saved. A warning should be displayed to the admin user: "Required custom options cannot be added to a simple product that is a part of a composite product"
> 
> ### Actual result
> A simple product is saved. It is unassigned from parent composite products. No warning is displayed to the admin user.
> 
> ### Additional Info
> Moreover there is problem with those simple product custom options. When simple product has custom option and You are in configurable product page and You choose simple product ( configurable attribute ) there should also be possibility to choose product simple custom option.

I have checked the same but now it works fine. Instead of being unassigned from parent composite products, it shows warning that Required custom options cannot be added to a simple product that is a part of a composite product"

**Comment by amanverma52555** [comment]
I have checked the same but now it works fine. Instead of being unassigned from parent composite products, it shows warning that "Required custom options cannot be added to a simple product that is a part of a composite product"
