### ISSUE TITLE
partial refund offline API

### ISSUE THREAD

**Issue by ITPL-Krunal** [magento/magento2#30500]
Description:
=========
**I think this is bug because of I have place all value proper and perfect by refund offline api but after I have check in backend full order go to in closed status.**

I am using magento 2.3.5. I need to offline partial refund through rest api. [I used POST /V1/order/<order_ID>/refund | Issues an offline refund ] URL : https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-issue-refund.html

My code
========
$jsonValue = array ('items' =>array (array ('order_item_id' =>$item_id,'qty' => $order_qty)),'notify' => true,'arguments' => array ('shipping_amount' => 0,'adjustment_positive' => 0,'adjustment_negative' => 0,'extension_attributes' => array ('return_to_stock_items' => array ($item_id))));

                $jsonValue =  json_encode($jsonValue);
                $order_url = $url."rest/V1/order/".$order_id."/refund";
                $setHaders = array('Content-Type:application/json','Authorization:Bearer '.$adminToken);
                $che = curl_init($order_url);
                curl_setopt($che, CURLOPT_CUSTOMREQUEST, "POST");
                curl_setopt($che, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonValue);
                curl_setopt($che, CURLOPT_HTTPHEADER, $setHaders);
                $resultcredit = curl_exec($che);
Problem : in body I have pass order_item_id' . I have pass value of item_id which I get order thorugh order api. I dont understand why full order go to in closed status.

Please suggest me full :
1) which value will pass in order_item_id ? where I get this?
2) which value will pass in return_to_stock_items ? where I get this?

**Comment by engcom-Delta** [comment]
Hi @krunalpanchal1607 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Create two simple products
- Create customer
- Place order with two simple products as customer
- Create invoice and shipment for order
- Use `POST /V1/order/<order_ID>/refund` via Postman to create partial refund
```
{
  "items": [
    {
      "order_item_id": 5,
      "qty": 1
    }
  ],
  "arguments": {
    "shipping_amount": 0,
    "adjustment_positive": 0,
    "adjustment_negative": 0
  }
}
```

**Result:**
:heavy_check_mark: Refund is created for one simple product
![Screenshot](https://user-images.githubusercontent.com/51681379/104504566-5106ae80-55eb-11eb-8fd0-cdf354954295.png)
![image](https://user-images.githubusercontent.com/51681379/104504551-4cda9100-55eb-11eb-894e-bb35041548af.png)
:heavy_check_mark: Order status is Complete

Value for `order_item_id` I took from `item_id` in `GET /V1/orders/<order_ID>` response
![image](https://user-images.githubusercontent.com/51681379/104505056-05083980-55ec-11eb-88f6-952c69a2f18a.png)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.

**Comment by krunalpanchal1607** [comment]
Thanks for reply.

In your example first you create shipment for order and after refund for one simple product then your status become "completed". this is right but my issue is another.

My question is different .
Don't do shipment and create one simple product refund then order status is going "completed" status means its wrong.
actually status not change for all order because only refund one simple product refund, another product is rest so please check and resolve this my issue. Full order go to "completed" status this is wrong.

**Comment by krunalpanchal1607** [comment]
I am waiting for your answer please reply me. I am also not able to reopen this issue. Last I will open new issue for same problem.
