### ISSUE TITLE
The new media gallery can not load images that were uploaded via file transfer (FTP, SSH)

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#30509]
The new media gallery can not load images that were uploaded via file transfer (FTP, SSH) and can not load old images too.

### Preconditions (*)

1. Php 7.4, Nginx, Mariadb
2. Install fresh Magento 2.4.1

### Steps to reproduce (*)

Issue 1:
1. Upload images to folder pub/media/wysiwyg/ by FTP (SSH)
2. Go to text editor and click insert image (by new media gallery) - **folder wysiwyg still empty**

Issue 2:
1. Go to text editor and upload image to folder wysiwyg/new/ (by new media gallery)
2. Delete images from pub/media/wysiwyg/new/ by FTP (SSH)
3. Go to text editor and insert image, all thumbnail images in wysiwyg/new/ **still exist**

Both issues exist in Magento 2.3.6 and 2.4.1

### Expected result (*)

All images should be showing in new media gallery that uploaded via file transfer (FTP, SSH)

### Actual result (*)

New media does not display images uploaded through file transfer (FTP, SSH)

**Comment by Nazar65** [comment]
@minhluan259 new media gallery runs the cron jobs for indexing your filesystems, if you don't have configured cron job, please run bin/magento media-gallery:sync

**Comment by minhluan259** [comment]
@Nazar65 thank you
