### ISSUE TITLE
URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by 2657968210** [magento/magento2#30511]
magento2.3.5-p2

{"0":"URI is not valid and cannot be converted into a string","1":"
#1 Laminas\\Http\\Request->getUriString() called at [vendor\/magento\/framework\/App\/PageCache\/Identifier.php:55]\n
#2 Magento\\Framework\\App\\PageCache\\Identifier->getValue() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n
#3 Magento\\Framework\\App\\PageCache\\Identifier\\Interceptor->___callParent('getValue', array()) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n
#4 Magento\\Framework\\App\\PageCache\\Identifier\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n
#5 Magento\\Framework\\App\\PageCache\\Identifier\\Interceptor->___callPlugins('getValue', array(), array(array('core-app-area-de...'))) called at [generated\/code\/Magento\/Framework\/App\/PageCache\/Identifier\/Interceptor.php:26]\n
#6 Magento\\Framework\\App\\PageCache\\Identifier\\Interceptor->getValue() called at [vendor\/magento\/framework\/App\/PageCache\/Kernel.php:112]\n
#7 Magento\\Framework\\App\\PageCache\\Kernel->load() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:71]\n
#8 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#00000000773f149d0000000025939023#, &Closure#00000000773f14b50000000025939023#, &Magento\\Framework\\App\\Request\\Http#00000000773f15770000000025939023#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n
#9 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000773f15770000000025939023#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n
#10 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000773f15770000000025939023#), array(array('page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'), array('front-controller...'), 'requestPreproces...')) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n
#11 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000773f15770000000025939023#) called at [vendor\/magento\/framework\/App\/Http.php:116]\n
#12 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n
#13 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n
#14 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#00000000773f15040000000025939023#) called at [index.php:57]\n","url":"close","script_name":"\/index.php","report_id":"a052b47446a2c39251c1942ed20fce6627639b45c2011f1d854be85c5268f718"}

**Comment by sdzhepa** [comment]
Hello @2657968210 

Could you please provide more details?
- Is it reproducible on 2.4-develop
- What exact steps to reproduce
- What exact Actual result
- What exact Expected result

Please see guidance https://github.com/magento/magento2/issues/30511#issuecomment-709929903 or[Issue reporting guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Without details, we are not able to check, confirm and fix this report
