### ISSUE TITLE
renderTag function html output incorrect

### ISSUE THREAD

**Issue by forcecodema** [magento/magento2#30524]
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. Preview html output in eg Google Chrome

### Expected result (*)

1. script tags rendered as `<script type="text/javascript">`

### Actual result (*)

1. script tags are being rendered with encoded slash `<script type="text&#x2F;javascript">`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by forcecodema** [comment]
It looks like it's getting escaped in:

Magento\Framework\View\Helper\SecureHtmlRender\HtmlRenderer class renderTag function:

```
public function renderTag(TagData $tagData): string
    {
        $attributesHtmls = [];
        foreach ($tagData->getAttributes() as $attribute => $value) {
            $attributesHtmls[] = $attribute . '="' .$this->escaper->escapeHtmlAttr($value) .'"';
        }
```

**Comment by mrtuvn** [comment]
Can you provide more details about steps for reproduce issue ?
Area ? frontend or backend

**Comment by mrtuvn** [comment]
what theme used in your scenario

**Comment by forcecodema** [comment]
Its frontend and the theme is stock luma - no third party plugins.

**Comment by mrtuvn** [comment]
Same result with 2.4.1 released package

**Comment by forcecodema** [comment]
Ok - makes sense.

Thanks for clarification.

**Comment by antoniocarboni** [comment]
> ![Screenshot from 2020-10-20 21-54-06](https://user-images.githubusercontent.com/1908873/96604057-dea16d80-131e-11eb-8351-0d389cafbe5a.png) use latest codebase 2.4-develop magento repo default luma theme with sample data installed
> 
> Note browser still understand type="text`&#x2F;`javascript" Html will parse to normal <script type="text/javascript"> I think the reason of this is security magento avoid attacker can inject malicious code in html attribute or another place in web html structure

some old browsers and OS (ex. iOS 15.x) not support this
