### ISSUE TITLE
Status Payment Review is not visible in front of the store.

### ISSUE THREAD

**Issue by elisei** [magento/magento2#30520]
Our method reaches payment_review status, and can stay on it for up to 72 hours, on the store frontend the consumer sees the order as "processing".

This process is done here:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Config.php#L56

But I don't see any logical reason for that. I seek guidance as to why this is applied.

### Preconditions
1. Magento 2.2+
2. Our method reaches payment_review status, without being a "fraud" state.

### Steps to reproduce
1 .Implement a customized payment method that will reach the status of payment_review.
2. Make the purchase using this method.

### Expected result
1. In the customer's view, obtain the status "payment_review"

### Actual result
1. In the customer's view, the status is "processing"

### Possible solution
Delete the line. However, I would like to understand the possible impact of this.
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by elisei** [comment]
This is not an obsolete problem and has already been pulled for solution.

**Comment by engcom-Dash** [comment]
Hi @elisei 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
