### ISSUE TITLE
The bin/magento console tool shows misleading message

### ISSUE THREAD

**Issue by brankoajzele** [magento/magento2#3052]
The `[InvalidArgumentException] There are no commands defined in the "deploy:mode" namespace.` when permissions are inadequate, see here https://db.tt/S4Y4yDyE

Seems a bit misleading.

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2300
https://mage2.pro/t/176

**Comment by mazhalai** [comment]
This is related to a ticket we are already working on: MAGETWO-49955

**Comment by mazhalai** [comment]
@ajzele this has been fixed in the develop branch in scope of #2335. Please have a look and create a new ticket if issues arise.

**Comment by ghost** [comment]
For me I had to manaully rm -Rf var/di/*
sudo php bin/magento setup:upgrade
sudo php bin/magento setup:di:compile

now I dont get 
 [InvalidArgumentException]                                     
  There are no commands defined in the "deploy:mode" namespace. 

I get this 

sudo php bin/magento deploy:mode:set developer
Enabled developer mode.

:)

hope that helps...
