### ISSUE TITLE
Magento 2.4  multisort on category

### ISSUE THREAD

**Issue by majidiyan** [magento/magento2#30532]
### Preconditions (*)

1.2.4.0
2.

### Steps to reproduce (*)

1.frontend category page
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.I set sort on collection on 2 attributes and got logs of $rawResponse   in  

  vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php 
try {
            $rawResponse = $client->query($query);
        }
$rawResponse was as I exspected, and I expected that sorting in category is the same.

### Actual result (*)

1. [Screenshots, logs or description]
2. on frontend category page was missed up.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by majidiyan** [comment]
I need sort on category page based on multi-sort  price and stock.

**Comment by engcom-Delta** [comment]
Hi @majidiyan I'm not able to reproduce issue by steps you described on clean 2.4-develop. I have checked sorting on category page and it works without errors. Multi sorting cannot be configured from admin panel
**Result:**
![image](https://user-images.githubusercontent.com/51681379/96612814-e6edae80-1306-11eb-96c4-818e1a09f865.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by majidiyan** [comment]
Hi
Yes I know in admin we cannot produce multisort capability.
I sent you part of code in vendor and explain that the query function gives the true info in enter argument and generate the true multisorted info, but I don’t know why the final result in category page is missed up.
Please check your codes.
  
>Вторник, 20 октября 2020, 19:06 +03:00 от Vasyl Shvorak <notifications@github.com>:
> 
> 
>Hi  @majidiyan I'm not able to reproduce issue by steps you described on clean 2.4-develop. I have checked sorting on category page and it works without errors. Multi sorting cannot be configured from admin panel
>Result:
>Please feel free to comment, reopen or create new ticket according to the  Issue reporting guidelines
>if you are still facing this issue on the latest 2.4-develop branch. Thank you for collaboration.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
--
АЛИ МАЖИДИЯН
