### ISSUE TITLE
Allow to Choose State if It is Optional for Country options not work in checkout

### ISSUE THREAD

**Issue by Tomasz5648** [magento/magento2#30535]
### Preconditions (*)

1. Magento 2.4.
2.

### Steps to reproduce (*)

1. Turn off option in admin panel in Stores > Configuration > General > Allow to Choose State if It is Optional for Country and disable all country in 'State is Required for'
--
--

### Expected result (*)

1. Input with state in checkout will not appear
2.

### Actual result (*)

1. Input with state in checkout appear
2.

### Additional Information
- detailed results , preconditions, and steps https://github.com/magento/magento2/issues/30535#issuecomment-711623356
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @Tomasz5648,
The first time Navigate the Checkout page "State" field is showing but after update the country value, The State field is disappears.
**PFA:**
![image](https://user-images.githubusercontent.com/24711761/96407230-912ddf00-11fe-11eb-85c7-1881fc8deed0.png)

See the screenshot after update the Country value.
**PFA:**
![image](https://user-images.githubusercontent.com/24711761/96407334-c3d7d780-11fe-11eb-9d2a-8a1c07a25715.png)

![image](https://user-images.githubusercontent.com/24711761/96407347-ccc8a900-11fe-11eb-811e-aec729953c6f.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38517` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
