### ISSUE TITLE
table setup_module not populate any data anymore

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#30531]
### Summary (*)

Any documents describe or clarify this ? To me as developer i found this a bit confuse since before everytime i want to check modules installed or not i go to directly database and check this table. But now it's not show any row anymore ! It's empty table
Is this new feature

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment]
setup module table, and the need to declare version number in etc/module.xml is part of the legacy way of defining database schema and patches. Magento now uses declaritive schema dbschema.xml files which has its own version tracking.

**Comment by mrtuvn** [comment]
Thanks for your response it's seem more make sense for me
