### ISSUE TITLE
Send in magento2 pending payment email confirmation

### ISSUE THREAD

**Issue by malkahakuk** [magento/magento2#30533]
I have the folowing issue: Id like Magento2 to send an email to notify my client that the order placed is under Pending Payment, how can I do this? Thanks

**Comment by krishprakash** [comment]
Hi @malkahakuk. Thank you for your report.
Looks like similar issue are already added #29263 
You can connect community forum OR magento stack exchange for general discuss about this

**Comment by malkahakuk** [comment]
> I have the folowing issue: Id like Magento2 to send an email to notify my client that the order placed is under Pending Payment, how can I do this? Thanks

Id like magento2 to send my client automatically after purchasing, this pending payment email.
How can I configure it?
