### ISSUE TITLE
Bug in the Captcha extension 

### ISSUE THREAD

**Issue by trunglv** [magento/magento2#30537]
I found a bug in this file : 
vendor/magento/module-captcha/view/frontend/web/js/view/checkout/defaultCaptcha.js
Line 59 : 
`!_.isEmpty(captchaData)[formId] `
It should be 
 `!_.isEmpty(captchaData[formId])`

### Preconditions (*)
Magento 2.4.1
:warning: **Note:** Issue cannot be reproduced on magento 2.4-develop (git version)

### Steps to reproduce (*)
1. Configure CAPTCHA for Checkout/Placing Order
![#30537IssueCaptchaSettings](https://user-images.githubusercontent.com/51681379/96613413-9aef3980-1307-11eb-9343-26b2562c62dc.png)
2. Create customer and login
3. Place order
4. Add product cart again
5. Go to checkout page
6. Click on Place Order button
 
### Expected result (*)
1. Order is placed successfully

### Actual result (*)
1. Validation message "Please provide CAPTCHA code and try again" is shown
2. Order cannot be placed
![Peek 2020-10-20 14-07](https://user-images.githubusercontent.com/51681379/96613800-0cc78300-1308-11eb-870d-cd6175c47fc0.gif)

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this issue

**Comment by ihor-sviziev** [comment]
Hi @engcom-Delta @trunglv,
If the issue isn't reproducing on 2.4-develop branch - seems like the issue was already solved here or maybe suggested solution isn't correct, right?

**Comment by chiranjeevi-cj** [comment]
@magento give me an instance.

**Comment by chiranjeevi-cj** [comment]
@magento give me a Magento 2.4 instance.

**Comment by chiranjeevi-cj** [comment]
@magento give me 2.4-develop instance

**Comment by chiranjeevi-cj** [comment]
@magento give me 2.4-develop instance

**Comment by chiranjeevi-cj** [comment]
Hi, @engcom-Delta @trunglv @ihor-sviziev,
This issue isn't producing on the 2.4-develop branch.
