### ISSUE TITLE
Elasticsearch issue "number_format_exception" - 2.4.1 

### ISSUE THREAD

**Issue by trunglv** [magento/magento2#30540]
I found a bug in the Elasticsearch extension when I tried to use the search functionality.  
Here is a log message I got 

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: For input string: \"xxx\"","index_uuid":"w5egRGlqQV6LbgrdYBqBYQ","index":"magento2_product_26_v157"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_26_v157","node":"UulsefOgTbiBKXUkTrwSPg","reason":{"type":"query_shard_exception","reason":"failed to create query: For input string: \"kawai\"","index_uuid":"w5egRGlqQV6LbgrdYBqBYQ","index":"magento2_product_26_v157","caused_by":{"type":"number_format_exception","reason":"For input string: \"xxx\""}}}]},"status":400}

What I found is: Magento\Elasticsearch\SearchAdapter\Query\ValueTransformerPool was missing an item for a double type attribute.
So we should add a new one: 
`<item name="double" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\DoubleTransformer</item>`
or 
`<item name="float" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\FloatTransformer</item>`

File: vendor/magento/module-elasticsearch/etc/di.xml

```
<type name="Magento\Elasticsearch\SearchAdapter\Query\ValueTransformerPool">
        <arguments>
            <argument name="valueTransformers" xsi:type="array">
                <item name="default" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\TextTransformer</item>
                <item name="date" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\DateTransformer</item>
                <item name="float" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\FloatTransformer</item>
                <item name="integer" xsi:type="object">Magento\Elasticsearch\SearchAdapter\Query\ValueTransformer\IntegerTransformer</item>
            </argument>
        </arguments>
    </type> 

```
### Preconditions (*)
1. Magento 2.4.1
2. Elastic Search 

### Steps to reproduce (*)
1. Try to search for a product on the frontend 
2. It doesn't work if there is a product attribute type is a double that is considered in the search query. 

### Expected result (*)
Search functionality should work properly. 

### Actual result (*)
It doesn't work if there is a product attribute type is a double that is considered in the search query.

**Comment by engcom-Bravo** [comment]
Hello @trunglv 

Thank you for your report

Can you please provide more details about the steps to reproduce with, screenshots attached? It's not clear how is the _double attribute_ created and searched for.
In this way, we could faster reproduce the issue and provide a fix for it

Thank you in advance

**Comment by trunglv** [comment]
Hi @engcom-Bravo 
Here is what I debugged:
 
Class : Magento\Elasticsearch\SearchAdapter\Query\Builder\Match => function buildQueries
 
```
$attributeAdapter = $this->attributeProvider->getByAttributeCode($resolvedField);
$fieldType = $this->fieldTypeResolver->getFieldType($attributeAdapter);

```
A variable $fieldType is returned a value is "double",  not "float"

class : Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldType\Resolver\CompositeResolver
class : Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldType\Resolver\FloatType
```
if ($attribute->isFloatType()) {
            return $this->fieldTypeConverter->convert(ConverterInterface::INTERNAL_DATA_TYPE_FLOAT);
}
```
class Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldType\Converter
```
private $mapping = [
        self::INTERNAL_DATA_TYPE_STRING => self::ES_DATA_TYPE_STRING,
        self::INTERNAL_DATA_TYPE_KEYWORD => self::ES_DATA_TYPE_STRING,
        self::INTERNAL_DATA_TYPE_FLOAT => self::ES_DATA_TYPE_DOUBLE,
        self::INTERNAL_DATA_TYPE_INT => self::ES_DATA_TYPE_INT,
        self::INTERNAL_DATA_TYPE_DATE => self::ES_DATA_TYPE_DATE,
    ];

```
You can see variable mappings: It mapped "float" => double. So it's a problem I think.

**Comment by engcom-Bravo** [comment]
Hello @trunglv 

I have rechecked the issue on the latest 2.4-develop with the following settings
**Catalog Input Type for Store Owner** - _Text field_
**Input Validation for Store Owner** - _Decimal Number_
![dec_attr_sett](https://user-images.githubusercontent.com/51680745/97181472-fc9a2280-17a3-11eb-9719-2e0a015e3819.png)
**Use in Search** - _Yes_
**Visible in Advanced Search** - _Yes_

I have created a Simple product and added the previously created attribute to it
![attr_in_product](https://user-images.githubusercontent.com/51680745/97181848-6b777b80-17a4-11eb-8bd3-d19e3e9d7783.png)

I can perform search on Storefront via attribute value and via Title. No error appears in log

Can you please confirm that you are able to reproduce the issue on 2.4-develop?

Thank you

**Comment by krish-vivek** [comment]
Hello @trunglv
Agree with @engcom-Bravo 

After following steps mentioned by you, product is showing in search list, so can you provide more information

Please review screenshot.

![1_search](https://user-images.githubusercontent.com/65163673/97776998-e371e700-1b92-11eb-930b-14b4fdc1f57d.png)
![2_attributr](https://user-images.githubusercontent.com/65163673/97776999-e4a31400-1b92-11eb-83c8-b7d15fb8d1cb.png)

**Comment by krishprakash** [comment]
Hello @trunglv. Feel free to reopen/comment once you confirm that issue reproduce on 2.4-develop instance 
Thanks!!

**Comment by siliconalchemy** [comment]
I'm getting exactly the same problem.  I wasn't actually aware I had so many attributes searchable (141!) so it will be difficult to track down which is the problem attribute, but this only occurred after upgrade from 2.3 to 2.4 and change from mysql to elasticsearch catalog search engine.  The elasticsearch error is:
```
Caused by: java.lang.NumberFormatException: For input string: "BEKO"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:549) ~[?:?]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType.objectToDouble(NumberFieldMapper.java:876) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType.access$200(NumberFieldMapper.java:173) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.parse(NumberFieldMapper.java:369) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.termQuery(NumberFieldMapper.java:388) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberFieldType.termQuery(NumberFieldMapper.java:928) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.lambda$newTermQuery$1(MatchQuery.java:576) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.newTermQuery(MatchQuery.java:579) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:277) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.MatchQueryBuilder.doToQuery(MatchQueryBuilder.java:426) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:394) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:380) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:334) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:346) ~[elasticsearch-7.6.2.jar:7.6.2]
```

And the corresponding entry in magento log:
```
}\",\"index_uuid\":\"rgbnzqW-SViJjs7WwTy-yg\",\"index\":\"magento2_product_1_v6\",\"caused_by\":{\"type\":\"number_format_exception\",\"reason\":\"For input string: \\\"BEKO\\\"\"}}}]},\"status\":400} at /srv/www/vhosts/cartersdirect.co.uk/dev.www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632)"} []
```

Magento: 2.4.1 opensource.

**Comment by siliconalchemy** [comment]
OK this was actually pretty easy to track down.  Look for eav_attribute.backend_type ='decimal' and change 'Use in Search' to 'No' for each attribute:

<img width="1908" alt="Screenshot 2020-12-11 at 17 53 05" src="https://user-images.githubusercontent.com/4799996/101937432-c42a9880-3bd9-11eb-89e0-84af676f7c68.png">

<img width="1075" alt="Screenshot 2020-12-11 at 17 52 03" src="https://user-images.githubusercontent.com/4799996/101937460-c987e300-3bd9-11eb-8f01-84818b2f743c.png">

After this, the search works as expected.

**Comment by trunglv** [comment]
Already fixed in Magento 2.4.2. Thanks

**Comment by zhartaunik** [comment]
I faced the same issue. In my case attribute wasn't created using UI. Decimal attributes there created as 
backend_type = varchar, frontend_input = text
In my case I made the following:
backend_type = decimal, frontend_input = text [optional input validation]

**Comment by HarryHung-Shopstack** [comment]
i got same issue. how about update it, hello @trunglv

**Comment by trunglv** [comment]
Pls check my quick fix - It may help
https://github.com/betagento/magento2_search_fixing

**Comment by HarryHung-Shopstack** [comment]
> Pls check my quick fix - It may help
> https://github.com/betagento/magento2_search_fixing

thanks @trunglv , i tried but it's not working for me.
hot fix i have to set config "use in search" to No

**Comment by trunglv** [comment]
> > Pls check my quick fix - It may help
> > https://github.com/betagento/magento2_search_fixing
> 
> thanks @trunglv , i tried but it's not working for me.
> hot fix i have to set config "use in search" to No

I worked on my customer website. Hope you have already done  necessary commands for it : setup-upgrade, Di Compile -- Cache so on ... -- Anyway Thanks for trying. I will try it to aother place

**Comment by HarryHung-Shopstack** [comment]
i am using magento 2.4.0
i create an attribute 
![image](https://user-images.githubusercontent.com/76460551/110893723-1ab68880-8329-11eb-8681-7330c0dc1459.png)
i can typing the number to the search box  and it's working
but if i typing the string/text to the search box, it's not work
already got the error 
`Exception #0 (Elasticsearch\Common\Exceptions\BadRequest400Exception): {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: For input string: \"xxx\"","index_uuid":"4Z6fNLOJT9mTqJ6KP9Py2Q","index":"magento2_homepro_product_2_v2"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_homepro_product_2_v2","node":"TGeJyLN7QhWm3nsFo-bVxA","reason":{"type":"query_shard_exception","reason":"failed to create query: For input string: \"xxx\"","index_uuid":"4Z6fNLOJT9mTqJ6KP9Py2Q","index":"magento2_homepro_product_2_v2","caused_by":{"type":"number_format_exception","reason":"For input string: \"xxx\""}}}]},"status":400}`

**Comment by tuyennn** [comment]
@krishprakash this was still reproduced on M2.4.0-p1

**Comment by trunglv** [comment]
> @krishprakash @engcom-Bravo this was still reproduced on M2.4.0-p1

Try my solution https://github.com/betagento/magento2_search_fixing

**Comment by jamie-selesti** [comment]
Still reproduced on Magento 2.4.2-p1 

Using https://github.com/betagento/magento2_search_fixing fixed my issue

**Comment by netjordanlee** [comment]
Reproduced in 2.4.3-p1

As @HarryHung-Shopstack describes, we can search for numbers, but trying to do a search for any string results in the error above (number_format_exception). Haven't tested the fix from @trunglv yet, will edit here with results when tested.

**Comment by redati** [comment]
reproduced in 2.4.5-p1 and https://github.com/betagento/magento2_search_fixing  dont fix for me.

**Comment by siliconalchemy** [comment]
Magento will ignore any closed issue (and close any new one as quickly as possible) - no point commenting on this one.  Raise a new issue and reference this one (see #30194).  I've had to raise 4 or 5 issues for a problem before to get it fixed.

https://github.com/betagento/magento2_search_fixing doesn't work any longer for me either in 2.4.5-p1.

**Comment by redati** [comment]
my solution is fix in amasty shobby

app/code/Amasty/Shopby/Model/Layer/Filter/Category.php em apply
$categoryId = is_numeric($categoryId) ? $categoryId : null;

where $categoryId is not validated and used for atack population log, requests contains ?cat=string and others sql injection

**Comment by JonathanHelvey** [comment]
https://github.com/betagento/magento2_search_fixing doesn't work any longer for us either. We are on Magento2.4.4-p2. This error is thrown constantly in our exception.log in Magento2.
