### ISSUE TITLE
[2.3.5] Shipping address gets assigned customer_address_id = 0.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#30543]
### Preconditions (*)

1. Magento 2.3+ (most likely also earlier versions)

### Steps to reproduce (*)

1. Create an order through the admin panel
2. As the billing address use "Add New Address"
3. As the shipping address set "Same As Billing Address"
4. Reorder the Order.

### Expected result (*)

1. Reordered is identical to the original order.
2. The shipping address is using "Same As Billing Address"

### Actual result (*)

1. Reordered order is identical except for the Shipping address.
2. The shipping address is not using "Same As Billing Address"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

When you are using "Same As Billing Address" in the admin panel Shipping Address on the Order (the data on the quote is correct) gets the Custom Address Id 0 instead of null, if the billing address is new. This results in the check to see if the address are identical to fail on reorder because 0 != null. This can cause new addresses being saved for every reorder you do or data to be unset if you are not careful.

**Comment by engcom-Bravo** [comment]
Hello @Hexmage

Thank you for your report.

We have tried to reproduce the issue using the steps provided in the description and seems that it already fixed on the latest 2.4-develop.

**Preconditions**
Magento 2.4-develop

**Steps to reproduce:**

1. Create an order through the admin panel
2. As the billing address use "Add New Address"
3. As the shipping address set "Same As Billing Address"
![New address](https://user-images.githubusercontent.com/67371013/98241393-8d76b800-1f73-11eb-8217-9eeafd5c39f3.png)
4. Reorder the Order.

**Actual result:**
Reordered is identical to the original order.
The shipping address is using "Same As Billing Address"

![After reorder](https://user-images.githubusercontent.com/67371013/98242147-acc21500-1f74-11eb-9a5d-825b3ff7e981.png)

So we are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you
