### ISSUE TITLE
separate  products and categories into a separate DB(DB is 250GB) and reuse it for multiple M2.4 shops ?

### ISSUE THREAD

**Issue by elizad** [magento/magento2#30544]
any idea of how can I have products and categories in M 2.4.1 community in a separate database from the actual shop and reuse products and categories in for a new M 2.4? The database I need to share is about 250GB. Thanks

**Comment by krishprakash** [comment]
Hi @elizad. Thank you for your report.
GitHub issue tacker is intended for Magento core technical issues only
Kindly refer community forum or Magento stack exchange for general discuss about this topic.
