### ISSUE TITLE
System Upgrade fails via Setup Wizard - Failed opening autoload.php

### ISSUE THREAD

**Issue by jason-vivid** [magento/magento2#3055]
Subject says it all...  

After entering public and private keys and running through to the last step (Step 4) which is the system upgrade. Update breaks.  Log below.

[Thu Jan 21 01:15:28.618633 2016] [:error] [pid 15527] [client IP:64218] PHP Warning:  require_once(/public_html/magento2/update/vendor/autoload.php): failed to open stream: No such file or directory in /public_html/magento2/update/app/bootstrap.php on line 13, referer: https://example.com/setup/
[Thu Jan 21 01:15:28.618709 2016] [:error] [pid 15527] [client IP:64218] PHP Fatal error:  require_once(): Failed opening required '/public_html/magento2/update/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /public_html/magento2/update/app/bootstrap.php on line 13, referer: https://example.com/setup/

**Comment by tanya-soroka** [comment]
Ticket for investigation has been created: MAGETWO-48266

**Comment by mazhalai** [comment]
@jason-vivid  did you install via composer-create project via default packagist or repo.magento.com? Please run `composer install` within the `update` folder, and try again. Also, please add the following to your _root_ composer.json file

```
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
```

**Comment by jason-vivid** [comment]
Ran composer via repo.magento.com

The lines above were already in the root repository. 

When I go to the update page now I'm getting this message: 

"System Upgrade Status:
Update application is running"

But the server doesn't show any activity and the system is still on the old version.

Console Log:
    [2016-01-25 19:47:04 EST] Job "maintenance_mode {"enable":true}" has been started
    [2016-01-25 19:47:04 EST] Magento maintenance mode is enabled.
    [2016-01-25 19:47:04 EST] Job "maintenance_mode {"enable":true}" has successfully completed
    [2016-01-25 19:47:04 EST] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}" has been started
    [2016-01-25 19:47:04 EST] Starting composer update...
    [2016-01-25 19:47:05 EST] ./composer.json has been updated

**Comment by mazhalai** [comment]
@jason-vivid can you confirm if the suggested crons are still running?

**Comment by jason-vivid** [comment]
Crons for the magento user are listed below.  They are firing every minute.  

m h  dom mon dow   command
*/1 \* \* \* \* php -c /etc/php5/cli/apache2 /fullpath//public_html/magento2/bin/magento cron:run
*/1 \* \* \* \* php -c /etc/php5/cli/apache2 /fullpath//public_html/magento2/update/cron.php
*/1 \* \* \* \* php -c /etc/php5/cli/apache2 /fullpath//public_html/magento2/bin/magento setup:cron:run

Running manually as the magento user the update cron says "Cron is already in progress..."  

That being said there are no processes running that match.

**Comment by mazhalai** [comment]
@jason-vivid, possibly there were some errors and it stopped midway. Some suggestions:
- add full path to php executable in cron
- stream output of cronjobs to some logs and check it. for example
  `*/1 * * * * /var/local/bin/php -c /etc/php5/cli/apache2 <fullpath>/public_html/magento2/update/cron.php >/tmp/magento.update.cron.log&` 
- look for `var/.update_in_progress.flag` and delete it. also clean `var/.update_queue.json` (if it is not already empty)

**Comment by jason-vivid** [comment]
Thanks for the help.  Deleting var/.update_in_progress.flag flag let me see that it was an out of memory issue. I bumped up the memory and it bombed again for different reasons. 

Closing this and opening a new item.
