### ISSUE TITLE
Theme disappeared and do not know how to fix 

### ISSUE THREAD

**Issue by CJMacPhie** [magento/magento2#30555]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @CJMacPhie.
Kindly update all the details as per issue reporting guidelines
Without these details we can not process this issue and it should be closed
Thanks

**Comment by krishprakash** [comment]
Feel Free to reopen the issue once you update all the details as per [issue reporting guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Also GitHub issue tacker is intended for Magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [Magento stack exchange](https://magento.stackexchange.com/) for discuss about this topic
Thanks!!
