### ISSUE TITLE
Can't download Product Files Into A CSV file

### ISSUE THREAD

**Issue by CJMacPhie** [magento/magento2#30574]
### Preconditions (*)

1.Magento ver. 2.3.4
2.Can't Export Product Information down into a CSV File?

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.I would like all my products to be downloaded to a CSV file

### Actual result (*)

1. [Screenshots, logs or description]
2.Nothing goes to a blank screen and idles with nothing happening.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bowens20832** [comment]
Can verify on 2.4.1 Vanilla

**Comment by Bowens20832** [comment]
@magento give me 2.4-develop instance

**Comment by Bowens20832** [comment]
Can not reproduce the issue on a 2.4-develop instance.

**Comment by ajijshekh123** [comment]
Hi @CJMacPhie,
I have verified this issue in the Latest Magento 2.4 Instance with as per your steps, actual result and expected result.
Export product functionality is working fine.
If you found this issue again please send me details about the Magento Version and Attached the video.

Thanks.

**Comment by CJMacPhie** [comment]
Still not working for me.

Thanks

Cam

**Comment by CJMacPhie** [comment]
Still cannot download or is it finding any of our products.

Am I doing this incorrectly?

Cam

**Comment by ajijshekh123** [comment]
Hi @CJMacPhie,
I have tried with the Latest Magento 2.4 Instance but Not able to reproduce this issue.
See attached the video:

![Dashboard _ Magento Admin](https://user-images.githubusercontent.com/24711761/97774374-380a6780-1b7d-11eb-971d-e418d992ea4e.gif)

Thanks.

**Comment by ajijshekh123** [comment]
Hi @CJMacPhie,
If you have reproduced this issue again you can reopen this issue.
Thanks.
