### ISSUE TITLE
Test new Issue board 

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#30573]
[Issue Confirmation and Triage Board ](https://github.com/magento/magento2/projects/23)
- all new issues should appear on this board
- when issue is confirmed(reproduced on 2.4-develop) and has a Priority label(triaged) it should move to one of the next boards

[Low Priority Backlog](https://github.com/magento/magento2/projects/25)
- when the issue is confirmed and triaged as P3 P4 it should appear on this board

[High Priority Backlog](https://github.com/magento/magento2/projects/26)
- when the issue is confirmed and triaged as P0 P1 P2 it should appear on this board

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-backlog[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38581` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-38581` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
