### ISSUE TITLE
GraphQL: filtering by simple product SKU returns bundle products, leading to pageSize flaws

### ISSUE THREAD

**Issue by real34** [magento/magento2#30578]
### Preconditions (*)

1. Magento 2.4.1 with sample data 

### Steps to reproduce (*)

1. Run the following GraphQL query:

```graphql
products(filter: { sku: { in: [ "24-WG084"] } }, pageSize: 1) {
    items {
      sku
    }
  }
```

### Expected result (*)

1. GraphQL should only return reviews for the `24-WG084` product.

```json
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "24-WG084"
        }
      ]
    }
  }
}
```

### Actual result (*)

1. The following response is returned. It includes reviews from `24-WG080` (a bundle product containing `24-WG084`)
```json
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "24-WG080"
        }        
      ]
    }
  }
}
```

3. This problem causes a **really annoying bug** if the `pageSize` is exactly the number of SKUs in the query.

### Workaround

The `24-WG084` product is returned if the `pageSize` is greater. It means that clients for now have to overfetch data in order to be sure to retrieve the simple product wanted.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @real34 

Thank you for your report

We have just rechecked the issue on 2.4-develop and on 2.4.1

This is the result we get from the query provided in Steps to reproduce
![mage_24develop_graph](https://user-images.githubusercontent.com/51680745/96724361-6b4c3a00-13b8-11eb-88fa-ab610229c721.png)

The SKU in the query is the same as the returned SKU in the response 

Can you please correct our steps so we could faster reproduce the issue and provide a solution for it?

Thank you in advance

**Comment by real34** [comment]
Thanks for the feedback, I'll try from a totally blank project… time to use the Magento bot for the first time!

@magento give me 2.4-develop instance

**Comment by real34** [comment]
Thank you everyone. I cannot reproduce, it must be related to overrides on the project I was on.
Sorry for bothering you. :wave:
