### ISSUE TITLE
mini search field head does not appear if suggestions and recommendations are disabled. Luma Theme and mobile navigation.

### ISSUE THREAD

**Issue by redati** [magento/magento2#30584]
### Preconditions (*)

Magento 2.4-develop

1. does not work when suggestions are disabled
2. because form-mini.js is not loaded
3. imput depends on the click to appear and the logic is in form-mini.js

<?php if ($helper->isSuggestionsEnabled()): ?>
           data-mage-init='{"quickSearch":{data-mage-init='{"quickSearch":{
 
problem here
                                   ...
<?php endif; ?>	  

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Configuration -> Catalog -> Catalog -> Catalog Search and set:

- **Enable Search Recommendations** to **No**
- **Enable Search Suggestions** to **No**

2. Click on the **Save Config** button;
3. Clean cache;
4. Using the standard luma theme, browse with mobile.
5. Click on the search button;

### Expected result (*)

 Appear input form search (form minisearch)

### Actual result (*)
:heavy_multiplication_x: Nothing happens

![Peek 2020-10-22 12-37](https://user-images.githubusercontent.com/51679138/96853715-5aa4ce00-1463-11eb-848c-361fd2ec8ea2.gif)

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [S4] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by redati** [comment]
@magento give me 2.4-develop instance

**Comment by redati** [comment]
problem confirmed

https://i.ibb.co/YQ7C7xv/disable-sugest.jpg
https://i.ibb.co/8M55TFH/erro.gif

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38652` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @redati. Thank you for your report. 
The issue has been fixed in magento/magento2#30634 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [e567fd6c343cd383bc58b8b6b8b90b45844ded7d](https://github.com/magento/magento2/commit/e567fd6c343cd383bc58b8b6b8b90b45844ded7d)
 - [dd044a0ad1e453325abb1f5eda8de2a8a067069c](https://github.com/magento/magento2/commit/dd044a0ad1e453325abb1f5eda8de2a8a067069c)

The fix will be available with the upcoming 2.4.3 release.

**Comment by kennylawrence** [comment]
this bug has killed me twice now. First on a development server, then again when I moved the theme over but didn't also check those particular settings (or at least, didn't care about them).
