### ISSUE TITLE
Complex products children ids are not cached in Type class leading to multiple unnecessary db requests

### ISSUE THREAD

**Issue by PierreLeMaguer** [magento/magento2#30585]
**Description**

in the product page, the method 'getChildrenIds' is called several times and each time we make an SQL request to get this info. 
For example juno-jacket.html with the sample data, the method of the configurable type is called 20 times.

**The problem**
The result of this method is not stored in a cache to avoid to make useless request.

**benefits**
We earn time by making a cache and storing the results instead of making SQL requests.

Related pull request closed due to inactivity: https://github.com/magento/magento2/pull/23910

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38593` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
