### ISSUE TITLE
Web Setup Wizard fails to upgrade to 2.0.1, gives "Sorry, we can't take that action right now." message

### ISSUE THREAD

**Issue by CalamityJames** [magento/magento2#3059]
I've run into this problem while trying to upgrade to 2.0.1.

If I try to perform the System Upgrade in the Web Setup Wizard I get the following message:
![image](https://cloud.githubusercontent.com/assets/5637797/12479334/5b467a50-c032-11e5-8ee2-4d36522814b6.png)

I've supplied my Magento Secure Keys as suggested elsewhere, but upon delving into the code a bit deeper it would seem my package information is not being pulled across.

`setup/src/Magento/Setup/Model/SystemPackage.php`  scans all the packages for "system packages", and according to mine at least, finds none.

I edited `getInstalledSystemPackages` to echo out every package installed (not just system packages) and it only returns the following:

```
braintree/braintree_php
composer/composer
justinrainbow/json-schema
magento/composer
magento/magento-composer-installer
magento/zendframework1
monolog/monolog
oyejorge/less.php
pelago/emogrifier
phpseclib/phpseclib
psr/log
seld/jsonlint
symfony/console
symfony/event-dispatcher
symfony/finder
symfony/process
tedivm/jshrink
tubalmartin/cssmin
zendframework/zend-code
zendframework/zend-config
zendframework/zend-console
zendframework/zend-crypt
zendframework/zend-di
zendframework/zend-escaper
zendframework/zend-eventmanager
zendframework/zend-filter
zendframework/zend-form
zendframework/zend-http
zendframework/zend-i18n
zendframework/zend-inputfilter
zendframework/zend-json
zendframework/zend-loader
zendframework/zend-log
zendframework/zend-math
zendframework/zend-modulemanager
zendframework/zend-mvc
zendframework/zend-serializer
zendframework/zend-server
zendframework/zend-servicemanager
zendframework/zend-soap
zendframework/zend-stdlib
zendframework/zend-text
zendframework/zend-uri
zendframework/zend-validator
zendframework/zend-view
```

Yet the code makes reference to expecting to find packages such as `magento/product-community-edition`.

The actual error being thrown via JSON when I try to run the upgrade is:
`{"error":"System packages not found","responseType":"error"}`

If anyone has any idea why this is happening I'd greatly appreciate some input as there is next to nothing available on the net for Magento 2 problems as of yet. Especially upgrading the system as this is the first patch to be released.

Regards,
James.

**Comment by Krapulat** [comment]
I have the same problem. I've supplied the Magento Keys and get "Sorry, we can't take that action right now. " when trying to use the system upgrade.

**Comment by fendowuk** [comment]
I'm also having the same issue.

**Comment by ghost** [comment]
This is due to the fact that you aren't logged in. We have an internal issue open to track, MAGETWO-458175.

To get around it, go to **System Config** (right below **System Upgrade**) and enter your authentication keys, then **Save Config**

**Comment by ghost** [comment]
FWIW, I added this to the [System Upgrade documentation page](http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html). It's kind of hard to find though.

**Comment by fendowuk** [comment]
I have logged in and still have the same issue. I am wondering if this is anything to do with /update/cron.php or the lack of it. I installed Magento 2 using composer but the /update/cron.php file is missing.

**Comment by CalamityJames** [comment]
@xcomSteveJohnson Sorry, but this is a separate issue. I've added those details already, as per my OP:

> I've supplied my Magento Secure Keys as suggested elsewhere

![image](https://cloud.githubusercontent.com/assets/5637797/12482342/fb134626-c046-11e5-9c90-63a45e165075.png)

**Comment by fendowuk** [comment]
@CalamityJames have you got an update folder?

**Comment by ghost** [comment]
I'm not sure if it's related to cron but the readiness check will fail if the updater cron job is not running. Set up your cron as instructed [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_cron.html).

**Comment by ghost** [comment]
And BTW, if you cloned the Magento 2 GitHub repo (as opposed to using `composer create-project` or a zip/tar), you cannot use System Upgrade anyway. [This topic](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/dev_options.html) should help you.

**Comment by Krapulat** [comment]
@xcomSteveJohnson I'm logged in (supplying the keys) and the cron job is running fine. I installed magento 2 using composer create-project.

And I get: "Sorry, we can't take that action right now."

**Comment by fendowuk** [comment]
@xcomSteveJohnson I installed magento 2 via composer create-project, the readiness check was fine, all cron jobs are running fine except /update/cron.php which errors "Could not open input file: /home/directory/public_html/update/cron.php" I presume that is due to the fact the update folder was not included in the installation. I have tried a fresh install and there is still no update folder included.

**Comment by ghost** [comment]
Try running the updater cron from the command line and see if it reports an error.

**Comment by ghost** [comment]
@fendowuk Could be permissions? The updater _is_ included in `composer create-project` and the zip/tar. If it's not there, try adding it as [here](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/prereq_updater.html). Caveat, never tried that, don't know if it works.

**Comment by ghost** [comment]
@Krapulat You're getting this before the first step, the readiness check, correct?

**Comment by Krapulat** [comment]
@xcomSteveJohnson Yes.

![screen shot 2016-01-21 at 15 50 04](https://cloud.githubusercontent.com/assets/4441564/12483686/b4112f3a-c056-11e5-9cdb-1be784c8a98f.png)

**Comment by CalamityJames** [comment]
@xcomSteveJohnson Thank you. My colleague had installed it via Git (I usually install via composer) so the other method you described was spot on.

Might be worth referencing this in the [original link](http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html) you provided?

**Comment by ghost** [comment]
OK, will do. Glad you worked it out. If I didn't mention it, we have an internal issue open to track a fix for this.

**Comment by fendowuk** [comment]
@xcomSteveJohnson I set permissions as outline after install. Is it not more likely to be the fact that the cron job is trying to open a file that doesn't exist? If there is no update folder and so no cron.php file included then the cron can't open it? I installed via composer but looking here https://github.com/magento/magento2 there is no update folder either?

**Comment by ghost** [comment]
The updater is in a separate repository [here](https://github.com/magento/magento2-community-edition).

If you have no `<your Magento install dir>/update/cron.php` after installing via `composer create-project`, something went wrong.

Example:

```
ls -1 /var/www/html/magento2/update
app
composer.json
composer.lock
cron.php
dev
index.php
pub
README.md
var
vendor
```

**Comment by ghost** [comment]
@Krapulat What is the status with your upgrade? Any progress?

**Comment by Krapulat** [comment]
@xcomSteveJohnson No, I can't upgrade the system. In my case cron works perfectly.

**Comment by ghost** [comment]
Only things I can think of:
-  Go to Component Manager and see if it thinks you're signed in. If not, try signing in and seeing if there is an error.
-  Generate another pair of authentication keys and log in with those. 

If those things don't work, you'll get a response soon.

**Comment by Krapulat** [comment]
@xcomSteveJohnson

· Inside Component Manager it thinks I logged in:

![screen shot 2016-01-21 at 16 25 24](https://cloud.githubusercontent.com/assets/4441564/12484812/4461027c-c05c-11e5-96ba-f0362d5c5027.png)

· I generated new keys, logged in with those but the same error.

**Comment by Krapulat** [comment]
@xcomSteveJohnson now it works! and I've done nothing...

**Comment by tanya-soroka** [comment]
MAGETWO-48262 ticket for investigation has been created.

**Comment by monkeysee** [comment]
@CalamityJames , Is this still a problem for you?  There is other discussion here and wanted to make sure your original issue is complete.

**Comment by ark99** [comment]
@CalamityJames ,  did I understand correctly that your colleague did installation via "git pull" ? If so, you will have to do "git pull" to upgrade and then

"composer install"
bin/magento setup:upgrade

Thanks!

**Comment by alankent** [comment]
Regarding "git", I just repeat in different places to help clarify how things work post GA, if you are doing a production site the official recommendation is use composer or the ZIP, not git clone/pull. (And yes, clearly we have some things to iron out with patching!) We do not recommend building production sites from git as the upgrade process is not guaranteed to work between arbitrary git commits. We only guarantee it between official releases. The directory structure is different too (e.g. vendor directory vs app/code), potentially causing issues. It's just gets messy. So git clone/pull if you are playing around - but as soon as you are talking production I would strongly recommend using composer or ZIP (the ZIP is a ZIP of the composer build).

**Comment by Eroan** [comment]
Same issue there..

**Comment by mazhalai** [comment]
Have you followed instructions posted [here](http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html)

**Comment by mazhalai** [comment]
@CalamityJames this issue has been fixed in the develop branch. Thank you for reporting this bug. Please open a new ticket if more issues arise.
