### ISSUE TITLE
0 shipping .. happins somtimes? cand figure out why?

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#30592]
### Preconditions (*)

1. lamp php 7.2
2. magento 2.3.1

### Steps to reproduce (*)

1. making a normal order

### Expected result (*)

1. shipping to be calculated in all orders

### Actual result (*)

1. shipping not calculated sometimes in some orders ( happens 1 in 500 )
- magento settings
![Screenshot from 2020-10-21 18-55-09](https://user-images.githubusercontent.com/3238761/96752952-75c5fe00-13cf-11eb-8c55-706acd16f78e.png)
- sample order
[order_11000452843_20-Oct-21_22-10-22.pdf](https://github.com/magento/magento2/files/5417551/order_11000452843_20-Oct-21_22-10-22.pdf)

**Comment by engcom-Delta** [comment]
Hi @salehawal you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop.
**Manual testing scenario:**
- Configure Flat Rate shipping method
![image](https://user-images.githubusercontent.com/51681379/96875049-75853b80-147f-11eb-8f74-daf0a594124e.png)
- Go to storefront
- Create customer and login
- Add some product to cart
- Place order with Flat Rate shipping method

**Result:**
**Shipping & Handling** is present in order and is correctly calculated
![image](https://user-images.githubusercontent.com/51681379/96875650-225fb880-1480-11eb-9e50-8851d47287ce.png)
![image](https://user-images.githubusercontent.com/51681379/96875819-5935ce80-1480-11eb-8cfe-8ab5d8cb39b6.png)
[#30592IssueOrder.pdf](https://github.com/magento/magento2/files/5422965/30592IssueOrder.pdf)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
