### ISSUE TITLE
Catalog Price Rule not working for magento2 rest api

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30593]
### Preconditions

1.  Magento 2.2.5 with Sample Data
2.  php 7.0+

### Steps to reproduce

1.  Create a Catalog Rule
2.  Run the cron and indexing
3.  Check /V1/products/{sku} rest api

### Expected result

1. Catalog rule applied price should come in special_price 

### Actual result

1.  It is not coming.

**Original Report**: https://github.com/magento/magento2/issues/16511 by @hiteshagrawal84

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38622` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tykvasergey** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @tykvasergey are you still working on this issue? If not, please unassign yourself. Thanks!

**Comment by tykvasergey** [comment]
Hi, Gabriel da Gama.
I've unsigned. Thanks.

пн, 12 апр. 2021 г. в 19:42, Gabriel da Gama ***@***.***>:

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by kandy** [comment]
Rest API represents "Admin level" API, and should contain only "raw" data. 
If you're looking for a storefront level API, you need to switch GraphQL, as it was designed exactly for such a case

Feel free to close this ticket as it contradicts with technical vision, or leave a comment if you have any objection

**Comment by inovation-inertia** [comment]
Rest API also be a part of Magento . Using GraphQL is not the solution of this Problem . So i request you please do not close this close

**Comment by devconnectpos** [comment]
> Rest API represents "Admin level" API, and should contain only "raw" data. If you're looking for a storefront level API, you need to switch GraphQL, as it was designed exactly for such a case
> 
> Feel free to close this ticket as it contradicts with technical vision, or leave a comment if you have any objection

What an irresponsible comment. REST API also supports guest checkout and customer level API token, why on earth do we need to use GraphQL just to get the most basic functionality works?

**Comment by kandy** [comment]
@devconnectpos Thanks for valuable feedback.  
Probably instead of make comment the better was to point to Magento Web API technical vision https://developer.adobe.com/commerce/php/architecture/technical-vision/web-api/#general  (see first pint)
