### ISSUE TITLE
Login as Customer: Create a Opt-in/ Opt-out system setting

### ISSUE THREAD

**Issue by onepack** [magento/magento2#30599]
### Description (*)

Make Login as Customer Opt-in/ Opt-out available via System Settings.
Option:
Login as Customer is: Opt-in/ Opt-out/ Mandatory

### Expected behavior (*)

This way a shop-owner can choose to:
Opt-in: Let customers decide to have this active. 
Opt-out: Let the Shop owner take control without being stuck when customers cannot find the setting of the setting is not present in an adjusted theme but leave the option for a customer to stop this function.
Mandatory: No setting in the frontend by customers to turn it off.
 
### Benefits

I have some B2B customers that need access to clients accounts to help them out or to check issues with customer prices.
With change https://github.com/magento/magento2/issues/29113 this has become impossible and now they call me to change this in the **database** as customers don't know how to "opt-in". Or the sales person that is new doesn't even know the client has to opt-in and they call me it's not working.
This setting will let shops choose how to implement this feature.

### Additional information

Please don't make this a 3 year battle as I'm now forced to change this in the database directly.

**Comment by engcom-Delta** [comment]
Hi @onepack thank you for your report. You could change customer opt-in (`Allow remote shopping assistance`) from admin panel: Customer edit page->Account Information->Allow remote shopping assistance
![image](https://user-images.githubusercontent.com/51681379/96868375-a01ec680-1476-11eb-9f27-41f31df9a00c.png)
**Result:** 
![Peek 2020-10-22 14-50](https://user-images.githubusercontent.com/51681379/96868313-867d7f00-1476-11eb-81e2-78c719ae9a91.gif)

Is this functionality resolve your issue?

**Comment by onepack** [comment]
Thank you for pointing this out.
I wasn't aware of this bolean.
I will close this issue as it is solved with this answer.
