### ISSUE TITLE
 Cannot type'Korean' in TinyMCE4 WYSIWYG Editor

### ISSUE THREAD

**Issue by uvaper** [magento/magento2#30597]
I have one question. I created a Korean site with magento 2. However, Korean characters cannot be entered where TinyMCE4 WYSIWYG editor is applied.

Please contact us how to solve this problem.

**Comment by engcom-Delta** [comment]
Hi @uvaper thank you for your report. Could you provide additional information with examples and screenshots what you get in result?

**Comment by krishprakash** [comment]
Hi @uvaper 
Feel free to reopen once you update all the proper details.
