### ISSUE TITLE
Somehow csp_whitelist.xml from Magento_Authorizenet ended up in Magento_CatalogUrlRewrite

### ISSUE THREAD

**Issue by nkajic** [magento/magento2#30607]
### Summary (*)
Magento 2.4-develop

Somehow csp_whitelist.xml from Magento_Authorizenet ended up in Magento_CatalogUrlRewrite

csp_whitelist.xml for Magento_Authorizenet was added to app/code/Magento/Authorizenet/etc/csp_whitelist.xml in commit f4db9a422c331902b41a37f413706ec40168f6e9 but somehow ended up in wrong module in 2.4-develop. It is in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/etc/csp_whitelist.xml

### Proposed solution
Delete file app/code/Magento/CatalogUrlRewrite/etc/csp_whitelist.xml since Magento_Authorizenet is not part of magento2 repository since https://docs.magento.com/user-guide/v2.3/payment/authorize-net-direct-post.html

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Hahaha, you're right! 🤦 

It was renamed without any changes in https://github.com/magento/magento2/commit/aec68c609ccc90f1a88e1c9ed55c50fe0ddecaed#diff-95fbf751fab0191251da0f2b611bd868fa0373bdeeb155d40e63c1cbbf95da24 (Authorizenet/etc/csp_whitelist.xml → CatalogUrlRewrite/etc/csp_whitelist.xml)

**Comment by heerdt** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38677` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
PR created: https://github.com/magento/magento2/pull/30640, and I found another incorrect `csp_whitelist.xml` file in the [LoginAsCustomerAdminUi module](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/LoginAsCustomerAdminUi/etc/csp_whitelist.xml).

Thanks for the report @nkajic!

**Comment by nkajic** [comment]
Hi @hostep Thanks to you too. Just make sure that entries from LoginAsCustomerAdminUi module are not needed elsewhere. I found www.paypalobjects.com and t.paypal.com are mentioned in PayPal module so it is ok. But did't find js.braintreegateway.com mentioned anywhere (not even on marketplace module where it was separated from M2 core)
