### ISSUE TITLE
ca domains not working with 'validate-clean-url' 

### ISSUE THREAD

**Issue by Neo-Creo** [magento/magento2#30618]
### Preconditions (*)

1. Magento Commerce 2.3.4 

### Steps to reproduce (*)
1. Validate url using 'validate-clean-url' in an input field
2. Validate value http://www.example.ca in the field

### Expected result (*)
1. The url should be validated successfully

### Actual result (*)
1. We get error "Please enter a valid URL. For example http://www.example.com or www.example.com."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround.

**Comment by Neo-Creo** [comment]
@magento I am working on it.

**Comment by Nazar65** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Duplicate of #30152
