### ISSUE TITLE
No design after installing Magento 2.0.1

### ISSUE THREAD

**Issue by aam1991** [magento/magento2#3061]
Hi,

I installed Magento 2.0.1

but after installing, there is no design and no pictures

Thin is the URL:
http://ph.care.sa/

Could any body help me please

Thanks,

**Comment by mrkhoa99** [comment]
Hello,

You try to run this command line from root folder: <pre>php bin/magento setup:static-content:deploy</pre>
Read more: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html

**Comment by aam1991** [comment]
I did it, But there is nothing fixed.

**Comment by mrkhoa99** [comment]
You can take a screenshot your terminal info after run this command line?
Try to delete folders:
+_var/cache_ 
+_var/page_cache_
+_var/view_preprocessed_
+_pub/static/frontend_
And run my command line again.
Also check permission and ownership: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by aam1991** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16762744/12483920/a82845e8-c068-11e5-8df9-6defc1add5dd.jpg)

You can see the attached screenshot

I did what you told me to do, and there is no change.

**Comment by mrkhoa99** [comment]
Hello,

The last thing I can help:

Step 1. php bin/magento setup:static-content:deploy
Step 2. php bin/magento indexer:reindex
Step 3. make sure Apache "rewrite_module" is enable and then restart the server.
Step 4. delete cache folder under var/cache

http://magento.stackexchange.com/questions/64857/css-and-javascript-files-are-not-loading-after-magento-2-installation
