### ISSUE TITLE
GraphQl public catalog endpoints expose some data that should not be visible

### ISSUE THREAD

**Issue by rogyar** [magento/magento2#30625]
### Preconditions (*)
1. Magento installation with `CatalogGraphQl` module enabled

### Steps to reproduce (*)
Take a look at the [ProductInterface](https://github.com/magento/magento2/blob/8c4de4d793590a4ca5282e4afb986205c7b773b4/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L85)

It allows retrieving some data for the non-authorized users that we usually expose neither on the standard storefront nor with the REST API.  

For example, the following fields
- `special_from_date`
- `special_to_date` 

are not supposed to be visible for a non-authorized client since this data exposes information about sales period that should be hidden by default.

The same about 

- `created_at`
- `updated_at` 
- `websites`
- `attribute_set_id`

### Expected result (*)
1. Only data that is required for rendering product details on the storefront is available

### Actual result (*)
1. Product data that is supposed to be visible for admin only is visible for non-authorized users

### Proposed solution

At least, remove the following fields from the schema

- `special_from_date`
- `special_to_date` 

The other fields mentioned in the issue need to be discussed

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by misha-kotov** [comment]
Agree with these as well: 
* created_at
* updated_at
* websites
* attribute_set_id

But if we remove them, will need to make sure sorting in categories still works (ex: if the category products are sorted by `updated_at` or `created_at`

**Comment by cpartica** [comment]
I can see a case where you have a "promotion" of a price and you want to say until when it's available: "1 day left"
It is true that `created_at`, `updated_at` shouldn't be there
Also `attribute_set_id` if we don't have a use case for it we can remove it.

The problem is that removing fields is backward incompatible and should be approved.
I can create an architectural proposal and try to get these flushed out

**Comment by rogyar** [comment]
@cpartica. Thanks for sharing your thoughts, it makes sense. 
We may add the possibility to see the special_to_date. But my point is GraphQL will be the only way to get this information without authorization. So, for existing stores, it means that if the merchant wants to keep this information publicly hidden (current behavior with the standard storefront) he needs to customize the system behavior. 

As for the architectural proposal, If you could create that, it would be great. Thanks!

**Comment by mauragcyrus** [comment]
@rogyar could you please link the PR?

**Comment by andrewbess** [comment]
@magento I'm working on it
