### ISSUE TITLE
2.0.2 still missing many translation texts

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#3062]
We have translated [Magento 2 to German language](https://connect20.aveo-trade.cz/cat:BuyPackage/details=1/extension=atconnect%2Fmagento-two-language-de-de) but it seems many phrases are still not collected for the translation..

2.0.1 is I assume still the beta release.. right?

Demo of our translations is here: http://mag2-test3.aveo-trade.cz/

Installed this way:

```
git clone -b 2.0.1 https://github.com/magento/magento2
cd magento2
composer update 
composer config repositories.atconnect composer https://connect20.aveo-trade.cz
composer require atconnect/magento-two-language-sk-sk
composer require atconnect/magento-two-language-de-de
composer require atconnect/magento-two-language-tr-tr
cd ..
chown -R root:www-data magento2
find magento2 -type f -print0 | xargs -r0 chmod 640
find magento2 -type d -print0 | xargs -r0 chmod 750
chmod -R g+w magento2/{pub,var}
cd magento2/bin/
chmod 0700 ./setup.sh
./setup.sh
cd ../../
chown -R root:www-data magento2
find magento2 -type f -print0 | xargs -r0 chmod 640
find magento2 -type d -print0 | xargs -r0 chmod 750
chmod -R g+w magento2/{pub,var}
```

Exported phrases using 

```
 php bin/magento i18n:collect-phrases --output="../2.0.1.csv" --magento .
```

Also, if M2 wants to be better than other eshop systems, is there any way how to export custom texts? For example product names, attributes, cms pages, and so on? We would like to provide translation services for eshops, so that for example in EU they may sell their products in every language and increase their revenues.. Now if there is no preddefined way to export the texts nor import the texts for example using composer, it is bad :( Or is there? :)

**Comment by scholtz** [comment]
the same issue applies for 2.0.2

we have full translation of Slovak language for version 2.0.2 including the magento develop branch, and we still see many non translated texts

the main question in this issue is however, do we need to create our custom module to extract texts to be translated (products, static pages) from our clients, or is magento going to make some general way how to translate stuff in clients eshops?

I assume if magento wants the competition advantage against other eshop systems or eshop system providers, there should be some way to translate whole eshop to other language, not just the system texts.

**Comment by davidalger** [comment]
@scholtz It would be great if you could provide some specific examples of texts which the phrase collector is missing, that way someone from the Magento team can attempt to reproduce, and then figure out why the collector is missing it. If it's missing collecting stuff properly passed through the translation system, then it would be a bug, but without details it may be a bit difficult to chase down.

I can't speak to Magento plans for something to a translation oriented export tool, but I'd suggest opening a separate feature request for such a tool mapping out in detail what you'd like to see so the team can review it. For product data though, I'd recommend looking at the existing export/import tools to see if they'll help

**Comment by scholtz** [comment]
@davidalger The examples are in here: [Issue #2630](https://github.com/magento/magento2/issues/2630)

this thread is intended to get the answer from magento team if they plan to make from the feature of translation of content to make the competitive advantage over other eshop systems as their own or not.. but for this they need to make the translation of M2 correct, so it is also reminder for that thread that still many texts are missing the translation.. Here we have the system with full translation of M2.0.0 - 2.0.2 with develop branch installed, and you can see some texts are in english: [https://mag2-test-ce.aveo-trade.cz/](https://mag2-test-ce.aveo-trade.cz/) (not counting the products which is not possible to translate with extract phrases for translation command)

Also note that from that any module you install you can hack magento by adding the php code to any of the language strings - [Issue #3233](https://github.com/magento/magento2/issues/3233) .. And if they cannot fix this as priority it is very bad sign than Magento team is underfinanced/not catching up or has too much work to be done or has too few developers.. :(

**Comment by magento-engcom-team** [comment]
Hi @scholtz 
Thank you for the report. Please try latest Magento release and let us know if you still have an issue. Please reopen the ticket if needed
