### ISSUE TITLE
2.4.1 braintree: Allow to Edit Shipping Address Entered During Checkout on PayPal Side setting missing

### ISSUE THREAD

**Issue by hubertus2017** [magento/magento2#30635]
### Summary of the issue
Admin Setting in braintree module no more available in 2.4.x :
"Allow to Edit Shipping Address Entered During Checkout on PayPal Side"

### Preconditions 
Magento 2.4.1 clean install

### Steps to reproduce 
Go to Stores / configuration / sales / payment options / braintree / configure / PayPal through braintree /

### Expected result 
Existing Setting for:
Allow to Edit Shipping Address Entered During Checkout on PayPal Side
..according documentation M2.4
https://docs.magento.com/user-guide/payment/braintree.html#step-5-complete-the-paypal-through-braintree-settings

(Setting is there for M2.3.5p2)

### Actual result
1. Setting is missing
2. not able to edit address in checkout with PayPal selected (not express checkout)

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Delta** [comment]
Hi @hubertus2017 
According magento 2.4.0 [release notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> The core Braintree module has been removed from the code base. The Braintree Payments module now provides the same feature set. See [Braintree Payments.](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.230236446.342701903.1604300595-820195782.1589897497)

Please refer to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page for further discussion

**Comment by hubertus2017** [comment]
Hello,

i think its a misunderstanding: its the other way round:

From Magento release 2.4:

Quote:
_Before the release of Magento 2.4.0, we recommended that merchants replace the core Magento Braintree integration with the official Braintree extension from Magento Marketplace. **Beginning with Magento 2.4.0, the Braintree extension is included in the release._**

https://docs.magento.com/user-guide/payment/braintree.html

I use the included module….

Please re-opnbe the case.

**Comment by engcom-Delta** [comment]
@hubertus2017 as I see from your comment you have already used Braintree as extension from Magento Marketplace:
> I have:
/vendor/braintree/
/vendor/paypal/module-braintree-core

Braintree module was removed and not present in magento [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento)  code base
All new reports connected with Braintree should be reported to [extension owner](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.230236446.342701903.1604300595-820195782.1589897497) on the Magento Market place page for further discussion

**Comment by hubertus2017** [comment]
ok, but the extension is bundled in magento 2.4 release, so i thought its the right place here.

i will contact the developper

**Comment by hubertus2017** [comment]
After six months now the problem still persists.

Customers fill in their addresses in magento checkout, then check out with PayPal and wonder, why address has changed afterwards. 
The default PayPal address is always overwriting the provided address in the shop. The PayPal address is mostly faulty. People do not see it and we sent out packets to wrong addresses. 
This happens very often. 4-5 wrong addresses per day. Some of them are critical wrong. 

Its the default braintree plugin, bundled with Magento 2.4.x. So i wonder why there is such a "bug" in a standard solution. Can you please provide more information, how to proceed?

After several conversation with braintree plugin developper "gene commerce) they said:
​Regarding the functionality/config option "Allow to Edit Shipping Address Entered During Checkout on PayPal Side", this has still not decided that if this needs to be part of module and included. This is still in queue with some other functionality list so at the moment, there is no ETA to provide

So this is an important issue, leading to many problems, furthermore the magento documantation is faulty at this point.

How to proceed?

**Comment by hubertus2017** [comment]
Hello,
its 20.11.2021 and the problem is still there.

People getting to me saying they put in another shipping address in magento, and after payment the address changed to the address which was the standard address in PayPal.

Am i the only person who has this problem?

**Comment by hubertus2017** [comment]
Hello,

its 24-06-2022
Magento 2.4.4 , same problem with originally bundled gene commerce Braintree...

**Comment by engcom-Charlie** [comment]
Hi @hubertus2017,

This issue of unavailability of the option “Allow to Edit Shipping Address Entered During Checkout on PayPal Side” is related to Braintree extension. 

Apart from that, we can see the documentation mismatch issue here, to address that, I have created new [issue](https://github.com/magento/devdocs/issues/9480) for document updation about the same field in Magento.

Thank you!

**Comment by hubertus2017** [comment]
Hi @engcom-Charlie ,

the feedback from braintree is:

_As I mentioned earlier, that functionality was part of Default Magento's module. Now the GENE Module is being used as Default Module and we don't have that functionality included (Mostly because it was not into a requirement when discussed with Braintree and PaypalTeam). The Magento docs haven't been updated completely and it is still in process._ 

So the problem is that both sides magento and braintree should specify together the way forward in this issue. Its not an issue one of the participants can solve alone.

This feature is often used by customers and this should be discussed for a re-implementation.

Hubertus

**Comment by engcom-Bravo** [comment]
Hi @hubertus2017,

We got reply from PO as described as follows:

1.Most implementations I am seeing of PayPal recently are where
      a.The journey starts on a product page or mini-cart (before address capture for guest)
      b.User selects a paypal button to do an express checkout
      c.address is selected at PayPal from a number of addresses stored there
      d.Customer arrives back at Commerce Order review page (to confirm some things such as shipping method)
-OR- Customer is completing address information first
2..Then customer chooses PayPal at final payment page of Commerce
3.Customer logs in to PayPal
4.Customer is going to see the address sent by Commerce to PayPal
6.Customer cannot change this address here in PayPal but if they want to change it, there is a link to go back to the store to change address in the store.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @hubertus2017,

We are closing this issue since there is no latest update on this.

 Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
