### ISSUE TITLE
Cannot Import Products when Enable Old Media Gallery is set to No

### ISSUE THREAD

**Issue by bernieu2** [magento/magento2#30649]
### Preconditions (*)

1. Magento 2.4.1 CE
2. PHP 7.4

### Steps to reproduce (*)

1. Set Enable Old Media Gallery to "NO" in STORES > CONFIGURATION > SYSTEM > ADVANCED
2. Go to System > Import
3. Import valid CSV of products (no images defined)

### Expected result (*)

1. Products to be validated and imported successfully

### Actual result (*)

1. Validation fails - exception "The file cannot be uploaded".
2. CSV is uploaded to var/importexport
3. Products are not imported
![Screenshot from 2020-10-26 16-20-42](https://user-images.githubusercontent.com/65838389/97136469-50f2d180-17a7-11eb-9286-d916dc87a232.png)

### When Enable Old Media Gallery is set to "YES"
1. Import the same, valid csv product file
2. Products are validated and imported successfully
![Screenshot from 2020-10-26 16-03-09](https://user-images.githubusercontent.com/65838389/97136567-8f888c00-17a7-11eb-975b-00a2db91b11a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by james-noon** [comment]
Just wish to state that I originally had this error and I tried everything to get the file to upload. Nothing worked (as posted here: https://community.magento.com/t5/Magento-2-x-Technical-Issues/M2-4-Product-CSV-Import-Validation-Results-The-file-cannot-be/m-p/460937#M16015 ). 

@bernieu2 found the fix which is posted above. Indeed it **works as stated**, with the **Old Media Gallery -> ON the import works**. With the **Old Media Gallery -> OFF, the import fails**. 

I suppose it makes sense with it being different galleries (but even the sample spits out versions that fail) but better errors would be nice (nothing in the var/logs). This problem had set me back over 20 hours cumulated and with no idea why it was doing it so I could prevent it from keep happening. Ugh.

Thanks @bernieu2 for the find!

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-backlog[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by Nazar65** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38702` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @bernieu2. Thank you for your report. 
The issue has been fixed in magento/magento2#30662 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [72cf701a71628bb8fcd96db69c3d6cf0630295cf](https://github.com/magento/magento2/commit/72cf701a71628bb8fcd96db69c3d6cf0630295cf)
 - [011a443739de7d6dddf64c3c5112da9d04a574e0](https://github.com/magento/magento2/commit/011a443739de7d6dddf64c3c5112da9d04a574e0)
 - [04400b0f1c2672ecac8d152da0f8292276380d0e](https://github.com/magento/magento2/commit/04400b0f1c2672ecac8d152da0f8292276380d0e)

The fix will be available with the upcoming 2.4.2 release.
