### ISSUE TITLE
Invalid login credentials when using magento connect manager

### ISSUE THREAD

**Issue by abdeldayem** [magento/magento2#3064]
I am the admin of my Magento community 1.9.2 I transferred my Magento installation from one Virtual machine to another new one with better performance , now I am trying to connect to the Magento connect Manager however I am always receiving the error message of Invalid login credentials, I deleted all users at the user section, I created a new admin user and tried several times with no luck, still have the same error message

please help and advise how to fix this and connect to the Magento connect manager

regards

**Comment by mazhalai** [comment]
This issues tracker is only for Magento2.  Please post in the relevant place for Magento1

**Comment by abdeldayem** [comment]
I did not find a place for Magento 1.x connect to post that question , can you please help to show me where?

**Comment by mazhalai** [comment]
https://community.magento.com/ (you will need to create an account)

**Comment by abdeldayem** [comment]
Thanks , I already posted there my question and did not get a reply yet, I am trying here in case I might get a faster reply 
ok, Appreciated
