### ISSUE TITLE
Default Product Layout setting is not used anywhere relevant

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#30651]
### Preconditions (*)

Magento 2.3.5

### Steps to reproduce (*)

* In the back-office, change the configuration for General -> Web -> Default Layouts -> Default Product Layout to the layout of your choice.
* In one of the catalog product, set the Layout attribute to _No layout updates_
* Open the product detail page of this product

### Expected result (*)

The page should be displayed using the layout set under General -> Web -> Default Layouts -> Default Product Layout.

### Actual result (*)

It is not.

### Workaround

It should be possible to create a plugin to the product view controller to fix that issue.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ericmorand-at-isobar** [comment]
Actually, the framework is violating the principles of Separation of Concerns once again here, preventing the usage of a plugin to solve the issue:

https://github.com/magento/magento2/issues/30653

**Comment by engcom-Delta** [comment]
Hi @ericmorand , thank you for your report. Value from`General -> Web -> Default Layouts -> Default Product Layout` is applied for new products:
![image](https://user-images.githubusercontent.com/51681379/97212408-0bdf9700-17c9-11eb-9eac-277fd29faf90.png)

To change `Design` configuration for existing products you could use `Update Attributes` mass action:
![image](https://user-images.githubusercontent.com/51681379/97212614-5234f600-17c9-11eb-881e-ae48e4e88046.png)

 If you'd like to update the issue, please reopen it.

**Comment by ericmorand** [comment]
@engcom-Delta , fair enough. Do you know what layout is used if none is selected at the product level or at any of its belonging categories level?
