### ISSUE TITLE
Not able to install magento 2.4.1 in my Macbook Air

### ISSUE THREAD

**Issue by HIMANSHU-281** [magento/magento2#30654]
### Preconditions (*)

1. I am using the Php version of 7.4.11
2. I have used the Below steps for installing Mangeto 2.4.11

a) Install elasticSearch

curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
sudo apt update
sudo apt install elasticsearch

b) Configure elasticSearch

sudo nano /etc/elasticsearch/elasticsearch.yml

# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: localhost

c) Enable Elasticsearch

sudo systemctl start elasticsearch
sudo systemctl enable elasticsearch

d) Test Elasticsearch

curl -X GET 'http://localhost:9200'

############ Step 3 (install magento 2.4.0) ##################

mkdir DIRECTORY_WHERE_YOU_WANT_TO_INSTALL

cd DIRECTORY_WHERE_YOU_WANT_TO_INSTALL

sudo composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.1

sudo php bin/magento setup:install --base-url=http://127.0.0.1/mage2.4/ \
--db-host=localhost --db-name=mage2.4.0 --db-user=root --db-password=root \
--admin-firstname=admin --admin-lastname=admin --admin-email=santosh.patel@ksolves.com \
--admin-user=admin --admin-password=Admin@123 --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine=elasticsearch7 --elasticsearch-host=localhost \
--elasticsearch-port=9200 --backend-frontname=admin

### Steps to reproduce (*)

1. Follow the above steps I have shared
2. I am getting the error on the last step when I am using the command

sudo php bin/magento setup:install --base-url=http://127.0.0.1/mage2.4/ \
--db-host=localhost --db-name=mage2.4.0 --db-user=root --db-password=root \
--admin-firstname=admin --admin-lastname=admin --admin-email=santosh.patel@ksolves.com \
--admin-user=admin --admin-password=Admin@123 --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine=elasticsearch7 --elasticsearch-host=localhost \
--elasticsearch-port=9200 --backend-frontname=admin
 

### Expected result (*)

1. Command should run properly

### Actual result (*)

1.  I am getting this error **too many arguments expected arguments command**

**Comment by nkajic** [comment]
Duplicate of #30620

**Comment by HIMANSHU-281** [comment]
Yes, I have mentioned all the required details

Thanks and Regards,
Himanshu Kanyal
Senior Software Test Engineer
Ksolves - https://www.ksolves.com
Email - himanshu.kanyal@ksolves.com <priyanka.dahiya@ksolves.com>
Contact -8859888885

**Comment by ihor-sviziev** [comment]
Hi @HIMANSHU-281,
Could you run the same command with adding ` -vvv`at the end?

**Comment by andrewbess** [comment]
Hello @HIMANSHU-281 
I see you use the database name with dots.
I don't recommend to use db name with dots.
Please try to change it on `mage2_4_0` or wrap it in quotes.
Also, I don't recommend to use the command `bin/magento` with `sudo`.
Could you please use the command below:
```
php bin/magento setup:install --base-url="http://127.0.0.1/mage2.4/"
--db-host=localhost --db-name="mage2_4_0" --db-user=root --db-password=root --admin-firstname=admin --admin-lastname=admin --admin-email=santosh.patel@ksolves.com --admin-user=admin --admin-password="Admin@123" --language=en_US --currency=USD --timezone="America/Chicago" --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost
--elasticsearch-port=9200 --backend-frontname=admin
```
and write result here?

**Comment by HIMANSHU-281** [comment]
Now getting these errors 

1-In ArgvInput.php line 172:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".   



2-Exception trace:
  at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Input/ArgvInput.php:172
 Symfony\Component\Console\Input\ArgvInput->parseArgument() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Input/ArgvInput.php:83
 Symfony\Component\Console\Input\ArgvInput->parse() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Input/Input.php:55
 Symfony\Component\Console\Input\Input->bind() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Command/Command.php:214
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/magento2.4.1/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /Applications/MAMP/htdocs/magento2.4.1/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/magento2.4.1/bin/magento:23

**Comment by ihor-sviziev** [comment]
Hi @HIMANSHU-281,
If you're just starting to set up your dev. env I would recommend you to use some environment that works in Docker and already supports Mac. For instance https://warden.dev/ (I would recommend this) or https://github.com/magento/magento-cloud-docker

**Comment by HIMANSHU-281** [comment]
I am already running Magento 7.3 version in my  Macbook.
I was just trying to run Magento 7.4 version

**Comment by ihor-sviziev** [comment]
@HIMANSHU-281 what is output of `sudo php -v`

**Comment by HIMANSHU-281** [comment]
PHP 7.4.11

**Comment by ihor-sviziev** [comment]
Hi @HIMANSHU-281,
Could you try to use some domain instead of 127.0.0.1 and add it to the /etc/hosts file, for instance `magento2.test`?

**Comment by ihor-sviziev** [comment]
Hi @HIMANSHU-281,
Let's try to differentiate issue or your environment and not expected changes in the directory. Let's try to start from the clean installation.
Could you try to install magento in the new clean directory and run the setup:install command again? Does it fails with the same result?
