### ISSUE TITLE
Related products of configurables don't change when choosing a variation

### ISSUE THREAD

**Issue by kolaente** [magento/magento2#30659]
### Preconditions (*)

1. Magento CE 2.3
2. php 7.2

### Steps to reproduce (*)

1. Create a configurable product with a simple which has releated products with the simple visibility set to "not visible individually"
2. Go to the product detail page 
3. Choose a variant from the dropdown

### Expected result (*)

1. The related products of the selected simple should show up

### Actual result (*)

1. The related products of the selected simple don't show up.

**Comment by kolaente** [comment]
@magento give me 2.4-develop instance

**Comment by kolaente** [comment]
I can confirm this does not work with the 2.4-dev test instance.

This is what I did:

1. Go to admin
2. Open a simple which belongs to a configurable, I used `WH01-XS-Orange` from the sample data
3. In the "Related Products, Up-Sells, and Cross-Sells" section, choose one or more related products
4. Save the changes
5. Go to the storefront product page of the configurable
6. Select the variant of the product you just edited (In my case "XS" and "Orange")
7. Scroll down to the "Related Products" section
8. Expect to see the products you just set as related for the simple but actually don't see them. In my case I still saw the related products of the "parent" configurable.

**Comment by VZeroCool** [comment]
@magento I am working on this

**Comment by VZeroCool** [comment]
@magento add to contributors team

**Comment by VZeroCool** [comment]
@magento I am working on this

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
> I can confirm this does not work with the 2.4-dev test instance.
> 
> This is what I did:
> 
> 1. Go to admin
> 2. Open a simple which belongs to a configurable, I used `WH01-XS-Orange` from the sample data
> 3. In the "Related Products, Up-Sells, and Cross-Sells" section, choose one or more related products
> 4. Save the changes
> 5. Go to the storefront product page of the configurable
> 6. Select the variant of the product you just edited (In my case "XS" and "Orange")
> 7. Scroll down to the "Related Products" section
> 8. Expect to see the products you just set as related for the simple but actually don't see them. In my case I still saw the related products of the "parent" configurable.

Hello @kolaente,

I have verified this issue per your steps but I think this is a Default Magento feature. When the user opens the configuration product details page It is showing only related, up-sell, and cross-sell products whatever the user selects a simple product or not.
In Simple product details, It's showing own Related products, Up-Sell and Cross-Sell products.

@sdzhepa - Let me confirm this issue. Can you please update me should I set this is an Issue or Feature?

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38827` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
