### ISSUE TITLE
error Customer reorder with unupdated product prices (?)

### ISSUE THREAD

**Issue by JMLucas96** [magento/magento2#30663]
When a customer reorders old order, Magento allows it but with old product prices. Reorder would have to updated prices.
### Preconditions (*)

1. Magento 2.1.8

### Steps to reproduce (*)

1. Buy one product on magento with customer account.
2. Change product price on admin.
3. Reorder previous order 
![image](https://user-images.githubusercontent.com/47561465/97307217-b73b2b00-185f-11eb-9778-18a1424e3ddd.png)

### Expected result (*)

1. Magento allows reorder with the updated product prices.

### Actual result (*)

1. Magento allows reorder but with the old product prices.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @JMLucas96 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Create simple product with Price=100
- Place order with simple product by registered customer
- Change simple product price to 50$
- Go to My Account->My Orders page 
- Click Reorder 

**Result:**
:heavy_check_mark: Order is placed with new product price
![Peek 2020-10-27 22-00](https://user-images.githubusercontent.com/51681379/97356500-06558000-18a1-11eb-8318-51e86c207287.gif)

If you'd like to update the issue, please reopen it.

**Comment by JMLucas96** [comment]
Hi @engcom-Delta thank you to test in Magento 2.4 fresh install, but issue is in magento 2.1.8 and is it possible that I need to update controller with Magento 2.4 version... Can you tell me what file manage reorder functionality?
