### ISSUE TITLE
 Magento won't detect inventory changes made while Product is being edited (VERY IMPORTANT)

### ISSUE THREAD

**Issue by jtalel** [magento/magento2#30677]
### Steps to reproduce (*)

1. Let's say you have a product with 6 units as quantity and you decide to update it's price. So you open the Product in Magento backend to edit it.
2. While you are editing the product let's change using API the Qty for that product. Update Qty to 12. Now this product should have 12 units as qty. (ALL THIS WHILE YOU'RE EDITING THE PRODUCT IN MAGENTO BACKEND MANUALLY)
3. You finish changing the product price and you SAVE AND CLOSE the Product without changing qty.

### Expected result (*)

1. There should be an observer that before let's you Save notices the Qty in database changed and tells you something like "hey while you were editing this product the Qty changed from 6 to 12, do you really want to change it back to 6 units?
2. We need some way to control inventory changes made programatically (or by anoter admin user) and to prevent you to overwrite those changes unknowingly.

### Actual result (*)

1. What actually happen is you unknowinly overwrite the product Qty and change it back to 6 units.
2. In our company We have some processes that work programatically and other process We do them manually in Magento backend and We've notices sometimes (huge coincidence) We have inventory issues due to admin user have opened Product Page for editing while some programatic process runs (API) and this users Saves after the process has already finished erasing all changes.

**Comment by engcom-Bravo** [comment]
@sdzhepa Can you please move this issue to the Feature Request repository?

Thank you

**Comment by jtalel** [comment]
@engcom-Bravo As long as it get's done it's a good thing... but the way it causes inventory inconsistency would be better to work on it as a issue. Don't you think? (We've had twice this problem before I decided to bring it here).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38955` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jtalel** [comment]
I think this is still important. This has not been implemented yet as to what I know.

Is there a way I can follow ticket MC-38955 to see if this is being moving forward? @sivaschenko

**Comment by sivaschenko** [comment]
@jtalel, unfortunately, there is no way to follow the internal ticket progress, except when the internal ticket is resolved or closed - this issue should be closed with appropriate comment by synchronization bot as well.

Considering the current priority of this issue I wouldn't expect it to be resolved soon.

I will add this issue to the agenda of our [public triage meeting](https://opensource.magento.com/community-calendar) to see if we can increase the priority.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
