### ISSUE TITLE
CORS ISSUE - Access to XMLHttpRequest at 'https://d3c34ef131pjj6.cloudfront.net/version1603798838/frontend/Magento/luma/en_US/Magento_Ui/templates/modal/modal-popup.html' from origin 'https://xyz.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ayushwebkul** [magento/magento2#30688]
### Summary (*)

This is my magento2 setup with cloudfront as CDN , Varnish for caching , Nginx for SSL termination , Apache2 as web server for Magento-2.3.5-p2 on AWS ubuntu 18.04 server.
I made a 2 distributions of cloudfront one for static content , one for dynamic content.
Then on browser I am getting the same issue again and again, I have added this header in nginx, apache2 conf:-

**Header set Access-Control-Allow-Origin "*"**
Then on browser I am getting this error on console :-

**_Access to XMLHttpRequest at 'https://d3cjgef131343pjj6.cloudfront.net/version1603798838/frontend/Magento/luma/en_US/Magento_Ui/templates/modal/modal-popup.html' from origin 'https://arabanah.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource_**

Please help.

### Steps to Reproduce
1. Launch and EC2 instance and Install Magento on it 
2. Install & configure Varnish Cache 
3. Install Nginx  for SSL termination, APache2 as webserver.
4. Make 2 Cloudfront distributions , one for static and one for media contents.
5 COnfigure the cloudfront URLS in magento2 admin panel under base, base-secure URLS.
6. Browse the website, you will get the same error.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ayushwebkul** [comment]
> @magento I am working on this

@magento I am working on this

**Comment by gwharton** [comment]
Firstly, do not set Header set Access-Control-Allow-Origin "*" as that opens you up completely.

I use cloudfront and have the following Headers set

- Header set Access-Control-Allow-Origin https://<my main magento domain>
- Header set Access-Control-Allow-Headers "Host, Content-Type, Origin, Accept, X-Requested-With"
- Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"

Then in the Cloudfront Distribution Settings Set the following

- Behaviour -> Allowed HTTP Methods = GET, HEAD, OPTIONS
- Behaviour -> Cached HTTP Methods = OPTIONS enabled
- Behaviour -> Object Caching = Use origin cache headers

You should be good to go

Plus, it costs nothing extra to setup your distribution to use an amazon issued SSL cert on your domain so you could have cdn.xyz.com instead of d3cjgef131343pjj6.cloudfront.net

**Comment by pako-g** [comment]
> Firstly, do not set Header set Access-Control-Allow-Origin "*" as that opens you up completely.
> 
> I use cloudfront and have the following Headers set
> 
> * Header set Access-Control-Allow-Origin `"https://<my main magento domain>"`
> * Header set Access-Control-Allow-Headers "Host, Content-Type, Origin, Accept, X-Requested-With"
> * Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"
> 
> Then in the Cloudfront Distribution Settings Set the following
> 
> * Behaviour -> Allowed HTTP Methods = GET, HEAD, OPTIONS
> * Behaviour -> Cached HTTP Methods = OPTIONS enabled
> * Behaviour -> Object Caching = Use origin cache headers
> 
> You should be good to go
> 
> Plus, it costs nothing extra to setup your distribution to use an amazon issued SSL cert on your domain so you could have cdn.xyz.com instead of d3cjgef131343pjj6.cloudfront.net

if I put in pub/static/.htaccess

`Header set Access-Control-Allow-Origin "https://<my main magento domain>"`

it doesn't work for me.
