### ISSUE TITLE
Is it ok to just move my local magento 2 installation files to hosting server?

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3068]
Hi, I have a dev magento 2 installation on my PC. The store is ready to go live, can I just copy all files and DB to my hosting server, or I need to do something on the host side before/after copying files and db?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by Pakkapao** [comment]
@lgarridoj  http://devdocs.magento.com/guides/v2.0/howdoi/deploy/deploy-to-prod.html
