### ISSUE TITLE
Can't Extend ProductCustomOptionValuesInterface.php and Value.php file.

### ISSUE THREAD

**Issue by hm-harshit** [magento/magento2#30682]
I Have added these two files in my module and update my module di.xml file but nothing comes up!

`Magento\Catalog\Api\Data\ProductCustomOptionValuesInterface`
`Magento\Catalog\Model\Product\Option.php`

Original Path:

`/vendor/magento/module-catalog/Api/Data/ProductCustomOptionValuesInterface.php`
`/vendor/magento/module-catalog/Model/Product/Option/Value.php`

Is there is any way to extent these two file only ?

**Comment by engcom-Delta** [comment]
Hi @harshitmahendra 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
