### ISSUE TITLE
How to fix magento compatibility issue in both version 2.3 & 2.4

### ISSUE THREAD

**Issue by sucharita-ksolves** [magento/magento2#30684]
For modify sales pdf design , I have overwrite pdf model file (module-sales/Model/Order/Pdf/Invoice.php, module-sales/Model/Order/Pdf/Shipment.php ,

As magento 2.3 and 2.4 version __construct function changed, so When I overwrite it will not work both version. How can I fix it ,so it will work in both version with same code.

**Comment by krishprakash** [comment]
Hi @sucharita-ksolves. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by hostep** [comment]
Yeah, [that change](https://github.com/magento/magento2/commit/66d259ed37ac8d7170012e14efb5df12c562cf13#diff-70b66724a68bb5a83ea8270f2504439bb34cbda48a1b145998c06d30e3b0d2b7) was a pretty bad one not done in a backwards compatible way.

We had the same problem with one of our modules after upgrading from Magento 2.3.5 to 2.3.6
We needed the module to be compatible with both 2.3.5 and 2.3.6 so we needed to figure out a solution.

Our solution - and it's probably going to be frowned upon - was to remove the constructor and use the `ObjectManager` directly to instantiate classes we needed.

For example, use something like this to instantiate `SomeClass`:

```php
<?php

...
use Magento\Framework\App\ObjectManager;
use Magento\Sales\Model\Order\Pdf\Invoice as InvoicePdfModel;
...

class Whatever extends InvoicePdfModel
{
    private $someClassInstance;

    private function getSomeClassInstance()
    {
        if ($this->someClassInstance === null) {
            $this->someClassInstance = ObjectManager::getInstance()->get(SomeClass::class);
        }
        
        return $this->someClassInstance;
    }
    ....
}
```
