### ISSUE TITLE
[Reorder feature] Feature very hard to customize

### ISSUE THREAD

**Issue by PierreLeMaguer** [magento/magento2#30686]
### Summary (*)

In magento version 2.4, the feature 'Reorder' changed a lot compared to 2.3. We have a new class app/code/Magento/Sales/Model/Reorder/Reorder.php with only one public method execute. Other methods are private. To customize this feature is very hard, we need to make a preference and copy/paste all methods.

### Examples (*)

One customization possible (that I actually need) is to be able to filter items for reorder. I don't want to reorder all items.

### Proposed solution

There are many possibilities to be more flexible. I'll push a PR for one idea.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
I think you should place proposal to https://github.com/magento/architecture
for wide discuss

**Comment by engcom-Bravo** [comment]
Hi @PierreLeMaguer,

Thanks for the collaboration!
We are using this board to tackle the bugs/issues facing in Magento but it seems that this is something related to a query on functionality. So I request you to please use Magento Stackexchange for these kinds of queries.

We are closing this issue.

Thanks
