### ISSUE TITLE
Magento 2.4.1 Set the website and try again for Magento_InventorySales module

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#30696]
### Preconditions (*)
1. Use Magento 2.4.1
2. Install Magento using CI/CD

### Steps to reproduce (*)

1. Install Magento 2.4.1 using bin/magento setup:install command

### Expected result (*)

1. Magento should be installed

### Actual result (*)

1. Getting the issue "The default website isn't defined. Set the website and try again." when installing "Magento_InventorySales" module
2. On step 4 when database is cleaned up getting :
Cleaning up database...
The default website isn't defined. Set the website and try again. - skipping database cleanup

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @magento2dev thank you for your report. Issue is not reproducible by steps you described.
Could you provide additional information? Is bin/magento setup:install command run for fresh install on empty database?

**Comment by SlowFamily** [comment]
I am experiencing the same issue. 2.4.1 Fresh install on empty database:

Module 'Magento_InventorySales':

In PatchApplier.php line 247:
                                                                                                                                                                                                                                 
  Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: The default website isn't defined. Set the website and try again.

**Comment by SlowFamily** [comment]
Starting from another fresh install via composer, and it did install successfully. Suspect previous error may have occurred  due to an initial issue when creating the project.

**Comment by engcom-Delta** [comment]
@SlowFamily  I rechecked issue and it is not reproducible with magento 2.4.1 fresh install
**Manual testing scenario:**
- Get magento composer version:
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.1 .
```
- Install magento
```
php bin/magento setup:install --base-url=http://magento241.loc/ \
--db-host=localhost --db-name=magento241 --db-user=hidden --db-password="hidden" \
--admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --backend-frontname=admin \
--admin-user=admin --admin-password=123123q --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine elasticsearch7 --elasticsearch-host localhost --elasticsearch-port 9200 \
--elasticsearch-index-prefix magento --elasticsearch-timeout 15
```

**Result:**
:heavy_check_mark: Magento is installed without errors

If you'd like to update the issue, please reopen it.

**Comment by leonhelmus** [comment]
It seems to work if you add the variables, but it doesn't seem to work without even though you have most varaibles setup in env.php and php environment variables.

**Comment by radub** [comment]
I also got this on 2.4.2 - CI/CD install with empty db

```
$ bin/magento se:di:co
Compilation was started.
Plugin list generation... 9/9 [============================] 100% 28 secs 310.0 MiB
Generated code and dependency injection configuration successfully.

In WebsiteRepository.php line 159:

The default website isn't defined. Set the website and try again.
```

**Comment by radub** [comment]
> @SlowFamily I rechecked issue and it is not reproducible with magento 2.4.1 fresh install
> **Manual testing scenario:**
> 
> * Get magento composer version:
> 
> ```
> composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.1 .
> ```
> 
> * Install magento
> 
> ```
> php bin/magento setup:install --base-url=http://magento241.loc/ \
> --db-host=localhost --db-name=magento241 --db-user=hidden --db-password="hidden" \
> --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --backend-frontname=admin \
> --admin-user=admin --admin-password=123123q --language=en_US \
> --currency=USD --timezone=America/Chicago --use-rewrites=1 \
> --search-engine elasticsearch7 --elasticsearch-host localhost --elasticsearch-port 9200 \
> --elasticsearch-index-prefix magento --elasticsearch-timeout 15
> ```
> 
> **Result:**
> ✔️ Magento is installed without errors
> 
> If you'd like to update the issue, please reopen it.

running the setup:install command results in the following:

```
Starting Magento installation:
File permissions check...
[Progress: 1 / 1314]
Required extensions check...
[Progress: 2 / 1314]
Enabling Maintenance Mode...
[Progress: 3 / 1314]
Installing deployment configuration...
[Progress: 4 / 1314]
Installing database schema:

In WebsiteRepository.php line 159:

  The default website isn't defined. Set the website and try again.


setup:install [--backend-frontname BACKEND-FRONTNAME] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--remote-storage-driver REMOTE-STORAGE-DRIVER] [--remote-storage-prefix REMOTE-STORAGE-PREFIX] [--remote-storage-bucket REMOTE-STORAGE-BUCKET] [--remote-storage-region REMOTE-STORAGE-REGION] [--remote-storage-key REMOTE-STORAGE-KEY] [--remote-storage-secret REMOTE-STORAGE-SECRET] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retries SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETRIES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--allow-parallel-generation] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--document-root-is-pub DOCUMENT-ROOT-IS-PUB] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--search-engine SEARCH-ENGINE] [--elasticsearch-host ELASTICSEARCH-HOST] [--elasticsearch-port ELASTICSEARCH-PORT] [--elasticsearch-enable-auth ELASTICSEARCH-ENABLE-AUTH] [--elasticsearch-username ELASTICSEARCH-USERNAME] [--elasticsearch-password ELASTICSEARCH-PASSWORD] [--elasticsearch-index-prefix ELASTICSEARCH-INDEX-PREFIX] [--elasticsearch-timeout ELASTICSEARCH-TIMEOUT] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]
```
