### ISSUE TITLE
Selecting a payment method results in a 400 error

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#30692]
### Preconditions (*)

1. Magento 2.4-develop
2. Checkout terms and agreements enabled in _Stores->Configuration->(Sales)Checkout->Enable Terms and Conditions_
3. At least one manually selected terms and conditions

### Steps to reproduce (*)

1. Logged in user
2. Go to last step of checkout
3. Select any payment method

### Expected result (*)

1. REST call set-payment-information completes successfully

### Actual result (*)

1. REST call set-payment-information results in a 400 error 
![image](https://user-images.githubusercontent.com/51681379/97581187-f18dff00-19fc-11eb-9e70-d26082d27613.png)

The error message reads "The order wasn't placed. First, agree to the terms and conditions, then try placing your order again." and comes from [here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/CheckoutAgreements/Model/Checkout/Plugin/Validation.php#L101)

**Note:** Order successfully could be placed 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by domeglic** [comment]
@magento give me 2.4-develop instance

**Comment by domeglic** [comment]
I can reproduce the issue on the test instance, happens anytime you select a payment method.
![image](https://user-images.githubusercontent.com/8225737/97460902-7b769300-193d-11eb-8183-e7534592e4a8.png)

**Comment by daniel-ifrim** [comment]
They added in:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/SalesRule/view/frontend/web/js/action/select-payment-method-mixin.js

```
$.when(
    setPaymentInformationExtended(
        messageContainer,
          {
              method: paymentMethod.method
          },
          true
        )
).done(
```
Validators for payment step is not executed or not executed correctly.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38791` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
