### ISSUE TITLE
Invoice PDF shows wrong date (magento 2.3.6)

### ISSUE THREAD

**Issue by mvdschot** [magento/magento2#30697]
The Invoice PDF shows a misinterpreted date. Looks like it is trying to parse a wrong format of a date.

### Preconditions (*)

1. Magento version 2.3.6
2. PHP version 7.2 fpm
3. Dutch locale in Magento

### Steps to reproduce (*)

1. Place an order
2. Open order in backend
3. Notice correct date
4. Open the invoice
5. Click on "Print invoice"
6. Notice incorrect date on pdf

### Expected result (*)

1. Correct date on invoice (example 28 oct. 2020)

### Actual result (*)

1. The date on the pdf is "12 apr. 2034"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

![image](https://user-images.githubusercontent.com/13979036/97476977-59860c00-194f-11eb-97bd-db7fb05333cd.png)

**Comment by devchris79** [comment]
Repeat of #26675 that contains a fix.

**Comment by mvdschot** [comment]
@devchris79 This looks as the same issue, thank you.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by sreichel** [comment]
> @devchris79 This looks as the same issue, thank you.

The other issue is also closed. Should this be reopened?
