### ISSUE TITLE
Magento 2.4.1 categories product disappear automatically

### ISSUE THREAD

**Issue by nsventures** [magento/magento2#30698]
I am facing this problem since I update to the latest Magento 2.4.1 I have elastic search running but  categories product disappear automatically and I have to run the reindex command this is happening 5,6 times in a day I have 3500 SKU on my website
it shows WE CAN'T FIND PRODUCTS MATCHING THE SELECTION.
after running reindex command it starts working again for sometime
kindly help

**Comment by mrtuvn** [comment]
Can you provide name any 3rd-party modules, customised modules work with your magento instance
Maybe indexing broken by some reason

**Comment by nsventures** [comment]
yes i have tried with the stock theme but the same problem I am running three sites with the same problem no solution after hours of work

**Comment by mrtuvn** [comment]
With less information will be very hard to find out real problem. Maybe core buy i'm not too sure. Hope you can provide steps for this issue. See var/log for more details can help you little bit

**Comment by nsventures** [comment]
I have found a solution maybe it helps you 

I am running 3 sites in 1 AWS server and elastic search need the prefix for all sites so that I don't confuse with all sites 

here is a quick tip 

go to admin > Catalog > catalog > Catalog Search > Elasticsearch Index Prefix 

fill this column with your site name 
so all three different sites have different names and it works for me

**Comment by mrtuvn** [comment]
Nice for quick fix!. Hope you have a great day

**Comment by mrtuvn** [comment]
Should update docs with correct section for clarify to user

**Comment by williamengbjerg** [comment]
> I have found a solution maybe it helps you 
> 
> I am running 3 sites in 1 AWS server and elastic search need the prefix for all sites so that I don't confuse with all sites 
> 
> here is a quick tip 
> 
> go to admin > Catalog > catalog > Catalog Search > Elasticsearch Index Prefix 
> 
> fill this column with your site name 
> so all three different sites have different names and it works for me

saved my day. 👍🏼
