### ISSUE TITLE
PHP Fatal error:  Uncaught exception 

### ISSUE THREAD

**Issue by Git-Rajkumar** [magento/magento2#3070]
Hi , 
     i try to install magento in ubuntu 14.04 using vagrant , bit i got some error in my apache2  error log

[Thu Jan 21 14:53:41.700490 2016] [:error] [pid 1988] [client 192.168.56.1:36344] PHP Fatal error:  Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /var/www/magento2/var/generation/Magento/Framework/App/ResourceConnection/.' in /var/www/magento2/lib/internal/Magento/Framework/Code/Generator.php:103\nStack trace:\n#0 /var/www/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\Framewo...')\n#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\Framewo...')\n#2 [internal function]: spl_autoload_call('Magento\Framewo...')\n#3 /var/www/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\Framewo...')\n#4 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Framewo...')\n#5 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectMa in /var/www/magento2/lib/internal/Magento/Framework/Code/Generator.php on line 103

What i miss in this installation process , thank you in advance

**Comment by mazhalai** [comment]
@Git-Rajkumar you need to give [correct permissions](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html) to the var directory. Closing since this is not a bug.

**Comment by Git-Rajkumar** [comment]
@mazhalai   thanks for your reply, yes its works for me..

**Comment by RijaCloud** [comment]
Hello, I am facing the same issues, even by giving the correct permissions, it still return the same problem.
I am using nginx on cento7.
Thanks
