### ISSUE TITLE
On Customer Email Confirmation, Message incorrectly shows set address link in plain text

### ISSUE THREAD

**Issue by ghost** [magento/magento2#30709]
### Preconditions (*)
1. Magento 2.3.6

### Steps to reproduce (*)
1. Go to Stores > Configuration > Customers > Customer Configuration > Create New account Options
2. Set **Enable Automatic Assignment to Customer Group** to **Yes**
3. Set **Require Emails Confirmation** to **Yes**
4. Go to the frontend and create a customer account
5. After receiving the email to verify your email address, you'll be directed to the website with a message to assign your address with a link.

### Expected result (*)
Customer sees a message with the link correctly formatted
![Message Formatted Correctly](https://i.imgur.com/BQlihyL.png)

### Actual result (*)
Customer sees a message with the raw html of a link in a message instead.
![Message Formatted Incorrectly](https://i.imgur.com/5NOhgnO.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmcnamaracpc** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hello @pmcnamaracpc 

Thank you for your report

This issue is already fixed in 2.4-develop
Please see the attachment
![var](https://user-images.githubusercontent.com/51680745/97690732-0ecad800-1aa6-11eb-944e-675d45634814.png)

So we have to close this issue. Please feel free to comment, create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by pmcnamaracpc** [comment]
Thanks @engcom-Bravo

**Comment by pmcnamaracpc** [comment]
For the sake of completeness, I also did not have this issue on 2.4.0, so looks good on all of 2.4.X.
