### ISSUE TITLE
Shipment mail not get tracking and order details magento 2.3.4

### ISSUE THREAD

**Issue by NTK-2016** [magento/magento2#30702]
Hi ,
I have an issue with shipment_new.html sending content . It is not able to wrap shiping and order grid also tracking details is missing 2.3.4 community edition,
here it is mail content
![image](https://user-images.githubusercontent.com/24722367/97545293-cc938f00-19f0-11eb-8c91-1cefbbf40197.png)

**Comment by milindsingh** [comment]
@magento give me 2.3.6-develop instance

**Comment by NTK-2016** [comment]
Hi @milindsingh ,thanks for working

**Comment by NTK-2016** [comment]
Hi @milindsingh  any updates

**Comment by NTK-2016** [comment]
Any update please

**Comment by NTK-2016** [comment]
please any update

**Comment by NTK-2016** [comment]
Hello , please look into issue
