### ISSUE TITLE
Reset password showing expired

### ISSUE THREAD

**Issue by shravanpathipaka** [magento/magento2#30701]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. goto www.sakdevsite.com/en and create an account
2. and then logout and try to click on forgot password then you will receive an email and then click on reset password in email and you will see an error called your link has expired.

### Expected result (*)

1. it should show form to enter password and confirm password
2.

### Actual re
![expired](https://user-images.githubusercontent.com/57125351/97528287-5a608180-19d3-11eb-8ae9-693df54798ea.PNG)
sult (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shravanpathipaka** [comment]
i think enough information has already given to reproduce and check the issue

**Comment by engcom-Delta** [comment]
Hi @shravanpathipaka thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Form `Set a New Password` is shown without error about expiration
![image](https://user-images.githubusercontent.com/51681379/100792093-cb57e680-3422-11eb-85ea-52c1aea89360.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.
