### ISSUE TITLE
Amazon Login message on reset password form is always displays

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#30704]
### Preconditions (*)

Magento 2.4.1
:warning: **Note:** Issue is **not** reproducible on 2.4-develop

### Steps to reproduce (*)

1. Ensure that Amazon Pay and Login With Amazon are disabled:

![image](https://user-images.githubusercontent.com/125664/97555635-a530c800-19d8-11eb-9e7f-9d377c4b7402.png)

2. Log in as 
3. In your account dashboard, choose to change your password

### Expected result (*)

Since Amazon Pay and Amazon Login are disabled, the Amazon Login message is not displayed.

### Actual result (*)

It is:

![image](https://user-images.githubusercontent.com/125664/97555845-ed4fea80-19d8-11eb-9ec2-d097fc6aa633.png)

There is not workaround here for merchants. If Amazon Payment is installed on their Magento 2 implementation, they can't get rid of that message even if they don't want to propose Amazon Login.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38808` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
