### ISSUE TITLE
setup:di:compile tries to delete var/cache completely, not just contents

### ISSUE THREAD

**Issue by stathis** [magento/magento2#30708]
We have the ```var/cache``` directory mounted as tmpfs in order to increase site performance in addition to using Varnish and/or Redis.
When compiling the binary should delete contents if removing the directory is not possible, as attempting to delete the whole directory is a hacky way to do it anyway.

### Preconditions (*)
1. Have ```var/cache``` mounted as tmpfs. _**or**_
2. Have it symlinked to a ```/dev/shm``` subdir

### Steps to reproduce (*)
```bin/magento setup:di:compile```

### Expected result (*)
For the command to run successfully, deleting ONLY the contents of ```var/cache/*``` , not the directory itself.

### Actual result (*)
1. For the first case:
```
In Write.php line 200:
                                                                                                                                     
  The directory "/home/magento/www/var/cache/" cannot be deleted Warning!rmdir(/home/magento/www/var/cache/): Device or resource busy  
```

2. For the second case:
It completely removes the symlink.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@stathis feed free to create a Pull Request that fixing this issue.
