### ISSUE TITLE
FAILED Download via Composer

### ISSUE THREAD

**Issue by antenhkibret** [magento/magento2#30710]
Executed this command to download via Composer

`composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento2`

And got this error message. 

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires magento/composer-root-update-plugin ~1.0 -> satisfiable by magento/composer-root-update-plugin[1.0.0].
>     - magento/composer-root-update-plugin 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
>   Problem 2
>     - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
>     - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
>   Problem 3
>     - laminas/laminas-dependency-plugin[1.0.0, ..., 1.0.4] require composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
>     - magento/product-community-edition 2.4.1 requires laminas/laminas-dependency-plugin ^1.0 -> satisfiable by laminas/laminas-dependency-plugin[1.0.0, ..., 1.0.4].
>     - Root composer.json requires magento/product-community-edition 2.4.1 -> satisfiable by magento/product-community-edition[2.4.1].
> 
> You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by hostep** [comment]
Hi @FalconOne 

Unfortunately Magento 2 isn't compatible yet with Composer version 2.
You can downgrade composer to version 1 using for example `composer selfupdate --1` and then you should be able to install Magento.

You can follow https://github.com/magento/community-features/issues/302 to see when Magento will become compatible with composer version 2
