### ISSUE TITLE
Fatal error: Class 'Cm_Cache_Backend_File' not found

### ISSUE THREAD

**Issue by vadariyanikunj** [magento/magento2#3071]
i upgrade 2.0.0 to 2.0.1 and try to run bin/magento setup:upgrade then showing below error.

Fatal error: Class 'Cm_Cache_Backend_File' not found in /opt/lampp/htdocs/magento/magento2test/vendor/magento/zendframework1/library/Zend/Cache.php on line 153

Anyone have idea then let me know.

**Comment by mazhalai** [comment]
@vadariyanikunj can you please give us steps followed to upgrade? Also, how did you deploy magento initially?

**Comment by mazhalai** [comment]
@vadariyanikunj this error occurred and it was found that var directory had incorrect permissions. Please check permissions and verify it is working fine now.

**Comment by davidalger** [comment]
Closing due to lack of reply from OP

**Comment by bentideswell** [comment]
I know this is closed but I have just had this problem and found the issue so figured I would post it here for people searching in the future.

After updating my fork with the latest changes from the develop branch, I had this exact error. To fix, I ran the following in terminal:

```
composer install
bin/magento setup:upgrade
```

**Comment by anherrera** [comment]
@bentideswell Thank you so much! That worked for me.
