### ISSUE TITLE
Cart Price Rules by Payment Method

### ISSUE THREAD

**Issue by DavaGordon** [magento/magento2#30712]
### Preconditions (*)

1. 2.4.0
2. 2.4.1

### Steps to reproduce (*)

1. Admin > Marketing > Promotions > Cart Price Rules
2. Add New > Fill out general Information > Select Conditions
3. Match Conditions
<img src="https://i.ibb.co/LQ0k0gz/Screenshot-2020-10-29-at-17-14-48.png" alt="Screenshot-2020-10-29-at-17-14-48" border="0">
4. Set 10% discount product price discount.

### Expected result (*)

1. On the checkout if the payment method klarna is selected then 10%, should be discounted

### Actual result (*)

1. When selecting klarna the discount is not applied

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
The reported issue is reproducible on Magento 2.4.1

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39331` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SmVladyslav** [comment]
@magento I am working on this.
