### ISSUE TITLE
Admin Dashboard blank page.

### ISSUE THREAD

**Issue by dumidesign** [magento/magento2#3072]
I'm getting a blank page after logged to admin panel.
I have an Windows 8.1 system with PHP 5.6.17, MySQL 5.6
But in M2CE admin panel working fine. this is only happen in M2EE.

![image1](https://cloud.githubusercontent.com/assets/1157326/12505375/60ab7830-c10c-11e5-9859-f856cffdf70d.jpg)
![image2](https://cloud.githubusercontent.com/assets/1157326/12505376/626fea66-c10c-11e5-80f5-b5409a86bc5d.jpg)

**Comment by dumidesign** [comment]
But in M2CE admin panel working fine. only this happen in EE.

**Comment by mazhalai** [comment]
@dumidesign Please do not post EE related issues on github. Please report it via partner portal.
