### ISSUE TITLE
Customer Account Edit controller action enforces Page Title to "Account Information"

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#30724]
### Preconditions (*)

Magento 2.3.5

### Steps to reproduce (*)

Change the page title in `view/frontend/layout/customer_account_edit.xml` file of a module.

### Expected result (*)

The page title set in the layout file is used as the browser page title.

### Actual result (*)

It is not. "Account Information" is always used as page title, whatever the setting of the layout.

This is coming from the `Magento\Customer\Controller\Account\Edit` controller action that enforces this value. There seems to be no workaround here. Except rewriting the whole action in a custom implementation.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39563` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ericmorand. Thank you for your report. 
The issue has been fixed in magento/magento2#31157 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [92e94220d329065708e1e97fe038f5aa2fb022c5](https://github.com/magento/magento2/commit/92e94220d329065708e1e97fe038f5aa2fb022c5)

The fix will be available with the upcoming 2.4.3 release.
