### ISSUE TITLE
Cant open category : Notice: Undefined index: price in vendor/magento/module-visual-merchandiser/Block/Adminhtml/Category/Merchandiser/Tile.php on line 322

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30725]
I tried to open a category, and I got this error:

> Notice: Undefined index: price in /home/company/company.de/vendor/magento/module-visual-merchandiser/Block/Adminhtml/Category/Merchandiser/Tile.php on line 323
> Exception in /home/company/company.de/vendor/magento/framework/App/ErrorHandler.php:61

I added this code to the method **getAttributesToDisplay** in **vendor/magento/module-visual-merchandiser/Block/Adminhtml/Category/Merchandiser/Tile.php** to fix the error:

    public function getAttributesToDisplay($product)
    {
        $attributeCodes = $this->getUsableAttributes();
        $availableAttributes = $product->getTypeInstance()->getSetAttributes($product);
        $availableFields = array_keys($product->getData());
        $filteredAttributes = [];

        foreach ($attributeCodes as $code) {
            $renderer = $this->attributeFactory->create($code);

            if ($code == 'price') {
                if (empty($availableAttributes[$code])) { continue; }       // <------- Added this line to fix it
                $attributeObject = $availableAttributes[$code];
                $filteredAttributes[] = $renderer->addData(
                    [
                        'label' => $attributeObject->getFrontend()->getLabel(),
                        'value' => $this->priceCurrency->format($product->getPrice())
                    ]
                );

This is the category:

![image](https://user-images.githubusercontent.com/16349349/97711087-e9959400-1abc-11eb-8b28-afd3db0115aa.png)

### Preconditions (*)
- 2.4

### Steps to reproduce (*)
- Not sure

### Expected result (*)
- Should load category

### Actual result (*)
- Does not load category

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone thank you for your report, issue is not reproducible by provided steps on EE 2.4-develop.
![image](https://user-images.githubusercontent.com/51681379/98208721-71105680-1f46-11eb-8599-beb591f415d6.png)

Please update issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines), add steps and details that helps to reproduce this issue

**Comment by Eddcapone** [comment]
As I said, I dont know how to reproduce it. I just report the bug that happend and showed my solution.

**Comment by engcom-Delta** [comment]
@Eddcapone I close issue as **Cannot Reproduce**

Please feel free to comment, reopen or create new ticket with additional steps according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by Eddcapone** [comment]
I am still facing the bug in 2.4.2
