### ISSUE TITLE
Server Error 500 on System -> Web Setup Wizard

### ISSUE THREAD

**Issue by simkea** [magento/magento2#3073]
Env: Debian Jessie, Apache, PHP 5.6.14
Magento CE 2.0.0 installed with GIT and composer. Frontend and Backend runs perfekt!

If i go into Web Setup Wizard i get this Error

[Fri Jan 22 09:10:38.351133 2016] [:error] [pid 1919] [client 94.79.145.147:59556] PHP Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php on line 132' in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61\nStack trace:\n#0 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/kaphin...', 132, Array)\n#1 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(84): Magento\Framework\ObjectManager\Config\Compiled->extend(Array)\n#2 /var/www/kaphingst/mage2-shop/magento2/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\ObjectManager\ObjectManager->configure(Array)\n#3 /var/www/kaphingst/mage2-shop/magento2/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): Magento\Setup\Model\ObjectManagerProvider->get()\n# in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php on line 61

**Comment by mazhalai** [comment]
@simkea Please clean your var folder and browser cache+local data and try again.

**Comment by simkea** [comment]
Sorry, but i clean complete var and my local cache. i get always the same error from apache/php

``````
PHP Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php on line 132' in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php(132):
Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined index...', '/var/www/kaphin...', 132, Array)
#1 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(84): 
Magento\\Framework\\ObjectManager\\Config\\Compiled->extend(Array)
#2 /var/www/kaphingst/mage2-shop/magento2/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): 
Magento\\Framework\\ObjectManager\\ObjectManager->configure(Array)
#3 /var/www/kaphingst/mage2-shop/magento2/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): 
Magento\\Setup\\Model\\ObjectManagerProvider->get()\n# in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php on line 61, referer: [...]```
``````

**Comment by simkea** [comment]
Okay... i removed my custom module and re-compile etc...
now i get another Error

```
PHP Fatal error: Uncaught exception 'Exception' with message 'Recoverable Error: Argument 1 passed to Magento\\Framework\\App\\State::__construct() must implement interface Magento\\Framework\\Config\\ScopeInterface, instance of Magento\\Framework\\ObjectManager\\ObjectManager given, called in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/State.php on line 76' in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/State.php(76): 
Magento\\Framework\\App\\ErrorHandler->handler(4096, 'Argument 1 pass...', '/var/www/kaphin...', 76, Array)
#1 /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(97): Magento\\Framework\\App\\State->__construct(Object(Magento\\Framework\\ObjectManager\\ObjectManager) in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php on line 61
```

**Comment by simkea** [comment]
When I call the address http://DOMAIN/setup/, then I get this error message in addition

```
PHP Warning: ltrim() expects parameter 1 to be string, object given in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php on line 152, referer: http://DOMAIN/setup/
PHP Notice: Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/Autoload/ClassLoaderWrapper.php on line 81, referer: http://DOMAIN/setup/
PHP Notice: Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/vendor/composer/ClassLoader.php on line 317, referer: http://DOMAIN/setup/
PHP Notice: Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/vendor/composer/ClassLoader.php on line 349, referer: http://DOMAIN/setup/
```

**Comment by simkea** [comment]
[solved] Okay... i clean ./var/ and runs NOT more re-compile and now i can access without error.

BUT why? 
If I'm doing this, I always get the error afterwards:

sudo -u www-data bin/magento setup:upgrade
sudo -u www-data bin/magento setup:di:compile
sudo -u www-data bin/magento setup:static-content:deploy

**Comment by mazhalai** [comment]
@simkea are you on developer mode or production mode?

**Comment by simkea** [comment]
this is the line in .htaccess:

```
#   SetEnv MAGE_MODE developer
```

i believe the production mode...

**Comment by mazhalai** [comment]
Just so that I understand the steps, you got Magento2 from git, ran `composer install` and navigated to domain/setup and got an error? After you cleaned `var` directory the error went away? But after running upgrade, compile, and static-content it reappears? 
Also, do you have any custom module?

**Comment by simkea** [comment]
1. Yes i have pulled the develop branch
2. i used composer install & composer upgrade etc
3. i used the "Setup Wizard" for main installation process ... 
4. Magento 2 runs perfect.
5. Now i have to install an own Module (Copy-Methode to /app/code/...) and add in config.xml the correct line   'Kaphingst_TestModul' => 1,
6. now i run my shell-script:

```
#!/bin/bash
############################################################################################################$

T_VERSION=mage2
T_STARTFOLDER=/var/www/kaphingst
T_RELPATH=${T_VERSION}-shop/magento2

############################################################################################################$

function setPermission
{
echo "CHANGE permissions"
find ${T_STARTFOLDER}/${T_RELPATH} -type d -exec chmod 770 {} \;
find ${T_STARTFOLDER}/${T_RELPATH} -type f -exec chmod 660 {} \;
chmod u+x ${T_STARTFOLDER}/${T_RELPATH}/bin/magento

chown -R www-data.www-data ${T_STARTFOLDER}/${T_RELPATH}/

chmod 777 ${T_STARTFOLDER}/${T_RELPATH}/var
chmod -R 777 ${T_STARTFOLDER}/${T_RELPATH}/pub/media
chmod -R 777 ${T_STARTFOLDER}/${T_RELPATH}/pub/static
chmod 777 ${T_STARTFOLDER}/${T_RELPATH}/app/etc

chmod +x ${T_STARTFOLDER}/${T_RELPATH}/*.sh
chown root.root ${T_STARTFOLDER}/${T_RELPATH}/*.sh
}

function startCleaning
{
echo "Cleaning"
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/view_preprocessed/
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/pub/static/adminhtml
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/page_cache
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/generation
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/di
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/cache
rm -rf ${T_STARTFOLDER}/${T_RELPATH}/var/*
}

startCleaning
setPermission

echo "re-compile"

sudo -u www-data ${T_STARTFOLDER}/${T_RELPATH}/bin/magento setup:upgrade
sudo -u www-data ${T_STARTFOLDER}/${T_RELPATH}/bin/magento setup:di:compile
sudo -u www-data ${T_STARTFOLDER}/${T_RELPATH}/bin/magento setup:static-content:deploy

echo "READY"
exit
```
1. my module is correct in the magento 2 enabled
2. if i go to setup wizard i get the error in logs: see above
3. now i clean the /var/ complete with: rm -rf \*     result: no error !
4. It doesn't matter which mode. i tryed both -> develop and production 

I have it tested now without my module, i get the same Problem! This is reproducable. i hope this helps.

**Comment by mazhalai** [comment]
I would check your custom module. Somehow some code from your custom module is not being compiled properly. Can you try a bare minimum module with only `module.xml` and `registration.php`?

Also, after you enable your module, why do you need to go to setup again? you have already installed, magento.

**Comment by simkea** [comment]
i have the same problem without my module (complete removed). 
I do not think that my module is the cause of the problem. 
I need the Setup not, but this is a regulare Menuitem in Backend to System upgrade or like somethink.
I think it is not right that there an error occurs, if you want to get in there.

**Comment by mazhalai** [comment]
So without your module, if you run install and then frontend and backend load fine? but if you run compile it breaks?

**Comment by simkea** [comment]
That's right! Without my module! But not when I compile, but then when I want to open /setup/. -> Server Error 500 - 
PHP Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/ObjectManager/Config/Compiled.php on line 133' in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61

###### So, and if I now clean /var/ then the error is gone again.  ?!*~ oO

**Comment by simkea** [comment]
If you are interested, here is my test modules. I need the whole re-compile process because I use a backend CSS file.
https://gitlab.com/kaphinst-developer/mage2_Kaphingst_TestModul

**Comment by simkea** [comment]
You have probably at all times and constantly clean the directory /var/. After each action with the Magento tool.  
That's too immature for me personally. :( thx

**Comment by aeldar** [comment]
I have the same problem. Clean magento installed from composer, without 3d-party modules. Thanks simkea for found workaround solution.

**Comment by jpreed2** [comment]
I have the same problem.  Specifically I need to remove the var/di directory after a compile or I get the described NOTICE.

**Comment by dziurawy** [comment]
same problem here..

**Comment by mazhalai** [comment]
@aeldar @jim5359 @dziurawy Please do not post on closed issues. Create a new one!
