### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by websuits** [magento/magento2#30743]
Download Magento 2.4.1 fresh server

Run :

bin/magento help setup:install

Result:

PHP Parse error:  syntax error, unexpected ')' in :

https://github.com/magento/magento2/blob/226b08d0f51c3f6aef7ea969435be2ca07f4b9f6/setup/src/Magento/Setup/Module.php#L81

Fix :

Remove end comma in line 81

**Comment by ihor-sviziev** [comment]
Hi @websuits,
Duplicates https://github.com/magento/magento2/issues/30604.

This issue appears in case if you're using too old php version.
Please check your php version, the minimum php version is 7.3 for Magento 2.4.x.
You can do that with running command `php -v`.

Unfortunately we had incorrect minimum php version check in magento that allows to run Magento on older php version, already fixed it in #29993

I'm closing this issue as not relevant.
