### ISSUE TITLE
Region field visible for Country when "Allow to Choose State if It is Optional for Country" is disabled

### ISSUE THREAD

**Issue by mweiss-quotient** [magento/magento2#30747]
### Preconditions (*)
1. Magento 2.4.1 and 2.4-develop
1. PHP 7.4

### Steps to reproduce (*)
1. In General Settings configure **Default Country** that doesn't support States (eg. Czech Republic)
1. In General Settings configure **Allowed countries** same as Default Country
1. Make sure that your Default Country isn't selected in **State is Required for** field
1. In General Settings configure **Allow to Choose State if It is Optional for Country* to *NO**
1. Navigate to storefront as a guest and add product to cart.
1. Go to Checkout page.

### Expected result (*)
1. Default Country is automatically selected in shipping address form and region field is hidden.

### Actual result (*)
1. Default Country is automatically selected in shipping address form but region input field is visible.

### Additional info from Engcom
According to the [documentation](https://docs.magento.com/user-guide/stores/state-options.html), when *Allow to Choose State if It is Optional for Country* is set to **No** - In countries where the state field is not required, omits the State field.

1. In General Settings set country that doesn't support States for Default Country and Allowed countries settings (eg. Czech Republic)
![Default and allow](https://user-images.githubusercontent.com/51680745/97873309-1f868280-1d20-11eb-9d6f-65f1f9951dfb.png)
1. Make sure that your Default Country isn't selected in State is Required for field
![state as required](https://user-images.githubusercontent.com/51680745/97873401-3e851480-1d20-11eb-94e4-7fa92ceead07.png)
1. In General Settings set Allow to Choose State if It is Optional for Country to NO
![Allow to choose](https://user-images.githubusercontent.com/51680745/97873836-d5ea6780-1d20-11eb-9c25-db6fcaaef2ea.png)
1. Navigate to storefront as a guest and add product to cart.
1. Go to Checkout page.

**Actual result**
Default Country is automatically selected in shipping address form but region input field is visible.
![Store](https://user-images.githubusercontent.com/51680745/97873983-06ca9c80-1d21-11eb-9e5e-0fcae46b1b39.png)

**Comment by mweiss-quotient** [comment]
I have hot-fixed this issue by adding following method to app/code/Magento/Ui/view/base/web/js/form/element/region.js:
```
filter: function (value, field) {
            var superFn = this._super;
            superFn.call(this, value, field);
            
            var option = _.isObject(this.countryOptions) && this.countryOptions[value];

            if (option && option['is_region_visible'] === false) {
                // hide select and corresponding text input field if region must not be shown for selected country
                this.setVisible(false);

                if (this.customEntry) {// eslint-disable-line max-depth
                    this.toggleInput(false);
                }
            }
}
```

Similar method was present in region.js in Magento 2.3.5-p2:
https://github.com/magento/magento2/blob/2.3.5-p2/app/code/Magento/Ui/view/base/web/js/form/element/region.js#L80

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38833` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
