### ISSUE TITLE
Different product URL when requested via crontab

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3074]
Having standard Magento2 setup `$product->getProductUrl()` return different values when called from admin and crontab.

Example:
from admin - `http://magento.dev/joust-duffle-bag.html`
via crontab - `http://magento.dev/catalog/product/view/id/1/`

The same applies for `$product->getUrlInStore()`.

Is this expected behaviour? I highly doubt it but if so - how to get the same URL via crontab?

**Comment by mazhalai** [comment]
@werdlv we have created ticket MAGETWO-48255 to investigate.

**Comment by oserediuk** [comment]
@werdlv Hi! This is known issue which cannot be resolved in backward-compatible way. We created task for it: MAGETWO-53478

As for you problem here is workaround how you can get url by using \Magento\UrlRewrite\Model\UrlFinderInterface:

```
        $rewrite = $this->urlFinder->findOneByData([
            UrlRewrite::ENTITY_ID => 1,
            UrlRewrite::ENTITY_TYPE => \Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator::ENTITY_TYPE,
            UrlRewrite::STORE_ID => 1
        ]);
```
