### ISSUE TITLE
/rest/default/V1/guest-carts/{cartId}/totals-information 404

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#30758]
### Steps to reprduce

1. Visitor add a product to cart.
2. Go to Cart Page.
3. Click on Proceed to Checkout
4. Login Pop-up will prompt to login.
5. When try to login it shows alert box with error "No such entity with %fieldName = %fieldValue"
in console : 
message : "No such entity with %fieldName = %fieldValue"
parameters : Object {fieldName: "cartId", fieldValue: null}

6. However we successfully logged into website but prior login show the above error and in console shows 404 error. 

Note: Guest Checkout is disabled in our site.

**Screen shot :** https://paste.pics/06331a59abb4cd738e1b4fe85877a511

### Expected Result
When visitor is going to logged then then alert box and its error should not appear.

### Actual Result 
When visitor try to login in,he gets error in alert box and then logged successfully.

**Comment by engcom-Delta** [comment]
Hi @thinksys-dev  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop with Allow Guest Checkout=No
![Peek 2020-11-05 22-43](https://user-images.githubusercontent.com/51681379/98294456-a81f5000-1fb8-11eb-8c3b-f80bdcb46a41.gif)

If you'd like to update the issue, please reopen it.

**Comment by harrigo** [comment]
Yeah i have this, nothing seems to be wrong can login, checkout however I get that little warning popup and also the exact JS error in my console. I'm on Magento 2.3.5, did you manage to solve or find out any more about what is causing this?

**Comment by thinksys-dev** [comment]
@harrigo Yes i solved this. 
Solution :
I created a patch for the model file : /vendor/magento/module-checkout/Model/GuestTotalsInformationManagement.php
code : 
`public function calculate(
        $cartId,
        \Magento\Checkout\Api\Data\TotalsInformationInterface $addressInformation
    ) {
        /** @var $quoteIdMask \Magento\Quote\Model\QuoteIdMask */
        $quoteIdMask = $this->quoteIdMaskFactory->create()->load($cartId, 'masked_id');
        if($quoteIdMask->getQuoteId()){
            return $this->totalsInformationManagement->calculate(
                $quoteIdMask->getQuoteId(),
                $addressInformation
            );
        }
    }`
I put "$quoteIdMask->getQuoteId()" this check in if condition that fixed the issue. By doing this it stops the further check which cause error prompt on site. Hope this will help.

**Comment by harrigo** [comment]
Oh awesome will make a patch tomorow and see if it works! This one has
confused me for a few days.

**Comment by vishwanathkharabe** [comment]
Hi 
I am also facing this issue on Magento 2.4.0-p1.
Getting error on login "No Such Entity with cartId = null"

**Comment by Januszpl** [comment]
@magento give me 2.4-develop instance

**Comment by Januszpl** [comment]
@harrigo and @thinksys-dev the issue related to this error in login popup was related fixed here:

https://github.com/magento/magento2/commit/55172bfd643757335ddc79723527ee4f20a3b449#diff-eb75768377727a571a5861f7385ed31d37a8eb632def30bfb9bd9a02f4486508

I had the same issues in "magento/product-enterprise-edition": "2.3.7-p2" but fix from above PR fixes this issue.
