### ISSUE TITLE
Magento 2.4.0 and 2.4.1 Security Tab system configuration label issue

### ISSUE THREAD

**Issue by sanjay-magecomp** [magento/magento2#30750]
### Preconditions (*)
Magento Version 2.4.0 and 2.4.1

### Steps to reproduce (*)
Follow Below Step To Produce Issue
1. Login To Magento Admin Panel
2. Go to  System -> Configurations
3. Next Expand Security Tab

### Expected result (*)
1. https://i.imgur.com/UQQa1y2.png
2. Lable should be Security.

### Actual result (*)
1. https://i.imgur.com/3aMpNfI.png
2. but  actual result shows security.txt

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
@sanjay-magecomp @engcom-Bravo

It is not a bug or typo. Its module "Securitytxt" 
please see for more details:
- https://github.com/magento/security-package/tree/1.0-develop/Securitytxt
- https://devdocs.magento.com/guides/v2.4/security/security-txt.html
