### ISSUE TITLE
/rest/default/V1/carts/mine/shipping-information 404

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#30757]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @thinksys-dev thank you for your report. Please update ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines), add additional steps, screenshots that helps to reproduce issue

**Comment by thinksys-dev** [comment]
HI Team,
I have updated the suggested guidelines on Ticket. Please have a look.

**Comment by krishprakash** [comment]
Hi @thinksys-dev. Ticket is not updated 
Feel free to reopen once you update all the details 
Thanks!!
