### ISSUE TITLE
Magento_Authorization model Rules/Role calling a resource model function update, that is not exist in resource model(Rules/Role)  

### ISSUE THREAD

**Issue by narendrarwt** [magento/magento2#30756]
### Preconditions (*)

Magento 2.4-develop

### Steps to reproduce (*)

Call `Magento\Authorization\Model\Rules::update` or `Magento\Authorization\Model\Role::update`method

[Magento\Authorization\Model\Role](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/Role.php)
[Magento\Authorization\Model\Rules](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/Rules.php)

### Actual result (*)
Fatal error. Update method is not defined.

### Expected result (*)
The update method for both Role and Rules should be marked as deprecated with see reference to save method.

```
@deprecated
@see \Magento\Authorization\Model\Rules::save
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39466` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @narendrarwt. Thank you for your report. 
The issue has been fixed in magento/magento2#32212 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [861594147d30ee8763013fdffb68791067f2a139](https://github.com/magento/magento2/commit/861594147d30ee8763013fdffb68791067f2a139)

The fix will be available with the upcoming 2.4.3 release.
