### ISSUE TITLE
Magento 2 extension Allegro.pl

### ISSUE THREAD

**Issue by sportmma** [magento/magento2#30754]
Hello. Is there anyone who would like to integrate Magento 2.4.1 with Allegro.pl I would like to get full integration of Allegro.pl with Magento 2. All functions provided by Api Allegro.pl

**Comment by sivaschenko** [comment]
@sportmma I am closing this feature request as I believe this is not related to the Magento core codebase, so we cannot work on it in the magento2 repository. This integration is specific and should be implemented as an extension.
