### ISSUE TITLE
Create configurable product  Apply unique prices by attribute to each SKU WRONG price in generated

### ISSUE THREAD

**Issue by xanka** [magento/magento2#30760]
### Preconditions (*)

1. Magento Version 2.3.6

### Steps to reproduce (*)

1. create configurable product with base price is 20$
2. Create two attribute is Color: Red, Blue and Size: X. M
3. Select Apply unique prices by attribute to each SKU follow:
Red: 20$.    X: 22$
Blue: 22$.   M: 26$
### Expected result (*)

1. 4  Product generated should be:
red-x: 22$
red-m: 26$
blue-x: 24$
blue-m: 28$

### Actual result (*)

<img width="1513" alt="Screen Shot 2020-11-03 at 16 15 26" src="https://user-images.githubusercontent.com/13864969/97969303-7066ab80-1df2-11eb-936f-9102bdcd92d6.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xanka** [comment]
@magento give me {2.3.4} instance

**Comment by xanka** [comment]
@magento give me 2.3-develop instance

**Comment by engcom-Bravo** [comment]
Hello @xanka 

Thank you for your report 

This is a basic Magento functionality. When the price of simple products is calculated, the higher price configuration is set 

Anyway, you can configure the price on the next step
![price](https://user-images.githubusercontent.com/51680745/97986242-1a8a0780-1de2-11eb-82c2-79a509251c43.png)

Thank you

**Comment by xanka** [comment]
@engcom-Bravo I think this function is wrong, This's simple example but in case have more many product attribute options and generated hundred  products. You suggest check each products price manual is BAD idea. I suggest add label for this issue is BUG.  Thanks
