### ISSUE TITLE
Magento 2.4.1 admin panel spinning continuously 

### ISSUE THREAD

**Issue by Sharlyll** [magento/magento2#30768]
### Preconditions (*)

1. Exact Magento version 2.4.1
2. Server: Nginx
3. Php-fpm 7.4
4. Ubuntu 20

### Steps to reproduce (*)

1. Install Magento 2.4.1 following the official documentation. 
2. Configure nginx using nginx.conf.sample from Magento docs. 

### Expected result (*)

1. Access to admin panel 
2. Magento loading properly.

### Actual result (*)

1. Frontend loads normally
2. Admin panel spins continuously and won't load (see image)
3. Error logs is empty of any warning or report

![Screenshot 2020-11-04 at 1 13 56](https://user-images.githubusercontent.com/22851271/98050833-37065e00-1e3b-11eb-9b8c-d9a430d2ba1b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @Sharlyll,
I have verified this issue in Windows 10 and Chrome browser.
After login with credentials in Dashboard, It is showing properly.
**See attached the video:**
![Magento Admin](https://user-images.githubusercontent.com/24711761/98204815-c22b4500-1f5c-11eb-98f3-41383a88587f.gif)

@Sharlyll - It may be some installation issue on your system or any other configuration is pending from your end.

Thanks.

**Comment by Sharlyll** [comment]
Hi,

Thanks. I finally figured out the issue. you  are correct. this content security policy caused the issues: 

`add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;`

I had it in my site-available config.
is there a way to have this on my Configurations while whitelisting my website?

Thanks for your help.

**Comment by ajijshekh123** [comment]
Hi @Sharlyll,
I don't know but Let me discuss with my team and update you soon. 
Thanks.

**Comment by Sharlyll** [comment]
> Hi @Sharlyll,
> I don't know but Let me discuss with my team and update you soon.
> Thanks.

Thanks a lot. I appreciate.

**Comment by ajijshekh123** [comment]
Hi @Sharlyll,
I have discussed with my development team, He updated me below comment:
There is no configuration for extra headers. but there is a plugin to set extra header.
See the solution link:
https://magento.stackexchange.com/questions/287239/how-to-enable-cors-to-access-magento-rest-apis-magento2

Let me know if you any other help needed.
Thanks.

**Comment by Sharlyll** [comment]
> Hi @Sharlyll,
> I have discussed with my development team, He updated me below comment:
> There is no configuration for extra headers. but there is a plugin to set extra header.
> See the solution link:
> https://magento.stackexchange.com/questions/287239/how-to-enable-cors-to-access-magento-rest-apis-magento2
> 
> Let me know if you any other help needed.
> Thanks.

Hi,
Thanks for the resource. You are the best!

**Comment by Sharlyll** [comment]
I will close this thread now, given that it has been resolved.

Thanks @ajijshekh123 . I appreciate.

**Comment by ajijshekh123** [comment]
Okay @Sharlyll

**Comment by salehawal** [comment]
this is related to this issue as well #34461
