### ISSUE TITLE
[GraphQl] Aggregations ignore attribute Position field.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#30775]
### Preconditions (*)

1. 2.3.5p2

### Steps to reproduce (*)

1. Create a category and add a couple products with attributes with different values.
2. Set the position for a couple attributes to different values. (eg. Color = position 10, Size = position 30)
3. Do a GraphQl call requesting the aggregations to the products endpoint with the category as the filter. 
````
query aggregations {
    products(filter:{category_id:{eq:"2"}}) {
        aggregations {
            count
            attribute_code
            options {
                value
                label
            }
            label
        }
    }
}
````
4. Switch the positions of the attributes.
5. Do a GraphQl call requesting the aggregations to the products endpoint with the category as the filter. 

### Expected result (*)

1. The aggregations results are ordered differently between the 2 GraphQl calls based on how position is changed.

### Actual result (*)

1.The aggregation results are identical.

### Notes
As the aggregations are created based on the configuration of the attributes, the data should be returned sorted as set in the configuration. You can't expect the frontend to do this, because the returned data is not consistent between different categories and changes. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Hexmage** [comment]
@magento give me 2.4-develop instance

**Comment by Hexmage** [comment]
Still an issue in 2.4-develop

**Comment by chiara-delrio** [comment]
I am having the same issue with GraphQL and Magento 2.4

**Comment by engcom-Bravo** [comment]
Hello @Hexmage 

Thank you for your report.

We have tried to reproduce the reported issue on the latest 2.4-develop. In our case, the order of the attributes in the query is changed after changing the attributes position value.

Please, see our steps:
1. Create a category and add a couple of products with attributes with different values.
![product](https://user-images.githubusercontent.com/67371013/103352619-58886c80-4aaf-11eb-8087-ed8ce66c0cb2.png)
2. Set the position for a couple attributes to different values. (eg. Color = position 10, Size = position 30)
![Color before](https://user-images.githubusercontent.com/51680745/103354611-ae134800-4ab4-11eb-8b8d-b12fc981e938.png)
![Size before](https://user-images.githubusercontent.com/51680745/103354620-b10e3880-4ab4-11eb-8df7-6e56f83be5d1.png)
3. Do a GraphQl call requesting the aggregations to the product's endpoint with the category as the filter.
![before](https://user-images.githubusercontent.com/67371013/103353169-c6816380-4ab0-11eb-8c22-07c615c5a3c4.png)
4. Switch the positions of the attributes by changing the Position value
![Color](https://user-images.githubusercontent.com/51680745/103354352-03028e80-4ab4-11eb-91df-70c200618c0a.png)
![size](https://user-images.githubusercontent.com/51680745/103354363-08f86f80-4ab4-11eb-89e3-e4217b623059.png)

5. Perform a GraphQLquery requesting the aggregations to the product's endpoint with the category as the filter.
```graphql
query aggregations {
    products(filter:{category_id:{eq:"2"}}) {
        aggregations {
            count
            attribute_code
            options {
                value
                label
            }
            label
        }
    }
}
```

**Actual result**
1. The aggregation's results are ordered differently between the 2 GraphQl calls based on how the position is changed.
![after](https://user-images.githubusercontent.com/67371013/103353549-d3eb1d80-4ab1-11eb-97ac-3d29dc8b04cb.png)

Can you please correct our steps in order we could reproduce the issue?

Thank you in Advance

**Comment by Hexmage** [comment]
@engcom-Bravo looks like it got fixed on the 27th of November

https://github.com/magento/magento2/commit/c6aaabc206c335ca9235ff84a403f9d6ac937ebc

**Comment by engcom-Bravo** [comment]
@Hexmage thank you for the quick response. 
So we can Close this issue then. 
Please feel free to comment or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by hardikM-addweb** [comment]
I was facing the same issue here. And i think that price filter in graphql does not work with position. I have set price filter position to 500, but still it always shows on top.

Any help will be appreciated

Thank you
