### ISSUE TITLE
Duplicate customer addresses for orders created from admin

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#30770]
### Preconditions (*)

1. Magneto version 2.4.1
2. **Not reproduced** on 2.4-develop Note: Release code 2.4.1 was already merged into 2.4-develop

### Steps to reproduce (*)

1. Go to storefront & create new customer account
2. Using this customer account place an order from storefront
3. Open the customer account and order in admin panel
4. Switch to "Addresses" tab  of customer account in admin & note the count of addresses
5. Now from the order view in admin, hit Reorder option, without any change select any Payment method & submit order
6. Switch back to customer edit interface in admin & refresh the page.
7. Check the "Addresses" tab again & you will notice that address count is increased & duplicate address is created

### Expected result (*)

1. Address shouldn't be re-created on Reorder as it already exists

### Actual result (*)

1. Duplicate address is being created for each Reorder

After placing 1 order from storefront & Reordering it 2 times, the customer addresses section look like below

![6217f53a-31bb-47b4-b400-05063164287c](https://user-images.githubusercontent.com/5336201/98073819-2aabf080-1e8f-11eb-9bd7-88aaa90ea773.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38898` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Probably was fixed in https://github.com/magento/magento2/search?q=MC-38113&type=commits

@engcom-Alfa  could you please double-check

**Comment by engcom-Echo** [comment]
@rav-redchamps, I checked it again, unfortunately, it does not reproduce

Was fixed, as mentioned in the [comment](https://github.com/magento/magento2/issues/30770#issuecomment-722435709)

![Peek 2020-12-28 16-51](https://user-images.githubusercontent.com/51681435/103222586-264f0180-492d-11eb-9073-549839cad98c.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
