### ISSUE TITLE
Admin CMS Action Detail - no controller

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#3078]
Hi

Within the admin panel CMS Blocks (and Pages)
When you click action, you see an option "Detail"
Clicking this takes you to the home page.
No Controller for detail exists for both CMS page and Block

This action option either needs to be removed or the controller needs to be added.

**Comment by shiftedreality** [comment]
Hi @teuma86 

We have internal ticket MAGETWO-44966 to fix this issue. Thank you for reporting.

**Comment by veloraven** [comment]
@teuma86 ,
this issue should be already fixed. 
But if it is still reproduces please specify Magento version you use.
