### ISSUE TITLE
Internal Error. Details are available in Magento log file. Report ID: webapi-5fa2fddf4008f"

### ISSUE THREAD

**Issue by 45lailson** [magento/magento2#30797]
### Steps to reproduce (*)

1.Adicionar item ao carrinho
2. Navegue para verificar
3. Coloquei o Metodo de Entrega
4. Metodo de Pagamento com Cartão
5. Finalizei a Compra
6. Aparace o Erro Internal Error. Details are available in Magento log file. Report ID: webapi-5fa2fddf4008f"
![magento](https://user-images.githubusercontent.com/49048949/98159021-a1aaae80-1eba-11eb-846d-9f6242d9caed.png)
![Captura de tela de 2020-11-04 16-31-10](https://user-images.githubusercontent.com/49048949/98159392-41683c80-1ebb-11eb-9e65-a249e979e6ba.png)

### Expected result (*)

1. Compra Concluida
2.

### Actual result (*)

1. [Screenshots, logs or description]
2. Internal Error. Details are available in Magento log file. Report ID: webapi-5fa2fddf4008f"
3.main.CRITICAL: Report ID: webapi-5fa3004e7eb73; Message: Email must be a valid email address {"exception":"[object] (Exception(code: 0): Report ID: webapi-5fa3004e7eb73; Message: Email must be a valid email address at /var/www/html/danashe/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Zend\\Mail\\Exception\\InvalidArgumentException(code: 0): Email must be a valid email address at /var/www/html/danashe/vendor/zendframework/zend-mail/src/Address.php:68)"} []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @45lailson . Please update issue on english so we can start to verify it

**Comment by 45lailson** [comment]
foi resolvido
