### ISSUE TITLE
Admin Grid (UI Component) - Remove columns from export

### ISSUE THREAD

**Issue by lisovski** [magento/magento2#3079]
Right now there is no way (I'm not sure) to remove columns from CSV/XML export using UI component. It would be good to have "is_system" config attribute in UI component (see Magento 1) to define the columns you don't want to export.

**Comment by NadiyaS** [comment]
Hi @lisovski,
you are right, now you can not change columns for export. And in the near future it is not planned to be changed.

**Comment by tkacheva** [comment]
@asemenenko, @antboiko  what do you think?

**Comment by tkacheva** [comment]
internal issue MAGETWO-57230

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-Grid-UI-Component-Remove-columns-from-export/idi-p/46105).
