### ISSUE TITLE
Feature Suggestion: Reports: Products Ordered Options

### ISSUE THREAD

**Issue by JIFFYmix** [magento/magento2#3080]
I noticed that when an order is refunded, via a Credit Memo, the items in the order still show up in the Products Ordered report for that day. I understand that a Credit Memo does not mean the items were not delivered, so to take them out of all refunded transactions would create the opposite problem for any that were refunded after the product was delivered.

My thought is this: If an order is refunded, the system would check to see if the order was shipped. If not, the items would be returned to inventory and removed from the Products Ordered report. If so, they would remain in the daily Products Ordered totals.

Another option would be to select which items, if any, are being returned to inventory, when a Credit Memo is processed. Then those items could be returned to inventory and removed from the Products Ordered totals.

**Comment by ilol** [comment]
Hi @JIFFYmix. Thank you for your suggestion. Please take a look on https://magento.com/company/press-room/press-releases/magento-commerce-acquires-rjmetrics 

I am temporary closing this issue until we decide how to incorporate your suggestion.
