### ISSUE TITLE
Magento 2.3.5 Csp Issue

### ISSUE THREAD

**Issue by abhishekc3** [magento/magento2#30804]
**Preconditions (*)**
1. Magento CE/EE 2.3.5 without Sample Data (composer installation)
2. Nginx 1.10.3 (PHP 7.3.21).
3. Default Nginx config used (nginx.conf.sample).

**Steps to reproduce (*)**
1. Navigate to URL: Click a form in home page.

**Expected result (*)**
1. Form Url should open.

**Actual result (*)**
1. Error - 502 Bad Gateway.

![image](https://user-images.githubusercontent.com/74008438/98258849-5de1a300-1fa7-11eb-81db-e284f8917465.png)

**Summary of the issue:**
I have created a custom CSP module for removing the browser console warnings. In module, I created two files **config.xml** and **csp_whitelist.xml**. When I enable this module i get the above error but when I disable the module my website is running properly.

**config.xml**
![image](https://user-images.githubusercontent.com/74008438/98259746-828a4a80-1fa8-11eb-9f6a-93a1e77aa5b3.png)

**csp_whitelist.xml**
![image](https://user-images.githubusercontent.com/74008438/98259838-9930a180-1fa8-11eb-979e-ae91fd11194f.png)

**Comment by hostep** [comment]
Could maybe be related to https://github.com/magento/magento2/issues/29964 (which has a fix in https://github.com/magento/magento2/commit/047629aeb29354c35c7ebe4f12b7eed160e241e0) but it's hard to say without more info. Maybe you can find more info the Magento and/or webserver log files?

**Comment by iphigenie** [comment]
> Could maybe be related to #29964 (which has a fix in [047629a](https://github.com/magento/magento2/commit/047629aeb29354c35c7ebe4f12b7eed160e241e0)) 

the symptom would be 1) cache taking a lot more space than it used to and 2) out of memory errors in the logs

**Comment by tim-breitenstein-it** [comment]
> Could maybe be related to #29964 (which has a fix in 047629a) but it's hard to say without more info. Maybe you can find more info the Magento and/or webserver log files?

Is it possible to fix this temporary with an custom module?
