### ISSUE TITLE
Magento 2 Upgrade to 2.0.1 Failed - Sorry, we can't take that action right now.

### ISSUE THREAD

**Issue by peternicholson26** [magento/magento2#3081]
![screen shot 2016-01-22 at 14 24 47](https://cloud.githubusercontent.com/assets/7713722/12513147/27adc0d0-c114-11e5-8372-6ecbef40e4c0.png)
I was about to upgrade Magento 2 to 2.0.1 but get the following error on the system upgrade:

Sorry, we can't take that action right now.

I have signed in using my secure keys but still get the error. Anyone else having the same issue?

Cheers!

(https://cloud.githubusercontent.com/assets/7713722/12513147/27adc0d0-c114-11e5-8372-6ecbef40e4c0.png)

**Comment by tanya-soroka** [comment]
Hello @peternicholson26. We have created MAGETWO-48262 ticket for the investigation.

**Comment by monkeysee** [comment]
Hi, @peternicholson26 , how did you originally get Magento 2 installed?  Through git clone or composer create-project?

**Comment by smatric** [comment]
Same problem here. I also have my keys added in the admin panel and filesystem permission, cron and ulimit set according to the documentation.

I installed magento from an archive (Magento-CE-2.0.0-2015-11-17-05-56-31.tar.bz2) using the Setup Wizard.

**Comment by monkeysee** [comment]
Thanks, @smatric can you and/or @peternicholson26 enable your browser's development mode? That will probably display a more specific error.

**Comment by smatric** [comment]
I've changed MAGE_MODE to developer in app/etc/env.php and I added SetEnv MAGE_MODE developer in .htaccess but I don't see any difference. However, if I look at the content of AJAX response from systemPackage, it says {"error":"Undefined index: name","responseType":"error"}

**Comment by smatric** [comment]
Also, following http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html#updater didn't help:

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update

**Comment by mazhalai** [comment]
@smatric ~~anything in `var/.updater_status.log`~~ Please add the following to your composer.json file and try again

```
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
```

**Comment by smatric** [comment]
That help. Thank you @mazhalai!

**Comment by driiftkiing** [comment]
Same problem, tried this one : http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html

Installed magento with wizard.

**Comment by malaiselvan** [comment]
Same problem. None of the solution provided in this [link](http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html) is not helping...

Below is my composer.json file.

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.0",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.0.6",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```

Installed Magento 2.0 via Composer + downloaded zip file from magento website.  Migrated the data from 1.9.1.0....

Struggling for almost a week to upgrade... No luck...

@tanya-soroka Any update on this... We could see this is tagged as a bug.  Do we have any timeline for this as this fix is addressing a security concern???

**Comment by refaelgold** [comment]
i got this error 

```
Check Cron Scripts
Cron script readiness check failed. Hide detail

Error from Setup Application Cron Script:
Cron job has not been configured yet
Other checks will fail as a result (PHP version, PHP settings, and PHP extensions)

For additional assistance, see cron scripts help.
```

i really try to do all but i cant upgrade magento 2.0.0 to 2.0.1

**Comment by smatric** [comment]
Here are the steps I had to follow to upgrade Magento 2.0.0 to 2.0.1. I hope this will help others.

1) I had to remove data-migration-tool dependency. In composer.json I replaced this section:

```
"repositories": {
    "0": {
        "type": "composer",
        "url": "https://repo.magento.com/"
    },
    "data-migration-tool": {
        "type": "git",
        "url": "https://github.com/magento/data-migration-tool-ce"
    }
},
```

with the following config:

```
"repositories": {
    "0": {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
},
```

Then I ran:

```
$ composer remove magento/data-migration-tool --update-with-dependencies
```

and:

```
$ composer update --lock
```

This step takes care of `Sorry, we can't take that action right now` error.

2) Then I had to create some missing `.gitignore` files:

```
$ touch vendor/magento/magento2-base/dev/tests/js/JsTestDriver/.gitignore
$ touch vendor/magento/magento2-base/dev/tests/api-functional/.gitignore
$ touch vendor/magento/magento2-base/dev/tests/unit/.gitignore
$ touch vendor/magento/magento2-base/dev/tests/static/.gitignore
$ touch vendor/magento/magento2-base/dev/tests/integration/.gitignore
$ touch vendor/magento/magento2-base/dev/tests/functional/.gitignore
```

This avoids errors such as:

```
[ErrorException] 
Source /var/www/html/m2/vendor/magento/magento2-base/dev/tests/integration/.gitignore does not exist
```

3) Finally, I had to edit the config section in composer.json:

```
"config": {
    "use-include-path": true,
},
```

to add my GitHub OAuth token:

```
"config": {
    "use-include-path": true,
    "github-oauth": {
        "github.com": "<token>"
    }
},
```

Which took care of this error:

```
[Composer\Downloader\TransportException] 
Could not authenticate against github.com
```

After that, I was able to successfully run the Web Setup Wizard.

This was a rather time consuming process that made me feel as if I was working with some beta software and not production ready eCommerce platform.

**Comment by simkea** [comment]
###### my crontab -u www-data

```
*/1 * * * * php -c /etc/php5/cli/ /var/www/kaphingst/mage2-shop/magento2/bin/magento cron:run
*/1 * * * * php -c /etc/php5/cli/ /var/www/kaphingst/mage2-shop/magento2/update/cron.php
*/1 * * * * php -c /etc/php5/cli/ /var/www/kaphingst/mage2-shop/magento2/bin/magento setup:cron:run
```

##### I believe there are missing this value "file_permissions_verified" in the /var/.setup_cronjob_status for UPDATER

![image](https://cloud.githubusercontent.com/assets/612913/12550296/2289a35c-c363-11e5-9577-9ead481a17f9.png)

```
{
    "readiness_checks": {
        "db_write_permission_verified": true
    },
    "php_checks": {
        "php_version_verified": {
            "responseType": "success",
            "data": {
                "required": "~5.5.0|~5.6.0|~7.0.0",
                "current": "5.6.14-0+deb8u1"
            }
        },
        "php_extensions_verified": {
            "responseType": "success",
            "data": {
                "required": [
                    "ctype",
                    "gd",
                    "spl",
                    "dom",
                    "simplexml",
                    "mcrypt",
                    "hash",
                    "curl",
                    "iconv",
                    "intl",
                    "xsl",
                    "mbstring",
                    "openssl",
                    "zip"
                ],
                "missing": []
            }
        },
        "php_settings_verified": {
            "responseType": "error",
            "data": {
                "always_populate_raw_post_data": {
                    "message": "Your PHP Version is 5.6.14-0+deb8u1, but always_populate_raw_post_data = 0.\n \t        $HTTP_RAW_PO$
                    "helpUrl": "http://php.net/manual/en/ini.core.php#ini.always-populate-settings-data",
                    "error": true
                }
            }
        }
    },
    "last_timestamp": 1453723145,
    "current_timestamp": 1453723146
}
```

**Comment by eddielau** [comment]
@simkea Do you find a file named .update_cronjob_status in the var directory?

**Comment by grasdaggel** [comment]
Same problem - fixes didn't work. Please advise how to fix asap, Updating is a _huge_ problem rn for most of our customers.

**Comment by mazhalai** [comment]
Have you tried fixes mentioned [here](http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html). These issues have been addressed for almost two weeks now.

**Comment by sshrewz** [comment]
As we have not heard back from you, we will proceed with closing this issue.  Feel free to submit a new issue if you encounter additional problems.
