### ISSUE TITLE
Magento 2.4 Installation Error On CentOS

### ISSUE THREAD

**Issue by techqa10** [magento/magento2#30814]
Note: I have some issue with #29462 Because of the issue closed i created new one. If this against to rules please accept my apologies.

### Summary (*)
I can install Magento 2.4 to different environments excepts CentoOS. I had CentOS 7.X i tried to install Magento 2.4 and i get the "Class Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor does not exist" error on Installation step. I upgraded my PHP version to 7.4 but i still get same error.

After that, I installed CentOS v8.4 with PHP 7.3 but i got same error. And tried with PHP 7.4 but i got same error again.

Finally i have CentOS 8.2 with official PHP 7.3 but getting same error.

Note: I can successfully install Magento 2.4 into my OS X and other operating systems.

### Examples (*)

When i run this command (with/without install parameters)

`php bin/magento setup:install`

I get this error

```
Class Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor does not exist

In InstallCommand.php line 274:
                               
  Parameter validation failed 
```

`php -v` Results

```
PHP 7.3.20 (cli) (built: Jul  7 2020 07:53:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.20, Copyright (c) 1999-2018, by Zend Technologies
```

`php -m` Results

```
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
readline
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

Thanks

**Comment by ihor-sviziev** [comment]
Hi @techqa10,
Seems like this issue duplicates https://github.com/magento/magento2/issues/30575.

Could you try to remove / disable PDO php extension? I believe it should fix the issue.
If the issue still exists - please try to run with `-vvv ` option at the end and give us output. 

Hope it will help you

**Comment by techqa10** [comment]
Hi @ihor-sviziev,

I removed my PDO extension. But at this time i'm getting this error:

```
PHP Fatal error:  Uncaught Error: Class 'PDO' not found in /var/www/sites/magento/setup/src/Magento/Setup/Model/ConfigOptionsList.php:180
Stack trace:
#0 /var/www/sites/magento/setup/src/Magento/Setup/Model/ConfigModel.php(71): Magento\Setup\Model\ConfigOptionsList->getOptions()
#1 /var/www/sites/magento/setup/src/Magento/Setup/Console/Command/ConfigSetCommand.php(64): Magento\Setup\Model\ConfigModel->getAvailableOptions()
#2 /var/www/sites/magento/vendor/symfony/console/Command/Command.php(77): Magento\Setup\Console\Command\ConfigSetCommand->configure()
#3 /var/www/sites/magento/setup/src/Magento/Setup/Console/Command/ConfigSetCommand.php(54): Symfony\Component\Console\Command\Command->__construct()
#4 /var/www/sites/magento/vendor/laminas/laminas-di/src/Di.php(511): Magento\Setup\Console\Command\ConfigSetCommand->__construct(Object(Magento\Setup\Model\ConfigModel), Object(Magento\Framework\Module\ModuleList), Object(Magento\Framework\App\DeploymentConfig))
#5 /var/www/sites/magento/vendor/laminas/laminas-di/src/Di.php(318):  in /var/www/sites/magento/setup/src/Magento/Setup/Model/ConfigOptionsList.php on line 180
```

And this is output for when PDO extension enabled

```
Class Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor does not exist

In InstallCommand.php line 274:
                               
  [InvalidArgumentException]   
  Parameter validation failed  
                               

Exception trace:
  at /var/www/sites/magento/setup/src/Magento/Setup/Console/Command/InstallCommand.php:274
 Magento\Setup\Console\Command\InstallCommand->initialize() at /var/www/sites/magento/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /var/www/sites/magento/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/sites/magento/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/sites/magento/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /var/www/sites/magento/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/sites/magento/bin/magento:23
```

**Comment by ihor-sviziev** [comment]
Hi @techqa10,
I'm really sorry, I wrote incorrect extension name. Please try to enable back the `pdo` exception, but disable `psr` extension.

**Comment by techqa10** [comment]
Hi @ihor-sviziev,

Thank you for great support.

This is `my php -m` results.

```
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib
```

So i don't have php-psr extension. And i added `"ext-psr": "*"` line to my composer.json file's conflict object like mentioned in  #30575 

But result is same as before.

**Comment by techqa10** [comment]
I installed CentOS and Ubuntu to two virtual machines. I can successfully install Magento 2.4.1 to Ubuntu Server. But i'm still getting same error on CentOS.

**Comment by ihor-sviziev** [comment]
@techqa10 sorry, I wasn’t able to check it.

@engcom-Alfa @engcom-Bravo @engcom-Charlie could you verify this issue? Seems really critical to me

**Comment by techqa10** [comment]
Additional information:

I checked my composer versions on Ubuntu and CentOS (Both same: 1.10.1)

And i just run this command

`COMPOSER_MEMORY_LIMIT=-1 composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento` for two platforms

And i compared folders via `diff -arq` command, and see that on CentOS there are no directories in

- generated/code/Magento/Framework/DB
- generated/code/Psr

this explains why i'm getting this error on CentOS. But why this folders does't exists? I still can't understand.

Thanks.

**Comment by ihor-sviziev** [comment]
Could you make sure that permissions are set correctly?

**Comment by techqa10** [comment]
Yes, i'm sure i checked permissions twice.

* After this message i run command with root user. Still same results.

**Comment by ihor-sviziev** [comment]
@techqa10 have you fixed the issue you had?

**Comment by Sharlyll** [comment]
Hi I am getting a similar error during installation.
magento version: 2.4.5-p1
composer: 2.5.1
nginx
php 8.1
all php extensions are installed
command run:
bin/magento setup:install \
--base-url=http://123.123.123.123 \
--db-host=localhost \
--db-name=magento \
--db-user=magento \
--db-password="U274eeGzNCqKJ2LpvtS@329" \
--admin-firstname=bob \
--admin-lastname=smith \
--admin-email=bob@example.com \
--admin-user=bob \
--admin-password=example@123 \
--language=en_US \
--currency=GBP \
--timezone=Europe/London \
--use-rewrites=1

here is the error:
array_merge(): Argument #2 must be of type array, string given#0 /var/www/html/setup/src/Magento/Setup/Model/ConfigModel.php(157): array_merge()
#1 /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php(273): Magento\Setup\Model\ConfigModel->validate()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(221): Magento\Setup\Console\Command\InstallCommand->initialize()
#3 /var/www/html/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#6 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#7 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#8 {main}

please help

**Comment by ihor-sviziev** [comment]
@Sharlyll it doesn't look as a similar issue. Please report it separately
