### ISSUE TITLE
Token Revocation REST API

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#30820]
### Description (*)
As a user, when I log out, I want to guarantee that my token is revoked. Currently, with the REST API, there's no known way to do this.

The GraphQL api supports this:
https://devdocs.magento.com/guides/v2.3/graphql/mutations/revoke-customer-token.html

### Expected behavior (*)
I can securely revoke my authentication token.

### Benefits
Basic security improvement for customers.

### Additional information
cc: @zetlen

**Comment by sivaschenko** [comment]
The feature request was confirmed by @nrkapoor

**Comment by ProkopovVitaliy** [comment]
@magento I am working on this
