### ISSUE TITLE
Upgrade procedure fails

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3082]
Hello...

I think this is a bug. I tried to upgrade from 2.0.0 to 2.01, however, the following error occurs:

[ErrorException] 
chdir(): open_basedir restriction in effect. File(/home/depasa) is not within the allowed path(s): (/home/depasa/public_html:/tmp:/home/depasa/tmpsite:/opt/php5-6/lib/php:/opt/ferozo/etc/suspen:/opt/ferozo/suspended.page) 

I know how to solve it, but, why does the script try to access the user root directory? it is a nonsense from my point of view. 

Regards,
Jaime

**Comment by buskamuza** [comment]
Hi @jaimestuardo ,
could you, please, provide more information?
1. How were you doing upgrade (console or Setup Wizard, any other details)?
2. Where is your Magento root folder located? Is it in the user dir?
3. Do you use symlinks for anything inside Magento?

**Comment by jaimestuardo** [comment]
Hi Olga... here are the answers:

1.- Setup wizard. Just using System -> Web Setup Wizard option. After upgrade process started, the error is shown in console log area.

2.- Magento root folder is at public_html folder. Full path is /home/depasa/public_html, where /home/depasa is root folder for depasa user, so, it does not have any sense that magento tries to do something there.

3.- Just use symlinks provided by Magento (generally concerning templates. I don't know if Magento uses another symlinks). I did not create any symlink by myself

**Comment by tanya-soroka** [comment]
@jaimestuardo thanks you for reporting the issue. We have created ticket MAGETWO-48259 to investigate.

**Comment by buskamuza** [comment]
Thanks for the answers, @jaimestuardo .

> After upgrade process started, the error is shown in console log area.

Just to confirm. Readiness check was all green, and the failure happens only during upgrade itself. Right?

UPD. Basing on https://github.com/magento/magento2/issues/3084 it's probably on the upgrade step itself.

**Comment by jaimestuardo** [comment]
Yes... all green... and in fact, that is the only case when Next button is activated.

**Comment by sshrewz** [comment]
This issue has been resolved and new patch version was released.  Feel free to submit a new issue if you encounter any problems.
