### ISSUE TITLE
Address field prefix not drop-down on Checkout

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#3083]
I have made the Prefix field dropdown for Mr, Mrs, Ms, Miss.

This works when altering / adding an address in the My Account Section.

but when I add new billing / shipping address in the checkout, it shows as a text field.

**Comment by ishakhsuvarov** [comment]
@teuma86 Thank you for reporting this issue. We have created an internal ticket `MAGETWO-48248` to fix this problem.

**Comment by mktudock** [comment]
We are having the same issue, is this already resolved on the develop branch?

**Comment by ludwig-gramberg** [comment]
we have the same issue, any update on this?

**Comment by sjavalv** [comment]
Same, but i can't see prefix on checkout at all.

**Comment by magento-engcom-team** [comment]
@teuma86 thank you for your report.
The fix for this issue is already fixed in 2.1.0 release
