### ISSUE TITLE
Better JS extensibility of variables and functions declared outside JS components, widgets, etc

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#30836]
### Summary (*)

We need better extensibility of JS files in Magento 2.

### Examples (*)

`vendor/magento/module-checkout/view/frontend/web/js/view/billing-address/list.js`
I want to change the `addressOptions` or just replace it with a new list that I want to add in my module.
See bellow which `addressOptions`, because there is another property in the component with same name:
```
define([
    'uiComponent',
    'Magento_Customer/js/model/address-list',
    'mage/translate',
    'Magento_Customer/js/model/customer'
], function (Component, addressList, $t, customer) {
    'use strict';

    var newAddressOption = {
            /**
             * Get new address label
             * @returns {String}
             */
            getAddressInline: function () {
                return $t('New Address');
            },
            customerAddressId: null
        },
        addressOptions = addressList().filter(function (address) {
            return address.getType() === 'customer-address';
        });

    return Component.extend({
```

Magento JS Mixins will not allow me to do this because the variable is the scope of the function that is in the original file `list.js`.

This is a general issue with JS files in Magento. All over there are declarations of variables that we can't change though Magento extensible techniques.
This is a "rewrite" issue. 
Different 3rd party developers have to replace completely a JS file from `vendor/magento` just because of this issue.
Now, I know sometimes 3rd party developers find other ways to bring same feature with a different approach. But this does not always hold.

### Proposed solution
Can we have a refactor on all JS files having this issue ?
Like create a new Javascript file. Include this file in `list.js`.
We, 3rd party developers can do a mixin on this new JS file. And it will work.
In this JS file make a class that has methods and properties needed in `list.js`,
In the case of `list.js` there are 2 variables: `newAddressOption` and `addressOptions`.
In other Magento JS files there are functions declared outside the JS component, jQuery UI widget, ...

Bring this up and extension developers and other types of devs in general will appreciate it much.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
For your case why not mixin and add your extend behavior in Magento_Customer/js/model/address-list 
I think in your specific case you need customise both js side and php side for set address. Some case you must rewrite but it think it's ok if you know what you are doing

**Comment by daniel-ifrim** [comment]
@mrtuvn Mixin can be made. But it won't work for this.addressOptions, the property inside the component.
I wanted to changed it and have it like this:
```
var addressOptions = addressList().filter(function (address) {
            return address.getType() === 'customer-address' && address.canUseForBilling();
});
```
I ended up having the mixin like this:
```
...
mixin = {
            /**
             * @returns {Object} Chainable.
             */
            initConfig: function () {
                this._super();

                this.addressOptions = this.addressOptions.filter(function (address) {
                    return typeof address.getType !== 'function' || (typeof address.getType === 'function'
                        && address.getType() === 'customer-address' && address.canUseForBilling());
                });

                return this;
            },

            /**
             * @return {exports.initObservable}
             */
            initObservable: function () {
                this._super();

                // Init again with filtered addressOptions
                this.observe({
                    isNewAddressSelected: !customer.isLoggedIn() || !addressOptions.length
                });

                return this;
            }
...
```

I could not affect the code with initial values.
I had to find a work around. Which happens to work and to be close to the architecture of KO in Magento 2 / checkout JS files.
In this case I was lucky it worked.
We need something to extend the JS in a proper way, comfortably and programmatically correct.
Some of the JS code within a file can be moved inside component. Like there isn't always a need to create separate JS file for that part in the beginning.
I believe that this refactoring will add more extensibility to Magento 2 and make things easier for developers.
There are cases when w need to copy paste the original file inside store theme just for a small change.
Since we developers maintain extensions or modules that can be used in different store, duplicating entire original files inside extension directory is very hard to maintain. Magento 2 does release new versions quite often (which is great).
I don't really understand why there is code inside Magento 2 JS files that can not be extended properly.
Was this a decision for security reasons ?
Magento 2 is a great platform and can be extended easy in most of the cases.

**Comment by mrtuvn** [comment]
Yep magento is big system but it not perfect. Some parts is old code migrate or implementation incorrect can lead to this case. Some place code inconsistent and wait for refactor
