### ISSUE TITLE
Region selector disabled when all countries set to region optional and "Allow to Choose State if It is Optional for Country" set to Yes

### ISSUE THREAD

**Issue by david-kominek** [magento/magento2#30840]
### Preconditions (*)

1. Magento version 2.4.1
2. PHP 7.3

### Steps to reproduce (*)

1. Clear all countries from Stores > Configuration > General > State Options > "State is Required for"
2. Set Stores > Configuration > General > State Options > "Allow to Choose State if It is Optional for Country" to Yes
3. On customer create form (or any other form with country and region), select a country with a regions list (if default country does not have a region list) ![image](https://user-images.githubusercontent.com/26467332/98449607-7910f780-20fa-11eb-80c5-918a9ff73cfb.png)
4. On the same form, select a country with no regions list 
![image](https://user-images.githubusercontent.com/26467332/98449635-ad84b380-20fa-11eb-99e4-11d9fcbf3c9e.png)
5. On the same form, select a country with a regions list 
![image](https://user-images.githubusercontent.com/26467332/98449643-bbd2cf80-20fa-11eb-9c65-319c37e83352.png)

### Expected result (*)

1. Region list input should not be disabled, customer should be able to select the region ![image](https://user-images.githubusercontent.com/26467332/98449607-7910f780-20fa-11eb-80c5-918a9ff73cfb.png)

### Actual result (*)

1. Region list input is disabled, customer is not able to select a region from the dropdown ![image](https://user-images.githubusercontent.com/26467332/98449646-bf665680-20fa-11eb-95d7-5f65b345e184.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

---
I have created a patch that resolves the issue:
```javascript
diff -Naur a/vendor/magento/module-checkout/view/frontend/web/js/region-updater.js b/vendor/magento/module-checkout/view/frontend/web/js/region-updater.js
Fixed region field shown but disabled for countries with region list but not set to region required
--- a/vendor/magento/module-checkout/view/frontend/web/js/region-updater.js
+++ b/vendor/magento/module-checkout/view/frontend/web/js/region-updater.js
@@ -193,7 +193,7 @@
                         regionList.hide();
                         container.hide();
                     } else {
-                        regionList.show();
+                        regionList.removeAttr('disabled').show();
                     }
                 }

```

**Comment by engcom-Bravo** [comment]
Hello @david-kominek 

Thank you for your report

We have rechecked the reported issue on 2.4.1 and on 2.4-develop and we are **not** able to reproduce the issue 

We have cleared all the Countries from _Stores > Configuration > General > State Options >_  **"State is Required for"**
And set "_Allow to Choose State if It is Optional for Country"_ to **Yes**
![config_regions](https://user-images.githubusercontent.com/51680745/98538852-12274600-2294-11eb-831c-53a3bb42f074.gif)

We have rechecked the described behavior on Storefront - Checkout
![Region selection_storefront_checkout](https://user-images.githubusercontent.com/51680745/98539051-5fa3b300-2294-11eb-8b76-c58902f5083f.gif)

On Storefront, Customer Address edit page
![Region selection_storefront_cust_address](https://user-images.githubusercontent.com/51680745/98538966-3a16a980-2294-11eb-83fb-b5a1edfec9bc.gif)

And on Customer Address page on Admin

The **State/Province** dropdown is available and selectable 

Can you please add more info to the description?

Thank you in Advance

**Comment by david-kominek** [comment]
Reviewing source for 2.4.0 and 2.4.1, the patch above was already applied to those versions.
