### ISSUE TITLE
(Admin) Review page was break layout

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#30844]
### Preconditions (*)
1. M2.4.0

### Steps to reproduce (*)
1. go Admin > Marketing > (User Content) All Reviews > Choose one to Edit
2. Layout was break https://imgur.com/E6gOKtr
I seen that form HTML structure was incorrect. All fields was pulled to summary-rating field https://imgur.com/oWKE0Mz

### Expected result (*)
1. https://imgur.com/USohC2d

### Actual result (*)
1. https://imgur.com/E6gOKtr

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @kamui23,
I have verified this issue on the latest Chrome, Firefox and Microsoft Edge browser in the Windows 10 OS.
I didn't reproduce this issue. 
Can you please update me on which browser break the page?
See attached the screenshot:
Chrome:
![image](https://user-images.githubusercontent.com/24711761/98502978-75f04580-2279-11eb-864a-a3817ebab665.png)

Firefox:
![image](https://user-images.githubusercontent.com/24711761/98502990-7ab4f980-2279-11eb-8ddd-4f54bfcc72c6.png)

Microsoft Edge:
![image](https://user-images.githubusercontent.com/24711761/98502997-80aada80-2279-11eb-9c76-89915fc01deb.png)

Thanks.

**Comment by kamui23** [comment]
@magento give me 2.4-develop instance

**Comment by kamui23** [comment]
hi @ajijshekh123 
thank you for your verification.
i checked on 2.4-develop instance and saw no issue.
Please close this issue.
Thank you

**Comment by kamui23** [comment]
hi @ajijshekh123
thank you for your verification.
i checked on 2.4-develop instance and saw no issue.
Please close this issue.
Thank you

**Comment by ajijshekh123** [comment]
Okay @kamui23 
Thanks for the Update.

**Comment by tprocter-ldg** [comment]
Hello, 

We have replicated this issue on M2.4.0 and it appears to be the self closing `<div class="rating"/>` tag on line 14 of `/magento/module-review/view/adminhtml/templates/rating/stars/summary.phtml`

The solution would be to use [valid HTML](https://html.spec.whatwg.org/#start-tags) in this template as a div element should not be self closing:
`<div class="rating"></div>`
