### ISSUE TITLE
Can't save attribute value|Or can't update attribute value

### ISSUE THREAD

**Issue by Aiweline** [magento/magento2#30842]
### Preconditions (*)

1. get a description in below url
https://bbs.aiweline.com/thread-120788.htm

### Steps to reproduce (*)

1. get a description in below url
https://bbs.aiweline.com/thread-120788.htm

### Expected result (*)

1. can't save attribute value,but tip message is saved ok!

### Actual result (*)

1. Attribute value can't save.

**Comment by engcom-Delta** [comment]
HI @Aiweline 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
