### ISSUE TITLE
Adding colorpicker to configuration

### ISSUE THREAD

**Issue by rexxx2011** [magento/magento2#30852]
Adding color picker to custom configuration tab in magento 2.4

**Comment by engcom-Delta** [comment]
Hi @rexxx2011 there is not enough information to understand and verify issue you described

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
