### ISSUE TITLE
how to change the robots meta tag only in a static page

### ISSUE THREAD

**Issue by riswit** [magento/magento2#3085]
After weeks of research, I feel here.

I want to set the robots meta tags - via XML - only in a static page, not all site.

what is the equivalent of this code in magento 2?

< reference name="head">
< action method="setRobots">< value>NOINDEX,FOLLOW</ value></ action>
</ reference>

Thank you!!

**Comment by antboiko** [comment]
Hello @riswit , you can include this < meta name="robots" content="NOINDEX,FOLLOW"/ > into the < head > < /head > section.

**Comment by riswit** [comment]
Hello @antboiko, 

i have maked a static page, throught "Admin - Content - Pages".
I want to set meta tag robots, only in this page.

if i try to set this code in "Design - Layout Update XML": 

appears this error:

"Please correct the XML data and try again. Element 'head': This element is not expected. Expected is one of ( referenceContainer, container, update, move ). Line: 1" 

What's a method equivalent to this code:

< reference name="head">
< action method="setRobots">< value>NOINDEX,FOLLOW</ value></ action>
</ reference>

it's possible in magento 2?

thank you!!

**Comment by antboiko** [comment]
Hi @riswit , we have internal ticket MAGETWO-52688 for this feature in our backlog.

Thanks,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/how-to-change-the-robots-meta-tag-only-in-a-static-page/idi-p/46100).

**Comment by Khaleel** [comment]
Was this ever fixed?

**Comment by zakgrindle** [comment]
This is still an issue in 2.2.3.  It's basically impossible to set noindex on individual categories, products or cms pages as an admin without this.

**Comment by kor3** [comment]
Is this issue still unresolved?

**Comment by rav-redchamps** [comment]
Hi @riswit @kor3 @zakgrindle @Khaleel 

We have developed a Magento 2 extension to set meta robot tag per page basis. You can use it to easily update meta robot tag for any of store pages(particular product, category, CMS page, shopping cart etc ) via admin.

Additionally, it will also exclude pages from sitemap having meta robots tag 'NOINDEX, FOLLOW' or 'NOINDEX, NOFOLLOW'

The extension can be found at below URL

https://redchamps.com/meta-robots-tag-per-page-magento-2-extension.html
