### ISSUE TITLE
Cron error Undefined index: jobs and stuck in Magento installer

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3086]
After the data migration from Magento 1.9.1.0 to 2.0 I get the following error: 

PHP:  syntax error, unexpected ')' in /usr/local/php56/bin/php56 on line 1

  [ErrorException]  
  Undefined index: jobs  

cron:run [--group="..."] [--bootstrap="..."]

I has nothing todo with the cron jobs, because I get the same error if I run "php -f bin/magento cron:run" from ssh.

Is gues this is a bug, does anyone know how to solve the issue.

Thanks alot 

Michiel

**Comment by ghost** [comment]
I have checked the cron log and it says that always_populate_rawdata = 0, however I'm 100% sure that the value is -1 according to my php log (http://www.db6479.web44.ixl.nu/phpinfo.php)

{
    "readiness_checks": {
        "db_write_permission_verified": true
    },
    "php_checks": {
        "php_version_verified": {
            "responseType": "success",
            "data": {
                "required": "~5.5.0|~5.6.0|~7.0.0",
                "current": "5.6.16"
            }
        },
        "php_extensions_verified": {
            "responseType": "success",
            "data": {
                "required": {
                    "0": "curl",
                    "1": "dom",
                    "2": "hash",
                    "3": "openssl",
                    "4": "simplexml",
                    "5": "xmlwriter",
                    "8": "gd",
                    "10": "iconv",
                    "11": "mcrypt",
                    "14": "spl",
                    "15": "xsl",
                    "16": "intl",
                    "17": "mbstring",
                    "18": "ctype"
                },
                "missing": []
            }
        },
        "php_settings_verified": {
            "responseType": "error",
            "data": {
                "always_populate_raw_post_data": {
                    "message": "Your PHP Version is 5.6.16, but always_populate_raw_post_data = 0.\n \t        $HTTP_RAW_POST_DATA is deprecated from PHP 5.6 onwards and will be removed in PHP 7.0.\n \t        This will stop the installer from running.\n\t        Please open your php.ini file and set always_populate_raw_post_data to -1.\n \t        If you need more help please call your hosting provider.",
                    "helpUrl": "http://php.net/manual/en/ini.core.php#ini.always-populate-settings-data",
                    "error": true
                }
            }
        }
    },
    "last_timestamp": 1453547103,
    "current_timestamp": 1453547163
}

**Comment by ghost** [comment]
It's common to have two `php.ini`, one for the PHP CLI and one for the web server. To determine which one you need to edit, use a [`phpinfo.php`](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/optional.html#install-optional-phpinfo) file to find the **Loaded Configuration File**.

Please let us know if this helps.

**Comment by ghost** [comment]
Thank you for your reply. Our web server host modified the cron job as follow to solve the warning:

/usr/local/php70/bin/php -d always_populate_raw_post_data=-1 /home/telefoon/domains/db6479.web44.ixl.nu/public_html/bin/magento setup:cron:run  

However for some reason the installer stuck every time at: ''./composer.json has been updated''.

[2016-01-27 10:49:03 UTC] Job "maintenance_mode {"enable":true}" has been started
[2016-01-27 10:49:03 UTC] Magento maintenance mode is enabled.
[2016-01-27 10:49:03 UTC] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-01-27 10:49:03 UTC] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}" has been started
[2016-01-27 10:49:03 UTC] Starting composer update...
[2016-01-27 10:49:03 UTC] ./composer.json has been updated

Do you have any idea how to solve this?

**Comment by mazhalai** [comment]
@MichielTG can you check your var folder for presence of files that begin with `.` any indication of error? Also try running your crons manually. Do you get any errors?

**Comment by ghost** [comment]
Thank you for your reply. I have run al my cron jobs and double checked the /var folder for any errors. etc

> Crons:
> php -c /home/telefoon/php.ini /home/telefoon/domains/blueburst.nl/public_html/update/cron.php
> php -c /home/telefoon/php.ini /home/telefoon/domains/blueburst.nl/public_html/bin/magento cron:run
> /usr/local/php70/bin/php -d always_populate_raw_post_data=-1 /home/telefoon/domains/blueburst.nl/public_html/bin/magento setup:cron:run

However I can't find any errors and the installer is still stuck at ' ./composer.json has been updated'.

**Comment by mazhalai** [comment]
@MichielTG sorry for the delay, has your issue been fixed?  Once composer has been updated, it does take a while for the code to be updated.

**Comment by lernerValeriy** [comment]
Good Day! 
I have a similar problem. Command php ./magento cron:run give  [ErrorException] Undefined index: jobs. Logs are empty. PHP v7.0
Migration was from 1.7.0.2 to 2.0.2. I don't know if it works before migration on not.
I don't even know how I can debug this. Please, help

**Comment by mazhalai** [comment]
@lernerValeriy `cron:run` is not used during setup upgrade. You have to setup `update/cron.php` and `/bin/magento setup:cron:run`. Please see complete details [here](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html).

**Comment by lernerValeriy** [comment]
I don't need setup upgrade. I just want schedule indexer and newsletters. But it is not working

**Comment by mazhalai** [comment]
@lernerValeriy Please open a new issue instead of posting on old threads. This original thread was related to upgrade related cron.

**Comment by ghost** [comment]
@mazhalai Thank you for your reply. We are currently trying to fix it to update and install composer in the update subdirectory. I will let you know if this fixes the issue.

**Comment by mazhalai** [comment]
@MichielTG any update?

**Comment by ghost** [comment]
@mazhalai Unfortunately we have encountered another problem with the setup wizard. For this reason we are unable to test is properly. Currently the web setup wizard link redirect tot 404-page. 
There doesn't seem to be any redirects in .htaccess and file permissions are setup properly. 

Any idea what might be the problem?

We are looking forward to your reply.

**Comment by mazhalai** [comment]
@MichielTG you mean when you login to admin and click on config->web setup wizard?

**Comment by ghost** [comment]
@mazhalai Yes, this is indeed the issue right now.

**Comment by mazhalai** [comment]
@MichielTG are you still on 2.0 and upgrading to 2.0.1/2.0.2 there were a couple of issues re upgrade. Please read this http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html

**Comment by ghost** [comment]
@mazhalai We currently have Magento ver. 2.0.2 - because we were able to upgrade Magento 2 to 2.0.1 and 2.0.2 with Installatron (http://installatron.com).

**Comment by mazhalai** [comment]
@MichielTG do you have access to your var folder. Please try clearing it, and then access setup-wizard.

**Comment by ghost** [comment]
@mazhalai Do you mean all files and folders?
We have just tried cleaning:
Clearing var/cache
Clearing var/session
Clearing var/page_cache
Clearing var/tmp

**Comment by ghost** [comment]
Thanks for the tip. I just cleaned the whole directory and this seems to fix the 404-error however. Some files are currently missing according to the browser:

```
http://www.screenprotectorgoedkoop.nl/setup/index.php/navigation/side-menu Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.screenprotectorgoedkoop.nl/setup/index.php/navigation Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.screenprotectorgoedkoop.nl/setup/index.php/navigation/header-bar Failed to load resource: the server responded with a status of 404 (Not Found)
```

Could the setup directory be corrupted?

**Comment by mazhalai** [comment]
@MichielTG please check file permissions.

**Comment by ghost** [comment]
@mazhalai Thank you for your message. File permissions was indeed the issue. However we are now getting the '"Sorry, we can't take that action right now" error. 
And we also tried the guidelines which didn't seem to fix the issue: http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html#not-auth

We are looking forward to your message.

**Comment by mazhalai** [comment]
@MichielTG please check keys within `var/composer_home/auth.json`

**Comment by ghost** [comment]
@mazhalai I have double checked the auth.json, but those settings are filled in properly. I also tried regenerating the keys without any success.

**Comment by veloraven** [comment]
@MichielTG is this issue still actual?
As I can see from previous comments at least the original issue was resolved, so we can close this ticket.
If you have any other issues please create separate ticket for each of them.

**Comment by ghost** [comment]
This issue is still actual, however because we had multiple problems with Magento 2. So we went back to the stable 1.9. So unfortunately we can't help to solve this bug anymore.
