### ISSUE TITLE
Public content based on context variables not working

### ISSUE THREAD

**Issue by ahajji06** [magento/magento2#30878]
### Summary (*)

We used in our Shop a context variable "CUSTOMER_SEGMENT" to generate diffrent full page cache for specific customers.
But after last update from version 2.4.0 to version 2.4.1 full page cache seems to only reflect the default context variables of magento. Any extension using plgin like documented will be ignored.
### Examples (*)

class CustomerAgeContextPlugin
{
    public function __construct(
        \Magento\Customer\Model\Session $customerSession
    ) {
        $this->customerSession = $customerSession;
    }

    function beforeGetVaryString(\Magento\Framework\App\Http\Context $subject)
    {
        $age = $this->customerSession->getCustomerData()->getCustomAttribute('age');
        $defaultAgeContext = 0;
        $ageContext = $age >= 30 ? 1 : $defaultAgeContext;
        $subject->setValue('CONTEXT_AGE', $ageContext, $defaultAgeContext);
    }
}

Let´s say our goal is to priovide different prices based on CONTEXT_AGE variable. (5% discount for customer over 30 and 20% for customer under 30). Both customers have the same customer group.
Price modification plugin is working fine.

When a customer from first segment logs in he sees the correct prices on category, search results and product view.
When a customer from the second segement logs in he sees the price of the first segment.

and vice versa.

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sunilit42** [comment]
@ahajji06 any update on that?
