### ISSUE TITLE
Reservation issues with Inventory Management / Sallable quantity when working with configurable products.

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#30877]
### Preconditions (*)

1.  Magento 2.3.5-p2
2.  Inventory Management with Sallable QTY enabled

_Scenario 1:_ 

### Steps to reproduce (*)

1. Make two simple products: SKU-A and SKU-B
2. Make a configurable with SKU-CONFIG
3. Add the two simple products to the configurable
4. Place an order on the **front-end** for SKU-A via the configurable
5. Ship the order in the backend

### Expected result (*)

1.  During ordering SKU-A should be added to the inventory_reservation table
2.  During shipping SKU-A should be counter added to the inventory_reservation table

### Actual result (*)

1.  During ordering SKU-CONFIG is added to the inventory_reservation table, but this is the configurable without stock management
2. During shipping SKU-CONFIG is counter added to the inventory_reservation table, but this is the configurable without stock management

Because of this the underlying simple product is not reserved, so the sallable quantity of the simple product is incorrect while the order is waiting for shipment.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

_Scenario 2:_ 

### Steps to reproduce (*)

1. Make two simple products: SKU-A and SKU-B
2. Make a configurable with SKU-CONFIG
3. Add the two simple products to the configurable
4. Place an order in the **backend** for SKU-A via the configurable
5. Ship the order in the backend

### Expected result (*)

1.  During ordering SKU-A should be added to the inventory_reservation table
2.  During shipping SKU-A should be counter added to the inventory_reservation table

### Actual result (*)

1.  During ordering SKU-A is added to the inventory_reservation table
2. During shipping SKU-A is counter added to the inventory reservation table
3. During shipping SKU-CONFIG is counter added to the inventory_reservation table, but this is the configurable without stock management
4. This causes also a balance that is no zero for that order, so those lines are never removed from the inventory_reservation table.

For scenario 2 the sallable quantity is correct, but because it counter adds the configurable sku too, the qty balance of that order is not 0 and all the rows for that order are kept in the inventory_reservation table.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @GuiltyNL , issue related to Magento Inventory Project(MSI)
Could you create issue in appropriate MSI [repo](https://github.com/magento/inventory/issues) for further investigation and close this ticket once it will be done?

**Comment by krishprakash** [comment]
Hi @GuiltyNL. Thank you for your report 
MSI related issues should be reported to its separate [repo ](https://github.com/magento/inventory/issues)
