### ISSUE TITLE
2.0.1 breaks out-of-stock configurable options disabled rendering

### ISSUE THREAD

**Issue by tigerx7** [magento/magento2#3087]
After upgrading to 2.0.1, configurable options swatches aren't not acting the same. In 2.0.0, when an option of a configurable product with other in-stock options was out of stock and "Display out-of-stock" was enabled, the out-of-stock option swatch would still show but disabled with a red line across it.

After upgrading to 2.0.1, the out-of-stock swatch no longer shows at all. There were no issues doing the upgrade via the Setup wizard. Static files were re-deployed and cache flushed, still the same.

**Comment by tigerx7** [comment]
After some debugging, I traced the issue to /Magento/Swatches/Block/Product/Renderer/Configurable.php https://github.com/magento/magento2/commit/b59734d32a8882e59caced35e12c8be3a45e104a

The issue seemed to have happened when getAllOptionsIdsFromAttributeArray() was refactored to getConfigurableOptionsIds(). What I figured was for optimization purposes, inadvertently changed the method of retrieving configurable options to rely on getAllowProducts() which only retrieves products that return true for isSaleable or if skipSaleableCheck is true. Since the configurable option is "out-of-stock" and not saleable and skipSaleableCheck is false, it is not being included in the list of products and thus its configurable attribute option isn't being included in getJsonSwatchConfig().

I'm not sure if the better method would be to set skipSaleableCheck to true or to fallback to not using getAllowProducts() to retrieve configurable options. In our production version, I've gone ahead and rolled back the method of retrieving configurable options IDs for now to restore the functionality of displaying out-of-stock swatch options.

**Comment by tomasgriffin** [comment]
Can confirm this is also a problem when not using swatches. The configuration option "Display out of stock products" no longer has the expected effect as the products are completely removed from the drop down menus.

**Comment by magento-engcom-team** [comment]
@tigerx7, thank you for your report.
We've created internal ticket(s) MAGETWO-82603 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tigerx7, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
