### ISSUE TITLE
GraphQL product filter not using website/store

### ISSUE THREAD

**Issue by avra911** [magento/magento2#30875]
### Preconditions (*)

1. Install Magento 2.4.0
2. Create at least 2 websites (A and B)

### Steps to reproduce (*)

1. Create a new product and select only B website in the edit page under the "Product in Websites" tab.
2. Use graphQl "products(filter: { sku: { eq: "SKU" } } ) {" query and a store header from the website A.

### Expected result (*)

1. The product SKU should not be in the search result.

### Actual result (*)

1. The product SKU is listed in the search result.

**Comment by netzkollektiv** [comment]
Just to clarify for others: 

The store needs to be passed in the request header.
https://devdocs.magento.com/guides/v2.3/graphql/send-request.html#headers
