### ISSUE TITLE
Tab component in Custom entity form

### ISSUE THREAD

**Issue by UpSage** [magento/magento2#30889]
### Preconditions (*)

1. Magento 2.4.0
2. Magento 2.4.1

### Steps to reproduce (*)

1.  When I created a custom module with a custom entity, I tried adding a tab to make the UI more presentable but Tab won't work

### Expected result (*)

1. Expected result
![image](https://user-images.githubusercontent.com/14990670/98908187-038e9800-24fb-11eb-8155-18701326a4de.png)

### Actual result (*)

1. Actual result

![image](https://user-images.githubusercontent.com/14990670/98908279-23be5700-24fb-11eb-925e-d13526bc29a5.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sandy6666** [comment]
@SageKit Please update your layout attribute in the page tag where you are calling your ui_component 

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" layout="admin-2columns-left">
    <update handle="styles"/>
    <update handle="editor"/>
    <head>
        <title>Add New Store</title>
    </head>
    <body>
        <referenceContainer name="content">
            <uiComponent name=""/>
        </referenceContainer>
    </body>
</page>
