### ISSUE TITLE
Google Analytics CSP Violation

### ISSUE THREAD

**Issue by zaximus84** [magento/magento2#30880]
### Preconditions (*)

1. Magento 2.4.0
2. Magento_Csp installed / enabled
3. Magento_GoogleAnalytics installed / enabled

### Steps to reproduce (*)

1. In admin store configuration, go to Sales / Google API > Google Analytics. Set Enabled = Yes and enter an Account Number.
2. Flush all caches and load a page on the store front (such as the home page).

### Expected result (*)

1. There are no console errors / failed assets or requests due to CSP violations.

### Actual result (*)

1. There is a console error regarding a CSP violation for an XHR request to https://www.google-analytics.com/j/collect. If CSP is in report-only mode, it's just a console error. If CSP is actually enforced, the XHR request is not executed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39579` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @zaximus84. Thank you for your report. 
The issue has been fixed in magento/magento2#30881 by @zaximus84 in 2.4-develop branch
Related commit(s):
 - [a4f66bd38ebf2d889dbc90ca517d2c4ef1f8869f](https://github.com/magento/magento2/commit/a4f66bd38ebf2d889dbc90ca517d2c4ef1f8869f)
 - [9be0942b374cdb619b4a38f962b0a26911a30fec](https://github.com/magento/magento2/commit/9be0942b374cdb619b4a38f962b0a26911a30fec)

The fix will be available with the upcoming 2.4.3 release.
