### ISSUE TITLE
Unit test testGetLocaleList fails for non en_US php default locale

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#30894]
### Preconditions (*)

1. Magento version 2.4.0
2. set intl.default_locale to 'de-DE' in php.ini

### Steps to reproduce (*)

1. run unit test testGetLocaleList in Magento\Framework\Setup\Test\Unit\ListsTest

### Expected result (*)

1. Test passes

### Actual result (*)

1. Test fails with error: Failed asserting that two arrays are equal.

Expected | Actual
------------- | ---------
'en_US' => 'English (United States)' | 'en_US' => 'English (United States)'
'en_GB' => 'English (United Kingdom)' | 'en_GB' => 'English (United Kingdom)'
'uk_UA' => 'Ukrainian (Ukraine)' | 'uk_UA' => 'Ukrainian (Ukraine)'
'de_DE' => 'German (Germany)' | 'de_DE' => 'German (Germany)'
'sr_Cyrl_RS' => 'Serbian (Cyrillic, Serbia)' |
'sr_Latn_RS' => 'Serbian (Latin, Serbia)' |

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Bravo** [comment]
Hi @ochnygosch,

The Related PR has been closed.Hence We are Closing this issue.

Please feel free to open the issue.

Thanks.
