### ISSUE TITLE
Doubles the quantity of products on the checkout page

### ISSUE THREAD

**Issue by sergey-ctrl** [magento/magento2#30905]
### Preconditions (*)

1. Magento ver. 2.4.1, php 7.4

### Steps to reproduce (*)

1. Log in customer account https://i.imgur.com/oYsH3pe.png
2. Add product with quantity 1 to cart 
3. Go to Shopping Cart and then click "Check Out with Multiple Address" https://i.imgur.com/J7A7ryL.png
4. Go to Home Page https://i.imgur.com/IL4p1Hx.png
5. Go to Checkout https://i.imgur.com/K4xicyF.png
6. Open Order Summary

### Expected result (*)

  1. Qty = 1

### Actual result (*)

 1. Qty=2 https://i.imgur.com/bVleOsA.png 
 2. Double Cart Subtotal  https://i.imgur.com/hPKG5oV.png

---

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @sergey-ctrl, Not able to replicate the issue as provided steps by you.
Kindly provide the additional steps and also kindly verify in latest magento instance
![image](https://user-images.githubusercontent.com/46617848/98944762-8d4c5e80-2517-11eb-9d3f-19b123284a47.png)

**Comment by krishprakash** [comment]
Hi @sergey-ctrl, Feel free to reopen the issue once you confirm that issue reproduce on 2.4-develop instance 
Thanks!!
