### ISSUE TITLE
ProductUrlSuffix and CategoryUrlSuffix GraphQL resolvers fail with null values

### ISSUE THREAD

**Issue by aligent-lturner** [magento/magento2#30909]
### Preconditions (*)

1. Magento version 2.4.x
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization
2. Clear product and category url suffix values in admin and save

![Screenshot from 2020-11-20 15-24-20](https://user-images.githubusercontent.com/51679138/99806502-c94e7780-2b46-11eb-9875-251237379bba.png)

Run GraphQL query that requests product and/or category url suffix value

```graphql
{
  categoryList {
    url_suffix
  }
}
```

**Expected result:**  Empty string (`''`) is returned for `url_suffix` value

![Screenshot from 2020-11-20 15-40-01](https://user-images.githubusercontent.com/51679138/99807411-2d257000-2b48-11eb-876c-0421e8c9b59a.png)

**Actual Result:** :heavy_multiplication_x: Query fails

![Screenshot from 2020-11-20 15-29-15](https://user-images.githubusercontent.com/51679138/99806636-fac74300-2b46-11eb-8ff7-df40a6beb19d.png)

:heavy_multiplication_x:  with the following error in `exception.log`:

`
2020-11-20 13:29:04] main.ERROR: Return value of Magento\CatalogUrlRewriteGraphQl\Model\Resolver\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/vendor/webonyx/graphql-php/src/Error/Error.php:174, TypeError(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/CategoryUrlSuffix.php:80)"} []
`

### Additional Information
The problem is that the private functions `getProductUrlSuffix` and `getCategoryUrlSuffix` are declared with `string` as the return type, but when values are cleared in admin config, `null` gets stored in the `core_config_data` table. The value being returned by `ScopeConfigInterface->getValue` should be checked for null and changed to empty string instead.
I will create PR to fix this.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39290` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by aligent-lturner** [comment]
@zakdma there is already an approved PR for this issue.

**Comment by zakdma** [comment]
@aligent-lturner ok
Please assign it to issue

**Comment by aligent-lturner** [comment]
@zakdma it was referenced - for some reason the bot removed the pr in progress tag.
https://github.com/magento/magento2/pull/30910

**Comment by magento-engcom-team** [comment]
Hi @aligent-lturner. Thank you for your report. 
The issue has been fixed in magento/magento2#30910 by @aligent-lturner in 2.4-develop branch
Related commit(s):
 - [5512626bfdfdede24ded8095998c647092d60ebb](https://github.com/magento/magento2/commit/5512626bfdfdede24ded8095998c647092d60ebb)
 - [ffcc5234644f0b6813dcbacc120689c372ee7af9](https://github.com/magento/magento2/commit/ffcc5234644f0b6813dcbacc120689c372ee7af9)
 - [673edbeef402cdce35888dcc105261be24184337](https://github.com/magento/magento2/commit/673edbeef402cdce35888dcc105261be24184337)
 - [53ed515634f5a38a04eb32b93a69f12ae6695ab2](https://github.com/magento/magento2/commit/53ed515634f5a38a04eb32b93a69f12ae6695ab2)

The fix will be available with the upcoming 2.4.3 release.
