### ISSUE TITLE
Unable to find template for sales/order/print/order_id/x

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30913]
### Summary (*)
I am searching the template for the order PDF which is showing in checkout success page when you click the "**print receipt**" link.

Where can I find it? I have to change the header.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by Eddcapone** [comment]
@engcom-Delta This is a Developer experience issue, why did you created this issue category if such questions are not allowed?

![image](https://user-images.githubusercontent.com/16349349/99376185-e247f600-28c4-11eb-8b2d-5e81452f0839.png)
