### ISSUE TITLE
New Relic is not being given useful transaction names for graphql requests

### ISSUE THREAD

**Issue by convenient** [magento/magento2#30915]
{quote}
### Description (*)

Every graphql is being given the same transaction name in new relic.

This means when using a PWA site that most of the requests do not get split out in any useful way in New Relic. They all get lumped into `/FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor`.

This makes it really hard to debug specific slow or buggy requests. I would classify this as a bug because it makes New Relic pretty useless with a Magento PWA stack and makes it much harder to support.
### Expected behavior (*)

We have some better naming of transactions within the application. Maybe something like
```java
- /GraphQL-productDetail
- /GraphQL-getCartDetails
```
There is an open discussion here <https://discuss.newrelic.com/t/feature-idea-magento-2-graphql-api-transaction-naming/98824> but both the options discussed there make it seem like this fix needs to come from within the Magento application.
### Benefits

Having the transactions properly broken down within New Relic is vital for supporting the application at an enterprise level. It's a big step back to not have this functionality.
### Additional information

N/A
{quote}

**Comment by sasha19957099** [comment]
@magento I am working on this

**Comment by nizarn** [comment]
@magento export issue to Jira project MC

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MC-39998) is successfully created for this issue.

**Comment by sasha19957099** [comment]
To test on the cloud environment with Magento in vendor repository rename with .patch extension and change the file paths.
[Newrelic_for_GraphQL_transactions.txt](https://github.com/magento/magento2/files/5881173/Newrelic_for_GraphQL_transactions.txt)

**Comment by convenient** [comment]
@sasha19957099 How does this work for `Mutation` and `Query` types?

https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/CustomerGraphQl/etc/schema.graphqls#L17-L18

For example would the above show as `GraphQL-Mutation` or `GraphQL-generateCustomerToken`?

Thanks

**Comment by cspruiell** [comment]
@sasha19957099 Please provide a pull request for your fix.

**Comment by cspruiell** [comment]
Coverage of additional scenarios will be handled internally.

**Comment by cpartica** [comment]
this ticket was developed internally and will be available part of 2.4.4

**Comment by ashkumar-wtc** [comment]
Do we have a patch for this ? We need it for Magento 2.43 .

**Comment by convenient** [comment]
https://github.com/magento/magento2/commit/b0131a276cb34bd928da996658b4110ec1188863
