### ISSUE TITLE
Can`t apply link to widget with TinyMCE 4 Magento 2.3.5-p1

### ISSUE THREAD

**Issue by Artishhh** [magento/magento2#30918]
### Preconditions (*)

1. Magento 2.4-develop
2. Magneto 2.3.5 and Magneto 2.3.5-p1 fresh project without sample data.

### Summary (*)
1. After TinyMCE 4 update widgets can`t be wrapped in link with WYSIWYG editor

### Steps to reproduce (*)

0. Steps on Fresh magneto 2 installations.
1. Make sure TinyMCE 4 is enabled for the WYSIWYG editor
2. Edit homepage cms page
3. Add any widget to a home page content
4. Select widget and click on Add link icon on  in WYSIWYG editor or right-click on widget add a link

### Expected result (*)

1. Widget is wrapped in a tag and link works for all widget content

### Actual result (*)

1. All content stays the same and the widget isn`t wrapped in a tags

![link](https://user-images.githubusercontent.com/51679138/99083915-e88d5800-25ce-11eb-90c2-ab40d46d047d.gif)

### Note:
An issue exists only on TinyMCE 4 and works as expected with TinyMCE 3

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39113` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
