### ISSUE TITLE
Missing Indexes

### ISSUE THREAD

**Issue by itisraza** [magento/magento2#30914]
### Description (*)
Attached are some of the table indexes which are missing in the default installation of magento 2, these indexes once added will really boost the performance of both admin and the store

### Expected behavior (*)
From end user stand point, there is no change in the user experience and the admin side of the store

### Benefits
These indexes will improve the overall performance of both the store and the database side of things

### Additional information
Please see attached for details 
[Magento2-Missing-Indexes.xlsx](https://github.com/magento/magento2/files/5536216/Magento2-Missing-Indexes.xlsx)

**Comment by pemann** [comment]
@itisraza where did that list come from? Which indexes particularly will boost the performance?

**Comment by itisraza** [comment]
This list is pulled directly from database, so these are FK/relational IDs but not indexed and these will slow down performance of underlying database queries for sure whenever and wherever these are referenced in JOIN or in WHERE clause.

Hope this answers your question.

Let me know if you need more details.

Regards,
Raza.
