### ISSUE TITLE
Configurable product price is not displayed if all children are out of stock and even if Display Out of Stock Products is set to

### ISSUE THREAD

**Issue by tranhoangthien1990** [magento/magento2#30912]
Configurable product price is not displayed if all children are out of stock and even if Display Out of Stock Products is set to "yes"

Preconditions (*)
1. Magento 2.4.1 with sample data (include b2b module)
2. Magento 2.4-develop

Steps to reproduce (*)
1. Create a configurable product with view simples (4 children products with 2 attributes size and color)
2. Make configurable and all simple products out of stock
3. Set Display Out of Stock Products to "yes"

Expected result (*)
1. Price for the configurable product should be displayed

Actual result (*)
1. Price for the configurable product is not displayed
![image](https://user-images.githubusercontent.com/51681379/101777369-0d57eb00-3afb-11eb-8967-bcf7396f7359.png)

I'm looking for an official topic for this issue, to tracking this issue process. As i can see we have a lot of topic about this issue, but seem it's already closed a long time ago but it's still happened in the 2.4.1 version.

Thanks for your support.

**Comment by engcom-Delta** [comment]
This issue should be discussed in the scope of **Feature Request**.
