### ISSUE TITLE
System integration issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#30925]
### Preconditions (*)

1. Magento 2.4.1
2. php 7.1
3. Mysql 5.7

### Steps to reproduce (*)

1. Add new integration with all allowed
2. Click Authorize

### Expected result (*)

1. Authorization succesfull and integration enable. Generation of Api access.

### Actual result (*)

1. Error on exception.log. 
[2020-11-15 17:22:06] main.CRITICAL: Role '241' not found {"exception":"[object] (Zend_Acl_Role_Registry_Exception(code: 0): Role '241' not found at /var/www/html/vendor/magento/zendframework1/library/Zend/Acl/Role/Registry.php:132)"} []

**Comment by achatpc** [comment]
@magento give me 2.4-develop instance

**Comment by achatpc** [comment]
@magento I am working on this

**Comment by achatpc** [comment]
@magento add to contributors team

**Comment by achatpc** [comment]
@magento add to contributors team

**Comment by achatpc** [comment]
@magento give me 2.4-develop instance

**Comment by pemann** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
For people running into this problem: try flushing the cache after you created an integration. That solved this problem over here on Magento 2.3.5.

**Comment by mortenbirkelund** [comment]
We just faced this issue when creating a user-role.. Clearing the cache worked. 
Is this just one of those peculiar things you have to accept in magento?

**Comment by hostep** [comment]
@mortenbirkelund: hmm yeah, I didn't open a new issue because I didn't have the time to verify if this was still a problem on the latest version of Magento. But if you can confirm that the same problem happens on the latest version of Magento, I think it would be wise to open a new issue so it gets solved one day or another.
