### ISSUE TITLE
Upgrading magento 2.3.5 to 2.4.0

### ISSUE THREAD

**Issue by apuc** [magento/magento2#30920]
### Preconditions (*)
1. Magento 2.3.5, php 7.3.24, mysql 8
2. Magento 2.3.5 with theme Supro

### Steps to reproduce (*)
1. installing Elasticseacrh 7.10.0
2. composer require magento/composer-root-update-plugin=~1.0 --no-update
composer update
3. composer require magento/product-community-edition=2.4.0 --no-update
composer update
4. I updated versions of packages from require that gave errors

### Expected result (*)
1. the version will be updated to 2.4

### Actual result (*)

1. from the "replace" section of the composer, a large number of packages give a version error, it is not possible to specify for the version ">="
![image](https://user-images.githubusercontent.com/6388044/99087881-5724e280-25dc-11eb-95c9-dede446ac25d.png)

My composer.json:
{
    "name": "magento/magento2ce",
    "description": "Magento 2 (Open Source)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "php": "~7.1.3||~7.2.0||~7.3.0",
        "ext-bcmath": "*",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-dom": "*",
        "ext-gd": "*",
        "ext-hash": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "ext-pdo_mysql": "*",
        "ext-simplexml": "*",
        "ext-soap": "*",
        "ext-xsl": "*",
        "ext-zip": "*",
        "lib-libxml": "*",
        "applitools/eyes.sdk.php": "^1.3",
        "braintree/braintree_php": ">=3.35.0",
        "colinmollenhour/cache-backend-file": "~1.4.1",
        "colinmollenhour/cache-backend-redis": ">=1.10.6",
        "colinmollenhour/credis": ">=1.10.0",
        "colinmollenhour/php-redis-session-abstract": "~1.4.0",
        "composer/composer": "^1.9",
        "dpdinrussia/magento-2-dpd-russia": "dev-master",
        "elasticsearch/elasticsearch": "~2.0||~5.1||~6.1||~7.6",
        "emagicone/module-connector": "^1.0",
        "guzzlehttp/guzzle": "^6.3.3",
        "laminas/laminas-captcha": "^2.7.1",
        "laminas/laminas-code": ">=3.3.0",
        "laminas/laminas-config": "^2.6.0",
        "laminas/laminas-console": "^2.6.0",
        "laminas/laminas-crypt": "^2.6.0",
        "laminas/laminas-db": "^2.8.2",
        "laminas/laminas-dependency-plugin": "^1.0",
        "laminas/laminas-di": "^2.6.1",
        "laminas/laminas-eventmanager": "^3.0.0",
        "laminas/laminas-feed": "^2.9.0",
        "laminas/laminas-form": "^2.10.0",
        "laminas/laminas-http": "^2.6.0",
        "laminas/laminas-i18n": "^2.7.3",
        "laminas/laminas-json": "^2.6.1",
        "laminas/laminas-log": "^2.9.1",
        "laminas/laminas-mail": "^2.9.0",
        "laminas/laminas-mime": "^2.5.0",
        "laminas/laminas-modulemanager": "^2.7",
        "laminas/laminas-mvc": "~2.7.0",
        "laminas/laminas-serializer": "^2.7.2",
        "laminas/laminas-server": "^2.6.1",
        "laminas/laminas-servicemanager": "^2.7.8",
        "laminas/laminas-session": "^2.7.3",
        "laminas/laminas-soap": "^2.7.0",
        "laminas/laminas-stdlib": "^3.2.1",
        "laminas/laminas-text": "^2.6.0",
        "laminas/laminas-uri": "^2.5.1",
        "laminas/laminas-validator": "^2.6.0",
        "laminas/laminas-view": "~2.11.2",
        "magento/composer": ">=1.5.0",
        "magento/composer-root-update-plugin": "~1.0",
        "magento/magento-composer-installer": ">=0.1.11",
        "magento/product-community-edition": "2.4.0",
        "magento/zendframework1": "~1.14.2",
        "mageplaza/magento-2-russian-language-pack": "dev-master",
        "mageplaza/module-core": "^1.4",
        "mageplaza/module-smtp": "^4.0",
        "magestat/module-cookie-law-banner": "^1.1",
        "monolog/monolog": "^1.17",
        "msp/recaptcha": "^2.2",
        "paragonie/sodium_compat": "^1.6",
        "pelago/emogrifier": ">=2.0.0",
        "php-amqplib/php-amqplib": "~2.7.0||~2.10.0",
        "php-webdriver/webdriver": "^1.8",
        "phpseclib/mcrypt_compat": "1.0.8",
        "phpseclib/phpseclib": "~2.0",
        "ramsey/uuid": "~3.8.0",
        "retailcrm/api-client-php": "~5.0",
        "symfony/console": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "symfony/event-dispatcher": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "symfony/process": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "tedivm/jshrink": "~1.3.0",
        "tubalmartin/cssmin": "4.1.1",
        "webonyx/graphql-php": "^0.13.8",
        "wikimedia/less.php": "~1.8.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "friendsofphp/php-cs-fixer": "~2.14.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "~2.6.4",
        "pdepend/pdepend": "2.5.2",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "@stable",
        "phpstan/phpstan": "^0.12.2",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "~3.4.0"
    },
    "suggest": {
        "ext-pcntl": "Need for run processes in parallel mode"
    },
    "replace": {
        "magento/module-marketplace": "101.0.0",
        "magento/module-admin-analytics": "101.0.0",
        "magento/module-admin-notification": "101.0.0",
        "magento/module-advanced-pricing-import-export": "101.0.0",
        "magento/module-amqp": "100.4.0",
        "magento/module-amqp-store": "100.4.0",
        "magento/module-analytics": "101.0.0",
        "magento/module-asynchronous-operations": "101.0.0",
        "magento/module-authorization": "101.0.0",
        "magento/module-authorizenet": "101.0.0",
        "magento/module-authorizenet-acceptjs": "101.0.0",
        "magento/module-authorizenet-cardinal": "101.0.0",
        "magento/module-authorizenet-graph-ql": "101.0.0",
        "magento/module-advanced-search": "101.0.0",
        "magento/module-backend": "101.1.0",
        "magento/module-backup": "101.0.0",
        "magento/module-braintree": "101.0.0",
        "magento/module-braintree-graph-ql": "101.0.0",
        "magento/module-bundle": "101.0.0",
        "magento/module-bundle-graph-ql": "101.0.0",
        "magento/module-bundle-import-export": "101.0.0",
        "magento/module-cache-invalidate": "101.0.0",
        "magento/module-captcha": "101.0.0",
        "magento/module-cardinal-commerce": "101.0.0",
        "magento/module-catalog": "103.0.5",
        "magento/module-catalog-customer-graph-ql": ">=100.3.0",
        "magento/module-catalog-analytics": "101.0.0",
        "magento/module-catalog-import-export": "101.1.0",
        "magento/module-catalog-inventory": "101.0.0",
        "magento/module-catalog-inventory-graph-ql": "101.0.0",
        "magento/module-catalog-rule": "101.2.0",
        "magento/module-catalog-rule-configurable": "101.0.0",
        "magento/module-catalog-search": "101.1.0",
        "magento/module-catalog-url-rewrite": "101.0.0",
        "magento/module-catalog-widget": "101.0.0",
        "magento/module-checkout": "101.0.0",
        "magento/module-checkout-agreements": "101.0.0",
        "magento/module-checkout-agreements-graph-ql": "101.0.0",
        "magento/module-cms": "103.0.5",
        "magento/module-cms-url-rewrite": "101.0.0",
        "magento/module-config": "101.2.0",
        "magento/module-configurable-import-export": "101.0.0",
        "magento/module-configurable-product": "101.0.0",
        "magento/module-configurable-product-sales": "101.0.0",
        "magento/module-contact": "101.0.0",
        "magento/module-cookie": "101.0.0",
        "magento/module-cron": "101.0.0",
        "magento/module-currency-symbol": "101.0.0",
        "magento/module-customer": "103.0.0",
        "magento/module-customer-analytics": "101.0.0",
        "magento/module-customer-downloadable-graph-ql": ">=100.3.0",
        "magento/module-customer-import-export": "101.0.0",
        "magento/module-deploy": "101.0.0",
        "magento/module-developer": "101.0.0",
        "magento/module-dhl": "101.0.0",
        "magento/module-directory": "101.0.0",
        "magento/module-directory-graph-ql": "101.0.0",
        "magento/module-downloadable": "101.0.0",
        "magento/module-downloadable-graph-ql": "101.0.0",
        "magento/module-downloadable-import-export": "101.0.0",
        "magento/module-eav": "103.0.0",
        "magento/module-elasticsearch": "101.0.0",
        "magento/module-elasticsearch-6": "101.0.0",
        "magento/module-elasticsearch-7": ">=100.3.0",
        "magento/module-email": "101.1.0",
        "magento/module-encryption-key": "101.0.0",
        "magento/module-fedex": "101.0.0",
        "magento/module-gift-message": "101.0.0",
        "magento/module-google-adwords": "101.0.0",
        "magento/module-google-analytics": "101.0.0",
        "magento/module-google-optimizer": "101.0.0",
        "magento/module-graph-ql": "101.0.0",
        "magento/module-graph-ql-cache": "101.0.0",
        "magento/module-catalog-graph-ql": "101.0.0",
        "magento/module-catalog-cms-graph-ql": ">=100.3.0",
        "magento/module-catalog-url-rewrite-graph-ql": "101.0.0",
        "magento/module-configurable-product-graph-ql": "101.0.0",
        "magento/module-customer-graph-ql": "101.0.0",
        "magento/module-eav-graph-ql": "101.0.0",
        "magento/module-swatches-graph-ql": "101.0.0",
        "magento/module-tax-graph-ql": "101.0.0",
        "magento/module-url-rewrite-graph-ql": "101.0.0",
        "magento/module-cms-url-rewrite-graph-ql": "101.0.0",
        "magento/module-weee-graph-ql": "100.4.0",
        "magento/module-cms-graph-ql": "101.0.0",
        "magento/module-grouped-import-export": "101.0.0",
        "magento/module-grouped-product": "101.0.0",
        "magento/module-grouped-catalog-inventory": "101.0.0",
        "magento/module-grouped-product-graph-ql": "101.0.0",
        "magento/module-import-export": "101.0.0",
        "magento/module-indexer": "101.0.0",
        "magento/module-instant-purchase": "101.0.0",
        "magento/module-integration": "101.0.0",
        "magento/module-layered-navigation": "101.0.0",
        "magento/module-media-gallery": "101.0.0",
        "magento/module-media-gallery-api": ">=100.3.0",
        "magento/module-media-storage": "101.0.0",
        "magento/module-message-queue": "100.4.0",
        "magento/module-msrp": "101.0.0",
        "magento/module-msrp-configurable-product": "101.0.0",
        "magento/module-msrp-grouped-product": "101.0.0",
        "magento/module-multishipping": "101.0.0",
        "magento/module-mysql-mq": "101.0.0",
        "magento/module-new-relic-reporting": "101.0.0",
        "magento/module-newsletter": "101.0.0",
        "magento/module-offline-payments": "101.0.0",
        "magento/module-offline-shipping": "101.0.0",
        "magento/module-page-cache": "101.0.0",
        "magento/module-payment": "101.0.0",
        "magento/module-paypal": "101.0.0",
        "magento/module-paypal-captcha": "101.0.0",
        "magento/module-paypal-graph-ql": "101.0.0",
        "magento/module-persistent": "101.0.0",
        "magento/module-product-alert": "101.0.0",
        "magento/module-product-video": "101.0.0",
        "magento/module-quote": "101.2.0",
        "magento/module-quote-analytics": "101.0.0",
        "magento/module-quote-graph-ql": "101.0.0",
        "magento/module-related-product-graph-ql": "101.0.0",
        "magento/module-release-notification": "101.0.0",
        "magento/module-reports": "101.0.0",
        "magento/module-require-js": "101.0.0",
        "magento/module-review": "101.0.0",
        "magento/module-review-analytics": "101.0.0",
        "magento/module-robots": "101.1.0",
        "magento/module-rss": "101.0.0",
        "magento/module-rule": "101.0.0",
        "magento/module-sales": "103.0.0",
        "magento/module-sales-analytics": "101.0.0",
        "magento/module-sales-graph-ql": "101.0.0",
        "magento/module-sales-inventory": "101.0.0",
        "magento/module-sales-rule": "101.2.0",
        "magento/module-sales-sequence": "101.0.0",
        "magento/module-sample-data": "101.0.0",
        "magento/module-search": "101.1.0",
        "magento/module-security": "101.0.0",
        "magento/module-send-friend": "101.0.0",
        "magento/module-send-friend-graph-ql": "101.0.0",
        "magento/module-shipping": "101.0.0",
        "magento/module-signifyd": "101.0.0",
        "magento/module-sitemap": "101.0.0",
        "magento/module-store": "101.1.0",
        "magento/module-store-graph-ql": "101.0.0",
        "magento/module-swagger": "101.0.0",
        "magento/module-swagger-webapi": "101.0.0",
        "magento/module-swagger-webapi-async": "101.0.0",
        "magento/module-swatches": "101.0.0",
        "magento/module-swatches-layered-navigation": "101.0.0",
        "magento/module-tax": "101.0.0",
        "magento/module-tax-import-export": "101.0.0",
        "magento/module-theme": "101.1.0",
        "magento/module-theme-graph-ql": "101.0.0",
        "magento/module-translation": "101.0.0",
        "magento/module-ui": "101.2.0",
        "magento/module-ups": "101.0.0",
        "magento/module-url-rewrite": "102.0.0",
        "magento/module-user": "101.2.0",
        "magento/module-usps": "100.4.0",
        "magento/module-variable": "100.4.0",
        "magento/module-vault": "101.2.0",
        "magento/module-vault-graph-ql": "100.4.0",
        "magento/module-version": "100.4.0",
        "magento/module-webapi": "100.4.0",
        "magento/module-webapi-async": "100.4.0",
        "magento/module-webapi-security": "100.4.0",
        "magento/module-weee": "100.4.0",
        "magento/module-widget": "101.2.0",
        "magento/module-wishlist": "101.2.0",
        "magento/module-wishlist-graph-ql": "100.4.0",
        "magento/module-wishlist-analytics": "100.4.0",
        "magento/theme-adminhtml-backend": "100.4.0",
        "magento/theme-frontend-blank": "100.4.0",
        "magento/theme-frontend-luma": "100.4.0",
        "magento/language-de_de": "100.4.0",
        "magento/language-en_us": "100.4.0",
        "magento/language-es_es": "100.4.0",
        "magento/language-fr_fr": "100.4.0",
        "magento/language-nl_nl": "100.4.0",
        "magento/language-pt_br": "100.4.0",
        "magento/language-zh_hans_cn": "100.4.0",
        "magento/framework": "103.0.0",
        "magento/framework-amqp": "100.4.0",
        "magento/framework-bulk": "101.0.0",
        "magento/framework-message-queue": "100.4.0",
        "trentrichardson/jquery-timepicker-addon": "1.4.3",
        "components/jquery": "1.11.0",
        "blueimp/jquery-file-upload": "5.6.14",
        "components/jqueryui": "1.10.4",
        "twbs/bootstrap": "3.1.0",
        "tinymce/tinymce": "3.4.7"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "extra": {
        "component_paths": {
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce_4"
        }
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "version": "2.3.5",
    "minimum-stability": "stable",
    "repositories": {
        "wyomind": {
            "type": "composer",
            "url": "https://repo.wyomind.com"
        },
        "dpd": {
            "type": "vcs",
            "url": "https://bitbucket.org/DPDinRussia/dpd.magento.git"
        },
        "composer":  {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "WYOMIND": {
            "type": "composer",
            "url": "https://repo.wyomind.com"
        }
    }
}

**Comment by ihor-sviziev** [comment]
Hi @apuc,
You're using github based installation that can't be updated with the composer, it have to be used only for Magento contributions, more details here https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html.

In case if you're using this type of magento installation in your production environment - I'm strongly recommend switch to composer based installation using metapackage https://devdocs.magento.com/guides/v2.4/install-gde/composer.html
