### ISSUE TITLE
Magento 2.4.1 Rewrite conflicts

### ISSUE THREAD

**Issue by perfpcs** [magento/magento2#30935]
### Preconditions (*)

Using the latest version of Magento 2.4.1 along with php 7.4.12 I am using the Mirasvit Health Monitor and it has identified at least 4 rewrite conflicts within this version of Magento. They are as follows:

1. Parent:Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Alerts\Stock---->Rewrite:Magento\InventoryProductAlert\Block\Adminhtml\Product\Edit\Tab\Alerts\Stock

2.  Parent:Magento\Catalog\Model\Product\Option\Type\Date------>Rewrite:Magento\Catalog\Model\Webapi\Product\Option\Type\Date

3. Parent:Magento\Framework\Mail\Template\SenderResolverInterface------> Rewrite:Magento\Email\Model\Template\SenderResolver

and since Dot Ditigital is built in and encouraged to use with this version of Magento:

4. Parent:Magento\Framework\Mail\Template\SenderResolverInterface------------->Rewrite:Dotdigitalgroup\Email\Model\Email\DotdigitalSenderResolver

### Steps to reproduce (*)

Since this is just a situation all I can do is report that the conflicts exist not reproduce any specific error. As I understand it, to have no conflicts within Magento, these rewrites should be merged into one file with the Parent extending the class and then deleting the other files.

### Expected result (*)

What is expexted is to not have any rewrite conflict. In order to do this what needs to happen is:

ClassA overrides Mage_Core_ClassX
ClassB overrides Mage_Core_ClassX

To fix this here is basic example of what needs to be done to avoid the conflict:

1. Remove the rewrite code in config.xml from any one of the modules (just comment it out). Lets say we remove the rewrite code in config.xml for ClassA

2. Next we will make ClassB extend ClassA

3. So finally ClassB extends ClassA , ClassA extends Mage_Core_ClassX

This helps to solve the conflict problem. But there is a big catch here, if ClassA and ClassB have defined same function inside their classes then the code written in ClassA will no longer be used. In such cases you need to manually merge the code written in ClassA and ClassB. To explain this better, lets assume
ClassA has a function getCustomerName() in it where some code is written.
ClassB also has the same function getCustomerName(), since ClassB now extends ClassA the code written in ClassA will become redundant. So you will have to copy/merge code from ClassA and put it in ClassB’s getCustomerName() function.

### Actual result (*)

What is actually happening is multiple files have been created in Magento that are rewritng classes and that should not be occurring. see results of Health monitor:

![image](https://user-images.githubusercontent.com/22109696/99285162-32f81a00-2805-11eb-8e8d-a592498807e7.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @perfpcs  thank you for your report. Looks like is not technical issue with visible wrong behavior but some points could be improve:
1. Parent:Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Alerts\Stock---->Rewrite:Magento\InventoryProductAlert\Block\Adminhtml\Product\Edit\Tab\Alerts\Stock
- Agree - rewrite conflict
2. Parent:Magento\Catalog\Model\Product\Option\Type\Date------>Rewrite:Magento\Catalog\Model\Webapi\Product\Option\Type\Date
- Semi agree - there is no conflict. Rewrites are in different areas of magento.
3. Parent:Magento\Framework\Mail\Template\SenderResolverInterface------> Rewrite:Magento\Email\Model\Template\SenderResolver
- Interface implementation.
4. Parent:Magento\Framework\Mail\Template\SenderResolverInterface------------->Rewrite:Dotdigitalgroup\Email\Model\Email\DotdigitalSenderResolver
- Rewrite from 3-rd party module.

Seems like it is better create issue in [community-features repo](https://github.com/magento/community-features/issues) as code improvement or feel free to create PR with appropriate fix

If you'd like to update the issue, please reopen it.
