### ISSUE TITLE
Perfomance:Cms/Model/Page/DataProvider.php#L103 loads full collection without any filter

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#30936]
###### (i) This ticket is created automatically based on a verified GitHub issue.        
{panel}
***If you are starting to work on this Jira ticket, please notify issue reporter and authors of related community pull requests (if any) that you are going to work on this issue:***
  1.  *Assign [#30936](https://github.com/magento/magento2/issues/30936) issue to yourself on Magento GitHub*
  2.  *Add comment "Internal Magento team is working on this issue right now."*
{panel}
######Preconditions (*)
1. Magento 2.4

######Steps to reproduce (*)
1. Set break ponit at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Page/DataProvider.php#L103
2. Open https://your*backend.com/admin/cms/page/edit/page*id/17

######Expected result (*)
1. Only curent page should be loaded

######Actual result (*)
1. All exiting pages are loaded in my case 1200

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40230` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
