### ISSUE TITLE
Products GraphQL query response inconsistent with results from Elasticsearch when sorting by price

### ISSUE THREAD

**Issue by webamMarko** [magento/magento2#30949]
### Preconditions (*)

1. Magento 2.4.1
2. Ubuntu 18.04
3. Mysql 5.7.31-34
4. nginx/1.14.0 (Ubuntu)
5. PHP 7.3.24
6. Elasticsearch 7.10.0 (running via docker docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.0)

### Steps to reproduce (*)

1. Install Magento Open Source 2.4.1
2. Install Venia Sample data as described: https://magento.github.io/pwa-studio/venia-pwa-concept/install-sample-data/
3. Add special price of 108 to product with entity_id 1126 - Isadora Skirt (special price is required on only one child product)
4. Run full reindex with bin/magento indexer:reindex
5. Perform the following query on the newly installed magento instance:
`query category($pageSize: Int!, $currentPage: Int!, $filters: ProductAttributeFilterInput!, $sort: ProductAttributeSortInput) {
 products(pageSize: $pageSize, currentPage: $currentPage, filter: $filters, sort: $sort) {
 items {
 id
 price {
                regularPrice {
                    amount {
                        currency
                        value
                    }
                }
                minimalPrice {
                    amount {
                        currency
                        value
                    }
                }
                maximalPrice {
                    amount {
                        currency
                        value
                    }
                }
            }
 }
 }
}`

with variables:

`{"id":16,"onServer":true,"pageSize":40,"currentPage":1,"filters":{"category_id":{"eq":"16"}},"sort":{"price":"ASC"}}`

Note the order of products returned by the graphql query.

6. Perform the following query against Elasticsearch (using the described enviroment a POST request to the following url: localhost:9200/magento2_product_1/_search):
`{
    "from": 0,
    "size": 40,
    "stored_fields": [
        "_id",
        "_score",
        "price_0_1"
    ],
    "sort": [
        {
            "price_0_1": {
                "order": "asc"
            }
        }
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "category_ids": "16"
                    }
                },
                {
                    "terms": {
                        "visibility": [
                            "2",
                            "4"
                        ]
                    }
                }
            ]
        }
    }
}`

Note the order of products. 

7. Compare the order of products in both cases. One can see that the product which was assigned the special price is in different positions in each query. 

### Expected result (*)

1. The order of products returned by the GraphQL query should be the same as the order of products returned by Elasticsearch and consistent.

### Actual result (*)

1. The queries return inconsistent ordering of products. The product where we changed the special price is in different positions. The sorting is happening in Elasticsearch so that information should be kept when performing queries on the mysql database as well. 

### Additional information
The code is implemented in a way where elasticsearch results are used only as a filter for product ids and an implicit sort (which mysql does not suppor!). The resulting mysql query looks like this:
`SELECT e.*, cat_index.position AS cat_index_position, IF(at_status.value_id > 0, at_status.value, at_status_default.value) AS status, IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS visibility FROM catalog_product_entity AS `e`
 INNER JOIN search_tmp_5fb3b718988463_53847207 AS search_result ON e.entity_id = search_result.entity_id
 INNER JOIN catalog_category_product_index_store1 AS cat_index ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.category_id=16
 INNER JOIN cataloginventory_stock_status AS stock_status_index ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN catalog_product_entity_int AS at_status_default ON (at_status_default.entity_id = e.entity_id) AND (at_status_default.attribute_id = '97') AND at_status_default.store_id = 0
 LEFT JOIN catalog_product_entity_int AS at_status ON (at_status.entity_id = e.entity_id) AND (at_status.attribute_id = '97') AND (at_status.store_id = 1)
 INNER JOIN catalog_product_entity_int AS at_visibility_default ON (at_visibility_default.entity_id = e.entity_id) AND (at_visibility_default.attribute_id = '99') AND at_visibility_default.store_id = 0
 LEFT JOIN catalog_product_entity_int AS at_visibility ON (at_visibility.entity_id = e.entity_id) AND (at_visibility.attribute_id = '99') AND (at_visibility.store_id = 1) WHERE (e.entity_id IN('1126', '1127', '1128', '1129', '1130', '1131', '1132', '1133', '1134', '1135', '1136', '1137', '1138', '1139', '1140', '1141', '1142', '1143', '1144', '1145', '1146', '1147', '1148', '1149')) AND (stock_status_index.stock_status=1)`

Note the lack of any kind of ORDER BY statement. This kind of "sorting" is unpredictable (a brief explanation is available here: https://dba.stackexchange.com/questions/6051/what-is-the-default-order-of-records-for-a-select-statement-in-mysql).

In an environment such as ours where we have hundreds to thousands of products in special promotion categories this kind of sorting causes major issues in combination with infinite scroll. In some situations we simply don't show some products and in some situations we show duplicates due to inconsistent sorting and therefor inconsistent results between GraphQL requests which are identical (same category, same page size, same current page and same sorting). 

 ### Current Workaround
To fix the issue we have made some rewrites of core code. Specifically:

- \Magento\Framework\Search\Adapter\Mysql\TemporaryStorage
Here we added a new auto increment primary key "sort" which provides a field that can be sorted to provide data in the order of insertion into the temporary table.
- \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier
Here we added ordering by the mentioned field into the query if no other order is set.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by webamMarko** [comment]
This is still an issue. Don't see what else I can contribute. Please let me know if you need more information.

**Comment by vmalyk** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @webamMarko,

We request you to please try to reproduce the issue in Magento 2.4-develop and let us know if this is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @webamMarko,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by PascalBrouwers** [comment]
In my case it was https://github.com/magento/magento2-pwa/blob/main/EavGraphQlAux/Plugin/ReorderNullAttributeValues.php who resets the ORDER BY if you have more than 1

**Comment by webamMarko** [comment]
@PascalBrouwers - for us the solution was to move from the category -> products field to products query with filtering by category id. I am not sure if the category -> products field is marked as deprecated at this time or if the issue was addressed at all.
