### ISSUE TITLE
Graphql - issue adding multiple configurable products to cart

### ISSUE THREAD

**Issue by calin-ImDigital** [magento/magento2#30948]
### Preconditions (*)

1. magento 2.3.4

### Steps to reproduce (*)

create a mutation for addConfigurableProductsToCart with multiple configurable products

### Expected result (*)

1. products added to cart

### Actual result (*)
{
  "errors": [
    {
      "message": "You need to choose options for your item.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 25,
          "column": 3
        }
      ],
      "path": [
        "addConfigurableProductsToCart"
      ]
    }
  ],
  "data": {
    "addConfigurableProductsToCart": null
  }
}
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nige-one** [comment]
I have the same issue. The problem is that in 
https://github.com/magento/magento2/blob/445b0f1a3d6a91b5da32d311077c2112ef0b1503/app/code/Magento/ConfigurableProductGraphQl/Model/Options/Collection.php#L100
the `!empty($this->attributeMap)` does not take into account the case of more then one Configurable Product's super attribute needs to be resolved.

**Comment by engcom-Bravo** [comment]
Hello @cdiacon-img 

Thank you for your report.

Can you please clarify, are you trying to add multiple Products with options using one mutation, or you are trying to add one single configurable product with multiple options?  
In any case, could you please provide a mutation example?

Thank you in advance

**Comment by cdiacon-img** [comment]
Hi @engcom-Bravo 

As I remember it was adding multiple products(cart items) with this mutation

```
mutation {
#   addConfigurableProductsToCart(
#     input: {
#       cart_id: "QZBii1Eu3vb5tOoGo94Rl9kcnquhc1Nf"
#       cart_items: [
#         {
#           data: {
#             quantity: 1
#             sku: "40012244"
#           },
#           parent_sku: "style-123"
            
#         },
#         {
#           parent_sku: "style-321"
#           data:{
#             quantity: 2
#             sku: "40023175"
#           }
          
#         }
#       ]
#     }
#   ) {
#     cart {
#       items {
#         id
#         product {
#           sku
#           stock_status
#         }
#         quantity
#       }
#     }
#   }
# }
```

**Comment by engcom-Bravo** [comment]
@cdiacon-img Thank you for the quick response.

This actually was the mutation we have tried to reproduce with. 
The difference is that we are getting a different error
```graphql
{
  "errors": [
    {
      "message": "Could not add the product with SKU Configurable2 to the shopping cart: Could not find specified product.",
      "extensions": {
        "category": "graphql-input"
```
This happens when we try to add two products. The _Configurable2_ itself is added to the Cart successfully.

**Comment by cdiacon-img** [comment]
@engcom-Bravo 

I am not sure why you are getting product not found but I guess you are hitting the condition of this test 

`testAddVariationFromAnotherConfigurableProductWithTheSameSuperAttributeToCart`

But in my case it was getting attribute data from wrong product
`You need to choose options for your item`

This is how we patched at the moment, I hope this helps : 

```
---
 vendor/magento/module-configurable-product-graph-ql/Model/Options/Collection.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/vendor/magento/module-configurable-product-graph-ql/Model/Options/Collection.php b/vendor/magento/module-configurable-product-graph-ql/Model/Options/Collection.php
index 36ee00d..c8bbe74 100644
--- a/vendor/magento/module-configurable-product-graph-ql/Model/Options/Collection.php
+++ b/vendor/magento/module-configurable-product-graph-ql/Model/Options/Collection.php
@@ -97,7 +97,7 @@ class Collection
      */
     private function fetch() : array
     {
-        if (empty($this->productIds) || !empty($this->attributeMap)) {
+        if (empty($this->productIds)) {
             return $this->attributeMap;
         }

--
```

**Comment by cdiacon-img** [comment]
This is the same thing that @nige-one pointed out above.

**Comment by engcom-Bravo** [comment]
Hello @cdiacon-img 

I'm still getting a different error than the reported.
The following mutation 
```graphql
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "nUdFfPMkIyC3vJS8I6K56Tk0zdPDUpco"
      cart_items: [
        { parent_sku: "Conf1", data: { quantity: 1, sku: "Conf1-white" } }
        { parent_sku: "Conf2", data: { quantity: 1, sku: "Conf2-s" } }
      ]
    }
  ) {
    cart {
      items {
        uid
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
          }
        }
      }
    }
  }
}
```
returns
```graphql
{
  "errors": [
    {
      "message": "Could not add the product with SKU Conf2 to the shopping cart: The product with SKU Conf2 is out of stock.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addConfigurableProductsToCart"
      ]
    }
  ],
  "data": {
    "addConfigurableProductsToCart": null
  }
}
```
It might be that on 2.4-develop the behavior is different. I noticed that you are reporting the issue on 2.3.4. Can you please verify if the issue is reproducible on 2.4-develop for you?

Thank you
