### ISSUE TITLE
Performance toolkit - generating fixtures gives error during customer template creation

### ISSUE THREAD

**Issue by igorwulff** [magento/magento2#30946]
### Preconditions (*)
Magento Commerce 2.4.1 installed through composer, but most likely other versions as well

### Steps to reproduce (*)
bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/ee/small.xml

### Expected result (*)
I except to have no error while generating the fixture.

### Actual result (*)
Error: Cannot generate entities - error occurred during template creation: Invalid value of "1" provided for the regionId field.

The getAddressTemplate method in setup/src/Magento/Setup/Model/FixtureGenerator/CustomerTemplateGenerator.php returns an static region_id value of 1 amonst other values. This region_id value of 1 does not exist when trying to select it in the Magento admin for the US country either. My database comes from a PII free dump from Magento Cloud from an original database setup by Magento Cloud.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ V ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by igorwulff** [comment]
I've replaced the region_id value to 3 in the CustomerTemplateGenerator.php as a workaround. Since 3 is the lowest available value for US states (Alabama) in the database.

After running the script again, I receive a new error also at the **generating customers** step:
The entity ID field for the "customer_address_entity_varchar" table wasn't found. Verify the field and try again.

This happens in vendor/magento/magento2-base/setup/src/Magento/Setup/Model/FixtureGenerator/EntityGenerator.php

Where a check is being made if the primary key field is actually set as a foreign key in other tables. 
(
    [CSTR_ADDR_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID] => Array
        (
            [FK_NAME] => CSTR_ADDR_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID
            [SCHEMA_NAME] => 
            [TABLE_NAME] => customer_address_entity_varchar
            [COLUMN_NAME] => attribute_id
            [REF_SHEMA_NAME] => 
            [REF_TABLE_NAME] => eav_attribute
            [REF_COLUMN_NAME] => attribute_id
            [ON_DELETE] => CASCADE
        )
    [CSTR_ADDR_ENTT_VCHR_ENTT_ID_CSTR_ADDR_ENTT_ENTT_ID] => Array
        (
            [FK_NAME] => CSTR_ADDR_ENTT_VCHR_ENTT_ID_CSTR_ADDR_ENTT_ENTT_ID
            [SCHEMA_NAME] => 
            [TABLE_NAME] => customer_address_entity_varchar
            [COLUMN_NAME] => entity_id
            [REF_SHEMA_NAME] => 
            [REF_TABLE_NAME] => customer_address_entity
            [REF_COLUMN_NAME] => entity_id
            [ON_DELETE] => CASCADE
        )
)

It seems to be assuming that entity_id should be a primary_key in customer_address_entity_varchar but in my database the value_id column is the primary key.

This fixture generation seems a mess... and it is unfortunately required for running the performance toolkit, which also doesn't seem to work out of the box.

**Comment by engcom-Bravo** [comment]
Hello @igorwulff 

Thank you for your report

I'm getting this error on my installation 
![rerformance_fixture_error](https://user-images.githubusercontent.com/51680745/100088249-7f240980-2e58-11eb-86ba-3176141a5297.png)

Is this the same error message you are experiencing?

Thank you

**Comment by igorwulff** [comment]
Hi @engcom-Bravo I had no issue in the FixtureConfig or any I/O warnings... perhaps an issue on your installation only?

My issue was an error during customer generation:
`The entity ID field for the "customer_address_entity_varchar" table wasn't found. Verify the field and try again.`

**Comment by engcom-Delta** [comment]
@igorwulff I am not able to reproduce issue on clean EE magento 2.4-develop
Manual testing scenario:
Install magento EE 2.4-develop
Run `bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/ee/small.xml`
**Result:**
:heavy_check_mark: Data generated succesfully
![image](https://user-images.githubusercontent.com/51681379/102346483-9497d980-3fa7-11eb-82f9-5a5b34062138.png)

Do you generate data on clean database or it contains some data?

**Comment by igorwulff** [comment]
I have now found that one of our modules with an plugin and an event is disturbing the generation. The weird thing is that it is just inserting data in the customer address entity during a save. So why would this conflict so much with the basic generation structure. I will look further into this, and hopefully this information is still helpful to others, but to continue we can disable the module while generation a fixture for now.

I suppose this issue can get closed now?

**Comment by engcom-Delta** [comment]
@igorwulff yes, I think we can close issue now
Please feel free to comment, reopen or create new ticket if additional information appears during your investigation. Thank you for collaboration.

**Comment by munkhulzii** [comment]
I still get this error with magento 2.4.2 when I run 
```
bin/magento setup:perf:generate-fixtures /magento/setup/performance-toolkit/profiles/ce/small.xml
```
