### ISSUE TITLE
Magento 2.4.1 doesn't display Cart Price Rule's description

### ISSUE THREAD

**Issue by ivan-prysiazhniuk** [magento/magento2#30954]
### Preconditions (*)

1. Pure Magento 2.4.1
2. PHP 7.4.12
3. Mysql - MariaDB 10.4.17
4. Elasticsearch 7.6.2
5. Server - Apache2 (2.4.29)
6. Installed Sample Data

### Steps to reproduce (*)

1. Create cart price rule in admin panel with this set of data and enable it:

> cart rule name: **5% (test)**
> description: **5% test description**
> websites: **Main Website**
> customer groups: **_all available_**
> coupon: **no**
> apply: **percent of product price discount**
> discount amount: **5**
> labels: **_leave empty_**
> 
> **other fields in not necessary.**

2. Go to the storefront catalog and add some product to the cart
3. Go to "View and Edit Cart"

### Expected result (*)

1. Title of discount total contains a description of the applied rule
![Screenshot from 2020-11-17 15-08-50](https://user-images.githubusercontent.com/39122839/99394303-55626400-28e7-11eb-9f5f-bc123b1fb9d8.png)

### Actual result (*)

1. Magento doesn't display the description of the created cart rule
![Screenshot from 2020-11-17 13-51-17](https://user-images.githubusercontent.com/39122839/99394460-9490b500-28e7-11eb-8c65-3b4b717d838b.png)
**_(Magento 2.4.1 displays Cart Price Rule's description if the rule created and applied as COUPON)_**
![Screenshot from 2020-11-17 17-57-09](https://user-images.githubusercontent.com/39122839/99413350-59e64700-28fe-11eb-9d56-e46e517a2651.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by p-ivanko** [comment]
@magento I am working on this

**Comment by p-ivanko** [comment]
@magento add to contributors team

**Comment by p-ivanko** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and is reproducible. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/205096073-79bc4cd2-1bf1-4074-82d4-f7591f81f5e2.png)
