### ISSUE TITLE
Empty space in prices when Bulgarian locale and Lev as currency used

### ISSUE THREAD

**Issue by nemke82** [magento/magento2#30958]
### Preconditions (*)

Magento 2.4-develop
Php 7.4
Mysql v8
Install latest Magento 2.4.x version

1. Go to Admin -> Stores --> Configuration --> General --> Locale Options put **Bulgarian**
2. Go to Currency set up under the General section and select Bulgarian Lev currency for Default Display currency and Base.
3. Install sample data or performance fixtures (https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-perf-data.html)  - bin/magento setup:perf:generate-fixtures /var/www/html/magento2/setup/performance-toolkit/profiles/ce/small.xml
--

### Steps to reproduce (*)
1. Go to Storefront;
2. Open any product page;

<span class="price">1&nbsp;5,17&nbsp;лв.</span>

![image](https://user-images.githubusercontent.com/22136088/99447564-8b233f00-291f-11eb-8236-e7a691abe673.png)

### Expected result (*)
1. It should show without &nbsp
2. Like this:
![image](https://user-images.githubusercontent.com/22136088/99448109-b017b200-291f-11eb-9ea5-94d2e7712367.png)

### Actual result (*)
1. Price showing with &nbsp;
2. <span class="price">1&nbsp;5,17&nbsp;лв.</span>
![image](https://user-images.githubusercontent.com/22136088/99447564-8b233f00-291f-11eb-8236-e7a691abe673.png)

I tried to apply charset from latin1 to utf8 still results are the same.

mysql> show variables like "character_set_database";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| character_set_database | utf8  |
+------------------------+-------+
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39185` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by robbie-thompson** [comment]
We've noticed this when using the Bulgarian locale with Euros, it doesn't seem specific to Lev.

**Comment by robbie-thompson** [comment]
Still relevant, as it's still reproducible on 2.4.2.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by miraclebg** [comment]
Experiencing the same thing - so far i am able to find out it is caused by javascript - if you disable it temporarily it shows just fine.

**Comment by miraclebg** [comment]
Issue seems to be coming from magento/zendframework1/library/Zend/Locale/Data/bg.xml, <pattern>#,##0.00 ¤</pattern>

I've overriden the \Magento\Framework\Locale\Format class like this - which fixes the problem for me:

```
<?php

namespace Nimasystems\Angro\CustomPriceFormat\Model;

class Format extends \Magento\Framework\Locale\Format
{
    public function getPriceFormat($localeCode = null, $currencyCode = null)
    {
        $d = parent::getPriceFormat($localeCode, $currencyCode);

        // remove the broken groupSymbol causing an empty space in the prices for BG
        $d['groupSymbol'] = '';

        return $d;
    }
}

```
