### ISSUE TITLE
Process Manager always exits successfully if the amount of functions(i.e. indexer dimensions) is lower than the MAGE_INDEXER_THREADS_COUNT env variable

### ISSUE THREAD

**Issue by pawel-siejba** [magento/magento2#30964]
Process Manager always exits successfully if the amount of functions passed to it(i.e. indexer dimensions) is lower than the MAGE*INDEXER_THREADS*COUNT env variable. Can cause the Index to think it was rebuilt successfully when in fact it wasn't.
### Preconditions (*)

1. Magento 2.3.0 CE/EE or higher
1. Magento 2.4-develop
1. Several stores are active, but less than MAGE*INDEXER_THREADS_COUNT(if MAGE_INDEXER_THREADS*COUNT=4, then the amount of stores active to reproduce this bug can be 3).
1. (Optional) Elasticsearch is configured as search_engine - for ease of reproducing

### Steps to reproduce (*)

1. Run `MAGE*INDEXER_THREADS_COUNT=4 php bin/magento indexer:reindex catalogsearch*fulltext`
1. Kill Elasticsearch process to simulate an exception thrown

### Expected result (*)

1. Main process exits with an error as child process failed.

### Actual result (*)

1. Observe "Catalog Search index has been rebuilt successfully"
```
xx@xx:/var/www/magento2$ MAGE*INDEXER_THREADS_COUNT=4 php bin/magento indexer:reindex catalogsearch*fulltext
Catalog Search indexer process unknown error:
Indexer handler is not available: elasticsearch7
Catalog Search indexer process unknown error:
Indexer handler is not available: elasticsearch7
Catalog Search indexer process unknown error:
Indexer handler is not available: elasticsearch7
Catalog search index has been rebuilt successfully in ...
```
(Sidenote) The duplicated error messages are already fixed in scope of https://github.com/magento/magento2/pull/30626
## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- <x] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39718` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
