### ISSUE TITLE
No data appread even after successful data migration

### ISSUE THREAD

**Issue by vcpawate** [magento/magento2#3096]
I am migrating magento from 1.9.0.1 to Magento 2.0.1, using Magento Data migration tool, 

Data migration tool executed with no error, but I cannot see any data in magento admin backend,

I have cleared cache, reindexed. I can see data in database, but no data appeared on Magento admin panel, 

Please help

**Comment by mazhalai** [comment]
@vcpawate please post this issue on https://github.com/magento/data-migration-tool-ce
