### ISSUE TITLE
On News letter Subcribe email template Error

### ISSUE THREAD

**Issue by mhafizumer** [magento/magento2#30962]
I have upgrade my store from magento 2.3.3 to 2.4.1, Everything is working except when I am subscribe news letter or create account for customer then It throw Error .

 **TypeError: Return value of Magento\Framework\Filter\DirectiveProcessor\TemplateDirective::process() must be of the type string, null returned in /var/www/html/vendor/magento/framework/Filter/DirectiveProcessor**

I have attach screenshot also

![image](https://user-images.githubusercontent.com/67052331/99503531-23f99f00-29a0-11eb-974d-26a52efe461f.png)

**Comment by engcom-Delta** [comment]
Hi @mhafizumer thank you for your report, I'm not able to reproduce issue by steps you described
Magento was upgraded from 2.3.6 to 2.4.1 according [Upgrade Magento](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html) documentation
**Result:**
:heavy_check_mark: Customer subscribes to newsletter without errors
![Screenshot from 2020-11-26 10-07-42](https://user-images.githubusercontent.com/51681379/100325523-74d94b00-2fd1-11eb-8b42-0ad074ae5454.png)

:heavy_check_mark: Customer is able create account without errrors

**Comment by engcom-Delta** [comment]
Hi @mhafizumer thank you for your report, I'm not able to reproduce issue by steps you described
Magento was upgraded from 2.3.6 (php7.3) to 2.4.1(php7.3) according [Upgrade Magento](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html) documentation. Also was checked newsletter subscribe and create customer account with php7.4 after magento upgrade
**Result:**
:heavy_check_mark: Customer subscribes to newsletter without errors
![Screenshot from 2020-11-26 10-07-42](https://user-images.githubusercontent.com/51681379/100325523-74d94b00-2fd1-11eb-8b42-0ad074ae5454.png)

:heavy_check_mark: Customer is able create account without errrors
![Screenshot from 2020-11-26 10-08-36](https://user-images.githubusercontent.com/51681379/100325560-80c50d00-2fd1-11eb-986a-5f1dacf4f9f5.png)

If you'd like to update the issue, please reopen it.
