### ISSUE TITLE
Variable $from not found :: only for specific search term

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#30979]
### Preconditions (*)

1. Magento 2.3.6 with elastic search
2. (if possible migrated from 2.3.3-p1)
3. Elasticsearch v 6

### Steps to reproduce (*)

1. Search for the specific term "Crestron"

### Expected result (*)

1. Show the normal search result

### Actual result (*)

1. Throws an error

`{"0":"Notice: Undefined variable: from in /vendor\/magento\/module-elasticsearch\/Elasticsearch5\/SearchAdapter\/Aggregation\/Interval.php on line 130","1":"#1 Magento\\Elasticsearch\\Elasticsearch5\\SearchAdapter\\Aggregation\\Interval->loadPrevious() called at [vendor\/magento\/framework\/Search\/Dynamic\/Algorithm.php:306]\n#2 Magento\\Framework\\Search\\Dynamic\\Algorithm->_findValueSeparator() called at [vendor\/magento\/framework\/Search\/Dynamic\/Algorithm.php:179]\n#3 Magento\\Framework\\Search\\Dynamic\\Algorithm->calculateSeparators() called at [vendor\/magento\/framework\/Search\/Dynamic\/Algorithm\/Improved.php:70]\n#4 Magento\\Framework\\Search\\Dynamic\\Algorithm\\Improved->getItems() called at [vendor\/magento\/module-elasticsearch\/SearchAdapter\/Aggregation\/Builder\/Dynamic.php:48]\n#5 `

Interestingly it happens to only this specific search term "Crestron". Everything else is working so far.

**On my further investigation, it looks like this is only happening to my specific instance, so I have to say, it will be hard to reproduce and please feel free to close this. However, before you close this, please have a look below:**

On this line, if `$lower` is null then the system will not have `from` and `to` variables `. Then it will fail to execute the below line of code:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php#L130

It should have `$from = $to = [];` at the beginning of the function's body so that it always finds the `$from and $to` variables like this: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php#L94

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
A temporary workaround is to add a redirection to the search term to something similar, maybe `Crestro`.

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @adarshkhatri  I'm not able to reproduce issue by steps you described on clean 2.4-develop with [Elasticsearch 7.6.x](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#elasticsearch)
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php is not used by elasticsearch7 and issue should not be reproducible on the latest magento version

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by rani-webkul** [comment]
In my case I changed the value of **Price Navigation Step Calculation** to “Automatic (equalize price ranges)" then it is working..
![image](https://user-images.githubusercontent.com/44425160/105921371-c5ffcc80-605e-11eb-9b79-72a117d6c77c.png)

**Comment by nvncbl** [comment]
> ... Elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php is not used by elasticsearch7 and issue should not be reproducible on the latest magento version

I am finding this is not the case.  The file vendor/magento/module-elasticsearch-7/etc/di.xml.  The argument "elasticsearch7" to "intervals" is the Elasticsearch5 class

<item name="elasticsearch7" xsi:type="string">Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Aggregation\Interval</item>

**Comment by timelam** [comment]
> In my case I changed the value of **Price Navigation Step Calculation** to “Automatic (equalize price ranges)" then it is working.. ![image](https://user-images.githubusercontent.com/44425160/105921371-c5ffcc80-605e-11eb-9b79-72a117d6c77c.png)


I was getting the following error with Elasticsearch 7, but only for certain categories. Your solution fixed the problem. Thanks!

main.CRITICAL: Notice: Undefined variable: from in vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php on line 130

**Comment by mobweb** [comment]
Also getting this error on the latest version, using ES7. When looking at the code of that _loadPrevious_ method, it seems obvious that something is wrong, because _$lower_ may be NULL, but in that case a PHP warning will always be triggered because the _$to_ variable won't be set a few lines down, but it is always used, even if it has not been set above.

**Comment by adarshkhatri** [comment]
It is still happening. and yes, changing the confi fixes it but my business won't allow me to change that. 

Why won't Magento fix it?
