### ISSUE TITLE
Using concrete class instead of abstraction

### ISSUE THREAD

**Issue by madonzyaccenture** [magento/magento2#30984]
Hello everyone, are there any plans to replace realizations with interfaces (ex: Product model, etc.)? Now it's impossible to extend models by composition.

**Comment by engcom-Delta** [comment]
Hi @madonzyaccenture  thank you for your report
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) for general discussion about this issue.
