### ISSUE TITLE
Getting Extra/Duplicate credit memo  

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#30987]
### Preconditions (*)

1.Magento version 2.3.5

### Steps to reproduce (*)

1.Configure the postman
2.Make an API call using the below details
API : rest/V1/creditmemo
Request : searchCriteria[filter_groups][0][filters][0][field]=order_id&searchCriteria[filter_groups][0][filters][0][value]=14

### Expected result (*)

1. We are getting extra credit memo which is not on UI of magento. it seems to be duplicate credit memo.   
2. There are two refunds are coming whereas is only one refund 

### Actual result (*)

1. We are getting two credit memo 
Response: {
    "items": [
        {
            "created_at": "2019-09-02 14:44:10",
            "email_sent": 0,
            "entity_id": 84,
            "grand_total": 215,
            "increment_id": "000000077",
            "order_id": 14,
            "shipping_amount": 10,
            "state": 2,
            "subtotal": 205,
            "tax_amount": 0,
            "updated_at": "2019-09-02 14:44:10",
            "items": [],
            "comments": [
                {
                    "comment": "visiable",
                    "created_at": "2019-09-02 14:45:02",
                    "entity_id": 12,
                    "is_customer_notified": 0,
                    "is_visible_on_front": 1,
                    "parent_id": 84
                }
            ]
        },
        {
            "base_grand_total": 215,
            "created_at": "2019-09-02 14:49:46",
            "email_sent": 0,
            "entity_id": 85,
            "grand_total": 215,
            "increment_id": "000000078",
            "order_id": 14,
            "shipping_amount": 10,
            "state": 2,
            "subtotal": 205,
            "tax_amount": 0,
            "updated_at": "2019-09-02 14:49:46",
            "items": [],
            "comments": []
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "order_id",
                        "value": "14",
                        "condition_type": "eq"
                    }
                ]
            }
        ]
    },
    "total_count": 2
}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @webgility-amazonapi thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: One credit memo in response:
```
{
    "items": [
        {
            "adjustment": 0,
            "adjustment_negative": 0,
            "adjustment_positive": 0,
            "base_adjustment": 0,
            "base_adjustment_negative": 0,
            "base_adjustment_positive": 0,
            "base_currency_code": "USD",
            "base_discount_amount": 0,
            "base_grand_total": 0,
            "base_discount_tax_compensation_amount": 0,
            "base_shipping_amount": 0,
            "base_shipping_incl_tax": 0,
            "base_shipping_tax_amount": 0,
            "base_subtotal": 0,
            "base_subtotal_incl_tax": 0,
            "base_tax_amount": 0,
            "base_to_global_rate": 1,
            "base_to_order_rate": 1,
            "billing_address_id": 8,
            "created_at": "2020-11-20 10:30:31",
            "discount_amount": 0,
            "entity_id": 1,
            "global_currency_code": "USD",
            "grand_total": 0,
            "discount_tax_compensation_amount": 0,
            "increment_id": "000000001",
            "order_currency_code": "USD",
            "order_id": 5,
            "shipping_amount": 0,
            "shipping_incl_tax": 0,
            "shipping_tax_amount": 0,
            "state": 2,
            "store_currency_code": "USD",
            "store_id": 1,
            "store_to_base_rate": 0,
            "store_to_order_rate": 0,
            "subtotal": 0,
            "subtotal_incl_tax": 0,
            "tax_amount": 0,
            "updated_at": "2020-11-20 10:30:31",
            "items": [
                {
                    "base_cost": null,
                    "base_discount_tax_compensation_amount": 0,
                    "base_price": 0,
                    "base_price_incl_tax": 0,
                    "base_row_total": 0,
                    "base_row_total_incl_tax": 0,
                    "base_tax_amount": 0,
                    "base_weee_tax_row_disposition": 0,
                    "entity_id": 1,
                    "discount_tax_compensation_amount": 0,
                    "name": "Downloadable",
                    "order_item_id": 5,
                    "parent_id": 1,
                    "price": 0,
                    "price_incl_tax": 0,
                    "product_id": 3,
                    "qty": 1,
                    "row_total": 0,
                    "row_total_incl_tax": 0,
                    "sku": "Downloadable",
                    "tax_amount": 0,
                    "weee_tax_applied": "[]",
                    "weee_tax_applied_row_amount": 0,
                    "weee_tax_row_disposition": 0
                }
            ],
            "comments": []
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "order_id",
                        "value": "5",
                        "condition_type": "eq"
                    }
                ]
            }
        ]
    },
    "total_count": 1
}
```

If you'd like to update the issue, please reopen it.
