### ISSUE TITLE
Opinion: URL Rewrite management should be read only for users and not considered a redirect tool

### ISSUE THREAD

**Issue by aliomattux** [magento/magento2#30989]
**Description**:
Magento 2 provides out of box a tool under Marketing > SEO & Search > URL Rewrites. This tool allows anyone with access to delete any URL, including system generated URL's. It also is intended to allow users to create custom redirects.

**Opinion**: this tool cannot be used as intended. This tool should become readonly and not changeable by users. Magento should introduce a new storage and delivery system for redirects.

**Why? Several reasons**
1. There is a constraint that each URL be unique. This alone eliminates the ability to redirect a product from A to B. When you create a product, a URL is generated for the system in url_rewrite for the product and every combination of category. The format is request_url = url_key, and target = catalog/product/id, etc. Because the system generates this URL, it is impossible to redirect the url to any other location due to constraint. If you attempt to create a custom redirect, you will receive an error that the request path already exists. 
This forces users to either delete the system URL which is improper and should not be allowed, or to go around Magento and use a webserver redirect. Note that business process for redirects varies greatly depending on company practice. Some companies would leave the URL available and say not available for purchase, some companies would make the page 404, and others would redirect that request to either another product or a category/landing page. The greatest flexibility is to create a request url and target url.

2. If a user deletes the system url, and saves either ANY category that the product is associated with or the product itself, the system will attempt to regenerate the URL and prevent the user from saving. The same problem can happen if the user creates a URL redirect and then later attempts to change the category or product url to match. Some of these are practice issues, however the system "allows" this behavior. The user is not aware they may have created a problem. This creates a "Nightmare" scenario for developers as users will repeatedly report problems and inability to save. Each URL issue must be investigated.

### Preconditions (*)
Version: 2.3.3, probably all versions

### Steps to reproduce (*)
1. Create product A. Assign to category A. Save product
2. Create redirect from A to B. Error is received and cannot create redirect

1. Delete system url redirect
2. Create custom url redirect
3. Save category or product with no changes
Error is received

### Actual result (*)

1. Allow users to create 301 redirects for products no longer sold
2. Do not allow users to delete system urls arbitrarily

**The tool is marketed as an SEO tool, but it is a critical part of the core program!**

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @aliomattux thank you for your report.
Looks like it is not an issue as you could  restrict access for URL Rewrites using User Roles
**Manual testing scenario:**
- Create new user role with unchecked URL Rewrites
![image](https://user-images.githubusercontent.com/51681379/106755295-a3f5e380-6636-11eb-98a1-a5a2d797bf36.png)
- Create new admin user and assign him to appropriate user role
![image](https://user-images.githubusercontent.com/51681379/106755458-d56eaf00-6636-11eb-95a1-ba185758b543.png)
- Login as new admin user

**Result:**
:heavy_check_mark: URL Rewrites is not shown 
![image](https://user-images.githubusercontent.com/51681379/106754880-2af68c00-6636-11eb-9712-9077bbce5396.png)


Is `User Roles` functionality not enough for your purpose?

**Comment by aliomattux** [comment]
Hello,

You can go ahead and close the ticket, but to answer your question, no
permissions do not solve the issue. My feedback was Magento rewrite system
functionality is incompatible with how standard practice is carried out for
redirects. I believe the feature of redirect is mislabeled. See my original
post for details.
