### ISSUE TITLE
There are no options for the bundle products in the wishlist

### ISSUE THREAD

**Issue by soleksii** [magento/magento2#30980]
### Preconditions (*)

1. Magento 2.4-develop;
2. Php 7.3;
3. Mysql 8;
4. Sample Data;

### Steps to reproduce (*)

1. Login as a customer on Storefront;
2. Go to Gear -> Fitness Equipment;
3. Open **Sprite Yoga Companion Kit** product page;
4. Customize Sprite Yoga Companion Kit an click on the **Add to Wishlist** button

### Expected result (*)

1. [Screenshots, logs or description]
2. The bundle product should be with pre-selected options in the wishlist

### Actual result (*)

1. There are no options for the bundle products in the wishlist
![Screenshot from 2020-11-19 10-32-28](https://user-images.githubusercontent.com/44244273/99641297-bfe3e300-2a52-11eb-8e41-0abaf6d52c45.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39183` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by milindsingh** [comment]
@magento I am working on this

**Comment by engcom-Foxtrot** [comment]
Closing as fix already merged https://github.com/magento-engcom/magento2ce/pull/4111.

**Comment by sukeshini-kot** [comment]
> Closing as fix already merged https://github.com/magento-engcom/magento2ce/pull/4111.

This link is not accessible anymore
