### ISSUE TITLE
The Magento_CurrencySymbol module contains not only the «Currency Symbols» functionality but the «Currency Rates» functionality too which is inconsistent with the module name

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3098]
https://mage2.pro/t/372

**Comment by palamar** [comment]
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
