### ISSUE TITLE
Magento export products: I'm not able to download the .csv file 

### ISSUE THREAD

**Issue by birdawn** [magento/magento2#30999]
### Magento 2.3.5 with cron job running 

 Once I ask for export the products is prompt:  ✔️Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file.

Cron use to work properly, I guess one the file it is show at the bottom is ready to download. Well just I suppose is created. In the second image, show the file path but I can't find it.
Appreciate any help to solve my issue, thank you in advance, Juan 

![Captura de pantalla 2020-11-20 a las 17 41 08](https://user-images.githubusercontent.com/19686207/99826026-171fab80-2b58-11eb-94d6-b9e44cefbec2.png)
![Captura de pantalla 2020-11-20 a las 17 41 34](https://user-images.githubusercontent.com/19686207/99826028-18e96f00-2b58-11eb-94ce-16a4775c0053.png)

**Comment by moazzama** [comment]
> ### Magento 2.3.5 with cron job running
> Once I ask for export the products is prompt: ✔️Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file.
> 
> Cron use to work properly, I guess one the file it is show at the bottom is ready to download. Well just I suppose is created. In the second image, show the file path but I can't find it.
> Appreciate any help to solve my issue, thank you in advance, Juan
> 
> ![Captura de pantalla 2020-11-20 a las 17 41 08](https://user-images.githubusercontent.com/19686207/99826026-171fab80-2b58-11eb-94d6-b9e44cefbec2.png)
> ![Captura de pantalla 2020-11-20 a las 17 41 34](https://user-images.githubusercontent.com/19686207/99826028-18e96f00-2b58-11eb-94ce-16a4775c0053.png)

use PHP bin/magento deploy:mode:set developer
chmod -R 777 pub ; chmod -R 777 app ; chmod -R 777 var ; chmod -R 777 generated 
then try it

**Comment by birdawn** [comment]
@moazzama Thank you, it is safe set all this folders with this permissions or is just for try ?

**Comment by moazzama** [comment]
> @moazzama Thank you, it is safe set all this folders with this permissions or is just for try ?

Just try only these folders
PHP bin/magento cron:run
PHP bin/magento deploy:mode:set developer
chmod -R 777 pub ; chmod -R 777 app ; chmod -R 777 var ; chmod -R 777 generated

**Comment by engcom-Alfa** [comment]
Hi @birdawn . Thank you for your report.
Unfortunately, we are not able to reproduce the issue on clean 2.4-develop and on 2.4.1.

![Peek 2020-11-23 09-57](https://user-images.githubusercontent.com/51679138/99939280-63dece80-2d72-11eb-90af-f1fffe2d64ee.gif)

This may be due to a problem with permissions. Please take a look for [File systems access permissions](https://devdocs.magento.com/guides/v2.4/config-guide/prod/prod_file-sys-perms.html)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by birdawn** [comment]
@engcom-Alfa engcom-Alfa Thank you very much, Magento can't access to some folders and files because permissions and group was incorrect, the owner of this files was root, I guess the administrator of hosting did something wrong.
Already I ask for change the permissions to Magento user and everything works.

Thank you very much to all people who reply and try to help me in this issue.
I would like to remark that the solution isn't change the permissions to 777 because this make security vulnerable.
The issue is solved.
