### ISSUE TITLE
Validating VAT Number on Admin Order Creation screen wipes shipping address when customer group changes.

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#30994]
### Preconditions (*)

2.4-develop

### Steps to reproduce (*)

```
- BACKEND

-- Customers
--- All Customers
---- Add New Customer
----- First Name = Test
----- Last Name = Test
----- Email = test@test.com
----- Save Customer

-- Catalog -> Products -> Add Product
--- Name = Test
--- Sku = TEST
--- Price = 100
--- Tax Class = Taxable Goods
--- Qty = 100
--- Save & Close

-- Stores -> Tax Zones and Rates -> Add New Tax Rate
--- Tax Identifier = Ireland Zero Rate
--- Zip Postcode = *
--- Country = Ireland 
--- Rate = 0
--- Save Rate

-- Stores -> Tax Rules -> Add New Tax Rule
--- Name = Ireland Zero Rate
--- Tax Rate = Ireland Zero Rate
--- Additional Settings
---- Add New Tax Class
----- Domestic
---- Add New Tax Class
----- VAT Error
---- Add New Tax Class
----- Invalid VAT
---- Add New Tax Class
----- Intra EU
--- Customer TAX Class = Intra EU (Deselect all others)
--- Save

-- Customers -> Customer Group -> Add New Customer Group
--- Group Name = Domestic
--- Tax Class = Domestic
--- Save Customer Group

-- Customers -> Customer Group -> Add New Customer Group
--- Group Name = Invalid VAT
--- Tax Class = Invalid VAT
--- Save Customer Group

-- Customers -> Customer Group -> Add New Customer Group
--- Group Name = VAT Error
--- Tax Class = VAT Error
--- Save Customer Group

-- Customers -> Customer Group -> Add New Customer Group
--- Group Name = Intra EU
--- Tax Class = Intra EU
--- Save Customer Group

-- Store -> Configuration -> Customers -> Customer Configuration -> Create new account options
--- Enable Automatic Assignment to Customer Group = Yes
--- Tax Calculation Based On = Shipping Address
--- Group for Valid VAT ID - Domestic = Domestic
--- Group for Valid VAT ID - Intra-Union = Intra EU
--- Group for Invalid VAT ID = Invalid VAT
--- Validation Error Group = VAT Error
--- Validate on Each Transaction = Yes
--- Show VAT Number on Storefront = Yes
--- Save Config

-- Store -> Configuration -> Customers -> Customer Configuration -> Name and Address Options
--- Show Tax/VAT Number = Optional
--- Save Config

-- Store -> Configuration -> General -> General -> Store Information
--- Country = United Kingdom
--- VAT Number = GB782325424 (This is ebay UK's vat number)
--- Save Config

--- Sales -> Orders -> Create New Order
---- Select "Test Test"
---- Click Add Products
---- Select Test and hit "Add Selected Products to Order"
---- First Name = "Billing"
---- Last Name = "Address"
---- Street Address = "Street"
---- Country = "Ireland"
---- City = "City"
---- Phone Number = "1234"
---- VAT Number = "IE3206488LH" (Stripes VAT Number)
---- Click "Validate VAT Number"
---- Click "OK" on the warning displayed asking you to change Customer Group to Intra EU
```

### Expected result (*)

1. Group should be changed to Intra-EU
2. Rest of fields on form should be unchanged

### Actual result (*)

1. The whole shipping address is wiped.

![Peek 2020-11-20 11-52](https://user-images.githubusercontent.com/51679138/99787311-41f20b80-2b28-11eb-8611-847ff4236200.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39285` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
I think whats going on is that when either the "Validate VAT Number" link is clicked, or the "Customer Group" dropdown is changed, the forms content is refreshed and redrawn using the contents of the $quote object which will probably have empty address objects. However when either of these two events are triggers, the current contents of the form are not saved in the quote and are lost when it is refreshed.

**Comment by gwharton** [comment]
Is this the bug

reset_shipping is set true when the address field being modified is a billing address field, and Shipping is the same as Billing, or if the field being edited is a shipping address field. That makes sense.
https://github.com/magento/magento2/blob/2cf043303b61423eaaadc5a095b83bdcf6443a6b/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L264-L271

But here, Whenever a field on the form is edited, the form data is only ever sent to the backend and updated in the quote object when reset_shipping is false..... Huh?
https://github.com/magento/magento2/blob/2cf043303b61423eaaadc5a095b83bdcf6443a6b/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L291-L299

Seems the correct approach should be
```
if (data['reset_shipping']) {
    this.resetShippingMethod();
}

this.saveData(data);
if (name === 'country_id' || name === 'customer_address_id') {
    this.loadArea(['shipping_method', 'billing_method', 'totals', 'items'], true, data);
}
```
With this mod running locally, I can confirm that after every field change, the quote object is updated. and if any changes cause the form to be refreshed, i.e VAT validation, or customer group change, the correct data is loaded back into the form.

**Comment by gwharton** [comment]
```
https://github.com/magento/magento2/issues/30994
@package magento/module-sales
--- view/adminhtml/web/order/create/scripts.orig.js	2020-11-20 12:35:00.703278519 +0000
+++ view/adminhtml/web/order/create/scripts.js	2020-11-20 12:34:10.759542518 +0000
@@ -290,12 +290,11 @@

             if (data['reset_shipping']) {
                 this.resetShippingMethod();
-            } else {
-                this.saveData(data);
+            }
+            this.saveData(data);

-                if (name === 'country_id' || name === 'customer_address_id') {
-                    this.loadArea(['shipping_method', 'billing_method', 'totals', 'items'], true, data);
-                }
+            if (name === 'country_id' || name === 'customer_address_id') {
+                this.loadArea(['shipping_method', 'billing_method', 'totals', 'items'], true, data);
             }
         },
```

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this.

**Comment by chiranjeevi-cj** [comment]
@magento give me 2.4-develop instance
