### ISSUE TITLE
Error while moving categories with partially matching path

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2#30997]
### Preconditions (*)

1. Magento 2.4-develop
2. Magento 2.3.x, 2.4.x

### Steps to reproduce (*)

1. You must have one category with _entity_id_=**134** and _url_path_=**1/2/134**
2. You must have a second category with _entity_id_=**1347** and _url_path_=**1/2/1347**
3. Try moving category **134** inside category **1347**
Send **PUT** request on `/V1/categories/{category_id}/move`

### Expected result (*)

1. Moving the category was completed successfully

### Actual result (*)

1. You will see an error with the message **Operation do not allow to move a parent category to any of children category**

![Swagger result](https://user-images.githubusercontent.com/51679138/100103083-1c893880-2e6d-11eb-8031-a1250b420949.png)

### Additional details (*)
1. the issue is an incorrect comparison of category paths by entry position [\Magento\Catalog\Model\CategoryManagement](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/CategoryManagement.php#L132)
2. Possible solution
```patch
--- Model/CategoryManagement.php	(date 1605797070514)
+++ Model/CategoryManagement.php	(date 1605797070515)
@@ -129,7 +129,7 @@
         }
         $parentPath = $parentCategory->getPath();
         $path = $model->getPath();
-        if ($path && strpos($parentPath, $path) === 0) {
+        if ($path && empty(array_diff(explode('/', $path), explode('/', $parentPath)))) {
             throw new \Magento\Framework\Exception\LocalizedException(
                 __('Operation do not allow to move a parent category to any of children category')
             );
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @DmitryFurs.
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

### The first way

**Manual testing scenario:**

1. You must have one category with **entity_id=134** and **url_path=1/2/134**
2. You must have a second category with **entity_id=1347** and **url_path=1/2/1347**
`catalog_category_entity`
![Screenshot from 2020-11-20 13-58-07](https://user-images.githubusercontent.com/51679138/99797740-7ec5fe80-2b38-11eb-9fc7-4b927433c0a3.png)
3. Try moving category **134** under category **1347**

**Actual Result:** :heavy_check_mark: Moving the category was completed successfully

![Peek 2020-11-20 14-00](https://user-images.githubusercontent.com/51679138/99797903-c2206d00-2b38-11eb-98e8-1ad3b9498ce9.gif)


### The second way

**Manual testing scenario:**

1. You must have one category with **entity_id=134** and **url_path=1/2/134**
2. You must have a second category with **entity_id=1347** and **url_path=1/2/1347**
`catalog_category_entity`
![Screenshot from 2020-11-20 13-58-07](https://user-images.githubusercontent.com/51679138/99797740-7ec5fe80-2b38-11eb-9fc7-4b927433c0a3.png)
3. `catalogCategoryManagementV1`
Send **PUT** request `/V1/categories/{categoryId}/move`

![Screenshot from 2020-11-20 13-38-40](https://user-images.githubusercontent.com/51679138/99798139-204d5000-2b39-11eb-81f0-6012c6e98f98.png)

**Actual Result:** :heavy_check_mark: Moving the category was completed successfully

![Screenshot from 2020-11-20 13-53-02](https://user-images.githubusercontent.com/51679138/99798191-3e1ab500-2b39-11eb-9afa-67c5f7762b03.png)
![Screenshot from 2020-11-20 13-52-53](https://user-images.githubusercontent.com/51679138/99798204-45da5980-2b39-11eb-961b-0a6fb95dbf74.png)

@DmitryFurs Could you take a look?
Thanks!

**Comment by DmitryFurs** [comment]
@engcom-Alfa sorry. when I wrote **under**, I meant **inside** so that the category path structure becomes **1/2/1347/134**

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39330` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by DmitryFurs** [comment]
The issue is still relevant.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
