### ISSUE TITLE
XML Sitemap contains non-canonical URLs

### ISSUE THREAD

**Issue by redinn** [magento/magento2#3099]
Sitemap.xml has been genetated, but contains non-canonical product links.

For instance few lines from sitemap.xml:
http://mysite.com/women/tops-women/tanks-women/zoe-tank  (full path, non-canonical)
http://mysite.com/nora-practice-tank (canonical)

All sitemap links should be equal to the canonical product links

Could someone please have a look at it.

**Comment by shiftedreality** [comment]
@redinn thank you for reporting. Internal ticket MAGETWO-50495 was created.

**Comment by shiftedreality** [comment]
Fix merged with 9bf93a3fc6da720da989607916b92301e4af6a57
Closed
