### ISSUE TITLE
Cannot get fresh install pages to work unless --use-rewrites=0

### ISSUE THREAD

**Issue by briand617** [magento/magento2#31006]
### Preconditions (*)

1.  2.4.0
2.

### Steps to reproduce (*)

1.  Fresh install on Ubuntu 20, Apache 2.4, MySQL 8, PHP 7.4 using "magento setup:install ... --use-rewrites=1"
2. Made sure to change the apache2.conf appropriately and that mod_rewrites was installed

### Expected result (*)

1. Expected to go to http://mydomain.com/Magento2/ and reach homepage
2. Expected to go to http://mydomain.com/Magento2/admin_<provided> and reach admin login

### Actual result (*)

1. Reached a Magento "Whoops our bad" page in both cases, with all the appropriate Magento styling applied
2.  Was able to see the home page using http://mydomain.com/Magento2/index.php, but none of the other links on the page worked because of the lack of index.php in the URLs.
3. Apparently the rewriting is not working appropriately.  I confirmed that the Apache mod_rewrite works, because when I go to http://mydomain.com/Magento2 and remove pub/index.php, I get a Apache 404 page.  So it is hitting the pub/index.php in order to create the Magento Whoops page.
4. Reinstalled with --use-rewrites=1 and was able to reach http://mydomain.com/Magento2/index.php and all the contained links worked, and was able to login to admin at http://mydomain.com/Magento2/index.php/admin_<provided> and reach admin login

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @briand617 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Case 1:**
Install magento with `-use-rewrites=0`:
```
php bin/magento setup:install --base-url=http://magento2dev.loc/ \
--db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" \
--admin-firstname=Magento --admin-lastname=User --admin-email=maguser@yopmail.com  --backend-frontname=admin \
--admin-user=admin --admin-password=123123q --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=0 \
--search-engine elasticsearch7 --elasticsearch-host localhost --elasticsearch-port 9200 \
--elasticsearch-index-prefix magento2dev --elasticsearch-timeout 15 
```
:heavy_check_mark: : Result on home page:
![image](https://user-images.githubusercontent.com/51681379/99963787-fa26ea80-2d9a-11eb-9dd1-c14b9d950b55.png)
:heavy_check_mark: Result on admin page:
![image](https://user-images.githubusercontent.com/51681379/99964591-3444bc00-2d9c-11eb-8184-44b4f13f63f1.png)

**Case 2:**
Install magento with `-use-rewrites=1`:
```
php bin/magento setup:install --base-url=http://magento2dev.loc/ \
--db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" \
--admin-firstname=Magento --admin-lastname=User --admin-email=maguser@yopmail.com  --backend-frontname=admin \
--admin-user=admin --admin-password=123123q --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine elasticsearch7 --elasticsearch-host localhost --elasticsearch-port 9200 \
--elasticsearch-index-prefix magento2dev --elasticsearch-timeout 15 
```
:heavy_check_mark: : Result on home page:
![image](https://user-images.githubusercontent.com/51681379/99965605-c00b1800-2d9d-11eb-893e-cfac6061f28d.png)
:heavy_check_mark: Result on admin page:
![image](https://user-images.githubusercontent.com/51681379/99965746-f3e63d80-2d9d-11eb-9239-f605fc654a47.png)

Please check your [web server](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/apache.html) configuration: virtual host and hosts files.

If you'd like to update the issue, please reopen it.

**Comment by briand617** [comment]
I will provide my exact steps to reproduce:

cd /var/www/html
git clone https://github.com/Magento/Magento2.git
cd Magento2
composer install
chmod -R 755 /var/www/html/Magento2/
chmod -R 777 /var/www/html/Magento2/var/
chmod -R 777 /var/www/html/Magento2/pub/
chmod -R 777 /var/www/html/Magento2/app/etc
chmod -R 777 /var/www/html/Magento2/generated
systemctl restart apache
<created database magento>
su www-data -s /bin/bash
export PATH=$PATH:/var/www/html/Magento2/bin
magento module:disable Magento_Elasticsearch Magento_Elasticsearch6 Magento_Elasticsearch7
magento setup:install --base-url=http://localhost/Magento2/ --db-host=localhost --db-name=magento --db-user=magento --db-password=pass --admin-firstname=Admin --admin-lastname=User --admin-email=brian@brevitywebsolutions.com --admin-user=admin --admin-password=pass --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1

When I went to http://localhost/Magento2, I got an Apache URL not found error.  So I modified the Magento root .htaccess file to be:

RewriteEngine on
RewriteCond %{REQUEST_URI} !^/Magento2/pub/
RewriteCond %{REQUEST_URI} !^/Magento2/setup/
RewriteCond %{REQUEST_URI} !^/Magento2/update/
RewriteCond %{REQUEST_URI} !^/Magento2/dev/
RewriteRule .* /Magento2/pub/$0 [L]
DirectoryIndex index.php

I then went to http://localhost/Magento2 and go
![whoops](https://user-images.githubusercontent.com/15182529/99981216-bae2a480-2d6e-11eb-86d7-b8711d946391.jpg)
t the attached screen

My apache2.conf settings for this environment are:

<Directory /var/www/html/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
</Directory>

**Comment by engcom-Delta** [comment]
@briand617 seems like apache is misconfigured. You could try create one Apache virtual host per Magento website as in [docs](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_apache.html#ms-apache-vhosts)
