### ISSUE TITLE
CMS Page saving fails with "The value specified in the URL Key field would generate a URL that already exists."

### ISSUE THREAD

**Issue by frostblogNet** [magento/magento2#31007]
### Preconditions (*)

1. 2.3.6
2. 2.4.1

Note: 2.4.0 is not affected.

### Steps to reproduce (*)

1. Create a magento installation with 2 storeview (f.e. uk, us) 
2. Go to Stores -> Configuration -> General -> Web and set "Add Store Code to URls" to Yes
3. Go to Content -> Pages and Create a CMS Page with the identifier "privacy" in the scope of the uk storeview.
4. Now create a CMS Page with the identifier "privacy" in the scope of the us storeview.

### Expected result (*)

1. saving both cms page with the same identifier is possible due to the fact that the url is still uniqe
https://example/uk/privacy vs. https://example/us/privacy

### Actual result (*)

1. it is not possible to save the secound cms page.
2. You will see this error in the backend "The value specified in the URL Key field would generate a URL that already exists."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The problem here is a new validator in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/PageRepository.php#L193. This validator is only checking if there is a CMS Page with the same identifier in the hole frontend scope not the scope itself. This works in a single store / storeview shop but not in a multi store / languarge store.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/PageRepository.php#L308

**Comment by engcom-Bravo** [comment]
Hello @frostblogNet 

Thank you for your report.

We are not able to reproduce the reported issue using the provided steps on Magento 2.4.1 and 2.4-develop

We have created two Store Views, _US_ and _UK_ 
![uk_us_views](https://user-images.githubusercontent.com/51680745/99983571-b0e39480-2db4-11eb-9493-12ab86cda591.png)
 and set **Add Store Code to Urls** to **Yes**
![add_store_code_yes](https://user-images.githubusercontent.com/51680745/99984019-41ba7000-2db5-11eb-83ce-88010eb4d6f3.png)
Then we create one _privacy_ page for US Store View, and one _privacy_ page for UK Store View. The pages are created successfully
![privacy](https://user-images.githubusercontent.com/51680745/99984655-05d3da80-2db6-11eb-9e99-9de412e62fba.png)
![two_pages_2020-11-23 18-00](https://user-images.githubusercontent.com/51680745/99984671-0c625200-2db6-11eb-8566-6894f2ea037b.gif)

Please, correct our steps if we are missing something.

Thank you in advance

**Comment by frostblogNet** [comment]
@magento give me 2.4-develop instance

**Comment by frostblogNet** [comment]
Hello @engcom-Bravo  thanks for your quick response this is a bit strange. I will double check and will give you more information.

**Comment by frostblogNet** [comment]
Sorry I don`t know why but I also can not reproduce this issue again.

**Comment by CyberSecutor** [comment]
Hi @engcom-Bravo and @frostblogNet  

I have this issue as well. I can only trigger this issue with content pages with duplicate keys, but different stores created in 2.3.5 and after migrating to 2.4.1 this issue arises.


https://user-images.githubusercontent.com/843685/110450819-d8d8d880-80c3-11eb-9f62-7178711f668e.mp4

**Comment by vipulra** [comment]
facing the same issue when migrating from Magento 2.3.2 to Magento 2.4.1

**Comment by alexiscl02** [comment]
Having the exact same issue as video posted by @CyberSecutor with Magento 2.4.2.

Maybe it was already present with a previous version and we didn't notice. We don't have much page with same URL key for different store view.

**Comment by jgallup** [comment]
We too are receiving this error after upgrading from v2.3.2-p2 to 2.4.2(.) In looking through this it appears that the one difference is that in @engcom-Bravo's example the "Add Store code to URLs" option is set to "Yes." In our case, this is set to "No" as the individual stores themselves exist on entirely different domains. i.e. we have www.url1.com setup with one store view and www.otherURL2.com setup for the second store view. 

I'm not sure what the process is, but I feel like this issue should be reopened as we cannot include the store view code in the URL.

**Comment by cubanmercury** [comment]
We are also seeing this issue after upgrading from 2.3.6 -> 2.4.2 and with "Add store code to URLs" set to "no" and individual stores setup on different domains.
In our case there are no other CMS pages with the same url key (even across all store views) and there are no redirects setup for that particular key in the url_redirects table.
![image](https://user-images.githubusercontent.com/34423353/116554880-a002f600-a8f3-11eb-9c4c-4e1d6b61f7be.png)

**Comment by jwhitney55** [comment]
I have this same issue as well, after upgrading to 2.4.2.

**Comment by frostblogNet** [comment]
Same here. Quick fix is to disable this validator

`diff --git a/vendor/magento/module-cms/Model/PageRepository.php b/vendor/magento/module-cms/Model/PageRepository.php
index e0f50bd..8881534 100644
--- a/vendor/magento/module-cms/Model/PageRepository.php
+++ b/vendor/magento/module-cms/Model/PageRepository.php
@@ -168,7 +168,7 @@ class PageRepository implements PageRepositoryInterface
         }
         try {
             $this->validateLayoutUpdate($page);
-            $this->validateRoutesDuplication($page);
+            # $this->validateRoutesDuplication($page);
             $this->resource->save($page);
             $this->identityMap->add($page);
         } catch (\Exception $exception) {
-- 
2.24.3 (Apple Git-128)
`

**Comment by hugozang** [comment]
same thing happen to me, any updates on this issue?

**Comment by chslava** [comment]
Hi! Got the same issue. In my case, the CMS page had a URL key identical to the 'frontName' specified in the modules routes.xml file. So, I think that the validation works correctly and the URL key should be changed.

**Comment by kanevbg** [comment]
If you have cms page with URI key "shipping" you will not be able to save it after migration because the validator of URI key will find that there is frontend route "shipping" defined from module Magento_Shipping.
In practice this will not cause conflict of the URLs, however this validator will prevent the save....

**Comment by pmonosolo** [comment]
Having the same issue with "leasing" URL. Even though I have deleted the URL rewrite from the list, the URL still works and I am still unable to save the page.

Its really strange that this thing happens. This is a bug, NOT a feature.

**Comment by JoostWan** [comment]
@frostblogNet same issue over here with url key `contact` for CMS page. Also on 2.4.2 and 2.4.3-p1. There are no other entries with contact in the database, did a full search.

**Comment by frostblogNet** [comment]
@JoostWan @pmonosolo  @kanevbg 

This ticket is not about creating a cms page with a url key used in module-contact or someting else. This ticket is about create 2 cms pages in different Storeview with the same url key. This fails now and in my opinion this is wrong.

**Comment by mikelevy300** [comment]
I'm getting the same issue with a CMS page that has the url key 'shipping' in version 2.4.3-p1. 

I tested this out on a local install of 2.4.3-p1 using the sample data and luma theme and I'm getting the duplicate urk_key error when trying to create a new CMS page with the url key 'shipping'.

This case really should be re-opened because this used to work.  Creating a CMS page with url key 'shipping' is a very common place to put shipping information (delivery times, processing times, etc) for a store.  Going further, a non-technical person without access to the code, or knowledge of how magento works, would never be able to know if the url key for a CMS page they're trying to create might conflict with a route frontname.

Steps to reproduce:
1) Log into the admin panel
2) Go to Content -> Pages
3) Create a new CMS page
4) Add some content and set the url key to 'shipping'
5) Save the page

Expected result:
The CMS page saves

Actual result:
The error "The value specified in the URL Key field would generate a URL that already exists." displays and the page is not saved.

**Comment by aliomattux** [comment]
For those commenting on this issue that is already closed, I filed a new bug report specific to the issue with shipping.
https://github.com/magento/magento2/issues/35115
