### ISSUE TITLE
The Magento version number is 2.0.0 in the "develop" branch but should be not less than 2.0.1 because it is newer than the stable branch

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3100]
https://github.com/magento/magento2/blob/develop/composer.json#L5
https://github.com/magento/magento2/blob/2.0.1/composer.json#L5

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by simkea** [comment]
The version displayed in backend is incorrect [latest develop branch]

**Comment by okorshenko** [comment]
@dfediuk thank you reporting the issue. We will bump Magento version in develop branch after public release 2.1.0. We will consider your suggestion in a future
