### ISSUE TITLE
$order = $this->quoteManagement->submit($order); Guest

### ISSUE THREAD

**Issue by faca5** [magento/magento2#31017]
Hello.

I have created Payment module for Magento 2.4.0.

It works perfect for logged customers.

It doesn't work very well for guest customers.

It hang on submit().
```
$order = $this->_checkoutSession->getQuote();
...
$order = $this->quoteManagement->submit($order);
```

Error:
`Fatal error: Out of memory (allocated 10051649536) (tried to allocate 262144 bytes) in /vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php on line 907
`

Memory is not a problem!

Any idea?

**Comment by ihor-sviziev** [comment]
Hi @faca5,
Does this issue reproducing on empty magento installation?
If no - seems like the issue in the custom extension.

**Comment by faca5** [comment]
Hello.

I have tested on Magento 2.4.0 with LUMA. 

Command "$order = $this->quoteManagement->submit($order);" automatically redirect to home page.

Something is missing.


```
$order = $this->_checkoutSession->getQuote();
$order_id = $order->getId();
$order->setState($order_status, true)->save();
$this->_checkoutSession->setLastQuoteId($order_id)->setLastSuccessQuoteId($order_id);
$order = $this->quoteManagement->submit($order);
```

**Comment by faca5** [comment]
Error:
Customer Email address missing.

Email address is in the billing address?!

**Comment by ihor-sviziev** [comment]
Hi @faca5,
I would suggest you to look at some example in other payment method, probably it will help you to understand what's wrong with your solution and why it doesn't work. If still you will not be able to detect it - you can use xdebug to debug your solution and compare it with any other payment method.

Hope I helped you

**Comment by krishprakash** [comment]
Hi @faca5. Hope you got the answer if anything that you need to know then Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
Thanks!!

**Comment by faca5** [comment]
Hello.

I have solved the problem with add additional lines which for guest order add email address in customer.

```
$logged = 0;
if($customerSession->isLoggedIn()) {
    $logged = 1;
}

if(!$logged) {
    $quote->setCustomerId(null)
        ->setCustomerEmail($quote->getBillingAddress()->getEmail())
        ->setCustomerIsGuest(true);
}
```
