### ISSUE TITLE
Sku with dashed number is  returning wrong result 

### ISSUE THREAD

**Issue by NTK-2016** [magento/magento2#31026]
Hi ,
I have facing issue with dashed number sku issue eg: 9290810-1
here is my url of site https://m4.eyedev.net
![image](https://user-images.githubusercontent.com/24722367/100092772-a096ec80-2e7c-11eb-9483-066e68478712.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @NTK-2016. 
Can you please explain the issue with all the details like which search engine you are using
Thanks!!

**Comment by NTK-2016** [comment]
Hi @krishprakash ,
yes, issue is occurred when I searching with this kind of sku 9290810-1, for more information you can search on provided url above

**Comment by NTK-2016** [comment]
Hi @krishprakash  any update

**Comment by krishprakash** [comment]
Hi @NTK-2016 
Kindly confirm the issue is reproduce on 2.4-develop instance or not as I checked it is not reproduce on latest 2.4-develop instance

**Comment by NTK-2016** [comment]
hi @krishprakash  issue on 2.3.4

**Comment by krishprakash** [comment]
Hi @NTK-2016. We only confirm the issue which is reproduce on latest magento 2.4-develop

**Comment by krishprakash** [comment]
Hi @NTK-2016. Feel free to reopen the issue once you confirm that issue is reproduce on latest 2.4-develop instance as per https://github.com/magento/magento2/issues/31026#issuecomment-732937246
