### ISSUE TITLE
Text Swatch, can't turn off "Visible on catalog pages"

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#3103]
On Text Swatch Attributes - i have found that you cannot turn off the "Visible on Catalog Pages on Storefront".

![screen shot 2016-01-24 at 10 06 33 pm](https://cloud.githubusercontent.com/assets/9780829/12535897/06c833b2-c2e7-11e5-839e-bb5191de30d0.png)

For Visual swatch this does work.

I believe this is a bug. I have tested on 2.0.1 & 2.0.0 clean / free install.

**Comment by rudik99** [comment]
Hi, not sure what the MX label is, but let me know if you need anymore info.

**Comment by fendowuk** [comment]
I am also experiencing the same issue on a fresh install ver. 2.0.2, installed via composer.

**Comment by jibrandlr** [comment]
Also experiencing this issue, ver. 2.0.5 installed via composer.

**Comment by fendowuk** [comment]
@lgarridoj I have just upgraded to 2.0.6 it this seems to have been fixed.

**Comment by jibrandlr** [comment]
@fendowuk I just upgraded to 2.0.6 but the issue is still present. I select "No" from dropdown menu, save, and after save the value is set to "Yes" automatically.

**Comment by kfaer** [comment]
2.0.7 and same issue, not saving the changes for : "Visible on Catalog Pages on Storefront" & "Used in Product Listing"

**Comment by antboiko** [comment]
Hi @rkhoury82 , thanks for reporting. Internal ticket MAGETWO-53929.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@rkhoury82, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
