### ISSUE TITLE
"Serialization failure" when trying to import products

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#3104]
CentOS 6.7
Apache 2.2
PHP 7.0.2
MariaDB 10.1
Magento 2.0.1

Just tried to import a 72MB product file, but it bombs out after about 10 mins with:

"
General system exception happened
Additional data: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `catalog_category_product` (`product_id`,`category_id`,`position`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) ON DUPLICATE KEY UPDATE `position` = VALUES(`position`)
"

M2 is in developer mode but nothing useful in the logs that I can see, just:
"[2016-01-24 16:09:01] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
"

Is this a known issue (a quick search revealed nothing).

We didn't see this problem on our previous build (PHP5.6/MariaDB10.0/Magento2.0). Was I being too optimistic expecting M2 to work with the latest tech!?

Cheers.

**Comment by mazhalai** [comment]
@hgpit PHP7 had issues with serialization earlier and a bug was reported: https://bugs.php.net/bug.php?id=70730, which was fixed. Can you please verify that your php version is the latest?

**Comment by hgpit** [comment]
Hello,

I am using the following, from Remi's repo:

PHP 7.0.2 (cli) (built: Jan  6 2016 15:33:31) ( NTS )

On 25 January 2016 at 14:34, mazhalai notifications@github.com wrote:

> @hgpit https://github.com/hgpit PHP7 had issues with serialization
> earlier and a bug was reported: https://bugs.php.net/bug.php?id=70730,
> which was fixed. Can you please verify that your php version is the latest?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/3104#issuecomment-174524416.

## 

Group IT Support
Hayley Group PLC (Site 3)
Shelah Road, Halesowen, West Midlands, B63 3PG, England
Company No: 1257303. VAT No: GB 287546119
[Tel] +44 (0)121 585 5334 | [Fax] +44 (0)121 585 7924 | [www]
http://helpdesk.hayley-group.local

## 

The information contained in this e-mail is intended only for the person or 
entity to which it is addressed and may contain confidential and/or 
privileged material. If you are not the intended recipient of this e-mail, 
the use of this information or any disclosure, copying or distribution is 
strictly prohibited and may be unlawful. If you received this e-mail in 
error, please contact the sender immediately and delete the material from 
any computer.

The views expressed in this e-mail may not necessarily be the views of 
Hayley Group PLC and should not be taken as authority to carry out any 
instruction contained within.

**Comment by shiftedreality** [comment]
Hi @hgpit 

Thank you for reporting.
This issue will be fixed in scope of https://github.com/magento/magento2/issues/6004

Closed as duplicate.
