### ISSUE TITLE
Free shipping delivery method does not work as expected with GraphQL

### ISSUE THREAD

**Issue by RetroModernDev** [magento/magento2#31052]
### Preconditions (*)

Magento version: 2.4.0

### Steps to reproduce (*)

1. Log-in to admin panel
2. Go to configuration -> sales -> delivery methods
3. Enable Free shipping delivery method
4. Set Minimum Order Amount to 100
5. Use GraphQl query like this to fetch data about available shipping methods: 
```
query getCart($cartId: String!) {
    cart(cart_id: $cartId) {
    	prices {
        grand_total {
          value
        }
      }
    	shipping_addresses {
        available_shipping_methods {
          amount {
            currency
            value
          }
          available
          carrier_code
          carrier_title
          error_message
          method_code
          method_title
          price_excl_tax {
            currency
            value
          }
          price_incl_tax {
            currency
            value
          }
        }
      }
    }
}

```

### Expected result (*)

1. If the order total of the cart is less than 100, the results shouldn't contain free shipping delivery methods

### Actual result (*)

1. The results contain free shipping even if the order total is less than 100
![Screen Shot 2020-11-25 at 11 37 39](https://user-images.githubusercontent.com/11998249/100216555-b48d2d80-2f12-11eb-8cfa-9985f9cb7698.png)
![Screen Shot 2020-11-25 at 11 41 19](https://user-images.githubusercontent.com/11998249/100216969-31b8a280-2f13-11eb-8a60-ade640e24cb6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by RakeshJesadiya** [comment]
Hello @Frodigo,

This is not the bug but I am sure you are checking the GraphQL code with the Magento sample data.

Magento sample data comes with predefined 'Cart price rules' by default.
There is one rule with Label "Spend $50 or more - shipping is free!" cause the issue for you.  This rule allowed to Free shipping with Cart subtotal equals or greater than 50.

Check Cart Rule by Go to
Admin Left Sidebar menu > Marketing > Cart Price Rules
Open the rule 'Spend $50 or more - shipping is free!'
This is the rule responsible for adding free shipping for your cart quote.
For Testing valid result, Just Disable this cart rule save Cart Rule and check the GraphQL response again. 
It will be not display free shipping below the minimum subtotal thresholds.

2) If you don't want to disable Cart Price rule. Just add item with amount less than 50 and you cant able to see Free Shipping in the Response of your query.

Let me know if you have still concerns/issue.

**Comment by Frodigo** [comment]
@RakeshJesadiya thanks for the clarification, that's correct. Closing.
