### ISSUE TITLE
Convert attribute codes for setters and getters issue when number in code exists

### ISSUE THREAD

**Issue by vpashovski** [magento/magento2#31068]
### Preconditions (*)

1. Magento 2.3.5

### Steps to reproduce (*)

1. Create product/category attribute with number in the code. For example use this attribute code `title_h1`
2. Save value for this attribute
3. Call getters for product/category attribute. For example, if we have attribute `title_h1` call `$object->getTitleH1()`

### Expected result (*)

1. When `$object->getTitleH1()` is called we expect to get the value for the attribute. Same as `$object->getData('title_h1')`

### Actual result (*)

1. `$object->getTitleH1()` returns NULL
2. `$object->getData('title_h1')` returns correct value

### Debuging info
After some debugging I found that the issue is in `\Magento\Framework\DataObject::_underscore` method.
In this method there is converting the getter name to attribute code.
Using attribute code with number it adds `_` before it.
In our case `getTitleH1` is converted to `title_h_1`. After that Magento looks for `$object->getData('title_h_1')` but attribute with code `title_h_1` doesn't exists.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @vpashovski thank you for your report. Could you clarify what object do you use for getter function?

**Comment by vpashovski** [comment]
Hi @engcom-Delta,
It is used `$category->getDataUsingMethod($attribute);` where $category is `\Magento\Catalog\Model\Category`.

**Comment by engcom-Delta** [comment]
@vpashovski  not sure if it is the issue. For now getter could correct handle with attributes codes `title_h_1`
Do you have a solution for case when attributes code are `title_h_1` and `title_h1` that don't break current behavior?

**Comment by vpashovski** [comment]
Hi @engcom-Delta , I didn't work on this issue and I don't have a solution for this. Sorry
