### ISSUE TITLE
Magento Search form-mini auto-suggest clicks not working, problem in form-mini.js

### ISSUE THREAD

**Issue by tigerx7** [magento/magento2#3106]
I was experiencing intermittent issues with clicking on the auto-suggested terms dropdown on the site search. Sometimes it would work, other times it wouldn't.

I traced the issue to: Magento / Search / view / frontend / web / form-mini.js with the click handler for the responseList.

It is assigning the selected element as so:

``` javascript
this.responseList.selected = $(e.target);
```

and on submit, it is locating the search term with the following:

``` javascript
this.element.val(this.responseList.selected.find('.qs-option-name').text());
```

The problem though is that since the element is being based on the object that initiated the event, the `<li>` may not always be what's assigned to responseList.selected. In the template, the search term and the result count is wrapped in a span. If those are clicked on directly, then `$(e.target);` returns those elements; thus `this.responseList.selected.find('.qs-option-name')` would return false.

If for some reason the user clicks just to the left or right of the spans, then it works, but most of the users we see are clicking either directly on the suggested term or on the result count.
### Temporary Workaround

In the submit function, I added a check to see if it was one of the `<li>` element's child that was assigned and if so, then I traverse up the DOM a level to retrieve .qs-option-name. Not sure if this is the best method though or if a more thorough refactoring of form-mini.js would be.

On a minor note, around line 34, the template contains an extra leading space before `<%- data.title %>` that was making itself into the query.

**Comment by vzabaznov** [comment]
#3657

**Comment by vzabaznov** [comment]
Hi @tigerx7 i will close this ticket due to duplication with #3657, internal ticket was created MAGETWO-50184
