### ISSUE TITLE
GraphQL: CustomizableDateOption or CustomizableDateValue should indicate the precise Date option type

### ISSUE THREAD

**Issue by laurentiumagureanu** [magento/magento2#31075]
### Preconditions (*)
1. Magento 2.4.1 CE

### Steps to reproduce (*)
1. Add multiple **Date** customizable options to a product. Use different date types: **Date**, **Date & Time**, **Time** 
2. Query the previous product via *graphQL* and display the customizable options. Use sample query below:

```graphql
{
  products(filter: {sku: {eq: "test-sku"}}) {
    items {
      sku
      __typename
      id
      name
      ... on SimpleProduct {
         options {
          __typename
          option_id
          required
          sort_order
          title
          ... on CustomizableDateOption {
            value {
              uid
              price
              price_type
              __typename
            }
            __typename
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. The customizable option part of the response, for Date options, should contain information about the precise field type ( **Date**, **Date & Time**, **Time**)

### Actual result (*)

1. There is no way to tell which is which. All Date options use the same type for the `value` field
![image](https://user-images.githubusercontent.com/6639076/100441685-8db82e00-30af-11eb-8669-67c27fdc86a7.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7343) is successfully created for this issue.

**Comment by korovitskyi** [comment]
@magento I am working on this
