### ISSUE TITLE
Unable to use bin/magento with Xdebug 3.0.0

### ISSUE THREAD

**Issue by maxlussier** [magento/magento2#31089]
### Preconditions (*)

1. Magento Commerce 2.3.5
2. PHP 7.3 with Xdebug 3.0.0

### Steps to reproduce (*)
1. php bin/magento list

### Expected result (*)

1. Should return the list of CLI commands available

### Actual result (*)

1. Triggers a PHP fatal error:

```
Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in /Sites/ew/src/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php on line 73

Error: Call to undefined function xdebug_disable() in /Sites/ew/src/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php on line 73

Call Stack:
    0.0002     395464   1. {main}() /Sites/ew/src/bin/magento:0
    0.0004     406472   2. require('/Sites/ew/src/app/bootstrap.php') /Sites/ew/src/bin/magento:14
    0.0006     413368   3. require_once('/Sites/ew/src/app/autoload.php') /Sites/ew/src/app/bootstrap.php:33
    0.0009     415032   4. include('/Sites/ew/src/vendor/autoload.php') /Sites/ew/src/app/autoload.php:30
    0.0012     429176   5. ComposerAutoloaderInit24b897732668d45e66b30e26efe4f7eb::getLoader() /Sites/ew/src/vendor/autoload.php:7
    0.0744    3212032   6. composerRequire24b897732668d45e66b30e26efe4f7eb($fileIdentifier = 'eda65932675b68b5aee4503e0762d64d', $file = 'C://Users//mlussier//Sites//ew//src//vendor//composer/../magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php') /Sites/ew/src/vendor/composer/autoload_real.php:63
    0.0749    3227968   7. require('/Sites/ew/src/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php') /Sites/ew/src/vendor/composer/autoload_real.php:73
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maxlussier** [comment]
Linked to a closed issue: https://github.com/magento/magento2/issues/28961 being the format was invalid.

**Comment by maxlussier** [comment]
Close the issue. Wrong repository. Issue on MFTF here: https://github.com/magento/magento2-functional-testing-framework/issues/808

**Comment by Knase** [comment]
I got this problem after the update Xdebug.
The fix is turn off Xdebug
`sudo mv /etc/php/7.3/cli/conf.d/20-xdebug.ini /etc/php/7.3/cli/conf.d/20-xdebug.ini.bak`
