### ISSUE TITLE
Remove laminas-config dependency from composer.json

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31082]
### Description (*)

In order to support PHP 8, the laminas/laminas-config dependency version should be either updated from "^2.6.0" to "^3.4.0" or removed as a dependency.

See the migration guide provided by laminas: https://docs.laminas.dev/laminas-config/migration/to-v3/

As there are no usages of laminas-config in the codebase, it appears the dependency should be removed

### What should be done

1. Remove `laminas/laminas-config` from `composer.json`
2. Run `composer update nothing` to update the lock file

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ProkopovVitaliy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39656` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
