### ISSUE TITLE
Update magento2 codebase to be compatible with PHP 8

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31081]
### Description 

Add PHP 8 compatibility to Magento 2
### What should be done
1. Fix the areas not yet covered by PHPCompatibility on develop branch:
 <https://github.com/PHPCompatibility/PHPCompatibility/issues/809>
1. Update PHP version in composer.json from "7.3.0||7.4.0" to "7.4.0||8.0.0"
1. Fix failed tests with PHP 8

### Apply fro the following repos:
* < > <https://github.com/magento/magento2>
* < > <https://github.com/magento/partners-magento2ee>
* < > <https://github.com/magento/partners-magento2b2b>
* < > <https://github.com/magento/partners-magento2-infrastructure>

**Comment by jamescowie** [comment]
Going to use this ticket as the tracker for what issues I faced and resolved. 

Currently working on `resolveArgument` with $enforcedArguments being the wrong type. Within ClassReader reflection resolved the deprecated code of `getType` with `getName`

**Comment by jamescowie** [comment]
For composer and package manager we need to upgrade `"laminas/laminas-mvc": "3.1.*",` however that version conflicts which then stops installation of additional packages

**Comment by sivaschenko** [comment]
@jamescowie great idea, It could be really helpful if you share the issues you faced, however, it could be even more helpful if these issues could be described thoroughly. Unfortunately, I don't really understand which `resolveArgument` and `$enforcedArguments` you are talking about.

Also, this issue is related to the Magento codebase only, there are separate issues created for dependencies versions

**Comment by sergeynezbritskiy** [comment]
@sivaschenko I've ran the next command `vendor/bin/phpcs -p --standard=PhpCompatibility --extensions=php,phtml --ignore=./vendor/* .`
Here is the list of issues, I've found: 
[report.txt](https://github.com/magento/magento2/files/5899449/report.txt)
There are tones of `PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound: Possible use of ASP style opening tags detected. ASP style opening tags have been removed in PHP 7.0. Found` errors which make report very noisy. I'm going to disable that rule for reported files and generate a new much more clear report

**Comment by sergeynezbritskiy** [comment]
After applying the PR [#31913](https://github.com/magento/magento2/pull/31913) the report is much more clear
[report.txt](https://github.com/magento/magento2/files/5899516/report.txt)

**Comment by sivaschenko** [comment]
Thanks for the report @sergeynezbritskiy ! Added to the description

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @sergeynezbritskiy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39455` was closed as `Fixed`.

**Comment by sivaschenko** [comment]
Closed in favour to new issue https://github.com/magento/magento2/issues/33563
