### ISSUE TITLE
Store image in DB doesn't seem to work

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#3109]
CentOS6.7
PHP7
M2.0.1

Hello,

On a clean system I have configured M2 to store product images in its database.
Then I run a product import but all images still get stored under pub/media/catalog/product...

Am I missing something?

**Comment by veloraven** [comment]
@hgpit is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
