### ISSUE TITLE
Request Entity To Large: Indexing of BUNDLE products (multiple options) with elasticsearch hits 413 error

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#31094]
### Preconditions (*)

1. Magento 2.3.x
2. Magento 2.4.x.
3. Have 100 saleable bundle products with at least 1800 children *EACH*
4. Each bundle product child has it's own description (1000) characters and other multiple attributes (it can be copied from parent products)

### Steps to reproduce (*)

1. Run reindex of such bundle product catalog

### Expected result (*)

1. Products are indexed without any issues
2.

### Actual result (*)

1. `Request Entity is to large`
```
020-11-30 12:52:07] main.CRITICAL:  {"exception":"[object] 
(Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 413):  
at [...]vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632)"} []
```

### Source of the issue:
When bundle product is prepared to be indexed, part of it's data is containing entire data from *ALL CHILD PRODUCTS*.
Even with `batchSize` reduced to 20 products request is over 500MB 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by qsolutions-pl** [comment]
I can provide a database image to debug this issue.

**Comment by engcom-Charlie** [comment]
Hello, @qsolutions-pl we are not able to reproduce the issue on the latest `2.4-develop` and `elasticsearch 7.1.0` by the following steps:

1. Generate adjusted `medium` fixture (without orders. taxes, configurable products, etc) with 4000 simple products
2. Set `Description`, `Short Description` to 5000 chars, `Meta Keywords` to 255 for all simple products via `Mass Update`
3. Create a category with 100 bundle products, each with one checkbox option -> 2000 child simple products(random products from previously created 4000 products)
4. Run `indexer:reindex`

**AR**: Indexer was passed successfully, all 100 bundle products are visible on the category page.
Could you please take a look?
Thank you.

**Comment by qsolutions-pl** [comment]
@engcom-Charlie I will share database image, just need to randomize some data - it will take a while.
