### ISSUE TITLE
Double charges

### ISSUE THREAD

**Issue by KatieWoodSouthland** [magento/magento2#31104]
Hi,

We have had, on 2 occasions in the past week, double charges on customer credit cards.

Order number 1000002076 the customer paid $76.84 twice on 24 November 3.36.07pm and 3.37.02pm
Order number 1000002115 the customer was charged $118.25 twice on 29 November 2.32.21pm and 2.59.29pm

As this is now the second time this has occurred, we thought that there might be an issue.

![image](https://user-images.githubusercontent.com/75285659/100685164-fc5afb80-33cf-11eb-983a-88d06e3cd93c.png)

![image](https://user-images.githubusercontent.com/75285659/100685346-4b089580-33d0-11eb-89a6-56f12466d34c.png)

Please advise.

Regards
Katie 
 

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by KatieWoodSouthland** [comment]
not required

**Comment by TonySchiano** [comment]
Same Issue,
multiple order have multiple checkout with different quoteID.
I have this issue with braintree payments.
![WhatsApp Image 2020-12-08 at 23 51 52](https://user-images.githubusercontent.com/9199001/101553538-1ccd1c00-39b5-11eb-8221-3aa0bce7c1e2.jpeg)
