### ISSUE TITLE
Zend_Db_Adapter_Exception when  running terminal command

### ISSUE THREAD

**Issue by freshface** [magento/magento2#3110]
When i try to run`php bin/magento indexer:info`
I get following error:

![screen shot 2016-01-24 at 22 12 12](https://cloud.githubusercontent.com/assets/103913/12538952/8e6f98e6-c2e7-11e5-81b3-585d72f7c608.png)

Any suggestions on how to fix this?
The storefront and backend are working.
I installed it in Mamp Pro.

Regards

**Comment by mazhalai** [comment]
It seems your mysql is not running, or you have an issue with [mysql sockets](http://stackoverflow.com/questions/1676688/php-mysql-connection-not-working-2002-no-such-file-or-directory). Please verify that and then run the command again.

**Comment by mazhalai** [comment]
@freshface closing due to non-responsiveness.
