### ISSUE TITLE
Registering on order success page saves addresses in the address book without checking save_in_address_book

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#31113]
When registering as a new customer on the success page after placing an order, the \Magento\Sales\Model\Order\OrderCustomerExtractor class copies all addresses from the order to the customer data.
This however is incorrect if 1 or more addresses have the save_in_address_book variable set to false in the quote_address table.

```
public function extract(int $orderId): CustomerInterface
{
    ...
    foreach ($order->getAddresses() as $orderAddress) {
        $addressData = $this->objectCopyService
            ->copyFieldsetToTarget('order_address', 'to_customer_address', $orderAddress, []);

        $index = array_search($addressData, $processedAddressData);
        if ($index === false) {
            // create new customer address only if it is unique
            $customerAddress = $this->addressFactory->create(['data' => $addressData]);
            $customerAddress->setIsDefaultBilling(false);
            $customerAddress->setIsDefaultBilling(false);
            if (is_string($orderAddress->getRegion())) {
                /** @var RegionInterface $region */
                $region = $this->regionFactory->create();
                $region->setRegion($orderAddress->getRegion());
                $region->setRegionCode($orderAddress->getRegionCode());
                $region->setRegionId($orderAddress->getRegionId());
                $customerAddress->setRegion($region);
            }

            $processedAddressData[] = $addressData;
            $customerAddresses[] = $customerAddress;
            $index = count($processedAddressData) - 1;
        }

        $customerAddress = $customerAddresses[$index];
        // make sure that address type flags from equal addresses are stored in one resulted address
        if ($orderAddress->getAddressType() == OrderAddress::TYPE_BILLING) {
            $customerAddress->setIsDefaultBilling(true);
        }
        if ($orderAddress->getAddressType() == OrderAddress::TYPE_SHIPPING) {
            $customerAddress->setIsDefaultShipping(true);
        }
    }

    $customerData['addresses'] = $customerAddresses;

    return $this->customerFactory->create(['data' => $customerData]);
}
```

A solution would be to fetch and check the quote_address (based on the order address quote_address_id data) to see if the save_in_address_book flag is set to true.

### Preconditions (*)
1. PHP7.2
2. Any version since M2.2

### Steps to reproduce (*)
1. Add products to cart and proceed to checkout
2. Programmatically make sure that the shipping and/or billing address are sent with the save_in_address_book flag to false when placing order OR go through the default checkout, place the order and then change the quote_address in the database by setting the save_in_address_book value to 0
3. Register as new customer on the success page after placing the order

### Expected result (*)
1. The addresses with flag save_in_address_book set to false should not be copied to customer_address_entity table

### Actual result (*)
1. Addresses are copied to the customer_address_entity table without taking the save_in_address_book flag into account

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @koenner01,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
