### ISSUE TITLE
Terms Conditions not showing in Panel 

### ISSUE THREAD

**Issue by alpeur** [magento/magento2#31116]
Please help!!

Terms Conditions not showing in Panel. If I click on sidebar on "store", terms condition missing.

**Comment by ajijshekh123** [comment]
@alpeur - Please add your bugs in the below Magento Issue reporting guidelines.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ajijshekh123** [comment]
@alpeur  - If you have found this issue again you can reopen and add the issue with proper reporting guidelines and screenshot/video.
