### ISSUE TITLE
Products query returns empty

### ISSUE THREAD

**Issue by developer0116** [magento/magento2#31114]
I tried to pull the products using graphql like this.
query {  
  products(
    filter: { sku: {  eq: "20409-903-1-1" } }
    pageSize: 20
    currentPage: 1
    sort: { name: DESC }
  ) {
    items {
      sku
    }
  }
}
but empty response like this.
{
  "data": {
    "products": {
      "items": []
    }
  }
}

So I tried many other queries but result is the same.

How to figure it out?

Thank you!

**Comment by sathiyaaa** [comment]
Did you try `setup:upgrade` and `setup:di:compile` command? @developer0116

**Comment by mauragcyrus** [comment]
Checked and this is not reproducible so closing this issue.
