### ISSUE TITLE
[GraphQL] Customer Order Totals missing gift card amount

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#31112]
During PWA development, it was discovered that gift card amounts are missing from the order total responses. This leads to us having to render an order total of $0 with no real explanation why. If it followed the same structure as the cart, we would maybe find a new gift_cards field instead, not sure how it would need structured since it's somewhat treated like a payment method.

Repro:
1. Create an account, login, place an order and pay with a gift card (gift card covers entire order)
1. Makes a customer query for customer.orders.items.total

Expected: total_giftcard field available
 Actual: No gift card related fields are available

Reproducible:

Yes, the issue can be observed when doing a `customer` GraphQL request. We hope to display something similar to our cart view, where we have access to a field like [applied*gift*cards](https://devdocs.magento.com/guides/v2.4/graphql/queries/cart.html#AppliedGiftCard).

![image](https://user-images.githubusercontent.com/69251111/100777680-fb6b9f00-33ba-11eb-959e-188287797c86.png)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-38927

**Comment by sasha19957099** [comment]
@magento I am working on this

**Comment by maddumarala** [comment]
Seems like same issue happening to Customer invoice totals.
