### ISSUE TITLE
[GraphQL] Products query returns products not assigned to a shared catalog

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#31111]
When shared catalog is enabled and a product is created, but not assigned to a shared catalog, that product will not appear in luma under the category or in search results.

However, its aggregations (price range & category) are being returned in the product graphQL query. This query should be modified to not any data for products not assigned to a shared catalog, when shared catalog is enabled.
#### Steps to reproduce
1. Enable shared catalog under Stores->Configuration, General->B2B Features->Enable Shared Catalog
1. Create a new product with sku="test_product" and do not assign to shared catalog
1. Go to Luma storefront and confirm that the product does not appear under the assigned category and is not returned in search for "test_product"
1. Run the following graphql query:
```java
{
  products(filter: {sku: {eq: "test_product"}}) {
    items
    aggregations
      attribute_code
      label
      options {
        count
        label
        value
      }
    }
  }
}
```

#### Expected Result

Query returns empty result set
#### Actual Result

Query returns the aggregations of the product, even though the product itself is not returned in the items[]
#### Notes

It is reproducible on EE 2.4-develop + B2B 1.2-develop

B2B
 commit 4bb3be18d8bf1bfba7bbeb572e1e2113f83d7a2e
 Magento 2 CE
 commit 32ed03cad4f2b2abc6ca6e5dc14885cd822c4508
 Magento 2 EE
 commit 405cc90c9a066d6a7f7b393275b3eccaa457c6d4

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-39522

**Comment by cspruiell** [comment]
@shikhamis11 please make sure the aggregations are also filtered in the same way. Right now they are still populated even when no items are returned. The test should also be updated to verify this.

For example:
```
{
  "data": {
    "products": {
      "items": [],
      "aggregations": [
        {
          "attribute_code": "price",
          "label": "Price",
          "options": [
            {
              "count": 1,
              "label": "50-60",
              "value": "50_60"
            }
          ]
        },
        {
          "attribute_code": "category_id",
          "label": "Category",
          "options": [
            {
              "count": 1,
              "label": "Gear",
              "value": "3"
            }
          ]
        }
      ]
    }
  }
}

```
