### ISSUE TITLE
Index Management not Updating

### ISSUE THREAD

**Issue by lookinglavish** [magento/magento2#3111]
When updating Index Management it doesn't seem to properly execute the function. 

After I "update on save" i get the following message: 9 indexer(s) are in "Update on Save" mode and also the "status" doesn't change at all remains as "ready". It seems like nothing processes. The hosting company was successful updating it through the command line.

Thanks!

**Comment by katmoon** [comment]
Hi,

In Magento 2 Index Management page serves only to change indexers mode.
Reindex no longer can be run from Admin, unlike Magento 1.

Usually in Update on Save mode you don't need to run reindex from command line until you get a system message that reindex is needed. This can happen if you perform a major update, e.g. delete a store, that requires significant resources to update indexes. In this case status will change from 'Ready' to 'Reindex Required'.

Does this solve your issue?

Thanks,
Kateryna.

**Comment by lookinglavish** [comment]
Yes, thank you!

**Comment by somnath12** [comment]
I can do arrange it such a way that you will need not do any indexing :) 
Email: somnathde_btech08@yahoo.com
