### ISSUE TITLE
Creditmemos incorrectly refund entirety of tax with separate invoices and virtual products

### ISSUE THREAD

**Issue by martinshawruroc** [magento/magento2#31120]
### Preconditions (*)

1. Magento 2.4.0 and 2.4.1
2. Other environment details are unimportant, for this report I've used https://github.com/markshust/docker-magento

### Steps to reproduce (*)

1. Configure an online payment method, with the ability to invoice separately and refund. I used Klarna - 3 interest-free instalments.
2. Configure two products - one simple, and one virtual. Make both of these taxable. 
3. Place an order containing both of those products
4. Invoice each of those items separately (so you have 2 invoices, each containing 1 item.)
5. Create a creditmemo from the invoice containing the virtual product (note, from the invoice, not the order)
6. Observe that the tax amount on the invoice contains the tax for the whole order, where it should only contain the virtual product's tax

### Expected result (*)

The creditmemo should only contain the tax amount for the items in the invoice, it should not consider the tax across the entire order.

### Actual result (*)

The creditmemo contains the tax for the entire order. See this example: https://i.imgur.com/nZaWUol.png You can see because of the incorrect tax, I'm able to create a creditmemo which has a greater grand total than the invoice's grand total.
---
### Additional info from Engcom

The issue is reproducible on Magento 2.4.1 

**Steps to reproduce**

3. Place an order containing both of those products
![1](https://user-images.githubusercontent.com/67371013/100868106-d43ccc80-34a3-11eb-890a-07cb9b9950a4.png)
4. Invoice each of those items separately (so you have 2 invoices, each containing 1 item.)
![2](https://user-images.githubusercontent.com/67371013/100868573-7361c400-34a4-11eb-86a1-740664ca6462.png)
5. Create a creditmemo from the invoice containing the virtual product (note, from the invoice, not the order)
6. Observe that the tax amount on the invoice contains the tax for the whole order, where it should only contain the virtual product's tax

*Expected result*
The creditmemo should only contain the tax amount for the items in the invoice, it should not consider the tax across the entire order.

*Actual result*
The creditmemo contains the tax for the entire order
![3](https://user-images.githubusercontent.com/67371013/100868861-df442c80-34a4-11eb-928c-0594c03c8fac.png)

**Comment by engcom-Bravo** [comment]
Hello @martinshawruroc 

Thank you for your report

We confirm that the issue is reproducible on Magento 2.4.1 and have added _Additional info from Engcom_ to the bugs description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39544` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment]
Hello, @martinshawruroc we can't reproduce the issue on the latest 2.4-develop having order with simple and virtual products placed via PayPal.
![Peek 2021-01-28 15-39](https://user-images.githubusercontent.com/51680850/106146793-cc399a00-617f-11eb-93ba-bd8cdb89adaf.gif)
Could you please take a look?
Thank you.

**Comment by martinshawruroc** [comment]
Hi @engcom-Charlie, I've just tried this out on the latest branch and you are correct it does seem to be fixed. I've confirmed that the issue is present in 2.4.1 so I assume we'll get it in the next release. I'll close the issue.

**Comment by magento-engcom-team** [comment]
Hi @martinshawruroc, @engcom-Charlie. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39544` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
