### ISSUE TITLE
1 exception(s): Exception #0 (Exception): Deprecated Functionality: implode(): Passing glue string after array is deprecated.

### ISSUE THREAD

**Issue by rameshkpm1984** [magento/magento2#31148]
### Preconditions (*)

1.Add Products
2.Edit Products

### Steps to reproduce (*)

1.Add Products
2.Edit Products

### Expected result (*)

1. [Screenshots, logs or description]
2.
![image](https://user-images.githubusercontent.com/48516751/101024771-95d60900-359a-11eb-9a3c-985062a00e73.png)

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @rameshkpm1984 
The problem is reproduced due to a third-party module.
This is not Magento issue.

**Comment by ihor-sviziev** [comment]
Hi @rameshkpm1984,
As @andrewbess said - the issue goes from the 3rd party module, in your case, it's Rokanthemes/Brand.

You could contact to developers of this extension in order to fix your issue.
