### ISSUE TITLE
Invoice for an order that contains only one configurable product is not generated correctly

### ISSUE THREAD

**Issue by mizzimizzi** [magento/magento2#31143]
### Preconditions (*)
1. Magento ver. 2.3.5-p1
2. Magento 2.4-develop

### Steps to reproduce (*)
1. create a cart with exactly one configurable product
2. complete the order with any payment method
3. invoice the order from Admin (only if the invoice has not already been created)

### Expected result (*)
The invoice is treated as last invoice (\Magento\Sales\Model\Order\Invoice::isLast returns true)
e.g., invoice with simple product
![Peek 2020-12-14 15-43](https://user-images.githubusercontent.com/51681379/102088697-f29bb400-3e23-11eb-8a43-377a011dc635.gif)

### Actual result (*)
The invoice is not treated as last invoice (\Magento\Sales\Model\Order\Invoice::isLast returns false)
![Peek 2020-12-14 15-46](https://user-images.githubusercontent.com/51681379/102088712-f6c7d180-3e23-11eb-96d1-de977a9df29a.gif)

---
similar issue is https://github.com/magento/magento2/issues/22283
isLast should skip the dummy items to avoid the problem.

extra info: if the order contains extra fees (for example the costs of cash on delivery) taxes on these are not calculated in the total and the total due is greater than 0

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39878` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by alexalisov** [comment]
I've tried to fix this issue in my module, using my custom method for checking last invoice. Seems like it is working fine

````php
    /**
     * Checking if the invoice is last
     *
     * @param Invoice $invoice order invoice
     *
     * @return bool
     */
    private function invoiceIsLast(Invoice $invoice)
    {
        foreach ($invoice->getAllItems() as $item) {
            /** @var \Magento\Sales\Model\Order\Invoice\Item $item */
            if (!$item->isLast() && ($item->getOrderItem() !== null) && !$item->getOrderItem()->isDummy()) {
                return false;
            }
        }
        return true;
    }
````

**Comment by mastiuhin-olexandr** [comment]
@magento I am working on this

**Comment by mastiuhin-olexandr** [comment]
@magento add to contributors team

**Comment by mastiuhin-olexandr** [comment]
@magento I am working on this

**Comment by leonhelmus** [comment]
@mizzimizzi  @mastiuhin-olexandr  It seems this fix should also be applied for creditmemo. See my bug:
https://github.com/magento/magento2/issues/36722

Thanks for adding this issue!
