### ISSUE TITLE
Price decimal mark replaced to [object Object] (Locale problem)

### ISSUE THREAD

**Issue by apychan** [magento/magento2#3116]
I got price format problem at product detail page after I change my store locale to Chinese (Hong Kong SAR China) (zh_Hant_HK").
There are no problem if I use English(US).
And I have tried different theme or use php5.6, but results are same

For example, I have one $123.45 product are listing, If I change to Chinese (Hong Kong SAR China), the price decimal mark will replaced like $123[object Object]45.

I am not sure, but I think it is replace by js, and js can't process correctly? 

ENV: apache, php7.0.2, mysql5.6

**UPDATE**: Little more information, I have self translated language file, the problem only occur if I apply the translated language file and I can sure it is replaced by JS.

**Comment by okorshenko** [comment]
@apychan thank you reporting the issue. Could you please update issue description using the following format: 

## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...

## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...

## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
