### ISSUE TITLE
REST endpoint /customers/search not working for multi-store newsletter subscriptions

### ISSUE THREAD

**Issue by moiashvin** [magento/magento2#31168]
### Preconditions (*)

1. Magento version 2.4.1
2. Magento 2.4-develop
3. Admin -> Stores -> Configuration -> Customers -> Customer Configuration -> Account Sharing Options and set S**hare Customer Accounts** to **Global**

![Screenshot from 2020-12-07 12-59-48](https://user-images.githubusercontent.com/51679138/101343060-1d1dc800-388c-11eb-914f-4ac3e0579d06.png)

4. Multiple-store views setup in Magento

![Screenshot from 2020-12-07 12-56-25](https://user-images.githubusercontent.com/51679138/101342739-a97bbb00-388b-11eb-93c7-89cbbe5d0ddf.png)

5. Have one customer ( _test@example.com_ for ex.);

### Steps to reproduce (*)

1. Go to _Admin -> Customers -> All Customers_ and open customer for edit;
2. On left side, select _Newsletter_, to have the Newsletter Informaiton panel where all stores views are displayed.
3. Select more than 1 checkbox to subscriber customer to the store's newsletter and save customer 
(at this point, in Newsletter Subscribers view, customer is subscribed to newsletter for multiple-store views)

![Screenshot from 2020-12-07 13-04-43](https://user-images.githubusercontent.com/51679138/101343548-d1b7e980-388c-11eb-86ff-a6ff23308ba7.png)

4. Use REST to call **GET** `/V1/customers/search` to retrieve the customer 

V1/customers/search?searchCriteria[filterGroups][0][filters][0][field]=email&searchCriteria[filterGroups][0][filters][0][value]=test@example.com&searchCriteria[filterGroups][0][filters][0][conditionType]=eq

![Screenshot from 2020-12-07 13-06-15](https://user-images.githubusercontent.com/51679138/101343677-09bf2c80-388d-11eb-9aa3-b4c3d3ede206.png)

### Expected result (*)

1. Customer details are returned correctly

### Actual result (*)

1. Exception occurs.
{
    "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-xxx"
}

![Screenshot from 2020-12-07 13-06-26](https://user-images.githubusercontent.com/51679138/101343713-15125800-388d-11eb-8b21-38f995bf3979.png)

2. And in the **_exception.log_** file: 

`
[2020-12-07 10:36:54] main.CRITICAL: Report ID: webapi-5fce05c67a1e6; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "1" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-5fce05c67a1e6; Message: Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento24/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento24/lib/internal/Magento/Framework/Data/Collection.php:408)"} []
`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39712` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @moiashvin. Thank you for your report. 
The issue has been fixed in magento/magento2#31261 by @korovitskyi in 2.4-develop branch
Related commit(s):
 - [f5cc98e68c00ff0e66d1dcc40b706e3bed1b7c98](https://github.com/magento/magento2/commit/f5cc98e68c00ff0e66d1dcc40b706e3bed1b7c98)
 - [66c3bff0b4c5aff1cfd1dd26bd7719bd622d8862](https://github.com/magento/magento2/commit/66c3bff0b4c5aff1cfd1dd26bd7719bd622d8862)
 - [b19a6dccb759e5cf0a494984467ea8efd9af3df5](https://github.com/magento/magento2/commit/b19a6dccb759e5cf0a494984467ea8efd9af3df5)

The fix will be available with the upcoming 2.4.3 release.
