### ISSUE TITLE
Argument 6 missing in SaveImageInformation

### ISSUE THREAD

**Issue by anvanza** [magento/magento2#31167]
### Preconditions (*)
1. Magento 2.4.1 with PHP 7.4

### Steps to reproduce (*)
1. Use module (Firebear import) to import images with the command line

### Expected result (*)
1. Images are imported

### Actual result (*)
Type Error occurred when creating object: Magento\MediaGalleryIntegration\Plugin\SaveImageInformation, Argument 6 passed to Magento\MediaGalleryIntegration\Plugin\SaveImageInformation::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

### Cause
https://github.com/magento/magento2/pull/29399

### Solution
The imageExtensions argument is defined in the Magento/MediaGalleryIntegration/etc/adminhtml/di.xml file while the SaveImageInformation class could also be used in CLI. Therefore the imageExtensions argument should be moved to Magento/MediaGalleryIntegration/etc/di.xml (without the adminhtml)

CC @firebearstudio

**Comment by ihor-sviziev** [comment]
Hi @anvanza,
Could you create a Pull Request with your suggested changes?

**Comment by PascalBrouwers** [comment]
Confirmed bug and tested PR. PR fixes the issue (import image via cli).
Tested with PHP 7.4 and Magento 2.4.0

**Comment by ihor-sviziev** [comment]
@PascalBrouwers @anvanza, could you provide some example of how exactly we can reproduce the issue? 
The suggested test in the PR https://github.com/magento/magento2/pull/31282 looks really strange. You shouldn't call plugin methods directly.

**Comment by alitopaloglu** [comment]
I can reproduce this on v2.4.3-p2

**Comment by pmonosolo** [comment]
I can also reproduce on 2.4.3, but with a custom plugin that was built in-house.

Same thing - when importing products using cron job - no problem. When using CLI command throws errors. 

Interestingly, if you extend the class that does the import, it throws error. If you just use ObjectManager (yes I know), it does not throw these errors.

**Comment by pmonosolo** [comment]
> 

Are you saying just throwing di.xml into src\vendor\magento\module-media-gallery-integration\etc\di.xml with

```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\MediaGalleryIntegration\Plugin\SaveImageInformation">
        <arguments>
            <argument name="imageExtensions" xsi:type="array">
                <item name="jpg" xsi:type="string">jpg</item>
                <item name="jpeg" xsi:type="string">jpeg</item>
                <item name="gif" xsi:type="string">gif</item>
                <item name="png" xsi:type="string">png</item>
            </argument>
        </arguments>
    </type>
</config>
```

will work?

**Comment by leonhelmus** [comment]
This fixed my import issue thanks a lot!

**Comment by engcom-Bravo** [comment]
Hi @anvanza,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/issues/31167#issuecomment-1185971449 issue has been fixed we are closing this issue.

Thanks.
