### ISSUE TITLE
Update league dependencies to PHP 8 compatible versions

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31177]
In scope of the user story MC-41382 we need to the update league/flysystem, league/flysystem-aws-s3-v3 and league/flysystem-cached-adapter dependency versions from "<sup>1.0" to "</sup>2.0"

 

In scope of this spice we need to estimate the effort required to provide that upgrade.

**Comment by sergeynezbritskiy** [comment]
@magento I am working on this

**Comment by sergeynezbritskiy** [comment]
Hi @sivaschenko I checked the ability to upgrade league packages
Here is what I've found: 
1. package [league/flysystem-cached-adapter](https://github.com/thephpleague/flysystem-cached-adapter) has the highest tag [1.1.0](https://github.com/thephpleague/flysystem-cached-adapter/releases/tag/1.1.0) at the moment, and this the version we use right now, so nothing to update here
2. at the same time this package has a constraint on league/flysystem [~1.0](https://github.com/thephpleague/flysystem-cached-adapter/blob/1.1.0/composer.json#L10), which makes impossible to update this package to 2.0
3. current version of league/flysystem is 1.1.3 which already does support [php8](https://github.com/thephpleague/flysystem/blob/1.1.3/composer.json#L24), so no need to update this package itself in terms of compatibility with php8
4. Package league/flysystem-aws-s3-v3 needs to be updates but versions 2.0.0 and higher require league/flysystem [^2.0.0](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/2.0.0/composer.json#L13) and this conflicts with our current version of flysystem

I'm a bit confused how to deal with it. please suggest
Currently it looks like we just need package league/flysystem-cached-adapter to support league/flysystem:^2.0. So should I just wait while the new version of league/flysystem-cached-adapter will be released ?

**Comment by sergeynezbritskiy** [comment]
FYI: created internal issue for league/flysystem-cached-adapter to track the progress https://github.com/thephpleague/flysystem-cached-adapter/issues/41
cc: @sivaschenko

**Comment by sivaschenko** [comment]
Thanks for the detailed investigation @sergeynezbritskiy ! Yes, we have to wait until `league/flysystem-cached-adapter` version compatible with `league/flysystem:^2.0` will be released to update all 3 packages.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @sergeynezbritskiy, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39646` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @sergeynezbritskiy, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41385` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
