### ISSUE TITLE
jQuery in custom extension did not work some times if it fire before default jQuery

### ISSUE THREAD

**Issue by emizentech** [magento/magento2#3117]
I want to use jQuery code in my custom extension and i am using require as below 

require([
    'jquery',
    "jquery/jquery-ui",
    'domReady!'
], function($){
    `use strict`;

// my code here 

});

after using strict the console error of jquery not defined is resolved.
But if my code fires before 
JQMIGRATE: Logging is active
than my code did not work 

it happens many times like 50% time my code runs and 50% times my code did not run 
any resolutions/suggestions  on this ?

**Comment by dmitrii-fediuk** [comment]
Try to place your initial JavaScript inside `x-magento-init`: https://mage2.pro/t/145

**Comment by anton-huz** [comment]
Hi Emizen,
So in general to execute any JavaScript code on the page you can use:
- External .js file with `require` and place it via `<script src=".." />` on the page. Please notice that in general its limited solution.
- External .js file with `define` and place it via [declarative initialization](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js_init.html) as suggested Dmitriy. This is more convenient way.

In both cases we did catch issues with `use strict;` statement.
In both cases you will not catch error _$ is not defined_ in case you use `$` as alias for jQuery module. And you can catch error  _jquery is not defined_ in case variable `jquery` really wasn't defined previously. 

Also fill free to use [StackExchange](http://magento.stackexchange.com/) as place for knowledge sharing. It has useful features for tracking particular question. And has wider community ready to give a hand.
Github Issues is more about _issues_ in source code.

Thanks for understanding.

**Comment by anton-huz** [comment]
Fill free to reopen issue in case my answer wasn't full. Or you have something to add.
