### ISSUE TITLE
Magento CLI enforces layout, block_html and full_page caches enable

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#31181]
### Preconditions (*)
1. Clear Magento 2.4

### Steps to reproduce (*)
1. `bin/magento cache:disable full_page`
2. `bin/magento setup:upgrade`

### Expected result (*)
1. `bin/magento cache:status full_page` should confirm that Full Page cache is disabled

### Actual result (*)
1. `bin/magento cache:status full_page` is... enabled 🤦🏻 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @lbajsarowicz,
It seems like this issue was already fixed in 2.4-develop in https://github.com/magento/magento2/pull/28491. Could you confirm that?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev I work with Magento 2.4.1, so... I need to wait for 2.4.2 then 🤦🏻

**Comment by ihor-sviziev** [comment]
@lbajsarowicz or you can apply fix as a patch, more into at https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#custom-patches

**Comment by ihor-sviziev** [comment]
I’m closing this issue as duplicate.
Thank you do much for reporting this issue!
