### ISSUE TITLE
IP access to Magento 2.2.7 and tracking of modfications

### ISSUE THREAD

**Issue by Ecoceramica** [magento/magento2#31186]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Ecoceramica** [comment]
Magento 2.2.7. As an e-commerce manager, I need an updated tracking of IP access to the platform and areas of intervention, to better coordinate the job and repair errors. This feature is currently not provided by the platform, apparently. I wait for anybody of the community to help me on this. Thank you very much

**Comment by itisraza** [comment]
Hi @Ecoceramica, you can join **admin_user_session** with other entity tables to find out who updated what and from where(IP). For example "catalog_product_entity" in conjunction with "admin_user_session" you can find out all the updates done on a product.

Hope this will help

Regards,
Raza.

**Comment by Ecoceramica** [comment]
Thank you Muhammad,

from where can I join admin_user_session?

How can I control this practically? Please send me the instructions


Chiara Montorsi
*Marketing and Customer Care*
ECO CERAMICA S.P.A.
Via Don P.Borghi, 5
42013 S.Antonino di Casalgrande (RE) - Italy
Tel. +39 0536.991729
Mob +39 334.6722456
www.ecoceramica.com
www.shop.ecoceramica.com

*to see our new handcrafted collection, click here
<https://mailchi.mp/ecoceramica/metallica>*

***

I Suoi dati personali saranno trattati in ottemperanza al Regolamento
Generale (UE) 2016/679. Per maggiori informazioni la invitiamo a prendere
visione delle ns. informative <https://www.ecoceramica.com/privacy.php>. Si
precisa che il presente messaggio non è a carattere personale e le risposte
allo stesso potranno essere conosciute dall’organizzazione lavorativa di
appartenenza del mittente secondo le modalità previste all’interno
dell’azienda. Le informazioni contenute nella presente comunicazione e i
relativi allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati. La diffusione,
distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi
soggetto diverso dal destinatario è proibita ai sensi di legge. Se ha
ricevuto questo messaggio per errore, La preghiamo di distruggerlo e di
informarci immediatamente per telefono al 0536/991701 o inviando un
messaggio all'indirizzo e-mail privacy@ecoceramica.com.

Your personal data will be processed in compliance with the General
Regulation (EU) 2016/679. For further information, we invite you to read
our information notices. Please note that this message is not for personal
purposes and the answers to it may be disclosed to the sender's work
organization according to the procedures provided within the company. The
information contained in this communication and its attachments may be
confidential and are, in any case, intended exclusively for the persons or
the Company indicated above. The diffusion, distribution and/or copying of
the document transmitted by any person other than the recipient is
prohibited by law. If you have received this message in error, please
destroy it and inform us immediately by telephone on +39 (0) 536/991701 or
by sending a message to privacy@ecoceramica.com.



Il giorno lun 7 dic 2020 alle ore 11:14 Muhammad Raza <
notifications@github.com> ha scritto:

**Comment by itisraza** [comment]
Hi Chiara, unfortunately entity tables(e.g. catalog_product_entity) only tells us when an entity is updated but doesn't give idea about who did this change so the only way to combine both admin_user_session and entity tables is via updated time stamps' windows of both admin_user_session and catalog_product_entity and that would not always be accurate. 

Alternatively, you can update the installation to add additional column for admin_user_id to these entity tables besides just the updated time stamp so you could join these updates via admin ID JOIN clause e.g. admin_user_session.id = catalog_product_entity.admin_id

Hope this answers your question

Regards,
Raza.

**Comment by Ecoceramica** [comment]
Thank you Raza.
If I was satisfied only to know WHEN an entity table has been updated,
which is the path inside Magento I should follow to come to that
information?

Please consider I am not a developer with coding skills, but a digital
specialist, with content management and coordination, follow up skills.

Thank you for your precious support


Chiara Montorsi
*Marketing and Customer Care*
ECO CERAMICA S.P.A.
Via Don P.Borghi, 5
42013 S.Antonino di Casalgrande (RE) - Italy
Tel. +39 0536.991729
Mob +39 334.6722456
www.ecoceramica.com
www.shop.ecoceramica.com

*to see our new handcrafted collection, click here
<https://mailchi.mp/ecoceramica/metallica>*

***

I Suoi dati personali saranno trattati in ottemperanza al Regolamento
Generale (UE) 2016/679. Per maggiori informazioni la invitiamo a prendere
visione delle ns. informative <https://www.ecoceramica.com/privacy.php>. Si
precisa che il presente messaggio non è a carattere personale e le risposte
allo stesso potranno essere conosciute dall’organizzazione lavorativa di
appartenenza del mittente secondo le modalità previste all’interno
dell’azienda. Le informazioni contenute nella presente comunicazione e i
relativi allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati. La diffusione,
distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi
soggetto diverso dal destinatario è proibita ai sensi di legge. Se ha
ricevuto questo messaggio per errore, La preghiamo di distruggerlo e di
informarci immediatamente per telefono al 0536/991701 o inviando un
messaggio all'indirizzo e-mail privacy@ecoceramica.com.

Your personal data will be processed in compliance with the General
Regulation (EU) 2016/679. For further information, we invite you to read
our information notices. Please note that this message is not for personal
purposes and the answers to it may be disclosed to the sender's work
organization according to the procedures provided within the company. The
information contained in this communication and its attachments may be
confidential and are, in any case, intended exclusively for the persons or
the Company indicated above. The diffusion, distribution and/or copying of
the document transmitted by any person other than the recipient is
prohibited by law. If you have received this message in error, please
destroy it and inform us immediately by telephone on +39 (0) 536/991701 or
by sending a message to privacy@ecoceramica.com.



Il giorno lun 7 dic 2020 alle ore 11:47 Muhammad Raza <
notifications@github.com> ha scritto:

**Comment by itisraza** [comment]
Hi Chiara, this is only available in EE although there is a free plug-in available for CE which serves the purpose, please take a look at https://www.mageplaza.com/magento-2-security/action-log.html?utm_source=mageplaza&utm_medium=mageplaza&utm_campaign=mageplaza-review&a=bigvn&utm_content=Admin%20Actions%20Log

Regards,
Raza.

**Comment by Ecoceramica** [comment]
Great Raza,

I see it is only 149 USD one shot (no every year).

I am wondering why the previous Ecommerce Manager did not adopt it.

Thank you for your precious support

[image: image.png]




Chiara Montorsi
*Marketing and Customer Care*
ECO CERAMICA S.P.A.
Via Don P.Borghi, 5
42013 S.Antonino di Casalgrande (RE) - Italy
Tel. +39 0536.991729
Mob +39 334.6722456
www.ecoceramica.com
www.shop.ecoceramica.com

*to see our new handcrafted collection, click here
<https://mailchi.mp/ecoceramica/metallica>*

***

I Suoi dati personali saranno trattati in ottemperanza al Regolamento
Generale (UE) 2016/679. Per maggiori informazioni la invitiamo a prendere
visione delle ns. informative <https://www.ecoceramica.com/privacy.php>. Si
precisa che il presente messaggio non è a carattere personale e le risposte
allo stesso potranno essere conosciute dall’organizzazione lavorativa di
appartenenza del mittente secondo le modalità previste all’interno
dell’azienda. Le informazioni contenute nella presente comunicazione e i
relativi allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati. La diffusione,
distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi
soggetto diverso dal destinatario è proibita ai sensi di legge. Se ha
ricevuto questo messaggio per errore, La preghiamo di distruggerlo e di
informarci immediatamente per telefono al 0536/991701 o inviando un
messaggio all'indirizzo e-mail privacy@ecoceramica.com.

Your personal data will be processed in compliance with the General
Regulation (EU) 2016/679. For further information, we invite you to read
our information notices. Please note that this message is not for personal
purposes and the answers to it may be disclosed to the sender's work
organization according to the procedures provided within the company. The
information contained in this communication and its attachments may be
confidential and are, in any case, intended exclusively for the persons or
the Company indicated above. The diffusion, distribution and/or copying of
the document transmitted by any person other than the recipient is
prohibited by law. If you have received this message in error, please
destroy it and inform us immediately by telephone on +39 (0) 536/991701 or
by sending a message to privacy@ecoceramica.com.



Il giorno lun 7 dic 2020 alle ore 16:52 Muhammad Raza <
notifications@github.com> ha scritto:

**Comment by krishprakash** [comment]
Hi @Ecoceramica. Hope you got the help if you need any other help then kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem because GitHub issue tracker is intended for magento core technical issues only
