### ISSUE TITLE
Issue circular dependency with 2.4-develop branch

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#31183]
### Summary (*)

Got issue when run cli magento setup upgrade command in 2.4-develop

Circular dependency: customRemoteFilesystem depends on Magento\RemoteStorage\Driver\Cache\CacheFactory and vice versa.

Basically command setup upgrade not work after merge 2.4-develop

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shiftedreality** [comment]
@mrtuvn have you cleaned all caches and `generated` folder before running `setup:upgrade`?

**Comment by mrtuvn** [comment]
Yes i have cleared that

**Comment by shiftedreality** [comment]
What if you install cleanly? Upgrade of dev branch might have unpredictable results

**Comment by mrtuvn** [comment]
OK i will try again

**Comment by mrtuvn** [comment]
@shiftedreality you are right now i can run setup upgrade
But in local i got issue with setup di compile command
![Screenshot from 2020-12-06 10-52-58](https://user-images.githubusercontent.com/1908873/101270997-736a0880-37b1-11eb-8cd4-623cafa12e25.png)
Any idea why this happen

**Comment by mrtuvn** [comment]
php74 with magento 2.4-develop branch no sample data

**Comment by shikhamis11** [comment]
@magento give me 2.3.4 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4.1 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4.0-beta2 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4.0 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.3.6 instance with edition ee

**Comment by DavaGordon** [comment]
Just a fyi for anyone getting this issue. i had this same issue after upgrading from 2.4.2-p1 to 2.4.3 turned out it was an issue with redis and the simple enough fix was just to flush the redis

`redis-cli FLUSHALL`
