### ISSUE TITLE
Newsletter enabled setting is always retrieved from the default scope

### ISSUE THREAD

**Issue by savimar06** [magento/magento2#31188]
When disabling the newsletter for store scope and website scope the newsletter checkbox is still visible in register form and the newsletter info-box is visible in customer account dashboard.

The newsletter enabled setting is always retrieved from the default scope

### Preconditions (*)

1. Magento Version: 2.3.5-p2

### Steps to reproduce (*)

1. Enable the newsletter for default scope in Stores > Settings > Configuration -> Customers -> Newsletter > General Options > Enabled
2. Disable newsletter for store scope.
3. Navigate to customer registration page

### Expected result (*)

1. the newsletter should be disabled in frontend. The newsletter subscription checkbox should not be visible in register form and the newsletter info-box should not be visible in customer account dashboard

### Actual result (*)

1. The newsletter subscription checkbox is visible in register form and the newsletter info-box is visible in customer account dashboard
![Kuvakaappaus - 2020-12-07 13-50-58](https://user-images.githubusercontent.com/52239248/101348323-24e16a80-3894-11eb-86d1-5704c04ada40.png)
![Kuvakaappaus - 2020-12-07 13-49-55](https://user-images.githubusercontent.com/52239248/101348324-26129780-3894-11eb-83b1-63988b25cdd9.png)

\Magento\Newsletter\Model\Config::isActive
```
    /**
     * Returns newsletter's enabled status
     *
     * @param string $scopeType
     * @return bool
     */
    public function isActive(string $scopeType = ScopeConfigInterface::SCOPE_TYPE_DEFAULT): bool
    {
        return $this->scopeConfig->isSetFlag(self::XML_PATH_NEWSLETTER_ACTIVE, $scopeType);
    }

```

\Magento\Customer\Block\Form\Register::isNewsletterEnabled
```
    /**
     * Newsletter module availability
     *
     * @return bool
     */
    public function isNewsletterEnabled()
    {
        return $this->_moduleManager->isOutputEnabled('Magento_Newsletter')
            && $this->newsLetterConfig->isActive();
    }

```

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39748` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saphaljha** [comment]
@magento I am working on this issue.
