### ISSUE TITLE
Error in FileTest

### ISSUE THREAD

**Issue by lewbor** [magento/magento2#3119]
In file dev/tests/integration/testsuite/Magento/Framework/Filesystem/Driver/FileTest.php: method testCreateDirectory: $this->assertTrue($this->driver->createDirectory($generatedPath, '755'));

Directory permissions is incorrect, it must be $this->driver->createDirectory($generatedPath, DriverInterface::WRITEABLE_DIRECTORY_MODE)

**Comment by mazhalai** [comment]
@lewbor thank you for reporting, we have created MAGETWO-48296 to track the fix.

**Comment by KrystynaKabannyk** [comment]
Hello @lewbor, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
