### ISSUE TITLE
[EY] Routable Interface in GraphQL

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#31196]
More info here. <https://github.com/magento/architecture/blob/898049e0834d7a07e4a9ee500937c011a111aa99/design-documents/graph-ql/coverage/storefront-route.md>

**Acceptance Criteria:**

Add a `RoutableInterface` to the base schema, and require all entity types which are routable to implement it.

A subset of Magento entities is "routable", in that they have URLs and they serve as the model for a rendered page. The natural fit for this concept is an interface, and GraphQL provides [multiple interfaces](https://graphql.github.io/graphql-spec/June2018/#sec-Objects) (<http://spec.graphql.org/June2018/#sec-Objects)> so that a given type can implement more than one.

As described in [Requirements](https://github.com/magento/architecture/blob/898049e0834d7a07e4a9ee500937c011a111aa99/design-documents/graph-ql/coverage/storefront-route.md#requirements) (<https://github.com/magento/architecture/blob/898049e0834d7a07e4a9ee500937c011a111aa99/design-documents/graph-ql/coverage/storefront-route.md#requirements),> the PWA must have the entity type and entity data for a given route, and it should be able to query for display metadata for that route. A GraphQL interface is a good match for these requirements:

Get the entity type using `__typename` introspection to get the GraphQL concrete type of the `RoutableInterface`

Get the entity data from the same `RoutableInterface` using GraphQL fragments on concrete type conditions

Get optional display metadata by requiring that field in the `RoutableInterface`

**Notes:**

An uncached response from the `urlResolver` query, in Magento cloud, takes around ~200ms to complete.

This change would provide the following benefits:
1. No need to make a 2nd, follow-up request for entity, so client doesn't pay the cost of Magento Framework bootstrap 2x
1. Querying of entity data happens at least 200ms earlier in page load

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-39746

**Comment by KrishnaK-Z** [comment]
@magento I am working on this
