### ISSUE TITLE
Fix default Magento font in order PDF (and filesize of 1MB +)

### ISSUE THREAD

**Issue by seansan** [magento/magento2#312]
Fix default Magento font in order PDF (and filesize of 1MB +)

Please have a look at the code alterations here:

http://magento.stackexchange.com/questions/4812/why-is-my-invoice-pdf-1mb

How about we provide a font dropdown in backend to select our own font. And default this to Helvetica?

Now users can choose. (and actually choose for small PDF files)

**Comment by verklov** [comment]
According to the new procedure, we are closing ticket here when it has a related ticket in our internal tracker placed to our backlog.
ID: MAGETWO-23732

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Fix-default-Magento-font-in-order-PDF-and-filesize-of-1MB/idi-p/46859).

**Comment by seansan** [comment]
It was acknowledged ... and I dont believe in a FORUM being the proces and
method to store important feedback and sometimes even code suggestions ...
it will get lost, forgotten - the forum will be killed in 2018 or 2019 just
like the previous one. I never understood why one did not open a simple
uservoice account or JIRA account and log it there.
