### ISSUE TITLE
Inventory sources cannot be deleted only disabled

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#31204]
It's impossible to delete custom sources that were created by mistake, during development for testing purposes or no longer needed even if we don't assign them to stocks or sales channels. 
 
### Preconditions (*)
1. Magento 2.4.1 with MSI
2. Add an additional custom source in Manage Sources

### Steps to reproduce (*)
1. Create a custom source
2. Try to delete a custom source

### Expected result (*)
I would expect to find a delete button and a delete mass action for inventory sources. 

### Actual result (*)
Instead I can only see the disable action
![image](https://user-images.githubusercontent.com/20220341/101469291-3cc8f500-394d-11eb-9a05-b4cebd9b773d.png)

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by ioweb-gr** [comment]
It's the same on the dev instance

**Comment by Pavel-Fekete** [comment]
According to magento [documentation](https://docs.magento.com/user-guide/catalog/inventory-sources-disable.html): Sources may not be deleted to ensure all order data retains in Magento. Sources, orders, and shipments are directly connected to each other. You can disable sources and modify information including location and point of contact.

**Comment by ioweb-gr** [comment]
@Pavel-Fekete This is also happening to ERPs to retain data coherence, however, when a source has no type of connection to order data or shipments I think it's useful be able to delete it. I think the delete action should be allowed but throw an exception if there's related data that depend on the specific source.

**Comment by itisraza** [comment]
Totally agree with @ioweb-gr, there should be a delete option and the system should validate underlying entities before triggering the delete i.e. if dependent entity exists then return the delete operation with error otherwise system should allow the delete.

Regards,
Raza.

**Comment by ioweb-gr** [comment]
This can also be caught on the data layer as well for additional safeguards with a ON DELETE RESTRICT

**Comment by engcom-Bravo** [comment]
Hello @ioweb-gr 

Thank you for your report.

The Inventory sources can not be deleted for a reason. According to magento [documentation](https://docs.magento.com/user-guide/catalog/inventory-sources-disable.html): Sources may not be deleted to ensure all order data retains in Magento. Sources, orders, and shipments are directly connected to each other. You can disable sources and modify information including location and point of contact. 
Like mentioned in the comment above https://github.com/magento/magento2/issues/31204#issuecomment-740531981

We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
