### ISSUE TITLE
[GraphQl] Selected shipping method does not contain value including tax.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#31206]
### Preconditions (*)

1. Magento 2.4.1 (also present in at least 2.3.5p2)

### Steps to reproduce (*)

1. Enable the shipping method flatrate and set its price to 10
2. Configure a default tax class for shipping that's not 0%. My example is 21%
2. Set tax/calculation/shipping_includes_tax to "Including Tax"
3. Set tax/cart_display/shipping to "Including Tax"
4. Set tax/display/shipping to "Including Tax"
4. Create a Cart through GraphQl
5. Add a product to your cart through GraphQl
6. Set a Shipping Address on your cart through GraphQl
7. Set flatrate/flatrate as your shipping method through GraphQl using the following query.
````
mutation setShippingMethodsOnCart(
    $cartId: String!, 
) {
    setShippingMethodsOnCart(
        input: {
            cart_id: $cartId, 
            shipping_methods:[{
		carrier_code:"flatrate",
		method_code:"flatrate"
	    }]
        }
    ) {
        cart {
            shipping_addresses {
                selected_shipping_method {
                    amount {
                        currency
                        value
                    }
                }
            }
        }
    }
}
````

### Expected result (*)

````
{
    "data": {
        "setShippingMethodsOnCart": {
            "cart": {
                "shipping_addresses": [
                    {
                        "selected_shipping_method": {
                            "amount": {
                                "currency": "EUR",
                                "value": 10.00
                            }
                        }
                    }
                ]
            }
        }
    }
}
````

### Actual result (*)

````
{
    "data": {
        "setShippingMethodsOnCart": {
            "cart": {
                "shipping_addresses": [
                    {
                        "selected_shipping_method": {
                            "amount": {
                                "currency": "EUR",
                                "value": 8.26
                            }
                        }
                    }
                ]
            }
        }
    }
}
````
There is currently no way to get the value of the selected shipping method including tax. This is a value you want for all countries where its normal to display prices including tax (most if not all EU countries) . Currently the only way to get the value (without code changes) is to match the selected shipping method with available shipping methods and get the price incl tax from there. 

I'm not certain if the way forward is giving both values to the endpoint or based on configuration change the response of selected_shipping_method { amount { value }}.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by itisraza** [comment]
Hi @Hexmage, I think you need to include the following constructs in your input request
        ```
        price_excl_tax {
          value
          currency
        }
        price_incl_tax {
          value
          currency
        }

```
Hope this will help

Regards,
Raza.

**Comment by Hexmage** [comment]
@itisraza those only exist for AvailibleShippingMethods, I want them on SelectedShippingMethod.

**Comment by DuckThom** [comment]
Has this change ever been released? I see the commit (https://github.com/magento/magento2/commit/41ba02dad66d5b5c279fb16fd9f4a643bc22a9fe) in 2.4-develop but there are no tags associated with it.
