### ISSUE TITLE
Compile  Error -> setup:di:compile-multi-tenant

### ISSUE THREAD

**Issue by simkea** [magento/magento2#3120]
Env: Debian Jessie, Magento2 Git latest origin/develop (no custom modules)

$> rm -rf ./var/generation
$> sudo -u www-data ./magento setup:di:compile-multi-tenant

PHP Warning:  ltrim() expects parameter 1 to be string, object given in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php on line 152

PHP Notice:  Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/lib/internal/Magento/Framework/Autoload/ClassLoaderWrapper.php on line 81

PHP Notice:  Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/vendor/composer/ClassLoader.php on line 317

PHP Notice:  Uninitialized string offset: 0 in /var/www/kaphingst/mage2-shop/magento2/vendor/composer/ClassLoader.php on line 349

  [Magento\Framework\Exception\LocalizedException]
  Source class "" for "Magento\Catalog\Model\Product\Gallery\CreateHandler\Interceptor" generation does not exist.

**Comment by mazhalai** [comment]
@simkea Thank you for reporting, we have created MAGETWO-50842 to investigate and fix.

**Comment by joanhe** [comment]
@simkea With the latest decision, Multi-tenant compiler has been removed from Magento 2. The issue is no longer applicable any more.
