### ISSUE TITLE
No admin user after installation

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#3121]
Dear dev team,

after we tried today install Magento we found that the setup installer hasn't created a new user in the admin_user database, and there are also no pointers to the other admin_XXX tables. 

I can provide all necessary logs if needed. In the meantime I'd like to know:
- how shall passwords be stored if account is created trough DB? (MD5, SHA1, ???)
- how can I fix this problem?

Kind regards, Max

**Comment by mazhalai** [comment]
@kingalca how did you install? via command line or web setup? Also, how was magento deployed, vai git, compsoer create-project or downloaded zip from magento.com

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
