### ISSUE TITLE
[Vault] Template term is not translatable

### ISSUE THREAD

**Issue by elisei** [magento/magento2#31211]
Unable to create translation for [highlighted term](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Vault/view/frontend/templates/customer_account/credit_card.phtml#L46-L48)

### Preconditions
1. Magento 2.3+
2. Payment method with vault support and using [native template](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Vault/view/frontend/templates/customer_account/credit_card.phtml).

### Steps to reproduce
1. Store uses any language other than en_US.
2. Use a payment method that allows you to save a card. (This method should consume the native template for managing stored payment methods).
3. Go on My Account -> Stored Payment Methods, click on delete

### Expected resul

The content is not translatable.

### Actual result

In a translation file for any language you can translate the term.

### Possible solution

Presented on the pull

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sidolov 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39767` were created

**Issue Available**: @sidolov, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @elisei. Thank you for your report. 
The issue has been fixed in magento/magento2#31212 by @elisei in 2.4-develop branch
Related commit(s):
 - [9cae620c1648b48b01cce3dcc9fea06c9249a14a](https://github.com/magento/magento2/commit/9cae620c1648b48b01cce3dcc9fea06c9249a14a)
 - [a1808865c58768cc5e9afdb3c301893743ec6bfd](https://github.com/magento/magento2/commit/a1808865c58768cc5e9afdb3c301893743ec6bfd)

The fix will be available with the upcoming 2.4.3 release.
