### ISSUE TITLE
All orders creating with 0000-00-00 00:00:00 created_at

### ISSUE THREAD

**Issue by Damikooo** [magento/magento2#31227]
I'm using Magento 2.2.9 and i can't create order.
Before this i was getting Undefined index: year in /var/www/html/vendor/magento/zendframework1/library/Zend/Date.php on line 2653 at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61)"} []
I hardcoded it by this way
$parsed = ['date_format' => "yyyy-MM-dd",  "locale"=>"ru_RU", "year"=>"2020","month"=>"12","day"=>"02","fixed"=>0];
But now i'm getting orders with 0000-00-00 00:00:00 created at.
How can i fix it?

**Comment by krishprakash** [comment]
Hi @Damikooo. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this topic.
