### ISSUE TITLE
Entry in quote_item is not getting deleted after product is deleted

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31220]
### Preconditions (*)

1. 2.4.1

### Steps to reproduce (*)

1. Create a new product
2. Add the product to the cart
3. Open the database table "quote_item" and filter for the related quote_id.
4. Notice that the quote_item has one entry for the product you just added to the cart
![image](https://user-images.githubusercontent.com/16349349/101616341-8bd75e80-3a0f-11eb-9bdc-3222e7e26814.png)

5. Delete the product from the magento backend.

### Expected result (*)

1. The entry should get deleted from quote_item as well.

### Actual result (*)

1. The entry is still in the table quote_item, even though the product does not exist anymore.
![image](https://user-images.githubusercontent.com/16349349/101616341-8bd75e80-3a0f-11eb-9bdc-3222e7e26814.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Pavel-Fekete** [comment]
Not able to reproduce on 2.4.1

"quote_item" table when product is added to cart
![add to cart](https://user-images.githubusercontent.com/67371013/101631185-9d7b2f00-3a2c-11eb-92c7-af09724e8ded.png)

"quote_item" table after deleting product from the backend
![empty](https://user-images.githubusercontent.com/67371013/101631423-fa76e500-3a2c-11eb-830b-3f3538044d0f.png)

**Comment by Eddcapone** [comment]
Then maybe a third party extension is causing this. Thank you for testing!
