### ISSUE TITLE
Improve Fulltext indexer to not stop when getSearchableProducts return 0 depending on batch or other plugins

### ISSUE THREAD

**Issue by engcom-Hotel** [magento/magento2#31224]
### Summary (*)
Recreated from https://github.com/magento/magento2/issues/30798

Based on the issue mentioned above, there may be scenarios that with some customizations to Magento that will cause problems where Fulltext indexer will stop because `getSearchableProducts` returns 0 and the condition `while (count($products) > 0)` makes the indexer stop.

More details are provided on the discussion on #30798 and specifically here https://github.com/magento/magento2/issues/30798#issuecomment-737886556

This issue is created to suggest a more robust implementation to avoid such a scenario where that combination of while loop with antiGapModifiers and batchSize cause the problem.

### Preconditions (*)
Any Magento 2 version with ElasticSearch
Configure ElasticSearch 6.x / 7.x
Use steps from https://github.com/magento/magento2/issues/30798#issuecomment-738726660

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sidolov 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39790` were created

**Issue Available**: @sidolov, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madbounce** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by nthurston** [comment]
FYI this is happening again with built-in MSI on the latest versions of Magento because of a plugin in module-inventory-catalog-search/Plugin/CatalogSearch/Model/Indexer/ChildProductFilterByInventoryStockPlugin.php

The following scenario is breaking:
1. Have MSI modules enabled
2. Have Display Out Of Stock Products set to No
3. Have a gap of salable products > 2500 in your entity IDs

**Comment by hostep** [comment]
@nthurston: could you open a new issue with your findings? It will get more traction than to comment on this old issue.

**Comment by nthurston** [comment]
Sure - I just made #34887 
Wasn't sure if this belongs here or in MSI repo (ticket exists there already).
