### ISSUE TITLE
Row totals sum differs from subtotal in special cases when decimal qty is allowed

### ISSUE THREAD

**Issue by wilfriedwolf** [magento/magento2#31237]
### Preconditions (*)
Fresh Magento2 (Tested with 2.4.0)

### Steps to reproduce (*)
1. Create 2 identical products, Qty can be decimal: "yes", minimum Qty: 0.1, price 16.5  (choose no tax to exclude tax calculation effects)
2. Add 0.25 units of each product to cart.

### Expected result (*)
1. Each row total should be 4.13
2. Subtotal should be 8.26

### Actual result (*)
1. Each row total should is 4.13
2. But Subtotal is 8.25

![TotalsTest](https://user-images.githubusercontent.com/23700116/101688871-f10d6d00-3a6c-11eb-9dc4-22233fba9d96.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wilfriedwolf** [comment]
@magento give me 2.4-develop instance

**Comment by wilfriedwolf** [comment]
I could reproduce this on the 2.4-develop instance:

![totals-from-dev-instance](https://user-images.githubusercontent.com/23700116/101692206-27002080-3a70-11eb-8e46-bd52f6bcf817.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @wilfriedwolf. Yes it shows row totals as 4.13 and sub total as 8.25 but as per product price sub total is correct 16.5/2  = 8.25 
But yes here we can allow 3 digits for row total as 4.125 + 4.125 = 8.25

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39808` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wilfriedwolf** [comment]
Hi @krishprakash, 

in my opinion you are not right. Of course 

> 16.5/2 = 8.25

But I think you do have to give row total as full cents not as fraction of cents. I do not think, that this is legally correct.
And I do not think you can put 0.5 ct on an invoice (at least in Germany)

Also I do not quite agree about the S3 rating:
- This has also consequences with the invoice: As i saw it (I'll try to reproduce) the issue is corrected in the invoice yielding two different calculations (4.12 and 4.13) for the two Items.
- Also in our case this issue causes an error actually deducing wrong amounts from paypal, when the quote is modified in the checkout, causing much manual work and phone calls.

Best regards,

Willi

**Comment by wilfriedwolf** [comment]
@magento give me 2.4-develop instance

**Comment by wilfriedwolf** [comment]
Hi @krishprakash 

I was wrong. In vanilla Magento this also yields illegal invoices (see screenshot from the dev-instance). In my opinion it is not the row total that should be corrected, but the subtotal itself!
Please reconsider the severity.

Best regards, 
Willi
![invoice](https://user-images.githubusercontent.com/23700116/101737813-a9ff9600-3ac5-11eb-8775-4750b7776747.png)

**Comment by wilfriedwolf** [comment]
Do I get something wrong? Why is the bot marking the issue as stale, although it is a confirmed bug, ready for dev? How should I ever notice if it is fixed, if the bot closes the issue?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by xtremevision** [comment]
We are experiencing the same issue. See screenshot. The amounts are not matching, there's a 0.03 discrepancy between the amount paid and the grand total - 776.79 vs 776.82, and the same discrepancy between the row total and subtotal. To note: our catalog prices already include the tax.

![image](https://github.com/magento/magento2/assets/6533394/511a9bc8-6d7a-43c1-8f4f-67fe64edd0b8)
