### ISSUE TITLE
Configurable products sorting by price issue

### ISSUE THREAD

**Issue by mobeen-sarwar** [magento/magento2#31230]
**Preconditions (*)**

1- Magento 2.3.4
2- Not reproducible on 2.4.1

**Steps to reproduce (*)**

**1-** Install `Magento 2.3.4` with sample data

**2-** Go to some product category page that has configurable products from the front end
![menue](https://user-images.githubusercontent.com/75013004/101647007-0dec7500-3a5a-11eb-94c8-d85c50050db2.png)

**3-** Sort products by price from the sorting toolbar
![sortbypr](https://user-images.githubusercontent.com/75013004/101647204-4429f480-3a5a-11eb-9eec-36ac3aac28a0.png)

**Expected result (*)**
**1-** Products should be sorted according to the price

**Actual result (*)**
**1-** Products are not fully sorted according to price

![sortingIssue](https://user-images.githubusercontent.com/75013004/101646807-cf56ba80-3a59-11eb-905f-e15302c994b3.png)

**Further Details(*)**

[Video recording of the issue](https://www.loom.com/share/20572f1889534cfb9021ea4167c08e1cl)

**Comment by Pavel-Fekete** [comment]
Not reproducible on the latest 2.4-develop with sample data
![price](https://user-images.githubusercontent.com/67371013/101649566-b4794b80-3a43-11eb-936c-855990b806f5.gif)

**Comment by krishprakash** [comment]
Hi @mobeen-sarwar. Thank you for your report.
We can not approve and confirm issue which is already fixed in latest 2.4-develop instance
So kindly refer[ magento stack exchange ](https://magento.stackexchange.com/)or [community forum](https://community.magento.com/) for general discuss about this topic
Thanks!!
