### ISSUE TITLE
magento extension manager themes v 2.3.6

### ISSUE THREAD

**Issue by Morezon** [magento/magento2#31246]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Morezon** [comment]
![WhatsApp Image 2020-12-10 at 9 06 02 PM](https://user-images.githubusercontent.com/69711167/101794676-2083ae80-3b2d-11eb-8dde-4b1db7a753b3.jpeg)

**Comment by krishprakash** [comment]
@Morezon. Kindly update all the details Pre-condition,steps to reproduce,expected and actual result as per [issue reporting guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Without these details your ticket should be closed

**Comment by Morezon** [comment]
i give you screenshot i dont no what is promblem but extension manager is not open

**Comment by krishprakash** [comment]
Hi @Morezon. It's totally unclear as per your screenshot attached so suggest you to refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this problem
Thanks!!

**Comment by krishprakash** [comment]
Closing this ticket as per given feedback https://github.com/magento/magento2/issues/31246#issuecomment-743015101
