### ISSUE TITLE
magento 2 payment not showing in checkout payment list

### ISSUE THREAD

**Issue by poongud** [magento/magento2#3124]
i have create one offline payment method my custom payment method it not showing in front-end payment.

what are the main configuration file of payment to display in front end or else any admin config is there ?.

**Comment by poongud** [comment]
what are the main configuration file of payment to display in front end.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by tinelps** [comment]
hi @poongud have you had any solution to your problems?
