### ISSUE TITLE
Command "queue:consumers:start" is not defined.

### ISSUE THREAD

**Issue by DylanHopman** [magento/magento2#31255]
### Magento (*)
Magento 2.3.3

### How to reproduce (*)
bin/magento queue:consumers:start product_action_attribute.update
However, if you look in the bin / magento list and scroll to the queue, you will only see the: list in it. consumer: start is not even listed here. If you do in manually, you get the following error:
`Command "queue:consumers:start" is not defined.  
                                                   
  Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list `

### Expected result (*)
Updating the attributes, but not working. 
### Actual result (*)
`Command "queue:consumers:start" is not defined.  
                                                   
  Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list `

### Extra issue (*)
Also bin/magento cron:run isn't working. Got the following error in it:
`
Command "queue:consumers:start" is not defined.  
Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list                         

Command "queue:consumers:start" is not defined.  
Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list                         
                                               
Command "queue:consumers:start" is not defined.  
Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list                         

Command "queue:consumers:start" is not defined.  
Did you mean one of these?                       
      ce_mq:consumers:start                        
      queue:consumers:list `

**Comment by engcom-Alfa** [comment]
Hi @DylanHopman .
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Everything works as expected.

**Manual testing scenario:**
1. Configure Rabbit Mq ([devdocs](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/install-rabbitmq.html));
2. Run in console: `bin/magento queue:consumers:start product_action_attribute.update`
3. Update any product attribute;

**Actual Result:** :heavy_check_mark: An attribute was successfully updated

@DylanHopman Are you able to reproduce this issue on fresh 2.4-develop?
Thanks!

**Comment by DylanHopman** [comment]
@engcom-Alfa, thank you for answering. No we have a couple of websites, also websites on 2.3.3. But this is the first website we have this issue with. Is there an option to fix it, without updating?

**Comment by engcom-Alfa** [comment]
Maybe this solution will help you https://github.com/magemojo/m2-ce-cron/issues/89#issuecomment-604938652

**Comment by DylanHopman** [comment]
Hi,

Thanks for your quick reply. Unfortunately it doesn't solve the problem :(

**Comment by hostep** [comment]
@DylanHopman: that `ce_mq:consumers:start` is strange. When I google it I end up on https://github.com/renatocason/magento2-module-mq, I suspect you have that one installed. Maybe that module is removing the default `queue:consumers:start` command (which is definitely available in Magento 2.3.3).

Anyway, I strongly believe this issue is because of some customisation done to your webshop, hope you can figure it out! 🙂

**Comment by DylanHopman** [comment]
Thank you @hostep ,

This fixed the issue for me: 
bin/magento mod:dis Rcason_Mq Rcason_MqMysql
bin/magento se:di:co
bin/magento s:s:d nl_NL en_US -f
bin/magento c:f
bin/magento cron:run --group default
bin/magento cron:run

You helped me a lot, thanks 👍
