### ISSUE TITLE
MMAP "Cannot allocate memory" when importing products

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#3125]
CentOS 6.7
Apache 2.2
Magento 2.0.1

I am pretty much out of my league here, but I really have to get to the bottom of the abysmal M2 product import speeds we are seeing (today my Xeon 8 core 32GB DDR4 RAM build is importing 15 products/min...) .

Can anyone shed any light on the following?

If I strace the HTTPD process which seems to be dealing with the product import, I am seeing 
"
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x40000, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5522400000
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|0x40000, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5522200000
"

Are these memory allocation errors something which needs to be addressed or is it just misleading and harmless/normal?

Thank you.

**Comment by mazhalai** [comment]
What is your version of PHP?

**Comment by hgpit** [comment]
Hello,

My PHP version is:

PHP 7.0.2 (cli) (built: Jan  6 2016 15:33:31) ( NTS )

On 25 January 2016 at 16:03, mazhalai notifications@github.com wrote:

> What is your version of PHP?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/3125#issuecomment-174555135.

## 

Group IT Support
Hayley Group PLC (Site 3)
Shelah Road, Halesowen, West Midlands, B63 3PG, England
Company No: 1257303. VAT No: GB 287546119
[Tel] +44 (0)121 585 5334 | [Fax] +44 (0)121 585 7924 | [www]
http://helpdesk.hayley-group.local

## 

The information contained in this e-mail is intended only for the person or 
entity to which it is addressed and may contain confidential and/or 
privileged material. If you are not the intended recipient of this e-mail, 
the use of this information or any disclosure, copying or distribution is 
strictly prohibited and may be unlawful. If you received this e-mail in 
error, please contact the sender immediately and delete the material from 
any computer.

The views expressed in this e-mail may not necessarily be the views of 
Hayley Group PLC and should not be taken as authority to carry out any 
instruction contained within.

**Comment by veloraven** [comment]
@hgpit thank you for your question.
You should increase memory limit in php.ini file.

**Comment by ghost** [comment]
We have some `memory_limit` guidelines [here](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone). Let us know if they help you.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
