### ISSUE TITLE
Category Layout Update XML not working on frontend

### ISSUE THREAD

**Issue by test4295** [magento/magento2#31254]
### Preconditions (*)

1.Magento 2.3.2
2.Default Mode

### Steps to reproduce (*)

1.In category admin, catalog > category > select category > Design >Layout
2. Select custom layout 

### Expected result (*)

1. Updated layout should be show on frontend page-layout-customlayout

### Actual result (*)

1. It is showing page-layout-1column not updated layout showing in default mode

**Comment by engcom-Alfa** [comment]
Duplicate of #27942
