### ISSUE TITLE
Reindexing is taking a too much time

### ISSUE THREAD

**Issue by pnaimish** [magento/magento2#31260]
![Screenshot 2020-12-11 at 15 10 08](https://user-images.githubusercontent.com/28819105/101890115-47da8a00-3bc6-11eb-9209-ba8cdd5312c0.png)

### Summary (*)

I am Putting magento2 in reindexing brfore 3 hrs and it't taking a too much and products are stop showing in frontend.
### Examples (*)

  I am using cron job httpdocs/bin/magento indexer:reindex and indexer are stuck in processing
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @pnaimish. Can you please update issues description with all the details like pre-condition,reproducible steps,expected and actual result as per [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Thanks!!

**Comment by krishprakash** [comment]
Hi @pnaimish. Feel free to reopen ticket once you update with all required details as per issue reporting guidelines 
Thanks!!

**Comment by pnaimish** [comment]
Hi 

I am try to reindexing Product Categories, Category Products, Product Price but it it take too much time and in frontend all enabled product are stop showing could you please help me .

I am using magento 2.1.1

![Screenshot 2020-12-15 at 12 53 31](https://user-images.githubusercontent.com/28819105/102183859-8c229e80-3ed4-11eb-90b9-89e5e7d85e7a.png)
