### ISSUE TITLE
Afther successly install magento 2.0.1 Readiness still errors

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#3126]
- Just succesly installed magento 2.0.1 (frontend and backend works fine), when check Readdiness in System Upgrade still errors show up related whit php version and cronjob added correctly yet.

Best Regards
Toni
![readyness_check](https://cloud.githubusercontent.com/assets/16081377/12556193/fcac6616-c384-11e5-8355-eb20e429bf5f.jpg)

**Comment by mazhalai** [comment]
Please setup cron as [mentioned here](http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_cron.html)

**Comment by salelsol** [comment]
- Hi Mazhalai, I can´t add second cronjob due at this warning (update/cron.php) wroks fine:

Best Regards
Toni

**Comment by mazhalai** [comment]
What warning?

**Comment by salelsol** [comment]
- Hi, just - Enter your command in correct format e. g. “script.php” or “folder/script.php”

Best regards
Toni

**Comment by mazhalai** [comment]
@salelsol can you please post your cron scripts here.

**Comment by salelsol** [comment]
Hi, 
- This works: magento-14205-30960-83876.cloudwaysapps.com/update/cron.php
- This not works: magento-14205-30960-83876.cloudwaysapps.com/bin/magento setup:cron:run

Best Regards
Toni

**Comment by mazhalai** [comment]
Do you have a bin folder? have you tried `php -f magento-14205-30960-83876.cloudwaysapps.com/bin/magento setup:cron:run` and cron example is

```
*/1 * * * * php /var/www/html/magento2/update/cron.php &
*/1 * * * * php /var/www/html/magento2/bin/magento setup:cron:run & 
```

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
