### ISSUE TITLE
Admin Panel breaks when locale selected for user in production mode:

### ISSUE THREAD

**Issue by davefarthing** [magento/magento2#3127]
When changing locale for an admin user with the site in 'production' mode, the admin Breaks. 

to Recreate:
I have store views configured for en_GB and en_US, site set to production and all static content generated. Admin user selects a different locale from the list under user preferences, e.g. fr_FR 

The user is allowed the freedom to select any locale and this influences the path to the static resources (js/css etc). Under development mode the static.php handles the requests,  fetches and caches the requested files, however in production they return 404s owing to:

``` php
/* Magento\Framework\App\StaticResource */

    public function launch()
    {
        // disabling profiling when retrieving static resource
        \Magento\Framework\Profiler::reset();
        $appMode = $this->state->getMode();
        if ($appMode == \Magento\Framework\App\State::MODE_PRODUCTION) {
            $this->response->setHttpResponseCode(404);
        } else {
...
```

The only solution currently would be to pre-generate static content for all 82 locales as the admin user could choose any one of them. (extreme maybe, but you get my point?)

I appreciate that PHP should not be used to serve static content in production, but this tight relationship between locale and theme with the current configuration makes it almost impossible to rely upon anything else. I do not want to serve JS/CSS etc with static.php and certainly don't want to run in developer mode.

I do not understand why **all** content has to be replicated for **all** locales under the current static content system. Having this locale variable for all content is surely overkill and needs  to be rethought. JS and CSS and agnostic of locale for the most part, Jquery is the same in french,german,english or any other language and locale.

**Comment by davefarthing** [comment]
Any Suggestions?

**Comment by ghost** [comment]
I have a similar issue. I am using Magento 2.0.7 installed via the web setup wizard with en_CA locale. After changing to production mode the frontend requests from pub/static/frontend/Magento/luma/en_CA/ but the backend requests from pub/static/frontend/Magento/luma/en_US/. en_US was not deployed when setting the mode to production so it gives a 404 for those files.

Running the deploy static content command to deploy the en_US content seems to resolve the issue.

Should the backend be requesting from en_CA like the frontend or does the backend only use en_US?

**Comment by duhon** [comment]
Hello @davefarthing 

To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ghost** [comment]
I was able to resolve the issue I was having. I set the locale to English (Canada) when installing. After switching to production mode I had to deploy both en_CA and en_US static content to have everything display correctly.

I used the following command if anyone else has the same issue:

bin/magento setup:static-content:deploy en_US en_CA

**Comment by nigelcopley** [comment]
Surely this is a bug, I have my locale set to en_GB yet when in production it's only generating en_US static files

**Comment by nigelcopley** [comment]
the above command from @crtsl does work
