### ISSUE TITLE
Recommendation engine (Adobe Sensei) shows products already disabled or out of stock

### ISSUE THREAD

**Issue by sodhancha** [magento/magento2#31271]
### Preconditions (*)
1. Magento Commerce 2.4.0-P1  (On-Prem)
2.Recommendation Engine Module enabled in Product Details Page (Adobe Sensei)

### Steps to reproduce (*)
1. Enable Recommendations Engine module for Product Details Page
2.Use the Most Viewed setting for the recommendation engine

### Expected result (*)
1. Links to recommended products should be of products which are In-Stock and are Enabled

### Actual result (*)
Video: [https://www.loom.com/share/16b4b297214f49ac81559207040270df](https://www.loom.com/share/16b4b297214f49ac81559207040270df)
1. Links of recommended products go to 404 pages since those products are disabled.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by sodhancha** [comment]
There has been no movement on this issue.

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Hotel** [comment]
Hello @sodhancha,

Have you tried to reproduce the issue in Magento 2.4-develop. It seems that this issue is not reproducible in this branch.

Please try to reproduce it and let us know in case you are able to reproduce it.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @sodhancha,

We have noticed that this issue has not been updated for a period 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards
