### ISSUE TITLE
Customer sees raw code displayed after selecting My billing and shipping addresses are the same

### ISSUE THREAD

**Issue by lagunacellar** [magento/magento2#31272]
### Preconditions (*)

1. Magento 2.4.1 on Cloud
2.

### Steps to reproduce (*)

1. Log in as customer
2. Add product to cart and enter checkout
3. Select shipping method, click Next
4. At Review & Payments screen, check My billing and shipping addresses are the same
5. See raw code inserted between Street Address and City/Zip

### Expected result (*)

1. Screenshot Checkout-1
2. Expect confirmation of customer billing and shipping addresses are the same 
![checkout-1](https://user-images.githubusercontent.com/64744041/102019696-c7349e80-3d29-11eb-8812-0140c8ad5a87.jpg)

### Actual result (*)

1. Screenshot Checkout-2
2. See raw code inserted between Street Address and City/Zip
![checkout-2](https://user-images.githubusercontent.com/64744041/102019721-de738c00-3d29-11eb-9c35-9a747bb7bde0.jpg)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @lagunacellar,
I have verified this issue as per your steps, actual result, and expected result.
**See attached the screenshot:**
![image](https://user-images.githubusercontent.com/24711761/102079927-93de3680-3e33-11eb-9f92-ab8dfb550a4e.png)

Thanks.

**Comment by lagunacellar** [comment]
Our issue was resolved after applying patch MDVA-33289_EE_2.4.1_v1.  The solution was to remove _.values for currentBillingAddress().street in line 10 of file vendor/magento/module-checkout/view/frontend/web/template/billing-address/details.html:

<text args="_.values(currentBillingAddress().street).join(', ')"/><br/>

![Screen Shot 2020-12-14 at 10 04 08 AM](https://user-images.githubusercontent.com/64744041/102117887-c23c2180-3df3-11eb-898f-ae4025bfb333.png)

**Comment by ajijshekh123** [comment]
Okay, that's fine @lagunacellar
