### ISSUE TITLE
Page Builder Error Popup

### ISSUE THREAD

**Issue by rohan-magento** [magento/magento2#31277]
### Preconditions (*)

1. PHP 7.4
2. Magento 2.4.1 EE

### Steps to reproduce (*)

1.  Log in to Magento admin panel
2.  Go to any existing CMS Block or CMS Page
3. With the page builder, we are getting a popup error "Page Builder Error An error has occurred while initiating Page Builder. Please consult with your technical support contact." 
3. When we keep the inspect window open on chrome browser then we don't get this error,
4. We checked from our end and found that the above error is coming from the JS file - `vendor\magento\module-page-builder\view\adminhtml\web\js\stage-builder.js`

### Expected result (*)

1. Page builder should load without any error.

### Actual result (*)

1. With the page builder, we are getting a popup error "Page Builder Error An error has occurred while initiating Page Builder. Please consult with your technical support contact." screenshot attached here.
2. we also checked the console.error response in the same JS it says - `"TypeError: Cannot read property 'children' of null"`

![page-builder-error](https://user-images.githubusercontent.com/75991143/102091851-600c0c80-3e45-11eb-87a9-37e9eb26e996.PNG)

**Comment by rohan-magento** [comment]
The issue is resolved after provided the patch by the Magento team.
[Patch by Magento.zip](https://github.com/magento/magento2/files/5696417/Patch.by.Magento.zip)

**Comment by Guru-pwc** [comment]
How to use this magento patch file
