### ISSUE TITLE
SQL error on CMS > Block > Save and Duplicate

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#31281]
When selecting 'Save & Duplicate' from a CMS block, a SQL error is shown above the success message, and no duplicate block is created.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Log into admin > Content > CMS > Blocks
2. Create a block, or select an existing block
3. From the button on the top right, select 'Save and Duplicate'

### Expected result (*)

1. Success message, block is duplicated

### Actual result (*)

1. Success message, SQL error is shown:
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null, query was: INSERT INTO `cms_block` (`block_id`, `title`, `identifier`, `content`, `is_active`, `valid_from`, `valid_to`, `customer_group`, `tag`, `cron_schedule_flag`, `css_phone_small`, `css_phone`, `css_tablet_small`, `css_tablet`, `css_desktop`, `css_desktop_large`, `custom_js`, `css_global`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @nbennett25. Cannot able to reproduce the issue as provided steps by you 

![image](https://user-images.githubusercontent.com/46617848/102172723-5a530d00-3ebf-11eb-9899-8d200712425d.png)

Kindly provide additional details/steps to reproduce issue also confirm once issue reproduce on latest 2.4-develop instance
Thanks!!

**Comment by nbennett25** [comment]
@magento give me 2.3 instance

**Comment by willstorm** [comment]
@magento give me 2.3.3 instance

**Comment by nbennett25** [comment]
@magento give me 2.3 instance

**Comment by krishprakash** [comment]
Hi @nbennett25. Feel free to reopen the issue once you confirm that issue reproduce on latest magento 2.4 develop instance.
