### ISSUE TITLE
The "magento/magento-composer-installer" plugin was skipped

### ISSUE THREAD

**Issue by rvtechmagento** [magento/magento2#31283]
The "magento/magento-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "magento/inventory-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

I got above error when i run the below mentioned command.

composer config repositories.magento composer https://repo.magento.com

I have magento2 website and i want to migrate data from Magento1 to Magento2 using data migration tool. But i got above error.
Could you please check this issue.

Thanks

**Comment by ihor-sviziev** [comment]
Hi @rvtechmagento,
You're having this issue due to missing composer 2  support by magento.

We have a feature request for that https://github.com/magento/community-features/issues/302.

For now, you should use composer 1.x while working with Magento installations.

**Comment by rvtechmagento** [comment]
Hi,

**I already instaled composer 2.0.7 in magento.But still it gives me an below error.**

The "magento/magento-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "magento/inventory-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

Thanks

**Comment by rvtechmagento** [comment]
> Hi @rvtechmagento,
> You're having this issue due to missing composer 2 support by magento.
> 
> We have a feature request for that [magento/community-features#302](https://github.com/magento/community-features/issues/302).
> 
> For now, you should use composer 1.x while working with Magento installations.

Hi,

I already instaled composer 2.0.7 in magento.But still it gives me an below error.

The "magento/magento-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "magento/inventory-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

Thanks

**Comment by ihor-sviziev** [comment]
@rvtechmagento as I said above - you should use **composer 1.x**, not 2.x

**Comment by rvtechmagento** [comment]
okay
