### ISSUE TITLE
FileSystem IO Ftp connection ls() method error for empty folders

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#31288]
### Preconditions (*)

1. Magento 2.4-develop
2. Use the FTP connection by `Magento\Framework\Filesystem\Io\Ftp`

Regarding to the PHP documentation `ftp_nlist() `method can return as array and the false,
and in case of empty folder it returns false.
https://github.com/magento/magento2/blob/ad2945209811dc9fb5cd531af8f2a2bace8647f3/lib/internal/Magento/Framework/Filesystem/Io/Ftp.php#L316

Need to add additional check for the (false) case ad not put  result of` ftp_nlist()` directly to the foreach loop

### Steps to reproduce (*)

1. Try to execute ls method of Magento\Framework\Filesystem\Io\Ftp::ls() on empty folder

### Expected result (*)

1. [Screenshots, logs or description]
2.. empty array returned

### Actual result (*)

1. [Screenshots, logs or description]
2. Exception Returned
` Invalid argument supplied for foreach() in vendor/magento/framework/Filesystem/Io/Ftp.php on line 319`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nazar65** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40234` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for your report. 
The issue has been fixed in magento/magento2#31308 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [5559a51bccae19c3b032a3fe17e08047a67aacf8](https://github.com/magento/magento2/commit/5559a51bccae19c3b032a3fe17e08047a67aacf8)
 - [c42d022322d7e6114d6a8cd4b7029adc5e44022a](https://github.com/magento/magento2/commit/c42d022322d7e6114d6a8cd4b7029adc5e44022a)

The fix will be available with the upcoming 2.4.3 release.
