### ISSUE TITLE
WYSIWYG ISSUE

### ISSUE THREAD

**Issue by toantvlf** [magento/magento2#31294]
### Description (*)
When i try use wysiwyg in form backend  i can't click button Show / Hide Editor and Insert Widget... . I checked code and realize that the error is coming from the code of magento.
This is conflict git. https://i.imgur.com/fijhW6u.png
### Preconditions (*)
Bug on Magento version 2.4.0 and 2.4.1
### Steps to reproduce (*)
check file vendor/magento/framework/Data/Form/Element/Editor.php
conflict in function getElementHtml

 $js = $this->secureRenderer->renderTag(
            'script',
            ['type' => 'text/javascript'],
            <<<script
                //<![CDATA[
                openEditorPopup = function(url, name, specs, parent) {
                    if ((typeof popups == "undefined") || popups[name] == undefined || popups[name].closed) {
                        if (typeof popups == "undefined") {
                            popups = new Array();
                        }
                        var opener = (parent != undefined ? parent : window);
                        popups[name] = opener.open(url, name, specs);
                    } else {
                        popups[name].focus();
                    }
                    return popups[name];
                }

                closeEditorPopup = function(name) {
                    if ((typeof popups != "undefined") && popups[name] != undefined && !popups[name].closed) {
                        popups[name].close();
                    }
                }
            //]]>
script
            ,
            false
        );
        
        $html .= $this->secureRenderer->renderTag(
                        'script',
                        ['type' => 'text/javascript'],
                        <<<script
                            //<![CDATA[
                            require(["jquery", "mage/translate", "mage/adminhtml/wysiwyg/widget"], function(jQuery){
                                (function($) {
                                    $.mage.translate.add({$this->serializer->serialize($this->getButtonTranslations())})
                                })(jQuery);
                            });
                            //]]>'
script
                        ,
                        false
                    );

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
Are you sure problem happen in 2.4.0 or 2.4.1 ?
I can't reproduce issue! Can you update details steps by steps for able reproduce issue
<img width="1640" alt="Screen Shot 2020-12-16 at 14 27 37" src="https://user-images.githubusercontent.com/1908873/102317895-f6a60e00-3faa-11eb-9624-d88b059f2582.png">
<img width="1683" alt="Screen Shot 2020-12-16 at 14 28 11" src="https://user-images.githubusercontent.com/1908873/102317913-fd348580-3faa-11eb-9d93-a120c1d3b42d.png">

**Comment by krishprakash** [comment]
Hi @toantvlf. Not able to replicate the issue as provided steps by you 
Can you please provide more details/additional steps to reproduce this issue

**Comment by toantvlf** [comment]
> Are you sure problem happen in 2.4.0 or 2.4.1 ?
> I can't reproduce issue! Can you update details steps by steps for able reproduce issue
> <img alt="Screen Shot 2020-12-16 at 14 27 37" width="1640" src="https://user-images.githubusercontent.com/1908873/102317895-f6a60e00-3faa-11eb-9624-d88b059f2582.png">
> <img alt="Screen Shot 2020-12-16 at 14 28 11" width="1683" src="https://user-images.githubusercontent.com/1908873/102317913-fd348580-3faa-11eb-9d93-a120c1d3b42d.png">

please check screenshot in **Description** 
use \Magento\Cms\Model\Wysiwyg\Config for field editor in form backend https://i.imgur.com/3Hn47Ot.png - custom module
or u can check directly file **vendor/magento/framework/Data/Form/Element/Editor.php**

**Comment by toantvlf** [comment]
> Hi @toantvlf. Not able to replicate the issue as provided steps by you
> Can you please provide more details/additional steps to reproduce this issue

please check screenshot in Description
use \Magento\Cms\Model\Wysiwyg\Config for field editor in form backend https://i.imgur.com/3Hn47Ot.png - custom module
or u can check directly file vendor/magento/framework/Data/Form/Element/Editor.php

**Comment by mrtuvn** [comment]
Can you reproduce issue in clean 2.4.0 or 2.4.1 ? 
Test Case 1 Vanilla install magento no extra customises or 3rd-party modules, custom theme
Test Case 2 Setup with configuration same as your enviroments (provide details)

Description not clearly to me(Can you clean markup or syntax). Sorry I don't understand what you want to describe. Please clarify more! Thanks

**Comment by krishprakash** [comment]
Hi @toantvlf. Feel free to reopen/comment the issue once you confirm that issue reproduced on latest magento 2.4 develop instance
