### ISSUE TITLE
Install EE via Metapackage

### ISSUE THREAD

**Issue by jksimoniii** [magento/magento2#3130]
I am seeing the following

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition <installation directory name>

  [InvalidArgumentException]                                                        
  Could not find package magento/project-enterprise-edition with stability stable.
```

I have secure keys generated, but I am never being prompted to enter them

**Comment by ghost** [comment]
Hi, I pasted your command into a terminal window, was prompted for a user name and password, and the download appears to be progressing normally. Unfortunately, I do not know what your issue is.

**Comment by mazhalai** [comment]
@jksimoniii can you try deleting `repo.magento.com` details in your `~/.composer/auth.json`  file and then try again? Also, try cleaning composer cache with `composer clear-cache` 

Also, please report EE details to the partner portal and not on Github, which is for community related issues.

**Comment by jksimoniii** [comment]
@mazhalai Thank you for this.  I am now being prompted for credentials.  But, after enter credentials I am getting the following.  Would you like me to close this issue and move discussion to partner portal?

```
[InvalidArgumentException]                                                        
  Could not find package magento/project-enterprise-edition with stability stable.
```

**Comment by mazhalai** [comment]
@jksimoniii yes please. closing this ticket for now.

**Comment by michaeldyl520** [comment]
> cleaning composer cache with `composer clear-cache`

add `auth.json` to `~/.composer`, then we can use command `composer create-project --repository=https://repo.magento.com/ magento/project-enterprise-edition:2.2.6 m226`.

**Comment by murali290987** [comment]
Try like this, 
composer config --global http-basic.repo.magento.com {public key} {private key}.

It worked for me.
