### ISSUE TITLE
[Multishipping] Custom Price issue

### ISSUE THREAD

**Issue by PierreLeMaguer** [magento/magento2#31301]
### Preconditions (*)

1. Magento version CE 2.3.6

### Steps to reproduce (*)

I don't know how reproduce natively with Luma Theme, but here the conditions to reproduce with few developments
1. Having Multi Shipping enabled
2. Having the One Page Checkout disabled
3. Add a simple product to cart
4. Having a development which sets a custom price and an original custom price to the quote item
5. Go to the Checkout

### Expected result (*)

1. The custom price set to the quote item is used for the quote address item. 

### Actual result (*)

1. [Screenshots, logs or description]
![screenshot-magento-ce-2-3 lxc-2020 12 16-12_09_13](https://user-images.githubusercontent.com/19976778/102341182-c012c800-3f97-11eb-9a81-0f496c1e4a0a.png)
![screenshot-magento-ce-2-3 lxc-2020 12 16-12_09_58](https://user-images.githubusercontent.com/19976778/102341168-bab57d80-3f97-11eb-8739-e9e9d727f53a.png)
The custom price of the quote item is not used when the multi shipping is enabled. Everything works well when it is disabled.

### Solution
The issue is the following: in this case, we have:
vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php l90 $item is an instanceof AddressItem, so we give a quote address item to vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php::_calculateRowTotal . Then in vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php::getCalculationPriceOriginal we don't have the original_custom_price data because it does not exist for quote address item.

The solution could be to add custom_price and original_custom_price to the table quote_address_item and 
edit the method vendor/magento/module-quote/Model/Quote/Address/Item.php::importQuoteItem to set the custom price of the quote item.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by edenduong** [comment]
@magento give me 2.4-develop instance

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.

**Comment by ilnytskyi** [comment]
> The issue is the following: in this case, we have:
vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php l90 $item is an instanceof AddressItem, so we give a quote address item to vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php::_calculateRowTotal . Then in vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php::getCalculationPriceOriginal we don't have the original_custom_price data because it does not exist for quote address item.

>The solution could be to add custom_price and original_custom_price to the table quote_address_item and
edit the method vendor/magento/module-quote/Model/Quote/Address/Item.php::importQuoteItem to set the custom price of the quote item.

I think there is a wider problem. Not only related to custom price. Total is collected for Address/Item without updating Quote/Item object. Later when you use `$quote->getAllVisibleItems()` the items have wrong data. And in DB `quote_item` have older data than `quote_address_item`

Other problem is that both objects have slight difference in it's fields and behavior.

**Comment by dverkade** [comment]
L.s.,
 
Ik ben t/m 4 Maart niet aanwezig. Het e-mail bericht wordt niet automatisch doorgestuurd. Na mijn terugkomst zal ik wanneer nodig op het verstuurde bericht reageren. Voor dringende zaken kan er contact worden opgenomen met mijn collega Marcel van Wijk per e-mail ***@***.*** of telefoon 010-7536090. 
 
I'm not in the office until the 4th of March. Your e-mail will not be forwarded. I'll respond to it when I'm back at the office. You can contact my coworker Marcel van Wijk for urgent matters per e-mail ***@***.*** or phone +31 10 7536090. 
 
Danny Verkade

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @PierreLeMaguer 

We are closing this issue as the PR - https://github.com/magento/magento2/pull/31309 is closed. 

Thanks.
