### ISSUE TITLE
Where is the Cancel Shipment functionality ?

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#31319]
### Preconditions (*)

Regarding this documentation https://docs.magento.com/user-guide/v2.3/sales/shipment-cancel.html
There must be such functionality to cancel only shipment,
But from code There is no any button for that action, you have ability to only cancel the whole order and then it will cancel the shipping amounts.

this is the only place where the shipment with whole order can be canceled

https://github.com/magento/magento2/blob/ad2945209811dc9fb5cd531af8f2a2bace8647f3/app/code/Magento/Sales/Model/Order.php#L1284

So this functionality is not implemented ?

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nazar65** [comment]
@magento I am working on this

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41449` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
