### ISSUE TITLE
in MAgento2.4 <all/V1/integration/admin/token> asking for <Please use the 2fa provider-specific endpoints to obtain a token.>

### ISSUE THREAD

**Issue by YouCanDoIt12** [magento/magento2#31314]
### Preconditions (*)

1.Magento 2 Version community 2.4.0

2. enable 2FA

### Steps to reproduce (*)

1. make a post-call to all/V1/integration/admin/token with body {username: 'xx', password:'yy'}

### Expected result (*)

1. Should give a token in the response
2.

### Actual result (*)

1.Asking for 2 FA configuration
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- effecting to integrate rest API with other system

**Comment by 13mcmc12** [comment]
if i want to integrate the M2 order rest API to fetch order to an external system, so how can I make a connection to M2 , so i no need to enter 2FA code every time when I need a bearer token to get orders

**Comment by 13mcmc12** [comment]
Hi @engcom-Bravo any update on above issue

**Comment by engcom-Bravo** [comment]
Hello @13mcmc12 

Did you try to use _/V1/tfa/provider/google/authenticate_ ? We have tested via this request and we successfully get the token.

![auth](https://user-images.githubusercontent.com/51680745/102618765-09077f80-4144-11eb-951f-fe493d521d78.png)

https://devdocs.magento.com/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.html

**Comment by 13mcmc12** [comment]
@engcom-Bravo  for this tfa API I have to add OTP from the google authentication app in every 4 hours or based on the configuration for the bearer token. 
now if I want to access Magento 2 rest API every time I have to regenerate the bearer token myself and add it to my script in every 4 hours.

Now my question is how can I automate this process, earlier I have a script which will check the token is expired or not, and if expired it will make a call to all/V1/integration/admin/token with admin creds and regenerate the token.

now with this tfa API, we have to enter otp every time. how can we access the rest API without any manual effort.

**Comment by engcom-Bravo** [comment]
@13mcmc12 By default, an admin token is valid for 4 hours. To change this value, log in to Admin and go to _Stores > Settings > Configuration > Services > OAuth > Access Token Expiration >_ **Admin Token Lifetime** (hours).

The other way to get an access token is to **Add New Integration** in _System > Integrations _ **Activate** it and use the _Access Token_
![token](https://user-images.githubusercontent.com/51680745/102624349-8cc56a00-414c-11eb-87e8-44b701eeb903.png)

**Comment by 13mcmc12** [comment]
@engcom-Bravo  Thanks
