### ISSUE TITLE
Product Prices And Cart Prices With Tax Setting From Configurations Are Not Showing In Graphqls

### ISSUE THREAD

**Issue by deepanshuyadav87** [magento/magento2#31313]
### Preconditions (*)

1.Magento 2.3.4

### Steps to reproduce (*)

1. Set the tax class for product and customer
2. Set the tax configurations from Sales->Tax->Calculation Settings, Sales->Tax->Price Display Settings
![taxconfig](https://user-images.githubusercontent.com/76148264/102455242-3f220200-4065-11eb-9b55-06289371858b.png)

3. Get the product data from products Graphql using this query
query{
  products(
      filter:{
        sku:{eq:"Ammdent-RustOC"}
      }
    ){
      items{
          special_price
          price{
            minimalPrice{
                amount{
                    value
                }
            }
            maximalPrice{
                amount{
                    value
                }
            }
            regularPrice{
                amount{
                    value
                }
            }
          }
          price_range{
            minimum_price{
                regular_price{
                    value
                    currency
                }
                final_price{
                    value
                }
                discount{
                    percent_off
                    amount_off
                }
            }
            maximum_price{
                regular_price{
                    value
                    currency
                }
                final_price{
                    value
                    currency
                }
            }
          }
  }
}

### Expected result (*)

1. Graphql response contains product prices having **tax** (_including/excluding_) (**excl. tax**=21000, **incl tax**=23520 )according to Sales->Tax configurations

![ammdentCortRes](https://user-images.githubusercontent.com/76148264/102455211-316c7c80-4065-11eb-9271-b8b426457d01.png)

### Actual result (*)

1. Response contains the price(_in image_,21000 ) values without the calculation of tax which was saved in the tax configurations 
![productsGql](https://user-images.githubusercontent.com/76148264/102454772-878cf000-4064-11eb-8be8-813165ec39cf.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mauragcyrus** [comment]
@magento export issue to Jira project MCLOUD as Bug

**Comment by oneserv-heuser** [comment]
Any updates on this? We would need this feature.

**Comment by engcom-Hotel** [comment]
Hi @deepanshuyadav87,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop but the graphQL request works as expected, it is returning data as per the tax settings.

Steps followed to reproduce issue:

1. Go to Sales->Tax->Calculation Settings, Sales->Tax->Price Display Settings and update the setting as per the screenshot given in the ticket.

2. Verify the product price on the store products.

3. Execute the GraphQL query as given in the ticket, before updating the tax settings and after updating the tax settings.

4. Observe the product price on the store product and in the GraphQL output. (Please see the attached video)


It might be possible this issue has been addressed already, hence we are closing this issue for now. If you still facing this issue, then you can reopen it.

https://user-images.githubusercontent.com/51681618/141779197-45f8a11f-af7d-4b08-8a07-b0f605372ce3.mp4


Thanks
