### ISSUE TITLE
Translation i18n:pack command failed in Phrase.php, because of single quote characters in text

### ISSUE THREAD

**Issue by clarenceh** [magento/magento2#3132]
I am trying to translate the labels and text into Chinese and following the i18n guide.

Version using:
- Magento: 2.0.1
- PHP: 7.0.2

Steps:
- Collect the phrases in English (this is OK)
  
  ```
  php bin/magento i18n:collect-phrases -o "tmp/zh_HK.csv" -m .
  ```
- Perform my translation by updating the generated zh_HK.csv file
- Submit the package to packagist and install the language module using composer
  - the language pack was installed in (MAGENTO_ROOT)/vendor/skywidesoft/magento2-language-zh_hk
- Run the package language command
  
  ```
  php bin/magento i18n:pack --mode=merge -d vendor/skywidesoft/magento2-language-zh_hk/zh_hk.csv . zh_Hant_HK
  ```

Then I got the following error:

> PHP Parse error:  syntax error, unexpected '' is not found'' (T_CONSTANT_ENCAPSED_STRING), expecting ';' in /var/www/html/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php(278) : eval()'d code on line 1

Workaround:
I need to replace all single quote characters ("'") in the zh_HK.csv file with empty string in order for the command to succeed.

Sample text line in CSV file with single quote character:
"We couldn\'t remove the messages because of an error.","We couldn\'t remove the messages because of an error.",module,Magento_AdminNotification

Suspect that the i18n tool is having issue in packing the language with single quote characters in it.

Regards
Clarence

**Comment by clarenceh** [comment]
Hi, 

I found that after a change to the program Phrase.php, I can get the language pack command ran successfully. I post it here to see if I am doing things correctly.

File: (MAGENTO_ROOT)/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php

From code:

```
if (count($matches[0]) % 2 !== 0) {
    $string = addslashes($string);
}
```

To code:

```
if (count($matches[0]) > 0) {
    $string = addslashes($string);
}
```

Kindly advice and thanks
Clarence

**Comment by dynamogold-bkre** [comment]
#3303 - having the same issue

**Comment by dynamogold-bkre** [comment]
https://community.magento.com/t5/Technical-Issues/Problem-with-i18n-translation-collection-command-PHP-Parse-error/td-p/24879 reporting the same issue in the Magento forum

**Comment by mazhalai** [comment]
Internal ticket MAGETWO-50078

**Comment by Zatara7** [comment]
Hi @clarenceh we have changed the logic that you mentioned. Could you please checkout the develop branch. I just ran the collect command again on php 7.0.2 and then the pack command and got no issues. Also to update your packagist repository here's the file with the newly collected phrases: http://sprunge.us/IfPG :) or you can just collect again
