### ISSUE TITLE
Extend conditions functionality

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3133]
There is that nice UI to provide conditions to filter products, cart attributes etc. I could not find any documentation how such functionality should be extended for custom module.

Based on **module-catalog-rule** and **module-sales-rule** modules I was able to implement conditions UI and saving corresponding values(conditions_serialized) but I am not able to apply those conditions to get filtered products.

How can I implement conditions in a custom module? How can I use(apply) conditions? How to add custom conditions e.g. product type?

<img width="857" alt="conditions" src="https://cloud.githubusercontent.com/assets/1607778/12573983/2f5a15ee-c408-11e5-8942-12b292037a6e.png">

**Comment by rganin** [comment]
Rule conditions are property-based. Product type is not a property, semantically it`s a class of products that may have common properties. However products can have different attribute sets and rule can be based on it.
By default only few attributes are available for rules creation, you can turn on any product attribute to be available for rules creation in attribute configuration: Open Stores -> Attributes -> Products, choose an attribute, open StoreFront Properties tab and set "Use for Promo Rule Conditions" flag to "Yes".
Any attribute may have custom backend model to store/fetch property to/from DB, configuration or 3rd party system API and Magento will validate product to match condition on rule reindex.

**Comment by jsakars** [comment]
@rganin thanks! However that does not answer the main question - how can I apply(use) conditions set for my custom module to get product collection that matches them?

**Comment by tudn9x** [comment]
Hi @werdlv  you can try this files:
- mview.xml in folder etc
- ApplyRules.php in Plugin/Indexer/Product/Save
- All files in Model/Indexer

At folder magento-catalog-rule
I am sorry, my english is bad.

**Comment by jsakars** [comment]
Turns out [this](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogRule/Model/Rule.php#L282-L306) holds the answer. Conditions are not applied - instead each model(product in this case) is validated against conditions like so `$this->getConditions()->validate($product);`
