### ISSUE TITLE
[GraphQL] Store validation executes after defining current store

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#31336]
During working on https://github.com/magento/magento2/pull/31263 we found that just making General session a proxy instead of the regular object causing GraphQL web API test failures.

During my investigation (details in https://github.com/magento/magento2/pull/31263#issuecomment-747499196), we found that for some reason the method that sets the current store is executing BEFORE the method that does validation for that store and not doing any validation inside (so it's not failing).
As result - any code on later steps will fail when it will try to get the current Store  (`$this->scopeCodeResolver->resolve('store', 'null')`) and fails with NoSuchEntityException.

**Note 1:** as a workaround in scope of https://github.com/magento/magento2/pull/31263 we added following line to the app/code/Magento/GraphQl/etc/graphql/di.xml, that should be removed once this issue will be resolved.
```xml
    <preference for="Magento\Framework\Session\SessionManagerInterface" type="Magento\Framework\Session\Generic" />
```
**Note 2:** seems like the following change also not required in the scope of the GraphQL area and was added as a workaround to this issue, need to double-check that also:
https://github.com/magento/magento2/pull/26032/files#diff-5a258589534652449d6d2a5484b3f175168b02d80722ac29aee29669ab371f37R10

### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Set breakpoint on `Magento\StoreGraphQl\Controller\HttpRequestValidator\StoreValidator::validate`
2. Set breakpoint on `\Magento\StoreGraphQl\Controller\HttpHeaderProcessor\StoreProcessor::processHeaderValue`
3. Execute ANY graphql request with a Store header.

### Expected result (*)
1. `Magento\StoreGraphQl\Controller\HttpRequestValidator\StoreValidator::validate` should be executed first
2. `\Magento\StoreGraphQl\Controller\HttpHeaderProcessor\StoreProcessor::processHeaderValue` should be executed 2nd

### Actual result (*)

1. `\Magento\StoreGraphQl\Controller\HttpHeaderProcessor\StoreProcessor::processHeaderValue` executes 1st
2. `Magento\StoreGraphQl\Controller\HttpRequestValidator\StoreValidator::validate` should be executed 2nd

### Aditional info from Engcom
Use, for example, the following GraphQL mutation
```graphql
mutation {
  createCustomer(
    input: {
      prefix: "Prince"
      firstname: "John"
      suffix: "IV"
      middlename: "Ruel"
      lastname: "Doe"
      email: "John.Doe@example.com"
      gender: 1
      password: "123123qA"
    }
  ) {
    customer {
      firstname
      lastname
      email
    }
  }
}
```
With HTTP Header
```graphql
{
  "Store": "default"
}
```
Breakpoint in file _.../app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php_
![bp1](https://user-images.githubusercontent.com/51680745/103363454-c9d21a80-4ac3-11eb-8a43-766ed45168db.png)

Breakpoint in file _.../app/code/Magento/StoreGraphQl/Controller/HttpRequestValidator/StoreValidator.php_
![bp2](https://user-images.githubusercontent.com/51680745/103363545-01d95d80-4ac4-11eb-9346-eac260f1f95c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @ihor-sviziev 

Thank you for your report.

We Confirm the issue, and we have added Additional info form Engcom to the Description

Thank you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40260` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-November** [comment]
Hi @ihor-sviziev 
Development team is working on this issue.
Thank you.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-821 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-821&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.
