### ISSUE TITLE
2FA input not requesting focus (Firefox browser)

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#31333]
### Preconditions (*)
1. 2 Factor Authentication is enabled for the backend
2. **Firefox browser**. Not reproducible on Google Chrome

### Steps to reproduce (*)
1. Login by providing username and password
2. Start typing the 2FA code without using the mouse

### Expected result (*)
1. The 2FA input field has requested the inition keyboard focus and the code is entered into the correct field
![login](https://user-images.githubusercontent.com/67371013/102602318-0b5ce000-412a-11eb-92a2-19ff809b3de4.gif)

### Actual result (*)
1. no input field has the focus and the typed code is not entered unless the user clicks the input field
![Firefox](https://user-images.githubusercontent.com/51680745/102612048-baa0b380-4138-11eb-94f3-5523f0e8f75f.gif)

As the 2FA code for accessing the backend is absolutely critical,
it must never appear to the user as if the code was entered into anything but the input field to maintain trust.
Therefore choosing severity S1 for this technically trivial issue.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Pavel-Fekete** [comment]
Hello @YiffyToys 

I can't reproduce this issue according to your steps, input field is in focus without using the mouse
![login](https://user-images.githubusercontent.com/67371013/102602318-0b5ce000-412a-11eb-92a2-19ff809b3de4.gif)
Please correct me if I'm doing wrong steps.

**Comment by YiffyToys** [comment]
Strange. This is Firefox 84.0 on Windows 10 and it doesn't work in Magento 2.4.1.
(It does work in other the AN entry field for online banking forcing the keyboard focus.)


It seems that "autofocus is defined to work reliably only on page load."
In my case, the 2FA field need an additional second or two to apear. That may be a possible cause as your apears instantly.
So it is not a page load anymore. Maybe only Javascript can force the focus at that point.


Inspection shows the 2FA input field to be:
<input data-bind="value: verifyCode, enable: !waitText()" id="tfa_code" class="admin__control-text" type="text" autofocus="" placeholder="Your code'">
Another possibility is that the "autofocus" attribute apears to not be supposed to be a key-value pair but just a key. Could it be that your browser is handling this illegal HTML diffrently?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40020` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment]
https://github.com/magento/security-package/tree/develop/TwoFactorAuth
I think better add issue to this repo ! Well this module belong another repo and not included in magento repo

**Comment by YiffyToys** [comment]
> 
> 
> https://github.com/magento/security-package/tree/develop/TwoFactorAuth
> I think better add issue to this repo ! Well this module belong another repo and not included in magento repo

I don't understand your sentence.
Are you asking somebody else if it is a good idea to do that?
Are you informing everyong that you are about to do that or have done that?
Are you asking anyone specific to please do that?

**Comment by YiffyToys** [comment]
not blocking

**Comment by dverkade** [comment]
Confirmed issues can't be closed automatically.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mrtuvn 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40020` were created

**Issue Available**: @mrtuvn, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance
