### ISSUE TITLE
Placeholder is missing

### ISSUE THREAD

**Issue by mnohai** [magento/magento2#31339]
At the moment it removes all link types

https://github.com/magento/magento2/blob/445b0f1a3d6a91b5da32d311077c2112ef0b1503/app/code/Magento/CatalogImportExport/Model/Import/Product/LinkProcessor.php#L223

**Comment by engcom-Delta** [comment]
Hi @mnohai thank you for your report. Please update issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) . Actual and expected result would be helpful
