### ISSUE TITLE
Update sebastian/phpcpd dependency version to "~6.0.3"

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31344]
### Description (*)
Update sebastian/phpcpd dependency version to "~6.0.3"

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @hws47a. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39654` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
