### ISSUE TITLE
Update friendsofphp/php-cs-fixer dependency to PHP 8 Compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31343]
### Description (*)
Update friendsofphp/php-cs-fixer dependency version to "~2.18.0"

**Comment by hostep** [comment]
Version [2.18.0](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases) was released a couple of days ago, does it make sense to directly move to that version?

**Comment by sivaschenko** [comment]
@hostep yes, thank you! Updated. cc @konarshankar07

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @konarshankar07. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39653` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
