### ISSUE TITLE
Installation Not Working : even from GitHub or Magentocommerce.com

### ISSUE THREAD

**Issue by benyaminl** [magento/magento2#3134]
I don't know why but I think this's a big problem, I can't even install magento2 from browser, it always show this kind of page. It redirect to setup but seems like broken, Please I need help...
![mag](https://cloud.githubusercontent.com/assets/2817332/12574289/298626c6-c435-11e5-9e17-482b412813be.jpg)

It's 2.0.1, all req is fulfilled, I'm on XAMPP windows, I tried using fresh code by clone from git and using composer, still result the same, even all composer and framework all passed.

**Comment by mrkhoa99** [comment]
Hello,
Did you download Magento 2.0.1 version from official website: https://www.magentocommerce.com/download

**Comment by thaiphan** [comment]
Can you open up your inspector and show us the output? Might give us some insights into why nothing is loading properly!

**Comment by benyaminl** [comment]
Yes, I'm, it's from magento.com

Benyamin Limanto

sent from my ASUS

**Comment by mazhalai** [comment]
@benyaminl please check if all the [required permissions](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html) are set. Also, check if there are any errors in your browser's developer console.

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
