### ISSUE TITLE
Update elasticsearch/elasticsearch dependency version to "~7.11.0"

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31341]
### Description (*)
Update elasticsearch/elasticsearch dependency version to "~7.11.0"
(https://github.com/elastic/elasticsearch-php/tree/7.11)

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by hws47a** [comment]
Closed 😢

**Comment by sivaschenko** [comment]
@hws47a the issue was closed as your pull request is delivered, thank you!

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @hws47a. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39650` was closed as `Complete`.
