### ISSUE TITLE
Update laminas/laminas-server dependency version to "^2.9.1"

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31347]
### Description (*)
Update laminas/laminas-server dependency version to "^2.9.1"

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @konarshankar07. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39675` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
