### ISSUE TITLE
Update pelago/emogrifier dependency version to "^5.0.0"

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31342]
### Description (*)
Update pelago/emogrifier dependency version to "^5.0.0"
https://packagist.org/packages/pelago/emogrifier

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @konarshankar07. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39651` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
