### ISSUE TITLE
Rapidflow Export Issue

### ISSUE THREAD

**Issue by nicololamigo** [magento/magento2#31349]
### Preconditions (*)

1. Magento ver. 2.3.3-p1
2. Rapidflow

### Steps to reproduce (*)

1. Export data attributes via Rapidflow
2. Include these attributes stock.is_in_stock, gsa_fssi_category, product.websites,Category.path

### Expected result (*)

1. These attributes should have data values as attached to the picture below.

### Actual result (*)

1. No data when exported. Checked with the backend and it has values.

![image](https://user-images.githubusercontent.com/76213632/102622754-50ffb580-40f6-11eb-9f86-b07f3fbb0f9a.png)

**Comment by paales** [comment]
@nicolecornelson You should contact the developers of Rapidflow to solve the issues :)

**Comment by engcom-Delta** [comment]
Hi @nicololamigo thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.4-develop as magento default export functionality save created product attributes into `additional_attributes` column
**Result:**
:heavy_check_mark: Created dropdown attribute `test` is shown in scv file
![image](https://user-images.githubusercontent.com/51681379/102886555-fe0f6080-445d-11eb-830d-b37edb1d7ebf.png)

Please refer to Rapidflow support as it is 3rd party extension
