### ISSUE TITLE
Update laminas/laminas-servicemanager dependency version to "^3.5.1"

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31346]
### Description (*)
Update laminas/laminas-servicemanager dependency version to "^3.6.0"

**Comment by konarshankar07** [comment]
@magento I'm working on this

**Comment by Den4ik** [comment]
@sivaschenko As I see php 8 support officially added from 3.6.0 https://github.com/laminas/laminas-servicemanager/releases/tag/3.6.0

**Comment by sivaschenko** [comment]
@Den4ik that's correct, thank you, updated description.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ProkopovVitaliy, @konarshankar07. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39667` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
