### ISSUE TITLE
Generating Invoice does recalculate tax but wrong!!!

### ISSUE THREAD

**Issue by chequille** [magento/magento2#31366]
@srenon
Thanks for this. I made the changes manually. It is only one line to change :)
After chaning the page break when showing an invoice with zero tax did not happen again. So far so good.
But unfortunately, I found another bug regarding tax. It seems in 2.4.1 there are a lot of changes which did not solve problems but made new problems. I will show you what I found:
1. Tax calculation is set in my system to "afterdiscount"
2. I have a coupon for a special product at 49,-€ which reduces this amount 100% and no delivery costs are applied. Therefore, customer does not have to pay something. The invoice total and tax must be ZERO
3. This working perfectly in my 2.3.5 store which is online

No, I show ou with some screenshots what happens in 2.4.1
I placed an order with a coupon code and the product I mentioned above.
Bank transfer payment, so invocie is not generated.
In the backend the order shows the following totals and tx amount which are correct, all zero !!!!
![grafik](https://user-images.githubusercontent.com/15807794/101965581-77fd4980-3c15-11eb-83c4-af4c14388572.png)

So far so good, but now I generate the invoice for this order and after doing so, we suddenly have a non zero total. Tax still says zero, but total is increased with 16% of 49,-€, definetely wrong!!!!!!! (16% is our current tax rate)
![grafik](https://user-images.githubusercontent.com/15807794/101965735-fe199000-3c15-11eb-8818-dfb3f8e49cd0.png)

This is a very strange bug and I hope this will be solved very soon, as well with some patches, because waiting for the next release is probably to long.

Looking forward to hearing from you.

Best regards,
Chequille

**Comment by engcom-Bravo** [comment]
Hello @chequille 

Thank you for your report

We have rechecked the reported issue on 2.4.1 and on 2.4-develop versions
Here are the steps we performed:
1. _Apply Customer Tax_ is set to **After Discount** in _Stores - Configuration - Sales - Tax - Calculation Settings_
![after_discount](https://user-images.githubusercontent.com/51680745/102899550-c27f9100-4473-11eb-8a34-e919dab4877c.png)
2. _Bank Transfer payment_ is Enabled and configured in _Stores - Configuration - Sales - Payment Methods_
3. **New Tax Rule** added with tax Rate of 5% for all US users under _Stores - Tax Rules_
4. **Cart Price Rule** created in _Marketing - Cart Price Rule_ 
- With a _Specific Coupon_
![spec_cupon](https://user-images.githubusercontent.com/51680745/102905815-5ead9600-447c-11eb-9d29-511e73c42732.png)
- 100% Product discount **Applied** under _Actions_ (**Also chcked Fixed amount discount of 99 and a product with price 99$**)
![100percent](https://user-images.githubusercontent.com/51680745/102906071-cbc12b80-447c-11eb-9ddb-b84799312692.png)
5. From the Storefront, Sign In as a customer with US Address
6. Add any product to Cart
![cart_withot_coupon](https://user-images.githubusercontent.com/51680745/102906664-9f59df00-447d-11eb-946f-c1092669ba7a.png)
7. Apply the previously created Coupon and assert that the discount is applied
![cart_with_coupon](https://user-images.githubusercontent.com/51680745/102906910-f6f84a80-447d-11eb-864f-92241b92137e.png)
8. Place the order
9. Go to Admin Panel _Sales - Orders_ and **View** the previously created order
10. Click **Invoice**
11. Click **Submit Invoice**

***Actual Result**
The order totals display 0
![submit_invoice](https://user-images.githubusercontent.com/51680745/102907260-7be36400-447e-11eb-811d-2cd6b21821e8.png)

Can you please provide more info, correct our steps and explain the "_coupon for a special product_"

Thank you in advance

**Comment by chequille** [comment]
Hi,
must be honest, did not see, that htere is already another ticket saying exactly the same. It is ticket #30853
In this ticket, the error was reproduced and as well I do have it.
What I see in your picture above, you are looking at the order page not at the invoice page. Because on the order page everthing is still correct.
But look at the invoice page, there it is wrong as in my picture above.
Or just print the invoice to pdf and you will see there as well a not zero total.

Please try again, as I am not the only one facing this problem.
Thanks and best regards
Chequille

**Comment by chequille** [comment]
Hi,
I made a change in Magento_Sales/Modul/Order/Invoice/Total/Tax.php and removed the $totalDiscountTaxCompensation and §baseTotalDiscountTaxCompoensation values in line 121 and 122 so it looks like below.

$invoice->setGrandTotal($invoice->getGrandTotal() + $totalTax); 
$invoice->setBaseGrandTotal($invoice->getBaseGrandTotal() + $baseTotalTax);

Doing so, my total value is 0 as it should.

Where is this tax compensation coming from and for what reason is it?

Do you have any explanation for it and what will be the solution?

Best regards,
Jürgen

**Comment by engcom-Bravo** [comment]
@chequille Yes you are right, the https://github.com/magento/magento2/issues/30853 it the same issue
So we are closing this as Duplicate
Please, follow all the updates in that issue

Thank you
