### ISSUE TITLE
/etc/nginx/html/pub/index.php" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by asd99557** [magento/magento2#31367]
### Preconditions (*)

1. setup configured using docker file create 3 container like nginx php and mysql
2.also added another container like Elasticsearch rarebitmq.
2.bind volume in host system.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1.After install magento when open page given below error /etc/nginx/html/pub/index.php" failed (2: No such file or directory)
2.

### Actual result (*)

1.after cli command wheni run it will showing magento admin page.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
Hi @asd99557. Kindly update all the details Steps to reproduce, actual and expected result as per [issue reporting guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Without such details, this issue could be closed

**Comment by asd99557** [comment]
Issue was resolve.
