### ISSUE TITLE
Admin Analytics - Enable Admin Usage endpoint without exception handling

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#31393]
### Summary (*)
**Context**: When learning Magento, many developers look around for small examples of "Best Practices" to follow. One of such is Admin Analytics setting update endpoint.

**Issue**: The response is hardcoded in the endpoint, so if an exception occurs on Settings save, there's no information about such exception in the logs. The response becomes HTTP 503, instead of returning information about the error.

### Examples (*)
https://github.com/magento/magento2/blob/5372c61f08ee4a0a8c3179af6ba9667243e8a548/app/code/Magento/AdminAnalytics/Controller/Adminhtml/Config/EnableAdminUsage.php#L71-L82

### Proposed solution
There should be an error handling mechanism, that returns error JSON, instead of a hardcoded success response.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40256` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dverkade** [comment]
This is not a stale issue, PR is in progress and issue is ready for work. This issue can't be closed automatically.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by lbajsarowicz** [comment]
@dverkade  - There's no progress in the PR for 6 months already.
The closed issue goes away, as it's no longer Adobe's problem.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-40256` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
