### ISSUE TITLE
No alive nodes found in your cluster in magento2.4.1

### ISSUE THREAD

**Issue by ajmalbuffy** [magento/magento2#31416]
**Summary of the issue:**
Getting No alive nodes found in your cluster in Magento 2.4.1. I have installed the magento2.4.1 version using composer install and CLI and added the sample data with the CLI. Then when I go to Magento admin panel --> STORES --> Configuration --> CATALOG --> Catalog --> Catalog Search but am getting Connection failed! Test again?. How to resolve this?

I have tested the connection with an elastic search using the comment **curl localhost:9200**  and confirmed am getting success response. 

**Information on your environment**
Elasticsearch version 7.10.1 
PHP version 7.3.25
MySQL version 5.7
Apache version 2..37
Magento version 2.4.1
Centos 8

**Steps to reproduce**
Download and install Magento 2.4.1 and it's dependencies 
Goto Magento admin panel --> STORES --> Configuration --> CATALOG --> Catalog --> Catalog Search 
Click Test Connection button

**Expected result:** 
Successful! Test Again?

**Actual result**
Connection failed! Test Again?
![Screenshot from 2020-12-23 15-23-04](https://user-images.githubusercontent.com/11898037/102984041-fd94c980-4532-11eb-88f4-a5c432a3f4c7.png)
![Screenshot from 2020-12-23 15-23-00](https://user-images.githubusercontent.com/11898037/102984089-0a192200-4533-11eb-9a0c-ec5bd9b7d031.png)
![Screenshot from 2020-12-23 15-10-03](https://user-images.githubusercontent.com/11898037/102984107-12715d00-4533-11eb-8338-dd3491d0e41a.png)

**Comment by engcom-Delta** [comment]
Hi @ajmalbuffy thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and on 2.4.1 with sample data
**Result:**
:heavy_check_mark: Success message `Successful! Test Again?` is shown
![Screenshot from 2020-12-28 14-16-52](https://user-images.githubusercontent.com/51681379/103215618-91dca300-491c-11eb-9995-db2c05e124ba.png)

Are you able to reproduce this issue on 2.4-develop?

**Comment by ajmalbuffy** [comment]
@engcom-Delta thanks for spending time on this. Yes, I can reproduce this issue.

**Comment by ajmalbuffy** [comment]
@engcom-Delta can I get your  elasticsearch.yml file for comparison

**Comment by engcom-Delta** [comment]
@ajmalbuffy sorry for delay. Disabled Magento_TwoFactorAuth module should not affect to elasticsearch connection.
My elasticsearch.yml:
[elasticsearch.yml.txt](https://github.com/magento/magento2/files/5925715/elasticsearch.yml.txt)

Elasticsearch version:
![image](https://user-images.githubusercontent.com/51681379/106893266-f8ac6380-66f5-11eb-9423-eed5364fa60f.png)
