### ISSUE TITLE
Cannot read property 'is_region_required' of undefined.

### ISSUE THREAD

**Issue by zolotokrylin** [magento/magento2#3142]
I have out of the box Magento 2 with standard Luma template. In General settings turned of all countries except China. Since then having a problem in this URL location: ./checkout/ 
![screen shot 2016-01-26 at 18 26 18](https://cloud.githubusercontent.com/assets/1125014/12578205/532d36a2-c45a-11e5-8e31-18b2f7e53f1a.png)

How can I fix this problem? I also have set the  Default Tax Destination Calculation to China.

Thanks in advance, guys!

**Comment by ishakhsuvarov** [comment]
@hommedeplage Thank you for reporting this issue. We have already fixed a similar problem in #2933, could you please update and check if issue still persists?
