### ISSUE TITLE
Fresh magento  upload in server then not work magento 2

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#3144]
How to solve ....
![magento](https://cloud.githubusercontent.com/assets/16436069/12578473/288dd018-c447-11e5-8854-5b6ff3193569.png)

**Comment by mrkhoa99** [comment]
Hello,

You need to upgrade your PHP version 5.5.x or later. Magento doesn't support your current PHP version.
http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html
http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html

**Comment by mazhalai** [comment]
@mitulispace what is your PHP version?

**Comment by mitulispace** [comment]
@mazhalai 

![server_error](https://cloud.githubusercontent.com/assets/16436069/12605114/a6722a60-c4e7-11e5-9920-3f9f6eb77983.png)

**Comment by mazhalai** [comment]
@mitulispace your php version is 5.3 which is not supported. You need 5.5 or higher. Also, your mysql version of 5.5 is not supported, it should be 5.6 or higher.
