### ISSUE TITLE
ayuda subir videos en pages

### ISSUE THREAD

**Issue by akimaagustin** [magento/magento2#31459]
Hola, no me deja subir vídeos en pages ni iframe, ni windows media, me da error al subir el vídeo y no logro conseguir incrustar un video en mi page de la tienda magento, ayuda, gracias.

**Comment by akimaagustin** [comment]
No me reconoce ni link de youtube ni tampoco iframe ni nada desde el panel.

**Comment by krishprakash** [comment]
Hi @akimaagustin, Kindly update all the details as per [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Steps to reproduce, actual and expected result, screens that illustrate problem will help a lot.
Without such details, this issue could be closed

**Comment by krishprakash** [comment]
Also update all the details in English only

**Comment by krishprakash** [comment]
Hi @akimaagustin, Feel free to reopen the issue once you update all the details as per issue reporting guidelines and In english only. Thanks!!
