### ISSUE TITLE
Unable to access production dashboard

### ISSUE THREAD

**Issue by michealcarroll** [magento/magento2#31477]
### Preconditions (*)
 

1.  
https://www.hydeparkjewelers.com/hydepark_admin/admin/dashboard/index/key/913cd5d80331d5fb5fe1ce1a183846c0c9b49a63e8a97f90f63093cf0b5b0c7b/

2. 

### Steps to reproduce (*)

1. got to url  
https://www.hydeparkjewelers.com/hydepark_admin/admin/dashboard/index/key/913cd5d80331d5fb5fe1ce1a183846c0c9b49a63e8a97f90f63093cf0b5b0c7b/

2. login to Magento server
3. Access dashboard

### Expected result (*)

1. Should be logged into the Dashboard and be able to access the server

### Actual result (*)

1. [Screenshots, logs or description] Get the following error
2. 
![image](https://user-images.githubusercontent.com/62347170/103242170-4ed1fe00-4923-11eb-826b-c3efd7d1e1f7.png)

**Comment by engcom-Bravo** [comment]
Hello @michealcarroll 

Thank you for your report.

Please, observe the .log files in your _.../var/log_ directory
