### ISSUE TITLE
Admin always return default store code, not admin

### ISSUE THREAD

**Issue by hiephm** [magento/magento2#3147]
In admin controller, the following code will not work as expected (always return false):

``` php
/** @var \Magento\Store\Model\StoreManagerInterface $storeManager */
$storeManager->getStore()->getCode() == \Magento\Store\Model\Store::ADMIN_CODE;
```

because the 'admin' store code is not set anywhere in Action class.
Magento 1 does this properly by hooking to 'adminhtml_controller_action_predispatch_start' event and set it:

``` php
// in Mage_Adminhtml_Model_Observer
    public function bindStore()
    {
        Mage::app()->setCurrentStore('admin');
        return $this;
    }
```

**Following code doesn't work, see update below:**
~~Magento 2 does not have such event, but we can use 'controller_action_predispatch' in adminhtml/events.xml in any module, then set 'admin' store code:~~

``` php
/** @var \Magento\Store\Model\StoreManagerInterface $storeManager */
$this->storeManager->setCurrentStore('admin');
```

~~I can create a pull request if necessary.~~

**UPDATE 1**: above fix will cause unset of website when saving products, there maybe easier ways to check if current store is admin, now I am using `\Magento\Backend\Model\Auth::isLoggedIn()`

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2254
https://github.com/magento/magento2/issues/2064
https://mage2.pro/t/128

**Comment by hiephm** [comment]
Thanks for more info, @dfediuk 
I believe this is a bug and should be fixed.
@antonkril : the `\Magento\Store\Api\StoreResolverInterface::getCurrentStoreId` also incorrectly return 'default' instead of 'admin', since 'admin' never got set.

**Comment by hshar7** [comment]
Hi @hiephm the best way to check whether the request is coming from admin panel is to use \Magento\Framework\App\State::getAreaCode == \Magento\Framework\App\Area::AREA_ADMINHTML

**Comment by GuiltyNL** [comment]
I think specifying the run code in the webservers config, could solve this issue too. Please see: https://github.com/magento/magento2/issues/12354#issuecomment-588998818
