### ISSUE TITLE
Currency graphql query should return symbols for all available currency in a store

### ISSUE THREAD

**Issue by dani97** [magento/magento2#31494]
Currency graphql query should return symbols for all available currency in a store. It only provides default currency symbol and base currency symbol

### Preconditions (*)

1. Create multiple currencies for a single store
2. Go to Magento admin > Stores > Currency > Currency Symbols
3.  Change currency symbol as you want  then Click to Save currency symbols + Clear cache

### Steps to reproduce (*)

1. call currency query with all the fields

### Expected result (*)

1. Only base currency symbol and default currency symbol is available from currency query
2. Available currency codes (can be renamed to available currency) should return symbols also.

### Actual result (*)

1. All currency symbols for the store should be provided

### Additional info from Engcom

1. A new store currency can be added in _Stores - Configuration - General - Currency Setup - Currency Options - Allowed Curencies_
2. Symbols can be changed in _Stores - Currency - Currency Symbols_
![currency2](https://user-images.githubusercontent.com/51680745/103404601-da829f00-4b5c-11eb-9630-0b2ca6394818.png)
3. GraphQL currency query
```graphql
query {
    currency {
        base_currency_code
        base_currency_symbol
        default_display_currency_code
        default_display_currency_symbol
        available_currency_codes
        exchange_rates {
            currency_to
            rate
        }
    }
}
```
Response
```graphql
{
  "data": {
    "currency": {
      "base_currency_code": "USD",
      "base_currency_symbol": "+",
      "default_display_currency_code": "USD",
      "default_display_currency_symbol": "+",
      "available_currency_codes": [
        "EUR",
        "USD",
        "UAH"
      ],
      "exchange_rates": [
        {
          "currency_to": "EUR",
          "rate": 0.7067
        },
        {
          "currency_to": "USD",
          "rate": 1
        },
        {
          "currency_to": "UAH",
          "rate": 0
        }
      ]
    }
  }
}
```

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @dani97

Thank you for your report.

We are moving this issue to the _Feature Request_ board.
Additional info is added to the description

Thank you

**Comment by dverkade** [comment]
Ready for confirmation issues can't be closed automatically.
