### ISSUE TITLE
Invalid Method Magento\Newsletter\Model\Subscriber\Interceptor:: loadByCustomer

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31493]
### Preconditions (*)

1. EE 2.4.1

### Steps to reproduce (*)

I registered a new customer, it worked fine. Then I deleted that customer and tried to register him again, and now it suddenly failed with an error saying **Invalid Method Magento\Newsletter\Model\Subscriber\Interceptor:: loadByCustomer**
The error also shows when I try to edit a customer in the magento backend now.

Even when I comment out the code `// $subscriber->loadByCustomerId((int)$customer->getId());`
then I still get another error "**Invalid method Magento\Newsletter\Model\Subscriber\Interceptor::loadBySubscriberEmail**".
There are so many errors, I wonder how that broken code made its way into production?

I inspected the code and it became obvious that magento made a fault in the code:

## vendor\magento\module-newsletter\Model\Plugin\CustomerPlugin.php:

```
    private function getSubscriber(CustomerInterface $customer): Subscriber
    {
        $customerId = (int)$customer->getId();
        if (isset($this->customerSubscriber[$customerId])) {
            return $this->customerSubscriber[$customerId];
        }

        /** @var Subscriber $subscriber */
        $subscriber = $this->subscriberFactory->create();
        $websiteId = $this->getCurrentWebsiteId($customer);
        $subscriber->loadByCustomer((int)$customer->getId(), $websiteId);    <--- Magento tries to access a method which does not exist, probably the wanted to call `loadByCustomerId` instead of `loadByCustomer`
```

The same non existing method is also getting called in the method `retrieveSubscriberData` in the file **vendor\magento\module-customer\Block\Adminhtml\Edit\Tab\Newsletter.php**

```

    /**
     * Retrieve subscriber data
     *
     * @param CustomerInterface $customer
     * @param int $websiteId
     * @return array
     */
    private function retrieveSubscriberData(CustomerInterface $customer, int $websiteId): array
    {
        $subscriber = $this->_subscriberFactory->create()->loadByCustomer((int)$customer->getId(), $websiteId);
```

### Expected result (*)

Should work

### Actual result (*)

Not working because the method does not exist

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
This method that you mentioned declare in this file below
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Newsletter/Model/Subscriber.php#L406
Magento marked annotation deprecated in method `loadByCustomerId`. Maybe previous commit modify/refactor miss use case when customer not available or deleted in database

**Comment by Eddcapone** [comment]
I executed `composer update` again and checked the file, but the method `loadByCustomer` is still not there. I am on the branch `"magento/product-enterprise-edition": "2.4.1",`

**Comment by mrtuvn** [comment]
Just curious if you deleted customer i wonder how that customer still visible in admin for such case error happen?

**Comment by Eddcapone** [comment]
The customer is not still visible in backend. The error shows on any customer.

**Comment by mrtuvn** [comment]
Ohh ! That is good use case for investigate problem! I'm not sure about that method available in EE version
Maybe miss some case  and need refactor code for fix that problem

**Comment by mrtuvn** [comment]
Can you provide steps by steps for reproduce issue ?

**Comment by Eddcapone** [comment]
I figured out that my code was different from the original code, because `composer update` did not updated the core properly and so I still had old code from an older magento version partially. Not sure why composer does not work correctly.

**Comment by mrtuvn** [comment]
Nice feedback! @ihor-sviziev @sidolov can you guys note this case

**Comment by ihor-sviziev** [comment]
TBH never heard about similar issues. I think that might be some local
issue with the composer

**Comment by mrtuvn** [comment]
Aha maybe false alarm here! We are good when it's cause not related code
