### ISSUE TITLE
/V1/invoices/{id}/capture does not save payment.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#31497]
### Preconditions (*)

1. 2.3.3, 2.3.5-p2, 2.4.0
2. A capturable payment method. (or change `$_canCapture = false;` to `$_canCapture = true;` in \Magento\Payment\Model\Method\AbstractMethod)

### Steps to reproduce (*)

1. Create an order with the capturable payment method.
2. Create an invoice through the admin panel for the order but don't capture it.
3. Capture the invoice using the /V1/invoices/{id}/capture REST endpoint.

### Expected result (*)

1. Invoice status goes to Paid.
2. Invoice is no longer capturable through the adminpanel

### Actual result (*)

1.Invoice status stays on Pending
2. Invoice is still capturable through the adminpanel.

The Api is used by this class and this works properly because it is saved after.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Capture.php
But if you call the Api directly all the code is executed correctly, but nothing is saved causing nothing to happen.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @Hexmage 

Thank you for your report.

We have rechecked the reported issue on the latest 2.4-develop, and it is not reproducible.
The Order Status is changed to **Paid** after _POST /V1/invoices/{id}/capture_ request is performed

Manual testing scenario:
1. Place an order using a capturable payment method
2. Submit invoice for the order, selecting **Not Capture** under _Amount_
![capture](https://user-images.githubusercontent.com/51680745/103529920-30be4d80-4e8f-11eb-9d9a-47f460f15d78.png)
4. Assert that the Status is - _Pending_
![pending](https://user-images.githubusercontent.com/51680745/103530162-9f031000-4e8f-11eb-823f-d5f08f9a5570.png)
3. Perform Swagger _POST /V1/invoices/{id}/capture_ API request specifying the Invoice id
![api_request](https://user-images.githubusercontent.com/51680745/103530128-8eeb3080-4e8f-11eb-99fb-c1d058cc916b.png)
4. Check the Invoice Status

Actual Result:

The Invoice Status is **Paid**
![paid](https://user-images.githubusercontent.com/51680745/103530281-cbb72780-4e8f-11eb-9b17-a33df932d70d.png)

So we are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
