### ISSUE TITLE
Magento2.4 GraphQL CustomerOrders Query Logic

### ISSUE THREAD

**Issue by LouisFangAligentConsulting** [magento/magento2#31537]
### Preconditions (*)

1.Magento2.4.0
2.GraphQL

### Steps to reproduce (*)

1.Create a new Module HelloWorld.
2.Create a schema.graphqls in HelloWorld/Sales/etc/ folder to extend the CustomerOrderFilterInput.
Put following codes in this file:
```
input CustomerOrdersFilterInput @doc(description: "Identifies the filter to use for filtering orders.") {
    created_at: FilterRangeTypeInput @doc(description: "Filters by created at.")
}

input FilterRangeTypeInput @doc(description: "Defines a filter that matches a range of values, such as prices or dates.") {
    from: String @doc(description: "The beginning of the range")
    to: String @doc(description: "The end of the range")
}
```
3.Use the following payload and `{{your URL}}/graphql` to query the customer token.
```
mutation {
  generateCustomerToken(email: "{{your email address}}", password: "{{your password}}") {
    token
  }
}
```
4.Put above token in Postman Headers `Authorization` with `Bearer {{your token}}`.
5.Use following payload to query the above customer's sales orders.
```
query {
    customer {
        orders(filter: { 
            created_at: { 
                from: "2021-01-02"
                to: "2021-01-04"
            }}) { 
            items { 
                number  
                created_at 
            }
        }
    }
}
```
6.The above query will get the result of all orders from 2021-01-02 or to 2021-01-04, not between 2021-01-02 and 2021-01-04.

### Expected result (*)

1.What I expect is that the orders between 2021-01-02 and 2021-01-04.

### Actual result (*)

1.The actual result is that the orders from 2021-01-02 or to 2021-01-04.
2.OrderFilter.php file makes filter conditions in the same filterGroups item and the relationship is `OR`. Maybe it is not a bug, but generally every condition should be in a separate filterGroups which relationship is `AND`. More ideally, in graphQL payload, some style like `and: "true"` can be provided to make a different logic combination.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [*] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Santoshziffity** [comment]
@magento I am working on this

**Comment by Santoshziffity** [comment]
@magento add to contributors team

**Comment by engcom-Hotel** [comment]
Hello @LouisFangAligentConsulting,

We have tried to reproduce this issue in Magento 2.4-develop branch and it is reproducible for us while extending. To reproduce this issue we have followed the steps mentioned in the main description as well as enabling DB logs via the command `bin/magento dev:query-log:enable`.

I am attaching the db.log related to that query with the stack trace. It will help the developer in fixing the issue.
[db.log](https://github.com/magento/magento2/files/7570710/db.log)

Thanks

**Comment by serbynskyi** [comment]
@magento I am working on this

**Comment by serbynskyi** [comment]
@magento add to contributors team

**Comment by serbynskyi** [comment]
@magento I am working on this

**Comment by Kiraberos** [comment]
@magento add to contributors team

**Comment by GrzegorzWalewski** [comment]
@magento add to contributors team

**Comment by GrzegorzWalewski** [comment]
@magento I am working on this

**Comment by GrzegorzWalewski** [comment]
I don't have time right now to fix it on Magento's repo, but here is a patch I came with which fix this issue:
```
--- /dev/null
+++ ../Data/Collection/AbstractDb.php
@@ -393,7 +393,7 @@
                 $conditions[] = $this->_translateCondition($value, isset($condition[$key]) ? $condition[$key] : null);
             }
 
-            $resultCondition = '(' . implode(') ' . \Magento\Framework\DB\Select::SQL_OR . ' (', $conditions) . ')';
+            $resultCondition = '(' . implode(') ' . \Magento\Framework\DB\Select::SQL_AND . ' (', $conditions) . ')';
         } else {
             $resultCondition = $this->_translateCondition($field, $condition);
         }
```
The only thing that has to be changed is `SQL_OR` to `SQL_AND` – if we use more filters, we want the data we receive 
(e.g., products, orders) to meet all our requirements, not just one of them. E.g., we want orders from within dates – not before max date and after min date.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-1805 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1805&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
