### ISSUE TITLE
install 2.3 requires access to /tmp ???

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#31536]
why not use the php value session.save_path ?

`
[Mon Jan 04 23:04:42.178595 2021] [proxy_fcgi:error] [pid 14589:tid 139846802659072] [client 8.8.8.8:56223] AH01071: Got error 'PHP message: PHP Warning:  error_reporting() has been disabled for security reasons in /home/account/shop.domainname.com/app/bootstrap.php on line 10\nPHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/account) in /home/account/shop.domainname.com/vendor/magento/framework/Filesystem/DirectoryList.php on line 101\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/setup/index.php on line 31\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/vendor/laminas/laminas-stdlib/src/ErrorHandler.php on line 54\nPHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/account) in /home/account/shop.domainname.com/vendor/magento/framework/Filesystem/DirectoryList.php on line 101\nPHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/account) in /home/account/shop.domainname.com/vendor/magento/framework/Filesystem/DirectoryList.php on line 101\nPHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/account) in /home/account/shop.domainname.com/vendor/magento/framework/Filesystem/DirectoryList.php on line 101\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/vendor/laminas/laminas-stdlib/src/ErrorHandler.php on line 54\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/vendor/laminas/laminas-stdlib/src/ErrorHandler.php on line 54\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/setup/src/Magento/Setup/Model/InstallerFactory.php on line 45\nPHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /home/account/shop.domainname.com/vendor/laminas/laminas-stdlib/src/ErrorHandler.php on line 54\n', referer: http://shop.domainname.com/setup/`

**Comment by ihor-sviziev** [comment]
Hi @f1-outsourcing,
It feels like more a question than an issue, such questions should be asked at https://magento.stackexchange.com/ and not there. That's why I'm closing this issue. 


But! As I already took it - I just analyzed the lines that you referred to in logs:
https://github.com/magento/magento2/blob/aeedfcd6591df8cc629878278e69cae73b7f1b29/lib/internal/Magento/Framework/Filesystem/DirectoryList.php#L100-L101

As you can see - here is Magento tries to retrieve the default temp folder from PHP for file uploads - it tries to get it from the `upload_tmp_dir` PHP setting with a fallback to `sys_get_temp_dir()`.
Seems like your `upload_tmp_dir` PHP setting isn't set and that's why Magento used the default temp directory which is `/tmp` on your server.

In order to fix the issue - you can just update your PHP settings with the correct path on your server from the whitelisted paths. 

Hope I helped to solve your issue.

**Comment by f1-outsourcing** [comment]
My upload_tmp_dir is set to the same value as session.save_path and both are visible and set when I execute a phpinfo() from within the magento root. 
I just removed the /tmp from the open_basedir and get from a running magento 2.3.6 again the errors

`com/app/bootstrap.php on line 10\nPHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): `

So there is still something wrong with detecting this somewhere.

**Comment by ihor-sviziev** [comment]
@f1-outsourcing I dn't see any realpath on the magento 2.3.5 in the app/bootstrap.php
https://github.com/magento/magento2/blob/2.3.6/app/bootstrap.php#L10

Seems like you have some modified version. Could you provide it?

**Comment by f1-outsourcing** [comment]
I have almost a fresh install, I downloaded this.
magento-ce-2.3.6-2020-09-25-06-31-35.tar.gz

And currently applied these changes (making some manual for myself)

```
umask 0027
mkdir -p app/code/AvS/DisableModules/
tar -zxvf ../AvS_DisableModules-1.0.0.tar.gz -C app/code/AvS/DisableModules/ --strip 1
bin/magento module:enable AvS_DisableModules
bin/magento setup:upgrade

bin/magento info:dependencies:show-removable 2>&1 | grep -v error_reporting | grep -v set_error_handler

bin/magento module:disable Amazon_Payment
bin/magento module:disable Amazon_Login
bin/magento module:disable Amazon_Core

bin/magento module:disable Magento_AuthorizenetGraphQl
bin/magento module:disable Magento_AuthorizenetCardinal
bin/magento module:disable Magento_Authorizenet
bin/magento module:disable Magento_AuthorizenetAcceptjs

bin/magento module:disable Magento_CardinalCommerce

bin/magento module:disable Dotdigitalgroup_Chat
bin/magento module:disable Dotdigitalgroup_Email
bin/magento module:disable Temando_ShippingRemover

bin/magento module:disable Magento_CatalogAnalytics
bin/magento module:disable Magento_CustomerAnalytics
bin/magento module:disable Magento_SalesAnalytics
bin/magento module:disable Magento_QuoteAnalytics
bin/magento module:disable Magento_Analytics

bin/magento module:disable Magento_Dhl
bin/magento module:disable Magento_Fedex
bin/magento module:disable Magento_Ups
bin/magento module:disable Magento_Usps

bin/magento module:disable Magento_BraintreeGraphQl
bin/magento module:disable Magento_Braintree

bin/magento module:disable Magento_Signifyd
bin/magento module:disable Magento_SampleData

bin/magento module:disable Klarna_Kp
bin/magento module:disable Klarna_Ordermanagement
bin/magento module:disable Klarna_Core

bin/magento module:disable Vertex_AddressValidation
bin/magento module:disable Vertex_Tax

bin/magento module:disable Magento_GoogleShoppingAds
bin/magento module:disable Magento_GoogleAdwords
bin/magento module:disable Magento_GoogleOptimizer
bin/magento module:disable Magento_GoogleAnalytics

bin/magento module:disable Magento_WishlistAnalytics

bin/magento module:disable Magento_SwatchesLayeredNavigation
bin/magento module:disable Magento_SwatchesGraphQl
bin/magento module:disable Magento_Swatches

bin/magento module:disable Yotpo_Yotpo

bin/magento module:disable Magento_ReviewAnalytics

bin/magento module:disable Magento_WeeeGraphQl
bin/magento module:disable Magento_Weee

bin/magento module:disable Magento_Marketplace
bin/magento module:disable Magento_Sitemap
```

The idea is to see if I can get some date migrated from an old 1.9 store.

**Comment by ihor-sviziev** [comment]
Hi @f1-outsourcing,
So you have disabled `error_reporting` and `set_error_handler` functions using https://www.php.net/manual/en/ini.core.php#ini.disable-functions 
Unfortunately, Magento might work incorrectly when these functions are disabled. I strongly recommend you to allow using these functions for correct work of Magento.

**Comment by f1-outsourcing** [comment]
As in if we do not see/log the error, it is resolved? :) Lets focus on that /tmp is being accessed and  upload_tmp_dir / session.save_path is not properly read. Maybe time to reopen this.

**Comment by ihor-sviziev** [comment]
@f1-outsourcing could you provide more info, like error/warning log that you're having?

**Comment by f1-outsourcing** [comment]
Ok ok I know what the problem is. I have this issue already when I press the luma logo of the default store.
You are using get_cfg_var[1] which tries to get the var from ini file. But this does not seem to work well in (my) setups where php-fpm is being used (returns false). If you would change it to ini_get('upload_tmp_dir'); which gets the runtime value. You get a proper value returned.

So you can either change it to ini_get, or just do the ini_get after the get_cfg_var fails. 

However you have to keep in mind why the choice has been made to get this directly from the file. This could be related to a security approach. I do not know to much about php to judge this. It for sure fails in my setup, and logically I would say that if magento is using ini_set in the code, why also not stick to ini_get.




The error is gone if I change this line in vendor/magento/framework/Filesystem/DirectoryList.php

```
//$sysTmpPath = get_cfg_var('upload_tmp_dir') ?: sys_get_temp_dir();
        $sysTmpPath = ini_get('upload_tmp_dir') ?: sys_get_temp_dir();
```


[1]
https://www.php.net/manual/en/function.get-cfg-var
get_cfg_var returns the value from php.ini directly,while the ini_get returns   the runtime config value.

[2]
PHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/...) in /home/.../vendor/magento/framework/Filesystem/DirectoryList.php on line 101

**Comment by ihor-sviziev** [comment]
Ok... interesting thing. This line was added in https://github.com/magento/magento2/pull/21170 and actually was changed from ini_get to get_cfg_var in https://github.com/magento/magento2/pull/21170/commits/aeedfcd6591df8cc629878278e69cae73b7f1b29 by @nmalevanec just in order to fix static test failure. To be honest it doesn’t seems to me as a valid case for such change if it’s causing such issue.

I just reopened this issue for further research

**Comment by ihor-sviziev** [comment]
@f1-outsourcing, will you be able to update the issue according to the issue-reporting template?

**Comment by f1-outsourcing** [comment]
> 
> 
> @f1-outsourcing, will you be able to update the issue according to the issue-reporting template?

You may write it anyway you like.

**Comment by TheRealHunzik** [comment]
@magento give me 2.3.5-p2 instance

**Comment by TheRealHunzik** [comment]
@magento give me 2.3.5 instance

**Comment by engcom-November** [comment]
Hi @f1-outsourcing ,
Thank you for reporting. Can you please elaborate more details about the issue / provide steps to reproduce this issue
Thank you.
