### ISSUE TITLE
Error when saving product in catalog/products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#31541]
### Preconditions (*)

1. Mysql 8.0.21
2. Php 7.3.19

### Steps to reproduce (*)

1. In backend, catalog/products
2. Click to save

### Expected result (*)

1. Product saved without error
2.

### Actual result (*)

1. SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'store_id' in where clause is ambiguous, query was: SELECT `main_table`.* FROM `url_rewrite` AS `main_table` INNER JOIN `catalog_product_entity` AS `product_entity` ON main_table.entity_id = product_entity.entity_id INNER JOIN `catalog_product_entity_int` AS `product_status_default` ON product_status_default.entity_id = product_entity.entity_id AND product_status_default.attribute_id = 97 AND product_status_default.store_id = 0 LEFT JOIN `catalog_product_entity_int` AS `product_status` ON product_status.entity_id = product_entity.entity_id AND product_status.attribute_id = 97 AND product_status.store_id = main_table.store_id WHERE (`redirect_type` = '0') AND (`entity_type` = 'product') AND (`store_id` IN('1', 0)) AND ((product_status.value_id > 0 AND product_status.value IN (1)) OR (product_status.value_id IS NULL AND product_status_default.value IN (1))) AND (`product_entity`.`entity_id` = '88514')
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [*] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hello @achatpc,

Verified this issue on the latest Magento 2.4 Instance. After the product saved I didn't get any of the errors.
**You can review attached the video of the below link:**
https://drive.google.com/file/d/11iZta4EORJ_-siuVjCnZTimYdwlYo86j/view

Thanks.

**Comment by ajijshekh123** [comment]
@achatpc - Let me update you if the above issue is fixed or not.

**Comment by ajijshekh123** [comment]
@achatpc  - If you have reproduced this issue again on Latest Magento Instance you can reopen it.
Thanks.

**Comment by senders** [comment]
@achatpc
Have they figured out the problem?
I have exactly the same problem.

**Comment by JKetelaar** [comment]
Same problem here...

**Comment by achatpc** [comment]
Hello all.

In my side issue was related with mirasvit seo extension. 

I can solve it with changement in:

/var/www/html/vendor/magento/module-url-rewrite/Model/ResourceModel/UrlRewriteCollection.php :
$this->addFieldToFilter ('main_table.store_id', ['in' => $store]);

If you need i can send détails of file change.

**Comment by JKetelaar** [comment]
I dug into the problem and in my case, it's related to `amasty/module-fpc-warmer`.
If you disable the option "Auto-update Cache upon the Product Changes" everything seems to work again.

Please submit this issue to Amasty yourself as well, so they can dig into it instead of always asking for SSH access... They say they haven't had this issue yet...

**Comment by achatpc** [comment]
I use also amasty/module-fpc-warmer
Thank you for information. I can check it on my side.
Buy my issue wass solved with change in this file:

/var/www/html/vendor/magento/module-url-rewrite/Model/ResourceModel/UrlRewriteCollection.php :
$this->addFieldToFilter ('main_table.store_id', ['in' => $store]);

**Comment by JKetelaar** [comment]
That fix indeed seems to fix this issue where modules use the `addStoreFilter` function. Bad code from Magento's side... Good call @achatpc!

**Comment by achatpc** [comment]
I confirm that issue is linked with amasty/module-fpc-warmer.
If you disable the option "Auto-update Cache upon the Product Changes" everything seems to work again without any change in UrlRewriteCollection.php

**Comment by JKetelaar** [comment]
Thanks @achatpc - I have mentioned it to them as well

**Comment by gabrieldagama** [comment]
@achatpc @JKetelaar created a new issue here https://github.com/magento/magento2/issues/31853
