### ISSUE TITLE
Shipping Label is created although shipment creation fails due to items being out of stock

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#31555]
### Preconditions (*)

Magento 2.4.1
Netresearch DHL Shipping Module (dhl/shipping-m2) v1.3.0 (but it will happen with any other carrier that is able to print shipping labels)

### Steps to reproduce (*)
- Create an order with an in stock product and shipping method of carrier that is able to print shipping labels
- Set quantity of product to 0 (this can happen in different scenarios, even if reservations feature is used)
- Reindex and clear cache
- Go to order and click "Ship"
- Check checkbox "Create Shipping Label"
- Click "Submit Shipment"

### Expected result (*)
1. Message is shown: "Not all of your products are available in the requested quantity."
2. Shipping Label is not created, since shipment creation failed

### Actual result (*)
1. Message is shown: "Not all of your products are available in the requested quantity." 
![image](https://user-images.githubusercontent.com/18382633/103665905-42c5ec00-4f74-11eb-96dc-3d5a9989b7eb.png)

2. Shipping Label is created in background without any immediate notice and without any comment on the order that a label was created although shipment failed.

### Reason

The creation of the label takes place in `Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::execute` on line 153.
The check for out of stock items takes place in `Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::execute` on line 157 (i.e. somewhere in `_saveShipment`), so after the labels was already created successfully. 
By saying that, all errors that might occur in `Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::_saveShipment` result in a failed shipment but in a successfully created shipping label in the background.

### Proposed solutions

1. Defer creation of shipping label to after shipment was created successfully or
2. Cancel shipping label if shipment failed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @HenKun . Thank you for your report!

Unfortunately, we are not able to reproduce the issue on а clean 2.4-develop. Everything works as expected.

**_Precondition:_**
Configure DHL shipping method;

**Manual testing scenario:**

1. Create an order with an in stock product and shipping method of carrier that is able to print shipping labels
![Screenshot from 2021-02-17 13-00-43](https://user-images.githubusercontent.com/51679138/108195226-2b0b8700-7120-11eb-87fd-ab8397d8557d.png)
2. Set the quantity of product to 0;
3. Go to order and click "Ship"
4. Check the checkbox "Create Shipping Label"

**Actual Result:** Shipping Label was successfully created

![Screenshot from 2021-02-17 13-14-14](https://user-images.githubusercontent.com/51679138/108196802-352e8500-7122-11eb-9b49-9a9b69a1447e.png)

@HenKun Maybe we missed something?
Could you take a look?
Thanks!

**Comment by HenKun** [comment]
@engcom-Alfa 

The steps seem correct, however I am wondering why your shipment could be created successfully if the product is not in stock (after setting stock to 0 manually).

Normal behavior:
- Let's assume the qty of the product was 1 before ordering
- After ordering the qty is still 1 and a reservation of -1 is added
- On creating shipment the reservation is balanced by adding a reservation of +1 and the qty is reduced from 1 to 0

The case on hand:
- Let's assume the qty of the product was 1 before ordering
- After ordering the qty is still 1 and reservation of -1 is added
- **Qty of product is manually changed to 0 now**
- Creation of shipment must fail, because the qty is already 0 and cannot be deducted (this seems to be different in your test)

So maybe these config settings were not correct:
- `cataloginventory/options/can_subtract` needs to be `true`
- `cataloginventory/item_options/manage_stock` nees to be `true`
- `cataloginventory/item_options/backorders` needs to be `false`
- Those setting should not be overriden differently on product level

So the issue on hand will occur, if the shipment fails, i.e. shipment cannot be created if the qty of the product is already 0.

You can even simulate the problem by throwing an arbitrary exception in `Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::_saveShipment`. And indeed, the shipment can fail on whatever failure happens in `_saveShipment`.

**Comment by HenKun** [comment]
Any more updates needed for this issue?

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
1. Create an order with an in stock product and shipping method of carrier that is able to print shipping labels (Ex: DHL)
2. Set quantity of product to 0 from Admin - Catalog - Edit Product - Update Quantity to 0 and save
3. Reindex and clear cache
4. Go to Admin - Sales - Orders - View order and click "Ship"
5. Check checkbox "Create Shipping Label"
6. Click "Submit Shipment" - Add Products to Package - Select Product - Add selected
7. Click on Save button - No issue:  "Not all of your products are available in the requested quantity." error message is displayed to the user
8. Verify shipping.log file
**Issue:** Shipping Label number is getting created even though Shipment creation failed.
![image](https://user-images.githubusercontent.com/60198231/130437509-6d2f0380-9152-49d7-a039-2a478b929137.png)

![image](https://user-images.githubusercontent.com/60198231/130437406-1af229fb-af1e-4cf7-a8be-03cdcc3ccb2a.png)

**Comment by engcom-November** [comment]
Verified the scenario again by putting back the same Product quantity to Stock and created Shipment again for the same order with Shipping Label - Shipment is created with new Shipping Label and DB tables are updated as expected - **No issue.**
Issue observed only when product Quantity is 0 while creating Shipment with Shipping Label - Shipment is failing but Shipping Label is getting created.
**Steps to reproduce:**
1. Create an order with an in stock product and shipping method of carrier that is able to print shipping labels (Ex: use DHL Shipping Method while placing order)
2. Set quantity of same product to 0 from Admin - Catalog - Edit Product - Update Quantity to 0 and save
3. Reindex and clear cache
4. Go to Admin - Sales - Orders - View order and click "Ship"
5. Check checkbox "Create Shipping Label"
6. Click "Submit Shipment" - Add Products to Package - Select Product - Add select
7. Click on Save button - No issue: "Not all of your products are available in the requested quantity." error message is displayed to the user
8. Verify shipping.log file
**Issue: Shipping Label number is getting created even though Shipment creation failed.**
9. Put back the Product Quantity to >1 or in stock and save
10. Reindex and clear cache
11. Admin - Sales - Open same Order - Ship - Check with Shipping Label - Submit shipment - Shipment is created with new Shipping Label.

**Comment by HenKun** [comment]
Amy progress on that?

**Comment by HenKun** [comment]
Any news on that?

**Comment by engcom-Delta** [comment]
Hi @HenKun ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
