### ISSUE TITLE
ecommerce history won't come up 

### ISSUE THREAD

**Issue by yougottabekiddingme** [magento/magento2#31559]
I can't pull up orders from December to print label for customer's part that came in and needs shipped.
Is the a help phone number for the new ecommerce setup as it's currently not very user friendly
 

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by MartinAarts** [comment]
I think you need to be a lot more specific about what is going wrong. Can you tell a lot more about what you've tried and what isn't working?

No, there isn't a support phone number, you're using free software. If you want proper support, you should apply for Magento Commerce. Then you might get some support.

**Comment by engcom-Delta** [comment]
Hi @yougottabekiddingme thank you for your report. Please update ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.

**Comment by yougottabekiddingme** [comment]
I thought I was clear with explaining history on 
Ecommerce Orders prior to January not being available to view,
but I guess not. Anyhow, I have the pros at fordparts.com working on it and 
apparently it’s a nation wide issue since transition to Magento.
By the way, We’re on Magento Commerce, not the free software
 

 

Sent from Mail for Windows 10
