### ISSUE TITLE
Tax calcuation for UK VAT is wrong

### ISSUE THREAD

**Issue by TectonicKestrel** [magento/magento2#31566]
### Preconditions (*)
1. Magento CE 2.3.6 (had same issue on 2.3.3)
2. PHP 7.3
3. Server version: 5.7.31-cll-lve - MySQL Community Server
4. https://github.com/StockChannel/SinchImport - This module imports stock and pricing
5. Official Stripe Payment module
6. Catalog prices are Ex VAT
7. Frontend prices show as exc and inc VAT
8. Tax is calucated on Unit, but have the same result on Row and Total

### Steps to reproduce (*)
1. Add a product, for example that is £10 inc VAT, is saved in the database as £8.3333
2. Add a second (or more) of the same product to the basket

### Expected result (*)
1. 2 x £10 products added to equal £20 inc VAT and a delivery price of £5 inc VAT for a total of £25

### Actual result (*)
1. In my example above, if 2 x £10 (inc VAT) products are added the product price says £10, but the row total is £19.99 inc VAT and the exc VAT subtotal is £16.66, not £16.67. Delivery price is £5 inc VAT so the total for this example should be £25, not £24.99.
 ![tax incorrect](https://user-images.githubusercontent.com/10212208/103755011-0d1d1380-5005-11eb-923d-1eec06fa7125.JPG)
2. This can also add 1p to an order total, depending on how a product price is rounded.

I have tried using https://github.com/meanbee/magento2-tax-rounding and while that does work from a displaying price perspective, Stripe still charges the customer the original price (in this example £19.99). I dont really think i should have to use a plugin to achieve basic ecommerce functionality. This seems to have been a problem for years and never been sorted.

---
- [*] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by alexsmith2709** [comment]
@magento give me 2.4-develop instance

**Comment by alexsmith2709** [comment]
On magento 2.4 this is still wrong. It is wrong in a differetn way, but the result is similar and the order total inc VAT is still wrong.
![tax incorrect2](https://user-images.githubusercontent.com/10212208/104132111-2dd1ca00-5373-11eb-9e3f-efbda99589d6.JPG)
This screenshot is from the 2.4 instance generated for me. I am not sure why the Flat Rate is showing as £8.34 when i set it to £4.17 ex VAT, the same as my live shop.
As you can see, 2 x £10 + £5 delivery should equal £30.00 total inc VAT, not £30.01.

**Comment by alexsmith2709** [comment]
Using a plugin to fix the frontend, but issue still present in the admin panel when creating an order manually.
