### ISSUE TITLE
Checkout page when Promotion code applied Shipping charge not reflected

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#31562]
### Preconditions (*)
1. Magento 2.3.3
2. MySQl 7.2

### Steps to reproduce (*)
1. Create Cart Rule if cart total is equal or greater than 75 Free Shipping
![image](https://user-images.githubusercontent.com/50168477/103729184-d693c880-5005-11eb-9a58-5aa9d723b55d.png)

2.  Create Cart Rule with Discount code , e.g Discount Code (20OFF) 
![image](https://user-images.githubusercontent.com/50168477/103729234-f9be7800-5005-11eb-9f1f-c4b617c15241.png)

3. add Product with price Cart total 75
4. go to Checkout page in Payment Information with Total 75 shipping charge is 0
![image](https://user-images.githubusercontent.com/50168477/103729292-207cae80-5006-11eb-9120-b07050df8e10.png)

5.  in Discount tab add Discount Code "20OFF" then  shipping charge also 0
![image](https://user-images.githubusercontent.com/50168477/103729494-8ff29e00-5006-11eb-817b-350caacc09d8.png)

### Expected result (*)
1. 
![image](https://user-images.githubusercontent.com/50168477/103729596-ce885880-5006-11eb-8ffe-9a799a8c7e23.png)

### Actual result (*)
1. 
![image](https://user-images.githubusercontent.com/50168477/103729494-8ff29e00-5006-11eb-817b-350caacc09d8.png)

please check this is the issue , need to fix this.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @niku0911,
I have verified this issue as per your steps, the actual result, and the expected result.
I have created the 2 rules as per your configuration and setup.
The shipping charge is properly showing.
![image](https://user-images.githubusercontent.com/24711761/104324303-44138d80-550d-11eb-85cf-f603b90caf7b.png)

![image](https://user-images.githubusercontent.com/24711761/104324392-62798900-550d-11eb-97ca-3f3a0d061a5e.png)

![image](https://user-images.githubusercontent.com/24711761/104324410-67d6d380-550d-11eb-83ec-8b5b57982016.png)

Is there any pending from my end so please let me know?

Thanks.

**Comment by niku0911** [comment]
hi @ajijshekh123 

thanks for help i think don't know in my site some bug, i need to checkout on my side.

**Comment by ajijshekh123** [comment]
Okay @niku0911
