### ISSUE TITLE
Canceling moving a category has unexpected behavior for the category tree

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#31567]
### Preconditions (*)
1. Magento 2.4-develop,
 Magento CE 2.3 (did't check on other versions yet)
2. Be logged in in the backend and view the category management page.
3. Admin category tree as follows. 

```
Default Category
 |-- Level 1.1
 |----|-- Level 2.1
 |----|-- Level 2.2
 |----|-- Level 2.3
 |-- Level 1.2

``` 

### Steps to reproduce (*)
1. Move category Level 2.1 up one level as a sibling of Level 1.1 and level 1.2 and press OK in the confirmation popup. Do not refresh the page after doing this.
2. Move category Level 2.2 up one level as a sibling of Level 1.1 and level 1.2 and press CANCEL in the confirmation popup

### Expected result (*)
1. The category tree I see in the admin should looks like this with the category Level 2.1 moved and Level 2.2 on its original place

```
Default Category
 |-- Level 1.1
 |----|-- Level 2.2
 |----|-- Level 2.3
 |-- Level 1.2
 |-- Level 2.1
```
### Actual result (*)
1. The category tree is reset to the state it was before the first move that was OK'd
```
Default Category
 |-- Level 1.1
 |----|-- Level 2.1
 |----|-- Level 2.2
 |----|-- Level 2.3
 |-- Level 1.2

``` 

### Additional info:
This only happens in the UI. Refreshing the admin page with the category tree shows the expected result. 
But this may cause confusion (and panic) if someone moves a few categories around and when canceling one move sees all the tree reset.

### Side note 
(can be reported separately if needed)
When moving a category and the confirmation popup is shown, pressing ESC makes the popup disappear but it does not put back the category to the initial value. It should have the same behavior as the Cancel click. Basically nothing happens to the category tree when pressing ESC.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40314` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
