### ISSUE TITLE
Magento 2 Downloadable products

### ISSUE THREAD

**Issue by Rajesh-Rathod** [magento/magento2#3156]
Downloadable product link is not working even after created invoice.

**Comment by kandy** [comment]
@Rajesh-Rathod, Thanks for reporting.
Can I ask you describe in more details  steps to reproduce and expected behavior.
I try reproduce it on Magento 2.0.2 and after create invoice links are available in "My Downloadable Products" panel of Customer Account.

**Comment by katmoon** [comment]
@Rajesh-Rathod  I'm closing the ticket since there is no response for more than 2 weeks.
Please feel free to reopen if you have any questions.
