### ISSUE TITLE
Can't scroll inside the Store View selector

### ISSUE THREAD

**Issue by pivulic** [magento/magento2#3158]
## Problem

If there are multiple stores, it's not possible to scroll to the bottom and select the desired store view. 
See http://www.vaimo.com/snaps/pablo.ivulic/m2-cant-select-bottom-store.png
## Expected result

It should be possible to scroll inside this Store View selector so that I can choose any of my stores.
## How to recreate

1) Setup a lot of stores, similar to: http://www.vaimo.com/snaps/pablo.ivulic/m2-a-lot-of-stores.png
2) Navigate to a page in admin where there is a Store View selector, i.e. **Products » Categories** or **Stores » Configuration**.
3) Try and select the lowest store, i.e. UK or US in this case.

**Comment by MomotenkoNatalia** [comment]
https://github.com/magento/magento2/issues/2896

**Comment by MomotenkoNatalia** [comment]
@pivulic Internal ticket MAGETWO-48386 is closed and delivered to mainline. Please let us know if you still have an issue.
