### ISSUE TITLE
ImportOrderPayment throws the exception Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by AlexandrosMor** [magento/magento2#31599]
In Magento\Paypal\Model\Billing\Agreement the [importOrderPayment](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/Model/Billing/Agreement.php#L249) method is setting customertId, method code, referenceId, status and agreement label to the $billingAgreement. The referenceId is set from the `$baData['billing_agreement_id']`where $ba is the billing agreement data. 
The issue is that when we set the reference Id if the `$baData['billing_agreement_id']` is not set then throws the exception 
`Message: Trying to access array offset on value of type null`. This happens because $baData is not null but the index 'billing_agreement_id' does not exist. Previous versions of PHP may have been less strict on such mistakes and not throw the error / notice while 7.4 does not do this anymore. This is happening in magento 2.4 as it uses 7.4 php and it is not happening in the previous magento versions 2.3 and 2.2 

### Preconditions (*)

1. Magento 2.4
2. 7.4 php

### Steps to reproduce (*)

1. Use the Magento\Paypal\Model\Billing\Agreement the importOrderPayment in magento 2.4
2.Make a payment and create billing agreement

### Expected result (*)

1. Create billing agreement with out an error
2.

### Actual result (*)

1. Throws the exception `Trying to access array offset on value of type null`
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ *] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by real34** [comment]
This issue still seems to be here. If one wants to find a solution for it, see https://github.com/Adyen/adyen-magento2/pull/941
