### ISSUE TITLE
Referencing Issue #2986

### ISSUE THREAD

**Issue by Karl456** [magento/magento2#3159]
Issue #2986 was recently closed because of the following reason

```
Magento support only options defined in product_options.xml and there no area type so I am closing this issue, as fixed. 
```

However, this link shows that `area` is a type listed in `product_options.xml`: https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/etc/product_options.xml#L11

This is still an issue which needs addressing.

**Comment by ktomk** [comment]
@Karl456: Then please post the objection in that issue (and yes you did). No need to open a new issue only because you already have one and it got closed, did already comment on the close. That's only draining resources. Thanks.

**Comment by Karl456** [comment]
If you read KAndy's comment, it clearly states:

```
Feel free to open new issue if we missed anything.
```

So I'm assuming they don't check replies to closed issues, hence my opening of a new issue.

**Comment by ktomk** [comment]
Ouch, my fault. I should not conclude by my own habits on others. If they ask for it, sure.

**Comment by Karl456** [comment]
Not to worry :)

**Comment by kandy** [comment]
Hi @Karl456, Can you review [integration test](https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Catalog/Block/Adminhtml/Product/Options/AjaxTest.php) and [fixture](https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Catalog/_files/product_with_options.php) that create all type options. 
Looks like problem in method `setProductOptions` in your code (test use setOptions), but it's hard to understand without all data.

**Comment by katmoon** [comment]
I'm closing the ticket since there is no response for 2 weeks.
Please feel free to reopen if you have any questions.
