### ISSUE TITLE
Sorting by position on product search via REST API does not work

### ISSUE THREAD

**Issue by mack4hack** [magento/magento2#31591]
### Preconditions
1. Magento 2.4-develop
2. Magento 2.3.3
3. Vanilla Install

### Steps to reproduce
1. Allow Anonymous Guest Access
From : Stores -> Configuration -> Services -> Magento Web API -> Web API Security

2. Assign position value to products 
from : Catalog -> Categories -> Select Category -> Products in Category

![2021-01-08_10-42](https://user-images.githubusercontent.com/51679138/103993482-5c4a7c00-519e-11eb-8951-ca07a0894ad1.png)

3. Hit this endpoint:
`GET : <domain name>/rest/V1/products/?searchCriteria[filterGroups][0][filters][0][field]= category_id&searchCriteria[filterGroups][0][filters][0][value]=3&searchCriteria[sortOrders][0][field]= position&searchCriteria[sortOrders][0][direction]=ASC&searchCriteria[pageSize]=5`

![Screenshot from 2021-01-08 10-44-33](https://user-images.githubusercontent.com/51679138/103993620-8d2ab100-519e-11eb-8a50-0c8c50135d34.png)

### Expected result :heavy_check_mark: 
The product's list should be sorted by "position" parameter

### Actual result: :heavy_multiplication_x: 
The product's list is not sorted by the "position" parameter

![2021-01-08_10-45](https://user-images.githubusercontent.com/51679138/103993726-b4817e00-519e-11eb-9111-e6d3874f420e.png)

Search Criteria, as returned in the response 
```
"search_criteria": {
    "filter_groups": [
      {
        "filters": [
          {
            "field": "category_id",
            "value": "3",
            "condition_type": "eq"
          }
        ]
      }
    ],
    "sort_orders": [
      {
        "field": "position",
        "direction": "ASC"
      }
    ],
    "page_size": 5
  }
```

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40344` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
