### ISSUE TITLE
[Feature request] Add store group configuration scope

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#316]
For now we have 3 variants configuration scope:
- default
- website
- store view

I think we need add new scope betwean website and store view - store_group.

For example:
we have one magento website with 2 stores(2 domains) + 2 mobile themes for them (+2 domains). So we created structure:
* store 1
  * store 1 desktop store view 
  * store 1 mobile store view 
* store 2
  * store 2 desktop store view 
  * store 2 mobile store view 

For design we have next structure:
* desktop package
  * default
  * store 1
  * store 2
* mobile package
  * default
  * store 1
  * store 2

For now we need configure for store 1 themes (Translations, skins, layout, etc.), so I need set theme value "store 1" for desktop store view and for mobile store view. 

If we have store_group scope we should be change theme value at store_group scope only.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-23733

**Comment by Michal-sk** [comment]
This gives so much more options than just themes. I was search for this when i stumbled on this github issue.

How i would like to use it:
Default would be the default configuration for our own store. Than we would create a Website as a package on which we would define package specifick settings. Than we could create stores for other people and again cascade settings down to them for there own store, than they could even change additional settings regarding the store view.

That way we can have a multistore and have Websites as a category. So we could have 3 Website's all with there own settings, like Free package, Extra package and Special package and than people could get a own store with the specific settings.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Add-store-group-configuration-scope/idi-p/46263).
