### ISSUE TITLE
Setting Prices to inc Tax makes all products show special price

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#3160]
I have a configurable product for sale at £120 and all its simple children are also £120
I have UK VAT Rule set up at 20%

If I set VAT Catalog Prices tax_calculation_price_includes_tax to Include Tax (all Tax settings are set to include tax) then the product prices shows special price of £100, original £120.
Basically, when working out the special price, it deducts the tax value and shows as a special price

**Comment by mazhalai** [comment]
@teuma86 This is similar to #2471 can you please try on the develop branch?

**Comment by teuma86** [comment]
This is not possible on our current build project.  Is there a commit I can review and make the changes?

**Comment by tang-yu** [comment]
Here is the commit: https://github.com/magento/magento2/commit/bf90e0b955689acd1c31441873aaa802fe4b35ed

Sorry for the delayed reply.
