### ISSUE TITLE
Shipping address region leaking into billing address

### ISSUE THREAD

**Issue by kassner** [magento/magento2#31608]
### Preconditions

1. Magento 2.4;

### Steps to reproduce

1. Create a purchase with billing address in the UK and Shipping address in Croatia. Make sure the `State/Province` field for the billing address is empty.

### Expected result

1. Billing address does not have a region name.

### Actual result

1. Billing address has a region name.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kassner** [comment]
@magento give me 2.4-develop instance

**Comment by kassner** [comment]
Managed to reproduce it:

Shipping address:

![Screenshot from 2021-01-11 14-20-01](https://user-images.githubusercontent.com/301255/104187708-7f806000-5418-11eb-81b9-cc7373180bab.png)

Billing address:

![Screenshot from 2021-01-11 14-20-47](https://user-images.githubusercontent.com/301255/104187654-6bd4f980-5418-11eb-86ee-bcd014dea1cd.png)

![Screenshot from 2021-01-11 14-20-41](https://user-images.githubusercontent.com/301255/104187735-86a76e00-5418-11eb-8b47-53e1de39992a.png)

Placed order:

![Screenshot from 2021-01-11 14-21-26](https://user-images.githubusercontent.com/301255/104187753-8d35e580-5418-11eb-9d4c-b12d29b56b2f.png)

**Comment by kassner** [comment]
It would be good if someone else can confirm the bug, given I opened it myself.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40362` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kassner** [comment]
Quick patch: https://gist.github.com/kassner/deae8483ecbbf2e4657fac2423b98c4e

**Comment by saphaljha** [comment]
@magento I am working on this issue.

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance
