### ISSUE TITLE
Flat Rate Shipping method Title will not save

### ISSUE THREAD

**Issue by ghost** [magento/magento2#31609]
Hello,

I'm trying to save the title of our flat rate shipping. This should be vwery simple, I'm visiting Store>Configuration>Sales>Shipping Method, and the field for Title currently says "Flat Rate (Orders under $50.00 ship U.S. Priority Mail; Orders over $50.00 ship by UPS Ground)" and I need it to say "Flat Rate (Orders under $80.00 ship U.S. Priority Mail; Orders over $80.00 ship by UPS Ground)"

Whenever I update it and click save configuration, it reverts back to the "$50" blurb. No matter how many times i try it. I've tried in all the different store Scopes, (Default, Main site, and this specific site). I've tried setting them all to use the default value and setting the default value to "Use System," saved it, and that stuck, but then I tried to set a custom title in Default and set it to the $80 blurb, and it immediately reverts back to the $50 blurb. 

Megento Version - 2.3.4-p2
Server OS: CentOS Linux 7
php 7.1.33
mysql: ver 15.1, distrib 10.2.33-MariaDB

### Steps to reproduce (*)
1. Visit Store>Configuration>Sales>Shipping Method 
2. Update Title Field
3.  Click Save

### Expected result (*)
1. The value should change in the field, and the database

### Actual result (*)
1. Nothing chages, and it reverts to the previously saved Title

**Comment by jeffspurlock** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@jeffspurlock - Have you reproduced this issue again on the latest Magento Instance?

**Comment by ajijshekh123** [comment]
@jeffspurlock - If you have reproduced this issue again you can reopen it.
