### ISSUE TITLE
pages not view and keep long loading.

### ISSUE THREAD

**Issue by daraadil** [magento/magento2#31616]
hi sir,
problim is : pages not view and keep long loading.

![Inkedscreencapture-kashmiranywhere-admin-nl12k8-cms-page-index-key-beeed989c0f8e3e95e393ecffcbb6f0fc7d735b1a06d68ad31d395280090d915-2021-01-12-17_09_53_LI](https://user-images.githubusercontent.com/57980700/104310189-508deb00-54f9-11eb-9023-cefde20ab969.jpg)

**Comment by krishprakash** [comment]
Hi @daraadil. Have you checked in latest clean magento instance as instructed [here](https://github.com/magento/magento2/issues/31616#issuecomment-758602274)

**Comment by krishprakash** [comment]
Hi @daraadil. Feel free to reopen the ticket if you confirm that issue reproduce on latest magento instance
Thanks!!
