### ISSUE TITLE
There was no Home CMS page configured or found.

### ISSUE THREAD

**Issue by daraadil** [magento/magento2#31617]
hi sir ,

my cms not found cms home page, 
every thing is all right but again and again show this error 
please help me 
![screencapture-kashmiranywhere-admin-nl12k8-cms-page-index-key-beeed989c0f8e3e95e393ecffcbb6f0fc7d735b1a06d68ad31d395280090d915-2021-01-12-17_20_05](https://user-images.githubusercontent.com/57980700/104311047-af079900-54fa-11eb-804e-6ecf447829d5.png)
![screencapture-kashmiranywhere-admin-nl12k8-admin-system-config-edit-section-web-key-74688ca076ec702d2f56d45998936b905ecc766191f212641830c1b20af2f305-2021-01-12-17_20_31](https://user-images.githubusercontent.com/57980700/104311054-b0d15c80-54fa-11eb-9e07-3796bcee9ddd.png)

**Comment by krishprakash** [comment]
Hi @daraadil. No need to create separate ticket. Kindly mention in previous ticket which you raise.

**Comment by krishprakash** [comment]
Closing this issue as [similar issue](https://github.com/magento/magento2/issues/31616) is already added
