### ISSUE TITLE
Create admin user with role managed storewise

### ISSUE THREAD

**Issue by gg24** [magento/magento2#3161]
I want to create a plugin in magento2.0 which helps to create a admin user who should restrict role/store/website wise.Is it possible in magento2.0, because as i found this feature was not present in magento1.9(although it was in magento 1.9 EE).

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
