### ISSUE TITLE
Abandoned cart wrong customer ID

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3162]
When I'm click on a abandoned cart, i'm redirect to an other customer

Tested on Magento 2.0.0 and 2.0.1

![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/12616242/725bf33c-c50a-11e5-94d2-fff12a996943.jpg)

![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/12616281/aec007a0-c50a-11e5-8887-b7052fb75d9a.jpg)

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-48527

**Comment by quienti** [comment]
Any news from your internal ticket ?

**Comment by sevos1984** [comment]
Still in progress

**Comment by quienti** [comment]
Fixed with commit https://github.com/magento/magento2/commit/de942b806f749c772a9d9a5413937571db898adf
