### ISSUE TITLE
404 errors after install and deploy

### ISSUE THREAD

**Issue by pushontom** [magento/magento2#3164]
![image](https://cloud.githubusercontent.com/assets/6860461/12622775/dd6eda40-c51e-11e5-8664-4ca1b5f8a01a.png)

Has anyone come across this? I've tried all sorts to resolve it and I'm getting nowhere fast.

**Comment by mazhalai** [comment]
@pushontom what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) are you in? if you are in production mode, did you run `bin/magento setup:static-content:deploy`? Also, what web server are you using apache or nginx?

**Comment by davidalger** [comment]
Closing due to lack of reply from OP
