### ISSUE TITLE
Braintree refunds should return Refund transaction id instead of parent id with "-refund" appended

### ISSUE THREAD

**Issue by Dannez83** [magento/magento2#31655]
### Description (*)
Braintree refunds display the original/parent transaction id with "-refund" appended. This is not helpful from an accounts reconciliation point of view or from a customer service point of view when communicating the transaction id of the refund to the customer. The actual refund transaction id would be much more suitable. The parent transaction ID is already set in a separate field in the table. Duplicating the transaction ID into another field and adding "-refund" onto the end provides no benefit and actually fails to provide accurate information

### Expected behavior (*)
The refund transaction ID should match the refund transaction id in Braintree. 

### Benefits
The refund transaction id will match the refund transaction id in Braintree. The customer is given more accurate information. The store owner is able to reconcile payments more easily  

### Additional information
None necessary. This seems pretty self explanatory to me. Real transaction id better than made up transaction id.

**Comment by Dannez83** [comment]
@magento give me 2.4-develop instance

**Comment by tobiasolge** [comment]
+1

**Comment by mosky17** [comment]
+1

**Comment by nicolasperic-ba** [comment]
To get this fixed after refund on payment method you need to set the following payment fields with the generated refund transaction ID  _($refund->getId() is just an example)_
```
    $payment->setLastTransId($refund->getId());
    $payment->setTransactionId($refund->getId());
```

Check in here `vendor/magento/module-sales/Model/Order/Payment.php`
When a refund is made with a `$creditmemo`, lines **699-701**
```
    $gateway->refund($this, $baseAmountToRefund);

    $creditmemo->setTransactionId($this->getLastTransId());
```
Some lines below it will call `addTransaction` function that will use from payment the transaction_id 
```
    // update transactions and order state
    $transaction = $this->addTransaction(
        Transaction::TYPE_REFUND,
        $creditmemo,
        $isOnline
    );
```
