### ISSUE TITLE
Elasic Search license change to SSPL affecting Magento2 license

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#31656]
Elastic Search changed to the SSPL license (according to OSI not even "open source" anymore).
This may or may not remove the abilty of Magento2 to use it in it's current version as a search
enginge  for category listing while keeping Magento2 under the current license.

License:
https://www.mongodb.com/licensing/server-side-public-license

Quote:
"13. Offering the Program as a Service.

If you make the functionality of the Program or a modified version available to third parties as a service, you must make the Service Source Code available via network download to everyone at no charge, under the terms of this License. Making the functionality of the Program or modified version available to third parties as a service includes, without limitation, enabling third parties to interact with the functionality of the Program or modified version remotely through a computer network, offering a service the value of which entirely or primarily derives from the value of the Program or modified version, or offering a service that accomplishes for users the primary purpose of the Program or modified version."

**Comment by skearns64** [comment]
[disclaimer: I work Elastic] 

The license change[1][2] announced yesterday will have **no impact** on Magento users using Elasticsearch. 

The change involves the source code of Elasticsearch, which is moving from Apache 2.0 to be dual licensed under the Elastic License and SSPL. However the users of Magento are not typically building Elasticsearch from source directly. 

The default distribution is **free to use** here, has no copyleft aspects, and will remain under the Elastic License as it as been for the last few years. We have thousands of folks using our default distribution with Magento today. 
For folks who are using the Apache 2.0 licensed distribution, you will need to switch to the default distribution when you upgrade to 7.11 or above, which includes many additional free features, like encrypted networking and role-based access control, etc. 

We have an FAQ at [2] that should help clarify most questions, and we're happy to answer additional questions at elastic_license@elastic.co. This change should not impact users of Magento.

[1] https://www.elastic.co/blog/licensing-change
[2] https://www.elastic.co/pricing/faq/licensing

**Comment by jabdoa2** [comment]
It does affect most enterprise users as their legal departments typically disallows using software under non-opensource licenses (such as SSPL in OSI sense). At least it invokes lengthy legal approval/exception processes. I'm not a legal expert but I heared that SSPL induces a lot of legal risks because the wording is vague in a lot of points. I know a few companies which even stricly disallow using Elasicsearch 7.11+.

**Comment by sdzhepa** [comment]
Hello @YiffyToys @jabdoa2 @skearns64 

Magento team aware of it and work in progress now.

**Comment by jonashrem** [comment]
I think this still has some relevance @ Stale Bot

**Comment by hostep** [comment]
It looks like Adobe is planning to move to [Opensearch](https://www.opensearch.org/) according to [the roadmap](https://devdocs.magento.com/release/roadmap.html) they released yesterday.

**Comment by engcom-Lima** [comment]
Hi @YiffyToys 

Thanks for your contribution and collaboration.
As per the @hostep  [comment](https://github.com/magento/magento2/issues/31656#issuecomment-948300013) magento is now supporting OpenSearch in there compatible version. Kindly refer the [document](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) for your reference.
Kindly close the issue.

**Comment by engcom-Lima** [comment]
Hi @YiffyToys ,

As per above [comment](https://github.com/magento/magento2/issues/31656#issuecomment-761296521) there will be no impact on Magento users .
Hence, marking this issue as non-issue. If you are facing any issue kindly create new ticket.

Thanks

**Comment by frogfx** [comment]
I’m using EUI or Elastic Charts in my application outside of Kibana, how does this affect me?
If your application is not a hosted or managed service, you may not be affected at all. If you would like clarification or have additional questions, please reach out to us at [elastic_license@elastic.co](mailto:elastic_license@elastic.co).

what does this mean?

_can I use EUI for the UI of one of the property management applications which does not use any Kibana or ES, and host it and sell this to client_?  I am not legal expert , please guide me
