### ISSUE TITLE
Customers cant change their gender anymore

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31657]
### Preconditions (*)

 I have two shops with 2.4.1
In the first shop I can still change the gender from the customer account page.

![image](https://user-images.githubusercontent.com/16349349/104729571-e9f71000-5738-11eb-8f86-2c6e2f47c73d.png)

In the second shop the field does not show.

Normally you could enable and disable the feature from the magento backend:

![image](https://user-images.githubusercontent.com/16349349/104729315-88cf3c80-5738-11eb-8796-733e2c66e202.png)

But the field does not exist anymore.

### Steps to reproduce (*)

-

### Expected result (*)

-

### Actual result (*)

-

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Should we change  title to "Customer gender config not respect scope store ?" Basically in your case the second store not show gender select

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance
