### ISSUE TITLE
Update to CE 2.0.1 breaks Web Setup Wizard

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3166]
Hi,

I have an install of Magento using composer.

I used the web setup wizard to apply update from 2 to 2.0.1.  It stalled at 
`./composer.json has been updated`

In an attempt to resolve the issue I updated via terminal.  

```
        cd to <your_install>/bin
        su magento_user

        ./magento maintenance:enable

        # ran with sudo
        composer self-update

        # cd to directory with composer.json
        composer update

        # to fix my broken file permssions
        sudo chown -hR magento_user:www-data /var/www/html/<your_install>
        # set magento to be executible
        sudo chmod u+x magento

        ./magento setup:di:compile

        ./magento setup:upgrade

        ./magento cache:flush
        ./magento maintenance:disable
```

Now the footer says I'm on version 2.0.1 but when I go to the web setup wizard page it still shows the stalled page.

![upgrade_bug](https://cloud.githubusercontent.com/assets/16491875/12623831/e7c27e72-c4f9-11e5-8dd2-f6eeb066c46f.PNG)

Any thoughts on how to get the Web Setup Wizard page functioning again?

Note similar issues on the community forums:  https://community.magento.com/t5/Version-Upgrades-for-2-x/Upgrading-to-2-0-1-stuck/m-p/26815#U26815

Thanks.

**Comment by mazhalai** [comment]
@Jedwards-Eric can you please check your `var` folder for any files with `update_status.txt` or files beginning with `.`

**Comment by ghost** [comment]
/var$ ls -la
total 68
drwxrwx--- 10 magento_user www-data 4096 Jan 26 17:56 .
drwxrwx--- 12 magento_user www-data 4096 Jan 26 14:02 ..
drwxrwx---  2 magento_user www-data 4096 Jan 27 00:00 backups
drwxrwx--- 19 magento_user www-data 4096 Jan 26 17:56 cache
drwxrwxrwx  3 magento_user www-data 4096 Dec 30 12:29 composer_home
-rw-rw-rw-  1 magento_user www-data 1851 Jan 22 17:07 composer.json
drwxrwx---  5 magento_user www-data 4096 Jan 26 17:56 generation
-rw-r--r--  1 magento_user www-data   30 Jan 26 14:02 .htaccess
drwxrwx---  2 magento_user www-data 4096 Dec 29 17:09 log
drwxrwx---  8 magento_user www-data 4096 Jan 26 17:56 page_cache
-rw-rw-rw-  1 magento_user www-data 1885 Jan 27 14:42 .setup_cronjob_status
drwxrwx---  2 magento_user www-data 4096 Jan 26 17:56 tmp
-rw-rw-rw-  1 magento_user www-data  164 Jan 22 17:09 .type.json
-rw-r--r--  1 magento_user www-data  148 Jan 27 14:42 .update_cronjob_status
-rw-r--r--  1 magento_user www-data    0 Jan 22 17:10 .update_in_progress.flag
-rw-rw-rw-  1 magento_user www-data    0 Jan 22 17:10 .update_queue.json
-rwxrwxrwx  1 magento_user www-data  486 Jan 22 17:10 update_status.log
-rwxrwxrwx  1 magento_user www-data  486 Jan 22 17:10 .update_status.txt
drwxrwx---  4 www-data     www-data 4096 Jan 26 17:56 view_preprocessed

/var$ tail -40 update_status.log
[2016-01-22 17:10:03 EST] Job "maintenance_mode {"enable":true}" has been started
[2016-01-22 17:10:03 EST] Magento maintenance mode is enabled.
[2016-01-22 17:10:03 EST] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-01-22 17:10:03 EST] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}" has been started
[2016-01-22 17:10:03 EST] Starting composer update...
[2016-01-22 17:10:04 EST] ./composer.json has been updated

**Comment by mazhalai** [comment]
@Jedwards-Eric is there anything in `.update_queue.json`

**Comment by ghost** [comment]
`.update_queue.json` is empty.

**Comment by mazhalai** [comment]
It is quite possible that update was successful, but since the `.update_in_progress.flag` could not be cleared due to restricted permissions, system upgrade is stuck. Can you please update permissions for all files within `var` to be writeable by the web user as well as cron user? 

Since you started update via web, and finished it on terminal, _and_ upgrade did apply, I think it is safe to remove `.update_in_progress.flag`, Then system update will be back to normal

**Comment by ghost** [comment]
Removing `update_in_progress.flag` resolved the issue.  I will double check user permissions.  Thank you for your help.
