### ISSUE TITLE
Feature Request: Command Line Installer Should have Interactive Prompts

### ISSUE THREAD

**Issue by astorm** [magento/magento2#3167]
Running the command line installer with no arguments results in the following error.  Most other PHP applications with command line installers will prompt the user with Symfony's interactive command prompts for missing arguments.  It would be nice if Magento 2 did the same

```
$ ./magento setup:install
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
User Name is a required field.
First Name is a required field.
Last Name is a required field.
Please enter a valid email.
Password is required field.
Your password must be at least 7 characters.
Your password must include both numeric and alphabetic characters.



  [InvalidArgumentException]   
  Parameter validation failed  
```

Steps to Reproduce
1. `cd bin`
2. `./magento setup:install`

Expected Behavior: Magento CLI prompts users to enter missing arguments
Actual Behavior: Magento CLI dies with an error

**Comment by ktomk** [comment]
@astorm: As an alternative may I suggest to make use of the magerun command for the setup? It is the `install` command and has the functionality you're looking for:

```
n98-magerun2 install
```

it starts the interaction then asking which version you'd like to install (if no arguments provided) first:

![magerun2-install](https://cloud.githubusercontent.com/assets/352517/12695683/0c5c1c58-c756-11e5-8b68-61379a044fa7.png)

(disclosure: I contribute to Magerun)

**Comment by astorm** [comment]
Any update on this feature request?

/cc @piotrekkaminski

**Comment by mazhalai** [comment]
@astorm for this we do have a story MAGETWO-26534

**Comment by astorm** [comment]
@mazhalai Dos that mean it's fixed?  Being worked on?  Might happen?  Is acknowledged but will slowly die on the vine?  It's hard for outsiders to understand what having a story means if they're not a part of your process :)

**Comment by pboisvert** [comment]
@tanya-soroka can you provide any insight on where this one sits?

**Comment by piotrekkaminski** [comment]
@astorm we don't have yet a final decision on that. The performance of the commands has higher priority.

**Comment by tanya-soroka** [comment]
Updates has been provided by @piotrekkaminski .
We have created a story for this, MAGETWO-26534.

**Comment by astorm** [comment]
No update on this since May. Assuming it's not a priority for the engineering team and closing out.
