### ISSUE TITLE
z-index issue with notification messages in Magento 2 backend

### ISSUE THREAD

**Issue by tinogo** [magento/magento2#3168]
When opening the notification messages from Magento and currently displaying the catalog products grid of the Magento 2 Backend, the notifications wrapper and the "Add product" split-button are overlapping because of the same z-indexes (400 in this case).

![bildschirmfoto am 2016-01-27 um 21 15 33](https://cloud.githubusercontent.com/assets/3515498/12626913/70c4c586-c53b-11e5-884f-3414d9081452.png)

**Comment by mrkhoa99** [comment]
@tinogo Which's version Magento you used? Your browser shown any errors?

**Comment by tinogo** [comment]
I'm currently using revision c0fc5b252187fce67c4415ab697fd2d1df678993 from the github repository.
The Browser doesn't show any errors.
The Mage 2.0.0 release version does work flawlessly in this regard, if this helps?!

**Comment by mrkhoa99** [comment]
I'm using Mage version 2.0.0 and also checked on latest version 2.0.1. They are ok. You try to install latest version 2.0.1 from https://www.magentocommerce.com/download

**Comment by tinogo** [comment]
To clarify this bug report:
I'm using the current Magento 2 developer version, checked out from your GIT-Repository ("bleeding edge").
I just wanted to make sure, that there aren't getting any new bug introduced with the new features. (My mentioned bug exists only in the current Magento 2 Github develop-branch)

**Comment by undefined-olha** [comment]
@tinogo thank you for reporting this issue. Internal issue MAGETWO-47608.

**Comment by MomotenkoNatalia** [comment]
@tinogo Internal ticket MAGETWO-47608 is closed and delivered to mainline. Please let us know if you still have an issue.
