### ISSUE TITLE
jsTree jquery plugin refers to style.css instead of style.min.css

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#3170]
When deploying with minified js and css, jsTree still refers to the unminified version of its stylesheet in its javascript. However, the minified version is not deployed to pub/static. This can be probably be resolved by configuring the correct minified style url for jsTree which does exist in pub/static.

See the failing url in the javascript console of the screenshot included below.

![image](https://cloud.githubusercontent.com/assets/253579/12630342/fe457f30-c519-11e5-9628-a7c177e2824f.png)

If I change the url to reference style.min.css, I see the expected icons next to the folder names in the UI.

![image](https://cloud.githubusercontent.com/assets/253579/12630631/5b85cc08-c51b-11e5-9845-d00483322da6.png)

**Comment by vrann** [comment]
@keithbentrup Thanks for reporting, this looks like a bug in configuration.

**Comment by pivulic** [comment]
We have the same issue with: http://www.vaimo.com/snaps/pablo.ivulic/acl-roles-not-working-with-minified.png

**Comment by stevenvdp** [comment]
We also have this issue.
Any progress @vrann ?

**Comment by vincentwinkel** [comment]
One year and half after, still not fixed...

**Comment by magento-engcom-team** [comment]
@keithbentrup, thank you for your report.
We've created internal ticket(s) MAGETWO-84017 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @keithbentrup

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@keithbentrup thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
