### ISSUE TITLE
Need an ability to modify an UI component XML declaration by an extension like we can do with other XML declarations

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3172]
An example of the UI component XML declaration:

https://github.com/magento/magento2/blob/c58d2d/app/code/Magento/Ui/view/base/ui_component/etc/definition.xml#L182-L188

**Comment by tkacheva** [comment]
@vkorotun please take a look

**Comment by tkacheva** [comment]
internal ticket MAGETWO-57229

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Need-an-ability-to-modify-an-UI-component-XML-declaration-by-an/idi-p/46096).
