### ISSUE TITLE
Can't disable all 2FA providers

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#31734]
### Preconditions (*)

1. Magento 2.4.1
2. Can disable all 2FA providers

### Steps to reproduce (*)

1. Stores/Configuration/Security/2FA/
2. General/Providers to use: Choose off everything providers
3. Automatically open window "Are you sure you want to disable all currently active providers?"
![act_pro](https://user-images.githubusercontent.com/51680745/105190165-683f2200-5b3e-11eb-81a2-670f7ff9a36a.png)
4. Click button "Confirm"
5. Click button "Save Config"
6. Clear cache

### Expected result (*)

1. Can disable all providers
![1](https://user-images.githubusercontent.com/26794034/104853836-1dd65f00-590c-11eb-9ee0-ca11b7cd9409.png)

### Actual result (*)

1. Automatically returns to the same provider selection even if I selected it off (example. Google Authenticator)
![3](https://user-images.githubusercontent.com/26794034/104853849-2c247b00-590c-11eb-8ff7-07d4e54cc983.png)

2. So I can't disable all providers. Always someone need to be chosen.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40521` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
I think his issue was raised a few times already in the past. 
Even @markshust created a module for disabling 2fa for Magento 2.4 https://github.com/markshust/magento2-module-disabletwofactorauth
@sivaschenko @sidolov maybe we might have similar functionality out of the box? What do you think about it?

**Comment by Userr017** [comment]
Magento 2.3.5-p2 is easier method disable all.
![4](https://user-images.githubusercontent.com/26794034/105342545-28814480-5be9-11eb-9ccd-56bf1fe7b596.png)

**Comment by hostep** [comment]
I think @nathanjosiah could have some interesting feedback on why it isn't allowed to disable 2FA through the Magento configuration system, pretty sure it's considered a security risk.

**Comment by nathanjosiah** [comment]
Thank you for your submission! 

The official relevant Q&A for this is:

>**Can you activate 2FA for just a few user in Magento or does everyone have to use 2FA when they log in?**
Magento recommends all admin users to have 2FA enabled when loggin into their admin account. For webstores running on Magento 2.4 and higher, 2FA is enabled by default for every user.

Magento does not and will not provide an official mechanism to disable 2FA. If you do so it is at your own risk.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
