### ISSUE TITLE
CSS Not working properly for filterInput on Ui Component Grid

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#31743]
### Summary (*)
I want to Add Only Filter in Order Grid Filters Function is Working Fine But CSS is Not working

### Examples (*)
I want to Add Column Like this

![likeSample](https://user-images.githubusercontent.com/51072292/104913777-ef11c480-59af-11eb-8eb8-6ac48d473fdb.png)

so i tired something like that in 

Vendor/Module/view/adminhtml/ui_component/sales_order.grid.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <container name="listing_top">
             <filters name="listing_filters" displayArea="dataGridFilters">
                 <settings>
                    <dataScope>filters</dataScope>
                 </settings>
                 <filterInput
                     name="custom_column"
                     provider="${ $.parentName }"
                     sortOrder="70" >
                     <settings>
                         <label translate="true">Custom Column</label>
                         <dataScope>custom_column</dataScope>
                     </settings>
                 </filterInput>
    </container>
</listing>
.
```

but I am getting something like that

![screenshot-local kipling com-2021 01 18-17_17_23](https://user-images.githubusercontent.com/51072292/104914605-35b3ee80-59b1-11eb-9ea3-d30d57509d40.png)

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MarianNapi** [comment]
But...Wtf?

This shit is still happening in newer Versions of Magento - So can someone PLEASE look into this crap?
