### ISSUE TITLE
Write stream file

### ISSUE THREAD

**Issue by giangitman** [magento/magento2#3174]
Hi,

I don't see the function streamOpen in Magento\Framework\Filesystem\Io\File, in Varien_Io_File magento1 have this function. Is that correct?

**Comment by tkn98** [comment]
Opening and writing to a stream is possible via `Magento\Framework\Filesystem\Driver`. Just saying, it's perhaps things have moved a little.

**Comment by okorshenko** [comment]
@tkn98 thank you for your answer

**Comment by MagePsycho** [comment]
I have been facing the same issue:

```
$io   = $this->ioFileFactory->create();
$path = $this->directoryList->getPath('var') . '/log/custom_dir';
$name = date('Y-m-d-H-i-s');
$file = $path . '/' . $name . '.log';

$io->setAllowCreateFolders(true);
$io->open(array('path' => $path));
$io->streamOpen($file, 'w+');
$io->streamLock(true);
```

And the `openStream()` method is missing in class `Magento\Framework\Filesystem\Io\File`.
Is this a bug or what?

**Comment by tkn98** [comment]
@MagePsycho: Please try with `Magento\Framework\Filesystem\Driver`.

**Comment by cscd98** [comment]
@tkn98 it makes no sense.. streamOpen does not exist, but streamWrite does..

**Comment by kinjal24** [comment]
Hello, 

We can use below code instead of the streamOpen, streamWrite and streamClose.

```
foreach ($cssFileContent as $fileContent) {
    $handle = fopen($fileContent['filename'], 'w');
    fwrite($handle, $fileContent['content']);
    fclose($handle);
}
```
