### ISSUE TITLE
Magento Tax system needs updating to support modern sales tax collection at point of sale for multiple tax systems.

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#31745]
### Description (*)
The Magento TAX system needs updating to reflect modern Sales Tax collection at point of sale for multiple countries.

### Expected behavior (*)
Countries worldwide are modernising their sales tax systems, shifting more towards collecting sales taxes at the point of sale for international sales, and requiring sellers to register for tax in multiple countries, rather than just collecting sales tax in their home country and relying on collecting sales tax at the point of import for international sales.

From 1st January 2021, every country in the world who sells goods to the united kingdom must now register with the UK government for VAT and collect sales tax (UK VAT) at the point of sale and remit this to the UK government. Whilst it is possible to setup a tax rule to cover this, the invoice needs to state the GB VAT ID, and not the tax id of the stores local tax system.

The same will apply from 1st July 2021 for all sales to the EU 27 countries. Any seller, selling goods to any EU country will need to register with a TAX office somewhere within the EU, and collect sales tax (The appropriate sales tax for the buyers country) and remit this to the tax office in the EU country where the seller registered. Again, tax rules can be used for this, but the VAT ID needs to be displayed for the invoices based on where the order is being sent.

Norway currently runs the same scheme when selling goods over a certain threshold from anywhere in the world to norwegian buyers, the seller must register for tax with the norweigan govt, and state your norwegian tax id on the invoices.

So it would appear that we need new functionality

1. Instead of storing a TAX id for the whole shop, you should have a "Tax Registration" table where you can add the tax system name/tax Id/tax ID Label for each system that the seller is registered in.
2. Be able to specify Tax Registration (from above) for each TAX rule, so the correct tax ID can be included on the invoice, depending on which tax rule was triggered. You should be able to have multiple tax rules linked to a single Tax Registration.
3 Should continue to work with existing VAT implementation for automatic detection of Intra-EU customers and auto group placement.
4. Be able to specify the label aswell as the number as not everywhere uses VAT Number as the label, for example GST Reg No : VEOC Reg No : VAT Reg No :
5. The correct TAX ID needs to be displayed on the invoice depending on where the product is going/which tax systems the seller is signed up to collect tax for/which tax rule is triggered.

Or do we just add all the VAT ID's to the invoice and let the buyer work it out!!!

### Benefits
Improved support for the changing worldwide tax systems.

**Comment by gwharton** [comment]
Also note the following article which summarises the changes.

https://www.dlapiper.com/en/us/insights/publications/2020/12/uk-vat-changes-sale-of-goods-to-customers/

**Comment by gwharton** [comment]
Worldwide selling to the UK must register with HMRC UK and collect UK VAT at point of sale for all transactions under 135GBP unless the UK buyer provides a valid UK VAT/EORI number. This is law as of January 1st 2021 . The invoice must include the sellers UK VAT Number. For sales where the buyer presents a valid UK VAT/EORI number then no VAT is charged and the invoice MUST include a declaration saying the VAT must be accounted for by the buyer by reverse charge.

Worldwide selling to the EU must register with an EU VAT office and collect the appropriate EU VAT for the buyers country at point of sale for all transactions under 150EUR unless the EU buyer provides a valid EU VAT/EORI number. This will be law as of July 1st 2021 . The invoice must include the sellers EU VAT Number. For sales where the buyer presents a valid EU VAT/EORI number then no VAT is charged and the invoice MUST include a declaration saying the VAT must be accounted for by the buyer by reverse charge.

It is likely that other countries systems may operate differently, so I recommend a plugin based "Tax Scheme" system where tax systems can be added.

e.g Norway VOEC, Australia GST are also law as of now, if certain sales thresholds are exceeded.

**Comment by gwharton** [comment]
Also note, that the VIES system will no longer validate UK VAT numbers, so the current system is not capable of putting UK buyers into a "No VAT" customer group. UK VAT numbers will need to be validated by https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0

￼

This needs thinking about too. If the VAT validation (should be renamed to TAX validation in my opinion) is updated to support different tax schemes from different countries, then we need to rethink the "Valid VAT ID" groups and how this can work with existing intra EU stuff.

This is now a worldwide issue, not some niche EU/UK thing that can be ignored. Everyone worldwide, as of 18 days ago, has a need to validate UK VAT numbers and place customers into special group depending on validation result.

**Comment by hostep** [comment]
@gwharton: nice summary!
Do we have some official documentation from some government or European legislation on this? The blog you linked to is not an official document. Not saying that it is incorrect but I think we need some kind of official documentation to make sure what we are implementing in Magento is correct to the letter of the law.

Also extra requirement:
- Intra Union determination in Magento should no longer be done on countries only, since the Northern Ireland part of the UK is considered Intra Union (tax-wise) but the rest of the UK isn't.
Source: https://finance.belgium.be/en/enterprises/vat/international/brexit#q9, but it comes with an asterisk as it currently says:
> Your attention is drawn to the fact that the European Union and the British authorities do not agree for now about the implementation of the Protocol on Ireland and Northern Ireland. The VAT regulation which applies in the relations between the European Union could thus differ from the regulation presented in these FAQs.

So I don't know how accurate this is.

**Comment by gwharton** [comment]
Authoritative information for the UK can be found on the UK Goverment website here https://www.gov.uk/guidance/vat-and-overseas-goods-sold-directly-to-customers-in-the-uk

**Comment by gwharton** [comment]
And an article on the EU Commission website detailing the EU changes for July 2021. https://ec.europa.eu/taxation_customs/business/vat/modernising-vat-cross-border-ecommerce_en

**Comment by gwharton** [comment]
The two systems are pretty much the same, apart from the threshold value. They were both supposed to go live on 1st January, but because of Covid, the EU delayed for 6 months, but the UK still went ahead.

**Comment by gwharton** [comment]
https://github.com/gwharton/autocustomergroup

Interim solution.

**Comment by gwharton** [comment]
FFS

**Comment by devchris79** [comment]
Its not been our understanding that we must register with an EU VAT office from July, the VAT exemption of low value shipments (22€ or less) is removed at that point, but they importer will be contacted by the courier for fee collection (and probably apply a handling charge).

We ship worldwide and everything was pretty straightforward,  unfortunately the changes in shipping have added a huge amount of work. DHL now require a mandatory EORI number among other things when shipping to European businesses, so this is going to have to be added to the website.  

The EU allows VAT registering with a member state and VAT can be paid to the one point through the IOSS scheme for shipments up to 150€. The problem with IOSS is that you need to charge VAT at the destination countries VAT rate, in the case of the EU that means keeping track with 27 budgets....
