### ISSUE TITLE
Translate attribute in html template is not working when adding colon as part of the value

### ISSUE THREAD

**Issue by t-velichko** [magento/magento2#31760]
### Preconditions (*)
Magento 2.4.1, 2.4-develop
Developer Mode 

### Steps to reproduce (*)
1. Edit web/template/shipping.html in Magento_Checkout module and update here:
`<span translate="'Next'" />` to `<span translate="'Next: Review & Payment'" />` with colon in its value.

### Expected result (*)
no errors in console, the page loads as expected

### Actual result (*)
errors in console
```knockout.js:2982 Uncaught SyntaxError: Unable to parse bindings.
Bindings value: i18n: {'Next: Review & Payment'}
Message: Unexpected token '}'
    at new Function (<anonymous>)
    at createBindingsStringEvaluator (knockout.js:2982)
    at createBindingsStringEvaluatorViaCache (knockout.js:2973)
    at ko.bindingProvider.parseBindingsString (knockout.js:2959)
    at ko.bindingProvider.getBindingAccessors (knockout.js:2941)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3300)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2173)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2140)
    at Function.evaluateImmediate (knockout.js:2101)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1954)
```

Checkout page is not loading

### Additional info from Engcom
![next_review_paym](https://user-images.githubusercontent.com/51680745/105049080-f2bb4f00-5a74-11eb-8fe7-3407eab0d030.png)
1. Go to Storefront
2. Open Browser dev console
3. Add Product to Cart
4. Click Proceed to checkout

**Comment by engcom-Bravo** [comment]
Hello @t-velichko 

Thank you for your report.

We Confirm that the issue is reproducible on the latest 2.4-develop. Additional info from Engcom is added to the description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40488` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gixid192** [comment]
I think the syntax is: `Next\: newText`, it requires a slash there.
Maybe this should be updated in the docs?

**Comment by mrtuvn** [comment]
Have you try
`<span data-bind="i18n: 'Next: Review & Payment'"/>`

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
