### ISSUE TITLE
What is the rationale to have a BlockInterface when AbstractBlock is required (in Fw\View ?)

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#3176]
What is the rationale to have a _Magento\Framework\View\Element\BlockInterface_ when  _Magento\Framework\View\Element\AbstractBlock_ is required?

E.g. in [Magento\Framework\View\Layout\Generator\Block::getBlockInstance()](https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/lib/internal/Magento/Framework/View/Layout/Generator/Block.php#L261):

```
    if (!$block instanceof \Magento\Framework\View\Element\AbstractBlock) {
        throw new \Magento\Framework\Exception\LocalizedException(
            new \Magento\Framework\Phrase('Invalid block type: %1', [$block])
        );
    }
```

It makes no sense to me to program against abstract classes instead of the interface.

Shouldn't it be easy to just extract the public interface needed and drop the requirement on the abstract class?

**Comment by maxwhite-ua** [comment]
Hi,
Thank you @tkn98 for your question.

Magento is continuously evolving system. The next goal is eliminate abstract classes (super types) and use API interfaces instead.  In near future `Magento\Framework\View\Element\AbstractBlock` cease to be required and we will use `Magento\Framework\View\Element\BlockInterface` or similar interface instead. This is major backward incompatible change and will be done in nearest future. 

Please let us know if this works for you.

**Comment by tkn98** [comment]
+1 for having an interface instead. IMHO you can keep abstract classes, more important looks to type-hint the interface for method parameters. When then the abstract class implements the interface, it does indeed works for me :)

**Comment by MomotenkoNatalia** [comment]
@tkn98 Thank you for your submission!
Do you want keep the topic or we can close it?

**Comment by tkn98** [comment]
@MomotenkoNatalia: It's fine for me to keep it open until Interfaces are implemented for this abstract class and the typehint is intorduced (I think that covers your planned feature).

**Comment by MomotenkoNatalia** [comment]
@tkn98 We have an internal task in our backlog - MAGETWO-41049 for this improvement. 
Your issue is more appropriate for the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. That's why I'm going to close this issue.
