### ISSUE TITLE
Magento CE 2.0.1 Admin list issue

### ISSUE THREAD

**Issue by cgrechcw** [magento/magento2#3177]
Was running Magento 2.0.0 CE on Nginx and PHP 7.0 without any apparent issues apart from the failing indexing due to memory leak which was a known issue. I've just tried to upgrade to 2.0.1 but the Update wizard failed which is also a known issue. So i tried a fresh installation of 2.0.1 CE and managed to install successfully. I can also confirm that the indexing problem is resolved. However, whenever I try to visit the Catalog/Customers pages in backend, I get an 'Attention - Something went wrong.' error. Using the browser's development tools I noticed that the Ajax call to  "http://XXX.com/admin_cw/mui/index/render/key/2f135db323f1fb226c5db501df388b7c988d6bdda4132409b23450bc57d85d35/?namespace=customer_listing&search=&filters%5Bplaceholder%5D=true&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=entity_id&sorting%5Bdirection%5D=asc&isAjax=true"

is returning a 'Initialization error component, check the spelling of the name or the correctness of the call.' error (full stack below)

Can anyone help please? 

`Initialization error component, check the spelling of the name or the correctness of the call.
#0 /mnt/storage/www/otb/magento2/vendor/magento/framework/View/Element/UiComponentFactory.php(139): Magento\Ui\Model\Manager->prepareData(NULL)
#1 /mnt/storage/www/otb/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(25): Magento\Framework\View\Element\UiComponentFactory->create(NULL)
#2 /mnt/storage/www/otb/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(24): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#3 /mnt/storage/www/otb/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#4 /mnt/storage/www/otb/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#7 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#8 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Ui\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminAuthentica...')
#9 /mnt/storage/www/otb/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#10 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#12 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Ui\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'designLoader')
#13 /mnt/storage/www/otb/magento2/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#14 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#16 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Ui\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminMassaction...')
#17 /mnt/storage/www/otb/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#18 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#20 /mnt/storage/www/otb/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(52): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /mnt/storage/www/otb/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#24 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 /mnt/storage/www/otb/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /mnt/storage/www/otb/magento2/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#29 /mnt/storage/www/otb/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /mnt/storage/www/otb/magento2/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /mnt/storage/www/otb/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#32 /mnt/storage/www/otb/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}`

**Comment by cgrechcw** [comment]
A fresh install of 2.0.0 and problem is gone, re-installed 2.0.1 and the same issue occurs. I believe this is an issue related to just 2.0.1 on PHP7 maybe?

**Comment by barbala4o** [comment]
Did you find a solution about that ? I am using 2.0.2 CE with php7 and ran into the same issue ? ? ?

**Comment by cgrechcw** [comment]
Yes, in our case it was a wrong nginx configuration. We were missing the part in **bold**

_location / {
    try_files $uri $uri/ /index.php**?$args**;
}_

Hope it helps!

**Comment by barbala4o** [comment]
I am using apache 2.4 .... have no Idea what's wrong... maybe something with the .htaccess of magento or.... I don't know. Not exactly a server guy

**Comment by cgrechcw** [comment]
Could be... I'm not a server guy either but I noticed that when a request was hitting our server, the query string part (the parameters after the '?') were being truncated which cause the symptoms above. Make sure there isn't any apache configuration which eliminates querystrings

**Comment by barbala4o** [comment]
Yeah, problem was that I made a reference class for controller that extended a Module_UI controller and at the end of my execute method of the reference class I made 

`parent::execute()`

which apparently is wrong. Thanks for the replay though

**Comment by vrann** [comment]
@cgrechcw Thanks for reporting, it looks like a bug in Ui

**Comment by atomixstar** [comment]
Hello, I have same problem, on nginx and php 7?

location / {
try_files $uri $uri/ /index.php?$args;
}

this not helped me.

**Comment by anton-huz** [comment]
Hi @atomixstar ,
Looks like guys (@cgrechcw and @ barbala4o) fixed their issues.

If you faced with similar issue could you describe what exact problem you faced with?

Please, note:
- You can use [Magento's Stack Exchange](http://magento.stackexchange.com/) for consulting and wide questions
- You can use [Magento's Forum](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2) for question and proposals and talk about _same problems_
- Use [GitHub issues](https://github.com/magento/magento2/issues/new) in case you find wrong behavior in Magento App
- Also take into account option "**Use Web Server Rewrites**" on _Configuration_ → _Web_ page in Admin area. Switch it to _"No"_.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
