### ISSUE TITLE
Update laminas/laminas-http dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31780]
### Description (*)
Update laminas/laminas-http dependency version.
PHP 8 compatibility is available starting from version 2.14. Composer.json change is not required, only composer.lock file should be updated running `composer update laminas/laminas-http` command

**Comment by sivaschenko** [comment]
Already updated to compatible version

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @omaxmo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39665` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
