### ISSUE TITLE
Update laminas/laminas-view dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31784]
Depends on #31346

### Description (*)
Update laminas/laminas-view dependency from version "~2.11.2" to "~2.12.0"

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
@magento add to contributors team

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
@sivaschenko Depend from task #[31346](url)
