### ISSUE TITLE
Update laminas/laminas-mvc dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31783]
Depends on: https://github.com/magento/magento2/issues/31346

### Description (*)
Update laminas/laminas-mvc dependency from version "~2.7.0" to "~3.2.0"

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by konarshankar07** [comment]
Hello @sivaschenko  @bohdan-harniuk 
I have been working on this issue and I have already upgraded in https://github.com/magento/magento2/pull/31383 PR
Thanks

**Comment by bohdan-harniuk** [comment]
Hello, @konarshankar07 
Please, assign issues on yourself if you work on them.
Thanks

**Comment by konarshankar07** [comment]
Thanks @bohdan-harniuk 
@magento I am working on this

**Comment by konarshankar07** [comment]
@magento I am working on this

**Comment by konarshankar07** [comment]
@sivaschenko 
Dependency https://github.com/magento/magento2/issues/31346

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ProkopovVitaliy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39673` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
