### ISSUE TITLE
Update laminas/laminas-validator dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31781]
### Description (*)
Update laminas/laminas-validator dependency version.
PHP 8 compatibility is available starting from version 2.14. Composer.json change is not required, only composer.lock file should be updated running `composer update laminas/laminas-validator` command

**Comment by vlmed** [comment]
@magento I am working on this

**Comment by vlmed** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @vlmed. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39666` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
