### ISSUE TITLE
Magento MTF -- Functional Testing

### ISSUE THREAD

**Issue by jahved** [magento/magento2#3178]
Hi Everyone ,

I have been able to run the MTF test on Magento 1.14.2.1 but now I want to know how to create a customized Test using MTF from start.
Example:
Login as admin 
create a product
Login an Front End  

In Magento 1.14.2.1 we don't have php generatefixturexml.php. So to create and Update the fixture we need to do that manually.

Attached herein is what I have understood of how MTF Architecture works. please update if am wrong.

I need a tutorial to create a simple functional test in Magento MTF explaining clearly the inject, prepare test e.t.c
![mtf](https://cloud.githubusercontent.com/assets/16699956/12641428/e61a32ca-c5c8-11e5-8aba-04745b683d88.jpeg)

Also the scenario section is missing on the website.http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_scenariotest.html

**Comment by ghost** [comment]
Devdocs is aware of this request and we're tracking it via e-mail at the moment.

**Comment by veloraven** [comment]
Internal issue SAASOPS-20584

**Comment by dshevtsov** [comment]
Issue on topic about scenario tests
https://github.com/magento/devdocs/issues/517

**Comment by dshevtsov** [comment]
This issue is completed in https://github.com/magento/devdocs/issues/500

**Comment by tanberry** [comment]
@jahved  do you have the information you need? Can we close this ticket if Yes?
