### ISSUE TITLE
Update laminas/laminas-log dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31782]
### Description (*)
Update laminas/laminas-log dependency version.
PHP 8 compatibility is available starting from version 2.13. Composer.json change is not required, only composer.lock file should be updated running `composer update laminas/laminas-log` command

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by AndreyChorniy** [comment]
Depend from task https://github.com/magento/magento2/issues/31346
Waiting for merging them firstly

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @AndreyChorniy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39670` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
