### ISSUE TITLE
Admin page in Magento not Loading

### ISSUE THREAD

**Issue by madihamallick** [magento/magento2#31796]
### Summary (*)
cms and js not getting loaded in Admin page of a website in Magento of ver 2.1.3 and it is only showing html text.

### Examples (*)
https://movantechonline.com/admin/admin/index/index/key/91d10573d4aa03ab149f3ba8b5509d447731a94b51cff6284b4d055c0509c007/
![Capture (1)](https://user-images.githubusercontent.com/70858557/105365734-96972d00-5c24-11eb-90d0-55596f3af5c4.PNG)

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by madihamallick** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @madihamallick . Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com/) for general discuss about this problem
