### ISSUE TITLE
LESS Docs about custom theme mixins is wrong?

### ISSUE THREAD

**Issue by BB-000** [magento/magento2#31792]
Here [https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html](https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html) it says:

"Theme mixins (except extends) should be located in the source/utilities directory."

However, placing a mixin here and trying to use it in a _module.less file causes a grunt build error 'NameError: .lib-custom-mixin is undefined'.

So I think it should say something more like ""Theme mixins (except extends) should be located in the source/**lib**/_utilities.less file."?

OR if not, it needs to be a lot more clear?

**Comment by omaxmo** [comment]
@BB-000  We have a separate repository for docs https://github.com/magento/devdocs

**Comment by mrtuvn** [comment]
We should update docs for such case but in my opinion you maybe misunderstood 
For mixins you can declare in any files less and recall it for use (This is quick but trade off when you have big project and source code growth so management will be nightmare). Instead you can declare mixins another place

Default magento declare mixins in file _extends.less in source folder theme. Create you own file (copy file content from magento if you want)
Another way is define your mixins with your own name but make sure import it in less file (Magento will not automatic include it for you)

**Comment by mrtuvn** [comment]
By the way docs related with standard less has updated
https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html
