### ISSUE TITLE
Magento stops installing at 66% - Web wizard

### ISSUE THREAD

**Issue by alvaroadair** [magento/magento2#3181]
Have been trying to install this for almost a week now :-(  - Any help appreciated

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':

Module 'Magento_Bundle':

Module 'Magento_Quote':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_User':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_CatalogRule':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_Integration':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Weee':

Module 'Magento_ProductVideo':

Module 'Magento_CatalogSampleData':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_BundleSampleData':

Module 'Magento_Rss':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_SendFriend':

Module 'Magento_Ui':

Module 'Magento_Sitemap':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_Shipping':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':

Module 'Magento_WishlistSampleData':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Running recurring.. 

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':

Module 'Magento_Bundle':

Module 'Magento_Quote':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_User':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_CatalogRule':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_Integration':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Weee':

Module 'Magento_ProductVideo':

Module 'Magento_CatalogSampleData':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_BundleSampleData':

Module 'Magento_Rss':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_SendFriend':

Module 'Magento_Ui':

Module 'Magento_Sitemap':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_Shipping':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':

Module 'Magento_WishlistSampleData':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [eav] => 1 [config_integration] => 1 [config_integration_api] => 1 [full_page] => 1 [translate] => 1 [config_webservice] => 1 ) 

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing data.. 
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'PRIMARY'' in C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\Ampps\www\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `di...', Array) #5 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`di...', Array) #6 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `di...', Array) #7 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(1915): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`di...', Array) #8 C:\Ampps\www\magento\vendor\magento\module-directory\Setup\InstallData.php(294): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('directory_count...', Array, Array) #9 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(798): Magento\Directory\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #10 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #11 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #12 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #13 C:\Ampps\www\magento\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #14 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #16 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #17 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #21 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #22 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 C:\Ampps\www\magento\setup\index.php(31): Zend\Mvc\Application->run() #25 {main} Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'PRIMARY', query was: INSERT INTO `directory_country` (`country_id`,`iso2_code`,`iso3_code`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)' in C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\Ampps\www\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\Ampps\www\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `di...', Array) #4 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`di...', Array) #5 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `di...', Array) #6 C:\Ampps\www\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(1915): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`di...', Array) #7 C:\Ampps\www\magento\vendor\magento\module-directory\Setup\InstallData.php(294): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('directory_count...', Array, Array) #8 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(798): Magento\Directory\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #9 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #10 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #11 C:\Ampps\www\magento\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #12 C:\Ampps\www\magento\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #13 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #15 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #16 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #17 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #20 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #21 C:\Ampps\www\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #22 C:\Ampps\www\magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 C:\Ampps\www\magento\setup\index.php(31): Zend\Mvc\Application->run() #24 {main}

**Comment by mazhalai** [comment]
@alvaroadair looks like you had a previous installation and hence db was not clean. Please clean your db (drop database and re-create) and try again. Alternatively, you can run `bin/magento setup:uninstall` which will  and try again.

**Comment by mazhalai** [comment]
@alvaroadair was this issue resolved?

**Comment by alvaroadair** [comment]
Indeed, a database was imported before, deleted it and re-installed - Worked a treat, Thanks for your help

**Comment by richtunnel** [comment]
I experienced a similar error. My issue resulted in removing ";".dtll in the wrong file.

Example:

Instead of removing the semi colon in Apache -> config ->"remove semi colon"
I accidentally removed it within my php folder via php.ini.
