### ISSUE TITLE
with template hints displayed, nav sections are set to display:none

### ISSUE THREAD

**Issue by kennylawrence** [magento/magento2#31813]
### Preconditions (*)

1. Magento version 2.3.6
2. Template hints enabled using /?templatehints=hints configured in admin

### Steps to reproduce (*)
1. Go to https://website.com/?templatehints=hints
2. Observe that top.menu is not displayed
3. Open code inspector and locate : <div> with id="store.menu", then look at it's child <div> and see that display:none;
4. Inspect styles-l.css and observe these two rules:

  .nav-sections-item-content {
    display: block !important;
  }
  .nav-sections-item-content > * {
    display: none;
  }

### Expected result (*)

1. Should be able to see the navigation menu when templatehints are enabled.

### Actual result (*)

1. nav menu is hidden with templatehints are enabled

**Comment by engcom-Delta** [comment]
Hi @kennylawrence thank you for your report. Seems like it is not an issue on 2.4-develop as `.nav-sections-item-content>*{display:none}` if observe `styles-l.css`
**Result:**
:heavy_check_mark: Template hints work as expected
![image](https://user-images.githubusercontent.com/51681379/105678427-d0528700-5ef5-11eb-9425-29dadef3d875.png)
:heavy_check_mark: Element with `id="store.menu"` is not shown as `.nav-sections-item-content>*{display:none}`
![image](https://user-images.githubusercontent.com/51681379/105678606-055ed980-5ef6-11eb-89c7-3da20afbebd0.png)


If you'd like to update the issue, please reopen it.
