### ISSUE TITLE
It is too hard and extremly time consuming to do simple modifications in checkout

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31833]
### Summary (*)

It is very hard to make changes in checkout and even very simple tasks are extremly time consuming.

  [1]: https://i.stack.imgur.com/nnXai.png
  [2]: https://i.stack.imgur.com/40855.png

### Examples (*)

I am using Amazon Pay. Currently it looks like this in the checkout:

[![Current State][1]][1]

I need to add a logo and a link pointing to the info page about amazon pay:

[![Target State][2]][2]

I solved it with a workaround by adding a javascript at the bottom of the page which adds elements...
but this is not clean. How can I solve it the proper way? I was not able to find a template,

I was searching for a solution for half a day but did not figured it out.
How are we supposed to go on issues like this without having to analyse the whole core in a very long process?

It shouldnt take someone more than maximum 10 minutes to simply add an image, instead I struggled for half a day without any success and will need to spend even more time today, for such a simple task.

-------

I tried to solve it like seen in the [documentation](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_edit_form.html).

**THEME/Amazon_Payment/layout/checkout_index_index.xml:**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="steps" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="billing-step" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="payment" xsi:type="array">
                                                    <item name="children" xsi:type="array">
                                                        <!-- The name of the form the field belongs to -->
                                                        <item name="payments-list" xsi:type="array">
                                                            <item name="children" xsi:type="array">
                                                                <!-- the field you are customizing -->
                                                                <item name="amazonlogin" xsi:type="array">
                                                                    <item name="config" xsi:type="array">
                                                                        <!-- Assigning a new template -->
                                                                        <item name="elementTmpl" xsi:type="string">Amazon_Payment/form/element/test.html</item>
                                                                    </item>
                                                                </item>
                                                            </item>
                                                        </item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

**THEME\Amazon_Payment\web\template\form\element\test.html**:

`Foobar123`

Then I executed `rm -r pub/static/frontend/* var/view_preprocessed/* && bin/magento cache:flush` then I cleared the browser cache and reloaded the checkout,  but "Foobar123" does not appear anywhere.

### Proposed solution

- Either add more guides to show how to modify any single aspect of the checkout (or at least some visual examples with images and all that so we can understand it all better), or solve it properly with .phtml instead of overcomplicated intransparent solutions.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Viper9x** [comment]
Hi @Eddcapone, you've done the wrong way.
The purpose of [the document page](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_edit_form.html) you applied is "Add a custom template for a form field on Checkout page"
But your task is to customize the payment method, so I think you should join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in #general channel instead create a GitHub issue.

To do your task, do the following:
1. Add Amazon_Payment to the sequence node in module.xml
2. Copy _Amazon payment template file_  from vendor/amzn/amazon-pay-module/view/frontend/web/template/payment/amazon-payment-widget.html to your theme app/design/frontend/Vendor/theme_name/web/template/payment/paypal-express-in-context.html
3. Delete all files in the pub/static/frontend
5. Clear your browser cache and reload the pages.

**Comment by engcom-Hotel** [comment]
Hi @Eddcapone 

As per the comment made by Viper9x, it seems that your doubt has been clear. I am closing this issue for now. If you still have any doubt related with this issue you can reopen it or create a new ticket in case of any other issue.
