### ISSUE TITLE
Importing Products Not Working

### ISSUE THREAD

**Issue by lookinglavish** [magento/magento2#3183]
After I check my data product data ( with no errors) I click on the import button to add/update. The screen blurs and the rotator hangs up with no response. No products are loaded. Does anyone have an idea on how to fix this?

Thanks,

Rob

**Comment by katmoon** [comment]
Hi Rob,

Are the any errors in the browser console, Magento `var/log` folder or in `error_log'?

Could you
- clear browser cache
- clear Magento cache `rm -rf var/* pub/static/*`
  and recheck if the problem persists?

Thanks, Kateryna.

**Comment by lookinglavish** [comment]
No errors in Magento. When I check the file it states that "File is 
valid!" and is ready for import. When I click on import that's when I 
get the spinning dial that says "please wait...". I did clear my cache 
on all levels. It seems once I updated to 2.0.2 I'm getting this issue.

Thanks!

On 2/1/16 4:44 AM, Kateryna Muntianu wrote:

> Hi Rob,
> 
> Are the any errors in the browser console, Magento |var/log| folder or 
> in `error_log'?
> 
> Could you
> - clear browser cache
> - clear Magento cache |rm -rf var/\* pub/static/*| and recheck if the
>   problem persists?
> 
> Thanks, Kateryna.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/magento/magento2/issues/3183#issuecomment-177878406.

## 

Rob Culotta
Administrator
Looking Lavish
Phone: (877)750-7337
Email: admin@lookinglavish.com
Web: lookinglavish.com

**Comment by Elamguil** [comment]
Same error I too got in magento version 2.0.2. 
" When I check the file it states that "File is
valid!" and is ready for import. When I click on import that's when I
get the spinning dial that says "please wait...". I did clear my cache
on all levels. It seems once I updated to 2.0.2 I'm getting this issue."

Any one can help?

Thanks.

**Comment by bh-ref** [comment]
I am on 2.0.2 as well. I cleared the cache and redeployed the static view files. The spinning dial keeps saying "please wait...". The chrome dev tool console says 
**POST https://example.com/admin/admin/import/validate/?form_key=YEihyJp6HMl8S2dM 500 (Internal Server Error)**

**Comment by fhennessy** [comment]
I am on 2.0.2, and I am able to get past the spinning dial but I keep getting the error code " Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in rows...", but the rest of the product information imports successfully.  I checked all server permissions, cleared cache, verified image labels..Any help?

**Comment by asemenenko** [comment]
Hi @fhennessy, please check a read/write permissions to **pub/media/import** and **var/import**

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
