### ISSUE TITLE
Adding custom validation before order placement - 

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31848]
### Preconditions (*)

1. Magento 2.4.1
2. I am using Amasty Single Step Checkout, I did not tested it on a fresh magento

### Steps to reproduce (*)

Implement custom error validation like described in the [documentation](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_order.html).

Step 1:

```
define(
    ['mage/translate', 'Magento_Ui/js/model/messageList'],
    function ($t, messageList) {
        'use strict';
        return {
            validate: function () {
            
                console.log("validate called");                       // <--- add this
            
                const isValid = false; //Put your validation logic here

                if (!isValid) {
                    messageList.addErrorMessage({ message: $t('a possible failure message ...  ') });
                }

                return isValid;
            }
        }
    }
);
```
Load Checkout. Open the browser console and notice that your console.log message appears. The validate method is getting called before the submit button was even pressed.

### Expected result (*)

validate Method should only get called after the submit button is getting pressed.

### Actual result (*)

validate Method is getting called when page loaded.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: Validation method is called after button was pressed
![Peek 2021-01-27 15-18](https://user-images.githubusercontent.com/51681379/105996568-2fa9c600-60b3-11eb-9264-57d96a445e52.gif)

Are you able to reproduce issue on clean 2.4-develop?

**Comment by Eddcapone** [comment]
@engcom-Delta, Thank you for testing it. Then the amasty extension is probaly interfering with it and messing it up.
I will test it on fresh installations before creating issues in the future. Sorry!
