### ISSUE TITLE
After installing Magento 2

### ISSUE THREAD

**Issue by alvaroadair** [magento/magento2#3184]
Trying to Launch magento admin takes me to 404 error page

**Comment by alankent** [comment]
Given the number of successful installs, my advice is to run through and check your environmental settings, base URL, etc.  Also check the logs in var/log for additional error messages. But certainly most people are not hitting this problem, indicating it is more likely to be something about your environment.

**Comment by mazhalai** [comment]
@alvaroadair do you have mod_rewrite turned on?

**Comment by alvaroadair** [comment]
mod_rewrite is turned on - will check log - thanks

**Comment by mazhalai** [comment]
@alvaroadair also check `AllowOverride` directive(if you are using apache)

**Comment by MomotenkoNatalia** [comment]
@alvaroadair Please let us know if you still have an issue.

**Comment by mazhalai** [comment]
@alvaroadair Closing this ticket as non responsive. Please open a new ticket if issues arise.
