### ISSUE TITLE
UrlRewriteCollection store_id filter may be ambiguous

### ISSUE THREAD

**Issue by gabrieldagama** [magento/magento2#31853]
### Summary (*)

The collection `app/code/Magento/UrlRewrite/Model/ResourceModel/UrlRewriteCollection.php` has a function `addStoreFilter`, the problem here is that the filter is being added without table reference on `store_id`.

That may be a problem on extensibility whenever a join is added to the collection on a table that also has a `store_id` column.

### Examples (*)
Add a plugin that adds a join to this collection from a table that has `store_id` column.

### Proposed solution
Add main_table reference to the `store_id` on `addStoreFilter` function.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@gabrieldagama Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@gabrieldagama Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @gabrieldagama 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40650` were created

**Issue Available**: @gabrieldagama, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @gabrieldagama. Thank you for your report. 
The issue has been fixed in magento/magento2#31815 by @achatpc in 2.4-develop branch
Related commit(s):
 - [e6bfef3c7c7dfe4754df87ee41d4fd06a22e9a93](https://github.com/magento/magento2/commit/e6bfef3c7c7dfe4754df87ee41d4fd06a22e9a93)
 - [2edaf153c09f3442eea64a7f7d295113d4173f1f](https://github.com/magento/magento2/commit/2edaf153c09f3442eea64a7f7d295113d4173f1f)
 - [974e35b42f546aabacad7176364c6c802d4da279](https://github.com/magento/magento2/commit/974e35b42f546aabacad7176364c6c802d4da279)
 - [1f7b00eb0b41b202c0d05a7ea03d63c49e9ffcc1](https://github.com/magento/magento2/commit/1f7b00eb0b41b202c0d05a7ea03d63c49e9ffcc1)
 - [797ed7c5310e09de7c609e3d137a43ac76b4e557](https://github.com/magento/magento2/commit/797ed7c5310e09de7c609e3d137a43ac76b4e557)

The fix will be available with the upcoming 2.4.3 release.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
