### ISSUE TITLE
Downloadable Link Repository Returns Incorrect Download Links

### ISSUE THREAD

**Issue by nwcasebolt** [magento/magento2#31869]
### Preconditions (*)

1. Magento 2.3.3-p1
2. PHP 7.2.34-8+ubuntu16.04.1

### Steps to reproduce (*)
1. Create a Downloadable Product with a URL for the "File" setting. In my case, the entity_id of the new product is 4714, and the row_id is 4951.
2. Load the new product from the product repository and pass it to \Magento\Downloadable\Api\LinkRepositoryInterface::getLinksByProduct().

### Expected result (*)

1. I expect to receive an array of download links for product 4714 (the entity_id of the passed product)

### Actual result (*)

1. I receive an array of download links for product 4951 (the row_id of the passed product).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @nwcasebolt . Thank you for your report!

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
Everything works as expected.

**Steps to reproduce:**
1. Create a Downloadable Product with a URLs for the "File" setting. In my case, the entity_id of the new product is 2051

![2021-01-28_14-46](https://user-images.githubusercontent.com/51679138/106140931-16b71880-6178-11eb-9604-62cb8e97fc54.png)
2. Load the new product from the product repository and pass it to \Magento\Downloadable\Api\LinkRepositoryInterface::getLinksByProduct().

**Actual Result:** :heavy_check_mark: We received an array of download links for product 2051 (the row_id of the passed product).

![Screenshot from 2021-01-28 14-41-05](https://user-images.githubusercontent.com/51679138/106141063-48c87a80-6178-11eb-9487-251aa27164f8.png)
![2021-01-28_14-41](https://user-images.githubusercontent.com/51679138/106141068-4bc36b00-6178-11eb-9367-4e8574738166.png)
![2021-01-28_14-42](https://user-images.githubusercontent.com/51679138/106141076-4d8d2e80-6178-11eb-83ab-835fa534cf25.png)
![2021-01-28_14-43](https://user-images.githubusercontent.com/51679138/106141080-4ebe5b80-6178-11eb-95cd-39b2ac07809c.png)

Maybe we missed something?
@nwcasebolt Are you able to reproduce this bug on clean 2.4-develop?
Thanks!

**Comment by nwcasebolt** [comment]
Hi @engcom-Alfa. I would expect these results in a case where the entity_id and row_id are identical. Can you test this in a case where the entity_id and row_id are divergent? This is my use case.

If you still get good results, is there a possibility that there is a difference here between 2.3.3-p1 and 2.4? Thank you.

**Comment by nwcasebolt** [comment]
> Hi @engcom-Alfa. I would expect these results in a case where the entity_id and row_id are identical. Can you test this in a case where the entity_id and row_id are divergent? This is my use case.
> 
> If you still get good results, is there a possibility that there is a difference here between 2.3.3-p1 and 2.4? Thank you.

Any progress on this? I was just testing this functionality again and getting the same results.
