### ISSUE TITLE
USPS to Canada is not working

### ISSUE THREAD

**Issue by lookinglavish** [magento/magento2#3186]
When using a shipping address in Canada (USPS Priority Mail International), the result comes back with $0.00. However, if I switch to another international address (Italy), it works fine. 

Thanks!

**Comment by alena-marchenko** [comment]
Hi,

We've created MAGETWO-49093 internal ticket for solving this issue

**Comment by alena-marchenko** [comment]
We have resolved this issue and delivered fix for this.
