### ISSUE TITLE
Cart Item does not reflect the changes when the product get some changes

### ISSUE THREAD

**Issue by deepanshuyadav87** [magento/magento2#31874]
### Preconditions (*)

1.Magento 2.3.4

### Steps to reproduce (*)

1. Add a product to the cart
2. Change the same product price or any other product attribute from the admin panel

### Expected result (*)

1. Item in the cart should get the changes according to the product changes

### Actual result (*)

1. Item in the cart have values that were set before the product changes initially when the product was added to the cart.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajaykumar03** [comment]
Hi deepanshuyadav87
Thank you for your report.

@magento Please provide  me 2.4-develop instance to verify this issue.

**Comment by ajaykumar03** [comment]
@magento give me 2.4-develop instance

**Comment by ajaykumar03** [comment]
@deepanshuyadav87  I'm unable to reproduce the issue as provided steps by you. Kindly provide more details to reproduce this issue and confirm the issue is on 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @deepanshuyadav87. Thank you for your report.
Feel free to reopen the ticket once you confirm that issue reproduce on latest 2.4-develop instance
Thanks!!
