### ISSUE TITLE
Cart page subtotal shows wrong when we back from multishipping

### ISSUE THREAD

**Issue by sumitvgupta** [magento/magento2#31889]
### Preconditions (*)
1. Magento V2.4.1
1. PHP 7.3.24

### Steps to reproduce (*)
1. Add 2 or more items to the basket then go to the Multiple Addresses selection page
Like I have added 5 qty on the same product and selected the 1st address for 3 qty and 2nd address for 2 qty.
1. From the Address selection page I'm going to the next step of the shipping method selection.
1. Now go to the back on the cart page and check the summary subtotal and it shows the subtotal of 1st address and it's wrong.

### Expected result (*)
1. Need to show correct subtotal after come back from multi shipping

### Actual result (*)
1. It's showing the wrong subtotal on the cart page. The subtotal needs to calculate of Address 1 + Address 2 but it's only showing the Address 1 subtotal.
## 

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as a Reporter. This information will help during Confirmation and Issue triage processes.

- <x] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by sumitvgupta** [comment]
Issue Video: https://drive.google.com/file/d/15Z4zSqHJJ772Py6t75NNPQ36MLPt-Set/view

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40678` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
