### ISSUE TITLE
A logical and resource consumption issue in the \Magento\Ui\Component\Form\Element\Wysiwyg::__construct() method: the editorElement object in unnecessary set as property but in never used (and can not be used) outside the single method

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3188]
https://mage2.pro/t/389

**Comment by ktomk** [comment]
There is also the flaw that the [_constructor does real work_](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/) ([ctor src](https://github.com/magento/magento2/blob/c58d2d/app/code/Magento/Ui/Component/Form/Element/Wysiwyg.php#L25)).

The dependency injection layer is lacking a feature to provide all needed dependencies in this case -or- the type's design is flawed. Would be interesting to get some feedback about this from the developers, there are perhaps other places that are worth of a discussion, e.g. I ran over the case that I could have used the injection of a parameter from the registry which AFAIK is not supported by the DI layer as well (correct me if not :)).

**Comment by Mulderua** [comment]
app/code/Magento/Ui/Component/Form/Element/Wysiwyg.php is no longer exist.

**Comment by NadiyaS** [comment]
Hi @ktomk  ,

The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by ktomk** [comment]
@NadiyaS: Jiust FYI, some people might find it offensive to be greeted with macro texts when they took the time to visit and give feedback to an issue. Per notifications, duplicate positings do also arrive even if deleted later on the Github platform. No worries please.
