### ISSUE TITLE
Order currency is used instead of bas currency in the shipping label for form

### ISSUE THREAD

**Issue by yogesh-valiya** [magento/magento2#31891]
When the store has multiple currencies and order is placed in any other currency rather than the base currency then this issue happens. The shipping label form uses order currency amounts instead of base currency amounts.
I checked further how different shipping carriers (checked in DHL, UPS, and FedEx) handles submitted custom amount. All of them treats received a custom amount as a base amount. I have faced this issue on Magento version 2.3.4 and 2.4-develop.

Here is the case,

- My order was like below. Order is placed in USD and the base currency is AED.
<img src="https://i.imgur.com/3jMDQab.png">
 !3jMDQab.png|thumbnail! 

-  On the shipping label form "Customs Value" has a suffix of AED (base currency) but values filled in automatically are in USD
<img src="https://i.imgur.com/uyUV2gR.png">
 !uyUV2gR.png|thumbnail! 

- Hance shipping label has invalid values. (Label should have 113AED as shown in the first screenshot) 
<img src="https://i.imgur.com/WHIbjUT.png">
 !WHIbjUT.png|thumbnail! 

### Preconditions (*)
1. Magento 2.4-develop
1. Store should have more than one currency.
1. Need any online shipping method enabled like DHL, FedEx, UPS, or any other.

### Steps to reproduce (*)
1. Open the frontend and switch to any currency different currency than the base currency.
<img src="https://i.imgur.com/VBNvAFp.png">
1. Place an order with any online shipping carrier. (I used DHL)
1. Got to the order page and open the new shipment page.
1. Check the checkbox "Create Shipping Label" and then "Submit Shipment..." - [screenshot](https://i.imgur.com/70CGPHU.png)
<img src="https://i.imgur.com/Kb1AIWJ.png"]
1. The input field "Customs Value" has a suffix of base currency but all amounts shown are in the order currency instead of the base currency. 
[img src="https://i.imgur.com/Ie5BBOO.png">

### Expected result (*)
1. All amounts shown on the shipping label should be in the base currency.

### Actual result (*)
1. All amounts shown on the shipping label are in the order currency.

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [x] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by yvaliya** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40702` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by yvaliya** [comment]
@magento I am working on this
