### ISSUE TITLE
Navigation Menu Child opens in different location

### ISSUE THREAD

**Issue by tony-sar** [magento/magento2#31911]
Hello. 
I been developing my site using magento 2 ( CE.2.4). 
I have added Category and subcategories and the 4 level child subcategory opens in different location and is not accessible to mouse click .. 
![Screen Shot 2021-01-29 at 10 43 36 PM](https://user-images.githubusercontent.com/34463591/106367397-60d30200-6310-11eb-98a9-ff1fb8d4917d.jpg)

as you can see on screen shot . Accessories is a child of Overhead Stirrer and is opening on top . i have also added another child category to other categories and result is the same . this is untouched Luma template 
I have cleaned and flush cache and reindexed, also switched to Production mode thinking that might resolve the issue . 

Any suggestion ? 
Thanks.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @tony-sar thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
:heavy_check_mark: 4 level child subcategory could be opened
![Peek 2021-02-01 09-53](https://user-images.githubusercontent.com/51681379/106429876-bc69d080-6473-11eb-9179-a7a18e6f0593.gif)

If you'd like to update the issue, please reopen it.

**Comment by tony-sar** [comment]
Thanks. 
I have recently moved my Database from localhost to remote database server . everything that end seems to be working. however, in admin > catalog . i sorted the categories by dragging and dropping them in right order. current category structure is not the same in category selection in Add products section of magento .. select category shows the old structure , is this a issue ? 
Only option i see to reinstall magento again
