### ISSUE TITLE
can not save cms pages

### ISSUE THREAD

**Issue by ran2345** [magento/magento2#3192]
I get this error when trying to save cms pages

{i:0;s:227:"Warning: preg_match(): Compilation failed: range out of order in character class at offset 6 in /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Locale/Format.php on line 527";i:1;s:8368:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'preg_match(): C...', '/home/42690-336...', 527, Array)
#1 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(527): preg_match('/^[\xE2\x80\x8E--]{0,1}[...', '', Array)
#2 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/LocalizedToNormalized.php(100): Zend_Locale_Format::isNumber('', Array)
#3 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Stdlib/DateTime/Filter/Date.php(55): Zend_Filter_LocalizedToNormalized->filter('')
#4 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\Date->filter('')
#5 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(722): Zend_Filter->filter('')
#6 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(701): Zend_Filter_Input->_filterRule(Array)
#7 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(785): Zend_Filter_Input->_filter()
#8 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(381): Zend_Filter_Input->_process()
#9 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/PostDataProcessor.php(54): Zend_Filter_Input->getUnescaped()
#10 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/Save.php(47): Magento\Cms\Controller\Adminhtml\Page\PostDataProcessor->filter(Array)
#11 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php(24): Magento\Cms\Controller\Adminhtml\Page\Save->execute()
#12 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->execute()
#13 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#16 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent('dispatch', Array)
#17 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'adminAuthentica...')
#18 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#21 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'designLoader')
#22 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#23 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#25 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'adminMassaction...')
#26 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#29 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php(39): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#33 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#34 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#38 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#39 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#40 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#41 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#42 {main}";s:3:"url";s:114:"/admin/cms/page/save/key/a0b9c79185fa8307fa761c74be1d13e399a058f0bd99aaac8656e7cc685974c0/active_tab/main_section/";s:11:"script_name";s:10:"/index.php";}

I get the error even when i dont change nothing on the page just press "save page"

**Comment by palamar** [comment]
@ran2345
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
