### ISSUE TITLE
CAN NOT ACCESS OR PRINT SHIPPING LABEL

### ISSUE THREAD

**Issue by d-rowton** [magento/magento2#31927]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
Hello @d-rowton,
Please add proper issue steps, actual result, and expected result. I can't able to reproduce the issue without detailed information. 
Thanks.

**Comment by ajijshekh123** [comment]
Hello @d-rowton,
Is there any update?

**Comment by ajijshekh123** [comment]
Hello @d-rowton,
If you are facing this issue again you can reopen with proper steps, actual result, and expected result.
Thanks.
