### ISSUE TITLE
Magento2.4 Plugin installation issue

### ISSUE THREAD

**Issue by vipinrv** [magento/magento2#31928]
![Screenshot from 2021-02-02 09-23-04](https://user-images.githubusercontent.com/11312457/106550034-4da27b00-6538-11eb-9945-e326ab6622d5.png
php bin/magento module:enable Sparsh_EasyProductTabs : Comment did not run. Who to fix this

**Comment by engcom-Alfa** [comment]
Hi @vipinrv, thank you for your report.

The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
