### ISSUE TITLE
Configurable Product not showing in product page

### ISSUE THREAD

**Issue by o0mohd0o** [magento/magento2#31932]
I have an issue with Configurable product are not showing in product page

I had look to system.log

I found this error

main.CRITICAL: Class Magento\Swatches\ViewModel\Product\Renderer\Configurable does not exist [] []

Actually I went to config.php to check if there are extension disabled. 
'Magento_ConfigurableProduct' => 1,
'Magento_ConfigurableProductSales' => 1,
'Magento_InventoryConfigurableProduct' => 1,
'Magento_InventoryConfigurableProductAdminUi' => 1,
'Magento_InventoryConfigurableProductIndexer' => 1,
'Magento_CatalogRuleConfigurable' => 1,

Any suggestion to fix this issue?

I also have this error:

main.INFO: Reference to undeclared plugin with name 'ddg_customer_sendNewAccountEmail_disabler'. [] []

Regards,

**Comment by engcom-Delta** [comment]
Hi @itc4u thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develo seems like this related to your custom modules. I didn't find plugin with name 'ddg_customer_sendNewAccountEmail_disabler' in magento core files
**Result:**
:heavy_check_mark: Configurable product page is opened without error
![image](https://user-images.githubusercontent.com/51681379/106590695-0f1bb900-6556-11eb-8b31-4c5540a5acfd.png)

If you'd like to update the issue, please reopen it.
