### ISSUE TITLE
Graphql request placeOrder is pending but order is processed in admin

### ISSUE THREAD

**Issue by smileguitar** [magento/magento2#31949]
*It's only occurred for Bundle product. As the order is requested using the magento 2 grahql interface(placeOrder mutation), the expected result is that it should return order id or error message.*

### Preconditions (*)
* Magento 2.3.5 
### Steps to reproduce (*)
1. Call graphql create cart mutation
2. Call graphql add item to cart mutation (**bundle product**)
3. Call graphql add cart guest email on cart mutation
4. Call graphql add shipping address on cart mutation
5. Call graphql add billing address on cart mutation
6. Call graphql add shipping method on cart mutation
7. Call graphql add payment method on cart mutation
8. Call graphql place order mutation
### Expected result
* returns order id or error message
### Actual result
* it's pending and when i try again, i get 'Current user does not have an active cart'. but if i visit orders in admin page, i can see this order was placed.

**Comment by heerdt** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by smileguitar** [comment]
Hi @heerdt and @magento
I fixed it. it was not magento problem. It was Odoo connector problem.
