### ISSUE TITLE
No ACL access to Marketing » URL Rewrites

### ISSUE THREAD

**Issue by pivulic** [magento/magento2#3194]
## Problem

It's not possible to create a User Role that has access to:  Admin » Marketing » SEO & Search » URL Rewrites

See http://www.vaimo.com/snaps/pablo.ivulic/m2-no-url-rewrites-acl.png
## How to recreate
1. Navigate to: System » Permissions » User Roles » Add New Role
2. Try and give access to "URL Rewrites"
## Expected result

It should be possible to create a User Role and give access to URL Rewrites.

**Comment by antboiko** [comment]
Hi @pivulic , thanks for reporting this. Internal ticket MAGETWO-49769 was created.

Best regards,
Anton.

**Comment by vzabaznov** [comment]
Issue was fixed, @pivulic could you please check, if you think that issue still persist, please feel free to write here, or to open new issue
