### ISSUE TITLE
Customer Register validation stops new submission form after error

### ISSUE THREAD

**Issue by Krielkip** [magento/magento2#31943]
### Preconditions (*)
1. Use Clean Magento 2.4.1 installation

### Steps to reproduce (*)
1. Go to register page (customer/account/create/)
2. (OPTIONAL) Fill in all fields, but different passwords
3. Press on register
4. See error by validation
5. Try to fill in write
6. Send form again

### Expected result (*)
1. Possible to send the form

### Actual result (*)
1. Not possible to resend. Register button state disabled

Possible problem: `Magento_Customer/js/block-submit-on-send.js`
``` 
 dataForm.bind('invalid-form.validate', function () {
            $(this).find(':submit').prop('disabled', false);            
        });
```
is run before:
```
dataForm.submit(function () {
            $(this).find(':submit').attr('disabled', 'disabled');
        });
```
       

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by Krielkip** [comment]
I also tested it on http://devm2php74.tk/magento241/ (BBS Commerce example 2.4.1 store)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @Krielkip. Thank you for your report.
Not able to replicate the issue on latest 2.4-develop instance. It may be fixed
The related internal Jira ticket MC-38509 was closed as Fixed.
Related commits can be found by search [https://github.com/magento/magento2/search?q=MC-38509&type=commits](https://github.com/magento/magento2/search?q=MC-38509&type=commits)
You can refer issue #30513 for more clarification.
Thanks!!
