### ISSUE TITLE
Error on production deployment - "PHP Fatal error:  Cannot instantiate interface"

### ISSUE THREAD

**Issue by lilmuckers** [magento/magento2#3195]
Hi there

I have automated deployment of my magento 2 CE site using deploybot, and it's throwing the following error on the deployment:

 `PHP Fatal error:  Cannot instantiate interface: Magento\Framework\Indexer\ConfigInterface`

magento 2 is being deployed using git and composer - Where the only files in the git repo are the base stripped down directories:

```
app/design/<our themes>
app/code/<our modules>
.gitignore
composer.json
```

but _basically_ it's the following (this isn't exactly it, but i am able to recreate the bug by doing this):

``` bash
## Check out the repo
cd /var/www/releases/
git checkout <repo> 13245678
cd 13245678

##install the dependancies and config
composer install
ln -s /var/www/shared/env.php app/etc/env.php

##run magento deployment
php bin/magento deploy:mode:set production
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
```

It seems that the `setup:di:compile` command is always returning the fatal error.
It doesn't seem to effect the site once it goes live - but i'm worried that something is wrong that i'm not seeing.

What am i doing wrong in my procedure?

**Comment by eddielau** [comment]
@lilmuckers Do you have config.php in app/etc? From the example it looks like you did not install Magento correctly. Please use `php bin/magento setup:install ...`, then run `php bin/magento deploy:mode:set production`. Deploy mode set command should run code compilation and static content deployment for you.

**Comment by lilmuckers** [comment]
we don't have a config.php

So you're saying i shouldn't just swap in the env.php - but instead run the install command on deployment?

okay, i'll give that a try.

**Comment by maksek** [comment]
@lilmuckers, any follow up on this? Did you try?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
