### ISSUE TITLE
Email may not be sent if Magento has enabled asynchronous email sending on multiple websites

### ISSUE THREAD

**Issue by kimurabanyan** [magento/magento2#31950]
### Preconditions (*)

1. Magento 2.4-develop;
1. Magento Open Source 2.4.0-p1  without sample data is installed;
2. There are two websites, each with one Store View;

### Steps to reproduce (*)

For convenience, I define two websites as follows:

A: Default Website
B: non-Default Website

1. Set "Stores > Configuration > Sales > Sales Emails > General Settings > Ansynchronous sending" to "**Enable**".
2. On A, set "Stores > Configuration > Sales > Sales Emails > Order > Enabled" to "**No**".
3. On B, set "Stores > Configuration > Sales > Sales Emails > Order > Enabled" to "**Yes**".
4. Complete the order on B.

### Expected result (*)

1. Order confirmation email is sent.

### Actual result (*)

1. Order confirmation email is **not** sent.

### Additional Information

* If asynchronous email sending is disabled, no problem.
* Invoice, Shipment, and Credit Memo emails have similar issues. However, Order Comments, Invoice Comments, Shipment Comments, Credit Memo Commets emails are sent successfully.
* If place an order through the storefront then messages are sent

**Comment by kimurabanyan** [comment]
@magento give me 2.4-develop instance

**Comment by kimurabanyan** [comment]
@magento give me 2.4.0 instance

**Comment by kimurabanyan** [comment]
No emails are sent on Magento vanilla instance even if I enabled email sending in system settings. The reproduction procedure could not be confirmed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40950` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
