### ISSUE TITLE
Can't move the message queue inventory.reservations.updateSalabilityStatus from DB to RabbitMQ

### ISSUE THREAD

**Issue by debuggeryang** [magento/magento2#31959]
### Preconditions (*)

1. Magento 2.3.6 + MySQL
2. RabbitMQ 3.8

### Steps to reproduce (*)

1. Install and connect Magento to RabbitMQ, MariaDB
2. Move the inventory.reservations.updateSalabilityStatus message queue from the database to RabbitMQ by configuring it in the `app/env.php` file like the following:

```
...
'queue' => [
        'consumers_wait_for_messages' => 1,
        'amqp' => [
            'host' => 'rabbit',
            'port' => '5672',
            'user' => 'magento2',
            'password' => 'passw0rd',
            'virtualhost' => '/'
        ],
        'topics' => [
            'inventory.reservations.updateSalabilityStatus' => [
                'publisher' => 'amqp-magento'
            ]
        ],
        'config' => [
            'publishers' => [
                'inventory.reservations.updateSalabilityStatus' => [
                    'connections' => [
                        'amqp' => [
                            'name' => 'amqp',
                            'exchange' => 'magento',
                            'disabled' => false
                        ],
                        'db' => [
                            'name' => 'db',
                            'disabled' => true
                        ]
                    ]
                ]
            ]
        ],
        'consumers' => [
            'inventory.reservations.updateSalabilityStatus' => [
                'connection' => 'amqp'
            ]
        ]
    ],
...
```

3. run `bin/magento setup:upgrade` to update the change
4. run `bin/magento queue:consumers:list` to list all consumers

### Expected result (*)

1. All queues are listed no matter they are handled by database or RabbitMQ

```
product_action_attribute.update
product_action_attribute.website.update
exportProcessor
inventory.source.items.cleanup
inventory.mass.update
inventory.reservations.cleanup
inventory.reservations.update
codegeneratorProcessor
inventory.reservations.updateSalabilityStatus
async.operations.all
```

### Actual result (*)

1.  An **Undefined index** Notice shows up
![image](https://user-images.githubusercontent.com/48190672/106747439-0d4a1680-6678-11eb-8af6-e2c65ccaebe0.png)
2. More details from debugging: At line 55 in the `ConfigReaderPlugin.php` file, I can see that when the `config` object tried to get consumers, it could not get all required config data.
---https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/lib/internal/Magento/Framework/MessageQueue/Config/Consumer/ConfigReaderPlugin.php#L55

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jordanvector** [comment]
Same exact issue on 2.3.6 EE.  All consumers except inventory.reservations.updateSalabilityStatus can be converted to rabbitmq. Converting inventory.reservations.updateSalabilityStatus throws this error

**Comment by Nuranto** [comment]
If it can helps someone : 

I had the same issue. It appears that one of a third part queue was misconfigured (missing queue.xml). So when a queue is misconfigured, every consumers of every queues won't work anymore..

**Comment by kanevbg** [comment]
This is still valid issue in Magento 2.3.7-p3. Please re-open!

**Comment by amirmdp** [comment]
I am exactly facing the same Notice: Undefined index: name in /vendor/magento/framework-message-queue/Config/Consumer/ConfigReaderPlugin.php on line 56.
When I tried to list consumers for my Magento 2.4.2 env.php, I noticed as I disabled the consumers array, the command started working linsting my consumers for RabbitMQ, now they are listed in Rabbit MQ, yet I see no connection or  channels in my RabbitMQ admin panel.
The new configuration looks like this:

    'queue' => [
		'consumers_wait_for_messages' => 1,
        'amqp' => [
            'host' => 'RabbitMQ_Host',
            'port' => '5672',
            'user' => 'RMQUser',
            'password' => 'RMQ_passwort',
            'virtualhost' => '/',
            'ssl' => ''
        ],
		'topics' => [
            'product_action_attribute.update' => [
                'publisher' => 'amqp-magento'
            ]
        ],
        'config' => [
            'publishers' => [
                'product_action_attribute.update' => [
                    'connections' => [
                        'amqp' => [
                            'name' => 'amqp',
                            'exchange' => 'magento',
                            'disabled' => false
                        ],
                        'db' => [
                            'name' => 'db',
                            'disabled' => true
                        ]
                    ]
                ]
            ]
        ],
		
	// Cause of Notice:
		/*
        'consumers' => [
            'product_action_attribute.update'	=>	[
				'connection' => 'amqp'
			],
			'product_action_attribute.website.update'	=>	[
					'connection' => 'amqp'
				],
			'exportProcessor'	=>	[
					'connection' => 'amqp'
				],
			'inventory.source.items.cleanup'	=>	[
					'connection' => 'amqp'
				],
			'inventory.mass.update'	=>	[
					'connection' => 'amqp'
				],
			'inventory.reservations.cleanup'	=>	[
					'connection' => 'amqp'
				],
			'inventory.reservations.update'	=>	[
					'connection' => 'amqp'
				],
			'codegeneratorProcessor'	=>	[
					'connection' => 'amqp'
				],
			'media.storage.catalog.image.resize'	=>	[
					'connection' => 'amqp'
				],
			'inventory.reservations.updateSalabilityStatus'	=>	[
					'connection' => 'amqp'
				],
			'inventory.indexer.sourceItem'	=>	[
					'connection' => 'amqp'
				],
			'inventory.indexer.stock'	=>	[
					'connection' => 'amqp'
				],
			'media.content.synchronization'	=>	[
					'connection' => 'amqp'
				],
			'media.gallery.renditions.update'	=>	[
					'connection' => 'amqp'
				],
			'media.gallery.synchronization'	=>	[
					'connection' => 'amqp'
				],
			'async.operations.all'	=>	[
					'connection' => 'amqp'
				],
			'rmq_order_consumer'	=>	[ // custom consumer
					'connection' => 'amqp'
				],
			'rmq_invoice_consumer'	=>	[ // custom consumer
					'connection' => 'amqp'
				]
			]
		*/
		
	// End Cause of Notice
	],
    'cron_consumers_runner' => [
        'cron_run' => false,
        'max_messages' => 20000,
        'consumers' => [
            'product_action_attribute.update',
            'product_action_attribute.website.update',
            'exportProcessor',
            'inventory.source.items.cleanup',
            'inventory.mass.update',
            'inventory.reservations.cleanup',
            'inventory.reservations.update',
            'quoteItemCleaner',
            'gaiterjones_product_save',
	'rmq_invoice_consumer', // custom consumer
			'rmq_order_consumer', // custom consumer
            'async.operations.all'
        ]
    ],
    'crypt' => [
        'key' => '069837d4c00945219c15378cc17a6547'
    ],
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => 'localhost',
                'dbname' => 'DB_name',
                'username' => 'db_user',
                'password' => 'db_passwort',
                'active' => '1',
                'initStatements' => 'SET NAMES utf8;'
            ]
        ]
    ],
    'resource' => [
        'default_setup' => [
            'connection' => 'default'
        ]
    ],
    'x-frame-options' => 'SAMEORIGIN',
    'MAGE_MODE' => 'developer',
    'session' => [
        'save' => 'files'
    ],
    'cache' => [
        'frontend' => [
            'default' => [
                'id_prefix' => '680_'
            ],
            'page_cache' => [
                'id_prefix' => '680_'
            ]
        ]
    ],
    'lock' => [
        'provider' => 'db',
        'config' => [
            'prefix' => ''
        ]
    ],
    'cache_types' => [
        'config' => 1,
        'layout' => 1,
        'block_html' => 1,
        'collections' => 1,
        'reflection' => 1,
        'db_ddl' => 1,
        'compiled_config' => 1,
        'eav' => 1,
        'customer_notification' => 1,
        'config_integration' => 1,
        'config_integration_api' => 1,
        'google_product' => 1,
        'full_page' => 1,
        'config_webservice' => 1,
        'translate' => 1,
        'vertex' => 1
    ],
    'downloadable_domains' => [
        'my.server.site'
    ],
    'install' => [
        'date' => 'Fri, 18 Oct 2019 14:29:33 +0000'
    ],
    'http_cache_hosts' => [
        [
            'host' => '127.0.0.1',
            'port' => '6081'
        ]
    ]

**Comment by edward-simpson** [comment]
@amirmdp you probably want to retract your crypt key...
