### ISSUE TITLE
URGENT: Expiring Digital Certificates for UPS® Developer Kit URL

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#31966]
### Preconditions (*)

1.Magento ver - 2.3.5-p2
2.Production Environment

### Steps to reproduce (*)

1. Received an email for Module UPS that Digital Certificates for UPS Developer Kit URL will expire.
2.This can break the API call of UPS
3. The current Comodo Sectigo server certificate used for UPS Developer Kit transactions submitted to https://onlinetools.ups.com will expire on February 25, 2021.
Beginning February 15, 2021, UPS will update the certificate to the current Comodo Sectigo at which time customers can download the new certificate. The migration will be completed February 19, 2021.
After February 19, 2021 if your certificate has not been updated your UPS Developer Kit API transactions will fail.

### Expected result (*)

1. What need to do to resolve this issue so that UPS API call will not break.
2. Do this mandatory to update for Magento2

### Actual result (*)

1. UPS API should not be break after 19 Feb.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @thinksys-dev 

Thank you for your report.

Can you please clarify how this issue is connected to Magento core?

Thank you in Advance
