### ISSUE TITLE
CAPTCHA not showing on storefront Magento 2.0.2

### ISSUE THREAD

**Issue by ifekaj** [magento/magento2#3196]
CAPTCHA field and image doesn't show on storefront after I enable them in admin. If I go to, for example, "Forgot password" page it just shows the email field. After I submit the form I get "Incorrect CAPTCHA" message. Please note that this happens on admin CAPTCHA as well. I also had this problem on Magento 2.0.0.
PHP version is 5.6.17, Apache 2.4.6 on Centos 7.2

**Comment by rpeddinti** [comment]
It is working for me. tested now

**Comment by vrann** [comment]
@ifekaj Thanks for reporting. Can you please try it on latest release?

**Comment by AirmanAJK** [comment]
In 2.0.4, when Captcha is enabled under customer configuration, the login page (among others) has window.checkout as undefined. When captcha is disabled, windows.checkout exists and no console errors occur.

<img width="661" alt="jsconsoleerr" src="https://cloud.githubusercontent.com/assets/18410935/14448399/10131476-002e-11e6-8a0d-8077a3d72214.png">

**Comment by oserediuk** [comment]
Hello! If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
