### ISSUE TITLE
LayeredNavigation/templates/layer/filter.phtml php format change breaks frontend 

### ISSUE THREAD

**Issue by BB-000** [magento/magento2#31971]
The updated version of this file breaks the frontend a bit, the line breaks that were added mean that blank space is output after the 'count'. This causes bad looking frontend (empty space and orphan brackets wrapping onto the next line). Reverting to the version without line breaks after '$filterItem->getCount()' fixes it

**Comment by mrtuvn** [comment]
Can you describe what expect and actually results that you want to see ?

**Comment by engcom-Delta** [comment]
Hi @BB-000 thank you for your report. 
Please update issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and add more details how to reproduce issue, additional screenshots will be useful.

**Comment by krishprakash** [comment]
Hi @BB-000. Feel free to reopen the issue once you update all the details as per issue reporting guidelines.
Thanks!!
