### ISSUE TITLE
Cutom column filter which is added in Sales invoice grid in Magento 2.4 admin is not working

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#31975]
### Preconditions (*)
1. Magento CE 2.4
2. PHP 7.4

### Steps to reproduce (*)
1.  Create any custom table with a column having Magento invoice increment id and other columns for example ERP invoice number
2. Add ERP invoice number column in sales invoice grid using ui component <Namespace>\<Modulename>\view\adminhtml\ui_component\sales_order_invoice_grid.xml
3. Join the custom table with sales invoice grid collection by overriding the core Magento class Magento\Sales\Model\ResourceModel\Order\Invoice\Grid\Collection to filter custom column ERP invoice number in sales invoice grid

### Expected result (*)
1. Custom column ERP invoice number filter should work

### Actual result (*)
1. Custom column ERP invoice number filter is not working

**Note:**
The same code is working in Magento 2.3.x. We observed that the class Magento\Sales\Model\ResourceModel\Order\Invoice\Grid\Collection removed from Magento 2.4.x.

Please suggest a way for a custom column filter in the sales invoice grid in Magento 2.4.x.

**Comment by frank-bokdam** [comment]
The class has been replaced by a Virtual type: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/etc/di.xml#L841

You can start using this virtualType injecting the `searchResults` class in your constructor and replacing it with the Virtualtype.

**Comment by i95devdivya** [comment]
@frank-bokdam Thank you for your response.

I added virtualType as below in our module <Namespace>/<Modulename>/
etc/di.xml. But it's not working.

<virtualType name="Magento\Sales\Model\ResourceModel\Order\Invoice\Grid\Collection">
        <arguments>
            <argument name="joins" xsi:type="array">
                <item name="custom_table" xsi:type="array">
                    <item name="table" xsi:type="string">custom_table</item>
                    <item name="origin_column" xsi:type="string">increment_id</item>
                    <item name="target_column" xsi:type="string">source_invoice_id</item>
                </item>
            </argument>
            <argument name="columns" xsi:type="array">
                <item name="erp_invoice_id" xsi:type="string">custom_table.erp_invoice_id</item>
            </argument>
        </arguments>
    </virtualType>

**Comment by frank-bokdam** [comment]
What I have done to make it work is update the class that is calling the invalid InvoiceCollection, replace `Invoice\Grid\Collection` with `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult`.

The prevent needing to update the rest of the class you can alias it with the old classname / alias you were using.

After that you have to add an entry to di.xml as follows:
```
    <type name="Vendor\AdditionalGridColumns\Plugin\AddColumnsGridCollection">
        <arguments>
            <argument name="invoiceCollection" xsi:type="object">Magento\Sales\Model\ResourceModel\Order\Invoice\Grid\Collection</argument>
        </arguments>
    </type>
```
To replace the constructor class in the (in my case) plugin class with the correct Virtual type.

so you don't need to create a new virtualType, since it is already existent.
