### ISSUE TITLE
Cannot Export/Import max_characters attribute within Custom Options

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3197]
Hi

While Exporting products **custom_options** column with in the export file doesn't contain **max_characters** attribute for custom options. Also the Import module doesn't recognize **max_character** key within the custom options  and import product data

**Comment by katmoon** [comment]
Hi @rohit47rohit ,

Thanks for reporting the issue!
Internal ticket `MAGETWO-48647` has been created.

Thanks,
Kateryna.

**Comment by vzabaznov** [comment]
@rohit47rohit thank you for reporting, issue was fixed and delivered, please feel free to write here or to open new one if you tnihk that issue wasn't fixed
