### ISSUE TITLE
Cannot save product in store view scope without Magento_Catalog::edit_product_design

### ISSUE THREAD

**Issue by SukimaSwitch** [magento/magento2#31973]
**Preconditions**

Magento 2.4-develop;
Magento Open Source 2.3.5-p2;

**Steps to reproduce**
1. Create a simple product;
1. Use an administrator account, set the "Schedule Design Update" attribute under the store view scope (***Default Store View*** for ex.)  for any product, and then save changes;
![image](https://user-images.githubusercontent.com/48080750/106994514-e561cc80-67b7-11eb-99f6-76a27306a66b.png)
1. Go to Admin -> System -> Permissions -> User Roles and create a new role with the entire `Catalog` tree selected, except for `Catalog > Inventory > Products > Edit Product Design`;
![Screenshot from 2021-02-05 10-47-15](https://user-images.githubusercontent.com/51679138/107010859-914aee00-679f-11eb-8d86-0c97ed4df8bf.png)
1. Create a user assigned to this new role and log into the backend with it;
1. Edit the same product, change the product name and save changes under the store view scope (***Default Store View***);

**Expected result**

(/) The changes can be saved successfully.

**Actual result**

(x) Raise an error and failed to save.
Error message: Not allowed to edit the product's design attributes
![image](https://user-images.githubusercontent.com/48080750/106995110-23abbb80-67b9-11eb-8069-158f98958fef.png)

In the ***exception.log*** file:
![Screenshot from 2021-02-05 11-10-44](https://user-images.githubusercontent.com/51679138/107013420-fa803080-67a2-11eb-88c3-f387ccb1e941.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40777` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kassner** [comment]
Likely related to the fix in #28106
