### ISSUE TITLE
Braintree PayPal not working Magento 2.3.5-p1 enterprise edition

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#31982]
### Preconditions (*)

1. Magento 2.3.5-p1
2. PHP 7.2

### Steps to reproduce (*)

1. Configure the Braintree PayPal and Braintree Credit card
2. Add to cart item and checkout
3. Choose Braintree PayPal Option and click on Pay with PayPal
4. PayPal window is opened and closed immediately with Console error

https://api.sandbox.braintreegateway.com/merchants/p7hk7jx76tsyf9ht/client_api/v1/paypal_hermes/setup_billing_agreement 422

### Expected result (*)

1. It should open the paypal window with paypal checkout option
2. I should place order using paypal braintree

### Actual result (*)

1. getting console error when click on Pay with PayPal button
2. 
checkout.min.js:2 ppxo_unhandled_error {stack: "Error: PayPal payment options are invalid.↵    at …w.paypalobjects.com/api/checkout.min.js:2:106714)", errtype: "[object Error]", timestamp: 1612550211225, windowID: "6b3dd1764f", pageID: "64dd225c1e", …}

checkout.min.js:2 Uncaught Error: PayPal payment options are invalid.
    at Object.w.<computed> [as postrobot_message_response] (checkout.min.js:2)
    at L (checkout.min.js:2)
    at E (checkout.min.js:2)

Please check the screenshot
![m235-1](https://user-images.githubusercontent.com/16815711/107075221-d575d700-680f-11eb-85da-855e716b7e6f.png)
![m235-2](https://user-images.githubusercontent.com/16815711/107075233-d9a1f480-680f-11eb-8fbc-a474dd7752bc.png)
![m235-3](https://user-images.githubusercontent.com/16815711/107075257-e292c600-680f-11eb-886d-1886d99a90ba.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @jigar48  thank you for your report. I checked issue with PayPal Express Checkout and PayPal Payflow Pro payment methods and it is not reproducible on clean magento 2.4-develop
Starting from `2.4.0` release, code related to this payment was removed from Magento code-base:
[Magento Open Source 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html)
> The core Braintree module has been removed from the code base. The Braintree Payments module now provides the same feature set. See [Braintree Payments](https://marketplace.magento.com/paypal-module-braintree.html?_ga=2.190658731.163879255.1612162480-1157872356.1605459366).

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

If you'd like to update the issue, please reopen it.
