### ISSUE TITLE
How to get access to magento commerce/enterprise github?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31980]
### Summary (*)

I created an issue which is for magento 2 enterprise, but it got moved to the enterprise repository,
and I received the info that I don't have access to it.

How can I get access to the enterprise magento 2 github?

### Examples (*)

-

**Comment by mrtuvn** [comment]
It's private repo you must have authorized/invited to access it

**Comment by krishprakash** [comment]
Hi @Eddcapone. It is private repository so you need to get authorization from community team.
Thanks!!

**Comment by Eddcapone** [comment]
How do I get autorization/invitation?
