### ISSUE TITLE
Magento 2 production mode problems

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#3198]
Hi,
I tried to search deeper in code generation and saw some strange Magento behavior.
Firstly I used magento-from-package installation. I change Mage Mode to production via command `bin/magento deply:mode:set production`
For code generation, Magento used `setup:di:compile-multi-tenant` commands.
After that I used to debug Magento\Framework\App\ObjectManagerFactory::create method, and found strangeness:
Firstly, on line 120 
`$definitions = $definitionFactory->createClassDefinition($deploymentConfig->get('definitions'))`
Mangento added \Magento\Framework\Code\Generator\Autoloader to autoload chain and return "Runtime" class definitions. Reason for this behavior is null value from  `$deploymentConfig->get('definitions')`
Unfortunately, I found anything in code and in documentation about 'definitions' argument in deployment config. In Runtime class devdocs I found 'Should be used only in dev mode.', so I suppose that is strange behavior in development mode.
Second point that,  `setup:di:compile-multi-tenant` created only var/di/plugin.ser and var/di/relations.ser.
As I understood, Magento select between Developer and Compiled states depend on var/di/global.ser file exists.
So, ObjectManager created with Developer factory and configs. 
After that I had flushed cache and used `setup:di:compile` command. It generated code and created var/di/global.ser file.
After this, Magento started to use Compiled factory and configs in ObjectManager, but 
`$definitions = $definitionFactory->createClassDefinition($deploymentConfig->get('definitions'))`
still return "Runtime" class definitions, and \Magento\Framework\Code\Generator\Autoloader also add in autoload chain.
I also installed Magento 2 from git and saw the same behavior. One difference that after 
`bin/magento deply:mode:set production` Magento used `setup:di:compile` for code generation.

**Comment by pynej** [comment]
Similar issue:
When I do a `magento deploy:mode:set production` or `setup:static-content:deploy`  my precompiled files are reset to this:

```
ls var/di
plugins.ser relations.ser
```

But if I do a `setup:di:compile` it makes me delete those and ends up only having this:

```
ls var/di
adminhtml.ser   crontab.ser frontend.ser    global.ser  webapi_rest.ser webapi_soap.ser
```

I'm not exactly sure what the optimal setup is, but it's inconsistent based on the last command i run.

**Comment by veloraven** [comment]
@swnsma is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
