### ISSUE TITLE
Header text for edit pages in admin area is not working

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#3199]
For example, I can't see header text 
`("Edit Page '%1'")`
for Edit CMS page (It must be in `<h3>` tag).
In the file:
/app/code/Magento/Cms/Block/Adminhtml/Page/Edit.php
function "getHeaderText" does't run. 

Magento 2.0.1 + Sample data

**Comment by andimov** [comment]
@sergei-sss 
Thanks for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
