### ISSUE TITLE
Images are not getting loaded if you change media base url

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31993]
### Preconditions (*)

I have two projects:

- relaunch.company.de
- redesign.company.de  (clone from relaunch.company.de)

**Note**: The base url of both projects is set to their `pub` directory.

I want to setup `redesign.company.de` to make it load images from `relaunch.company.de` so that I don't always have to upload the media to both projects.

So In `redesign.company.de` I added the URL `https://relaunch.company.de/media/` to 

**Stores -> Settings: Configuration -> General -> Base Url's -> Base URL for User Media Files**

and to 

**Stores -> Settings: Configuration -> General -> Base Url's (Secure) -> Base URL for User Media Files**

Then I flushed the cache.

But there are almost no images loaded in `redesign.company.de`

So I compared the same product on both servers and inspected the image urls.

On relaunch.company.de I get:
    
    https://relaunch.company.de/media/catalog/product/cache/1d080bca42fb631e749cc3891d555069/h/a/handschuh-pu-feinstrick-6618.jpg

and on redesign.company.de I get:

    https://relaunch.company.de/media/catalog/product/cache/183b11492b2e7b20f5c77f31599df17c/h/a/handschuh-pu-feinstrick_6618.jpg

As you can see the cache keys are different.

I also cant upload new images, it just looks like this:

[![enter image description here][1]][1]

and the images does not get loaded in the frontend either.

  [1]: https://i.stack.imgur.com/BZc0F.png
  
### Steps to reproduce (*)

see above

### Expected result (*)

-

### Actual result (*)

-

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Seem related with this https://github.com/magento/magento2/pull/31817#issuecomment-766558399 by @ihor-sviziev

**Comment by engcom-Alfa** [comment]
Hi @Eddcapone . 
We are not able to reproduce the described problem. Everything works properly.
The issue may be related to incorrect environment configuration.
Could you take a look at issue #31817?
Thanks!

**Comment by Eddcapone** [comment]
I have this .htaccess in `pub/media` on both servers:

```
Options -Indexes

<IfModule mod_php5.c>
php_flag engine 0
</IfModule>

<IfModule mod_php7.c>
php_flag engine 0
</IfModule>

AddHandler cgi-script .php .pl .py .jsp .asp .htm .shtml .sh .cgi
Options -ExecCGI

<FilesMatch ".+\.(ph(p[3457]?|t|tml)|[aj]sp|p[ly]|sh|cgi|shtml?|html?)$">
SetHandler default-handler
</FilesMatch>

<IfModule mod_rewrite.c>

############################################
## enable rewrites

    Options +FollowSymLinks
    RewriteEngine on

    ## you can put here your pub/media folder path relative to web root
    #RewriteBase /magento/pub/media/

############################################
## never rewrite for existing files
    RewriteCond %{REQUEST_FILENAME} !-f

############################################
## rewrite everything else to get.php

    RewriteRule .* ../get.php [L]
</IfModule>

############################################
## setting MIME types

# JavaScript
AddType application/javascript js jsonp
AddType application/json json

# CSS
AddType text/css css

# Images and icons
AddType image/x-icon ico
AddType image/gif gif
AddType image/png png
AddType image/jpeg jpg
AddType image/jpeg jpeg

# SVG
AddType image/svg+xml svg

# Fonts
AddType application/vnd.ms-fontobject eot
AddType application/x-font-ttf ttf
AddType application/x-font-otf otf
AddType application/x-font-woff woff
AddType application/font-woff2 woff2

# Flash
AddType application/x-shockwave-flash swf

# Archives and exports
AddType application/zip gzip
AddType application/x-gzip gz gzip
AddType application/x-bzip2 bz2
AddType text/csv csv
AddType application/xml xml

<IfModule mod_headers.c>

    <FilesMatch .*\.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$>
        Header append Cache-Control public
    </FilesMatch>

    <FilesMatch .*\.(zip|gz|gzip|bz2|csv|xml)$>
        Header append Cache-Control no-store
    </FilesMatch>

</IfModule>

<IfModule mod_expires.c>

############################################
## Add default Expires header
## http://developer.yahoo.com/performance/rules.html#expires

    ExpiresActive On

    # Data
    <FilesMatch \.(zip|gz|gzip|bz2|csv|xml)$>
        ExpiresDefault "access plus 0 seconds"
    </FilesMatch>
    ExpiresByType text/xml "access plus 0 seconds"
    ExpiresByType text/csv "access plus 0 seconds"
    ExpiresByType application/json "access plus 0 seconds"
    ExpiresByType application/zip "access plus 0 seconds"
    ExpiresByType application/x-gzip "access plus 0 seconds"
    ExpiresByType application/x-bzip2 "access plus 0 seconds"

    # CSS, JavaScript
    <FilesMatch \.(css|js)$>
        ExpiresDefault "access plus 1 year"
    </FilesMatch>
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"

    # Favicon, images, flash
    <FilesMatch \.(ico|gif|png|jpg|jpeg|swf|svg)$>
        ExpiresDefault "access plus 1 year"
    </FilesMatch>
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"

    # Fonts
    <FilesMatch \.(eot|ttf|otf|svg|woff|woff2)$>
        ExpiresDefault "access plus 1 year"
    </FilesMatch>
    ExpiresByType application/vnd.ms-fontobject "access plus 1 year"
    ExpiresByType application/x-font-ttf "access plus 1 year"
    ExpiresByType application/x-font-otf "access plus 1 year"
    ExpiresByType application/x-font-woff "access plus 1 year"
    ExpiresByType application/font-woff2 "access plus 1 year"

</IfModule>

```

I compared it with a fresh magento and they are identical.

**Comment by Eddcapone** [comment]
@engcom-Alfa Did you tested with product images? The problem only occurs with cached images.

**Comment by hostep** [comment]
@Eddcapone: make sure the contents of the `etc/view.xml` file of your custom theme between the two instances has the exact same `<media>` node. I seem to remember that part of the contents of that file determines the hash that is calculated for resized/cached images.

If this doesn't help, you could try to debug [the `miscParams` data](https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/MediaStorage/Service/ImageResize.php#L304) which get set between your two instances, maybe that helps in figuring out why the hashes are different. Executing `bin/magento catalog:images:resize` should give you a way to start debugging this I think.

**Comment by pmonosolo** [comment]
> @engcom-Alfa Did you tested with product images? The problem only occurs with cached images.

Have you figured this issue out? I'm getting a similar issue - cached image on a Amasty XSearch plugin sometimes generate, sometimes not.
