### ISSUE TITLE
Schedule Design Update when edit product in backend seem not set properly

### ISSUE THREAD

**Issue by engcom-Kilo** [magento/magento2#32007]
When edit product owner have able to set "Schedule Design Update"
Choose date applied, which theme will update, and page layout. But after set page layout to another value (example: 3 columns)
save and clear cache, Back to frontend and view exactly product edited before
View page source and see body class in DOM
Seem page layout not actually update. Owner will expected page layout change exactly like backend config but it's doesnt work
If we set in config it's should have highest priority or update last

https://docs.magento.com/user-guide/catalog/product-scheduled-design-update.html

### Preconditions (*)
1. Magento 2.4-develop
1. Luma theme (in my scenario) Blank will have same behavior

### Steps to reproduce (*)
1. Go to admin
1. Create new product or edit exists one
1. Go to Schedule Design Update
1. Set valid date for make sure update will be applied
1. Choose theme (can set current theme actived)
1. Choose page layout
1. Clear cache
1. Go to frontend and view details of product edit previously
1. Inspect dom in browser and view body class
### Expected result (*)
1. Body class use page-layout-3columns

### Actual result (*)
1. Body class still show page-layout-1column

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40811` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
