### ISSUE TITLE
DB rollback didn't complete

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#3200]
I tried to upgrade from 2.0.0 to 2.0.1 and it didn't worked. Then I tried to rollback the DB from a backup I did while trying to upgrade and the site seems to be working now but I keep seeing 

![screenshot - 01292016 - 10 53 46 am](https://cloud.githubusercontent.com/assets/3997682/12677282/9a4813b8-c676-11e5-9f17-106a7f0026ed.png)

**Comment by mazhalai** [comment]
Anything in `var/system.log`?

**Comment by miguelbalparda** [comment]
No, nothing useful in the system.log.
I found this from that date in the exception.log

> [2016-01-22 13:55:27] main.CRITICAL: exception 'InvalidArgumentException' with message 'Constant name is expected.' in /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Data/Argument/Interpreter/Constant.php:23
> Stack trace:
> #0 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\Data\Argument\Interpreter\Constant->evaluate(Array)
> #1 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php(103): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
> #2 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Config/Reader/Filesystem.php(168): Magento\Framework\ObjectManager\Config\Mapper\Dom->convert(Object(DOMDocument))
> #3 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Config/Reader/Filesystem.php(127): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator))
> #4 /chroot/home/magento1/magento2-demo.nexcess.net/html/var/generation/Magento/Framework/ObjectManager/Config/Reader/Dom/Proxy.php(95): Magento\Framework\Config\Reader\Filesystem->read('global')
> #5 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Interception/PluginList/PluginList.php(281): Magento\Framework\ObjectManager\Config\Reader\Dom\Proxy->read('global')
> #6 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/Interception/PluginList/PluginList.php(249): Magento\Framework\Interception\PluginList\PluginList->_loadScopedData()
> #7 /chroot/home/magento1/magento2-demo.nexcess.net/html/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(217): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\Framewo...', 'setHttpResponse...')
> #8 /chroot/home/magento1/magento2-demo.nexcess.net/html/pub/errors/processor.php(193): Magento\Framework\App\Response\Http\Interceptor->setHttpResponseCode(503)
> #9 /chroot/home/magento1/magento2-demo.nexcess.net/html/pub/errors/503.php(11): Magento\Framework\Error\Processor->process503()
> #10 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/App/Http.php(208): require('/chroot/home/ma...')
> #11 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/App/Http.php(137): Magento\Framework\App\Http->handleBootstrapErrors(Object(Magento\Framework\App\Bootstrap), Object(Exception))
> #12 /chroot/home/magento1/magento2-demo.nexcess.net/html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception))
> #13 /chroot/home/magento1/magento2-demo.nexcess.net/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> #14 {main} [] []

**Comment by mazhalai** [comment]
Thank you. We created MAGETWO-48564 to investigate and fix.

**Comment by miguelbalparda** [comment]
Thank you. To add some more info, the upgrade failed because of the missing .gitignore files.

**Comment by mazhalai** [comment]
The missing .gitignore files issue has been addressed [here](http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html) and [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/gitignore.html).

**Comment by OLTC-fperrin** [comment]
@miguelbalparda Hi, I posted about the missing .gitignore files [here](https://github.com/magento/magento2/issues/3056) which has been addressed in the new patch has mentioned by @mazhalai 

In the previous post I briefly mentioned about the rollback failing and didn't follow up; I had the exact same issue as yours, everything rolled back but whenever I accessed the setup page again I was redirected the the update/index.php at the 4th step with the console log showing something similar to what you have.

To unstuck the setup wizard I removed the `.update_in_progress.flag` file from the `var` directory of the Magento install (I also removed the .maintenance.flag), Everything went back to normal after that.

Since then I've been able to run the latest patch (2.0.2) from the setup wizard and using composer.

**Comment by miguelbalparda** [comment]
@fperrin87 I don't see that file inside var. @mazhalai are you aware of any other flags I can remove to update to 2.0.2 in this scenario?

**Comment by miguelbalparda** [comment]
I take that back, I just found the file in question. After removing the file I was able to see the update screen again.

**Comment by mazhalai** [comment]
@miguelbalparda We have merged a fix in the develop branch, hence closing this ticket. Please create a new ticket if issues still arise.
