### ISSUE TITLE
How to get invitation/authorisation for Enterprise repository on github?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32001]
### Summary (*)

I am using Magento 2.4.1 Enterprise, there are some issues which do not exist in open source magento, for example page builder related issues. 

I already asked the question "[How to get access to magento commerce/enterprise github?](https://github.com/magento/magento2/issues/31980)" but the question was closed and I only got the message, that I need to get invited and authorized, but no one could answer me, how I can request an invitation/authorisation.

### Examples (*)

-
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
github is not active than slack channel in my opinion . You should ask for invite in there could help! I'm not sure 
I'm not in the part of that private repo
Go here https://magentocommeng.slack.com

**Comment by sidolov** [comment]
@Eddcapone please, contact Magento Community Engineering team (engcom@adobe.com) with your request. I'm closing the issue since it's not suitable for bug tracker. For further questions please, use Magento forums.

**Comment by Eddcapone** [comment]
It is not just a "bug tracker" it is an issue tracker and I posted under "Developer Experience issues". But thx
