### ISSUE TITLE
Mark Cron, Csp, Customer and Deploy interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32016]
The following interfaces should be marked as API in api-changes-develop branch

1. app/code/Magento/Cron/Model/DeadlockRetrierInterface.php
1. app/code/Magento/Csp/Api/CspAwareActionInterface.php
1. app/code/Magento/Csp/Api/CspRendererInterface.php
1. app/code/Magento/Csp/Api/Data/ModeConfiguredInterface.php
1. app/code/Magento/Csp/Api/Data/PolicyInterface.php
1. app/code/Magento/Csp/Api/InlineUtilInterface.php
1. app/code/Magento/Csp/Api/ModeConfigManagerInterface.php
1. app/code/Magento/Csp/Api/PolicyCollectorInterface.php
1. app/code/Magento/Csp/Api/PolicyRendererInterface.php
1. app/code/Magento/Csp/Model/Collector/Config/PolicyReaderInterface.php
1. app/code/Magento/Csp/Model/Collector/MergerInterface.php
1. app/code/Magento/Csp/Model/Policy/SimplePolicyInterface.php
1. app/code/Magento/Customer/Api/AccountDelegationInterface.php
1. app/code/Magento/Customer/Api/SessionCleanerInterface.php
1. app/code/Magento/Customer/Block/Address/Renderer/RendererInterface.php
1. app/code/Magento/Customer/Controller/AccountInterface.php
1. app/code/Magento/Customer/CustomerData/JsLayoutDataProviderPoolInterface.php
1. app/code/Magento/Customer/CustomerData/SectionPoolInterface.php
1. app/code/Magento/Customer/Model/Customer/Attribute/Source/GroupSourceLoggedInOnlyInterface.php
1. app/code/Magento/Deploy/Collector/CollectorInterface.php
1. app/code/Magento/Deploy/Console/Command/App/SensitiveConfigSet/CollectorInterface.php
1. app/code/Magento/Deploy/Package/BundleInterface.php
1. app/code/Magento/Deploy/Package/Processor/ProcessorInterface.php
1. app/code/Magento/Deploy/Source/SourceInterface.php
1. app/code/Magento/Deploy/Strategy/StrategyInterface.php

**Comment by vlmed** [comment]
@magento I am working on this
