### ISSUE TITLE
Mark GraphQl, ImportExport, Indexer, Integration and LoginAsCustomer interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32018]
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/GraphQl/Controller/HttpHeaderProcessorInterface.php
1. app/code/Magento/GraphQl/Controller/HttpRequestValidatorInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextParametersInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextParametersProcessorInterface.php
1. app/code/Magento/ImportExport/Api/Data/ExtendedExportInfoInterface.php
1. app/code/Magento/ImportExport/Model/Report/ReportProcessorInterface.php
1. app/code/Magento/Indexer/Model/ModeSwitcherInterface.php
1. app/code/Magento/Indexer/Model/Source/DataInterface.php
1. app/code/Magento/Integration/Model/Oauth/Token/RequestLog/ReaderInterface.php
1. app/code/Magento/Integration/Model/Oauth/Token/RequestLog/WriterInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/Data/IsLoginAsCustomerEnabledForCustomerResultInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/GetLoggedAsCustomerAdminIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/GetLoggedAsCustomerCustomerIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/IsLoginAsCustomerEnabledForCustomerInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/SetLoggedAsCustomerAdminIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/SetLoggedAsCustomerCustomerIdInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/ConfigInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/IsAssistanceEnabledInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/SetAssistanceInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this
