### ISSUE TITLE
Failed opening required '/var/www/html/app/autoload.php'

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3201]
After installing the newest magento version 2.0.2 I get an error while running the installation script.

```
PHP Warning:  require_once(/var/www/html/app/autoload.php): failed to open stream: No such file or directory in /var/www/html/app/bootstrap.php on line 31
PHP Stack trace:
PHP   1. {main}() /var/www/html/bin/magento:0
PHP   2. require() /var/www/html/bin/magento:15
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/app/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/app/bootstrap.php on line 31
```

It is strange because `compoer install` downloads all modules but the mapping from the `magento-base` module doesn't work. In the `app` only `bootstrap.php`, `etc/vendor_path.php` and `design/adminhtml/Magento/...` are copied. Files like `autoload.php`, `functions.php` are not available in the `app` folder, but available in `vendor/magento/magento2-base/app`.

Any ideas whats wrong?

**Comment by ktomk** [comment]
Can you please run

```
composer -vvv run-script post-install-cmd
```

and provide the output?

And have you checked if file and directory access rights are properly set-up and you run composer with the correct user? (I assume you installed magento via the command-line, correct?)

**Comment by marvincaspar** [comment]
Yes I installed magento with cli. Here is the output:

```
Reading ./composer.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/var/www/sites/html): git describe --exact-match --tags
Executing command (/var/www/sites/html): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/sites/html/vendor/composer/installed.json
Loading plugin MagentoHackathon\Composer\Magento\Plugin
activate magento plugin
start magento deploy via deployManager
jump over deployLibraries as no Magento libraryPath is set
> post-install-cmd: chmod ug+x bin/magento
Executing command (CWD): chmod ug+x bin/magento
```

All files are owned by the same user, which is running the composer command

**Comment by ktomk** [comment]
Looks like you're installing as the root-user. As you [should](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html#integrator-first-composer-ce)

> 2. Log in to your Magento server as, or switch to, the Magento file system owner.

that would mean your magento file system owner would be root. I hardly doubt that so I assume you did this in error. As that kind of error supersedes your report from severity (IMHO), I'd say must fix the installation user problem first.

Especially as your report is about the composer installer not being able to copy files.

Note: Using the correct user in system setup must not automatically solve your problem but should create a basis on further trouble-shooting your issue.

**Comment by marvincaspar** [comment]
I tried it locally on my mashine with no root user and get the same result with an other user path

**Comment by ktomk** [comment]
@mc388: Then it's not the root user.

**Comment by marvincaspar** [comment]
Locally I'm using my dev user. He is also the owner of all files.

**Comment by marvincaspar** [comment]
Started a new installation from scratch and got this message

```
[196.5MB/62.54s] Generating autoload files
[197.2MB/62.99s] start magento deploy via deployManager
[197.2MB/62.99s] start magento deploy for magento/magento2-base
[197.2MB/67.78s] Source /var/www/sites/html/vendor/magento/magento2-base/app/design/frontend/Magento does not exist
[197.2MB/67.78s] start magento deploy for magento/magento2-ee-base
[197.2MB/69.13s] Source /var/www/sites/html/vendor/magento/magento2-ee-base/app/design/doc does not exist
[197.2MB/69.13s] jump over deployLibraries as no Magento libraryPath is set
```

**Comment by marvincaspar** [comment]
Created a new issue with more details #3248

**Comment by kabiridris** [comment]
I am still having the same error. Anyone with a solution please?

Thanks.
