### ISSUE TITLE
Mark AdvancedSearch, Analytics, Backend, Bundle, CardinalCommerce as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32013]
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/AdvancedSearch/Block/SearchDataInterface.php
1. app/code/Magento/Analytics/Api/Data/LinkInterface.php
1. app/code/Magento/Analytics/Api/LinkProviderInterface.php
1. app/code/Magento/Analytics/Model/Connector/CommandInterface.php
1. app/code/Magento/Analytics/Model/ExportDataHandlerInterface.php
1. app/code/Magento/Analytics/Model/ReportWriterInterface.php
1. app/code/Magento/Analytics/ReportXml/DB/Assembler/AssemblerInterface.php
1. app/code/Magento/Backend/Model/Image/UploadResizeConfigInterface.php
1. app/code/Magento/Backend/Model/Search/Config/Structure/ElementBuilderInterface.php
1. app/code/Magento/Bundle/Pricing/Adjustment/BundleCalculatorInterface.php
1. app/code/Magento/CardinalCommerce/Model/Response/JwtParserInterface.php
1. app/code/Magento/CardinalCommerce/Model/Response/JwtPayloadValidatorInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this
