### ISSUE TITLE
Mark MediaGallery interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32019]
The following interfaces should be marked as API in api-changes-develop branch

1. app/code/Magento/MediaContentApi/Api/GetAssetIdsByContentFieldInterface.php
1. app/code/Magento/MediaContentApi/Api/UpdateContentAssetLinksInterface.php
1. app/code/Magento/MediaContentApi/Model/GetAssetIdsByContentFieldInterface.php
1. app/code/Magento/MediaContentApi/Model/SearchPatternConfigInterface.php
1. app/code/Magento/MediaContentSynchronizationApi/Api/SynchronizeIdentitiesInterface.php
1. app/code/Magento/MediaContentSynchronizationApi/Api/SynchronizeInterface.php
1. app/code/Magento/MediaContentSynchronizationApi/Model/GetEntitiesInterface.php
1. app/code/Magento/MediaGalleryApi/Api/SearchAssetsInterface.php
1. app/code/Magento/MediaGalleryApi/Model/ExcludedPatternsConfigInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Api/AddMetadataInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Api/Data/MetadataInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Api/ExtractMetadataInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/FileInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/ReadFileInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/ReadMetadataInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/SegmentInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/WriteFileInterface.php
1. app/code/Magento/MediaGalleryMetadataApi/Model/WriteMetadataInterface.php
1. app/code/Magento/MediaGalleryRenditionsApi/Api/GenerateRenditionsInterface.php
1. app/code/Magento/MediaGalleryRenditionsApi/Api/GetRenditionPathInterface.php
1. app/code/Magento/MediaGallerySynchronizationApi/Api/SynchronizeFilesInterface.php
1. app/code/Magento/MediaGallerySynchronizationApi/Api/SynchronizeInterface.php
1. app/code/Magento/MediaGallerySynchronizationApi/Model/CreateAssetFromFileInterface.php
1. app/code/Magento/MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php
1. app/code/Magento/MediaGallerySynchronizationApi/Model/ImportFilesInterface.php
1. app/code/Magento/MediaGalleryUiApi/Api/ConfigInterface.php

**Comment by AndreyChorniy** [comment]
@magento I am working on this
