### ISSUE TITLE
Mark Catalog interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32014]
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/Catalog/Block/Product/AwareInterface.php
1. app/code/Magento/Catalog/Block/Product/ReviewRendererInterface.php
1. app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/HandlerInterface.php
1. app/code/Magento/Catalog/Controller/Product/View/ViewInterface.php
1. app/code/Magento/Catalog/Model/Attribute/LockValidatorInterface.php
1. app/code/Magento/Catalog/Model/Config/Source/ProductPriceOptionsInterface.php
1. app/code/Magento/Catalog/Model/Entity/Product/Attribute/Group/AttributeMapperInterface.php
1. app/code/Magento/Catalog/Model/Indexer/Product/Flat/TableDataInterface.php
1. app/code/Magento/Catalog/Model/Layer/CollectionFilterInterface.php
1. app/code/Magento/Catalog/Model/Layer/FilterableAttributeListInterface.php
1. app/code/Magento/Catalog/Model/Layer/ItemCollectionProviderInterface.php
1. app/code/Magento/Catalog/Model/Layer/StateKeyInterface.php
1. app/code/Magento/Catalog/Model/Product/Condition/ConditionInterface.php
1. app/code/Magento/Catalog/Model/Product/Configuration/Item/Option/OptionInterface.php
1. app/code/Magento/Catalog/Model/Product/Media/ConfigInterface.php
1. app/code/Magento/Catalog/Model/Product/Pricing/Renderer/SalableResolverInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/CollectionProviderInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Converter/ConverterInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Data/ListCriteriaInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Data/ListResultInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/MapProviderInterface.php
1. app/code/Magento/Catalog/Model/ProductOptions/ConfigInterface.php
1. app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/PriceModifierInterface.php
1. app/code/Magento/Catalog/Model/ResourceModel/Product/LinkedProductSelectBuilderInterface.php
1. app/code/Magento/Catalog/Pricing/Price/ConfiguredPriceInterface.php
1. app/code/Magento/Catalog/Pricing/Price/MinimalPriceCalculatorInterface.php
1. app/code/Magento/Catalog/Pricing/Price/SpecialPriceInterface.php
1. app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav/WysiwygConfigDataProcessorInterface.php

**Comment by vlmed** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41802` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
