### ISSUE TITLE
Mark Directory, Downloadable, Eav and Elasticsearch interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32017]
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/Directory/Model/Country/Postcode/ConfigInterface.php
1. app/code/Magento/Directory/Model/Country/Postcode/ValidatorInterface.php
1. app/code/Magento/Downloadable/Api/DomainManagerInterface.php
1. app/code/Magento/Downloadable/Pricing/Price/LinkPriceInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/AttributeInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/Backend/BackendInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/Source/SpecificSourceInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/UniqueValidationInterface.php
1. app/code/Magento/Eav/Model/Entity/AttributeLoaderInterface.php
1. app/code/Magento/Eav/Model/Entity/Setup/PropertyMapperInterface.php
1. app/code/Magento/Eav/Model/ResourceModel/Attribute/DefaultEntityAttributes/ProviderInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldIndex/ConverterInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldIndex/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldName/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldType/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProviderInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldsMappingPreprocessorInterface.php
1. app/code/Magento/Elasticsearch/SearchAdapter/Query/ValueTransformerInterface.php
1. app/code/Magento/Elasticsearch/SearchAdapter/QueryAwareInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41929` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
