### ISSUE TITLE
Division by zero at order completion on tax exempt products when multiple tax rates exist

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#32010]
This has happened to me on 2.4.1 where all my products have taxes applied except for one which is tax exempt

An order with that product in it will have its payment successfully taken but then fail at the final step

### Preconditions (*)

Have products with multiple tax rates applied

Have a class of products where these tax rates are all 0, overriding the default. 

### Steps to reproduce (*)

Place an order including the 0 taxed product

### Expected result (*)

Payment is taken successfully and the order is created
The confirmation page appears

### Actual result (*)

Payment is taken successfully and the order is created
The confirmation page does not appear
Order is not completed for the customer and they will try several times.

An error message appears

**main.CRITICAL: Saving order failed: Warning: Division by zero in /vendor/magento/module-tax/Model/Plugin/OrderSave.php on line 107**

There is indeed a bug in the code that deals with tax information at order completion, in the branch of the code used if there are multiple tax rates for a product rather than just one. This does not accommodate those rates being 0 for some products

The code does start on line 101 with  `$percentSum = 0;`  

The lines on 107 and 108 then both divide by  `$percentSum` without checking for the possibility that the value is still zero. Which in some rare cases it can be. A simple check on these lines should fix it

This needs an alternative for when the rate is 0.

` foreach ($taxRates as $rate) {
                                $realAmount = $rates['amount'] * $rate['percent'] / $percentSum;

                                $realBaseAmount = $rates['base_amount'] * $rate['percent'] / $percentSum;

                                $ratesIdQuoteItemId[$rates['id']][] = [
                                    'id' => $taxesArray['item_id'],
                                    'percent' => $rate['percent'],
                                    'code' => $rate['code'],
                                    'associated_item_id' => $taxesArray['associated_item_id'],
                                    'item_type' => $taxesArray['type'],
                                    'amount' => $rates['amount'],
                                    'base_amount' => $rates['base_amount'],
                                    'real_amount' => $realAmount,
                                    'real_base_amount' => $realBaseAmount,
                                ];

                            }

                        }`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by iphigenie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hello @iphigenie 

Thank you for your report

We are trying to reproduce the issue on the latest 2.4-develop and it is not reproducible.

Can you please correct our steps? Here is what we tried:

1. Go to _Stores - Tax Rules_ click **Add New Tax Rule**
2. Expand **Additional Settings**. Under _Product Tax Class_ click **Add New Tax Class**. Name it "Custom Zero" for example
![custome_zero](https://user-images.githubusercontent.com/51680745/107946224-6760ab00-6f99-11eb-9731-7bb9d168980c.png)
3. Type a name under _Tax Rule Information_ and click **Add New Tax Rate**
4. Set the following settings and **Save**:
- Tax Identifier - Custom Rate
- Zip/Post Code - *
- State - *
- Country - United States
- Rate Percent - 0
![rate2](https://user-images.githubusercontent.com/51680745/107946694-0e454700-6f9a-11eb-9565-bd12def95334.png)
5. **Save Rule**
6. Create and activate any tax rule for US Customers. 10% for example
7. Create a Simple Product selecting the previously created "Custom zero" as **Tax Class**
![tax_class_zero](https://user-images.githubusercontent.com/51680745/107947392-fb7f4200-6f9a-11eb-81d5-17e746486ff1.png)
8. Have a Simple product not changing the tax class, leave all by default while creating
9. Go to the Store front as a Customer with a valid US address 
10. Place an order selecting both previously created products

**Actual Result**
The order is placed successfully, no exception message 

Please, correct out steps and provide more details about the issue.
Thank you in advance

**Comment by iphigenie** [comment]
Hi engcom 

You need 2 different tax rules and tax rates, both zero for a particular product tax class (in my case: educational books). 

It's a hassle to reproduce on your vanilla instances as after I created new product tax classes, rates and rules, the changes don't deploy immediately, my test orders even in admin continued to use the old rates. I think the deployment of tax changes is several different a cron scheduled actions and without the command line to speed it up you just can't easily test.

It probably helps to look at the code on  `/vendor/magento/module-tax/Model/Plugin/OrderSave.php`

It requests applicable rates for the address match and the product in the order. There is a branching, one is used if only one rate is returned, the other is used is more than one rate is returned. That is where a variable is set to 0, tax rates are added to it, then it is used in a division without checking that the value is perhaps still 0.

It is not a common situation but it is not impossible - you can have national, state and city taxes, and some products exempt of all (educational books, baby clothes) at certain levels or all levels. 

PS: There is usually a way to work around the bug by carefully removing the product classes from rules, but there is always the risk that then suddenly a more general rule will apply and you will tax a product that you should not tax, and boy is that a PR disaster.

**Comment by engcom-Bravo** [comment]
@iphigenie Thank you for the response.

Can you please answer, which Payment Method are you using?

Thank you in advance

**Comment by krishprakash** [comment]
@iphigenie Closing this issue due inactivity
Feel free reopen add feedback to further proceedings

**Comment by iphigenie** [comment]
Hi @engcom-Bravo and @krishprakash 

This has nothing to do with payment methods, it happens no matter the method if you have multiple taxes (eg: local sales tax and state/county tax and national value added tax) set for products and then some rare product class is exempt of all of them (books, children's clothes etc.). It takes longer to build all these tax rates and product types than it does to just see the issue in the code: value set to 0, then value used in division later

The fix is simple, just add a check that $percentSum is not still zero (it is initialised as 0!) before the division: 

`$realAmount = $rates['amount'] * $rate['percent'] / $percentSum;`

and then populate the $ratesIdQuoteItemId[$rates['id']][] array without doing any "proportion" adjustment

If this ticket would just have been progressed I would have submitted a fix.

I don't really care, I reorganised things so I don't have multiple tax rates but it will happen to other people, and the fix is so simple.

**Comment by iphigenie** [comment]
not to forget the loss of confidence in the whole tax module - if a DIVISION BY ZERO is allowed to happen, what other basic mistakes are in there?
