### ISSUE TITLE
Mark Catalog*, Checkout, Cms, ConfigurableProduct interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32015]
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/LayerBuilderInterface.php
1. app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php
1. app/code/Magento/CatalogGraphQl/Model/Resolver/Product/Price/ProviderInterface.php
1. app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Product/CollectionProcessorInterface.php
1. app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ProductQueryInterface.php
1. app/code/Magento/CatalogImportExport/Model/Export/ProductFilterInterface.php
1. app/code/Magento/CatalogRule/Model/Indexer/IndexerTableSwapperInterface.php
1. app/code/Magento/CatalogSearch/Model/Adapter/Aggregation/RequestCheckerInterface.php
1. app/code/Magento/CatalogSearch/Model/Advanced/ProductCollectionPrepareStrategyInterface.php
1. app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection/SearchCriteriaResolverInterface.php
1. app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplierInterface.php
1. app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection/TotalRecordsResolverInterface.php
1. app/code/Magento/CatalogSearch/Model/Search/ItemCollectionProviderInterface.php
1. app/code/Magento/CatalogUrlRewrite/Model/Map/DatabaseMapInterface.php
1. app/code/Magento/CatalogUrlRewrite/Model/Map/HashMapInterface.php
1. app/code/Magento/Checkout/Api/PaymentProcessingRateLimiterInterface.php
1. app/code/Magento/Checkout/Controller/Express/RedirectLoginInterface.php
1. app/code/Magento/Checkout/CustomerData/ItemPoolInterface.php
1. app/code/Magento/CheckoutAgreements/Model/AgreementsProviderInterface.php
1. app/code/Magento/Cms/Model/Page/CustomLayout/Data/CustomLayoutSelectedInterface.php
1. app/code/Magento/Cms/Model/Page/CustomLayoutManagerInterface.php
1. app/code/Magento/Cms/Model/Page/CustomLayoutRepositoryInterface.php
1. app/code/Magento/Cms/Model/PageRepository/ValidatorInterface.php
1. app/code/Magento/Cms/Ui/Component/AddFilterInterface.php
1. app/code/Magento/ConfigurableProduct/Model/ResourceModel/Attribute/OptionSelectBuilderInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42317` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
