### ISSUE TITLE
Mark Framework GraphQL interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32028]
The following interfaces should be marked as API in 2.4-develop branch:

1. lib/internal/Magento/Framework/GraphQl/Config/ConfigElementFactoryInterface.php
1. lib/internal/Magento/Framework/GraphQl/Config/ConfigElementInterface.php
1. lib/internal/Magento/Framework/GraphQl/Config/Element/FieldInterface.php
1. lib/internal/Magento/Framework/GraphQl/Config/Element/OutputFieldInterface.php
1. lib/internal/Magento/Framework/GraphQl/Config/Element/TypeInterface.php
1. lib/internal/Magento/Framework/GraphQl/Config/Element/UnionInterface.php
1. lib/internal/Magento/Framework/GraphQl/ConfigInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/ErrorHandlerInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributesInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/SearchCriteria/ArgumentApplierInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchRequestItemInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchResolverInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchServiceContractResolverInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/ContextInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/IdentityInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/ResolveRequestInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/Resolver/TypeResolverInterface.php
1. lib/internal/Magento/Framework/GraphQl/Query/ResolverInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/SchemaGeneratorInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/Entity/MapperInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/Enum/DataMapperInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/InputTypeInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/Output/ElementMapper/FormatterInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/OutputTypeInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/Type/WrappedTypeInterface.php
1. lib/internal/Magento/Framework/GraphQl/Schema/TypeInterface.php
1. lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader/TypeMetaReaderInterface.php

**Comment by mrtuvn** [comment]
@magento i am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41764` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
