### ISSUE TITLE
Mark Msrp, Newsletter, PageCache, Payment, Paypal and Quote interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32020]
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/Msrp/Pricing/MsrpPriceCalculatorInterface.php
1. app/code/Magento/Newsletter/Model/SubscriptionManagerInterface.php
1. app/code/Magento/PageCache/Model/Spi/PageCacheTagsPreprocessorInterface.php
1. app/code/Magento/Payment/Api/Data/PaymentAdditionalInfoInterface.php
1. app/code/Magento/Payment/Model/Method/Online/GatewayInterface.php
1. app/code/Magento/Payment/Model/Method/TransparentInterface.php
1. app/code/Magento/Paypal/Helper/Shortcut/ValidatorInterface.php
1. app/code/Magento/Paypal/Model/Billing/Agreement/MethodInterface.php
1. app/code/Magento/Paypal/Model/IpnInterface.php
1. app/code/Magento/Paypal/Model/Payflow/Service/Response/Handler/HandlerInterface.php
1. app/code/Magento/Paypal/Model/Payflow/Service/Response/ValidatorInterface.php
1. app/code/Magento/Quote/Api/ChangeQuoteControlInterface.php
1. app/code/Magento/Quote/Model/Cart/BuyRequest/BuyRequestDataProviderInterface.php
1. app/code/Magento/Quote/Model/Product/QuoteItemsCleanerInterface.php
1. app/code/Magento/Quote/Model/Quote/Address/CustomAttributeListInterface.php
1. app/code/Magento/Quote/Model/Quote/Address/Total/CollectorInterface.php
1. app/code/Magento/Quote/Model/Quote/Address/Total/ReaderInterface.php
1. app/code/Magento/Quote/Model/Quote/Item/CartItemProcessorInterface.php
1. app/code/Magento/Quote/Model/ValidationRules/QuoteValidationRuleInterface.php
1. app/code/Magento/QuoteGraphQl/Model/Cart/BuyRequest/BuyRequestDataProviderInterface.php
1. app/code/Magento/QuoteGraphQl/Model/Cart/Payment/AdditionalDataProviderInterface.php
1. app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressesOnCartInterface.php
1. app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingMethodsOnCartInterface.php
1. app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/CustomizableOptionValueInterface.php
1. app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/Processor/ItemDataProcessorInterface.php

**Comment by mrtuvn** [comment]
@magento i am working on this
