### ISSUE TITLE
Mark Search, Security, Shipping, Store, Tax, Theme and Ui interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32022]
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/Search/Model/SearchEngine/ValidatorInterface.php
1. app/code/Magento/Search/Setup/InstallConfigInterface.php
1. app/code/Magento/Security/Api/Data/UserExpirationInterface.php
1. app/code/Magento/Shipping/Model/Carrier/Source/GenericInterface.php
1. app/code/Magento/Store/Model/Config/Importer/Processor/ProcessorInterface.php
1. app/code/Magento/Store/Model/StoreResolver/ReaderInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/ContextInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPostprocessorInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPreprocessorInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataSerializerInterface.php
1. app/code/Magento/Store/Model/StoreSwitcherInterface.php
1. app/code/Magento/Tax/Api/TaxAddressManagerInterface.php
1. app/code/Magento/Tax/Model/System/Message/NotificationInterface.php
1. app/code/Magento/Tax/Model/TaxClass/Type/TypeInterface.php
1. app/code/Magento/Theme/Model/Design/Config/MetadataProviderInterface.php
1. app/code/Magento/Theme/Model/Theme/StoreThemesResolverInterface.php
1. app/code/Magento/Ui/Component/Form/Element/DataType/DataTypeInterface.php
1. app/code/Magento/Ui/Component/Layout/Tabs/TabInterface.php
1. app/code/Magento/Ui/Component/Wysiwyg/ConfigInterface.php
1. app/code/Magento/Ui/Config/Argument/ParserInterface.php
1. app/code/Magento/Ui/Config/ConverterInterface.php
1. app/code/Magento/Ui/Controller/UiActionInterface.php
1. app/code/Magento/Ui/DataProvider/AddFieldToCollectionInterface.php
1. app/code/Magento/Ui/DataProvider/AddFilterToCollectionInterface.php
1. app/code/Magento/Ui/DataProvider/Mapper/MapperInterface.php
1. app/code/Magento/Ui/DataProvider/Modifier/PoolInterface.php
1. app/code/Magento/Ui/Model/ColorPicker/ModeInterface.php
1. app/code/Magento/Ui/Model/UrlInput/ConfigInterface.php

**Comment by mrtuvn** [comment]
@magento i am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41765` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
