### ISSUE TITLE
Mark ReleaseNotification, RemoteStorage and Sales interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32021]
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/ReleaseNotification/Model/ContentProviderInterface.php
1. app/code/Magento/RemoteStorage/Driver/DriverFactoryInterface.php
1. app/code/Magento/RemoteStorage/Driver/RemoteDriverInterface.php
1. app/code/Magento/RemoteStorage/FilesystemInterface.php
1. app/code/Magento/Sales/Api/OrderCustomerDelegateInterface.php
1. app/code/Magento/Sales/Api/PaymentFailuresInterface.php
1. app/code/Magento/Sales/Controller/AbstractController/OrderLoaderInterface.php
1. app/code/Magento/Sales/Controller/AbstractController/OrderViewAuthorizationInterface.php
1. app/code/Magento/Sales/Controller/OrderInterface.php
1. app/code/Magento/Sales/Model/Order/Creditmemo/CreditmemoValidatorInterface.php
1. app/code/Magento/Sales/Model/Order/Creditmemo/ItemCreationValidatorInterface.php
1. app/code/Magento/Sales/Model/Order/Creditmemo/SenderInterface.php
1. app/code/Magento/Sales/Model/Order/Email/Container/IdentityInterface.php
1. app/code/Magento/Sales/Model/Order/Invoice/InvoiceValidatorInterface.php
1. app/code/Magento/Sales/Model/Order/Invoice/SenderInterface.php
1. app/code/Magento/Sales/Model/Order/OrderValidatorInterface.php
1. app/code/Magento/Sales/Model/Order/Payment/State/CommandInterface.php
1. app/code/Magento/Sales/Model/Order/Payment/Transaction/BuilderInterface.php
1. app/code/Magento/Sales/Model/Order/Payment/Transaction/ManagerInterface.php
1. app/code/Magento/Sales/Model/Order/Shipment/SenderInterface.php
1. app/code/Magento/Sales/Model/Order/Shipment/ShipmentValidatorInterface.php
1. app/code/Magento/Sales/Model/ResourceModel/Order/CollectionFactoryInterface.php
1. app/code/Magento/Sales/Model/ResourceModel/Provider/NotSyncedDataProviderInterface.php
1. app/code/Magento/Sales/Model/Spi/CreditmemoCommentResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/CreditmemoItemResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/CreditmemoResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/InvoiceCommentResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/InvoiceItemResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/InvoiceResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/OrderAddressResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/OrderItemResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/OrderPaymentResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/OrderResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/OrderStatusHistoryResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/ShipmentCommentResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/ShipmentItemResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/ShipmentResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/ShipmentTrackResourceInterface.php
1. app/code/Magento/Sales/Model/Spi/TransactionResourceInterface.php
1. app/code/Magento/Sales/Model/ValidatorInterface.php
1. app/code/Magento/SalesGraphQl/Model/Shipment/Item/FormatterInterface.php
1. app/code/Magento/SalesRule/Api/Data/DiscountDataInterface.php
1. app/code/Magento/SalesRule/Api/Data/RuleDiscountInterface.php
1. app/code/Magento/SalesRule/Model/Spi/CodeLimitManagerInterface.php
1. app/code/Magento/SalesRule/Model/Spi/QuoteResetAppliedRulesInterface.php
1. app/code/Magento/SalesRule/Model/Spi/RuleQuoteRecollectTotalsInterface.php

**Comment by AndreyChorniy** [comment]
@magento I am working on this
