### ISSUE TITLE
Mark UrlRewriteGraphQl, User, Vault, Webapi, Widget and Wishlist interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32023]
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/UrlRewriteGraphQl/Model/Resolver/UrlRewrite/CustomUrlLocatorInterface.php
1. app/code/Magento/User/Model/Spi/NotificationExceptionInterface.php
1. app/code/Magento/User/Model/Spi/NotificatorInterface.php
1. app/code/Magento/Vault/Block/Customer/IconInterface.php
1. app/code/Magento/Webapi/Controller/Rest/RequestProcessorInterface.php
1. app/code/Magento/Widget/Block/BlockInterface.php
1. app/code/Magento/Wishlist/Controller/IndexInterface.php
1. app/code/Magento/Wishlist/Controller/WishlistProviderInterface.php
1. app/code/Magento/Wishlist/Model/AuthenticationStateInterface.php
1. app/code/Magento/Wishlist/Model/ResourceModel/Item/Product/CollectionBuilderInterface.php
1. app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/BuyRequestDataProviderInterface.php

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41813` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
