### ISSUE TITLE
Mark framework interfaces as API part 6

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32032]
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Profiler/Driver/Standard/OutputInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/Aggregation/AggregationResolverInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/OptionsInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/Preprocessor/PreprocessorInterface.php
1. lib/internal/Magento/Framework/Search/AdapterInterface.php
1. lib/internal/Magento/Framework/Search/Dynamic/Algorithm/AlgorithmInterface.php
1. lib/internal/Magento/Framework/Search/Request/Aggregation/StatusInterface.php
1. lib/internal/Magento/Framework/Search/Request/IndexScopeResolverInterface.php
1. lib/internal/Magento/Framework/Search/ResponseInterface.php
1. lib/internal/Magento/Framework/Search/SearchEngine/ConfigInterface.php
1. lib/internal/Magento/Framework/Search/SearchEngineInterface.php
1. lib/internal/Magento/Framework/Session/Config/ConfigInterface.php
1. lib/internal/Magento/Framework/Session/SaveHandlerInterface.php
1. lib/internal/Magento/Framework/Session/StorageInterface.php
1. lib/internal/Magento/Framework/Session/ValidatorInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this
