### ISSUE TITLE
Mark Framework MessageQueue interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32030]
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/MessageQueue/BulkPublisherInterface.php
1. lib/internal/Magento/Framework/MessageQueue/CallbackInvokerInterface.php
1. lib/internal/Magento/Framework/MessageQueue/ConnectionTypeResolverInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Consumer/Config/ConsumerConfigItem/HandlerInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Consumer/Config/ConsumerConfigItemInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Consumer/Config/ReaderInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Consumer/Config/ValidatorInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Lock/ReaderInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Lock/WriterInterface.php
1. lib/internal/Magento/Framework/MessageQueue/LockInterface.php
1. lib/internal/Magento/Framework/MessageQueue/MergedMessageInterface.php
1. lib/internal/Magento/Framework/MessageQueue/MergerInterface.php
1. lib/internal/Magento/Framework/MessageQueue/MessageProcessorInterface.php
1. lib/internal/Magento/Framework/MessageQueue/PoisonPill/PoisonPillCompareInterface.php
1. lib/internal/Magento/Framework/MessageQueue/PoisonPill/PoisonPillPutInterface.php
1. lib/internal/Magento/Framework/MessageQueue/PoisonPill/PoisonPillReadInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Publisher/Config/PublisherConfigItemInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Publisher/Config/PublisherConnectionInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Publisher/Config/ReaderInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Publisher/Config/ValidatorInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Topology/Config/ExchangeConfigItem/BindingInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Topology/Config/ExchangeConfigItemInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItemInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Topology/Config/ReaderInterface.php
1. lib/internal/Magento/Framework/MessageQueue/Topology/Config/ValidatorInterface.php

**Comment by AndreyChorniy** [comment]
@magento I am working on this
