### ISSUE TITLE
Mark Framework Model, Module, Mview and ObjectManager interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32031]
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Model/Entity/ScopeInterface.php
1. lib/internal/Magento/Framework/Model/Entity/ScopeProviderInterface.php
1. lib/internal/Magento/Framework/Model/EntitySnapshot/AttributeProviderInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Db/VersionControl/RelationInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Type/Db/ConnectionFactoryInterface.php
1. lib/internal/Magento/Framework/Module/ModuleListInterface.php
1. lib/internal/Magento/Framework/Mview/ConfigInterface.php
1. lib/internal/Magento/Framework/Mview/ProcessorInterface.php
1. lib/internal/Magento/Framework/Mview/View/ChangelogInterface.php
1. lib/internal/Magento/Framework/Mview/View/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/State/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/StateInterface.php
1. lib/internal/Magento/Framework/Mview/View/SubscriptionInterface.php
1. lib/internal/Magento/Framework/Mview/ViewInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigLoaderInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DefinitionInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DynamicConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/FactoryInterface.php
1. lib/internal/Magento/Framework/ObjectManager/NoninterceptableInterface.php
1. lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41932` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
