### ISSUE TITLE
Mark Framework Setup interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32033]
The following interfaces should be marked as API

1. lib/internal/Magento/Framework/Setup/ConfigOptionsListInterface.php
1. lib/internal/Magento/Framework/Setup/DataCacheInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/DataSavior/DataSaviorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/DataSavior/DumpAccessorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DDLTriggerInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbDefinitionProcessorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbSchemaReaderInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbSchemaWriterInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Declaration/ValidationInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Diff/DiffInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnDefaultAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnIdentityAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnNullableAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnUnsignedAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/ElementDiffAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Factories/FactoryInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/TableElementInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/OperationInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/SchemaConfigInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/DataPatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/DependentPatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/NonTransactionableInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/PatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/PatchRevertableInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/SchemaPatchInterface.php
1. lib/internal/Magento/Framework/Setup/SampleData/InstallerInterface.php
1. lib/internal/Magento/Framework/Setup/SampleData/StateInterface.php
1. lib/internal/Magento/Framework/Setup/SchemaListenerDefinition/DefinitionConverterInterface.php
1. lib/internal/Magento/Framework/Setup/SchemaListenerHandlers/SchemaListenerHandlerInterface.php
1. lib/internal/Magento/Framework/Setup/UpToDateValidatorInterface.php

**Comment by Usik2203** [comment]
@magento I am working on this
