### ISSUE TITLE
Mark Checkout and Bundle blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32045]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Checkout\Block\Cart
1. Magento\Checkout\Block\Registration
1. Magento\Checkout\Block\Onepage
1. Magento\Checkout\Block\Onepage\Success
1. Magento\Checkout\Block\Onepage\Failure
1. Magento\Checkout\Block\Onepage\Link
1. Magento\Checkout\Block\Item\Price\Renderer
1. Magento\Checkout\Block\Cart\Grid
1. Magento\Checkout\Block\Cart\Totals
1. Magento\Checkout\Block\Cart\Sidebar
1. Magento\Checkout\Block\Cart\Shipping
1. Magento\Checkout\Block\Cart\Coupon
1. Magento\Checkout\Block\Cart\Item\Renderer
1. Magento\Checkout\Block\Cart\Item\Renderer\Actions
1. Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove
1. Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit
1. Magento\Checkout\Block\Cart\Additional\Info
1. Magento\Bundle\Block\Sales\Order\Items\Renderer
1. Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer
1. Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Usik2203** [comment]
HI @sivaschenko 
I see that all these block already marked as API 
Thanks

**Comment by sivaschenko** [comment]
Thanks @Usik2203 ! I will recheck the blocks list for all tasks
