### ISSUE TITLE
Mark Catalog Blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32043]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Catalog\Block\Navigation
1. Magento\Catalog\Block\FrontendStorageManager
1. Magento\Catalog\Block\Adminhtml\Product
1. Magento\Catalog\Block\Adminhtml\Category\Tree
1. Magento\Catalog\Block\Adminhtml\Category\Edit
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute\Tab\Websites
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Action\Attribute\Tab\Inventory
1. Magento\Catalog\Block\Adminhtml\Product\Composite\Configure
1. Magento\Catalog\Block\Adminhtml\Product\Composite\Fieldset\Qty
1. Magento\Catalog\Block\Adminhtml\Product\Attribute\Set\Main
1. Magento\Catalog\Block\Adminhtml\Product\Attribute\Set\Toolbar\Main
1. Magento\Catalog\Block\Category\View
1. Magento\Catalog\Block\Category\Rss\Link
1. Magento\Catalog\Block\Ui\ProductViewCounter
1. Magento\Catalog\Block\Product\Gallery
1. Magento\Catalog\Block\Product\ProductList\Toolbar
1. Magento\Catalog\Block\Product\View\Additional
1. Magento\Catalog\Block\Product\View\Description
1. Magento\Catalog\Block\Product\View\Options
1. Magento\Catalog\Block\Product\View\Attributes
1. Magento\Catalog\Block\Product\View\Details
1. Magento\Catalog\Block\Product\View\Options\Type\Date
1. Magento\Catalog\Block\Product\View\Options\Type\Text
1. Magento\Catalog\Block\Product\View\Options\Type\File
1. Magento\Catalog\Block\Product\View\Options\Type\Select

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Usik2203** [comment]
HI @sivaschenko 
I see that all these blocks already marked as API
Thanks
