### ISSUE TITLE
Mark Theme, Eav, Ui, Rss, Wishlist and Downloadable Blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32049]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Theme\Block\Html\Header
1. Magento\Theme\Block\Html\Notices
1. Magento\Theme\Block\Html\Footer
1. Magento\Theme\Block\Html\Pager
1. Magento\Theme\Block\Html\Breadcrumbs
1. Magento\Theme\Block\Html\Topmenu
1. Magento\Theme\Block\Html\Title
1. Magento\Theme\Block\Html\Header\Logo
1. Magento\Theme\Block\Adminhtml\Design\Config\Edit\Scope
1. Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content
1. Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Tree
1. Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content\Files
1. Magento\Theme\Block\Adminhtml\Wysiwyg\Files\Content\Uploader
1. Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\Labels
1. Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\Options
1. Magento\Ui\Block\Logger
1. Magento\Ui\Block\Wysiwyg\ActiveEditor
1. Magento\Ui\Block\Component\StepsWizard
1. Magento\Rss\Block\Feeds
1. Magento\Wishlist\Block\AddToWishlist
1. Magento\Wishlist\Block\Link
1. Magento\Wishlist\Block\Rss\Link
1. Magento\Wishlist\Block\Item\Configure
1. Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist
1. Magento\Wishlist\Block\Customer\Sharing
1. Magento\Wishlist\Block\Customer\Wishlist\Button
1. Magento\Wishlist\Block\Customer\Wishlist\Items
1. Magento\Downloadable\Block\Sales\Order\Email\Items\Downloadable
1. Magento\Downloadable\Block\Sales\Order\Email\Items\Order\Downloadable
1. Magento\Downloadable\Block\Sales\Order\Item\Renderer\Downloadable
1. Magento\Downloadable\Block\Adminhtml\Sales\Items\Column\Downloadable\Name
1. Magento\Downloadable\Block\Checkout\Success
1. Magento\Downloadable\Block\Checkout\Cart\Item\Renderer
1. Magento\Downloadable\Block\Customer\Products\ListProducts

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
Hello @sivaschenko,

I checked all Blocks class from this issue and all of them have already marked as @api . So should I add additional information or do nothing?
Thanks.

**Comment by sivaschenko** [comment]
Thanks for checking @vlmed, nothing should be done, I will recheck the blocks lists for all tasks
