### ISSUE TITLE
Mark Backend Blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32044]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Backend\Block\Menu
1. Magento\Backend\Block\GlobalSearch
1. Magento\Backend\Block\Page
1. Magento\Backend\Block\Template
1. Magento\Backend\Block\Denied
1. Magento\Backend\Block\Page\Header
1. Magento\Backend\Block\Page\Notices
1. Magento\Backend\Block\Page\RequireJs
1. Magento\Backend\Block\Page\Footer
1. Magento\Backend\Block\Widget\Tabs
1. Magento\Backend\Block\Widget\Tab
1. Magento\Backend\Block\Widget\Button
1. Magento\Backend\Block\Widget\Breadcrumbs
1. Magento\Backend\Block\Widget\Container
1. Magento\Backend\Block\Widget\Form\Renderer\Fieldset
1. Magento\Backend\Block\Store\Switcher
1. Magento\Backend\Block\Cache\Additional

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Usik2203** [comment]
Hi @sivaschenko 
I see that all these blocks already marked as API
Thanks
