### ISSUE TITLE
Mark Sales Blocks as API part 1

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32046]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Sales\Block\Widget\Guest\Form
1. Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer
1. Magento\Sales\Block\Adminhtml\Items\Column\Name
1. Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn
1. Magento\Sales\Block\Adminhtml\Order\AbstractOrder
1. Magento\Sales\Block\Adminhtml\Order\Payment
1. Magento\Sales\Block\Adminhtml\Order\Comments\View
1. Magento\Sales\Block\Adminhtml\Order\Totals\Item
1. Magento\Sales\Block\Adminhtml\Order\Totals\Tax
1. Magento\Sales\Block\Adminhtml\Order\Create\Data
1. Magento\Sales\Block\Adminhtml\Order\Create\Customer
1. Magento\Sales\Block\Adminhtml\Order\Create\Coupons
1. Magento\Sales\Block\Adminhtml\Order\Create\Totals
1. Magento\Sales\Block\Adminhtml\Order\Create\Store
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar
1. Magento\Sales\Block\Adminhtml\Order\Create\Form
1. Magento\Sales\Block\Adminhtml\Order\Create\Newsletter
1. Magento\Sales\Block\Adminhtml\Order\Create\Search
1. Magento\Sales\Block\Adminhtml\Order\Create\Comment
1. Magento\Sales\Block\Adminhtml\Order\Create\Giftmessage
1. Magento\Sales\Block\Adminhtml\Order\Create\Items
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Pviewed
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Pcompared
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Cart
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Reorder
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Compared
1. Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Viewed
1. Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address
1. Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method
1. Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method\Form
1. Magento\Sales\Block\Adminhtml\Order\Create\Coupons\Form
1. Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid
1. Magento\Sales\Block\Adminhtml\Order\Create\Form\Account
1. Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Address
1. Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method
1. Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method\Form

**Comment by edenduong** [comment]
Hi @sivaschenko,

I check Sales Blocks class but I see it has been marked @api . So we should add additional information or do nothing ?

Thanks.
