### ISSUE TITLE
Mark Sales Blocks as API part 2

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32047]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Sales\Block\Adminhtml\Order\Invoice\Totals
1. Magento\Sales\Block\Adminhtml\Order\Invoice\Create\Form
1. Magento\Sales\Block\Adminhtml\Order\Invoice\Create\Items
1. Magento\Sales\Block\Adminhtml\Order\Invoice\View\Form
1. Magento\Sales\Block\Adminhtml\Order\Invoice\View\Comments
1. Magento\Sales\Block\Adminhtml\Order\Invoice\View\Items
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\Totals
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\Create\Form
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\Create\Adjustments
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\Create\Items
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\View\Form
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\View\Comments
1. Magento\Sales\Block\Adminhtml\Order\Creditmemo\View\Items
1. Magento\Sales\Block\Adminhtml\Order\View\Tabs
1. Magento\Sales\Block\Adminhtml\Order\View\History
1. Magento\Sales\Block\Adminhtml\Order\View\Giftmessage
1. Magento\Sales\Block\Adminhtml\Order\View\Info
1. Magento\Sales\Block\Adminhtml\Order\View\Items
1. Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer
1. Magento\Sales\Block\Adminhtml\Order\View\Tab\Shipments
1. Magento\Sales\Block\Adminhtml\Order\View\Tab\Invoices
1. Magento\Sales\Block\Adminhtml\Order\View\Tab\Creditmemos
1. Magento\Sales\Block\Adminhtml\Order\View\Tab\Info
1. Magento\Sales\Block\Adminhtml\Order\View\Tab\Transactions
1. Magento\Sales\Block\Reorder\Sidebar
1. Magento\Sales\Block\Order\Invoice
1. Magento\Sales\Block\Order\View
1. Magento\Sales\Block\Order\Recent
1. Magento\Sales\Block\Order\History
1. Magento\Sales\Block\Order\Totals
1. Magento\Sales\Block\Order\Creditmemo
1. Magento\Sales\Block\Order\PrintShipment
1. Magento\Sales\Block\Order\Comments
1. Magento\Sales\Block\Order\Info
1. Magento\Sales\Block\Order\Items
1. Magento\Sales\Block\Order\Email\Items
1. Magento\Sales\Block\Order\Email\Items\DefaultItems
1. Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder
1. Magento\Sales\Block\Order\Email\Invoice\Items
1. Magento\Sales\Block\Order\Email\Creditmemo\Items
1. Magento\Sales\Block\Order\Email\Shipment\Items
1. Magento\Sales\Block\Order\Invoice\Totals
1. Magento\Sales\Block\Order\Invoice\Items
1. Magento\Sales\Block\Order\History\Container
1. Magento\Sales\Block\Order\Creditmemo\Totals
1. Magento\Sales\Block\Order\Creditmemo\Items
1. Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer
1. Magento\Sales\Block\Order\Info\Buttons
1. Magento\Sales\Block\Order\Info\Buttons\Rss
1. Magento\Sales\Block\Order\PrintOrder\Invoice
1. Magento\Sales\Block\Order\PrintOrder\Shipment
1. Magento\Sales\Block\Order\PrintOrder\Creditmemo

**Comment by edenduong** [comment]
Hi @sivaschenko,

I check Sales Blocks class but I see it has been marked @api . So we should add additional information or do nothing ?

Thanks.

**Comment by sivaschenko** [comment]
Thanks for checking @edenduong ! I will review the blocks lists for all tasks
