### ISSUE TITLE
Mark Customer, User, Directory, Store and Cms Blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32048]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Customer\Block\SectionConfig
1. Magento\Customer\Block\CustomerData
1. Magento\Customer\Block\CustomerScopeData
1. Magento\Customer\Block\Newsletter
1. Magento\Customer\Block\Address\Grid
1. Magento\Customer\Block\Address\Book
1. Magento\Customer\Block\Address\Edit
1. Magento\Customer\Block\Form\Edit
1. Magento\Customer\Block\Form\Register
1. Magento\Customer\Block\Form\Login
1. Magento\Customer\Block\Form\Login\Info
1. Magento\Customer\Block\Account\SortLinkInterface
1. Magento\Customer\Block\Account\Resetpassword
1. Magento\Customer\Block\Account\Delimiter
1. Magento\Customer\Block\Account\Customer
1. Magento\Customer\Block\Account\Dashboard
1. Magento\Customer\Block\Account\Link
1. Magento\Customer\Block\Account\AuthorizationLink
1. Magento\Customer\Block\Account\Forgotpassword
1. Magento\Customer\Block\Account\AuthenticationPopup
1. Magento\Customer\Block\Account\Dashboard\Address
1. Magento\Customer\Block\Account\Dashboard\Info
1. Magento\User\Block\Buttons
1. Magento\Directory\Block\Currency
1. Magento\Store\Block\Switcher
1. Magento\Cms\Block\Page
1. Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content
1. Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree
1. Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files

**Comment by mrtuvn** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41769` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
All the classes are already marked as API.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @mrtuvn. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41769` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
