### ISSUE TITLE
Is it possible to use data migration tool version 2.0.0 on Magento 2.0.1 ?

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3204]
I haven't receive an answer in the [data migration tool](https://github.com/magento/data-migration-tool-ce/issues/57) section, so I ask here.

The data migration guide says:

"Note: The versions of both the migration tool and the Magento 2 code must be identical (for example, 2.0.0). To find the version of either package, open composer.json and find the value of "version"."

However, there is no data migration tool version 2.0.1.
Can I use the version 2.0.0 on magento 2.0.1?

**Comment by maksek** [comment]
Closing, since it was answered  in the data migration tool section
