### ISSUE TITLE
Mark classes and interfaces as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32054]
The following classes and interfaces should be marked as API

1. Magento\Framework\Data\FormFactory	
1. Magento\Framework\View\Element\UiComponent\Control\ButtonProviderInterface	
1. Magento\Framework\Event\ManagerInterface	
1. Magento\Framework\App\Filesystem\DirectoryList	
1. Magento\Framework\Api\AbstractSimpleObject	
1. Magento\Framework\Controller\Result\JsonFactory	
1. Magento\Framework\App\Response\RedirectInterface	
1. Magento\Framework\DataObject\IdentityInterface
1. Magento\Framework\App\Response\Http\FileFactory
1. Magento\Framework\Logger\Handler\Base	
1. Magento\Framework\Controller\Result\Raw	
1. Magento\Framework\View\LayoutFactory	
1. Magento\Sales\Model\ResourceModel\Order\CollectionFactory	
1. Magento\Widget\Block\BlockInterface	
1. Magento\Shipping\Model\Carrier\CarrierInterface	
1. Magento\Framework\View\Element\Html\Select	
1. Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult	
1. Magento\Customer\Controller\RegistryConstants	
1. Magento\Framework\App\Http\Context	
1. Magento\Framework\App\Action\HttpPostActionInterface
1. Magento\Customer\Model\Context	
1. Magento\Ui\Component\Layout\Tabs\TabInterface	
1. Magento\Framework\Filesystem\DirectoryList	
1. Magento\Framework\View\Element\UiComponent\ContextInterface	
1. Magento\Framework\App\Action\HttpGetActionInterface	
1. Magento\Framework\DataObject\Factory
1. Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider
1. Magento\Framework\App\CsrfAwareActionInterface	
1. Magento\Framework\App\CsrfAwareActionInterface

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this
