### ISSUE TITLE
Mark classes and interfaces as API part 3

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32058]
The following classes and interfaces should be marked as API in 2.4-develop branch

1. Magento\Framework\Data\Form\Element\Image	
1. Magento\Sales\Model\Order\Pdf\Total\DefaultTotal	
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Button\Generic	
1. Magento\Sales\Controller\Adminhtml\Order	
1. Magento\Customer\Setup\CustomerSetup	
1. Magento\Checkout\Controller\Cart
1. Magento\Quote\Model\Quote\Item\CartItemOptionsProcessor

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by mrtuvn** [comment]
Magento\Framework\View\DesignInterface seem duplicate in some other issue

**Comment by sivaschenko** [comment]
Thanks, @mrtuvn ! Can you please share the links to the issues it's mentioned on?

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/issues/32037 @sivaschenko 
 DesignInterface mark also note here

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
Thanks @mrtuvn , @Usik2203 `Magento\Framework\View\DesignInterface` removed from this task in favour of https://github.com/magento/magento2/issues/32037
