### ISSUE TITLE
Mark classes and interfaces as API part 2

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32056]
The following classes and interfaces should be marked as API in 2.4-develop branch

1. Magento\Ui\DataProvider\Modifier\PoolInterface	
1. Magento\Framework\App\RouterInterface	
1. Magento\Framework\Setup\Patch\DataPatchInterface
1. Magento\Framework\Console\Cli
1. Magento\Catalog\Controller\Adminhtml\Product	
1. Magento\Framework\App\Config\ValueFactory	
1. Magento\Framework\Module\ModuleListInterface
1. Magento\Catalog\Pricing\Price\FinalPrice
1. Magento\Framework\App\Config\ConfigResource\ConfigInterface	
1. Magento\Framework\Module\Dir	
1. Magento\Framework\App\Cache\Type\Config	
1. Magento\Store\Ui\Component\Listing\Column\Store\Options
1. Magento\Framework\Mview\ActionInterface
1. Magento\Ui\DataProvider\AddFieldToCollectionInterface	
1. Magento\Framework\Filesystem\Directory\ReadFactory
1. Magento\Framework\GraphQl\Query\ResolverInterface	
1. Magento\Payment\Gateway\Config\Config	
1. Magento\Ui\DataProvider\AddFilterToCollectionInterface	
1. Magento\Customer\Block\Adminhtml\Edit\GenericButton

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this
