### ISSUE TITLE
Mark blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32052]
The following blocks should be marked as API in 2.5-develop branch

1. Magento\InstantPurchase\Block\Button
1. Magento\Paypal\Block\Logo
1. Magento\Paypal\Block\Iframe
1. Magento\Paypal\Block\Billing\Agreements
1. Magento\Paypal\Block\Billing\Agreement\View
1. Magento\Paypal\Block\Express\Review
1. Magento\Paypal\Block\Express\InContext\Component
1. Magento\Paypal\Block\Express\Review\Details
1. Magento\Paypal\Block\Adminhtml\System\Config\ResolutionRules
1. Magento\SendFriend\Block\Send
1. Magento\CheckoutAgreements\Block\Agreements
1. Magento\Cookie\Block\RequireCookie
1. Magento\Cookie\Block\Html\Notices
1. Magento\Weee\Block\Sales\Order\Totals
1. Magento\Weee\Block\Adminhtml\Items\Price\Renderer
1. Magento\Weee\Block\Item\Price\Renderer
1. Magento\Swagger\Block\Index
1. Magento\GoogleAnalytics\Block\Ga
1. Magento\Robots\Block\Data
1. Magento\Security\Block\Adminhtml\Session\Activity
1. Magento\Swatches\Block\Adminhtml\Attribute\Edit\Options\Text
1. Magento\Swatches\Block\Adminhtml\Attribute\Edit\Options\Visual
1. Magento\LayeredNavigation\Block\Navigation\FilterRenderer
1. Magento\Persistent\Block\Form\Remember
1. Magento\Backup\Block\Adminhtml\Backup

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
Hello @sivaschenko,

I checked all Blocks class from this issue and all of them have already marked as @api . So should I add additional information or do nothing?
Thanks.
