### ISSUE TITLE
Mark CatalogSearch, Msrp, CustomerBalance, GiftCardAccount, ConfigurableProduct, GiftCard, GroupedProduct and Search blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32051]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\CatalogSearch\Block\Result
1. Magento\CatalogSearch\Block\Advanced\Result
1. Magento\CatalogSearch\Block\Advanced\Form
1. Magento\Msrp\Block\Popup
1. Magento\CustomerBalance\Block\Sales\Order\Customerbalance
1. Magento\CustomerBalance\Block\Adminhtml\Sales\Order\Create\Payment
1. Magento\CustomerBalance\Block\Adminhtml\Sales\Order\Creditmemo\Controls
1. Magento\CustomerBalance\Block\Adminhtml\Customer\Edit\Tab\Customerbalance\Balance
1. Magento\CustomerBalance\Block\Checkout\Onepage\Payment\Additional
1. Magento\CustomerBalance\Block\Account\History
1. Magento\CustomerBalance\Block\Account\Balance
1. Magento\GiftCardAccount\Block\Check
1. Magento\GiftCardAccount\Block\Sales\Order\Giftcards
1. Magento\GiftCardAccount\Block\Adminhtml\Sales\Order\Create\Payment
1. Magento\GiftCardAccount\Block\Checkout\Onepage\Payment\Additional
1. Magento\GiftCardAccount\Block\Account\Redeem
1. Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix
1. Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Summary
1. Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\SelectAttributes
1. Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Bulk
1. Magento\ConfigurableProduct\Block\Adminhtml\Product\Attribute\NewAttribute\Product\Created
1. Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable
1. Magento\ConfigurableProduct\Block\Product\Configurable\AttributeSelector
1. Magento\GiftCard\Block\Sales\Order\Item\Renderer\Noquote
1. Magento\GroupedProduct\Block\Cart\Item\Renderer\Grouped
1. Magento\GroupedProduct\Block\Product\Grouped\AssociatedProducts
1. Magento\GroupedProduct\Block\Product\Grouped\AssociatedProducts\ListAssociatedProducts
1. Magento\Search\Block\Term

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
Hello @sivaschenko,

I checked all Blocks class from this issue and all of them have already marked as @api . So should I add additional information or do nothing?
Thanks.
