### ISSUE TITLE
Mark AdminNotification, Multishipping and other blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32053]
The following blocks should be marked as API in 2.5-develop branch

1. Magento\AdminNotification\Block\Window
1. Magento\AdminNotification\Block\ToolbarEntry
1. Magento\AdminNotification\Block\System\Messages\UnreadMessagePopup
1. Magento\GoogleAdwords\Block\Code
1. Magento\GoogleOptimizer\Block\Code\Product
1. Magento\GoogleOptimizer\Block\Code\Category
1. Magento\Marketplace\Block\Partners
1. Magento\Multishipping\Block\Checkout\Addresses
1. Magento\Multishipping\Block\Checkout\Results
1. Magento\Multishipping\Block\Checkout\Overview
1. Magento\Multishipping\Block\Checkout\Billing
1. Magento\Multishipping\Block\Checkout\Success
1. Magento\Multishipping\Block\Checkout\Link
1. Magento\Multishipping\Block\Checkout\Shipping
1. Magento\Multishipping\Block\Checkout\Billing\Items
1. Magento\Multishipping\Block\Checkout\Address\Select
1. Magento\Sitemap\Block\Robots
1. Magento\Ups\Block\Backend\System\CarrierConfig

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by vlmed** [comment]
Hello @sivaschenko,

I checked all Blocks class from this issue and all of them have already marked as @api . So should I add additional information or do nothing?
Thanks.
