### ISSUE TITLE
Mark Newsletter, Review, PageCache, Tax, Payment, Contact, Shipping and ImportExport Blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32050]
The following Blocks should be marked as API in 2.5-develop branch

1. Magento\Newsletter\Block\Subscribe
1. Magento\Newsletter\Block\Adminhtml\Subscriber
1. Magento\Newsletter\Block\Adminhtml\Problem
1. Magento\Newsletter\Block\Adminhtml\Template\Edit
1. Magento\Newsletter\Block\Adminhtml\Queue\Edit
1. Magento\Review\Block\Adminhtml\Rss\Grid\Link
1. Magento\Review\Block\Customer\Recent
1. Magento\Review\Block\Customer\ListCustomer
1. Magento\Review\Block\Product\Review
1. Magento\Review\Block\Product\View\Other
1. Magento\PageCache\Block\Javascript
1. Magento\PageCache\Block\System\Config\Form\Field\Export
1. Magento\Tax\Block\Sales\Order\Tax
1. Magento\Tax\Block\Adminhtml\Items\Price\Renderer
1. Magento\Tax\Block\Adminhtml\Rate\Toolbar\Add
1. Magento\Tax\Block\Item\Price\Renderer
1. Magento\Payment\Block\Transparent\Redirect
1. Magento\Payment\Block\Transparent\Form
1. Magento\Contact\Block\ContactForm
1. Magento\Shipping\Block\Items
1. Magento\Shipping\Block\Tracking\Link
1. Magento\Shipping\Block\Tracking\Popup
1. Magento\Shipping\Block\Adminhtml\Create\Form
1. Magento\Shipping\Block\Adminhtml\Create\Items
1. Magento\Shipping\Block\Adminhtml\Order\Tracking
1. Magento\Shipping\Block\Adminhtml\Order\Packaging
1. Magento\Shipping\Block\Adminhtml\Order\Tracking\Invoice
1. Magento\Shipping\Block\Adminhtml\Order\Tracking\View
1. Magento\Shipping\Block\Adminhtml\View\Form
1. Magento\Shipping\Block\Adminhtml\View\Comments
1. Magento\Shipping\Block\Adminhtml\View\Items
1. Magento\Shipping\Block\Order\Shipment
1. Magento\ImportExport\Block\Adminhtml\Import\Edit\Before
1. Magento\ImportExport\Block\Adminhtml\Import\Frame\Result
1. Magento\ImportExport\Block\Adminhtml\Form\After

**Comment by vlmed** [comment]
@magento i am working on this

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by ProkopovVitaliy** [comment]
@sivaschenko all of the mentioned classes already marked as api in this commit `a6e43abdcecce2b063b314aae73cede677c029bc`.

**Comment by sivaschenko** [comment]
Thanks for checking @ProkopovVitaliy ! I will review the list of blocks for all the tasks
