### ISSUE TITLE
Data migration tool - killed

### ISSUE THREAD

**Issue by chris-brabender** [magento/magento2#3206]
I am attempting to migrate from 1.7.0.2 to EE2.0.2 using the data migration tool.

Executing this command: php bin/magento migrate:data -r /path-to/vendor/magento/data-migration-tool-ee/etc/ce-to-ee/1.7.0.2/config.xml

**Results in this error:**

`[INFO][mode: data][stage: data migration][step: Map Step]: started
85% [=======================>----] Remaining Time: 7 mins Killed`

It ran for around 45-50 minutes before that error was thrown.

**Attempting a re-index after results in:**

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.store_id' in 'field list', query was: SELECT`catalog_product_entity`.`entity_id`,`catalog_product_entity`.`store_id`,`catalog_product_entity`.`value`FROM`catalog_product_entity`WHERE (attribute_id = 98)`
- Customers are migrated across (and visible in the admin panel)
- Categories are migrated across (and visible in the admin panel) with products assigned to them
- Products are visible in the category assignment tab however navigating to Products > Catalog results in this error:
- Orders are in the sales_order table but do not show in the grid

`SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: SELECT COUNT(DISTINCT main_table.attribute_id) FROM`eav_attribute`AS`main_table`
 INNER JOIN`eav_entity_type`AS`entity_type`ON main_table.entity_type_id = entity_type.entity_type_id
 INNER JOIN`eav_entity_attribute`ON main_table.attribute_id = eav_entity_attribute.attribute_id
 INNER JOIN``AS`additional_table`ON main_table.attribute_id = additional_table.attribute_id WHERE (`entity_type_code`= 'catalog_product') AND (`additional_table`.`is_used_in_grid`= 1)`

Any ideas as to why it is failing or where I can get detailed information as to why (eg: where it outputs logs to, why no error messages were thrown etc).

**Comment by SantyagoSeaman** [comment]
Hello!
Can you run 'dmesg | grep php' and provide results?

**Comment by chris-brabender** [comment]
Hi @SantyagoSeaman , dmesg | grep php helped actually, thank-you. It showed the virtual machine was running out of memory. So I've upped that allocation and it runs better now.

I am getting new errors now though on the url_rewrite document

```
[Migration\Exception]  
  Volume Check failed   
```

And when trying to index:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.store_id' in 'field list', query was: SELECT `catalog_product_entity`.`entity_id`, `catalog_product_entity`.`store_id`, `catalog_product_entity`.`value` FROM `catalog_product_entity` WHERE (attribute_id = 98)
```

And still getting this error on the Catalog page in admin

```
Syntax error or access violation: 1103 Incorrect table name '', query was: SELECT COUNT(DISTINCT main_table.attribute_id) FROM `eav_attribute` AS `main_table`
INNER JOIN `eav_entity_type` AS `entity_type` ON main_table.entity_type_id = entity_type.entity_type_id
INNER JOIN `eav_entity_attribute` ON main_table.attribute_id = eav_entity_attribute.attribute_id
INNER JOIN `` AS `additional_table` ON main_table.attribute_id = additional_table.attribute_id WHERE (`entity_type_code` = 'catalog_product') AND (`additional_table`.`is_used_in_grid` = 1)
```

**Comment by chris-brabender** [comment]
Managed to fix the last two issues.

The column not found was related to some catalog price rules that failed to come across and were causing issues.

The last issue appears related to - https://github.com/magento/data-migration-tool-ce/issues/48 which should hopefully be addressed with - MAGETWO-47928

As a temporary workaround I updated the eav_entity_type table and set the additional_attribute_table column value to catalog_eav_attribute where entity_type_code = catalog_product.

**Comment by andidhouse** [comment]
Hi Chris,

we are facing also some problems migrating from 1.7.0.2 to 2.0.
Did you edit the table in the migrated magneto 2 database or the 1.7 one?
Many thanks!

"As a temporary workaround I updated the eav_entity_type table and set the additional_attribute_table column value to catalog_eav_attribute where entity_type_code = catalog_product."

**Comment by chris-brabender** [comment]
@andidhouse I updated the new Magento 2 database.

**Comment by maksek** [comment]
Please use forums for questions, GitHub only for bugs and PR related to Magento 2 code.

**Comment by chris-brabender** [comment]
@maksek this wasn't a question, it is a bug with the migration tool, please re-open.

**Comment by maksek** [comment]
The repo is for Magento2 code. There is separate repo for data migration tool, if you can create issue with concrete step to reproduce team will work on it.  In the repo - you will not have answer of fix.
