### ISSUE TITLE
Mark Inventory interfaces and blocks as API

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32067]
The following interfaces and blocks should be marked as API in api-changes-develop branch

1. inventory/InventoryApi/Model/IsProductAssignedToStockInterface.php
1. inventory/InventoryCatalogApi/Model/SourceItemsProcessorInterface.php
1. inventory/InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequest/ResolverInterface.php
1. inventory/InventoryIndexer/Indexer/SelectBuilderInterface.php
1. inventory/InventorySalesAdminUi/Model/SalesChannelNameResolverInterface.php
1. inventory/InventorySalesApi/Model/GetSkuFromOrderItemInterface.php
1. inventory/InventorySalesApi/Model/ReturnProcessor/Request/ItemsToRefundInterface.php
1. inventory/InventorySalesApi/Model/StockByWebsiteIdResolverInterface.php
1. Magento\InventoryShippingAdminUi\Block\Adminhtml\Shipment\Inventory
1. Magento\InventoryShippingAdminUi\Block\Adminhtml\Order\View\ShipButton

**Comment by ProkopovVitaliy** [comment]
@magento i am working on this

**Comment by engcom-November** [comment]
Hi,
This issue got fixed in the scope of the internal Jira ticket AC-1050 and has been merged to [api-changes-develop](https://github.com/magento/inventory/tree/api-changes-develop)  branch
Commit id: e4406290483ff6e3f34cb2932aa3ef6772cc7b8a
Based on Jira, target version is 2.4.4
