### ISSUE TITLE
'contentUpdated' event listener isn't always created due to a race condition

### ISSUE THREAD

**Issue by navarr** [magento/magento2#32068]
### Preconditions
1. Magento 2.3.6
1. Utilize a JavaScript bundling system (our system uses Advanced Bundling)
2. Utilize a theme based on theme-frontend-blank
3. Ensure your bundling system is loading the requirejs config in an element in the <head>
4. mage/mage should be loaded in the same file that applies the requirejs config

### Steps to reproduce
1. Load a webpage
2. Place a breakpoint on `$("body").on("contentUpdated", function() {`
2. Hard refresh the webpage

**NOTE**: This does not always work due to a race condition

### Expected result
1. `document.getElementsByTagName('body').length` is 1

### Actual result
1. In some cases, `document.getElementsByTagName('body').length` is not 1

### Technical Notes
In environments where there are fewer JavaScript files that can be loaded fast enough, `mage/mage` can be triggered quick to execute before a `<body>` tag exists in the DOM.

This is due to it being a dependency of, at least, `Magento_Theme/js/theme` in the blank theme - which is set as a global dependency by the `requirejs-config.js` file in that theme.

Previous ticket was reported in 2017: #10360 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
i think we can go change to $(html) or $(document) should be fine for apply call

**Comment by engcom-Hotel** [comment]
Hi @navarr ,

We had tried to reproduce this issue in the following way:
Step 1: Use advance javascript bundling using below command:
`php -f bin/magento config:set dev/js/enable_js_bundling 1`
Step 2: Clean the cache
Step 3: Tried to open the Homepage (Theme : Luma)
Step 4: Apply the breakpoint in mage.js on L88 ($('body').on('contentUpdated', function () {)
Step 5: Hard refresh the page 10 times. 

Out of the 10 times 3 times breakpoint was not hit. So issue is reproducible. 

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42655` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
