### ISSUE TITLE
Azure Blob storage integration 

### ISSUE THREAD

**Issue by MourIdri** [magento/magento2#32074]
Hi we have our magento on Azure , is it possible to bring also a storage media for Azure blob storage ?

like the one for s3 ?
https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html

**Comment by mindcurv-vishnu** [comment]
I also want this

**Comment by mahgo** [comment]
Is this added? It is marked as Done, but I can't see any documentation on this.
