### ISSUE TITLE
setup:static-content:deploy fails with errors which makes no sense

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32075]
### Preconditions (*)

1. 2.4.1 (i had this bug with any version since I started with magento 2)

### Steps to reproduce (*)

If I execute `php bin/magento setup:static-content:deploy` then I get alot of errors like:

    Compilation from source: /home/company/staging.company.de/app/design/frontend/company/fresh/web/css/source/_mixins/fx.less
    variable @theme__color__primary is undefined in file /home/company/staging.company.de/var/view_preprocessed/pub/static/frontend/company/fresh/de_DE/css/source/_mixins/fx.less in fx.less on line 3, column 12
    1| .link_hover {
    2|     cursor: pointer;
    3|     color: @theme__color__primary;
    4|     text-decoration: underline;
    5|     text-decoration-color: @theme__color__primary;
    6| }

It says that `@theme__color__primary` is undefined in the file fx.less,
so I checked if that is true:

This is my _extend.less file:

    // Variables
    @import 'lib/extend/variables/_layout';
    @import 'lib/extend/variables/_colors';
    
    @import '_variables/elements/button';
    @import '_variables/responsive';
    @import '_variables/icons';
    @import '_variables/colors';                     // <-- @theme__color__primary is defined here
    @import '_variables/header';
    @import '_variables/typographie';
        // Extensions
        @import '_variables/amasty/checkout';
    
    // Mixins
    @import '_mixins/fonts';
    @import '_mixins/fx';                            // <-- Error is getting thrown here
    @import '_mixins/elements/button';

As you can see, the file `_variables/colors.less` which contains the variable is loaded before _mixins/fx.less, so why is the error thrown?

**_variables/colors.less**

    @defaultBackgroundColor: #EFF1F2;
    @color-company-orange-alt: #FF7712;
    @theme__color__primary: @color-company-orange-alt; 

### Expected result (*)

It should compile without errors

### Actual result (*)

It throws errors.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
If I am using `grunt refresh` in a environment with deploy mode set to developer , then it works without any errors. Why does it fail in production mode with `php bin/magento setup:static-content:deploy -f` ?

**Comment by hostep** [comment]
Does it fail on a particular theme? Maybe `Magento/blank` ?
I've seen failures like that which can happen when you try to use a variable defined in a custom theme from inside a module, then compiling the `Magento/blank` theme will break since it doesn't know that variable.

Magento's SCD command compiles your custom theme + its parent themes, so that could be a possible explanation here.
This behavior can be changed in Magento 2.4.2 btw, where you can specify a new `--no-parent` flag which got introduced by https://github.com/magento/magento2/pull/30090

Not sure if this is helpful though, I'm not a frontend developer, so I might be mistaken here

**Comment by Eddcapone** [comment]
@hostep, I figured it out that the bug is related to the filename. I have to add an underscore `_` in front of the files where the problem occurs. I am confused as why this is necessary and why I never had to do this when using `grunt refresh`.

So I changed `_variables/colors.less` to `_variables/_colors.less` **and** `_mixins/fx` to `_mixins/_fx.less`

I am puzzled why the filename caused the bug, I was not able to find anything about it in the documentation.

I hope someone from the magento team can answer this, maybe the bug is unknown to them.

**Comment by Mereep** [comment]
> [@hostep](https://github.com/hostep), I figured it out that the bug is related to the filename. I have to add an underscore `_` in front of the files where the problem occurs. I am confused as why this is necessary and why I never had to do this when using `grunt refresh`.
> 
> So I changed `_variables/colors.less` to `_variables/_colors.less` **and** `_mixins/fx` to `_mixins/_fx.less` Of course I also changed it in the file `_extend.less`
> 
> I am puzzled why the filename caused the bug, I was not able to find anything about it in the documentation.
> 
> I hope someone from the magento team can answer this, maybe the bug is unknown to them.

Thanks you, you saved my day. Got random `file is empty` errors and variable not found errors. Completely unrelated to anything, as the files were neither empty nor was the variable not defined.  This error seems to happen only on some environments, as I can deploy without underscore on the renamed files on my local machine happily.

This seems to be a undocumented quirks / bug happening still on `Magento CLI 2.4.7-p4`

**Comment by Eddcapone** [comment]
The question still remains. Where is the documentation for the underscore prefix for the style filename?
