### ISSUE TITLE
ArrayIterator incompatible method current() php 7.4

### ISSUE THREAD

**Issue by jeroenkosse** [magento/magento2#32088]
### Preconditions (*)

1. Version 2.4.1 and previous releases with support for php 7.4
2. Environment should use php >= 7.4

### Steps to reproduce (*)

1. Invoke the \Magento\Catalog\Block\Product\ListProduct::initializeProductCollection function on a product page with a product with categories
2. Following line will be executed: $this->setCategoryId(current($categories->getIterator())->getId()); 

### Expected result (*)

1. I expect the id from the first category from the product

### Actual result (*)

1. Error is returned because you call getId() on null.
2. From php >= 7.4 the current() method is no longer returning the first item from a ArrayIterator and instead returns null
3. More informations about this incompatible change can be found on phpdoc ( https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.spl )

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mamsincl** [comment]
confirmed using 2.4.2 with php7.4

switching back to php7.3 temporarily solved the issue

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41398` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @jeroenkosse. Thank you for your report. 
The issue has been fixed in magento/magento2#32389 by @mamsincl in 2.4-develop branch
Related commit(s):
 - [e5b3bb3e9d379b22c643d5db3108c2a1df14aa81](https://github.com/magento/magento2/commit/e5b3bb3e9d379b22c643d5db3108c2a1df14aa81)
 - [b13fcbb5e6f30d5952267ca64d2006b9c62a6cbc](https://github.com/magento/magento2/commit/b13fcbb5e6f30d5952267ca64d2006b9c62a6cbc)

The fix will be available with the upcoming 2.4.3 release.
