### ISSUE TITLE
Don't log customers out, after they change their password

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32081]
### Description (*)

I noticed that you are getting logged out, if you are changing your password as a customer.
This makes no sense to me.

### Expected behavior (*)

Don't log users out if they have changed the password.

### Benefits

Users can proceed shopping without having to log in again.
They might find it too exhausting and rather leave the site.

### Additional information

-

**Comment by johnspostsalotfishing** [comment]
No, no this is a dreadful idea. Imagine your customer finds out they've been hacked, someone's in their account. They change their password but the hacker is still allowed to do whatever they like because they're still logged in. Really bad idea. 0/10, security nightmare.

**Comment by Eddcapone** [comment]
Thank you @johnspostsalotfishing , now it makes sense.
