### ISSUE TITLE
Not able to install magento-module-staging-page-builder with composer install

### ISSUE THREAD

**Issue by mfchk** [magento/magento2#32098]
Got 404 Error, seems the repo has been disappear? Will it be back soon? Thanks
```
 The "https://repo.magento.com/archives/magento/module-staging-page-builder/magento-module-staging-page-builder-2.1.0.0.zip" file   
  could not be downloaded (HTTP/1.1 404 Not Found)        
```

**Comment by johncy65** [comment]
@mfchk Did you find the solution to this? I'm having the same issue

**Comment by mfchk** [comment]
Hi @johncy65 , Its resolved after I login a new credential that included magento enterprise package (administrator paid for it).
So its false alarm, we can close this ticket.

**Comment by johncy65** [comment]
Hey @mfchk, I used a different approach to revolve this issue. The credentials were already present in the auth.json file. For some reason composer wasn't picking it up. I deleted that file and added the creds as an environment variable. After that, all the dependencies got resolved.

**Comment by ihor-sviziev** [comment]
Thank you for confirming that that was an issue with credentials. I'm closing this issue.

**Comment by ivanaugustobd** [comment]
Same here, and regenerating the keys worked too. Just a question, why the hell the repo return 404 instead of 403 in those cases? That's confusing and frustrating, an "access denied" or even a "credentials expired" would much more intuitive..

**Comment by ivanaugustobd** [comment]
Seems to be a pretty old issue: https://github.com/magento/magento2/issues/2419

**Comment by jonatanaxe** [comment]
> Parece ser um problema muito antigo: [# 2419](https://github.com/magento/magento2/issues/2419)

normal kkk

**Comment by ivanaugustobd** [comment]
Also here: #2416
