### ISSUE TITLE
Media Gallery doesn't show any product images

### ISSUE THREAD

**Issue by Kishorchhugani** [magento/magento2#32104]
### Preconditions (*)

1.Install Fresh Magento 2.4.1

### Steps to reproduce (*)

1.Set No to Enable Old Media Gallery option in Advanced->System  section in system configuration
2.go to content ->media gallery

### Expected result (*)

1. All images should be display

### Actual result (*)

1. No images are displaying in the media gallery

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @Kishorchhugani. Thank you for your report!
After disabling the old gallery, you need to run the following commands:

- Set No to Enable Old Media Gallery option in Advanced->System section in system configuration;
- Run in console `php bin/magento media-gallery:sync`;
- Run in console `php bin/magento media-content:sync`;

Once synchronization is complete, all images should be displayed in the gallery.
@Kishorchhugani Could you check it?
Thanks!

**Comment by Kishorchhugani** [comment]
thank you now its working ..all images are there

**Comment by jegit23** [comment]
> Hi @Kishorchhugani. Thank you for your report! After disabling the old gallery, you need to run the following commands:
> 
> * Run in console: `php bin/magento media-gallery:sync`;
> * Run in console: `php bin/magento media-content:sync`;
> 
> Once synchronization is complete, all images should be displayed in the gallery. @Kishorchhugani Could you check it? Thanks!

Thanks for the solution, may I ask if this way will increase the storage space of all previous images? same or double, thanks. We having the same issue today since upgrading Magento 2.4.3 to 2.4.3-p3, everything is working fine but the Media Gallery shows nothing.
