### ISSUE TITLE
swaches are not filtering issue for configurable product

### ISSUE THREAD

**Issue by sprajapat770** [magento/magento2#32105]
Magento 2.4.0 not filtering Swaches of Configurable product Website Wise so simple product assigned to different website are also rendered with configurable product in.

### Preconditions (*)

1. You should have Two Websites on Same Magento 2.4.0.
2. Should Have Configurable Product And Two Simple Product Variations.
3. Swatch Attribute and Assigned to Simple Products also.

### Steps to reproduce (*)

1. create two websites in magento 2
2. create 1 configurable product and create more than two Configurations of simple products
3.  assign Configurable product to both websites 
4. assign both simple products to each websites and check in storefront.
![image](https://user-images.githubusercontent.com/57035224/107612208-be017880-6c6b-11eb-88dd-471d90190d9f.png)
![image](https://user-images.githubusercontent.com/57035224/107612220-c2c62c80-6c6b-11eb-83a1-374b8cadf23b.png)
![image](https://user-images.githubusercontent.com/57035224/107612284-eb4e2680-6c6b-11eb-89cb-74a686eb9250.png)
![image](https://user-images.githubusercontent.com/57035224/107612327-06209b00-6c6c-11eb-97a8-0cf3c16ee8c2.png)

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/57035224/107612499-66afd800-6c6c-11eb-8792-cc6b1cb22c5a.png)
![image](https://user-images.githubusercontent.com/57035224/107612527-75968a80-6c6c-11eb-925d-7c1bd02934c2.png)

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/57035224/107612418-3a945700-6c6c-11eb-9e79-10f3775d4882.png)
![image](https://user-images.githubusercontent.com/57035224/107612452-4bdd6380-6c6c-11eb-93aa-92487b69dbef.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40860` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by SilinMykola** [comment]
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
issue is not reproducible and can be closed.
![admin_configurable_product](https://user-images.githubusercontent.com/15772032/115398038-647b7400-a1ef-11eb-9b0d-361e6f44a4ae.jpg)
![admin_products](https://user-images.githubusercontent.com/15772032/115398041-66453780-a1ef-11eb-8298-37f95a61d1b8.jpg)
![product_in_web1](https://user-images.githubusercontent.com/15772032/115398044-66ddce00-a1ef-11eb-84e2-ddfa9abdee40.jpg)
![product_in_web2](https://user-images.githubusercontent.com/15772032/115398046-66ddce00-a1ef-11eb-8437-dd0d0112e983.jpg)

**Comment by atwixfirster** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @sprajapat770,

As per this comment https://github.com/magento/magento2/issues/32105#issuecomment-823244501 we are closing this issue.

Thanks.
