### ISSUE TITLE
Support S3 Compatible Storage

### ISSUE THREAD

**Issue by griffithg** [magento/magento2#32114]
### Description (*)
As a site admin I would like to be able to use my S3 compatible storage (ex. MinIO) in the same way I use AWS S3 storage.

### Expected behavior (*)
If I am using AWS S3 nothing changes. If I want to use S3 API compatible storage there would be a config option to provide a URL and a option to enable path style endpoints.

### Benefits
It would give those of us hosting on-prem the ability to use the S3 compatible storage systems we already have available instead of going to AWS.

### Additional information
From my testing it seems to come down to adding a couple config options to the factory and then working out the config options. Wasn't sure if this was on the roadmap internally. Should it be a separate module or an enhancement to the AwsS3 module.

**Comment by barryvdh** [comment]
It would basically be adding an optional endpoint condig5 (eg like in https://flysystem.thephpleague.com/v1/docs/adapter/digitalocean-spaces/ ) and an option to determine the url, right?

**Comment by griffithg** [comment]
Yes.
I was trying MinIO out by adding:
`      $config['endpoint'] = 'https://someurl';  `                   
`      $config['use_path_style_endpoint'] = true/false;   `
to createConfigured in AwsS3Factory.php

The second option is needed to allow for the use of url/bucket instead  of bucket.url in environments where DNS can't be or isn't set for all the buckets.

Haven't gotten as far as adding config options yet. Mostly since they are defined in the Remote Storage module and wasn't sure where the more appropriate place to define the new options would be.

**Comment by dverkade** [comment]
Open issues should not be closed automatically. Posting a comment here to remove the stale issue label.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43046` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
