### ISSUE TITLE
bin/magento i18n:collect-phrases -m String Eval Error

### ISSUE THREAD

**Issue by DevBinnooh** [magento/magento2#3211]
After installing magento2 and executing command:
bin/magento i18n:collect-phrases -m

It will generate error:
PHP Parse error:  syntax error, unexpected 'Gateway' (T_STRING), expecting ';' in /path/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php(276) : eval()'d code on line 1
Parse error: syntax error, unexpected 'Gateway' (T_STRING), expecting ';' in /path/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php(276) : eval()'d code on line 1

Caused by unescaped single quote while trying to get php strings.

A fix will be proposed.

**Comment by mazhalai** [comment]
@DevBinnooh this has already been fixed in 2.0.1, which branch did you try on? 

Since it has been fixed internally, we wont be able to accept your PR. Related internal tickets: MAGETWO-47301 and MAGETWO-48541

**Comment by MomotenkoNatalia** [comment]
@DevBinnooh  Internal ticket MAGETWO-47301 is closed and delivered to mainline. Please let us know if you still have an issue.
