### ISSUE TITLE
Module Store dependancy on module MessageQueue

### ISSUE THREAD

**Issue by sashas777** [magento/magento2#32127]
The module store should have dependency on MessageQueue because it uses:
```
\Magento\Framework\MessageQueue\PoisonPill\PoisonPillPutInterface
```
https://github.com/magento/magento2/blob/2.3/app/code/Magento/Store/Model/Store.php#L413

Currently it is only depends on framework:
https://github.com/magento/magento2/blob/2.3/app/code/Magento/Store/composer.json
which doesn't have Magento\Framework\MessageQueue

### Preconditions (*)
1.  Copy last version of Module_Store in empty folder

### Steps to reproduce (*)
1. Run composer install

### Expected result (*)
 
1. There is folder vendor/magento/framework-message-queue/ 

### Actual result (*)
1. The folder vendor/magento/framework-message-queue/ does not exist

**Comment by sashas777** [comment]
This is not resolved per https://github.com/magento/magento2/issues/28289

**Comment by engcom-Delta** [comment]
Hi @sashas777  thank you for your report. 
Could you clarify what issue you are experienced? Real case would be helpful
Is issue reproducible on clean 2.4-develop?

**Comment by sashas777** [comment]
@engcom-Delta 
Hi,
The issue comes when you use this module for unit tests or declare dependency of this module. Also, it would fail OOTB integrity tests from /dev/ folder. 

As you can see for 2.4 as well the class: 
https://github.com/magento/magento2/blob/2.4/app/code/Magento/Store/Model/Store.php#L391 
uses another class from the module MessageQueue (magento/framework-message-queue) and this module not listed as a dependency at the composer.json of Magento_Store module (https://github.com/magento/magento2/blob/2.4/app/code/Magento/Store/composer.json).
 
The resolution would be to add to Magento_Store module's composer.json dependency for "magento/framework-message-queue"

**Comment by sashas777** [comment]
@engcom-Delta  here is example of the change: https://github.com/sashas777/magento2/commit/065ee9f0b0e53cb90b13480a1b5b01079f795ce5
