### ISSUE TITLE
Bom dia!!!Trabalho como o Magento integrado a SkyHub, e estou com problemas ao consumir os pedidos, tem demorado muito tempo o ultimo pedido esta disponível para sincronizar e ainda não foi consumido 

### ISSUE THREAD

**Issue by Kaorionline** [magento/magento2#32138]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi Kaorionline 
Issue should be described on english for further investigation
Please feel free to reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are able to reproduce this issue on the latest `2.4-develop` branch. Thank you for collaboration.
