### ISSUE TITLE
A logical issue in the \Magento\Ui\Component\AbstractComponent::__construct() method: the UI components are registered before their initialization

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3213]
https://mage2.pro/t/391

**Comment by veloraven** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
