### ISSUE TITLE
Deploying Static Files. Could not parse theme static file

### ISSUE THREAD

**Issue by diegorkable** [magento/magento2#3214]
Hey guys,

I am trying to deploy static files in my magento website that I just installed (2.0.2), I use the command: 

> php -f bin/magento setup:static-content:deploy en_US

And it gives me the following error:

`Could not parse theme static file 'C:/Program Files (x86)/Zend/Apache2/htdocs/ma
gento202/vendor/magento/theme-frontend-blank/web/css/email-fonts.less'>`

I found the file and it's there... what shall I do?

**Comment by diegorkable** [comment]
help?

**Comment by mazhalai** [comment]
@diegorkable can you turn on developer mode and see if you get a more extensive stack-trace?

**Comment by diegorkable** [comment]
@mazhalai Still the same...

That's what I did:

> C:\Program Files (x86)\Zend\Apache2\htdocs\magento202\bin>php -f magento deploy:
> mode:set developer
> Enabled developer mode.
> 
> C:\Program Files (x86)\Zend\Apache2\htdocs\magento202\bin>php -f magento setup:s
> tatic-content:deploy
> Requested languages: en_US
> Could not parse theme static file 'C:/Program Files (x86)/Zend/Apache2/htdocs/ma
> gento202/vendor/magento/theme-frontend-blank/web/css/email-fonts.less'>

**Comment by diegorkable** [comment]
@mazhalai Also to note, when I enter the website there are only links and sentences, it isn't placed well and half of the pictures are gone.

**Comment by mazhalai** [comment]
@diegorkable the css and js is missing, thats why the website dosent look right.

We are having trouble reproducing this issue. Can you please give us more details: How did you deploy magento? Also what version of PHP?

**Comment by TienYiChi** [comment]
I'm also having this problem now. My project (CE 2.0.2) is installed on osx el capitan with php5.6.10.

error message under developer mode:
`Could not parse theme static file '<project dir>/vendor/magento/theme-frontend-blank/web/css/_styles.less'`

I haven't found what in the front-end site was affected though.

**Comment by openmagecz** [comment]
Also having the same issue on Windows 10 using EasyPHP DEVSERVER. Everything done using this tutorial from Amasty - https://blog.amasty.com/how-to-install-magento-2-php7-localhost/ - but getting also "_Could not parse theme static file .../vendor/magento/theme-frontend-blank/web/css/email-fonts.less_". In frontend and backend, all icons are broken. Some idea? Have bought EasyPHP to be able to check different Magento 2 versions on my laptop, but can´t work with none of those... even with PHP 7.0,2, 7.0.6 or 7.0.11.

**Comment by veloraven** [comment]
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by reillo** [comment]
For those who are having issues with this. Kindly see my commits on how to fix it.

At this time of writing. My pull request is not merged yet, so there are two solutions that you can do for now.

First, apply the changes I made in this commit:
https://github.com/magento/magento2/pull/13344/commits/11bf138f142e16ee2fb2ce8fe7dfb948838d4191

Second, move your Magento application away from parent folder that has special characters that can cause issue with regular expression. I.e if you put it under `C:/Program Files (x 82)`, then you need to move it away and adjust your virtual host.
