### ISSUE TITLE
magento 2.3 when you click 'send email' you get a message 'You sent the order email.'

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#32148]
When you click 'Send Email' on this page adminuo/sales/order/view/order_id/140/key/xxx/

This is an incorrect message. The message is not send, the sending is scheduled not?

**Comment by f1-outsourcing** [comment]
this[1] works for me, and here[2] they write that magento 2.3 is still using the php mail function. So I do not know why these mails are not going out. I have even reverted back to original/default templates of magento, but still no luck.

Thus, I do not know how you can generate a message with a green check mark, when in fact the message is not send.

php -r "mail('test@example.com','theme','body');"


[1]
https://github.com/magento/magento2/issues/20033#issuecomment-484414998

[2]
https://github.com/magento/magento2/issues/20033#issuecomment-532289611

[3]
[2021-02-12 18:14:02] main.ERROR: Unable to send mail: Unknown error [] []
[2021-02-12 18:14:28] main.ERROR: Unable to send mail: Unknown error [] []

**Comment by engcom-Delta** [comment]
Hi @f1-outsourcing thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Create simple product 
- Create custome
- Place order as customer
- Go to Sales->Orders
- Click View link for order
- Click **Send Email**

**Result:**
:heavy_check_mark: Success message "You sent the order email." is shown
![image](https://user-images.githubusercontent.com/51681379/107943596-9b39d180-6f95-11eb-98a7-2cbb91f2b0c0.png)
:heavy_check_mark: Customer receive order confirmation email
![image](https://user-images.githubusercontent.com/51681379/107943896-0388b300-6f96-11eb-8b44-1f5ebd0250b9.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.

**Comment by f1-outsourcing** [comment]
> 
> 
> Hi @f1-outsourcing thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
> **Manual testing scenario:**
> 
>     * Create simple product
> 
>     * Create custome
> 
>     * Place order as customer
> 
>     * Go to Sales->Orders
> 
>     * Click View link for order
> 
>     * Click **Send Email**
> 
> 
> **Result:**
> heavy_check_mark Success message "You sent the order email." is shown
> ![image](https://user-images.githubusercontent.com/51681379/107943596-9b39d180-6f95-11eb-98a7-2cbb91f2b0c0.png)
> heavy_check_mark Customer receive order confirmation email
> ![image](https://user-images.githubusercontent.com/51681379/107943896-0388b300-6f96-11eb-8b44-1f5ebd0250b9.png)
> 
> Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
> if you are still facing this issue on the latest `2.4-develop` branch.


Did you have this in your log file "main.ERROR: Unable to send mail: Unknown error "?

I guess not,  thus you have tested totally different situation. And since I did not mention what I did to get this message, you can maybe conclude that I have no idea what config setting it could have been. That means you have to ask a developer under what circumstances this message is being generated, so you can apply these to your test. 
Then I am confident that you will be able to reproduce it.

Besides you should never use 'sent' but 'scheduled', because it goes in your queue and if the cron does not run, the message is simply not sent. You can only use sent when the MTA reports back the message has correctly been received (obviously).
