### ISSUE TITLE
Magento 2.3.x and 2.4.x API product search with sort by price does not work properly

### ISSUE THREAD

**Issue by OxCom** [magento/magento2#32144]
https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1740

and

https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php#L81

Order by **price_index.min_price = 0** cause issue on API requests when we have store ID > 0: 
Any product with price = 0 will be sorted in the end of the list. So, when we request products list with API we have all free products in the end of the list. API call for all stores are fine.

Affected versions:
 - Magento CE 2.3.x
 - Magento CE: 2.4.x
 - Magento CE: 2.5.x-dev

**Update**
Issue can be visible on frontend when user applies sorting by price for any of categories that has free and paid products. All free products appears in the end of the list

**Comment by engcom-Delta** [comment]
Hi @OxCom thank you for your report. 
Could you add the example of API call you used, actual and expected results?

**Comment by OxCom** [comment]
@magento give me 2.3-develop instance

**Comment by OxCom** [comment]
Magento should have paid and free products with only one store, so API call for products list without filters will return products list.

Issue not does not exists with **all** stores call
```
/rest/all/V1/products?searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=price&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=ASC
```
Issue reproducible  with default store call
```
/rest/V1/products?searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=price&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=ASC
```

With provided filters we should have (**expected**) products sorted by price and products with 0 price should be on a first place.
**Current**: free products are in the end of the list

**Comment by OxCom** [comment]
Any update on the issue?
There is invalid SQL query that make not possible to use ordering by price in API for default store.
```sql
SELECT ...
FROM   ...
ORDER BY field = 0
```
The ```field = 0``` will be interpreted as as TRUE when the price is zero, and as we have no provided order direction then it will be sorted in ascending order by default.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42031` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by OxCom** [comment]
Branch 2.5-dev also affected by the issue

**Comment by OxCom** [comment]
Any update on the issue?

**Comment by OxCom** [comment]
Based on latest changes in 2.4-dev branch issue can be closed
