### ISSUE TITLE
Style is not getting compiled

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32149]
### Preconditions (*)

2.4.2
Production Mode

### Steps to reproduce (*)

I try to compile my code from my build system.

I don't know how we can reproduce it, today it worked the whole day but suddenly it fails.

    php bin/magento setup:di:compile
    php bin/magento setup:static-content:deploy en_US de_DE
    
    git add pub/static/
    git add pub/media/
    git add generated/
    git commit -m "Update Static Files"
    git push

    cd ~/staging    // Same branch checked out
    php bin/magento maintenance:enable
    git pull
    php bin/magento cache:clean
    php bin/magento maintenance:disable

------------------

### Expected result (*)

If I load the frontend then the changes I made in dev should be visible in staging after deployment.

### Actual result (*)

Changes are not there.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
There is only one workaround. You can trigger the build if you change from deploy mode `production` to `developer` and then back to `production`. This will trigger the compilation.

There is a major bug somewhere in `setup:static-content:deploy` and I have to change my deploy script to this until it gets fixed:

```
php bin/magento deploy:mode:set developer
php bin/magento deploy:mode:set production

git add pub/static/
git add pub/media/
git add generated/
git commit -m "Update Static Files"
git push

cd ~/staging    // Same branch checked out
php bin/magento maintenance:enable
git pull
php bin/magento cache:clean
php bin/magento maintenance:disable
```

**Comment by mrtuvn** [comment]
one note production mode must run static content deploy but developer mode not require it
Most important command is run setup:upgrade for get sync. 
In developer mode you don't have run all commands. For daily work i just only use setup:upgrade (my Frontend task for update styles). For uncommon task may need to change workflow
In production you have to run all commands

**Comment by ihor-sviziev** [comment]
@Eddcapone
Actually before executing `php bin/magento setup:static-content:deploy` command you should delete var/view_preprocessed, pub/static/* (deployed version file, frontend and adminhtml folders). usually `php bin/magento setup:upgrade` Command does it.

**Comment by mrtuvn** [comment]
:green_check_mark:

**Comment by Eddcapone** [comment]
I was following this guide from the [documentation about pipeline deployment](https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/example/shared-configuration.html), and it does not mention that we have to execute setup:upgrade.

**Comment by mrtuvn** [comment]
Before compile code by command setup:di:compile you should run setup upgrade first. Use this for both Dev or production

**Comment by Eddcapone** [comment]
I changed my deploy script to this:

```
php bin/magento setup:upgrade
php bin/magneto setup:di:compile
php bin/magento setup:static-content:deploy de_DE en_US

git add pub/static/
git add pub/media/
git add generated/
git commit -m "Update Static Files"
git push

cd ~/staging    // Same branch checked out
php bin/magento maintenance:enable
git pull
php bin/magento cache:clean
php bin/magento maintenance:disable

```

The style changes were still not applied.

**Comment by Eddcapone** [comment]
I also tried this

```
php bin/magento setup:upgrade
php bin/magneto setup:di:compile
php bin/magento setup:static-content:deploy
```

The style changes were still not applied.

**Comment by Eddcapone** [comment]
Pls wait. I have to test again. I forgot something.

**Comment by Eddcapone** [comment]
It was my fault, I forgot to commit a file, it works with:

```
php bin/magento setup:upgrade
php bin/magneto setup:di:compile
php bin/magento setup:static-content:deploy
```

I will create an issue in the documentation and explain that there is a step missing.

Thank you very much @mrtuvn and @ihor-sviziev
