### ISSUE TITLE
phpunit --filter is not working

### ISSUE THREAD

**Issue by BlackIkeEagle** [magento/magento2#3215]
example:

vendor/bin/phpunit --configuration=dev/tests/unit/phpunit.xml.dist --filter Magento\Setup\Test\Unit\Console\Command\CronRunCommandTest
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/website/dev/tests/unit/phpunit.xml.dist

Time: 30.33 seconds, Memory: 530.00Mb

No tests executed!

**Comment by Vinai** [comment]
instead of using `--filter`, you can just specify the file path to the test (or directory) to run.
I think the problem is that you would have to escape the backslashes.

**Comment by BlackIkeEagle** [comment]
the file alone does not work:

```
vendor/bin/phpunit setup/src/Magento/Setup/Test/Unit/Console/Command/CronRunCommandTest.phpPHPUnit 4.1.0 by Sebastian Bergmann.

...Segmentation fault (core dumped)
```

even with configuration it does not work

```
vendor/bin/phpunit --configuration=dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/Console/Command/CronRunCommandTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/website/dev/tests/unit/phpunit.xml.dist

...Segmentation fault (core dumped)
```

I've never had to escape the namespaced stuff with --filter before (just tested it and it also gives me no result)

**Comment by Vinai** [comment]
Strange, running the exact same command works file for me:

``` bash
$ vendor/bin/phpunit --configuration=dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/Console/Command/CronRunCommandTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /Volumes/CaseSensitive/Workspace/mage2katas/mage2-ce/dev/tests/unit/phpunit.xml.dist

..........

Time: 171 ms, Memory: 8.25Mb

OK (10 tests, 42 assertions)
```

Tried on PHP 5.6.16 and PHP 7.0.2
What PHP version are you using?

**Comment by Vinai** [comment]
Regarding the variant with the `--filter` option, the following works for me:

``` bash
vendor/bin/phpunit --configuration=dev/tests/unit/phpunit.xml --filter 'Magento\\Setup\\Test\\Unit\\Console\\Command\\CronRunCommandTest'
```

If I only use a single backslash or omit the quotes I also get "No tests executed".

**Comment by BlackIkeEagle** [comment]
the above test was run on a ubuntu trusty box

```
php -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

**Comment by Vinai** [comment]
Can you try on a different PHP version?

**Comment by BlackIkeEagle** [comment]
Yes, but not immediatly

**Comment by Vinai** [comment]
Also works on 

```
$ php --version
PHP 5.5.31 (cli) (built: Jan  8 2016 08:36:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with uopz v2.0.7, Copyright (c) 2014, by Joe Watkins <krakjoe@php.net>
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by Vinai** [comment]
If I recall correctly, xdebug `2.2.3` had some issues. Maybe upgrading or disabling it will help.

**Comment by BlackIkeEagle** [comment]
@Vinai thanks for the support. I'll check with my php 7.0.2 box and try later with an up2date php5 in my trusty box.

**Comment by BlackIkeEagle** [comment]
Ok confirmed it must be an issue related to the version we are having in ubuntu. with php 7.0.2 I get no more segfault.

thanks
