### ISSUE TITLE
Undefined index: PK_CMS_PAGE in /home/mydomain/public_html/mysite/vendor/magento/framework/EntityManager/EntityMetadata.php on line 96

### ISSUE THREAD

**Issue by shakshigithub** [magento/magento2#32155]
Hi all,
We are struggling with an issue in Magento.
My Magento website is successfully running in local server but when I am uploading it on server it shows me this errror or notice kind of.
Undefined index: PK_CMS_PAGE in /home/mydomain/public_html/mysite/vendor/magento/framework/EntityManager/EntityMetadata.php on line 96

My hosting server is A2hosting, 
And magento version is 2.3.3 
We got to know it can be a version issue from your hosting server.
Please let us know whether it is a hosting server magneto version issue or something else in database or magento files.

Feel free to offer solution as we are struggling a lot due to this issue.

Thank you in advance!

**Comment by shakshigithub** [comment]
Magento I am working on this

**Comment by engcom-Delta** [comment]
Hi @shakshigithub , thank you for your report. 
Could you steps to reproduce issue ?
Is this issue reproducible on clean 2.4-develop?

**Comment by krishprakash** [comment]
Hi @shakshigithub. Feel free to reopen the issue once you confirm that issue reproduce on latest magento 2.4-develop instance with proper reproducible steps
Thanks!!
