### ISSUE TITLE
$.event.props is undefined

### ISSUE THREAD

**Issue by adrianalin89** [magento/magento2#32159]
### Preconditions (*)

Magento CE 2.4.1 using PHP 7.3

### Steps to reproduce (*)

I'm using Windows 10 usgin Fireforx  86.0b9 64bit / Chrom 88.0.4324.150 / Opera 74.0.3911.107
It's not really Browser related.
It's not something that I can constantly get I mostly get it hard-refreshing the website.
It gives me this js error:
jquery.mobile.custom.js:50 
Uncaught TypeError: Cannot read property 'concat' of undefined
    at jquery.mobile.custom.js:50
    at jquery.mobile.custom.js:529
    at jquery.mobile.custom.js:15
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)
    at Module.emit (require.js:1155)
I've try to update to the latest version of jQuery core / Migration  and Mobile and the issue has gone away. But the admin has broken :D So I had to revert it all back.

### Expected result (*)

Well, I was expecting to not have this error when jQuery fail to initiate and break the rest of the site functionality.

### Actual result (*)

The actual result is the message above that in a way means the Jquery was not loaded and because of that all the rest of the jQuery script stoped.

---
Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
Well is all the jQuery is not working then the site is pretty useless I call that hay severity.
Also the site is live and in production, you can check out the error on https://emersonscigars.com

**Comment by adrianalin89** [comment]
@magento give me 2.4-develop instance

**Comment by adrianalin89** [comment]
As expected was not able to replicate it. I will start disabling module to find where the error is coming from.

**Comment by mrtuvn** [comment]
Seem not related with magento! I think you have use custom jquery version
This maybe not compatible jquery lib (jquery mobile)
Note that magento current use jquery 1.12 (quite long period)
https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/jquery.min.js#L1

**Comment by adrianalin89** [comment]
![image](https://user-images.githubusercontent.com/39235439/107953515-e9ee6800-6fa3-11eb-9be5-d41816998ff4.png)
I have run a grep command in all the app folder for "jquery" and there is no other lib require of jquery. 
Also just noticed that this is happening only in the production mod.

**Comment by adrianalin89** [comment]
Please close this issue. The client was loading a script from Shopper Approved that was loading jquery 3
