### ISSUE TITLE
incorrect(?) assumption on cron execution security

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#32150]
The questions that was asked:
"Is it possible to use wget instead of php in cron for Magento 2?"
the answer from adobe:
"I think the answer to the question is straightforward - no, you cannot use wget instead of php in cron in Magento 2. And we are not likely to add this by default due to security ramifications."

Please explain. Because running the code under the website user is in my opinion more secure than as a user account. Php even advices to use disable_functions to disable shell execution. (because that bypasses the openbasedir).
Running the cron job via wget/curl allows for php restrictions to be in place, like limit execution time, like the openbase dir.
The command line does not have that at all. How can that be more secure.

The webuser has been configured and secured to execute website scripts and user/shell accounts are not configured to execute website scripts. 

I would flag this issue as high. Because if this assumption is indeed incorrect, you have implemented exactly the opposite, and chosen the less secure implementation.

https://community.magento.com/t5/Just-Ask-Alan/Is-it-possible-to-use-wget-instead-of-php-in-cron-for-Magento-2/m-p/25418/highlight/true#M155

https://community.magento.com/t5/Installing-Magento-2-x/Is-it-possible-to-use-wget-instead-of-php-in-cron-for-Magento-2/m-p/468515#M9476

**Comment by f1-outsourcing** [comment]
So Adobe does not care about magento security? I always had the impression that adobe was shitty with programming and security ever since this flash debacle. Is it not time you invest more money in better development? Just writing some dumb arguments of the use of cron does not make it secure. Get someone professional to look at this.

**Comment by Penchal-magento** [comment]
Hi @f1-outsourcing : It is not an issue , magneto no longer support wget url  and actually its customized logic.

**Comment by engcom-Alfa** [comment]
Hi @f1-outsourcing 
The suggested logic is customizable and Magento cron job doesn't support the wget-url. Hence it is not treated as issue.

**Comment by f1-outsourcing** [comment]
@engcom-Alfa 

> The suggested logic is customizable 
I do not get what you mean by this.

Magento 1.9 supported scheduled tasks to be ran via a wget request. Your developers threw that away for all the incorrect arguments, they created something that is less safe.

**Comment by ihor-sviziev** [comment]
Hi @f1-outsourcing,
Unfortunately, providing an ability to run the cron jobs using wget / curl might cause some additional issues due to the nature of running the cron jobs. Usually, they're running way longer than web requests.

For instance, with Magento 1 we had many issues when some running cron jobs were killed (which led to some issues) in the middle due to request timeout. From my perspective, Magento shouldn't support it out of the box. If you really need it - you could implement it yourself for you or do some open-source module.

Thank you for understanding!

**Comment by engcom-Lima** [comment]
Hi @f1-outsourcing,

Sorry to say, Magento ver. dev-2.4-develop does not support which you are looking. If you needed then you can customise the feature as per your requirements or check some open source module. Hence, closing this ticket if you have any other issue then you can raise the new ticket.

Thanks for the understanding!

**Comment by f1-outsourcing** [comment]
@ihor-sviziev 


> Unfortunately, providing an ability to run the cron jobs using wget / curl might cause some additional issues due to the nature of running the cron jobs. Usually, they're running way longer than web requests.
> 
> For instance, with Magento 1 we had many issues when some running cron jobs were killed (which led to some issues) in the middle due to request timeout. 

And that is how it should be, because the server admin decides how many resources / cpu time the task gets. Besides the argument you are giving is not really an argument. If you code nicely with exceptions you would know where the previous job ended and the new should start. That being said, this is of course not something to be implemented by rookie programmers.

>From my perspective, Magento shouldn't support it out of the box. If you really need it - you could implement it yourself for you or do some open-source module.
> 

Your perspective seems to be from "to difficult to realize". I think that such argument is not really allowed being magento/adobe. 
From my perspective your current design is wrong. For instance why not allow order/sales emails to be configured to go out directly, why do they first need to go to cron? For small stores good enough.
I am more and more getting the impression your strategy lacks vision, direction and experience. A good example for this is this ini values and database existence testing (which were good in 1.9)  and the lack of consistent logic in arguments. 

I would research what my largest install base looks like, and focus on making that work. I wonder even if your application is going to do well in container environments, I have my doubts. You get that this is going to be the future not?

Do you discuss these types of issues with your team lead? Or are you just closing issues when you are annoyed and criticized? ;)

**Comment by Den4ik** [comment]
@f1-outsourcing What task do you prefer run via wget?
I'm agree with @ihor-sviziev that it's not good idea run all schedule tasks via wget/curl because they could be longtime. It's badly affect to user experience. And I'm not sure that it should be available in core.

**Comment by f1-outsourcing** [comment]
Hi @Den4ik I prefer to run via wget scheduled order/invoice emails. I have no idea what other tasks can be scheduled also. But I want these emails to go out instantly.

You have to think about that at some point in the future your magento instance is going to be ran in a container.  So that means no local shell access no local cron. With your current solution that would mean you have to create and run a 2nd container to run these scheduled tasks. I would not even know how to make it, because most containers run in foreground and that process is monitored by the OC, so the OC will restart it when it fails. So you have to fall back on some cron framework that executes such tasks on specific times, but there you have to problem that you need to have the whole fs structure and mysql login available to run the scheduled magento tasks. Which is not that trivial to implement.
The easiest solution would be running a cron job with a wget to the container, and that would execute what ever needs to be executed, and that all happens within the resource limits a user has configured, as it should be.

**Comment by ihor-sviziev** [comment]
@f1-outsourcing,
Unfortunately, there a lot of different cron jobs are running. There are email sending, quotes cleanups, async indexing, some CRONs from 3rt party extensions, and much more. From the first look, it looks pretty simple, but sometimes it's not.

Even with email sending, there could be different limits - sending 1 email is for sure faster than sending 50 emails, especially when you send emails with 3rt party service, and this service has some temporary service slowdown.
I'm pretty sure you don't expect to have process kill in the middle of sending emails and lose the state of which emails were sent and which weren't, and having such an issue in a loop - means emails will be sent again and again.

Again, if you need such custom implementation - you can develop such a logic yourself or look for custom extensions. Maybe some of them could provide such an ability.

If you're talking about containers, you can run cron jobs in a separate container, as well as message queue runners.
