### ISSUE TITLE
Update laminas-mail to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32164]
Update laminas/laminas-mail version to "^2.13.0".

The change should be done in php8-develop branch.
composer.json and composer.lock files should be updated in https://github.com/magento/magento2 and https://github.com/magento/partners-magento2ee repositories.
In case of backwards-incompatible changes the client code should be adjusted

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39671` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
