### ISSUE TITLE
New modules doesnt installed !

### ISSUE THREAD

**Issue by elbasri** [magento/magento2#32165]
### Summary of the issue
new modules wont installed on magento 2.3-5 p
even the module is installed by Magento CLI, setup:uprade command run without errors (compile, deploy, cache flush..), but the module doesnt apear in the admin or system config !
note1: the app/etc/config.php contain the correct value ("vendor_module" = 1)
note2: not just new modules but there are many plugins work before this problem, but its not work now

### Steps to reproduce (*)
the current magento version is 2.3-5 p
the problem occured when migrate to new server and upgrade the theme (with its plugins)

### Expected result (*)
the module should installed so it should appear in the config scope in the admin.

### Actual result (*)

the module installed from the cli, but its show an error on: https://site/setup/index.php#/module-grid :

![image](https://user-images.githubusercontent.com/11248380/107962646-7b130e00-6fa7-11eb-8e25-d01e2fb070f4.png)

thank you

**Comment by engcom-Delta** [comment]
Hi @elbasri thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop. All modules are installed and works. 
This issue is related to your custom module. 
Please refer to extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Comment by elbasri** [comment]
> Hi @elbasri thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop. All modules are installed and works.
> This issue is related to your custom module.
> Please refer to extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page


Hi,
thank you for your reply,
not, it's not related to my module, I tested many modules but with the same issue, I don't know if it exists in 2.4 but already mentioned that I use 2.3-5 p, not 2.4 !
however, I find the solution.. and for those who have the same problem, please check your PHP version used in CLI is the same as the FPM, and make sure that APC is installed and added in both php.ini files (PHP fpm and CLI).
