### ISSUE TITLE
Website with NOT default inventory source fails on layered navigation attribute filter

### ISSUE THREAD

**Issue by way2ecommerce** [magento/magento2#32183]
### Preconditions (*)
1. Magento CE 2.3.6 (fresh install)

### Steps to reproduce (*)
1. Create new website / store / store view (e.g. website2)
2. Create new inventory source (e.g. source2) (from Stores > Inventory > Sources)
3. Create new Stock and assign the new created website and source (from Stores > Inventory > Stock)
4. Create new filtrable Attribute (e.g. attribute1) (or use manufacturer attribute) and add some options
5. Assign attribute to default attribute set
6. Create category (e.g. "Cat 1")
7. Create product, assign category, set values to attributes, and Assign Source (**not default source**), add qty, in stock, and enable all websites
8. Reindex all

### Expected result (*)
1. The product should be shown on the new website when in the category we filter by any of the options created

### Actual result (*)
1. The filter options have a correct product count, but when we click it does not return the product in the list.

Some screenshots:
![imagen](https://user-images.githubusercontent.com/28978936/108058944-0a2a2f80-7055-11eb-9a82-8c2ca4af5352.png)

![imagen](https://user-images.githubusercontent.com/28978936/108058965-131b0100-7055-11eb-85ee-9f79832ab417.png)

---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Alfa** [comment]
Hi @way2ecommerce   .
Looks like this issue related to MSI functionality.
@sdzhepa Could you move this ticket to the Inventory repository?
Thanks!

**Comment by way2ecommerce** [comment]
Done.. https://github.com/magento/inventory/issues/3279
Thanks!

**Comment by engcom-Alfa** [comment]
We will close this problem because а ticket has already been created in the inventory repository.
