### ISSUE TITLE
Multistore not working after upgrading from 2.3.5-p1 to 2.4.2

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#32197]
### Preconditions (*)

1.  Magento 2.3.5-p1
2.  PHP 7.3.27

### Steps to reproduce (*)

1. I upgraded from 2.3.5-p1 to 2.4.2 via composer
2. Changed the PHP-version form 7.3.27 to 7.4.15
3. Replaced the htaccess files for the other websites with the version that came with Magento 2.4.2

After upgrading the extra websites (not the default one) are redirected to de the default scope of the defult website.

One of my index.php files of the non-default websites:
`<?php
 
require realpath(__DIR__) . '/app/bootstrap.php'; // path of root magento bootstrap.php 
$params = $_SERVER;
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = '*WebsiteCode*';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website'; 
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
    
$app = $bootstrap->createApplication('Magento\Framework\App\Http');
$bootstrap->run($app);`

My .htaccess
`RewriteEngine on
RewriteCond %{REQUEST_URI} !^/pub/
RewriteCond %{REQUEST_URI} !^/setup/
RewriteCond %{REQUEST_URI} !^/update/
RewriteCond %{REQUEST_URI} !^/dev/
RewriteRule .* /pub/$0 [L]
DirectoryIndex index.php`

I checked the websitecode and it is the correct one.

I checked the settings in the backend under Stores => Configuration => General => Web, the correct URL's are still there.

I use symlinks for the folder app, lib, pub and var.

### Expected result (*)

1. Website projected that belongs to the domain.

### Actual result (*)

1. Redirected to the default website

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mtjweb** [comment]
Could this problem being caused because the document root isn't set to the pub folder? I'm using Centos Webpanel and am not able to change the document root in the Vhosts file.

**Comment by mtjweb** [comment]
Problem is solved, I added the following to .htaccess.

SetEnvIf Host ^(.*)huepfburggeblaese\.de MAGE_RUN_CODE=websitecode
SetEnvIf Host ^(.*)huepfburggeblaese\.de MAGE_RUN_TYPE=website

**Comment by engcom-Delta** [comment]
Hi @mtjweb  thank you for your report.
According [docs](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_apache.html#ms-apache-vhosts) multistore could be configured by virtual hosts
Is this issue solved and could be closed?

**Comment by mtjweb** [comment]
Hi @engcom-Delta,

Yes, the problem is resolved. This issue can be closed.

**Comment by engcom-Delta** [comment]
Issue was closed according [comment](https://github.com/magento/magento2/issues/32197#issuecomment-784013958)
