### ISSUE TITLE
multiple discount rules gives wrong discount

### ISSUE THREAD

**Issue by JoostWan** [magento/magento2#32190]
1. Magento 2.3.6

### Steps to reproduce (*)

1. Create a price rule that gives €15 discount for whole shopping cart. 
2. Create a price rule with a coupon that gives 15% discount to a specific product. 
3. Add a product in the cart. 
4. Add a product in the cart that apply rule from step 2. 
5. Apply price rule from step 2 with coupon

We have subtotal off 45,90 in this case. Discount for whole cart is € 15. Discount for the second product is 15% of that product (19,95) that's 2,99. So total discount should be 17,99. But Magento shows that the discount is 17,01

<img width="1283" alt="Screenshot 2021-02-16 at 14 42 35" src="https://user-images.githubusercontent.com/5435412/108070837-436a9b80-7065-11eb-88cb-0e9d5b8fe04c.png">

**Comment by engcom-Bravo** [comment]
Hello @JoostWan 

Thank you for your report.

Can you please help us to reproduce the issue by answering the following:

- What Tax **Rate Percent** is applied in this particular order?
- What setting is set under _Stores - Configuration - Sales - Tax - Calculation Settings - Apply Discount on Prices_?
- How did you create a _price rule with a coupon that gives 15% discount to a specific product_? If possible, please provide screenshots.

This would really help us to process with the issue.
Thank you in advance

**Comment by JoostWan** [comment]
@engcom-Bravo 

- Tax is 21% (Dutch)
- Stores - Configuration - Sales - Tax - Calculation Settings - Apply Discount on Prices? -> **Including Tax**

<img width="853" alt="Screenshot 2021-02-18 at 14 50 55" src="https://user-images.githubusercontent.com/5435412/108366482-b5bfb500-71f8-11eb-8df9-72ad999f892a.png">

**Comment by jamie-selesti** [comment]
@JoostWan This looks similar to the bug I raised yesterday - https://github.com/magento/magento2/issues/32351 - Do you think its linked?

**Comment by krishprakash** [comment]
Hi @JoostWan. Looks similar issue #32351 already added and verified 
So track the progress on same
Thanks!!
