### ISSUE TITLE
Value is not getting changed if it gets loaded from another less variable

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32208]
### Summary (*)

Value is not getting changed if it gets loaded from another less variable

### Examples (*)

I copied the file **vendor\magento\magento2-base\lib\web\css\source\lib\variables\\_layout.less** to my theme at **THEME\web\css\source\lib\variables\\_layout.less**.

Then I changed the value of `@layout-column__sidebar-width` to a very high value, just to see if the change is taking effect.
This should change the sidebar width for example in catalog_category_view

**Before**

```
//  Variables for layout columns
@layout-column__width: @total-columns;
@layout-column__sidebar-width: 2;
@layout-column__left-width: @layout-column__sidebar-width;
@layout-column__right-width: @layout-column__sidebar-width;
```

**After**

```
//  Variables for layout columns
@layout-column__width: @total-columns;
@layout-column__sidebar-width: 123;
@layout-column__left-width: @layout-column__sidebar-width;
@layout-column__right-width: @layout-column__sidebar-width;
```

The sidebar width did not changed at all.

So I tried this instead:

```
//  Variables for layout columns
@layout-column__width: @total-columns;
@layout-column__sidebar-width: 2;
@layout-column__left-width: 123;
@layout-column__right-width: 123;
```

It should not make a difference, since it is the same logic, but this worked!
So less does seem to have a problem with variables receiving the value of another variable?
Is this a less bug or maybe a magento bug?

------------

I also outputed the value in the frontend like this and it is `5` instead of `123`:

```
@layout-column__sidebar-width: 123;
@layout-column__left-width: @layout-column__sidebar-width;
@layout-column__right-width: @layout-column__sidebar-width;

main { test: @layout-column__left-width; }    // <--- DEBUG VALUE
```

![image](https://user-images.githubusercontent.com/16349349/108265792-8b72e680-7169-11eb-9672-3c3f4925aa46.png)

Is there an explanation for this?

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
It's because that value is override in another file so basically your value in file variables is unusable

Value defined in this file have higher priority
https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/luma/web/css/source/_theme.less#L52

**Comment by mrtuvn** [comment]
> So less does seem to have a problem with variables receiving the value of another variable?
It's true

**Comment by Eddcapone** [comment]
Thank you @mrtuvn , I copied the file **vendor\magento\theme-frontend-luma\web\css\source\_theme.less** to **THEME\web\css\source\_theme.less** and changed the value, that worked! 

I was not aware that values can get overwritten later. I though it it like in javascipt:

```
var x = 1;
var y = x;
document.write(y);  // Output: 1
x = 2;
```


But in less it works like this:

```
@foo: 1;
@bar: @foo;
main { test: @bar; }    // Output: 2
@foo: 2;
```

Thank you again!
