### ISSUE TITLE
Inherit from Luma - Functionality issues.

### ISSUE THREAD

**Issue by cvpportraits** [magento/magento2#3220]
Hi, first I wanted to state that I was told luma wasn't meant to be used in production... but... it is a great starting point and would love to use it as a base, so... 

new Magento2 installation, went through a whole series of learning where I could not figure out why my default head blocks xml wasn't working to load my custom css/js files... as per the new theme in the documentation.

After re-going over the code, there was nothing wrong... by trial & error,

I figured out that if I made my new theme inherit from magento/blank, then my custom css & js would load... but if I inherit from magento/luma, it would not... so... my question is HOW can I use the Luma theme and then just modify it to suit needs, it's a great starting point, and would cut out weeks of development if we could use this.

So, I created a new theme, and inherited from luma...

`<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>CVPStyle4</title>
    <parent>Magento/luma</parent>
    <media>
        <preview_image>media/preview.jpg</preview_image>
    </media>
</theme>`

hen I go and regenerate static files via deploy, and my theme is in the backend, and I activate it and it looks like luma, but it does NOT load my custom css/js files, or anything in the default_head_blocks.xml

inside: **app > design > frontend > myvendor > mytheme > Magento_Theme > layout**

and here's my code in that xml:

` 
    <css src="css/cvpstyle.css" />

```
<!--Before-After Script-->
<link src="js/jquery.twentytwenty.js"/>
<link src="js/jquery.event.move.js"/>

<!--Font Awesome-->
<css src="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" src_type="url" />`
```

and no matter how I do it, it will not load and work.

How can I inherit from luma and add some css/js to customize it?
note

I have tried copying the entire luma theme from:

**vendor > magento > theme-frontend-luma** and then changing the name and such in composer.json, registration.php, and theme.xml - theme sort of loads, (doesn't look quite right) - and STILL won't load any custom CSS/JS from the default_head_blocks.xml

any thoughts? I'd really like to use luma as a base. Thank
(I have a stackexchange request for help too, but there seems to be not many people there)

really hoping someone can help with this!

**Comment by alankent** [comment]
I checked with the PM's more recently, and they said aim is now _to_ allow people to inherit from Luma. We might need to clean up a few things over time to make this "nicer" (including some new features in Magento itself), but it is a goal. So sorry for any misinformation earlier (which could have been from me).

I am waiting for any feedback on a Gulp proposal at http://alankent.me/2016/01/27/gulp-et-al-in-magento-2/, and am desperately trying to finish off an e-book covering this topic. Something quick and dirty however for you right now in case it helps:
1. Using pre-blog post approach (relies on Magento's //@magento_import feature - works but not Gulp friendly).

**theme.xml**

```
    <theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
      <title>Luma Modified</title>
      <parent>Magento/luma</parent>
    </theme>
```

**web/css/source/_extend.less**

```
    body {
      background-color: #fff6e5;
    }
```

Being not Gulp friendly, I am moving towards creating a new CSS file as you describe. I have to race right now, so not tested, but I think the following is how to move forwards:

**web/css/orange.css**

```
    body {
      background-color: #ff7f00;
    }
```

**Magento_Theme/layout/default.xml**

```
    <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation
            ="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
      <head>
        <css src="css/orange.css"/>
      </head>
    </page>
```

Less files you just use orange.less as the filename, and we will compile Less to CSS for you.

The thing I need to check still is whether I should be putting a "Vendor_Module::" prefix in front of the CSS file name to make Less compilation happen - I have not tried pushing all the way to deployment (just about to head out the door - I will try later). In one context I think it was required to get the file pushed through in all tools (which felt like it might be a bug, but I have not had time to track it down yet).  That is, try `<css src="Magento_Theme::css/orange.css">` and put the css/less file under the Magento_Theme directory, like the layout file is.

Sorry for not having something more definitive - I will hopefully have a look later today in more detail. I am working on examples like this right now - trying to adjust them to be friendly to the Gulp proposal blog post.

**Comment by cvpportraits** [comment]
Thank you, I really appreciate your help with this. =]
I am not familiar with Gulp. 

Basically I'm willing to try whatever... I will follow directions as specifically as possible.
Magento is obviously complex, I'm really close to having it functioning, the only things I need left is to be able to override some of Luma's CSS, and add a few global JS files.. that, and something like IWD one page checkout if they can make it for 2.0 - and that's literally all I need. - so close, yet so far.

**Comment by alankent** [comment]
When you do view source, do you see any of the markup? Is it present but not working? Or is it not present in the returned HTML?

Note: JS files should be added via RequireJS (I have not actually tried this myself yet). http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html

Also, for the font, if the markup is present but not working, could it be something like cross site scripting protection? You are doing a HTTPS request to a different domain name. Have you tried making the font local so it sits within the same domain name? See also http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/using-fonts.html

**Comment by cvpportraits** [comment]
I didn't see the markup when it was not working, no... but now I have since managed to get it working, inheriting from luma, with the script and css called in default_head_blocks.xml.

the only thing now I am working through is the order of that, it appears that the jquery script from magento is being loaded async or defer, so that the other jquery script I put in the head is being loaded before it, causing it not to work, but I'm sure I can work through that!

thank you so much for your help! you certainly helped me to work through this challenge and get to a point where I can build my storefront now!

**Comment by alankent** [comment]
I am not really a front end developer, but my understanding is for JS that by using requireJs you can declare dependencies to make sure things get loaded in the right order. From the requireJs docs: "If you do not express the dependencies, you will likely get loading errors since RequireJS loads scripts asynchronously and out of order for speed."

Some further reading:
- http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html
- https://firebearstudio.com/blog/advanced-development-with-requirejs-magento-2-tutorial.html
- http://inchoo.net/magento-2/custom-javascript-in-magento-2-with-requirejs/
- https://rohitguptadotco.wordpress.com/2015/09/24/requirejs-in-magento2-basics/

But sounds like you are all good, so closing off this request.

**Comment by MomotenkoNatalia** [comment]
I close the issue for now. If you have further question to this issue please feel free to reopen

**Comment by alankent** [comment]
Oh, one more source of reading data is now available - I just released a **personal** effort (evenings), a Kindle ebook on theme development tackling CSS, HTML, and basic JavaScript. See http://alankent.me/gsd/ for more details.
