### ISSUE TITLE
Messages are not displayed in store with sub path base url

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [magento/magento2#32219]
Success and error messages are not displayed if Magento has its base url configured in a sub path.

### Preconditions (*)
1. Configure a base url with a sub path (example: https://magento.com/sub/)
2. Copy/paste `pub/index.php` to `pub/sub/index.php` on the server (and replace `/../app/bootstrap.php` by `/../../app/bootstrap.php` in the `pub/sub/index.php` file)

### Steps to reproduce (*)
1. Go to the contact page (https://magento.com/sub/contact/ in our example)
2. Submit the contact form

### Expected result (*)
1. The success message should display after sending the contact message

### Actual result (*)
1. No success message is displayed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Yonn-Trimoreau** [comment]
@magento I am working on this

**Comment by Yonn-Trimoreau** [comment]
https://github.com/magento/magento2/pull/32220

**Comment by Yonn-Trimoreau** [comment]
@magento add to contributors team

**Comment by Yonn-Trimoreau** [comment]
@magento I am working on this

**Comment by Yonn-Trimoreau** [comment]
@magento give me 2.4-develop instance

**Comment by Yonn-Trimoreau** [comment]
It is not reproducible on the Magento instance provided since it requires a file modification in pub directory.

**Comment by engcom-Bravo** [comment]
Hi @Yonn-Trimoreau,

The Related PR has been closed.Hence We are Closing this issue.

Please feel free to open the issue.

Thanks.
