### ISSUE TITLE
Products are being disappeared randomly

### ISSUE THREAD

**Issue by zuber903** [magento/magento2#32211]
In Magento 2.3.4, frequently Products are being disappeared from listing page and upon next refresh it works. I checked all possible cases but failed to find out the root cause.

 
Can some share the possible reason / solution for it?

**Comment by GuillaumeBrook** [comment]
I would check the indices of elasticsearch.
Example you see 1000 documents in your indices, you launch a reindexation, you check again the number of documents.
Sometimes there is a drastic change in the number of documents.

**Comment by zuber903** [comment]
I didn't get it. What does that mean? Could you please elaborate? Sorry...

**Comment by GuillaumeBrook** [comment]
If you are using Elasticsearch, you could go on your server and type :
curl -X GET "localhost:9200/_cat/indices"
It will write one index per store, for example : magento2_product_1_v10. (store id 1, version 10)
The 4th column from the right is the number of products inside.

If you launch a reindexation of "catalogsearch_fulltext" your index will be magento2_product_1_v11 (store id 1, version 11).
The important thing is to check if the 4th column from the right has changed a lot or not.

If you don't have access to the server, just do a reindexation in the back-office of "Catalog Search", flush the caches and check  the frontend.

You could also do a reindexation of "catalog_category_product".
