### ISSUE TITLE
Post Migration, no products showing, but layered navigation with qty's

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#3222]
Fresh install of 2.0.2
Migration of 1.9.2 store using offical tool.

When first migrated the store products showed on frontend via correct categories
Tweaked various settings under STORES > CONFIGURATION (i.e payment modules, carriers, tax settings etc) 

Ran: 
Reindex
Deploy static content
Cache Clean
Cron Run 

Products stopped showing on frontend.

I then deleted all the settings directly from DB only left URL options to be able to access the store.

Ran: 
Reindex
Deploy static content
Cache Clean
Cron Run 

Still did not fix; No errors through browser console;

<img width="1213" alt="screen shot 2016-01-31 at 8 35 57 am" src="https://cloud.githubusercontent.com/assets/9780829/12698732/8cbf7bcc-c7f8-11e5-9b97-69bec6a0adbb.png">

**Comment by kandrejevs** [comment]
I'm having same issue, products are in BE, but not showing up in FE, only empty categories

**Comment by surfer190** [comment]
@rkhoury82 Please comment as to why you closed this issue. Did you resolve the problem. Was it just a problem that you had not done a `reindex`
