### ISSUE TITLE
Magento Checkout module Billing address show javascript code 

### ISSUE THREAD

**Issue by chirag-taraviya** [magento/magento2#32227]
### Preconditions (*)

1. Magento 2.4.2
2.php 7.4

### Steps to reproduce (*)

1. Checkout as new customer and add new address. 
2. Payment section show javascript code instead of address 

### Expected result (*)

1. [Screenshots, logs or description]
2.Should be full address

### Actual result (*)

1. [Screenshots, logs or description]
2.![image](https://user-images.githubusercontent.com/531597/108508502-ee878900-72e1-11eb-9a9c-22bffdea5287.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DuySexy** [comment]
issue still exist!!!
