### ISSUE TITLE
Table Rate - Incorrect State Code for Queensland Australia

### ISSUE THREAD

**Issue by ovdev1** [magento/magento2#3223]
Just noticed when trying to load table rates that the directory_country_region table contains the wrong state code for Queensland Australia, should be QLD not QSD

**Comment by vrann** [comment]
@ovdev1 Thanks for reporting! Can you please create pull request to fix it?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Table-Rate-Incorrect-State-Code-for-Queensland-Australia/idi-p/45335).
