### ISSUE TITLE
FilterGroup filters are not processed as OR in Search

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#32236]
### Preconditions (*)
1. Magento 2.4.1 
2. Elastic Search 

### Steps to reproduce (*)
1. Create a custom module with a di.xml 

```
    <type name="Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchCriteriaResolver">
        <plugin sortOrder="1" name="iowebProductDisplaySearchCriteriaResolver"
                type="Ioweb\ProductDisplay\Plugin\Model\ResourceModel\Fulltext\Collection\SearchCriteriaResolverPlugin"/>
    </type>
```

2. Create your plugin
```
<?php
/*
 * Copyright (c) 2021. IOWEB TECHNOLOGIES
 */

namespace Ioweb\ProductDisplay\Plugin\Model\ResourceModel\Fulltext\Collection;

use Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchCriteriaResolver;
use Magento\Framework\Api\FilterBuilderFactory;
use Magento\Framework\Api\Search\FilterGroupBuilderFactory;

class SearchCriteriaResolverPlugin
{

    protected $flag = false;

    protected $filterBuilderFactory;
    protected $filterGroupBuilderFactory;

    /**
     * CollectionPlugin constructor.
     */
    public function __construct(
        FilterBuilderFactory $filterBuilderFactory,
        FilterGroupBuilderFactory $filterGroupBuilderFactory
    )
    {
        $this->filterBuilderFactory = $filterBuilderFactory;
        $this->filterGroupBuilderFactory = $filterGroupBuilderFactory;
    }

    public function afterResolve(SearchCriteriaResolver $subject,
                                 $result)
    {
        if ($this->flag) {
            return $result;
        }

        $fgb1 = $this->filterGroupBuilderFactory->create();
        $fb1 = $this->filterBuilderFactory->create();
        $fb2 = $this->filterBuilderFactory->create();

        $fb1->setField('stock_status')->setValue(1)->setConditionType('eq');
        $fb2->setField('attribute_1')->setValue(1)->setConditionType('eq');

        $fgb1->addFilter($fb1->create());
        $fgb1->addFilter($fb2->create());

        $fg1 = $fgb1->create();
        $fgroups = $result->getFilterGroups();
        $fgroups[] = $fg1;
        $result->setFilterGroups($fgroups);
        return $result;
    }
}
```

3. Visit a category page and you will notice that the filter group is treated as an AND clause. 

### Expected result (*)
1. The filter group is treated as an OR clause. 

### Actual result (*)
1. The filter group was treated as an AND clause

It appears that the function `\Magento\Framework\Search\Search::search`

Is adding filters one by one ignoring the filtergroup part and treating it as separate simple filters. 

```
        foreach ($searchCriteria->getFilterGroups() as $filterGroup) {
            foreach ($filterGroup->getFilters() as $filter) {
                $this->addFieldToFilter($filter->getField(), $filter->getValue());
            }
        }
```

In my use case I need to hide out of stock products unless they have a specific boolean attribute set to yes. 
When using the stock_status filter I get 73 products
When using the attribute_1 filter I get 1 product

When using both in the filter group I get 1 product but I would expect to see 74

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
Not stale

**Comment by engcom-Echo** [comment]
Hi @ioweb-gr,

Can you kindly share the collection query. 

Thanks

**Comment by ioweb-gr** [comment]
Unfortunately I went with a different approach so I can't directly give the query. I have posted though the exact code used for a plugin to replicate the issue. If you need me to send you the query I'll have to do it this weekend when I get some free time to create the environment

**Comment by engcom-Echo** [comment]
hi @ioweb-gr ,

Were you able to get the collection query. Let me know or else I will proceed with my analysis.

Thanks

**Comment by ioweb-gr** [comment]
Unfortunately I wasn't able due to the customizations in place on the website to avoid all MSI issues :(

**Comment by ioweb-gr** [comment]
I do think that the code 

```
        foreach ($searchCriteria->getFilterGroups() as $filterGroup) {
            foreach ($filterGroup->getFilters() as $filter) {
                $this->addFieldToFilter($filter->getField(), $filter->getValue());
            }
        }
``` 

Is pretty self-evident though that the conditions are processed as AND and not as an OR clause though if you read the code segment. 

Because it's taking all filters in the groups and adding them with addFieldToFilter

This same use case has been refactored many times in the past issues in other areas.

**Comment by engcom-Echo** [comment]
Thanks @ioweb-gr , for your explanation.

**Comment by engcom-Lima** [comment]
Hi @ioweb-gr,

I understand your concern but with your use case, I can't confirm the issue based on code only. I'll have to reproduce the actual issue in order to understand fully how it is affecting the search result.

So, that's what I was asking, can you please try to reproduce this based on your plugin code and share the relevant screenshot of unexpected behaviour for the filters ? If you can add the screenshots of **Step 3**, that would be really helpful.

**Comment by engcom-Lima** [comment]
Hi @ioweb-gr,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
