### ISSUE TITLE
Add to Cart broken on lists view with redirect to cart enabled

### ISSUE THREAD

**Issue by jeffyl** [magento/magento2#32232]
### Preconditions (*)

1. Magento 2.4.2
1. Redirect to cart enabled

### Steps to reproduce (*)

1. Fresh Magento 2.4.2 with sample data
1. Enable redirect to cart: https://docs.magento.com/user-guide/sales/cart-redirect.html
1. Go to a list view in any of the categories and try to add an item to cart from that page

### Expected result (*)

1. Add to cart button is enabled after page finishing loading

### Actual result (*)

1. Add to cart button continues to be disabled

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [x] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by jeffyl** [comment]
The issue starts with 95859dc036a6076423f30409f224a6b5d6f5ac84 which defaults the button to be disabled until the catalog-add-to-cart.js is loaded, which enables the buttons. But if you have redirect to cart enabled, require.js never loads that script and so it will not enable the button

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/templates/product/list.phtml#L157

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @jeffyl,
The issue has been reproduced on the Latest Magento 2.4 Instance.
In Admin > Stores > Configuration > Sales > Checkout > After Adding a Product Redirect to Shopping Cart "YES"
In the Front end, the Categories > Product Listing > Add to Cart button is disabled 
**Screenshot:**
![image](https://user-images.githubusercontent.com/24711761/108668289-efe2cc80-7500-11eb-8ffb-3e1c11ab0908.png)

![image](https://user-images.githubusercontent.com/24711761/108668295-f4a78080-7500-11eb-907f-06fa4b8bdcbe.png)

**Expected result:**
The "Add to Cart" button should be enabled.

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40983` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
