### ISSUE TITLE
Magento 2.3.4-p2 issue on changing media_gallery attribute to Global "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribute_id' in 'where clause' query was: DELETE FROM `catalog_product_entity` WHERE (attribute_id = '268') AND (store_id IN(1, 10, 13))"

### ISSUE THREAD

**Issue by arslan-eg** [magento/magento2#32242]
###Summary (*)
Not able to change the product attribute scope from website to Global.
Navigate to  (Admin->STORES->Attributes->Product) edit attribute_code = media_gallery
Then change the attribute scope (ATTRIBUTE INFORMATION -> Properties -> Advanced Attribute Properties -> Scope) change it to website and click on Save Attribute. Now change the scope back to Global and click on Save Attribute. (Not able to change)

###Preconditions (*)
Magento 2.3.4-p2
media_gallery attribute's scope must be Store View or Website.

###Steps to reproduce (*)
In Admin Panel Navigate to  (Admin->STORES->Attributes->Product) search Attribute Code (media_gallery) click on record and edit this attribute. Then change the attribute scope (ATTRIBUTE INFORMATION -> Properties -> Advanced Attribute Properties -> Scope) change it to website and click on Save Attribute (it is working fine). Now change the scope back to Global and click on Save Attribute. (Not able to change)

###Expected result (*)
Should be able to change media_gallery attribute's scope to Global. If its scope is Website or Store View

###Actual result (*)
Not able to change the attribute's scope.
(SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribute_id' in 'where clause', query was: DELETE FROM `catalog_product_entity` WHERE (attribute_id = '268') AND (store_id IN(1, 10, 13)))

Further Details(*)
[Video recording of this issue](https://www.loom.com/share/ec9068b063e94ab2bcb0e5872f5c651d)

**Comment by arslan-eg** [comment]
@magento give me 2.4-develop instance

**Comment by qhdctod** [comment]
I've just run into this issue as well - when changing the scope of an attribute from 'website' to 'global' in Magento 2.3.4

**Comment by kamranzafar1** [comment]
Any solution for this
