### ISSUE TITLE
Magento 2.4.1 New Account Key Confirmation email

### ISSUE THREAD

**Issue by JoergLindner** [magento/magento2#32247]
### Preconditions (*)

1. Magento 2.4.1
2. PHP 7.4.14 
3. After updating to 2.4.1 from 2.3.5-p2 we facing the issue that if a customer open an account, mainly try to open an account, Magento will just send the 'Default' New Account Email, instead of the 'New Account Key Confirmation' email. Of course 'Require Emails Confirmation' is set to 'Yes'. After checking, it basically that it use the 'E-Mail' Template of 'Default Welcome Email'. So the Setting under 'Confirmation Link Email' and 'Welcome Email' (email will be sent instead of the Default Welcome Email, after account confirmation) is completly ignored.  

### Steps to reproduce (*)

1. Enable E-Mail confirmation (set to Yes)
2. Stores->Configuration->Customers->Customer Configuration 
 2a. Default Welcome Email (use Default)
 2b. Default Welcome Email Without Password (use Default)
 2c. Require Emails Confirmation --> YES
 2d. Confirmation Link Email --> Default, New account confirmation key
 2e. Welcome Email --> New Account confirmed
3. Go to 'Create an account' and create account
4. You will receive a E-Mail, but it is the 'Default Welcome E-Mail' instead of the 'New account confirmation key' Email, which weill be received.
5. If a request for resending the confirmation E-Mai request, again only the 'Default Welcome E-Mail' is sent

### Expected result (*)

1. The selected E-Mail Template should be send as selcted under 'Confirmation Link Email' and 'Welcome Email'0

### Actual result (*)

1. Email Template of Default Welcome Email is used

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @JoergLindner . Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop.

**Manual testing scenario:** 
1. Create custom templates for  **_Confirmation Link Email_** and **_Welcome Email_**;
![Screenshot from 2021-02-24 14-13-53](https://user-images.githubusercontent.com/51679138/109000383-50fad380-76ac-11eb-97c6-c5329484f955.png)
2. Go to Admin->Stores->Configuration->Customers->Customer Configuration->Create New Account Options and set:
![2021-02-24_14-15](https://user-images.githubusercontent.com/51679138/109000507-7687dd00-76ac-11eb-92d6-6135ac87de06.png)
3. Go to 'Create an account' and create account;

**Actual Result:** :heavy_check_mark: We received an email with a custom template (_**Custom New Account Confirmation Key**_)

![Screenshot from 2021-02-24 14-18-10](https://user-images.githubusercontent.com/51679138/109000735-c49ce080-76ac-11eb-8570-12feb77cecca.png)
![2021-02-24_14-18](https://user-images.githubusercontent.com/51679138/109000757-c8306780-76ac-11eb-87f2-ee64a54bbada.png)

4. Click on the **Confirm Your Account** button;

**Actual Result:** :heavy_check_mark: We received an email with a custom template (_**Custom New Account Confirmed**_)
![Screenshot from 2021-02-24 14-18-48](https://user-images.githubusercontent.com/51679138/109001047-1cd3e280-76ad-11eb-9018-89a9f5294d76.png)
![2021-02-24_14-19](https://user-images.githubusercontent.com/51679138/109001052-1e9da600-76ad-11eb-80e9-8117d7e6c1c8.png)

Maybe we missed something?
@JoergLindner Could you take a look?
Thanks!

**Comment by JoergLindner** [comment]
This is our settings too. It worked/s on 2.3.5-p2 and after Update to M2.4.1 not. We have MagePlaza SMTP Module installed but there is no issue with it, as this is the same if the Module is disabled! In our case it always just send the 'Default' Welcome Email. As a E-Mail is sent, there is no real 'failure' we can see. If we set the Default to a different Template, the e-mail changes. So the selection, at least for the Default E-Mail works. For us it seems that the  'Require E-Mail confirmation' set to 'Yes' is not handed over to the EMail Handler correctly, for what ever reason. Everything related to EMail works fine, except this single item
