### ISSUE TITLE
Lecgacy model observer on catalog module

### ISSUE THREAD

**Issue by Mecalux-Developer** [magento/magento2#32243]
On the Catalog Module Events XML, there are declared a bunch of observers, whose names starts with "legacy_model_<whatever>".

Seems that those observers are not needed, as the models they are observing are doing exactly the same.

Are those observers still needed?

**Comment by engcom-Delta** [comment]
Hi @Mecalux-Developer thank you for your report.
This issue could be investigated in scope of feature request/code improvement
Could you create issue in [community-features repo](https://github.com/magento/community-features/issues) for further discussion and close this one once it will be done?

**Comment by krishprakash** [comment]
Hi @Mecalux-Developer.
Kindly raise this ticket to [community feature repository](https://github.com/magento/community-features/issues) for further process. Thanks !!
