### ISSUE TITLE
Theme not registering with Varnish/Nginx setup

### ISSUE THREAD

**Issue by raybogman** [magento/magento2#3225]
New theme not registering in M2 (tested on 2.0.0, 2.0.1, 2.0.2) EE

Server setup Nginx/Varnish (default magento config setup) (using magento nginx.conf)

When switching back to apache everything works

After removing varnish from the setup and only using Nginx the probleem still occurred

So there is maybe a issue in the nginx config

**Comment by mazhalai** [comment]
@raybogman is this is production mode? May be related to #2797

**Comment by raybogman** [comment]
@mazhalai in dev mode, using a clean setup (no caching, no static files in pub)

**Comment by oleg-onufer** [comment]
Hi @raybogman.
If this issue is actual for Enterprise Edition only, please address it to Magento Support.
