### ISSUE TITLE
The «Enable Page» checkbox on the backend «Content» → «Pages» → <Page> screen has a wrong vertical alignment 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3226]
![magento2-01](https://cloud.githubusercontent.com/assets/83204/12703628/db8920ae-c858-11e5-8d25-09e9ae1ee9d1.png)

**Comment by zanilee** [comment]
Hi, @dfediuk!

Thank you for reporting this issue. Internal ticket MAGETWO-48772

**Comment by MomotenkoNatalia** [comment]
@dfediuk  Changes are currently in the mainline. Issue can be closed.
