### ISSUE TITLE
Error happened during deploy process: Path %1 cannot be used with directory %2

### ISSUE THREAD

**Issue by faradey** [magento/magento2#32267]
### Preconditions (*)

1. Magento 2.3.6 and Magento 2.4.2
2. Composer 1.10.20

### Steps to reproduce (*)

1. Configuring the loading of modules from local folders.
`{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.2",
    "require": {
        "magento/product-community-edition": "2.4.2",
        "magento/composer-root-update-plugin": "~1.1",
        "extmag/dhlshipping":"*"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.16.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": ">=0.12.3 <=0.12.23",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "~5.0.0",
        "squizlabs/php_codesniffer": "~3.5.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
    	{
            "type": "path",
            "url": "/home/admin/magento-modules/v2/Extmag-Core/Extmag/Core"
        },
        {
            "type": "path",
            "url": "/home/admin/magento-modules/v2/Extmag-DhlShipping/Extmag/DhlShipping"
        },
        {
            "type": "path",
            "url": "/home/admin/magento-modules/v2/Extmag-Shiplab/Extmag/Shiplab"
        },
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
`
2. extmag/dhlshipping depend on extmag/shiplab and extmag/core
3. Modules are in a folder /home/admin/magento-modules/v2/ and magento site is in /mnt/B6BCC155BCD11111/ci-cd/
4. Run command PHP bin/magento deploy:mode:set production

### Expected result (*)

1. Command is complete successfully

### Actual result (*)

1. I had the error Error happened during deploy process: Path "/home/admin/magento-modules/v2/Extmag-Shiplab/Extmag/Shiplab/view/frontend/templates/email/shipment/track.phtml" cannot be used with directory "/mnt/B6BCC155BCD11111/ci-cd/"

---
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by usman786cs** [comment]
I get this error when I try to upload a CSV file from admin 
"Path "var//import/od_redirects_13.csv" cannot be used with directory "pub/media/"
"

Please give clues to fix this error. 
Exception comes in file 

vendor/magento/framework/Filesystem/Directory/PathValidator.php::LINE#60
