### ISSUE TITLE
Manage Gallery not working 2.4.2

### ISSUE THREAD

**Issue by scott4243** [magento/magento2#32276]
### Preconditions (*)

1.2.4.2
2.

### Steps to reproduce (*)

1.we have quite a lot of pics and the Manage Gallery crashes every time
2.

### Expected result (*)

1. Manage Gallery to open
2.

### Actual result (*)

1. crashed admin and logs me out
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [* ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @scott4243 

Can you please run the following commands and check if the issue still occurs?
`bin/magento media-gallery:sync`
`bin/magento media-content:sync`

Thank you

**Comment by scott4243** [comment]
hi
thank you for replying i have just run the commands still the same i get this 

i click on Manage Gallery then the following happens 

Attention

Something went wrong.

Something went wrong with processing the default view and we have restored the filter to its original state.


when running your commands i did get this 
Form: Additional restrictions grant 
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
