### ISSUE TITLE
Magento 2.3.5p2 Multisite Installation - non default websites much slower than default site.

### ISSUE THREAD

**Issue by carylewis** [magento/magento2#32278]
### Preconditions (*)

1. Configure multiple websites in Magento 2.3.5p2 EE
2. Enable FPC - we are using Redis on AWS

### Steps to reproduce (*)

1. Access home page of default web site
2. Access home page of any non-default web site

### Expected result (*)
1. Home pages of default web site should start returning data in approx 800ms

### Actual result (*)
1. Home page of default web site returns data in 800ms
2. Home page of default web site returns data in 4.58 seconds!

Severity is S0

This problem is also discussed in https://github.com/magento/magento2/issues/15828, where it's marked as closed, but it is still happening.

**Comment by ihor-sviziev** [comment]
Unfortunately it’s hard to understand what could be wrong here.
Are you using varnish (recommended) or built in FPC? So you have black fire installed? If so - you could just compare results for 2 websites

**Comment by carylewis** [comment]
We are using Redis for the fpc backend.

We encountered this issue a couple of years ago with 2.1.18 and had to fix a magneto core function that prevented magento from being able to obtain the correct store id for non-default web sites.

**Comment by ihor-sviziev** [comment]
@carylewis please provide more info how we can reproduce this issue on clean magento installation

**Comment by carylewis** [comment]
We are trying to reproduce on a vanilla Magneto 2.3.5 installation.

What appears to be happening though is this:

The very first time a user accesses a non-default website, the full page cache is not used, and we this `X-Magento-Cache-Debug: MISS` in the header.

Accessing the default web site results in `X-Magento-Cache-Debug: HIT` being reported.

Once a session has been established a subsequent request to the same url results in `X-Magento-Cache-Debug: HIT` being reported.

It's as if even though magento knows which site to serve up (the correct content is always served up), for non-default web sites, the absence of the `X-Magento-Vary` cookie prevents the full page cache from being used. I know it's the `X-Magento-Vary` cookie and not the `PHPSESSID` cookie, because I did two tests where I removed each cookie in turn from the request.

Is this the expected behaviour? I would think not, as things like bots (google, etc.), would not have the `X-Magento-Vary` cookie  set when the sites are crawled, and having a slow page (TTFB) would harm rankings, etc.

**Comment by ihor-sviziev** [comment]
@carylewis do you have single domain for multiple stores, or own domain per store?

**Comment by carylewis** [comment]
Multiple domains, some domains have multiple stores / store views.

**Comment by ihor-sviziev** [comment]
Hi @carylewis,
Please switch to Varnish for full page cache, as it's recommended FPC option for production, and then check if you have this issue. If the issue still there - please write me on Slack. It would be much faster to chat and find the root of the issue.
