### ISSUE TITLE
Notice: Undefined index: (stuff)/Validator/Plugin.php on line 115 on large configuration product lists

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#3228]
I am trying to create over 360 configuration products from a configurable product with 24 colors and 15 lengths.   Every thing goes well (it works) if I don't add images to the "colors" attribute for the files.  If I have images added (about 3KB in size each), things work fine until it's time to hit "save" and I consistently get:

Notice: Undefined index: configurable_attribute in /var/www/html/magento2/vendor/magento/module-configurable-product/Model/Product/Validator/Plugin.php on line 115

Unfortunately the manual entry screen has what seems like a permanent spin to please wait.

Low numbers of product creation from a configurable product (like 40) goes well.

Maybe related to:  #3154 

It's probably something simple right?  My configuration?

Magento 2.0
Debian 8 up to date
MySQL version 5.6.28
OpenVZ 6 cores
1024M  php memory
5000 max_input_vars
PHP 5.6.17-0+deb8u1

**Comment by davidalger** [comment]
@joebusby You may be able to workaround it by disabling E_NOTICES in the error reporting levels configured on your PHP stack, but it is a bug, as PHP Notices should not happen regardless of what you're doing. ;)
