### ISSUE TITLE
Magento just plain sucks. Magento 2.4.2 is unusable. Period.

### ISSUE THREAD

**Issue by thewhiterabbit** [magento/magento2#32280]
I thought maybe I'd try to use Magento 2.4.2 for a recent project.

I flowed all the installation instructions.

The first time I tried to add a product, Error: Could not add Index, yada whatever.

Restart elastic search because, you know, pass the buck.

Product save button press, wait 2 minutes. Reload page. Empty fields. Goto Catalog>Products. Oh, it added product.

Try to update descriptions to product I just added, Error (again): Blah, index blah, I am Magento and I suck.

Attempt switching the indexing from "On Save" to "Schedule Indexing". Nope. Magento can't do that, sorry, Magento sucks.

Don't get me started on trying to integrate Magento into any other project, *if you could even get Magento to function properly on it's own in the first place.

Hey, Magento team, tell Adobe to stop serving junk bay allowing you to Start from zero and build Magento correctly, with proper engineering.

You can't fix what you have already, it's just absolute trash. I looked at the source and it's a convoluted mess of "trying to make bad practices good". Throw your core code into a dump site like that ET game, because that's how bad Magento is now.

Congratulations on destroying something that could have been improved, Adobe.

**Comment by thewhiterabbit** [comment]
> 
> 
> Hi @thewhiterabbit. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * Summary of the issue
> 
>     * Information on your environment
> 
>     * Steps to reproduce
> 
>     * Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> Please, add a comment to [assign the issue](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this`
> 
>     * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.
> 
> 
> ⚠️ According to the Magento Contribution requirements, all issues must go through the Community Contributions Triage process. Community Contributions Triage is a public meeting.
> 
> 🕙 You can find the schedule on the [Magento Community Calendar page](https://opensource.magento.com/community-calendar).
> 
> 📞 The triage of issues happens in the queue order. If you want to speed up the delivery of your contribution, please join the Community Contributions Triage session to discuss the appropriate ticket.
> 
> 🎥 You can find the recording of the previous Community Contributions Triage on the [Magento Youtube Channel](https://www.youtube.com/playlist?list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj)
> 
> ✏️ Feel free to post questions/proposals/feedback related to the Community Contributions Triage process to the corresponding [Slack Channel](https://magentocommeng.slack.com/archives/C016SG16J03)

GFYS, robot.

**Comment by thewhiterabbit** [comment]
Nope. That instance loads like 56k dial-up. Nope.

If Adobe wants proper engineering consulting with best practices for data architecture, scalability, and integration...maybe I'd be interested, to start from scratch.

I charge $2500 for 10 hour consulting blocks. Maximum 30 hours per month. I need my "me time".

Good luck, Adobe, Magento. You used to be good.

**Comment by shawnabramson** [comment]
It sounds like you didn't follow best practices and modified the core. Or maybe Magento didn't like your overall attitude and it said "screw this" Im not going to compile for this guy.

Here are links to some qualified trainings:
https://www.yireo.com/magento
https://www.mage2.tv/
https://m.academy/

**Comment by bgorski** [comment]
I closed the issue as it was an expression of one's opinion instead of an actual bug report. @thewhiterabbit if you'd like to report actual issues (like what you mentioned with descriptions or indexers), please open new issues formatted according to the template. Thanks!

**Comment by thewhiterabbit** [comment]
> 
> 
> It sounds like you didn't follow best practices and modified the core. Or maybe Magento didn't like your overall attitude and it said "screw this" Im not going to compile for this guy.
> 
> Here are links to some qualified trainings:
> https://www.yireo.com/magento
> https://www.mage2.tv/
> https://m.academy/

My practices reflect perfection. Your apparent lack of overall intelligence prevents you from insulting me. My attitude towards junk is a direct reflection of the experience with the junk that is Magento.

I'm not the only human that has deduced the _fact_ that Magento is in a degenerate state.

When users have to jump through hoops to install an app that still doesn't work properly, it's called failing, by any standard.

Let's see how many times you can put Magento 2 in your bio field. Good luck finding clients as a so called Magento 2 Certified Professional whilst the Magento ship is being deboarded by literally everyone in favor of any other ship that isn't full of holes.

Statistics don't lie. However, people like you lie to themselves, and everyone else.

Let Magento die. Start fresh.

P.S. - You look like you were already age 40 when Magento was born. The curve on new skills must be too steep for you to climb, better keep walking downhill.

**Comment by Adel-Magebinary** [comment]
The solution is simple. Bring back Magento 1. And call it Magento 3.

**Comment by zukovasmartynas** [comment]
Where are these haters comming from.
They took an enterprise level solution and think that they can install it with a few button clicks 😀
Ofc you need to know a lot to start working with magento 2. Its not a wordpress or awful magento 1.
