### ISSUE TITLE
Magento 2.4.2 old docroot logic does not work without workaround

### ISSUE THREAD

**Issue by rkapu** [magento/magento2#32285]
Hello!
On the other day i had a task to install magento 2.4.2 for testing purposes. I am holding my testing shops in subdirectories.
Version 2.4.2 does not work with that logic from the start because it's following new pub docroot path.
Magento is working perfectly fine if I will create a virtual host that points on pub directory. But on some testing servers i would preffer to hold different magento installations in subdirectories rather than creating a subdomains. So I tried to find the way for it to work with old logic and in my opinion I found some bugs that broke the old way of accesing magento which results into the need of implementing a workaround to work properly.

### Preconditions
1. Magento 2.4.2 Installation
2. PHP 7.4
3. Apache 2.4.18
4. Elasticsearch 7.9.1

### Steps to reproduce
1. Install magento 2.4.2
2. Make base url and apache virtual host point to magento installation in subdirectory (example 127.0.0.1/magento242/)
3. Try to access 127.0.0.1/magento242. This immediately result into a 404 not found page. I looked at new .htaccess and found this line:
```
RewriteRule .* /pub/$0 [L]
```
Okay, that 404 error is expected because the request is redirected to 127.0.0.1/pub and I don't have it on my environment. I created that folder and index file for simple test and it worked as i expected.
4. Then I think that I just need to change that line to redirect into magento pub directory.
```
RewriteRule .* /magento242/pub/$0 [L]
```
That still gave me a 404 not found error but now it was a magento error page not the apache one because files from pub directory such as error page and static files were correctly downloaded on request. I tried going to admin url and it still does not work.
Okay I don't know why that do not work so I tried to change new array key in **env.php** config file **directories=>document_root_is_pub** to **false**. I cleared the cache but nothing changed.
5. In the next step I decided to implement the old way of accesing magento installation. I copied **.htacces_sample** into magento root installation as **.htaccess**, copied **index.php** from **pub** into the root folder of installation and changed require path to **app/bootstrap.php** in it. It is important to clear the cache on this step.
6. The home and admin page works perfectly now. They gave 200 response and not a 404 error page anymore. But there are issues with static files. They now give a 404 errors because of path changes in magento 2.4.2 that i think are relative to this commit https://github.com/magento/magento2/commit/640cad53009b291334234ccd61ab79f256b43da2.
I tried to change value of **directories=>document_root_is_pub** because I think that this config value should regulate the correct paths but nothing changed. Either it is false or true the result is the same. I looked at the code and don't see any places where this config value would somehow be used. (I found only one place where it is set into $configData)
7. So I found 2 workarounds to this problem. 
  * Make a redirect on top of .htaccess to pub if certain words are met in the REQUEST_URI.
  ```
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond "%{REQUEST_URI}" "(/errors/|/static/|/media/|/opt/)"
    RewriteRule .* /magento242/pub/$0 [L]
</IfModule>
  ```
  * Make a symlinks from magento root to folders inside the pub directory such as **errors, opt, static, media**

### Expected result
4. I expected it to work and display all the pages but instead it displays 404 errors on any link such as **homepage**, **admin_url** but static files are downloaded fine.  
6. Expected it to work in this step too, because I haven't found a mention in 2.4.2 release notes that paths are changed to not include **/pub/** anymore and now aren't compatible with old way of accessing magento.

### Actual result
3. 
![image](https://user-images.githubusercontent.com/49211917/109145153-c62cde00-776a-11eb-83d3-a4542d904fec.png)

4. 
![image](https://user-images.githubusercontent.com/49211917/109145187-d47afa00-776a-11eb-88b1-46bae1816609.png)

6. 
![image](https://user-images.githubusercontent.com/49211917/109145202-dcd33500-776a-11eb-9834-398d1d563df1.png)

7. 
![image](https://user-images.githubusercontent.com/49211917/109145222-e2307f80-776a-11eb-862f-c32c075d726d.png)

I didn't find how to add a label for Severity so I decide to leave it here. I think that is **Severity: S1**

**Comment by incarnate** [comment]
I've had a similar experience as AstroniumGIT - fresh install in a subdirectory and changed the `.htaccess` file to include the subdirectory in the rewrite rule. Trying to access the setup resulted in infinite redirects to /pub/setup. After performing the installation via the CLI, all pages return 404 same as screenshot 4 above.

I can't find any documentation around this change (granted this is a tricky one to search for) or what needs to be done to ensure installation works in a subdirectory now.

**Comment by mrtuvn** [comment]
cc @shiftedreality

**Comment by shiftedreality** [comment]
This change was done as part of the Remote Storage development track.

We have not found official mention of this installation flow in either public or internal documentation. Also, our manual tests showed it as partially broken in 2.4.1.
Is there any official documentation that mentions this as supported?

**Comment by khoimm92** [comment]
This .htaccess rule works for me (remove the slash before pub/):
`RewriteEngine on
RewriteCond %{REQUEST_URI} !^pub/
RewriteCond %{REQUEST_URI} !^/setup/
RewriteCond %{REQUEST_URI} !^/update/
RewriteCond %{REQUEST_URI} !^/dev/
RewriteRule .* pub/$0 [L]
DirectoryIndex index.php`

**Comment by iphigenie** [comment]
> I can't find any documentation around this change (granted this is a tricky one to search for) or what needs to be done to ensure installation works in a subdirectory now.

the new installation documentation simply puts "pub set as the document root" in the requirements, which simply washes its hands of all other scenarios.

**Comment by shiftedreality** [comment]
You still can use `index.php` from the root folder.

We've adjusted root `.htaccess` to point to `pub` folder in a backward-compatible way.
Here is more on the change: https://github.com/magento/magento2/pull/29176

So, in version 2.4.2+ you still have 3 options as before:

1. Apache with the root `.htaccess` configured to point to `pub`: https://github.com/magento/magento2/blob/2.4.2/.htaccess
2. Apache with the `pub` root
3. Nginx with the `pub` root

Since having Magento in subdirectories is not officially supported and tested, I would encourage you to use a workaround and create a pull-request into Devdocs with the preferred method.

Otherwise, we do not have any tests or tools in place to verify this installation method.

**Comment by iphigenie** [comment]
I understand that having magento in subdirectories is not supported - it would have been nice if so many installation instructions and hosting companies didn't make it the default. 

I don't mind switching to running through pub either, that's fine.

What's more flabbergasting is that a base URL containing a subpath - I'm talking urls here, independently from any "server storage" - like mysite.com/shop seems to now cause fatal errors with rewrites. Clearly adaptations need to be made and it'd been nice if this was at the very least mentioned in the release notes...

**Comment by mrtuvn** [comment]
Maybe this link https://devdocs.magento.com/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.html will have more clear about this

**Comment by shiftedreality** [comment]
@iphigenie is this solved for you with alternative configuration instructions?

I will be happy to help with any documentation updates if needed.

**Comment by mrtuvn** [comment]
CC: @dobooth may be we need add issue clarify this section in devdocs

**Comment by dobooth** [comment]
Thanks for the great conversation here. I would be happy to help with any PR around this.

**Comment by shiftedreality** [comment]
We've performed an investigation and found the solution with symlinks (https://magento.stackexchange.com/a/332419/38801) to be working fine on 2.4.2. We will proceed with official documentation for it. 

Please let me know if there any other use cases that need investigation.

**Comment by shiftedreality** [comment]
DevDocs was updated with https://github.com/magento-commerce/devdocs/pull/2170

**Comment by hostep** [comment]
@shiftedreality: please link to publicly visible repositories, the link you put here is a private repository, thanks! 🙂

**Comment by shiftedreality** [comment]
@hostep thanks for noticing this, changed to link on DevDocs instead of private PR

**Comment by mrtuvn** [comment]
Hi Is there any link available in devdocs for guide setup multiple domain/stores with 2.4.2 root pub changes

**Comment by AstroniumGIT** [comment]
Thank you all for colaboration!
I`m glad that DevDocs were updated.

**Comment by iphigenie** [comment]
@shiftedreality I got rid of the subfolders but I can't help but notice that the installation instructions https://devdocs.magento.com/guides/v2.4/install-gde/composer.html are STILL GIVING EXAMPLES THAT LEAD TO GENERAL 404 

These need to be modified to something that works on 2.4.2 

Because people are following these instructions and you can find them on stack exchange "fresh install doesnt work" https://magento.stackexchange.com/questions/337808/magento-2-fresh-install-showing-whoops-our-bad-404-page-not-found/339249
