### ISSUE TITLE
How to re install missing foreign-key constraints?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32289]
### Summary (*)

I am using a third party extension.
I noticed that a constraint is missing by comparing with a fresh installation. This causes a bug when deleting an item of the extension.

Is there a command which is able to install missing constraints?

I've tried 

```
php -f bin/magento setup:db-schema:upgrade
php -f bin/magento setup:db-data:upgrade
php -f bin/magento setup:upgrade
```

but none of these commands re-installed the missing constraint.

--------

The only way I've found is deleting the table and the extension entry from the table `setup_module` and executing `php bin/magento setup:upgrade`, but this is too radical since I have to re-add the data

### Examples (*)

If you like to reproduce it, then just delete a random Foreign Key Constraint, then try to execute 

```
php -f bin/magento setup:db-schema:upgrade
php -f bin/magento setup:db-data:upgrade
php -f bin/magento setup:upgrade
```

and see if the constraint was added again.

### Proposed solution

-

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Maybe problem related with this solution https://github.com/magento/magento2/pull/32286

**Comment by hostep** [comment]
Nope, that's something completely different :)

@Eddcapone, you'll need to provide some more details and actually github isn't really the correct place to discuss these sort of things, you'll probably want to try https://magento.stackexchange.com/
Issues on github should have very clear steps about how we can reproduce these before we can consider this a bug in Magento itself. If this is a problem caused by some 3rd party plugin, then github is not really the right place to start this discussion.

**Comment by Eddcapone** [comment]
@hostep , This is not a bug report. I created the issue under **Developer Experience Issue**.

I did not added steps since I thought it is self explanatory. To reproduce you just have to delete a random constraint and then try to look for a command which is able to install it again.

![image](https://user-images.githubusercontent.com/16349349/109274328-a998b080-7813-11eb-9ee1-c4801c93e17b.png)
