### ISSUE TITLE
VAT number validation is not working since some days in Magento2

### ISSUE THREAD

**Issue by rodolfo2111** [magento/magento2#32284]
### Summary (*)
VAT number validation does not work anymore in Magento
When I try to validate a VAT number in the Magento backend Stores --> Configuration --> General --> General I always receive the message: "Error during VAT number verification" . 
The same problem occurs when I try to automatically check the VAT number of a customer during the registration process.
Everything worked fine some days ago - I did not any change on my side in the last weeks and now it stopped working. It seems that something on the VAT service may have changed.

### Preconditions (*)

Magento version 2.4.1

### Steps to reproduce (*)
Enter a VAT number in the Magneto backend  Stores --> Configuration --> General --> General 
and click the "Validate VAT number button"

### Expected result (*)

The expected result should be either the verification that the VAT number is correct or  a message which informs me that the VAT number is incorrect.

### Actual result (*)
I get the same mesage  "Error during VAT number verification", in the case that the VAT number is correct and in the case that the VAT number is incorrect.
I checked the WSDL file in 
vendor/magento/module-customer/Model which is https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
and tested it with postman and the webserice seems to be up and running.
However, obviously it cannot be called by Magento 2.4.1 anymore.
Does anybody know if some parameters on the service have changed the last days and which adoptions I have to do tomake it work again. 

---
![Bildschirmfoto vom 2021-02-25 10-42-31](https://user-images.githubusercontent.com/79634506/109134349-39782500-7756-11eb-92c3-f2596ee6cba2.png)

**Comment by devchris79** [comment]
Magento requires the VAT number without the Country code. We use a free add on to allow country codes (CopeX_VatFix).

**Comment by rodolfo2111** [comment]
@devchris79 : I also tried it without the country code and it does not work. However, it also worked with the country code some days ago. So unfortunately this cannot be the reason for the problem

**Comment by devchris79** [comment]
@rodolfo2111 The country code is the AT part only (Austria), the U123456 is the code required.

**Comment by rodolfo2111** [comment]
@devchris79 : I tried all variants ;-) It does not work. And it definitively worked with the ATU in the past
![Bildschirmfoto vom 2021-02-25 11-17-06](https://user-images.githubusercontent.com/79634506/109142716-7d235c80-775f-11eb-88f4-51861b621d4d.png)

**Comment by devchris79** [comment]
Try a genuine Austrian VAT number, like this one:
U16168803

**Comment by rodolfo2111** [comment]
@devchris79 : i tried, also  one and the one you provided.  
![Bildschirmfoto vom 2021-02-25 11-55-43](https://user-images.githubusercontent.com/79634506/109143664-937de800-7760-11eb-9a86-fd0189dbaa87.png)

**Comment by devchris79** [comment]
There was #27874 when the validation URL changed, but that was some time ago.

**Comment by rodolfo2111** [comment]
yes, I have seen this issue. Since I have the latest Magento version 2.4.1 the link should be correct: 'https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl';

**Comment by rodolfo2111** [comment]
I identified that the Service is working on my local Magneto instance (which is a 1:1 copy of the live system) correctly ... so it seems to be a problem with my Server instance. I will check this with my provider and keep you updated

**Comment by rodolfo2111** [comment]
I identified the following message in the log file: main.CRITICAL: javax.xml.rpc.soap.SOAPFaultException: IP_BLOCKED [] []

**Comment by nuzil** [comment]
Hey @rodolfo2111 looks like your server is blocking requests to EU Service, so I'm closing issue as its not related to Magento itself.

**Comment by drinkingsouls** [comment]
Apologies for reopening if this is not a vanilla Magento issue, however I also have this problem.

Magento 2.4.4, PHP8.1, Soap is installed.

I have the following request url in Vat.php:
https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

Same issue as reported here. "Error during VAT number verification"
Tried with and without country code.

I have no logged errors.

@rodolfo2111 did you find a solution?
