### ISSUE TITLE
The requested class did not generate properly, because the 'generated' directory permission is read-only.

### ISSUE THREAD

**Issue by faradey** [magento/magento2#32296]
### Preconditions (*)

1. Magento 2.3.6, Magento 2.4.2
2. Magento 2 Cloud 2.4.0 

### Steps to reproduce (*)

1. Specify such a proxy class in the di.xml module
 `<type name="Extmag\Shiplab\Model\LabelRepository"><arguments><argument name="trackRepository" xsi:type="object">
Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy
</argument></arguments></type>`
2. Run command setup:di:compile
3. Specify such a proxy class in the di.xml module
`<type name="Extmag\Shiplab\Model\LabelRepository">
        <arguments>
            <argument name="trackRepository" xsi:type="object">Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy</argument>
        </arguments>
    </type>`
4. Run command setup:di:compile

### Expected result (*)

1. Class Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy created
2. Class Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy created

### Actual result (*)

1. Class Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy not created
2. Class Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy created

In the first case, for Magento cloud, it still gives an error when accessing the class:
[2021-02-18 13:31:48] report.CRITICAL: Can't create directory /app/generated/code/Magento/Sales/Model/Order/Shipment/TrackRepository/.
Class Magento\Sales\Model\Order\Shipment\TrackRepository\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []

Most likely the point is that some ide format the code differently. In this case, the problem is that there is a line feed in the argument tag. But it is interesting that when you go to a page using this proxy class in the admin panel, it is created without problems, unless, of course, the "generated" folder is closed for writing. (in developer mode).

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by ihor-sviziev** [comment]
Hi @faradey,
Please contact Magento Cloud support to fix this issue. Also, you could ask for help in the `#cloud` channel in EngCom Slack.
This repository relates to Magento in general and not to Magento Cloud. That's why I'm closing this issue.

**Comment by faradey** [comment]
Hi @ihor-sviziev,
I think this is Magento's problem. Magento Cloud is a special case.
If you work in developer mode, the file is created. If you run setup: di: compile, the file is not created. There is inconsistency in Magento's behavior in developer mode and during compilation. Two identical actions cannot give different results.

**Comment by ihor-sviziev** [comment]
@faradey feels like you have some issue with permissions. on Magento Cloud I believe only during build phase you have write permissions to the generated folder. That's why you're getting this issue.

**Comment by faradey** [comment]
Hi @ihor-sviziev,
I have done some research and described step by step how to repeat the error. My folder permissions are correct. I have rechecked several times. I even gave full rights to folders to all users. And it didn't help. Please disregard Magento Cloud. This is happening with the Magento Community. This is repeated both locally and on the server.
I am ready to provide the necessary additional data.

**Comment by ihor-sviziev** [comment]
@faradey steps to reproduce not clear to me. Why should you 2 times add the same piece to di.xml?
The correct version will be w/o spaced near the argument, like this:
```xml
<type name="Extmag\Shiplab\Model\LabelRepository">
    <arguments>
        <argument name="trackRepository" xsi:type="object">Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy</argument>
    </arguments>
</type>
```

**Comment by faradey** [comment]
Points 1, 2 are done separately from points 3, 4. 
First, in points 1 and 2, add a line break code to di.xml https://tinyurl.com/y9reywq7 . Check if the proxy class is being created in developer mode. If the class was created, then delete it. And then you do the compilation. And check if the proxy class has been created. The file will not be created.

Then follow steps 3.4. Change (add) the code with a line break to code without a line break in di.xml https://tinyurl.com/ybraag46 . Check if the proxy class is being created in developer mode. If the class was created, then delete it. And then you do the compilation. And check if the proxy class has been created. The file will be created.

**Comment by faradey** [comment]
It is best to put the site in maintenance mode so that the cron does not interfere. Otherwise, proxy files can be created for the cron, if the cron tasks use proxy classes.

**Comment by ihor-sviziev** [comment]
Ok. It seems like the trimming is missing somewhere, right?

✔ works fine
```xml
<type name="Extmag\Shiplab\Model\LabelRepository">
    <arguments>
        <argument name="trackRepository" xsi:type="object">Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy</argument>
    </arguments>
</type>
```

❌ doesn't work
```xml
<type name="Extmag\Shiplab\Model\LabelRepository">
    <arguments>
        <argument name="trackRepository" xsi:type="object">
            Magento\Sales\Api\ShipmentTrackRepositoryInterface\Proxy
        </argument>
    </arguments>
</type>
```

Am I right?

**Comment by faradey** [comment]
@ihor-sviziev,
yes, cropping is missing somewhere. But I didn't have enough time to figure out the very place in the code where this happens.
