### ISSUE TITLE
Adding subgroup in system.xml causes error 

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#32300]
### Preconditions (*)

1. Magento 2.3.6

### Steps to reproduce (*)

1. Create module that has in system.xml nested groups, what, according to docs is possible - https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-systemxml.html#group-node-reference
Example:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Config:etc/system_file.xsd">
    <system>
        <section id="sales">
            <group id="cart_items_limits" translate="label" type="text" sortOrder="105" showInDefault="1" showInWebsite="1" showInStore="1">
                <label>Cart items limits</label>
                <group id="max_count_limit" translate="label" type="text" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Max count limit</label>
                    <field id="value" translate="label" type="text" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="0">
                        <label>Value</label>
                        <validate>required-number validate-number validate-greater-than-zero</validate>
                    </field>
                    <field id="reached_limit_message" translate="label comment" sortOrder="20" type="textarea" showInDefault="1" showInWebsite="1" showInStore="1">
                        <label>Reached limit message</label>
                        <comment>This message will be shown if cart items max count limit is reached. In order to include limit value add {{limit_value}}.</comment>
                        <validate>required-entry</validate>
                    </field>
                    <field id="overflow_message" translate="label comment" sortOrder="30" type="textarea" showInDefault="1" showInWebsite="1" showInStore="1">
                        <label>Overflow message</label>
                        <comment>This message will be shown when cart items max count limit is overflown. In order to include limit value add {{limit_value}}.</comment>
                        <validate>required-entry</validate>
                    </field>
                </group>
            </group>
        </section>
    </system>
</config>
```

2. Save values for these fields

### Expected result (*)

1. Configuration loaded, app works normally.

### Actual result (*)

1. We get anywhere (not only while saving values) - `Exception: Warning: Illegal string offset 'value' in /var/www/html/vendor/magento/framework/App/Config/Scope/Converter.php ` - so whole magento is down

This fix works, but I don't know if it is good approach - https://mage2.pro/t/topic/2323. Of course, you can just rewrite you system.xml to not use nested groups, which just organizes your configuration better, but it worked in magento 2.2.*
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bartoszkubicki** [comment]
Still an issue, nothing has changed

**Comment by Penchal-magento** [comment]
We tried on Magento ver. dev-2.4-develop  and lower version (2.3.5)  but we did not get mentioned error.
Kindly upgrade magneto version to 2.4.

**Comment by engcom-Lima** [comment]
We can't see the any activity more than 14 days. Hence closing this ticket. In case of any new issue you can create the new ticket.

**Comment by bartoszkubicki** [comment]
It should be reopened and fixed. All details were provided, you need someone from your team to pick this up
