### ISSUE TITLE
Error install Sampledata Magento 2.0.2

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#3230]
`Module 'Magento_CatalogSampleData':
[ERROR] exception 'ReflectionException' with message 'Class Magento\Catalog\Model\ResourceModel\Product\Attribute\Backend\Media does not exist' in D:\App\htdocs\magento2\lib\internal\Magento\Framework\Code\Reader\ClassReader.php:29 Stack trace: #0 D:\App\htdocs\magento2\lib\internal\Magento\Framework\Code\Reader\ClassReader.php(29): ReflectionParameter->getClass() #1 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Definition\Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Catalog...') #2 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Catalog...') #3 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #4 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #5 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'gallery', 'Magento\\Catalog...') #6 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #7 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #8 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #9 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'productSetup', 'Magento\\Catalog...') #10 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #11 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #12 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #13 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'installer', 'Magento\\Catalog...') #14 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #15 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array) #16 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(869): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...') #17 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(1173): Magento\Setup\Model\Installer->createSchemaDataHandler('Magento\\Catalog...', 'Magento\\Framewo...') #18 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(797): Magento\Setup\Model\Installer->getSchemaDataHandler('Magento_Catalog...', 'data-install') #19 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(748): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #20 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #21 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #22 D:\App\htdocs\magento2\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #23 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #24 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #25 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #26 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #27 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #28 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #29 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #30 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #31 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #32 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #33 D:\App\htdocs\magento2\setup\index.php(31): Zend\Mvc\Application->run() #34 {main} Next exception 'ReflectionException' with message 'Class Magento\Catalog\Model\ResourceModel\Product\Attribute\Backend\Media does not exist' in D:\App\htdocs\magento2\lib\internal\Magento\Framework\Code\Reader\ClassReader.php:37 Stack trace: #0 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Definition\Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Catalog...') #1 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Catalog...') #2 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #3 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #4 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'gallery', 'Magento\\Catalog...') #5 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #6 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #7 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #8 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'productSetup', 'Magento\\Catalog...') #9 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #10 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...') #11 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...') #12 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'installer', 'Magento\\Catalog...') #13 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array) #14 D:\App\htdocs\magento2\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array) #15 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(869): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...') #16 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(1173): Magento\Setup\Model\Installer->createSchemaDataHandler('Magento\\Catalog...', 'Magento\\Framewo...') #17 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(797): Magento\Setup\Model\Installer->getSchemaDataHandler('Magento_Catalog...', 'data-install') #18 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(748): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #19 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #20 D:\App\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #21 D:\App\htdocs\magento2\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #22 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #23 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #24 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #25 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #26 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #27 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #28 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #29 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #30 D:\App\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #31 D:\App\htdocs\magento2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #32 D:\App\htdocs\magento2\setup\index.php(31): Zend\Mvc\Application->run() #33 {main}`

**Comment by mazhalai** [comment]
Did you have have a previous installation? Please clean you var/ directory and try again. Also, how did you deploy? via git, composer create-project or downloaded a zip from magento.com

**Comment by scholtz** [comment]
i used this to install sample data on 2.0.2 and it works:
``` php bin/magento sampledata:deploy
 php bin/magento setup:upgrade

chown -R root:www-data .
find . -type f -print0 | xargs -r0 chmod 640
find . -type d -print0 | xargs -r0 chmod 750
chmod -R g+w {pub,var}
```

**Comment by mazhalai** [comment]
@scholtz thanks for the update. closing this issue for now. Please create a new one in case you run into any more issues.

**Comment by scholtz** [comment]
it is not my issue, i think you should wait for @minhluan259 how he managed to get the error.. :)

**Comment by mazhalai** [comment]
@scholtz thanks for pointing that out. i did not pay attention to who posted the reply!

**Comment by minhluan259** [comment]
I use git for clone
git clone https://github.com/magento/magento2.git
php bin/magento sampledata:deploy
Then I use setup wizard, when the process is 88%, the error message appears.

Update: I have downloaded a zip from magento.com and successfully installed.

**Comment by mazhalai** [comment]
@minhluan259 for git clone, did you get `develop` branches for both magento2 as well as sample-data?

**Comment by minhluan259** [comment]
I use `php bin/magento sampledata:deploy` , `composer update`
and it auto download sampledata v100.0.3

**Comment by ghost** [comment]
If you used git clone, you probably cannot use `magento sampledata:deploy`. Instead, try [this](http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data-clone.html)

**Comment by minhluan259** [comment]
Thank for all.
@mazhalai , you can close this issue.
