### ISSUE TITLE
API add to cart with simple product but different options increases qty instead of adding new cart item

### ISSUE THREAD

**Issue by DavidLambauer** [magento/magento2#32302]
We're trying to add the same simple product into the cart, but with custom options through the api. The expected result would be to have 2 items in the cart with different custom options. Actual result is the first item is in cart with qty of 2.

### Preconditions

Magento Version 2.4.2

### Steps to reproduce

You might want to check the video attached below

https://user-images.githubusercontent.com/1841317/109302902-39515580-783a-11eb-8633-92756f921f4e.mp4

.

1. Create a cart via rest call: POST | {{ base_url  }}guest-carts
2. Receive the cart to make sure no items are in the cart: GET | {{ base_url  }}guest-carts/cartId
3. Add a simple product with custom options to the cart: POST | {{ base_url  }}guest-carts/cartId/items

Example Payload: 

```json
{
  "cartItem": {
    "sku": "THE-SKU-OF-YOUR-SIMPLE-PRODUCT",
    "qty": 1,
    "product_option": {
      "extension_attributes": {
        "custom_options": [
          {
            "option_id": "1",
            "option_value": "abc"
          },
          {
            "option_id": "2",
            "option_value": "abc"
          }
        ]
      }
    },
    "quoteId": "YOUR-QUOTE-ID"
  }
}
```

4. (optional) Re-do step 2 to validate that the product was added to the cart.
5. Re-do step 3 but change the custom option values in the payload.
6. Re-do step 2 to again to see that two different products got merged into one but the qty was increased.

### Expected result (*)

1. 

### Actual result (*)

The cart should contain two items, each one with the custom options that were selected.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by simonmaass** [comment]
@magento give me 2.4-develop instance

**Comment by simonmaass** [comment]
@magento I am working on this

**Comment by simonmaass** [comment]
@magento add to contributors team

**Comment by simonmaass** [comment]
@magento I am working on this

**Comment by simonmaass** [comment]
can confirm issue

**Comment by simonmaass** [comment]
this is not fixed and should not be stale!

**Comment by engcom-Alfa** [comment]
Hi , Tried on Magento 2.4 Develop , issue is replicable , Hence request to look into it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42474` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42474` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment]
Hi @DavidLambauer,

We have tried to reproduce this issue in 2.4-develop branch, but this is not reproducible. May be this issue has been fixed in this branch.

So we request you to please try to reproduce this in 2.4-develop branch and let us know, if you are able to reproduce this issue in this branch.

Thanks

**Comment by DavidLambauer** [comment]
Well, maybe we wait two more weeks if the next person confirms the issue again? A couple of people mentioned that this is still valid and has not been fixed yet. I can't provide even more information. I think the description and how you reproduce this issue is pretty clear.

**Comment by emanuelcorrea** [comment]
@magento I am working on this

**Comment by emanuelcorrea** [comment]
@magento add to contributors team
