### ISSUE TITLE
Update laminas/laminas-serializer to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32318]
Update laminas/laminas-serializer to PHP 8 compatible version (2.10.1)

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @khrystynastolbova. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39674` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
