### ISSUE TITLE
Product gallery jumps while loading

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#32315]
It seems like after https://github.com/magento/magento2/pull/27871 we have a bit jumpy gallery again. My investigation shown that it's happening because of not hiding the thumbnails below the big image.

/CC @krzksz 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. Open frontend in chrome, open developer tools 
2. In the "source tab" set a breakpoint on the following line: https://github.com/magento/magento2/blob/15860ab3ab274e1b0df007b5cdb8bf30b52fe515/lib/web/mage/gallery/gallery.js#L307
3. refresh the page
4. When the script will stop on breakpoint switch to the elements tab and find the `.fotorama-item` item

### Expected result (*)

1. There should be no jumps during gallery load

### Actual result (*)

1. fotorama-items eats some space that causes not expected layout shifts:
**Dev tools:**
![image](https://user-images.githubusercontent.com/1873745/109506842-c567b500-7aa6-11eb-920b-0327e16a7339.png)
**Desktop:**
![image](https://user-images.githubusercontent.com/1873745/109506790-b97bf300-7aa6-11eb-8d59-19bbcde64432.png)
**Mobile:**
![image](https://user-images.githubusercontent.com/1873745/109507017-f3e59000-7aa6-11eb-86cf-0b1d8006e9a6.png)

https://user-images.githubusercontent.com/1873745/109507971-fbf1ff80-7aa7-11eb-8182-9c3bfcdb3fe5.mp4

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by Quazz** [comment]
Personally I've replaced the function with 

`        initGallery: function () {
            var breakpoints = {},
                settings = this.settings,
                config = this.config,
                tpl = template(galleryTpl, {
                    next: $t('Next'),
                    previous: $t('Previous')
                }),
                mainImageIndex,
                $element = settings.$element,
                $fotoramaElement;

            if (settings.breakpoints) {
                _.each(_.values(settings.breakpoints), function (breakpoint) {
                    var conditions;

                    _.each(_.pairs(breakpoint.conditions), function (pair) {
                        conditions = conditions ? conditions + ' and (' + pair[0] + ': ' + pair[1] + ')' :
                        '(' + pair[0] + ': ' + pair[1] + ')';
                    });
                    breakpoints[conditions] = breakpoint.options;
                });
                settings.breakpoints = breakpoints;
            }

            _.extend(config, config.options,
                {
                    options: undefined,
                    click: false,
                    breakpoints: null
                }
            );
            settings.currentConfig = config;

            $element
                .css('min-height', settings.$element.height())
                .append(tpl);

            $fotoramaElement = $element.find('[data-gallery-role="gallery"]');

            $fotoramaElement.fotorama(config);
            $fotoramaElement.hide();
            $element.find('.gallery-placeholder__image').remove();
            $element
                .removeClass('_block-content-loading')
                .css('min-height', '');
            $fotoramaElement.show();

            settings.$elementF = $fotoramaElement;
            settings.fotoramaApi = $fotoramaElement.data('fotorama');

            $.extend(true, config, this.startConfig);

            mainImageIndex = getMainImageIndex(config.data);

            if (mainImageIndex) {
                this.settings.fotoramaApi.show({
                    index: mainImageIndex,
                    time: 0
                });
            }
        }`

I found the fotoramaStage troublesome like you did and the f:load function seems unreliable (causing jumps as well)

Since the slowest part is loading the gallery, hiding the element, removing placeholder, then showing the element seemed to be the most reliable answer. I tried other variations, trying to make use of the fotorama f:load event, but it never seemed to produce the desired results in a reliable fashion.

**Comment by ihor-sviziev** [comment]
@Quazz, your solution will probably cause gallery blinking and potentially add Layout Shift, making worse Google Pagespeed Results.

**Comment by Quazz** [comment]
> @Quazz, your solution will probably cause gallery blinking and potentially add Layout Shift, making worse Google Pagespeed Results.

There is a slight blinking (followed swiftly by ajax spinner), but 0 layout shift. 

I care less about that slight blinking than about the layout shift, but if someone has a solution that fixes both that would be ideal.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ihor-sviziev 

Thanks for reporting and collaboration.

We have verified the issue in magento 2.4 dev instance but we are not seeing the lines `$fotoramaStage.css('position', 'absolute'); ` in line 307 on source tab.

Can you please share the detailed steps to reproduce inorder for us to test the issue.

Please refer the attached screenshots and let us know if we missed anything.
<img width="1440" alt="Screenshot 2024-03-20 at 6 42 42 PM" src="https://github.com/magento/magento2/assets/60198592/536d5219-3e92-4b22-b3a6-22e7454b71a6">

**Comment by ihor-sviziev** [comment]
These changes were already merged in another pull request https://github.com/magento/magento2/pull/33265#issuecomment-1774582770
