### ISSUE TITLE
Category selector style issue

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#3231]
If the category property "is_active" is false, in the tree mode of category selector the name will be in hidden style:
https://www.dropbox.com/s/m57klwrboifd8zk/tree.png?dl=0

but in the list mode of category selector the name will be in default style:
https://www.dropbox.com/s/h66ljb8ez3nkij9/list.png?dl=0

**Comment by katmoon** [comment]
Hi @sergei-sss ,

Thank you for reporting the issue!
Internal ticket is `MAGETWO-48646`

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
We've created internal ticket(s) MAGETWO-48646 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
