### ISSUE TITLE
Current Config Scope shows as "disabled" / "non-selectable" while it is active

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#3232]
When in the adminhtml area in Stores > Configuration the scope drop-down menu does not show which one is currently selected.

![image](https://cloud.githubusercontent.com/assets/10513307/12715605/78c245d0-c8db-11e5-8996-5e68db48ad26.png)

**Comment by veloraven** [comment]
@tkn98 is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.

**Comment by tkn98** [comment]
You're asking stuff. This is months away. We have many more tickets opened in the enterprise gold support, you should perhaps concentrate on these. This one was just reported for your information.

I close as I read your comment as there is no real interest from your side to reproduce/fix it. Just so that my motivations are clear.
