### ISSUE TITLE
Replace usages of ReflectionParameter deprecated methods

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32332]
### Description (*)

Replace usages of \ReflectionParameter deprecated methods:

- isArray (Use ReflectionParameter::getType() and the ReflectionType APIs should be used instead)
- isCallable (Use ReflectionParameter::getType() and the ReflectionType APIs should be used instead)

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by ihor-sviziev** [comment]
Is it duplicate of https://github.com/magento/magento2/issues/31600 ?

**Comment by AndreyChorniy** [comment]
Hello @ihor-sviziev, 
It seems that is similar but not duplicate. In #31600 I can see that `isArray()` still used for example [here](https://github.com/magento/magento2/pull/31861/files#diff-8aa8f6efe0cef6bfe3ca2cba84f0d238617d0e624a90a09fcb58720f3744bcfcR336)
Could you please check once again and let me know if I should proceed with this?
Thank you.

**Comment by ihor-sviziev** [comment]
Ah, if that solution isn't full - I think we need to fix all not fixed
things

**Comment by sivaschenko** [comment]
@ihor-sviziev @AndreyChorniy hi guys, this is not a duplicate. Only getClass methods have been replaced in https://github.com/magento/magento2/pull/31861 and we decided to extract other deprecated methods to a separate task

**Comment by sivaschenko** [comment]
Hi @AndreyChorniy would you like to work on this issue or it can be unassigned?

**Comment by konarshankar07** [comment]
@magento I am working on this
