### ISSUE TITLE
Magento 2.4.2 Commerce, Pagebuilder is not saving images

### ISSUE THREAD

**Issue by phathro** [magento/magento2#32347]
### Preconditions (*)

1.  Magento 2.4.2 (Commerce)
2. Ordinary image element in page builder
3. (Everything else is saving normally, caption, text, etc.)

### Steps to reproduce (*)

1. Just add an image-element to a CMS-page and add a random image file
2. Save the whole CMS-page

### Expected result (*)

1. It should save the picture as normally

### Actual result (*)
1. the image selected is gone
2. in the database it says "undefined"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @phathro 

Thank you for your report.

When you are adding an image using PageBuilder, do you drag-drop a _Row_, for example, and then drag-drop _Image_ element from Media?
If yes, do you **Upload** an image or **Select from Gallery**?

Thank you in advance

**Comment by phathro** [comment]
Hello,

i add the image via "Select from Gallery". This issue also appears for a colleague, funny thing is, two other colleagues dont have this issue, with the same setup. 

We thought it may be a problem with our rights or something about the database, but we couldn't find a problem there or difference

**Comment by engcom-Bravo** [comment]
@phathro 
I see. Sometimes a problem might happen with the Page Builder because of caching. Did you try to clear the browser's cache and Magento cache?

Thank you in advance

**Comment by phathro** [comment]
@engcom-Bravo i cleared the caches of every source i knew multiple times, so far this issue appears still. Also, interestingly, another colleague setup the project locally on his lap top and it works fine for him, with the same data. 
So im still kinda clue less :)
