### ISSUE TITLE
Install magneto 2.4.2 in Apache2

### ISSUE THREAD

**Issue by karangar** [magento/magento2#32348]
### Preconditions (*)

Magneto 2.4.2
1. Magneto 2.4.2
2. composer 1.10.9
3. php 7.4.15

### Steps to reproduce (*)

1. Download Magneto 2.4.2 using Composer Or  direct Zip file
2. Install and setup magento using command

### Expected result (*)

1.Front end and Admin Should be work

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/34768419/109780243-d5110600-7c2c-11eb-96dd-c43032fb1ae9.png)

Please let me know which step I have to performed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @karangar 

Thank you for your report.

The described behavior is not a Magento issue. Please check that your Apache server is active and Running, check the configuration file, check that you've set the correct permissions.

We are closing this issue as this is not a Magento issue.

**Comment by farazWebDev** [comment]
I tried to install using composer. Frontend and Backend URLs are throwing 404.

I also tried zip file, but same error. when extracted I found index.php file is not in root of Magento installation.
If I rename .htaccess file then URL shows all files and folders in the Magento installation directory.
