### ISSUE TITLE
Upgrade 2.4.1 to 2.4.2 with Dotdigitalgroup_Email disabled

### ISSUE THREAD

**Issue by micwallace** [magento/magento2#32345]
### Preconditions (*)

    - Magento 2.4.2

### Steps to reproduce (*)

    1. Disable the Dotdigitalgroup_Email module in 2.4.1 and upgrade Magento 2 to 2.4.2
    2. After upgrading via composer login to the backend of magento2.

### **Expected result (*)**

    Expected to dashboard

### Actual result (*)

I got an error page with the following:
Exception #0 (OutOfRangeException): Specified invalid parent id (Dotdigital group Email::marketing automation)

## My suggestion

This was "fixed" in 2.3.4, original issue here: https://github.com/magento/magento2/issues/26573

As discussed there I propose a solution which will get rid of this once and for all:

Either have 3rd party modules disabled by default (fat chance of that happening), or:

1. Check dependencies on new 3rd party modules
2. Check config.php to see if any dependent modules are disabled
3. If dependent modules are disabled, the new 3rd party module **should remain disabled** to prevent any dependency issues.

**Comment by AlldoGroup** [comment]
I can confirm this issue, when upgrading from 2.4.1 to 2.4.2.

**Comment by Serializator** [comment]
I experienced the same issue and disabling "Dotdigitalgroup_Sms" as well resolved it for me. Weirdly enough "Dotdigitalgroup_Sms" **is** specified as a dependency (sequence) in "Dotdigitalgroup_Email", so it's weird that it is enabled in the first place.

**Comment by ihor-sviziev** [comment]
@sivaschenko @gabrieldagama, can this issue be passed to the Digitalgroup bundled extension developers?

**Comment by frithjof** [comment]
can this crapware please be removed from default install?

**Comment by simon-letch** [comment]
@ihor-sviziev The new dotdigital SMS extension was included as part of 2.4.2. Installs that had the core dotdigital extension disabled would cause this error. The cause of it is the SMS extension attempting to add a menu item to the menu the core extension adds. Which in this case doesn't exist as it's disabled.

There are community members which maintain modules to composer replace the bundled extensions. These modules are kept up to date as new releases come out and should save time for developers that do not wish to have the bundled extensions enabled.

**Comment by engcom-November** [comment]
Hi @micwallace 
I am unable to see any error as such after upgrading to 2.4.2. Can you please provide me the step by step commands that you have tried to upgrade from your end to reproduce the issue.
Thank you.

**Comment by asim-blueprintprep** [comment]
Hi @engcom-November 
If you have:
``` 'Dotdigitalgroup_Email' => 0,```
before you run setup:upgrade, and then try to log into the admin, you will get the error.

As 2.4.2 adds in a new module:
```'Dotdigitalgroup_Sms' => 1```
Which requires the Email module to be enabled. 

The solution so far is before running setup:upgrade, to edit app/etc/config.php and set
``'Dotdigitalgroup_Sms' => 0```

**Comment by engcom-November** [comment]
Issue is reproducible on Magento 2.4.2 Composer version
Steps to reproduce:
1. Pull 2.4.2 Modules via composer
2. Disable only Dotdigitalgroup_Email module
3. Run setup:upgrade
4. Login to Magento Admin
Exception: Specified invalid parent id (Dotdigitalgroup_Email::marketing_automation)

![image](https://user-images.githubusercontent.com/60198231/122950944-81bcf200-d39a-11eb-87bb-6d53e999bd5b.png)

**Comment by engcom-November** [comment]
Hi @micwallace,
Issue related to bundle extension is not part of this repository. Please contact the extension owner support on the marketplace (https://marketplace.magento.com/extensions.html) page.
Thank you.
