### ISSUE TITLE
Rest API with XML response

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#3234]
I am trying to create custom api using webapi and we need output in custom XML.
When we are trying to return some XML and  hit the rest API url then XML shown as plain text in the <response> .... </response> tags. It is not creating XML in response.

it shows like this : 
![image](https://cloud.githubusercontent.com/assets/6079017/12744480/82112a22-c9ba-11e5-8e11-d491f5edf39d.png)

Is there any way to modify the response tag to get custom XML response.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-API-with-XML-response/idi-p/45334).
