### ISSUE TITLE
Missing xdebug support

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32349]
### Preconditions (*)

1. 2.4.2 Enterprise
2. xdebug 3.0.3
3. PHP 7.4.3
4. Apache/2.4.41 (Ubuntu)
5. Ubuntu Server

### Steps to reproduce (*)

1. I try to debug magento 2 with xdebug, but if I try to load the home page then I already get this error, even when I did not started the debugger yet.

`Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in /srv/www/vhosts/company_m2/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php:73 Stack trace: #0 /srv/www/vhosts/company_m2/vendor/composer/autoload_real.php(75): require() #1 /srv/www/vhosts/company_m2/vendor/composer/autoload_real.php(65): composerRequire8af7b3a00f767fb4cad56fc4263587ba() #2 /srv/www/vhosts/company_m2/vendor/autoload.php(7): ComposerAutoloaderInit8af7b3a00f767fb4cad56fc4263587ba::getLoader() #3 /srv/www/vhosts/company_m2/app/autoload.php(51): include('/srv/www/vhosts...') #4 /srv/www/vhosts/company_m2/app/bootstrap.php(33): require_once('/srv/www/vhosts...') #5 /srv/www/vhosts/company_m2/pub/index.php(17): require('/srv/www/vhosts...') #6 {main} thrown in /srv/www/vhosts/company_m2/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php on line 73`

### Expected result (*)

1. It should be possible to debug magento 2 with xdebug

### Actual result (*)

1. It is not possible.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
This issue was in the MFTF. Now the issue is fixed https://github.com/magento/magento2-functional-testing-framework/commit/6d6a7c59fc789625345c0b7b071fe08ea68b487b and available in version 3.3.0


Also I see that in magento 2.4.2 we have not too strict requirements, so you should be able to update it using `composer update magento/magento2-functional-testing-framework`
https://github.com/magento/magento2/blob/2.4.2/composer.json#L120

**Comment by Eddcapone** [comment]
magento/magento2-functional-testing-framework was set to 2.4.5 in composer.json. I changed it to ^2.4.5 and updated it. Now the obsolete xdebug_disable() function does not appear anymore, so the error should be gone. Can't test right now though. Thx!
