### ISSUE TITLE
Magento sets user and group for automatically generated files to weird values

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32355]
### Summary (*)

This is not a bug report, but a developer experince issue.
I created a project on a dev server and deleted the folders in generated/code.
If I load the homepage, then code is getting generated, but it has weird user and group combination:

```
company@server:/srv/www/vhosts/company_m2/generated/code$ ls -lah
total 64K
drwxrwxr-x  16 company  www-data 4,0K Mär  3 14:28 .
drwxrwxr-x   4 company  www-data 4,0K Mär  3 13:50 ..
drwxrwxr-x   3 www-data www-data 4,0K Mär  3 14:27 ADM
drwxrwxr-x   8 www-data www-data 4,0K Mär  3 14:28 Amasty
drwxrwxr-x   4 www-data www-data 4,0K Mär  3 14:27 Amazon
drwxrwxr-x   3 black   sudo     4,0K Mär  3 14:28 Composer
drwxrwxr-x   3 www-data www-data 4,0K Mär  3 14:27 Dotdigitalgroup
drwxrwxr-x   3 black   sudo     4,0K Mär  3 14:28 EthanYehuda
drwxrwxr-x   3 www-data www-data 4,0K Mär  3 14:27 Ho
drwxrwxr-x 107 www-data www-data 4,0K Mär  3 14:28 Magento
drwxrwxr-x   5 black   sudo     4,0K Mär  3 14:28 Migration
drwxrwxr-x   3 black   sudo     4,0K Mär  3 14:28 PayPal
drwxrwxr-x   3 www-data www-data 4,0K Mär  3 14:27 Psr
drwxrwxr-x   3 black   sudo     4,0K Mär  3 14:28 Symfony
drwxrwxr-x   3 www-data www-data 4,0K Mär  3 14:27 Vertex

```

black is the user which I used to connect to the server via SSH.
But since the files are generated by the webserver I wonder why it is set to "black" ?

Do I miss some magento configuration or is it a pure webserver problem?

### Examples (*)

-

### Proposed solution

-

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/file-system-perms.html
