### ISSUE TITLE
Backorder Use Config Setting not properly used in sql query

### ISSUE THREAD

**Issue by iflam** [magento/magento2#32358]
### Preconditions (*)

Magento 2.4.1
MSI enabled

### Steps to reproduce (*)

1. Enable backorders via Stores > configuration > catalog > inventory
2. Set Out of Stock threshold to -2
3.  Create a product with quantity -2 for all sources
4. Within the product's advanced inventory, make sure "Use Config Setting" is checked under "Backorder"

### Expected result (*)

1. Product should display "Out of Stock" on frontend, because the out of stock threshold is reached.
![image](https://user-images.githubusercontent.com/34324129/109885534-a4d95f80-7c4c-11eb-996c-16f02011c595.png)

### Actual result (*)

1.  Product always displays "In Stock".
2. Within InventoryIndexer/Indexer/Stock/IndexDataProviderByStockId.php, the $select statement contains a sql query which sets is_salable with the following statement: 
```
( 
    legacy_stock_item.use_config_backorders = 1 
    OR legacy_stock_item.backorders <> 0
    AND ( 
            legacy_stock_item.min_qty >= 0
            OR legacy_stock_item.qty > legacy_stock_item.min_qty
        )
)
```

However, this implies that if use_config_backorders is set to 1, it will always be true. This should not be the case.

It should be something similar to:
```
IF(item.use_config_backorders = 1, :config_backorders, item.backorders) <> 0
AND ( 
            legacy_stock_item.min_qty >= 0
            OR legacy_stock_item.qty > legacy_stock_item.min_qty
        )
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @iflam 

Thank you for your report.

The MSI related issues should be reported into a separate https://github.com/magento/inventory/issues repository.

Can you please open the same issue but in the [Inventory](https://github.com/magento/inventory/issues) repo.

Thank you

**Comment by iflam** [comment]
https://github.com/magento/inventory/issues/3295
