### ISSUE TITLE
Installation is incomplete.  Check the console log for errors before trying again.

### ISSUE THREAD

**Issue by gokhanayan** [magento/magento2#3236]
Hello friends. I knew very little English. I'm having problems mentioned in the Annex picture file. I've seen similar problems living here. But what I did not try the solution. How can you help me?

Meanwhile, I'm using a server installed CentOS. I have no problem installing Magento 1.9.2. But I get this question when I want to install Magento 2.

![hata](https://cloud.githubusercontent.com/assets/17006175/12718660/ba409a62-c8f8-11e5-9a9a-bb98697b6fc2.jpg)

**Comment by gokhanayan** [comment]
In the meantime, I'd like you guidance as to tell one very beginner. Because I'm very new at this.

**Comment by mazhalai** [comment]
@gokhanayan have you tried changing `max_execution_time` as specified here? http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_70pct.html

**Comment by gokhanayan** [comment]
Unfortunately, the result is still the same. Error continues. It is going to 95% when incomplete.

**Comment by ghost** [comment]
@gokhanayan Sorry to ask a dumb question but did you restart your web server after you made that change?

**Comment by gokhanayan** [comment]
Yes, I restart. But the most natural right to ask you this question. I said because I was a beginner.

**Comment by ghost** [comment]
Look in `var/update_status.log` for errors. Look in your web server logs also. Please paste the entire error messages here.

**Comment by mazhalai** [comment]
@gokhanayan are you in developer mode or production? Please turn on developer mode, if it is not already on.

**Comment by gokhanayan** [comment]
Steve and Mazhalai, thank you very much for your interest 

How to Run in developer mode. I have no information in this regard. In addition, there are magento2 not specified in the log.

**Comment by ghost** [comment]
[Enable developer mode](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html#config-mode)

**Comment by mazhalai** [comment]
please see

**Comment by mazhalai** [comment]
Sorry clicked close accidentally

**Comment by eddielau** [comment]
@gokhanayan Please try to enable PHP error logging and see if anything is logged.
To enable it, in your php.ini file, add

```
log_errors=1
error_log=<path to a log file>
```

Then restart the web server and reinstall Magento again.

**Comment by mazhalai** [comment]
@gokhanayan closing due to non-responsiveness
