### ISSUE TITLE
System-Setting Menu

### ISSUE THREAD

**Issue by gokhanayan** [magento/magento2#3237]
Let you choose which part of the left side of the system settings menu. On the right side of the section that does not display the necessary arrangements. Additional pictured are available.
![hata2](https://cloud.githubusercontent.com/assets/17006175/12719075/82508e52-c8fb-11e5-8d89-e56f8393e001.png)

**Comment by gokhanayan** [comment]
Is there that can help?

**Comment by vrann** [comment]
@gokhanayan From the screenshot it seems like Magento 1.x. Can you confirm that your question is about Magento 2?

**Comment by maksek** [comment]
Not relevant to Magento 2
