### ISSUE TITLE
Got error after logged in as customer after logged in expired.

### ISSUE THREAD

**Issue by webkul-dhananjay** [magento/magento2#32388]
### Preconditions (*)

Magento 2.4.2
Php- 7.4.9
reproducible.

### Steps to reproduce (*)

Leave the session expired for the logged in customer and re- login as customer.

### Expected result (*)
should be logged in successfully

### Actual result (*)
shown error message after login 

https://prnt.sc/105nv8p

**Comment by ihor-sviziev** [comment]
Hi @webkul-dhananjay,
From the screenshot you provided, it feels like an issue in the custom extension Digitalgroup/Chat. Could you contact the support of this extension?

**Comment by webkul-dhananjay** [comment]
> Hi @webkul-dhananjay,
> From the screenshot you provided, it feels like an issue in the custom extension Digitalgroup/Chat. Could you contact the support of this extension?

Sure

**Comment by engcom-Oscar** [comment]
Hi @webkul-dhananjay ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.

### Steps to reproduce (*)
1. Create new customer from homepage
2. Login as new customer
3. Leave the session expired for the logged in customer
4. Try re- login as customer.

**Actual Result:** :heavy_check_mark: 
Customer logged in successfully

So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.
