### ISSUE TITLE
Create store view using the command line

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#3238]
Hi, it would be cool, if someone could setup the shop using the command line. For example to set the other language, someone would need just this code to run on command line:

```
composer config repositories.atconnect composer https://connect20.aveo-trade.cz
composer require atconnect/magento-two-language-de-de:2.*

php bin/magento setup:store-view:new "Main Website Store" DE de 1 1
php bin/magento setup:store-view:edit setLang de_DE
```

I know that setup:store-view: does not exists, so please give to this post label "improvement" or "feature request"

Thanks

**Comment by TommyKolkman** [comment]
Agree! Saves me a lot of clicking!

**Comment by Vinai** [comment]
:+1: from me to being able to create websites store views on the command line. However, I don't know if this should be part of the core. It could be provided by a community extension.

Maybe setting the language can already already be done using `bin/magento setup:store-config:set --language=de_DE`

See
```
$ bin/magento help setup:store-config:set                                                                                                                    ✖ ✹ ✚ ✭
Usage:
 setup:store-config:set [--base-url="..."] [--language="..."] [--timezone="..."] [--currency="..."] [--use-rewrites="..."] [--use-secure="..."] [--base-url-secure="..."] [--use-secure-admin="..."] [--admin-use-security-key="..."] [--magento-init-params="..."]
```

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Create-store-view-using-the-command-line/idi-p/44754).
