### ISSUE TITLE
[Issue - Important] - Problems with login

### ISSUE THREAD

**Issue by UncleKhab** [magento/magento2#32386]
### Preconditions (*)

1. Magento ver. 1.9.3.0
2. Any browser

### Steps to reproduce (*)

1. Try to login on any browser
2. Try to login with incognito

### Expected result (*)

1. Login and be redirected to dashboard.

### Actual result (*)

1. After completing the login fields with correct credentials, the page just reloads without redirecting to the dashboard
2. Sometimes it shows an error (Invalid username or password)
3. If I try to login with incognito mode, same credentials, **sometimes** is works, sometimes it doesn't.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @UncleKhab 

Thank you for your report. 

This is a known issue, connected with disabling URL Rewrites. The PR for the issue is here https://github.com/magento/magento2/pull/32099
