### ISSUE TITLE
Order created_at field showing wrong datetime in grid + order view page

### ISSUE THREAD

**Issue by davidandersson1** [magento/magento2#32385]
Hello,

We are using Magento version 2.3.5 + MySQL 5.7!

We are facing issue with order created_at time, its showing 1 hour behind compare to our timezone(Europe/Stockholm). (db field created_at and grid has same value)

We are using AWS RDS + ec2 instances for database and storefront and RDS showing UTC in all three fields as per below query
SELECT @@global.time_zone, @@session.time_zone,@@system_time_zone

EC2 showing
Time zone: Europe/Stockholm (CET, +0100)

Through phpinfo() function, we can see Default timezone = Europe/Berlin (same timing as Europe/Stockholm)

Magento backend configuration we set globally "Central European Standard Time(Europe/Stockholm)" at General -> General ->  Locale Options, store and website level same as global scope.

if anyone faced same issue and know about solution for this issue then please help!

Thanks in advance!
David Andersson

**Comment by davidandersson1** [comment]
Hello,

Is there any solution for this issue?

Please help!

**Comment by davidandersson1** [comment]
We have fixed the issue!

It was one timezone file corrupted on the server(RDS), which now is fixed. and this did not reflected the correct time on PHP.
date_default_timezone_set('UTC');

**Comment by engcom-Bravo** [comment]
Hi @davidandersson1,

Glad to know the issue was fixed. Closing the ticket henceforth. Kindly re-open the ticket for any concerns.
