### ISSUE TITLE
While updating the order status increment_id is also updating why?

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#32397]
### Preconditions (*)

1. Magento version 2.3.1

### Steps to reproduce (*)

1. Call the API /rest/V1/orders
2. Provide the following request in API
 {"entity":{"entity_id":287,"status":"pending"}}
 3. Now downlaod the order id 287 
 4. You will see increment_id is updated on UI and in order downlaod response as well. 

### Expected result (*)

1. When we are updating only status it should only update status. it should not update increment_id

### Actual result (*)

1. When we are updating the  status it should only update status. its updating increment_id

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @webgility-amazonapi !
Thank you for report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps  from this ticket.
As result i have Order status updated, but entity_id still the same.
![Screenshot from 2021-03-11 14-30-36](https://user-images.githubusercontent.com/60198413/110787763-6d833800-8276-11eb-8183-7604dc27a658.png)
![Screenshot from 2021-03-11 14-30-48](https://user-images.githubusercontent.com/60198413/110787779-7247ec00-8276-11eb-9dcf-997f0d466af1.png)

May you recheck it and add more details how to reproduce it please!

**Comment by webgility-amazonapi** [comment]
Hello Slava Moskalyuk
We are asking about the increment_id. When we are updating the status only the increment_id is automatically gets updated.

**Comment by engcom-Oscar** [comment]
@webgility-amazonapi 
![Screenshot from 2021-03-12 11-00-47](https://user-images.githubusercontent.com/60198413/110917265-6154b480-8322-11eb-9d9e-2415c48d59e2.png)
increment_id is not changed as well. Please recheck it on clean Magento instance, without 3rd part extentions.

**Comment by engcom-Oscar** [comment]
@webgility-amazonapi   Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Comment by webgility-amazonapi** [comment]
Hello Magento Support,

This issue is not yet resolved. Can you please reopen it and let us know the ETA.

Thanks,
Webgility
