### ISSUE TITLE
Error when loading javascript

### ISSUE THREAD

**Issue by ad1rie1** [magento/magento2#3239]
Helllo, 
I just update to 2.0.2 install but , after upgrade, almost all javascript in client page don' load . 

I have an error 404, the load URL is : 
http://127.0.0.1:443/index.php/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)

But on my other install, it load the file in : 
http://127.0.0.1:8080/static/frontend/Magento/luma/en_US/jquery.js

One idea because it's append ?

**Comment by mrkhoa99** [comment]
You try to run deploy command: _php bin/magento setup:static-content:deploy_ under root folder

**Comment by ad1rie1** [comment]
i have already done that :) no change , i thinck it's redirection problem because it don't look in static file, it consider load page named jquery.js

**Comment by ad1rie1** [comment]
i see in requirejs-config.js : require.config({"baseUrl":"http://domain.com/static/frontend/Athena/theme-frontend-luma/fr_FR"});

and in my new config nothing.... how this file was generated and where i can configurate the BaseUrl argument of this script ?

**Comment by ad1rie1** [comment]
ok , it's realy update, i revert all to 2.0 and it's work just fine

**Comment by ad1rie1** [comment]
are you change commit about requireJs in framework or in her utilisation in module gererate requirejs-config.js ?
it's work with default magento theme but if you don't use magento directory, bug happend

**Comment by ad1rie1** [comment]
I have overide default file layout in my theme :) and one change has happend in the update
