### ISSUE TITLE
Eliminate laminas/laminas-mvc-console dependency

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32407]
`laminas/laminas-mvc-console` dependency was temporarily introduced in https://github.com/magento/magento2/pull/31854 for Laminas Sevrice Manager, MVC and DI dependencies update.

Considering that this package is deprecated, it is required to move all necessary functionality to the Magento side and remove the dependency.

Target branch: `php8-develop`

**Comment by ihor-sviziev** [comment]
It feels like it's quite related to https://github.com/magento/magento2/issues/32321, as there is a notice "We recommend using laminas/laminas-cli.". Probably moving to laminas/laminas-cli will allow us to remove this dependency at all

**Comment by hws47a** [comment]
@magento I am working on this
