### ISSUE TITLE
Tax data-label attribute disappear after translation

### ISSUE THREAD

**Issue by csvikram44** [magento/magento2#32401]
### Summary (*)
I noticed that Tax data-label working for English(default) language. After translate the text **Excl. Tax** to other languages it removed or disappear because CSS missing or not working for other languages. Every where it displaying using CSS and CSS written for **data-label="Excl. Tax"** only.

### Examples (*)
I attached 2 screenshots for cart and checkout page.
![image-issue-1](https://user-images.githubusercontent.com/16976794/110480662-c040e080-810c-11eb-8683-84942ff25a5e.jpg)
![image-issue-2](https://user-images.githubusercontent.com/16976794/110480675-c2a33a80-810c-11eb-908a-87da47b47e32.jpg)

### Proposed solution
There are many solutions to fix this issue.
1. CSS should be update related to data-label for every language after translation.
2. Remove current CSS code and make it dynamic like other label working like color etc.

I translate text in Swedish language and write custom css for that and working for me.
"Excl. tax","Exkl. moms"
![image-issue-3](https://user-images.githubusercontent.com/16976794/110482548-cb950b80-810e-11eb-9783-0e3d1dbbe1a0.jpg)

Thanks
Vikram K

**Comment by mrtuvn** [comment]
What version that you get problem ?

**Comment by csvikram44** [comment]
I get issue on 
"magento/product-community-edition": "2.3.5-p2"

**Comment by mrtuvn** [comment]
Seem i don't get problem like your describe (Tried in latest version 2.4-develop + sample data with german locale)
![Screenshot from 2021-03-10 20-30-17](https://user-images.githubusercontent.com/1908873/110637096-a0c6b800-81df-11eb-9dc5-5d6f37047023.png)

**Comment by mrtuvn** [comment]
#1 text still visible not be hidden
#2 test translate as we expected relate german
