### ISSUE TITLE
URL key "standard" matches a reserved endpoint name (admin, soap, rest, graphql, standard, swcradmin). Use another URL key.

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#32408]
### Preconditions (*)

1. Magento 2.3.6
2. This URL is actually a sub-category: example.com/category/standard
3. We upgraded from 2.3.0

### Steps to reproduce (*)

1. Create Category with sub-category URL standard
2. Try and save category
3. This error pops up. 
4. This is actually an existing category.

### Expected result (*)

1. No error.

### Actual result (*)

1. Error: URL key "standard" matches a reserved endpoint name (admin, soap, rest, graphql, standard, swcradmin). Use another URL key.

I'm not sure why this is popping up. Is standard a reserved endpoint? And if it is, how is it associated even when hidden behind a sub-category?

**Comment by nickpiro** [comment]
@magento give me 2.3.6 instance

**Comment by nickpiro** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment]
Hi @nickpiro !
The described issue is expected behavior for Magento 2.4 latest release, so have to close this ticket as non-issue.

**Comment by nickpiro** [comment]
@engcom-Oscar thats very strange behavior considering we already have categories that end in standard. Are you saying that these categories are causing an issue somehow? Also, how does /sub-category/sub-category/standard not be able to be used? You’re saying a company cannot have products that are called “standard”? 

There is no explanation as to what is the reasoning? What’s the reason that this is expected behavior? So you’re telling me I have to tell my client they have to change a URL that they’ve had for years because Magento suddenly doesn’t allow them to use it?

**Comment by nickpiro** [comment]
Any guidance would be nice! @engcom-Oscar
