### ISSUE TITLE
Missing Content on Checkout Screen

### ISSUE THREAD

**Issue by lsmithcom** [magento/magento2#3240]
I just opened an account with Nexcess and they installed Magento 2 on a shared hosting server.  The only changes made so far are through the admin panel, so I have not changed any code.

In testing out the site features I tested the Checkout pages.  When you go to the Checkout and then attempt to sign in via the link, but do not do so successfully and then go to forgot password and then back through the cart to get to the checkout,  the page is blank except for the order summary box and the sign in.  So all the fields to Checkout are blank.  Once you follow that path and get a blank screen, any time you return to the checkout you get that blank screen.   

I am not sure if there were any mistakes made in the installation process, since it was performed by Nexcess.

**Comment by ishakhsuvarov** [comment]
@lsmithcom Thank you for reporting the issue. We have tried to reproduce it, but currently with no success.
To help us resolve the problem faster, please provide more detailed steps to reproduce, your Magento version and changes you have done in admin panel.
Thanks.

**Comment by ishakhsuvarov** [comment]
@lsmithcom Closing the ticket for now. Feel free to reopen if this issue persists.
