### ISSUE TITLE
Admin Dashboad is not displaying properly

### ISSUE THREAD

**Issue by dnsahoo** [magento/magento2#3242]
I am working on Full HD (1920 x 1080) resolution. Following are the atttached screen shot. 

![dashboad2](https://cloud.githubusercontent.com/assets/1394129/12727284/4bc95cc8-c942-11e5-951c-40aa5d3659ce.png)
![dashboad1](https://cloud.githubusercontent.com/assets/1394129/12727285/4bcaef48-c942-11e5-9514-b221c620aedf.png)

**Comment by jstuardo** [comment]
Check permissions of folder pub amd below. I had similar problems before, and the problem was that files had 660 permissions, instead of 664 and folders 750 permissions instead of 755.

**Comment by serzhik** [comment]
Run at console from your magento2 installation path

`php bin/magento setup:static-content:deploy`

**Comment by dnsahoo** [comment]
Thank you Serzhik,

After running this  command, Magento Dashboard displaying properly. 

I am using Windows machine.

But other modules like Sales, Products, Customer etc are not displaying properly (like previous Dashboard).

**Comment by dnsahoo** [comment]
Hi Jstuardo,

I am using Windows 10 (Full HD 1920 x 1080 resolution). Can you please suggest, how to fix it. By running the command given by Serzhik, it only fix Dashboard. How to fix other modules like Sales, Products, Customer etc.

Thank You.

**Comment by serzhik** [comment]
@dnsahoo, can you show your browser console errors?

**Comment by dnsahoo** [comment]
Hi Serzhik,

I am here with attaching screenshot of my browser console. There is a warning message, no errors.

![consolr_magento2](https://cloud.githubusercontent.com/assets/1394129/12953552/f5cb290e-d040-11e5-8d5e-5b961bd9967e.jpg)

**Comment by serzhik** [comment]
@dnsahoo errors on pages that do not work, please.

**Comment by dnsahoo** [comment]
I did not get any page with error. Except Dashboard (after running your command), all the page design gets break.

**Comment by dnsahoo** [comment]
Hi Serzhik and Jstuardo,

I am able to resolve the issue, it was a browser font issue in my Chrome browser. Long time ago, I made a little changes (increasing font size) in my chrome browser, which causes the issue. 

Sorry for my mistake,

Thank you.

**Comment by dnsahoo** [comment]
Hi Serzhik and Jstuardo,

I am able to resolve the issue, it was a browser font issue in my Chrome browser. Long time ago, I made a little changes (increasing font size) in my chrome browser, which causes the issue.

Sorry for my mistake,

I am closing this issue.

Thank you.
