### ISSUE TITLE
Magento 2.3.5-p2 EE customer receives default Welcome email regardless of config setting

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#32429]
### Preconditions (*)

1. Magento 2.3.5-p2 EE installed
2. B2B Company module is enabled

### Steps to reproduce (*)

1. Go to Email Templates
2. Click create new template
3. Load new account registration email template
4. Customize
5. save template
6. Go to Customer configuration
7. Set customized template as template to send on new account registration
8. Go to front end
9. Create Company via the /company/account/create form

### Expected result (*)

1. Email address entered into the Company registration is sent welcome email with customizations

### Actual result (*)

1. Default `account_new` email template is sent

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @nbennett25 !
Thank you for your report.
If I understand your issue right, to change email template for Company registration you need to do it in Admin -> Configuration -> Customers -> Company Configuration -> Email Options - Company Registration -> Default Company Registration Email. Please re-check
![Screenshot from 2021-03-11 13-36-56](https://user-images.githubusercontent.com/60198413/110781729-ed0d0900-826e-11eb-95c7-e8bf12088e71.png)

**Comment by nbennett25** [comment]
Thx @engcom-Oscar - I should have been more clear - even with the Admin -> Configuration -> Customers -> Company Configuration -> Email Options - Company Registration -> Default Company Registration Email set to the customized template, the system is still sending the default one.

**Comment by engcom-Oscar** [comment]
Hi @nbennett25  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
### Steps to reproduce (*)
B2B Company module is enabled
1. Go to Email Templates
2. Click create new template
3. Load new account registration email template
4. Customize
5. save template
6. Go to  Admin -> Configuration -> Customers -> Company Configuration -> Email Options - Company Registration -> Default Company Registration Email.
7. Set customized template as template to send on new account registration
![Screenshot from 2021-03-11 13-36-56](https://user-images.githubusercontent.com/60198413/110913204-83980380-831d-11eb-81ef-03bc6af51c53.png)
8. Go to front end
9. Create Company via the /company/account/create form

**Actual Result:** :heavy_check_mark: 
I got registration email with my customized template
![Screenshot from 2021-03-12 10-23-38](https://user-images.githubusercontent.com/60198413/110913310-a4f8ef80-831d-11eb-8e12-94d49fc46746.png)

Did you flush the cache after making changes in configuration?
