### ISSUE TITLE
Cart page error with Porto theme

### ISSUE THREAD

**Issue by diegozanotti** [magento/magento2#32438]
### Preconditions (*)
1. Magento 2.3.6 in developer mode
2. Porto theme 3.2.6
3. Paypal and Stripe checkout methods
4. PHP 7.3 and Debian 4.9.246-2 (dedicated virtual machine)
5. website: https://www.00up.app/magento2/

### Steps to reproduce (*)
1. Go to catalog
2. Add product to cart (one or more)
3. Click on shopping bag top right
4. Open mini cart
5. Click on bottom button (view or edit cart) - "Visualizza e modifica il carrello"

### Expected result (*)
1. Display cart page (checkout/cart/)

### Actual result (*)
1. Cart page return error (checkout/cart/)

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': The attribute 'name' is required but missing.
Line: 1219

Element 'argument': Not all fields of key identity-constraint 'blockReferenceActionArgumentName' evaluate to a node.
Line: 1219

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'argument': The attribute 'name' is required but missing.
Line: 1219

Element 'argument': Not all fields of key identity-constraint 'blockReferenceActionArgumentName' evaluate to a node.
Line: 1219

<pre>#1 Magento\Framework\Config\Dom->__construct('<layout xmlns:xs...', &Magento\Framework\App\Arguments\ValidationState#00000000797756090000000074da638e#, array(), NULL, '/var/www/vhosts/...', '%message%\nLine: ...') called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Framewor...', array('<layout xmlns:xs...', &Magento\Framework\App\Arguments\ValidationState#00000000797756090000000074da638e#, array(), NULL, '/var/www/vhosts/...', '%message%\nLine: ...')) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#3 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Framewor...', array('xml' => '<layout xmlns:xs...', 'schemaFile' => '/var/www/vhosts/...', 'validationState' => &Magento\Framework\App\Arguments\ValidationState#00000000797756090000000074da638e#)) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create('Magento\Framewor...', array('xml' => '<layout xmlns:xs...', 'schemaFile' => '/var/www/vhosts/...', 'validationState' => &Magento\Framework\App\Arguments\ValidationState#00000000797756090000000074da638e#)) called at [vendor/magento/framework/Config/DomFactory.php:43]
#5 Magento\Framework\Config\DomFactory->createDom(array('xml' => '<layout xmlns:xs...', 'schemaFile' => '/var/www/vhosts/...', 'validationState' => &Magento\Framework\App\Arguments\ValidationState#00000000797756090000000074da638e#)) called at [vendor/magento/framework/View/Model/Layout/Update/Validator.php:141]
#6 Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:xs...', 'layout_merged', false) called at [vendor/magento/framework/View/Model/Layout/Merge.php:512]
#7 Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend_...', '<body>\n   <refer...') called at [vendor/magento/framework/View/Model/Layout/Merge.php:488]
#8 Magento\Framework\View\Model\Layout\Merge->load(array()) called at [generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php:206]
#9 Magento\Framework\View\Model\Layout\Merge\Interceptor->load() called at [vendor/magento/framework/View/Layout/Builder.php:86]
#10 Magento\Framework\View\Layout\Builder->loadLayoutUpdates() called at [vendor/magento/framework/View/Layout/Builder.php:63]
#11 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:224]
#12 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:247]
#13 Magento\Framework\View\Page\Config->getTitle() called at [vendor/magento/module-checkout/Controller/Cart/Index.php:57]
#14 Magento\Checkout\Controller\Cart\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Checkout\Controller\Cart\Index\Interceptor->___callParent('execute', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Checkout\Controller\Cart\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Checkout\Controller\Cart\Index\Interceptor->___callPlugins('execute', array(), array(array('amazon_login_car...'))) called at [generated/code/Magento/Checkout/Controller/Cart/Index/Interceptor.php:26]
#18 Magento\Checkout\Controller\Cart\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#19 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Checkout\Controller\Cart\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Checkout\Controller\Cart\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\Checkout\Controller\Cart\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...', 'multishipping_cl...'))) called at [generated/code/Magento/Checkout/Controller/Cart/Index/Interceptor.php:39]
#23 Magento\Checkout\Controller\Cart\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/App/FrontController.php:186]
#24 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#, &Magento\Checkout\Controller\Cart\Index\Interceptor#00000000797754280000000074da638e#) called at [vendor/magento/framework/App/FrontController.php:118]
#25 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#26 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#27 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#28 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000797756660000000074da638e#, &Closure#00000000797756450000000074da638e#, &Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#29 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#30 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000797756660000000074da638e#, &Closure#00000000797756450000000074da638e#, &Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#31 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#32 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#33 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000007977572c0000000074da638e#) called at [vendor/magento/framework/App/Http.php:116]
#34 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#35 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#36 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000797757d60000000074da638e#) called at [index.php:39]
</pre>

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Seem this problem related to porto theme and not from magento
Some layout of your theme rely on argument tag but it's missing name attribute (this is required)
Search in entire your theme files and locate the missing tag argument

**Comment by diegozanotti** [comment]
> Seem this problem related to porto theme and not from magento
> Some layout of your theme rely on argument tag but it's missing name attribute (this is required)
> Search in entire your theme files and locate the missing attribute name in tag argument

Thank you for your fast reply! Unfortunately I'm new in Magento, can you please suggest me how to check and fix it?

**Comment by mrtuvn** [comment]
You should search all tag argument in XML files in your porto scope theme to indicates missing required name one

**Comment by diegozanotti** [comment]
Ok, will try, thank you very much!

**Comment by diegozanotti** [comment]
> You should search all tag argument in XML files in your porto scope theme to indicates missing required name one

I have tried to set LUMA theme instead PORTO, and have the same error, so should be not Porto theme error...

**Comment by mrtuvn** [comment]
What about switch to blank theme ?

**Comment by diegozanotti** [comment]
Yes I have tried with blank theme too... same error

**Comment by mrtuvn** [comment]
Maybe cause from layout modules. It's hard to tell you without see direct code. You should re-test with sample instance. Clean install without any customise

**Comment by krishprakash** [comment]
Hi @diegozanotti. Thank you for your report.
GitHub issue tracker is intended for Magento core technical issues only
Kindly refer community forum or Magento stack exchange for general discuss about this topic
