### ISSUE TITLE
New product need to add at bottom position at the category product list instead of top

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#32431]
### Steps to reproduce (*)
1. Create 3 product in the one category
2. Set position for this product 1, 2 and 3
3. Create one more product in the same category

### Expected result (*)
1. Last created product should be at the end of category product list

### Actual result (*)
1. Last created product at the first position of category product list (position is set as 0)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @vijay-prevaj!
It is correct that new product  added to current category get position '0' in the 'products in category' list, but you can change this position manually afterwards or apply Category Rules (Magento Commerce only) for products sorting (https://docs.magento.com/user-guide/catalog/category-product-rules.html). 
So I'm closing this ticket as non-isuue.
