### ISSUE TITLE
Update laminas/laminas-captcha dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#32443]
Update laminas/laminas-captcha dependency to PHP 8 compatible version

Depends on the new laminas/laminas-captcha version release.
That depends on the pull request: https://github.com/laminas/laminas-captcha/pull/7
That depends on the PHP 8 compatible version for laminas-recaptcha
That depends on the pull request: https://github.com/laminas/laminas-recaptcha/pull/5

**Comment by hws47a** [comment]
@magento I am working on this
