### ISSUE TITLE
Product View Page - Meta Description Fix

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#3244]
Magento\Catalog\Block\Product\View
line 146 - $this->pageConfig->setDescription($this->string->substr($product->getDescription(), 0, 255));

we put table tags in product description and got missaligned text in head of page.. 
<.meta name="description" content="<.table style="width: 763px;" border="0">.....

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2295, https://github.com/magento/magento2/issues/1514, https://github.com/magento/magento2/issues/3090, https://github.com/magento/magento2/issues/3255
https://mage2.pro/t/161

**Comment by vzabaznov** [comment]
@artmiller bug was fixed and delivered to develop branch, thank you for contributing, please feel free to add new issues or write, if fix doesn't help.
