### ISSUE TITLE
Tier Price Refresh after custom option price change in simple product

### ISSUE THREAD

**Issue by ocirneb** [magento/magento2#32445]
Preconditions (*)
Magento 2.3.1

Steps to reproduce (*)
Create single product with tier prices and custom options that change price

Expected result (*)

When i change custom option in product page 
single price change
tier price table change

Actual result (*)
only single price change

**Comment by engcom-Oscar** [comment]
Hi @ocirneb !
If I get it right, you created for your simple product 'Customizable Options' which if selected, add additional cost to product price, but it not suppose to affect 'Tier prices' table, like here:
![Screenshot from 2021-03-12 16-03-33](https://user-images.githubusercontent.com/60198413/110950473-8f4eee80-834c-11eb-8db4-140fe7b04ffc.png)
Please re-check

**Comment by ocirneb** [comment]
> Hi @ocirneb !
> If I get it right, you created for your simple product 'Customizable Options' which if selected, add additional cost to product price, but it not suppose to affect 'Tier prices' table, like here:
> ![Screenshot from 2021-03-12 16-03-33](https://user-images.githubusercontent.com/60198413/110950473-8f4eee80-834c-11eb-8db4-140fe7b04ffc.png)
> Please re-check

yes this is the problem

**Comment by engcom-Oscar** [comment]
Hi @ocirneb !
Unfortunately vanilla Magento doesn't apply 'Customizable Options' additional price to Tier prices the way how you expected. 
So I'm closing this ticket as non-issue.  
You may look for some custom modules on Magento Marketplace to find appropriate solution for your case or submit PR with your own solution for that.

**Comment by ocirneb** [comment]
Hi @engcom-Oscar i created my module thanks anyway
