### ISSUE TITLE
Configurable product shows price of options excluding tax when configured to show prices including tax

### ISSUE THREAD

**Issue by pmbright** [magento/magento2#32453]
### Preconditions (*)

1. Magento CE 2.3.6
2. PHP 7.3.27
3. Ubuntu 20.04.1

### Steps to reproduce (*)

1. Ensure that the store is configured to show prices including tax.
2. Create a configurable product with size and colour attributes
3. Change the price of some of the simple products that were created by the configurable product wizard.  In our case we have one size that has a higher price than the rest.
4. View the configurable product page on the store front.
5. With no options selected, the "as low as" price correctly shows the price including tax
6. Select any size and colour combination.
7. Observe the updated price.

### Expected result (*)

1. When the size and colour attributes are selected We expect to see the price including tax.

### Actual result (*)

1. When the size and colour attributes are selected we see that the price shown is excluding tax even though its configured to show prices including tax
2. When the product is added to cart the price does actually include the tax as expected.

**Screenshot showing no attributes selected, price is the lowest price including tax.**
![image](https://user-images.githubusercontent.com/28593265/110818085-da9dca00-8284-11eb-9c07-c1525477fcc6.png)

**Screenshot showing size and colour selected, price shown is excluding tax   (156.99 / 1.2 == 130.82)**
![image](https://user-images.githubusercontent.com/28593265/110818213-f7d29880-8284-11eb-96f1-a821bbfedb25.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [*] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmbright** [comment]
I have confirmed that the issue is present using the Luma theme, so it does not appear to be related to the Theme our store uses.

**Comment by pmbright** [comment]
Issue is reproduced on our test server.  Here is a link to a product showing the issue:   https://test.bbwear.co.uk/deluxe-bee-suit

**Comment by pmbright** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment]
Hi @pmbright ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
### Steps to reproduce (*)
1. Configure in Admin that the store is configured to show prices including tax.
![Screenshot from 2021-03-12 14-18-59](https://user-images.githubusercontent.com/60198413/110939343-ec8f7380-833d-11eb-9a27-72e58012ce42.png)

2. Create a configurable product with size and colour attributes
3. Change the price of some of the simple products that were created by the configurable product wizard.  In our case we have one size that has a higher price than the rest.
4. View the configurable product page on the store front.
5. With no options selected, the "as low as" price correctly shows the price including tax
6. Select any size and colour combination.
7. Observe the updated price.

**Actual Result:** :heavy_check_mark: 
Product with no options selected:
![Screenshot from 2021-03-12 14-19-26](https://user-images.githubusercontent.com/60198413/110939456-1ea0d580-833e-11eb-98bd-ca41d5d4f0a6.png)

Product with both options selected:
![Screenshot from 2021-03-12 14-19-47](https://user-images.githubusercontent.com/60198413/110939519-3710f000-833e-11eb-9700-8be36dcb4443.png)

This product in the cart:
![Screenshot from 2021-03-12 14-20-01](https://user-images.githubusercontent.com/60198413/110939554-455f0c00-833e-11eb-834c-3c2574849958.png)

Can you please recheck this issue on the 2.4-develop instance?

**Comment by pmbright** [comment]
Hi Thanks for looking into this.

So the steps to reproduce didnt take into consideration a lot of configuration options such as currrency and tax settings and tax rates.   Apologies for that. 

Using the develop instance created here for me (see above) Ive changed the currency to GBP and set the default tax rate to 20% (UK VAT) and been through all the config settings in sales -> tax to make sure its as per my own website.

Ive created a test product but even though the tax setting for sales -> tax -> calculation settings -> catalog prices is set to "including tax" (meaning that prices entered into the magento admin include tax already) the store frontend is adding the 20% tax to the price I entered in the admin!

Product SKU:  pmbtest
Product URL:  https://a37015557ebeb88688e39ce3d598ee41-2-4-develop.instances.magento-community.engineering/pmbtest.html

For example the price of all sizes except Large is entered in magento admin as £152.99 (the price including VAT) but the store front shows it as £183.59.  And the Large sizes are entered into magento admin as £181.99 (the price including VAT) but the store front shows it as £218.39.  This is not quite the issue I originally opened!  But there is something odd going on there.

I have cleared the caches and invalidated the indexes, resaved the product and refreshed the page but the problem persists.

Here is a screenshot of the most relevant tax settings;

![image](https://user-images.githubusercontent.com/28593265/110958105-3da26600-8344-11eb-8c6d-80dd0bf0c1ae.png)

**Comment by pmbright** [comment]
The problem goes away when I change the tax settings for "price display settings" and "shopping cart display setting" to be "including and excluding tax".  Which is fine by us.

Ill just leave the issue there since it was hard to replicate here.
