### ISSUE TITLE
How to Use Magento 2 translation "pt_BR" from CrowdIn ?

### ISSUE THREAD

**Issue by cerebrumgit** [magento/magento2#3245]
How to Use Magento 2 translation "pt_BR" from CrowdIn ?

Hello Good afternoon my friend

1)

Based on the following post

http://magento.stackexchange.com/questions/99915/use-magento-2-translation-for-example-german-from-crowdin/99935#99935

I am making the following to use the translation for pt_BR language

http://cerebrumgit.github.io/instala%C3%A7%C3%A3o/instalando-magento2#pacote-de-tradução-pt_br

But as picture, we see that the error is displayed

"Requested languages: pt_BR File" /i18n/pt_BR.csv "does not exist>"

Do you have any information about this incident because I plan to use this translation pack

http://pasteboard.co/1eIoZv6N.png

http://pasteboard.co/1eIsgplB.png

The strange thing is that when I update the page, we see that the proper translation is displayed

http://pasteboard.co/1eIMGoxK.png

2)

What would be your recommendation for me to use the translation "pt_BR"?

**Comment by thomvanderboon** [comment]
Take a look here:

http://www.vanderboon.net/wiki/Install_Test_Magento_2_Translation

It is a description of the Dutch (nl_NL) language, but with these steps you should be able to get your translation working

**Comment by maksek** [comment]
please use forums for questions, GitHub only for bugs and PR.
