### ISSUE TITLE
Admin Grid date range filter not working as expected

### ISSUE THREAD

**Issue by Zwernemann** [magento/magento2#32456]
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. In Backend select "Sales/Orders".
2. Click on "Filters" and add a date range filter for "purchase date" and apply this filter. The filtered grid will appear as expected.
3. Click on "Clear all" to remove this filter
![filter2](https://user-images.githubusercontent.com/52236002/110911760-6100ed00-8313-11eb-953a-1a08d3276b04.JPG)

### Expected result (*)

After removing the filter the date range should be cleared when you click next time on "Filters". 

### Actual result (*)

The date range is still filled out. Even worse, if you click next time on "Apply filters" (without modifying the date range), this date range is not applied.

![filter](https://user-images.githubusercontent.com/52236002/110911393-ec2db300-8312-11eb-88fd-3067ab2a0588.JPG)

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41301` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment]
Sorry, closed by mistake

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42404` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41301` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zwernemann, @engcom-Foxtrot. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-42404` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42404` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zwernemann, @engcom-Foxtrot. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-42404` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @Zwernemann, @engcom-Foxtrot. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41301` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
@Den4ik Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42404` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment]
Issue fixed in https://github.com/magento/magento2/commit/86acabb3a77042d986af7232b91f60f08a70c29a
