### ISSUE TITLE
Magento erroneously assums one category is parent of another based on category path

### ISSUE THREAD

**Issue by dot319** [magento/magento2#32464]
### Preconditions (*)

1. Magento 2.4-develop
2. Admin side: Have a category tree where 2 categories exists side by wide, where 1 category id starts with the category id of the other. (Like id 14 and id 146.)
 For example:

- Default Root Category (id:2)
- - Child Category Products (id:3)
- - - Child-child category Example One (id:14)
- - - Child-child category Example Two (id:146)
Example Screenshot
![image](https://user-images.githubusercontent.com/51679138/122874478-a7bda480-d350-11eb-8d99-6a27b878815f.png)

### Steps to reproduce (*)

1. Somewhere in the code base, call \Magento\Catalog\Model\CategoryManagement::move(14, 146) to try and move the category with id 14 into the category with id 146

Ex: We can call move method inside the new simple model controller class created as like below code:

    protected $_pageFactory;
    public function __construct(
    \Magento\Framework\App\Action\Context $context,
    \Magento\Catalog\Model\CategoryManagement $pageFactory)
    {
    $this->_pageFactory = $pageFactory;
    return parent::__construct($context);
    }
    
    public function execute()
    {
        echo "Hello World";//die;
        $this->_pageFactory->move(14, 146);
        echo "Manju11";
        die;
    }

### Expected result (*)

1. The category with id 14 is moved into the category with id 146

### Actual result (*)

1. An error is thrown 'Operation do not allow to move a parent category to any of children category'

This happens because in the method \Magento\Catalog\Model\CategoryManagement::move there exists the assumption that if strpos($parentPath, $path) === 0, the category you are trying to move is a parent of the category you are trying to move it into. While actually in this case they are 'siblings', their paths are '1/2/14' and '1/2/146'.

Below is the complete report log generated:
{
	"0": "Operation do not allow to move a parent category to any of children category",
	"1": "#1 Mks\\Helloworld\\Controller\\Index\\Index->execute() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:58]\n#2 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->___callParent() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:138]\n#3 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:153]\n#4 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->___callPlugins() called at [generated\\code\\Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor.php:23]\n#5 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->execute() called at [lib\\internal\\Magento\\Framework\\App\\Action\\Action.php:111]\n#6 Magento\\Framework\\App\\Action\\Action->dispatch() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:58]\n#7 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->___callParent() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:138]\n#8 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:153]\n#9 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->___callPlugins() called at [generated\\code\\Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor.php:32]\n#10 Mks\\Helloworld\\Controller\\Index\\Index\\Interceptor->dispatch() called at [lib\\internal\\Magento\\Framework\\App\\FrontController.php:245]\n#11 Magento\\Framework\\App\\FrontController->getActionResponse() called at [lib\\internal\\Magento\\Framework\\App\\FrontController.php:212]\n#12 Magento\\Framework\\App\\FrontController->processRequest() called at [lib\\internal\\Magento\\Framework\\App\\FrontController.php:147]\n#13 Magento\\Framework\\App\\FrontController->dispatch() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:58]\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:138]\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\\code\\Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor.php:99]\n#16 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:135]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\\code\\Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin.php:75]\n#18 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:135]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [lib\\internal\\Magento\\Framework\\Interception\\Interceptor.php:153]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\\code\\Magento\\Framework\\App\\FrontController\\Interceptor.php:23]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [lib\\internal\\Magento\\Framework\\App\\Http.php:116]\n#22 Magento\\Framework\\App\\Http->launch() called at [generated\\code\\Magento\\Framework\\App\\Http\\Interceptor.php:23]\n#23 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [lib\\internal\\Magento\\Framework\\App\\Bootstrap.php:264]\n#24 Magento\\Framework\\App\\Bootstrap->run() called at [pub\\index.php:29]\n",
	"url": "\/Mks\/Index\/Index",
	"script_name": "\/index.php",
	"report_id": "876d49429e34c918d1163ad0b48fb02baab92e59889dec335691fc4e0b137805"
}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dot319** [comment]
I confirmed this issue on my local vanilla Magento environment.

**Comment by hostep** [comment]
This shouldn't have been closed, it sounds valid at first sight. @Den4ik or @ihor-sviziev, can we get somebody to verify this first before it gets closed without any attention? Thanks!

**Comment by ihor-sviziev** [comment]
@gabrieldagama, feels like it should be prioritized as P1 or P2

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @dot319 

Tried to reproduce in Magento 2.4-develop version, and unable to successfully reproduce it. Below are the steps I followed.

1. Created a separate root category and added 2 sub categories into it (While adding categories, manipulated in such a way that, ID 14 and 146 should fall under a separate created category) 

2. Cleaned cache and refreshed the UI page, made sure that UI content is updated properly.

3. Tried to drag and drop the category that is having ID:14, under the category ID:146

4. After moving the category inside its sibling, refreshed the page as well. There is no such error message I noticed.

Here is the screen record that I tried to reproduce in Magento 2.4-develop version
https://user-images.githubusercontent.com/51679138/122394747-f0154500-cf93-11eb-8584-126b2f96eee1.mp4

Hope I have followed correct steps to reproduce as per my understanding.
- If there is any change you want to do in the execution considering above steps, kindly inform me the required change mentioning that step number.
- If you are expecting other output for any of the other step, kindly mention that expected output with the step number only please.
- If you want to add/remove any step from the list, kindly tell me what is that you want to add/remove and in between which step number.

**Comment by dot319** [comment]
Hi @engcom-Alfa 
Thanks for the message!

If I understand correctly, in step 3 you try to drag and drop the category with id:14 into the category with id:146 in the admin panel, correct? The bug I reported is occurring in \Magento\Catalog\Model\CategoryManagement::move(14, 146). I believe dragging and dropping a category in the admin panel doesn't make use of that specific method, so you wouldn't be able to reproduce the bug that way.

I encountered this bug when I was trying to programmatically move categories using Magento\Catalog\Model\CategoryManagement::move().

**Comment by engcom-Alfa** [comment]
Thanks for the updates @dot319 

I have re tested it, and it is reproducible. Hence I have updated the description with more information and confirming the issue.

Thanks for your contribution!

In case of any Magento related issues, you may please report a bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide]

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42692` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mozok** [comment]
@magento I am working on this
