### ISSUE TITLE
GraphQL: add category_url_path to ProductAttributeFilterInput

### ISSUE THREAD

**Issue by paales** [magento/magento2#32460]
*As a Developer I want to be able to filter `products()` on `category_url_path` so that I'm able to request all products for a category in a single query.*

Currently we have to do the following:

First query
```graphql
query CategoryData($urlPath: String!) {
  # We fetch the complete category in the first query
  categories(filters: { url_path: { eq: $urlPath } }) {
    items {
      uid
      ...OtherFields
    }
  }

  # Alternatively we get the entity_uid from the urlResolver
  urlResolver(url: $urlPath) {
    entity_uid
  }
}
```

After that query completes, we run the following query:

```graphql
query ProductListFiltered($uid: String!, $color: String!) {
  products(filter: { category_uid: { eq: $uid }, color: { eq: $color } }) {
    ...FilteredProducts
  }
}
```

This costs lots of extra latency (~300ms) and extra load on Magento (because it has to startup twice)

### AC

Make a modification to the schema:

```graphql
input ProductAttributeFilterInput {
  """Filter product by the url_path String for a `CategoryInterface` object."""
  category_url_path: FilterEqualTypeInput
}
```

Be able to query all information in one go:

```graphql
query CategoryWithFilteredProducts($urlPath: String!, $color: String!) {
  categories(filters: { url_path: { eq: $urlPath } }) {
    items {
      uid
      ...OtherFields
    }
  }
  products(filter: { category_url_path: { eq: $urlPath }, color: { eq: $color } }) {
    ...FilteredProducts
  }
}
```

### Approved Schema

..

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by rodrigowebjump** [comment]
@magento give me 2.3 instance

**Comment by rodrigowebjump** [comment]
@magento give me 2.3.5-p2 instance

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Verified the behavior on Magento 2.4-develop instance and current Magento behavior does not support category_url_path for "ProductAttributeFilterInput" also not mentioned in official Magento [Dev docs](https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#productfilterinput-attributes) . Hence we are considering this as an enhancement and labelling as feature request.
Thank you.
