### ISSUE TITLE
Wrong "min" and "max" prices when logged in via GraphQL using SharedCatalogs 

### ISSUE THREAD

**Issue by jonataswebjump** [magento/magento2#32466]
### Preconditions (*)

Magento 2.3.5-p2

### Steps to reproduce (*)

When the customer is logged in via GraphQL, the valuee of "min_price" and "max_price" returned are the values of public Shared Catalog. 

In this method, the customer_group_id filter is not applied:
 \Magento\Catalog\Model\ResourceModel\Product\Collection::_productLimitationPrice

Local where the query is analysed (expected result and actual result prints): 
vendor/magento/module-catalog-graph-ql/Model/Resolver/Products/DataProvider/ProductSearch.php

SQL Query:

`SELECT `e`.*,
       IF(at_status.value_id > 0, at_status.value, at_status_default.value)             AS `status`,
       IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS `visibility`,
       `price_index`.`price`,
       `price_index`.`tax_class_id`,
       `price_index`.`final_price`,
       IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price),
          price_index.min_price)                                                        AS `minimal_price`,
       `price_index`.`min_price`,
       `price_index`.`max_price`,
       `price_index`.`tier_price`
FROM `catalog_product_entity` AS `e`
       INNER JOIN `catalog_product_entity_int` AS `at_status_default`
                  ON (`at_status_default`.`row_id` = `e`.`row_id`) AND (`at_status_default`.`attribute_id` = '289') AND
                     `at_status_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_int` AS `at_status`
                 ON (`at_status`.`row_id` = `e`.`row_id`) AND (`at_status`.`attribute_id` = '289') AND
                    (`at_status`.`store_id` = 1)
       INNER JOIN `catalog_product_entity_int` AS `at_visibility_default`
                  ON (`at_visibility_default`.`row_id` = `e`.`row_id`) AND
                     (`at_visibility_default`.`attribute_id` = '295') AND `at_visibility_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_int` AS `at_visibility`
                 ON (`at_visibility`.`row_id` = `e`.`row_id`) AND (`at_visibility`.`attribute_id` = '295') AND
                    (`at_visibility`.`store_id` = 1)
       INNER JOIN `catalog_product_index_price` AS `price_index`
                  ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND
                     price_index.customer_group_id = 0
WHERE (e.created_in <= 1)
  AND (e.updated_in > 1)
ORDER BY `price_index`.`min_price` DESC
LIMIT 9`

In query, the Customer Group Id is public.
**price_index.customer_group_id = 0**

GraphQL Query to reproduce:

`query category(
    $id: Int!
    $pageSize: Int!
    $currentPage: Int!
    $onServer: Boolean!
    $filters: ProductAttributeFilterInput!
    $sort: ProductAttributeSortInput
) {
    category(id: $id) {
        id
        description
        name
        product_count
        meta_title @include(if: $onServer)
        meta_keywords @include(if: $onServer)
        meta_description
    }
    products(
        pageSize: $pageSize
        currentPage: $currentPage
        filter: $filters
        sort: $sort
    ) {
        items {
            __typename
            meta_description
            name
            id
            stock_status
            sku
            peso_caixa
            conservacao
            special_price
            price_tiers {
                quantity
                discount {
                    percent_off
                }
                final_price {
                    value
                    currency
                }
            }
            price {
                regularPrice {
                    amount {
                        currency
                        value
                    }
                }
            }
            ... on ConfigurableProduct {
                configurable_options {
                    attribute_code
                    attribute_id
                    id
                    label
                    values {
                        default_label
                        label
                        store_label
                        use_default_value
                        value_index
                    }
                }
                variants {
                    attributes {
                        code
                        value_index
                    }
                    product {
                        id
                        media_gallery_entries {
                            id
                            disabled
                            file
                            label
                            position
                        }
                        sku
                        stock_status
                    }
                }
            }
        }
        page_info {
            total_pages
        }
        total_count
    }
}
7:02
{
	"currentPage": 1,
	"id": CATEGORY_ID,
	"filters": {
		"category_id": {
			"eq": "CATEGORY_ID"
		}
	},
	"onServer": false,
	"pageSize": 12,
	"sort": {
		"price": "ASC"
	}
}`

### Expected result (*)

![Screenshot from 2021-03-12 11-25-06](https://user-images.githubusercontent.com/27784517/110953139-c8c03380-8325-11eb-8acb-3539293470bb.png)

### Actual result (*)

![Screenshot from 2021-03-12 11-24-22](https://user-images.githubusercontent.com/27784517/110953197-d970a980-8325-11eb-86ff-9da41bdada24.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jonataswebjump** [comment]
@magento give me 2.3.5-p2 instance

**Comment by jonataswebjump** [comment]
@magento give me 2.3.5-p2 instance

**Comment by jonataswebjump** [comment]
@magento give me 2.3.5 instance

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by tuyennn** [comment]
@jonataswebjump I found this issue on Magento 2.4.7, do you have this fixed already?
