### ISSUE TITLE
One or more indexers are invalid (when installed through cpanel)

### ISSUE THREAD

**Issue by dervism** [magento/magento2#3247]
I know this is issue might have been discussed in another ticket, but I still can't get it working.

I installed Magento 2.0.2 on my shared hosting though CPanel and Softaculous and have set up the cron jobs. I have only access to the CPanel interface as the shop is on the shared hosting server, so no command line access.

The job is running and printing "Ran jobs by schedule." in the log, but in Magento admin I still have the error message "One or more indexers are invalid" and nothing has been updated.

This is the command that get executed: /usr/bin/php /home/public_html/shop/bin/magento cron:run

Any ideas?

**Comment by tudn9x** [comment]
Hi, you can try checking table "cron_schedule" in the database. I think you can find issue with that.

**Comment by dervism** [comment]
@htmyheart Everything there is "success" except the two first rows:

catalog_index_refresh_price, error, Bad value was supplied.
aggregate_sales_report_coupons_data, running, Class Magento\SalesRule\Crone\AggregateSalesReport

**Comment by tudn9x** [comment]
Hi, Did you clear cache?
In row two, I think class should be: Cron. Your class is Crone, it was wrong.

**Comment by dervism** [comment]
@htmyheart Yes, I have cleared the cache several times. I updated the text you mention to "cron". The error message is still there, doesnt look like it had any effect.

As I said, all the other rows are "sucess", so it look like it runs the job and updates the database table....

**Comment by tudn9x** [comment]
Sorry, my English. Yes, sure, when your cronjob ran, status of jobs will update to this table. I don't have any solution for your issue, please search again and try another way.

**Comment by dervism** [comment]
@htmyheart I think I solved it.

I added another cron job in CPanel and then the error message disappered and all my products are now visible on my shop!

Looks like this cron job must be run the first time after Magento is installed in CPanel:
/usr/bin/php /home/public_html/shop/bin/magento indexer:reindex

**Comment by tudn9x** [comment]
Yep, thanks for your share. I will remember this issue. Usually, when I finished installing Magento, I will run reindex and clear cache. :)

**Comment by PaddlePop** [comment]
help! I also faced the same issue and added the cron job in my cpanel. However I received an error message "bin/magento must be run as a CLI application". I am total newbie. I also installed Magento 2 on my shared hosting though CPanel and Softaculous, also do not have access to command line. Please advise! Thanks

**Comment by dervism** [comment]
The reason you see that message is because the path to PHP is wrong. You also need two cron jobs, not just one, configured in your CPanel:
- magento cron:run
- magento indexer:reindex

To get these two working, you need to specify the full path to both PHP (look further down in this post for how-to find it) and your Magento-installation.

**magento cron:run**
In my CPanel, I added the "cron:run" like this (replace "foobar" with your own magento folder name if it's in a sub-folder or remove it if not, that is, if it is directly in the public_html folder):

`/opt/alt/php55/usr/bin/php /home/dervism/public_html/foobar/bin/magento cron:run | awk '{ print strftime("\%Y-\%m-\%d \%H:\%M:\%S"), $0; fflush(); }' 2>&1 >> /home/dervism/public_html/shop/cron.log` 

The job will now run and write the output to the "cron.log" file, which you can view in the CPanel File Manager. 

**magento indexer:reindex**
Then I added the "indexer:reindex" like this:

`/opt/alt/php55/usr/bin/php /home/dervism/public_html/foobar/bin/magento indexer:reindex >/dev/null 2>&1`

While developing the site, I set both jobs to run every 2nd minute: 
`*/2    *   *   *   *`

Go back to your Magento Admin frontend and delete the cache and wait 2 minutes. The error messages should disappear.

**PHP full path**
You might wonder how I found the full path to PHP:
1. In your CPanel File Manager, browse to your shops public folder
2. In the root folder, where Magento's index.php file is, create a file called info.php
3. Paste in this code:

```
<?php
phpinfo();
?>
```
1. Save, and then open another browser tab and open the url to this file. Example something like www.your-shop-domain.com/shop/info.php
2. Search for "php" on that page and you'll find the full path

That's it. Remember to delete the info.php file when get everything up and running. Btw: It's seems like it's possible to connect to CPanel though [SSH](https://documentation.cpanel.net/display/ALD/SSH+Shell+Access), however, I myself didn't need to do this. It was more easy to create the info.php.

Hope this helps.

**Comment by PaddlePop** [comment]
Hi. Thank so much for your help! I actually already have the other cron job you asked me to add. It was already added by softacculous? If I am right. However, I managed to solve it last night before I see your reply. I added the below.  

"php-cli -q /home/admin/public_html/Store/bin/magento indexer:reindex >/dev/null 2>&1"

It was fixed. Although I still receive an email (refer to below) Not too sure if I should ignore it since my problem was fixed. Can you also advise? I accidentally added CAPS "S" to my store when creating magento on softaculous. Do you know how I should change it safely? Your help is very appreciated! 

"/usr/local/cpanel/bin/jailshell: line 1: 883837 Killed php-cli -q /home/admin/public_html/Store/bin/magento indexer:reindex > /dev/null 2>&1"
