### ISSUE TITLE
Magento 2 MFTF test : Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by dhirajdanodeborn** [magento/magento2#32479]
Hello Support team

We are running the Magento function testing framework in Magento 2.4.2 enterprise.
We used devious documentation for all setups.
https://devdocs.magento.com/mftf/docs/getting-started.html

while runing below command we are getting issue,
vendor/bin/codecept run functional -c dev/tests/acceptance/codeception.yml
vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove

Could anyone can help on this.

**Here is the issue**
1) AdminLoginSuccessfulTestCest: Admin login successful test
 Test  tests/functional/Magento/_generated/default/AdminLoginSuccessfulTestCest.php:AdminLoginSuccessfulTest

  [Facebook\WebDriver\Exception\UnknownErrorException] unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: '62f55528a568', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1040-azure', java.version: '1.8.0_282'
Driver info: driver.version: unknown
remote stacktrace: #0 0x55b6020212b9 \<unknown>                                                                                                                        
#1  /var/www/magento/releases/48/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
#2  /var/www/magento/releases/48/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
#3  /var/www/magento/releases/48/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
#4  /var/www/magento/releases/48/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php:749
#5  /var/www/magento/releases/48/vendor/symfony/event-dispatcher/EventDispatcher.php:264
#6  /var/www/magento/releases/48/vendor/symfony/event-dispatcher/EventDispatcher.php:239
#7  /var/www/magento/releases/48/vendor/symfony/event-dispatcher/EventDispatcher.php:73

**Comment by dhirajdanodeborn** [comment]
Hello support team

**Summary of the issue**
	Magento functional testing framework test showing error :- Chrome failed to start: exited abnormally
**Information on your environment**
  Magento vanilla 2.4.2 Enterprise
**Steps to reproduce**
	https://devdocs.magento.com/mftf/v2/docs/getting-started.html
	Followed all the steps as per devdocs document, istall java seleniumn, chorme driver 
	and followed the steps as per document.
	
	For below command we are getting error,
	vendor/bin/codecept run functional -c dev/tests/acceptance/codeception.yml
	vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove
	
	AdminLoginSuccessfulTestCest: Admin login successful test
	Test tests/functional/Magento/_generated/default/AdminLoginSuccessfulTestCest.php:AdminLoginSuccessfulTest
	[Facebook\WebDriver\Exception\UnknownErrorException] unknown error: Chrome failed to start: exited abnormally.
	(unknown error: DevToolsActivePort file doesn't exist)
	(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
	
**Expected and actual results**
	Test should run smoothly without any error.

**Comment by engcom-Bravo** [comment]
Hi @dhirajdanodeborn ,

I followed all the steps as per https://devdocs.magento.com/mftf/docs/getting-started.html and I was able to run the test successfully. Please find the below screenshot for reference.

![image](https://user-images.githubusercontent.com/51680745/123068702-c47cd980-d42f-11eb-9d1d-b8bef55aca9c.png)

<br><br>
For Chrome web-driver related issue, kindly ensure you have below points in place:
1. Chromedriver file path should be correct in the below command or you can copy the driver file to the current path where you are executing this command and run the command as it is.
<pre class="highlighter" style="box-sizing: border-box; font-family: Courier, Consolas, monospace; display: block; word-break: break-all; overflow-wrap: break-word; white-space: pre; overflow: auto; margin: 0px; padding: 10px; color: rgb(43, 43, 44); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box; font-family: Courier, Consolas, monospace; font-size: 0.875rem; white-space: pre; overflow-wrap: normal;">

java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.14.0.jar
--


</code></pre>

<br><br>
2. Selenium server should be up and running before you run sample tests like below.

![image](https://user-images.githubusercontent.com/51680745/123069594-8b913480-d430-11eb-96f3-9b259514b167.png)

<br><br>
3. Also, ensure that the chromedriver version and the chrome browser you have in your system are of the same version.

Please try and let me know if you are able to solve it.

**Comment by engcom-November** [comment]
@dhirajdanodeborn ,
We are closing this issue as there has been no latest update on the same.
Thank you.
