### ISSUE TITLE
Magento2-Base archive is broken

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3248]
I have build my own satis server for more performance than `repo.magento.com`. Therefore I added the magento 2 repository to my `satis.json` file. 

After mirroring the magento composer I can't install magento 2 because `magento2-base` and `magento2-ee-base` modules are broken. There are files missing, for example the `app/design/` folder. Then the mapping fails und I can't install the shop.

```
[196.5MB/62.54s] Generating autoload files
[197.2MB/62.99s] start magento deploy via deployManager
[197.2MB/62.99s] start magento deploy for magento/magento2-base
[197.2MB/67.78s] Source /var/www/sites/html/vendor/magento/magento2-base/app/design/frontend/Magento does not exist
[197.2MB/67.78s] start magento deploy for magento/magento2-ee-base
[197.2MB/69.13s] Source /var/www/sites/html/vendor/magento/magento2-ee-base/app/design/doc does not exist
```

I debugged into satis and stopped after downloading the archive from `repo.magento.com`. Inside the zip archive the files are also missing, so that is no satis problem on my site.

**Comment by atishgoswami** [comment]
I had encountered this issue a while ago #2787. Its an issue with the Satis [#289](https://github.com/composer/satis/issues/289)

**Comment by marvincaspar** [comment]
I did some more research and found the issue.

The `magento2-base` and `magento2-ee-base` includes empty folders. Theres are ignored by composer when create a new archive with [PharData::buildFromDirectory](http://php.net/manual/de/phardata.buildfromdirectory.php). 

Solution could be to add a `.keep` file in empty folders.

**Comment by ktomk** [comment]
Or add a `.gitignore` file in those directories that is ignoring everything but itself:

```
*
!.gitignore
```

Should be easy to patch.

**Comment by okorshenko** [comment]
Internal ticket MAGETWO-50039

**Comment by diabeeto076** [comment]
Magento 2.0.4 has been released today and this still hasn't been fixed. 
Composer won't fix empty directories anytime soon either. i've created a PR where .keep files were added to empty directories when building the archive (not downloading as suggested in the post of Feb 2 of this issue). 
https://github.com/JBleijenberg/composer/blob/keep-empty-directories/src/Composer/Package/Archiver/ArchivableFilesFinder.php#L65
But they don't want to manipulate archives, which i can understand.

So please fix this so we can use satis to mirror the packages.

**Comment by ktomk** [comment]
@JBleijenberg: There is nothing in upstream composer to fix IMHO. Whether or not this needs a "fix" in M2 core I can't say, however I'd say that making use of the _.gitkeep_ like `.gitignore` files is not hurting at all. It's perhaps similar to placing `.htaccess`  files everywhere (with even some questionable settings but that's a different story). It would fix the issue you address.

The suggested pull request unfortunately contains a broken commit, I just left [a comment](https://github.com/magento/magento2/pull/3550#issuecomment-204551553) perhaps it gets some traction.

**Comment by m0zziter** [comment]
I've replied to @ktomk's comment on my pull request and will have time over the next few days to review it.

In the meantime, I would suggest taking a look at Toran Proxy https://toranproxy.com/. The most current version supports private composer repos. We've had a lot of success using this instead of Satis.

**Comment by ktomk** [comment]
@m0zziter: Toran proxy is a great help, but mentioning it here is distracting to a high degree. Also I have problems to understand why you need to review your own pull request. I mean you filed it in the first place and you just wrote you left out the first line by intention, so not that it looks like you entirely don't know what you're doing, it would be great you give a reason why I shouldn't just provide a new PR that would be much quickier then to write comments here... .. ???

**Comment by m0zziter** [comment]
I apologize to anyone else who found my suggestion of Toran Proxy "distracting to a high degree", I was merely trying to provide help.

Writing your own pull request probably would be quicker than commenting here; I would say "I encourage anyone to submit a pull request" but I see you've already done that. Hopefully the double pull request will get Magento's attention.

**Comment by ktomk** [comment]
Sorry for the distraction, I'm merely interested in what is behind the removal of the first line.

**Comment by ktomk** [comment]
@mc388: [Composer has been patched ca. 4 hours ago](https://github.com/composer/composer/pull/5144#issuecomment-205021044) and I've tested it with satis, archived packages do contain empty directories now.

Example path: 

```
/app/design/frontend/Magento/
```

is in the zip (`magento-magento2-base-2.0.4.zip`) as empty directory.

I was not able to reproduce your original report (my Magento 2 setup via satis fails at a different point), but the re-packaged zips in my satis archive directory contain the just shown directories (and they didn't earlier). But I can't confirm those empty directories are actually created when unziped via the installer.

So if you could give it a try would be great. Just do a _composer update_ in your satis and it should resolve (in theory).

**Comment by marvincaspar** [comment]
@ktomk Thank you for your fix.

Currently I'm not able to test this but I will try asap.

**Comment by astorm** [comment]
@ktomk Thanks for being on top of this -- wish I'd stumbled across this thread on Thursday instead of late Friday night ;)  Data point of 1, but after updating composer and satis to the latest versions, and clearing out my composer cache, this fixed an empty directory issue for me. 

Related: Do you (or does anyone else here) have any insight on this new issue https://github.com/composer/composer/issues/5206?  It seems like changing one archive format to behavior differently from the other might introduce potential problems down the line.  Or am I misunderstanding something about composer's/Satis's implementation here?

**Comment by ktomk** [comment]
Just in late review, we fixed the related issue as well (/cc @astorm).

@mc388: I think we're green here since about a year and this can be closed, right?

**Comment by marvincaspar** [comment]
@ktomk I will close this issue but I am not able to test this, because I do not longer develop in Magento 2.
