### ISSUE TITLE
Magento doesn't respect codesniffer rules

### ISSUE THREAD

**Issue by MajorKuprich** [magento/magento2#32483]
### Summary (*)

1. Override **Magento\Framework\App\ExceptionHandler** class in custom module (by preference in **di.xml**).
2. Override **handleBootstrapErrors** function to define a new template.
3. Run code sniffer for newly created module:
 `phpcs --standard=Magento2 --extensions=php,phtml --error-severity=10 --ignore-annotations app/code/Company/Module`.

Report throws error:
`ERROR   | "require" statement detected. File manipulations are discouraged. Variables inside are insecure.`

### Proposed solution

Replacing **require** with a function that meets the requirements of the code sniffer.

### Sources
https://devdocs.magento.com/marketplace/sellers/code-sniffer.html
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @MajorKuprich,

Could you please elaborate on the steps to reproduce the issue along with screenshots if any?

**Comment by engcom-Bravo** [comment]
Hi @MajorKuprich ,

We are closing this ticket as we did not receive any update. Please open a new ticket if you are still facing this issue.

Thanks.
