### ISSUE TITLE
How to include e-mail template in email template?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32480]
### Summary (*)

I am creating a new template in: **Marketing -> Communication: E-Mail Templates -> Create new template**.
I also created a template in my theme: **THEME/Magento_Email/email/usp.html**

I even added this code to one of my modules:

## app/code/Company/Base/etc/email_templates.xml:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Email:etc/email_templates.xsd">
    <template id="custom_email_usp_template" label="USP Block" file="usp.html" type="html" module="Magento_Email" area="frontend"/>
</config>

```

How can I include it in the template?

I tried it like this:

`{{template id="custom_email_usp_template"}}`

But if I preview the template then I just get: **{Error in template processing}**

The header and footer are getting added like this:

`{{template config_path="design/email/header_template"}}`

I basically want to do it just like this, but it is no where documented how this is done.

### Examples (*)

see above

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aligent-skumar** [comment]
I believe you want to get the email template work, but the email template layout handle tag usage is to be fixed:

Below is a rough idea of the steps to get the email template working:

1.create a template - which you have already done.
 magento/app/code/NameSpace/ModuleName/etc/email_templates.xml

2. Define the email template - which should look something like this
magento/app/code/NameSpace/ModuleName/view/frontend/email/usp.html

`{{template config_path="design/email/header_template"}}
                    {{layout handle="my_custom_email_handle" area="frontend"}}
{{template config_path="design/email/footer_template"}}`

3.Define the layout handle if required like below: 
magento/app/code/NameSpace/ModuleName/view/frontend/layout/my_custom_email_handle.xml

`<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"
      label="Subscription renew notification email items" design_abstraction="custom">
    <block name="test.email.viewmodel" class="Magento\Framework\View\Element\Template" template="NameSpace_ModuleName::my_email_template.phtml">
        <arguments>
            <argument name="view_model" xsi:type="object">NameSpace\ModuleName\ViewModel\<ViewModelClass></argument>
        </arguments>
    </block>
</page>`

**Comment by Eddcapone** [comment]
Thanks for your answer, can you please format your XML correctly in your post?

**Comment by aligent-skumar** [comment]
@Eddcapone I've formatted the xml, let me know if that helps.

**Comment by Eddcapone** [comment]
@aligent-skumar Thx, what content needs to be in the .phtml file from the block `test.email.viewmodel` and how do I know what code is required for the view_model?

**Comment by Eddcapone** [comment]
Thank you it worked :) But I had to omit the `arguments` section, not sure why I one would need them.

**Comment by Eddcapone** [comment]
I have to reopen the issue. I noticed that you can't use code like this in the template if you include it via layout directive:

`{{config path='general/store_information/postcode'}} {{config path='general/store_information/city'}}`

**Comment by engcom-Lima** [comment]
Hi @Eddcapone,  May know the issue status? If still you are facing the issue while including e-mail template then follow the below steps:

- create ’email_templates.xml’ file in folder ‘Tutorial/Math/etc’.
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Email:etc/email_templates.xsd">
	<template id="math_template" label="Hello World" file="math.html" type="html" module="Tutorial_Hello" area="frontend"/>
</config>`

- Now create email template file ‘math.html’ in folder ‘Tutorial/Math/view/frontend/email’.
`


{{template config_path="design/email/header_template"}}
		<table cellspacing="0" cellpadding="0" border="0" width="100%">
			<tr>
				<td align="center" valign="top" style="padding:20px 0 20px 0">
					<table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
						<tr>
							<td valign="top">
						<h1 style="font-size:22px;font-weight:normal;line-margin:0 0 11px 0;">{{trans "Hello"}},</h1>
							</td>
						</tr>
						<tr>
							<td>
								<table cellspacing="0" cellpadding="0" border="0" width="650">
									<tbody>
										<tr>
											<td colspan="2" valign="top" style="font-size:12px;padding:7px 9px 9px 9px;border:1px solid #EAEAEA;">
												{{var message}}
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA;text-align:center;">
								<center>
									<p style="font-size:12px;margin:0;">
										<strong>{{trans "Thank you"}}</strong>
									</p>
								</center>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	{{template config_path="design/email/footer_template"}}`

![Screenshot_1](https://user-images.githubusercontent.com/60198022/121890551-1a6ac680-cd38-11eb-8cf3-c5d79f08b20b.png)

Also you can visit below document:
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email.html

**Comment by engcom-Lima** [comment]
Hi @Eddcapone 

I hope your issue has been resolved now. Hence closing this ticket.

Please feel free to open the new ticket if you have any other issue.

Thanks
