### ISSUE TITLE
Magento 2 with Azure Mysql Server table issues with temporary tables

### ISSUE THREAD

**Issue by hsb1007** [magento/magento2#32484]
Currently we have 2 magento instances on Azure environment using Azure mysql and Azure Kubernetes Service.

Users found that logging into both backend and frontend does not work with generic errors: There has been an error processing your request.

One of the site started from 12th March and the other site was first reported today.

In the error log, it was found that Magento is trying to query against some of the temporary db tables and it complains that those db tables do not exist.

When we check the db, we found a long list of temporary tables and reports that the particular table exists (show tables;) however when we ran query on the table, it throws an error saying the table doesn't exist.

These tables vary from "search" tmp tables to catalogue temp tables. 

We have tried
- Refresh the db
- Restart the db (it removed all the temp tables from show tables but it grows back again)
- Redeploying the db

None of the workarounds worked except for the restore of the database that hasn't worked last few days.

And it takes a bit of time until the db gets messed up and presents the same error again.

Has anyone experienced this before?

We are not sure if it is Magento or Azure mysql specific issue. 

Any insight would be appreciated

**Comment by harizyusoff** [comment]
@hsb1007 how did you solve this issue ? I'm having same error for this
