### ISSUE TITLE
Upgrading via composer deletes dev/tests/integration/etc/install-config-mysql.php

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#3249]
In order to execute integration tests, I copied the file `dev/tests/integration/etc/install-config-mysql.php.dist` to `dev/tests/integration/etc/install-config-mysql.php` and adjusted the mysql connection credentials for the test database.
After the upgrade I discovered the file has been deleted.
I would expect local copies to persist between upgrades, just like local `phunit.xml` copies do, so it seems like a bug to me.

**Comment by davidalger** [comment]
Seems similar to #3097

**Comment by Vinai** [comment]
True that. In this case the initial install was done via composer create-project, but probably the same issue.

**Comment by davidalger** [comment]
My guess is the fault is buried somewhere in magento-composer-installer, since it's what's copying in the stuff from magento-base. I just don't have time to dig in to find out atm :)

**Comment by Vinai** [comment]
With the modules residing in `vendor` now, and projects being created via `composer create-project`, I wonder if the magento composer installer is still needed at all. My feeling is that it should be possible to remove it without too much effort.

**Comment by davidverholen** [comment]
The only things that the installer should still do is create the base folder structure for the web app and the vendor_path.php, right?

The current installer still has all the features from the hackathon magento1 installer. That seems very overloaded.

**Comment by davidalger** [comment]
The `composer create-project` just uses the package you reference as a basis for the new project. One of the dependencies of the `magento/project-community-edition` package is `magento/magento2-base` which is what requires the composer installer. Last I checked, everything outside of vendor comes in via this `magento/magento2-base` package, and the composer installer is the mechanism used to copy / move the files from that into place when `create-project` runs.

**Comment by davidverholen** [comment]
ok then, if the magento/magento2-base only contains the base folder structure for the web app, wouldn't it be better to directly download it to the web root instead of first downloading it to vendor and then copy it there.

The approach of symlinking / copying the files is only a leftover of the magento1 installer where it was necessary to have all files at specific places in your web root

**Comment by Vinai** [comment]
Just experienced this issue again while upgrading from 2.0.2 to 2.0.3.
On a side note, the custom files `dev/tests/*/phpunit.xml` did not get deleted during the upgrade.

**Comment by alankent** [comment]
http://alankent.me/2016/03/31/m2-project-source-code-management-recommendation/ talks about this a bit as well (but probably does not add much to the above discussion).

**Comment by Vinai** [comment]
Still happens when upgrading from 2.0.4 to 2.0.5.

**Comment by mazhalai** [comment]
@all have created ticket MAGETWO-52617 to investigate and fix.

**Comment by KrystynaKabannyk** [comment]
Hello @Vinai, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
