### ISSUE TITLE
Admin interface locale breaks  "Expiration date" field

### ISSUE THREAD

**Issue by rustavellyne** [magento/magento2#32497]
### Preconditions (*)
1. Magento version 2.4.2

### Steps to reproduce (*)
1. sigh in to admin panel
1. go to System -> All users
1. change locale of current user to Any except 'en_Us'
1. try to create a new user, and set expiration date 
1. save user
1. get an error "Expiration Date is not valid"

### Expected result (*)
1. expect to create user

### Actual result (*)
1. !https://user-images.githubusercontent.com/33631491/111330717-df91bd80-8678-11eb-91c4-824bccdf455c.jpeg!

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*

@magento give me 2.4-develop instance

**Comment by rustavellyne** [comment]
@magento give me 2.4-develop instance

**Comment by rustavellyne** [comment]
reproduced on Magento instance
![Uploading Screenshot 2021-03-16 at 17.23.10.png…]()

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41400` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @rustavellyne. Thank you for your report. 
The issue has been fixed in magento/magento2#33033 by @engcom-Kilo in 2.4-develop branch
Related commit(s):
 - [be3cb9c2382d4473dcc01d380cfaea25f92c4a1c](https://github.com/magento/magento2/commit/be3cb9c2382d4473dcc01d380cfaea25f92c4a1c)

The fix will be available with the upcoming 2.4.3 release.
