### ISSUE TITLE
Disable Email Communications Not Working

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#3250]
I wanted to disable all outgoing mails for the Magento2 application, so I used the setting at:

Configuration > ADVANCED > System > Disable Email Communications and set it to "Yes".

Still the emails are being sent out, is there something I am missing here ?

I searched the code base for system setting path `system/smtp/disable` in order to figure out where it is being used, only could find a constant `Magento\Email\Model\Template::XML_PATH_SYSTEM_SMTP_DISABLE` which is been used in a method `Magento\Email\Model\Template::isValidForSend()`. This method is only utilized in some unit tests.

Is there any other way of disabling mails from the admin settings ?

P.s. Cache is `disabled` for the application and `MAGE_MODE` is set to `developer`

**Comment by veloraven** [comment]
@atishgoswami is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
if it is a question and is not an issue, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
