### ISSUE TITLE
Integrity and crossorigin with external stylesheets not working

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#32509]
### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.1

### Steps to reproduce (*)
1. Edit `app/design/frontend/<Vendor>/<theme>/Magento_Theme/layout/default_head_blocks.xml`
2. Try to include a CDN CSS or JS like Bootstrap for example: `<link rel="stylesheet" src_type="url" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>`
3. Error: attribute integrity and crossorigin not supported

### Expected result (*)
Ability to import external CSS and JS using modern methods and requirements

### Actual result (*)

Errors saying attributes integrity and crossorigin is not supported.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41625` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by erfanimani** [comment]
There's a PR here also: https://github.com/magento/magento2/pull/32455
