### ISSUE TITLE
A PHPDoc result type of the \Magento\Framework\View\TemplateEngineInterface::render() method is wrong

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3252]
https://mage2.pro/t/394

**Comment by palamar** [comment]
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by Vinai** [comment]
@palamar You might not know, but @mage2pro was banned. He is unable to respond to you.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
