### ISSUE TITLE
Table structure issue catalog_product_entity (sku field is allowed nulls)

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#32525]
# Preconditions

1. Any Magento version (tested on all significant releases, 2.1, 2.2, 2.3)
2. Reproduced on 2.4-develop
3. #magento2/27411 was closed while it's a verified and open bug. You can't do that. Opening this as a new issue. 

# Steps to reproduce

1. Add a product either through migration, a custom importer or directly in the database.
2. Leave out the field SKU (in other words, leave it NULL).
3. Go to the product edit page in the backoffice.

# Expected result

1. Should not be possible to add the product OR should not throw an error in the backoffice.

# Actual result

1. Product is added without issues.
2. When attempting to edit the product in the backoffice the following error is thrown:
`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() must be of the type string, null given, called in /vendor/magento/module-catalog/Model/ProductRepository.php on line 790 and defined in /vendor/magento/module-catalog/Model/ProductRepository.php:800 Stack trace: #0 /vendor/magento/module-catalog/Model/ProductRepository.php(790): Magento\Catalog\Model\ProductRepository->prepareSku(NULL) #1 /vendor/magento/module-catalog/Model/ProductRepository.php(349): Magento\Catalog\Model\ProductRepository->saveProductInLocalCache(Object(Magento\Catalog\Model\Product\Interceptor), '3e07f167255019f...') #2 /vendor/magento/module-catalog/Model/ProductRepository.php(314): Magento\Catalog\Model\ProductRepository->cacheProduct('3e07f167255019f...', Object(Magento\Catalog\Model\Product in /vendor/magento/module-catalog/Model/ProductRepository.php on line 800`

**Comment by ihor-sviziev** [comment]
@dverkade, thx for raising this issue again. I'll re-open the original issue, as it was already prioritized.
I'll close this one as duplicate.

BTW I created a PR that suppose to fix this issue https://github.com/magento/magento2/pull/32532

**Comment by gabrieldagama** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#32532 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [a369d5a510f7bbbdf790bfdeffcc5fc9126949e1](https://github.com/magento/magento2/commit/a369d5a510f7bbbdf790bfdeffcc5fc9126949e1)

The fix will be available with the upcoming 2.4.3 release.
