### ISSUE TITLE
Magento 2.4.2 appears to sort products incorrectly

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#32522]
### Preconditions (*)

1. Magento 2.4.2
2. Luma theme used for example, but I also see issues with Porto

### Steps to reproduce (*)

1. Sort category products by position
2.

### Expected result (*)

1. Products within category to be sorted in order defined by position set
2.

### Actual result (*)

1. Screenshot shows sample data, category appears to be sorted descending, while settings are for ascending
2. 
![result](https://user-images.githubusercontent.com/43850303/111461355-0271af80-8715-11eb-9cc0-f20e486e4a08.jpg)
![settings](https://user-images.githubusercontent.com/43850303/111461357-030a4600-8715-11eb-8402-056972e058b2.jpg)

I also have a live site with Porto theme, the sort order is completely messed up on 2.4.2, but I am pretty sure it was fine on my old Magento 2.3 site.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41401` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cfarnleitner** [comment]
just a side note in case one may be able to temporarily fix this by re-positioning products: 
the positioning does not seem to be "random" but takes the position info from ONE _particular_ catalog_category_product (haven't tested in detail but I would assume the lowest entity_id wins) entry; in other words, once you have a product assigned to multiple categories this issue seems to occur.

**Comment by devchris79** [comment]
The order isn't random, but its not the case that a product appears in one category then the sort order is correct.

I have tested on our test installation and it appears the order is affected by the last time the product was edited. With the newest edit being placed last in the sort order. weird....

**Comment by omerts** [comment]
@magento-engcom-team This is pretty critical is the order of products is critical to marketing needs

**Comment by daancart2quote** [comment]
This is an important issue, this forces some users to keep using the SQL search.

**Comment by vandijkstef** [comment]
Sadly, @devchris79 solution didn't do anything for me

**Comment by devchris79** [comment]
Hi Stef,

Its strange because after I changed my code as above it worked for me.
I am wondering if another fix I had implemented also had an effect and the combination of the two corrected the issue.

Here is the fix in question, it also affects Elasticsearch so it may work for you #32304
