### ISSUE TITLE
Magento 2.3.5p1 issue with Fedex Shipping Getting Incorrect Rates 

### ISSUE THREAD

**Issue by smartsanjay** [magento/magento2#32536]
### Preconditions (*)

1.2.3.5-P1
2.Fedex Shipping Rates in magento are different from Fedex live estimate.Also Fedex support is saying to upgrade Fedex version 28 as currently using version 10 which is quite older.

### Steps to reproduce (*)

1.IN one page checkout Want to ship product from China to US and the Fedex rates are different from LIve estimate
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. Fedex LIve estimate should match with Magento2 Shipping Rates and module version should be updated.
3. 
![Screenshot Capture - 2021-03-18 - 01-35-59](https://user-images.githubusercontent.com/39264183/111531339-684c4e80-878a-11eb-8616-59342ce574a3.png)

### Actual result (*)

1. [Screenshots, logs or description]
2. 
![Screenshot Capture - 2021-03-18 - 01-37-44](https://user-images.githubusercontent.com/39264183/111531486-9c277400-878a-11eb-88c6-d067086484a2.png)

3.shipping.log
[2021-03-17 19:56:39] main.DEBUG: array (
  'request' => 
  array (
    'WebAuthenticationDetail' => 
    array (
      'UserCredential' => 
      array (
        'Key' => '****',
        'Password' => '****',
      ),
    ),
    'ClientDetail' => 
    array (
      'AccountNumber' => '788108974',
      'MeterNumber' => '****',
    ),
    'Version' => 
    array (
      'ServiceId' => 'crs',
      'Major' => '28',
      'Intermediate' => '0',
      'Minor' => '0',
    ),
    'RequestedShipment' => 
    array (
      'DropoffType' => 'REGULAR_PICKUP',
      'ShipTimestamp' => '2021-03-17T19:56:35+00:00',
      'PackagingType' => 'YOUR_PACKAGING',
      'TotalInsuredValue' => 
      array (
        'Amount' => 16.0,
        'Currency' => 'USD',
      ),
      'Shipper' => 
      array (
        'Address' => 
        array (
          'PostalCode' => '314000',
          'CountryCode' => 'CN',
        ),
      ),
      'Recipient' => 
      array (
        'Address' => 
        array (
          'PostalCode' => '79065',
          'CountryCode' => 'US',
          'Residential' => true,
          'City' => 'Pampa',
        ),
      ),
      'ShippingChargesPayment' => 
      array (
        'PaymentType' => 'SENDER',
        'Payor' => 
        array (
          'AccountNumber' => '788108974',
          'CountryCode' => 'CN',
        ),
      ),
      'CustomsClearanceDetail' => 
      array (
        'CustomsValue' => 
        array (
          'Amount' => 16.0,
          'Currency' => 'USD',
        ),
      ),
      'RateRequestTypes' => 'LIST',
      'PackageCount' => '1',
      'PackageDetail' => 'INDIVIDUAL_PACKAGES',
      'RequestedPackageLineItems' => 
      array (
        0 => 
        array (
          'Weight' => 
          array (
            'Value' => 1.8911,
            'Units' => 'LB',
          ),
          'GroupPackageCount' => 1,
          'InsuredValue' => 
          array (
            'Amount' => 16.0,
            'Currency' => 'USD',
          ),
        ),
      ),
    ),
  ),
  'result' => 
  stdClass::__set_state(array(
     'HighestSeverity' => 'NOTE',
     'Notifications' => 
    stdClass::__set_state(array(
       'Severity' => 'NOTE',
       'Source' => 'crs',
       'Code' => '820',
       'Message' => 'The destination state/province code has been changed.  ',
       'LocalizedMessage' => 'The destination state/province code has been changed.  ',
    )),
     'Version' => 
    stdClass::__set_state(array(
       'ServiceId' => 'crs',
       'Major' => 28,
       'Intermediate' => 0,
       'Minor' => 0,
    )),
     'RateReplyDetails' => 
    array (
      0 => 
      stdClass::__set_state(array(
         'ServiceType' => 'INTERNATIONAL_PRIORITY',
         'ServiceDescription' => 
        stdClass::__set_state(array(
           'ServiceType' => 'INTERNATIONAL_PRIORITY',
           'Code' => '01',
           'Names' => 
          array (
            0 => 
            stdClass::__set_state(array(
               'Type' => 'long',
               'Encoding' => 'utf-8',
               'Value' => 'International PriorityÂ®',
            )),
            1 => 
            stdClass::__set_state(array(
               'Type' => 'long',
               'Encoding' => 'ascii',
               'Value' => 'International Priority',
            )),
            2 => 
            stdClass::__set_state(array(
               'Type' => 'medium',
               'Encoding' => 'utf-8',
               'Value' => 'International PriorityÂ®',
            )),
            3 => 
            stdClass::__set_state(array(
               'Type' => 'medium',
               'Encoding' => 'ascii',
               'Value' => 'International Priority',
            )),
            4 => 
            stdClass::__set_state(array(
               'Type' => 'short',
               'Encoding' => 'utf-8',
               'Value' => 'IP',
            )),
            5 => 
            stdClass::__set_state(array(
               'Type' => 'short',
               'Encoding' => 'ascii',
               'Value' => 'IP',
            )),
            6 => 
            stdClass::__set_state(array(
               'Type' => 'abbrv',
               'Encoding' => 'ascii',
               'Value' => 'IP',
            )),
          ),
           'Description' => 'International Priority',
           'AstraDescription' => 'IP',
        )),
         'PackagingType' => 'YOUR_PACKAGING',
         'DestinationAirportId' => 'LBB',
         'IneligibleForMoneyBackGuarantee' => false,
         'OriginServiceArea' => 'PM',
         'DestinationServiceArea' => 'AM',
         'SignatureOption' => 'NO_SIGNATURE_REQUIRED',
         'ActualRateType' => 'PAYOR_ACCOUNT_SHIPMENT',
         'RatedShipmentDetails' => 
        array (
          0 => 
          stdClass::__set_state(array(
             'EffectiveNetDiscount' => 
            stdClass::__set_state(array(
               'Currency' => 'CNY',
               'Amount' => '0.0',
            )),
             'ShipmentRateDetail' => 
            stdClass::__set_state(array(
               'RateType' => 'PAYOR_ACCOUNT_SHIPMENT',
               'RateScale' => 'CN0474F2_01_YOUR_PACKAGING',
               'RateZone' => 'CN0474',
               'RatedWeightMethod' => 'ACTUAL',
               'CurrencyExchangeRate' => 
              stdClass::__set_state(array(
                 'FromCurrency' => 'CNY',
                 'IntoCurrency' => 'CNY',
                 'Rate' => '1.0',
              )),
               'DimDivisor' => 139,
               'DimDivisorType' => 'COUNTRY',
               'FuelSurchargePercent' => '16.5',
               'TotalBillingWeight' => 
              stdClass::__set_state(array(
                 'Units' => 'LB',
                 'Value' => '1.89',
              )),
               'TotalBaseCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '537.0',
              )),
               'TotalFreightDiscounts' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '214.8',
              )),
               'TotalNetFreight' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '322.2',
              )),
               'TotalSurcharges' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '97.43',
              )),
               'TotalNetFedExCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'TotalTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'TotalRebates' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalAncillaryFeesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesTaxesAndFees' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetChargeWithDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'FreightDiscounts' => 
              stdClass::__set_state(array(
                 'RateDiscountType' => 'VOLUME',
                 'Description' => 'Volume',
                 'Amount' => 
                stdClass::__set_state(array(
                   'Currency' => 'CNY',
                   'Amount' => '214.8',
                )),
                 'Percent' => '40.0',
              )),
               'Surcharges' => 
              array (
                0 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'PEAK',
                   'Description' => 'Peak Surcharge',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '14.0',
                  )),
                )),
                1 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'RESIDENTIAL_DELIVERY',
                   'Description' => 'Residential delivery',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '24.0',
                  )),
                )),
                2 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'FUEL',
                   'Description' => 'Fuel',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '59.43',
                  )),
                )),
              ),
            )),
          )),
          1 => 
          stdClass::__set_state(array(
             'ShipmentRateDetail' => 
            stdClass::__set_state(array(
               'RateType' => 'PAYOR_LIST_SHIPMENT',
               'RateScale' => 'CN0474F2_01_YOUR_PACKAGING',
               'RateZone' => 'CN0474',
               'RatedWeightMethod' => 'ACTUAL',
               'CurrencyExchangeRate' => 
              stdClass::__set_state(array(
                 'FromCurrency' => 'CNY',
                 'IntoCurrency' => 'CNY',
                 'Rate' => '1.0',
              )),
               'DimDivisor' => 139,
               'DimDivisorType' => 'COUNTRY',
               'FuelSurchargePercent' => '16.5',
               'TotalBillingWeight' => 
              stdClass::__set_state(array(
                 'Units' => 'LB',
                 'Value' => '1.89',
              )),
               'TotalBaseCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '537.0',
              )),
               'TotalFreightDiscounts' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '214.8',
              )),
               'TotalNetFreight' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '322.2',
              )),
               'TotalSurcharges' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '97.43',
              )),
               'TotalNetFedExCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'TotalTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'TotalRebates' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalAncillaryFeesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesTaxesAndFees' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetChargeWithDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '419.63',
              )),
               'FreightDiscounts' => 
              stdClass::__set_state(array(
                 'RateDiscountType' => 'VOLUME',
                 'Description' => 'Volume',
                 'Amount' => 
                stdClass::__set_state(array(
                   'Currency' => 'CNY',
                   'Amount' => '214.8',
                )),
                 'Percent' => '40.0',
              )),
               'Surcharges' => 
              array (
                0 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'PEAK',
                   'Description' => 'Peak Surcharge',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '14.0',
                  )),
                )),
                1 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'RESIDENTIAL_DELIVERY',
                   'Description' => 'Residential delivery',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '24.0',
                  )),
                )),
                2 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'FUEL',
                   'Description' => 'Fuel',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '59.43',
                  )),
                )),
              ),
            )),
          )),
        ),
      )),
      1 => 
      stdClass::__set_state(array(
         'ServiceType' => 'INTERNATIONAL_ECONOMY',
         'ServiceDescription' => 
        stdClass::__set_state(array(
           'ServiceType' => 'INTERNATIONAL_ECONOMY',
           'Code' => '04',
           'Names' => 
          array (
            0 => 
            stdClass::__set_state(array(
               'Type' => 'long',
               'Encoding' => 'utf-8',
               'Value' => 'FedEx International EconomyÂ®',
            )),
            1 => 
            stdClass::__set_state(array(
               'Type' => 'long',
               'Encoding' => 'ascii',
               'Value' => 'FedEx International Economy',
            )),
            2 => 
            stdClass::__set_state(array(
               'Type' => 'medium',
               'Encoding' => 'utf-8',
               'Value' => 'FedEx International EconomyÂ®',
            )),
            3 => 
            stdClass::__set_state(array(
               'Type' => 'medium',
               'Encoding' => 'ascii',
               'Value' => 'FedEx International Economy',
            )),
            4 => 
            stdClass::__set_state(array(
               'Type' => 'short',
               'Encoding' => 'utf-8',
               'Value' => 'IE',
            )),
            5 => 
            stdClass::__set_state(array(
               'Type' => 'short',
               'Encoding' => 'ascii',
               'Value' => 'IE',
            )),
            6 => 
            stdClass::__set_state(array(
               'Type' => 'abbrv',
               'Encoding' => 'ascii',
               'Value' => 'IE',
            )),
          ),
           'Description' => 'International Economy',
           'AstraDescription' => 'IE',
        )),
         'PackagingType' => 'YOUR_PACKAGING',
         'DestinationAirportId' => 'LBB',
         'IneligibleForMoneyBackGuarantee' => false,
         'OriginServiceArea' => 'PM',
         'DestinationServiceArea' => 'AM',
         'SignatureOption' => 'NO_SIGNATURE_REQUIRED',
         'ActualRateType' => 'PAYOR_ACCOUNT_SHIPMENT',
         'RatedShipmentDetails' => 
        array (
          0 => 
          stdClass::__set_state(array(
             'EffectiveNetDiscount' => 
            stdClass::__set_state(array(
               'Currency' => 'CNY',
               'Amount' => '0.0',
            )),
             'ShipmentRateDetail' => 
            stdClass::__set_state(array(
               'RateType' => 'PAYOR_ACCOUNT_SHIPMENT',
               'RateScale' => 'CN0474F2_04_YOUR_PACKAGING',
               'RateZone' => 'CN0474',
               'RatedWeightMethod' => 'ACTUAL',
               'CurrencyExchangeRate' => 
              stdClass::__set_state(array(
                 'FromCurrency' => 'CNY',
                 'IntoCurrency' => 'CNY',
                 'Rate' => '1.0',
              )),
               'DimDivisor' => 139,
               'DimDivisorType' => 'COUNTRY',
               'FuelSurchargePercent' => '16.5',
               'TotalBillingWeight' => 
              stdClass::__set_state(array(
                 'Units' => 'LB',
                 'Value' => '1.89',
              )),
               'TotalBaseCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '432.0',
              )),
               'TotalFreightDiscounts' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '172.8',
              )),
               'TotalNetFreight' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '259.2',
              )),
               'TotalSurcharges' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '87.04',
              )),
               'TotalNetFedExCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'TotalTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'TotalRebates' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalAncillaryFeesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesTaxesAndFees' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetChargeWithDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'FreightDiscounts' => 
              stdClass::__set_state(array(
                 'RateDiscountType' => 'VOLUME',
                 'Description' => 'Volume',
                 'Amount' => 
                stdClass::__set_state(array(
                   'Currency' => 'CNY',
                   'Amount' => '172.8',
                )),
                 'Percent' => '40.0',
              )),
               'Surcharges' => 
              array (
                0 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'PEAK',
                   'Description' => 'Peak Surcharge',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '14.0',
                  )),
                )),
                1 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'RESIDENTIAL_DELIVERY',
                   'Description' => 'Residential delivery',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '24.0',
                  )),
                )),
                2 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'FUEL',
                   'Description' => 'Fuel',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '49.04',
                  )),
                )),
              ),
            )),
          )),
          1 => 
          stdClass::__set_state(array(
             'ShipmentRateDetail' => 
            stdClass::__set_state(array(
               'RateType' => 'PAYOR_LIST_SHIPMENT',
               'RateScale' => 'CN0474F2_04_YOUR_PACKAGING',
               'RateZone' => 'CN0474',
               'RatedWeightMethod' => 'ACTUAL',
               'CurrencyExchangeRate' => 
              stdClass::__set_state(array(
                 'FromCurrency' => 'CNY',
                 'IntoCurrency' => 'CNY',
                 'Rate' => '1.0',
              )),
               'DimDivisor' => 139,
               'DimDivisorType' => 'COUNTRY',
               'FuelSurchargePercent' => '16.5',
               'TotalBillingWeight' => 
              stdClass::__set_state(array(
                 'Units' => 'LB',
                 'Value' => '1.89',
              )),
               'TotalBaseCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '432.0',
              )),
               'TotalFreightDiscounts' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '172.8',
              )),
               'TotalNetFreight' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '259.2',
              )),
               'TotalSurcharges' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '87.04',
              )),
               'TotalNetFedExCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'TotalTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetCharge' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'TotalRebates' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalAncillaryFeesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalDutiesTaxesAndFees' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '0.0',
              )),
               'TotalNetChargeWithDutiesAndTaxes' => 
              stdClass::__set_state(array(
                 'Currency' => 'CNY',
                 'Amount' => '346.24',
              )),
               'FreightDiscounts' => 
              stdClass::__set_state(array(
                 'RateDiscountType' => 'VOLUME',
                 'Description' => 'Volume',
                 'Amount' => 
                stdClass::__set_state(array(
                   'Currency' => 'CNY',
                   'Amount' => '172.8',
                )),
                 'Percent' => '40.0',
              )),
               'Surcharges' => 
              array (
                0 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'PEAK',
                   'Description' => 'Peak Surcharge',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '14.0',
                  )),
                )),
                1 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'RESIDENTIAL_DELIVERY',
                   'Description' => 'Residential delivery',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '24.0',
                  )),
                )),
                2 => 
                stdClass::__set_state(array(
                   'SurchargeType' => 'FUEL',
                   'Description' => 'Fuel',
                   'Amount' => 
                  stdClass::__set_state(array(
                     'Currency' => 'CNY',
                     'Amount' => '49.04',
                  )),
                )),
              ),
            )),
          )),
        ),
      )),
    ),
  )),
) [] []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by smartsanjay** [comment]
Hi Team,
Could anyone please help us on this.

Thanks
Sanjaya

**Comment by smartsanjay** [comment]
@magento I am working on this

**Comment by smartsanjay** [comment]
@magento add to contributors team

**Comment by engcom-November** [comment]
Hi @smartsanjay,

Verified the issue on Magento Version 2.4.2 and FedEx configuration is working fine for US shipping with Home Delivery option.
Unable to select FedEx Shipping method if Origin Country is china and shipping address is US.
**Steps performed:**
1. Magento Admin - Configured FedEx: Stores - Configuration - Sales - Delivery Methods - FedEx (Set Allowed methods to any - International methods) **Issue: For any international method selected - Unable to select FedEx shipping method in Front end checkout page**
2. Created new Website, Store and Store View for China Store
Ref: https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html#step-2-create-websites 
(Stores – Settings – Configuration – General - Change the scope – Select Newly created Store
Stores – Settings – Configuration - Web - Update the 'Base URLs', 'Base Url Secure' with the new URL
Default Country selected: China
Store information – Provided China Address
Add the Base URL configuration in etc/apache2/stes-available/lyour.conf file and /etc/hosts file restart the server, clean cache)
4. Navigate to Stores – Inventory – Sources – Add source and stock with newly created store code using China Address 
5. Navigate to Stores - Configuration - Sales - Shipping Settings - Change the scope (Newly created Store) - Save China address 
6. Create a simple product in newly created store with Weight and quantity as per FedEx configuration
7. Login to Magento Front End as customer with US shipping address and the product to Cart:

**Note:** If Origin Country US address is given under Shipping Settings (and FedEx Home Delivery method is configured ) - There is no change in FedEx shipping charges. Same charges are applied in both china store and and US store (No difference in shipping charged)
Issue: If Origin Country - China is selected under Shipping Settings - Unable to select FedEx Shipping method in Front end checkout page

Can you please provide more details or exact steps to do International FedEx Configuration to ship from China to US

![image](https://user-images.githubusercontent.com/60198231/121511266-153f0c00-ca06-11eb-8f4b-1264b489bdd0.png)

![image](https://user-images.githubusercontent.com/60198231/121511358-2a1b9f80-ca06-11eb-849f-929b116101d1.png)

![image](https://user-images.githubusercontent.com/60198231/121511507-56cfb700-ca06-11eb-8539-d19fba22a235.png)

**Comment by engcom-November** [comment]
Hi @smartsanjay,

We are closing this ticket , as there has been no update on the same.
Thank you.
