### ISSUE TITLE
Button "add product" for new order on admin is missing

### ISSUE THREAD

**Issue by kennysinkeler** [magento/magento2#32530]
Hi all,
I am using magento 2.4.2. If i want to create a new order(sales -> orders -> create new order) than i am missing the "add product" button.

 Preconditions

1. Magento 2.4.2
2. Nginx
3. Ubuntu 20.04

Steps to reproduce (*)
1. Login into the backend
2. hover on Sales
3. Go to orders
4. Click on new order.
5. Choose a client.

### Expected result (*)
1. One black button to "add products" 

Actual result
The black button with "add product" is missing
![image](https://user-images.githubusercontent.com/10799266/111475130-11645c00-872d-11eb-92dd-2c6adc63c1dd.png)

This work around, is not working.
https://support.magento.com/hc/en-us/articles/360047481431-Magento-2-4-0-known-issue-Create-New-Order-buttons-missing

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @kennysinkeler. Here it works fine in latest Magento instance so kindly share the additional details like browser,

**Comment by kennysinkeler** [comment]
hi @krishprakash,
I am using chrome 89.0.4389.90 but i have this problem with multiple browsers.

This is the dev config 
![image](https://user-images.githubusercontent.com/10799266/111609280-6ca05800-87da-11eb-96a9-ac967e36136d.png)

**Comment by kennysinkeler** [comment]
My console log (of chrome) on create order page is saying, is this maybe related?

```[DOM] Found 2 elements with non-unique id #order-comment: (More info: https://goo.gl/9p2vKq) <fieldset class=​"admin__fieldset order-history" id=​"order-comment">​ <legend class=​"admin__legend">​…​</legend>​ <br>​ <div class=​"admin__field field-comment">​…​</div>​ <script>​…​</script>​ </fieldset>​ <textarea id=​"order-comment" name=​"order[comment]​[customer_note]​" class=​"admin__control-textarea">​</textarea>​
```

**Comment by kennysinkeler** [comment]
I see this in the source (from the browser)
```<div class="admin__page-section-title">
    <strong class="title">Items Ordered</strong>
    <div class="actions">
            </div>
</div>
```
This is as the button show(it does sometime)
```
<div class="admin__page-section-title">
    <strong class="title">Items Ordered</strong>
    <div class="actions"><button class="action-secondary action-add" type="button"><span>Add Products</span></button>
            </div>
</div>
```

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4.2 version but is not reproducible.
@kennysinkeler Porto theme is a 3rd party extension and code of this extension is not part on https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository
All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento [Market place page](https://marketplace.magento.com/extensions.html)
Thank you.
