### ISSUE TITLE
Checkout with PayPal - Buttons not being rendered anymore

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#32548]
Since March 16th, "Checkout with PayPal" Buttons are not being rendered anymore.
The URL for dynamic images from paypal doesn't seem to work anymore. 

### Preconditions (*)
1. Install a Magento 2.4.2 Shop with sample sample products
2. Have a PayPal Account to set the shop up with

### Steps to reproduce (*)
1. in Sales > Payment Method go to PayPal and set "Enable this Solution" to "Yes"
2. Configure PayPal using API Signature (set API Username, Password and Signature)
3. Leave "Enable in-Context Checkout Experience" set to "No"
4. Under "Basic Settings", set "Display on Product Details page" to "Yes"
5. Under "Advanced Settings", be sure to set "Shortcut Buttons Flavor" to "Dynamic"

### Expected result (*)
On Product detail page or on cart/minicart, it should show a button with "Checkout with Paypal"

### Actual result (*)
1. "Checkout with PayPal"-Buttons shows a broken image link.
The URL of the image is https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&amp;buttontype=ecshortcut&amp;locale=en_GB
which doesn't seem to work anymore.

The generated code for the image button is:
`<input type="image" data-action="checkout-form-submit" data-checkout-url="http://bbq.testwebshop.eu/paypal/express/start/button/1/" src="https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&amp;buttontype=ecshortcut&amp;locale=en_GB" alt="Checkout with PayPal" title="Checkout with PayPal">`

Only workaround is to set Advanced Settings > Shortcut Buttons Flavor to "static".

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stephansteiner** [comment]
@magento give me 2.4-develop instance

**Comment by stephansteiner** [comment]
I could not reproduce the issue, the Magento instance provided renders a different button code.
`<input type="image" data-action="checkout-form-submit" data-checkout-url="https://05a5d3499b4d527537d8f55e02bd75aa-2-4-develop.instances.magento-community.engineering/paypal/express/start/button/1/" src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-medium.png" alt="Checkout with PayPal" title="Checkout with PayPal">`

The url of the image is not https://fpdbs.paypal.com/dynamicimageweb but https://www.paypalobjects.com

**Comment by stephansteiner** [comment]
Ok, issue could have been reproduced, but is dependent of the locale setting of the webshop.
See here for broken Image of checkout with paypal button:
https://05a5d3499b4d527537d8f55e02bd75aa-2-4-develop.instances.magento-community.engineering/argus-all-weather-tank.html

The issue is in the function _getDynamicImageUrl in class \Magento\Paypal\Model\Config:
for locales different from en_US the image url is build using
```
return sprintf(
            'https://fpdbs%s.paypal.com/dynamicimageweb?%s',
            $this->getValue('sandboxFlag') ? '.sandbox' : '',
            http_build_query($params)
        );
```
Apparently https://fpdbs.paypal.com/dynamicimageweb and https://fpdbs.sandbox.paypal.com/dynamicimageweb are both defunct, resulting in the broken image url.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by stephansteiner** [comment]
@ajijshekh123 Hi, I noticed that you're verifying this - please remember to change the shops locale, as the default "en_US" won't display broken image buttons. You may also enter fake data for PayPal credentials as these come only into use when actually clicking the button.

**Comment by ajijshekh123** [comment]
Hi @stephansteiner,
I have verified this issue as per your steps and configuration. All configuration I have set up properly but I didn't know which change required on shops local as the default "en_US". Please update the screenshot here.
The rest of the configuration I have set up properly and the "Checkout with PayPal" button is showing properly as Expected.

Product Details Page:
![image](https://user-images.githubusercontent.com/24711761/111769322-18c36b00-88cf-11eb-8b06-6c9fea239d14.png)

Mini Cart:
![image](https://user-images.githubusercontent.com/24711761/111769392-31cc1c00-88cf-11eb-9e9d-593134676d39.png)

Thanks.

**Comment by stephansteiner** [comment]
The
SandBox Version of Icons is working, if you disable Sandbox the icon logo is broken again.
Sandbox Payment Icon URL:
https://fpdbs.sandbox.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecshortcut&locale=de_DE
Non-Sandbox Version (Broken):
https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecshortcut&locale=de_DE

**Comment by ajijshekh123** [comment]
Hello @stephansteiner,
As per defined your configuration, I have reviewed the "Checkout with PayPal" button on the product details page. It is broken and not showing properly.

![image](https://user-images.githubusercontent.com/24711761/111780017-d7d25300-88dc-11eb-93f6-a44ebf34de74.png)

![image](https://user-images.githubusercontent.com/24711761/111780034-ddc83400-88dc-11eb-8823-26be5b926d6c.png)

![image](https://user-images.githubusercontent.com/24711761/111780147-fe908980-88dc-11eb-9949-8d8ca4a3813b.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41454` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
