### ISSUE TITLE
Collecting totals can remove reward points from quote grand total

### ISSUE THREAD

**Issue by martinshawruroc** [magento/magento2#32541]
### Preconditions (*)

1. Magento EE 2.4.1
2. Installed a simple module I've written to demonstrate the issue (attached)

### Steps to reproduce (*)

1. Create a customer account on your store frontend. Make sure your customer has a shipping address configured. 
2. Navigate to your admin panel
3. Navigate to Stores > Configuration > Customer > Reward Points.
4. Enable Reward Points Functionality -> Yes
5. Enable Reward Points Functionality on Storefront -> Yes
6. Save
7. Navigate to Stores > Reward Exchange Rates
8. Create a points to currency conversion (I set 1 points = $0.50)
9. Create a currency to points conversion (I set $1.00 = 2 points)
10. Award your customer with some points via the admin (I added 2 points)
11. Switch back to the frontend
12. Add an item to cart
13. Navigate to the checkout
14. Click the button to "Use Reward Points"
15. Look at {your base URL}/martinshaw/rewardissue/demo 

### Expected result (*)
The grand total should always show the reduced amount (because of the reward points) regardless of whether or not the totals have been collected. 

### Actual result (*)
When I navigate to that URL, I see this:

```
Grand Total Before Collecting: 466.8300
Grand Total After Collecting: 467.83
```

As the two points that are being redeemed are worth $1, you can see that the first value is correct. However after running `\Magento\Quote\Model\Quote\TotalsCollector::collectAddressTotals` (see `\Martinshaw\RewardIssueDemo\Controller\RewardIssue\Demo::execute`) you'll see that the grand total has lost the reward points associated to it and is $1 higher.

[Martinshaw_RewardIssueDemo.zip](https://github.com/magento/magento2/files/6162474/Martinshaw_RewardIssueDemo.zip)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @martinshawruroc ,

The total Collection process gets called after any cart update, it collects total for quote object . Can you please help me understand the use case that you are trying to achieve ( by making an intermediate call to TotalCollector) so that I can guide you more with this.

Thanks

**Comment by martinshawruroc** [comment]
Hi @engcom-Echo ,

It's a 3rd party checkout module which triggers the second call to TotalCollector. The module is https://www.onestepcheckout.com/

Regardless of that though, it's my expectation that we should get the same output from totals colleciton process, regardless of whether or not it has been called previously. I don't think it should have state that impacts the output.

**Comment by engcom-Hotel** [comment]
Hi @martinshawruroc,

As per your ticket description, we are able to reproduce the issue. So we are confirming the issue.

Thanks

**Comment by engcom-Bravo** [comment]
As direct call is being made to `$this->totalsCollector->collectAddressTotals()` from custom module. Instead of that `quote->collectTotals()` needs to be used to get total. As there are plugin which reset info beforeCollect on quote like rewards etc.

In this case when direct call is being made to` collectAddressTotals()` plugins are not called to reset the rewards points.

Below is the plugin which reset the reward info on quote beforeCollect `app/code/Magento/Reward/Model/Plugin/TotalsCollector.php `
