### ISSUE TITLE
Bug Report | Disclosure of authentication cookie

### ISSUE THREAD

**Issue by shubhamdhungana** [magento/magento2#32545]
There was disclosure of cookie in one of your client ecommerce site named sastodeal. I don't know if this is the core issue of magento.  Here's the issue : 
## Vulnerability Bug Impact:
Because of this bug, hacker can see the  session id of the user. Session id is the very sensitive piece of data.
Hacker (Man in the middle) can get access to any sastodeal user account. The good hacker can easily get access to user’s sastodeal account.
## Summary:
Disclosure of Cookie with session over insecure http

## Vulnerability Name: 
Disclosure of Authentication Cookie

**Comment by ihor-sviziev** [comment]
Hi @shubhamdhungana,
I'm closing this issue. For the details please DM me in EngCom Slack
