### ISSUE TITLE
Mobile Android keyboard force open and closed

### ISSUE THREAD

**Issue by ghost** [magento/magento2#32552]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @radcleong !
Please provide more details in description to made possible reproduce your issue.

**Comment by krishprakash** [comment]
Hi @radcleong. Feel free to reopen once you update all the details as per issue reporting guidelines
Thanks!
