### ISSUE TITLE
[Graphql] Category_uid is not available as a product aggregation type

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#32557]
### Preconditions (*)
v2.4.2

### Steps to reproduce (*)
```
query GetProductsInCategory($categoryUid: String!) {
  products(filter: {category_uid: {eq: $categoryUid}}) {
    aggregations {
        __typename
        attribute_code
    }
    __typename
  }
}
```

### Expected result (*)
I expect to get `category_uid` back as an aggregation.

### Actual result (*)
```

{
    "data": {
        "products": {
            "aggregations": [
                {
                    "__typename": "Aggregation",
                    "attribute_code": "price"
                },
                {
                    "__typename": "Aggregation",
                    "attribute_code": "category_id"
                },
                {
                    "__typename": "Aggregation",
                    "attribute_code": "packaging"
                },
                {
                    "__typename": "Aggregation",
                    "attribute_code": "new_brand"
                },
                {
                    "__typename": "Aggregation",
                    "attribute_code": "new_model"
                }
            ],
            "__typename": "Products"
        }
    }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Other information

Note that:

```
query GetFilterTypesForCategory {
  __type (name: "ProductAttributeFilterInput") {
      inputFields {
        name
        type {
            name
        }   
      }
  }
}
```

Returns the `category_uid`

```
{
    "data": {
        "__type": {
            "inputFields": [
                {
                    "name": "accessories_size",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "bed_bath_type",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "category_id",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "category_uid",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "color",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "description",
                    "type": {
                        "name": "FilterMatchTypeInput"
                    }
                },
                {
                    "name": "format",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "gender",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "length",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "material",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "name",
                    "type": {
                        "name": "FilterMatchTypeInput"
                    }
                },
                {
                    "name": "new_brand",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "new_model",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "price",
                    "type": {
                        "name": "FilterRangeTypeInput"
                    }
                },
                {
                    "name": "short_description",
                    "type": {
                        "name": "FilterMatchTypeInput"
                    }
                },
                {
                    "name": "size",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "sku",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "style",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                },
                {
                    "name": "url_key",
                    "type": {
                        "name": "FilterEqualTypeInput"
                    }
                }
            ]
        }
    }
}
```

**Comment by engcom-Golf** [comment]
@damienwebdev Please share correct Request Payload with example. on using this, getting error: 
![image](https://user-images.githubusercontent.com/51681547/121308268-7986a080-c91e-11eb-827f-664be0cf46d1.png)

so I modified my request payload & configure the attribute_code against Product from Admin Panel.
![image](https://user-images.githubusercontent.com/51681547/121309062-5ad4d980-c91f-11eb-8adc-1edff148e092.png)

Please check whether you configure attribute codes or not.

**Comment by damienwebdev** [comment]
@engcom-Golf the sample request provided expects you to use GraphQl variables, please do so -- my current request payload is correct.

Regardless, the issue isn't an admin attribute, it is the category_uid attribute introduced by the GraphQl team in v2.4.2.

This isn't an attribute configurable in the admin panel.

@cpartica can explain if there is any confusion.

**Comment by engcom-Golf** [comment]
@damienwebdev Thanks for quick reply. Please find the snapshot for reference

**Comment by engcom-Alfa** [comment]
Hi @damienwebdev ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by joggienl** [comment]
I am trying out this fix and the aggregation now shows `category_uid` in stead of `category_id`. BUT the values are still the category id values, and not the uid values, is that correct and intended? This way they are not usable.

Example query:

```graphql
query searchProducts {
    products(search: "") {
        aggregations {
          attribute_code 
          options {
            value
          }
        }
    }
}
```

Result I see (not a complete result:

```json
{
  "data": {
    "products": {
      "aggregations": [
        {
          "attribute_code": "category_uid",
          "options": [
            {
              "value": "48"
            },
            {
              "value": "58"
            },
            {
              "value": "47"
            }
          ]
        }
      ]
    }
  }
}
```
In my case I would expect values like `NDg=` for 48,  `NTg=` for 58 and `NDc=` for 47.

@damienwebdev have you had the change to check this "fix"? If you do get the proper values it might be something wrong on my end.

**Comment by damienwebdev** [comment]
@joggienl I haven't re-reviewed.

**Comment by joggienl** [comment]
@damienwebdev thanks for your quick reply!

I've tried the call I used on https://venia.magento.com/graphql and there I do get the actual uid's.

So that is weird to say the least.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1089150/202204004-665c810f-fe25-4d0e-8813-f7ce41fea07b.png">
