### ISSUE TITLE
storeConfig GraphQl query has no cache identity

### ISSUE THREAD

**Issue by lewisvoncken** [magento/magento2#32554]
The storeConfig Query contains `@cache(cacheable: false)`

Which results in a very slow configuration query and it could be cached

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @webtekindo,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by yaroslav-qlicks** [comment]
@engcom-Hotel This is so stupid politics to close issue when no long reply. Devs are give you info how to improve and instead of making software better to just close issue. It means work of this guy gone. Never understand it

**Comment by cpartica** [comment]
I am going to re-open this - so sorry about our bot - I am making the case for it to have a way longer grace period

**Comment by hansvereyken** [comment]
We are hitting the same problem, but in the docs:
https://devdocs.magento.com/guides/v2.4/graphql/caching.html#:~:text=Magento%20explicitly%20disallows%20caching%20the%20following%20queries.

Magento explicitly disallows caching the following queries.

> ...
> storeConfig
> ...

I can't find any reason for this. It's just written as something that's not allowed, but why?

**Comment by engcom-Bravo** [comment]
Hi @lewisvoncken,

Thank you for reporting and collaboration.

As per Magento devdocs [document](https://devdocs.magento.com/guides/v2.4/graphql/caching.html).Magento explicitly disallows the storeConfig caching.


However it is an existing behaviour of Magento.This is not an issue.

Hence we are considering as Feature Request.

Thanks.

**Comment by tuyennn** [comment]
BB2B-2598: Adds caching capability to storeConfig, currency, country, countries, and availableStores GraphQl queries
https://github.com/magento/quality-patches/blob/master/patches/os/B2B-2598__add_caching_capability_to_GraphQL_queries__2.4.6.patch
