### ISSUE TITLE
Meta Information not filtering HTML data

### ISSUE THREAD

**Issue by starnetwork** [magento/magento2#3255]
Hi,
I added new product using Unique Characters, and it's just show it at the top of the page, instead of filter it
for example
צ'ימידן 10 ליטר נייד

<p>צי'ימידן נייד מעולה לטיולים</p>

Please check and fix it

Regards,

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2295, https://github.com/magento/magento2/issues/1514, https://github.com/magento/magento2/issues/3090, https://github.com/magento/magento2/issues/3244
https://mage2.pro/t/161

**Comment by vzabaznov** [comment]
@starnetwork bug was fixed and delivered to develop branch, thank you for contributing, please feel free to add new issues or write, if fix doesn't help.
