### ISSUE TITLE
[Graphql] Filtering Products by CategoryUid type is incorrect.

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#32556]
### Preconditions (*)
Magento v2.4.2

### Steps to reproduce (*)
Make a GraphQl query like

```
query GetProductsInCategory($categoryUid: ID!) {
  products(filter: {category_uid: {eq: $categoryUid}}) {
    aggregations {
        __typename
        attribute_code
    }
    __typename
  }
}
```

### Expected result (*)
I expected to get back products filtered by my category id.

### Actual result (*)

```
{
    "errors": [
        {
            "message": "Variable \"$categoryUid\" of type \"ID!\" used in position expecting type \"String\".",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 29
                },
                {
                    "line": 2,
                    "column": 40
                }
            ]
        }
    ]
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

cc: @cpartica @sirugh

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41477` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by karyna-tsymbal-atwix** [comment]
Hi @damienwebdev  , I had the same behavior and I was able to successfully run the query when I replaced ID! with String:

```
query GetProductsInCategory($categoryUid: String!) {
  products(filter: {category_uid: {eq: $categoryUid}}) {
    aggregations {
        __typename
        attribute_code
    }
    items {
      sku
    }
    __typename
  }
}
```
