### ISSUE TITLE
wysiwyg text editor not works in front-end popup

### ISSUE THREAD

**Issue by jatin-kspli190** [magento/magento2#32567]
**Preconditions (*)**
      Magento 2.4

**Steps to reproduce ()**
    Make a popup on frontend.
    Add wysiwyg text editor in it.

**Expected result (*)**
               wysiwyg text editor is should be editable in the popup on the frontend.

**Actual result (*)**
    wysiwyg text editor is not editable in the popup on the frontend.
![Screenshot from 2021-03-22 17-07-46](https://user-images.githubusercontent.com/76148776/111986538-13b32580-8b34-11eb-8f24-18b7e6c0b237.png)

**Comment by mrtuvn** [comment]
seem your problem not related with magento. Default wysiwyg feature not available in frontend

**Comment by mrtuvn** [comment]
For issue non-releated to core i think better post to magento.stackexchange

**Comment by krishprakash** [comment]
Hi @jatin-kspli190. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) Or[ magento stack exchange](https://magento.stackexchange.com) for general discuss about this topic
