### ISSUE TITLE
Configurable products: Duplicated products is not generating meta fields.

### ISSUE THREAD

**Issue by davirs** [magento/magento2#32570]
### Description (*)

When I create a new configurable product magento create automatically the meta fields for this products, acording with my configuration at Configuration/Catalog/Product Fields Auto-Generation.
But, if I duplicate a product to change only sku and product options(configurations), this new product from duplicated one not generate the meta fields automatically.

![Screenshot_31](https://user-images.githubusercontent.com/4355062/112036855-dfce0500-8b1f-11eb-8247-40cbb396ba9c.png)

![Screenshot_32](https://user-images.githubusercontent.com/4355062/112036890-e78da980-8b1f-11eb-9401-281f25dec6f3.png)

![Screenshot_33](https://user-images.githubusercontent.com/4355062/112037083-215eb000-8b20-11eb-96e8-0c91f640ef5d.png)

### Expected behavior (*)

We expect the metafields is generated automatically as default.

### Benefits

This function already exists in magento, you must implement it at duplicated products to magento works apropriatelly

**Comment by palviggi-flagbit** [comment]
This one is "broken" on magento 2.4 because of https://github.com/magento/magento2/issues/26054, that specifically clears the meta fields on duplication

**Comment by krishprakash** [comment]
Hi @davirs. Thank you for your report.
This is done intentionally. You can refer issue #26054

**Comment by cptX** [comment]
Meta fields should all be copied when duplicating. This is the definition of duplication, copy all infos!!
It is stupid to not populate these fields, I really don't understand how the https://github.com/magento/magento2/issues/26054 passed through. I'll open a new issue and will try to persuade the devs. Please back me up on this.
