### ISSUE TITLE
[GQL Gift registry] Add specialized query to move items from cart

### ISSUE THREAD

**Issue by cpartica** [magento/magento2#32574]
*As a PWA developer I want to move all items from the cart so that the gift registry would contain all items from cart and also don't be responsible for validation as cart ensures it's own validation.

### AC
* add specialized schema
* cover with webapi tests existing architecture schema
### Approved Schema
* https://github.com/magento/architecture/pull/480

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by cpartica** [comment]
hi @khrystynastolbova , please sync with @eduard13 because he's also working on it

**Comment by eduard13** [comment]
Hi @cpartica, it’s fine here, I’ve delegated this one to her (she’s also from Atwix), as currently don’t have too much free time. 

Thank you.
