### ISSUE TITLE
Missing dependency in Magento/JwtFrameworkAdapter

### ISSUE THREAD

**Issue by fooman** [magento/magento2#32578]
### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
1. check https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/JwtFrameworkAdapter/Model/JweManager.php#L11
2. notice `use Jose\Component\Encryption\JWEBuilder; `
3. check https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/JwtFrameworkAdapter/composer.json

### Expected result (*)

1. web-token/jwt-framework to be declared as dependency in the module that uses it magento/module-jwt-framework-adapter

### Actual result (*)

1.  defined on the global level https://github.com/magento/magento2/blob/2.4-develop/composer.json#L87

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @fooman,
Could you create a PR for fixing this issue?

**Comment by magento-engcom-team** [comment]
@bgorski Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by bgorski** [comment]
ok, now I know that this wasn't marked as confirmed in the first place. I'll go ahead and create a PR for this tomorrow if still needed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41613` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
@sivaschenko @sidolov @gabrieldagama from my perspective missing dependency should be treated as P2 priority as it might cause not obvious issue from developer perspective

**Comment by sivaschenko** [comment]
@sidolov @gabrieldagama @ihor-sviziev priority is set to P2 as this issue not only affect the dev experience but also can lead to potential errors during codebase analysis, design and automation.

**Comment by gabrieldagama** [comment]
Hi @fooman. Thank you for your report. 
The issue has been fixed in magento/magento2#32612 by @bgorski in 2.4-develop branch
Related commit(s):
 - [7306e85cfabd31582c4c366ef90820aa85825963](https://github.com/magento/magento2/commit/7306e85cfabd31582c4c366ef90820aa85825963)

The fix will be available with the upcoming 2.4.3 release.
