### ISSUE TITLE
Add name to existing blocks not just alias

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#3258]
Hi,

is it possible to add to all existing core blocks name tags as well not just as (alias) ?
For example here, if i want to remove the swatches I would be able to do it easily if there would be a name tag on this block:

> https://github.com/magento/magento2/blob/develop/app/code/Magento/Swatches/view/frontend/layout/catalog_category_view.xml

Without the name tag it is impossible to move the blocks. 

Thanks

**Comment by maksek** [comment]
please use forums for questions, GitHub only for bugs and PR.
