### ISSUE TITLE
Undefined Index, Deleted Store - bin/magento inventory:reservation:list-inconsistencies

### ISSUE THREAD

**Issue by timpea** [magento/magento2#32586]
### Preconditions (*)
1. Magento 2.4.2
2. Data migration from M1.9, M1 site historically had 2 stores, one of these had been deleted.  Still open orders related to the old store.

### Steps to reproduce (*)
1.  Run data migration
2. Run bin/magento inventory:reservation:list-inconsistencies

### Expected result (*)
1. List of orders with stock inconsistancies

### Actual result (*)
1.  Notice: Undefined index:  in /data/web/splat/public/vendor/magento/module-inventory-reservation-cli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php on li  
  ne 95   

No isset check on line 95 of GetOrderItemsDataForOrdersInNotFinalState.php:
$orderItem['website_id'] = $storeWebsiteIds[$orderItem['store_id']];

Changed to:
$orderItem['website_id'] = isset($storeWebsiteIds[$orderItem['store_id']]) ? $storeWebsiteIds[$orderItem['store_id']] : '';

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @timpea ,

We are unable to re-produce the issue based, Please find the below screenshot where list-inconsistencies have successfully executed.
<img width="512" alt="Screenshot 2021-06-17 at 1 57 00 PM" src="https://user-images.githubusercontent.com/51681435/122360586-204ceb80-cf74-11eb-915d-9c5aed7b1d73.png">

As per your description , it looks like the problem occurred during Step 2, also can you specify what steps were taken during deleting the store that you mentioned.

Thanks

**Comment by engcom-November** [comment]
@timpea,
We are closing this issue as there has been no latest update on the same.
Thank you.
