### ISSUE TITLE
Category Update API resets available_sort_by to use config value

### ISSUE THREAD

**Issue by lewisvoncken** [magento/magento2#32596]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Create a Category in the admin and specify a value for available_sort_by
2. Execute the following api (change the id based on your created category)
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://example.com/rest/all/V1/categories/1321',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'PUT',
  CURLOPT_POSTFIELDS =>'{
    "category": {
        "name": "Example Category",
        "parent_id": "25",
        "id": "1321",
        "custom_attributes": [
            {
                "attribute_code": "url_key",
                "value": "example-category"
            }
        ]
    }
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json',
    'Authorization: Bearer xxxxxxxxxxx',
    'Cookie: PHPSESSID=2kansl4q65fupe9jn1ptrl6j2q; XDEBUG_SESSION=PHPSTORM'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

### Expected result (*)

![image](https://user-images.githubusercontent.com/6040343/112487552-1a80a900-8d7d-11eb-99c8-cceca7c4f080.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/6040343/112487592-23717a80-8d7d-11eb-8ed8-56b322d09d9a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Foxtrot** [comment]
Hello,  @lewisvoncken. Unfortunately, I'm closing and re-creating this PR, as I was not able to push any changes to this PR branch. Please feel free to push any updates to https://github.com/magento/magento2/pull/33001.

**Comment by magento-engcom-team** [comment]
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41612` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
