### ISSUE TITLE
Magento Security panel provide 500 error while verifying the confirmation code frequently.

### ISSUE THREAD

**Issue by subhadeep-webkul** [magento/magento2#32591]
**Summary of the issue:**
I am receiving 500 error while try to verify the site (site.com) from magento2  security panel.

Errors received in console:
a)Exception printing is disabled by default for security reasons.(500 in validate url)
b)POST https://account.magento.com/scanner/verificationcode/ jquery.js:10260 validate / 500

I am also attaching the error snaps for reference .
![error 500](https://user-images.githubusercontent.com/81345650/112423239-4178b400-8d58-11eb-8188-b71a1776584c.png)
![error_magento_sce_panel](https://user-images.githubusercontent.com/81345650/112423286-56554780-8d58-11eb-9d24-5a577618156f.png)

**Environment**

site based on magento 2.3.5 p2 version , Varnish caching configured in site and cloudflare used for Cdn.

**Steps**

1.sign up to magento security panel and try to add a site. 

2. After adding the meta tag from magento admin and theme code end as well , the verify confirmation code button not responding for about 10-15 mins frequently.

3. After about 10 mins , after pressing the button of confirm code on magento security panel , it loaded for 10 secs but no response, after that i check the browser console and found that the 500 error coming from magento security panel itself.

**Expected Or Actual Result**
Expected that result was verified but it showed as not verifed on security panel.

Need appreciation.

Thanks and regards,
subhdeep , team webkul

**Comment by hostep** [comment]
@MaxSavich, sounds like something you might be interested in.

Not sure, if github is the correct place to report these sort of things though...

**Comment by engcom-Lima** [comment]
Hi @subhadeep-webkul,

This does not look like Magento Dev issue. If you are facing any website configuration issue, you can check with Magento Support.

Please update the description accordingly if you think this is related to Magento Dev otherwise we'll have to close this thread.

Thanks

**Comment by engcom-Lima** [comment]
Hi @subhadeep-webkul,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
