### ISSUE TITLE
Failed to set PHP CodeSniffer installed_paths Config (2.4.2, Composer 2)

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#32609]
### Summary (*)
Failed to set PHP CodeSniffer installed_paths Config
In my opinion its a deployment order: CS, should be configured after Magento deployManager (missing NonComposerComponentRegistration.php deployed via deployManager)
Works fine with composer 1

### Examples (*)
```
mkdir ~/cs-test
cd ~/cs-test
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition -vvv
[...]
> post-update-cmd: Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->onDependenciesChangedEvent
Running PHPCodeSniffer Composer Installer
Executing command (/Users/XXX/project-community-edition/vendor/bin): phpcs --config-show installed_paths
Executing command (/Users/XXX/project-community-edition/vendor/squizlabs/php_codesniffer): '/usr/local/Cellar/php@7.4/7.4.13_1/bin/php' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='2G' ./bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility
Failed to set PHP CodeSniffer installed_paths Config

Warning: require(/Users/XXX/project-community-edition/vendor/composer/../../app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory in /Users/XXX/project-community-edition/vendor/composer/autoload_real.php on line 75

Fatal error: require(): Failed opening required '/Users/XXX/project-community-edition/vendor/composer/../../app/etc/NonComposerComponentRegistration.php' (include_path='/Users/XXX/project-community-edition/vendor/magento/zendframework1/library:.:/usr/local/Cellar/php@7.4/7.4.13_1/share/php@7.4/pear') in /Users/XXX/project-community-edition/vendor/composer/autoload_real.php on line 75

> post-update-cmd: MagentoHackathon\Composer\Magento\Plugin->onNewCodeEvent
start magento deploy via deployManager
start magento deploy for magento/magento2-base
jump over deployLibraries as no Magento libraryPath is set
[...]
composer -V
Composer version 2.0.11 2021-02-24 14:57:23
```

### Proposed solution
Reorder CS config AFTER magento deployment

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @maciej-orba,
Unfortunately, we didn't get any response from you for a long time, so I'll close this issue as fixed. In case if you still have this issue - please drop a comment here.

**Comment by maciej-orba** [comment]
yes i can confirm, fixed in installer 0.2.1

**Comment by maciej-orba** [comment]
PHP CodeSniffer Config installed_paths set to ../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility

**Comment by PiroozMB** [comment]
Still having this issue with upgrading to magento version 2.4.3 . Any solution to that?

**Comment by AtifChatdroid** [comment]
Same issue here when upgrading to magento version 2.4.3-p1

**Comment by crowd42** [comment]
I'm facing the same issue, does anyone know how to fix it? thanks

**Comment by hostep** [comment]
According to the comments above, you should first upgrade `magento/magento-composer-installer` to at least version 0.2.1, before attempting to upgrade Magento itself. @PiroozMB, @AtifChatdroid, @crowd42 has anyone already tried that?

**Comment by alltomasterpiece** [comment]
I've had the same issue.
I was deploying magento 2.4.3 project on Windows.
When I'd run composer install, I'd got this error.
 Failed to set PHP CodeSniffer installed_paths Config
I've finally found the solution.
The fact is, I hadn't run the xampp.
