### ISSUE TITLE
Grunt exec:<theme> issue

### ISSUE THREAD

**Issue by mayhem-ahmad** [magento/magento2#3260]
This issue appears when executing the following command:
sudo grunt exec:<theme>

Processed Area: frontend, Locale: en_US, Theme: <vendor>/<theme>, File type: less.

> > [Magento\Framework\Exception\FileSystemException]  
> >   The "/var/www/<theme>/" file doesn't exist or not a file
> > dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
> > Exited with code: 1.
> > Warning: Task "exec:<theme>" failed. Use --force to continue.

Aborted due to warnings.

And this issue appears when executing the following command:
sudo grunt less:<theme>

Running "less:<theme>" (less) task

> > Destination pub/static/frontend/<vendor>/<theme>/en_US/css/styles-m.css not written because no source files were found.
> > Destination pub/static/frontend/<vendor>/<theme>/en_US/css/styles-l.css not written because no source files were found.

Done, without errors.

**Comment by shuaiZend** [comment]
![image](https://cloud.githubusercontent.com/assets/1478692/12836173/4f007cf8-cbf1-11e5-940e-3a34a96f33eb.png)

**Comment by code-K** [comment]
i have this issue too. Any solution to it?

Thanks much and best regards,
Chris

**Comment by mrkhoa99** [comment]
Hello,

**1.** You try to run deploy static command line under your Magento root folder: `php bin/magento setup:static-content:deploy`
**2.** On Windows environment, please run command prompt as administrator: https://technet.microsoft.com/en-us/library/cc947813(v=ws.10).aspx

Run Grunt command again.

**Comment by mayhem-ahmad** [comment]
Thanks! guys .

**Comment by MomotenkoNatalia** [comment]
@mayhem-ahmad do you still have this issue?

**Comment by mayhem-ahmad** [comment]
@MomotenkoNatalia 
No I solved it, it turns out that i have errors in my theme less files .
Thanks!

**Comment by digimix** [comment]
Ran into a similar issue after I cleared the pub/frontend/<Vendor>/<theme> directory and attempted to re-deploy via $ grunt exec:<theme>.

**Comment by MomotenkoNatalia** [comment]
@mayhem-ahmad I close the issue for now. If you have further question to this issue please feel free to reopen.

@digimix Please create new issue with the steps to reproduce.
