### ISSUE TITLE
Collection Processor not extendable for Customer Repository

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#32603]
### Summary (*)
It is not easily possible to change the collection processing in Customer Repository. E.g. when wanting to filter extension attributes in `getList()` method, it will not work.

The implementation of `Magento\Customer\Api\CustomerRepositoryInterface` is `Magento\Customer\Model\ResourceModel\CustomerRepository`. As `collectionProcessor` argument the `di.xml` specifies `Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor`. 

On [DevDocs - Searching with Repositories](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/searching-with-repositories.html#using-collection-processors-in-repositories) there is an example on how to change the `collectionProcessor` argument of the `Magento\Customer\Model\ResourceModel\CustomerRepository` by using a virtual type that in turn uses virtual types as filter and sorting processors. Within these filter and sorting processors one can add field mapping and custom filters.

The problem is that the example from the link above needs to be implemented in the customer module `Magento_Customer` itself. It is not possible for multiple custom modules to apply this pattern, because they would interfer, one overriding the application of the other. Only one module can specify the `collectionProcessor` argument, and that need to be the customer module.

An example where this is already done, is directly below the customer repository, it is the `Magento\Customer\Model\ResourceModel\GroupRepository`. Here a custom module can easily extend the virtual type `Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor\GroupFilterProcessor` by passing new custom filters or field mappings as arguments. Custom modules will not interfer with each other.

### Examples (*)
Due to this lack of flexibility, the [Amazon Pay Module](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/Plugin/CustomerCollection.php) needed to create an 'around' plugin for the `Magento\Customer\Model\ResourceModel\Customer\Collection` to apply an extension attribute filter.

This workaround would not be needed, if the customer repository would use a virtual subclass of `Magento\Framework\Api\SearchCriteria\CollectionProcessor`.

(I am in no way related to Amazon Pay, but while researching how filtering extension attributes can be done, I found out that Amazon is using this workaround)

### Proposed solution
The problem lies in https://github.com/magento/magento2/blob/aaeadff2f3130f2ddf14018cb64ca259799d1a1c/app/code/Magento/Customer/etc/di.xml#L379

Similar to how the group repository is registered:

```
<!-- @api -->
<virtualType name="Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor"/>
<!-- @api -->
<virtualType name="Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor">
    <arguments>
        <argument name="processors" xsi:type="array">
            <item name="filters" xsi:type="object">Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor</item>
            <item name="sorting" xsi:type="object">Magento\Framework\Api\SearchCriteria\CollectionProcessor\SortingProcessor</item>
            <item name="pagination" xsi:type="object">Magento\Framework\Api\SearchCriteria\CollectionProcessor\PaginationProcessor</item>
        </argument>
    </arguments>
</virtualType>
<type name="Magento\Customer\Model\ResourceModel\CustomerRepository">
    <arguments>
        <argument name="collectionProcessor" xsi:type="object">Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor</argument>
    </arguments>
</type>
```

This will allow custom modules to simply add field mappings or custom filters to `Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor`, allowing to handle extension attribute filtering.

In the solution above I left out a virtual sorting and pagination processor, I don't think that would be useful, but is discussable.

Even more enhanced: Filtering on extension attributes in a repository's `getList()` method should even be simpler without the need to specify a dedicated custom filter per extension attribute. Identically to how an extension attribute is automatically added to the select part by using the `$extensionAttributesJoinProcessor`, the filtering via search criteria of these attributes can also be allowed automatically, by implementing a general `ExtensionAttributeFilter` that implements `Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor\CustomFilterInterface` and is passed to `Magento\Customer\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor` as `customFilters` argument in the customer module itself.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by HenKun** [comment]
Not solved yet but does not seem to be important to filter on extension attributes

**Comment by engcom-Echo** [comment]
Hi @HenKun,

The description provided is not much clear and it appears to be a Feature Request rather than issue. If you can provide your use case that you are trying to achieve and what errors you are getting in doing so , I can provide more help into it or can advice some suggestions to implement the same.

Waiting for your response.

Thanks

**Comment by HenKun** [comment]
Unfortunately I cannot elaborate more on the description and use cases as I did above. It's quite detailed IMHO. Since there is not much demand for solving the issue by other developers it can be closed, as far as I am concerned. The issue can be used as a reference for the misleading Docs.

**Comment by engcom-Echo** [comment]
Hi @HenKun. Thank you for your report.
To help us process this issue please provide the issue description in the following format

Summary of the issue
Information of your environment, Preconditions (*)
Steps to reproduce
Expected and actual results
Thank you

**Comment by engcom-November** [comment]
Hi @HenKun ,
We are closing this issue as there has been no latest update on the same.
Thank you.
