### ISSUE TITLE
Product export fails with 40 k products

### ISSUE THREAD

**Issue by terolahtinen** [magento/magento2#32618]
### Steps to reproduce (*)

1. Install Magento 2.4
2. Create 40 000 products
3. Use export tool to export products to a csv file

### Expected result (*)

1. An export file is generated to var/export -folder containing the products

### Actual result (*)

1.  No export file is created

**Comment by engcom-Alfa** [comment]
Hi @terolahtinen 
I have tried to export the csv of products with 40k+ records. I could successfully get the file downloaded. Below is the screenshot of it.
<img width="925" alt="ExportWith40kProductsWorking" src="https://user-images.githubusercontent.com/51679138/118807318-be8e5880-b8c5-11eb-9dec-6204a8926e3d.PNG">
Kindly let me know if you are getting the same issue again.
Also please provide me the reproducible steps and mention me if it is specific to any type of products export and with any particular export filter combination.

**Comment by engcom-Alfa** [comment]
Since there is no update last ~15 days, this issue is getting closed. Kindly create a new ticket with updated reproducible steps in the latest version, in case if you are facing the same issue again.
