### ISSUE TITLE
Add assign customer to cart mutation

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#32615]
*As a developer I want to assign a customer to an existing guest cart so that I can easily implement the checkout with the register method.*

At the moment there is no possibility to easily implement the checkout with the register method when using the graphql api.
The [Venia Storefront Demo](https://venia.magento.com/) is also facing the issue as the checkout with the register method is not working correctly. If you place an order there and register simultaneously the order is not connected to your new user account, which contradicts the purpose of this register checkout method.

There is a [REST endpoint](https://github.com/magento/magento2/blob/3de1d60e7eaeb551af15e38142fa08cd219e8603/app/code/Magento/Quote/etc/webapi.xml#L97) which does exactly what's needed to solve the problem.

The mergeCarts mutation doesn't solve the problem as it just merges cart items.

The solution would be to either make the mergeCarts mutation merge ALL data into the customer cart or add a new mutation which assigns a customer to a guest cart. The implementation would be quite simple as the [GuestCartManagementInterface::assignCustomer() method](https://github.com/magento/magento2/blob/3de1d60e7eaeb551af15e38142fa08cd219e8603/app/code/Magento/Quote/Api/GuestCartManagementInterface.php#L33) does exactly what's needed.

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
Hi @oneserv-heuser 
` mergeCarts(source_cart_id: String!, destination_cart_id: String): Cart! @doc(description:"Merges the source cart into the destination cart") `

This mutation expects that:
-  'source_cart_id' - guest's cart  
-  'destination_cart_id' - customer's cart
Then it just merge items from the guest cart to the customer's one and marks the guest cart as inactive.

It seems to me that the best solution is also to allow you to specify:
-  'source_cart_id' - customer's cart
-  'destination_cart_id' - guest's cart  
So it will work the same way as [GuestCartManagementInterface::assignCustomer() method](https://github.com/magento/magento2/blob/3de1d60e7eaeb551af15e38142fa08cd219e8603/app/code/Magento/Quote/Api/GuestCartManagementInterface.php#L33)

@eduard13, what do you think about it?

**Comment by oneserv-heuser** [comment]
@khrystynastolbova I guess it would be more distinct to create an extra mutation which executes the [GuestCartManagementInterface::assignCustomer() method](https://github.com/magento/magento2/blob/3de1d60e7eaeb551af15e38142fa08cd219e8603/app/code/Magento/Quote/Api/GuestCartManagementInterface.php#L33). The mutation would just need a cart_id as the other parameters can be obtained from the session.

**Comment by khrystynastolbova** [comment]
@oneserv-heuser Ok, I will create an extra mutation

**Comment by magento-engcom-team** [comment]
@engcom-Hotel Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42995` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
