### ISSUE TITLE
Magento CE 1.9 vs Magento CE 2.0 Performance Comparison | MageCore, Inc

### ISSUE THREAD

**Issue by comunidademagento** [magento/magento2#3261]
This Comparison is true?

http://www.magecore.com/blog/news/magento-ce-19-vs-magento-ce-20-performance-comparison

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by cscd98** [comment]
@davidalger I'm not sure why this is closed. The performance of M2 is quite bad in the checkout specifically (all those requests?). I'm not sure the idea of interfaces while sounding good on paper is good for performance either.

I hope you improve the performance.

**Comment by davidalger** [comment]
@craigcarnell The reason this is closed is as stated above. The GitHub issue tracker is for bug reporting, and this is far from a bug report and rather clearly stated a technical question regarding a blog post.

I think it's pretty clear that Magento cares about performance, and will do what's necessary to resolve any performance problems that are found. If I gave a different impression than that in closing, I do apologize!

If you have technical details pointing to specific problematic performance areas in the software and/or how to fix them, that would be something IMO which would warrant opening an issue. PRs demonstrating performance enhancements would also I'm sure be welcome. General chatting about performance are best kept to the forums though.
