### ISSUE TITLE
Unable to decrease qty in cart, when its higher than available.

### ISSUE THREAD

**Issue by AkermanisM** [magento/magento2#32626]
### Preconditions (*)
1. Magento Version 2.4.0

### Steps to reproduce (*)

1. Create product with 20 Qty
2. Add product to cart with 10 Qty
3. Change available product Qty to 5
4. Go to cart, a message is displayed that product is not available in requested quantity
5. Change Qty to 2 and update cart

### Expected result (*)
1. Qty of cart item changes to 2

### Actual result (*)
1. Qty of cart item stays 5.

### Causes
1. In vendor/magento/module-checkout/Model/Cart.php:528
```
if ($item->getHasError()) {`
     throw new \Magento\Framework\Exception\LocalizedException(__($item->getMessage()));`
}
```

hasError() = true, but the $item->getMessage() returns empty string.

2. This behaviour appears to be caused byvendor/magento/module-catalog-inventory/Model/Quote/Item/QuantityValidator/Initializer/StockItem.php:121
```
if ($result->getHasError() === true && in_array($result->getErrorCode(), ['qty_available', 'out_stock'])) {
    $quoteItem->setHasError(true);
}
```
This check is called twice, first for 10, then 2 qty, however the error is never unset. Changing the code to 
```
if ($result->getHasError() === true && in_array($result->getErrorCode(), ['qty_available', 'out_stock'])) {
    $quoteItem->setHasError(true);
} else {
    $quoteItem->setHasError(false);
}
```
Appears to fix the error, however I'm not sure how this might impact other magento funcionality.
---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by AkermanisM** [comment]
@magento give me 2.4-develop instance

**Comment by AkermanisM** [comment]
I was unable to replicate this on the develop instance. It must be caused by some other modification.

**Comment by DinkoIlicic** [comment]
I managed to reproduce the issue on Default Magento 2.4.4 version. The issue is a bit specific:
The project has to have the following module replaced/removed "magento/module-inventory-sales", in my case I have removed all the module-inventory modules.

Additionally, it only affects simple product types, by following the provided steps. The posted solution is resolving the issue as well.
