### ISSUE TITLE
State/Province drop down not appear issue 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32628]
State/Province drop down not appear issue 

### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

- As guest user add 2-3 products to cart 
- Shopping Cart 
- Click on Checkout with multiple addresses 
- Login page -> Click on Create an account button 
- Observe State/Province field

### Expected result (*)
State/Province drop down/Field should be appear 

### Actual result (*)
State/Province drop down not appear
https://prnt.sc/y4uz7p

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Able to Reproduce the issue

![image](https://user-images.githubusercontent.com/46617848/113093949-8005e700-920e-11eb-8987-a5230e219ae8.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41668` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by magento-engcom-team** [comment]
Hi @renard123, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41668` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
