### ISSUE TITLE
The "--access-key" option does not exist. on configuring S3 bucket

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#32627]
I am getting error in console while trying to install aws bucket :

**Command**
 bin/magento setup:config:set --remote-storage-driver="aws-s3" --remote-storage-bucket="abc-web-img" --remote-storage-region="ap-south-1" --remote-storage-prefix="mysite" --access-key=xyz --secret-key=abc -n
 
 **Error** 
  The "--access-key" option does not exist.
  
  
**Magento Version :** 2.4.2
**Server :** Nginx 
**Database :** Mysql AWS RDS

**Comment by ia-gaurav** [comment]
@magento give me 2.4.2-develop instance

**Comment by ia-gaurav** [comment]
@denchev  does it shows any setting in admin to do this also

**Comment by denchev** [comment]
@ia-gaurav No, this is only via CLI.

**Comment by ia-gaurav** [comment]
@denchev  thanks it worked

**Comment by engcom-Lima** [comment]
Hi @ia-gaurav

I hope your issue get fixed  and please confirm to us about the same.

is it resolved?

**Comment by ia-gaurav** [comment]
@engcom-Alfa  it was resolved

**Comment by engcom-Lima** [comment]
@ia-gaurav Okay Thanks for confirmations. Hence, closing this ticket.
