### ISSUE TITLE
Attribute Metadata Cache not being deleted when signing out session

### ISSUE THREAD

**Issue by HumbertoGonc** [magento/magento2#32621]
### Preconditions (*)

1.  Magento version: 2.3.6
2.  Open Source version

### Steps to reproduce (*)

3.  Create a type of user – “distributor”.
4.  When a “distributor” is created, a new customer_group associated to this “distributor” is also created.
5.  When this “distributor” is creating a new customer in the backend:
       Sales -> Orders -> Create New Order -> Create New Customer
6.  The filter works, and the presents an unique group in “Account Information”:
       ->  This information is saved in cache.

**The problem comes when I Sign Out of this “distributor” session and Log In with the admin user.**

### Expected result (*)

9.  If I try to create a new customer in the same way, when logged as **admin**:
       Sales -> Orders -> Create New Order -> Create New Customer
10.  Returns me all groups in the select field Group.  

### Actual result (*)

7.  If I try to create a new customer in the same way, when logged as **admin**:
       Sales -> Orders -> Create New Order -> Create New Customer
8.  Returns me just the group of the latest “distributor” in the select field Group, and not all groups.
    ![imagem](https://user-images.githubusercontent.com/72799015/113563580-d8b6f480-95ff-11eb-9c35-da8fd703436b.png)

### Possible solution (*)

__The best solution would be to clean cache when I log out - I didn’t found how to do it yet.

11.  In file:
       vendor\magento\module-customer\Model\Metadata\AttributeMetadataCache.php
       add the clean() method in the beggining of method Load() as in the image below:
       ![imagem](https://user-images.githubusercontent.com/72799015/113563727-229fda80-9600-11eb-93ee-9b0dd9f84d19.png)

**Note:  I’m actually using a beforeLoad() plugin in order to don’t modify core files.**

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @HumbertoGonc,
Unfortunately, it's not clear what issue do you have and what's working incorrectly.
Could you provide more details, maybe with some examples?
Thank you!

**Comment by HumbertoGonc** [comment]
Hi Ihor,

Sorry for my late answer.

 

I’ve redone my solution.

 

I’ve created a type of user – “distributor”.

When a “distributor” is created, a new customer_group associated to this “distributor” is also created.

 

When this “distributor” is creating a new customer in the backend:

 

Sales -> Orders -> Create New Order -> Create New Customer

 

The filter works, and the presents an unique group in “Account Information”:



This information is saved in cache.

 

The problem comes when I Sign Out of this “distributor” session and Log In with the admin user.

 

If I try to create a new customer in the same way:

Sales -> Orders -> Create New Order -> Create New Customer

 

Returns me just the group of the latest “distributor” in the select field Group, and not all groups.

 

The best solution would be to clean cache when I log out - I didn’t found how to do it yet.

 

I’ve tried this below solution in:

vendor\magento\module-customer\Model\Metadata\AttributeMetadataCache.php 

 

file and it worked for me (I’m actually using a beforeLoad() plugin in order to don’t modify core files).

 



 

 

Thanks for your time and consideration.

Best regards,

 

Humberto Gonçalves
Programmer

Skype: Nka-Humberto Gonçalves

Email:  ***@***.***> ***@***.***

NKA – New Knowledge Advice Lda

Tel  + 351 253 278 646 |  Fax +351 253 276 154
 <http://www.nka.pt/> www.nka.pt

 

 <https://www.facebook.com/pages/NKA-New-Knowledge-Advice-Lda/189197804479572>    <http://www.linkedin.com/pub/nka-new-knowledge-advice-lda/42/602/113>    <https://twitter.com/NKA_Lda> 

 

 

De: Ihor Sviziev ***@***.***> 
Enviada: 31 de março de 2021 06:50
Para: magento/magento2 ***@***.***>
Cc: HumbertoGonc ***@***.***>; Mention ***@***.***>
Assunto: Re: [magento/magento2] $cachekey with bug in AttributeMetadataCache.php (#32621)

 

Hi @HumbertoGonc <https://github.com/HumbertoGonc> ,
Unfortunately, it's not clear what issue do you have and what's working incorrectly.
Could you provide more details, maybe with some examples?
Thank you!

**Comment by ihor-sviziev** [comment]
@HumbertoGonc, thank you for the additional info. May I ask you to update the issue description with this data? It will be so helpful during prioritization

**Comment by engcom-Lima** [comment]
Hi @HumbertoGonc 

I tried following steps to reproduce the issue using the backend in **Magento V - 2.4.develop**:

Step 1: Created the new customer group - "**Distributor**"
Step2: Created the new user from **Customers => All Customer => Add New Customer**
>  Choose the group - Distributor and created the user
> Placed the order using new created user and then logged out and i checked everything is working as expected.
> Placed the order again and create the user while placing the order - **Sales -> Orders -> Create New Order -> Create New Customer**, this is also working as expected.

Please try once on **Magento V - 2.4.develop**, If you are able to reproduce the issue then you can provide us reproducible steps with screenshot.

Hence as of now i am closing the issue, Please feel free to raise the new ticket or reopen the existing ticket with reproducible steps with screenshots.

Thanks for the understanding!
