### ISSUE TITLE
 Skipped Zip/Postal code in required fields 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32633]
Skipped Zip/Postal code in required fields 

### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

- As guest user add 2-3 products to cart 
- Shopping Cart 
- Click on Checkout with multiple addresses 
- Login page -> Click on Create an account button 
- Create an account page 
- Without enter any click on create account it focused on first name
- Enter 1st name click on create account it focused on last name
- Do this for all fields one by one 
- Observe Zip/Postal code is skipped in require validation 

### Expected result (*)

As Zip/Postal code is require field after city focused should be on Zip/Postal Code

### Actual result (*)

![image](https://user-images.githubusercontent.com/50658701/113097818-3a98e800-9215-11eb-8035-b6ce48d07823.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by yvaliya** [comment]
@magento I am working on this

**Comment by yvaliya** [comment]
This issue will be fixed by #32634

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
