### ISSUE TITLE
Unable to manage/add product configurations

### ISSUE THREAD

**Issue by TRMMarketing** [magento/magento2#3263]
After the initial creation of a configurable product you are unable to update the associated products relationship with the parent product. This means you cannot add additional existing products to a configurable product after creation. 

It seems (unless I am missing something) that the only way to associate a product to a configurable product is with the create configuration options which creates new SKUs and does not allow you to manage the associated products to the configurable.

**Comment by cgrechcw** [comment]
+1

**Comment by webtekindo** [comment]
+1

**Comment by antboiko** [comment]
Hi @TRMMarketing , thanks for your inquiry.

Please note you can update variations using Actions menu:
![configurable product](https://cloud.githubusercontent.com/assets/15442705/13114849/fbf557d4-d59d-11e5-9cab-31a4af0f277b.png)

**Comment by antboiko** [comment]
@TRMMarketing 

Please check my answer above. You can update variation of Configurable product by clicking on "Select" in Actions column and "Choose a different Product". This way you can replace generated product with existing one.

Please feel free to reopen this issue or to add a new one.

Best,
Anton.
