### ISSUE TITLE
Performance mview cataloginventory_stock_cl

### ISSUE THREAD

**Issue by samy-m-dev** [magento/magento2#32631]
### Preconditions (*)

Magento 2.3

### Steps to reproduce (*)
1. Open a Product in admin
2. Save the Product in admin

### Expected result (*)
1. No new record in cataloginventory_stock_cl 

### Actual result (*)
1. New record is created in cataloginventory_stock_cl

The problem is on $stockItem->addData($stockData);

The format of data differ from initial stockItem. (ex: qty 1.000 becomes 1). Which will trigger hasDataChanges to be true, then save the stock item in database.

```
public function execute(EventObserver $observer)
{
  $product = $observer->getEvent()->getProduct();
  
  $stockItem = $this->getStockItemToBeUpdated($product);
  
  if ($product->getStockData() !== null) {
      $stockData = $this->getStockData($product);
      $stockItem->addData($stockData);
  }
  $this->stockItemValidator->validate($product, $stockItem);
  $this->stockRegistry->updateStockItemBySku($product->getSku(), $stockItem);
  $this->processParents($product);
}
```

The trigger on cataloginventory_stock will also need to reindex price and catalog search index as these are dependant indexers. Which overall decrease the performance of indexer. As each time we save a product it will reindex stock, price, catalog search even if no data was changed.

**Comment by ihor-sviziev** [comment]
Hi @webtekindo,
The tables with _cl suffix are used for MView indexing mechanism, and it absolutely expected that when you're saving some product - it adds a record that inventory should be reindexed. 
Basically, it contains the data about items that should be re-indexed. More details here: https://magento.stackexchange.com/questions/164315/magento-2-tables-being-created-ending-in-cl

If you still believe that there is some issue - please describe it in more detail.

**Comment by webtekindo** [comment]
@ihor-sviziev thank you I already understand the mechanism.

But when there's no change to data it should not trigger any partial reindexing.

The problem is on $stockItem->addData($stockData); 

The format of data differ from initial stockItem. (ex: qty 1.000 becomes 1). Which will trigger hasDataChanges to be true, then save the stock item in database.

`public function execute(EventObserver $observer)
    {
        /** @var Product $product */
        $product = $observer->getEvent()->getProduct();

        /** @var Item $stockItem */
        $stockItem = $this->getStockItemToBeUpdated($product);

        if ($product->getStockData() !== null) {
            $stockData = $this->getStockData($product);
            $stockItem->addData($stockData);
        }
        $this->stockItemValidator->validate($product, $stockItem);
        $this->stockRegistry->updateStockItemBySku($product->getSku(), $stockItem);
        $this->processParents($product);
    }`

The trigger on cataloginventory_stock will also need to reindex price and catalog search index as these are dependant indexers. Which overall decrease the performance of indexer. As each time we save a product it will reindex stock, price, catalog search even if not data was changed.

**Comment by ihor-sviziev** [comment]
@webtekindo ok, now it's clear to me what you meant. Could you add all this info to the issue description?
Also as to me, it's not causing some performance issue, just does not need re-indexation for one specific product, which is a quite fast operation. I think we should put P3 priority for this issue.

**Comment by webtekindo** [comment]
@ihor-sviziev yes I agree this is not a very severe issue. But when Magento is connect to a PIM or an ERP and makes a lot of updates, sometimes mview indexing may have difficulty to keep up to date

**Comment by ihor-sviziev** [comment]
@webtekindo, thank you for the additional info! It will be really useful!

**Comment by engcom-Alfa** [comment]
Hi @webtekindo 
I tried reproducing it in the 4.2-develop version and below is information about my investigation.

1. I didn't find the table name specific namely "cataloginventory_stock_cl", and so I noted all the relevant tables total record and the table names are - cataloginventory_stock , cataloginventory_stock_item , cataloginventory_stock_status , cataloginventory_stock_status_idx , cataloginventory_stock_status_replica and cataloginventory_stock_status_tmp
2. Well, opened the existing product from admin and saved it again.
3. Cross checked all the tables updated records again, and didn't find any new record update as such in any of the above given tables.
Well here, I didn't find the table specifically by the name cataloginventory_stock_status_tmp in the DB.
Kindly upgrade to the latest version and please try to reproduce the same issue again. If you are going to find the same issue in the latest version, kindly update me here. Also provide me the detailed step by step procedure to get the cataloginventory_stock_status_tmp table created.

**Comment by webtekindo** [comment]
Hello @engcom-Alfa,

Those tables are related to MView from Magento 2. It's the indexer that runs in cron every minute by default. MView is used if you set the indexer mode to 'Index by Schedule'. 

You have to set Inventory indexer on 'Index by Schedule'.

**Comment by engcom-Alfa** [comment]
Hi @webtekindo 

Well I re tried to reproduce in Magento 2.4-develop version. Below are the steps I followed.

1. Set the indexing to Index by Schedule and noted the "cataloginventory_stock_cl" records count and it was 4.
2. Created a new simple product "xyz" and cross checked the "cataloginventory_stock_cl" records count, and that was updated to 8 records. (Re indexing was not yet done).
3. Later re indexed using the command, and re checked the records in the "cataloginventory_stock_cl", and the total records count was still 8.
4. Well, opened the same record again and just clicked on "Save" button.
5. Checked the records in the "cataloginventory_stock_cl", and **the total records count was still 8.**
6. Anyhow re indexed again and then checked the records in the "cataloginventory_stock_cl", and **the total records count was still 8.**
This is the screen record, that I have tried from my end.
https://user-images.githubusercontent.com/51679138/122360532-12976600-cf74-11eb-988c-fcd046eea87e.mp4

So, kindly go through my reproducible steps, and if there is any change in execution steps you want to do, kindly inform me mentioning that step number. If you are expecting anything else apart from what I have written in each step, kindly mention that expected output with the step number only please. If you want to add/remove any step from the list, kindly tell me what and in between which step please.

**Comment by engcom-Alfa** [comment]
Hi @

Tried to reproduce in Magento 2.4-develop version, and unable to successfully reproduce it. Below are the steps I followed.

1. Set the indexing to Index by Schedule and noted the "cataloginventory_stock_cl" records count and it was 4.
 
2. Created a new simple product "xyz" and cross checked the "cataloginventory_stock_cl" records count, and that was updated to 8 records. (Re indexing was not yet done).

3. Later re indexed using the command, and re checked the records in the "cataloginventory_stock_cl", and the total records count was still 8.

4. Well, opened the same record again and just clicked on "Save" button.

5. Checked the records in the "cataloginventory_stock_cl", and the total records count was still 8.

6. Anyhow re indexed again and then checked the records in the "cataloginventory_stock_cl", and the total records count was still 8.

This is the screen record, that I have tried from my end.
https://user-images.githubusercontent.com/51679138/122360532-12976600-cf74-11eb-988c-fcd046eea87e.mp4


Hope I have followed correct steps to reproduce as per my understanding.
- If there is any change you want to do in the execution considering above steps, kindly inform me the required change mentioning that step number.
- If you are expecting other output for any of the other step, kindly mention that expected output with the step number only please.
- If you want to add/remove any step from the list, kindly tell me what is that you want to add/remove and in between which step number.

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).
