### ISSUE TITLE
The proper styles are not been applied to the «Enable Block» checkbox on the backend block pages («develop» code branch)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3264]
https://mage2.pro/t/397
Similar to https://github.com/magento/magento2/issues/3226

**Comment by vil11** [comment]
@dfediuk Dmitry, thanks for reporting the issue!

Check-boxes on the "create/edit CMS Block" Admin page are already styled, the same as for [CMS Pages](https://github.com/magento/magento2/issues/3226). Now it looks like this:
![no](https://cloud.githubusercontent.com/assets/5585456/13645086/e1d40d2e-e631-11e5-8967-987fcaa72d99.jpg)
![yes](https://cloud.githubusercontent.com/assets/5585456/13645090/e6d7b6c2-e631-11e5-822c-7512e94897f9.jpg)

:sunny: Dmytro Vilchynskyi, M2 QA engineer.

**Comment by MomotenkoNatalia** [comment]
Changes are currently in the mainline. Issue can be closed.
