### ISSUE TITLE
Amazon Sales Channel fails to import orders when using Fulfilment By Amazon (FBA)

### ISSUE THREAD

**Issue by piorus** [magento/magento2#32645]
### Preconditions (*)

1. Create Store in Amazon Sales Channel and connect it with Amazon Seller Central store
2. Set  order import to `Yes`
3. Have at least one Amazon order with the status `Shipped` on the Amazon

### Steps to reproduce (*)

Amazon Sales Channel fails to create Magento orders during order synchronization when using FBA (Fulfilment by Amazon).

Following error occurs for all of the imported Amazon orders that have the status `Shipped`
```Cannot create sales order: Please check the shipping address information. "firstname" is required. Enter and try again. "street" is required. Enter and try again.```

channel_amazon.log have following entries for that error:

marketplaces.DEBUG: An error occurred during magento order creation {"amazon_order":"amazon-order-id","status":"Shipped","exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Please check the shipping address information. \"firstname\" is required. Enter and try again. \"street\" is required. Enter and try again. at /home/piotr/sites/m2/cdprs.magento/vendor/magento/module-quote/Model/QuoteValidator.php:107)"} {"area_code":"crontab","mode":"developer","module_version":"4.2.0","file":"/vendor/magento/module-amazon/Model/Order/AbstractOrderHandler.php","line":270,"class":"Magento\\Amazon\\Model\\Order\\AbstractOrderHandler","function":"handleMagentoOrderCreation","stack_trace":"#0 /vendor/magento/module-quote/Model/SubmitQuoteValidator.php(50): Magento\\Quote\\Model\\QuoteValidator->validateBeforeSubmit(Object(Magento\\Quote\\Model\\Quote\\Interceptor))\n#1 /vendor/magento/module-quote/Model/QuoteManagement.php(498): Magento\\Quote\\Model\\SubmitQuoteValidator->validateQuote(Object(Magento\\Quote\\Model\\Quote\\Interceptor))\n#2 /vendor/magento/module-quote/Model/QuoteManagement.php(453): Magento\\Quote\\Model\\QuoteManagement->submitQuote(Object(Magento\\Quote\\Model\\Quote\\Interceptor), Array)\n#3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Quote\\Model\\QuoteManagement->submit(Object(Magento\\Quote\\Model\\Quote\\Interceptor), Array)\n#4 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callParent('submit', Array)\n#5 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Quote\\Model\\Quote\\Interceptor))\n#6 /generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(91): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callPlugins('submit', Array, Array)\n#7 /vendor/magento/module-amazon/Model/Amazon/OrderManagement.php(648): Magento\\Quote\\Model\\QuoteManagement\\Interceptor->submit(Object(Magento\\Quote\\Model\\Quote\\Interceptor))\n#8 /vendor/magento/module-amazon/Model/Amazon/OrderManagement.php(367): Magento\\Amazon\\Model\\Amazon\\OrderManagement->convertCartToOrder(Object(Magento\\Quote\\Model\\Quote\\Interceptor), Object(Magento\\Amazon\\Model\\Amazon\\Account\\Order), false)\n#9 /vendor/magento/module-amazon/Model/Order/MsiOrderHandler.php(96): Magento\\Amazon\\Model\\Amazon\\OrderManagement->create(Object(Magento\\Amazon\\Model\\Amazon\\Order), Object(Magento\\Amazon\\Model\\Amazon\\Account\\Order), false)\n#10 /vendor/magento/module-amazon/Model/Order/AbstractOrderHandler.php(260): Magento\\Amazon\\Model\\Order\\MsiOrderHandler->createMagentoOrder(Object(Magento\\Amazon\\Model\\Amazon\\Order), Object(Magento\\Amazon\\Model\\Amazon\\Account\\Order))\n#11 /vendor/magento/module-amazon/Model/Order/AbstractOrderHandler.php(145): Magento\\Amazon\\Model\\Order\\AbstractOrderHandler->handleMagentoOrderCreation(Object(Magento\\Amazon\\Model\\Amazon\\Order), Object(Magento\\Amazon\\Model\\Amazon\\Account\\Order), Object(Magento\\Amazon\\Model\\Amazon\\Account))\n#12 /vendor/magento/module-amazon/Model/Order/AbstractOrderHandler.php(111): Magento\\Amazon\\Model\\Order\\AbstractOrderHandler->synchronizeOrdersForMerchant(Object(Magento\\Amazon\\Model\\Amazon\\Account))\n#13 /vendor/magento/module-amazon/Cron/ListingStateMachineAction.php(213): Magento\\Amazon\\Model\\Order\\AbstractOrderHandler->synchronizeOrders(1)\n#14 /vendor/magento/module-amazon/Cron/ListingStateMachineAction.php(176): Magento\\Amazon\\Cron\\ListingStateMachineAction->scheduleActionsForMerchant(Object(Magento\\Amazon\\Model\\Amazon\\Account))\n#15 /vendor/magento/module-amazon/Cron/ListingStateMachineAction.php(128): Magento\\Amazon\\Cron\\ListingStateMachineAction->runTasks()\n#16 [internal function]: Magento\\Amazon\\Cron\\ListingStateMachineAction->execute(Object(Magento\\Cron\\Model\\Schedule))\n#17 /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(350): call_user_func_array(Array, Array)\n#18 /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(809): Magento\\Cron\\Observer\\ProcessCronQueueObserver->_runJob(1617263700, 1617263747, Array, Object(Magento\\Cron\\Model\\Schedule), 'channel_amazon')\n#19 /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(776): Magento\\Cron\\Observer\\ProcessCronQueueObserver->tryRunJob(1617263700, 1617263747, Array, Object(Magento\\Cron\\Model\\Schedule), 'channel_amazon')\n#20 /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(267): Magento\\Cron\\Observer\\ProcessCronQueueObserver->processPendingJobs('channel_amazon', Array, 1617263747)\n#21 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\\Cron\\Observer\\ProcessCronQueueObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#22 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Cron\\Observer\\ProcessCronQueueObserver), Object(Magento\\Framework\\Event\\Observer))\n#23 /vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#24 /generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\\Staging\\Model\\Event\\Manager->dispatch('default', Array)\n#25 /vendor/magento/framework/App/Cron.php(86): Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch('default')\n#26 /vendor/magento/module-cron/Console/Command/CronCommand.php(117): Magento\\Framework\\App\\Cron->launch()\n#27 /vendor/symfony/console/Command/Command.php(255): Magento\\Cron\\Console\\Command\\CronCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#28 /vendor/magento/framework/Interception/Interceptor.php(58): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#29 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor->___callParent('run', Array)\n#30 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#31 /generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php(104): Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor->___callPlugins('run', Array, Array)\n#32 /vendor/symfony/console/Application.php(1009): Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#33 /vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Magento\\Cron\\Console\\Command\\CronCommand\\Interceptor), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#34 /vendor/magento/framework/Console/Cli.php(115): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#35 /vendor/symfony/console/Application.php(149): Magento\\Framework\\Console\\Cli->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#36 /bin/magento(23): Symfony\\Component\\Console\\Application->run()\n#37 {main}"}

### Expected result (*)

The module creates Magento order correctly

### Actual result (*)

The module fails to create magento order because of missing firstname and street out of Amazon order details (there is no firstname nor street for orders fulfilled by Amazon)

\Magento\Amazon\Model\Amazon\OrderManagement::createAddress is causing the issue there - there is no additional logic to verify if firstname or street is empty (it always is for orders Fulfilled by Amazon)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @piotrusin 
Kindly  provide Magento version and amazon sales channel version to reproduce the issue.

**Comment by piotrusin** [comment]
@engcom-Alfa this issue was confirmed by Magento customer support and occurs on module-amazon:4.2.0 and Magento 2.3.5-p2.

For anyone facing similar problems with this integration: we managed to fix that issue by creating a plugin over `\Magento\Amazon\Model\Amazon\Order` that set placeholders in `afterGetBuyerName`, `afterGetShipName`, `afterGetShipAddressOne`

**Comment by engcom-November** [comment]
@peter-rusin ,
This issue related to bundle extension is not part of this repository. Please contact the extension owner support on the [marketplace](https://marketplace.magento.com/extensions.html) page.
Thank you.
