### ISSUE TITLE
Magento 2.4.2 How to hide duplicate pictures when the product color is switched

### ISSUE THREAD

**Issue by AngeloZou** [magento/magento2#32641]
Hi everyboby,
I use Magento2.4.2. When the product is configurable, the default picture will be displayed repeatedly when switching colors. How to hide duplicate pictures when the product color is switched. No third-party extensions are used.

https://prnt.sc/111a244
https://prnt.sc/111a3fv
https://prnt.sc/111a4f2
Link url: http://devm2php74.tk/magento241/radiant-tee.html

**Comment by AngeloZou** [comment]
Hi everyboby,
I found a solution, modify your magento2.4.2 view.xml
app/design/frontend/yourtheme/yourtheme/etc/view.xml
`<vars module="Magento_ConfigurableProduct"> <var name="gallery_switch_strategy">prepend</var> </vars>`
change into
`<vars module="Magento_ConfigurableProduct"> <var name="gallery_switch_strategy">replace</var> </vars>`

It works fine.

**Comment by mrtuvn** [comment]
Seem this may not bug

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by shikhamis11** [comment]
@AngeloZou Thank you for reporting this, but it seems to be default behavior and not an issue. So I am closing this issue
