### ISSUE TITLE
Login/Registration success/error message not showing in Magento version 2.3.6-p1

### ISSUE THREAD

**Issue by milanu13** [magento/magento2#32655]
### Preconditions (*)

1. Magento version 2.3.6-p1
2. Mac OS, PHP 7.3.24, Apache: 2.4.41, MySQL: 5.7.22

### Steps to reproduce (*)

1. Go customer registration page and register a new customer.
2. Go to the login page and try to login with the wrong email or password.
3. Add mail to the subscription form in the footer.

### Expected result (*)

1. Session message should be shown for login, customer registration, and other operations.
2.

### Actual result (*)

1. No error or success message is showing up
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
@magento give me magento2.3.6-p1 instance

**Comment by shikhamis11** [comment]
@magento give me 2.3.6-p1 instance

**Comment by shikhamis11** [comment]
@milanu13 I tried to reproduce the issue on latest magento 2 develop instance but not able to reproduce this. Let me know if it requires additional configuration as well to reproduce the issue.

**Comment by milanu13** [comment]
@shikhamis11  I found this issue only in the Magento 2.3.6-p1 version. Thank You for your effort.

**Comment by milanu13** [comment]
Hi, I was working using an IP address. After pointing to the real domain this issue is gone.  Thank You for your effort.
