### ISSUE TITLE
Reorder feature in the administration page thrown an error when a product is out of stock

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#32651]
### Preconditions (*)
- Magento versions >= 2.3.6
- No MSI

### Steps to reproduce (*)
1. Create a product with one in the quantity
2. Create Test Product, in stock, Qty 1
3. Create Test Customer
4. Create Test Order in Adminhtml and assign the Test Customer
5. Complete the order
6. Click at the REORDER button

### Expected result (*)
- Magento creates a new order showing a nice error close the product out of stock

![Selection_289](https://user-images.githubusercontent.com/1553035/113313769-dd339280-930b-11eb-85f6-8dc112f938e6.jpg)

### Actual result (*)
- Magento shows an ugly exception error

![Selection_290](https://user-images.githubusercontent.com/1553035/113314212-5c28cb00-930c-11eb-837b-56705ff05056.jpg)

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

We have debugged Magento and we have discovered that the bug (https://github.com/magento/magento2/issues/24365) generates another issue when an administrator create an order because this line  https://github.com/magento/magento2/blob/2.3.6/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L159 set a new error code not handled here: https://github.com/magento/magento2/blob/2.3.6/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/Initializer/StockItem.php#L121

We suggest to add the getIsSuperMode() check in the IF condition at line 121: 

        if (!$quoteItem->getQuote()->getIsSuperMode() && $result->getHasError() === true && in_array($result->getErrorCode(), ['qty_available', 'out_stock'])) {
            $quoteItem->setHasError(true);
        }

So check the MC-19751: Placing order in Admin for more stock than is available at https://github.com/magento/magento2/commit/bf36d5be648d9e042f2ebc3f14e8eff9778098cf#diff-2932c5dab0cb802cf69bcd4baf14796bf5cac628f68936ab39fb7861e1b307e3R121

**Comment by shinesoftware** [comment]
@magento give me 2.4-develop instance

**Comment by shinesoftware** [comment]
I have tested the latest version 2.4-develop and seems that the issue is not affect this version.

![image](https://user-images.githubusercontent.com/1553035/113318276-985e2a80-9310-11eb-8927-3a2069dc2b00.png)

**Comment by shinesoftware** [comment]
@magento I am working on this

**Comment by shinesoftware** [comment]
@magento add to contributors team

**Comment by shinesoftware** [comment]
I can confirm that Magento 2.4-develop doesn't show the error as mentioned before even when the MSI is completely disabled.

![Selection_292](https://user-images.githubusercontent.com/1553035/113333652-fc89ea00-9322-11eb-8524-fea6a9f0efc7.jpg)

**Comment by shinesoftware** [comment]
Hello guys,

after spending some hour to debug the issue we have created a little free module that fix the issue for all the Magento 2.3.6 and above versions 'till < 2.4.0 version. You can download the fix here: https://bitbucket.org/shinesoftware/inventoryfix/src/master/

regards

**Comment by gabrieldagama** [comment]
Hi @shinesoftware, on public GitHub we are just accepting issues that are reproducible on 2.4-develop, if that is not the case we will close this issue. We recommend you to upgrade to the latest version to get this fix.

Hope that helps. Thanks!
