### ISSUE TITLE
Taxes not getting applied at the end of transaction..

### ISSUE THREAD

**Issue by panoramik707** [magento/magento2#32663]
Taxes are not applied at the end of order sales amount. 
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. https://drive.google.com/file/d/1FrKXfLjFJy8qCnLRvx7s-x12j7D2DYxO/view?usp=sharing
2.

### Actual result (*)

1. [](url)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
@panoramik707 
I have created a tax role and used that to purchase a product. If I see in the Admin end: Sales>Invoices (even after exporting) , there is tax applied properly as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/51679138/118645814-07c6a580-b7fd-11eb-90e5-9e6fc9b49f38.png)

Kindly update reproducible steps in case if it in a specific case like Tax rules settings/pin range etc.
Detailed step by step procedure helps us to reproduce and fix in this case.

**Comment by panoramik707** [comment]
ok- thanks- the issue is fixed as the tax rules was not being applied properly.
