### ISSUE TITLE
Customer Group Price - Price is not getting updated on QTY change

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32669]
### Description (*)

You can create products with grouped prices, for example like this:

![image](https://user-images.githubusercontent.com/16349349/113681933-dc5f7f80-96c2-11eb-9eab-c63ee6f1e0a5.png)

### Expected behavior (*)

If you open the product in the frontend and update the QTY, then the price should change accordingly.
At the moment nothing happens.

![demo](https://user-images.githubusercontent.com/16349349/113682312-4bd56f00-96c3-11eb-856e-c2d7cf98ef39.gif)

Tested on a fresh magento 2.4.2 Enterprise

### Benefits

Customers would see that the price has changed.
The probability that they think they did something wrong and the pricing does not work, is very high.
We get many calls from customers that ask why the price does not change.

### Additional information

You should add some products with advanced price setup in the sample data.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hello @Eddcapone,
The issue has been reproduced on the latest Magento 2.4 Instance.

See attached the screenshot:

![image](https://user-images.githubusercontent.com/24711761/113698076-b4d3db80-96f1-11eb-8283-ca620381972d.png)

![image](https://user-images.githubusercontent.com/24711761/113698117-bd2c1680-96f1-11eb-841c-fbe7a1e0f5e3.png)

Thanks.

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41767` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Eddcapone. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41767` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
