### ISSUE TITLE
[Issue] unable to save product (changes)

### ISSUE THREAD

**Issue by vertic4l** [magento/magento2#32662]
### Preconditions (*)
Magento 2.4.1

### Expected result (*)
Saving a product in backend doesn't end with an error message:
"Make sure the To Date is later than or the same as the From Date"

### Actual result (*)
error message occurs and product does not get saved

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### The Problem
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Attribute/Backend/Startdate.php

the validate method of Startdate.php checks if value of **$startDate** equals exactly **false** which is not.

### Solution
for example:
`if (!!$startDate === false) {`

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @vertic4l. Thank you for your report.
Could you please provide steps to reproduce so it will help in issue verification

**Comment by krishprakash** [comment]
Hi @vertic4l. Thank you for your report.
Feel free to reopen once you conform that issue reproduce on magento 2.4-develop instance
Thanks!!
