### ISSUE TITLE
Problem with catalog rules magento 2.3.4

### ISSUE THREAD

**Issue by Giacomo420** [magento/magento2#32665]
For several months, every time we set the catalog rules they apply correctly, then after 48h they deactivate by themselves, even if the setting provides for a more distant deadline. To restart them I tried to save and apply them again and then clear the cache several times, in some cases it temporarily solved the problem but it is not always enough.
the rules specifically provide for discounts each based on the category of products

**Comment by engcom-Alfa** [comment]
Hi @Giacomo420 
I have rested the issue in the Magento 2.4-develop version and there is no issue noticed as such. Below is the screen shot on the same.
![image](https://user-images.githubusercontent.com/51679138/118948155-a544e500-b975-11eb-9e83-f3206501127c.png)

Kindly upgrade to latest version and give a try on the same. If you find the issue again, you may please report a new bug on this.
