### ISSUE TITLE
Error after installing from 2.0 branch with sample data

### ISSUE THREAD

**Issue by Sniperumm** [magento/magento2#3266]
I've installed via the 2.0 branch (2.0.2) and I've also installed the sample data. 

Steps - 

Cloned 2.0 Branch
Ran composer install
Ran bin/magento sampledata:deploy
Went to url and ran web setup
Opened base url and got the usual error report generated.

Here's the error report:

a:4:{i:0;s:726:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Catalog schema: current version - 2.0.4, required version - 2.0.3
Magento_Catalog data: current version - 2.0.4, required version - 2.0.3
Magento_Search schema: current version - 2.0.3, required version - 2.0.1
Magento_Search data: current version - 2.0.3, required version - 2.0.1
Magento_Quote schema: current version - 2.0.2, required version - 2.0.1
Magento_Quote data: current version - 2.0.2, required version - 2.0.1
Magento_CatalogRule schema: current version - 2.0.1, required version - 2.0.0
Magento_CatalogRule data: current version - 2.0.1, required version - 2.0.0";i:1;s:1030:"#0 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 C:\Apps\Development\Wamp\www\magento2a\lib\internal\Magento\Framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#2 C:\Apps\Development\Wamp\www\magento2a\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#3 C:\Apps\Development\Wamp\www\magento2a\lib\internal\Magento\Framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 C:\Apps\Development\Wamp\www\magento2a\lib\internal\Magento\Framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 C:\Apps\Development\Wamp\www\magento2a\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main}";s:3:"url";s:16:"/magento2a/admin";s:11:"script_name";s:20:"/magento2a/index.php";}

**Comment by scholtz** [comment]
i suggest you should run bin/magento setup:upgrade as stated in the the [manual](http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data-after-composer.html)

**Comment by mazhalai** [comment]
@Sniperumm running upgrade wont work, since you are trying to downgrade(from a previous installation probably via develop in which module versions have been updated in module.xml, which is newer than 2.0.2). But, downgrade is not supported. Please clean you database and start over. You can use `bin/magento setup:uninstall` to clean it too, it will also clean generated files and cache.

**Comment by mazhalai** [comment]
Created MAGETWO-48744 to improve messaging when attempting downgrade.

**Comment by eharvest** [comment]
I'm running into the same issue, however I cannot afford to uninstall my magento2 as there're months work involved. Is there another solution at all? I run bin/magento upgrade all the time with no problem, now this issue has suddenly come up:
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Sales schema: current version - 2.0.3, required version - 2.0.2
Magento_Sales data: current version - 2.0.3, required version - 2.0.2

**Comment by vishalmobio** [comment]
Removing the reference to the module from app/etc/config.php or set 'o' value for each module then run magento setup:upgrade

**Comment by srepn** [comment]
> Removing the reference to the module from app/etc/config.php or set 'o' value for each module then run magento setup:upgrade

Doesn't work.  
For example, if I disable Magento_Store, I get a message: 

> PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Store\Api\StoreRepositoryInterface in /../vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73

**Comment by magento-engcom-team** [comment]
@Sniperumm, thank you for your report.
We've created internal ticket(s) MAGETWO-48744 to track progress on the issue.

**Comment by NerminPh** [comment]
Hi guys
Please help me to fix my error, update from 2.1.3 to 2.2 by the following steps 
upload the new magento version on root and the updated them too then run the following commands
rm -rf var
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
php bin/magento cache:clean
chmod -R 777 pub var generated

1. steps but when I add php bin/magento setup:upgrade it gives me the following code

php bin/magento setup:upgrade
Running schema recurring...Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 6

, and I follow the rest of steps

2. & Now I get the following error on the front-end and the admin area
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please update your modules: Run "composer install" from the Magento root directory.
The following modules are outdated:
Magento_Customer db data version: defined in codebase - 2.0.12, currently installed - 2.0.9
Exception #0 (Magento\Framework\Exception\LocalizedException): Please update your modules: Run "composer install" from the Magento root directory.
The following modules are outdated:
Magento_Customer db data version: defined in codebase - 2.0.12, currently installed - 2.0.9
#0 /home/cottonlinen/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
#1 /home/cottonlinen/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#2 /home/cottonlinen/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#3 /home/cottonlinen/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#4 /home/cottonlinen/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#5 /home/cottonlinen/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/cottonlinen/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#7 /home/cottonlinen/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#8 /home/cottonlinen/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#9 {main}
Thanks

**Comment by angelEbizmarts** [comment]
Hello @NerminPh are you still having this problem with your upgrade? if it so, please I highly recommend you to create a new Ticket with a proper title to have someone to help you, because this one is about to how to downgrade to another version (which is not at all recommended, and imply to modify manually some DB information).

**Comment by angelEbizmarts** [comment]
Hello @NerminPh are you still having this problem with your upgrade? if it so, please I highly recommend you to create a new Ticket with a proper title to have someone to help you, because this one is about to how to downgrade to another version (which is not at all recommended, and imply to modify manually some DB information).

I’m working on it #distributed-cd

**Comment by magento-engcom-team** [comment]
@angelEbizmarts thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.
