### ISSUE TITLE
[Question] Where does GraphQL Schema Directives get parsed?

### ISSUE THREAD

**Issue by elidrissidev** [magento/magento2#32678]
Sorry for opening this as an issue although it isn't really, since the discussions tab is not available.

So I'm working on a GraphQL extension for Magento 1 and I was learning from this repository how it's being implemented, but I'm stuck in one part that has to do with Schema Directives, I don't understand where they get parsed. Right now with my M1 implementation, I'm getting an error `Unknown directive "somedirective"` which makes sense but why in this repository I can't seem to find any code that parses them.

I would appreciate if I can get any help, or at least guide me to the direction where I should be looking. Thanks in advance!🙏🏻

**Comment by krishprakash** [comment]
Hi @elidrissidev. Thank you for your report.
GitHub issue tracker is intended for magento core technical issues only
Kindly refer[ community forum](https://community.magento.com/) or magento [stack exchange](https://magento.stackexchange.com) for general discuss about this topic. You will surely get help from anybody
