### ISSUE TITLE
Adding less files per <locale> for the same theme

### ISSUE THREAD

**Issue by mayhem-ahmad** [magento/magento2#3267]
Hey guys,

I want to add another language to my website, so i'm using twitter/css-flip so i can generate (styles-m-rtl.css,styles-l-rtl.css) for my theme.
so how can i add it to for <ar_SA>  for the same theme, so when i change the language switcher from the  frontend it will load just the assets in  <ar_SA> .

Your help is much appreciated,
Thanks!

**Comment by eug123** [comment]
Hi @mayhem-ahmad,

You can put whatever should be overridden to the: 
`<theme_dir>/web/i18n/<locale>/css|images|fonts|js`
or in the context of some module in the theme
`<theme_dir>/<module_name>/web/i18n/<locale>/css|images|fonts|js`

For example:
1. Image 
`app/design/frontend/Magento/luma/web/images/logo.svg`  - Default logo for default locale
`app/design/frontend/Magento/luma/web/i18n/de_DE/images/logo.svg`  - Overriden logo for German locale
2. Styles
`app/design/frontend/Magento/luma/web/i18n/de_DE/css/source/_extend.less` – You can override some variables in this file or add new styles (_extend.less is imported by [@magento_import](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.html#fedg_css-magento-import) instruction in the initial styles file) or you can import your own .less file for style modifications

**Comment by MomotenkoNatalia** [comment]
Hey @mayhem-ahmad !
Let us know if this works fine for you

**Comment by mayhem-ahmad** [comment]
Hi @eug123  @MomotenkoNatalia 

I tried to override the logo but it didn't work, so i placed it in 
vendor/vendor name/theme name/web/i18n/ar_SA/images/logo.png

I tried the same thing with styles, i placed it in 
vendor/vendor name/theme name/web/i18n/ar_SA/css/style-l.css
again it didn't work.

note: i'm adding the "ar_SA" as a store view, is there a new way in magento 2 to add new language to the website ?

Thanks!

**Comment by eug123** [comment]
Hi @mayhem-ahmad
Have you set "Arabic (Saudi Arabia)" locale for your "ar_SA" store view. In the admin
`Stores -> Configuration -> General -> Locale options` ?
Please clear caches and `pub\static\` folder then check again.

**Comment by mayhem-ahmad** [comment]
@eug123  thanks!, it's working fine now.
