### ISSUE TITLE
\Magento\Framework\Url.php::getUrl uses wrong scope with EnvironmentEmulation 

### ISSUE THREAD

**Issue by marvinhinz** [magento/magento2#32687]
### Preconditions (*)
1. Magento 2.4.2
2. Multi Store Setup with different domains per StoreView

### Steps to reproduce (*)
1. Create a CLI Command 
2. Iterate over all Stores
3. Start EnvironmentEmulation
4. Retrieve URLs of Various Entities (CMS Pages, Categories, Products...)

### Expected result (*)
1. The URLs should be correct for every emulated store

### Actual result (*)
1. The URLs keep the same domain of the first store

The Problem is, when a $routeParams['_direct'] is used, all route params get stripped before passing on to getBaseUrl(). The current _scope is not passed, and the default store is used. 

When adding following changes, it seems to work correct. But im sure there is a better / elegant way to fix (or workaround) this, so i didnt prepare a pr.

`\Magento\Framework\Url` in Line 838 add the following Line:
`$routeParams["_scope"] = $this->_scopeResolver->getScope();`

`\Magento\Framework\Url` in Line 749 replace with the following Line:
`return $this->getBaseUrl(['_scope' => $routeParams['_scope']]) . $routeParams['_direct'];`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Can you create PR for this problem if it's real issue ?

**Comment by engcom-Lima** [comment]
Hi @marvinhinz,

I don't think this issue is exist. Can you please provide me the few reproducible steps and details with screenshots. 

So, it will be help in reproduce the issue.

**Comment by marvinhinz** [comment]
Ill prepare a testcase when i can find some spare time

**Comment by engcom-Lima** [comment]
Hi @marvinhinz, As per your comments, when you will get time then you can provide the more details. Hence closing this issue as of now.

Please feel free to raise the new ticket or reopen the existing issue with reproducible steps and complete details with screenshots. That would be helpful in reproducing the issue.
