### ISSUE TITLE
Magento ver. 2.3.6 - A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by genseo2** [magento/magento2#32683]
### Proposed solution

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by genseo2** [comment]
Please advise and help me with this. thanks1

**Comment by krishprakash** [comment]
Hi @genseo2. Kindly update all the necessary details to reproduce the issue.
Without such a detail issue should be closed

**Comment by krishprakash** [comment]
Hi @genseo2. Feel free to reopen once you update all the details.
Thanks !!
