### ISSUE TITLE
URL key for specified store already exists.

### ISSUE THREAD

**Issue by vipin33** [magento/magento2#3268]
Hi sir ,
i am facing problem "URL key for specified store already exists." in category section during saving category.....in Magento ver. 2.0.0. plz help..some time it disappear or some time it shown ...but why i don't know.

**Comment by antboiko** [comment]
Hi @vipin33. This message appears when you create a category with already existing name in the same parent category (e.g. you already have category "Shoes" in "Men" and you try to create another category "Shoes" under "Men". In this case you will see this message "URL key for specified store already exists.").
By default URL key is being generated based on "Category Name". So for the second "Shoes" category it will try to assign the same URL key "shoes" which is already existing and you will get this error. In such cases user should manually define an URL key in "Search Engine Optimization' panel.  

Please check this solution and if that won't work for your case, please feel free to reopen this one.

Best,
Anton.

**Comment by azeemhassni** [comment]
I'm facing the same error in magento 2.1.0 when i update an existing category and i don't have any category with same URL key.

**Comment by SahakTadevosyan** [comment]
I have this problem in importing new products and adding new category. my magento version is Magento CE 2.1.0: Is there any solution?

**Comment by pboisvert** [comment]
@azeemhassni @SahakTadevosyan This specific issue is closed. If you are encountering this issue please open a new ticket and use the reporting guidelines to provide all information (system configurations, step by step instructions) needed to reproduce the issue

**Comment by SahakTadevosyan** [comment]
@pboisvert Thanks I will do like you mentioned.

**Comment by jyoti-bwc** [comment]
Hello
I am using magento 2.0.9 version for my site.
I am using the Mageworx Custom Option Templates Extension.
I have created the custom option templates.while assigning the products to custom options template in a group.
I am getting the error " URL Key for specified store already exists while saving it.

Can anyone help me out for this?

**Comment by sajidunnar** [comment]
did anyone got its solution ? I just migrated from m1 to m2 and having this issue

**Comment by qbo-tech** [comment]
The problem in this case, is likely that you have 2 or more products with the same name under the same category path and you try to save the category or add a new product with that same duplicated name.

In our case, there where 2 products with a EMPTY name (you can find those on the product grid by sorting by name), **deleting/disabling/changing those duplicated products fixes the problem.**

This isnt particularly  a bug, its more like a quite specific scenario where Magento tries to generate a URL like: category1/category2/.html-1 or something like that.

The correct approach would be to make the NAME attribute input mandatory.

**Comment by cgrio** [comment]
You have 2 products with same name. 
Try rename the name of product to another.

**Comment by assaka** [comment]
Also check the url keys of the cms pages, because they also might conflict with the category url keys

**Comment by ewallkrishnaprakash** [comment]
I am facing **"URL key for specified store already exists"** error when i am trying to update existing category or product for default store view as well as on secondary store view.

I have try to replicate the issue, When i check found problem in the following  scenario.

When save the category it will update the category url also the associated products url in url rewrite table.
When update the category if some product not have a url key or some products url key not updated in url rewrite table that time only this issue occurs.

Kindly suggest me how to solve the issue.
Magento verion : 2.1.3

**Comment by vikasneoventis** [comment]
0
down vote
	

I was also facing same issue while adding/editing categories.

Firstly I found there was wrong attribute id in "catalog_category_entity_varchar" table for url_key and url_path. Then I checked the exect attribute_id of both attributes ('url_key' and 'url_path').

e.g in "catalog_category_entity_varchar" table it was showing '117' and '118' but exact id was '119' and '120'. Then I found there was some rows in "catalog_category_entity_varchar" table with these (correct id '119','120').

I followed below steps to resolve issue.

    firstly I searched rows in "catalog_category_entity_varchar" where attribute id is in (117,118) and exported the data from table.
    then I searched rows in "catalog_category_entity_varchar" where attribute id is in (117,118,119,120) and deleted these data (rows) from table.
    then I just opened exported file in notpadd++ then I changed attribute ids 117 with 119 and 119 with 120 and import the data again.

Make sure take the backup of the database before doing above steps.
