### ISSUE TITLE
SQL request is incorrect on importing products. Magento 2.3.x

### ISSUE THREAD

**Issue by nans** [magento/magento2#32694]
https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L3247

We need to delete cross_sell from products with ids 1,2,3
`cross_sell link_type_id = 5`
And array will be
`$linksToDelete[5 => [1,2,3]];`
SQL request will be:
`WHERE link_type_id and product_id IN (1,2,3)`
As result, all records (cross_sell, up_sell) for products 1,2,3 will be deleted, because link_type_id is not set.
So, when we delete cross_sell, up_sell will be deleted too.

It looks like missed "=?". The correct code would be:
 `$whereLinkId = $this->_connection->quoteInto('link_type_id=?', $linkTypeId);`

**Comment by ihor-sviziev** [comment]
Hi @nans,

As @hostep mentioned, the issue was already fixed in the 2.4-develop branch.

Could you confirm that?

**Comment by nans** [comment]
> But it looks like this problem already got fixed in [02a93cb](https://github.com/magento/magento2/commit/02a93cbd776e7a30a796ac4397ba050e047ebcf4)
> Unfortunately it appears this fix is not released yet, if I have to guess, the fix is probably going to be included in Magento 2.4.3

Class updated in Magento 2.4.1, so the issue for the new version is not actual.
