### ISSUE TITLE
issue with product image cache

### ISSUE THREAD

**Issue by bohdan-berezhniy** [magento/magento2#32699]
If you add a new image to the product with an image name that contains '.'  dot, then save the product and clean image cache, a new cache will not be generated

### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1.Create a new product or go to the existing one.
2. Add image to product (image name should contain dot '.'). For e.g. 'i.mage.jpg'
3. Save product (on this step, image cache will be generated and all is fine)
4. Go to System -> Cache Management and click by button "Flush Catalog Image Cache"
5. Find your product on frontend

### Expected result (*)

 Image cache for product image generated successfully

### Actual result (*)

Image cache is not generated  (showed placeholder)
![image](https://user-images.githubusercontent.com/26215478/114182570-70dc1300-994b-11eb-9381-ff6dda838c30.png)

---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hello @bohdan-berezhniy,
I have verified this issue as per your above steps, actual result and expected.
I have create a new product, upload image as per defined name, Flush Catalog Image Cache & Full Cache Management then review the same product on front end but Product image is not showing.

Product image is showing on backend product grid list but on front end product image is not showing.

Front end:
![image](https://user-images.githubusercontent.com/24711761/114262441-9c1f3a80-99fd-11eb-9811-31a1ec95a0ed.png)

Backend:
![image](https://user-images.githubusercontent.com/24711761/114262453-a7726600-99fd-11eb-870a-3fc233b198e3.png)

![image](https://user-images.githubusercontent.com/24711761/114262505-f6200000-99fd-11eb-947a-20c09d59a604.png)

I suggest to you please latest Magento GitHub clone on your local system and verified this issue as well.

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41852` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by temptask** [comment]
I am working on this issue

**Comment by temptask** [comment]
@magento I am working on this

**Comment by temptask** [comment]
@magento add to contributors team

**Comment by temptask** [comment]
@magento I am working on this
