### ISSUE TITLE
2.3.6 var order.grand_total is not displayed in currency

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#32696]
When using email templates in a theme (extended from luma) using {{var order.grand_total}} does not display as currency formatted. It displays as XXX.XXXX (4 decimals, without currency symbol) It displays exactly the same as  {{var order.grand_total|raw}}.

I assume these filters should work, because they are used with other variables in ./Magento_Sales/email/order_new.html

Since there is no need to have {{var order.grand_total|raw}} output the same as {{var order.grand_total}}, this must be a bug.

[1]
https://community.magento.com/t5/Magento-2-x-Technical-Issues/mail-template-how-to-format-currency-var-order-grand-total-raw/m-p/468588

**Comment by engcom-Golf** [comment]
@f1-outsourcing I have tried reproducing this issue, but It is not replicated in Magento 2.4.2. Can you please upgrade your Magento version to verify.

**Comment by f1-outsourcing** [comment]
2.3 is still a maintained version not? So should this then not be back ported? (I am waiting for you to implement the correct way to read php ini settings, because now I had to change the source to even get it to work on my environment)

**Comment by f1-outsourcing** [comment]
> 
> 
> @f1-outsourcing I have tried reproducing this issue, but It is not replicated in Magento 2.4.2. Can you please upgrade your Magento version to verify.

So are you going to try with 2.3.6?

**Comment by f1-outsourcing** [comment]
Or can you point me to a patch that I can apply? I currently have email order templates that have 4 digits and a . instead of a , as decimal separator.

**Comment by engcom-Golf** [comment]
@f1-outsourcing I can't test on Magento 2.3.6. As many issues has already been fixed in the latest version. Patches currently are just provided via support channel for Magento Commerce & Cloud versions. So please get in touch with Support team.

**Comment by f1-outsourcing** [comment]
> 
> 
> @f1-outsourcing I can't test on Magento 2.3.6. As many issues have already been fixed in the latest version. Patches currently are just provided via the support channel for Magento Commerce & Cloud versions. So please get in touch with the Support team.

Are you aware of the concept that if you maintain multiple releases you have to update these accordingly? At least that is how it goes with most professional projects.

Afaik 2.3 is an official active release (that is why I chose it). Remove this 2.3 release then from the internet lots other people will be irritated that it is in fact an unsupported version.

If you are to lazy to test on 2.3 why would you expect that I would just convert my store to 2.4 after all the hassle to migrate my data from 1.9 to 2.3. (I think to 2.4 was not even supported)

(I am starting to hate this Adobe, I wonder what all your efforts actually generated, because I have the impression that a 2.4/2.3 store is just as slow as a 1.9 store under same cpu/mem limits.)

**Comment by f1-outsourcing** [comment]
> 
> 
> @f1-outsourcing I have tried reproducing this issue, but It is not replicated in Magento 2.4.2. Can you please upgrade your Magento version to verify.

I need a work-a-round for this until you have fixed 2.4 to run without elastic search support.
