### ISSUE TITLE
products.items.configurable_options.values does not return the values in the same order as they are in admin

### ISSUE THREAD

**Issue by jurvi** [magento/magento2#32691]
### Preconditions (*)

1. Magento Cloud 2.4.2 with PWA Studio as UI, using GraphQL API for data.

### Steps to reproduce (*)

1. Add a configurable product with some super attributes and variants, as values you might want to use format "100 mm" or such that can be seen in actual result screenshot.
2. Observe how the values for configurable_options are not returned in the same order as they are defined in admin (Manage Options (Values of Your Attribute))

### Expected result (*)

1. products.items.configurable_options.values query should return the values in same order as they are defined in admin

### Actual result (*)

Order of values is not the same, see screenshots (attribute id and code checked to be same):
![image](https://user-images.githubusercontent.com/12542277/113975772-b1069d00-9848-11eb-8686-56f07b2fd61b.png)
![image](https://user-images.githubusercontent.com/12542277/113975795-bbc13200-9848-11eb-89bd-443a81cfaefb.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by denchev** [comment]
@magento give me 2.4-develop instance

**Comment by denchev** [comment]
I cannot confirm this issue. Tested it with this graphql:

`query {
  products(search: "Opeth" ) {
    items {
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          values {
            default_label
            label
            store_label
            use_default_value
          }
        }
      }
    }
  }
}`

The return result set is:

`{
  "data": {
    "products": {
      "items": [
        {
          "configurable_options": [
            {
              "attribute_code": "size",
              "values": [
                {
                  "default_label": "55 cm",
                  "label": "55 cm",
                  "store_label": "55 cm",
                  "use_default_value": true
                },
                {
                  "default_label": "XS",
                  "label": "XS",
                  "store_label": "XS",
                  "use_default_value": true
                },
                {
                  "default_label": "65 cm",
                  "label": "65 cm",
                  "store_label": "65 cm",
                  "use_default_value": true
                },
                {
                  "default_label": "S",
                  "label": "S",
                  "store_label": "S",
                  "use_default_value": true
                },
                {
                  "default_label": "75 cm",
                  "label": "75 cm",
                  "store_label": "75 cm",
                  "use_default_value": true
                },
                {
                  "default_label": "M",
                  "label": "M",
                  "store_label": "M",
                  "use_default_value": true
                },
                {
                  "default_label": "6 foot",
                  "label": "6 foot",
                  "store_label": "6 foot",
                  "use_default_value": true
                },
                {
                  "default_label": "L",
                  "label": "L",
                  "store_label": "L",
                  "use_default_value": true
                },
                {
                  "default_label": "8 foot",
                  "label": "8 foot",
                  "store_label": "8 foot",
                  "use_default_value": true
                },
                {
                  "default_label": "XL",
                  "label": "XL",
                  "store_label": "XL",
                  "use_default_value": true
                },
                {
                  "default_label": "10 foot",
                  "label": "10 foot",
                  "store_label": "10 foot",
                  "use_default_value": true
                },
                {
                  "default_label": "28",
                  "label": "28",
                  "store_label": "28",
                  "use_default_value": true
                },
                {
                  "default_label": "29",
                  "label": "29",
                  "store_label": "29",
                  "use_default_value": true
                },
                {
                  "default_label": "30",
                  "label": "30",
                  "store_label": "30",
                  "use_default_value": true
                },
                {
                  "default_label": "31",
                  "label": "31",
                  "store_label": "31",
                  "use_default_value": true
                },
                {
                  "default_label": "32",
                  "label": "32",
                  "store_label": "32",
                  "use_default_value": true
                },
                {
                  "default_label": "33",
                  "label": "33",
                  "store_label": "33",
                  "use_default_value": true
                },
                {
                  "default_label": "34",
                  "label": "34",
                  "store_label": "34",
                  "use_default_value": true
                },
                {
                  "default_label": "36",
                  "label": "36",
                  "store_label": "36",
                  "use_default_value": true
                },
                {
                  "default_label": "38",
                  "label": "38",
                  "store_label": "38",
                  "use_default_value": true
                }
              ]
            }
          ]
        }
      ]
    }
  }
}`

![image](https://user-images.githubusercontent.com/1044677/126893384-f1446002-efd6-43ec-a3fd-a4f8b165f487.png)


The response from the GraphQL and the admin are equally ordered.

**Comment by engcom-Hotel** [comment]
Hello @jurvi,

We have tried to reproduce the issue in Magento 2.4-develop,  but are unable to do that. Please find below the steps we have followed:
1. Create a configurable product with the configurations mentioned in the description. Please find the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/126968976-0d817880-bbc2-4d5b-b4be-3223bb0c1e37.png)

![image](https://user-images.githubusercontent.com/51681618/126968351-61768950-ea32-4ea9-a059-26209bb31ca7.png)

2. Ran below query on grapql:

`query {
  products(filter: {
    sku: {
      eq: "levis"
    }
  }) {
    items {
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          values {
            default_label
            label
            store_label
            use_default_value
          }
        }
      }
    }
  }
}`

3. The response from the query is as follows:

`{
  "data": {
    "products": {
      "items": [
        {
          "configurable_options": [
            {
              "attribute_code": "size_updated",
              "values": [
                {
                  "default_label": "100 mm",
                  "label": "100 mm",
                  "store_label": "100 mm",
                  "use_default_value": true
                },
                {
                  "default_label": "1000 mm",
                  "label": "1000 mm",
                  "store_label": "1000 mm",
                  "use_default_value": true
                },
                {
                  "default_label": "1050 mm",
                  "label": "1050 mm",
                  "store_label": "1050 mm",
                  "use_default_value": true
                },
                {
                  "default_label": "1100 mm",
                  "label": "1100 mm",
                  "store_label": "1100 mm",
                  "use_default_value": true
                },
                {
                  "default_label": "1150 mm",
                  "label": "1150 mm",
                  "store_label": "1150 mm",
                  "use_default_value": true
                },
                {
                  "default_label": "1200 mm",
                  "label": "1200 mm",
                  "store_label": "1200 mm",
                  "use_default_value": true
                }
              ]
            }
          ]
        }
      ]
    }`


You can see the order in which the configurations are added, is showing the same in the graphql query. Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @jurvi,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
