### ISSUE TITLE
Disallowed file type for XML - Store Configuration 

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#32705]
### Summary (*)

Magento 2.4.1
PHP 7.4.14
I have created store configuration for the custom file upload in custom module, I have allowed XML file type but it still showing error "Disallowed file type."

### Proposed solution

It should be allow the XML file to be uploaded as per backend_model function.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
![1](https://user-images.githubusercontent.com/16815711/114196489-0b018280-996f-11eb-81c0-18f843b59d64.png)
![2](https://user-images.githubusercontent.com/16815711/114196502-0dfc7300-996f-11eb-976f-c1079c057d1e.png)
![3](https://user-images.githubusercontent.com/16815711/114196509-0fc63680-996f-11eb-8293-71dbab839794.png)

**Comment by jigar48** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by jigar48** [comment]
@magento how to access code ? I want to create store configuration for custom file upload to check issue

**Comment by engcom-Echo** [comment]
Hi @jigar48 ,

The correct method to use is  _getAllowedExtensions() and not getAllowedExtensions().
Kindly check and let us know.

Thanks

**Comment by engcom-Echo** [comment]
Hi @jigar48 ,

XML file type is configured as a protected file extension in Magento/Store/etc/config.xml , hence upload of xml file is restricted for security issues.

Thanks

**Comment by engcom-Hotel** [comment]
Hi @jigar48,

As per the comment by @engcom-Echo, the XML extension is protected file extension. So you are not able to do so. Are you able to perform the task with some other type of file.

Thanks

**Comment by engcom-Hotel** [comment]
Hi @jigar48,

It seems that your issue has been resolved. We are not able to hear from you since 14 days, so we are closing this issue for now.

If you still facing the issue either you can reopen it or create a new ticket.

Thanks
