### ISSUE TITLE
Naming conventions (vendor name) 

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#3270]
Under app\code I am now setting the vendor name to VaxLtd. What is the normal naming conventions to use here?

Should it be lower case e.g. vaxltd, or VaxLtd or Vaxltd?

Same ges for app/design/frontend/VaxLtd/UK, should it all be lower case? Does it matter?

The case for vendors is different, that all seems lower case.

**Comment by maksek** [comment]
@craigcarnell , please use forums for questions, GitHub only for bugs and PR.
