### ISSUE TITLE
Store switcher gives 404 when logged in

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#32706]
### Preconditions

1. Magento 2.3.4
2. PHP 7.2
3. Varnish cache enabled (not tested without it)

### Steps to reproduce

1. Create at least 2 store views (let's say store A and store B)
2. Create a customer account
3. Create a category
4. Change the URL key in the second store (store B)
5. Log in with the customer account created in step 2
3. Go to the category in frontend on store A
4. Use the store switcher to go to the store B
5. Use the store switcher to go back to store A

### Expected result

1. The user is redirected to the correct store
2. The URL is correct

### Actual result

1. The user is redirected to the correct store
2. The URL is incorrect (404) because the URL key of the category stays the same as the store B

### Related issues

I've found the issue #24942 that has the same bug but described differently.
I've tried the fix mentioned in this comment https://github.com/magento/magento2/issues/24942#issuecomment-539983560 and it seems to work perfectly, but according to the other comments bellow, it doesn't take into account the URL parameters and it still needs official fix as the same code is present in Magento 2.4.2 (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/etc/di.xml).

**Comment by mrtuvn** [comment]
Seem the fix already delivered to 2.3.6 or 2.4.2 (Official release) And also available in 2.4-develop branch git
Have you check your scenario again in latest code ? Or issue still reproducible in specific cases

**Comment by Axel29** [comment]
> Seem the fix already delivered to 2.3.6 or 2.4.2 (Official release) And also available in 2.4-develop branch git
> Have you check your scenario again in latest code ? Or issue still reproducible in specific cases

Hi, thanks for the answer, I didn't try it on a 2.3.6 or higher, do you have by any chance the fix for it? 

Thanks!

**Comment by mrtuvn** [comment]
https://support.magento.com/hc/en-us/articles/360049869051
Also while dive in some link i found this

**Comment by Axel29** [comment]
> https://support.magento.com/hc/en-us/articles/360049869051
> Also while dive in some link i found this in comment
> [#23755 (comment)](https://github.com/magento/magento2/issues/23755#issuecomment-697018813)

The [MDVA-30107](https://support.magento.com/hc/en-us/articles/360049869051) patch doesn't seem to define the same issue. In this patch, the user gets redirected to the home page, which is not my case, but I'll try it tomorrow to be sure.

**Comment by engcom-Oscar** [comment]
Hi @Axel29 !
Can you please check and confirm that issue not valid against 2-4-develop code (I was not able to reproduce it on 2-4-develop branch)

**Comment by krishprakash** [comment]
Hi @Axel29. Feel free to reopen/comment the issue once you confirm the issue is reproduce on latest 2.4-develop instance
Thanks!!
