### ISSUE TITLE
New page layout destroys product view

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32700]
### Preconditions (*)

1. 2.4.2 EE

### Steps to reproduce (*)

1. Create new page layout, inheriting from 1column, in your theme

**THEME\Magento_Theme\layouts.xml**

    <?xml version="1.0"?>
    <layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    	<update handle="1column"/>
    </layout>

**THEME\Magento_Theme\page_layout\hf-grouped-product-big-1col.xml**

    <?xml version="1.0" encoding="UTF-8"?>
    <page_layouts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/PageLayout/etc/layouts.xsd">
        <layout id="hf-grouped-product-big-1col">
            <label translate="true">Hf Grouped Product (Big) -- 1 Col</label>
        </layout>
    </page_layouts>

2. Open a product in the backend and change layout to 1column (or ommit this step, since it is set to 1column by default)

3. Load product in the frontend, it looks good:

[![enter image description here][1]][1]

4. Change the product layout to your new layout.

5. Load product in the frontend, it looks weird:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/mhhYR.png
  [2]: https://i.stack.imgur.com/ccCRE.png

### Expected result (*)

Why does it look different, even though my page layout inherits **1column** page layout and has no other changes yet?

### Actual result (*)

- see above

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
The xml file contain page_layouts directive tag that  you put in wrong file name
The correct path should be 

THEME\Magento_Theme\layouts.xml

The first file is correct and valid

**Comment by Eddcapone** [comment]
@mrtuvn Oh sorry, I accidentially pasted the wrong path :( I corrected the question

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,
Please confirm is this still persists ?

Thanks

**Comment by mrtuvn** [comment]
File bigcol have you try add handle 1 column ? If you dont magento will not extend from any page layout. So your page broken totally make sense

**Comment by engcom-Hotel** [comment]
Dear @Eddcapone,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
