### ISSUE TITLE
unnecessary spaces around inline-link widget

### ISSUE THREAD

**Issue by nordcomputer** [magento/magento2#32712]
### Preconditions (*)
Magento 2.4.2

### Steps to reproduce (*)
1. Place an inline-link (widget) into a site or cms-block inside of a text. 
`This is a ,{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="link" title="link" template="category/widget/link/link_inline.phtml" id_path="category/4"}}, to show the behaviour of inline-links.`

### Expected result (*)
The link should not have any spaces around it:
![grafik](https://user-images.githubusercontent.com/13378398/114356454-ea087f80-9b70-11eb-95f6-541b413262b8.png)

### Actual result (*)
The link gets inserted with additional whitespaces around it:
![grafik](https://user-images.githubusercontent.com/13378398/114356268-b2013c80-9b70-11eb-9ebc-2b5dd0e42425.png)

---

- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by ajijshekh123** [comment]
Hello @nordcomputer,
This issue has been fixed and merged the code throw the below link:
https://github.com/magento/magento2/pull/32719

Thanks.
