### ISSUE TITLE
Can't override knockoutjs template

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32715]
### Preconditions (*)

1. 2.4.2 EE

### Steps to reproduce (*)

I try to override the knockoutjs template `vendor\amasty\module-single-step-checkout\view\frontend\web\template\checkout\summary\item\details.html` from my own Theme.
The module `amasty\module-single-step-checkout` is registered as `Amasty_Checkout`

#### Attempt 1:

I copied the file into my theme at `THEME\Amasty_Checkout\web\template\checkout\summary\item\details.html` and made my changes, then I flushed the cache and the browser cache, but it still loads the old template.
I also executed `grunt clean` to clear static files. But it does not help either.

#### Attempt 2:

1. **THEME\Company_Base\web\template\details.html** (Copied from `THEME\Amasty_Checkout\web\template\checkout\summary\item\details.html`)

2. **THEME\Amasty_Checkout\layout\checkout_index_index.xml**:

```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="checkout" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
			<arguments>
				<argument name="jsLayout" xsi:type="array">
					<item name="components" xsi:type="array">
						<item name="checkout" xsi:type="array">
							<item name="children" xsi:type="array">
								<item name="sidebar" xsi:type="array">
									<item name="children" xsi:type="array">
										<item name="summary" xsi:type="array">
											<item name="children" xsi:type="array">
												<item name="cart_items" xsi:type="array">
													<item name="children" xsi:type="array">
														<item name="details" xsi:type="array">
															<item name="config" xsi:type="array">
																<!-- Assigning a new template -->
																<!--<item name="elementTmpl" xsi:type="string">Company_Base/details</item>-->
																<item name="template" xsi:type="string">Company_Base/details</item>
															</item>
														</item>
													</item>
												</item>
											</item>
										</item>
									</item>
								</item>
							</item>
						</item>
					</item>
				</argument>
			</arguments>
        </referenceBlock>
    </body>
</page>
```

#### Additional Information:

The template is set in the file `vendor\amasty\module-single-step-checkout\view\frontend\web\js\view\checkout\summary\item\details.js`:

```
/*jshint browser:true jquery:true*/
/*global alert*/
define(
    [
        'jquery',
        'Magento_Checkout/js/view/summary/item/details',
        'Magento_Checkout/js/model/quote',
        'Magento_Ui/js/modal/confirm',
        'Amasty_Checkout/js/action/remove-item',
        'Amasty_Checkout/js/action/update-item',
        'mage/translate',
        'ko',
        'Amasty_Checkout/js/options/configurable',
        'priceOptions',
        'mage/validation'
    ],
    function ($, Component, quote, confirm, removeItemAction, updateItemAction, $t, ko, configurable, priceOptions) {
        "use strict";
        return Component.extend({
            defaults: {
                template: 'Amasty_Checkout/checkout/summary/item/details'
            },
            ...
```

### Expected result (*)

1. Template should get overridden

### Actual result (*)

1. Template is not getting overridden

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Add mixin for `Amasty_Checkout/js/view/checkout/summary/item/details` and place you custom js in module
`YourBrand_CustomAmastyCheckout/js/view/checkout/summary/item/details-mixin`

**Comment by mrtuvn** [comment]
This problem may suitable for magento stackexchange than git for purpose report bug. In my opinion this may not a bug

**Comment by Eddcapone** [comment]
@mrtuvn ok thanks, but are you sure that this is not a bug? You can override templates by placing them in your own theme. I also managed to do this with .phtml and .html but in this case it just does not work. Maybe because the template is hardcoded into the .js view model file? You can't even override it from a layout file.
This looks like a bug to me. It should get programmed properly, so that you can override it from a layout file.

**Comment by mrtuvn** [comment]
I'm not sure maybe template process by jsLayout will different than normal template block (phtml) with fallback mechanism. Need to recheck

**Comment by mrtuvn** [comment]
Another approach you can try is use requirejs-config.js in custom theme to replacehtml

use map directive
'Amasty_Checkout/checkout/summary/item/details': 'Amasty_Checkout/checkout/summary/item/details-custom'

Amasty_Checkout/checkout/summary/item/details-custom create your own html file in theme

**Comment by Eddcapone** [comment]
I already found a way to override the template via uiRegistry, but in this bug report I try to point out that it does not work the normal way. But thank you very much for your help attempt.

**Comment by mrtuvn** [comment]
Good to know! Glad you find the way when we got many ways to get a job done. But imo i don't like XML way with crazy XML tree xmas. Hard to track. Hope it's should be improved someday

**Comment by mrtuvn** [comment]
Amasty checkout module is more complex than normal so i don't think you can override with basic normal way. I don't dig too much in it but i think they create they stuff via php for init components. Component will be added via php array

**Comment by mrtuvn** [comment]
![Screenshot from 2021-04-14 06-37-22](https://user-images.githubusercontent.com/1908873/114634040-e9482880-9ceb-11eb-8302-d5fada5ea5ed.png)
Tested replace html app/code/Magento/Checkout inside theme luma

**Comment by mrtuvn** [comment]
![Screenshot from 2021-04-14 06-53-15](https://user-images.githubusercontent.com/1908873/114635073-1d244d80-9cee-11eb-9eee-9ba25e39ee0b.png)
This one demo override html via layout like your second attemp in description

**Comment by Eddcapone** [comment]
@mrtuvn yes I guess the bug is only caused if the template was already overriden by another module. like described in my question. There is a module called "Amasty_Checkout" which overrides the template. And I try to override the overriden template again. Do you understand?

**Comment by mrtuvn** [comment]
![Screenshot from 2021-04-14 22-04-25](https://user-images.githubusercontent.com/1908873/114733273-6667b200-9d6d-11eb-92aa-9eb260585d71.png)
still work at my local

**Comment by Eddcapone** [comment]
@mrtuvn ok I see you have a module called Amasty/CustomCheckout. Did you made any additional changes there to make it work?

**Comment by mrtuvn** [comment]
No in last reploy that module not included/enable only module default of amasty and additional small in theme

**Comment by Eddcapone** [comment]
@mrtuvn Ok thx for testing. I have no explanation for this then. I will close the issue and if I know how I can reproduce it everytime then I will open another issue. Thx!

**Comment by mrtuvn** [comment]
If you need any further discuss please ping me or DMs to me on slack or skype (see my profile).

**Comment by Eddcapone** [comment]
@mrtuvn ok thank you very much for your offer :) very nice from you

**Comment by cartok** [comment]
I have the same problem right now, tried to override `vendor/magento/module-tax/view/frontend/web/template/checkout/summary/shipping.html` via theme and it does not work.

**Comment by elburro1887** [comment]
In case this helps anyone, I just found out that Amasty's own template file in `view/frontend/web/template/checkout/summary/item/details.html` is only loaded when "Allow to Edit Products in the Order Summary" is set to YES. If it is set to no then Magento's own file is loaded.

Im running Magento 2.3.3 and Amasty Checkout 3.0.13
