### ISSUE TITLE
Update to 2.4.2 is not possible with PHP 7.4.3

### ISSUE THREAD

**Issue by chequille** [magento/magento2#32718]
### Preconditions (*)

1. Installed php version 7.4.3
2. Magento 2.4.1

### Steps to reproduce (*)

1. Use composer require magento/product-community-edition 2.4.2 --no-update
2.

### Expected result (*)

1. Should update composer.json
2.

### Actual result (*)

1. Could not find a Magento project package matching "magento/product-community-edition 2.4.2" for PHP version 7.4.3
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @chequille 
As I checked with PHP 7.4.19, the Magento 2.4.2 is compatible and it is working well. You may have to upgrade to PHP 7.4.latest and the composer update.
You can find the Magento 2.4.2 here -> composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.2 _project_directory_

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).
