### ISSUE TITLE
Register Capture Notification for different Currency

### ISSUE THREAD

**Issue by wajihkm** [magento/magento2#32713]
https://github.com/magento/magento2/blob/c46d9bfea43f6ce8fe572b4498e858f15b3319cb/app/code/Magento/Sales/Model/Order/Payment/Operations/RegisterCaptureNotificationOperation.php#L42

The payment gateway's partial_capture command captures the amount in "Order Currency [$order->getOrderCurrencyCode()]",
How to register a capture command in the Currency that is used to Place the Order?

**Comment by engcom-Delta** [comment]
Hi @wajihkm,

There has no movement on this ticket , Hence closing it. Kindly raise new ticket if required.

Thanks
