### ISSUE TITLE
Billing address issue!

### ISSUE THREAD

**Issue by AndreyChorniy** [magento/magento2#3272]
Hello guys! 
I have found important bug in checkout process. 
Scenario:
I configured some of  Payment methods for specific country (i.e. USA). And I want to ship order to not available country (i.e. French) for this method. I have use my shipping address - French, Edmonton, 105 Ave NW... I have selected Shipping Method.
After this I want to use billing address: USA New York, 1 Broadway.... BUT I cannot use another billing address because payment method configured for USA country only and it is not available for French country. 

Please advice.

**Comment by sdzhepa** [comment]
@AndreyChorniy Thank you for reporting this issue. We have created an internal ticket `MAGETWO-48761` to fix the problem.

**Comment by asemenenko** [comment]
Hi @AndreyChorniy 

Not all payment methods have a billing address to be asked from a customer - we control only shipping address to allow or disallow orders to be placed for a certain regions with a certain payment method, this is the most common scenario, especially when it comes to international shipping.

**Comment by AndreyChorniy** [comment]
Hi @asemenenko 
As I understand Magento team will not  fix this bug. 

It is correct?

**Comment by AndreyChorniy** [comment]
@asemenenko 
Why do you close this error?
Your team initially recognized the problem, and then you just shut it. https://drive.google.com/file/d/0B2vGZI5KgHsdRmZ0WTBxYWk0b3M/

This is problem and you guys should to fix it!

Have a nice day.

**Comment by rfapinkesh** [comment]
nn
