### ISSUE TITLE
Error while opening Media Gallery in any Page Builder image component

### ISSUE THREAD

**Issue by mikamarkus** [magento/magento2#32748]
### Preconditions (*)

Magento Commerce v2.4.2

### Steps to reproduce (*)

1. Drag Image component to page
2. Click Select from Gallery
3. Modal will open, but it only says "Insert images..." at the top and no content

### Expected result (*)

Media Gallery should be loaded and user should be able to select an asset

### Actual result (*)

Empty modal appears

Console warnings:

`DevTools failed to load SourceMap: Could not load content for /static/version1617124211/adminhtml/Magento/backend/en_US/Magento_PageBuilder/js/content-type-factory.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

### Edit:

Issue started after Magento upgrade from 2.4.0 to 2.4.1 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @mikamarkus! Thank you for your report. 
Unfortunately, I couldn't reproduce the issue on a fresh 2.4-develop by following steps from this ticket. May you please recheck if we not missing some preconditions here and update ticket description?

**Comment by john-rock** [comment]
@mikamarkus I am experiencing the same issue. We recently upgraded from 2.3.2-p2 to 2.4.2 and none of our assets are showing in the Media Gallery.

![image](https://user-images.githubusercontent.com/46692803/115414153-cc1bca00-a1c3-11eb-9587-40997b315962.png)

**Comment by mikamarkus** [comment]
Actually our problem started after upgrade as well. Media Gallery content is just not showing up. Exactly the same problem which @john-rock has.

**Comment by engcom-Delta** [comment]
Hi @mikamarkus,
Issue is not reproducible in Magento 2.4 Develop instance , Hence closed .

**Comment by nocturnalfrog** [comment]
This issue only seems to appear in developer mode @engcom-Delta can you please check again?
