### ISSUE TITLE
Street Address {n} is double handled by localisation systems implemented in uiComponents

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#32749]
### Preconditions (*)

1. Magento 2.4.2 php 7.4

### Steps to reproduce (*)

1. Create checkout module with the __("Street Address"), __("Street address 1") and so on
2. Create translation of your plugin with something like "Street Address","Street" "Street address 1","House number"

### Expected result (*)

1. translation should work 

### Actual result (*)

1. right now we are getting translations as **Street** and **Street 1**
2. so in order to get the House number for our translation we have to use "Street Address","Street"  "Street 1","House number"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Golf** [comment]
@Naberdz I have been trying to reproduce the Translation Issue, but can't.  It seems, this may not be an issue. 

There are certain reasons, when Translations don't work. So please reply with below asked queries:

1. Did you install Magento Language translation Pack? 
2. Did you configure the Language to be used in specified scope i.e storefront via magento Admin Panel?
3. Path of Translation csv File?

**Comment by engcom-Golf** [comment]
@Naberdz This issue is Fixed for you?

**Comment by Naberdz** [comment]
No, we had use this workaround.

**Comment by engcom-Golf** [comment]
@Naberdz Thanks for your reply. Can you please answer for the asked questions. https://github.com/magento/magento2/issues/32749#issuecomment-863909522

Also please let me know:
Did you override the Checkout Module to add one 

Did you override **Magento_Checkout** module to create 2 Form Elements having Label as
__("**Street Address**")
__("**Street address 1**") 

Translation added  for above labels as giving below:
"Street Address","Street"
"Street address 1","House number"

You added translation inside your Module? If not please mention the path of your Translation CSV file ?

**Comment by Naberdz** [comment]
@engcom-Golf 
wel we use translation from HO-NL, so it's in vendor/honl/magento2-nl-nl
we also have custom translation file in template directory

language was selected as global for all stores. So every store use same language.

The module from onestepcheckout. we made translations for this module inside our template.
so it's in app/design/frontend/vendor/child_theme/i18n/nl_NL.csv

**Comment by engcom-Lima** [comment]
Hi @Naberdz,

For further analysis, can you please update below details:

1. Is onestepcheckout open-source module ? 
2. Without onestepcheckout module, with your provided steps can we be able to reproduce this 2.4-develop branch ? If not, can you provide more detailed **'Steps to reproduce'** as the instructions provided is not clear for us to reproduce this.

**Comment by engcom-Lima** [comment]
Hi @Naberdz,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
