### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by ludar** [magento/magento2#3274]
I have encountered this issue in 2.0, 2.0.1 and 2.0.2

In some cases when modifying custom options specifically drop down menus the product display breaks.
To replicate: Create an item with custom options, created a drop down menu with several items. Save.
Go back and delete one of the drop down choices.

Flushing Cache / Rebuilding Magento did not do anything.

What it looks like in admin area after save:
![screen shot 2016-02-03 at 10 50 19 am](https://cloud.githubusercontent.com/assets/1166369/12787806/068b6d30-ca65-11e5-88da-6d4c05a668e7.png)

The error dump on storefront page for the item that was edited:
`Warning: Invalid argument supplied for foreach() in /var/www/mystore.com/project-community-edition/vendor/magento/module-catalog/Block/Product/View/Options.php on line 213
#0 /var/www/mystore.com/project-community-edition/vendor/magento/module-catalog/Block/Product/View/Options.php(213): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/var/www/canser...', 213, Array)
#1 /var/www/mystore.com/project-community-edition/vendor/magento/module-catalog/view/frontend/templates/product/view/options.phtml(18): Magento\Catalog\Block\Product\View\Options->getJsonConfig()
#2 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/canser...')
#3 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Options), '/var/www/canser...', Array)
#4 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/canser...')
#5 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#6 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#8 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#9 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#10 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#11 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/AbstractBlock.php(501): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#12 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(778): Magento\Framework\View\Element\AbstractBlock->getChildHtml('', true)
#13 /var/www/mystore.com/project-community-edition/vendor/magento/module-catalog/view/frontend/templates/product/view/options/wrapper.phtml(15): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml('', true)
#14 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/canser...')
#15 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/var/www/canser...', Array)
#16 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/var/www/canser...')
#17 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/var/www/canser...')
#18 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#19 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#21 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#22 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#23 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#24 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#25 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/AbstractBlock.php(532): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#26 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(791): Magento\Framework\View\Element\AbstractBlock->getChildChildHtml('options_contain...', '', true)
#27 /var/www/mystore.com/project-community-edition/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml(35): Magento\Catalog\Block\Product\View\Interceptor->getChildChildHtml('options_contain...')
#28 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/canser...')
#29 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/var/www/canser...', Array)
#30 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/var/www/canser...')
#31 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/var/www/canser...')
#32 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#33 /var/www/mystore.com/project-community-edition/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#35 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info')
#36 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info')
#37 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info')
#38 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info', true)
#39 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info')
#40 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('product.info.ma...')
#41 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...')
#42 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.ma...')
#43 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.ma...', true)
#44 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.ma...')
#45 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#46 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#47 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#48 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#49 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#50 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#51 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#52 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#53 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#54 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#55 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#56 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#57 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#58 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#59 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#60 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#61 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#62 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#63 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#64 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#65 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#66 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#67 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#68 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#69 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#70 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#71 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#72 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#73 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#74 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#75 [internal function]: Magento\Framework\View\Layout->getOutput()
#76 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#77 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#78 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#79 /var/www/mystore.com/project-community-edition/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#82 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#83 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#84 /var/www/mystore.com/project-community-edition/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#85 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#86 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#87 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#88 /var/www/mystore.com/project-community-edition/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#89 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#90 /var/www/mystore.com/project-community-edition/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#91 /var/www/mystore.com/project-community-edition/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#92 /var/www/mystore.com/project-community-edition/vendor/magento/framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#93 /var/www/mystore.com/project-community-edition/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#94 /var/www/mystore.com/project-community-edition/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#95 {main}`

**Comment by katmoon** [comment]
Possibly the same issue as #2989

**Comment by mbrinton01** [comment]
Hello @ludar, this issue has been fixed in 2.0.5 patch release, so I'm closing it. Thanks for your help!
