### ISSUE TITLE
Magento 2.4.1 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.catalog_category_product_index_store0' doesn't exist

### ISSUE THREAD

**Issue by andrewb49** [magento/magento2#32745]
### Preconditions (*)

Get all categories by REST API Magento 2.4.1

### Steps to reproduce (*)

GET https://domain/rest/all/V1/categories/

### Expected result (*)

Get all categories

### Actual result (*)

In Exception Log: Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.catalog_category_product_index_store0' doesn't exist, query was: SELECT cat_index.category_id, count(cat_index.product_id) AS count FROM catalog_category_product_index_store0 AS cat_index WHERE (cat_index.category_id in (2, 3, 4, 5, 6)) GROUP BY cat_index.category_id {"exception":"[object] (Exception(code: 1146): Report ID: webapi-5fbbd8e7e2f81; Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mag2ma1h_shop2.catalog_category_product_index_store0' doesn't exist, query was: SELECT cat_index.category_id, count(cat_index.product_id) AS count FROM catalog_category_product_index_store0 AS cat_index WHERE (cat_index.category_id in (2, 3, 4, 5, 6)) GROUP BY cat_index.category_id at /home/mag2ma1h/public_html/shop/magento-2_4_1/vendor/magento/framework/Webapi/ErrorProcessor.php:208

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
seem work in latest code base
![Screenshot from 2021-04-15 06-50-42](https://user-images.githubusercontent.com/1908873/114794609-faaa3700-9db6-11eb-9835-965275422b9f.png)
Have you try in 2.4.2 release

**Comment by andrewb49** [comment]
@mrtuvn 

Never tried it in 2.4.2 but it didn't work in 2.4.0 and 2.4.1.

Any patches for this?

**Comment by mrtuvn** [comment]
Both cases work fine with my test in latest code

**Comment by andrewb49** [comment]
@mrtuvn 

It's single store website, but it isn't enabled. Do you think that cause the problem?

**Comment by mrtuvn** [comment]
dunno may not be that case! My test previously is single website no enabled single-mode

**Comment by andrewb49** [comment]
@mrtuvn Can you test it out on 2.4.0 or 2.4.1?

**Comment by vitalii0o** [comment]
Hey @andrewb49.

This commit helped me to fix the same problem:
https://github.com/magento/magento2/commit/61cb299119dacdb5f5553cb1b46f038ca32a39fa

**Comment by engcom-Golf** [comment]
@andrewb49 I have tried to reproduced on Magento 2.4.2 version &  dev-2.4-develop. It is working as expected. Kindly upgrade your Magento version.
