### ISSUE TITLE
Adobe Sensei (Product recommendations): renaming environment doesn't work

### ISSUE THREAD

**Issue by denis-zyk** [magento/magento2#32752]
### Preconditions (*)

1. Magento Commerce 2.4.1
2. Magento Product Recommendations 3.2.2
3. PHP 7.4.16

### Steps to reproduce (*)

1. Create & configure relevant API credentials under _STORES → Settings → Configuration → SERVICES → Magento Services_
2. Change "SaaS Environment" to one of "Testing" environments
3. Click on "Rename this Environment"
4. Enter a new value in "Environment Name" input field
5. Click "Save Environment Name"
6. Message "Success. Saving and reloading page..." would appear

### Expected result (*)

1. Page is reloaded automatically and changed environment name appears in the "SaaS Environment" list

### Actual result (*)

1. Page is reloaded automatically, but environment name stays the same

I've tried to call Adobe's Web API directly, but got the same (unchanged) environmentName in the response, e.g.:
```
>>> $payload = ['environmentName' => 'Testing STAGE'];
>>> $url = '/merchant-registry/v1/registry/environments/<removed/hidden>';
>>> $result = $servicesClient->request("PATCH", $url, $serializer->serialize($payload));
=> [
     "mageId" => "MAG00XXXXXXX",
     "environmentId" => "<removed/hidden>",
     "organizationId" => "<removed/hidden>",
     "organizationName" => "<removed/hidden>",
     "projectId" => "<removed/hidden>",
     "projectName" => "<removed/hidden>",
     "environmentType" => "Testing",
     "environmentName" => "Testing 2",
     "accountGroup" => "Commerce Entitlement",
     "featureSet" => [
       "Product Recommendations",
     ],
     "subscriptionEndDate" => "2022-07-30",
     "createdAt" => "2020-12-09T14:33:55.631Z",
     "updatedAt" => "2021-04-15T10:12:41.616Z",
   ]
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @denis-zyk,

We have tried to reproduce the issue in Magento 2.4-develop, but we are unable to do the same. We have followed the above-mentioned steps and tried to edit the project name and we are able to edit the project. 

Please have a look at the below screenshot for reference:

**Before Edit**

![image](https://user-images.githubusercontent.com/51681618/134169734-256fac56-7166-486d-ba66-07b5c313488a.png)

**After Edit**

![image](https://user-images.githubusercontent.com/51681618/134169766-efb27c7d-c9a3-441c-9e72-db3d6460a309.png)

Let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @denis-zyk,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards
