### ISSUE TITLE
unable to save new product in magento 2.4

### ISSUE THREAD

**Issue by milltu** [magento/magento2#32750]
### Preconditions (*)

1. Am following the book Magneto 2 Explained pages 36-40 on creating a new product
2. Am in Magento 2.4.0

### Steps to reproduce (*)

1. I am following the exact steps as outlined in this book for how to create a new product. I have checked & double checked and am following the instructions exactly, but it doesn't work. The book was made with Magento 2.2 but the UI looks the same. 
2. When I try to save and close I get this error message. "The stock item was unable to be saved. Please try again."

### Expected result (*)

1. I should be getting a message saying that I saved the product, but I don't. 
2.

### Actual result (*)

1. It won't let me save the product and I get this error message "The stock item was unable to be saved. Please try again."
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- **[ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._**
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by milltu** [comment]
So I can't ask a question? I filled out the form. If by "vanilla Magento instance" you mean Magento Open source, that's what I'm using. This was literally the first thing I tried to do in it. Now I'm somehow locked out of my account, so I can't even try to replicate this again today. So guess I'm just totally SOL.

**Comment by engcom-Alfa** [comment]
Hi @milltu 

I am able to create a product without any issues. Kindly check this procedure to create a new product - https://docs.magento.com/user-guide/catalog/product-create-simple.html

Since now you are already locked from your admin account, you may follow the below screenshot command to create a new admin user

![image](https://user-images.githubusercontent.com/51679138/119626326-b6379f80-be28-11eb-86c3-99c1777430dc.png)

**Comment by engcom-Alfa** [comment]
Since there is no response till ~14 days, closing the issue. Kindly report a newly in case of any issues you face in the latest versions.
