### ISSUE TITLE
Resizable knockout binding does not work on the frontend

### ISSUE THREAD

**Issue by martasiewierska** [magento/magento2#32753]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Add resizable knockout binding for UI Component template (for example minicart) as described in the documentation: https://devdocs.magento.com/guides/v2.4/ui_comp_guide/concepts/knockout-bindings.html#resizable

### Expected result (*)

1. There is a resizable element visible, with controls attached
2. No error in the console

### Actual result (*)

1. There is a console error: 
<img width="870" alt="error" src="https://user-images.githubusercontent.com/7559952/114867576-467bd100-9df5-11eb-8142-f45dbdbd6016.png">
2. if line 124 in resizable.js is commented out resizable is binded without error. However as styles are not included controls that are added are not visible, so component is useless.
<img width="1245" alt="resizab" src="https://user-images.githubusercontent.com/7559952/114868117-dfaae780-9df5-11eb-8c23-e992f9408b4d.png">

It seems to me that this component is used only in the admin panel. I have checked issues and no one reported problems with resizable. Maybe it would be useful to mark this binding as admin only and do not load unnecessary javascript on the frontend side.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
nice catch!

**Comment by magento-engcom-team** [comment]
@mrtuvn Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mrtuvn 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41921` were created

**Issue Available**: @mrtuvn, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @martasiewierska. Thank you for your report. 
The issue has been fixed in magento/magento2#32756 by @martasiewierska in 2.4-develop branch
Related commit(s):
 - [e282209df4aa8b8795cd8af7dc446dd0822e87f1](https://github.com/magento/magento2/commit/e282209df4aa8b8795cd8af7dc446dd0822e87f1)
 - [4ddefaf758d9de53ea547d99e4f235c571021279](https://github.com/magento/magento2/commit/4ddefaf758d9de53ea547d99e4f235c571021279)
 - [9c9b8ce56f3c790fb24af8eb918d3b9304b95157](https://github.com/magento/magento2/commit/9c9b8ce56f3c790fb24af8eb918d3b9304b95157)

The fix will be available with the upcoming 2.4.3 release.
