### ISSUE TITLE
Product Recommendation Filters not working

### ISSUE THREAD

**Issue by pratikvs** [magento/magento2#32761]
### Preconditions 

1. Install Magento2 version 2.4.2
2. nstall Product Recommendations with latest version "^3.0". Follow this link (https://devdocs.magento.com/recommendations/install-configure.html). 

### Steps to reproduce (*)

1. Log in into Magento admin. Go to Marketing > Product Recommendations.
2. Select the scope as Default Store View and click on create a recommendation
3. Add Recommendation Name , Select page type as `Cart` , Select Recommendation type Most viewed, add label , Number of products to be displayed and Placement
4. Create Filter Products . Click on Exclusion. Click on Product. Enable the Filter. Try to Add the SKU under Product inclusions (Available Products). Please refer the screenshot
![Screenshot-from-2021-04-15-20-30-18](https://user-images.githubusercontent.com/79628084/114892921-d12af300-9e2a-11eb-9933-d3cf77991335.png)

### Expected result (*)
1. The system should allow to add the relevant sku in the given textbox.

### Actual result (*)
1. The Create New Recommendation form disappears as soon as you start typing the SKU.
![Screenshot-from-2021-04-15-20-31-13](https://user-images.githubusercontent.com/79628084/114893256-28c95e80-9e2b-11eb-870f-b49906ddd37f.png)

2. Also found error in the console. Please check the screen shot below.
![Screenshot-from-2021-04-15-20-43-43](https://user-images.githubusercontent.com/79628084/114893678-94abc700-9e2b-11eb-8726-3b3f365013a0.png)

**Comment by pratikvs** [comment]
Hello, Any updates on this?

**Comment by Penchal-magento** [comment]
Hi @pratikvs ,
Cross checked with @paras89  on this , in fact issue is not with magento open source , it is only applicable for EE/Commerce, request to raise a support ticket for this .

Thanks

**Comment by Penchal-magento** [comment]
Hi @pratikvs , I request you to raise a ticket as a feature.

**Comment by engcom-Alfa** [comment]
Hi @pratikvs 
In fact issue is not with magento open source , it is only applicable for EE/Commerce, Therefore , I request you to raise a ticket as a feature.
.
Thanks
