### ISSUE TITLE
Invoice Created Via /V1/order/:orderId/invoice Missing Items in Invoice Email

### ISSUE THREAD

**Issue by moranotcsos** [magento/magento2#32760]
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

1. Go to Marketing > _Communications_ > Email Templates.
2. Press Add New Template.
3. Load New Invoice template.
4. Add any Template Name.
5. Press Save Template.
6. Set the template you just created under Stores > Configuration > Invoice > Invoice Email Template.
7. Place order online.
8. Create invoice for the order via /V1/order/:orderId/invoice.

### Expected result (*)

1. The invoice has the items listed.

### Actual result (*)

1. The invoice does not have items listed.

The issue seems to be in vendor/magento/module-sales/Model/Order/Invoice/Sender/EmailSender.php lines 105 - 120.
The $transport is missing order_id and invoice_id.

Alternatively, the Magento/Sales/view/frontend/email/invoice_new.html (and invoice_new_guest.html) should replace:
{{layout area="frontend" handle="sales_email_order_invoice_items" invoice_id=$invoice_id order_id=$order_id}}

with

{{layout area="frontend" handle="sales_email_order_invoice_items" invoice=$invoice order=$order}}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vovsky** [comment]
@magento I am working on this

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
@eduard13 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42087` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment]
Here is how the email looks after creating the invoice via REST API
![image](https://user-images.githubusercontent.com/15868188/116374030-9b1c4480-a816-11eb-8af5-9c82176de9dd.png)

**Comment by gabrieldagama** [comment]
Hi @moranotcsos. Thank you for your report. 
The issue has been fixed in magento/magento2#32902 by @vovsky in 2.4-develop branch
Related commit(s):
 - [c47505d0ac890d62b054cfb7be7b505ab4480f97](https://github.com/magento/magento2/commit/c47505d0ac890d62b054cfb7be7b505ab4480f97)
 - [158331dafa299df3c718cc7343e7cb0a55039791](https://github.com/magento/magento2/commit/158331dafa299df3c718cc7343e7cb0a55039791)

The fix will be available with the upcoming 2.4.3 release.
