### ISSUE TITLE
229 364 Translated Words and Approved 419 only in crowdin

### ISSUE THREAD

**Issue by ksaltik** [magento/magento2#32769]
### Preconditions (*)

1. Yes it is reproducable. If it is not not just 419 words will be approved.
2.

### Steps to reproduce (*)

1. 229 364 Translated Words and Approved 419 only
2. 229 364 Translated Words and Approved 419 only

### Expected result (*)

1. [Screenshots, logs or description]
2. 229 364 Translated Words and Approved 419 only

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @ksaltik,
Can you please provide some more information about the ticket or specify steps to reproduce to verify the issue.
Thank you.

**Comment by engcom-November** [comment]
Hi @ksaltik,

We are closing this ticket , as there has been no update on the same.
Thank you.
