### ISSUE TITLE
Amazon Sales Channel Intelligent Pricing beats your own Price

### ISSUE THREAD

**Issue by joemstar** [magento/magento2#32776]
### Preconditions (*)

1. PHP 7.4 
2. MariaDB version 10.4.18
3. Magento 2.4.2
4. Amazon Sales Channel 4.3.0

### Steps to reproduce (*)

1. Create a new pricing rule in Amazon Sales Channel
2. Under Pricing Rule Actions, set Rule Type to Intelligent repricing rule and Competitor Price Source to "Use Lowest Competitor Price". Minimum Positive Feedback to "All Competitor's Prices and Minimum Feedback Count to 0.
3. Set Price Adjustment to Decrease By, Apply as fixed amount and Adjustment amount 0.01

### Expected result (*)

1. The price should check all other competitors (excluding your own price) and reduce your price by $0.01.

### Actual result (*)

1. The price checks all competitors prices INCLUDING your own and reduces your price by 0.01 every hour.
<img width="216" alt="AmazonSalesChannelBug" src="https://user-images.githubusercontent.com/40399102/115116986-700a3900-9f6a-11eb-92cf-0fbd465177c6.PNG">

**Comment by engcom-November** [comment]
@joemstar , This issue related to bundle extension is not part of this repository. Please contact the extension owner support on the [marketplace](https://marketplace.magento.com/extensions.html) page.
Thank you.
