### ISSUE TITLE
 Broken images

### ISSUE THREAD

**Issue by thor777** [magento/magento2#3278]
Icons appear broken and links on the dashboard not working.

**Comment by dmitrii-fediuk** [comment]
[How to fix the problem of loading css and javascript files](https://mage2.pro/t/259)

**Comment by MomotenkoNatalia** [comment]
@thor777 do you still have this issue?

**Comment by thor777** [comment]
I still have this problem when installing on Windows 10 with xampp .

2016-03-10 11:00 GMT-03:00 nmomotenko notifications@github.com:

**Comment by mazhalai** [comment]
@thor777 have you run the `bin/magento setup:static-content:deploy` command?

**Comment by mazhalai** [comment]
@thor777 closing due to non-responsiveness.
