### ISSUE TITLE
GraphQlAuthorizationException is thrown for guest carts even when the customers are not logged in

### ISSUE THREAD

**Issue by shahriar-vdc** [magento/magento2#32785]
### Summary
When requesting current cart via GraphQl, if cart customer id is 0 and current customer is a guest, but if somehow he has customer id set on the PHP session, then instead of getting the actual cart, it throws exception.
```
The current user cannot perform operations on cart <cart_masked_id>
```

### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. Log in to an account in a Magento installation and then log out
2. Make sure the customer id exists on the PHP session even after logging out _(we had this issue on our website several times but we still do not know why customer id persists on the session in some cases)_
3. Create a quote by adding any product to the cart as a guest customer
4. Make the following GraphQl request:
```mutation ($cart_id: String!, $cart_items: [SimpleProductCartItemInput]!) {
  addSimpleProductsToCart(input: {
    cart_id: $cart_id,
    cart_items: $cart_items
  }) {
    cart {
      ...CartItems
    }
  }
}

fragment CartItems on Cart {
  items {
    id,
    quantity,
    prices {
        price {
            value,
            currency
        }
        row_total_including_tax {
            value,
            currency
        }
        total_item_discount {
            value,
            currency
        }
    }
    product {
      name,
      sku,
      url_key,
      canonical_url,
      categories {
        name,
        breadcrumbs {
          category_name
        },
        path_in_store,
        path,
        url_path
      },
      special_price,
      special_to_date,
      special_from_date,
      image {
        url
       },
       small_image {
        url
       }
    }
  }
}
```
GraphQl Variables:
```
{
  "cart_id": "<cart_masked_id>",
  "cart_items": [
    {
      "data": {
        "sku": "<product_sku>",
        "quantity": 1
      }
    }
  ]
}
```
### Expected result (*)

1. GraphQl response
```
{
  "data": {
    "addSimpleProductsToCart": {
      "cart": {
        "items": [
          //...
        ]
      }
    }
  }
}
```

### Actual result (*)

1. GraphQl response
```{
  "errors": [
    {
      "message": "The current user cannot perform operations on cart \"bR6w488E42fXwOpWOphkGuY62hkBuHZw\" cart_customer_id \"69\" customer_id \"0\" is_logged_in \"\"",
      "extensions": {
        "category": "graphql-authorization"
      },
      "locations": [
        {
          "line": 7,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}
```
2. Magento Exception Log
```
[2021-04-14 13:15:04] report.ERROR: The current user cannot perform operations on cart "bR6w488E42fXwOpWOphkGuY62hkBuHZw" {"exception":"[object] (GraphQL\\Error\\Error(code: 0): The current user cannot perform operations on cart \"bR6w488E42fXwOpWOphkGuY62hkBuHZw\" at /var/www/html/vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\GraphQl\\Exception\\GraphQlAuthorizationException(code: 0): The current user cannot perform operations on cart \"bR6w488E42fXwOpWOphkGuY62hkBuHZw\" at /var/www/html/vendor/magento/module-quote-graph-ql/Model/Cart/GetCartForUser.php:95)"} []
```
3. This exception message was triggered on every page load and every interaction with cart

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shahriar-vdc** [comment]
@magento I am working on it

**Comment by engcom-Golf** [comment]
@shahriar-vdc I have tried to reproduce the issue by following steps. Issue is not reproducible.
**Case 1. As Guest user:**
      1. Create a guest cart
      2. Add Product using addSimpleProductsToCart mutation.

**Case 2: As a Login User**
      1. Create Customer Token using generateCustomerToken mutation.
      2. Create a customer cart. You must specify Customer Token in the headers of the call.
      3. Add Product using addSimpleProductsToCart mutation. You must specify Customer Token in the headers of the call.

Note: **Current user cannot perform operations on cart \"bR6w488E42fXwOpWOphkGuY62hkBuHZw\" type of error occur when you don't pass the Customer Token in the headers of the call.** Or might be your active session logoff due to inactivity after certain time.

You can pass the headers as shown:
![image](https://user-images.githubusercontent.com/51681547/121674569-d9707900-cacf-11eb-9445-cb3b531cd6a9.png)

**Comment by megancooper** [comment]
@shahriar-vdc Where you able to solve this problem? I'm facing something similar

**Comment by shahriar-vdc** [comment]
@megancooper We are still facing the issue as Magento acknowledged it as `non-reproducible`. 

However, I was able to fix it temporarily. Please see my commit: https://github.com/shahriar-vdc/magento2/commit/d79fcc190e1d55a36794af7d2443e241d19311fc

**Comment by huykon** [comment]
@shahriar-vdc I check your commit but I am considering why you check the customer session here? GraphQl can not synchronized with magento php session

**Comment by yevhen-slabonoha** [comment]
I've fixed such an issue by creating the after plugin for Magento\JwtUserToken\Model\Revoker that executes during the customer logout process (**Mutation revokeCustomerToken**). 
And in my case, I did next that fixed all related issues with guests and customers.
**Current version:** Adobe Commerce ver. 2.4.5-p1

`use Magento\Customer\Model\Session as CustomerSession;`

`/**
     * @param \Magento\JwtUserToken\Model\Revoker $subject
     * @return void
     */
    public function afterRevokeFor(\Magento\JwtUserToken\Model\Revoker $subject): void
    {
        try {
            $this->customerSession->logout();
        } catch (\Exception $exception) {
            throwException($exception);
        }
    }`
