### ISSUE TITLE
NewRelic: Missing observer event for reporting Application handled exception

### ISSUE THREAD

**Issue by maximecarey** [magento/magento2#32788]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Any cause of exception that is getting logged into exception.log

### Expected result (*)

1. The exception should appear in the error APM listing

### Actual result (*)

1. These exceptions aren't logged into New Relic

For whatever reason, it seems that the observer Magento\NewRelicReporting\Model\Observer\ReportApplicationHandledExceptionToNewRelic is present in the module, however, there is no events configured in the module events.xml that would allow it to work. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi Werfu,

Have you configured your store to integrate with New Relic. Can you share the snap shot of this configuration from store -> Configurations -> General -> New Relic Reporting.

Thanks

**Comment by engcom-Echo** [comment]
Hi @werfu ,

We are closing this issue as there has been no update on the same.

Thanks
