### ISSUE TITLE
LoginAsCustomer leaves admin backend unaccessible in multidomain-setup

### ISSUE THREAD

**Issue by MarcusSchwarz** [magento/magento2#32796]
### Preconditions (*)

1. Magento 2.4.2
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Create a multi store, multi domain setup, for example

Domain | StoreView
-------|----------
test1.test | de_DE
test2.test | en_US
2. Configure Magento such as the StoreView must not be part of the url
3. Configure the backend such as it is available under one of these domains, eg test2.test/admin
4. Create a customer each for both StoreViews
5. Login to the backend and configure the customers so that both can be accessed with the "LoginAsCustomer" feature
6. From the backend login as customer which is assigned to a StoreView on another domain as the backend (eg test1.test)
7. Close the frontend session
8. Hit Refresh in the browser for the backend

### Expected result (*)

1. the backend reloads and can be used

### Actual result (*)

1. the backend hits - depending on the system configuration - either a redirection loop of death or a plain text site without any style or javascript loaded

### Workaround
The backend can be made accessible again by deleting a cookie named "store", which contains the StoreView of the customer. 

The problem lies in https://github.com/magento/magento2/blob/f25fc0398899c2bc126bc877d4147aeea377af64/app/code/Magento/LoginAsCustomerAdminUi/Controller/Adminhtml/Login/Login.php#L250
```php
        if (!$targetStore->isUseStoreInUrl()) {
            $fromStore = $this->storeManager->getStore();
            $redirectUrl = $this->manageStoreCookie->switch($fromStore, $targetStore, $redirectUrl);
        }
```
The immediate workaround is a patch to change the condition as follows
```php
        if (!$targetStore->isUseStoreInUrl() && $targetStore->getBaseUrl() === $this->_url->getBaseUrl()) {
            $fromStore = $this->storeManager->getStore();
            $redirectUrl = $this->manageStoreCookie->switch($fromStore, $targetStore, $redirectUrl);
        }
```
This workaround does it's thing for our use case, but  there is no warranty it will work in yours

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jordanvector** [comment]
same issue as well

**Comment by engcom-Alfa** [comment]
Hi @MarcusSchwarz ,

I tried to reproduce the issue in 2.4-develop. Not able to reproduce as such. Kindly check the steps I followed below based on your given steps.


https://user-images.githubusercontent.com/51679138/119825070-34bd3b80-bf14-11eb-97e9-04f5514f397c.mp4

**Please give more information in what condition exactly the issue is reproducible.**

**Comment by MarcusSchwarz** [comment]
@engcom-Alfa, as far as I see in your browsers address bar you are on the same domain in the backend as well as in the frontend. This works. You must setup two different domains, like in the example given test1.test and test2.test, or, in other words:
my-fancy-shop.com
my-fancy-shop.de

Backend is on my-fancy-shop.com, the user is on my-fancy-shop.de; This breaks.

**Comment by engcom-Alfa** [comment]
HI @MarcusSchwarz 
As you suggested in the previous comment. I have tested applying different domain as well. I could not reproduce the issue at all.
Below is the screen record on the same.

https://user-images.githubusercontent.com/51679138/119984262-d315d380-bfde-11eb-82c2-a8d149d8eb80.mp4

Please give more information in what condition exactly the issue is reproducible. Also check your any relevant configuration if you are missing or I might include anything as such to reproduce.

**Comment by engcom-Alfa** [comment]
As there is no response last ~14 days, the issue is being closed. If you face issue on this again in the latest magento version, kindly raise a new ticket.
Thanks
