### ISSUE TITLE
Product price change does not update price in quote

### ISSUE THREAD

**Issue by anantab** [magento/magento2#3280]
If a product price is updated after a customer has added it to cart, the customer still sees old price in mini cart in header. The issue also exists in checkout page, if customer directly go to checkout page without going to full basket page.

**Comment by ishakhsuvarov** [comment]
@anantab Thank you for reporting this issue. We have created an internal ticket `MAGETWO-49645` to  fix the problem.

**Comment by shahankitb997** [comment]
Is it solved?

**Comment by ishakhsuvarov** [comment]
Hi @shahankitb997 
Unfortunately it is still not solved. We will update the ticket as soon as we have any progress.
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @anantab, @shahankitb997
Please use the following setting **Stores** > **Configuration** > **Customers** > **Customers Configuration** > **Online Customers Options** > **Customer Data Lifetime** to set the time when customer's local cache is force-cleared. This will force reload the prices as well. 
Thank you.

**Comment by timbaker1991** [comment]
Using Magento 2.2.x there is no option for "Customer Data Lifetime", only "Online Minutes Interval". Is this something that can only be set in 2.3.x?

**Comment by magento2dev** [comment]
I still get the same issue on Magento 2.2.3.

Thanks !

**Comment by ghost** [comment]
@magento2dev, we were not able to reproduce this issue on Magento 2.2.5.
![1](https://user-images.githubusercontent.com/40756187/45490439-bfaf7500-b76f-11e8-8a03-315a51a075f8.gif)

**Comment by sonbui00** [comment]
I think the issue still happend

**Comment by giordhano** [comment]
this happens with configurable products. 

![image](https://user-images.githubusercontent.com/823663/91494462-7bdfa880-e87e-11ea-92da-8af312ce5e2b.png)

Magento 2.3.5-p1

**Comment by bricht** [comment]
Why is this issue closed?

**Comment by pfortin-expertime** [comment]
It's happening with special price too
