### ISSUE TITLE
No option to search for specific order number.

### ISSUE THREAD

**Issue by pdeboo** [magento/magento2#32806]
### Preconditions (*)

1. Magento ver. 2.3.3-p1
2. https://master-7rqtwti-5xc2bzxuexzme.us-3.magentosite.cloud/sales/order/history/?limit=50&p=3

### Steps to reproduce (*)

1. I am looking on the orders page and I do not see anywhere that allows me to search for a specific order number
![Magento -  screen shot - no place to search specific order](https://user-images.githubusercontent.com/82110275/115572321-6728a880-a285-11eb-952c-9430d746cb86.PNG)

2. 
3. 

### Expected result (*)

1.  There should be a search option for a specific order # and when you search on the order # it should find it.  There is just the general search, no Search Order option.

### Actual result (*)

1. See the attached document.  I want to find a specific order.
[Magento order # search.docx](https://github.com/magento/magento2/files/6351778/Magento.order.search.docx)

**Comment by krishprakash** [comment]
Hi @pdeboo. Magento not provide search option in my order specific page as this by default

**Comment by krishprakash** [comment]
Hi @pdeboo. We can consider this as feature request not an issue as by default magento not provide such functionality.
But Yes this is goot to be add search box in my orders to search only order related data
So I can approve this as feature request

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42028` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vyablonskiy** [comment]
Hi @pdeboo, do you tried to use Filter on My Orders page?

**Comment by pdeboo** [comment]
No – it doesn’t work the way I need it to.

**Comment by magento-engcom-team** [comment]
Hi @pdeboo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-42028` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @pdeboo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-42028` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
