### ISSUE TITLE
Change load order of custom page layout

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32807]
### Summary (*)

I created a new page layout, but I noticed that it does not get loaded last and it gets overridden from other layouts.

Is there a way to change the load order so that my custom page layout gets loaded last?

### Examples (*)

I have this simple layout where I create a new block which just shows the text `foobar123`. I move it after the **header.container**.

### THEME\layout\catalog_product_view.xml

    <?xml version="1.0"?>
    
    <page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
        <body>

		    <block class="Magento\Framework\View\Element\Template"
				   name="test_foobar"
				   template="Hausfux_Base::test.phtml" />

            <move element="test_foobar" destination="page.wrapper" after="header.container"/>
        </body>
    </page>

### THEME\Company_Base\templates\test.phtml

    foobar123

Now I create a new page layout and try to move that foobar123 block, after the footer only for this page layout.

### THEME\Magento_Theme\layouts.xml

    <?xml version="1.0" encoding="UTF-8"?>
    <page_layouts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/PageLayout/etc/layouts.xsd">
        <layout id="hf-grouped-product-big-1col">
            <label translate="true">Hf Grouped Product (Big) -- 1 Col</label>
        </layout>
    </page_layouts>

### THEME\Magento_Theme\page_layout\hf-grouped-product-big-1col.xml

    <?xml version="1.0"?>
    <layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
        <update handle="1column"/>

        <move element="test_foobar" destination="page.wrapper" after="footer-container"/>
    </layout>

Now I select my new custom page layout **Hf Grouped Product (Big) -- 1 Col** on a product and load it, then the text "foobar123" is showing, but still after the header, because my custom page layout is getting loaded before **catalog_product_view.xml**.

How can I make my custom page layout always get loaded last?

### Proposed solution

-
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Here is the order in which layout XML is merged default in magento. Order from top to bottom:
Module base files loaded
Module area files loaded
Sorted according to their module priority (array index of module’s position in app/etc/config.php)
If their priorities are equal, they are sorted according to their alphabetical priority.
Theme files (from furthest ancestor to current theme)
Layout files loaded
Override files replaced

Current i'm not clearly what you requirements and expect to do or visual
"Is there a way to change the load order so that my custom page layout gets loaded last?" Why this have to load last

As i remember magento update handle from request and also update page layout after that. It's collect all block for specific handle and merge all into one big XML file. After that magento rearrange, replace, override following declare

**Comment by Eddcapone** [comment]
@mrtuvn "Why this have to load last"
Because I need my page layout to override all other layouts.

**Comment by engcom-Echo** [comment]
Hi @Eddcapone ,

Can you please refer the link to understanding layout instructions

**Comment by engcom-Echo** [comment]
Hi @Eddcapone ,

We are closing the issue as there has been no-update on the same. Hopefully the link provided has helped you.

Thanks
