### ISSUE TITLE
Attention, Something went wrong

### ISSUE THREAD

**Issue by Elmira9292** [magento/magento2#32800]
After I logged every single time, I got this Alert, Attention , Something went wrong ,A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later. in my admin magento 2.3.6
Also this issue happened to me after I've been tried to change the logo of header from content>configuration.
![M A](https://user-images.githubusercontent.com/77969506/115465783-faa99d00-a1e3-11eb-8158-858f2c420507.png)
. Also I've tried for php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
php bin/magento cache:clean
that it doesn't answer.
It would greatly appreciate if anyone help me

**Comment by engcom-Oscar** [comment]
Hi @Elmira9292 ! 
Can you please add to ticket what errors you got in your system or exception logs and in the browser console,  when this Alert popup? Also, may you please specify - on which page/action this alert appear?

**Comment by krishprakash** [comment]
Hi @Elmira9292. Feel free to reopen the ticket once you update all the necessary details for this issue 
Thanks
