### ISSUE TITLE
Advanced Pricing does not work for multiple websites

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#32809]
### Preconditions (*)

**1.** Magento `2.4.2` with a `sample data`
**2.** There are 2 websites:
<img width="1445" alt="01" src="https://user-images.githubusercontent.com/13585327/115626558-5704dd80-a306-11eb-8030-2e93098263c9.png">
**3.** Product **Joust Duffle Bag** (SKU = `24-MB01`) is available to both websites:
<img width="1661" alt="02" src="https://user-images.githubusercontent.com/13585327/115626743-96332e80-a306-11eb-8c60-c8e916be083f.png">

### Steps to reproduce (*)

1. Open for edit product **Joust Duffle Bag** (SKU = `24-MB01`)
2. Try to select the "**Second**" website in the "Website" dropdown

### Expected result (*)

1. Admin user sees a three options in the "Website" dropdown:
-  "All Websites"
- Main Website
- Second

### Actual result (*)

**1.** Admin user sees a single option "All Websites" in the "Website" dropdown
<img width="1671" alt="03" src="https://user-images.githubusercontent.com/13585327/115627078-15286700-a307-11eb-8479-30c4cce70fa5.png">

### Issue description
Product attribute `tier_price` always have `is_global` = `1` in [\Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\AdvancedPricing::getWebsites()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/AdvancedPricing.php#L318) even it set to "Website" scope

<img width="1370" alt="04" src="https://user-images.githubusercontent.com/13585327/115627871-61c07200-a308-11eb-9e18-cef9b8d3e7fe.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41998` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Leland** [comment]
@magento give me 2.4-develop instance

**Comment by atwixfirster** [comment]
Configuration issue. To get the expected result the `Catalog Price Scope` option should be set to `Website`:

<img width="1325" alt="06" src="https://user-images.githubusercontent.com/13585327/115865257-c2eb6100-a440-11eb-80ad-4996a55cd196.png">

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
