### ISSUE TITLE
Generated Associated Product Name and SKU have issue

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#32824]
### Preconditions (*)
1. Magento 2.3.3
2. PHP 7.2

### Steps to reproduce (*)
1. Create Configurable Product
2. Add name Like "Test A&B"
3. Create Configuration and Add color Attributue than select any color 
4. Generate Products

### Expected result (*)
No need to show extra "amp;" text in product name and sku
1. ![image](https://user-images.githubusercontent.com/50168477/115852663-f41a6000-a445-11eb-837f-cd38df7c00a5.png)

### Actual result (*)
1. 
![image](https://user-images.githubusercontent.com/50168477/115852802-190ed300-a446-11eb-8487-efbdd35d831b.png)

please check on this, and reply if any suggestion or code is available

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @niku0911,
This issue has been verified on Magento 2.4 Instance. Extra "amp" text is not required on Configuration sections. I have found extra "amp" text only on product name not on product sku.
 
![New Product _ Pr](https://user-images.githubusercontent.com/24711761/115861123-08635a80-a450-11eb-8123-e5611de61fe2.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42032` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by niku0911** [comment]
hi @ajijshekh123 ,

thanks to check this issue, can we fixed this?, i found this issue in Magento 2.3.3

**Comment by ajijshekh123** [comment]
Yes @niku0911 , You can fixed it.

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by niku0911** [comment]
hi @SilinMykola  Thanks for solution

**Comment by magento-engcom-team** [comment]
Hi @niku0911, @SilinMykola. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-42032` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
