### ISSUE TITLE
Product price cannot be saved per website

### ISSUE THREAD

**Issue by vseager** [magento/magento2#32825]
This is a copy of issue #31978. The issue still exists on Magento 2.4.1

1. Magento 2.4.1
2. The installation has multiple websites and store views

### Steps to reproduce (*)

1. Price Scope is set to "per website"
2. Create a product with price = 10
3. Switch to another StoreView than default
4. Remove "Use default" for price, set price = 20
5. Save the product

### Expected result (*)

1. Price for website 1 should be 20
2. "Use default" should be unchecked (please only look at the database when solving this issue - there is another issue with displaying the value in the admin backend - it just does not show the correct value, even if the database is correct)
3. The catalog_product_entity_decimal should look like this:

| value_id | attribute_id | store_id | entity_id | value |
| ---- | ---- | ---- | ---- | ---- |
| 471122 | 75 | 0 | 38045 | 10.000000 |
| 471122 | 75 | 1 | 38045 | 10.000000 |

### Actual result (*)

1. Price for the seelcted storeView 1 is still 10
2. "Use default" is checked
3. the catalog_product_entity_decimal actually looks like this:

| value_id | attribute_id | store_id | entity_id | value |
| ---- | ---- | ---- | ---- | ---- |
| 471122 | 75 | 0 | 38045 | 10.000000
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @vseager  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
**Actual Result:** :heavy_check_mark: 
![Screenshot from 2021-04-23 15-17-44](https://user-images.githubusercontent.com/60198413/115869997-5162e100-a447-11eb-9e71-e27de584ee8d.png)
![Screenshot from 2021-04-23 15-17-32](https://user-images.githubusercontent.com/60198413/115870015-56279500-a447-11eb-8677-7d587926e820.png)
![Screenshot from 2021-04-23 15-18-06](https://user-images.githubusercontent.com/60198413/115870028-5a53b280-a447-11eb-8d3e-9b1049c0be0c.png)
Can you please recheck and confirm if it reproducing for you on the clear vanilla installation with latest 2.4 Magento code?

**Comment by vseager** [comment]
Sorry I realise now in the original issue it said this was fixed in 2.4-develop.
