### ISSUE TITLE
mini cart issue

### ISSUE THREAD

**Issue by hannanhaider** [magento/magento2#32823]

**Comment by engcom-Oscar** [comment]
Hi @hannanhaider ! Do you have any errors in browser console and in logs? Can you please add them to your ticket?

**Comment by onlinebizsoft** [comment]
We also have a similar issue, this is happening randomly and we can't reproduce easily
1. Add a product to cart successfully
2. The mini cart show no item

![image](https://user-images.githubusercontent.com/22501570/116499847-57d5da80-a8d7-11eb-9b45-fc954a0372ea.png)

**Comment by mrtuvn** [comment]
@onlinebizsoft This issue maybe from custom theme template cart not sync with new code

**Comment by onlinebizsoft** [comment]
@mrtuvn but it is happening randomly

**Comment by mrtuvn** [comment]
If you have issue i highly recommended you create new seperate github issue with clear steps describe your problem

**Comment by krishprakash** [comment]
Hi @hannanhaider. Thank you for your report.
Looks like it's from your custom theme issue 
@onlinebizsoft  Kindly create another issue if you confirm that issue reproduce on latest 2.4-develop instance
