### ISSUE TITLE
Magento Admin not working after changing base url , but changing base url working fine , but admin url not working 

### ISSUE THREAD

**Issue by Git-Rajkumar** [magento/magento2#3282]
i setup magento 2 in locally in My Pc(fedora-23)

I Changed base url for magento 2 using magento admin (Store-→ Configuration-→ change Default View to Web view  → then Click Web Option → Then Choose Base Url Option , then Change Base Url)

Example: http://localhost/magento2/  → MYIPAddr/magento2/

I only changed base url not in admin url, after chaged this url,  magento2 working on this url, but not working magento admin url. 

if i run admin url , browser says,  "The Page is not redirecting properly".    Before Changing baseurl , magento site and admin working fine. 

what is the problem , how to solve this, thanks in advance

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2439

**Comment by cspruiell** [comment]
@Git-Rajkumar - I am unable to reproduce this scenario. When you change the base URL, it changes both the admin and frontend URLs. If I change the URL to my IP address I still get correct behavior under the new address. If I try to use the old address it resolves to the newly configured URL. Please retry this under the latest develop branch.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
