### ISSUE TITLE
Cannot create product "URL key for specified store already exists." - pure magento, no migration, no scripts, no categories

### ISSUE THREAD

**Issue by chelevich** [magento/magento2#32832]
### Preconditions (*)

1. Magento 2.4.0 (Enterprise Edition) 
2. PHP 7.4

### Steps to reproduce (*)

1. Create two websites with a store for each website (website IDs: 1 and 2, store IDs: 1 and 2)
2. Create a product with URL Key "test" (product ID: 1)
3. Assign it to **both websites**
4. Observe two URL Rewrites created for both stores
- store 1, "test -> catalog/product/view/id/1",
- store 2, "test -> catalog/product/view/id/1"
5. Un-assign the product **from website 1**, change URL Key to "test2" with "Create redirect" checked, hit Save
6. Observe three URL Rewrites: 
- store 1, "test -> catalog/product/view/id/1",
- store 2, "test -> test2",
- store 2, "test2 -> catalog/product/view/id/1"
7. Attempt to create new product assigned to **website 1** with URL Key "test"

### Expected result (*)

1. In step 6 there should only two URL Rewrites remain for store 2 as the product is unassigned from website 1
2. Should allow to save new product in step 7 with the initial URL Key "test" (new product ID: 2)
3. Three URL Rewrites should exist after save:
- store 1, "test -> catalog/product/view/id/2",
- store 2, "test -> test2",
- store 2, "test2 -> catalog/product/view/id/1"

### Actual result (*)

1. Error is thrown in step 7 "URL key for specified store already exists."
2. The error message points to the conflicting URL Rewrite with **store 2** although the product is assigned only to **website 1**

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
Hi @chelevich 
I tried to reproduce the issue on 2.4-develop instance. It's working fine. At step 6 there is only 2 url rewrite exists related to the website the product is assigned. 
So I am able to create new product on other website with previous product url key.

**Comment by shikhamis11** [comment]
Can you confirm you are able to reproduce the issue on latest 2.4-develop instance? 
Also let us know if require additional steps to reproduce the issue if any

**Comment by chelevich** [comment]
@shikhamis11 sorry, I cannot reproduce the issue in 2.4-develop.
Probably it's fixed by https://github.com/magento/magento2/pull/31106
I need to find a way to upgrade my 2.4.0

**Comment by shikhamis11** [comment]
Thanks for the update @chelevich
It seems that changes are not released yet maybe It will be there in 2.4.3.
I am closing this one as it is already fixed.
