### ISSUE TITLE
Show error on setup:di:compile if  you attempt to override a class which does not exist

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32839]
### Description (*)

I was experiencing a bug where my class override attempt with precedence was not working.
It was entirely my fault and a bug caused by me.

I accidentially used Magento\Subscriber instead of Magento\Newsletter in the following di.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <preference for="Magento\Subscriber\Model\Subscriber"    <--- I accidentially used Magento\Subscriber instead of Magento\Newsletter
                type="Company\Newsletter2Go\Model\Subscriber" />
</config>
```

However, `setup:di:compile` ran through without any errors. It would be nice if there would be an error showing, if the class could not get found, since I needed many hours to finally find this bug.

### Expected behavior (*)

Error message should show

### Benefits

- Easier to find bugs

### Additional information

Reproduction example:
https://github.com/magento/magento2/issues/32838

**Comment by ihor-sviziev** [comment]
@Eddcapone I think it's better to do some Static test for such a case. What do you think?

**Comment by Eddcapone** [comment]
@ihor-sviziev In my oppinion it would be much better if the setup:di:compile command would get extended to show an error or a warning in this case. A static test would not have helped either, since I would probably had the same bug in the static test (accidentially using Magento\Subscriber instead of Magento\Newsletter)

**Comment by ihor-sviziev** [comment]
Hi @Eddcapone,
It would not be good to show such warnings during setup:di:compile because there are valid cases when you have "optional" dependency to 3rd party extension. If module there - some model should be re-declared. Not sure if it's quite a popular use case, but anyway - that might not be the best behavior to see new warnings for a valid case.

Wring the static test will provide an ability to detect such cases in general
