### ISSUE TITLE
setup:di:compile issue

### ISSUE THREAD

**Issue by webrod** [magento/magento2#32833]
### Preconditions (*)

1. magento 2.4.2
2. developer OR production mode
3. Load on the frontend (because the issue is linked to a race condition between frontend requests and CLI)

### Steps to reproduce (*)

1. bin/magento setup:static-content:deploy -f
2. bin/magento setup:di:compile
.

### Expected result (*)

1. Generated code and dependency injection configuration successfully.
2.

### Actual result (*)

1. The directory "/xxxxx/htdocs/generated/code/Magento" cannot be deleted Warning!rmdir(/xxxxx/generated/code/Magento): Directory not empty
2. OR could be any other directory within generated/doce

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

I'm fighting with this issue as many people.
Many proposed solution is to change permission, but actually I noticed something and I'm guessing now what the issue is.
Actually IF you run multiple time  "bin/magento setup:di:compile", you will most likely get a different folder name being the error, but more interresting is after X try then... it works!! compilation starts and finish well!
my guess:
1) the process make a rm first to delete files in a folder
2) then it deletes the parent folder (or a parent-parent-...-folder)
3) by the time the files  have been deleted, it might be another one is created!! (there are activities on the front end so I guess some missing files might be automatically re-created?)
4) if you are lucky enough one of the try will succeed because of no (or minor) front end activities (or cron or backend actually)

any idea? (note it also happens with some other commands like "bin/magento module:enable  xxx", same type of errors messages, but it works after X try. so not specific to di:compile"

Look at the full tries below, it worked at the 8th very consecutive try!:
```
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento): Directory not empty The directory "/my-path/htdocs/generated/code/Klarna" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Klarna): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento/Catalog" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Catalog): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Option" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Option): Directory not empty The "/my-path/htdocs/generated/code/Magento/Quote/Model/Quote/PaymentFactory.php.27191" file can't be deleted. Warning!unlink(/my-path/htdocs/generated/code/Magento/Quote/Model/Quote/PaymentFactory.php.27191): No such file or directory
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The "/my-path/htdocs/generated/code/Vertex/Data/CustomerInterfaceFactory.php.27283" file can't be deleted. Warning!unlink(/my-path/htdocs/generated/code/Vertex/Data/CustomerInterfaceFactory.php.27283): No such file or directory The directory "/my-path/htdocs/generated/code/Vertex/Tax" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Vertex/Tax): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Variable/Model" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Variable/Model): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Widget/Model/Widget" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Widget/Model/Widget): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Directory" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Directory): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento/SalesRule/Model/Rule" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/SalesRule/Model/Rule): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento/Catalog/Model" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Catalog/Model): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Theme/Model" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Theme/Model): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Magento" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
The directory "/my-path/htdocs/generated/code/Vertex" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Vertex): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Catalog/Model" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Catalog/Model): Directory not empty The directory "/my-path/htdocs/generated/code/Magento/Customer/Model" cannot be deleted Warning!rmdir(/my-path/htdocs/generated/code/Magento/Customer/Model): Directory not empty
my-user@my-ip:~/apps/magento/htdocs$ bin/magento setup:di:compile
Compilation was started.
Plugin list generation... 9/9 [============================] 100% 30 secs 538.0 MiB
Generated code and dependency injection configuration successfully.

```

**Comment by ihor-sviziev** [comment]
Hi @webrod,
It really looks like a race condition issue between the CLI and some requests on the frontend - the CLI tries to remove all files and a directory, while the frontend at the same time creating new files there.
In order to prevent it - you can enable maintenance mode before running `setup:static-content:deploy`, and disable it once you're ready. This will also improve the experience for your customers - they will understand that there is some maintenance in progress, and will not get some 500 errors.

For the production environment, it's strongly recommended to deploy static content on the build server. More info https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/

Hope I helped you.

**Comment by panwarsingh** [comment]
I am having the same issue, can we have any fixes for this.

**Comment by ihor-sviziev** [comment]
@panwarsingh see my comment https://github.com/magento/magento2/issues/32833#issuecomment-826552227
I hope it will help you to resolve the issue.

**Comment by panwarsingh** [comment]
> @panwarsingh see my comment [#32833 (comment)](https://github.com/magento/magento2/issues/32833#issuecomment-826552227)
> I hope it will help you to resolve the issue.

No its not helping in our case

**Comment by ihor-sviziev** [comment]
@panwarsingh, could you provide more tails, what isn't helping you, what issue you have, and how to reproduce it?

**Comment by panwarsingh** [comment]
@ihor-sviziev we were trying to put Magento 2.4.2 website to production mode but when we used di-compile command it gave the error that directory not empty, you can have the screenshot below.

![issue](https://user-images.githubusercontent.com/84184281/118277273-40593d00-b4e6-11eb-923b-3ce3339fcf8d.png)

**Comment by ihor-sviziev** [comment]
@panwarsingh, as I said - it's strongly recommended to run the setup:di:compile and static content deploy on a separate build server (where you won't have any generated folder). From your screenshot, I see that you ran it on the "live" website, where some requests might happen, or some cron job might be running, or a message queue might be running. 
All of these things potentially might cause such issues.

**Comment by medigeek** [comment]
On a separate build server or using capistrano or deployer or similar tools. It will deploy and link everything once finished.
Still, it seems to be a weird race condition. We have enabled maintenance mode, cleaned cache, waited for several (10-15) seconds) and we still faced the same issue. Perhaps we need to wait a bit longer.

**Comment by ihor-sviziev** [comment]
@medigeek, did you kill cron jobs and queue runners? They also might cause such issues.

**Comment by medigeek** [comment]
@ihor-sviziev that's a very good point! will add it in the to-do list next time and try it out definitely. Thanks!

**Comment by medigeek** [comment]
@ihor-sviziev I've been thinking about this, shouldn't we have a check in place if var/.maintenance is present before executing the cron.php ?

**Comment by ihor-sviziev** [comment]
@medigeek, we do check if the maintenance flag file doesn't exist before running cron jobs. But Magento isn't checking it by default.

**Comment by medigeek** [comment]
I'm checking the bootstrap:

https://github.com/magento/magento2/blob/3c5ff49c11eec2d4510b25571acf0d30b804cdf1/lib/internal/Magento/Framework/App/Bootstrap.php#L38

https://github.com/magento/magento2/blob/3c5ff49c11eec2d4510b25571acf0d30b804cdf1/lib/internal/Magento/Framework/App/Bootstrap.php#L279

From what I see, getIsExpected() checks the $_SERVER parameters:
https://github.com/magento/magento2/blob/3c5ff49c11eec2d4510b25571acf0d30b804cdf1/lib/internal/Magento/Framework/App/Bootstrap.php#L338

In command line / cron we don't have server parameters.

And if by default it's set to false, then cron will run regardless of the maintenance mode, is that correct?

If so, how do we enforce cron:run to check the maintenance flag? At least temporarily with a command line ENV parameter? Or permanently if the user wants their cron:run not to run when maintenance flag is enabled? (Obviously without fiddling with the crontab every time 😀  )

**Comment by ihor-sviziev** [comment]
@medigeek, we're checking in the crontab if file not exists - then execute cron

**Comment by medigeek** [comment]
@ihor-sviziev  which files/lines are you referring to? 🤔 
The default cron:install doesn't add any maintenance flag checks in the crontab AFAICS.

Maintenance isn't referred at least directly in the cron:run file https://github.com/magento/magento2/blob/3c5ff49c11eec2d4510b25571acf0d30b804cdf1/app/code/Magento/Cron/Console/Command/CronCommand.php 

Sorry I'm asking, just interested to see how it all connects. Cheers for the answers so far! 😊

**Comment by ihor-sviziev** [comment]
@medigeek in the crontab we just writing something like this:
```
* * * * *       www-data  test ! -e /path/to/magento2/var/.maintenance.flag && /usr/bin/php /path/to/magento2/bin/magento cron:run | grep -v "Ran jobs by schedule"
```

**Comment by medigeek** [comment]
Thanks for the clarification, I thought there was an internal check within the cron:run task. 😁 
Shouldn't that be handled by the default cron:install command? 
Cheers!

**Comment by engcom-Delta** [comment]
Hi @webrod ,

This issue is not reproducible in Magento 2.4. Develop. Hence it is closed.
Please find the attached screenshot.
![di_compile](https://user-images.githubusercontent.com/51681379/135461933-f0b71a71-f202-4bb5-97e7-dc34dd3d3159.JPG)
Thanks

**Comment by webrod** [comment]
I added Step 3, as explain in the next comments, this is a race condition with frontend request so to reproduce the issue load is required.
" _the CLI tries to remove all files and a directory, while the frontend at the same time creating new files there._"

**Comment by medigeek** [comment]
@engcom-Delta this is still happening. Enable maintenance, install cron and try run the setup:di:compile 10-15 times to reproduce it.

 It doesn't happen *every* time, it happens *sometimes*, when cron runs seconds before running the setup:di:compile

This happens *sometimes* during builds and software upgrades and we want to avoid breaking the compilation and re-running docker and/or other CI/CD pipelines with the compilation step. 

This can dub Magento as unstable or unfit for production servers with high load websites. 

To fix this properly, bin/magento cron:install command should install a check for the maintenance file in the cron task, as shown in an earlier comment:
https://github.com/magento/magento2/issues/32833#issuecomment-883910773
