### ISSUE TITLE
Investigate upgrade to the latest tinymce4

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32849]
### Overview

For the tinymce4 library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration. 

Note: take a look at PageBuilder

**Comment by mrtuvn** [comment]
we updated to 4.9.10 
9months ago
