### ISSUE TITLE
Investigate upgrade to the latest script.aculo.us

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32848]
### Overview

For the script.aculo.us library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

## Conclusion
Deleting a library is not possible due to its use in the following libraries:

lib / web / prototype / prototype.js
lib / web / prototype / validation.js
lib / web / prototype / window.js
lib / web / extjs / ext-tree.js

**Comment by anzin** [comment]
@magento I am working on this
