### ISSUE TITLE
Adjustment refund : no tax calculated in credit memo

### ISSUE THREAD

**Issue by samy-m-dev** [magento/magento2#3284]
The issue exists in Magento 1 and still exists in Magento 2, when we use the Adjustment Refund or Fee taxes are not calculated.

I see in the documentation : "In the Adjustment Refund field, enter a value to be added to the total amount refunded as an additional refund that does not apply to any particular part of the order (shipping, items, or tax). The amount entered cannot raise the total refund higher than the paid amount."

So I understand that these adjustments dont apply to shipping, items or tax. But in the case we want to partially refund an items, we dont have choice to use the Adjustments fields and then the taxes are not recalculated.

I think a better way should be to allow to refund one or more products with a custom price (with checkbox as on admin new order form) and if the products are taxable then the refund will correctly recalculate the correct taxes.

**Comment by choukalos** [comment]
This is a feature enhancement - created MAGETWO-50517 to encapsulate and shared with appropriate PM.

**Comment by jakobfdev** [comment]
Anything happend so far? It would at least be helpful, if the method names in the CreditMemoInterface would suggest, if adjustments are included or not like with ...InclTax suffix. This is a little incoherent...

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Adjustment-refund-no-tax-calculated-in-credit-memo/idi-p/46086).
