### ISSUE TITLE
Investigate upgrade to the latest MutationObserver.js

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32856]
### Overview

For the MutationObserver.js library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

**Comment by ihor-sviziev** [comment]
As I said in https://github.com/magento/magento2/issues/32851#issuecomment-832745748 , we can safely remove the MutationObserver, as all supported browsers already have native support of it
