### ISSUE TITLE
Investigate upgrade to the latest es6-collections.js

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32851]
### Overview

For the es6-collections.js library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

**Comment by ihor-sviziev** [comment]
**List of supported browsers:**
Microsoft Edge, latest–1
Firefox latest, latest–1 (any operating system)
Chrome latest, latest–1 (any operating system)
Safari latest, latest–1 (Mac OS only)
Safari Mobile for iPad 2, iPad Mini, iPad with Retina Display (iOS 12 or later), for desktop storefront
Safari Mobile for iPhone 6 or later; iOS 12 or later, for mobile storefront
Chrome for mobile latest–1 (Android 4 or later) for mobile storefront 
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers

The es6-collections are providing the following polyfills:
- **WeakMap** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakmap
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L8-L22
- **Map** - ✔ supported https://caniuse.com/mdn-javascript_builtins_map
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L24-L46
- **Set** - ✔ supported https://caniuse.com/mdn-javascript_builtins_set
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L48-L67
- **WeakSet** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakset
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L69-L80


**It looks like we can safely remove the es6-collections**

Also, I see ec6-collections are used as a dependency for the `MutationObserver` polyfill library.
✔ The MutationObserver also natively supported by all supported browsers https://caniuse.com/mutationobserver

**Comment by sivaschenko** [comment]
@ihor-sviziev thanks for the investigation and detailed results, the issue to eliminate the library was created: https://github.com/magento/magento2/issues/33206
