### ISSUE TITLE
Investigate upgrade to the latest FormData.js

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32852]
We need to continue investigation of the outdated Magento Core build-in 3rd party JS dependencies identified in scope of previous investigation <https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=COREENG&title=Investigate<ins>Magento</ins>Core<ins>build-in</ins>dependencies<ins>on</ins>3rd-party+libraries>

Investigate only Core code

For FormData.js library we need to identify the following additional details:
1. If this library is used on Admin UI or Storefront Luma or both
1. What exact functionality is using this particular library
1. What is a preliminary estimate for upgrade to the actual version (T shirt size would be great) including testing effort
1. Is it possible to migrate without introducing BIC into Luma
1. Level of impact of updating dependency in terms of BIC
1. Do we need to migrate to another library since this one looks abandoned

**Comment by anzin** [comment]
@magento I am working on this
