### ISSUE TITLE
Update phpseclib/mcrypt_compat to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32865]
Update phpseclib/mcrypt_compat composer dependency to the latest major version 2.x.x

What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)

t

**Comment by drpayyne** [comment]
@magento I am working on this
