### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by shinethazhava** [magento/magento2#3286]
![import](https://cloud.githubusercontent.com/assets/6826291/12811653/e4524366-cb53-11e5-810c-2a9c55b6717c.png)

Maximum error count has been reached or system error is occurred!
Following Error(s) has been occurred during importing process:
Only first 100 errors are displayed here. Download full report
General system exception happened
Additional data: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`safety`.`catalog_product_link_attribute_int`, CONSTRAINT `CAT_PRD_LNK_ATTR_INT_LNK_ID_CAT_PRD_LNK_LNK_ID` FOREIGN KEY (`link_id`) REFERENCES `catalog_product_link` (`link_id`) ON DELETE CASCA), query was: INSERT INTO `catalog_product_link` (`link_id`,`product_id`,`linked_product_id`,`link_type_id`) VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `link_id` = VALUES(`link_id`)

**Comment by shuaiZend** [comment]
a foreign key constraint fails

**Comment by shinethazhava** [comment]
After a  detailed investigation i found that when i import a product with a category after that i move the category into a another sub category then after perform the same product import getting these error

**Comment by sandeepBWC** [comment]
Hey,

I'm also getting same, have you found some solution ?

**Comment by yaronish** [comment]
Fixed

**Comment by sandeepBWC** [comment]
Thanks yaronish!!!!!

**Comment by andkirby** [comment]
Found this issue on v2.1.6.
