### ISSUE TITLE
Update webonyx/graphql-php dependency

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32863]
Depends on: magento/magento-coding-standard#206

Update webonyx/graphql-php dependency in https://github.com/magento/magento-coding-standard repository to the latest version (later update magento with new coding standard version and new webonyx/graphql-php)

### What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)

t

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
Created a PR (https://github.com/magento/magento-coding-standard/pull/206) in the Magento Coding Standard repository. I shall update this repo once a new version from there is released.

**Comment by drpayyne** [comment]
Hi @sivaschenko, could you please add a `has dependency` label to this ticket?
