### ISSUE TITLE
Update php-amqplib/php-amqplib to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32866]
Update php-amqplib/php-amqplib from 2.10.1 to 3.0.0

### What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)

**Comment by nuzil** [comment]
First review results:

* PhpAmqpLib\Wire\AMQPTable; - safe
* PhpAmqpLib\Exception\AMQPInvalidArgumentException - safe
* PhpAmqpLib\Connection\AbstractConnection - need to be checked
* PhpAmqpLib\Channel\AMQPChannel - need to be checked, BIC found
* PhpAmqpLib\Message\AMQPMessage - need to be checked, BIC found
* PhpAmqpLib\Connection\AMQPSSLConnection - safe
* PhpAmqpLib\Connection\AMQPStreamConnection - need to be checked, deprecated param found
* PhpAmqpLib\Exception\AMQPLogicException - safe

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by anzin** [comment]
@magento I am working on this
