### ISSUE TITLE
Update phpseclib/phpseclib to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32864]
Update phpseclib/phpseclib from 2.0.31 to 3.0.8

### What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)
 
t

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story
