### ISSUE TITLE
Update monolog/monolog to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32868]
Update monolog/monolog from 1.26.0 to 2.2.0

What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)

**Comment by andrewbess** [comment]
Hello @sivaschenko 
I have added the PR with the fixes of the codebase according to your request. FYI, my PR updates `monolog/monolog` to version 2.3.1.
Please check it after all tests are passed successfully.

**Comment by andrewbess** [comment]
Status "On hold" by reason: waiting for the new release of the MFTF
