### ISSUE TITLE
Update colinmollenhour/cache-backend-redis to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32871]
Update colinmollenhour/cache-backend-redis composer dependency to the latest minor version

 

What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as story

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by bbakalov** [comment]
I see that PR was merged to the `magento:platform-health` but not any stable branches. 
I think, this PR need to merge to any stable and last version of Magento2, because it's impossible to upgrade module `colinmollenhour/cache-backend-redis` to the last stable version **1.14.2** 

All the time composer gives an error

> Problem 1
>     - magento/product-community-edition 2.4.3 requires colinmollenhour/cache-backend-redis 1.11.0 -> satisfiable by colinmollenhour/cache-backend-redis[1.11.0] but these conflict with your requirements or minimum-stability.
>     - magento/product-community-edition 2.4.3 requires colinmollenhour/cache-backend-redis 1.11.0 -> satisfiable by colinmollenhour/cache-backend-redis[1.11.0] but these conflict with your requirements or minimum-stability.
>     - magento/product-community-edition 2.4.3 requires colinmollenhour/cache-backend-redis 1.11.0 -> satisfiable by colinmollenhour/cache-backend-redis[1.11.0] but these conflict with your requirements or minimum-stability.
>     - Installation request for magento/product-community-edition 2.4.3 -> satisfiable by magento/product-community-edition[2.4.3].
> 

So, any reasons why this PR haven't merged to some stable version?
