### ISSUE TITLE
Mark interfaces as API on Adobe Stock Integration

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32875]
Description provided here: https://github.com/magento/adobe-stock-integration/issues/1858

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by shikhamis11** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Hi @mmansoor-magento ,
It has been decided that this is expected behavior of Magento and no need to change the current tax calculation logic.
Thank you.

**Comment by engcom-November** [comment]
Hi @mmansoor-magento 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-853 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-853&type=commits
Based on Jira, target version is 2.4.4
Thank you
