### ISSUE TITLE
Validate backward compatibility for Web URLs

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32873]
See the issue in semver repository: https://github.com/magento/magento-semver/issues/60

**Comment by andrewbess** [comment]
@magento I am working on it

**Comment by engcom-Hotel** [comment]
Hello @mmansoor-magento,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Also after looking into the below mentioned issue, we are unable to get this:

https://github.com/magento/magento-semver/issues/60

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mmansoor-magento ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
