### ISSUE TITLE
Update colinmollenhour/credis to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32870]
Update colinmollenhour/credis from 1.11.1 to 1.12.1

### What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)

**Comment by texboy** [comment]
@magento I am working on this
