### ISSUE TITLE
Paypal Payflow Advanced returnUrl response cookies SameSite=Lax

### ISSUE THREAD

**Issue by mikew-westlund** [magento/magento2#32879]
### Preconditions (*)

1. Magento 2.3.6-p1
2. Apache2
3. PHP 7.3
4. Chrome 90.0.4430.85 or greater
5. Paypal Payments Advanced
6. URL method for Cancel URL and Return URL: GET

### Steps to reproduce (*)

1. add product to cart
2. checkout
3. proceed through checkout
4. select Paypal Payments Advanced payment method
5. submit payment

### Expected result (*)

1. redirected to /checkout/onepage/success/
2. order is recorded and notification emails sent

### Actual result (*)

1. page stays on /checkout/#payment
2. order is recorded and notification emails sent
2. chrome developer tools returns the message in regard to the returnUrl cookies PHPSESSID and X-Magento-Vary "This Set-Cookie was blocked because it had the "SameSite=Lax" attribute but came from a cross-site response which was not the response to a top-level navigation"
![image](https://user-images.githubusercontent.com/65622809/116150313-d13bb600-a6a8-11eb-9e06-b5b8bf53fc80.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mikew-westlund** [comment]
As far as I can tell this problem began with Chrome 90.0.4430.72

**Comment by mikew-westlund** [comment]
I believe the solution for this would be to set those cookies to SameSite=None and secure

**Comment by engcom-Alfa** [comment]
Hi @mikew-westlund 
I have tried re producing in the 4.2-develop version and the issue is not reproducible as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/51679138/120329680-b55fab80-c309-11eb-9b72-8d3400dba99e.png)
Kindly provide more reproducible steps and provide the actual resulted screenshot / screen record. Kindly upgrade to the latest version possibly and provide me more updates about reproducing it.

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may [go through the user guide](https://docs.magento.com/user-guide/).

**Comment by numan201** [comment]
I'm having the exact same issue on 2.4.2-p1 on the latest Chrome. Customers are left very confused after paying with their credit cards, and nothing happening afterwards. @mikew-westlund  did you ever figure this out?
