### ISSUE TITLE
Minicart no update with custom add to cart

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3287]
Hi!

I created my custom module for add a product to my cart, if I use my controller with this form :

`<form action="http://*********/test/cart/add/uenc/*******/product/471/" method="post" id="product_addtocart_form" novalidate="novalidate">`

My product is in my cart, but minicart is not update, and change page not resolve this problem.

But, if I change my form link with magento controller like this :

`<form action="http://*********/checkout/cart/add/uenc/*******/product/471/" method="post" id="product_addtocart_form" novalidate="novalidate">`

It's work fine

In my controller, I have just change this

`namespace Magento\Checkout\Controller\Cart`
to this
`namespace Test\Test\Controller\Cart;`

**Comment by ishakhsuvarov** [comment]
@quienti Thank you for your question.
Please try creating a `sections.xml` file in the `etc` folder of your module and configure it according to your needs, for example:

``` xml
<action name="test/cart/add">
    <section name="cart"/>
</action>
```

This would reload customer's minicart on each `POST` request to your controller. Basically, `action` node indicates controller path and `section` node defines which client-side content should be updated.
Caches have to be flushed for this change to apply.
You may use `Magento/Checkout/etc/frontend/sections.xml` for a reference.

**Comment by quienti** [comment]
Whoaa!
Awesome ! Thanks you !

**Comment by pankaj-pareek** [comment]
@ishakhsuvarov - sections.xml will only work for Post request ? As in GET request it is not working. any solution for this.

**Comment by ishakhsuvarov** [comment]
@pankaj-pareek It is designed only to be used on a state-changing requests, which `GET` isn't.

**Comment by orlangur** [comment]
@pankaj-pareek `POST` and `PUT` to be clear. Any code changing system state in `GET` request violates CQRS and needs to be reworked.

**Comment by pankaj-pareek** [comment]
Thanks for clarification. I will make changes in the flow to add products programmatically using post request.

**Comment by WED2B** [comment]
Magetno 2.2.2 Xml Session doesn't work e.g
`<action name="test/cart/add">
    <section name="cart"/>
</action>`
. It works only with required e.g
`<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        setTimeout(function(){ customerData.reload(['cart']); }, 1000);
    });
</script>`

is there a bug that it doesn't reload with sections.xml?

**Comment by lano-vargas** [comment]
Magetno 2.2.2 Xml Session doesn't work e.g
`<action name="test/cart/add"> <section name="cart"/> </action>`
. It works only with required e.g
`<script> require([ 'Magento_Customer/js/customer-data' ], function (customerData) { setTimeout(function(){ customerData.reload(['cart']); }, 1000); }); </script>`

is there a bug that it doesn't reload with sections.xml?

**Comment by orlangur** [comment]
@lano-vargas section should be enough if you access this action with post/put/delete http method.

**Comment by lano-vargas** [comment]
@orlangur Thank you.

I am injecting the `\Magento\Checkout\Model\Cart`  then:

        .....
        try {
 
            $_product = $this->productRepository->getById($productId);

            $this->_cart->addProduct($_product, $params);

            $this->_cart->save();

            $this->_messageManager->addSuccessMessage(__('You added '.$_product->getName().' to your shopping cart.'));

            // Perhaps here reload cart customer data E.G $this->_cart->reload('cart')

        }catch (\Exception $e){
            $this->_messageManager->addError($e->getMessage());
        }
       .....


Magento doesn't happen to have a method to reload customer data? E.G 
`$this->_cart->reload('cart')`  similar to requireJS
