### ISSUE TITLE
Login on second attempt after one unsuccessful try redirects customer to 404 page

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#32885]
### Preconditions (*)

1. Reproduced on Magento 2.4.1, Magento 2.4.2
2. Config "customer/startup/redirect_dashboard" is set to "No"

### Steps to reproduce (*)

1. Navigate to login page, without referrer parameter in URL (i.e. "/customer/account/login/")
2. Enter invalid login data and try to login
3. After page reload, URL will now contain a referrer parameter, which is the URL to "/customer/account/loginPost/" as base64 encoded string
4. Enter correct login data and login
5. You will be redirected to "/customer/account/loginPost", which will display a 404 error page, because this controller is not available for GET requests

### Expected result (*)

1. Unsuccessful login redirects back to login page without adding a referrer

### Actual result (*)

1. Unsuccessful login adds invalid URL as referrer parameter

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42075` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment]
This issue should have P2 priority in my opinion

**Comment by mfickers** [comment]
@mrtuvn I've created a PR: https://github.com/magento/magento2/pull/32891

**Comment by Viper9x** [comment]
Hi @mfickers, I've dug deep into this issue today. I confirm that this issue occurs on magento 2.4, 2.4.1, 2.4.2, 2.4.2-1. 

Magento version < 2.4 doesn't have this issue and the function getLoginUrlParams() in [Magento\Customer\Model\Url.php:113](https://github.com/magento/magento2/blob/2.4/app/code/Magento/Customer/Model/Url.php#L113) on magento 2.4 does not change compared to [magento 2.3](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Customer/Model/Url.php#L113) so I think we shouldn't add more conditions here to check if the request is GET or not as you did.

Let's debug:
Login in with invalid login data on the first time, `$this->customerSession->getNoReferer()` in [Magento\Customer\Model\Url.php:113](https://github.com/magento/magento2/blob/2.4/app/code/Magento/Customer/Model/Url.php#L113) return different result between magento 2.3 and magento 2.4

In magento 2.3, `$this->customerSession->getNoReferer()` return _**1**_ while it return _**null**_ in magento 2.4. So this is the problem, we should digging into this. I can't find where set NoReferer value so I'm stuck here. Hopefully, we can fix by this way.
