### ISSUE TITLE
opFileXXXXXXXX is not defined

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#3289]
1. Start to create order 
2. Add to order product with custom option - input type is file
3. Try to update file. Click to button "Change"
   https://drive.google.com/file/d/0Bw3Wyc4ElUWNTnozZmtOcmhjSkE/

AR: we have error in console like "opFile875762837 is not defined"
ER: allow change file.

**Comment by NadiyaS** [comment]
Hi @OleksiyOleksiyovych ,
What version did you use? 
On latest Magento version custom option is changed correct.

**Comment by OleksiyOleksiyovych** [comment]
Thank you for your replay.
I am using 2.0.2 version (commit 71dab8d8564c52aca5f11ad101ab5a6df5785df8)

**Comment by Mulderua** [comment]
Hi @OleksiyOleksiyovych, we cannot reproduce on 2.0.2 version (commit 71dab8d) too. Try to disable all thirt party extension and do scenario again. 
Notice that current magento version is 2.0.7.

**Comment by NadiyaS** [comment]
The issue is closed since there is no response from reporter more than 2 weeks.
