### ISSUE TITLE
Catalog Search index exception: Could not ping search engine: No alive nodes found in your cluster

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#32894]
### Preconditions (*)

1. Magento 2.4.2
2. Elastic Search 7.12.0

### Steps to reproduce (*)

1. Configuration the elastic from admin-end
```
curl -X GET '127.0.0.1:11243'
{
  "name" : "xxx.xxx.xxx",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Uc-2BrK7RjmZPUjOU_kVQQ",
  "version" : {
    "number" : "7.12.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "78722783c38caa25a70982b5b042074cde5d3b3a",
    "build_date" : "2021-03-18T06:17:15.410153305Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
```
curl -i http://127.0.0.1:11243/_cluster/health
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 389
{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":2,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":2,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
```
2. Configure Catalog Search as elasticsearch7  host `127.0.0.1` and port `11243`, Test the connection successfully
3. Reindex by CLI

### Expected result (*)

1. Catalog Search could be reindexed successfully 
2.

### Actual result (*)

1. Catalog Search index exception: Could not ping search engine: No alive nodes found in your cluster

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Hi. Can you reproduce issue in 2.4-develop branch ? Just curiosity why do you not use 9200 port instead

**Comment by engcom-Golf** [comment]
@tuyennn I tried to reproduce the same issue with given below configurations:
![image](https://user-images.githubusercontent.com/51681547/119498264-0f4cf800-bd83-11eb-8ae6-d1cf89e8be6c.png)

I can successfully reindex via CLI. 
**Note:** Reported error occur when elasticsearch is not Active.
