### ISSUE TITLE
issue with loading new product configurations to configurable products

### ISSUE THREAD

**Issue by Wiesjames** [magento/magento2#32900]
### Preconditions (*)

1. version 2.4.1
2.

### Steps to reproduce (*)

1. open an already created configurable product
2. Click edit configurations
3. select new configurations
4. add them to product
5. click save and continue or save and close

### Expected result (*)

1. I expect when i add new products to the configurable product and press save that it updates the product listing with all the new colours and sizes etc of the products i want to add

### Actual result (*)

1. I updated a configurable product adding new colours and sizes and than then gets added to the product and i can see all the products there with the new variations
2. When i Click Save and exit or save and continue then I get the below error message (screenshot).
3. if i click back on the browser then it takes me back to the product and if i was trying to load 20 products variations then it might only create 1 to 3 of them.
4. if i'm on the error screen and i click refresh and then go back into the product then you can see the same 1 to 3 products with  new sku's that shows i've duplicated the product adding the -1 or -2 after the original sku
![Capture](https://user-images.githubusercontent.com/83393924/116517361-c0688b80-a8c6-11eb-91fc-c915a573c5f6.JPG)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by Wiesjames** [comment]
not sure what i need to do to get this moving forward. i'm not a dev so no idea re what i'm missing here

**Comment by Wiesjames** [comment]
@magento give me 2.4-develop instance

**Comment by Wiesjames** [comment]
@magento-admin sorry guys i've no idea how i'm supposed to get attention for me query. i'm not a dev so not sure what i'm not adding to get this in front of someone

**Comment by engcom-Oscar** [comment]
Hi @Wiesjames   ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?

**Comment by krishprakash** [comment]
Hi @Wiesjames, Feel free to reopen the issue once you provide additional details to reproduces this issue
Thanks
