### ISSUE TITLE
Composer file not found when a custom vendor-dir is set

### ISSUE THREAD

**Issue by jalogut** [magento/magento2#3290]
Magento\Framework\Composer\ComposerJsonFinder::findComposerJson() expects the root composer.json file to always be one directory higher than vendor folder. However this is not true when a custom vendor-dir is specified. 

Either this method is adjusted to work with any vendor-dir location or you should inform that a custom vendor-dir is not supported.

Regards

**Comment by eddielau** [comment]
@jalogut Are you using Composer to deploy Magento? Currently custom vendor directory support is only available in develop branch of the git repo. It will be included in Composer deployed Magento in future versions.

**Comment by jalogut** [comment]
@eddielau Yes, I am using composer to deploy Magento but I am using latest official 2.0.2. I will git it a try with develop branch and let you know.

**Comment by andimov** [comment]
@jalogut 
Do you have any update for this issue?

**Comment by jalogut** [comment]
Hello @andimov ,
I just tested it on version 2.1.0 and now there is a different issue:

``` bash
Composer file not found#0 /Volumes/workspace/krieger-test/magento/vendor/magento/framework/Composer/ComposerFactory.php(48): Magento\Framework\Composer\ComposerJsonFinder->findComposerJson()
```

That comes from the following function on Magento\Framework\App\Filesystem\DirectoryList\ComposerJsonFinder:

``` php
/**
     * Find absolute path to root Composer json file
     *
     * @return string
     * @throws \Exception
     */
    public function findComposerJson()
    {
        $composerJson = $this->directoryList->getPath(DirectoryList::ROOT) . '/composer.json';
        $composerJson = realpath($composerJson);
        if ($composerJson === false) {
            throw new \Exception('Composer file not found');
        }
        return $composerJson;
    }
```

As you can see on the first line, the function is now looking for the composer file on the Magento root. This is not right if we set a different magento-root-dir on the composer-installer config:

``` json
 "extra": {
    "magento-root-dir": "magento/",
  },
```

For now I just use a work around that symlinks the expected `composer` files on the Magento root:

``` json
"scripts": {
    "post-install-cmd": [
          "cd magento && ln -sf ../composer.* ."
     ]
    "post-update-cmd": [
          "cd magento && ln -sf ../composer.* ."
     ]
}
```

Should I open a different issue for that?

Thanks

**Comment by veloraven** [comment]
@jalogut thank you for update.
Yes, please create another issue for another problem.
Please, format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If original issue is not actual anymore please close this one.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by sanaeefar-saeed** [comment]
i faced this problem when i used dockergento 
solution:
$ dockergento down  // stop all containers
$dockergento start //run all containers 
the problem has been solved.
