### ISSUE TITLE
Youtube Video not playing after installing porto theme

### ISSUE THREAD

**Issue by RahulRajputana-Dev** [magento/magento2#32908]
### Youtube Video not playing after installing porto theme

Hi
I just intstalled a porto theme on magento 2.4 without sample data. Before installing porto theme youtube video and product view was working fine but just after installing porto theme both youtube video and product view not responding. Does someone know how to fix it?
### Preconditions (*)

1. Magento 2.4.0
2. Product View

### Steps to reproduce (*)

1. Install Magento 2.4.0 open source without Sample Data on ubuntu server using CLI
2. Install Porto theme
3. Add product with images and youtube video URL after entering youtube API
4. Go to customer view and check video is not playing and just showing a thumbnail of it.

### Expected result (*)

1. Video should play

### Actual result (*)

1. Video not playing and only showing a thumbnail of it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by eduard13** [comment]
Hi @RahulRajputana-Dev, since the issue occurred only after installing the theme, please report the issue to theme's vendor.
Thank you.
