### ISSUE TITLE
Checkout failure when using PayPal and Braintree on Magento 2.4.2

### ISSUE THREAD

**Issue by lagunacellar** [magento/magento2#32907]
We have been having issues processing checkout when using PayPal through Braintree and credit card through Braintree.  At first, we thought it was just our site.  We have been disabling all 3rd party modules to isolate any potential cause.  That process is ongoing.  But we encountered the same issue when purchasing an extension on Magento Marketplace.  The exactly same error is thrown by the reference site marketplace.magento.com

### Preconditions (*)

1. Magento 2.4.2
2. PayPal_Braintree module by Gene Commerce

### Steps to reproduce (*)

1.  Add product to cart, proceed to checkout
2. Select either PayPal or Credit Card as payment method

### Expected result (*)

1. Expected to proceed to the step where PayPal pop-up or credit card form is displayed
2.

### Actual result (*)

1. 
<img width="800" alt="Screen Shot 2021-04-29 at 9 37 36 AM" src="https://user-images.githubusercontent.com/64744041/116593599-1c86dc00-a8d6-11eb-8099-652f4cddfa84.png">
<img width="788" alt="Screen Shot 2021-04-29 at 9 37 13 AM" src="https://user-images.githubusercontent.com/64744041/116593603-1db80900-a8d6-11eb-8e42-84285ba0f649.png">

2.  Instead, an error message is displayed "Something went wrong with your request.  Please try again later."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @lagunacellar 
Need more information because we tried on Magento ver. dev-2.4-develop, we are able to place an order

**Comment by engcom-Lima** [comment]
Hi @lagunacellar,

Waited since 2 week about the updates, Hence closing this ticket as of now. If you have any issue or query then you can raise the new ticket or reopen.

Thanks for understanding!
