### ISSUE TITLE
CMS Page allows route names to be saved

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#32913]
### Preconditions
1. Magento 2.4.1

### Steps to reproduce
1. Create a new CMS page
2. Set the title to "Checkout"
3. Save the CMS page. Pages is saved, URL Key is set to "checkout"
4. Try to save the page another time, notice "The value specified in the URL Key field would generate a URL that already exists." is shown.

### Expected result
1. On the first save when no URL key is given, validation if the generated URL key is the same as a route name should still be checked. 
2. Notice "The value specified in the URL Key field would generate a URL that already exists." is shown. 

### Actual result 
1. CMS page is saved with a URL key that is also used as a route name. 
2. When trying to access checkout via the frontend user will get a CMS page instead.

![image](https://user-images.githubusercontent.com/1058480/116676861-cd10e080-a9a7-11eb-8f65-627e4527e13c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@engcom-Golf Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Golf Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Golf Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42419` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#33043 by @SilinMykola in 2.4-develop branch
Related commit(s):
 - [f41f4d48891a01e07d948152ffdf793f822169e8](https://github.com/magento/magento2/commit/f41f4d48891a01e07d948152ffdf793f822169e8)
 - [485ef768e6d76f44ba89a32aaf492f9fcee9f6ee](https://github.com/magento/magento2/commit/485ef768e6d76f44ba89a32aaf492f9fcee9f6ee)

The fix will be available with the upcoming 2.4.3 release.
