### ISSUE TITLE
Incorrect dispalying of out of stock bundle product

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#32918]
### Preconditions (*)

1. Magento 2.4.2 with sample data installed
2. Stores → Configuration → Catalog → Inventory → Stock Options → Display Out of Stock Products → set the option to YES
3. Simple product, in stock, but with limited qty. Example: 
![image](https://user-images.githubusercontent.com/24728606/116715565-8212bf80-a9df-11eb-91fb-631d2e296381.png)

### Steps to reproduce (*)

1. Create bundle product with simple product from the preconditions
2. For this bundle, make the product as a required option, forbid to modify qty by user, and set default qty > current stock qty for simple product 
![image](https://user-images.githubusercontent.com/24728606/116715977-e766b080-a9df-11eb-9ada-d656792afb04.png)

3. Run reindex 
4. Go to the storefront and open any category, where created bundle product is assigned to

### Expected result (*)

1. Bundle product should be invisible in the catalog, according to the config option "Display Out of Stock Products"

### Actual result (*)

1. Bundle product is visible in the catalog, but marked as "out of stock", while option "Display Out of Stock Products" is set to NO
![image](https://user-images.githubusercontent.com/24728606/116716879-f1d57a00-a9e0-11eb-8ca2-1b1ba11a4ee8.png)

### Additional information
As I can see, stock index for bundle product does not take into account default qty of simple product, specified within the bundle

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Penchal-magento** [comment]
@avgust1111 avgust1111 : 
1. It is not an issue when product is out of stock  and option "Display Out of Stock Products" is set to YES-Product will be visible in front end with out of stock option.
2. It is not an issue when product is out of stock  and option "Display Out of Stock Products" is set to NO-Product will be invisible in front end.

This is the expected behavior ,kindly let me know if you are expecting different behavior.
Kindly log a new issue if you are expecting different behavior with detailed steps.

**Comment by avgust1111** [comment]
Hello, @Penchal-magento
Thank you for checking 
I'd like to ask: did you check behavior for bundle option product qty, as I mentioned in detailed steps?
Or did you just change stock status for simple products? Unfortunately, it's not clear in your comment, what exactly have you checked

**Comment by Penchal-magento** [comment]
Hi @avgust1111 : Yes , i have verified for bundle option product qty.
Thanks
