### ISSUE TITLE
Checkout edit address creates new address - magento2

### ISSUE THREAD

**Issue by sanganb** [magento/magento2#32912]
### Preconditions (*)

1. Magento 2.3
2.luma version 

### Steps to reproduce (*)

1. Add product to cart and move to checkout then if existing shipping address is available  click edit  button.

![image](https://user-images.githubusercontent.com/73931635/116671657-d194c380-a9be-11eb-8299-dbdecf26fe82.png)

2.Edit the existing shipping address where pop up will open then, update the address which creates new address
![image](https://user-images.githubusercontent.com/73931635/116671741-ea04de00-a9be-11eb-8e13-0544ec576d9d.png)

### Expected result (*)

1. When we edit existing new address its should update address rather than create new address 
![image](https://user-images.githubusercontent.com/73931635/116660454-ac00bd80-a9b0-11eb-9d89-8e6952134a52.png)

2.after clicking ship here button It will update existing address.
![image](https://user-images.githubusercontent.com/73931635/116671840-0c96f700-a9bf-11eb-8081-28f548617c31.png)

### Actual result (*)

1. Add product to cart and move to checkout then if existing shipping address is available  click edit  button.

![image](https://user-images.githubusercontent.com/73931635/116671657-d194c380-a9be-11eb-8299-dbdecf26fe82.png)

2.Edit the existing shipping address where pop up will open then, update the address which creates new address
![image](https://user-images.githubusercontent.com/73931635/116671741-ea04de00-a9be-11eb-8e13-0544ec576d9d.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @sanganb. Thank you for your report.
As provided steps not able reproduce the issue on magento 2.4-develop instance 
Kindly confirm the issue reproducible on latest magento instance

**Comment by krishprakash** [comment]
Hi @sanganb. Feel free to reopen the issue one confirm the issue reproduce on latest 2.4-develop instance
Thanks
