### ISSUE TITLE
The «Add Products Manually» («Select Associated Product») backend configurable products scenario wrongly allows to add only a single simple product at once, not multiple

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3292]
https://mage2.pro/t/599

**Comment by palamar** [comment]
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
