### ISSUE TITLE
Catalog Category Indexing on DISABLED Store View takes a long time. Magento 2.4.2. Related issue -> #25199

### ISSUE THREAD

**Issue by neddy236** [magento/magento2#32925]
### Description

This is somewhat related to https://github.com/magento/magento2/issues/25199 .
While magento tries to reindex indexer -> 'catalog_category_product' it runs a query for 'catalog_category_product_index_store{{store_id}}_tmp . 

This works fine for the first 2 store views but for the third one **which is also disabled**, it can take up to 10-15 minutes to complete.  The first 2 take like 30 seconds max.  (Store3 is the disabled one https://prnt.sc/12cya22)

While this is happening, no transactions related to the product can be completed in the database, everything results in 504 timeout. (Api or change in the backend).

### Preconditions (*)
Magento 2.4.2
PHP 7.4
MariaDB 10.4.17
22k Products (as of writing this issue)
1 website with 3 store view. Last store view is disabled.

### Steps to reproduce (*)

bin/magento indexer:reindex catalog_category_product 

or

let the cron run reindex_all_invalid job. (If its invalidated it will reindex it and the problem will show it self)

### Expected result (*)
Not sure if the indexing needed to be done in the first place for a disabled store view,
but admins should never notice a hung like this in the backend while updating product.

### Actual result (*)
Products could not be created/updated in the backend nor through the API (rest/v1/products/}

---

- [S1]Severity:  Affects critical data or functionality and forces users to employ a workaround.

**Comment by neddy236** [comment]
Please close this. We investigated a little bit more and we found out that the **"optimizer_search_depth"** on our mariaDB config was the issue here. After changing it to the value of 4 it got down to 27 seconds more or less.

**Comment by MackieeE** [comment]
> Please close this. We investigated a little bit more and we found out that the **"optimizer_search_depth"** on our mariaDB config was the issue here. After changing it to the value of 4 it got down to 27 seconds more or less.

If you don't mind me asking (I confess I've not researched this value) but what was the value before? Was this higher/lower than 4 once set?
