### ISSUE TITLE
Gray out Not working if one of option of configurable Product is out of stock

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#32924]
**Preconditions**
Magento 2.4.2
Browser Chrome/Firefox

**Issue: Out of stock configurable product with custom attribute configuration Size and Fit (custom configuration with visual swatch options) is not greyed out in the front end product page.**

**Steps to reproduce:**
1. Back End Side (admin) : Create a configurable product (Using existing, it might not reproduce).
    Use **Size** Attribute configuration. Also create a new attribute with the name **Fit** having visual 
    swatch option (_keep default white color to the swatches; Swatches options with under18 and 18+_).
2. Save the product configuration. 
3. Go to Admin: Store > Configuration >> Catalog > Inventory ; Set the option Display Out of Stock Products - Yes (This has been in the below screen shot)
![image](https://user-images.githubusercontent.com/63009790/116781891-81436180-aaa3-11eb-82b5-5179b93739fb.png)
4. Open the product in the front end, it loads properly (make sure cache is cleared and re-indexed in case if it is not showing in the front end.) It opens appropriately. (as shown in the screen shot below)
![image](https://user-images.githubusercontent.com/51679138/118285444-10fafe00-b4ef-11eb-9020-9c5382d83dae.png)
5. Back end - Open any one product SKU and mark it as out of stock as shown in below screen shot.
![image](https://user-images.githubusercontent.com/51679138/118285660-53243f80-b4ef-11eb-8cea-2b761d51c444.png)
6. Again come back to the front product page and reload the product.
7. try to select the out of stock option.

**Expected:** If we select the size that is out of stock and then immediately relevant **Fit** option should be greyed out.
**Actual:** Still the Fit option is keeping enabled and able to select
![image](https://user-images.githubusercontent.com/51679138/118286169-ce85f100-b4ef-11eb-9718-48c64c6d867a.png)

**Comment by ia-gaurav** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by pavel77718** [comment]
@magento I am working on this

**Comment by engcom-Delta** [comment]
Hi @ia-gaurav ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Back End Side (admin) : Create a configurable product (Using existing, it might not reproduce).
Use Size Attribute configuration. Also create a new attribute with the name Fit having visual
swatch option (keep default white color to the swatches; Swatches options with under18 and 18+).
2. Save the product configuration.
3. Go to Admin: Store > Configuration >> Catalog > Inventory ; Set the option Display Out of Stock Products - Yes 
4. Open the product in the front end, it loads properly (make sure cache is cleared and re-indexed in case if it is not showing in the front end.) It opens appropriately. (as shown in the screen shot below)
<img width="959" alt="config test - 1" src="https://github.com/user-attachments/assets/ec4d409c-b577-44f0-af11-d0faacb7880c">
5. Back end - Open any one product SKU and mark it as out of stock as shown in below screen shot.
<img width="598" alt="mark one SKU as OOS" src="https://github.com/user-attachments/assets/49615264-5271-4ef5-90ee-93dc77df7d03">
6. Again come back to the front product page and reload the product.
7. try to select the out of stock option.
<img width="949" alt="OOS product" src="https://github.com/user-attachments/assets/16d0763d-75ea-4edb-a3dc-3ced52dad5e2">
 OOS option is grey out as expected.

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @ia-gaurav ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
