### ISSUE TITLE
Cant change atribute set from default

### ISSUE THREAD

**Issue by SteveReda** [magento/magento2#32929]
### Preconditions (*)
Magento ver. 2.2.7

### Steps to reproduce (*)
1. go to product page
2. change atribute set to other

### Expected result (*)
1. expecting it would save to the new atribute set

### Actual result (*)
1. Getting an error that i need to change an atribute of that atribute set wich i cant reach because i cant change the atribute set. (loophole)
2. 
![image](https://user-images.githubusercontent.com/83576402/116854904-b90fed80-abf8-11eb-93d7-dc8c82f04448.png)

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
I think. Sorry first time issue

**Comment by engcom-Alfa** [comment]
Hi @SteveReda 
I have tested the issue in the Magento ver. 2.4.*, No issue reproduced as per the description.
Below is the working screen shot.
![image](https://user-images.githubusercontent.com/51679138/118480219-953bc400-b72f-11eb-8352-b2d25002953d.png)
In fact, tried to reproduce with different product types like Configurable, Bundle, Grouped as such. It is not reproducible.
Kindly upgrade to the latest and try it. Please re-open or log a new bug in case with detailed description about the bug if you find the issue again.
