### ISSUE TITLE
Static CMS image urls when using a different (sub)domain for custom admin url

### ISSUE THREAD

**Issue by elouwerse** [magento/magento2#32930]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Admin panel » Stores » Configuration » General » Content Management » Use Static URLs for Media Content in WYSIWYG: No
2. Admin panel » Stores » Configuration » Advanced » Admin » Admin Base URL » Use Custom Admin URL: Yes
3. Set admin to a different (sub)domain than the actual store url.
4. Add/edit a CMS page, static block or product page
5. Add image

### Expected result (*)

1. Media tag with relative image url
2. `<img src="{{media url="wysiwyg/test-image.png"}}" alt="">`

### Actual result (*)

1. Media tag with static Magento admin url instead of store url
2. `<img src="{{media url="https://dev.magentotest.local/wysiwyg/test-image.png"}}" alt="">`

This issue is caused by inconsistend use of `$this->_storeManager->getStore()` in /vendor/magento/module-cms/Helper/Wysiwyg/Images.php
Line 214: `$this->_storeManager->getStore()`
Line 299: `$this->_storeManager->getStore($this->_storeId)`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@Den4ik Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42160` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
