### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by jacksonsinliss** [magento/magento2#32935]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Den4ik** [comment]
I'm closing this issue due to empty description

**Comment by jacksonsinliss** [comment]
Denis,

sorry about sending this by mistake before I could get any further than the title. The problem appears to be with the application and the owner is working on their website now.

Roger and out from the Isle of Wight
