### ISSUE TITLE
CMS blocks and pages content edited with Page Builder adding extra html DIVS causing style issues #29320

### ISSUE THREAD

**Issue by manish-sp** [magento/magento2#32941]
### Preconditions (*)

1. Magento 2 EE 2.4.1

### Steps to reproduce (*)

1.Edit CMS block or page with Page Builder
2. Save CMS block or page.

### Expected result (*)

1. Content should be saved without extra divs around CMS content
2.

### Actual result (*)

1. Content is saving successfully but some extra divs are automatically adding around content as you are seeing below.
2. `<div data-content-type="row" data-appearance="contained" data-element="main"><div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-background-type="image" data-video-loop="true" data-video-play-only-visible="true" data-video-lazy-load="true" data-video-fallback-src="" data-element="inner" style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px 0px 10px; padding: 10px;"><div data-content-type="html" data-appearance="default" data-element="main" style="border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;" data-decoded="true">`
3. This leads to the CSS Styling issue. Should be an option to add or not add above divs.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by manish-sp** [comment]
@magento-engcom-team Same issue exists here 
https://github.com/magento/magento2/issues/29320
this issue has been closed without fix.

**Comment by mrtuvn** [comment]
@manish-sp re-opened issue. So i will close this
