### ISSUE TITLE
Installing magento on database with sql_require_primary_key

### ISSUE THREAD

**Issue by fxlip** [magento/magento2#32940]
The installation fails when creating the schema, showing the `SQLSTATE [HY000] error: General error: 3750 Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. `

### Preconditions
    Magento 2.4
    Debian 10
    PHP 7.3.27
    MySQL 8 on DigitalOcean Cluster

### Steps to reproduce
`php -f bin/magento setup:install --base-url=http://site.com --use-secure=0 --db-host=db.ondigitalocean.com:25060 --db-name=magento --db-user=admin --db-password=xxxxx --admin-firstname=user --admin-lastname=admin --admin-email=admin@site.com --admin-user=admin --admin-password=xxxxx --language=pt_BR --currency=BRL --timezone=America/Sao_Paulo --use-rewrites=1 --use-secure=1 --base-url-secure=https://site.com --use-secure-admin=1;`

### Expected result
```
Starting Magento installation:
File permissions check...
[Progress: 1 / 842]
Required extensions check...
[Progress: 2 / 842]
Enabling Maintenance Mode...
[Progress: 3 / 842]
Installing deployment configuration...
[Progress: 4 / 842]
Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema...
[Progress: 5 / 842]
```

### Actual result
```
Starting Magento installation:
File permissions check...
[Progress: 1 / 842]
Required extensions check...
[Progress: 2 / 842]
Enabling Maintenance Mode...
[Progress: 3 / 842]
Installing deployment configuration...
[Progress: 4 / 842]
Installing database schema:
Schema creation/updates:

In Mysql.php line 91:

SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
```

### Proposed solution
Check the resources received during [createTable](https://github.com/magento/magento2/blob/2.4/lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/MySQL/DbSchemaWriter.php) and include primary keys if there are none. 

---
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Lima** [comment]
Hi @fel1p,

Unfortunately, I can't reproduce the issue. 

Can you disable this flag first - set sql_require_primary_key = off? and
try to install again.

Let me know if you will get any issue again.
