### ISSUE TITLE
Itemprop offers cache issue upsell

### ISSUE THREAD

**Issue by JoostWan** [magento/magento2#32948]
### Preconditions (*)

1. Magento 2.3.6
2. Luma theme

### Steps to reproduce (*)
1. Create two products
2. Link both products to each other via upsell
3. Open product 1
4. Open product 2
5. View source code 

### Expected result (*)
1. Product 2 has correct itemprop offer

### Actual result (*)
1. Product 2 has no itemprop offer (main product on that page)
2. Product 1 in the upsell section has de itemprop offer.

<img width="1020" alt="Screenshot 2021-05-05 at 17 04 06" src="https://user-images.githubusercontent.com/5435412/117163472-f96f9700-adc3-11eb-9aa1-4c6b6611b1ec.png">
<img width="1128" alt="Screenshot 2021-05-05 at 17 04 25" src="https://user-images.githubusercontent.com/5435412/117163485-faa0c400-adc3-11eb-9b4a-a59b71882241.png">

**Comment by ihor-sviziev** [comment]
Hi @JoostWan,
It looks like the issue was already fixed in the 2.4-develop branch by the following PR https://github.com/magento/magento2/pull/34207.

Could you confirm that?

**Comment by JoostWan** [comment]
@ihor-sviziev Thanks. It's working

**Comment by ihor-sviziev** [comment]
Hi @JoostWan,
Thank you for confirming! I'm closing this issue now.
