### ISSUE TITLE
Widget atomic type

### ISSUE THREAD

**Issue by giangitman** [magento/magento2#3295]
Hi,

I want create a widget.xml like that:
<parameter name="attribute_options" xsi:type="MT\Widget\Block\Adminhtml\Widget\Attribute\Option"  visible="true">
                <label translate="true">Attribute Options</label>
                <description translate="true">Select attribute options to show</description>
                <depends>
                    <parameter name="widget_type" value="attribute" />
                </depends>
            </parameter>

So, could I create a new parameter type like that? If no, how can expand new atomic type?

**Comment by maksek** [comment]
@giangitman, please use forum for questions.
