### ISSUE TITLE
We can't find products matching the selection on Category Page Frontend in magento 2.4.2

### ISSUE THREAD

**Issue by Webalpha97** [magento/magento2#32967]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Webalpha97** [comment]
I had done re-indexing and even cleared cache. Then also showing Same issue.

**Comment by mrtuvn** [comment]
Can you provide details related issue following guide

**Comment by Webalpha97** [comment]
What you want let me know I will share that.

**Comment by Webalpha97** [comment]
I had migrated data from M1.9.4.2  to M2.4.2.

**Comment by Webalpha97** [comment]
I am having 2lakh products.

**Comment by Webalpha97** [comment]
When I open magento 2.4.2 category page now product is displayed and it shows above error.

**Comment by Webalpha97** [comment]
But it works for single product page .

**Comment by Webalpha97** [comment]
Anyone here who can help me out for this issue.

**Comment by engcom-Hotel** [comment]
Hello @Webalpha97,

Are you still facing this issue? If yes, then please provide us some steps to reproduce, actual and expected results,  and screenshots in order to better understanding the issue.

Thanks
