### ISSUE TITLE
Text Area for Customizable Options shows line break html<br/> on the front end in cart area if a user enters more than 55 characters

### ISSUE THREAD

**Issue by adamstapley** [magento/magento2#32977]
Summary of the issue
We have Customizable Options with text areas where people can enter up to 350 characters. If they enter a message that's 50 characters with line breaks it all works OK and displays properly in the cart area. If they enter more than 55 characters the cart area displays the html <br/> line break code

### Preconditions (*)
Information on your environment
Running Magento 2.4.2
Dedicated server
PHP 7.3
MariaDB10.3

### Steps to reproduce (*)
Steps to reproduce
Create a product in admin, create two customizable options both with text area option with 350 characters allowed. Enter less than 55 characters in one text area and more than 55 in the other both with spaces and line breaks. Add the item to your cart and you will see the html line breaks in the text area option with more than 55 characters.

### Expected result (*)
Cart should just show the text entered in each option and not the html line break code

### Actual result (*)
Cart shows html in option
![Capture](https://user-images.githubusercontent.com/45047386/117560309-d48b6480-b0e0-11eb-9be1-d89247f7defd.JPG)

**Comment by adamstapley** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by adamstapley** [comment]
Created a test product and issue still exist. This is a bundle product
URL: https://b8f5c5bbfe16193694e9c15ef90cc1d9-2-4-develop.instances.magento-community.engineering/checkout/cart/configure/id/5/product_id/2047/

![1](https://user-images.githubusercontent.com/45047386/117560550-d35b3700-b0e2-11eb-82e1-dcaee65fb370.JPG)
![2](https://user-images.githubusercontent.com/45047386/117560553-d6562780-b0e2-11eb-8cfb-89f7704e5cd6.JPG)

**Comment by adamstapley** [comment]
This looks like it might be related to issue #25418

I created a fix in Magento 2.4.2:
/public_html/vendor/magento/module-checkout/view/frontend/templates/cart/item/default.phtml

Line 52
<?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
Change to
<?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>

All line break code is removed. I presume this isn't the 100% correct way to achieve this but it works for me at the moment and I'm not a developer :)

**Comment by adamstapley** [comment]
Reproduced on 2.4.x.

**Comment by AZiniukhin** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42773` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @adamstapley. Thank you for your report. 
The issue has been fixed in magento/magento2#33256 by @AZiniukhin in 2.4-develop branch
Related commit(s):
 - [f724fece9f6704af67ca2a14ffe3c8d5adf38e7e](https://github.com/magento/magento2/commit/f724fece9f6704af67ca2a14ffe3c8d5adf38e7e)
 - [a3bf2977c53b96de2a5ab271624b90a7ec4dcac1](https://github.com/magento/magento2/commit/a3bf2977c53b96de2a5ab271624b90a7ec4dcac1)
 - [b506bb4a357b53c35176ca9e175de53144110623](https://github.com/magento/magento2/commit/b506bb4a357b53c35176ca9e175de53144110623)

The fix will be available with the upcoming 2.4.3 release.
