### ISSUE TITLE
Vertex Tax Calculation is really Slow on 2.4.2 

### ISSUE THREAD

**Issue by ninjacoder30** [magento/magento2#32974]
Magento 2.4.2 - vertex module calculation is extremely slow which makes the entire website slow wherever there is a calculation related code like add to cart , Checking totals on Checkout process etc.  
 
 Steps to reproduce (*)
 I have Installed the vanilla Enterprise Edition on My system and i am testing the add to cart Api on Product listing Page
1. First thing u need to be logged in as a customer or if u are using Guest Account the calculation is skipped
2. once u login just go to product Listing and try to add the Product it will take u more then 5 secs just to add the product when vertex is enabled and without it takes 0.5 sec so there is a huge difference in performance and because this entire checkout process is becoming slow. On our production where we have more data it takes more then 10 secs just to add a product with a better environment.

After doing debugging i found
vendor/vertex/module-tax/Model/Api/Data/QuotationRequestBuilder.php Line 94 -buildFromQuoteDetails this function is taking a lot of time and also this function is being called multiple times basically the calculatetax function and slowing down entire website.

    public function buildFromQuoteDetails(QuoteDetailsInterface $quoteDetails, $scopeCode = null)
    {
        $quoteMapper = $this->mapperFactory->getForClass(RequestInterface::class, $scopeCode);

        $request = $this->requestFactory->create();
        $request->setShouldReturnAssistedParameters(true);
        $request->setDocumentDate($this->dateTimeFactory->create());
        $request->setTransactionType(static::TRANSACTION_TYPE);
        $request->setCurrencyCode($this->storeManager->getStore($scopeCode)->getBaseCurrencyCode());

        $taxLineItems = $this->getLineItemData($quoteDetails, $scopeCode);

        $request->setLineItems($taxLineItems);

        $seller = $this->sellerBuilder
            ->setScopeCode($scopeCode)
            ->setScopeType(ScopeInterface::SCOPE_STORE)
            ->build();

        $request->setSeller($seller);

        $request->setCustomer(
            $this->customerBuilder->buildFromQuoteDetails(
                $quoteDetails,
                $scopeCode
            )
        );

        $this->deliveryTerm->addDeliveryTerm($request);

        $configLocationCode = $this->config->getLocationCode($scopeCode);

        if ($configLocationCode) {
            $locationCode = $this->stringUtilities->substr(
                $configLocationCode,
                0,
                $quoteMapper->getLocationCodeMaxLength()
            );
            $request->setLocationCode($locationCode);
        }

        return $request;
    }`

With Vertex Enabled : 
![Screenshot from 2021-05-08 14-51-02](https://user-images.githubusercontent.com/12250864/117534085-92ddb980-b00d-11eb-9dd6-19be7575d734.png)

Vertex Disabled
 
![Screenshot from 2021-05-08 14-53-30](https://user-images.githubusercontent.com/12250864/117534099-9ffaa880-b00d-11eb-9cad-ebdd70dbdb01.png)

Please note till 2.3.5 it was working really fast there was no issue . But after the upgrade of 2.4 it as slowed down. in 2.4.1 it was slow but slightly better then 2.4.2 but now in 2.4.2 its extremely slow which is bringing the entire website down. Please let me if there is any solution.

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko @gabrieldagama could you forward this issue to vertex developers?

**Comment by navarr** [comment]
@ninjacoder30 Hi!  Do you have any additional information that lead you to the conclusion that this is due to `buildFromQuoteDetails`?  

As far as the Vertex module is concerned, there have been no major changes to that method between 2.4.1 and 2.4.2, so I am surprised to hear of a major slowdown between the versions.

**Comment by ninjacoder30** [comment]
@navarr - Hi, there are changes in that and one thing i notice they are calling region collection for every product. 
add around 10 different sku's in the Cart and see the performance its really bad and wherever there is calculation that code is repeatedly called which wasn't happening before in 2.3 . 

one of the code you can check is getRegionData() in 351  =>vendor/magento/module-directory/Helper/Data.php

**Comment by navarr** [comment]
@ninjacoder30 Investigating this is going to be a bit more in-depth than I can handle on a GitHub ticket alone.  Could you please open a support request with Vertex?

**Comment by engcom-Alfa** [comment]
Hi @ninjacoder30 
Kindly update here about the vertex team response if you have got the issue resolved.

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may [go through the user guide](https://docs.magento.com/user-guide/).
