### ISSUE TITLE
"Add to Cart" button is disabled on the category page

### ISSUE THREAD

**Issue by spaho1986** [magento/magento2#32971]
### Preconditions (*)

1. Magento community v2.4.2
2. "Add to Cart" button on the category page is disabled

### Steps to reproduce (*)

1. Go to the category page by clicking any Magento category
2. Check the "Add to Cart" button of each product, it is disabled

### Expected result (*)

1. That button should not be disabled, at least it should be managed by a Magento configuration
2. The only way to enable the button is to hardcode the project

### Actual result (*)

1. The button is disabled and we cannot add a product in the cart from the category page
2. The only way to add it, is to go in the PDP of the product and click the "Add to Cart" button

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by spaho1986** [comment]
If you confirm that this is an issue, I can help you to solve it because I already have the solution.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@spaho1986, thanks for report.
Issue is not reproduced on clear installation 2.4.2
![2021-05-07-22-26-22@2x](https://user-images.githubusercontent.com/1129623/117499107-6bdaa580-af83-11eb-8e5e-3a40d37b6fdf.jpg)
and not reproduced on 2.4-develop
![2021-05-07-22-28-12@2x](https://user-images.githubusercontent.com/1129623/117499202-8f9deb80-af83-11eb-8ce2-9972bfa2420a.jpg)

**Comment by spaho1986** [comment]
@Den4ik @magento can you check the admin configuration option in STORES → Configuration → Sales → Checkout → Shopping Cart → “After Adding a Product Redirect to Shopping Car“
If you set it to yes, then you will be able to reproduce the issue on clear installation 2.4.2

**Comment by Den4ik** [comment]
@spaho1986 Thanks for the update. Yes, issue reproduced in 2.4.2 but fixed in https://github.com/magento/magento2/commit/373c220429547a098520eed2ba0b34a01449401e
Fix will be available in next release

**Comment by Den4ik** [comment]
@spaho1986 It's already fixed in 2.4-develop branch and will be available in next Magento release.

**Comment by spaho1986** [comment]
@Den4ik thank you,
for the next time, if I already have a solution once I open the issue should I provide the fix too(at the same time) in order to become a Magento contributor?

**Comment by Den4ik** [comment]
@spaho1986 If you would like to become contributor just follow documentation [DevDocs](https://devdocs.magento.com/contributor-guide/contributing.html) and welcome aboard :)

**Comment by spaho1986** [comment]
@Den4ik thank you :)
