### ISSUE TITLE
Backend-Content-Themes-View, No theme information

### ISSUE THREAD

**Issue by colyield** [magento/magento2#32970]
### Preconditions (*)

1. Magento version 2.4.2
![Screenshot 2021-05-07 052109](https://user-images.githubusercontent.com/18225064/117428441-16a38300-aef4-11eb-839f-0de7705f3429.jpg)

2.

### Steps to reproduce (*)

1. Upgraded from 2.4.1 to 2.4.2, the theme information does not display on the backend.
2.

### Expected result (*)

1. Theme information should display on Content-Themes-View.
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Any log details ? See your logs from var/log folder

**Comment by colyield** [comment]
> Any log details ? See your logs from var/log folder

An exception log: main.CRITICAL: The "catalog.leftnav" block threw an exception, and it can't be rendered. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The \"catalog.leftnav\" block threw an exception, and it can't be rendered.

A system log: main.CRITICAL: Warning: A non-numeric value encountered in /var/www/html/vendor/magento/module-catalog-search/Model/Layer/Filter/Price.php on line 194 [] []

**Comment by colyield** [comment]
Instead of using composer, I downloaded the 2.4.2 version from the Magento website and overwrite the files on the server, and setup/compile, now the backend for the theme-view is different, but the tabs are still not working. When click the tabs, nothing happened.


![Screenshot 2021-05-18 001145](https://user-images.githubusercontent.com/18225064/118589288-1619b080-b76e-11eb-8e9d-45a9db764f63.jpg)

**Comment by mrtuvn** [comment]
Seem i see you have custom module here! Default magento does not have any function related with css editor or js editor. Not sure that can be cause of problem! Can you share url of current page above ?
![themes](https://user-images.githubusercontent.com/1908873/125014091-38a5b700-e097-11eb-8491-95d1d1a9fa9f.png)
Theme view (edit from grid)
![theme-edit](https://user-images.githubusercontent.com/1908873/125014159-60951a80-e097-11eb-9c32-2f6488cdc091.png)

**Comment by colyield** [comment]
I have checked all the possibilities already. Even if I change the theme to
the official Luma theme, the "theme settings" page still shows nothing.
Sorry my website is in production, I will not share the url here.

**Comment by mrtuvn** [comment]
So i think problem may happen in production mode (real data) + require 3rd-party modules right ?

**Comment by colyield** [comment]
There's no 3rd-party module installed. The only thing we changed is some
CSS modifications in the customized theme. And I added some content on the
home page, with a small JAVA script for the home banner. I tried to delete
everything that I added or modified, still the same problem.

**Comment by colyield** [comment]
> So i think problem may happen in production mode (real data) + require 3rd-party modules right ? Do i go to right page in above screenshot

Yes, you are on the right page.

**Comment by engcom-Hotel** [comment]
Hello @colyield,

Thanks for posting this issue!

As per the description, it seems that you have tried to upgrade the Commerce from 2.4.1 to 2.4.2 but have not followed the official [documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html). Actually, this link described the correct way to upgrade commerce. Please follow the link and let us know if you are facing any difficulties.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @colyield ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
