### ISSUE TITLE
Issue with Cache Management.

### ISSUE THREAD

**Issue by Sammnyg2** [magento/magento2#32982]
### Preconditions (*)

1.  Magento 2.3.5
2. 

### Steps to reproduce (*)

1.  I flushed the catalog Images cache
2.  I flushed the Javascript/CSS cache
3.

### Expected result (*)

1. [Screenshots, logs or description]  The website is without layout and the links are un-clickable

### Actual result (*)

1. [Screenshots, logs or description]  The website is without layout and the links are un-clickable

**Comment by engcom-Alfa** [comment]
HI @Sammnyg2 
Can you please provide detailed steps to reproduce the issue along with screenshots/logs? Possibly you can even attached screen recording.
Currently we are unable to view the expected and actual attached screen shots too. Please make sure attached files are appropriate.
Thanks

**Comment by engcom-Echo** [comment]
Hi @Sammnyg2,

We are closing this issue as there has been no update on the same.

Thanks
