### ISSUE TITLE
Datetime custom attribute throws exception at mass attribute updates from admin product grid

### ISSUE THREAD

**Issue by Parism** [magento/magento2#32983]
### Preconditions (*)

1. Magento version 2.4.1
2.

### Steps to reproduce (*)

1. Create a custom date and time attribute and assign it to an attribute set.
2. From admin panel go to Catalog -> Products -> Select a product which is assigned to the attribute set which includes the newely created date and time custom attribute -> Actions -> Update attributes

### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/6481531/117637208-44095e80-b18a-11eb-9d26-2ce0741001c7.png)
2. Attribute edit page opens and the user moves on selecting the mass update actions.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/6481531/117637000-0e647580-b18a-11eb-8c59-f53eb7f7175e.png)

2. Exception thrown: Exception #0 (InvalidArgumentException): datetime doesn't extend \Magento\Framework\Data\Form\Element\AbstractElement

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
For me it showing blank page here :
![image](https://user-images.githubusercontent.com/46617848/118084716-cbe7a680-b3de-11eb-87fe-1b617430c820.png)

**Comment by Parism** [comment]
@krishprakash That's right, if you have production mode on it shows the blank page you mentioned. 
If you have developer mode on it prints the exception.
But the case is the same, there is a bug regarding the datetime attributes.

**Comment by Rakhi161** [comment]
@magento I am working on this

**Comment by Rakhi161** [comment]
@magento give me 2.4-develop instance

**Comment by Rakhi161** [comment]
![Uploading screenshot-192.168.32.118-2021.05.15-07_57_31.png…]()

**Comment by Rakhi161** [comment]
![screenshot-192 168 32 118-2021 05 15-07_57_31](https://user-images.githubusercontent.com/56825336/118345628-6963e700-b553-11eb-8229-d6e421e9086e.png)

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance
