### ISSUE TITLE
System config value never marked as changed when set to use system value

### ISSUE THREAD

**Issue by marciomaciel** [magento/magento2#32988]
When restoring a system configuration to the default value in Magento Admin, the system does not identify that the option has been changed even if the default configuration is different from the selected one.

This problem occurs for any system configuration that has a backend_model that checks whether the value has been changed or if the cached value needs to be invalidated when value is restored for default and different from previous value.

### Preconditions (*)

1. Magento Open Source/Commerce 2.*
2. Vanilla install, without sampledata
3. Store > Configuration > Catalog > Storefront -> List Mode checked to use system value
![image](https://user-images.githubusercontent.com/11759813/117734877-bf8b0000-b1ca-11eb-8a16-a46f27e52848.png)

### Steps to reproduce (*)

1. Place a XDebug breakpoint at vendor/magento/framework/App/Config/Value.php:126
https://github.com/magento/magento2/blob/5f0516612488bda34d4c0bf2aa863a3510c374b0/lib/internal/Magento/Framework/App/Config/Value.php#L125-L127
2. With XDebug enabled in browser, go to **Store > Configuration > Catalog > Storefront > List mode** and unchecked the option 'Use system value';
![image](https://user-images.githubusercontent.com/11759813/117735570-18a76380-b1cc-11eb-98c1-a7fadb31a0c5.png)
3. Change the default value '**Grid (default) / List**' to '**Grid Only**' on **List Mode** drop down and save config;
![image](https://user-images.githubusercontent.com/11759813/117735492-e8f85b80-b1cb-11eb-83a1-97fc2f3666d7.png)
4. The breakpoint will be reached, because data has changed from '**Grid (default) / List**' to '**Grid Only**'
5. Resume the execution;
6. With XDebug still enabled check the '**Use system value**' for List Mode config to restore the default configuration and save;
![image](https://user-images.githubusercontent.com/11759813/117735519-f7df0e00-b1cb-11eb-8dcb-852619862eac.png)
7. the breakpoint is never reached

### Expected result (*)

1. As the previous setting '**Grid only**' was restored to the default value '**Grid (default) / List**' and consequently changed, the breakpoint should be reached

### Actual result (*)

1. The breakpoint is never reached, not identifying that the configuration has been changed 
![image](https://user-images.githubusercontent.com/11759813/117734467-ea288900-b1c9-11eb-9906-2d73027c0d94.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment]
@magento-admin  give me 2.4-develop instance

**Comment by Penchal-magento** [comment]
Tried to reproduce the steps provided but we are unable to reproduce, kindly provide more detailed steps.

**Comment by marciomaciel** [comment]
@magento give me 2.4.2-p1 instance

**Comment by TheRealHunzik** [comment]
@magento give me 2.4.2-p1 instance
