### ISSUE TITLE
Magento 2 installation error on Step 6: Install

### ISSUE THREAD

**Issue by Shento** [magento/magento2#3298]
I'm installation magento 2 (Magento-CE-2.0.2) on live server i mean on cpanel but facing this error, i did everything according to magento 2 installation requirement but at the end i don't know how to solve this error.

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

![screenshot_1](https://cloud.githubusercontent.com/assets/17082603/12845265/7e06d120-cc26-11e5-9b9c-aa81959f5b1c.png)

Your help will be thankful :)
Thank you

**Comment by mazhalai** [comment]
@Shento is there any error in `var/log`? Also please check apache and php logs.

**Comment by Shento** [comment]
@mazhalai yes var folder create .maintenance.flag file

**Comment by mazhalai** [comment]
@Shento not just `var` directory, but `var/log`? Also, do you have access to command line? Can you run
`bin/magento deploy:mode:set developer` and try to install again.

**Comment by eddielau** [comment]
@Shento Also, please try to enable PHP error logging and see if anything is logged.
To enable it, in your php.ini file, add

```
log_errors=1
error_log=<path to a log file>
```

Then restart the web server and reinstall Magento again.

**Comment by Shento** [comment]
@mazhalai i have WHM access but don't know how to use command line installation. can you please explain me command installation ?

**Comment by Shento** [comment]
@eddielau just rename the php.ini.simple file to php.ini but still has error.

**Comment by Shento** [comment]
I have found .htaccess file in setup folder 

Options -Indexes
    RewriteEngine Off

Any idea about this ?

**Comment by mazhalai** [comment]
@shento more about CLI [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html) also, did you restart your server after making changes to php.ini and .htaccess?

**Comment by Shento** [comment]
@mazhalai no didn't restart server and still facing below error i don't know why this error coming  because everything is setup from WHM according to requirement and still facing below error ? 

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

**Comment by Shento** [comment]
@mazhalai can you tell me about > File permissions check error ? why it's accor and how to solve it ?

**Comment by ghost** [comment]
If you're using shared hosting and your web server runs as the `nobody` user/group, please let us know. That could be the issue. Magento expects [file system permissions](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html) to be 770/660, which can be an issue in a shared hosting environment.

If the web server runs as `nobody`, it has no permissions to files and directories in the Magento file system.

I'm not sure what the best solution is but if you can confirm this, it might help. Thanks

**Comment by Shento** [comment]
@xcomSteveJohnson I have VPS for magento 2 installation and setup everything according of magento 2 installation, you can see in above screenshot at the end i mean in last step : 6 got error. tried with different process but nothing find for solution.

**Comment by Shento** [comment]
@mazhalai any idea about below error ?

Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 12288 bytes) in /home/klikkapotek/public_html/vendor/magento/module-captcha/Observer/CheckUserLoginObserver.php on line 87

![screenshot_2](https://cloud.githubusercontent.com/assets/17082603/12865844/758f5314-ccda-11e5-941f-e41fdaf5cffb.png)

**Comment by ghost** [comment]
Sounds like you need to increase [`memory_limit`](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html#instgde-prereq-timezone) in `php.ini`

**Comment by Amnonsha** [comment]
getting same problem on VPS 3GB ram at godaddy.

on my var/log/ : 

<span class="text-info">Starting Magento installation:</span><br><span class="text-info">File permissions check...</span><br><span class="hidden">[Progress: 1 / 362]</span><br><span class="text-info">Enabling Maintenance Mode...</span><br><span class="hidden">[Progress: 2 / 362]</span><br><span class="text-info">Installing deployment configuration...</span><br>

allso in setup folder error_log attached. 

[error_log.zip](https://github.com/magento/magento2/files/123703/error_log.zip)

any idea?

**Comment by eddielau** [comment]
@Amnonsha Can you please try this https://github.com/magento/magento2/issues/3298#issuecomment-180458626 ?

**Comment by mazhalai** [comment]
@Amnonsha please check you php.ini, is the intl extension enabled?

**Comment by Amnonsha** [comment]
@eddielau 

added to php.ini: 
log_errors = 1
error_log=/var/log/error_log_text

restarted apache
"error_log_text" file not created. 

any ideas?

**Comment by Amnonsha** [comment]
@mazhalai - yes , it is set up on my php.inf

**Comment by eddielau** [comment]
Is your hosting environment Windows or *nix? If latter you will have to comment out the line in php.ini which includes intl.dll

**Comment by Amnonsha** [comment]
@eddielau  

its unix . so should I remove the intl extension ??!!!!

**Comment by Amnonsha** [comment]
@eddielau  

I removed the intl extension line.... that didnt help.

 please see 
[error_log.zip](https://github.com/magento/magento2/files/123751/error_log.zip)
I uploaded the error log. please take a look. I get memory size messages,  but its 3GB Server - shoudl be enough. 

 any idea mate?

**Comment by eddielau** [comment]
Did you restart your web server?

**Comment by Amnonsha** [comment]
yes . apache restarted every time.

**Comment by eddielau** [comment]
Can you share your php.ini file?

**Comment by Amnonsha** [comment]
I need your help , using PuTTY , how do I download the php.ini. 

by the way: just cleared my log file and tried again. getting single error line: 
[09-Feb-2016 20:40:16 UTC] PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 3072 bytes) in /home/qlear2016/public_html/vendor/magento/module-media-storage/Helper/File/Storage/Database.php on line 258

can it be that more than 3GB is needed? ???

**Comment by Amnonsha** [comment]
@eddielau 

please see at: 
http://qlear.co.il/phpinfo.php

**Comment by Amnonsha** [comment]
I got this working!!!!

changed php.ini memory alocated size.

I guess magento script is way to long for VPS servers

its running now ..... damm , I am good :-)

php.ini: 

max_execution_time  600 
max_file_uploads    20  
max_input_nesting_level 64  
max_input_time  600 
max_input_vars  1000000

**Comment by Amnonsha** [comment]
ok , got it installed , but look at this probelm , the theeme is not loading. any idea? 
http://qlear.co.il/
same thing on the admin backend

**Comment by mazhalai** [comment]
Can you check file permissions on `pub/static`? does webserver have access to those files? if you have access to command line please run `bin/magento setup:static-content:deploy`

**Comment by Amnonsha** [comment]
amazing,  this worked. thanks @mazhalai

**Comment by Amnonsha** [comment]
@mazhalai I was rushing too fast. 
I did get it all installed , but now it dosent work properly

admin is showing but nothing works. links are no working and admin is totaly dead. just seeing the first page. 

any more great ideas?

**Comment by mazhalai** [comment]
@Amnonsha can you please be specific about what doesn't work? css and js dont load? or something else?

**Comment by Amnonsha** [comment]
take a look : 
qlear.co.il
http://qlear.co.il/admin_rkcjlw
user:qlear_admin
pass: }B_bP!-(1qQH

* I will later change all users and passwords - its an empty site for now

**Comment by benmarks** [comment]
@Amnonsha **Please _do not_ post credentials here regardless of the circumstances.**

**Comment by mazhalai** [comment]
Check all file permissions again, looks like all in pub static are giving a 404 error.

**Comment by Amnonsha** [comment]
hi @mazhalai I got my magento 2.02 permissions messed up. how can I fix it?

i tried this , but still dosent work: 

find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
chmod +x mage

**Comment by mazhalai** [comment]
@Amnonsha please refer to [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and  [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)

**Comment by Amnonsha** [comment]
@mazhalai - HELP!
ok , after spending 2 hours , removing all files. installing agian. changing permissions, I cant get it to work. 

File Permission Check
2 file permission not met. Hide detail

The best way to resolve this is to allow write permissions for the following Magento directories and their sub-directories. The exact fix depends on your server, your host, and other system variables. 
Our File Permission Help can get you started.

If you need more help, please call your hosting provider.

"/home/qlear2016/public_html/app/etc" writable directory permission.
"/home/qlear2016/public_html/var" writable directory permission.
"/home/qlear2016/public_html/pub/media" writable directory permission.
"/home/qlear2016/public_html/pub/static" writable directory permission.

after chnging permissions it still give me this messgae. these are the currant permissions: 

drwxr-xr-x  7 qlear2016 qlear2016      4096 Feb 10 11:39 var/

drwxr-xr-x  6 qlear2016 qlear2016      4096 Feb 10 11:39 pub/

please help!!!!! I got lost.

**Comment by mazhalai** [comment]
what about files within each folder? all files need to be writable.

**Comment by Amnonsha** [comment]
755 permission?

**Comment by Amnonsha** [comment]
I kind of found the problem I think. I am not so good in SSH so file system issues I am used to do in Cpanel file explorer. 

I reinstalled the magento 2.02 on clean Cpanel account , everything went great- single shoot. 
once the site was set up , a single touch in the cpanel file explorer killed the site. It probably changed the public  files owner  and it got messed up. This time i tried changing back to 755 permisssions the PUB folder THROUGH FTP (only and not SSH ) and it worked. 

I guess I need to fix the file owners issue, how do I do that?

**Comment by mazhalai** [comment]
@Amnonsha file owner can be set by `chown -R :<your web server group name> .` See [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)

**Comment by mazhalai** [comment]
@Shento we assume your issue has been resolved, hence closing this ticket. Please feel free to open a new one if issues arise.

**Comment by JialuZhang** [comment]
@Shento 


In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
