### ISSUE TITLE
Configurable product loses linked configurations that are available in specific websites when data for other store view scope is edited

### ISSUE THREAD

**Issue by Skullsneeze** [magento/magento2#32993]
### Preconditions (*)

1. Magento Commerce version 2.3.6
2. Multiple websites / store views

  _For this example I use websites NL and DE, and store views nl_NL and de_DE_

### Steps to reproduce (*)

1. Go to Catalog > Products and create a configurable product
2. Create 2 configurations for the configurable product
3. Save the configurable product
4. Open one of the configurations for the configurable product
5. Change the website scope of the simple so that it is only available for the DE website and save the product
6. Go back to edit the configurable, and change the scope to the nl_NL store view
7. Change any field (e.g. the Title), and save the product
8. Switch back to either global or de_DE scope

### Expected result (*)

1. Both linked simples (configurations) are still linked to the configurable

### Actual result (*)

1. The simple product that is only available on the DE website is no longer linked to the configurable

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Skullsneeze** [comment]
@magento give me 2.4-develop instance

**Comment by Skullsneeze** [comment]
@engcom-Oscar I tested on the provided 2.4-develop instance, and the issue is not appearing there.

What I did notice is that the behaviour on my 2.3.8 instance is different. Mainly that when I switch to a different scope while editing the configurable product, I only see the configurations that are available in the selected scope (store views) website. On the 2.4-develop instance, I see all configurations, regardless of scope.

Do you know if this is something that has changed internally between 2.3 and 2.4?

In the mean time I will re-request a 2.3.8 instance to verify the issue there.

**Comment by Skullsneeze** [comment]
@magento give me 2.3.6 instance

**Comment by Den4ik** [comment]
@Skullsneeze Thanks for the report.
`@magento` provide only mainline instance from `2.4-develop`
Unfortunately you could not take 2.3.6 instance here.

**Comment by engcom-Oscar** [comment]
Hi @Skullsneeze I am not aware why the behavior so different on 2.4 and 2.3.6 Magento. But I also was not able to reproduce descried issue on the latest 2.4-develop branch.

**Comment by Skullsneeze** [comment]
After some further debugging it seemed that this was caused by a plugin which was setting the type instance's store filter, causing the product links to be disregarded.
