### ISSUE TITLE
State/Province Sorting of Magento2-jp has broken by the 2.3.6 core side logic change

### ISSUE THREAD

**Issue by mkawachi** [magento/magento2#32996]
### Preconditions (*)

1. Magento CE/Community 2.3.6 later with sample data is installed
2. Install Community-engineering/japan-common (https://marketplace.magento.com/community-engineering-japan-common.html)

### Steps to reproduce (*)

1. Go to demo store front, and create a new account.
2. Click and see the State/Province pull-up list.

The cause is below code, it's added at 2.3.6
regionsEntries.sort(function (a, b) {
    return a[1].name > b[1].name ? 1 : -1;
});
This code will force the database to change its output order to Unicode order.
This will cause the order in which they were correctly stored in the database to be appeared wrongly.

### Expected result (*)

1. Go to demo store front, and add 1 product to cart.
2. Go to Cart and Proceed to Checkout.　
3. Shipping Address shows up and click and see the State/Province pull-up list.
This list order is expected. Its working same as 2.3 even after the core logic change. It's expected, as specified in the Japanese standard, they are displayed in order from north to south.
English sample ![correct 2 3](https://user-images.githubusercontent.com/37786082/117919090-5b318300-b327-11eb-9eb4-c0b17342ca40.png)
Japanese sample ![correct-region-sort](https://user-images.githubusercontent.com/37786082/117924930-7e613000-b331-11eb-97b7-5da083718051.png)
 

### Actual result (*)

1. This is 2.4 actual result and it's wrong order.
The sorting is changed to unicode order.   U+4E09, U+4EAC, U+4F50, U+5175, U+5317 ....
![スクリーンショット 2021-05-27 12 06 16](https://user-images.githubusercontent.com/37786082/119760268-a5e4fa80-bee4-11eb-82f9-e96f67ded06f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
As written above, this state/provice (Japan's prefecture) has to be sorted north to west, it's Japanese standard JIS.

And, this won't be a Japan specific problem. Some country which are not using roman character mainly may have the same problem. Even in French, German, the country uses special characters such as having "umlaut" the order may become incorrect. 

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by paras89** [comment]
I am having trouble reproducing this issue on Magento 2.3.7, with the JP language pack installed.

Seeing the regions appear in checkout in the same order as they are in the database - sorted by ids.

I am seeing regions in ascending order from id 702 to 748
<img width="1056" alt="Screenshot 2021-05-24 at 20 31 26" src="https://user-images.githubusercontent.com/5895210/119398478-8628b900-bccf-11eb-8a20-b2b9fe0056f2.png">

**Comment by magento-engcom-team** [comment]
@paras89 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@paras89 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by m-kawachi** [comment]
Hi magento engcom team, I heard Paras could reproduced this on 2.3.7. So, please add Reproduced on 2.3.7 label and move forward. This is simple problem and he already have this solution. Thanks .

CC @paras89

**Comment by mkawachi** [comment]
Hi all, multiple Japanese customer using 2.3.x and 2.4.x are wating this fix. So, could you also include this fix into the next quality patch ?

**Comment by sukeshini-kot** [comment]
Is there any update on this?

**Comment by m-kawachi** [comment]
@sukeshini-kot 
I think this is already resolved by 2.4.3, except “Sales -> Orders -> Create New Order -> Create New Customer”.
Please check the behavior and comment.
