### ISSUE TITLE
Date and Time Format for Custom Option Not Working

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#32990]
### Preconditions (*)

1. Magento ver. 2.4.2
2. Nginx 1.18.0 (Ubuntu)
3. Maria DB 10.3.25

### Steps to reproduce (*)

1. [Follow these Steps](https://docs.magento.com/user-guide/stores/attribute-date-time-options.html) to Configure Date format
2. Check Date of Product with Custom Options of type Date

### Expected result (*)

1. Date Format Should Change on Front-end

### Actual result (*)

1. See result Below

https://user-images.githubusercontent.com/51072292/117776610-353bae00-b255-11eb-90f2-37dab6fe7f0c.mp4

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ *] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vlmed** [comment]
@magento I am working on it

**Comment by vlmed** [comment]
Hello, @engcom-Alfa 
If we look at the code, we can see that the Date Fields Order configuration is not used for the Js Calendar. And the date format is taken from the current locale
![1620828897596](https://user-images.githubusercontent.com/41998275/117990479-e02b9500-b345-11eb-8491-9e90ac841871.jpg)

Are you sure we need to change this behavior?

**Comment by paras89** [comment]
Magento\Catalog\Block\Product\View\Options\Type\Date::getDateHtml makes use of the given configuration.
Magento\Catalog\Block\Product\View\Options\Type\Date::getDateHtml is called from module-catalog/view/frontend/templates/product/view/options/type/date.phtml

**Comment by paras89** [comment]
Looks like Magento is coded to honor the order configuration only if Use JavaScript Calendar is set to NO.

<img width="854" alt="Screenshot 2021-05-12 at 15 55 50" src="https://user-images.githubusercontent.com/5895210/117997064-92f5f600-b33a-11eb-87d7-4951d36fe95a.png">
<img width="446" alt="Screenshot 2021-05-12 at 15 55 38" src="https://user-images.githubusercontent.com/5895210/117997084-97221380-b33a-11eb-841d-f6166755f5f1.png">

**Comment by TheRealHunzik** [comment]
Anyone working on this issue?

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @TheRealHunzik,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


<img width="1092" alt="Screenshot 2024-06-17 at 09 43 04" src="https://github.com/magento/magento2/assets/51680745/18d36014-158a-4701-b81d-c7beee0128af">


<img width="764" alt="Screenshot 2024-06-17 at 09 42 37" src="https://github.com/magento/magento2/assets/51680745/f91848e6-aa63-46f5-829d-3e9a0d35b559">


Date Format not Changing on Front-end.

Hence Confirming the issue.

Thanks.

**Comment by NitrogenUA** [comment]
@magento I am working on it
