### ISSUE TITLE
Bundle Products cannot save an option price of 0

### ISSUE THREAD

**Issue by ghost** [magento/magento2#33009]
### Preconditions (*)

1. Magento 2.4.2-p1

### Steps to reproduce (*)

1. Create a bundle product. (In the original case this was static sku, static price, 1 option with dropdown and multiple products, 1 option with checkbox and 1 product)
2. Attempt to set a price of 0 on items in the options
3. Save the product

### Expected result (*)

- Product saves with a price of 0 on those options.

### Actual result (*)

- Price of options reverts to product price, with no way to save the price at 0 in the admin panel.
- Users can only keep a price of 0 by manually editing catalog_product_bundle_selection in the database. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmcnamaracpc** [comment]
@magento give me 2.4-develop instance

**Comment by pmcnamaracpc** [comment]
I am having issues with recreating this on that development instance, I'll be checking again on the Magento instances this occurred on to see if there's more details needed to recreate

**Comment by pmcnamaracpc** [comment]
The relevant code was changed in https://github.com/magento/magento2/commit/acdefe469fbd242d66063a35f87aca202e884454 in LinksList.php lines 55-60 (changed to lines 65-70). The if ($bundledProductPrice <= 0) including 0 was related to this behavior.

This should only be an issue on 2.4.2 and 2.4.2-p1, and does not effect 2.4-develop
