### ISSUE TITLE
Order Status do not get updated in Shipment Grid.

### ISSUE THREAD

**Issue by gosavesg** [magento/magento2#33017]
@magento-admin  this is my issue:

### Preconditions (*)
Magento ver. 2.4.1.  

### Steps to reproduce (*)

1. Create New Order status Shipped and assign to state complete and set as default status.
2. View any order in Processing status and click the Ship button and submit, shipment is generated with status Shipped.
3. Go to shipment grid and select order status column to show in grid. Status will show as shipped - This is correct.
4. Go back to the same order and view the order. In the "Notes for this Order section" change status to Complete and click submit comment.
5. In the order grid the status shows as Complete - This is correct.
6. In the shipment grid the status still shows Shipped - This in incorrect.
7. If we view the shipment in the detail view Order status shows complete - This is also correct.

### Expected result (*)
1. The order status should be updated in the shipment grid as well whenever the order status is changed in the orders grid.

### Actual result (*)
1. Whenever I update status of any order using the "Notes for this Order section" it does not get updated in the shipment grid.

**Comment by gosavesg** [comment]
@krishprakash Can you please let us know if you were able to reproduce this issue? We are having lot of problem regarding shipment due to this issue and the status is not getting updated in the shipment grid!

**Comment by gosavesg** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42365` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @gosavesg,

Thanks for your reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/38917.

Hence we are closing this duplicate.

Thanks.
