### ISSUE TITLE
Integration with Klaviyo "Sorry, something went wrong. Please try again later." issue

### ISSUE THREAD

**Issue by IvanCyber** [magento/magento2#33013]
@magento this is my issue:

### Preconditions (*)

Magento ver. 2.4.2

### Steps to reproduce (*)

1. I Login in Magento2 with admin credentials.
2. In Magento2 administration,  Stores -> Configuration -> Klaviyo is properly set, and I see the Klaviyo lists there in the dropdown list.
3. When I go to Magento administration, System -> Integrations and click "Add new integration",
 - I set name, my e-mail, 
 - I set Callback url: https://www.klaviyo.com/integration-oauth-one/magento-two/auth/confirm?c=XXXXXXX
 - I set Identity link URL: https://www.klaviyo.com/integration-oauth-one/magento-two/auth/handle 
 - I set my Magento2 admin pass
 - Go to API tab and in Resource Access dropdown list I set "All", and
 - Click "Save", it is being saved, with note that the data are saved, but the new user is not created, because the old one is overwritten and updated.
 
 
### Expected result (*)

1. When I go to System -> Integrations and click on "Activate", I expect activated integration, so that I can finish integration in Klaviyo.

### Actual result (*)

1. When I go to System -> Integrations and click on "Activate", I get the window with note "The integration you selected asks you to approve access to the following:" and all the selected resources are listed. I click on "Allow" window and I get "Sorry, something went wrong. Please try again later.".  
2. When I go to see the integration, what I see is that "Consumer Key" and "Consumer Secret" fields are filled, but "Access Token" and "Access Token Secret" are empty.

What am I doing wrong?

**Comment by IvanCyber** [comment]
@magento I am working on this

**Comment by jorgb90** [comment]
Hi @IvanCyber ,

This wil fix your issue; https://github.com/magento/magento2/commit/68d20230ca9d6198fa3093eb174e24aff47b1646

**Comment by magento-engcom-team** [comment]
@engcom-Golf Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Golf 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42344` were created

**Issue Available**: @engcom-Golf, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by klaviyojad** [comment]
@magento-engcom-team when is this fix going to be released?  what version of Magento will include it?
