### ISSUE TITLE
Sort of related products in GraphQL not implemented

### ISSUE THREAD

**Issue by ceggebeen** [magento/magento2#33010]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Create a product and add some related products
2. Get product from de GraphQL endpoint

### Expected result (*)

1. Product data with related products sort by position

### Actual result (*)

1. Product data with related products without sort

**Comment by ceggebeen** [comment]
@magento I am working on this

**Comment by ceggebeen** [comment]
@magento add to contributors team

**Comment by ceggebeen** [comment]
@magento add to contributors team

**Comment by ceggebeen** [comment]
@magento I am working on this

**Comment by serbynskyi** [comment]
@magento I am working on this
