### ISSUE TITLE
Magento EE 2.0 upgrade issue

### ISSUE THREAD

**Issue by ils-rajnikantd** [magento/magento2#3301]
Hello I am trying to upgrade Magento EE 2.0 to 2.0.2 on my local windows machine using the command line. But during the upgrade process I am getting the following issue.

Please see the attache image.
![m2-update error](https://cloud.githubusercontent.com/assets/12799420/12848437/e97cda76-cc3f-11e5-8043-1ef08e08dfc8.png)

**Comment by mazhalai** [comment]
@ils-rajnikantd please do not post EE issue on github, please use the partner portal.  Also, did you checkout instructions [here|http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html]
