### ISSUE TITLE
when i upgrade magento2.1 to 2.2  

### ISSUE THREAD

**Issue by cha80** [magento/magento2#33020]
### Preconditions (*)

2.1 to 2.2
2. i don't know why 
3. it's my mysql error log
[izm5ea0oa5iduipatpy2jyz.err.txt](https://github.com/magento/magento2/files/6482145/izm5ea0oa5iduipatpy2jyz.err.txt)

### Steps to reproduce (*)

1.
2. 
bin/magento setup:upgrade

### Expected result (*)

1. [Screenshots, logs or description]
2.
![image](https://user-images.githubusercontent.com/56351661/118347177-b5268880-b573-11eb-9749-10dfdafde5d2.png)
when i re run upgrade command it's show 
 [](url)
![image](https://user-images.githubusercontent.com/56351661/118349163-9cbd6a80-b581-11eb-804c-31a2db91c5f6.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This is my mysql configure file my.cnf
[my.cnf.txt](https://github.com/magento/magento2/files/6481868/my.cnf.txt)

 information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
[]

(url)[](url)

**Comment by cha80** [comment]
i think it maybe  sales_order don't have index  cause this problem

**Comment by engcom-Alfa** [comment]
Hi @cha80 
Require more updates for re-producing issue like steps to reproduce , mysql version etc

**Comment by engcom-Echo** [comment]
Hi @cha80 ,

We are closing the issue as no updates were provided on the same.

Thanks

**Comment by cha80** [comment]
when i delete the order it's fix
