### ISSUE TITLE
main.CRITICAL: Exception message: Class Magento\Customer\Model\Validator\Name does not exist

### ISSUE THREAD

**Issue by tyago343** [magento/magento2#33028]
### Preconditions (*)

1. Magento 2.4.2-p1
2.

### Steps to reproduce (*)

1. Create an user
2.

### Expected result (*)

1. User created

### Actual result (*)

1. Error, "we can't create a customer

main.CRITICAL: Exception message: Class Magento\Customer\Model\Validator\Name does not exist
Trace: <pre>#1 Magento\Framework\Code\Reader\ClassReader->getConstructor() called at [vendor/magento/framework/ObjectManager/Definition/Runtime.php:54]
#2 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:100]
#3 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/Validator/UniversalFactory.php:36]
#5 Magento\Framework\Validator\UniversalFactory->create() called at [vendor/magento/framework/Validator/Builder.php:285]
#6 Magento\Framework\Validator\Builder->_createConstraintValidator() called at [vendor/magento/framework/Validator/Builder.php:252]
#7 Magento\Framework\Validator\Builder->_createConstraint() called at [vendor/magento/framework/Validator/Builder.php:155]
#8 Magento\Framework\Validator\Builder->_createValidatorInstance() called at [vendor/magento/framework/Validator/Builder.php:141]
#9 Magento\Framework\Validator\Builder->createValidator() called at [vendor/magento/framework/Validator/Config.php:100]
#10 Magento\Framework\Validator\Config->createValidator() called at [vendor/magento/framework/Validator/Factory.php:145]
#11 Magento\Framework\Validator\Factory->createValidator() called at [vendor/magento/module-customer/Model/ResourceModel/Customer.php:190]
#12 Magento\Customer\Model\ResourceModel\Customer->_validate() called at [vendor/magento/module-customer/Model/ResourceModel/Customer.php:175]
#13 Magento\Customer\Model\ResourceModel\Customer->_beforeSave() called at [vendor/magento/module-eav/Model/Entity/VersionControl/AbstractEntity.php:90]
#14 Magento\Eav\Model\Entity\VersionControl\AbstractEntity->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:23]
#18 Magento\Customer\Model\ResourceModel\Customer\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:655]
#19 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Customer\Model\Customer\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Customer\Model\Customer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\Customer\Model\Customer\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/Customer/Interceptor.php:23]
#23 Magento\Customer\Model\Customer\Interceptor->save() called at [vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php:255]
#24 Magento\Customer\Model\ResourceModel\CustomerRepository->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/vertex/module-tax/Model/Plugin/CustomerRepositoryPlugin.php:155]
#27 Vertex\Tax\Model\Plugin\CustomerRepositoryPlugin->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-customer/Model/Plugin/CustomerRepository/TransactionWrapper.php:44]
#29 Magento\Customer\Model\Plugin\CustomerRepository\TransactionWrapper->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php:23]
#32 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->save() called at [vendor/magento/module-customer/Model/AccountManagement.php:927]
#33 Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash() called at [vendor/magento/module-customer/Model/AccountManagement.php:874]
#34 Magento\Customer\Model\AccountManagement->createAccount() called at [vendor/magento/module-customer/Controller/Account/CreatePost.php:380]
#35 Magento\Customer\Controller\Account\CreatePost->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#36 Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#37 Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-customer/Controller/Plugin/Account.php:64]
#38 Magento\Customer\Controller\Plugin\Account->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#39 Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#40 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#41 Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#42 Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php:23]
#43 Magento\Customer\Controller\Account\CreatePost\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#44 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#45 Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#46 Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#47 Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php:32]
#48 Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#49 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#50 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#51 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#52 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#53 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#54 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#55 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#56 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#57 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#58 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#59 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#60 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]

**Comment by engcom-Alfa** [comment]
@tyago343 
I have tried to reproduce it. As the description says create a new **_user_**. Actual message is having Error in creating **_customer_**. So tried to create user and customer both. Worked well. Below is the successfully created screenshots.

<img width="936" alt="UserCreationWorking" src="https://user-images.githubusercontent.com/51679138/118607231-f7e79b00-b7d5-11eb-936e-6afe55727dce.PNG">
<img width="937" alt="CustomerCreationWorking" src="https://user-images.githubusercontent.com/51679138/118607248-fcac4f00-b7d5-11eb-9755-dc7c3b192f74.PNG">

Kindly update provide us the reproducible steps completely. If you are creating user, then kindly mention what test data you are using and what type of role and etc. Similarly if you are creating a customer, kindly provide complete test data.

**Comment by engcom-Alfa** [comment]
As waited for ~14 days; going to close the ticket.
If you find a issue in the future on it again, you may please report a new issue.
Thanks
