### ISSUE TITLE
Sample data installation fails with "Duplicate entry" error on setup_module table

### ISSUE THREAD

**Issue by deltab** [magento/magento2#3304]
Running "magento setup:upgrade" can fail when the first sample data module is reached, with a database error similar to "Integrity constraint violation: Duplicate entry 'Magento_CustomerSampleData' for key PRIMARY in setup_module".

Executing "select \* from setup_module" in MySQL shows that schema_version is NULL for all the sample data modules.

File var/.sample-data-state.flag contains "error". It appears that the database error is not logged.

**Workaround**
Executing "delete from setup_module where schema_version is null" in MySQL appears to resolve the problem.

**Comment by rudenko-maksym** [comment]
The workaround worked for me. Thanks.

**Comment by veloraven** [comment]
@deltab thank you for your report.
Please provide information about versions you used.

**Comment by deltab** [comment]
`git branch -v` output:
- develop 01141f4 Merge pull request #342 from magento-extensibility/MAGETWO-38635-prs

composer.json starts with:

```
{
    "name": "magento/magento2ce",
    "description": "Magento 2 (Community Edition)",
    "type": "project",
    "version": "2.0.0",
```

Would composer.lock be useful? Something else?

**Comment by NadiyaS** [comment]
Hi @deltab ,
we can not reproduce this bug on current Magento develop branch.
If you still have the same problem please provide us more detailed steps to reproduce. 
Thanks,

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
