### ISSUE TITLE
not display welcome message and customer name on mobile device after advanced js bundling

### ISSUE THREAD

**Issue by arhmart** [magento/magento2#33045]

**Comment by engcom-Alfa** [comment]
Hi @arhmart 
Kindly provide more details like steps to reproduce and expected/actual behaviour so that we can reproduce it

**Comment by arhmart** [comment]
hi, the versionis magento 2.4.2-p1 luma theme.
All steps are according to the Magento advanced js bundling guide.
No other problems have been found for the time being. But in the account menu of the mobile device, the welcome message are not displayed, and the customer name and the qty number in the wishlist brackets are also not displayed after login.

I have this issue on magento 2.4.1 version, and the problem still exists after upgrading to magento 2.4.2-p1. The problem was reproduced on the other test site of magento 2.4.2.

Sorry, I am using github for the first time and I don't know how to update the question. If you enable advanced bundling, then you should be able to find this problem. I have this problem on both servers.

![QQ图片20210520005434](https://user-images.githubusercontent.com/84454905/118853682-97a44680-b906-11eb-9dac-e472e94566de.png)
![QQ图片20210520005754](https://user-images.githubusercontent.com/84454905/118853687-983cdd00-b906-11eb-8a90-a1e0da210640.png)

**Comment by ihor-sviziev** [comment]
@arhmart i would recommend you to try https://github.com/magesuite/magepackfor advanced bundling

**Comment by arhmart** [comment]
@ihor-sviziev i'll try it, thanks

**Comment by arhmart** [comment]
### Summary of the issue
After advanced js bundling, the welcome message (customer name after login), and the item qty of wishlist on the menu not display on mobile device. But they work fine on PC and also work fine without advanced js bundling. The picture below shows the display of the mobile device, there are no welcome message before login, and the customer name and wishlist quantity is not displayed after login.

![1](https://user-images.githubusercontent.com/84454905/119135059-8414ef00-ba70-11eb-9adf-a6879fb602a7.png)
![2](https://user-images.githubusercontent.com/84454905/119135062-84ad8580-ba70-11eb-8049-203c7f945ffb.png)


### Information on your environment
Magento 2.4.2-p1 luma (I have this issue on magento 2.4.1 version, and the problem still exists after upgrading to magento 2.4.2-p1. The problem was reproduced on the other test site of magento 2.4.2.)

Nginx 1.18
PHP 7.4
Mysql 8
Redis
Varnish
Elasticsearch
NPM r.js

### Steps to reproduce
All steps are according to the Magento advanced js bundling guide.
https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html

After enable advanced js bundling, no other problems have been found for the time being, except that the welcome message, customer name and wishlist qty are not displayed.

### Expected and actual results
Display the welcome message before login, customer name and wishlist qty after login like below:

![3](https://user-images.githubusercontent.com/84454905/119135088-8bd49380-ba70-11eb-89f7-9108e0df996b.png)
![4](https://user-images.githubusercontent.com/84454905/119135093-8d05c080-ba70-11eb-9b5d-6a01c9c3f291.png)


Hi @engcom-Alfa, i has update the question, please help to find out what is causing it, thank you very much for your contribution.

**Comment by arhmart** [comment]
@magento I am working on this

**Comment by engcom-Echo** [comment]
Hi @arhmart ,

Can you please provide update on this.

Thanks

**Comment by engcom-Echo** [comment]
Hi @arhmart ,

We are closing this issue as no update has been given.

Thanks
