### ISSUE TITLE
Magento2: Import product not working. Stuck on Please Wait notice

### ISSUE THREAD

**Issue by mateusz-is** [magento/magento2#33049]
### Preconditions (*)

1. Magento 2.4.0

### Steps to reproduce (*)

1. When i try import csv file, importing stuck on "Please wait" and nothing more.
I choose Entity Type = Product
![image](https://user-images.githubusercontent.com/72963245/118963510-cb16bd80-b966-11eb-8028-d69b414771f1.png)

### Expected result (*)

1. I found error in exception.log but i have the same error in my staging version and there import is working fine.

`[2021-05-20 09:42:31] main.CRITICAL: Path "/var/www/html/test/var/importexport//uMJOeNuQBxABrcFkb9mrdvP2o3o8lQ8Q.csv" cannot be used with directory "/var/www/html/test/pub/media/" {"exception":"[object] (Magento\\Framework\\Exception\\ValidatorException(code: 0): Path \"/var/www/html/test/var/importexport//uMJOeNuQBxABrcFkb9mrdvP2o3o8lQ8Q.csv\" cannot be used with directory \"/var/www/html/test/pub/media/\" at /var/www/html/test/vendor/magento/framework/Filesystem/Directory/PathValidator.php:63)"} []`

2. In developer mode I don't have any errors in console, network etc. I don't know what problem is also i give the same permission on my staging version and production and import on staging is working and on production dosen't working.  

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/72963245/118958714-f5b24780-b961-11eb-85d2-8f02a7748d70.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mateusz-is** [comment]
Hello, Guys do you have any ideas?

**Comment by engcom-Alfa** [comment]
I have tried importing the sample product data in the bulk with 10k records as such. Similarly tried with Configurable products also able to import with 10k records in the CSV file.
Tried with magento 2.4-develop and no issue found as such.
Kindly update me with more info like what type of records you are importing and what all content the file has.
Also please upgrade to the latest version and give a try. More and more detailed information will be good to check.

Note: Also kindly check if your php.ini has a enough memory limit. It would be good if you set it to memory_limit=-1

**Comment by engcom-Alfa** [comment]
As there is no response in last ~14 days, the issue is being closed.
If you face issue on this again in the latest Magento version, kindly raise a new ticket.
Thanks
