### ISSUE TITLE
Newsletter Subscription does not check for newsletter/general/active (no effective check for disabled newsletter implemented)

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#33040]
We found on our Magento2 Shops (Version 2.4.0 - 2.4.2) various successful attempts to subscribe to newsletter by posting to /newsletter/subscriber/new/. The newsletter functionality however is disabled, but still accepting new emails and sending confirmation mails out.

### Preconditions (*)
1. Magento installation version 2.4.0 to 2.4.2 is vulnerable 

### Steps to reproduce (*)
1. In the admin backend, disable newsletter functionality.
2. Create or forge html form that posts to /newsletter/subscriber/new/

### Expected result (*)
1. New subscribers should not be accepted

### Actual result (*)
1. In the backend, you will find a new newsletter subscriber. Furthermore, a newsletter confirmation email is sent out.

Since the Magento_Newsletter module can't be disabled due to dependencies from Magento_Customer, the only way to prevent new subscribers is to edit code in vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stephansteiner** [comment]
@magento give me 2.4-develop instance

**Comment by stephansteiner** [comment]
Ok, I was able to recreate the bug on the test instance. To make it easy, I used the newsletter subscription form on the home page of the test instance. But you can inject any html form into the page or modify the search form.

The steps to recreate the bugs are:
1. Open frontend, the newsletter subscription in the page bottom should be visible
2. Open backend, disable the newsletter functionality (Stores > Configuration > Customers > Newsletter > General Options > Enabled -> set to "No", clear cache to make configuration change active
3. Switch to the frontend (don't reload or the newsletter subscription form will disappear)
4. Enter any email (i entered "ohmgod@foundabug.com") click on "Subscribe"
5. The message "Thank you for your subscription" appears, in the backend the email is subscribed.

If you already disabled the newsletter functionality and the form is not visible, you can inject any html into the page source code (just change the shop url before /newsletter/subscriber/new) :
```
<form action="https://2bfdda75e315b500b123d2eca47506cd-2-4-develop.instances.magento-community.engineering/newsletter/subscriber/new/" method="POST">
<input type="text" name="email" value="ohmygodness@magentobug.com" />
<input type="submit"/>
</form>
```
when submitting the form, you have another subscriber in the newsletter.
![Bildschirmfoto 2021-05-19 um 10 34 20](https://user-images.githubusercontent.com/5113496/118781877-d0540980-b88d-11eb-96b4-75c02ccda0d4.png)

**Comment by engcom-Golf** [comment]
@stephansteiner Thanks for reporting the Bug. We are working on it.

**Comment by magento-engcom-team** [comment]
@engcom-Golf Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by SilinMykola** [comment]
@magento I am working on this
