### ISSUE TITLE
Composer package not updated to v2

### ISSUE THREAD

**Issue by marciomaciel** [magento/magento2#33047]
The composer package installed in _vendor/bin/composer_ not up-to-date to V2 and not available to upgrade with composer require` composer/composer ^2 `due to locked versions of semver package not compatible with Composer 2
### Preconditions (*)

1. Magento Open Source/Commerce 2.4.2-p1
2. Vanilla install

### Steps to reproduce (*)

1. Install Magento with `bin/magento setup:install`
2. Run `bin/magento sampledata:deploy`

### Expected result (*)

1. Sampledata installation using system composer or composer 2
2. Fast installation using Composer 2 features and auth.json created with Magento installation with `composer create-project `command
3. Usage of composer cache previously created by Magento instalation by composer

### Actual result (*)

1. Sampledata installation with composer v1.* located at vendor/bin/composer and installed with project composer create-project
2. Slow install due to composer 1 issues and download of all cached contents before install sampledata packages
3. ![image](https://user-images.githubusercontent.com/11759813/118874250-1080af80-b8c1-11eb-81f1-488f57a8d460.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
I'm pretty sure that this will be introduced in Magento 2.4.3 in August later this year, since it already happened in Magento 2.3.7 that got released last week:

```
# Magento 2.4.2-p1:
$ vendor/bin/composer --version
Composer 1.10.20 2021-01-27 15:41:06

$ composer depends composer/composer
magento/composer                               1.6.0       requires  composer/composer (^1.9)
magento/composer-root-update-plugin            1.1.1       requires  composer/composer (<=1.10.20 || >=2.0.0 <=2.0.11)
magento/framework                              103.0.2-p1  requires  composer/composer (^1.9 || ^2.0)
magento/inventory-composer-installer           1.2.0       requires  composer/composer (^1.9 || ^2.0)
magento/magento-composer-installer             0.2.1       requires  composer/composer (^1.9 || ^2.0)
magento/magento2-base                          2.4.2-p1    requires  composer/composer (^1.9 || ^2.0)
magento/magento2-functional-testing-framework  3.5.0       requires  composer/composer (^1.9||^2.0)
magento/product-community-edition              2.4.2-p1    requires  composer/composer (^1.9 || ^2.0)

# Magento 2.3.7:
$ vendor/bin/composer --version
Composer 2.0.11 2021-02-24 14:57:23

$ composer depends composer/composer
magento/composer                               1.7.0    requires  composer/composer (^1.9 || ^2.0)
magento/composer-root-update-plugin            1.1.1    requires  composer/composer (<=1.10.20 || >=2.0.0 <=2.0.11)
magento/framework                              102.0.7  requires  composer/composer (^1.9 || ^2.0)
magento/inventory-composer-installer           1.2.0    requires  composer/composer (^1.9 || ^2.0)
magento/magento-composer-installer             0.2.1    requires  composer/composer (^1.9 || ^2.0)
magento/magento2-base                          2.3.7    requires  composer/composer (^1.9 || ^2.0)
magento/magento2-functional-testing-framework  2.7.1    requires  composer/composer (^1.9||^2.0)
magento/product-community-edition              2.3.7    requires  composer/composer (^1.9 || ^2.0)
```

Notice that the only package that blocks composer v2 in Magento 2.4.2-p1 is `magento/composer` that is [locked to version 1.6.0](https://github.com/magento/magento2/blob/2.4.2-p1/composer.json#L69).
In Magento 2.3.7, they allow [both versions 1.6.0 and 1.7.0](https://github.com/magento/magento2/blob/2.3.7/composer.json#L69) and version 1.7.0 allows composer v2 to get installed.

You can probably work around this by adding something like this to your `composer.json` file:
```
     "require": {
        "magento/composer": "1.7.0 as 1.6.0",
        ...
     }
```
And running `composer update magento/composer`

Be sure to remove this again when upgrading to Magento 2.4.3 or higher.

**Comment by marciomaciel** [comment]
magento@0047281fee66:/var/www/html$ composer require composer/composer ~2.0.0
./composer.json has been updated
Running composer update composer/composer
Gathering patches for root package.
Loading composer repositories with package information                                                                                                                                           In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/composer[2.0.0, ..., 2.0.14] require composer/semver ^3.0 -> found composer/semver[3.0.0, ..., 3.2.5] but the package is fixed to 1.7.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires composer/composer ~2.0.0 -> satisfiable by composer/composer[2.0.0, ..., 2.0.14].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by engcom-Lima** [comment]
Hi @marciomaciel

I saw your issue and It seems composer is not installed properly. Can you remove existing composer and reinstall composer in your machine? 

You can check this https://getcomposer.org/doc/03-cli.md for installing and upgrading the composer.

Let me know if any query or issue.

**Comment by hostep** [comment]
@marciomaciel: you can ignore @engcom-Lima's remark (he's talking about a globally installed composer, not the `composer/composer` package in your Magento project).

Have you already tried [the workaround I mentioned earlier](https://github.com/magento/magento2/issues/33047#issuecomment-844423628)?

**Comment by engcom-Lima** [comment]
Hi @marciomaciel,

We are waiting since 14 days, We did not get any response on this ticket. Hence we are closing this ticket. 

Please feel free to raise the issue if you get into future.

Thanks for the understanding!
