### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Magento\\InventoryConfiguration\\Model\\IsSourceItemManagementAllowedForProductType\\Interceptor::execute() must be of the type string, null given

### ISSUE THREAD

**Issue by olegosh** [magento/magento2#33053]
### Preconditions (*)

When we try to delete a product by its sku, in version of magento 2.3.6 an error occurs.

It seems that problem might be in DB table with sku with values equal to null, the solution might be like this:

UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;

But I don't have a catalog_product_entity table and these products are generated and deleted on the fly by tests in order to make sure that process of deletion products by their sku works fine. It works in version 2.3.5, but in version 2.3.6 doesn't work.
What could be a possible solution to this issue?
### Steps to reproduce (*)

1. Installed magento 2.3.6 instance on web hosting
2. Generate product with randomized SKU
3. Add product to DB
4. Request the deletion of this product by its SKU

### Expected result (*)

The expected result is the successful removal of the product generated by the test and the added product according to its SKU.

### Actual result (*)

Error occurs:
`Error: Error in making request to https://hostname.com/magento_2_3_6/rest/V1/products Status code: 500 Body: "<br />\n<b>Fatal error</b>: Uncaught TypeError: Argument 1 passed to Magento\\InventoryConfiguration\\Model\\IsSourceItemManagementAllowedForProductType\\Interceptor::execute() must be of the type string, null given, called in /home/username/public_html/magento_2_3_6/vendor/magento/module-inventory-low-quantity-notification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php on line 83 and defined in /home/username/public_html/magento_2_3_6/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20\nStack trace:\n#0 /home/username/public_html/magento_2_3_6/vendor/magento/module-inventory-low-quantity-notification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php(83): Magento\\InventoryConfiguration\\Model\\IsSourceItemManagementAllowedForProductType\\Interceptor-&gt;execute(NULL)\n#1 /home/username/public_html/magento_2_3_6/vendor/magento/framework/Interception/Interceptor.php(146): Magento\\InventoryLowQuantityNotifi in <b>/home/username/public_html/magento_2_3_6/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php</b> on line <b>20</b><br />\n{\"messages\":{\"error\":[{\"code\":500,\"message\":\"Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\\\InventoryConfiguration\\\\Model\\\\IsSourceItemManagementAllowedForProductType\\\\Interceptor::execute() must be of the type string, null given, called in \\/home\\/username\\/public_html\\/magento_2_3_6\\/vendor\\/magento\\/module-inventory-low-quantity-notification\\/Plugin\\/Catalog\\/Model\\/ResourceModel\\/Product\\/ProcessDefaultSourceItemConfigurationPlugin.php on line 83 and defined in \\/home\\/username\\/public_html\\/magento_2_3_6\\/generated\\/code\\/Magento\\/InventoryConfiguration\\/Model\\/IsSourceItemManagementAllowedForProductType\\/Interceptor.php:20\\nStack trace:\\n#0 \\/home\\/username\\/public_html\\/magento_2_3_6\\/vendor\\/magento\\/module-inventory-low-quantity-notification\\/Plugin\\/Catalog\\/Model\\/ResourceModel\\/Product\\/ProcessDefaultSourceItemConfigurationPlugin.php(83): Magento\\\\InventoryConfiguration\\\\Model\\\\IsSourceItemManagementAllowedForProductType\\\\Interceptor->execute(NULL)\\n#1 \\/home\\/username\\/public_html\\/magento_2_3_6\\/vendor\\/magento\\/framework\\/Interception\\/Interceptor.php(146): Magento\\\\InventoryLowQuantityNotifi' in '\\/home\\/username\\/public_html\\/magento_2_3_6\\/generated\\/code\\/Magento\\/InventoryConfiguration\\/Model\\/IsSourceItemManagementAllowedForProductType\\/Interceptor.php' on line 20\",\"trace\":\"Trace is not available.\"}]}}"
`
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ +] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @olegosh,

Kindly elaborate the issue with screenshots and logs as the steps to re-produce are not clear.

Thanks

**Comment by engcom-Echo** [comment]
Hi @olegosh ,

We are closing this issue as no update has been provided on the same.

Thanks
