### ISSUE TITLE
Cart page show error after update magento 2.3.2 to 2.4.2

### ISSUE THREAD

**Issue by jpillai88** [magento/magento2#33054]
After update magento  2.3.2 to 2.4.2  check out page show this error.

Error: Call to a member function isClearShoppingCartEnabled() on null in /home/magento/magento2_staging/vendor/magento/module-checkout/view/frontend/templates/cart/form.phtml:59 Stack trace: #0 /home/magento/magento2_staging/vendor/magento/framework/View/TemplateEngine/Php.php(71): include() #1 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render() #2 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() #3 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() #4 /home/magento/magento2_staging/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() #5 /home/magento/magento2_staging/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render() #6 /home/magento/magento2_staging/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView() #7 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #8 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #9 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #10 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml() #11 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock() #12 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #13 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #14 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #15 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #16 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #17 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #18 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #19 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(522): Magento\Framework\View\Layout->renderElement() #20 /home/magento/magento2_staging/vendor/magento/module-checkout/view/frontend/templates/cart.phtml(16): Magento\Framework\View\Element\AbstractBlock->getChildHtml() #21 /home/magento/magento2_staging/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/magento/m...') #22 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render() #23 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() #24 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() #25 /home/magento/magento2_staging/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() #26 /home/magento/magento2_staging/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render() #27 /home/magento/magento2_staging/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView() #28 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #29 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #30 /home/magento/magento2_staging/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #31 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml() #32 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock() #33 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #34 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #35 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #36 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #37 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #38 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #39 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #40 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #41 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #42 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #43 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #44 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #45 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #46 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #47 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #48 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #49 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #50 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #51 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #52 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement() #53 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer() #54 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement() #55 /home/magento/magento2_staging/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement() #56 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput() #57 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent() #58 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #59 /home/magento/magento2_staging/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins() #60 /home/magento/magento2_staging/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #61 /home/magento/magento2_staging/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render() #62 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult() #63 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent() #64 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() #65 /home/magento/magento2_staging/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins() #66 /home/magento/magento2_staging/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult() #67 /home/magento/magento2_staging/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch() #68 /home/magento/magento2_staging/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #69 {main}

**Comment by jpillai88** [comment]
I cannot understand the previous comment

**Comment by hostep** [comment]
This is most likely an issue that appeared after https://github.com/magento/magento2/pull/28594/files#diff-fb9bd589d1af97eaeb16fb56abf8969ea6e49950c5fdcef5e8354d7dc09476ac got merged.

Can you try to search your custom theme for xml files where the template file `Magento_Checkout::cart/form.phtml` is being used and see if that `<block>` has the following argument?

```
<arguments>
    <argument name="view_model" xsi:type="object">Magento\Checkout\ViewModel\Cart</argument>
</arguments>

```

If it doesn't have this argument, adding it in your custom xml file should solve your issue (don't forget to flush the cache).

If it solved your issue, please close this ticket, this isn't really considered a bug.
When working on a Magento upgrade you should always double check your custom theme and make sure it's compatible with the latest code.

Good luck! 🙂

**Comment by jpillai88** [comment]
This is block is present.
This is not theme related because ,in magento luma theme also show this error.

**Comment by hostep** [comment]
Hmm, and is some custom module adding this block through php code maybe?

You'll need to debug a bit, it sounds like the [`$block->getViewModel()` call](https://github.com/magento/magento2/blob/2.4.2-p1/app/code/Magento/Checkout/view/frontend/templates/cart/form.phtml#L59) returns `null` in your specific case, why that happens is up to you to figure out.

Pretty sure this works fine in a vanilla Magento installation, but if you have evidence that it also happens in a vanilla installation, then let us know! 🙂

**Comment by engcom-Alfa** [comment]
Hi @jpillai88

I tried below documents to upgrade the magento 2.3.x to magento 2.4.2.
https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html

I can’t reproduce the issue.

**Comment by jpillai88** [comment]
I updated the magento successfully,pages are loaded correctly.
I have issue with checkout page.

**Comment by jpillai88** [comment]
Hi ran the setup:upgrade command
It show this message 
Running data recurring...Reading /home/magento/magento2_staging/composer.json
Loading config file /home/magento/magento2_staging/var/composer_home/config.json
Loading config file /home/magento/magento2_staging/var/composer_home/auth.json
Loading config file /home/magento/magento2_staging/composer.json
Loading config file /home/magento/magento2_staging/auth.json
Reading /home/magento/magento2_staging/auth.json
Reading /home/magento/magento2_staging/var/composer_home/composer.json
Loading config file /home/magento/magento2_staging/var/composer_home/config.json
Loading config file /home/magento/magento2_staging/var/composer_home/auth.json
Loading config file /home/magento/magento2_staging/var/composer_home/composer.json
Loading config file /home/magento/magento2_staging/var/composer_home/auth.json
Reading /home/magento/magento2_staging/var/composer_home/auth.json
Reading /home/magento/magento2_staging/vendor/composer/installed.json
Reading /home/magento/magento2_staging/composer.lock
Checking for "magento/composer-root-update-plugin: 1.1.2" for the Web Setup Wizard...
Reading /home/magento/magento2_staging/var/vendor/magento/composer-root-update-plugin/composer.json
Loading config file /home/magento/magento2_staging/var/composer_home/config.json
Loading config file /home/magento/magento2_staging/var/composer_home/auth.json
Loading config file /home/magento/magento2_staging/var/vendor/magento/composer-root-update-plugin/composer.json
No Web Setup Wizard update needed for magento/composer-root-update-plugin; version 1.1.2 is already in /home/magento/magento2_staging/var

Is there any issue?

**Comment by iphigenie** [comment]
Hi @jpillai88 what you posted above looks normal 

Do you have any extensions/modules involved in cart, minicart or checkout? especially one that is perhaps older?

**Comment by jpillai88** [comment]
Now we fixed above error now show another error.

Error: Call to undefined method Magento\Catalog\Model\Layer\CategoryFactory::getState() in /home/magento/magento2_staging/app/code/Mirasvit/Seo/Service/StateService.php:132 Stack trace: #0 /home/magento/magento2_staging/app/code/Mirasvit/Seo/Observer/Canonical.php(211): Mirasvit\Seo\Service\StateService->isNavigationPage() #1 /home/magento/magento2_staging/app/code/Mirasvit/Seo/Observer/Canonical.php(186): Mirasvit\Seo\Observer\Canonical->getCanonicalUrl() #2 /home/magento/magento2_staging/app/code/Mirasvit/Seo/Observer/Canonical.php(527): Mirasvit\Seo\Observer\Canonical->setupCanonicalUrl() #3 /home/magento/magento2_staging/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Mirasvit\Seo\Observer\Canonical->execute() #4 /home/magento/magento2_staging/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #5 /home/magento/magento2_staging/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #6 /home/magento/magento2_staging/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #7 /home/magento/magento2_staging/vendor/magento/framework/App/Action/Plugin/EventDispatchPlugin.php(135): Magento\Framework\Event\Manager\Proxy->dispatch() #8 /home/magento/magento2_staging/vendor/magento/framework/App/Action/Plugin/EventDispatchPlugin.php(84): Magento\Framework\App\Action\Plugin\EventDispatchPlugin->dispatchPostDispatchEvents() #9 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Action\Plugin\EventDispatchPlugin->afterExecute() #10 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() #11 /home/magento/magento2_staging/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(23): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins() #12 /home/magento/magento2_staging/vendor/magento/framework/App/Action/Action.php(111): Magento\Cms\Controller\Index\Index\Interceptor->execute() #13 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch() #14 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Index\Index\Interceptor->___callParent() #15 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() #16 /home/magento/magento2_staging/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(32): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins() #17 /home/magento/magento2_staging/vendor/magento/framework/App/FrontController.php(186): Magento\Cms\Controller\Index\Index\Interceptor->dispatch() #18 /home/magento/magento2_staging/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #19 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #20 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #21 /home/magento/magento2_staging/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #22 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() #23 /home/magento/magento2_staging/app/code/Mirasvit/CacheWarmer/Plugin/Debug/OnHitPlugin.php(115): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #24 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch() #25 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}() #26 /home/magento/magento2_staging/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins() #27 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch() #28 /home/magento/magento2_staging/vendor/swissup/module-amp/Plugin/Framework/FrontController.php(48): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #29 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch() #30 /home/magento/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #31 /home/magento/magento2_staging/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #32 /home/magento/magento2_staging/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #33 /home/magento/magento2_staging/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #34 /home/magento/magento2_staging/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #35 /home/magento/magento2_staging/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #36 {main}

**Comment by iphigenie** [comment]
hi @jpillai88 I think you need to make sure your modules are updated, and it the error is still there a ticket with Mirasvit

**Comment by jpillai88** [comment]
Issue still exist

**Comment by hostep** [comment]
@jpillai88: as mentioned above by @iphigenie, it sounds like the Mirasvit_Seo module is now causing issues, try contacting them or updating their module to the latest version.

Unless you can proof that one of the issues you have is a core Magento bug, it's not necessary to keep commenting over here in github.
But if you want more help from others, it's probably better to use https://magento.stackexchange.com/ or https://community.magento.com/

Good luck! 🙂

**Comment by hareshpatel** [comment]
same issue how can resolve plz ler me know
