### ISSUE TITLE
Mailchimp module not working with Magento 2.4

### ISSUE THREAD

**Issue by stjohnkrog11** [magento/magento2#33057]
### Preconditions (*)

1. Magento 2.4
2. php 7.4

### Steps to reproduce (*)

1) I have downloaded Mailchimp for Magento 2.4 and manually installed it. I then run the command php bin/magento setup:upgrade and i am getting the following error in console(Shown below). I have removed it and it works fine. 

I am new to this so if any more information is needed please let me know.

### Expected result (*)

1. For it to run.
2.

### Actual result (*)

1.  ![image](https://user-images.githubusercontent.com/84202377/119127311-1646d400-ba2c-11eb-9786-2633820fc4a8.png)
2.
`s***@laptop-3490 p*** % php bin/magento setup:upgrade
Cache types config flushed successfully
Warning: DOMXPath::query(): Invalid predicate in /Users/s***/Projects/p***/vendor/magento/framework/Config/Dom.php on line 336

In ErrorHandler.php line 61:

Warning: DOMXPath::query(): Invalid predicate in /Users/s***/Projects/p***/vendor/magento/framework/Config/Dom.php on line 336`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- not sure what is required here

**Comment by engcom-Alfa** [comment]
HI @stjohnkrog11 
Kindly specify what version of the Mailchimp extension are you trying

**Comment by stjohnkrog11** [comment]
it was

**Comment by engcom-Echo** [comment]
Hi @stjohnkrog11 ,

We are not able to reproduce the issue based on your inputs . Can you kindly try to re-produce the issue on latest 2.4-develop branch . Also please specify some elaborate steps to re-produce the same like mailchimp version number etc.

**Comment by malikt** [comment]
Faced the same issue, and found a typo in `Ebizmarts/MailChimp/etc/events.xml` in the observer name of the `'newsletter_subscriber_save_before'` event.
change the below set of lines:
`<event name="newsletter_subscriber_save_before">
        <observer name="'mailchimp_newsletter_subscriber_save_before" instance="\Ebizmarts\MailChimp\Observer\Subscriber\SaveBefore" />
    </event>`
with
```
<event name="newsletter_subscriber_save_before">
        <observer name="mailchimp_newsletter_subscriber_save_before" instance="\Ebizmarts\MailChimp\Observer\Subscriber\SaveBefore" />
    </event>
```
