### ISSUE TITLE
Encrypted fields issue - PayPal Payflow

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#3305]
With PayPal Payflow gateway we are receiving the following error.
The PayPal gateway rejected the request. User authentication failed

We contacted the PayPal dev team for assistance and they tried their own credentials without success.  

After diving into their logs they verified that the USER and PWD fields are being sent as garbage special characters : `ª¤ó

Ideas?

Environment: php 7.02, magento 2.0.2

**Comment by alena-marchenko** [comment]
Hi,

internal ticket MAGETWO-48387 is already created for this issue

**Comment by alena-marchenko** [comment]
The issue is already resolved and delivered to develop branch.

**Comment by KrystynaKabannyk** [comment]
Hello @caesarcxiv, this issue has been fixed in the 2.0.7 patch release. Thanks for reporting the issue! If you have additional questions or proposals you are welcome to create another one.

**Comment by beatdemon** [comment]
Hello, I seem to be having a very similar issue but with version 1.9.3.9 of Magento CE. Is anyone aware of this? Thank you for any help you can offer.
