### ISSUE TITLE
Magento 2.4.2 Wrong store in UpdateItemQty Controller

### ISSUE THREAD

**Issue by ronakchauhan** [magento/magento2#33056]
### Preconditions (*)
1. Magento 2.4.2
2. PHP 7.3.24
3. SQL: mariadb:10.4
4. Nginx: 1.16 

### Steps to reproduce (*)

1. Add items to cart
2. Update Item quantity
3. Press update quantity button 
4. Ajax controller will be called (vendor/magento/module-checkout/Controller/Cart/UpdateItemQty.php)
5. Inject StoreManagerInterface to get current store value
6. Print current store using `echo $this->storeManager->getStore()->getCode();`

### Expected result (*)

1.  Current store is en-int so when controller UpdateItemQty is being called current store should be fetched
2. same thing should be happened in plugin as well.
3. I am trying to add custom cart quantity restriction with custom error which contains current items count.
4. Instead error message display in english language as per current store it just translate error message into default store de-de.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/8565366/119126773-c0762a00-ba33-11eb-8329-469dfbcc0a2e.png)
2. Current store is en-int which has en_US language but on controller it fetches default de-de store.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ronakchauhan** [comment]
Issue: Confirmed

**Comment by engcom-Golf** [comment]
@ronakchauhan : Please share the requested snapshot for better clarity.
Magento Admin > Click Store > Settings > All Stores.

**Comment by engcom-Golf** [comment]
@ronakchauhan Can you please share the requested Stores?

**Comment by engcom-Golf** [comment]
@ronakchauhan As you are not responding, It seems this issue has been already resolved. Assuming this, Closing the Issue. If still Issue persist, please re-open the same ticket.
