### ISSUE TITLE
`categoryList` GraphQL query is not returning same categories backend order

### ISSUE THREAD

**Issue by MeeGz** [magento/magento2#33065]
### Preconditions (*)

1. Magento Version 2.4.2 or Magento 2.4-develop without sample data
2. Create 2 categories (cat 1, cat 2) under default category
3. Create 1 category (cat child) under cat 2
<img width="231" alt="Screen Shot 2021-05-24 at 2 19 39 PM" src="https://user-images.githubusercontent.com/15185278/119347082-4ea01980-bc9b-11eb-82e8-e483f1a1cc98.png">

### Steps to reproduce (*)

1. run this graphql query 
```graphql
{
  categoryList {
    children {
      name
      children {
        name
      }
    }
  }
}
```

### Expected result (*)

1. default category, cat 1 comes before cat 2
Same as Luma categories order:
<img width="340" alt="Screen Shot 2021-05-24 at 2 22 35 PM" src="https://user-images.githubusercontent.com/15185278/119347213-81e2a880-bc9b-11eb-81c3-e74402a55753.png">

### Actual result (*)

1. default category, cat 2 comes before cat 1
<img width="1440" alt="Screen Shot 2021-05-24 at 2 20 13 PM" src="https://user-images.githubusercontent.com/15185278/119347147-64adda00-bc9b-11eb-94b1-7b5bd099f9d6.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MeeGz** [comment]
@magento give me 2.4-develop instance

**Comment by MeeGz** [comment]
It is working on develop instance.

But I have tried to install v2.4.2-p1 with no sample data and the issue reproduced locally again.

**Comment by MeeGz** [comment]
@magento give me 2.4.x

**Comment by MeeGz** [comment]
@magento give me 2.4.x instance

**Comment by LucasCalazans** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @MeeGz,

 Unfortunately, I can't reproduce the issue. i followed the provided steps and preconditions. Please find the attached Screenshot for the same.
<img width="1440" alt="Screenshot 2021-05-27 at 5 16 36 PM" src="https://user-images.githubusercontent.com/60198022/119821389-22d99980-bf10-11eb-815c-2b62a9fc3551.png">

If you have still issue then provide me the reproducible steps. make sure graphql is not providing the sorting for categorylist.

**Comment by MeeGz** [comment]
Hi there,
Kindly check this with a fresh instance of magento 2.4.2 without any sample data installed.

I have created this hypernode trial instance (you can use it for example for 14 days) without any third parties installed, Only disabled the `Magento_TwoFactorAuth` module to be able to login.
<img width="1103" alt="Screen Shot 2021-05-30 at 3 18 39 PM" src="https://user-images.githubusercontent.com/15185278/120105691-53ad0f00-c15a-11eb-80e9-01514730dd3f.png">

Kindly find admin credentials below:
Magento username: admin
Magento password: PHcEDtt2psu30TlaNy5cA3Yl8bpIe6KF
Magento backend URL: http://categorylist.hypernode.io/categorylist_admin


I have created the same category structure 
<img width="1437" alt="Screen Shot 2021-05-30 at 3 15 44 PM" src="https://user-images.githubusercontent.com/15185278/120105605-ebf6c400-c159-11eb-9aa5-c934a3d51589.png">

and it is okay on luma
<img width="590" alt="Screen Shot 2021-05-30 at 3 16 21 PM" src="https://user-images.githubusercontent.com/15185278/120105626-003ac100-c15a-11eb-8a92-5f86b0a7f537.png">

but not okay on graphql
<img width="1439" alt="Screen Shot 2021-05-30 at 3 16 41 PM" src="https://user-images.githubusercontent.com/15185278/120105632-0af55600-c15a-11eb-8493-25df6c8b4b2f.png">

**Comment by magento-engcom-team** [comment]
@engcom-Lima Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Lima Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Lima** [comment]
@MeeGz It is reproduced without sample data installed
![image-2](https://user-images.githubusercontent.com/60198022/120202639-761b5700-c244-11eb-8e62-461dbc0203d7.png)
![image](https://user-images.githubusercontent.com/60198022/120202665-7b78a180-c244-11eb-8a1a-1ede0679725d.png)

**Comment by MeeGz** [comment]
I think the issue has not been confirmed yet as it gets automatically unconfirmed.

Kindly confirm it to get it into Magento dev queue to implement the solution ASAP.

Thanks in advance.

**Comment by magento-engcom-team** [comment]
@engcom-Lima Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by MeeGz** [comment]
@engcom-Lima this issue has not been confirmed yet

**Comment by MeeGz** [comment]
@engcom-Lima any updates ?

**Comment by MeeGz** [comment]
@engcom-Lima ??

**Comment by engcom-Alfa** [comment]
Hi @MeeGz 

Tried to reproduce in **Magento 2.4-develop** version, and unable to successfully reproduce it. Below are the steps I followed.

1. Installed a fresh Magento 2.4-develop instance especially to test this case, where didn't install the sample data at all.
 

2. Just created one customer in the front end (This is required to request the query using customer token)


3. Admin> Created 2 categories exactly as given in the below screenshot
![image](https://user-images.githubusercontent.com/51679138/135621260-13ee9a5d-51cc-4ff1-b67e-d011c974cfe7.png)


4. Retried the GraphQL customer auth token first and then requested the below query for the category list
![image](https://user-images.githubusercontent.com/51679138/135621426-a95aaf3a-f2ce-4510-abdf-0f0546eb95bc.png)


5. Checked the response and didn't find the issue as described above.


Hope I have followed correct steps to reproduce as per my understanding.
- If there is any change required in the above execution steps, please correct me!

Note: If the issue is reproducible in the older versions only, kindly upgrade to the latest version and then give a try to reproduce the same.

Thanks for your contribution and collaboration!
