### ISSUE TITLE
Magento 2.3.5 Product Export Error | Missing Entity Attributes

### ISSUE THREAD

**Issue by yoritomoto** [magento/magento2#33062]
### Summary (*)

Issue: Entity attributes are not showing up for CSV product export.

General Information: 
Currently going to System -> Data Transfer -> Export | Entity Type: Products, Export File Format: CSV.
I tried the Improved Export but ran into a different error: A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

Error Message: Please correct the data sent value.

Environment: Magento 2.3.5

### Examples (*)

https://github.com/magento/magento2/issues/26925
https://magento.stackexchange.com/questions/219147/entity-attributes-not-listed-when-exporting-products-magento2
https://github.com/magento/magento2/issues/17320

### Proposed solution

In [this thread](https://github.com/magento/magento2/issues/26925) user @maniramav says he was able to fix this issue in this message: 

_The issue have been fixed. The issue cased be attributed created during magento update. The particular attribute was created using SQL. That was causing the issue. Once I deleted those attribute and recreated in magento admin page fixed the issue._

However, I and a few other people are struggling to interpret this message and recreate the solution.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [S0] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @yoritomoto 
I have retried to export the CSV file with more big data where the products with 40k+ records.
I am not able to reproduce the issue with 4.2-develop. Kindly upgrade yourself to the latest version and let me know if you are able to reproduce.
Below is the working screenshot.
<img width="925" alt="ExportWith40kProductsWorking" src="https://user-images.githubusercontent.com/51679138/119815510-3fbe9e80-bf09-11eb-83cb-507e1dcc6eb6.PNG">

**Comment by engcom-Alfa** [comment]
As there is no response in last ~14 days, the issue is being closed.
If you face issue on this again in the latest Magento version, kindly raise a new ticket.
Thanks

**Comment by dazz397** [comment]
I am having this same issue after upgrading from 2.3.5-p2 to 2.4.2-p1. I checked my eav_attribute table and removed anything the upgrade added and nothing changed. Please let me know if you have any updates.
