### ISSUE TITLE
Not show customer name, welcome message after enable advanced js bundling

### ISSUE THREAD

**Issue by arhmart** [magento/magento2#33068]
### Summary of the issue
After advanced js bundling, the **welcome message** (**customer name** after login), and the **item qty** of wishlist on the menu **not display on mobile device**. But they work fine on PC and also work fine without advanced js bundling. The picture below shows the display of the mobile device, there are no welcome message before login, and the customer name and wishlist quantity is not displayed after login.

![1](https://user-images.githubusercontent.com/84454905/119444116-53c59d00-bd5d-11eb-81c7-c86d10588585.png)
![2](https://user-images.githubusercontent.com/84454905/119444122-545e3380-bd5d-11eb-90f1-9481d0511abf.png)

**Information on your environment**
Magento 2.4.2-p1 luma (I have this issue on magento 2.4.1 version, and the problem still exists after upgrading to magento 2.4.2-p1. The problem was reproduced on the other test site of magento 2.4.2.)

Nginx 1.18
PHP 7.4
Mysql 8
Redis
Varnish
Elasticsearch
NPM r.js

**Steps to reproduce**
All steps are according to the Magento advanced js bundling guide.
https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html

After enable advanced js bundling, no other problems have been found for the time being, except that the welcome message, customer name and wishlist qty are not displayed.

**Expected and actual results**
Display the welcome message, customer name and wishlist qty after login like below:

![3](https://user-images.githubusercontent.com/84454905/119444144-5d4f0500-bd5d-11eb-8612-08c630b08157.png)
![4](https://user-images.githubusercontent.com/84454905/119444149-5e803200-bd5d-11eb-8374-0910b1691f8e.png)

**Comment by engcom-Golf** [comment]
@arhmart Tested on mobile version of a website by using Dev tools. Issue is not reproducible. So considering this, I am closing this Issue.  If still issue persist, please re-open the same ticket with more updates. For ex. mobile model etc.
