### ISSUE TITLE
Error displaying price and summary on bundle product without input

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#3306]
The price calculation is wrong and the summary doesn't display correct on bundled product when you have an option configured to be rendered without an input like this example:
![bundle-error](https://cloud.githubusercontent.com/assets/5768842/12851031/0acf6aa8-cc28-11e5-97d5-80cc447736b4.png)

It works ok if you configure so that all options have an input of some kind for example like this:
![bundle-ok](https://cloud.githubusercontent.com/assets/5768842/12851171/bee54f6c-cc28-11e5-85ab-1088a25ef5ed.png)

I have this issue on 2.0.2 and 2.0.0-rc

**Comment by mikeweis** [comment]
@thomasnordkvist Hmm, I could not recreate this on the very latest code branch.  However my bundle item options always give me the ability to check "user defined" ... in your screen shots, for the first two options, you don't show that ability.  Am I missing something?  Thanks.

**Comment by thomasnordkvist** [comment]
@mikeweis In my versions 2.0.2 and earlier.
To get the error you need to have two "inputless" options on the storefront.
If you only have one option without input the calculation ok.

To get rid of the "user defined" i set the input type to Checkbox.
To make the storefront skip the rendering of an input to the option i check required for the first two options.
Then in the storefront the first two options will always be included in the bundle.
With this setup the presented price calculation to the right stops working.
If i uncheck "required" it works ok.

It probably has something to do with the fact that there are no input attached to the first two options.

/Thomas

**Comment by tang-yu** [comment]
@thomasnordkvist , thanks for raising this issue. I have created an internal ticket MAGETWO-49975 to track this issue. I also noticed that this issue does not exist on the latest code (develop branch) on github.

**Comment by mslabko** [comment]
Hello @thomasnordkvist,

Issue is not reproduced on develop branch. On stable release fix will be available in 2.1 version.
