### ISSUE TITLE
"Loading" attribute is not allowed on img tag in blocks Wysiwig editor

### ISSUE THREAD

**Issue by martasiewierska** [magento/magento2#33063]
### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

1. Create a block and insert image in Wysiwyg editor. 
2. Add manually loading="lazy"

### Expected result (*)

1. Block is saved without a warning as loading is a valid attribute on img HTML element. (https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading , https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes) 
2.

### Actual result (*)

1. Blocks is saved but there is a warning: "Temporarily allowed to save HTML value that contains restricted elements. Allowed HTML attributes for tag "img" are: class,width,height,style,alt,title,border,id,src"
2.
<img width="1112" alt="loading" src="https://user-images.githubusercontent.com/7559952/119310064-87c29480-bc6f-11eb-86b3-bea6293110a6.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
message throw from this one class
Magento\Framework\Validator\HTML\ConfigurableWYSIWYGValidator

I'm not sure why code base duplicated  twice declare `DefaultWYSIWYGValidator` in di.xml 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/etc/di.xml#L261
https://github.com/magento/magento2/blob/2.4-develop/app/etc/di.xml#L1852

**Comment by engcom-Alfa** [comment]
HI @martasiewierska 
I have tried reproducing it in 2.4-develop and unable to reproduce, it is working perfect.
**
https://user-images.githubusercontent.com/51679138/121342883-ba42e180-c93f-11eb-8512-e441385802fe.mp4
**
**Kindly try to reproduce in the latest version and possibly share a screen record for better understanding of reproducible steps.**

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

**Comment by bsdonaldson** [comment]
@engcom-Alfa based on your video your adding an img tag as text rather than HTML. If you look at the first screenshot provided by martasiewierska they aren't using the HTML Editor. This issue still happens with the following steps:

1. Create a block and hide editor.
2. Insert image and manually add loading="lazy" (eg. `<img src="https://via.placeholder.com/350x150" alt="Example image" loading="lazy">` )
