### ISSUE TITLE
Importing table rates not working when using S3 storage adapter

### ISSUE THREAD

**Issue by apachler** [magento/magento2#33072]
### Preconditions (*)
1. Magento 2.4.2
2. PHP 7.4
3. Activated S3 storage adapter in Magento

### Steps to reproduce (*)
1. Export the tablerates.csv in Backend
2. Import the exported tablerates.csv in Backend

### Expected result (*)
1. Uploaded tablesrates.csv file is processed.

### Actual result (*)
1. File "https://[bucket].s3.eu-central-1.amazonaws.com/[prefix]/tmp/phpLjGmHf" not found.

### Details
It seems there is a problem with the "uploadAndImport" method in "/app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate.php".
It gets the path of the uploaded file from the $_FILES global variable and passes it to "$this->filesystem->getDirectoryReadByPath($dirName)" in the "getCsvFile" method.

Since the S3 storage adapter is active, this call is returning a location on the S3 bucket but the file is not existing there.
The file exists on the local filesystem located in the path defined by the PHP var "upload_tmp_dir".

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42520` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
