### ISSUE TITLE
Struggling to understand the magento api oauth process

### ISSUE THREAD

**Issue by datacubed** [magento/magento2#33071]
Im not sure where to post this, as I couldnt find a general support section. No email address or "contact us" anywhere inside the Magento admin section.

We've build a bunch of different oauth2 based API integrations into things like Google Adwords, Facebook, Doubleclick etc...

But we're struggling to understand what exact Magento wants/needs from us.

We have a client who's given us Admin access, and we've created an Intergration with some API access. 
As mentioned here : https://devdocs.magento.com/guides/v2.4/get-started/bk-get-started-api.html

We log in at: https://www.client.com/admin/admin/dashboard/index/key/<token-id>/

Our understanding, based on previous experiences, was that now with the key, secret, and token, we could make requests to Magento on behalf of our client. 
We'd like to able to pull customer order data: https://magento.redoc.ly/2.3.7-admin/tag/orders 

We tried building an api request via our python code base going to:
https://www.client.com/admin/rest/default/V1/orders

But this hasnt worked. I assume we're doing this very wrong. Can anyone provide some help or any ideas on what we should be doing?

Cheers

**Comment by datacubed** [comment]
Im sorry I dont know what this means:
_Please make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:_

**Comment by engcom-Echo** [comment]
Hi @datacubed ,

Please refer the REST API documentation here 
https://magento.redoc.ly/

Hopefully this would answer all your queries regarding the same. Closing this issue.

Thanks
