### ISSUE TITLE
USD $ sign is missing for price after advance search with price

### ISSUE THREAD

**Issue by renard123** [magento/magento2#33081]
USD $ sign is missing for price after advance search with price

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
1. Advanced Search page 
2. Search with any price range

### Expected result (*)
![image](https://user-images.githubusercontent.com/50658701/119664422-eeeb6f00-be50-11eb-87d5-18891fe95769.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/119664472-fca0f480-be50-11eb-9563-e221afaec476.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42450` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this
