### ISSUE TITLE
Rename confusing store select labels at admin login as customers related config and modal window

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#33094]
Due to discussion at https://github.com/magento/magento2/issues/29101 customer login work per Store.
Customer login modal window show **Store View** as label for select box with Stores list. Wrong title little bit confuse.

**What need to do:**
1. Rename **Store View** to **Store** at customer login modal window
2. Rename **Store View To Login To** to **Store To Login** at Stores -> Configuration -> Customers -> Login as Customer

### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Set `Store View To Login To` to `Manual Selection` in Stores -> Configuration -> Customers -> Login as Customer
2. Go to Customer edit page and click **Login as Customer**

### Expected result (*)

1. Store select label is **Store**

### Actual result (*)

![118659506-aba85500-b7ed-11eb-9df4-4c618e87735d](https://user-images.githubusercontent.com/1129623/119971040-26752b00-bfb9-11eb-8d8c-92e4581b156b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42492` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vovsky** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#33097 by @vovsky in 2.4-develop branch
Related commit(s):
 - [4c26dfa6b6dd0e58a159512b4311782bed98d7a8](https://github.com/magento/magento2/commit/4c26dfa6b6dd0e58a159512b4311782bed98d7a8)
 - [ae6a2a8ca7c0ee500c0915e3e523c45a993a952a](https://github.com/magento/magento2/commit/ae6a2a8ca7c0ee500c0915e3e523c45a993a952a)

The fix will be available with the upcoming 2.4.3 release.
