### ISSUE TITLE
Not showing error message when create attribute at product page

### ISSUE THREAD

**Issue by dangminh** [magento/magento2#33099]
Admin is a required field when create attribute with type is swatch but not showing message when click save button.
### Preconditions (*)

1. Magento 2.4.2EE
2.

### Steps to reproduce (*)

1. Admin -> Catalog -> Product -> Add new product -> Add Attribute -> Create New Attribute
2. Fill Attribute Label -> Choose  Catalog Input Type for Store Owner is Vitual Swatch -> Manage Swatch -> Add Swatch -> Fill Default Store View -> Save Attribute
3. 

### Expected result (*)

1. Display error message: Admin is a required field in each row

### Actual result (*)

1. Not thing happened.
2. 
![image](https://user-images.githubusercontent.com/9212967/120062326-cdc29280-c08b-11eb-91ae-19264fe6c290.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42510` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @engcom-Echo, can you provide/update the description with more details on the steps to reproduce? Especially if there is a happy path that the user will be able to create a new attribute.

Also, is the user stuck on this page? What does the user need to do in order to get back to the application?

Thanks!

**Comment by engcom-Echo** [comment]
hi @gabrieldagama ,

Yes, the user does get stuck in this page if he selects Visual Swatch as Attribute Type , and does not fills the Admin label ,no error message pop's up saying that 'Admin is required' , neither Admin label is mentioned as required field .If we check the response on network only then we can see api is throwing error stating 'Admin is required' . A happy flow would be to also fill data in admin label when selecting Visual Swatch as 'Attribute Type'.
I will also update the description to add more details in it.

Thanks

**Comment by sdzhepa** [comment]
@engcom-Echo 

Please update/edit description with information from your comment https://github.com/magento/magento2/issues/33099#issuecomment-863073318



cc @gabrieldagama

**Comment by Usik2203** [comment]
@magento I am working on this
