### ISSUE TITLE
Error when I choose Weight = no

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3309]
Hello guys. New to Github, New to M2, New to bugs.

When I add a new "Configurable product" I need to choose "weight". Now, since I dont have weight for this product, I choose "Weight" = No.

When I create configurations for this product, i see it generates VIRTUAL products instead of SIMPLE products. The problem is I want SIMPLE products, even I do not have a weight (!).

After I load the product again I See  "Weight" =" yes", I try to save it as "NO" but it always keep showing "yes".

Now, the problem with Virtual products that are generated, is: when I go to checkout selection  these products it does not offer me to enter shipping address. So this issue is critical for me. I can not make SIMPLE products using a "Configurable product" because I do not have a weight?

I hope anyone can help me and confirm it is a bug.
Thank you!

**Comment by pynej** [comment]
Ok, So i partly figured out how to get around this by adding a weight to my configurable items, But I can't seam to fix the exiting items.  I can to a mass edit to add a weight to the child configurations but this doesn't convert them back to simple items.  If iI go into items one at a time and cgive them a weight and select product_has_weight then they convert to a simple item and work as expected.  Not sure if there is a way to change all the child itmes to simple products without rebuilding all the configurations.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Error-when-I-choose-Weight-no/idi-p/45329).
