### ISSUE TITLE
Can't import customer

### ISSUE THREAD

**Issue by ruibinben** [magento/magento2#331]
Magento dev-44
When I  import customer data,then check data,
on the csv file,the first column is email
the error likes this:Can not find required columns: email!!
on the csv file,the first column is  _website
the error likes this:Can not find required columns: _website!!

On the csv file,have the two columns: email    _website

**Comment by ghost** [comment]
Hey Guys, I know this is old, but I experiencing the same issue here with Magento 2.2.3 any ideas?

> We can't find required columns: _website.


BTW: I've saved my CSV with UTF-8 Encoding.

thanks!
