### ISSUE TITLE
Unable to install Magento 2.0.2 on WHM Cpanel 

### ISSUE THREAD

**Issue by vikkymedia** [magento/magento2#3311]
I'm unable to install Magento 2.0.2 on WHM CPanel, it is stuck at 0%,

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Why im stuck at 0%.

**Comment by vikkymedia** [comment]
![checklist](https://cloud.githubusercontent.com/assets/7601119/12865686/9c2895e0-ccd9-11e5-9f3e-85dcf4c2b07a.png)

**Comment by mazhalai** [comment]
Check if your [max_execution_time](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_70pct.html) setting is as [recommended](https://github.com/magento/magento2/blob/develop/.htaccess#L67). also see #3332

**Comment by mazhalai** [comment]
@vikkymedia  closing as non-responsive.
