### ISSUE TITLE
Uncaught TypeError: Cannot read property 'swatchImage' of undefined

### ISSUE THREAD

**Issue by cha80** [magento/magento2#33110]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1.  Uncaught TypeError: Cannot read property 'swatchImage' of undefined
2.
![image](https://user-images.githubusercontent.com/56351661/120271816-97c91c80-c2de-11eb-9c91-19f50e765b0c.png)

### Actual result (*)

1.  
![image](https://user-images.githubusercontent.com/56351661/120408314-5b9ac800-c381-11eb-9df3-ae0bf84ca441.png)

 when i select visual swatch and upload a image file it's happen this error

2.

---
 Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cha80** [comment]
magento 2.2.11 version

**Comment by krishprakash** [comment]
Hi @cha80. Kindly update all the necessary details as per issue reporting guidelines 
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by cha80** [comment]
> Hi @cha80. Kindly update all the necessary details as per issue reporting guidelines
> https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
magento 2.2.11 ce vesion
it's all detail

**Comment by krishprakash** [comment]
Hi @cha80. In the current stage, it is not clear what the problem and what functionality is broken.
Steps to reproduce, actual and expected result, screens that illustrate problem will help a lot.
Feel free to reopen the ticket once you update all the details as per issue reporting guidelines
Thanks

**Comment by cha80** [comment]
when i upgrade magento it's disppear
