### ISSUE TITLE
<font> node not adding proper attributes when using css font with query string.

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [magento/magento2#33121]
` <font src="fonts/customicons/icomoon.ttf?abcdef" />` in xml is not adding attributes like `as="font"` and `crossorigin` when font-face in css points to version font using query string  i.e. `?abcdef`.

```
@font-face {
  font-family: 'icomoon';
  src:  url('../fonts/customicons/icomoon.eot?abcdef');
  src:  url('../fonts/customicons/icomoon.eot?abcdef#iefix') format('embedded-opentype'),
    url('../fonts/customicons/icomoon.ttf?abcdef') format('truetype'),
    url('../fonts/customicons/icomoon.woff?abcdef') format('woff'),
    url('../fonts/customicons/icomoon.svg?abcdef#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

```

and thus **preload** is not working as per psi google guidelines.

Thanks.

**Comment by engcom-Echo** [comment]
Hi @Shashank-Bhatt1 ,

We are not able to re-produce the issue based on given inputs. Kindly elaborate the steps to re-produce and expected/actual results.

Thanks

**Comment by Shashank-Bhatt1** [comment]
Hi @engcom-echo, please find these steps to reproduce.

- Add font via newly added font node in default_head_blocks.xml file in the head of the page.
- Keep src of the font node with some querystring for version number i.e. ?abcdef
- Try to see actually generated link element in the head
 
Expected result
- Newly generated link should have preload attribute with other attributes like `crossorigin=annonymous` and `as=font`.

Actual Result
- Actual rendered link element has no preload and as attributes.

**Comment by engcom-Delta** [comment]
There is no update from reporter and it has been ~14 days. Hence , closing the ticket.
if required kindly open new issue or re-open existing ticket.
