### ISSUE TITLE
Class Magento\Framework\DB\QueryBuilderFactory does not exist after migration from Magento 1.8.1

### ISSUE THREAD

**Issue by algostore** [magento/magento2#3312]
After successful migration from 1.8.1 to m2.0.2 I cannot get access to products in backend, because i am getting this error "Class Magento\Framework\DB\QueryBuilderFactory does not exist". Even I see my products in database. 

M2 installed from git branch master and native Magento migration tool

PHP 5.6
Mysql: 5.6

**Comment by palamar** [comment]
@algostore 
We have separate repositories for migration tools:
- https://github.com/magento/data-migration-tool
- https://github.com/magento/code-migration
  please address issues related to migration to one of migration tools
