### ISSUE TITLE
when i create shippment it's display created but it's not display but invoice can see 

### ISSUE THREAD

**Issue by cha80** [magento/magento2#33131]
### Preconditions (*)
magento 2.2.11 bug
1.
![image](https://user-images.githubusercontent.com/56351661/120570461-c9f78d00-c44a-11eb-8865-76a54f7b7ebf.png)

![image](https://user-images.githubusercontent.com/56351661/120570368-8ef55980-c44a-11eb-93d9-e3c7971b9259.png)
![image](https://user-images.githubusercontent.com/56351661/120570396-a3395680-c44a-11eb-9cfc-3da36f8a004c.png)

2.

### Steps to reproduce (*)

1.
2.

### mgento version (*)

1.![image](https://user-images.githubusercontent.com/56351661/120748216-fdaee180-c534-11eb-88e5-66ba58e8bf18.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Since magento not deliver patch/fix for 2.2 anymore . So in your case you have to manually fix with your patch or upgrade current magento version to higher version

**Comment by cha80** [comment]
![image](https://user-images.githubusercontent.com/56351661/120586986-18b32000-c467-11eb-9bf5-6ca82c4eaab1.png)

**Comment by cha80** [comment]
magento shipping is not active

**Comment by cha80** [comment]
> Since magento not deliver patch/fix for 2.2 anymore . So in your case you have to manually fix with your patch or upgrade current magento version to higher version
> Is your store running at 2.2.11 currently ?

i use lampp enviroment it's hard to update

**Comment by cha80** [comment]
![image](https://user-images.githubusercontent.com/56351661/120588366-a4c64700-c469-11eb-9e45-1f6b32f64226.png)

**Comment by cha80** [comment]
why i can't change the value

**Comment by cha80** [comment]
> Since magento not deliver patch/fix for 2.2 anymore . So in your case you have to manually fix with your patch or upgrade current magento version to higher version
> Is your store running at 2.2.11 currently ? how to fix

**Comment by cha80** [comment]
> > Since magento not deliver patch/fix for 2.2 anymore . So in your case you have to manually fix with your patch or upgrade current magento version to higher version
> > Is your store running at 2.2.11 currently ? how to fix

@engcom-Alfa. how to fix this problem

**Comment by engcom-Alfa** [comment]
Hi @cha80 
Kindly update to the latest version and give a try on this. It should have been fixed. If you still face issue on the latest version, kindly raise a new issue with proper steps on this.

**Comment by cha80** [comment]
> Hi @cha80
> Kindly update to the latest version and give a try on this. It should have been fixed. If you still face issue on the latest version, kindly raise a new issue with proper steps on this.
it 's hard to upgrade 2.4
