### ISSUE TITLE
Catalog Placeholder doesn't support remote storage

### ISSUE THREAD

**Issue by reevelau** [magento/magento2#33132]
### Preconditions (*)

1. Magento 2.4.2
2. [Config remote storage](https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html)
3. [Config placeholder images](https://docs.magento.com/user-guide/catalog/product-image-placeholders.html) 

### Steps to reproduce (*)

1. curl -v http://localhost:8080/media/catalog/test.jpg

### Expected result (*)

1. Placeholder image should be returned

### Actual result (*)

1. See curl command and log below:

```
>  curl -v http://localhost:8080/media/catalog/test.jpg
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /media/catalog/test.jpg HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Thu, 03 Jun 2021 02:45:44 GMT
< Server: Apache/2.4.38 (Debian)
< X-Powered-By: PHP/7.4.19
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: IE=edge
< Content-Length: 1284
< Content-Type: text/plain;charset=UTF-8
<
File 'https://[s3 bucket name].ap-east-1.amazonaws.com/media/catalog/product/placeholder/default/placeholder.png' does not exists.
#0 /var/www/html/vendor/magento/module-media-storage/Model/File/Storage/Response.php(63): Magento\Framework\File\Transfer\Adapter\Http->send(Array)
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\MediaStorage\Model\File\Storage\Response->sendResponse()
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\MediaStorage\Model\File\Storage\Response\Interceptor->___callParent('sendResponse', Array)
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\MediaStorage\Model\File\Storage\Response\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/html/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php(23): Magento\MediaStorage\Model\File\Storage\Response\Interceptor->___callPlugins('sendResponse', Array, Array)
#5 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\MediaStorage\Model\File\Storage\Response\Interceptor->sendResponse()
#6 /var/www/html/pub/get.php(87): Magento\Framework\App\Bootstrap->run(Object(Magento\MediaStorage\App\Media))
* Connection #0 to host localhost left intact
#7 {main}
```

### Additional Information
Spent some time debugging the issue:

[Placeholder::getPath()](https://github.com/magento/magento2/blob/33242e4b19cf207d7b73f7791ef894b48bb41f8a/app/code/Magento/Catalog/Model/View/Asset/Placeholder.php#L104) returns the s3 bucket URL, i.e. ```https://[s3 bucket name].ap-east-1.amazonaws.com/media/catalog/product/placeholder/default/placeholder.png```. The URL will be referenced in [Response::sendResponse()](https://github.com/magento/magento2/blob/33242e4b19cf207d7b73f7791ef894b48bb41f8a/app/code/Magento/MediaStorage/Model/File/Storage/Response.php#L60) and then be passed to ```Http::send($option)``` function which tests if the file path a 
valid and readable path using native storage functions (is_file, is_readable). When it isn't, the function throws an ```InvalidArgumentException("File '{$filepath}' does not exists.")```.

**Comment by reevelau** [comment]
@magento give me 2.4-develop instance

**Comment by reevelau** [comment]
I cannot config AwsS3 remote storage in the dev instance...

**Comment by engcom-Lima** [comment]
Hi @reevelau

What problem you are facing while config AwsS3 remote storage in the dev instance. It is not environment specific. Please follow the below document.

https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html

**Comment by engcom-Lima** [comment]
Hi @reevelau,

Hoping your issue got resolved because we did not get response from you. Hence closing this ticket.

Thanks for the understanding!

**Comment by reevelau** [comment]
@engcom-Lima Sorry for late response. 

Could you please provide me the instructions to execute "bin/magento" cli command in the dev instance?
