### ISSUE TITLE
Tier Prices are filtered before adjustments

### ISSUE THREAD

**Issue by galanis-a** [magento/magento2#33140]
### Preconditions (*)

1. Magento version 2.4.2
2. PHP 7.4.11

### Steps to reproduce (*)

1. Create a price adjustment calculator for Magento\Catalog\Pricing\Price\TierPrice

### Expected result (*)

1. The $priceList should be filtered, against the finalPrice, after the adjustments.

### Actual result (*)

1. The $priceList is filtered before the adjustments of the calculator. If a tier prices has a lower price than the final prices never reaches the adjustments calculator.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [:heavy_check_mark:] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by george-vlahakis** [comment]
Having the same issue here.

**Comment by engcom-Echo** [comment]
Hi @galanis-a ,

We are not able to re-produce the issue based on your input, can you please specify the steps along with screenshot of your custom code/configuration.

Also request you to test the same on Magento latest version i.e. 2.4-develop

Thanks

**Comment by engcom-Echo** [comment]
Hi @galanis-a ,

We are closing this ticket , as there has been no update on the same.'

Thanks
