### ISSUE TITLE
100% discount Coupon in magento 2

### ISSUE THREAD

**Issue by CFA2021** [magento/magento2#33155]
Preconditions (*)
1. Magento ver. 2.3.4
2.

Steps to reproduce (*)

I am trying to create a coupon that will give the customer a free order. We use Cardknox payment option.
1. New coupon
2. Percent of product price discount
3. Discount amount: 100%
![image](https://user-images.githubusercontent.com/85434022/120919116-9faf0500-c6c0-11eb-9243-cbfd60e875c9.png)
Hi,
I am having an issue regarding coupons in magneto - I tried to create a coupon that will give the customer 100% discount on his order, when trying to place an order with this coupon, the cart shows the correct prices but when trying to checkout I get an error: Payment Method Not Allowed - I am using cardknox for the payment method

Expected result (*)
1. Cart total should be $0
2. Credit card is required for authorization

Actual result (*)
1. The required payment method is not available.
![image](https://user-images.githubusercontent.com/85434022/120919318-9d00df80-c6c1-11eb-8aec-68d2ca1a0ae8.png)

---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by ajijshekh123** [comment]
Hello @CFA2021,

If Your Order Total Amount would be 0, In Checkout, None of the Payment method would be displayed and Only "No Payment Information Required" payment options would be displayed.

![image](https://user-images.githubusercontent.com/24711761/121184668-f19f8880-c882-11eb-9767-e475d802f505.png)

![image](https://user-images.githubusercontent.com/24711761/121185578-d3865800-c883-11eb-885a-41870fbb8103.png)


Thanks.

**Comment by ajijshekh123** [comment]
Hello @CFA2021 ,
If you have face this issue again you can reopen it with proper details.
Thanks.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance
