### ISSUE TITLE
paypal-express-checkout is not work in graphql api

### ISSUE THREAD

**Issue by hawkcraw** [magento/magento2#33157]
### Preconditions (*)

1. Magento ver. 2.4.0-p1
2. Ubuntu 18.04.3
3. PHP 7.3.27

### Steps to reproduce (*)
1. Follow this API step：https://devdocs.magento.com/guides/v2.4/graphql/payment-methods/paypal-express-checkout.html
2. createEmptyCart
3. addSimpleProductsToCart
4. createPaypalExpressToken
5. setPaymentMethodOnCart
  This step shows an error : The shipping address is missing. Set the address and try again
  I think this step should be to automatically get the shipping address and fill it from paypal instead of manually setting the shipping address.

### Expected result (*)

1. I think this step should be to automatically get the shipping address and fill it from paypal instead of manually setting the shipping address, because the user has already set the shipping address when paying with paypal

### Actual result (*)

1. setPaymentMethodOnCart show error:  "The shipping address is missing. Set the address and try again"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Lima** [comment]
Hi @hawkcraw

I am working on the ticket, I need some more details regarding the "createPaypalExpressToken"

What payload you are using, Can you please provide me?

**Comment by hawkcraw** [comment]
4. createPaypalExpressToken
`mutation {
  createPaypalExpressToken(
    input: {
      cart_id: "RDSkwThOiADqqmn5xojNXZCcA48EuWnQ"
      code: "paypal_express"
      express_button: true
      urls: {
        return_url: "paypal/action/return.html"
        cancel_url: "paypal/action/cancel.html"
      }
    }
  ) {
    token
    paypal_urls {
      start
      edit
    }
  }
}`

5.setPaymentMethodOnCart
`mutation {
  setPaymentMethodOnCart(input: {
    cart_id: "RDSkwThOiADqqmn5xojNXZCcA48EuWnQ"
    payment_method: {
      code: "paypal_express"
      paypal_express: {
        payer_id: "P47KYL863PXJ4"
        token: "EC-6S68110894138003S"
      }
    }
  }) {
    cart {
      selected_payment_method {
        code
        title
      },
      shipping_addresses {
      firstname
      lastname
      street
      city
      region {
        code
        label
      }
      country {
        code
        label
      }
      telephone
      pickup_location_code
      available_shipping_methods {
        amount {
          currency
          value
        }
        available
        carrier_code
        carrier_title
        error_message
        method_code
        method_title
        price_excl_tax {
          value
          currency
        }
        price_incl_tax {
          value
          currency
        }
      }
      selected_shipping_method {
        amount {
          value
          currency
        }
        carrier_code
        carrier_title
        method_code
        method_title
      }
    }
    }
  }
}`

![image](https://user-images.githubusercontent.com/9996664/121453109-2cb0d180-c9d3-11eb-8697-694f8bfa5e80.png)

**Comment by engcom-Lima** [comment]
Hi @hawkcraw 

It is not an issue. before setPaymentMethodOnCart you should has to setShippingAddressesOnCart first. it is behaviour of system. it is not related to graphql. 

Hence, closing this ticket. Please feel free to raise a new ticket or reopen the same ticket if you have any issue.

Thanks

**Comment by millennialdeveloper** [comment]
What shipping address are we supposed to set via setShippingAddressesOnCart?
The customer sets the shipping and billing address through Paypal, doesn't Magento have access to them?

**Comment by ageffray** [comment]
Any update on this bug ? 
@engcom-Lima it's a real bug, as @millennialdeveloper said address is defined on Paypal not on checkout

**Comment by millennialdeveloper** [comment]
> Hi @hawkcraw
> 
> It is not an issue. before setPaymentMethodOnCart you should has to setShippingAddressesOnCart first. it is behaviour of system. it is not related to graphql.
> 

The whole point of PayPal Express is not to have the user input their address again on the store to speed things up and get it directly from PayPal 🙄 how is it not an issue?

Magento should do better

**Comment by AKALuffy** [comment]
Totally agree the paypal graphql plugin vendor/magento/module-paypal-graph-ql/Model/Plugin/Resolver/SetPaymentMethodOnCart.php:87 

should be set on beforeResolve not afterResolve

**Comment by mpchadwick** [comment]
> It is not an issue. before setPaymentMethodOnCart you should has to setShippingAddressesOnCart first. it is behaviour of system. it is not related to graphql.

Just going to pile on and state that this is not how any one would expect PayPal express to need to work (the shipping info should come from PayPal and shouldn't require to be collected again from the user). We will also try switching to `beforeResolve` in the plugin.

**Comment by dimitriBouteille** [comment]
There is absolutely no reason to have to make a `setShippingAddressesOnCart` when checkout with Paypal Express, the data comes from Paypal. User must not re-enter information.

What is funny is that in the documentation of Magento it is specify to do directly `setPaymentMethodOnCart`: https://developer.adobe.com/commerce/webapi/graphql/payment-methods/paypal-express-checkout/

![Capture d’écran du 2023-01-04 11-09-02](https://user-images.githubusercontent.com/34821762/210532412-4c340032-e7e4-4728-848e-c4058c44b187.png)


----

@AKALuffy @mpchadwick PayPal Express work with `beforeResolve` plugin ?

**Comment by mileandra** [comment]
+1 for this one.

As a temporary workaround I ended up creating a new module, disabling the plugin and setting a preference for Magento\QuoteGraphQl\Model\Resolver\SetPaymentMethodOnCart to a custom resolver that checks for paypal express and then runs the `returnFromPaypal` method before collecting the totals.

Not sure a `beforeResolve` would work fine as the cart is not resolved there yet, but it is crucial that the shipping address is set before `$this->setPaymentMethodOnCart->execute($cart, $paymentData);`. Maybe the paypal graphql module could just provide a custom mutation for the return of the `onApproved` callback that will set the shipping and billing address for express checkouts and could be called prior to `setPaymentMethodOnCart`?
