### ISSUE TITLE
Error after admin login with user that was changed and has incorrect password hash

### ISSUE THREAD

**Issue by michal-balut-accenture** [magento/magento2#33151]
### Preconditions (*)
1. Reproduced on clean Magento 2.4.2 installation, production mode, PHP 7.4.16
2. admin_user account with both reload_acl_flag = 1 AND password with previous hash version (can be manually achieved by changing last password part 3 -> 2)

### Steps to reproduce (*)
1. Attempt to login with with admin_user with reload_acl_flag = 1 AND password with previous hash version (3 -> 2)

### Expected result (*)
1. User is successfully logged in, and password is saved again with newest hash version.

### Actual result (*)
1. Magento crashes, password is saved again with newest hash version. After refresh user is successfully logged in
2. error log:
`report.CRITICAL: Password is required field.
Invalid type given. String expected
Invalid type given. String, integer or float expected`

EDIT: Updated information regarding the issue. Error does not occur when user has incorrect hash version, but rather when user has previous hash version (2, compared to current 3). Currently when user with hash version 2 tries to login, he is logged in successfully, and his password is saved again. However that is not the case when reload_acl_flag is also set to 1.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @michal-balut-accenture 
Steps followed to reproduce:
1. Created an admin_user
2. Copy the password hash of this user from the admin_user table in database (referred as old password)
3. Update the password for this user from the admin panel(CMS) of Magento (referred as new password)
4. Also update reload_acl_flag field value to 1 for that user
5. Opened admin_user table in database and updated the password to old password's hash
6. Tried to login to Magento with the same admin user

By following above steps, we were able to successfully login without any errors. Please let us know if the steps followed are proper as per your query and kindly revert for any changes in the reproducible steps.

**Comment by michal-balut-accenture** [comment]
Hi @engcom-Alfa 

Firstly i would like to add that i was only able to reproduce this bug on production deploy mode. Furthermore, after switching from developer mode to production, i would still not encounter this error. Probably something from developer mode has to cleared for this to happen.

Also, it was maybe unclear in my initial post, but by hash version i referred to hashing algorithm key version. Those are named hash versions in frameworks Encryptor class.

Please try these steps to reproduce the error:
1. Clear everything or just run `magento setup:upgrade`
2. Run `magento deploy:mode:set production`
3. Create new user (all further steps refer to this user)
4. Change in database user password hash version to 2 (change the last part of password to 2, for example: XXXXXX:XXXXX:3 -> XXXXXX:XXXXX:2)
5. By default newly created user should have reload_acl_flag = 1, so there should be no need to set it manually.
6. Attempt login with user

Additionally, my observation regarding this issue: it seems that the reason for this issue is that user object is firstly saved with password, but then is saved again, this time without password. Saving user object second time, but without password, when this user object was previously saved with password results in unhandled exception.

Please let me know if there is some further clarification needed

**Comment by engcom-Bravo** [comment]
Hi @michal-balut-accenture,

Thanks for the detailed steps. It is not expected to force the hashing version(algorithm) manually through database in magento. Closing this ticket as non-issue. Kindly re-open the ticket for any concerns.
