### ISSUE TITLE
Override Mixin with another Mixin

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#33159]
### Summary (*)

I need to disable a third party mixin and replace it with my own. But there are no informations on how to disable a mixin and it seems to be impossible to replace it with another one.

### Examples (*)

https://magento.stackexchange.com/questions/338137/magento-2-override-mixin-with-another-mixin/339319#339319

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @Eddcapone ,

You can try using map in requirejs-config.js to load your mixin instead third party mixin. if this does not work , request you to kindly add more description to the ticket , like your use case and code snapshots,

Thanks

**Comment by Eddcapone** [comment]
Hello @engcom-Echo, there is a link to stackoverflow in my Issue. Yes map solves it, I just used it incorrectly because it is not described in the documentation.
