### ISSUE TITLE
Cannot disable shipment update emails

### ISSUE THREAD

**Issue by kassner** [magento/magento2#33165]
### Preconditions

1. Magento 2.4.2;

### Steps to reproduce

1. In the admin panel, go to Stores > Configuration > Sales > Sales Emails and disable the Shipment comments;
2. Open a shipment view in the admin panel;

### Expected result

1. No `Notify Customer by Email` checkbox;

### Actual result (*)

1. Checkbox is still there:

![Screenshot from 2021-06-07 15-36-36](https://user-images.githubusercontent.com/301255/121026515-7f597600-c7a6-11eb-8613-ba306f7e0fcc.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kassner** [comment]
@magento give me 2.4-develop instance

**Comment by kassner** [comment]
Looks reproducible on 2.4-develop.

![Screenshot from 2021-06-07 16-40-02](https://user-images.githubusercontent.com/301255/121036437-0c083200-c7af-11eb-8d2a-6aa2b4d47537.png)
![Screenshot from 2021-06-07 16-39-55](https://user-images.githubusercontent.com/301255/121036443-0ca0c880-c7af-11eb-8acb-75a729b8467a.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42577` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
