### ISSUE TITLE
Magento 2 Paypal payflow mobile redirect

### ISSUE THREAD

**Issue by abhishekc3** [magento/magento2#33170]
**Preconditions (*)**

1. Magento CE 2.3.4 without Sample Data
2. Apache (PHP 7.2.34)

**Steps to reproduce (*)**

1. Enable only Paypal Payflow payment method from configuration
2. Add any product and navigation to checkout page.
3. Add the billing address and click on submit button.
4. Click on continue button on payment page.

**Expected result (*)**
 Iframe should be open in mobile view being in the same page. (Should not redirect to another page.)

**Actual result (*)**
 Page is redirect to Paypal gateway page in a new window using mobile view.

Below is the reproducible recorded video ie reproducible in **2.4-develop version** with or without sample data.
https://user-images.githubusercontent.com/51679138/121349559-499fc300-c947-11eb-9659-5f405f1aa2f5.mp4

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42605` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mayankgchetu** [comment]
@magento-engcom-team Can you please add priority label in this issue?

**Comment by abhishekc3** [comment]
@magento-engcom-team Can you please add priority label in this issue?

**Comment by engcom-Lima** [comment]
Hi @abhishekc3,

As per the current implementation in Magento, it is an expected behaviour that a new window opens for payment and after paypal payment is completed, the control is back to original window. Hence closing this ticket as non-issue. Kindly re-open the ticket if you have any concerns or create a new one.

Regards
