### ISSUE TITLE
[Magento Enterprise][Catalog Import] Magento still create URL rewrite record for "Not Visible Individually" product.

### ISSUE THREAD

**Issue by tranhoangthien1990** [magento/magento2#33174]
Hi team. We're facing an issue with Product import flow. Magento still generates the URL rewrite record for the product with the "Not Visible Individually" state.

Preconditions (*)
1. Magento Enterprise 2.4.2 (with sample data)

Steps to reproduce (*)
1. Create another store view for the Default website, for example, a new store view website code will be fr.
2.  Create import file for this store view, include column sku, store_view_code, name, url_key (url_key is very important, if you don't add this column, you cannot see this issue)
3. Change the product name for this sku, you can specify a value for url_key column or leave it blank 
4. Note that you must specify the SKU with visibility is "Not Visible Individually" (and make sure this value is "Use default value" in fr store view).
5. Try to import this file.
6. Import success.
7. Verify the product data in fr store view.

Expected result (*)
1. New name has applied (OK)
2. URL key is the same with Default website (use default value checkbox is checked)
3. No more URL rewrite for this product

Actual result (*)
1. New name has applied
2.URL key is autogenerated by the new name in the import file (use default value checkout is unchecked)
3. URL rewrites are generated automatically for this product even visibility is still "Not Visible Individually"

Please help to check it again.

Regards.

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990,

Could you please help us with some screenshots of the actual result to understand the issue better?

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990,

As we have not received any reply for the last comment since few days, we are closing this ticket. Please open a new ticket if you are still facing this issue.

Thanks

**Comment by sdzhepa** [comment]
@engcom-Bravo 

Could you please clarify your questions from https://github.com/magento/magento2/issues/33174#issuecomment-860548427 ?

what exactly steps you did and what of them are not clear?
please specify what exact step or statement to actual/expected result si not clear

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990,

URL key field will be autogenerated even for products with 'Not visible individually' value in visibility field on import. That is the behaviour of Magento. 
Hence, the actual result you have provided in the description seems correct. 

Please let us know for any other queries on this.

**Comment by tranhoangthien1990** [comment]
Hi @engcom-Bravo it sounds like doesn't make sense to me. Why Magento tries to create a URL rewrite for "Not visible individually" via the import process, but if I create a new product via admin dashboard by manually, it doesn't generate the URL rewrite.
It's really strange and makes our import process conflict with the default Magento flow.
Let example that i have a configurable product with the name is Configurable A and children lists are: Product A (color Green), product A (color Yellow), product A (color Red). All the children items are "Not visible individually", but when we try to import data for children items, Magento show an error message related to "The URL rewrite already exist", because they try to generate the url rewrite for the children product, all of them have the same name, so that's why they cannot generate url rewrite for all of them.

If It's a Magento native behavior, it's really strange.
Hi @sdzhepa , can you help to confirm it again, and after that might I will close this ticket.

Regards
Thien.

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990,

We understand your issue. We will re-check on this native behaviour and get back to you on this soon.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990 ,

In both cases of manual product creation and import through CSV file, following is the behaviour:
1. URL key field is autogenerated as per new product name even for 'Not visible individually' products.
2. URL rewrite is not created for 'Not visible individually' products.

If you are able to see URL rewrites created for 'Not visible individually' products, Please share the screenshots of product page settings and URL rewrite page to examine further. 

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @tranhoangthien1990,

As we have not received any reply for the last comment since 16 days, we are closing this ticket. Please open a new ticket if you are still facing this issue.

Thanks.
