### ISSUE TITLE
Notice: Undefined index: store_id error after deleting a store on 2.0.2

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3317]
After deleting a store my cms and static block pages have become unviewable under admin. Instead I'm left with the error below. I tried to reindex and delete any cache files I could find even though I'm sure this is a db issue.

> Notice: Undefined index: store_id in /var/www/html/magento2/vendor/magento/module-store/Ui/Component/Listing/Column/Store.php on line 82

**Comment by sstovall** [comment]
PR #3477 to re-run checks. (#3476 failed due to travis-ci poweroff)

**Comment by cspruiell** [comment]
I believe this is related to https://github.com/magento/magento2/issues/2921 and will be resolved by that fix.

**Comment by kevando** [comment]
Why doesnt reindexing fix this?

**Comment by wert2all** [comment]
Fixed
