### ISSUE TITLE
The \Magento\Catalog\Model\Indexer\Category\AffectCache and \Magento\Catalog\Model\Indexer\Product\AffectCache have 39 lines of code each but differs by a single constant (copy/paste) 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3318]
https://mage2.pro/t/467

**Comment by palamar** [comment]
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
