### ISSUE TITLE
Swagger UI is out of date (version 3 is latest)

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#33194]
### Preconditions
1. Magento 2.x

### Steps to reproduce
1. Open /swagger route using browser

### Expected result
1. Swagger UI is using version 3

### Actual result
1. Swagger UI is using version 2

##  

Is there any plans to upgrade swagger UI, or anything blocking this currently? See comment here: <https://github.com/magento/magento2/pull/7446#issuecomment-350105915>

**Original Report**: <https://github.com/magento/magento2/issues/12595> by @careys7

**Comment by mmezhensky** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story
