### ISSUE TITLE
Amazon Pay Versions

### ISSUE THREAD

**Issue by BernardRobbins** [magento/magento2#33195]
We have 2.2.5 installed. Running composer update will install Amazon Pay v2.2.2. Amazon Pay version for Magento 2.2.5 is 2.0.15.

https://packagist.org/packages/amzn/amazon-payments-magento-2-plugin
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/composer.json

**Comment by drpayyne** [comment]
Hi @sivaschenko @BernardRobbins, is this issue still present? I would like to know how I can help. :)

FYI, https://packagist.org/packages/amzn/amazon-payments-magento-2-plugin is abandoned and https://packagist.org/packages/amzn/amazon-pay-magento-2-module is the active one.

**Comment by engcom-Delta** [comment]
Hi @BernardRobbins.
Kindly provide clear issue description , steps to reproduce , Actual results and Expected results.
Hence, adding the 'Needs update' Label.

Thanks

**Comment by engcom-Delta** [comment]
There has no update from reporter and it has been more than ~14 days. Hence closing the ticket.
Kindly raise new issue if required or re-open the existing ticket.

Thanks
