### ISSUE TITLE
Upgrade vendors to latest versions for magento 2.4 release

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#33192]
Hi community!
I want to report current state of vendors in `2.4-develop` branch.
For details see https://github.com/magento/magento2/issues/28939
 
This work allow us to use the latest versions of vendors in our code base.
example: in my own code i want to use `monolog/monolog: v2.*` but it's incompatible with magento.
same for other vendors.

**Comment by sivaschenko** [comment]
Hi @rvitaliy I will close this issue as we have separate issues for each specific dependency update
