### ISSUE TITLE
Currency is not updating [Magento 2]

### ISSUE THREAD

**Issue by LogicalBaphomet** [magento/magento2#33190]
Hi everyone,

I have a trouble with my website in magento 2, I have changed the currency for a MXN Pesos and I can see the change in my local, but when I reboot the server to update the website it shows always the currency in dollars.

Do you know what is happening? I have days trying to fix it.

Thank you!

**Comment by engcom-Echo** [comment]
Hi @LogicalBaphomet ,

Kindly provide few more details like what all steps you did to change the currency along with expected/actual behaviour , if possible kindly provide screenshots as well. Also request you to check whether you have set Currency Rates ( Admin => Stores => Currency Rate ) properly and also try flushing the cache and check if that resolves the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hi @LogicalBaphomet ,

It seems that your issue has been resolved. Since we have not received your comment for more than 14 days, we are closing this ticket. In case of issue, you can create new ticket.
