### ISSUE TITLE
Eliminate laminas/laminas-crypt composer dependency

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33208]
laminas/laminas-crypt has released it's PHP 8 compatible version in February 2021, in order to accelerate future PHP compatibility work this dependency should be eliminated.

Laminas crypt is currently only used in `\Magento\Framework\Encryption\Helper\Security` for a single static function call of `\Laminas\Crypt\Utils::compareStrings`.

Compare strings implementation should be done in `\Magento\Framework\Encryption\Helper\Security::compareStrings` method and laminas/laminas-crypt composer dependency should be removed.

**Comment by engcom-Golf** [comment]
**composer require laminas/laminas-crypt** will fix this issue
