### ISSUE TITLE
MP3 download

### ISSUE THREAD

**Issue by kcam6690** [magento/magento2#33201]
### Preconditions (*)

1.Magento ver. 2.4.0
2.

### Steps to reproduce (*)

1. download new product
2.downloadable product 
3.upload MP3 file and a alert comes up saying true. but MP3 doesnt show onscreen

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/85662157/121469521-a5d80680-c98a-11eb-9d80-ce1468162c9a.png)

2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Hi @kcam6690 
Tried on Magento 2.4 Develop but it works fine.

**Comment by kcam6690** [comment]
is there a way  i can show you what i am going through ?
I can not use my website for what it is needed for 

    On Thursday, June 10, 2021, 6:46:31 AM EDT, Manjunath ***@***.***> wrote:  
 
 


Hi @kcam6690
Tried on Magento 2.4 Develop but it works fine.

**Comment by engcom-Delta** [comment]
Hi @kcam6690,
I tried again on Magento 2.4 Develop , chrome browser 91.0 and Followed the below steps to reproduce it .
1. Log into Magento admin backend
2. Click on Catalog & select the products
3. Click on Add Product button and select Downloadable product option
4. Enter product name ,sku name  & price
5. Scroll down to downloadable information section
6. Click on 'Add Link' button 
7. Enter title  & click on Browse files 
8. observed that uploaded files are displayed on UI
9. click on Save button 
10. Observe that we could see MP3 file info. Hence Labelled as needs update .
Kindly find the attached video for reference.

Please suggest clear steps if my approach is wrong.

https://user-images.githubusercontent.com/51681379/122400559-754f2880-cf99-11eb-8ef0-19c9b5df1d8c.mp4

**Comment by kcam6690** [comment]
Good morning,

So when I go to add a MP3 a notification pops up that says |attention true |. It doesn’t upload successfully.

**Comment by engcom-Delta** [comment]
Hi @kcam6690,

As per latest comments it works as expected. moreover, there has no update from 14 days .Hence closing the ticket.
Kindly log a new issue if required or re-open the existing issue.
Thanks
