### ISSUE TITLE
Sample Data Installation "var/composer_home"

### ISSUE THREAD

**Issue by mariarti** [magento/magento2#3320]
Hi,
I experience problem when try to add `composer config http-basic.repo.magento.com $PubKey $PriKey` into `var/composer_home` directory via CLI.
Even when I try to create empty file 
`su - apache -c "cd $basepath$baseurl/var/composer_home/ && touch composer.json && composer config http-basic.repo.magento.com $PubKey $PriKey"` 
directly after 
`composer install && composer config repositories.magento composer https://repo.magento.com` 
it says  `No such file or directory` (seems like /composer_home folder not exist at that time? when it appear? )

upd
Indeed, folder `var/composer_home` appear only after starting `php ./bin/magento sampledata:deploy`

So, i have an issue how to add `composer config http-basic.repo.magento.com $PubKey $PriKey` into `var/composer_home` directory via CLI _before_ `php ./bin/magento sampledata:deploy` (to automate installation process without manual entering credentials)?

Adding magento repo to user home directory works well (it create all necessary credentials in ~/.composer/auth.json)
`composer config --global http-basic.repo.magento.com $PubKey $Pri

`ln -s ~/.composer/auth.json var/composer_home/` and copying - is not an option.

**Comment by buskamuza** [comment]
Hi @mariarti ,
`var/composer_home` appears only when it is necessary (when Setup Application works with Composer).
You can add the folder manually, like `mkdir cd $basepath$baseurl/var/composer_home/ && cd $basepath$baseurl/var/composer_home/ ...`

**Comment by mariarti** [comment]
Вопрос был как сделать это композером, а не костылями. я специально уточнил об этом в конце.
например как `composer config http-basic.repo.magento.com $PubKey $PriKey`

**Comment by buskamuza** [comment]
@mariarti , as I can see Composer is not able to create a directory for the `auth.json` file, though it creates the file itself. Maybe it would make more sense to ask the question in https://github.com/composer/composer , as you're asking a question about `composer` command?
Basing on what Composer can do, you should create the directory in advance.

If you want to make a feature request for Magento to introduce a CLI command for filling data into this file, please, say this explicitly.

Another idea about sample data command was to allow options for the keys, so this information can be used by the command. But this is specific to this command only.

**Comment by mariarti** [comment]
Why it so complicated? Especially if developers invent this "easy" way for "convenience".
Yes, i would be very appreciate if Magento developers could make this feature as option _during installing sample data only_ (and may be some how check if keys already exists)
It is bad idea to make things before thinking about how easy to use it. (this game with keys was absent in beta).

Composer developers should know all tricks of using their product? 
I think composer does not invent such logic of sample data deployment.

**Comment by buskamuza** [comment]
Composer supports `--file` option, which allows to create/update a config file in arbitrary location. This is exactly what is needed for this case.

**Comment by andimov** [comment]
@mariarti 
Looks like this is not a Magento bug.
Do you have any other questions?

**Comment by mariarti** [comment]
Looks like m2 developers use non obvious methods in creating sample data with composer, so I compelled to ask help.
So, @buskamuza advice to use `--file` option and I try to implement it to script which try to setup credentials for Sample data. I make something like:
`cd $basepath$baseurl/var/composer_home/ && touch auth.json` and then
`cd $basepath$baseurl/var/composer_home/ && composer config --file $basepath$baseurl/var/composer_home/auth.json http-basic.repo.magento.com $PubKey $PriKey`

I don't know is it correct, but seems work. Hope it can help someone.
I appreciate @buskamuza  for help.

**Comment by andimov** [comment]
@mariarti
Thank you for the solution with detailed description!
