### ISSUE TITLE
Eliminate es6-collections.js

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33206]
**Depends on MutationObserver.js elimination**: https://github.com/magento/magento2/issues/33207

Remove `lib/web/es6-collections.js` and replace usages with native JS.

The es6-collections are providing the following polyfills:
- **WeakMap** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakmap
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L8-L22
- **Map** - ✔ supported https://caniuse.com/mdn-javascript_builtins_map
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L24-L46
- **Set** - ✔ supported https://caniuse.com/mdn-javascript_builtins_set
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L48-L67
- **WeakSet** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakset
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L69-L80

Following the investigation in: https://github.com/magento/magento2/issues/32851

**Comment by anzin** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story
