### ISSUE TITLE
Put sample data in require-dev instead of require (composer)

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3321]
What is the reason the sample data is installed in the require part of composer.json? I would say it makes more sense to put it in require-dev, as it's mainly a development tool in my believe. If that makes more sense, I'm happy to make a PR. But there might be a very good valid reason to have it in there of course :)

**Comment by magento-engcom-team** [comment]
@stefandoorn please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
