### ISSUE TITLE
the whole website collapsed 

### ISSUE THREAD

**Issue by dr7oran** [magento/magento2#33228]
everything was perfect 
i was forced to to change my password for admin login to the dashboard 
change it 
could not re log in 
tried to unlock 
on code lead to another the whole website collapsed front end and back end 

help please

**Comment by mrtuvn** [comment]
maybe you should re-create second admin account for re-access your site again
Magento allow you create account from command line "bin/magento admin:user:create"

About collapse website feel weird to me! Have you revert your changes ? Any errors log or visible on screen. Please provide fullpage screenshot if possible

**Comment by engcom-Bravo** [comment]
Hi @dr7oran ,

Please let us know if you have tried the suggested solution in this ticket thread and if in case it is still not working kindly help us with more details of the issue with screenshots.

**Comment by dr7oran** [comment]
a guy checked and told me it is s composer issue 
wish anyone can help 
both ended has collapsed front end and back end

**Comment by engcom-Bravo** [comment]
Hi @dr7oran ,

In your description you have mentioned, you "tried to unlock and
one code led to another the whole website collapsed". Could you please let us know the details on these code changes?

Also, You can try following steps:
1. Try reverting the code changes made for this issue
2. Flush the cache - bin/magento cache:flush
3. Create a new admin user - bin/magento admin:user:create

Additionally, kindly provide more details with screenshots and error logs if any, to understand the issue better.

**Comment by dr7oran** [comment]
unfortunately nothing worked so far

**Comment by dr7oran** [comment]
<img width="626" alt="Screen Shot 2021-06-19 at 00 34 07" src="https://user-images.githubusercontent.com/85847436/122618119-44085280-d096-11eb-80c8-d27d50e59874.png">
<img width="867" alt="Screen Shot 2021-06-19 at 00 34 01" src="https://user-images.githubusercontent.com/85847436/122618121-45397f80-d096-11eb-9366-c443d6350494.png">

**Comment by mrtuvn** [comment]
Seem your problem not related to magento. This broken may be come from misconfiguration composer. Some incorrect setup permissions. Tell your hosting provider support or your admin system if you have

**Comment by dr7oran** [comment]
I have hosting from inter server 
what am I suppose to tell them ?

**Comment by dr7oran** [comment]
xxx.com/admin 
is not working too

**Comment by mrtuvn** [comment]
Maybe you should start at https://composer.github.io/pubkeys.html
Try run re-run correct composer command in your terminal

**Comment by engcom-Bravo** [comment]
Hi @dr7oran,

As rightly said by @mrtuvn , looks like this is an issue with composer and not magento.

Please run "composer self-update --update-keys" and refer  https://composer.github.io/pubkeys.html for pubkeys.

Then run "composer diagnose" to check if the issue has fixed. 

We are closing this issue as it is not related to Magento. Please open a new ticket for any magento related issues.

Thanks.
