### ISSUE TITLE
search result sorting broken when "Remember Category Pagination" is enabled

### ISSUE THREAD

**Issue by 0xdeb** [magento/magento2#33220]
### Preconditions (*)

1. Magento 2.4.2-p1 with sample data

### Steps to reproduce (*)

1. Go to Stores > Configuration > Catalog > Catalog > Storefront
2. Enable "Remember Category Pagination"
3. Go to frontend and search for something (e.g. "bag")
4. Sort defaults to "Relevance". Change to "Price".
5. Clicik the arrow to sort by price desc/asc.

### Expected result (*)

1. Search result should still be sorted by price. 

### Actual result (*)

1. The sort defaults back to Relevance. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @fabis2000 ,

I have followed the steps given in description , however I was not able to re-produce the same . In my case the sort on price worked on both asc and desc and was not changing back to 'Relevance'. Please find the screenshots attached.

<img width="1087" alt="Screenshot 2021-06-11 at 5 02 41 PM" src="https://user-images.githubusercontent.com/51681435/121680283-fbb9c500-cad6-11eb-8375-cfb730167b3b.png">

<img width="1008" alt="Screenshot 2021-06-11 at 5 02 54 PM" src="https://user-images.githubusercontent.com/51681435/121680293-ff4d4c00-cad6-11eb-9af9-59f492c6120e.png">

<img width="1033" alt="Screenshot 2021-06-11 at 5 03 06 PM" src="https://user-images.githubusercontent.com/51681435/121680301-02483c80-cad7-11eb-830c-793a14e8468f.png">

Request you to kindly test the same on latest magento branch 2.4-develop and let us know if you get the issue there.

Thanks

**Comment by fabis2000** [comment]
@magento give me 2.4-develop instance

**Comment by fabis2000** [comment]
Thanks @engcom-Echo for having a look at this. 
I was able to reproduce it in the public 2.4-develop instance. I recorded a uncut video showing the problem and how I replicated it. The 3 minute video starts before first login, so all steps for reproducing can be seen.
Here is the link: https://youtu.be/BGNkilmG-2Q
The only thing I did different was flush the cache, I dont't know if that makes any difference. 

Please let me know if you need any additional information.

**Comment by fabis2000** [comment]
@magento I am working on this

**Comment by fabis2000** [comment]
@magento add to contributors team

**Comment by fabis2000** [comment]
@magento I am working on this

**Comment by fabis2000** [comment]
Hi @engcom-Echo. Have you had a chance to look at the video yet? Can you please have another look at this issue and update the tags so this can proceed? Thanks.

**Comment by engcom-Echo** [comment]
Hi @fabis2000 ,

I tried to replicate the same issue on our vanilla instance , and the issue was reproducible there.

Thanks

**Comment by vovsky** [comment]
@magento give me 2.4-develop instance

**Comment by vovsky** [comment]
@magento I am working on this

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-8904&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks
