### ISSUE TITLE
Move to Shopping Cart action not working in admin order.

### ISSUE THREAD

**Issue by sanjay-github** [magento/magento2#33238]
### Preconditions (*)

1. Magento v2.4.1 Enterprise Edition
2. 

### Steps to reproduce (*)

1. Go to the admin panel and start creating a new order.
2. Make sure you have added additional_options on the quote item via event or plugin. In my case, I have set using "**sales_quote_item_set_product**" event.
3. Now Move the product to the shopping cart using the "**Move to Shopping Cart**" option in **Action**.

### Expected result (*)

1.The item should be moved to the shopping cart in the left sidebar.

### Actual result (*)

1. The item is not moving to the shopping cart in the left sidebar. Basically, this happens because the quote item has additional_options. It is not about how it was added. Once added, the feature will anyway stop working.

**Comment by engcom-Hotel** [comment]
Hello @sanjay-github,

Please let us know the location of your events.xml file. It is in the frontend folder or outside from it.

Thanks

**Comment by sanjay-github** [comment]
@engcom-Hotel :
The event is in the adminhtml area.

**Comment by engcom-Hotel** [comment]
Hello @sanjay-github,

Please keep the events.xml file from outside of adminhtml folder. and then try again.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @sanjay-github,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
