### ISSUE TITLE
Add enable/disable compare functionality

### ISSUE THREAD

**Issue by AurelienLavorel** [magento/magento2#3323]
Hello,

In v1 of Magento it was easy to disable compare functionality but now it take lot of time, can you add a yes/no configuration for that please ?

Regards,

Aurelien

**Comment by antboiko** [comment]
Hi @AurelienLavorel , thanks for your inquiry. Could you please clarify what Magento versions did you compare? 
Also, please give me more details about disabling process itself, how do you perform it?

Best,
Anton.

**Comment by AurelienLavorel** [comment]
Hi, 

I compare 1.x versions to 2.x. In 1.x, we just have to do add this in your layout file :
`<layout>
    <default>
        <remove name="catalog.compare.sidebar" />
    </default>
</layout>`
And override Mage_Catalog_Helper_Product_Compare

In 2;x, I have to modify more than 10 files to disable this.

Can't we have a dropdown to enable/disable this ? Like for Wishlist.

Thanks,

Aurelien

**Comment by quienti** [comment]
> Can't we have a dropdown to enable/disable this ? Like for Wishlist.

+1

**Comment by ghost** [comment]
> Can't we have a dropdown to enable/disable this ? Like for Wishlist.

+2

**Comment by cscd98** [comment]
+3

**Comment by mengento** [comment]
+4

**Comment by jakobfdev** [comment]
+5

**Comment by pboisvert** [comment]
@tkacheva Olena--can you file a ticket for the backlog to make this configurable with the default set to no comparison?

**Comment by tkacheva** [comment]
Internal ticket MAGETWO-52841

**Comment by sivaschenko** [comment]
Current workaround to remove compare functionality from frontend: https://coderwall.com/p/vsqmbw

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-enable-disable-compare-functionality/idi-p/46074).
