### ISSUE TITLE
How to find what is the controller responsible?

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [magento/magento2#33243]
I am using the Amasty store locator module, in the backend, i am filled with all values and click the save button, how to find which controller is responsible for saving all the values.

After clicking the save button i want to do some customization, What is the controller responsible?

**Comment by engcom-Lima** [comment]
Hi @Jeeva-Rathinam 

I checked your ticket. If am i right? it is not an issue. Please check the below url to understand the routing.
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/routing.html

Hence closing this ticket. Please feel free to raise the new ticket if you have any other genuine issue.

Thanks for the understanding!
