### ISSUE TITLE
Magento Elasticsearch goes down frequently 

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#33240]
**Preconditions (*)**

1. - Magento 2.4.1
2. - I have around 10 K products - simple and confugurable 
3. - VPS Server with 8 GB ram and 4 vCpus

**Issue** 
Elasticsearch goes down frequently 

**Indices Settings as below**
![image](https://user-images.githubusercontent.com/63009790/121917223-8b1edc80-cd52-11eb-8c7b-9e134aa6ca0b.png)

**Comment by engcom-Echo** [comment]
Hi @ia-gaurav ,

Can you please provide more details to the issue like the steps to re-produce or attach logs so that we can verify the same at our end.

Thanks

**Comment by engcom-Hotel** [comment]
Hi @ia-gaurav,

It seems that your issue has been resolved. We have not received your reply since more than 14 days, we are closing this issue for now. 

If you still having this issue, you can reopen the ticket or create a new ticket.

Thanks
