### ISSUE TITLE
Unable to translate cache.xml title and label

### ISSUE THREAD

**Issue by sIiiS** [magento/magento2#3324]
Translation of the cache.xml file in the below path not working for me in "MCE 2.0.2"
path = `/vendor/magento/module-store/etc/cache.xml`

**Comment by andimov** [comment]
@sIiiS
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by sIiiS** [comment]
I changed the Title, is this enough ?

**Comment by sa495679** [comment]
Hi,
I am using Magento 2.1.9 version. In admin Cache Management section translations are not working.
I added Translation text in respective language file also. but its not reflecting in admin.
So please give me the solution for Admin cache management translations.
Below path file i used for cache management translations
path = /vendor/magento/module-store/etc/cache.xml
