### ISSUE TITLE
front end & backend 

### ISSUE THREAD

**Issue by dr7oran** [magento/magento2#33246]
a problem started with forced password changing after logging in to the admin panel 
changed it 
tried to sign in again couldn't 
tried to unlock user as per advice 
one code to another error reports occurred
at the end website disappeared front end and back end 

as a guy, he told me it is a composer, etc issue !!

need help

**Comment by krishprakash** [comment]
Hi @dr7oran. GitHub issue tracker is intended for Magento core technical issues only
Kindly refer Community Forum Or Magento stack exchange to general discuss about this topic so any one can solve your problem and you will get answers about your problem.
Thank you!
