### ISSUE TITLE
Rest api is not providing Rush Fee and Oversize fee within get order response 

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#33259]
### Summary (*)

We are downloading order through magento 2 rest API. but we are not getting additional fees within order response. 
The additional fees are Rush Fee and Oversize fee 

### Examples (*)

We are calling the api v1/orders. 
In the response order we are not getting the additional fee those are Rush Fee and Oversize fee 

### Proposed solution

These additional field must be downloaded with the order. so they should be included into response 
![Magnto 2 order with Fees](https://user-images.githubusercontent.com/54638813/122227045-29867b80-ced4-11eb-8c0d-d8957edbe9af.png)
[magento-orderresponse.txt](https://github.com/magento/magento2/files/6663333/magento-orderresponse.txt)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Golf** [comment]
@webgility-amazonapi Can you please update the description mentioning about Specific **Magento version**. Also Rush Fee and Oversize fee are the custom attributes ?

**Comment by engcom-November** [comment]
@webgility-amazonapi , we are closing this issue as there has been no latest update on the same.
Thank you.
