### ISSUE TITLE
Magento 2.4.2 does not allow login Error 404 Page Login

### ISSUE THREAD

**Issue by adorobeleza** [magento/magento2#33252]
Hello friends, after upgrading from magento 2.3.6 to 2.4.2 I can't log in anymore, and as you can see there are errors in the email.php file

Website: https://www.adorobeleza.com.br/customer/account/login/

PHP 7.4.20 (cli) (built: Jun 4 2021 21:24:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.20, Copyright (c), by Zend Technologies

nginx.conf.sample is in the /pub folder

https://pastebin.com/JVhEjz1t

![error 404](https://user-images.githubusercontent.com/80371175/122140824-7c9ff600-ce22-11eb-8572-3033d33f85e8.png)

Preconditions (*)
Steps to reproduce (*)
Expected result (*)
[Screenshots, logs or description]
2.error 404

Actual result (*)
[Screenshots, logs or description]

Error email error 404

![email-error](https://user-images.githubusercontent.com/80371175/122140765-685bf900-ce22-11eb-89c8-2f6baf32782a.png)

<script type="text/x-magento-init">{"body":{"pageCache":{"url":"https:\/\/www.website.com.br\/page_cache\/block\/render\/referer\/aHR0cHM6Ly93d3cuYWRvcm9iZWxlemEuY29tLmJyL3NhbGVzL29yZGVyL2hpc3Rvcnkv\/","handles":["default","customer_account_login"],"originalRequest":{"route":"customer","controller":"account","action":"login","uri":"\/customer\/account\/login\/referer\/aHR0cHM6Ly93d3cuYWRvcm9iZWxlemEuY29tLmJyL3NhbGVzL29yZGVyL2hpc3Rvcnkv\/"},"versionCookieName":"private_content_version"}}}</script>

email.php file

https://pastebin.com/FFqHHYSg

Please provide Severity assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

 Severity: S0 - Affects critical data or functionality and leaves users without workaround.
 Severity: S1 - Affects critical data or functionality and forces users to employ a workaround.
 Severity: S2 - Affects non-critical data or functionality and forces users to employ a workaround.
 Severity: S3 - Affects non-critical data or functionality and does not force users to employ a workaround.
 Severity: S4 - Affects aesthetics, professional look and feel, “quality” or “usability”.

**Comment by mrtuvn** [comment]
Seem problem not related with magento codebase! Have you double check from your customise code ? I don't found in the magento code around with isEnabled('google') like your console log error screenshot show

**Comment by engcom-Golf** [comment]
@adorobeleza This is not an issue due to Magento 2.4.2. It seems something wrong with your Codebase. I would suggest you to check error log as well. Are you getting **email.php** related console error on Login Screen or Login Action Screen. 

I opened the link you shared for Login Screen, and have not found **email.php** related Console error. 
![image](https://user-images.githubusercontent.com/51681547/122364385-56d83580-cf77-11eb-8c60-e588d5faa3fa.png)

Please update, if the Issue still persist.

**Comment by adorobeleza** [comment]
Hello friends, I understand that this cannot be a problem with Magento, but in version 2.3.6 it was working normally, What changed in this version to make this error occur?


@engcom-Golf You need to enter some email to get the popup with a 404 error.

Note that in this version magento has adopted the docroot this may be interfering? Regarding the Google error, do you know what it can be?

**Comment by adorobeleza** [comment]
Note: After updating we need to update the nginx file and remove the TAG ttl=3600 from the default.xml file to be able to view the menu one

**Comment by engcom-November** [comment]
Verified the issue after upgrading from Magento 2.3.6 to 2.4.2 and Admin login and Front-end login both are working fine. We are closing this issue as there has been no latest update on the same. @adorobeleza , kindly reopen/create new issue if you are still facing issues and provide missing configuration details if any.
Thank you.
