### ISSUE TITLE
Magento Backend Not Working

### ISSUE THREAD

**Issue by NishaHublit** [magento/magento2#33257]
After Cache Clean my Magento backend not working..
how can I resolve this

**Comment by mrtuvn** [comment]
Can you provide more information or fullpage screenshot show error ?
See log in folder magento_root_folder/var/*.log for more futher infor to investigate

**Comment by krishprakash** [comment]
Hi @NishaHublit. Feel free to reopen once you provide all the details as per [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Thanks
