### ISSUE TITLE
Not able to upload vimeo video

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#33276]
### Preconditions (*)

1. latest magento 
2. applied patch MDVA-35092

### Steps to reproduce (*)

1. go to any product and try to add vimeo video 
2. you will get error Notice: Undefined index: extension in /var/www/html/vendor/magento/framework/File/Uploader.php on line 810 ( error is getting when get thumbail from video)

### Expected result (*)

1. it should be get thumbail image and no error on save or ajax get image info

### Actual result (*)

1. getting error Undefined index: extension in /var/www/html/vendor/magento/framework/File/Uploader.php on line 810 ( error is getting when get thumbail from video) - 

![image](https://user-images.githubusercontent.com/2923438/122451216-83b33980-cfc5-11eb-95f9-adf111b8e1d7.png)

on click on save
![image](https://user-images.githubusercontent.com/2923438/122451345-a6dde900-cfc5-11eb-873a-29b2ca3ff19c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by mrtuvn** [comment]
Hi @sunilit42 The fix may related with your issue already created at link below
https://github.com/magento/magento2/pull/33260/files

**Comment by engcom-Delta** [comment]
Hi @sunilit42,

We have tried on Magento 2.4 Develop to reproduce , unfortunately we could not replicate it.
Followed the below steps to replicate.
1. Log into Magento admin backend
2. Go to Categories --> Products
3. Select the one product to add video
4. Go to section Images & video
5. Click on Video
6. Enter url of vimeo video link & provide title
7. select the thumbnails as Role 
8. Observe that you have not any error on UI
9. click on 'Save' button 
10. Observe that no error found.
Hence , added the label as not reproducible and Kindly find the attached screenshot for reference.
![thumbnail_saved](https://user-images.githubusercontent.com/51681379/122550296-1f3dbc00-d051-11eb-8201-ff089784e8e8.jpg)
![Vimeo_videoAdd](https://user-images.githubusercontent.com/51681379/122550305-21a01600-d051-11eb-8ca4-6b810c6b8921.jpg)

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by sunilit42** [comment]
@engcom-Delta 
don't upload thumbail image, it should be fetch from video and try to save it

**Comment by sunilit42** [comment]
@engcom-Delta 
I have tested with https://vimeo.com/56282283 and not working
https://nimb.ws/N89v1c

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42680` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment]
@engcom-Delta @sunilit42 As mentioned @mrtuvn PR already in progress https://github.com/magento/magento2/issues/33276#issuecomment-863740072

**Comment by gabrieldagama** [comment]
This is the same issue as https://github.com/magento/magento2/issues/33266, closed in favour of the other one that already has a PR as described by @Den4ik.
