### ISSUE TITLE
After a validation error of a configurable product the variant table is not functional anymore

### ISSUE THREAD

**Issue by MarianNapi** [magento/magento2#33270]
### Preconditions (*)

1. Magento version 2.4.2
2. PHP 7.4

### Steps to reproduce (*)

1. Create new configurable product
2. add several child products
3. force the validator to fail
4. try to remove one child product

### Expected result (*)

1. the chosen child should be removed from the variation list

### Actual result (*)

1. every child get's removed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MarianNapi** [comment]
@magento give me 2.4-develop instance

**Comment by MarianNapi** [comment]
I tried to force the built in validator to return an error but failed on that. You can simply use a custom validatePlugin to throw an error and the table wont work anymore.

**Comment by oneserv-heuser** [comment]
I can confirm that this issue exists on my local machine by just manipulating the Validate class and force it to fail. The result is that the entire configurable matrix is destroyed ui wise and continue working is impossible, you have to reload the page and you'll loose every change you made.

**Comment by engcom-Delta** [comment]
Hi MarianNapi,
Kindly elaborate step# 3 (force the validator to fail) , how to force the validator ?. 

Thanks

**Comment by oneserv-heuser** [comment]
Hi @engcom-Delta you can force the validator to fail by just editing the [Validate class](https://github.com/magento/magento2/blob/f121ac8359768b5ebcc7462574e58c36f34c52df/app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php#L118) and adding "throw new LocalicedException(__('Error'))" to the line i've linked (line 118). This will force the validation to fail and you'll be able to the the issue described.

We've found no way to trigger a validation error via UI.

**Comment by engcom-Delta** [comment]
Hi MarianNapi,

Tried to reproduce it by following the steps provided but issue is not reproducible , it works as expected.
Kindly find attached snapshots for reference.

Steps followed  (on Magento 2.4 Develop).
1. Log into backend 
2. create configurable product
3. go to file (validate.php ) path magento2/app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php and open file in notepad
4. Add "throw new LocalicedException(__('Error'))" to the line i've linked (line 118)( in Validate.php file)
5. Save it
6. Go to configurable product & remove 1  child product
7. Observed that other child products remain present , not getting all the child product.
Hence  labelled this issue as 'Needs update'.

Thanks
![Remove_Product1](https://user-images.githubusercontent.com/51681379/123636503-95ed6d00-d83a-11eb-96c8-664f353932b5.jpg)
![After_removed](https://user-images.githubusercontent.com/51681379/123636688-c92ffc00-d83a-11eb-8af9-0b197160035f.jpg)

**Comment by MarianNapi** [comment]
Hey engcom-Delta,

after your step 5 you need to click save in the configurable product. (For example after adding a child or renaming the product) The save process then get's interrupted because of the failed validation and you are still in the edit page of your product. After this failed validation trying to remove one child removes all children.

**Comment by engcom-Delta** [comment]
Hi @MarianNapi,

Thanks for quick turnaround. 
![Default_configurations_set for country](https://user-images.githubusercontent.com/51681379/124443971-c897e800-dd9b-11eb-9572-a4860b4a9da2.jpg)
![Delete_config_Prod](https://user-images.githubusercontent.com/51681379/124444016-d0f02300-dd9b-11eb-9723-82d9459ba2cd.jpg)
![Remove_Product1](https://user-images.githubusercontent.com/51681379/124444137-ee24f180-dd9b-11eb-9e60-e1c702d2d55c.jpg)
I tried once again , I performed Save operation also , the process is not deleting child products. Kindly find few more snapshots for reference.

**Comment by engcom-Delta** [comment]
There has no update from Reporter and it has been more than 14 days. Hence closing the ticket.

**Comment by MarianNapi** [comment]
Sorry for the late reply, I was on vacation.

I made a video to show the bug:

At first I show that normally it's no problem to remove a child product from the list.
Then I reload the page to get it's state back
After that I switch to the Validate class and add an hard coded error.
Now I press save on the product and the validation error get's thrown.
If you try to remove one child product after that it will remove all children.


https://user-images.githubusercontent.com/65761018/126181122-b470e42d-f200-4c91-981a-70ec5a8fb8e8.mp4

**Comment by oneserv-heuser** [comment]
@engcom-Delta Please reopen the ticket, thank you

**Comment by oneserv-heuser** [comment]
Created new issue: https://github.com/magento/magento2/issues/33744
