### ISSUE TITLE
Magento 2 links in admin/backend don't work

### ISSUE THREAD

**Issue by vikimal** [magento/magento2#33275]
We finished migration and we got an issue after loging to backend. I see dashboard, but I cannot handle anything (icons on the left side in admin look like inactive)

### Preconditions (*)

1. Magento 2.4.2p1

### Expected result (*)

1. The ability for icons and other active elements to be active and controllable in backend

### Actual result (*)
1. screen of issue: https://prnt.sc/15pn9gk 
2. I see dashboard after logging, but I cannot handle anything (icons on the left side in admin look like inactive)

**Comment by engcom-Delta** [comment]
Hi ,
We tried installation and verify the ticket but unfortunately looks fine , not faced any error .
System OS is iOS mac & Chrome browser 91.0
1.	Install magento 2.4.2-p1 version
2.	Log into admin/backend
3.	Go to dashboards
4.	Click on various tabs , active elements and all controllable 
5.    Observed that seems good.
Hence request to try again from your end. If
![Magento2 4](https://user-images.githubusercontent.com/51681379/122553778-c02e7600-d055-11eb-9c16-76dd1f274905.jpg)
 not , kindly share clear steps to reproduce the issue.
Please find the attached screenshot for reference.

**Comment by engcom-Delta** [comment]
There has no update , it is been more than 14 days , Hence closing the defect.
Kindly request to log new issue if required or re-open the existing issue.

Thanks
