### ISSUE TITLE
Call to a member function quoteIdentifier() on null

### ISSUE THREAD

**Issue by iamcoolbuddy** [magento/magento2#33274]
I am trying created an Ui Component admin form for a Banner module. When Loading the form page getting this error.

**"Call to a member function quoteIdentifier() on null".**

I do not find any solution anywhere with this issue. I am hopeless

Can anyone help to find what I am doing wrong here! I am using

Magento Version 2.3.7

Thanks in advance.

Below is My Form Xml Code.

`<argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">banner_form.banner_form_data_source</item>
            <item name="deps" xsi:type="string">banner_form.banner_form_data_source</item>
        </item>
        <item name="label" xsi:type="string" translate="true">Banner Information</item>
        <item name="config" xsi:type="array">
            <item name="dataScope" xsi:type="string">data</item>
            <item name="namespace" xsi:type="string">banner_form</item>
        </item>
        <item name="template" xsi:type="string">templates/form/collapsible</item>
    </argument>`
`<dataSource name="banner_form_data_source">
    <argument name="dataProvider" xsi:type="configurableObject">
        <argument name="class" xsi:type="string">CB\Banner\Model\DataProvider</argument>
        <argument name="name" xsi:type="string">banner_form_data_source</argument>
        <argument name="primaryFieldName" xsi:type="string">id</argument>
        <argument name="requestFieldName" xsi:type="string">id</argument>
        
    </argument>
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="component" xsi:type="string">Magento_Ui/js/form/provider</item>
        </item>
    </argument>
</dataSource>`
`<fieldset name="general">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="label" xsi:type="string" translate="true">Banner Information</item>
        </item>
    </argument>
    <field name="title">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">Title</item>
                <item name="dataType" xsi:type="string">text</item>
                <item name="formElement" xsi:type="string">input</item>
                <item name="validation" xsi:type="array">
                    <item name="required-entry" xsi:type="boolean">true</item>
                </item>
                <item name="source" xsi:type="string">banner_form_data_source</item>
            </item>
        </argument>
    </field>`
`<field name="description">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">Description</item>
                <item name="dataType" xsi:type="string">text</item>
                <item name="formElement" xsi:type="string">input</item>
                <item name="source" xsi:type="string">banner_form_data_source</item>
            </item>
        </argument>
    </field>`
`</fieldset>`

**Comment by engcom-Hotel** [comment]
Hi @iamcoolbuddy,

We need more information in order to get this issue reproduce at our end. So please provide us more details as below:
1. Reported on Magento version
2. Component name 
3. Preconditions 
4. Steps to reproduce 
5. Expected result
6. Actual result


Thanks

**Comment by engcom-Hotel** [comment]
Dear @iamcoolbuddy,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards
