### ISSUE TITLE
GraphQL: As a developer I would like to get the configured configurable_product_options_selection for a ConfigurableCartItem, so I can render configurable's image in the cart

### ISSUE THREAD

**Issue by paales** [magento/magento2#33278]
*As a developer I would like to get the configured configurable_product_options_selection for a ConfigurableCartItem, so I can render configurable's image in the cart*

Currently we _can_ get the information but it requires and additional roundtrips (one for each configurable) on the frontend to get this:

```graphql
query GetCart($cartId: String!) {
  cart(cart_id: $cartId) {
    items {
      ... on ConfigurableCartItem {
        configurable_options {
          # First we get the uids
          configurable_product_option_value_uid
        }
      }
    }
  }
}

# We run an additional query FOR EACH configurable product
query GetCartImages($sku: String!, $options: [ID!]!) {
  products(filter: { sku: { eq: $sku } }) {
    items {
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          attribute_uid
        }
        configurable_product_options_selection(
          configurableOptionValueUids: [$options]
        ) {
          media_gallery {
            url
          }
        }
      }
    }
  }
}

```

### AC

We would like to be able to do the following:

```graphql
query GetCart($cartId: String!) {
  cart(cart_id: $cartId) {
    items {
      ... on ConfigurableCartItem {
        configurable_options {
          # First we get the uids
          configurable_product_option_value_uid
        }
        configurable_product_options_selection {
          media_gallery {
            url
          }
        }
      }
    }
  }
}
```

### Approved Schema
*

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and Cart Query is working fine as per official Magento [dev docs](https://devdocs.magento.com/guides/v2.4/graphql/queries/cart.html) however "configurable_product_options_selection" option is not applicable for cart Query as per Magento Docs. Hence labeling this as feature request.
Current behavior:
![image](https://user-images.githubusercontent.com/60198231/145592666-251844f9-72a3-4c1e-919f-514094dbe261.png)
![image](https://user-images.githubusercontent.com/60198231/145592803-de1ac109-b520-45f7-9b31-7338da89205c.png)

**Comment by paales** [comment]
Since Magento 2.4.3 (Released 10 Aug 2021) there is a new configured_variant available in the cart. Introduced here: https://github.com/magento/magento2/commit/7ca4158ecac89a1c1a7f4829a10fed637897f3b7#diff-6032b79b3087e50be3e6c58ea93634e2ad1d9f3fdcc5cf43e8adb94ea6eb2744R64

https://github.com/magento/magento2/blob/8de016a35bbd3d668f10046af1007ce69a9ee86f/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls#L67

This solves the exact same issue as this issue is describing.
