### ISSUE TITLE
After Upgrade to Magento 2.4.2 AbstractFactory.php:121 Error

### ISSUE THREAD

**Issue by adorobeleza** [magento/magento2#33286]
<! ---
Revise nossas diretrizes antes de adicionar um novo problema: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Os campos marcados com (*) são obrigatórios. Não remova o modelo.
->

### Pré-condições (*)
<! ---
Forneça a versão exata do Magento (exemplo: 2.4.0) e qualquer informação importante sobre o ambiente onde o bug pode ser reproduzido.
->
Hello friends

After upgrading to magento 2.4.0 to 2.4.2 I received the following error
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'arguments': This element is not expected.

I am also getting the message "There are no source items with in stock status" when trying to add an item to my cart

Could someone help me how I should proceed to solve this problem

Thank you for your help now!
![Captura de tela de 2021-06-18 21-06-14](https://user-images.githubusercontent.com/80371175/122625941-0ef00600-d07e-11eb-946f-74f7361bf1d6.png)

![Captura de tela de 2021-06-18 21-12-04](https://user-images.githubusercontent.com/80371175/122625944-144d5080-d07e-11eb-961e-021c36fdc2cc.png)

<pre>#1 Magento\Framework\Config\Dom->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]

### Passos para reproduzir (*)
<! ---
Importante: forneça um conjunto de etapas claras para reproduzir esse bug. Não podemos fornecer suporte sem instruções claras sobre como reproduzir.
->
1
dois.

### Resultado esperado (*)
<! --- Diga-nos o que você espera que aconteça. ->
1. [Capturas de tela, logs ou descrição]

### Resultado atual (*)
<! --- Conte-nos o que aconteceu. Incluir mensagens de erro e problemas. ->
1. [Capturas de tela, logs ou descrição]
dois.

---
Forneça uma avaliação de [Severidade] (https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) para o problema como Relator. Essas informações ajudarão durante os processos de confirmação e triagem de problemas.

- [] Gravidade: ** S0 ** _- Afeta dados críticos ou funcionalidade e deixa os usuários sem solução alternativa._
- [] Gravidade: ** S1 ** _- Afeta dados ou funcionalidade crítica e força os usuários a empregar uma solução alternativa._
- [] Gravidade: ** S2 ** _- Afeta dados ou funcionalidades não críticas e força os usuários a empregar uma solução alternativa._
- [] Gravidade: ** S3 ** _- Afeta dados não críticos ou funcionalidade e não força os usuários a empregar uma solução alternativa._
- [] Gravidade: ** S4 ** _- Afeta a estética, aparência profissional, “qualidade” ou “usabilidade” ._

**Comment by engcom-Bravo** [comment]
Hi @adorobeleza ,

When we upgrade clean installation of magento we are unable to reproduce this error. Hence could you please provide the steps/settings of your magento to reproduce this issue?

Also the error "There are no source items with in stock status" is usually seen when the product does not have enough stock specified. Kindly provide us more details to check on this issue.

**Comment by engcom-Delta** [comment]
There has no update from reporter and it has been more than 14 days. Hence closing the issue.
