### ISSUE TITLE
Incorrect 'State' selected for post code in France

### ISSUE THREAD

**Issue by mattf10** [magento/magento2#33283]
When user does not select 'State' field, it is automatically selected based on postcode*.   In the backend under State Options, France is not selected, and 'Allow to Choose State if It is Optional for Country' is set to 'No'.

 I have one order where the 'State' that was selected is incorrect.  The postcode for the order is '56100', which should return department (State) of 'Morbihan', code = 56.   However, the department selected in this case was 'Alpes-de-Haute-Provence', code = 4.   

It would be better if the system did not automatically select the State.  If it's not required and the user isn't allowed to select it, then there is no reason for the system to add the State to the address.   In France, Department (state) is not used in postal addresses.

* 'State' is only selected automatically for some orders.  

### Preconditions (*)

1.  Magento 2.4.2-p1
2. PHP 7.4

### Steps to reproduce (*)

1.  Configuration -> General -> General -> State Options -> State is Required:  France is not selected
2.  Configuration -> General -> General -> State Options -> Allow to Choose State if It is Optional for Country:  No
3. Place order with Country = France, Post code: 56100, Ville: Lorient
4. Order in back end billing address has incorrect department as part of the shipping address

### Expected result (*)

1.  Billing address should not have department as part of address (or correct department should be selected)

### Actual result (*)

1. billing address has incorrect department as part of the shipping address

Workaround is to add France to State is Required countries.   

Severity: S1

**Comment by mattf10** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi mattf10,
We tried placing an order with provided steps, we unable to reproduce the issue. moreover ,it is working as expected.
Snapshots are attached for your reference.
![State_not_selected](https://user-images.githubusercontent.com/51681379/123072071-da3fce00-d432-11eb-8e3d-ec248289df31.jpg)
![orderPlaced](https://user-images.githubusercontent.com/51681379/123072128-e62b9000-d432-11eb-8bb5-1f51844585a4.jpg)
![front_end_order](https://user-images.githubusercontent.com/51681379/123072192-f3e11580-d432-11eb-9fa7-618a4562756d.jpg)
![Backend_screenshot](https://user-images.githubusercontent.com/51681379/123072285-08251280-d433-11eb-953a-06001714ce07.jpg)

**Comment by mattf10** [comment]
Ok - thanks for looking into it.  The problem only happened on this one order.

Do you happen to know if the code that automatically adds the State/Region is part of Magento core?   If not, it could be a problem with the Shipping extension used on the site.
