### ISSUE TITLE
[MFTF] Replace AspectMock with PHPUnit for PersistedObjectHandlerTest

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33293]
### Goal

`codeception/aspect-mock` library is still not compatible with PHP 8.0 at the time of the creation of this ticket.

To speed up Magento compatibility with new PHP versions we'd like to eliminate `codeception/aspect-mock` dependency from MFTF. This will make MFTF compatible with PHP 8.0 that is required for declaring the Magento core PHP 8 compatible as well.

In order to do this existing unit tests using AspectMock should be refactored to use PHPUnit instead.

### Task
Replace AspectMock with PHPUnit for `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/PersistedObjectHandlerTest.php` in https://github.com/magento/magento2-functional-testing-framework repository.

### Example

Mocking an object using AspectMock (current):

```
        $mock = AspectMock::double(
            MockedClass::class,
            [
                'mockedMethodName' => 'methodReturnValue',
            ]
        )->make();
```

Mocking an object using PHPUnit (refactored code):

```
        $mock = $this->createMock(File::class);
        $file->expects($this->any())
            ->method('mockedMethodName')
            ->willReturn('methodReturnValue');
```

Example pull request: https://github.com/magento/magento2-functional-testing-framework/pull/833

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
Hi @sivaschenko, I'm looking for some guidance on how to eliminate the AspectMock usage from this file. Here are the details

- `PersistedObjectHandlerTest` uses `AspectMock` to create a test double for `CurlHandler` in the `PersistedObjectHandlerTest::mockCurlHandler` method for every test case. 
- Every test case uses `PersistedObjectHandler::createEntity` which calls `DataPersistenceHandler::createEntity` using the `new` operator, which in turn instantiates `CurlHandler` using the `new` operator.

Any thoughts on how I can mock this and/or remove the AspectMock usage for cases where no constructor/method DI is used?

**Comment by sivaschenko** [comment]
@drpayyne is it possible to extract the `CurlHandler` creation to a new Factory class?

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by sivaschenko** [comment]
@drpayyne are you still working on this issue?

**Comment by drpayyne** [comment]
@sivaschenko, I did for a while but I won't be able to work on this for a couple weeks. So anyone who wants to can pick this up. :)

**Comment by anzin** [comment]
@magento I am working on this
