### ISSUE TITLE
Attribute is returned as aggregation in products query even if Use in Search Results Layered Navigation is set to no

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#33318]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. On any attribute set the setting "Use in Search Results Layered Navigation" to no (using price as example here)
2. Execute the following graphql query:
```graphql
query searchProducts {
    products(search: "") {
        aggregations {
            label
        }
    }
}
```

### Expected result (*)

![image](https://user-images.githubusercontent.com/53174153/122883660-b64e9080-d33d-11eb-948d-fd9c6a972a72.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/53174153/122883487-8acba600-d33d-11eb-9caa-a71775561b93.png)

### Whats the problem about it (*)
The huge problem is here that if you build filters based on the aggregation field the user will be able to filter the price. But if you try to filter via the price if it's disabled for layered navigation you'll receive the following error:
![image](https://user-images.githubusercontent.com/53174153/122884112-180efa80-d33e-11eb-8cdf-7d4d8163840c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment]
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment]
@magento I can confirm that this issue is reproducible on the vanilla magento instance

**Comment by oneserv-heuser** [comment]
I just found out that this issue not only exists for the price attribute but for **all** attributes. Magento ignores the settings in the backend. If you set the setting "Use in Search Results Layered Navigation" to false then the attribute gets returned when asking for the aggregation field but you cannot use it in the field ProdutAttributeFilterInput.

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
Hi @oneserv-heuser. 
I tested, and Magento really ignores the settings in the backend of the "price" field, but I have no problems with other attributes.

The settings for the "price", "visibility", "category_ids" fields are specifically ignored (in file CatalogGraphQl/Plugin/Search/Request/ConfigReader.php)
```
/**
     * Generate search request for search products via GraphQL
     *
     * @return array
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     */
    private function generateRequest()
    {
        $request = [];
        foreach ($this->getSearchableAttributes() as $attribute) {
            if (\in_array($attribute->getAttributeCode(), ['price', 'visibility', 'category_ids'])) {
                //some fields have special semantics
                continue;
            }
           ...
```

The price is added separately in the file CatalogGraphQl/etc/graphql/di.xml
```
    <type name="Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\LayerBuilder">
        <arguments>
            <argument name="builders" xsi:type="array">
                <item name="price_bucket" xsi:type="object">Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Price</item>
                <item name="category_bucket" xsi:type="object">Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Category</item>
                <item name="attribute_bucket" xsi:type="object">Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Attribute</item>
            </argument>
        </arguments>
    </type>
```

**Comment by oneserv-heuser** [comment]
@khrystynastolbova You're right, it only affects those attributes. I tried it again and my custom attributes are not returned. Maybe that was something cache related back then.

**Comment by engcom-Hotel** [comment]
Hi @oneserv-heuser,

Thank you for informing the issue.

The issue is verified and is reproducible on Magento 2.4-develop.

Navigated to Stores->Attributes->Product and I changed ‘Use in Layered Navigation’ to ‘No’ for ‘Price’ Attribute. Below a screenshot of the same:
![image](https://user-images.githubusercontent.com/51681618/145374547-d77c6f31-680e-4415-88a4-21149d5f33f9.png)
I tried to run GraphQL product search query but ‘Price’ is still coming in ‘aggregations’ as below:
![image](https://user-images.githubusercontent.com/51681618/145374582-afa2926a-94c1-4844-98b3-563c39d529d6.png)
Magento is ignoring the ‘Price’ and some other settings which are set in Admin Panel. So that is why putting the issue as Confirmed.

Thanks,

**Comment by engcom-Alfa** [comment]
Hi @oneserv-heuser ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento-commerce/magento2ce/commit/e71f1543555d7740b5132f18c192f61c02857551).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by joggienl** [comment]
Hopefully someone can respond to this question because I am confused.

Which one of the following settings should be affected by this issue?

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1089150/202188664-566d2b88-1025-4d93-8395-e731b829eb1f.png">

The issue seems to be talking about both of them.

Thanks!

**Comment by oneserv-heuser** [comment]
@joggienl The "Use in Layered Navigation" setting should be affected by this issue.
