### ISSUE TITLE
In Authorize.net test mode, after order place page is not redirecting to success page.

### ISSUE THREAD

**Issue by pallaboffice** [magento/magento2#3331]
In Authorize.net test mode, after order place page is not redirecting to success page.
All cache are enabled.

**Comment by alena-marchenko** [comment]
Hi,

I was not able to reproduce the issue. Could you provide screenshot of Authorize.net configuration and exception/debug logs, specify version of Magento that you are using? Also, please take a look at our [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by robfico** [comment]
We saw something very similar with a merchant. Using PHP 7.0.3 (and Magento 2.0.2), using Auth.net direct post, when placing an order, the checkout page would hang (spinning indicator on page), and the transaction would not appear in Auth.net. debug.log just shows the request, and then nothing else.

We downgraded to php 5.5.32, and the transaction went through just fine. Looks to be a bug with PHP 7 and direct post. fyi - we also saw this same hang issue with Braintree using php 7.

**Comment by pallaboffice** [comment]
Thank you Rob, Thanks for the finding correct issue! It is something wrong in PHP 7.x.x version and Authorize.net API. The return value was null. I also will try to find the issue on Monday once more.

Thanks

**Comment by alena-marchenko** [comment]
We delivered fix for issue with PHP 7 and payment methods to develop branch.
Please verify that the issue is resolved.

**Comment by jitendracis** [comment]
Hi,
I am getting same issue "In Authorize.net test mode, after order place page is not redirecting to success page." in Magento 2.0.8. 

Could you please tell me, in which file you have fixed this issue? Because I don't want to upload all files on Magento 2 website.

Please let me know.
