### ISSUE TITLE
checkout keeps loading after upgrade to 2.4.2

### ISSUE THREAD

**Issue by luudv** [magento/magento2#33317]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Add a product to the cart.
2. Click the checkout button.
3. The checkout page shows loading without stopping. There aren't any javascript errors showing in developer tool.

### Expected result (*)

1. The checkout page can work
<img width="2044" alt="1" src="https://user-images.githubusercontent.com/2778871/122854795-789e3780-d33e-11eb-9790-bb464b5e4093.png">

### Actual result (*)

1. 
<img width="2039" alt="2" src="https://user-images.githubusercontent.com/2778871/122854939-a97e6c80-d33e-11eb-9942-1917b4ad69dd.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
You can open your chrome browser and click on Console tab Or Navigate to Network tab => Filter XHR
Then reload checkout page wait a seconds to reveal real issue error message!

**Comment by luudv** [comment]
> You can open your chrome browser and click on Console tab Or Navigate to Network tab => Filter XHR
> Then reload checkout page wait a seconds to reveal real issue error message!

Yes, I did it and don't see any errors. These commands have all been executed:
`bin/magento cache:clean && bin/magento cache:flush && bin/magento setup:upgrade && bin/magento setup:di:compile && bin/magento indexer:reindex && bin/magento setup:static-content:deploy -f`

**Comment by mrtuvn** [comment]
I'm not sure about real issue without see the code and website. But i think you should check with custom modules and customises first related with checkout section. Maybe something broken related with customises code after upgrade

**Comment by luudv** [comment]
Yeah, I tried disabling my third-party extensions and customizations but it still doesn't work. I had to go back to the old version 2.4.0. Thank you for your help.

**Comment by engcom-Delta** [comment]
Hi luudv,

We tried to reproduce this issue, unfortunately we are not facing this issue .Kindly try to test it one more from your end and specify from which version to which you are upgrading .

Thanks

**Comment by engcom-Delta** [comment]
There has no update from reporter from ~14 days. Hence closing the issue.
Kindly log new issue if required or re-open the existing issue.
