### ISSUE TITLE
Package is not installed: magento/project-community-edition-2.3.7.0

### ISSUE THREAD

**Issue by kennedyabitbol** [magento/magento2#33328]
### Preconditions (*)

1. Magento 2.3.7

### Steps to reproduce (*)

1. After upgrading the composer json with 2.3.7 version, everything seems fine but when i am launching another time composer require+update for another module it stops
  ```
- Installing magento/product-community-edition (2.3.7)

In LibraryInstaller.php line 114:

  Package is not installed: magento/project-community-edition-2.3.7.0

```

### Expected result (*)

Just want to follow with composer 

### Actual result (*)

1. when using composer update i encountered an error
```
$ php7.4 -f /usr/bin/composer update
Loading composer repositories with package information                                                                                                   Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Package operations: 55 installs, 1 update, 0 removals

In LibraryInstaller.php line 114:

  Package is not installed: magento/project-community-edition-2.3.7.0
```

This version number comes from:
installed.json:
```

    {
        "name": "magento/magento2-base",
        "version": "2.3.7",
        "version_normalized": "2.3.7.0",
        "dist": {
            "type": "zip",
            "url": "https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.3.7.0.zip",
            "shasum": "23b58922ee35a7207fcf8a45e9dc0d651ead279e"
        },
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Have you add authenticate keys to auth.json in magento root folder  for `repo.magento.com` ?

**Comment by kennedyabitbol** [comment]
> Have you add authenticate keys to auth.json in magento root folder for `repo.magento.com` ?
Thanks for your answer, yes, composer downloads more than half of the packages, then stop on magento/project-community-edition-2.3.7.0.

I just solved it by changing old name    "name": "magento/project-community-edition" to "name": "magento/magento2ce", removing vendor folder, install then update, seems to have passed.

I got now some error when running _bin/magento setup:db:status_
`Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /vendor/magento/module-inventory-api/registration.php:8`

**Comment by mrtuvn** [comment]
usually i used this command
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition /tmp/exampleproject 2.4.2
rsync -a /tmp/exampleproject/ /var/www/html/
rm -rf /tmp/exampleproject/

Devdocs: https://devdocs.magento.com/guides/v2.4/install-gde/composer.html

**Comment by kennedyabitbol** [comment]
Yes, i did not used it for my upgrade, otherwise i did not encounter trouble like this migrating to 2.4.2 :(.
Maybe i'll skip this one, thank you.

**Comment by engcom-Hotel** [comment]
Hello @kennedyabitbol ,

As per the comments, it seems that your issue has been resolved. Please let us know, if you are still facing the issue.

**Comment by kennedyabitbol** [comment]
> As per the comments, it seems that your issue has been resolved. Please let us know, if you are still facing the issue.

I did not tried more :(

**Comment by engcom-Hotel** [comment]
Hello @kennedyabitbol,

As communicated earlier that the issue has been fixed already. So we are closing this ticket for now. 

If you still facing the issue, either you can reopen it or you can create a new ticket.

Thanks
