### ISSUE TITLE
Layout gets initialized twice if ViewInterface is not injected into Controller

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#33329]
I was working on a feature including a custom product list page, including filters for category and product attributes. For some reason, every active filter element got duplicated during rendering.

Through debugging I found out, that the method Magento\RequireJs\Block\Html\Head\Config::_prepareLayout would trigger a second build of page layout, resulting in every block being initialized twice. Since Magento\LayeredNavigation\Block\Navigation::_prepareLayout isn't idempotent, every active filter got added a second time.

It seems like the controller and the RequireJs block for some reason end up with separate instances of either the \Magento\Framework\View\Page\Config or the \Magento\Framework\View\Layout\Builder classes in their dependencies, because they have flags that should prevent a second build of the page layout.

I could prevent this behavior by injecting Magento\Framework\App\ViewInterface into my controller, though this is a deprecated class.

### Preconditions (*)

Magento version is 2.4.1, but I suspect this bug exists ever since controller aren't required to extend the default Action anymore.

### Steps to reproduce (*)

1. Create a custom Controller rendering a page, make sure not to extend \Magento\Framework\App\Action\Action
2. Inject Magento\Framework\View\Result\PageFactory
3. In the execute method, return $this->pageFactory->create();
4. Include a custom block in page layout, that implements the _prepareLayout method

### Expected result (*)

1. _prepareLayout should only be called once

### Actual result (*)

1. _prepareLayout is called twice

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
[Tuna_Tweak.zip](https://github.com/magento/magento2/files/6706698/Tuna_Tweak.zip)
Try to reproduce your same scenario with my own custom module but seem result opposite. Log file only show one.
Can you check that module fit same your case ?
I have tested in latest codebase

**Comment by mfickers** [comment]
I copied your module into the same project and there are two log messages for a single request, but I couldn't recreate the behavior on a fresh Magento 2.4.1 installation. Looks like this is caused by third party code.

I'm closing this issue, thank you for your time.
