### ISSUE TITLE
magento 2 installation stops randomly

### ISSUE THREAD

**Issue by ranimstudios** [magento/magento2#3332]
Magento 2 installation stuck randomly. Sometimes at 68% or sometimes at 97

**Comment by mazhalai** [comment]
Check if your [max_execution_time](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_70pct.html) setting is as [recommended](https://github.com/magento/magento2/blob/develop/.htaccess#L67).

**Comment by iw0der** [comment]
Hi,
I think it is the voracity of memory & time, which plays tricks; you need to changes the limits in php and anyway others are actually changed even within the code. So you will need to wait for a fix or take action manually on the code.

Partially, I will carry that could impact in php.ini (values from experience):

`php_value       memory_limit            768M`
`php_value       max_execution_time      18000`
`php_value       max_input_vars          4096`

and in **vendor/tubalmartin/cssmin/cssmin.php** where where strangely execution time is set too short value, with `set $this→max_execution_time = 60;`. This one sure impact on command `magento setup:static:deploy`; there should be some tickets around but can not remember where!

I do not know all, probably there is more that depends on the type of installation, but this can be a beginning waiting for fixes and minor claims by software ;-)

73s,
A

**Comment by mazhalai** [comment]
@ranimstudios closing this as non-responsive.
