### ISSUE TITLE
Declare PHP 8 compatibility in magento/composer

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33339]
Declare PHP 8.0 compatibility for https://github.com/magento/composer/

Update magento/composer version in magento2 composer.json once the PHP 8 compatible magento/composer is released.

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by andrewbess** [comment]
PR is merged in magento/composer repository
