### ISSUE TITLE
Eliminate laminas-mvc and all possible dependencies used for retired Setup Wizard

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33338]
Setup Wizard was retired leaving only a couple of static pages as part of it's functionality.

The laminas-mvc and all other dependencies of the retired Setup Wizard should be eliminated. The existing static functionality of Setup Wizard should not require any external libraries

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story
