### ISSUE TITLE
Update laminas-soap dependency

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33336]
laminas/laminas-soap has released it's PHP 8 compatible version in February 2021, in order to accelerate future PHP compatibility work this dependency should be eliminated.

The main entry points are:
`\Magento\Webapi\Controller\Soap`
`\Magento\TestFramework\TestCase\Webapi\Adapter\Soap::instantiateSoapClient`

Approach:
Implement soap support in Magento codebase

**Comment by andrewbess** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by anzin** [comment]
@magento I am working on this
