### ISSUE TITLE
Eliminate laminas-i18n and laminas-filter dependency

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33337]
laminas/laminas-i18n has a hidden dependency `laminas/laminas-filter` released its PHP 8 compatible version in January 2021, in order to accelerate future PHP compatibility work this dependency should be eliminated.

laminas/laminas-i18n and as a result laminas/laminas-filter dependencies should be eliminated.

Laminas\I18n\Filter\NumberParse is used in \Magento\Checkout\Model\Cart\RequestQuantityProcessor::process

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story
