### ISSUE TITLE
get configuration values in CMS static block  

### ISSUE THREAD

**Issue by hawksakr** [magento/magento2#3334]
is there a way to get configuration values in CMS static block  like it was in Magento 1

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
