### ISSUE TITLE
Cannot Add Group Product Item to Basket If Any Simple Products have a Default Quantity of 0

### ISSUE THREAD

**Issue by mjflipmind** [magento/magento2#33348]
### Preconditions (*)
Magento 2.4

### Steps to reproduce (*)
On Magneto 2.4.x on group product when trying to add it to the cart I get this error:

![image](https://user-images.githubusercontent.com/11608958/123381184-81b03280-d5e4-11eb-992d-3ce9b7573861.png)

Issue relates to https://github.com/magento/magento2/pull/24955

Issue 24955 says it relates to stock level but this doesn't seem to be true.  It seems to be caused if any of these values is 0:

![image](https://user-images.githubusercontent.com/11608958/123381090-61807380-d5e4-11eb-8766-10faaf2e41b1.png)

Issue is caused by this code in vendor/magento/module-grouped-product/Model/Product/Type/Grouped.php :

![image](https://user-images.githubusercontent.com/11608958/123381360-c0de8380-d5e4-11eb-8b7f-dc44801ce496.png)

### Expected result (*)

It should add the item to the basket without error.

### Actual result (*)
Item is not added to basket.

**Comment by barryvdh** [comment]
Why was this closed? I'm encountering the same issue.
