### ISSUE TITLE
Can't login to any store when using plugin to Magento\Framework\Logger\Monolog addRecord method

### ISSUE THREAD

**Issue by donotdividebyzero** [magento/magento2#3335]
Hi!

When i'm using before plugin to Magento\Framework\Logger\Monolog addRecord method i can't login to admin panel or for that mater to any of frontend stores.

I've tried to plugin also to : 
\Monolog\Logger
\Psr\Log\LoggerInterface

It's just clearing input fields and nothing is happen.

I know for sure that plugin as well as base method are executed.

There is no errors or any debug indication what so ever.

**Comment by andimov** [comment]
@maciejvel 
Sorry for late reply!
Is this issue still actual for you?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
