### ISSUE TITLE
Admin dashboard Most Viewed Products Tab statistics not updating.

### ISSUE THREAD

**Issue by ksvikas** [magento/magento2#33371]
### Summary (*)
Most View Product is not showing on Admin side in Dashboard- Most-View-Product tab.

**Comment by krishprakash** [comment]
Hi @ksvikas.
Could you please provide more details as described in Issue reporting guidelines
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ksvikas** [comment]
In magento admin dashboard no products are showing in most viewed product grid if all product are in different attribute sets (not in default attribute set), even with magento sample data this grid is always displaying "We couldn't find any records.".
while visit to many products with registered user.

**Preconditions**

Magento ver. 2.4.1  with sample data

**Steps to reproduce**

Login to magento admin panel
check Most view product tab 


**Actual Result** 
It should update the viewed products

![123](https://user-images.githubusercontent.com/77429949/123776049-8d556f00-d8ec-11eb-9e46-1e206c5bd169.png)

**Comment by ksvikas** [comment]
@krishprakash, please check that issue.

**Comment by ksvikas** [comment]
@krishprakash , Can you suggest me the solution for this?

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @ksvikas,

Thanks for reporting this issue!

This is the duplicate issue of [issue](https://github.com/magento/magento2/issues/33389).  So we are closing this issue. 

Thanks
