### ISSUE TITLE
Setup Issue - 2.3.7

### ISSUE THREAD

**Issue by CHS-DanHirst** [magento/magento2#33374]
### Preconditions (*)

1. Magento 2.3.7
2. PHP 7.2.34
3. mysql  Ver 8.0.22-13
4. 

### Steps to reproduce (*)

1. Let Magento Update to 2.3.7
2. run bin/magento set:up

### Expected result (*)

1. Upgrade Magento 2 with no issues

### Actual result (*)

1. Returns the following: PHP Parse error:  syntax error, unexpected ')' in /var/www/setup/src/Magento/Setup/Module.php on line 80

### Proposed solution
You have an extra comma in your include array, removing it allows it to work without any issues

**Comment by abude** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
https://www.tutorialspoint.com/what-is-trailing-comma-in-php
you can use last comma in array without issue

**Comment by CHS-DanHirst** [comment]
Thought so, maybe some PHP setting because, here is a screenshot showing the issue: 
![image](https://user-images.githubusercontent.com/55755613/123759178-8eb87480-d8b7-11eb-8c2f-dc9a0e916c23.png)
![image](https://user-images.githubusercontent.com/55755613/123759298-ab54ac80-d8b7-11eb-9006-3aac6d61db22.png)

Although, the issue still happens in the interactive shell.

![image](https://user-images.githubusercontent.com/55755613/123759542-e6ef7680-d8b7-11eb-8196-781c1e10e283.png)

**Comment by mrtuvn** [comment]
i think you should try revert your code change!

**Comment by CHS-DanHirst** [comment]
> 
> 
> i think you should try revert your code change!

Thanks, even if i did its still in the source code?

https://github.com/magento/magento2/blob/2.3/setup/src/Magento/Setup/Module.php

![image](https://user-images.githubusercontent.com/55755613/123763792-0e484280-d8bc-11eb-834b-716f79a8a610.png)

**Comment by hostep** [comment]
@CHS-DanHirst: you are using the wrong PHP version I believe.

Magento 2.3.7 [dropped support for PHP 7.2](https://devdocs.magento.com/guides/v2.3/release-notes/open-source-2-3-7.html#platform-upgrades), you need 7.3 or even preferably 7.4:
> - Removal of PHP 7.1 and 7.2 compatibility. You cannot run Magento 2.3.7 on PHP 7.1 or 7.2.
> - PHP 7.3 is now deprecated. We do not recommend running Magento 2.3.7 with PHP 7.3. Merchants can run Magento 2.3.7 with PHP 7.3, but this configuration has not been tested.
> - PHP 7.4 support. Magento 2.3.7 introduces support for PHP 7.4.

It looks like that syntax didn't work properly on PHP 7.2, it started working in PHP 7.3, see this demo: https://3v4l.org/qZhYY

**Comment by CHS-DanHirst** [comment]
Ah apologies, Thanks - Closing Issue
