### ISSUE TITLE
Logging in or out as customer via graphql doesnt create a entry in 'customer_log'

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#33378]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Log in as customer via graphql
2. Log out as customer via graphql

### Expected result (*)

1. An entry in the table 'customer_log' is created

### Actual result (*)

1.  No entry in table 'customer_log' is created

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment]
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment]
I can confirm that this issue exists on an vanilla magento instance.
When logging in via the magento UI it will be logged and I can see myself as online in adminhtml under "Customers > Now Online". When using the graphql API to login this doesnt happen.

**Comment by khrystynastolbova** [comment]
@magento I am working on this
