### ISSUE TITLE
mangento2 setup on nginx with default lemp or magenx scripts fails permanently

### ISSUE THREAD

**Issue by atittandon** [magento/magento2#3337]
I dont want to hurt anyone but it was really frustrating that how can a preconfigured script fail after so many attempts. we are still not fully successful as the installation is stuck on php intl/xsl extension missing not found by magento installer pre requisite check (searching for the files for php 7).
Our system configuration.
IBM xserver 3650m3 with dual xeon server with 36 gb ram 73gb x5  sas 15k hdd
Os Centos7 minimal
Lempstack/Magenx configuration opted: Nginx/Tengine+Percona
+PHP7+Pureftpd+phpMyAdmin+redis+memcached/varnish.
after almost 105 attempts  in 15 days of magento 2 installation according to magenx scripts and lempstack both we were able to figured out that they both failed to run even the magento install 
We came around the final solution to at least run the installation and will update after full install to working config of magento2.
These are the solution to the white screen+ top bar with white screen+404/403/502 we were able to resolve(THANKS Google & Github)

1.change----> cgi.fix_pathinfo=1 inside php.ini
2.enter----> security.limit_extensions=.php .phtml in php-fpm.conf and the conf file inside php-fpm.conf.d 
3.define  ----> fastcgi_pass for .phtml files also in nginx config
 this allowed us to at least reach the magento installation.

WE Thank Magenx because of whom We would have never created the account at github.
He has given a really good script as without it we would have taken months to reach this level.
As we have no one to guide except google.
we will post the complete workaround for the users who are experiencing the same issue in few days after we resolve the whole issue and again repeat the same method at least 2 time from scratch

conclusion the default files given in mageto installation current dont work on ngix out of the box a lot of changes have to been done to start the installation over  the changes mentioned above.
Still working for the installation to conplete.

**Comment by fernandoneto** [comment]
@atittandon did you have any news about this?

**Comment by magenx** [comment]
our magento 2 server installation script works 20 out of 20 without any glitch. if you experimenting or pre-installing or mixing software packages  then any setup will fail badly..

**Comment by duhon** [comment]
Hello @atittandon 

To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
