### ISSUE TITLE
Bundle import broken when option name contains a question mark.

### ISSUE THREAD

**Issue by braders** [magento/magento2#33380]
I have a client who is making heavy use of bundle products, and are facing an issue when importing these products via CSV. This is affecting bundles, where the bundle option name contains a question mark.

For example, consider a site selling toys. They may have a bundle like the following:

**Option 1**
Name: Select a toy
Products: A selection of toys

**Option 2**
Name: Need batteries? Add them to your order
Products: A selection of batteries required to operate option 1

On importing the CSV containing these items for the first time, the products and bundle options are correctly created. However, on importing the CSV subsequent times (in order to update the product data), the bundle options are left in a broken state. 

The issue occurs because the second option name is "Need batteries? Add them to your order". If it was "Need batteries, Add them to your order" then there would be no issue.

### Preconditions (*)
1. Magento 2.4.1 (although I have verified that the affected lines of code have not changed in later releases of Magento)
2. Open Source & Commerce are affected

### Steps to reproduce (*)
1. Create a CSV product upload file. Add a selection of simple products, to be used by the bundle.
2. Upload the CSV using the native product import. Note that I have been testing with the following import configuration:
2.a Import behaviour: Add/ Update
2.b Fields enclosure: Unticked
2.c Field separator: , (comma)
2.d Multiple value separator: , (comma)
3. Observe that the bundle product has been imported correctly
4. Repeat step 2 (i.e. updating the previously inserted bundle)
5. Observe that the bundle product has duplicated battery products, and that empty option sets appear.

A sample CSV demonstrating the issue can be downloaded here: https://gist.github.com/braders/b9d9896671bc16539c28f65c8875b2a9

### Expected result (*)
The bundle options should appear correctly when viewing the bundle product, even when the import is ran multiple times. I.e. the bundle should appear like it does after a single import:

![Screenshot 2021-06-29 102642](https://user-images.githubusercontent.com/1931323/123774521-66377700-d8c5-11eb-8d6c-2f2b3a54f186.jpg)

### Actual result (*)
After the second import an empty option is created, and the products in the original option are duplicated (that is, the product "2 pack - AA Battery" is listed twice under the same product)

![image (2)](https://user-images.githubusercontent.com/1931323/123775090-f37acb80-d8c5-11eb-8e9b-c84e6177edca.png)

On importing subsequent times, the number of duplicate listings continues to grow. For example, after 3 imports:

![image (3)](https://user-images.githubusercontent.com/1931323/123776455-37ba9b80-d8c7-11eb-84b5-e224c440207c.png)

### Other observations

I have considered that maybe the question mark should be escaped in the CSV file in some way. However, I have so far not had any luck with trying this. The only way to get the correct setup is to manually edit the product (through the admin panel) after the faulty CSV upload.

The Magento products CSV export shows the `bundle_values` in the same format as the data imported (i.e. including the question mark, without any special formatting or escaping). It is expected that the values exported by CSV should be suitable for re-import later without any additional work. 

### Technical investigation

So far I have managed to track this issue down to `vendor/magento/module-bundle-import-export/Model/Import/Product/Type/Bundle.php`. It appears the question mark is being interpreted as a placeholder for a SQL prepared statement. 

In `Bundle::populateExistingOptions()`, `$this->_cachedOptionSelectQuery` correctly shows the question mark, if observed at the very start of the `populateExistingOptions` method. However, if the resulting query from the chained `$this->connection->select()...` call is observed, then the question mark has been replaced. Therefore, the variable `$existingOptions` incorrectly references only the options which do not contain question marks.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by braders** [comment]
@magento give me 2.4-develop instance

**Comment by braders** [comment]
I can confirm that I have reproduced on the fresh 2.4-develop instance:

![Screenshot 2021-06-29 105954](https://user-images.githubusercontent.com/1931323/123778606-2c686f80-d8c9-11eb-9399-ae31da80b325.jpg)

**Comment by engcom-Delta** [comment]
Hi @braders,

Tried to reproduce the issue with provided steps but we are not able to replicate it on Magento 2.4.2.
Hence, added the label 'Needs update '.

Please find the snapshots for reference.
![import1](https://user-images.githubusercontent.com/51681379/125052809-fd6cad80-e0c1-11eb-8a41-cadf6598fdbd.jpg)

After importing(1st attempt)
![after_1st_importing](https://user-images.githubusercontent.com/51681379/125052889-14130480-e0c2-11eb-9d1f-d1d2921b473a.jpg)

2nd import
![import2](https://user-images.githubusercontent.com/51681379/125052939-212ff380-e0c2-11eb-90c4-b3b1c52c06dd.jpg)

after 2nd import
![after_2nd_Import](https://user-images.githubusercontent.com/51681379/125052987-2bea8880-e0c2-11eb-9695-751fb9af661c.jpg)

i could not find the differences like duplication of products.

**Comment by engcom-Delta** [comment]
There has no update since 14 days. Hence it is closed.
Kindly raise new issue if required or re-open the existing issue.

Thanks
