### ISSUE TITLE
Add deleteCustomer mutation

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#33383]
*As a developer I want to be able to delete a customer via graphql so that I can build a button for customers to click on to delete their account when logged in to comply with the GDPR.*

### AC
* A mutation exists with the name 'deleteCustomer' which takes no arguments and returns a boolean and is capable of throwing an exception if anything went wrong.
* Calling the mutation will delete the customer identified by the customer token which must be sent along in the request header.

**Comment by oneserv-heuser** [comment]
I can confirm that this mutation doesn't exist on a magento vanilla instance 😄

**Comment by oneserv-heuser** [comment]
I can confirm that this mutation doesn't exist on a magento vanilla instance 😄

**Comment by khrystynastolbova** [comment]
@magento I am working on this
