### ISSUE TITLE
GraphQl products query layered navigation filters return incorrect child categories list

### ISSUE THREAD

**Issue by rohan-magento** [magento/magento2#33387]
### Preconditions (*)

1. Magento 2.4.1 Adobe Commerce & Open Souce both.
2. Use sample data to reproduce the issue

### Steps to reproduce (*)

1. Use below GraphqlQl request with sample data setup 
Use category ID - 21 with default store code in the header

`
query {
  products(filter: {category_id: {eq: "21"}}) {
    aggregations {
      attribute_code
      count
      label
      options {
        count
        label
        value
      }
    }
  }
}
`

### Expected result (*)

1. Only these 4 sub-categories should appear in GraphQl response.

![image](https://user-images.githubusercontent.com/75991143/123914933-93efef00-d99d-11eb-9ede-47f173986039.png)

### Actual result (*)

1. More than 4 categories in aggregation result -

![image](https://user-images.githubusercontent.com/75991143/123915157-d285a980-d99d-11eb-9845-9803252aff83.png)

The response is more than 4 child categories which wrong here (same response below) -

`        {
          "attribute_code": "category_id",
          "count": 11,
          "label": "Category",
          "options": [
            {
              "count": 50,
              "label": "Tops",
              "value": "21"
            },
            {
              "count": 14,
              "label": "Bras & Tanks",
              "value": "26"
            },
            {
              "count": 13,
              "label": "New Luma Yoga Collection",
              "value": "8"
            },
            {
              "count": 13,
              "label": "Performance Fabrics",
              "value": "35"
            },
            {
              "count": 12,
              "label": "Jackets",
              "value": "23"
            },
            {
              "count": 12,
              "label": "Hoodies & Sweatshirts",
              "value": "24"
            },`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rohan-magento** [comment]
@magento give me 2.4-develop instance

**Comment by rohan-magento** [comment]
I can confirm that the same issue exists on the vanilla Magento instance too.

![image](https://user-images.githubusercontent.com/75991143/123921200-5fcbfc80-d9a4-11eb-8103-a1e56d9665b8.png)

![image](https://user-images.githubusercontent.com/75991143/123921285-7a05da80-d9a4-11eb-8eb9-c2efefbf7674.png)

**Comment by prabhakaran777** [comment]
@rohan-magento is that we are not indexing category related data in elastic search index right ?

**Comment by rohan-magento** [comment]
@prabhakaran777 Yes, indexing and elastic search are all good but still, this issue exists.

**Comment by prabhakaran777** [comment]
@rohan-magento yeah. do you have any idea for this problem.

**Comment by engcom-Delta** [comment]
Hi @rohan-magento ,
We tried to reproduce the issue and found it is reproducible on Magento 2.4 Develop.
query results are more than 4 categories in aggregation result.
Kindly find the attached snapshots for reference.
![4_catagories in UI](https://user-images.githubusercontent.com/51681379/124268179-d27cd980-db56-11eb-8161-c781fb9ee92b.jpg)


Query Response Results:
{
  "data": {
    "products": {
      "aggregations": [
        {
          "attribute_code": "price",
          "count": 7,
          "label": "Price",
          "options": [
            {
              "count": 12,
              "label": "20-30",
              "value": "20_30"
            },
            {
              "count": 15,
              "label": "30-40",
              "value": "30_40"
            },
            {
              "count": 4,
              "label": "40-50",
              "value": "40_50"
            },
            {
              "count": 10,
              "label": "50-60",
              "value": "50_60"
            },
            {
              "count": 5,
              "label": "60-70",
              "value": "60_70"
            },
            {
              "count": 3,
              "label": "70-80",
              "value": "70_80"
            },
            {
              "count": 1,
              "label": "80-90",
              "value": "80_90"
            }
          ]
        },
        {
          "attribute_code": "category_id",
          "count": 11,
          "label": "Category",
          "options": [
            {
              "count": 50,
              "label": "Tops",
              "value": "21"
            },
            {
              "count": 14,
              "label": "Bras & Tanks",
              "value": "26"
            },
            {
              "count": 13,
              "label": "New Luma Yoga Collection",
              "value": "8"
            },
            {
              "count": 13,
              "label": "Performance Fabrics",
              "value": "35"
            },
            {
              "count": 12,
              "label": "Jackets",
              "value": "23"
            },
            {
              "count": 12,
              "label": "Hoodies & Sweatshirts",
              "value": "24"
            },
            {
              "count": 12,
              "label": "Tees",
              "value": "25"
            },
            {
              "count": 12,
              "label": "Women Sale",
              "value": "30"
            },
            {
              "count": 12,
              "label": "Tees",
              "value": "33"
            },
            {
              "count": 11,
              "label": "Erin Recommends",
              "value": "34"
            },
            {
              "count": 6,
              "label": "Eco Friendly",
              "value": "36"
            }
          ]
        },
        {
          "attribute_code": "climate",
          "count": 10,
          "label": "Climate",
          "options": [
            {
              "count": 8,
              "label": "All-Weather",
              "value": "206"
            },
            {
              "count": 4,
              "label": "Cold",
              "value": "207"
            },
            {
              "count": 17,
              "label": "Cool",
              "value": "208"
            },
            {
              "count": 35,
              "label": "Indoor",
              "value": "209"
            },
            {
              "count": 16,
              "label": "Mild",
              "value": "210"
            },
            {
              "count": 2,
              "label": "Rainy",
              "value": "211"
            },
            {
              "count": 21,
              "label": "Spring",
              "value": "212"
            },
            {
              "count": 28,
              "label": "Warm",
              "value": "213"
            },
            {
              "count": 8,
              "label": "Windy",
              "value": "214"
            },
            {
              "count": 6,
              "label": "Wintry",
              "value": "215"
            }
          ]
        },
        {
          "attribute_code": "color",
          "count": 10,
          "label": "Color",
          "options": [
            {
              "count": 12,
              "label": "Black",
              "value": "49"
            },
            {
              "count": 22,
              "label": "Blue",
              "value": "50"
            },
            {
              "count": 1,
              "label": "Brown",
              "value": "51"
            },
            {
              "count": 8,
              "label": "Gray",
              "value": "52"
            },
            {
              "count": 18,
              "label": "Green",
              "value": "53"
            },
            {
              "count": 21,
              "label": "Orange",
              "value": "56"
            },
            {
              "count": 23,
              "label": "Purple",
              "value": "57"
            },
            {
              "count": 18,
              "label": "Red",
              "value": "58"
            },
            {
              "count": 9,
              "label": "White",
              "value": "59"
            },
            {
              "count": 16,
              "label": "Yellow",
              "value": "60"
            }
          ]
        },
        {
          "attribute_code": "eco_collection",
          "count": 2,
          "label": "Eco Collection",
          "options": [
            {
              "count": 38,
              "label": "0",
              "value": "0"
            },
            {
              "count": 12,
              "label": "1",
              "value": "1"
            }
          ]
        },
        {
          "attribute_code": "erin_recommends",
          "count": 2,
          "label": "Erin Recommends",
          "options": [
            {
              "count": 39,
              "label": "0",
              "value": "0"
            },
            {
              "count": 11,
              "label": "1",
              "value": "1"
            }
          ]
        },
        {
          "attribute_code": "material",
          "count": 18,
          "label": "Material",
          "options": [
            {
              "count": 9,
              "label": "Cocona&reg; performance fabric",
              "value": "142"
            },
            {
              "count": 6,
              "label": "Fleece",
              "value": "144"
            },
            {
              "count": 2,
              "label": "Hemp",
              "value": "145"
            },
            {
              "count": 1,
              "label": "Jersey",
              "value": "146"
            },
            {
              "count": 1,
              "label": "LumaTech&trade;",
              "value": "147"
            },
            {
              "count": 6,
              "label": "Lycra&reg;",
              "value": "148"
            },
            {
              "count": 2,
              "label": "Mesh",
              "value": "149"
            },
            {
              "count": 1,
              "label": "Microfiber",
              "value": "150"
            },
            {
              "count": 10,
              "label": "Nylon",
              "value": "151"
            },
            {
              "count": 22,
              "label": "Polyester",
              "value": "152"
            },
            {
              "count": 13,
              "label": "Spandex",
              "value": "153"
            },
            {
              "count": 16,
              "label": "Cotton",
              "value": "154"
            },
            {
              "count": 3,
              "label": "HeatTec&reg;",
              "value": "155"
            },
            {
              "count": 5,
              "label": "EverCool&trade;",
              "value": "156"
            },
            {
              "count": 9,
              "label": "Organic Cotton",
              "value": "157"
            },
            {
              "count": 1,
              "label": "TENCEL",
              "value": "159"
            },
            {
              "count": 6,
              "label": "CoolTech&trade;",
              "value": "160"
            },
            {
              "count": 4,
              "label": "Wool",
              "value": "163"
            }
          ]
        },
        {
          "attribute_code": "new",
          "count": 2,
          "label": "New",
          "options": [
            {
              "count": 37,
              "label": "0",
              "value": "0"
            },
            {
              "count": 13,
              "label": "1",
              "value": "1"
            }
          ]
        },
        {
          "attribute_code": "pattern",
          "count": 4,
          "label": "Pattern",
          "options": [
            {
              "count": 1,
              "label": "Checked",
              "value": "198"
            },
            {
              "count": 2,
              "label": "Color-Blocked",
              "value": "199"
            },
            {
              "count": 46,
              "label": "Solid",
              "value": "201"
            },
            {
              "count": 1,
              "label": "Striped",
              "value": "203"
            }
          ]
        },
        {
          "attribute_code": "performance_fabric",
          "count": 2,
          "label": "Performance Fabric",
          "options": [
            {
              "count": 35,
              "label": "0",
              "value": "0"
            },
            {
              "count": 15,
              "label": "1",
              "value": "1"
            }
          ]
        },
        {
          "attribute_code": "sale",
          "count": 2,
          "label": "Sale",
          "options": [
            {
              "count": 38,
              "label": "0",
              "value": "0"
            },
            {
              "count": 12,
              "label": "1",
              "value": "1"
            }
          ]
        },
        {
          "attribute_code": "size",
          "count": 5,
          "label": "Size",
          "options": [
            {
              "count": 49,
              "label": "XS",
              "value": "171"
            },
            {
              "count": 50,
              "label": "S",
              "value": "172"
            },
            {
              "count": 50,
              "label": "M",
              "value": "173"
            },
            {
              "count": 50,
              "label": "L",
              "value": "174"
            },
            {
              "count": 49,
              "label": "XL",
              "value": "175"
            }
          ]
        },
        {
          "attribute_code": "style_general",
          "count": 19,
          "label": "Style",
          "options": [
            {
              "count": 4,
              "label": "Insulated",
              "value": "116"
            },
            {
              "count": 12,
              "label": "Jacket",
              "value": "117"
            },
            {
              "count": 6,
              "label": "Lightweight",
              "value": "119"
            },
            {
              "count": 5,
              "label": "Hooded",
              "value": "120"
            },
            {
              "count": 1,
              "label": "Heavy Duty",
              "value": "121"
            },
            {
              "count": 2,
              "label": "Rain Coat",
              "value": "122"
            },
            {
              "count": 3,
              "label": "Hard Shell",
              "value": "123"
            },
            {
              "count": 8,
              "label": "Soft Shell",
              "value": "124"
            },
            {
              "count": 4,
              "label": "Windbreaker",
              "value": "125"
            },
            {
              "count": 5,
              "label": "&frac14; zip",
              "value": "127"
            },
            {
              "count": 12,
              "label": "Full Zip",
              "value": "128"
            },
            {
              "count": 2,
              "label": "Reversible",
              "value": "129"
            },
            {
              "count": 5,
              "label": "Bra",
              "value": "130"
            },
            {
              "count": 5,
              "label": "Sweatshirt",
              "value": "132"
            },
            {
              "count": 9,
              "label": "Tank",
              "value": "134"
            },
            {
              "count": 12,
              "label": "Tee",
              "value": "135"
            },
            {
              "count": 10,
              "label": "Pullover",
              "value": "136"
            },
            {
              "count": 9,
              "label": "Hoodie",
              "value": "137"
            },
            {
              "count": 1,
              "label": "Camisole",
              "value": "141"
            }
          ]
        }
      ]
    }
  }
}

Hence  added the label 'Issue confirmed'

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42783` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by korovitskyi** [comment]
@magento I am working on this
