### ISSUE TITLE
No way to update layout after changing something

### ISSUE THREAD

**Issue by jstuardo** [magento/magento2#3338]
Hello...

I am creating a custom theme for Magento 2. I need to customize the layout existng in app/design/frontend/[Vendor]/[CustomTheme]/Magento_Theme/layout] whose name is default.xml.

I have changed it by adding and changing some things, however, changes are not taken into account. I always see the original layout.

I have disabled cache, however, just in case, I have flushed it but it was unsuccessful.

How can I reload the layout? maybe it was stored in database, but, how can I refresh it?

Thanks
Jaime

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
