### ISSUE TITLE
Captcha image for password reset not displayed if S3 storage adapter is active

### ISSUE THREAD

**Issue by apachler** [magento/magento2#33381]
### Preconditions (*)
1. Magento 2.4.2
2. PHP 7.4
3. Activated S3 storage adapter in Magento

### Steps to reproduce (*)
1. Browse to "/customer/account/forgotpassword/" or "/backendfrontname/admin/auth/forgotpassword/"

### Expected result (*)
1. The captcha image is shown

### Actual result (*)
1. The captcha image is NOT shown

### Details

Since the S3 storage adapter is active, the captcha image is served from the S3 bucket but the image is not existing on the bucket at the time of the request. Some seconds later the image arrives at the S3 bucket and the end user is able to manually reload the image. This issue leads to confusion of the end user but a workaround is available.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @apachler,

I have tried to reproduce the issue in Magento 2.4-develop branch with mentioned steps. To enable S3 storage we have followed this [devdocs link](https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html) and [this link](https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html).

After enabling, tried to access the forgot password page, but we are able to get the captcha image. Please refer below screenshot:

![image](https://user-images.githubusercontent.com/51681618/133603425-10cad508-4f5d-497c-a3a3-c697222e4bad.png)

Please try to reproduce the issue in Magento 2.4-develop branch and let us know, if you are still able to reproduce it.

Thanks

**Comment by apachler** [comment]
Thanks for giving it a shot.
You are right, i am also not able to reproduce that with the Magento 2.4-develop branch.

**Comment by engcom-Hotel** [comment]
Hello @apachler,

Thanks for the confirmation!

As per the feedback, we are closing this issue.

Thanks
