### ISSUE TITLE
Eliminate laminas-mvc from Magento\Framework\Console\Cli

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#33391]
This ticket is related to <https://github.com/magento/magento2/issues/33338>

Magento/Framework/Console/Cli.php uses Magento/Setup/Application class, which, in turn, uses Laminas\Mvc.

We need to investigate how to get rid of Magento/Setup/Application.php class (or its laminas dependency)
### Resolution

Removing this dependency from the Magento code leads to a large refactoring of installation functionality

We decided not to remove this dependency

**1. The Laminas dependencies on which the `laminas/laminas-mvc` depends and incompatible with PHP 8.0**
- `laminas/laminas-stratigility` 2.1.1 (in require >2.0.1 && <=2.2) requires php (^5.6 || ^7.0) - can be updated to 3.4.0

**2. The Laminas dependencies on which the `laminas/laminas-mvc` depends and incompatible with PHP 8.1**
- `laminas/laminas-config` 3.6.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-diactoros` 2.6.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-psr7bridge` 1.3.1 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-router` 3.4.5 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-servicemanager` 3.7.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-stratigility` 2.1.1 requires php (^5.6 || ^7.0) - **the latest version 3.4.0 requires php: ^7.3 || ~8.0.0**
- `laminas/laminas-view` 2.12.0 requires php (^7.3 || ~8.0.0)

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by anzin** [comment]
@magento I am working on this

**Comment by anzin** [comment]
**Hello team, this is dependency tree for laminas-mvc:**

**laminas-mvc** required in the next  laminas libraries:

- **laminas/laminas-modulemanager** _required in the next  laminas libraries:_
    - **laminas/laminas-hydrator** _required in the next  laminas libraries:_
         - **laminas/laminas-db**
    - **laminas/laminas-mvc**
    - **laminas/laminas-view**


- **laminas/laminas-view** _required in the next  laminas libraries:_
    - **laminas/laminas-i18n** _required in the next  laminas libraries:_
         - **laminas/laminas-config**
         - **laminas/laminas-router**
         - **laminas/laminas-validator**
         - **laminas/laminas-view**
    - **laminas/laminas-mvc**

Thank you.

cc. @andrewbess

**Comment by andrewbess** [comment]
Hello @anzin 
Thank you for your research here.
Great job.

**Comment by andrewbess** [comment]
The Laminas dependencies on which the `laminas/laminas-mvc` depends and incompatible with PHP 8.0
- `laminas/laminas-stratigility` 2.1.1 (in require >2.0.1 && <=2.2) requires php (^5.6 || ^7.0) - can be updated to 3.4.0

The Laminas dependencies on which the `laminas/laminas-mvc` depends and incompatible with PHP 8.1
- `laminas/laminas-config` 3.6.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-diactoros` 2.6.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-psr7bridge` 1.3.1 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-router` 3.4.5 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-servicemanager` 3.7.0 requires php (^7.3 || ~8.0.0)
- `laminas/laminas-stratigility` 2.1.1 requires php (^5.6 || ^7.0) - **the latest version 3.4.0 requires php: ^7.3 || ~8.0.0**
- `laminas/laminas-view` 2.12.0 requires php (^7.3 || ~8.0.0)

cc @fascinosum
