### ISSUE TITLE
Order retry mechanisum issue

### ISSUE THREAD

**Issue by zarnar** [magento/magento2#33405]
Hi,

Right now we are facing problem that sometimes we take payment from paypal or braintree but order do not place because we take first payment and then place order but in case when pla

cing order if we face problem like table get locked or due to any error order get not placed then we need to retry order placing functions and mechanism. We need to try max 3 times to place an order. I will explain this task on call with details if require.

Any customer try to place order using any payment method and if something went wron

g from our side e.g DB got full, table got locked, server went down, table has problem then when magento convert quote to order it rollback transactions. So we need to try place order process again from coding for that customer and need to see if it get success or not. same apply 3rd time too. 

![screenshot-cpjira selfip com_8080-2021 07 02-18_14_02](https://user-images.githubusercontent.com/32868943/124276460-753a5580-db61-11eb-9ef9-7716d3642616.png)

**Comment by engcom-Hotel** [comment]
Hi @zarnar,

Please help us in providing more details in order to reproduce the issue, like:

1. Preconditions
2. Steps to reproduce 
3. Expected Result
4. Actual result.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @zarnar,

It seems that your issue has been resolved. As we are unable to get your response for the last 14 days, we are closing this issue for now. In case you still facing the issue then you can reopen it.

Thanks
