### ISSUE TITLE
Migrate old plugin jQuery-Storage-API

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#33416]
https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/jquery.storageapi.min.js

This plugin is no longer maintained (Announcements from origin repo author)

A new one but not latest, without dependencies with jQuery, is available : https://github.com/julien-maurel/js-storage (but seem not active currently)

Should we consider upgrade to js-storage or use something new lib or maybe new custom local-storage implements for magento

### Proposed solution

Implements new custom local-storage

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
cc: @sivaschenko not too much high priority but i think we should note this

**Comment by ihor-sviziev** [comment]
@mrtuvn, this storage API library has too many issues. It was causing https://github.com/magento/magento2/issues/7931 https://github.com/magento/magento2/issues/16568 https://github.com/magento/magento2/issues/17195 https://github.com/magento/magento2/issues/27355.
The library you're suggesting had its last release in 2017, which is pretty old and feels not supported.

I think in most cases, we could use native local storage with a fallback to a local array, similar to https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Ui/view/base/web/js/lib/core/storage/local.js#L40-L79.

What do you think?

**Comment by sivaschenko** [comment]
@fascinosum

**Comment by engcom-Hotel** [comment]
Hello @mrtuvn,

I have checked the Github repo related to that [lib](https://github.com/julien-maurel/jQuery-Storage-API), it is not maintained now. And for [another library](https://github.com/julien-maurel/js-storage), has a very old commit.

So we need to think of some other way to do it. I am confirming this issue for further analaysis. 

Thanks

**Comment by in-session** [comment]
Is there any news on this yet? 

![image](https://user-images.githubusercontent.com/16542619/166487740-b8602562-d7cb-40a6-b200-f6306fc8115f.png)

**Comment by mrtuvn** [comment]
cc: @andrewbess possible know something

**Comment by mrtuvn** [comment]
Look like we have some updated internals at latest develop code
AC-2627: Migrate from `jquery/storageapi` to `js-storage/js.storage`
cc: @in-session

**Comment by mrtuvn** [comment]
So i think we can close this ticket
