### ISSUE TITLE
Avoid extending actions from \Magento\Framework\App\Action\Action cause X-Magento-Vary cookie problem

### ISSUE THREAD

**Issue by 06romix** [magento/magento2#33412]
### Summary
It is not possible to use `\Magento\Framework\App\ActionInterface` without `\Magento\Framework\App\Action\AbstractAction` because plugins for filling HTTP Context bound to `\Magento\Framework\App\Action\AbstractAction::dispatch` instaed of `\Magento\Store\App\Action\Plugin\Context::beforeDispatch`

### Preconditions (*)
1. Discovered on Magento 2.4.1
2. Have two or more currency

### Steps to reproduce (*)
1. Create new ajax action implementing `\Magento\Framework\App\ActionInterface` (do not use `\Magento\Framework\App\Action\Action`)
2. Go to the frontend
3. Change currency from default (USD) to EUR
4. Make ajax call using either jQuery.get or fetch
5. Check response Set-Cookie headers
5. Reload page
6. Check selected currency

### Expected result (*)
1. After reloading the page the currency is EUR
2. Ajax response contains `Set-Cookie: X-Magento-Vary=........`

### Actual result (*)
1. After reloading the page the currency is USD
2. Ajax response contains `Set-Cookie: X-Magento-Vary=deleted;`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Not sure but you want to say following magento best practices will lead to another problem ?

**Comment by 06romix** [comment]
Although dispatching events were moved from `\Magento\Framework\App\Action\AbstractAction,` plugins are still there.
So, yes, following this particular Magento best practice will lead to the cache problem.

**Comment by mrtuvn** [comment]
Not sure how impact but in my opinion we should move to `Magento\Framework\App\ActionInterface`

**Comment by 06romix** [comment]
One more plugin for `\Magento\Framework\App\Action\AbstractAction::dispatch`

`\Magento\Catalog\Plugin\Framework\App\Action\ContextPlugin `

**Comment by mrtuvn** [comment]
Seem we still used old approach controller somewhere. Some code already use new controller way (implement Magento\Framework\App\ActionInterface) but some other doesn't not and still use old way
Another example  
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/Controller/Currency/SwitchAction.php#L9

**Comment by kanevbg** [comment]
?

**Comment by ihor-sviziev** [comment]
Hi @06romix @mrtuvn,
Unfortunately, it's unclear what damage this issue causes, how often it reproduces, and how critical it is to fix.
Could you explain in a bit more detail the issue it causes and how to reproduce it (maybe with some screenshots)? Does it happen in the Magento Core, or only in a custom extension(s)?

**Comment by engcom-Hotel** [comment]
Hello @06romix @mrtuvn,

Have you got a chance to check this https://github.com/magento/magento2/issues/33412#issuecomment-1151057477? Please provide us with some more information on this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @06romix,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by mfickers** [comment]
We've run into an issue using multiple display currencies and using Varnish as FPC.

When a custom controller that doesn't extend AbstractAction is called, the response sets a new X-Magento-Vary cookie that does not depend on the selected currency. This leads to issues where some pages are cached with the wrong currency displayed.

Can this issue be reopened?

**Comment by engcom-Hotel** [comment]
Hello @mfickers,

Thank you for your response!

We will be happy in reopening this issue, but as per this https://github.com/magento/magento2/issues/33412#issuecomment-1151057477, we need more information for issue reproduction.

Please help us with the same.
