### ISSUE TITLE
Error messages are not displayed in the login page.

### ISSUE THREAD

**Issue by majidiyan** [magento/magento2#33415]
### Preconditions (*)

1. 2.3.6-p1
2. 2.3.7

### Steps to reproduce (*)

1. Go to customer login page.
2. Try to login with true email, and wrong password.

### Expected result (*)

Displaying error message box with a message like "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later." .

### Actual result (*)

No message box is displaying.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

-  Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @majidiyan. Thank you for your report.
Not able to replicate the issue as per your description.
Can you please provide additional steps in which this issue occurred and also kindly verify in latest magento instance

**Comment by majidiyan** [comment]
Hello krishprakash !
In latest Magento version all is ok (2.4), but I need to fix this bug on 2.3.6-p1 and 2.3.7.
Steps to bug is easy, simply go to customer login page  site.com/customer/account/login  and try to login with wrong password.
Expected to get pink box error message, but nothing is showing.

**Comment by krishprakash** [comment]
Hi @majidiyan.Thank you for your feedback.
We are not processed the issue which is not reproduced on latest instance.
So kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
