### ISSUE TITLE
create customer attribute in magento2

### ISSUE THREAD

**Issue by VLCSolutions** [magento/magento2#3342]
Unable to create a customer attribute which should show only in backend (admin panel) and should not show in frontend. I have not found any property set to show in adminhtml.
![customer_attribute](https://cloud.githubusercontent.com/assets/14070968/12908072/fb3c063e-cf18-11e5-9008-db164075e50a.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/create-customer-attribute-in-magento2/idi-p/44753).
