### ISSUE TITLE
Excel writer produces invalid files for numbers preceded by spaces

### ISSUE THREAD

**Issue by thomasheller** [magento/magento2#33422]
### Preconditions (*)
Encountered in production with Magento 2.4.1, but this will happen with any Magento2 version, since the code hasn't changed in 7 years.

### Steps to reproduce (*)
1. Create an instance of `Magento\Framework\Convert\Excel` with an `ArrayIterator` over an array containing a field with a value like `␣123` (i.e. space followed by digits, read `␣` as space).
2. Call `convert` or `write` on the object.
3. Try opening the resulting file with a current version of Microsoft Excel or LibreOffice Calc. They will refuse to open the file or display `NaN` for the value respectively.

### Expected result (*)
The Excel XML should encode field as a `String`:

```xml
<Data ss:Type="String"> 123</Data>
```

### Actual result
The value is encoded as `Number`:

```xml
<Data ss:Type="Number"> 123</Data>
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Note:** For Microsoft Excel users this can be problematic, as Excel does not report the actual error. The Excel file needs to be opened as an XML file, and the value of `ss:Type` needs to be fixed manually to be able to import the file at all. LibreOffice Calc _does_ open the file, but doesn't show a warning and silently replaces the cell's value with `NaN`, so people may not even be aware that some data is actually missing.

### Cause

The Magento2 class mainly relies on PHP's `is_numeric` function to determine the `ss:Type`, which causes the bug: https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/lib/internal/Magento/Framework/Convert/Excel.php#L153

### Workaround

From a developer's perspective, the issue can be circumvented by `trim`ing all numeric values before passing them to the `Excel` class.

**Comment by zakdma** [comment]
@magento give me 2.4-develop instance

**Comment by zakdma** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @thomasheller,

We have tried to reproduce the issue in Magento 2.4-develop. We have passed the content type in create function as below:

`$data[] = ['message' => ' 123'];

        $convert = new \Magento\Framework\Convert\Excel(new \ArrayIterator($data));
        $file = $convert->convert('single_sheet');
        $fileName = "test_without_space.xml";
        return $this->_fileFactory->create($fileName, $file, DirectoryList::VAR_DIR, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');`

Please try once with a given solution or let us know if we missed anything in order to reproduce the issue.


Thanks

**Comment by thomasheller** [comment]
@engcom-Hotel Well, what output do you get when you actually run that code, i.e. what's the value of the `ss:Type` attribute in the XML file on your instance?

**Comment by engcom-Hotel** [comment]
Hello @thomasheller,

In my case the value of the ss:Type is number. Please try to reproduce this in the 2.4-develop branch and let us know if you still facing the issue.

Thanks

**Comment by thomasheller** [comment]
Hello @engcom-Hotel

I would kindly ask you to read my original bug report again. The value of `ss:Type` being `Number` is actually the issue, you have successfully reproduced it. Opening the resulting file in Excel or LibreOffice will fail. The expected value for numbers preceded by whitespace is `String`.

**Comment by engcom-Hotel** [comment]
Hello @thomasheller,

Let me try to reproduce the issue once again. I will update you on this.

Thanks

**Comment by engcom-Bravo** [comment]
The issue is confirmed on 2.4-develop branch.
Here are the steps to reproduce the issue.

1. Create an instance of Magento\Framework\Convert\Excel with an ArrayIterator over an array containing a field
2. Call convert or write on the object.
3. Try opening the resulting file with a current version of Microsoft Excel. It will refuse to open the file.

Sample code
```
$data[] = ['message' => " 1233"];
    $convert = new \Magento\Framework\Convert\Excel(new \ArrayIterator($data));
    $file = $convert->convert('single_sheet');
    $fileName = "test_without_space.xml";
    return $this->_fileFactory->create($fileName, $file, DirectoryList::VAR_DIR, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

```

Generated file should contain the encoded value as string but it is coming as number
`<Data ss:Type="Number"> 1233</Data>`

**Comment by hutychivan** [comment]
@magento I am working on this
