### ISSUE TITLE
Issue at checkout when trying to enter new billing address

### ISSUE THREAD

**Issue by AdrianChungie** [magento/magento2#33444]
### Preconditions (*)

1. Magento version 2.4.2
2. I am using a custom theme in this example, however I tested with Magento Luma theme and I get the same result
3. I am using sample data, however I tested on 2 different environments with real product data and same result.

### Steps to reproduce (*)

1. Go to checkout
2. On the Review & Payments screen under Payment Method
3. Uncheck "My billing and shipping address are the same"
4. It does not show the fields to add a new address, it will just be blank and gives a error in console

### Expected result (*)

1. It should show fields to enter a new billing address

### Actual result (*)
![magento 2 billing address issue at checkout](https://user-images.githubusercontent.com/1384964/124962569-c7112e80-dfec-11eb-8a8d-a5e2fb43d167.png)

1. Does not show the billing address fields, instead it just shows nothing
2. In the browser console it gives the error

```
Uncaught ReferenceError: Unable to process bindi
![magento 2 billing address issue at checkout](https://user-images.githubusercontent.com/1384964/124962540-be205d00-dfec-11eb-9a8d-90fd39aed694.png)
ng "afterRender: function(){return autoFillAddress }"
Message: autoFillAddress is not defined
afterRender http://domain.com/static/version1619210092/frontend/bs_complex/bs_complex1/en_US/knockoutjs/knockout.js line 2982 > Function:3
    init http://domain.com/static/version1619210092/frontend/bs_complex/bs_complex1/en_US/Magento_Ui/js/lib
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
Seem maybe not related with magento code! Have you check function customised code "AutoFillAddress". This is not standard of default magento. Also if possible please provide module sample can help easier to indicate issue

**Comment by AdrianChungie** [comment]
@mrtuvn yea you are right. I tested it again on a clean environment and there was no issue. I guess there is a issue with the theme that I am using, or an extension.

Sorry about that, you can close this issue. I will investigate further on my own.
