### ISSUE TITLE
Disgusting Magento 2 Layout and design

### ISSUE THREAD

**Issue by kuldip1** [magento/magento2#3344]
Hi

Magento 2 CE disgusting to easy access all admin pages. It's take very long time to load becuase of jQuery Migration is loaded so. So please use magento 1.9 stable version to use.

**Comment by prasad8803** [comment]
it's true. Magento CE 2.0.2 and EE 2.0.2 admin pages taking too long time even we don't have records

**Comment by mazhalai** [comment]
@kuldip1 and @prasad8803 have you setup varnish as [recommended](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html)? Also, what mode are you in? developer or production? If there is a specific issue that we can fix, please post here.

**Comment by davidalger** [comment]
Closing due to no response from OP.
