### ISSUE TITLE
GraphQL Customer Orders query returns only current store orders

### ISSUE THREAD

**Issue by pawel-siejba** [magento/magento2#33450]
### Preconditions (*)

1. Magento 2.4.1 or higher
2. Customer account shared globally
3. Customer Account has orders placed from multiple store views
4. (Optionally) Venia Storefront

### Steps to reproduce (*)

1. Query:
`{
  customer {
   orders {
      items {
        number
      }
    }
  }
}`

### Expected result (*)

1. See all orders, as in Luma

### Actual result (*)

1. See only orders from the currently selected store(Store header)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42856` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
