### ISSUE TITLE
Authentication PopUp showing even when customer is already logged in

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#33458]
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

I could not figure out how to reproduce this every time, it happens randomly.

If you are logged in as a customer and try to go to checkout, then sometimes the popup-authentication window shows:

![bug](https://user-images.githubusercontent.com/16349349/125267004-af94b700-e306-11eb-960f-6c98818270f9.PNG)

### Expected result (*)

Checkout should load

### Actual result (*)

Popup shows instead

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
hi!
In theory that popup only show when you have disabled guest checkout and customer required login when process checkout page. You can test in magento build instance by require it in comment
Use
magento give me 2.4-develop will request clean instance for test purpose if you have clear step

**Comment by mrtuvn** [comment]
dunno maybe related with persistent customer data from frontend still remain

**Comment by engcom-Delta** [comment]
Hi @Eddcapone,
Kindly update expected results and actual results. So that we will try to replicate the issue.
Hence added the label 'Needs Update'.

Thanks

**Comment by Eddcapone** [comment]
@engcom-Delta I updated it.

**Comment by engcom-Delta** [comment]
Hi @Eddcapone,

Tried reproducing the issue on Magento 2.4.2 ( Backend & frontend). unfortunately we are not able to replicate it . it works as expected.

Thanks

**Comment by mrtuvn** [comment]
Imho i think this not easy to reproduce with clean install case. It's may require magento store with custom module/theme with some data. Can you able share your store url ?

**Comment by engcom-Delta** [comment]
Hi @mrtuvn,
Ok. Here is my store (local ) url: http://local.magentop241.com/.

Thanks

**Comment by engcom-Delta** [comment]
There has no update from the reporter from 14 days .Hence closing it .
Kindly raise new issue if required or re-open the existing ticket.
