### ISSUE TITLE
Issues creating/updating simple product

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3345]
``` php
$product = $productFactory->create();
if ($id) {
    $product->load($id);
}

$product
    ...
    ->setStockData([
        'qty'         => $quantity,
        'is_in_stock' => $quantity ? 1 : 0
    ])
    ->setPrice($price)
    ->addImageToMediaGallery($file, ['image', 'small_image', 'thumbnail'], true);
    ->save();
```

Known issues:
- `setStockData` works only for new product
- `addImageToMediaGallery` adds image as expected however:
  - image is NOT marked as "Base" in admin product edit view
  - image is NOT shown in front-end single product view
  - image is set only for default store view - it's not shown for other store views

**Comment by jsakars** [comment]
@magento-team could You please look into this?

**Comment by benmarks** [comment]
No need to tag us, we'll look into it :-)

**Comment by werdlv** [comment]
While playing around setting `$product->setStoreId(0)` I noticed that image does get set correctly except it gets marked as "Hide from Product Page"

**Comment by jsakars** [comment]
Update regarding images - product must be saved from global scope `$product->setStoreId(0)`

**Comment by jsakars** [comment]
Update regarding stock - `$product->setStockData()` should not be used.
Instead save the product and then save the stock item:

``` php
$product->save();
$stockItem = $stockRegistry->getStockItem($product->getId());
$stockItem
    ->setQty($quantity)
    ->setIsInStock($quantity ? true : false)
    ->save();
```

I think the real issue is that M2 is not well enough documented from development perspective. Even source code examples and unit & integration tests might hold wrong or partial answer.

**Comment by veloraven** [comment]
@werdlv thank you for your feedback.
Please provide the used Magento version if this issue is still actual, or close it if it is not.
Please also format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
