### ISSUE TITLE
Issue when importing CSV with empty rows

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#3346]
When importing a CSV with a single empty row inbetween a lot of different, filled rows Magento only outputs "Columns number: "18" have empty headers" instead of "Columns number: "R" have empty headers". 

This is just a minor spelling Bug, but I'd be better if Magento shows the character of the column instead of the number, for visibility purposes.

**Comment by katmoon** [comment]
Hi,

Displaying 'R' or 18 as a column number depends on your settings in Excel (or similar app that you use). There is no such information in CSV file, so Magento cannot know about this.

Does this answers your issue?

Thanks,
Kateryna.

**Comment by katmoon** [comment]
I'm closing the ticket since there is no response for 2 weeks.
Please feel free to reopen if you have any questions.
