### ISSUE TITLE
Unable to import a Theme with a frontend and a backend

### ISSUE THREAD

**Issue by Meberem** [magento/magento2#33479]
### Preconditions (*)

1. Magento 2.4
2. Have a Theme with a `frontend` and a `adminhtml` i.e.
```
app/design/
		  adminhtml/Vendor/ThemeName
          frontend/Vendor/ThemeName
```

### Steps to reproduce (*)

1. Have an installed instance
2. run `bin/magento app:config:import`

### Expected result (*)

1. The themes are imported and available

### Actual result (*)

1. Cli Error: `Import failed: Item (Magento\Theme\Model\Theme) with the same ID "" already exists.`

### Observations
This appears to be the result of an incorrect key generation. Debugging yields that both the frontend and backend get the following key: adminhtml/vendor/theme-name. This comes from `Magento\Theme\Model\Theme:getArea()` as the the `EmulatedAdminhtmlAreaProcessor` is in effect the `area` will always be `adminhtml` hence the conflict.

I have also observed that the error message is unsatifactory i.e. empty. Should the exception in `Magento\Framework\Data\Collection:addItem()` use the already computed, non-null `$itemId` that will be used as the key rather than call `$item->getId()` which in this case returns null?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Meberem,

We tried to reproduce the issue but unfortunately not getting any error . we are able to uploaded.
Hence, request to help me if it happens in any specific test scenario.

Steps followed:

1.	Download new theme from Magento community (free)
2.	Extract the zip folder ‘orson_v1.0.0_1_2’
3.	After extracting upload the app folder into magento root folder
4.	Then run below commands
Run command line: php bin/magento module:enable MGS_Mpanel
Run command line: php bin/magento module:enable MGS_Portfolio
Run command line: php bin/magento module:enable MGS_Testimonial
Run command line: php bin/magento module:enable MGS_Brand
Run command line: php bin/magento module:enable MGS_Core
Run command line: php bin/magento module:enable MGS_Promobanners
Run command line: php bin/magento module:enable MGS_StoreLocator
Run command line: php bin/magento module:enable MGS_Blog
Run command line: php bin/magento setup:upgrade

5.	Go to MGS --> Theme settings
6.	Click on ‘Install Orson theme’
7.	Observe that theme  is installed 
8.	Goto Content -->Themes -->  observe that Orson them found

Please find the attached snapshots for reference.
<img width="960" alt="Theme_opened" src="https://user-images.githubusercontent.com/51681379/126622296-f231e221-0bcb-4cf8-b8d3-7318fc972230.png">
![cart_discount](https://user-images.githubusercontent.com/51681379/126622493-f64c5399-89d9-4c79-9096-2e238d876ba4.jpg)

**Comment by Meberem** [comment]
I don't know which Orson theme you are using, I tried to look on the Magento Marketplace but it's not there. Looking at [MageSolutions version](https://www.magesolution.com/magento2/free-themes/orson-ultimate-magento-2-theme.html) it doesn't have an admin theme as well.

Does the theme you are using have a frontend and admin theme with the same name?

**Comment by engcom-Delta** [comment]
HI @Meberem,
Verified on Admin Theme ,Kindly find the attached orson which  i tried.
[orson_v1.0.0_1_2.zip](https://github.com/magento/magento2/files/6954871/orson_v1.0.0_1_2.zip)

Thanks

**Comment by Meberem** [comment]
I'm not quite sure how the Orson theme provided is supposed to replicate the issue. Please find attached a very paired down example of what I had setup when I experienced this issue: [DemoThemes.zip](https://github.com/magento/magento2/files/6960000/DemoThemes.zip)

**Comment by engcom-Delta** [comment]
Hi @Meberem ,

I tried with provided theme(DemoThems.zip), unfortunately we are unable to upgrade it , getting error like "Fatal error: require(): Failed opening required 'D:\xampp\htdocs\magento242\bin/../app/bootstrap.php' (include_path='C:\xampp\php\PEAR') in D:\xampp\htdocs\magento242\bin\m
agento on line 14".
![MGMCommandError](https://user-images.githubusercontent.com/51681379/131337838-398d8f1a-5150-4510-bef6-1b9f6b791dec.JPG)

**Comment by Meberem** [comment]
What does `MSG_Mpanel` have to do with this? That error sounds like it belongs to that, you haven't gotten to importing the themes yet.

I created 2 themes that are the bare minimum required to demonstrate the problem. Pick any working Magento instance, or a brand new one and import those themes to see the error.

**Comment by engcom-Delta** [comment]
Hi @Meberem,
Thanks for creating the themes. Kindly share them, I will try to replicate  the error.
Regards,

**Comment by Meberem** [comment]
> Hi @Meberem,
> Thanks for creating the themes. Kindly share them, I will try to replicate the error.
> Regards,

Please see the attachment in [my previous comment](https://github.com/magento/magento2/issues/33479#issuecomment-895818968). 

The issue experienced is not to do with the files I provided. *Do not use* MSG_* they are unrelated to this issue

**Comment by Meberem** [comment]
After the first import something similar to this will have been applied to `config.php`
```diff
<?php
return [
	...
    'themes' => [
        'frontend/Magento/blank' => [
            'parent_id' => null,
            'theme_path' => 'Magento/blank',
            'theme_title' => 'Magento Blank',
            'is_featured' => '0',
            'area' => 'frontend',
            'type' => '0',
            'code' => 'Magento/blank',
        ],
        'adminhtml/Magento/backend' => [
            'parent_id' => null,
            'theme_path' => 'Magento/backend',
            'theme_title' => 'Magento 2 backend',
            'is_featured' => '0',
            'area' => 'adminhtml',
            'type' => '0',
            'code' => 'Magento/backend',
        ],
+        'frontend/BreakingTheme/ThemeName' => [
+            'parent_id' => 'Magento/blank',
+            'theme_path' => 'BreakingTheme/ThemeName',
+            'theme_title' => 'Breaking Theme - Frontend',
+            'is_featured' => '0',
+            'area' => 'frontend',
+            'type' => '0',
+            'code' => 'BreakingTheme/ThemeName',
+        ],
+        'adminhtml/BreakingTheme/ThemeName' => [
+            'parent_id' => 'Magento/backend',
+            'theme_path' => 'BreakingTheme/ThemeName',
+            'theme_title' => 'BreakingTheme - Backend',
+            'is_featured' => '0',
+            'area' => 'adminhtml',
+            'type' => '0',
+            'code' => 'BreakingTheme/ThemeName',
+        ]
    ],
    ...
];
```

If these changes are removed/reverse/not present then a subsequent import fails

**Comment by engcom-Hotel** [comment]
Hello @Meberem,

We request you to please try to reproduce the issue in Magento 2.4-develop branch and let us know if you are able to reproduce it in the same.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Meberem,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by Funfelek** [comment]
as far as i can see this problem exists i've just run into it, 
problem is that bin/magento app:co:im is run in adminhtml emulation
when loading collection in vendor/magento/module-theme/Model/Config/Importer.php:getWarningMessages
it runs also vendor/magento/framework/View/Design/Theme/ThemeList.php:_loadFromFilesystem
then addItem is called, and following path is executed:
html/vendor/magento/framework/Data/Collection.php:addItem($item) -> $itemId = $this->_getItemId($item);
html/vendor/magento/framework/View/Design/Theme/ThemeList.php:_getItem($item);
html/vendor/magento/module-theme/Model/Theme.php:getFullPath()
html/vendor/magento/module-theme/Model/Theme.php:getArea() -> this always returns 'adminhtml' 

thats why $itemId (wchich _loadFromFilesystem trying to add to collection) is wrong should be frontend/XX/YY instead of adminhtml/XX/YY
