### ISSUE TITLE
Migrate to new js cookie

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#33477]
Current magento used jquery cookie but this package no longer maintained anymore
So we should consider recheck current function and migrate to newer version or another package. Example 
https://github.com/js-cookie/js-cookie

current magento is using 
https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/jquery.cookie.js

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
cc: @sivaschenko

**Comment by eduard13** [comment]
### Update

Currently Magento uses jquery/jquery.cookie.js in the following files:
- app/code/Magento/Cookie/view/base/web/js/jquery.storageapi.extended.js
- lib/web/jquery/jstree/jquery.jstree.js
- lib/web/mage/cookies.js

The latest v3.0.1 jQuery.cookie.js requires additional changes into Magento codebase, which makes the JS library update quite complicated. 
Also most likely, these changes are BIC.
