### ISSUE TITLE
Paging Alignment issue on my order page in the front end 

### ISSUE THREAD

**Issue by Abhay-Agrawal** [magento/magento2#33482]
### Preconditions (*)

1. Magento Version 2.4.2-p1
2. more than 10 order id must be visible on my order page
3. steps: My account -> Navigate to My Orders page
4. screenshot 
![alignment](https://user-images.githubusercontent.com/55655451/125631302-82e28604-9b53-4df9-a605-d3cd883f142e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
what theme that you used ? magento theme or custom

**Comment by Abhay-Agrawal** [comment]
I am using the default Magento Luma theme. Please check the issue with the 2.4.2-p1  version

**Comment by Abhay-Agrawal** [comment]
Close
