### ISSUE TITLE
Admin Product Dashboard Pagination is broken

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#33493]
### Preconditions (*)
1. Magento Community Edition 2.4.2
2. Regular setup with PHP 7.4 and MariaDB

### Steps to reproduce (*)
1. Create 1000 simple products, 21 configurable products
2. Enter **Catalog > Products** grid
3. Filter by Type: Configurable

### Expected result (*)
1. Results count displays the actual number of filtered items (21)
2. There are only 2 pages in the pagination

### Actual result (*)
1. The total number of products in the Magento database is displayed
2. 50 pages are reported to be available in the pagination

![image](https://user-images.githubusercontent.com/1639941/125803554-95b419ae-ec6e-4233-8354-75b8be7d0642.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
long time no see you

**Comment by mrtuvn** [comment]
Hi @lbajsarowicz  Can you update more details related with issue ? Thanks you for reporting

**Comment by lbajsarowicz** [comment]
Hey! Yes, of course - I managed to find some time early morning to fill missing details @mrtuvn

**Comment by mrtuvn** [comment]
Is this related problem that you sent to me via slack message ?

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz,

We tried reproducing the issue on Magento 2.4.2 & Magento 2.4 . Develop, it is not reproducible .it works as expected.
Kindly find the attached screenshots for reference.

Magento 2.4 Develop:
![Filters_by_config](https://user-images.githubusercontent.com/51681379/126776692-97afe04c-4d07-4b0e-aed8-a56f5ba11da7.jpg)

Magento 2.4.2 :
===========
<img width="960" alt="filters_by_config_242" src="https://user-images.githubusercontent.com/51681379/126776721-a33fa8b7-2a9a-43e1-974d-8c7e3dcf0d76.png">

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by lbajsarowicz** [comment]
The problem does not appear on `2.4-develop`, with Sample Products installed.
However, I am able to reproduce it with large volume of data on local environments.

I'll verify the API responses, because it may be related to the timeouts on updating the total count / pagination (so it keeps the values from before filtering)

**Comment by mrtuvn** [comment]
Maybe problem can reproduce with big data instead

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/commit/9400ece5216a9bc34dc9b5d246134ba2d63c9599
@lbajsarowicz maybe you will want include this changes for your project

**Comment by engcom-Delta** [comment]
@magento give me 2.4.2 instance

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz ,
Tried with huge data on Magento 2.4.2 , it works fine , pagination looks good.
Kindly find the attached snapshots for reference.
![filters_pagination](https://user-images.githubusercontent.com/51681379/131544744-5e2c469b-5dda-4430-a8cb-48684b428c62.JPG)
![filters_pagination2](https://user-images.githubusercontent.com/51681379/131544784-ae5211ed-0cd4-4a2b-bdc1-27cbd1cad392.JPG)


Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by lbajsarowicz** [comment]
After update to the very latest version of Magento, it works as expected.
We can consider this issue resolved.
