### ISSUE TITLE
Simple Configurable Products

### ISSUE THREAD

**Issue by sverdier** [magento/magento2#335]
Is it planned to add this natively?
http://www.magentocommerce.com/magento-connect/simple-configurable-products.html
With Simple Configurable Products, the price for configurable products is taken directly from the associated simple products rather than the configurable product itself.
Otherwise it is necessary to calculate the difference of price and enter it to the configurable product and this is a very complex management for customers using Magento without ERP.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-23739

**Comment by tanya-soroka** [comment]
@shayW I would like to clarify one use-case which you posted on your comment: "the attribute prices (either entered manually under custom options) CANNOT be associated to the product price". 
Do you mean that final product price is not associated with value of the attribute price? Do you request of ability to overwrite the main product price by different price options: custom option price,  tier price, sub-product price, etc. ?
Thank you in advance

**Comment by nevparmar** [comment]
Magento- How to config a Product with different sizes, materials and prices??
i need to find the best method to configure a product which has multiple materials, sizes and prices. I tried making attribute sets with custom material and sizes, but after adding the 3rd size and prices, I loose the pricing structure.

Briefly this is how it should look:

Product Sign 1 - the default material, size and price is Silver Sign, 10x10, and it's 5.00.

(These are simple/associated products)

Product Sign 1

Material       Size        Price
Silver Sign    10x10        5.00
Gold Sign      10x10        10.00
Bronze Sign    10x10        15.00
Silver Sign    12x12        5.75
Gold Sign      12x12        10.75
Bronze Sign    12x12        15.75
Silver Sign    18x18        25.75
Gold Sign      18x18        20.75
Bronze Sign    18x18        25.75

**Comment by crane-cio** [comment]
Nevparmar Just to be certain are you asking how to do this in Magento **2** ?
If you are inquiring regarding 2 I am not 100% sure about this answer but I believe to be true.

You will need a 3rd party magento extension like Organic Internet's Simple Configurable Products (SCP) which overrides the weird default configurable product behavior of Magento.  With SCP or one of the various similar extension each simple product is a unique SKU capable of having its own unique pricing and inventory and you can have near unlimited configurable options.

This thread is requesting that SCP functionality be added by default to the currently under development Magento **2** .  

If you are using Magento 1 in a I suggest you find a supported extension similar to SCP from Organic Internet, becuase as of now the original is no longer maintained by the developer.  I personally am currently looking for a working opensource alternative for SCP.

**Comment by joshdifabio** [comment]
What is the status of this issue for Magento 2? As someone who has worked full-time as a Magento 1 backend developer for almost six years at @ampersandhq, I can say that we have used configurable products on almost all of our clients' websites and we have never had a single client who has wanted to use price adjustments as implemented in Magento 1. I believe it is fundamental that Magento 2 provides the option for configurable product prices to be taken from the associated products.

**Comment by peterjaap** [comment]
Hear hear @joshdifabio. We have exactly the same experience. This definitely needs to be built-in in Magento 2. I mean, even WooCommerce has it by default.

**Comment by crane-cio** [comment]
I absolutely agree, there is no reason this should not be built into the Magento 2, we use it in all of our sites.

**Comment by tanya-soroka** [comment]
Hello all. I would like to update you that team is currently working on changing configurable price according to your recommendation ( using simple price). Will be available soon.

**Comment by peterjaap** [comment]
Great!!

**Comment by Vinai** [comment]
:+1:

**Comment by crane-cio** [comment]
Supper happy to hear this @tanya-soroka This alone will move up our adoption of M2

**Comment by clockworkgeek** [comment]
:relieved:

**Comment by namrodbui** [comment]
Anyone know the status of this?

**Comment by tanya-soroka** [comment]
It is in progress right now. You will see this changes soon ( please check our following releases)

**Comment by fiavanana** [comment]
:+1:

**Comment by robert198222** [comment]
:+1:

**Comment by vpelipenko** [comment]
Internal ticket is closed. @tanya-soroka, can you confirm that it is fixed and available for community?

**Comment by tanya-soroka** [comment]
The recommendation of using simple product price fr the configurable has been implemented. 
We need just to remove price attribute form the configurable product and change the logic of displaying price and calculating discount on the front-end for configurable product.  That part will be implemented in the MAGETWO-41014 and MAGETWO-41069.

**Comment by roman204** [comment]
Yes, where is the like or +1 Button here !!

**Comment by joshdifabio** [comment]
Great new! Thanks, guys!

**Comment by nhp** [comment]
The only disadvantage of this solution is that the prices are now only available if the product is fully configured or will it be like today in Magento1 that the Price could be shown on a per option base, like you select one option of a multi attribute configurable and only that one is price-differing than you could see the differences directly after selecting that attribute.

**Comment by miinervagg** [comment]
@tanya-soroka I've removed the price of the attributes from the configurable product but Magento doesn't pick the single product price of the associated products. Instead, magento only shows the price of the configurable product (that I must put for create a configurable product) The dropdown let me change the attributes of the product but it doesn't change de prices: it shows and calculates at the shopping cart the configurable product price instead of the simple and associated products price.
How can I fix it? 
By the way, I'm using Magento 1.9

**Comment by tanya-soroka** [comment]
Hello @miinervagg, this fix only related to Magento 2 versions, it is not applied to Magento 1. 
You can search for the existing extension in Connect ( http://www.magentocommerce.com/magento-connect), to get the same behavior.

**Comment by tanya-soroka** [comment]
@nhp, by default we use less simple price to show on the category page. To get the final price for your product you will need to select the correct options.

**Comment by tanya-soroka** [comment]
@sverdier  the features has been implemented. Do you agree to close this ticket?

**Comment by robert198222** [comment]
yes

**Comment by davidalger** [comment]
Closing this ticket since this feature has been implemented and is now available in Magento 2.

**Comment by amresh13500** [comment]
hi to all..i am new here so please ignore my mistakes..
i am using this SCP extenstion in my magento site. the problem is whateve price i am setting for configurable product(at time of creating configurable product) that not shown on product page and it show price of last simple product added in configurable type
![home page](https://cloud.githubusercontent.com/assets/16338381/14775273/9a5b03c0-0a72-11e6-8387-7dd31c091f1c.PNG)
![product page](https://cloud.githubusercontent.com/assets/16338381/14775272/9a58ce70-0a72-11e6-9221-2957859d9ec7.PNG)

see this images and you ill get it...please reply

**Comment by mitesh-toptal** [comment]
from where I can download latest version of SCP for magento2. Please share link or give me details.
Thanks,
Mitesh

**Comment by peterjaap** [comment]
@mitesh-toptal judging from the screenshot @amresh13500 uploaded in this thread, he is talking about Magento 1.
