### ISSUE TITLE
File Permission Issue

### ISSUE THREAD

**Issue by Vikasdeveloper** [magento/magento2#3350]
http://awesomescreenshot.com/0de5mb3s88
I am getting 403 forbidden issue every time in the magento backend. I have already set permission of "pub" folder to 755 and file in this folder to 644.
But Still getting this error.

I have also tried to set File system permissions and ownership. But still not working.

Please fix this issue.

Thanks

**Comment by mazhalai** [comment]
but 755 is not recommended: recommended is 770, as per http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html and http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html

**Comment by MomotenkoNatalia** [comment]
@Vikasdeveloper Please let us know if this helps.

**Comment by Vikasdeveloper** [comment]
Yes, I got this links already and fixed the issue. But It was little tricky to set this ownership and files system permissions at first time.

**Comment by mazhalai** [comment]
Closing since issue has been addressed.
