### ISSUE TITLE
vendor/magento/framework/Data/Collection.php

### ISSUE THREAD

**Issue by savandholu** [magento/magento2#33500]
vendor/magento/framework/Data/Collection.php

line : 406

```
 public function addItem(\Magento\Framework\DataObject $item)
    {
        $itemId = $this->_getItemId($item);

        if ($itemId !== null) {
            if (isset($this->_items[$itemId])) {
                throw new \Exception(
                    'Item (' . get_class($item) . ') with the same ID "' . $item->getId() . '" already exists.'
               );
            }
            $this->_items[$itemId] = $item;
        } else {
            $this->_addItem($item);
        }
        return $this;
    }
```
become => below, wait for M2 fix
 public function addItem(\Magento\Framework\DataObject $item)
    {
        $itemId = $this->_getItemId($item);

        if ($itemId !== null) {
            if (isset($this->_items[$itemId])) {
            return $this;
            }
            $this->_items[$itemId] = $item;
        } else {
            $this->_addItem($item);
        }
        return $this;
    }

_Originally posted by @smagic39 in https://github.com/magento/magento2/issues/6126#issuecomment-299430080_

Changes file code but it's not working

**Comment by engcom-Delta** [comment]
Hi @savan13,

Kindly provide the issue description, steps to reproduce, Actual results and expected results. so that we will try to reproduce the issue.

Thanks

**Comment by engcom-Delta** [comment]
There has no update from the reporter and it is ~ 14 days. Hence closing the issue.
Kindly raise new ticket if required or re-open the existing issue.

Thanks
