### ISSUE TITLE
Update npm packages to the latest versions

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33512]
Update npm packages to the latest versions

The following npm packages should be updated:

- grunt
- grunt-contrib-clean
- grunt-contrib-connect
- grunt-contrib-cssmin
- grunt-contrib-imagemin
- grunt-contrib-less
- grunt-eslint
- imagemin-svgo
- morgan
- path
- serve-static
- squirejs
- strip-json-comments
- time-grunt
- underscore

### Conclusion

- glob from ~7.1.1 to ~7.1.7 (latest)
- grunt from ~1.0.1 to ~1.4.1 (latest)
- grunt-contrib-clean from ~1.1.0 to ~2.0.0 (latest)
- grunt-contrib-connect from ~1.0.2 to ~3.0.0 (latest)
- grunt-contrib-less (not latest. Details below)
- grunt-contrib-cssmin from ~2.2.1 to ~4.0.0 (latest)
- grunt-contrib-jasmine (not latest. Details below)
- grunt-contrib-imagemin from ~2.0.1 to ~4.0.0 (latest)
- grunt-contrib-watch from ~1.0.0 to ~1.1.0 (latest)
- grunt-eslint from ~20.1.0 to ~20.2 .0(not latest. Details below)
- grunt-replace from ~1.0.1 to ~2.0.2 (latest)
- load-grunt-config from ~0.19.2 to ~4.0.1 (latest)
- imagemin-svgo from ~5.2.1 to ~7.1.0(not latest. Details below)
- morgan from ~1.9.0 to ~1.10.0 (latest)
- node-minify from ~2.3.1 to ~3.6.0 (latest)
- path - probably abandoned
- serve-static from ~1.13.1 to ~1.14.1 (latest)
- squirejs - probably abandoned
- strip-json-comments from ~2.0.1 to ~3.1.1 (not latest. Details below)
- time-grunt from ~1.4.0 to ~2.0.0 (latest)
--------------------------------------------------
- `grunt-contrib-jasmine` - from the next 2.0.0, the library has switched from PhantomJS to Chrome Headless via puppeteer, and requires reconfiguring the extension.
- `grunt-contrib-less` - version 3.0.0 and higher, are failing on Github builds without an explicitly reason
- `grunt-eslint` - from the next 21.0.0 we're started getting the Warning: must provide pattern
- `imagemin-svgo` - version 8.0.0 and higher, are failing on Github builds without an explicitly reason
- `strip-json-comments` - versions above 3.1.1 throw the following warning: `require() of ES modules is not supported.`

####  ⚠️ Deprecated npm packages

- `grunt-autoprefixer` - removed in magento/magento2/issues/34037
- `time-grunt` - can be easily removed. There is no suggestion what can be used instead.
- `grunt-jscs` - Requires migration to grunt-eslint - https://eslint.org/docs/user-guide/migrating-from-jscs. ESLint and JSCS are really solving the same set of problems, which was the reason of merging them - https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2.

####  :question: Broken or unavailable builds on https://www.npmjs.com/

- grunt-banner
- grunt-contrib-watch
- grunt-text-replace

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by mrtuvn** [comment]
Hi @sivaschenko 
Upgrade all packages may come with some broken in grunt compile flow. Previous i saw less current version of magento not compatible with higher version. Less latest version is 4.x. Grunt have some updated too but i'm not sure current magento less lib allow we get into there
