### ISSUE TITLE
not working extending products page in MEE, MCE ver 2.0.2 & 2.0  (Magento 2 ver 1.0.0-beta is working)

### ISSUE THREAD

**Issue by bojjaiah** [magento/magento2#3351]
Hi Magento Team,

I'm extending products page in Magento 2 ver 2.0 & 2.0.2 (MEE & MCE) and my custom code is showing in `products new/edit` page, but when I'm saving product it's not saving like it's hanging.

Previously I'm implemented same functionality in Magento 2 ver 1.0.0 beta it's perfectly working.

Can you please suggest me on this issue ASAP. Because I'm working on extension.

**Comment by bojjaiah** [comment]
@magento-team Can you please look on this thread.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by bojjaiah** [comment]
@davidalger it's a bug from Magento 2 GA. Why because same functionality working in Magento ver 1.0.0 beta, But it's not working on recently released MEE 2.0.0, MEE 2.0.2 and MCE 2.0.0, MCE 2.0.2.
