### ISSUE TITLE
Update magento/composer composer dependency to version 1.7.0

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33510]
Update magento/composer composer dependency to version 1.7.0

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by hostep** [comment]
It's funny that this was delivered in Magento 2.3.7 almost 3 months ago and then was forgotten in Magento 2.4(.3). Anyways, let's hope for 2.4.3-p1 or maybe even 2.4.4 (which is happening somewhere in 2022 I'm guessing)
