### ISSUE TITLE
Configurable Price Range (feature request)

### ISSUE THREAD

**Issue by samy-m-dev** [magento/magento2#3352]
It should be nice to have an option in Admin to display price range for configurable products instead of only displaying the minimal price.

50$ - 90$ (minimal price) - (maximal price)

That range may be display on the product listing, and on the product page when no options selected yet

I beleive many companies have use cases on which they use the configurable product type, but price may vary a lot depending on the configurable options.

**Comment by antboiko** [comment]
Hi @webtekindo , thanks for your inquiry. We currently have internal ticket MAGETWO-46737 in our backlog which covers informing that price can be higher.

Best,
Anton.

**Comment by samy-m-dev** [comment]
Ok that's great thanks.

**Comment by ntzz** [comment]
@antboiko is there any update for this?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-Price-Range-feature-request/idi-p/46069).

**Comment by ovidiucaramida** [comment]
This extension displays the price range on the category product listing, product page and also handles price update when switching between product options
https://webpanda-solutions.com/configurable-product-price-range.html
