### ISSUE TITLE
When use Special Price the Regular Price for Configurable product not dynamically update

### ISSUE THREAD

**Issue by samy-m-dev** [magento/magento2#3353]
When we use a Special Price on the simple products that are part of a configurable product, on the configurable product page the Special Price is correctly update with Javascript, but the Regular Price is not update by Javascript.

![select conf](https://cloud.githubusercontent.com/assets/16412622/12941624/48885cca-d00f-11e5-9f81-b81e849b13f8.png)

**Comment by veloraven** [comment]
@webtekindo thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with more detailed steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
