### ISSUE TITLE
Magento 2 using a old version of jQuery

### ISSUE THREAD

**Issue by vishalkmodi007** [magento/magento2#33543]
### Preconditions (*)

1.Magento CE ver. 2.3.x
2.I see that 2.3.x is using the old version of jQuery

### Steps to reproduce (*)

1.Install Magento
2.check jQuery version that is packed with it

### Expected result (*)

1. Have a newer version of jQuery

### Actual result (*)

1. Old version of jQuery

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Internal team already acknowledge this . I believe we will upgrade jquery to higher version soon

**Comment by engcom-November** [comment]
Verified this issue on Magento 2.4-develop branch and the current version of Magento is using jQuery 1.12.4 version having [vulnerabilities](https://snyk.io/vuln/npm:jquery@1.12.4)
Steps: Check the jQuery version from console:
![image](https://user-images.githubusercontent.com/60198231/126605301-f429b07f-a724-4a08-beed-b03d2abb9e78.png)
**Expected behavior:** Magento 2.4.x should be using newer jQuery version

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42898` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @vishalkmodi007

Thank you for reporting and collaboration!


It's a quite complex task that affects a lot of other components and requires a little bit more effort than just fix and delivering bug.
But Magento is aware of it and currently, this task is in progress in the scope of Project: Platform Health.

Please see for more details: 
-  [Magento Community Engineering Community Engineering Hangouts. May 19, 2021](https://youtu.be/mwTzDFoogwU)
- [Migration to jQuery 3.5.x](https://www.slideshare.net/StanislavIdolov/migration-to-jquery-35x)
 

So we are closing this issue, update for the jQuery will be done and delivered in the scope of Platform Health project
