### ISSUE TITLE
BUG: 2.4.2 does not run

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#33542]
[Tue Jul 20 22:08:50.376593 2021] [proxy_fcgi:error] [pid 30726:tid 140429973939968] [client a.a.a.a:59960] AH01071: Got error 'PHP message: PHP Warning:  error_reporting() has been disabled for security reasons in /xxxxx/xxxx/xxxx.xxxxxxx.xx/app/bootstrap.php on line 10PHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/xxxxx/xxxx) in /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/Filesystem/DirectoryList.php on line 101PHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/xxxxx/xxxx) in /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/Filesystem/DirectoryList.php on line 101PHP message: PHP Warning:  realpath(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/xxxxx/xxxx) in /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/Filesystem/DirectoryList.php on line 101PHP message: PHP Warning:  set_error_handler() has been disabled for security reasons in /xxxxx/xxxx/xxxx.xxxxxxx.xx/vendor/laminas/laminas-stdlib/src/ErrorHandler.php on line 62PHP message: PHP Fatal error:  Uncaught ReflectionException: Class Magento\\Framework\\App\\ResourceConnection\\Proxy does not exist in /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:24\nStack trace:\n#0 /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(24): ReflectionClass->__construct('Magento\\\\Framewo...')\n#1 /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(54): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Magento\\\\Framewo...')\n#2 /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters('Magento\\\\Framewo...')\n#3 /xxxxx/xxxx/xxxx.xxxxxxx.xx/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->creat...'

**Comment by mrtuvn** [comment]
Can you provide some details on how do you setup ? nginx, apache, Any preconditions

**Comment by krishprakash** [comment]
Hi @f1-outsourcing. Feel free to reopen once you provide all necessary details to reproduce this issue
Thanks
