### ISSUE TITLE
You can not end support for 2.3 when you do not offer a solution for disabling elastic search in 2.4

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#33553]
I just need a shop to sell 10 products. I do not want any other 'shit' like elastics to install, just something light, then better no search at all. Who is responsible for your design decisions? Currently you are making magento crap. I was so pleased with 1.9, and I am hugely disappointed with 2.3/2.4. I can not get that you are forcing Elastic search and do not give the option for no search, it is like some teenager is planning your strategy.

**Comment by mrtuvn** [comment]
Agreed with you at some points but maybe magento not fit with your business models. Just my opinion
If you want to share any thoughts feel free add some notes/proposals here
https://github.com/magento/architecture/issues

**Comment by f1-outsourcing** [comment]
@mrtuvn 

Cannot post issues here, did not try the other link
https://github.com/magento/architecture/issues

First thing I would like to address is if elasticsearch is even a viable option for the future. Are you even aware of this license change?
This is in there new license 'Of greater concern, the boundaries of what constitutes a "Prohibited SaaS Offering" '[1]

Ehmmm I think that means that you can not offer this service in your cloud solution of magento.

'Yes. Neither the Elastic License nor SSPL have been approved by the OSI, so to prevent confusion, we no longer refer to Elasticsearch or Kibana as open source. '[2]


[1]
https://www.reworked.co/knowledge-findability/not-so-open-any-more-elasticsearch-relicensing-and-implications-for-open-source-search/

[2]
https://www.elastic.co/pricing/faq/licensing#does-this-mean-that-elasticsearch-and-kibana-are-no-longer-open-source

**Comment by engcom-Lima** [comment]
@f1-outsourcing,

We have looked at your query and suggestion. This looks like an architecture related query which you can write on the below link:
https://github.com/magento/community-features

This link is for development related issues only so unless you have any dev related issue, we'll have to close this thread. Please update.

**Comment by engcom-Lima** [comment]
There has been no update from the reporter so closing this issue.
