### ISSUE TITLE
Investigate the possible unused CSS files that can be removed

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#33554]
### Overview

We need to identify the CSS files that aren't used anywhere, and check if it's safe to be removed.

### Investigation Outcome

The list of CSS files is provided and removed from the codebase.

**Comment by eduard13** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
Seem lot of css stay in lib/web/prototype/windows/themes/

**Comment by eduard13** [comment]
@mrtuvn since we are still planning to keep Prototype JS, is much better to keep all the files related to it, including css files.
