### ISSUE TITLE
XML syntax to change block's template

### ISSUE THREAD

**Issue by cescopag** [magento/magento2#3356]
### Summary

Documentation claims that it is possible to change a block's template by the following layout update:

```
<referenceBlock name="navigation.sections">
  <arguments>
    <argument name="template" xsi:type="string">Magento_Theme::html/nav_sections.phtml</argument>
  </arguments>
</referenceBlock>
```

But It doesn't work. 

Using **`action`** node, instead of **`arguments`** node, works fine:

```
<referenceBlock name="navigation.sections">
  <action method="setTemplate">
    <argument name="template" xsi:type="string">Magento_Theme::html/nav_sections.phtml</argument>
  </action>
</referenceBlock>
```

Source:
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-manage.html#set_template

### Preconditions (*)

1. Magento 2.3-develop
2. PHP 7.2

### Steps to reproduce (*)
Try to change a block's template by the following layout update
e.g.:
![3356](https://user-images.githubusercontent.com/51680850/70244131-813f1500-177c-11ea-9871-bdc8c5854261.png)

### Expected result (*)
Block's template is changed without any errors

### Actual result (*)
Got exception 
![3356ex](https://user-images.githubusercontent.com/51680850/70244264-bb101b80-177c-11ea-93d6-9f64804dadf3.png)

**Comment by shiftedreality** [comment]
Hi @cescopag 

You provided correct way with **action method**
Looks like mistake in public docs

**Comment by almarchenko** [comment]
Hi @cescopag!
Thank you for reporting this. Looks like there's a bug in magento code, that is why the code sample provided in docs doesn't work. But you found the correct temporary solution. 
It must be temporarily as <action> is deprecated. I'll add a note in docs, and updated them when the bug is fixed.

**Comment by LiamFielding** [comment]
Is this now fixed?

**Comment by dnadle** [comment]
In 2.1.0 I still have to use 'action' and the online documentation is still wrong.

**Comment by digitalpianism** [comment]
As another alternative I'm pretty sure you can do:

`<referenceBlock name="navigation.sections" template="Magento_Theme::html/nav_sections.phtml" />`

**Comment by LiamFielding** [comment]
@digitalpianism No, sorry - I believe that's what we all tried first. At least I did, that's how I ended up here.

**Comment by digitalpianism** [comment]
@LiamFielding my bad. I guess we gotta wait ^^

**Comment by sylvainraye** [comment]
The reason why it doesn't work is because the method \Magento\Framework\View\Layout\Generator\Block::generateBlock:

When we want to overwrite an existing block, this one was at first initialized via a layout XML with an attribute `template`. 

Into the `generateBlock`method, `arguments` are passed to the block, then `setTemplate` is called and then in the calling method `process` the action is called. 

So the priority is the following:
- actions
- setTemplate via attribute `template`
- arguments

When a block was initialized with its attribute `template`, `arguments` will have no effect. That's why you need to use `actions`

```
protected function generateBlock(
        Layout\ScheduledStructure $scheduledStructure,
        Layout\Data\Structure $structure,
        $elementName
    ) {
        list(, $data) = $scheduledStructure->getElement($elementName);
        $attributes = $data['attributes'];

        if (!empty($attributes['group'])) {
            $structure->addToParentGroup($elementName, $attributes['group']);
        }
        if (!empty($attributes['display'])) {
            $structure->setAttribute($elementName, 'display', $attributes['display']);
        }

        // create block
        $className = $attributes['class'];
        $block = $this->createBlock($className, $elementName, [
            'data' => $this->evaluateArguments($data['arguments'])
        ]);
        if (!empty($attributes['template'])) {
            $block->setTemplate($attributes['template']);
        }
        if (!empty($attributes['ttl'])) {
            $ttl = (int)$attributes['ttl'];
            $block->setTtl($ttl);
        }
        return $block;
    }
```

**Comment by nsergo** [comment]
Issue in progress @nsergo & @sambolek

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66248

**Comment by magento-engcom-team** [comment]
Closing the issue as the feature request. Please, see more details here https://github.com/magento/magento2/pull/8913#discussion_r106549969

**Comment by tmotyl** [comment]
@magento-engcom-team the PR you've referencing was also closed, as it required some changes in the pull request code.
So now both this issue and PR are closed but the issue still exists and documentation is still wrong.
In my opinion this issue should stay open until it's fixed. 

If you consider this a feature request, please at last fix the documentation.

**Comment by DanielRuf** [comment]
This issue still exists. We should reopen it.

**Comment by ghost** [comment]
@cescopag, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by adriancaragea** [comment]
This is still not solved.

**Comment by artbychenko** [comment]
Solution:
<pre>
if ($block->hasData('template')) {
    // set template agrument
    $block->setTemplate($block->getData('template'));
} else {
    if (!empty($attributes['template'])) {
        $block->setTemplate($attributes['template']);
    }
}
if (!empty($attributes['ttl'])) {
    $ttl = (int)$attributes['ttl'];
    $block->setTtl($ttl);
}
return $block;
</pre>

**Comment by bartoszkubicki** [comment]
On Magento 2.3.2 seems to not be an issue any more

**Comment by bartoszkubicki** [comment]
This does not seem to be issue any more. I have replaced template using arguments in Magento 2.3.2.

**Comment by dvyaschts** [comment]
This issue still exist.  

<referenceBlock name="product.info.addtocart">
            <arguments>
                <argument name="template" xsi:type="string">Yoma_Dipen::addtocart.phtml</argument>
            </arguments>
        </referenceBlock>


I tried this code in my customer module's catalog_product_view.xml

it's not working.

**Comment by adarshkhatri** [comment]
Doesn't work in 2.3.3-p1

**Comment by Eddcapone** [comment]
Does not work in 2.3.5-p2

**Comment by ihor-sviziev** [comment]
FYI This issue was resolved by adjusting the docs and highlighting the applied priorities in https://github.com/magento/devdocs/pull/7977
