### ISSUE TITLE
Introduce PHP 8 Compatibility to adobe/stock-api-libphp

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33562]
## What should be done

Create a new PR to https://github.com/adobe/stock-api-libphp introducing PHP 8 compatibility. The changes can be based on https://github.com/adobe/stock-api-libphp/pull/21
The Library should be tested on PHP 8, the formatting changes should not be included in the PR (removed spaces)

adobe/stock-api-libphp is a dependency of Adobe Stock Integration project.

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by anzin** [comment]
@magento I am working on this

**Comment by andrewbess** [comment]
A new version of the `adobe/stock-api-libphp` has been released https://github.com/adobe/stock-api-libphp/releases/tag/1.1.5
