### ISSUE TITLE
add information on elasticsearch configuration, eg what user/node roles are required.

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#33578]
None of these pages[1] write anything about creating the magento user in elasticsearch. I mean users created at this endpoint and what roles it should have[2]. Also there is nothing written about what node roles[3] are expected to be available.

[1]
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html
https://devdocs.magento.com/guides/v2.4/config-guide/elasticsearch/es-overview.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html#es-install-es7

[2]
https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-roles.html

[3]
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

**Comment by hostep** [comment]
Hi @f1-outsourcing: since this is a request to improve the documentation, it's probably better to open an issue on [the devdocs repository](https://github.com/magento/devdocs/issues) for this, right?

**Comment by f1-outsourcing** [comment]
Ohh I guess, can you move it?

**Comment by hostep** [comment]
I can't, I'm just a normal contributor not part of the Magento team, but maybe @sdzhepa can move it?
But if you don't see activity here in the first couple of days, it's probably faster to close it and open a new one at the devdocs repo.

**Comment by mrtuvn** [comment]
cc: @dobooth

**Comment by sdzhepa** [comment]
Hello @hostep, @f1-outsourcing  
cc: @dobooth @mrtuvn 

Unfortunately, I do not have permission to move this ticket to the DevDoc repo.
But I would propose to
- create a new issue in the https://github.com/magento/devdocs/issues
- close this one
