### ISSUE TITLE
Authenticate popup block should not render or available if customer logged in

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#33576]
This part become unneccessary when customer logged in 

id authenticationPopup
This block defined in xml at 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/layout/default.xml#L26

One specific case if customer not logged in and guess checkout disabled
Instead render by default it's should render on demand

If guest checkout enabled. This block is valid to not have to be render

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @mrtuvn 
To help us process this issue please share with us additional details regarding the issue under the requested heads as below.
Summary of the issue
Information on your environment, Prerequisites
Steps to reproduce
Expected and actual results

Thank you.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
