### ISSUE TITLE
Cover web setup page with MFTF tests

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#33580]
### Summary
According to magento/magento2#33338 the library `laminas/laminas-mvc` has been eliminated from web setup.
The covering this page by the MFTF test can get some effort by some reasons:
- creating a new module does not make any sense, however, MFTF tests work with Magento modules;
- some elements of HTML markup (for example: <section>) found on the page aren't supported by MFTF.

The web setup landing page should be covered with MFTF tests only after merging related PR (pull request).

### Related Issues
magento/magento2#33338: Eliminate laminas-mvc and all possible dependencies used for retired Setup Wizard

### Related Pull Requests
https://github.com/magento/magento2/pull/33397

### Expected result (*)

1. The web setup landing page is covered with MFTF tests

### Actual result (*)

1. The web setup landing page is not covered with MFTF tests

**Comment by magento-engcom-team** [comment]
@andrewbess Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!
