### ISSUE TITLE
[MFTF] Eliminate AspectMock where it was imported but never used

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2#33581]
### Goal
`codeception/aspect-mock` library is still not compatible with PHP 8.0 at the time of the creation of this ticket.

To speed up Magento compatibility with new PHP versions we'd like to eliminate `codeception/aspect-mock` dependency from MFTF. This will make MFTF compatible with PHP 8.0 that is required for declaring the Magento core PHP 8 compatible as well.

In order to do this existing unit tests using AspectMock should be refactored to use PHPUnit instead.

### Task
Eliminate AspectMock usage for the next classes:

1. \tests\unit\Magento\FunctionalTestFramework\DataGenerator\Handlers\DataObjectHandlerTest
2. \tests\unit\Magento\FunctionalTestFramework\DataGenerator\Handlers\OperationDefinitionObjectHandlerTest
3. \tests\unit\Magento\FunctionalTestFramework\Page\Handlers\PageObjectHandlerTest
4. \tests\unit\Magento\FunctionalTestFramework\Page\Handlers\SectionObjectHandlerTest
5. \tests\unit\Magento\FunctionalTestFramework\Test\Handlers\ActionGroupObjectHandlerTest
6. \tests\unit\Magento\FunctionalTestFramework\Test\Util\ActionGroupAnnotationExtractorTest
7. \tests\unit\Magento\FunctionalTestFramework\Test\Util\AnnotationExtractorTest

Do code refactoring for all of these files.

### Example

Mocking an object using AspectMock (current):

```
        $mock = AspectMock::double(
            MockedClass::class,
            [
                'mockedMethodName' => 'methodReturnValue',
            ]
        )->make();
```

Mocking an object using PHPUnit (refactored code):

```
        $mock = $this->createMock(File::class);
        $file->expects($this->any())
            ->method('mockedMethodName')
            ->willReturn('methodReturnValue');
```

Example pull request: https://github.com/magento/magento2-functional-testing-framework/pull/833

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Story

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Story

**Comment by bohdan-harniuk** [comment]
Hello, @KevinBKozan! 

Why did you close this issue?

Thanks, Bohdan

**Comment by KevinBKozan** [comment]
@bohdan-harniuk It was auto-closed apparently since I merged an internal PR containing community commits https://github.com/magento-commerce/magento2-functional-testing-framework/pull/88

**Comment by KevinBKozan** [comment]
@anzin's PR was subsequently merged in the public Repo https://github.com/magento/magento2-functional-testing-framework/pull/862

**Comment by bohdan-harniuk** [comment]
@KevinBKozan, thank you!
