### ISSUE TITLE
Update phpunit/phpunit composer dependency to the latest version

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#33596]
Update `phpunit/phpunit` composer dependency to the latest version (9.5.*).

Pay attentions, Magento has a lot of dependencies from old classes and methods removed in phpunit version 9.5.
 We need to find and eliminate these problems.
 Also, refactoring of the codebase Magento should be made in all related repositories (CE, EE, B2B).

To check all problems you can create a temporary PR with updating `phpunit/phpunit` composer dependency to version 9.5.7 and use allure report feature.
### Expected result (*)

1. The `phpunit/phpunit` composer dependency should be updated to the latest version (9.5.*);
1. PRs for refactoring codebase Magento should be created for all related repositories (CE, EE, B2B);
1. All builds for created PRs shouldn't have problems.

### Related issue (*)
1. magento/magento2#33707 - STAGE 1
1. magento/magento2#33708 - STAGE 2
1. magento/magento2#33709 - STAGE 3

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Story

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Story

**Comment by irenelagno** [comment]
@magento export issue to Jira project AC as Story

**Comment by slavvka** [comment]
@magento export issue to Jira project AC as Story

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Story
