### ISSUE TITLE
invoice email not working magento 2.4.2-p1

### ISSUE THREAD

**Issue by zeekinfo** [magento/magento2#33594]
Hello,

I was upgrade  magento 2.4.2-p1 after that invoice email not working magento 2.4.2-p1 but order confirm email is going 

How to fix this

**Comment by engcom-Delta** [comment]
Hi @zeekinfo, 
Kindly provide issue description, steps to reproduce , actual results and expected results.

Thanks

**Comment by engcom-Delta** [comment]
There has no update for 14 days from 14 days. Hence closing the issue.
Kindly raise new issue if required or re-open the existing issue.
