### ISSUE TITLE
JS error blocks account creation when disabling 'Allow remote shopping assistance' in adminpanel

### ISSUE THREAD

**Issue by bramvanderholst** [magento/magento2#33597]
### Preconditions (*)

1. Magento v2.4.2

### Steps to reproduce (*)

1. Disable 'Allow remote shopping assistance': Stores → Configuration → Customers → Login as Customer → Emable extension: no
2. Attempt to create an account on /customer/account/create/ page

### Expected result (*)

1. Successful account creation without errors

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/7457340/127112897-f233f9b3-7d0a-488e-a20e-ed13e919e5c8.png)

2. Opt-in.js fails due to it not being able to find the shopping assistance field, causing the submit to fail entirely and blocking users from creating an account.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bramvanderholst** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/commit/69c26af51b38754144eedf1ad73b44e479f4f29a
Seem internal team already fixed in 2.4-develop branch

**Comment by mrtuvn** [comment]
https://github.com/magento/quality-patches/tree/master/patches/os
