### ISSUE TITLE
Magento 2.4.3 composer install failed

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#33598]
### Preconditions (*)

1. Composer version 2.0.11 2021-02-24 14:57:23
2. PHP 7.4.13 (cli)

### Steps to reproduce (*)

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.3 2.4.3      
Creating a "magento/project-community-edition:2.4.3" project at "./2.4.3"
Installing magento/project-community-edition (2.4.3)
  - Installing magento/project-community-edition (2.4.3): Extracting archive
Created project in /Users/mbabol/2.4.3
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/composer-dependency-version-audit-plugin, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

### Expected result (*)

1. Install should pass

### Actual result (*)

1. `Root composer.json requires magento/composer-dependency-version-audit-plugin, it could not be found in any version, there may be a typo in the package name.`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Confirmed, but I think it's a bit too early. Usually they fully release a new Magento version at evening in the European timezones, so maybe we should re-test this in about 8 hours or so?

**Comment by maciej-orba** [comment]
yes i will :)

**Comment by mrtuvn** [comment]
![243](https://user-images.githubusercontent.com/1908873/127139880-20012ad6-af62-486a-bcff-903ff3f870b7.png)
maybe you come too soon. Maybe same response results as i got

**Comment by maciej-orba** [comment]
prestissimo plugin is not still required  parallel downloads) when you use composer 2 and also it requires composer 1

**Comment by hostep** [comment]
@maciej-orba: it works correctly at this moment.

I briefly talked to @fascinosum on Slack about it just now, and they still had to setup the correct permissions for this one package. But now everything is ok.

@mrtuvn: you can install Magento 2.4.3 today if you have access to the pre-release. It will be out for everyone on the 10th of August. See https://devdocs.magento.com/release/

Ticket can be closed now I think.

**Comment by maciej-orba** [comment]
yep, composer deploy passed! thx!
