### ISSUE TITLE
Magento 2.4.3, 2.4.2-p2, 2.3.7-p1 DI Compile error

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#33607]
### Preconditions (*)

1. Composer 2
2. PHP 7.4
3. Magento 2.4.3, 2.4.2-p2, 2.3.7-p1

### Steps to reproduce (*)

1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.3 2.4.3`
2. `cd 2.4.3`
3.  `bin/magento module:enable --all`
4.  `bin/magento setup:di:compile`

### Expected result (*)

1. no errors during compilation

### Actual result (*)

<img width="838" alt="Screenshot 2021-07-27 at 21 13 10" src="https://user-images.githubusercontent.com/44395593/127214007-f434b2ea-2eb1-4a00-bd42-66d2355e28f0.png">

<img width="832" alt="Screenshot 2021-07-27 at 21 46 41" src="https://user-images.githubusercontent.com/44395593/127218145-0b44c7f7-d11f-4754-aed5-4953d09e8d36.png">

<img width="747" alt="Screenshot 2021-07-27 at 21 46 29" src="https://user-images.githubusercontent.com/44395593/127218193-5f104921-a604-4a7c-91c6-e914081f814b.png">

```
	Magento\Framework\Setup\Option\AbstractConfigOption
		Incompatible argument type: Required type: int. Actual type: string; File: 
/Users/mbabol/projects/2.4.3/vendor/magento/framework/Setup/Option/AbstractConfigOption.php

Total Errors Count: 1

In Log.php line 92:
                            
  Error during compilation         
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maciej-orba** [comment]
@hostep you may be interested :)

**Comment by ihor-sviziev** [comment]
Hi @maciej-orba,
Thank you for your report. This issue duplicates https://github.com/magento/magento2/issues/33595, so I’m closing it as a duplicate.

**Comment by maciej-orba** [comment]
You right :) hop will be solved immediately
