### ISSUE TITLE
Unique constraint violation after saving CMS pages with node hierarchy

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#33600]
FOLLOW UP issue from https://github.com/magento/magento2/issues/33254

@engcom-November Unfortunately you closed the old ticket and I cannot comment it any longer. This is exact reproduction on a Vanilla instance. Problem still appears.

### Preconditions (*)
1. Magento 2.4.2-p1 with B2B (1.3.1-p1) modules installed (Commerce + B2B)
2. CMS hierarchy feature activated (Store -> Configuration -> )

### Steps to reproduce (*)
1. Content => Hierarchy => Created 2 levels of nodes like this:
<img width="164" alt="Bildschirmfoto 2021-07-27 um 11 08 59" src="https://user-images.githubusercontent.com/3983052/127128140-e4edd48d-9dc3-4491-94f4-95d5035eb4bb.png">
2. Go to an existing CMS page: Content => Pages => Edit one existing page

3. Go to hierarchy tab and add the page to node level 2
<img width="677" alt="Bildschirmfoto 2021-07-27 um 11 10 22" src="https://user-images.githubusercontent.com/3983052/127128314-7c0eaa56-2e5c-412a-b2b4-d2a027659985.png">
4. Save => OK

5. Save again => Unique constraint violation found
<img width="556" alt="Bildschirmfoto 2021-07-27 um 11 10 14" src="https://user-images.githubusercontent.com/3983052/127128327-7d5c381e-13b1-4f87-8dc7-3ff6c99e33a2.png">

### Expected result (*)
1. No error message
2. CMS page saving is successful

### Actual result (*)
1. Error message Unique constraint violation found appears

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sydekumf** [comment]
@engcom-November

**Comment by BrentRobert** [comment]
Hi @sydekumf this is indeed an issue on EE, and has already been fixed in develop, but not has not been released yet.

I created a patch for you, that you can apply to your project.

```
--- a/vendor/magento/module-versions-cms/Observer/Backend/CmsPageSaveAfterObserver.php	(date 1628166201535)
+++ b/vendor/magento/module-versions-cms/Observer/Backend/CmsPageSaveAfterObserver.php	(date 1628166201535)
@@ -131,7 +131,7 @@
                 continue;
             }
 
-            $requestUrl = $parentNode->getIdentifier() . '/' . $page->getIdentifier();
+            $requestUrl = $parentNode->getRequestUrl() . '/' . $page->getIdentifier();
             if ($this->isNodeExist($requestUrl, $nodeScopeId, (int)$parentNode->getId(), (int)$page->getId())) {
                 throw new LocalizedException(
                     __(
```

**Comment by BrentRobert** [comment]
For histories sake:

It's only reproducible when all the nodes in the tree are CMS pages itself.

**Comment by engcom-Hotel** [comment]
Dear @sydekumf,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
