### ISSUE TITLE
Some unit tests jasmine seem broken with recently updated

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#33610]
### Preconditions (*)

1. 2.4-develop branch
2. Developer mode

### Steps to reproduce (*)

1. setup grunt/jasmine for tests
https://devdocs.magento.com/guides/v2.4/test/js/jasmine.html
2. full static deploy
3. run grunt spec for run all js tests
grunt spec:luma

### Expected result (*)

No errors / warning

### Actual result (*)

Got some errors, warning type
![Screenshot from 2021-07-28 14-13-02](https://user-images.githubusercontent.com/1908873/127280216-097c70a0-eb94-4aba-b332-d9c90be70133.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Closed since my last check not update to lastest code

**Comment by mrtuvn** [comment]
No failures at the ends but while running we can see some type error raised! Better we should investigate that

**Comment by engcom-Delta** [comment]
Hi @mrtuvn,
May I know please which operating system was this error displayed ?. I have been working on windows system.

Thanks

**Comment by mrtuvn** [comment]
I dont think this depend on system. Current i used linux

**Comment by engcom-Hotel** [comment]
Hello @mrtuvn,

We have tried to reproduce the issue in Magento 2.4-develop branch but this is not reproducible for us. Please have a look into below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/145377282-e8cab873-cc92-4730-a212-7e719c87f5cd.png)

we request you to please try to reproduce it again in the latest branch and let us know if this is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mrtuvn,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
