### ISSUE TITLE
Change Weight not available when updating product via Catalog / Filter /Update Attributes

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#3361]
The Checkbox to allow a Weight change in selected products is inside the edit box, so It seems it can't be checked to allow weight changes on selected products.  Both Chrome and FireFox

![weight](https://cloud.githubusercontent.com/assets/16857667/12949844/22e5cc1e-cfd8-11e5-89c6-45a3ab1ea332.JPG)

I tried clearing all caches, to no avail. 

It turns out that you can get past the inability to click on the check-box by clicking on the box above twice (just highlight it blue) and then tab to the hidden check-box and hit the space bar to check it and add a weight to update the weight on all selected, but it does not change the product attribute "Have Weight"  to checked when you add weight to the product.  It requires that you still go through the records individually and check the "Have Weight" box to change them from virtual to simple.

Magento 2.0.2
Debian 8
PHP Version 5.6.17-0+deb8u1

**Comment by vil11** [comment]
@joebusby thanks for reporting the issue with env details & a screenshot. Internal ticket **MAGETWO-46950** describes yours + several related UI issues on the same form.

Dima Vilchynskyi, M2 QA engineer.

**Comment by MomotenkoNatalia** [comment]
@joebusby Internal ticket MAGETWO-46950 is closed and delivered to mainline. Please let us know if you still have an issue.

**Comment by tuyennn** [comment]
@MomotenkoNatalia  @magento-engcom-team which ref commit and pull request related to this internal ticket MAGETWO-46950 while it was marked as DONE on 2.3-develop?

**Comment by edwinchandra** [comment]
We are also facing same issue with Magento 2.3.3. We still not able to the update weight attribute as it shows in the disabled state. Can you please let us know the specific commit for this issue.
