### ISSUE TITLE
Template hints are shown to all customers when  FPC is enabled

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#33616]
### Preconditions (*)
1. Magento 2.4.1

### Steps to reproduce (*)
1. Make sure Full page cache is enabled
2. set _Developer Client Restrictions_ to your custom IP address in Stores -> Configuration -> Advanced -> Developer -> Developer Client Restrictions
3. set _Enable Template Path Hints for Storefront_ to _Yes_ in Stores -> Configuration -> Advanced -> Developer -> Debug
4. Save config and clear/flush cache.
5. Go to a FPC cacheable page( some category page) using the same IP as set in step 2
6. Open the same URL as in step 5 using another device( mobile with LTE - wireless disabled - so that the IP is different )

### Expected result (*)
1. The content rendered in step 5 of _Steps to reproduce_ should contain template hints, but the content rendered in step 6 should not.

### Actual result (*)
1. The content with template hints is FPC cached and served to both devices.

**Comment by theodorhanu** [comment]
@magento give me 2.4.1 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4.2 develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @theodorhanu,

We tried to reproduce the issue on Magento 2.4.2  and found that it is not reproducible ,it works as expected.
Kindly find the attached snapshots for reference. Please review the provided steps.

FPC Enabled: 
![template_hints](https://user-images.githubusercontent.com/51681379/127999457-f7df7721-2bc6-4ce4-8116-fcc63a49258a.jpg)

The content with template hints is not FPC cached :
![template_hints_noCached](https://user-images.githubusercontent.com/51681379/127999583-c47966f4-96fe-4ac7-8d62-61f6cc537f90.jpg)
