### ISSUE TITLE
Zoho Integration Magento

### ISSUE THREAD

**Issue by juancruzunq** [magento/magento2#33628]
Hello! In the section "Field Mapping" in Zoho CRM Integration i cant see anithing : only screen in white 

![image](https://user-images.githubusercontent.com/54421721/127539432-4b2e1745-662d-4abb-b38b-f7027cd091a0.png)

this happens about 3 days ago and does not load any information

Thankl you !

**Comment by engcom-Delta** [comment]
Hi @juancruzunq,

Kindly provide the issue description ,steps to reproduce, actual results and expected results. Hence we can reproduce it.
Added the label 'Needs update'

Thanks

**Comment by juancruzunq** [comment]
Hello! The current results are like a blank screen with no information. What should happen is an interface where I can choose the Zoho CRM module and be able to do the correct mapping of fields. In the photo that I attach you can see the module "Invoice" and following the fields to match
![1](https://user-images.githubusercontent.com/54421721/127689516-de6c2594-2556-4b7e-b114-3065234b4a55.PNG)

Thankls

**Comment by juancruzunq** [comment]
![image](https://user-images.githubusercontent.com/54421721/127741107-7314413a-f6e7-48e9-82b3-69bfc4e83545.png)
Actual results

**Comment by hostep** [comment]
@juancruzunq: as far as I see this, you don't claim a bug in core Magento but a problem in that [Zoho CRM Integration module](https://marketplace.magento.com/magenest-module-zohocrm-integration.html). So this is not the correct place to report this.
I'd recommend you to report this bug to the people that maintain that Zoho module.

If it does turn out to be a bug in core Magento, we will need a lot more (technical) information.

Thanks!

**Comment by juancruzunq** [comment]
Thanks for the feedback!
