### ISSUE TITLE
GraphQL - price_range for configurable products is affected by disabled variants

### ISSUE THREAD

**Issue by aligent-lturner** [magento/magento2#33629]
### Preconditions (*)

1. Magento 2.4.x (reproduced on latest dev at time of writing)

### Steps to reproduce (*)

1. Create a configurable product with a sku "test-config-1" with a single configurable attribute (e.g. size) and at least 2 options (e.g. S, M, L)
2. Set the price of one variant to be $40, and the others to be $50
3. Disable the variant with the lower price
4. Execute the following query:
```
query {
  products(
    filter: {
      sku: {
        eq: "test-config-1"
      }
    }
  ) {
    items {
      sku
      price_range {
        minimum_price {
          discount {
            amount_off
            percent_off
          }
          final_price {
            value
            currency
          }
          regular_price {
            value
            currency
          }
        }
      }
      ...on ConfigurableProduct {
        configurable_options {
          values {
            label
          }
        }
        variants {
          attributes {
            label
          }
          product {
            sku
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. `price_range` values are unaffected by disabled variants:
```
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "test-config-1",
          "price_range": {
            "minimum_price": {
              "discount": {
                "amount_off": 0,
                "percent_off": 0
              },
              "final_price": {
                "value": 50,
                "currency": "USD"
              },
              "regular_price": {
                "value": 50,
                "currency": "USD"
              }
            }
          },
          "configurable_options": [
            {
              "values": [
                {
                  "label": "S"
                },
                {
                  "label": "M"
                },
                {
                  "label": "L"
                }
              ]
            }
          ],
          "variants": [
            {
              "attributes": [
                {
                  "label": "L"
                }
              ],
              "product": {
                "sku": "test-config-1-L"
              }
            },
            {
              "attributes": [
                {
                  "label": "M"
                }
              ],
              "product": {
                "sku": "test-config-1-M"
              }
            }
          ]
        }
      ]
    }
  }
}
```

### Actual result (*)

1. Price of disabled sku affects `price_range` values of configurable:
```
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "test-config-1",
          "price_range": {
            "minimum_price": {
              "discount": {
                "amount_off": 10,
                "percent_off": 20
              },
              "final_price": {
                "value": 40,
                "currency": "USD"
              },
              "regular_price": {
                "value": 50,
                "currency": "USD"
              }
            }
          },
          "configurable_options": [
            {
              "values": [
                {
                  "label": "S"
                },
                {
                  "label": "M"
                },
                {
                  "label": "L"
                }
              ]
            }
          ],
          "variants": [
            {
              "attributes": [
                {
                  "label": "L"
                }
              ],
              "product": {
                "sku": "test-config-1-L"
              }
            },
            {
              "attributes": [
                {
                  "label": "M"
                }
              ],
              "product": {
                "sku": "test-config-1-M"
              }
            }
          ]
        }
      ]
    }
  }
}
```
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

I consider this to be critical data, as incorrect pricing is provided to the customer. A work-around would be to change the price of the disabled product, but this is not a good solution.

Note - the `variants` field being returned does not show the disabled product, so I believe the solution would involve applying the same logic used by its collection to the collection used for calculating pricing.

**Comment by aligent-lturner** [comment]
@magento give me 2.4-develop instance

**Comment by aligent-lturner** [comment]
Confirmed on 2.4-develop:

Created configurable:
![image](https://user-images.githubusercontent.com/40189797/127596556-69e38ce3-e595-4098-bdf0-60405070dd6c.png)

Run GraphQL query and see incorrect pricing:
![image](https://user-images.githubusercontent.com/40189797/127596708-77f789ba-4173-4b1b-9a27-f601d2549a61.png)

**Comment by aligent-lturner** [comment]
Note - additional bug found.

If configuration is changes to show out of stock products, then disabled products also appear under `variants` field.
I believe this is due to disabled products essentially being "out of stock", and hence being filtered out by `Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CollectionProcessor\StockProcessor`
```
public function process(
    Collection $collection,
    SearchCriteriaInterface $searchCriteria,
    array $attributeNames,
    ContextInterface $context = null
): Collection {
    if (!$this->stockConfig->isShowOutOfStock()) {
        $this->stockStatusResource->addIsInStockFilterToCollection($collection);
    }

    return $collection;
}
```

**Comment by aligent-lturner** [comment]
I believe that potentially, a fix for the `variants` issue would be changing https://github.com/magento/magento2/blob/39e13001e682725329c8515dc587d0d115684e55/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Product/CollectionProcessor/VisibilityStatusProcessor.php#L38
to
```
$collection->addAttributeToFilter('status', Status::STATUS_ENABLED);
```

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43075` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pawel-siejba** [comment]
One of the possible reasons for this bug is the lack of https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogInventory/etc/frontend/di.xml plugins in `graphql` area. In `frontend` area `add_stock_information` plugin is the one that makes sure stock is taken into consideration on each product collection load. In `graphql` area there is no such plugin, but I'm wondering why `frontend` and `graphql` areas are split as they are both made to serve business logic for the customers. At least I would expect the `graphql` area to inherit base logic from `frontend` area.

**Comment by cpartica** [comment]
that is an interesting idea for graphql to inherit frontend - but the code in GraphQL differs a lot from Luma and we won't be able to split the two. Even for frontend API there's a different area, and it's a by product of how area works.
Inheritance would also make it hard to split the two systems and be coupled forever.
Better fill in the gaps for the missing frontend logic in graphql and decouple - in the far future Luma might not be a thing but GraphQL might

**Comment by engcom-Alfa** [comment]
Hello @aligent-lturner 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-818` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5
