### ISSUE TITLE
Update phpunit to the latest version for magento-coding-standard

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#33622]
Update PHPUnit to the latest version for magento-coding-standard repository.

This will also require update or elimination of `PHP_CodeSniffer\Tests\Standards\AbstractSniffUnitTest` dependency.

**Comment by sivaschenko** [comment]
@magento export issue to Jira project AC as Story

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by ihor-sviziev** [comment]
FYI I tried to update to phpunit 8 or phpunit 9 - it unit tests were failing due to missing `void` return type on setUp method on the https://github.com/squizlabs/PHP_CodeSniffer/blob/master/tests/Standards/AbstractSniffUnitTest.php#L55

**Comment by korovitskyi** [comment]
Hi, @ihor-sviziev , @sivaschenko .
I'm not sure that we can update PHPUnit version to 8 or 9(lastest). 
As the dependency `squizlabs/php_codesniffer:3.6` (lastest) support only `PHPUnit:7.x` as lastest.
And the whole `magento-coding-standard ` depends on `squizlabs/php_codesniffer'` package.

Please, let me know if we have any variants here.
Thank you.

**Comment by ihor-sviziev** [comment]
@korovitskyi, as an option, we can ask if they're going to add such compatibility and/or send them a pull request? :)

**Comment by korovitskyi** [comment]
@ihor-sviziev , yes, looks like they are going to add, we can see at [PHP_CodeSniffer V 4.0](https://github.com/squizlabs/PHP_CodeSniffer/tree/4.0), but it is not released yet.
