### ISSUE TITLE
Body Tag Left Blank

### ISSUE THREAD

**Issue by StuartLBG** [magento/magento2#33634]
### Preconditions (*)
2.4.2 or 2.4.2-p1
PHP 7.4

### Steps to reproduce (*)

1. I have updated 2 separate Magento instances, one from 2.3.2 and one from 2.4.0-p1 to 2.4.2

### Expected result (*)

Body tag is generated with appropriate CSS tags (pre 2.4.2)
![image](https://user-images.githubusercontent.com/48946329/127634594-ec6ab367-dcd2-4845-aacb-e660b17853f5.png)

### Actual result (*)

Body tag is left blank (post 2.4.2)
Elements tab in dev tools:
![image](https://user-images.githubusercontent.com/48946329/127634640-3a45db10-4f76-4e58-bb11-2b5beb443835.png)
However, sources tab in dev tools:
<body data-container="body"
        id="html-body" itemtype="http://schema.org/Product" itemscope="itemscope" class="page-product-configurable catalog-product-view product-test categorypath-womens category-womens page-layout-1column">

I have removed all custom theme and modules and the above still occurs.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @StuartLBG,
We tried to reproduce it on Magento 2.4.2 which is upgraded from 2.4.0-p1. unfortunately we could not find this issue, it works as expected. Hence added the label 'Needs update'

Please find the attached snapshots for reference.

![BodyTag](https://user-images.githubusercontent.com/51681379/127663475-ed52e9f1-51fd-43e8-b052-4a2988bab4ea.JPG)
![Version](https://user-images.githubusercontent.com/51681379/127663607-6ffdfac4-aa46-4174-ba98-1ebdd3c61496.JPG)
Thanks

**Comment by StuartLBG** [comment]
Have you confirmed that the body works correctly on the frontend? 

I have checked my admin and the body is working correctly on that side as it is on yours

![image](https://user-images.githubusercontent.com/48946329/127665487-a122977e-226e-43ad-8de2-80aded66a72b.png)

**Comment by engcom-Delta** [comment]
Hi @StuartLBG,
Verified on Magento 2.4.2 Frontend but could see the body tag with values. Please find the attached snapshots for reference.
![bodyTag_collapsed](https://user-images.githubusercontent.com/51681379/128863625-f3ba78e3-09f6-463a-968b-2478b256d91f.JPG)
![bodytag_expansed](https://user-images.githubusercontent.com/51681379/128863656-004f7790-fe45-4fce-922c-8fe402372d54.JPG)
