### ISSUE TITLE
Date issue with UI components Date form Element when Interface Locale is English UK

### ISSUE THREAD

**Issue by alicedfisheye** [magento/magento2#33630]
### Preconditions (*)
Magento 2.4.2-p1 - Admin Account with the Interface Locale = "English (United Kingdom) / English (United Kingdom)"

### Steps to reproduce (*)
1. Create an admin account with the Interface Locale = "English (United Kingdom) / English (United Kingdom)"
2. Create a UI component with a form element of date and set 'showsTime' as false. 

For example : 

        <field name="pet_birthday" formElement="date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">Pet</item>
                </item>
            </argument>
            <settings>
                <validation>
                    <rule name="required-entry" xsi:type="boolean">true</rule>
                </validation>
                <dataType>text</dataType>
                <label translate="true">Birthday</label>
                <dataScope>pet_birthday</dataScope>
            </settings>
            <formElements>
                <date>
                    <settings>
                        <options>
                            <option name="dateFormat" xsi:type="string">MMM d, y</option>
                            <option name="showsTime" xsi:type="boolean">false</option>
                            <option name="maxDate" xsi:type="string">+30y</option>
                        </options>
                    </settings>
                </date>
            </formElements>
        </field>

### Expected result (*)
1. When you save the date on the newly created UI component the date saved should match the date entered. 

### Actual result (*)
1. When you save the date on the newly created UI component the date saved is wrong. 

**NOTE : ** This issue does not just occur when you create a new UI component. If you change `showsTime` to `false` on line 150 in the file : vendor/magento/module-sales-rule-staging/view/adminhtml/ui_component/salesrulestaging_update_remove_form.xml
You have the same result. 

---
Please provide [Severity]

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Lima** [comment]
Hi @alicedfisheye,

The information you provided is not sufficient for us to reproduce this issue. 

It would be easier for us if you can elaborate on Step 2 or perhaps you can share the screenshots of the results that you are getting ?

Thanks

**Comment by engcom-Lima** [comment]
Hi @alicedfisheye,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
