### ISSUE TITLE
Adminhtml tax totals renderer incorrectly attempting to get id of array

### ISSUE THREAD

**Issue by alex-james** [magento/magento2#33636]
Magento 2.4.2 within the following file at line 62 the template attempts to call getId() on $rates which is an array, this can be clearly seen at line 64 where $rates['percent] is used:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/templates/order/totals/tax.phtml

It looks like the id is being used as an element id simply so it can be referenced later at line 77, it also looks like this issue has been resolved in the next section of the file where a pseudo id is generated on line 92 with:

$infoId = $randomHelper->getRandomString(20);

this variable is then used to set and reference the element id.

### Preconditions (*)
None, can be seen clearly in the Magento 2.4.2 source code, see above link

### Steps to reproduce (*)
I have spotted this when creating a zero value order with the No Payment method and then viewing the invoice of the order in the backend.

### Expected result (*)
The template should not attempt to call a method on an array and the invoice page should render

### Actual result (*)
The template fails with an "cannot call method getId() on array" error and the invoice page is not rendered correctly.

**Comment by mrtuvn** [comment]
i think this one duplicated with this https://github.com/magento/magento2/issues/33638

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/issues/30094
