### ISSUE TITLE
Can't import additional images when product already has image

### ISSUE THREAD

**Issue by vseager** [magento/magento2#33642]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Create new product in admin
2. Upload product image in admin and set to base image, small image, thumbnail image
3. Upload additional image to `var/import/images`
4. Create import file and upload additional images via CSV import  (Example import file: [test-import.csv](https://github.com/magento/magento2/files/6908170/test-import.csv))

### Expected result (*)

1. Product should have two images

### Actual result (*)

1. New image isn't uploaded, product only has original image

**Note:** Uploading images via CSV works as expected when the product doesn't have any images already. The issue only exists when added additional images to a product which already has images.
 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @vseager,

I tried importing the images as per provided steps, it works as expected in Magento 2.4.2 .
Please find the attached screenshot for reference.

Kindly request to review the steps. Hence added 'Needs Update
![Image_importing](https://user-images.githubusercontent.com/51681379/127865119-96752f15-cd7e-4d82-996f-eef0c3facad0.jpg)
'
