### ISSUE TITLE
Wrong redirectCode returned by urlResolver() GraphQL endpoint

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#33641]
### Preconditions (*)

1. Magento 2.4.2 CE
2. docker-php-fpm:7.4-0.0.1

### Steps to reproduce (*)

1. Make request:
![image](https://user-images.githubusercontent.com/9048430/127664036-6fb2d8fb-de98-4c07-8840-3e5526abca69.png)

### Expected result (*)

1. "redirectCode" in response should be "0"

### Actual result (*)

1. "redirectCode" in response is "301"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by kirillvidyuk** [comment]
@magento give me 2.4-develop instance

**Comment by kirillvidyuk** [comment]
I'm able to reproduce issue with Vanilla Magento instance:
![image](https://user-images.githubusercontent.com/9048430/127665623-c150bda4-18a3-4d95-8b22-78af335f6111.png)

**Comment by kirillvidyuk** [comment]
@magento I am working on this

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by kirillvidyuk** [comment]
@magento I am working on this
