### ISSUE TITLE
Incorrect totals calculation in order_invoice prevents paypal checkout

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#33651]
### Preconditions (*)
1. Magento 2.4.1 
2. Paypal website payments standard or express checout

### Steps to reproduce (*)
1. Create a sales order with a discount coupon using live credentials on paypal (not sandbox credentials). When using the sandbox credentials everything works for some reason. I think paypal is missing the verification for AMT and ITEMAMT on sandbox. 
2. Try to checkout with paypal
3. Receive an error about AMT mismatch with ITEMAMT

I've debugged it a lot to see what is happening behind the scenes and how that 6.14 turns out in my request to paypal gateway, and it seems it's due to orders total calculation. 

In file https://github.com/magento/magento2/blob/2c94da6391b61d6e336b3aa3b5739f6df874e7dc/app/code/Magento/Sales/etc/sales.xml the sort order calculation is like this

```xml
    <section name="order_invoice">
        <group name="totals">
            <item name="subtotal" instance="Magento\Sales\Model\Order\Invoice\Total\Subtotal" sort_order="50"/>
            <item name="discount" instance="Magento\Sales\Model\Order\Invoice\Total\Discount" sort_order="100"/>
            <item name="shipping" instance="Magento\Sales\Model\Order\Invoice\Total\Shipping" sort_order="150"/>
            <item name="tax" instance="Magento\Sales\Model\Order\Invoice\Total\Tax" sort_order="200"/>
            <item name="cost_total" instance="Magento\Sales\Model\Order\Invoice\Total\Cost" sort_order="250"/>
            <item name="grand_total" instance="Magento\Sales\Model\Order\Invoice\Total\Grand" sort_order="350"/>
        </group>
    </section>
```

So in my case the discount amount is also applied to the shipping amount. I end up with the following amounts in checkout

subtotal -> 5.90
discount -> -10.79
shipping -> 5
tax -> 0.02
grand total -> 0.11

However for the order_invoice which is used by paypal, when totals are collected in this order 

subtotal -> discount -> shipping -> tax 

the grand total becomes 6.14  because the discount is not applied to the shipping amount. It seems that Magento is also using the amounts without tax for subtotal and shipping totals collection but with tax for discount amount. 

If I change the order of execution to be

subtotal -> shipping -> tax -> discount the grand_total becomes 0.11 

Here's my tax configuration in backend 

![image](https://user-images.githubusercontent.com/20220341/127765178-5cd61e25-7601-4208-ae5a-046d5ec6f1b4.png)

Maybe I have something wrong configured but it seems that this shouldn't happen as the checkout values are correct. 

### Expected result (*)
Paypal completes the order without errors

### Actual result (*)

The payment fails with error "Transaction refused because of an invalid argument. See additional error messages for details"

Extract from payment log 

```
[2021-08-01 08:39:44] main.DEBUG: array (
  'url' => 'https://api-3t.paypal.com/nvp',
  'DoExpressCheckoutPayment' =>
  array (
    'TOKEN' => 'EC-1A314795U40262610',
    'PAYERID' => 'RZ63UJNG2MNWJ',
    'PAYMENTACTION' => 'Sale',
    'AMT' => '6.14',
    'CURRENCYCODE' => 'EUR',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'NOTIFYURL' => 'https://example.com/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'ITEMAMT' => '0.11',
    'BUSINESS' => '---',
    'EMAIL' => 'test@example.com',
    'FIRSTNAME' => 'test',
    'LASTNAME' => 'test',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'GR',
    'STATE' => 'Άρτας',
    'CITY' => 'Quae fuga Dolor ut ',
    'STREET' => 'Rerum accusamus dolo',
    'ZIP' => '32123',
    'PHONENUM' => '+1111111111',
    'SHIPTOCOUNTRYCODE' => 'GR',
    'SHIPTOSTATE' => 'Άρτας',
    'SHIPTOCITY' => 'Quae fuga Dolor ut ',
    'SHIPTOSTREET' => 'Rerum accusamus dolo',
    'SHIPTOZIP' => '32123',
    'SHIPTOPHONENUM' => '+11111111',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'test test',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' =>
  array (
    'TOKEN' => 'EC-XXXXX',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2021-08-01T08:39:44Z',
    'CORRELATIONID' => 'XXXXX',
    'ACK' => 'Failure',
    'VERSION' => '72.0',
    'BUILD' => '55829961',
    'L_ERRORCODE0' => '10413',
    'L_SHORTMESSAGE0' => 'Transaction refused because of an invalid argument. See additional error messages for details.',
    'L_LONGMESSAGE0' => 'The totals of the cart item amounts do not match order amounts.',
    'L_SEVERITYCODE0' => 'Error',
  ),
) [] []
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maghamed** [comment]
@magento give me 2.4-develop instance

**Comment by liamomg** [comment]
Same issue of https://github.com/magento/magento2/issues/24233

**Comment by ioweb-gr** [comment]
With the difference in my case it's not a rounding issue. The amounts differ by lots of digits

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
Paypal Express Checkout payment is working fine for Greece Shipping.
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
[2021-09-23 07:38:58] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'DoExpressCheckoutPayment' => 
  array (
    'TOKEN' => 'EC-8JJ273199M170581E',
    'PAYERID' => 'EFY585K73D8NQ',
    'PAYMENTACTION' => 'Authorization',
    'AMT' => '0.27',
    'CURRENCYCODE' => 'EUR',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'NOTIFYURL' => 'http://magento2.4.local/index.php/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'ITEMAMT' => '0.27',
    'BUSINESS' => NULL,
    'EMAIL' => 'srfrefre4343@gmail.com',
    'FIRSTNAME' => 'vreregre',
    'LASTNAME' => 'rgreger',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'GR',
    'STATE' => 'GR-I',
    'CITY' => 'Athens',
    'STREET' => 'rgreger 4554',
    'ZIP' => '104 31',
    'PHONENUM' => '34535454354',
    'SHIPTOCOUNTRYCODE' => 'GR',
    'SHIPTOSTATE' => 'GR-I',
    'SHIPTOCITY' => 'Athens',
    'SHIPTOSTREET' => 'rgreger 4554',
    'SHIPTOZIP' => '104 31',
    'SHIPTOPHONENUM' => '34535454354',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'vreregre rgreger',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-8JJ273199M170581E',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2021-09-23T07:40:51Z',
    'CORRELATIONID' => '604beeabad1e',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '55938276',
    'TRANSACTIONID' => '7T003991XD436531G',
    'TRANSACTIONTYPE' => 'expresscheckout',
    'PAYMENTTYPE' => 'instant',
    'ORDERTIME' => '2021-09-23T07:40:50Z',
    'AMT' => '0.27',
    'TAXAMT' => '0.00',
    'CURRENCYCODE' => 'EUR',
    'PAYMENTSTATUS' => 'Pending',
    'PENDINGREASON' => 'authorization',
    'REASONCODE' => 'None',
    'PROTECTIONELIGIBILITY' => 'Eligible',
    'INSURANCEOPTIONSELECTED' => 'false',
    'SHIPPINGOPTIONISDEFAULT' => 'false',
    'PAYMENTINFO_0_TRANSACTIONID' => '7T003991XD436531G',
    'PAYMENTINFO_0_TRANSACTIONTYPE' => 'expresscheckout',
    'PAYMENTINFO_0_PAYMENTTYPE' => 'instant',
    'PAYMENTINFO_0_ORDERTIME' => '2021-09-23T07:40:50Z',
    'PAYMENTINFO_0_AMT' => '0.27',
    'PAYMENTINFO_0_TAXAMT' => '0.00',
    'PAYMENTINFO_0_CURRENCYCODE' => 'EUR',
    'PAYMENTINFO_0_PAYMENTSTATUS' => 'Pending',
    'PAYMENTINFO_0_PENDINGREASON' => 'authorization',
    'PAYMENTINFO_0_REASONCODE' => 'None',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITY' => 'Eligible',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE' => 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    'PAYMENTINFO_0_SECUREMERCHANTACCOUNTID' => '54Z2EE6T7PRB4',
    'PAYMENTINFO_0_ERRORCODE' => '0',
    'PAYMENTINFO_0_ACK' => 'Success',
  ),
) [] []
