### ISSUE TITLE
Magento 2.4.2 Uncached After Placing Order

### ISSUE THREAD

**Issue by hasnatme** [magento/magento2#33650]
### Preconditions (*)

1. Magento 2.4.2 (CE)
2. Varnish Cache or FPC

### Steps to reproduce (*)

1. Place order with any products from any category as customer.
2. Place order from admin panel with any products from any category.

### Expected result (*)

1. Magento should purge cache for varnish only for the product by tag. And rest cache should remain intact.

### Actual result (*)

1. However Magento registering full varnish cache to be purged and the whole store becoming unchached again. As a result slow user experience again and again as long as customers kept ordering.
2. Without placing any orders or changing anything, no cache is being purged until varnish TTL expires.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Seem unclear information
Can you provide in the case varnish used which version that you used?
Case 1 Both enabled varnish + FPC
Case 2 Enabled Varnish Disabled FPC
Case 3 Disabled Varnish Enabled FPC

**Comment by hasnatme** [comment]
Hello,

This is my website www.banglashoppers.com you can check yourself by placing an order, you do not need to pay as we have cash on delivery system. My Hosting is cloudways.com. Please note, it is doing after couple of min, not instantly.

Using latest 2.4.2 CE with FPC and Varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e

**Comment by rvanwilgen** [comment]
Seems related to issue #30128

**Comment by mrtuvn** [comment]
Turn out after place order with some deduct amount products internal code do some stuff to resync and clear cache.

**Comment by mrtuvn** [comment]
@hasnatme Can you update more details stock Inventory used ?

**Comment by engcom-Lima** [comment]
Hi @hasnatme,

This issue seems duplicate to #30128.

Can you please check and confirm if you are having same problems ? If yes, we can close this issue since 1 issue is already open.

**Comment by engcom-Lima** [comment]
Hi @hasnatme,

This ticket is duplicate to #30128 hence we are closing this one. Please follow up on other issue for the update.
