### ISSUE TITLE
Custom options with price type "percent" is not available for configurable product

### ISSUE THREAD

**Issue by rosemariepopescu** [magento/magento2#33655]
Hi, I know this issue was countlessly reported during the last 5 years, but I am reporting it again, maybe somebody will take care this time.
It is a real nuisance
Custom options with price type "percent" is not available for configurable product on Magento 2.4

Thank you!

**Comment by krishprakash** [comment]
Hi @rosemariepopescu.
Could you please provide more details as described in Issue reporting guidelines
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks!!

**Comment by krishprakash** [comment]
Hi @rosemariepopescu.
Feel free to reopen the issue once you update all the details as per the issue reporting guidelines.
Thanks
