### ISSUE TITLE
Magento 2 Backend and Frontend Stopped working

### ISSUE THREAD

**Issue by reihaan** [magento/magento2#33665]
I am running magento 2.3.3 on a VPS. Recently it stopped working, could it be due to the composer? As our server administrator updated the composer version to 2. Now after degrading the composer to version 1 the issue still remains. I ran the composer install, update and bin/magento commands to update and deployed the website again, but still can't access frontend and backend. 

The error I am getting is as follow: 

{"0":"Expecting a string, got NULL","1":"<pre>#1 Zend\\Uri\\Uri->parse() called at [vendor\/magento\/module-backend\/App\/Area\/FrontNameResolver.php:140]\n#2 Magento\\Backend\\App\\Area\\FrontNameResolver->getHostWithPort() called at [vendor\/magento\/module-backend\/App\/Area\/FrontNameResolver.php:129]\n#3 Magento\\Backend\\App\\Area\\FrontNameResolver->isHostBackend() called at [vendor\/magento\/module-backend\/App\/Area\/FrontNameResolver.php:106]\n#4 Magento\\Backend\\App\\Area\\FrontNameResolver->getFrontName() called at [vendor\/magento\/framework\/App\/AreaList.php:73]\n#5 Magento\\Framework\\App\\AreaList->getCodeByFrontName() called at [vendor\/magento\/framework\/App\/Http.php:132]\n#6 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#7 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#8 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/\/data\/web\/magento2\/pub\/errors\/default\/images\/favicon.ico","script_name":"\/index.php"}

Running Magento 2.3.3

Tested with PHP 7.2, 7.3 and 7.4  but issue remains.

Can someone please guide?

Thank You

**Comment by engcom-Delta** [comment]
Hi @reihaan , 
Kindly provide issue description ,steps to reproduce ,expected results & actual results.

Thanks

**Comment by reihaan** [comment]
The website was in production state and working fine but now suddenly it stopped working on investigating the issue I found the above error in the error report.

The error states expecting a string got null.

need help to fix this issue.

thank you

**Comment by hostep** [comment]
@reihaan: github isn't really the place to ask for help with a problem you have with Magento. It's meant for reporting bugs or feature requests. This doesn't appear to be a bug but a misconfiguration in your Magento shop.

Anyways, if I follow your stacktrace, I end up [over here](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Backend/App/Area/FrontNameResolver.php#L123-L129), and I believe that either one of these configuration options will have been set to `NULL` in your database, so you'd best double check these:
- Stores > Configuration > General > Web > Base URLs > Base URL (search for an entry `web/unsecure/base_url` in the `core_config_data` table in your database)
- Stores > Configuration > Advanced > Admin > Admin Base URL > Custom Admin URL (search for an entry `admin/url/custom` in the `core_config_data` table in your database)

I hope this helps but if it doesn't, I would advise you to head over to http://community.magento.com/ or https://magento.stackexchange.com/ and try getting help over there.

Good luck! 🙂

**Comment by engcom-Delta** [comment]
Hi @reihaan,

Kindly confirm @hostep comments.

Thanks
