### ISSUE TITLE
New Checkout Shipping Address Has Company After Changing Show Company to No

### ISSUE THREAD

**Issue by moranotcsos** [magento/magento2#33663]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. In the admin panel, change Show Company to Optional, press Save Config, and then clear cache.
2. Create a customer.
3. Login as the customer and add separate billing and shipping addresses with a company on both.
3. In the admin panel, change Show Company to No, press Save Config, and then clear cache.
2. While logged in as the customer, add items to the cart and go to checkout.
3. Create a new shipping address (the company field should not be visible).
4. Place the order.

### Expected result (*)

1. The shipping address on the order does not have a company set.

### Actual result (*)

1. The shipping address on the order has a company set.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @moranotcsos. Not able to replicate the issue as provided steps by you

Refer the steps which I follow

- Create new account -> Login into account
- Add different address for billing and shipping with company added 
- Updated the configuration for Show Company to No
- Clear the caches
- Login into account -> Add product to cart
- Checkout -> Add new shipping address
- Observe the company field not showing here
- 
![image](https://user-images.githubusercontent.com/46617848/127961274-a9531dda-aaf1-4a2b-ba71-5b147168d4c3.png)

Feel free the reopen once you confirm that issue reproduce on latest magento 2.4-develop instance

Thanks!!

**Comment by moranotcsos** [comment]
The issue isn't that the company field is missing.

The issue is that, after placing the order, the shipping address created at checkout on the customer account and in the Magento database has the old shipping address company on it, even though the field was not showing.

**Comment by moranotcsos** [comment]
Hello,

I just wanted to confirm you received my response. It seems there is a misunderstanding about what the issue is. I've reiterated it below:

### Steps to reproduce (*)

1. In the admin panel, change Show Company to Optional, press Save Config, and then clear cache.
2. Create a customer.
3. Login as the customer and add separate billing and shipping addresses with a company on both.
3. In the admin panel, change Show Company to No, press Save Config, and then clear cache.
2. While logged in as the customer, add items to the cart and go to checkout.
3. Create a new shipping address (the company field will not be visible -- this is working and is not the issue).
4. Place the order.

### Expected result (*)

1. After placing the order, the shipping address should not have a shipping company on it on the customer address or on the order in the database.

### Actual result (*)

1. After placing the order, the shipping address will have the previous shipping address's company on it in the database. **The company will not show in the customer address book or on the order in the admin panel**. You will only see it **in the Magento database** in the company field on the order and on the customer address.
