### ISSUE TITLE
Jquery Issuein admin area

### ISSUE THREAD

**Issue by sandeepnetqual** [magento/magento2#3366]
I am using: PHP Version 7.0.2:
1. I am getting error in admin area, the side bar menus are not working. 
2. I have found some of jquery errors in the console.
3. The fonts icons are not working.

Please see the attached screenshots:

![magento menus](https://cloud.githubusercontent.com/assets/17174615/12972540/27b215a0-d0cc-11e5-86b6-4137d9fb481c.png)
![jqueryissuemagento2 02](https://cloud.githubusercontent.com/assets/17174615/12972541/27c2c76a-d0cc-11e5-9832-e282da1c5232.png)

**Comment by mrkhoa99** [comment]
Hello,
Try to run : `php bin/magento setup:static-content:deploy` under Magento ROOT folder

**Comment by MomotenkoNatalia** [comment]
@sandeepnetqual Please let us know if this helps.

**Comment by MomotenkoNatalia** [comment]
As there are no new updates from reporter, issue will be closed.
