### ISSUE TITLE
Upgrade Issue, While upgrade from Magento 2.4.2-p1 to Magento 2.4.3

### ISSUE THREAD

**Issue by arjunadobe** [magento/magento2#33678]
### Preconditions (*)
1. Magento 2.4.3 (EE)
2. Composer 2

### Steps to reproduce (*)
Hi,

I am upgrading from Magento 2.4.2-p1 from Magento 2.4.3. Composer Update was working fine, but when I tried to run

`php bin/magento setup:upgrade`

I am getting the below error.

`Unable to apply data patch Magento\Paypal\Setup\Patch\Data\UpdateBmltoPayLater for module Magento_Paypal. 
Original exception message: Notice: Undefined offset: 1 in 
vendor/magento/module-paypal/Setup/Patch/Data/UpdateBmltoPayLater.php on line 138
`
When I checked the code, I found out we didn't check whether the value is exploadable in some scenarios like this

                                                
path => payment/paypal_express_bml/active , value => 0

and it's throwing the error in this line

` $page = $settingParts[0];
  $setting = $settingParts[1];`

### Expected result (*)
While Setup:upgrade it should work fine

### Actual result (*)
`Module 'Magento_Paypal':
Unable to apply data patch Magento\Paypal\Setup\Patch\Data\UpdateBmltoPayLater for module Magento_Paypal.
Original exception message: Notice: Undefined offset: 1 in vendor/magento/module-paypal/Setup/Patch/Data/UpdateBmltoPayLater.php on line 138`

Fix for this :
Add  if(strpos($setting, '_') == false) { continue }

`        foreach ($bmlSettings as $bmlPath => $bmlValue) {
            $setting = str_replace(self::BMLPATH, '', $bmlPath);
            if(strpos($setting, '_') == false) {
                continue;
            }`

**Comment by ericclaeren** [comment]
Yes, can confirm this issue. I had to remove config values

```
DELETE FROM `core_config_data` WHERE `path` IN ('payment/paypal_express_bml/active', 'payment/paypal_express_bml/publisher_id'); 
```

To get setup:upgrade to run.

**Comment by arjunadobe** [comment]
> 
> 
> Yes, can confirm this issue. I had to remove config values
> 
> ```
> DELETE FROM `core_config_data` WHERE `path` IN ('payment/paypal_express_bml/active', 'payment/paypal_express_bml/publisher_id'); 
> ```
> 
> To get setup:upgrade to run.

`DELETE FROM core_config_data WHERE path="payment/paypal_express_bml/active";` 

This is enough

**Comment by ericclaeren** [comment]
Yes @arjunadobe, thanks, you're absolutely right!

**Comment by EmperorKonstantin** [comment]
@ericclaeren Can you let me know how you diagnosed this bug?

**Comment by fascinosum** [comment]
@magento export issue to Jira project AC as Bug

**Comment by fascinosum** [comment]
hi @arjunadobe,
thank you for reporting this issue. 
The internal team will work to fix this, internal Jira ticket linked to the GitHub issue, and the status will be updated accordingly
 
@ericclaeren thank you for the workaround

**Comment by ericclaeren** [comment]
> @ericclaeren Can you let me know how you diagnosed this bug?

I have upgraded a Adobe Commerce (F.K.A Magento EE) from version 2.3.5-p1 to 2.4.3. And got stuck during setup upgrade.

**Comment by EmperorKonstantin** [comment]
@ericclaeren  During setup:upgrade what steps did you take that lead you to find the mysql entry that was causing the hangup?

**Comment by sims-smith-corona** [comment]
> @ericclaeren During setup:upgrade what steps did you take that lead you to find the mysql entry that was causing the hangup?

In my case, I stumbled upon it by looking at the file/line number referenced in the console error during setup:upgrade:
vendor/magento/module-paypal/Setup/Patch/Data/UpdateBmltoPayLater.php on line 138

In that section of the file, UpdateBmltoPayLater.php is just grabbing all rows from the core_config_data table whose path begins with "payment/paypal_express_bml/". It is anticipating that all of the returned path values include some string after that "payment/paypal_express_bml/" portion that includes an underscore.

I went and queried that table:

`SELECT * FROM `core_config_data` WHERE `path` LIKE 'payment/paypal_express_bml/%' `

I found that the very first record had the path "payment/paypal_express_bml/active" which would result in the original error.

**Comment by fahu** [comment]
I experience the same issue on update of Magento 2.3.5 to 2.4.3. The solution suggested by @arjunadobe fixed the issue for us.

**Comment by ntoombs19** [comment]
I experienced this issue upgrading from 2.4.2-p1 to 2.4.3

**Comment by drinkingsouls** [comment]
I also have this issue after upgrade from 2.4.2 to 2.4.3.

**Comment by hostep** [comment]
The issue got closed, I assume that's because the following fix landed on `2.4-develop`: https://github.com/magento/magento2/commit/a30173520979f4fd79668dc6d7adb0e8cab6dc60

**Comment by sdzhepa** [comment]
Hello 

Let me try to bring some light on this issue.
Right not in internal Jira, there are two tickets linked with this issue

1. **AC-493**
- Status: Fixed/Done
- Target version: 2.4.4 (means should be available in 2.4.4 release)
- related commits can be found by search using  `AC-493` in commits: [EXAMPLE](https://github.com/magento/magento2/search?q=AC-493&type=commits)  

2. **AC-507**
-  Status: Open/Ready for Dev
- Target version: 2.4.3-p1

cc: @drinkingsouls @ntoombs19 @fahu @sims-smith-corona @EmperorKonstantin @fascinosum @ericclaeren @ihor-sviziev @hostep

**Comment by ericclaeren** [comment]
Just an idea, maybe it could be helpful to include a Magento Quality Patch for this issue, so people don't have to manually find and apply a patch for this issue? Lot's of people will be upgrading and possible run into this issue.

**Comment by ihor-sviziev** [comment]
@ericclaeren, definitely a good idea! Will you be able to create a PR to the https://github.com/magento/quality-patches?

**Comment by ericclaeren** [comment]
@ihor-sviziev Sure, not today, but might be able to look into this mid-next week.

**Comment by drinkingsouls** [comment]
I note that it is ready for development/to be fixed in 2.4.4 but what is the current solution to be able to upgrade from 2.4.2 to 2.4.3?

**Comment by ihor-sviziev** [comment]
@drinkingsouls, you can apply the following commit as a patch https://github.com/magento/magento2/commit/5753111dc7ba1dca2ef0ca98f7d0abac488ebbb2
Here is instructions how to do so https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#custom-patches

**Comment by heyepic** [comment]
I did this fix but now I can't view any orders in the admin:
[2021-08-22 16:22:14] main.CRITICAL: Payment model name is not provided in config! {"report_id":"8dec9410e07d0b28947a72006f673b6ad0a2035af6f0523f3fe680c1ba7c8168","exception":"[object] (UnexpectedValueException(code: 0): Payment model name is not provided in config! at /home/asdf/public_html/vendor/magento/module-payment/Helper/Data.php:113)"} []

**Comment by speller** [comment]
@ihor-sviziev 
I'm trying to apply a patch according to the instructions you mentioned but getting the following error while patching:

```
patch '-p1' --no-backup-if-mismatch -d '/magento/vendor/magento/module-paypal' < '/magento/patches/composer/github-issue-33678.diff'
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/app/code/Magento/Paypal/Setup/Patch/Data/UpdateBmltoPayLater.php b/app/code/Magento/Paypal/Setup/Patch/Data/UpdateBmltoPayLater.php
|index 449b130fa992..9684c60cbdd6 100644
|--- a/app/code/Magento/Paypal/Setup/Patch/Data/UpdateBmltoPayLater.php
|+++ b/app/code/Magento/Paypal/Setup/Patch/Data/UpdateBmltoPayLater.php
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
```
WHat I'm doing wrong?
