### ISSUE TITLE
Unable to add Bundle product containing products with multiple FPT when allowed apply taxes on Fixed Product Taxes

### ISSUE THREAD

**Issue by aman2134** [magento/magento2#33670]
### Preconditions (*)

1. Magento version - 2.4.2
2.

### Steps to reproduce (*)

1. Create a simple product with multiple Fixed product taxes
2. Create a bundle product and add the above product as one of the options
3. Enable Configuration -> Sales->Tax -> Fixed Product Taxes-> Apply Tax To FPT
4. Go to frontend and try adding the bundle product to cart  with the product with FPT selected

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2. Log- Notice: Array to string conversion in /var/www/html/mage2.4/vendor/magento/module-weee/Model/Total/Quote/Weee.php on line 314 Trace: <pre>#1 array_unique() called at [vendor/magento/module-weee/Model/Total/Quote/Weee.php:314]
 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @aman2134,

Tired in Magento 2.4. Develop, unfortunately it is not reproducible ,it works as expected.
Please find the attached screenshots for reference. Kindly review the provided steps.
<img width="960" alt="FPT_product" src="https://user-images.githubusercontent.com/51681379/128164947-e6a5c530-cadd-420c-a63b-c8c6ba53e2d5.png">


Added the label 'Needs update'
Thanks
