### ISSUE TITLE
Error 500 when an empty XML file is present

### ISSUE THREAD

**Issue by MorganGonzales** [magento/magento2#3367]
I'm receiving the following error when I created an empty XML file somewhere within my config folder.

> PHP Catchable fatal error:  Argument 1 passed to Magento\Framework\Config\Dom::_mergeNode() must be an instance of DOMElement, null given, called in /Users/user/Sites/m2-training/vendor/magento/framework/Config/Dom.php on line 122 and defined in /Users/user/Sites/m2-training/vendor/magento/framework/Config/Dom.php on line 138

I think Magento should not prompt a 500 error when we are in the process of preparing out our XML files. Unless there's a fault in syntax.

**Comment by benmarks** [comment]
> I'm receiving the following error when I created an empty XML file

A completely empty XML file is syntactically invalid; see https://www.w3.org/TR/xml/#sec-documents

**Comment by scholtz** [comment]
i think Magento should not fail to load if any of the XML files in config dir or anywhere else is empty, invalid in xml parsing or invalid in xml schema validation..

i think everyone would prefer to load frontend with wrong files skipped and to show some error message in the admin area so that admin is notified

**Comment by benmarks** [comment]
@scholtz

> i think Magento should not fail to load if any of the XML files in config dir or anywhere else is empty, invalid in xml parsing or invalid in xml schema validation..

This is how the system functions in production mode, though, preparing the system for production mode requires valid files and module state.

> i think everyone would prefer to load frontend with wrong files skipped and to show some error message in the admin area so that admin is notified

Can you support this claim about "everyone" with data? I can think of no good reason for invalid files to be accommodated. Warning an administrator via the GUI does not seem appropriate, as this condition is necessarily a low-level concern which should be handled by developers.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
