### ISSUE TITLE
My gift registry will not display within my site

### ISSUE THREAD

**Issue by homefieldandstream** [magento/magento2#33684]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @homefieldandstream,

Kindly provide issue description, steps to reproduce, actual results and expected results.so that we can replicate it in respective magento version's.Hence added the label 'Needs Update'.

Thanks

**Comment by homefieldandstream** [comment]
Hi,
Within Magento i have an extension for Gift Registry.
In this gift registry i can make engagement and wedding lists.
When making the wedding list, I created it within my website.
I have created a wedding list but it will not appear on my website under
the wedding list section.
I was wondering if there is a fix to this?

Regards,
Ryan
*Home, Field & Stream *
www.hfs-online.com

Home, Field & Stream
18-20 Church Street
Enniskillen
BT74 7EJ
Northern Ireland

*Tel:*  0044 (0)2866 340 758 (Online Sales)
*Tel:*  0044 (0)2866 322 114 (Main)
*Fax:* 0044 (0)2866 327 335
*Website:* www.hfs-online.com
*Email:* ***@***.***

This e-mail transmission, including any attachments, is intended only for
the named recipient(s) and may contain information that is privileged,
confidential and/or exempt from disclosure under applicable law.
If you have received this transmission in error, or are not the named
recipient(s), please notify Home, Field & Stream immediately by return
e-mail and permanently delete this transmission, including any attachments.

**Comment by engcom-Delta** [comment]
Hi @homefieldandstream,

Kindly provide the steps to install for GiftRegistry , What u followed?. in addition please give issue descriptions , steps to follow , actual , expected results.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
