### ISSUE TITLE
Magento 2.4.2 We can’t save customer

### ISSUE THREAD

**Issue by thedigitalkern** [magento/magento2#33687]
### Preconditions (*)

1. MAGENTO 2.4.2 via Bitnami

### Steps to reproduce (*)

1. Fresh Install of Magento 2.4.2

### Expected result (*)

1. New Customer Account Created successfully via frontend and logging in as a customer on Magento 2.4.2 out of the box setup. Alternatively, new customer account can be created via Admin.

### Actual result (*)

1. I am facing unusual error such as “We can’t save the customer.” Form refreshes. Data does not get saved.
2. Customer data (New User Account) cannot be created via Magento Admin as well. Error - "Something went wrong."
3. Form Key refreshes on every submit successfully.
4. Changing env files bricks the instance with 503

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @thedigitalkern,
We tried to reproduce the issue and it is not reproducible .it works as expected.
Kindly find the attached snapshot for reference.

Thanks
![Uploading usercreation.jpg…]()

**Comment by thedigitalkern** [comment]
Well, that's strange, I have setup two instances and both don't seem to support Create a New Customer Account via Front end and Admin as well. Please advise how to amend this error if not reproduced on a fresh install by your end. None of the forums or Support topics address this issue.

**Comment by engcom-Delta** [comment]
Hi @thedigitalkern,

Please find the attached video for reference which customer creation is successful.
https://user-images.githubusercontent.com/51681379/128948639-aa9d0715-022d-4a9b-a52e-17691a929910.mp4

Kindly have a look into it.

Thanks
