### ISSUE TITLE
Magento 2 : My custom payment module is not rendered at checkout

### ISSUE THREAD

**Issue by mohinik-chetu** [magento/magento2#3368]
I have created a payment module with two payment methods. When I install the module in new magento 2 setup, one method is displayed on checkout page but, not the second one.
method renderer js files are created in pub/static/...[Module]  but not included on checkout page for second method.
Unable to debug the issue. Please Help!!!

Second payment method renderer file is using Magento_Payment/js/view/payment/cc-form only, while first one using  Magento_Checkout/js/view/payment/default.
And both were working fine in my local environment where I developed the module.

**Comment by Jeevachezhiyan** [comment]
Yes me also facing same thing.My custom payment not rendering in front end

**Comment by Jeevachezhiyan** [comment]
Yes me also facing same problem .My custom payment is not rendering in front end

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
