### ISSUE TITLE
Magento Order issue

### ISSUE THREAD

**Issue by jadebaileywowcher** [magento/magento2#33693]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)
 I should be able to enter an order number or an email and pull up the order itself, this doesn't happen and just sticks on that screen with the red banner, circle swirling in middle of the screen.

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Delta** [comment]
Hi @jadebaileywowcher,

Thanks for raising an issue . Issue description, steps to reproduce ,actual results  are missing. kindly update them.
Hence we can reproduce the issue . added the label 'Needs update'.

**Comment by jadebaileywowcher** [comment]
I am not sure what you mean sorry?

You go onto magento, sign in, go to the left of the screen where it says sales, click there, then click orders and then that's where the problem is. Sent screenshots too

***@***.***

***@***.***

***@***.***Will not move from this screen

**Comment by ericclaeren** [comment]
@jadebaileywowcher 

Thanks for raising an issue, but you have given absolutely no information about the issue you are experiencing.

![image](https://user-images.githubusercontent.com/4748495/128356542-52fb76ab-e6b0-487e-817c-ccafda7645f6.png)

**Comment by jadebaileywowcher** [comment]
From: Jade Bailey
Sent: 05 August 2021 12:10
To: magento/magento2 ***@***.***>; magento/magento2 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [magento/magento2] Magento Order issue (#33693)

I am not sure what you mean sorry?

You go onto magento, sign in, go to the left of the screen where it says sales, click there, then click orders and then that's where the problem is. Sent screenshots too

***@***.***

***@***.***

***@***.***Will not move from this screen

**Comment by jadebaileywowcher** [comment]
Good Afternoon,

Im very sorry but I am not part of the technical team and can only tell you what I can see!

I have resent the 3 screenshots I took of Magento when I try to access the orders within the sales tab on the left and it sticks every time.

Please advise what you need from me and potentially where to find it and I will be very happy to try and get the information :)

Thanks in advance

Jade Bailey :)

Wowcher EU / Living Social and Wowcher Customer Services

**Comment by engcom-Delta** [comment]
Hi @jadebaileywowcher,
screenshots are missing , Kindly attach the screenshots, issue description, steps to follow , actual results & expected results.

Thanks

**Comment by jadebaileywowcher** [comment]
***@***.***


***@***.***

***@***.***

The screen does not change from this and the whirring circle. I click sales, click orders and the above happens

**Comment by engcom-Delta** [comment]
Hi @jadebaileywowcher ,
Not sure why it is outstanding still, but it is not reproducible on Magento 2.4.2 . Kindly suggest further action on this ticket.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
