### ISSUE TITLE
My custom payement method not showing in checkout page

### ISSUE THREAD

**Issue by Jeevachezhiyan** [magento/magento2#3369]
I have created one custom offline payment method,But in check out page it is not showing

**Comment by alena-marchenko** [comment]
Hi,

The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forum](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the programming questions forum is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by magewn** [comment]
Hi,

Have you got the solution for this because I am facing the same issue, I am taking offline payment examples and Its not showing on checkout payment page.

Thanks
