### ISSUE TITLE
Update `phpunit/phpunit` composer dependency to version ^9.3 (STAGE 1)

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#33707]
This issue is a STAGE 1 of the magento/magento2#33596.
We need to upgrade `phpunit/phpunit` to the version ^9.3 with fixes of the codebase of the Magento tests.

### Related issue (*)
1. magento/magento2#33596 - parent issue
2. magento/magento2#33708 - STAGE 2
3. magento/magento2#33709 - STAGE 3

**Comment by bohdan-harniuk** [comment]
This issue should stay open till all related PRs merged.
