### ISSUE TITLE
Can't login into backend - Magento 2.0.2

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3372]
If I try to login into the m2 backend, nginx throws the following error.

```
2016/02/11 13:35:44 [error] 9#9: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Notice: session_write_close(): &quot;_underscoreCache&quot; returned as member variable from __sleep() but does not exist in /var/www/html/vendor/magento/framework/Session/SessionManager.php on line 139 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8, 'session_write_c...', '/var/www/html/v...', 139, Array)
#1 /var/www/html/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
#2 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
#3 {main}
  thrown in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61" while reading response header from upstream, client: 172.20.0.1, server: , request: "POST /index.php/management/admin/index/index/key/38d071a516bea51d08643a4f2945da0615b9e5d5d54b2678e0fd5afba5f65861/ HTTP/1.1", upstream: "fastcgi://172.20.0.10:9000", host: "magento2-dev.io", referrer: "https://magento2-dev.io/index.php/management/admin/index/index/key/38d071a516bea51d08643a4f2945da0615b9e5d5d54b2678e0fd5afba5f65861/"
```

I'm using the m2 nginx settings and uses php 7.0.3.

The php process is running als www-data user and this user is owner of `var/sessions`.

**Comment by mazhalai** [comment]
What is value of `session.save-path` in php.ini? is it accessible for the nginx user?

**Comment by marvincaspar** [comment]
`session.save_path = ""`
I also tried an other path but both doesn't work.

It worked before updating to v2.0.2 and session files are created in `var/sessions`.

**Comment by marvincaspar** [comment]
This issue is triggered by a custum module which intercepts the error_handler #3387

**Comment by marvincaspar** [comment]
#3405

**Comment by magebay99** [comment]
You can try recover your password via email or phpmyadmin. 
`UPDATE admin_user SET password = CONCAT(SHA2('xxxxxNewPassword', 256), ':xxxxx:1') WHERE username = 'admin';`
See more detail on: https://bestcodestore.com/magento-2-admin-cant-login-backend/

**Comment by NandoSantana** [comment]
I have the same issue, after installed banner plugin in command line 
`php bin/magento module:enable WeltPixel_Backend --clear-static-content
php bin/magento module:enable WeltPixel_OwlCarouselSlider --clear-static-content
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f`

i did changed path to session but, didnt resolved.
