### ISSUE TITLE
i am not getting ouath Token (Response : 400 Bad request

### ISSUE THREAD

**Issue by UppalaBasava** [magento/magento2#33720]
### Summary (*)
I am not getting oauth Token , i am getting bad Request , can you please suggest me how to Resolve this issue.

### Examples (*)
url: https://www.dme-medical.com/rest/v1/Integration/admin/Token

-- DELETED ---

Response:
400 Bad Request

### Proposed solution
please suggest me how to resolve this issue.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nuzil** [comment]
Hi  @UppalaBasava 

1) Please never paste your Login/Password into Issue description, somebody can get a full access to your system.

2) I assume its Upper/Lower case issue:
This this call:

curl --location --request POST 'https://www.dme-medical.com/rest/V1/integration/admin/token' \
--header 'Content-Type: application/json' \
--data-raw '{"username":"USERNAME", "password":"PASSWORD"}'
