### ISSUE TITLE
'Billing & Shipping address the same' checkbox is empty

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#33725]
### Preconditions (*)

1. Clean installation of "magento/product-community-edition": "2.4.2"

### Steps to reproduce (*)

1. Add some product to cart
2. Go to checkout
3. Fill shipping address by Chrome autocomplete
4. Click 'Next' to go to next step **BEFORE** shipping methods block is reloaded (recalculated)

See reproducing here https://youtu.be/-lW947TCD7k

### Expected result (*)

1. 'My billing and shipping address are the same' checkbox is checked by default

### Actual result (*)

1. 'My billing and shipping address are the same' checkbox is not checked by default

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MyroslavDobra** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43026` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by maghamed** [comment]
@magento give me 2.4-develop instance

**Comment by NipulThoriya572** [comment]
@magento I am working on this

**Comment by NipulThoriya572** [comment]
@magento add to contributors team

**Comment by NipulThoriya572** [comment]
@magento give me test instance

**Comment by NipulThoriya572** [comment]
@magento give me 2.4-develop instance

**Comment by NipulThoriya572** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Let's increase priority to P2 as this is an additional step that customers should do on checkout (check the "my billing and shipping address the same" checkbox), which reduces the conversion rate.

**Comment by rostilos** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Reconfirming this issue for creating JIRA
