### ISSUE TITLE
Unable to generate invoices "/var/www/html/var/log/test.log" cannot be opened with mode "a"

### ISSUE THREAD

**Issue by marinalovatooo** [magento/magento2#33739]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by leebellabarista** [comment]
Pretty sure this will be a server permissions error and not a Magento bug.

**Comment by marinalovatooo** [comment]
> Pretty sure this will be a server permissions error and not a Magento bug.

Thank you for your reply! Do you know who should I contact to get it fixed?

**Comment by hostep** [comment]
Try your hosting provider. Or the person that setup your Magento installation.

**Comment by nuzil** [comment]
Thats not really a Magento issue, please contact your hosting provider for that.
