### ISSUE TITLE
Error on dashboard login: Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by alitopaloglu** [magento/magento2#33749]
### Preconditions (*)

1. v2.4.3

### Steps to reproduce (*)

1. Install magento v2.4.3 by using composer
2. Go to /admin_XXXXXX which is a unique admin url that generated by magento 
3. Login with your admin credentials 

### Expected result (*)

1. If login successful, it should show dashboard without any error

### Actual result (*)

1. Dashboard loads with an error -> Invalid security or form key. Please refresh the page. 
2. [https://www.dropbox.com/s/i5c3epqcuh5mhjw/Screen%20Shot%202021-08-11%20at%2014.42.11.png?dl=0](https://www.dropbox.com/s/i5c3epqcuh5mhjw/Screen%20Shot%202021-08-11%20at%2014.42.11.png?dl=0)

#### Network section of browser, filtered by doc

1. /admin_XXXXXX POST 302 found
2. /admin_XXXXXX/admin_XXXXXX/index/index/key/XXXXXX/ GET 302 found
3. /admin_XXXXXX/admin/dashboard/index/key/XXXXXX/ GET 200 OK

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by groomershop-mt** [comment]
No, this is not the same issue. After exceeding session size (solving issue #33748), the warning is still being diplayed:

Invalid security or form key. Please refresh the page.

**Comment by achatpc** [comment]
@magento give me 2.4-develop instance

**Comment by jorgb90** [comment]
> No, this is not the same issue. After exceeding session size (solving issue #33748), the warning is still being diplayed:
> 
> Invalid security or form key. Please refresh the page.

Mm for me it went away after exceeding the session size (I disabled it with "0").

**Comment by devchris79** [comment]
We also see this, the error appears on first entry to the admin panel but after a page refresh or navigating away from the initial screen it disappears.

**Comment by oriolauge** [comment]
Hi, I see the same error after upgrade my magento 2.4.2-p1 to 2.4.3. The error happens after admin login as @devchris79 said

**Comment by Thundar** [comment]
I had the same error on upgrading from 2.4.2-p1 to 2.4.3.
Solved with the following queries, as default values are too strict and I couldn't modify them from admin panel, before setting them higher.
`insert into core_config_data set scope="default", scope_id=0, path="system/security/max_session_size_admin", value=NULL;
insert into core_config_data set scope="default", scope_id=0, path="system/security/max_session_size_storefront", value="512000";`

**Comment by TheRealHunzik** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4.3 version after upgrading from 2.4.2-p1 to 2.4.3 and the issue is reproducible:
**Steps to reproduce:**
 Upgrade Magento version from 2.4.2-p1 to 2.4.3
Login to Magento Admin using admin credentials
Issue: Invalid security or form key. Please refresh the page. Error message is getting displayed on Admin Dashboard
User have to refresh the page to remove the error message
Logout and Login again - Issue: Above error message is displayed always after every login 
![image](https://user-images.githubusercontent.com/60198231/129342485-f0e2ca01-f906-444a-991e-173e84b66048.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43085` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chrisbadley** [comment]
> Verified the issue on Magento 2.4.3 version after upgrading from 2.4.2-p1 to 2.4.3 and the issue is reproducible:
> **Steps to reproduce:**
> Upgrade Magento version from 2.4.2-p1 to 2.4.3
> Login to Magento Admin using admin credentials
> Issue: Invalid security or form key. Please refresh the page. Error message is getting displayed on Admin Dashboard
> User have to refresh the page to remove the error message
> Logout and Login again - Issue: Above error message is displayed always after every login
> ![image](https://user-images.githubusercontent.com/60198231/129342485-f0e2ca01-f906-444a-991e-173e84b66048.png)

Not isolated to upgrading from 2.4.2-p1 to 2.4.3. This has also occured for me when upgrading from 2.3.6 P-1

**Comment by JKair** [comment]
I meet this issues,too.
When I upgrade 2.4.2 --> 2.4.3.

**Comment by WebHostingAce** [comment]
Same issue. Fresh Installation of 2.4.3

**Comment by mrtuvn** [comment]
Not only 2.4.3. I see this issue sometimes after login to admin from version 2.3.3

**Comment by birdman002** [comment]
When we upgraded to 2.4.3 this also happened. Put in a ticket from support they said they couldnt replicate it. Nice to see others are having the same issue

**Comment by DinkoIlicic** [comment]
This is happening on 2.4.2-p2 as well. The issue seems to be tied to https://github.com/magento/magento2/compare/2.4.2-p1...2.4.2-p2#diff-b2a114335ec9a934a79cf70838fa7920ef5beb6f588fa353b58561c18ddceacbR229

$baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
This function is returning an empty string instead of the base URL because PHP_URL_PATH is specified instead of PHP_URL_HOST

This causes the $requestUri to have the wrong value for admin login

**Comment by DinkoIlicic** [comment]
The issue seems to be tied to the following change https://github.com/magento/magento2/compare/2.4.2-p1...2.4.2-p2#diff-b2a114335ec9a934a79cf70838fa7920ef5beb6f588fa353b58561c18ddceacbR229

$baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
This is returning an empty string, which then creates the wrong admin login requestUri.

**Comment by anvanza** [comment]
I might have found an actual issue (besides the annoying red message).

In the admin go to Categories and Select a category, in the "content" tab, click on "select from gallery", click any folder and upload an image there.
![Screenshot 2021-08-20 at 12 28 17](https://user-images.githubusercontent.com/2848347/130220236-c2e7045b-582e-4810-a6aa-d47fecdb4caf.png)
![Screenshot 2021-08-20 at 12 28 24](https://user-images.githubusercontent.com/2848347/130220258-be3d06e0-ed66-454d-886c-d5f8447d8c8d.png)

My client got the error below:
![Screenshot 2021-08-20 at 12 23 34](https://user-images.githubusercontent.com/2848347/130219763-a7e9f8e6-deff-48b9-9988-58a4295f9f3b.png)

At first it seemed unrelated, **but**, it tries to get the path from the session and the path is always null.
[Upload:L58](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/Upload.php#L58)

When I tried the fix from @Thundar https://github.com/magento/magento2/issues/33749#issuecomment-897413643
It started working.

Could any of you try to verify this on your environments?

**Comment by mrtuvn** [comment]
image path seem not related with this issue. Maybe something else from another component

**Comment by mrtuvn** [comment]
@DinkoIlicic https://github.com/magento/magento2/pull/32099 changes made here

**Comment by Teup407** [comment]
> > Verified the issue on Magento 2.4.3 version after upgrading from 2.4.2-p1 to 2.4.3 and the issue is reproducible:
> > **Steps to reproduce:**
> > Upgrade Magento version from 2.4.2-p1 to 2.4.3
> > Login to Magento Admin using admin credentials
> > Issue: Invalid security or form key. Please refresh the page. Error message is getting displayed on Admin Dashboard
> > User have to refresh the page to remove the error message
> > Logout and Login again - Issue: Above error message is displayed always after every login
> > ![image](https://user-images.githubusercontent.com/60198231/129342485-f0e2ca01-f906-444a-991e-173e84b66048.png)
> 
> Not isolated to upgrading from 2.4.2-p1 to 2.4.3. This has also occured for me when upgrading from 2.3.6 P-1

I had the same issue and found that after I found "report.WARNING: Session size of 400723 exceeded allowed session max size of 256000. "  this in the debug log and then found the new setting in the admin under stores->system->configuration->advanced->system  security and changed that setting cleared cache and now it works fine..  caused by my admin front_name being anything other than admin.

**Comment by mrtuvn** [comment]
Not only happen in 2.4.3. Reproduced in 2.3.3
![sessions](https://user-images.githubusercontent.com/1908873/130312231-29dc740e-29f5-48ac-a260-e9c372efc09d.png)
Some sensitive parts already hidden

site running (No-single-store) I have setup multiple store

**Comment by mugua** [comment]
> @DinkoIlicic it seems that the idea of these changes was to redirect to the page an admin user was trying to open. So i gave it another take:
> 
> * I check for the existence of the frontname to determine the requestParts
> * I get the current params and unset key and form_key from them
> * Pass the correct requestParts and params into the getUrl function
> 
> ```
> diff --git a/App/Action/Plugin/Authentication.php b/App/Action/Plugin/Authentication.php
> index 8227966..19795a5 100644
> --- a/App/Action/Plugin/Authentication.php
> +++ b/App/Action/Plugin/Authentication.php
> @@ -225,13 +225,24 @@ class Authentication
>  
>          // Checks, whether secret key is required for admin access or request uri is explicitly set
>          if ($this->_url->useSecretKey()) {
> -            $requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
> -            $baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
> -            $routeIndex = empty($baseUrlPath) ? 0 : 1;
> -            $requestUri = $this->_url->getUrl($requestParts[$routeIndex]);
> +            if (strpos(trim($request->getRequestUri(),'/'), $request->getFrontName()) === 0) {
> +                // request starts with admin router frontname, get parts 1-2-3 for redirect
> +                $requestParts = explode('/', trim($request->getRequestUri(), '/'.$request->getFrontName()), 4);
> +            } else {
> +                // request doesnt start with admin router frontname, get first three parts for redirect
> +                $requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
> +            }
> +
> +            $requestParams = $request->getParams();
> +
> +            //remove key and form key params
> +            unset($requestParams['key'],$requestParams['form_key']);
> +            
> +            $requestUri = $this->_url->getUrl(implode('/',$requestParts), $requestParams);
> +
>          } elseif ($request) {
>              $requestUri = $request->getRequestUri();
> -        }
> +        } 
>  
>          if (!$requestUri) {
>              return false;
> ```

Using the fix plugin, The first time won't show this error, but if I Logout and login again, it is also display again...

**Comment by mugua** [comment]
waitting for Magento offical to fix this bug...

**Comment by DinkoIlicic** [comment]
@mugua @basvanpoppel I have made a small change that resolved the issue that mugua has. It happens because the trim function does not properly trim '/frontName/admin' which we get after logout. Here is the change:

```
diff --git a/App/Action/Plugin/Authentication.php b/App/Action/Plugin/Authentication.php
index 8227966..0052ee3 100644
--- a/App/Action/Plugin/Authentication.php
+++ b/App/Action/Plugin/Authentication.php
@@ -225,10 +225,15 @@ class Authentication
 
         // Checks, whether secret key is required for admin access or request uri is explicitly set
         if ($this->_url->useSecretKey()) {
-            $requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
-            $baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
-            $routeIndex = empty($baseUrlPath) ? 0 : 1;
-            $requestUri = $this->_url->getUrl($requestParts[$routeIndex]);
+            $requestParts = strpos(trim($request->getRequestUri(),'/'), $request->getFrontName()) === 0 ?
+                explode('/', trim($request->getRequestUri(), '/'), 4) :
+                explode('/', trim($request->getRequestUri(), '/'), 3);
+            if (($key = array_search($request->getFrontName(), $requestParts)) !== false) {
+                unset($requestParts[$key]);
+            }
+            $requestParams = $request->getParams();
+            unset($requestParams['key'], $requestParams['form_key']);
+            $requestUri = $this->_url->getUrl(implode('/', $requestParts), $requestParams);
         } elseif ($request) {
             $requestUri = $request->getRequestUri();
         }
```

**Comment by mugua** [comment]
> @mugua @basvanpoppel I have made a small change that resolved the issue that mugua has. It happens because the trim function does not properly trim '/frontName/admin' which we get after logout. Here is the change:
> 
> ```
> diff --git a/App/Action/Plugin/Authentication.php b/App/Action/Plugin/Authentication.php
> index 8227966..0052ee3 100644
> --- a/App/Action/Plugin/Authentication.php
> +++ b/App/Action/Plugin/Authentication.php
> @@ -225,10 +225,15 @@ class Authentication
>  
>          // Checks, whether secret key is required for admin access or request uri is explicitly set
>          if ($this->_url->useSecretKey()) {
> -            $requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
> -            $baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
> -            $routeIndex = empty($baseUrlPath) ? 0 : 1;
> -            $requestUri = $this->_url->getUrl($requestParts[$routeIndex]);
> +            $requestParts = strpos(trim($request->getRequestUri(),'/'), $request->getFrontName()) === 0 ?
> +                explode('/', trim($request->getRequestUri(), '/'), 4) :
> +                explode('/', trim($request->getRequestUri(), '/'), 3);
> +            if (($key = array_search($request->getFrontName(), $requestParts)) !== false) {
> +                unset($requestParts[$key]);
> +            }
> +            $requestParams = $request->getParams();
> +            unset($requestParams['key'], $requestParams['form_key']);
> +            $requestUri = $this->_url->getUrl(implode('/', $requestParts), $requestParams);
>          } elseif ($request) {
>              $requestUri = $request->getRequestUri();
>          }
> ```

Yeah, It is fine now, Thanks.

**Comment by amcguireweb** [comment]
> @mugua @basvanpoppel I have made a small change that resolved the issue that mugua has. It happens because the trim function does not properly trim '/frontName/admin' which we get after logout. Here is the change:
> 
> ```
> diff --git a/App/Action/Plugin/Authentication.php b/App/Action/Plugin/Authentication.php
> index 8227966..0052ee3 100644
> --- a/App/Action/Plugin/Authentication.php
> +++ b/App/Action/Plugin/Authentication.php
> @@ -225,10 +225,15 @@ class Authentication
>  
>          // Checks, whether secret key is required for admin access or request uri is explicitly set
>          if ($this->_url->useSecretKey()) {
> -            $requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
> -            $baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
> -            $routeIndex = empty($baseUrlPath) ? 0 : 1;
> -            $requestUri = $this->_url->getUrl($requestParts[$routeIndex]);
> +            $requestParts = strpos(trim($request->getRequestUri(),'/'), $request->getFrontName()) === 0 ?
> +                explode('/', trim($request->getRequestUri(), '/'), 4) :
> +                explode('/', trim($request->getRequestUri(), '/'), 3);
> +            if (($key = array_search($request->getFrontName(), $requestParts)) !== false) {
> +                unset($requestParts[$key]);
> +            }
> +            $requestParams = $request->getParams();
> +            unset($requestParams['key'], $requestParams['form_key']);
> +            $requestUri = $this->_url->getUrl(implode('/', $requestParts), $requestParams);
>          } elseif ($request) {
>              $requestUri = $request->getRequestUri();
>          }
> ```

This seems to resolve the error message if you are not using **Magento_TwoFactorAuth**, but if I enable that module, I observe the same behavior as prior to applying this patch. The authentication form page simply refreshes, the field is cleared, and the admin user is unable to log in and prompted to reenter a Google Authenticator code.

Any ideas as to why this happens when **Magento_TwoFactorAuth** is enabled?

**Comment by leonhelmus** [comment]
I have the same issue with some clients that are going from 2.4.2-1 to 2.4.3.

**Comment by davordragic** [comment]
Same issue with from 2.4.2-p1 to 2.4.3

**Comment by bvkl** [comment]
@magento give me 2.4-develop instance

**Comment by pemann** [comment]
This seems to be fixed to 2.4-development in this commit: [3d262f88824c7acbf23f3c520078377bc8129c9f](https://github.com/magento/magento2/commit/3d262f88824c7acbf23f3c520078377bc8129c9f)

**Comment by emiliatereanu** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@sidolov I believe we can close this issue with upcoming release version where will be available fix https://github.com/magento/magento2/commit/3d262f88824c7acbf23f3c520078377bc8129c9f

**Comment by drinkingsouls** [comment]
I'm experiencing this issue since upgrading to 2.4.3
Is commenting out the following in Authentication.php currently the best way around this?

```
$requestParts = explode('/', trim($request->getRequestUri(), '/'), 3);
            $baseUrlPath = trim(parse_url($this->backendUrl->getBaseUrl(), PHP_URL_PATH), '/');
            $routeIndex = empty($baseUrlPath) ? 0 : 1;
            $requestUri = $this->_url->getUrl($requestParts[$routeIndex]);
```

**Comment by birdman002** [comment]
> Is Patch Available for Magento Commerce Cloud ?

Yes it is email your account manager

**Comment by hostep** [comment]
Official fix was already [linked above](https://github.com/magento/magento2/issues/33749#issuecomment-1002349475), but that was only one commit out of 3 in total, here's the merge commit which should contain the full fix: https://github.com/magento/magento2/commit/a7d1290d7fed9e37f000642120cedc7f94cebcc3

**Comment by scolandrea** [comment]
I just installed a fresh 2.4.4, and the issue is still reproducible.

**Comment by ihor-sviziev** [comment]
@scolandrea you can apply the changes from this comment as a patch https://github.com/magento/magento2/issues/33749#issuecomment-1028410426

**Comment by erfanimani** [comment]
@scolandrea If you've included the Magento Quality Patches Tool in your project, you can simply run `vendor/bin/magento-patches apply MDVA-40311`.

I believe the strategy is that, moving forward, a lot of these type of fixes are not included into patch releases.

**Comment by pixel-paul** [comment]
> I believe the strategy is that, moving forward, a lot of these type of fixes are not included into patch releases.

There are currently 21 patches available for 2.4.4 - should they all be applied? Or does that consitute a 'large number'?

![Screenshot 2022-04-13 at 09-45-30 Quality Patches Tool Adobe Commerce Developer Guide](https://user-images.githubusercontent.com/389303/163138195-2cb6c7b1-06b4-48bb-b16e-9d04232a89f8.png)

**Comment by heerdt** [comment]
Upgraded from 2.4.2 to 2.4.4, never had the issue and after the upgrade I can't login into the admin dashboard, debugging I found the same error: Invalid Form Key. Please refresh the page.

**Comment by simonmaass** [comment]
not sure why this is closed...

**Comment by Copxer** [comment]
Hi, Upgraded from 2.4.2 to 2.4.4, now I can't login into the admin dashboard. 
 - No  errors compiling.
 - No Logs.
 Everytime I try to login loop me back to the sign in page.  Anyone know how to fix this issue?

**Comment by drinkingsouls** [comment]
@Copxer I have experienced this also. Just refreshes the login page with no errors.
For me the solution was increasing the admin session lifetime.

Command line:
bin/magento config:set admin/security/session_lifetime 10800

Or change in database:
INSERT INTO core_config_data(path, value) VALUES('admin/security/session_lifetime', 10800);

**Comment by LucasVollebergh** [comment]
I had this issue only on accounts without admin rights. 
What helped me solve this issue was setting the **User Role permissions** of the 2FA module checked. 
![image](https://user-images.githubusercontent.com/13552277/181249705-a46b1f7b-d0b6-4218-8e9b-7bf0fb8b02dd.png)

**Comment by drinkingsouls** [comment]
> 

I believe you need both of these enabled for User Roles to work with 2FA correctly:

Stores > Settings > Configuration >Two Factor Auth
System > Permissions > Two Factor Auth
