### ISSUE TITLE
ext-sodium requirement for 2.4.3 missing in system requirements and backwards incompatibility not mentioned in release notes

### ISSUE THREAD

**Issue by Morgy93** [magento/magento2#33743]
```
magento/product-community-edition 2.4.3 requires web-token/jwt-framework ^v2.2.7

web-token/jwt-framework v2.2.10 requires ext-sodium *
```

But `ext-sodium` is not mentioned here: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

![image](https://user-images.githubusercontent.com/7961978/128995496-726da9df-4d30-4d48-809e-76b8d6923899.png)

Also it is not mentioned on the release notes: https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html

I have no clue if this backwards incompatibility is just not mentioned or "wrong" in this version.

Maybe someone can clear things up?

**Comment by hostep** [comment]
The devdocs team is working on improving a script to automatically determine the php extensions a Magento shop requires: https://github.com/magento/devdocs/issues/7960

Once they are done with this, you should find the `sodium` extension as part of the required extensions on devdocs.

It strongly recommended to use the sodium extension anyway to profit from improved password hashing security which got introduced in Magento 2.3.2 I seem to remember.

**Comment by Morgy93** [comment]
Luckily this was just missing for the latest https://github.com/magento/magento-cloud-docker 7.2-cli-1.2.4 on my end.

I'll leave this open for the docs to original Magento and will open up another issue for the docker image.

**Comment by hostep** [comment]
Hi @Morgy93: https://github.com/magento/devdocs/issues/7960 was solved today and now `ext-sodium` is documented as a required extension on https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

I believe we can close this issue now?

**Comment by engcom-Bravo** [comment]
Issue closed by reporter.
