### ISSUE TITLE
Backorder (qty backordered recorded in database for order) is broken on multi source/stock systems.

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#33756]
### Preconditions (*)

1.Magento 2.4.3

### Steps to reproduce (*)

1. Create Test Stock
2. Create Test Source
3. Assign Default Website to Test Stock and assign Test Source
4. Create Test Product, allow backorders with notify, In Stock. Default Source Qty = 10, Test Source Qty = 0
5. Frontend, Add to cart test Product. Observe the backorder warning on checkout indicating product is coming from test source.
6. Place Order
7. View order in Admin and check backorder status

### Expected result (*)

1. The order should show Qty 1 Backordered.

### Actual result (*)

1. It does not. It just shows 1 Ordered, not Backordered.

If you now go in and change the Qty in Default Source to 0 and repeat the process it will show Backordered. The backorder info that is stored in the database for the order item is ALWAYS taken from the default source, not the source assigned to the order item.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43064` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by onlinebizsoft** [comment]
@krishprakash label as Reported on 2.4.3 please

**Comment by gwharton** [comment]
Original issue reported last year
Fixes magento/inventory#3180

Also fixes this issue
Fixes magento/inventory#3181

Old Pull Requests that fix all the above issues, that I got bored of waiting to get traction. Probably because they require simultaneous updates to both core and inventory.
https://github.com/magento/magento2/pull/29881
https://github.com/magento/inventory/pull/3182

Someone else will need to take this forward as contributing has gotten too difficult recently.

Workaround is to only use the Default Source/Stock for products that can be backordered.

**Comment by engcom-Alfa** [comment]
Hi @gwharton ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest 2.4-develop to retest the case.

In case of any Magento related issues found in 2.4-develop, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by gwharton** [comment]
Unless there are additional commits in MSI, this will remain broken. This is a problem when using multiple source/stocks on MSI.

**Comment by gwharton** [comment]
Create test product, test stock and test source.

Assign test product to test source and set stock to 10. Set stock to 5 in default source. 

Purchase test product on website linked to test source.

Backorder should be 10. It is not, it will be 15 as it always uses default stock for backorder calcs.

**Comment by gwharton** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by gwharton** [comment]
@magento give me 2.4-develop instance
