### ISSUE TITLE
WEBAPI: Missing shipping method detail in salesOrderRepositoryV1 GET response

### ISSUE THREAD

**Issue by karanbhomiagit** [magento/magento2#3375]
When I am making a GET call to the salesOrderRepositoryV1 REST API, the response json does not have "shipping_method" field in it.

API : 
GET /V1/orders/{id}
GET /V1/orders

**Comment by pboisvert** [comment]
@mbrinton01 do we have this captured in the backlog?

**Comment by mbrinton01** [comment]
@karanbhomiagit we have a shipping method in that API under:

```
"shippingAssignments": [
      {
        "shipping": {
          ...
          "method": "string"
```

Does this work for you?

**Comment by NadiyaS** [comment]
this issue is a duplicate of #2628 and had been fixed already.  
Shipping data is transmitted to extension attributes.
