### ISSUE TITLE
What the hell is happening here?

### ISSUE THREAD

**Issue by chequille** [magento/magento2#33758]
I've been waiting for this update for over 6 months now so that I can finally get started on my VServer with Magento 2.4. But the Update to 2.4.3 does not fix my main problem. As before, a product is only shown as not in stock in the frontend when all orders have been processed and stock quantity is 0. So it is still not the salable quantity that is used but the quantity in the warehouse. Accordingly, the swatches for configurable products are still not crossed out and can be selected.
Unfortunately, this is very frustrating.
In addition, some errors were added during the update, as the entries in Github show.
In the end, this means that I still can't switch to 2.4 and my VServer is still useless and only costs money.
What do you intend to do to finally get a usable 2.4?
Regards
Chequille

**Comment by jorgb90** [comment]
Just disable MSI modules and its working fine? Dont like MSI at all.. bad replacement at the moment.

**Comment by chequille** [comment]
Hi jorgb90,
I tried this now to disable all Magento/Inventory modules and on frontend it is working regarding out of stock and crossed swatches etc.
Infortunately, in backend, i cannot edit a product, as it is throwing an error because of missing InventoryApi

Do I have to set something else in the config?
Could you tell me the steps which I would have to do to get it working without Inventory modules?
Best regards,
Jürgen

**Comment by nuzil** [comment]
Hi @chequille 
did you try to report an issue with detailed problem explanation? 
Cause based on your description its impossible to reproduce it normally.
Issue creation may support in defining correct priority and fixing it ASAP

**Comment by chequille** [comment]
@nuzil

Yes I did long time ago as it is part of ticket #31117 which seems to be solved for simple products.
But configurable products do show the swatches not crossed out or grayed if the according product does have a salable quantity of 0.
There are as well other tickets claiming this: #32924
And the most frustrating is, that it is working in Magento 2.3.x !?!?!?!?!?!?!?!?!?!

Nobody cares as I believe.
Regards,
Chequille

**Comment by chequille** [comment]
@nuzil
I made now again a new ticket describing the bug.
#33799

**Comment by engcom-Echo** [comment]
Hi @chequille , 
It seems you have created a new ticket ([https://github.com/magento/magento2/issues/33758](url)), with detailed description & steps to reproduce the issue. Hence we are closing this ticket.
Thank you.

**Comment by jorgb90** [comment]
@chequille Sorry I missed your question completely! I disabled the following modules to get everything working without MSI:

Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleImportExport
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryBundleProductIndexer
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogFrontendUi
Magento_InventoryCatalogSearch
Magento_InventoryCatalogSearchBundleProduct
Magento_InventoryCatalogSearchConfigurableProduct
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventorySourceSelectionApi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupGraphQl
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryQuoteGraphQl
Magento_InventoryRequisitionList
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_CatalogInventoryGraphQl
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventoryShippingAdminUi
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventoryInStorePickupFrontend
Magento_InventorySwatchesFrontendUi
Magento_InventoryVisualMerchandiser
Magento_InventoryWishlist
Magento_InventoryInStorePickupMultishipping
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryInStorePickupSalesAdminUi
Magento_InventoryGraphQl
Magento_InventoryConfigurableProductFrontendUi
Magento_InventoryInStorePickupWebapiExtension
