### ISSUE TITLE
404 erroe after typing wrong password and replace to correct one

### ISSUE THREAD

**Issue by b-juszczyk** [magento/magento2#33752]
### Preconditions (*)

1. Magento: 2.4.2-p1
2. PHP: 7.4

### Steps to reproduce (*)

1. Type wrong password for user
2. Try to login
3. Change password to correct
4. Try to login

### Expected result (*)

1. Customer is logged in and redirect to "My Account"

### Actual result (*)

1. Customer is logged in and 404 page is showed with path /customer/account/loginPost

**Comment by darvin55** [comment]
@magento give me 2.4-develop instance
