### ISSUE TITLE
Magento Update 2.4.2 > 2.4.3 - User Deprecated Functionality: Class Laminas\Hydrator\Reflection is deprecated, please use Laminas\Hydrator\ReflectionHydrator instead in magento/vendor/laminas/laminas-hydrator/src/Reflection.php on line 17

### ISSUE THREAD

**Issue by in-session** [magento/magento2#33751]
After update from 2.4.2 to Magento 2.4.3 we get an error when running setup:di:compile

![image](https://user-images.githubusercontent.com/16542619/129044935-2a8ae808-7bf5-4ea2-be49-9c3b0b21300e.png)

```
composer require magento/product-community-edition 2.4.3
composer update -W
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy de_DE en_US -f
```

**Comment by hostep** [comment]
@in-session: a vanilla Magento OS 2.4.3 project contains the following Laminas modules:
```
$ composer2 show laminas/*
laminas/laminas-captcha
laminas/laminas-code
laminas/laminas-config
laminas/laminas-crypt
laminas/laminas-db
laminas/laminas-dependency-plugin
laminas/laminas-di
laminas/laminas-escaper
laminas/laminas-eventmanager
laminas/laminas-feed
laminas/laminas-filter
laminas/laminas-http
laminas/laminas-i18n
laminas/laminas-json
laminas/laminas-loader
laminas/laminas-mail
laminas/laminas-math
laminas/laminas-mime
laminas/laminas-modulemanager
laminas/laminas-mvc
laminas/laminas-router
laminas/laminas-server
laminas/laminas-servicemanager
laminas/laminas-session
laminas/laminas-soap
laminas/laminas-stdlib
laminas/laminas-text
laminas/laminas-uri
laminas/laminas-validator
laminas/laminas-view
laminas/laminas-zendframework-bridge
```

Notice that the Hydrator component is not part of this. So I'd assume this one got installed by some customisation done to the shop, you should be able to figure out how it gets installed by running:
```
$ composer depends laminas/laminas-hydrator
```

After that hopefully you can try to figure out how to solve this by looking at the customisation that brought in this dependency.

**Comment by mrtuvn** [comment]
interesting that you used composer update -W mean updated with all dependencies too. Maybe require with laminas hydrator. Maybe broken from 3rd-package

**Comment by YiffyToys** [comment]
laminas/laminas-hydrator replaces Zend/hydrator but (with the latest version) the class Reflection  is not/no longer 100% compatible with the Reflection class of Zend/hydrator that it replaces-
Some 3rd party modules depend on  Zend/hydrator

**Comment by in-session** [comment]
Thanks for the info, have found the problem and indeed comes from a module: dhl/shipping-m2

![Ashampoo_Snap_Donnerstag, 12  August 2021_07h58m13s_001_](https://user-images.githubusercontent.com/16542619/129171277-3d864a78-2208-454d-8053-532f65b48095.png)
![Ashampoo_Snap_Donnerstag, 12  August 2021_10h57m52s_002_](https://user-images.githubusercontent.com/16542619/129171286-f721b064-de46-45ce-b683-e992894cfe77.png)

**Comment by YiffyToys** [comment]
> Thanks for the info, have found the problem and indeed comes from a module: dhl/shipping-m2

For the record (and anyone arriving here due to the error message):
Same issue exists in GLS shipping. I already created a ticket there and linked the  dhl/shipping-m2 issue.

**Comment by in-session** [comment]
@YiffyToys well noted thanks

As I have seen is already a patch proposal published, I just tested it and runs now:

https://github.com/netresearch/dhl-module-carrier-paket/issues/3
