### ISSUE TITLE
Upgrade to 2.4.3 - Unable to apply data patch Magento\Paypal\Setup\Patch\Data\UpdateBmltoPayLater

### ISSUE THREAD

**Issue by EmperorKonstantin** [magento/magento2#33757]
### Preconditions (*)

1. Magento 2.4.2
2. PHP 7.4

### Steps to reproduce (*)

1. Upgrade 2.4.2 to 2.4.3
2. composer update
3. bin/magento setup:upgrade

### Expected result (*)

1. bin/magento setup:upgrade
2. Finishes with: 
3. Nothing to import.

### Actual result (*)

1. bin/magento setup:upgrade
2. Unable to apply data patch Magento\Paypal\Setup\Patch\Data\UpdateBmltoPayLater for module Magento_Paypal. Original exception message: Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-paypal/Setup/Patch/Data/UpdateBmltoPayLater.php on line 138

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Duplicate of https://github.com/magento/magento2/issues/33678, hopefully the advise in there can help you further.

**Comment by EmperorKonstantin** [comment]
@hostep Worked flawlessly, thanks.

**Comment by heyepic** [comment]
@EmperorKonstantin are you able to view orders? I tried adding both of these fixes but both are resulting in logs spitting out: Payment model name is not provided in config!

Have both of these in UpdateBmltoPayLater.php:
`        foreach ($bmlSettings as $bmlPath => $bmlValue) {
            $setting = str_replace(self::BMLPATH, '', $bmlPath);
            if(strpos($setting, '_') == false) { continue; }
            $settingParts = explode('_', $setting);
            if (count($settingParts) !== 2) {
                continue;
            }            `
