### ISSUE TITLE
Product price updated using Manage Base Price API is not updating in Store front Catalog Search Results page and Admin panel

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#33767]
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)

1. Generate Admin access token using POST request:  storeurl/rest/default/V1/integration/admin/token
2. Send POST API request for sync product: storeurl/rest/V1/products/base-prices. (Update Price using below Payload):
**Payload:**
```
{
  "prices": [
    {
      "price": 85.67,
      "store_id": 1,
      "sku": "Test PRice"
    }
  ]
}
```

3. Reindex and clear cache
4. Navigate to Front-end -> Verify Price in Search Results page and Product Details page 
**Issue 1:** Price updated through API is getting updated in Front-end Product Details page only but not getting updated in Catalog Search Results page and Admin - Products page
5. Navigate to Admin - Catalog - Products - Edit same Product - Update new price say ex: 90 and save
6. Reindex and clear cache
7. Navigate to front-end - Product Details page
**Issue 2:**  New Price updated from Admin panel is not getting updated in Front-end product details page (Old value saved using API is displayed in Front-end Product Details page)
### Expected result (*)
Base price should be updated in both Search Results page, Product Details page and Admin -> Catalog - > Products page

### Actual result (*)
**Issue 1**. Price updated through API is getting updated in Front-end Product Details page only but not getting updated in Catalog Search Results page and Admin - Products page
![Admin PDP](https://user-images.githubusercontent.com/51681379/130823149-c48218f4-4bbb-4098-b341-8b1a14737bf6.png)

Updated price through API : 85.67 is updated in Product Details page only
![ProductDetailsPage](https://user-images.githubusercontent.com/51681379/130823365-693112ac-a9e4-4883-9d4c-4dd1526287cb.JPG)

![Products_Inventory](https://user-images.githubusercontent.com/51681379/130823431-2d51eb0b-5d0a-4aef-a370-97c35fb51d55.JPG)

![TestPrice_Prods](https://user-images.githubusercontent.com/51681379/130823557-b97f887f-1a5d-47cf-93eb-34bee57fb3c5.JPG)

**Issue 2:**  New Price updated from Admin panel is not getting updated in Front-end product details page (Old value saved using API is displayed in Front-end Product Details page)
![ProductsPage](https://user-images.githubusercontent.com/51681379/130823720-fc2c969d-86f1-4ed2-8833-92f5ef19972d.JPG)

![TestPrice](https://user-images.githubusercontent.com/51681379/130823803-ff24b3aa-37f3-4878-9278-fe4e340488cd.JPG)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43069` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43069` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nuzil** [comment]
Hi @engcom-November 
I have a strong feeling issue is connected with this changes:
https://github.com/magento/magento2/pull/32371

Can you please try with patch from this PR and tell if its still exists? 

Or try directly on PR test Magento instance

**Comment by engcom-November** [comment]
We are closing this issue as its not reproducible anymore on Magento 2.4-develop branch.

**Comment by engcom-November** [comment]
This issue is no more reproducible on Magento 2.4-develop instance.
