### ISSUE TITLE
Run cron in console: php bin/magento cron:run -->  [ErrorException] 

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#3377]
Hi there,

we tried to run the cron via console: "php bin/magento cron:run"

We always get this error:

 [ErrorException]  
 DOMDocument::loadXML(): XML declaration allowed only at the start of the document in Entity, line: 1

Magento 2.0.2

**Comment by mazhalai** [comment]
@andidhouse what OS/PHP version etc?

**Comment by andidhouse** [comment]
this was a bug in an extension that has been fixed. can be closed
