### ISSUE TITLE
The «Bank Transfer» payment method allows itself to be «Active» in the incorrect state: when the «Instructions» field is empty, and is silently hidden on the checkout scheen, confising store owners

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3378]

**Comment by davidalger** [comment]
@dfediuk Please stop posting self-promoting links to your site, and post real contributions just like everyone else, or stop posting all together. If you have bugs to report, that's great, but post them with proper details and steps to reproduce contained in the body of the github issue not on an off-site link.
