### ISSUE TITLE
Error on credit memo saving

### ISSUE THREAD

**Issue by Fel1xx** [magento/magento2#3379]
Found weird issue happening while saving a creditmemo. It seems that method register() is called for creditmemo model, but there is NO such method in a class \Magento\Sales\Model\Order\Creditmemo

Stack trace:

[2016-02-11 20:13:42] main.CRITICAL: exception 'Magento\Framework\Exception\LocalizedException' with message 'Invalid method Magento\Sales\Model\Order\Creditmemo\Interceptor::register(Array
(
)
)' in /var/www/magento2/html/vendor/magento/framework/DataObject.php:396
Stack trace:
#0 /var/www/magento2/html/var/generation/Magento/Sales/Model/Order/Creditmemo/Interceptor.php(2377): Magento\Framework\DataObject->__call('register', Array)
#1 /var/www/magento2/html/vendor/magento/module-sales/Model/Order/Payment.php(750): Magento\Sales\Model\Order\Creditmemo\Interceptor->__call('register', Array)
#2 /var/www/magento2/html/vendor/magento/module-sales/Model/Order/Payment.php(750): Magento\Sales\Model\Order\Creditmemo\Interceptor->register()
#3 /var/www/magento2/html/var/generation/Magento/Sales/Model/Order/Payment/Interceptor.php(310): Magento\Sales\Model\Order\Payment->registerRefundNotification(83.65)
#4 /var/www/magento2/html/vendor/magento/module-paypal/Model/Ipn.php(487): Magento\Sales\Model\Order\Payment\Interceptor->registerRefundNotification(83.65)
#5 /var/www/magento2/html/vendor/magento/module-paypal/Model/Ipn.php(262): Magento\Paypal\Model\Ipn->_registerPaymentRefund()
#6 /var/www/magento2/html/vendor/magento/module-paypal/Model/Ipn.php(170): Magento\Paypal\Model\Ipn->_registerTransaction()
#7 /var/www/magento2/html/vendor/magento/module-paypal/Model/Ipn.php(89): Magento\Paypal\Model\Ipn->_processOrder()
#8 /var/www/magento2/html/vendor/magento/module-paypal/Controller/Ipn/Index.php(56): Magento\Paypal\Model\Ipn->processIpnRequest()
#9 /var/www/magento2/html/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(24): Magento\Paypal\Controller\Ipn\Index->execute()
#10 /var/www/magento2/html/vendor/magento/framework/App/Action/Action.php(102): Magento\Paypal\Controller\Ipn\Index\Interceptor->execute()
#11 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#13 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callParent('dispatch', Array)
#14 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'designLoader')
#15 /var/www/magento2/html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#18 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'customer-app-ac...')
#19 /var/www/magento2/html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#20 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#22 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'contextPlugin')
#23 /var/www/magento2/html/vendor/magento/module-store/App/Action/Plugin/Context.php(98): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#26 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'storeCheck')
#27 /var/www/magento2/html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#30 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'tax-app-action-...')
#31 /var/www/magento2/html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#34 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Paypal\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'weee-app-action...')
#35 /var/www/magento2/html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Paypal\Controller\Ipn\Index\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#38 /var/www/magento2/html/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(39): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#39 /var/www/magento2/html/vendor/magento/framework/App/FrontController.php(55): Magento\Paypal\Controller\Ipn\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#40 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#42 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#43 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#44 /var/www/magento2/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#47 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#48 /var/www/magento2/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#51 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#52 /var/www/magento2/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#53 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /var/www/magento2/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#55 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#56 /var/www/magento2/html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#57 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /var/www/magento2/html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#59 /var/www/magento2/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#60 /var/www/magento2/html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#61 /var/www/magento2/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#62 /var/www/magento2/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#63 {main} [] []

**Comment by Fel1xx** [comment]
Does anyone checking this?

**Comment by stevenvdp** [comment]
We also have this problem, seems like this is not a priority for Magento...
@Fel1xx  I've found a PR where they simply remove the register() call, you could give it a try.
https://github.com/magento/magento2/pull/2656

**Comment by NadiyaS** [comment]
Hi @Fel1xx , @stevenvdp 
thank you for reporting this problem. And we are sorry that sometimes we have delay about reported issues. 
We are processing PR with fix for this problem #2656

**Comment by alena-marchenko** [comment]
Closing the issue, the fix has been delivered to develop branch.
