### ISSUE TITLE
PayPal express checkout popup not working as expected in Dual Monitor setup

### ISSUE THREAD

**Issue by mathanagopaloxsoftwares** [magento/magento2#33797]
### Summary (*)
When trigger PayPal from the second monitor in dual monitor setup, the popup goes out of the second monitor and gets itself attached to the first monitor and in a very odd way

### Examples (*)
Please refer to the bellow screenshot:
![1628915781273](https://user-images.githubusercontent.com/76041988/129434824-239417a8-c748-460c-87cb-4453fb3af911.JPEG)

### Steps to reproduce
Open a website with PayPal integrated in fresh chrome browser in monitor-2. Trigger PayPal express checkout. The popup window appears in monitor-1's right side(since the connection was made from right side port).

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by onlinebizsoft** [comment]
@mathanagopaloxsoftwares I dont think it is a Magento bug, I guess the OS remember the possition where the window would appear next time so it happened

**Comment by engcom-Lima** [comment]
Hi @mathanagopaloxsoftwares,

We are closing this issue due to the reason being not related to Magento Dev.
