### ISSUE TITLE
The store will not work correctly in the case when cookies are disabled.

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#33796]
Upon upgrading from M2.3.7 to M2.4.3 the following banner appears at the top of the page...

"The store will not work correctly in the case when cookies are disabled."

Tried all the suggestions found in the forums, and found a few people complaining specifically that it appeared upon M2.4.3 upgrade.   Does not appear in a clean 2.4.3 install, only with upgrade.  Twiddled all settings obviously related without success.  Appears no one has found a resolution for 2.4.3 upgrades.

**Comment by mrtuvn** [comment]
have you disable cookies in your browser ? Can you check config in clientside( browser preferences )

**Comment by n2diving-dgx** [comment]
Tested (with cookies enabled) in Chrome, Edge, IE, Safari, Opera.... Win10, MacOs, iOS, Android,  all the same message...

"The store will not work correctly in the case when cookies are disabled."   Yet they are enabled.  Rolling back to 2.4.2 resolves the issue.

**Comment by mrtuvn** [comment]
This message only show if you disable cookie from client-side. Is there another case do i missed

**Comment by likearocket** [comment]
I also have this issue, upgrading from 2.4.2-p1 to 2.4.3.

**Comment by n2diving-dgx** [comment]
> This message only show if you disable cookie from client-side. Is there another case do i missed

Yes this message is now showing as of M2.4.3 upon upgrade even when client side cookies are ENABLED.

**Comment by devchris79** [comment]
OK, I have fixed this now for Porto. It appears that any theme now needs to turn the message off due to MC-41474. Porto doesn't make any attempt so its always displayed.

You need to add app/design/frontend/Smartwave/porto/Magento_Theme/web/css/source/_module.less:

.cookie-status-message {
display: none;
}

I put this on line 234 for Porto

**Comment by n2diving-dgx** [comment]
To sum up discussioin from several contributors, this issue is caused by a change in M2.4.3 and how it handles the cookie status message.

https://github.com/magento/magento2/search?q=41474&type=commits

Starting with M2.4.0, but prior to M2.4.3 the cookie status message was hidden by default using a bit of inline js that was injected in the theme by /view/frontend/templates/js/cookie_status.phtml

```
<script type="text/javascript">document.querySelector("#cookie-status").style.display="none";</script>
```

but that is changed in M2.4.3 and is now hidden using a css class that was added to the M2.4.3 blank and luma themes by /web/css/source/_module.less

```
.cookie-status-message {
display: none;
}
```

The change in default behavior for M2.4.3 affects pre-existing custom themes that provide their own version of _module.less because they will not contain the additional css class needed to hide the cookie status message. The solution is to add the cookie-status-message class to _module.less of custom themes.
