### ISSUE TITLE
Removing 'Remote Shopping assistant' fails to client side validation

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#33794]
### Preconditions (*)

1. Adobe Commerce Cloud 2.4.2
2. 

### Steps to reproduce (*)

1. Disable Remote Shopping Assistant from admin Stores > Configurations > Customer > Login as Customer 
2. Make it disable

### Expected result (*)

1. It should remove checkbox on registration page - Working as expected 
2. Without filling form if we click on submit it should error message per field

### Actual result (*)

1. [Screenshots, logs or description]
2. It's reloading page and then showing error

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by VZeroCool** [comment]
So it's not reproducing in this develop instance, Can you help me with commit which fixed this issue ?

**Comment by mrtuvn** [comment]
seem fixed in 2.4-develop

**Comment by mrtuvn** [comment]
Same ticket here https://github.com/magento/magento2/issues/33597
