### ISSUE TITLE
Remove scheduled jobs after changing cron settings

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#3380]
It would be helpful if pending entries in cron_schedule are deleted when changing a cron job's config:
![screen shot 2016-02-12 at 09 46 48](https://cloud.githubusercontent.com/assets/1489129/13002324/eb5626ee-d16d-11e5-8b0e-da501f8684d5.png)

I've changed the config from 09:50:00 to 09:55:00 and then to Enabled: No.
In between changing the config settings i ran: `magento cache:clean config && magento cron:run`.
The result was this:

![screen shot 2016-02-12 at 09 50 17](https://cloud.githubusercontent.com/assets/1489129/13002336/0afff2b8-d16e-11e5-82d2-a4537ac2c2c2.png)

At the moment that the cron is turned off by config it will still run based on the cron_schedule entry:

![screen shot 2016-02-12 at 09 49 07](https://cloud.githubusercontent.com/assets/1489129/13002325/ed9b6ef0-d16d-11e5-9e89-73f0071ac7ba.png)

Here the config was off, but the cron job will still run.

AOE_Scheduler has a nice fix for this and it reschedules the job at the moment you change the configuration. It would be nice if Magento itself would at least remove the pending schedules on config change.

**Comment by AntonEvers** [comment]
@MomotenkoNatalia, @piotrekkaminski would you be open to a pull request on this issue?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Remove-scheduled-jobs-after-changing-cron-settings/idi-p/45327).

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70029
