### ISSUE TITLE
Vertex_AddressValidation breaks checkout  on billing-validation-mixin.js

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#33815]
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1.  if Vertex_AddressValidation is in system but not configured to be used from config 
2.  if this mixin is initiated or loaded before quote billing address object is initiated or filled with valid data 
2.  it is possible to replicate this by requiring billing-validation-mixin.js before billing address is set, for example requiring vendor/magento/module-checkout/view/frontend/web/js/view/billing-address.js in any component  before address data is populated or in a race condition where data is not set. 
3. mixin calls _super() , _super() defines a template , template requires <text args="currentBillingAddress().street.join(', ')"></text><br/> 
4. if data is not valid fails with `Uncaught TypeError: Unable to process binding "text: function(){return currentBillingAddress().street.join(', ') }"` . Error that breaks all further js execution on site 

### Expected result (*)

1. if Vertex_AddressValidation is in system but not configured to be used from config no  resources should be included on  frontend (https://github.com/magento/magento2/issues/15967)
2. no errors on checkout 

### Actual result (*)

1. `Uncaught TypeError: Unable to process binding "text: function(){return currentBillingAddress().street.join(', ') }"`
2. solution is either to disable this extension with `bin/magento module:disable` or disable the mixin in any requirejs-config.js file

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ * ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@magento/ext-vertex, could you take a look?

**Comment by speedupmate** [comment]
false alarm, only issue left is that its included when not configured but that is not critical 

this is what actually causes the issue and due this mixing being the first entry point I missed the details on template change

https://github.com/magento/magento2/commit/53b85cce1e95a5cfb60db6dc029e551d053e1f14#diff-e4dcdf0e20375ec650339c4cc63147ff8156a5eb9d2e82e2927d744599d157b5 

created a new issue for that
