### ISSUE TITLE
does magento 2.3.5-p2 not surpport PR country code Puerto Rico

### ISSUE THREAD

**Issue by cha80** [magento/magento2#33817]
![image](https://user-images.githubusercontent.com/56351661/129675541-d95a272a-3813-4436-9959-8bb480da5b2c.png)

**Comment by devchris79** [comment]
The screenshot is for currencies, Puerto Rico uses the United States Dollar.

**Comment by engcom-November** [comment]
Hi @cha80,
Current Magento 2.4-develop branch behavior is - "Puerto Rico" is provided as a State Option for Country "United States" and currency "US Dollar" can be used.
![image](https://user-images.githubusercontent.com/60198231/129888222-d0353a60-2140-4aaa-8e1a-6f195c28c455.png)
Kindly recheck under State Options by Selecting "United States" Country and confirm back.
Thank you.

**Comment by cha80** [comment]
> Hi @cha80,
> Current Magento 2.4-develop branch behavior is - "Puerto Rico" is provided as a State Option for Country "United States" and currency "US Dollar" can be used.
> ![image](https://user-images.githubusercontent.com/60198231/129888222-d0353a60-2140-4aaa-8e1a-6f195c28c455.png)
> Kindly recheck under State Options by Selecting "United States" Country and confirm back.
> Thank you.

thanks

**Comment by engcom-November** [comment]
Thanks for the update @cha80, we are closing this issue as your query has been resolved.
Thank you.
