### ISSUE TITLE
Static content compile time seem not correct as docs describe

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#33816]
Preconditions
2.4.3 + sample data
Production mode

Default mode (quick strategy) . In the devdocs said it's deploy quicker but it's may not true with test.
https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.html

But it's seem consume more time when compare with compact mode

![deploy-time](https://user-images.githubusercontent.com/1908873/129666485-7b6ccc32-4fea-4c65-9438-438f56eb216d.png)

usually compact mode use-case to save cloud disk space (magento claims) .  But In this mode, it will not working with relative path ( my dev experiences )

To be accurate better test with real server with some theme working for recheck
i don't have test server at the moment. Only check in local machine

Expected results
Amount time of quick strategy should have lower than compact mode

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
This has been a bug since the strategies were added in Magento 2.2.0

See this duplicated bug report that was closed incorrectly: https://github.com/magento/magento2/issues/10674 😉
