### ISSUE TITLE
Cookie acceptance still displays message in header

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#33811]
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Switch on cookie restriction mode, settings as below:
![image](https://user-images.githubusercontent.com/43850303/129553194-c77091ee-450f-4614-a3d6-08c0e7f44341.png)

### Expected result (*)

1. Message for cookies acceptance presented, upon acceptance all messages should be removed.

### Actual result (*)

1. At the top of our site we see a message "The store will not work correctly in the case when cookies are disabled." that disappeared after acceptance in version 2.4.2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chrisastley** [comment]
I have the same issue although Cookie Restriction Mode has always been disabled, but after updating from 2.4.2-p1 to 2.4.3 I have the 'The store will not work correctly in the case when cookies are disabled.' message showing although cookies/sessions are working fine.

**Comment by mrtuvn** [comment]
Seem looks same behavior with this issue https://github.com/magento/magento2/issues/33796

**Comment by mrtuvn** [comment]
Can you share screenshot and record maybe make easier to QC team can check ? I don't see any messages cookie at the top

**Comment by mrtuvn** [comment]
![cookie](https://user-images.githubusercontent.com/1908873/129572080-f708b8cf-4cf4-474e-8d71-b289ffd6742a.png)

**Comment by devchris79** [comment]
![image](https://user-images.githubusercontent.com/43850303/129575581-b251e687-d682-4a9e-9eb6-78a3525871a5.png)

**Comment by devchris79** [comment]
I think this commit has probably broken it: MC-41474

**Comment by mrtuvn** [comment]
i think your case may similar https://github.com/magento/magento2/issues/33796
but i don't know how to reproduce at the clean install 2.4.3

**Comment by chrisastley** [comment]
@devchris79 I notice you are using the Porto theme, both sites I have the issue on are also using Porto. Not sure if it's related though.

**Comment by mrtuvn** [comment]
Have you check what theme that use template cookie status ? Maybe that template override current magento template. That make that block always show

**Comment by chrisastley** [comment]
> Have you check what theme that use template cookie status ? Maybe that template override current magento template. That make that block always show
> I will assume somehow that theme still use old version with class name `cookie-status` but in latest version magento change class to `cookie-status-message`. So your old block will still visible

On a site running version 2.4.2-p1 I can see this in the source.
<script type="text/javascript">document.querySelector("#cookie-status").style.display="none";</script>

But it isn't in the source code of 2.4.3, when I look at the changes introduced in #33796 there is an added css/less rule in the base  theme Magento_Theme/web/css/source/_module.less 

The Porto theme has it's own Magento_Theme/web/css/source/_module.less file without this rule so I'm guessing this is the issue as the base one won't be loaded?

**Comment by devchris79** [comment]
OK, I have fixed this now. It appears that any theme now needs to turn the message off due to MC-41474. Porto doesn't make any attempt so its always displayed.

You need to add app/design/frontend/Smartwave/porto/Magento_Theme/web/css/source/_module.less:

.cookie-status-message {
        display: none;
    }

I put this on line 234 for Porto

**Comment by devchris79** [comment]
The message shouldn't have changed to default on though...
