### ISSUE TITLE
Offline shipping sort order error.

### ISSUE THREAD

**Issue by TandyCorp** [magento/magento2#3382]
/app/code/Magento/OfflineShipping/etc/adminhtml/system.xml

Both flatrate and freeshipping have a sort order of sortOrder="2"

Suggestion that freeshipping should be changed so that each shipping type has a unique sort order value.

In fact I would suggest that built-in shipping modules have sort orders as follows...

group id="flatrate" sortOrder="0"
group id="freeshipping" sortOrder="5"
group id="tablerate" sortOrder="10"

This allows developers of shipping extensions to target the position of their shipping module to fit in an appropriate position on the shipping methods page in admin without having to override the default system.xml file. For example if I want to create a 'Flat Rate Expedited Shipping' option I could have that appear in a logical position after the standard flatrate by setting the sort order of the module to '2'.

I think it best to enable developers to add their modules with a minimum of overriding core files.

**Comment by alena-marchenko** [comment]
Hi,

We've created internal ticket regarding this issue MAGETWO-49206

**Comment by alena-marchenko** [comment]
Hi,
We've delivered your https://github.com/magento/magento2/pull/3384  fix.
Thank you for contribution!
