### ISSUE TITLE
Magento2 Automatic group change according billing address and VIES/VAT Validation

### ISSUE THREAD

**Issue by sebek222** [magento/magento2#33821]
### Preconditions (*)

1. Magento 2.4.2-p1

### Steps to reproduce (*)

1. Adding product to cart.
2. Go to shipping address step and select address without VAT ID
3. On next step, select different billing address (create new with TAX ID)
4. Confirm order

### Expected result (*)

1. When new billing address is created, it should be included in Tax in cart based on VAT ID
2. Updated prices should be visible immediately in cart, and after order processing.

### Actual result (*)

1. New billing address exists only in local storage and new VAT ID is not validated, I can see old prices, based on default shipping address.
2. The new billing address is visible as "shipping" type, and is skipped in vat validation.
3. New billing address works only, when I set it as default billing address in customer account settings.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [* ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Thank you in advance,
Best regards,
Sebastian

**Comment by engcom-Delta** [comment]
Hi @sebek222 .

We tried to reproduce the issue on Magento 2.4 Develop but i could not able to select different addresses other than default Shipping address & Billing address while placing an order. Getting same address for Billing & Shipping.
![shippingAddresswtihoutVat](https://user-images.githubusercontent.com/51681379/130714275-2760bece-661f-421c-8fb8-645dcd9e3b02.JPG)

Hence , request to help with what were the addresses you have used for vat calculation and provide clear steps.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
