### ISSUE TITLE
API requests without storecode lead to infinity loop

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#33823]
### Preconditions (*)
1. Magento 2.4.3

### Steps to reproduce (*)
1. Create website-store-storeview structure like this
![image](https://user-images.githubusercontent.com/19759530/129723438-0c9b282a-a0b9-48b3-9c2f-2f5d794c0316.png)
The main idea to have different websites
2. Set BO->Stores->Configuration->General->Web->Url Option->Add Store Code to Urls: **Yes**
3. Run REST API request to create customer (use payload from docs: https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-create-customer.html) but using url **without** storecode (suppose you forgot that it's required)

### Expected result (*)
1. Customer is not created, 'store code is required' error is shown (or something like this)

### Actual result (*)
1. Memory size PHP error is show
![image](https://user-images.githubusercontent.com/19759530/129724202-49ff9459-ae00-480f-a184-ffd76981b5b3.png)
2. Infinity loop is happens here \Magento\Store\Model\StoreResolver::getCurrentStoreId
3. Server is broken because all resources are used by PHP process

Note: Without the store code & even with the store code we were facing the Fatal error mentioned in the issue description. However if the store code is passed as a request parameter (eg: store_id: 1) then the customer was getting created successfully

Note: I guess it could happen with all API endpoints. It's important because this little mistake can break the server.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @Dren7755 
Thanks for reporting this issue.
We are able to reproduce this issue on **2.4-develop** branch.
Steps to reproduce
1. On a fresh instance of magento 2.4-develop, create multiple stores along with its storeviews.
2. On Adminpanel navigate to **Stores**->**Configuration**->**General**->**Web**->**Url Option**
 and set **Add Store Code to Urls** to **Yes**
3. Run REST API request to **create customer** (use payload from docs: https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-create-customer.html).
Without the store code & even with the store code we were facing the Fatal error mentioned in the issue description. However if the store code is passed as a request parameter (eg: **store_id: 1**) then the customer was getting created successfully.

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by SilinMykola** [comment]
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
@magento give me 2.4-develop instance

**Comment by sidolov** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
Hi @slavvka , @sidolov ! I tried to check this issue locally and can't reproduce it. I tried to get Magento instance to check here. I can't get an instance. What do you think I should do next? Thanks!

**Comment by sdzhepa** [comment]
Hello @SilinMykola ,

The issue with Magento instances was fixed just a couple of minutes ago

**Comment by SilinMykola** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment]
The issue is not reproducible on Magento instance and can be closed.
![image](https://user-images.githubusercontent.com/15772032/152396199-47a60267-40aa-4337-9215-3426b266fac6.png)

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance
