### ISSUE TITLE
Incorrect date time in order status history.

### ISSUE THREAD

**Issue by goralgen** [magento/magento2#3383]
All comments in order status history have the same time (current time).
![image](https://cloud.githubusercontent.com/assets/15174144/13006394/6b17ae48-d191-11e5-84c2-fbbef7549d23.png)

The problem is in vendor/magento/module-sales/view/adminhtml/templates/order/comments/view.phtml (line 56,57):
Now:
$_comment->getCreatedAtDate()
Should be:
$_comment->getCreatedAt()

**Comment by goralgen** [comment]
The same problem in vendor/magento/module-sales/view/adminhtml/templates/order/view/history.phtml

**Comment by NadiyaS** [comment]
Hi @goralgen ,
thank you for reporting this issue.
This bug is already fixed in develop branch [87f27af](https://github.com/magento/magento2/commit/87f27afb8e581f47292303ac16c4685ca12e7f14).
Please update your code from develop branch or wait until next release.
