### ISSUE TITLE
Invalid Captcha

### ISSUE THREAD

**Issue by SomayaAbdo** [magento/magento2#33842]
Hello,

I changed my password account a week ago but since then I'm trying to enter my account. every time it requires a captcha and I write it but it keeps says "Invalid Captcha" I've tried to reach any support from Magento it self but non helps. I'm working with ver 2.3.1

**Comment by SomayaAbdo** [comment]
@magento-admin

**Comment by engcom-Delta** [comment]
Hi @SomayaAbdo,

Kindly provide issue description, steps to reproduce, actual results & expected results.

Thanks

**Comment by SomayaAbdo** [comment]
I don't know what you mean. I changed my account password then it should to log in with the new password but it doesn't and keeps asking me to enter the captcha which I did but it keeps says "Invalid Captcha" although I'm pretty sure I wrote it correctly.

**Comment by engcom-Delta** [comment]
Hi @SomayaAbdo,

Thanks for reverting on the issue. it would be great if you can share the screenshots of this issue.so that we can try to replicate it.

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
