### ISSUE TITLE
Admin - Load pages doesn't work - Something went wrong

### ISSUE THREAD

**Issue by chriskamps** [magento/magento2#3385]
When I go to the "Pages"-page: /cms/page/index then I get the message "Attention - Something went wrong" in a popup.

The reason is this call:

/admin_???/mui/index/render/key/[key]/?namespace=cms_page_listing
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&search%5B%5D=
&sorting%5Bfield%5D=ids
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&sorting%5Bdirection%5D%5B%5D=false
&paging%5BpageSize%5D=20
&paging%5Bcurrent%5D=1
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&filters%5Bplaceholder%5D%5B%5D=true
&isAjax=true

Very much search-, sorting%5Bdirection- and parameters: filters%5Bplaceholder. 

What is the solution to fix this?

**Comment by chriskamps** [comment]
I see also a comma in het searchbox and a active filte: Keyword: ...-...

**Comment by chriskamps** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/17198662/13008831/318c207a-d199-11e5-99ee-e6447821e281.PNG)

**Comment by jvpatel** [comment]
I have similar issue, and was able to reproduce. Were you able to address above issue? How?

[3904](https://github.com/magento/magento2/issues/3904) - https://github.com/magento/magento2/issues/3904

**Comment by andimov** [comment]
@chriskamps 
Thank you for reporting!
We already work on duplicate issue #3904 so  I'm closing this one. Please feel free to reopen if you need.
