### ISSUE TITLE
Magento 2.4.2-p2 Window10 localhost Xampp broken static content

### ISSUE THREAD

**Issue by himanshusavranntz** [magento/magento2#33857]
I am trying to setup Magento 2.4.2-p2 on local with Xampp with php7.4. Website is trying to fetch the css and js files from folder _view in place of theme like following url.

http://abc.local/static/version1629289186/frontend/_view/en_US/requirejs/require.js

so css and js files are redirecting to 404 page. Please let me know if anyone has solution to fix this issue.
![error](https://user-images.githubusercontent.com/59817631/130027631-305c142d-5e5b-48e4-8c31-7b080b098541.png)

Thanks!

**Comment by himanshusavranntz** [comment]
**Summary of the issue:**
I am trying to setup Magento 2.4.2-p2 on local with Xampp with php7.4. Website is trying to fetch the css and js files from folder _view in place of theme like following url.

http://abc.local/static/version1629289186/frontend/_view/en_US/requirejs/require.js

so css and js files are redirecting to 404 page. Please let me know if anyone has solution to fix this issue.
Information on your environment.

**Steps to reproduce:**
- I am trying to setup existing magnto2.4 on localhost. After running static-content:deploy command it's fetching static files from _view folder.

**Expected results:**
Website should fetch static files from theme.

**Actual results:**
it's fetching from folder _view.

**Comment by ihor-sviziev** [comment]
Hi @himanshusavranntz,
The windows OS isn't supported by Magento.
As a workaround, you could run Magento inside the WSL2 or using Virtualbox with Linux.
