### ISSUE TITLE
Unable to customize position of configuration attributes

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#3386]
Hi,

I followed instructions from [here](https://community.magento.com/t5/Just-Ask-Alan/Product-Configurations-Attribute-sort-order/td-p/27564) to change position of configuration options on product page but it didn't work. I think it could be a bug. `Magento 2.0.2 / PHP 7.0.2 / Production Mode`

**[Admin] 'Length' option is on top of 'Gender'**
![capture](https://cloud.githubusercontent.com/assets/11070293/13010129/f6efad08-d1d2-11e5-99c7-d0c2cb194879.PNG)
![2016-02-12_22-01-48](https://cloud.githubusercontent.com/assets/11070293/13010407/4bdec7b2-d1d4-11e5-81a5-db3d006a2e12.png)

**[Product Page] 'Length' isn't the first option.**

![2](https://cloud.githubusercontent.com/assets/11070293/13010148/08a8a874-d1d3-11e5-942d-ce16ede8eb95.PNG)

Thanks,

**Comment by Kastnerd** [comment]
I also have the same problem

**Comment by ghost** [comment]
I'm having this problem as well - What I found is that the attribute positions depend on their ID.

Lets say you create a Size attribute and then create a Color attribute. On the front end, you would want Color positioned on top of Size, however that's not the case. If you create another size attribute (just call the attribute_code something different than what the original size attribute was called), and recreate the product using the existing Color attribute, and the newly created Size attribute, Color will be position on top of Size.

Definitely something that should be addressed though. That work-around is cumbersome.

**Comment by nobuttsalex** [comment]
I got the same problem, need to be able to control the order they appear on the front-end (ideally with drag-and-drop from the attribute set page)

**Comment by CKUDG** [comment]
I'm having the exact same problem.. -.- Need to re-order attributes. But it doesn't take affect on front end... Any solutions to this?

Thanks much and best,
Chris

**Comment by rhiensch** [comment]
At step 2 you can select the attributes picker icon on the left so you can re-order the attributes using drag and drop. 
![f6efad08-d1d2-11e5-99c7-d0c2cb194879](https://cloud.githubusercontent.com/assets/3329416/16952166/60704302-4dc8-11e6-9cdc-d87076cf11f8.PNG)

*marked in red

**Comment by zeljkoprsa** [comment]
Can anyone else test to confirm this is no longer an issue on 2.1?
Tested it myself and can confirm that it is working as expected.

**Comment by wert2all** [comment]
Can you still reproduce  this bug?

**Comment by zeljkoprsa** [comment]
@wert2all  Can confirm that it's working correctly now on 2.1.

**Comment by luantran1311** [comment]
i'm running on v2.1.0 , but it is not working!

**Comment by Pakkapao** [comment]
It's working correctly on 2.1.1.

**Comment by veloraven** [comment]
I'm closing this issue as it was fixed.
If you can still reproduce this issue, please create a new GitHub issue report formatting it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by varghesevisal** [comment]
I've the same problem with 2.1.4. I just imported 7 attributes and it wasn't listed in the order which I've given. So, the issue persists. Can anyone suggest anything on this?. Need to import bulk attributes.

**Comment by LiquidSebbey** [comment]
You can easily change this, open the catalog_product_super_attribute table en load the product_id of your configurable product in combination with the required attribute_id's. Then, change the position variables in 10,20,30 (it loads ascending) Go to your configurable product in admin and just save the product. 

This worked for me!
