### ISSUE TITLE
Page builder should be deactivatable for the categories description

### ISSUE THREAD

**Issue by in-session** [magento/magento2#33864]
I think most people will not fill in the category description field with the page builder, but only with text. So it would be handy here to make the field deactivatable for the page builder.

Magento CE 2.4.3

![Ashampoo_Snap_Donnerstag, 19  August 2021_18h28m19s_016_](https://user-images.githubusercontent.com/16542619/130107948-a54c45fe-034a-4adb-ba8c-0dd37cb832cb.png)
![Ashampoo_Snap_Donnerstag, 19  August 2021_18h33m53s_017_](https://user-images.githubusercontent.com/16542619/130107960-629484e7-9487-48c6-8fc3-7ab3a52fa086.png)

**Comment by in-session** [comment]
Moved to https://github.com/magento/magento2-page-builder/issues/768

**Comment by pmonosolo** [comment]
Also, maybe EDIT HTML should be next to EDIT WITH PAGE BUILDER? This is so you don't have to click through 2-3 times just to get to EDIT WITH HTML flow every time?

![image](https://user-images.githubusercontent.com/66754347/130653002-f6bccfdc-dcf7-4c8a-862f-32a1e5fe1765.png)
