### ISSUE TITLE
Unit Test Case Failing in default Magento 2.4.3

### ISSUE THREAD

**Issue by yogicse** [magento/magento2#33861]
### Summary (*)

Unit Test Case Failing in default Magento 2.4.3

1. Navigate to magento root folder
2. Run the command below ` php -f vendor/bin/phpunit -- -c dev/tests/unit/phpunit.xml.dist`

### Examples (*)

`................................................ 16958 / 23201 ( 73%)
...............................PHP Fatal error:  Class Mock_ContextExtensionInterface_9d86d6ca contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\GraphQl\Model\Query\ContextExtensionInterface::getCustomerGroupId, Magento\GraphQl\Model\Query\ContextExtensionInterface::setCustomerGroupId) in /var/www/html/magento243/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(42) : eval()'d code on line 3

Fatal error: Class Mock_ContextExtensionInterface_9d86d6ca contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\GraphQl\Model\Query\ContextExtensionInterface::getCustomerGroupId, Magento\GraphQl\Model\Query\ContextExtensionInterface::setCustomerGroupId) in /var/www/html/magento243/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(42) : eval()'d code on line 3`

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @yogicse,
Could you check if you have such issue on the 2.4-develop branch? I have feeling that this issue already fixed

**Comment by yogicse** [comment]
@ihor-sviziev 

I checked this with the  2.4-develop  branch here it gives warnings instead of fatal errors.

`
155) Magento\Framework\ObjectManager\Test\Unit\Config\XsdTest::testSchemaCorrectlyIdentifiesInvalidXml with data set "virtualtype with empty_type" ('<config xmlns:xsi="http://www...onfig>', array('Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Element 'virtualType', attrib...e: 2\n'
-    1 => 'Element 'virtualType', attrib...e: 2\n'
 )

/var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Test/Unit/Config/XsdTest.php:50

156) Magento\Framework\ObjectManager\Test\Unit\Config\XsdTest::testSchemaCorrectlyIdentifiesInvalidXml with data set "virtualtype with invalid_type" ('<config xmlns:xsi="http://www...onfig>', array('Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Element 'virtualType', attrib...e: 2\n'
-    1 => 'Element 'virtualType', attribute 'name': '777Digits\IsNotAllowed' is not a valid value of the atomic type 'phpClassName'.\n
+    1 => 'Element 'virtualType', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happened.\n
     Line: 2\n
     '
-    2 => 'Element 'virtualType', attrib...e: 2\n'
 )

/var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Test/Unit/Config/XsdTest.php:50

157) Magento\Framework\ObjectManager\Test\Unit\Config\XsdTest::testSchemaCorrectlyIdentifiesInvalidXml with data set "virtualtype with digits_and_prefix_slash" ('<config xmlns:xsi="http://www...onfig>', array('Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Element 'virtualType', attrib...e: 2\n'
-    1 => 'Element 'virtualType', attribute 'name': '\777Digits\IsNotAllowed' is not a valid value of the atomic type 'phpClassName'.\n
+    1 => 'Element 'virtualType', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happened.\n
     Line: 2\n
     '
-    2 => 'Element 'virtualType', attrib...e: 2\n'
 )

/var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Test/Unit/Config/XsdTest.php:50

FAILURES!
Tests: 22643, Assertions: 62154, Failures: 157, Warnings: 15, Skipped: 194, Incomplete: 47.
`

**Comment by Den4ik** [comment]
@yogicse I checked tests on 2..4-develop and fresh 2.4.3 installation and reported fatal error is not reproduced on both installations.

**2.4.3 results**
```
Time: 02:07.141, Memory: 2.20 GB

There was 1 error:

1) PayPal\Braintree\Test\Unit\Gateway\Request\AddressDataBuilderTest::testBuild with data set #0 (array('John', 'Smith', 'Magento', 'street1', 'street2', 'Chicago', 'IL', 'US', '00000'), array(array('John', 'Smith', 'Magento', 'street1', 'street2', 'Chicago', 'IL', '00000', 'US'), array('John', 'Smith', 'Magento', 'street1', 'street2', 'Chicago', 'IL', '00000', 'US')))
Error: Call to undefined method Mock_AddressAdapterInterface_39224eeb::getStreet()

/var/www/html/vendor/paypal/module-braintree-core/Gateway/Request/AddressDataBuilder.php:102
/var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Gateway/Request/AddressDataBuilderTest.php:121

--

ERRORS!
Tests: 23201, Assertions: 63803, Errors: 1, Warnings: 12, Skipped: 217, Incomplete: 47.
```

**2.4-develop results**
```
Time: 01:39.327, Memory: 2.11 GB

There was 1 error:

1) Magento\Setup\Test\Unit\Module\Di\Code\Scanner\PhpScannerTest::testCollectEntities
Magento\Framework\Exception\FileSystemException: The permissions can't be changed for the "/var/www/html/dev/tests/unit/tmp/generated/code/Magento/SomeModule/DummyFactory.php" path. Warning!chmod(): No such file or directory.

/var/www/html/lib/internal/Magento/Framework/Filesystem/Driver/File.php:524
/var/www/html/lib/internal/Magento/Framework/Filesystem/Driver/File.php:345
/var/www/html/lib/internal/Magento/Framework/Code/Generator/Io.php:101
/var/www/html/lib/internal/Magento/Framework/TestFramework/Unit/Autoloader/GeneratedClassesAutoloader.php:64
/var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php:281
/var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php:68
/var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php:130
/var/www/html/setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php:183
/var/www/html/setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Scanner/PhpScannerTest.php:71

--

ERRORS!
Tests: 22644, Assertions: 62187, Errors: 1, Failures: 1, Warnings: 21, Skipped: 182, Incomplete: 47.
```

Please try to recheck your installations and changed files.
Feel free to reopen issue if you will have additional information
