### ISSUE TITLE
Wrong ratings at second Catalog Product List 

### ISSUE THREAD

**Issue by Joshua-Ye** [magento/magento2#33867]
### Preconditions (*)

1.Magento 2.4.3
 

### Steps to reproduce (*)

1.Insert two Catalog Product List on homepage.

### Expected result (*)

1.The product ratings should be correct at second Catalog Product List.

### Actual result (*)

1.![20210820103125](https://user-images.githubusercontent.com/73095214/130169939-b0a052cd-b388-4391-ba83-0bc5ef90e708.png)
2.The product ratings display incorrect at second Catalog Product List.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @Joshua-Ye,
I have tried 4 different products with 2 different columns. Rating is showing as expected.
See attached screenshot:

![image](https://user-images.githubusercontent.com/24711761/130190640-197b78d2-ad2d-48e6-9d7e-9571711de914.png)

![image](https://user-images.githubusercontent.com/24711761/130190684-8308fbe9-f562-4cb7-852d-d44d23211fe8.png)

![image](https://user-images.githubusercontent.com/24711761/130190696-1b6034ef-90de-4b5d-a1ca-6fd4119816dd.png)

![image](https://user-images.githubusercontent.com/24711761/130190727-ae4981ec-22bf-4c56-8fc6-6bd8aed0a4c4.png)

![image](https://user-images.githubusercontent.com/24711761/130190769-71620c5e-530f-411b-9e29-e0bbe2527f98.png)

Can you please how to reproduce this issue @Joshua-Ye?

Thanks.

**Comment by engcom-Echo** [comment]
This is issue is reproducible on 2.4-develop branch with the given steps to reproduce. 
<img width="554" alt="Screenshot 2021-08-20 at 18 38 07" src="https://user-images.githubusercontent.com/51681435/130238131-06477aa6-83a5-4002-bf4f-c854df841e8b.png">
There is definitely a discrepancy on the ratings of products displayed on the 2 product list widgets placed on the home page.

**Comment by Kannakiraj123** [comment]
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment]
@magento give me 2.3.5 instance

**Comment by Kannakiraj123** [comment]
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment]
@magento I am working on this
