### ISSUE TITLE
Integration Issue-Amazon

### ISSUE THREAD

**Issue by melissahtp** [magento/magento2#33862]
We've had a handful of addresses coming over yesterday & today that are coming over with n/a in the name field and the street address field.  The city, state & zip come over fine.  Any idea what would be causing this?  Its not all which leads me to believe its an issue with Amazon's API but wondering if you've had reports of it. Magento ver. 2.3.4-p2

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @melissahtp,

The information provided is not enough for us to check the issue.

In order to check this issue, please update below information:
1. Is issue reproducible on 2.4-develop instance ? If yes, please provide the ‘Steps to reproduce’ same.
2. Which specific API functionality or module is in question ?

**Comment by engcom-Lima** [comment]
There has been no update from the reporter on this issue so closing this.
