### ISSUE TITLE
User-Agent Exceptions breaks theme translations translations

### ISSUE THREAD

**Issue by helloeverything** [magento/magento2#3388]
When using theme translations for example **parent/theme/i18n/en_GB.csv** and have the the theme set to appear via a User-Agent Exceptions the translations do not show on the front-end.

**Comment by antboiko** [comment]
Hi @helloeverything , thanks for your inquiry. Could you please clarify which Magento version do you use?

Best,
Anton.

**Comment by helloeverything** [comment]
Hi Anton,

I am using  Magento ver. 2.0.2.

Many thanks
David

**Comment by antboiko** [comment]
David, 

Thanks for reporting, we've created internal ticket MAGETWO-49207 to investigate.

Best,
Anton.

**Comment by arkadiych** [comment]
@helloeverything, could you give more details and some use cases how to reproduce this issue?

**Comment by andimov** [comment]
@helloeverything 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
