### ISSUE TITLE
Page Builder missing support for remote storage

### ISSUE THREAD

**Issue by in-session** [magento/magento2#33882]
Currently there is the problem that you can not use the resize function with remote storage and the pagebuilder.
For the converting of the images there should be a possibility to add parameters to resize the images.

Magento 2.4.3
https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.html

**Comment by mrtuvn** [comment]
i think we should report bug in pagebuilder repo instead

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2-page-builder/issues

**Comment by in-session** [comment]
Moved to 
https://github.com/magento/magento2-page-builder/issues/767
