### ISSUE TITLE
Passwort request token cannot be passed as provided

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#33894]
### Preconditions (*)

1. Magento 2.4.3
2. Customer Account

### Steps to reproduce (*)

1. Execute the `requestPasswordResetEmail` mutation
2. Click on the link you'll receive, it looks like this:
  `https://localhost/customer/resetpassword?token=3DNOQwdipYtLgFjSpnwAz59CDBCFECLCVt`
3. Copy the token
4. Execute the `resetPassword` mutation with the token

### Expected result (*)

1. Success!

### Actual result (*)

1. Error!

### Underlaying problem
The problem is that the `resetPassword` mutation wants the token without the first two letters (3D), so instead of `3DNOQwdipYtLgFjSpnwAz59CDBCFECLCVt` you have to pass `NOQwdipYtLgFjSpnwAz59CDBCFECLCVt`.

Maybe in the magento default frontend the token gets properly processed in the frontend, but this is not the case for graphql.
  At the moment we're removing the "3D" from the token before passing it to the mutation, but it's just a temporary solution and nothing permanent as it can break anytime, as it just did with the update from Magento 2.4.2 to 2.4.3.
In Magento 2.4.2 the token looked like `3D=NOQwdipYtLgFjSpnwAz59CDBCFECLCVt`.
In Magento 2.4.3 the "=" after "3D" was removed and our frontend broke.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment]
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment]
Well, cannot test it as the instance doesn't send emails...

**Comment by oneserv-heuser** [comment]
Found the issue, it's our email slurping program, which destroys the email and adds 3D. So not magentos fault.
