### ISSUE TITLE
magento/module-sales-archive afterGetIds memory limit error

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#33891]
### Preconditions (*)

1. Magento Enterprise 2.3.4

### Steps to reproduce (*)

1. Get about 5 millions orders in sales_order
2. Get about 3 millions orders in magento_sales_order_grid_archive
3. Try to run cron sales_grid_order_async_insert

### Expected result (*)

1. Grid reindex without error

### Actual result (*)

1. Php memory limit exception

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

---

My workaround : 

src/vendor/magento/module-sales-archive/Plugin/ArchivedEntitiesProcessorPlugin.php

 public function afterGetIds(
        UpdatedIdListProvider $provider,
        array $result,
        string $mainTableName,
        string $gridTableName
    ) : array {
        $archiveTable = $this->tableMapper->getArchiveEntityTableBySourceTable($gridTableName);
        if (!empty($result) && $archiveTable !== null) {

            //overide : fix memory limit error using array_chunk
            $totalFetchedArchivedIds = [];
            foreach(array_chunk($result, self::BATCH_SIZE) as $bunch) {
                $select = $this->getConnection()->select()
                    ->from($archiveTable)
                    ->where($archiveTable . '.entity_id IN (?)', $bunch);
                $fetchedArchivedIds = $this->getConnection()->fetchAll($select, [], \Zend_Db::FETCH_COLUMN);

                $totalFetchedArchivedIds = array_merge($totalFetchedArchivedIds, $fetchedArchivedIds);
            }

            return array_diff($result, $totalFetchedArchivedIds);
        }

        return $result;
    }

**Comment by engcom-Lima** [comment]
Hi @vahir2016,

Thank you for reporting the issue.

I tried to reproduce this issue on 2.4-develop instance and cron sales_grid_order_async_insert is running as expected.

For further analysis, can you please update the below queries:
1. Can you please check and confirm if this issue reproducible on 2.4-develop instance with the data that you have ?
2. How much time does the cron is taking and what is your PHP memory limit ?

**Comment by sivajik34** [comment]
https://medium.com/swlh/magento-2-legacy-orm-explained-178431305fb9

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
