### ISSUE TITLE
Session size of 276672 exceeded allowed session max size of 256000 - but in Magento 2.4.3 backend 

### ISSUE THREAD

**Issue by UsmanIftikhar881** [magento/magento2#33897]
After upgrading to Magento 2.4.3, when we log into backend (admin panel), everypage hangs/is loading about 30 seconds.

In logs we see exceptions: Session size of 276672 exceeded allowed session max size of 256000.

We are using Redis for sessions.

Does anybody else have similar issue after upgrading to Magento 2.4.3?

**Comment by nureintropf** [comment]
Hi @UsmanIftikhar881 you get configure this 
![grafik](https://user-images.githubusercontent.com/19589209/130651168-b81ed86f-b5a2-46e3-a885-46d91b3e2490.png)

**Comment by craigfleming** [comment]
@UsmanIftikhar881 - Yes, I experienced this issue on my local Docker development system after upgrading to v2.4.3.

Follow the advice given by @nureintropf.

If you can not access the admin to update the values, use the following CLI commands:

`bin/magento config:set system/security/max_session_size_admin 512000`
`bin/magento config:set system/security/max_session_size_storefront 512000`

Clean your cache and your admin backend should function at full speed like before.

**Comment by mrtuvn** [comment]
Please search issues first for avoid same issue here https://github.com/magento/magento2/issues/33748

**Comment by engcom-Lima** [comment]
Hi @UsmanIftikhar881,

As this issue is duplicate to #33748 which is also open, we are closing this issue. Please follow up on the other thread for the solution.
