### ISSUE TITLE
unable to run any magento commad

### ISSUE THREAD

**Issue by moonbutt20** [magento/magento2#33895]
Hello, 

when i run any commad this error comes. 
"[root@server httpdocs]# php -dmemory_limit=1G bin/magento indexer:reindex
Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read <a href="http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements.html" target="_blank" class="redactor-autoparser-object">http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements.html"

even my php version is 7.1

how i resolve this issue?

**Comment by engcom-Echo** [comment]
Hi @moonbutt20 
Please let us know more details about the issue you are facing, like the exact command you are trying to hit & the response you are getting. Do try to change your memory limit (may be to 5G) & re run the command.
Also please update the issue descriptions with Preconditions, Steps to reproduce, Expected result, Actual result.

Thank you.

**Comment by moonbutt20** [comment]
thanks for responding. yes i also change the memory limit but same issue. 

i am using Magento 2.3 and using plesk hosting they update version into [php](url) 7.1 and i used winscp to run commands. 
i checked the version using `php --version` this shows 5.4 php version installed
"Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read <a href="http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements.html"
i updated and at this time php version is 7.1 but same error occur when i run any command. 

could you please guide me. how i run any command? or update template?

**Comment by engcom-Hotel** [comment]
Hello @moonbutt20,

It seems that still CLI picked up an older version of PHP. Please try to update PHP and let us know if you still facing the same issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @moonbutt20,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
