### ISSUE TITLE
[GraphQl 2.4.2] subtotal_with_discount_excluding_tax is calculated using discount including tax

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#33905]
### Preconditions (*)

1. Magento 2.4.2
2. tax/calculation/price_includes_tax = including tax
3. tax/calculation/apply_after_discount = after discount
4. tax/calculation/discount_tax = including tax

### Steps to reproduce (*)

1. Create a cart and add  a product that's worth 1000 (incl tax) with a tax% of 25%.
2. Set a discount on the cart for 10.
3. Do the following graphql request
```
query getCartDetails($cartId: String!) {
	cart(cart_id: $cartId) {
                 prices {
			applied_taxes {
				amount {
					value
				}
			}
			discount {
				amount {
					value
				}
			}
			subtotal_including_tax {
				value
			}
			subtotal_excluding_tax {
				value
			}
                        subtotal_with_discount_excluding_tax {
				value
			}
			grand_total {
				value			
                        }
		}
	}
}
```

### Expected result (*)

```
{
    "data": {
        "cart": {
            "prices": {
                "applied_taxes": [
                    {
                        "amount": {
                            "value": 198
                        }
                    }
                ],
                "discount": {
                    "amount": {
                        "value": -10
                    }
                },
                "subtotal_including_tax": {
                    "value": 1000
                },
                "subtotal_excluding_tax": {
                    "value": 800
                },
                "subtotal_with_discount_excluding_tax": {
                    "value": 792
                },
                "grand_total": {
                    "value": 990
                }
            }
        }
    }
}
```
"subtotal_with_discount_excluding_tax"  should be 1000 - 10 - 198 = 792
Which is same as 800 (Sub total) - 8 (Sub total discount) = 792

### Actual result (*)

```
{
    "data": {
        "cart": {
            "prices": {
                "applied_taxes": [
                    {
                        "amount": {
                            "value": 198
                        }
                    }
                ],
                "discount": {
                    "amount": {
                        "value": -10
                    }
                },
                "subtotal_including_tax": {
                    "value": 1000
                },
                "subtotal_excluding_tax": {
                    "value": 800
                },
                "subtotal_with_discount_excluding_tax": {
                    "value": 790
                },
                "grand_total": {
                    "value": 990
                }
            }
        }
    }
}
```
**UI Issue: Payment Breakup details sum is not matching with Grand Total.
800 - 10 + 198 = 988 but not 990**
![image](https://user-images.githubusercontent.com/60198231/131515648-cb884239-4153-4997-9ccd-cb80797b991f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
The issue has been fixed and merged with mainline 2.4-develop. The commit id for the same is `986cef0977fdcfd3fe85a9b8647866dee60e66a4 `
