### ISSUE TITLE
File stat or filesize validation of File Attribute leading exception while saving model

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#33901]
### Preconditions (*)

1. Magento 2 all versions
2.

### Steps to reproduce (*)

1. Create an attribute for customer which 'input' => 'file',
```
$customerSetup->addAttribute(
            \Magento\Customer\Model\Customer::ENTITY,
            'foo',
            [
                'type' => 'text',
                'label' => 'Foo',
                'input' => 'file',
                'source' => '',
                'required' => false,
                'visible' => true,
                'position' => 200,
                'system' => false,
                'backend' => ''
            ]
        );
        
```
2. Try to upload for it a value(a file - foo.jpg for example)
3. Save the customer
4. Manually remove the local file on server (foo.jpg)
5. Save the customer again

### Expected result (*)

1. The customer could be saved even the value or the local file was removed
2. Cannot do anything related to this customer or customer group which this customer belong to such as Import or Save or anything.

### Actual result (*)

1. Exception throw-ed while trying to saving the customer
2. https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Eav/Model/Attribute/Data/File.php#L195-L200
Those lines throwing exception while the local file doesn't exist. Possible do try catch while exception throw-ed the status of should be marked as Missing and by pass the validation?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tuyennn** [comment]
@engcom-Delta any update from this issue?

**Comment by engcom-Hotel** [comment]
Hello @tuyennn,

Thanks for posting the issue!

We have tried it in Magento 2.4-develop and seems this is expected behaviour. If the original file has been removed then it should raise an error so that the admin can check this issue.

Please correct me if I am wrong.

Thanks

**Comment by tuyennn** [comment]
@engcom-Hotel I believe while I process the customer group as saving them for example then I also have to check all the member of this group whether several or many customer members were missing those data.

If you find that is expected behaviour I will close the ticket, but please get me back those questions

**Comment by engcom-Hotel** [comment]
Hello @tuyennn,

Please clarify the below comment:

> @engcom-Hotel I believe while I process the customer group as saving them for example then I also have to check all the member of this group whether several or many customer members were missing those data.

Thanks

**Comment by tuyennn** [comment]
@engcom-Hotel I believe this is still the problem while it prevents us to process customer, customer group which related to this exception.

But fine, Magento often considered expect behavior rather than admit it a bug.
