### ISSUE TITLE
The beforeSave() method in app/code/Magento/Ui/view/base/web/js/form/client.js tries to make AJAX requests for undefined URLs

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3391]

**Comment by davidalger** [comment]
@dfediuk This is the 3rd time this week you have been requested to stop posting self-promoting links by the moderators. Consider this your last warning. If you will not post meaningful content and contribute just like everyone else, you are not welcome here and will end up banned from participation.
