### ISSUE TITLE
Having more than one custom option of type File does not work

### ISSUE THREAD

**Issue by jlenzstaysafe** [magento/magento2#33927]
### Preconditions (*)

Magento 2.4.2 Commerce

### Steps to reproduce (*)

1. Add 2 custom options of type "File" to a product
2. Go to the frontend product page and try adding that product to cart with those 2 file options

### Expected result (*)

1. Product should be added to cart

### Actual result (*)

1. Page refreshes with product not added to cart, no error message displayed, no JS errors, no errors in any log files

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-November** [comment]
Hi @jlenzstaysafe ,
We are closing this issue as there has been no latest update on the same.
Thank you.
