### ISSUE TITLE
Unable to import tablerates when condition is set in config.php

### ISSUE THREAD

**Issue by Meberem** [magento/magento2#33931]
### Preconditions (*)

1. Set config.php to set carrier "tablerate" to use a set condition

My config looks like so:
```
<?php
return [
 'system' => [
        'default' => [
            'carriers' => [
                'tablerate' => [
                    'condition_name' => 'package_value_with_discount'
                ]
            ]
        ]
    ]
];
?>
```

### Steps to reproduce (*)

1.Upload a [tablerates.csv](https://github.com/magento/magento2/files/7066360/tablerates.csv)

### Expected result (*)

1. I am able to upload tablerates.csv

### Actual result (*)

1. Error on the Admin UI: "Something went wrong while importing table rates"
2. Error in the exception.log
```
.CRITICAL: The "condition_name_short: " code type for Table Rate is incorrect. Verify the type and try again. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The \"condition_name_short: \" code type for Table Rate is incorrect. Verify the type and try again. at /var/www/html/vendor/magento/module-offline-shipping/Model/Carrier/Tablerate.php:252)"} []
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by nuzil** [comment]
Hi @Meberem 
Its not a bug, its expected behaviour. If you settings up config in config.php, then this value has more priority then config one.
Only solution here is to remove fixed config value from config.php

**Comment by Meberem** [comment]
@nuzil then why am I given the option to upload a csv file? It is an incredibly unintuative UI if this is the case.

I have set this option with the expectation that my stores only support a certain table rate setting to prevent any accidental configuration changes. Then I would be able to adjust the rates without adjusting the Price/Weight/Number of items vs destination setting.

The [user guide](https://docs.magento.com/user-guide/shipping/shipping-table-rate.html#step-2-prepare-the-table-rate-data) even shows this UI even though it is wrong.
