### ISSUE TITLE
Error with PHP 8 str_contains function when upgrade to 2.4.3

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#33945]
### Preconditions (*)
1. Magento current version: enterprise 2.4.1-p1
2. Use PHP 7.4
3. Disable MSI modules

### Steps to reproduce (*)
1.Run composer command: `composer require magento/product-enterprise-edition=2.4.3 --no-update`
2.Run composer update command: `composer update`

### Expected result (*)
1. Upgrade to Magento EE 2.4.3 successfully

### Actual result (*)
1. An error exception appear
`Fatal error: Uncaught Error: Call to undefined function Magento\Framework\Filesystem\Directory\str_contains() in vendor/magento/framework/Filesystem/Directory/DenyListPathValidator.php:74`
![image](https://user-images.githubusercontent.com/88669934/131301198-24d1022f-3da6-4098-8474-0bce25958c90.png)

**Comment by manhtranisobar** [comment]
This issue was fixed

**Comment by ihor-sviziev** [comment]
Duplicates https://github.com/magento/magento2/issues/33680
