### ISSUE TITLE
Error with queue Newsletter

### ISSUE THREAD

**Issue by Zocky01** [magento/magento2#3394]
I try to queue newsletter but when i pick Queue Date Start from calendar (Croatian locale) and click "Save Newsletter", I am getting error report "Failed to parse time string (14. velj 2016. 02:16:59) at position 0 (1): Unexpected character"

**Comment by veloraven** [comment]
@Zocky01 thank you for your report.
If this issue is still actual please provide version for which it is actual.
I can suppose that you used some localization, please provide information about used localization as well.
If this issue is not actual anymore, please close it.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
