### ISSUE TITLE
Closed orders not showing closed

### ISSUE THREAD

**Issue by IssyHutchins** [magento/magento2#33956]
Hi,

I have 4 orders that are 'closed' but are not showing closed on my system.
0544 - 'on hold' but is not letting me cancel and close.
0050 - 'on hold' but is not letting me cancel and close.
0739 - 'processing' but is closed but not changing.
1239 - 'processing' but is closed but not changing.

How do I change this?
Thanks,

**Comment by engcom-Delta** [comment]
Hi @IssyHutchins  ,

Thanks for logging an issue and found that issue reproducible steps , actual results ,snapshots for reference and expected results. Hence request to provide them.

Regards

**Comment by devchris79** [comment]
Its not obvious if this is a bug or a question about how Magento works.

If you want to close an order that has been refunded externally to Magento you need to create an offline credit memo of equal value to the order. You just need to go to the order details and click credit memo and click OK when Magento warns you are going to create an offline credit. You will then reach the screen that you can set the items to be credited, if all is credited the order state will become closed.
