### ISSUE TITLE
WYSIWYG (TinyMCE4) HTML Render & Save Issue in a Magento 2 Widget

### ISSUE THREAD

**Issue by goranhorvathr** [magento/magento2#33952]
Preconditions (*)
Magento 2.4.2, 2.4.3
PHP 7.4

Steps to reproduce (*)

Adding a native WYSWYG field to Magento 2 native widgets results in failed rendering when accessing the widget data from CMS page. 

Creating a block class https://gist.github.com/goranhorvathr/44f5ea3eeac054071d250d2ba6614024. Adding it to widget in widget.xml  as a parameter and adding the widget to any CMS page with the following wysiwyg html code https://gist.github.com/goranhorvathr/37d3280e2864af21e88fcc3e37b20f49

`<parameter name="example_content" sort_order="20" visible="true" xsi:type="block">
                <label>Content</label>
                <description>Enter any content here.</description>
                <block class="Example\Widgets\Block\WidgetConfigs\Wysiwyg"/>
</parameter>` 

Expected result (*)
We are expecting to see the rendered html inside of the wysiwyg. 
![WYSIWYG-Correct Render](https://user-images.githubusercontent.com/36931660/131428290-6cf5a054-07e1-41ab-946a-57bbb7cbb023.jpg)
 

Actual result (*)
We have a broken view. We are currently tracking down this issue but it seems it is closely connected to webroot/lib/web/mage/adminhtml/wysiwyg/widget.js lines 290

Seems like gsub regex is not working correctly to properly map html values. Or there is escape issue of the apostrophes.

![WYSIWYG-RenderIssue](https://user-images.githubusercontent.com/36931660/131427534-3063388b-66be-42ce-9fd4-60bd3dcdf409.jpg)

Severity: <strong>S2</strong> <em>- Affects non-critical data or functionality and forces users to employ a workaround.

**Comment by mrtuvn** [comment]
seem you try to mix tailwind class to html but i'm not sure it work when class contain character ":"

**Comment by Vinai** [comment]
No idea what is going on here. Just wanted to note that I haven't had any issues using tailwind variant css classes in TinyMCE.

**Comment by goranhorvathr** [comment]
Right so short update here we have done some fixes on this main fix has been done in a plugin for aroundGetWidgetDeclaration. We are currently preparing all of these things and we will post here with the repository where this will be resolved as part of something bigger. If anyone has any issues with Magento 2 widgets and WYSWYG editors in it among other problems not functioning correctly in native m2 do please hit us up here we might have already fixed it. Thank you everyone for engagement and stay tuned.

**Comment by indykoning** [comment]
Hi @goranhorvathr,
Have you been able to fix this issue? we are experiencing this as well right now

**Comment by goranhorvathr** [comment]
Yes we did @indykoning. We are going to release this as part of a certain project we are doing. So it will be available to you open source with 4 prebuilt widgets it requires a set of changes & plugins. I got several hits also directly on my email too regarding this so i can see that this is starting to be an issue slowly for frontend devs. I will prepare a short blog post on the fixes however in the meantime please find the gists attached https://gist.github.com/goranhorvathr/5ee7eb1e10b5f01bdda4eea56aee6942. The main issue of everything is actually the escaping of the apostrophes on widget insert so we fixed that in aroundGetWidgetDeclaration Plugin. Additionally Magento 2 has directive issues with image fields in widgets on custom image fields which we fixed by forcing static urls only for custom image fields with the following observer https://gist.github.com/goranhorvathr/577cf4b3b5371638d2dd2547792d5a6f & its appropriate events.xml https://gist.github.com/goranhorvathr/52431bc0d9e03f89c7c466c685098f8. Additionally WYSIWYG image plugin  for proper rendering of images inside of a custom WYSIWYG editor field inside of the widgets https://gist.github.com/goranhorvathr/78b3737f1d7b1383a652a01d5fb4c7f5https://gist.github.com/goranhorvathr/78b3737f1d7b1383a652a01d5fb4c7f5

**Comment by indykoning** [comment]
Thank you!
Yeah i do think it's an issue introduced in one of the Magento updates.
What i've noticed when looking in the database is that before the content of a wysiwyg widget in the database would be htmlencoded
```
{{widget type="Vendor\Module\Block\Widget\Grid" 
content1="&lt;p&gt;&lt;a title=&quot;Lorem Ipsum&quot; href=&quot;/&quot;&gt;&lt;img src=&quot;/media/image.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;&lt;/p&gt;" 
content2="&lt;p&gt;&lt;a title=&quot;Lorem Ipsum&quot; href=&quot;/&quot;&gt;&lt;img src=&quot;/media/image.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;&lt;/p&gt;" 
content3="&lt;p&gt;&lt;a title=&quot;Lorem Ipsum&quot; href=&quot;/&quot;&gt;&lt;img src=&quot;/media/image.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;&lt;/p&gt;" 
content4="&lt;p&gt;&lt;a title=&quot;Lorem Ipsum&quot; href=&quot;/&quot;&gt;&lt;img src=&quot;/media/image.jpg&quot; alt=&quot;&quot;&gt;&lt;/a&gt;&lt;/p&gt;" 
template="widget/grid.phtml"}}
```
And now when saving even the htmlencoded version it saves it as
```
{{widget type="Vendor\Module\Block\Widget\Grid" 
content1="<p><a title="Lorem Ipsum" href="/"><img src="/media/image.jpg" alt=""></a></p>" 
content2="<p><a title="Lorem Ipsum" href="/"><img src="/media/image.jpg" alt=""></a></p>" 
content3="<p><a title="Lorem Ipsum" href="/"><img src="/media/image.jpg" alt=""></a></p>" 
content4="<p><a title="Lorem Ipsum" href="/"><img src="/media/image.jpg" alt=""></a></p>" 
template="widget/grid.phtml"}}
```
Which makes it clear that it would close the content variable after encountering the first `title=` making the content in the frontend
`<p><a title=`

**Comment by indykoning** [comment]
I believe this is the exact commit that broke the encoding: https://github.com/magento/magento2/commit/ae3d3df4752dfcac5256ddb5014ce02b19e8a529

**Comment by goranhorvathr** [comment]
Exactly @indykoning. Could possibly be the change occurred between m2 2.3.7 & 2.4.0 which could be the https://github.com/magento/magento2/commit/ae3d3df4752dfcac5256ddb5014ce02b19e8a529

**Comment by engcom-Hotel** [comment]
Hello @goranhorvathr,

We have tried to reproduce the issue in Magento 2.4-develop branch with the above-mentioned steps. The issue is not reproducible for us. 

Please find attached the screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/134349093-be2925f4-f4b2-45d6-827b-9c777525b9c7.png)

Please find attached my block class:

[Editor.php.txt](https://github.com/magento/magento2/files/7210907/Editor.php.txt)

Let us know in case we missed anything.

Thanks

**Comment by goranhorvathr** [comment]
Hello @engcom-Hotel thank you i will test it thoroughly our code is practically the same but we have two different results. Im positive there is an issue there it depends in the difference in the testing environments because  2.3.7 we could not replicate this either. So i will take the clean branch this weekend and retest it and come back to you guys.

**Comment by engcom-Hotel** [comment]
Hello @goranhorvathr,

Thanks for the update. We will wait for your reply.

Thanks

**Comment by goranhorvathr** [comment]
Hello Guys yes. We have fixed the issue for ourselves we are still reviewing the solution. We will get back to  everyone and all interested parties here with the fix. We have not published the fix yet.
