### ISSUE TITLE
The quantity of Bundle products on the Shopping Cart is wrong when Magento_Inventory* modules are disabled

### ISSUE THREAD

**Issue by densen45** [magento/magento2#33964]
### Preconditions (*)

1. Magento 2.4.2-p2 (may happen with previous versions)
2. PHP 7.3

### Steps to reproduce (*)

1. Disable all Magento_Inventory* modules, delete generated and compiled files, flush cache
1. Create a Bundle with at least one option (radio or drop-down), add several simple products to the option and check "User Defined Qty"
2. Open the Bundle on frontend
3. Choose one of the simple products and change the quantity for the option to another value then "1" (e.g. 2)
4. Make sure that the quantity of the Bundle itself is still set to "1"
4. Add the configured Bundle to the shopping cart

### Expected result (*)

1. The Bundle is added to the shopping cart with quantity 1
3. The subtotal price on the shopping cart is shown for quantity 1
2. The mini cart preview icon shows an amount of 1

### Actual result (*)

1. The shopping cart shows the Bundle with quantity 4 (when set the quantity of the selection to 2)
2. The subtotal price is shown for quantity 2
2. The mini cart preview icon shows an amount of 2

### Investigation
It seams to me, that the quantity of the Bundle product is multiplied with the quantity of the last selection in the Bundle.
The whole situation gets worst when you add further products to the shopping cart. Every time a new product is added, the current (wrong) quantity of the Bundle is multiplied again with the quantity of the last selection.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment]
@magento give me 2.4.2-p2 instance

**Comment by densen45** [comment]
I cannot reproduce the issue on the provided Magento Instance.

**Comment by densen45** [comment]
I was not able to reproduce the issue on the provided Magento Instance, because this issue only occurs when the Magento_Inventory* modules are disabled. Maybe we missed something that these are mandatory?

We have disabled these modules since they exist and the issue did not occur before M 2.4.2.

**Comment by nuzil** [comment]
Hi @densen45 
Officially, Magento_Inventory cannot be disabled if you are using Stock. Old module is still there, but its a legacy module and support for it is not provided.

**Comment by densen45** [comment]
After enabling all Magento_Inventory* modules the issue is gone, but now we are not able to save any product.

This is the error message:
`The stock item was unable to be saved. Please try again.`

This is the message from the exeption.log
```
[2021-09-01 14:37:23] main.CRITICAL: The stock item was unable to be saved. Please try again. 
{"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, 
Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): Could not save Source Item at vendor/magento/module-inventory/Model/SourceItem/Command/Handler/SourceItemsSaveHandler.php:79, 
Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db_name`.`inventory_source_item`, CONSTRAINT `INVENTORY_SOURCE_ITEM_SOURCE_CODE_INVENTORY_SOURCE_SOURCE_CODE` FOREIGN KEY (`source_code`) REFERENCES `inventory_source` (`sour), query was: INSERT INTO `inventory_source_item` (`source_code`, `sku`, `quantity`, `status`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `quantity` = VALUES(`quantity`), `status` = VALUES(`status`) at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, 
PDOException(code: 23000): 
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db_name`.`inventory_source_item`, CONSTRAINT `INVENTORY_SOURCE_ITEM_SOURCE_CODE_INVENTORY_SOURCE_SOURCE_CODE` FOREIGN KEY (`source_code`) REFERENCES `inventory_source` (`sour) at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
```

We appreciate any help :)

**Comment by daancart2quote** [comment]
After updating from 2.3.5-p2 to 2.3.7-p2, we found the same issue.

`\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\Initializer\quoteItem:123`
```
            /**
             * if option's qty was updates we also need to update quote item qty
             */
            $quoteItem->setData('qty', (int) $result->getItemQty());
```
            
This multiplies the quoteItem qty (the bundle) with each qty of a bundle option. The last option qty remains the multiplier of the resulting qty of the bundle.

Indeed the module `Magento_Inventory` is disabled.

Finding this has cost us a lot of hours, and we didn't even start fixing it. This should be fixed or mitigated with a warning somewhere.

**Comment by daancart2quote** [comment]
Investigating this further, this line was changed in the last release by this commit: https://github.com/magento/magento2/commit/dac067c9e8c056e5aedeba62cf3d58b10bc90d8e

```
-            $quoteItem->setData('qty', (int) $qty);
+            $quoteItem->setData('qty', (int) $result->getItemQty());
```

The note "if option's qty was updates we also need to update quote item qty" and the line `$quoteItem->setData('qty', (int) $qty);` were there since Magento 2.0.0.0-dev66, and `$qty` has indeed the correct value.

The original code:

```
            /**
             * if option's qty was updates we also need to update quote item qty
             */
            $quoteItem->setData('qty', (int) $qty);

```

Was probably there, not because it changed anything, but as a trigger for other implementations. As $qty is a parameter of the function and is never overwritten.

This change was in 2.4.3 but probably made its way into 2.3.7-p2 and 2.4.2-p2.

**Comment by daancart2quote** [comment]
For anyone that needs a quick patch for this. (Presumably users on 2.3.7-p2, 2.4.2-p2, and 2.4.3)

`composer.json require:`
```
 "cweagans/composer-patches": "^1.7.1",
```

`composer.json extra:`
```
        "patches": {
            "magento/module-catalog-inventory": {
                "issue-33964": "patches/composer/33964-bundles-multiply-with-inventory-disabled.diff"
            }
        }
```

`[root]/patches/composer/33964-bundles-multiply-with-inventory-disabled.diff`
```
diff --git a/Model/Quote/Item/QuantityValidator/Initializer/Option.php b/Model/Quote/Item/QuantityValidator/Initializer/Option.php
--- a/Model/Quote/Item/QuantityValidator/Initializer/Option.php
+++ b/Model/Quote/Item/QuantityValidator/Initializer/Option.php
@@ -120,7 +120,7 @@
             /**
              * if option's qty was updates we also need to update quote item qty
              */
-            $quoteItem->setData('qty', (int) $result->getItemQty());
+            $quoteItem->setData('qty', (int) $qty);
         }
         if ($result->getMessage() !== null) {
             $option->setMessage($result->getMessage());

```

**Comment by densen45** [comment]
> Hi @densen45 Officially, Magento_Inventory cannot be disabled if you are using Stock. Old module is still there, but its a legacy module and support for it is not provided.

Hey @nuzil, for clarification: We had disabled all the modules that are prefixed by "Magento_Inventory", not only the "Magento_inventory" module. Thus, we didn't used any of these "new" Stock features at all.
We would like to disable all of these modules again, as we have had some issues combined with our custom modules and the obvious deployment and adminhtml overhead.

Our questions:
1. Do we always have to enable all the modules prefixed by "Magento_Inventory" or only when we intend to use the Stock features that come with the other Magento_Inventory* modules?
1. Do we have to expect other issues when we disable these modules, even we don't use the Stock features that come with the Magento_Inventory* modules?

If we can disable these modules without expecting further issues, we would like to go with the quick fix of @daancart2quote.

**Comment by zamoroka** [comment]
same issue during update from 2.4.2 to 2.4.2-p2
quick fix helps as mentioned by @daancart2quote  
```
-            $quoteItem->setData('qty', (int) $result->getItemQty());
+            $quoteItem->setData('qty', (int) $qty);
```
