### ISSUE TITLE
Problema email

### ISSUE THREAD

**Issue by raffaele345** [magento/magento2#33962]
Salve buongiorno, ho un problema con l email del mio sito magento2. Non riesco a ricevere email ne tantomeno i miei clienti riescono a riceverle quando si iscrivono al mio sito o acquistano prodotti.

**Comment by krishprakash** [comment]
Hi @raffaele345. There should some issue with your email configuration.
Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
Thanks
