### ISSUE TITLE
Update some npm libraries (see description) to the latest versions

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#33972]
### Description (*)
As part of task magento/magento2#33512, we have updated most of the npm libraries.
The updated libraries are described below.
1. `glob` from ~7.1.1 to ~7.1.7
2. `grunt` from ~1.0.1 to ~1.4.1
3. `grunt-contrib-clean` from ~1.1.0 to ~2.0.0
4. `grunt-contrib-connect` from ~1.0.2 to ~3.0.0
5. `grunt-contrib-cssmin` from ~2.2.1 to ~4.0.0
6. `grunt-contrib-imagemin` from ~2.0.1 to ~4.0.0
7. `grunt-contrib-watch` from ~1.0.0 to ~1.1.0
8. `grunt-replace` from ~1.0.1 to ~2.0.2
9. `load-grunt-config` from ~0.19.2 to ~4.0.1
10. `morgan` from ~1.9.0 to ~1.10.0
11. `node-minify` from ~2.3.1 to ~3.6.0
12. `serve-static` from ~1.13.1 to ~1.14.1
13. `time-grunt` from ~1.4.0 to ~2.0.0

However, 4 libraries were identified that caused the builds to crash.
These libraries are described below. They have also been updated to the latest minor or patch versions of the current major.
1. `grunt-contrib-jasmine` current version ~1.2.0 (available version 3.0.0)
2. `grunt-eslint` has been updated from ~20.1.0 to ~20.2.0 (available version 23.0.0)
2. `imagemin-svgo` has been updated from ~5.2.1 to ~5.2.4 (available version 9.0.0)
3. `strip-json-comments` current version ~2.0.1 (available version 4.0.0)

We need to investigate and fix the problem and update these libraries to the latest available version.
A task can be separated into sub-tasks.

### Expected result (*)
1. All npm libraries updated to the latest versions

### Actual result (*)
1. Some libraries not updated

**Comment by eduard13** [comment]
### Overview

- grunt-contrib-jasmine - from the next 2.0.0, the library has switched from PhantomJS to Chrome Headless via puppeteer, and requires reconfiguring the extension.
- grunt-contrib-less - version 3.0.0 and higher, are failing on Github builds without an explicitly reason
- grunt-eslint - from the next 21.0.0 we're started getting the Warning: must provide pattern
- imagemin-svgo - version 8.0.0 and higher, are failing on Github builds without an explicitly reason
- strip-json-comments - versions above 3.1.1 throw the following warning: `require() of ES modules is not supported.`
