### ISSUE TITLE
Magento2 - Change customer Group Programatically for guest and logged in users

### ISSUE THREAD

**Issue by dhanrajm-denali** [magento/magento2#3398]
Hi,
     I have a form in which when a particular code is given, the customer group should be changed to apply discounts. 

I have tried the following code, it changes the customer group. I can see the discounted prices in Product list page as well as Product detail page. But in the cart and checkout process it doesnt apply.

$this->session->setCustomerGroupId("3");

Can someone please help in solving the issue.

Thanks,
Dhanraj

**Comment by benmarks** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
