### ISSUE TITLE
customer missing in the backend.

### ISSUE THREAD

**Issue by cs221313** [magento/magento2#3399]
Hi, all,

After I registered an account, that account information is not shown in the backend. I can find it at the table customer_entity.
![image](https://cloud.githubusercontent.com/assets/8097168/13032410/7ced1fc6-d32c-11e5-831a-95b36d0979ce.png)

but could not find at the customer list.
![image](https://cloud.githubusercontent.com/assets/8097168/13032414/8eaac560-d32c-11e5-81dc-0e85068519f1.png)

**Comment by sevos1984** [comment]
Your grid indexer seems to be invalidated, try running 'php bin/magento indexer:reindex customer_grid'

**Comment by cs221313** [comment]
You are right. It works after I run the php bin/magento indexer:reindex customer_grid command.

Thanks a lot.
