### ISSUE TITLE
Creating new Product fail - Error SQLSTATE[42000]: Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by fm-cl** [magento/magento2#33994]
### Preconditions (*)

1. Migrate from Magento 1.9.1.0 to Magento 2.4.3
2. 

### Steps to reproduce (*)

1. Create a producto in magento 2
2.

### Expected result (*)

1.  Should create a product
2.

### Actual result (*)

1. SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?))' at line 2, query was: SELECT `e`.`entity_id` FROM `catalog_product_super_link` AS `l` INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = l.parent_id WHERE (l.product_id IN(?))
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Delta** [comment]
Hi @fm-cl,
Just tried to test it on Magento 2.4.3, it works fine but i could not upgrade from  Magento 1.9.1.0.
![2 4 3_productCreated](https://user-images.githubusercontent.com/51681379/139839115-e22a3c8e-12db-4348-8864-d1830792641e.JPG)

![2 4 3_productCreated](https://user-images.githubusercontent.com/51681379/139839281-17ba0e6b-954f-435f-95dc-5e559a4a5326.JPG)

**Comment by engcom-Hotel** [comment]
Dear @fm-cl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
