### ISSUE TITLE
Admin panel copyright url http

### ISSUE THREAD

**Issue by Ylmzef** [magento/magento2#33993]
Please change copyright url from admin panel from http to https.
When ssl is enabled, it gives an error message from the browser.

https://github.com/magento/magento2/blob/6a0db3b86e0214eacdd1a3b47cca78bede766ca7/app/code/Magento/Backend/view/adminhtml/templates/page/copyright.phtml#L7

**Comment by Bashev** [comment]
What is the correct name here? - Magento or Adobe Commerce powered by Magento?

Second line also need to be updated. 

Is correct to change "Magento Commerce Inc." to "Adobe Inc." in the copyright line?

@magento-admin

**Comment by engcom-November** [comment]
Hi @Ylmzef ,
Thank you for reporting. However, the provided information is not enough for us to reproduce this issue. Kindly recheck the issue on Magento 2.4-develop branch and provide clear description of the issue if its still reproducible. Please update your issue description with below details:
    1. Steps to reproduce. 
    2. Expected and Actual Results. 
Thank you.

**Comment by engcom-November** [comment]
Hi @Ylmzef ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Comment by hostep** [comment]
Just for completeness sake, the issue that @Ylmzef tried to describe has to do withthe url on the logo in the footer of the backoffice of Magento. But I don't think it's a big problem, a fix would be very easy.

<img width="1020" alt="Screenshot 2021-09-21 at 19 01 54" src="https://user-images.githubusercontent.com/85479/134215420-d9f94122-35a3-49dc-9bf7-92ec0f5cc0db.png">
