### ISSUE TITLE
Filipino (philippines) language translation not working!

### ISSUE THREAD

**Issue by pawan** [magento/magento2#33996]
### Preconditions (*)

1. Magento 2.3, 2.4, 2.4-develop
2. Multi Store

### Steps to reproduce (*)

- Create a new store view for philippines i.e. philippines

- Go to system -> configuration -> change scope from Default to philippines store view

- Change locale to Filipino (Philippines)

- Install language pack for Filipino i.e. composer require mageplaza/magento-2-filipino-language-pack:dev-master Or can create a custom language pack

- Go to front-end and change Store view form Default to Philippines

### Expected result (*)

1. translation should work on frontend!

### Actual result (*)

exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vendor/mageplaza/magento-2-filipino-language-pack/language.xml" is invalid:
Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

Verify the XML and try again.
Exception #1 (Magento\Framework\Config\Dom\ValidationException): Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/html/m2-git/vendor/mageplaza/magento-2-filipino-language-pack/language.xml" is invalid:
Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

### Additional Information (*)

All other locale have code either az_AZ or  az_aAzZ_ZZ, only Filipino language have code `fil_PH` which is different form all other codes.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
@magento I am working on this

**Comment by Bashev** [comment]
@magento add to contributors team

**Comment by Bashev** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Added appropriate labels in order to create a JIRA ticket.

**Comment by sidolov** [comment]
Hi @pawan. Thank you for your report. 
The issue has been fixed in magento/magento2#34000 by @Bashev in 2.4-develop branch
Related commit(s):
 - [22b5f382e0ee00107a99e92cb405e3bf01ee1134](https://github.com/magento/magento2/commit/22b5f382e0ee00107a99e92cb405e3bf01ee1134)
 - [8801961bccde5a38fa4439adad48c9f5fc69139c](https://github.com/magento/magento2/commit/8801961bccde5a38fa4439adad48c9f5fc69139c)

The fix will be available with the upcoming 2.4.3 release.
