### ISSUE TITLE
New admin user created related mail notification

### ISSUE THREAD

**Issue by vibhavankhade** [magento/magento2#34006]
### Summary (*)

I have created a new admin from the backend but getting any mail related to that also new admin user notification template is showing in the Load default template

**Comment by engcom-Lima** [comment]
Hi @vibhavankhade,

Thank you for reporting the issue.

However, the provided info is not enough for us to reproduce this. It is always appreciated to have clear description of the issue. So kindly update your issue description with below details:

1) Steps to reproduce.
2) Expected and Actual Results.

We'll try to reproduce it on 2.4-develop instance then.

**Comment by engcom-Lima** [comment]
Hi @vibhavankhade,

We have noticed that this issue has not been updated for a some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
