### ISSUE TITLE
Fetch Currency Rates fails if multiple 'base' (from) currencies

### ISSUE THREAD

**Issue by marchharesoftware** [magento/magento2#34002]
### Preconditions (*)

1. Magento 2.3.7 (same code in Magento 2.4.3)
2.set up with currencies AUD, GBP, EUR, USD
3. configure fetch currencies with Currency Converter API 

![matrix-of-currencies](https://user-images.githubusercontent.com/38123089/132205726-56993c5b-4023-4228-a361-98b8d8908abc.jpg)

### Steps to reproduce (*)

1. use the currencies screen to fetch currencies.

```
We can't retrieve a rate from https://prepaid.currconv.com for AUD.
We can't retrieve a rate from https://prepaid.currconv.com for EUR.
We can't retrieve a rate from https://prepaid.currconv.com for GBP.
```

### Expected result (*)

1.  getServiceURL() in CurrencyConverterApi.php should calculate a new URL each time.
2. it should populate all the currency conversions

### Actual result (*)

1. convertBatch () in CurrencyConverterApi.php  is called repeatedly for each 'from' currency (string) and each 'to' currency (array of strings).
2. convertBatch () calls getServiceURL() in CurrencyConverterApi.php 
3.  getServiceURL() only calculates the URL if it is called the first time (and $serviceUrl is empty)
4. subsequent calls to  convertBatch () / getServiceURL() fail to get the conversion rates and produce the error:

We can't retrieve a rate from https://prepaid.currconv.com for AUD.
We can't retrieve a rate from https://prepaid.currconv.com for EUR.
We can't retrieve a rate from https://prepaid.currconv.com for GBP.

getServiceURL()  is called initially to get the URL for converting:
response EUR to AUD 
response EUR to EUR 
response EUR to GBP 
response EUR to USD

eg:

[https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=EUR_AUD,EUR_EUR,EUR_GBP,EUR_USD&compact=ultra](https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=EUR_AUD,EUR_EUR,EUR_GBP,EUR_USD&compact=ultra)

On the second pass getServiceURL()  is called to get the URL for converting:
response GBP to AUD 
response GBP to EUR 
response GBP to GBP 
response GBP to USD

So the URL should be:
[https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=GBP_AUD,GBP_EUR,GBP_GBP,GBP_USD&compact=ultra](https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=GBP_AUD,GBP_EUR,GBP_GBP,GBP_USD&compact=ultra)

But the SAME url is returned (because $serviceUrl  is not empty) so the URL is instead:
[https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=EUR_AUD,EUR_EUR,EUR_GBP,EUR_USD&compact=ultra](https://prepaid.currconv.com/api/v7/convert?apiKey=xxx&q=EUR_AUD,EUR_EUR,EUR_GBP,EUR_USD&compact=ultra)

The workaround is to manually enter the currency conversions.

Here is the fix I have implemented (including debugging messages):

```
***************
*** 22,28 ****
      /**
       * @var string
       */
!     public const CURRENCY_CONVERTER_URL = 'https://free.currconv.com/api/v7/convert?apiKey={{ACCESS_KEY}}'
          . '&q={{CURRENCY_RATES}}&compact=ultra';
  
      /**
--- 22,28 ----
      /**
       * @var string
       */
!     public const CURRENCY_CONVERTER_URL = 'https://prepaid.currconv.com/api/v7/convert?apiKey={{ACCESS_KEY}}'
          . '&q={{CURRENCY_RATES}}&compact=ultra';
  
      /**
***************
*** 117,123 ****
              } else {
                  if (!isset($response[$currencyFrom . '_' . $to])) {
                      $serviceHost =  $this->getServiceHost($url);
!                     $this->_messages[] = __('We can\'t retrieve a rate from %1 for %2.', $serviceHost, $to);
                      $data[$currencyFrom][$to] = null;
                  } else {
                      $data[$currencyFrom][$to] = $this->_numberFormat(
--- 117,123 ----
              } else {
                  if (!isset($response[$currencyFrom . '_' . $to])) {
                      $serviceHost =  $this->getServiceHost($url);
!                     $this->_messages[] = __('We can\'t retrieve a rate from %1 for %2 to %3.', $serviceHost, $currencyFrom, $to);
                      $data[$currencyFrom][$to] = null;
                  } else {
                      $data[$currencyFrom][$to] = $this->_numberFormat(
***************
*** 156,162 ****
       */
      private function getServiceURL(string $currencyFrom, array $currenciesTo): string
      {
-         if (!$this->serviceUrl) {
              // Get access key
              $accessKey = $this->scopeConfig
                  ->getValue('currency/currencyconverterapi/api_key', ScopeInterface::SCOPE_STORE);
--- 156,161 ----
***************
*** 175,181 ****
                  [$accessKey, $currencyRates],
                  self::CURRENCY_CONVERTER_URL
              );
-         }
          return $this->serviceUrl;
      }
  
--- 174,179 ----  
```
  
Note: CURRENCY_CONVERTER_URL - for me I had to change 'free' to 'prepaid' - I guess 'free' works for some users but 'prepaid' is needed for other users.  This probably needs two choices in the config 'are you using "Currency Converter API (Free)" or "Currency Converter API (prepaid)"?'.  I'm not sure if it warrants a whole other bug report/issue though...

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Severity: S1
Priority: P2

**Comment by engcom-Delta** [comment]
Hi @marchharesoftware ,
Kindly provide steps for setting up with currencies AUD, GBP, EUR, USD.so that we can reproduce it .

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
