### ISSUE TITLE
\Magento\Framework\Module\PackageInfo assumes locations

### ISSUE THREAD

**Issue by fooman** [magento/magento2#3400]
This code 

```
private function load()
{
    if ($this->packageModuleMap === null) {
        $jsonData = $this->reader->getComposerJsonFiles()->toArray();
        foreach ($this->componentRegistrar->getPaths(ComponentRegistrar::MODULE) as $moduleName => $moduleDir) {
            $key = $moduleDir . '/composer.json';
```

assumes that the registered path also holds the composer.json file which is not necessarily the case (for example https://github.com/fooman/sameorderinvoicenumber-m2/tree/v2.0.2/src). I am hoping there is a way to query composer itself for all packages of type magento2-module.

**Comment by davidverholen** [comment]
I'm not sure if you can query a composer instance for these paths, but it would be pretty easy to find them.

Since the composer.json is always in the root directory of the package, it just has to go to the parent dir until it finds the composer.json. 

This could be limited to the vendor dir, so that it does not go any higher in the directory structure. The vendor-dir can be read from the root composer.json (default: vendor)

**Comment by fooman** [comment]
I think the underlying problem is that Magento has an internal name for a module which is defined via `registration.php`. This definition is not formally tied to the composer name (it usually follows the convention `VendorName_ModuleName`), however for their own modules they employ some trickery here https://github.com/fooman/magento2/blob/1535766cb5d9146485793462c9cc9270c970cf0e/lib/internal/Magento/Framework/Module/PackageInfo.php#L177.

Just trialling something here https://github.com/magento/magento2/compare/develop...fooman:component-manager-reader-improvements?expand=1, where at least the parent dir is checked. It works but it's not quite right as this currently determines the name from the autoload section, and I think it would be better if it would get back the module name from the reader.

**Comment by davidverholen** [comment]
but, to read the module name from the composer.json, it would have first to know, where it is.
Currently, there is no direct connection between the registered component and a module.

Searching it in the parent dirs would work but also is not really nice.

It would be possible to create a map in the magento-composer-installer: composer-name to magento module name.

The it would be easy to find the composer.json

**Comment by fooman** [comment]
> but, to read the module name from the composer.json, it would have first to know, where it is.

That is what Magento currently tries to do, even though the `composer.json` name does not include the module name as it is known to Magento under.

> Currently, there is no direct connection between the registered component and a module.

This is the overall process of how I currently have it pieced together:

1.) Magento application gets started
2.) includes Composer autoload information
3.) Composer autoload files includes modules' `registration.php` files
4.) `registration.php` file registers module with the framework (`\Magento\Framework\Component\ComponentRegistrar`), information includes directory and chosen name (`Vendor_ModuleName`)
5.) When PackageInfo is called (from the Component Manager for example) it retrieves all modules and their registered directory. I then searches for a `composer.json` file in that folder.
6.) From that `composer.json` it will then reconstruct the [module name ](https://github.com/fooman/magento2/blob/1535766cb5d9146485793462c9cc9270c970cf0e/lib/internal/Magento/Framework/Module/PackageInfo.php#L177) and in addition also reads in the require, version and conflict section.

Overall there are a few things to note - between step 3.) and 4.) there is a disconnect between composer and Magento which in step 5 is brought back together based on the assumption that the location registered via `registration.php` also holds the composer.json file.

I have attached a screenshot with a problem of the current approach:

![component-manager](https://cloud.githubusercontent.com/assets/455508/13042237/7de8f312-d423-11e5-87b4-8ee8c5e41532.JPG)

I am currently thinking to make the ComponentRegistrar smarter by optionally allowing to register the composer name. And we could then query `composer.lock` for everything PackageInfo is looking for. Unfortunately there are also components which will never have a composer name so this needs to somehow be worked into it as well.

**Comment by buskamuza** [comment]
Internal ticket MAGETWO-49459

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-Framework-Module-PackageInfo-assumes-locations/idi-p/46417).
