### ISSUE TITLE
Composer patches

### ISSUE THREAD

**Issue by chaikivskyi** [magento/magento2#34011]
### Preconditions (*)

1. Magento 2.4.3
2. composer 2.1.6

### Steps to reproduce (*)

1. create a patch from git commit (https://github.com/magento/magento2/commit/9e7742e3f4f29b692453c9fdc563392e1dcf4f53.diff)
2. Remove path app/code/Magento/Csp from diff file
3. Add 
 ` "patches": {
            "magento/module-csp": {
                "Fix - 'frame-ancestors' does not support ''unsafe-inline'": "patches/composer/github-issue-33202-csp.diff"
            }
        }
` 
to composer.json
3. Try to apply patch with command `composer install -v`
### Expected result (*)

1. Successfully installed patch

### Actual result (*)

patch '-p1' --no-backup-if-mismatch -d '/var/www/html/vendor/magento/module-csp' < '/var/www/html/patches/composer/github-issue-33202-csp.diff'
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/etc/config.xml b/etc/config.xml
|index 07761995fdbc..3c4f5bda8805 100644
|--- a/etc/config.xml
|+++ b/etc/config.xml
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
S1
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@chaikivskyi: I've just tried it over here and it works perfectly fine.
I'm suspecting that your patch file might not be 100% correct, here's mine, maybe compare it with yours and see where it goes wrong:

```diff
diff --git a/etc/config.xml b/etc/config.xml
index 07761995fdbc..3c4f5bda8805 100644
--- a/etc/config.xml
+++ b/etc/config.xml
@@ -106,7 +106,7 @@
                     <frame-ancestors>
                         <policy_id>frame-ancestors</policy_id>
                         <self>1</self>
-                        <inline>1</inline>
+                        <inline>0</inline>
                         <eval>0</eval>
                         <dynamic>0</dynamic>
                     </frame-ancestors>
@@ -217,7 +217,7 @@
                     <frame-ancestors>
                         <policy_id>frame-ancestors</policy_id>
                         <self>1</self>
-                        <inline>1</inline>
+                        <inline>0</inline>
                         <eval>0</eval>
                         <dynamic>0</dynamic>
                     </frame-ancestors>

```

Also these sort of questions aren't about bugs in core Magento (which issues on github are meant for), so please next time ask these sort of questions on https://magento.stackexchange.com/ or https://community.magento.com/, thanks! 🙂

**Comment by chaikivskyi** [comment]
> @chaikivskyi: I've just tried it over here and it works perfectly fine.
> I'm suspecting that your patch file might not be 100% correct, here's mine, maybe compare it with yours and see where it goes wrong:
> 
> ```diff
> diff --git a/etc/config.xml b/etc/config.xml
> index 07761995fdbc..3c4f5bda8805 100644
> --- a/etc/config.xml
> +++ b/etc/config.xml
> @@ -106,7 +106,7 @@
>                      <frame-ancestors>
>                          <policy_id>frame-ancestors</policy_id>
>                          <self>1</self>
> -                        <inline>1</inline>
> +                        <inline>0</inline>
>                          <eval>0</eval>
>                          <dynamic>0</dynamic>
>                      </frame-ancestors>
> @@ -217,7 +217,7 @@
>                      <frame-ancestors>
>                          <policy_id>frame-ancestors</policy_id>
>                          <self>1</self>
> -                        <inline>1</inline>
> +                        <inline>0</inline>
>                          <eval>0</eval>
>                          <dynamic>0</dynamic>
>                      </frame-ancestors>
> ```
> 
> Also these sort of questions aren't about bugs in core Magento (which issues on github are meant for), so please next time ask these sort of questions on https://magento.stackexchange.com/ or https://community.magento.com/, thanks!

Your patch does not work for me also.
