### ISSUE TITLE
Magento should surpport products sold calculator

### ISSUE THREAD

**Issue by cha80** [magento/magento2#34023]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Delta** [comment]
Hi @engcom-Delta ,
Kindly provide issue description ,the steps to reproduce, actual results and expected results.

Thanks

**Comment by koushikch7** [comment]
@cha80 You can check the repository https://github.com/koushikch7/magento2-productSoldCount

**Comment by cha80** [comment]
OK

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
