### ISSUE TITLE
Better popup not working/showing

### ISSUE THREAD

**Issue by Alirazadar** [magento/magento2#34027]
### Preconditions (*)

1. Magento ver. 2.3.3
2. On extensions page

### Steps to reproduce (*)

1. I have installed better popup extension, but it is not showing on the page https://oliq.ch/
2.

### Expected result (*)

1. A popup to show for newsletter subscription
2. 

### Actual result (*)

1. Nothing, it does not show anything.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [S2 ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Lima** [comment]
Hi @Alirazadar,

This does not seem to be Magento Dev issue. This section is for reporting Dev related issues.

For the solution to your problem, you can check with Magento Support or report on various Magento Forums. Also please check with third party vendor from where you got the extension.

If you have Dev related issue, please update the description with relevant details. If not, we'll have to close this issue.

Thanks

**Comment by lbajsarowicz** [comment]
@Alirazadar How is that issue related to the Magento core?
