### ISSUE TITLE
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by carolinerenul** [magento/magento2#34049]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @carolinerenul 
Thank you for reporting. However, the provided information is not enough for us to reproduce this issue. Kindly recheck the issue on Magento 2.4-develop branch and provide clear description of the issue if its still reproducible. Please update your issue description with below details:
1. Steps to reproduce.
2. Expected and Actual Results.
Thank you.

**Comment by engcom-November** [comment]
Hi @carolinerenul ,

We are closing this issue as there has been no latest update on the same.
Thank you.
