### ISSUE TITLE
Cart Price Rules -  Uses per Coupon /  Uses per Customer not working

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#34065]
### Preconditions (*)

1. Magento 2.4-develop, 2.4.3
### Steps to reproduce (*)

1. Admin - Marketing - Cart Price Rules - Add New Rule - Create Specific Coupon , Customer Groups - Select All options except "Not Logged In" (exclude "Not Logged In")
Set Uses per Coupon  ,  Uses per Customer to 1 
Actions - Enter discount amount and Save
2. Reindex and clear cache
3. Front-end - Login using Customer which belong to any of the above configured Customer Group
4. Add product to Cart
5. Enter Discount code and proceed to checkout
6. Place Order - No issue: Discount applied and user is able to submit order
7. Add any product to cart again using same customer and apply coupon
**Issue**: There is no restriction on Coupon usage. User is able to apply coupon multiple times and place Order using same customer
DB tables - salesrule_coupon, salesrule  - "times_used" column is not getting updated even after using multiple times 
There is no entry in salesrule_coupon_usage table
### Expected result (*)

Coupon Usage must be restricted to logged-in customers
![image](https://user-images.githubusercontent.com/60198231/133081030-774e9a14-e4d6-4c3a-ad74-b3a2ca1a8eae.png)

### Actual result (*)

1. There is no restriction on Coupon usage. User is able to apply coupon multiple times and place Order using same customer
2. DB tables - salesrule_coupon, salesrule  - "times_used" column is not getting updated even after using multiple times 
There is no entry in salesrule_coupon_usage table
![image](https://user-images.githubusercontent.com/60198231/133068282-066144c9-92f9-4321-8f87-922da222f24d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
I have re-evaluated this issue and verified the same. Issue is reproducible on 2.4-develop.

Currently Coupon can be used n number of times per customer.

**Comment by glo05363** [comment]
In analysis with 2.4-develop i found out that sales.rule.update.coupon.usage is introduced under consumer queue to avoid deadlock under high load when a lot of concurrent orders are placed at the same time.
Follow all the steps to place order and run following consumer command:

bin/magento queue:consumers:start sales.rule.update.coupon.usage
The "salesrule_coupon_usage" table will get updated.

Now if you try using the same coupon , the coupon will state as invalid one.

**Comment by glo05363** [comment]
After Analysis with 2.4-develop we have found out that sales.rule.update.coupon.usage is introduced under consumer queue to avoid deadlock under high load when a lot of concurrent orders are placed at the same time.
Follow all the steps to place order and run following consumer command:

**bin/magento queue:consumers:start sales.rule.update.coupon.usage**

The "salesrule_coupon_usage" table will get updated.

Closing this as per above analysis.

**Comment by preeteshtavant** [comment]
@glo05363 
Why you clsoed this issue.
Do we need to run this command ever time or once.
Is it needs to run in prod also.

Is it different comapred to this https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/coupon-code-used-more-than-once-adobe-commerce.html?lang=en
