### ISSUE TITLE
Creditmemo field "Refund Shipping (Incl. Tax)" is assumed to be ex VAT

### ISSUE THREAD

**Issue by wouthoekstra** [magento/magento2#3406]
When Catalog prices and shipping prices are both set to 'including tax', the creditmemo form wrongly assumes that shipping amount is still excluding VAT.

Example:
- Set store->sale->tax->catalog prices and shipping prices tot including tax
- Create an order, selling something for €10,-, and default €5,- shipping costs
- Try to create creditmemo

In this last step I got the error "Maximum shipping amount allowed to refund is: €4.14". The creditmemo copies the values from the order, which has a value of €5,- for shipping. Magento 2 seems to assume this value is ex vat, and tries to add vat. When I manually change the value "Refund Shipping (Incl. Tax)" to €4.14, it works: Magento 2 adds €0.86 VAT which makes the shipping amount equal to that of the original order.

**Comment by tang-yu** [comment]
Thanks for submitting this bug. We have created internal ticket MAGETWO-49805 to track this issue.

**Comment by MomotenkoNatalia** [comment]
@wouthoekstra  Internal ticket MAGETWO-49805 is closed and delivered to mainline. Please let us know if you still have an issue.

**Comment by peterjaap** [comment]
@magento-engcom-team is there a commit reference available for this fix in the 2.3-develop branch?

**Comment by peterjaap** [comment]
@magento-engcom-team ping

**Comment by navidnadali** [comment]
@magento-engcom-team please can you update in RE to this bug? We have multiple customers affected by it
