### ISSUE TITLE
Price mismatch in frontend product search and product details pages

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#34074]
### Summary (*)
There is a price mismatch issue happening in Product search and detail page on frontend with multiple stores and Catalogue Price Scope is changed from Website to Global. Issue is specific to existing products before switching the scope.

### Preconditions (*)

1. Magento 2.4-develop
2. Multiple Websites/Stores are setup

### Steps to reproduce (*)

1. Setup multiple Magento Stores
2. Admin - Stores - Configuration - Catalog - Catalog - Set "Catalog Price Scope" to 'Website' and Save
3. Reindex and clear cache
4. Create a simple product which should be visible in all websites
5. Product edit page - Change the scope view to your website store, enter different price amount and save
6. Product edit page - Change the scope view to other store, enter different price and save
6. Reindex and clear cache
7. Frontend - Navigate to new Store website - **No issue**: Website Price is displayed in Catalog Search Results page and Product Details page
8. Admin - Stores - Configuration - Catalog - Catalog - Set "Catalog Price Scope" to "Global" and Save
9. Reindex and clear cache
10. Front end - New store view - Verify Product Price in Catalog Search Results page and Product Details page
**Issue**: Global Price is displayed in Catalog Search Results page whereas Website Price is displayed in Product Details page

### Expected result (*)

Global Price to be displayed in both Catalog Search Results page and product details page

### Actual result (*)

Global Price is displayed in Catalog Search Results page whereas Website Price is displayed in Product Details page

![image](https://user-images.githubusercontent.com/60198231/133241732-15eac45e-ad4f-4f4c-99be-4c6af62e69c1.png)
![image](https://user-images.githubusercontent.com/60198231/133241813-0d32bdd6-1abc-40a9-8a22-0d05e48fc64d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
I re-evaluated the issue and verified the same. Issue is reproducible on 2.4-develop instance.

**Comment by radu-work** [comment]
@magento I'm working on it

**Comment by engcom-November** [comment]
This issue got fixed in the scope of the internal Jira ticket `AC-1214` by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1214&type=commits

Based on Jira, target version is 2.4.5
