### ISSUE TITLE
Performance tool

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#3407]
While trying to use the new performance tool on a Magento 2.0.2 with Sample data I can only get a couple of admin requests and the test ends. Below is the command I'm using and the output and logs.

> michael@michael-HP-Pavilion-15-Notebook-PC:~/Downloads/apache-jmeter-2.13$ ./bin/jmeter -n -t bench.jmx -Jhost=xxxx.net -Jbase_path=/ -Jramp_period=3000 -Jreport_save_path=./ -Jguest_checkout_percent=4 -Jview_catalog_percent=62 -Jview_product_add_to_cart_percent=10 -Jorders=2000 -Jadmin_path=admin_41207x -Jadmin_user=admin -Jadmin_password=admin123 -Jloops=10
> Creating summariser <summary>
> 
> 
> Created the tree successfully using bench.jmx
> Starting the test @ Mon Feb 15 09:52:54 ART 2016 (1455540774295)
> Waiting for possible shutdown message on port 4445
> summary +      4 in     6s =    0.7/s Avg:  1457 Min:     8 Max:  3027 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
> summary +      3 in   8.3s =    0.4/s Avg:  2698 Min:  2205 Max:  2983 Err:     1 (33.33%) Active: 0 Started: 0 Finished: 0
> summary =      7 in  14.2s =    0.5/s Avg:  1989 Min:     8 Max:  3027 Err:     1 (14.29%)
> Tidying up ...    @ Mon Feb 15 09:53:08 ART 2016 (1455540788693)
> ... end of run

**Comment by miguelbalparda** [comment]
detailed-urls-report.log

> elapsed,label,grpThreads,allThreads,URL,SampleCount,ErrorCount,Hostname
> 8,SetUp - BeanShell Sampler: Clear properties,1,1,null,1,0,michael-HP-Pavilion-15-Notebook-PC
> 8,SetUp - BeanShell Sampler: validate user defined variables,1,1,null,1,0,michael-HP-Pavilion-15-Notebook-PC
> 3027,SetUp - Login,1,1,http://xxxx.net/admin_41207x/admin/index/index/key/36c48d64f4da89cdf3f8ac1708268520ea584f83bef664190041c618379a1040/,1,0,michael-HP-Pavilion-15-Notebook-PC
> 2786,SetUp - Login Submit Form,1,1,http://xxxx.net/admin_41207x/admin/dashboard/index/key/a5c11ab50b5184bb268118e3db799514bb292e454bd349ee98cf3f4bf8349387/,1,0,michael-HP-Pavilion-15-Notebook-PC
> 2205,SetUp - HTTP Request: Admin - Enable All Cache Types,1,1,http://xxxx.net/admin_41207x/admin/cache/index/key/83933f93392e32eee82f82fe9a72c12e0a630331d74bcd2c0153a7356f40df0d/,1,0,michael-HP-Pavilion-15-Notebook-PC
> 2983,SetUp - HTTP Request: Admin - Refresh All Cache Types,1,1,http://xxxx.net/admin_41207x/admin/cache/index/key/83933f93392e32eee82f82fe9a72c12e0a630331d74bcd2c0153a7356f40df0d/,1,0,michael-HP-Pavilion-15-Notebook-PC
> 2906,SetUp - HTTP Request - Cache Validation - All Enabled,1,1,http://xxxx.net/admin_41207x/admin/dashboard/index/key/a5c11ab50b5184bb268118e3db799514bb292e454bd349ee98cf3f4bf8349387/,1,1,michael-HP-Pavilion-15-Notebook-PC

**Comment by miguelbalparda** [comment]
summary-report.log

> 1455540774555,8,SetUp - BeanShell Sampler: Clear properties,200,OK,setUp Thread Group 1-1,text,true,0,1,1,0,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540774566,8,SetUp - BeanShell Sampler: validate user defined variables,200,OK,setUp Thread Group 1-1,text,true,0,1,1,0,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540774583,3027,SetUp - Login,200,OK,setUp Thread Group 1-1,text,true,3514,1,1,2030,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540777621,2786,SetUp - Login Submit Form,200,OK,setUp Thread Group 1-1,text,true,15013,1,1,989,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540780418,2205,SetUp - HTTP Request: Admin - Enable All Cache Types,200,OK,setUp Thread Group 1-1,text,true,15157,1,1,1196,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540782628,2983,SetUp - HTTP Request: Admin - Refresh All Cache Types,200,OK,setUp Thread Group 1-1,text,true,15198,1,1,981,1,0,michael-HP-Pavilion-15-Notebook-PC
> 1455540785710,2906,SetUp - HTTP Request - Cache Validation - All Enabled,200,OK,setUp Thread Group 1-1,text,false,15013,1,1,900,1,1,michael-HP-Pavilion-15-Notebook-PC

**Comment by okobchenko** [comment]
Hi, Miguelbalparda.

Performance toolkit scenarios are designed to work with generated store profiles only. To generate store fulfillment of certain size, please execute next command on empty Magento instance:

`php bin/magento setup:performance:generate-fixtures __PATH_TO_PROFILE_DEFINITION__`
All profiles can be found by next path: ..../setup/performance-toolkit/profiles/ce/

In order to use profiling toolkit in combination with Sample Data store or any custom store you should make corresponding changes to corresponding JMeter scenarios.

**Comment by hankzhh** [comment]
I have the similar issue, failed in "HTTP Request - Cache Validation - All Enabled" for testing the sample data.
Anyone have any tips to change the jMeter config to test with sample data?

edited:
it try to access GET ${base_path}${admin_path}/admin/cache/?form_key=4ukMSIZXkPGrNDpn
but for some reason it redirect to ${base_path}${admin_path}/admin//dashboard/index/key/???????????????????/
it looks "/key/???????????????????/" is not added to the first http request?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Performance-tool/idi-p/45319).
