### ISSUE TITLE
Cache lock issue

### ISSUE THREAD

**Issue by jonathanribas** [magento/magento2#34078]
### Preconditions (*)
1. Adobe Commerce 2.3.7 / 2.4.3

This one relates to the famous https://github.com/magento/magento2/pull/22829

### Steps to reproduce (*)
1. After a deployment, Adobe Commerce cache is emptied, having some concurrency on cache generation, it can lead to long running time saving keys.
2.  I've tested to kill PHP-FPM master process when SYSTEM CONFIG key was being generated on Redis cache. 

After killing it, I can still see the lock for SYSTEM CONFIG with a 7200 seconds TTL. During some minutes, it was very difficult to render a page on my local env as it keeps loading lock without any success:

1631628812.442996 [0 172.25.0.7:52150] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.443861 [0 172.25.0.7:52150] "hget" "zc:k:cad_LOCKED_RECORD_INFO_SYSTEM_CONFIG" "d"
1631628812.444582 [0 172.25.0.7:52162] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.445426 [0 172.25.0.7:52162] "hget" "zc:k:cad_LOCKED_RECORD_INFO_SYSTEM_CONFIG" "d"
1631628812.445471 [0 172.25.0.7:52120] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.445766 [0 172.25.0.7:52184] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.446496 [0 172.25.0.7:52120] "hget" "zc:k:cad_LOCKED_RECORD_INFO_SYSTEM_CONFIG" "d"
1631628812.446598 [0 172.25.0.7:52184] "hget" "zc:k:cad_LOCKED_RECORD_INFO_SYSTEM_CONFIG" "d"
1631628812.447747 [0 172.25.0.7:52088] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.448711 [0 172.25.0.7:52088] "hget" "zc:k:cad_LOCKED_RECORD_INFO_SYSTEM_CONFIG" "d"
1631628812.448845 [0 172.25.0.7:52146] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"
1631628812.448892 [0 172.25.0.7:52178] "hget" "zc:k:cad_SYSTEM_DEFAULT" "d"

I've decided to set expire manually to 20 seconds to that key and pages were generated immediately.

I think setting back `$defaultLifetime` to 10 seconds will maybe create another issue, I hope not as huge as this one.

Does someone know why lock TTL is set to 7200 seconds (2 hours) here https://github.com/magento/magento2/blame/2.4-develop/lib/internal/Magento/Framework/Lock/Backend/Cache.php#L46?

### Expected result (*)
1. Cache keys should generate without any issue even with concurrency
2. User Experience should not be impacted by cache key saving

### Actual result (*)
1.  After a deployment or during site life, sometimes (random) our end users are affected with more than 10 seconds loading time on several pages.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kandy** [comment]
@jonathanribas  W We don't recommend using `\Magento\Framework\Lock\Backend\Cache` implementation due to described problem. 
Can you check if this issue is reproduced with `\Magento\Framework\Lock\Backend\Database`?

**Comment by jonathanribas** [comment]
@kandy thanks for your help!

I've just tested `\Magento\Framework\Lock\Backend\Database` and now we have the following error on some homepage blocks (Page Builder):
`Error filtering template: Current connection is already holding lock for 9af174cd8e68c0ec0d719dd1cd00434, only single lock allowed`

**Comment by kandy** [comment]
@jonathanribas Yes, by default composer will overwrite the di.xml file
You also can specify adapter in env.php file. see https://github.com/magento/magento2/blob/2.3.7/lib/internal/Magento/Framework/Lock/LockBackendFactory.php#L98

if you think that there is no issue in 2.4.3 feel free to close the ticket ;)

**Comment by jonathanribas** [comment]
@kandy, great to know, thank you!

Closing this one at the moment, will reopen if we still have issues.

Thanks again.
