### ISSUE TITLE
Magento is still caching, even when cache is disabled

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#34083]
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

1. Disable Cache
2. Change something in a checkout template
3. Disable Browser Cache (network tab in chrome dev tools) and reload checkout

### Expected result (*)

1. Changes should show

### Actual result (*)

1. Changes not showing
2. Flush Cache
3. Changes are showing now.
Why do I need to flush the cache, even though it is disabled?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
from my exp magento have many levels of cache. Cache also come from server, opcache/php
Depends on what you want to change while development. If i working with phtml (disable block_html cache) may help. Same approach with xml (layout cache). After work done i re-enable again

**Comment by Eddcapone** [comment]
Yes, but I disabled all magento caches. It has nothing to do with server cache, but with magento cache, because it only works after I flush the magento cache.

**Comment by mrtuvn** [comment]
You changed file html in folder web ?

**Comment by Eddcapone** [comment]
I updated it in my theme folder or in app/code

**Comment by engcom-Delta** [comment]
Hi @Eddcapone,
Issue is not reproducible on Magento 2.4 Develop after we made changes in checkout template & save it .
Please find the attached snapshots. added 'Needs Update' label.
![disabled_cache](https://user-images.githubusercontent.com/51681379/134462460-c93aec3f-63b8-462b-ab59-95c0ce5452ad.JPG)
![checkout_template_changed](https://user-images.githubusercontent.com/51681379/134462480-4b57cc9b-9528-4d3b-afbe-1310196572cf.JPG)
![disabled_cache_browser](https://user-images.githubusercontent.com/51681379/134462495-594afc62-8cbd-48b1-b9c9-1087f0a12537.JPG)
thanks

**Comment by Eddcapone** [comment]
You need to change something in a template not in the config, to see the difference.

**Comment by mropanen** [comment]
I don't understand what engcom-Delta is trying to demonstrate in those screenshots, but anyway. 

Most likely when you're editing checkout templates, you're dealing with .html files, which are considered static content (their URI is something like domain.tld/**static/version1632380873**/frontend/..../template/meh.html)
The versionXXXX is what needs to change in the URI so that the template gets reloaded for sure.

This "deployment version" is stored in file pub/static/deployed_version.txt
Usually when I have to do frontend stuff, after changes I delete that file and everything in folder pub/static/frontend/

**Comment by mrtuvn** [comment]
The faster way you enable network tab in browser and reload that file modified

**Comment by mropanen** [comment]
You're right, I was thinking of CSS development with LESS, which is a bit different :)
