### ISSUE TITLE
Magento Swatches uses real stock instead of default stock to show red crossed in storefront

### ISSUE THREAD

**Issue by luisseidel** [magento/magento2#34087]
### Preconditions (*)

1. Magento 2.4.2 and 2.4.3 version.
2. Enable the option in Stores -> Configuration -> Catalog -> Inventory -> Stock Options -> Display Out of Stock Products.
3. Create a configurable product with a visual swatch or text swatch.

### Steps to reproduce (*)

1. Create a configurable product with a visual swatch or text swatch.
2. Put a quantity of 1 unit in any of the simple products option linked with this configurable product.
3. See the product in store front, and select the option.
4. Create an order with the product who has 1 unit.
5. Go back to the configurable product page in store front.

### Expected result (*)

1. When you make an order, the default stock of a product goes down.
2. After the order occours, when you visit the configurable product page, the swatch option who has 0 in default must be red crossed, to don't be selected anymore.

![image](https://user-images.githubusercontent.com/39092706/133491421-b630ad97-4a77-4a6c-ab95-e9af0b188924.png)

### Actual result (*)

1. Actualy, you can select the option even if the default stock is 0.
2. The red line only apperas when the order is completed, because magento decrement the real stock of the product to zero.
3. As you can see in the images below, the default stock is 0, but you can select the swatch and try to add to the cart again.

![image](https://user-images.githubusercontent.com/39092706/133492368-f6be5acd-12ba-4d8b-98e3-f374e56b0f53.png)

![image](https://user-images.githubusercontent.com/39092706/133492477-7bbb588c-1bd3-4162-bcb1-291f472480be.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by chequille** [comment]
@luisseidel
Hi,
do have the same problem.
There is already a pull request #33799

Here you can find a solution for the moment. It is not merged yet but it is working on my site.
Mayjor problem in 2.4.3 is, the function isSaleable is returning true if real stock is > 0 and not default qty > 0
This was solved with the change of class Magento/InventoryIndexer/Model/IsProductSalable.php
For configurables you have to change as well the function getOptions in Magento/ConfigurableProduct/Helper/Data.php

But here my version did solve it, not the given in the ticket.
```
	public function getOptions($currentProduct, $allowedProducts)
	{
		$options = [];
		$allowAttributes = $this->getAllowAttributes($currentProduct);
		
		foreach ($allowedProducts as $product) {
			$productId = $product->getId();
			foreach ($allowAttributes as $attribute) {
				$productAttribute = $attribute->getProductAttribute();
				$productAttributeId = $productAttribute->getId();
				$attributeValue = $product->getData($productAttribute->getAttributeCode());
				if ($this->canDisplayShowOutOfStockStatus()) {
					if ($product->isSalable()) {
						$options[$productAttributeId][$attributeValue][] = $productId;
						//$options[$productAttributeId][$attributeValue][] = $productId;
					}
					//$options[$productAttributeId][$attributeValue][] = $productId;
				} else {
					if ($product->isSalable()) {
						$options[$productAttributeId][$attributeValue][] = $productId;
					}
				}
				$options['index'][$productId][$productAttributeId] = $attributeValue;
			}
		}
		$options['canDisplayShowOutOfStockStatus'] = $this->canDisplayShowOutOfStockStatus();
		return $options;
	}
```

One problem left, as it is only working fine when the page of the product is not cached. That's still a problem to be solved. I did this with making one block of the product list page not cachable.

So three things to do:

- Change Magento/InventoryIndexer/Model/IsProductSalable.php as in the pull request
- Change getOptions in Magento/ConfigurableProduct/Helper/Data.php as above
- Make one block in product list not cachable

Would be good if you can test this as well and give some feedback here or in the pull request ticket.
They need to fix this now 100% as it is a mandatory functionality.

Best regards,
Chequille

**Comment by ajijshekh123** [comment]
Yes @chequille You are right. This issue is related to https://github.com/magento/magento2/issues/33799 your issue. 
@luisseidel - Can you please integrate the above code and let me know this issue is fixed or not and it's working as expected or not?

**Comment by chequille** [comment]
Hi Guys, just to say it again because it is important:

it is working as long as the page is not cached !!!!!!!!!
I made one block in catalog_view.xml layout file cachable="false"

If done so, it works for me.

Best regards,
Chequille

**Comment by engcom-Lima** [comment]
Hi @luisseidel,

This issue is duplicate to #33799 and so we are closing it. Please follow up on the other thread for issue's solution. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

You can also check @chequille's comment and see if helps. 

Regards
