### ISSUE TITLE
Configurable products price indexer not working

### ISSUE THREAD

**Issue by sheepfy** [magento/magento2#34086]
On vanilla magento with sample data, no multiinventory, config set to display out of stock products and global config of manage_stock = 0 (all products from sample data have use config for manage_stock). 

Reindex catalog_product_price - notice that we have price = 0, final_price = 0, min_price = X, max_price = Y

Go to a configurable product -> pick all of his children then set manage stock = 1 -> edit stock status to out of stock -> set manage stock back to 0 (or to use config manage stock). 

Reindex catalog_product_price - notice that we have price = final_price = min_price = max_price = 0.

Now other issues happens. Go to listing, sort by price ascending. Notice that 0 priced product is shown first. 

PS: Not sure if this happens with multiinventory too, but I'll leave to someone else to test it.

**Comment by orlangur** [comment]
@sheepfy 
> On vanilla magento with sample data, no multiinventory

This is not a valid setup as old inventory is deprecated.

**Comment by sheepfy** [comment]
@orlangur if that so, then why this was developed https://github.com/ magento/magento2/commit/a22010091673e485be42a2bd8097488d241da254 exactly 1 year - 2 days ago, when old inventory was deprecated at that time too ?

**Comment by sheepfy** [comment]
Also here https://github.com/magento/magento2/commit/7ee934df7e141f0b9285fc8ec3f1532e6f8f95ef last year.

**Comment by orlangur** [comment]
See here about deprecation https://devdocs.magento.com/guides/v2.4/inventory/inventory-api-reference.html#deprecated-modules.

However, logic you mentioned does not really seem to be related whether you use old inventory or a new one.

**Comment by slackerzz** [comment]
@orlangur The old inventory is deprecated but this doesn't mean it cannot be used. From wikipedia: 

> deprecation is a term for the discouragement of use of some terminology, feature, design, or practice, typically because it has been superseded or is no longer considered efficient or safe, without completely removing it or prohibiting its use

> While a deprecated software feature remains in the software, its use may raise warning messages recommending alternative practices. Deprecated status may also indicate the feature will be removed in the future. Features are deprecated, rather than immediately removed, to provide backward compatibility and to give programmers time to bring affected code into compliance with the new standard. 

Not everybody needs msi, it adds a layer of complexity. Not everybody needs the reservation system. Most of our customers handle inventory in external system and in this case the best thing to do is to remove msi instead of patching it to disable reservation.

Price sorting and filtering don't work as expected if you enable the option to show out of stock products becouse the index contains wrong data, as pointed by @sheepfy .

After reverting the changes of `app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/Indexer/Price/Configurable.php` done in 3487aff4175bdc5af289094503d9ef44f57723dc and 7ee934df7e141f0b9285fc8ec3f1532e6f8f95ef the indexer works as expected.

Here's the composer patch:
```
--- a/vendor/magento/module-configurable-product/Model/ResourceModel/Product/Indexer/Price/Configurable.php
+++ b/vendor/magento/module-configurable-product/Model/ResourceModel/Product/Indexer/Price/Configurable.php
@@ -7,7 +7,6 @@

 namespace Magento\ConfigurableProduct\Model\ResourceModel\Product\Indexer\Price;

-use Magento\Catalog\Model\ResourceModel\Product\BaseSelectProcessorInterface;
 use Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\BasePriceModifier;
 use Magento\Framework\DB\Select;
 use Magento\Framework\Indexer\DimensionalIndexerInterface;
@@ -17,8 +16,10 @@
 use Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\IndexTableStructureFactory;
 use Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\IndexTableStructure;
 use Magento\Framework\App\Config\ScopeConfigInterface;
+use Magento\Store\Model\ScopeInterface;
 use Magento\Framework\App\ObjectManager;
 use Magento\CatalogInventory\Model\Stock;
+use Magento\CatalogInventory\Model\Configuration;

 /**
  * Configurable Products Price Indexer Resource model
@@ -78,11 +79,6 @@
     private $scopeConfig;

     /**
-     * @var BaseSelectProcessorInterface
-     */
-    private $baseSelectProcessor;
-
-    /**
      * @param BaseFinalPrice $baseFinalPrice
      * @param IndexTableStructureFactory $indexTableStructureFactory
      * @param TableMaintainer $tableMaintainer
@@ -92,7 +88,6 @@
      * @param bool $fullReindexAction
      * @param string $connectionName
      * @param ScopeConfigInterface $scopeConfig
-     * @param BaseSelectProcessorInterface|null $baseSelectProcessor
      *
      * @SuppressWarnings(PHPMD.ExcessiveParameterList)
      */
@@ -105,8 +100,7 @@
         BasePriceModifier $basePriceModifier,
         $fullReindexAction = false,
         $connectionName = 'indexer',
-        ScopeConfigInterface $scopeConfig = null,
-        ?BaseSelectProcessorInterface $baseSelectProcessor = null
+        ScopeConfigInterface $scopeConfig = null
     ) {
         $this->baseFinalPrice = $baseFinalPrice;
         $this->indexTableStructureFactory = $indexTableStructureFactory;
@@ -117,8 +111,6 @@
         $this->fullReindexAction = $fullReindexAction;
         $this->basePriceModifier = $basePriceModifier;
         $this->scopeConfig = $scopeConfig ?: ObjectManager::getInstance()->get(ScopeConfigInterface::class);
-        $this->baseSelectProcessor = $baseSelectProcessor ?:
-            ObjectManager::getInstance()->get(BaseSelectProcessorInterface::class);
     }

     /**
@@ -211,7 +203,15 @@
             []
         );

-        $this->baseSelectProcessor->process($select);
+        // Does not make sense to extend query if out of stock products won't appear in tables for indexing
+        if ($this->isConfigShowOutOfStock()) {
+            $select->join(
+                ['si' => $this->getTable('cataloginventory_stock_item')],
+                'si.product_id = l.product_id',
+                []
+            );
+            $select->where('si.is_in_stock = ?', Stock::STOCK_IN_STOCK);
+        }

         $select->columns(
             [
@@ -300,4 +300,17 @@
     {
         return $this->resource->getTableName($tableName, $this->connectionName);
     }
+
+    /**
+     * Is flag Show Out Of Stock setted
+     *
+     * @return bool
+     */
+    private function isConfigShowOutOfStock(): bool
+    {
+        return $this->scopeConfig->isSetFlag(
+            Configuration::XML_PATH_SHOW_OUT_OF_STOCK,
+            ScopeInterface::SCOPE_STORE
+        );
+    }
 }

```
