### ISSUE TITLE
The problem with sprintf(Magento\Framwork\Phrase()) construction in PHP >= 8

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34085]
### Description (*)
We found a problem with `sprintf(__())` and `sprintf(Magento\Framwork\Phrase())` construction in PHP >= 8.
The error looks like "Expected parameter of type 'string', 'Magento\Framework\Phrase' provided".
This problem should be found and fixed in Magento codebase.
Currently, there are about 20 problems with provided constructions.

We need to change constructions to `sprintf(__()->render())`.

**Comment by xmav** [comment]
@magento export issue to Jira project AC as Story
