### ISSUE TITLE
Retry Failed Send sits there and does nothing.

### ISSUE THREAD

**Issue by Any-Documentation-Would-be-Great** [magento/magento2#34081]
### Preconditions (*)

1. Ver. 2.3.6
2. ERP Order Information

### Steps to reproduce (*)

1. Have an Order set to 'ERP Error' by your system failing to send
2. Manually change that to 'Error - Retry Attempt Failure'
3. Refresh for an hour waiting for Magento to do literally anything with this new information

### Expected result (*)

1.  RETRY SENDING THE ORDER MAYBE?

### Actual result (*)

1. Order never retries sending 
2. 'Retry Count' number never updates from N/A
3. 
![image](https://user-images.githubusercontent.com/90729445/133339794-dbf13cc9-41cb-499c-9d24-4b13d37c7e4f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Hotel** [comment]
Dear @Any-Documentation-Would-be-Great,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards
