### ISSUE TITLE
Update `phpgt/dom` composer dependency for `magento/magento2-page-builder` extension

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34096]
We checked fatal errors with environment PHP 8.
One of the problems is incompatible composer dependency - `phpgt/dom` in `magento/magento2-page-builder` extension.
We need to upgrade `phpgt/dom` composer dependency to the next versions `"~2.2.1||~3.0.0"` and check it again.

### Expected result (*)

1. The system has no fatal errors

### Actual result (*)

1. Declaration of Gt\Dom\ChildNode::before(DOMNode $node): void must be compatible with DOMElement::before(...$nodes): void in /var/www/html/vendor/phpgt/dom/src/Element.php on line 29

**Comment by xmav** [comment]
@magento export issue to Jira project AC as Story

**Comment by andrewbess** [comment]
Changes have been delivered
