### ISSUE TITLE
Database gets full locking/deadlock when use READ COMMITTED

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#34090]
We have a site (multiple websites) running with much traffic all time.
On a day, we changed the tx isolation mode to READ COMMITTED, everything was still working fine. 
On next day the problem seems to happen when we deploy new version, the database start getting locking and deadlock very fast (we tried multiple times and same problem happened)

So we had to change back to the default mode. 

### Preconditions (*)

1. Version 2.4.3
2. Mysql tx isolation READ COMMITTED (mysql 5.7)

### Steps to reproduce (*)

1. Flushing whole cache and varnish
2. Send some concurrent traffic (both frontend and backend)

### Expected result (*)

Everything should work normally with any tx isolation mode, the site shouldn't be down

### Actual result (*)

![image](https://user-images.githubusercontent.com/22501570/133543218-f361c7e8-66ef-4f8e-982c-fd2803e89415.png)
![image](https://user-images.githubusercontent.com/22501570/133543233-41d5f897-8402-40dd-b538-2d9185377821.png)
![image](https://user-images.githubusercontent.com/22501570/133543253-cc995ea8-fc8b-4ae0-8f8a-07a318b1a1df.png)
![image](https://user-images.githubusercontent.com/22501570/133543552-322f0d6c-39fd-473a-bccb-865c8883ee2f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by onlinebizsoft** [comment]
@hostep you may hear about this ever?

**Comment by hostep** [comment]
Sorry, I have no experience with these different mysql transaction isolation levels. If it's not working, it probably means Magento was not tested or designed with that in mind...

**Comment by cmuench** [comment]
We have a good experience with this setting. It's also set in Magento Cloud environments as default.

**Comment by engcom-Lima** [comment]
Hi @onlinebizsoft 

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
