### ISSUE TITLE
Database Error while creating Bundle products in community2.4.3 instance

### ISSUE THREAD

**Issue by dinesh6686** [magento/magento2#34102]
After updating the Magento2 community edition from the version. 2.4.2-p1 to 2.4.3, while creating a bundle item( which includes single/multiple simple items that are already present in the instance catalog) we see the below error:

**SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'selection_price_type' cannot be null, query was: INSERT  INTO `catalog_product_bundle_selection_price` (`selection_id`,`website_id`,`selection_price_type`,`selection_price_value`,`parent_product_id`) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `selection_price_type` = VALUES(`selection_price_type`), `selection_price_value` = VALUES(`selection_price_value`)**

### Preconditions (*)

1. Update Magento2 community edition to version 2.4.3
2.  Try creating a bundle item using API call with URL having any storeview in it(Working as expected for 'all' storeviews and bundle product is getting created in the instance)

### Steps to reproduce (*)

1. Error appears when we try to make a PUT call from the postman to create a bundle item in magento2 community243 instance.
2. URL should contain any one of the storeview codes in it other than 'all'

### Expected result (*)

1. Bundle item should get created successfully for the URLs having storeview codes as well in it.

### Actual result (*)

![com243bundle](https://user-images.githubusercontent.com/24934652/133660672-25454b8d-fc4c-40f4-90fe-c4baa7be95da.png)

---

[ ] Severity: S0 _- Affects critical data or functionality and leaves users without workaround.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4.3 version after upgrading from 2.4.2-P1 and unable to reproduce the issue:

**Steps performed:**
Upgraded Magento 2.4.2-P1 version to 2.4.3 using composer
`composer require magento/product-community-edition 2.4.3 --no-update`
`composer update`
`php bin/magento setup:upgrade`
Rest API - generate Admin access token using /rest/default/V1/integration/admin/token
Send POST request to /rest/default/V1/products/   to create Bundle Product - No issue. Bundle product is created
Send PUT request to /rest/default/V1/products/test4  to update Bundle product - No issue: Bundle Product is updated
Send PUT request to  /rest/default/V1/products/reergrgrge to create new Bundle product - No issue. Bundle product is created.
![image](https://user-images.githubusercontent.com/60198231/134174230-3c46d2e8-97ac-426f-851d-1334d6ce099d.png)

Payload used:
`
{
  "product": {
   "id": 9,
    "sku": "reergrgrge",
    "name": "reergrgrge",
    "attribute_set_id": 4,
    "price": 35,
    "status": 1,
    "visibility": 4,
    "type_id": "bundle",
    "created_at": "2021-09-21 12:42:22",
    "updated_at": "2021-09-21 12:42:22",
    "weight": 10,
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "stock_item": {
            "item_id": 9,
            "product_id": 9,
            "stock_id": 1,
            "qty": 2,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        },
        "bundle_product_options": [
            {
                "option_id": 5,
                "title": "Container Type",
                "required": true,
                "type": "select",
                "position": 0,
                "sku": "reergrgrge",
                "product_links": [
                    {
                        "id": "9",
                        "sku": "simpleww",
                        "option_id": 5,
                        "qty": 2,
                        "position": 0,
                        "is_default": false,
                        "price": 45,
                        "price_type": null,
                        "can_change_quantity": 0
                    },
                    {
                        "id": "10",
                        "sku": "testproduct",
                        "option_id": 5,
                        "qty": 2,
                        "position": 1,
                        "is_default": false,
                        "price": 50,
                        "price_type": null,
                        "can_change_quantity": 0
                    }
                ]
            }
        ]
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "shipment_type",
            "value": "0"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "url_key",
            "value": "reergrgrge"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "price_view",
            "value": "0"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "sku_type",
            "value": "0"
        },
        {
            "attribute_code": "price_type",
            "value": "0"
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "weight_type",
            "value": "0"
        },
        {
            "attribute_code": "category_ids",
            "value": []
        }
    ]
  },
  "saveOptions": true
}
`
Kindly recheck the issue again on Magento 2.4-develop branch or provide missing steps if any if the issue is still reproducible on 2.4.3.
Thank you.
