### ISSUE TITLE
Product saleability status incorrect after reindex

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#34107]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Product salability is same before and after reindex.
Verified the same using Get API calls:
/rest/V1/inventory/is-product-salable/salableproduct/3
/rest/V1/inventory/get-product-salable-quantity/salableproduct/3
@dphilipps kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by dphilipps** [comment]
Hi 
The issues occurs after reindexing in the following scenario:

Purchase all salable stock for a product (e.g. all 100), then stock_status column is correctly automatically set to 0 in the cataloginventory_stock_status table. The view inventory_stock_1 reflects this accordingly in the 'is_salable' column.  The product (in the case of a configurable) then shows this option as crossed out (or missing if a dropdown).  All good.

Runing php bin/magento indexer:reindex from the command line (or cron) will revert all unsalable products so they appear in stock on the front end of the store. 'is_salable' column is then reverted to '1' in the cataloginventory_stock_status table and the  view inventory_stock_1 will reflect this changed value too, hence the product is showing as in stock and salable.

Relates to https://github.com/magento/magento2/issues/33799

**Comment by swleighton** [comment]
@magento give me 2.4.3 instance with edition ee

**Comment by swleighton** [comment]
@magento give me 2.4.3 instance with edition ee

**Comment by swleighton** [comment]
@magento give me 2.4.3 instance

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by dphilipps** [comment]
> Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
> Product salability is same before and after reindex.
> Verified the same using Get API calls:
> /rest/V1/inventory/is-product-salable/salableproduct/3
> /rest/V1/inventory/get-product-salable-quantity/salableproduct/3
> @dphilipps kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps to reproduce if the issue is still reproducible.
> Thank you.

@engcom-November Thank you for trying to reproduce this issue.  I've now spent further time looking into the issue and have closed this issue written up a complete bug report in a new ticket.  I'm confident you'll be able to reproduce the problem in the current branch following the steps I've provided.  Would you be able to look at this ticket please as the issue has been affecting our customers for 9 months now: https://github.com/magento/magento2/issues/34127?

**Comment by nkajic** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by nkajic** [comment]
https://github.com/magento give me 2.4.3 instance

**Comment by nkajic** [comment]
@magento give me 2.4-develop instance
