### ISSUE TITLE
URL product and URL category suffix

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3410]
For some reason if the product or category suffix is changed. In settings -> Catalog -> Catalog -> SEO.
The administrator wil get the warning that their is a table missing:

__Something went wrong: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_db.url_rewrite' doesn't exist, query was: UPDATE `url_rewrite` SET `request_path` = ? WHERE (`url_rewrite_id` = 4382)_
_

This has something todo with the basetable suffix, because the search doesn't add this suffix xx_ to the mysql query.
When the tablename is changed and the suffix is deleted, than the administrator will get another error that the table with suffix is missing.

I hope somebody knows a solution for this problemen

Magento 2.0.2 CE

**Comment by anvanza** [comment]
This is related to issue [#3013](https://github.com/magento/magento2/issues/3013)

**Comment by ghost** [comment]
thanks Anvanza!
