### ISSUE TITLE
widget block title seem not update as expected with low lifetime cache

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#34129]
### Summary (*)

My test case

Step 1
Default theme set to luma
Create widget show products list type for theme and display only in product detail for "Joust Duffle Bag"
1.1 Type: Catalog Products List
1.2 Design Package/Theme: Luma theme
1.3 Assign to Store Views: All Store Views
1.4 Layout Updates: All product types
Specific Products: choose "Joust Duffle Bag"
Container: Main Container Bottom
Widget options: Choose default to make sure all critieria meet and valid widget to show
Add some title for block
widget option Cache Lifetime (Seconds) set to 100 (seconds)
Save widget
Flush cache

Go  to frontend visual widget title update show correct title set in backed

Step 2
Now back to backend and edit previous widget
But we change title again to another text
widget option Cache Lifetime (Seconds) set to 1(second) or 2
Save widget
At this time we don't flush cache 

Go back to Joust Duffle Bag and visual title again

Expected results
Text updated after few second

Actually results
No update text

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @mrtuvn,

Thank you for reporting the issue. 

Although I understand the issue expected and actual results which you might be getting but some of the steps to reproduce the issue are not clear.

Would you be willing to share widget code of your test case ? Maybe I'll get more clarity then.

Thanks

**Comment by mrtuvn** [comment]
No need code here you can add widget if you have installed sample data

**Comment by engcom-Lima** [comment]
Hi @mrtuvn,

Thanks for the update.

However I tried to reproduce same on 2.4-develop but text got updated on frontend once I edited the widget title and cache lifetime also without cache flush as you suggested. Please find the below screenshots of the changed title.

<img width="1324" alt="Screenshot 2021-09-23 at 3 59 44 PM" src="https://user-images.githubusercontent.com/60198022/134494554-dc460c73-f50f-467e-8118-6fb6c654e186.png">

<img width="1428" alt="Screenshot 2021-09-23 at 4 07 29 PM" src="https://user-images.githubusercontent.com/60198022/134494587-19d114c3-901f-41ca-9b72-c1a9badf75c5.png">

So, can you please update if you found this issue on 2.4-develop instance or any other specific version ? Or can you please update what you did differently ?

**Comment by engcom-Lima** [comment]
Hi @mrtuvn,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Feel free to reopen this ticket with more details if still think it is an issue.

Regards
