### ISSUE TITLE
Do not allow user access by default

### ISSUE THREAD

**Issue by brideo** [magento/magento2#3412]
`Magento\Backend\Controller\Adminhtml\Index`

```
/**
 * Check if user has permissions to access this controller
 *
 * @return bool
 */
protected function _isAllowed()
{
    return true;
}
```

Should this return false?

**Comment by veloraven** [comment]
@brideo is this issue still actual?

**Comment by brideo** [comment]
https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/Controller/Adminhtml/Index.php#L22

Appears to be.

**Comment by dmitriyprime** [comment]
Unfortunately, I could not reproduce the issue as you described it. Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by korostii** [comment]
This is getting ridiculous.

Hi @dmitriyprime, have you actually verified that the `Magento\Backend\Controller\AdminhtmlIndex::_isAllowed()` method is returning `false` instead? Otherwise I fail to understand what you were trying to reproduce, exactly.

**Comment by brideo** [comment]
I'm probably not going to update this with steps to reproduce, feel free to close this issue.
