### ISSUE TITLE
Magento Graph QL :  router query cms-page caching issue

### ISSUE THREAD

**Issue by chanforix** [magento/magento2#34121]
Steps to Reproduce:

1. http://{{base_url}}/graphql?query={route(url: "cms-page-identifier") {__typename relative_url redirect_code type ... on CmsPage { identifier url_key title content content_heading page_layout meta_title meta_description meta_keywords}}}
2. Call this graphql again. But caching not working.

Expected result (*) :

1. The second call. The content should get in caching.

Also, i change this code
vendor/magento/module-cms-url-rewrite-graph-ql/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php:26
From

> public function getIdentities(array $resolvedData): array
    {
        $ids = [];
        if (isset($resolvedData['id'])) {
            $selectedCacheTag = $this->cacheTag;
            $ids =  [$selectedCacheTag, sprintf('%s_%s', $selectedCacheTag, $resolvedData['id'])];
        }
        return $ids;
    }

To

> public function getIdentities(array $resolvedData): array
    {
        $ids = [];
        if (isset($resolvedData['page_id'])) {
            $selectedCacheTag = $this->cacheTag;
            $ids =  [$selectedCacheTag, sprintf('%s_%s', $selectedCacheTag, $resolvedData['page_id'])];
        }
        return $ids;
    }

It works correctly.

**Comment by engcom-Delta** [comment]
Hi @chanforix ,

Thank you for raising an issue , we are happy to work on this issue . Kindly provide clear issue description , actual results with screenshots or logs.

Regards,

**Comment by engcom-Hotel** [comment]
Dear @chanforix,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
