### ISSUE TITLE
Frontend Prices is 0 After upgrading from 2.4.2 to 2.4.3

### ISSUE THREAD

**Issue by mohammadzahwy2017** [magento/magento2#34139]
### Preconditions (*)

1. Magento Version 2.4.3
2. Upgrade My Application from Version 2.4.2 to 2.4.3 Using Composer

### Steps to reproduce (*)

1. Upgrade Magento Version from 2.4.2 to 2.4.3
2. When open and product page the price appears normal then when the page completely loaded the price transferred to 0
3. When open checkout all shipping prices and product prices appears 0

Note : I install a clean Magento Version then install my themes and modules with an empty database and create some demo products till here everything is working fine but when I change the database to the main one and run the commands to upgrade it then the error mentioned in point 2 and 3 occured.

### Expected result (*)

1. Magento with Version 2.4.2 [https://prnt.sc/1t7h967](https://prnt.sc/1t7h967)

### Actual result (*)

1. Magento with Version 2.4.3 [https://prnt.sc/1t7hfzc](https://prnt.sc/1t7hfzc)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by mohammadzahwy2017** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
Hi @mohammadzahwy2017,
This is a duplicate of https://github.com/magento/magento2/issues/33798 which still not fixed yet.

As a temporary workaround, you can apply the following patch: https://github.com/magento/magento2/issues/33856#issuecomment-904606945
