### ISSUE TITLE
Cannot open the front end or back end after successful install. 404 error

### ISSUE THREAD

**Issue by Devabby** [magento/magento2#3413]
OS: Windows 7
WAMP Server 2.5

hello 
I have installed Magento 2.0 without any errors. The DB are populated with the tables and sample data. However I cannot open the front end nor the back end using http://Localhost/mystore and http://Localhost/mystore/admin

Installation process
1) composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition Magento2

2) php <your Magento install dir>/bin/magento sampledata:deploy

3) Setup Wizard. http://Localhost/magento2/setup

INSTALLED SUCCESSFULLY.

This is the error I get.
Not Found
The requested URL /magento/ was not found on this server.
Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

What am i missing?

Any help will be appreciated.
Thanks
Abby

**Comment by mazhalai** [comment]
Please do not use [localhost](http://alankent.me/2015/04/25/use-of-localhost-when-installing-magento-2-quick-note/). Your domain needs at least one `.`
