### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by florin221123432211** [magento/magento2#34145]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by florin221123432211** [comment]
One or more indexers are invalid. Make sure your Magento cron job is running.

**Comment by krishprakash** [comment]
@florin221123432211 
Feel free to reopen the issue once you update all necessary details as per [issue reporting guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Thanks
