### ISSUE TITLE
Fixed Product Price added twice in cart cart subtotal.

### ISSUE THREAD

**Issue by magentoTraining** [magento/magento2#34141]
Fixed Product Price added twice in cart cart subtotal.

### Preconditions (*)
1. Magento version 2.3.5
2.

### Steps to reproduce (*)
1. Enable Fixed Product Tax from backend Admin >> configuration >> Sales >> Tax 
![FPT Enable](https://user-images.githubusercontent.com/78601937/134343073-13e838e3-ae27-49b0-b186-b1dd8b0a674d.png)

2. Create an product attribute  for Fixed Product Tax Catalog Type
3. Assign that attribute into any attribute set.
4. Configure any product and assign any amount of Fixed Product Tax.
5. Create and configure Fixed Product Tax class
6. Use this Price Display Settings and Shopping Bag Display Setting
![Price Display Settings](https://user-images.githubusercontent.com/78601937/134345113-474fe5af-9323-449e-ae82-bdb9298c95f3.png)
 
7. In My case Product Price is : 220.77
8. Fixed Product Tax is : 39.23
9. Price show in subtotal : 299.23 

### Expected result (*)
1.Tax should be added once 
2. Price should show in subtotal : 260.00 

### Actual result (*)
1. Tax applied twice
2. Price is showing in subtotal in both mini cart and checkout screen : 299.23 
![Checkout Screen](https://user-images.githubusercontent.com/78601937/134346831-1a5a3de6-dad3-4c08-a19f-eeae0eceeb5e.png)
 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @magentoTraining. Thank you for your report.
Not able to replicate the issue as provided steps by you
Feel free to reopen the issue once you confirm issue reproduce in latest magento instance
Thanks
