### ISSUE TITLE
Error during the cancelling sales order with cart price rule applied

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#34167]
### Preconditions (*)

1. Magento 2.4.3 CE
2. Native M2 sample data installed

### Steps to reproduce (*)

1. Create the cart price rule: no coupon, auto-applying for the product A (let's say for example), some discount is applied (let's say, 15%)
2. Go to the storefront and add to the shopping cart product A
3. Check, that the cart price rule from  step 1 is applied
4. Place an order, use "Check/Money order" payment method (I suppose, the bug can be reproduced for any other payment method)
5. In the backend, open newly created sales order
6. Cancel this sales order

### Expected result (*)

1. Sales order cancelling is processed correctly, with no errors occured

### Actual result (*)

1. An error message appears "You have not canceled the item."
2. Corresponding sales order item has status "Cancelled"
3. 
![image](https://user-images.githubusercontent.com/24728606/134865665-45ea0501-7dff-41e0-bf4c-c9245055466a.png)
4. [exception.log](https://github.com/magento/magento2/files/7234307/exception.log)

---

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment]
Hi @avgust1111. Not able to replicate the issue as provided steps by you.

![image](https://user-images.githubusercontent.com/46617848/134894594-f80619fe-3e66-4ef7-81b6-733edbfbd742.png)

Can you please confirm the issue on latest magento instance
Thanks

**Comment by avgust1111** [comment]
Hello
I've just verified the described flow within your test environment (https://7819294f9e05404d25287c695ecac8b7-2-4-develop.instances.magento-community.engineering/) and it seems like the bug isn't reproduced on the latest M2 version for develop
But I believe, the issue can be reproduced on M2.4.3

**Comment by krishprakash** [comment]
Hi @avgust1111. Thanks for the prompt response.
We only approve/Confirm issue which reproduce on latest instance.
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem.
Thanks.
