### ISSUE TITLE
i add  giftmessage form attribute "my_test" when i click updte button return 500 error

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#3416]
POST http://127.0.0.1/m202/rest/default/V1/carts/mine/gift-message 500 (Internal Server Error)
Property "MyTest" does not have corresponding setter in class "Magento\GiftMessage\Api\Data\MessageInterface".

but i have already add extension_attributes.xml code 
 <extension_attributes for="Magento\GiftMessage\Api\Data\MessageInterface">
        <attribute code="my_test" type="string" />
    </extension_attributes>

**Comment by ishakhsuvarov** [comment]
@LifeAsBook Please clear Magento caches and try again. If the issue persists, please let us know what did you add to `extension_attributes.xml` and which payload are you using for the `POST` request.

**Comment by LifeAsBook** [comment]
@ishakhsuvarov my mean is  if i have to extension_attributes that "my_test" , should i  use "my_test" or "extension_attributes"  in the front form name?

**Comment by ishakhsuvarov** [comment]
@LifeAsBook If I understand you correctly it should be "my_test" under "extension_attributes", however code sample would be helpful to clarify things.

**Comment by LifeAsBook** [comment]
@ishakhsuvarov 
![q1](https://cloud.githubusercontent.com/assets/10986726/13247693/cad8168e-da55-11e5-8174-8e5eaedc326a.jpg)
![q2](https://cloud.githubusercontent.com/assets/10986726/13247702/d4c2b35c-da55-11e5-828d-80dd6242297e.jpg)

![q3](https://cloud.githubusercontent.com/assets/10986726/13248003/289c022a-da57-11e5-8206-89ef033e4ff0.jpg)

this updte button is call http://127.0.0.1/m202/rest/default/V1/carts/mine/gift-message
and method is Magento\GiftMessage\Api\CartRepositoryInterface::save($cartId, \Magento\GiftMessage\Api\Data\MessageInterface $giftMessage);

I'm sorry extension_attributes is not extends_attribute

**Comment by veloraven** [comment]
@LifeAsBook is this issue still actual?
If it is please specify Magento version.
If it is not please close this ticket.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
