### ISSUE TITLE
Stabilize Static Tests

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#34188]
https://github.com/magento/magento2
https://github.com/magento/partners-magento2ee
https://github.com/magento/partners-magento2b2b
https://github.com/magento/partners-magento2-infrastructure
https://github.com/magento/magento2-sample-data
AC:

Static test build is green (PHP 7.4 & PHP 8.0)
Fix functional issues that cause failed tests
The result of composer install command is green with PHP 7.4 and PHP 8.0
\Magento\Test\Integrity\ComposerTest::testValidComposerJson() is green

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by xmav** [comment]
@magento export issue to Jira project AC as Story
