### ISSUE TITLE
Error css when create new theme

### ISSUE THREAD

**Issue by tungmpo** [magento/magento2#3418]
Hi,
When I create  new theme and run it , some file weren't generated  as styles-m.css, styles-l.css
Anyone can help me ? 

Thank You!

**Comment by mrkhoa99** [comment]
Hi,
You tried to run deploy content command under Magento root folder: `php bin/magento setup:static-content:deploy`

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by tungmpo** [comment]
Thank you so much!  Your solution have helped me solved problem

The reason is   @copyright__background-color  wasn't  defined  before   :)
