### ISSUE TITLE
isMenuFixed in theme-adminhtml-backend bug

### ISSUE THREAD

**Issue by proseLA** [magento/magento2#34183]
i can not see when you would ever want this to be false.

whenever this returns false, the header for the actual data starts below the menu.  having this always return true provides desired format.  unless someone can show me otherwise.

https://github.com/magento/magento2/blob/44a7b6079bcac5ba92040b16f4f74024b4f34d09/app/design/adminhtml/Magento/backend/web/js/theme.js#L27-L33

![image](https://user-images.githubusercontent.com/1095136/135142505-1125723b-1bb9-4430-86ab-f91acdbd73fb.png)

**Comment by engcom-Delta** [comment]
Hi @proseLA  ,
Kindly provide detailed issue description ,steps to reproduce , actual results and  expected results. So that we can reproduce it.
Hence added the label 'Needs Update'.
Thanks

**Comment by proseLA** [comment]
hi @engcom-Delta,

- this is a vanilla install of 2.4.3.  i have not tried on 2.4-develop.  once i get my magento foo a bit stronger i will reproduce on 2.4-develop.
- there is no sample data loaded.  no modifications whatsoever.
- i have logged into the admin side, again with no modifications.
- the format on the admin dashboard is fine.
- as an example, i then click content -> configuration to bring me to: http://mag/index.php/admin/theme/design_config/index/key/longKey/#
- at this point, there is 1 `div` on the page with a class of `menu-wrapper`
- the content of the page, not the menu, is now completely off.  the menu looks fine, but the content is too far to the left under the menu, and there is far too much padding at the top.
- if that same `div` (no id) had the class of `_fixed` in there, the content looks completely fine and is how it should be.
- that node should be `<div class="menu-wrapper _fixed" style="top: 0px;">`
- i have narrowed the problem done to the javascript method in the title of this issue.  whenever that method returns false for any admin page, the lineup is the same.  left margin not enough; top padding too much.
-  i am on a 32" monitor in landscape mode with a resolution of 2560 x 1440.
- any admin page where the javascript function `isMenuFixed` returns false exhibits the same behavior.
- using developer tools on chrome i have reproduced the same issue with various mobile devices.

hope that helps.

**Comment by engcom-Delta** [comment]
Hi @proseLA,
Thanks for providing detailed info. it would be great help if you can provide screenshots.
Regards,

**Comment by proseLA** [comment]
attached are 2 screenshots.  they are both of the catalog products page.  the first one is unmodified out of the box.  the second screenshot, i changed the `isMenuFixed` javascript function to return true.  all i did was modify the static theme.js file.  i took no action at all using the magento cli to clear cache or regenerate static content, etc.
![catalog_product_unmodified](https://user-images.githubusercontent.com/1095136/135663957-877a3230-e229-4f78-9488-be64fb0c1042.png)
![catalog_product_isMenuFixed_true](https://user-images.githubusercontent.com/1095136/135663980-f0d8b6d5-f10c-4359-8817-7d010141a490.png)

**Comment by engcom-Alfa** [comment]
We have to reproduce it from our end once before confirming the issue! Hence moving back to the pervious stages.
Thanks for your patience!

**Comment by engcom-Hotel** [comment]
Hello @proseLA,

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, this is not reproducible. Please have a look at the below video for reference:
https://user-images.githubusercontent.com/51681618/140289752-f5b31864-bda0-488f-a02e-f0e5f96b5cdd.mov

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @proseLA,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by JoostWan** [comment]
This is still an issue. We can reproduce it on 2.4.3-p2

**Comment by creativebay** [comment]
I can also confirm that the issue still exists on 2.4.5

**Comment by engcom-Hotel** [comment]
Hello @JoostWan @creativebay,

As we can see that you are still able to reproduce the issue. Can you please let us know something more about this issue, like below:
1. Any steps
2. Console logs
3. Screenshots
4. Screen size

Thanks
