### ISSUE TITLE
KEEP GETTING KICKED OUT OF MAGENTO ADMIN - EXTREMELY FRUSTRATING - FIX ASAP!!!!!

### ISSUE THREAD

**Issue by pdeboolw** [magento/magento2#34201]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. LOG IN TO ADMIN
2. DO A SEARCH
3. SWITCH OUT OF TO EXCEL OR EMAIL, ETC
4. TRY DOING ANOTHER SEARCH
2. 
3. 

### Expected result (*)

1. I SHOULD NOT GET KICKED BACK TO THE LOGIN PAGE EVERY TIME

### Actual result (*)

1.GETTING KICKED OUT AND BACK TO THE LOGIN SCREEN
[Admin error.docx](https://github.com/magento/magento2/files/7255412/Admin.error.docx)

**Comment by cjnewbs** [comment]
@pdeboolw this looks like it may be a configuration issue with your store. I just took a look at your admin login page and the cookie it sets for the admin session expires pretty much immediately. Take a look at this page and check if the admin session lifetime is set correctly. https://docs.magento.com/user-guide/stores/admin-session-lifetime.html
<img width="448" alt="Screenshot 2021-10-02 at 19 05 16" src="https://user-images.githubusercontent.com/1676494/135727360-ddd46f9e-0fb7-42ff-9915-57c471ad33af.png">

**Comment by Bashev** [comment]
See here #33748

**Comment by pdeboolw** [comment]
Thank you very much!

**Comment by pdeboolw** [comment]
Question from our web technical team:

Inside of Magento, the admin cookie settings are already set to the max which is one year. However default cookie settings have the cookie restriction mode turned off. IS THIS something that needs to be turned on? I think that it is the bar that shows a button for accepting cookie settings. It is possible that the cookie settings hard coded in the backend which we do not have access to or just like the advanced reporting, there might be a bug that is causing the cookie settings in the admin side from getting to the backend.


Go with the blessings of God!!

Philip DeBoo ***@***.******@***.***>)
Bill Winston Ministries<https://www.billwinston.org/home/> / Living Word Christian Center<https://www.livingwd.org/lwcc-home/>



From: DeBoo, Philip
Sent: Monday, October 4, 2021 9:53 AM
To: 'magento/magento2' ***@***.***>; magento/magento2 ***@***.***>
Cc: Mention ***@***.***>; LWCC Analysts ***@***.***>
Subject: RE: [magento/magento2] KEEP GETTING KICKED OUT OF MAGENTO ADMIN - EXTREMELY FRUSTRATING - FIX ASAP!!!!! (#34201)

Thank you very much!

**Comment by pdeboolw** [comment]
Forgot to include screenshot:

***@***.***

From: DeBoo, Philip
Sent: Monday, October 4, 2021 12:02 PM
To: 'magento/magento2' ***@***.***>; 'magento/magento2' ***@***.***>
Cc: 'Mention' ***@***.***>; LWCC Analysts ***@***.***>; 'Debajyoti N' ***@***.***>
Subject: RE: [magento/magento2] KEEP GETTING KICKED OUT OF MAGENTO ADMIN - EXTREMELY FRUSTRATING - FIX ASAP!!!!! (#34201)

Question from our web technical team:

Inside of Magento, the admin cookie settings are already set to the max which is one year. However default cookie settings have the cookie restriction mode turned off. IS THIS something that needs to be turned on? I think that it is the bar that shows a button for accepting cookie settings. It is possible that the cookie settings hard coded in the backend which we do not have access to or just like the advanced reporting, there might be a bug that is causing the cookie settings in the admin side from getting to the backend.


Go with the blessings of God!!

Philip DeBoo ***@***.******@***.***>)
Bill Winston Ministries<https://www.billwinston.org/home/> / Living Word Christian Center<https://www.livingwd.org/lwcc-home/>



From: DeBoo, Philip
Sent: Monday, October 4, 2021 9:53 AM
To: 'magento/magento2' ***@***.******@***.***>>; magento/magento2 ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; LWCC Analysts ***@***.******@***.***>>
Subject: RE: [magento/magento2] KEEP GETTING KICKED OUT OF MAGENTO ADMIN - EXTREMELY FRUSTRATING - FIX ASAP!!!!! (#34201)

Thank you very much!

**Comment by engcom-Delta** [comment]
Hi @pdeboolw,
is this issue resolved ? Please confirm.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has fixed as per recent comments.
 so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
