### ISSUE TITLE
Category page crashes when "Equalize product counts" price navigation step calculation is chosen

### ISSUE THREAD

**Issue by tatiana-scandi** [magento/magento2#34218]
### Preconditions (*)

1. Magento 2.4.3
2. In magento admin navigate to Stores -> Configuration -> Catalog -> Inventory, select "Display Out of Stock Products"  = "Yes"
3. In magento admin navigate to Stores -> Configuration -> Catalog -> Catalog, select "Price Navigation Step Calculation" = "Automatic (equalize product counts)"
4. Create 1 configurable product, for which all options are out of stock. Add this product to "Men -> Bottoms" category
5. Create 10 simple products, all costing 5 USD, in the "Men -> Bottoms" category

### Steps to reproduce (*)

1. Open category, into which products from preconditions were added

### Expected result (*)

1. Category page should be loaded, price layered navigation should work

### Actual result (*)

1. Error `Notice: Undefined variable: from in /home/tappiola/PhpstormProjects/catalog-graphql/src/SearchAdapter/Aggregation/Interval.php on line 130` is thrown. Full stack trace:
```
Exception #0 (Exception): Notice: Undefined variable: from in /home/tappiola/PhpstormProjects/magento-20210921-pmrev/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php on line 131
<pre>#1 Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Aggregation\Interval->loadPrevious() called at [vendor/magento/framework/Search/Dynamic/Algorithm.php:309]
#2 Magento\Framework\Search\Dynamic\Algorithm->_findValueSeparator() called at [vendor/magento/framework/Search/Dynamic/Algorithm.php:179]
#3 Magento\Framework\Search\Dynamic\Algorithm->calculateSeparators() called at [vendor/magento/framework/Search/Dynamic/Algorithm/Improved.php:70]
#4 Magento\Framework\Search\Dynamic\Algorithm\Improved->getItems() called at [vendor/magento/module-elasticsearch/SearchAdapter/Aggregation/Builder/Dynamic.php:48]
#5 Magento\Elasticsearch\SearchAdapter\Aggregation\Builder\Dynamic->build() called at [vendor/magento/module-elasticsearch/SearchAdapter/Aggregation/Builder.php:89]
#6 Magento\Elasticsearch\SearchAdapter\Aggregation\Builder->build() called at [vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php:128]
#7 Magento\Elasticsearch7\SearchAdapter\Adapter->query() called at [vendor/magento/module-search/Model/SearchEngine.php:42]
#8 Magento\Search\Model\SearchEngine->search() called at [vendor/magento/framework/Search/Search.php:85]
#9 Magento\Framework\Search\Search->search() called at [vendor/magento/module-catalog-search/Model/ResourceModel/Fulltext/Collection.php:465]
#10 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection->_renderFiltersBefore() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:343]
#11 Magento\Framework\Data\Collection\AbstractDb->_renderFilters() called at [vendor/magento/module-catalog-search/Model/ResourceModel/Fulltext/Collection.php:583]
#12 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection->_renderFilters() called at [vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:926]
#13 Magento\Eav\Model\Entity\Collection\AbstractCollection->load() called at [vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php:833]
#14 Magento\Catalog\Model\ResourceModel\Product\Collection->load() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection/Interceptor.php:23]
#18 Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\Interceptor->load() called at [vendor/magento/module-catalog/Block/Product/ListProduct.php:205]
#19 Magento\Catalog\Block\Product\ListProduct->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1113]
#20 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1118]
#21 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:678]
#22 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#23 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#25 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:525]
#26 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [vendor/magento/module-catalog/Block/Category/View.php:100]
#27 Magento\Catalog\Block\Category\View->getProductListHtml() called at [vendor/magento/module-catalog/view/frontend/templates/category/products.phtml:15]
#28 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
```

This issue happens due to unhanded condition in the `loadPrevious()` method: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php#L130

If either `$lower` is `null` or `0`, variable `$from` becomes undefined. I noticed case when `null` is being passed as value for `$lower` here: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Search/Dynamic/Algorithm.php#L309 , via `$this->_lowerLimit`. Value of field `$this->_lowerLimit` equals to 0, if search results from elasticsearch include any product with price = 0. It's possible to get such product in the index, if you create configurable product, for which all configurations are out of stock (but configurable product itself is enabled and marked as in stock). Logic, which sets `$this->_lowerLimit` equal to `null`, when cheapest product returned in aggregation has 0 price, sits here: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Search/Dynamic/Algorithm/Improved.php#L67. Method `$this->algorithm->setLimits();` sets `$this->_lowerLimit` to `null`, if `$aggregations['min']` is zero:
```
    public function setLimits($lowerLimit = null, $upperLimit = null)
    {
        $this->_lowerLimit = empty($lowerLimit) ? null : (double)$lowerLimit;
        $this->_upperLimit = empty($upperLimit) ? null : (double)$upperLimit;

        return $this;
    }
```

Second condition for getting this issue is presence of group of products having same price. In this case, `if` condition in this line returns true (it compares first and last value from the interval): https://github.com/magento/magento2/blob/202bd44c84c86f60004dcbd7fa1fc17e5b3623a4/lib/internal/Magento/Framework/Search/Dynamic/Algorithm.php#L307. This way, method `$interval->loadPrevious($lastValue, $quantileInterval[0], $this->_lowerLimit)` is being executed, with `$this->_lowerLimit` being equal to `null`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tatiana-scandi** [comment]
@magento give me 2.4-develop instance

**Comment by tatiana-scandi** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @tatiana-scandi,
Tried to reproduce the issue on Magento 2 .4 Develop . it is not reproducible . Hence adding the label 'Needs Update'.
Please help us to reproduce it or try to replicate on latest Magento 2.4 Develop branch from your end as it is latest version.

![product_inCategory](https://user-images.githubusercontent.com/51681379/135870816-b4826ae1-2ad0-4f95-96e8-bd41b66862b3.JPG)

**Comment by joinso** [comment]
Same issue with this conditions:
1.- Magento ver. 2.3.5
2.- In magento admin navigate to Stores -> Configuration -> Catalog -> Inventory, select "Display Out of Stock Products" = "Yes"
3.- In magento admin navigate to Stores -> Configuration -> Catalog -> Catalog, select "Price Navigation Step Calculation" = "Automatic (equalize product counts)"
4.- Just only Virtual products.
Error:
Notice: Undefined variable: from in /var/app/current/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php on line 131.

A live example:
https://www.icreatia.es/software/render/v-ray?software_magento2=1167
This are the values of parameters:
data:84.55
index:1
lower: <--- null
Pleas, reopen the issue.
