### ISSUE TITLE
Magento\Framework\View\Element\Html\Link generates automatically slash at the end

### ISSUE THREAD

**Issue by in-session** [magento/magento2#34227]
When using the Link current class, a slash is automatically created at the end of the link. 
Although the forwarding runs without suffix, it would be unnecessary to have a forwarding here. 
Also here it would be good to control the CMS pages by the suffix setting.
This should happen depending on additional seo setting, so that allways the same suffix are given:

![image](https://user-images.githubusercontent.com/16542619/135716927-6af0158b-845a-4c19-b573-63063d69f3a1.png)
![image](https://user-images.githubusercontent.com/16542619/135717555-ae4bb5df-31b4-49e6-8841-220b5fc666e3.png)

**Comment by engcom-Lima** [comment]
Hi @in-session,

Thank you for reporting the issue. 

However the provided description is not clear enough to understand what is the issue that you are facing. So below are some of the points which can help us in understanding and reproducing this issue:
1. Magento Version on which you are facing the issue.
2. Clear 'Steps to reproduce' will make it easy for us to reproduce this.
2. Expected and Actual results of the issue.

Please update the description with above points and any other information would be appreciated and we'll do further analysis acocrdingly.
