### ISSUE TITLE
setup:install fails if console command that injects Customer model class exists

### ISSUE THREAD

**Issue by Revengance1024** [magento/magento2#34220]
### Preconditions (*)

1. Magento Community 2.4.2 (possibly earlier versions affected)
2. Custom console command that has Customer model (directly or indirectly) injected in constructor
3. Database tables not yet created (install hasn't been run yet)

### Steps to reproduce (*)

1. Create custom module
2. Add custom console command that injects \Magento\Customer\Model\ResourceModel\Customer (directly or via another class, e.g. CustomerRepository)
2. Run setup:install. For example:
```
setup:install
--base-url=https://local.magento.com/
--db-host=127.0.0.1
--db-name=magento
--db-user=magento
--db-password=magento
--admin-firstname=Admin
--admin-lastname=User
--admin-email=example@example.com
--admin-user=admin
--admin-password=admin123
--language=en_US
--currency=USD
--timezone=America/Chicago
--use-rewrites=1
-vvv
```

### Expected result (*)

1. setup:install completes without issues

### Actual result (*)

1. setup:install fails during step 4 (Installing database schema) with error
```
[Magento\Framework\DB\Adapter\TableNotFoundException (1146)]                                                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.eav_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_type` AS `main_table`
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Revengance1024** [comment]
This issue is caused by \Magento\Customer\Model\ResourceModel\Customer calling `$this->setType('customer');` in constructor (vendor/magento/module-customer/Model/ResourceModel/Customer.php:87).

For anyone currently facing this issue there are 2 workarounds:
- Disable the custom module before install, run install, re-enable the module and run setup:upgrade
- Add dependencies that directly or indirectly inject Customer model as proxies. For example, if Foo/Bar/Console/Command/TestCommand has \Magento\Customer\Api\CustomerRepositoryInterface (argument name customerRepository) as a dependency (CustomerRepository has Customer Resource Model as a dependency), then you could add this in di.xml
```
    <type name="Foo/Bar/Console/Command/TestCommand">
        <arguments>
            <argument name="customerRepository" xsi:type="object">Magento\Customer\Api\CustomerRepositoryInterface\Proxy</argument>
        </arguments>
    </type>
```

**Comment by engcom-Hotel** [comment]
Hello @Revengance1024,

Thanks for posting this issue!

But can you please let us know any specific use case to create a custom module before installing Magento?

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Revengance1024,

We have tried to reproduce the issue on Magento 2.4-develop, but we are getting another error, not the same you are getting. Please have a look at the below screenshot:
![error](https://user-images.githubusercontent.com/51681618/138254632-fad23d10-c068-40b3-a3a2-d4363240abc9.jpg)

Please find attached the custom module, we have made in order to reproduce the issue:
[Magz_ConsoleCmd.tar.gz](https://github.com/magento/magento2/files/7387946/Magz_ConsoleCmd.tar.gz)

Please let us know in case we have missed any steps in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Revengance1024,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
