### ISSUE TITLE
Erro na instalação do magento via composer - (HTTP / 2 404)

### ISSUE THREAD

**Issue by MayaraNovais** [magento/magento2#34222]
[Composer\Downloader\TransportException]                                                                                                          
  The "https://repo.magento.com/archives/ricardomartins/pagseguro/ricardomartins-pagseguro-2.9.7.0.zip" file could not be downloaded (HTTP/2 404 )

**Comment by engcom-Delta** [comment]
Hi @MayaraNovais,
Kindly provide clear description of issue , steps to reproduce ,actual results with screenshots and expected results.
Hence added the label 'Needs Update'.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
