### ISSUE TITLE
Cannot save view in Catalog->Products

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#3422]
I have added a few extra properties to the default property set, now I cannot select which columns to be shown and save the view. I get an "Attention Something went wrong." message.

**Comment by antboiko** [comment]
Hi @bgabrovsek , thanks for your inquiry.

Could you please provide more details? Some screenshots would be really helpful.

Best,
Anton.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by chapa38** [comment]
I cant see the products in the catalog, why?
The message say:
Add Product 
Can't check requested quantity for products without Source Items support.

??
