### ISSUE TITLE
Configurable products has zero price (in product view) after Locale is changed to Greek.

### ISSUE THREAD

**Issue by konstantinos158358** [magento/magento2#34229]
### Preconditions (*)

1. Plesk Obsidian 18.0.38
2. Magento Open Source 2.4.3
3. Php 7.4.23
4. Select English (United State) Locale from Stores --> Configuration --> General --> General (http://prntscr.com/1un7u6e)

### Steps to reproduce (*)

1. Change Catalog Input Type for Store Owner to Visual Swatch, for product attribute color (http://prntscr.com/1un5ram)
2. Create some options (http://prntscr.com/1un5v29) 
3. Add new configurable product from admin area (http://prntscr.com/1un63k5)
4. Add sample data to parent product(http://prntscr.com/1un6cec)
5. Create configurations

> - Select attribute color and click Next
> - Select all attribute values and click next
> - Skip image uploading for all SKUs
> - Apply single price to all SKUs (e.g: 50)
> - Apply single quantity to each SKUs (e.g: 120) and click Next
> - Click Generate Products

6. Save product (http://prntscr.com/1un7092)	
7. As a result the price of each product seems to be normal (http://prntscr.com/1un8fr9 , http://prntscr.com/1un8i11)
8. Change store locale from English (United State) to Greek (Greece) : http://prntscr.com/1un8o7r
9. Flush Magento Cache

### Expected result (*)

The product prices should be the same with the result of English Locale (http://prntscr.com/1un8fr9 , http://prntscr.com/1un8i11)

### Actual result (*)

All prices are zero (http://prntscr.com/1un9h1e , http://prntscr.com/1un9ii1)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by konstantinos158358** [comment]
@magento give me 2.4-develop instance

**Comment by Bashev** [comment]
Looks like to be related to #33798  #33856 #33910 #34139 #34156

**Comment by ihor-sviziev** [comment]
@konstantinos158358,
As a temporary workaround, you can apply the following patch: https://github.com/magento/magento2/issues/33856#issuecomment-904606945
