### ISSUE TITLE
After magento upgrade 2.3.2 to 2.4.3 Invalid parameter configuration provided for $configPaths argument

### ISSUE THREAD

**Issue by vibhavankhade** [magento/magento2#34235]
### General (*)
 Magento version: 2.4.3
 PHP version: 7.4

### Summary (*)

Magento2.3.2 to Magento 2.4.3 upgrade successfully but when I edit cms block getting an error

{"0":"Invalid parameter configuration provided for $configPaths argument of Magento\\Variable\\Model\\Source\\Variables","1":"#1 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:239]\n#2

### Proposed solution
 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by GalileoWebagentur** [comment]
@vibhavankhade Do a full text search for "_Magento\Variable\Model\Source\Variables_" and locate the extensions, that still use this. In our case it was firegento/magesetup, which I then upgraded to ^1.0, to solve the problem by the module using "Magento\Variable\Model\Config\Structure\AvailableVariables" instead

**Comment by DivyaSCeymox** [comment]
> @vibhavankhade Do a full text search for "_Magento\Variable\Model\Source\Variables_" and locate the extensions, that still use this. In our case it was firegento/magesetup, which I then upgraded to ^1.0, to solve the problem by the module using "Magento\Variable\Model\Config\Structure\AvailableVariables" instead

Its doesn't work dependency field in the system configuration. Its reflect [2022-12-02 07:55:15] main.CRITICAL: Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/local.m2/app/code/Magento/Config/Model/Config/Structure/AbstractMapper.php on line 33 {"exception":"[object] (Exception(code: 0): Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/local.m2/app/code/Magento/Config/Model/Config/Structure/AbstractMapper.php on line 33 at /var/www/html/local.m2/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
