### ISSUE TITLE
Klarna logs: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_id' in 'where clause'

### ISSUE THREAD

**Issue by arsalanworld** [magento/magento2#34236]
### Preconditions (*)

1. Magento 2.4.3
2. Cron jobs are enabled
3. Debug log is enabled
4. Make sure there is a payment done using Klarna payment method.
### Steps to reproduce (*)

1. Run the cron jobs and notice it during midnight at 12AM in `var/log/debug.log` log file
2. Or create an object to "Klarna\Core\Cron\CleanLogs" class and try accessing the "execute" method.

### Expected result (*)

1. The cron Jobs should run without an exception
2. The retrieved logs should be deleted.

### Actual result (*)

1. An exception is thrown: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_id' in 'where clause' query was: SELECT COUNT(*) FROM `klarna_logs` AS `main_table` WHERE (`store_id` = '1') AND (`created_at` <= '2021-07-06')
Exception (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_id' in 'where clause'

![Screenshot from 2021-10-04 17-04-24](https://user-images.githubusercontent.com/7779579/135848649-6d268de2-f466-43cb-9675-cdc195dc8bba.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by arsalanworld** [comment]
@magento I am working on this

**Comment by arsalanworld** [comment]
@magento add to contributors team

**Comment by ihor-sviziev** [comment]
@magento/klarna could someone look on it?

**Comment by engcom-Hotel** [comment]
Hello @arsalanworld,

Thanks for reporting the issue. We have tried to reproduce the issue with the above-mentioned steps and are able to reproduce it by making the object of `Klarna\Core\Cron\CleanLogs` and call the `execute` method. 

Please find below the screenshot for reference:

![Untitled](https://user-images.githubusercontent.com/51681618/136043997-81e5c367-6b5a-441b-88b3-96502c9e7610.jpg)

Thanks

**Comment by ralbin** [comment]
I have a brand new Adobe commerce cloud project version 2.4.3 that shows the exact same errors.  When I review the structure of the table `klarna_logs` it is missing the column store_id.
`MariaDB [main]> DESCRIBE klarna_logs;
+--------------+--------------+------+-----+---------------------+----------------+
| Field        | Type         | Null | Key | Default             | Extra          |
+--------------+--------------+------+-----+---------------------+----------------+
| log_id       | smallint(6)  | NO   | PRI | NULL                | auto_increment |
| status       | varchar(255) | NO   |     | NULL                |                |
| action       | varchar(255) | YES  | MUL | NULL                |                |
| klarna_id    | varchar(255) | YES  | MUL | NULL                |                |
| increment_id | varchar(255) | YES  |     | NULL                |                |
| url          | varchar(255) | NO   |     | NULL                |                |
| method       | varchar(255) | NO   |     | NULL                |                |
| service      | varchar(255) | NO   |     | NULL                |                |
| request      | text         | YES  |     | NULL                |                |
| response     | text         | YES  |     | NULL                |                |
| created_at   | datetime     | NO   |     | current_timestamp() |                |
+--------------+--------------+------+-----+---------------------+----------------+
11 rows in set (0.00 sec)`

**Comment by engcom-Hotel** [comment]
Hello @arsalanworld,

As Klarna is not part of the bundled extension now, we are marking this issue as 3rd party extension. Hence closing this issue.

Thanks
