### ISSUE TITLE
Cant install Magento 2 with CLI

### ISSUE THREAD

**Issue by anjenehm** [magento/magento2#3424]
I cant install magento 2 with shell on my webserver...

"bin/magento must be run as a CLI application"

i tryed to install it with a browser and the install stucked at several times 37%, 73% and so on...

i set the permissions to the folder and files like its written on the tutorial http://devdocs.magento.com/guides/v2.0/install-gde/prereq/zip_install.html

on my local mamp installation everthing works fine so i upload a dump to my server and mysql fixed the routes but get only 500 errors... ( i think i will try to fix that version cause it was the first time i reached the frontend (with no css an js) on my server ) 

maybe some one can really helps me :(

**Comment by anjenehm** [comment]
Wow 100% with browser installer..
But after the successful installation i get only 500 errors..

**Comment by anjenehm** [comment]
okay i changed the mod_rewrite

<IfModule mod_rewrite.c>

############################################

## enable rewrites

```
Options +FollowSymLinks
RewriteEngine On
```

to RewriteEngine Off

now i get 404 errors :o

**Comment by ghost** [comment]
Do you see logs that explain the 500 errors? Look in Magento's `var/log` directory and in your web server's logs. Please post details.

**Comment by anjenehm** [comment]
[2016-02-17 15:31:41] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://mydomain.com/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []

**Comment by mazhalai** [comment]
@anjenehm anything in error log as "CRITICAL" ?
what about apache logs?

**Comment by anjenehm** [comment]
[2016-02-18 15:05:32] main.CRITICAL: Could not determine temp directory, please specify a cache_dir manually [] []

**Comment by anjenehm** [comment]
I update the: lib/internal/Cm/Cache/Backend and a File.php
with 'cache_dir' => 'var/tmp/', doesn't help .... 

i cleared the cache logs and only that message in debug.log appears

[2016-02-19 08:15:30] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://mydomain.com/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []

**Comment by anjenehm** [comment]
1. Upload the zip file to the target directory.
2. Unzip the zip on the server
3. Adjustment of DBValidator.php file under setup / src / Magento / Setup / Validator
   private function check database privileges (\ Magento \ Framework \ DB \ Adapters \ Adapter interface $ connection, $ dbName) {return true;
4. Allocation of the file and folder permissions (660 files and folders 770)
5. executing the setup through the browser
6. After successful installation, no styles are available css or js files are not loaded. Backend (admin) points to a 500 error.
7. adjust the .htaccess file Options + FollowSymLinks RewriteEngine On Options + FollowSymLinks RewriteEngine to Off 404 errors the files. Backend still can not be called. Deploying 8. Static files via cli CLI php5-55STABLE bin / magento setup: static-content: deploy 9. Deletion of Cache folder 10.Reload the Page. Still 404 error pages and files.

**Comment by mazhalai** [comment]
@anjenehm 
- why do you need step 3? 
- also, recommended permissions are not 660, and 770. Please see [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)
- did you check file permissions after static content deploy?

**Comment by anjenehm** [comment]
Cause my Server Provider told me to do step 3 (cause he cant change to the newest mysql version)
(So what did you think should i buy a managed mage2 server ?)

so what? 
All directories have 770 permissions.
770 permissions give full control (that is, read/write/execute) to the owner and to the group and no permissions to anyone else.
All files have 660 permissions.
660 permissions mean the owner and the group can read and write but other users have no permissions.

I checked it.

I found a reason for the 500 error
in my .htaccess

enable rewrites
    Options +FollowSymLinks
    RewriteEngine On
and
    RewriteBase /

but my frontend look like these now..

![image](https://cloud.githubusercontent.com/assets/7089704/13245201/e80464c8-da0b-11e5-8731-7edcc8d1cb49.png)

why this email message?

and my backend so

![image](https://cloud.githubusercontent.com/assets/7089704/13245210/fe711b66-da0b-11e5-91db-8c38b5748751.png)

**Comment by mrkhoa99** [comment]
You try to enable developer mode from CLI:
`bin/magento deploy:mode:set developer`
And then, deploy static content:
`bin/magento setup:static-content:deploy`

**Comment by mazhalai** [comment]
@anjenehm If you choose to go with a lower version, please do not expect the store to be fully functional. we rely on many features of 5.6 like [fulltext indexes and timestamp columns](https://dev.mysql.com/doc/refman/5.6/en/upgrading-from-previous-series.html).

**Comment by anjenehm** [comment]
So i should maybe buy a new "managed server only for magento 2"... 
Can you agree?

**Comment by anjenehm** [comment]
ok i have now a backend but get a error message

"Could not determine temp directory, please specify a cache_dir manually"

so i setup in file.php 'cahce_dir'=> '/var/tmp', but still get the error :(

**Comment by mazhalai** [comment]
@anjenehm ~~that line is no where in M2, it is in M1. Please do not post M1 related issues here. The proper place for that is community.magento.com~~ Just checked it is in vendor/magento/zendframework1/.

**Comment by anjenehm** [comment]
I get this error message when i want to open /admin (dashboard) this is magento 2.0.2 ce

**Comment by mazhalai** [comment]
@anjenehm what OS are you on?

**Comment by anjenehm** [comment]
Linux Gentoo

(i reinstall at this moment)

**Comment by anjenehm** [comment]
@mazhalai Ok succesful installation ... but ... when try to open /admin dashboard and the same error appears

main.CRITICAL: Could not determine temp directory, please specify a cache_dir manually

**Comment by mazhalai** [comment]
@anjenehm supported OSs are Centos and Ubuntu, though, it should work. Does your apache user have write permissions to the `/var/tmp` dir?

**Comment by anjenehm** [comment]
@mazhalai i reinstalled all again deployed static files en_US/de_DE. In htaccess i set the rewritebase and removed on my php.ini asp_tags. Bam succesful static files and a worked backend.

Thx for your help!

**Comment by mazhalai** [comment]
Thank you for your update. closing this ticket for now. If you have any more issues, please create a new one.

**Comment by JialuZhang** [comment]
@anjenehm 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
