### ISSUE TITLE
Bulk API requests to 'configurable-products' fail due to Magento\Framework\Webapi\ServiceInputProcessor::process() error

### ISSUE THREAD

**Issue by ThisIsRuddy** [magento/magento2#34248]
### Preconditions (*)
1. Magento 2.4.3 (works as expected in 2.4.2-p1
2. Some values added to the 'color' attribute for use with variations
3. Configurable & Simple products ready for linking (csv attached to create products)

### Steps to reproduce (*)
1. Create a 'configurable' product and its variations as 'simple' products via Admin Import
2. Create Integration entry with permissions
- Catalog > Inventory > Products > Update Attributes
3. Attempt to set options on 'configurable' via bulk API endpoint:

#### ENDPOINT: 
`{{MAGE_BASE_URL}}/rest/async/bulk/V1/configurable-products/bySku/options`
#### **EDIT! ALSO AFFECTS ENDPOINT: 
`{{MAGE_BASE_URL}}/rest/async/bulk/V1/configurable-products/bySku/child`
#### PAYLOAD: 
```
[
  {
    "sku": "P-001",
    "option": {
      "attribute_id": 93, //color attribute id
      "label": "Color",
      "is_use_default": false,
      "position": 1,
      "values": [
        {
          "value_index": 58 // 'red' attribute value id
        }
      ]
    }
  }
] 
```

#### RESPONSE:
```
{
    "bulk_uuid": "61c2dfb3-1f57-4c8f-95c0-ed9763100f7a",
    "request_items": [
        {
            "id": 0,
            "data_hash": "e3e1df0e6c9d1045abda606dd195ab1c0edd1a9e3455a22323009a5ba314fd71",
            "status": "accepted"
        }
    ],
    "errors": false
}
```

#### RESPONSE:
```
TypeError: Argument 3 passed to Magento\Framework\Webapi\ServiceInputProcessor::process() must be of the type array, string given, called in /var/www/domains/magento.local/http/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 154 and defined in /var/www/domains/magento.local/http/vendor/magento/framework/Webapi/ServiceInputProcessor.php:172
Stack trace:
#0 /var/www/domains/magento.local/http/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php(154): Magento\Framework\Webapi\ServiceInputProcessor->process()
#1 /var/www/domains/magento.local/http/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php(100): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolveBulkItemParams()
#2 /var/www/domains/magento.local/http/vendor/magento/module-webapi-async/Controller/Rest/AsynchronousRequestProcessor.php(100): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolve()
#3 /var/www/domains/magento.local/http/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor->process()
#4 /var/www/domains/magento.local/http/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#5 /var/www/domains/magento.local/http/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#6 /var/www/domains/magento.local/http/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/domains/magento.local/http/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#8 /var/www/domains/magento.local/http/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#9 /var/www/domains/magento.local/http/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#10 /var/www/domains/magento.local/http/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#11 {main}
```

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”.
_

[catalog_product.csv](https://github.com/magento/magento2/files/7284688/catalog_product.csv)

**Comment by ThisIsRuddy** [comment]
@magento give me 2.4-develop instance

**Comment by ThisIsRuddy** [comment]
I am unable to complete testing due to not being unable to make successful API requests using a newly created 'Full Access' Integration key as all requests state "The consumer isn't authorized to access %resources." when using PostMan or curl commands. Are API requests disabled on devbot instances?

![image](https://user-images.githubusercontent.com/1761171/136005826-15aeba12-ea46-499a-9f72-c6bb23a691a1.png)
![image](https://user-images.githubusercontent.com/1761171/136005850-4952124c-a234-4c03-90e1-6d7202637ec9.png)
![image](https://user-images.githubusercontent.com/1761171/136005732-a4533ce2-9cfd-4d5b-9d6e-6a6aeef9e887.png)
![image](https://user-images.githubusercontent.com/1761171/136006048-abd8a7c0-b4a8-4f5e-931c-3a777ea7823f.png)

**Comment by frostblogNet** [comment]
@akovtun 

In my opinion your patch does not fix the hole issue. The problem seems to be that the InputParamsResolver is merging Get parameters and the body. A quick solution for us was to skip get parameters using this code but it is also not a proper solution.

`diff --git a/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php b/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php
index 064bd99..28bedf3 100644
--- a/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php
+++ b/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php
@@ -97,6 +97,9 @@ class InputParamsResolver
         $this->requestValidator->validate();
         $webapiResolvedParams = [];
         foreach ($this->getInputData() as $key => $singleEntityParams) {
+            if (!is_array($singleEntityParams)) {
+                continue;
+            }
             $webapiResolvedParams[$key] = $this->resolveBulkItemParams($singleEntityParams);
         }
         return $webapiResolvedParams;
--
`

**Comment by engcom-Delta** [comment]
Hi @ThisIsRuddy,
is this issue resolved? if yes , can we close it?
Thanks

**Comment by ThisIsRuddy** [comment]
No this is definetly not resolved

I am currently holding back our go live so I can populate our store
products via bulk api on m2.4.2-p1 as this still works as expected on that
version

**Comment by hostep** [comment]
@ThisIsRuddy: have you tried [this fix](https://github.com/magento/security-package/commit/d2adcbb47d01e46ed5b193f0c973ea269eb62639) already?

**Comment by Anton-PiercingMania** [comment]
@ThisIsRuddy, did the fix solve your issues? We are experiencing the same problem.

**Comment by ThisIsRuddy** [comment]
@hostep Confirmed working as expected with below patch based off the commit you linked [d2adcbb](https://github.com/magento/security-package/commit/d2adcbb47d01e46ed5b193f0c973ea269eb62639)
I missed your previous comment so apologies for that :)

```diff --git a/vendor/magento/module-re-captcha-webapi-rest/Plugin/RestValidationPlugin.php b/vendor/magento/module-re-captcha-webapi-rest/Plugin/RestValidationPlugin.php
index fe434c8..be26337 100644
--- a/vendor/magento/module-re-captcha-webapi-rest/Plugin/RestValidationPlugin.php
+++ b/vendor/magento/module-re-captcha-webapi-rest/Plugin/RestValidationPlugin.php
@@ -54,12 +54,13 @@ class RestValidationPlugin
      * @param EndpointFactory $endpointFactory
      */
     public function __construct(
-        ValidatorInterface $recaptchaValidator,
+        ValidatorInterface                      $recaptchaValidator,
         WebapiValidationConfigProviderInterface $configProvider,
-        RestRequest $request,
-        Router $restRouter,
-        EndpointFactory $endpointFactory
-    ) {
+        RestRequest                             $request,
+        Router                                  $restRouter,
+        EndpointFactory                         $endpointFactory
+    )
+    {
         $this->recaptchaValidator = $recaptchaValidator;
         $this->configProvider = $configProvider;
         $this->request = $request;
@@ -71,20 +72,24 @@ class RestValidationPlugin
      * Validate ReCaptcha if needed.
      *
      * @param RequestValidator $subject
-     * @throws WebapiException
      * @return void
      *
      * @SuppressWarnings(PHPMD.UnusedFormalParameter)
+     * @throws WebapiException
      */
-    public function afterValidate(RequestValidator $subject): void
+    public function aroundValidate(RequestValidator $subject, callable $proceed): void
     {
-        $route = $this->restRouter->match($this->request);
+        $request = clone $this->request;
+        $proceed();
+        $route = $this->restRouter->match($request);
+
         /** @var Endpoint $endpoint */
         $endpoint = $this->endpointFactory->create([
             'class' => $route->getServiceClass(),
             'method' => $route->getServiceMethod(),
             'name' => $route->getRoutePath()
         ]);
+
         $config = $this->configProvider->getConfigFor($endpoint);
         if ($config) {
             $value = (string)$this->request->getHeader('X-ReCaptcha');
diff --git a/vendor/magento/module-re-captcha-webapi-rest/Test/Unit/Plugin/RestValidationPluginTest.php b/vendor/magento/module-re-captcha-webapi-rest/Test/Unit/Plugin/RestValidationPluginTest.php
index 96ea855..c236fe6 100644
--- a/vendor/magento/module-re-captcha-webapi-rest/Test/Unit/Plugin/RestValidationPluginTest.php
+++ b/vendor/magento/module-re-captcha-webapi-rest/Test/Unit/Plugin/RestValidationPluginTest.php
@@ -93,7 +93,8 @@ class RestValidationPluginTest extends TestCase
         bool $configFound,
         bool $isValid,
         bool $expectException
-    ): void {
+    ): void
+    {
         //Mocking route found
         $mockRoute = $this->createMock(Router\Route::class);
         $mockRoute->method('getServiceClass')->willReturn($class = 'class');
@@ -120,6 +121,8 @@ class RestValidationPluginTest extends TestCase
             $this->expectException(Exception::class);
         }

-        $this->model->afterValidate($this->subject);
+        $proceed = function (): void {
+        };
+        $this->model->aroundValidate($this->subject, $proceed);
     }
 }
```

**Comment by engcom-Delta** [comment]
Thanks for confirming @Thislsruddy.we are closing it as specified patch works fine.

**Comment by ThisIsRuddy** [comment]
Is the patch being merged?
