### ISSUE TITLE
crowdin missing source strings into language pack

### ISSUE THREAD

**Issue by paresh6002** [magento/magento2#34243]
### Preconditions (*)

1. Magento 2.4.3 

### Steps to reproduce (*)

1. install community danish language pack
2. set locale to danish(da_DK)

![translation_issue_1](https://user-images.githubusercontent.com/59193951/135813681-b5a7a4d7-e22e-41b6-9530-bd70db282528.png)

_**screenshot-1**_

3. Add a product to cart which have backorder and notify customer activated and 0 qty. as we can see on screenshot-2 this text is not translated as in danish pack.

![translation_issue_2](https://user-images.githubusercontent.com/59193951/135813773-1e2fa448-d9a7-4793-8fd3-e5180f70b05d.png)

_**screenshot-2**_

4. Crowdin missing that source string like screenshot-2. Also, there are other source strings missing as listed below:

> - Allow remote shopping assistance
> - This allows merchants to "see what you see" and take actions on your behalf in order to provide better assistance.
> - Sign up for Newsletter
> - The requested qty exceeds the maximum qty allowed in shopping cart
> - or call us at <a href="tel:%store_phone">%store_phone</a>
> - Customer login from customer login page.
> - Create New Customer Account" from customer account page.
> - We don't have as many quantity as you requested, but we'll back order the remaining %1.

### Expected result (*)

   As explained in point 4 of "steps to reproduce" that all source strings should add to crowdin in the language pack.

### Actual result (*)

    Same as explained in point 3  and 4 of "steps to reproduce".

**Comment by engcom-Delta** [comment]
Hi @paresh6002 ,
Issue is not reproducible in Magento 2.4 Develop. I have not able to modify the Locale field. Hence need your help to reproduce the issue .
Kindly provide more steps to modify the language from Locale field.
Please find the attached screenshot for reference.
![Locale](https://user-images.githubusercontent.com/51681379/136568015-6c925cd3-609b-4e0e-85fd-bd7a9bf92a30.JPG)
