### ISSUE TITLE
404 Not Found : js-translation.json

### ISSUE THREAD

**Issue by RohitSavaliya** [magento/magento2#3425]
I install magneto 2 on IIS 7, it is working good, but on home page and all other pages including admin panel a JavaScript error occurred

the error is :

```
NetworkError: 404 Not Found - http://localhost:8080/pub/static/frontend/Magento/luma/en_US/js-translation.json"
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
$.mage.translate.add(JSON.parse(string));
```

then I explore location `/pub/static/frontend/Magento/luma/en_US/`and found that the file is there when open the file it is contain just two square bracket `[]`.

i dont know why magento show that file is not found, because it is already there

I already delete folders in pub/static directory and then re-run the deploy command from cmd

php bin/magento setup:static-content:deploy
but it is not work for me.

is magento support IIS 7 ?
is problem occurred due to iis ?

**Comment by abdel1220** [comment]
Hello,
this is an IIS issue to fix it please follow this steps:

```
1- Open IIS Manager
2- Display properties for the IIS Server
3- Click MIME Types and then add the JSON extension:
    File name extension: .json
    MIME type: application/json 
4- Go back to the properties for IIS Server
5- Click on Handler Mappings
6- Add a script map
    Request path: *.json
    Executable: C:\WINDOWS\system32\inetsrv\asp.dll
    Name: JSON 
```

And then browse your json file in broswer, if your IIS setup successfully now you can see the json file content in broswer.

**Comment by veloraven** [comment]
@RohitSavaliya thank you for your question.
No, Magento does not support IIS as it does not support Windows operating system: http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html
If you really need this functionality you can create a feature request for it.
