### ISSUE TITLE
addAttributeToFilter is not respecting the attribute_id type bypassing db indexes

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#34258]
### Preconditions (*)
1. Magento 2.4.1 
2. MariaDB 10.4

### Steps to reproduce (*)
1. Create a collection using addAttributeToFilter

For example
```php
<?php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

use Magento\Framework\App\Bootstrap;

require 'app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);

$obj = $bootstrap->getObjectManager();

$state = $obj->get(Magento\Framework\App\State::class);
$state->setAreaCode('frontend');

$localeDate = $obj->get(\Magento\Framework\Stdlib\DateTime\TimezoneInterface::class);
$visibility = $obj->get(\Magento\Catalog\Model\Product\Visibility::class);

/**
 * @var $collection \Magento\Catalog\Model\ResourceModel\Product\Collection
 */
$collection = $obj->get(\Magento\Catalog\Model\ResourceModel\Product\Collection::class);


$todayStartOfDayDate = $localeDate->date()->setTime(0, 0, 0)->format('Y-m-d H:i:s');
$todayEndOfDayDate   = $localeDate->date()->setTime(23, 59, 59)->format('Y-m-d H:i:s');

$collection->addAttributeToFilter(
    'news_from_date',
    [
        'or' => [
            0 => ['date' => true, 'to' => $todayEndOfDayDate],
            1 => ['is' => new \Zend_Db_Expr('null')],
        ]
    ],
    'left'
)->addAttributeToFilter(
    'news_to_date',
    [
        'or' => [
            0 => ['date' => true, 'from' => $todayStartOfDayDate],
            1 => ['is' => new \Zend_Db_Expr('null')],
        ]
    ],
    'left'
)->addAttributeToFilter(
    [
        ['attribute' => 'news_from_date', 'is' => new \Zend_Db_Expr('not null')],
        ['attribute' => 'news_to_date', 'is' => new \Zend_Db_Expr('not null')],
    ]
)->addAttributeToSort(
    'news_to_date',
    'desc'
);

echo $collection->getSelectSql(true);
```

2. Retrieve the sql select produced by the collection

```sql
SELECT `e`.*,
       IF(at_news_from_date.value_id > 0, at_news_from_date.value, at_news_from_date_default.value) AS `news_from_date`,
       IF(at_news_to_date.value_id > 0, at_news_to_date.value, at_news_to_date_default.value)       AS `news_to_date`
FROM `catalog_product_entity` AS `e`
         LEFT JOIN `catalog_product_entity_datetime` AS `at_news_from_date_default`
                   ON (`at_news_from_date_default`.`entity_id` = `e`.`entity_id`) AND
                      (`at_news_from_date_default`.`attribute_id` = '81') AND `at_news_from_date_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_datetime` AS `at_news_from_date`
                   ON (`at_news_from_date`.`entity_id` = `e`.`entity_id`) AND
                      (`at_news_from_date`.`attribute_id` = '81') AND (`at_news_from_date`.`store_id` = 8)
         LEFT JOIN `catalog_product_entity_datetime` AS `at_news_to_date_default`
                   ON (`at_news_to_date_default`.`entity_id` = `e`.`entity_id`) AND
                      (`at_news_to_date_default`.`attribute_id` = '82') AND `at_news_to_date_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_datetime` AS `at_news_to_date`
                   ON (`at_news_to_date`.`entity_id` = `e`.`entity_id`) AND
                      (`at_news_to_date`.`attribute_id` = '82') AND (`at_news_to_date`.`store_id` = 8)
WHERE (((((IF(at_news_from_date.value_id > 0, at_news_from_date.value, at_news_from_date_default.value) <=
           '2021-10-06 23:59:59') OR
          (IF(at_news_from_date.value_id > 0, at_news_from_date.value, at_news_from_date_default.value) IS null)))))
  AND (((((IF(at_news_to_date.value_id > 0, at_news_to_date.value, at_news_to_date_default.value) >=
           '2021-10-06 00:00:00') OR
          (IF(at_news_to_date.value_id > 0, at_news_to_date.value, at_news_to_date_default.value) IS null)))))
  AND ((IF(at_news_from_date.value_id > 0, at_news_from_date.value, at_news_from_date_default.value) IS not null) OR
       (IF(at_news_to_date.value_id > 0, at_news_to_date.value, at_news_to_date_default.value) IS not null))
ORDER BY IF(at_news_to_date.value_id > 0, at_news_to_date.value, at_news_to_date_default.value) desc 
```

3. Notice that the attribute_id in joins is treated as a text value but in reality it's an integer value 

The query execution time due to this is extremely high. With text values and conversion it's reaching 3.5minutes. 
With integers it's reaching 1.5seconds 

### Expected result (*)
The query is using int for the attribute_id 

### Actual result (*)
The query is using text for the attribute_id 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
@engcom-November This is not really a dev experience issue, it's causing a huge performance bottlneck as this way of joining is used in pretty much everything including indexers. Thus indexing takes quite a bit more time compared to what it should. It's more of a a core bug that should be addressed. 

On our instance, due to constant data entry, it caused the CPU to use 32 cores at all times fully as it was in a constant state of indexing stuff using queries that used an int attribute as string.

**Comment by engcom-Hotel** [comment]
Hi @ioweb-gr,
I have tried the above query using the quotes around the integer value and without quotes, in both of the cases, the required indexes are being used. I have run the query using EXPLAIN ANALYZE and compared their plans, both are almost the same.

Please have a look at the query plan: https://explain.depesz.com/s/A63S

In the above link, I have added 2 plans one is with the quotes around integer value and one is without quotes.

In both of the plans observe the indexes used.
Could you please run your query again using the EXPLAIN ANALYZE and find out which indexes are used by the query with quotes and without quotes. If you found the difference please share the details. I will try to reproduce it again.

**Comment by engcom-Hotel** [comment]
Dear @ioweb-gr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by ioweb-gr** [comment]
Kind of late on this due to other emergencies. Unfortunately we patched the issue on the system so it's not possiible to give you a current EXPLAIN however if you take a look at https://dba.stackexchange.com/questions/300724/can-i-improve-this-query-by-adding-indexes-or-tuning-mariadb-config where I got some help regarding the issue I have added a profile and explain 

https://i.stack.imgur.com/TM5iv.png
https://i.stack.imgur.com/e1GdY.png
