### ISSUE TITLE
Sort order in category view not respected

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#34268]
### Preconditions (*)

1. Magento ver. 2.4.2-p1
2.

### Steps to reproduce (*)

1. Set product sort order in Catalog => Categories => Select Category => Products in Category
2.

### Expected result (*)

1. Set sort order: https://mtjwebservice.nl/screenshot1.png
2. Check result in frontend: https://mtjwebservice.nl/screenshot2.png

### Actual result (*)

1. Products in category view are in a different order then what is set in admin
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
duplicated #32571

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
