### ISSUE TITLE
Out of stock shown as In Stock in catagory view

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#34267]
### Preconditions (*)

1. Magento ver. 2.4.2-p1
2.

### Steps to reproduce (*)

1. Set article to out of stock
2. Open frontend and select category where product is assigned to
3. No add-to-cart-button is shown, but instead you see the label "In stock"

### Expected result (*)

1. Label "Out of stock"should be shown
2.

### Actual result (*)

1. Screenshot: https://mtjwebservice.nl/screenshot.png
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
Are you sure indexers are "Update on Save", what happens after run
`bin magento indexer:reindex`?

**Comment by mtjweb** [comment]
Please check in the Blank theme, the Luma theme does have stock status in category view.
