### ISSUE TITLE
Multiple store views product duplicate error

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#3426]
I have two languages: A (default) and B.
When editing a product in B and clicking "save and duplicate", it duplicates the product, but the new product has all default details in language B. I think it should not do that, but completely duplicate the product in both languages (store views)

**Comment by antboiko** [comment]
Hi @bgabrovsek , thanks for your inquiry. We've created internal ticket MAGETWO-49618 for this issue.

Best,
Anton.

**Comment by oserediuk** [comment]
Hello! We have fixed this issue. So this ticket can be closed. If you reproduce this case or have questions related to this issue, please, reopen this ticket.
