### ISSUE TITLE
Graphql Exception "Category image not found" if image doesn't exist shouldn't error the entire request

### ISSUE THREAD

**Issue by iba-1** [magento/magento2#34266]
### Summary (*)
When trying to get a list of categories, or even only one category, if "image" field is filled but the image can't be found on filesystem the request will fail with "Error: Category image not found."
This shouldn't be the correct behavior as not being able to render an image for a category isn't an unrecoverable error, and we've been able to handle in frontend this kind of errors for years, either be using a fallback or by leveraging other solutions.
Plus, when displaying a list of categories an image missing shouldn't block the whole categories being displayed by erroring the request.

### Examples (*)
- Upload an image to a category
- Delete it from FS
- Run any categories Graphql query including "image" attribute 
- Watch it fail by "Error: Category image not found."

In our case, this was the query:
```js
const QUERY = gql`
  query GetLines {
    categories {
      items {
        children {
          name
          children {
            name
            children {
              name
              fast_shipping
              url_path
              image
            }
          }
        }
      }
    }
  }
`;
```

### Proposed solution
Remove entirely this exception:
https://github.com/magento/magento2/blob/1807f70756b521240c06eb556802422307cabbb5/app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php#L70-L72

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._

No workaround that we can think of can be applied to recover from this error apart from re-uploading the missing image.

**Comment by iba-1** [comment]
@magento I am working on this

**Comment by iba-1** [comment]
@magento add to contributors team

**Comment by iba-1** [comment]
> magento I am working on this
> If that's possible I would take this issue as > it's a good first issue, don't know if there 
> are any policies forbidding from it.

What should we return if no image is found?
Is there some docs regarding standard graphql responses?

**Comment by shikhamis11** [comment]
> > magento I am working on this
> > If that's possible I would take this issue as > it's a good first issue, don't know if there
> > are any policies forbidding from it.
> 
> What should we return if no image is found? Is there some docs regarding standard graphql responses?

@cpartica

**Comment by cpartica** [comment]
That will work. Plz link that Pr to the issue when you have it.

**Comment by cpartica** [comment]
> > magento I am working on this
> > If that's possible I would take this issue as > it's a good first issue, don't know if there
> > are any policies forbidding from it.
> 
> What should we return if no image is found? Is there some docs regarding standard graphql responses?

Settled on what we'll do. We are going to just return the placeholder image to prevent blocking errors and log non existing images not found - 
We also want to add a field-  "errors" as data to any query - that a PWA would better interpret - GQL spec doesn't have this
a differentiation between critical fatal errors vs recoverable errors like this one - 
plz refer to this recommendation as a further standard: https://github.com/magento/architecture/pull/505

**Comment by engcom-Alfa** [comment]
Hi @Reporter ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest 2.4-develop to retest the case.

In case of any Magento related issues found in 2.4-develop, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
