### ISSUE TITLE
Sales order items not visible in New Order Email

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#34269]
### Preconditions (*)

1. Magento 2.3.5-p2

### Steps to reproduce (*)

1. Go to Admin > Marketing > Email > Email Templates > Add Email Template
2. Load Magento_Sales > New Order template
3. Add name and set that Email Template to be used in the store
4. Place an order from the front end, or on an existing order select Sales > Orders > [Order] > Send Email

### Expected result (*)

1. Order item grid is present in email template

### Actual result (*)
1. Order item grid is not present in email template

This appears to be related to https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html, however the default template has not been updated to accommodate the order item grid:

`{{layout handle="sales_email_order_items" order=$order area="frontend"}}`

the `$order` object does not pass any information, and other order data is passed through the template using `$order_data` rather than `$order`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by yogesh-15git** [comment]
#dmcdindia2020

**Comment by yogesh-15git** [comment]
@magento I'm working on it.

**Comment by engcom-Delta** [comment]
Hi @nbennett25 ,
We verified in Magento 2.4 Develop instance with latest branch , it works fine . I could see order grid present in received email.
Please find the attached screenshots for reference.
![order_grid1](https://user-images.githubusercontent.com/51681379/144423163-a399e13a-1734-404e-bdb9-728c7f6e0c96.JPG)
![order_grid2_email](https://user-images.githubusercontent.com/51681379/144423186-9a2805f0-0b10-49d9-aa84-e7f4bf95ce84.JPG)
Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Comment by cwwhisperpumps** [comment]
I am also experiencing this issue, can someone please assist in how it was resolved? I apologise, I am not a developer so would appreciate simplified help if possible?

**Comment by cctorres** [comment]
@cwwhisperpumps the same in Magento 2.4.4. @magento-admin

**Comment by cwwhisperpumps** [comment]
> @cwwhisperpumps the same in Magento 2.4.4. @magento-admin

Do you know how to resolve the issue? I am running Magento 2.3.7-p3

**Comment by cctorres** [comment]
> > @cwwhisperpumps the same in Magento 2.4.4. @magento-admin
> 
> Do you know how to resolve the issue? I am running Magento 2.3.7-p3


Use {{layout handle="sales_email_order_items" order_id=$order_id area="frontend"}} instead of {{layout handle="sales_email_order_items" order=$order area="frontend"}} if you don't hace custom attributes in your order layout

**Comment by cwwhisperpumps** [comment]
> > > @cwwhisperpumps the same in Magento 2.4.4. @magento-admin
> > 
> > 
> > Do you know how to resolve the issue? I am running Magento 2.3.7-p3
> 
> Use {{layout handle="sales_email_order_items" order_id=$order_id area="frontend"}} instead of {{layout handle="sales_email_order_items" order=$order area="frontend"}} if you don't have custom attributes in your order layout

I have tried this and it still isn't working :(

**Comment by cctorres** [comment]
> > > > @cwwhisperpumps the same in Magento 2.4.4. @magento-admin
> > > 
> > > 
> > > Do you know how to resolve the issue? I am running Magento 2.3.7-p3
> > 
> > 
> > Use {{layout handle="sales_email_order_items" order_id=$order_id area="frontend"}} instead of {{layout handle="sales_email_order_items" order=$order area="frontend"}} if you don't have custom attributes in your order layout
> 
> I have tried this and it still isn't working :(

Sorry, so I don't know. I used it and it worked for me, but the project has custom attributes on the table and those attributes don't show up.

**Comment by cwwhisperpumps** [comment]
![screenshot email](https://user-images.githubusercontent.com/107941857/176205786-ac86a5bb-4f4b-41f1-bed8-d603f682daee.png)

**Comment by cctorres** [comment]
> > > > > > @cwwhisperpumps the same in Magento 2.4.4. @magento-admin
> > > > > 
> > > > > 
> > > > > Do you know how to resolve the issue? I am running Magento 2.3.7-p3
> > > > 
> > > > 
> > > > Use {{layout handle="sales_email_order_items" order_id=$order_id area="frontend"}} instead of {{layout handle="sales_email_order_items" order=$order area="frontend"}} if you don't have custom attributes in your order layout
> > > 
> > > 
> > > I have tried this and it still isn't working :(
> > 
> > 
> > Sorry, so I don't know. I used it and it worked for me, but the project has custom attributes on the table and those attributes don't show up.
> 
> I take that back! It wasn't showing anything in the preview box so I presumed it didn't work but we've had an order through with it on now :) The only thing is... It's slightly cropped and not filling the space like it was before. See screenshot. Any ideas about this? If not, don't worry as you've been a massive help getting the order details back.

No. I dont know how to fix that. sorry

**Comment by sanaeefar-saeed** [comment]
@magento give me 2.4-develop instance

**Comment by berkelle** [comment]
Hi. Having the same issue on 2.4.2

**Comment by cctorres** [comment]
> Hi. Having the same issue on 2.4.2

Did you tray change $order to $order_id?

**Comment by KarlComSe** [comment]
Similar issues. Worked to update the template variables.
