### ISSUE TITLE
Missmatch Portugal ZIP Code Matching

### ISSUE THREAD

**Issue by mklooss** [magento/magento2#34271]
Missmatch Portugal ZIP Code Matching -  ( https://github.com/magento/magento2/issues/14220 )

**Issue description:** irrespective of zip code & tax rate set , tax gets calculated only default is 23% which is zip code set  '* '.

the Issues will be produced by this method: https://github.com/magento/magento2/blob/2.4/app/code/Magento/Tax/Model/ResourceModel/Calculation.php#L345-L355

### Preconditions (*)

1. Magento 2.4.3
2. Tax Calculation Rule: 
```
+-------------------------+----------------+---------------+--------------+-----------------------+---------+--------------+----------+--------+
| tax_calculation_rate_id | tax_country_id | tax_region_id | tax_postcode | code                  | rate    | zip_is_range | zip_from | zip_to |
+-------------------------+----------------+---------------+--------------+-----------------------+---------+--------------+----------+--------+
|                      54 | PT             |             0 | *            | TAX Portugal       | 23.0000 |         NULL |     NULL |   NULL |
|                     136 | PT             |             0 | 96*          | 0% TAX - PT/A2-96% |  1.0000 |         NULL |     NULL |   NULL |
|                     137 | PT             |             0 | 97*          | 0% TAX - PT/A2-97% |  0.0000 |         NULL |     NULL |   NULL |
+-------------------------+----------------+---------------+--------------+-----------------------+---------+--------------+----------+--------+

```

### Steps to reproduce (*)

1. Create 3 known Rules as mentioned in above grid.
2. Try to Checkout anything with an Address from the Range (eg: 9610-111) and Country Portugal.

### Expected result (*)

1. Tax Should be 0 % = 0 €

### Actual result (*)

1. Tax will be applied from 54 but Never from 136

### Additional Info (*)
1. By choosing an 96XXXX code, the applied tax is turning to 24% (Where 23% is from * rule, and 1% from 96*)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @mklooss ,
We tried to replicate it on Magento 2.4 Develop latest branch. Unfortunately we could not find the zip-codes which provided in the ticket.
Link# https://en.wikipedia.org/wiki/Postal_codes_in_Portugal.
Hence request to review it once again.

**Comment by mklooss** [comment]
@engcom-Delta just take a look at the list on wikipedia: "Postal regions (first digit of postal code)" -> "9. (brown) - Madeira Islands and Azores" and also at the Image on the right side of the article: https://en.wikipedia.org/wiki/Postal_codes_in_Portugal#/media/File:Postal_Codes_of_Portugal.png
There you can found the data, of this postal codes.

**Comment by engcom-Delta** [comment]
Hi mklooss,
We tried to reproduce the issue  as per provided steps , we could see the difference in tax calculation for PT country .Hence added label 'Issue confirmed'.
![PT_taxRule](https://user-images.githubusercontent.com/51681379/144462949-a7b06ced-cf85-4384-b1e6-cd6f302941f8.JPG)

![Tax_applied_PT](https://user-images.githubusercontent.com/51681379/144462118-0d4d704d-7746-4213-beb2-eb744b30b1de.JPG)

**Comment by engcom-Alfa** [comment]
@mklooss 
Thanks for your contribution, and reported issue is in discussion
Thanks for your patience!


@engcom-Hotel 
Please look into the code how it is working, and needs to confirm the actual behaviour by looking into the documentation.

**Comment by glo11468** [comment]
Hi @mklooss,

Please find attached proofs for reference and updated issue description.
![PT_taxRule](https://user-images.githubusercontent.com/90306034/146310895-3679cd0b-29bc-4f8a-8e75-3c0c2e8ccbf2.JPG)
![PT_taxRule_star_configured](https://user-images.githubusercontent.com/90306034/146310936-b33f6333-5b11-4dc2-90a8-85f6316c1db6.JPG)
![PT_taxRule_Star](https://user-images.githubusercontent.com/90306034/146310940-630f2fa4-0c48-410b-ad55-f9835d7be5d2.JPG)
![PT_taxrule_96_configured](https://user-images.githubusercontent.com/90306034/146310942-b001d10c-3eb1-4422-ac66-926856da8a80.JPG)
![PT_taxrule_96](https://user-images.githubusercontent.com/90306034/146310945-634a35e5-d3fc-40da-a9bd-2050ddaa35fb.JPG)

**Comment by engcom-Delta** [comment]
Hi @mklooss,

Please find attached proofs for reference and updated issue description.

**Issue description:** irrespective of zip code & tax rule , tax gets calculated only default is 23% which is zip code set '* '.

Screenshots:
![PT_taxRule_star_configured](https://user-images.githubusercontent.com/51681379/146317960-dcc52c38-9919-46f8-bbe7-3f468344e75c.JPG)
![PT_taxRule_Star](https://user-images.githubusercontent.com/51681379/146317972-1356dbd7-2797-4c55-8196-eb957c749ebc.JPG)
![PT_taxrule_96_configured](https://user-images.githubusercontent.com/51681379/146317975-517fcf31-f5ce-46a4-9472-012bf15151ba.JPG)
![PT_taxrule_96](https://user-images.githubusercontent.com/51681379/146317977-836b7b1b-dfd2-4cf8-ac9d-4f070f7ca5d1.JPG)
![PT_taxRule](https://user-images.githubusercontent.com/51681379/146317980-ed2f3533-5e79-4568-b3b5-6af7792d2ac3.JPG)
![Tax_applied_PT](https://user-images.githubusercontent.com/51681379/146317983-59f45c54-728d-496c-88f6-9de3a2a13d60.JPG)
![Tax_rule_97zipcode](https://user-images.githubusercontent.com/51681379/146317996-b356dfe3-6495-4200-bc50-293daca30bf6.JPG)

**Comment by engcom-Alfa** [comment]
Hello @mklooss 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-XXX` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5
