### ISSUE TITLE
PayPal-Order Status Complete just after payment, instead of Processing 

### ISSUE THREAD

**Issue by tanolalano** [magento/magento2#34276]
### Preconditions (*)
1. Magento 2.4.3
2. Php 7.4
3. Ngix 
4. Magento Hosted pro

### Steps to reproduce (*)

1. Order payed with paypal

### Expected result (*)
1. Order signed as Processing

### Actual result (*)

1. After Ipn received order as marked as Complete because orders doesn't have Shipping informations
2. No error in log
<img width="1245" alt="Schermata 2021-10-07 alle 12 00 37" src="https://user-images.githubusercontent.com/4384863/136457159-1efeb98c-b2ff-439c-a528-0d93d52585a7.png">

---
Severity: **S1**

**Comment by engcom-Hotel** [comment]
Hello @tanolalano,

Thanks for reporting this issue!

But we are not able to get with the below point. We request you to please elaborate.

> ### Expected result (*)
> 1. Order signed as Processing
> 
> ### Actual result (*)
> 1. After Ipn received order as marked as Complete because orders doesn't have Shipping informations
> 2. No error in log

Thanks
