### ISSUE TITLE
jquery.min.js:14 [Violation] Added synchronous DOM mutation listener to a 'DOMSubtreeModified' event. Consider using MutationObserver to make the page more responsive

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#34278]
Preconditions :

Magento 2.4 latest version

Steps 1: Run website in browser
Steps 2: Open console tab
Added synchronous DOM mutation listener to a 'DOMSubtreeModified' event. Consider using MutationObserver to make the page more responsive

Can it be fixed are it is causing issue with mobile performance

**Comment by ia-gaurav** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @ia-gaurav,

Kindly provide clear issue description , steps to reproduce, expected results & actual results.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
