### ISSUE TITLE
Theme inheritance example not working

### ISSUE THREAD

**Issue by MattDeanCS** [magento/magento2#3429]
I was following this guide http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-inherit.html and tried to copy the example at the bottom of the page "OrangeCo decided they should remove the “Report bugs” link from the footer" using

`<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <remove name="report.bugs"/>
    </body>
</page>`

This doesn't work though.

If I swap the `<remove name="report.bugs"/>` out for `<referenceBlock name='report.bugs' remove='true'/>` this now works.

My question is should the example given work and if so why is it not working?
Alternatively is the guide wrong? 
I'm pretty new to this so took quite a while to figure out what was the issue.
Thanks
Matt

**Comment by davidalger** [comment]
@MattDeanCS The examples listed in the guides should work. :) Would you mind opening an issue on the http://github.com/magento/devdocs/ repo to report the broken example? The docs team can then take troubleshooting it from there. Glad you found a working solution!

**Comment by MattDeanCS** [comment]
Will do David, thanks
