### ISSUE TITLE
Unique constraint violation found while placing order

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/magento2#34296]
Hello Support,
I hope you are doing fine.

I have magento 2 site which is upgraded from Magento 2.4.0 to 2.4.3 and after upgrading I am getting error like "Unique constraint violation found" while using credit/debit card payment method. Although customers are getting charged but orders are not created in admin. I have tried changed sequence_order_1 as well sequence_invoice_0 as well but still getting error.

Website url: https://brightlinkav.com/
Php: 7.4
Magento version: 2.4.3

Please check once and help me to solve this issue asap.
@victor-ruiz  @victor-v-rad @engcom-Delta 

Thanks

**Comment by baljinderimpinge** [comment]
@victor-ruiz @victor-v-rad @engcom-Delta
Any update please?

**Comment by engcom-Delta** [comment]
Hi @baljinderimpinge,
Kindly provide the steps to reproduce the issue , actual results and expected results.

Thanks
