### ISSUE TITLE
Knockout not translateable with text contain single quote character

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#34319]
### Examples (*)

Example this text italiano
se hai scelto il ritiro dell'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato

As you can see text contain one single quote
if we use translate attribute will not work. Same for data-bind

Change text (remove quote) will be workarounds but it's may not be option when sometimes we want keep remain text

Example
```text
<span translate="'se hai scelto il ritiro dell'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>
```

or
```text
<span data-bind="i18n: 'se hai scelto il ritiro dell'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>
```

### Additional Information
**Steps to reproduce**
1. Add below line in `app/code/Magento/Checkout/view/frontend/web/template/onepage.html`:
`<span data-bind="i18n: 'se hai scelto il ritiro dell'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>`
2. Add translation in `app/code/Magento/Checkout/i18n/en_US.csv`
3. Check the checkout page, if we do not escape single quote, then there is an error in the console like below:
![CheckoutPageConsoleError](https://user-images.githubusercontent.com/51681618/138073620-22de42e1-b062-47de-88a8-c625f5c627d4.jpg)

**If we escape the single quote, we are not getting any error but the translation is not working, please have a look into the below screenshot**:
![CheckoutPageWOConsoleError](https://user-images.githubusercontent.com/51681618/138074166-02590dc7-a7d8-44e6-8830-78c4961769e2.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
@mrtuvn, I guess it should be escaped, example:
```
<span translate="'se hai scelto il ritiro dell\'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>
```
and 
```
<span data-bind="i18n: 'se hai scelto il ritiro dell\'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>
```

**Comment by mrtuvn** [comment]
Yes your way work but seem text still not able to translate

Before  following ihor way
Error visible
![ko-fail-bind-single-quote-text-contain](https://user-images.githubusercontent.com/1908873/136946186-cbc69552-75e2-43b3-8af5-7bb9466bb023.png)


After apply escape
Error gone but text still not able translate

**Comment by tuna2smc** [comment]
i think this easy to reproduce add this text bind above + your escape in any html file . Example onepage.html checkout and reload. Also add text translate to csv too.

**Comment by Melnychuk-Alexandr** [comment]
@magento I am working on this

**Comment by Melnychuk-Alexandr** [comment]
Hi @mrtuvn . This solution works good.
In html:
<span data-bind="i18n: 'se hai scelto il ritiro dell\'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato'"></span>

In csv:
"se hai scelto il ritiro dell'usato, ricordati di preparare il vecchio prodotto scollegato e disinstallato","Italiano text."

Please check and let me know. Thanks!

**Comment by mrtuvn** [comment]
yes your solution works for my case.
Seem in csv we don't need to add backslash before single quote. In knockout template we have to add this slash for avoid compile error
Many Thanks

**Comment by mrtuvn** [comment]
I think we can close this now
