### ISSUE TITLE
How to add custom form in custom payment method?

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3431]
I have created custom payment method based on [Inchoo_Stripe](https://github.com/Inchoo/magento2-Inchoo_Stripe). This custom payment method requires custom form fields to be filled in - where should I define them and how to process/validate the form?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
