### ISSUE TITLE
Added Products are Not Showing on the Admin Order Page After 2.4.3 Upgrade

### ISSUE THREAD

**Issue by chattertech** [magento/magento2#34329]
### Preconditions (*)

1. Upgrade from 2.4.2 to 2.4.3
2. PHP 7.4
3. Redis 6

### Steps to reproduce (*)

1. Create a new order in the backend
2. Pick a customer or create a new one
3. Click 'Add Products'
4. Choose a product and click 'Add Selected Product(s) to Order'

### Expected result (*)

1. Products to show in the **Items Ordered** list
2. Totals to reflect the products in the list

### Actual result (*)

1. **Items Ordered** list is empty
2. Totals do not reflect the products added
3. There is no longer an 'Add Product' button
3. A workaround was found which requires refreshing (reloading) the page
4. When page is reloaded the products added show in the Items Ordered list and totals are correct
5. Every time a new product is added (or changed) the page must be reloaded
6. https://www.screencast.com/t/ePqbbrS3

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @chattertech,

I have verified this issue with the latest Magento instance with your steps, actual result, expected result, and attached video but I am not able to reproduce this issue.

**Please attached the below video link:**
https://www.awesomescreenshot.com/video/5609710?key=0f604b9654424775554e5ecaf869b5d3

Can you please update me on which Magento Version and Type (Community/Commerce) you are using?

Thanks.

**Comment by chattertech** [comment]
I was able to find a fix...

I looked up the system.log and noticed that i was getting this error when trying to place an order as admin.

_main.WARNING: Session size of 359208 exceeded allowed session max size of 256000._

I found the following solution.

bin/magento config:set system/security/max_session_size_admin 0

then

bin/magento c:f

Now the admin order page is working as expected.
