### ISSUE TITLE
Error saving product magento 2.02

### ISSUE THREAD

**Issue by sela88** [magento/magento2#3432]
edit product > Advanced settings > autosettings > short description >
When I try to save the product, I get this error: 
You don't have permission to access /admin_121bmr/catalog/product/save/id/2/key/6244de5c82012f0affb6147fe06fa6f9645f3b6cefae1e6a3262b394b1100ebe/back/edit/active_tab/autosettings/ on this server.

It happens also for some CMS pages I try to save.

**Comment by vzabaznov** [comment]
Hi @sela88, do you have ACL permission to do such kind of operations?

**Comment by maksek** [comment]
Closing due no response for long time.
