### ISSUE TITLE
Bug when Creating a Mixin on Magento_GoogleTagManager with AdBlocker enabled

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#34335]
**Preconditions**
Magento 2.4.2 commerce edition
mysql 8.0
php 7.4

**Steps to reproduce**
- Enable Google Analytics in Stores > Settings > Configuration > Sales >Google API
- Create any mixins over Magento_GoogleTagManager/js/google-tag-manager-cart or Magento_GoogleTagManager/js/google-analytics-universal
- Install AdBlocker Adblock Plus - free ad blocker and enable block tracking
- Go to Checkout

**Expected result**
- Checkout is working

**Actual result**
Checkout is loading infinitely

**Similar old issues**
https://github.com/magento/magento2/issues/12428

**Technical Investigations**
This comment https://github.com/magento/magento2/issues/12428#issuecomment-416556613 is suggesting to replace with the old resolver, where the pending check was changed, while this seems to work but we believe it is not the best solution.

the problem is with isRejected function 

```
    function isRejected(module) {
        return registry[module.id] && (registry[module.id].inited || registry[module.id].error);
    }
```

As we can see, it is checking the registry for the module id, when this condition is checked for the mixins, it is not returning true since .inited is always null, while for the original module it is returning true as expected.

for example when this condition is called for this module id ‘Magento_GoogleTagManager/js/google-tag-manager-cart’ it is returning true, while for the mixins ‘mixins!Magento_GoogleTagManager/js/google-tag-manager-cart’ it is returning false although we expect if the module is rejected the same should be for its mixins.

as a hotfix we tried the following and it worked:

 ```
    function isRejected(module) {
        return registry[module.id] && (registry[module.id].inited || registry[module.id].error || (registry[module.name] && registry[module.name].inited));
    }
```

this is because for mixins module.name is identical to the id of the parent module, similarly, we could just check for the module id after removing mixins! from the beginning. 

Special thanks to omarmohssen for investigating.

**Comment by mrtuvn** [comment]
Do you check the case define mixin in requirejs-config ? Instead use mixins!Magento_GoogleTagManager/js/google-tag-manager-cart
Does it work same

**Comment by mrtuvn** [comment]
Normal way magento define mixin in file requirejs-config
https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_mixins.html
I'm not tested with the case enable plugin AdBlock but sometimes magento not call mixin correct as we expected. You also can call mixin
like this

```js
define([
    'mixins!ComponentJsPath'
], function () {
    'use strict';

    return function (originMethod) {
        //CODE HERE SOMETIMES NOT REACH
    };
});
```

**Comment by engcom-November** [comment]
Hi @leonhelmus ,
We are closing this issue as there has been no latest update on the same.
Thank you.
