### ISSUE TITLE
Remote storage sync fails on similar image filenames (with hyphens and underscores)

### ISSUE THREAD

**Issue by lphilippo** [magento/magento2#34337]
### Preconditions (*)
1. Magento 2.4.3 CE
2. Activate remote storage with AWS S3

### Steps to reproduce (*)
1. Use an image where the filename has an hyphen as a second character: `5-100.png`
2. Use a second image with the same first character, but an underscore as second: `5_100.png`
3. Synchronise remote storage with `bin/magento remote-storage:sync`

### Expected result (*)
1. Both images will be synchronised with the remote storage.

### Actual result (*)
1. The first image (with dash) is being stored correctly.
2. The second image fails with the message `Notice: Undefined index: media/catalog/product/5/_ in /src/vendor/magento/module-remote-storage/Driver/Adapter/Cache/Generic.php on line 197`
3. The sync process halts.

### Technical background
The issue lies in `RemoteStorage/Driver/Adapter/Cache/Generic`. The dashes are converted to underscore in the internal workings of the cache adapter (line 192). This causes that the underscore variant receives the cache that the dash variant has already created. However, the path inside the `$meta` has been unaffected by the underscore conversion and the mismatch triggers the exceptions. This was very easily circumvented by the following change to check both non-empty content as well as existence, which prevents that the incorrect cache is  being used for the underscore variant:

```
<             if (!$meta[$path]) {
---
>             if (empty($meta[$path])) {
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

### Additional Info
![error](https://user-images.githubusercontent.com/51681618/137308953-38cdbcfb-2510-4ee4-a72b-374ee6cae733.jpg)

[X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by engcom-Hotel** [comment]
Hello @lphilippo,

Thanks for reporting the issue!

Hence the issue is reproducible with the given steps, we are confirming this issue. We are getting the below error while running `bin/magento remote-storage:sync` command:

![error](https://user-images.githubusercontent.com/51681618/137308953-38cdbcfb-2510-4ee4-a72b-374ee6cae733.jpg)


Thanks

**Comment by simonmaass** [comment]
can also confirm in 2.4.3-p1

**Comment by simonmaass** [comment]
where can i see the PR for this?

**Comment by simonmaass** [comment]
@lphilippo do you have any workaround?

**Comment by lphilippo** [comment]
@simonmaass 
For me the change I mentioned in the original ticket was enough to make it working correctly. I don't know if for the final PR they took a different approach, though.

**Comment by engcom-November** [comment]
Hi @lphilippo 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-1486 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1486&type=commits
Based on the Jira ticket, the target version is 2.4.6.

Thanks
