### ISSUE TITLE
Last-Modified header stuck after upgrade to 2.4.3

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#34334]
### Preconditions (*)

1. Upgraded from 2.4.0 to 2.4.3
2. Apache server with Varnish Cache, Nginx SSL termination
3. Redis Session storage

### Steps to reproduce (*)

1. Upgrade to 2.4.3 with Last-Modified header active
2. Visit a frontend category, product, or cms page and check HTTP head

### Expected result (*)

1. On page load Last-Modified http header is updated with recent changes date
2. HTTP  Last-Modified header progresses to update on page modifications and creations

### Actual result (*)

1. HTTP header Last-Modified header date is fixed at M2.4.3 upgrade date
2. The Last-modified date is not updated even on new page creation
3. Our last-modified date is fixed permanently as the exact time and date seen below on our M2 folders 23-09-21 17:58:48 when we upgraded to 2.4.3

![image](https://user-images.githubusercontent.com/39824288/137096957-6b8e015a-d1d3-499d-acf5-73f5a4894b11.png)

This is resulting in google search getting 304 response on new content
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by nadroj467** [comment]
Further to this issue I found that the Last-Modified date for our whole magento stores webpages was fixed at the last modified date of index.php. If I update index.php then the whole site last-modified date updates. This is a magento issue? causing a lot of issues for google crawl as the google thinks there has been no site updates and does not refresh the page content as it receives 304 error

**Comment by nadroj467** [comment]
@magento give me 2.4-develop instance

**Comment by bjornmeat** [comment]
@nadroj467 Can it be that the set beresp.grace  Varnish grace took effect during your upgrade, and then served stale content?

**Comment by engcom-Hotel** [comment]
Hello @nadroj467,

As per your below comment, it seems that this issue has been resolved. Can we close this issue?

> Problem solved by stripping the request header in Varnish
> 
> `sub vcl_recv { unset req.http.If-Modified-Since;`
> 
> And the response header
> 
> `sub vcl_deliver { unset resp.http.Last-Modified;`

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nadroj467,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
