### ISSUE TITLE
Password reset link redirect to forgotPassword URL on Apple devices

### ISSUE THREAD

**Issue by groomershop-mt** [magento/magento2#34331]
From several weeks, customers have been reporting to us that they are having trouble resetting their account password. We checked and everything seemed to work fine, but more and more customers started reporting a problem with password reset saying that they are being "redirecting over and over".

Yesterday we analyzed the problem and were able to replicate it on the iPhone. We also analyzed customer reports and noticed that the submitters were Apple users - both iPhone (iOS) and Mac (MacOSX).

We managed to repeat the problem by opening the link to give a new password from the Gmail email client, going to Safari or Chrome. This is resulting in redirects:
from:
/ customer / account / createPassword /? token = ...
redirects (302) to:
/ customer / account / createPassword /
then redirects (302) to:
/ customer / account / forgotPassword /

The second redirect should not take place. As a result, the customer sees the form for entering the email address again, instead of the form for setting a new password. Has anyone encountered such a problem in the past time? It looks like it appeared after Apple changed it (introducing private browsing).

The problem do not occur when the link is being open e. g. on Windows or by holding the link (preview window on iOS).

**Comment by groomershop-mt** [comment]
The problem occur exactly, when you open the password reset link for second time - at first opening it seems to work, but when you open it second time then the user is being redirect to forgotPassword page.

**Comment by mageprashant** [comment]
@magento give me a magento 2.4.3 instance

**Comment by desaiuttam** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Dear <user>,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by markPostema** [comment]
@luancschmitz Did you ever solve this? I have the same problem with Magento 2.4.5 on PHP8
