### ISSUE TITLE
Unable to Export Advanced Prices

### ISSUE THREAD

**Issue by onepack** [magento/magento2#34336]
### Preconditions (*)

1. M2.4.2-p1
2.

### Steps to reproduce (*)

1. Just export advanced prices via the export functionality
2.

### Expected result (*)

1. Need to get a message that the export has finished that can be downloaded
2.

### Actual result (*)

1. Directly you get the message: Error during export process occurred Error during export process occurred. Please check logs for detail
2. No logs are available on the error, anywhere. So it's unclear what is causing this error so there is no easy way to bugfix the issue.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [S2 ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @onepack ,

Tried to reproduce it on Magento 2.4 Develop with latest branch . it works fine , not getting any error .
Kindly find the attached screenshot for reference.
Thanks
![Exporting_CSV](https://user-images.githubusercontent.com/51681379/137183508-7016a48e-44e7-4ab3-91cf-49f5fcf2932c.JPG)
