### ISSUE TITLE
Create Custom session and Initialize it preDispatch

### ISSUE THREAD

**Issue by SasiKiranK** [magento/magento2#3433]
I am unable to find dev docs for creating Custom Session and Initialize it before PreDispatch,
Like Customer session, Core Session, and Checkout Session
Thanks 
Sasikiran Kesavan

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
