### ISSUE TITLE
"Add New Template" button missing on Template section in Magento v2.4.3

### ISSUE THREAD

**Issue by guptarakesh2701** [magento/magento2#34340]
### Preconditions (*)
1. PHP Version: 7.4.9
2. MySQL Version: 8.0.26
3. Apache Version: 2.4.46
4. Magento Version: 2.4.3 (New installation)

### Steps to reproduce (*)
1. Magento Admin -> Content -> Elements -> Templates

### Expected result (*)
1. "Add New Template" button should be there.

### Actual result (*)
1. Missing the "Add New Template" button.
![magento-bug](https://user-images.githubusercontent.com/47495345/137251444-de0abf59-dfcb-428b-b913-680bb47a949b.png)

**Comment by mageprashant** [comment]
@magento give me 2.4.3-develop instance

**Comment by girija-kudupudi** [comment]
Hi @guptarakesh2701 ,

As per Magento, [Dev docs](https://docs.magento.com/user-guide/cms/page-builder-templates.html) Add Template button is not available in Content > Elements > Templates which is current Magento behavior.
User have to navigate to the [Page Builder stage](https://docs.magento.com/user-guide/cms/page-builder-workspace.html#stage) to access the content that we want to save as a template.
Kindly refer the above links for further understanding of the same.
Thank you.
