### ISSUE TITLE
404 error when you switch store views from a view that has a url key to another that has not.

### ISSUE THREAD

**Issue by mstrigkos** [magento/magento2#3434]
The scenario is that your store has two store views or more. In the case that one catalog item (product/category) or page has a url key only in one of the two store views (the other is blank); when you are in this item's page and you switch between store views you get a 404 error. This occurs when you switch from a view that has a url key to the one that has not. You should have been redirected to the non sef url instead.

If I find a solution I will make a pull request.

**Comment by veloraven** [comment]
@mstrigkos thank you for your report.
Please, provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
