### ISSUE TITLE
Multiple store category name behaving unexpected

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#3435]
I have two store views (languages) A and B.
When adding a product in both languages A (default store view) and B (specific store view),
when I save the product and re-enter the product, the product category is written in language B even if i have my view in default or in language A.
This also happens when I export my products to csv. No category names of products are in default language A.
Perhaps this is causing the whole "product catalog" in the admin panel to freeze if I enter a lot of products.

**Comment by bgabrovsek** [comment]
Perhaps this is related to bug https://github.com/magento/magento2/issues/3426
Also, I did not mention i have my categories in both languages.

**Comment by antboiko** [comment]
Hi @bgabrovsek , thanks for reporting this issue. Internal ticket MAGETWO-49617 was created.

Best,
Anton.

**Comment by vzabaznov** [comment]
Hi @bgabrovsek seems like issue cannot be reproduced in fresh magento version, please check, and if you feel that not, write here, or open new issue
