### ISSUE TITLE
Can export in 2.4.3 with s3

### ISSUE THREAD

**Issue by JKair** [magento/magento2#34359]
### Preconditions (*)

1. magento 2.4.3

### Steps to reproduce (*)

1. use s3
2. export product in admin panel

### Expected result (*)

1. export normal

### Actual result (*)

1. the error log:
Warning: stream_get_meta_data(): supplied resource is not a valid stream resource in /vendor/magento/module-aws-s3/Driver/AwsS3.php on line 850 {"exception":"[object] (Exception(code: 0): Warning: stream_get_meta_data(): supplied resource is not a valid stream resource in /vendor/magento/module-aws-s3/Driver/AwsS3.php on line 850 at /vendor/magento/framework/App/ErrorHandler.php:61)"} []

2. In my s3 bucket:
![image](https://user-images.githubusercontent.com/5440088/137570601-3d9543ca-687c-4cbe-8c44-010fc7056dde.png)
It create many file and the size is 0b.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ * ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @JKair ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by veppywaqar** [comment]
Did u got any solution for this?
