### ISSUE TITLE
Calling and initializing JavaScript | '0' is not a valid selector : lib/web/mage/apply/scripts.js@processElems

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#34373]
### Preconditions (*)

1. magento 2.4
2. a new module with added script lines in *.phtml template file

### Steps to reproduce (*)

0- read : https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html
1. open : app/code/Magento/Customer/view/frontend/templates/form/register.phtml
2. add the below code at the end of the file:
 <script type="text/x-magento-init">
    $('#firstname').addClass('v-validate');
    $('#lastname').addClass('v-validate');
    { ".v-validate": { "Vky_Core/js/vky_custom": {} } }
</script>
3- build and open the register page : domain.com/customer/account/create/
4- open the debugger ( F12 in firefox ) and check the console window )

### Expected result (*)

1. it should work normally with no js errors

### Actual result (*)

1. it shows js error: "DOMException: Document.querySelectorAll: '0' is not a valid selector"

---
[Severity] = S2

**Comment by ihor-sviziev** [comment]
@salehawal, you merged the declarative and imperative declaration of the js.
You can read about it here: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html#init_script

**Comment by ihor-sviziev** [comment]
Hi @salehawal,
If you still have some questions - feel free to ask them at https://magento.stackexchange.com/.
I'm closing this as not an issue
