### ISSUE TITLE
Invalid customer address error 84711 adding item to cart and trying to confirm purchase

### ISSUE THREAD

**Issue by pdeboolw** [magento/magento2#34371]
### Expected result (*)

1. When I first hit checkout there should not be an error.
2. When I click 'Place Order' it should bring me to the screen to confirm purchase - without error!

### Actual result (*)

1. See screen shot
[Error 84711 Invalid customer address id.docx](https://github.com/magento/magento2/files/7365756/Error.84711.Invalid.customer.address.id.docx)

**Comment by pdeboolw** [comment]
[Error 84711 Invalid customer address id.docx](https://github.com/magento/magento2/files/7374249/Error.84711.Invalid.customer.address.id.docx)

I don't know why you got that error.  The other thing to note is that even though the order never got to the Confirm Purchase page, the order still went through.  It also still shows that it is in the cart.

**Comment by engcom-Delta** [comment]
Hi pdeboolw,

it seems coupon has been expired. Kindly review once.
Please find the attached screenshot for reference. 
![coupone_applied](https://user-images.githubusercontent.com/51681379/142172347-28aa017a-45e2-4477-9543-3adf3d7dbc5b.JPG)
in addition to this, we placed an order successfully. 
![OrderPlaced](https://user-images.githubusercontent.com/51681379/142172452-5e60001c-164e-4513-86c3-c994a28514ff.JPG)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
