### ISSUE TITLE
Warning: A non-numeric value encountered in vendor/magento/module-checkout/Controller/Sidebar/UpdateItemQty.php on line 69

### ISSUE THREAD

**Issue by Morgy93** [magento/magento2#34380]
### Preconditions (*)

Magento 2.4.3

### Steps to reproduce (*)

1. Open https://domain.com/checkout/sidebar/updateItemQty/?item_qty=error
2. See 500 error

### Expected result (*)

No 500 error

### Actual result (*)

`Warning: A non-numeric value encountered in /vendor/magento/module-checkout/Controller/Sidebar/UpdateItemQty.php on line 69`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Morgy93** [comment]
Works flawless: https://154f4b7285936dc3490238c6f0d5b01d-2-4-develop.instances.magento-community.engineering/checkout/sidebar/updateItemQty/?item_qty=error

Reproduced in latest 2.4-develop

**Comment by Melnychuk-Alexandr** [comment]
@magento I am working on this

**Comment by Melnychuk-Alexandr** [comment]
Hi @Morgy93 How did you get this url ? How did you get the value of "item_qty" string "error" ? Thanks!

**Comment by Melnychuk-Alexandr** [comment]
Hello @sidolov
This problem is reproducible and I think it serious problem.
I think we need to add additional validation for input params in controller.
If input params are invalid or request type (in the issue request type is GET instead of POST) is wrong we need to output message about it. For example "This link is not valid".
I think this is P1 or P2 priority issue.
Could you please help me with it.
Thank you in advance.

**Comment by hardiksinh** [comment]
I get similar issue when trying Update Attribute action from products grid on admin side in Magento 2.4.3.

`Exception #0 (Exception): Warning: A non-numeric value encountered in /var/www/html/magento2/vendor/magento/module-inventory-catalog-admin-ui/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 296`
Typecasting below to integer fixes the issue:
old:
`value="<?= $block->getDefaultConfigValue('notify_stock_qty') * 1 ?>"`
new:
`value="<?= (int) $block->getDefaultConfigValue('notify_stock_qty') * 1 ?>"`

**Comment by Melnychuk-Alexandr** [comment]
Hi @hardiksinh thank you for your comment! Please give me more information, for example: steps to reproduced.

**Comment by hardiksinh** [comment]
@Melnychuk-Alexandr Steps are really straight-forward to reproduce issue:
1. Login to admin panel of your Magento 2.4.3
2. Click on Catalog -> Products menu to go the products grid
3. Select products from the grid either by "Select All" or "Select All on This Page" or manually checking checkbox of product.
4. From the Actions drop-down on product grid, choose "Update Attributes".

If you are in developer mode, the page shows error as below:
`Exception #0 (Exception): Warning: A non-numeric value encountered in /var/www/html/magento2/vendor/magento/module-inventory-catalog-admin-ui/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 296`

**Comment by Melnychuk-Alexandr** [comment]
Hi @hardiksinh, thank you for your answer!
