### ISSUE TITLE
Unit test in Catalog/Test/Unit/Model/CategoryRepositoryTest.php fails

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3438]
It fails when I run the full suite, it doesn't fail if I just run the tests from this file stand alone. That is weird, but when I look at CategoryRepository:173 a foreach happens, while in the test the output of validate() is mocked to return false, that means a foreach() on false. 

```
Starting test 'Magento\Catalog\Test\Unit\Model\CategoryRepositoryTest::testSaveWithException'.
PHP Warning:  Invalid argument supplied for foreach() in /var/www/webshop/vendor/magento/module-catalog/Model/CategoryRepository.php on line 173
F
Warning: Invalid argument supplied for foreach() in /var/www/webshop/vendor/magento/module-catalog/Model/CategoryRepository.php on line 173
```

I'm not sure what is the best way to fix this, but I think checking for the appropriate output of the validate() function would be best. I submitted a PR to do that: #3437.

**Comment by katmoon** [comment]
The issue has been fixed in `MAGETWO-49647` and will be delivered soon.
Thank you for reporting!

Kateryna.

**Comment by katmoon** [comment]
The fix is delivered. Closing the ticket.
