### ISSUE TITLE
Adding an image via REST API throws 'The product can't be saved'.

### ISSUE THREAD

**Issue by TysvdHeuvel** [magento/magento2#34393]
This is something which worked perfectly well with all previous versions of Magento we and our customers have used. 
Our software allows ERP systems to create products in Magento and to add images as well. 
We are simply posting an entry to the /products/SKU/media API endpoint. This has worked until we now upgraded to 2.4.3. 
I have also tested this on multiple fresh instances of Magento 2.4.3. But whatever I try, I always get this unusable error message "The product can't be saved.".

### Preconditions (*)
Fresh Magento 2.4.3

### Steps to reproduce (*)
Try to add an image by using the REST API. 
POST https://my.domain.com/rest/all/V1/products/1900-S/media
```
{
    "entry": {
        "media_type": "image",
        "label": "1900-S.jpg",
        "position": 1,
        "disabled": false,
        "types": ["image", "small_image", "thumbnail"],
        "file": "1900-S",
        "content": {
            "base64_encoded_data": "/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABkAAD/4QMtaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA3LjEtYzAwMCA3OS5kYWJhY2JiLCAyMDIxLzA0LzE0LTAwOjM5OjQ0ICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgMjIuNSAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6NzEwNTlBQzkzMTkyMTFFQzlFQjlCMDFBQkZFNkY3RDYiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6NzEwNTlBQ0EzMTkyMTFFQzlFQjlCMDFBQkZFNkY3RDYiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo3MTA1OUFDNzMxOTIxMUVDOUVCOUIwMUFCRkU2RjdENiIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDo3MTA1OUFDODMxOTIxMUVDOUVCOUIwMUFCRkU2RjdENiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pv/uAA5BZG9iZQBkwAAAAAH/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgMDAwMDAwMDAwMBAQEBAQEBAgEBAgICAQICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA//AABEIAAEAAQMBEQACEQEDEQH/xABKAAEAAAAAAAAAAAAAAAAAAAAIAQEAAAAAAAAAAAAAAAAAAAAKEAEAAAAAAAAAAAAAAAAAAAAAEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwBpizBsP//Z",
            "type": "image/jpeg",
            "name": "1900-S.jpg"
        },
        "extension_attributes": null
    }
}
```

### Expected result (*)
Seeing the new image attached to the product. 

### Actual result (*)
Header: Status 400 Bad Request
Body: 
```
{
    "message": "The product can't be saved."
}

```
---

Severity: **S0** _- We have many users using our software to add images to their Magento products, and every customer which has upgraded to Magento 2.4.3 is now having this issue.

**Comment by TysvdHeuvel** [comment]
Thank you for processing this so quickly!

**Comment by engcom-Delta** [comment]
@magento give me 2.4.3 instance

**Comment by engcom-Delta** [comment]
Hi @engcom-Alfa ,
Verified on Magento 2.4.3 ,getting different error with response code 400.Kindly find the attached screenshot.
![Error_different_400](https://user-images.githubusercontent.com/51681379/139826973-24e51911-5e74-4b5c-9c4c-e65410abfda1.JPG)
Response:
{
    "message": "One or more input exceptions have occurred.",
    "errors": [
        {
            "message": "\"%fieldName\" is required. Enter and try again.",
            "parameters": {
                "fieldName": "sku"
            }
        },
        {
            "message": "\"%fieldName\" is required. Enter and try again.",
            "parameters": {
                "fieldName": "option"
            }
        }
    ]
}

**Comment by engcom-Alfa** [comment]
As per [above-comment](https://github.com/magento/magento2/issues/34393#issuecomment-957294348) , we have the same issue in 2.4.3 version as well.
Hi @TysvdHeuvel As per your description, there was no issue till 2.4.2 version only, and started facing issue with 2.4.3 version. Is my understanding correct here?
If so, we have check the same scenario once in 2.4.2 version and then we can set the priority of it.

**Comment by engcom-Delta** [comment]
Hi @TysvdHeuvel ,
We tried once again on Magento 2.4 Develop latest branch & 2.4.3 version as well.
it works fine , getting successful response code.
Here is attached snapshots for reference.
Magento 2.4 Develop: 
![2 4 Develop_SuccessfulResponse](https://user-images.githubusercontent.com/51681379/139834030-2bd8eee1-a3b4-4b99-a2a9-adb3a5ee2273.JPG)


Magento 2.4.3
----------------
https://2c833ad1e4e90190e781ca633ab36c9f-2-4-3.instances.magento-community.engineering/rest/all/V1/products/24-MB01/media
![2 4 3_SuccessfulResponse](https://user-images.githubusercontent.com/51681379/139834330-89452fd2-7312-4060-a0d7-b03241f503cd.JPG)

Response:
3423

Hence added label 'Needs update'

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
