### ISSUE TITLE
Changing customer email changes that customer's orders with CUSTOM emails.

### ISSUE THREAD

**Issue by bgorski** [magento/magento2#34397]
When you create an order for a registered customer, the email field comes pre-filled with that customer's email. Usually you won't change it when creating the order. Then, if it turns out that the customer calls the customer service and wants to change their email (maybe there was a typo when they registered, maybe they use a different email now etc.), it can be done on the customer edit page. It will affect the orders that customer placed - the email value will change on them as well. 

So far so good. 

However, when creating an order for a registered customer, you can change the email on the order. They may just want to use a different one for this particular order while not changing the email associated with their account (for example they may be buying a gift for their lover and don't want the spouse to find out while jealously browsing their email inbox). Those custom email addresses associated with orders should NOT change when you change the main email address on the account edit page in the admin panel. But it does, and it's a bug.

Then, you have no way of reverting just one order to the custom email address value. No workaround is possible for customer service, a code change is required by vendor's implementation team to change this behavior. 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. Register a customer
2. Create an order for that customer with an email address unchanged
3. Create an order for that customer with a custom email address - change the default one on the order creation page
4. Notice that the main customer email address remains remained unchanged by this
5. Change the main customer email address on the customer edit page in the admin panel

### Expected result (*)

1. Email address on the first order (one created with an unchanged email) is now changed
2. Email address on the 2nd order remains custom

### Actual result (*)

1. Both orders have their email address changed to the new value 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @bgorski 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-1536 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC1536&type=commits
Based on Jira, target version is 2.4.5
Thank you.
