### ISSUE TITLE
User can place duplicate orders using Paypal Express Checkout

### ISSUE THREAD

**Issue by kkhebbar89** [magento/magento2#34402]
1. Magento Version 2.4.3
2. Paypal Express Checkout

Steps to reproduce:
1. Add a product to cart and proceed to checkout
2. In Checkout select "Paypal Express Checkout", click "Paypal" button, proceed with Paypal Login and click pay now.
3. Paypal window closes and user can once again click on "Paypal" button and repeat the step 2 and place multiple duplicate orders.

Expected result
1. If the above steps is followed in Magento Version 2.3.6-p1, once the paypal window closes the user is  immediately taken to success page.
2. So the behavior should be same in Magento Version 2.4.3.

Actual result
1. In Magento Version 2.3.6-p1, the paypal window doesn't close until {{MAGENTO_URL}}/paypal/express/onAuthorization call is complete
2. In Magento Version 2.4.3, the paypal window closes immediately after {{MAGENTO_URL}}/paypal/express/onAuthorization is called and the user is made to wait on payment review page until the call is finished. So the user can click again on "Paypal button" and create duplicate orders.

Severity: **S0**
I think this is severe as the User is made to wait in payment review page blankly without any waiting message after successful payment leading to confusion. And also causes inconvenience for store owners to handle the duplicate orders.

**Comment by engcom-Hotel** [comment]
Hello @kkhebbar89,

We have tried to reproduce this issue in Magento 2.4-develop branch but it is not reproducible for us. It might be possible it resolved in the latest release. Please try to reproduce it in the latest version and let us know if it is reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @kkhebbar89,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
