### ISSUE TITLE
AddProductsToCart with File Upload Custom Option

### ISSUE THREAD

**Issue by lilbumblebear** [magento/magento2#34406]
*As a merchant I want to allow customers to upload an image with a product so that it can be customized.*

### AC
* When you upload an image this should be passed as a base64 encoded string to the server
* Server should save the file
* Custom option should be saved for the cart item

### Approved Schema
* ?

**Comment by engcom-Hotel** [comment]
Hi @lilbumblebear,

Thank you for reporting the issue.

Can you please elaborate on the issue? From the issue title and description, you want GraphQL AddProductsToCart mutation should have a file update option. Right?

Although which is confusing is that how product image upload will help in customization? Can you please help me understand the process that you want to build or perhaps some illustration if you could give?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @lilbumblebear,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by lilbumblebear** [comment]
This should not be closed. I apologize for my delay. 

Example of a customizable file upload:
A store sells a mug, which users can upload an image to add to the mug. 

This is functionality that exists in Magento's default custom options:
https://docs.magento.com/user-guide/catalog/settings-advanced-custom-options.html

Therefore, it should also be possible to use this functionality through graphql.
