### ISSUE TITLE
Deleting a custom option is crashing Magento 2.0.2 (Release) - No 3rd Party extensions

### ISSUE THREAD

**Issue by echh** [magento/magento2#3442]
### to reproduce:

1) add a simple product
2) add one custom option (Drop Down Type)
3) add 3 rows 
4) save
5) Delete the first custom option row 
The whole custom area in the backend is gone:
### the frontend shop crashed with errors:

``
Warning: Invalid argument supplied for foreach() in /webroots/wolke/shop/vendor/magento/module-catalog/Block/Product/View/Options.php on line 213
#0 /webroots/wolke/shop/vendor/magento/module-catalog/Block/Product/View/Options.php(213): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/webroots/wolke...', 213, Array)
#1 /webroots/wolke/shop/vendor/magento/module-catalog/view/frontend/templates/product/view/options.phtml(18): Magento\Catalog\Block\Product\View\Options->getJsonConfig()
#2 /webroots/wolke/shop/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/webroots/wolke...')
#3 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Options), '/webroots/wolke...', Array)
#4 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/webroots/wolke...')
#5 /webroots/wolke/shop/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#6 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#8 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#9 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#10 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#11 /webroots/wolke/shop/vendor/magento/framework/View/Element/AbstractBlock.php(501): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#12 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(778): Magento\Framework\View\Element\AbstractBlock->getChildHtml('', true)
#13 /webroots/wolke/shop/vendor/magento/module-catalog/view/frontend/templates/product/view/options/wrapper.phtml(15): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml('', true)
#14 /webroots/wolke/shop/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/webroots/wolke...')
#15 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/webroots/wolke...', Array)
#16 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/webroots/wolke...')
#17 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/webroots/wolke...')
#18 /webroots/wolke/shop/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#19 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#21 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#22 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#23 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#24 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#25 /webroots/wolke/shop/vendor/magento/framework/View/Element/AbstractBlock.php(532): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#26 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(791): Magento\Framework\View\Element\AbstractBlock->getChildChildHtml('options_contain...', '', true)
#27 /webroots/wolke/shop/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml(35): Magento\Catalog\Block\Product\View\Interceptor->getChildChildHtml('options_contain...')
#28 /webroots/wolke/shop/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/webroots/wolke...')
#29 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/webroots/wolke...', Array)
#30 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/webroots/wolke...')
#31 /webroots/wolke/shop/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/webroots/wolke...')
#32 /webroots/wolke/shop/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#33 /webroots/wolke/shop/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#35 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info')
#36 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info')
#37 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info')
#38 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info', true)
#39 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info')
#40 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('product.info.ma...')
#41 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...')
#42 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.ma...')
#43 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.ma...', true)
#44 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.ma...')
#45 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#46 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#47 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#48 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#49 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#50 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#51 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#52 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#53 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#54 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#55 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#56 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#57 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#58 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#59 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#60 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#61 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#62 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#63 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#64 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#65 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#66 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#67 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#68 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#69 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#70 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#71 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#72 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#73 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#74 /webroots/wolke/shop/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#75 [internal function]: Magento\Framework\View\Layout->getOutput()
#76 /webroots/wolke/shop/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#77 /webroots/wolke/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#78 /webroots/wolke/shop/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#79 /webroots/wolke/shop/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /webroots/wolke/shop/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#82 /webroots/wolke/shop/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#83 /webroots/wolke/shop/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#84 /webroots/wolke/shop/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#85 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#86 /webroots/wolke/shop/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#87 /webroots/wolke/shop/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#88 /webroots/wolke/shop/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#89 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#90 /webroots/wolke/shop/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#91 /webroots/wolke/shop/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#92 /webroots/wolke/shop/vendor/magento/framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#93 /webroots/wolke/shop/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#94 /webroots/wolke/shop/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#95 {main}

**Comment by keyurmd** [comment]
Yes, this issue also occur in backend.

**Comment by marissen-srj** [comment]
Same problem here. When deleting an option it makes the frontend crash. Custom option doesnt show up anymore in backend.

1 make new product
2 add custom option
a dropdown
b add three values
3 save product
4 delete first value/row
5 product crashes on frontend and custom option doesnt show anymore in backend

**Comment by marissen-srj** [comment]
NEW
When i make a new identical product with same name and SKU etc. this product will have the same error on frontpage. No need to add custom options first.

1 delete product with error on frontpage
2 create new product with identical values but no custom options
3 frontend crashes directley for this product

**Comment by magento-engcom-team** [comment]
@echh, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
