### ISSUE TITLE
Pagebuider encode html 

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#34420]
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Add a new CMS block/page
2. Add HTML code in PageBuilder and Save 
`<h2>text</h2>`
3. Check table cms_block / cms_page in database:
The content was encoded to:
`<div data-content-type="html" data-appearance="default" data-element="main">&lt;h2&gt;text&lt;/h2&gt;</div>`
4. Disable all Magento Pagebuider modules and use default text editor Tinymce 4

### Expected result (*)

The content show in:
1. Database: `<h2>text</h2>`
2. Backend - textarea: `<h2>text</h2>`
3. Text editor - tinymce 4: `text`
4. Frontend: `text`

### Actual result (*)

The content show in:
1. Database: `<div data-content-type="html" data-appearance="default" data-element="main">&lt;h2&gt;text&lt;/h2&gt;</div>`
2. Backend - textarea: `<div data-content-type="html" data-appearance="default" data-element="main">&lt;h2&gt;text&lt;/h2&gt;</div>` 
![Screenshot_1](https://user-images.githubusercontent.com/7834473/138711005-81fe5958-c458-491d-bdfe-0ed7006caa43.png)
3. Text editor - tinymce 4: `<h2>text</h2>`
![Screenshot_2](https://user-images.githubusercontent.com/7834473/138711044-a13b8560-c068-4227-98c9-b0959ab5b89e.png)
4. Frontend: `<h2>text</h2>` - layout break
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hi @minhluan259,

Thank you for reporting the issue.
We tried to reproduce it on Magento 2.4-develop.

We followed your steps and then tried to disable the Page Builder from admin, we get the alert popup regarding the impact of disabling.
![image](https://user-images.githubusercontent.com/51681618/143863737-b30556cb-26c0-4d63-a263-c0fe4d49e77e.png)

So it could be an expected behaviour of the system.

Thank you

**Comment by engcom-Hotel** [comment]
Dear @minhluan259,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by bmxmale** [comment]
Same problem here, page builder encode html content.

```
<div data-content-type="html" data-appearance="default" data-element="main">&lt;p&gt;&lt;strong&gt;Markizy okienne&lt;/strong&gt;
```

**Comment by antoniocarboni** [comment]
same problem with magento 2.4.6

**Comment by Nuranto** [comment]
Same problem in 2.4.6-p3
