### ISSUE TITLE
I am having almost the exact same issue in 2.4.3  when an order i being place in the admin order area, if the stored payment method is selected then we get the "Order saving error: Public hash should be defined"

### ISSUE THREAD

**Issue by flashtechusa** [magento/magento2#34424]
I am having almost the exact same issue in 2.4.3  when an order i being place in the admin order area, if the stored payment method is selected then we get the "Order saving error: Public hash should be defined"   

If i login as the customer on the front end the stored payment method works.

_Originally posted by @flashtechusa in https://github.com/magento/magento2/issues/32943#issuecomment-951343176_

**Comment by engcom-Delta** [comment]
Hi @flashtechusa,
Thank you for raising an issue .Kindly provide the steps to reproduce ,expected results ,actual results and screenshots for reference.
Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by WebHostingAce** [comment]
Same issue. We cant place orders via Admin Panel with the Stored Credit Cards (Braintree) 

Error - "Order saving error: Public hash should be defined"

This was working until we upgraded from 2.4.3-p1 to 2.4.3-p2

**Comment by leoho150899** [comment]
Hi everyone,
I have the same issue with M246p2. Any update on this issue.
