### ISSUE TITLE
Fix Unit tests to be compatible with PHP8.1

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#34441]
Fix Unit tests to be compatible with the upcoming PHP 8.1 release.
Need to run all unit tests on PHP8.1 environment and fix all issues (e.g. problems with Deprecation)

### Expected result (*)
Unit Tests build is green on PHP 7.4, 8.0, and 8.1 environments
Magento related issues fixed on PHP 8.1

### Actual result (*)
Errors and failures on PHP 8.1. env

**Comment by xmav** [comment]
Please exclude issues with "Deprecation Notice" from the scope of this ticket

**Comment by andrewbess** [comment]
Closed due to fixes have been delivered into 2.4-develop
