### ISSUE TITLE
after update from 2.3.5-p1 to 2.4.3-p1 customers cant login anymore

### ISSUE THREAD

**Issue by SimonGSGmbH** [magento/magento2#34449]
### Preconditions (*)

1. Magento CE updated to 2.4.3-p1
2. Nginx
3. PHP 7.4
4. Redis Cache

### Steps to reproduce (*)

1. update Magento including Modules and Extensions from 2.3.5-p1 to 2.4.3-p1
2. go to customer/account
3. Exception thrown "main.ERROR: User Deprecated Functionality: Session ID is not used as URL parameter anymore. in /var/www/clients/client1/web12/web/magento/vendor/magento/framework/Session/SidResolver.php on line 106"

### Expected result (*)

1. customer is redirected to login and able to login

### Actual result (*)

1. Exception thrown, Report generated

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @SimonGSGmbH,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
