### ISSUE TITLE
Missing product_id on is_salable filter for wishlist

### ISSUE THREAD

**Issue by brudev** [magento/magento2#34448]
### Preconditions (*)

1. Magento 2.4.1
2. Magento_Wishlist enabled

### Steps to reproduce (*)

1. Create 2 products of any kind.
2. Add those two products to a customer wishlist.
3. On adminhtml, edit the customer and access "Manage Shopping Cart".

### Expected result (*)

1. Adminhtml cart management screen.
![Screenshot from 2021-10-26 17-47-19](https://user-images.githubusercontent.com/9268132/138958517-1061e3b0-b28e-447d-aac4-db102b4a338a.png)

### Actual result (*)

1. The error message "An error has occurred. See error log for details." appears.
![Screenshot from 2021-10-26 17-38-31](https://user-images.githubusercontent.com/9268132/138957362-11ca1f2b-c46a-4b13-9d4d-edd6d66b2989.png)

### What i found debuggin
On class __Magento\AdvancedCheckout\Block\Adminhtml\Manage\Accordion\Wishlist__, on __getItemsCollection__ function, there's a call to __setSalableFilter__ on the collection.
The collection is a __Magento\Wishlist\Model\ResourceModel\Item\Collection__.
During the collection load, the protected function ___renderFiltersBefore__ is called, but the _productSalable filter doesn't include the catalog_product_entity.entity_id to main_table.product_id relation, causing the rows to duplicate, and throwing "item with id N already exist on collection".
Since the method is protected, i couldn't write a plugin to fix this and overriding the class goes against good practices.
![Screenshot from 2021-10-26 17-49-22](https://user-images.githubusercontent.com/9268132/138958773-59182658-b23d-4aff-932a-34cc9bbc02d6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @brudev ,
We are closing this issue as there has been no latest update on the same.
Thank you.
