### ISSUE TITLE
The calendar won't work with some sections 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#34455]
### Preconditions (*)

1. The calendar at the section "vrijgezellenfeest" at our website www.tsjechiexperience.nl wont work
2.

### Steps to reproduce (*)

1. Go to the website www.tsjechiexperience.nl and at the menu click "vrijgezellenfeest" 
2. Click on a product (doesnt matter which one) and click to "voorkeursdatum" (that meand date in Dutch). It opens an agenda, but the data cant go further than this month. 

### Expected result (*)

1. I need the datums to work so our clients can plan theis activities
2.

### Actual result (*)

1. The datas wont go further in the calendar
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @TsjechieXperience,
We tried to retest it , in fact we observed that issue is reproducible .we are not able to select beyond the current month from the calendar widget. Unable to move to next month or previous month from the calendar widget.
Please find the attached video for reference and added the label 'Issue confirmed'



https://user-images.githubusercontent.com/51681379/140762324-7afb2a20-c9e4-489f-bf35-52dc18bd6646.mp4
Thanks

**Comment by engcom-Alfa** [comment]
Thanks for your contribution @TsjechieXperience 
Please provide me any additional steps that are missed in the description; for eg- Have you created any custom widget to enable the calendar as such?
HI @engcom-Delta Kindly test the same scenario in the Magento 2.4-develop instance. Before confirming the issue, that should be reproducible on Magento 2.4-develop instance!

**Comment by engcom-Hotel** [comment]
Hello @TsjechieXperience,

We have tried to reproduce this issue in Magento 2.4-develop branch but this is not reproducible for us. For us, the date picker is showing and we can navigate the date picker for any date. Please have a look at the below video for reference:

https://user-images.githubusercontent.com/51681618/140896308-1e7339ed-c0ae-4304-9274-6ff424bb1f51.mov


We have followed steps to display the date picker on the product detail page:
1. Added `Field` from customizable options as below:
![image](https://user-images.githubusercontent.com/51681618/140895567-3f8fa179-9a81-47e0-896e-27f5c8cbedef.png)
2. Edit `app/design/frontend/Magento/luma/Magento_Catalog/layout/catalog_product_view.xml` and add below `reference` in-between `body` tag:
`
<referenceContainer name="content">
            <block class="Magento\Framework\View\Element\Template"
                   name="custom.js" as="custom.js" template="Magento_Catalog::product/js.phtml"/>
        </referenceContainer>
`
3. Create new file `app/design/frontend/Magento/luma/Magento_Catalog/templates/product/js.phtml`, and below code in it:
`
<script type="text/javascript">
    require(["jquery", "mage/calendar"], function ($) {
        $('#options_2_text').datepicker({
                prevText: '&#x3c;zurück', prevStatus: '',
                prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                nextText: 'Vor&#x3e;', nextStatus: '',
                nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'],
                monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                dayNames: ['Sunday ', 'Monday', 'Tuesday ', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                showMonthAfterYear: false,
                dateFormat: 'd/m/yy'
            }
        );
    });
</script>
`


4. Clean the cache through the `bin/magento c:c` command.

Please try above steps and let us know if still you are facing the same issues.

**Comment by engcom-Hotel** [comment]
Dear @TsjechieXperience,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
