### ISSUE TITLE
Class media_image does not exist

### ISSUE THREAD

**Issue by chris-brabender** [magento/magento2#3445]
After a successful migration from 1.7.0.2 to EE 2.0.2 the following error is thrown when trying to edit any product:

```
Class media_image does not exist
#0 /vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('media_image')
#1 /vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('media_image')
#2 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('media_image')
#3 /vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('media_image', Array)
#4 /vendor/magento/framework/Data/Form/Element/Factory.php(81): Magento\Framework\ObjectManager\ObjectManager->create('media_image', Array)
#5 /vendor/magento/framework/Data/Form/AbstractForm.php(155): Magento\Framework\Data\Form\Element\Factory->create('media_image', Array)
```

Has anyone seen this issue or have a fix for it?

**Comment by gorillagroup** [comment]
Update - The migration tool doesn't seem to map the frontend_input_renderer column in the catalog_eav_attribute table.

I updated the column to be Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage where the attribute_id was my new image attribute.

Seems to be quite a few issues with the migration tool not populating the database properly.

**Comment by chris-brabender** [comment]
Update - The migration tool doesn't seem to map the frontend_input_renderer column in the catalog_eav_attribute table.

I updated the column to be Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage where the attribute_id was my new image attribute.

Seems to be quite a few issues with the migration tool not populating the database properly.

**Comment by agustincl** [comment]
Hello @chris-brabender, could you explain a little more in detail where you made the changes, what you fix, or where to update in database?

I'm using magento 2.0.7 and the migration is really painful.

**Comment by kandy** [comment]
Internal ticket for tracking progress MAGETWO-51381

**Comment by chris-brabender** [comment]
Hi @agustincl, I honestly wouldn't recommend this tool until the issues have been addressed by Magento. There are several places around the database where data just isn't mapped correctly.

But to fix this particular issue, the table "catalog_eav_attribute" has a column called "frontend_input_renderer".  In that table, find the new row for the newly created Image attribute (you may need to look up the eav_attribute table for the attribute_id), then set the frontend_input_renderer value to "Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage"

**Comment by baltechies** [comment]
I have same issue. I have upgraded magento1.9.2.2 database into magento2.0.7. 
But unable to add/edit any product. 

main.CRITICAL: Class media_image does not exist [] []
[2016-08-30 14:33:57] main.CRITICAL: Block product_tabs throws exception and cannot be rendered. [] []
[2016-08-30 14:33:57] main.CRITICAL: Block product_tabs throws exception and cannot be rendered. [] []
