### ISSUE TITLE
New admin account is disabled after a login attempt is made if the account's expiration date is greater than 2038

### ISSUE THREAD

**Issue by SinpietruAdrian** [magento/magento2#34463]
**Preconditions**

    Magento 2.4.3-p1 CE

**Steps to reproduce**

    Create an admin user (System - All Users - Add New User)and set the Expiration Date greater than the year 2038
    Try to login in the admin area with the newly created user

**Expected result**

    You are able to login in the admin area

**Actual result**

    You get an error stating the account doesn't exist / has been disabled

**PR of a workin solution**
    https://github.com/magento/magento2/pull/34462

**Comment by engcom-Alfa** [comment]
It needs to be re confirmed by internal team as well.
Thanks for raising the issue, and your collaboration & contribution!

**Comment by engcom-November** [comment]
This issue is reproducible on Magento 2.4-develop branch. Hence updating the description and confirming the issue.

**Comment by JettyRohanAditya** [comment]
@magento I am working on this

**Comment by JettyRohanAditya** [comment]
@magento add to contributors team

**Comment by JettyRohanAditya** [comment]
@magento give me 2.4-develop instance

**Comment by JettyRohanAditya** [comment]
I am getting this error message, rather than the one mentioned in the issue.

<img width="609" alt="Screenshot 2023-07-07 at 4 10 27 PM" src="https://github.com/magento/magento2/assets/136695508/cb93de49-b43c-4e49-8fff-a91329633e96">

**Comment by JettyRohanAditya** [comment]
I am not able to reproduce the issue

https://github.com/magento/magento2/assets/136695508/716cbf0d-c209-4ad6-bd4d-e2d3faf13867

**Comment by engcom-Bravo** [comment]
@JettyRohanAditya Thanks for your contribution!!

Hi @SinpietruAdrian,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence we are closing this issue.

Thanks.
