### ISSUE TITLE
State/Province Sorting of Magento2-jp in Admin/Sales doesn't work as expected. 

### ISSUE THREAD

**Issue by mkawachi** [magento/magento2#34460]
Preconditions (*)

Magento CE/Community 2.3.6 later with sample data is installed
Install https://github.com/magento/magento2-jp (Japanese feature extension)

Steps to reproduce (*)

1. Go to admin site. Select Sales> Orders -> Create New Order -> Create New Customer”
2. Choose Japan from Country list.
3. See the State/Province list.

Actual result:
The shown sort order is not expected. It seems to be sorted by UTF8 number.
wrong order from top5
三重県 (Mie)
京都府 (Kyouto)
佐賀県 (Saga)
兵庫県 (Hyougo)
北海道 (Hokkaido)

Expected result (*)
Japan state information is stored in the database by the correct order. And region_id is already stored correctly in database. so the final sort order should be same as region_id. (region_id by locale) 
correct order from top5 (this is Geographic order from north, and It's a legal definition in Japan.）  
北海道 (Hokkaido) 1108
青森県 (Aomori) 1109
岩手県 (Iwate) 1110
宮城県 (Miyagi) 1111
秋田県 (Akita) 1112

The same problem in another area was resolved by https://github.com/magento/magento2/issues/32996. Please also refer that since it has solution.

**Comment by engcom-November** [comment]
Hi @mkawachi ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and this behavior no longer exist on latest Magento versions. We dont have list of options for state field to select for Japan Country.
![image](https://user-images.githubusercontent.com/60198231/189347264-c1688fae-2894-457f-aa02-047478db76bb.png)
Kindly recheck the behavior on Magento 2.4-develop branch and let us know if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment]
hi @mkawachi ,
We are closing this issue as there has been no latest update on the same. Kindly create new issue if you are still facing any issues.
Thank you.
