### ISSUE TITLE
Not possible to order top menu items

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [magento/magento2#3446]
When I observe `page_block_html_topmenu_gethtml_before` event, just like `Magento\Catalog\ObserverAddCatalogToTopmenuItemsObserver` does, and add some items to the `top.menu`, I can't order the items I add (whether it should be displayed before or after category listing, for example).

I think it should be possible, since the "top menu" must be one of the first and most modified element on any website.

Maybe by adding a special `\Magento\Framework\DataObject` attribute "order" which will be used inside or before `Magento\Theme\Block\Html`'s `_getHtml` method, in a way to reorder the `\Magento\Framework\Data\Tree\Node` before rendering it ? 

Or even clearer : adding a `$_position` property to the `Node` class, and a non-mandatory variable to the `Node` class constructor, which could be used in a similar way I expressed before ?

Simple, non-breaking, no performance issue, really useful. Right ?

I can try to make a pull request if you accept this issue.

**Comment by Yonn-Trimoreau** [comment]
This issue may be resolved by fixing https://github.com/magento/magento2/issues/2354
But it still persists in a matter of simplicity

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Not-possible-to-order-top-menu-items/idi-p/45317).
