### ISSUE TITLE
Error in massive change order status [2.4.0]

### ISSUE THREAD

**Issue by PelirrojosinAlma** [magento/magento2#34474]
### Preconditions (*)

1. Magento 2.4.0
2. Installed on Litespeed Server with LiteMage installed.

### Steps to reproduce (*)

1. Go to SALES/(Under Operations) Orders
2. Select two or more order with "Processing" status.
3. Click on "Actions", then select "Change Order Status" and select a custom status (with unassign state)
4. Wait until magento response.

### Expected result (*)

1. Successful message: "A total of X record(s) status have been updated."
2. Selected orders with the selected order status assigned.

### Actual result (*)

1. ![imagen](https://user-images.githubusercontent.com/30088678/139337534-db9324e7-8498-48bf-a6af-c88dd9b010cb.png)
2. DEBUG LOG -> [2021-10-28 21:22:00] main.CRITICAL: Warning: Illegal offset type in isset or empty in /home/weplay/public_dev/lib/internal/Magento/Framework/DataObject.php on line 191 {"report_id":"d47c603fadaacd20bfc08805a1d71c2ae5eec22894e2589332f433e8b3f6fe34","exception":"[object] (Exception(code: 0): Warning: Illegal offset type in isset or empty in /home/weplay/public_dev/lib/internal/Magento/Framework/DataObject.php on line 191 at /home/weplay/public_dev/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @PelirrojosinAlma,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
