### ISSUE TITLE
admin | spinner keep loading forever in all areas

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#34476]
### Preconditions (*)
1. php 7.4
2. apache 2
3. magento 2.4-develop

### Steps to reproduce (*)

1. install magento 2.4-develop
2. login to admin

### Expected result (*)

1. normal page load

### Actual result (*)
1. 
![Screenshot from 2021-10-28 23-45-11](https://user-images.githubusercontent.com/3238761/139340957-144fdd79-3bf3-49bd-8413-c917af7d8cd2.png)
2.
![Screenshot from 2021-10-28 23-45-24](https://user-images.githubusercontent.com/3238761/139340978-0a6ff438-4ebf-43a9-807e-3c5bbeb31bf1.png)
3
![Screenshot from 2021-10-28 23-45-50](https://user-images.githubusercontent.com/3238761/139340996-d26457dc-bee1-480f-bfe5-103098e0820a.png)

---
- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround.

**Comment by salehawal** [comment]
the only difference is:
1- i never installed the demo data
2- i remove these modules below:
bin/magento module:disable Magento_Elasticsearch Magento_Elasticsearch6 Magento_Elasticsearch7 Magento_AdminAnalytics

**Comment by salehawal** [comment]
i did the following:
1- installed mysql legacy search engine from this source:
```
composer config repositories.swissup composer https://docs.swissuplabs.com/packages/
composer require swissup/module-search-mysql-legacy --prefer-source --ignore-platform-reqs
bin/magento module:enable Swissup_SearchMysqlLegacy Swissup_Core
bin/magento config:set catalog/search/engine 'lmysql'
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento indexer:reindex catalogsearch_fulltext 
```

2- build and flush
```
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento indexer:reindex
bin/magento cache:flush
```

and still not resolved?

**Comment by salehawal** [comment]
do i need to install the demo data? it is still not loading all data-grid related pages ( orders - customers - catalog .. etc)

**Comment by salehawal** [comment]
@engcom-November 
i did pull the latest update now from 2.4-develop branch and still it is not working?

**Comment by salehawal** [comment]
update...

samesite cookie issue #34461 is not the cause of the problem and we fixed, now the real cause of the problem is not found yet?
![Screenshot from 2021-11-02 22-07-11](https://user-images.githubusercontent.com/3238761/139946353-6d86ac44-8273-4b7c-a4e7-225d028362b6.png)
![Screenshot from 2021-11-02 22-06-58](https://user-images.githubusercontent.com/3238761/139946357-a613dc3d-541b-4bb7-b363-872628e758e5.png)

**Comment by engcom-November** [comment]
Hi @salehawal ,

Magento requires elastic Search modules enabled. Kindly refer the [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) elastic Search compatible version to support for specific Magento 2.4.x version.
Elastic Search configuration is must for all Magento 2.4.x versions.
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html
Thank you

**Comment by salehawal** [comment]
> Hi @salehawal ,
> 
> Magento requires elastic Search modules enabled. Kindly refer the [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) elastic Search compatible version to support for specific Magento 2.4.x version. Elastic Search configuration is must for all Magento 2.4.x versions. https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html Thank you

i did install it but that did not resolve the problem?

**Comment by engcom-November** [comment]
Hi @salehawal ,
Please try running below commands step by step from Magento root directory
> rm -rf var/* generated/* pub/static/*
> chmod -R 777 var/ generated/ pub/static/
> php bin/magento setup:upgrade
> php bin/magento setup:di:compile
> chmod -R 777 var/ generated/ pub/static/
> php bin/magento setup:static-content:deploy -f
> php bin/magento indexer:reindex
> php bin/magento cache:flush
> chmod -R 777 var/* generated/ pub/*
> chmod -R 777 /var/www/html/magento2
If you are still facing issues, kindly provide more details of Configuration/environment setup.
Thank you.

**Comment by engcom-November** [comment]
Hi @salehawal ,
We are closing this issue as there has been no latest update on the same.
Thank you.
