### ISSUE TITLE
jwt_auth_revoked doesn't exist

### ISSUE THREAD

**Issue by snez** [magento/magento2#34481]
In an integration test, I get the following error:

`>>> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'm2_integration_tests.jwt_auth_revoked' doesn't exist, query was: INSERT  INTO `jwt_auth_revoked` (`user_type_id`,`user_id`,`revoke_before`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `user_type_id` = VALUES(`user_type_id`), `user_id` = VALUES(`user_id`), `revoke_before` = VALUES(`revoke_before`)`

The code which triggers the error is:

```
$repository = $objectManager->create(\Magento\Customer\Api\CustomerRepositoryInterface::class);
$registry = $objectManager->get(\Magento\Framework\Registry::class);
$area = $registry->registry('isSecureArea');
if (!$area)
    $registry->register('isSecureArea', true);

$customer = $repository->get('customer@example.com');
$repository->delete($customer);
```

The problem is highlighted below - getTableName() does not return the db table prefix when called from within an integration test data fixture:

```diff
diff --git a/app/code/Magento/JwtUserToken/Model/ResourceModel/RevokedRepository.php b/app/code/Magento/JwtUserToken/Model/ResourceModel/RevokedRepository.php
index d948463018b..f0b273a3682 100644
--- a/app/code/Magento/JwtUserToken/Model/ResourceModel/RevokedRepository.php
+++ b/app/code/Magento/JwtUserToken/Model/ResourceModel/RevokedRepository.php
@@ -38,7 +38,7 @@ class RevokedRepository implements RevokedRepositoryInterface
     public function saveRevoked(Revoked $revoked): void
     {
         $conn = $this->getAdapter();
-        $table = $conn->getTableName(self::TABLE);
+        $table = $conn->getTableNameWithPrefix(self::TABLE);

         $conn->insertOnDuplicate($table, $revoked->getData(), array_keys($revoked->getData()));
     }
@@ -49,7 +49,7 @@ class RevokedRepository implements RevokedRepositoryInterface
     public function findRevoked(int $userTypeId, int $userId): ?Revoked
     {
         $conn = $this->getAdapter();
-        $table = $conn->getTableName(self::TABLE);
+        $table = $conn->getTableNameWithPrefix(self::TABLE);

         $data = $conn->fetchRow(
             $conn->select()
```

### Preconditions (*)

1. Magento 2.4.x
2. Database tables must use a prefix
3. Must run the example code in an integration test

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @snez,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by chapagain** [comment]
https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/reference/#243---244
```
Database Changes

jwt_auth_revoked | Table was added
```

Creating the `jwt_auth_revoked` table should solve the issue:

```
CREATE TABLE `jwt_auth_revoked` (
  `user_type_id` int(10) unsigned NOT NULL COMMENT 'User Type ID',
  `user_id` int(10) unsigned NOT NULL COMMENT 'User ID',
  `revoke_before` bigint(20) unsigned NOT NULL COMMENT 'Not accepting tokens issued before this timestamp',
  PRIMARY KEY (`user_type_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Holds revoked JWT authentication data';
```
