### ISSUE TITLE
Price cart rules problem

### ISSUE THREAD

**Issue by mateuszadd** [magento/magento2#34480]
Hi, 
i have a problem with price cart rules. 

I mean, i have general discount connected with multi buy. 
If customer buy 3 or more products get 10%, if 5 of more 20% and if 10 or more 30%. 
Another discount based on code "XYZ" and offer 50% for buy 10x specific product.
I want to disable general discount after using discount based od code XYZ.
How can i do that?

**Comment by krishprakash** [comment]
Hi @mateuszadd. Thank you for your report.
Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or magento [stack exchange](https://magento.stackexchange.com) for general discuss about this problem
