### ISSUE TITLE
All OAuth Tokens Are Deleted When An Integration Is Deleted

### ISSUE THREAD

**Issue by gary287** [magento/magento2#3450]
When multiple integrations are defined and one is deleted, all tokens are deleted from the oauth_token table. The expected behavior is that the token associated with the integration that was deleted will be deleted. The current behavior is that all tokens for all integrations are deleted.

**Comment by arkadiych** [comment]
Internal issue MAGETWO-51112

**Comment by okorshenko** [comment]
@gary287 thank you for reporting the issue. MAGETWO-51112 was merged to develop branch.
