### ISSUE TITLE
Add fixes Magento to run on PHP 8.1

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#34505]
Need to fix Magento codebase to be able to launch it on PHP 8.1

### Preconditions (*)
Use PHP 8.1

### Expected result (*)
Successfully launch Magento on PHP 8.1 (and basic CLI commands).

### Actual result (*)
Fatal errors when trying to launch magento

**Comment by xmav** [comment]
Postponed till appropriate way for resolving issue with passing null to non-nullable arguments discovered
Deprecation notice will be suppressed for tests branches only for now
