### ISSUE TITLE
cannot add to cart

### ISSUE THREAD

**Issue by hankzhh** [magento/magento2#3452]
fresh magento v2.02 with sample data.
I firstly create a bundle product sku= test1, and I login in and add it to cart for test successfully.
then i changed this bundle product at the backend by removing some bundle items, and saved.
Then I cannot add any product into cart any more in the frontend. Until i removed all quote items from database tables, i can add products to cart in the frontend.

**Comment by ishakhsuvarov** [comment]
@hankzhh Thank you for reporting the issue.
Do you get any error messages or exceptions? Which Magento version are you using?
Any additional information and detailed steps to reproduce would be helpful as well.

**Comment by hankzhh** [comment]
@ishakhsuvarov 
Thank your reply.
I repeat it in magento v2.0.2 (nginx+phpv7.0.3):
1. create a bundle in the backend, sku=test1, with two options: test option 1 and test option 2. and "Ship Bundle Items" set to "seperately". 
test option 1 have 3 simple products(product1, product2 and produc3). test option 2 have 2 simple products(product4 and product5).
other setting are not changed.
2. in the front end, /test1.html, add this bundle to cart with option product2 and product5.
it can be added to cart successfully.
3. remove product 2 and product5 from test1 bundle product and save.
4. in the front end, any simple product cannot be added to cart.
there is an ajax call error:

GET /customer/section/load/?sections=cart%2Cmessages&update_section_id=false&_=1456254555678 HTTP/1.1
Host: xxxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: application/json, text/javascript, _/_; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://xxxxxxx/strive-shoulder-pack.html
Cookie: __insp_slim=1454605212149; _ga=GA1.2.1796440809.1433281922; __insp_uid=2559916907; fbm_1628401260728929=base_domain=.xxxxxx.com; __insp_wid=494547864; __insp_nv=false; __insp_ref=d; __insp_targlpu=http%3A%2F%2Fxxxxxx.com%2Fcheckout%2Fcart%2F; __insp_targlpt=Shopping%20Cart; __insp_pad=39; __insp_sid=485247463; private_content_version=39649b102f89f671907ee681e23178db; mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; form_key=SIQpmeUKXcuAZjXT; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; mage-cache-sessid=true; PHPSESSID=91h2u2notvhmkil4r8ppo1k4j1; section_data_ids=%7B%22directory-data%22%3A1456254347%2C%22messages%22%3A1456258466%2C%22customer%22%3A1456254347%2C%22compare-products%22%3A1456254347%2C%22last-ordered-items%22%3A1456254347%2C%22cart%22%3A1456258466%2C%22review%22%3A1456254347%2C%22wishlist%22%3A1456254347%7D
Connection: keep-alive

Response:
HTTP/1.1 400 Bad Request
Server: nginx/1.9.11
Date: Tue, 23 Feb 2016 19:09:06 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.0.3
Set-Cookie: form_key=SIQpmeUKXcuAZjXT; expires=Tue, 23-Feb-2016 20:09:06 GMT; Max-Age=3600; path=/; domain=xxxxx.com
Pragma: no-cache
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Expires: Mon, 23 Feb 2015 19:09:06 GMT
X-Magento-Tags: FPC
X-Frame-Options: SAMEORIGIN
Content-Encoding: gzip
Vary: Accept-Encoding

Response Body:
{"message":"The options you selected are not available."}

**Comment by ishakhsuvarov** [comment]
@hankzhh This issue is already fixed in the `develop` branch. Fix will be delivered in the scope of the next release, meanwhile you may use [commit](https://github.com/magento/magento2/commit/c07b2023928685ef87fff914f5cdf4941b52f2d2) `c07b2023928685ef87fff914f5cdf4941b52f2d2` as a hotfix.

**Comment by ishakhsuvarov** [comment]
@hankzhh Closing this ticket for now, please feel free to reopen if you have any additional questions.
Thank you.
