### ISSUE TITLE
increment_id column in sales_order table too short?

### ISSUE THREAD

**Issue by hans-vereyken** [magento/magento2#34521]
While testing a marketplace integration we stumbled upon the fact that the 3rd party extension is expecting the increment_id to be 50 characters. It tries to save an increment_id of > 32 characters into the sales_order column. It's an easy workaround, but it feels like an oversight in the Magento core code:
Looking at all increment_id columns and there length, only sales_order.increment_id has a length of 32, all the others have a length of 50:
tablename:increment_id-field-length
**sales_order:32**
**sales_order_grid:50**
sales_shipment:50
sales_shipment_grid:50
sales_invoice:50
sales_invoice_grid:50
sales_creditmemo:50
sales_creditmemo_grid:50

The difference between sales_order an sales_order_grid bothers me the most :-)
Also increment_id columns in other modules (eg: Customer) have a length of 50.
Is it an oversight or is there a good reason for the sales_order.increment_id to be only 32 characters in length? For me it's a bug.
Thx to https://github.com/vacla He found the bug.

### Preconditions (*)

1. Magento 2.4.x (2.4-develop)

### Steps to reproduce (*)

1. Install certain 3rd party modules assuming sales_order.increment_id has a length of 50 characters

### Expected result (*)

1. An increment_id of 50 characters is save completely

### Actual result (*)

1. Only 32 characters of an increment_id of 50 characters is saved

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @hans-vereyken,
Could you please specify the 3rd party extension which you had tried to reproduce this issue?

In fact , I checked in Data base for the columns specified with respect to table names.

![order_grid_table](https://user-images.githubusercontent.com/51681379/140272103-68ba1692-7ccc-4ad4-a72c-bc517886b017.JPG)
![sales_order](https://user-images.githubusercontent.com/51681379/140272115-96090ac6-9dff-4eaa-9b6a-023677363c6c.JPG)
![column_incremntId](https://user-images.githubusercontent.com/51681379/140272126-2ef8207c-a1b8-4d7a-a1d5-6eaf027b9ec9.JPG)

Hence added the label 'Needs Update'

**Comment by hans-vereyken** [comment]
It's the Phoenix Media Tradebyte Connector module (Phoenix_TradebyteConnector), but it's proprietary, so I can't provide you the code.
The module takes the CHANNEL_ID from an order in Tradebyte (tb.one) and places it in the sales_order.increment_id field. Such a CHANNEL_ID can be 50 characters and is used as an identifier for syncing further order updates (payment, invoicing, shipment, credit memo...). It fails because the identifier saved in the increment_id is not complete due to the column is only allowing 32 characters.
We fixed it in the code by altering the Phoenix_TradebyteConnector module, but yet it feels like this is a bug on the Magento side since all increment_id columns in various tables, including the sales_order_grid has a length of 50 whereas the sales_order.increment_id has a length of only 32 characters.

**Comment by vacla** [comment]
@engcom-Delta I don't have access to this issue but I was the one who found this originally, could it be possible to remove "Issue: needs update" with the above answer as answer for your question
