### ISSUE TITLE
Add fixes to make `jms/metadata` composer dependency compatible with PHP 8.1.

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34534]
### Description (*)
Some problems have been found in `jms/metadata` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/schmittjoh/metadata).

**Comment by SilinMykola** [comment]
@andrewbess On branch master this module already have needed changes.

**Comment by andrewbess** [comment]
Hello @SilinMykola 
Thank you for update
Issue closed due to update above
