### ISSUE TITLE
Fix Magento custom error handlers to ignore Deprecations for PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34532]
### Description (*)
We have a lot of errors when running Integration, WebApi and other tests due to https://wiki.php.net/rfc/deprecations_php_8_1.
Also, a lot of Magento features are broken in PHP 8.1.
We need to fix this problem using fix of the Magento custom error handlers in `bootstrap.php` files.

**Comment by ihor-sviziev** [comment]
Hi @andrewbess,
I think hiding deprecations might introduce security issues. I strongly NOT recommend doing so.

**Comment by xmav** [comment]
@ihor-sviziev Thats will not be merged to mainline. Thats temporary solution to unblock rest of the PHP8.1 related tasks. Eventually those deprecation notices will be fixed

**Comment by andrewbess** [comment]
Closed due to changes have been delivered to platform-health
