### ISSUE TITLE
Backend throws PHP Fatal TypeError when session storage is empty

### ISSUE THREAD

**Issue by pmzandbergen** [magento/magento2#34531]
**Description**
When the admin session storage is empty, a PHP Fatal TypeError occurs:
```
PHP Fatal error:  Uncaught TypeError: strtotime() expects parameter 1 to be string, null given in .../vendor/magento/module-security/Model/AdminSessionInfo.php:136
Stack trace:
#0 .../vendor/magento/module-security/Model/AdminSessionInfo.php(136): strtotime(NULL)
#1 .../vendor/magento/module-security/Model/AdminSessionInfo.php(119): Magento\Security\Model\AdminSessionInfo->isSessionExpired()
#2 .../vendor/magento/module-security/Model/AdminSessionInfo.php(108): Magento\Security\Model\AdminSessionInfo->checkActivity()
#3 .../vendor/magento/module-security/Model/Plugin/AuthSession.php(63): Magento\Security\Model\AdminSessionInfo->isLoggedInStatus()
#4 .../vendor/magento in .../vendor/magento/module-security/Model/AdminSessionInfo.php on line 136
```
Please note that line numbers might be different in the current version, the problem however still exists.

**Since**
_Introduced with MC-34197:_
https://github.com/magento/magento2/commit/67fae82c6278827f2c9b0f63083486a9d7740366
_Specific:_
https://github.com/magento/magento2/blob/6b196b5df43f63c7364f7e193709694abca576d0/app/code/Magento/Backend/Model/Auth/Session.php#L186

**Suggested Fix**
Return `true` if the session is blank:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Security/Model/AdminSessionInfo.php#L130
```
    public function isSessionExpired()
    {
        $lifetime = $this->securityConfig->getAdminSessionLifetime();
        $currentTime = $this->dateTime->gmtTimestamp();
        $lastUpdatedTime = $this->getUpdatedAt();
        if (empty($lastUpdatedTime)) {
            return true;
        }
        if (!is_numeric($lastUpdatedTime)) {
            $lastUpdatedTime = strtotime($lastUpdatedTime);
        }

        return $lastUpdatedTime <= ($currentTime - $lifetime) ? true : false;
    }
```

**Comment by simonmaass** [comment]
related... https://github.com/magento/magento2/issues/34415

**Comment by kanevbg** [comment]
Magento version 2.3.7-p2 has the same issue.

**Comment by albsa** [comment]
@kanevbg did you find any solution for it?

**Comment by albsa** [comment]
@kanevbg did you find any solution for it?

**Comment by kanhaiya5590** [comment]
Hi @albsa and @kanevbg,

https://github.com/magento/magento2/pull/34606/files

do have look on solution which added for 2.3.7 version

**Comment by kanevbg** [comment]
@albsa since than I created patch and already using on production. Let me help you
[HD-MDVA-42269-1.zip](https://github.com/magento/magento2/files/8449566/HD-MDVA-42269-1.zip)

**Comment by albsa** [comment]
@kanhaiya5590 i tried multiple times yesterdya with that patch, but composer kept failing with applying the patch. @kanevbg I am trying your hotfix right now, hoping it works.

**Comment by albsa** [comment]
@kanhaiya5590 i tried multiple times yesterdya with that patch, but composer kept failing with applying the patch. @kanevbg I am trying your hotfix right now, hoping it works.

**Comment by albsa** [comment]
@kanhaiya5590 @kanevbg Now I keep getting that the You current session has expired when signing in. Cleared cache, history cookies, etc. Did you guys also had this issue?

**Comment by albsa** [comment]
@kanhaiya5590 @kanevbg Now I keep getting that the You current session has expired when signing in. Cleared cache, history cookies, etc. Did you guys also had this issue?

**Comment by albsa** [comment]
For other people regarding this matter, if you applied this patch and still can't login, we had this issue https://magento.stackexchange.com/questions/353147/can-we-increase-the-system-security-session-size-at-admin-on-magento-2 

[2022-04-12 13:11:50] report.WARNING: Session size of 489033 exceeded allowed session max size of 400000.

Solved it by running this command on CLI bin/magento config:set system/security/max_session_size_admin 800000

**Comment by albsa** [comment]
For other people regarding this matter, if you applied this patch and still can't login, we had this issue https://magento.stackexchange.com/questions/353147/can-we-increase-the-system-security-session-size-at-admin-on-magento-2 

[2022-04-12 13:11:50] report.WARNING: Session size of 489033 exceeded allowed session max size of 400000.

Solved it by running this command on CLI bin/magento config:set system/security/max_session_size_admin 800000

**Comment by theiconnz** [comment]
Clear the cookies, and try again. It worked
