### ISSUE TITLE
Add fixes to make `league/flysystem` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34539]
### Description (*)
Some problems have been found in `league/flysystem` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/thephpleague/flysystem).

**Comment by SilinMykola** [comment]
@andrewbess I made a [PR](https://github.com/thephpleague/flysystem/pull/1374)

**Comment by andrewbess** [comment]
Changes have been delivered
