### ISSUE TITLE
Add fixes to make `elasticsearch/elasticsearch` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34533]
### Description (*)
Some problems have been found in `elasticsearch/elasticsearch` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/elastic/elasticsearch-php).

**Comment by xmav** [comment]
@magento export issue to Jira project AC as story

**Comment by karyna-tsymbal-atwix** [comment]
possible fix https://github.com/elastic/elasticsearch-php/pull/1175
