### ISSUE TITLE
GraphQL returns wrong product image URL

### ISSUE THREAD

**Issue by binbee** [magento/magento2#34540]
**Preconditions(*)**
1. Magento CE 2.4.3 installed with template
2. Created the category, products and all details
3. Test the category products and images in website. All are working fine in website
4. Tested the GraphQL with Altair and all products were returning with all images.
5. Update the product images with new image.
6. Website is working fine and all updated images are displaying in website.

**Steps to Reproduce(*)**
1. Open the Altair GrapghQl tool
2. Run the query
{
  products(search: "Seer Fish- Bengal Cut") {
    items {
      
      name
      sku
      
      manufacturer
      description {
        html
      }
      image {
        url
        label
        position
        disabled
      }
    }
  }
}

**Expected Result(*)**
1. Product image is coorect
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Chicken Dressed with Skin",
          "sku": "Chicken Dressed with Skin",
          "image": {
            "url": "http://xyxyx.com/media/catalog/product/cache/83edf9a8b211cb912125f83b4c5fde73/d/r/dressed-chicken-1.png",
            "label": "Chicken Dressed with Skin",
            "position": null,
            "disabled": null
          }
        }
}

**Actual Result (*)**
1. Product image not correct
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Chicken Dressed with Skin",
          "sku": "Chicken Dressed with Skin",
          "image": {
            "url": "http://xyxyx.com/media/catalog/product/cache/df6a81da379efbb616e3b27bc19215e0/d/r/dressed-chicken-1.png",
            "label": "Chicken Dressed with Skin",
            "position": null,
            "disabled": null
          }
        }
}

**Comment by binbee** [comment]
Self assigned this

**Comment by engcom-Hotel** [comment]
Hi @binbee,

Thank you for reporting the issue.

We tried to reproduce it on Magento 2.4-develop, But it's not reproducible.

Steps followed to reproduce this issue.

- Create a new category.
- Create a new product with image and select created Category.
- Try to get product data via GraphQl.
![image](https://user-images.githubusercontent.com/51681618/143863454-bceb183a-4436-4afc-9ccb-27f1ed521ae6.png)

- Now update the product image and see it's working on the website.
- Again get the product data via GraphQl and we can get updated product images.
![image](https://user-images.githubusercontent.com/51681618/143863499-23ec5036-05a1-4296-bc19-4a576f1314c0.png)

Please let us know in case we missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @binbee,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by miteshdhaduk1** [comment]
**Magento 2.4.4**

**small_image** URL returns the wrong cache hash in products and cart GraphQL.

**Comment by miteshdhaduk1** [comment]
> 

Fix by **Content > Design > Configuration > Store View > Product Image Watermarks** 

Proper configure the watermarks image or remove it, this fixes my cart page image issue.

**Comment by bogdanignat** [comment]
For anyone that did not find a solution for the diffrent hash cache, and i think this is happening just on custom themes.
Here is how u can use the view.xml settings and get the same hash.

1. Add ur module to app/code
2. In ur module etc make a schema.xml

`type CustomProductImageUrl {
    url: String
}

extend type ProductInterface {
    customProductImageUrl: CustomProductImageUrl @resolver(class: "MyModule\\ModuleName\\Model\\Resolver\\CustomProductImageUrl") @doc(description: "CustomProductImageUrl resolver for product image url.")
}
`

3. Create a resolver class 

`<?php

namespace MyModule\ModuleName\Model\Resolver;

use Magento\Catalog\Helper\Image as ImageHelper;
use Magento\Catalog\Model\ProductRepository;
use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Query\ResolverInterface;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Magento\Store\Model\App\Emulation;
use Magento\Store\Model\StoreManagerInterface;
use Psr\Log\LoggerInterface;

class CustomProductImageUrl implements ResolverInterface
{
    protected ProductRepository $productRepository;
    protected ImageHelper $imageHelper;
    protected Emulation $appEmulation;
    protected StoreManagerInterface $storeManager;

    public function __construct(
        private readonly LoggerInterface $logger,
        ProductRepository $productRepository,
        ImageHelper $imageHelper,
        Emulation $appEmulation,
        StoreManagerInterface $storeManager
    ) {
        $this->productRepository = $productRepository;
        $this->imageHelper = $imageHelper;
        $this->appEmulation = $appEmulation;
        $this->storeManager = $storeManager;
    }

    public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
    {
        // Check if the product data is available in the $value parameter
        if (!isset($value['model'])) {
            throw new \Exception("Product data is not available in the resolver context.");
        }

        $product = $value['model']; // 'model' is the product instance
        $storeId = $this->storeManager->getStore()->getId();

        try {
            $imageUrl = $this->getImageUrl($product, $storeId);
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
            throw new \Exception('Unable to retrieve the image URL.');
        }

        return [
            'url' => $imageUrl,
        ];
    }

    public function getImageUrl($product, $storeId): string
    {
        //get the image type from view.xml
        $imageType = 'category_page_grid';

        try {
            //use frontend area
            $this->appEmulation->startEnvironmentEmulation($storeId, \Magento\Framework\App\Area::AREA_FRONTEND, true);
            $imageUrl = $this->imageHelper->init($product, $imageType)->getUrl();
        } finally {
            //u need to emulate the env.
            $this->appEmulation->stopEnvironmentEmulation();
        }

        return $imageUrl;
    }

}
`

4. In ur query use the define resolver from schema
`query getAutoRelatedProducts($skus: [String!]) {
    products(filter: { sku: { in: $skus } }) {
        items {
            id
            sku
            name
            type_id
            small_image {
                label
            }
            **customProductImageUrl {
                url
            }**
            price_range {
                minimum_price {
                    regular_price {
                        value
                        currency
                    }
                    final_price {
                        value
                        currency
                    }
                    discount {
                        amount_off
                        percent_off
                    }
                }
            }
            url_rewrites {
                url
                parameters {
                    name
                    value
                }
            }
        }
    }
}
`

And thats it.
U will see that will generate the same hash cache like in the category page.

This is the part from view.xml

`            <image id="category_page_grid" type="small_image">
                <width>207</width>
                <height>207</height>
            </image>
`
