### ISSUE TITLE
PHP Version error do not send a proper code error

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#34545]
### Summary (*)

If the PHP version is not the one needed by Magento 2, we only get a message and a return code 200.

### Examples (*)

```php
//bootstrap.php
if (!defined('PHP_VERSION_ID') || PHP_VERSION_ID < 70300) {
    if (PHP_SAPI == 'cli') {
        echo 'Magento supports PHP 7.3.0 or later. ' .
            'Please read https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html';
    } else {
        echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <p>Magento supports PHP 7.3.0 or later. Please read
    <a target="_blank" href="https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html">
    Magento System Requirements</a>.
</div>
HTML;
    }
    exit(1);
}
```

It slows down the potential tracking of issues when multiple servers are involved. Health tracking tools will not see the error because the response is a 200.

I know that this is an infrastructure related issue but it could happen on misconfigured servers, and Magento could help to debug it faster.

The same happens when the Autoload is missing in index.php
 
```php
try {
    require __DIR__ . '/app/bootstrap.php';
} catch (\Exception $e) {
    echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
        <h3 style="margin:0;font-size:1.7em;font-weight:normal;text-transform:none;text-align:left;color:#2f2f2f;">
        Autoload error</h3>
    </div>
    <p>{$e->getMessage()}</p>
</div>
HTML;
    exit(1);
}
```

### Proposed solution

The else case could return an appropriate HTTP response code such as a 503.

```php
if (!defined('PHP_VERSION_ID') || PHP_VERSION_ID < 70300) {
    if (PHP_SAPI == 'cli') {
        echo 'Magento supports PHP 7.3.0 or later. ' .
            'Please read https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html';
    } else {
  http_response_code(503);
        echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <p>Magento supports PHP 7.3.0 or later. Please read
    <a target="_blank" href="https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html">
    Magento System Requirements</a>.
</div>
HTML;
    }
    exit(1);
}
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @MeCapron,

Thanks for posting the issue!

I agree with your point hence confirming this issue.

Thanks

**Comment by artskirk** [comment]
@magento I am working on this
