### ISSUE TITLE
[GraphQl] Cart error messages are faulty

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#34546]
### Preconditions (*)

1. Magento 2.4.2+

### Steps to reproduce (*)

1. Create a cart
2. Add 2 products to the cart with at least 4 quantities each.
3. Set the quantity of added products below the quantity in the cart.
4. Retrieve cart through graphql 
```
{
  cart(cart_id: "RQg4YPcQX1htp47j6GMpTKRshfY6SVm6") {
    items {
      id
      product {
        name
        sku
        stock_status
      }
      quantity
    }
  }
}
```

### Expected result (*)

1. A error message which tells me which item in the cart causes the error. So that we can give correct feedback to the Customer.
2. A cart with valid values for items.
3. An error message for each issue with the cart.

### Actual result (*)

1.
```
{
  "errors": [
    {
      "message": "The requested qty is not available",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cart": {
      "items": [
        null,
        {
          "id": "32",
          "product": {
            "name": "Strive Shoulder Pack",
            "sku": "24-MB04",
            "stock_status": "IN_STOCK"
          },
          "quantity": 3
        },
        {
          "id": "33",
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01",
            "stock_status": "IN_STOCK"
          },
          "quantity": 4
        }
      ]
    }
  }
}
```
2. In the items node there is a null entry, this only shows up when there is an error. In default Venia this breaks the cart page.
3. I assume the path node in the error node should reference the item it's affecting. It currently points to the above null value.
4. Only the first error of the cart shows up.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Hexmage,

Thanks for posting the issue!

I would like to suggest you add `stock_status`, so that it will give the exact situation of stock.

for eg:
The below query:

```
{
  cart(cart_id: "5VrDt8LhknXPP3ugJuXZZerItlVDrtB0") {
    items {
      id
      product {
        name
        sku
        stock_status
      }
      quantity
    }
  }
}
```
Will return:
```
{
  "errors": [
    {
      "message": "Some of the products are out of stock.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cart": {
      "items": [
        null,
        {
          "id": "12",
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01",
            "stock_status": "OUT_OF_STOCK"
          },
          "quantity": 1
        },
        {
          "id": "13",
          "product": {
            "name": "Strive Shoulder Pack",
            "sku": "24-MB04",
            "stock_status": "IN_STOCK"
          },
          "quantity": 1
        }
      ]
    }
  }
}
```

You can see `stock_status` as `OUT_OF_STOCK` where the product is out of stock.

Thanks

**Comment by Hexmage** [comment]
@engcom-Hotel 
But what if the stock of a product changes from 3 to 2 and I had 3 in my cart. stock_status won't help me identify what the problem is in that scenario.

It's nice that there are error messages in the cart response, but they need a second pass over. Because as they are now they aren't good enough.

**Comment by engcom-Hotel** [comment]
Hello @Hexmage,

Thanks for the reply!

This is the valid point, if the cart item is less in stock then proper handling is required. I have followed the below steps to reproduce the issue:

- Add 2 items in the cart with 4 quantities each
- Set the quantity of a product to 2 in the admin panel, it should be in the customer cart.
- Run the `cart` query:
```
{
  cart(cart_id: "RQg4YPcQX1htp47j6GMpTKRshfY6SVm6") {
    items {
      id
      product {
        name
        sku
        stock_status
      }
      quantity
    }
  }
}
```

- The response for the same is as follows:
```
{
  "errors": [
    {
      "message": "The requested qty is not available",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cart": {
      "items": [
        null,
        {
          "id": "32",
          "product": {
            "name": "Strive Shoulder Pack",
            "sku": "24-MB04",
            "stock_status": "IN_STOCK"
          },
          "quantity": 3
        },
        {
          "id": "33",
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01",
            "stock_status": "IN_STOCK"
          },
          "quantity": 4
        }
      ]
    }
  }
}
```
It should display which item has not enough quantity. 

Updating the main description as well.

Thanks

**Comment by Hexmage** [comment]
@engcom-Hotel I also consider the fact that a null object appears in the items node when an error occurs very crucial to resolve. As it currently breaks default Venia.

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Hexmage** [comment]
@Usik2203 I'd rather have something that has to be unique to identify the product, because the product name can be identical for products. Also your solution doesn't solve the null object that suddenly got added to the items array.

**Comment by alitopaloglu** [comment]
Any update about null value? I can still reproduce this on 2.4.3-p2

**Comment by Hexmage** [comment]
@alitopaloglu 
I've learned that the null value is the actual exception object. Which is handled by the resolver to make the error node in the response. But this node is never deleted after its handled. I'm currently testing some code on my own environment where I moved the Exception Object to a new node in the item that created it. But this will not work with default Venia.

**Comment by Hexmage** [comment]
@PauloPhagula 
Think they fixed it in https://github.com/magento/magento2-pwa which is a repo with pwa specific fixes because the normal magento repo doesn't update fast enough.

**Comment by marwan-corals** [comment]
@Hexmage I just checked and [magento2-pwa](https://github.com/magento/magento2-pwa) didnt fix the issue either

**Comment by marwan-corals** [comment]
@Hexmage are you willing to help here ?

**Comment by Hexmage** [comment]
@marwan-corals 
The Plugin
```<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Experius\CartFix\Plugin\Magento\QuoteGraphQl\Model\Resolver;

use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Exception\GraphQlNoSuchEntityException;
use Magento\Framework\GraphQl\Query\Uid;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Magento\Quote\Model\Quote;
use Magento\Quote\Model\Quote\Item as QuoteItem;
use Magento\QuoteGraphQl\Model\Cart\GetCartProducts;

/**
 * @inheritdoc
 */
class CartItems
{
    /**
     * @var GetCartProducts
     */
    private $getCartProducts;

    /** @var Uid */
    private $uidEncoder;

    /**
     * @param GetCartProducts $getCartProducts
     * @param Uid $uidEncoder
     */
    public function __construct(
        GetCartProducts $getCartProducts,
        Uid $uidEncoder
    ) {
        $this->getCartProducts = $getCartProducts;
        $this->uidEncoder = $uidEncoder;
    }

    /**
     * @inheritdoc
     */
    public function afterResolve($subject, $result, Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
    {
        if (!isset($value['model'])) {
            throw new LocalizedException(__('"model" value should be specified'));
        }
        /** @var Quote $cart */
        $cart = $value['model'];

        $itemsData = [];
        $cartProductsData = $this->getCartProductsData($cart);
        $cartItems = $cart->getAllVisibleItems();
        /** @var QuoteItem $cartItem */
        foreach ($cartItems as $cartItem) {
            $productId = $cartItem->getProduct()->getId();
            if (!isset($cartProductsData[$productId])) {
                $itemsData[] = new GraphQlNoSuchEntityException(
                    __("The product that was requested doesn't exist. Verify the product and try again.")
                );
                continue;
            }
            $productData = $cartProductsData[$productId];
            $errorMessages = null;
            if ($cart->getData('has_error')) {
                foreach ($cartItem->getErrorInfos() as $error) {
                    $errorMessages[] = $error;
                }
            }

            $itemsData[] = [
                'id' => $cartItem->getItemId(),
                'uid' => $this->uidEncoder->encode((string) $cartItem->getItemId()),
                'quantity' => $cartItem->getQty(),
                'product' => $productData,
                'errors' =>  $errorMessages,
                'model' => $cartItem,
            ];
        }
        return $itemsData;
    }

    /**
     * Get product data for cart items
     *
     * @param Quote $cart
     * @return array
     */
    private function getCartProductsData(Quote $cart): array
    {
        $products = $this->getCartProducts->execute($cart);
        $productsData = [];
        foreach ($products as $product) {
            $productsData[$product->getId()] = $product->getData();
            $productsData[$product->getId()]['model'] = $product;
            $productsData[$product->getId()]['uid'] = $this->uidEncoder->encode((string) $product->getId());
        }

        return $productsData;
    }
}
```
The schema.graphqls additions
```
interface CartItemInterface {
    errors: [Error]
}

type Error {
    origin: String
    type: Int
    message: String
}
```

**Comment by alexmtch** [comment]
They removed the module : https://github.com/magento/magento2-pwa/commit/96c5f5f2ed31865f0b87f096221ddb9245f194da

**Comment by Hexmage** [comment]
That explains a lot.

**Comment by marwan-corals** [comment]
Thanks, @Hexmage the provided code is helpful; one more note here is to add to di.xml

```
    <type name="Magento\QuoteGraphQl\Model\Resolver\CartItems">
        <plugin name="Magento_CartItems_Add_Source_Errors" type="PathTo\Your\Class\Resolver\CartItems" />
    </type>
```

**Comment by engcom-Lima** [comment]
Hi @Hexmage  ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue in `2.4-develop` but issue is not reproducible to me.

Followed below steps :

1. Create a cart
2. Add 2 products to the cart with at least 4 quantities each.
3. Set the quantity of added products below the quantity in the cart from admin.
4. Get cart  details through graphql query:
```
query {
  
  customerCart {
    id
    items {
      uid
      product {
        name
        sku
      }
      quantity
    }
  }
}
```
After running above query I am not getting any error message **`"message": "The requested qty is not available",`** as you have reported.
Below is the screenshot for your reference:
![image](https://user-images.githubusercontent.com/60198022/185880352-00af9a0b-1bc9-44c4-a3ef-4bcef14ed0c4.png)
If anything missing in above steps kindly provide the information.
Please note that I did PR changes but the response of step 4 was same.

Please test it in latest `2.4-develop` if you are facing any issue kindly provide the information.

Thanks

**Comment by Hexmage** [comment]
@engcom-Lima 
Feels like you don't have manage stock turned on. Because there should be an error message when the stock is below the available stock.

**Comment by engcom-Lima** [comment]
HI @Hexmage ,

I have tried to reproduce the issue in 2.4-develop and followed below steps but issue is not reproducible to me:

1. Create a cart
2. Add 2 products to the cart with at least 4 quantities each.
3. Set the quantity of added products below the quantity in the cart from admin.
4. Get cart details through graphql query:
```
query {
  
  customerCart {
    id
    items {
      uid
      product {
        name
        sku
      }
      quantity
    }
  }
}
```
5. Also Stores >> configuration >> Catalog >> inventory >>Product Stock Options >> Set Yes in Manage Stock.

Kindly provide me more information inorder to reproduce the isssue.
Also, please check in latest `2.4-develop` and inform us whether issue is reproducible or not.

Thanks

**Comment by engcom-Lima** [comment]
Hi @Hexmage ,

Thank for your contribution and collaboration.

Please provide more information required to reproduce the issue.

Thanks
