### ISSUE TITLE
Account Address Book invalid form key

### ISSUE THREAD

**Issue by Nas1k** [magento/magento2#3455]
Preconditions: I have logged customer on frontend (without addresses)
Step 2 reproduce:
1. Go to My Account -> Address Book (forward to Add New Address form)
2. Fill all required field
3. Submit form
Expected: Show page with my addresses
Actual: Show Add New Address form without any error message

PS. When I use debuger I can see condition on app/code/Magento/Customer/Controller/Address/FormPost.php:182 return true.

**Comment by Nas1k** [comment]
Hmm... bug fixed right now.. Some magic : )

**Comment by sevos1984** [comment]
magento is magical sometimes )

**Comment by dsolorzanoIBM** [comment]
I am experiencing this issue. Have any clue?
