### ISSUE TITLE
Add fixes to make `tomzx/php-semver-checker` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34573]
### Description (*)
Some problems have been found in `tomzx/php-semver-checker` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/tomzx/php-semver-checker).

**Comment by andrewbess** [comment]
The pull request with fixes have been created https://github.com/tomzx/php-semver-checker/pull/112

**Comment by xmav** [comment]
library partially upgraded. leftovers currently ignored in test builds to unblock testing

**Comment by andrewbess** [comment]
Closed due to PR has been created
