### ISSUE TITLE
Add fixes to make `webonyx/graphql-php` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34571]
### Description (*)
Some problems have been found in `webonyx/graphql-php` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/webonyx/graphql-php).

**Comment by SilinMykola** [comment]
@andrewbess On branch master this module already have needed changes.

**Comment by andrewbess** [comment]
Closed due to reason described above

**Comment by andrewbess** [comment]
Reopened due to require additional fixes in https://github.com/webonyx/graphql-php/blob/master/src/Error/Error.php#L302

**Comment by andrewbess** [comment]
The PR with fixes - https://github.com/webonyx/graphql-php/pull/1011

**Comment by andrewbess** [comment]
Closed due to fixes have been delivered
