### ISSUE TITLE
Add fixes to make `vlucas/phpdotenv` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34572]
### Description (*)
Some problems have been found in `vlucas/phpdotenv` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/vlucas/phpdotenv).

**Comment by xmav** [comment]
Please check that dependency still installed(use latest MFTF from develop branch in Magento)

**Comment by xmav** [comment]
`vlucas/phpdotenv` is no longer in the list of dependencies
