### ISSUE TITLE
Move to Shopping Cart doesn't reflect at a time while click Move to Shopping Cart link[ backend new order create]

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3458]
Hello,

Move to Shopping Cart doesn't reflect at a time while click on Move to Shopping Cart link. It reflect when we click Update Changes button.

To reproduce this issue
- Login into magento2 admin  panel.
- Click on Sales > Orders
- Click on Create New Order
- Select Appropriate customer & store view
- Click on Add Products & Select Appropriate product
- Go to Action header and select Move to Shopping Cart option & click on Update Items and Quantities.
- After completion of AJAX request added product doesn't reflect on shopping cart on left side from Shopping Cart block.

![new order orders operations sales magento admin](https://cloud.githubusercontent.com/assets/17308601/13136448/940bfe32-d63f-11e5-9442-07f38f10ca07.png)

**This is the bug because when we add to shopping cart product it reflect at a time on left side block of shopping cart.**

When we click on **Update Changes** button from left block[At the end] , Product display in shopping cart block, So there must ajax render issue.

**Comment by NadiyaS** [comment]
Hi @keyurshah070 ,
products are added to shopping cart correct on latest Magento version.
If you still have the same problem on latest version please provide more details to reproduce it.
Otherwise close this issue.

Thanks.

**Comment by keyurshah070** [comment]
Hi @NadiyaS 

Thank you for the response.

I have checked this issue on latest Magento2.2 version , But still it creats an issue. Please follow below step to reproduct this issue.
1. Login into your magento backend panel with your details.
2. Go to Sales > Orders 
3. Click on Create New Order button
4. Select appropriate customer.
5. Click on Add Products and select appropriate product.
6. After adding product you can able to see new product row in your Items Ordered grid.
7. Go to last column[Action] and click on dropdown and select Move to Shopping Cart and click on Update Items and Quantities .
8. **After completion of AJAX request you couldn't to see your added product into shopping cart block[ On left side, below the Customer's Activities]**
   ![issue_1](https://cloud.githubusercontent.com/assets/17308601/13353511/f1b59c6a-dcba-11e5-90c0-6344124e2e4b.png)

It should reflected on shopping cart block when you add the product.[You can check same scenario in Magento1 if you want to confirm] 

![1](https://cloud.githubusercontent.com/assets/17308601/13353595/6dd4f994-dcbb-11e5-83f2-1700ddbf6cb2.png)

Also, When you click on update changs button than it works fine.

**Comment by NadiyaS** [comment]
Hi @keyurshah070 ,
magento version 2.0.7 really has problem with reorder. But it was fixed on develop branch.
You can upgrade your code from develop branch or wait until next release.
Feel free to reopen this issue if you have encountered this bug on upgraded version.

**Comment by Bertolossi** [comment]
I still have this issue on version CE 2.0.8.
