### ISSUE TITLE
Fix disable autovivification on false

### ISSUE THREAD

**Issue by anzin** [magento/magento2#34589]
Auto-creation of arrays from false value is not allowed since PHP 8.1 - PHP RFC: Deprecate autovivification on false.

ToDo:

Fix all detected places in
 - [x] https://github.com/magento/magento2 
 - [x] https://github.com/magento/partners-magento2ee
 - [x] https://github.com/magento/partners-magento2b2b
 - [x] https://github.com/magento/partners-magento2-infrastructure
 - [x] https://github.com/magento/inventory
 - [x] https://github.com/magento/magento2-page-builder
 - [x] https://github.com/magento/magento2-page-builder-ee
 - [x] https://github.com/magento/security-package
 - [x] https://github.com/magento/adobe-stock-integration
- [x] https://github.com/magento/adobe-ims

**Comment by anzin** [comment]
@magento I am working on this

**Comment by andrewbess** [comment]
The repository https://github.com/magento/partners-magento2-infrastructure has been checked.
The problems weren't found.
