### ISSUE TITLE
Wrong Tax calculation on Creditmemo (under certain circumstances)

### ISSUE THREAD

**Issue by wilfriedwolf** [magento/magento2#34586]
### Preconditions (*)

1. 2.4.3
2. Create Creditmemo in Backend
3. Sometimes they can not be displayed as there is an Exception in the template (see below)

### Steps to reproduce (*)

1. Hard to reproduce, anyhow: If you have mainly zero tax articles and create creditmemos they can not be displayed (Exception in the template), if the order with the same ID as the creditmemo contains articles with taxes. 

### Expected result (*)

1. Creditmemos can all be displayed correctly

### Actual result (*)

1. Exception thrown in magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml:62 (trying to access method on array)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @wilfriedwolf ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
