### ISSUE TITLE
Persistent cart causes "Invalid state change requested" error

### ISSUE THREAD

**Issue by qlhu** [magento/magento2#34585]
### Preconditions (*)
1. Persistent Shopping Cart is enabled and Persistent Lifetime is configured longer than Cookie lifetime
2. Redis is configured for session and disable_locking = 1
3. Only a payment method is enabled

### Steps to reproduce (*)
1. Add a product to cart
2. Log in an account
3. Delete all cookies which will be expired no later than PHPSESSID
4. Visit checkout page and shipping form should be filled with default address of logged in account
5. Choose a shipping method
6. Press Next button
7. The only enabled payment method is selected and press place order button

### Expected result (*)
1. Order is placed and it redirects to success page

### Actual result (*)
1. Occasionally it raises error "Invalid state change requested" and displays friendly error message on the page
2. Customer can't place order until log in his account again

This issue happens to our site occasionally. After giving lots of tries to narrow down the issue, figured out it may be caused by the concurrent/overlap AJAX calls /V1/guest-carts/:cart_id/set-payment-information and /customer/section/load. The HTTP requests are triggered concurrently when customer presses Next button on Checkout - Shipping page. Why /V1/guest-carts/:cart_id/set-payment-information is triggered automatically is only a payment method be available.

- [Magento\Persistent\Observer\EmulateCustomerObserver](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Persistent/Observer/EmulateCustomerObserver.php)::execute() is triggered per every http request to front controller and it emulates customer by assign customer id to current session when persistent cart functions. The request to /V1/guest-carts/:cart_id/set-payment-information/customer/section/load triggers it.

- [Magento\Persistent\Model\Checkout\GuestPaymentInformationManagementPlugin](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Persistent/Model/Checkout/GuestPaymentInformationManagementPlugin.php)::beforeSavePaymentInformation() is triggered when payment is saved and it removes customer id from both session and quote.

If Magento\Persistent\Observer\EmulateCustomerObserver::execute() and Magento\Persistent\Model\Checkout\GuestPaymentInformationManagementPlugin::beforeSavePaymentInformation() are executed like the following sequence, the quote is converted to a guest quote but customer id is kept in session. After that, it will trigger "Invalid state change requested" error whenever it tries to update quote such as updating shipping information, add new product to cart and etc.

1. GuestPaymentInformationManagementPlugin loads session
2. EmulateCustomerObserver - loads session
3. GuestPaymentInformationManagementPlugin removes customer id from both session and quote
4. EmulateCustomerObserver - assigns customer id to session

This issue doesn't happen too often or even never to site with low http requests. I'm wondering if it's possible do the conversion from customer cart to guest cart at the beginning of place order because there would be none concurrent ajax calls triggered.

**Comment by engcom-Delta** [comment]
Hi @qlhu ,
We tried to reproduce the issue on Magento 2.4 Develop, unfortunately it is not reproducible. Hence request to review the provided steps.

Thanks

**Comment by qlhu** [comment]
@engcom-Delta ,
It's hard to reproduce in vanilla Magento installation. Probably our sites have 3rd party modules installed and many visitors. It's free to close this issue. But I do want to share the possibility of this issue. It may be good to think about a better way when converting customer's quote to guest quote because both Magento\Persistent\Observer\EmulateCustomerObserver::execute() and Magento\Persistent\Model\Checkout\GuestPaymentInformationManagementPlugin::beforeSavePaymentInformation() are able to execute concurrently and the possible issue would be the quote has been converted while customerId is still kept in the session.

**Comment by qlhu** [comment]
@engcom-Delta ,
It's hard to reproduce in vanilla Magento installation. Probably our sites have 3rd party modules installed and many visitors. It's free to close this issue. But I do want to share the possibility of this issue. It may be good to think about a better way when converting customer's quote to guest quote because both Magento\Persistent\Observer\EmulateCustomerObserver::execute() and Magento\Persistent\Model\Checkout\GuestPaymentInformationManagementPlugin::beforeSavePaymentInformation() are able to execute concurrently and the possible issue would be the quote has been converted while customerId is still kept in the session.

**Comment by engcom-Delta** [comment]
thanks for confirming @qlhu.we are closing this issue , Kindly raise new issue if required or free to re-open the issue.
