### ISSUE TITLE
Magento 2.0.2 Dashboard for All Store Views not show with multi store

### ISSUE THREAD

**Issue by balack** [magento/magento2#3459]
Hi guys!
I have website config multi store (english and Vietnam).
When view dashboard for each store (English or Vietnam) dashboard view very good - http://pasteboard.co/1DMhZAPB.png

But when I view dashboard for All Store Views is not show - http://pasteboard.co/1DMmuPCp.png

Can you help me, pls ?

Thanks

**Comment by arkadiych** [comment]
@balack, Could you check a value of the option "Use Aggregated Data" in Stores->Configuration->Sales->Sales->Dashboard ?

**Comment by balack** [comment]
@arkadiych, i have check yes http://pasteboard.co/1KxgO6He.png but it isn,t show

**Comment by arkadiych** [comment]
@balack, does it work, if  "Use Aggregated Data" = 'No' ?

**Comment by balack** [comment]
Yes, i have select "NO", it working, thank you so much

**Comment by arkadiych** [comment]
That's a problem with "Use Aggregated Data" setting. Internal issue MAGETWO-47255

**Comment by KrystynaKabannyk** [comment]
Hello @balack, the reported issue has been fixed in 2.0.5 patch release that's why I'm closing it. Thanks for your help! If you have additional questions or information feel free to create another issue!
