### ISSUE TITLE
Wrong url rewrite for store view after update category by native magento importer

### ISSUE THREAD

**Issue by modryk** [magento/magento2#34599]
Magento 2.3.5 p2 has problem with rewrites on multiple store views after update category product by native importer. We have noticed, that after product category has been updated by native importer, magento cron has create rewrite for each store views which redirect old_ulr_key to default_store_view_url_key.

**This problem does not exist when we update category manualy by admin panel.** 

### Preconditions (*)

1. Magento 2.3.5 p2 with several store views
2. Each product has different url_key on certain store views

### Steps to reproduce (*)

1. Install clear magento version
2. Create few store views
3. Import new products by magento importer to admin store view
4. Add those products to another store views
5. Change products url on each store view another than "Default" to different than "Default"
6. Update products categories by addiing new category using magento importer.

### Expected result (*)
1. Products will keep their urls_keys as they got on each store view. Ex: 
de - url_key: X-de (will have url: /X-de)
fr - url_key: X-fr (will have url: /X-fr)
default - url_key: X-default (will have url: /X-default)

### Actual result (*)
1. On each frontend store views after category update, product has default url address: /X-default because magento create rewrite to default url_key from old one.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hi @modryk ,
Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop but the import functionality is working as expected.

Steps followed to reproduce issue:

1. Created two store view - France(fr), India(ind).

2. Imported three products using the CSV file (Store -> Import -> Select Product).

3. Import the attached CSV file as per the store view (Use the attached CSV file *-fr,-ind).

4. Reindex the product using (bin/magento indexer:reindex) and clear the cache. 

5. Verify the product URL. 

6. Add a new category to any of the newly created store view (test-1). 

7. Update the new category name(test-1) in the CSV file for any of the newly created store view (use the attached CSV - catalog_product-ind-cat-update.csv). 

8. Reindex the product using (bin/magento indexer:reindex) and clear the cache. 

9. Verify the product URL for the store view.

Conclusion: The product URL is working as expected given in the CSV files.

Possible Solution: Do reindex after importing products.

If the issue still persists at your end then provide the issue details in depth also provide screenshots or video, accordingly I’ll try to reproduce it again.

[catalog_product-def.csv](https://github.com/magento/magento2/files/7538684/catalog_product-def.csv)
[catalog_product-fr.csv](https://github.com/magento/magento2/files/7538685/catalog_product-fr.csv)
[catalog_product-ind-cat-update.csv](https://github.com/magento/magento2/files/7538686/catalog_product-ind-cat-update.csv)
[catalog_product-ind.csv](https://github.com/magento/magento2/files/7538687/catalog_product-ind.csv)


Thanks

**Comment by engcom-Hotel** [comment]
Dear @modryk,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
