### ISSUE TITLE
Could Not Parse Elasticsearch URI

### ISSUE THREAD

**Issue by murtadha-ahmed** [magento/magento2#34597]
### Preconditions (*)

1. Magento Community V2.4.3-p1 hosted on AWS EC2
2. AWS OpenSearch V1

### Steps to reproduce (*)

1. Create OpenSearch Service in AWS
2. Configure OpenSearch to use master user and password
3. In Magento Configuration, set up the ElasticSearch Configuration to:
```
hostname: https://[yourOpenSearchHost]
port: 443
HTTP auth: yes
HTTP username: [yourUserName]
HTTP password: [yourPassword] 
```
4. Click on `test connection`

### Expected result (*)

A Success Message

### Actual result (*)

Message Box:
```
Attention

Could not parse URI: "https://[yourUsername]:[yourPassword]@[yourOpenSearchHost]/:443"
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Be aware that official OpenSearch support is not included in Magento yet. It's on [the roadmap](https://devdocs.magento.com/release/roadmap.html) though... (that doesn't mean it won't work, it probably means it wasn't fully tested yet)

But good to hear you got it working!
