### ISSUE TITLE
Add fixes to make `fgrosse/phpasn1` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34591]
### Description (*)
Some problems have been found in `fgrosse/phpasn1` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/FGrosse/PHPASN1).

**Comment by SilinMykola** [comment]
A PR with necessary changes have been made [https://github.com/fgrosse/PHPASN1/pull/87](https://github.com/fgrosse/PHPASN1/pull/87)
