### ISSUE TITLE
ReAdding configurable Item to cart

### ISSUE THREAD

**Issue by emrahuyanik** [magento/magento2#34594]
### Preconditions (*)

1. Magento version 2.4.3 ( might be lower version )
2. At least one Configurable product should be in the cart. 
3. Magento\Checkout\Model\Cart::save method should be triggered twice.

### Steps to reproduce (*)

1. Add configurable items to the cart.
2. Trigger an endpoint which is saving cart 2 times.

**Note for below**: I couldn't find any double cart saving at the same run time in OOTB, but Magento shouldn't remove and re-add configurable items. Therefore I am providing an example for the stripe module endpoint.

**Example 1:**
composer require stripe/module-payments

endpoint: rest/V1/stripe/payments/estimate_cart
requestBody
{
  "address": {
    "country": "GB",
    "city": "London",
    "postcode": ""
  }
}
(set PHPSESSID cookie when sending request)

**Example 2:** Instead of installing a third party module to reproduce the issue, we can create a custom controller with below code and trigger it by our own.

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get(\Magento\Checkout\Model\Cart::class);
$cart->save();
$cart->save();

### Expected result (*)

1. Configurable items should stay in the cart even $this->cart->save triggered twice

### Actual result (*)

1. Configurable item is being removed and reAdding again. created_at field is being updated in quote_item table.
2. It is causing an issue for info_buyRequest productOption.

---

We are using the official Stripe module with GooglePay and ApplePay. For express checkout, there are endpoints which are triggering $this->cart->save twice. 
\StripeIntegration\Payments\Api\Service::estimate_cart
\StripeIntegration\Payments\Api\Service::apply_shipping

If a customer adds a configurable product and placed an order with GooglePay, we are losing critical data which have been stored in info_buyRequest due to re-adding issue.

We debugged that issue to find root cause and realized the below method is the reason.

\Magento\Quote\Model\Quote\Item::compareOptions 

This method is comparing itemOptions and productOptions. If there is difference  
\Magento\Quote\Model\Quote::getItemByProduct is returning false.

According to above, it's re-adding.

**Solution Recommendation** : Adding attributes key as an excaptional product option.
\Magento\Quote\Model\Quote\Item
protected $_notRepresentOptions = ['info_buyRequest', 'attributes'];

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @emrahuyanik ,
Kindly provide more clarity on step# 2 which says endpoint, it would be great if you can specify the endpoint details.

Thanks

**Comment by emrahuyanik** [comment]
> Hi @emrahuyanik , Kindly provide more clarity on step# 2 which says endpoint, it would be great if you can specify the endpoint details.
> 
> Thanks

Hi @engcom-Delta 

Thanks for the reply. It is really a rare case but it is causing data lost.

I provided 2 alternative ways for reproducing the issue.

**Comment by mathiastervo** [comment]
I can confirm that this is an issue.

Im working on a project that has configurable products that have dynamic values, i.e. length in centimeters and width in centimeters. These are stored on the product 

I have a really ugly workaround that probably causes other issues but seems to work for the specific type of product Im testing with and that is to always return null from "www/vendor/magento/module-configurable-product/Model/Quote/Item/CartItemProcessor.php::convertToBuyRequest". Here I provide an example of how the data changes:

I hope that this helps, its rather a complex issue and I have no idea what the bes solution for it is, if I knew, I would fix it.

`{
  "method": "Magento\\ConfigurableProduct\\Model\\Quote\\Item\\CartItemProcessor::convertToBuyRequest",
  "line": 71,
  "buyRequestData": {
    "uenc": ",,",
    "product": "10837",
    "selected_configurable_option": "10838",
    "related_product": "",
    "item": "10837",
    "super_attribute": {
      "167": "316"
    },
    "extra_options": {
      "langd": "1000",
      "rullbredd": ""
    },
    "qty": 1,
    "original_qty": "1"
  }
}
{
  "method": "Magento\\ConfigurableProduct\\Model\\Quote\\Item\\CartItemProcessor::convertToBuyRequest",
  "line": 84,
  "options": [
    {
      "option_id": 167,
      "option_value": "316"
    }
  ],
  "itemOptions": [
    {
      "option_id": "1968",
      "item_id": "637",
      "product_id": "10837",
      "code": "info_buyRequest",
      "value": "{\"uenc\":\",,\",\"product\":\"10837\",\"selected_configurable_option\":\"10838\",\"related_product\":\"\",\"item\":\"10837\",\"super_attribute\":{\"167\":\"316\"},\"extra_options\":{\"langd\":\"1000\",\"rullbredd\":\"\"},\"qty\":\"1\"}"
    },
    {
      "option_id": "1969",
      "item_id": "637",
      "product_id": "10837",
      "code": "attributes",
      "value": "{\"167\":\"316\"}"
    },
    {
      "option_id": "1970",
      "item_id": "637",
      "product_id": "10838",
      "code": "product_qty_10838",
      "value": "1",
      "stock_state_result": {}
    },
    {
      "option_id": "1971",
      "item_id": "637",
      "product_id": "10838",
      "code": "simple_product",
      "value": "10838"
    },
    {
      "option_id": "1972",
      "item_id": "637",
      "product_id": "10837",
      "code": "additional_options",
      "value": "[{\"label\":\"L\\u00e4ngd\",\"value\":\"1000 cm\"}]"
    }
  ]
}
{
  "method": "Magento\\ConfigurableProduct\\Model\\Quote\\Item\\CartItemProcessor::convertToBuyRequest",
  "line": 71,
  "buyRequestData": {
    "super_attribute": {
      "167": "316"
    },
    "qty": 1,
    "reset_count": true,
    "original_qty": 1
  }
}
{
  "method": "Magento\\ConfigurableProduct\\Model\\Quote\\Item\\CartItemProcessor::convertToBuyRequest",
  "line": 84,
  "options": [],
  "itemOptions": [
    {
      "option_id": "1975",
      "item_id": "639",
      "product_id": "10837",
      "code": "info_buyRequest",
      "value": "{\"super_attribute\":{\"167\":\"316\"},\"qty\":1,\"reset_count\":true}"
    },
    {
      "option_id": "1976",
      "item_id": "639",
      "product_id": "10837",
      "code": "attributes",
      "value": "{\"167\":\"316\"}"
    },
    {
      "option_id": "1977",
      "item_id": "639",
      "product_id": "10838",
      "code": "product_qty_10838",
      "value": "1",
      "stock_state_result": {}
    },
    {
      "option_id": "1978",
      "item_id": "639",
      "product_id": "10838",
      "code": "simple_product",
      "value": "10838"
    }
  ]
}`

**Comment by engcom-Hotel** [comment]
Dear @emrahuyanik,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
