### ISSUE TITLE
Add fixes to make `allure-framework/allure-php-api` composer dependency compatible with PHP 8.1

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34592]
### Description (*)
Some problems have been found in `allure-framework/allure-php-api` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/allure-framework/allure-php-api).

**Comment by SilinMykola** [comment]
A PR with necessary changes have been made [https://github.com/allure-framework/allure-php-api/pull/81](https://github.com/allure-framework/allure-php-api/pull/81)

**Comment by andrewbess** [comment]
Closed due to fixes have been delivered into master branch
