### ISSUE TITLE
Proper Test Cases for Configurable/Simple Products

### ISSUE THREAD

**Issue by fr0x** [magento/magento2#346]
I've seen a few patches in regards to configurable products closed due to insufficient gains in load time in your unit testing.

You mentioned this setup in testing:
- Magento CE 1.7.0.1 with clear DB
- 2500 configurable products with 2 simple products as options per each configurable product

I assume that is then 5000 individual simple products (2 unique simple products per configurable product)? What were the number of unique super attributes for those simple products?  Some of these changes are in large part dependent on the number of super attributes returned.  If you only had 2 super attributes defined for those 5000 simple products (black and white) as opposed to multiple thousands (red, pink, cherry, rose, sunset, and on and on.....) these changes pan out quite a bit differently.

See Issue #293
https://github.com/magento/magento2/issues/293

**Comment by kokoc** [comment]
Thank you for proposal.
We will get back to you once we have the solution or answer.

Internal reference: MAGETWO-33574

**Comment by choukalos** [comment]
Moving 33574 under performance measurement epic 53797.

@fr0x In our market research we identified the average e-commerce site having 3 product options for configurable & bundled products.  We are currently using that when generating test fixtures with the performance tool kit.  The epic 53797 is intended to provide more generation control for test fixtures to address # of product options and # of super attributes that manage those permutations.

**Comment by kandy** [comment]
Now fixture for configurable product support any number of variation, so I close issue
