### ISSUE TITLE
Randomly product disappear from search and category on frontend 

### ISSUE THREAD

**Issue by nitindotsquares** [magento/magento2#34600]
We are facing the product disappear issue on magento 2.4.0 version 

Magento version 2.4.0

Total catalog size - 2.5 lekh product 
category - 1000
store - 7 
order - 2 lekh 
customer - 5 lekh

we are adding the products everyday on the website 

We facing the random product disappear issue on category page becasue of deadlock 

some time it happend when indexing in middle 

anyone have solution to prevent the deadlock or indexing solution so product dont disappear

**Comment by engcom-Hotel** [comment]
Hello @nitindotsquares,

Please let us know if you have any errors in the error log file.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nitindotsquares,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by nitindotsquares** [comment]
Hello @engcom-Hotel

Doesnt generating any logs in error logs
