### ISSUE TITLE
Update declared PHP version for Magento Extensions

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34609]
* Update composer.json files for each module of the Magento Github Extensions - set required php version to 
```json
"~7.4.0||~8.0.0||~8.1.0"
```

* [https://github.com/magento/partners-magento2b2b]()
* [https://github.com/magento/inventory]()
* [https://github.com/magento/adobe-stock-integration]()
* [https://github.com/magento/security-package]()
* [https://github.com/magento/security-package-b2b]() - community has no permissions
* [https://github.com/magento/magento2-page-builder]()
* [https://github.com/magento/magento2-page-builder-ee]()
* [https://github.com/magento/adobe-ims]()
* [https://github.com/magento/magento2-sample-data]()
* [https://github.com/magento/magento2-sample-data-ee]() - community has no permissions

**AC:**

* \Magento\Test\Integrity\ComposerTest::testValidComposerJson() is green
* Deliver changes to platform-health

**Comment by anzin** [comment]
@magento I am working on this

**Comment by andrewbess** [comment]
Closed due to changes have been delivered
