### ISSUE TITLE
Remember Me Not working

### ISSUE THREAD

**Issue by preeteshtavant** [magento/magento2#34602]
Magento 2.4.1 remember me not working

### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. Enable persistent cart and enable remember me
2. go to sing in page
3. click on remember me checkbox
4. enter credentials and login
5. after successful login, click on logout
6. again click on sign in

### Expected result (*)

1. It should show username and credentials auto fill, no need to enter credentials as we already selected remember me while login previously.

### Actual result (*)

1.  It should show username and credentials but its showing empty fields 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
**S2**

- [S2 ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @preeteshtavant,
We tried to reproduce the issue on Magento 2.4 Develop latest branch. issue is reproducible.
Please find the attached screenshot for reference. added the label  'Issue confirmed'.
![Enable_PersistantRememberme](https://user-images.githubusercontent.com/51681379/141225789-98bb3f87-00af-45fd-b372-6a5cb23dfcfe.JPG)
![RemeberMechecked](https://user-images.githubusercontent.com/51681379/141225798-0fc25d84-cdb1-46ba-a967-ba06b6591b26.JPG)

https://user-images.githubusercontent.com/51681379/141225844-bbc7e9c1-ffe9-44bf-b3d1-c1f29bd48b99.mp4

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by Usik2203** [comment]
Hello @preeteshtavant @engcom-Delta 

I have investigated reported issue and seems Expected result is Not Correct for this feature. 
**Enable "Remember Me"**  config in **Stores->Configuration->Customer->Persistent Shopping Cart->General Option** doesn't not provide auto filling functionality for **Email** and **Password** fields while logging to customer accout . 
These configurations using for other functionality 

https://docs.magento.com/user-guide/sales/cart-persistent-workflow.html 
https://docs.magento.com/user-guide/sales/cart-persistent.html


Thanks!

**Comment by preeteshtavant** [comment]
@Usik2203 
thanks for reply, i will go through those links but could you please clear me on below points

1. if expected result is incorrect than how @engcom-Delta mentioned that it is reproducible and confirmed.
2. Are you saying that if customer logged in by selecting this remember me option , he/she will never be logged automatically.
3. If expected result is incorrect than what about those articles

https://www.rootways.com/blog/how-to-enable-remember-me-on-the-login-page
https://meetanshi.com/blog/enable-disable-remember-me-functionality-in-magento/
https://www.magetop.com/blog/enable-remember-me-functionality-in-magento-2/
https://www.dckap.com/blog/how-to-add-remember-me-username-and-password-feature-in-magento-2/
https://www.expertwebadvisor.com/how-to-enable-remember-me-option-in-magento/

Could you please reply on this, will really appreciate  and thanks in advance

**Comment by Viper9x** [comment]
@preeteshtavant answer your questions:
1 and 4: @engcom-Delta were wrong. You can see, many people misunderstood the "Remember Me" feature on magento, included: Rootways, Metanshi, Magetop, Expertwebadvisor guys that you listed above.

When you hover on "What's this?" on the login/create an account page, it will show the tooltip, it said:

> Check "Remember Me" to access your shopping cart on this computer even if you are not signed in.

![Screen Shot 2022-01-08 at 22 16 01](https://user-images.githubusercontent.com/5556060/148649513-f18543f6-2d0e-4e20-96e9-c451b40ed766.png)

The blog post from dckap that you've mentioned above is already said:

> This feature is not available by default in Magento 2. This blog provides the code to add  ‘Remember me – Username and Password’ feature in Magento 2.

That means the feature "Remember email and password" is not available in magento 2 core, so they are talking about adding a customization to magento 2 core.

2. That's right.
3. No, it depends on the config in Persisten Shopping Cart config.
You can read more about this here: https://docs.magento.com/user-guide/sales/cart-persistent-workflow.html#persistent-cart-settings-and-effects

Can someone who is a maintainer close this github issue and the jira issue https://jira.corp.magento.com/browse/AC-1715 ?

**Comment by engcom-Delta** [comment]
Hi @Viper9x ,

As suggested by above comments . Closing the issue.
