### ISSUE TITLE
Tier prices for group visible after logout

### ISSUE THREAD

**Issue by 0xMatt** [magento/magento2#34615]
### Preconditions (*)

1. 2.4.3-p1
2. PHP 7.4 - CentOS 8

### Steps to reproduce (*)

1. Log in as customer within a specific group that has tier prices(e.g wholesale)
2. See tier prices for specific customer group
2. Log out
3. Tier prices from specific group visible for NOT_LOGGED_IN customer

### Expected result (*)

1. Expect tier prices for specific groups to disappear when a customer logs out

### Actual result (*)

1. Tier prices for specific group remain visible

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0xMatt** [comment]
@magento give me 2.4-develop instance

**Comment by 0xMatt** [comment]
Doesn't seem reproducible in 2.4-develop.

What was being used for the page cache on this instance, filesystem? Can this be changed to redis?

**Comment by engcom-Hotel** [comment]
Hi @0xMatt,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop/2.4.3/2.4.3-p1 but the tier price for customer group functionality is working as expected.
Steps followed to reproduce issue:

1. Go to Catalog -> product -> Select any product -> Click on the advance pricing -> setup customer group price (See the attached screenshot).

2. Verify the product price by login in as a customer and after login (See the attached screenshots).

3. We have tested the tier functionality with the file and Redis cache (Redis cache setup - https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html). For both of the caching system tier functionality works as expected. (See the attached screenshots.)

If the issue still persists at your end then please provide the screenshots or video, accordingly, I’ll try to reproduce it again.

<img width="1438" alt="Screenshot 2021-11-16 at 12 19 42 PM" src="https://user-images.githubusercontent.com/51681618/141943413-6604f305-27dd-45c9-aa46-12c888f5769c.png">
<img width="1438" alt="Screenshot 2021-11-16 at 12 20 18 PM" src="https://user-images.githubusercontent.com/51681618/141943433-7595cf7f-b3fb-4787-8b8e-1a23ff58aa62.png">
<img width="1438" alt="Screenshot 2021-11-16 at 12 20 39 PM" src="https://user-images.githubusercontent.com/51681618/141943440-d814e809-ff00-45af-87ad-da037924e9d4.png">
<img width="1438" alt="Screenshot 2021-11-16 at 12 21 12 PM" src="https://user-images.githubusercontent.com/51681618/141943443-3c723ef4-09a4-452c-a7d3-125d844a929c.png">


Thanks

**Comment by 0xMatt** [comment]
That should be my exact scenario. I hardly have any third party extensions or custom code modifications and am using stock Luma so I wonder what could be causing this.

I'll close this for now. Thanks for taking your time to reproduce my exact scenario to the best of my knowledge to try any reproduce this. Thanks.
