### ISSUE TITLE
Load values in di.xml from a helper class

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#34611]
### Summary (*)

Is it possible to load values in the di.xml from a helper class?

I [asked the community](https://magento.stackexchange.com/questions/349471/magento-2-use-helper-in-di-xml), but there is no one who can help me.

  [1]: https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html

### Examples (*)

Currently the template is defined like this:

**Company/PdfDesign/etc/di.xml**

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
        <type name="Company\PdfDesign\Model\CompanyDesign">
            <arguments>
                <argument name="templateFiles" xsi:type="array">
                    <item name="extras" xsi:type="string">Company_PdfDesign::pdf/table/extras.phtml</item>
                </argument>
            </arguments>
        </type>
    </config>

However, I want to make this dynamic and load it from the settings, so I tried to use a helper like seen [here][1]:

**Company/PdfDesign/etc/di.xml**

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
        <type name="Company\PdfDesign\Model\CompanyDesign">
            <arguments>
                <argument name="templateFiles" xsi:type="array">
                    <item name="extras" xsi:type="helper" helper="Company\PdfDesign\Helper\Table\Extras::getTemplate"></item>
                </argument>
            </arguments>
        </type>
    </config>

But if I flush cache from CLI then I get alot of XML errors.´

    Invalid Document 
    Element 'item', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'helper' of the xsi:type attribute does not resolve to a type definition.
    Line: 11
    
    Element 'item': The type definition is abstract.
    Line: 11
    
    Internal error: xmlSchemaXPathProcessHistory, The state object to be removed is not the first in the list.
    Line: 10
    
    Internal error: xmlSchemaValidateChildElem, calling xmlRegExecPushString2().
    Line: 9
    
    Internal error: xmlSchemaValidateElem, calling xmlSchemaStreamValidateChildElement().
    Line: 9
    
    Internal error: xmlSchemaDocWalk, calling xmlSchemaValidateElem().
    Line: 9

How can I load the value from a helper instead of hardcoding it?

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment]
I figured out that you can't use helper in di.xml, only in layout files.

Is there a way to use helpers or similar functionality in di.xml or do we have to solve it differently?

**Comment by engcom-Hotel** [comment]
Hi @Eddcapone,

Thank you for reporting the issue.

As we checked your requirement, but helper is allowed in layout XML files check here  https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html#argument

You can see the allowed argument types for di.xml here  https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/di-xml-file.html#argument-types

Thank you

**Comment by engcom-Hotel** [comment]
Dear @Eddcapone,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
