### ISSUE TITLE
403 on inLine edit from grid in Admin with Custom Roles Resources

### ISSUE THREAD

**Issue by Leonede** [magento/magento2#3461]
Hello,
When admin with role that have Roles Resources = Custom, but all resources selected by checkbox, trying to inLine edit Grid (for examle CMS > Block) he got 403 error (Forbitten)
Screen with Role settings:
http://storage1.static.itmages.com/i/16/0218/h_1455801720_7065438_9508b91065.png
Сode screen with XDEBUG: http://storage2.static.itmages.com/i/16/0218/h_1455801233_6333368_bc214b27b9.png
Maybe this setting can be important: Add Secret Key to URLs = Disabled; Admin Session Lifetime (seconds) = 9999; Cache is disabled; All Local modules is Disabled.

**Comment by Leonede** [comment]
For resolve this issue you need to add 

```
    /**
     * Check the permission to run it
     *
     * @return boolean
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Magento_Cms::block');
    }
```

to `Magento\Cms\Controller\Adminhtml\Block\InlineEdit` or extends from `Magento\Cms\Controller\Adminhtml\Block`. Same for `Magento\Cms\Controller\Adminhtml\Page\InlineEdit`

**Comment by shiftedreality** [comment]
You need to check your ACL. Looks like expected behavior.
