### ISSUE TITLE
Order download issue: getting access denied error

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#34622]
### Preconditions (*)

1. Magento ver. 2.4.3
2.

### Steps to reproduce (*)

1. Download orders through order API. Use get method
2. API url used :  REMOVED as customer has security issues
3.  Request header: REMOVED as customer has security issues

### Expected result (*)

1.  Orders should get downloaded without any error.  [Screenshots, logs or description]
2.

### Actual result (*)

1.  Getting error as "Access Denied" 
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @webgility-amazonapi,
We tried verifying the issue on Magento 2.4 Develop with latest branch , it works fine . Please find the attached screenshots for reference.Added 'Needs Update' Label.
![Success_API](https://user-images.githubusercontent.com/51681379/141807599-3b77a9c2-ab9c-482f-b62b-3ff22af1002d.JPG)
![Order_API_success](https://user-images.githubusercontent.com/51681379/141807630-ad099fca-cc16-4666-b680-fb1695c7356a.JPG)
Thanks
