### ISSUE TITLE
Magento ver. 2.3.6 Cart Emptying 

### ISSUE THREAD

**Issue by Liv2BF** [magento/magento2#34629]
### Preconditions (*)

1. Magento 2.3.6

### Steps to reproduce (*)

1. Guest user and Member user
2. Add any product to the basket
3. Add an additional Item to the basket (Basket empties or original item disappears) 
4. If you refresh the page it sometimes totally empties the basket

### Expected result (*)

1. Checkout basket with all items 

### Actual result (*)

1. Basket removes original item if adding an additional item
2. Basket empties during the checkout stage

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Liv2BF,
We tried to reproduce the issue on Magento 2.4 Develop with latest branch, it works fine.
Please find the attached screen recording video for reference. Hence

https://user-images.githubusercontent.com/51681379/141733517-4fd11336-7fc5-4cab-b3b6-405de4d2cbe5.mp4

 added 'Needs Update ' Label.

**Comment by Liv2BF** [comment]
Thank you for looking into this @engcom-Delta, the only difference with our site is that once you add an item to the cart it directs you to the cart immediately and you then have to click out of it into another product category to select the next item you want to add to cart, However, I'm hoping by upgrading the site to 2.4 it will fix the issue :)

**Comment by engcom-Delta** [comment]
Hi @Liv2BF ,
Hope issue is fixed ? . Please confirm.
Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 13 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
