### ISSUE TITLE
Payment method download issue

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#34623]
### Preconditions (*)

1. Magento ver. 2.4.3
2.

### Steps to reproduce (*)

1. Download payment method. Use get method
2. Request : REMOVED as customer has security issues
3.  Request header : REMOVED as customer has security issues

### Expected result (*)

1. [Screenshots, logs or description]
2. payment methods should be downloaded successfully

### Actual result (*)

1. [Screenshots, logs or description]
2. payment methods are not downloading and giving error as
3. {
    "message": "Specified request cannot be processed."
}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @webgility-amazonapi,

As per the doc, the API endpoint `​/V1​/guest-carts`, used to enable a customer or guest user to create an empty cart and quote for an anonymous customer. Please have a look at below screenshot:

![image](https://user-images.githubusercontent.com/51681618/141447123-f6b07421-bded-417d-ab64-2bf3311b5be3.png)

You might look into `rest/all/V1/guest-carts/<cart-id>/payment-methods` to get all the payment methods. Please review it and let us know in case you need help with this.

Thanks
