### ISSUE TITLE
knockout.js error when Flat rate Method Name is empty

### ISSUE THREAD

**Issue by markwalravens** [magento/magento2#3462]
If i remove the Shipping Method - Method Name for Flat Rate i get the following error in the /checkout/cart/ url:

```
Uncaught ReferenceError: Unable to process binding "foreach: function (){return $parent.getRatesForGroup($data) }"
Message: Unable to process binding "if: function (){return (available) }"
Message: Unable to process binding "text: function (){return method_title }"
Message: method_title is not defined
```

The cart-summary is not reloading anymore and the Shipping costs line is not showing.

If I enter the Method Name again, the error is also gone and it works again.

**Comment by ishakhsuvarov** [comment]
@markwalravens Thank you for reporting this issue. We have created an internal ticket `MAGETWO-49561` to investigate and fix the problem.

**Comment by ishakhsuvarov** [comment]
@markwalravens Closing, as the fix for this issue is already delivered to the `develop` branch in the scope of the linked commit.
Please reopen, if you have any additional questions.
