### ISSUE TITLE
Unique constraint for attribute labels and option values

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#34621]
### Summary (*)

When migrating data from M1, using the migration tool, I got duplicate rows for eav_attribute_option_value and eav_attribute_label, leading to front crash or wrong behaviours.

### Examples (*)

- add two rows in eav_attribute_option_value with same option and store ids
- add two rows in eav_attribute_label with same attribute and store ids

### Proposed solution

- Add unique constraint for eav_attribute_option_value :  
```
  <table name="eav_attribute_option_value">
        <constraint xsi:type="unique" referenceId="EAV_ATT_OPT_VAL_OPT_ID_STORE_ID_UNQ">
            <column name="option_id"/>
            <column name="store_id"/>
        </constraint>
  </table>
```

- Add unique constraint to replace existing `EAV_ATTRIBUTE_LABEL_ATTRIBUTE_ID_STORE_ID` index.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hi @Nuranto,

Thank you for reporting the issue. Can you please provide the below info:

1. Which migration tool did you use?
2. What kind of wrong behavior are you getting or can you share the error logs that you got while upgrading?

Thanks

**Comment by Nuranto** [comment]
Hi,

1. I used `magento/data-migration-tool` of course. And the issue 
2. Product page giving an error `Magento\Eav\Model\Entity\Attribute\Option) with the same ID "682" already exists.`

But whatever, the change seems obvious, isn't it ?

**Comment by engcom-Echo** [comment]
Hi @Nuranto,

Thank you for providing the info.

I may have to check the validity of the duplicated data then only I can confirm this issue. I reproduce this issue which you got so can you help me with the data to reproduce this ? Or at least help me create the data so that I can do further analysis.

Thanks

**Comment by engcom-Echo** [comment]
Dear @Nuranto,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
