### ISSUE TITLE
Duplicated product does not retain store view specific values 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#34628]
### Preconditions (*)
1. Magento 2.4.2-p1
2. Multiple store views

### Steps to reproduce (*)
1. Create a second store view (e.g. GR)
2. Go to catalog product edit screen and open any product
3. Open the product in default store view
4. Switch to the second store view GR 
5. Edit the product name in GR store view and change it. 
6. Go back to default store view 
7. Check the name and you'll see it's for all store views the same as the default store view one. The GR store view value is lost. 

### Expected result (*)
1. Duplicating a product creates a perfect duplicate of the original for the other store views as well. . 

### Actual result (*)
1. Data was lost in the clone that exist in the original

As a result the person doing data entry has to manually renenter a lot of data in multiple languages. 
In our use case this can be 10 different languages. It's not nice to make the data entry people go through this hassle when cloning a product. 

https://user-images.githubusercontent.com/20220341/141488852-8b837a34-420b-4a3a-b678-e63e94405ffc.mp4

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by ioweb-gr** [comment]
@magento give me 2.4.2-p1 instance

**Comment by ioweb-gr** [comment]
@magento give me 2.4.3 instance

**Comment by ioweb-gr** [comment]
I was able to reproduce up to 2.4.3 on the bot instances.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
@magento give me 2.4.3 instance

**Comment by shikhamis11** [comment]
@magento give me 2.4.3-p1 instance

**Comment by shikhamis11** [comment]
hi @ioweb-gr 
Thank you for reporting this issue. This issue is reproducible at Magento 2.4.3 and 2.4.3-p1 instance but not 2.4-develop instance. Seems It is fixed on develop branch and will be available on 2.4.4

**Comment by ioweb-gr** [comment]
@shikhamis11 Did you find a relevant PR or Commit which tracks this issue that we could apply specifically?

**Comment by hostep** [comment]
@ioweb-gr: I can find a possible solution under "MC-42506: [CLOUD] duplicated product does not retain some store view specific data", 2 commits: https://github.com/magento/magento2/commit/f0bc113c3179590cb18fbc94b94ae292cd5962e2 & https://github.com/magento/magento2/commit/fa474dd5a5eb6245cc435b8bb939c07545009e71 (no clean merge commit unfortunately)

**Comment by engcom-November** [comment]
Hi @ioweb-gr ,
This issue is not reproducible on Magento 2.4-develop branch hence we are closing it. Kindly reopen the ticket with missing steps if any if you are still facing issues / solution under MC-42506 doesn't work.
Thank you.
