### ISSUE TITLE
Regarding product list API to get only list of SKUs via REST API

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#3463]
Hi,

I am executing 'V1/products' WebApi with SearchCriteria and it is providing whole detail of product with it's all attributes and taking so much time to get all products.

My question is this if i need only sku of all products and i don't need rest of the attributes. So, in this case what should i do to get only sku of all products with same API.

Thanks,

**Comment by choukalos** [comment]
Looking through our dev docs it doesn't look like we've documented how to only get a few fields back ( partial fields filtering ).  It's a framework feature.  

Try
V1/products?fields=sku

You can even get nested objects out too..  
ex : ?fields=customer[id,email],sampleField,addresses[city,postcode,region[region_code,region]]

**Comment by ankursachdeva11** [comment]
Hi @choukalos ,

I have tried 'fields' parameter with searchCriteria but it is not working.
Here is the example URL for REST API : 

[Domain]/rest/V1/products?fields=sku&searchCriteria[filter_groups][0][filters][0][field]=status&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq

Please verify the url and let me know if i am making any mistake in calling API.

Thanks,

**Comment by wozniakm** [comment]
That should be `?fields=items[sku]`, check what is your response and adjust that.

**Comment by ankursachdeva11** [comment]
Thanks @wozniakm, it works.

**Comment by keharper** [comment]
Documented at http://devdocs.magento.com/guides/v2.1/howdoi/webapi/filter-response.html

**Comment by triabhishek95** [comment]
You can try this 

> /V1/categories/[category_id]/products

 it will bring all the products sku falling in the same category.

**Comment by Sabrina-tahir** [comment]
> ?fields=items[sku]

can u share the full url ?
i wan to list all the products Sku i have tries this rest/V1/products?fields=items[sku] butit throws error
