### ISSUE TITLE
Magento 2.4.3 - Checkout Issue with Canadian Shipping Tax - ReferenceError: Unable to process binding "foreach: function(){return getDetails() }"

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#34645]
### Preconditions (*)

1. Magento 2.4.3 CE

### Steps to reproduce (*)

1. Add Canadian taxes to Magento (Import file: https://ufile.io/g1fk6r9a)
2. Create Tax Rules:
![image](https://user-images.githubusercontent.com/66754347/141874614-d0145fae-cd00-43ef-a526-f78c96e1d45d.png)
3. Create SHIPPING TAX rule
![image](https://user-images.githubusercontent.com/66754347/141874689-ea5225eb-2318-462f-9eb4-08a7acada979.png)
4. Add new TAX CLASS - Shipping Tax
![image](https://user-images.githubusercontent.com/66754347/141874749-39b74c1e-9c9c-4d2f-95ca-286dd8e0c6bf.png)
5. Set Tax Class for Shipping to "Shipping Tax"
![image](https://user-images.githubusercontent.com/66754347/141875944-f3b6d426-94e6-4a5c-806e-54a1bfe907a2.png)
6. Save everything.
7. Checkout with Flat Rate - $5 and ship to British Columbia
8. On checkout page the Order Summary will have a spinning loader image
![image](https://user-images.githubusercontent.com/66754347/141875731-5efcade3-6d4a-489b-8d36-b9cc280e6962.png)
9. Error in the console:

`Uncaught ReferenceError: Unable to process binding "foreach: function(){return getDetails() }"
Message: Unable to process binding "foreach: function(){return rates }"
Message: Unable to process binding "if: function(){return value == 0 }"
Message: value is not defined
    if http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js line 3221 > Function:3
    evaluateValueAccessor http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:3494
    getValueAccessor http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:3671
    init http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:4820
    evaluateImmediate_CallReadThenEndDependencyDetection http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:2331
    evaluateImmediate_CallReadWithDependencyDetection http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:2288
    evaluateImmediate http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:2253
    dependentObservable http://localhost/static/frontend/Vendor/vendor/en_US/knockoutjs/knockout.js:2085`

### Expected result (*)

1. Show Order Summary without error.

The tax seems to be calculated correctly:

Item Price = 13.56
Shipping Price = $5

Total Tax: 1.88

GST tax: ($13.56 + $5) * 0.05 ~ 0.93
PST tax: ($13.56) * 0.07 ~  0.95

So the error is somewhere else. 

### Actual result (*)

1. Error in console:
![image](https://user-images.githubusercontent.com/66754347/141875536-eadee036-6281-4f05-bc5e-a38741a9673c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by pmonosolo** [comment]
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment]
@magento give me 2.4.3 instance

**Comment by pmonosolo** [comment]
Hmmmmm....can't confirm on a vanilla 2.4.3 or 2.4-develop. 

Need a bit more time to figure it out.

**Comment by pmonosolo** [comment]
Closing, found an issue inside a local theme. Not related to Magento 2.4.3.

**Comment by engcom-Delta** [comment]
Hi @pmonosolo,
We tried to replicate it on Magento 2.4 Develop.it is not reproducible. Hence added 'Needs Update' Label.
Please find the attached screenshots for reference.
![Placed_order_Canada](https://user-images.githubusercontent.com/51681379/142170239-434073a2-962a-41fa-a266-ccad300f8b51.JPG)


Thanks
