### ISSUE TITLE
feat: support Fedex REST API

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#34642]
### Description (*)

Fedex is outlining a [new RESTful API](https://fedex-betacommunity.centercode.com/key/FedExAPIBeta2020). It will likely be the new standard going forward. We should be starting implementation of this at an early stage because the current implementation [is exceedingly slow](https://github.com/magento/magento2/issues/28337).

### Expected behavior (*)
Use the REST API, not the SOAP API.

### Benefits
A better shipping provider experience than exists today.

**Comment by AdamBorealis** [comment]
I'm desperately trying to get the FedEx implantation to work correctly in 2.3.7-p3, and 2.4.3-p2 test environment, and I'm using the same exact FedEx account meter number / credentials as another store that uses WooCommerce, and the Magento rates are 2x the price, so something is wrong...

I believe the lack of being able to input dimensional shipping from within Magento is throwing everything off.  I don't know how I'm the only person having this issue getting FedEx rates working for an E-Commerce platform...

**Comment by jaminion** [comment]
I'd like to point out that FedEx has announced the retirement of their SOAP web services for May 15, 2024: https://www.fedex.com/en-us/developer/announcements.html#web-services.

**Comment by cjstage** [comment]
@jaminion I have also seen this notice.  Hoping to boost visibility of this ticket.

**Comment by vipin12117** [comment]
Yes better plugin available on marketplace to use rest api Integration. 

https://commercemarketplace.adobe.com/ecomplugins-fedexrest.html

**Comment by jaminion** [comment]
It looks like Adobe has posted patches to support this feature (using FedEx REST API) on currently available supported software versions, I was surprised as I would have expected announcements or at least updates on issues like this concerning it. I expect these are collections of changes that are making it into the next expected supported versions, more specifically version 2.4.7.

I have not used this yet, just about to start testing it, but figure it should be identified for anyone else who was following this ticket for updates.

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/fedex-shipping-method-integration-migration-soap-restful-api.html?lang=en

**Comment by AdamBorealis** [comment]
Oh wow, that was posted back in Nov 2023.  Yeah, I'll certainly be trying this patch on 2.4.4 branch.

**Comment by vipin12117** [comment]
Fedex rest api plugin with auto address validation with dimension weight shipping 

https://commercemarketplace.adobe.com/ecomplugins-fedexrest.html

**Comment by jaminion** [comment]
Hello, I was able to get the patch to apply against a 2.4.5-p5 deployment successfully. Had issues with it failing to return any rates using sandbox keys/account/url for some reason, that may have been temporary, when I switched to production keys/account/url it returned rates fine and I have not switched back to attempt to further debug that.

My biggest problem was that it appears the REST api may not be returning the account-specific rates along with the list rates when submitting `['LIST']` for the `rateRequestType` field in the request, like it does with the SOAP api, and appears to be documented that it would (https://developer.fedex.com/api/en-us/catalog/rate/v1/docs.html). I feel that's more on FedEx than Magento (could be some account/project setting I have overlooked), but this could really bite if you are simply converting/applying just to get ahead of May 15th, as it is hardcoded in the `_formRestRateRequest()` method and they use protected functions throughout so you cannot wrap that with plugins nor use observers to alter it (maybe I missed something else in the request flow that could be injected).

It appears that the OAUTH access token that gets requested does not get cached/reused which is somewhat disappointing but that's also where third parties like the one posting in this thread commonly provide value.

**Comment by Axel29** [comment]
> Hello, I was able to get the patch to apply against a 2.4.5-p5 deployment successfully. Had issues with it failing to return any rates using sandbox keys/account/url for some reason, that may have been temporary, when I switched to production keys/account/url it returned rates fine and I have not switched back to attempt to further debug that.
> 
> My biggest problem was that it appears the REST api may not be returning the account-specific rates along with the list rates when submitting `['LIST']` for the `rateRequestType` field in the request, like it does with the SOAP api, and appears to be documented that it would (https://developer.fedex.com/api/en-us/catalog/rate/v1/docs.html). I feel that's more on FedEx than Magento (could be some account/project setting I have overlooked), but this could really bite if you are simply converting/applying just to get ahead of May 15th, as it is hardcoded in the `_formRestRateRequest()` method and they use protected functions throughout so you cannot wrap that with plugins nor use observers to alter it (maybe I missed something else in the request flow that could be injected).
> 
> It appears that the OAUTH access token that gets requested does not get cached/reused which is somewhat disappointing but that's also where third parties like the one posting in this thread commonly provide value.

@jaminion , I've actually faced the same issue with @vipin12117 's module.
I contacted FedEx's support which gave me this answer:

Rate is fully virtualized, so you would be required to use the Rate JSON Collection located on the FedEx Developer Portal. If none of the samples are what you need, then you would have to use Production to run it, which means you have to have a production Account setup.

So apparently, there's a "virtualized" environment that has a sample request payload that must be used to fetch shipping rates (methods), but it's unclear how for me yet.

**Comment by vipin12117** [comment]
Issue with fedex sandbox. 90 % their system gets down.  If you can call with fedex support then they can up the sandbox environment. Mostly they always forgot to up it. This is my past experience with them.

**Comment by Axel29** [comment]
Okay so @jaminion apparently I managed to make it work (tests are in progress) by:

1. Downloading the Postman API Collection from [this link](https://developer.fedex.com/api/en-us/catalog/rate/v1/docs.html)
2. Send a request `US-US - All services with transit times - No carriercode` to the API to get the "general" shipping ragtes
3. Send a second request `DROPOFF_AT_FEDEX_LOCATION ACCOUNT    GROUND_HOME_DELIVERY` to the API to get the `Ground Home Delivery` shipping rate
4. Merge the two JSON responses by adding the Ground Home Delivery `rateReplyDetails` into the first one
5. Replace the `$response = $this->_doRatesRequest(self::RATE_REQUEST_GENERAL);` (`\Magento\Fedex\Model\Carrier::_getQuotes` line 855) by the JSON decoded (needs to be an array)

Then and only then I got the shipping methods displayed on Magento's checkout..

This is so unpractical and needs custom developements whereas it should have been added by Magento's team as a check in case the sandbox mode is enabled...

**Comment by andrewbess** [comment]
Hello folk
It looks like we will have FedEx Rest API from Magento 2.4.7
I see necessary changes in the 2.4.7-beta2 tag

**Comment by andrewbess** [comment]
The requested features already implemented and will be released in 100.4.5
The issue closed due to reason above

**Comment by vipin12117** [comment]
Use FedEx Rest API plugin auto address check with dimensional shipping with packaging rules

https://www.ecomplugins.com/magento2-fedex-shipping-carrier-with-rest-api
