### ISSUE TITLE
Unable to make curl request to external endpoint while clicking placeorder button

### ISSUE THREAD

**Issue by devendhiranr** [magento/magento2#34647]
Hi Team,
I am working on magento payment gateway extension development using Magento 2.4.3. In that i am having the requirement to capture using magento backend. The problem i am facing is after clicking place order from checkout ajax call is happening. It is calling 2 commands authorize and capture.

In capture flow within TransferFactory implements TransferFactoryInterface class i have configured endpoint url and data. But the request is not hitting the endpoint server and also i am not getting the error message. Please let me know how to make API(curl) call to external end point in capture command.

class CaptureTransferFactory implements TransferFactoryInterface
{
   
    private $transferBuilder;

    public function __construct(
        TransferBuilder $transferBuilder
    ) {
        $this->transferBuilder = $transferBuilder;
    }

  
    public function create(array $request)
    {	
	
        return $this->transferBuilder
            ->setBody($request)
            ->setMethod('POST')
            ->setHeaders(
                [
                    'force_result' => isset($request[MockDataRequest::FORCE_RESULT])
                        ? $request[MockDataRequest::FORCE_RESULT]
                        : null
                ]
            )
			 ->setUri('https://xyz-sandbox.dev.xyz.com/v1/charges')
            ->build();
			
    }
} 
Please let me know what transfer builder will do and how to make curl call and debug the data in capture command.

I am configured magento with xampp and doing development in localhost. 

I am getting "An error has happened during application run. See exception log for details". But in exception log i am not able to see any issue.

Please let me know the best approach to make API call to endpoint within capture command.

**Comment by engcom-Hotel** [comment]
Hi @devendhiranr,

Thank you for reporting the issue.

As we can understand you are implementing a custom Payment Method via Payment Gateway.
You can follow the doc to implement it. It requires more commands to make a request.
Please follow this link: https://devdocs.magento.com/guides/v2.4/payments-integrations/payment-gateway/payment-gateway-structure.html 

Thank you

**Comment by engcom-Hotel** [comment]
Dear @devendhiranr,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
