### ISSUE TITLE
Magento 2.4.3-p1 No make order button displayed and JS not loaded in checkout page

### ISSUE THREAD

**Issue by Domux-France** [magento/magento2#34654]
Hello dear all,

I'm getting a js error while placing an order. there is no order button displayed.
I use Magento 2.4.3-P1 with PHP 7.4 under Plesk with CentOS 8

Can anyone help me please? 
Thanks a lot

605c976991bfab95c737f255d2a64e13.js:1895 GET https://xxxxxx/static/frontend/bs_complex/bs_complex1/fr_FR/Amazon_Payment/js/model/storage.js net::ERR_ABORTED 404
console-output-handler.js:34 [2021-11-17 12:39:53] [ERROR] Failed to load the "Rokanthemes_OnePageCheckout/js/view/place-order-btn" component.
605c976991bfab95c737f255d2a64e13.js:1895 GET https://[xxxxxx](https://xxxxxx/static/frontend/bs_complex/bs_complex1/fr_FR/Rokanthemes_OnePageCheckout/js/paypal/view/payment/method-renderer/in-context/checkout-express.js net::ERR_ABORTED 404
605c976991bfab95c737f255d2a64e13.js:166 Uncaught Error: Script error for: Rokanthemes_OnePageCheckout/js/paypal/view/payment/method-renderer/in-context/checkout-express
http://requirejs.org/docs/errors.html#scripterror
    at makeError (605c976991bfab95c737f255d2a64e13.js:166)
    at HTMLScriptElement.onScriptError (605c976991bfab95c737f255d2a64e13.js:1681)

**Comment by Domux-France** [comment]
Edit :
I renamed some folders and files in Pub/static folder and I it temporary solved but if I generate new static files I get the same issue

I checked logs and found that some static js and css are not in the right folder and not with the right name
For example : 
bs_complex/bs_complex1/fr_FR/Amazon_Payment/js/model/storage.js
When I checked by FTP the folder is called Amazon_Pay and not Amazon Payment
Some JS files have other names than what's in the log
Here is errors in my log :
404 GET /static/_cache/merged/bootstrap.css.map HTTP/1.0
404 GET /static/frontend/bs_complex/bs_complex1/fr_FR/Amazon_Payment/js/model/storage.js HTTP/1.0
404 GET /static/frontend/bs_complex/bs_complex1/fr_FR/Rokanthemes_OnePageCheckout/js/paypal/view/payment/method-renderer/in-context/checkout-express.js HTTP/1.0
404 GET /static/_cache/merged/bootstrap.css.map HTTP/1.0
404 GET /static/frontend/bs_complex/bs_complex1/fr_FR/Rokanthemes_OnePageCheckout/js/paypal/view/payment/method-renderer/in-context/checkout-express.js HTTP/1.0

Please tell me where to check. i don't know if it's magento or plesk issue

**Comment by engcom-Hotel** [comment]
Hello @Domux-France,

Thanks for posting this issue!

We have tried to reproduce this issue in Magento 2.4-develop branch but this is not reproducible for us. We request you to please tell us more about this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Domux-France,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
