### ISSUE TITLE
Fix WebAPI Tests to be compatible with PHP 8.1

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#34653]
We have a lot of errors (>1000) when we run build (WebAPI) on PHP 8.1 
All those issues need to be fixed in all our repos:

- [ ] https://github.com/magento/magento2
- [ ]  https://github.com/magento/partners-magento2ee
- [ ]  https://github.com/magento/partners-magento2b2b
- [ ]  https://github.com/magento/partners-magento2-infrastructure
- [ ]  https://github.com/magento/inventory
- [ ]  https://github.com/magento/magento2-page-builder
- [ ]  https://github.com/magento/magento2-page-builder-ee
- [ ]  https://github.com/magento/security-package
- [ ]  https://github.com/magento/adobe-stock-integration
- [ ]  https://github.com/magento/adobe-ims

### Steps to reproduce (*)
Run Magento WebAPI functional tests on PHP8.1 (E_ALL error reporting level).

### Expected result (*)
No errors and failures, all builds are green on 7.4, 8.0 and 8.1

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this
