### ISSUE TITLE
Saving custom options with dutch formatCurrency separator in price fails

### ISSUE THREAD

**Issue by JohanCore** [magento/magento2#34655]
### Preconditions (*)
Magento 2.4.3-p1
Set admin user locale to for example dutch

### Steps to reproduce (*)
1. Create a product with custom options
2. set price of custom option to -10,00
3. Save product
4. open product again, and try to save.

### Expected result (*)
1. Product should save fine.

### Actual result (*)
1. When opening product for the second time, the price of the product has been changed to 10,00-.

![54028197-88f96b00-41a4-11e9-93b3-960719a16680](https://user-images.githubusercontent.com/10997571/142197698-2f195d09-b6bb-40a4-bce1-f64bd8d895e0.png)

**Comment by engcom-Delta** [comment]
Hi @34655,
We tried to reproduce the issue , it works fine , Price has not been changed .
Hence added label 'Needs Update'. Please find the attached screenshots for reference.
![custom_pricePRod](https://user-images.githubusercontent.com/51681379/142393462-138b1eb3-4771-41d7-92e0-804f35143ee7.JPG)
![Price_not changed](https://user-images.githubusercontent.com/51681379/142393477-7c53c335-3755-47ff-bb8d-5af8f15728b7.JPG)

**Comment by JohanCore** [comment]
Hello,

I'm missing the minus sign in your example.
If we put in a negative amount ( - 410,00 ) the minus sign goes behind the number.

**Comment by engcom-Delta** [comment]
Hi @JohanCore ,
We tried with Dollar price & EUR price by adding negative values on Magento 2.4 Develop with latest branch.
but on frontend it takes negative values and it does not throw any error for entry of negative values.
After saving the product and re-opening the product , it remains the same value .
![Dollar_custom_Options1](https://user-images.githubusercontent.com/51681379/144835938-af7a567f-b609-4df8-8fae-ba353a673b2e.JPG)
![Euro_Negative](https://user-images.githubusercontent.com/51681379/144835956-e722584b-bacf-4fd8-bcb4-a9ced2d62dd8.JPG)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
