### ISSUE TITLE
Youtube video on the product page is not working. 

### ISSUE THREAD

**Issue by TarasPasickyy** [magento/magento2#34652]
### Preconditions (*)
1. Magento ver. 2.4.0-p1 EE
2. Product is created.)

### Steps to reproduce (*)
1. Add Youtube video to the product image gallery. 
2. Add cms block to the product page that have iframe from Youtube.

### Expected result (*)
1. Both videos can be loaded.

### Actual result (*)
1. Gallery video doesn't work.

Issue is in this file:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ProductVideo/view/frontend/web/js/load-player.js

Event "window.onYouTubeIframeAPIReady" from the file load-player.js is not working. (because another iframe have loaded Youtube js and triggered it, already)
After 'clicking' play video from gallery - there is duplicates of https://www.youtube.com/iframe_api js scripts. 
Also load-player.js  is not returning widgets, so developers can't create mixin on those three widgets. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TarasPasickyy** [comment]
Confirmed

**Comment by engcom-Hotel** [comment]
Hello @TarasPasickyy,

Thanks for posting the issue!

We request you to please provide us some sample code or screenshots of your CMS block.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @TarasPasickyy,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
