### ISSUE TITLE
USPS shipping weight calculation rounds ounces to whole number

### ISSUE THREAD

**Issue by iandfox** [magento/magento2#3465]
When a product (and/or total weight) is very low, then USPS kicks back an error that no package weight has been specified.

If an order has a total weight of less than 1 ounce, then the USPS module rounds it to the nearest whole number (which is often 0) and sends that off to USPS for a shipping quote. The FedEx module, in contrast, does not round at all.

I checked in with the USPS [pricing api docs](https://www.usps.com/business/web-tools-apis/rate-calculator-api.pdf) and it says that there can be 10 total digits for the ounces field.

**Comment by alena-marchenko** [comment]
Hi Ian,

we've created MAGETWO-51868 internal ticket for this

**Comment by alena-marchenko** [comment]
Hi Ian,

We've resolved this issue and delivered the fix to develop branch.
Closing the issue.
