### ISSUE TITLE
 WebShopApps matrix rate issue

### ISSUE THREAD

**Issue by kalyani-zithas** [magento/magento2#34662]
magento version - magento 2.3.2
php version - php  5.2

I have uploaded the WebShopApps matrix rates file at the backend for no. of items vs destination condition but it's not working and not showing on order page.Please refer the attached file and give me the solution.

![Screenshot (13)](https://user-images.githubusercontent.com/94588763/142351785-7e60b5e4-26b6-4b88-89be-12d0bf7bf718.png)

Expected Result - so i want to display the matrix rates under shipping method.

**Comment by engcom-Hotel** [comment]
Hello @kalyani-zithas 

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @kalyani-zithas,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
