### ISSUE TITLE
found bug in create job application first name , last name and education details taking in numbers format

### ISSUE THREAD

**Issue by thaknaikshreya** [magento/magento2#34666]
### Preconditions (*)

1. magento version 2.3.2
2.platform : ecomm
3. mode: production/developer

### Steps to reproduce (*)

1. log in to admin panel 
2.job board>view application>create job application
### Expected result (*)

1. [Screenshots, logs or description]
2. numbers should not be taken 

### Actual result (*)

1. [Screenshots, logs or description]
2. numbers taken in the place of first and last name

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @thaknaikshreya 
Job board is a 3rd party extension and code of this extension is not part on https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
