### ISSUE TITLE
Found bug when apply filter in Sort order 

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34663]
### Preconditions (*)

1. Platform : eCommerce
2. Mode : Developer/ Production
3. Magento version : 2.3.2

### Steps to reproduce (*)

1. Log in to Admin panel
2. Navigate to JOB BOARD > Manage Jobs > Filter> Sort Order
3. Try to filter using Sort Order

### Expected result (*)

1. Data should be successfully sorted in filter key.

### Actual result (*)

1. Error : Something went wrong

###Description

1. Unable to filter using "Sort Order" at Manage Jobs in Admin Panel
2. It is showing the error " Something went wrong with processing  the default view.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Vartikamish,

This issue is not related to Magento core, please contact the actual developer of this module from Marketplace. I am closing this issue from here.

Thanks
