### ISSUE TITLE
Repeated multilanguage problems

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#3466]
I think you should in general reexamine multiple Store views.
As soon as I:
- make two store views with two languages
- make a few categories in two languages
- make a few product attributes in two languages 
- add a few products in two languages

The whole thing starts breaking down in the product catalog list. I keep on getting errors "Something went wrong" and the page just loads until it eventually stops working.

It is my 3rd clean instalation now, I am trying to make some order of the above operations work, but eventually it always breaks down. Very annoying.

**Comment by piotrekkaminski** [comment]
@bgabrovsek were you able to resolve it? did you see this problem again?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
