### ISSUE TITLE
Get error in detail shipment with pakages in admin panel

### ISSUE THREAD

**Issue by mohaelmrabet** [magento/magento2#34675]
### Preconditions (*)
1. Magento 2.4.3-p1
2. Php 7.4

### Steps to reproduce (*)

Go into the detail of a shipment in admin panel. (A shipment with pakages) 

### Expected result (*)
No error

### Actual result (*)

Get error in detail shipment in admin

 Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/magento/module-shipping/view/adminhtml/templates/order/packaging/packed.phtml on line 14

### Explanation

The issue comes from the fact that the method Magento\Sales\Model\Order\Shipment::getPackages return string.
But at the page level we must have an array 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mimou78** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @mimou78,

Thanks for posting the issue!

We request you to please elaborate below point mentioned in the main description:

> Go into the detail of a shipment in admin panel. (A shipment with pakages)

Thanks

**Comment by mimou78** [comment]
> Hello @mimou78,
> 
> Thanks for posting the issue!
> 
> We request you to please elaborate below point mentioned in the main description:
> 
> > Go into the detail of a shipment in admin panel. (A shipment with pakages)
> 
> Thanks

Hello,

You must use a delivery method that use the shipping label, and create a new shipment with shipping labels.
and when you go to the the detail of a shipment.
You get the error, because we store packages as string in DB. and we except to get array.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @mimou78,

As we debugged the code, `getPackages` is called from the `app/code/Magento/Shipping/Block/Adminhtml/Order/Packaging.php` class, which is returning `array` as expected.

For debugging we have added a breakpoint here in the [file](https://github.com/magento/magento2/blob/9f43821af62ab177e44b51b112ff8d32d9b82813/app/code/Magento/Shipping/view/adminhtml/templates/order/packaging/packed.phtml#L14). And then debug the code. It is going into the above class ie `app/code/Magento/Shipping/Block/Adminhtml/Order/Packaging.php` and calling `getPackages` function.

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mimou78,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
