### ISSUE TITLE
PATCH method support in Magento\Framework\HTTP\Client\Curl class

### ISSUE THREAD

**Issue by jlballes** [magento/magento2#34677]
### Summary (*)

I am trying to make a HTTP request using the class "Magento\Framework\HTTP\ZendClient". I need to use the PATCH http method, but I am seeing that the PATCH method is not supported by the class "Magento\Framework\HTTP\Client/Curl".
So, I tried to make a preference of the "Magento\Framework\HTTP\Client\Curl" class, in order to add support to the PATCH http method, but the preference is not working, otherwise other preferences are working well.

Version: Magento 2.4.3-p1 Enterprise Edition

### Examples (*)

Preference in my [Vendor]/[Module]/etc/di.xml

`    <preference for="Magento\Framework\HTTP\Client\Curl" type="[Vendor]\[Module]\Framework\HTTP\Client\Curl" />
`

### Proposed solution

Is it possible to add support for the PATCH method in the Magento\Framework\HTTP\Client\Curl class?
Is there some way to make a preference for the Magento\Framework\HTTP\Client\Curl class?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hi @jlballes

Thank you for reporting the issue.

As we can see you are looking for some custom customization, you can try the below solution.

Create a class extending the original Curl class, define your additional functions here and use this class in your code.
![image](https://user-images.githubusercontent.com/51681618/144060453-fdb85841-4904-4878-9960-cfc04da769ea.png)

Please let us know if this works for you

Thanks

**Comment by engcom-Hotel** [comment]
Dear <user>,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
