### ISSUE TITLE
composer.json - dependency not available anymore

### ISSUE THREAD

**Issue by azngeek** [magento/magento2#34688]
### Preconditions (*)

Magento 2.4.2

### Steps to reproduce (*)

Setup a composer with Magento 2.4.2 and run composer install. 

### Expected result (*)

All dependencies should be downloaded.

### Actual result (*)

It seems like that a dependency could not be downloaded.
```

  - Installing magento/module-tinymce-3-banner (100.4.0): Loading from cache
  - Installing magento/module-target-rule-graph-ql (100.4.0): Downloading (connecting...)Downloading (failed)       
                                                                                                                                                                                       
  [Composer\Downloader\TransportException]                                                                                                                                             
  The `https://repo.magento.com/archives/magento/module-target-rule-graph-ql/magento-module-target-rule-graph-ql-100.4.0.0.zip` file could not be downloaded (HTTP/1.1 404 Not Found)  
```

**Comment by engcom-Delta** [comment]
Hi @azngeek,
We tried reproducing the issue , we are able to install the magento 2.4.2 using composer.Hence added label 'Needs Update'
Please find the attached screenshots for reference.
Thanks
![install 2 4 2 by composer](https://user-images.githubusercontent.com/51681379/143069462-ab9de8ad-9ae5-4529-b9a2-8b2a0b1de4d8.JPG)
![installation_last line](https://user-images.githubusercontent.com/51681379/143069477-fbed79cb-3bd2-4afd-8d2b-cc8df0cac068.JPG)
Regards,

**Comment by azngeek** [comment]
I think this Ticket could be closed then. I assume it is an issue with the enterprise license and created an enterprise issue ticket. Thanks.

**Comment by engcom-Delta** [comment]
As it is working fine and confirmed , closing the issue
