### ISSUE TITLE
File exported using RapidFlow doesn't open in Excel

### ISSUE THREAD

**Issue by marielito** [magento/magento2#34682]
### Preconditions (*)

1. Magento ver. 2.3.6-p1
2. Desktop is on Windows 10 Pro version 20H2
3. Browser is Chrome Version 96.0.4664.45 (Official Build) (64-bit)
4. Microsoft® Excel® for Microsoft 365 MSO (Version 2110 Build 16.0.14527.20270) 64-bit  

### Steps to reproduce (*)

1. Go to System > RapidFlow
2. Click Product Export
3. Go to Profile Status tab.
4. Click Export Excel Report.
5. File downloads after approximately 5 minutes
6. Open file with Excel OR...
7. Import the file by going to Data tab and Get Data > From File > From Workbook.

### Expected result (*)

1. File opens in Excel without any issues.

### Actual result (*)

1. File never opens in Excel if just opened directly OR
2. If importing, file doesn't open and Excel generates "Unable to connect" message as in attachment below.
![unable_to_connect](https://user-images.githubusercontent.com/13594380/142676491-6e707d07-da23-497d-8153-8e30080bbe64.png)

**Comment by engcom-November** [comment]
Hi @marielito ,

RapidFlow is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
