### ISSUE TITLE
Running phpstan twice (using the default Magento phpstan configuration) results in strange error

### ISSUE THREAD

**Issue by hostep** [magento/magento2#34680]
### Preconditions (*)
1. clean Magento installation (I've using 2.4-develop, commit 40ceb7019989c949f3e756efe2db673c8e40345c) with composer developer dependencies (which is the default when running `composer install`)
2. macOS 11.6.1
3. Case sensitive filesystem APFS
4. PHP 7.4.25 natively (no virtualisation or docker or whatever)

### Steps to reproduce (*)
1. Analyse the `app/autoload.php` file with phpstan: `./vendor/bin/phpstan analyse --level 1 app/autoload.php`
2. Run the same command a second or third time. Notice that this works fine everytime
3. Now use the default phpstan configuration file from Magento: `./vendor/bin/phpstan analyse --level 1 --configuration ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon app/autoload.php` - this runs without issues
4. Now run this exact same command a **second** time - now this **fails** with:
```
$ ./vendor/bin/phpstan analyse --level 1 --configuration ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon app/autoload.php

In File.php line 208:

  Failed to open stream hoa://Library/Regex/Grammar.pp.


analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [--generate-baseline [GENERATE-BASELINE]] [--memory-limit MEMORY-LIMIT] [--xdebug] [--fix] [--watch] [--pro] [--] [<paths>...]
```
5. Change level of phpstan's analysis from 1 to 2: `./vendor/bin/phpstan analyse --level 2 --configuration ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon app/autoload.php` - notice that this works fine again
6. Run the exact same command again a **second** time - notice that this **fails** again

I have no idea what this is, it only fails with Magento's configuration file and fails the **second** time you try to run the command.
Clearing phpstan's cache with `./vendor/bin/phpstan clear-result-cache` doesn't help ...
Removing the entire `vendor` directory and running `composer install` also doesn't help ...
Problem happens on phpstan versions 0.12.x and 1.x
When switching from `2.4-develop` to the `2.4.3` tag and running `composer install`, it does fix the problem, but only for the first run. The **second** run fails again! Switching back to `2.4-develop` and running `composer install` fixes it again but only for the first run.

When I search the web for this error, I end up on https://github.com/wunderio/code-quality/issues/45 but I don't understand much of this.
So not sure if this is a bug in Magento's phpstan configuration file, or in phpstan, or in one of the hoa libraries, it's hard to say ...
But it's very annoying for users of phpstan if they want to run phpstan inside a Magento project and use the default Magento configuration file.

### Expected result (*)
1. No failures

### Actual result (*)
1. Failures, see above

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @hostep,

Thanks for posting this issue!

I have looked into the issue and the issue is reproducible for me. I have also done some analysis to check if this issue is related to Magento or hoa library and found below links:

- https://github.com/hoaproject/Ruler/issues/86
- https://github.com/hoaproject/Protocol/issues/12

It seems that this issue can be fixed at Magento's end only. 

Please suggest.

Thanks

**Comment by engcom-Hotel** [comment]
Hence the issue is reproducible with the given steps, we are confirming this issue.
