### ISSUE TITLE
bug in crowd funding project >filters>target amount and donated amount >> taking negative value and giving wrong output

### ISSUE THREAD

**Issue by thaknaikshreya** [magento/magento2#34685]
### Preconditions (*)

1.magento version : 2.4.1
2.

### Steps to reproduce (*)

1. go to crowd funding management> crowd funding project> filters>target amount and donated amount
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. we could not find any records

### Actual result (*)

1. [Screenshots, logs or description]
[2.](https://magento-uvdesk-connector-demo15257170157.webkul.com/admin/crowdfunding/project/index/key/d299462094f9d008cb6a5e385b9766364374a28e096ce7d682f69cd8ba1e79b9/)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @thaknaikshreya ,
Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
