### ISSUE TITLE
 Customer group does not change logged in user when entering VAT number.

### ISSUE THREAD

**Issue by DylanHopman** [magento/magento2#34699]
### Preconditions (*)

https://barnwoodweb.dev-atvise.nl/
Magento 2.4.1

### Steps to reproduce (*)

1. Create a user with an address in the Netherlands.
2. Order a product, but change the address to Belgium in the checkout and enter a valid VAT number (BE0761622719)
3. VAT is not deducted

### Expected result (*)

If a user logs in and has never paid with a VAT number before, they enter a general customer group. However, when they log in next time, but this time with a valid VAT number, the customer group is not changed to VAT-free, so the VAT remains.

It should be the intention that as soon as a valid VAT number is entered, the customer group is changed to VAT-free, as is set if you are not logged in and settled with a valid VAT number.

### Actual result (*)

At the moment it only works if you check out as a guest, because then you are not yet assigned to a customer group.

**Comment by engcom-Delta** [comment]
Hi @DylanHopman,
Thank you for logging an issue , Kindly provide the screenshots for reference as it is required for reproducing the issue on Magento instance.
Regards,

**Comment by DylanHopman** [comment]
Best,

Sorry for the late response. Herewith a video explaining exactly what I mean :)
https://www.loom.com/share/afdc40a790594d6c9b7b017f0ca2379d

**Comment by engcom-Delta** [comment]
Hi @DylanHopman ,
Thanks for providing video , We are missing where VAT is getting calculated in the video during checkout .it would be great help if you provide the details steps with screenshots.

Looking forward to hear from you .

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
