### ISSUE TITLE
Filter is not working properly for Select Target Amount

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34691]
### Preconditions (*)

1. Platform: ecommerce
2. Mode : Developer/Production
3. Magento version: 2.4.1

### Steps to reproduce (*)

1. Log in to admin page
2. Navigate to Manage Crowd Funding Project>Filter>Target Amount
3. Try to filter in Target Amount

### Expected result (*)

1. [Screenshots, logs or description]
2. It should be shown row according to filled amount.

### Actual result (*)

1. [Screenshots, logs or description]
2. It is showing all rows or column. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Vartikamish,

Thanks for posting the issue!

Please let us know the module name in which you are facing this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Vartikamish,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
