### ISSUE TITLE
Any PDF file or word file has not been uploaded

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34690]
### Preconditions (*)

1. Platform: ecommerce
2. Mode: Developer/Production
3. Magento version: 2.4.1

### Steps to reproduce (*)

1. Log in Admin panel
2. Navigate to Crowd Funding Project>Manage Crowd Funding Agent>Add Project>Project image> Upload
3. Try to upload file.

### Expected result (*)

1. [Screenshots, logs or description]
2. File should be uploaded successfully in Project Image

### Actual result (*)

1. [Screenshots, logs or description]
2.  Result showing - pdf was not uploaded. We don't recognize or support this file extension type.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Vartikamish ,
Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
