### ISSUE TITLE
If we have removed Project Name. Still data saved with given previous project name

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34697]
### Preconditions (*)

1. Platform : eCommerce
2. Mode: Developer/Production
3. Magento version: 2.4.1

### Steps to reproduce (*)

1. Log in admin panel
2. Navigate to Manage crowd funding project>Edit Project>Remove Project Name

### Expected result (*)

1. [Screenshots, logs or description]
2. Project name should not be show after remove the project name.

### Actual result (*)

1. [Screenshots, logs or description]
2. It showing all project detail after editing or removed. Photo link is mentioned below :
3. ![image](https://user-images.githubusercontent.com/94451028/142982439-1a1a6fd7-8e36-46a0-86b5-df5150f72642.png)
4. ![image](https://user-images.githubusercontent.com/94451028/142982463-f7748864-6408-4f37-9c06-76de1e8524ef.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Vartikamish,

Thanks for reporting the issue!

We request you to please let us know the module in which you are facing this issue.

Thanks

**Comment by andrewbess** [comment]
Hello @Vartikamish 
I didn't find module that contains phrase "Crowd Funding Management"
I think this problem is problem of the 3-rd party extension, but not Magento.
Please send request to support team of the extension vendor

**Comment by andrewbess** [comment]
Hello @engcom-Hotel 
I am sure we need to close this issue.
I checked it on Magento EE.
Module which contain provided titles doesn't exist.
What do you think about it?

**Comment by engcom-Hotel** [comment]
Hello @andrewbess,

I agree with your point. We need to close this issue as this does not belong to Magento's module.

Hello @Vartikamish,

We have noticed that this issue does not belong to the Magento core library. So we are closing it.

Regards
