### ISSUE TITLE
Table is not insert in Description and also not visible Cell, Row and Column under Project information

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34698]
### Preconditions (*)

1. Platform: eCommerce
2. Mode : Developer/Production
3. Magento version: 2.4.1

### Steps to reproduce (*)

1. Log in to Admin Panel
2. Navigate to Crowd funding Management>Add Project>Description>Insert table

### Expected result (*)

1. [Screenshots, logs or description]
2. It should be insert table in description (Show/Hide editor)

### Actual result (*)

1. [Screenshots, logs or description]
2. It is not inserting the table and also Cell, Row or Column is not visible.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Vartikamish,

Thanks for reporting the issue!

We request you to please let us know the module in which you are facing this issue.

Thanks

**Comment by andrewbess** [comment]
Hello @Vartikamish 
I didn't find module that contains phrase "Crowd Funding Management"
I think this problem is problem of the 3-rd party extension, but not Magento.
Please send request to support team of the extension vendor

**Comment by andrewbess** [comment]
Hello @engcom-Hotel 
I am sure we need to close this issue.
What do you think about it?

**Comment by engcom-Hotel** [comment]
Hello @andrewbess,

I agree with your point. We need to close this issue as this does not belong to Magento's module.

Hello @Vartikamish,

We have noticed that this issue does not belong to the Magento core library. So we are closing it.

Regards
