### ISSUE TITLE
Add or remove an simple product from a configurable product not working

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#34696]
### Preconditions (*)

1. 2.4.3
2. Entreprise Edition

### Steps to reproduce (*)

1. Try do add or remove a simple product from a configurable product
2.

### Expected result (*)

1. Product added or removed from backoffice (http://url.local/magentoadmin/catalog/product/edit/id/789/set/17/type/configurable/store/0/back/edit/)
2.

### Actual result 
(*)

1. ![Sélection_1233](https://user-images.githubusercontent.com/24229641/142869369-f07738b2-3112-499e-a8e7-31b7bbe2dbce.png)

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'attribute_id' in where clause is ambiguous, query was: SELECT `main_table`.* FROM `eav_attribute` AS `main_table` INNER JOIN `eav_entity_type` AS `entity_type` ON main_table.entity_type_id = entity_type.entity_type_id LEFT JOIN `eav_entity_attribute` ON main_table.attribute_id = eav_entity_attribute.attribute_id INNER JOIN `catalog_eav_attribute` AS `additional_table` ON main_table.attribute_id = additional_table.attribute_id WHERE (`entity_type_code` = 'catalog_product') AND ((`attribute_id` IN('93'))) GROUP BY `main_table`.`attribute_id`

It start here :
src/vendor/magento/module-configurable-product/Plugin/Model/ResourceModel/Product.php:120 (getList)

and bug here src/vendor/magento/module-eav/Model/AttributeRepository.php after collectionProcessor is applying $searchCriteria when getIterator load Collection.

[AttributeRepository.php][130]Magento\Framework\Api\SearchCriteria::__set_state(array(
   '_data' => 
  array (
    'filter_groups' => 
    array (
      0 => 
      Magento\Framework\Api\Search\FilterGroup::__set_state(array(
         '_data' => 
        array (
          'filters' => 
          array (
            0 => 
            Magento\Framework\Api\Filter::__set_state(array(
               '_data' => 
              array (
                'field' => 'attribute_group_id',
                'value' => 
                array (
                  0 => 102,
                  1 => 101,
                  2 => 100,
                  3 => 99,
                  4 => 98,
                  5 => 97,
                  6 => 96,
                  7 => 95,
                  8 => 94,
                  9 => 93,
                  10 => 103,
                  11 => 127,
                ),
                'condition_type' => 'in',
              ),
            )),
          ),
        ),
      )),
      1 => 
      Magento\Framework\Api\Search\FilterGroup::__set_state(array(
         '_data' => 
        array (
          'filters' => 
          array (
            0 => 
            Magento\Framework\Api\Filter::__set_state(array(
               '_data' => 
              array (
                'field' => 'is_visible',
                'value' => 1,
                'condition_type' => 'eq',
              ),
            )),
          ),
        ),
      )),
    ),
    'sort_orders' => 
    array (
      0 => 
      Magento\Framework\Api\SortOrder::__set_state(array(
         '_data' => 
        array (
          'field' => 'sort_order',
          'direction' => 'ASC',
        ),
      )),
    ),
  ),
))

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @vahir2016,
We tried to reproduce the issue on Magento 2.4 Develop, it works fine ,Kindly share the screenshots for reference or any logs.
![config_prod](https://user-images.githubusercontent.com/51681379/143067700-e6b37556-7144-4bda-9f12-8e6ed993acaf.JPG)
![Remove the Product](https://user-images.githubusercontent.com/51681379/143067713-8a0826ce-c6d1-4f97-89af-87a5359dec3d.JPG)

Please find the attached screenshots for reference.

Thanks

**Comment by vahir2016** [comment]
Hello,

Could you tell me if during your test you go through :

src/vendor/magento/module-eav/Model/AttributeRepository.php

>         $additionalTable = $entityType->getAdditionalAttributeTable();
>         if ($additionalTable) {
>             $attributeCollection->join(
>                 ['additional_table' => $attributeCollection->getTable($additionalTable)],
>                 'main_table.attribute_id = additional_table.attribute_id',
>                 []
>             );
>         }

and what's the regenerated SQL query when getIterator is loaded

>         foreach ($attributeCollection as $attribute) {
>             $attributes[] = $this->get($entityTypeCode, $attribute->getAttributeCode());
>         }

Here is the SQL i got :

> SELECT `main_table`.*
> FROM `eav_attribute` AS `main_table`
>          INNER JOIN `eav_entity_type` AS `entity_type` ON main_table.entity_type_id = entity_type.entity_type_id
>          LEFT JOIN `eav_entity_attribute` ON main_table.attribute_id = eav_entity_attribute.attribute_id
>          INNER JOIN `catalog_eav_attribute` AS `additional_table`
>                     ON main_table.attribute_id = additional_table.attribute_id
> WHERE (`entity_type_code` = 'catalog_product')
>   AND ((`attribute_id` IN ('93')))
> GROUP BY `main_table`.`attribute_id`;

And if you try to play it manually you will get an error.

**Comment by engcom-Hotel** [comment]
Hello @vahir2016,

We have tried to reproduce this issue in Magento 2.4-develop with EE, but for us it is not reproducible for us.

> Could you tell me if during your test you go through :
> 
> src/vendor/magento/module-eav/Model/AttributeRepository.php
> 
> >

We have debugged the code and our code has been reached in the above code.


> and what's the regenerated SQL query when getIterator is loaded

For us the below query has been generated:
```
SELECT `main_table`.* FROM `eav_attribute` AS `main_table`
 INNER JOIN `eav_entity_type` AS `entity_type` ON main_table.entity_type_id = entity_type.entity_type_id
 LEFT JOIN `eav_entity_attribute` ON main_table.attribute_id = eav_entity_attribute.attribute_id
 INNER JOIN `catalog_eav_attribute` AS `additional_table` ON main_table.attribute_id = additional_table.attribute_id WHERE (`entity_type_code` = 'catalog_product') AND ((`main_table`.`attribute_id` IN('93'))) GROUP BY `main_table`.`attribute_id`
```

Please let us know in case we have missed anything.

Thanks

**Comment by vahir2016** [comment]
Hello,

That's weird. Have you got an idea your query is different from mine ?

**Comment by engcom-Hotel** [comment]
Hi @vahir2016,

I am also using the same version of MySQL in my system and as I analyzed our queries they seem similar to me. I request you to please reverify the steps to reproduction and let me know if we missed anything.

**Comment by engcom-Hotel** [comment]
Dear @vahir2016,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
