### ISSUE TITLE
Empty string supplied as input in vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php on line 327

### ISSUE THREAD

**Issue by Tirakal** [magento/magento2#34695]
Hello,
please help to find a solution to this issue. I am tried to find an XML file with empty spaces in the first line, but without a result.
Magento version is 2.3.6
I find some answers that related to permissions, but it's not help.

The issue mostly happening when I tried to go homepage or product page.

1 exception(s):
Exception #0 (Exception): Warning: DOMDocument::loadXML(): Empty string supplied as input in vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php on line 327

Exception #0 (Exception): Warning: DOMDocument::loadXML(): Empty string supplied as input in vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php on line 327
<pre>#1 DOMDocument->loadXML() called at [vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php:327]
#2 Magento\Framework\View\Element\UiComponent\Config\DomMerger->createDomDocument() called at [vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php:396]
#3 Magento\Framework\View\Element\UiComponent\Config\DomMerger->merge() called at [vendor/magento/framework/View/Element/UiComponent/Config/Reader.php:60]
#4 Magento\Framework\View\Element\UiComponent\Config\Reader->readFiles() called at [vendor/magento/framework/View/Element/UiComponent/Config/Reader.php:47]
#5 Magento\Framework\View\Element\UiComponent\Config\Reader->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#6 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#7 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#8 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/UiComponent/Config/ReaderFactory.php:40]
#9 Magento\Framework\View\Element\UiComponent\Config\ReaderFactory->create() called at [vendor/magento/framework/View/Element/UiComponent/Config/Provider/Template.php:108]
#10 Magento\Framework\View\Element\UiComponent\Config\Provider\Template->getTemplate() called at [vendor/magento/framework/View/TemplateEngine/Xhtml.php:78]
#11 Magento\Framework\View\TemplateEngine\Xhtml->render() called at [vendor/magento/framework/View/Element/UiComponent/ContentType/Xml.php:66]
#12 Magento\Framework\View\Element\UiComponent\ContentType\Xml->render() called at [vendor/magento/module-ui/Component/AbstractComponent.php:159]
#13 Magento\Ui\Component\AbstractComponent->render() called at [vendor/magento/module-ui/Block/Wrapper.php:94]
#14 Magento\Ui\Block\Wrapper->renderApp() called at [vendor/magento/module-catalog/view/frontend/templates/product/widget/viewed/grid.phtml:16]
#15 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#16 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:26]
#20 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#21 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#22 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1100]
#23 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1104]
#24 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:674]
#25 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:566]
#26 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:542]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#28 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#29 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#30 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#31 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#32 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#33 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#34 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#35 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#36 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#37 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#38 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#39 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#40 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#41 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#42 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#43 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#44 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#45 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#46 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#47 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#48 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#49 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#50 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#51 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#52 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#53 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#54 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#55 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:963]
#56 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#57 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#58 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#59 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:494]
#60 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#61 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#62 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#63 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#64 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#65 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
#66 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#67 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#68 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#69 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by Tirakal** [comment]
> 

Issue: Clear Description

**Comment by engcom-Hotel** [comment]
Hi @Tirakal.

Thank you for reporting the issue.

As we can see you are doing some custom development.
I can suggest that there might be some blank XML files in your development.
Try to find the blank file(s).

Thank you

**Comment by Tirakal** [comment]
Thanks @engcom-Hotel 
for the response.
I am tried to find blank files earlier, but without results. Maybe I was searched didn't know what file is blank.
Do you mean without any line of code or it can be commented code.?
Or it can be with XML open tag but after it, all content commented?
Or it can be empty spaces on the first line.

How You think it can be wrong permissions.?
pub and var folders were 775, I changed them to 755. And for now, I do not see that error page.

**Comment by engcom-Hotel** [comment]
Hi @Tirakal,

Yes, it could be due to permissions or you may need to debug that XML more if not resolved after giving proper permissions also. A similar issue was reported [here](https://magento.stackexchange.com/questions/133815/warning-domdocumentloadxml-empty-string-supplied-as-input) and answered so please check. It should help.

By your last comment, it seems you are not facing this issue anymore. Also, since this issue is not related to Magento core development, we are closing this issue for now. You can raise similar issues on Magento Stack Exchange(https://magento.stackexchange.com) or [Magento Community](https://community.magento.com) forums. If you think, this is Magento core-related issue then feel free to re-open this ticket or raise a new one with relevant details.

Thanks
