### ISSUE TITLE
magento/framework should require zendframework/zend-escaper

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3470]
When using magento/catalog as a requirement in my separated module, I want to make sure I can still run unit tests without requiring all of Magento. It fails in an error as zend-escaper is required. To rebuild:

In test:

```
        $this->objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);

        $this->contextMock = $this->objectManager->getObject('Magento\Framework\View\Element\Template\Context');
```

Composer:

```
  "require": {
    "php": "~5.5.0|~5.6.0|~7.0.0",
    "magento/module-catalog": "100.0.*"
  },
  "require-dev": {
    "phpunit/phpunit": "5.0.*"
  },
```

Same goes for missing zendframework/zend-stdlib btw.

I think magento/catalog used magento/framework, which should add these dependencies to make sure they are available even if you only install part of the framework.

Error when not requiring these zendframework modules myself:

```
PHP Fatal error:  Class 'Zend\Escaper\Escaper' not found in /var/www/module/vendor/magento/framework/Escaper.php on line 11

Fatal error: Class 'Zend\Escaper\Escaper' not found in /var/www/module/vendor/magento/framework/Escaper.php on line 11
```

**Comment by mazhalai** [comment]
Related internal ticket MAGETWO-31454

**Comment by nickmarx12345678** [comment]
+1, have encountered this attempting to use the Magento1 to Magento2 migration tool, causes a Fatal with output semi-finished

**Comment by nickmarx12345678** [comment]
@stefandoorn did you happen to have a go-around for this?

**Comment by stefandoorn** [comment]
@nickmarx12345678 I was developing a custom module and needed this to run the unit tests standalone. I simply just figured out from the composer.lock of M2 which version was installed/required and required the same dependency in my custom module in the require-dev part to support the tests. Not optional, but it worked :)

**Comment by orlangur** [comment]
This was fixed in https://github.com/magento/magento2/pull/10114, now `zend-escaper` is implicitly required (would be nice to make it explicit but it is just an improvement).

```
Vlads-MacBook-Pro:magento2 orlangur$ composer why zendframework/zend-escaper
zendframework/zend-uri  2.5.2  requires  zendframework/zend-escaper (^2.5)
```
