### ISSUE TITLE
Update composer dependencies to the last released versions

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#34700]
The composer dependencies described below have been fixed by Magento contributors

- [x] [allure-framework/allure-phpunit](https://packagist.org/packages/allure-framework/allure-phpunit#1.5.0)
- [x] [allure-framework/allure-php-api](https://packagist.org/packages/allure-framework/allure-php-api#1.4.0)
- [ ] [elasticsearch/elasticsearch](https://packagist.org/packages/elasticsearch/elasticsearch#v7.15.0)
- [x] [jms/metadata](https://packagist.org/packages/jms/metadata#2.6.1)
- [x] [phpstan/phpstan](https://packagist.org/packages/phpstan/phpstan#1.2.0)
- [x] [webonyx/graphql-php](https://packagist.org/packages/webonyx/graphql-php#v14.11.3)
- [x] [magento/zendframework1](https://github.com/magento/zf1/tree/master) as 1.14.6

These composer dependencies should be updated in composer files in Magento OS, and Magento EE, and Framework after updating `magento/magento-coding-standard` there.

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by andrewbess** [comment]
The `friendsofphp/php-cs-fixer` v.3.3.2 depends on `symfony/console` >= 5.1.3
So, we cannot update it in this issue.

cc @xmav @fascinosum
