### ISSUE TITLE
New Relic module does not complies with CSP

### ISSUE THREAD

**Issue by esteban-serfe** [magento/magento2#34707]
### Preconditions (*)
1. Magneto Commerce v2.4.2
2. New Relic Reporting module v100.4.1

### Steps to reproduce (*)
1. Enable the extension to strart tracking website data.
2. Enter to the homepage

### Expected result (*)
1. Domains for the new relic domains for browser reporting should be included into the CSP headers

### Actual result (*)
1. The following errors appears on the browser console (chrome): 
```
[Report Only] Refused to load the script 'https://js-agent.newrelic.com/nr-spa-1212.min.js' because it violates the following Content Security Policy directive: "script-src [.....] 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
[Report Only] Refused to load the script 'https://bam.nr-data.net/1/[..]etToken' because it violates the following Content Security Policy directive: "script-src [..]'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Current workarround:
1. Add a new module and set this values explicitly. Requires developer knowhow.

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
Thanks for your contribution @EstebanSerfe 

We have to re-confirm internally by reproducing it.
Thanks for your patience!

@engcom-November Please try to reproduce at the earliest!

**Comment by esteban-serfe** [comment]
Related merge request: https://github.com/magento/magento2/pull/34708

**Comment by Kiraberos** [comment]
@magento I am working on this
