### ISSUE TITLE
504 Gateway Timeout on System > Export > Entity Type = Customer Addresses or Products

### ISSUE THREAD

**Issue by sheenaogaya** [magento/magento2#34710]
### Preconditions (*)

1. Magento ver. 2.2.11
2. System > Export
### Steps to reproduce (*)

1. System > Export > Entity Type=Customer Addresses > Export File Format=CSV
2. System > Export > Entity Type=Products > Export File Format=CSV

### Expected result (*)

1. Export the Customer Addresses in CSV format
2. Export the Products in CSV format

### Actual result (*)

1. 504 Gateway Timeout Error (ERR_LB_HPY_504)
2. 504 Gateway Timeout Error (ERR_LB_HPY_504)

---
![image (11)](https://user-images.githubusercontent.com/95012818/143388061-011b408e-2a05-45be-8cfa-e6c3f3ae942f.png)

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @sheenaogaya ,
We tried to reproduce the issue on magento 2.4 Develop with latest branch.it is not reproducible.
Please find the attached screenshots for reference.
It might be a temporary issue , Kindly request to verify once again & share the logs if issue is still persisting.
Thanks

**Comment by sheenaogaya** [comment]
> Hi @sheenaogaya , We tried to reproduce the issue on magento 2.4 Develop with latest branch.it is not reproducible. Please find the attached screenshots for reference. It might be a temporary issue , Kindly request to verify once again & share the logs if issue is still persisting. Thanks

As of November 26, 2021 11:14 AM Philippines time. I am still getting the same error 504 Gateway Timeout when trying to extract Customers Addresses. My other colleague, tried also but the same issue still exists.  Kindly see attached screenshots for your reference.

![image](https://user-images.githubusercontent.com/95012818/143520835-1a360add-e6e3-4b56-ad74-5f2ce44ac575.png)

**Comment by dev-ajaysaini** [comment]
@sheenaogaya Magento officially ended the support for Magento 2.2.X on 01 Dec 2019 it means you will no longer receive any fix for this. You need to upgrade your Magento to latest version.

**Comment by engcom-Delta** [comment]
As per Dev-ajaysaini confirmation it is required the upgradation of Magento. Hence closing the issue .Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
