### ISSUE TITLE
webkul mangopay payment method not working in wallet system

### ISSUE THREAD

**Issue by thaknaikshreya** [magento/magento2#34714]
### Preconditions (*)

1.magenti version - 2.4.2
2.mode - developer / production
3. platform - ecommerce 

### Steps to reproduce (*)

1.wallet system > my wallet > manage wallet > add money to wallet > go to cart > proceed to checkout > select Webkul Mangopay Payment Method
2. place order

### Expected result (*)

1. [Screenshots, logs or description]
2. money add in wallet 

### Actual result (*)

1. [Scr
![error2](https://user-images.githubusercontent.com/39938703/143407371-44962954-3928-4225-b256-334438122002.PNG)
eenshots, logs or description]
2.money not added

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @thaknaikshreya ,
Wallet system is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
