### ISSUE TITLE
Sort order not working on Multishipping Checkout Totals

### ISSUE THREAD

**Issue by mebingeorge04** [magento/magento2#34715]
I have created a module for adding extra free to order. I am facing an issue in multi-shipping checkout total section sorting.
sales.xml
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Sales:etc/sales.xsd">
    <section name="quote">
        <group name="totals">
            <item name="gift_wrap_fee" instance="vendor\customFee\Model\Total\Fee" sort_order="150"/>
        </group>
    </section>
</config>`

![image](https://user-images.githubusercontent.com/95022568/143416955-421f8fa1-7cd9-4b94-b1b4-0daabc1c1232.png)

But in other versions is working fine. 

![image](https://user-images.githubusercontent.com/95022568/143418069-7db2c2b5-6170-40f7-9621-b7af3791fc05.png)

**Comment by engcom-Echo** [comment]
Hi @mebingeorge04,

Thank you for reporting the issue.

I understood the issue to some point but some additional details are required for me to do further analysis and reproduce this:
1. Which Magento version are you facing this issue on ? 
2. In which version it was working fine ?
2. Can you provide the sample module code that you are using for adding extra fee ?

Thanks

**Comment by engcom-Echo** [comment]
Dear @mebingeorge04,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
