### ISSUE TITLE
Error massage and Pop-ups not vanishing 

### ISSUE THREAD

**Issue by thaknaikshreya** [magento/magento2#34713]
### Preconditions (*)

1.platform : ecommerce 
2.mode : developer/production
3. magento version : 2.4.2

### Steps to reproduce (*)

1.wallet system > transfer amount to bank >customer sign up> account
2.my account > account information

### Expected result (*)

1. [Screenshots, logs or description]
2. error massage and pop ups should vanish after some time like in 30 sec or in 1min

### Actual result (*)

1. [Screenshots
![error](https://user-images.githubusercontent.com/39938703/143400876-20ab8b10-2e77-42a6-9429-3574630bff82.PNG)
, logs or description]
2.Error massage and Pop-ups not vanishing 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @thaknaikshreya ,
Wallet system is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
