### ISSUE TITLE
Bug in translating the word "Compare products"

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#3471]
If I inline-translate "Compare products" the frontpage gets messed up seriously when I add an item to the compare list (perhaps one must also flush cache)

You can see on screen on top and on the right column HTML code:

> `Compare Products <span data-translate="[{&quot;shown&quot;:&quot;1 item&quot;,&quot;translated&quot;:&quot;1 item&quot;,&quot;original&quot;:&quot;1 item&quot;,&quot;location&quot;:&quot;Text&quot;,&quot;scope&quot;:&quot;theme4&quot;}]">1 item</span>`

check on 2 different instalations, always the same.
I would be greatful for a manual fix, since now I cannot use my store.

**Comment by antboiko** [comment]
Hi @bgabrovsek , thanks for your inquiry. We've created internal ticket MAGETWO-49514.

Best,
Anton.

**Comment by bgabrovsek** [comment]
I do not know what exactly I did, but the HTML code eventually disappeared. Perhaps turn off "inline-translate" and flush. Anyway, it still is a bug.

**Comment by Zatara7** [comment]
Bug cannot be reproduced: https://gfycat.com/UnnaturalBaggyAmethystgemclam
I believe was fixed by internal issue MAGETWO-46846
Please close
