### ISSUE TITLE
Magento removes group prices when VAT number is invalid

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#34718]
### Preconditions (*)

1. Magento 2.4.3
2.

### Steps to reproduce (*)

1. Add a customer with dealer group prices
2. Give the customer profile an invalid VAT number. We saw the issue with a dealer in Germany.

### Expected result (*)

1. VAT to be applied if applicable, but group prices to be offered
2.

### Actual result (*)

1. General group prices were applied, and only fixed by checking "Disable Automatic Group Change Based on VAT ID"
2. It seems the VAT check seems to demote dealer group prices in the event that the number is invalid, the prices displayed on the frontend and cart also reflect general prices.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @devchris79 ,
We tried to reproduce the issue on Magento 2.4 Develop with latest branch but we did not find any variation on price for invalid VAT number . Please find the attached screenshot for reference.
![Price](https://user-images.githubusercontent.com/51681379/143522633-02f007ce-b89c-46c3-b6ae-852db36a021d.JPG)

We request to provide how do we find out dealer group prices differences on front end  for invalid VAT Number?
Please provide more details to replicate the issue.

**Comment by devchris79** [comment]
Hi @engcom-Delta 

I have a dealer account on our web shop that showed the issue, however if I recreate the pretty much all the account details as a new customer it works fine.
The account was created back in 2018 under a old version of Magento, maybe its a corruption or incompatibility.

I will close the issue unless I find the root cause.

**Comment by engcom-Delta** [comment]
Hi @devchris79 ,
Can we close the issue please?

Thanks

**Comment by devchris79** [comment]
@engcom-Delta 
I thought I had closed it on November 26th??
