### ISSUE TITLE
We can't add the item to Wish List right now: Cannot add product without stock to wishlist..

### ISSUE THREAD

**Issue by BushraAsif** [magento/magento2#34719]
I am getting this message when enabling Multisource inventory.

### Preconditions (*)
1. Magento 2.4.1
2. Enable Multi-Source inventory

### Steps to reproduce (*)

1. Enable Multi-Source Inventory for Jorden
2. Click on the Wishlist button from the front end. It redirects to the wishlist page and shows the error 

### Expected result (*)

1. It should add the products to wishlist 

### Actual result (*)
1. "We can't add the item to Wish List right now: Cannot add product without stock to wishlist."

---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @BushraAsif ,
We tried to reproduce the issue on Magento 2.4 Develop with latest branch , it works fine. Unfortunately we are unable to replicate it with provided steps. Kindly request to review the steps.
Please find the attached screenshots for reference.
Added the label 'Needs Update'
![Uploading wishList.JPG…]()

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 13 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
