### ISSUE TITLE
Popup is not showing when we have entered amount with special character in Add project 

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34720]
### Preconditions (*)

1. Platform: eCommerce
2. Mode: Developer/Production
3. Magento : 2.4.1

### Steps to reproduce (*)

1. Log in to Admin Panel.
2. Navigate to Crowd funding> Add Project> Target amount> Minimum Donation amount>Maximum Donation amount.
3. Try to not save amount with special characters. 

### Expected result (*)

1. [Screenshots, logs or description]
2. It should be show popup when we have entered amount with special character.

### Actual result (*)

1. [Screenshots, logs or description]
2. Its saved easily without any error.
3. ![image](https://user-images.githubusercontent.com/94451028/143538265-67dbcef0-39ac-4dac-9756-833378c8b61d.png)
4. ![image](https://user-images.githubusercontent.com/94451028/143538363-4503da71-499a-44df-924c-b160cd1eb626.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment]
@magento give me 2.4-developer instance

**Comment by Vartikamish** [comment]
Ok and Thank you for this.

**Comment by engcom-November** [comment]
Hi @Vartikamish  ,
Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
