### ISSUE TITLE
Archaic X-XSS-Protection value set in HTTP header by XSSprotection.php

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#34726]
Some browsers include XSS Auditors, built-in defenses against XSS. Although these defenses work against simple reflective XSS attacks, they can be abused by skillful attackers to add weaknesses to otherwise secure web sites. These dangers are present in both filtering and blocking modes.  Many browsers have removed their built-in XSS auditor because it can help attackers bypass modern XSS controls implemented by the website server such as a Content Security Policy.   Unfortunately, at this time the Safari browser still ships with its XSS auditor enabled by default.   For further discussion see...

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

The Magento 2 file XSSprotection.php enables the browser client side XXS auditor in the HTTP response header by default for all browsers except IE8.

X-XSS-Protection: 1; mode=block 

However, the current best practice is now to disable the client side XSS auditor for all modern browsers and implement more comprehensive XSS protection on the server side. 

X-XSS-Protection: 0

Magento 2 probably should not include the X-XSS-Protection header at all, thus allowing it to default to the website server or client browser setting, or at the least set disabled by default and allow the value to be changed in the Admin UI.  Currently it appears a Magento 2 core code patch via cwegans or a custom module are the only solutions to configurating for best practice.

**Comment by DanielRuf** [comment]
Generally the current modern browsers do not have any XSS auditor

> However, the current best practice is now to disable the client side XSS auditor for all modern browsers and implement more comprehensive XSS protection on the server side.

Generally CSP is the new and recommended way.

https://web.dev/strict-csp/
https://portswigger.net/web-security/cross-site-scripting/content-security-policy

Afaik Magento 2 already sets some CSP-headers.

For some better graphical overview regarding the XSS header support see https://caniuse.com/mdn-http_headers_x-xss-protection

**Comment by n2diving-dgx** [comment]
> The current modern browsers do not have any XSS auditor

> Unfortunately, at this time the Safari browser still ships with its XSS auditor enabled by default.

**Comment by engcom-Hotel** [comment]
Hi @n2diving-dgx

Thank you for your input.

Now coming to your point, I think for now it's okay to have X-XSS-Protection: 1; mode=block as default since Safari supports XSS auditor which you also agreed on. Once all the browsers remove support for it, we can look at it again or make X-XSS-Protection: 0; as default or provide Admin UI to change value respectively as you suggested.

Let me know if you are facing any issue in general due to it or shall we close this issue for now?

Thanks

**Comment by engcom-Echo** [comment]
Dear @n2diving-dgx,

We have noticed that this issue has not been updated for a period of 14 Days. Since there is no action required from our side, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
