### ISSUE TITLE
Braintree Payment's error only with Litespeed & not Apache

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#3473]
Hi, 

Firstly, I understand that M2 is officially compatible with only apache and nginx.

I use Litespeed which is a drop in replacement for Apache. I have never had compatibility issues in the past with Magento1.

With Magento 2, everything seems to work perfectly except for the Braintree Payment module.

The symptom: On Checkout the payment method is not shown.
How i replicated: Setup apache server, built site.
Went to migrate to production which is litespeed (yeah i know should use the same for dev and production.)  
Copied the exact database and files.

The error: in the chrome console:

Uncaught TypeError: Cannot read property 'addErrorMessage' of undefined
/pub/static/frontend/Magento/luma/en_US/Magento_Braintree/js/view/payment/method-renderer/cc-form.js:159 

In Safari:
<img width="1239" alt="error" src="https://cloud.githubusercontent.com/assets/9780829/13163864/903b62b4-d704-11e5-87b2-731953010424.png">

This actually looks like its trying to give me an error message but it can't.

Any help would be appreciated!

**Comment by rudik99** [comment]
After some further testing, this might be a PHP version issue. Not a web server issue. 
Seems to appear when using PHP 7.02 and not php 5.6.*
Also potentially a related issue with #2878  ?

**Comment by rudik99** [comment]
Can replicate on php 5.6 as well for the original issue

**Comment by rudik99** [comment]
I am no longer having this issue, i am going to close this

**Comment by chiragayartops** [comment]
Hi,
I use braintree payment method(Credit card) in my store.
It is working in some time but some time it is not working. gives error like 'Unable to place order. Please try again later'.
Please give me solution for this.
Thanks.
