### ISSUE TITLE
REST API Customer Create fails ReCaptcha with Admin Token

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#34731]
### Preconditions (*)

1. 2.4.3-p1

### Steps to reproduce (*)

1. In ReCaptcha Storefront settings, Enable for Create New Customer Account set to reCAPTCHA v3 Invisible
2. Send POST to /customers route to create a new customer using an admin token as the bearer token

### Expected result (*)

1. Customer is created

### Actual result (*)

1. 400 Bad Request {"message":"ReCaptcha validation failed, please try again"}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by karim-haned** [comment]
@nthurston You need to generate integration access token from admin panel and pass it for this to call to avoid Recaptcha. It worked for me

**Comment by shinesoftware** [comment]
hi @karim-haned could you share how you pass it? I have already created the integration access token in the administration page and I have pass it at the client as bearer token header. what else? thanks

**Comment by karim-haned** [comment]
@shinesoftware you should be good if you pass the token in the header 
![image](https://user-images.githubusercontent.com/68304005/210805564-a0ddf9af-7483-45ab-b83d-5221e0eb127a.png)

**Comment by karim-haned** [comment]
@shinesoftware This is an example when I remove the authorization from the header. It doesn't work
![image](https://user-images.githubusercontent.com/68304005/210805820-a610771f-2660-491a-97a9-d04d0a1d45d3.png)

**Comment by davirs** [comment]
I have exactly same problem here.
I sent authorization from the header and the error still the same.
![image](https://user-images.githubusercontent.com/4355062/216653349-cab243df-a6d7-4b88-b3c2-6da88ce6513c.png)

I disabled google recaptcha V3 for storefront customer new registration and the API worked fine.
![image](https://user-images.githubusercontent.com/4355062/216652215-ee5322c4-ad1b-4e34-ac7e-5e36add15aa9.png)

@karim-haned I'm using bearer token here. can you help with more details about your configurations?
I'm using postman for tests

**Comment by karim-haned** [comment]
@davirs Your screenshot shows that you did not enable the authorization in the header 
![image](https://user-images.githubusercontent.com/68304005/216663023-860e1d93-9d02-4141-a02e-6191f6f7cb13.png)

**Comment by davirs** [comment]
Sorry for my lack of experience. I have enabled the header in the settings; 
Can you tell me the correct place to activate the token in the header?

![image](https://user-images.githubusercontent.com/4355062/216668530-df19c8ca-5a95-407d-a08c-0be65e2b8292.png)

**Comment by igi8819** [comment]
@davirs you have to create integration token and pass it into the header, i think you tried with admin token.
To generate integration token you have to go into
System -> Extensions -> Integrations -> Add new integration

**Comment by sky-hub** [comment]
For Magento 2.4.X, in addition to what @igi8819 said, if you really want to use integration tokens as bearer tokens you may want to have a look at this: 

https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/

**Comment by swiftank** [comment]
Same problem facing while create customer with rest api. Added token bearer token also in the headers but still throwing
"ReCaptcha Validation Failed " message

![image](https://github.com/magento/magento2/assets/60032102/959cc6f6-b8b8-4697-a563-94c1bdefe973)
