### ISSUE TITLE
Unit tests are failing with libxml 2.9.10

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#34733]
### Steps to reproduce (*)
1. Checkout platform-health branch from magento2 repository
2. run `composer install`
3. run `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist`

### Expected result (*)
1. All unit tests should be passing

### Actual result (*)
1. We have 158 test failures
```
FAILURES!
Tests: 22720, Assertions: 61403, Failures: 158, Skipped: 184, Incomplete: 47.
```
2. Errors : 

```
1) PayPal\Braintree\Test\Unit\Block\FormTest::testIsVaultEnabled
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object
/var/www/html/vendor/magento/framework/Session/SessionManager.php:169
/var/www/html/vendor/paypal/module-braintree-core/Block/Form.php:116
/var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Block/FormTest.php:156
2) PayPal\Braintree\Test\Unit\Ui\Component\Report\Filters\Type\DateRangeTest::testPrepare with data set #1 ('test_date', array(array(null, '11-05-2015')), array('2015-05-11T23:59:00+0000', 'lteq'))
Exception: Deprecated Functionality: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Ui/Component/Report/Filters/Type/DateRangeTest.php on line 117
/var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
/var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Ui/Component/Report/Filters/Type/DateRangeTest.php:117
--
```

Failures (I have 153 failures, I give you only one for example) : 
```
153) Magento\Framework\ObjectManager\Test\Unit\Config\XsdTest::testSchemaCorrectlyIdentifiesInvalidXml with data set "virtualtype with digits_and_prefix_slash" ('<config xmlns:xsi="http://www...onfig/>', array('Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Element 'virtualType', attrib...e: 2\n'
-    1 => 'Element 'virtualType', attribute 'name': '\777Digits\IsNotAllowed' is not a valid value of the atomic type 'phpClassName'.\n
+    1 => 'Element 'virtualType', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happened.\n
     Line: 2\n
     '
-    2 => 'Element 'virtualType', attrib...e: 2\n'
 )
```

### Additional Information
Same issue is reported [here](https://github.com/magento/magento2/issues/35683). Launching Unit tests with M2.4.4 and PHP8.1 gives errors and failures

### Additional Notes
1. I prepared a branch on how to run unit tests on Github Actions (based on top of `platform-health` branch):
https://github.com/magento/magento2/compare/platform-health...ihor-sviziev:run-unit-tests

You can find the result of the execution here:
https://github.com/ihor-sviziev/magento2/runs/4353240450?check_suite_focus=true

2. When using centos based image (https://warden.dev/) - we have different test failures.
3. I noted that the amount of ran unit tests on Magento build is different:
Example: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34723/e5b7c4fa8fbdcd87b9a7e2551dc072ab/Unit/console-error-logs.html
At the end of CE tests
```
Tests: **6875**, Assertions: 14857, Failures: 1, Skipped: 99, Incomplete: 7.
```

But when we're running tests locally, we have the following output (**4X more tests were run!**):
```
Tests: **22720**, Assertions: 61407, Failures: 158, Skipped: 184, Incomplete: 47.
```

/CC @andrewbess @xmav 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @ihor-sviziev 
Thank you for your vigilance

**Comment by xmav** [comment]
Thats reporting issue (from Jenkins to GitHub). Tests are running in different groups in few threads. Total number of reported OpenSource php unit tests is **26011**
platform-helath branch is not stable branch. It holds "work in progress" type of code so it is expected for now to see failures there. 
Btw which PHP version did you use to run tests?

**Comment by xmav** [comment]
From what I see most of the failures in your results related to xml\xsd. Please double check that everything is ok on that environment

**Comment by ihor-sviziev** [comment]
@xmav, please ping me in Slack, it will be way faster to check it

**Comment by ihor-sviziev** [comment]
After discussion with @xmav in Slack - it feels like the current tests work with outdated libxml2 library version **2.9.1**, while on Ubuntu 20.04 we have **2.9.10** and (2.9.12).

Just a side note: on local env unit tests are running 2 minutes. Why the hell they're running for 30+ mins on the CI?

**Comment by Nuranto** [comment]
I confirm this issue on Debian bullseye / libxml 2.9.10 on M2.4.4.

(2.9.4 is not available on standard bullseye)

**Comment by robin31** [comment]
For others running in docker and facing this issue, until this is fixed in the core, sharing my small hack;

Running in a `php:8.1-fpm-alpine` container the following downgrades your libxml2 to `2.9.4` and dropped failures massively.
I've not encountered an issue by doing this so far. PHP will still say it's built with the newer version but it will load this older version. 

```Dockerfile
FROM php:8.1-fpm-alpine

## LIBXML 2.9.4 for Magento unit tests (https://github.com/magento/magento2/issues/34733)
RUN apk add --no-cache --virtual .build-deps build-base automake libtool zlib-dev autoconf make && \
  apk del libxml2-dev && \
  curl https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.9.4/libxml2-v2.9.4.zip -o /tmp/libxml.zip && \
  cd /tmp && \
  unzip libxml.zip && \
  cd libxml2-v2.9.4 && \
  ./autogen.sh && \
  make && \
  make install  && \
  apk del --no-network .build-deps && \
  rm /usr/lib/libxml2.so.2 && \
  ln -s /usr/local/lib/libxml2.so.2.9.4 /usr/lib/libxml2.so.2
  ```
  
  Make sure you test this before you use this in production, use at your own risk.

**Comment by engcom-Dash** [comment]
Hi @ihor-sviziev ,

We are trying to reproduce the issue in 2.4-develop instance.But we are not able to reproduce the issue.
We got 23 failures in while running the - vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist command.

Magento Version -2.4 develop
PHP - 8.1

**Steps to Reproduce:**
1.Install fresh Magento instance
2.Checkout Platform-Health branch Magento2 repository using "git clone git@github.com:magento/magento2.git "
3.Run Composer install command
4.Run vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist command
5.We got 23 Failures....

**Screenshots:**
<img width="1512" alt="Screenshot 2022-12-23 at 5 20 35 PM" src="https://user-images.githubusercontent.com/60198592/209332426-4ad2df0d-5e6d-4c12-a9ae-cd6b6efe6bb4.png">
<img width="1512" alt="Screenshot 2022-12-23 at 5 22 44 PM" src="https://user-images.githubusercontent.com/60198592/209332444-45452f26-32ef-4049-a398-b6e5a7a90931.png">

As per the description there are 153 failures was occurred. But we got 23 Failures only occurred.We are not able to reproduce the issue.

Let us know if we missing anything!!!

Thanks!!!!

**Comment by ihor-sviziev** [comment]
@engcom-Dash did you test on Ubuntu 22.04?

**Comment by engcom-Dash** [comment]
Hi @ihor-sviziev ,

We Worked this issue in Mac-System.

Configuration is---> MAC os Ver.12.2.1

Thanks!!!

**Comment by ihor-sviziev** [comment]
I had this issue on Ubuntu 22.04, so would be great try to reproduce it
there

**Comment by rvr31** [comment]
I think the issue is platform independent and linked to a breaking change in libxml

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence confirming this issue.
Unit tests are getting failed on latest Magento 2.4-develop instance as well.
![image](https://user-images.githubusercontent.com/60198231/220821691-950f4a56-7172-4a17-b19e-4b42f6c3ad31.png)

**Comment by engcom-Bravo** [comment]
Hi @ihor-sviziev,

We got Confirmation from internal team.

We have run 2 jenkins build on baseimages/centos7php82os2mysql80 & baseimages/centos7php81os2mysql80 


**There are no failures observed**.

Hence this issue which is created is no longer reproducible.


Screenshots for reference:


<img width="1427" alt="Screenshot 2023-05-02 at 14 07 42" src="https://user-images.githubusercontent.com/51680745/236799070-09424e68-519f-4455-9c44-30c1b3c7652f.png">


<img width="1427" alt="Screenshot 2023-05-02 at 14 06 23" src="https://user-images.githubusercontent.com/51680745/236799109-d78e361c-1a1d-42ec-9596-ab3f92661f82.png">


<img width="1427" alt="image-2023-05-02-14-12-05-876" src="https://user-images.githubusercontent.com/51680745/236799172-2763097a-e698-4032-8f74-c84bae4e1a6e.png">


<img width="1427" alt="image-2023-05-02-14-12-13-747" src="https://user-images.githubusercontent.com/51680745/236799565-da212d7d-90c4-4701-bae1-b476fe215edf.png">





Thanks.

**Comment by ihor-sviziev** [comment]
hi @engcom-Bravo,
I just re-checked - it looks like the listed errors are not there anymore, but I still have 2 failures:
https://github.com/ihor-sviziev/magento2/actions/runs/4916496544/jobs/8780333650
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/1873745/236858176-19c93f19-6038-47f3-8574-b7c99b458950.png">

Note: I rebased my branch on top of current 2.4-develop branch and updated it to use PHP 8.1 https://github.com/magento/magento2/compare/2.4-develop...ihor-sviziev:run-unit-tests

**Comment by ihor-sviziev** [comment]
So since this issue isn't reproducing anymore, I'm closing it. But keep in mind. The tests still failing
