### ISSUE TITLE
I am getting Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site. warning in browser console.

### ISSUE THREAD

**Issue by mohanwbsofttech** [magento/magento2#34789]
I am getting Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site. warning in the browser console.
peoples are saying that to remove 
require(['jquery',
        'priceBox',
        'mage/translate', 
        'Magento_Catalog/js/price-utils',
        'mage/validation',
        'jquery/ui'
    ], function ($, priceBox, $t, priceUtils) {

kind of js. My question is what I can use in place of this?

**Comment by engcom-Hotel** [comment]
Hi @mohanwbsofttech. 

Thank you for your report.
To speed up the processing of this issue, make sure that you provided the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks
