### ISSUE TITLE
Dear magento 2 maintainers, please take a relaxing pill and think about backward compatibility

### ISSUE THREAD

**Issue by kwojc** [magento/magento2#34787]
Lets say... it's totally crazy to build stable store on magento 2. 

Everything from 2.3 does not fit to 2.4. In addition lot of tests from  "stable" relase fails. 
You need example? 

Find Magento\InventoryApi\Api\Data\SourceItemInterfaceFactory in source code, you will find it only in tests, and there is no such interface in repo. For gods sake... Keep backward compatibility. Nothing works as expected.

Just stop making new features and fix existing codebase.

Thanks for reading.

P.S.
I'm maintaining stores built on 2.3 and 2.4. Upgrading from 2.3 to 2.4 will burn lot of hours on stupid searching interface replacements.

**Comment by sidolov** [comment]
@kwojc `Magento\InventoryApi\Api\Data\SourceItemInterfaceFactory` is auto-generated factory class to provide ability to generate objects based on `Magento\InventoryApi\Api\Data\SourceItemInterface` located under inventory repo: https://github.com/magento/inventory/blob/develop/InventoryApi/Api/Data/SourceItemInterface.php#L20.
Please, provide more details in case I'm missing something.

**Comment by kwojc** [comment]
Dear @sidolov - Interfaces are Contracts, written in stone contracts between developers how to treat objects. They descibe behaviour of objects. How whould you call "auto generated contract"? 
For gods sake, it doesn't make any sense to generate Interfaces. Auto-gen instances for cache some magic (like findBy* methods in doctrine - it's ok for me) but interfaces? How to develop, trust code, run static analysis etc. It should be more human readable and understandable.

**Comment by engcom-November** [comment]
Hi @kwojc , Thank you for reporting and collaboration. This feedback was relayed to the core team and since there are specific action items out of this report we are closing it.
Thank you.
