### ISSUE TITLE
[GraphQl] Wrongly deprecated fields in ProductInterface

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#34783]
In the `ProductInterface` the fields `new_from_data` and `new_to_date` are marked as deprecated. This happened in #30694 because of the issue #30625.
They were deprecated alongside other fields which are said that they would expose data that should not be visible. While i agree with most of the deprecated fields I **strongly** disagree with the deprecation of the fields `new_from_data` and `new_to_date`.

These 2 fields are in no way sensitive and are also needed when building a headless magento shop to be able to show to the customer whether a product is new, e.g via a label in the category or product view itself.

We want to add a label "New" to the product in categories, which is not possible anymore if the fields  `new_from_data` and `new_to_date` are removed.

The deprecation should be withdrawn.

Fun fact: The fields `new_from_data` and `new_to_date` were not requested to be deprecated in #30625, the PR just did it.

**Comment by engcom-November** [comment]
As per official Magento [dev docs,](https://devdocs.magento.com/guides/v2.4/graphql/queries/products.html) new_to_date and new_from_date are deprecated input attributes. Hence implementing these features can be considered as a feature request but not as a bug. Hence labeling this as feature request.

**Comment by oneserv-heuser** [comment]
@engcom-November  Yeah thats true, but this ticket is not about the input attributes for filters. Its about the output in ProductInterface.

**Comment by cpartica** [comment]
@oneserv-heuser - can we just leave "new_to_date" without new_from_data? 
why do you need the From? do you have such frontend needs to specify a date range?

**Comment by cpartica** [comment]
> As per official Magento [dev docs,](https://devdocs.magento.com/guides/v2.4/graphql/queries/products.html) new_to_date and new_from_date are deprecated input attributes. Hence implementing these features can be considered as a feature request but not as a bug. Hence labeling this as feature request.

more like missed requirements actually - we should of not deprecated those

**Comment by engcom-Alfa** [comment]
Hi @oneserv-heuser ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by pmonosolo** [comment]
> In the `ProductInterface` the fields `new_from_data` and `new_to_date` are marked as deprecated. This happened in #30694 because of the issue #30625. They were deprecated alongside other fields which are said that they would expose data that should not be visible. While i agree with most of the deprecated fields I **strongly** disagree with the deprecation of the fields `new_from_data` and `new_to_date`.
> 
> These 2 fields are in no way sensitive and are also needed when building a headless magento shop to be able to show to the customer whether a product is new, e.g via a label in the category or product view itself.
> 
> We want to add a label "New" to the product in categories, which is not possible anymore if the fields `new_from_data` and `new_to_date` are removed.
> 
> The deprecation should be withdrawn.
> 
> Fun fact: The fields `new_from_data` and `new_to_date` were not requested to be deprecated in #30625, the PR just did it.

Thanks for bringing this issue up!

This would definitely throw a wrench into upgrades if you have created a theme dependent on those fields.
