### ISSUE TITLE
Not translatable phrase in Wish List

### ISSUE THREAD

**Issue by nja78** [magento/magento2#3479]
magento2/app/code/Magento/Wishlist/view/frontend/templates/messages/addProductSuccessMessage.phtml

Success message about adding product to Wish List cannot be translated

**Comment by antboiko** [comment]
Hi @nja78 , thanks for your inquiry. We've created internal ticket MAGETWO-49512.

Best,
Anton.

**Comment by slavvka** [comment]
@nja78, the issue has been fixed and delivered. Please check.
