### ISSUE TITLE
js/model/customer.js isLoggedIn() is populated only when user opens the checkout page

### ISSUE THREAD

**Issue by mushketer888** [magento/magento2#34790]
### Summary
js/model/customer.js isLoggedIn() is populated only when user opens checkout page
Until the user hasn't opened the checkout page, js/model/customer.js isLoggedIn() will always return undefined
So the js/model/customer.js isLoggedIn() is barely useless
Version: 2.4.2

### Examples 
See 'Magento_Customer/js/model/customer'
var isLoggedIn = ko.observable(window.isCustomerLoggedIn)
But window.isCustomerLoggedIn is populated only in module-checkout/view/frontend/templates/cart/shipping.phtml,module-checkout/view/frontend/templates/onepage.phtml,/view/frontend/templates/checkout/billing.phtml:
window.checkoutConfig = {$serializedCheckoutConfig};
window.customerData = window.checkoutConfig.customerData;
window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;

### Proposed solution
To populate window.isCustomerLoggedIn when the user has just logged in or logged out or maybe use it via 'Magento_Customer/js/customer-data'

- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by mushketer888** [comment]
@magento give me 2.4-develop instance

**Comment by mushketer888** [comment]
Its easy to replicate
use js console and window.isCustomerLoggedIn

**Comment by mrtuvn** [comment]
as i remembered `isLoggedIn` this is ko observable placed in file mentioned for check customer flag logged or not. Maybe it will be used in another place such as checkout screen

**Comment by engcom-Hotel** [comment]
Hello @mushketer888,

Thanks for posting the issue!

In order to reproduce the issue, we need some more information like steps to reproduce, screenshots, or video recording (if possible).
Please help us with the above information.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mushketer888,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by niranjan-gondaliya** [comment]
Hello @mushketer888 ,

Same issue i am getting with Magento 2.4.6 version.

I am getting  window.isCustomerLoggedIn variable undefine some times in customer.js.
