### ISSUE TITLE
Magento 2 Problem: Allowing price to show on website 

### ISSUE THREAD

**Issue by tripleasupplies** [magento/magento2#34807]
hi all, 

as I was changing my e-commerce website to show the pricing of each product. I didn't see the category permission to enable this action for my company's website. Is there any solution for this ?

**Comment by engcom-Hotel** [comment]
Hello @tripleasupplies,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @tripleasupplies,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
