### ISSUE TITLE
Bug: less pocessor

### ISSUE THREAD

**Issue by syntaxwanderer** [magento/magento2#3480]
1)
![image](https://cloud.githubusercontent.com/assets/1311643/13172785/a69bd220-d702-11e5-8c7a-03426dba88b6.png)

2)
![image](https://cloud.githubusercontent.com/assets/1311643/13172806/cc4a8eda-d702-11e5-9951-92fb87a4b3fb.png)

3) 
![image](https://cloud.githubusercontent.com/assets/1311643/13172904/43a087be-d703-11e5-8acb-3ca97d550a0e.png)

4) 
![image](https://cloud.githubusercontent.com/assets/1311643/13172985/b42803f4-d703-11e5-8961-1f040ebcc489.png)

5) 

![image](https://cloud.githubusercontent.com/assets/1311643/13172859/0d755b7e-d703-11e5-9f83-f5b612a8afa0.png)

6) 
![image](https://cloud.githubusercontent.com/assets/1311643/13172945/7ee27382-d703-11e5-9c08-16768f63803b.png)

**Comment by syntaxwanderer** [comment]
Update
![image](https://cloud.githubusercontent.com/assets/1311643/13173546/d1efb406-d706-11e5-89d3-2d578024e286.png)

**Comment by alankent** [comment]
Is it possible to get the theme? If a commercial offering and you don't want to send, could you try using say https://github.com/SnowdogApps/magento2-frontools to see if it comes up with a different error message?

Normally I would not have recommended overriding our default styles-m.less file, but that is not a reason for getting a stack trace.

**Comment by vzaporozhets** [comment]
Closing this issue as no update provided for a long time. @ArniXXX - do not hesitate to contact us if issue is still present.
