### ISSUE TITLE
Media Gallery mediaAttribute string|array, only array works

### ISSUE THREAD

**Issue by iflam** [magento/magento2#34815]
### Preconditions (*)

1. When doing $product->addImageToMediaGallery(), it says you can provide both a string and an array, however if you provide a string then it breaks.

### Steps to reproduce (*)

1. Create a product programmatically
2. addImageToMediaGallery($path, "thumbnail")
3. productRepository->save($product)
### Expected result (*)

1. Image is added successfully on saving with product repository.

### Actual result (*)

1. Error received stating that types is supposed to be an array, not a string.

When debugging I found that in Module_Catalog/Model/Product/Gallery/Processor.php on line 223, 'types' is set as $mediaAttribute, where it probably should be set as 
is_array($mediaAttribute) ? $mediaAttribute : [$mediaAttribute]

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @iflam,

We have tried to reproduce this issue in Magento 2.4-develop branch but for us, it is not reproducible. Please have a look at the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/146205559-d2a0e5c6-e9d3-4cd3-966d-c2e50767e21b.png)

We have used the below lines to upload an image:

```
$product->addImageToMediaGallery(
                        'TestBundle' . DIRECTORY_SEPARATOR . pathinfo($image)['basename'],
                        'thumbnail',
                        false,
                        false
                    );
```

Please let us know in case we have missed anything.

Thanks

**Comment by iflam** [comment]
After that you ran save() on product repository? That's the part where it doesn't work for me.

**Comment by engcom-Hotel** [comment]
Hello @iflam,

Thanks for the reply!

Yes we are also running `$product->save();` after that. We request you to please try to reproduce it in Magento 2.4-develop branch and let us know if it is reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @iflam,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
