### ISSUE TITLE
Reindex by schedule on servers with several PHP versions

### ISSUE THREAD

**Issue by mrgoogle** [magento/magento2#3482]
Not sure if this can be considered a bug, but finding the reason of the problem and its solution took some time and debugging.

Our customer has two PHP versions on the server: 5.4 for old websites and 5.6 for Magento 2. Web server is set up correctly to use 5.6, but there was a problem with cron tasks.

As it is described in the documentation, I added bin/magento cron:run call to crontab with the correct path to PHP 5.6. And cron tasks from the default group were working fine. However, other group (e.g. index) weren't working.

After some digging I found that for index group Magento2 runs a separate process using the default php binary (Magento\Cron\Observer\ProcessCronQueueObserver::execute()). And since in my case 5.4 is the default PHP ("which php" gives path to it), this separate process fails telling that only PHP 5.5+ is supported. But it tells you that only if you repeat the separate process command - if you run bin/magento cron:run, you just see the usual "Ran jobs by schedule" success message.

Yes, now I know that it can be solved by just setting "Use Separate Process" to "No" for index group in admin, but to find this solution I had to dig through the code, find the command for running the separate process, run it and read the error. 

I think that such errors should be written into some log to make it easier for the other people who may meet the same issue. Or set "Use Separate Process" to "No" by default.

**Comment by rganin** [comment]
Thanks for reporting. Created internal issues for lost output (MAGETWO-49638) and multiple php executables (MAGETWO-49633).

**Comment by mazhalai** [comment]
@mrgoogle the issue with multiple php executables has been fixed in the develop branch.

**Comment by veloraven** [comment]
This issue was fixed.
Closed.
