### ISSUE TITLE
Magento custom attributes not being updated via the api 

### ISSUE THREAD

**Issue by brideo** [magento/magento2#34832]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Have a product with a description set to "a" 
2. Try and update it via the API to "b"

```
curl --location --request POST 'http://example.test/rest/V1/products?XDEBUG_SESSION_START=PHPSTORM' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer 12345' \
--header 'Cookie: PHPSESSID=dpeckrkmgvkra3tfdmqubdvrr1; XDEBUG_SESSION=PHPSTORM' \
--data-raw '{
    "product": {
        "id": 17996,
        "sku": "SKU123",
        "custom_attributes": [
            {
                "attribute_code": "description",
                "value": "b"
            }
        ]
    }
}'
```

### Expected result (*)

1. Description should be "b"

### Actual result (*)

1. description is still "a

---

`$product->getData('description')` uses the `$_data` variable on the DataObject whereas `$product->getData()` uses `getCustomAttribute` if available. 

This results in a weird scenario: 

![image](https://user-images.githubusercontent.com/4906361/146478857-93413867-3086-41b7-8e77-b95def25f6eb.png)

`ProductRepository` overwrites the data of the object here: 

```
    protected function initializeProductData(array $productData, $createNew)
    {
        unset($productData['media_gallery']);
        if ($createNew) {
            $product = $this->productFactory->create();
            $this->assignProductToWebsites($product);
        } elseif (!empty($productData['id'])) {
            $this->removeProductFromLocalCacheById($productData['id']);
            $product = $this->getById($productData['id']);
            $product->getData();
        } else {
            $this->removeProductFromLocalCacheBySku($productData['sku']);
            $product = $this->get($productData['sku']);
        }

        foreach ($productData as $key => $value) {
            $product->setData($key, $value);
        }

        return $product;
    }
```

This only overrides the _data variable but the hydrator uses ->getData() which gets a different variable. 

The method in `ProductRepository`  should have this: 

```
            if ($product->getCustomAttribute($key)) {
                $product->getCustomAttribute($key)->setValue($value);
            }
```

```
    protected function initializeProductData(array $productData, $createNew)
    {
        unset($productData['media_gallery']);
        if ($createNew) {
            $product = $this->productFactory->create();
            $this->assignProductToWebsites($product);
        } elseif (!empty($productData['id'])) {
            $this->removeProductFromLocalCacheById($productData['id']);
            $product = $this->getById($productData['id']);
            $product->getData();
        } else {
            $this->removeProductFromLocalCacheBySku($productData['sku']);
            $product = $this->get($productData['sku']);
        }

        foreach ($productData as $key => $value) {
            $product->setData($key, $value);
            if ($product->getCustomAttribute($key)) {
                $product->getCustomAttribute($key)->setValue($value);
            }
        }

        return $product;
    }
```

**Comment by engcom-Hotel** [comment]
Hello @brideo,

We have tried to reproduce this issue in Magento 2.4-develop branch but for us, this issue is not reproducible. We are able to update both `short description` and `description` via the below API:

![image](https://user-images.githubusercontent.com/51681618/148916274-bb913de0-4068-4ccb-8cdd-71d99c608153.png)

Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @brideo,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
