### ISSUE TITLE
Crowdin translations aren't updating to the composer language packages

### ISSUE THREAD

**Issue by mlaurense** [magento/magento2#34833]
### Preconditions (*)

1. N/A (all versions)

### Steps to reproduce (*)

1. Translations are made on https://crowdin.com/project/magento-2/activity-stream
2. Translations are not visible in their composer packages, e.g. https://github.com/magento-l10n/language-nl_NL

### Expected result (*)

1. Translations should be in the Github projects within a day or two

### Actual result (*)

1. On december 6, the last change to the Romanian community language pack was committed on Github, as seen on https://github.com/magento-l10n/
2. On that same day, changes to the crowdin project were made:
![Schermafbeelding 2021-12-17 om 08 40 26](https://user-images.githubusercontent.com/16759472/146507935-8ac1f97d-f845-4b6e-9b2a-7acb354287a8.png)
3. Since december 6, multiple changes to several translations have been made on Crowdin

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @mlaurense,

We have checked the translation in this [Github repo](https://github.com/magento-l10n/language-da_DK) and we are able to find the translation in a CSV file. 

Please let me know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mlaurense,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
