### ISSUE TITLE
Why https://www.magento.com redirect to https://business.adobe.com

### ISSUE THREAD

**Issue by vrkansagara** [magento/magento2#34834]
issue :- **Why https://www.magento.com redirect to https://business.adobe.com**

Any strategic decision behind **Magento Open source** ? or Someone is playing !

**Comment by engcom-Hotel** [comment]
Hello @vrkansagara,

The issue is not related with core Magento functionality. This board is using for collecting the issues occurs in Magento code modules. So we are closing this issue.

Thanks

**Comment by vrkansagara** [comment]
@engcom-Hotel Can you tell me the right place for raising this issue ?

**Comment by vrkansagara** [comment]
Ping @m2-community-project re-open this issue.
