### ISSUE TITLE
Magento 2.4 translate checkout, quantity in product page, compare and my wishlist near search bar

### ISSUE THREAD

**Issue by tradeincarthage** [magento/magento2#34841]
Hi Guys)

Preconditions
Magento 2.4
Steps to reproduce and Environment
I have a multilanguage store.

I used the GitHub method to install relevant language packs The file containing the different language packs is located at /var/www/html/magento/app/i18n/Mageplaza Each language pack such as fr_fr, ar_sa is composed of: composer.json, language.xml, license, registration.php, fr_FR.csv

I have almost everything translated on the website except some special strings:

1-Quantity (on the product page)

2- My wishlist and Compare near the Search bar

3-The whole checkout after I click on add to cart including VIEW CART, GO TO CHECKOUT and you added ....... product to the shopping cart

4- Translate Enter your destination to get a shipping estimate

I tried to put those strings in my CSV file but all of them were not translated to the target language.

Thank you very much)

**Comment by engcom-Hotel** [comment]
Hi @tradeincarthage,

Mageplaza translation is a 3rd party extension and the code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as a community is not able to provide a fix for it in this repository. All questions, issue reports, and fixes for them should be addressed to the corresponding extension. 

Thank you
