### ISSUE TITLE
Media manager bad behaviour

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3484]
Hello,

This issue is really getting me crazy. When editing a product in backend, with 5 pictures, sometimes, only the base picture is shown in pictures list and sometimes all pictures are ahown. When that happen, I am afraid to save the product thinking that maybe all pictures will be removed from the product but the first one.

I check in database, and product pictures are in fact assigned to the product. I don't know why sometimes only 1 picture is shown and sometimes all pictures are shown.

Please, test this feature deeply.

This screenshot shows only 1 product:

![product_pictures_bad](https://cloud.githubusercontent.com/assets/9195659/13177052/7a583864-d6f5-11e5-9f41-4706bd1bda63.png)

And you could see this in database (above picture shows product whose ID is 1). (note that there are 3 media files that are not shown, and they correspond to videos)

![product_images_db](https://cloud.githubusercontent.com/assets/9195659/13177285/d2db3422-d6f6-11e5-984c-03190282780d.png)

And after several refreshes, I could finally make the page to show all images:

![product_pictures_good](https://cloud.githubusercontent.com/assets/9195659/13177592/e9fee9da-d6f8-11e5-874d-cadf92dcac62.png)

Regards
Jaime

**Comment by AurelienLavorel** [comment]
Hi,
I have the same issue and also got log in system.log :

> main.CRITICAL: Warning: Invalid argument supplied for foreach() in app/code/Magento/Catalog/Block/Product/View/Gallery.php on line 112 [] []
> main.CRITICAL: Warning: Invalid argument supplied for foreach() in app/code/Magento/ProductVideo/Block/Product/View/Gallery.php on line 52 [] []

**Comment by wert2all** [comment]
Please, provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by vincentwinkel** [comment]
Each time we have a problem with Magento2 (actually 10 times per day), we see a lot of people in the same situation since several months / years, and you just close the tickets without fixing anything.
Stats to be pathetic...

**Comment by AurelienLavorel** [comment]
Magento ver. 2.2.0-dev, since the Magento ver. 2.1.0-dev
