### ISSUE TITLE
Upgrade 2.4.2 to 2.4.3 error: Integrity constraint violation

### ISSUE THREAD

**Issue by zeekinfo** [magento/magento2#34845]
I was trying to upgrade from 2.4.2 to 2.4.3 in my test environment. While trying to run bin/magento setup:upgrade,

The below error appeared:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '249191' for key 'PRIMARY', query was: ALTER TABLE catalog_url_rewrite_product_category ADD CONSTRAINT PRIMARY KEY (url_rewrite_id)

How to fix these issues

**Comment by ihor-sviziev** [comment]
Hi @zeekinfo,
Thank you so much for your report!
I'm closing this issue as a duplicate of https://github.com/magento/magento2/issues/33770.
