### ISSUE TITLE
Dynamic rows component behaves incorrectly when a new element is added

### ISSUE THREAD

**Issue by densen45** [magento/magento2#34850]
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

The following process leads to two issues.

1. Create a Grouped Product
2. Add about 30+ Simple Products to the Grouped Product (at least "display per page" + 1, but it is clearer when you add more)
3. Save the Grouped Product
4. Add another Simple Product to the Grouped Product
5. Go to the last page of the pagination
6. Notice that the newly added Simple Product is shown at the top of the last page (**first issue**)
7. Change the position of a Simple Product that was added before (not the new one) by editing the position number
8. Notice that the newly added Simple Product is moved (**second issue**)

### Expected result (*)

1. The newly added product is in the last position
2. Changing the position of another Simple Product (not the new one) does not affect the position of the newly added Simple Product

### Actual result (*)

1. The newly added product is not in the last position, instead it is in the first position of the last page
2. Changing the position of another Simple Product (not the new one) affects the position of the newly added Simple Product. It is moved to the last position or to the "display per page" + 1 position (have not found the pattern yet).

### Workaround
1. Before adding a new Simple Product: display so many products per page that all Simple Products are displayed on one page
2. Add a new Simple Product

### Investigation (so far)
The issue also holds for the dynamic rows of the Bundle Products Options. Probably the entire Backend is affected where ever the dynamic rows component is used.

#### Adding a new Simple Product to a Grouped Product
The newly added product (`obj`) gets its position in 
https://github.com/magento/magento2/blob/2c2b2745151ecf2872f006c109d355f7a01ba9db/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows-grid.js#L256-L259
The `this.setMaxPosition();` function from the above code snippet calls the function
https://github.com/magento/magento2/blob/2c2b2745151ecf2872f006c109d355f7a01ba9db/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js#L802-L813
Inside that function the `this.maxPosition` from the above code snippet is "calculated" and set. So far so good.
The problem is, that `this.elems` only contains the elements of the current page and not all elements. Thus, when you have displayed 20 elements and you are on the first page, `this.maxPosition` is set to the position of the last element on this page, which is 19 (starts at 0). And this is the value (+1) the newly added Simple Product gets assigned. 
When you than go to the last page, the newly added Simple Product is for some milliseconds in the last place (because the index is correct) but then the position attributes are checked and since it has the smallest position on this page, it is moved to the top of this page.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment]
@magento give me 2.4.2-p2 instance

**Comment by densen45** [comment]
Reproduced on the provided 2.4.2-p2 instance.

**Comment by densen45** [comment]
@magento give me 2.4-develop instance

**Comment by densen45** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and issue 1 is reproducible but issue 2 is not reproducible. Hence updating the description.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2020 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2020&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
