### ISSUE TITLE
Magento 2.4 translate checkout, quantity in product page, compare and my wishlist near search bar 

### ISSUE THREAD

**Issue by tradeincarthage** [magento/magento2#34854]
Hi Guys)

Preconditions
Magento 2.4
Steps to reproduce and Environment
I have a multilanguage store.

I already installed my language packs The file containing the different language packs is located at /var/www/html/magento/app/i18n/  Each language pack such as fr_fr, ar_sa is composed of: composer.json, language.xml, license, registration.php, fr_FR.csv....

I have almost everything translated on the website except some special strings:

1-Quantity (on the product page)

2- My wishlist and Compare near the Search bar

3-The whole checkout after I click on add to cart including VIEW CART, GO TO CHECKOUT and you added ....... product to the shopping cart

4- Translate Enter your destination to get a shipping estimate

I tried to put those strings in my CSV file but all of them were not translated to the target language.

My js.translation.json is not empty but do not contait the needed translations

Thank you very much)

I tried to do static deployment after puting product on csv file but no way it becomes translated

Should i add the needed translations directly inside js-translation.json? 
I can do it in all languages except in arabic beacause arabic language js-translation.json contains some strange caracters like a1a2,... maybe json file cannot read arabic

or there is other way to translation checkout buttons, and other special strings?

Except result

All special strings should be translated to target language.

Actual Results
All special strings are still in English, still showing, Quantity, My wishlist, Compare, VIEW CART, GO TO CHECKOUT....

Thank you very much

**Comment by engcom-Hotel** [comment]
Hi @tradeincarthage,

Could you please provide the steps/commands/screenshots, how you installed the language packs?

Thank you.

**Comment by engcom-Hotel** [comment]
Dear @tradeincarthage,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
