### ISSUE TITLE
Trouble in creating shipment records for child items for order for bundle products.

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#3486]
Here we have two scenarios to observer
1) order created for bundle-product which has value "separately" set for "Ship Bundle Items" field in it's settings : As shown in picture

![i2](https://cloud.githubusercontent.com/assets/12557241/13177780/532e556a-d741-11e5-8659-2011f281d16a.PNG)

If we create shipment record for child items via api "POST /V1/shipment/" it creating shipment record but with no data under "Items Shipped" block on shipment record, as shown in screenshot
![i1](https://cloud.githubusercontent.com/assets/12557241/13177875/d0a6e020-d741-11e5-8b24-554a60c23287.PNG)

Also , we are able to create shipment for entire bundle product perfectly , which should not be the case since we have opted "seperatey" for shipping in items settings.

2) order created for bundle-product which has value "together" set for "Ship Bundle Items" field:  
  The behavior is same here as it happening in scenario 1. Point to be noted here is for bundle product with "together" shipping setting, we should not be able to create shipments record for child items even if it is with blank data for "Items Shipment" record on shipment record.

**Comment by KrystynaKabannyk** [comment]
The internal ticket is created MAGETWO-51640.

**Comment by ruby10** [comment]
Hi @NadiyaS , @KrystynaKabannyk  any news on it??

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Trouble-in-creating-shipment-records-for-child-items-for-order/idi-p/46413).

**Comment by anupwankhede** [comment]
@magento-engcom-team  can we get this fix in 2.1 or 2.2 versions as well ?
As its critical for business , kind of must have one in active stable releases :)
