### ISSUE TITLE
Price indexer slow for configurable BaseStockStatusSelectProcessor (Partial Clone from Issue 33763)

### ISSUE THREAD

**Issue by steven-hoffman-jomashop** [magento/magento2#34875]
Preconditions (*)
1) Magento 2.4.2
2) Catalog with lot of configurable products

Steps to reproduce (*)
1) Reindex catalog_product_price

Expected result (*)
1) Fast

Actual result (*)
1) Slow (in my case it never ends)

Please see https://github.com/magento/magento2/issues/33763.
Please see my last comment below

Also: 
- Is there a procedure for re-opening tickets?

---

Hi @engcom-Lima,

We see this issue on 2.4.3:

```
INSERT INTO `catalog_product_index_price_cfg_opt_temp`
SELECT `le`.`entity_id`, `i`.`customer_group_id`, `i`.`website_id`, MIN(final_price), MAX(final_price), MIN(tier_price)
FROM `catalog_product_index_price` AS `i`
INNER JOIN `catalog_product_super_link` AS `l` ON l.product_id = i.entity_id
INNER JOIN `catalog_product_entity` AS `le` ON le.row_id = l.parent_id AND (le.created_in <= '1637600400' AND le.updated_in > '1637600400')
INNER JOIN `cataloginventory_stock_item` AS `si` ON si.product_id = l.product_id
INNER JOIN `cataloginventory_stock_item` AS `si_parent` ON si_parent.product_id = l.parent_id
WHERE (si.is_in_stock = 1) OR (si_parent.is_in_stock = 0) AND (le.entity_id IN (502243, 251917, 251927, 691473, 691475, 691476, 691507, 691505))
GROUP BY `le`.`entity_id`,`customer_group_id`,`website_id` 
ON DUPLICATE KEY UPDATE `min_price` = VALUES(`min_price`), `max_price` = VALUES(`max_price`), `tier_price` = VALUES(`tier_price`)
```
You can see that the WHERE clause is 1WHERE X OR Y AND Z1; as per [mysql docs](https://dev.mysql.com/doc/refman/8.0/en/operator-precedence.html) AND is higher precedence then OR.
Thus the above WHERE clause `WHERE X OR Y AND Z` is really: `WHERE X OR (Y AND Z)` which is not correct.

You can see that [\Magento\ConfigurableProduct\Model\ResourceModel\Product\Indexer\Price\Configurable::fillTemporaryOptionsTable adds a where clause](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/Indexer/Price/Configurable.php#L196) on the le.entity_id.

Also, you can see that the $this->baseSelectProcessor->process($select) call is made before the where adds the le.entity_id filter. (Line 214 vs line 229).
You should be able to 'reproduce' by echoing the select after line 230; though I am not 100% of the sequence needed to hit line 229. (Full reindex vs partial).
(You definitely need a configurable with options)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @steven-hoffman-jomashop,

Thank you for raising this issue.

I have re-opened issue #33763 as requested and closing this one. Discussion can be continued on old issue only.

Thanks
