### ISSUE TITLE
Store Pickup Not Available for Products with Custom Options When SKU is Assigned to Custom Options

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#34889]
### Preconditions (*)

1. Magento 2.4.3-p1
2. Enable Store Pickup
3. Assign custom stock to all products (so store pickup will become available during checkout)

### Steps to reproduce (*)

1. Assign custom option (i.e. text field) to a product
2. Assign a SKU for the custom option (i.e. "TEST1001")
2. Add the product to cart

<img width="1130" alt="custom" src="https://user-images.githubusercontent.com/20729592/147515702-f8016de9-3c80-4acd-9dfa-660121d271d5.png">

### Expected result (*)

1. Store Pickup should be available during checkout

### Actual result (*)

1. Store Pickup is unavailable during checkout

---

Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @uandiweb,

Thanks for raising an issue , Kindly help us in knowing the which module or extension you had used for store pickup.
Regards,

**Comment by uandiweb** [comment]
Hi @engcom-Delta

I use the default Magento store pickup module (not a 3rd party extension). It works fine as long as custom options don't have a sKU assigned to it.

Thank you!

**Comment by engcom-Delta** [comment]
Hi @uandiweb ,
Thank you for prompt reply. We tried to reproduce it on Magento 2.4 Develop with latest branch , Issue is reproducible.

Steps followed:
**Pre-Condition:**
1. Inventory module should have been installed successfully.
2. Store--> Sources--> create new source
<img width="1440" alt="Screenshot 2022-03-01 at 2 55 35 PM" src="https://user-images.githubusercontent.com/51681379/156145697-5389f500-a8c4-47f0-bafd-5c7e783c7bdf.png">
3. Go to Stores--> Stocks and add new stock with custom store pickup
<img width="1440" alt="Screenshot 2022-03-01 at 3 07 28 PM" src="https://user-images.githubusercontent.com/51681379/156145785-17e259dd-7bc7-4b4a-8775-1e4fd3762277.png">
4. Enable store pickup from Stores > Settings > Configuration>Expand Sales > Choose Delivery Methods

**Steps:**
1. Assign custom option (i.e. text field) to a product by editing from Catalog--> Product
<img width="1440" alt="Screenshot 2022-03-01 at 3 08 13 PM" src="https://user-images.githubusercontent.com/51681379/156145265-eead0ec7-da87-4ed3-af2e-e81c1fbfe172.png">
2. Assign a SKU for the custom option (i.e. "TEST1001")
<img width="1440" alt="Screenshot 2022-03-01 at 3 08 23 PM" src="https://user-images.githubusercontent.com/51681379/156145178-37f85be9-43ba-4626-b7af-18c002551fb8.png">
3. Add the product to cart
<img width="1440" alt="Screenshot 2022-03-01 at 3 16 28 PM" src="https://user-images.githubusercontent.com/51681379/156145471-6a6ca0fc-3fff-4e50-a19c-ef87efa0f965.png">
4. Go to checkout page and observe the shipping method section
**Actual Results** 
Created store pick up is not available in Shipping Methods section
<img width="1440" alt="Screenshot 2022-03-01 at 2 51 12 PM" src="https://user-images.githubusercontent.com/51681379/156147343-1184004e-c5b9-4dc0-9342-561d92ba2567.png">

Hence issue is confirmed.

**Comment by engcom-Hotel** [comment]
Hi @engcom-Delta,

As per the triage meeting, we need to recheck this issue.

Thanks

**Comment by engcom-Delta** [comment]
Hi @uandiweb ,
As per above comments , issue is not reproducible. Hence request to review the provided steps.
Thanks

**Comment by engcom-Delta** [comment]
Hi @uandiweb ,
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
Thanks
