### ISSUE TITLE
attribute is not deleted from products

### ISSUE THREAD

**Issue by bkristl** [magento/magento2#3488]
Steps with example:
1) i create attribute for example **foot_high** - type dropdown with values 10cm, 20cm, 30cm
2) i assign that attribute to attribute set for example **furniture**
3) i created product with attribute set furniture and select value 100cm  for attribute **foot_high** 
4) I save product
5) then i open attribute set furniture and remove  attribute foot_high and save it
6) reindexing is also done

Problem:
When i go to front end site and search by filters (layered navigation), the same attribute appears.
So i could filter product by attribute which not exist.

Solution:
1) When attribute is removed from attribute set, it also must be deleted (attribute) from products  with that attribute set.

**Comment by palamar** [comment]
@bkristl 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by bkristl** [comment]
I think it was version 2.0.2. I can not remember, because i have always
upgraded to the last version when it was available.

**Comment by magento-engcom-team** [comment]
@bkristl, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
