### ISSUE TITLE
critical CSS needs to move

### ISSUE THREAD

**Issue by in-session** [magento/magento2#34899]
### Preconditions (*)

1. Use CSS critical path

### Steps to reproduce (*)

1.  Configuration>Developer>Use CSS critical path>Yes

### Expected result (*)
1. Critical CSS should appear before all link tags

### Actual result (*)

1. At present it is only issued after the Fonts

**Comment by in-session** [comment]
@magento give me 2.4-develop instance

**Comment by in-session** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @in-session,

Issue description is empty. Can you please update issue description with below details of the issue so that we can check further:

1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

Thanks

**Comment by in-session** [comment]
@magento give me 2.4-develop instance

**Comment by in-session** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance
