### ISSUE TITLE
Make grunt to load tasks automatically

### ISSUE THREAD

**Issue by ravbetsky** [magento/magento2#3491]
Currently if I want to add my custom grunt task to M2 front-end workflow I need to modify Gruntfile.js because all tasks located in `dev/tools/grunt/tasks/` are adding manually in it (see Gruntfile.js). 

``` javascript
    [
        taskDir + '/mage-minify',
        taskDir + '/deploy',
        taskDir + '/black-list-generator',
        taskDir + '/clean-black-list',
        taskDir + '/static',
        'time-grunt'
    ].forEach(function (task) {
        require(task)(grunt);
    });
```

So if I need to add some task, for example `sprite` I must modify Gruntfile.js like this:

``` javascript
    [
        taskDir + '/mage-minify',
        taskDir + '/deploy',
        taskDir + '/black-list-generator',
        taskDir + '/clean-black-list',
        taskDir + '/static',
        taskDir + '/sprite'  // Added my task here
        'time-grunt'
    ].forEach(function (task) {
        require(task)(grunt);
    });
```

This a minor change, but however this is a core file which can be updated after upgrade. Is it a good practice?

**Comment by alankent** [comment]
It is a problem. We are thinking of doing something like shipping Gruntfile.js.sample instead to overcome this problem. You would then copy it to the Gruntfile.js and take responsibility to merge in any changes later. I am not sure the final solution, but you are right - it is a problem. For now my advice is to change the file and be aware that doing an upgrade will need to to save copies of all changes made to core files so you can reapply them. From our side, we need to make sure that external parties _never_ need to touch the core. We have achieved a lot, but there are a few gaps still that we are working towards plugging.

**Comment by ravbetsky** [comment]
Alan,

May be you can just scan `dev/tools/grunt/tasks/` folder for any `*.js` files and then return them as an array of tasks. This solution will prevent from modifying `Gruntfile.js`.

I've created a pull request, may be it can help [https://github.com/magento/magento2/pull/3492]

**Comment by alankent** [comment]
Thanks. I will pass it onto the team (internal reference MAGETWO-48461). Have you also seen the work by SnowdogApps on Gulp? I have not timed it, but some people claim it is faster. https://github.com/SnowdogApps/magento2-frontools

**Comment by ravbetsky** [comment]
Thank you. Gulp is much faster then grunt. I'll check this link, may be in future M2 will use gulp instead of grunt.

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-48461 is closed and delivered to mainline.
