### ISSUE TITLE
Product Plugin(Magento\Catalog\Api\ProductRepositoryInterface) not Working.

### ISSUE THREAD

**Issue by mhafizumer** [magento/magento2#34928]
**Magento Version**
CE 2.4.2-p2

**Summary**
Magento Product save plugins not Working. I have wrote **afterSave** for the type **Magento\Catalog\Api\ProductRepositoryInterface**.

Then I have try to create plugin for save method for Controller class (**Magento\Catalog\Controller\Adminhtml\Product\Save**), its worked fine

**Steps to reproduce (*)**

in etc directory create di.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Catalog\Controller\Adminhtml\Product\Save">
        <plugin type="Soscodes\PluginExample\Plugin\ProductPlugin" name="soscodes_productexample_controller" />
    </type>
 <type name="Magento\Catalog\Api\ProductRepositoryInterface">
        <plugin name="catalog_product_save_plugin_two" type="Soscodes\PluginExample\Plugin\ProductPluginTWO" />
    </type>
</config>
```

**Plugin Files code :**

```
<?php

namespace Soscodes\PluginExample\Plugin;

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Catalog\Api\ProductRepositoryInterface;

use Psr\Log\LoggerInterface;

class ProductPluginTWO
{
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function afterSave(ProductRepositoryInterface $subject, ProductInterface $result, $saveOptions = false)
    {
        $this->logger->info('products saveAfter plugin using \Magento\Catalog\Api\ProductRepositoryInterface ');
        return $result;
    }
}

```
Controller save plugin code that is work fine.

```
<?php

namespace Soscodes\PluginExample\Plugin;

use Psr\Log\LoggerInterface;

class ProductPlugin
{
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function afterExecute(\Magento\Catalog\Controller\Adminhtml\Product\Save $subject, $result)
    {
        $this->logger->info('product save contoller plugin');
        return $result;
    }
}
```

I have also written di.xml in webapi_rest folder as I followed Magento_Catalog module.

![image](https://user-images.githubusercontent.com/67052331/148116313-04bb3a9b-2296-49c1-92a9-e2ae40b2fcd8.png)

But not working for me on the Fresh Magento CE 2.4.2-p2 version.

My system.log file content is 

![image](https://user-images.githubusercontent.com/67052331/148116458-235fd5e3-9d74-4394-ab79-78864f9755de.png)

### Expected result (*)

This is the expected result in my system.log file

![image](https://user-images.githubusercontent.com/67052331/148116610-0158c738-066b-4af9-a731-28793e7d9444.png)

I have also attached my module zip file here

[Soscodes.zip](https://github.com/magento/magento2/files/7810185/Soscodes.zip)

**Comment by engcom-Hotel** [comment]
Hello @mhafizumer,

Thanks for posting the issue!

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, it is not reproducible with the given steps. Maybe we have missed anything in order to reproduce the issue.

We request you to please elaborate on the issue more.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mhafizumer,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
