### ISSUE TITLE
Multiple default choice bug 

### ISSUE THREAD

**Issue by ad1rie1** [magento/magento2#3493]
When you add new product attribut you can select only one default choice, normal. 

but if you edit the attribute, it transform the select to checkbox . And you can select multiple default :D 
And if you add new option it spanw select 

checkbox :
![bug1](https://cloud.githubusercontent.com/assets/1949622/13197041/818858b6-d7e1-11e5-828d-ea9037b1a49c.png)

Add option : 
![bug2](https://cloud.githubusercontent.com/assets/1949622/13197045/88e2add2-d7e1-11e5-92c5-b23b90afe828.png)

**Comment by anton-huz** [comment]
Hi  ad1rie1,
Could I ask you about browser that was used by you?
And it would be handy if you tell how Magento was installed? From Composer or Github, from `develop` or `2.0`  branch.

**Comment by ad1rie1** [comment]
ok, The magento used is downloaded from magento2 Website, not directly downloaded from git.My install is updated in 2.0.2. 
I'm using the last version of chrome browser

**Comment by vzabaznov** [comment]
Thanks for reporting, could you please provide a proper steps to reproduce the bug, seems like this problem cannot be reproduced on current main branch, but maybe you have some specific scenario @ad1rie1

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
