### ISSUE TITLE
Url rewrites are all removed when mass updating visibility on store view when set to not visible indivudually.

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#34937]
### Preconditions (*)

1. php 7.4
2. composer 1
3. Magento version 2.4.2 enterprise
4. RabbitMQ

### Steps to reproduce (*)

1. Have a multi store website (2-5 store views)
2. Create a product that's connected to all stores make sure attribute code: **visibility** is on **catalog,search**
3. Now go to backend Catalog -> Product. Select the created product and use the action update attributes.
4. Now select a specific store view after change the attribute code: **visibility** to **Not Visible Individually**
5. Now click on Save.

### Expected result (*)

1. Only the urls of the specific store for the specific product should be deleted in the url_rewrite table.

### Actual result (*)

1. **ALL** urls are removed of the specific product in the url_rewrite table and Admin UI - Marketing - URL Rewrites page

What my two cents tells me what it is.
I have debugged the issue and found out that the following observer does not take into account that the mass action can be done on store level (see https://github.com/magento/magento2/blob/8afdb9858d238392ecb5dbfe556068ec1af137bc/app/code/Magento/Catalog/Setup/CategorySetup.php#L722). If you look in these two classes you see that it does not take into account that the user could change the visibility on store view. See these two classes:
* https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/CatalogUrlRewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
* https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/CatalogUrlRewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php

While it does take account for the global way it does not take account that it can be set on store view. When you look at the dispatch of the event: 
* https://github.com/magento/magento2/blob/8afdb9858d238392ecb5dbfe556068ec1af137bc/app/code/Magento/Catalog/Model/Product/Action.php#L92

It does pass a store id. I think the store level should be taken into account to resolve this issue.

I believe this is a S1 problem there are workarounds by changing it in the database or changing everything manual but it's a lot of work to fix. And this could give merchant problems with their SEO while they are not aware of it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by leonhelmus** [comment]
It seems it did not work @engcom-Hotel

**Comment by igorwulff** [comment]
@magento give me 2.4-develop instance

**Comment by Aquarvin** [comment]
```diff --git a/vendor/magento/module-catalog-url-rewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php b/vendor/magento/module-catalog-url-rewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
This is a proposition to solve the issue. The idea is to pass store ID to appropriate methods:

--- a/vendor/magento/module-catalog-url-rewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php	
+++ b/vendor/magento/module-catalog-url-rewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php	(date 1642437502101)
@@ -43,12 +43,13 @@
         $event = $observer->getEvent();
         $attrData = $event->getAttributesData();
         $productIds = $event->getProductIds();
+        $storeId = $event->getStoreId();
         $visibility = $attrData[ProductInterface::VISIBILITY] ?? 0;
 
         if (!$visibility || !$productIds) {
             return;
         }
 
-        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility);
+        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility, $storeId);
     }
 }

diff --git a/vendor/magento/module-catalog-url-rewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php b/vendor/magento/module-catalog-url-rewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
--- a/vendor/magento/module-catalog-url-rewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php	
+++ b/vendor/magento/module-catalog-url-rewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php	(date 1642437629598)
@@ -65,9 +65,10 @@
      *
      * @param array $productIds
      * @param int $visibility
+     * @param int $storeId
      * @throws UrlAlreadyExistsException
      */
-    public function execute(array $productIds, int $visibility): void
+    public function execute(array $productIds, int $visibility, int $storeId): void
     {
         $products = $this->getProductsByIds($productIds);
 
@@ -78,6 +79,7 @@
                     [
                         UrlRewrite::ENTITY_ID => $product->getId(),
                         UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
+                        UrlRewrite::STORE_ID => $storeId,
                     ]
                 );
             } elseif ($visibility !== Visibility::VISIBILITY_NOT_VISIBLE) {```

**Comment by leonhelmus** [comment]
@magento give me 2.4-develop instance

**Comment by leonhelmus** [comment]
@magento-mts-pre-check-svc

**Comment by Aquarvin** [comment]
The solution given above solve this issue. But it is not complete, problem still occurs when we change visibility back to "Catalog, Search", take a look at https://github.com/magento/magento2/issues/35036 
I propose this solution https://github.com/magento/magento2/issues/35036#issuecomment-1027194217 as a full fix for both tickets.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Issue: After setting the product visibility to "Not visible individually" for only one specific store view using "Update Attributes", all entries of product are deleted from url_rewrite table

**Comment by leonhelmus** [comment]
We also have a fix when doing this with the api will share it tomorrow

**Comment by vijay-prevaj** [comment]
Patch to resolve this issue..

`diff --git a/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php b/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
index f5851cf..a816285 100644
--- a/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
+++ b/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
@@ -65,21 +65,21 @@ public function __construct(
      *
      * @param array $productIds
      * @param int $visibility
+     * @param int $storeId
      * @throws UrlAlreadyExistsException
      */
-    public function execute(array $productIds, int $visibility): void
+    public function execute(array $productIds, int $visibility, int $storeId): void
     {
-        $products = $this->getProductsByIds($productIds);
+        $products = $this->getProductsByIds($productIds, $storeId);
 
         /** @var Product $product */
         foreach ($products as $product) {
             if ($visibility == Visibility::VISIBILITY_NOT_VISIBLE) {
-                $this->urlPersist->deleteByData(
-                    [
-                        UrlRewrite::ENTITY_ID => $product->getId(),
-                        UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
-                    ]
-                );
+                $this->urlPersist->deleteByData([
+                    UrlRewrite::ENTITY_ID => $product->getId(),
+                    UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
+                    UrlRewrite::STORE_ID => $storeId
+                ]);
             } elseif ($visibility !== Visibility::VISIBILITY_NOT_VISIBLE) {
                 $product->setVisibility($visibility);
                 $productUrlPath = $this->urlPathGenerator->getUrlPath($product);
@@ -110,11 +110,13 @@ public function execute(array $productIds, int $visibility): void
      * Get Product Models by Id's
      *
      * @param array $productIds
+     * @param int $storeId
      * @return array
      */
     private function getProductsByIds(array $productIds): array
     {
         $productCollection = $this->productCollectionFactory->create();
+        $productCollection->setStoreId($storeId);
         $productCollection->addAttributeToSelect(ProductInterface::VISIBILITY);
         $productCollection->addAttributeToSelect('url_key');
         $productCollection->addFieldToFilter(
diff --git a/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php b/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
index 2337bb3..57fb93d 100644
--- a/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
+++ b/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
@@ -43,12 +43,13 @@ public function execute(Observer $observer)
         $event = $observer->getEvent();
         $attrData = $event->getAttributesData();
         $productIds = $event->getProductIds();
+        $storeId = $event->getStoreId();
         $visibility = $attrData[ProductInterface::VISIBILITY] ?? 0;
 
         if (!$visibility || !$productIds) {
             return;
         }
 
-        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility);
+        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility, (int)$storeId);
     }
 }`

**Comment by leonhelmus** [comment]
This patch i applied for apis, sorry for the delay.

```

diff --git a/Observer/ProductProcessUrlRewriteSavingObserver.php b/Observer/ProductProcessUrlRewriteSavingObserver.php
--- a/Observer/ProductProcessUrlRewriteSavingObserver.php
+++ b/Observer/ProductProcessUrlRewriteSavingObserver.php
@@ -18,6 +18,8 @@
 use Magento\UrlRewrite\Model\Exception\UrlAlreadyExistsException;
 use Magento\UrlRewrite\Model\UrlPersistInterface;
 use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
+use Magento\Catalog\Api\Data\ProductInterface;
+use Magento\Catalog\Model\Attribute\ScopeOverriddenValue;

 /**
  * Class ProductProcessUrlRewriteSavingObserver
@@ -46,6 +48,11 @@
      */
     private $getStoresList;

+    /**
+     * @var ScopeOverriddenValue|null
+     */
+    private ?ScopeOverriddenValue $scopeOverriddenValue;
+
     /**
      * @param UrlPersistInterface $urlPersist
      * @param AppendUrlRewritesToProducts|null $appendRewrites
@@ -56,12 +63,15 @@
         UrlPersistInterface $urlPersist,
         AppendUrlRewritesToProducts $appendRewrites,
         ScopeConfigInterface $scopeConfig,
-        GetStoresListByWebsiteIds $getStoresList
+        GetStoresListByWebsiteIds $getStoresList,
+        ?ScopeOverriddenValue $scopeOverriddenValue = null
     ) {
         $this->urlPersist = $urlPersist;
         $this->appendRewrites = $appendRewrites;
         $this->scopeConfig = $scopeConfig;
         $this->getStoresList = $getStoresList;
+        $this->scopeOverriddenValue = $scopeOverriddenValue ?: \Magento\Framework\App\ObjectManager::getInstance()
+            ->create(ScopeOverriddenValue::class);
     }

     /**
@@ -103,7 +113,22 @@
         );
         if ((int)$product->getVisibility() === Visibility::VISIBILITY_NOT_VISIBLE) {
             $isGlobalScope = $product->getStoreId() == Store::DEFAULT_STORE_ID;
-            $storesToRemove[] = $isGlobalScope ? $product->getStoreIds() : $product->getStoreId();
+            $storesToRemove = [];
+            if ($isGlobalScope) {
+                foreach ($product->getStoreIds() as $storeId) {
+                    if (!$this->scopeOverriddenValue->containsValue(
+                        ProductInterface::class,
+                        $product,
+                        \Magento\Catalog\Api\Data\ProductInterface::VISIBILITY,
+                        $storeId
+                    )
+                    ) {
+                        $storesToRemove[] = $storeId;
+                    }
+                }
+            } else {
+                $storesToRemove[] = $product->getStoreId();
+            }
         }
         if ($storesToRemove) {
             $this->urlPersist->deleteByData(

```

**Comment by engcom-Alfa** [comment]
Hi @Reporter ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-2535&type=commits).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by leonhelmus** [comment]
@engcom-Alfa thanks for solving it!

**Comment by willbrammer** [comment]
Still appears to be an issue on 2.4.6 Adobe Commerce, will explore patches provided by Aquavrin
