### ISSUE TITLE
Magento - I can't click on any of the lateral tabs

### ISSUE THREAD

**Issue by mdvm7** [magento/magento2#34936]
Hello! 

I'm using Magento ver. 2.4.3-p1 to do a groupwork for my master degree. The site for the backend was working completely fine, until yesterday. I accessed the backend to edit the project, but unlike the other times I've accessed it, now I can't click on any of the lateral tabs. I need to add more products for the e-commerce project, but when I try to click and enter the catalog tab, nothing happens. The same happens for the all the other options.

Hopefully someone can help me fix this! Thanks.

**Comment by engcom-November** [comment]
Hi @mdvm7 ,
Thank you for reporting and collaboration. However, provided description is not enough to reproduce the issue. Verified the issue on Magento 2.4.3-p1version and user is able to perform all operations from Back-end. Kindly provide missing steps to reproduce / configuration details to reproduce the issue.

**Comment by engcom-November** [comment]
Hi @mdvm7 ,
We are closing this issue as there has been no latest update on the same.
Thank you.
