### ISSUE TITLE
[GraphQl] Product query does not give translated attribute label

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#34944]
### Preconditions (*)
1. On Magento 2.3.6

### Steps to reproduce (*)
1. Run the Product Query on a store with translated attribute label and retrieve aggregations

### Expected result (*)
1. Get the aggregations are translated

### Actual result (*)
1. The aggregations are not trabslated

### Workaround
- In vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php
- Add this left join

```
->joinLeft(
    ['option_label_store' => $this->resourceConnection->getTableName('eav_attribute_label')],
    "a.attribute_id = option_label_store.attribute_id AND option_label_store.store_id = {$storeId}",
    [
        'attribute_label' => $connection->getCheckSql(
            'option_label_store.attribute_label_id > 0',
            'option_label_store.value',
            'a.frontend_label'
        )
    ]
)
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @alexmtch,

Thank you for reporting the issue.

However, the information provided is not enough for me to reproduce this. Can you please share the GraphQl query that you are running and the actual results plus what you expect the results to be ?

Any other info would also be helpful. We'll do further analysis accordingly.

Thanks

**Comment by korovitskyi** [comment]
Hi, @shikhamis11 , @cpartica .
It was checked translation (attribute label and option label) (magento `2.4-develop` branch).
And, it works OK.
Want to notice that translation of attributes is setting in the attribute, but not by the `i18n`.

**Here is the testing result view:**

- changed locale to Germany:
<img width="2645" alt="image" src="https://user-images.githubusercontent.com/74533818/153871623-a6c27e94-c534-4e86-be57-895dd35b9c4c.png">

- added translates by `i18n`:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/74533818/153871813-611cf3a1-c8a3-4c18-8075-aaa44439f9fd.png">

- added translate to the attribute `material` for default store:
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/74533818/153872092-236931e0-3de4-43ad-a0cb-f8fff828c43a.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/74533818/153872177-11f9f004-d529-43b4-a28c-4f1e9256ee69.png">

- frontend side view:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/74533818/153872283-545d9cd9-b2eb-4e25-b4dc-81dec7561564.png">

- GraphQl response view:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/74533818/153872419-216a7963-1c76-44aa-81fa-a51770c8e77d.png">

So, I think this issue may be closed.
Or maybe @alexmtch will give some more information about some specific cases.
Thank you.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
yes, @alexmtch the attribute label and its option label's stores values are given from backend attribute settings not through i18n. I also checked translation for attribute label and option label on the `Magento 2.4-develop` instance. It seems to work fine. so @cpartica we can close it. 



<img width="894" alt="Screenshot at Feb 15 10-12-55" src="https://user-images.githubusercontent.com/25526037/153994235-6b711ab8-8c6d-4e6e-bec6-21d7dd5c7c31.png">
<img width="741" alt="Screenshot at Feb 15 10-13-46" src="https://user-images.githubusercontent.com/25526037/153994291-8c6ee417-5a05-4c0d-99b7-602ce870e27a.png">
<img width="745" alt="Screenshot at Feb 15 10-14-48" src="https://user-images.githubusercontent.com/25526037/153994352-14d09e18-87a5-48aa-8a1c-38dba5e5cda7.png">

**Comment by engcom-Hotel** [comment]
Hello @alexmtch,

As confirmed by PO this is not an issue & the feature is working as expected. Hence closing this issue.

Thanks

**Comment by alexmtch** [comment]
Hello @engcom-Hotel Have you tester in 2.3.6 version of Magento ? As i see in 2.4.3 this is resolved as i see you've done excactly what i've done and submitted on the post description

```
->joinLeft(
                ['attribute_label' => $this->resourceConnection->getTableName('eav_attribute_label')],
                "a.attribute_id = attribute_label.attribute_id AND attribute_label.store_id = {$storeId}",
                [
                    'attribute_store_label' => 'attribute_label.value',
                ]
            )
```
