### ISSUE TITLE
Less file got some issue with compilation (undefined variable) if file name not have prefix underscore at the begin

### ISSUE THREAD

**Issue by tuna2smc** [magento/magento2#34945]
### Summary (*)

Got this behavior in lower version 2.3.2 Magento EE. Not test at latest version
My code base have many files less. I have got this experiences when import custom less file to custom theme. File don't have underscore at begin of file name

After run static content deploy. Magento console raise below error 

Compilation from source: file abc.less
variable @media-common is undefined in file. Something like that. Super weird behavior

Example code
Scenario for reproduce

app/design/vendor_name/theme/web/css/source/_extend.less

now we import second less file into file _extend.less. 2 files will stay at same folder source

like this
```less
//Here is demo file content _extend.less

/// Others code v.v.

@import 'base';

```

app/design/vendor_name/theme/web/css/source/base.less
Content file less base like this
```less
& when (@media-common = true) {
// Styles
}
```
Results
```less
@import 'base'; // FAILS => COMPILATION  UNDEFINED VARIABLE @MEDIA-COMMON

@import '_base'; // WORKS AS NORMAL AFTER RENAME FILE WITH UNDERSCORE AT BEGIN
```

Use local deploy with compact strategy mode. Actually file with or without underscore should act normal . Seem magento restricts and only load file with underscore

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tuna2smc** [comment]
![error](https://user-images.githubusercontent.com/82012895/148628167-3b134241-ba0b-43c8-a002-67bae0147643.png)
Can reproduce same behavior in latest

**Comment by taintedstephen** [comment]
Any less file in a Magento theme without a leading underscore is treated as though it should be its own css file when the theme is compiled. The underscore denotes it is included in another file and therefore shouldn't be compiled unless it is imported somewhere else.

**Comment by tuna2smc** [comment]
Yeap but imho i think we should add some notify/notes somewhere for this one to avoid misleading or miss-acknowledges

**Comment by engcom-Charlie** [comment]
Hi @tuna2smc,

As per the Magento naming convention mentioned in [this](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-themes.html), if you wants to import a custom less file then it should start with an underscore "_".

As per Magento implementation its an expected behaviour and hence not considering it as an issue. Hence closing the same.

Thank you!
