### ISSUE TITLE
Can't add more images to previously imported products

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3494]
I can add images to new created products on Magento ver 2.0.1. However, when I try to add more images to previously imported products, the images don't show up in the "Images and videos" section. If I clic the "Save" button, the backend freezes.

The imported products include one image which shows up in back and front end. The issue happens when I try to add a 2nd, 3rd... image to the product.

**Comment by jsakars** [comment]
Seems to work fine on 2.0.2

**Comment by jibrandlr** [comment]
I just upgraded to 2.0.2 but the issue is still present

**Comment by jsakars** [comment]
@lgarridoj how are You importing Your products? Try adding a product manually from backend and see if the issue is present

**Comment by jibrandlr** [comment]
The issue occurs only in products imported via CSV files.

**Comment by jibrandlr** [comment]
Solved. The issue solved when correcting permissions on the installation.
