### ISSUE TITLE
414 (Request-URI Too Large) when using "add products manually"

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#3495]
Scenario
A configurable product with a large amount of attached variants (150 - 10 size & 15 colour)
Press Add Products Manually to add more variants.
Pop up appears, but spinning wheel appears and just sits there forever.

Error: 
In browser console.
Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

With Apache the limit is a configurable using LimitRequestLine. This value can be changed to something larger than its default of 8190 but its not recommend.  Apache even says "Under normal conditions, the value should not be changed from the default."

After some research if you're actually running into this limit it means you are using a "get" rather than "post" to transmit the data.

This will be problematic for those on shared or managed hosting.  Increasing the value is also a security risk. 

Is there a work around to adding products manually? 

`http://example.com/admin/catalog/product/associated_grid/componentJson/1/key/c73c2acbe4f05f2ec7984b4d0e739fd0f4526029eacc480e7058d3484e5be630/?filters=&attributes_codes%5B%5D=colour_config&attributes_codes%5B%5D=size_config&filters_modifier%5Bcolour_config%5D%5Bcondition_type%5D=notnull&filters_modifier%5Bsize_config%5D%5Bcondition_type%5D=notnull&filters_modifier%5Bentity_id%5D%5Bcondition_type%5D=nin&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=31448&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=310&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=336&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=362&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=388&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=414&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=440&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=31449&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=326&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=31034&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=378&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=404&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=430&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=456&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23161&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23162&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23163&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23164&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23165&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23166&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23167&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23147&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23148&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23149&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23150&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23151&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23152&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23153&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35033&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35034&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35035&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35036&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35037&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35038&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35039&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23411&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23412&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23413&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23414&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23415&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23416&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23417&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30729&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30730&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30731&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=364&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=390&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30734&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30735&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61600&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61601&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61602&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61603&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61604&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61605&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=61606&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23182&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23183&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23184&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23185&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23186&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23187&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23188&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23175&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23176&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23177&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23178&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23179&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23180&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23181&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35040&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35041&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35042&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35043&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35044&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35045&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35046&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35047&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35048&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35049&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35050&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35051&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35052&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35053&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30717&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30718&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=343&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30719&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=395&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30720&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30721&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30722&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30723&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30724&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30725&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30726&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30727&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30728&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23126&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23127&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23128&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23129&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23130&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23131&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23132&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23119&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23120&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23121&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23122&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23123&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23124&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23125&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35054&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35055&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35056&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35057&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35058&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35059&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35060&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35061&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35062&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35063&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35064&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35065&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35066&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=35067&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30736&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30737&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30738&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30739&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30740&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30741&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=30742&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23154&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23155&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23156&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23157&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23158&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23159&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23160&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23168&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23169&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23170&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23171&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23172&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23173&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=23174&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1239&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1240&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1241&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1242&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1243&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1244&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1245&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1260&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1261&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1262&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1263&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1264&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1265&filters_modifier%5Bentity_id%5D%5Bvalue%5D%5B%5D=1266&isAjax=true`

**Comment by veloraven** [comment]
@rkhoury82 thank you for your feedback.
If this issue is still actual please provide used Magento version.
If it is not, please close the issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by depyou** [comment]
2.4.4 didn't solve the problem

**Comment by MaxStetsenko** [comment]
> 2.4.4 didn't solve this problem

Did you find a solution?

**Comment by rohitkumawat17** [comment]
I am facing the same issue in Magento 2.4.5-p1. Any solution there?

**Comment by ProxiBlue** [comment]
This problem exists in 2.4.4-p11

![Image](https://github.com/user-attachments/assets/ad5b6ff2-1d7e-440d-ae71-e447f140ce83)

**Comment by ProxiBlue** [comment]
@veloraven can you please re-open this ticket, as it is not solved, and the issue is ongoing. Or, is there a related ticket for this issue.

**Comment by ProxiBlue** [comment]
ah:  https://github.com/magento/magento2/issues/36282
