### ISSUE TITLE
Do NOT update stock status on CSV Product import if quantity is 0 and "Allow Qty Below 0 and Notify Customer" is set

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#34957]
### Preconditions (*)

1. Magento v2.4.3-p1

### Steps to reproduce (*)

1. Stores > Configuration > Catalog: Inventory > Backorders: Allow Qty Below 0 and Notify Customer

2. Choose a product that is in stock with a qty greater than 0.

3. System > Import > Entity Type: Products > Import Behavior: Add/Update > Import a file to set the qty to 0, e.g:

```
"sku","qty"
"test-sku","0"
```

### Expected result (*)

a) The qty is changed to 0
b) The stock status remains "In Stock"

The stock status should NOT be changed because when backorders are set to "Allow Qty Below 0 and Notify Customer" Magento does NOT change the stock status when the qty reaches 0.

### Actual result (*)

a) The qty is changed to 0
b) The stock status is changed to "Out of stock"

This behaviour appears to come from a previous issue that was fixed:

https://github.com/magento/magento2/issues/23042
https://github.com/magento/magento2/pull/24053

However, when backorders are set to "Allow Qty Below 0 and Notify Customer" Magento does NOT change the stock status when the qty reaches 0, therefore it shouldn't change it when the qty 0 is imported with this setting enabled.

**Comment by engcom-Echo** [comment]
Hi @atIOCrON,

Thank you for reporting the issue.

We have tried this issue on Magento 2.4-dev/2.4.3-P1 and we have successfully reproduced it.

Steps followed to reproduce issue:
1. Installed the clean Magento 2.4-dev/2.4.3-P1.
2. Updated Backorders to “Allow Qty Below 0 and Notify Customer”.
3. Import new product by setting the quantity to “0”. (CSV file is attached)
[catalog_product_1.csv](https://github.com/magento/magento2/files/7860301/catalog_product_1.csv)
4. Observed the stock status for the uploaded imported product in the admin and for the customer.
5. Product status is set to out of stock and the product is not salable to the frontend (See the attached screenshots)

<img width="1428" alt="1 Screenshot 2022-01-12 at 8 36 34 PM" src="https://user-images.githubusercontent.com/51681435/149274162-5080ec31-6e98-45df-9f42-7f211ab6418b.png">
<img width="1428" alt="2 Screenshot 2022-01-12 at 8 36 43 PM" src="https://user-images.githubusercontent.com/51681435/149274169-ec92ca9c-4204-414c-83c3-6c3da59cf755.png">

The Backorders configuration is not working as stated in the documentation(https://docs.magento.com/user-guide/catalog/inventory-backorders.html), hence confirming the issue.

Thanks

**Comment by DiVoronovich** [comment]
@magento give me 2.4-develop instance

**Comment by zhartaunik** [comment]
@magento give me 2.4-develop instance

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by zhartaunik** [comment]
Unable to reproduce locally

**Comment by pmaryglobalia** [comment]
vendor/magento/module-catalog-import-export/Model/Import/Product.php
This code added at Line 3208 is the culprit: 
`  if (isset($rowData['qty']) && $rowData['qty'] == 0) {
                $row['is_in_stock'] = 0;
            }`
It does not take in account the back order setting of the product

**Comment by Zaahed** [comment]
@magento I am working on this

**Comment by Zaahed** [comment]
@magento give me 2.4-develop instance

**Comment by Zaahed** [comment]
Can't reproduce this in 2.4-develop either. Backorders is set to `Allow Qty Below 0 and Notify Customer`. Set an existing product's qty to zero by importing a CSV file, stock status remains `In Stock` as expected.

**Comment by engcom-Delta** [comment]
Hi @atIOCrON ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Stores > Configuration > Catalog: Inventory > Backorders: Allow Qty Below 0 and Notify Customer
2. Choose a product that is in stock with a qty greater than 0.
3. System > Import > Entity Type: Products > Import Behavior: Add/Update > Import a file to set the qty to 0
[catalog_product_1.csv](https://github.com/user-attachments/files/17406746/catalog_product_1.csv)
Observe Qty is 0 and stock is "Instock"
![image](https://github.com/user-attachments/assets/caaf114c-ba91-45f1-a205-389130db813d)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @atIOCrON ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
