### ISSUE TITLE
Mobile menu sub category link goes to undefined

### ISSUE THREAD

**Issue by mohanwbsofttech** [magento/magento2#34955]
I am using Ibnab_MegaMenu module. Everything is working fine on desktop. But in mobile when I am clicking on category link it showing me undefined . This is my website link https://www.ruralcam.com/

**Comment by mohanwbsofttech** [comment]
Summary of the issue:I am using Ibnab_MegaMenu module. Everything is working fine on desktop. But in mobile when I am clicking on category link it showing me undefined . This is my website link https://www.ruralcam.com/
    Information on your environment: Magento2.3.4 open community 
    Steps to reproduce: check this url https://www.ruralcam.com/ in mobile and click on menu item under product categories.
    Expected results: Need to open category URL .
    Actual results: the URL showing undefned.

**Comment by engcom-November** [comment]
Hi @mohanwbsofttech  ,
Thank you for reporting. However, Ibnab_MegaMenu is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
