### ISSUE TITLE
Orders page - Filtering with Purchase Date is not working when removed and re-applied

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#34954]
### Preconditions (*)

1. Magento 2.4-develop having Orders

### Steps to reproduce (*)

1. Admin - Sales - Orders
2. Filters - Purchase Date - Select from and To date 
3. Apply Filter - No Issue. Filter applied
4. Remove/Close the Filter
5. Click again on Filters
6. Previous filter dates are displayed and apply same filters - Issue. Filter not working
Issue also observed when only To Date is changed and filter applied. Filter not working properly.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

Attached Video for reference
1. [Screenshots, log
[b92b71bc-9999-40e0-9595-00e1420a4554 (1).zip](https://github.com/magento/magento2/files/7845886/b92b71bc-9999-40e0-9595-00e1420a4554.1.zip)
s or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@engcom-November We will reverify this ticket. Hence moving it to the **Ready for confirmation** board.

**Comment by engcom-Hotel** [comment]
Hello @engcom-November,

Thanks for posting the issue!

We have tried to reproduce the issue in Magento 2.4-develop and it is reproducible for us with the mentioned steps.

Hence confirming this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @engcom-November,

Thanks for posting the issue!

We have tried to reproduce the issue in Magento 2.4-develop and it is reproducible for us with the mentioned steps.

Hence confirming this issue.

Thanks

**Comment by ksenia-zlotin** [comment]
@engcom-Hotel Is there an update on this issue? Still seeing this in Magento 2.4.4-p2.

**Comment by engcom-Hotel** [comment]
Hello @ksenia-zlotin,

Thanks for asking for the updates!

As I can see the JIRA status of this issue, is still in the `implementation` phase. As per the process, someone from internal will pick this issue and raise a PR to fix this. 

The issue can also be picked by the community as well to open up a public PR, we will process them as well.

Thanks

**Comment by ksenia-zlotin** [comment]
@engcom-Hotel This is still happening in Adobe Commerce 2.4.4-p6. Is there a patch provided for this issue? Just looking for an update on this issue, thanks!
