### ISSUE TITLE
Color picker wrong value

### ISSUE THREAD

**Issue by NguyenXuanNam** [magento/magento2#34967]
### Preconditions (*)

1. Magento version 2.4.2 and 2.4.1
### Steps to reproduce (*)

1. Go to stores -> Product -> filter color 
2. Go to manage swatch, chooose any color,  select chooose a color, enter hexcolor : ff7a96 -> Save Attribute. 
3. After save value : ff7a97

### Expected result (*)

Hex color : ff7a96

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by nisha-vaghela** [comment]
@magento i am working on this

**Comment by rvr-robert** [comment]
@magento I am working on this

**Comment by rvr-robert** [comment]
The bug is reproduced in a third-party library (colorpicker.js). I understand that third party libraries should not be edited. This pr fixes the bug described in the problem. If left as is, this bug will be reproduced until this library is changed. The author of colorpicker.js hasn't changed anything since 2009 (https://www.eyecon.ro/colorpicker/#download)

**Comment by NguyenXuanNam** [comment]
thanks.
