### ISSUE TITLE
how can i export all my Produkt Images??? 

### ISSUE THREAD

**Issue by Exxor87** [magento/magento2#34961]
### Preconditions (*)

1. Magento ver. 2.3.6

Hi Dear Magento Team,

we have over 6000 Products in our coldewerk.de shop. 
We just want to export all product images as files or as URLs.
we dont know exactly what to export to get them.

Looking Forward to hear from you soon.

Enlil Arevalo

**Comment by krishprakash** [comment]
Hi @Exxor87. Thank you for your report.
Github issue tracker is intended for magento core technical issues only
Kindly refer [community forum](https://community.magento.com/) or [magento stack exchange](https://magento.stackexchange.com) for general discuss about this problem
