### ISSUE TITLE
Server error during the ordering process. Skus are interpreted as floats

### ISSUE THREAD

**Issue by Ligniperdus** [magento/magento2#34965]
### Preconditions (*)
1. Magento 2.4.1

### Steps to reproduce (*)
**GUI way:**
1. Create two simple products with sku _00.060_ and sku _0.060_
2. Add both items to the shopping cart
3. Go though the checkout and try to purchase the articles

**Code way:**
1. Open \Magento\InventoryCatalog\Model\ResourceModel\GetProductTypesBySkus.php
2. Call the function `getResultKey(string $sku, array $productSkuList)` with those parameters: `$sku = "00.060"`, `$productSkuList = [1000 => 0.060, 1001 => 00.060]`

### Expected result (*)
**GUI way:**
1. The checkout finishes successfully

**Code way:**
1. The return should be _00.060_

### Actual result (*)
**GUI Way**
1. Server error
2. exception.log -> `main.CRITICAL: Notice: Undefined index: 00.060 in /.../vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php on line 156`

**Code way**
1. The return is _0.060_

### Reason
The array_search function interprets the string skus as floats.

### Solution
Set the optional strict_parameter of the array_search function to TRUE
`$key = array_search(strtolower($sku), array_map('strtolower', $productSkuList), true);`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Ligniperdus ,
We are closing this issue as there has been no latest update on the same.
Thank you.
