### ISSUE TITLE
VAT on Delivery Cost is wrongly calculated.

### ISSUE THREAD

**Issue by MelissaVE** [magento/magento2#34976]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MelissaVE** [comment]
![BTW](https://user-images.githubusercontent.com/97790897/149622208-93e67bbb-4784-4911-93f5-58e37723d456.PNG)

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by nuzil** [comment]
Hi @MelissaVE  can you rovide a bit more infromation what is wrong? My Dutch is not so good as I want to :-) 
Also how Tax is configured in your system in details

**Comment by MelissaVE** [comment]
Magento ver. 2.4.1-p1

Tax on deliv. cost is INCL.
Tax on product cost is INCL.
6% Tax rate

Subtotal €31,48 + Del cost €2,99 = Total €34,47 (CORRECT)

If you do the callculation 6% on the total cost, this should be €2,06. But only the subtotal tax is shown, not the delivery tax €0,18. So most of the time we're missing the tax on the delivery cost.

@nuzil : if you need more info, just ask ;-)

**Comment by MelissaVE** [comment]
![image](https://user-images.githubusercontent.com/97790897/150008673-50931789-9c72-4642-ae34-7879ee258b55.png)

**Comment by engcom-November** [comment]
Hi @MelissaVE ,
We are closing this issue as there has been no latest update on the same.
Thank you.
