### ISSUE TITLE
Increment and decrement button is not working with decimal

### ISSUE THREAD

**Issue by marcelloinfoweb** [magento/magento2#34970]
The increment and decrement button is not working with the setting of the decimal value on the products page. It is always set to 1 or -1.

Products that can only be sold by fractions, for example: Product A with Qty Increments of 0.2.

Magento 2.4.2

**Comment by engcom-November** [comment]
Hi @marcelloinfoweb,
Increment and Decrement buttons are not present in Store front - Product Details / Shopping Cart pages in Clean 2.4-develop instance. Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps / configuration details to reproduce the issue.
Thank you.

**Comment by engcom-Hotel** [comment]
Dear @marcelloinfoweb,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
