### ISSUE TITLE
Error after disabling MSI on v2.3.4

### ISSUE THREAD

**Issue by pcis-mub** [magento/magento2#34978]
We have been using this site for over a year now and MSI was a pain since the inventory was always wrong. So eventualy we decided to disable MSI. Everything worked fine on the dev instance but as soon as disabled MSI on LIVE; we started getting error during compile

### Preconditions (*)
1. Magento v2.4.0 with MariaDB 10.2.38
2. PHP 7.2.34
3. Apache 2.4.6
4. redis 6.2.4
5. CloudFlare Firewall & CDN

### Steps to reproduce (*)
1.1. Updated composer.json as shown below and then ran composer update
`{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "eadesigndev/module-fullbreadcrumbs": "^1.0",
        "ebizmarts/magento2-mandrillsmtp": "^102.3",
        "facebook/php-business-sdk": "^9.0",
        "magento/product-community-edition": "2.3.4",
        "mageplaza/module-core": "^1.4",
        "mailchimp/mc-magento2": "102.3.43"
    },
    "replace": {      
        "magento/inventory-composer-installer":"*",
        "magento/inventory-composer-metapackage":"*",
        "magento/module-inventory": "*",
        "magento/module-inventory-admin-ui": "*",
        "magento/module-inventory-advanced-checkout": "*",
        "magento/module-inventory-requisition-list": "*",
        "magento/module-inventory-api": "*",
        "magento/module-inventory-bundle-import-export": "*",
        "magento/module-inventory-bundle-product": "*",
        "magento/module-inventory-bundle-product-indexer": "*",
        "magento/module-inventory-bundle-product-admin-ui": "*",
        "magento/module-inventory-cache": "*",
        "magento/module-inventory-catalog": "*",
        "magento/module-inventory-catalog-admin-ui": "*",
        "magento/module-inventory-catalog-api": "*",
        "magento/module-inventory-catalog-frontend-ui": "*",
        "magento/module-inventory-catalog-search": "*",
        "magento/module-inventory-catalog-search-bundle-product": "*",
        "magento/module-inventory-catalog-search-configurable-product": "*",
        "magento/module-inventory-configurable-product": "*",
        "magento/module-inventory-configurable-product-admin-ui": "*",
        "magento/module-inventory-configurable-product-frontend-ui": "*",
        "magento/module-inventory-configurable-product-indexer": "*",
        "magento/module-inventory-configuration": "*",
        "magento/module-inventory-configuration-api": "*",
        "magento/module-inventory-distance-based-source-selection": "*",
        "magento/module-inventory-distance-based-source-selection-admin-ui": "*",
        "magento/module-inventory-distance-based-source-selection-api": "*",
        "magento/module-inventory-export-stock": "*",
        "magento/module-inventory-export-stock-api": "*",
        "magento/module-inventory-elasticsearch": "*",
        "magento/module-inventory-graph-ql": "*",
        "magento/module-inventory-grouped-product": "*",
        "magento/module-inventory-grouped-product-admin-ui": "*",
        "magento/module-inventory-grouped-product-indexer": "*",
        "magento/module-inventory-import-export": "*",
        "magento/module-inventory-indexer": "*",
        "magento/module-inventory-in-store-pickup": "*",
        "magento/module-inventory-in-store-pickup-admin-ui": "*",
        "magento/module-inventory-in-store-pickup-api": "*",
        "magento/module-inventory-in-store-pickup-frontend": "*",
        "magento/module-inventory-in-store-pickup-graph-ql": "*",
        "magento/module-inventory-in-store-pickup-multishipping": "*",
        "magento/module-inventory-in-store-pickup-quote": "*",
        "magento/module-inventory-in-store-pickup-quote-graph-ql": "*",
        "magento/module-inventory-in-store-pickup-sales": "*",
        "magento/module-inventory-in-store-pickup-sales-admin-ui": "*",
        "magento/module-inventory-in-store-pickup-sales-api": "*",
        "magento/module-inventory-in-store-pickup-shipping": "*",
        "magento/module-inventory-in-store-pickup-shipping-admin-ui": "*",
        "magento/module-inventory-in-store-pickup-shipping-api": "*",
        "magento/module-inventory-in-store-pickup-webapi-extension": "*",
        "magento/module-inventory-low-quantity-notification": "*",
        "magento/module-inventory-low-quantity-notification-admin-ui": "*",
        "magento/module-inventory-low-quantity-notification-api": "*",
        "magento/module-inventory-multi-dimensional-indexer-api": "*",
        "magento/module-inventory-quote-graph-ql": "*",
        "magento/module-inventory-product-alert": "*",
        "magento/module-inventory-reservations": "*",
        "magento/module-inventory-reservations-api": "*",
        "magento/module-inventory-reservation-cli": "*",
        "magento/module-inventory-sales": "*",
        "magento/module-inventory-sales-admin-ui": "*",
        "magento/module-inventory-sales-api": "*",
        "magento/module-inventory-sales-frontend-ui": "*",
        "magento/module-inventory-setup-fixture-generator": "*",
        "magento/module-inventory-shipping": "*",
        "magento/module-inventory-shipping-admin-ui": "*",
        "magento/module-inventory-source-deduction-api": "*",
        "magento/module-inventory-source-selection": "*",
        "magento/module-inventory-source-selection-api": "*",
        "magento/module-inventory-swatches-frontend-ui": "*",
        "magento/module-inventory-visual-merchandiser": "*",
        "magento/module-inventory-wishlist": "*",
        "Magento_CatalogInventoryGraphQl": "*"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "friendsofphp/php-cs-fixer": "~2.14.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "~4.0.0",
        "magento/magento2-functional-testing-framework": "2.5.3",
        "pdepend/pdepend": "2.5.2",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "~3.4.0"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.4",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}`
2. run "bin/magento maintenance:enable && php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy -f && bin/magento cache:flush && bin/magento maintenance:disable"

### Expected result (*)
1. MSI module should get removed from the instance
2. site should start working after complie and static content deploy

### Actual result (*)
1. php bin/magento setup:di:compile runs into an error and the website throws a 503 "Service Temporarily Unavailable" error
`Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 42 secs 326.0 MiB
In ClassReader.php line 43:
                                                                           
  Class Magento\InventoryApi\Api\SourceRepositoryInterface does not exist  
                                                                           

In ClassReader.php line 36:
                                                                           
  Class Magento\InventoryApi\Api\SourceRepositoryInterface does not exist  
                                                                           

setup:di:compile`

Severity: **S0**

**Comment by engcom-Hotel** [comment]
Hello @pcis-mub,

Thanks for posting the issue!

Please let us know the exact changes you made in the `composer.json` file. This will help us in the reproduction of the issue.

Thanks

**Comment by pcis-mub** [comment]
We added the following modules under "replace" in composer.json 

	"replace": {
		"magento/inventory-composer-installer": "*",
		"magento/inventory-composer-metapackage": "*",
		"magento/module-inventory": "*",
		"magento/module-inventory-admin-ui": "*",
		"magento/module-inventory-advanced-checkout": "*",
		"magento/module-inventory-requisition-list": "*",
		"magento/module-inventory-api": "*",
		"magento/module-inventory-bundle-import-export": "*",
		"magento/module-inventory-bundle-product": "*",
		"magento/module-inventory-bundle-product-indexer": "*",
		"magento/module-inventory-bundle-product-admin-ui": "*",
		"magento/module-inventory-cache": "*",
		"magento/module-inventory-catalog": "*",
		"magento/module-inventory-catalog-admin-ui": "*",
		"magento/module-inventory-catalog-api": "*",
		"magento/module-inventory-catalog-frontend-ui": "*",
		"magento/module-inventory-catalog-search": "*",
		"magento/module-inventory-catalog-search-bundle-product": "*",
		"magento/module-inventory-catalog-search-configurable-product": "*",
		"magento/module-inventory-configurable-product": "*",
		"magento/module-inventory-configurable-product-admin-ui": "*",
		"magento/module-inventory-configurable-product-frontend-ui": "*",
		"magento/module-inventory-configurable-product-indexer": "*",
		"magento/module-inventory-configuration": "*",
		"magento/module-inventory-configuration-api": "*",
		"magento/module-inventory-distance-based-source-selection": "*",
		"magento/module-inventory-distance-based-source-selection-admin-ui": "*",
		"magento/module-inventory-distance-based-source-selection-api": "*",
		"magento/module-inventory-export-stock": "*",
		"magento/module-inventory-export-stock-api": "*",
		"magento/module-inventory-elasticsearch": "*",
		"magento/module-inventory-graph-ql": "*",
		"magento/module-inventory-grouped-product": "*",
		"magento/module-inventory-grouped-product-admin-ui": "*",
		"magento/module-inventory-grouped-product-indexer": "*",
		"magento/module-inventory-import-export": "*",
		"magento/module-inventory-indexer": "*",
		"magento/module-inventory-in-store-pickup": "*",
		"magento/module-inventory-in-store-pickup-admin-ui": "*",
		"magento/module-inventory-in-store-pickup-api": "*",
		"magento/module-inventory-in-store-pickup-frontend": "*",
		"magento/module-inventory-in-store-pickup-graph-ql": "*",
		"magento/module-inventory-in-store-pickup-multishipping": "*",
		"magento/module-inventory-in-store-pickup-quote": "*",
		"magento/module-inventory-in-store-pickup-quote-graph-ql": "*",
		"magento/module-inventory-in-store-pickup-sales": "*",
		"magento/module-inventory-in-store-pickup-sales-admin-ui": "*",
		"magento/module-inventory-in-store-pickup-sales-api": "*",
		"magento/module-inventory-in-store-pickup-shipping": "*",
		"magento/module-inventory-in-store-pickup-shipping-admin-ui": "*",
		"magento/module-inventory-in-store-pickup-shipping-api": "*",
		"magento/module-inventory-in-store-pickup-webapi-extension": "*",
		"magento/module-inventory-low-quantity-notification": "*",
		"magento/module-inventory-low-quantity-notification-admin-ui": "*",
		"magento/module-inventory-low-quantity-notification-api": "*",
		"magento/module-inventory-multi-dimensional-indexer-api": "*",
		"magento/module-inventory-quote-graph-ql": "*",
		"magento/module-inventory-product-alert": "*",
		"magento/module-inventory-reservations": "*",
		"magento/module-inventory-reservations-api": "*",
		"magento/module-inventory-reservation-cli": "*",
		"magento/module-inventory-sales": "*",
		"magento/module-inventory-sales-admin-ui": "*",
		"magento/module-inventory-sales-api": "*",
		"magento/module-inventory-sales-frontend-ui": "*",
		"magento/module-inventory-setup-fixture-generator": "*",
		"magento/module-inventory-shipping": "*",
		"magento/module-inventory-shipping-admin-ui": "*",
		"magento/module-inventory-source-deduction-api": "*",
		"magento/module-inventory-source-selection": "*",
		"magento/module-inventory-source-selection-api": "*",
		"magento/module-inventory-swatches-frontend-ui": "*",
		"magento/module-inventory-visual-merchandiser": "*",
		"magento/module-inventory-wishlist": "*",
		"Magento_CatalogInventoryGraphQl": "*"
	}

**Comment by engcom-Hotel** [comment]
Hello @pcis-mub,

In order to disable the MSI module, you can follow the below command:
```
php bin/magento module:disable -f Magento_Inventory Magento_InventoryAdminUi Magento_InventoryApi Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCatalog Magento_InventorySales Magento_InventoryCatalogAdminUi Magento_InventoryCatalogApi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProduct Magento_InventoryConfigurableProductAdminUi Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventoryIndexer Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryReservations Magento_InventoryReservationsApi Magento_InventoryCache Magento_InventorySalesAdminUi Magento_InventorySalesApi Magento_InventorySalesFrontendUi Magento_InventoryShipping Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventorySourceSelectionApi Magento_InventoryShippingAdminUi Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticsearch Magento_InventoryExportStockApi Magento_InventoryReservationCli Magento_InventoryExportStock Magento_CatalogInventoryGraphQl Magento_InventorySetupFixtureGenerator Magento_InventoryAdvancedCheckout Magento_InventoryDistanceBasedSourceSelection Magento_InventoryRequisitionList Magento_InventoryGraphQl Magento_InventoryBundleImportExport Magento_InventoryBundleProductIndexer Magento_InventoryInStorePickupApi Magento_InventoryInStorePickupAdminUi Magento_InventoryInStorePickup Magento_InventoryInStorePickupGraphQl Magento_InventoryInStorePickupShippingApi Magento_InventoryInStorePickupQuoteGraphQl Magento_InventoryInStorePickupSales Magento_InventoryInStorePickupSalesApi Magento_InventoryInStorePickupQuote Magento_InventoryInStorePickupShipping Magento_InventoryInStorePickupShippingAdminUi Magento_InventoryInStorePickupFrontend Magento_InventoryInStorePickupMultishipping Magento_InventoryInStorePickupSalesAdminUi Magento_InventoryInStorePickupWebapiExtension Magento_InventoryCatalogFrontendUi Magento_InventoryConfigurableProductFrontendUi Magento_InventorySwatchesFrontendUi Magento_InventoryVisualMerchandiser Magento_InventoryWishlist
```
Or read devdocs on this [link](https://devdocs.magento.com/extensions/inventory-management/) for more Information.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @pcis-mub,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
