### ISSUE TITLE
Bulk API operation field is too small

### ISSUE THREAD

**Issue by mischabraam** [magento/magento2#34980]
https://github.com/magento/magento2/blob/44a86cbbc5a2d6c8309de34922818c3e04b2dcd1/app/code/Magento/AsynchronousOperations/etc/db_schema.xml#L45

As you can see in the db schema the type of column `serialized_data` is `BLOB`. This is very short. If you consider processing a lot of data is faster doing asynchronously I would expect that this column can at least store data of `MEDIUMBLOB`.

**Comment by nuzil** [comment]
Hi @mischabraam did you have usecases when data was bigger then 64Kb? 
Cause we using API intensively and didnt hit this limit with Magento APIs

**Comment by engcom-Hotel** [comment]
Hello @mischabraam,

Thanks for posting the issue!

I agree with @nuzil, please let us know the use case. It will help us in issue reproduction.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mischabraam,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by mischabraam** [comment]
Sorry, missed your question. But yes, I've had use cases where we hit the limit, otherwise I wouldn't create this issue ;)
