### ISSUE TITLE
Customer who exceeded max login failures not able to login even after reset password

### ISSUE THREAD

**Issue by MagicLegend** [magento/magento2#34981]
### Preconditions (*)

1. Magento 2.4.0 CE

### Steps to reproduce (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is still active

### Expected result (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is removed

### Actual result (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is still active
4. The User account will active after sometime

This was fixed before in #15255. However, this commit removed this one-line fix again: https://github.com/magento/magento2/commit/cdc0fd39bac4218fe16eecb34ee7ffa407ac94ca#diff-b8e39c5ed5e0b80ed62825ba186962adf41803236c50285ab7466ec65f632967L627

What is the reason for removing this fix?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @MagicLegend,

Thanks for posting this issue!

We have tried to reproduce the issue in Magento 2.4-develop branch and it is not reproducible for us, we have followed all the steps mentioned in the main description. 

The account has been unlocked after some time, please ensure that the cron has been installed for that instance. Let us know if we have missed anything.


Thanks

**Comment by MagicLegend** [comment]
@engcom-Hotel 

But that is not the issue. The issue is that it doesn't immediately unlock the account after a password reset. This caused confusion for our customers, and I personally agree that it is odd behaviour that I can't see a security-improvement for. I see that this used to be the case before M2.4, so I am wondering why this was changed.

Thank you for your time.

**Comment by engcom-Hotel** [comment]
Hello @MagicLegend,

I agree with your point that the user is not unlocked immediately. Hence confirming the issue and edit the main description accordingly:

**After exceeded max login failures(Frontend):**
![image](https://user-images.githubusercontent.com/51681618/151763063-a6f6b337-d6e5-40fd-8444-4e67ef3ac9ee.png)

**After exceeded max login failures(Backend):**
![image](https://user-images.githubusercontent.com/51681618/151763165-3e0c0994-79a1-47e8-af74-cb5475638eaa.png)

**After resetting the password (Frontend), still unable to log in:**
![image](https://user-images.githubusercontent.com/51681618/151763523-7f0d17dc-1b54-449d-a135-0e5099f7198b.png)

In the admin panel, the user status is still locked.

Thanks

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @MagicLegend,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2235 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2235&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
