### ISSUE TITLE
add option limit only 248 of dropdown or multiselect atribut on magento 2

### ISSUE THREAD

**Issue by binamandiri** [magento/magento2#3498]
i try to make new atribut with "Catalog Input Type for Store Owner = multiselect ( or dropdown )" but when i add option the limit is only 248 option i can add. if we add more than 248 they are not appear.

![new picture](https://cloud.githubusercontent.com/assets/17111300/13204135/b7e4f5ee-d8fa-11e5-8dc0-42895a27ca75.png)

on magento 1.9.xx theres no problem like this

**Comment by palamar** [comment]
@binamandiri 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by binamandiri** [comment]
@palamar 
it was tested on magento 2.02, since i use 1.9.2.4 i dont test it anymore on newest update magento 2.07

**Comment by kandy** [comment]
Described issue  related to PHP setting max_input_vars. By default, it's set to 1000 and allow save  ~250 option (4 input need per option). Increase this setting to 100000 and its resolve your problem.
