### ISSUE TITLE
GraphQL Bundle Options  generates wrong DB request and result

### ISSUE THREAD

**Issue by novakivskiy** [magento/magento2#34991]
The class `\Magento\BundleGraphQl\Model\Resolver\Options\Collection`  generates an erroneous query to the database.

Error in 2 parts of the code:

```
    public function addParentFilterData(int $parentId, int $parentEntityId, string $sku) : void
    {
        $this->skuMap[$parentId] = ['sku' => $sku, 'entity_id' => $parentEntityId];
    } 

```
and
```
        $optionsCollection->getSelect()->join(
            ['cpe' => $productTable],
            'cpe.'.$linkField.' = main_table.parent_id',
            []
        )->where(
            "cpe.entity_id IN (?)",
            $this->skuMap
        );
```
As a result, a query is generated:
<img width="952" alt="bundle_gql" src="https://user-images.githubusercontent.com/971021/150120264-45ed946a-189a-4ffa-82ae-16cc0615105b.png">

### Preconditions (*)

The error was repeated CE 2.3.6. In theory, the error is relevant for the latest version of magento. Mysql: 5.7.26

### Steps to reproduce (*)

1. create 2 products bundle
2. first product bundle has a sku that contains the id of the second product bundle. Example: first bundle: entity_id = 14, sku = 16D01-E, second bundle: entity_id = 16
 3. run graphql 

```query bundle($productSku:String){

  products(
    filter: { sku: { eq: $productSku } }
  ) {
    items {
      id
      type_id
      name
      sku
   ... on BundleProduct {
        items{
          option_id
        }
      }
    }  
 
  }
}
```

Variable: {"productSku":"16D01-E"}

### Expected result (*)

Graphql returns option list

### Actual result (*)

Retrieving bundle options via a module _BundleGraphQl_  returns an error:

`"debugMessage": "Notice: Undefined offset: 16 in vendor/magento/module-bundle-graph-ql/Model/Resolver/Options/Collection.php on line 130",`

S0

**Comment by dniprotrophy** [comment]
PR: https://github.com/magento/magento2/pull/34992

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
![image](https://user-images.githubusercontent.com/60198231/150350849-84520916-7286-4101-8a45-29a4dd832223.png)

Exception: 
`
[2022-01-20T13:44:26.152445+00:00] main.ERROR: Notice: Undefined offset: 16 in /var/www/html/mgcl24/magento2ce/app/code/Magento/BundleGraphQl/Model/Resolver/Options/Collection.php on line 139

GraphQL (10:9)
 9:    ... on BundleProduct {
10:         items{
            ^
11:           option_id
 [] []
`
