### ISSUE TITLE
PayPal IPN Fails with Multiple Merchant Accounts

### ISSUE THREAD

**Issue by 0xMatt** [magento/magento2#34993]
### Preconditions (*)

1. CentOS 8
2. PHP 7.4
3. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Setup default PayPal Pro merchant account information used by primary store
2. Setup secondary PayPal Pro merchant account scoped to the secondary website config

### Expected result (*)

1. IPN posts back successfully

### Actual result (*)

1. Error occurs, IPN does not use the store ID from the order

```
 main.CRITICAL: The requested "merchant@example1.com" and the configured "merchant@example2.com" merchant emails don't match. {"exception":"[object] (Exception(code: 0): The requested \"merchant@example1.com\" and the configured \"merchant@example2.com\" merchant emails don't match. at /var/www/html/magento/vendor/magento/module-paypal/Model/Ipn.php:123)"} []
```

The IPN posts back to my website id 2, but it's comparing with the email from website id 0(admin).

This results in complete failures of postback notifications.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0xMatt** [comment]
I cannot provide my PayPal credentials into a demo instance. How should I go about reproducing this? I can provide access to my server from a Magento staff member, but that's about it as far as giving any sort of access to our merchant information.

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @0xMatt,
I tried digging deep into the issue, from the code base and the log It seems that Magento is loading the proper store view i.e **second store** but the email we get in response from PayPal is different than what is configured for the **second store scope**.

`File: \Magento\Paypal\Model\Ipn::_getConfig`
```
// verify merchant email intended to receive notification
        $merchantEmail = $this->_config->getValue('businessAccount');
        if (!$merchantEmail) {
            return $this->_config;
        }
        $receiver = $this->getRequestData('business') ?: $this->getRequestData('receiver_email');
        if (strtolower($merchantEmail) != strtolower($receiver)) {
            // phpcs:ignore Magento2.Exceptions.DirectThrow
            throw new Exception(
                sprintf(
                    'The requested "%s" and the configured "%s" merchant emails don\'t match.',
                    $receiver,
                    $merchantEmail
                )
            );
        }
```
As you can see in the code base Magento tries to match the email configured in **second store** with the email received in **Paypal response data**.
Proper data is loaded from Magento end e.g for **Second Store View** email **merchant@example2.com** is loaded correctly.

Can you please try to verify in your Paypal account the same email is configured as that in your Magento instance.

Thanks!

**Comment by engcom-Hotel** [comment]
Dear @0xMatt,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by atty31** [comment]
I m still facing this on M2.4.6, any updates on this one ?
