### ISSUE TITLE
enable menu in admin pannel of magento

### ISSUE THREAD

**Issue by Humanshu24** [magento/magento2#3499]
hi all please guide me i installed magneto 2.2 in my xampp localhost directory i setup every thing once when i tried to login in admin panel it login in but all the menu are disabled i am unable to do anything in admin panel of magneto please guide me how can i enable the all menu in magneto admin panel 

thanks in advance

**Comment by mrkhoa99** [comment]
Hi,
You try to run this command under Magento root folder: 
`php bin/magento setup:static-content:deploy`

**Comment by Humanshu24** [comment]
hey **mrkhoa** actually i am totally new for magento  even i dont know how to run this command php bin/magento setup:static-content:deploy under Magento root folder if possible plz explain me step by step .

waiting from hear You
Thanks in advance

**Comment by bh-ref** [comment]
@Humanshu24 the command that mrkhoa99 mentioned has to be executed from a command line. you have to open a command line terminal (like powershell.exe on windows or bash on linux) and navigate to your magento root folder, and then execute the command.

if you are using linux and your magento root folder was /var/www/magento2, then you would use these commands:

`cd /var/www/magento2`
`php bin/magento setup:static-content:deploy`

**Comment by maksek** [comment]
Please use http://devdocs.magento.com/ for installation steps. Also if you have any question you can use forum to find answers or ask questions - https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2
