### ISSUE TITLE
Combine tier price and catalog price rules

### ISSUE THREAD

**Issue by quterorta** [magento/magento2#34994]
If we used in project tier price and catalog price rules, Magento pick rule, wich return min price. So, i have a question, how i can combine  this rules? I need the discount should be calculated based on tier price, not regular price.

**Comment by engcom-November** [comment]
Hi @quterorta ,
Verified the behavior on Magento 2.4-develop branch. Please find the observations below:
Product Created with Price: 500
Tier Price set up as below:
Catalog Price Rule Created: fixed amount: 50
![image](https://user-images.githubusercontent.com/60198231/157424346-d56d5eef-8fdf-4b85-9fb9-7af3c8525938.png)
Front- end behavior:
**Catalog Price Rule is not applied**
![image](https://user-images.githubusercontent.com/60198231/157424983-c6648e22-9b88-4d6a-84ce-a96b1157ff15.png)

Catalog Price Rule is applied only if Base Price is < Tier Price
Base Price: 300
Catalog Price Rule: 50
Tier Price: 400
![image](https://user-images.githubusercontent.com/60198231/157426257-cb4d5cc9-e149-44cf-b526-1bbed960a2cb.png)

As per Magento official [docs](https://docs.magento.com/user-guide/catalog/product-price-tier.html), final product price is calculated as the minimum relevant price, using the following formula:
Final Price=Min(Regular(Base) Price, Group(Tier) Price, Special Price, Catalog Price Rule) + Sum(Min Price per each required custom option)

Hence confirming the issue.

**Comment by engcom-November** [comment]
Hi @quterorta ,
We are closing this issue as there has been no latest update on the same.
Thank you.
