### ISSUE TITLE
add to cart is not working and cart is empty

### ISSUE THREAD

**Issue by washingtonberry** [magento/magento2#35007]
Hello,
My site ADD TO CART is not working, there is no action when I click on this button.

Sometimes it works but the cart is empty.

Please help me to resolve this problem ASAP.

Check this link https://www.royalsovereign.com/  and let me know what is the major issue with ADD TO CART.

**Comment by engcom-Hotel** [comment]
Dear @washingtonberry,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
