### ISSUE TITLE
configuration path contact/contact/recipient_email not existing in Magento 2.4.2

### ISSUE THREAD

**Issue by samueldemir** [magento/magento2#35003]
### Preconditions (*)
1. Magento version 2.4.2
2. Ubuntu 20.04

### Steps to reproduce (*)
1. Searching the conf_set path for contact 'Send Emails To' on https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-most.html
2.  Running `php bin/magento conf:set contact/contact/recipient_email xxx@xx.de` throws error that path does not exists

### Expected result (*)
1. The value for the 'Send Emails To' should be set to xxx@xx.de

### Actual result (*)
1. The "contact/contact/recipient_email" path doesn't exist. Verify and try again.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by makzef** [comment]
@samueldemir Hello.
I investigated a little and you are completely correct - the config path `contact/contact/recipient_email` is not exists.
If you look at this config in magento admin panel, you can see that the correct path is `contact/email/recipient_email`. 
So I assumed this is just a typo in magento devdocs. 

I am already created [PR](https://github.com/magento/devdocs/pull/9342) to fix this typo in devdocs repository.

Also notice: I think this kind of issues should be reported to the according repository [Magento DevDocs](https://github.com/magento/devdocs/issues).

Thank you!
