### ISSUE TITLE
Install Stuck at 0%

### ISSUE THREAD

**Issue by luc-anise** [magento/magento2#3500]
Hey guys so I was ready to install magenta on my GoDaddy VM and then it was all looking great till it got stuck at 0%. The log was of no help either all it showed was this:

```
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...
```

Also when I visit the domain without the /setup (so where the homepage would normally be) I get this error:

`Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 10880 bytes) in /home/shopstudioanise/public_html/vendor/magento/module-eav/Block/Adminhtml/Attribute/Edit/Main/AbstractMain.php on line 231`

Any insight would be greatly appreciated asap because this deployment is rather urgent. Thanks!

**Comment by luc-anise** [comment]
To answer my own question: I didn't allocate enough memory in my php.ini file (I upped it from 32M to 512M). Hope this helps anyone looking for the same answer.

**Comment by ghost** [comment]
FWIW, we recommend 768M. 512 isn't enough for sample data, for example, and you might have issues importing products.

**Comment by ishakhsuvarov** [comment]
@z6tanker Closing the ticket as the issue seems to be solved already. Please feel free to reopen if there are any further questions regarding this.

**Comment by ashik685** [comment]
Not working in my cpanel .. stuck on same .

**Comment by MonsieurLeSuisse** [comment]
Magento sucks! How can they still require mcrypt? Magento is outdated tech
