### ISSUE TITLE
GraphQl: BundleItemOption is missing `price_range`

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#35010]
### Description (*)
Unlike the rest of the pricing API, the GraphQl type `BundleItemOption` is missing a `price_range`.

### Expected behavior (*)
I can query the `price_range` of a  `BundleItemOption` 

### Benefits
Price consistency across the API.

**Comment by cpartica** [comment]
I don't think this is a feature request, but missed requirements preventing bundle product rendering 
Goal is to provide good support for Bundle products as we do for Configurables

**Comment by engcom-Alfa** [comment]
Hi @damienwebdev  ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Comment by damienwebdev** [comment]
https://github.com/magento/magento2/blob/5c97ea79ab68dbb1ff0a7182f82abaa79374722d/app/code/Magento/BundleGraphQl/etc/schema.graphqls#L50

Please read my original issue.

This doesn't address my original issue.

**Comment by damienwebdev** [comment]
@sidolov for review
