### ISSUE TITLE
AdvancedPricing  (regularPruce + absolutePrice + changing Price currency)

### ISSUE THREAD

**Issue by kattykate9** [magento/magento2#35012]
### Steps to reproduce (*)
<!---
1)Create a product with a price of 100 and a special price of 90
2)Create an option with a price of 100%
3)Set 2 currencies: USD and Euros

### Expected result (*)
regular price is the correct one - https://gyazo.com/aef7f42832969944650455effbcdbd0e 

### Actual result (*)
The regular price is twice converted - https://gyazo.com/c78d8a3c3842e52047c208981ce73780

**Comment by engcom-Echo** [comment]
Hi @kattykate9 

Thanks for reporting the issue. Please provide below information so that we can proceed with our analysis:
1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @kattykate9,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
