### ISSUE TITLE
product ordered don't show in report 

### ISSUE THREAD

**Issue by tungmpo** [magento/magento2#3501]
Hi,
I ordered some products but it don't show in  reports  at:  Reports -> Sales -> Order

Do you know why ? How to show  them   ? 

Thanks
Regards
PT Team

**Comment by rganin** [comment]
Orders with "Pending" status are not shown in report. Seems that hint in Order Status filter is incorrect.

**Comment by tungmpo** [comment]
Hi,
Thank you for your help.
When status pending  change to completed . products ordered also don't
shown in report.

Regards

**Comment by veloraven** [comment]
@tungmpo thank you for your report.
Please, provide the used Magento version. Was it clear install or upgrade from some previous version?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
