### ISSUE TITLE
Mass ShippingLabel PDF in var folder

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#35018]
### Preconditions

1. Magento <= 2.4.3

### Steps to reproduce

1. Generate and download a shipping label from the administration

### Expected result

1. The shipping label is downloaded from the browser
2. The PDF is not created / kept in the `var` folder

### Actual result

1. The PDF is kept in the `var` folder

The issue is present in the `\Magento\Shipping\Controller\Adminhtml\Order\Shipment\PrintLabel::execute` method that doesn't remove the file after preparing its download.

It was fixed for the invoices and packingslips in the issues [#14517](https://github.com/magento/magento2/issues/14517) and [#3535](https://github.com/magento/magento2/issues/3535)  but not for the shipping labels.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Axel29 ,
Verified the issue on Magento 2.4-develop branch but unable to create Shipping Label in Magento 2.4-develop branch
Shipping Method used: UPS
![image](https://user-images.githubusercontent.com/60198231/151548458-a9e5822c-00c2-45a0-a0f0-883ac0b1a6de.png)
There is an ongoing issue: unable to create shipping label for existing shipments. But looks like shipping label creation failing for new shipments as-well.
Kindly recheck the behavior on 2.4-develop branch as it is having latest code base and let us know if you are facing issues.
Thank you.

**Comment by engcom-Hotel** [comment]
Dear @Axel29,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
