### ISSUE TITLE
Create job application functionality issue

### ISSUE THREAD

**Issue by Sarvesh0639** [magento/magento2#35015]
-Magento version :2.3.2
-Mysql version :5.6
-Mode :QA/Staging/Developer/Production
-commit id :92b1fb16bebcccd92eb9bcb747f2c1377603378e
## Description

-In the first name and last name taking wrong data like "Numeric" value

## Step to Reproduce

1. Login to Admin panel
2. Navigate to job board>>View Application
3. Try to create new job 

## Expected result

-jobs should be successfully apply if enter only right data

## Actual Result
Jobs are applied taking numerical data in first name and last name 
![Screenshot_2022-01-25-12-51-07-51](https://user-images.githubusercontent.com/98222190/150932824-196d3a19-448c-4f3e-9faf-06e175f7fbff.png)

**Comment by engcom-November** [comment]
Hi @Sarvesh0639
Job board is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
