### ISSUE TITLE
Cannot instantiate interface PsrExt\Log\LoggerInterface 

### ISSUE THREAD

**Issue by Qiang156** [magento/magento2#35019]
maybe remi:php74 has some problem.

**Comment by ihor-sviziev** [comment]
Hi @Qiang156,
I think your issue caused by installed ext-psr PHP extension. 
Starting from PHP 8.0 this issue should be solved.
More info: https://github.com/jbboehr/php-psr/issues/78

**Comment by Qiang156** [comment]
@ihor-sviziev 
Thanks for your reply.
You are right, I finally found this problem when I struggled with it for two days.
Cause I have installed Phalcon4 which needs php-psr library.
I have removed it then everything comes back.
Thanks again.

**Comment by coresh** [comment]
> @ihor-sviziev Thanks for your reply. You are right, I finally found this problem when I struggled with it for two days. Cause I have installed Phalcon4 which needs php-psr library. I have removed it then everything comes back. Thanks again.

```
sudo dnf -y remove php74-php-pecl-psr-devel.x86_64
```

Also helped to fix the issue:

```
Cannot instantiate interface PsrExt\Log\LoggerInterface#0 /app/ufia/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
```

Thank you
