### ISSUE TITLE
Unable to filter using sort order at view a job page at admin eng.

### ISSUE THREAD

**Issue by Sarvesh0639** [magento/magento2#35016]
Magento version : 2.3.2
-Mysql version :5.6
-Mode :QA/Developer/Production
-Commit id : 92b1fb1

##Description
Unable to filter using"Sort Order" at view a job page at Admin end

Step to Reproduce
Login to Admin page
Navigate to job board>>Manage jobs
Try to Sort order using order data 

##Expected result
-job should be successfully filter using Sort order

##Actual result
-job is  not be opened using sort order filter

![Screenshot_2022-01-25-13-34-32-54](https://user-images.githubusercontent.com/98222190/150937460-ae499ff4-d6e8-4752-8242-89bf70fb9ed4.png)

**Comment by engcom-November** [comment]
Hi @Sarvesh0639 
Job board is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
