### ISSUE TITLE
Cart Price rule forces Free Shipping to "No" even if "-- Please Select --" was saved

### ISSUE THREAD

**Issue by nkajic** [magento/magento2#35013]
### Preconditions (*)

1. Clean Magento 2.4.3-p1 install or 2.4-develop branch

### Steps to reproduce (*)

1. Admin > Marketing > Cart price rule > Add new rule
2. Fill general fields
3. Leave Actions > Free Shipping to default "-- Please select --" option
4. Save rule

### Expected result (*)

1. Open previously generated rule Free Shipping should be "-- Please select --"

### Actual result (*)

1. Open previously generated rule Free Shipping is "No" 

*This bug does not allow free shipping method and leave checkout without shipping options for some customers making it impossible to complete checkout.*

Reproduced on 2.4-develop branch
https://youtu.be/kB-laiPWax4

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nkajic** [comment]
@magento give me 2.4-develop instance

**Comment by nkajic** [comment]
Reproduced on 2.4-develop branch
https://youtu.be/kB-laiPWax4

**Comment by engcom-Hotel** [comment]
Engcom team verification is in progress.

**Comment by abdulsamadabbasi786** [comment]
Any update on this issue? I can reproduce it on 2.4.3 p1.

**Comment by nkajic** [comment]
Hi @krishprakash
Do you maybe have some additional information you can share with us?

**Comment by rogerdz** [comment]
@nkajic  I think Free Shipping is "No" or '-- Please select --' doesn't matter.
The Free Shipping value is stored in the simple_free_shipping column of the salesrule table.
simple_free_shipping is handled Magento\SalesRule\Model\Validator\Calculator, function processFreeShipping https://i.imgur.com/HBOUOpV.png. With value '' or 0 the result is the same.
Please provide more of your case
