### ISSUE TITLE
Exported file not getting

### ISSUE THREAD

**Issue by gulfclickdxb** [magento/magento2#35020]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-November** [comment]
Hi @gulfclickdxb ,
Thank you for reporting and collaboration. However provided description is not enough for us to reproduce the issue. Kindly check the behavior on Magento2.4-develop branch and elaborate the steps to reproduce if you are still facing issues.
Thank you.

**Comment by engcom-Lima** [comment]
Dear @gulfclickdxb,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
