### ISSUE TITLE
Product Quantity is not updating on first time save. Happening from Magento 2.3.6 version.

### ISSUE THREAD

**Issue by ganesh102** [magento/magento2#35026]
### Preconditions (*)

1. The same plugin is working till Magento 2.3.5.
2. It is not working from Magento 2.3.6 to 2.4.3 (the latest)

### Steps to reproduce (*)

Steps:
1. Install the extension https://marketplace.magento.com/dart-productkeys.html
2. Go to Dart -> Product Keys List ->
3. Create a new key with Key Pool - Ex: "General Pool"
4. Go to Catalog -> Product
5. Create a new product
6. Under the tab Product Keys Set Key Pool Name as -- "General Pool"
7. Save the product

### Expected result (*)

The product qty must be updated according to Keypool's "General Pool" availability.

### Actual result (*)

1. The Quantity is not updating.
2. Now, Click the Save button again and you can see the Quantity updates according to the Number of Keys in Keypool.
3. This Video can explain better. https://screenrec.com/share/7zBW14EM5x
4. This is the code written on our plugin. http://dartinnovations.net/clients/setProductQty.jpg
5. The same code working till Magento 2.3.5 version.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] We can't submit the plugin with our updates due to this issue. We tried many work arounds but it looks like a bug in core.

**Comment by engcom-November** [comment]
Hi @ganesh102 ,
Product Key Delivery is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Comment by ganesh102** [comment]
Product Key Delivery is a plugin of ours. We are the owners. The problem here is updating the quantity on runtime using the code and method provided by Magento core is not working. If you see the video the Save button only updates on 2nd time click not at first time. So there is some issue with the core on that area.
Could you please still investigate and assist?
