### ISSUE TITLE
Klarna is not shown on checkout

### ISSUE THREAD

**Issue by in-session** [magento/magento2#35034]
### Preconditions (*)

1. Magento 2.4.3-p1
2. Merchant country: Multistore + one currency
3. Add testdrive api data

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. No payment option avaiable in checkout

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by in-session** [comment]
@magento give me 2.4.3-p1 instance

**Comment by in-session** [comment]
![FireShot Capture 006 - Configuration _ Settings _ Stores _ Magento Admin](https://user-images.githubusercontent.com/16542619/151609104-90565558-b6c9-42c9-9c7f-3a81666c7c1e.png)
![Screenshot 2022-01-28 202512](https://user-images.githubusercontent.com/16542619/151609143-6b4ece46-7f62-480b-a84b-4d0e89de6eeb.png)
![Screenshot 2022-01-28 202616](https://user-images.githubusercontent.com/16542619/151609164-9c651d53-29e0-4e05-b4a4-9da0a2598a8e.png)

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.3-p1 instance

**Comment by engcom-Delta** [comment]
Hi @in-session ,
Thank you for reporting the issue. We have verified the issue on Magento 2.4.3 P1 and the issue is reproducible.
Hence confirming the issue.

**Steps Performed:**

1. Install Magento 2.4.3-p1
2. Go to – Stores>Configration>Sales>Payment methods>Klarna (Configure it)
3. Try ordering a product from frontend

Result – Not getting an option to pay from Klarna.
<img width="758" alt="Screenshot 2022-03-12 at 9 43 02 AM" src="https://user-images.githubusercontent.com/51681379/158003258-173f7871-b7e3-4d37-94b6-6ab794a51338.png">

**Comment by engcom-Hotel** [comment]
Hello @engcom-Delta,

As per the discussion in the triage call, we need to reconfirm this issue.

Thanks

**Comment by engcom-Delta** [comment]
Hi @in-session ,
We tried to reproduce the issue on Magento 2.4.3.p1 branch , it works fine , During checkout we could see that Klarna payments displayed. Please find the screenshots for reference.
<img width="1440" alt="Screenshot 2022-03-24 at 3 01 26 PM" src="https://user-images.githubusercontent.com/51681379/159941441-d17b659d-a97a-4a8b-bba5-6595e662f1b0.png">
<img width="1440" alt="Screenshot 2022-03-24 at 8 03 31 PM" src="https://user-images.githubusercontent.com/51681379/159941481-c14fab2d-dbf9-45be-98ed-18aba565b1a4.png">

**Comment by Shockwave2k** [comment]
Hi,

we are currently facing the same/similar issue on Magento 2.4.5 with klarna/m2-klarna 1.1.3

Default Config (Klarna is available)
(Same for Main Website Config)
![available](https://user-images.githubusercontent.com/7497733/189604827-05473911-7679-4636-b9c9-fa1feb4343b6.png)

Store Config (Klarna is NOT available)
![not-available](https://user-images.githubusercontent.com/7497733/189604841-d21c0ea4-9173-4ab2-8dbc-76ca928b9748.png)

Store configuration
![stores-view](https://user-images.githubusercontent.com/7497733/189604855-826cfd41-d091-43d5-90e9-44484a412026.png)

If any further information is needed or i should create a new issue please let me know.

**Comment by vipin12117** [comment]
Any solution yet ? We are facing same issues from 2 months and continuing to Klarna support but they not helping. Not sure why these people not care own major bugs.

**Comment by engcom-Bravo** [comment]
Hi @in-session @vipin12117 ,

Thanks for your contribution.


<img width="826" alt="Screenshot 2023-03-13 at 12 51 54 PM" src="https://user-images.githubusercontent.com/51680745/224693987-f54fa97d-9de2-4526-bfdf-fe6eb5fe3521.png">


“Klarna” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
