### ISSUE TITLE
Orders tab of Magento is not working

### ISSUE THREAD

**Issue by snadiminty** [magento/magento2#35044]
Hi, 

My Magento version is ver. 2.3.5-p1. I am unable to access the orders data.

Have been trying to get this resolved for a month with IT, but does not work. Magento is working alright for others in my company.
The error says "Something went wrong with processing the default view and we have restored the filter to its original state." and keeps buffering.

Please check the below screenshot :

![image](https://user-images.githubusercontent.com/98805096/151941443-ced26073-939d-41db-b29d-bc68e093af2d.png)

Do let me know on how I can get this up and running!

**Comment by engcom-Hotel** [comment]
Hello @snadiminty,

We have tried to reproduce the issue in Magento 2.4-develop by accessing the orders page, but we are unable to do so. Please have a look at the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/151956589-1c631be4-736b-4945-831b-fa21c31093da.png)

It seems some issues related to customization. Please check the logs.

Thanks

**Comment by Sental** [comment]
@snadiminty  it's likely the entry for in the ui_bookmark table for your user id with the namespace of sales_order_grid with the identifier of current has been corrupted. Have your dev remove the row and it should work consistently.

I've had this happen before but never been able to find consistent steps to reproduce. Usually something to do with grid filters.

**Comment by engcom-Hotel** [comment]
Dear @snadiminty,

We have noticed that this issue has not been updated by you for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
