### ISSUE TITLE
add /vendor/ folder to repository & add /vendor/artifacts/ for commercial packages

### ISSUE THREAD

**Issue by mikebranderhorst** [magento/magento2#3505]
In .gitignore:

```
/vendor
!/vendor/.htaccess
```

Should be:

```
/vendor/*
!/vendor/.htaccess
```

This way /vendor/.htaccess is added to (private) repository (and with deployment the folder is created).

Maybe also add the third line (to make adding commercial packages possible by artifact)
https://getcomposer.org/doc/05-repositories.md#artifact

```
/vendor/*
!/vendor/.htaccess
!/vendor/artifacts/.htaccess
# uncomment when using a private repository and want to
# add artifact (commercial) packages to the repository
#!/vendor/artifacts/
```

Combined with an addition in composer.json
(composer config repositories.artifacts artifact vendor/artifacts)

```
    "repositories": {
        "artifacts": {
            "type": "artifact",
            "url": "vendor/artifacts"
        }
    },
```

And to keep the folder adding the file /vendor/artifacts/.htaccess

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/add-vendor-folder-to-repository-amp-add-vendor-artifacts-for/idi-p/45316).
