### ISSUE TITLE
Free shiping coupon usage is not tracked

### ISSUE THREAD

**Issue by Fel1xx** [magento/magento2#3506]
Hi.

Found an issue that usage of free shipping coupons is not tracked correctly. Steps to reproduce:
1. Create a cart rule with "Free Shipping" in actions and Uses per Coupon and Uses per Customer set to 1.
2. Make sure that discount amount is set to 0.
3. Generate some coupon code
4. Place an order with generated coupon on store front.
5. Try to apply this coupon again and it will be applied (it shouldn't!).

Tested on 2.0.2. Seems it comes from https://github.com/magento/magento2/blob/develop/app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php#L60. It bypasses coupon usage processing with `$order->getDiscountAmount() == 0` if no discount amount was applied but we just allow free shipping, not some particular discount.

**Comment by olysenko** [comment]
Hi @Fel1xx ,
thank you for reporting this issue, internal ticket was created MAGETWO-55342

**Comment by sdzhepa** [comment]
@Fel1xx 
 Fix for this issue was delivered to develop branch. Pls feel free to check it in develop and reopen if need
- Fix for Magento 2.1 will be delivered later in scope of internal ticket 'MAGETWO-59243'
- Fix for Magento 2.0 will be delivered later in scope of internal ticket 'MAGETWO-59245'
