### ISSUE TITLE
Static attribute cannot be updated via \Magento\Eav\Model\Entity\AbstractEntity::saveAttribute

### ISSUE THREAD

**Issue by ameysar** [magento/magento2#35064]
### Preconditions (*)

1. Magento 2.3.6

### Steps to reproduce (*)

1. Create customer (ex. ID = 100500).
2. Create address for customer (ex. ID = 123).
3. Run code
``` 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

/** @var \Magento\Customer\Model\Customer $customer */
$customer = $objectManager->create(\Magento\Customer\Model\Customer::class);
/** @var \Magento\Customer\Model\ResourceModel\Customer $customerResource */
$customerResource = $objectManager->get(\Magento\Customer\Model\ResourceModel\Customer::class);
$customerResource->load($customer, 100500);

$customer->setDefaultBilling(123);
$customerResource->saveAttribute($customer, 'default_billing');
```

### Expected result (*)

1. Customer's billing address updated with address ID.

### Actual result (*)

1. SQL exception appears
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer_entity.value_id' in 'field list', query was: SELECT `customer_entity`.`value_id`, `customer_entity`.`value` FROM `customer_entity` WHERE (attribute_id='?' AND entity_id='?')
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @ameysar,

Thanks for the report and collaboration!

I would like to suggest you to use the customer model as given below:

```
        $customer = $this->customerFactory->create();
        $this->customerResourceModel->load($customer, 1);
        $customer->setDefaultBilling(1);
        $customer->save();
```

Let us know in case of any queries.

Thanks

**Comment by ameysar** [comment]
> Hello @ameysar,
> 
> Thanks for the report and collaboration!
> 
> I would like to suggest you to use the customer model as given below:
> 
> ```
>         $customer = $this->customerFactory->create();
>         $this->customerResourceModel->load($customer, 1);
>         $customer->setDefaultBilling(1);
>         $customer->save();
> ```
> 
> Let us know in case of any queries.
> 
> Thanks

@engcom-Hotel, I've already used workaround, but as for me [\Magento\Eav\Model\Entity\AbstractEntity::saveAttribute](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Eav/Model/Entity/AbstractEntity.php#L1670) should work correclty and should be aware of static attributes.

**Comment by engcom-Hotel** [comment]
Hello @ameysar,

There is one more similar issue https://github.com/magento/magento2/issues/35699, which is confirmed. So marking this issue as a duplicate. Hence closing this issue.

Thanks
