### ISSUE TITLE
Quotation form doesn't send anymore

### ISSUE THREAD

**Issue by joeridewit1** [magento/magento2#35063]
The quotation form on our website doesn't send anymore. The customer can fill in this form but we and the customer doesn't receive any email. We didn't change any email settings. We moved the website last week. Our email still working, ony email from our website we don't receive. See an image in the file with some errors.
![image_2022_02_07T12_44_15_895Z](https://user-images.githubusercontent.com/99193054/152804731-bb54c737-d2a7-4877-aed3-a95fb624bda9.png)

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Dear @joeridewit1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
