### ISSUE TITLE
Sender Name and Sender Mail address are default hostname (username@server) only

### ISSUE THREAD

**Issue by Alisinasyon** [magento/magento2#35074]
### Preconditions (*)

1. Magento 2.4.3 (first install 2.2.*), multilpe site/ scope configuration
2. nginx 1.20.1, PHP 7.4
3. All Mail Sender Names and Sender Emails under "Stores ->Settings ->Configuration ->General ->Store Email Addresses" Configured

### Steps to reproduce (*)

1. Fill and send default contact formular on (sub-) site
2. Receving Mail

### Expected result (*)

1. Received mail has the "Sender Name" that saved in "Store Mail Addresses" in Magento configuration
2. Received mail has the "Sender Email" that saved in "Store Mail Addresses" in Magento configuration

### Actual result (*)

1. Received mail has the default hostname of server where Magento is installed, no Sender Name
2. Received mail has the default hostname of server where Magento is installed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Stuperfied** [comment]
public function setFromAddress($fromAddress, $fromName = null)
    {
        $this->zendMessage->setFrom($fromAddress, $fromName);
        return $this;
    }
    
    I've just had a quick browse, been years since i've worked on this code. It appears the $fromName variable is empty at this point and so picking up the default of void. I'll keep looking into it later but for now it's time to rest.

**Comment by engcom-Delta** [comment]
Hi @Alisinasyon ,
Thank you for reporting an issue , very happy to assist you and Please provide the screenshots for reference .
Hence, added the label 'Needs update'

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 13 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
