### ISSUE TITLE
Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

### ISSUE THREAD

**Issue by nomuprive** [magento/magento2#35079]
> Platform: Magento 2 (V2.4.0) |
Server: Linux Centos

When I run the command below,

    COMPOSER_MEMORY_LIMIT=-1 php bin/magento setup:static-content:deploy -f

I get the error,

> Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

When I run,

    systemctl restart elasticsearch.service

I get the error,

> Failed to restart elasticsearch.service: Unit not found.

And when I run the command,

    systemctl status elasticsearch

I get the error,

> Unit elasticsearch.service could not be found

However, I can see Elasticsearch folder and files in the following path:

> vendor/elasticsearch/elasticsearch

Any suggestions?

Thank you!

**Comment by bjclark13** [comment]
@williambize Are you using username/password for your connection? I wonder if https://github.com/magento/magento2/issues/35083 would be similar to what you are experiencing.

**Comment by williambize** [comment]
@bjclark13 I'm not sure what username and password you're referring to. All I was doing is to upgrade Magento 2.3.7 to 2.4.0 via the composer with SSH. It seems everything is going well expect when I run "php bin/magento setup:static-content:deploy -f"

**Comment by bjclark13** [comment]
Gotcha. I was asking if your Elasticsearch cluster uses authentication with a username and password, but sounds like it does not :)

**Comment by engcom-Hotel** [comment]
Hello @williambize,

The error mentioned in the main description generally occurs when elasticsearch service is not running. But as I can see that you have tried to start the service as well but then the error shows that you do not have elasticsearch installed in your environment.

I request you to please install the elasticsearch and then try to start the service. It may resolved your issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @williambize,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
