### ISSUE TITLE
[Elastic|Open]Search Validation Fails with Special Characters

### ISSUE THREAD

**Issue by bjclark13** [magento/magento2#35083]
### Preconditions (*)

1. Magento 2.3.4
2. Elastic Search 7 on AWS
3. php7.4-fpm Docker image (kubernetes)

### Steps to reproduce (*)

1. Create an elastic search cluster with username/password and the password is similar to `z52tu|N[x2Hp"^@3==X8+XTd#qLCs}w1` 
2. Curl with username/password combination works properly
```
curl -XGET -u 'username:z52tu|N[x2Hp"^@3==X8+XTd#qLCs}w1' 'https://search-xxx.us-east-1.es.amazonaws.com//_search'
```
2. Run `setup:install` command with elastic search configured with that password.

### Expected result (*)

1. Elasticsearch validation should be able to either identify passwords that are not going to work and produce a meaningful error, or be able to properly escape passwords that continue characters that pose a problem.

### Actual result (*)

 Receive similar error:
```
In SearchConfig.php line 81:
                                                                                          
  Could not validate a connection to Elasticsearch. No alive nodes found in your cluster  
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @bjclark13,

Thanks for the report and collaboration!

I hope you have passed `--elasticsearch-enable-auth=true` while running `setup:install` command.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @bjclark13,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
