### ISSUE TITLE
How to disable API methods?

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3508]
I want to disable unused API methods. I tried a lot but I did not find a solution how I can disable them without changing the core code.

Is there a way which I didn't see?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
