### ISSUE TITLE
Unable to increase upload_max_size for magento2

### ISSUE THREAD

**Issue by InfoAmbient** [magento/magento2#35081]
Unable to increase upload_max_size for magento2 even increased upload_max_size in all php.ini present in system . but it still showing 2M upload size only.
![Screenshot from 2022-02-10 20-55-10](https://user-images.githubusercontent.com/29921114/153439325-74b77dca-79bb-4de4-a1e4-5c9d926f344c.png)

**Comment by hostep** [comment]
This isn't a core Magento bug, it sounds like an environmental issue on your side. I would suggest you ask your hosting provider for some help with this.

**Comment by engcom-Hotel** [comment]
Hello @InfoAmbient,

We have tried to make changes in php.ini and make `upload_max_filesize` with 8M. The same configuration is working for us. Please have a look at the below screenshot for reference:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/51681618/153848159-e4f0e273-1050-455c-a22b-0b76dd4729ea.png">

Please try the solution given by @hostep in this [comment](https://github.com/magento/magento2/issues/35081#issuecomment-1036505946) and let us know if this resolves your issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @InfoAmbient,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
