### ISSUE TITLE
Duplicate reCAPTCHA validation breaks checkout success redirect after initial server error response

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#35093]
### Preconditions (*)

1. Magento 2.4.3-p1
1. Enable for Checkout/Placing Order - reCAPTCHA v3 invisible

### Steps to reproduce (*)

1. Trigger a server side error on initial place order press
1. Fix server side error and place order again

### Expected result (*)

1. Order is placed
1. Redirect to success page

### Actual result (*)

1. Order is placed
1. No redirect to success page
1. Cart is cleared

### Diagnosis
This presented with a custom Payment Gateway module, it was triggered by bad AVS validation but I suspect that any server side error will cause this sequence of events.

Main problem is in Magento_ReCaptchaWebapiUi/js/webapiReCaptchaRegistry.js addListener method.  If the token has already been gathered, it simply calls the callback function.  

``{{
addListener: function (id, func) {
    if (this.tokens.hasOwnProperty(id)) {
        func(this.tokens<id>);
    } else {
        this._listeners<id> = func;
    }
}
}}``

In Magento_ReCaptchaCheckout/js/model/place-order-mixin.js this means the payment-information URL gets called with the old token.  

``{{
recaptchaRegistry.addListener('recaptcha-checkout-place-order', function (token) {
    //Add reCaptcha value to place-order request and resolve deferred with the API call results
    payload.xReCaptchaValue = token;
    originalAction(serviceUrl, payload, messageContainer).done(function () {
        recaptchaDeferred.resolve.apply(recaptchaDeferred, arguments);
    }).fail(function () {
        recaptchaDeferred.reject.apply(recaptchaDeferred, arguments);
    });
});
}}``

As far as I am aware, a second validation request with the same token will always fail, so that request fails and rejects, completing the promise.  

Meanwhile, place-order-mixin also triggers another validation which generates a new token.

```
recaptchaRegistry.triggers<'recaptcha-checkout-place-order'>();
```

When that returns it goes back into the callback, that request succeeds and the order is placed.  However, the placeOrder deferred object has already been rejected with the original error.

It's not clear to me why you would ever want to reuse the old token, so I am able to solve this by simply changing the addListener method to this:

``{{
addListener: function (id, func) {
    this._listeners<id> = func;
}
}}``

But I haven't studied the other reCAPTCHA modules enough to know if that will cause issues elsewhere.  Perhaps v2 or checkbox should be handled differently.

Could potentially be solved with different logic in the place-order-mixin as well.

**Comment by nthurston** [comment]
Diff for anyone that needs it.  Not tested much yet, so use at your own risk.  Seems to solve this checkout issue and not cause any other issues with v3 invisible on other forms.

```
diff --git a/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptchaRegistry.js b/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptchaRegistry.js
index ba2f786..119e8e4 100644
--- a/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptchaRegistry.js
+++ b/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptchaRegistry.js
@@ -32,11 +32,7 @@ define([], function () {
          * @param {Function} func - Will be called back with the token
          */
         addListener: function (id, func) {
-            if (this.tokens.hasOwnProperty(id)) {
-                func(this.tokens[id]);
-            } else {
-                this._listeners[id] = func;
-            }
+            this._listeners[id] = func;
         }
     };
 });
```

**Comment by alikhani97** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @nthurston,

Thanks for posting this issue!

We request you to please elaborate below point:

> 1. Trigger a server side error on initial place order press

Thanks

**Comment by nthurston** [comment]
Need to simulate payment gateway denial.  It can be done with Braintree sandbox and order amount between $2000-$3000.  That acts a little differently because of Braintree mixin.  Not sure of the best way to simulate it with magento core code.

**Comment by engcom-Hotel** [comment]
Hello @nthurston,

Thanks for posting the issue!

We have tried to reproduce the issue in the latest stable version of Magento and the issue is reproducible for us. We have followed below steps in order to reproduce the issue:

1. Enable Recaptcha V3 invisible for the store on the checkout/order page.
2. Add a product to the cart.
3. On the checkout page fill in all the required details like CC details for making the order.
4. Stop the server.
5. Click on the `place order` button, it returns the error as follows:
![image](https://user-images.githubusercontent.com/51681618/158596829-707a9905-f604-4781-805b-5fad17bc2d5b.png)

6. Start the server
7. Then again click on the `place order` button, it will not redirect to the order confirmation page and throw the below error:
![image](https://user-images.githubusercontent.com/51681618/158597139-5295b3e1-6077-44b6-a14a-bb4bd0d701d3.png)

8. But the order is placed. Please have a look at the below screenshot:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/51681618/158597265-e969aa3d-543c-4f72-a041-9fcba92bc9b5.png">

Hence confirming the issue.

Thanks

**Comment by Calvin495** [comment]
Is there any potential fix that is officially released for this issue?

**Comment by Calvin495** [comment]
the solution that @nthurston suggested is not working for us.

**Comment by nthurston** [comment]
Can someone link the PR for this?
As a note, I've confirmed the issue on 2.4.4-p1 so it is still not fixed there.

**Comment by engcom-Hotel** [comment]
Hello @nthurston,

I think you are looking for the commits related to the fix. For this please refer the below link:

https://github.com/search?q=org%3Amagento+AC-2642&type=commits

Thanks

**Comment by jmonrove** [comment]
Recaptcha V3 is causing issues on my store as well when adding a bundled product to the cart, seems like the promise is not triggered and then it hands and resends, ends up doubling up the quantity in the cart, as soon as I disabled Recaptcha V3  on the frontend the problem went away....

**Comment by aveshnaik007** [comment]
I am getting this issue on Magento 2.4.6-p9 "ReCaptcha validation failed, please try again"
