### ISSUE TITLE
Admin user role performance issue

### ISSUE THREAD

**Issue by ageffray** [magento/magento2#35107]
### Preconditions (*)
1. Magento 2.4.3-p1
2. PHP 7.4.26
3. MySQL 8.0.26

### Steps to reproduce (*)
On User module in app/code/Magento/User/Model/User.php for method getRole() when you call it from admin user model it reloads every role from getRoles() then use ->load() on each one

### Expected result (*)
don't reload every roles

### Actual result (*)
Roles are loaded and cause performance issue on database with lot of data 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @ageffray,

We have tried to reproduce the issue in Magento 2.4-develop branch by accessing this endpoint `admin/customer/index/index/`. We have added the breakpoint, to check whether it is calling `->load` method.

But for us, it is not reaching there. Please let us know if we need to check it on another page.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @ageffray,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
