### ISSUE TITLE
i18n: If you have questions about your order, you can email us at...

### ISSUE THREAD

**Issue by iw0der** [magento/magento2#3510]
Hi Guys,
I have a strange language problem... in Italian order confirmation messages, a text appears in English even though it was set to its Italian translation!

Perhaps the i18n language files have some problems with double quotes?

./vendor/magento/theme-frontend-luma/i18n/it_IT.csv:
`"If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>.","Se hai domande sul tuo ordine, puoi inviare una email a <a href=""mailto:%store_email"">%store_email</a>."`

./vendor/magento/module-sales/i18n/it_IT.csv:
`"If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>","Se hai domande sul tuo ordine, puoi inviare una email a <a href=""mailto:%store_email"">%store_email</a>"`

Now despite these two files; of MG CE v2.0.2, the messages arrive with this sentence yet in English :-(

Like this:

![order-ita-eng](https://cloud.githubusercontent.com/assets/16407046/13250124/782d74ba-da28-11e5-995c-f43882e0ae5c.JPG)

Any ideas or suggestions?

Thanks,
A.

**Comment by iw0der** [comment]
I see that the same phrase is presented several times, with and without the end dot... the issue may be that?

> 'If you have questions about your order, you can email us at <a href="mailto:%store_email">%store_email</a>**.**'

But `magento i18n::collect-phrases` report only the one with the dot on "lumia theme":

> "If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>","If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>",module,Magento_Sales
> "If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>.","If you have questions about your order, you can email us at <a href=""mailto:%store_email"">%store_email</a>.",theme,frontend/Magento/luma

Ok, I tried adding one without the dot but nothing happens (in fact I did not do a complete test complete with a cache flush, etc.)

73s,
A.

**Comment by mazhalai** [comment]
@iw0der what version of Magento are you using?

**Comment by iw0der** [comment]
@mazhalai Magento 2.0.2 CE

**Comment by thomvanderboon** [comment]
I have replicated your problem on the github development branche (with the Magento Crowdin Translation file), but it works correctly on the 2.0.2 branche (with my own translation file).

Do you use the Magento Crowdin translation file?

**Comment by iw0der** [comment]
Yes,
I use even those;  I refer to individual files because the single file is unusable.

73s,
A.

**Comment by fulviocazzanti83** [comment]
How you are add italian languages ?

**Comment by veloraven** [comment]
Internal ticket MAGETWO-59942

**Comment by magento-engcom-team** [comment]
@iw0der, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
