### ISSUE TITLE
Improve import/export validation error reporting

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#35106]
### Summary (*)

Import/export module code can be used in custom CLI scripts to import data. Then `ProcessingErrorAggregatorInterface` can be used to get errors that were caught during the import, for example, to show output to the user, or to log the output.

There is a behavior that looks like a small bug, that causes problems in a specific use case - when `is_unique` error is triggered in the script that supposes to provide detailed error output.

### Examples (*)

`is_unique` attribute validation inside `\Magento\CatalogImportExport\Model\Import\Product\Validator::isAttributeValid` method  doesn't set invalid attribute code when it returns `false`.

It doesn't cause an issue with import itself but makes handling error output harder - later in the stack when validation errors are accessed using the `getAllErrors` method from the `ProcessingErrorAggregatorInterface` interface, the `column_name` key is empty, so it's not possible to provide information on which attribute triggered the unique error "Duplicated unique attribute".

Some other cases which result with returning `false` are handled properly - they set `$valid` variable to `false` and at the end of the method there is a condition that sets `setInvalidAttribute` when `$valid` is false. 

Problem with `is_unique` occurs as it uses early return instead of setting `$valid` variable.

### Proposed solution

The proposed solution is to add a call to the `setInvalidAttribute` method when an error related to `is_unique` occurs.

This code:

```
        if ($valid && !empty($attrParams['is_unique'])) {
            if (isset($this->_uniqueAttributes[$attrCode][$rowData[$attrCode]])
                && ($this->_uniqueAttributes[$attrCode][$rowData[$attrCode]] != $rowData[Product::COL_SKU])) {
                $this->_addMessages([RowValidatorInterface::ERROR_DUPLICATE_UNIQUE_ATTRIBUTE]);
                return false;
            }
            $this->_uniqueAttributes[$attrCode][$rowData[$attrCode]] = $rowData[Product::COL_SKU];
        }
```

Can be changed to:

```
        if ($valid && !empty($attrParams['is_unique'])) {
            if (isset($this->_uniqueAttributes[$attrCode][$rowData[$attrCode]])
                && ($this->_uniqueAttributes[$attrCode][$rowData[$attrCode]] != $rowData[Product::COL_SKU])) {
                $this->_addMessages([RowValidatorInterface::ERROR_DUPLICATE_UNIQUE_ATTRIBUTE]);
                $this->setInvalidAttribute($attrCode);
                return false;
            }
            $this->_uniqueAttributes[$attrCode][$rowData[$attrCode]] = $rowData[Product::COL_SKU];
        }
```

Another approach would be about removing early return and setting `$valid` to `false`.

The affected file:

https://github.com/magento/magento2/blob/2d446475953e907c9844d493857d172bc9956bd8/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator.php#L257-L264

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @wojtekn,

Thanks for reporting the issue. 

We are analyzing it at our end. But it will help us better to understand it more accurately if you can provide us some steps with some screenshots of where exactly you are getting this issue so that we can replicate the issue with the given steps at our end and could provide a solution in a better way.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @wojtekn,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
