### ISSUE TITLE
New and Edit User Role is not working correctly

### ISSUE THREAD

**Issue by pansys** [magento/magento2#3511]
I have installed Magento 2.0.2 and everything looked fine. I was able to create new User and New User Role. But since yesterday creating a new role creates a new record but role name is empty. Editing the role creates a duplicate record too with role name empty for both actual and duplicate records. 

Create new user not creating any user record.

**Comment by sevos1984** [comment]
Not reproducible, need more detailed steps

**Comment by pansys** [comment]
Permission and indexing issue. Nothing to do with Magento.
