### ISSUE TITLE
Duplicate primary key error on catalog_url_rewrite_product_category when saving change to category URL key

### ISSUE THREAD

**Issue by aarontalcott** [magento/magento2#35114]
### Preconditions (*)

1. 2.4.3
2. At least 2 stores
3. Catalog > Search Engine Optimization > Generate "category/product" URL Rewrites = Yes
4. Category A that exists in all stores
4. At least one Product A that is assigned to only a subset of the stores 
5. At least one Product B that is assigned to all stores
6. Product A and Product B assigned to Category A
7. Sufficient number of products in sufficient number of stores that more than 10k URL rewrites are generated for products in the Category A

### Steps to reproduce (*)

1. Assign or unassign any product to Category A using any of the available methods in the category edit page and save changes.
2. Re-edit the category update the category URL key, save changes.

### Expected result (*)

1. Category changes saved without errors.

### Actual result (*)

1. Category changes not saved. "Something went wrong while saving the category" error appears.

We encountered this error while saving scheduled updates on categories (a Commerce feature) but eventually found it also affects saving updates to the category URL key. 

Then when the URL key is updated the bunch replacing (10k per bunch) in `Magento\CatalogUrlRewrite\Model\UrlRewriteBunchReplacer::doBunchReplace` results in a potential mismatch between the rewrites that are replaced in url_rewrite and those that Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage::afterReplace finds as having been replaced. As a result, the latter attempts to add rows to catalog_url_rewrite_product_category that already exist, resulting in a duplicate primary key error. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @aarontalcott,

Thanks for posting the issue!

We have started checking this issue. But can you please provide some screenshots for the below steps:

> * At least 2 stores
> * Catalog > Search Engine Optimization > Generate "category/product" URL Rewrites = Yes
> * Category A that exists in all stores
> * At least one Product A that is assigned to only a subset of the stores
> * At least one Product B that is assigned to all stores
> * Product A and Product B assigned to Category A

Thanks

**Comment by engcom-Hotel** [comment]
Dear @aarontalcott,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
