### ISSUE TITLE
Magento 2 compatible with php 8.1

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35121]
Problem 1
    - Root composer.json requires laminas/laminas-code ^3.5.1 -> satisfiable by laminas/laminas-code[3.5.1].
    - laminas/laminas-code 3.5.1 requires php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires laminas/laminas-escaper 2.7.0 -> satisfiable by laminas/laminas-escaper[2.7.0].
    - laminas/laminas-escaper 2.7.0 requires php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires magento/composer 1.6.0 -> satisfiable by magento/composer[1.6.0].
    - magento/composer 1.6.0 requires php ~7.3.0||~7.4.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires pelago/emogrifier ^5.0.0 -> satisfiable by pelago/emogrifier[v5.0.0, v5.0.1].
    - pelago/emogrifier[v5.0.0, ..., v5.0.1] require php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 5
    - laminas/laminas-feed[2.13.0, ..., 2.14.1] require php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
    - laminas/laminas-feed[2.15.0, ..., 2.16.0] require laminas/laminas-escaper ^2.9 -> found laminas/laminas-escaper[2.9.0] but it conflicts with your root composer.json require (2.7.0).
    - Root composer.json requires laminas/laminas-feed ^2.13.0 -> satisfiable by laminas/laminas-feed[2.13.0, ..., 2.16.0].

**Comment by Sanjay-100** [comment]
Summary of the issue  - magneto 2 work with php 8.1 version
Information on your environment  windows  xampp  php 8.1.1
Steps to reproduce  -> clone magento from 2.4 from  https://magento.com/tech-resources/download
 Expected and actual results  - with php version need to be run,

**Comment by hostep** [comment]
@Sanjay-100: have you read [the system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)? The latest version of Magento (version 2.4.3-p1) currently only supports PHP 7.4

The next version (version 2.4.4, to be [released in a couple of weeks](https://devdocs.magento.com/release/index.html)), will support PHP 8.1

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

The current stable version does not support PHP 8.x version. Please go through with the below link:

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

Hence closing this issue.

Thanks
