### ISSUE TITLE
Backup housekeeping missing

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#35120]
### Preconditions (*)
1. OS 2.4.3-p1

### Steps to reproduce (*)
1. Stores > Configuration > System > Backup Settings
2. Enable Scheduled backups

### Expected result (*)
1. Option to limit retained backups

### Actual result (*)
1. No option to limit retained backups

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

Any system that does automated scheduled backup must provide a means to specify a retention period for those backups. Failing to do so means disks will eventually fill and bring down the application. Magento used to have this - why was it removed?

**Comment by engcom-Delta** [comment]
Hi @adamlavery ,
Thank you for reporting an issue and We could not find the expected option in UI and it would be great if you can provide screenshot for reference for expected results.
Hence request to review the steps provided . added the label 'Needs Update'.

Steps followed:
1. Stores > Configuration > System > Backup Settings
2. Advanced --> System --> Backup Settings
3. Enable backups to 'Yes' option
4. Enable Scheduled Backup field to 'Yes'

Actual results:
No option to limit retained backups
<img width="1440" alt="Screenshot 2022-02-21 at 2 36 35 PM" src="https://user-images.githubusercontent.com/51681379/154922987-582e0bfc-b238-4773-a79a-3514bafbd1bc.png">

**Comment by engcom-Delta** [comment]
Hi @adamlavery ,
Thank you for confirming and We could find out issue is reproducible on Magneto 2.4 Develop.
Hence marking the issue confirmed.

Steps followed:

Stores > Configuration > System > Backup Settings
Advanced --> System --> Backup Settings
Enable backups to 'Yes' option
Enable Scheduled Backup field to 'Yes'
**Actual results:**
No option to limit retained backups

<img width="1440" alt="Screenshot 2022-02-21 at 2 36 35 PM" src="https://user-images.githubusercontent.com/51681379/155273517-ac03f356-f2eb-41a9-9a00-f73798f69bd0.png">

**Expected results**
Option to limit retained backups

**Comment by engcom-Delta** [comment]
As per confirmation from @engcom-Lima , Please refer the [documentation](https://docs.magento.com/user-guide/system/backups.html)
the documentation as of Magento v2.3.0, backup features have been deprecated.

Hence issues has been closed.
