### ISSUE TITLE
The store that was requested wasn't found on creditmemo grid page

### ISSUE THREAD

**Issue by faradey** [magento/magento2#35122]
### Preconditions (*)

1. Magento 2.4.3
2. PHP 7.4

### Steps to reproduce (*)

1. Create website, store, and Store View with numbers at the beginning of the name. For example 123Test
2. Place orders for this store.
3. Create creditmemo for the order.
4. Go to creditmemo grid page

### Expected result (*)

1. Must be displayed creditmemos

### Actual result (*)

1. There is an error on the page 
> The store that was requested wasn't found. Verify the store and try again.
> Exception in /var/www/html/vendor/magento/module-store/Model/StoreRepository.php:75
2. 
![Credit Memos _ Operations _ Sales _ Magento Admin](https://user-images.githubusercontent.com/61543096/154799593-5d927c7c-d745-49c8-a813-c0185982cf5e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ *] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by faradey** [comment]
I found this bug location vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php
`public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                $currencyCode = isset($item['base_currency_code']) ? $item['base_currency_code'] : null;
                if (!$currencyCode) {
                    $storeId = isset($item['store_id']) && **(int)$item['store_id']** !== 0 ? $item['store_id'] :
                        $this->context->getFilterParam('store_id', Store::DEFAULT_STORE_ID);
                    $store = $this->storeManager->getStore(
                        $storeId
                    );
                    $currencyCode = $store->getBaseCurrency()->getCurrencyCode();
                }
                $basePurchaseCurrency = $this->currency->load($currencyCode);
                $item[$this->getData('name')] = $basePurchaseCurrency
                    ->format($item[$this->getData('name')], [], false);
            }
        }

        return $dataSource;
    }`

if store_id has name such "123Test <br/>&nbsp;&nbsp;&nbsp; 123Test <br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 123Test <br/>" then (int)$item['store_id'] equals 123.
Then function 
`$store = $this->storeManager->getStore(
                        $storeId
                    );`
returns exception because the store with id = "123Test <br/>&nbsp;&nbsp;&nbsp; 123Test <br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 123Test <br/>" is not exists

**Comment by engcom-November** [comment]
hi @faradey


Thank you for reporting the issue.

We verified the issue on Magento Commerce 2.4-develop branch and the issue is reproducible.

Steps performed:

Create website, store, and Store View with numbers at the beginning of the name. For example 123Test
Place orders for this store.
Create creditmemo for the order.
Go to creditmemo grid page


result:
There is an error on the page as shown in screenshot

![image](https://user-images.githubusercontent.com/60198231/154964148-4c5ffa71-bc91-473d-a21a-fb30f91cf763.png)


Based on the above observation, confirming the issue.

**Comment by engcom-Alfa** [comment]
Hi @faradey ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento-commerce/magento2ce/commit/e71f1543555d7740b5132f18c192f61c02857551).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
