### ISSUE TITLE
Upgrade 2.3.7 to 2.4.3-p1: Unable to apply data patch Magento\PageBuilder\Setup\Patch\Data\UpgradePageBuilderStripStyles for module Magento_PageBuilder

### ISSUE THREAD

**Issue by winds1983** [magento/magento2#35136]
Unable to apply data patch Magento\PageBuilder\Setup\Patch\Data\UpgradePageBuilderStripStyles for module Magento_PageBuilder. Original exception message: Type Error occurred when creating object: Magento\PageBuilder\Model\Dom\Element, Argument 2 passed to Magento\PageBuilder\Model\Dom\Element::__construct() must be an instance of Gt\Dom\Element, null given, called in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

### Preconditions (*)
Run command:
```
php bin/magento setup:upgrade
```

### Steps to reproduce (*)
Run command:
```
php bin/magento setup:upgrade
```

### Actual result (*)
It will throw below issues:
Unable to apply data patch Magento\PageBuilder\Setup\Patch\Data\UpgradePageBuilderStripStyles for module Magento_PageBuilder. Original exception message: Type Error occurred when creating object: Magento\PageBuilder\Model\Dom\Element, Argument 2 passed to Magento\PageBuilder\Model\Dom\Element::__construct() must be an instance of Gt\Dom\Element, null given, called in /usr/share/nginx/html/demo.hp.php9.cc/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

**Comment by engcom-Delta** [comment]
Hi @winds1983 ,
Thank you for raising an issue, We tried to reproduce the issue on Magento 2.4 Develop , We found that issue is not reproducible after running the command.

Hence , request to elaborate more on pre-conditions.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
