### ISSUE TITLE
Magento 2 links in admin/backend don't work

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#3514]
All the links in the left admin bar don't work. They all end on #3513 
But the Icons are shown. 

The following solution doesn't help in my case:
https://www.envisionecommerce.com/magento-2-admin-links-not-working-on-localhost-easy-solution/

**Comment by mazhalai** [comment]
@flipflap are there any browser errors? What server are you on?

**Comment by flipflap** [comment]
I tried all browsers. All links on the left icons goes to the same url:
admin/admin/dashboard/index/key/6561974a85c481df22c6423cb57656edcb68974725c37a7e5b8bd41b85ee6f2b/#

**Comment by flipflap** [comment]
![error](https://cloud.githubusercontent.com/assets/6672673/13427047/b90f9baa-dfb1-11e5-87d7-68b43ae2f1c4.png)

It ist full of script errors.

**Comment by mazhalai** [comment]
Please run `bin/magento setup:static-content:deploy` on command line.

**Comment by cyberbloke** [comment]
Having same issue - ran bin/magento setup:static-content:deploy --- still the admin dashboard as well as store front broken...

**Comment by flipflap** [comment]
For me the Magento installer didn't work. It seems full of bugs.

But my hosters has a tool in cpanel called installatron. Using that tool I could install Magento in 10 minutes. It also works with sample data. While Magento Installer stops at 90%.

**Comment by mazhalai** [comment]
@cyberbloke can you check file permissions especially for `pub` folder? Please see [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and [this](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)

@flipflap please check if your `max_execution_time` is set to the recommended [18000](https://github.com/magento/magento2/blob/develop/.htaccess#L41)

**Comment by flipflap** [comment]
@mazhalai max_execution_time is already at 18000. I really tried everithing, it just don't work. I recommend to use installatron until this things are fixed.

**Comment by mazhalai** [comment]
@flipflap what is your configuration like so that we can reproduce this issue.

**Comment by flipflap** [comment]
@mazhalai thanks, it is ok now as I installed by installatron. Aniway, here is my PHP setting:
![php](https://cloud.githubusercontent.com/assets/6672673/13989343/38fbacb8-f110-11e5-92b6-66c307e7ed60.jpg)

**Comment by mazhalai** [comment]
@flipflap what OS and what Webserver?

**Comment by flipflap** [comment]
Here is my server information. Interesting, it shows me a lower PHP Version here 5.5.3 and not 5.6.
![php](https://cloud.githubusercontent.com/assets/6672673/13990588/3904f43a-f115-11e5-92fc-da0f086d0091.jpg)

**Comment by mazhalai** [comment]
@flipflap but this does not show what OS and what webserver you have.

**Comment by flipflap** [comment]
Sorry, I took the wrong picture :-(
![server](https://cloud.githubusercontent.com/assets/6672673/13992293/d368a610-f11b-11e5-8179-6b5136dfde48.jpg)

**Comment by flipflap** [comment]
Sorry, I took the wrong picture :-(
![server](https://cloud.githubusercontent.com/assets/6672673/13992330/f1b6711a-f11b-11e5-85ab-78d3e1dbf573.jpg)

**Comment by medma-infomatix** [comment]
Hi I having solution of the above problem.

open the terminal and navigate to magento web root

 $ cd /var/www/html/magento2
Step 1.

$ php bin/magento setup:static-content:deploy
Step 2.

$ php bin/magento indexer:reindex
Step 3.

make sure apache “rewrite_module” is enable and then restart the server

Step 4.

$ chown -R www-data:www-data /var/www/html/magento2 
Step 5.

$ chmod -R 777 /var/www/html/magento2 
Step 6.

delete cache folder under var/cache

http://gotechnies.com/css-javascript-files-loading-magento-2-installation/

**Comment by mazhalai** [comment]
@flipflap do you still have this issue?

**Comment by flipflap** [comment]
Thanks for your feedbacks.
I deleted Files and DB and setup all again. Now I don't have that problem anymore.

**Comment by manojind** [comment]
2
down vote
accepted
I have find the simple solution: Open the file di.xml at the location:

app/etc/di.xml
Go to the line number 574 line:
Older line:
Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink
Replace it with (New line)
Magento\Framework\App\View\Asset\MaterializationStrategy\copy

**Comment by moytho** [comment]
@manojind  solution fixed my errors too. Thank you.
