### ISSUE TITLE
Synonyms don't work correctly when using "Minimum Terms to Match" using Elasticsearch

### ISSUE THREAD

**Issue by Quazz** [magento/magento2#35141]
### Preconditions (*)

1. Magento 2.4.3
2. Elasticsearch 7

### Steps to reproduce (*)

1. Define synonym group (eg notebook,laptop)
2. Have product with name "New Laptop" and another product with name "New Laptop Notebook"
3. Use Elastichsearch 7 as search engine
4.  Set "Minimum Terms to Match" to a value (eg 2 or 75% or 2<75%)
5. Search in frontend on "notebook" or "laptop"

### Expected result (*)

1. Both products show up in search results

### Actual result (*)

1. Only products that have ALL synonyms (as opposed to ANY) within their searchable terms are listed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

If you have a larger synyonym group (eg 3+ words), the odds of matching are near 0 and thus produces undesirable results on frontend. The "workaround" is to either not use synonyms or to not use "Minimum Terms to Match", both workarounds offering subpar search experience.

**Comment by engcom-Delta** [comment]
Hi @Quazz,
We tried to reproduce the issue but it is not reproducible on Magento 2.4 Develop branch with latest code.
Followed below steps:
1. Define synonym group (eg notebook,laptop)
<img width="1440" alt="Screenshot 2022-02-28 at 6 21 01 PM" src="https://user-images.githubusercontent.com/51681379/155988477-22a88b12-ce27-4c26-88f6-9e8c4e5f8d6d.png">

2. Have product with name "New Laptop" and another product with name "New Laptop Notebook"
<img width="1440" alt="Screenshot 2022-02-28 at 6 40 00 PM" src="https://user-images.githubusercontent.com/51681379/155988955-8cd59e4c-ed46-4cf0-a015-a7efab65b0b1.png">

3. Use Elastichsearch 7 as search engine
<img width="1440" alt="Screenshot 2022-02-28 at 6 41 24 PM" src="https://user-images.githubusercontent.com/51681379/155989077-6a90427c-028c-41f3-977c-3c102bd501ef.png">

4. Set "Minimum Terms to Match" to a value (eg 2 or 75% or 2<75%)
<img width="1440" alt="Screenshot 2022-02-28 at 6 43 50 PM" src="https://user-images.githubusercontent.com/51681379/155989385-825dbb6b-1179-4a39-8d87-8497391883b6.png">

5. Search in frontend on "notebook" or "laptop"
<img width="1440" alt="Screenshot 2022-02-28 at 6 45 03 PM" src="https://user-images.githubusercontent.com/51681379/155989817-a611495e-f819-4e02-8331-910910afd93a.png">
<img width="1440" alt="Screenshot 2022-02-28 at 6 46 02 PM" src="https://user-images.githubusercontent.com/51681379/155990749-84657904-bd36-471c-ab4b-882105484510.png">
<img width="1440" alt="Screenshot 2022-02-28 at 6 45 54 PM" src="https://user-images.githubusercontent.com/51681379/155990927-a0d8fc6d-34bf-42de-a5a7-df74bef47ebe.png">

Hence ,we are adding 'Needs Update' Label

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @Quazz,
Thank you for your quick reply and we have verified the issue on Magento 2.4 Develop , Here are the test results.
1. Define synonym group (eg notebook,laptop)
<img width="1440" alt="Screenshot 2022-03-04 at 6 04 16 AM" src="https://user-images.githubusercontent.com/51681379/156678038-76441897-de04-438e-a81d-48653876717d.png">
2. Have product with name "New Laptop" and another product with name "New Laptop Notebook"
<img width="1440" alt="Screenshot 2022-03-04 at 6 09 14 AM" src="https://user-images.githubusercontent.com/51681379/156678130-cfdec902-41fc-413d-a5db-2a048a3a3b09.png">
3. Used Elastichsearch 7 as search engine

4. Set "Minimum Terms to Match" to a value (Ex: 2 )
Here test results only displayed Single product.
<img width="1440" alt="Screenshot 2022-03-04 at 7 12 00 AM" src="https://user-images.githubusercontent.com/51681379/156683181-d6fb05f0-25d0-45c9-95d3-83e8196183c8.png">
Results of 'Notebook' search results.
<img width="1440" alt="Screenshot 2022-03-04 at 7 15 18 AM" src="https://user-images.githubusercontent.com/51681379/156683372-d1977efc-efd1-4dd0-8b6a-1c228be7439f.png">
Results of 'Laptop'
<img width="1440" alt="Screenshot 2022-03-04 at 7 17 20 AM" src="https://user-images.githubusercontent.com/51681379/156683475-8eebae4c-3280-48b4-92cb-58560982bd61.png">

6. Set "Minimum Terms to Match" to a value (Ex: 75%)
<img width="1440" alt="Screenshot 2022-03-04 at 7 17 56 AM" src="https://user-images.githubusercontent.com/51681379/156683594-551051ca-14e1-40ee-a400-f882e3ab1b19.png">

Results: Both Products displayed.
<img width="1440" alt="Screenshot 2022-03-04 at 7 20 19 AM" src="https://user-images.githubusercontent.com/51681379/156684487-fa49b082-8e75-4e18-a95e-2800deb12890.png">
<img width="1440" alt="Screenshot 2022-03-04 at 7 20 36 AM" src="https://user-images.githubusercontent.com/51681379/156684510-140e517f-019b-4c3d-9a5c-960000a35d78.png">


8. Set "Minimum Terms to Match" to a value (Ex: 2<75%)
<img width="1440" alt="Screenshot 2022-03-04 at 7 31 52 AM" src="https://user-images.githubusercontent.com/51681379/156684973-0c5eebd4-6907-408e-a6bc-122bcf3da7e2.png">
Result: **Single Products are getting displayed.**
<img width="1440" alt="Screenshot 2022-03-04 at 7 31 29 AM" src="https://user-images.githubusercontent.com/51681379/156685036-780d8634-544f-4961-b190-a1dcc7204185.png">
<img width="1440" alt="Screenshot 2022-03-04 at 7 31 43 AM" src="https://user-images.githubusercontent.com/51681379/156685060-52514c3b-ad56-4ec7-a2e1-bb4a4be398e7.png">

Hence, issue is not reproducible for First two scenario's. Please review the steps provided.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by rvm-pmis** [comment]
Not sure if this re-opens the ticket, but....
The last test case in this ticket used synonyms "laptop, notebook" combined with 2<75%.
What happens then if you search for either word is that Magento sends the query "laptop notebook" to elasticsearch. The minimum match criterium 2<75% in this case means match at least 1 of the keywords. That's why you get results.

If you were to test with synonyms "laptop,notebook,macbook" combined with 2<75%, then searching for each of these words individually would send all three words as a query to elasticsearch "laptop notebook macbook". 75% of 3 when rounded down is 2, so elasticsearch would require at least 2 of those keywords to match. In that case you'll probably NOT get any results.
