### ISSUE TITLE
Inaccurate Shipping Cost for Multiple Packages

### ISSUE THREAD

**Issue by nicolasddev** [magento/magento2#35146]
### Preconditions (*)

Magento v2.3 & 2.4

### Steps to reproduce (*)

1. Configure any shipping method with a max_package_weight value.
2. Add multiple products to the shopping cart, making sure that multiple boxes are required based on the shipping method's maximum package weight.
3. Trigger the \Magento\Quote\Model\Quote\Address\RateCollectorInterface::collectRates() method either by requesting shipping estimates from the shopping cart or the checkout page, or programmatically through a third party module and use the getResult() method to obtain the rates.

### Expected result (*)

The `cost` values should be accurate in relation to the estimates returned by the carrier.

### Actual result (*)

Although the `price` values from the different packages are compiled properly, the `cost` values remain the ones returned for the first package only.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @nicolasddev,

Thanks for your response!

We have checked the PR stated in the above comment and checked the existing functionality as well. 

Can you please tell us the impacted area and your use case for this? Actually, this will help us in the reproduction of this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nicolasddev,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by nicolasddev** [comment]
Hi @engcom-Hotel,

The Cost value is set by Magento built-in shipping carrier modules such as UPS, DHL and USPS, as it can be seen below.

**UPS Module:**
[https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Ups/Model/Carrier.php#L966](https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Ups/Model/Carrier.php#L966)

**DHL Module:**
[https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Dhl/Model/Carrier.php#L1234](https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Dhl/Model/Carrier.php#L1234)

**USPS Module**
[https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Usps/Model/Carrier.php#L691](https://github.com/magento/magento2/blob/2a774fc107e8b42d61b1ee0853c5c1b5bfd9f248/app/code/Magento/Usps/Model/Carrier.php#L691)

These values have been set by the different carriers, even in earlier Magento versions such as 1.9.X.

However, to answer your question, at this time I'm not aware of any Magento function currently using the Cost value returned for any specific purpose. Although it might not be actively used right now by Magento, it is important to maintain the availability of this variable and to always pass it along with the result to ensure compatibility with other modules, which might be using it.

This is actually what led me to opening this issue.
