### ISSUE TITLE
magento2 customer admin grid not loaded properly in Magento2.4.3p1

### ISSUE THREAD

**Issue by Manjula-kalyan** [magento/magento2#35159]
### Preconditions (*)

1.Magento2.4.3p1

### Steps to reproduce (*)

1.All the customers are not listed in customer grid. It's shows only one customer
2.error in console-Uncaught TypeError: Unable to process binding "text: function(){return $col.getLabel($row()) }"
Message: Cannot read properties of undefined (reading 'isValid')

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![Screenshot from 2022-03-03 15-39-50](https://user-images.githubusercontent.com/100841301/156548286-a3397efa-dcc2-4e46-b611-2f08149f6ef0.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Manjula-kalyan ,
Thank you for reporting and collaboration. However provided steps are not enough for us to reproduce the issue. Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and elaborate steps to reproduce / missing configuration details if you are still facing the issue.
Thank you.

**Comment by engcom-November** [comment]
Hi @Manjula-kalyan ,
We are closing this issue as there has been no latest update on the same.
Thank you.
