### ISSUE TITLE
Noticed exception 'Magento\Framework\Exception\SessionException' with message 'The "http_user_agent" session value is invalid. Verify and try again.'

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#35153]
### Preconditions (*)

Hello,

I have installed New Relic on a production website and noticed there is an error popping in the logs showing up.

The error happens when users visit with specific User Agent - IPhone users from Instagram.

I assume the users are some kind of bots or the issue is caused by the internal Instagram browser that does not create a proper session.

1. Magento 2.4.3 CE
2. User Agents that have this issue:

Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 223.0.0.11.104 (iPhone11,6; iOS 15_3_1; en_CA; en-CA; scale=3.00; 1242x2688; 352006504)

Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 223.0.0.11.104 (iPhone13,4; iOS 15_3_1; en_CA; en-CA; scale=3.00; 1284x2778; 352006504)

Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 223.0.0.11.104 (iPhone10,4; iOS 15_3_1; en_CA; en-CA; scale=2.00; 750x1334; 352006504)

Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 223.0.0.11.104 (iPhone13,4; iOS 15_3_1; en_CA; en-CA; scale=3.00; 1284x2778; 352006504)

3. Location - Admin page (/admin)

### Steps to reproduce (*)

1. Turn on HTTP_USER_AGENT validation

![image](https://user-images.githubusercontent.com/66754347/156248472-0cb79b15-e179-4414-aa95-a3693c41efc2.png)

2. Open Magento 2.4.3 /admin page using specific User Agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 223.0.0.11.104 (iPhone10,4; iOS 15_3_1; en_CA; en-CA; scale=2.00; 750x1334; 352006504)

Firefox has an addon for changing the User Agent:
https://addons.mozilla.org/en-CA/firefox/addon/user-agent-string-switcher/

Chrome has extension (not tested):
https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

UPDATE:
I was able to replicate it by visiting /admin URL.

![image](https://user-images.githubusercontent.com/66754347/156245804-2f20d93c-b25b-4317-92d8-14ae40a5bfdf.png)

After I refresh the page, the error disappears. 

### Expected result (*)

1. Admin page shows up correctly without error

### Actual result (*)

1. Exception being thrown about session not being valid:

Magento\Framework\Exception\SessionException: Noticed exception 'Magento\Framework\Exception\SessionException' with message 'The "http_user_agent" session value is invalid. Verify and try again.' in /home/magentosite/site_location/vendor/magento/framework/Session/Validator.php:156
in Magento\Framework\Session\Validator::_validate called at /home/magentosite/site_location/vendor/magento/framework/Session/Validator.php (86)
in Magento\Framework\Session\Validator::validate called at /home/magentosite/site_location/vendor/magento/framework/Session/SessionManager.php (211)
in Magento\Framework\Session\SessionManager::start called at /home/magentosite/site_location/vendor/magento/framework/Interception/Interceptor.php (58)
in Magento\Framework\Session\Generic\Interceptor::___callParent called at /home/magentosite/site_location/vendor/magento/framework/Interception/Interceptor.php (138)
in Magento\Framework\Session\Generic\Interceptor::Magento\Framework\Interception\{closure} called at /home/magentosite/site_location/vendor/magento/framework/Interception/Interceptor.php (153)
in Magento\Framework\Session\Generic\Interceptor::___callPlugins called at /home/magentosite/site_location/generated/code/Magento/Framework/Session/Generic/Interceptor.php (23)
in Magento\Framework\Session\Generic\Interceptor::start called at /home/magentosite/site_location/vendor/magento/framework/Session/SessionManager.php (141)
in Magento\Framework\Session\SessionManager::__construct called at /home/magentosite/site_location/generated/code/Magento/Framework/Session/Generic/Interceptor.php (14)
in Magento\Framework\Session\Generic\Interceptor::__construct called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php (121)
in Magento\Framework\ObjectManager\Factory\AbstractFactory::createObject called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (108)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (150)
in Magento\Framework\ObjectManager\Factory\Compiled::get called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (79)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (150)
in Magento\Framework\ObjectManager\Factory\Compiled::get called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (79)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (150)
in Magento\Framework\ObjectManager\Factory\Compiled::get called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (79)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (150)
in Magento\Framework\ObjectManager\Factory\Compiled::get called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (125)
in Magento\Framework\ObjectManager\Factory\Compiled::parseArray called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (86)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/ObjectManager.php (70)
in Magento\Framework\ObjectManager\ObjectManager::get called at /home/magentosite/site_location/vendor/magento/framework/App/FrontController.php (109)
in Magento\Framework\App\FrontController::__construct called at /home/magentosite/site_location/generated/code/Magento/Framework/App/FrontController/Interceptor.php (14)
in Magento\Framework\App\FrontController\Interceptor::__construct called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php (121)
in Magento\Framework\ObjectManager\Factory\AbstractFactory::createObject called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/Factory/Compiled.php (108)
in Magento\Framework\ObjectManager\Factory\Compiled::create called at /home/magentosite/site_location/vendor/magento/framework/ObjectManager/ObjectManager.php (70)
in Magento\Framework\ObjectManager\ObjectManager::get called at /home/magentosite/site_location/vendor/magento/framework/App/Http.php (115)
in Magento\Framework\App\Http::launch called at /home/magentosite/site_location/vendor/magento/framework/App/Bootstrap.php (264)
in Magento\Framework\App\Bootstrap::run called at /home/magentosite/site_location/pub/index.php (29)

Here is the attributes of the Error on NewRelic:

![image](https://user-images.githubusercontent.com/66754347/156233791-cd26052d-0af5-46e3-b828-0afed654790f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by pmonosolo** [comment]
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment]
https://github.com/magento give me 2.4.3-develop instance

**Comment by pmonosolo** [comment]
@magento give me 2.4.3-develop instance

**Comment by pmonosolo** [comment]
Hmmm, looks like its erroring out on 2.4-develop instance(when going to /admin url it redirects to homepage), 

I don't know how to turn on error reporting on the instance, can somebody point me to the docs?

**Comment by pmonosolo** [comment]
I think its happening when the User Agent is changing on the URL:

![image](https://user-images.githubusercontent.com/66754347/156250240-50e0d204-938a-4050-b971-adf9361fd178.png)

![image](https://user-images.githubusercontent.com/66754347/156250348-74d5d27e-8e09-4fca-9901-8b96a4afb90b.png)

Then it goes to the home page:

![image](https://user-images.githubusercontent.com/66754347/156250392-240064d6-291d-4306-94e5-b3d738f5139c.png)

![image](https://user-images.githubusercontent.com/66754347/156250419-cf417a08-ad0e-4daf-b0a5-edeaf9d7719e.png)



This is the 302 Redirect that was created as soon as I changed the User Agent.

**Comment by engcom-Delta** [comment]
Hi @pmonosolo ,

Thank you for raising the issue , we tried to reproduce it on Magento 2.4 Develop but it is reproducible.
Hence marking the issue 'Issue Confirmed'.
Steps followed:

1. Turn on HTTP_USER_AGENT validation
![Screenshot from 2022-03-07 16-11-50](https://user-images.githubusercontent.com/51681379/157016866-118323cd-7528-4b7f-81e9-3f4c66348012.png)

2. Open Magento 2.4.3 /admin page using specific User Agent:
Mozilla/5.0 
Firefox has an addon for changing the User Agent:
https://addons.mozilla.org/en-CA/firefox/addon/user-agent-string-switcher/

Chrome has extension (not tested):
https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg
3.Mozilla/5.0
(iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15
(KHTML, like Gecko) FxiOS/33.0 Mobile/15E148 Safari/605.1.15


Mozilla/5.0
(iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15
![Screenshot from 2022-03-07 13-46-17](https://user-images.githubusercontent.com/51681379/157017535-f93f9bd8-c50e-4ffd-a0cc-a8e061fae7a5.png)
![Screenshot from 2022-03-07 14-05-54](https://user-images.githubusercontent.com/51681379/157017557-c184342d-f28a-41a1-b15a-cb1b55973aac.png)
![Screenshot from 2022-03-07 14-29-23](https://user-images.githubusercontent.com/51681379/157017579-28756737-d492-44cb-9c8b-8c64c68dd805.png)
![Screenshot from 2022-03-07 14-34-20](https://user-images.githubusercontent.com/51681379/157017620-f7921469-c162-4f0c-803b-e3b2d0ba4c4d.png)

**Comment by engcom-Delta** [comment]
Hi @pmonosolo ,
As per confirmation from @engcom-Lima  , The issue is reproducible but not for specific https_user_agent as mentioned by the reporter.
The issue exists when we switch http_user_agent , in that case the http_user_agent in $_SESSION and $_SERVER will be different and hence will throw an error as mentioned in the [documentation](https://docs.magento.com/user-guide/stores/security-session-validation.html)

Also in case of production mode the site will not break and will be redirected to home page and it will only break in case of developer mode.

This seems to be an expected behaviour and not the issue as per the documentation.

Hence, issue has been closed.
