### ISSUE TITLE
Problem with Phone Number required in different stores

### ISSUE THREAD

**Issue by amenk** [magento/magento2#35158]
Follow up of #10978 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by amenk** [comment]
@magento give me 2.4-develop instance with extensions magefan/module-cli

**Comment by amenk** [comment]
https://github.com/magento give me 2.4-develop with extensions magefan/module-cli instance

**Comment by amenk** [comment]
@magento give me 2.4-develop with extensions magefan/module-cli instance

**Comment by amenk** [comment]
@engcom-Delta Yes, that is my plan, but I did not succeed in spinning up a test instance with CLI access which I need for the repro. Do you have an idea about this?

**Comment by amenk** [comment]
@engcom-Delta Does adding extensions work only for the Magento team ? (see https://devdocs.magento.com/contributor-guide/contributing.html#customize-deployed-instances) can you issue that command above `give me 2.4-develop instance with extensions magefan/module-cli`) to get an instance with the CLI so I can reproduce the issue we are facing?

**Comment by amenk** [comment]
@engcom-Delta is it possible to get a test instance with CLI ?

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance with extensions magefan/module-cli

**Comment by amenk** [comment]
@engcom-Hotel Thanks, but still the instance does not seem to have the CLI module - so I believe either something is broken or that does not work to add extensions?

Will probably try to reproduce it in another way

**Comment by amenk** [comment]
I cannot reproduce the issue anymore in 2.4-develop

I configured as follows
![1-website-settings](https://user-images.githubusercontent.com/1087128/158425316-f0a7c661-5efd-4a27-b3b2-dd7e7656622b.png)
![2-config-default](https://user-images.githubusercontent.com/1087128/158425324-28b83d64-9fd7-4186-9e4d-994fae95cb40.png)
![3-config-second](https://user-images.githubusercontent.com/1087128/158425333-6994255e-0fc6-452c-9a0e-f159abfeba4d.png)

Made the requests

[requests.zip](https://github.com/magento/magento2/files/8255335/requests.zip)

I was expecting getting a "telephone required" in the second store, but this seems to work.

**Comment by amenk** [comment]
@magento give me 2.3.4-p2 instance

**Comment by amenk** [comment]
@magento give me 2.3.4-p2 instance

**Comment by amenk** [comment]
@magento give me 2.3.4 instance

**Comment by amenk** [comment]
I wanted to verify my repro steps in 2.3.4 but that does not seem to work. Closing this.

**Comment by amenk** [comment]
The problem still appears in 2.4.4 in our customized instance. I did not yet have the time to reproduce this in a vanilla instance.

As my repro steps locally involve cleaning the cache via CLI, this is quite hard to test in the vanilla cloud instances.

Is there anyone of the Magento team who can test this with CLI access? In the end of the day #10978 is still open anyways, so probably it's best to track that there.

**Comment by amenk** [comment]
This is still an issue, currently we have disabled the eav cache as a workaround.

But it is not verifyable here in GitHub due to the technical limitations of the test instances.

Please test locally

**Comment by engcom-Bravo** [comment]
Hi @amenk,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance(locally) and the issue is not reproducible.Kindly refer the screenshots.


![Configuration-Settings-Stores-Magento-Admin (7)](https://github.com/magento/magento2/assets/51680745/df3bfdfb-8ce0-4811-8f7e-00a750b4e950)



<img width="1042" alt="Screenshot 2023-06-08 at 4 40 09 PM" src="https://github.com/magento/magento2/assets/51680745/4990c31b-80d4-4a6f-8369-9775a67c1bcd">



![Configuration-Settings-Stores-Magento-Admin (8)](https://github.com/magento/magento2/assets/51680745/ced4af80-2eac-4482-8763-b9001e22d41b)



<img width="1153" alt="Screenshot 2023-06-08 at 4 35 09 PM" src="https://github.com/magento/magento2/assets/51680745/0957bb36-0704-40be-893b-cb7d22a61fde">



For main website show telephone is set as required and in the response we are getting telephone is required for second website(English) it is working as expected.Kindly provide us detail steps to reproduce it will help us to reproduce the issue.


Please let us know if we are missing anything.

Thanks.

**Comment by amenk** [comment]
Thanks for testing, the cache needs to be cleaned in the middle of the process, it's pretty much the same issue as in https://github.com/magento/magento2/issues/10978

**Comment by engcom-Bravo** [comment]
Hi @amenk,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance(locally) still we are not reproducible the issue.Kindly refer the attached video.


We have flushed the cache in the middle of process.



https://github.com/magento/magento2/assets/51680745/2755295b-8bc6-47bd-abea-0cba75edcb3d



Please let us know if we are still missing anything.

Thanks.

**Comment by amenk** [comment]
Let's follow this in https://github.com/magento/magento2/issues/10978 - maybe you can reproduce there and follow up on the status.
