### ISSUE TITLE
Import image public URL

### ISSUE THREAD

**Issue by DipaliMarade** [magento/magento2#35151]
Hi,

I am getting public URL from client's system. what i want to do is I want to add image URL on magento product through Rest API. 
But on the standard Product API section i did not get any way to add public URL.
Is there any way to do so. I think only way i found is to add Base64.
Let me know if it is possible to add public URL?

**Comment by engcom-Hotel** [comment]
Hello @DipaliMarade,

Currently, we have only API which requires Base 64 encoded value for product image uploading. Please go through with the below link for documentation:

https://magento.redoc.ly/2.4.3-admin/tag/productsskumedia#operation/catalogProductAttributeMediaGalleryManagementV1CreatePost

Thanks

**Comment by engcom-Hotel** [comment]
Dear @DipaliMarade,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
