### ISSUE TITLE
Two admin menu nodes use the same ACL resource

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#3515]
"Products  -> Inventory" menu node uses "Magento_Catalog::catalog" ACL resource, the same as root "Products" node. It causes UI problem when custom node is added under "Products" node. To display such custom node I need to add permission to "Magento_Catalog::catalog" and it causes displaying empty "Inventory" node.

"Products  -> Inventory" should use "Magento_Catalog::catalog_inventory" ACL resource.

**Preconditions**
1. Install Magento 2.0.2

**Steps to reproduce**
1. Install custom module which adds backend menu item under Products node
2. Create administrator account with access only to custom module section
3. Log in into administrator account

**Expected result**
Only custom module menu items should be displayed under Products node

**Actual result**
Above custom module menu items empty "Inventory" node is displayed

**Comment by kokoc** [comment]
Thanks for your findings.

This node was used as a container in previous design, not for catalog inventory module. The same behaviour could be observed in sales menu (Sales -> Operations)
Also we can't remove such obsolete nodes now, because of possible impact on developers who use these nodes.

**Comment by wojtekn** [comment]
@kokoc why you close this? you could at least document it somewhere as "known bug".
