### ISSUE TITLE
umasked quote_id being passed when calling estimate-shipping-methods API in checkout page

### ISSUE THREAD

**Issue by vicehope** [magento/magento2#35167]
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Login to storefront as a regular customer
2. Add few items into the cart
3. Click on "Proceed to checkout"
4. Checkout page renders on the browser
6. API call to rest/home3/V1/guest-carts/22806/estimate-shipping-methods where `22806` is the unmasked quote_id

### Expected result (*)

1. Checkout as registered customer
2. Able to proceed to get shipping quote. Call API rest/home3/V1/guest-carts/<masked_quote_id>/estimate-shipping-methods using the masked quote ID (hashed ID)
3. Redirect to payment page and complete the order

### Actual result (*)

1. Checkout page doesn't recognize the login session, it is checking out as guest identity 
![image](https://user-images.githubusercontent.com/10783715/156871113-8c1015a5-b8fe-4ca9-9a13-b508d9f37195.png)

2. Call estimate-shipping-methods with unmasked quote_id provided
![image](https://user-images.githubusercontent.com/10783715/156870981-737bd7c7-eaad-4e42-84bf-5e65efb2a273.png)
3. API response with error `No such entity` because of unmasked quote_id doesn't exists in masked quote mapping table
![image](https://user-images.githubusercontent.com/10783715/156871040-2266dbe7-6d9e-46ba-9dbd-10dba598b001.png)

Additional Information
1. the properties window.checkoutConfig.quoteData.entity_id has stored a unmasked value
![image](https://user-images.githubusercontent.com/10783715/156871409-2c1d49c7-7cc3-4e4b-9d98-d0f9a0310e7e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ryanpalmerweb** [comment]
@vicehope What was the issue?

**Comment by fidellakis-coolibar** [comment]
Interested in knowing what the fix was also. Suffering from this issue currently.

**Comment by usman786cs** [comment]
I'm struggling with same problem where
`/V1/guest-carts/1877091/estimate-shipping-methods`
is being used instead of masked quote ID.

@manish85sixty you think above solution will resolve this issue?
Thanks in advance!

**Comment by manish85sixty** [comment]
@usman786cs Above solution resolved the issue on our end.

**Comment by usman786cs** [comment]
Thanks @manish85sixty  , I'll check if it work for us.
