### ISSUE TITLE
Buttons not showing on UI Listing component

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#35161]
1. Magento 2.4.3-p1

### Steps to reproduce (*)

Create a new listing UI component to add as a custom tab on product edit page. This involves creating far more code than it should need so here's the relevant section of the listing XML:

```
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">quantities_grid.quantities_grid_data_source</item>
            <item name="deps" xsi:type="string">quantities_grid.quantities_grid_data_source</item>
        </item>
        <item name="spinner" xsi:type="string">quantities_grid_columns</item>
        <item name="buttons" xsi:type="array">
            <item name="addqty" xsi:type="array">
                <item name="name" xsi:type="string">addqty</item>
                <item name="label" xsi:type="string" translate="true">Add Quantity</item>
                <item name="class" xsi:type="string">primary</item>
                <item name="url" xsi:type="string">*/*/add</item>
            </item>
        </item>
    </argument>

```

### Expected result (*)
Button Add Quantity should be added to listing

### Actual result (*)
Button is not added and no errors/logs anywhere to indicate why.

![image](https://user-images.githubusercontent.com/13659750/156737443-ad3ae5ca-e7e9-4f16-b55f-42662420f74b.png)

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by adamlavery** [comment]
Please note: for a development instance to be any use for this kind of issue we also need SSH access to be able to install modules. We don't get that so won't ask for one.

**Comment by engcom-Delta** [comment]
Hi @adamlavery ,
Thank you for raising an issue and happy to assist. Could you please specify that in which file provided code has to be added for new listing UI component to add as a custom tab on product edit page.
Hence, We added the label 'Needs update'.
Regards,

**Comment by adamlavery** [comment]
Normal rules and placement for this code, although appreciate using UI components is overly complicated requiring large amounts of displaced code. This is the listing component XML in:

`Vendor/Module/view/adminhtml/ui_component/quantities_grid.xml`

This is referenced in the tab XML that is inserted into the product page:

```
ALP/TablePricing/Ui/DataProvider/Product/Form/Modifier/QuantitiesTab.php

<?php 
namespace ALP\TablePricing\Ui\DataProvider\Product\Form\Modifier; 

use Magento\Catalog\Model\Locator\LocatorInterface; 
use Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\AbstractModifier; 
use Magento\Framework\Stdlib\ArrayManager; 
use Magento\Framework\UrlInterface; 
use Magento\Ui\Component\Container; 
use Magento\Ui\Component\Form\Fieldset; 

class QuantitiesTab extends AbstractModifier { 
    
    const FIELDSET_NAME = 'quantities_grid_fieldset'; 
    const FIELD_NAME = 'quantities_grid'; 

    ...    

    protected function addQuantitiesTab()
    {
        $this->meta = array_merge_recursive(
            $this->meta,
            [
                static::FIELDSET_NAME => $this->getTabConfig(),
            ]
        );
    }
  
    protected function getTabConfig()
    {

        return [
            'arguments' => [
                'data' => [
                    'config' => [
                        'label' => __('Quantities'),
                        'componentType' => Fieldset::NAME,
                        //'provider' => static::FORM_NAME . '.product_form_data_source',
                        //'ns' => static::FORM_NAME,
                        'collapsible' => true,
                        'sortOrder' => 10,
                    ],
                ],
            ],

            'children' => [
                static::FIELD_NAME => [
                    'arguments' => [
                        'data' => [
                            'config' => [
                                'autoRender' => true,
                                'componentType' => 'insertListing',
                                'dataScope' => 'quantities_grid',
                                'externalProvider' => 'quantities_grid.quantities_grid_data_source',
                                'selectionsProvider' => 'quantities_grid.quantities_grid.product_columns.ids',
                                'ns' => 'quantities_grid',
                                'render_url' => $this->urlBuilder->getUrl('mui/index/render'),
                                'realTimeLink' => false,
                                'behaviourType' => 'simple',
                                'externalFilterMode' => true,
                                'imports' => [
                                    'productId' => '${ $.provider }:data.product.current_product_id'
                                ],
                                'exports' => [
                                    'productId' => '${ $.externalProvider }:params.current_product_id'
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
 }

```

**Comment by adamlavery** [comment]
Now getting somewhere establising why this is happening - I think! I believe it hinges around this obscure comment in the notes on InsertListing:

![image](https://user-images.githubusercontent.com/13659750/157425804-bb91790c-8ffe-4d51-ac67-4cb237cc220a.png)

Modifying the code to do as suggested results in even stranger behaviour:

```
                                //'render_url' => $this->urlBuilder->getUrl('mui/index/render'),
                                'render_url' => $this->urlBuilder->getUrl(
                                    'mui/index/render_handle', 
                                    [
                                        'handle' => 'tablepricing_quantities_add',
                                        'buttons' => 1
                                    ]
                                ),

```
That results in the following UI:

![image](https://user-images.githubusercontent.com/13659750/157441120-fbba993c-54ac-4df0-a685-bc3557313cd9.png)

It seems to me that buttons declared in the UI component XML simply don't work in the context of a Listing component added via InsertListing. Probably some convoluted mechanism that the note above alludes to. As I'm finding with UI components, nothing is well explained at all. We're left to try to find examples that are a closest match to what were trying to do but then find the configuration that works in one context doesn't work in another; which you only discover when nothing happens. How did you manage to come up with something so complex it's unfathomable and probably undocumentable? 

This explains why core components are a mishmash of different ways UI components can be implemented. Isn't this going to be fun working with Magento in the future! Methinks time to find something you don't need a Masters in Magento to accomplish even the simplest of tasks on.

**Comment by adamlavery** [comment]
Closing this because I suspect this issue is "by accidental design" that will/can never be fixed given the complexity of UI Components. Seems working with them is always going to be hit'n'miss.
