### ISSUE TITLE
UPS negotiated rates not working on label purchase

### ISSUE THREAD

**Issue by mswaidan** [magento/magento2#3516]
UPS negotiated rates are not being applied at the time of label purchase. They do appear to be applied during checkout, as the customers are paying a discounted rate. `</Package><RateInformation><NegotiatedRatesIndicator/></RateInformation>  </Shipment>` does show up in the XML request in debug.log for the labels in question.

Let me know what other information I can supply to help get this resolved. Thanks!

**Comment by alena-marchenko** [comment]
Hi Matthew,

We've created MAGETWO-50249 internal ticket regarding this issue

**Comment by mswaidan** [comment]
Thanks @alena-marchenko . I noticed yesterday when I examined my bills that the negotiated rates are in fact being applied, they just don't show up on the package detail page the way other negotiated rates typically do. They are applied on the invoice from UPS. You can close the ticket. Thanks for the follow up!
