### ISSUE TITLE
2.4.3-p1 - Magento\Customer\Model\Address\AbstractAddress::_implodeArrayValues($value)

### ISSUE THREAD

**Issue by zepgram** [magento/magento2#35160]
### Preconditions (*)

1. Magento 2.4.3-p1
2. PHP 7.4

### Steps to reproduce (*)

1. To reproduce, simply try to set an address through graphql with a non scalar attribute (null) for second street.<br>
![image](https://user-images.githubusercontent.com/16258478/156549296-296ff652-3e0f-4559-b6f6-b06b40b938cf.png)
```
mutation {
 setShippingAddressesOnCart(
  input: {
   cart_id: "{{cart}}"
   shipping_addresses: [
    {
     address: {
      country_code: "FR"
      street: ["Lorem ipsum dolor sit ame", null]
      telephone: "0601020304"
      postcode: "56590"
      city: "PARIS"
      firstname: "B"
      lastname: "C"
      save_in_address_book: false
     }
    }
   ]
  }
 ) {
  cart {
   shipping_addresses {
    firstname
    lastname
    company
    street
    city
    postcode
    country {
     code
     label
    }
    telephone
   }
  }
 }
}
```

### Expected result (*)

1. While analysing this issue, I found out that `magento/vendor/magento/module-customer/Model/Address/AbstractAddress.php` is responsible of this.
2. Left side is 2.4.3-p1, right side is 2.3.5, by simply reading the code you can understand the issue: **if one of the value in the array is non-scalar, values will never be trimmed and exploded as expected.** see related commit: https://github.com/magento/magento2/commit/876c8052f96d6770254277ff4dd39bce5e935d50 <br>
![image](https://user-images.githubusercontent.com/16258478/156546150-61322d6e-4c55-4bb1-b195-f5afa1e52727.png)
3. By putting back the 2.3.5 code, this work as expected:
<br>![image](https://user-images.githubusercontent.com/16258478/156548564-4c91a2fb-c4b1-4a31-a353-d31bfc373843.png)

### Actual result (*)

1. By setting null in secondary address field, an exception is thrown: _"The address failed to save. Verify the address and try again."_<br>
![image](https://user-images.githubusercontent.com/16258478/156549593-dad8cbbe-10eb-4cfc-aea8-1dd0aa408d31.png)
2. Due to the scalar condition, the street field is never imploded and his value is an array instead of a string, the class `magento/framework/DB/Adapter/Pdo/Mysql.php` logicly throw when trying to cast the value in string, and we can find this in logs: ```[2022-03-03 09:42:03] report.CRITICAL: Notice: Array to string conversion in /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 {"exception":"[object] (Exception(code: 0): Notice: Array to string conversion in /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 at /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/App/ErrorHandler.php:61)"} []```

---
Due to multiple impact and side effects on quote/customer addresses, I think this is a S0 priority.

- [x] Severity: **S0**

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
![image](https://user-images.githubusercontent.com/60198231/156569002-85925224-6b6f-4e62-bc26-45ab7d560404.png)

**Comment by Zaahed** [comment]
@magento I'm working on this

**Comment by pmzandbergen** [comment]
Verified on 2.4.4, applying patch for `magento/module-customer` on our projects awaiting a fix in the Magento Core.

```
--- Model/Address/AbstractAddress.php.org	2022-08-08 16:06:17.000000000 +0200
+++ Model/Address/AbstractAddress.php	2022-08-08 16:06:36.000000000 +0200
@@ -329,10 +329,10 @@
                 return '';
             }
 
-            $isScalar = true;
+            $isScalar = false;
             foreach ($value as $val) {
-                if (!is_scalar($val)) {
-                    $isScalar = false;
+                if (is_scalar($val)) {
+                    $isScalar = true;
                     break;
                 }
             }
```

_PS Maybe `if (is_scalar($val) || $val === null) {` is a better option (depending on where this is being used)_

**Comment by pmzandbergen** [comment]
@Zaahed accidentally didn't spot your PR, which does the job (even with only `null` values). Maybe add a unit test to verify and keep future updates from breaking this again.

**Comment by Zaahed** [comment]
@pmzandbergen Thx for the suggestion. I added a unit test to the PR.

**Comment by PascalBrouwers** [comment]
I can confirm this issue is present in 2.4.3 when using GraphQL. Using provided diff I can also confirm it works when reverting the code.

Currently it's almost a year later and still not fixed or even added to the latest develop branch.

**Comment by engcom-November** [comment]
Hi @zepgram ,
Development team has started working on this issue.
Thank you.
