### ISSUE TITLE
Customer session setData return null if add to cart more than 30 products at a time.

### ISSUE THREAD

**Issue by mgoswamirave** [magento/magento2#35177]
Customer session setData return null if add to cart more than 30 products at a time.

### Preconditions (*)

Magento Version : 2.3.7-p2 EE (B2B)

Environment: Production

Third-party modules: No

### Steps to reproduce (*)

1. Login with the customer.
2. Add to cart more than 30 products and getData from customer session on the cart page which we set previously.
3. We get a null value from the customer session.

### Expected result (*)

1. Customer session should return previously set value.
2.  We are getting the previously set value if we add only 10 to 15 products to the cart. This issue only occurs if we add more than 30 items in the cart.

Everything was working fine but after upgrading to Magento 2.3.7-p2 version we are facing this customer session setData value with more than 30 items a time.

Is there any PHP.in setting that needs to change to enable heavy cart? Please suggest.

**Comment by hostep** [comment]
This is just a guess, but Magento 2.3.7-p1 (and 2.4.3) introduced (as a security feature) two fields to limit the session size, both in admin & frontend. Maybe you run against this limit? You should be able to find violations against this limit in the `var/log/system.log` file.
You can increase these limits in the backoffice via: Stores > Configuration > Advanced > System > Security

Also this unreleased change might improve your experience: https://github.com/magento/magento2/commit/1b84b623f36282e9a95eddbb8205b8d45a9ca77b

I hope this helps, but if this is something else, you'll  probably will need to do some debugging to figure out what goes wrong in your specific case.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop branch

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @mgoswamirave ,

Kindly add Actual results and Screenshots Because it is very useful to proceed further.

Thanks!!

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
