### ISSUE TITLE
My site backened take many time in loading please help me 

### ISSUE THREAD

**Issue by haroonsulehri** [magento/magento2#35176]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @haroonsulehri ,
Thank you for reporting and collaboration. However provided summary is not enough for us to reproduce the issue. Kindly elaborate the issue and provide steps to reproduce the issue.
Thank you.

**Comment by hostep** [comment]
We've noticed such behavior as well in recent Magento versions after they've introduced a session size limit.

So if you run into the same problem, I would suggest you look into your `var/log/system.log` file and see if it mentions something along these lines:

```
Session size of xxxxxx exceeded allowed session max size of 256000
```

If that's the case, you'll need to increase the max session limit value for the admin:

```
bin/magento config:set system/security/max_session_size_admin yyyyyy
bin/magento cache:flush
```

(where `yyyyyy` is a number higher than `xxxxxxx`)

**Comment by engcom-November** [comment]
Hi @haroonsulehri ,
We are closing this issue as there has been no latest update on the same.
Thank you.
