### ISSUE TITLE
Magento 2 Quality Patch Tool MDVA-43443

### ISSUE THREAD

**Issue by nmtrimblper** [magento/magento2#35170]
### Preconditions (*)

1. 2.4.3-p1 Enterprise Edition (on prem)
2. Currently attempting to apply the patch in a local environment

### Steps to reproduce (*)

1.  Install the quality patches tool: composer require magento/quality-patches
2.  Install the MDVA-43443 security patch using the tool from the project root directory: ./vendor/bin/magento-patches apply MDVA-43443 

### Expected result (*)

1. I expect the MDVA-43443 patch to be applied.   The related security patch, MDVA-43395 is able to be applied via the tool
![image](https://user-images.githubusercontent.com/101122692/157068202-f9eb8641-d4f2-4d93-af5c-d125b5d75cd2.png)
2. Security patch article: https://support.magento.com/hc/en-us/articles/4426353041293-Security-updates-available-for-Adobe-Commerce-APSB22-12#:~:text=To%20resolve%20the%20vulnerability%2C%20you%20must%20apply%20two%20patches%3A%20MDVA%2D43395%20patch%20first%2C%20and%20then%20MDVA%2D43443%20on%20top%20of%20it.

### Actual result (*)

1. You will receive error: "Next patches weren't found: MDVA-43443. Please, check with "status" command availability of these patches for the current Magento version." 
![image](https://user-images.githubusercontent.com/101122692/157068635-46225c1b-97d8-4ea8-8ccb-2f09d0842801.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4.3-p1** branch.

**Description:** Not able to apply patch MDVA-43443 &  MDVA-43395.
**Pre-requisite:**
Fresh magento `2.4.3-p1` should be installed.

**Steps to reproduce:**

1. Install the quality patches tool: composer require magento/quality-patches
2. Install the MDVA-43443 security patch using the tool from the project root directory: ./vendor/bin/magento-patches apply MDVA-43443
I have checked in  checked status `./vendor/bin/magento-patches status` but both patches (MDVA-43443 &  MDVA-43395) is not available.

**Expected result:**  Patch should be installed successfully.
**Actual result:**  Getting error.In my case  MDVA-43395 also not getting installed as we have to install it before MDVA-43443.
**Screenshots:**

![Screenshot from 2022-08-18 17-23-57](https://user-images.githubusercontent.com/60198022/185407067-1519106a-54e3-45e9-8e21-3c51c11d9871.png)


Hence,confirming the issue.

**Comment by sdzhepa** [comment]
Hello @nmtrimblper 

I think such issue should be reported and fixed in https://github.com/magento/quality-patches/issues

cc @engcom-Lima

**Comment by agorbivskyi** [comment]
@nmtrimblper there is actually no issue here - these security patches were never added to QPT tool and therefore are not supposed to be applied via QPT. They should be downloaded and applied as a regular patches https://support.magento.com/hc/en-us/articles/360028367731

There might be some confusions when you are checking statuses of these particular security patches (**already applied**) via QPT tool which was addressed in this article https://support.magento.com/hc/en-us/articles/4426353041293-Security-updates-available-for-Adobe-Commerce-APSB22-12

Also, please note, these security patches were added to cloud patches - so it will be applied automatically for cloud clients (e.g. https://github.com/magento/magento-cloud-patches/blob/1.0.18/patches/MDVA-43443__parser_token_new_fix__2.4.3.patch).

cc: @sdzhepa , @engcom-Lima
