### ISSUE TITLE
Facebook Business Ext

### ISSUE THREAD

**Issue by elicru** [magento/magento2#35173]
Facebook Business Extension not syncing properly

Facebook for Magento (App ID: 195311308289826) is “enabled to sync” but products are not updating properly in Facebook?

![Screen Shot 2022-03-10 at 1 03 49 AM](https://user-images.githubusercontent.com/101280751/157493320-be928bf8-3c2d-4e08-83a1-685d084c8b10.png)

![Screen Shot 2022-03-10 at 12 56 10 AM](https://user-images.githubusercontent.com/101280751/157493411-4f16a386-c860-4a88-a656-ac1c0e435bb2.png)

**Comment by engcom-November** [comment]
Hi @elicru 
Thank you for reporting. However, Facebook Business is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
