### ISSUE TITLE
Shipping costs not calculated correctly with table rates and virtual/physical products in cart

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#35185]
### Preconditions (*)
1. Magento 2.4.3-p1

Tables rates is configured to allow 0 shipping costs once the cart total reaches a threshold value. It fails when the cart contains both virtual and physical products even though the configuration "Include Virtual Products in Price Calculation" is set to "No".

### Steps to reproduce (*)
1. Table rates shipping table is set to zero shipping cost once you reach a total amount of 75,- € (63.0252 excl. tax)
![ship-config](https://user-images.githubusercontent.com/1006378/157886556-6c67b601-7370-4ff4-a9c9-0954047a40c4.png)
2. Table rates config is set to price vs. destination
3. "Include Virtual Products in Price Calculation" set to "No"
4. Create a simple (e.g. 34,- €) and a virtual product (e.g. 100,-€)
5. Add both products to cart

### Expected result (*)

Only the physical product's price should be taken into account when calculating the shipping price. The virtual product's price should be ignored completely.

![checkout-expected](https://user-images.githubusercontent.com/1006378/157888191-5a5e041c-69e8-4597-86bb-b1c42bf1835b.png)

### Actual result (*)
1. The virtual product is taken into account
2. Magento thinks the threshold is reached and sets the shipping cost to 0,-

![checkout-actual](https://user-images.githubusercontent.com/1006378/157888768-e2432bec-679c-47ea-8ade-eefd14034e59.png)

The exact same issue has been reported here: https://github.com/magento/magento2/issues/27861
It is supposed to be fixed but it is not.

**Comment by OvalMedia** [comment]
@magento give me 2.4-develop instance

**Comment by OvalMedia** [comment]
Same thing in the latest dev version.

**Comment by engcom-Alfa** [comment]
Hi @Reporter ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-2621&type=commits).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
