### ISSUE TITLE
Magento defaults to todays date when adding a custom date product attribute when value is null in the db

### ISSUE THREAD

**Issue by chris-mccabe** [magento/magento2#35189]
### Preconditions (*)

version 2.4.2-p2

### Steps to reproduce (*)

1. Add a custom date attribute programmically to products and the product has a null date in the db 
2. View the product page, the attribute will have a default of todays date as the value passed in the html is null or invalid

### Expected result (*)

1. The field should be empty

### Actual result (*)

1. The value is set to todays date
![image](https://user-images.githubusercontent.com/70527336/158152701-4e9405e8-2e0d-4649-ad27-6e74972e7333.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @adulion2 ,
Thank you for raising an issue and happy to assist you .We are not clear on step# 1 , Hence request to  provide details on which file we should refer the custom date please?
Regards,

**Comment by engcom-Delta** [comment]
Hi @adulion2 ,
We have noticed that this issue has not been updated for a period of 13 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

Thanks
