### ISSUE TITLE
"Not you?" link not shown in header with persistence enabled in 2.4.3-p1 

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#35182]
### Preconditions (*)

1. Magento 2.4.3-p1 or dev-develop
2. Customers->Persistent Shopping Cart->Enable Persistence must be set to YES and all other options below set to YES
3. When logging into front end the checkbox "Remember Me What's this?" must be ticked

### Steps to reproduce (*)

1. Set Customers->Persistent Shopping Cart->Enable Persistence to YES and all other options below set to YES
2. Set General->Web->Default Cookie Settings->Cookie Lifetime to 60 seconds (this is only useful to speed up the testing time but the issue still exists with the default cookie lifetime 
3. Sign in to Luma store with Demo Customer Access (roni_cost@example.com) WITH checkbox "Remember Me What's this?" ticked
4. Browse to any product and add to cart (this step can be omitted but it is useful to prove the persistence is enabled and working when the cart is retrieved)
5. Wait for cookie lifetime to expire simulating a customer's session timing out
6. Browse to homepage and refresh

### Expected result (*)

1. With a persistent cookie is applied, a Not Veronica Costello? link should appears in the page header, to give the customer the ability to terminate the persistent session and start working as a guest, or log in as a different customer. 
2. See Magento documentation for documented behaviour: https://docs.magento.com/user-guide/sales/cart-persistent-workflow.html

### Actual result (*)

1. The "Not you" link is not displayed on the header
2. The first link is "Sign in"
3. To prove persistence is enabled and working, browse to a product and add to cart
4. Previous cart is restored showing both products that have been added
5. See screenshot of actual behaviour
![image](https://user-images.githubusercontent.com/44231639/157855845-a3dbc824-ea4b-494e-975c-e523b5f5a032.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

May cause a customer to unwittingly purchase items added to a previous user on a shared computer as per the example in the documentation.  

### Actual result (*)

1. The "Not you" link is not displayed on the header
2. The first link is "Sign in"
3. To prove persistence is enabled and working, browse to a product and add to cart
4. Previous cart is restored showing both products that have been added
5.  The "Not you" link is STILL not displayed on the header even after retrieving the cart

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

May cause a customer to unwittingly purchase items added to a previous user on a shared computer as per the example in the documentation.

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hello @dphilipps,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2619 by the internal team

Related commits:https://github.com/magento/magento2/search?q=AC-2619&type=commits


Based on the Jira ticket, the target version is 2.4.5.


Thanks
