### ISSUE TITLE
Wrong customer_firstname in sales_order table after re-order

### ISSUE THREAD

**Issue by simonmaass** [magento/magento2#35184]
### Preconditions (*)

1. Magento 2.4.3-p1
2. php7.4

### Steps to reproduce (*)

1. Create guest order
2. Create an account with the same email from the guest order
3. Click on "Reorder" in the created guest order (From step 1) and just save order

### Expected result (*)

1. Correct customer_firstname and customer_lastname fields

### Actual result (*)

1. Both the first and lastname are concatinated and filled in customer_firstname database field

![image](https://user-images.githubusercontent.com/32599710/157859404-7fe04c3c-e9c2-4378-8d11-619f4c9276f0.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @simonmaass ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4 Develop with latest branch.
Unfortunately issue is not reproducible.Hence request to review the provided steps.
<img width="1440" alt="Screenshot 2022-03-11 at 6 54 18 PM" src="https://user-images.githubusercontent.com/51681379/157880387-bca30b4e-59e0-422a-87dc-1fb46f3d6fd5.png">

**Comment by simonmaass** [comment]
@engcom-Delta unfortunately you didnt quite reproduce the steps as provided...

1. Create guest order
**2. Create an account with the same email from the guest order**
3. Click on "Reorder" in the created guest order (From step 1) and just save order

Also your screenshot is showing the "sales_order_address" table while i am talking about the **"sales_order"** table... if you make the 3 steps and DID do the 2nd step then also the new order should be a customer order and not a guest order... so a customer id shoudl be set

**Comment by simonmaass** [comment]
@engcom-Delta would you mind trying again :)

**Comment by engcom-Hotel** [comment]
Hi @engcom-Delta,

As per our discussion in the Triage call, we need to recheck this issue for the Actual result mentioned in the main description.

Thanks

**Comment by engcom-Delta** [comment]
Hi @simonmaass ,
We tried to reproduce it on magento 2.4 develop & 2.4.3-p1 instance ,found that lastname is not concatenated in firstname column .instead of it found that NULL is showing in firstname ,lastname columns. Hence request to review the steps provided.

Please find the attached screenshots for reference.
<img width="1440" alt="Screenshot 2022-03-29 at 2 34 01 PM" src="https://user-images.githubusercontent.com/51681379/160577479-2fad2d18-706d-42d7-bef4-c5a0989a84ee.png">

**Comment by simonmaass** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @simonmaass ,

As per @Serhii Dzhepa instructions , we have verified again in Magento 2.4-develop. it is not reproducible
Firstname and Lastname are not concatenated into firstname column in sales_order table after recorder.

**Steps followed:**

1. Create guest order

<img width="1440" alt="Screenshot 2022-04-29 at 10 51 00 PM" src="https://user-images.githubusercontent.com/51681379/165996059-463b4c93-c603-4d88-8f31-6edf8fcf99cf.png">

2. Create an account with the same email from the guest order

<img width="1440" alt="Screenshot 2022-04-29 at 10 57 08 PM" src="https://user-images.githubusercontent.com/51681379/165996216-6bdbf188-3667-43d6-a305-4c903227823f.png">

<img width="1440" alt="Screenshot 2022-04-29 at 10 57 33 PM" src="https://user-images.githubusercontent.com/51681379/165996273-f1507e61-732e-4cca-a3d5-aacbf0c6fedf.png">

3. Click on "Reorder" in the created guest order (From step 1) and just save order

<img width="1440" alt="Screenshot 2022-04-29 at 11 01 05 PM" src="https://user-images.githubusercontent.com/51681379/165996415-f97e8b2d-a7e7-4700-94a0-276ad14cd633.png">

<img width="1440" alt="Screenshot 2022-04-29 at 11 17 51 PM" src="https://user-images.githubusercontent.com/51681379/165996570-78c4ca5f-496f-48ef-94b7-bf32f1f154b3.png">

<img width="1440" alt="Screenshot 2022-04-29 at 11 18 47 PM" src="https://user-images.githubusercontent.com/51681379/165996661-7691381f-5f74-4b58-9d07-9b87c217153d.png">

4. Verify first name & Last name columns for above orders.

![Uploading Screenshot 2022-04-29 at 11.20.16 PM.png…]()

As per above screenshot  first name & last name values are not concatenated in first name column for re-ordered orders. instead we can see that NULL values is getting inserted for both columns.

**Comment by engcom-Delta** [comment]
Hi @simonmaass ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
