### ISSUE TITLE
Persistent cart contents empty until new product added to cart

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#35183]
### Preconditions (*)

1. Magento 2.4.3-p1 or dev-develop
2. Customers->Persistent Shopping Cart->Enable Persistence must be set to YES and all other options below set to YES
3. When logging into front end the checkbox "Remember Me What's this?" must be ticked

### Steps to reproduce (*)

1. Set Customers->Persistent Shopping Cart->Enable Persistence to YES and all other options below set to YES
2. Set General->Web->Default Cookie Settings->Cookie Lifetime to 60 seconds (this is only useful to speed up the testing time but the issue still exists with the default cookie lifetime
3. Sign in to Luma store with Demo Customer Access ([roni_cost@example.com](mailto:roni_cost@example.com)) WITH checkbox "Remember Me What's this?" ticked
4. Browse to any product and add to cart
5. Wait for cookie lifetime to expire simulating a customer's session timing out
6. Browse to homepage and refresh
7. Click on basket icon to display mini cart

### Expected result (*)

1. Mini cart should show previous product added to persistent cart (without having to add another product)

### Actual result (*)

1. Cart is empty
2. Click on 'View and Edit Cart' also displays empty cart
3. Previous cart contents are not displayed until another product is added to cart.  I believe if I recall correctly(?) this is different behaviour from earlier versions of Magento when the persistent cart contents were available immediately.  The Magento documentation is not explicit about the intended behaviour.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dphilipps** [comment]
Thanks @engcom-Delta good news.

FYI Another bug I have raised may be related https://github.com/magento/magento2/issues/35182

**Comment by engcom-November** [comment]
Hi @dphilipps 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-2619 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2619&type=commits
Based on the Jira ticket, the target version is 2.4.6.
Thank you.

**Comment by dphilipps** [comment]
Hi @engcom-November 
That's good news, and thanks - I appreciate the update.

Dave.
