### ISSUE TITLE
Google Universal Analytics will be EOL July 2023

### ISSUE THREAD

**Issue by rhoerr** [magento/magento2#35204]
### Summary (*)

Per https://support.google.com/analytics/answer/11583528 (at time of writing):

> ### Universal Analytics will be going away
> [Google Analytics 4](https://support.google.com/analytics/answer/10089681) is our next-generation measurement solution, and it's replacing Universal Analytics. On July 1, 2023, standard Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you [prepare to use Google Analytics 4](https://support.google.com/analytics/answer/10759417) going forward.
> 
> #### Understand what's going to happen
> Until July 1, 2023, you can continue to use and collect new data in your Universal Analytics properties.
> After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time.

Magento_GoogleAnalytics currently implements `analytics.js` and its associated `ga(...)` function calls. Based on the info above, starting 2023-07-01, that will become completely nonfunctional (no longer collecting data). Continuing to use Google Analytics services will require implementing Google Analytics 4, which uses `gtag.js` and `gtag(...)` calls with event-based tracking.

This affects all Magento and Adobe Commerce installations 2.0 to 2.4.

### Examples (*)

Magento_GoogleAnalytics currently uses `analytics.js` for Universal Analytics:

```
            (function (i, s, o, g, r, a, m) {
                i.GoogleAnalyticsObject = r;
                i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            // Process page info
            ga('create', config.pageTrackingData.accountId, 'auto');
```

Per above, in July 2023, this will stop collecting data and no longer function as intended.

### Proposed solution

Implement Google Analytics 4 far in advance of 2023-07-01 to allow merchants to transition to the new data collection platform.

Implementing GA4 will require total overhaul of the current implementation: https://support.google.com/analytics/answer/10119380?hl=en&ref_topic=11192706

### See also

Deprecation/EOL notice: https://support.google.com/analytics/answer/11583528
Migration guide: https://support.google.com/analytics/answer/10759417?hl=en&ref_topic=10737980
Previously reported in #12941

---

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Hotel** [comment]
Hello @rhoerr,

Thanks for posting the issue!

We have tried to reproduce the issue in Magento 2.4-develop branch and found that currently, Magento uses **Google Universal Analytics**, please refer to the below:

https://github.com/magento/magento2/blob/bbaa5284414191fafafe26acbc97186ff7ed93d1/app/code/Magento/GoogleAnalytics/view/frontend/web/js/google-analytics.js#L36

Hence confirming the issue.

Thanks

**Comment by Bashev** [comment]
This is already in development on this issue #32623

**Comment by sidolov** [comment]
Delivered in scope of https://github.com/magento/magento2/pull/35376
