### ISSUE TITLE
Category Product mapping

### ISSUE THREAD

**Issue by asyadav5** [magento/magento2#35203]
### Summary (*)

I have added a simple product in the Magento database from the backend which is coming on UI also when I am searching with the name but I am not able to add in category search, can anyone help me that in which table we need to create a mapping for the same
Magento ver. 2.4.3

I am new to Magento, I tried to find some solution on google but I did not get any relevant details, if anyone has any relevant link and blog where i can understand the backend workflow, kindly share

### Examples (*)

eg from the menu bar once we select the category then it should fetch the product which under that category

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @asyadav5,

You can map Category to a product from Admin Panel. Please have a look to the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/161733085-048559ed-4696-4241-9bd7-0110b44d5912.png)

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @asyadav5,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
