### ISSUE TITLE
Reindexing price takes hours when having many bundle products

### ISSUE THREAD

**Issue by ailovan** [magento/magento2#35213]
### Preconditions (*)
1. Magento version: 2.4.3
2. 84K products, of which 44K bundle products, each bundle with about 4-5 options (very small bundles)
3. VPS with 4 cores, 16 GB RAM, SSD
4. All third-party extensions disabled.
5. Search engine: ElasticSearch
6. MSI enabled
7. Smile ElasticSuite is used (but disabled for testing purposes for this issue)

### Steps to reproduce (*)
1. Reindex pricing, either from CLI or admin

### Expected result (*)
1. Reindexing the price index should take a few minutes. We have other Magento sites with a similar number of products (mostly simple, some configurable) and a similar hardware and software configuration where reindexing all indexes takes under 10 minutes

### Actual result (*)
1. Reindexing the price index takes over an hour. We tried this on 3 servers and the results seem to be the same.

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by juanmanuelcinto** [comment]
We have a similar issue on our site with 20k bundle products and 10k of simple.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch by adding 40K Bundle Products with 4 options for each bundle and Re-indexing Price didn't take long when ran from terminal:
![image](https://user-images.githubusercontent.com/60198231/162887241-456d3726-1bae-459e-bb9f-34a0777bb68d.png)
@ailovan , kindly recheck the issue on Magento 2.4-develop instance as it the upcoming 2.4.x release and elaborate steps if you are still facing issues.
Thank you.

**Comment by engcom-November** [comment]
Hi @ailovan ,
We are closing this issue as there has been no latest update on the same.
Thank you.
