### ISSUE TITLE
All the cookies should be in secure mode 

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35217]
**Description**
All the cookies on browser should be in secure mode.

### Preconditions (*)
 
1**. Magento version 2.4**

### Steps to reproduce (*)

1. setup the new magneto store and check the cookies are secured set or not in client end browser -> application -> cookies   
2.  

### Expected result (*)

1. [Screenshots, logs or description]
2.  i want to create more secure cookies from magento side 
![image](https://user-images.githubusercontent.com/98302784/159692715-108aee5d-36db-4ec7-88d7-10f4d3705055.png)

### Actual result (*)

1. [Screenshots, logs or description]
2. there is no Error  
 
Screenshots: 
<img width="1440" alt="cookies_1" src="https://user-images.githubusercontent.com/51681379/166677322-a1e4ef0f-d56a-4073-9fd4-434c88b07399.png">

<img width="1440" alt="cookies_2" src="https://user-images.githubusercontent.com/51681379/166677535-155e0765-cd78-433b-aa20-8d5689a51fb9.png">

**Comment by Sanjay-100** [comment]
Summary of the issue  : i want to add more cookies to batter user UX 
Information on your environment : magneto 2  php 7.4 xammp and LEMP stack
Steps to reproduce ; create new magneto instance 
Expected and actual results : same as above screenshot admin secured cookies created.

**Comment by engcom-Delta** [comment]
Hi @Sanjay-100 ,
Thank you for raising an issue . Kindly can you elaborate on actual results what you have got.
Screenshots are more helpful for actual results if possible .
Hence added label 'Needs Update'

**Comment by Sanjay-100** [comment]
Hi magneto admin dashboard  cookies creating the secure without the SSL certificate   
you see the my screenshot from magneto dashboard.   i can see the magneto admin site magneto create secure cookies  i want the all fronted cookies also as secure cookies. 

does this can done use of magneto admin settings ?

![image](https://user-images.githubusercontent.com/98302784/159913452-b623bf6f-a669-4659-a6d9-6fd0b64e6858.png)


 i tried to made settings but not working

**Comment by Sanjay-100** [comment]
@engcom-Delta 
if i do the  NO 
**Use HTTP Only** | Yes No Warning: Do not set to "No". User security could be compromised.
-- | --


what can be effect ?

i want to read the some cookies for analytics propose. 

I think batter way to create modules and make custom cookies that was batter option ?

**Comment by engcom-Delta** [comment]
Hi @Sanjay-100 ,

Thank you for providing the required information. We tried to reproduce the issue on Magento 2.4 Develop & 2.4.3-p1 instance. We could not find out secure cookies on admin page and frontend page. Hence confirming the issue.
in Admin Page "Use HTTP only "field settings to 'YES':
<img width="1440" alt="Screenshot 2022-04-06 at 1 03 35 PM" src="https://user-images.githubusercontent.com/51681379/161926140-a5f3f4ec-c452-4640-800c-d8752db57393.png">

Results:
<img width="1440" alt="Screenshot 2022-04-06 at 1 00 56 PM" src="https://user-images.githubusercontent.com/51681379/161926385-9c22d50c-bbb2-4902-943b-69ba87280a88.png">
<img width="1440" alt="Screenshot 2022-04-06 at 1 12 05 PM" src="https://user-images.githubusercontent.com/51681379/161926464-5d3b739f-3839-4378-9320-4338c360b6df.png">
<img width="1440" alt="Screenshot 2022-04-06 at 1 15 22 PM" src="https://user-images.githubusercontent.com/51681379/161926472-5e068dee-2d98-4f75-af87-f5a0552bf7f6.png">


in Admin Page "Use HTTP only "field settings to 'NO':
<img width="1440" alt="Screenshot 2022-04-06 at 1 26 41 PM" src="https://user-images.githubusercontent.com/51681379/161927814-047fc1bc-4ead-46e8-92f3-d59f483cc4d3.png">

Results:
<img width="1440" alt="Screenshot 2022-04-06 at 1 28 15 PM" src="https://user-images.githubusercontent.com/51681379/161928014-49149107-2b65-4bff-95d5-0bbca63f87fe.png">
<img width="1440" alt="Screenshot 2022-04-06 at 1 30 10 PM" src="https://user-images.githubusercontent.com/51681379/161928478-a757b069-b762-47c3-ae7b-df4ac0a2e3cd.png">

**Comment by Sanjay-100** [comment]
@engcom-Delta I need all the cookies are secured need all cookies are secured. ticks.

You can see my expected result with some cookies are secured some of now secured but I want all of them secured.

**Comment by engcom-Hotel** [comment]
Hello @engcom-Delta,

We are marking this issue as `on hold`, because it seems a specific requirement. We need a PO confirmation on this.

Thanks

**Comment by Sanjay-100** [comment]
@engcom-Hotel  @engcom-Delta 

this is not specific if any user chooses the secure cookies from the magneto admin settings  => store configuration -> web -> default cookies settings here is not an option for secure cookies.
AS per the google guide we need all cookies stored in secure cookies only I can see some of the cookies are stored insecurely some of the cookies are not stored as secure cookies. 

I hope this detail helps you understand the magneto cookies store insecurely

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @Sanjay-100 ,

We have verified this issue on  "https". Here are the test results.

1. Set Use HTTP Only to 'YES' [Stores--> Configuration --> General --> Default Cookie Settings

<img width="1440" alt="Screenshot 2022-05-04 at 5 39 00 PM" src="https://user-images.githubusercontent.com/51681379/166680782-5f0cd922-4eeb-457e-9ffa-e8e6ab27b5a3.png">

2. Verify the cookies

**in Backend(Admin) few cookies secured but not all** 

<img width="1440" alt="Screenshot 2022-05-04 at 5 42 58 PM" src="https://user-images.githubusercontent.com/51681379/166681051-9d0721db-0d6f-4bf9-b69e-cbccdff42698.png">

**in Frontend all cookies are not in secure** 

<img width="1440" alt="Screenshot 2022-05-04 at 5 45 44 PM" src="https://user-images.githubusercontent.com/51681379/166681228-abc25691-d32a-484f-9a57-1a752caa6812.png">

2. Set Use HTTP Only to 'NO' [Stores--> Configuration --> General --> Default Cookie Settings

<img width="1440" alt="Screenshot 2022-05-04 at 5 51 34 PM" src="https://user-images.githubusercontent.com/51681379/166681467-0367eefe-e0fd-4b1a-a726-61036720678e.png">

<img width="1440" alt="Screenshot 2022-05-04 at 5 45 44 PM" src="https://user-images.githubusercontent.com/51681379/166681612-db02136d-c95d-4150-9c11-b1c2110e6807.png">

**Comment by engcom-Delta** [comment]
Hi @Sanjay-100 ,
Issue has been moved to 'On Hold' status due to confirmation from Product Owner.

Thanks
