### ISSUE TITLE
Backend javascript not working

### ISSUE THREAD

**Issue by luc-anise** [magento/magento2#3521]
So I just installed magenta and ran the deploy command. I've been having problems with permissions but I believe I have them all sorted out. What's really weird is that all the files are intact there and the permissions are 100% right as far as I can tell. This is a bit of a problem because I'm unable to use most of the buttons (basically every thing that isn't navigation) to save categories, products, etc and it's not loading data either so it won't display the pages, block, etc that exist. This is some ward urgent so thanks in advance!
![magento_error](https://cloud.githubusercontent.com/assets/6894830/13274841/87126522-da7c-11e5-9b99-a40735d6b222.png)

**Comment by luc-anise** [comment]
This seems have to fixed it's self. Perhaps I didn't wait long enough after running the deploy command. any insight? would still like to help anyone who comes across this post! All so is there no nav if you don't have the sample data or where is mine?? ([shop.studioanise.com](http://shop.studioanise.com))

**Comment by maksek** [comment]
Hi @z6tanker, GitHub for issue reporting and PR publication. Seems like you do not have issue, and website works as expected. For particular questions please use Magento forum. https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2
