### ISSUE TITLE
Bulk Update Attributes - datetime doesn't extend \Magento\Framework\Data\Form\Element\AbstractElement

### ISSUE THREAD

**Issue by timpea** [magento/magento2#35214]
### Preconditions (*)
1. Magento 2.4.3

### Steps to reproduce (*)
1. Add a datetime product attribute
2. Assign attribute to Default attribute set. 
3. Catalog>Products: Update Attributes on 1 or more products 

### Expected result (*)

1. Ability to update product attributes

### Actual result (*)
1. Update attributes page fails to load
1. [2022-03-22 12:04:34] main.CRITICAL: datetime doesn't extend \Magento\Framework\Data\Form\Element\AbstractElement {"exception":"[object] (InvalidArgumentException(code: 0): datetime doesn't extend \\Magento\\Framework\\Data\\Form\\Element\\AbstractElement at /public/vendor/magento/framework/Data/Form/Element/Factory.php:83)"} []

[ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by timpea** [comment]
@magento give me 2.4-develop instance

**Comment by timpea** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @timpea ,
We tried to reproduce the issue on Magento 2.4 Develop with latest branch , unfortunately issue is not reproducible.
Hence request to review the provided steps.

steps followed:
1. Add a datetime product attribute
<img width="1440" alt="Screenshot 2022-03-22 at 5 49 20 PM" src="https://user-images.githubusercontent.com/51681379/159482382-7cd8302a-30c4-455b-b2a5-ac84219a27e9.png">
2. Assign attribute to Default attribute set.
<img width="1440" alt="Screenshot 2022-03-22 at 5 55 17 PM" src="https://user-images.githubusercontent.com/51681379/159482445-bc660d9f-191d-4f2f-b106-b719ea139a1b.png">
3. Catalog>Products: Update Attributes on 1 or more products

Actual : Attributed are updated without any error.
Please find below screenshots for reference.
<img width="1440" alt="Screenshot 2022-03-22 at 5 58 03 PM" src="https://user-images.githubusercontent.com/51681379/159482711-4950e229-6d69-470a-9e62-7e5987cb736e.png">
<img width="1440" alt="Screenshot 2022-03-22 at 5 58 20 PM" src="https://user-images.githubusercontent.com/51681379/159482737-58f9abed-e95f-4a12-9b74-bfa7a1c4de99.png">

Hence, added the label 'Needs Update'

**Comment by timpea** [comment]
@magento give me 2.4-develop instance

**Comment by timpea** [comment]
@engcom-Delta try the bulk update attributes page:
![Screenshot 2022-03-22 at 12 56 51](https://user-images.githubusercontent.com/4026115/159487254-e1e8d123-2982-4b45-ad18-c1b2154ad3e5.png)

**Comment by feling07** [comment]
I have the same issue. Any update?

**Comment by engcom-Delta** [comment]
Hi @timpea ,
Thanks for quick turn around. tried again in Magento 2.4 Develop. We are able to do Bulk update attributes. 
Not getting any errors the page. Hence request to review the provided steps.
<img width="1440" alt="Screenshot 2022-03-25 at 6 37 54 AM" src="https://user-images.githubusercontent.com/51681379/160036796-69a6c27e-5fc0-4300-9a92-97e6e8450b2f.png">
<img width="1440" alt="Screenshot 2022-03-25 at 6 51 30 AM" src="https://user-images.githubusercontent.com/51681379/160036821-6eacb934-dae3-43cf-80b6-6735e196ce76.png">
<img width="1440" alt="Screenshot 2022-03-25 at 6 51 45 AM" src="https://user-images.githubusercontent.com/51681379/160036830-3f8084ec-1e88-48f3-8bdc-f8bc98733104.png">

in Magento 2.4.3.p1 insance also verified ,it works fine.
<img width="1440" alt="Screenshot 2022-03-25 at 6 59 43 AM" src="https://user-images.githubusercontent.com/51681379/160037154-a218d4cf-66cd-401a-a431-01ac8f184d08.png">
<img width="1440" alt="Screenshot 2022-03-25 at 7 00 32 AM" src="https://user-images.githubusercontent.com/51681379/160037171-b67b9fec-1258-4dd0-b8a4-11e163a00a9e.png">
<img width="1440" alt="Screenshot 2022-03-25 at 7 01 02 AM" src="https://user-images.githubusercontent.com/51681379/160037225-aec25cbd-b7da-4c10-bf87-4be80a89bf3c.png">

**Comment by timpea** [comment]
@magento give me 2.4-develop instance

**Comment by timpea** [comment]
@engcom-Delta It looks like you are updating a Date field, it is the DateTime attribute that is causing the error for us.  I haven't tested it on a fresh install of 2.4.3-p1, but we are getting this error on our live and staging sites running 2.4.3-p1.

I have just tested it in the Develop version and it is working as expected.

**Comment by feling07** [comment]
Hi Timpea, I checked all the data in eav_attribute and found the one using backend_type datetime and frontend_input datetime. After updating the frontend input to date the error is gone and it seems all working fine. I'm not sure if yours would be similar but in frontend there's no element for the type of datetime that's why it throws the error for me. Hope this helps.

**Comment by timpea** [comment]
@feling07 thank you, I was able to get around it by using the Date attribute, we didn't really need DateTime, it was only for a last_stock_checked field so we could record when we last checked the stock levels of each product.

**Comment by engcom-Delta** [comment]
Hi @timpea ,
Kindly try on fresh instance of 2.4.3-p1 and confirm.

Thanks

**Comment by timpea** [comment]
@magento give me 2.4.3-p1 instance

**Comment by timpea** [comment]
@magento give me 2.4.3-p1 instance

**Comment by timpea** [comment]
@magento give me 2.4.3-p1 instance

**Comment by timpea** [comment]
@magento give me 2.4.3-p1 instance

**Comment by timpea** [comment]
@magento give me 2.4.3-p1 instance

**Comment by engcom-Delta** [comment]
Hi @timpea ,
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Comment by visahardik** [comment]
@magento I am facing the same issue in M2.4.3-p1 instance while trying to bulk attribute update

**Comment by timpea** [comment]
@visahardik it appears to be fixed in 2.4.4 - https://github.com/magento/magento2/commit/90334d932f24dc1fe200e1b7e1262827e48c82c6
