### ISSUE TITLE
Magento2 REST APIs Quote Currency Issue

### ISSUE THREAD

**Issue by reshadzazai** [magento/magento2#35212]
I have a single website, with 2 stores and 2 store-views, one store-view for each store:
![image](https://user-images.githubusercontent.com/60198231/161557864-d1d68076-b4c1-4aea-bf1d-a3a0ae1a1b2c.png)

Admin - Stores - Configuration - General - Currency Setup - Currency Options - US
Change scope to Australian English - set Currency to Australian Dollar and Save
Change scope to American English - set Currency to American Dollar and Save
(The base currency is USD at the global scope and the display currency for store-view en_us is USD and en_au in AUD.)

API POST request: Create Customer Access token using /rest/all/V1/integration/customer/token

 2. Create a cart:
`POST https://example.com/rest/en_us/V1/carts/mine`

2. Add a product to the cart:
` POST https://example.com/rest/en_us/V1/carts/mine/items`

```
{
  "cartItem": {
    "sku": "Product-1040",
    "qty": 1,
    "quote_id": 22980
    
  }
}
```
3. Get your cart:
 `   GET https://example.com/rest/en_us/V1/carts/mine`

```
"currency": {
        "global_currency_code": "USD",
        "base_currency_code": "USD",
        "store_currency_code": "USD",
        "quote_currency_code": "USD",
        "store_to_base_rate": 0,
        "store_to_quote_rate": 0,
        "base_to_global_rate": 1,
        "base_to_quote_rate": 1
    },
```
4. Access the same cart from a different store-view Ex. en_au where display currency is AUD but quote_currency_code is still shown as USD.

```
GET https://example.com/rest/en_au/V1/carts/mine
"currency": {
        "global_currency_code": "USD",
        "base_currency_code": "USD",
        "store_currency_code": "USD",
        "quote_currency_code": "USD",
        "store_to_base_rate": 0,
        "store_to_quote_rate": 0,
        "base_to_global_rate": 1,
        "base_to_quote_rate": 1
    },
```
But if you switch store-view to en_au from the browser the quote_currency_code changes to AUD because this plugin gets executed
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\Quote\Plugin;

use Magento\Checkout\Model\Session;
use Magento\Quote\Model\QuoteRepository;
use Magento\Store\Api\Data\StoreInterface;
use Magento\Store\Model\StoreSwitcherInterface;

/**
 * Updates quote items store id.
 *
 * @SuppressWarnings(PHPMD.CookieAndSessionMisuse)
 */
class UpdateQuoteItemStore
{
    /**
     * @var QuoteRepository
     */
    private $quoteRepository;

    /**
     * @var Session
     */
    private $checkoutSession;

    /**
     * @param QuoteRepository $quoteRepository
     * @param Session $checkoutSession
     */
    public function __construct(
        QuoteRepository $quoteRepository,
        Session $checkoutSession
    ) {
        $this->quoteRepository = $quoteRepository;
        $this->checkoutSession = $checkoutSession;
    }

    /**
     * Update store id in active quote after store view switching.
     *
     * @param StoreSwitcherInterface $subject
     * @param string $result
     * @param StoreInterface $fromStore store where we came from
     * @param StoreInterface $targetStore store where to go to
     * @param string $redirectUrl original url requested for redirect after switching
     * @return string url to be redirected after switching
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterSwitch(
        StoreSwitcherInterface $subject,
        $result,
        StoreInterface $fromStore,
        StoreInterface $targetStore,
        string $redirectUrl
    ): string {
        $quote = $this->checkoutSession->getQuote();
        if ($quote->getIsActive()) {
            $quote->setStoreId(
                $targetStore->getId()
            );
            $quote->getItemsCollection(false);
            $this->quoteRepository->save($quote);
        }
        return $result;
    }
}

```
**Expected Result:** 
The `quote_currency_code` is changed when the REST API is called from en_au store-view?

**Actual Result:**
Calling 
`GET https://example.com/rest/en_au/V1/carts/mine/payment-information`
 returns totals in USD where it should have provided them in AUD.
Get payment information in en_au store-view: quote_currency_code still shown as USD where it had to be AUD
Note: This behavior is only for the REST APIs, From UI - change the store in the website and call the same API again, this time you will see the quote_currency_code in AUD and the amount as A$60.75 

```
"totals": {
        "grand_total": 100,
        "base_grand_total": 100,
        "subtotal": 100,
        "base_subtotal": 100,
        "discount_amount": 0,
        "base_discount_amount": 0,
        "subtotal_with_discount": 100,
        "base_subtotal_with_discount": 100,
        "shipping_amount": 0,
        "base_shipping_amount": 0,
        "shipping_discount_amount": 0,
        "base_shipping_discount_amount": 0,
        "tax_amount": 0,
        "base_tax_amount": 0,
        "weee_tax_applied_amount": null,
        "shipping_tax_amount": 0,
        "base_shipping_tax_amount": 0,
        "subtotal_incl_tax": 100,
        "shipping_incl_tax": 0,
        "base_shipping_incl_tax": 0,
        "base_currency_code": "USD",
        "quote_currency_code": "USD",........
```

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
For any Store view set - currency codes and values are changed only when Base Currency is changed but not display currency in both UI and API as well.
![image](https://user-images.githubusercontent.com/60198231/159627615-57991a55-846a-4c86-89ea-bed79e24ad97.png)
![image](https://user-images.githubusercontent.com/60198231/159627710-66e05ed9-cbc2-4b82-841a-06af24a5a8b3.png)

![image](https://user-images.githubusercontent.com/60198231/159627420-cf23ebfd-6636-4c1a-958c-c8ae213412fa.png)
If Base Currency is changed from configuration, values and currency are displayed in AUD for any store view in both UI and API response.
@reshadzazai , kindly recheck the behavior on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base. Elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by reshadzazai** [comment]
Can I get an instance with Magento 2.4-develop branch and I will do the necessary configurations in the admin panel and write down the step to reproduce the issue?

**Comment by engcom-November** [comment]
Hi @reshadzazai ,
Please write a comment to this issue: "@magento give me 2.4-develop instance" to get  magento 2.4-develop instance. Please note that it has limited access. Try again after sometime if you are unable to get the instance at that moment.
Thank you.

**Comment by reshadzazai** [comment]
@magento give me 2.4-develop instance

**Comment by reshadzazai** [comment]
Step 1. Create a cart in en_us store-view
![Screenshot_1](https://user-images.githubusercontent.com/20941245/160226983-c3d7dac9-0e38-4e15-9301-488d100b0306.jpg)

Step 2. Add a product to the cart in en_us store-view
![Screenshot_2](https://user-images.githubusercontent.com/20941245/160227000-d3871407-fb00-4d9b-8fac-7655538487c9.jpg)

Step 3. Get Payment Information in en_us store-view: Everything is fine
![Screenshot_3](https://user-images.githubusercontent.com/20941245/160227013-9c6e7307-41f5-423c-b329-af41e73aa851.jpg)

Step 4. Get payment information in `en_au` store-view: `quote_currency_code` still shown as **USD** where it had to be **AUD**, the amount is **$45** where it had to be **A$60.75** according to 1.349891 currency rate.

![Screenshot_4](https://user-images.githubusercontent.com/20941245/160227049-3edb25dc-bebb-4cef-a689-4ad3a65e907d.jpg)

**Note:** This behavior is only for the REST APIs, change the store in the website and call the same API again, this time you will see the `quote_currency_code` in **AUD** and the amount as **A$60.75** , check the screenshots below:

![Screenshot_5](https://user-images.githubusercontent.com/20941245/160227273-62cd574b-2141-4531-b823-d34b4b483b51.jpg)

![Screenshot_6](https://user-images.githubusercontent.com/20941245/160227291-d5f20fe5-ebe9-459d-9ab1-c537766d4e3b.jpg)

**Comment by reshadzazai** [comment]
**My configurations**

![Screenshot_7](https://user-images.githubusercontent.com/20941245/160227391-ec568c26-adb6-44db-addb-e72e49b4bf60.jpg)

![Screenshot_8](https://user-images.githubusercontent.com/20941245/160227394-1397f866-8689-446f-a235-055e72f9f8ae.jpg)

![Screenshot_9](https://user-images.githubusercontent.com/20941245/160227397-2fb34249-36c9-4c0d-aa46-4e9cdbf266aa.jpg)

![Screenshot_10](https://user-images.githubusercontent.com/20941245/160227402-9110c62a-4631-4eb2-8cd1-7a37e26515a6.jpg)

![Screenshot_11](https://user-images.githubusercontent.com/20941245/160227428-4ef1d41f-6955-4b97-9c57-a155235e0c0b.jpg)

**Comment by reshadzazai** [comment]
@engcom-November You have not checked the issue base on my description.

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Thanks for your inputs @reshadzazai ,
Verified the issue again on Magento 2.4-develop branch and the issue is reproducible. Hence updating the description and confirming the issue.

**Comment by engcom-Alfa** [comment]
We have to update the this ticket based on our internal discussion further updates. Needs to be cross checked the internal ticket discussion comments given [HERE](https://jira.corp.magento.com/browse/AC-2756?focusedCommentId=1858239&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1858239).

**Comment by engcom-Alfa** [comment]
As per the given [comment](https://github.com/magento/magento2/issues/26664#issuecomment-581439963), this is not an issue.
Additionally please refer my above analysis as GET method should not be responsible for updating Quote.
There is a dedicated PUT method for the same.
[Reference](https://magento.redoc.ly/2.4.4-customer/tag/cartsmine/#operation/quoteCartRepositoryV1SavePut) for PUT method to update the cart.
Based on this information, currently the ticket is being closed.

In case of any Magento related issues found in the latest Magento `2.4-develop`, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).
