### ISSUE TITLE
How I can view the magento store system information?

### ISSUE THREAD

**Issue by devphoenix2404** [magento/magento2#35221]
Hi team,

I want to know, how I can view the Magento store system information from the Magento back-end like which mysql version is used by the store?

Thanks

**Comment by engcom-November** [comment]
Hi @devphoenix2404 ,
Thank you for reporting and collaboration. All 2.4.x versions of Magento require Mysql 8 version. Kindly refer the [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) of all compatible versions that is required for specific magento version.
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/prereq-overview.html
Thank you.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
