### ISSUE TITLE
magento 2 catalog search full text programmatically

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35229]
### Summary (*)
 magento 2 catalog search full text programmatically

### Examples (*)
 i want to tracker the search result for every customer who do the search. and magento search result i wan to capture all the search data  i already did the custom plugin 

### Proposed solution
 
 i build the custom modules -  i used the event observer i am getting the user search query 
 
 `<?php

namespace Sanjay\Search\Observer;

use Magento\Framework\View\Page\Config;
use Magento\Framework\Event\Observer as EventObserver;
use Magento\Framework\Event\ObserverInterface;
use Magento\Catalog\Model\Category;
use Magento\Search\Model\QueryFactory;
use Netcore\Cee\Logger\Logger;

class Searchdispatch implements ObserverInterface
{

    /**
     * @var \Magento\Framework\View\LayoutInterface
     */
    protected $_layout;

    /**
     * @var \Magento\Store\Model\StoreManagerInterface
     */
    protected $_storeManager;

    protected $_eventManager;

    protected $_queryFactory;

    protected $_request;

    protected $collection;
    private $logger;

    public function __construct(
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Framework\View\LayoutInterface $layout,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\Framework\App\RequestInterface $request,
        \Magento\Search\Model\QueryFactory $queryFactory,
        Config $config,
        Logger $logger,
        \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection $collection,
        \Netcore\Cee\Helper\Data $helper
    ) {
         
    
        $this->_layout       = $layout;
        $this->_storeManager = $storeManager;
        $this->_request      = $request;
        $this->_eventManager = $eventManager;
        $this->_queryFactory = $queryFactory;
        $this->config        = $config;
        $this->collection    = $collection;
        $this->helper        = $helper;
        $this->logger        = $logger;
    }//end __construct()

    public function execute(EventObserver $observer)
    {
        $str    = $search = $json = '';
        $search = $this->_request->getParam('q');
        // print_r($search);
        
        $productIdList  = [];
        // $this->collection->load();
        // print_r(get_class_methods($this->_queryFactory));
        $query = $this->_queryFactory->get();
        // dd($query);
        // dd(get_class_methods($query));
        if (!$query->isQueryTextShort()) {
            // dd($query->isQueryTextShort());
            // dd($this->collection->addSearchFilter($query->getQueryText()));
            // print_r($collection_res);
        }
        // print_r("Search ");
        // dd($query);`
 
 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Sanjay-100** [comment]
**Summary of the issue**  : need to store the all search event data into database i am using the custom modules for that with magento event and observers 
**Information on your environment** : magento 2.4 LEMP stack
Steps to reproduce : use any magneto in instance 
Expected and actual results : need the complete search result then store to database.

**Comment by Sanjay-100** [comment]
@engcom-Hotel 

Summary of the issue  : i want to store the all search query with result data into database.
Information on your environment : Magneto 2 with elastic search
Steps to reproduce : setup new magneto assistance from GitHub.  
Expected and actual results : same as Magneto store  front search result i need to capture into the  modules log.

here is the modules code  you can test on your end.
https://github.com/Sanjay-100/magento2_search

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

This is the the General issue board for Magento. As per your comment in the main description, it seems its a new feature which is required by any specific merchant but not for all.

Please let us know your thoughts on it.

Thanks

**Comment by Sanjay-100** [comment]
@engcom-Hotel   I am not talking about the new feature I want to use the same Magento 2. X search in my custom modules.
I need to use the search feature same as the frontend to my custom programming method.

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

Sorry but we are not able to get the comment you made [here](https://github.com/magento/magento2/issues/35229#issuecomment-1089926184). Can you please elaborate this?

Thanks

**Comment by Sanjay-100** [comment]
@engcom-Hotel   Summary of the issue: I have to use the same search feature as of now storefront need to add into Magento modules  I added my code in a git repo https://github.com/Sanjay-100/magento2_search
Information on your environment: Magneto 2 with elastic search
Steps to reproduce : set up new magneto assistance from GitHub.
Expected and actual results: same as Magneto store front search result I need to capture into the modules log. I added my code in a git repo https://github.com/Sanjay-100/magento2_search

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

It seems that you need to create a new module in magento and implement the above functionality. For this please refer this [article](https://devdocs.magento.com/videos/fundamentals/create-a-new-module/).

Thanks

**Comment by Sanjay-100** [comment]
@engcom-Hotel   Yes I already build the modules but still, I am not able to perform the search into a plugin  can you please  see this code or provide me an article there has working search operation 

https://github.com/Sanjay-100/magento2_search/blob/main/Observer/Searchdispatch.php

here demo modules code I build you can test this one  https://github.com/Sanjay-100/magento2_search

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

We request you to please tell us the exact issue/error you are getting while using this module.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by Sanjay-100** [comment]
@engcom-Hotel  Hi sorry for the dealy

@engcom-Hotel Yes I already build the modules but still, I am not able to perform the search into a plugin can you please see this code or provide me an article there has working search operation

https://github.com/Sanjay-100/magento2_search/blob/main/Observer/Searchdispatch.php

here demo modules code I build you can test this one https://github.com/Sanjay-100/magento2_search

**I want to use the Magento search result into the my Magento modules code**
