### ISSUE TITLE
Mage2 cache_dir

### ISSUE THREAD

**Issue by anjenehm** [magento/magento2#3522]
@mazhalai so now you see that this error displays on a mage2 setup!
![image](https://cloud.githubusercontent.com/assets/7089704/13279424/067a5f9e-dad8-11e5-9995-fe2db9f99357.png)

**Comment by anjenehm** [comment]
I cant add a product or something else 

just blank areas

![image](https://cloud.githubusercontent.com/assets/7089704/13283110/81853538-daec-11e5-9639-f86f09cc64c9.png)

**Comment by mazhalai** [comment]
@anjenehm is this still on Gentoo? We have not tested on all flavors of linux, officially only Centos and Ubuntu are supported.

**Comment by anjenehm** [comment]
@mazhalai yes still on gentoo

**Comment by anjenehm** [comment]
![image](https://cloud.githubusercontent.com/assets/7089704/13303812/ada6536c-db51-11e5-9ae7-65d53217c9bd.png)

**Comment by anjenehm** [comment]
@mazhalai you told me in the old ticket https://github.com/magento/magento2/issues/3424 when i set in setup/src/Magento/Setup/Validator/DbValidator.php after the query "checkDatabasePrivileges" to return true, that magento wouldnt be fully functional. What did that mean? 

a other mysterious thing is that the backend url is www.mydomain.com/admin/admin/dashboard/index/key/

**Comment by mazhalai** [comment]
If you have a db user without the required permissions, how can you expect all db functions to work?

What is mysterious about the backend url?

**Comment by anjenehm** [comment]
Sure.... Maybe i should take a look for a new hoster

The url should be like domain.com/admin/dashboard and not doubled /admin/admin, or not?

**Comment by anjenehm** [comment]
@mazhalai can you tell me concretely what functions would not work?

**Comment by mazhalai** [comment]
Any db commands with the ones listed under [requiredPrivileges](https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L140) 

Double admin shows up, since you selected admin as your backend-frontname, by default it is `admin_<some random string>` for e.g. `admin_1xx7xi`, then urls shows as `admin_1xx7xi/admin/`

**Comment by anjenehm** [comment]
So @mazhalai can you give me a update to my error?

**Comment by anjenehm** [comment]
Couldn’t create cache_dir error. If you have cache_dir error in magento 1 and magento 2, goto the [Magento_Root]/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php on your magento site.

Now edit this file and goto line no. 99 and you will see cache dir is assign to null

‘cache_dir’ => null,

Add var in place of null and save file

‘cache_dir’ => ‘var’

Now you have assign the magento root var dir as a cache dir for your magento store.

this helped!
