### ISSUE TITLE
Cannot Navigate Magento 2 after logging in

### ISSUE THREAD

**Issue by imeechan** [magento/magento2#35230]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @imeechan ,
Thank you for reporting and collaboration. However, provided steps are not enough for us to reproduce the issue on Magento 2.4-develop branch. Kindly elaborate the issue and steps to reproduce.
Please check if magento setup is done as per the the [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and [prerequisiteshttps](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/prereq-overview.html)
Thank you.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 13 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
