### ISSUE TITLE
Magento EE 2.0.2 admin gets into infinite loop. 

### ISSUE THREAD

**Issue by shashidharg** [magento/magento2#3523]
Hello,

I installed Magento EE 2.0.2 version on my windows desktop, this one was with sample data. The setup went on fine and the home page and other non admin pages are loading fine. But my admin page goes into infinite loop.
My setup is with a virtual host entry http://mage2ee:8585/.

I have tried with Chrome and IE but with no luck, can someone please help me out here?

Note: Port 80 is not free so I had to use an alternative port.

Thanks & Regards,
Shashidhar.G

**Comment by mazhalai** [comment]
@shashidharg please do not post EE related issues here, this is for CE issues only. Please report it via partner portal.

**Comment by shashidharg** [comment]
@mazhalai, did not realize it. Thanks :)
