### ISSUE TITLE
Uncaught Exception: Warning: fwrite(): SSL operation failed with code 1.

### ISSUE THREAD

**Issue by hassanas** [magento/magento2#35235]
Magento 2.4 is using this module facinf error while sending success email:

`error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown in /app/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php on line 253 in
 /app/vendor/magento/framework/App/ErrorHandler.php:61`

Stack trace:
```
#0 [internal function]: Magento\Framework\App\ErrorHandler-&gt;handler()
#1 /app/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php(253): fwrite()
#2 /app/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(454): Laminas\Mail\Protocol\AbstractProtocol-&gt;_send()
#3 /app/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(493): Laminas\Mail\Protocol\Smtp-&gt;quit()
#4 /op in <b>/app/vendor/magento/framework/App/ErrorHandler.php</b> on line <b>61</b><br />

```

**Comment by engcom-Delta** [comment]
Hi @hassanas ,
Thank you for raising an issue. Kindly provide steps to reproduce , actual results , expected results and screenshots for reference. Hence added 'Needs update' Label

Regards,
