### ISSUE TITLE
The Stripe PHP library has not been installed.

### ISSUE THREAD

**Issue by haroonsulahri** [magento/magento2#35242]
Hi,
i install a stripe extension.But admin panel show error msg.Please help me..
![image](https://user-images.githubusercontent.com/102534997/160422518-dd9a41d2-5332-4344-85fc-df926316d79c.png)
thank you
sincerly
Haroon S.

**Comment by haroonrajpoot** [comment]
My site frontend checkout page show error masg
Could not initialize Stripe.js: Please call Stripe() with your publishable key. You used an empty string.
![image](https://user-images.githubusercontent.com/102534997/160423456-364744ee-34df-4492-b1f6-d96e8638198e.png)

**Comment by engcom-Delta** [comment]
Hi @haroonrajpoot ,
Thank you raising an issue. Kindly provide steps to reproduce, actual results, expected results and screenshots for reference.
Hence added the label 'Needs update'.
Regards,

**Comment by engcom-Delta** [comment]
Hi @haroonrajpoot ,
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

Thanks
