### ISSUE TITLE
Configurable product in order via /rest/V1/orders/:id showing wrong product type

### ISSUE THREAD

**Issue by algostore** [magento/magento2#3524]
Magento 2.0.1 + sample data.

Returned:
 {"base_currency_code":"EUR","base_discount_amount":0,"base_grand_total":32.05,"base_discount_tax_compensation_amount":0,"base_discount_tax_compensation_invoiced":null,"base_discount_tax_compensation_refunded":null,"base_shipping_amount":15,"base_shipping_discount_amount":0,"base_shipping_discount_tax_compensation_amnt":null,"base_shipping_incl_tax":15,"base_shipping_tax_amount":0,"base_subtotal":15.75,"base_subtotal_incl_tax":17.05,"base_tax_amount":1.3,"base_total_due":32.05,"base_to_global_rate":1,"base_to_order_rate":1,"billing_address_id":11,"created_at":"2016-02-22 15:22:43","customer_email":"xxxx@xxx.nl","customer_firstname":"Veronica","customer_gender":0,"customer_group_id":1,"customer_id":1,"customer_is_guest":0,"customer_lastname":"Costello","customer_note_notify":1,"discount_amount":0,"email_sent":1,"entity_id":6,"global_currency_code":"EUR","grand_total":32.05,"discount_tax_compensation_amount":0,"discount_tax_compensation_invoiced":null,"discount_tax_compensation_refunded":null,"increment_id":"000000006","is_virtual":0,"order_currency_code":"EUR","protect_code":"302189","quote_id":9,"shipping_amount":15,"shipping_description":"Best Way - Table Rate","shipping_discount_amount":0,"shipping_discount_tax_compensation_amount":0,"shipping_incl_tax":15,"shipping_tax_amount":0,"state":"new","status":"pending","store_currency_code":"EUR","store_id":1,"store_name":"Main Website\nMain Website Store\n","store_to_base_rate":0,"store_to_order_rate":0,"subtotal":15.75,"subtotal_incl_tax":17.05,"tax_amount":1.3,"total_due":32.05,"total_item_count":1,"total_qty_ordered":1,"updated_at":"2016-02-22 15:22:48","weight":0,"items":[{"amount_refunded":0,"base_amount_refunded":0,"base_discount_amount":0,"base_discount_invoiced":0,"base_discount_tax_compensation_amount":0,"base_discount_tax_compensation_invoiced":null,"base_discount_tax_compensation_refunded":null,"base_original_price":14,"base_price":15.75,"base_price_incl_tax":17.05,"base_row_invoiced":0,"base_row_total":15.75,"base_row_total_incl_tax":17.05,"base_tax_amount":1.3,"base_tax_invoiced":0,"created_at":"2016-02-22 15:22:43","discount_amount":0,"discount_invoiced":0,"discount_percent":0,"free_shipping":0,"discount_tax_compensation_amount":0,"discount_tax_compensation_canceled":null,"discount_tax_compensation_invoiced":null,"discount_tax_compensation_refunded":null,"is_qty_decimal":0,"is_virtual":0,"item_id":7,"name":"Sprite Yoga Strap 6 foot","no_discount":0,"order_id":6,"original_price":14,"price":15.75,"price_incl_tax":17.05,"product_id":11363**,"product_type":"grouped",**"qty_canceled":0,"qty_invoiced":0,"qty_ordered":1,"qty_refunded":0,"qty_shipped":0,"quote_item_id":13,"row_invoiced":0,"row_total":15.75,"row_total_incl_tax":17.05,"row_weight":0,"sku":"24-WG085","store_id":1,"tax_amount":1.3,"tax_invoiced":0,"tax_percent":8.25,"updated_at":"2016-02-22 15:22:43"}],"billing_address":{"address_type":"billing","city":"Calder","country_id":"US","customer_address_id":1,"email":"xxxx@xxx.nl","entity_id":11,"firstname":"Veronica","lastname":"Costello","parent_id":6,"postcode":"49628-7978","region":"Michigan","region_code":"Michigan","region_id":33,"street":["6146 Honey Bluff Parkway"],"telephone":"(555) 229-3326"},"payment":{"account_status":null,"additional_information":["Check \/ Money order",null,null],"amount_ordered":32.05,"base_amount_ordered":32.05,"base_shipping_amount":15,"cc_exp_year":"0","cc_last4":null,"cc_ss_start_month":"0","cc_ss_start_year":"0","entity_id":6,"method":"checkmo","parent_id":6,"shipping_amount":15},"status_histories":[]}

I've highlighted main product type by bold.

Please help us,
Thanks in advance

**Comment by veloraven** [comment]
@algostore thank you for your feedback.
Is this issue still  actual?
If it is, please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
If it is not, please close it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
