### ISSUE TITLE
Proxy code generation does not generate classes

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2#35252]
### Preconditions (*)

1. Magento Commerce 2.4.3-p1
2. PRODUCTION mode (!important)

### Steps to reproduce (*)

1. Create a new module
2. Add the file `etc/adminhtml/di.xml` with content in which the proxy arguments have line breaks at the end
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Amasty\Oaction\Model\Action\ActionModifierProvider">
        <arguments>
            <argument name="modifiers" xsi:type="array">
                <item name="amasty_oaction_orderattr" xsi:type="object">
                    Amasty\Oaction\Model\Action\Modifier\OrderAttributesModifier\Proxy
                </item>
                <item name="pdfshipments_order" xsi:type="object">
                    Amasty\Oaction\Model\Action\Modifier\PrintPackingSlipsModifier\Proxy
                </item>
            </argument>
        </arguments>
    </type>
    <type name="Amasty\Oaction\Model\Command\Pdf\PdfCollectorResolver">
        <arguments>
            <argument name="collector" xsi:type="object">
                Amasty\Oaction\Model\Command\Pdf\PdfCollector\ZipCollector\Proxy
            </argument>
        </arguments>
    </type>
</config>
```
3. Set production mode
4. run the **`setup:di:compile`** command
5. Check the generated/code folder for `Amasty\Oaction\Model\Action\Modifier\OrderAttributesModifier\Proxy` and `Amasty\Oaction\Model\Action\Modifier\PrintPackingSlipsModifier\Proxy`
6. Check the generated/metadata folder for `generated/metadata/adminhtml.php` content 

### Expected result (*)

1. Proxy files were successfully created after compilation
2. Factory files have been successfully created after compilation

### Actual result (*)

1. Proxy files are missing
2. In my case, there is even an error when trying to open the admin panel

```
Class Amasty\\Oaction\\Model\\Action\\Modifier\\OrderAttributesModifier\\Proxy does not exist

#1 Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor() called at [vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php:54],,,
#2 Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:100]
#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:150]
#4 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:125]
#5 Magento\\Framework\\ObjectManager\\Factory\\Compiled->parseArray() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:86]
#6 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:150]
#7 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:79]
#8 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]
#9 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php:174]
#10 Magento\\Framework\\Interception\\PluginList\\PluginList->getPlugin() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:144]
#11 Magento\\Ui\\Config\\Reader\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#12 Magento\\Ui\\Config\\Reader\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Ui\/Config\/Reader\/Interceptor.php:23]
#13 Magento\\Ui\\Config\\Reader\\Interceptor->read() called at [vendor\/magento\/module-ui\/Config\/Data.php:102]
#14 Magento\\Ui\\Config\\Data->initData() called at [vendor\/magento\/module-ui\/Config\/Data.php:136]
#15 Magento\\Ui\\Config\\Data->get() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/UiComponent.php:100]
#16 Magento\\Framework\\View\\Layout\\Reader\\UiComponent->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#17 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/Container.php:84]
#18 Magento\\Framework\\View\\Layout\\Reader\\Container->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#19 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Page\/Config\/Reader\/Body.php:68]
#20 Magento\\Framework\\View\\Page\\Config\\Reader\\Body->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#21 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout.php:346]
#22 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:32]
#23 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]
#24 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:65]
#25 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]
#26 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Page\/Config.php:224]
#27 Magento\\Framework\\View\\Page\\Config->build() called at [vendor\/magento\/framework\/View\/Page\/Config.php:237]
#28 Magento\\Framework\\View\\Page\\Config->publicBuild() called at [vendor\/magento\/framework\/View\/Result\/Page.php:244]
#29 Magento\\Framework\\View\\Result\\Page->render() called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]
#30 Magento\\Framework\\View\\Result\\Layout->renderResult() called at [generated\/code\/Magento\/Backend\/Model\/View\/Result\/Page\/Interceptor.php:23]
#31 Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->renderResult() called at [vendor\/magento\/framework\/App\/Http.php:120]
#32 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]
#33 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]
```

### Discovery

When production mode is set, code generation is performed only during **`setup:di:compile`**.

After code generation, Proxy and Factory files are missing because [\Magento\Setup\Module\Di\Code\Scanner\XmlScanner::collectEntities()](https://github.com/magento/magento2/blob/2.4.3-p1/setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php#L48) and [\Magento\Setup\Module\Di\Code\Scanner\XmlScanner::scanFactories()](https://github.com/magento/magento2/blob/2.4.3-p1/setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php#L76) use not quite correct regular expressions that want to meet the value without extra whitespace characters after Proxy and Factory

At the same time, these arguments were successfully added to the metadata file `generated/metadata/adminhtml.php`

![image](https://user-images.githubusercontent.com/1055999/161046078-19515e08-4106-4c45-a967-842b19d283f3.png)

If you use developer mode, then after compiling di, there is also no proxy files, but when accessing the website, these classes are generated on the fly, which avoids errors.

Most likely, this problem can be fixed by changing regexp, which will allow you to use whitespace characters at the end, or by replacing this regulatory expression with a suitable xpath expression.

`$regex = '/^(.*)\\\(.*)Proxy$/';` -> `$regex = '/^(.*)\\\(.*)Proxy(\s*)$/';`
` $regex = '/^(.*)Factory$/';` -> `$regex = '/^(.*)Factory(\s*)$/';`

When I reformat `di.xml` without line breaks, then everything starts working correctly. 

From  ![image](https://user-images.githubusercontent.com/1055999/161046667-f3a0454a-f4bc-4534-ba9c-9c7f7ec1c545.png)

To ![image](https://user-images.githubusercontent.com/1055999/161046608-f484acfc-1bc7-47f6-972c-dd1417dbdf60.png)

But the use of line breaks in the arguments is not prohibited in any way

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @DmitryFurs,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch  and followed the following steps to replicate the issue:-

1. Created a custom module named ‘Magento_CustomModule’
2. In the etc folder of the module created a di.xml with this content

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
   <type name="Magento\Catalog\Model\ProductLink\CollectionProvider">
       <arguments>
           <argument name="providers" xsi:type="array">
               <item name="crosssell" xsi:type="object">
                       Magento\Catalog\Model\ProductLink\CollectionProvider\Crosssell\Proxy
               </item>
               <item name="upsell" xsi:type="object">Magento\Catalog\Model\ProductLink\CollectionProvider\Upsell\Proxy</item>
               <item name="related" xsi:type="object">Magento\Catalog\Model\ProductLink\CollectionProvider\Related\Proxy</item>
           </argument>
       </arguments>
   </type>
   <type name="Magento\Catalog\Model\Product">
       <arguments>
           <argument name="catalogProductStatus" xsi:type="object">
           Magento\Catalog\Model\Product\Attribute\Source\Status\Proxy
           </argument>
           <argument name="productLink" xsi:type="object">
           Magento\Catalog\Model\Product\Link\Proxy
           </argument>
       </arguments>
   </type>
</config>
```
3. Set the Production mode on
4. Deleted the generated folder from the root and run the command bin/magento setup:di:compile
5. In the generated folder, the Proxy file is only generated for proxy arguments that are given without the line break and not for the arguments that are given with a line break. 
![image](https://user-images.githubusercontent.com/51681618/180034806-f1fede16-d2a4-47ec-bc6f-649f029b58a1.png)

Hence this issue is reproducible and confirmed.

Thanks

**Comment by maqlec** [comment]
I can confirm that issue and I can add that Magento must be in production mode or must be without installation (eg. config.php is present but env.php is not). Im using this configuration for generate classes before create classmap optimization and now its causes error. Im counting on fast fix
