### ISSUE TITLE
Unable to send order confirmation email to users with specific emails

### ISSUE THREAD

**Issue by SerhiiMandrykin** [magento/magento2#35258]
### Preconditions (*)

1. Magento ^2.4.3

### Steps to reproduce (*)

1. Create an order with email like `test-1-@example.com` (important to have - character)
2. Try to send order confirmation email

### Expected result (*)

1. The email is sent

### Actual result (*)

1. The email is not sent

### Additional info
It looks like the issue comes from `\Magento\Framework\Mail\AddressConverter::convertEmailUserToAscii`, from the `idn_to_ascii` function.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by SerhiiMandrykin** [comment]
@magento give me 2.4-develop instance

**Comment by SerhiiMandrykin** [comment]
Is reproducing on Magento Instance

**Comment by kassner** [comment]
I have a patch for it, although not very well tested in production yet: https://gist.github.com/kassner/808f13e1263108fdde7b12ebdfdb0fca

**Comment by hostep** [comment]
This is a duplicate of https://github.com/magento/magento2/issues/34318 btw 🙂

**Comment by SerhiiMandrykin** [comment]
@hostep yes, thank you!
