### ISSUE TITLE
Unable to migrate magento1.9.3.2 into magento 2.4.3

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35251]
Magento 1.9.3.2
Magento 2.4.3
Data migation tool installed on magento 2.3.4
All configuration are good, when  i am run migration:data command it will working and around 53% it stucked and say that 
In Mysql.php line 599:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sales_flat_qoute' doesn't exist, query was: SELECT DISTINCT     
  `child`.`quote_id` FROM `justselling_projectrequest` AS `child`                                                                   
   LEFT JOIN `sales_flat_qoute` AS `parent` ON child.quote_id = parent.entity_id WHERE (child.quote_id IS NOT NULL) AND (parent.e   
  ntity_id IS NULL)   

In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sales_flat_qoute' doesn't exist  

Result:
unable to migrate data
Excepted
data migrated succssfully

**Comment by crabnomad** [comment]
This is a typo. The table name “sales_flat_qoute” is spelled incorrectly. It should have been “sales_flat_quote”. Please check the data migration tool you are using, find and correct this table name in it

**Comment by engcom-Hotel** [comment]
Hello @hemendraajmera,

Thanks for posting the issue!

Currently, Magento supports 2.3+ versions. And such transitions may not be possible in one step, you need to follow several upgrades before the application can be upgraded to 2.4.x.

Please try once with upgrades and let us know in case of any query.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @hemendraajmera,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
