### ISSUE TITLE
Via Rest API cannot create another product with same name

### ISSUE THREAD

**Issue by algostore** [magento/magento2#3525]
Magento 2.0.1 + sample data.

/rest/V1/products/478

Data, what I have used to create product
{
    "product":{
        "sku": "478",
        "typeId":"simple",
        "attributeSetId":"4",
        "name":"Test 123456",
        "price":"125.00"
    }
 }

If Product with same name is exist, then during the this API call you will get an error.

{
  "message": "Unable to save product",
  "trace": "#0 [internal function]: Magento\Catalog\Model\ProductRepository->save(Object(Magento\Catalog\Model\Product\Interceptor), false)\n#1 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)\n#2 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('save', Array)\n#3 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'configurablePro...')\n#4 /var/www/app/code/Magento/ConfigurableProduct/Model/Plugin/AroundProductRepositorySave.php(62): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)\n#5 [internal function]: Magento\ConfigurableProduct\Model\Plugin\AroundProductRepositorySave->aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)\n#6 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)\n#7 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'catalogInventor...')\n#8 /var/www/app/code/Magento/CatalogInventory/Model/Plugin/AroundProductRepositorySave.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)\n#9 [internal function]: Magento\CatalogInventory\Model\Plugin\AroundProductRepositorySave->aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)\n#10 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)\n#11 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'transactionWrap...')\n#12 /var/www/app/code/Magento/Catalog/Model/Plugin/ProductRepository/TransactionWrapper.php(44): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)\n#13 [internal function]: Magento\Catalog\Model\Plugin\ProductRepository\TransactionWrapper->aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)\n#14 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)\n#15 /var/www/var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(52): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('save', Array, Array)\n#16 [internal function]: Magento\Catalog\Model\ProductRepository\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor), false)\n#17 /var/www/app/code/Magento/Webapi/Controller/Rest.php(249): call_user_func_array(Array, Array)\n#18 /var/www/app/code/Magento/Webapi/Controller/Rest.php(160): Magento\Webapi\Controller\Rest->processApiRequest()\n#19 /var/www/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))\n#20 /var/www/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#21 /var/www/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()\n#22 /var/www/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))\n#23 {main}"
}

In admin part, you can create more then one product with same name.

Please help us,
Thanks in advance

**Comment by Widmayer** [comment]
Hi,
stumbled upon the same issue...
You have to specify the url_key in the payload:
{
  "product": {
    "sku": "12345678",
    "name": "Name",
    "attributeSetId": 11,
    "price": 1234.56,
    "weight": 1,
    "visibility": 4,
    "typeId": "simple",
    "status": 1,
  "custom_attributes": [
    {
      "attribute_code": "url_key",
      "value": "12345678"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    }
  ]
  }
}

**Comment by algostore** [comment]
It's sort of working. Because when you do same within backend it's not necessary to define url_key, and you can save 100 products with same name without paying attention to url.

Question to: **Magento2 development team**. Is it final way(REST API) of saving products, so I should always define url_key  (curious how I know if that url is already in use, if I need import 50K of product via API), or it will be improved in future, and will work same way as backend?
Thanks

**Comment by Widmayer** [comment]
For me it is just a workaround, too...
My url_key contains the sku so there will be no match with another one as the sku is unique.
But I would also expect that the API tries to put a number to the url_key if it already exiists.

**Comment by veloraven** [comment]
@algostore is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
