### ISSUE TITLE
POS Error Code No such Enterty CustomerID 2295

### ISSUE THREAD

**Issue by Dragonsupplies** [magento/magento2#35255]
### Preconditions (*)

1.  2.3.3
2. POS front end main till

### Steps to reproduce (*)

1. Placing a sale trough the POS -Adding goods to cart, going to checkout, clicking Pay, error Code appears No such Enterty CustomerID 2295 POS now has a missing identity. 
2. POS not syncing with backend
3.

### Expected result (*)

1. POS to Sync with back end and complete transaction. Stock removed from backend
2. POS receipt printed

### Actual result (*)

1. No such Enterty CustomerID 2295
2. Not assigned to Shop 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Delta** [comment]
Hi @Dragonsupplies ,
POS is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
