### ISSUE TITLE
Unable to migrate data from m1 to m2

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35268]
Magento 2.4.3-p1
using data migration tool
it running and suddenly this issue occurs 
 Notice: unserialize(): Error at offset 334 of 373 bytes in vendor\magento\data-migration-tool\src\Migration\Handler\Rule\   
  SerializedData.php on line 36

**Comment by nuzil** [comment]
Hi @hemendraajmera 
Can you please raise the issue on respective project? 
https://github.com/magento/data-migration-tool/

also more detailes about the issue to reproduce will be great. 

Closing here
