### ISSUE TITLE
Invalid from_date / to_date salesRules rest response

### ISSUE THREAD

**Issue by websecureNL** [magento/magento2#35265]
### Preconditions (*)

1. Magento ver. 2.4.3

### Steps to reproduce (*)

1. Create a new Cart Price Rule through API - endpoint: /rest/V1/salesRules/
2. Enter sample date and from_date / to_date to a YYYY-MM-DD format in the request. Like:

"from_date":"2022-06-01",
"to_date":"2022-06-10"

3. Send request and inspect response. 

### Expected result (*)

1. Would like a new Cart Price Rule to have the correct from_date / to_date in the response

### Actual result (*)

1. The from_date and to_date are both 0000-00-00 in the response

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by websecureNL** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Alfa** [comment]
Hello @websecureNL 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2764` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5
