### ISSUE TITLE
Stock\StatusFactory does not exist

### ISSUE THREAD

**Issue by jahved** [magento/magento2#3527]
I have just install the Magento2 version 
On the CMS Homepage I am try to search from simple product and i am getting 
Class Magento\CatalogInventory\Model\ResourceModel\Stock\StatusFactory does not exist

Can anyone please advise how to resolve this issue.

**Comment by rganin** [comment]
This is an autogenerated class. Please ensure that your http thread has access to `var/generation` directory, or set rights with `chown -R apache:apache var/* pub/*` (or whatever user/group you have for httpd instead of 'apache').
For production mode it should be pre-compiled with `php -f bin/magento setup:di:compile` command.

**Comment by veloraven** [comment]
@jahved thank you for your feedback.
Is this issue still actual? Please close it if it is not.
Please, provide the used Magento version if it is still actual.
Please, also format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by jarnail104** [comment]
Clean , Flush cache and disable cache. After that removed var/generation folder then ran magento setup:di:compile which generated all necessary classes. It works like charm.
