### ISSUE TITLE
Continue using Klarna Payments in Magento 2.4.4 - What do I have to do?

### ISSUE THREAD

**Issue by C4rter** [magento/magento2#35288]
### Preconditions (*)
1. Magento 2.4.4

### Steps to reproduce (*)
1. Update to Magento 2.4.4
2. Try to use Klarna Payments
3. It's removed now. What do I have to install to keep using the exact same extension?

### Expected result (*)

1. Still using Klarna Payments in Magento 2.4.4

### Actual result (*)
1. I only found Klarna Checkout in the Marketplace but it's a totally different thing.
2. How can I kep using the Klarna Payments extension in Magento 2.4.4?

**Comment by Smpatidar** [comment]
https://docs.klarna.com/platform-solutions/adobe-commerce/adobe-commerce-244-and-above/installation/


please read here to find proper solution

**Comment by CanBeer** [comment]
Is the Klarna  9.3.3 version compatible with Adobe Commerce 2.4.4 ?

I have a `guzzlehttp/guzzle` dependency error ? Core of Magento seems to need 7+ version and Klarna required old 6+ version.

```
php /usr/local/bin/composer2 require klarna/m2-checkout                                                                                                                   
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^9.3 for klarna/m2-checkout
./composer.json has been updated
Running composer update klarna/m2-checkout
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - klarna/m2-checkout[9.3.1, ..., 9.3.3] require klarna/module-base ^8.3.1 -> satisfiable by klarna/module-base[8.3.1].
    - klarna/m2-checkout 9.3.0 requires klarna/module-base ^8.3.0 -> satisfiable by klarna/module-base[8.3.0, 8.3.1].
    - klarna/module-base[8.3.0, ..., 8.3.1] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but the package is fixed to 7.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires klarna/m2-checkout ^9.3 -> satisfiable by klarna/m2-checkout[9.3.0, 9.3.1, 9.3.2, 9.3.3].
```

**Comment by C4rter** [comment]
> https://docs.klarna.com/platform-solutions/adobe-commerce/adobe-commerce-244-and-above/installation/
> 
> please read here to find proper solution

Thank you. I followed the guideline on that page but the only solution I can find the in Marketplace is:
https://marketplace.magento.com/klarna-m2-checkout.html
Which is not it. But they are saying I need to get it from the marketplace.

> Is the Klarna 9.3.3 version compatible with Adobe Commerce 2.4.4 ?
> 
> I have a `guzzlehttp/guzzle` dependency error ? Core of Magento seems to need 7+ version and Klarna required old 6+ version.
> 
> ```
> php /usr/local/bin/composer2 require klarna/m2-checkout                                                                                                                   
> Info from https://repo.packagist.org: #StandWithUkraine
> Using version ^9.3 for klarna/m2-checkout
> ./composer.json has been updated
> Running composer update klarna/m2-checkout
> Gathering patches for root package.
> Loading composer repositories with package information
> Info from https://repo.packagist.org: #StandWithUkraine
> In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - klarna/m2-checkout[9.3.1, ..., 9.3.3] require klarna/module-base ^8.3.1 -> satisfiable by klarna/module-base[8.3.1].
>     - klarna/m2-checkout 9.3.0 requires klarna/module-base ^8.3.0 -> satisfiable by klarna/module-base[8.3.0, 8.3.1].
>     - klarna/module-base[8.3.0, ..., 8.3.1] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but the package is fixed to 7.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires klarna/m2-checkout ^9.3 -> satisfiable by klarna/m2-checkout[9.3.0, 9.3.1, 9.3.2, 9.3.3].
> ```

I can't even find anything when I try that. It says:
```
 [InvalidArgumentException]
  Could not find a matching version of package klarna/m2-checkout. Check the package spelling, your version constrain
  t and that the package is available in a stability which matches your minimum-stability (dev).
```

**Comment by CanBeer** [comment]
When I try with the documentation package : 

```
╰─$ php /usr/local/bin/composer2 require klarna/m2-klarna                                                                                                                                                                                                                                                                                                    
  [InvalidArgumentException]                                                                                                                                                     
  Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which mat  
  ches your minimum-stability (stable).        
```

**Comment by C4rter** [comment]
I guess it fails because it's not in the Magento Account. But I'm unable to add it to the account as it's not available in the Marketplace

**Comment by C4rter** [comment]
> @C4rter The version you are using does not work for the Magento version >= 2.4.4. We will add in the future a fix for it. But we created a new extension which consist of all Klarna Products. Link: https://marketplace.magento.com/klarna-m2-klarna.html
This new extension is the place where we add new functionalities, features and so on in the future. The Extension m2-checkout will be maintained for bug and security fixes but no bigger improvements will happen there. To ensure you always have the most performant and stable code I advise to use the new extension: m2-klarna. :)

Thank you. Now that Extension can also be found in the Marketplace and can be "bought" there so it's registered to my Magento account. That wasn't available yesterday and the day before. When searching for "Klarna" in the Marketplace, only the Klarna Checkout Extension came up.

> Thank you @Clodan87 for the update
> 
> @C4rter could you pls confirm it resolves the issue?

That indeed resolves the issue now. Once "bought" in the Marketplace that Extension can be installed via composer and can be used for Klarna payments in the M2 Checkout.

**Comment by Smpatidar** [comment]
use this --> composer require klarna/m2-klarna:1.0.0

if you receive --->(may be solution )
$ php /usr/local/bin/composer2 require klarna/m2-klarna                                                                                                                                                                                                                                                                                                    
  [InvalidArgumentException]                                                                                                                                                     
  Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which mat  
  ches your minimum-stability (stable).    
  
  
  please go to you'r root folder and find auth.json.sample and edit this file and add  access key https://marketplace.magento.com/customer/accessKeys/     from this link and add there and rename auth.json.sample to auth.json 
  
  now go to marketplace and purchase klarna module (its free) .
  now execute this cmd --> composer require klarna/m2-klarna:1.0.0

**Comment by C4rter** [comment]
> use this --> composer require klarna/m2-klarna:1.0.0
> 
> if you receive --->(may be solution ) $ php /usr/local/bin/composer2 require klarna/m2-klarna [InvalidArgumentException] Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which mat ches your minimum-stability (stable).
> 
> please go to you'r root folder and find auth.json.sample and edit this file and add access key https://marketplace.magento.com/customer/accessKeys/ from this link and add there and rename auth.json.sample to auth.json
> 
> now go to marketplace and purchase klarna module (its free) . now execute this cmd --> composer require klarna/m2-klarna:1.0.0

Thank you, yeah I know, that works now. But it didn't work before because the Klarna module couldn't be purchased. Only Klarna Checkout could be found in the Marketplace Tuesday and Wednesday.

**Comment by satinderjot-tech** [comment]
The issue has been resolved for me according to the .

1. Purchase the extension from magento marketplace and create access key into the same account.
2. Rename auth.json.sample to auth.json and update he access keys.
3. run composer require klarna/m2-klarna:1.0.2.

That is worked for me.

**Comment by TomR5** [comment]
It still won't work for me.  I "purchased" the free Klarna/m2-klarna, but the composer commands still fail  "Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)."  I even tried klarna:m2-klarna, klarna/klarna-m2-klarna.  Could someone PLEASE tell me the exact composer command I need to use to install klarna on our open source Magneto 2.4.4 site?  Thank you.  Yes I have an Adobe commerce account; yes my keys are correct.

**Comment by Smpatidar** [comment]
> It still won't work for me. I "purchased" the free Klarna/m2-klarna, but the composer commands still fail "Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)." I even tried klarna:m2-klarna, klarna/klarna-m2-klarna. Could someone PLEASE tell me the exact composer command I need to use to install klarna on our open source Magneto 2.4.4 site? Thank you. Yes I have an Adobe commerce account; yes my keys are correct.

use this "composer require klarna/m2-klarna"

**Comment by OBurtyka** [comment]
I have the same issue when trying to composer require klarna/m2-klarna
                                                                                                                              
  [InvalidArgumentException]                                                                                                  
  Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (alpha).

**Comment by realadityayadav** [comment]
You would need to add the correct credentials in auth.json from the account that you purchased the extension from.

```
{
    "http-basic": {
        "repo.magento.com": {
            "username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
    }
}
```
Replace xx with your credentials from https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/authentication-keys.html
