### ISSUE TITLE
Subtotal on invoice not correct

### ISSUE THREAD

**Issue by MrJoshFisher** [magento/magento2#35282]
### Preconditions (*)
1. Magento Version: 2.4.0

### Steps to reproduce (*)
1. Add items to cart,
2. Subtotal does not match the total when items are added together.

### Expected result (*)

1. Subtotal to match the cost of the items

### Actual result (*)

1. When adding the subtotals of the items in screenshot the total is £790.87 but the subtotal states £659.06

---
![Screenshot 2022-04-08 140621](https://user-images.githubusercontent.com/8970358/162441620-e02f5497-c250-418e-9760-c5d2618fdcb9.jpg)

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @MrJoshFisher ,
Thank you for raising an issue and we tried to reproduce it on Magento 2.4 Develop with latest branch. it works fine, issue is not producible.
Please find below screenshots for reference.
<img width="1440" alt="Screenshot 2022-04-08 at 11 09 01 PM" src="https://user-images.githubusercontent.com/51681379/162494358-fcb57879-9fac-4c72-94be-312177cdc127.png">

Hence, request to review the provided steps.

**Comment by MrJoshFisher** [comment]
Hello, 

Im new to magento so apologies if I'm not clear on some points, but how would I diagnose this is it a matter of disabling modules to see which one is affecting the price? 

Cheers

Josh

**Comment by engcom-Delta** [comment]
Hi @MrJoshFisher ,
Thanks for updating us and We request you to provide more details on modules which you are using to test it.
Regards,

**Comment by engcom-Delta** [comment]
Hi @MrJoshFisher ,
Kindly let us know your settings for Base currency , Default display currency  and allowed currencies (Stores--> Configuration--> General--> Currency Setup)  in Admin portal page(backend) .
<img width="1440" alt="Screenshot 2022-04-25 at 6 01 57 PM" src="https://user-images.githubusercontent.com/51681379/165089989-7469f9e9-e91c-425d-85a9-49b358af02e0.png">

Thanks

**Comment by MrJoshFisher** [comment]
Hi @engcom-Delta,

Apologies for the delay

Please see a list of modules below:

List of enabled modules:
Magento_AdminAnalytics
Magento_Store
Magento_AdobeIms
Magento_AdobeImsApi
Magento_AdobeStockAdminUi
Magento_MediaGallery
Magento_AdobeStockAssetApi
Magento_AdobeStockClient
Magento_AdobeStockClientApi
Magento_AdobeStockImage
Magento_Directory
Magento_AdobeStockImageApi
Magento_AdvancedPricingImportExport
Magento_Theme
Magento_Amqp
Magento_AmqpStore
Magento_Config
Magento_Backend
Magento_Authorization
Magento_Search
Magento_Backup
Magento_Eav
Magento_Variable
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_Customer
Magento_AdminNotification
Magento_Indexer
Magento_Security
Magento_GraphQl
Magento_EavGraphQl
Magento_Cms
Magento_CatalogImportExport
Magento_Catalog
Magento_CatalogInventory
Magento_Rule
Magento_Payment
Magento_CatalogRuleGraphQl
Magento_CatalogRule
Magento_CatalogUrlRewrite
Magento_StoreGraphQl
Magento_Widget
Magento_Quote
Magento_SalesSequence
Magento_CheckoutAgreementsGraphQl
Magento_MediaGalleryUi
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_ComposerRootUpdatePlugin
Magento_User
Magento_Msrp
Magento_Sales
Magento_CatalogGraphQl
Magento_Checkout
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_CatalogCustomerGraphQl
Magento_Integration
Magento_Downloadable
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_Captcha
Magento_DirectoryGraphQl
Magento_QuoteGraphQl
Magento_DownloadableGraphQl
Magento_ImportExport
Magento_ConfigurableProduct
Magento_BundleGraphQl
Magento_CatalogSearch
Magento_AdvancedSearch
Magento_Elasticsearch
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GoogleShoppingAds
Magento_CatalogCmsGraphQl
Magento_PageCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Magento_Bundle
Magento_InstantPurchase
Magento_Analytics
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleImportExport
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryBundleProductIndexer
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventorySourceSelectionApi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupGraphQl
Magento_Shipping
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_Multishipping
Magento_Webapi
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_Reports
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryRequisitionList
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_CatalogInventoryGraphQl
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventoryShippingAdminUi
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventoryInStorePickupFrontend
Magento_LayeredNavigation
Magento_LoginAsCustomer
Magento_LoginAsCustomerAdminUi
Magento_LoginAsCustomerApi
Magento_LoginAsCustomerFrontendUi
Magento_LoginAsCustomerLog
Magento_LoginAsCustomerPageCache
Magento_LoginAsCustomerQuote
Magento_LoginAsCustomerSales
Magento_Marketplace
Magento_MediaContent
Magento_MediaContentApi
Magento_MediaContentCatalog
Magento_MediaContentCms
Magento_MediaContentSynchronization
Magento_MediaContentSynchronizationApi
Magento_MediaContentSynchronizationCatalog
Magento_MediaContentSynchronizationCms
Magento_AdobeStockAsset
Magento_MediaGalleryApi
Magento_MediaGalleryCatalog
Magento_MediaGalleryIntegration
Magento_MediaGallerySynchronization
Magento_MediaGallerySynchronizationApi
Magento_AdobeStockImageAdminUi
Magento_MediaGalleryUiApi
Magento_MediaStorage
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_InventoryInStorePickupMultishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_Newsletter
Magento_OfflinePayments
Magento_SalesRule
Magento_GraphQlCache
Magento_CardinalCommerce
Magento_Vault
Magento_Paypal
Magento_PaypalGraphQl
Magento_Persistent
Magento_ProductAlert
Magento_ProductVideo
Magento_CheckoutAgreements
Magento_QuoteAnalytics
Magento_ConfigurableProductGraphQl
Magento_ReCaptchaAdminUi
Magento_ReCaptchaCheckout
Magento_ReCaptchaContact
Magento_ReCaptchaCustomer
Magento_ReCaptchaFrontendUi
Magento_ReCaptchaMigration
Magento_ReCaptchaNewsletter
Magento_ReCaptchaPaypal
Magento_ReCaptchaReview
Magento_ReCaptchaSendFriend
Magento_ReCaptchaUi
Magento_ReCaptchaUser
Magento_ReCaptchaValidation
Magento_ReCaptchaValidationApi
Magento_ReCaptchaVersion2Checkbox
Magento_ReCaptchaVersion2Invisible
Magento_ReCaptchaVersion3Invisible
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_RequireJs
Magento_Review
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Magento_Elasticsearch6
Magento_ConfigurableProductSales
Magento_SalesAnalytics
Magento_SalesGraphQl
Magento_SalesInventory
Magento_OfflineShipping
Magento_ConfigurableImportExport
Magento_UrlRewrite
Magento_Elasticsearch7
Magento_CustomerAnalytics
Magento_Securitytxt
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_InventoryInStorePickupSalesAdminUi
Magento_Sitemap
Magento_UrlRewriteGraphQl
Magento_CustomerDownloadableGraphQl
Magento_Swagger
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_AsynchronousOperations
Magento_ThemeGraphQl
Magento_Tinymce3
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogUrlRewriteGraphQl
Magento_CatalogAnalytics
Magento_Usps
Magento_InventoryGraphQl
Magento_PaypalCaptcha
Magento_VaultGraphQl
Magento_Version
Magento_InventoryInStorePickupWebapiExtension
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_Weee
Magento_WeeeGraphQl
Magento_CatalogWidget
Magento_Wishlist
Magento_WishlistAnalytics
Magento_WishlistGraphQl
Amasty_Base
Amasty_Geoip
Amasty_CronScheduleList
Amasty_Finder
PayPal_Braintree
Amasty_Mage24Fix
Amasty_ShopbyBase
Mirasvit_Search
Amasty_ShopbyBrand
Mirasvit_SearchElastic
Mirasvit_SearchMysql
Amazon_Core
Amazon_Login
Amazon_Payment
Dotdigitalgroup_Email
Dotdigitalgroup_Chat
Ebizmarts_SagePaySuite
Klarna_Core
Klarna_Ordermanagement
Klarna_Onsitemessaging
Klarna_Kp
Mageplaza_Core
Mageplaza_Smtp
Magestat_CookieLawBanner
Mirasvit_Core
Mirasvit_Misspell
Mirasvit_Report
Mirasvit_SearchSphinx
Mirasvit_SearchAutocomplete
Amasty_Shopby
Mirasvit_SearchGraphQl
Mirasvit_SearchLanding
Amasty_ShopbyPage
Mirasvit_SearchReport
Amasty_ShopbySeo
Ninedotmedia_Base
Ninedotmedia_CsvImporter
Ninedotmedia_Seo
Ninedotmedia_Shipping
Ninedotmedia_Theme
Amasty_Checkout
PayPal_BraintreeGraphQl
Shippingx_Shiptheory
Springbot_Queue
Temando_ShippingRemover
Vertex_Tax
Vertex_AddressValidation
Ves_All
Ves_Megamenu
Ves_Setup
Xtento_XtCore
Xtento_ProductExport
Yotpo_Yotpo
digitalethos_jsModule

List of disabled modules:
Magento_Csp
Magento_TwoFactorAuth
Amasty_ShippingTableRates

Also the currency is set to British Pound for both options,

![image](https://user-images.githubusercontent.com/8970358/165483807-b1c0e133-d992-4da6-bfab-825bbc83567f.png)

Cheers

**Comment by engcom-Delta** [comment]
Hi @MrJoshFisher ,

Thank you so much for sharing the base currency setup screenshot. Unfortunately we need one more help from you that what was your Tax amount and Tax percentage settings please? 

Regards,

**Comment by MrJoshFisher** [comment]
Hi @engcom-Delta 

VAT 20%

![image](https://user-images.githubusercontent.com/8970358/165920360-60784cb5-48ac-4660-ab37-d8c472c58c31.png)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
