### ISSUE TITLE
Magento Admin - Hitting enter when configuring a product to add to order in admin does not save the custom options

### ISSUE THREAD

**Issue by blockedie** [magento/magento2#35284]
### Preconditions (*)

1. Magento ver. 2.4.2-p2
2.

### Steps to reproduce (*)

In Magento 2, navigate to Sales > Order and create a new order

Select "Add Products" to add a product to the order from the product list.

In the product list, find an upholstery product and select "Configure". In the configure pop-up, select the custom options and enter the quantity. From the quantity field HIT ENTER instead of using the cursor to select "Ok" in the top right corner. Note that the configuration pop up window has closed.

add the product to the order and return to the order page. Scroll to the product you just added and note that you see an error "The product has required options". Select "Configure" on the product and note that the custom options that were set before are no longer present, suggesting they were not saved.

Once you reconfigure the options, the error goes away. On the order page, if you use "Enter" rather than selecting "Ok" in the configuration pop-up, the configurations are saved as appropriate.

Current behavior (please include any screenshots or videos as needed):

When I select different custom options for a MTO product and then hit "enter" on the keyboard to apply changes and close the window, the custom options are not saved. When I add the product to the order, and find the product, I notice that I receive an error "The product has required options" and I am forced to reconfigure the product options

Here's a loom video showing what I did to encounter the error:  [https://www.loom.com/share/40dab8667bef40a882c513f52eb2985a]

**Expected behavior:** 

I should be able to hit "Enter" to apply the custom options and close the window and expect that the options are saved when I add the product to the order.

**Additional Information:**

2.4-develop branch behavior: Product got selected but "The requested qty is not available" error is displayed on clicking "Add selected products" button. 
This issue is not reproducible for Bundle Products on 2.4-develop branch.On hitting "Enter" instead of OK button, product is not getting selected.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ **X** ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch however we are getting different error message on performing mentioned steps: "The requested qty is not available" and the product is not getting added
Please find the attached video below:
https://user-images.githubusercontent.com/60198231/162720260-460b6a8d-c723-4e9b-8e3e-7ed0d1c839b0.mp4

However on clicking OK button instead of hitting "Enter" while configuring, this issue is not reproducible. User is able to add product and submit order. No error message is displayed.

https://user-images.githubusercontent.com/60198231/162720965-41d64575-3720-4c79-b87c-81c409ee5bc7.mp4

Hence confirming this issue as the product is getting selected on hitting ENTER but not able to add the product.
