### ISSUE TITLE
Numeric value is expected.

### ISSUE THREAD

**Issue by snowwhite686** [magento/magento2#3528]
i deleted the var cache/ \* 
 var/view_preprocessed/*
 var/generation/*
pub/static/ \* 

As i cannot see any template changes,i did a static-content:deploy and it says success.

But the website is showing now like

Numeric value is expected.
#0 E:\xampp\htdocs\magstore\vendor\magento\framework\Data\Argument\Interpreter\Composite.php(61): Magento\Framework\Data\Argument\Interpreter\Number->evaluate(Array)
#1 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\Reader\Block.php(339): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#2 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\Reader\Block.php(214): Magento\Framework\View\Layout\Reader\Block->evaluateArguments(Object(Magento\Framework\View\Layout\Element), Array)
#3 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\Reader\Block.php(128): Magento\Framework\View\Layout\Reader\Block->scheduleReference(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Element))
#4 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#5 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Page\Config\Reader\Body.php(70): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#6 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\ReaderPool.php(105): Magento\Framework\View\Page\Config\Reader\Body->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#7 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout.php(314): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#8 E:\xampp\htdocs\magstore\var\generation\Magento\Framework\View\Layout\Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#13 E:\xampp\htdocs\magstore\vendor\magento\framework\View\Layout.php(859): Magento\Framework\View\Layout->build()
#14 E:\xampp\htdocs\magstore\var\generation\Magento\Framework\View\Layout\Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#15 E:\xampp\htdocs\magstore\vendor\magento\module-cms\Helper\Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#16 E:\xampp\htdocs\magstore\vendor\magento\module-cms\Controller\Index\Index.php(43): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor), 'home')
#17 E:\xampp\htdocs\magstore\var\generation\Magento\Cms\Controller\Index\Index\Interceptor.php(24): Magento\Cms\Controller\Index\Index->execute(NULL)
#18 E:\xampp\htdocs\magstore\vendor\magento\framework\App\Action\Action.php(102): Magento\Cms\Controller\Index\Index\Interceptor->execute()

**Comment by asimraffaqat** [comment]
You must have other characters where numeric value is required, even a **blank space** is also considered as a character. OR have you copy and paste code from pdf or somewhere else.?
Just add numeric value e.g. 135 or 200 etc.

**Comment by palamar** [comment]
@snowwhite686 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please provide additional steps to reproduce.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
