### ISSUE TITLE
Virtual refunded orders do not persist closed state when comment is added via Admin

### ISSUE THREAD

**Issue by ksenia-zlotin** [magento/magento2#35283]
I believe this is caused by the commit here:
https://github.com/magento/magento2/commit/4f90cf54c303bdcb3de6d010a63fb8af87d46eec
I would like an explanation why was this check added and how come even on a clean 2.4.3-p1 copy I am able to recreate this error?

### Preconditions (*)
1. Magento 2.4.3-p1
2. PHP 7.4.13

### Steps to reproduce (*)
1. Install clean copy of Magento 2.4.3-p1 without sample data
2. Create virtual product with a price of $10
3. Place order with that product and invoice it in the Admin so that credit memo is possible
4. Press the credit memo button and go ahead and create one
5. In the
<img width="1785" alt="Screen Shot 2022-04-08 at 2 08 15 PM" src="https://user-images.githubusercontent.com/62074773/162497847-7e40795f-4725-49a6-b4af-97376bd8042e.png">
 order view loaded after the creditmemo saved, scroll to bottom of page where comments section status dropdown is

### Expected result (*)
1. The status dropdown should only show the 'Closed' option, that way when a comment is added to this closed order - it does not set it to 'Complete'.
<img width="1687" alt="Screen Shot 2022-04-07 at 11 26 00 AM" src="https://user-images.githubusercontent.com/62074773/162497795-db143307-18d9-4e07-a5cf-fc31500e64a9.png">

### Actual result (*)
1. order state is never set to closed when the refund saves successfully, while the status **does** update to closed in the db
2. order status dropdown in comments section showing only 'Complete' option which will cause any new comment which will be added to revert the order status from 'Closed' to 'Complete'
<img width="1705" alt="Screen Shot 2022-04-08 at 2 08 20 PM" src="https://user-images.githubusercontent.com/62074773/162497861-842b78f7-a914-4716-987c-2967b96f7f20.png">

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and is reproducible. As per [Magento docs](https://docs.magento.com/user-guide/sales/order-status.html), order status should be closed after issuing credit memo and customer is refunded.
For Virtual Product, Order status is displayed "Complete" in drop-down but displayed "Closed" in comment. On adding new comment, its displayed as Complete in comment section as well. 
![image](https://user-images.githubusercontent.com/60198231/162672879-ec2b8b05-14ae-42b4-aafe-e30bc0471124.png)

Simple Product behavior:
![image](https://user-images.githubusercontent.com/60198231/162672814-bca949df-9b6d-43a2-80aa-621c03e4aaf3.png)

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @ksenia-zlotin,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2811 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2811&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
