### ISSUE TITLE
Catalog\Pricing\Price\FinalPrice::getMaximalPrice for configurable product returns wrong value

### ISSUE THREAD

**Issue by yuriichayka** [magento/magento2#35285]
`getMaximalPrice()` method doesn't work for configurable products, as for bundles for example. 
It returns the same value as `getMinimalPrice()`.
For bundles, related FinalPrice methods are overridden with correct logic, but it isn't implemented for configurables.

### Preconditions (*)

1. Magento 2.4.3 OS

### Steps to reproduce (*)

1. Configure some configurable product with different prices for options
3. Try to get maximal price for configurable product by using \Magento\Catalog\Pricing\Price\FinalPrice::getMaximalPrice()

### Expected result (*)

1. The method returns maximal available price of options
### Actual result (*)

1. The minimal final options price is returned.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @yuriichayka 
As per your explanation we can validate that getMaximalPrice Method is not exists for Configurable Final Price calculation in
\Magento\ConfigurableProduct\Pricing\Price\FinalPrice. Hence confirming this issue. If you want the get the Regular Maximum price of Configurable Product you can use \Magento\ConfigurableProduct\Pricing\Price\ConfigurableRegularPrice::getMaxRegularAmount()
Thanks

**Comment by engcom-November** [comment]
Hi @yuriichayka ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
