### ISSUE TITLE
Database port missing in Magento\TestFramework\Db\Mysql

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#3529]
The methods:
1. `Magento\TestFramework\Db\Mysql::storeDbDump()`
2. `Magento\TestFramework\Db\Mysql::restoreFromDbDump()`

(and perhaps others) are creating mysql / mysqldump commands to be invoked via shell. They make use of the `--host` command-line switch without adressing a potential (optional) port configuration (`--port=#`).

The configuration format is:

```
host[:port]
```

As the configuration data is taken over unchanged, every configuration with a port given makes these CLI commands fail then.

This flaw blocks users with mysql port configuration making use of the test-suite.

Reference: #2735 ~~#2736~~

**Comment by ktomk** [comment]
Just a little reminder that we need to file a request for this with Magento support.

**Comment by KrystynaKabannyk** [comment]
Hello @tkn98, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by tkn98** [comment]
@KrystynaKabannyk: May I ask to share the hash of the commit in which the fix has been applied?
