### ISSUE TITLE
Magento 2.4.4 admin panel - Error: Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#35292]
### Summary (*)

**Magento 2.4.4 running on PHP 8.1**

If you create a plugin for any method of class `vendor/magento/module-backend/Model/Menu.php` then you will receive below error in admin panel 
```
Error: Call to undefined method ReflectionUnionType::getName() in /magento244/vendor/magento/framework/Code/Generator/EntityAbstract.php:335
Stack trace:
#0 /magento244/vendor/magento/framework/Code/Generator/EntityAbstract.php(393): Magento\Framework\Code\Generator\EntityAbstract->extractParameterType(Object(ReflectionParameter))
#1 [internal function]: Magento\Framework\Code\Generator\EntityAbstract->_getMethodParameterInfo(Object(ReflectionParameter))
#2 /magento244/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(103): array_map(Array, Array)
#3 /magento244/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(76): Magento\Framework\Interception\Code\Generator\Interceptor->_getMethodInfo(Object(ReflectionMethod))
#4 /magento244/vendor/magento/framework/Code/Generator/EntityAbstract.php(226): Magento\Framework\Interception\Code\Generator\Interceptor->_getClassMethods()
#5 /magento244/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(177): Magento\Framework\Code\Generator\EntityAbstract->_generateCode()
#6 /magento244/vendor/magento/framework/Code/Generator/EntityAbstract.php(106): Magento\Framework\Interception\Code\Generator\Interceptor->_generateCode()
#7 /magento244/vendor/magento/framework/Code/Generator.php(130): Magento\Framework\Code\Generator\EntityAbstract->generate()
#8 /magento244/vendor/magento/framework/Code/Generator/Autoloader.php(53): Magento\Framework\Code\Generator->generateClass('Magento\\Backend...')
#9 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Backend...')
#10 /magento244/vendor/magento/framework/Code/Reader/ClassReader.php(34): ReflectionClass->__construct('Magento\\Backend...')
#11 /magento244/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Backend...')
#12 /magento244/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Backend...')
#13 /magento244/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...', Array)
#14 /magento244/generated/code/Magento/Backend/Model/MenuFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Backen...', Array)
#15 /magento244/vendor/magento/module-backend/Model/Menu/Config.php(140): Magento\Backend\Model\MenuFactory->create()
#16 /magento244/vendor/magento/module-backend/Model/Menu/Config.php(116): Magento\Backend\Model\Menu\Config->_initMenu()
#17 /magento244/vendor/magento/module-backend/Block/Menu.php(265): Magento\Backend\Model\Menu\Config->getMenu()
#18 /magento244/generated/code/Magento/Backend/Block/Menu/Interceptor.php(41): Magento\Backend\Block\Menu->getMenuModel()
#19 /magento244/vendor/magento/module-backend/Model/View/Result/Page.php(28): Magento\Backend\Block\Menu\Interceptor->getMenuModel()
#20 /magento244/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Backend...')
```

### Examples (*)

Install module https://github.com/redchamps/magento2-module-backend-menu-plugin using below command to quickly repeat the problem

composer require redchamps/magento2-module-backend-menu-plugin

### Proposed solution

The issue occurs to to function exchangeArray called in class \Magento\Backend\Model\Menu this method belongs to parent class \ArrayObject and has return type `object|array` & the Magento code doesn;t support the mix return type while creating Intercepter for the class.

This issue occurs only when the Intercepter class being created for  \Magento\Backend\Model\Menu & in native Magento there is no plugin for this class so this error appears only when some third-party plugin or customisation do this.

This will be the case throughout the Magento classes not only for \Magento\Backend\Model\Menu.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @rav-redchamps,

We have tried to reproduce the issue in Magento 2.4.4 but for us, the issue is not reproducible. Please have a look into the below screenshots for reference:

1. Magento Version:

![image](https://user-images.githubusercontent.com/51681618/163156730-6126fe59-6af2-407f-9635-50bf477fab1d.png)

2. We made a custom plugin in order to reproduce the issue on `Magento\Backend\Model\Menu`. Please find below the module:
[Magz.zip](https://github.com/magento/magento2/files/8480517/Magz.zip)

3. After enabling the plugin, in the admin panel, there is no error:
![image](https://user-images.githubusercontent.com/51681618/163157136-b941eaf4-ff40-4073-92fb-1cf657e2bbb5.png)

Let us know in case we have missed anything.

Thanks

**Comment by rav-redchamps** [comment]
This still repeats for me with your attached module. I am on PHP version 8.1.2

On which PHP version you are trying?

**Comment by engcom-Hotel** [comment]
Hello @rav-redchamps,

We have again tried to reproduce the issue and the issue is reproducible for us with the given steps in the main description. Hence confirming the issue.

PHP Version:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/51681618/163322638-0a400bca-700b-4aae-8e43-2ddcd3b68f5f.png">

Magento Version:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/51681618/163322709-3fba5066-7432-4838-abee-0f941f122453.png">

Error:
![image](https://user-images.githubusercontent.com/51681618/163322735-fa22733a-07ee-4ea2-b12f-c00da202e2cf.png)

Thanks

**Comment by engcom-Alfa** [comment]
Hello @rav-redchamps 
As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2855` by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2855&type=commits

Based on Jira, target version is 2.4.5

**Comment by lfolco** [comment]
Is there a PR for this issue that could be used to create a patch?

**Comment by engcom-Hotel** [comment]
Hello @lfolco,

Please find attached the patch file. This may help you.

[35292.patch.txt](https://github.com/magento/magento2/files/9604499/35292.patch.txt)

This is fetched from the internal PR.

Thanks

**Comment by lfolco** [comment]
thank you!

**Comment by hostep** [comment]
@lfolco: the merge commit is this one: https://github.com/magento/magento2/commit/e4d10436897c1e11e46cc871a44135a92a063a5f, which seems to be much cleaner that the patch that was provided earlier.

**Comment by BernardRobbins** [comment]
In case anyone else needs this patch.
[35292.patch.txt](https://github.com/user-attachments/files/16614634/35292.patch.txt)
Copy to your root dir. 
`patch -p1 -t < 35292.patch.txt`
