### ISSUE TITLE
Email Reminder Not sending automatically

### ISSUE THREAD

**Issue by Manjula-kalyan** [magento/magento2#35291]
### Preconditions (*)

1.Magento ver. 2.4.3-p1
2.Enterprise Edition

### Steps to reproduce (*)

1.Configured New Email reminder- as per magento devdocs-https://docs.magento.com/user-guide/marketing/email-reminder-rules.html
2.verified  Automated Email Reminder Rules - as per devdocs-https://docs.magento.com/user-guide/marketing/email-reminder-rules-configure.html

### Expected result (*)

1. send_notification cron should run every 5 mins but it's not running
2."Run now" button in the rule working but reminder email is not sending automatically

### Actual result (*)

1. Didn't receive any email after configured the rule.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Manjula-kalyan ,
We are closing this issue as there has been no latest update on the same.
Thank you.
