### ISSUE TITLE
Magento 2.4.4 under PHP 8.1.4

### ISSUE THREAD

**Issue by MartinKuhl** [magento/magento2#35295]
### Preconditions (*)

1. PHP  8.1.0 / 8.1.1 / 8.1.3 & 8.1.4
2. Magento 2.4.4 fresh installation via composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . 2.4.4

### Steps to reproduce (*)

1. Fresh installation of M2.4.4 under PHP  8.1.0 / 8.1.1 / 8.1.3 & 8.1.4
2. get Installation files via ZIP oder composer
3. try to call magento binary under bin/magento with any argument

### Actual result (*)

Error message:
/var/www/html/bin/magento --version
Call to undefined function Laminas\Http\PhpEnvironment\apache_request_headers()#0 /var/www/html/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(101): Laminas\Http\PhpEnvironment\Request->setServer(Object(Laminas\Stdlib\Parameters))
#1 /var/www/html/vendor/laminas/laminas-mvc/src/Service/RequestFactory.php(21): Laminas\Http\PhpEnvironment\Request->__construct()
#2 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(612): Laminas\Mvc\Service\RequestFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Request', NULL)
#3 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('Request')
#4 /var/www/html/setup/src/Magento/Setup/Application.php(48): Laminas\ServiceManager\ServiceManager->get('Request')
#5 /var/www/html/vendor/magento/framework/Console/Cli.php(80): Magento\Setup\Application->bootstrap(Array)
#6 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#7 {main}

---

**Comment by MartinKuhl** [comment]
error in self made docker base image

**Comment by poshyvailo** [comment]
@magento give me 2.4-develop instanc
