### ISSUE TITLE
Replace variables from API response

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35290]
### Summary (*)
Unable to replace  {{store direct_url="about-magento-demo-store"}} this in api response.

I am using headless approach to render frontend using vue js.  i am using api to get page and block content and it have {{store direct_url="about-magento-demo-store"}} in content area.

### Examples (*)

```
{
    "id": 1,
    "identifier": "footer_links",
    "title": "Footer Links",
    "content": "\n<ul>\n    <li><a href=\"{{store direct_url=\"about-magento-demo-store\"}}\">About Us</a></li>\n    <li><a href=\"{{store direct_url=\"customer-service\"}}\">Customer Service</a></li>\n<li class=\"last privacy\"><a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy</a></li>\r\n</ul>",
    "creation_time": "2015-01-02 14:23:30",
    "update_time": "2015-01-02 14:23:31",
    "active": true
}
```
### Proposed solution

I don't want to get this variables in the content area.
and also how i get all pages and blocks information for the specific store using API

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @hemendraajmera,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @hemendraajmera,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
