### ISSUE TITLE
Admin notifications for asynchronous operations causing critical performance issues

### ISSUE THREAD

**Issue by jarnooravainen** [magento/magento2#35301]
### Preconditions (*)

1. Magento 2.4.3-p1 Open Source installed
2. Integration created that has same ID as admin user (integration.integration_id == admin_user.user_id)
3. Integration used to import big number of entities via asynchronous API to get for example 20 000 rows to magento_bulk table

### Steps to reproduce (*)

1. Login as admin that has same ID as integration used for bulk API updates
2. Observe 60-100 second page load time when reloading any admin page

### Expected result (*)

1. Admin notification module queries bulk operations related to admin user only

### Actual result (*)

1. Admin notification module queries bulk operations by user ID and gets all bulk rows related to integration also
2. Processing huge number of bulk rows will render admin account unusable

New Relic trace:
![image](https://user-images.githubusercontent.com/12761665/163208379-600abf5d-dafc-4b4e-b701-a80db1503d71.png)

### How to fix
User type condition should be included in DB query made by \Magento\Framework\Bulk\BulkStatusInterface::getBulksByUser to process bulk operations related to admin user only. Suggesting that user type argument is added to getBulksByUser method.

See https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/AsynchronousOperations/Model/ResourceModel/System/Message/Collection/Synchronized/Plugin.php#L93

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @jarnooravainen,
Thank you for logging an issue and kindly provide if you have any documentation that integration ID used for bulk API updates,and also how we can use Integration to import big number of entities via asynchronous API.


Regards.

**Comment by engcom-Bravo** [comment]
Hi @jarnooravainen,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by bartoszkubicki** [comment]
This is an issue on magento 2.4.5
