### ISSUE TITLE
`SQLSTATE[23000]: Integrity constraint violation:` error while running `sales_clean_orders` cron job 

### ISSUE THREAD

**Issue by Usik2203** [magento/magento2#35302]
### Preconditions (*)

I see next error while running `sales_clean_orders` cron job 
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES ()` 

### Steps to reproduce (*)

**1.** Set `Pending Payment Order Lifetime (minutes)` to `1 `
<img width="281" alt="Screenshot 2022-04-13 at 17 16 31" src="https://user-images.githubusercontent.com/13517181/163207085-24214ec5-8285-4cda-b409-bf00ccdb396b.png">
**2.** Set schedule for `sales_clean_orders` to `* * * * *` in `app/code/Magento/Sales/etc/crontab.xml:14`
**3.** Create `Cart Price Rule`  
<img width="275" alt="Screenshot 2022-04-13 at 17 51 58" src="https://user-images.githubusercontent.com/13517181/163208533-ed61da07-f7ef-419f-b8b3-4cf649a04c89.png">
<img width="241" alt="Screenshot 2022-04-13 at 17 52 45" src="https://user-images.githubusercontent.com/13517181/163208553-c893502f-7286-4fb7-bd56-b74dd4dbc308.png">
**4.** Login as Customer and place order with applied `Cart Price Rule `
<img width="219" alt="Screenshot 2022-04-13 at 17 57 32" src="https://user-images.githubusercontent.com/13517181/163209653-f9628956-efed-4bcc-a2a7-c2bf9e6e4968.png">
**5** Go to `sales_order` table and set status `pending_payment` for current order
<img width="281" alt="Screenshot 2022-04-13 at 17 59 45" src="https://user-images.githubusercontent.com/13517181/163210122-ed12bf71-9281-4526-895b-e8e4681f96b8.png">
**6** Go **Marketing -> Cart Price Rule** and remove `Cart Price Rule`
<img width="217" alt="Screenshot 2022-04-13 at 18 01 36" src="https://user-images.githubusercontent.com/13517181/163210581-45ba2476-f111-48b0-8bb0-9ca7a78138cf.png">
**6** Go to console and run `bin/magento cron:run --group="default"` 
<img width="191" alt="Screenshot 2022-04-13 at 18 04 46" src="https://user-images.githubusercontent.com/13517181/163211046-821057e9-004a-4070-b240-4839aeab75dd.png">
**7**   Go to `cron_schedule` table   you will see 
<img width="297" alt="Screenshot 2022-04-13 at 18 06 22" src="https://user-images.githubusercontent.com/13517181/163211365-a7b82c03-bde5-4421-a076-994e2618746e.png">

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES ()`

### Expected result (*)

I don't see mentioned error while running `sales_clean_orders` cron job

### Actual result (*)

<img width="297" alt="Screenshot 2022-04-13 at 18 06 22" src="https://user-images.githubusercontent.com/13517181/163211365-a7b82c03-bde5-4421-a076-994e2618746e.png">

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES ()`

### Related issues(*)
https://github.com/magento/magento2/issues/27918
https://github.com/magento/magento2/issues/19230
https://github.com/magento/magento2/issues/16779

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance
