### ISSUE TITLE
Wrong display on Magento 2 site

### ISSUE THREAD

**Issue by nFed** [magento/magento2#3530]
Hello,

After installing magento 2 on linux server - i get wrong display:
http://nbg.co.il/
![ghhgfshfs](https://cloud.githubusercontent.com/assets/4190176/13286844/8b196d06-db0c-11e5-92b3-35ad45fe2858.JPG)

php 5.5.30
apache version 2.4.16
linux

Thanks.

**Comment by mazhalai** [comment]
Please run `bin/magento setup:static-content:deploy` also make sure mod_rewrite is turned on.

**Comment by anjenehm** [comment]
Try also to set the rewrite_base in your .htaccess

**Comment by rganin** [comment]
Ensure that:
- you have mod_rewrite enabled
- access rights to pub/\* directory are correctly set and httpd thread has access (selinux can make some troubles as well)
- you are running in non-production mode ("developer" or "default"). For production mode static content should be pre-deployed with `php -f bin/magento setup:static-content:deploy`

**Comment by nFed** [comment]
Thank you all

**Comment by mazhalai** [comment]
@nFed you have indicated that your problem has been resolved. Closing this ticket. If you still have issues, please create a new ticket.
