### ISSUE TITLE
Quote item in checkout_cart_product_add_after contains incorrect values

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#3531]
I've created observer for event `checkout_cart_product_add_after` to set custom price for quote item. But `$observer->getEvent()->getData('quote_item')` shows me old data, for ex. - I have product with base price=100$, and tier price (qty>=2) = 50$. When I add product to cart in the first time, quote price = 0, in the 2nd time - 100$ (but should be 50$), in the 3rd time - 50$.
My events.xml
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="checkout_cart_product_add_after">
        <observer name="my" instance="My\ProductDesigner\Observer\Frontend\AddProductAfterObserver"/>
    </event>
</config>`
Code of observer:
`namespace My\ProductDesigner\Observer\Frontend;

use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Registry;

class AddProductAfterObserver  implements ObserverInterface
{
public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $item = $observer->getEvent()->getData('quote_item');
        $item = ( $item->getParentItem() ? $item->getParentItem() : $item );
        $item->getPrice(); // here I got old value
    }
}`

**Comment by ishakhsuvarov** [comment]
@Katerina1993 Thank you for reporting the issue. We have created an internal ticket `MAGETWO-49809` to investigate.

**Comment by ishakhsuvarov** [comment]
Hi @Katerina1993
We have investigated the problem you described with the `checkout_cart_product_add_after` event. Cart and item in question are not yet saved at the moment when the event is fired, leading to inconsistent price information at that moment, as the prices are calculated on cart save in the most of the cases. The main purpose of this event is to add additional information to the item.

You may use a different event to get accurate prices, for example `checkout_cart_save_after`, which is also fired in the add to cart controller. Another option would be creating a plugin for `\Magento\Quote\Api\CartRepositoryInterface::save`.

**Comment by ishakhsuvarov** [comment]
@Katerina1993 Closing this ticket for now. Please reopen if you have any additional questions.
