### ISSUE TITLE
Disable max session size in admin - Unable to login to admin anymore

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35312]
### Preconditions (*)

1.
2. Magento 2.4-develop, 2,4,4

### Steps to reproduce (*)

1. Store > Settings > Configuration. - Advanced and choose System - Security - set Max Session Size in Admin to 0 and save
2. Login to admin

### Expected result (*)

1. [Screenshots, logs or description]
2. Login works

### Actual result (*)

1. [Screenshots, logs or description]
2. Unable to login

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mgwalk** [comment]
I am getting the same issue.
I see admin login
Enter user and pass. 
Page looks like it just refreshes

**Comment by engcom-Delta** [comment]
Hi @engcom-November ,
We have verified this issue on Magento 2.4 develop and 2.4.4 instances. Found that issue is reproducible on both instances.
Hence issue is confirmed.
Please find the attaches screenshots for reference.
1. Login to admin
2. Store > Settings > Configuration. - Advanced and choose System - Security - set Max Session Size in Admin to 0 and save
<img width="1440" alt="Screenshot 2022-04-19 at 5 21 41 PM" src="https://user-images.githubusercontent.com/51681379/163998895-62dc4460-2708-44d7-91f9-6069bb7906d0.png">
3. observe that user logged out
4. Login to admin again
<img width="1440" alt="Screenshot 2022-04-19 at 5 34 35 PM" src="https://user-images.githubusercontent.com/51681379/163999607-cd57a298-aba0-4427-a16f-720c5a3ecba3.png">

**Comment by mgwalk** [comment]
I was able to fix by updating frontend and admin before upgrading to 2.4.4.  
I also had magefan blog which needed updated.

**Comment by nisha-vaghela** [comment]
@magento I am working on this

**Comment by hostep** [comment]
Possible solution from https://github.com/magento/magento2/issues/35414, credits to @advocat:

> Root Cause
> [magento2/lib/internal/Magento/Framework/Session/SaveHandler.php](https://github.com/magento/magento2/blob/7d80b877d7057e62555d3376f2be7e7be68838f0/lib/internal/Magento/Framework/Session/SaveHandler.php#L129)
>
> Line 129
>
> if ($sessionSize !== null && $sessionMaxSize < $sessionSize) { 
>
> Should be:
> 
> if ($sessionMaxSize !== null && $sessionMaxSize < $sessionSize) {

**Comment by MeetKamal** [comment]
HI @hostep 

For Magento 2.4.4 found that file below 
/vendor/magento/framework/Session/SaveHandler.php

**Comment by VincentMarmiesse** [comment]
> I had the same issue because I set the session size to 0 before this release to fix a different issue. You can update the value back to default via the cli to resolve this issue:
> 
> `bin/magento config:set system/security/max_session_size_admin 256000`

On my store, 256000 was not enough, and I have setted 512000.

Be careful, there is also a frontend limit: `system/security/max_session_size_storefront`.

**Comment by nisha-vaghela** [comment]
@magento give me test instance

**Comment by nisha-vaghela** [comment]
@magento give me 2.4-develop instance

**Comment by glo71317** [comment]
Based on the priority internal team is working on the automation test and will deliver soon for 2.4.5 release

**Comment by engcom-Alfa** [comment]
Hello @engcom-November 
As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2883` by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2883&type=commits

Based on Jira, target version is 2.4.5

**Comment by salesigniter** [comment]
Just as another note if the customer side session is at 0 or the system/security/max_session_size_storefront path you will get an error like this when adding to cart: There is an error. Please Contact store administrator coming from vendor/magento/framework/Session/SaveHandler.php:133 so it is really not obvious when debugging where this error is coming from, I'm adding this note hoping that when people google this issue this page will come up, again the fix it doing:

bin/magento config:set system/security/max_session_size_storefront 256000
