### ISSUE TITLE
Error too many redirects when attempting to setup redis for session storage

### ISSUE THREAD

**Issue by timothyfisherdev** [magento/magento2#35320]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento 2.3.3
2. Configure redis as session storage with the following config in `app/etc/env.php`:
```
...
'session' => [
    'save' => 'redis',
    'redis' => [
        'host' => '127.0.0.1',
        'port' => '6379',
        'password' => 'password',
        'timeout' => '2.5',
        'persistent_identifier' => '',
        'database' => '2',
        'compression_threshold' => '2048',
        'compression_library' => 'gzip',
        'log_level' => '1',
        'max_concurrency' => '500',
        'break_after_frontend' => '5',
        'break_after_adminhtml' => '30',
        'first_lifetime' => '600',
        'bot_first_lifetime' => '60',
        'bot_lifetime' => '7200',
        'disable_locking' => '0',
        'min_lifetime' => '60',
        'max_lifetime' => '2592000'
    ]
]
```

### Expected result (*)

1. Magento should use redis as session storage

### Actual result (*)

1. [Screenshots, logs or description]
2. Produces a "too many redirects" error when visiting any page on the site in a browser.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @timothyfisherdev ,
Thank you for raising an issue , we tried to reproduce the issue on magento 2.4 develop instance with redis session cache.
in fact it works much faster after setting up with redis , but we found different error in the logs.  Please review and confirm. 




configuration: 

<img width="573" alt="Screenshot 2022-06-07 at 8 09 18 PM" src="https://user-images.githubusercontent.com/51681379/172420801-d944cc46-6394-4404-b78c-6856463aece7.png">

frontend products: 
<img width="1440" alt="Screenshot 2022-06-07 at 9 03 27 PM" src="https://user-images.githubusercontent.com/51681379/172421513-09dd79a9-295c-4a7f-891c-d9fb78bd9f96.png">


logs:

<img width="1440" alt="Screenshot 2022-06-07 at 8 52 21 PM" src="https://user-images.githubusercontent.com/51681379/172421123-5dbc0053-120c-4e3b-9d0d-9587ae2722b3.png">
<img width="1440" alt="Screenshot 2022-06-07 at 8 56 50 PM" src="https://user-images.githubusercontent.com/51681379/172421207-7793e8b4-a421-4b2f-b116-b3f140742dc4.png">

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
