### ISSUE TITLE
jQuery UI Slider and SelectMenu Mapping is not correct in requirejs-config.js

### ISSUE THREAD

**Issue by pixopa** [magento/magento2#35327]
### Preconditions (*)

On Magento 2.4.4 release, jQuery UI Slider and SelectMenu Mapping is not correct in vendor/magento/module-theme/view/base/requirejs-config.js. This causes an error on frontend as jQuery slider and selectmenu modules do not get loaded and we see an error saying "$j(..).slider is not a function".

### Steps to reproduce (*)

Open vendor/magento/module-theme/view/base/requirejs-config.js

On line 42 you will notice the incorrect mapping -

'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/selectmenu',

### Expected result (*)

The correct mapping should be -

'jquery-ui-modules/selectmenu': 'jquery/ui-modules/widgets/selectmenu',
'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/slider',

### Actual result (*)

This causes an error on frontend where jQuery slider is used and shows an error saying "$j(..).slider is not a function".

<img width="1222" alt="Screenshot 2022-04-19 at 4 38 23 PM" src="https://user-images.githubusercontent.com/22843013/163991117-2a3bcc65-4215-4c43-81ea-991cd8d7e21e.png">

**Comment by pixopa** [comment]
Please try jQuery slider (https://jqueryui.com/slider/) not Magento Slide Show

**Comment by jorgb90** [comment]
We have the same issue as @pixopa which gets fixed when properly mapped as suggested.

**Comment by pixopa** [comment]
Your updated mapping is still wrong. The correct mapping should be -

'jquery-ui-modules/selectmenu': 'jquery/ui-modules/widgets/selectmenu',
'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/slider',


https://user-images.githubusercontent.com/22843013/163991117-2a3bcc65-4215-4c43-81ea-991cd8d7e21e.png

**Comment by pixopa** [comment]
Your updated mapping is still wrong. The correct mapping should be -

'jquery-ui-modules/selectmenu': 'jquery/ui-modules/widgets/selectmenu',
'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/slider',

https://user-images.githubusercontent.com/22843013/163991117-2a3bcc65-4215-4c43-81ea-991cd8d7e21e.png <https://user-images.githubusercontent.com/22843013/163991117-2a3bcc65-4215-4c43-81ea-991cd8d7e21e.png>

**Comment by engcom-Hotel** [comment]
Hello @pixopa,

Thanks for the update. I corrected it.

Thanks

**Comment by sheepfy** [comment]
I think also effect-size mapping is missing
