### ISSUE TITLE
【Priority issue】,2.4.3-p2,configurable product can't filter well,swatch small image not match with big image

### ISSUE THREAD

**Issue by mattqiu** [magento/magento2#35323]
### Preconditions (*)

1.magento 2.4.3-p2
2.PHP 7.4.18

firstly I use 2.4.1,I found this iusse,so I try to upgrade to check if you guys alrady fixed it.but it's still the same.but I found version 2.3.4 it's worked well 

### Steps to reproduce (*)

1.go https://www.murzic.com/men/handbags/all-handbags.html,and filter color in left
2. check the small image and the big image it's now match,just small part of them was wrong

### Expected result (*)

1. 
![`T{$5({@(A~`)F51 XUQJ5E](https://user-images.githubusercontent.com/2038610/163916776-6e64000d-1b46-4921-be1b-5ce5b1ecaf27.png)

2.
![VNR_{ZAH_6HB(B19~6EYT`9](https://user-images.githubusercontent.com/2038610/163916768-58cf9852-308c-4af4-a5c6-8716e70c4138.png)

### Actual result (*)

1. 
![`T{$5({@(A~`)F51 XUQJ5E](https://user-images.githubusercontent.com/2038610/163916783-7daca3d6-b8bd-471e-b6a7-90a4c9a287c8.png)

2.
![VN690URQC{2%BQTC(_N@%3V](https://user-images.githubusercontent.com/2038610/163916753-bc442ac9-d85d-482f-a818-fbc028b4bf42.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mattqiu** [comment]
Can anyone help me

**Comment by engcom-Delta** [comment]
Hi @mattqiu ,
Thank you for raising an issue and we tried to reproduce the issue on Magento 2.4 Develop instance, unfortunately issue is not reproducible , it works as expected.

Kindly refer the screenshots attached. Kindly help me to reproduce the issue with appropriate steps.

![Screenshot (145)](https://user-images.githubusercontent.com/51681379/172383458-a3647e63-f37c-4ecb-97f5-44c12b718fb8.png)
![Screenshot (146)](https://user-images.githubusercontent.com/51681379/172383512-bd1c1619-bb84-42b3-a426-e8a26189ee0c.png)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
