### ISSUE TITLE
Magento 2.4.4 admin panel - Uncaught SyntaxError: Unexpected token 'const'

### ISSUE THREAD

**Issue by sanchit-redmonks** [magento/magento2#35325]
### Summary (*)
Magento 2.4.4 running on PHP 8.1 in Production mode

If you enable the js bundling and minify the scripts. 
`php bin/magento config:set  dev/js/minify_files 1`
`php bin/magento config:set  dev/js/enable_js_bundling 1`

After running the deployment and logging into the admin panel. We can't click on any menue option. There is an error in the browser console: *Uncaught SyntaxError: Unexpected token 'const'*

### Preconditions (*)
1. PHP 8.1
2. Magento 2.4.4, 2.4-develop
3. Magento instace should be in production mode

### Steps to reproduce (*)
1. Enable JS bundling.
2. Minify the JS files
3. Run deployment
4. Login to the admin panel.

### Expected result (*)
We should be able to access admin panel without any error.

### Actual result (*)
We are getting the following error and not able to click on any menu option:

<img width="1437" alt="Admin Error" src="https://user-images.githubusercontent.com/89576243/163936666-35d6fc3e-4454-4155-997a-52eb1855ad79.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4.4 version and 2.4-develop branch as well and the issue is reproducible.
Configured JS Bundling as per [devdocs](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html)
Login to admin - Unable to navigate to any other pages. None of the Menu options/buttons are working.
![image](https://user-images.githubusercontent.com/60198231/163947281-43e0d5b6-f96d-45ea-adb5-0d195e7c2208.png)

**Comment by softinfoline** [comment]
Here is the solution:-
[lib/web/jquery/bootstrap/collapse.js](https://github.com/magento/magento2/compare/2.4-develop...softinfoline:patch-1#diff-30853d5d372040a61dbdf9eb58b5840f3b533701024c13eb485b634929fd77cf)
@@ -32,7 +32,7 @@ define([
    const VERSION = '5.1.3'
    const NAME = 'collapse'
    const DATA_KEY = 'bs.collapse'
    const EVENT_KEY = `.${DATA_KEY}`
    const EVENT_KEY = `.${DATA_KEY}`;
    const DATA_API_KEY = '.data-api'

    const Default = {
@@ -45,17 +45,17 @@ define([
        parent: '(null|element)'
    }

    const EVENT_SHOW = `show${EVENT_KEY}`
    const EVENT_SHOWN = `shown${EVENT_KEY}`
    const EVENT_HIDE = `hide${EVENT_KEY}`
    const EVENT_HIDDEN = `hidden${EVENT_KEY}`
    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`
    const EVENT_SHOW = `show${EVENT_KEY}`;
    const EVENT_SHOWN = `shown${EVENT_KEY}`;
    const EVENT_HIDE = `hide${EVENT_KEY}`;
    const EVENT_HIDDEN = `hidden${EVENT_KEY}`;
    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`;

    const CLASS_NAME_SHOW = 'show'
    const CLASS_NAME_COLLAPSE = 'collapse'
    const CLASS_NAME_COLLAPSING = 'collapsing'
    const CLASS_NAME_COLLAPSED = 'collapsed'
    const CLASS_NAME_DEEPER_CHILDREN = `:scope .${CLASS_NAME_COLLAPSE} .${CLASS_NAME_COLLAPSE}`
    const CLASS_NAME_DEEPER_CHILDREN = `:scope .${CLASS_NAME_COLLAPSE} .${CLASS_NAME_COLLAPSE}`;
    const CLASS_NAME_HORIZONTAL = 'collapse-horizontal'

    const WIDTH = 'width'
@@ -204,10 +204,10 @@ define([
        }

        const capitalizedDimension = dimension[0].toUpperCase() + dimension.slice(1)
        const scrollSize = `scroll${capitalizedDimension}`
        const scrollSize = `scroll${capitalizedDimension}`;

        this._queueCallback(complete, this._element, true)
        this._element.style[dimension] = `${this._element[scrollSize]}px`
        this._element.style[dimension] = `${this._element[scrollSize]}px`;
    }

    Collapse.prototype.hide = function() {
@@ -222,7 +222,7 @@ define([

        const dimension = this._getDimension()

        this._element.style[dimension] = `${this._element.getBoundingClientRect()[dimension]}px`
        this._element.style[dimension] = `${this._element.getBoundingClientRect()[dimension]}px`;

        reflow(this._element)

and

https://github.com/magento/magento2/compare/2.4-develop...softinfoline:patch-2#diff-9491b738ecd44704ca31f811089a745495d6c5f1851224f71d2d15259d0c4a15

@@ -28,14 +28,14 @@ define([
    const VERSION = '5.1.3'
    const NAME = 'tab'
    const DATA_KEY = 'bs.tab'
    const EVENT_KEY = `.${DATA_KEY}`
    const EVENT_KEY = `.${DATA_KEY}`;
    const DATA_API_KEY = '.data-api'

    const EVENT_HIDE = `hide${EVENT_KEY}`
    const EVENT_HIDDEN = `hidden${EVENT_KEY}`
    const EVENT_SHOW = `show${EVENT_KEY}`
    const EVENT_SHOWN = `shown${EVENT_KEY}`
    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`
    const EVENT_HIDE = `hide${EVENT_KEY}`;
    const EVENT_HIDDEN = `hidden${EVENT_KEY}`;
    const EVENT_SHOW = `show${EVENT_KEY}`;
    const EVENT_SHOWN = `shown${EVENT_KEY}`;
    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`;

    const CLASS_NAME_DROPDOWN_MENU = 'dropdown-menu'
    const CLASS_NAME_ACTIVE = 'active'

**Comment by lagunacellar** [comment]
Yes, this solution works! Thanks!

**Comment by kolaente** [comment]
Is someone working on a PR to fix this?

**Comment by fredden** [comment]
@sidolov please can you confirm why this issue has been closed.

Is this fixed in https://github.com/magento/magento2/commit/faa7e0ee7f402ab518ad38f004467a26491d9ab4 (which introduced https://github.com/magento/magento2/commit/a806598ad9d2250897e7fc02ffd7fe5d89a8988f and https://github.com/magento/magento2/commit/26b484075a60b4a384ae1f43aa5cf3ff1fb1d8fa)? I can't see a corresponding pull request for this change.

What should we do about https://github.com/magento/magento2/pull/35540 (which fixes all cases not just those covered in 26b484075a60b4a384ae1f43aa5cf3ff1fb1d8fa and a806598ad9d2250897e7fc02ffd7fe5d89a8988f) ?

**Comment by technodelight** [comment]
This is still present in 2.4.4-p2

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi. Also facing this issue in 2.4.4-p2

**Comment by scottbolasevich** [comment]
same

**Comment by boneio** [comment]
Issue still present on 2.4.4-p3

**Comment by kaochiuan** [comment]
Issue still present on 2.4.4-p6

**Comment by kaochiuan** [comment]
Patch MDVA-44887

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-15/mdva-44887-uncaught-syntaxerror-unexpected-token-const-error-in-admin-panel.html?lang=en

**Comment by MacsHolding** [comment]
The problem persists on "Adobe Commerce ver. 2.4.4-p7" in production mode and PHP 8.1

Steps to reproduce:

- Enable JavaScript-Bundling
- Enable and minify the JS files
- Deploy and clear cache

The Issue: The admin user can’t click on any menu option. There is an error in the browser console: Uncaught SyntaxError: Unexpected token const.

Provided Patch MDVA-44887 did not fix the issue.

Steps to apply the Patch:

- `composer require magento/quality-patches`
- `./vendor/bin/magento-patches apply MDVA-44887`
- `./bin/magento cache:clean`

Check and test the Patch:

The command `./vendor/bin/magento-patches status` shows that the Patch MDVA-44887 was "Applied"

The Patch does not fix the Issue. The same Issue persists "The admin user can’t click on any menu option. There is an error in the browser console: Uncaught SyntaxError: Unexpected token const."

**Comment by onepack** [comment]
> The problem persists on "Adobe Commerce ver. 2.4.4-p7" in production mode and PHP 8.1
> 

Tested in 2.4.4-p9. Same issue persists.

**Comment by barryvdh** [comment]
I'm having this issue on Magento ver. 2.4.7-p2
