### ISSUE TITLE
Amazon integration not working

### ISSUE THREAD

**Issue by FrankieCSS** [magento/magento2#35336]
RE: M2E Pro
Magento ver. 2.3.4

Hi, 

Can anyone help, I'm having issues with bringing up my product catalogue on M2E pro for the Amazon integration side, eBay and my own website seem to just find and all synced up and running smoothly. 

Amazon doesn't even show any products or anything. I cant even remove Amazon and start again

Many thanks

**Comment by engcom-November** [comment]
Hi @FrankieCSS 
Thank you for reporting and collaboration. However, Amazon Integration is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
