### ISSUE TITLE
Facebook Business Extension not working on magento 2

### ISSUE THREAD

**Issue by wilsonssot** [magento/magento2#35331]
### Preconditions (*)

1.Magento Comunity ver. 2.3.5-p2
2.Have a business page and application on facebook.

### Steps to reproduce (*)

1. Install FBE through composer.
2. Connect FBE from magento to facebook.
3. Push products from stores->settings->configuration->facebook->Business Extension-> Push Products
### Expected result (*)

1. Catalog should be synchronize to facebook

### Actual result (*)

1. Receiving error in push response:
![image](https://user-images.githubusercontent.com/29804260/164048437-b1e6382b-422f-42de-a707-c7c360661aef.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @wilsonssot 
Thank you for reporting and collaboration. However, Facebook Business is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
