### ISSUE TITLE
2.4.3-p2 missing patches MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch & MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#35341]
### Preconditions (*)

1. Magento 2.4.3-p2 on premise enterprise/open source
2. php 7.4

### Steps to reproduce (*)

1. Patch magento from 2.4.3-p1 to 2.4.3-p2. Check release notes: https://devdocs.magento.com/guides/v2.4/release-notes/2-4-3-p2.html.
2. When reading release notes it says the patches have been applied.
3. Remove patches: MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch & MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch
4. Should still be secure.

### Expected result (*)

1. MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch  &  MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch are retrofitted to the m2.4.3-p2 release.

### Actual result (*)

1. MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch  &  MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch are not retrofitted to the m2.4.3-p2 release. 

Am I looking in the wrong place or are the security patches for https://helpx.adobe.com/security/products/magento/apsb22-12.html missing in all the latest Magento releases? The changes introduced by those patches don't seem to exist in 2.4.3-p2 and 2.4.4. For example, the existing blockDirective method was renamed to resolveBlockDirective and a new blockDirective method was added in vendor/magento/module-email/Model/Template/Filter.php
The blockDirective method hasn't been touched in 8 years in the magento 2 repo according to a git blame https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/Model/Template/Filter.php#L403.

When looking into the release notes of 2.4.3-p2, MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch  &  MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch should be included: https://devdocs.magento.com/guides/v2.4/release-notes/2-4-3-p2.html. 

Related issue:
* https://github.com/magento/magento2/issues/35340

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by leonhelmus** [comment]
A collegue of mine said its the same for 2.4.4.

**Comment by nathanjosiah** [comment]
The patches are not present because we chose to implement a more comprehensive fix in the 2.3.7-p3/2.4.3-p2/2.4.4 release. The hotfixes will not and should not be applied to these releases.

**Comment by leonhelmus** [comment]
@nathanjosiah Good to know could you share a commit that resolved it. This way i can inform internally. 

I have also added two other issues:
https://github.com/magento/magento2/issues/35343
https://github.com/magento/magento2/issues/35340

**Comment by leonhelmus** [comment]
@nathanjosiah It seems for cloud projects it still gets applied, see : 
https://github.com/leonhelmus/magento-cloud-patches

I will make a PR to resolve it.

**Comment by leonhelmus** [comment]
@hostep What do you think?

**Comment by hostep** [comment]
No idea, I don't work with Magento Cloud, but if the patch still applies on 2.4.3-p2 for Magento Cloud, then there is probably something wrong on their end. So wait a bit until somebody reviews your PR and gives some feedback there 😉

**Comment by nathanjosiah** [comment]
@BaDos can you take a look?

**Comment by leonhelmus** [comment]
Any updates on this?

**Comment by gbobts** [comment]
> The patches are not present because we chose to implement a more comprehensive fix in the 2.3.7-p3/2.4.3-p2/2.4.4 release. The hotfixes will not and should not be applied to these releases.

Could you let us know where the changes have been applied, such as patch MDVA-43395 is not required anymore ? Is it with applyModifiers method ?
