### ISSUE TITLE
Error with loading order via loadByIncrementId

### ISSUE THREAD

**Issue by Grohotun** [magento/magento2#3534]
\Magento\Sales\Model\OrderFactory $orderFactory

$order = $this->_orderFactory->create()->loadByIncrementId(000000013)

echo $order->getId();

returns 11 (but not 13)

But in sales_order - all is good.

If echo  $order->getPayment()->getMethodInstance()->getCode()    - result is 'substitution' - method, which was never used.

![2016-02-24 19 22 26](https://cloud.githubusercontent.com/assets/11591042/13292232/022a4ab8-db2c-11e5-8360-c5f713763b26.png)

**Comment by Mulderua** [comment]
Hi @Grohotun, we cannot reproduce your issue. 
For properly data retrieving you should use \Magento\Sales\Model\OrderRepository::getList(\Magento\Framework\Api\SearchCriteria $searchCriteria)  and Magento\Framework\Api\SearchCriteriaBuilder

For example

```
$searchCriteria = $this->searchCriteriaBuilder->addFilter('increment_id', '000000001', 'eq')->create();
$orderList = $this->orderRepository->getList($searchCriteria);
echo $orderList->getFirstItem()->getIncrementId();
```

Repositories are the best way to work with data in Magento 2.

**Comment by Grohotun** [comment]
Hi, @Mulderua 
I've just tested on 2.0.6 version - my code works well.
So, I think, that was bug in 2.0.2 version and it was somehow fixed.
