### ISSUE TITLE
I can't save product description fields in mangento backend

### ISSUE THREAD

**Issue by jgutierrezs** [magento/magento2#35350]
I can save a new product as long as I don't enter Description, Short Description or Image Description. If I add any description I don't get any response from Magento and it freezes.

### Preconditions (*)

1. Magento 2.4.4
2. PHP 8.0
3. MariaDB 10.4
4. Elasticsearch 7.9

### Steps to reproduce (*)

1. Add Product
2. Add Short Description or Description or Description Image
3. Save

### Expected result (*)

1. Successfully saved the product.
2.

### Actual result (*)

1. Does not save the product.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jgutierrezs** [comment]
I have a new update. This only happens with a custom user, but if I do it as an administrator this bug does not happen.

**Comment by engcom-Delta** [comment]
Hi @jgutierrezs ,
We have tried to reproduce the issue on Magento 2.4.4 ,unfortunately issue is not reproducible.Hence request to review the provided steps to reproduce it.

Please find the screenshot for reference.
<img width="1440" alt="Screenshot 2022-04-22 at 3 24 42 PM" src="https://user-images.githubusercontent.com/51681379/164687313-bc33927b-65c2-45b9-bd80-c1d3fcd7a760.png">
<img width="1440" alt="Screenshot 2022-04-22 at 3 25 12 PM" src="https://user-images.githubusercontent.com/51681379/164687390-2e378fa9-f334-4bfe-90fa-7be61f96d396.png">

**Comment by engcom-Delta** [comment]
Hi @jgutierrezs ,
Thank you for confirming on user . Could you please provide more details on custom user? What does mean customer user ? his role when compared to Admin?

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Comment by fvlasie** [comment]
I resolved this same issue on my Magento server by running permissions fix: https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/file-system/configure-permissions
