### ISSUE TITLE
Documentation and code are conflicting

### ISSUE THREAD

**Issue by lollar** [magento/magento2#35357]
### Summary (*)
The documentation and code implementation do not match and make for an extremely frustrating and difficult debugging experience. In the getting started [documentation](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-oauth.html), it states that the OAuth Signature method _must be_ `HMAC-SHA1` yet, in the code, only `HMAC-SHA256` is supported. Furthermore, making such a major change to OAuth support in a patch version upgrade severly violates semver. 

### Examples (*)
![Screenshot from 2022-04-22 14-00-48](https://user-images.githubusercontent.com/24404416/164786162-a852e984-e0ec-4cf5-8fd8-c6c9aa494ad1.png)

![Screenshot from 2022-04-22 14-05-07](https://user-images.githubusercontent.com/24404416/164786265-3279a5a2-b90a-4245-b24c-fa2c0b64dcc0.png)

### Proposed solution
Keep documentation updated so that it is actually usable (from what I can tell, SHA1 has never been the _only_ supported method for magento2), and don't make breaking changes in a patch version upgrade.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment]
I completely agree! There is no mentioning in the release notes of dropping SHA1.. There are a lot of integrations shops rely on which may break with these kind of changes.

**Comment by jajajaime** [comment]
I second this! I spent more time than needed trying to figure out why my requests were not working.

**Comment by engcom-November** [comment]
Hi @lollar ,

Thank you for reporting and collaboration. Above Mentioned [page](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-oauth.html) has been moved to this [page](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-oauth/) and has been updated with "HMAC-SHA256" only as a supported method. Also verified other [docs](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/) but could not find anywhere mentioning HMAC-SHA1 as the supported method.
Kindly recheck the docs again and provide the docs links mentioning HMAC-SHA1 as the supported method if any.
Thank you.

**Comment by jajajaime** [comment]
I can see one page that still shows HMAC-SHA1:
https://developer.adobe.com/commerce/webapi/get-started/authentication/oauth-errors/#oauth-error-codes
