### ISSUE TITLE
Magento 2.4-x - Changing any configuration from admin and reindex - version changing to 1.0.0+no-version-set

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35353]
### Preconditions (*)

2.4-develop branch

### Steps to reproduce (*)

**Intermittent issue:** Changing any Store configuration from admin in 2.4-develop branch - reindex and cache flush - 2.4-develop version is getting changed to 1.0.0+no-version-set
1. Ex: Set the Price scope to website and save  (Stores - Configuration - Catalog - Catalog)
2. Reindex and cache flush
3. Setup multi store (with different websites) [ref doc](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html)
4. reindex and cache flush

### Expected result (*)

1. [Screenshots, logs or description]
2. Version should remain 2.4-develop

### Actual result (*)

1. Version changing back to 1.0.0+no-version-set
![image](https://user-images.githubusercontent.com/60198231/164723157-efcfec1e-a2ac-4d48-a2de-fc64ac09cd3a.png)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance
without magento-commerce/magento2-sample-data, magento-commerce/magento2-sample-data-ee

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @engcom-November,

We have tried to reproduce the issue on the cloud Magento 2.4-develop instance with the mentioned steps but for us, the version is not changing. Please have a look at the below screenshots for reference:

### Initial dashboard when Magento instance prepared:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/51681618/166680955-9abd5912-21a5-4dd5-838c-4aa7a8518bb6.png">

### After making changes in the configuration as well as creating stores referring [this article](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html):

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/51681618/166681149-f8975116-0423-425e-9575-8d02895f71c0.png">

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @engcom-Hotel ,
Unable to reproduce the issue on Magento cloud instance but is reproducible to me when cloned from [repository.](https://github.com/magento/magento2) Verified this today by downloading 2.4-develop from https://github.com/magento/magento2/ and is still reproducible. Kindly recheck.
Thank you.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento Give me 2.4-Develop Instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Zaahed** [comment]
@magento I'm working on this

**Comment by Zaahed** [comment]
This only happens on my local environment if the current working directory `getcwd()` is not set to the Magento 2 root directory. See line 306 in the `Composer/Factory` class. If you set `$cwd` to the Magento 2 root directory, it will return the correct version, even after flushing the cache.

**Comment by engcom-Bravo** [comment]
Hi @engcom-November,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Version remains 2.4-develop.

Hence we are closing this issue.

Thanks.
