### ISSUE TITLE
Unable to apply data patch Magento\BundleSampleData

### ISSUE THREAD

**Issue by kiakahaDZ** [magento/magento2#35360]
### Preconditions (*)
1. Magento 2.4.3-p1
2. windows 10
3. xampp 
4. PHP 7.4.9 

### Steps to reproduce (*)
the steps is like Magento docs for installing sample data
1. php bin/magento sampledata:deploy
2. php bin/magento setup:upgrade

### Expected result (*)
we Expect that after executing the first command successfully and start executing the second don't work normally and get the error at the magento_bundle sample data  

### Actual result (*)
![image](https://user-images.githubusercontent.com/46278484/164974573-44f07a8a-5511-4268-8bb4-d90f831ca113.png)

i get after  php bin/magento setup:upgrade
```
Unable to apply data patch Magento\BundleSampleData\Setup\Patch\Data\InstallBundleSampleData for module Magento_BundleSampleData. Original exception message: Rolled back transaction has not be
en completed correctly.
```

---
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment]
Verified the issue on both Magento 2.4-develop and 2.4.3-p1 instances but cannot able to reproduce the issue.
Magento 2.4.3-p1 - Sample data installed successfully using mentioned steps in description
[Reference doc](https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-composer.html)
![image](https://user-images.githubusercontent.com/60198231/165282843-62467fd6-f003-4008-b0ee-c93cc59e75c8.png)

Magento 2.4-develop - Sample data installed successfully using [ref doc](https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-clone.html)

@kiakahaDZ kindly recheck the issue again and provide missing steps / Configuration details. Also please check [System Requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) that are required to be installed for specific magento versions and if any third party modules / extensions added is causing this issue.
Thank you.

**Comment by kiakahaDZ** [comment]
@engcom-November Sample data installed successfully using the second option docs description, but when using the first option using composer does not work, I have given all steps to reproduce the issue, such I have respect the [System Requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html), and the project is a fresh one no any third party modules/extensions added, but thanks anyway.
