### ISSUE TITLE
Magento 2.3.5-p2 Deleted ElasticSearch index breaks Category landing page grid

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#35375]
### Summary
We are using ElasticCloud as our Search Provider, but from other issues (https://github.com/magento/magento2/issues/35248) it seems like a Magento issue an not specific to having ElasticSearch on the same server or 3rd party. 

A single missing ElasticSearch index should not break the product display on every Category landing page - this seems like poor handling of exceptions by Magento.

### Preconditions (*)

1.  Magento 2.3.5-p2
2. ElasticSearch 7 

### Steps to reproduce (*)

1. Reindex via the cli
2. Via the cli, remove an index from ElasticSearch using a curl `DELETE` request
3. Reindex via the cli

### Expected result (*)

1. Reindexing is successful
2. Products are shown on the Category landing page

### Actual result (*)

1. Reindexing throws a CRITICAL exception for the missing index:
`main.CRITICAL: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [_index_name_]`
2. Products are not visible on the Category landing pages

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @nbennett25 ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
