### ISSUE TITLE
magento 2 plus search event observer not getting the same data as store  front end. 

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35379]
### Summary (*) 
I want to use the magneto search event in the magneto modules development 

### Examples (*)
 Yes I already build the modules but still, I am not able to perform the search into a plugin can you please see this code or provide me an article there has a working search operation

https://github.com/Sanjay-100/magento2_search/blob/main/Observer/Searchdispatch.php

here demo modules code I build you can test this one https://github.com/Sanjay-100/magento2_search

I want to use the Magento search result in my Magento modules code

### Proposed solution
store front end side search result I need same into the plugin search event observer 

---
Please provide

**Comment by engcom-Hotel** [comment]
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
