### ISSUE TITLE
[Magento 2.4.4] MQ consumers run into issue "Deprecated Functionality: trim() .. magento/framework-amqp/Config.php on line 143" on PHP 8.1

### ISSUE THREAD

**Issue by vadimjustus** [magento/magento2#35380]
### Preconditions (*)

1. Magento 2.4.4
2. PHP 8.1

### Steps to reproduce (*)

1. Install fresh (vanilla) Magento instance
1.1 ` composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <install-directory-name>`
1.2 run install with AMQP: e.g. `bin/magento setup:install --base-url="http://magento-ce.test/" --base-url-secure="https://magento-ce.test/" --use-secure-admin=1 --use-rewrites=1 --use-secure=1 --db-host="127.0.0.1" --db-name=magento_ce --db-user=root --db-password=root --backend-frontname=admin --admin-firstname=admin --admin-lastname=admin --admin-email=admin@magento-ce.test --admin-user=admin --admin-password=admin123 --language=en_US --currency=EUR --timezone=Europe/Berlin --amqp-host=localhost --amqp-port=5672 --amqp-user=admin --amqp-password=admin --amqp-virtualhost=magento_ce --elasticsearch-host=localhost --elasticsearch-port=9207 --session-save=redis --session-save-redis-host=localhost --session-save-redis-port=6379 --session-save-redis-db=0 --cache-backend=redis --cache-backend-redis-server=localhost --cache-backend-redis-port=6379 --cache-backend-redis-db=1 --page-cache=redis --page-cache-redis-server=localhost --page-cache-redis-port=6379 --page-cache-redis-db=2 --cleanup-database`
2. Start MQ consumer like: `bin/magento queue:consumer:start async.operations.all`

### Expected result (*)

1. Consumer starts and keeps running

### Actual result (*)

1. Start of the consumer breaks with following error
```
In ErrorHandler.php line 61:
                                                                                                    
  Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is depre  
  cated in .../vendor/magento/framework-amqp/Config.php on line 143  
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @vadimjustus,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in both Magento 2.4.4 and 2.4-develop branches and the issue is reproducible for us. We have followed the below steps in order to reproduce the issue:
1. Install Magento via the below command (configure RabbitMQ while installing Magento, refer [the doc](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/install-rabbitmq.html)):
```
bin/magento setup:install --base-url=http://local.magento2ce9.com --db-host=localhost --db-name=magento2ee_9 --db-user=root --db-password= --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=admin@123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin --amqp-host=localhost --amqp-port=5672 --amqp-user=guest --amqp-password=guest
```
2. Run command `bin/magento queue:consumers:start async.operations.all`
3. It will return the below fatal error:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/51681618/165557689-58fc874e-f57e-4781-8cb6-57c5024a2c79.png">

Hence confirming the issue.

Thanks

**Comment by adamiwaniszyn** [comment]
For fix it in installation or env.php in amqp section needs to be added:
`'ssl' => true/false,`

there is checking if this option is set:
`$sslEnabled = trim($this->getValue(self::SSL)) === 'true';`

**Comment by vadimjustus** [comment]
> For fix it in installation or env.php in amqp section needs to be added: `'ssl' => true/false,`
> 
> there is checking if this option is set: `$sslEnabled = trim($this->getValue(self::SSL)) === 'true';`

True, this is a workaround for this issue. But the bug is still there and needs to be fixed.
@adamiwaniszyn Thank you for the hint!
