### ISSUE TITLE
Javascript minimizing 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3538]
There is a bug with the minimizing of Javascript in production mode. 
When the option of minimizing javascript is enabled, Magento 2 will automatically search for the .min.js files. However those files aren't generated when the option is enabled. 
For this reason the administrator isn't able to change the option back to disabled. 

Solution to this problem is to acces the database table core_config_data and set the key dev/js/minify_files back to 0 or 1 depends on your default setting.

I hope someone can fix this issue.

Regards,

Michiel

**Comment by rganin** [comment]
This is not a bug, switching to production mode presumes that all static assets are pre-deployed `php -f bin/magento setup:static-content:deploy` command that deploys static files to pub/ directories and minifies or merges them regarding config settings. You can use `php -f bin/magento deploy:mode:set production` command to switch modes, it includes static deployment process.

**Comment by MomotenkoNatalia** [comment]
@MichielTG Please let us know if this helps.

**Comment by ghost** [comment]
Thank you for your reply. For some reason I'm unable to test this solution because the deployment of the production mode fails please see '#3850'.
I will let you know when I have more information.
