### ISSUE TITLE
\Magento\Framework\Lock\Backend\FileLock::isLocked unlocks which is not intended to happen

### ISSUE THREAD

**Issue by kanevbg** [magento/magento2#35397]
![image](https://user-images.githubusercontent.com/11477130/165775111-ad4843af-e2a3-441d-acaa-02509535b893.png)

Trying to unlock something just because someone asked `is it is locked?` have no point at all. Yeah if the call to `isLocked` is from another process it may not cause issue, but what if it is from the same process (which is totally needed to be supported by the Magento framework)? Eg, see other implementations for `\Magento\Framework\Lock\LockManagerInterface::isLocked`, for them no such `tryToUnlock` instruction is performed.

It seems it was supposed to be:
`if (!$result) $this->tryToUnlock($fileResource);`
Or in words: if my asking for locking status resulted in lock than try to unlock now in order to leave the original state for the lock ID and return `false` for the `isLocked` call.

**Comment by engcom-Hotel** [comment]
Hello @kanevbg,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @kanevbg,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by kanevbg** [comment]
@engcom-Hotel Please bring some core developer to take a look at this. I will be here to communicate and work on this. Believe me this very likely to be hidden issue messing up the overall stability of the platform when the FileSystem locker implementation is used.

**Comment by engcom-Hotel** [comment]
Sure @kanevbg,

But we need more details on this issue as mentioned in [this comment](https://github.com/magento/magento2/issues/35397#issuecomment-1114708992). Please provide the same we will analyze the issue more.

Thanks

**Comment by hostep** [comment]
@kandy, @ishakhsuvarov, @sidolov: anyone willing to want to work with @kanevbg to figure out what's going on exactly with this issue?

I can agree that when you call `isLocked`, you don't expect something to happen to the lock. So calling `tryToUnlock` inside it makes not that much sense, unless it's to unlock the lock that got created by the call of `tryToLock`, right?

So the `tryToUnlock` line should probably be moved up to just underneath the `$result = false` line so it doesn't trigger when a lock already existed.

**Comment by kanevbg** [comment]
@hostep Absolutely right. Your proposal is logically equivalent to my.

I'd try to find time to write something reproducible and share here. Currently I can only add one more thought: to get in problematic state, the process which acquired lock should ask if it is locked (using isLocked method) and this should result in unexpected lock release. After the isLocked call I believe it is best to test with native PHP function if the lock exists, and if it's not than that confirms the problem.

**Comment by kanevbg** [comment]
I have been doing some testing and was unable to drive the system to behave incorrectly, however the tryToUnlock operation is redundant when there was already a lock. What saves from the bug to appear seems to be that the file descriptor is opened by the `$fileResource` saved in the `\Magento\Framework\Lock\Backend\FileLock::$locks` property which likely makes that the lock still persist until the process exit although the LOCK_UN was executed successfully from tryToUnlock call in isLocked. That's the only difference between unlock and tryToUnlock.
