### ISSUE TITLE
Error: Call to a member function setScopeFilter()

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#35402]
### Preconditions (*)
1. Magento 2.4.4 (Upgrade from 2.4.3-p1)
2. Multi-store setup

### Steps to reproduce (*)
1. Have existing orders or customers
3. Create a new order through a customer or reorder an existing order in the backend

### Expected result (*)
1. Can create order for this specific customer

### Actual result (*)
1. main.CRITICAL: Error: Call to a member function setScopeFilter() on null in /home/xxxxxx/public_html/var/view_preprocessed/pub/static/vendor/magento/module-sales/view/adminhtml/templates/order/create/form/address.phtml:1

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

> Stack trace:
#0 /home/xxxxxx/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include()
#1 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#2 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#3 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#4 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#5 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#6 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Billing/Address/Interceptor.php(23): Magento\Framework\View\Element\Template->fetchView()
#7 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->fetchView()
#8 /home/xxxxxx/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#9 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#10 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#11 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#12 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Billing/Address/Interceptor.php(32): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address\Interceptor->toHtml()
#14 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#15 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#18 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /home/xxxxxx/public_html/var/view_preprocessed/pub/static/vendor/magento/module-sales/view/adminhtml/templates/order/create/data.phtml(5): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /home/xxxxxx/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/xxxxxx/pu...')
#21 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#22 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#23 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#24 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#25 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#26 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Data/Interceptor.php(23): Magento\Framework\View\Element\Template->fetchView()
#27 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->fetchView()
#28 /home/xxxxxx/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#29 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#30 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#31 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#32 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Data/Interceptor.php(32): Magento\Framework\View\Element\AbstractBlock->toHtml()
#33 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Sales\Block\Adminhtml\Order\Create\Data\Interceptor->toHtml()
#34 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#35 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#36 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#37 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#38 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#39 /home/xxxxxx/public_html/var/view_preprocessed/pub/static/vendor/magento/module-sales/view/adminhtml/templates/order/create/form.phtml(1): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#40 /home/xxxxxx/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/xxxxxx/pu...')
#41 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#42 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#43 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#44 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#45 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#46 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Form/Interceptor.php(23): Magento\Framework\View\Element\Template->fetchView()
#47 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->fetchView()
#48 /home/xxxxxx/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#49 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#50 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#51 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#52 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Form/Interceptor.php(32): Magento\Framework\View\Element\AbstractBlock->toHtml()
#53 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor->toHtml()
#54 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#55 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#58 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /home/xxxxxx/public_html/vendor/magento/module-backend/Block/Widget/Form/Container.php(220): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#60 /home/xxxxxx/public_html/var/view_preprocessed/pub/static/vendor/magento/module-backend/view/adminhtml/templates/widget/form/container.phtml(1): Magento\Backend\Block\Widget\Form\Container->getFormHtml()
#61 /home/xxxxxx/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/xxxxxx/pu...')
#62 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#63 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#64 /home/xxxxxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#65 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#66 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#67 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(23): Magento\Framework\View\Element\Template->fetchView()
#68 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->fetchView()
#69 /home/xxxxxx/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#70 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#71 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#72 /home/xxxxxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#73 /home/xxxxxx/public_html/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Interceptor.php(32): Magento\Framework\View\Element\AbstractBlock->toHtml()
#74 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Sales\Block\Adminhtml\Order\Create\Interceptor->toHtml()
#75 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#76 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#77 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#78 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#79 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#80 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#81 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#82 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#83 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#84 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#85 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#86 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#87 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#88 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#89 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#90 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#91 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#92 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#93 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#94 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#95 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#96 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#97 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#98 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#99 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#100 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#101 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#102 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#103 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#104 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#105 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#106 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#107 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#108 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#109 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#110 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#111 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#112 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#113 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#114 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#115 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#116 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#117 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#118 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#119 /home/xxxxxx/public_html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#120 /home/xxxxxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#121 /home/xxxxxx/public_html/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#122 /home/xxxxxx/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#123 /home/xxxxxx/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Layout->renderResult()
#124 /home/xxxxxx/public_html/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#125 /home/xxxxxx/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#126 /home/xxxxxx/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#127 /home/xxxxxx/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#128 {main} [] []

**Comment by engcom-November** [comment]
Hi @jorgb90 ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4.4 and 2.4-develop versions but cannot able to reproduce the issue. Can you please provide more details and exact Preconditions and steps? From which version it is upgraded from? [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
Thank you.

**Comment by jorgb90** [comment]
Hi @engcom-November We have updated the platform from 2.4.3-p1 to 2.4.4, but the platform itself is already older then that. We are running into this issue when opening a customer account in the admin and create an order from there. The customer needs to have a default address saved.

**Comment by hostep** [comment]
Is probably caused by this change: [MC-42623:Countries list is incorrect when using different countries per website and Global Customer Account settings](https://github.com/magento/magento2/commit/3420116963ff10bd45d2c9b7e75fb2e5c1e31996).
However, it's probably not a core bug in Magento, but some bug caused by a modification.

Somehow that `$block->getData('customerAddressCollectionAttributeFilter');` is returning `null` in your case, while it should be set via an xml file:
```xml
<argument name="customerAddressCollectionAttributeFilter" xsi:type="object">Magento\Sales\ViewModel\Customer\Address\AddressAttributeFilter</argument>
```

So maybe you have some kind of customisation done to the backoffice order create form, that's somehow missing this `customerAddressCollectionAttributeFilter` argument in the block?

**Comment by jorgb90** [comment]
@hostep Thanks! Will look into this. Only thing is that creating a new order from the order overview and selecting a customer there doesn't trigger this problem. It only occurs when trying to create an order from the customer profile.

**Comment by jorgb90** [comment]
Found the issue to be indeed a module, so this can be closed.
