### ISSUE TITLE
What's the right step to update magento2 source code

### ISSUE THREAD

**Issue by woei66** [magento/magento2#3540]
My magento2 source code is coming from git clone
and below are my steps to update Magento2 source code on production.
Can anyone help to check these steps are correct?
Thank you.

1) git pull
2) composer update
3) php bin/magento setup:upgrade
4) php bin/magento setup:static-content:deploy
5) chown -R nginx:nginx *

**Comment by mazhalai** [comment]
Git clone is not recommended for production, it is only for contributing developers. See [this](http://devdocs.magento.com/guides/v2.0/install-gde/continue.html)

**Comment by maksek** [comment]
Hi @woei66, GitHub issues only for bugs or issues with system. All questions or "how to" you may ask in Magento forum. https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2

**Comment by woei66** [comment]
ok, thanks
