### ISSUE TITLE
Imposible to reorder configurable products with optional custom options

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#35409]
### Preconditions
1. Magento >= 2.4.2 (not tested on older versions)

### Steps to reproduce
1. Create a configurable product
2. Add a custom option of type select (drop down) and set it as optional (Uncheck Required field)
3. Order this product without choosing any custom option (as it is optional) from front end
4. Try to reorder from the admin view - Sales - Orders - View Order - Click on Reorder
5.  Error message displayed and clicking on Submit Order - Does not work - **Issue**
**Temporary workaround:** Click on Configure button - do not select anything - click OK and submit order - Order is created - **No issue**

### Expected result
1. The reorder page is shown without any error and it is possible to reorder

### Actual result
1. An error message is shown at the configurable product: `Some of the selected options are not currently available.`

![image](https://user-images.githubusercontent.com/3015249/166268214-55422d37-9491-4945-9bd4-19c082c77b0a.png)

### Additional information

From what I've debugged, it seems like the issue is caused by the method `\Magento\Catalog\Model\Product\Option\Type\Select::getEditableOptionValue`.  

This one doesn't check if the custom option is required or optional.  

Thus, when fetching the value with `$_result = $option->getValueById($_value);`, which is `null`, the `else` statement is reached and then a `$this->getListener()->setHasError(true)->setMessage($this->_getWrongConfigurationMessage());` is set.  

Finally, this triggers the error in `\Magento\Quote\Model\Quote\Item\AbstractItem::checkData` because of the `if ($this->getProduct()->getHasError()) { ... }` condition.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Updating the description with additional information and temporary workaround.
![image](https://user-images.githubusercontent.com/60198231/166644824-5ffa7dd5-ac04-4f2b-ba92-f0db34b13d8d.png)

**Comment by Zaahed** [comment]
@magento I am working on this

**Comment by Zaahed** [comment]
@magento add to contributors team

**Comment by Zaahed** [comment]
@magento I am working on this

**Comment by fallbeata** [comment]
Hello everybody! Can anyone help me with this problem? If no option was selected with the order I can't do a reorder. I get the same error message as "Some of the selected options are not currently available".
