### ISSUE TITLE
Changing admin url from admin not working

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35416]
### Preconditions (*)
 Magento 2.4.4
### Steps to reproduce (*)

1. Stores > Settings > Configuration - Advanced - Admin - Custom admin Url set to "yourmagentostore.com/backend/"
2. Custom Admin path set to "backend"
3. Save config
Issue: UI is broken Unable to login even after clearing cache.
Note: There is no issue on setting from CLI as per [docs](https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html)

### Expected result (*)

1. [Screenshots, logs or description]
4. it should be changed to new one and throw success message.

### Actual result (*)

Exception #0 (Exception): Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/magento2/vendor/magento/module-backend/App/Area/FrontNameResolver.php on line 135

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by hemendraajmera** [comment]
issue reproduced on requested instance , after saving it redirected to 404 page 
![image](https://user-images.githubusercontent.com/2478037/166675769-52782bbe-f5e8-4fb3-9552-d764eb28f5a1.png)

**Comment by engcom-November** [comment]
Hi @hemendraajmera ,
Thank you for reporting and collaboration. Unable to reproduce the issue on Magento 2.4-develop version. It seems like your URL is not changed with new value set in admin. (Browsing with same old admin URL as per your Screenshot ). Can you please refer the [docs](https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html) and recheck the issue again on Magento 2.4-develop branch.
Thank you.

**Comment by hemendraajmera** [comment]
It still open because i tried to updated admin base url from admin panel which not working,after that the admin panel URL not working,
you can try using fresh magento 2.4.4 instance

**Comment by hemendraajmera** [comment]
@magento give me 2.4.4-develop instance

**Comment by hemendraajmera** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @hemendraajmera ,
You can use this instance for testing:
https://776f90ef02ea42110562a8984a262d53.instances.magento-community.engineering/
Admin access: https://776f90ef02ea42110562a8984a262d53.instances.magento-community.engineering/admin_0536
Login: 51b18ebb
Password: ba2fe815432b

**Comment by engcom-November** [comment]
Verified the issue again on Magento 2.4.4 and 2.4-develop branch and observed below issue on changing admin base url and custom admin path:
**Steps performed:**
1. Stores > Settings > Configuration - Advanced - Admin - Custom admin Url set to "yourmagentostore.com/backend/"
2. Custom Admin path set to "backend"
3. Save config
Issue: UI is displayed as below. Unable to login even after clearing cache.
![image](https://user-images.githubusercontent.com/60198231/167558026-2e39beac-0c48-484e-bfb5-bf72ae2277ec.png)

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by robolmos** [comment]
Is there a related commit with the fix or quality patch?

**Comment by hostep** [comment]
@robolmos: it's probably [this commit](https://github.com/magento/magento2/commit/688168d4df5b57278a797c8236fbf3d8aa0e0aa2) which fixed it, since it's the only commit that mentions `AC-3036` (source: https://github.com/magento/magento2/issues/35416#issuecomment-1121963281):
