### ISSUE TITLE
GraphQL not working on fresh 2.4.4 installation

### ISSUE THREAD

**Issue by bskimball** [magento/magento2#35412]
Fresh install of Magento 2.4.4. I'm trying to set it up to work with PWA Studio. I installed the opensource metapackage.

### Preconditions (*)
1. Magento/product-community-edition:2.4.4
2. magento/pwa: 0.2.1

### Steps to reproduce (*)
1. composer install
2. open browser to magento-url.com/graphql

### Expected result (*)
I expect to see a GraphIQL page for testing graphql queries

### Actual result (*)
1 exception(s):
Exception #0 (Exception): Warning: Undefined array key "query" in /var/www/two/vendor/magento/module-graph-ql/Controller/GraphQl.php on line 208

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### Extra Info
I commented out the lines with the error since it was just logging. Now when I go to the page I get this:
```
{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}
```

**Comment by engcom-Hotel** [comment]
Hello @bskimball,

We have tried to reproduce the issue in Magento 2.4-develop and 2.4.4 with PWA module installed. But for us, the issue is not reproducible. I suggest you go through with the [devdoc](https://devdocs.magento.com/guides/v2.4/graphql/index.html#how-to-access-graphql) link in order to run the GraphQl for your Magento instance.

According to the devdocs, either you need to use the [GraphiQl](https://github.com/graphql/graphiql) or a browser extension like `Altair GraphQL Client`.

Let us know in case of any other queries.

Thanks

**Comment by bskimball** [comment]
I rolled back to 2.4.3 and I no longer receive the error about the 'query' key missing in the $data array. I can create a PR to check if the query key exists in the array on line 208 in the Graphql.php file. 

I did revisit the docs this morning to find that I need to use graphiql when testing the endpoint.

**Comment by rtsehynka** [comment]
HI.
I have the same problems after update to 2.4.4 and php 8.1. Also, it  
very easy to fix if you add additional check  isset($data['query']) && on string of  if ( strpos($data['query'], 'IntrospectionQuery') === false) { in file /vendor/magento/module-graph-ql/Controller/GraphQl.php. 
`    // log information about the query, unless it is an introspection query
    if (isset($data['query']) &&  strpos($data['query'], 'IntrospectionQuery') === false) {
        $queryInformation = $this->logDataHelper->getLogData($request, $data, $schema, $this->httpResponse);
        $this->loggerPool->execute($queryInformation);
    }
`

**Comment by cmuench** [comment]
I can confirm that. A fresh Magento 2.4.4 produces this PHP warning. We should fix that.
IMHO it's a minor issue. GraphQL POST requests are not affected.
I was also able to query via GET (then we have the query parameter "query" available).
So the title is misleading.

**Comment by cpartica** [comment]
> 
@bskimball can you link that PR to this issue?
