### ISSUE TITLE
Magento 2.4.4 Session issue

### ISSUE THREAD

**Issue by advocat** [magento/magento2#35414]
**Precondition:**
- Install Magento 2.4.4
- `bin/magento config:set system/security/max_session_size_admin 0`
- Flush cache

**Steps to reproduce**
- Go to login page
- Try to login

**Actual Result**
- Reload the same login page without any messages

**Expected Result**
- Successful login into admin 

**Root Cause**
https://github.com/magento/magento2/blob/7d80b877d7057e62555d3376f2be7e7be68838f0/lib/internal/Magento/Framework/Session/SaveHandler.php#L129
Should be:
`if ($sessionMaxSize !== null && $sessionMaxSize < $sessionSize) {`

**Comment by hostep** [comment]
Sounds like a duplicate of https://github.com/magento/magento2/issues/35312
If you agree, maybe post your root cause findings on that ticket and close this one so that we only have one to track this issue. Thanks! 🙂

**Comment by advocat** [comment]
Yep. Didn't found first one. I can confirm that it's the same issue.
You can add root of cause and possible fix to internal ticket or https://github.com/magento/magento2/issues/35312.
Feel free to decide what to do with the ticket
Thank you

**Comment by engcom-Hotel** [comment]
Hello @advocat,

Closing this issue as duplicate of https://github.com/magento/magento2/issues/35312
