### ISSUE TITLE
Recoverable Error: Argument 1 passed to iterator_to_array() on AbstractBlock.php

### ISSUE THREAD

**Issue by woei66** [magento/magento2#3541]
The admin back-end can't be accessed with below error message
I have no idea about this problem.
Does anyone can share your suggestion about this problem?
Thank you.

`Recoverable Error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given, called in /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php on line 657 and defined in /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Element/Html/Calendar.php on line 72
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/usr/share/ngin...', 72, Array)
#1 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Element/Html/Calendar.php(72): iterator_to_array(NULL)
#2 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Html\Calendar->_toHtml()
#3 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#4 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('head.calendar')
#5 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar')
#6 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('head.calendar')
#7 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('head.calendar', true)
#8 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('head.calendar')
#9 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#10 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#11 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.star...')
#12 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#13 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#14 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#15 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#16 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#17 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#18 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#19 /usr/share/nginx/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#20 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#21 /usr/share/nginx/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#22 /usr/share/nginx/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#23 /usr/share/nginx/magento2/lib/internal/Magento/Framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#24 /usr/share/nginx/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#25 /usr/share/nginx/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#26 {main}

`

**Comment by woei66** [comment]
The problem is interesting.
I used below to change the language from zh_Hant_TW to en_US
php bin/magento setup:store-config:set --language=en_US 
and the problem is solved.

I traced the code lib/internal/Magento/Framework/View/Element/Html/Calendar.php
$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());
If the language is zh_Hant_TW , I got a empty DataBundle object
If I change the language to en_US, it works.

**Comment by ddlawrence303** [comment]
I did the same way for myself 
but it still stay and I just can't access to admin  {root_url}/admin_interface_url .......

**Comment by tanloi3004** [comment]
It got same issue when open Product Detail page. I use locale ja_JP for a Japanese store view, PHP 7.0.9.
However, when I switched to PHP 7.0.6-dev then it works fine.

**Comment by tanloi3004** [comment]
Seem that problem occur when run magento 2 on Centos with Iibicu version 50.1.2. My ubuntu server installed libicu 52.1 working fine.

**Comment by mrkhoa99** [comment]
A temporary solution:

Go to this file: `vendor/magento/framework/View/Element/Html/Calendar.php` line ~65

Replace:

`$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());`
With:

`$localeData = (new DataBundle())->get('en_US');`

**Comment by woshka** [comment]
I have reported this issue here
https://github.com/magento/magento2/issues/14068

**Comment by woshka** [comment]
This problem seems to be combined with the operating system issue related
today a working system of Centos 7 with CPanel resulted this issue while there was no issue till today
I haven't seen any such issues on ubuntu OS builds

**Comment by mChaudharizarafaksa** [comment]
Any solution?

**Comment by mnjsngh** [comment]
Any solution?

**Comment by woshka** [comment]
Please specify your OS you have installed your Magento on it
for a quick fix change your Locale for admin to US temporarly to access the admin panel
