### ISSUE TITLE
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by rohit-12284** [magento/magento2#35426]
### Preconditions (*)

1.i updated my magento version 2.3.1 to 2.4.3
2.

### Steps to reproduce (*)

1.while I login into my admin pannel i show this error  
2
![Uploading Screenshot_3.png…]()

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @7018424048 ,

Thank you for logging an issue, We could not find clear screenshots, issue description . Hence request to help us with clear issue description ,  screenshots , Actual test results and expected test results to replicate the issue.

Regards,
