### ISSUE TITLE
Icons in Magento UI Library

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#3542]
I'd like to play around a bit with the Magento UI Library. It's really nice! 

Not sure if this is a bug report, or if I'm missing something, but I can't really get the icons working. I've checked if it works for other webshops, but I didn't find any other webshop which had the icons working. 

Here's an example of a dropdown:

![image](https://cloud.githubusercontent.com/assets/1165302/13314838/853d1b26-dba7-11e5-88af-bfb1a5561092.png)

Is this a bug or am I(and everyone else) missing something?

**Comment by zanilee** [comment]
Hi, @Desmaster!

This is known issue and it is present in library documentation only.
Icons are ok in both storefront and admin.
The documentation issue will be fixed in MAGETWO-34178

**Comment by tdgroot** [comment]
@zanilee Good to know the issue is already known! Even though `MAGETWO-34178` sounds really promising, what does it mean for me? Will it be fixed soon or late?

**Comment by MomotenkoNatalia** [comment]
@Desmaster this issue will be fixed in future ;) We know that the styledocco work is not very good, and we are thinking about changing it. 
And what do you think about Magento UI Library? Is it useful for you?

**Comment by tdgroot** [comment]
@MomotenkoNatalia we see it as a way to see the styling of all elements in one place. This provides styling consistency through the whole theme. 

What's the status of the issue right now? It's been a while since I filed this issue.

**Comment by magento-engcom-team** [comment]
@tdgroot, thank you for your report.
We've created internal ticket(s) MAGETWO-82332 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tdgroot, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
