### ISSUE TITLE
Configurable Stock not updated after a child is back in stock

### ISSUE THREAD

**Issue by yuriichayka** [magento/magento2#35428]
Configurable product remains Out of Stock after children's stock is updated. 
May be related to the https://github.com/magento/magento2/commit/1707f2a8169558a199ef07a4e045be58b18ceeeb

### Preconditions (*)

1. Magento 2.4.4 EE
2. PHP8.1
3. Elasticsearch 7
4. MSI functionality is enabled.

### Steps to reproduce (*)

1. Create configurable product in Magento Admin with children without specifying any stocks;
2. Make sure that products appear as Out Of Stock  in `cataloginventory_stock_status`  table after Cron processes changes;
3. Check Configurable page on FE, it should be shown as Out of Stock;
4. Update some child product to be in stock in Magento Admin;
5. Make sure that the child's stock is updated in the `cataloginventory_stock_status`;
6. Wait for Cron to process changes(update all views)

### Expected result (*)

1. Configurable product becomes In Stock;

### Actual result (*)

1. Configurable products remains Out of Stock, event though status is chagned to 'In Stock'.
2. For checking: SELECT product_id, stock_status FROM cataloginventory_stock_status t ORDER BY 1 DESC LIMIT 10;
3. In Magento 2.4.3, `stock_status`is updated after CRON or `cataloginventory_stock` indexer is run

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by yuriichayka** [comment]
reverting changes in Model/ResourceModel/Indexer/Stock/DefaultStock.php prior to the mentioned commit helps

**Comment by yuriichayka** [comment]
Hello @engcom-Delta 
Thanks for working on it.

The issue is caused by the latest release of MSI, particularly by this newly introduced file - https://github.com/magento/inventory/blame/develop/InventoryCatalog/Model/ResourceModel/StockStatusExpressionForDefaultStock.php

Following line breaks the logic:
```
        $isInStockExpression = $connection->getCheckSql(
            'cisi.is_in_stock = 0',
            0,
            $connection->getCheckSql('css.stock_status IS NOT NULL', 'css.stock_status', $stockItemInStockField)
        );
```
For us, the fix was to revert related changes:
```
diff --git vendor/magento/module-inventory-catalog/etc/di.xml vendor/magento/module-inventory-catalog/etc/di.xml
--- vendor/magento/module-inventory-catalog/etc/di.xml
+++ vendor/magento/module-inventory-catalog/etc/di.xml	(date 1651749987637)
@@ -181,9 +181,7 @@
     <type name="Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\GetStatusExpression">
         <arguments>
             <argument name="statusExpressions" xsi:type="array">
-                <item name="default" xsi:type="object">Magento\InventoryCatalog\Model\ResourceModel\StockStatusExpressionForDefaultStock</item>
-                <item name="bundle" xsi:type="object">Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression</item>
-                <item name="grouped" xsi:type="object">Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression</item>
+                <item name="default" xsi:type="object">Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression</item>
             </argument>
         </arguments>
     </type>

```

**Comment by hostep** [comment]
@yuriichayka: why did you close this issue? Is it not reproducible on a clean Magento 2.4.4 installation with MSI installed?

**Comment by yuriichayka** [comment]
@hostep because the issue is MSI-related, and there is a separate MSI repository. 
the issue is reproducible on clean Magento 2.4.4 installation with MSI

**Comment by hostep** [comment]
Ah okay! Can you link to the issue on the MSI repository from within this one? That will help people find more info quicker in case they run into the same issue, thanks 🙂

**Comment by engcom-Delta** [comment]
Hi @yuriichayka ,

We have tested the with latest MSI Module , unfortunately still not reproducible.

<img width="1440" alt="Screenshot 2022-05-12 at 8 39 58 PM" src="https://user-images.githubusercontent.com/51681379/168108261-2a2056eb-1bb4-4d1d-b51d-db91d7c859d4.png">

Kindly provide the clear steps to reproduce the issue.

Thanks
