### ISSUE TITLE
Config element "FrameworkDataImageContentInterface" is not declared in GraphQL schema

### ISSUE THREAD

**Issue by bskimball** [magento/magento2#35433]
### Preconditions (*)

1. Magento 2.4.4

### Steps to reproduce (*)
1. Query the Schema via Graphql
```
__schema {
    types {
        kind
    }
}
```

### Expected result (*)
See the Magento schema

### Actual result (*)
Logs show:
[2022-05-05T15:18:52.315065+00:00] main.ERROR: Config element "FrameworkDataImageContentInterface" is not declared in GraphQL schema

GraphQL (3:9)
2:     __schema {
3:         types {
           ^
4:             kind
 [] []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by bskimball** [comment]
@magento give me 2.4-develop instance

**Comment by bskimball** [comment]
works on fresh instance. Must have something to do with the data migration.
