### ISSUE TITLE
Issue with extending \ArrayObject

### ISSUE THREAD

**Issue by anowave** [magento/magento2#35448]
### Preconditions (*)

1. Magento 2.4.4
2. PHP 8.1

### Steps to reproduce (*)

1. Create a simple class e.g. 

`class Param extends \ArrayObject {}`

2. Create a child class e.g. 

`class Bug extends Param` {}

### Expected result (*)

1. Running bin/magento setup:di:compile should complete without errors

### Actual result (*)

1. Compilation results in error: Call to undefined method ReflectionUnionType::isBuiltin()#0

### Probable cause (*)

We believe the issue is located in Laminas\Code\Reflection\ParameterReflection->detectType(), in PHP 8.1 the __construct() arguments of \ArrayObject have a union type hint e.g.

__construct(array|object $array = [], int $flags = 0, string $iteratorClass = ArrayIterator::class)

However, in PHP 8.1 ReflectionUnionType does not have the isBuiltin() method and this is causing issues.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shkoliar** [comment]
While there are no updates yet for the *laminas/laminas-code* package, I've added a patch to fix it:
```
--- a/vendor/laminas/laminas-code/src/Reflection/ParameterReflection.php
+++ b/vendor/laminas/laminas-code/src/Reflection/ParameterReflection.php
@@ -7,6 +7,7 @@
 use ReflectionMethod;
 use ReflectionParameter;
 use ReflectionProperty;
+use ReflectionUnionType;
 use ReturnTypeWillChange;

 use function method_exists;
@@ -76,11 +77,13 @@
      */
     public function detectType()
     {
-        if (
-            method_exists($this, 'getType')
-            && null !== ($type = $this->getType())
-            && $type->isBuiltin()
-        ) {
+        $type = method_exists($this, 'getType') ? $this->getType() : null;
+
+        if ($type instanceof ReflectionUnionType) {
+            $type = $type->getTypes()[0] ?? null;
+        }
+
+        if (null !== $type && $type->isBuiltin()) {
             return $type->getName();
         }

```

_ReflectionIntersectionType_ also could cause some troubles.

**Comment by hostep** [comment]
If you guys consider this a bug in the [`laminas/laminas-code` package](https://github.com/laminas/laminas-code), why not open an issue over there or suggest this fix with pull request to them?

**Comment by engcom-Charlie** [comment]
Hi @anowave,

Currently I have below installed versions on my local machine and the issue is not reproducible.
- Magento 2.4-develop
- PHP 8.1.7
- Composer 2.3.10

In order to reproduce the issue followed below steps.

1. Created a simple class e.g.
class First extends \ArrayObject {}

2. Created a child class e.g.
class Second extends First {}

bin/magento setup:di:compile is running successfully without any error.

Can you please check once again or let me know if I am missing anything in reproduction steps.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @anowave,

As we have not received any reply on [comment](https://github.com/magento/magento2/issues/35448#issuecomment-1191303794) for a period more than 14 days so we are closing this issue because of the inactivity .

Please raise a fresh issue or reopen this issue if you need more assistance on this.

Thank you!

**Comment by padmapriya-varadhan** [comment]
This issue is happening to me as well. 
Magento version: 2.4.6
PHP: 8.1.17

Why was this closed without a fix?

**Comment by kallard1** [comment]
I've same issue with Magento 2.4.5-p2 / PHP 8.1.14

**Comment by hostep** [comment]
@padmapriya-varadhan, @kallard1: if I read the comments above, it might be considered a bug in https://github.com/laminas/laminas-code/ and not in the Magento codebase. If you guys agree, maybe one of you could open an issue over there so it can get fixed there?

**Comment by edwinljacobs** [comment]
It would not make sense to create an issue with laminas as the method is marked as deprecated

```/**
     * Get parameter type
     *
     * @deprecated this method is unreliable, and should not be used: it will be removed in the next major release.
     *             It may crash on parameters with union types, and will return relative types, instead of
     *             FQN references
     *
     * @return string|null
     */
    public function detectType()
    {
```

This is the commit where that method has been deprecated (at the time of writing 6 months ago)
https://github.com/laminas/laminas-code/commit/b310381955a67ec09c2a11ef9691216ed346f6e9

Im running into a similar issue where one of my interfaces defines a method which takes a string|int argument, this apparently cannot be processed by the swagger processor.
