### ISSUE TITLE
i18n:collect-phrases does not include mail template translations in depend constructs

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#35449]
### Preconditions (*)

1. Magento 2.4.3-p2

### Steps to reproduce (*)

1. Run `bin/magento i18n:collect-phrases --output=test.csv vendor/magento/module-sales/view/frontend/email/`
2. Take a look at `vendor/magento/module-sales/view/frontend/email/order_new.html` and see for example the following code snippet: ```                 {{depend store_hours}}
                    {{trans 'Our hours are <span class="no-link">%store_hours</span>.' store_hours=$store_hours |raw}}
                {{/depend}} ```

### Expected result (*)

1. I would expect, that all string, which shall be translated, are included in my test file.

### Actual result (*)

1. Strings, which are surrounded by a `depend` construct, are not included in the exported file. So for example `Our hours are <span class="no-link">%store_hours</span>.` is not included in the file.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @norgeindian ,
We tried to reproduce the issue on Magento 2.4 develop instance , issue is reproducible. Hence issue has been confirmed.

**Steps followed:** 


1. Run bin/magento i18n:collect-phrases --output=test.csv app/code/magento/sales/view/frontend/email/

<img width="1440" alt="Screenshot 2022-06-09 at 8 29 50 PM" src="https://user-images.githubusercontent.com/51681379/172879383-d696b733-7be8-48c3-a136-8fdece861ac9.png">

2. Take a look at app/code/magento/sales/view/frontend/email/order_new.html and see for example the following code snippet: {{depend store_hours}} {{trans 'Our hours are <span class="no-link">%store_hours</span>.' store_hours=$store_hours |raw}} {{/depend}}

<img width="608" alt="Screenshot 2022-06-09 at 8 35 28 PM" src="https://user-images.githubusercontent.com/51681379/172880513-8d265ff2-dd8e-4c9a-886a-2fb27d13d3b3.png">

<img width="1440" alt="Screenshot 2022-06-09 at 8 36 48 PM" src="https://user-images.githubusercontent.com/51681379/172880581-cc7a3326-d809-448c-8263-a3b609433df5.png">

Actual results:

Strings, which are surrounded by a depend construct, are not included in the exported file. So for example Our hours are <span class="no-link">%store_hours</span>. is not included in the file.

<img width="1440" alt="Screenshot 2022-06-09 at 8 27 44 PM" src="https://user-images.githubusercontent.com/51681379/172879699-a87989ec-0426-4d54-93a9-62d536c577bf.png">

**Comment by sprankhub** [comment]
@magento I am working on this

**Comment by glo71317** [comment]
@sprankhub thanks for contributing, Internal team is processing your PR along with your commits and will fix failed automation tests.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3499 by the internal team
Related commits: https://github.com/search?q=AC-3499&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
