### ISSUE TITLE
Magento Commerce ver. 2.4.3-p1 missing category thumbnail attribute

### ISSUE THREAD

**Issue by raulsinapsis** [magento/magento2#35455]
### Preconditions (*)
Magento Commerce ver. 2.4.3-p1
Hosted in Adobe Cloud servers / it can be reproduced in local environment

### Steps to reproduce (*)
Install default project in a clean database with composer packages:
"magento/composer-root-update-plugin": "~1.1",
"magento/magento-cloud-metapackage": ">=2.4.3 <2.4.4"

### Expected result (*)
Category thumbnail attribute is installed 

### Actual result (*)
Category thumbnail attribute is not installed 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by raulsinapsis** [comment]
Maybe it's something related to magento/magento-cloud-metapackage composer package?

**Comment by engcom-Delta** [comment]
@magento give me 2.4.3-p1 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Hotel** [comment]
Dear @raulsinapsis,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
