### ISSUE TITLE
Magento CE 2.4.4 - 404 on static content - developer/default mode

### ISSUE THREAD

**Issue by aetonsi** [magento/magento2#35454]
### Preconditions (*)

1. Magento community edition 2.4.4
2. linux mint 20.3 una (ubuntu) (but SAME result on Windows11 cmd and Windows11 WSL2)
3. php 8.1.5
4. composer 2.3.5
5. mysql ver 8.0.29-ubuntu0.20.04.3 x86_64
6. elasticsearch 7.17.3
7. apache/2.4.41 (ubuntu)

### Steps to reproduce (*)

0. install various packages `sudo apt install gzip lsof sed tar p7zip-full unzip zip`
1. install and start elastic search with `./bin/elasticsearch -d -p pid`
2. install php 8.1 and its extensions by adding the repository, then `sudo apt install php8.1 php8.1-bcmath php8.1-mysql php8.1-ctype php8.1-curl php8.1-dom php8.1-fileinfo php8.1-gd php8.1-iconv php8.1-intl php8.1-mbstring php8.1-simplexml php8.1-soap php8.1-sockets php8.1-tokenizer php8.1-xmlwriter php8.1-xsl php8.1-zip`
3. edit `php.ini` with these settings, then restart apache2 service:
```
        date.timezone = Europe/Rome
	memory_limit = -1
	realpath_cache_size = 10M
	realpath_cache_ttl = 7200
	opcache.enable = 1
	opcache.save_comments = 1
```
4. install composer via install script
5. install mysql-server
6. in DB: create magento user and database in mysql; grant ALL PRIVILEGES to magento user; create database magento
7. create magento project: 
```
        cd /var/www/html
        composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2
```
8. set permissions
```
        cd /var/www/html/magento2
        find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +
        find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +
        chown -R :www-data . # Ubuntu
        chmod u+x bin/magento
```
9. install magento via
```
        bin/magento setup:install \
--base-url=http://localhost/magento2 \
--db-host=localhost \
--db-name=magento \
--db-user=magento \
--db-password=magento \
--admin-firstname=ivan \
--admin-lastname=drago \
--admin-email=ivandrago@example.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=EUR \
--timezone=Europe/Rome \
--use-rewrites=1 \
--search-engine=elasticsearch7 \
--elasticsearch-host=localhost \
--elasticsearch-port=9200 \
--elasticsearch-index-prefix=magento2 \
--elasticsearch-timeout=15
 ```
10. open `http://localhost/magento2/pub`

### Expected result (*)

i'd expect to see a fully loaded page

### Actual result (*)
![image](https://user-images.githubusercontent.com/18366087/167803503-4130fdca-a322-4394-b367-5ef5ba50eded.png)

### What i tried
```bash
sudo a2enmod rewrite
sudo service apache2 restart
cd /var/www/html/magento2
bin/magento deploy:mode:set developer
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aetonsi** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @aetonsi,

Thanks for the report and collaboration!

I would like to suggest you create a virtual host and then try to access the instance using the domain name given in the virtual host.

Thanks

**Comment by aetonsi** [comment]
> Hello @aetonsi,
> 
> Thanks for the report and collaboration!
> 
> I would like to suggest you create a virtual host and then try to access the instance using the domain name given in the virtual host.
> 
> Thanks

Hello, here it is with virtual host in linux mint, i tried with `DocumentRoot /var/www/magento2-domain` and `DocumentRoot /var/www/magento2-domain/pub`, the 404 errors persist...

![image](https://user-images.githubusercontent.com/18366087/168620396-78c80ca7-c537-40a6-93f2-821119d6cafc.png)

**Comment by engcom-Hotel** [comment]
Hello @aetonsi,

Thanks for your reply!

I can see the vhost entry but I suggest one change to make as below:

DocumentRoot should change from:
`/var/www/magento2-domain`
To
`/var/www/magento2-domain/pub/`

Please make the changes restart the apache and let us know if the issue is fixed or not.

Thanks

**Comment by aetonsi** [comment]
No, same result after i restarted apache:


![image](https://user-images.githubusercontent.com/18366087/168822949-8a260fb1-1fc8-438f-8b8d-31fca22dd8b1.png)

**Comment by Digiraf** [comment]
> * sudo php bin/magento setup:static-content:deploy -f;

it is working because of this command: sudo php bin/magento setup:static-content:deploy -f; but this does not fix the issue.
