### ISSUE TITLE
There has been an error processing your request

### ISSUE THREAD

**Issue by ahmed22s885111qq** [magento/magento2#35463]
Exception printing is disabled by default for security reasons.

Error log record number: d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f

i run the record log number in putty this what i see :

`var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: tax_class_id: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: final_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: minimal_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: min_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: max_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: tier_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: cat_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: position: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: cat_index_position: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: name: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: image: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: small_image: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: thumbnail: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: name: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: short_description: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: special_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: special_from_date: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: special_to_date: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: image: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: small_image: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: thumbnail: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: news_from_date: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: news_to_date: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: required_options: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: image_label: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: small_image_label: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: thumbnail_label: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: msrp: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: msrp_display_actual_price_type: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: url_key: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: links_purchased_separately: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: links_exist: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_type: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: weight_type: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_view: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: swatch_image: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: tax_class_id: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: sw_featured: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: ordered_qty: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: order: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: state: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: stock_status_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: stock_status: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: is_salable: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: catalog_product_entity: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: e: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: catalog_product_index_price: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: price_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: catalog_category_product_index_store1: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: cat_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: sales_order_item: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: soi: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: sales_order: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: order: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: cataloginventory_stock_status: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: stock_status_index: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: soi: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: product_id: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: ordered_qty: command not found var/report/d11d948cb3596b359566fa162df65dbf6baef2446fe384f4476057675f3dd95f: lin e 1: 0:SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.name' in 'field list', query was: SELECT .*, ., ., ., IF(price_index.tier_price IS NOT NULL, LE AST(price_index.min_price, price_index.tier_price), price_index.min_price) AS , ., ., ., . AS , ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., . , ., ., ., ., ., ., ., ., SUM(soi.qty_ordered) AS , ., . AS FROM AS \n INNER J OIN AS ON price_index.entity_id = e.entity_id AND price_index.customer_group_i d = 0 AND price_index.website_id = '1'\n INNER JOIN AS ON cat_index.product_id =e.entity_id AND cat_index.store_id=1 AND cat_index.category_id=2 AND cat_index. is_parent=1\n LEFT JOIN AS ON soi.product_id = e.entity_id\n INNER JOIN AS O N order.entity_id = soi.order_id\n INNER JOIN AS ON e.entity_id = stock_status _index.product_id WHERE (order.state <> 'canceled' and soi.parent_item_id IS NUL L AND soi.product_id IS NOT NULL) AND (stock_status_index.stock_status = 1) GROU P BY . ORDER BY DESC\n LIMIT 3: command not found`

**Comment by FadedOut** [comment]
@ahmed22s885111qq seeing how this is your first report I'll give you a few tips. 

1. You should follow the guidelines it gives you when you start the report. Like the prerequisites, the steps to reproduce, etc. as this helps other members on here know more information to why you may be getting the problem you're having. Without this info, no one knows any info to report back on to help you with. Just posting lines with errors in it will get you no help usually.
2. There are log files in var/log/. You'll want to take a look at "exception.log" and "system.log" for better results. What you posted above looks like it contains maybe only some of what system.log might have.

Following these tips might help you get your issues resolved quicker. Just posting some error lines will deter anyone to post helping you. Like for me, I have no idea what version Magento you're on, if you did any updates, what you were doing when it happened, etc. etc. etc....follow the original bug report guidelines, it explicitly tells you to do so for us members to accurately help you.

Also asking magento to give you a magento 2.4 instance helps to see if it is related to your install or if it is something stock magento.

**Comment by engcom-Delta** [comment]
Hi @ahmed22s885111qq ,
Thank you for raising an issue and We are happy to assist you . Kindly provide clear issue description, pre-condition, steps to reproduce, actual results and expected results .

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
