### ISSUE TITLE
when I do a transaction through a payment gateway in an iframe, then after returning to the merchant site, sessions are destroyed and users log out in magento2.4.3 in the firefox browser

### ISSUE THREAD

**Issue by babarzafar** [magento/magento2#35460]
### Preconditions (*)

when I do a transaction through a payment gateway in an **iframe**, then after returning to the merchant site, sessions are destroyed and users log out in magento2.4.3 in the **firefox browser** but it works properly in **all browsers** except firefox.

### Expected result (*)
I want to get the proper transactions through the payment gateway and sessions should not destroy.

### Actual result (*)
when I do a transaction through a payment gateway in an iframe, then after returning to the merchant site, sessions are destroyed and users log out in magento2.4.3 in the firefox browser.

**Comment by engcom-Delta** [comment]
Hi @babarzafar ,
Thank you for raising an issue , Steps are missing to reproduce the issue . Kindly provide clear issue description, pre-condition, steps to reproduce and screenshots if required.
Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
