### ISSUE TITLE
REST API POST:/V1/customers fails if firstName contains ’ (ascii code 2019 (hex))

### ISSUE THREAD

**Issue by joepperkins** [magento/magento2#35469]
### Preconditions (*)

1. 2.4.0 or greater

### Steps to reproduce (*)

POST:/V1/customers 
{
	"customer": {
		"email": "OToole@joeperkins.com",
		"firstname": "O’Toole",
		"lastname": "perkins",
		"website_id": 1
	}
   }

### Expected result (*)

200, Success

### Actual result (*)

Status: 400, Response:  {"message":"First Name is not valid!"}'

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Issue: Confirmed

**Comment by joepperkins** [comment]
I am not working on this issue, just reporting it

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @joepperkins ,
Thank you for reporting and collaboration. Verified this issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Customer is created successfully using given API request
![image](https://user-images.githubusercontent.com/60198231/168737722-7a7c8d4f-26eb-49fa-80a4-478bf1767603.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by joepperkins** [comment]
Thank you for looking into this

**Comment by joepperkins** [comment]
I found the issue in the source for magento2-2.4.3, thanks for your help on this

The regex is incomplete for valid names.

private const PATTERN_NAME = '/(?:[\p{L}\p{M}\,\-\_\.\'\s\d]){1,255}+/u'


![image](https://user-images.githubusercontent.com/13791515/168878934-b22d4b90-108c-460c-8e37-d1e6c8c9b938.png)


![image](https://user-images.githubusercontent.com/13791515/168878757-4b098910-ac6b-42f1-86fe-33cf9fe1c16b.png)

**Comment by joepperkins** [comment]
Confirmed fixed with commit below

https://github.com/magento/magento2/commit/2a83c2e566a8de512cc398ce1dfb5ab3f4bf26e2

![image](https://user-images.githubusercontent.com/13791515/168882779-06909fe9-b9ce-46ce-88dc-9361f5a59de3.png)
