### ISSUE TITLE
GET    /V1/categories/:categoryId/products  doesn't work

### ISSUE THREAD

**Issue by algostore** [magento/magento2#3547]
Magento 2.0.1 + sample data:
I've tried to get list of products in category 
Gear (ID: 3) 46 records found 

Making a call http://xxxx.hypernode.io/rest/V1/categories/3/products/

Output: []

Does it mean, nothing is connected? what should be correct respond?

Thanks in advance

**Comment by veloraven** [comment]
@algostore is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
