### ISSUE TITLE
Type Error occurred when creating object

### ISSUE THREAD

**Issue by YouCanDoIt12** [magento/magento2#35475]
### Preconditions (*)

1. Install Magento CE 2.4.4 using composer
2. Create Any custom module for sales order interface
3. run command  bin/magento setup:upgrade
5. throwing error 
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName(): Argument #2 ($typeName) must be of type string, null given, called in /Applications/MAMP/htdocs/ent244/vendor/magento/framework/Reflection/TypeProcessor.php on line 550

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. Should install successfully 

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
