### ISSUE TITLE
Which API is used to get credit card information?

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#35472]
### Examples (*)

We are not getting complete information of credit card information applied on order 
a not getting the full credit card type. eg we are getting VI instead of VISA under the node of "cc_type" in order api
b Not getting name on credit card in resposne of order api

So how we can get these information. 

### Proposed solution

We needed complete information of credit card information. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

-[S0 ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @webgility-amazonapi ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch using Debit/Credit card option (Card type used: VISA on front-end) configured using paypal express checkout payment method but couldn't get "cc_type" in the Get Order API response.
Can you please recheck the behavior on 2.4-develop branch and provide payment configuration used for reproducing this issue.
![image](https://user-images.githubusercontent.com/60198231/172386269-af6c33da-48cd-49d2-9bdc-2c10c1cdc0d0.png)
![image](https://user-images.githubusercontent.com/60198231/172386334-fd67156f-5394-460f-a74a-817d551e6bdc.png)
Thank you.

**Comment by engcom-November** [comment]
![image](https://user-images.githubusercontent.com/60198231/172387093-a7014f7c-430b-401c-8a89-f0e21f73fc9d.png)

**Comment by engcom-November** [comment]
Hi @webgility-amazonapi ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
