### ISSUE TITLE
Magento 2.4.4 - Swatches not strike-through inventory reaches "0"

### ISSUE THREAD

**Issue by webpar** [magento/magento2#35486]
### Preconditions (*)
1. Magento 2.4.4

### Steps to reproduce (*)
1. Install sample data
2. Set Admin > Stores > Configuration > Catalog > Inventory > Stock Options > Display Out of Stock Products = Yes
3. Create configurable product with multiple sizes
4. Change only simple/size products to have 0 quantity and out of stock status (leave all other sizes quantities greater than 0)

### Expected result (*)
1. All sizes should be shown and the one without stock should be displayed as crossed out option
![image](https://user-images.githubusercontent.com/105699097/168740020-23638807-c95b-42bb-a043-3aeb79bf6940.png)

### Actual result (*)
1. All sizes are displayed as available
![image](https://user-images.githubusercontent.com/105699097/168740097-effcf1da-1b05-42a8-8877-b0b11f09302a.png)

This has  been reported many times and was fixed in 2.4.3. However the issue is back. I did a bit of research and I found that when a simple product option si out of stock, the following code returns 1 instead of 0 : getQty method from stock stockItemRepository.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment]
Thank you for your report on this. 

But to inform you, this has already been confirmed to be a bug and is currently being worked on.

#35319

**Comment by FadedOut** [comment]
@engcom-Delta 

The OP is talking about the swatch bug that has already been confirmed here: https://github.com/magento/magento2/issues/35319

So it is a duplicate report meaning this could be closed.

**Comment by engcom-Delta** [comment]
Hi @webpar,
We have noticed that this  can be closed as per above @FadedOut comments. Hence closed.
