### ISSUE TITLE
Can't add slider from product slider on magento 2.4.4

### ISSUE THREAD

**Issue by wisesa** [magento/magento2#35484]
when i install product slider both from composer or manually paste then add it to magento 2, i cant add slider on admin page, 
i dont know why, im using magento 2.4.4

**Comment by engcom-November** [comment]
Hi @wisesa ,
Thank you for reporting. However, Product slider is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
