### ISSUE TITLE
UPS Shipping XML rate request sending full weight as one package instead of breaking per weight limit set in admin

### ISSUE THREAD

**Issue by tstamplis** [magento/magento2#35497]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento 2.4.4 open source
PHP 7.4x

### Steps to reproduce

Add products to cart at a quantity that exceeds weight limit set for shipping carrier in admin (210 pounds in my case, shipping carrier cut-off weight set to 150 lbs in admin).  Applies to UPS as well as USPS carriers.

### Expected result

XML requests rate for 2 packages, divided by equal weight (210/2 = 105) and receive rates from carrier.

### Actual result

XML sends request for ONE package weighing 210 pounds.  No rate is returned as it exceed single package weight limit for carrier resulting in no shipping methods displayed resulting in "Sorry, no quotes are available at this time" message.

### Additional information

Problem started after upgrade from 2.4.3 p-1 to 2.4.4 open source.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tstamplis** [comment]
Sorry, closing this issue.  It was tracked down to 3rd party module.

**Comment by bulldogm11** [comment]
> Sorry, closing this issue. It was tracked down to 3rd party module.

What 3rd party module caused it? I'm dealing with the same issue.
