### ISSUE TITLE
Admin user cannot create New Cart Price Rule in 2.4.4

### ISSUE THREAD

**Issue by lagunacellar** [magento/magento2#35492]
### Preconditions (*)

1. Adobe Commerce 2.4.4
2.Commerce on the Cloud

### Steps to reproduce (*)

1. In Admin backend, click side panel Marketing > Promotions > Cart Price Rules 
<img width="617" alt="Marketing Side Panel" src="https://user-images.githubusercontent.com/64744041/168908878-4a3f5827-4589-4015-9ff8-de583e86bc97.png">

2. Click Add New Rule
<img width="1153" alt="Add New Cart Price Rule" src="https://user-images.githubusercontent.com/64744041/168908905-f00244e7-ee1c-4d33-8880-1dae2cda0b16.png">

### Expected result (*)

1. The creation of a new cart price rule with configurations available
2.

### Actual result (*)

1. Error: Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125 
<img width="1180" alt="Error message" src="https://user-images.githubusercontent.com/64744041/168909158-4f138d26-0802-4455-9b9d-55d750fce69a.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lagunacellar** [comment]
@magento give me 2.4-develop instance

**Comment by lagunacellar** [comment]
@magento I am working on this

**Comment by lagunacellar** [comment]
@magento add to contributors team

**Comment by lagunacellar** [comment]
@magento I am working on this

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-November** [comment]
Hi @shikhamis11 ,
Verified the issue on both Magento 2.4-develop with enterprise edition and 2.4.4 versions but could not able to reproduce the issue.
User is able to create new cart price rule with no issues.
![image](https://user-images.githubusercontent.com/60198231/169005606-95d426f9-ee79-4390-87f5-437a11f03764.png)
Kindly recheck the issue again on Magento 2.4-develop enterprise version and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by lagunacellar** [comment]
After further investigation, we found the issue was caused by StripeIntegration_Payments module.  As of version 3.1, stripe/stripe-payments has a bug.

**Comment by joaquin-becerra** [comment]
The problem, I Think, it happend in the Commerce Version, since the module magento/module-price-permissions in not in the Community version. I reproduceit in a 2.4.5 Commerce enterprise version, and the version: 100.4.1 of the magento/module-price-permissions module:

`    /**
     * Handle adminhtml_block_html_before event
     *
     * @param EventObserver $observer
     * @return void
     */
    public function execute(EventObserver $observer)
    {
        /** @var $block Template */
        $block = $observer->getBlock();

        $this->_filterByBlockName($block);

        // Handle prices that are shown when admin reviews customers shopping cart
        if (stripos($block->getNameInLayout(), 'customer_cart_') === 0) {
            if (!$this->observerData->isCanReadProductPrice()) {
                if ($block->getParentBlock()->getNameInLayout() == 'admin.customer.carts') {
                    $this->_removeColumnFromGrid($block, 'price');
                    $this->_removeColumnFromGrid($block, 'total');
                }
            }
        }
    }`
