### ISSUE TITLE
Grouped product with tax throws exception with PHP 8.1

### ISSUE THREAD

**Issue by craig-bartlett** [magento/magento2#35500]
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1 (though 8.0 is probably the same)
- Tax applied (in my case a blanket 20% tax)

### Steps to reproduce

1. Create a simple product
2. Create a grouped product and add the simple product to it, add the grouped product to a category
3. Ensure tax will be applied (in my case, I added a new tax zone for the UK, all regions and zip codes, at a rate of 20%.  I applied this to the Retail Customer class, and set all customer groups to use it)
4. Set both options to "Including and Excluding Tax" under Store > Configuration > Sales > Tax > Price Display Settings
5. Run bin/magento setup:upgrade (not entirely sure this is needed), bin/magento c:f and bin/magento index:reindex
6. Navigate to the category the grouped product belongs to on frontend

### Expected result

A list of products belonging to the category should be displayed.

### Actual result

An exception is thrown: 

`main.CRITICAL: Exception: Deprecated Functionality: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/m24/vendor/magento/module-tax/Pricing/Render/Adjustment.php on line 188 in /var/www/m24/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/m24/vendor/magento/module-tax/Pricing/Render/Adjustment.php(188): ucfirst()
#2 /var/www/m24/vendor/magento/module-tax/view/base/templates/pricing/adjustment.phtml(15): Magento\Tax\Pricing\Render\Adjustment->getDataPriceType()
#3 /var/www/m24/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#4 /var/www/m24/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#5 /var/www/m24/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#6 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#7 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#8 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#9 /var/www/m24/vendor/magento/module-tax/Pricing/Render/Adjustment.php(64): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /var/www/m24/vendor/magento/framework/Pricing/Render/AbstractAdjustment.php(57): Magento\Tax\Pricing\Render\Adjustment->apply()
#11 /var/www/m24/vendor/magento/framework/Pricing/Render/Amount.php(205): Magento\Framework\Pricing\Render\AbstractAdjustment->render()
#12 /var/www/m24/vendor/magento/framework/Pricing/Render/Amount.php(176): Magento\Framework\Pricing\Render\Amount->getAdjustments()
#13 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\Pricing\Render\Amount->_toHtml()
#14 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#15 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#16 /var/www/m24/vendor/magento/module-grouped-product/view/base/templates/product/price/final_price.phtml(30): Magento\Framework\View\Element\AbstractBlock->toHtml()
#17 /var/www/m24/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#18 /var/www/m24/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#19 /var/www/m24/generated/code/Magento/Catalog/Pricing/Render/FinalPriceBox/Interceptor.php(194): Magento\Framework\View\Element\Template->fetchView()
#20 /var/www/m24/vendor/magento/framework/View/Element/Template.php(293): Magento\Catalog\Pricing\Render\FinalPriceBox\Interceptor->fetchView()
#21 /var/www/m24/vendor/magento/framework/Pricing/Render/PriceBox.php(69): Magento\Framework\View\Element\Template->_toHtml()
#22 /var/www/m24/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php(71): Magento\Framework\Pricing\Render\PriceBox->_toHtml()
#23 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Catalog\Pricing\Render\FinalPriceBox->_toHtml()
#24 /var/www/m24/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(136): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#25 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1117): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#26 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#27 /var/www/m24/generated/code/Magento/Catalog/Pricing/Render/FinalPriceBox/Interceptor.php(410): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 /var/www/m24/vendor/magento/framework/Pricing/Render.php(97): Magento\Catalog\Pricing\Render\FinalPriceBox\Interceptor->toHtml()
#29 /var/www/m24/vendor/magento/module-catalog/Block/Product/ListProduct.php(411): Magento\Framework\Pricing\Render->render()
#30 /var/www/m24/generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(131): Magento\Catalog\Block\Product\ListProduct->getProductPrice()
#31 /var/www/m24/vendor/magento/module-catalog/view/frontend/templates/product/list.phtml(77): Magento\Catalog\Block\Product\ListProduct\Interceptor->getProductPrice()
#32 /var/www/m24/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#33 /var/www/m24/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#34 /var/www/m24/generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(392): Magento\Framework\View\Element\Template->fetchView()
#35 /var/www/m24/vendor/magento/framework/View/Element/Template.php(293): Magento\Catalog\Block\Product\ListProduct\Interceptor->fetchView()
#36 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#37 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#38 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#39 /var/www/m24/generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(617): Magento\Framework\View\Element\AbstractBlock->toHtml()
#40 /var/www/m24/vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\ListProduct\Interceptor->toHtml()
#41 /var/www/m24/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#42 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#43 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#44 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#45 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#46 /var/www/m24/vendor/magento/module-catalog/Block/Category/View.php(100): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#47 /var/www/m24/vendor/magento/module-catalog/view/frontend/templates/category/products.phtml(15): Magento\Catalog\Block\Category\View->getProductListHtml()
#48 /var/www/m24/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#49 /var/www/m24/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#50 /var/www/m24/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#51 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#52 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#53 /var/www/m24/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#54 /var/www/m24/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#55 /var/www/m24/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#56 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#57 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#58 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#59 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#60 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#61 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#62 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#63 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#64 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#65 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#66 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#67 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#68 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#69 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#70 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#71 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#72 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#73 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#74 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#75 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#76 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#77 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#78 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#79 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#80 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#81 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#82 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#83 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#84 /var/www/m24/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#85 /var/www/m24/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#86 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#87 /var/www/m24/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#88 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#89 /var/www/m24/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#90 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#91 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#92 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#93 /var/www/m24/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#94 /var/www/m24/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#95 /var/www/m24/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#96 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#97 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#98 /var/www/m24/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#99 /var/www/m24/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#100 /var/www/m24/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#101 /var/www/m24/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#102 /var/www/m24/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#103 /var/www/m24/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#104 {main} [] []
`

### Additional information

For whatever reason the priceType returned by amountRender is null, which is not a valid parameter for ucfirst in PHP 8. I suspect this has something to do with how grouped products calculate their display price but haven't tracked it down yet.

vendor/magento/module-tax/Pricing/Render/Adjustment.php line 184: 

`    public function getDataPriceType(): string
    {
        return $this->amountRender->getPriceType() === 'finalPrice'
            ? 'basePrice'
            : 'base' . ucfirst($this->amountRender->getPriceType());
    }`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by craig-bartlett** [comment]
@magento give me 2.4-develop instance

**Comment by craig-bartlett** [comment]
Doesn't seem to occur on the test instance - is it on PHP 8?

**Comment by engcom-Delta** [comment]
Hi @craig-bartlett ,
We have PHP 8.1 installed and we are using the same & We do not get any error when viewing the category that grouped belongs to it. please have a look and confirm us.

<img width="1440" alt="Screenshot 2022-05-20 at 10 09 10 PM" src="https://user-images.githubusercontent.com/51681379/169573638-f5c18a8f-d8f4-4cc6-8c71-fed889a1f188.png">

<img width="1440" alt="Screenshot 2022-05-20 at 10 05 09 PM" src="https://user-images.githubusercontent.com/51681379/169573253-72e2e3f1-3ae8-48ca-a335-5b28363e2c21.png">

**Comment by craig-bartlett** [comment]
Hi @engcom-Delta 

I'll refresh my environment and try to reproduce it again to make sure I didn't miss a step. In the meantime - did you set the tax rule to apply for all customers? Only your last screenshot doesn't show the incl. and excl. tax prices in the category view, even though the screenshot before shows that setting enabled.

Thanks again.

**Comment by craig-bartlett** [comment]
Hi @engcom-Delta 

I re-ran the full scenario from scratch and took screen shots along the way. I managed to reproduce the error.

- First I created 2 simple products and 1 grouped product, all in the same category and set to in-stock. I assigned the two simple products to the grouped product. At this point they display fine.

<img width="1504" alt="Screenshot 2022-05-23 at 13 25 36" src="https://user-images.githubusercontent.com/17876214/169824048-e4d6eeb2-ff23-45cb-8c4b-1ef7f5d233b7.png">

- I then created the tax rates as before and ensured it applied to all customers.

<img width="1401" alt="Screenshot 2022-05-23 at 13 29 14" src="https://user-images.githubusercontent.com/17876214/169824354-7fb9f081-6ae5-498f-ba18-a4e9c031f675.png">
<img width="1403" alt="Screenshot 2022-05-23 at 13 28 23" src="https://user-images.githubusercontent.com/17876214/169824359-565b6b8c-60d4-4635-8935-2bd44be25d9c.png">
<img width="1392" alt="Screenshot 2022-05-23 at 13 27 58" src="https://user-images.githubusercontent.com/17876214/169824360-b50798b0-797f-4e43-afad-4751d00fff3e.png">

- I changed the price settings to display catalog prices with and without tax.

<img width="1387" alt="Screenshot 2022-05-23 at 13 31 35" src="https://user-images.githubusercontent.com/17876214/169825263-c589d183-2a39-48c9-ae3c-2dbda79ea736.png">

- At this point I wanted to make sure it was a PHP 8.1 issue, so I left my machine running PHP 7.4. I ran setup:upgrade, cache:clear, cleared the generated/ folder, and ran a reindex. The page displayed as expected (note the "excl tax" price shows). 

<img width="1414" alt="Screenshot 2022-05-23 at 13 37 24" src="https://user-images.githubusercontent.com/17876214/169825674-43187157-0f30-4c47-98db-4d4414ddbd12.png">

- Finally I swapped to PHP 8.1. I wiped generated/ again, ran setup:upgrade, cache:clear, and ran a full reindex. This resulted in the page displaying incorrectly.

<img width="1400" alt="Screenshot 2022-05-23 at 13 49 13" src="https://user-images.githubusercontent.com/17876214/169825906-5056c87a-92d6-428a-a44e-9f746297ff1e.png">

In system.log I found the same error from before.

<img width="981" alt="Screenshot 2022-05-23 at 13 50 24" src="https://user-images.githubusercontent.com/17876214/169825955-a9f9276b-3e43-4d68-90c4-f9060aeb8193.png">

If I swap back to PHP 7.4 it works fine, so I'm 99% sure this is a PHP 8.1 issue.  For whatever reason, ucfirst() is being provided null as its parameter which is not allowed in PHP 8.1. This occurs in Magento\Tax\Pricing\Render\Adjustment (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Tax/Pricing/Render/Adjustment.php#L184). I don't know why getPriceType() returns null yet, or if it's even normal. 

I've forced it to work in my own environment by applying a plugin. The following plugin ensures that ucfirst() is not called on null. As I said, I'm not sure why getPriceType() is returning null yet in the first place, so if anyone else has this issue - use at your own risk:

`/** https://github.com/magento/magento2/issues/35500
     * @param Adjustment $subject
     * @param callable $proceed
     * @return string
     */
    public function aroundGetDataPriceType(Adjustment $subject, callable $proceed): String
    {
        $priceType = $subject->getAmountRender()->getPriceType();
        if ($priceType) {
            return $priceType === 'finalPrice'
                ? 'basePrice'
                : 'base' . ucfirst($priceType);
        } else {
            return 'base';
        }
    }`

**Comment by engcom-Delta** [comment]
Hi @craig-bartlett ,

Thank you so much for sharing the detailed steps and it is reproducible on Magento 2.4.4 instance with PHP 8.1 .
Hence marking the ticket issue is reproducible.

1. created 2 simple products and 1 grouped product, all in the same category and set to in-stock. I assigned the two simple products to the grouped product. At this point they display fine.

<img width="1440" alt="Screenshot 2022-05-24 at 3 12 40 PM" src="https://user-images.githubusercontent.com/51681379/170075554-70a4cd33-1deb-429a-b370-c3773fe899ad.png">

<img width="1440" alt="Screenshot 2022-05-24 at 5 35 51 PM" src="https://user-images.githubusercontent.com/51681379/170075662-3a5959f4-e520-40d3-8251-745048604746.png">

2. then created the tax rates as before and ensured it applied to all customers.

<img width="1440" alt="Screenshot 2022-05-24 at 5 49 57 PM" src="https://user-images.githubusercontent.com/51681379/170075832-25854b23-621b-401b-bc71-30f87b4cbf9b.png">

3. Tax rules 
 
<img width="1440" alt="Screenshot 2022-05-24 at 6 00 37 PM" src="https://user-images.githubusercontent.com/51681379/170076336-d458f3bd-7cde-4552-a232-4a2a4cf6efe1.png">

4. Changed the price settings to display catalog prices with and without tax.

<img width="1440" alt="Screenshot 2022-05-24 at 6 11 20 PM" src="https://user-images.githubusercontent.com/51681379/170076625-b2227116-97a0-4e09-92f8-46ea5e4efe27.png">

5. I wiped generated/ again, ran setup:upgrade, cache:clear, and ran a full reindex. This resulted in the page displaying incorrectly.

<img width="1440" alt="Screenshot 2022-05-24 at 9 03 03 PM" src="https://user-images.githubusercontent.com/51681379/170076790-476c4456-2d5d-4cd1-8d52-05d6e30bd072.png">

Thanks

**Comment by Pranav-242** [comment]
@magento i'm working on it.

**Comment by Hexmage** [comment]
The exact same error is thrown when you try to configure bundle products through the adminhtml.

**Comment by Hexmage** [comment]
Workaround:

change `vendor/magento/module-tax/Pricing/Render/Adjustment.php:188`

From 
` : 'base' . ucfirst($this->amountRender->getPriceType());`
To 
` : 'base' . ucfirst($this->amountRender->getPriceType() ?: '');`

**Comment by craig-bartlett** [comment]
Hi @Hexmage 

Cheers - for a temporary solution my plugin above does the same. It could also be applied as a Composer patch until this is fixed in the core.

Thanks

**Comment by pixiemediaweb** [comment]
found my way here with the same issue on a Cloud 2.4.4 upgrade - is there a patch planned?  @Pranav-242

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3157 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3157&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by peterjaap** [comment]
Patch for Magento 2.4.5-p1 to use with `vaimo/composer-patches`;

```
@package magento/module-tax
@link https://github.com/magento/magento2/issues/35500
@level 0

diff --git Pricing/Render/Adjustment.php Pricing/Render/Adjustment.php
index 0e5c619..06f4e02 100644
--- Pricing/Render/Adjustment.php
+++ Pricing/Render/Adjustment.php
@@ -185,6 +185,6 @@ class Adjustment extends AbstractAdjustment
     {
         return $this->amountRender->getPriceType() === 'finalPrice'
             ? 'basePrice'
-            : 'base' . ucfirst($this->amountRender->getPriceType());
+            : 'base' . ucfirst($this->amountRender->getPriceType() ?? '');
     }
 }
```
