### ISSUE TITLE
Order remains in status 'processing' after shipping, if items get partially refunded 

### ISSUE THREAD

**Issue by vseager** [magento/magento2#35528]
### Preconditions and environment

This is a repeat of issue #31063 which is closed despite the issue still being present in 2.4.3-p2.

- Magento 2.4.3-p2

### Steps to reproduce

1. Create an order with multiple items ordered.
2. From the admin, create an invoice for the order.
3. From the admin, create a credit memo and refund an item only partially.
4. From the admin, create a shipping for the order and the remaining items.
5. Observe the order status.

### Expected result

Status of the order should be 'Complete'. (As it is, when one item is fully refunded)

### Actual result

Status of the order stays 'Processing'.

### Additional information

1. Create an order for a Product in the quantity of 10
2. From Admin, create an Invoice for the order. (for all 10 items)
3. Create a Credit Memo for a quantity of 5 items
4. Ship the remaining 5 items

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @vseager ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4 Develop instance, it is not reproducible.
Order status is 'complete' after shipping successfully. 

followed below steps:
1. Create an order with multiple items ordered.

<img width="1440" alt="Screenshot 2022-05-25 at 7 04 04 PM" src="https://user-images.githubusercontent.com/51681379/170279488-d4ff6a13-a8e5-4800-adec-76ab6b5f4070.png">


2. From the admin, create an invoice for the order.

<img width="1440" alt="Screenshot 2022-05-25 at 7 08 59 PM" src="https://user-images.githubusercontent.com/51681379/170279800-09e2d435-f337-4781-ae54-097e13e58a0a.png">


3. From the admin, create a credit memo and refund an item only partially.

<img width="1440" alt="Screenshot 2022-05-25 at 7 11 53 PM" src="https://user-images.githubusercontent.com/51681379/170279892-7077c190-170c-404f-8afd-97b48d9aa1d2.png">

4. From the admin, create a shipping for the order and the remaining items.
Before: 
<img width="1440" alt="Screenshot 2022-05-25 at 7 13 01 PM" src="https://user-images.githubusercontent.com/51681379/170280142-621c89ae-98d3-4a66-9283-eab86df9e8f7.png">

After: 
<img width="1440" alt="Screenshot 2022-05-25 at 7 14 14 PM" src="https://user-images.githubusercontent.com/51681379/170280370-d5c951e4-f27a-459f-8962-b3f4fbefffe2.png">

<img width="1440" alt="Screenshot 2022-05-25 at 7 30 38 PM" src="https://user-images.githubusercontent.com/51681379/170280794-b4ae3144-230a-4e30-9efb-1e88b733bb9e.png">

Observe the order status. it is 'complete' status only

**Comment by engcom-Delta** [comment]
Hi @vseager ,

Thank you so much for sharing the detailed steps , We tried once again to reproduce it , Yes  issue is reproducible with a product that has 5 quantity .

Hence marked issue as 'Issue Confirmed'.

1. Go to SKU 24-MB05
2. Add more than one 24-MB05 to the cart (for example 5) - Your cart should show only ONE product but a QTY of 5

<img width="1440" alt="Screenshot 2022-05-26 at 12 54 49 PM" src="https://user-images.githubusercontent.com/51681379/170442651-1c8553cd-6cb6-45b1-bf35-d83fc2db6eae.png">

4. Invoice the whole order (5 x 25-MB05)

<img width="1440" alt="Screenshot 2022-05-26 at 12 56 11 PM" src="https://user-images.githubusercontent.com/51681379/170442836-b7502c09-fd34-4c0c-9ac7-1ecae0015ac0.png">

6. Create a credit memo for only 2 x 25-MB05

<img width="1440" alt="Screenshot 2022-05-26 at 12 58 50 PM" src="https://user-images.githubusercontent.com/51681379/170443283-977332f3-75cc-46e9-b780-be8b1d580f0a.png">

8. Create a shipment for the remaining 3 x 25-MB05

<img width="1440" alt="Screenshot 2022-05-26 at 1 21 51 PM" src="https://user-images.githubusercontent.com/51681379/170443722-ca1b7506-39ee-4e2a-88c6-8ea18a377033.png">
<img width="1440" alt="Screenshot 2022-05-26 at 1 22 16 PM" src="https://user-images.githubusercontent.com/51681379/170443781-c00c9c7a-8475-4eae-b685-4510858ca403.png">


Thanks

**Comment by nisha-vaghela** [comment]
@magento i am working on this.

**Comment by stupachenko** [comment]
@nisha-vaghela It was broken in https://github.com/magento/magento2/commit/cbc352e0d0235f1e8e200eee1f6587d08b1ec7ca

**Comment by hostep** [comment]
Closed without any comments? Possibly fixed by [AC-3178::Order remains in status 'processing' after shipping, if items is get partially refunded](https://github.com/magento/magento2/commit/64d121cc9ca5dc799ecc6cd3cfee7f943acc5e7b)

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3178 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3178&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by kwilliams-concentrix** [comment]
Can we get a patch for our version? 2.4.5p-2

**Comment by qlhu** [comment]
Just FYI the code fix doesn't work to partial refund/shipment to grouped product.
