### ISSUE TITLE
Base table or view not found: 1146 Table 'mgdemo244.mgreservations_temp_for_stock_2' doesn't exist

### ISSUE THREAD

**Issue by rathodsunny005** [magento/magento2#35539]
### Preconditions and environment

- Magento 2.4.4
- Install fresh Magento 2.4.4 with the table prefix
- create stock and sources

### Steps to reproduce

1. Install Magento 2.4.4 with table prefix `mg`
2. reindex inventory using using `php bin/magento indexer:reindex`
3. create stock and sources (default stock and source will be there you need to create second)

### Expected result

Successfully inventory index

### Actual result

Base table or view not found: 1146 Table '`mgdemo244.mgreservations_temp_for_stock_2`' doesn't exist

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rathodsunny005** [comment]
actully the problem in `Magento\InventoryIndexer\Indexer\Stock\ReservationsIndexTable` file.
```
**before**
/**
     * Return temporary table name.
     *
     * @param int $stockId
     * @return string
     */
    public function getTableName(int $stockId): string
    {
        return 'reservations_temp_for_stock_' . $stockId;
    }
```

**change to**

```
/**
     * Return temporary table name.
     *
     * @param int $stockId
     * @return string
     */
    public function getTableName(int $stockId): string
    {
        return $this->resourceConnection->getTableName('reservations_temp_for_stock_' . $stockId);
    }
```

the problem will be resolved.
Actually I don't know how to contribute and I don't have time to read your instruction of contribution so I'm just post here. :)
the problem in generating table without prefix and fetch data with prefix so it could not fetch the data.
thanks

**Comment by engcom-Delta** [comment]
Hi @rathodsunny005 ,
Thank you for raising an issue but need more clarity on the table name that is belong to mgservations_temp_for_stock_2?
We could see below list of tables.

<img width="927" alt="Screenshot 2022-05-30 at 9 23 21 PM" src="https://user-images.githubusercontent.com/51681379/171027740-5bf9bbc9-64ad-4cea-850e-058cadcedce2.png">

<img width="510" alt="Screenshot 2022-05-30 at 9 26 41 PM" src="https://user-images.githubusercontent.com/51681379/171027667-500fbd7a-f1bc-4c68-8e8a-557370738c44.png">

**Comment by rathodsunny005** [comment]
I think you have not used the prefix table. use prefix tables so every table name should have prefix like `catalog_product_entity` to `mgcatalog_product_entity` if you use `mg` as table prefix.

actually, it creates a table without prefix when you are using a prefix for your Magento website and fetches data with a prefix so table not found error appear.

**Comment by salesigniter** [comment]
@rathodsunny005 Thanks so much! You saved me so much stress by posting this fix
