### ISSUE TITLE
magento 2 plus search event observer not getting the same data as store front end.

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35541]
### Preconditions and environment

- Magento versions 2.3 and 2.4
- Anything else that would help a developer reproduce the bug
I create the custom modules I want all search results the same as storefronts.  here you can find the code https://github.com/Sanjay-100/magento2_search

### Steps to reproduce

1 Setup mangeto 
2 https://github.com/Sanjay-100/magento2_search  install this module 
3 do store search 
4 plugin show the search result was different  you can compare with without plugin and with plugin, code see both result are too different 

### Expected result

do the store search the store search results will be output into modules event observer

### Actual result

do the store search the store search results will be output into modules event observer

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Sanjay-100** [comment]
@m2-community-project

**Summary of the issue  :-** Magento versions 2.3 and 2.4
Anything else that would help a developer reproduce the bug
I create the custom modules I want all search results the same as storefronts. here you can find the code https://github.com/Sanjay-100/magento2_search

**Information on your environment** :- LEMP stack magento 2.4 development mode 
**Steps to reproduce** :- user the my git repo test Magento modules and compare with Magento default search 
**Expected and actual results** :- on my code repo result same as the magento

**Comment by engcom-Hotel** [comment]
Hello @Sanjay-100,

Thanks for the report and contribution!

We request you to please provide some more information on this issue like expected and the actual result with a screenshot if possible. Currently, both actual and expected results are the same.

Also please let us know the specific issue you are facing while using Magento. I will also suggest you to please raise this query in [Magento stack exchange](https://magento.stackexchange.com/).

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
