### ISSUE TITLE
upgrade 2.4.4 There are no commands defined in the "setup" namespace.

### ISSUE THREAD

**Issue by Skyfly2021** [magento/magento2#35543]
### Preconditions and environment

- Magento 2.4.3-p1
- Upgrade 2.4.4

### Steps to reproduce

1.composer require  magento/product-community-edition 2.4.4 --no-update
2.composer update
3.rm -rf var/cache/*
4.rm -rf var/page_cache/*
5.rm -rf var/page_cache/*
6.bin/magento setup:upgrade

### Expected result

Expect step 6 to run successfully

### Actual result

![image](https://user-images.githubusercontent.com/53896477/170520785-f4e20441-2904-41bb-a26f-e229390901e5.png)
![image](https://user-images.githubusercontent.com/53896477/170520952-6570940e-f7e1-4f2f-8c18-617e2f3de014.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Skyfly2021 ,
Thank you for reporting and collaboration. Verified the issue by upgrading 2.4.3-p1 to 2.4.4 version using ref [document](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html) but could not able to reproduce the issue.
Upgrade is successful. 
Please check the permissions and and also try running the commands with php bin/magento which may solve your issue.
Kindly check if any 3rd party extensions/modules enabled is causing this issue or Magento [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) compatible for 2.4.4
Thank you.

**Comment by Skyfly2021** [comment]
I have successfully upgraded after disabling the vertex module, thanks
