### ISSUE TITLE
Minicart and customer name issue

### ISSUE THREAD

**Issue by devhn** [magento/magento2#3554]
Hi,

after upgrading to Magento 2.0.2. i see strange issues (theme Luma and Blank):
1. I logged into my account on frontend as a customer and added for example five items into the cart. Minicart shows there are five items inside. After logging out the minicart then shows 0 items inside but the red square (items counter) is visible (like it has some items inside). After logging to the account again the minicart still shows 0 items. Then if I add a new product in cart the minicart updates it self with 5 old and 1 new products = 6 items total.
2. When logging into the account the customer name doesn't show up within the header beside the dropdown arrow (Luma only).

Screenshoots:
- http://i.imgur.com/F8G5XnP.png (minicart not showing cart items after logging in and customer name not showing)
- http://i.imgur.com/zYz4kS8.png (missing customer name within span)

So far I tried:
- cleaning & flushing all the caches (both from Magento & broswer)
- removing var/ and pub/static

Strangely I didn't see this issues in 2.0.0. Is this a bug or some user (mine) setup error? Thanks.

**Comment by ishakhsuvarov** [comment]
@bb8d Thank you for reporting these issues. 

> the red square (items counter) is visible (like it has some items inside)

Fix for this issue is already available in the `develop` branch. You may use [commit](https://github.com/magento/magento2/commit/eec3cf17bc5deae71c83c797d1339de46cf6905f) `eec3cf1` as a hotfix.

Regarding other points, we had no luck reproducing it so far. Please try to clear browser's localStorage in addition to the caches you mentioned. Such kind of problems are sometimes observed when experimenting with the different installations on the same domain. 

If the issue persists – please let us know.

**Comment by devhn** [comment]
Thank you, minicart square is now solved.

I've tried with your suggestions regarding the account issue but no luck, still cant get customer name to appear after logging. It appears only when i add an item to cart, go to checkout and then go back to store.

p.s. We have 4 installations on different subdomains but share the same parent domain.

**Comment by ishakhsuvarov** [comment]
@bb8d Do you use secure urls (https)? Any JavaScript errors in browser console?

**Comment by devhn** [comment]
http and no errors.

**Comment by sengaigibon** [comment]
Hello, 
I think I have the same problem, described here:
https://github.com/magento/magento2/issues/3572

**Comment by devhn** [comment]
Hi,

yep, looks +/- all the same issues, thanks.

**Comment by ishakhsuvarov** [comment]
@bb8d Do you have any extensions / modifications on your Magento installation? Does this happen on a clean install with the stock settings?
We still can not reproduce the issue, any additional information would be helpful.

**Comment by ishakhsuvarov** [comment]
Indeed, with the preconditions described in #3572 issue may be reproduced. We are going to look into this case.

**Comment by devhn** [comment]
Yes, sengaigibon has the same issues - i have some custom modules, but the problem persist when i create fresh installation without them, using only custom theme.

**Comment by devhn** [comment]
p.s. can this issue be merged with [#3572](https://github.com/magento/magento2/issues/3572)?

**Comment by ishakhsuvarov** [comment]
@bb8d @sengaigibon 
This issue seems to duplicate #3572 
Closing this ticket for now.
