### ISSUE TITLE
PROMO code apply on the shipping showing null in graphql responce

### ISSUE THREAD

**Issue by Abhay-Agrawal** [magento/magento2#35545]
*As a ___ I want to ___ so that ___.*

**Steps to reproduce:**
1. Navigate to Marketing Menu-> Promotions -> Cart Price Rule
2. Add the New Rule
3. Add the One Rule and apply it on shipping Amount. Plz check the attached screenshot to add shipping rule
![Screenshot (1)](https://user-images.githubusercontent.com/55655451/170628184-0dc76802-30e0-4646-9420-8f6785360dfe.png)

1. apply the same PROMO code on the shipping amount
2. check the graphql response
3. showing discounts null
"discounts": null,
                "discount": {
                    "label": [
                        "FreeShip"
                    ],
                    "amount": {
                        "value": -15
                    }
                },
or
_**Run cart graphql query:**
{
  cart(cart_id: "croja3eQTvZe2OI26BoMyN94N9B2z3Fd") {
    email
    items {
      uid
      prices {
        total_item_discount {
          value
        }
        price {
          value
        }
        discounts {
          label
          amount {
            value
          }
        }
      }
      product {
        name
        sku
      }
      quantity
    }
    applied_coupons {
      code
    }
    prices {
      discounts {
        amount {
          value
        }
        label
      }
      grand_total {
        value
      }
    }
  }
}_
**Expected result:**
All Graphql requests having discount field should return correct discount value in response

**Additional Information:**
Please refer the [comment](https://github.com/magento/magento2/issues/35545#issuecomment-1139589146)

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and discount amount applied on shipping amount is ignored. Only discount on product price is displayed in graphql response.
**Steps performed:**
1. Created cart Price Rule Specific Coupon, Actions - 100 % discount and Apply to shipping amount - yes, Free shipping - For Shipments with matching items
![image](https://user-images.githubusercontent.com/60198231/170702044-8c76821b-e2ac-4118-8095-7ab1c0198f60.png)
2. Front-end - login as customer - Add product to cart and select Flat rate shipping methods.
3. Apply discount
4. Run the cart graphql query
**Issue**: Total discount is displayed ignoring discount applied on Shipping amount
![image](https://user-images.githubusercontent.com/60198231/170702255-50f87d1a-0c98-4124-8283-4237bb598527.png)
![image](https://user-images.githubusercontent.com/60198231/170702336-f26e6bc9-4de0-4c46-9c67-67180ed80bf4.png)
While on UI - discount amount is displayed including the discount applied on shipping amount.

**Comment by artskirk** [comment]
@magento give me 2.4-develop instance

**Comment by artskirk** [comment]
@magento I am working on this

**Comment by engcom-Charlie** [comment]
As mentioned in [PR](https://github.com/magento/magento2/pull/35725#issuecomment-1277374881), the internal team worked on this issue and committed in [this](https://github.com/magento/magento2/commit/29bacd0b09b443b61370d47d8e552ae0a5c99ce0) revision. 

Hence closing this issue.

Thank you!
