### ISSUE TITLE
Cart Rules with conditions on attributes only present on some products causes an error on checkout page.

### ISSUE THREAD

**Issue by freakpol** [magento/magento2#35558]
### Preconditions and environment

- Vanilla Magento version: 2.4.4 (with sample data)
- PHP: 8.1

### Steps to reproduce

1.- Create a cart rule with a condition on some product attribute. For example, I've created a rule that looks like this:

If [ALL] of these conditions are [TRUE] :
    If an item is [FOUND] in the cart with [ALL] of these conditions true: 
        Style Bags  [contains] [Backpack, Luggage]

2.- Save the rule.
3.- In the front add any product that is NOT a bag, for example, I've aded "Breathe-Easy Tank".
4.- Proceed to checkout.

### Expected result

No error message

### Actual result

Deprecated Functionality: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in .../vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php on line 556

### Additional information

This is beacause that portion of code is checking ALL items in the cart, to check if the validate against the given condition.
Thus, when getting the "Style Bags" attribute value for a products that is NOT a bag, it returns null (as any DataObject).
Then, that retrieved value is used in a strlen and explode functions, that, in PHP8.1 expect the parameter to be string.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by freakpol** [comment]
Please, keep in mind that this is reproducible using PHP 8.1.

**Comment by freakpol** [comment]
It must be some PHP configuration then, cause for me, any call to the strlen, strpos, etc etc that are NOT receiving a string are throwing exceptins like this one: Exception: Deprecated Functionality: strlen(): Passing null to parameter #35441 
So, I'm able to reproduce this 100% of the times. Even worse, I cannot even add a product to the cart when this issue is present.

Is there any info I can give you to help to reproduce the issue?

**Comment by freakpol** [comment]
Note also that this happens on Magento 2.4.4.
Magento 2.4-develop branch seems to be fixed already.

**M2.4.4**
https://github.com/magento/magento2/blob/2.4.4/app/code/Magento/Rule/Model/Condition/Product/AbstractProduct.php#L556

**M2.4-develop**
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Rule/Model/Condition/Product/AbstractProduct.php#L557

So yeah, in develop branch is not reproducible but it is present on 2.4.4.

**Comment by engcom-November** [comment]
Hi @freakpol ,
Verified the issue again on Magento 2.4.4 community edition with sample data installed and PHP 8.1 version but still could not able to reproduce the issue.
User is able to place the order with/without coupon code
![image](https://user-images.githubusercontent.com/60198231/171400303-f3bd2076-cf15-43f0-b6c1-f00a7b2c0c5b.png)
![image](https://user-images.githubusercontent.com/60198231/171400217-3e341e81-4758-491c-b8c2-a2c60b2e5d19.png)
![image](https://user-images.githubusercontent.com/60198231/171400263-3e64c9c7-703b-418c-bdd2-f93ce9e9abf1.png)
Kindly check the issue on latest code base as the issue may have fixed already and provide missing steps / configuration details if any if the issue is still reproducible.
Thank you.
