### ISSUE TITLE
Category with Virtual Rules is not showing correct result

### ISSUE THREAD

**Issue by dannya06** [magento/magento2#35555]
### Preconditions and environment

- Magento Community Edition 2.3.4 with sample data
- PHP 7.3

### Steps to reproduce

1. Add two or three Subcategory (children) on parent category.
![image](https://user-images.githubusercontent.com/87116996/171077221-dd42f53b-883d-45f7-968f-1b9e2db7556d.png)

2. Make all of them have the virtual rule with different rule, but in parent category check attribute is not sofa model.
![image](https://user-images.githubusercontent.com/87116996/171077472-2432b191-99b8-4ff8-9012-56a53143fb76.png)
![image](https://user-images.githubusercontent.com/87116996/171077341-786b8684-d373-4557-b707-c0f3b0ce6faf.png)
![image](https://user-images.githubusercontent.com/87116996/171077390-2f3c2cbd-ca86-473c-b120-160d6b6808f3.png)
![image](https://user-images.githubusercontent.com/87116996/171077426-b3333453-3b5f-47ed-8aac-03b321306b96.png)

### Expected result

The result in parent category using virtual category rule give the correct result (Products with the attributes of sofa models don't go to the generator) and can be filter.

### Actual result

The result give the incorrect result (Products with the attributes of sofa models still go to the generator) and can't be filter (ex: price is greater 100) the result can't be filter. Here the result
![image (33)](https://user-images.githubusercontent.com/87116996/171081463-dc111c39-2318-4d88-83b2-aeefcda7a982.png)
![image (34)](https://user-images.githubusercontent.com/87116996/171081473-d2de55f9-07f8-49ff-a1aa-8cd765a9d9a5.png)
![image (35)](https://user-images.githubusercontent.com/87116996/171081478-13ec0029-cbe4-497c-9cc1-3d48a9301aa7.png)
![image](https://user-images.githubusercontent.com/87116996/171077599-83997d2a-ad2f-4e5d-bfac-23ec2e2dc629.png)
![image](https://user-images.githubusercontent.com/87116996/171077635-07816994-3204-40df-8b52-a6335888ee4a.png)
![image](https://user-images.githubusercontent.com/87116996/171077791-f99c448a-59c7-4b37-8e7d-bbbf100f72c3.png)
![image](https://user-images.githubusercontent.com/87116996/171077817-cfe21907-369f-4cf2-9a75-39e599921d29.png)
![image](https://user-images.githubusercontent.com/87116996/171078872-4eadf351-2474-4fd0-8cad-808f9692c9c8.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adyasa** [comment]
Hello I believe this is Elastic Issue from another vendor.
cc @dannya06

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
