### ISSUE TITLE
Product edit form fails if title is empty

### ISSUE THREAD

**Issue by MarksAfanasevics** [magento/magento2#35557]
### Preconditions and environment

- Magento version 2.4.4
- Custom label in product form that is empty

### Steps to reproduce

- Go to product edit form in admin

### Expected result

Product edit form works fine

### Actual result

Console error:
`[2022-05-31 01:29:58] [ERROR] Failed to load the "ui/form/fieldset" template requested by "product_form.product_form.gallery".`
Product edit form is broken

### Additional information

Can be fixed in vendor/magento/module-ui/view/base/web/templates/form/fieldset.html, by changing if condition in second div (fieldset-wrapper-title)
`         if="label">`
to
`         if="$data.label">`

After that, everything works fine. 

I'm not sure, but as I understand, error happens because of some custom label with empty value.
![image](https://user-images.githubusercontent.com/62943480/171159397-a50b18d3-f1c6-49a5-8e32-47acb904072e.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @MarksAfanasevics ,
Thank you for reporting and collaboration. However, Product Label is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
