### ISSUE TITLE
Magento 2 GraphQl Products Query should return Child Variant Image Url when custom filter is used

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#35563]
### Summary (*)

I am using Magento 2 GraphQl for products query with some filter attributes like "color". It is returning correct products but the image URL is of the parent product where it should return the correct child variant image url. 
### Examples (*)

{
  products(filter: {
  color:{
    eq:"14"
  }
    category_id:{
      eq:"14"
    }
  }
  sort: {
    position: ASC
  }) {
    total_count
    items {
      name
      country_of_manufacture
      sku
      color
      image{
        disabled
        label
        position
        url
      }
      thumbnail {
        disabled
        label
        position
        url
      }
      swatch_image
      small_image {
        disabled
        label
        position
        url
      }
    }
  }
}

### Proposed solution

The response should return the child variant image url as well. Because in PWA it is creating issue where incorrect images are shown when using layered filter.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ **S1** ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround.

**Comment by engcom-November** [comment]
Hi @routbiplab ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch however graphql response is the same with/without custom attribute / filter
**Steps performed:**
1. Enabled Color attribute (Stores - Attributes - Product - color)
![image](https://user-images.githubusercontent.com/60198231/172165795-4a5a5827-b670-4eb5-a000-9603bce3bfe0.png)
![image](https://user-images.githubusercontent.com/60198231/172165835-86742231-9ee4-4c26-a12a-d06f36d36bb3.png)
2. Reindex and clear cache
3. Created configurable product with child variants
4. Run the Graphql query: Response retrieved as expected
![image](https://user-images.githubusercontent.com/60198231/172166019-5583edb8-4e94-4e0d-b4f4-8dde1856f5cf.png)
5. Run the below query:
![image](https://user-images.githubusercontent.com/60198231/172166145-ec7b87dc-363e-426e-be8d-7acf2c8a0957.png)
Graphql response if not effected with/without the attribute. 
@routbiplab Can you please check the behavior on Magento 2.4-develop branch and elaborate the steps to reproduce this issue. 
Thank you.

**Comment by routbiplab** [comment]
Hi @engcom-November In the above response that you shared can you see the Image URL. It is same for all the products. 

If you observe closely it is returning the image of the parent product for all its variant. 

Steps to reproduce in any PWA website:

1. Select any color in color layered filter.
2. See the product images. All products may not contain the color selected in the filter.


**Request**:
`{
  products(filter: {
  fashion_color:{
    eq:"14"
  }
    category_id:{
      eq:"14"
    }
  }
  sort: {
    position: ASC
  }) {
    total_count
    items {
      name
      sku
      small_image{
        url
      }
    }
  }
}`


**Response**:
`{
  "data": {
    "products": {
      "total_count": 3,
      "items": [
        {
          "name": "Angelina Tank Dress",
          "sku": "VD01",
          "small_image": {
            "url": "http://localhost:8080/magento243/media/catalog/product/cache/fe7bb503d3dfa1a46b68bcd97bddeee6/v/d/vd01-ll_main.jpg"
          }
        },
        {
          "name": "Candace Dress",
          "sku": "VD02",
          "small_image": {
            "url": "http://localhost:8080/magento243/media/catalog/product/cache/fe7bb503d3dfa1a46b68bcd97bddeee6/v/d/vd02-ll_main.jpg"
          }
        },
        {
          "name": "Karena Halter Dress",
          "sku": "VD03",
          "small_image": {
            "url": "http://localhost:8080/magento243/media/catalog/product/cache/fe7bb503d3dfa1a46b68bcd97bddeee6/v/d/vd03-mt_main.jpg"
          }
        }
      ]
    }
  }
}`

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @routbiplab ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
