### ISSUE TITLE
Delete all categories at once in Magento 2

### ISSUE THREAD

**Issue by justinb** [magento/magento2#3557]
We have been experimenting with syncing our existing database(not Magento) to Magento 2.0.

In the process we have created over 1000 categories, but then we rearranged all the IDs to sync with our system. The problem is that I can no longer import the new categories as I get the error "URL key for specified store already exists." and we are getting duplicate categories now.

I think the best solution would be to clear them all out and import fresh. I found this tutorial for 1.9
https://gist.github.com/jklance/9664371

When I look at the new database I notice small differences
1. entity_type_id is in all the old categoriy tables but none of the new ones.
2. new database has an additional table catalog_category_product_index_tmp

My questions are these,
1. can I use that code I found and modify to remove "entity_type_id"
   and add TRUNCATE TABLE `catalog_category_product_index_tmp`; 
2. or is there more I need to modify?
3. or can you provide me a clean script to remove all categories?

we only have 1 test product in the system, so no need to worry about them

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by justinb** [comment]
Sorry aobut that, I have tried all those avenues, this question is techical for those areas, no one is able to answer and my question sits unansered for days on end (magento commity forum)
