### ISSUE TITLE
Customer Information Sidebar not displayed correctly

### ISSUE THREAD

**Issue by HorizonCode** [magento/magento2#35585]
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1

### Steps to reproduce

1. setup a 2.4.3 build of Magento
2. Update to 2.4.4 via Composer

### Expected result

Expected Result: The Sidebar should be displayed correctly

### Actual result

![The Sidebar](https://i.imgur.com/xnvbmBC.png)

The error message in console
```
JQMIGRATE: HTML tags must be properly nested and closed: <div class="admin__page-nav">
    <div class="admin__page-nav-title" css="_collapsible: collapsible, _opened: opened && collapsible" click="toggleOpened" keyboard="13: toggleOpened">
        <strong tabindex="1" text="label" keyboard="13: toggleOpened"/>
    </div>
    <ul class="admin__page-nav-items items" each="elems" visible="opened">
        <if args="$data.sub_section">
            <li class="admin__page-nav-title">
                <strong text="$data.sub_section"/>
            </li>
        </if>
        <li class="admin__page-nav-item" tabindex="2" css="_active: active, _loading: loading" click="activate" keyboard="13: activate">
            <a class="admin__page-nav-link" css="_changed: changed" attr="id: 'tab_' + index, href: '#' + index">
                <span text="label"/>
                <span class="admin__page-nav-item-messages">
                    <span class="admin__page-nav-item-message _changed">
                        <span class="admin__page-nav-item-message-icon"/>
                        <span class="admin__page-nav-item-message-tooltip"
                               translate="'Changes have been made to this section that have not been saved.'"/>
                    </span>
                    <span class="admin__page-nav-item-message-loader">
                        <span class="spinner">
                           <span repeat="8"/>
                        </span>
                   </span>
                </span>
            </a>
        </li>
    </ul>
</div>
```

### Additional information

I tried it multiple times to update, all with the same result.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @HorizonCode ,
Thank you for raising an issue , we tried to reproduce the issue after upgrading from Magento 2.4.3 to 2.4.4 instance.unfortunately issue is not reproducible. Hence request to help us with appropriate steps to replicate the issue.

Here are the screenshots.

**Before upgrading** 
<img width="1440" alt="Screenshot 2022-06-09 at 5 03 51 PM" src="https://user-images.githubusercontent.com/51681379/172839773-2c4a50d6-5a8f-44e4-a2a7-d5992eab257f.png">

**After upgrading**

<img width="1440" alt="Screenshot 2022-06-09 at 5 15 38 PM" src="https://user-images.githubusercontent.com/51681379/172839910-501c6fa8-73c7-4391-823f-a0970acfca5c.png">
