### ISSUE TITLE
Attempting to Place Order with payment method of G Pay (Google Pay) fails

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#35584]
### Preconditions and environment

Attempting to Place Order with payment method of G Pay (Google Pay) fails with error message...

"**Request Failed**
Unexpected developer error, please try again later."

Environment is M2.4.4 with PHP 7.4 using native Braintree extension bundled with M2.4.4
Problem appears to have begun co-incident with upgrade from M2.4.3-p1 to M2.4.4

IMPORTANT:  There is a "sandbox" vs "production" aspect to this problem.   When M2.4.4 is in production mode using the Basic Braintree Settings of Environment = "Sandbox" a checkout with G Pay succeeds... switch the Braintree Environment to "Production", validate credentials and clear cache... checkout with G Pay fails as described.  What this means is you will be unable to reproduce the problem without using live Production credentials with Braintree.

### Steps to reproduce

Upgrade working M2.4.3-p1 environment with working G Pay payment method to M2.4.4 using "Production" Braintree credentials

IMPORTANT:  There is a "sandbox" vs "production" aspect to this problem.   When M2.4.4 is in production mode using the Basic Braintree Settings of Environment = "Sandbox" a checkout with G Pay succeeds... switch the Braintree Environment to "Production", validate credentials and clear cache... checkout with G Pay fails as described.  What this means is you will be unable to reproduce the problem without using live Production credentials with Braintree.

### Expected result

G Pay continues to work as an accepted payment method.

### Actual result

Attempting to Place Order with payment method of G Pay (Google Pay) fails with error message...

**Request Failed**
Unexpected developer error, please try again later.

There were no associated errors present in system.log

### Additional information

Environment is M2.4.4 (Production) with PHP 7.4 using native Braintree extension bundled with M2.4.4
Problem appears to have begun co-incident with upgrade from M2.4.3-p1 to M2.4.4

Customer is unable to make payment via Gpay and must choose a different payment method.   G Pay payments are relatively rare and this issue was only detected day after the upgrade M2.4.4 when a customer complained of being unable to make payment via G Pay.

IMPORTANT:  There is a "sandbox" vs "production" aspect to this problem.   When M2.4.4 is in production mode using the Basic Braintree Settings of Environment = "Sandbox" a checkout with G Pay succeeds... switch the Braintree Environment to "Production", validate credentials and clear cache... checkout with G Pay fails as described.  What this means is you will be unable to reproduce the problem without using live Production credentials with Braintree.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by n2diving-dgx** [comment]
Fails on both Android/Chrome (S22 phone) and Win11/Chrome desktop

![image](https://user-images.githubusercontent.com/17930467/172433008-b596d5ba-e1e5-49c8-ba11-c9ab726d5f28.png)

**Comment by cankarales** [comment]
I have a simmilar issue so here are my 2 cents.

 I found that there is an issue in this file: `Paypal_Braintree/js/googlepay.js` on lines 133 through 135:
```
if (this.getEnvironment() !== "TEST") {
    result['merchantId'] = this.getMerchantId();
}
```

the `if()` statement implies that this issue only appears in production environments. If you remove it, you'll get the same error which is:

> DEVELOPER_ERROR in loadPaymentData: PaymentDataRequest.merchantId does not exist.

this means that `merchantId` is not a valid field, which according to Google Pay docs is true. Correct way would be like this:

```
if (this.getEnvironment() !== "TEST") {
    result.merchantInfo = { merchantId: this.getMerchantId() };
}
```

This was I'm allowed to enter my card info but then I get a different error...

**Comment by engcom-Delta** [comment]
@magento give me 2.4.4 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by Kishorchhugani** [comment]
I am Facing the Same issue While Using Gpay in my checkout in magento version 2.4.4

**Comment by Kishorchhugani** [comment]
hi @engcom-Delta  any Updates?

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.4 instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.4 instance

**Comment by n2diving-dgx** [comment]
FYI, I contacted the original authors of the Braintree extension embedded in 2.4.4, named Gene Commerce, and they were able to reproduce the problem.   They have developed a patch which resolves the issue.

**Comment by cankarales** [comment]
@n2diving-dgx correct! I already pointed this out in my first comment. Has Gene Commerce already released the patch? If so, where can we find it?

**Comment by engcom-Delta** [comment]
@magento give me 2.4.3-p1 instance with edition ee

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.4 instance with edition ee

**Comment by engcom-Delta** [comment]
@magento give me 2.4.4 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4.4 instance with edition ee

**Comment by engcom-Delta** [comment]
@magento give me 2.4.4 instance

**Comment by j-lloyd-slc** [comment]
This continues to be an issue with Google Pay and 2.4.4. I have not been able to get a response from the developer.

**Comment by engcom-Hotel** [comment]
Hello @n2diving-dgx,

The Code of this extension is not part of the https://github.com/magento/magento2 git repository.

The community is not able to provide a fix in this repository, and we are not able to deliver such Pull Request 

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Marketplace](https://marketplace.magento.com/extensions.html) page

Hence closing this issue from here.

Thanks

**Comment by ecoprince** [comment]
I found an issue with getPaymentRequest() structure.

Solution:
**vendor/paypal/module-braintree-core/view/frontend/web/js/googlepay/implementations/core-checkout/method-renderer/googlepay.js**

getPaymentRequest()

     if (this.getEnvironment() !== "TEST") {
          result.merchantInfo = {
              "merchantId": this.getMerchantId()
          };
     }

**Comment by johncarlson21** [comment]
the above fix works, however only on the checkout page and not for the buttons on the cart page or the mini cart.
I'm not even sure how this gets loaded to my magento and I've been trying to find the actual package repo as there is an update for it according to composer, however it will not update until you either force it or I believe upgrade your version of magento.
I would like to see the code for the paypal/braintree package so I can determine if it was actually fixed.
any insight would be helpful.
