### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by Totarenx** [magento/magento2#3558]
#1731

I'm trying to do the same using custom js and got it to work... sometimes. But sometimes jQuery library is loaded later than script that use it.

Template:

```
<script>
    require([
        'jquery',
        'domReady!',
        'Vendor_Module/js/myscript'
    ], function ($) {
        $(document).ready(function () {
            $(".class_name").jQueryPlugin({
                .......................
            });
        });
    });
</script>
```

Myscript:

```
define(['jquery'], (function($, window, document, undefined) {
    'use strict';
    if ( !window.jQuery ) {
        console.log('Jquery is undefined!');
    }
    ....
    $.fn.jQueryPlugin = function() {
        ....
    };
    ....
})(window.jQuery, window, document));
```

Sometimes I've got in console:
**Jquery is undefined!
Uncaught TypeError: Cannot read property 'fn' of undefined**

**Comment by Totarenx** [comment]
Solved through "shim"

**Comment by rlynjb** [comment]
@Totarenx what shim was it? I'm having the same issue right now

**Comment by Totarenx** [comment]
file: Vendor/Module/view/frontend/requirejs-config.js
content:
var config = {
	"map": {
		'*': {
			"script_short_name": "Vendor_Module/js/myscript"
		}
	},
	"shim": {
		"Vendor_Module/js/myscript": ["jquery"]
	}
};
