### ISSUE TITLE
Any specific payload format to be used when using payment api to pay using credit card

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35597]
Magento 2.3.4

### Summary (*)

Unable to make payment using credit card via rest api on payone_creditcard payment method
### Examples (*)

Unable to make order using that credit card via rest api
### Proposed solution

can you please suggest me the payload which we can use for making payment from credit card

**Comment by engcom-Hotel** [comment]
Hello @hemendraajmera,

I suggest you post these kinds of queries in the [Magento StackExchange](https://magento.stackexchange.com/). This platform is not suitable for this.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @hemendraajmera,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
