### ISSUE TITLE
Environment emulation nesting when sending invoice email

### ISSUE THREAD

**Issue by pumpe24** [magento/magento2#35603]
On Magento Open Source 2.4.4, `$this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);` is added to `Magento\Sales\Model\Order\Email\Sender\InvoiceSender::send` .
While on this emulation there is a call to `Magento\Payment\Helper\Data::getInfoBlockHtml` where the emulation is started again.

This results in an error message `main.ERROR: Environment emulation nesting is not allowed` in system.log every time an invoice email is sent.

### Preconditions (*)
1. Magento Open Source 2.4.4

### Steps to reproduce (*)
1.  send an invoice email

### Expected result (*)
1. it works, but system.log is flooded with the error message below

### Actual result (*)
1. system.log is flooded with `main.ERROR: Environment emulation nesting is not allowed`

**Comment by nisha-vaghela** [comment]
@magento i am working on this

**Comment by simonmaass** [comment]
can confirm this issue on 2.4.4 - not only on invoices but also on credit memos

**Comment by drinkingsouls** [comment]
I am seeing this error in my system.log too since upgrading to Magento 2.4.4

main.ERROR: Environment emulation nesting is not allowed. [] []

**Comment by xtremevision** [comment]
Same here, also seeing it after upgrade to 2.4.4. I also think it's affecting cart integrity/behavior, as in, I place the order, it completes successfully, I see the error in the log, the cart shows it's empty, I got to a category page and the same product and suddenly the cart shows 2 items. If I proceed with the order and try to place it, I get an exception:

[2022-08-10T23:09:54.909522+00:00] main.ERROR: Magento2 v3.2.7: The cart details have changed. Please refresh the page and try again (1). [] []
[2022-08-10T23:09:54.909680+00:00] main.ERROR: Magento2 v3.2.7: #0 /home/michael/www/Farmacias-Roma-Magento/htdocs/vendor/stripe/module-payments/Model/PaymentMethod.php(180): StripeIntegration\Payments\Model\PaymentElement->updateFromOrder()

(I didn't paste the whole stack trace, too big)

If I refresh the page, I can place the order successfully, but the same issue happens again.

**Comment by reense** [comment]
We're having this issue with multiple shops as well.

**Comment by kalalruturaj** [comment]
> 

any solution on this issue?

**Comment by LeoNun** [comment]
Hello,
having the same problem in magento 2.4.5.

Best regards,
L Nunes

**Comment by jdubbya** [comment]
This is also occurring when sending out **shipment** notification emails in Magento 2.4.4-p1.

**Comment by danielpugh** [comment]
seeing this problem as well

**Comment by i6media** [comment]
Same here, possibly related to invoices being sent twice by cron (1 minute after each other)

**Comment by MartynasKasp** [comment]
The issue still exists in 2.4.5-p1 (community edition) when sending an email after shipping an order.

**Comment by simonmaass** [comment]
can confirm this for 2.4.5-p1

**Comment by MikeDevs** [comment]
Same issue on 2.4.4-p2

**Comment by rofokken** [comment]
Still exist on: Adobe Commerce ver. 2.4.5-p1

**Comment by glo23503** [comment]
Internal team started working on the issue.

**Comment by glo23503** [comment]
@magento I am working on this

**Comment by michi-z** [comment]
Hello, when will this PR be handled?

**Comment by hostep** [comment]
@glo23503: this issue got closed without any comments, any idea why?

Might have been fixed by [ACP2E-1341: [On-Premise] Merchant Informed Core Issue Magento 2.4.4 main.ERROR: Environment emulation nesting is not allowed](https://github.com/magento/magento2/search?p=1&q=ACP2E-1341&type=commits), unfortunately I can't seem to find a clean merge commit

**Comment by MTheProgrammer** [comment]
Still present in 2.4.5-p1

**Comment by peterjaap** [comment]
@kassner @hostep @simonmaass anyone aware of a workaround? We're running into this as well.

**Comment by simonmaass** [comment]
@peterjaap hey peter! unfortunately not... currently living with the logspam... it doesnt seem to have an inpact on the actual functionality...

**Comment by mvisd** [comment]
Same here. Any update on why this is closed? Is there a patch we can add to fix it temporarily?

**Comment by sebfie** [comment]
Hello,

Can you please provide us a patch or any visibility on a PR?

**Comment by ihor-sviziev** [comment]
@sivaschenko @sidolov, why this issue was closed? If it was fixed, please provide link to commit / pull request

**Comment by o-iegorov** [comment]
Internal team already fixed the issue, merge commit id: https://github.com/magento/magento2/commit/3e5be99a940ef572e1a99fee8b9258fda5be9ff4

**Comment by peterjaap** [comment]
Thanks!

Relevant changes are [here](https://github.com/magento/magento2/commit/3e5be99a940ef572e1a99fee8b9258fda5be9ff4#diff-38f96c71e6ed72eb48ddf775a12541b9114400e05092ed6e6c7fdb7da6a2db49), [here](https://github.com/magento/magento2/commit/3e5be99a940ef572e1a99fee8b9258fda5be9ff4#diff-b844099b5caffa3038cbdfbfc4fdc34a8a8cda702c35ad0679898df0c2ed6501) and [here](https://github.com/magento/magento2/commit/3e5be99a940ef572e1a99fee8b9258fda5be9ff4#diff-2137cb7dd9d88b5ae751ba10c28f5fb47bf38ecaaf9f94087f3e2c4729d062d2).

So the fix was moving the creation of the payment HTML block to outside the emulation since that info is not store specific.

Here's the patch with just those changes:

```
@package magento/module-sales
@link https://github.com/magento/magento2/issues/35603
@link https://github.com/magento/magento2/commit/3e5be99a940ef572e1a99fee8b9258fda5be9ff4
@level 5

From f1538d3d453e9de884d78eb91c1177562d0e6a25 Mon Sep 17 00:00:00 2001
From: Sarmistha Martha <glo23503@adobe.com>
Date: Fri, 11 Nov 2022 13:11:19 +0530
Subject: [PATCH 12/51] ACP2E-1341: [On-Premise] Merchant Informed Core Issue
 Magento 2.4.4 main.ERROR: Environment emulation nesting is not allowed

---
 .../Order/Email/Sender/CreditmemoSender.php   |  3 +-
 .../Order/Email/Sender/InvoiceSender.php      |  3 +-
 .../Order/Email/Sender/ShipmentSender.php     |  3 +-

diff --git a/app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php b/app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php
index 19dc627725138..22d5bc2b7a562 100644
--- a/app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php
+++ b/app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php
@@ -118,6 +118,7 @@ public function send(Creditmemo $creditmemo, $forceSyncMode = false)
 
         if (!$this->globalConfig->getValue('sales_email/general/async_sending') || $forceSyncMode) {
             $order = $creditmemo->getOrder();
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -126,7 +127,7 @@ public function send(Creditmemo $creditmemo, $forceSyncMode = false)
                 'creditmemo_id' => $creditmemo->getId(),
                 'comment' => $creditmemo->getCustomerNoteNotify() ? $creditmemo->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
diff --git a/app/code/Magento/Sales/Model/Order/Email/Sender/InvoiceSender.php b/app/code/Magento/Sales/Model/Order/Email/Sender/InvoiceSender.php
index 1ca2efef4d8f5..585da4d965840 100644
--- a/app/code/Magento/Sales/Model/Order/Email/Sender/InvoiceSender.php
+++ b/app/code/Magento/Sales/Model/Order/Email/Sender/InvoiceSender.php
@@ -126,6 +126,7 @@ public function send(Invoice $invoice, $forceSyncMode = false)
                 $order->setBaseTaxAmount((float) $invoice->getBaseTaxAmount());
                 $order->setBaseShippingAmount((float) $invoice->getBaseShippingAmount());
             }
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -134,7 +135,7 @@ public function send(Invoice $invoice, $forceSyncMode = false)
                 'invoice_id' => $invoice->getId(),
                 'comment' => $invoice->getCustomerNoteNotify() ? $invoice->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
diff --git a/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php b/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php
index ba6d65a40c653..78aaf1a696e9a 100644
--- a/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php
+++ b/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php
@@ -120,6 +120,7 @@ public function send(Shipment $shipment, $forceSyncMode = false)
         if (!$this->globalConfig->getValue('sales_email/general/async_sending') || $forceSyncMode) {
             $order = $shipment->getOrder();
             $this->identityContainer->setStore($order->getStore());
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -128,7 +129,7 @@ public function send(Shipment $shipment, $forceSyncMode = false)
                 'shipment_id' => $shipment->getId(),
                 'comment' => $shipment->getCustomerNoteNotify() ? $shipment->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
```

**Comment by ihor-sviziev** [comment]
Thank you so much! Now it's absolutely clear that it was already fixed and not just closed by not because of some glitch or whatever.

**Comment by mobweb** [comment]
And the patch below worked for me and I was able to patch the files in my vendor directory. Note that I had to change the paths of the files and add an empty newline at the very end of the patch.

Just copy and paste the contents below into a file named `emulation.patch` in your Magento base directory, then run `git apply emulation.patch` in that directory.

```
diff --git a/vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoSender.php b/vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoSender.php
index 19dc627725138..22d5bc2b7a562 100644
--- a/vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoSender.php
+++ b/vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoSender.php
@@ -118,6 +118,7 @@ public function send(Creditmemo $creditmemo, $forceSyncMode = false)
 
         if (!$this->globalConfig->getValue('sales_email/general/async_sending') || $forceSyncMode) {
             $order = $creditmemo->getOrder();
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -126,7 +127,7 @@ public function send(Creditmemo $creditmemo, $forceSyncMode = false)
                 'creditmemo_id' => $creditmemo->getId(),
                 'comment' => $creditmemo->getCustomerNoteNotify() ? $creditmemo->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
diff --git a/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php b/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php
index 1ca2efef4d8f5..585da4d965840 100644
--- a/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php
+++ b/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php
@@ -126,6 +126,7 @@ public function send(Invoice $invoice, $forceSyncMode = false)
                 $order->setBaseTaxAmount((float) $invoice->getBaseTaxAmount());
                 $order->setBaseShippingAmount((float) $invoice->getBaseShippingAmount());
             }
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -134,7 +135,7 @@ public function send(Invoice $invoice, $forceSyncMode = false)
                 'invoice_id' => $invoice->getId(),
                 'comment' => $invoice->getCustomerNoteNotify() ? $invoice->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
diff --git a/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php b/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
index ba6d65a40c653..78aaf1a696e9a 100644
--- a/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
+++ b/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
@@ -120,6 +120,7 @@ public function send(Shipment $shipment, $forceSyncMode = false)
         if (!$this->globalConfig->getValue('sales_email/general/async_sending') || $forceSyncMode) {
             $order = $shipment->getOrder();
             $this->identityContainer->setStore($order->getStore());
+            $paymentHTML = $this->getPaymentHtml($order);
             $this->appEmulation->startEnvironmentEmulation($order->getStoreId(), Area::AREA_FRONTEND, true);
             $transport = [
                 'order' => $order,
@@ -128,7 +129,7 @@ public function send(Shipment $shipment, $forceSyncMode = false)
                 'shipment_id' => $shipment->getId(),
                 'comment' => $shipment->getCustomerNoteNotify() ? $shipment->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
-                'payment_html' => $this->getPaymentHtml($order),
+                'payment_html' => $paymentHTML,
                 'store' => $order->getStore(),
                 'formattedShippingAddress' => $this->getFormattedShippingAddress($order),
                 'formattedBillingAddress' => $this->getFormattedBillingAddress($order),
                 
```

**Comment by peterjaap** [comment]
@mobweb I formatted the patch to use with [vaimo/composer-patches](https://github.com/vaimo/composer-patches), so you don't have to change the file paths in the patch. That's what `@level 5` at the top of the patch does.

**Comment by qaniel** [comment]
So, when this is hitting a release or a quality patch? or is it already out there? (couldn't find it :( )

**Comment by hostep** [comment]
@qaniel: it's not included in Magento 2.4.6 which got released today, so you'll have to wait until version 2.4.7 which will be released in the year 2024 ([I'm not joking](https://experienceleague.adobe.com/docs/commerce-operations/release/planning/schedule.html)).
No idea if Adobe is going to turn this into a quality patch, maybe consider creating a request for it: https://github.com/magento/quality-patches/issues

But if you need it urgently, you'd probably want to follow @peterjaap's [advise](https://github.com/magento/magento2/issues/35603#issuecomment-1419257643) and use a custom patch.

**Comment by Yuwei9291** [comment]
$order->getStoreId() ----> $order->createStoreId()   it will solve the problem.

**Comment by drinkingsouls** [comment]
@Yuwei9291 

> $order->getStoreId() ----> $order->createStoreId() it will solve the problem.

Where exactly did you add this?

**Comment by Yuwei9291** [comment]
> @Yuwei9291
> 
> > $order->getStoreId() ----> $order->createStoreId() it will solve the problem.
> 
> Where exactly did you add this?

Sorry that's my fault. this issue happened when I use an old email template. please ignore and sorry for the misunderstanding.

For my issues, the designer of the email template use objectManager to load product

$product = $objectManagerHere->get('Magento\Catalog\Model\Product')->load($productId);

and this row cause the **Environment emulation nesting** error. and once i checked and edited to 
$product = $objectManagerHere->create('Magento\Catalog\Model\Product')->load($productId);
the problem solved. 

I improved the code by using dependency injection by ChatGPT so I forget the detailed solution of the problem, just remember to change get to create. 

Sorry I'm a seller not a programmer, the problem happened in multiple store mode when I using jopin's email template and once I removed it, the problem does not recur. 

I hope my solution will tip off some users who have this error
