### ISSUE TITLE
Giftcard type product payment method not display 

### ISSUE THREAD

**Issue by tusharpatelborn** [magento/magento2#35611]
### Preconditions and environment

2.4.2-p1

### Steps to reproduce

    Clear all cookies or use incognito mode for the browser
    Add gift card product
    Go to checkout
    Adyen payments will not be present

### Expected result

Adyen payment method should be display on checkout page

### Actual result

Adyen payment method is not displayed on the checkout page

### Additional information

Here is the video : https://share.vidyard.com/watch/HNpEAnFCuHXvwQXZ1vWWSe?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @tusharpatelborn 
Thank you for reporting and collaboration. However, Adyen payment method is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
