### ISSUE TITLE
Puerto Rico is missing as an Enum in GraphQL

### ISSUE THREAD

**Issue by jesse-deboer** [magento/magento2#35610]
### Preconditions and environment

- Magento 2.4.4

### Steps to reproduce

1. Create a cart
2. Set Puerto Rico as country in the shipping address through GraphQL

### Expected result

Shipping address saves to the cart and adds Puerto Rico as country

### Actual result

GraphQL error: ```Expected a value of type "CountryCodeEnum" but received: PR```

### Additional information

Created a PR:
https://github.com/magento/magento2/pull/35609

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jesse-deboer** [comment]
> Hi @jesse-deboer , Thank you for reporting and collaboration. Current 2.4-develop version Magento behavior is: "Puerto Rico" is a State option under Country: "United States" Hence Puerto Rico cannot be set as Country in the shipping address through GraphQL ![image](https://user-images.githubusercontent.com/60198231/173814242-7ce4c5a2-c898-457b-80a2-3baebc2c4ec0.png) Kindly recheck the behavior on Magento 2.4-develop branch and provide ref docs/proofs that supports this to be a valid issue. Thank you

Sorry, but this is a very unsatisfying answer. You can set it as state, but also as a country. See screenshot:
![image](https://user-images.githubusercontent.com/14839421/173855749-fb49ee39-6e7a-4cf6-86f0-d99cfe995e11.png)

In GraphQL you can get it as a country, but you can not SET it as a country because the email was accidentally not added. Guam for example, which is also a overseas territory, is set as Enum.

Please see my [pull request](https://github.com/magento/magento2/pull/35609) which solves this problem. 

Right now customers that use a PWA/GraphQL checkout can not set their address with the country Puerto Rico which is making Puerto Ricans leave the checkout.

**Comment by engcom-November** [comment]
Hi @jesse-deboer ,
Thank you for your response. Verified the issue again on Magento 2.4-develop branch but still we are not able to set Puerto Rico as Country option but can able to set as State option only in both UI and GraphQl
![image](https://user-images.githubusercontent.com/60198231/174069576-6febfb4f-d8ef-4ff6-a21f-5291cdab9363.png)
![image](https://user-images.githubusercontent.com/60198231/174069670-e6cd7c86-0592-41fe-ba9e-9da725c26fcd.png)
![image](https://user-images.githubusercontent.com/60198231/174069731-e39b18d9-c50d-4d6c-92e3-5ba205ce0277.png)
![image](https://user-images.githubusercontent.com/60198231/174069784-b3f935b8-e37c-4a9d-8451-0c5c7e025d44.png)
Could not able to find "Puerto Rico" Country option in UI aswell. (Verified in Stores - Configuration, Store Information, Countries options, Shipping Origin settings etc)
But I see you were able to set Country as Puerto Rico. Kindly provide configuration settings where exactly this option is available.
Thank you.

**Comment by jesse-deboer** [comment]
@engcom-November, have you set Puerto Rico to be activated in 'Allow Countries' under Stores -> Configuration -> General -> Country options? 

![image](https://user-images.githubusercontent.com/14839421/174082208-2240fd2a-48db-4ed4-ab2a-3e8fe37ad5be.png)

**Comment by engcom-November** [comment]
Hi @jesse-deboer ,
"Puerto Rico" Country option cant be found in  'Allow Countries' under Stores -> Configuration -> General -> Country options as well in Magento 2.4-develop branch.
![image](https://user-images.githubusercontent.com/60198231/174288590-1fbd6e7e-4bd5-4e22-bd56-15b14da41b92.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and upcoming 2.4.x release. 
Thank you.

**Comment by jesse-deboer** [comment]
@engcom-November I think I have found the issue. I did a new installation of Magento 2.4.4, but used an old database and thought Magento still considered Puerto Rico as a country since we have some customers that have addresses with 'PR' as country code.

Should the `_isUSCountry` inside `app/code/Magento/Shipping/Model/Carrier/AbstractCarrierOnline.php` and other references to U.S. Possessions and Trust Territories be deprecated to make it more clear?

Should Guam also be considered to delete from the country list? This made me confused that Puerto Rico is not there, but Guam is.

I will add a patch to have "PR" as a valid Enum for my installation and close the MR for now. Thanks for the help so far!

**Comment by engcom-November** [comment]
Hi @jesse-deboer ,
Thank you for your response. Current Magento 2.4-develop behavior is, Gaum is consider as Country and _isUSCountry inside app/code/Magento/Shipping/Model/Carrier/AbstractCarrierOnline.php and other references to U.S. Possessions and Trust Territories were not deprecated. We are closing this issue as non issue. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
