### ISSUE TITLE
There has been an error processing your request SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_id' in 'field list'

### ISSUE THREAD

**Issue by tinkumadspark** [magento/magento2#3561]
There has been an error processing your request
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_id' in 'field list'
Any help would be appreciated.
Thanks.

**Comment by katmoon** [comment]
Hi @tinkumadspark 

Could you provide the steps that lead to the error?
Is there any additional information available in MySQL or PHP error logs? Seeing the full query would help. Also please check `magento/var/log` and `magento/var/report` folders.

You can also [set `developer` mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) to see more errors immediately.

Thanks,
Kateryna.

**Comment by duhon** [comment]
closed due to lack of response
