### ISSUE TITLE
Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

### ISSUE THREAD

**Issue by irabattiakshay** [magento/magento2#35628]
### Summary (*)

Could not validate a connection to Elasticsearch. No alive nodes found in your cluster.

Elasticsearch is active and running but unable to connect while running magento commands
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @irabattiakshay,

It could happen if the port is different from the default port of ElasticSearch. So I suggest you to use the below command to install the Magento with specific ES credentials as below:

```
bin/magento setup:install \
--base-url=http://localhost/magento2ee \
--db-host=localhost \
--db-name=magento \
--db-user=magento \
--db-password=magento \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1 \
--search-engine=elasticsearch7 \
**--elasticsearch-host=es-host.example.com \
--elasticsearch-port=9200 \
--elasticsearch-index-prefix=magento2 \
--elasticsearch-timeout=15**
```

Please refer the below link for more information:
https://devdocs.magento.com/guides/v2.4/install-gde/composer.html

Thanks

**Comment by engcom-Hotel** [comment]
Dear @irabattiakshay,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
