### ISSUE TITLE
Magento\Framework\Reflection\DataObjectProcessor missed keys for arrays

### ISSUE THREAD

**Issue by rkwadriga** [magento/magento2#35629]
### Preconditions and environment

- Magento version 2.4.*
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create a new consumer <consumer_name>
2. Put to the Magento\Framework\MessageQueue\PublisherInterface->publish() message like
[
   'data' => [
      'key_1' => 'Value 1',
      'key_2' => 'Value 2',
   ]
]
3. Run the consumer: bin/magento queue:consumers:start <consumer_name>
4. In the queue handler var dump the $message 

### Expected result

The message on step 4 must be:
[
   'data' => [
      'key_1' => 'Value 1',
      'key_2' => 'Value 2',
   ]
]

### Actual result

The message on step 4 is:
[
   'data' => [
      0 => 'Value 1',
      1 => 'Value 2',
   ]
]

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
For Confirming Issue someone from Maintainers or engcom squad 
should verify and try to reproduce this issue and confirm it is a bug that should be fixed

**Comment by engcom-Echo** [comment]
Hello @rkwadriga,
Thank you for reporting the issue .
Steps followed:

1. Installed rabbitmq 
2. https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/ this file there.i went through this file and checked while reproducing.

But to follow next procedures not got proper steps . So if you provide exact steps to reproducible we can check and try to reproduce the issue.

Thanks

**Comment by engcom-Echo** [comment]
Hello @rkwadriga,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
