### ISSUE TITLE
Backup error after disabling module in Web Setup Wizard

### ISSUE THREAD

**Issue by cod3gen** [magento/magento2#3562]
Hello!

Ive already taken a backup, but it seems that after disabling a module in Web Setup Wizard/Component Manager i did do another backup here, but now i have errors when browsing to System/Backups in Administration. Stack Trace:

`Item (Magento\Framework\DataObject) with the same id "1456564469_db" already exist
#0 /var/www/myweb/vendor/magento/framework/Data/Collection/Filesystem.php(324): Magento\Framework\Data\Collection->addItem(Object(Magento\Framework\DataObject))
#1 /var/www/myweb/vendor/magento/framework/Data/Collection.php(677): Magento\Framework\Data\Collection\Filesystem->loadData(false, false)
#2 /var/www/myweb/vendor/magento/framework/Data/Collection.php(286): Magento\Framework\Data\Collection->load()
#3 /var/www/myweb/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(51): Magento\Framework\Data\Collection->getSize()
#4 /var/www/myweb/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/altish...')
#5 /var/www/myweb/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), '/var/www/altish...', Array)
#6 /var/www/myweb/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/altish...')
#7 /var/www/myweb/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#8 /var/www/myweb/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#9 /var/www/myweb/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /var/www/myweb/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.syste...')
#11 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.syste...')
#12 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.syste...')
#13 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.syste...', true)
#14 /var/www/myweb/vendor/magento/framework/View/Element/AbstractBlock.php(497): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.syste...', true)
#15 /var/www/myweb/vendor/magento/module-backup/view/adminhtml/templates/backup/list.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid')
#16 /var/www/myweb/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/altish...')
#17 /var/www/myweb/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backup\Block\Adminhtml\Backup), '/var/www/altish...', Array)
#18 /var/www/myweb/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/altish...')
#19 /var/www/myweb/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#20 /var/www/myweb/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#21 /var/www/myweb/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 /var/www/myweb/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.syste...')
#23 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.syste...')
#24 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.syste...')
#25 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.syste...', true)
#26 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.syste...')
#27 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#28 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#29 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#30 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#31 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#32 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#33 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#34 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#35 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#36 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#37 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#38 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#39 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#40 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#41 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#42 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#43 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#44 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#45 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#46 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#47 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#48 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#49 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#50 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#51 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#52 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#53 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#54 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#55 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#56 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#57 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#58 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#59 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#60 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#61 /var/www/myweb/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#62 /var/www/myweb/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#63 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#64 /var/www/myweb/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#65 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#66 /var/www/myweb/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#67 /var/www/myweb/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#68 /var/www/myweb/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#69 /var/www/myweb/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#70 /var/www/myweb/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /var/www/myweb/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /var/www/myweb/vendor/magento/module-backup/Controller/Adminhtml/Index/Index.php(30): Magento\Framework\App\View->renderLayout()
#73 /var/www/myweb/var/generation/Magento/Backup/Controller/Adminhtml/Index/Index/Interceptor.php(24): Magento\Backup\Controller\Adminhtml\Index\Index->execute()
#74 /var/www/myweb/vendor/magento/framework/App/Action/Action.php(102): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->execute()
#75 /var/www/myweb/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#76 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#77 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#78 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#79 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backup\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#80 /var/www/myweb/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#81 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#82 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#83 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backup\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'designLoader')
#84 /var/www/myweb/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#85 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#86 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#87 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backup\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#88 /var/www/myweb/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#89 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#90 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#91 /var/www/myweb/var/generation/Magento/Backup/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#92 /var/www/myweb/vendor/magento/framework/App/FrontController.php(55): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#93 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#94 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#95 /var/www/myweb/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#96 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#97 /var/www/myweb/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#98 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#99 /var/www/myweb/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#100 /var/www/myweb/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#101 /var/www/myweb/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#102 /var/www/myweb/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#103 /var/www/myweb/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#104 {main}`

There are three files that relates to backup 1456564469:
1456564469_db.gz
1456564469_filesystem_code.tgz
1456564469_filesystem_media.tgz

EDIT:
System is Magento 2.0.2 Stable.
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.3 - 10.1.11-MariaDB

Any ideas?

Thanks,
Stian

**Comment by blizam** [comment]
I'm having this same issue

**Comment by mazhalai** [comment]
@cod3gen @blizam Thank you for reporting, we have created MAGETWO-52615 to investigate and fix.

**Comment by mazhalai** [comment]
@cod3gen @blizam how much is your setting for PHP `memory_limit`?

**Comment by blizam** [comment]
1024

I'm not sure what caused this issue initially, but it was the same first string (different ID) in the error here:

Item (Magento\Framework\DataObject) with the same id "1456564469_db" already exist

I don't have this issue presently as I've reinstalled from scratch since my first post here... I haven't tried taking many backups though either. If I have further issues I'll post back for sure.

**Comment by cod3gen** [comment]
@mazhalai memory limit for php was at 1280M on that installation

Stian

**Comment by arkadiych** [comment]
@cod3gen, could you define precisely your steps to reproduce the issue?

**Comment by wert2all** [comment]
Fixed
