### ISSUE TITLE
Magento 2.4.4 missing Tier prices on product page

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#35637]
### Preconditions and environment

Magento 2.4.4
PHP 8.1
Luma theme, but also missing on Porto

### Steps to reproduce

1, Add some tier pricing to a product
2, Flush the cache and expect to see the tier prices on the product page

### Expected result

Tier prices on the product page

### Actual result

Only the individual product price appears:
![Tier](https://user-images.githubusercontent.com/43850303/174324404-4a4f884b-b9c1-463f-b534-2c26025acd39.jpg)

![Luma](https://user-images.githubusercontent.com/43850303/174324364-5c642a36-36c1-402e-8e8d-4de489d1ed22.jpg)
s

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @devchris79 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. 
![image](https://user-images.githubusercontent.com/60198231/174624733-c6ec5f53-24cf-44e7-842a-ecb18bd364ff.png)
Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by devchris79** [comment]
@magento give me 2.4-develop instance

**Comment by devchris79** [comment]
Hi @engcom-November I can't reproduce in the 2.4-develop instance. Can you tell me what PHP version the instances use? 
I am on the recommended 8.1, but may be able to test another version tomorrow.

**Comment by devchris79** [comment]
@engcom-November I have this morning tried with PHP 7.4, re-index, clear cache and the tier prices appear. Switch to PHP 8.1, re-index, clear cache and they disappear.

**Comment by engcom-November** [comment]
Hi @devchris79 ,
Verified this issue on Magento 2.4-develop branch with PHP 8.1 version as well but still could not able to reproduce the issue. Prices are displayed as expected even after reindex / cache flush
![image](https://user-images.githubusercontent.com/60198231/174808100-1b6b4c85-7607-4956-9438-0561a4059e37.png)
