### ISSUE TITLE
Magento 2.4.4 not loading address fields on checkout form after upgrading from 2.3.2

### ISSUE THREAD

**Issue by hoshiray** [magento/magento2#35635]
### Preconditions and environment

- Magento version: 2.4.4

### Steps to reproduce

1. Add product to cart 
2. Go to checkout

### Expected result

All checkout fields should be visible to customer. 

### Actual result

Getting javascript errors

```
Failed to load the "Rokanthemes_OpCheckout/form/field" template requested by "checkout.steps.shipping-step.shippingAddress.shipping-address-fieldset.firstname".

Failed to load the "ui/group/group" template requested by "checkout.steps.shipping-step.shippingAddress.shipping-address-fieldset.street".
```

### Additional information

This also happens when using default Magento theme.
If I delete attribute `firstname` from `eav_attribute` table the error disappears. Maybe some values could be wrong in DB?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @o7-sol ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by jornwildenbeest** [comment]
Hi @o7-sol, 

Did you manage to fix this issue? I am having the same problem.

**Comment by grafikchaos** [comment]
@jornwildenbeest - I had a similar issue and the fix for me was to go through the custom HTML templates and make sure there were no self-closing tags (i.e., `<div/>`, `<span/>`, `<each/>`, `<render/>`, etc).

**Comment by jornwildenbeest** [comment]
@grafikchaos Thanks, this was indeed the solution.

**Comment by mobeen-tekhqs** [comment]
I am having the same problem.

**Comment by europrotection** [comment]
me too, the checkout module is very a big shit, so complicated for nothing ...
