### ISSUE TITLE
Use news appearances in Page Builder

### ISSUE THREAD

**Issue by cctorres** [magento/magento2#35632]
### Preconditions and environment 
Magento 2.4.4

### Steps to reproduce

1. Add new appeareance [https://devdocs.magento.com/page-builder/docs/content-types/extend/add-appearances.html](url) or use the example given by Magento in its repository.
2. Go to Content > Block > Edit With Page Builder.
3. Add a banner (or another element)
4. Select the custom appeareance in the config

### Expected result
Display the block with the custom appeareance.

### Actual result
The block is not displayed although it is still there.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
I have tried to reproduce the issue. Need your confirmation on below steps:

**Steps to reproduce:**
1. Create custom appearance by following this [page](https://github.com/magento-devdocs/pagebuilder-examples/blob/master/README.md) & [page](https://github.com/magento-devdocs/pagebuilder-examples/tree/master/BannerApp/Appearance).
2. Go to Content > Block > Edit With Page Builder.
3. Add a banner .
4. Select the custom appearance `Simple Poster` in the config.
5. Save.
6. On block creation page, see the preview section below `Edit with page builder`button.
7. Go to frontend and check the block created.

I am able to see the created block displayed in the front-end. Please find below screenshot for your reference:

**Screenshot:**
![image](https://user-images.githubusercontent.com/60198022/178502888-2a9bae80-a0e4-4b85-a905-bf353500cbea.png)

![image](https://user-images.githubusercontent.com/60198022/178496031-9f24ba50-5c37-4294-b102-ea7d830ac56e.png)

Kindly provide me more information to reproduce the issue.

**Comment by engcom-Lima** [comment]
Hi @cctorres  ,

We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.

Thank you
