### ISSUE TITLE
Error during compilation - how to disable compiler in magento 2.0

### ISSUE THREAD

**Issue by rohitprasad** [magento/magento2#3563]
After installing a theme 'porto', while compiling i received the below error
On contacting Porto, they say i need to disable the compiler

Please help, my site is down now, and i dont know how to rectify the issue
Any pointers to getting the site up will be greatly appreciated

`magento_user@ip-172-31-22-54:/var/www/html/magento2$ sudo php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 2 mins 418.2 MiBErrors during compilation:
        Smartwave\Filterproducts\Helper\Data
                Extra parameters passed to parent construct: $data. File: /var/www/html/magento2/app/code/Smartwave/Filterproducts/Helper/Data.php
        Smartwave\Filterproducts\Block\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
Total Errors Count: 5
Errors during compilation:
        Smartwave\Filterproducts\Helper\Data
                Extra parameters passed to parent construct: $data. File: /var/www/html/magento2/app/code/Smartwave/Filterproducts/Helper/Data.php
        Smartwave\Filterproducts\Block\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Megamenu\Block\Topmenu
                Incorrect dependency in class Smartwave\Megamenu\Block\Topmenu in /var/www/html/magento2/app/code/Smartwave/Megamenu/Block/Topmenu.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 6
Errors during compilation:
        Smartwave\Filterproducts\Helper\Data
                Extra parameters passed to parent construct: $data. File: /var/www/html/magento2/app/code/Smartwave/Filterproducts/Helper/Data.php
        Smartwave\Filterproducts\Block\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Megamenu\Block\Topmenu
                Incorrect dependency in class Smartwave\Megamenu\Block\Topmenu in /var/www/html/magento2/app/code/Smartwave/Megamenu/Block/Topmenu.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 6
Errors during compilation:
        Smartwave\Filterproducts\Helper\Data
                Extra parameters passed to parent construct: $data. File: /var/www/html/magento2/app/code/Smartwave/Filterproducts/Helper/Data.php
        Smartwave\Filterproducts\Block\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Megamenu\Block\Topmenu
                Incorrect dependency in class Smartwave\Megamenu\Block\Topmenu in /var/www/html/magento2/app/code/Smartwave/Megamenu/Block/Topmenu.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 6
Errors during compilation:
        Smartwave\Filterproducts\Helper\Data
                Extra parameters passed to parent construct: $data. File: /var/www/html/magento2/app/code/Smartwave/Filterproducts/Helper/Data.php
        Smartwave\Filterproducts\Block\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\FeaturedList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\FeaturedList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/FeaturedList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\Home\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\Home\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Filterproducts\Block\LatestList
                Incorrect dependency in class Smartwave\Filterproducts\Block\LatestList in /var/www/html/magento2/app/code/Smartwave/Filterproducts/Block/LatestList.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Catalog\Helper\Image already exists in context object
        Smartwave\Megamenu\Block\Topmenu
                Incorrect dependency in class Smartwave\Megamenu\Block\Topmenu in /var/www/html/magento2/app/code/Smartwave/Megamenu/Block/Topmenu.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 6
Interception cache generation... 7/7 [============================] 100% 2 mins 376.5 MiB
Generated code and dependency injection configuration successfully.`

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
