### ISSUE TITLE
Magento graphql doesn't provide enough detail to show pricing in frontend where dynamic pricing is set as no with discount price 

### ISSUE THREAD

**Issue by bashizee** [magento/magento2#35649]
### Step to reproduce
* create a bundle product in Magento. 
* Set Dynamic Price as "No"
* In advanced pricing, add special price with some percent in discount
* Add different options for bundle products with individual pricing for products in option.

### Data provide in graphql for pricing.
* price range for the main product
* price and price_type for the options
* price range for products inside option.

### Data requires to implement frontend.
since we have individual prices for options, 
price*range(minimum_price & maximum*price)   gives the total minimum price that is including discount with options

ex:
main product price = 20$
main product discount = 50%
price1 (option 1 required) = 10$
price2 (option 1 required) = 8$
price1 (option 2) = 5$
price2 (option 2) = 5$

minimum_price  =  14$ ((50% of 20$) <ins> (50% of 8$)) 
maximum_price =  17.5$ ((50% of 20$) </ins> (50% of 10$ <ins> (50% 0f 5$)))

to handle pricing in frontend we need to know  main product price which is not available in graphql.

in frontend if we choose 
option 1 </ins> option 2 = price should be (10$ <ins> 5$ </ins> 2.5$) mainprice with discount <ins> individual price with discount for option 1 </ins>  individual price with discount for option 2

Main price and main final price required handle this situations, which is not provide by magento

**Comment by engcom-Delta** [comment]
Hi @bashizee ,
Thank you for raising an issue and Kindly provide actual results, expected results ,graphql endpoints and screenshots if required.
Regards,

**Comment by bashizee** [comment]
Hi @engcom-Delta ,

Data send from magento doesn't have enough information. 
product query
```
{
  products(filter:{
    url_key:{
      eq:"test-bundle-dynamic"
    }
  }) {
    items {
      url_key
      sku
         price_range {
             minimum_price {
                    final_price {
                      value
                      currency
                    }
              
              discount {
                percent_off
                amount_off
              }
            
              regular_price {
                value
                currency
              }
              
                  }
          
                  maximum_price {
                    final_price {
                      value
                      currency
                    }
                    regular_price {
                      value
                      currency
                    }
                    discount {
                      percent_off
                      amount_off
                    }
                  }
        }
   ... on BundleProduct {
#     			bundle_main_price {
#             price
#             final_price
#           }
          dynamic_sku
          dynamic_price
          dynamic_weight
          price_view
          ship_bundle_items
          items {
            uid
            title
            required
            type
            position
            sku
            options {
              uid
              quantity
              position
              is_default
              price
              price_type
              can_change_quantity
              label
              product {
                uid
                name
                sku
                price_range {
                  minimum_price {
                    final_price {
                      value
                    }
                      regular_price {
                value
              }
                  }
                  maximum_price {
                    final_price {
                      value
                      currency
                    }
                      regular_price {
                value
                        currency
              }
                  }
                  
                }
                __typename
              }
            }
          }
  }
      
    }
  }
}
```

Query should contain extra fields, which can be  main_price & main_final_price.

```
{
  products(filter:{
    url_key:{
      eq:"test-bundle-dynamic"
    }
  }) {
    items {
     ... on BundleProduct {
   main_price // this should be the actual  main product price
    main_final_price // this should be the actual  main product final price
}
    }
}

```

**Comment by bashizee** [comment]
https://user-images.githubusercontent.com/44311317/175206512-55dffc6e-7339-4a42-a0fc-3c6c8f299752.mp4

you can see in the above video, that the main price of the bundle is 50$.  which is not available in graphql.

https://user-images.githubusercontent.com/44311317/175206672-a93c41e2-022b-48e1-b28a-d9d39f106bfa.mp4
here: 
for first dropdown
$50(main price)  +  $10(first dropdown price available in graphql )  = $60 
for first + second dropdown,
$50 + $10 + $5 = $65
we are able to get $10 and $5 from magento, but not the main price from magento.

**Comment by bashizee** [comment]
This is one quick solution, which helped me

```
type BundleProduct {
    bundle_main_price: BundleMainPrices @resolver(class: "\\vendor\\CatalogGraphQl\\Model\\Resolver\\BundlePrice")
}

type BundleMainPrices {
    price: Float
    final_price: Float
}

```
Resolver:
```
if (!isset($value['model'])) {
            throw new LocalizedException(__('"model" value should be specified'));
}
      /** @var Product $product */
      $product = $value['model'];
      return [
          "price" =>  $product->getPrice(),
          "final_price" => $product->getFinalPrice()
      ];
```

**Comment by bashizee** [comment]
@engcom-Delta  also we will need the discount percentage for the main price in front end, This also not available in the graphql.  This is required for calculation of discount for dynamic price
