### ISSUE TITLE
Async API does not log request details like IP address, Headers

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#35642]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Place request with async API
2. Check table `magento_operation`

### Expected result

1. In case of it's async REST api request, the system logs additional details of request like headers, ip address etc
2. Consumer can have access to operation related data via `\Magento\Framework\App\RequestInterface` or in the other way

### Actual result

1. The `magento_operation` has only request body and no additional metadata
2. The code `\Magento\AsynchronousOperations\Model\ResourceModel\Operation\OperationRepository::createByTopic` looks unfinished and has no extension points to extend $serializedData 
```
        $serializedData = [
            'entity_id'        => null,
            'entity_link'      => '',
            'meta_information' => $encodedMessage,
        ];
```
3. Processor: `\Magento\AsynchronousOperations\Model\OperationProcessor::process` uses only 'meta_information'

### Additional information

In case we want to grab additional data from headers like IP address, and we rely on REST api instead of custom controller we can do it in sync mode. But in async mode we have acces only to payload.
There are various ways for workaround of this case. But as system we can expectd that enqueued/async requests placed via REST API `/rest/all/async/V1/someMethod` still have access to additional data as if sync api called `/rest/all/V1/someMethod`.
e.g. we check if API call from certain IP is allowed based on config. (When external payment gateway sends us IPN notification).

### Release note

ASYNC Rest API consumers now support access to request metadata (IP, headers etc) for enqueued operations via `\Magento\Framework\App\RequestInterface` as if in SYNC requests.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @ilnytskyi ,
Thank you for logging an issue and kindly provide if you have any documentation that async API logs , additional details of request like headers & ip address.

Regards,

**Comment by engcom-Delta** [comment]
Hi @ilnytskyi ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
