### ISSUE TITLE
Advanced Reporting 404 message Magento 

### ISSUE THREAD

**Issue by hugo-lopez-tg** [magento/magento2#35647]
### Preconditions and environment

- Magento 2.3.6
- I have enable the adavanced report but not function, i get error 404 

### Steps to reproduce

Generate Advanced Reporting

### Expected result

Generate advanced report

### Actual result

Error 404

### Additional information

I have enable advanced report and the url run in https
![Captura de pantalla 2022-06-20 a la(s) 12 43 26](https://user-images.githubusercontent.com/78605474/174654903-7ec4f2c9-e5aa-437d-b322-920ffb70757b.png)
![Captura de pantalla 2022-06-20 a la(s) 12 44 20](https://user-images.githubusercontent.com/78605474/174654940-27e9caf6-f332-4e78-862f-02270d9f97d6.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by HenKun** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @hugo-lopez-tg ,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could able to reproduce the issue.please refer the screenshots. Hence issue confirmed.

![Screenshot (206)](https://user-images.githubusercontent.com/51681379/174830142-a44e47a1-89e1-4cb5-8aaf-2f5b88441e11.png). 

![Screenshot (207)](https://user-images.githubusercontent.com/51681379/174830754-875f6921-597e-45b5-b935-0032c77c77b7.png)

**Comment by engcom-Delta** [comment]
Hi @hugo-lopez-tg,
We have gone through the similar issue and found that we should follow below points.

1. Time should be set correctly. Be carefully with Timezones in your system and magento
2. CRON should be configured
3. synchronization could take several hours

in general, there are a couple of main rules:
1. Magento Store URL should be available from the internet(not only for localhost or some internal network)
2. Magento crontab is created and cron jobs are running on the installed server.
3. Wait for the first Data Transfer to Adv.Report system according to Sys.Conf settings


Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
