### ISSUE TITLE
How to increase maximum amount of order more than 100 million

### ISSUE THREAD

**Issue by kakeyang** [magento/magento2#3564]
Hi,

I'm looking for the solution related to title.
By default of Magento, it's only 100 million but it's too small digit for Vietnamese dong.
How can I modify maximum amount?

<What I did>
- Change type of some fields of these tables from decimal(12,4) to decimal(24,4).
  +cataloginventory_stock_item
  +cataloginventory_stock_status
  +catalog_product_entity_decimal
  +catalog_product_index_price
  +catalog_product_index_price_tmp
  +catalog_product_index_price_final_tmp
- Change constant definition
  +MAX_QTY_VALUE -> 99999999999.9999
  +MAXIMUM_AVAILABLE_NUMBER -> 99999999999

<Current status>
- Able to calculate total amount over 100 million and sub-total on Shipping Cart screen and values on order confirmation email are correct
- Sub-total on minicart and Summary on right column of Shipping Cart screen is still wrong and always show 100 million when total amount is over 100 million.

<What I want to know>
How can I show up correct sub-total and grand total on minicart and Summary on right column of Shipping Cart screen?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by kakeyang** [comment]
Yes, this is technical issue, I think.
Actually this is not a bug because 100 million is the default spec of Magento.

But in order to increase it, I need to modify the code of Magento itself because this can't be changed on admin panel or something.

I've already asked on the forum but nobody can answer this issue.
I need you help! Please do not close this ticket.

**Comment by veloraven** [comment]
@kakeyang is this issue still actual?

**Comment by kakeyang** [comment]
@veloraven I've not resolved this issue but I no longer need to resolve this issue for our product because we decided to use another framework. I hope this will be resolved for currencies like Vietnam dong.

**Comment by yaronish** [comment]
Hi, @kakeyang , it's not clear to me why do you propose to change fields in cataloginventory_stock_item  and cataloginventory_stock_status . 
These tables doesn't contain any currency related data.
Qty fields describes amount of product, not price.
Is 100 million products per stock not enough in some cases?
Thanks.

**Comment by choukalos** [comment]
Hi @kakeyang if you're concerned about supporting devalued currency you should be aware of a couple potential issues.

- We assume support for 32-bit systems; hence our current schema
- size of float is platform dependent, for 64bit float 14 digits of precision is fairly common; more and you're likely to not have precise #'s which would be an issue for a commerce platform
- If you're on a 64-bit system seems like you could do (14,4) which would allow you to support #'s as large as 10 billion without loosing precision.

You could update the schema post install to be decimal(14,4) for prices and that'd let you support 10B without impacting precision.  

What do you use for an accounting system or ERP? 

Thanks!
Chuck

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, and all technical details was provided to customer
