### ISSUE TITLE
Missing languages when installing / upgrading

### ISSUE THREAD

**Issue by rubenelshof** [magento/magento2#35655]
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug
PHP version 8.1.7

### Steps to reproduce

Installing Magento with the following commands:
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`

`bin/magento setup:install \
--base-url=http://magento-ce.test \
--db-host=: --db-name=m2clean244 --db-user=magento --db-password=magento --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=WZ9ejKDbKK58Wx --language=nl_NL --currency=EUR --timezone=Europe/Amsterdam --use-rewrites=1 --cleanup-database --backend-frontname=admin --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200 --elasticsearch-enable-auth=0 --use-secure=1 --use-secure-admin=1`

### Expected result

Magento 2 is correctly installed with the language set to Dutch.

### Actual result

I get the following error when clean installing Magento 2 with the language parameter set to nl_NL
```
Command option 'language': Invalid value. To see possible values, run command 'bin/magento info:language:list'.

In InstallCommand.php line 282:

  [InvalidArgumentException]
  Parameter validation failed


Exception trace:
  at ../setup/src/Magento/Setup/Console/Command/InstallCommand.php:282
 Magento\Setup\Console\Command\InstallCommand->initialize() at ../vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at ../vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at ../vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at ../vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at ../vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at ../bin/magento:23
```

When running the command `bin/magento info:language:list` I get the following list:
```
+--------------------------+-------+
| Language                 | Code  |
+--------------------------+-------+
| English (United Kingdom) | en_GB |
| English (United States)  | en_US |
+--------------------------+-------+
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @rubenelshof ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. Magento 2 is correctly installed with the language set to Dutch Language.

Please refer the screenshots:

![Screenshot (212)](https://user-images.githubusercontent.com/51681379/175477761-bd944566-bee3-41af-96cd-5733ac45b8d4.png)
![Screenshot (213)](https://user-images.githubusercontent.com/51681379/175477793-df42af1d-1be7-43fc-8e74-923c0688ac12.png)
![Screenshot (214)](https://user-images.githubusercontent.com/51681379/175477796-b8821980-84eb-45d6-8bf0-3e8210b04a0a.png)

**Comment by rubenelshof** [comment]
Thank you for checking.
It appears to be an issue with my environment.
I will investigate further.

**Comment by treck** [comment]
Had the same issue with an alpine3.16 Docker Image.

You need to check `php -a`
and then type `print_r(\ResourceBundle::getLocales(''));`
The Magento List depends on that php-Feature.

**Comment by rubenelshof** [comment]
I should have added the solution I found.

Starting with alpine 3.16 & up the ICU package (which php uses) was split up between just English & a full package with all languages.
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split

To fix the issue I installed the package `icu-data-full`

**Comment by shyameasternent** [comment]
> To fix the issue I installed the package `icu-data-full`

Thanks @rubenelshof  This helped me to add in docker install
RUN apk add icu-dev icu-libs icu-data-full

**Comment by nicolasbejean** [comment]
> I should have added the solution I found.
> 
> Starting with alpine 3.16 & up the ICU package (which php uses) was split up between just English & a full package with all languages. https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split
> 
> To fix the issue I installed the package `icu-data-full`

Thanks a lot!

**Comment by mesbah69** [comment]
> I should have added the solution I found.
> 
> Starting with alpine 3.16 & up the ICU package (which php uses) was split up between just English & a full package with all languages. https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split
> 
> To fix the issue I installed the package `icu-data-full`

Thank you very much @rubenelshof , this approach saved me a lots of time, I appreciate your great answer.
