### ISSUE TITLE
MessageList JS component: Error message appears, then hides, then re-appears in checkout.

### ISSUE THREAD

**Issue by sertlab** [magento/magento2#35651]
### Preconditions and environment

- Magento version 2.4.4 commerce edition

I Followed this tutorial to add a custom validation in the checkout.
https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-order-validation/

I Found out that the error message that is printed by `Magento_Ui/js/model/messageList` component component appears, then is hidden (with a ‘blind’ effect), then re-appears..

It looks like this function is getting triggered after MessageList component prints an error message in the checkout page.

### Steps to reproduce

1. Apply this tutorial https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-order-validation/
2. Go to checkout
3. Attempt to place an order
4. Observe the  validation error message

### Expected result

Validation error message shouldn't hide and then be back again.
It should only hide or stay there forever.
(In 2.3.7 it collapses after a few sec's and never comes back)

### Actual result

Validation error message appears, then hides, then it's back

See this video.
https://www.loom.com/share/4f0f2c0ef55d48a58ab92144704a4817

### Additional information

This is issue is reproduceable on 2.4.4.
Tested on 2.3.7 works fine.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kuafucode** [comment]
@engcom-Hotel I experienced this bug and may have a fix, can I claim this issue?

**Comment by kuafucode** [comment]
@magento add to contributors team

**Comment by kuafucode** [comment]
@magento please assign me the task if you can, thanks @engcom-Hotel

**Comment by engcom-Hotel** [comment]
Hello @kuafucode,

In order to assign this ticket to yourself. Please go through with the below link:

https://developer.adobe.com/commerce/contributor/guides/code-contributions/#assigning-an-issue

Thanks

**Comment by kuafucode** [comment]
@magento I am working on this

**Comment by kuafucode** [comment]
Sorry just noticed there was already a 'PR created' label, did I mess this up?

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5985 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-5985&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
