### ISSUE TITLE
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() 

### ISSUE THREAD

**Issue by ubedrajput** [magento/magento2#35657]
magento ver 2.4.4
magento2 upgrade 2.4.4 i m doing setup upgrade give this type of error
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /var/www/test.test/public_html/vendor/magento/framework/Reflection/TypeProcessor.php on line 550

**Comment by engcom-November** [comment]
Hi @ubedrajput ,
Thank you for reporting and collaboration. Verified the issue by installing 2.4.4 Project-community-edition with PHP 8.1 version and performed setup:upgrade but could not able to reproduce the issue. Kindly recheck the issue as per [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and elaborate configuration details / any 3rd party extensions / modules enabled is causing this issue.
Thank you.

**Comment by hostep** [comment]
Does the [following comment](https://github.com/magento/magento2/issues/22773#issuecomment-1111790015) help in finding a solution @ubedrajput?

**Comment by engcom-November** [comment]
Hi @ubedrajput ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue f you are still facing any issues.
Thank you.

**Comment by elizad** [comment]
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName(): Argument #2 ($typeName) must be of type string, null given, called in /var/www/html/m/vendor/magento/framework/Reflection/TypeProcessor.php on line 550  when updrading to M.4.5 FRM M4.3

**Comment by Kerolusnasser** [comment]
One of your custom modules is not Magento 2.4.* compatible.
you should update your custom modules to the updated version , it solved my issue

**Comment by davidduong90** [comment]
@Kerolusnasser Thank you! In my case, I need to update plugin Magefan_Blog

**Comment by sanaeefar-saeed** [comment]
it's all about doc block you can read more about it here:
**best practice**
https://magento.stackexchange.com/questions/354838/error-when-upgrading-to-magento-to-2-4-4
 **cowboy way!:**
  https://stackoverflow.com/questions/57720302/upgrade-magento-2-2-2-3-2-type-error-occurred-when-creating-object-magento
