### ISSUE TITLE
Item actions (Edit, Remove) do not appear in cart for products added through Grouped products

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#3565]
If I have a Grouped product comprised of simple products, when I add one of the products to the cart, and then go to the Cart page, I'm unable to see the item actions such as Edit or Remove. I do however see the Edit and Remove actions in the mini cart.

If I have a Grouped product comprised of simple products that are part of a configured product, I'm unable to see the actions in either the cart page or mini cart. I'm assuming this is because visibility for simple products part of a configured product are set to not visible. When I change visibility to catalog, search, or both, item actions are then visible in the mini cart, although still not visible on the cart page.

**Comment by ishakhsuvarov** [comment]
@samleeiii Thank you for reporting this issue. We have tried but could not reproduce it with the information available. Please provide more detailed steps to reproduce and Magento version you are using.

**Comment by zerobrapsgiven** [comment]
Hi Levgen, I'm on ver 2.0.2. I'm running it locally on my machine with MAMP Pro ver 3.5 on OSX 10.11.3. Running PHP 7, and MySQL 5.6.25. I'll take detailed screenshots later tonight documenting the workflow to reproduce the bug. Thanks!

**Comment by zerobrapsgiven** [comment]
Weird I couldn't repeat the issue, sorry for the inconvenience!
