### ISSUE TITLE
Deleting an item from mini cart doesn't update cart page

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#3566]
When you're on the cart page and you remove an item from the cart using the mini cart, it doesn't update the cart page. You have to refresh the cart page to get the correct list of items in your cart.

**Comment by ishakhsuvarov** [comment]
@samleeiii Thank you for reporting this issue.
We already have a similar item in our backlog which is scheduled for the future releases. Internal ticket `MAGETWO-36985`.

**Comment by henk-hypershop** [comment]
What is the status on this? Almost issued a year ago and still buggy in 2.1.5!!!

**Comment by m2developer** [comment]
Still no updates ?

**Comment by henk-hypershop** [comment]
It seems that @magento-team does not address this issue. Lots and lots of issues in M2, but almost non are fixed in the future releases. Already in 2.1.7, still buggy. Issues are only growing. For now we have simply deleted the minicart from the cart page to prevent this issue.

**Comment by magento-engcom-team** [comment]
@samleeiii, thank you for your report.
We've created internal ticket(s) MAGETWO-36985 to track progress on the issue.

**Comment by wendydek** [comment]
The find function in the _removeItemAfter method doesn't work in IE. You can make a mixin to override it in your own theme:

```
define([
    'jquery',
    'Magento_Customer/js/customer-data',
], function ($,customerData) {
    return function(originalWidget) {

        $.widget('mage.sidebar', $.mage.sidebar, {

            _removeItemAfter: function (elem) {
                var productData = customerData.get('cart')().items.filter(function (item) {
                    if(Number(elem.data('cart-item')) === Number(item['item_id'])) {
                        return true;
                    }
                });

                $(document).trigger('ajax:removeFromCart', productData[0]['product_sku']);
            },
        });

        return $.mage.sidebar;
    }
});
```

in the requirejs-config you can add 

```
var config = {
    "config": {
        "mixins": {
            "Magento_Checkout/js/sidebar": {
                'Magento_Checkout/js/sidebar-mixin': true
            }
        }
    }
};
```

hope this helps!

**Comment by laurentlepee** [comment]
Still buggy in 2.2.3, wendydek solution work's for me.

**Comment by magento-engcom-team** [comment]
Hi @samleeiii @laurentlepee 
This issue is caused by the same larger issue described in the scope of #3625 
 We are closing this ticket now. Please continue tracking under that reference.

Thanks
