### ISSUE TITLE
Wrong price calculation for bundle products

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#35665]
### Preconditions and environment

- 2.4.1

### Steps to reproduce

Create a simple product with price 6.75

Create a bundle product which is consisted of 18 pieces of the simple product and add a price of 95% to the bundle product. 

The final price that magento calculates is 115.38 which is wrong

### Expected result

The price rounded is 115.43 (115.425)

### Actual result

The price is 115.38

### Additional information

The bug is coming due to order of calculation. 

Magento is doing it like this 

`round((price * bundle price %)) * pieces `

The correct calculation would be 

`round(price* pieces * bundle price %)`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ioweb-gr ,
We are getting Actual results...We are getting  price is 115.38 as well as the issue is confirmed.

Here i attached the Screenshot for reference.
![Screenshot from 2022-06-23 15-30-15](https://user-images.githubusercontent.com/60198592/175291054-f879d022-638a-4a9d-8e6a-45aa12112f95.png)

**Comment by aasim110** [comment]
@magento I'm working on this

**Comment by aasim110** [comment]
@magento I'm working on this
