### ISSUE TITLE
Magento 2.4.4 - The message was tampered with in transit (Customer Reset Password and customer grid not loading issue fixed) 

### ISSUE THREAD

**Issue by Thirumalbalu** [magento/magento2#35663]
https://github.com/magento/magento2/blob/28c1f28a2552de69158b40d1eaf84e45430c16f9/app/code/Magento/Customer/Model/ResourceModel/Customer.php#L245

Magento 2.4.4 / PHP 8.1

Customer Reset Password and customer grid not loading issue fixed.
If we use 
$customer->setRpToken($this->encryptor->encrypt($rpToken));
 instead of this 
$customer->setRpToken($this->encryptor->decrypt($rpToken));
It's working fine.

**Comment by Thirumalbalu** [comment]
vanilla magento instance working fine.

I think i have issue in my custom modules.
let me check from our side.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @Thirumalbalu ,
We need following information to proceed further Steps...

Summary of the issue
Information on your environment
Steps to reproduce
Expected and actual results

Thanks!!!

**Comment by Thirumalbalu** [comment]
Vanilla instance working fine and i have issue in our custom modules.

Thanks!
