### ISSUE TITLE
DI configuration extend logic

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#35664]
### Summary (*)

`\Magento\Framework\ObjectManager\Config\Compiled::extent` replace same key elements from previous configuration by next loaded configuration. For example `global` configuration will be replaced by `frontend`.
But in fact it means that configuration from one module could be lose due to another area configuration from another module.

### Examples (*)

ModuleA describe arguments for class A at `global` area di.xml
ModuleB describe another arguments for class A at `frontent` area.
ModuleB loaded after ModuleA.

As result arguments passed at ModuleA `di.xml` will be lose.

### Proposed solution

Merge same key elements with global area on di compilation step

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

Thanks for the report and collaboration!

I think this is expected behavior. I have gone through the documentation related to `di.xml` [here](https://developer.adobe.com/commerce/php/development/build/dependency-injection-file/). The below is mentioned on the page:

> Arguments on different stages—Configuration arguments are merged when they are declared on the same stage (Initial, Global, or Area-Specifc). If you declare new arguments on a higher stage, like Area-Specific, the arguments declared on the higher stage will replace the existing ones.

Still, please let us know your use case, and where you are facing any issues with this behavior. 

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Den4ik,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
