### ISSUE TITLE
Unable to add custom view model to a core block

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#35661]
### Summary (*)
I want to add custom functionality to the core block `Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist`  which is referenced as `view.addto.wishlist` in the layout file `catalog_product_view.xml`

Since that block extends `Magento\Framework\View\Element\Template` (not directly though) I thought it would by smart to reference `view.addto.wishlist` in my own layout and add my custom view_model. But that does not work:

```
<referenceBlock name="view.addto.wishlist">
	<arguments>
		<argument name="view_model" xsi:type="object">Vendor\Module\ViewModel\Wishlist</argument>
	</arguments>
</referenceBlock>
```

I like the idea of injecting view models but it falls flat on the nose if I can't do it to any core model (it seems). Instead I had to go back and use a helper again which is hated by so many and yet it is so much easier to use.

**EDIT:** I can add a view model to `Magento\Wishlist\Block\Link`. Why not to the other? What is the difference?

**Comment by engcom-Lima** [comment]
Hi @OvalMedia ,

Thank you for reporting the issue.

I tried to reproduce the issue on Magento 2.4-develop version but my ViewModel worked as expected for Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist Block. 

I added ViewModel in custom module referencing as view.addto.wishlist in the layout file catalog_product_view.xml, it worked for me. Below are the attached screenshot for same:
**Screenshots:**
<img width="1010" alt="Screenshot 1" src="https://user-images.githubusercontent.com/60198022/179765303-44da5618-0f94-4a86-88e7-8428da3038aa.png">

<img width="818" alt="Screenshot 2" src="https://user-images.githubusercontent.com/60198022/179765506-492c3760-e951-4531-b3cd-effdc5569ca0.png">

<img width="726" alt="Screenshot 3" src="https://user-images.githubusercontent.com/60198022/179765523-22936535-905d-4dec-81a8-e5b0865bf191.png">

Can you please check again and let me know if you did anything differently or which version of Magento are you facing this issue ?

**Comment by engcom-Lima** [comment]
Hi @OvalMedia ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
