### ISSUE TITLE
Backwards compatability PHP 8.1 Magento 2.4.4 Patches

### ISSUE THREAD

**Issue by WebKenth** [magento/magento2#35666]
### Summary (*)
Greetings! i am developer from a company which focuses on Magento shops, we have al ot of customers and have slowly begun updating them all to 2.4.4 with php8.1 and have found some interesting points which could become a baseline for introducing a new requirement on accepting Pull Requests. ( mainly defensive programming )

Usually updating/upgrading a magento platform is straight forward and the only real issues we have had in the past was third party modules. This time however we have found numerous core files which could have had a better test flow to ensure they would either work, or propagate a nice error message which could help with the upgrade.

This is not Critique, merely a point to help smoothe the transition from upgrade to upgrade without much trouble

**Disclaimer** the following examples were not tested on a clean magento 2.4.4 instance, they were merely a result of a few clients upgrade. Most of the issues are probably because of third party requirements or bad data. While this isn't the responsibility of the Magento team to fix/resolve such issues, working on defensive programming going forward would greatly improve the upgrade process.

### Examples (*)
In these examples i will provide a hotfix and show some of the issues these core files create

This filename resolver function has only typehinted in the docblock that it requires a string, however since anything can technically be passed through it (including null) the function can cause a fatal error due to the fact that `pathinfo` since php8.1 requires a value and cannot accept null values.

While the patch is not the best way to resolve the issue, it does allow the function to continue to work without throwing an exception due to invalid arguments

https://github.dev/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/View/Asset/PreProcessor/FileNameResolver.php#L41

```patch
@package magento/framework

--- View/Asset/PreProcessor/FileNameResolver.php
+++ View/Asset/PreProcessor/FileNameResolver.php
@@ -41,7 +41,7 @@
     public function resolve($fileName)
     {
         $compiledFile = $fileName;
-        $extension = pathinfo($fileName, PATHINFO_EXTENSION);
+        $extension = pathinfo($fileName ?? '', PATHINFO_EXTENSION);
         foreach ($this->alternativeSources as $name => $alternative) {
             if ($alternative->isExtensionSupported($extension)
                 && strpos(basename($fileName), '_') !== 0
```

---

The Reflection TypeProcessor has the same issue, in this case however it is down to a third party module not registering a propper type, in previous magento versions it is accepted to omit the value, however since 2.4.4 the value is now required and fatally breaks here:

Again the function accepts an empty string, but cannot accept a null value.
The funny thing is that just above the `$type` is checked for a string of `'null'`, but never `null` which is the inherently the same LogicException
```php 
        if ($type === 'null') {
            throw new \LogicException(
                sprintf(
                    '@param annotation is incorrect for the parameter "%s" in the method "%s:%s".'
                    . ' First declared type should not be null. E.g. string|null',
                    $param->getName(),
                    $param->getDeclaringClass()->getName(),
                    $param->getDeclaringFunction()->name
                )
            );
        }
```

https://github.dev/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/Reflection/TypeProcessor.php#L550 
```patch
--- Reflection/TypeProcessor.php
+++ Reflection/TypeProcessor.php
@@ -547,7 +547,7 @@
             return strpos($paramType, '[]') !== false ? $paramType : "{$paramType}[]";
         }
 
-        return $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $type);
+        return $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $type ?? '');
     }
 
     /**
```

---

This one is a funny one, and i have no clue why a timer is null
If `$timerIds[$j]` is null the entire profiler just breaks because it is passed into a `strpos` function

A simple defensive programming approach and the issue is resolved, the framework continues to work as expected and provides propper profiling stats

https://github.dev/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/Profiler/Driver/Standard/Stat.php#L210
```patch
--- Profiler/Driver/Standard/Stat.php
+++ Profiler/Driver/Standard/Stat.php
@@ -210,6 +210,8 @@
             while (strpos($timerId, $prevTimerId . Profiler::NESTING_SEPARATOR) !== 0) {
                 /* Add to result all timers nested in the previous timer */
                 for ($j = $i + 1; $j < count($timerIds); $j++) {
+                    if($timerIds[$j] === null)
+                        continue;
                     if (strpos($timerIds[$j], $prevTimerId . Profiler::NESTING_SEPARATOR) === 0) {
                         $result[] = $timerIds[$j];
                         /* Mark timer as already added */

```

---

This one is a straight up non compliant way to throw a valid exception
Since 2.4.4 has deprecated system integration tokens the `Magento_TwoFactorAuth` module is overriding a core SOAP api function `integrationAdminTokenServiceV1`. 

This service is responsible for returning a token which can be used in api calls going forward, it simply requires a username/password. However `Magento_TwoFactorAuth` module replaces and renames the endpoint causing the entire thing to break. Since it was notified and a deprecation notice was sent out, it is not Magento's responsibility to resolve this, however a message could have been provided in the logs or something.

The issue: a third party service is using SOAP api services to communicate with Magento. It uses the `integrationAdminTokenServiceV1` to get a token. This endpoint no longer exists and should throw a propper `RuntimeException`

The method responsible for this exception however, is not php8.1 compliant since the `__()` (Phrase) does not automatically resolve to a string when given as an argument.

You can validate that this is the case by visiting `https://<magento.shop>/soap/?wsdl_list=integrationAdminTokenServiceV1`

Expectation: an exception of an invalid endpoint/service requested
Reality: `Invalid Argument Exception` `String` expected where `Phrase` was given 

https://github.dev/magento/magento2/blob/2.4.4/app/code/Magento/Webapi/Model/ServiceMetadata.php#L200

```patch
@package magento/module-webapi

--- Model/ServiceMetadata.php
+++ Model/ServiceMetadata.php
@@ -197,7 +197,7 @@
     {
         $servicesConfig = $this->getServicesConfig();
         if (!isset($servicesConfig[$serviceName]) || !is_array($servicesConfig[$serviceName])) {
-            throw new \RuntimeException(__('Requested service is not available: "%1"', $serviceName));
+            throw new \RuntimeException((string)__('Requested service is not available: "%1"', $serviceName));
         }
         return $servicesConfig[$serviceName];
     }

```

---

Here's a really funny one. If an Order does not have a street, the `getStreet` method on an Order's Address simply breaks
This is simply amusing and i have no idea why the order's address's street would be null, might have been a third party module updating the address without propper validation.

But since the method passes the data directly into an `explode` method it just throws an invalid argument exception.

https://github.dev/magento/magento2/blob/2.4.4/app/code/Magento/Sales/Model/Order/Address.php#L238 
```patch
@package magento/module-sales

--- Model/Order/Address.php
+++ Model/Order/Address.php
@@ -237,10 +237,11 @@
      */
     public function getStreet()
     {
-        if (is_array($this->getData(OrderAddressInterface::STREET))) {
-            return $this->getData(OrderAddressInterface::STREET);
+        $street = $this->getData(OrderAddressInterface::STREET) ?? '';
+        if (is_array($street)) {
+            return $street;
         }
-        return explode(PHP_EOL, $this->getData(OrderAddressInterface::STREET));
+        return explode(PHP_EOL, $street);
     }
 
     /**

```

---

It is possible in the `setOptions` method to pass an `$options` argument with a `precision` of null
The [\Numberformatter](https://www.php.net/manual/en/class.numberformatter.php) class expects a value and cannot accept a null value

https://github.dev/magento/magento2/blob/2.4.4/app/code/Magento/Directory/Model/Currency.php#L497 
```patch
@package magento/module-directory

--- Model/Currency.php
+++ Model/Currency.php
@@ -494,7 +494,7 @@
             $this->numberFormatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
         }
         if (array_key_exists('precision', $options)) {
-            $this->numberFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, $options['precision']);
+            $this->numberFormatter->setAttribute(\NumberFormatter::FRACTION_DIGITS, $options['precision'] ?? 0);
         }
     }
 

```

### Proposed solution
My hotfixes in these patches are barebone at best and are not at all what i would call future proof. But it provides a nice context for a discussion about how to program defensively. Most of these patches are in very very old places of the framework and i wouldn't expect newer functionality to handle accepted arguments as badly as this.

The main cause of all of these issues are from core PHP updated functionality, in the goal of becoming more strongly typed.

When relying on third party vendors to update their code before you can update to a newer magento version we risk falling behind. I would hope that going forward better exception handling and exception handling with good descriptive messages could be the norm.

It would be impossible to expect the Magento Team to resolve any and all issues without having the user story required to replicate the issue. Testing on a pure installation of Magento is a nice sentiment, however it wouldn't catch outlying issues like bad data. Issues like an OrderAddress not having a valid Street entry is something that could have been expected to be passed into the DataModel since it does not validate any input and it is strictly not required to have a value. but since the function just passes the data to a core php function that now breaks due to type constraints is in my mind not an acceptable solution.

A Pure Magento installation would not catch old data migrated to a new installation.

Thank you for reading, if this was an annoying issue, close it ;) if you liked what you read, thank you for your time

If any of these patches could help resolve an issue you might happen to have, your welcome :) 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @WebKenth ,

Thank you for raising this issue.

I have gone through your explanation of some of the core Magento functionality issues which you have raised and found that these part of code can become better in terms of exception handling.

Regarding Street Address validation, Street Address is mandatory while checking out with shipping details so that is why errors don’t come in Magento Vanilla instance. As you only said, it could be work of Third Party modules.

The one which is given on file app/code/Magento/Webapi/Model/ServiceMetadata.php seems to be genuine issue which needs to be corrected.

That is why I am confirming the issue for further analysis by our core team who can check each issue separately also validate your patches.

Thanks

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5992 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-5992&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by engcom-Hotel** [comment]
Hello,

Currently the issue has been fixed for `app/code/Magento/Webapi/Model/ServiceMetadata.php` file. For the remaining files, there is a new JIRA created: https://jira.corp.adobe.com/browse/AC-7036

We will keep you posted here with more updates.

Thanks
