### ISSUE TITLE
Royal Mail click and drop integration no longer works with 2.4.4

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#35672]
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1

### Steps to reproduce

Follow [documented process](https://www.royalmail.com/sites/default/files/Integrating-your-Magento-V2-store-with-Click-and-Drop-Jan-19.pdf) from Royal Mail

### Expected result

Successful connection as we have achieved in Magento v2.4.3 and below 

### Actual result

Browser Windows opens for login and the presents the error:

![image](https://user-images.githubusercontent.com/43850303/175492637-f8a50842-9865-4016-baf1-b12ee51b8d55.png)

### Additional information

I did notice that after upgrading to 2.4.4 from 2.4.3 the Consumer Key and Consumer Secret values looked corrupt with strange symbols from the extended character set. I deleted the integration instance and started over and the values are now in the normal ASCII set.
This may be coincidental, but it made me wonder if there was an encoding issue.

Our server provider has also tried to get the integration working without success and has checked there is no server blocks stopping communications. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
Thanks Graham, that's worked a treat. I will try to contact Royal Mail on Monday.

**Comment by devchris79** [comment]
Hi Graham,

I rang Royal Mail Click and drop, they were well aware of the issue and said they are working towards a fix.
There is a [release information here](https://help.parcel.royalmail.com/hc/en-gb/articles/115004554734-Latest-release-information-Online-Business-Account-customers-) that they say will contain the fix notification when ready.

**Comment by devchris79** [comment]
@gwharton I presule Royal mail have added the SHA256 support in there latest update:

![image](https://user-images.githubusercontent.com/43850303/187388171-6fef78b9-93c3-4553-8ce4-e42153a9c6da.png)

**Comment by devchris79** [comment]
@gwharton We have noticed that the upload delivery confirmation seems to have stopped working so the tracking details/shipped status are not automatically transferred. Is this also affecting your installation? If so I will raise a query with them.

**Comment by gwharton** [comment]
I have delivery confirmation upload turned off and I manually ship items in magento as part of our workflow.

**Comment by devchris79** [comment]
Thanks Graham

**Comment by kestraly** [comment]
Just an FYI for others. 

I had to delete the integration and then create a new one. 

Click ReAuth or Activate made no difference, only delete and add integration worked.

**Comment by devchris79** [comment]
All the functionality now works as Royal Mail have added support for SHA256 and fixed the bug with tracking details/shipped status.

**Comment by kestraly** [comment]
It does indeed, but had to delete the existing connector and add it again because it kept coming up with the error "Couldn't connect"
