### ISSUE TITLE
REST API GET order request fails when Accept: application/xml for multibyte content

### ISSUE THREAD

**Issue by ni-bschmitt** [magento/magento2#35675]
### Preconditions and environment

Magento version: 2.4.3-p1

### Steps to reproduce

Create an order with an address containing multibyte characters (e.g. Trần Hưng Đạo, Hiệp Phú, Thành phố Hồ Chí Minh, Vietnam). Request the order via REST with `Accept: application/xml`, that will result in `An error has happened during application run. See exception log for details.`

`Accept: application/json` works. 

### Expected result

Valid XML is returned with encoded characters. 

### Actual result

An error has happened during application run. See exception log for details.

### Additional information

```message:[2022-06-24 10:33:14] report.CRITICAL: Report ID: webapi-62b592eab19cf; Message: Warning: DOMDocument::saveXML(): xmlEscapeEntities : char out of range in /app/vendor/magento/framework/Webapi/Rest/Response/Renderer/Xml.php on line 67 {"exception":"[object] (Exception(code: 0): Report ID: webapi-62b592eab19cf; Message: Warning: DOMDocument::saveXML(): xmlEscapeEntities : char out of range in /app/vendor/magento/framework/Webapi/Rest/Response/Renderer/Xml.php on line 67 at /app/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Warning: DOMDocument::saveXML(): xmlEscapeEntities : char out of range in /app/vendor/magento/framework/Webapi/Rest/Response/Renderer/Xml.php on line 67 at /app/vendor/magento/framework/App/ErrorHandler.php:61)"} []```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ni-bschmitt** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.3 release

**Comment by ni-bschmitt** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Hotel** [comment]
Hello @ni-bschmitt,

Thanks for your contribution and collaboration.

I tried to test the REST API GET order request fails when Accept: application/xml for multibyte content and below are my observation:

    1. Created an order with an address containing multibyte characters (Example: Trần Hưng Đạo, Hiệp Phú, Thành phố Hồ Chí Minh, Vietnam)

```
    Payload:
    {
    "paymentMethod": {
        "method": "checkmo"
    },
    "billing_address": {
        "email": "jdoe2@example.com",
        "region": "Hiệp Phú",
        "region_id": 45,
        "region_code": "Trần Hưng Đạo",
        "country_id": "VN",
        "street": [
            "Thành phố Hồ Chí Minh, Vietnam"
        ],
        "postcode": "Quan 12",
        "city": "Vietnam",
        "telephone": "512-555-1111",
        "firstname": "Jane",
        "lastname": "Doe"
    }
}
```
3. Requested the order via REST with `Accept: application/xml` (I am getting the response)
```
    <?xml version="1.0"?>
    <response>8</response>
```
4. Reviewed the order via REST with `Accept: application/xml` (I am getting the response)

Please refer to the screenshots for reference:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/51681618/175921470-812ee570-8b67-4611-9d9a-bac5ac67c645.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/51681618/175921537-6b3b522c-2581-496e-aa76-30a0fc00ffa7.png">

Please let us know if we have missed anything.

Thanks

**Comment by nuzil** [comment]
@magento give me test instance

**Comment by nuzil** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @ni-bschmitt 

Since there is no update from 14 days. Hence, closing the issue.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!
