### ISSUE TITLE
Magento's `setup:db:status` fails with MySQL 8.0.29

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#35671]
### Preconditions and environment

- Magento 2.4.4
- MySQL 8.0.29 and higher --- Server version: 8.0.29-0ubuntu0.20.04.3 (Ubuntu)

### Steps to reproduce

1. Set up Magento 2.4.4 following the requirements (https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
2. Execute `setup:upgrade`
3. Execute `setup:db:status`

### Expected result

Magento should report that the Database is up-to-date

### Actual result

1. `bin/magento setup:db:status`
> Declarative Schema is not up to date
> Run 'setup:upgrade' to update your DB schema and data.
2. `bin/magento setup:upgrade`
3. `bin/magento setup:db:status`
> Declarative Schema is not up to date
> Run 'setup:upgrade' to update your DB schema and data.
4. `bin/magento setup:db-schema:upgrade`
5. `bin/magento setup:db:status`
> Declarative Schema is not up to date
> Run 'setup:upgrade' to update your DB schema and data.

### Additional information

Issue is caused by charset comparison.

> Beginning with MySQL 8.0.28, utf8mb3 is also displayed in place of utf8 in columns of Information Schema tables, and in the output of SQL SHOW statements.

> Prior to MySQL 8.0.29, instances of utf8mb3 in statements were converted to utf8. In MySQL 8.0.30 and later, the reverse is true, so that in statements such as SHOW CREATE TABLE or SELECT CHARACTER_SET_NAME FROM INFORMATION_SCHEMA.COLUMNS or SELECT COLLATION_NAME FROM INFORMATION_SCHEMA.COLUMNS, users see the character set or collation name prefixed with utf8mb3 or utf8mb3_.

![image](https://user-images.githubusercontent.com/1639941/175430487-224b530c-9aef-48ce-9a45-75aa169e8263.png)

The default table charset is defined in `\Magento\Framework\Setup\Declaration\Schema\Dto\Factories\Table::create`
![image](https://user-images.githubusercontent.com/1639941/175430609-93bd18cc-9ec7-4bc6-b798-7b37af1b1387.png)

Our internal workaround is a plugin which overrides default MySQL charset if no other provided:
```php
<?php
declare(strict_types=1);

namespace SwiftOtter\MysqlCharsetFix\Plugin;

use Magento\Framework\Setup\Declaration\Schema\Dto\Factories\Table;

class OverrideDefaultCharsetPlugin
{
    private const DEFAULT_CHARSET = 'utf8mb3';

    /**
     * @param Table $subject
     * @param array $data
     * @return array
     */
    public function beforeCreate(Table $subject, array $data): array
    {
        if (!isset($data['charset'])) {
            $data['charset'] = self::DEFAULT_CHARSET;
        }

        return [$data];
    }
}
```

Another possible solution is to override `\Magento\Framework\Setup\Declaration\Schema\Dto\Table::getDiffSensitiveParams` parameters, excluding `charset` from the list. (Composer patch below)
```diff
diff --git a/Setup/Declaration/Schema/Dto/Table.php b/Setup/Declaration/Schema/Dto/Table.php
--- a/Setup/Declaration/Schema/Dto/Table.php
+++ b/Setup/Declaration/Schema/Dto/Table.php	(date 1655976014788)
@@ -343,7 +343,6 @@
             'resource' => $this->getResource(),
             'engine' => $this->getEngine(),
             'comment' => $this->getComment(),
-            'charset' => $this->getCharset(),
             'collation' => $this->getCollation()
         ];
     }
```

Huge thanks for helping with the investigation to @LeeSaferite, @navarr, and @so-max-u

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @lbajsarowicz ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with php 8.1 and the issue is reproducible. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/175469963-5edd2c5f-74d5-4678-8165-41ad3b6b8807.png)

**Comment by tgreeve** [comment]
This issue is reproducible in 2.4.3-p2.
![image](https://user-images.githubusercontent.com/77138909/175893453-987978eb-2a3b-4ade-bc1b-74deb14fbc56.png)

**Comment by zapotocnylubos** [comment]
The mentioned patch results (for me) in an error during `setup:install`

> [Progress: 4 / 1998]
Installing database schema:
Schema creation/updates:
>
> In ErrorHandler.php line 62:
>
> Warning: Undefined array key "charset" in /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Db/MySQL/DbSchemaWriter.php on line 89

**Comment by lbajsarowicz** [comment]
@zapotocnylubos There are two possible patches - Just use the other one :)

**Comment by zapotocnylubos** [comment]
U mean the plugin, right?

**Comment by joachimVT** [comment]
Having the same issue,
Creating a plugin 
<plugin name="fix_default_charset" type="Project\Theme\Plugin\OverrideDefaultCharsetPlugin" sortOrder="1"/>
Does not fix this issue.  After a successful deploy running setup:db:status still shows:
Declarative Schema is not up to date

**Comment by speller** [comment]
I'm having the same issue. The schema is always not up to date. The `\Magento\Framework\Setup\Declaration\Schema\Diff\Diff::$changes` variable always has 400 entries and all of them are related to `utf8mb3`.
Magento 2.4.5
PHP 8.1.13
MySQL version 8.0.30

**Comment by speller** [comment]
As a workaround, I'm using the following patch with the `cweagans/composer-patches` component:

```diff
--- a/Setup/Declaration/Schema/Dto/Factories/Table.php
+++ b/Setup/Declaration/Schema/Dto/Factories/Table.php
@@ -23,12 +23,12 @@
     /**
      * Default charset for SQL
      */
-    public const DEFAULT_CHARSET = 'utf8';
+    public const DEFAULT_CHARSET = 'utf8mb3';

     /**
      * Default collation
      */
-    public const DEFAULT_COLLATION = 'utf8_general_ci';
+    public const DEFAULT_COLLATION = 'utf8mb3_general_ci';

     /**
      * @var ObjectManagerInterface
```

It solves the problem with changes caused by encodings. I had other issues as well (#36558), so this workaround patch is not guaranteed to fix all issues.

**Comment by leonhelmus** [comment]
I think this means we need to update the charset in the database to utf8, since that's a reference at the moment for utf8mb3 and will be updated to a reference to utf8mb4. 

same for utf8mb3_general_ci that needs to be updated to utf8_general_ci. Or am i wrong?

**Comment by hostep** [comment]
Closed without an explanation telling why?

Possibly fixed by [AC-7469: Add support for MySQL8.0.29 and higher](https://github.com/magento/magento2/commit/2ae2a8fe580e6e439384c84933ce73914ac7277a#diff-5594dd842c8bc20d1396c7048c5279fb75ea07dc2e35bd9c68a1d2f23964e432) ?

**Comment by nocturnalfrog** [comment]
@hostep; I guess some habits are hard to kick. 😉

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5970 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-7469&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by jonathanribas** [comment]
There is already one for `utfmb4` support: https://github.com/magento/magento2/pull/35174
