### ISSUE TITLE
Submit Order Button Unresponsive in Magento Admin

### ISSUE THREAD

**Issue by fvlasie** [magento/magento2#35679]
### Preconditions and environment

- Magento version: 2.4.4
- Anything else that would help a developer reproduce the bug:
After filling all the required information the Submit Order button does not repond in /index.php/admin_XXXX/sales/order_create/index/key/XXXX/

### Steps to reproduce

1: Go to Sales > Order
2: Create New Order
3: Select Customer
4: Fill in products, address, payment, shipping
5: Click Submit Order

### Expected result

Order is placed successfully.

### Actual result

The Submit Order button produces no result.

### Additional information

Browser javascript console contains these errors:

[Error] Error: Syntax error, unrecognized expression: input:checked[name=payment[method]]
	(anonymous function) (legacy-build.min.js:12:9089)
	o (legacy-build.min.js:12:15482)
	(anonymous function) (legacy-build.min.js:12:18795)
	C (legacy-build.min.js:12:3176)
	a (legacy-build.min.js:12:20857)
	(anonymous function) (legacy-build.min.js:1:65929)
	getSelectedPaymentMethod (stripe_payments.js:372)
	placeAdminOrder (stripe_payments.js:416)
	eventListenerIL75gL28Xd (Anonymous Script 1 (line 2))
	(anonymous function) (Anonymous Script 1 (line 13))

The Content Security Policy 'font-src *.stripe.com klarna.com *.klarna.com *.klarnacdn.net *.klarnaevt.com fonts.gstatic.com data: 'self' 'unsafe-inline'; form-action secure.authorize.net test.authorize.net geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com pilot-payflowlink.paypal.com www.paypal.com www.sandbox.paypal.com *.cardinalcommerce.com *.paypal.com 'self' 'unsafe-inline'; frame-ancestors 'self'; frame-src fast.amc.demdex.net *.adobe.com secure.authorize.net test.authorize.net geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com www.paypal.com www.sandbox.paypal.com pilot-payflowlink.paypal.com player.vimeo.com *.youtube.com https://www.google.com/recaptcha/ magento-cloudflare.jetrails.com www.youtube.com c.paypal.com checkout.paypal.com assets.braintreegateway.com pay.google.com *.cardinalcommerce.com *.paypal.com *.stripe.com klarna.com *.klarna.com *.klarnacdn.net *.klarnaevt.com *.wesupply.xyz https://wesupplylabs.com *.weltpixel.com 'self' 'unsafe-inline'; img-src assets.adobedtm.com amcglobal.sc.omtrdc.net dpm.demdex.net cm.everesttech.net *.adobe.com widgets.magentocommerce.com data: www.googleadservices.com www.google-analytics.com www.paypalobjects.com t.paypal.com *.ftcdn.net *.behance.net www.paypal.com fpdbs.paypal.com fpdbs.sandbox.paypal.com *.vimeocdn.com i.ytimg.com validator.swagger.io *.ytimg.com https://maps.gstatic.com www.sandbox.paypal.com b.stats.paypal.com dub.stats.paypal.com assets.braintreegateway.com c.paypal.com checkout.paypal.com *.paypal.com *.gstatic.com *.cdninstagram.com *.fbcdn.net maps.googleapis.com *.aptrinsic.com storage.googleapis.com data: 'self' 'unsafe-inline'; script-src assets.adobedtm.com *.adobe.com secure.authorize.net test.authorize.net www.googleadservices.com www.google-analytics.com geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.paypalobjects.com js.braintreegateway.com www.paypal.com www.sandbox.paypal.com t.paypal.com s.ytimg.com www.googleapis.com vimeo.com www.vimeo.com *.vimeocdn.com https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ https://maps.googleapis.com assets.braintreegateway.com c.paypal.com pay.google.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.paypal.com *.stripe.com klarna.com *.klarna.com *.klarnacdn.net *.klarnaevt.com *.cloudflare.com ajax.googleapis.com https://www.googletagmanager.com tagmanager.google.com *.instagram.com maps.googleapis.com *.aptrinsic.com 'self' 'unsafe-inline' 'unsafe-eval'; style-src *.adobe.com unsafe-inline fonts.googleapis.com tagmanager.google.com *.aptrinsic.com 'self' 'unsafe-inline'; object-src 'self' 'unsafe-inline'; media-src *.adobe.com *.cdninstagram.com 'self' 'unsafe-inline'; manifest-src 'self' 'unsafe-inline'; connect-src dpm.demdex.net amcglobal.sc.omtrdc.net www.google-analytics.com geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com www.sandbox.paypal.com www.paypalobjects.com www.paypal.com pilot-payflowlink.paypal.com https://maps.googleapis.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.braintree-api.com *.paypal.com *.stripe.com klarna.com *.klarna.com *.klarnacdn.net *.klarnaevt.com https://www.google-analytics.com *.instagram.com *.googleusercontent.com *.aptrinsic.com 'self' 'unsafe-inline'; child-src assets.braintreegateway.com c.paypal.com *.paypal.com http: https: blob: 'self' 'unsafe-inline'; default-src 'self' 'unsafe-inline' 'unsafe-eval'; base-uri 'self' 'unsafe-inline';' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
legacy-build.min.js:12:9089

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by fvlasie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hello @fvlasie , 

We have tried to reproduce the issue in Magento 2.4.4 the issue is not reproducible.
Please refer the below screenshot for the reference;
![Screenshot from 2022-06-27 12-44-42](https://user-images.githubusercontent.com/60198592/175882167-c01de72f-8f61-4fd4-8bf0-f9752cd4335b.png)
![Screenshot from 2022-06-27 12-44-30](https://user-images.githubusercontent.com/60198592/175882182-04cf2127-6d25-4086-8eee-79369829a654.png)

We have followed the below steps in order to reproduce the issue:
1: Go to Sales > Order
2: Create New Order
3: Select Customer
4: Fill in products, address, payment, shipping
5: Click Submit Order

Let us know in case we have missed anything. 

Thanks

**Comment by timpea** [comment]
@fvlasie Have you updated Stripe to the latest version?  There was an issue with Stripe where it didn't allow you to place an order in the admin without selecting the Stripe payment method 1st.   This was fixed with Stripe 3.2.3.

**Comment by fvlasie** [comment]
I found the problem! My Stripe extension was outdated.
