### ISSUE TITLE
Multiple  Websites: website_id not updated on save

### ISSUE THREAD

**Issue by dafencun** [magento/magento2#3568]
I have built two sites: site1.com and site2.com, with site1 having Magento 2 sample products.

Place  all products in site1.com into site2.com  (by setting  the root directory to be same as site1)
In Product ===> Catalog  
      Select All ---> Update Attributes -->Websites --->Save

Issue: weibsite_id of site2.com is not updated. As a result,  no of the products are shown in site2.com

However, when an INDIVIDUAL product is EDITed without any changes and "Save",  weibsite_id does change correctly and the EDITed product is shown on site2.com

**Comment by katmoon** [comment]
Hi @dafencun 

Thank you for reporting the issue.
I tried to reproduce it, but it works as expected for me.

Could you try to reindex manually and let me know if it helps: `bin/magento indexer:reindex`
And clear cache if needed: `bin/magento cache:clean`

Thanks,
Kateryna.

**Comment by dafencun** [comment]
Hi, Kateryna,

Following your instructions, I managed to display all the sample products in multiple stores.

Many thanks,

Dafencun
