### ISSUE TITLE
Unable to compile the code

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#35681]
### Preconditions and environment

- Magento version: 2.4.3
- Php 7.4
- Upgraded from 2.2.11 to 2.4.3

### Steps to reproduce

In CLI try: composer require magento/product-community-edition=2.4.3 --no-update
There are several other plugins in CLI when appear you must allow
Use the following commands
php bin/magento setup:upgrade
php bin/magento setup:di:compile

### Expected result

php bin/magento setup:di:compile suppose to finish the compilation

### Actual result

I am getting this error in PUTTY CLI
`
[rstxdbpzav]:public_html$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/9 [==>----------------]  11% < 1 sec 135.0 MiClass 'PHPUnit_Framework_TestCase' not found#0 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(136): require_once()
#1 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#2 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#3 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#4 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#5 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#6 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#7 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#10 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#11 /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/bin/magento(23): Symfony\Component\Console\Application->run()
#12 {main}

[rstxdbpzav]:public_html$

`
![image](https://user-images.githubusercontent.com/17259817/175829376-2890c830-7b53-4961-a914-ac2d6a6836b7.png)

### Additional information

I have tried everything
Removed the app/code folder and tried
Removed generated var/cache var/page_cache etc

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
You need to update PHPUnit:

composer require phpunit/phpunit "^9.5"

**Comment by key-dev** [comment]
Thank you @devchris79 
I have tried that command but it throws errors.
Below is my current composer.json

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.4.3",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.4.3",
        "magento/composer-root-update-plugin": "~1.1",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "tnw/quickbooksbasic": "2.1.40",
        "tnw/quickbooksbusiness": "2.1.45",
        "tnw/quickbooksenterprise": "2.1.38",
        "affirm/magento2": "3.1.3",
        "magepal/magento2-gmailsmtpapp": "^2.9",
        "mailchimp/mc-magento2": "^103.4",
        "square/module-squareup-omni": "^1.12",
        "m2e/ebay-amazon-magento2": "^1.23",
        "aheadworks/module-raf": "^1.1",
        "aheadworks/module-reward-points": "^1.8",
        "rootways/module-authorizecim": "2.2.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.4",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.18.1",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": "^0.12.77",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "^6.0.3",
        "squizlabs/php_codesniffer": "~3.5.4",
        "symfony/finder": "^5.2"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/",
			"canonical": false
        },
        "1": {
            "type": "composer",
            "url": "https://packages.ebizmarts.com"
        },
        "powersync": {
            "type": "composer",
            "url": "https://dist.powersync.biz",
			"canonical": false
        },
        "repo-name": {
            "type": "composer",
            "url": "https://packages.ebizmarts.com"
        },
        "aheadworks": {
            "type": "composer",
            "url": "https://dist.aheadworks.com/"
        }
    },
    "extra": {
        "magento-force": "override"
    },
    "config": {
        "allow-plugins": {
            "magento/magento-composer-installer": true,
            "magento/inventory-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "magento/composer-dependency-version-audit-plugin": true,
            "magento/composer-root-update-plugin": true
        }
    }
}


The errors i am getting.
If i go with the option no.
![image](https://user-images.githubusercontent.com/17259817/176088520-0324203b-ef43-41d0-a465-7a813a511b9a.png)

If i go with the option yes.
![image](https://user-images.githubusercontent.com/17259817/176088609-945b1bb6-b603-4c11-991d-909b59fdb9c4.png)

**Comment by devchris79** [comment]
As I understand it `composer install` will install both the require (production dependencies) and the require-dev (development/test dependencies)

As long as you didn't use `composer install --no-dev` that installs only the development/test dependencies

**Comment by key-dev** [comment]
Its not working.
I have even tried by removing "phpunit/phpunit": "^9" from composer.json and then trying adding "phpunit/phpunit": "^9.5"

It throws the following errors.


  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.3 -> satisfiable by magento/product-community-edition[2.4.3].
    - magento/magento2-functional-testing-framework[3.0.0, ..., 3.5.0] require allure-framework/allure-codeception ~1.4.0 -> satisfiable by allure-framework/allure-codeception[1.4.0, ..., 1.4.5].
    - allure-framework/allure-codeception 1.4.5 requires allure-framework/allure-php-api ~1.2.1 -> satisfiable by allure-framework/allure-php-api[1.2.1].
    - allure-framework/allure-codeception[1.4.3, ..., 1.4.4] require allure-framework/allure-php-api ~1.1.8 -> satisfiable by allure-framework/allure-php-api[1.1.8].
    - allure-framework/allure-codeception 1.4.2 requires allure-framework/allure-php-api ~1.1.7 -> satisfiable by allure-framework/allure-php-api[1.1.7, 1.1.8].
    - magento/magento2-functional-testing-framework[3.6.0, ..., 3.10.0] require monolog/monolog ^2.3 -> satisfiable by monolog/monolog[2.3.0, ..., 2.7.0].
    - You can only install one version of a package, so only one of these can be installed: allure-framework/allure-php-api[1.1.0, ..., 1.4.0].
    - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.0.0, ..., 1.27.1, 2.0.0, ..., 2.7.0, 3.0.0, 3.1.0].
    - allure-framework/allure-codeception[1.4.0, ..., 1.4.1] require codeception/codeception ^2.3|^3.0 -> satisfiable by codeception/codeception[2.3.0, ..., 2.5.6, 3.0.0, ..., 3.1.3].
    - allure-framework/allure-phpunit[1.4.0, ..., 1.5.0] require allure-framework/allure-php-api ^1.3 -> satisfiable by allure-framework/allure-php-api[1.3.0, 1.3.1, 1.4.0].
    - magento/product-community-edition 2.4.3 requires monolog/monolog ^1.17 -> satisfiable by monolog/monolog[1.17.0, ..., 1.27.1].
    - codeception/codeception[2.2.11, ..., 2.3.0] require phpunit/phpunit >4.8.20 <6.0 -> found phpunit/phpunit[4.8.21, ..., 4.8.36, 5.0.0, ..., 5.7.27] but it conflicts with your root composer.json require (^9.5).
    - codeception/codeception[2.3.1, ..., 2.3.6] require phpunit/phpunit >4.8.20 <7.0 -> found phpunit/phpunit[4.8.21, ..., 4.8.36, 5.0.0, ..., 5.7.27, 6.0.0, ..., 6.5.14] but it conflicts with your root composer.json require (^9.5).
    - codeception/codeception[2.3.7, ..., 2.3.9] require phpunit/phpunit >=4.8.28 <5.0.0 || >=5.6.3 <7.0 -> found phpunit/phpunit[4.8.28, ..., 4.8.36, 5.6.3, ..., 5.7.27, 6.0.0, ..., 6.5.14] but it conflicts with your root composer.json require (^9.5).
    - codeception/codeception[2.4.0, ..., 2.5.6, 3.0.0, ..., 3.1.3] require symfony/finder >=2.7 <5.0 -> found symfony/finder[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.41] but it conflicts with your root composer.json require (^5.2).
    - Root composer.json requires allure-framework/allure-phpunit ~1.4 -> satisfiable by allure-framework/allure-phpunit[1.4.0, 1.5.0].
    - allure-framework/allure-phpunit[1.4.0, ..., 1.5.0] require phpunit/phpunit ^7.2 | ^8 | ^9 -> satisfiable by phpunit/phpunit[9.5.0, ..., 9.5.21].
    - phpunit/phpunit[9.5.16, ..., 9.5.21] require phpunit/php-code-coverage ^9.2.13 -> satisfiable by phpunit/php-code-coverage[9.2.13, 9.2.14, 9.2.15].
    - phpunit/phpunit[9.5.10, ..., 9.5.14] require phpunit/php-code-coverage ^9.2.7 -> satisfiable by phpunit/php-code-coverage[9.2.7, ..., 9.2.15].
    - phpunit/phpunit[9.5.0, ..., 9.5.9] require phpunit/php-code-coverage ^9.2.3 -> satisfiable by phpunit/php-code-coverage[9.2.3, ..., 9.2.15].
    - phpunit/php-code-coverage[9.2.8, ..., 9.2.15] require nikic/php-parser ^4.13.0 -> satisfiable by nikic/php-parser[v4.13.0, v4.13.1, v4.13.2, v4.14.0].
    - phpunit/php-code-coverage 9.2.7 requires nikic/php-parser ^4.12.0 -> satisfiable by nikic/php-parser[v4.12.0, ..., v4.14.0].
    - phpunit/php-code-coverage[9.2.3, ..., 9.2.6] require nikic/php-parser ^4.10.2 -> satisfiable by nikic/php-parser[v4.10.2, ..., v4.14.0].
    - You can only install one version of a package, so only one of these can be installed: nikic/php-parser[v4.3.0, ..., v4.14.0].
    - magento/magento2-functional-testing-framework 3.5.1 requires nikic/php-parser ~4.4.0 -> satisfiable by nikic/php-parser[v4.4.0].
    - Root composer.json requires magento/magento2-functional-testing-framework ^3.0 -> satisfiable by magento/magento2-functional-testing-framework[3.0.0, ..., 3.10.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.


Please help

**Comment by devchris79** [comment]
For some reason you are not picking up the latest symfony/finder, that's then restricting other things:

> codeception/codeception[2.4.0, ..., 2.5.6, 3.0.0, ..., 3.1.3] require symfony/finder >=2.7 <5.0 -> found symfony/finder[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.41] but it conflicts with your root composer.json require (^5.2).

It appears there up at v6, so why your latest is v4.4.41 I don't know.

**Comment by devchris79** [comment]
Try `composer show "symfony/finder" --all`

It should show all the versions in the repository, I see up to 6.1.0 as a release instance (there are also betas)

**Comment by key-dev** [comment]
Sorry, i am not pro, can you explain where to update it?

**Comment by devchris79** [comment]
composer require symfony/finder "^4.4.41"

**Comment by shubhamkanungoo007** [comment]
Hi @key-dev ,
Can you please confirm your Composer version using "composer --version" this command and if it is below 2.x so, please try to update it "Composer version 2.0.12" or atleast 2.0.x and then remove your vendor folder. After the removal of vendor folder please run "composer install" and "composer update" commands. 
After this process try to run the Magento commands setup:upgrade and setup:di:compile.

**Comment by shubhamkanungoo007** [comment]
@magento Can you please assign this ticket to me. I will work on it ? 

Thanks,

**Comment by engcom-Delta** [comment]
Hi @key-dev ,
Any update please on below comments .
https://github.com/magento/magento2/issues/35681#issuecomment-1174909456.

Thanks
