### ISSUE TITLE
'htmlContent' in Ui Components not rendering if block has no name

### ISSUE THREAD

**Issue by FYvwotschel** [magento/magento2#35694]
### Summary (*)
Creating the element 'htmlContent' in a UI Component Form does not render if the containing block does not contain a name. Also no error gets thrown, even with the console logger level set to 2.

### Examples (*)
```xml
<fieldset name="custom_fieldset">
  <settings>
    <label/>
  </settings>

  <htmlContent name="custom_html_content">
    <block class="Magento\Backend\Block\Template"
           template="Vendor_Module::form/custom_template.phtml"/>
  </htmlContent>
</fieldset
```

### Proposed solution
- Display error message

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Charlie** [comment]
Hi @FYvw,

As we have not received any reply on [comment](https://github.com/magento/magento2/issues/35694#issuecomment-1184453925) for a period more than 14 days hence because of the inactivity we are closing this issue. 

Please raise a fresh issue or reopen this issue if you need more assistance on this.

Thank you!
