### ISSUE TITLE
Email template preview issues

### ISSUE THREAD

**Issue by EugIvashAmasty** [magento/magento2#35697]
### Preconditions and environment

- Magento version 2.4.4

### Steps to reproduce

1. Go to Marketing->Communications->Email Templates.
2. Go to any email template.
3. Click “preview template”

### Expected result

Template is not clipped
![d5904f78-5aa7-41f0-a5b8-d64880d8df09](https://user-images.githubusercontent.com/108362366/176252634-5a09cc89-3d80-463a-ad11-1e78ef5da19b.png)

### Actual result

Template cut off
![0711e817-fa39-431d-8538-39f0972aa4d7](https://user-images.githubusercontent.com/108362366/176252333-e029bab7-9465-479f-a067-7b5722a5d0e3.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/176429854-21c6343b-3413-4bc8-9cd7-56fabb785e60.png)

**Comment by MaksSum41** [comment]
@magento I am working on this

**Comment by TerrapinSoftware** [comment]
The problem is in file vendor/magento/module-email/view/adminhtml/templates/preview/iframeswitcher.phtml, line 37:

    $('#preview_iframe').load(function() {

load() is deprecated and has been changed. The correct code is

    $('#preview_iframe').on('load', function() {
