### ISSUE TITLE
Category page will show that there's another page of products, but when you navigate to it, it's empty

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#3569]
My guess is if you have products that are disabled or not visible, it is still counting these products in the paging, but because it's not visible or enabled, shows nothing when you navigate to that next page.

**Comment by vzabaznov** [comment]
Hi @samleeiii , thank you for reporting, i've checked the pagination on category page and looks like all is ok, could you please provide a version of magento that you are using, and some proper steps to reproduce

**Comment by vzabaznov** [comment]
@samleeiii thank you for reporting, functionality was changed, and i cannot reproduce this issue with fresh version, please feel free to write here or to reopen issue, if you think this it is reproducable
