### ISSUE TITLE
Public deleteSegmentCustomers method no longer used in CustomerSegment module

### ISSUE THREAD

**Issue by sta1r** [magento/magento2#35696]
### Summary (*)

In 2.4.1-p1, a change was made to stop using the public method `Magento\CustomerSegment\Model\ResourceModel\Segment::deleteSegmentCustomers()` in favour of the private `Magento\CustomerSegment\Model\ResourceModel\Customer\LinksMatcher::deleteSegmentCustomers()`. 

See https://github.com/magento-commerce/magento2ee/commit/a2497862cdd547354be3c827eb28363a388c5864.

We have a plugin [here](https://github.com/dotmailer/dotmailer-magento2-extension-enterprise/blob/master/Plugin/SegmentPlugin.php) with a `beforeDeleteSegmentCustomers()` method to catch when customers are added or removed from a segment, and update matching rows in our own table so we can sync segment affiliation to a customer record in our main platform. This clearly stopped working at 2.4.1-p1 (yes I know we missed it for a while). 

### Examples (*)

```
<?php

namespace Dotdigitalgroup\Enterprise\Plugin;

use Magento\CustomerSegment\Model\Segment;
use Magento\CustomerSegment\Model\ResourceModel\Segment as SegmentResource;

class SegmentPlugin
{
    /**
     * Reimport customers from the segment before it is changed
     *
     * @param SegmentResource $segmentResource
     * @param Segment $segment
     */
    public function beforeDeleteSegmentCustomers(SegmentResource $segmentResource, Segment $segment)
    {
        // this code does not run since 2.4.1-p1
    }
}
```

### Proposed solution

To be honest I don't really have a solution here. I can see from the above change, and the introduction of the temporary table, that the goal behind this was to make segment handling more efficient with large volumes of customers - this is all good. I guess, ideally it might not have happened this way in a patch release, but OK.

Right now, as it stands, we can't react to segment affiliation properly, to mirror contacts 'belonging' to segments in our own table. If I have a set of customers like:
```
bob@gmail.com
dave@gmail.com
friend-of-bob@gmail.com
chaz@gmail.com
```
and initially the segment is 'customers using gmail' but is then changed to 'customers with email containing bob' I need to update ALL customers: not just the ones who now match, but the ones now removed who no longer match, and no longer belong to the segment. 

Does anyone have any suggestions for how to react to customers being removed from a segment? 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Charlie** [comment]
Hi @sta1r,

Yes. Magento have stopped using the public method Magento\CustomerSegment\Model\ResourceModel\Segment::deleteSegmentCustomers() in favour of the private Magento\CustomerSegment\Model\ResourceModel\Customer\LinksMatcher::deleteSegmentCustomers().

In order to get solution on your mentioned issue in proposed solution section you can reach out on https://magento.stackexchange.com/ 

Hence closing this issue now. Please update if you need further more information.

Thank you!
