### ISSUE TITLE
My advanced reporting is not working I enabled it 2 days ago and still nothing, are you able to assist?

### ISSUE THREAD

**Issue by kiaann1** [magento/magento2#35701]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Delta** [comment]
Hi @kiaann1 ,
Thank you for raising an issue , Kindly provide me the steps to reproduce ,actual test results, expected results and screenshots to replicate the issue.

**Comment by kiaann1** [comment]
Hi,

Here are the steps I had followed

Step 1: Enable Advanced Reporting
In the Commerce configuration, [Advanced Reporting](https://docs.magento.com/user-guide/configuration/general/advanced-reporting.html) is enabled by default, and starts automatically if cron is [configured](https://docs.magento.com/user-guide/configuration/advanced/system.html) and running. An attempt to establish the subscription is initiated at the beginning of each hour over the next 24-hours until successful. The subscription status is “pending” until the subscription is successfully established.

On the Admin sidebar, go to Stores > Settings > Configuration.

In the left panel where General is expanded, choose Advanced Reporting and do the following:

Verify that Advanced Reporting Service is set to Enable (the default setting).

Set the Time of day to send data to the hour, minute, and second, according to a 24-hour clock, that you want the service to receive updated data from your store. By default, data is sent at 2:00 AM.

Under Industry Data, choose the Industry that best describes your business.

I have attached my screen shot
![Screenshot 2022-06-29 125241](https://user-images.githubusercontent.com/83919397/176430230-bedcca13-e555-48a9-ad89-fe5f70cc2af1.png)

![Screenshot 2022-06-29 125241](https://user-images.githubusercontent.com/83919397/176430164-0213aad9-6e19-4b85-adae-baa7dc261b5c.png)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
