### ISSUE TITLE
Cart Price Rule Discard Subsequent Rules Not Working As Intended

### ISSUE THREAD

**Issue by tionousman** [magento/magento2#35707]
### Preconditions and environment

- Magento version : 2.4.4
- PHP : 8.1

### Steps to reproduce

1. Create a Cart Price Rule with a coupon code (name it TEST) that gives $10 discount to Product ID 1 with "Discard Subsequent Rules" set to "Yes" and Priority set to 1
2. Create another Cart Price Rule without coupon code that gives $5 discount to Product ID 2 with Priority set to 10 (we assume this is a global sale for Product ID 2)
3. Go to frontend site and add Product ID 1 and Product ID 2 into cart
4. Apply TEST coupon code

### Expected result

Product ID 1 will get $10 discount and Product ID 2 will get $5 discount
It's stated in the documentation that "Discard Subsequent Rules" prevents multiple discounts from being applied to the same product. In this case the products are different so although "Discard Subsequent Rules" is set to "Yes" the second rule (for Product ID 2) should be able to be applied.

### Actual result

Product ID 1 gets $10 discount but Product ID 2 doesn't get any discount

### Additional information

Under SalesRule\Model\Quote\Discount.php there is a logic to check on "Discard Subsequent Rules" and it will stop the loop if set to "Yes" while in previous version Magento 2.4.3 the logic to check on "Discard Subsequent Rules" is in SalesRule\Model\RulesApplier.php so when it's set to "Yes" it will stop the loop of the rules, but not the loop of the items

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @tionousman ,
Thank you for raising an issue but issue is not reproducible. observed that for both the products first cart price rule is getting applied . Kindly refer the attached video.

https://www.loom.com/share/b51f03189fb84c6991f3b83747401eaf
Regards,

**Comment by tionousman** [comment]
@magento give me 2.4-develop instance

**Comment by tionousman** [comment]
Hi @engcom-Delta the issue is reproducible on Magento instance I requested. This is the step by step

1. Add Joust Duffle Bag to your cart https://f715d3be47fccca5eb1944cb49639749.instances.magento-community.engineering/joust-duffle-bag.html
2. Add Affirm Water Bottle to your cart https://f715d3be47fccca5eb1944cb49639749.instances.magento-community.engineering/affirm-water-bottle.html
3. In the cart page, you will see the discount is $3.5 (I created a rule that gives 50% discount on water bottle). This looks good.
4. Then apply 10OFF coupon code, it will give you $10 off for the Joust Duffle Bag. The discount should be $10 + $3.5 = $13.5, but it's only $10.
5. 50% discount on water bottle comes with priority 5 while the $10 off for the Joust Duffle Bag has 0 priority and both are set to "Discard Subsequent Rules". In previous Magento version this works fine.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by tionousman** [comment]
Hi @engcom-Delta ,

Thank you for the details. I noticed one difference between my cart rules and yours. So I didn't use the "Conditions", but instead I put the specific SKU condition under the "Action". So the "Conditions" should be empty (valid for all) but in the "Action" add the SKU condition so the discount will apply only on the specific product. Could you please try it again?

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @tionousman ,

Many thanks for confirmation on condition part. After removing condition section and added sku in action section, then issue is reproducible on Magento 2.4. develop instance.

Hence confirming the issue.
Please find the attached reference video.
https://www.loom.com/share/b5bbd3c6dd0842d8931b8cd159b02df2

**Comment by dudzio12** [comment]
I can confirm the issue for sales rule which:
- is active
- have specified rule conditions
- have specified action conditions
- have stop_rules_processing flag

I'm working on this.

**Comment by bjoern-quast** [comment]
Maybe both options should be offered, since the current behaviour of "discard subsequent rule" does exactly what it says, discards any subsequent (lower prio) rule. That is what one would expect from an option by that name.
For more flexibility, maybe add "discard subsequent rules (only) for this product" as well.

**Comment by EvanRijn** [comment]
Is there a patch for this one ? Or do we need to develop a patch?

**Comment by nobodyfamouz** [comment]
We are also facing this issue. Any progress on it?

**Comment by veloraven** [comment]
Internal team is working on this issue.

**Comment by palakaccorin** [comment]
We are also facing this issue. Any update on it?

**Comment by david-v** [comment]
Yes, we faced the same issue, I prepared a patch that fixes it in our project, it might fix it for yours too @palakaccorin :

I've created a gist to better be able to see what it does:

https://gist.github.com/david-v/dcb7cd58f66fe8502dbfa4f83abd69f3

**Comment by palakaccorin** [comment]
Thanks @david-v this is working but you reset the quote applied rule which is not correct so I update some code in your patch and now is working
Replaced this in https://gist.github.com/david-v/dcb7cd58f66fe8502dbfa4f83abd69f3
`if ($rule->getStopRulesProcessing() && in_array($rule->getId(), $appliedRuleIds)) {
                    $quote->setAppliedRuleIds("");
                    break;
                }`

with 
`if ($rule->getStopRulesProcessing() && in_array($rule->getId(), $appliedRuleIds) && in_array($rule->getId(), explode(',', $item->getAppliedRuleIds()))) {
                    break;
                }`

**Comment by glanujnehra** [comment]
The internal team is working on the issue

**Comment by aleksinoleg** [comment]
I faced the same issue.

**Comment by glanujnehra** [comment]
The fix will available in 2.4.7

**Comment by hostep** [comment]
@glanujnehra: please provide more info. Magento 2.4.7 will be released in the year 2024, people running against this problem will want to figure out how to fix this in the meanwhile using a patch for example.

I can find commits tagged as [ACP2E-1300: Cart Price Rule Discard Subsequent Rules Not Working As Intended](https://github.com/magento/magento2/search?q=ACP2E-1300&type=commits), are those the ones that fix this?

**Comment by glanujnehra** [comment]
@hostep Yes, the commits tagged was the one that fixes this issue and about the patch, we will get back to you.

**Comment by o-iegorov** [comment]
@hostep, yes commits tagged with ACP2E-1300 contains changes related to the fix, merge commit:
https://github.com/magento/magento2/commit/09384dfebbab1d98af2e3fa9ddced25830925a08 (contains other bugfixes)

**Comment by vkolesny** [comment]
Hi @sgautamrave,
I have checked your scenarios on 2.4-develop mainline branch, where current fix is merged.

And this issue is not reproduced there.

Please make sure that your rules are setup correctly.

I am attaching my rules setup and Cart pages screenshots with 5 + 2 and 4 + 2 QTYs:

![image](https://github.com/magento/magento2/assets/47639523/624cff0b-5954-4906-bb8d-bc6228fab5e4)

![image](https://github.com/magento/magento2/assets/47639523/c015d1b6-f386-47a5-aa91-0ec1caaebdd2)

![image](https://github.com/magento/magento2/assets/47639523/aa0f00de-d615-486d-aa0e-f3290eee1a36)

![image](https://github.com/magento/magento2/assets/47639523/e69fe20c-d92b-4083-a290-2db63f64049a)

**Comment by sgautamrave** [comment]
Hello @vkolesny ,

This is how I have created cart rule please check the screenshots - 

Cart Rule 1 - with Priority set to 1 and Discard Subsequent Rule enabled
Screenshot - https://prnt.sc/6TRdJ7R13KdD
Screenshot - https://prnt.sc/5o-v0mJY_90W

Cart Rule 2 - with Priority set to 2 and without Discard Subsequent Rule enabled
Screenshot - https://prnt.sc/OY6z3scgalTq
Screenshot - https://prnt.sc/qXbSD70yy54w

How rule 1st and 2nd is getting applied -

Case 1st -
Added joust double 5 qty which satisfy 1st rule - https://prnt.sc/voyel8NliNlD

Case 2nd - 
Added joust double product with 5 qty and added Affirm Water Bottle product with qty 3. By adding these product both 1st and 2nd rule condition is satisfied and gets applied to relevant products - https://prnt.sc/OiMQAHbtmfxC

Case 3rd -
Now I decrease a 1 qty from joust double. So, 1st rule should be applied to both the products but it is not happening - https://prnt.sc/8Tmqb_NRnPlH

**Comment by vkolesny** [comment]
Hi @sgautamrave,
I have checked your scenarios on 2.4-develop mainline branch according to your screenshots.

And I have expected result. Discount is 54.95:
![image](https://github.com/magento/magento2/assets/47639523/37539f93-3c7b-4dd1-b8b5-5a0f0ce6c048)

**Comment by vkolesny** [comment]
Hi @sgautamrave 

If the issue is still reproducible on your environment on your Adobe Commerce version, could you please report it as a new issue according to the new issue reporting procedure on GitHub? Seems that's more deep investigation could be required in scope of your issue.

Unfortunately, that's all we can do in scope of this Closed issue.

**Comment by sgautamrave** [comment]
Hello @vkolesny ,

Actually you have also tested on vanilla instance at your end and it is working. So, I think there might be some file or fix which is missing. It will be very helpful if you can mention the list of files that needs to be used to fix the issue.
