### ISSUE TITLE
Backend Catalog Bundled products do not load when using Dutch language

### ISSUE THREAD

**Issue by dragonfly4** [magento/magento2#35704]
### Preconditions and environment

- Magento version v2.4.4
- PHP Version 8.1.7

### Steps to reproduce

1. Navigate to adminhtml and login
2. Set user language to English
3. create bundle product and assign discount
4. Navigate to Catalog -> Products
5. Set filter on Type: Bundle Product
6. Products load normally
7. Change user language to Dutch
8. Navigate to Catalog -> Products
9. Set filter on Type: Bundle Product if no longer active

### Expected result

See products

### Actual result

10. Error appears: "Something went wrong with processing the default view and we have restored the filter to its original state."

### Additional information

This message appears in the error log. I have not included the Full Stack trace

main.CRITICAL: Exception: Warning: A non-numeric value encountered in /vendor/magento/module-bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php on line 80 in /vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /vendor/magento/module-bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php(80): Magento\Framework\App\ErrorHandler->handler()
#1 /vendor/magento/module-catalog/Ui/DataProvider/Product/ProductDataProvider.php(93): Magento\Bundle\Ui\DataProvider\Product\Modifier\SpecialPriceAttributes->modifyData()

Line 80
$item[$priceAttribute] = $numberFormatter->format($item[$priceAttribute] / 100);

I have added debug code on a test environment.

With English language: main.DEBUG: bundle: 81.06 [] []
With Dutch language: main.DEBUG: bundle: 81,06 [] []

The adminhtml overview loads the price/discount with the Dutch decimal sign. See dot vs comma above.

![adminhtml_catalog_products_dutch](https://user-images.githubusercontent.com/221351/176444060-cdaadd3a-e6ab-49d6-8e68-afeae72e9406.jpg)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dragonfly4** [comment]
@magento give me 2.4-develop instance

**Comment by dragonfly4** [comment]
The problem is reproducible on the develop instance

![adminhtml_catalog_products_dutch_dev_instance](https://user-images.githubusercontent.com/221351/176446350-4999baaa-818c-44b9-8ed8-3a66e2ddd4a1.jpg)

![adminhtml_catalog_products_dutch_dev_instance_language](https://user-images.githubusercontent.com/221351/176446486-c4e0fcd0-4088-4f38-abc9-1ce3a06c2125.jpg)

**Comment by mikeKots** [comment]
@magento add to contributors team

**Comment by mikeKots** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @dragonfly4,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3769 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3769&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by vncnt-mb** [comment]
Hello,

Sorry to reopen this commit but there is the same problem with the French language and the bundled products with a special price.

I saw that there was a const created for languages using commas in decimals (39a7cfab9420aa7a16c2de1cc79da2ec12cee561 - LOCALE_USING_DECIMAL_COMMA), is it possible to add fr_FR (and maybe all equivalents)?

Thanks in advance!

**Comment by densen45** [comment]
German language is effected as well. Please see https://github.com/magento/magento2/issues/36089.

**Comment by satknightn** [comment]
This happens with en_US locale too in case you have comma as separator for thousands. So, when you have a price above 1000.00 it get formatted like 1,449.00 and you'll get error
