### ISSUE TITLE
Remote storage issue

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35706]
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1.7 (allow_url_fopen = ON)

### Steps to reproduce

1. Configure remote storage (S3, minio, ...)
2. Upload an image in Stores > Configuration > Sales > Sales > Logo for PDF Print-outs (200x50)
3. Place an order and invoice it
4. Try to print invoice from backend

### Expected result

PDF is generated

### Actual result

```
Cannot create image resource. File not found."
#1 Zend_Pdf_Image::imageWithPath() called at [vendor\/magento\/module-sales\/Model\/Order\/Pdf\/AbstractPdf.php:282]
```

### Additional information

I doubled checked : the file does exists. And the absolute url passed to `Zend_Pdf_Image::imageWithPath` is correct and gives a 200 when launched in browser. However, `php -r "var_dump(is_file('http://s3.domain/path/file.jpg'));"` does return false. (I don't understand why, it should work according to PHP doc)

`Zend_Pdf_Resource_ImageFactory` should be deprecated and replaced by a class which uses `Magento\Framework\Filesystem\DriverInterface::isFile()` instead of prohibited `is_file`. Maybe some other classes needs to be fixed as well.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment]
```
(I don't understand why, it should work according to PHP doc, but it seems that php issue is )
```

I misunderstood the PHP doc, it is indeed not allowed by PHP, cf here : https://www.php.net/manual/fr/wrappers.http.php
So it is "normal" that the code crashes. And `Zend_Pdf_Image_Factory` should definitely be rewritten.

**Comment by Nuranto** [comment]
If someone is stuck with this, here is a temporary fix 

```
diff --git a/library/Zend/Pdf/Resource/ImageFactory.php b/library/Zend/Pdf/Resource/ImageFactory.php
--- a/library/Zend/Pdf/Resource/ImageFactory.php
+++ b/library/Zend/Pdf/Resource/ImageFactory.php
@@ -32,11 +32,23 @@
  */
 class Zend_Pdf_Resource_ImageFactory
 {
-    public static function factory($filename) {
-        if(!is_file($filename)) {
+    public static function factory($filename)
+    {
+        $fileExists = false;
+        if (strpos($filename, '/media/') === false) {
+            $fileExists = is_file($filename);
+        } else {
+            $filesystem = \Magento\Framework\App\ObjectManager::getInstance()
+                ->get(\Magento\Framework\Filesystem::class);
+            $mediaReadDirectory = $filesystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA);
+
+            $fileExists = $mediaReadDirectory->isFile($filename);
+        }
+        if (!$fileExists) {
             #require_once 'Zend/Pdf/Exception.php';
-            throw new Zend_Pdf_Exception("Cannot create image resource. File not found.");
+            throw new Zend_Pdf_Exception("Cannot create image resource. File not found. " . $filename);
         }
+
         $extension = pathinfo($filename, PATHINFO_EXTENSION);
         /*
          * There are plans to use Zend_Mime and not file extension. In the mean time, if you need to
@@ -68,4 +80,3 @@
         }
     }
 }
-
```

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the report!

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is reproducible for us. We have followed the same steps as mentioned in the main description and getting the below error:

![image](https://user-images.githubusercontent.com/51681618/183607365-49c83dfa-4a0f-4a31-aa47-71ce1a9b00e2.png)

Hence confirming the issue.

Thanks

**Comment by monteshot** [comment]
@magento I am working on this

**Comment by Nuranto** [comment]
Hi @madalinignisca 

It's both. The patch I proposed still works in 2.4.6, but the file changed location (it is now in zend-pdf package)
