### ISSUE TITLE
Error: Call to a member function getUserName() on null in vendor/magento/module-contact/view/frontend/templates/form.phtml

### ISSUE THREAD

**Issue by jrswgtr** [magento/magento2#35703]
### Preconditions and environment

- Magento 2.4.3-p1
- PHP 7.4.28

### Steps to reproduce

1. Navigate to the contact page

### Expected result

The customer sees the contact form

### Actual result

The next error shows: 

> Error: Call to a member function getUserName() on null in vendor/magento/module-contact/view/frontend/templates/form.phtml

### Additional information

The `getUserName()` method is called on `\Magento\Contact\ViewModel\UserDataProvider` which is null because the block `\Magento\Contact\Block\ContactForm` does not have the method `getViewModel()`. 

I created a workaround which is extending and overriding the `ContactForm` block as follows:

```
use Magento\Framework\View\Element\Template;
use Magento\Contact\ViewModel\UserDataProvider;

class FixedContactForm extends \Magento\Contact\Block\ContactForm
{
    private $viewModel;
    
    /**
     * @param Template\Context $context
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        UserDataProvider $viewModel,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->viewModel = $viewModel;
    }
    
    public function getViewModel()
    {
        return $this->viewModel;
    }
}
```

di.xml:

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
    <preference for="Magento\Contact\Block\ContactForm" type="MyVendor\Contact\Block\FixedContactForm" />
</config>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@jrswgtr: the viewModel is supposed to be injected with the layout xml file, like so: https://github.com/magento/magento2/blob/2.4.3/app/code/Magento/Contact/view/frontend/layout/contact_index_index.xml#L16-L18 (at least in Magento 2.4.3, in 2.4.4 it [changed again](https://github.com/magento/magento2/commit/b5f3d973973985ea82317fd6d839429c2481929d))

So in your case, I'm going to guess that you are setting up the `form.phtml` file using some layout xml and might be missing that `view_model` argument?
