### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state. Magento V 2.4.4

### ISSUE THREAD

**Issue by magentoprasad** [magento/magento2#35717]
### Preconditions (*)

1. Admin - Catalog Product 
2. 

### Steps to reproduce (*)

1. After navigate product page from admin this error will get. 
2. 
3. 

### Expected result (*)

1. Access smoothly products and add / edit products.

### Actual result (*)

1. 
![error-](https://user-images.githubusercontent.com/15624977/176994945-ab6f86e8-252f-4d6f-b74f-5aa24654741c.png)
![Inventory _ Catalog _ Magento Admin-error](https://user-images.githubusercontent.com/15624977/176994957-d32dffbc-62ad-49ec-9941-d73db428e937.png)

**Comment by magentoprasad** [comment]
additionally now we facing issue for catalog-product page 
list of products not showing on page.
![Product_ Catalog _ Magento Admin](https://user-images.githubusercontent.com/15624977/177052281-7ecb41a3-f0e2-41bb-b327-3bdb95b40d9f.png)

**Comment by engcom-Delta** [comment]
Hi @magentoprasad ,
Thank you logging an issue . We tried to reproduce the issue on magento 2.4 develop, issue is not reproducible.
Please find the attached screenshots for reference.

![Screenshot (247)](https://user-images.githubusercontent.com/51681379/177143009-aca274d3-3aec-4e3d-a917-518d1d3046f5.png)

![Screenshot (248)](https://user-images.githubusercontent.com/51681379/177143036-8364f829-b4cb-4554-92ad-a017d7ab445f.png)

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by magentoprasad** [comment]
Hello 
currently we manage to resolve the issue. but it was not good practice.
we made changes in file /vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php
line no 61 'ariaLabel' => __('Edit ') . $item['name'], To   'ariaLabel' => __('Edit '),

One more I observe that when Elasticsearch get inactive that time also issue raised or product not get saved.

**Comment by julionc** [comment]
```diff
diff --git a/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php b/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php
index 82e8c40832..ed1bcf063f 100644
--- a/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php
+++ b/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php
@@ -53,6 +53,7 @@ class ProductActions extends Column
             $storeId = $this->context->getFilterParam('store_id');
 
             foreach ($dataSource['data']['items'] as &$item) {
+                $item['name'] = (isset($item['name'])) ? $item['name'] : '';
                 $item[$this->getData('name')]['edit'] = [
                     'href' => $this->urlBuilder->getUrl(
                         'catalog/product/edit',
```
