### ISSUE TITLE
Plugin disabled for adminhtml gets disabled for frontend environment emulation

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35718]
### Preconditions and environment

- Magento version: 2.4.3-p1.

### Steps to reproduce

1. Create a global plugin that changes the product name and define it in `etc/di/xml`
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <type name="Magento\Catalog\Model\Product">
        <plugin name="product_name_amendments" type="Qsolutions\ProductName\Plugin\ProductNameAmendments"/>
    </type>
</config>
```
plugin:
```
public function afterGetName(Product $subject, $result): string
{
    return $subject->getName() . '-some-random-feature'
}
```
2. Disable the same plugin in `etc/adminhtml/di.xml`
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <type name="Magento\Catalog\Model\Product">
        <plugin name="product_name_amendments" disabled="true" />
    </type>
</config>
```
3. Create a cron  / CLI task that fetches products from the repository and iterates through them
4. Try to get the product name in the look / by loading product model from resource / repository / in collection running in CLI / CRON task.
```
                $this->emulation->startEnvironmentEmulation($store->getId(), Area::AREA_FRONTEND, true);
                $productsCollection = $this->productCollectionFactory->create();
                $productsCollection->addAttributeToSelect('*');
                $productsCollection->addAttributeToFilter('sku', ['in' => $productSkus]);
                $productsCollection->setStore($store);

                foreach ($productsCollection->getItems() as $product) {
                    var_dump($product->getName());
                }
```

### Expected result

1. On the frontend, product name **is changed**
2. In the admin, product name **is not changed**
3. In CLI / CRON product name **is changed**

### Actual result

1. On the frontend, product name **is changed**
2. In the admin, product name **is not changed**
3. In CLI / CRON product name **is not changed** and it should be

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hello @qsolutions-pl,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
