### ISSUE TITLE
Paypal issue with Magento 2.4.3-P2

### ISSUE THREAD

**Issue by yasireg** [magento/magento2#35716]
### Preconditions and environment

- Magento version 2.4.3-P2
-After upgrading from 2.4.3-P1 to 2.4.3-P2

### Steps to reproduce

we are experiencing an issue while placing an order with papal, where we get **A wrong PayPal Express Checkout Token is specified**.

1. Enable promotion on specific products with Amasty promo module (Auto-add product)
2. Adding the products into the cart which will also add promo products into the cart
3. Place an order with PayPal

After click on pay button, it redirects to the shopping cart with an error message
**A wrong PayPal Express Checkout Token is specified**
the 

### Expected result

The order should be placed

### Actual result

But this error message is showing 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
@magento give me 2.4.3-p2 instance

**Comment by engcom-Delta** [comment]
Hi @yasireg ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4 develop instance , We are able to place an order successfully with paypal express checkout  which cart has promotions.

Kindly refer the attached video .
https://www.loom.com/share/f3ec5a48852248c5b1f79b9261d1529e

**Comment by engcom-Delta** [comment]
Hi @yasireg ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards,
