### ISSUE TITLE
Partial refund for Gift Cards

### ISSUE THREAD

**Issue by emrahuyanik** [magento/magento2#35715]
### Preconditions and environment

Magento version 2.4.3-p1 Enterprise

### Steps to reproduce

1. Add 2 gift cards product to the cart (it can be same or different product)
2. Place an order
3. Navigate to order detail in admin panel
4. Navigate to invoce detail
5. Click Creditmemo
6. Create a creditmemo for 1 item

### Expected result

1 Gift card should be removed. The other gift card which has not been refunded should remain

### Actual result

Both of the gift cards are being removed.

### Additional information

We have debugged the issue and realized below plugin is removing all of the gift cards. We have applied a fix like below

\Magento\GiftCardAccount\Model\Plugin\CreditmemoRepository::afterSave
```
  public function afterSave(CreditmemoRepositoryInterface $subject, CreditmemoInterface $entity): CreditmemoInterface
    {
        $order = ($entity->getOrder()) ?: $this->getOrderById((int)$entity->getOrderId());
        $orderItems = $this->getOrderItems($order);
        if ($orderItems) {
            foreach ($entity->getItems() as $creditMemoItem) {
                $orderItem = $orderItems[$creditMemoItem->getOrderItemId()];
                if ($orderItem->getProductOptionByCode('giftcard_created_codes')) {
                    $this->removeGiftCardAccount(
                        $orderItem->getProductOptionByCode('giftcard_created_codes'),
                        abs((int)$creditMemoItem->getQty())
                    );
                }
            }
        }

        return $entity;
    }
```

has been changed to below

```
 public function afterSave(CreditmemoRepositoryInterface $subject, CreditmemoInterface $entity): CreditmemoInterface
    {
        $order = ($entity->getOrder()) ?: $this->getOrderById((int)$entity->getOrderId());
        $orderItems = $this->getOrderItems($order);
        if ($orderItems) {
            foreach ($entity->getItems() as $creditMemoItem) {
                if (!$creditMemoItem->getId()) {
                    continue;
                }
                $orderItem = $orderItems[$creditMemoItem->getOrderItemId()];
                if ($orderItem->getProductOptionByCode('giftcard_created_codes')) {
                    $this->removeGiftCardAccount(
                        $orderItem->getProductOptionByCode('giftcard_created_codes'),
                        abs((int)$creditMemoItem->getQty())
                    );
                }
            }
        }

        return $entity;
    }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Issue is reproducible on 2.4 -develop branch. Steps to reproduce is same as above comment but for me issue is reproducible with two types of Gift card (ex- gift card virtual + gift card phyical/combined). Hence, confirming the issue.

**Comment by engcom-Lima** [comment]
Hi @emrahuyanik ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Lima** [comment]
Hi @emrahuyanik ,

Thanks for your contribution.

We have tried to deep dive in the issue again.
I have checked in my order page . I have done partial refund for the product but both of my product is not getting removed.
Please find below screenshot for your reference:
![image](https://user-images.githubusercontent.com/60198022/183452177-0d8c9219-6772-4ab2-8e41-667831d059a6.png)

**Additionally checked-** Stocks in product grid page.
Kindly provide us more information.

Thanks

**Comment by zepgram** [comment]
It's not the product who's deleted but the gift card account
