### ISSUE TITLE
Plugins not working while render email templates

### ISSUE THREAD

**Issue by Citizen4our** [magento/magento2#35727]
### Preconditions and environment

- Magento version - 2.4.3-p1
Looks like plugins not working while render email templates if plugin defined in other area, not in adminhtml or global.
it looks like the plugin defination  is missing in \Magento\Framework\Interception\PluginList\PluginList::$_inherited

### Steps to reproduce

1. create a plugin in area frontend for \Magento\Sales\Api\Data\OrderInterface. 
2.  create order
3. you will see plugin is not fired

### Expected result

plugin fired while renderer email template.

### Actual result

plugin is not fired

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @Citizen4our ,

Kindly Attach the screenshots for this Issue. It is very easy to proceed further.

Thanks!!!

**Comment by Citizen4our** [comment]
Hi @engcom-Dash 
![image](https://user-images.githubusercontent.com/47303372/178721967-03eb257d-f496-40d9-b354-956a25f808d0.png)

For example, my plugin defined on frontend area and must round up these prices

**Comment by engcom-November** [comment]
Hi @Citizen4our , Thank you for reporting and collaboration.
Can you please share your plugin code and on what method of Magento\Sales\Api\Data\OrderInterface Plugin is created?
Thank you.

**Comment by engcom-November** [comment]
Hi @Citizen4our ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
