### ISSUE TITLE
The attached file can't be seen on clients end. 

### ISSUE THREAD

**Issue by KarenO24** [magento/magento2#35723]
### Preconditions and environment

- Magento version Magento ver. 1.9.3.6
- Anything else that would help a developer reproduce the bug

We are trying to attach png, PDF file when responding to clients' emails but on clients' end they don't see it. 

### Steps to reproduce

Helpdesk
respond to open/new ticket
click the attached file and attached a file
then send a response. 

### Expected result

Client should received the files we sent to them. 

### Actual result

Client always say no attached files. 

### Release note

The only issue is sending attached files. When client send us a file we can see it. the problem is on our end. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,
Kindly Attach the Screenshots.  Because it is will easy to proceed to further in this Instance.

Thanks

**Comment by KarenO24** [comment]
Okay, I will get an example for you.

**Comment by KarenO24** [comment]
Please see example below, Hope you will be able to resolved this. Its been
ongoing and its difficult on our part.

As you can see I have an attachment on the ticket.

Ticket ID:  [IHA-17033

[image: image.png]

See Client response:

It was mentioned that he can't see the attached file. Same ticket, same
client.

[image: image.png]

**Comment by KarenO24** [comment]
Any update please?

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,

Thanks for your reply... I am not able to see the images which is attached same ticket!!!

Thanks.

**Comment by KarenO24** [comment]
Yes but on the screenshot I have showed you. the first image tells you that
I have attached a file but client confirmed that he did not received it.

The file I have attached is a PDF File.

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,

Thanks for your reply... I did't get any Images,Screenshots and PDF File with this comments.
So kindly Share appropriate files Directly.

Thanks!!!

**Comment by KarenO24** [comment]
Here you go. Please refer to the 3 files attached.

The EFT_Blank is the file that I have attached to the ticket number
[IHA-17033

**Comment by KarenO24** [comment]
Any update on this?

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,

Thanks for your reply...I didn't received any Files and Kindly Provide  some Screenshots with this ticket.

Thanks!!!

**Comment by KarenO24** [comment]
Please see the screenshot

**Comment by KarenO24** [comment]
Done. Please check

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,

Thanks for your reply...Currently we are Supporting magento version 2.4.x versions and we no longer supported magento version 1.9.x versions.So kindly upgrade the magento version.

Let us know in case we have missed anything. Thanks!

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
