### ISSUE TITLE
2.4.4 Configurable products are out of stock

### ISSUE THREAD

**Issue by hoshiray** [magento/magento2#35724]
### Preconditions and environment

- Magento version 2.4.4

### Steps to reproduce

1. Create/Import configurable products in Magento 
2. Product wont be displayed in catalog and will be out of stock even though it is selected in stock in product settings

### Expected result

Configurable product should be in stock

### Actual result

Product wont be displayed in catalog and will be out of stock even though it is selected in stock in product settings

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @o7-sol ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. Configurable products created are displayed on storefront in stock and able to place orders.
![image](https://user-images.githubusercontent.com/60198231/177313996-07cf251d-bafd-46e8-93cb-d87d287808ed.png)

![image](https://user-images.githubusercontent.com/60198231/177313949-c68892df-9f30-469e-b164-622c17d96508.png)

Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by o7-sol** [comment]
Problem is when you change product stock in this order:
1. In Stock
2. Out of stock
3. In Stock

The product will be out of stock with the value of `stock_status` zero in `cataloginventory_stock_status`

**Comment by engcom-November** [comment]
Thanks for the update @o7-sol . Verified the issue again on Magento 2.4-develop branch with above mentioned steps but cannot reproduce after re-indexing and clearing cache. 
Steps performed:
1. Configurable product - Edit - Change stock status to Out of Stock and save
2. Reindex and flush cache
3. Front-end - Verify catalog search - No issue. Product is not displayed since of out of stock
4. Edit again from admin - Change back to in stock and save
5. Reindex and flush cache - No issue - Product displayed on front end with in stock.
Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by seak6adtn59v** [comment]
> Problem is when you change product stock in this order:
> 
> 1. In Stock
> 2. Out of stock
> 3. In Stock
> 
> The product will be out of stock with the value of `stock_status` zero in `cataloginventory_stock_status`

This was the issue, somehow after updating to M2.4.4 some out of stock config products when we make them In Stock, they were still showing out of stock. Then I manually changed `stock_status` to 1 in `cataloginventory_stock_status` table for that config product and then it started showing all ok. 

I think Magento team should look into it.

**Comment by codecodeio** [comment]
I can confirm this issue on a vanilla install of Adobe Commerce Enterprise 2.4.4. Changing the configurable stock status from  "In Stock" to "Out of Stock" and back to "In Stock" leaves the configurable product showing as out of stock and will not appear in category pages even after full reindex and cache clearing.  I confirmed the issue occurs because cataloginventory_stock_status.stock_status remains at 0 even after changing the configurable product back to "In Stock". I also confirmed that manually updating cataloginventory_stock_status.stock_status to "1" resolves the issue.

**Comment by hostep** [comment]
@engcom-November: can you re-test based on the recent comments? (maybe check both with the MSI module installed and not installed, since this module affects these things)

**Comment by codecodeio** [comment]
@hostep Thanks but I don't know what the repercussions of disabling MSI would have on our site. I think the only acceptable solution is a patch or a version update. I did discover that a duplicate ticket exists for this same issue which was reproduced by Adobe, see the link below.  There is a ticket for it in the high-priority backlog. I am shocked this is not already being worked on as a priority 1 issue. In my view, this bug makes Adobe Commerce beta software that is not production ready.  I can not understate the importance of displaying products that are in stock for e-commerce software. 

[https://github.com/magento/magento2/issues/35494](url)

**Comment by likearocket** [comment]
I can also confirm this issue since upgrading to 2.4.4, so why is it closed?

**Comment by sebfie** [comment]
Can we have an update about it please? A patch or a fix ? Thank you

**Comment by danielrussob** [comment]
solved in quality patch: MDVA-41061-V4 and ACSD-45488

https://devdocs.magento.com/quality-patches/tool.html#patch-grid

**Comment by dragonfly4** [comment]
I couldn't figure out what was going on until I found this issue. Can confirm this is a bug on v2.4.4

**Comment by seak6adtn59v** [comment]
> 

Is there any patch for Magento Open Source? Or these patches only applies to Adobe Commerce versions?

We are having same issue in Magento Open Source as well.

**Comment by seak6adtn59v** [comment]
> solved in quality patch: MDVA-41061-V4 and ACSD-45488
> 
> https://devdocs.magento.com/quality-patches/tool.html#patch-grid

Is there any patch for Magento Open Source? Or these patches only applies to Adobe Commerce versions?

We are having same issue in Magento Open Source as well.

**Comment by sebfie** [comment]
These patches are for opensource version, here are my git patches applied in this order : 

https://gist.github.com/sebfie/cacb5410b37af1217c3b6c8d8fbeb11d

**Comment by seak6adtn59v** [comment]
> These patches are for opensource version, here are my git patches applied in this order :
> 
> I am on 2.4.4
> 
> https://gist.github.com/sebfie/cacb5410b37af1217c3b6c8d8fbeb11d

Hi @sebfie I think link your provided is for MDVA-44818 which is actually an official magento2 patch for some different problem: https://support.magento.com/hc/en-us/articles/6044536970637 

Is there any Magento official version for patch? I checked MDVA-41061-V4 but I do not found it in magento quality patches tool.  @danielrussob could you please check why it is not found in the magento patch tool?

I am on magento open source 2.4.5 and I still face this inventory issue but the patch you told is not listed in patch tool. 

Please help!

**Comment by seak6adtn59v** [comment]
> solved in quality patch: MDVA-41061-V4 and ACSD-45488
> 
> https://devdocs.magento.com/quality-patches/tool.html#patch-grid

Where is this patch for Magento Open Source?

@danielrussob could you please reply about the patch ? or open source community need to live with this error until Magento 2.4.6 release?

**Comment by bitumin** [comment]
FYI we could reproduce this issue in 2.4.4-p2 after creating a new configurable product, setting it to "In Stock", reindexing and flushing caches. The manual db fix commented above by @o7-sol fixed it for us.

**Comment by bitumin** [comment]
@sebfie The 3 patches linked in your gist (thanks by the way) are identical, i.e. I believe we should just try applying one of them?

**Comment by sebfie** [comment]
@bitumin I updated my gist

**Comment by bitumin** [comment]
> Hi @sebfie I think link your provided is for MDVA-44818 which is actually an official magento2 patch for some different problem: https://support.magento.com/hc/en-us/articles/6044536970637

> Is there any Magento official version for patch? I checked MDVA-41061-V4 but I do not found it in magento quality patches tool. @danielrussob could you please check why it is not found in the magento patch tool?

@seak6adtn59v your link is about MDVA-44188, sebfie provided the MDVA-44818 patch in his gist (44188 <> 44818). Additionally, I can see in the quality patches source code plenty of patches named MDVA-41061, including the V4 (and curiously, also a V6).

> These patches are for opensource version, here are my git patches applied in this order:
> I am on 2.4.4
> https://gist.github.com/sebfie/cacb5410b37af1217c3b6c8d8fbeb11d

I am not sure how stable it is, but I have tested today successfully these patches on a 2.4.4-p2 instance, as suggested by @sebfie:
MDVA-44818_2.4.4
MDVA-44818_1.2.4
ACSD-45488_1.2.2

After setting the configurable product from "Out of stock" to "In stock" in admin, reindexing and flushing caches, the product returned to normal (in stock) in the frontend, as expected.

**Comment by pixiemediaweb** [comment]
For anyone here with 2.4.4-p2, this is the only patch required;

ACSD-45488

Stick it in your env.yaml if you're on Cloud

build:
    QUALITY_PATCHES:
      - ACSD-45488

**Comment by naseeraslam** [comment]
> 

How can we use it?

**Comment by webcreative24** [comment]
The problem is still reproducible after applying the patches if you do a product import with 2.4.4-p2

**Comment by andrewdaluz** [comment]
The patch fix provided here is working for this: https://github.com/magento/inventory/issues/3350
This issue is still present in 2.4.5-p1

**Comment by maxinestewart** [comment]
@andrewdaluz could you confirm which patch from https://github.com/magento/inventory/issues/3350 you used? Lots of mentions of different ones. 
We are also having this issue in 2.4.5-p1

**Comment by softcommerceltd** [comment]
Temporary solution:
https://github.com/softcommerceltd/magento-inventory-configurable-product

**Comment by Velk** [comment]
Hello,
Still present in Magento 2.4.6 after updating stock status with an import : all configurable products are shown as "Out of Stock" on catalog pages but "In Stock" in product pages.

The following SQL command resolve the matter for me (until next stock update ?)

``UPDATE cataloginventory_stock_status INNER JOIN catalog_product_entity ON product_id=catalog_product_entity.entity_id SET stock_status = 1 WHERE type_id = 'configurable';``
