### ISSUE TITLE
Why api tag here?

### ISSUE THREAD

**Issue by wasimhc** [magento/magento2#35722]
https://github.com/magento/magento2/blob/4c36116dcf878e127059d9be9566a119783583f2/app/code/Magento/Store/Model/App/Emulation.php#L15

**Comment by engcom-Hotel** [comment]
Hello @wasimhc,

As per the Magento devdocs, the @api tag indicates the code is part of the public API and is subject to the [Backward Compatibility Policy](https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/).

https://developer.adobe.com/commerce/php/coding-standards/docblock/#api-tag

Please elaborate more on this if we have missed anything.

Thanks

**Comment by wasimhc** [comment]
Ok,  I thought only interface can be an API what I see in other areas of Magento. That's mean this class is an API here. thank you.

**Comment by engcom-Hotel** [comment]
Hi @wasimhc,

We are closing this issue as the raised concern is solved.

Thanks
