### ISSUE TITLE
Image resize from CLI is not working for all media attributes

### ISSUE THREAD

**Issue by amansrivastava** [magento/magento2#3573]
`php bin/magento catalog:images:resize`
When executing this command, only swatch_image and swatch_thumb attributes have resized images and when I looked into code, view.xml in module-swatches being executed rather than view.xml from theme directory.
view.xml exist in blank and luma theme but doesn't impact the output.

**Comment by amansrivastava** [comment]
@MomotenkoNatalia any updates ?

**Comment by MomotenkoNatalia** [comment]
@amansrivastava 
I'm sorry for the delay. Thanks for reporting this issue! 
Internal ticket MAGETWO-50553.

**Comment by cedricblondeau** [comment]
Looks like it has been fixed on develop branch : https://github.com/magento/magento2/commit/53eb7b7569d378c879456cc7e83e85acd6ffadf4#diff-88b36d43a34dcd4d0d151453c13871b6

**Comment by AntonEvers** [comment]
Yes, confirmed. This fixes it. Now just a matter of time :+1:

**Comment by magento-engcom-team** [comment]
@amansrivastava thank you for the report. The fix is available in 2.2.0
