### ISSUE TITLE
Can not Authorize API use because Consumer Key as Expired

### ISSUE THREAD

**Issue by gainesyeild** [magento/magento2#35744]
### Preconditions and environment

- Magento version - V2.1.0
- Anything else that would help a developer reproduce the bug
-Postman Request:
 
POST http://magento2-1.glew.io/oauth/token/request
401
1584 ms
Network
Request Headers
Authorization: OAuth oauth_consumer_key="486mpokb0vpeod2kg5b3qo09mm832wdn",oauth_token="2q1mlu7nxpsg3vwoq25jkd012pw5ft6l",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1657222251",oauth_nonce="s33ncE390jHYOmbFTHhy",oauth_version="1.0",oauth_signature="Ik%2BglC%2FJ3mNEAbvRolLThT2x0eI%3D"
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 7d68e6a4-f5f5-41fd-a694-e392e5b91194
Host: magento2-1.glew.io
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: PHPSESSID=d05cb31afeda7c6684899a2aa3b86bb2; mage-messages=%5B%5D
Content-Length: 0
Response Headers
Date: Thu, 07 Jul 2022 19:30:53 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 38
Connection: keep-alive
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.31
Expires: Wed, 07 Jul 2021 19:30:52 GMT
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Pragma: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

### Steps to reproduce

Trying to run oauth request in Postman

### Expected result

Expecting Auth Tokens

### Actual result

oauth_problem=Consumer+key+has+expired

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @gainesyeild 

Thanks for your contribution and collaboration.

In **`oauth_signature_method`** only **`HMAC-SHA256`** is supported. Kindly refer this [document](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-oauth/) for your reference.
Please use `HMAC-SHA256` in `oauth_signature_method` on latest `2.4-develop branch` and let us know if you face any issue.

Thank you!!

**Comment by engcom-Lima** [comment]
Hi @gainesyeild 

As per your above [comment](https://github.com/magento/magento2/issues/35744#issuecomment-1185929818) your issue issue is resolved and now you are getting another issue related to inventory. 
Kindly create separate issue for it meanwhile our internal team is working on this new issue.

As your issue is resolved now, hence marking this issue as non-issue and closing it.

Thanks
