### ISSUE TITLE
can upload and image into category product  - --so is impossible to show in the front end

### ISSUE THREAD

**Issue by richyarcaika** [magento/magento2#35749]
### Preconditions and environment

Magento ver. 2.4.1
1. GO TO CATEGORIES-> CONTENT-> UPLOAD IMAGE->. SAVE ( every thing looks ok, but i refresh the page and the category does not a hava a n image --- i look in the gallery and the image is there, but the cotegory is not taking the image
2. www.arcaika.com

### Steps to reproduce

GO TO CATEGORIES-> CONTENT->CHOOSE A CATEGORY -> UPLOAD IMAGE->. SAVE ( every thing looks ok, but i refresh the page and the category does not a hava an image --- i looked in the gallery and the image is there, but the category is not taking the image ( is empty like is no image)

I have try to flush cache, flush cage image, reindex, but nothing is working

2. web: www.arcaika.com
what can i do? please help!

### Expected result

upload a image into categories and display the categories images in the front page of my web

### Actual result

images are not geting atached in categories fiels

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @richyarcaika 

Thanks for your contribution and collaboration.
I have tried to reproduce the issue on `2.4-develop` branch but issue not reproducible to me. Below is the information on this:

**Pre-requisite**
1. Fresh magento `2.4-develop` installed.
2. Category should be created.

**Followed below steps:**
1. Login as admin.
3. Catalog >> Categories >> Content > Upload image.
4. Select image and saved it.
5. Go to frontend and click on category.
6. Refresh the page.

Kindly let us know if any thing got missed while reproducing the issue. Please refer [video](https://shared-assets.adobe.com/link/baa34272-f7dc-476d-5f17-c647d04b3d84) for your reference.

**Comment by engcom-Lima** [comment]
Hi @richyarcaika ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.

Thank you.
