### ISSUE TITLE
Feature Request: Grid issues

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#3575]
I don't like UX of Magento 2 grids. 

1) To find some product I need to do the following: 
- click on "filters"
- find Name input and fill in 
- click on "apply filters" button ("enter" does not submit form)
  Why there is no "search by keyword" input (like in Customers or CMS Pages grid)?
  https://s.mail.ru/2vjLSwe7zM5x/img-2016-02-29-11-46-30.png

2) Where there is no inline editor in the Product Grid (like in Customers or CMS Pages grid)? 

3) Why grids display mass-action dropdown even if nothing selected? I think it would better to display mass-action dropdown in some pop-over in floating position, and only if some items are selected. It would make grid pages cleaner and easier to use.

4) There is no need to display pagination block if there is no need to. For example, if I have <20 items, pagination can be hidden.

5) Bookmarks should be always visible and accessible at just one click. 

6) It should also be possible to change the order of bookmarks.

7) Our developers said that new magento grids are complicated to customize. It is difficult to make cell value a link or apply some CSS to a cell.

**Comment by anton-huz** [comment]
> 7) Our developers said that new magento grids are complicated to customize. It is difficult to make cell value a link or apply some CSS to a cell.

I can agree that it could be _difficult_ to do some thing with cell. But currently it is _possible_ to do that from one module in other module's Grid. And it is possible to do it in _maintainable_ way.

Lets start with existed knowledge sources:
- a. [Example of Ui Form](https://github.com/magento/magento2-samples/tree/master/sample-module-form-uicomponent) in magento-samples. Not a Grid as you asked, but an example of extending Ui Component.
- b. [Column Ui Component](http://devdocs.magento.com/guides/v2.0/ui-components/ui-secondary-column.html) is a right place that you developers are looking for.
- c. [Important notes about client-side part](http://devdocs.magento.com/guides/v2.0/ui-components/ui_components_js.html) of Ui Components
- d. When we talk about customizing a _cell_ we want to customize _every cell in a column_. So your developers can take a look on [Column Ui component properties](https://github.com/magento/magento2/blob/develop/app/code/Magento/Ui/view/base/web/js/grid/columns/column.js#L15-L23) and redefine for example `bodyTmpl` with own file and can do different stuff depending own imagination and business needs.

I hope I've gave your devs a topic for investigation ;-)

**Comment by antboiko** [comment]
@stasleo 

Hi Stanislav, thank you for providing your feedback on grids. Please let me comment every item:
**For the 1st and 2nd:**:
_Yes, I agree that currently Product Grid lacks some functionality in comparison to CMS Pages grid or Customers grid. This update is acknowledged and it's in our backlog_
**For the 3rd**:
_I mostly agree. Bulk actions dropdown behavior will be revised_
**For the 4th**:
_It makes sense, but it's better to have consistency in this place. So rather that have table controls appear and disappear based on the items per page setting or the result of filters applied (shifting controls side to side), the pagination control are displayed in place in the controls section of the table, but appear disabled when additional pages are not available to 'page to’_
**For the 5th**:
_I’m not sure I completely understand the request here. I can suppose you mean something like bookmark bar. But this could work not for all cases, especially when user has 10+ saved views (bookmarks)_
**For the 6th**:
_Stanislav, could you please provide some use cases for this one? Do you consider changing the order of bookmarks in a dropdown?_

Thanks,
Anton.

**Comment by stasleo** [comment]
@antboiko 

**For the 5th:**
Yes, I mean bookmarks bar.
Make it responsive. If there is enough space - display them all as a bookmarks bar. If there is not enough space - display all of them in a dropdown list. 

**For the 6th:**
Yes. Our extensions have built-in bookmarks for our clients. These bookmarks are used for different use-cases of the grid usage. We expect that some of the bookmarks will be used frequently, some of them are not so frequent. And we want to display bookmarks in order of usage frequency, not in a-z order.

**For the 7th:**
I think that customization of grids should be much easier. It should be a part of your UX guidelines. There should be some clear and easy way to add a link, to change font-weight, color, background color, add an icon or some other custom element. The current UX guideline is far from good usability. I mean that guideline says that actions (e.g. view, edit, delete) should be put in the last column in a dropdown menu. I think that actions and links to linked entities should always visible and availiabe in just one click.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Grid-issues/idi-p/44749).

**Comment by lucscu** [comment]
i hope someone in magento team take care asap about these entry level features list.
