### ISSUE TITLE
User Getting Auto Logout From My Account Custom Tab In Magento 2.4.3

### ISSUE THREAD

**Issue by rahulrave** [magento/magento2#35761]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rahulrave** [comment]
[Workout.tar.gz](https://github.com/magento/magento2/files/9096840/Workout.tar.gz)

Attached custom module , using this module we are managing custom tab in my account , We are recently updated magneto from 2.3.3 to 2.4.3 , The logout issue is coming after 2.4.2 version.

**Comment by rahulrave** [comment]
@magento give me 2.4-develop instance

**Comment by youngcrush** [comment]
@magento I am working on this

**Comment by youngcrush** [comment]
Hi @rahulrave 
issue is from app/code/Bigdrop/Workout/Block/Custom.php
There is no file Subscription.php in Helper folder. That's why issue is coming. After comment that line page is loaded properly.
![custom-workout](https://user-images.githubusercontent.com/63966602/179042096-1220da73-16d0-4c5d-9fb5-149d6e201221.png)

**Comment by rahulrave** [comment]
@youngcrush 
I was forget to add dependent module called subscription module , Please find in attachment. So enabled that line again and after login you will see custom tabs in my account called BB Challenges , My Custom Workout , if you will click on these tabs and will refresh page again then it will logout automatically.
[Subscription.tar.gz](https://github.com/magento/magento2/files/9114644/Subscription.tar.gz)

**Comment by youngcrush** [comment]
Hi @rahulrave Now we found error again of required Bigdrop\Theme\Setup\AttributeManager. Check again and provide all dependencies

**Comment by rahulrave** [comment]
[Bigdrop.tar.gz](https://github.com/magento/magento2/files/9128377/Bigdrop.tar.gz)
Added all custom modules , Hope it will fix dependency , let me know if you need whole code folder , I will sahre.

**Comment by youngcrush** [comment]
Hi @rahulrave 
I checked in M2.4.3 and there is no issue about auto logout in custom tabs.
https://user-images.githubusercontent.com/63966602/180044822-83473b10-fea0-4d17-98ee-5d6194462ef9.mp4

**Comment by rahulrave** [comment]
@youngcrush for us it's happening , let's us know if you need our instance access or db to reproduce the issue.

**Comment by youngcrush** [comment]
Hi @rahulrave 
ok, Please provide your staging instance and db then I can check properly.

**Comment by engcom-Lima** [comment]
Hi @rahulrave,

Thank you for reporting the issue.
However there are no steps given to reproduce the issue.
Can you please updated the description with exact steps to reproduce the issue.
Also can you please confirm if this issue exists in vanilla Magento 2.4-develop instance.

Thanks

**Comment by rahulrave** [comment]
@engcom-Lima After login in website from front end , In my account you will see BB Challenges , Custom Workout Subscription . Click into this any tab and then again refresh same tab , It will logout to user .
We don;t have vanilla instance for this , I will provide information once I will have.

**Comment by rahulrave** [comment]
> Hi @rahulrave ok, Please provide your staging instance and db then I can check properly.

How I can provide you DB etc in private ? I don't have staging ready for 2.4.3 to reproduce issue.

**Comment by youngcrush** [comment]
@rahulrave you can mail me at choudharyamit664.ac@gmail.com to share info privately and take backup propely.

**Comment by engcom-Lima** [comment]
Hi @rahulrave,

Thank you for the reply however in order to verify if this is a core Magento issue or custom code issue we will need exact reproducible steps on vanilla Magento 2.4-develop instance.
Do let us know the exact steps and I will reverify

Thanks

**Comment by engcom-Lima** [comment]
Hi @rahulrave ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
