### ISSUE TITLE
I cannot open the Catalog tab under my profile  - Could you please debug 

### ISSUE THREAD

**Issue by Chrischapot** [magento/magento2#35764]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

![image](https://user-images.githubusercontent.com/109213974/178707596-267d9283-c877-4b08-9a2c-ef0506bf2c5b.png)
![M2](https://user-images.githubusercontent.com/109213974/178707715-a9bad253-89a1-41b7-97c3-ae238ec8521d.PNG)

### Expected result

Cannot visualise catalog product from ZAGG

### Actual result

.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Chrischapot ,
Thank you for reporting and collaboration. This is an intermittent issue which cannot be reproduced frequently on 2.4-develop branch. However this has been confirmed here: https://github.com/magento/magento2/issues/35466. We are closing this issue as duplicate. Kindly move onto this issue for latest updates / solutions on the same.
FYI..as a temporary workaround, please check below possible solutions that may help you resolve the issue for now:
1. Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
    UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
2. Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
3. Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.

Thank you.

**Comment by Chrischapot** [comment]
Hello,

Could yo please find a way to resolve this issue as it bugged - See the print screen, there is no numbers and access for me to do anything ?
How do we do that - Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.
***@***.***
Please advise !
Kind Regards

**Comment by Chrischapot** [comment]
Issue not closed as unresolved - please revert some instruction as this is stopping me to help customer
Many thanks

**Comment by engcom-November** [comment]
Hi @Chrischapot ,
"TRUNCATE ui_bookmark; " is a sql query and should be run in any database sql editor. Please refer the screenshot of steps to switch to the DB and sql query ran.
![image](https://user-images.githubusercontent.com/60198231/183394707-9410823f-ef20-4a9f-99d9-47a4fe6fe5ac.png)
This issue has been confirmed here: https://github.com/magento/magento2/issues/35466. Kindly move onto this issue for latest updates / solutions on the same.
