### ISSUE TITLE
Unable to update cart item's custom option values with REST API

### ISSUE THREAD

**Issue by seungwooc-23** [magento/magento2#35768]
### Preconditions and environment

- Magento CE version 2.4.4
- Component: REST API

### Steps to reproduce

1. Create a simple product in the catalog with a customizable option

Using the Magento REST API:

2. Create a cart for checkout (`POST /rest/default/V1/guest-carts/`) and add a cart item of the product created in step 1
```
POST /rest/default/V1/guest-carts/{cartId}/items request body:
{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1, 
                        "option_value": "1"
                    }
                ]
            }
        }
    }
}
```

3. Specify a new option_value in the payload and perform `PUT /rest/default/V1/guest-carts/{cartId}/items/{itemId}` with the following request body:
```
{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1,
                        "option_value": 999
                    }
                ]
            }
        }
    }
}
```
5. Retrieve the cart items by doing a GET on `rest/default/V1/guest-carts/{cartId}/items/`

### Expected result

The custom option_value for the option_id should be updated after step 3.

### Actual result

Only the custom option_value of the first-added cart item does not get updated after the PUT request. 

### Additional information

I've reproduced this behavior on the `2.4-develop` branch using the instance provided by magento-deployment-service 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @seungwooc-23 

Kindly elaborate more about your steps to reproduce for ex-What option type you have choosed to create customizable options of simple product , your `post` method request body and also provide screeshots of the response that you are getting.

Thank you!!

**Comment by seungwooc-23** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by seungwooc-23** [comment]
Hi @engcom-Lima,

* The option type chosen is the Text Field type
* The cart item addition is 
```json
POST https://7f9f88ea28e9b8b7a2a492289744a5e4.instances.magento-community.engineering/rest/default/V1/guest-carts/g2QC7We6LJGkomp9XI2Tj8ZTjo3Edgtq/items

Request body:
{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1, 
                        "option_value": 1
                    }
                ]
            }
        }
    }
}```

* Cart update call is:
```json
PUT https://7f9f88ea28e9b8b7a2a492289744a5e4.instances.magento-community.engineering/rest/default/V1/guest-carts/g2QC7We6LJGkomp9XI2Tj8ZTjo3Edgtq/items/5

Request body:
{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1, 
                        "option_value": "9999"
                    }
                ]
            }
        }
    }
}
```

* List the items on the cart to verify its items:
```json
GET https://7f9f88ea28e9b8b7a2a492289744a5e4.instances.magento-community.engineering/rest/default/V1/guest-carts/g2QC7We6LJGkomp9XI2Tj8ZTjo3Edgtq/items/

Response:
{
    "item_id": 5,
    "sku": "24-MB01",
    "qty": 1,
    "name": "Joust Duffle Bag",
    "price": 34,
    "product_type": "simple",
    "quote_id": "3",
    "product_option": {
        "extension_attributes": {
            "custom_options": [
                {
                    "option_id": "1",
                    "option_value": "1"
                }
            ]
        }
    }
}
```

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Unable to update cart item's custom option values with REST API.

**Pre-requisite:**
Clean magento should be installed `2.4-develop`

**Steps to reproduce:**

1. Create simple product using customizable option (text as option type).
2. Add product to the cart using guest.
3. Go to db capture quote id masked.
4. Using post request >> add product to the cart `/rest/default/V1/guest-carts/[quoteid_masked]/items`
**Request body:**
```
`{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1, 
                        "option_value": 1
                    }
                ]
            }
        }
    }
}`
```
5. Update the cart using put method: /rest/default/V1/guest-carts/[quoteid_masked]/items/[itemid]
**Request body:**
```
{
    "cartItem": {
        "sku": "24-MB01",
        "qty": 1,
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": 1, 
                        "option_value": "9999"
                    }
                ]
            }
        }
    }
}

```

**Expected result:** Option value should be updated.
**Actual result:** Option value was not updated.
**Screenshot**
![Screenshot from 2022-07-19 13-32-47](https://user-images.githubusercontent.com/60198022/179705027-3b27cda8-9d57-44c9-915b-4a0faefddd1b.png)

Hence, confirming the issue.

**Comment by hostep** [comment]
Closed without a comment?
But I see a bunch of commits mentioning AC-5986, here's the merge commit:  https://github.com/magento/magento2/commit/70b864f4b103800784397f14b2887b25e619fad3, so that's probably the fix

**Comment by engcom-Hotel** [comment]
Hello 

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5986 by the internal team.
Related commits: https://github.com/magento/magento2/search?q=AC-5986&type=commits

Thanks
