### ISSUE TITLE
Inventory Endpoint Not Working

### ISSUE THREAD

**Issue by gainesyeild** [magento/magento2#35778]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Request and Response Message:
GET https://magento2-1.glew.io/rest/default/V1/inventory/source-items
Authorization: OAuth oauth_consumer_key="486mpokb0vpeod2kg5b3qo09mm832wdn",oauth_token="2q1mlu7nxpsg3vwoq25jkd012pw5ft6l",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1657918559",oauth_nonce="h0P0zYZTxRmrWHGZR0eY",oauth_version="1.0",oauth_signature="S43o9n57MI%2BTqVQU78BLNa77qbQ%3D"
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 33e75b1c-6c7c-469d-b1fc-75e571f5243f
Host: [magento2-1.glew.io](http://magento2-1.glew.io/)
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: mage-messages=%5B%5D
 
HTTP/1.1 404 Not Found
Date: Fri, 15 Jul 2022 20:56:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 60
Connection: keep-alive
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.31
Set-Cookie: PHPSESSID=ad1efb77e8af5bbbe38344cbf2e2c1ad; expires=Fri, 15-Jul-2022 21:56:04 GMT; Max-Age=3600; path=/; domain=[magento2-1.glew.io](http://magento2-1.glew.io/); HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache

### Expected result

Expected Inventory payload 

### Actual result

Request does not match any route 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gainesyeild** [comment]
HI,

I am having trouble understanding a few of the items. Firstly, I thought
this was a Rest API and I am wondering why I need to install the Magento
package. I can successfully hit other endpoints just not Inventory or
Refunds. Second, what did you do in step 2? Third, I could never get the
generate tokens endpoint to work which is why I have to do it for each
endpoint.

I am using this:
https://magento.redoc.ly/2.3.7-admin/tag/inventorystocks/#operation/inventoryApiStockRepositoryV1GetListGet
as documentation. Do you have a more indepth documentation that developers
can use? This might help me in understanding all of my above comments.

Thank you,

Gaines

**Comment by gainesyeild** [comment]
Hi,

I attempted your steps and I am still getting "Request does not match any
route." In my Postman request. Has this not been released yet?

**Comment by danielgoodwin97** [comment]
@gainesyeild I'm having the same issue - were you ever able to figure out what was up here?
