### ISSUE TITLE
Megento 2.3 Sales Confirugation Not Saving

### ISSUE THREAD

**Issue by haroonsulahri** [magento/magento2#35785]
Hi,
My site sales configuration not saving after changing.We tired to fix this issue.

**Comment by engcom-Hotel** [comment]
Dear @haroonrajpoot,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
