### ISSUE TITLE
Can't create a credit memo with qty 0

### ISSUE THREAD

**Issue by MarcusWolschon** [magento/magento2#35787]
### Preconditions and environment

- Magento version 2.4.3-p2

### Steps to reproduce

1. Create an order
2. pay the order
3. invoice the order
4. enter the credit memo screen
5. enter qty=0
6. press "updaste QTY's"

### Expected result

The "subtotal" updates to 0 and the "refund offline" button is enabled as long as the grand total (including shipping and adjustments) of the refund is >0

### Actual result

The subtotal does not update at all and the "refund offline" button is greyed out

### Additional information

No workaround is known to create the correct refund (e.g. becase a product had a slight defect) and then ship all the ordered products.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @MarcusWolschon,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
