### ISSUE TITLE
Magento unable to reindex bundle product not assigned to any sait (DisabledProductOptionPriceModifier.php on line 117).

### ISSUE THREAD

**Issue by pret1** [magento/magento2#35796]
**Preconditions**
Install Magento 2.4-develop with sample data.
 
**Issue** 
product price index (catalog*product*price) not working if bundle product not assigned to any website 
 
**Steps To Reproduce**
1)Go to admin ->catalog ->products -> create new bundle Or edit existing bundle product 
2)"Product in Websites" Tab  -> uncheck all checkboxes (website) and save the product 
3)Perform reindex 

 
**Expected result**
Reindex should be performed successfully 
 
**Actual result**
We get the below error while running the product price index
 
```java
Warning: Undefined array key <bundel product id > in vendor/magento/module-bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php on line 117
```

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Magento unable to reindex `catalog_product_price` for bundle prioduct when we are not selecting any websites. 

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Create bundle product
2. In bundle product  go to tab "Product in Websites"  & uncheck the Websites.
3. Click save & close.
4. In CLI enter bin/magento indexer:reindex catalog_product_price

**Expected result:** Reindex success and catalog_product_price have a status ready.
**Actual result:** Reindex was not successfull and getting error as below screenshot:

<img width="945" alt="reindex_issue" src="https://user-images.githubusercontent.com/60198022/180753175-dc06c0a3-73ca-4a15-91ed-6efc6612143e.png">

**Additionally tested :**
Also tested with other type of products like simple,configurable etc.
Hence, confirming the issue.

**Comment by artskirk** [comment]
@magento I am working on this

**Comment by chittima** [comment]
Internal team is working on this issue

**Comment by hostep** [comment]
@chittima, @sdzhepa: can you please explain why this issue got closed?

**Comment by chittima** [comment]
Issue is already fixed in the develop branch and not reproducible anymore. Here is the commit https://github.com/magento/magento2/commit/0d90748aa1dd76581b8a3dbf34b5ce82961d9902
