### ISSUE TITLE
An error has happened during application run. See exception log for details.

### ISSUE THREAD

**Issue by surajkurudiyar** [magento/magento2#35795]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

![image](https://user-images.githubusercontent.com/109786023/180380049-6b6a20ea-50e6-4042-b22b-2e369800b50d.png)

 Everyday and every time it is happening. 

Please help to resolve this issues permanently

### Steps to reproduce

httpsd://www.scrollnshops.com 

click on any tab 

You will find the error

### Expected result

page products is not visible

### Actual result

Product page is not visible

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @surajkurudiyar ,

Kindly discuss your magento related issue only and provide exact steps and screenshots to reproduce the issue.
Please go through the [system requirement](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) docs and try to make your setup according to it. Meanwhile you should have all the folder related permissions for your instance instance folder.

Thanks

**Comment by engcom-Lima** [comment]
Hi @surajkurudiyar ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
