### ISSUE TITLE
As a developer I want to query the current store category tree without providing the root_category_uid, so that can prevent a roundtrip

### ISSUE THREAD

**Issue by paales** [magento/magento2#35799]
*As a developer I want to query the current store category tree without providing the root_category_uid, so that can prevent a roundtrip*

Currently we have to run two queries:

```graphql
query StoreConfig {
  storeConfig {
    root_category_uid
  }
}
```

With that query we can get the root_category_uid and we use that to query the categories:

```graphql
query Categories($root: String!) {
  categories(filters: {parent_category_uid: {eq: $root}}) {
    items {
      url_path
    }
  }
}
```

### AC

* Be able to get a category tree for the current store view without providing the root_category_uid

### Approved Schema

```graphql
extend input CategoryFilterInput {
   parent_root_category: Boolean
} 
```

**Comment by engcom-November** [comment]
Hi @paales ,
Thank you for reporting and collaboration. As per the Magento [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/queries/store-config.html) StoreConfig Graphql query can contain "root_category_uid" attribute which is an existing behavior of Magento. Hence changing this feature can be considered as a Feature request but not a bug. Hence labelling this is as Feature request.

**Comment by paales** [comment]
Investigating if the following is sufficient, this seems to be undocumented.

If the categories query is called without any arguments it seems it will return the categories from the store group's root: 

```graphql
query CategoriesWithoutArguments {
  categories {
    items {
      uid #The root category
      url_path #null
      children {
        url_path
      }
    }
  }
}
```
