### ISSUE TITLE
Magento Connector Issue with VAT

### ISSUE THREAD

**Issue by nikkicheng93** [magento/magento2#35791]
### Preconditions and environment

- Magento version 2.4.3

We have a Vertex VAT customer. The issue is Magento has the product (Junior Maxi, product class 001) price of $54 which includes tax. When we checkout the product, Magento is adding the tax back onto the total price. On Vertex side, we have taxindicator set to true. We thought maybe there could be a setting within Magento to get around this. Please see the XML attached.

In order to use Vertex to calculate taxes, Price Display Settings must be set to Excluding Taxes. 
![Excluding](https://user-images.githubusercontent.com/109740821/180220311-c4829493-1da0-49e2-a4d3-1e148a112882.PNG)

### Steps to reproduce

[Quotation Response.txt](https://github.com/magento/magento2/files/9159523/Quotation.Response.txt)
[Quotation Request.txt](https://github.com/magento/magento2/files/9159528/Quotation.Request.txt)

1. Add product to Shopping Cart
2. View Basket
3. Taxes are being added on top of Product that has price included

### Expected result

1. Add product to Shopping Cart
2. View Basket
3. Product is the same price as displayed with no additional taxes

### Actual result

1. Add product to Shopping Cart
2. View Basket
3. Taxes are being added on top of Product that has price included

On Magento side, is there a tax included indicator that can be added? Magento is taking the Vertex result and adding it on top.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @nikkicheng93 ,
We tried to reproduce the issue on magento 2.4 instance and 2.4.4 instance ,but facing different error after successful installation of vertex module . 
While landing on Stores-->configuration--> Sales--> Tax

<style>.highlighted { background-color: #DFF7FF!important; }</style>
<form action="http://local.magento244.com/index.php/admin/admin/system_config/save/key/b51705d1d45f802cd76d7ac25aa045e65f684026ea3b4027efd65e7d1606f71a/section/tax/" method="post" id="config-edit-form"
      enctype="multipart/form-data">
    <div><input name="form_key" type="hidden" value="DacZ2PyIOt93Wir8" /></div>
    <div class="accordion">
        An error has happened during application run. See exception log for details
        
     **Exception log:**
[2022-07-26T17:18:38.989493+00:00] main.CRITICAL: Error: Cannot instantiate interface Vertex\RequestLoggingApi\Model\LogRequestInterface in /opt/homebrew/var/www/magento244/2.4.4/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /opt/homebrew/var/www/magento244/2.4.4/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Vertex\\RequestL...', Array)

**Comment by nikkicheng93** [comment]
Customer is on Magento version 2.4.3-p1, so we did not have to install the connector. It was already part of the Taxes screen. Vertex is part of Magento on version 2.4.3-p1, so I do not know why you are not seeing that screen.

**Comment by nikkicheng93** [comment]
@engcom-Delta Here is the Vertex documentation install guide. But customer is on Magento version 2.4.3-p1, so we did not have to install the connector. It was already part of the Taxes screen. Vertex is part of Magento on version 2.4.3-p1, so I do not know why you are not seeing that screen.

[Integration Guide - Vertex Tax Links for Magento 2 - 4.2.0.pdf](https://github.com/magento/magento2/files/9193219/Integration.Guide.-.Vertex.Tax.Links.for.Magento.2.-.4.2.0.pdf)

**Comment by kenit** [comment]
I can fix this issue by adding a if/else check to the Vertex\Tax\Model\Calculator class, line 444 to 447.
If the value of config 'tax/calculation/price_includes_tax' is true, the code should be 
```
->setPrice($this->optionalRound($unitPrice - $perItemTax, $round))
->setPriceInclTax($this->optionalRound($unitPrice, $round))
->setRowTotal($this->optionalRound($extendedPrice  - $vertexLineItem->getTotalTax(), $round))
->setRowTotalInclTax($this->optionalRound($extendedPrice, $round))
```

**Comment by engcom-Delta** [comment]
Hi @nikkicheng93 ,
Thank you for your update and inputs . Starting with the 2.4.4 release, this extension is no longer bundled with the core release and must be installed and updated from the Commerce Marketplace or directly from the vendor. [Contact Vertex](https://marketplace.magento.com/partner/vertex_inc) for information about the extension and documentation.

Link  for reference # https://docs.magento.com/user-guide/tax/taxes.html.

Kindly contact Vertex developers for further action.

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
