### ISSUE TITLE
Magento Amazon Extension fails to install if the database has a PREFIX 

### ISSUE THREAD

**Issue by adrianbsystems** [magento/magento2#35792]
### Preconditions and environment

- Magento version : 2.4.4
- Environment:
Fresh install Magento CE 2.4.4
No other third party extensions, default Luma theme
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Steps to replicate:
composer require magento/module-amazon
composer require magento/services-connector
php bin/magento setup:upgrade

### Expected result

Expected result: setup completes normally

### Actual result

Actual Result:
Unable to apply patch Magento\Amazon\Setup\Patch\Schema\DropUnnecessaryIndexesLeftFromOldSchema for module Magento_Amazon. Original exception message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.channel_amazon_account' doesn't exist, query was: SHOW INDEX FROM channel_amazon_account

### Additional information

If the database PREFIX is manually added the the files below, setup completes successfully, But this seems not the correct procedure ?

/vendor/magento/module-amazon/Setup/Patch/Schema/DropUnnecessaryIndexesLeftFromOldSchema.php

/**
* @var ModuleDataSetupInterface $moduleDataSetup
*/
private $moduleDataSetup;

private $indexesToDelete = [
    'nY3g_channel_amazon_account' => [
        'CHANNEL_AMAZON_ACCOUNT_UNIQUEVALUE' => 'unique',
        'MERCHANT_ID_MERCHANT_ID' => 'index',
    ],
    'nY3g_channel_amazon_account_listing' => [
        'CHANNEL_AMAZON_ACCOUNT_LISTING_UNIQUEVALUE' => 'unique',
        'MERCHNAT_ID_MERCHANT_ID' => 'index',
    ],
    'nY3g_channel_amazon_account_order' => [
        'CHANNEL_AMAZON_ACCOUNT_ORDER_UNIQUEVALUE' => 'unique',
        'MERCHNAT_ID_MERCHANT_ID' => 'index',
    ],
    'nY3g_channel_amazon_action' => [
        'CHANNEL_AMAZON_ACTION_UNIQUEVALUE' => 'unique',
        'CHANNEL_AMAZON_ACTION_UNIQUEVALUE_COMMAND' => 'unique',
    ],
    'nY3g_channel_amazon_attribute' => [
        'AMAZON_ATTRIBUTE_AMAZON_ATTRIBUTE' => 'index',
        'CHANNEL_AMAZON_ATTRIBUTE_UNIQUEVALUE' => 'unique',
        'ID_ID' => 'index',
    ],
    'nY3g_channel_amazon_attribute_value' => [
        'ASIN_ASIN' => 'index',
        'CHANNEL_AMAZON_ATTRIBUTE_VALUE_UNIQUEVALUE' => 'unique',
        'ID_ID' => 'index',
        'PARENT_ID_PARENT_ID' => 'index',
    ],
    'nY3g_channel_amazon_defect' => [
        'CHANNEL_AMAZON_ACCOUNT_DEFECT_UNIQUEVALUE' => 'unique',
    ],
    'nY3g_channel_amazon_error_log' => [
        'ID_ID' => 'index',
    ],
    'nY3g_channel_amazon_listing' => [
        'ASIN_ASIN' => 'index',
        'CATALOG_PRODUCT_ID_CATALOG_PRODUCT_ID' => 'index',
        'CHANNEL_AMAZON_ACCOUNT_LISTING_UNIQUEVALUE' => 'unique',
        'CONDITION_CONDITION' => 'index',
        'IS_SHIP_IS_SHIP' => 'index',
        'LISTING_ID_LISTING_ID' => 'index',
        'LIST_STATUS_LIST_STATUS' => 'index',
        'MERCHANT_ID_MERCHANT_ID' => 'index',
    ],
    'nY3g_channel_amazon_listing_log' => [
        'ID_ID' => 'index',
    ],
    'nY3g_channel_amazon_listing_multiple' => [
        'CHANNEL_AMAZON_LISTING_MULTIPLE_UNIQUEVALUE' => 'unique',
    ],
    'nY3g_channel_amazon_listing_rule' => [
        'MERCHANT_ID_MERCHANT_ID' => 'index',
    ],
    'nY3g_channel_amazon_listing_variant' => [
        'CHANNEL_AMAZON_LISTING_VARIANT_UNIQUEVALUE' => 'unique',
    ],
    'nY3g_channel_amazon_order' => [
        'CHANNEL_AMAZON_ORDER_UNIQUEVALUE' => 'unique',
        'ORDER_ID_ORDER_ID' => 'index',
    ],
    'nY3g_channel_amazon_order_item' => [
        'CHANNEL_AMAZON_ORDER_ITEM_UNIQUEVALUE' => 'unique',
        'ORDER_ID_ORDER_ID' => 'index',
    ],
    'nY3g_channel_amazon_order_reserve' => [
        'CHANNEL_AMAZON_ORDER_RESERVE_UNIQUEVALUE' => 'unique',
        'ORDER_ID_ORDER_ID' => 'index',
    ],
    'nY3g_channel_amazon_order_tracking' => [
        'ORDER_ID_ORDER_ID' => 'index',
    ],
    'nY3g_channel_amazon_pricing_bestbuybox' => [
        'ASIN_ASIN' => 'index',
        'CHANNEL_AMAZON_PRICING_BESTBUYBOX_UNIQUEVALUE' => 'unique',
        'COUNTRY_CODE_COUNTRY_CODE' => 'index',
    ],
    'nY3g_channel_amazon_pricing_index' => [
        'ASIN_ASIN' => 'index',
        'CHANNEL_AMAZON_PRICING_INDEX_UNIQUEVALUE' => 'unique',
        'CONDITION_CONDITION' => 'index',
        'ID_ID' => 'index',
        'PARENT_ID_PARENT_ID' => 'index',
        'PRODUCT_ID_PRODUCT_ID' => 'index',
        'SHIPPING_CALCULATED_SHIPPING_CALCULATED' => 'index',
        'STOP_RULES_STOP_RULES' => 'index',
    ],
    'nY3g_channel_amazon_pricing_lowest' => [
        'ASIN_ASIN' => 'index',
        'COUNTRY_CODE_COUNTRY_CODE' => 'index',
    ],
    'nY3g_channel_amazon_pricing_rule' => [
        'ID_ID' => 'index',
    ],
    'nY3g_channel_amazon_quantity_index' => [
        'CHANNEL_AMAZON_QUANTITY_INDEX_UNIQUEVALUE' => 'unique',
        'ID_ID' => 'index',
    ],
];

/vendor/magento/module-amazon/Setup/Patch/Schema/DropLegacyPreV4Columns.php

/**
 * @var ModuleDataSetupInterface $moduleDataSetup
 */
private $moduleDataSetup;

private $columnsToDrop = [
    ['table' => 'nY3g_channel_amazon_account', 'column' => 'setup_step'],
    ['table' => 'nY3g_channel_amazon_action', 'column' => 'api_group'],
    ['table' => 'nY3g_channel_amazon_action', 'column' => 'api_action'],
    ['table' => 'nY3g_channel_amazon_action', 'column' => 'api_content'],
];

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @adrianbsystems ,

Thank you for reporting and collaboration. 
Amazon Integration is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page.

Thank you.
