### ISSUE TITLE
Guest cart/queue from store 1 does not works when logging in store 2 (share customer account=global)

### ISSUE THREAD

**Issue by tales-desde-mileto** [magento/magento2#35809]
### Preconditions and environment

- Magento version :  Magento ver. 2.4.4
- 2 websites
- Conf. "Share Customer Accounts" : GLOBAL

### Steps to reproduce

1. Two websites: w1 and w2
2. As guest, add item1 in w1 to cart.
3. Change website to w2
4. Loggin in w2
5. Change website to w1
6. Checkout : "/checkout/#shipping" show always this error: "current customer does not have an active cart."
Quote table:
select entity_id, store_id, customer_id, customer_email, customer_is_guest from quote;
+-----------+----------+-------------+--------------------------------+-------------------+
| entity_id | store_id | customer_id | customer_email                 | customer_is_guest |
+-----------+----------+-------------+--------------------------------+-------------------+
|        87 |        1 |        NULL | NULL                           |                 1 |
|        88 |        2 |         201 | xxx@xxx.com |                 0 |
+-----------+----------+-------------+--------------------------------+-------------------+
2 rows in set (0.000 sec)

7. If you add a item in w1, then the queue is like:
select entity_id, store_id, customer_id, customer_email, customer_is_guest from quote;
+-----------+----------+-------------+--------------------------------+-------------------+
| entity_id | store_id | customer_id | customer_email                 | customer_is_guest |
+-----------+----------+-------------+--------------------------------+-------------------+
|        87 |        1 |         201 | xxx@xxx.com |                 1 |
|        88 |        2 |         201 | xxx@xxx.com |                 0 |
+-----------+----------+-------------+--------------------------------+-------------------+

But look customeris_guest = 1
When you select a address (you need one create save) always show this error:
The shipping information was unable to be saved. Error: "Invalid customer address id 402"
This is becouse It is checking customer_is_guest in:
$this->doValidate($address, $cart->getCustomerIsGuest() ? null : $cart->getCustomer()->getId());

### Expected result

1. When logging, both queue (from w1 and from w2) should work. 
1.1. queue should have in both stores correct values from: customer_id, customer_email and customer_is_guest
3. If I add new product, the the value of customer_is_guest is wrong.
4. Any guest queue/cart in any store should be correct when I log in.

### Actual result

Under these conditions I cannot finalize the sale

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @tales-desde-mileto ,
Thank you for raising an issue . We tried to reproduce the issue on magento 2.4 develop , We can't share accounts to Global.Please provide further information.
 Refer the attached screenshot.
<img width="929" alt="25" src="https://user-images.githubusercontent.com/51681379/180933721-b5c48308-f18f-4a0a-a3a1-7dcd9698a38d.png">

**Comment by tales-desde-mileto** [comment]
Hi:
You can't share accounts like Global probably because in your environment you have the same email on both websites (you have the "per website" setting).
You will be able to change it if you have a clean Magento 2.4.4. Or if you have an environment without the same customer email registered on more than one website.
You can find these customers with this query:
select email, count(website_id) from customer_entity group by email having count(*) > 1;

I understand that in a clean environment you should not have this problem.

Thanks in advance

**Comment by engcom-Delta** [comment]
Hi @tales-desde-mileto ,
Thank you for reporting and collaboration, We have verified the issue on magento 2.4 dev instance , but  issue is not reproducible . 

Please find the steps followed. correct me if i am wrong.

1. .share Accounts = Global

![Screenshot (354)](https://user-images.githubusercontent.com/51681379/181178823-379272da-4b05-405c-b6f4-356963e87783.png)

2. 2.Add a product as a guest in Website 1

![Screenshot (361)](https://user-images.githubusercontent.com/51681379/181178871-d53f1a5c-98cd-4bcc-8e4f-859f6194b46d.png)

3. Logging in Website 2

![Screenshot (356)](https://user-images.githubusercontent.com/51681379/181179085-4e5eac0b-2d0a-4ac6-96c3-957d451e7c44.png)

4. in Website 1 Go to checkout page

![Screenshot (362)](https://user-images.githubusercontent.com/51681379/181179330-161ba587-893c-4e8e-9266-0c61785757ca.png)

5. We are able to save the address and able to place the order

![Screenshot (364)](https://user-images.githubusercontent.com/51681379/181179472-38f69c6f-003a-4f3c-84d2-d0a4fa68434d.png)

Regards,

**Comment by engcom-Bravo** [comment]
Hi @tales-desde-mileto,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
