### ISSUE TITLE
Elasticsearch memory issues in jvm.options

### ISSUE THREAD

**Issue by abdulrj009** [magento/magento2#35813]
### Summary (*)

I have issue in elasticsearch memory I tried 100 times also increase that xms and xmx in jvm.options it work for a little bit and again the same issue because of this I am not able to  reindex the catalog and face many issues in websites please help me to resolve this 
### Examples (*)

elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-07-25 12:47:22 UTC; 3h 35min ago
       Docs: https://www.elastic.co
    Process: 1434466 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elastic>
   Main PID: 1434466 (code=exited, status=1/FAILURE)
### Proposed solution

I need to solve this because I am tried 100 times please help me to resolve it
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [s3 ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @abdulrj009,

Thanks for the collaboration!

I suggest you to please go through with the below articles in order to resolve this issue:

- https://devdocs.magento.com/cloud/project/services-elastic.html
- https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html
- https://www.elastic.co/guide/en/cloud-enterprise/2.1/ece-prereqs.html

And also please let us know more about your environment like OS, Number of catalogs present in the instance etc.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @abdulrj009,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
