### ISSUE TITLE
Space is missed

### ISSUE THREAD

**Issue by xdoctordog** [magento/magento2#35828]
https://github.com/magento/magento2/blob/2e45de7acefbd665ffa90c5e24dda6a5286c36ee/app/code/Magento/Customer/Model/EmailNotification.php#L130

**Comment by engcom-Delta** [comment]
Hi @xdoctordog ,

Thank you for raising an issue , Please provide issue description, steps to reproduce , actual results , expected results and screenshots if required.

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
