### ISSUE TITLE
Allow to translate texts in English in live search

### ISSUE THREAD

**Issue by agaraban** [magento/magento2#35831]
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug
-
Right now we are trying to translate "View All" and "Suggestions" in autocomplete, but we realized that this sec element is created by jaavscript and comes from an external magento service. We want to know if they are going to release a fix to solve this issue for multilanguage pages.

### Steps to reproduce

Right now we are trying to translate "View All" and "Suggestions" in autocomplete, but we realized that this sec element is created by jaavscript and comes from an external magento service. We want to know if they are going to release a fix to solve this issue for multilanguage pages.

### Expected result

Right now we are trying to translate "View All" and "Suggestions" in autocomplete, but we realized that this sec element is created by jaavscript and comes from an external magento service. We want to know if they are going to release a fix to solve this issue for multilanguage pages.

### Actual result

Right now we are trying to translate "View All" and "Suggestions" in autocomplete, but we realized that this sec element is created by jaavscript and comes from an external magento service. We want to know if they are going to release a fix to solve this issue for multilanguage pages.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @agaraban ,
Thank you for raising an issue , It seems actual results and expected are same in provided issue description. Hence kindly provide the expected results and actual results.

Regards,

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
