### ISSUE TITLE
i

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35830]

**Comment by engcom-Delta** [comment]
Hi @shannonearley ,
Thank you for raising an issue , We are happy to assist you but Please provide more details like which version of Magento to replicate this issue.

Regards,

**Comment by devchris79** [comment]
You are asking for trouble posting a customers address, phone number, who they ordered from etc on a public forum.

What is in the Sales->Orders page ? It may be that the customer checked out as a guest not realising they had an account or used another set of details.

**Comment by engcom-Delta** [comment]
Hi @shannonearley ,

May I have update on this issue please ?

Thanks
