### ISSUE TITLE
Site cannot handle Braintree API services being down

### ISSUE THREAD

**Issue by aliomattux** [magento/magento2#35841]
### Preconditions and environment

- Magento version
- 2.4.4
- Production environment.
- PHP 7.4
- Braintree extension installed and configured
Nginx webserver + PHP-FPM
64 core physical server

### Steps to reproduce

Reproduction of this issue is only possible when Braintree API services are not available. Prerequisite to the test is ensuring the unavailability of the stated service.

As a test, on your webserver, edit /etc/hosts.
create an entry with an invalid ip address for api.braintreegateway.com. Save the file

Navigate the site, add to cart. Try to go to cart.
Add to cart does not work. The page refreshes as if it added to cart, but it did not
Navigation to cart is not possible. Clicking on cart button will result in an infinite load

As these requests build up and are held, the max out the php connections, causing the entire webserver to crash. Sort of pathetic.

### Expected result

Payment cannot be taken but the site will still operate, and navigation to the cart and checkout is possible.

### Actual result

Nginx/php connections build up until they are maxed out. The site crashes and a bad gateway error is returned permanently until nginx is restarted.

Here are entries from nginx error.log

2022/07/28 15:11:05 [error] 2735#2735: *51548 connect() to unix:/run/php/php7.4-fpm.sock failed (11: Resource temporarily unavailable) while connecting to upstream
2022/07/28 15:11:18 [crit] 2734#2734: accept4() failed (24: Too many open files)
2022/07/28 15:11:18 [alert] 2734#2734: *53632 socket() failed (24: Too many open files) while connecting to upstream,

Corresponding entries from Magento 2 exception.log

[2022-07-28T19:16:26.363608+00:00] main.ERROR: Failed to connect to api.braintreegateway.com port 443: Connection refused [] []
[2022-07-28T19:16:26.439427+00:00] main.ERROR: Failed to connect to api.braintreegateway.com port 443: Connection refused [] []
[2022-07-28T19:17:01.453394+00:00] main.ERROR: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.braintreegateway.com:443  [] []
[2022-07-28T19:17:01.721655+00:00] main.ERROR: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.braintreegateway.com:443  [] []

### Additional information

https://www.paypal-status.com/history/production
Look at July 28th

Due to the nature of the problem it is likely that several if not all payment gateway services will affect the availability of the site. The sites ability to operate should not depend on the availability of an external api thats only purpose is to collect card data.

### Release note

The only work around is to disable the Braintree module until the service becomes available.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aliomattux** [comment]
IMO, this is a critical problem. Magento must not depend on the availability of an external service in order to operate. Every website running Magento and using an external payment gateway is vulnerable to the site becoming entirely inoperable if any of the configured gateways are become unavailable for any reason.

**Comment by engcom-Bravo** [comment]
HI @aliomattux ,

Thanks for contribution and collaboration.

According to system requirement [document](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) of Magento we should use Php 8.1 for `2.4.x` version. Kindly refer the document.
Let us Know if you are facing any Issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @aliomattux,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
