### ISSUE TITLE
the Rollback function in Magento 2.4.3 is not working, when I press the button nothing happens

### ISSUE THREAD

**Issue by malyoussef** [magento/magento2#35855]
### Preconditions and environment

- Magento version 2.4.3
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

the Rollback function in Magento 2.4.3 is not working, when I press the button nothing happens

### Expected result

the Rollback function in Magento 2.4.3 is not working, when I press the button nothing happens

### Actual result

the Rollback function in Magento 2.4.3 is not working, when I press the button nothing happens

### Release note

the Rollback function in Magento 2.4.3 is not working, when I press the button nothing happens

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4.3 instance

**Comment by engcom-Bravo** [comment]
Hi @malyoussef,
Thank you for raising an issue , It seems actual results and expected are same in provided issue description. Hence kindly provide the exact steps to reproduce, expected results ,actual results and screenshots if required.

Regards.

**Comment by engcom-Bravo** [comment]
Hi @malyoussef,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
