### ISSUE TITLE
NewRelic Wrapper is not allowing to capture TypeError

### ISSUE THREAD

**Issue by rmsundar1** [magento/magento2#35854]
### Summary (*)
In the current newrelic wrapper class, we are can capture only the `\Exception` however when we try to capture any TypeError it's giving the below exception

NewRelic agent supports capturing any kind of Throwable errors ref: https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error, so upgraded the NewRelicWrapper class to support any throwable type exceptions.

### Examples (*)
```
[2022-07-26T17:21:39.757093+00:00] report.CRITICAL: TypeError: Argument 1 passed to Magento\NewRelicReporting\Model\NewRelicWrapper::reportError() must be an instance of Exception, instance of TypeError given
```
### Proposed solution
In `\Magento\NewRelicReporting\Model\NewRelicWrapper::reportError`
```
    public function reportError(\Throwable $exception)
    {
        if ($this->isExtensionInstalled()) {
            newrelic_notice_error($exception->getMessage(), $exception);
        }
    }
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @rmsundar1,

Thanks for the report and collaboration!

We need some more information on this issue in order to process it further as below:

- Steps to reproduce (with screenshot if possible)
- Your specific use case where this functionality is not working as expected

Thanks

**Comment by rmsundar1** [comment]
@engcom-Hotel I was trying to capture the Graphql exceptions using the custom module in newrelic using the NewrelicReporting module.
And when I try to capture any TypeError exception using `\Magento\NewRelicReporting\Model\NewRelicWrapper::reportError` it's not allowed since it has the strict type in the function argument.

**Comment by engcom-Hotel** [comment]
Hello @rmsundar1,

Thanks for the reply!

As per looking into the code https://github.com/magento/magento2/blob/2e45de7acefbd665ffa90c5e24dda6a5286c36ee/app/code/Magento/NewRelicReporting/Model/NewRelicWrapper.php#L39
, the `reportError` method is accepting only `Exception` types but, `newrelic_notice_error` can accept `Throwable` types as well. This is the documentation link : https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error/#own-exception-handler

Hence confirming this issue.

Thanks
