### ISSUE TITLE
How to enable my onw disabled account (as only admin user) ? So I cannot login

### ISSUE THREAD

**Issue by MargreetMeijer** [magento/magento2#35860]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by MargreetMeijer** [comment]
Hi there

I’m, trying to login, but it will not work.
I’m the only admin user at the moment, so the other (sales users) cannot do anything.
We are using Magento ver. 2.3.5-p2

The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.

***@***.***
I tried all users I think it can be
Asked for new passwords
Captia problems…

I hope you can help to login again??

With the best regards,


Margreet Meijer


Van: m2-assistant[bot] ***@***.***>
Verzonden: dinsdag 2 augustus 2022 14:18
Aan: magento/magento2 ***@***.***>
CC: Margreet Meijer | NHMR ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [magento/magento2] How to enable my onw disabled account (as only admin user) ? So I cannot login (Issue #35860)


Hi @MargreetMeijer<https://github.com/MargreetMeijer>. Thank you for your report.
To speed up processing of this issue, make sure that you provided the following information:

  *   Summary of the issue
  *   Information on your environment
  *   Steps to reproduce
  *   Expected and actual results

Make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce. To deploy vanilla Magento instance on our environment, Add a comment to the issue:

@magento give me 2.4-develop instance - upcoming 2.4.x release

For more details, review the Magento Contributor Assistant<https://devdocs.magento.com/contributor-guide/contributing.html#contributor-assist> documentation.

Add a comment to assign the issue<https://devdocs.magento.com/contributor-guide/contributing.html#assigning-an-issue>: @magento I am working on this

To learn more about issue processing workflow, refer to the Code Contributions<https://devdocs.magento.com/contributor-guide/contributing.html>.

________________________________

  *   Join Magento Community Engineering Slack<https://opensource.magento.com/slack> and ask your questions in #github<https://magentocommeng.slack.com/messages/C7KB93M32> channel.

⚠️ According to the Magento Contribution requirements, all issues must go through the Community Contributions Triage process. Community Contributions Triage is a public meeting.

🕙 You can find the schedule on the Magento Community Calendar page<https://www.adobe.io/open/magento/calendar>.

📞 The triage of issues happens in the queue order. If you want to speed up the delivery of your contribution, join the Community Contributions Triage session to discuss the appropriate ticket.

✏️ Feel free to post questions/proposals/feedback related to the Community Contributions Triage process to the corresponding Slack Channel<https://magentocommeng.slack.com/archives/C016SG16J03>

**Comment by devchris79** [comment]
Source: https://www.simicart.com/blog/reset-magento-admin-password/

Magento CLI does not support changing admin passwords with a command, you can create a new admin user with the following command, and then use the new admin account to change the password of your original user.

Go to your Magento directory and execute the following command to create a new admin user:
php bin/magento admin:user:create --admin-user new_user_name --admin-password new_user_password --admin-email my@email.com --admin-firstname firstname --admin-lastname lastname

where :

    new_user_name: is the username of the new admin account that you’ll be creating
    new_user_password: is the password of the new admin account that you’ll be creating
    my@email.com : is the email of the new admin account that you’ll be creating
    firstname: replace it with your first name
    lastname: replace it with your last name

After you’ve created a new admin account, log into this new account and reset your old admin account’s password using method

**Comment by engcom-Bravo** [comment]
Hi @MargreetMeijer 

Thanks for contribution and collaboration.

Kindly refer above [comment](https://github.com/magento/magento2/issues/35860#issuecomment-1202497751) .
If you are still facing the issue please refer our Magento [documentation](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-admin.html)
Let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @MargreetMeijer,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
