### ISSUE TITLE
RequireJS config for theme doesn't update automatically 

### ISSUE THREAD

**Issue by ravbetsky** [magento/magento2#3586]
Each change in requirers-config.js of our module doesn't take any effect. After we had removed pub/static/_requirejs/frontend/Magento/luma/en_US/requirejs-config.js our changes applied.

**Comment by anton-huz** [comment]
Hi @ravbetsky ,
As you may know same behavior has `translation.json` file. Yes, they are not flushed if any source files are changed.

Could you imagine, describe how the issue could be solved?

For the generation `/_requirejs/../requirejs-config.js` responsive PHP app. But PHP app has no mechanizm for watching file's changes.

Frontend (via Grunt tasks) has ability for watching file's changes. But it doesn't know about rules why  `/_requirejs/../requirejs-config.js`  should be flushed.

So there is no pretty solution.

Maybe you have any ideas?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/RequireJS-config-for-theme-doesn-t-update-automatically/idi-p/45305).
