### ISSUE TITLE
Login session ending too early

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#35868]
### Preconditions and environment

2.4.3-p1
Site migrated from 1.9.3.6

### Steps to reproduce

Configuration > Advanced > Admin > Security > Admin Session Lifetime (seconds) : 36000 (10hrs)
Configuration > Web > Default Cookie Settings : 86400 (24hrs)

### Expected result

Admins stay logged in for 10hrs
Customers stay logged in for 24hrs

### Actual result

Admins and customers are required to login again after less than 1hr

### Additional information

session.gc_maxlifetime is set to 86400

Upon re-logging in as admin, receive notification that all active sessions were terminated. Only one user (me) using the account.

Sometimes receive a message like "visible section is not available" on the login panel, but not always.

Earlier in 2022 I found a git issue on this which identified a fault in 2.4.3-p1 along with workaround patch, but I cannot find that issue anymore.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adamlavery** [comment]
@magento give me 2.4-develop instance

**Comment by devchris79** [comment]
Is it this one? #34863

**Comment by adamlavery** [comment]
Hi @devchris79, yes I think that's the one I was looking at but looking at it again now I'm not sure how it relates. I was clutching at straws back then as to why this was happening but had to get on with more important stuff so had live with short sessions. Now getting close to release so need to address this as client will not be so happy to live with it!

**Comment by adamlavery** [comment]
Unable to reproduce on vanilla install. There I remain logged in for as long as expected.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by adamlavery** [comment]
Hi @engcom-Bravo, thanks for looking into this so quickly but can you hold off for now? I think I've found the cause of this and if I'm right it's the hosting platform, not Magento. Have made changes and testing this now i.e. checking I'm not logged out; so far so good. Will confirm in a hour or so along with cause and resolution.

**Comment by adamlavery** [comment]
**Issue resolved:** it was down to the hosting platform rather than Magento.

Site is hosted on Plesk server running Ubuntu with multiple PHP handlers installed. While session.gc_maxlifetime was set to 86400 for the M2 site PHP handler, it was still as default 1440 for other handlers. Magento default config was to use file based sessions stored in the default folder (session.save_path) i.e. no save_path defined in etc\env.php.

Ubuntu has a system cron job that clears out old sessions. However, it appears it does this by parsing all PHP instance php.ini files and then uses the smallest or last session.gc_maxlifetime it encounters (who knows!). Result is it was deciding session files were invalid after 1440 seconds and at 09 and 39 minutes past the hour was deleting them. Hence the variable timeouts of less than an hour.

**Solution:** define alternative save_path in etc\env.php e.g. [magento]\var\sessions

Then the Unbuntu cron job does not delete sessions prematurely as it only housekeeps the session files in the default save_path.

**Alternative solution:** ensure all PHP instances on the server use the same default session.gc_maxlifetime value.

Thanks to those who jumped on this.
