### ISSUE TITLE
PayPal Express Checkout order confirmation email addressed to 'Guest' instead of customer name

### ISSUE THREAD

**Issue by Finbayern** [magento/magento2#35866]
### Preconditions and environment

- Magento version 2.4.4 (was present at 2.3.5 already)
- php 7.4
- PayPal Express Checkout enabled
- Use standard `<p class="greeting">{{trans "%customer_name," customer_name=$order_data.customer_name}}</p>` in the order related email templates

### Steps to reproduce

1. Enable PayPal Express Checkout
2. Navigate to frontend
3. Add products in cart
4. Checkout using PayPal Express Checkout as a payment method
5. Receive the order confirmation email
6. (optional) Navigate to backend
7. (optional) Send invoice and shipping emails to the customer

### Expected result

Order confirmation email, invoice email and shipment emails are addressed to the customer name.

### Actual result

Order confirmation email, invoice email and shipment emails are all addressed to 'Guest'.

### Additional information

This only happens with PayPal, by using any other payment method the email will be correctly addressed to the customer name as expected.
This affects only the first line, all the payment information and shipping information fields work as expected, containing the customer name used upon placing the order.

I couldn't find any bug report about this, but this has been discussed already in 2020 here: https://community.magento.com/t5/Magento-2-x-Technical-Issues/Order-Confirmation-Emails-Addressed-to-Guest-post-update/td-p/463491

This can be fixed by modifying file vendor/magento/module-paypal/Model/Express/Checkout.php as discussed in the topic, but this should be fixed in the Magento core files as well.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @Finbayern ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Comment by DanieliMi** [comment]
This has been fixed in https://github.com/magento/magento2/commit/38cc5b1e35940dfe1d7a30605457f08222445658. Should be fixed in 2.4.5.
