### ISSUE TITLE
Magento 2.4.3 SameSite Cookie None Issue

### ISSUE THREAD

**Issue by sagargopale1992** [magento/magento2#35863]
### Summary (*)
I am developing third party payment gateway plugin for Magento version 2.4.3 and using PHP version 7.4 with ngnix server. Now I am facing problem after redirecting back from the payment gateway to Magento website.

Due to SameSite cookies issue my session getting lost after returning to the website.

I want to set SameSite Cookie value as None for all requests and for this I have tried all steps as mentioned in the below post.

### Examples (*)
https://hardikparikh94.medium.com/fixing-magento2-samesite-cookie-issue-8b687908a9e0

### Proposed solution
I have tried everything as mentioned in the above blog but still SameSite cookie issue is not getting resolved.

---

**Comment by engcom-Dash** [comment]
Hi @sagargopale1992 ,

Kindly Provide below information to speed up the process...

1.Summary of the issue
2.information on your environment
3.Steps to reproduce
4.Expected and actual results

Thanks!

**Comment by engcom-Dash** [comment]
Hi @sagargopale1992 ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
