### ISSUE TITLE
Can't import additional_attributes 2.4.3

### ISSUE THREAD

**Issue by isaacdzca** [magento/magento2#35879]
### Preconditions and environment

Magento 2.4.3

### Steps to reproduce

Import CSV files to update product boolean attribute does not work if the attribute is present on "additional_attributes". If I use the column additional_attributes will not work; also if I use the Attribute code will not work too.

### Expected result

Additional attributes are updated

### Actual result

Import process ends but the attribute is not updated

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @isaacdzca

Thank you for raising an issue.

Please help us to provide exact steps to reproduce and screenshots if possible provide us video in order to replicate the issue.


Regards.

**Comment by isaacdzca** [comment]
@magento give me a 2.4.-develop instance

**Comment by engcom-Bravo** [comment]
Hi @isaacdzca,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
