### ISSUE TITLE
Customer relogin not working

### ISSUE THREAD

**Issue by devhn** [magento/magento2#3587]
Hi,

i have setup a local Magento installation:
- Magento 2.0.2 with sample data
- Bitnami Mamp with php 7, mysql 5.7 and Varnish enabled
- localhost:8080/dev/

I experienced a strange issue with customer login:
- Created a new customer account on frontend
- After successful registration i logged out
- When trying to login back again the login page refreshes, clears the email and password field, gives no error and doesn't log me back in. The only notice i get below the login form is "Try Demo Customer Access" with the sample login data, which does not work when i try to use them.

I have also tried with M2 installation without sample data but the same problem perssist.
Is this a bug or just local missconfiguration of my setup? Thanks

**Comment by devhn** [comment]
Update: I can login/relogin in Firefox but the problem persist in Chrome.

**Comment by mrkhoa99** [comment]
Hello @bb8d!
Don't try to use top level domain(TLD) like _localhost:8080_ or _localhost_. You should add one dot to your domain, for example: _magento.local_, _127.0.0.1_.

**Comment by mazhalai** [comment]
+1 for @mrkhoa99's comment. Also, read [this](alankent.me/2015/04/25/use-of-localhost-when-installing-magento-2-quick-note/)

Closing since this is not an issue.
