### ISSUE TITLE
GJSS TEST ISSUE (AMY) #2

### ISSUE THREAD

**Issue by AmyJZhao** [magento/magento2#35871]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Steps to reproduce

### Expected result

Expected result

### Actual result

Actual result

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export to Jira project AC

**Comment by irenelagno** [comment]
@adobe https://github.com/adobe export to Jira project AC

**Comment by irenelagno** [comment]
https://github.com/adobe https://github.com/adobe export to Jira project PB

**Comment by irenelagno** [comment]
@adobe https://github.com/adobe https://github.com/adobe export to Jira project AC

**Comment by irenelagno** [comment]
https://github.com/adobe https://github.com/adobe https://github.com/adobe export to Jira project PB

**Comment by irenelagno** [comment]
@adobe export to Jira project PB

**Comment by irenelagno** [comment]
@adobe export issue to Jira project PB

**Comment by irenelagno** [comment]
@adobe export issue to Jira project AC

**Comment by irenelagno** [comment]
https://github.com/adobe export issue to Jira project ACP2E as bug

**Comment by irenelagno** [comment]
@adobe export issue to Jira project ACP2E

**Comment by irenelagno** [comment]
@adobe export issue to Jira project ACP2E as bug

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E as bug

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E as bug

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project AC as bug

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project AC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by engcom-Delta** [comment]
Hi @AmyJZhao ,
Thank you for raising an issue , Kindly provide issue clear description , steps to reproduce , actual results, expected results and screenshots if required.
Regards,

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project ACP2E

**Comment by engcom-Delta** [comment]
Hi @AmyJZhao ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
