### ISSUE TITLE
Company Graphql - Roles pagination is broken

### ISSUE THREAD

**Issue by manikandan-karuppaiah-accenture** [magento/magento2#35870]
If the company user creates multiple roles for the company. While access that in graphql by passing pagesize "5" and current page "1" in the company query. The result it always shows total page as 1 but the total roles created is more than "7".

Please refer the screenshot attached.

{
    "data": {
        "company": {
            "roles": {
                "items": [
                    {
                        "id": "OTU=",
                        "name": "Default User",
                        "permissions": [
                            {
                                "id": "Magento_Company::index",
                                "text": "All"
                            }
                        ]
                    },
                    {
                        "id": "OTc=",
                        "name": "Sales",
                        "permissions": [
                            {
                                "id": "Magento_Company::index",
                                "text": "All"
                            }
                        ]
                    },
                    {
                        "id": "OTg=",
                        "name": "Sub-Admin",
                        "permissions": [
                            {
                                "id": "Magento_Company::index",
                                "text": "All"
                            }
                        ]
                    },
                    {
                        "id": "MTY3",
                        "name": "Place Order",
                        "permissions": [
                            {
                                "id": "Magento_Company::index",
                                "text": "All"
                            }
                        ]
                    },
                    {
                        "id": "MTY5",
                        "name": "Sub-Admin - Duplicated",
                        "permissions": [
                            {
                                "id": "Magento_Company::index",
                                "text": "All"
                            }
                        ]
                    }
                ],
                "page_info": {
                    "page_size": 5,
                    "current_page": 1,
                    "total_pages": 1
                },
                "total_count": 5
            }
        }
    }
}

**Comment by engcom-Delta** [comment]
Hi @ManikandanKaruppaiah ,
Thank you for raising an issue and We are happy to assist to you . Kindly review the provided query it seems there is syntactical error  , please provide expectation results and actual results with screenshots if required.

Thanks

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
