### ISSUE TITLE
Class Magento\Framework\File\Filesystem does not exist

### ISSUE THREAD

**Issue by bruce-gemberling** [magento/magento2#35873]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by bruce-gemberling** [comment]
When trying to add a JPG image to a product I get the error:

Class Magento\Framework\File\Filesystem does not exist

How can i fix this in my Magento 2.3.6

<img width="778" alt="image" src="https://user-images.githubusercontent.com/395752/182682024-82a3a97c-c626-4236-9a02-d247e95fb110.png">

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @bruce-gemberling,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
