### ISSUE TITLE
translation with nl_NL.csv doesn't always work

### ISSUE THREAD

**Issue by bbraspenning** [magento/magento2#3588]
We have added a nl_NL.csv to our own theme and magento i18n folder
-   app/design/frontend/%CUSTOM_THEME%/default/i18n
-    app/i18n/magento/nl_nl
  "Adding...","Toevoegen..."
  "Added","Toegevoegd"
  "Add to Cart","Aan mandje toevoegen"

This gets most of the magento website translated except for
- product details page add to cart/ adding... / added.
  while the product overview page translations of added to/cart/adding.../added are correctly translated.

How can we get this translated correctly?

_note: seems to be a javascript issue. _data in translate.js doesn't seem to be filled correctly at the detail page and the same issue might be accuring within the checkout process where we also have some unchanged translated words...  Other example  $t('Welcome, %1!') in header
Please a fix or workaround for this..._

**Comment by thomvanderboon** [comment]
This issue is already covered by another issue:

https://github.com/magento/magento2/issues/2630

**Comment by hshar7** [comment]
Hi @bbraspenning this has been already fix. Please clone latest develop branch.
