### ISSUE TITLE
URL key in hierarchy not updated after URL key update in CMS page

### ISSUE THREAD

**Issue by Etje** [magento/magento2#35880]
### Preconditions and environment

Magento 2.4.4 Enterprise Edition

### Steps to reproduce

- Make a CMS page.
- Add the page to Hierarchy (Content -> Elements -> Hierarchy)
- Go back to the CMS page and change URL key
- Go back to hierarchy, and you will see that the URL key has not changed 

### Expected result

Expected result is an updated URL key in the hierarchy

### Actual result

Actual result is the the URL key in hierarchy is not updated

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Lima** [comment]
Hi @Etje ,

I have tried to reproduce the issue in clean Magento `2.4-develop` with EE edition but unable to reproduce it.
Kindly refer my video if anything I am missing kindly provide me information.
Also try to test in latest  Magento `2.4-develop` & let us know if you are facing any issue.

Thanks

**Comment by Etje** [comment]
I saw your video. unfortunately the Magento instance provided by @engcom-Lima does not work anymore, so I can not verify it. That said, I am oké with closing the issue, because it's not relevant anymore

**Comment by engcom-Lima** [comment]
Hi @Etje ,

As per your last comment marking this issue as fixed. Hence, closing this issue.

Thanks

**Comment by nouchka** [comment]
I still have the issue. In magento 2.4.3 in my case.

Hi @engcom-Lima , I watched the video and you added the page to the root node. I tried on my local setup and I don't have the issue when it's the root node.
so "Steps to reproduce" should be:
Add the page to Hierarchy (Content -> Elements -> Hierarchy) on a sub-node, not the root one

best regards

**Comment by reense** [comment]
I've created a similar issue, and I think it's the same problem. It's still not fixed: https://github.com/magento/magento2/issues/39482
