### ISSUE TITLE
Admin panel edit zip code with leading 0 not possible

### ISSUE THREAD

**Issue by plastikschnitzer** [magento/magento2#35887]
### Preconditions and environment

- Magento 2.4.4
- PHP8.1
- Mysql 8
- Ubuntu 20.04 LAMP-Stack

### Steps to reproduce

Go to an order in admin panel
Edit Shipping or Billing address
Change ZIP-Code and add a leading zero OR remove one 0 to correct zip code and save address

### Expected result

Zip code should be corrected

### Actual result

No matter if a leading 0 is added or removed, the change does not show in the order data. 

### Additional information

Workaround: 

(quick and dirty) If you substitute the existing / missing 0 with another number (1 for example) and then again substitute 1 with 0 or remove the 1, its working!

Issue is known on stackexchange: 
https://magento.stackexchange.com/questions/299814/magento-2-3-1-billing-shipping-address-zip-code-automatically-removes-leading
https://magento.stackexchange.com/questions/315161/backend-automatically-removes-leading-zeros-0-from-zip-codes-magento-2-3-4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by plastikschnitzer** [comment]
@magento give me 2.4-develop instance

**Comment by plastikschnitzer** [comment]
I cannot reproduce the issue on the vanilla Magento-2.4-dev instance.

Maybe some 3rd party incompatibility? Environment issue? 

No hints on my server in system.log, exception.log or debug.log.

**Comment by engcom-Delta** [comment]
Hi @plastikschnitzer ,
Thank you for logging an issue , We tried to reproduce the issue on Magento 2.4 develop and magento 2.4.4 but issue is not reproducible. Please find the attached screenshot for reference.

<img width="1304" alt="Screenshot 2022-08-17 at 4 44 57 PM" src="https://user-images.githubusercontent.com/51681379/185141284-c6dfffeb-6922-43bd-9ada-94e85d512f7e.png">

Hence request to review the provided steps.

**Comment by engcom-Delta** [comment]
Hi @plastikschnitzer,

We have noticed that, this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
