### ISSUE TITLE
Image loader is missing when deleting an item from minicart

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#3589]
The image loader is missing when we delete an item from mini cart.
They are appending a class 'ajax-loading' to the <body> tag, but the loader is absent there.
Anyone please help me to solve this problem?

**Comment by ishakhsuvarov** [comment]
@vipin-eglobeits Thank you for reporting.
There is indeed no loader on minicart item removal. Currently it is not considered a bug, however, we are going to look into possibility to add one.

**Comment by vipin-eglobeits** [comment]
Hi Ishakhsuvarov,
Thank you so much for your quick response.

**Comment by asemenenko** [comment]
@ishakhsuvarov @vipin-eglobeitsone of the options will be to display a loader over a product that is deleting right now but keep other products and elements clickable

**Comment by ishakhsuvarov** [comment]
@vipin-eglobeits Closing this ticket for now. Please reopen if you have any additional questions.
