### ISSUE TITLE
Translations are not working within consumer instance

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#35890]
### Preconditions and environment

- Magento version: 2.4.3-p1

### Steps to reproduce

1. Create consumer
2. Try to translate whatever by __()

### Expected result

Value is translated

### Actual result

Value is NOT translated

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by madonzy** [comment]
here is the solution: https://www.atwix.com/magento-2/cli-scripts-translations/

why is it not loaded OOTB?

**Comment by engcom-Echo** [comment]
Hello @madonzy,

Thanks for contribution and collaboration.
Please provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @madonzy,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by hostep** [comment]
The same reasoning from [over here](https://github.com/magento/magento2/issues/26333#issuecomment-1219467460) can probably be applied? This is just guessing though, there is not enough information provided to be sure...
