### ISSUE TITLE
Catalog shown as out of stock if show_of_stock_option enabled

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#35898]
### Preconditions and environment

- 2.4-develop Vanila instance

### Steps to reproduce

1. take Vanila instance by `magento give me 2.4-develoop instance`
2. Go to Stores->Configuration->Catalog->Inventory and Enable `Display Out of Stock Products`
3. Clear cache
4. Got to catalog

### Expected result

Product shown in stock

### Actual result

Products show as out of stock
![2022-08-09-16-48-41@2x](https://user-images.githubusercontent.com/1129623/183668038-b4618e1c-d025-43c4-b2ac-7a434ac19f51.jpg)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develoop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Product is showing out of stock.
**Pre-requisite:** 2.4-develop Vanila instance

**Steps to reproduce:**

1. Take Vanila instance by `@magento give me 2.4-develoop instance`.
2. Go to Stores->Configuration->Catalog->Inventory and Enable Display Out of Stock Products
3. Clear cache
4. Go to catalog,open categories like men,women.
5. Configurable products are showing out of stock.

**Expected result:**  Product should display in stock.
**Actual result:** Showing out of stock
Screenshot:
![image](https://user-images.githubusercontent.com/60198022/183670990-70a98f73-1d2c-4499-a8b8-f016ffdadd22.png)
![image](https://user-images.githubusercontent.com/60198022/183671074-936e5161-9d32-4f18-9e6d-bf78029dfcd5.png)

Hence,confirming the issue.

Thanks

**Comment by FadedOut** [comment]
Is this happening on the just released 2.4.5? (I have not updated yet)

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Issue is reproducible on 2.4-develop branch with sample data installed but is not reproducible on 2.4.4 project-community-edition

**Comment by hostep** [comment]
Uhm, I don't think this issue is valid @Den4ik @engcom-November, unless I'm misunderstanding the report.

The setting `Display Out of Stock Products` actually means: instead of hiding out of stock products, show them.
This could be useful for shopowners who want to tease their visitors about products that are only sometimes in stock so they come back often to check if it's finally in stock one day for example.

**Comment by Den4ik** [comment]
@hostep if you endless prob in admin panel all products that in stock will be displayed as our of stock on frontend. It's bug

**Comment by hostep** [comment]
Aaaah okay, now I get it. Sorry completely misunderstood your initial post, my bad 🙂

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6330 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6330&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.5 instance
