### ISSUE TITLE
Newsletter confirmation email is send twice

### ISSUE THREAD

**Issue by Flow09AT** [magento/magento2#35894]
### Preconditions and environment

- Magento version 2.4.1 & 2.4.2

### Steps to reproduce

1. Subscribe to newsletter as guest
2. Ignore the newsletter confirmation mail which you'll receive
3. Sign up as a new customer to the shop and leave "Sign up for newsletter" unchecked

### Expected result

Newsletter confirmation mail should just be send once (after subscribe as guest)

### Actual result

Newsletter confirmation mail is send twice. 
One after subscribe as guest, one after register a new customer account, even when the "Sign Up for newsletter" checkbox is unchecked

### Additional information

Issue is reproducable on different magento 2.4 instances

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @Flow09AT ,

I have tried to reproduce the issue but issue is not reproducible. 
After sign up, the mail I have received is of newsletter unsubscription mail which is valid. 
Here, once you subscribe as newsletter as a guest, your email will be stored in the Magento. While signup if you give the email, Magento will detect the email and check the checkbox automatically. Once you unselect it subscription mail will be sent to the customer.
Below is the screenshot for your reference:
![image](https://user-images.githubusercontent.com/60198022/183640749-69e09a2c-f044-4324-98f6-e8a74733cb82.png)

Kindly check in `2.4-develop` and let us know if you get any issue.
Thanks

**Comment by Flow09AT** [comment]
@magento give me 2.4-develop instance

**Comment by Flow09AT** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @Flow09AT ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
