### ISSUE TITLE
Catalog shown entire catalog items count if show_of_stock_option enabled

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#35899]
### Preconditions and environment

- 2.4-develop Vanila instance

### Steps to reproduce

1. Take Vanila instance by magento give me 2.4-develoop instance
2. Go to Stores->Configuration->Catalog->Inventory and Enable Display Out of Stock Products
3. Clear cache
4. Go to catalog Women->Tops->Bras & Tanks
5. Apply Filter Style->Bra that show 5 items

### Expected result

Total catalog items should show 5 items and 5 as total value

### Actual result

1. Shown 12 items in catalog
2. Shown 14 as total items
![2022-08-09-17-15-35@2x](https://user-images.githubusercontent.com/1129623/183672235-5a91208f-e266-4684-a519-423116c348fd.jpg)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Product is showing out of stock.
**Pre-requisite:** 2.4-develop Vanila instance

**Steps to reproduce:**

1. Take Vanila instance by `@magento give me 2.4-develoop instance`.
2. Go to Stores->Configuration->Catalog->Inventory and Enable Display Out of Stock Products
3. Clear cache
4. Go to catalog Women->Tops->Bras & Tanks
5. Apply Filter Style->Bra that show 5 items

**Expected result:**
Total catalog items should show 5 items and 5 as total value

**Actual result :**  It was showing 14 items.

**Screenshot:**

![image](https://user-images.githubusercontent.com/60198022/184365501-d6a62376-9a9e-4c3c-90b0-a4f883526e9d.png)
=============================================================================================
![image](https://user-images.githubusercontent.com/60198022/184365256-30c1479f-06bc-456e-b1e7-5c9ee3b11d25.png)


Hence,confirming the issue.

Thanks

**Comment by zhartaunik** [comment]
This commit broke this functionality and need to be refactored:
https://github.com/magento/magento2/commit/3a889f465e21cdba4a78788704f3c5b31f3d2d9f
Reverting everything back does help. I'm not absolutely sure about the logic stored in that private method.

**Comment by Bashev** [comment]
@magento give me 2.4-develoop instance

**Comment by Bashev** [comment]
@Den4ik can you make an review for this fix?

**Comment by leonhelmus** [comment]
Also check the magento inventory repo more often please:
https://github.com/magento/inventory/issues/3360

It looks like no one is active on that repo to pick the issues up.

**Comment by pmonosolo** [comment]
These are probably related: 
https://github.com/magento/magento2/issues/36055

**Comment by pmonosolo** [comment]
Whoever is working on this, please release this as a hotfix - this is an important part of the store. PHP 7.4 is EOD in 2 months, we've gotta get it fixed.

**Comment by pmonosolo** [comment]
Ya'll should try the fix in this thread:
https://github.com/magento/inventory/issues/3360

**Comment by Bashev** [comment]
@pmonosolo see also my fix https://github.com/magento/magento2/pull/35986

**Comment by glo17680** [comment]
@Den4ik Thanks for contributing, internal team has started working on this.

**Comment by i6media** [comment]
Any updates on this matter?

**Comment by glo71317** [comment]
@i6media It will be merge soon, PR in queue

**Comment by i6media** [comment]
@glo71317 could you link the correct PR here? The one from @Bashev is not sufficient since it still fetches all products and filters them afterwards by PHP (slow loading times), instead of in the query itself.

**Comment by glo71317** [comment]
@i6media We raised the internal PR so you will not have the access for the same, so i don't think it will help. we have taken the commits from @Bashev PR and written automation tests.

**Comment by ssx** [comment]
@glo71317 can you provide a patch file for the changes?

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6395 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6395&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by i6media** [comment]
@ssx you can copy the file (https://github.com/magento/magento2/blob/7792c18603d80f020dd0265d78ecf0ad8f64f944/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php) and temporarily overwrite it in your own module through di.xml, until the new versions comes out.

`<preference for="Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier" type="Foo\Bar\Plugin\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier" />`

**Comment by alek-s-andr** [comment]
I have tested the patch just now, filter is applied but the items counter not changing.

![2022-10-13-21-28-23](https://user-images.githubusercontent.com/34573954/195626317-71a186a1-6a55-42d2-af78-029f4e6d5925.png)

**Comment by i6media** [comment]
For me the same issue as @alek-s-andr

**Comment by norgeindian** [comment]
@alek-s-andr , this is probably related to https://github.com/magento/magento2/issues/36404.
The plugin `vendor/magento/module-inventory-catalog/Plugin/Catalog/Block/ProductList/UpdateToolbarCount.php` calculates the wrong item count at this spot.
