### ISSUE TITLE
Uncaught TypeError: utils.formatPriceLocale is not a function

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#35905]
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1. Navigate to a product, doesnt matter if its a simple, configurable or anything else.

### Expected result

No JS error

### Actual result

price-box.js:153 Uncaught TypeError: utils.formatPriceLocale is not a function
    at $.<computed>.<computed>.<anonymous> (price-box.js:153:41)
    at underscore.js:723:29
    at Function.each (underscore.js:1335:17)
    at $.<computed>.<computed>.reDrawPrices (price-box.js:148:15)
    at $.<computed>.<computed>.reloadPrice (widget.js:132:25)
    at HTMLDivElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at HTMLDivElement.<anonymous> (jquery.js:8797:30)
    at Function.each (jquery.js:385:35)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment]
This seems to also affect the cart and checkout..

[ERROR] Failed to load the "Magento_Tax/checkout/summary/subtotal" template requested by "block-totals.subtotal".

jquery.js:4050 jQuery.Deferred exception: Unable to process binding "if: function(){return !isTaxDisplayedInGrandTotal && isDisplayed() }"
Message: Unable to process binding "text: function(){return getValue() }"
Message: priceUtils.formatPriceLocale is not a function TypeError: Unable to process binding "if: function(){return !isTaxDisplayedInGrandTotal && isDisplayed() }"
Message: Unable to process binding "text: function(){return getValue() }"
Message: priceUtils.formatPriceLocale is not a function

**Comment by jorgb90** [comment]
Mm solved it. Was not a core issue.

**Comment by verhaeghep** [comment]
@jorgb90 How did you solve the problem? I have the same issue on my Magento 2.4.5 installation.

**Comment by ssx** [comment]
@jorgb90: what was the issue? I've got the same on a project.

**Comment by verhaeghep** [comment]
> @jorgb90: what was the issue? I've got the same on a project.

Module magento2-price-demical from lillik is the source of the problem. See: https://github.com/lillik/magento2-price-decimal/issues/78

**Comment by ssx** [comment]
thanks @verhaeghep - it'll be the same for this project too.
