### ISSUE TITLE
GraphQL Routes query with fragments has issue in the category page

### ISSUE THREAD

**Issue by jancyceymox** [magento/magento2#35906]
### Preconditions and environment

Environment: Magento Open Source 2.4.5

Preconditions: Use the category page URL in the param. Also, use fragments in the query

### Steps to reproduce

1. Create a sub category under default category and run the graphQL query with category url in the query. Please run it in the tool
````
query Route($url: String!) {
    route(url: $url) {
      redirect_code
      relative_url
      type
   
      ... on CategoryTree {
        name
        id
        url_path
        url_suffix
        breadcrumbs {
          category_name
          category_url_path
          category_uid
        }
      }
       ...on SimpleProduct{
        ...ProductFragment
        }
    }
  }
fragment ProductFragment on SimpleProduct {
    name
    price_range {
      minimum_price {
        regular_price {
          value
        }
        final_price {
          value
        }
      }
    }
    description {
      html
    }
    image {
      url
    }
    media_gallery {
      url
    }
  }
````

2. Variable used:
 `{
  "url": "men.html"
}`

### Expected result

Returns category information.

`{
  "data": {
    "route": {
      "redirect_code": 0,
      "relative_url": "men.html",
      "type": "CATEGORY",
      "name": "Men",
      "id": 11,
      "url_path": "men",
      "url_suffix": ".html",
      "breadcrumbs": null
    }
  }
}`

### Actual result

500 Internal server error is returned

`{
  "errors": [
    {
      "debugMessage": "Notice: Undefined property: GraphQL\\Language\\AST\\FragmentSpreadNode::$selectionSet in /var/www/html/mage245/vendor/magento/module-catalog-graph-ql/Model/Category/DepthCalculator.php on line 83",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "route"
      ]
    }
  ],
  "data": {
    "route": null
  }
}`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
hi @jancyceymox ,
Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is not reproducible. Can you please provide the complete GraphQl query that you have used to reproduce the issue from our end.
Thank you.

**Comment by jancyceymox** [comment]
@engcom-November 
I have added the complete graphQL query in the description. Please use your category URL instead of 'men.html'

```
{
    route(url: "men.html") {
      redirect_code
      relative_url
      type
   
      ... on CategoryTree {
        name
        id
        url_path
        url_suffix
        breadcrumbs {
          category_name
          category_url_path
          category_uid
        }
      }
       ...on SimpleProduct{
        ...ProductFragment
        }
    }
  }
fragment ProductFragment on SimpleProduct {
    name
    price_range {
      minimum_price {
        regular_price {
          value
        }
        final_price {
          value
        }
      }
    }
    description {
      html
    }
    image {
      url
    }
    media_gallery {
      url
    }
  }
```

**Comment by engcom-November** [comment]
Verified the issue on both Magento 2.4-develop branch and 2.4.5 project-community-edition and the issue is reproducible with below steps performed.
Note: Intermittent issue.
Steps performed:
1. Created sub category under default category and run above graphql query:
Issue: Internal server error is observed.
Note: This issue is not observed for all category links. Issue observed for categories under default category with no / 1 product.
![image](https://user-images.githubusercontent.com/60198231/186393930-dd9bc29d-e71c-4aef-8c6f-0fbf1381b3a0.png)

**Comment by monteshot** [comment]
@magento I am working on this
