### ISSUE TITLE
totally shit concepts you using

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3590]
totally shit concepts you using that  a designder can't understand to develop not even header and footer for magneto-2.

after two weeks unable to understand how to create a theme for magento-2.

**Comment by MomotenkoNatalia** [comment]
@seetpal-smartshore 
We appreciate any feedback about our work.

Have you tried to use documentation for Frontend Developers - http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/bk-frontend-dev-guide.html ?

**Comment by 471jozh** [comment]
lol

**Comment by jamescowie** [comment]
Closed as not a bug report. Can I suggest that you look at the dev docs but also if you are having issues look at the forums for Magento 2 where we are more than happy to help get you working with Magento 2.

**Comment by ae-mo** [comment]
Scams
