### ISSUE TITLE
Unable to install data migration tool from github

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35904]
### Preconditions and environment

Magento 2.4-develop

### Steps to reproduce

Install data migration tool on 2.4-develop from github. Ref [guide](https://devdocs.magento.com/guides/v2.4/migration/migration-tool-install.html)
**Steps:**
 > composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
 > composer require magento/data-migration-tool:2.4.4
or run > composer require magento/data-migration-tool:~2.4
 > bin/magento module:enable Magento_DataMigrationTool

### Expected result

Data migration tool is installed successfully.

### Actual result

Unable to install the tool from git hub.
![image](https://user-images.githubusercontent.com/60198231/183882505-ef28662a-1aa2-453e-b8b6-f26a452e7211.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @engcom-November,

Thanks for your contribution and collaboration.

Verified the issue on Magento 2.4-develop branch. We are able to reproduce the issue. Kindly refer the screenshots

Steps Followed:

1.composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
2.composer require magento/data-migration-tool:2.4.4

<img width="940" alt="gt" src="https://user-images.githubusercontent.com/51680745/183915164-d0f3eb97-39c5-4fe9-a3c8-b7ceb6bf1638.png">


Hence confirming the issue.


Thanks.

**Comment by sdzhepa** [comment]
@engcom-Bravo  @engcom-November @engcom-Hotel 

Is it an issue related to Magento Core code or to the data-migration tool?
If it's related to the tool(fix should be in tool repo) it makes sense to report in https://github.com/magento/data-migration-tool/issues

**Comment by hostep** [comment]
Maybe ask @sergiy-v for assistance to help move the data migration tool to Symfony 5.4? Similar as what was done with https://github.com/magento/magento2/commit/6c18f2e09a09ea481612e83e16f5c31c33cb563f#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by xmav** [comment]
@engcom-November Please move this issue to https://github.com/magento/data-migration-tool/issues

**Comment by engcom-November** [comment]
Thanks for the update @sdzhepa / @xmav . Logged new [issue](https://github.com/magento/data-migration-tool/issues/901) in repo:  https://github.com/magento/data-migration-tool/issues. Hence closing this issue.
