### ISSUE TITLE
Magento Marketplace login issue

### ISSUE THREAD

**Issue by mkikets99** [magento/magento2#35919]
### Preconditions and environment

- Magento Marketplace is on 2.4.5

### Steps to reproduce

Done 2 things to login either way...
1. Login with Adobe ID with same email as was on MM (Magento Marketplace) 2.4.3 (failed, Sign In button doesn't changes to profile name)
2. Login by creating a new profile on Adobe ID (failed, same results as in [1])

### Expected result

Successful login

### Actual result

Sign In button doesn't changes to profile name, which means that sign in was failed.

### Additional information

If this issue is not related to here, please provide information where to communicate.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by mkikets99** [comment]
According to this page:
https://marketplacesupport.magento.com/hc/en-us/articles/4403689268237-Cannot-Login-to-Magento-Marketplace-
I need to contact Support... but every redirection connection is broken... even a email redirection from https://marketplacesupport.magento.com to https://support.magento.com...
And idk what to do...

**Comment by engcom-November** [comment]
Hi @mkikets99 ,
I'm able to login to Magento Market place page using Adobe ID without any issues.
![image](https://user-images.githubusercontent.com/60198231/184883400-6730e80e-efb9-4da8-8e1a-e4e8da40b2e1.png)
Kindly check your VPN settings / or administrator settings is causing this issue. Kindly elaborate the issue if you are still facing any issues.
Thank you.
