### ISSUE TITLE
Magento orders not transferring to QuickBooks

### ISSUE THREAD

**Issue by jjordan73** [magento/magento2#35912]
### Preconditions and environment

Magento ver. 2.4.3-p1
I am missing orders that are not transferring to QuickBooks

### Steps to reproduce

Orders are in Magento, but not in quickbooks.  No pattern

### Expected result

All orders created in magento need to get transferred to quickbooks

### Actual result

we are missing orders

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
> ### Preconditions and environment
> Magento ver. 2.4.3-p1 I am missing orders that are not transferring to QuickBooks

Which plugin are you using? Magento 2 does not have direct QB connection.

**Comment by jjordan73** [comment]
I’ll check and get back to you.  Problem is we are getting most customer and orders transferring direct into QB from Magento, but not all of them 

Justin Jordan
512-487-0947

**Comment by pmonosolo** [comment]
> I’ll check and get back to you. Problem is we are getting most customer and orders transferring direct into QB from Magento, but not all of them Justin Jordan 512-487-0947
> […](#)
> On Aug 11, 2022, at 11:51 AM, pmonosolo ***@***.***> wrote: ﻿ Preconditions and environment Magento ver. 2.4.3-p1 I am missing orders that are not transferring to QuickBooks Which plugin are you using? Magento 2 does not have direct QB connection. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

You guys need a developer to take a look at this. 

This is not related to Magento 2.

**Comment by jjordan73** [comment]
We have 2.  Which plug-in do we need?

Justin Jordan
512-487-0947

**Comment by pmonosolo** [comment]
> We have 2. Which plug-in do we need? Justin Jordan 512-487-0947
> […](#)
> On Aug 11, 2022, at 11:51 AM, pmonosolo ***@***.***> wrote: ﻿ Preconditions and environment Magento ver. 2.4.3-p1 I am missing orders that are not transferring to QuickBooks Which plugin are you using? Magento 2 does not have direct QB connection. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

You need to check your website configuration and trust your website developers to fix the issue.

**Comment by engcom-November** [comment]
Hi @jjordan73 ,
Thank you for reporting and collaboration. However, QuickBooks is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Comment by Rusllana** [comment]
@magento give me 2.4-develop instance

**Comment by Rusllana** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by Rusllana** [comment]
https://github.com/magento give me 2.4-develop instance
