### ISSUE TITLE
From yesterday, issue after 'classic' composer update

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35911]
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug

From yesterday, i can see a lot of module updated with simple composer update command.
I note that yesterday, magento 2.4.5 has released

I understand not why composer update make one upgrade of all magento core module without i specify require with Magento version.

### Steps to reproduce

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug
composer update
bin/magento setup:upgrade
bin/magento setup:di compile

### Expected result

All working

### Actual result

magento_user@achatpc:/var/www/html$ php bin/magento setup:upgrade
Cannot instantiate interface Magento\AdobeImsApi\Api\ConfigInterface#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#5 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#6 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#7 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#8 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#9 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#10 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#11 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#12 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#13 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#14 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#15 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#16 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#17 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#18 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#19 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#20 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#21 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#22 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#23 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#24 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#25 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#26 /var/www/html/vendor/magento/framework/Console/Cli.php(153): Magento\Framework\ObjectManager\ObjectManager->create()
#27 /var/www/html/vendor/magento/framework/Console/Cli.php(134): Magento\Framework\Console\Cli->getApplicationCommands()
#28 /var/www/html/vendor/symfony/console/Application.php(1274): Magento\Framework\Console\Cli->getDefaultCommands()
#29 /var/www/html/vendor/symfony/console/Application.php(629): Symfony\Component\Console\Application->init()
#30 /var/www/html/vendor/symfony/console/Application.php(237): Symfony\Component\Console\Application->find()
#31 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#32 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#33 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#34 {main}

### Additional information

First bin/magento setup:upgrade working but after, any bin/magento commande provide this error.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
Hello @achatpc 

I am not sure but it looks like a known issue.
Could you please check this article and confirm if it helps?
https://support.magento.com/hc/en-us/articles/8214752983949

**Comment by achatpc** [comment]
Hello,
Working

Thank you so much!

**Comment by achatpc** [comment]
Well, I probably spoke a little fast...

On my developer environement:

This script allows you to stay on version 2.4.4 and to continue, if necessary, to run composer update and keep the versions of the different modules up to date.

However, after script rollback and update request to Magento 2.4.5, the issue reappears.

And the script does not work with Magento version 2.4.5.

Anyway, it is necessary to solve the initial error.

**Comment by engcom-Dash** [comment]
Hi @achatpc ,

We are trying to reproduce the issue but we  are not able to reproduce.
We are Expected results all working fine in magento 2.4.4 instance.

For reference here i attached the screenshots:
![2](https://user-images.githubusercontent.com/60198592/184129174-5c6e29aa-48f7-4d2a-a018-23968354ef62.png)
![1](https://user-images.githubusercontent.com/60198592/184129186-f14a5c63-9c4a-4009-888f-6ccbae92ed41.png)

Steps to reproduce:
1.Install Magento 2.4.4 instance
2.Upgrade the instance
3.compile the instance
4. all working fine


Let us Know if we are miss anything....

Thanks!!!

**Comment by achatpc** [comment]
Now try to upgrade to 2.4.5 version.

Can you provide me all uograde step ?

**Comment by johncy65** [comment]
I'm getting this error on 2.4.5

**Comment by engcom-Dash** [comment]
Hi @achatpc ,

We got Same Result after updating the magento version 2.4.5

Here I attached Screenshots for your Reference...

![Screenshot from 2022-08-12 16-11-10](https://user-images.githubusercontent.com/60198592/184339240-30c73c2f-c2fc-45c1-bbc3-1804430e7d97.png)
![Screenshot from 2022-08-12 16-10-57](https://user-images.githubusercontent.com/60198592/184339438-3ebd05fd-cc8a-4d49-b2a2-c0a18316dcb8.png)
![Screenshot from 2022-08-12 16-10-51](https://user-images.githubusercontent.com/60198592/184339496-16404b48-9576-4033-a679-74985187dd04.png)

Steps to Reproduce:
1.Install Magento 2.4.4 instance
2.Upgrade the instance --- "composer require magento/product-community-edition 2.4.5 --no-update"
3.Update the Composer ---- "composer update"
4.Compile the Instance -- "bin/magento  setup:di:compile"
5. all working fine

Let us Know if We are Missing anything...

Thanks!!!

**Comment by devprofun** [comment]
Please check in app/etc/config.php if modules Magento_AdobeIms and Magento_AdobeImsApi are enabled.
I had the same problem, but it worked after enabling both modules and cleaning cache directory manually.

**Comment by johncy65** [comment]
Turns out it had to do something with Redis. After running `redis-cli flushall` it worked.

**Comment by achatpc** [comment]
> 

Hello, thank you, this fix issue!

**Comment by achatpc** [comment]
> Please check in app/etc/config.php if modules Magento_AdobeIms and Magento_AdobeImsApi are enabled. I had the same problem, but it worked after enabling both modules and cleaning cache directory manually.


Hello, thank you, this fix issue!

**Comment by Viktorja1** [comment]
@magento give me 2.4-develop instance

**Comment by Rusllana** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by Rusllana** [comment]
@magento give me 2.4-develop instance
