### ISSUE TITLE
jquery.cookie dependency leads to JS issues with KO dependencies

### ISSUE THREAD

**Issue by sidolov** [magento/magento2#35913]
### Preconditions and environment

- 2.4.5

### Steps to reproduce

From Twitter: 

https://twitter.com/jissereitsma/status/1557372818257485834
I'm not getting this entirely yet, but a custom [#magento](https://twitter.com/hashtag/magento?src=hashtag_click) 2.4.5 install had a theme with a global Require dep for "jquery/jquery.cookie": This suddenly caused all of the other JS (like KO) to fail silently.

https://twitter.com/jissereitsma/status/1557391198863638530
My theme had a requirejs-config.js with a global "dep" for "jquery/jquery.cookie". Simply because of that, an add-to-cart was not weird: The AJAX call towards the addtocart URL worked fine, with a valid reply. But then the customerData AJAX call was never made ... :o I'm baffled

https://twitter.com/vovayatsyuk/status/1557399058435686400
Looks like Magento can't load the same dependency using different names. You load 'js-cookie/cookie-wrapper' with 'jquery/jquery.cookie' alias, while magento load the same file using 'js-cookie/cookie-wrapper' string.
Can be fixed at https://github.com/magento/magento2/blob/2.4-develop/lib/web/js-storage/js.storage.js#L17 

@jissereitsma , @vovayatsyuk please, add additional information if I missed something

### Expected result

It's possible to use aliases for jquery/jquery.cookie

### Actual result

Issue caused all of the other JS (like KO) to fail silently.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xmav** [comment]
Hello @jissereitsma 
Could you please check if that patch resolve issue for you ?

```
---
 lib/web/jquery/jquery.cookie.js                       | 11 +++++++++++
 lib/web/js-storage/js.storage.js                      |  2 +-
 .../module-theme/view/base/requirejs-config.js        |  1 -
 3 files changed, 12 insertions(+), 2 deletions(-)
 create mode 100644 lib/web/jquery/jquery.cookie.js

diff --git a/lib/web/jquery/jquery.cookie.js b/lib/web/jquery/jquery.cookie.js
new file mode 100644
index 000000000..5268ae4ea
--- /dev/null
+++ b/lib/web/jquery/jquery.cookie.js
@@ -0,0 +1,11 @@
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+
+define([
+    'jquery',
+    'js-cookie/cookie-wrapper'
+], function () {
+
+});
diff --git a/lib/web/js-storage/js.storage.js b/lib/web/js-storage/js.storage.js
index b016fc0aa..0ac802854 100644
--- a/lib/web/js-storage/js.storage.js
+++ b/lib/web/js-storage/js.storage.js
@@ -14,7 +14,7 @@
 (function (factory) {
     var registeredInModuleLoader = false;
     if (typeof define === 'function' && define.amd) {
-        define(['jquery', 'js-cookie/cookie-wrapper'], factory);
+        define(['jquery', 'jquery/jquery.cookie'], factory);
         registeredInModuleLoader = true;
     }
     if (typeof exports === 'object') {
diff --git a/vendor/magento/module-theme/view/base/requirejs-config.js b/vendor/magento/module-theme/view/base/requirejs-config.js
index 06e17f76d..911ff329d 100644
--- a/vendor/magento/module-theme/view/base/requirejs-config.js
+++ b/vendor/magento/module-theme/view/base/requirejs-config.js
@@ -68,7 +68,6 @@ var config = {
         'jquery/validate': 'jquery/jquery.validate',
         'jquery/file-uploader': 'jquery/fileUploader/jquery.fileuploader',
         'prototype': 'legacy-build.min',
-        'jquery/jquery.cookie': 'js-cookie/cookie-wrapper',
         'jquery/jquery-storageapi': 'js-storage/storage-wrapper',
         'text': 'mage/requirejs/text',
         'domReady': 'requirejs/domReady',
-- 
```

**Comment by pgosselin82** [comment]
@sidolov I had a similar issue. Deleting lib/web and running a composer install to recreate the files solved this for me.

**Comment by khoimm92** [comment]
I am also experiencing this. For example, if call `jquery.cookie` as dependency on the `default.xml` layout
```
requirejs([
        'jquery',
        'jquery/jquery.cookie',
    ], function ($) {
});
```
Then:
- Header welcome message
- Minicart
- Checkout button ...
 
will not working

**Comment by andrewbess** [comment]
Hello @khoimm92 
The provided fix resolves problem described by you.
We checked it.
Thank you for your collaboration

**Comment by jissereitsma** [comment]
@xmav  Sorry for the delay. As mentioned I actually fixed the issue for myself earlier. But I tested out things out, and indeed the fix is good! Many thanks! Also thanks @sidolov @vovayatsyuk for helping along with this.

**Comment by achatpc** [comment]
> Hello @jissereitsma Could you please check if that patch resolve issue for you ?
> 
> ```
> ---
>  lib/web/jquery/jquery.cookie.js                       | 11 +++++++++++
>  lib/web/js-storage/js.storage.js                      |  2 +-
>  .../module-theme/view/base/requirejs-config.js        |  1 -
>  3 files changed, 12 insertions(+), 2 deletions(-)
>  create mode 100644 lib/web/jquery/jquery.cookie.js
> 
> diff --git a/lib/web/jquery/jquery.cookie.js b/lib/web/jquery/jquery.cookie.js
> new file mode 100644
> index 000000000..5268ae4ea
> --- /dev/null
> +++ b/lib/web/jquery/jquery.cookie.js
> @@ -0,0 +1,11 @@
> +/**
> + * Copyright © Magento, Inc. All rights reserved.
> + * See COPYING.txt for license details.
> + */
> +
> +define([
> +    'jquery',
> +    'js-cookie/cookie-wrapper'
> +], function () {
> +
> +});
> diff --git a/lib/web/js-storage/js.storage.js b/lib/web/js-storage/js.storage.js
> index b016fc0aa..0ac802854 100644
> --- a/lib/web/js-storage/js.storage.js
> +++ b/lib/web/js-storage/js.storage.js
> @@ -14,7 +14,7 @@
>  (function (factory) {
>      var registeredInModuleLoader = false;
>      if (typeof define === 'function' && define.amd) {
> -        define(['jquery', 'js-cookie/cookie-wrapper'], factory);
> +        define(['jquery', 'jquery/jquery.cookie'], factory);
>          registeredInModuleLoader = true;
>      }
>      if (typeof exports === 'object') {
> diff --git a/vendor/magento/module-theme/view/base/requirejs-config.js b/vendor/magento/module-theme/view/base/requirejs-config.js
> index 06e17f76d..911ff329d 100644
> --- a/vendor/magento/module-theme/view/base/requirejs-config.js
> +++ b/vendor/magento/module-theme/view/base/requirejs-config.js
> @@ -68,7 +68,6 @@ var config = {
>          'jquery/validate': 'jquery/jquery.validate',
>          'jquery/file-uploader': 'jquery/fileUploader/jquery.fileuploader',
>          'prototype': 'legacy-build.min',
> -        'jquery/jquery.cookie': 'js-cookie/cookie-wrapper',
>          'jquery/jquery-storageapi': 'js-storage/storage-wrapper',
>          'text': 'mage/requirejs/text',
>          'domReady': 'requirejs/domReady',
> -- 
> ```

Working fine for me!

**Comment by achatpc** [comment]
https://github.com/magento/magento2/commit/bc2b48a284888d33e5300df29f6c81a354822d64

**Comment by shikharainabounteous** [comment]
Is this patch released? I am facing this issue on ver. 2.4.5-p1 also.

**Comment by Keivanph** [comment]
That patch fixed my issue on M2.4.5-p2
tnx.
I had similar issue, the proceed to checkout button was not working. Add to cart was not showing any notifications that a product is added to a cart.

**Comment by st-minhho2** [comment]
Thanks @xmav , Working fine for me! Magento 2.4.5 patch 12.
