### ISSUE TITLE
Unable to sort catalog by Custom Attribute of type Dropdown

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#35920]
### Preconditions and environment

- 2.4.5
- Sample data

### Steps to reproduce

To test this, we will create a test attribute and assign values to the products in the sample data category "Bag", and then attempt to sort by the test attribute.

```
- Stores -> Attributes -> Product
 - Add New Attribute
  - Properties Tab
   - Default Label = test
   - Catalog Input Type for Store Owner = Dropdown
   - Add Option "first"
   - Add Option "second"
   - Add Option "third"
   - Add Option "fouth"
```

![image](https://user-images.githubusercontent.com/30697781/184317313-a1883977-9957-4c50-b72b-5b0ac5ba8cbb.png)

```
  - Storefront Properties Tab
   - Used for sorting in product listing = Yes
  - Leave all other options as default
 - Save Attribute
``` 

```
- Stores >Attributes -> Attribute Set
 - Select Bag
 - Drag test attribute into Product Details group
- Save
``` 

```
- Catalog -> Products -> Add filter to only show products in Attribute Set "Bag"
- Configure the following products to have test attribute values
```

- Joust 24-MB01 - fourth
- Fusion 24-MB02 - third
- Crown Summit 24-MB03 - second
- Strive 24-MB04 - first
- Wayfarer 24-MB05 - fourth
- Rival Field 24-MB06 - third

To make testing easier, remove all other products that have attribute set of "Bag" to leave only the above 6 items in the filtered view.

![image](https://user-images.githubusercontent.com/30697781/184318784-cdbe17db-0d79-4861-8e7c-bc82275d3298.png)

```
- Clear cache
- Go to frontend and browse to the Bag category.
- Sort by test
```
### Expected result

The products should be ordered by test attribute. (Attribute value in brackets)

1. Strive (first)
2. Crown Summit (second)
3. Fusion (third)
4. Rival Field (third)
5. Joust (fourth)
6. Wayfarer (fourth)

### Actual result

![image](https://user-images.githubusercontent.com/30697781/184318162-912d21b0-3c58-4b5e-aae8-0c9e3b833633.png)

### Release note

Products can now be sorted on the Product Listing pages by custom attribute of Dropdown type.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @gwharton ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4.5 instance , we could not find out manage options at Stores-->Attributes-->Product. Please review the steps provided.

![new_prod1](https://user-images.githubusercontent.com/51681379/184932815-7a097f62-602c-4a71-b515-8162671198f8.png)
![NewProduct_2](https://user-images.githubusercontent.com/51681379/184932832-a829f9d9-11be-4c22-9067-bf0e7284a487.png)

**Comment by gwharton** [comment]
I have updated the steps to reproduce with more detailed layout of required steps to reproduce.

**Comment by gwharton** [comment]
@magento give me 2.4-develop instance

**Comment by gwharton** [comment]
Confirmed on 2.4-develop instance.
![image](https://user-images.githubusercontent.com/30697781/185086342-d941e378-8551-4aad-97e4-544a12904416.png)

**Comment by glo11468** [comment]
Hi @gwharton ,

Thank you for providing inputs and we tried to reproduce the issue on Magento 2.4 develop , issue is reproducible.
Hence , issue has been confirmed.

Please find below screenshots for reference.

on backend setup:

<img width="1347" alt="Screenshot 2022-08-19 at 3 31 36 PM" src="https://user-images.githubusercontent.com/90306034/185596434-159ace5c-ba24-4488-b85c-6e34661905e5.png">

**On frontend**
<img width="1440" alt="Screenshot 2022-08-19 at 3 26 47 PM" src="https://user-images.githubusercontent.com/90306034/185596765-fbc4eba0-c261-46e0-b2fb-17f977b66080.png">

**Comment by engcom-Delta** [comment]
Hi @gwharton ,

Thank you for providing inputs and we tried to reproduce the issue on Magento 2.4 develop , issue is reproducible.
Hence , issue has been confirmed.

Please find below screenshots for reference.

on backend setup:

<img width="1347" alt="Screenshot 2022-08-19 at 3 31 36 PM" src="https://user-images.githubusercontent.com/90306034/185596434-159ace5c-ba24-4488-b85c-6e34661905e5.png">

**On frontend**
<img width="1440" alt="Screenshot 2022-08-19 at 3 26 47 PM" src="https://user-images.githubusercontent.com/90306034/185596765-fbc4eba0-c261-46e0-b2fb-17f977b66080.png">

**Comment by Rusllana** [comment]
@magento give me 2.4-develop instance

**Comment by NetStorm84** [comment]
@magento give me 2.4-develop instance

**Comment by codebase-md** [comment]
Hello everybody,

I ran into the same problem. I think the root of this evil lies in \Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::categoryProductByCustomSortOrder. Here a completly new select statement is build which erases former table joins. Due to this circumstance custom sorting is not possible on category pages. Preconditions are that you are on a category page and you have enabled `cataloginventory/options/show_out_of_stock`.

I created a patch which fixes this behavior but can't promise it's a correct solution. Feedback is welcome:

```
Index: vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	(date 1662547508268)
@@ -213,17 +213,12 @@
         $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
 
         $connection = $this->collection->getConnection();
-        $query = clone $connection->select()
+        $query = clone $this->collection->getSelect()
             ->reset(\Magento\Framework\DB\Select::ORDER)
             ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
-            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
-            ->reset(\Magento\Framework\DB\Select::COLUMNS);
-        $query->from(
-            ['e' => $this->collection->getTable('catalog_product_entity')],
-            ['e.entity_id']
-        );
+            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
+
         $this->stockStatusApplier->setSearchResultApplier(true);
-        $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
         $query->join(
             ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
             'cat_index.product_id = e.entity_id'
```

**Comment by rogerdz** [comment]
I don't know why it is need create a collection for filtering and sorting using mysql. It should be action in elasticsearch (include move out stock product to bottom of list).
I created a PR for this idea https://github.com/magento/magento2/pull/36102

**Comment by jmonrove** [comment]
Still present on EE 2.4.5-p4
Setting OOO products to no display is a really bad SEO practice.
