### ISSUE TITLE
webapi issue main.CRITICAL: LogicException: The "OrderInterface[]" class doesn't exist and the namespace must be specified. Verify and try again.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35942]
### Preconditions and environment

- Magento version
2.4.5 open source
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Check webservice availability:

https://www.xxxxx.com/soap/default?wsdl&services=backendModuleServiceV1

### Expected result

No error and webservice available list

### Actual result

[2022-08-13T14:59:02.868044+00:00] main.CRITICAL: LogicException: The "OrderInterface[]" class doesn't exist and the namespace must be specified. Verify and try again. in /var/www/html/vendor/magento/framework/Reflection/TypeProcessor.php:147
Stack trace:
#0 /var/www/html/vendor/magento/module-webapi/Model/Config/ClassReflector.php(105): Magento\Framework\Reflection\TypeProcessor->register()
#1 /var/www/html/vendor/magento/module-webapi/Model/Config/ClassReflector.php(73): Magento\Webapi\Model\Config\ClassReflector->extractMethodData()
#2 /var/www/html/vendor/magento/module-webapi/Model/ServiceMetadata.php(141): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods()
#3 /var/www/html/vendor/magento/module-webapi/Model/ServiceMetadata.php(175): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata()
#4 /var/www/html/vendor/magento/module-webapi/Model/ServiceMetadata.php(198): Magento\Webapi\Model\ServiceMetadata->getServicesConfig()
#5 /var/www/html/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(367): Magento\Webapi\Model\ServiceMetadata->getServiceMetadata()
#6 /var/www/html/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(172): Magento\Webapi\Model\Soap\Wsdl\Generator->getServiceMetadata()
#7 /var/www/html/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(375): Magento\Webapi\Model\AbstractSchemaGenerator->getAllowedServicesMetadata()
#8 /var/www/html/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(107): Magento\Webapi\Model\Soap\Wsdl\Generator->getAllowedServicesMetadata()
#9 /var/www/html/vendor/magento/module-webapi/Controller/Soap.php(134): Magento\Webapi\Model\AbstractSchemaGenerator->generate()
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Soap->dispatch()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Soap\Interceptor->___callParent()
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Soap\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/generated/code/Magento/Webapi/Controller/Soap/Interceptor.php(23): Magento\Webapi\Controller\Soap\Interceptor->___callPlugins()
#14 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Soap\Interceptor->dispatch()
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#19 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#20 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#21 {main}

### Additional information

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
<env:Body>
<env:Fault>
<env:Code>
<env:Value>env:Receiver</env:Value>
</env:Code>
<env:Reason>
<env:Text xml:lang="fr">Internal Error. Details are available in Magento log file. Report ID: webapi-62f7beb20ad79</env:Text>
</env:Reason>
</env:Fault>
</env:Body>
</env:Envelope>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by achatpc** [comment]
After long time of investigation, i can not reproduce issue on fresh install.
Downgrade Magento to 2.4.4 version not solve my issue.

Anymore can help me to identify source of this issue ? I can not see any details on log about module related with this error. I have tested with all vendor tierce module disabled but withou success.

Thank you in advance.

**Comment by engcom-November** [comment]
Hi @achatpc ,
Verified the issue on both 2.4.5 project-community-edition and 2.4-develop instance as well but could not reproduce the issue.
![image](https://user-images.githubusercontent.com/60198231/185364707-8e97525c-2c2a-4afe-9c2f-866a57f42994.png)
![image](https://user-images.githubusercontent.com/60198231/185364960-95817523-5b1b-4e81-8911-7f8063337ecb.png)
Kindly check the Magento [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) or any 3rd party extensions / modules enabled is causing this issue. Please elaborate the issue / steps if you are still facing any issues.
Thank you.

**Comment by achatpc** [comment]
I can sea this with grep:

magento_user@achatpc:/var/www/html$ grep -r 'OrderInterface\[\]'
vendor/amasty/module-extra-fee/Block/Sales/CreditMemo/Create/Fee.php:     * @return ExtrafeeOrderInterface[]
vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/RequestInterface.php:     * @return SortOrderInterface[]
vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php:     * @return SortOrderInterface[]
vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/SortOrder/Builder.php:     * @param SortOrderInterface[] $sortOrders Sort orders specification.
vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request.php:     * @param SortOrderInterface[] $sortOrders     Sort orders specification.
vendor/shoppingfeed/magento2-manager/Model/Marketplace/Order/Manager.php:     * @return OrderInterface[]
vendor/shoppingfeed/magento2-manager/Model/Marketplace/Order/Manager.php:     * @return OrderInterface[]
vendor/shoppingfeed/magento2-manager/Model/Sales/Order/Importer.php:     * @param MarketplaceOrderInterface[] $marketplaceOrders
vendor/shoppingfeed/magento2-manager/Model/Sales/Order/Shipment/Track/Collector.php:     * @param OrderInterface[]|int[] $orders
vendor/shoppingfeed/magento2-manager/Model/Sales/Order/ImporterInterface.php:     * @param MarketplaceOrderInterface[] $marketplaceOrders
vendor/shoppingfeed/magento2-manager/Model/Sales/Order/SyncerInterface.php:     * @param MarketplaceOrderInterface[] $marketplaceOrders
vendor/geissweb/module-euvat/Plugin/OrderManagement.php:     * @return \Magento\Sales\Api\Data\OrderInterface[]
vendor/classyllama/module-zendesk/Model/OrderRepository.php:        /** @var OrderInterface[] $zendeskOrders */
vendor/classyllama/module-zendesk/Api/OrderRepositoryInterface.php:     * @return OrderInterface[]
vendor/magento/module-inventory-in-store-pickup-sales/Model/SourceSelection/GetOrderItemsByOrdersListAndSku.php:     * @param OrderInterface[] $orders
vendor/magento/module-inventory-in-store-pickup-sales/Model/SourceSelection/GetSourceItemQtyAvailableService.php:     * @return OrderInterface[]
vendor/magento/magento2-base/dev/tests/api-functional/testsuite/Magento/GraphQl/Sales/RetrieveOrdersByOrderNumberTest.php:        /** @var \Magento\Sales\Api\Data\OrderInterface[] $orders */
vendor/magento/module-gift-message/Model/OrderItemRepository.php:     * @var \Magento\Sales\Api\Data\OrderInterface[]
vendor/magento/module-sales/Model/OrderRepository.php:     * @var OrderInterface[]
vendor/magento/module-sales/Api/Data/OrderSearchResultInterface.php:     * @return \Magento\Sales\Api\Data\OrderInterface[] Array of collection items.
vendor/magento/module-sales/Api/Data/OrderSearchResultInterface.php:     * @param \Magento\Sales\Api\Data\OrderInterface[] $items
vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping/PlaceOrderInterface.php:     * @param OrderInterface[] $orderList
vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping/PlaceOrderPool.php:     * @var PlaceOrderInterface[] | TMap
vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php:            /** @var OrderInterface[] $failedOrders */
vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php:            /** @var OrderInterface[] $successfulOrders */
vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php:     * @param OrderInterface[] $orders
vendor/magento/module-multishipping/Test/Unit/Model/Checkout/Type/Multishipping/PlaceOrderPoolTest.php:     * @param PlaceOrderInterface[] $placeOrderList
dev/tests/api-functional/testsuite/Magento/GraphQl/Sales/RetrieveOrdersByOrderNumberTest.php:        /** @var \Magento\Sales\Api\Data\OrderInterface[] $orders */

I have disable all related vendor module and i have make test. Issue not solved...

I become crazy....

**Comment by achatpc** [comment]
Founded and fixed my issue.

Whas related with classyllama/module-zendesk.

Special thanks to Amasty support for help.
Patch attached in this post.

[zendesk patch.zip](https://github.com/magento/magento2/files/9387151/zendesk.patch.zip)

@magento/classy-llama

**Comment by achatpc** [comment]
I can not see update from Classy-llama team.

I thy to cite somes users from organisation.

Thank you in advance.

@magento/classy-llama 
@rtull 
@jonathanhodges
@mttjohnson
