### ISSUE TITLE
Magento\Catalog\Model\Category\FileInfo::removeStorePath(): Argument #1 ($path) must be of type string, array given, called in /vendor/magento/module-catalog/Model/Category/FileInfo.php

### ISSUE THREAD

**Issue by keval1415** [magento/magento2#35959]
I'm Having below issue while bulk select products in category.

Note : Magento has Upgraded to 2.4.4 Enterprise Cloud Edition. 

Magento\Catalog\Model\Category\FileInfo::removeStorePath(): Argument #1 ($path) must be of type string, array given, called in /vendor/magento/module-catalog/Model/Category/FileInfo.php

![image](https://user-images.githubusercontent.com/100849655/185066195-36497703-7f0e-4965-a009-fa1e03460e73.png)

![image](https://user-images.githubusercontent.com/100849655/185065501-78cb35f1-be6d-43ca-9aed-dc58beb73b5d.png)

I Have Tried to Convert It into String but After That It's throw error from another file then i have did same thing but it's throwing error's from different different files.

Expected Result : Products in Category have to save by select in bulk.
Actual Result :  Magento\Catalog\Model\Category\FileInfo::removeStorePath(): Argument #1 ($path) must be of type string, array given, called in /vendor/magento/module-catalog/Model/Category/FileInfo.php

**Comment by engcom-Delta** [comment]
Hi @keval1415 ,
Thank you for raising an issue . We are happy to assist you , Please provide detailed issue description, actual results and logs or screenshots if required.

Thanks

**Comment by engcom-Delta** [comment]
Hi @keval1415,

We have noticed that, this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
