### ISSUE TITLE
Custom module structure - Composer dependencies

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3595]
Having custom vendor module e.g. `Acme_Demo` located in `app/code/Acme/Demo` it's not clear how it's composer.json should be utilized.
Based on [Create your component file structure](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/build/module-file-structure.html) - `composer.json: Specifies component dependencies. For more information, see Composer integration.`

Let's say `Acme_Demo` has a dependency on `cocur/slugify` - so naturally You would specify such dependency in `app/code/Acme/Demo/composer.json`.

Given such scenario(which is basically for all custom modules You would buy/get from custom vendors unless they put it for free on [Packagist](https://packagist.org/)):
- custom module dependencies must be defined in it's own composer.json(how Composer is intended to be used)
- to actually get it working You would need to define the same dependencies in Your root composer.json

So **the questions**:
- How should custom modules composer.json be utilized?
- What is the M2 idea of Composer integration with custom modules and resolving their dependencies?

**Comment by vrann** [comment]
@werdlv that's a good question.

You are right, composer.json in the app/code/Acme/Demo is not used for the dependencies management (I'll later show explain it's needed). However when you complete the development of the module, you may decide to publish it as a composer package, let's say on Magento Marketplace or just in your local composer repository. At  this point of time, composer.json will define your module as a composer package and all dependencies listed there will be used to manage dependencies of the project which uses your package.

Now, why composer.json is required before you are publishing package:
- module will not be visible in [Component Manager](http://devdocs.magento.com/guides/v2.0/comp-mgr/compman-start.html)
- ultimately every module should become a composer package, when it get re-used in different project

**Comment by jsakars** [comment]
@vrann thanks for clarification! ;)
