### ISSUE TITLE
Admin Users unable to change front-end Logo in Design Config when in Single Store Mode

### ISSUE THREAD

**Issue by CadenceLabs-AndrewS** [magento/magento2#35952]
### Preconditions and environment

M2.4.4

php8.1
nginx
Multi website store

### Steps to reproduce
1. Setup Multi website store
2. Design Config (Content -> Design -> Config) - Edit Store view level - upload image under Header and save
3. Cache clean
4. Enable Single Store Mode
5. Design Config (Content -> Design -> Config) - Edit for Website - Upload another image under Header and save 
6. Header tab expand -> Logo
7. Upload new logo file notdefaultlogo.jpg
8. flush caches 
9. reload front end 

### Expected result

Display the new uploaded logo, notdefaultlogo.jpg

### Actual result

Displays default fallback magento svg logo

### Additional information

Related to Scope and SingleStoreMode

`vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php`
Logo Path Resolver explicitly passes store scope

`    /**
     * Return logo image path
     *
     * @return string|null
     */
    public function getPath(): ?string
    {
        $path = null;
        $storeLogoPath = $this->scopeConfig->getValue(
            'design/header/logo_src',
            ScopeInterface::SCOPE_STORE
        );
        if ($storeLogoPath !== null) {
            $path = Logo::UPLOAD_DIR . '/' . $storeLogoPath;
        }
        return $path;
    }`
    
    Debugged:
    
`$this->scopeConfig->getValue('design/header/logo_src','store');`
returns: "stores/1/logo_1.png"
`$this->scopeConfig->getValue('design/header/logo_src','website');`
returns: "websites/1/notdefaultlogo.jpg"
`$this->scopeConfig->getValue('design/header/logo_src');`
returns: null

I did not mark as S0 severity, but I believe it is considering it is site identity(logo) and an admin user can not resolve this without disabling single store mode - which is not a real resolution to the issue.

Additionally it looks like single store mode and scope has been an ongoing issue across many items:
https://github.com/magento/magento2/issues/22344

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by CadenceLabs-AndrewS** [comment]
Patch
`--- a/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
+++ b/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
@@ -39,9 +39,13 @@ class LogoPathResolver implements LogoPathResolverInterface, ArgumentInterface
     public function getPath(): ?string
     {
         $path = null;
+        $scope = ScopeInterface::SCOPE_STORE;
+        if ($this->scopeConfig->getValue('general/single_store_mode/enabled') === "1") {
+            $scope = ScopeInterface::SCOPE_WEBSITE;
+        }
         $storeLogoPath = $this->scopeConfig->getValue(
             'design/header/logo_src',
-            ScopeInterface::SCOPE_STORE
+            $scope
         );
         if ($storeLogoPath !== null) {
             $path = Logo::UPLOAD_DIR . '/' . $storeLogoPath;
`

**Comment by engcom-November** [comment]
Hi @CadenceLabs-AndrewS Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.
Newly uploaded logo.jpg is displayed as expected on front-end when single store mode is enabled. Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/184895498-839a4609-75fa-4f71-8386-9fab8180958e.png)
Thank you.

**Comment by CadenceLabs-AndrewS** [comment]
To clarify, a logo should be uploaded to the initial store and storeview before changing the site to singlestoremode.
Then after the change to single store mode, design config edit website and upload new logo with different filename.

**Comment by CadenceLabs-AndrewS** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @CadenceLabs-AndrewS ,
If the logo is changed for Website under design - Configuration, logo is not changed regardless of single store mode enabled or disabled. Logo is changed when uploaded for Store View which is the default behavior of Magento. Verified the same without and with enabling single store view mode and the issue is not reproducible if logo uploaded for store view. Logo updated as expected on front-end. Also checked updating logo for website with and without enabling single store mode and the new logo is not updated in both the cases. Please check the behavior on Magento 2.4-develop branch and provide missing steps if any if you are still facing any issues.
Thank you.

**Comment by CadenceLabs-AndrewS** [comment]
I just confirmed this with a fresh install of 2.4.4

Step 1:
Design Config -> add Logo to StoreView & Save & Flush Cache

Frontend Result:
![Screenshot from 2022-08-20 12-15-28](https://user-images.githubusercontent.com/93620501/185756663-13312b13-7e2e-4bc6-ab98-3d12ff493e58.png)
Admin Result:
![Screenshot from 2022-08-20 12-15-34](https://user-images.githubusercontent.com/93620501/185756674-2aec840a-403f-409a-ad51-808c3a2933d4.png)

Is Expected Results? :heavy_check_mark: 

Step 2:
Update store config and change to Single Store Mode (enabled)

Frontend Result:
Same as Step 1, Incorrect

Admin Result:
![Screenshot from 2022-08-20 12-18-14](https://user-images.githubusercontent.com/93620501/185756778-635eb1c6-7471-4b66-a6ab-517d5cb532e4.png)
![Screenshot from 2022-08-20 12-18-23](https://user-images.githubusercontent.com/93620501/185756791-434191a5-8798-4470-a4db-6c9d9d5978cf.png)


Why is this wrong? 
When a store is changed to single store mode - the design config values should pull from the default/website config.
The logo resolver added in 2.4.3 explicitly passes the store scope which disconnects the admin expectations, when updating the current website design config, to what renders on the frontend.

The frontend should match the current scoped config in the admin. The logo should be pulled from the current default/website config when in single store mode.

**Comment by engcom-November** [comment]
Thanks for the update @CadenceLabs-AndrewS . Re verified the issue again on Magento 2.4-develop branch and the issue is reproducible. Hence updating the description and confirming the issue.

**Comment by monteshot** [comment]
@magento I am working on this
