### ISSUE TITLE
Special prices vs flat catalog with different store view

### ISSUE THREAD

**Issue by modryk** [magento/magento2#35954]
### Preconditions and environment

Magento ver: 2.3.5 p2

Price range to store. 10 store views on different stores. Stores with EUR, PLN, CZK and HUF currencies. For default store view currency is PLN

### Steps to reproduce

1. Turn on flat catalog and flat products
2. Set up default store view
3. Add another web with different store and different store view (lets say that default view is X and another view is Y)
4. Set up price range on store (not global)
5. Set currency on X to PLN and on Y to CZK
6. Create product called PRODUCT. On view X set price 800 and special price 300. On view Y set price 2000 and leave special price empty (without checking to get from default value)
7. Reindex flat catalog
8. Search PRODUCT on each store frontend

### Expected result

On X view price is 800 and special price is 300. On Y view price should be 2000 without special price.

### Actual result

On X view price is 800 and special price is 300. On Y view price is 2000 and special price is 300. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @modryk,

Thank you for reporting and collaboration.

As per Magento Document to enable flat catalog and flat products is no longer recommended as a best practice.

Please refer this [document](https://docs.magento.com/user-guide/catalog/catalog-flat.html).

Kindly provide further information.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @modryk,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by madbounce** [comment]
@magento give me 2.4.2 instance
