### ISSUE TITLE
Notice: Undefined index: value in /app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Select.php on line 72

### ISSUE THREAD

**Issue by gnusmus** [magento/magento2#3596]
I am getting following notice when choose order page in admin panel. 
I am getting this notice when set transaction id in my payment module.

Notice: Undefined index: value in /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Select.php on line 72
#0 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Widget/Grid/Column/Filter/Select.php(72): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/gnusmus/s...', 72, Array)
#1 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Widget/Grid/Column.php(488): Magento\Backend\Block\Widget\Grid\Column\Filter\Select->getHtml()
#2 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/view/adminhtml/templates/widget/grid/column_set.phtml(42): Magento\Backend\Block\Widget\Grid\Column->getFilterHtml()
#3 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/home/gnusmus/s...')
#4 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid\ColumnSet), '/home/gnusmus/s...', Array)
#5 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/gnusmus/s...')
#6 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#7 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#9 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#10 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#11 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', true)
#12 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(497): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', true)
#13 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid.columnSet')
#14 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/home/gnusmus/s...')
#15 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), '/home/gnusmus/s...', Array)
#16 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/gnusmus/s...')
#17 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#18 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#19 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#21 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#22 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#23 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', false)
#24 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Text/ListText.php(26): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', false)
#25 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Text\ListText->_toHtml()
#26 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Widget/Tabs.php(387): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/view/adminhtml/templates/widget/tabs.phtml(57): Magento\Backend\Block\Widget\Tabs->getTabContent(Object(Magento\Sales\Block\Adminhtml\Order\View\Tab\Transactions))
#28 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/home/gnusmus/s...')
#29 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\View\Tabs), '/home/gnusmus/s...', Array)
#30 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/gnusmus/s...')
#31 /home/gnusmus/samba/public_html/magento2.local/app/code/Magento/Backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#32 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#33 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('sales_order_tab...')
#35 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales_order_tab...')
#36 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales_order_tab...')
#37 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales_order_tab...', true)
#38 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('sales_order_tab...')
#39 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('left')
#40 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#41 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#42 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', true)
#43 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#44 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('side.col')
#45 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#46 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#47 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', true)
#48 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#49 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#50 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#51 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#52 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#53 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#54 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#55 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#56 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#57 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#58 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#59 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#60 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#61 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#62 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#63 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#64 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#65 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#66 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#67 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#68 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#69 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#70 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#71 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#72 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#73 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#74 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#75 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#76 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 /home/gnusmus/samba/public_html/magento2.local/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /home/gnusmus/samba/public_html/magento2.local/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#80 /home/gnusmus/samba/public_html/magento2.local/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#81 {main}

**Comment by mazhalai** [comment]
@gnusmus can you please help us reproduce this issue. What version of magento? How did you deploy magento? via git? via composer create-project or via zip from magento.com

**Comment by gnusmus** [comment]
@mazhalai.... I tried different versions (2.0.0, 2.0.2) and installed them in different ways, but the problem was everywhere ...For example, with this module https://github.com/Inchoo/magento2-Inchoo_Stripe I have the same problem

**Comment by mazhalai** [comment]
@gnusmus is this still an issue?

**Comment by mazhalai** [comment]
@gnusmus closing as non-responsive.

**Comment by Techytt** [comment]
@mazhalai I am still facing this issue, can you please help me on this?

**Comment by twosg** [comment]
Just have the same problem.
Magento 2.1.9 installed with composer.

It happens when I try to open an order view in admin, where the payment method was Braintree PayPal.

**Comment by madonzy** [comment]
@ParimalMakwana @twosg @gnusmus here is the PR that fixes this issue: https://github.com/magento/magento2/pull/12284

**Comment by magento-engcom-team** [comment]
Hi @gnusmus. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1289 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - b41594122f532f6a89165a70906a5b257562c0df
 - 7369261d82e0e5ad926eaf4ccb2a8def79c4fcbb
 - dce1c66301cdddfee2dc2887f584c333d0b438b2
 - 95ed67ee4adbbd7f3f0107a52da4b9238cf44803
 - 05fcdd1a52c674ea09a34960cea71e73488fbc99
 - 8b1a2972b3f0ddd4713d00055b8d60f737a72ce4
 - 90addb731c3b253d3da4dc564ddf94ac3525bd0f
 - d5c9eef075cd5f4d9781ec7f3151a14e087d061d
 - 6ec62717c16ed96d45e670d7f867b724f0449aaa
 - f0af87edad79b295b4be87f6f92502bacfbc2764
 - 2497062749bf41c80aaebb9b6cd21eb48656f58c
 - 1f7347f47cca48238f9deabd48a0a280bc0c309f
 - 0d151c41539ba7c4d20ede20d614bb4be257903c
 - 07982fdea19074788654c6e825874cb8188ab627
 - 617da6ca08607890779ce71530a2871438c88351
 - 39ed21f83071ebffd71963e9097ecb59fd906702
 - 9aa036dec42211867f68f714a746b71395c43bb2
 - fda37ef0af75e6b28d4a0da1781b19c7a7894a97
 - 47b109180b6b5e499ba8d82e6c67888fca21ffe8
 - ef6badace5c6b046047a6e5f617020f9d4410a82
 - 809ec050986fa3ddfeec4a715ce5ace1e41a4427

The fix will be available with the upcoming patch release.
