### ISSUE TITLE
Hard dependency on magento/module-admin-adobe-ims in magento/module-two-factor-auth

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#35962]
### Preconditions and environment

Magento 2.4.5

When removing `magento/module-admin-adobe-ims` from the codebase by using the "replace"  section in `composer.json`, `bin/magento setup:di:compile` fails because of a hard dependency on the fairly unrelated module `magento/module-two-factor-auth`. 

This constitutes bad separation of concerns.

### Steps to reproduce

- Install Magento 2.4.5
- Add this to the `replace` section in the `composer.json`;
```
        "magento/module-adobe-ims": "*",
        "magento/module-adobe-ims-api": "*",
        "magento/module-admin-adobe-ims": "*"
```
- Run `composer update`
- Run `bin/magento setup:di:compile`

### Expected result

Compile finishes correctly

### Actual result

```
Compilation was started.
%message% 0/9 [>---------------------------]   0% < 1 sec 81.0 
MiBProxies code generation... 0/9 [>------------------------]   0% < 1 sec 81.0 MiB
Proxies code generation... 1/9 [==>----------------------]  11% < 1 sec 89.0 MiB
Repositories code generation... 1/9 [==>-----------------]  11% < 1 sec 89.0 MiB
Repositories code generation... 2/9 [====>---------------]  22% 4 secs 208.0 MiB
Service data attributes generation... 2/9 [===>----------]  22% 4 secs 208.0 MiB
Service data attributes generation... 3/9 [====>---------]  [33% 4 secs 208.0 MiB
Application code generator... 3/9 [====>---------]  33% 4 secs 208.0 MiB
Application code generator... 4/9 [======>-------]  44% 10 secs 2[34%).0 MiB
Interceptors generation... 4/9 [======>-------]  44% 10 secs 234.0 MiB
                                                                               
  Class "Magento\AdminAdobeIms\Service\ImsConfig" does not exist               
  Class Magento\TwoFactorAuth\Observer\ControllerActionPredispatch\Intercepto  
  r generation error: The requested class did not generate properly, because   
  the 'generated' directory permission is read-only. If --- after running the  
   'bin/magento setup:di:compile' CLI command when the 'generated' directory   
  permission is set to write --- the requested class did not generate properl  
  y, then you must add the generated class object to the signature of the rel  
  ated construct method, only.
```

### Additional information

The workaround right now is to remove `module-adobe-ims*` modules from the replace section, so they are included in the codebase, which we don't want.

```
-        "magento/module-adobe-ims": "*",
-        "magento/module-adobe-ims-api": "*",
-        "magento/module-admin-adobe-ims": "*",
```

Another workaround is to also remove `magento/module-two-factor-auth` from the codebase, which is even less desirable. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **Magento 2.4.5** .

**Description:** Hard dependency on magento/module-admin-adobe-ims in magento/module-two-factor-auth

**Steps to reproduce:**

1. Install fresh 2.4.5
2. Add this to the `replace` section in the composer.json:
 ```
"replace": {
        "magento/module-adobe-ims": "*",
        "magento/module-adobe-ims-api": "*",
        "magento/module-admin-adobe-ims": "*"
    },
```

3. Run composer update.
4. Run bin/magento setup:di:compile.
5. Check the debug log.

**Expected result:** 
Compile finishes correctly

**Actual result:** 
Getting error 
![Screenshot from 2022-08-18 17-02-29](https://user-images.githubusercontent.com/60198022/185607549-c4036833-ca7d-474f-8941-4bcc2784ab41.png)

**Note:** It has been observed 2FA is disabled or enabled issue is same.

Hence, confirming the issue.

Thanks

**Comment by fredden** [comment]
It looks like this was added / introduced in https://github.com/magento/security-package/commit/32beaeb8a5f6c94a38ab5ed20ef90b4191fa2f33, but I can't find a pull request nor any context on GitHub.

**Comment by gfxguru** [comment]
Is there a work around to fix this issue ATM?

**Comment by peterjaap** [comment]
> Is there a work around to fix this issue ATM?

Yes, see my OP

**Comment by peterjaap** [comment]
Bytheway, this issue is very similar to https://github.com/magento/magento2/issues/35479 but it concerns `magento/module-new-relic-reporting` and `magento/module-graph-ql` in that case.

**Comment by sprankhub** [comment]
I suggest that the Magento core team uses https://github.com/yireo/Yireo_ExtensionChecker/ to make sure all dependencies are found :see_no_evil:

**Comment by andimov** [comment]
fixed in https://github.com/magento/security-package/commit/4f5e220d68c4165a954f07311b7c80de92c22638
