### ISSUE TITLE
Unable to pull order data

### ISSUE THREAD

**Issue by cstinson4508** [magento/magento2#35969]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by rostilos** [comment]
@magento add to contributors team

**Comment by engcom-Bravo** [comment]
Hi @cstinson4508,


Thank you for raising an issue.

Please help us to provide exact steps to reproduce and screenshots if possible provide us video in order to replicate the issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @cstinson4508,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Comment by cstinson4508** [comment]
Good afternoon,
I am unable to access data pertaining to our blockchain orders, the order below is a valid order and the record is not pulling up under blockchain  tab. I can also generally go the the customer tab and see the order by searching the customer email. However when I pull the customer – who has several blockchain orders, there is no history available.
***@***.***
