### ISSUE TITLE
Child theme should not override folders in web/css/source

### ISSUE THREAD

**Issue by cartok** [magento/magento2#35973]
### Preconditions and environment

- Magento version: 2.4.4

We use LUMA, have a base theme based on it and two other themes that base one the base theme. LESS folders do not get merged, they get overridden entirely.

Is that intended?

### Steps to reproduce

```
../base/web/css/source/foo/bar.less
../base/web/css/source/foo/1.less
../base/web/css/source/foo/2.less
../base/web/css/source/foo/3.less
../specific/web/css/source/foo/bar.less
../specific/web/css/source/foo/fluffykin.less
```

### Expected result

All files are loaded and `../specific/web/css/source/foo/bar.less` overrides `../base/web/css/source/foo/bar.less`

### Actual result

The whole directory `../specific/web/css/source/foo` is overridden

### Additional information

Also happens in theme module directories.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @cartok ,
Thank you for raising an issue , We are happy to assist you but we are not clear on steps provided to replicate the issue.
Please provide clear steps one by one.

Regards,

**Comment by cartok** [comment]
God forgive me, I was wrong here.
