### ISSUE TITLE
Uninstallation of extension got stuck

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35974]
Uninstallation of extension got stuck.
I ran `bin/magento module:uninstall -r -c <module>` and system is not replying anymore.

Should I remove`-r` and just run `bin/magento module:uninstall -c <module>` for uninstalling extension at backend?
![螢幕快照 2022-08-18 下午8 28 58](https://user-images.githubusercontent.com/110151530/185395126-5e08d9e4-d7d7-4450-aa76-4ab460e6c856.png)

Magento 2.4.4 Open Source
Composer 2.1.0

### Please let me know what is the best solution for complete uninstallation of extension to remove all related extension's files. Thank you Support Team!

**Comment by KrusLeung** [comment]
Excepted `composer remove <module name>` , how to use`bin/magento uninstall` command correctly delete related files?

**Comment by engcom-Hotel** [comment]
Hello @KrusLeung,

Thanks for the report and collaboration!

I would like to suggest you go through the below link for more details on uninstalling the module:

https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-uninstall-mods.html

Also please raise these kinds of tickets on [Magento StackExchange](https://magento.stackexchange.com/).

Thanks

**Comment by engcom-Hotel** [comment]
Dear @KrusLeung,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
