### ISSUE TITLE
Magento web install (Installing... 87%)

### ISSUE THREAD

**Issue by korbi1919** [magento/magento2#3597]
Web Install stack in 87% . 
left it an entire night with no chance. 
there's no clear information in the install.log : 
[Progress: 316 / 362]</span><br><span class="text-info">Module 'Magento_ProductVideo':</span><br><span class="text-info">Upgrading data.. </span><br><span class="hidden">[Progress: 317 / 362]</span><br><span class="text-info">**Module 'Magento_CatalogSampleData':**</span><br><span class="text-info">Installing data.. </span>
In my PHP.ini php_values : 
     memory_limit 256M
     max_execution_time=18000 (as recommended). 
a re-install doesn't change anything. (did it 3 times so far).
PS : i don't have ssh access to the hosted server (only FTP)
Any help please !!

**Comment by mazhalai** [comment]
Can you create a file called info.php with the following code:

```
<?php
phpinfo();
```

ftp this file to your server, open page on a browser and then check what is the value of  `max_execution_time`. Please confirm that it is the same as you have set. 

Also, have you tried restarting your apache/nginx after settings changes? 

Also, can you increase memory_limit to `memory_limit = 2048M` and try again?

**Comment by korbi1919** [comment]
Hi Mazhalai, 

Thanks for your answer. 
i've created the file on the server to check phpinfo(). it looks ok same as i configured it. 
i restarted also Apache and increased the memory_limit to 2048M. Unfortunately i am getting exactly the same issue. 

Any other investigations  ?

Thanks.

**Comment by mazhalai** [comment]
Options:
- Install via [CLI](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html)
- Turn on [developer mode](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) which gives more stack trace.

**Comment by mazhalai** [comment]
@korbi1919  closing due to non-responsiveness.
