### ISSUE TITLE
testing if issue repeat 

### ISSUE THREAD

**Issue by low-neotran** [magento/magento2#35977]

**Comment by low-neotran** [comment]
@magento-engcom-team give me 2.4.4 instance

**Comment by low-neotran** [comment]
@magento-engcom-team give me 2.4.5 instance

**Comment by engcom-Delta** [comment]
Hi @low-neotran ,
Thank you for raising an issue . We are happy to assist you , Kindly provide Summary of the issue,Information on your environment, Steps to reproduce, Expected and actual results.

Regards,
