### ISSUE TITLE
Unable to ship items with a qty > 0 and < 1

### ISSUE THREAD

**Issue by ArronKing** [magento/magento2#35971]
### Preconditions and environment

- 2.4.5 (and prior)
- Product must have qty uses decimals enabled and a minimum qty in cart below zero (i.e. 0.2)

### Steps to reproduce

1. Create simple product in admin
2. Enable qty uses decimals for the product
3. Set minimum qty in cart equal to 0.2
4. Create an order - adding a qty of 0.5 for the test product
5. Order / Invoice create correctly
6. Ship the order

### Expected result

Shipment is created with a qty of 0.5

### Actual result

Shipment "items" are blank and therefore, you cannot create shipment

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ArronKing** [comment]
@magento I am working on this

**Comment by ArronKing** [comment]
I've got a fix ready - I'm just confirming this on the latest version

**Comment by ArronKing** [comment]
Confirmed - issue is present on develop instance:
<img width="1732" alt="Screenshot 2022-08-18 at 10 57 36" src="https://user-images.githubusercontent.com/2041079/185368042-168da696-9a8c-4417-bac0-304445bfccdb.png">

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ArronKing ,

We are trying to reproduce the issue but we are not able to reproduce in 2.4.5 instance.

we are not able create order in customer view page.

Screenshots for your reference:

![Screenshot from 2022-08-18 16-59-04](https://user-images.githubusercontent.com/60198592/185384634-95402a95-a31e-4372-9900-66622106836a.png)
![Screenshot from 2022-08-18 16-51-20](https://user-images.githubusercontent.com/60198592/185384642-b6695317-49e5-4874-b222-d1cd0d7cb6c7.png)

Steps to reproduce:

1.Install 2.4.5 magento instance
2.Enable the decimal quantity in Back-end
3.Add the product to the card
4.Update the card with 0.5 quantity
5.Go to checkout
6.Trying to place the order...

should not able to place the order.....

Let us know if we are missing anything....

Thanks!!!

**Comment by ArronKing** [comment]
Hi

I agree with you - I can't place an order on the frontend either.

But... that's not the issue I've raised *

I've created an order in admin (000000003), which you can see in your develop instance. If you try to ship that, that's what shows the issue I've raised and PR fixes.

* Whilst it's not the issue I've raised, I think the inability to create an order on the frontend is related. I can create an order on the front end with a qty of 1.5 but not 0.5. Which is the same behaviour I reported in the shipment.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ArronKing ,

We are confirming the issue...and We can reproduce the issue in 2.4.5 magento instance.

Here attached the screenshots for your reference...
![Screenshot from 2022-08-22 16-16-32](https://user-images.githubusercontent.com/60198592/185904009-73909cac-dc70-480a-8594-fde53475cadc.png)
![Screenshot from 2022-08-22 16-13-15](https://user-images.githubusercontent.com/60198592/185904023-41ce3a94-5419-43c8-b320-1b2d95753947.png)

Steps to reproduce:

1.Install 2.4.5 magento instance
2.Enable the decimal quantity in Back-end
3.Add the product to the card
4.Update the card with 0.5 quantity
5.Go to checkout
6.Trying to place the order...
7.Order Placed
8.Trying to ship the product...

should not able to ship the product in admin panel...

Let us know if we are missing anything....

Thanks!!!

**Comment by Jilco** [comment]
I tried some sollutions above and they can create the shipment for qty 0.5, but the state of the order stays "processing" and not switches to "completed".

**Comment by engcom-Delta** [comment]
@Jilco, we have checked the status of order with this [PR](https://github.com/magento/magento2/pull/36411) changes. we can see the status as processing to completed once the order is shipped kindly look into the below screenshot and this PR is already merged.
<img width="1401" alt="Screenshot 2023-01-04 at 10 25 28 PM" src="https://user-images.githubusercontent.com/51681379/210610707-460f19f4-2bbe-48a0-84c3-76f93502228e.png">

<img width="1410" alt="Screenshot 2023-01-04 at 10 25 12 PM" src="https://user-images.githubusercontent.com/51681379/210610589-b391be60-f0d8-4cbb-8feb-125389a01f05.png">

Thanks.

**Comment by Jilco** [comment]
I updated /magento2/vendor/magento/module-sales/Model/Order/ShipmentFactory.php (and changed line 168 from INT to FLOAT) and now it works in my production environment. The strange thing is that in my staging the behavior is different with the same version and config
