### ISSUE TITLE
Admin Panel on Magento 2.4.5 Stores - Advanced - Admin Freezes

### ISSUE THREAD

**Issue by mar88888** [magento/magento2#35989]
### Preconditions and environment

- Magento 2.4.5
- Admin panel freezes on option Stores-Advanced-Admin. Nothing work.

### Steps to reproduce

Access admin panel, goto to stores-advanced-admin

### Expected result

Options available and work

### Actual result

Options freeze

### Additional information

Nothing.

### Release note

Nothing.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mar88888,

Thank you for reporting and collaboration.

 Verified the issue on Magento 2.4-develop branch and 2.4.5 but could not able to reproduce the issue. Kindly refer the screenshots.

<img width="948" alt="admin" src="https://user-images.githubusercontent.com/51680745/185905402-6b0121ed-696c-4b42-b41d-a7844e0f3702.png">


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @mar88888,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.
