### ISSUE TITLE
Cart Rule with product qty requirement does work on Magento 2.4.3 + Graphql

### ISSUE THREAD

**Issue by SanctuaryMirror** [magento/magento2#35981]
### Preconditions and environment

- Magento version 2.4.3
- GraphQl Usage

### Steps to reproduce

1. Add Cart Rule:
![Zrzut ekranu z 2022-08-19 13-32-53](https://user-images.githubusercontent.com/54793425/185609598-9eadc5cc-b0d8-47ac-aa60-c2e00d66bb42.png)
2. Add Qty 2 or more of product to cart.
3. Check cart prices.

### Expected result

Rule where product qty should be equals 1 , should not be applied for higher product qty.

### Actual result

Discount will be applied.

### Additional information

Magento will create 2 entities on add to cart, simple and configurable in quote_item table.

magento/module-sales-rule/Model/Rule/Condition/Product/Combine.php 
function retrieveValidateEntities, has such code:
`else {
    $validateEntities = $entity->getChildren() ?: [];
    $validateEntities[] = $entity;
}`

It causes to create $validateEntities, which where node [0] has simple with qty 1, and use for validation instead of using $entity qty which should be 2 or higher. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by SanctuaryMirror** [comment]
I hope its helpfull, some demo vanilla 2.4 found in internet: file:///home/satisflay/Obrazy/Zrzuty%20ekranu/Zrzut%20ekranu%20z%202022-08-19%2013-32-53.png

Put 1 qty first, then updated cart to 2 qty. Same cart rule applied as in ticket, with product qty is 1

**Comment by engcom-Bravo** [comment]
Hi @SanctuaryMirror,


Thank you for reporting and collaboration.

 Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. Kindly refer the screenshots.


Cart Rule

<img width="930" alt="rule 1" src="https://user-images.githubusercontent.com/51680745/185628312-032e807b-1bbb-40ed-8b18-8710f5916dfb.png">
<img width="918" alt="rule 2" src="https://user-images.githubusercontent.com/51680745/185628351-12787026-956e-4f57-8841-586b9fcef0aa.png">


<img width="930" alt="k" src="https://user-images.githubusercontent.com/51680745/185628478-f84f588c-107b-44e9-af51-ea8bf9e99799.png">

<img width="932" alt="v" src="https://user-images.githubusercontent.com/51680745/185628547-c7ae516d-478a-4c11-9dc6-9c086c8fa3e3.png">

<img width="939" alt="kvk" src="https://user-images.githubusercontent.com/51680745/185628592-40e96a94-51ff-4af2-9632-2b96f1af16b2.png">

Let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @SanctuaryMirror,

Thank you for reporting and collaboration.

 Verified the issue on Magento 2.4-develop branch we are able to reproduce the issue. Kindly refer the screenshots.


1.Adding Cart Rule

<img width="932" alt="bng" src="https://user-images.githubusercontent.com/51680745/186149430-4df94240-d941-47ce-9960-098980bf255d.png">


<img width="934" alt="bng 2" src="https://user-images.githubusercontent.com/51680745/186149489-a2fe0ee7-502c-44fd-9e0c-4cad39596639.png">



2.Adding Qty 2 or more of product to cart.

<img width="936" alt="bng 3" src="https://user-images.githubusercontent.com/51680745/186149661-3fdf7e21-d5f7-4f65-8b55-df0a22daab02.png">


<img width="942" alt="bng 4" src="https://user-images.githubusercontent.com/51680745/186149789-c8e22b8c-982f-4f2d-9c6a-871b59f1bf1b.png">


Discount is added against Cart Rule.


Hence Confirming this issue.


Thanks.
