### ISSUE TITLE
wen i change server M2 admin display error.

### ISSUE THREAD

**Issue by shuaiZend** [magento/magento2#3599]
frontend is working.
but admin display:
`Fatal error: Magento\Framework\Message\Manager::getMessages(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Magento\Framework\Message\Collection&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /home/wwwroot/my.com/vendor/magento/framework/Message/Manager.php on line 116`
my new server is php7.

**Comment by shuaiZend** [comment]
i fixed.if i use php.ini.sample
but,use php7 php.ini Still Display this error.
I don't know why..

**Comment by piotrekkaminski** [comment]
Cannot reproduce. If you still have this issue with 2.1, please provide exact PHP version and steps to reproduce in a new ticket.

**Comment by beany-vu** [comment]
You should open the .htaccess on the top level of the project. Find this config   **php_flag session.auto_start** -> it 's **on** then change to **off** . I got the problem -> this configuration override the one in php.in

**Comment by gcampedelli** [comment]
Did you find a solution? I got the same error but inside a integration. How can we override this functions using if path etc to get an autoload
