### ISSUE TITLE
stripe payment  card_declined but order is place

### ISSUE THREAD

**Issue by hareshpatel** [magento/magento2#35999]
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

hello team 

i am used stripe payment  payment getway. but in checkout card_declined but order is place. so how can stop the order place

### Expected result

hello team 

i am used stripe payment  payment getway. but in checkout card_declined but order is place. so how can stop the order place

### Actual result

hello team 

i am used stripe payment  payment getway. but in checkout card_declined but order is place. so how can stop the order place

### Additional information

hello team 

i am used stripe payment  payment getway. but in checkout card_declined but order is place. so how can stop the order place

### Release note

hello team 

i am used stripe payment  payment getway. but in checkout card_declined but order is place. so how can stop the order place

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @hareshpatel,

Thank you for reporting and collaboration. However, Stripe Payments is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page.


Thank you.
