### ISSUE TITLE
on overriding  catalog_product_view.xml file in custom theme, in page tag by changing attribute 'layout=3colomns' not working !

### ISSUE THREAD

**Issue by Ritesh-Rana** [magento/magento2#35998]
### Preconditions and environment

- Magento version : 2.4.4
- Have to create new custom theme

### Steps to reproduce

1.Under custom theme create directory create a directory Magento_Catalog
2.Under Magento_Catalog create a directory layout 
3.Under this layout create a file catalog_product_view.xml
4.In this catalog_product_view.xml under page tag changeattribute layout as : layout=3columns

### Expected result

Expected to be layout=3columns in page see below image
![Screenshot from 2022-08-23 11-13-19](https://user-images.githubusercontent.com/109286689/186079174-a6e78a1d-f0a4-4e11-b603-5f62a02b7d87.png)

### Actual result

Actual result is getting as layout=page --Full width 
![Screenshot from 2022-08-23 11-14-29](https://user-images.githubusercontent.com/109286689/186079464-b69204ba-ea46-4558-8eb3-c2bca551dece.png)

### Additional information

here is my page tag looks like in  catalog_product_view.xml
page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="3columns" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Ritesh-Rana** [comment]
`Issue: Format is valid`
`Issue: Clear Description`
`Component: 35998`
`Reproduced on 2.4.4`
`Issue: Confirmed`

**Comment by engcom-Lima** [comment]
Hi @[Ritesh-Rana](https://github.com/Ritesh-Rana)

We have tried to reproduce this issue but issue is not  reproducible .

**Precondition:**
    • Magento version : `2.4 -develop`
    • Created custom theme

We have followed below steps
1.In custom theme we have created Magento_Catalog directory, under this created layout directory and under layout we have created the file catalog_product_view.xml and setted the layout attribute value as 3columns.
Here is the custom theme we have created and changed the layout attribute value as 3columns.
[customtheme.zip](https://github.com/magento/magento2/files/9442394/customtheme.zip)


2. We have set the Design Configuration to custom theme.

![image](https://user-images.githubusercontent.com/60198022/187145184-d51da100-8cf8-45f6-822d-39a2b7ab3012.png)


3. We have checked in the frontend  layout=3columns in page  and width not like  pagelayout=page --Full width. Please have a look into below image
![image](https://user-images.githubusercontent.com/60198022/187145163-5c956d2a-42b5-4ac1-9923-02ca5d60fa75.png)


Please let us know if we are missing any steps here.

Thanks

**Comment by Ritesh-Rana** [comment]
I have tired cutomtheme.zip code provided by your side. I don't know but its still not working in my system maybe some other issue.
