### ISSUE TITLE
Image filenames that start with an uppercase will return wrong image path location during regex parse getOriginalImage

### ISSUE THREAD

**Issue by CadenceLabs-AndrewS** [magento/magento2#35992]
### Preconditions and environment

standard implementation on nginx,php7.4
2.4.3-p2 and 2.4.4

the current regex parsing in https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/MediaStorage/App/Media.php#L260 `getOriginalImage` does not work with filenames that start with an uppercase.  eg: Fake_example_file.jpg

### Steps to reproduce

add image asset to product with uppercase character as first character in filename string
eg: Fake_example_file.jpg

### Expected result
media/catalog/product/cache/e6da45d6sdsd67safaf/f/a/Fake_example_file.jpg 
getOriginalImage returns `/f/a/Fake_example_file.jpg`
Add the 'i' flag to the regex options resolves it. 
test it yourself:
https://regex101.com/r/BAQMBq/1

### Actual result
media/catalog/product/cache/e6da45d6sdsd67safaf/f/a/fake_example_file.jpg 
getOriginalImage returns `/f/a/fake_example_file.jpg` 
media/catalog/product/cache/e6da45d6sdsd67safaf/f/a/Fake_example_file.jpg 
getOriginalImage returns `/Fake_example_file.jpg`
test it yourself:
https://regex101.com/r/WXHpv9/1

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @CadenceLabs-AndrewS,

Thanks for the report and collaboration!

We have checked the above issue in the Magento 2.4-develop and it seems the regex has been updated. We request you to please check the same in 2.4-develop and let us know if you are able to reproduce it.

https://github.com/magento/magento2/blob/bcb0fea6da9d08549d2c212f7ebf585caf66f426/app/code/Magento/MediaStorage/App/Media.php#L260

Thanks

**Comment by CadenceLabs-AndrewS** [comment]
@engcom-Hotel 
It appears the latest regex in dev branch appears to resolve the issue.
