### ISSUE TITLE
Error during app:config:import -- Import failed

### ISSUE THREAD

**Issue by densen45** [magento/magento2#35993]
### Preconditions and environment

- Magento version <= 2.4.4-p1
- Magento 2.4-develop

### Steps to reproduce

The steps to reproduce this issue are described very well by @hostep in https://github.com/magento/magento2/issues/31428#issuecomment-866144213.

- Run the below command to dump all the configurations in the config.php file:
`bin/magento app:config:dump`
- Try to import the config by running the below command
`bin/magento app:config:import`

### Expected result

The import of the config runs without any errors.

### Actual result

The import of the config does not work but produces the following error:
```
Import failed: Notice: Trying to access array offset on value of type null in [..]/vendor/magento/module-config/Model/Config/Backend/Currency/Cron.php on line 66
``` 

### Additional information

There is a corresponding issues that was already fixed in https://github.com/magento/magento2/issues/31428. However, we discovered that only part of the issue was fixed yet (see https://github.com/magento/magento2/issues/31428#issuecomment-1013057304 and https://github.com/magento/magento2/issues/31428#issuecomment-1212996021).

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @densen45 ,
Thank you for raising an issue . We tried to reproduce the issue on magento 2.4 develop but issue is not reproducible.
import was successful.

**Steps followed:**
Steps to reproduce on latest 2.4-develop:

1. Setup clean Magento from 2.4-develop branch (I've used commit https://github.com/magento/magento2/commit/f121ac8359768b5ebcc7462574e58c36f34c52df)
2. After Magento is up and running, execute bin/magento app:config:dump

<img width="1440" alt="Screenshot 2022-08-23 at 7 27 42 PM" src="https://user-images.githubusercontent.com/51681379/186178543-f0053cf5-29de-49ef-87eb-e11bb8c1dfc0.png">

<img width="1440" alt="Screenshot 2022-08-23 at 7 26 38 PM" src="https://user-images.githubusercontent.com/51681379/186178986-32bbe973-6390-43eb-94a8-a6e7662aa3c0.png">

3. Manually change the app/etc/config.php file like this:
--- app/etc/config.php.orig   2021-06-22 18:28:35.000000000 +0200
+++ app/etc/config.php  2021-06-22 18:28:42.000000000 +0200
@@ -1302,8 +1302,8 @@
                 ],
                 'generate' => [
                     'enabled' => '0',
-                    'time' => null,
-                    'frequency' => null,
+                    'time' => '03,07,00',
+                    'frequency' => 'D',
                     'error_email_identity' => 'general',
                     'error_email_template' => 'sitemap_generate_error_email_template',
                 ],
@@ -4023,7 +4023,7 @@
                     'jobs' => [
                         'sitemap_generate' => [
                             'schedule' => [
-                                'cron_expr' => '0 0 * * *',
+                                'cron_expr' => '7 3 * * *',
                             ],
                         ],
                     ],
4. Try to import those changes by using: bin/magento app:config:import
5. We got below output:

<img width="1440" alt="Screenshot 2022-08-23 at 7 26 38 PM" src="https://user-images.githubusercontent.com/51681379/186178461-ae076ae8-dc4a-4136-8a92-e7e6b5219a42.png">

Processing configurations data from configuration file...
Import failed: Notice: Trying to access array offset on value of type null in app/code/Magento/Cron/Model/Config/Backend/Sitemap.php on line 78

**Comment by hostep** [comment]
@engcom-Delta: please read the last couple of comments in https://github.com/magento/magento2/issues/31428 very carefully

Yes, it was fixed for the sitemap generation cron, but it most likely wasn't fixed for the currency update cronjob, or for the log cleanup cronjob, or for the backups cronjob.

**Comment by engcom-Hotel** [comment]
Hello @hostep,

Thanks for the detailed information on this issue as well as https://github.com/magento/magento2/issues/31428.

Hello @densen45,

We have checked this issue in the latest development branch ie 2.4-develop and for us, the issue is reproducible for currency rates cron, we are updating the issue description and confirming the issue.

Note: The issue seems not reproducible for backups & log clear.

Thanks

**Comment by armpogart** [comment]
@engcom-Hotel Is there any chance that patches for #31428 (PR - [AC-988::Fixing app:config:import issue after config dump](https://github.com/magento/magento2/commit/cb375e7c5b0e24ef57f6bab1796846baeb4274ec) and later patch for this one will be added to 2.3.7 patch releases or quality-patches?

**Comment by hostep** [comment]
Closed without comments? (again @sdzhepa, please end this situation!!! All issue closings should have a comment explaining why!!!)

But most likely fixed by [AC-6588: Error during app:config:import -- Import failed](https://github.com/magento/magento2/commit/8bfe6109eb5b99281a3675a3d809a13f19f5b020)

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6588 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6588&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
