### ISSUE TITLE
Magento Upgrade

### ISSUE THREAD

**Issue by RenderZar** [magento/magento2#36000]
Hi I want to updgrade my magento on my website, I have Magento ver. 2.4.2 and I want to upgrade it to the latest version

**Comment by engcom-Bravo** [comment]
Hi @RenderZar,

Thank you for reporting and collaboration.


Kindly go through with official Magento [devdocs](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html) to upgrade your Magento Website.

Let us Know your are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @RenderZar,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
