### ISSUE TITLE
Save the job applictions without name using emoji.

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36006]
### Preconditions and environment

*magento2.4.5
*Fresh Install

### Steps to reproduce

1.Openn job portal.
2.Apply any job.
3 .In the candidate name field we add emoji and thi application was save without name of applicant
4.save the  application.

### Expected result

show erro massage

### Actual result

*not allow to to save withouth name of applicant.
*it is mandetry field so give some error massage shows

### Additional information

![image](https://user-images.githubusercontent.com/110841790/186380536-a0c0ed3b-5c05-4a7c-95b9-b04828b4eac4.png)

### Release note

![image](https://user-images.githubusercontent.com/110841790/186381325-eedac95a-cfd6-429b-a977-9b7b6344d0d9.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @SunilC1512,


Thank you for reporting and collaboration.

This issue is not related to Magento's core library. Please connect with module developers for the same.

Hence we are closing this issue.


Thanks.
