### ISSUE TITLE
Previous type informaion not clear when we fill the details even we not save the apllicatin

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36019]
### Preconditions and environment

#Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1.Openn job portal.
2.Apply any job.
3 fill the information
4.not save the application.
5.back wthouth saving application.
![image](https://user-images.githubusercontent.com/110841790/186623083-b0c08fa1-453f-491d-bc7d-fdf5c7728383.png)

### Expected result

clear all informatio we fill

### Actual result

isply previous info we fill
![image](https://user-images.githubusercontent.com/110841790/186623496-45334153-dbac-4a59-bd05-dd361891c541.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @SunilC1512 ,
Thank you for raising an issue and happy to assist you but kindly share the job portal url as per the steps provided.
Magento Admin portal looks like below.

<img width="1434" alt="Screenshot 2022-08-29 at 3 46 55 PM" src="https://user-images.githubusercontent.com/51681379/187179547-178d2d7e-25aa-4855-aae8-4c35f573ad3f.png">

Regards,

**Comment by engcom-Delta** [comment]
Hi @SunilC1512 ,

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Delta** [comment]
Hi @SunilC1512 ,

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
