### ISSUE TITLE
Unnecessary message rejection on pill version update

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#36012]
### Preconditions and environment

- Magento version: all versions

### Steps to reproduce

1. Run consumer with 100000 messages
2. Change config
3. Add more messages to RabbitMQ

### Expected result

The consumer will fail without message rejection and the message is processed in the next consumer-run process

### Actual result

The consumer will fail and the message is rejected and the message is lost forever

### Additional information

Here's the rejection: https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/internal/Magento/Framework/MessageQueue/CallbackInvoker.php#L90

Just remove this line and the message will not be rejected at all, so it will proceed in the future.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@madonzy: are you sure?

As far as I know (but I might be mistaken):
- calling `dequeue` removes the message from the queue
- calling `reject` puts it back in the queue, so it won't be lost

**Comment by madonzy** [comment]
yeah, param true is the difference I did not notice, I close this issue :)
