### ISSUE TITLE
Save the job applictions without last name using emoji

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36017]
### Preconditions and environment

#Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1.Openn job portal.
2.Apply any job.
3 .In the candidate name field we add emoji and thi application was save without name of applicant
4.save the application.

### Expected result

show erro massage

### Actual result

*not allow to to save withouth name of applicant.
*it is mandetry field so give some error massage shows
![186380536-a0c0ed3b-5c05-4a7c-95b9-b04828b4eac4](https://user-images.githubusercontent.com/110841790/186616258-3c1100f2-2e18-45e4-90da-d7d33f31d5c1.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @SunilC1512 ,

Thank you for your report and collaboration!
Unfortunately community is not able to provide fix for it in this repository as code of this extension is not part on https://github.com/magento/magento2 git repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.

Thank you
