### ISSUE TITLE
export cvc file some error

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36026]
### Preconditions and environment

Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1go to admin panel
2 crowd fund mangemnt
3export cvc file

### Expected result

all deatil correct format

### Actual result

![image](https://user-images.githubusercontent.com/110841790/186660456-e472908b-b613-4623-924c-0441bac02617.png)
![image](https://user-images.githubusercontent.com/110841790/186660664-bfa78d06-ab5f-49e5-b467-75eb197d8ec3.png)
end date not show in the file.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @SunilC1512 ,

Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page

Thank you
