### ISSUE TITLE
create a new project wthtoun name using emoji

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36025]
### Preconditions and environment

Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1go to admin panel
2 crowd fund mangemnt
3 add new project
4 add information wthout name using emoji

### Expected result

project not create

### Actual result

![image](https://user-images.githubusercontent.com/110841790/186659299-8840dc48-4a0a-4dff-8115-6f09b192a58c.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @SunilC1512 ,

Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page

Thank you
