### ISSUE TITLE
Direct donation without add to cart

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36023]
### Preconditions and environment

#Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1.go to crowd funding page.
2.select any help
3 add to cart.

### Expected result

we donet some small amount noat any product so add to acrt repalce with Donete
![image](https://user-images.githubusercontent.com/110841790/186655471-ad585a10-060d-4806-82ed-72709406a089.png)

### Actual result

add to cart and then check outn then ppyment.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @SunilC1512 ,

Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page

Thank you
