### ISSUE TITLE
Project is created without name when we enter emoji instead of project name.

### ISSUE THREAD

**Issue by rajnishkrpatel** [magento/magento2#36035]
### Preconditions and environment

- **Magento version : - 2.4.1**

### Steps to reproduce

- click on magento url
- login as admin end
- click on crowd funding management
- click on add project
- add emoji in project name

### Expected result

-  project name should not be accepted by emoji.

### Actual result

- emojies are accepted here.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @rajnishkrpatel,

Thank you for reporting and collaboration.


Crowd funding management is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.

Thank you.
