### ISSUE TITLE
Fallback for Magento_SalesRule Does not work 

### ISSUE THREAD

**Issue by hawksakr** [magento/magento2#3603]
i want to implement Magento_SalesRule module in my theme 
1- first create the module folder inside my theme folder 
2- copy js and templates inside web folder 
3- do some edits to templates and i found it does not work 
4- then i checked that iam in developer mode 
5- run deploy command 
but it still does not do the right fall back

**Comment by piotrekkaminski** [comment]
This is better suited for magento.stackexchange.com or community.magento.com
