### ISSUE TITLE
[Documentation] Message queues - Issue with 2.4.5

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#36046]
### Summary (*)

In this page : https://developer.adobe.com/commerce/php/development/components/message-queues/

We get an example containing 

```
...
'db' => [
                        'name' => 'db',
                        'disabled' => true
                    ]
...
```

On 2.4.5, this throws an exception : `Missing exchange field for publisher product_action_attribute.update in connection config.`

### Proposed solution

Change the documentation to :

```
...
'db' => [
                        'name' => 'db',
                        'exchange' => 'magento',
                        'disabled' => true
                    ]
...
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Shouldn't this be reported to https://github.com/magento/devdocs if it's a documentation bug?

**Comment by Nuranto** [comment]
I was unaware of this project, moved to https://github.com/magento/devdocs/issues/9504.

Thanks
