### ISSUE TITLE
Magento2 Backend save button

### ISSUE THREAD

**Issue by anjenehm** [magento/magento2#3604]
After a fresh installation of mage2 i tryed to put some products in the backend but the save button has no functionality. 

![image](https://cloud.githubusercontent.com/assets/7089704/13454536/2b23569a-e058-11e5-999a-5347de06e3ae.png)

**Comment by anton-huz** [comment]
Hi Sebastian,
On latest version of Magento, develop (798a8420e5738ceb5f2dcb332a59c7ee60b83444) branch, I don't reproduce this issue. 

Look like we had limited period of time when issue could be reproducible in upstream version and this is already fixed.

Fill free to reopen issue if you has additional info regarding issue.

And great thanks for reporting.
