### ISSUE TITLE
Receiving A Lot of Spam Emails Daily

### ISSUE THREAD

**Issue by KarenO24** [magento/magento2#36044]
### Preconditions and environment

- Magento ver. 1.9.3.6
- Each day we are getting more than 60 emails but all spams
Refer to the attached file as reference. I remember before this was addressed but again it showed up in our help desk daily.

on my screenshot you will also see the ticket ids as reference. 

### Steps to reproduce

Go to Help desk and click new/open tickets
Then after you refresh the spams emails coming in
Subject: [Contact form Подравляем! Заберите Ваш подарочный юбилейный билет ГОСЛОТО: www...](https://www.theticketmerchant.com.au/index.php/admin/awhdu3_ticket/edit/id/23839/key/b8c80642db46d5616d83d912ccc5a0d7/)

sender and content: 
Подравляем! Заберите Ваш подарочный юбилейный билет ГОСЛОТО: www.tinyurl.com/2lwjegmz | 27 Aug 2022 1:01:22 pm
4mlVAhB 2sKD NkWztiu nIIZo6J vUEP OkmppXG
![spams](https://user-images.githubusercontent.com/108387579/187011876-f019ea6d-c3fc-4314-a9db-c5220336ffb1.png)

### Expected result

These type of emails should be filtered and it should not go straight to our inbox. 

### Actual result

Remove and should not receive this type of emails

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Hi @KarenO24, this github repository is about Magento 2, not Magento 1

However, I would recommend you to install and configure some Captcha/ReCaptcha module to make sure all the forms on your webshop are protected against spammers. That should hopefully solve the problem.

**Comment by engcom-Dash** [comment]
Hi @KarenO24 ,

This issue is related to spamming which can be manage by adding Captcha. It will protect against spammers.

Let us know if we missing anything!!!

Thanks!!!

**Comment by sdzhepa** [comment]
Hello @KarenO24 

This repository and issue tracker has intended for Magento 2.4.x versions for bugs that can be reproduced on the latest `2.4-develop` code base. More details [Report an issue](https://developer.adobe.com/commerce/contributor/guides/code-contributions/#report-an-issue) guide and requirements

> Check if the issue exists on the 2.4-develop branch with a clean installation. We only accept pull requests for the 2.4-develop branch. If the issue is not reproducible on the 2.4-develop branch, it will be closed.


Also, [Support for Magento 1 Software Ends June 30, 2020](https://business.adobe.com/blog/basics/support-magento-1-software-ends-june-30-2020)

Due to all mentioned above, we are not able to process this issue here.
