### ISSUE TITLE
Catalog Price Rule single product reindex works incorrectly 

### ISSUE THREAD

**Issue by Myroslava-Myroslava** [magento/magento2#36049]
### Preconditions and environment

- Magento 2.4.3 , 2.4-develop

- Magento multi store setup. 2 Websites (W1 and W2)
- Create the the Product's Attribute (e.g. "Age Group") with the scope "website" and "Use for Promo Rule Conditions" set to "yes".
- The Product assigned to both websites and having Attribute with option 1 for W1, and option 2 for W2 (e.g. "adults" for W1 and "children" for W2).

### Steps to reproduce

1. Create a Catalog Price Rule.
3. In the rule as a condition, age groups is "adults"
4. Assign the rule to both websites (W1 and W2).
5. Reindex and clear cache
6. Admin - Open the Product edit page.
7. Select scope W1 on the Product edit page.
8. Save the product.
9. Open Front end - W1 catalog as a User - see the price of the Product.
10. Admin - Open the Product edit page again.
11. Select scope W2 on the Product edit page and save with no changes made
12. Open Front end - W2 catalog as a User - see the price of the Product.

### Expected result

The rule is applied (the price is reindexed) to the product only for the websites for which the attribute has an option value matching the rule. 

In our case: 
The rule is applied (the discount is applied) to the Product on W1 and NOT applied on W2.

### Actual result

The rule is applied to the product NOT taking into account the SCOPE chosen.
The rule takes the value of the attributes from the Product's edit page on which save event happens. And then the rule is applied or not applied (according to these values) to ALL websites.

In our case: 
1) After the save for W1: the rule is applied (the discount is applied) to the Product on BOTH W1 and on W2.
2) After the save for W2: the rule is NOT applied (the discount is applied) on BOTH websites.

### Additional information

The process is triggered in the \Magento\CatalogRule\Model\Indexer\IndexBuilder::reindexById. Inside, \Magento\CatalogRule\Model\Indexer\IndexBuilder::assignProductToRule applies the rule to all the websited, which is wrong

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Myroslava-Myroslava** [comment]
@magento give me 2.4-develop instance

**Comment by Myroslava-Myroslava** [comment]
@magento I am working on this

**Comment by Myroslava-Myroslava** [comment]
@magento add to contributors team

**Comment by Myroslava-Myroslava** [comment]
@magento I am working on this

**Comment by Myroslava-Myroslava** [comment]
We created 2 websites:
![image](https://user-images.githubusercontent.com/112387241/187225644-873bfd95-3f2e-4849-9b44-d3924d8000b1.png)


The rule:

![Screenshot 2022-08-29 at 17-11-39 R1 _ Catalog Price Rule _ Promotions _ Marketing _ Magento Admin](https://user-images.githubusercontent.com/112387241/187223433-924c5d4b-f425-465f-8c47-bf58a975989c.png)



We select the option matching the rule for the Main Website and save:
![Screenshot 2022-08-29 at 17-18-14 Joust Duffle Bag _ Products _ Inventory _ Catalog _ Magento Admin](https://user-images.githubusercontent.com/112387241/187223967-5308a97c-3e92-4335-8a14-e98cea6bd80d.png)



Visit catalog page on a Main Website as a user - the rule is applied (which is correct):
![Screenshot at 2022-08-29 17-14-01](https://user-images.githubusercontent.com/112387241/187225368-8852b332-ea4f-4000-b5ca-a96d93a5495b.png)



Select the option NOT matching the rule for the Website 2 and save:
![Screenshot 2022-08-29 at 17-17-36 Joust Duffle Bag _ Products _ Inventory _ Catalog _ Magento Admin](https://user-images.githubusercontent.com/112387241/187225032-508b430b-4560-48a4-89ed-2ec3253198c4.png)



Visit catalog page on a Main Website as a user - the rule is NOT applied (which is wrong since the value for Main Website still matches the rule):
![Screenshot at 2022-08-29 17-13-27](https://user-images.githubusercontent.com/112387241/187225416-c6b37a6f-f6cc-4bb3-94dc-482de67aa48f.png)

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence updating the description with exact steps and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/193583598-a58bd079-e567-43ac-810a-cf3e1bf2288d.png)
After saving the product with no changes made - catalog price rule got removed on front end.
![image](https://user-images.githubusercontent.com/60198231/193583645-a3932048-430b-4283-a267-183589fb1d0a.png)

**Comment by glo35082** [comment]
Our internal team has started working on this.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6810 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6810&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
