### ISSUE TITLE
THE ROYAL EXPRESS TRAVELS 

### ISSUE THREAD

**Issue by ROYALEXPRESSTRAVELS** [magento/magento2#36053]
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
Please follow [Report an issue](https://developer.adobe.com/commerce/contributor/guides/code-contributions/#report-an-issue) requirements and guidelines
