### ISSUE TITLE
Magento 2.4.5: Show Out Of Stock option outputs all available products during search

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#36055]
### Preconditions and environment

- Magento version 2.4.5
- PHP 8.1
- ES 7.17.0

On website I'm working on to upgrade to 2.4.5 from 2.4.3, the Catalog Search ouputs the whole Enabled Catalog:

![image](https://user-images.githubusercontent.com/66754347/187525323-fc678812-47c8-49e0-ab26-394f14058e98.png)

Instead of only ouputting the search results which should be 664 items:

![image](https://user-images.githubusercontent.com/66754347/187525486-33f63799-cf85-4131-a469-ed9ca283efbf.png)

Sorry bad screenshots because I was pulling the store apart to try to understand where it's coming from.

This can sort of be replicated on Vanilla Magento 2.4.5 with test data.

Here are the settings:

**Catalog - > Inventory**
This is the main culprit (Display Out Of Stock Products = YES)
![image](https://user-images.githubusercontent.com/66754347/187525711-be22c86f-2ada-4887-b790-d2aa156c42bd.png)

I believe there are some settings in the Catalog section that are also affecting the issue:

**Catalog - > Catalog**
![image](https://user-images.githubusercontent.com/66754347/187525982-dd7c38d8-dbb0-40bd-94c6-b07b15ee6e52.png)
![image](https://user-images.githubusercontent.com/66754347/187526023-0ba05067-5e87-4e85-b6a2-b84b0a8e9dd5.png)
![image](https://user-images.githubusercontent.com/66754347/187526040-383f8f19-0e15-45b0-bf85-bdd113b5bae8.png)
![image](https://user-images.githubusercontent.com/66754347/187526060-2365d7a2-39be-4e9b-b86c-692be99b1d84.png)
![image](https://user-images.githubusercontent.com/66754347/187526103-0c34f136-a846-4002-bcab-31338608a65d.png)
![image](https://user-images.githubusercontent.com/66754347/187526138-d246ce29-5d99-4f80-beed-4d7064e4f112.png)
![image](https://user-images.githubusercontent.com/66754347/187526164-d27ea116-30bf-46b0-958b-fddf6862e5d2.png)
![image](https://user-images.githubusercontent.com/66754347/187526198-3fb057ee-79b1-4373-b32a-1a689f9553c6.png)

### Steps to reproduce

1.  Login as admin.
2.  Go to Stores >> configuration >> Catalog >> Inventory >> Display Out Of Stock Products = YES)
3. On Vanilla 2.4.5 storefront Search for "ryker" it should output two items

/catalogsearch/result/?q=ryker

### Expected result

Two items are shown:
![image](https://user-images.githubusercontent.com/66754347/187527194-f931b0ff-4f93-488f-b716-ffa5a22ca090.png)

### Actual result

But it shows two items and toolbar shows "181 items":
![image](https://user-images.githubusercontent.com/66754347/187526770-99cfd935-e254-4adb-95aa-f26d20929af4.png)

### Additional information

On my site this is creating a problem because each search instead of 2 seconds, becomes a 22 second search. HELP!

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment]
Here are tests:
https://2a84a4e16655dab06981be102116addf.instances.magento-community.engineering/catalogsearch/result/?q=ryker

BEFORE:
![image](https://user-images.githubusercontent.com/66754347/187529064-c98697c0-f423-416f-b085-d8c221b3f785.png)


AFTER:
![image](https://user-images.githubusercontent.com/66754347/187529174-7538bc1a-82cb-4f35-832d-069281f31de3.png)

**Comment by pmonosolo** [comment]
https://github.com/magento give me 2.4.3 instance

**Comment by pmonosolo** [comment]
@magento give me 2.4.3 instance

**Comment by pmonosolo** [comment]
Magento 2.4.3 does not have this issue:
https://a8564c0d1a87b370b3d016bd8a0ccd93.instances.magento-community.engineering/catalogsearch/result/?q=ryker

BEFORE:
![image](https://user-images.githubusercontent.com/66754347/187531033-9423aa3f-9afd-44d5-96fc-0e5f84e9516e.png)

AFTER:
![image](https://user-images.githubusercontent.com/66754347/187531000-f95ee5ca-48bc-4629-a6ce-a26bf8d9e2ea.png)

**Comment by pmonosolo** [comment]
It looks like the fix for this issue is in this thread:
https://github.com/magento/inventory/issues/3360

I need to test a bit more, but so far, it's outputting only the items in the search.

**Comment by Bashev** [comment]
Probably fixed in https://github.com/magento/magento2/pull/35986

**Comment by pmonosolo** [comment]
@Bashev
> Probably fixed in #35986

Hmmm, doesnt seem to work. The page loading time is still slow.

The fix in vendor\magento\module-inventory-catalog\Plugin\Catalog\Block\ProductList\UpdateToolbarCount.php

![image](https://user-images.githubusercontent.com/66754347/187546945-b6316962-0056-404d-add9-ac22cce6fc05.png)

It looks like somebody by mistake is calling wrong method - it pulls the WHOLE product collection rather than a collection related to the search.

![image](https://user-images.githubusercontent.com/66754347/187547142-fba15555-4160-4a0f-99ce-023e22b212d8.png)

I need to test other parts of the catalog page in case there's some hidden issue thats not related to search.

**Comment by Amadeco** [comment]
The both solutions for me doesn't work : 
Fixed Issue #35899: Filtering with out of stock products, limited only to products in… #35986
Category count for category pages is wrong when show out of stock is enabled 2.4.5 #3360

I am on Magento 2.4.5 and PHP 8.1.
The only reason why it is not working for me is a 3rd party extension (I am using Smile Elasticsuite) but I cannot see any plugin which modify this part of code.

**Comment by pmonosolo** [comment]
> The both solutions for me doesn't work :
> 
> * PR magento/module-elasticsearch : [Fixed Issue #35899: Filtering with out of stock products, limited only to products in… #35986](https://github.com/magento/magento2/pull/35986)
> * Issue magento/module-inventory-catalog : [Category count for category pages is wrong when show out of stock is enabled 2.4.5 #3360](https://github.com/magento/inventory/issues/3360)
> 
> I am on Magento 2.4.5 and PHP 8.1. My guess, if it is working for you, a 3rd party extension (I am using Smile Elasticsuite) but I cannot see any plugins which modify this part of the code. I am not using single-store mode.

Search for their name in the issues, I believe I've seen somebody working on this issue for that specific plugin.

**Comment by Amadeco** [comment]
Thank you @pmonosolo for your heads up.

Indeed, I found https://github.com/Smile-SA/elasticsuite/issues/2663#issuecomment-1214813879 but it is the same solution as https://github.com/magento/inventory/issues/3360.

I will report this to the 3rd party.

**Comment by pmonosolo** [comment]
I rewrote this a bit to check for "catalogsearch_result_index" action:

![image](https://user-images.githubusercontent.com/66754347/188241417-ee752b65-ae18-445f-b2c8-68adb42dc3f5.png)

This way it skips the Show Out Of Stock before it even starts. 

Constructor:

![image](https://user-images.githubusercontent.com/66754347/188241522-6294a70c-026d-4204-bc54-d1f566d03282.png)


![image](https://user-images.githubusercontent.com/66754347/188241506-fc16ade1-852a-400f-9956-ac6c467bb955.png)

Its not perfect, but it works better than the previous solution. 

The code in afterGetTotalNum in original state just checks if it's a Category Page.

Search Result Page outputs Category as "Default Category" so when the items are being put into an array, it puts the whole store worth of products into the list.

**Comment by pmonosolo** [comment]
Ah, I just disabled that Plugin.

![image](https://user-images.githubusercontent.com/66754347/188243710-8f2d7efe-d1df-43e6-ba9d-a0a151f8a0bc.png)

They need to rewrite that to check for:

- If page is Catalog Search Page
- If there are filters applied.

Currently it just checks the Category page, so on Search Page it uses "Default Category" and outputs the whole catalog.

When you filter by attributes, it does not decrease the number because the only lookup that is done is for Category. It does not check if filters were applied to the category.

**Comment by engcom-Lima** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in Magento **2.4-develop**  and **2.4.5**

**Description:**
Showing wrong count of items for Ryker product when Display out of stock options is set to Yes.

**Pre-requisite:**
Fresh magento `2.4-develop`  && `2.4.5` should be installed.

**Steps to reproduce:**
1. Login as admin.
2. Go to Stores >> configuration >> Catalog >> Inventory >> Display Out Of Stock Products = YES)
3. On Vanilla 2.4.5 storefront Search for "ryker" it should output two items.

**Expected result:** It should show 2 items for ryker product.

**Actual result:** It is showing 187 items as shown in screenshot below:

**Screenshots:**
<img width="1309" alt="Screenshot 2022-09-29 at 3 05 05 PM" src="https://user-images.githubusercontent.com/60198022/193000542-3ba654fa-be91-44a1-84b4-66fe2b36703e.png">

**Comment by pmonosolo** [comment]
Thanks @engcom-Lima ! 

The issue is not really in the number, its the time it takes to pull the number of the products. 

If you have a 300,000 sku store, this is an issue because it outputs the whole catalog 300,000 products on a search page, for EVERY search!
