### ISSUE TITLE
Undefined constant "MagentoHackathon\Composer\Magento\Deploystrategy\GLOB_BRACE" under Alpine linux

### ISSUE THREAD

**Issue by speller** [magento/magento2#36062]
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

Following official instructions to upgrade 2.4.4 to 2.4.5 https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html

### Expected result

Upgraded successfully

### Actual result

Composer fails on the `composer update` step:

```none
In DeploystrategyAbstract.php line 345:

  [Error]
  Undefined constant "MagentoHackathon\Composer\Magento\Deploystrategy\GLOB_BRACE"


Exception trace:
  at /magento/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php:345
 MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->removeContentOfCategory() at /magento/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php:322
 MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->remove() at /magento/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php:92
 MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->clean() at /magento/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Installer.php:611
 MagentoHackathon\Composer\Magento\Installer->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:552
 Composer\Installer\InstallationManager->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:452
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:28
 React\Promise\FulfilledPromise->then() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:453
 Composer\Installer\InstallationManager->executeBatch() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:390
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:282
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:763
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:590
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:279
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:241
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1024
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:335
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29
```

### Additional information

The official PHP documentation https://www.php.net/manual/en/function.glob.php says:

> Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux.

Failing code: https://github.com/magento/magento-composer-installer/blame/master/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php#L345

```php
    protected function removeContentOfCategory($sourcePath, $destPath)
    {
        $sourcePath = preg_replace('#/\*$#', '/{,.}*', $sourcePath);
        $matches = glob($sourcePath, GLOB_BRACE);
        if ($matches) {
```
Possible workaround is also discussed here: https://github.com/docker-library/php/issues/719

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maddumarala** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
See https://github.com/magento/magento-composer-installer/pull/35 & https://github.com/magento/magento-composer-installer/pull/37 for fixes

**Comment by navarr** [comment]
I would recommend this be increased to S1 as the ability to run composer commands is likely "critical functionality"

**Comment by ihor-sviziev** [comment]
@sidolov @sdzhepa @andrewbess i think it should have p1 priority since that’s the only issue on alpine Linux and the fix is pretty simple, we even have a pull request with needed changes

**Comment by engcom-November** [comment]
Verified the issue by upgrading from 2.4.4 to 2.4.5 Project-community-edition as per the upgrade [guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html) and the issue is not reproducible on Mac OS.

**Comment by ihor-sviziev** [comment]
@engcom-November any updates?

**Comment by sdzhepa** [comment]
@engcom-November and @engcom-Hotel 

Could you please process this issue?

**Comment by engcom-Hotel** [comment]
Hello @speller,

Thanks for the report and collaboration!

We have tried to reproduce the issue with the docker image of Alpine Linux. We have pulled the image from its official link as below:

https://hub.docker.com/_/alpine

We have tried to reproduce the issue with a simple PHP script with the use of the `GLOB_BRACE` constant use and we are able to get the actual result as you mentioned in the main description. Please refer to the below screenshot for reference:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/51681618/189890073-3b83c621-01f9-420e-8c5b-1e656c13caef.png">

As in the Magento, we are using this constant in file `DeploystrategyAbstract.php` line number 345 without any checks, we are confirming the issue.

Thanks

**Comment by BernardRobbins-BMediaLLC** [comment]
I had a dev run into this too. They ran `bin/magento sampledata:remove`.

Undefined constant "MagentoHackathon\Composer\Magento\Deploystrategy\GLOB_BRACE"

They're on Den which is using 
Alpine 3.16.2 
PHP 8.1.11
M2.4.5-p1

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6671 by the internal team
Related commits: https://github.com/magento/magento-composer-installer/commit/255b3f6b301f65e727c5f7deea63fa43babe4e42

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by amcguireweb** [comment]
> I am getting this error today when trying to update ece-tools. I've looked over the "fix" and I have the updates mentioned here but i'm still getting the error. I've never seen this error before today.
> 
> I'm on a Mac running Adobe Commerce B2B v2.4.6-p3. I tried deleting the vendor folder, running **composer install**, and then attempting to upgrade ece-tools again using **composer update magento/ece-tools --with-dependencies**, but I get the following error:
> 
> `- Upgrading symfony/yaml (v6.4.11 => v6.4.13): Extracting archive PHP Fatal error: Uncaught Error: Class "Laminas\Stdlib\Glob" not found in /var/www/html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php:347 Stack trace: #0 /var/www/html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php(324): MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->removeContentOfCategory('/var/www/html/v...', '/var/www/html/....') #1 /var/www/html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php(94): MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->remove('dist/mnt', './.docker/mnt') #2 /var/www/html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Installer.php(611): MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->clean() #3 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(543): MagentoHackathon\Composer\Magento\Installer->update(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage), Object(Composer\Package\CompletePackage)) #4 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(448): Composer\Installer\InstallationManager->update(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\UpdateOperation)) #5 [internal function]: Composer\Installer\InstallationManager->Composer\Installer\{closure}(NULL) #6 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), NULL) #7 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(449): React\Promise\FulfilledPromise->then(Object(Closure)) #8 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(390): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array) #9 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array) #10 phar:///usr/local/bin/composer/src/Composer/Installer.php(763): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true) #11 phar:///usr/local/bin/composer/src/Composer/Installer.php(590): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true) #12 phar:///usr/local/bin/composer/src/Composer/Installer.php(279): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true) #13 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(248): Composer\Installer->run() #14 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run() #21 /usr/local/bin/composer(29): require('phar:///usr/loc...') #22 {main} thrown in /var/www/html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php on line 347 `

The solution for me was to remove the **vendor/** folder, then run **composer update --with-dependencies**.

**Comment by jaywilliams** [comment]
Thanks @amcguireweb, deleting the `vendor/` directory and re-running `composer update --with-dependencies` did the trick for me as well.

**Comment by thedotwriter** [comment]
On some projects, when switching between branches with different dependencies, deleting the `vendor/` folder and running `composer install` works as well. No need for `composer update`.
