### ISSUE TITLE
Gift Options for Entire Order and Gift Options for Individual Items are not displayed in Magento2 front end

### ISSUE THREAD

**Issue by LS-Supriya** [magento/magento2#3606]

**Comment by ishakhsuvarov** [comment]
@LS-Supriya Please provide your Magento version and steps to reproduce the issue.

**Comment by LS-Supriya** [comment]
Magneto Enterprise Endition
Version: 2.0.0
Steps:
1. Go to Magento admin
2. Go to Stores-.Configuration->Sales->Sales
3. Set "yes" for all the options under Gift Options Section
4. Save the config
5. Go to stores->Other Settings->Gift Wraping
6. Add Gift Wrapping
7. Go to Check out page from Magento front end
8. Look for Gift wrap options

![2016-03-02_1448](https://cloud.githubusercontent.com/assets/17175033/13455898/3f990b32-e086-11e5-8dcc-d05d69cebf22.png)

**Comment by ishakhsuvarov** [comment]
@LS-Supriya Both types of Gift Options were moved from One Page Checkout page to Shopping Cart page. Please verify, that Gift Options are available in the shopping cart.
For motivation behind this you may see #3046

**Comment by LS-Supriya** [comment]
Got it Thanks

**Comment by LS-Supriya** [comment]
But I don't see following description, 
1. Gift Options for Entire Order 
2. Gift Options for Individual Items 

It Just says Gift Options
![2016-03-02_1625](https://cloud.githubusercontent.com/assets/17175033/13458461/61bc84f2-e093-11e5-9d7c-5e7d6cb278cf.png)

**Comment by ishakhsuvarov** [comment]
@LS-Supriya Item level Gift Options are displayed at the bottom of each item, order level Gift Options are displayed at the bottom of the cart.
On your screenshot, the section below `Update Cart` button is order level Gift Options.

**Comment by LS-Supriya** [comment]
Gotcha. Can the naming convention be changed?

**Comment by ishakhsuvarov** [comment]
@LS-Supriya You may check and customise templates in `Magento/GiftMessage/view/frontend/web/template`, there are different templates for item level and order level containers.

**Comment by mcspronko** [comment]
Hi Magento,

Gift Messages functionality does not work.
It throws error during HTTP POST request.
Error: 404 Not Found
URL: POST http://demo.theirishstore.com/rest/tis_english/V1/guest-carts/:cartId/gift-message 404 (Not Found)

It seems like :cartId is not populating with identifier.

**Comment by ishakhsuvarov** [comment]
@mcspronko Hi, issue you have described is already fixed in the `develop` branch with the commit [802411](https://github.com/magento/magento2/commit/8024119f0424fa792d2043db9cbfd520a3fee770) (issue #3804). This fix is likely to be delivered to the `2.0` branch in the future releases as well.

**Comment by mcspronko** [comment]
@ishakhsuvarov thank you for reply.

**Comment by ishakhsuvarov** [comment]
Closing this issue for now, please reopen if there are any additional questions.
