### ISSUE TITLE
Coupon codes export to Excel XML not working as expected

### ISSUE THREAD

**Issue by zohmi** [magento/magento2#36073]
### Preconditions (*)
1. Magento 2.4.5

### Steps to reproduce (*)
1. Create a salesrule of type "Specific Coupon" and check "Use auto generation":
![Bildschirmfoto 2022-09-02 um 10 25 52](https://user-images.githubusercontent.com/1702177/188097945-3f49372d-192a-4ce5-885b-bd2facb301e2.png)

2. Hit "Save and Continue Edit"
3. Head to "Manage Coupon Codes" Tab and generate e.g. 500 Coupons: 
![Bildschirmfoto 2022-09-02 um 10 26 15](https://user-images.githubusercontent.com/1702177/188098267-d77d386a-1c7c-42be-b8c6-bb30634f4388.png)

4. Hit generate and wait for completion
5. Go to generated coupon code list and hit "Mass actions" -> "Select all"
![Bildschirmfoto 2022-09-02 um 10 30 28](https://user-images.githubusercontent.com/1702177/188098652-e733764d-b7aa-4985-af03-035020687890.png)

6. All coupons (500) should now be shown as selected.
7. Choose "Export to CSV" and hit the "Export" button.
![Bildschirmfoto 2022-09-02 um 10 31 46](https://user-images.githubusercontent.com/1702177/188098923-1ccaef4f-8ef5-4a4b-bd82-1117c152aa4a.png)

8. The generated and downloaded file contains all 500 coupons.
9. Choose "Export to Excel XML" and hit the "Export" button.
![Bildschirmfoto 2022-09-02 um 10 33 52](https://user-images.githubusercontent.com/1702177/188099078-662c8a12-c383-46e7-ac01-257173bb151f.png)

10. The generated and downloaded file only contains as much items, as choosen in the items per page selector. In the above mentioned example that would be 20.

### Expected result (*)
1. The export of Excel XML should contain all selected coupons. In the above mentioned example 500.

### Actual result (*)
1. The generated and downloaded file only contains as much items as selected in the items per page selector instead of the selected items itself.

**Comment by engcom-Dash** [comment]
Hi @zohmi ,

We are trying to reproduce the issue in 2.4.5 magento instance....But we are not able to reproduce the issue.
When we trying to generate the coupon code it is not listed out in respective fields....So with coupon codes we are not able to reproduce the bug....

Here i attached the screenshots for your reference:
![Screenshot from 2022-09-05 22-17-36](https://user-images.githubusercontent.com/60198592/188492101-835a50ba-a76f-478a-8426-f10af5f51cfc.png)
![Screenshot from 2022-09-05 22-17-02](https://user-images.githubusercontent.com/60198592/188492110-d57820e0-0db5-4cfa-b5fb-16d27ab00b06.png)
![Screenshot from 2022-09-05 22-16-54](https://user-images.githubusercontent.com/60198592/188492111-f9bc8a62-214a-4408-9ee7-9ad295f17e57.png)

Steps we Followed:
1.Install magento instance
2.Go to admin panel
3.Click the Marketing option 
4.Create the Cart price rule
5.Generate Coupon codes
6. Coupon codes is not generated

Let us know if we missing anything!!!

Thanks!!!

**Comment by zohmi** [comment]
> Hi @zohmi ,
> 
> We are trying to reproduce the issue in 2.4.5 magento instance....But we are not able to reproduce the issue. When we trying to generate the coupon code it is not listed out in respective fields....So with coupon codes we are not able to reproduce the bug....
> 
> Here i attached the screenshots for your reference: ![Screenshot from 2022-09-05 22-17-36](https://user-images.githubusercontent.com/60198592/188492101-835a50ba-a76f-478a-8426-f10af5f51cfc.png) ![Screenshot from 2022-09-05 22-17-02](https://user-images.githubusercontent.com/60198592/188492110-d57820e0-0db5-4cfa-b5fb-16d27ab00b06.png) ![Screenshot from 2022-09-05 22-16-54](https://user-images.githubusercontent.com/60198592/188492111-f9bc8a62-214a-4408-9ee7-9ad295f17e57.png)
> 
> Steps we Followed: 1.Install magento instance 2.Go to admin panel 3.Click the Marketing option 4.Create the Cart price rule 5.Generate Coupon codes 6. Coupon codes is not generated
> 
> Let us know if we missing anything!!!
> 
> Thanks!!!

Hi @engcom-Dash,

you have to wait for the generation of the coupon codes. As the message says, the job has been queued and will be processed asynchronously. It takes a while and then the codes are there.

Thanks

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance
