### ISSUE TITLE
Issues with adding attribute set

### ISSUE THREAD

**Issue by hungvt** [magento/magento2#3607]
Hi,
 i found some issue with adding attribute set on magento 2.0.2
-  when i add new group, i do not enter the group and click OK. it show the error like the attached image
  ![error_1](https://cloud.githubusercontent.com/assets/367271/13455142/27141450-e08e-11e5-8506-f04eb20f49b1.PNG)
- When i select a group and click Delete Selected Group the group is deleted but all attributes inside the group are not added automatically to  Unassigned Attributes list.

**Comment by vzabaznov** [comment]
Hi @hungvt , thank you for reporting, looks like its 2 different cases, the first one is bug, and internal ticket MAGETWO-50412 was created, the second one is feature request

**Comment by pboisvert** [comment]
@antboiko adding Anton to capture the feature request portion of this issue

**Comment by antboiko** [comment]
Hi @hungvt , I've created internal ticket MAGETWO-52474 and added it to the backlog to cover the feature described in the second case.

Best,
Anton.

**Comment by olysenko** [comment]
the first issue was fixed and delivered into develop branch in [commit](https://github.com/magento/magento2/commit/14028aad37ee7435d89eb3b647e6d03ecd8e2e13)
