### ISSUE TITLE
Decimal number representation with "," leads to errors in the adminhtml (for e.g. locale: German)

### ISSUE THREAD

**Issue by densen45** [magento/magento2#36089]
### Preconditions and environment

- Magento version 2.4.4-p1

### Steps to reproduce

The error occurs in the adminhtml/backend. The following procedure is related to the adminhtml/backend, not the frontend.

1. Login to adminthml/backend
2. Admin Account: Make sure the setting for Interface Locale is "English (United States) / English (United States)" (Click on your name at the top-right corner > Account Settings > Interface Locale)
3. Create a Bundle Product with a special price by percentage (e.g. 95)
4. Go to the product list (Catalog > Products) and search for the Bundle
5. See the Bundle and ensure that it works
6. Admin Account: Now, change your account setting for Interface Locale to "Detusch (Deutschland) / German (Germany)"
7. Go back to the product list and recognize error message

### Expected result

No matter which language for the Interface Locale setting is selected, the product list works.

### Actual result

When selecting a language in which the decimal number representation comes with "," instead of ".", the product list does not load and shows the following errors:

```
Attention
Something went wrong.
```
```
Something went wrong with processing current custom view and filters have been reset to its original state. Please edit filters then click apply.
```

### Additional information

See also the exception in the var/log/system.log and debug:
```
main.CRITICAL: Exception: Notice: A non well formed numeric value encountered in vendor/magento/module-bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php on line 80 in vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 vendor/magento/module-bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php(80): Magento\Framework\App\ErrorHandler->handler()
#1 vendor/magento/module-catalog/Ui/DataProvider/Product/ProductDataProvider.php(93): Magento\Bundle\Ui\DataProvider\Product\Modifier\SpecialPriceAttributes->modifyData()
#2 vendor/magento/module-ui/Component/Listing.php(38): Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider->getData()
#3 vendor/magento/framework/View/Element/UiComponent/Context.php(250): Magento\Ui\Component\Listing->getDataSourceData()
#4 vendor/magento/framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData()
#5 vendor/magento/module-ui/Component/AbstractComponent.php(158): Magento\Framework\View\Element\UiComponent\ContentType\Json->render()
#6 vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(91): Magento\Ui\Component\AbstractComponent->render()
#7 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#8 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#9 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#10 generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#11 vendor/magento/framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#12 vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#13 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#14 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#15 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#16 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#17 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#18 generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(41): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#19 vendor/magento/framework/App/FrontController.php(245): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch()
#20 vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#21 vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#22 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#23 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#24 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#26 vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#27 generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#29 pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#30 {main} [] []
```
Debugging:
In the SpecialPriceAttributes in line 80, you can see how the decimal number representation changes when you change the Interface Locale during debugging. 
This is the cause of the error.

The language of the interface isn't changed at all. However, this might be another issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment]
After I have opened this issue, I looked at the current 2.4-develop code and saw that this issue was already addressed for Dutch language in https://github.com/magento/magento2/commit/39a7cfab9420aa7a16c2de1cc79da2ec12cee561.

Adding 'de_DE' to the introduced LOCALE_USING_DECIMAL_COMMA solves this issue for German language too. See here https://github.com/magento/magento2/blob/f26ae808bd9f9164793cb7bc9211d9ac3abb958a/app/code/Magento/Bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php#L22
Probably other languages are effected?

**Comment by engcom-November** [comment]
Hi @densen45 , Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance with both German(Germany) and French(France) locale options but the issue is not reproducible.
Steps performed:
1. Locale set to English (United States). Created Bundle product with Special Price in decimal values.
2. Locale changed to French (France).
3. Clean cache
4. Front-end - Catalog - No issue
5. Product Details page - No issue
6. User is able to place order - No issue.
![image](https://user-images.githubusercontent.com/60198231/192438873-858ecadb-c0d4-4e5a-a086-7d02022991a4.png)

![image](https://user-images.githubusercontent.com/60198231/192438844-bcacf8d7-3b8b-4e2b-bb53-22dfc92fdc8f.png)

![image](https://user-images.githubusercontent.com/60198231/192438812-b02a63ea-f085-4ed3-bf99-ebc9b65a5d68.png)

Kindly recheck the issue on Magento 2.4-develop instance and let us know for which language package the issue is reproducible.
Thank you.

**Comment by densen45** [comment]
@engcom-November Thanks for checking this issue.

I have updated the "Steps to reproduce" above. 
Please read carefully and notice, it's an adminhtml/backend related issue. You need to change the locale settings in your admin account, not the translation settings in your browser. Later you have to go to the product list in the adminhtml/backend. You don't need to go to the frontend at all.

If anything is still unclear, I'm happy to help.

**Comment by engcom-November** [comment]
Thank you for the response @densen45 ,
Verified the issue again on Magento 2.4-develop instance with updated steps and the issue is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/195667526-a19f0744-c392-4bd1-9488-9238436e2e05.png)

Thank you.

**Comment by engcom-Dash** [comment]
Hi @densen45 ,

The issue is not reproducible with the provided steps in the video 
please fine the screen shots attached for the same.
![image](https://user-images.githubusercontent.com/60198592/233067310-9dc4ae9a-34c4-47de-b797-844177b3f3ae.png)
![image](https://user-images.githubusercontent.com/60198592/233067351-f7b2cbbc-3c94-4c74-ae10-3f40bc2935fd.png)

Hence we are closing this issue.

Let us know if we are missing anything!!!

**Comment by densen45** [comment]
@engcom-Dash It looks like you didn't follow the sequence of steps to reproduce this issue. Please reopen this issues.

You have to set the the Interface Locale fist to "Detusch (Deutschland) / German (Germany)" and afterwards open the Products overview.
On your first screenshot the locale is not set to German (e.g. see the button "Add Product").

With Magento 2.4.6 changes according to https://github.com/magento/magento2/issues/35704 were released. As I mentioned above, they implemented this for the Dutch language. It would be pretty easy, to add further effected languages.
