### ISSUE TITLE
Error function getResultCount in Magento/CatalogSearch/Block/Result 

### ISSUE THREAD

**Issue by AprilNJ** [magento/magento2#36085]
### Preconditions and environment

- Magento version 2.4.4
- PHP 8.1

### Steps to reproduce

1. call function getResultCount in Magento\CatalogSearch\Block\Result
![Screen Shot 2565-09-05 at 10 30 30](https://user-images.githubusercontent.com/108717422/188355349-4fb34076-d0d5-4f7b-9828-839cb1e85590.png)

3. input search and enter result on frontend it's broked
![Screen Shot 2565-09-05 at 10 28 37](https://user-images.githubusercontent.com/108717422/188355171-087d185b-517a-4f16-85f2-62f83d34ea9f.png)

### Expected result

show text result search massage
![Screen Shot 2565-09-05 at 10 33 14](https://user-images.githubusercontent.com/108717422/188356150-cd15e00f-e29a-4d22-aef7-37a76382cac4.png)

### Actual result

![Screen Shot 2565-09-05 at 10 28 37](https://user-images.githubusercontent.com/108717422/188355171-087d185b-517a-4f16-85f2-62f83d34ea9f.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @AprilNJ,

 We have tried to reproduce this issue in magento 2.4-develop, but issue is not reproducible .

Precondition:
• Magento version : 2.4.4-develop
• PHP 8.1

We have followed below steps
1.We called getResultCount() function in Magento\CatalogSearch\Block\Result.
<img width="634" alt="Screenshot 2022-09-22 at 9 01 45 PM" src="https://user-images.githubusercontent.com/51681379/191789963-eca77ec8-35a4-487a-92af-f48397465e86.png">

2.Search for the product which is not available in frontend. 
<img width="1223" alt="Screenshot 2022-09-22 at 9 09 13 PM" src="https://user-images.githubusercontent.com/51681379/191791390-a04aec39-a27a-4eb3-bd2b-d9bae02440e8.png">

3.Search for available product in frontend
<img width="1239" alt="Screenshot 2022-09-22 at 9 16 25 PM" src="https://user-images.githubusercontent.com/51681379/191793001-d3158a8e-9eb9-4a41-833a-1a29c7a6e922.png">


Please let us know if we are missing any steps here.

Thanks
