### ISSUE TITLE
Cannot save sku using ResourceModel saveAttribute function

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#36084]
### Preconditions and environment

- 2.4.3-p1

### Steps to reproduce

Create a product with SKU test1
Run the following standalone script located in `pub/tools/` folder

```php
<?php
/*
 * Copyright (c) 2022. IOWEB TECHNOLOGIES
 */

ini_set('display_errors', 1);

use Magento\Framework\App\Bootstrap;
require __DIR__ . '/../../app/bootstrap.php';
$bootstrap = Bootstrap::create(BP, $_SERVER);

$om = $bootstrap->getObjectManager();
$state = $om->get(Magento\Framework\App\State::class);
$state->setAreaCode('adminhtml');

$productResource = $om->get(\Magento\Catalog\Model\ResourceModel\Product::class);
$productRepository = $om->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
$product = $productRepository->get('test1');
$product->setSku('test');
$productResource->saveAttribute($product, 'sku');
```

You will get an exception 

```
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.value_id' in 'field list' in /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91 Stack trace: #0 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(91): PDOStatement->execute(Array) #1 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(107): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}() #2 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(92): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure)) #3 /var/www/vhosts/website/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #4 /var/www/vhosts/website/httpdocs/vendor/magento/zendframework1/li in /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php on line 110
```

### Expected result

The sku is saved properly

### Actual result

An exception is thrown 

```

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.value_id' in 'field list' in /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91 Stack trace: #0 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(91): PDOStatement->execute(Array) #1 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(107): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}() #2 /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(92): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure)) #3 /var/www/vhosts/website/httpdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #4 /var/www/vhosts/website/httpdocs/vendor/magento/zendframework1/li in /var/www/vhosts/website/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php on line 110
```

### Additional information

I'm in the process of creating an automation for generating product SKUs based on a series and I was tyring to create a cron job that will automatically alter the SKUs to the appropriate format. 
However this issue occured and I'm now unable to do it in a fast way and I have to use the ProductRepository to save the whole product instead of just modifying the attribute itself. 

That means one extra load for the product and one extra save for the whole product instead of just saving my requested attribute

In my opinion saveAttribute should be able to save the sku as well but it seems it only works for non-static attributes. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rogerdz** [comment]
same https://github.com/magento/magento2/issues/7247

**Comment by ioweb-gr** [comment]
But that one refers to addAttributeUpdate and not save attribute so it's different area

**Comment by andrewbess** [comment]
Hello @ioweb-gr 
The `sku` is not attribute. This is field in `catalog_product_entity` table and is different from attribute in EAV conception.
For example from issue please use 
```$productRepository->save($product);```
or
```$productResource->save($product);```
But I recommend first way.

I am sure this is not bug and issue can be closed.

**Comment by ioweb-gr** [comment]
So what is the recommended way to update only one field or static attribute without saving the whole model?

Shouldn't there be an equivalent for those fields as well like saveField or something? 

If not, shouldn't there be a documented way to do this properly and efficiently as it apparently affects all static attributes or fields which are saved in any entity on a table column and not in eav structures.

For products specifically, I think that saving a model with 60+ attributes to update and firing all observers and plugins when you need to update only one column is a waste of resources and leaves us with no workaround except for running direct sql queries. 

It may not be a bug in the way you mentioned it but it is a limitation or lack of documentation, whatever you may call it. In any case this area needs improvement and the issue is reasonable. 

You could have marked it as dev experience instead of closing in my humble opinion as all closed issues are never processed even if they have validity
