### ISSUE TITLE
Backend Product Edit : Content > Description by Page Builder not change after edit

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#36094]
### Preconditions and environment

- Magento 2.4.4, Magento 2.4.5

### Steps to reproduce

1. Create a new product, edit contect > description by page builder
2. Add a row, Drag Element > Text to the row, Enter a few lines of text using TinyMCE instead of html codes
![image](https://user-images.githubusercontent.com/45879513/188649688-9f708ebd-9cba-4aab-bec9-23acf714b486.png)
3. Save the product, open the link in frontend.
4. Edit what you created in step 2 by TinyMCE, remove the 1st paragraph.
![image](https://user-images.githubusercontent.com/45879513/188650171-61301160-ddd8-4cb3-bc19-a6061ab0a6e8.png)
5. Click right top button and save the product.

### Expected result

You will see updated description ( 1st paragraph removed)

### Actual result

Nothing changed as the code didn't changed in step 4.
TinyMCE view after edit :
 
![image](https://user-images.githubusercontent.com/45879513/188650702-dcc0ada7-2f32-4173-a3c6-cb5ae88a4a1d.png)

![image](https://user-images.githubusercontent.com/45879513/188650752-91e7d43c-77a2-416e-b9d1-f8c4685797e2.png)
Click on the gear button. I found that the code was not changed.

![image](https://user-images.githubusercontent.com/45879513/188651091-1ce1c76a-677a-4224-9954-096e60a0b361.png)

GIF : 
https://im4.ezgif.com/tmp/ezgif-4-77f5331d3e.gif

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Yuwei9291 ,
We have tried to reproduce this issue in magento 2.4.5
Steps are followed to reproduce.
1.Created a product and open the Edit with PageBuilder.
<img width="1398" alt="Screenshot 2022-09-20 at 3 41 42 PM" src="https://user-images.githubusercontent.com/51681379/191238415-432f0227-8db1-44dd-bf57-6ca1436f4bcd.png">

2.Added row, dragged text and  added the few paragragh.
<img width="1396" alt="Screenshot 2022-09-20 at 3 42 37 PM" src="https://user-images.githubusercontent.com/51681379/191239090-71c13f81-c5e7-4222-8509-5fa5abd2459b.png">

3.Saved the product and saw the product in storefront.
<img width="1009" alt="Screenshot 2022-09-20 at 3 43 51 PM" src="https://user-images.githubusercontent.com/51681379/191239431-87571656-11d5-4d6b-9b3c-4fc795986aa2.png">
 
4.We have removed the initial few lines.
<img width="1408" alt="Screenshot 2022-09-20 at 3 45 26 PM" src="https://user-images.githubusercontent.com/51681379/191239660-e9af1d91-ba96-456e-98e5-9762803c3f9b.png">

5. we chceked in both frontend and backend the initial lines are removed
backend
<img width="1377" alt="Screenshot 2022-09-20 at 3 48 47 PM" src="https://user-images.githubusercontent.com/51681379/191240945-4e6bf040-262c-4c8f-ac39-51dff721e2a4.png">
frontend
<img width="1112" alt="Screenshot 2022-09-20 at 4 57 20 PM" src="https://user-images.githubusercontent.com/51681379/191246127-d10892e1-5b46-4a90-9e0a-bca5037ba647.png">
after click on gear button we are getting this
<img width="1482" alt="Screenshot 2022-09-20 at 5 09 41 PM" src="https://user-images.githubusercontent.com/51681379/191248709-80f7f7c9-4c81-4ef0-9779-cf5669a6f42b.png">

**Comment by engcom-Delta** [comment]
Hi @Yuwei9291 

We have noticed that, this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
