### ISSUE TITLE
dev:urn-catalog:generate generated file contains wrong paths when using Vagrant

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#3610]
When using Varnish, the paths that are generated refer to the internal structure. But the IDE tries to find the files using that path too, while that path is Vagrant specific.

So maybe it's an idea to add a --prefix or a --dir flag that allows you to set the path used. Because now I have to do a replace in the file everytime after generation.

**Comment by peterjaap** [comment]
FYI: this was added in the new PhpStorm 11;

> Mappings for Remote Interpreters
> 
> In PhpStorm 11 your work with Remote Interpreters and their mappings becomes more transparent and easy to manage. Now all detected and inherited path mappings are shown in one place. Besides when you need you can easily add custom mappings and disable detected once.

**Comment by boldhedgehog** [comment]
I have PHPStorm 10 and it automatically converts absolute paths to project directory relative paths like this: `location="$PROJECT_DIR$/vendor/magento/framework-foreign-key/etc/constraints.xsd"`

Perhaps `$PROJECT_DIR$` can be the default value in the generator?

**Comment by andimov** [comment]
@peterjaap 
Did you try to use $PROJECT_DIR$ as a solution?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
