### ISSUE TITLE
Category selection tree in edit product is not in the same order as set in Catalog->Categories

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#36101]
### Preconditions and environment

Development branch and latest release (as well as earlier ones).  Verified on latest development branch.

### Steps to reproduce

1. Create a new category under Catalog->Categories
2. Move the new category to the top of the tree
3. Edit a product and click on the Categories select... drop down

### Expected result

- New category should be at the top of the tree as per display order set in Catalog->Categories

### Actual result

The new category is at the bottom of the tree - suggesting the category tree under edit product is in creation order

Makes administering  products difficult in large catalogues more difficult

### Additional information

Current behaviour is not what I would say was intuitive or expected.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/202429882-c4cea6b7-c435-4733-bccb-6b1769fd7b5d.png)
![image](https://user-images.githubusercontent.com/60198231/202429798-149a358f-a817-4422-854b-480a46aafac1.png)
