### ISSUE TITLE
Magento API endpoints are not working as per store

### ISSUE THREAD

**Issue by howdyravi** [magento/magento2#36105]
### Preconditions and environment

- Magento version : 2.4.5

### Steps to reproduce

As per Magento Documentation, API endpoint should follow the below pattern.
`GET <host>/rest/<store_code>/V1/store/websites` to make a request.

When i try to make this call it works fine, if i use `<store_code> as default` but if i use any store code from store it gives an error.
**Working Endpoint** : `GET <host>/rest/default/V1/store/websites`
**Issue Endpoint** : `GET <host>/rest/1/V1/store/websites`

### Expected result

When run as per store code, It should give the website details with respect to that store.

### Actual result

![image](https://user-images.githubusercontent.com/39335589/188864955-11a49f70-a265-45aa-9440-6c5318e264ba.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rogerdz** [comment]
Is 1 the store code ? I think it is store id

**Comment by howdyravi** [comment]
Yeahh!  Thats correct.
I think previously it used to work with store ID.

nvm ! Thanks @rogerdz
