### ISSUE TITLE
 Fatal when using GraphQl query

### ISSUE THREAD

**Issue by DmitrySamushchenko** [magento/magento2#36117]
### Preconditions and environment

- Magento 2.4.5
- Default Magento ElasticSearch7
- Not empty database prefix, for example "pref"

### Steps to reproduce

1. Run this graphQl query:
```
query {
  products(filter: {category_id: {eq: "2"}}, sort: {price:ASC}, currentPage: 1) {
    items {
      ...productAttributesForListing
      ... on ConfigurableProduct {
        variants {
          __typename
        }
      }
    }
  }
}

fragment productAttributesForListing on ProductInterface {
  categories {
    breadcrumbs {
      category_name
    }
  }
}
```

### Expected result

Results without error:
![image](https://user-images.githubusercontent.com/90465167/189161206-7462330c-2fbd-4de0-b2f2-6a6f65ddf031.png)

### Actual result

Fatal Error: 
![image](https://user-images.githubusercontent.com/90465167/189159984-5e8deb4e-e41f-48db-814a-fb711a2220d8.png)

### Additional information

This error happened because the subquery
`SELECT 1 FROM store_group WHERE cat_index.category_id IN (store_group.root_category_id`
 is missing a table prefix for `store_group`
 
 See `\Magento\CatalogGraphQl\Model\Resolver\Product\ProductCategories::getCategoryIdsByProduct`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop

**Comment by engcom-Lima** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6685 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6685&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
