### ISSUE TITLE
Magento 2 Admin page is just showing source code

### ISSUE THREAD

**Issue by oa19** [magento/magento2#36110]
Today I made two changes to a Magento instance and it has totally broken the admin page. The login page is completely fine but once logged in it is all source code.

The two changes were
- deleting orders using an app
- creating a directory in the tmp folder

Has anyone got any ideas how we fix this?

<img width="1435" alt="Screenshot 2022-09-07 at 22 02 15" src="https://user-images.githubusercontent.com/50533202/188979550-2bf82199-ced5-4ce7-b7b6-433e60716485.png">

**Comment by engcom-Delta** [comment]
Hi  @oa19 oa19,

Thank you for reporting and collaboration. However, deleting orders with 3rd party extensions / app’s code is not part of https://github.com/magento/magento2 git repository. Community cannot provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.

Thank you.

**Comment by engcom-Delta** [comment]
Hi @oa19 

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Delta** [comment]
Hi @oa19

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
