### ISSUE TITLE
Setup does not even start

### ISSUE THREAD

**Issue by luca-vercelli** [magento/magento2#3611]
Trying to install Magento-CE-2.0-2016-01-28-02-26-45 on nginx.
The setup does not even start.
When I browse to the homepage, I see the Magento favicon, I see the browser move to /setup/ folder, and then I see a blank page. Some errors appears in log file:

```
(...) open() "/home/myname/mypath/setup/index.php/navigation" failed (20: not a directory) (...) request: GET /setup/index.php/navigation HTTP/1.1
```

**Comment by luca-vercelli** [comment]
Similar issue with apache

**Comment by mazhalai** [comment]
What OS? Also have you checked file permissions?
You can try setting [developer mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) to see more detailed errors.

**Comment by luca-vercelli** [comment]
OS is Linux Ubuntu Server. File permissions look ok, apache user can read and write every file in the docroot, even hidden ones.
I was not able to set up developer mode. If I run

```
./magento deploy:mode:show
```

or such, I get an error:

```
There are no commands defined in the "deploy:mode" namespace.
```

php version is 5.5.9

**Comment by mazhalai** [comment]
Sorry I should have been cleared, before installation, to turn developer mode on, uncomment line 5 on [.htaccess](https://github.com/magento/magento2/blob/develop/.htaccess#L5) and restart server. Also, check contents of var/log and apache logs too

**Comment by luca-vercelli** [comment]
Turned on. I still see a blank page, and no var/log file. In ngninx logs, now I see a different error:
    FastCGI sent in stderr: Access to the script /home/myname/mypath/setup/index.php/navigation have been denied (see security.limit_extensions)

**Comment by luca-vercelli** [comment]
So, I think this is not an issue of Magento but a configuration problem of php5-fpm (fastcgi). The rewrite engine is not working and I cannot set it up.

**Comment by luca-vercelli** [comment]
I have solved by myself, with a small hacking into nginx.conf.sample. I had to add a rewrite rule to convert "index.php/smthg" into "index.php?smthg":

```
location ~ ^/setup/index.php {
    rewrite ^/setup/index.php/(.*)$ /setup/index.php?$1 break;
    ...
}
```

Anyway, I still don't understand how the standard Magento setup can work on nginx.

**Comment by mazhalai** [comment]
@luca-vercelli closing since your issue has been resolved. Please feel free to open a new issue if problems persist.
