### ISSUE TITLE
Magento 2.4.x When Elasticsearch doesn't work, orderings will be unlimitedly spammed. 

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#36119]
### Preconditions and environment

- Magento 2.4.x
- Catalog Search Engine was set Elasticsearch7

### Steps to reproduce

- Add to cart
- Go checkout page
- Disable Elasticsearch service (Elasticsearch suddenly stop working)
- Click Place Order button
- An error message was shown but order was still placed.
- You can spam "Click Place Order" more one times without limit action and the orders would be placed without any mechanism which prevents Place Order action.
- If your store have Credit or Reward Points features(can be checked in EE ). In this case, customer can apply credit points to get $0 order without being subtracted any credit points.

### Expected result

- Order is not placed successfully
- Order should not spammed.
- Admin should not be able to do invoice,shipping etc.

### Actual result

- Order is placed successfully
- Can spam Place Order to make many orders at the same time.
- https://www.loom.com/share/00369a0f855a4e50be2e5594bc92ddb7
- Admin is be able to do invoice,shipping etc.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Magento 2.4.x When Elasticsearch doesn't work, orderings will be unlimitedly spammed.

**Pre-requisite:** 
- Magento `2.4-develop` should be installed.
- Elasticsearch 7

**Steps to reproduce:**

1. Add to cart
2. Go checkout page
3. Disable Elasticsearch service (Elasticsearch suddenly stop working)
4. Click Place Order button
5. An error message was shown but order was still placed.
6. You can spam "Click Place Order" more one times without limit action and the orders would be placed without any mechanism which prevents Place Order action.
7. If your store have Credit or Reward Points features. In this case, customer can apply credit points to get $0 order without being subtracted any credit points.(can be checked in EE version)

**Expected result:**  

1. Order should be placed. 
2. Store credit should not be used.
3. Admin should not be able to do invoice,shipping etc.

**Actual result:** 

1. Order is placed successfully
2. Can spam Place Order to make many orders at the same time.
4. Admin is be able to do invoice,shipping etc.

**Screenshots:**
**Order placed after elaticsearch was down:**
<img width="1360" alt="Screenshot 2022-09-28 at 2 21 26 PM" src="https://user-images.githubusercontent.com/60198022/192736999-f3efaf64-6a9f-43d4-b1f5-f8d2a393cf47.png">

**Showing error in the frontend but order is placed successfully:**
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/60198022/192737172-9206a17e-b6f8-489f-a129-587b132a2e45.png">
**Store credit was applied and order was placed:**
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/60198022/192738335-5cbe7323-e57a-4523-8198-cbf88b535c8d.png">

**Comment by texboy** [comment]
@magento I am working on this
