### ISSUE TITLE
Template file is not found if a module is sym-linked

### ISSUE THREAD

**Issue by victor-shelepen** [magento/magento2#3612]
Hello.
The setting "Follow sym links" is enabled. But the template is not loaded correctly. I've found that in
lib/internal/Magento/Framework/Filesystem/Driver/File.php:214, getAbsolutePath . It seems that it  is not designed to process absolute paths. 

The root of the project is /github/vlikin/magento2/

According to the project The path of the template(it follows on the link) is:
/github/vlikin/magento2/app/code/Vlikin/Blog/view/frontend/templates/list.phtml

The real path(wihout link) is:
/github/vlikin/m2-module/log/view/frontend/templates/list.phtml

During debugging, I've found that the real path is used. The absolute path is not processed well, so I receive 

**/github/vlikin/magento2**/github/vlikin/m2-module/log/view/frontend/templates/list.phtml

`
    lib/internal/Magento/Framework/Filesystem/Driver/File.php:214

```
public function getAbsolutePath($basePath, $path, $scheme = null)
{
    return $this->getScheme() . $basePath . $path;
}
```

`

**The absolute path is not processed well**

**Comment by victor-shelepen** [comment]
I've found a such problem here:
http://magento.stackexchange.com/questions/95071/magento-2-does-not-allow-linking-modules-using-symlinks

It seems an old issue. I've not found duplicate issues.

**Comment by palamar** [comment]
@vlikin 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by giacmir** [comment]
Same with 2.1.6.

It's a generic problem with the File driver that does not take into account symlinks, and duplicates the first part of the path if the given path has symlinks into it..
