### ISSUE TITLE
Reordering bundle options does not work as expected

### ISSUE THREAD

**Issue by densen45** [magento/magento2#36129]
### Preconditions and environment

- Magento version 2.4.4.-p1

### Steps to reproduce

1. Create a new bundle product
2. Add at least two options
3. Try to reorder the options via drag and drop

### Expected result

Reordering the options does work via drag and drop.

### Actual result

Reordering the options does not work.

Touching the drag handle makes the options element to jump/snap to the left but it cannot be moved. 

### Additional information

If you collapse all the options and then try to drag an option, you can move that option down one position in the order.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment]
@magento give me 2.4.4-p1 instance

**Comment by densen45** [comment]
@magento give me 2.4.4-p1 instance

**Comment by densen45** [comment]
@magento give me 2.4-develop instance

**Comment by densen45** [comment]
I was able to reproduce this issue on the provided 2.4-develop instance.

**Comment by densen45** [comment]
The reason for this issue is, that the dynamic-rows `table` element that contains the bundle options has no `thead` element (possible confusion: I'm not referring here to the tables containing the selections/simple products, these do indeed have a `thead` element).

In the [dnyamic-rows/dnd.js](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dnd.js) the min and max Y-positions are calculated for the elements that are dragged (on the mouse down event). The calculation for the max value depends on the min value and the calculation for the min value assumes, that a `thead` element exists. If no `thead` element exists the min value is `NaN`.
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dnd.js#L137-L139

This leads to the fact that when moving the mouse, the translation of the position of the dragged element is never entered.
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dnd.js#L168-L174

**Comment by densen45** [comment]
@magento I am working on this

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by Den4ik** [comment]
Duplicate for https://github.com/magento/magento2/issues/36051
