### ISSUE TITLE
Custom layout handle when there are no search results

### ISSUE THREAD

**Issue by gyduxa** [magento/magento2#36125]
### Preconditions and environment

- Magento Open Source 2.4
- I've checked the resolved and old issue #18038 for Magento 2.3 and its [PR](https://github.com/magento/magento2/pull/18069)
- In Magento 2.4 I can see the similar code in `/vendor/magento/module-catalog-search/` files calling `DEFAULT_NO_RESULT_HANDLE` and referring to `catalogsearch_advanced_result_noresults` and also `catalogsearch_result_index_noresults`.
- I have my magento files in /vendor/ folder and on my `/app/design/frontend/{my_vendor_folder}/{my_project_folder}/` I've created `/Magento_CatalogSearch/layout/` with the layout files: `catalogsearch_advanced_result_noresults.xml` and `catalogsearch_result_index_noresults.xml` to override the module
- In those files I tried with the [code](https://github.com/magento/magento2/issues/18038#issuecomment-423064521) @qsolutions-pl also referred in his issue
- I ran upgrade, di compile, deploy -f, c:f
- In **storefront** when I search for something to get no results I have the 2 columns layout on the `/catalogsearch/result/?q=something` but I can call layout="1column" in `catalogsearch_advanced_result_noresults` and get the 1 column in `/catalogsearch/advanced/result/?name=something`. So it seems is not working for the simple search result.

Thank you very much

### Steps to reproduce

1. Navigate to storefront and use the catalogsearch with a keyword that won't have results
2. The result page has 2 columns (sidebar and results)

### Expected result

I want to define 1column layout because I want to remove the sidebar (because it's empty) in no results page.

### Actual result

The result page has 2 columns (sidebar and results)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gyduxa** [comment]
I've edited the last bullet on Preconditions on the first post, because it works for the results on the Advanced Page but not for the results on the simple page.

It works adding the `catalogsearch_advanced_result_noresults.xml`, in my case now, I'm overriding on `app/code/{my_vendor_folder}/Magento_CatalogSearch/view/frontend/layout/catalogsearch_advanced_result_noresults.xml`) with

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" />
```

But the same approach doesn't work for `catalogsearch_result_index_noresults.xml`

**Comment by rogerdz** [comment]
It still works, I can't duplicate

![2022-09-14_22-34](https://user-images.githubusercontent.com/78783748/190198870-dc601eff-d2dd-4c4d-9835-daf61243ff62.png)
![2022-09-14_22-35](https://user-images.githubusercontent.com/78783748/190199011-e859645f-1252-4e18-bf9a-390d366051ae.png)

**Comment by gyduxa** [comment]
Thank you for the confirmation @rogerdz . I've discovered a module was interfering with this, after disabled it, it worked as expected also.
