### ISSUE TITLE
Bundle Options Qty Errore

### ISSUE THREAD

**Issue by AndreaMastracchio** [magento/magento2#36120]
### Preconditions and environment

- Magento version Magento CLI 2.3.3-p1
In the quantity control function, the quantity of the bundle/configurable product is transmitted and not that of the option. Thus, if one of the options has a minimum purchase, the bundle product cannot be purchased. To correct this, I created a preference in the QuantityValidator.php file. The function checkOptionsQtyIncrements I changed from this:

"
$result = $this->stockState->checkQtyIncrements(
                $option->getProduct()->getId(),
                $quoteItem->getData('qty'),
                $option->getProduct()->getStore()->getWebsiteId()
            );
"

to this:

"
 $result = $this->stockState->checkQtyIncrements(
                $option->getProduct()->getId(),
                $option->getValue(),
                $option->getProduct()->getStore()->getWebsiteId()
            );
"

As you can see, the quantity of the product itself (i.e. the bundle) is passed and not the quantity of the option

### Steps to reproduce

To reproduce the bug, it is necessary to create a bundle with a product inside that has a minimum purchase. After adding it to the cart, if you reach the cart page, this does not continue with an error message that the quantity is incorrect.

### Expected result

Corrected checkout flow for bundled products with miminum purchase options

### Actual result

Unable to close the order

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @AndreaMastracchio,


Thanks for reporting and collaboration.


We are happy to assist to you.Kindly provide exact steps to reproduce and also kindly provide screenshots if required.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @AndreaMastracchio,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.
