### ISSUE TITLE
Unable to reindex Product Prices in m

### ISSUE THREAD

**Issue by shocker178** [magento/magento2#36139]
### Preconditions and environment

- Magento version 2.4.4
- Have migrated data from Magento 1.9.3.8 store
- No customisations of installation, no changes made in Magento admin

### Steps to reproduce

1. Run php bin/magento indexer:reindex catalog_product_price

### Expected result

`Product Price index has been rebuilt successfully`

### Actual result

Error:
```
Product Price index process error during indexation process:
Notice: Undefined offset: 768 in /web/m244/vendor/magento/module-bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php on line 117
```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
**Hi @shocker178 ,**

We are trying to reproduce the issue in magento 2.4.4 instance.But we are not able to reproduce.
Product Price index has been rebuilt successfully.

**Screenshots**:
![3](https://user-images.githubusercontent.com/60198592/190132104-ce977f01-7ce6-4ab7-871a-6f79cf0e5c23.png)


Steps:
1.Install 2.4.4 instance
2.Run php bin/magento indexer:reindex catalog_product_price
3.Product Price index has been rebuilt successfully.


Let us know if we are missing anything!!!

Thnaks!!!

**Comment by rodrigowebjump** [comment]
@magento give me 2.4.4 instance

**Comment by vberthet** [comment]
I've got the same issue. If a bundle product is assign to no store (ie all stores are unchecked  in "Product in Websites") then the indexer crash.

`Product Price index process error during indexation process:
Notice: Undefined offset: 1393 in /home/dexergie/www/releases/173/vendor/magento/module-bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php on line 124
`

Inside Magento\Bundle\Model\ResourceModel\Indexer\Price\DisabledProductOptionPriceModifier :
```php
private function getWebsiteIdsOfProduct(int $entityId): array
    {
        if (isset($this->websiteIdsOfProduct[$entityId])) {
            return $this->websiteIdsOfProduct[$entityId];
        }
        $connection = $this->resourceConnection->getConnection('indexer');
        $select = $connection->select();
        $select->from(
            ['product_in_websites' => $this->resourceConnection->getTableName('catalog_product_website')],
            ['website_id']
        )->where('product_in_websites.product_id = ?', $entityId);
        foreach ($connection->fetchCol($select) as $websiteId) {
            $this->websiteIdsOfProduct[$entityId][] = (int)$websiteId;
        }
        return $this->websiteIdsOfProduct[$entityId];
    }
```

If the product as not website assigned $connection->fetchCol($select) will return an empty array so $this->websiteIdsOfProduct[$entityId] will never be populated. 

This could be fixed by : 
```php
private function getWebsiteIdsOfProduct(int $entityId): array
    {
        if (isset($this->websiteIdsOfProduct[$entityId])) {
            return $this->websiteIdsOfProduct[$entityId];
        }
        $connection = $this->resourceConnection->getConnection('indexer');
        $select = $connection->select();
        $select->from(
            ['product_in_websites' => $this->resourceConnection->getTableName('catalog_product_website')],
            ['website_id']
        )->where('product_in_websites.product_id = ?', $entityId);
        $this->websiteIdsOfProduct[$entityId] = [];
        foreach ($connection->fetchCol($select) as $websiteId) {
            $this->websiteIdsOfProduct[$entityId][] = (int)$websiteId;
        }
        return $this->websiteIdsOfProduct[$entityId];
    }
```
