### ISSUE TITLE
Call to a member function getMethodInstance() on null in /srv/magento/vendor/paypal/module-braintree-core/Block/Form.php:174

### ISSUE THREAD

**Issue by TerrapinSoftware** [magento/magento2#36131]
### Preconditions and environment

- Magento version: 2.4.5
- PHP 8.1.9

### Steps to reproduce

1. Make sure that BrainTree credit card payments are enabled.
2. View an order in the admin backend.
3. Click Edit.

### Expected result

The Edit form displays

### Actual result

Partial HTML is displayed

### Additional information

The file `vendor/paypal/module-braintree-core/Block/Form.php` contains a bug. The private variable `$paymentDataHelper` is not initialized. The fix is:

```php
use Magento\Payment\Helper\Data as PaymentDataHelper;
...
    public function __construct(
        ...
        PaymentDataHelper $paymentDataHelper,
        array $data = []
    ) {
        parent::__construct($context, $paymentConfig, $data);
        ...
        $this->paymentDataHelper = $paymentDataHelper;
    }


### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @TerrapinSoftware ,
Thank you for reporting and collaboration. As mentioned by @hostep , this is a known issue and mentioned in release notes of 2.4.5 [devdocs](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-5.html#known-issue) See the [Admin can’t create order/reorder when Braintree payment enabled](https://support.magento.com/hc/en-us/articles/8322266352525) Knowledge Base article for a discussion of this issue and access to the patch. We are closing this issue. Please reopen / create new issue if you are still facing any issues.
Thank you.
