### ISSUE TITLE
Magento Community Edition 2.0 User Guide

### ISSUE THREAD

**Issue by VarinhoPontes** [magento/magento2#3613]
In pag 420 bad spelling
![pag 420](https://cloud.githubusercontent.com/assets/5529234/13457885/4201bb4a-e062-11e5-8692-365b6e432c0e.png)

**Comment by ccondra** [comment]
Thanks so much for passing this along. It looks like part of the sentence got deleted. I fixed the missing info, and also updated the topic while I was in there. The correction is now live in the online user guide, and will be included the next time the pdf is generated. Here's a link: http://docs.magento.com/m2/ce/user_guide/catalog/navigation-layered-filterable-attributes.html
Claire

**Comment by choukalos** [comment]
Fixed, Closing.
