### ISSUE TITLE
OAuth1.0 should not validate the timestamp against server's system clock

### ISSUE THREAD

**Issue by higuhi** [magento/magento2#36135]
### Preconditions and environment

- Magento version: 2.x (found in 2.4.0 and also confirmed on vanilla 2.5.4)
- Anything else that would help a developer reproduce the bug 

### Step 1 - Magento Setup
1. Setup clean vanilla Magento
2. Go to SYSTEM > Integrations  and click "Add New Integration"
3. Fill in the form and create a new integration (choose ALL for Available APIs)

### Step2 - OAuth1.0 Test Client 
You can use any OAuth1.0 Client, but you can quickly set up a test client if you have PHP and composer. 
Note that the client must run outside the Magento server because we need to change the time of the client to replicate the issue.

1. make sure you can run PHP and composer commands
2. run `composer require guzzlehttp/oauth-subscriber` 
3. copy and paste the PHP script below and update the base URL and OAuth credentials
4. run the script to see if it works (you should get HTTP Error Response 400) 
5. change the client PC's clock to the future time like tomorrow (the time must be more than 10 minutes future than the Magento server clock)
6. run the script and you will get a HTTP Error Response 401 with "An error occurred validating the nonce" 

```
<?php

require_once 'vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Subscriber\Oauth\Oauth1;

$stack = HandlerStack::create();

// Base URL to your magento
$baseURL = '<Your Base URL>';

// Integration credentials 
$middleware = new Oauth1([
    'consumer_key'    => '<Your Consumer Key>',
    'consumer_secret' => '<Your Consumer Sercret>',
    'token'           => '<Your Token>',
    'token_secret'    => ''<Your Token Secret>',
    'signature_method' => Oauth1::SIGNATURE_METHOD_HMACSHA256,
]);
$stack->push($middleware);

$client = new Client([
    'base_uri' => $baseURL,
    'handler' => $stack
]);

// Set the "auth" request option to "oauth" to sign using oauth

try {
    $res = $client->get('rest/V1/products', ['auth' => 'oauth']);
} catch (\Exception $ex) {
    echo "You should get HTTP ERRROR Response 400 with parameter error here \n";
    echo $ex->getMessage();
}
```

### Expected result

```
You should get HTTP ERRROR Response 400 with parameter error here 
Client error: `GET http://vanila-shop.europeanspermbank.com/rest/V1/products` resulted in a `400 Bad Request` response:
{"message":"\"%fieldName\" is required. Enter and try again.","parameters":{"fieldName":"searchCriteria"},"trace":"#0 \/ (truncated...)
```

### Actual result

```
You should get HTTP ERRROR Response 400 with parameter error here 
Client error: `GET http://vanila-shop.europeanspermbank.com/rest/V1/products` resulted in a `401 Unauthorized` response:
{"message":"An error occurred validating the nonce","trace":"#0 \/var\/www\/html\/magento\/vendor\/magento\/framework\/O (truncated...)
```

Even if the client PC or server has the future time incorrectly, Magento should not reject the request as long as the timestamp is newer than the timestamp of the previous request.

### Additional information

When OAuth1 authentication is used, the following code validates the nonce and timestamp from the client requesting authentication. 

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/Integration/Model/Oauth/Nonce/Generator.php#L79

According to the if condition in line 79, it rejects request if the timestamp is in the future exceeding  TIME_DEVIATION, which is 10 minutes. 

In other words, if the client mistakingly has a wrong time in the future OR magento server incorrectly has past time, the client is not authenticated. 

This validation logic that checks client's timestamp against the server's system clock is wrong because:
- it is not defined in OAuth1.0 (see https://oauth.net/core/1.0/#nonce) - it only says "The timestamp value MUST be a positive integer and MUST be equal or greater than the timestamp used in previous requests", so we only need to check the timestamp from the timestamp used in the previous request, not against the sever's timestamp. 
- we cannot expect all client PC/servers to have the correct system time

I am not sure, but the issue reported https://github.com/magento/magento2/issues/33724 might be caused by this. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by higuhi** [comment]
@magento I am working on it

**Comment by higuhi** [comment]
@magento add to contributors team

**Comment by higuhi** [comment]
@mangento add to contributors team

**Comment by higuhi** [comment]
@magento add to contributors team

**Comment by higuhi** [comment]
@magento I am working on it

**Comment by engcom-Hotel** [comment]
Hello @higuhi,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento's development branch i.e. 2.4-develop and the issue is reproducible for us. We have also checked the official website of [Oauth1.0](https://oauth.net/core/1.0/#nonce) for the documentation related with timestamp, which is as follows:

>  Nonce and Timestamp
> Unless otherwise specified by the Service Provider, the timestamp is expressed in the number of seconds since January 1, 1970 00:00:00 GMT. The timestamp value MUST be a positive integer and MUST be equal or greater than the timestamp used in previous requests.

> The Consumer SHALL then generate a Nonce value that is unique for all requests with that timestamp. A nonce is a random string, uniquely generated for each request. The nonce allows the Service Provider to verify that a request has never been made before and helps prevent replay attacks when requests are made over a non-secure channel (such as HTTP).

We are getting the actual result mentioned in the main description. Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @higuhi,

We have re-verified the issue in the latest 2.4-develop branch, when we ran the script provided in the main description, the first time only we got the `401 Unauthorized`. Please refer to the below screenshot:

![image](https://github.com/user-attachments/assets/c915aded-41f0-4eac-a687-49315fcd59a4)

Please review the steps again and let us know if we need to change anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @higuhi,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks
