### ISSUE TITLE
PHP 8.1 not supported because wrong dependency for friendsofphp/php-cs-fixer 

### ISSUE THREAD

**Issue by antoniocarboni** [magento/magento2#36138]
### Preconditions and environment

- Magento version: 2.4.5
- PHP 8.1

### Steps to reproduce

Copy metapackage composer.json and run composer update on php 8.1

### Expected result

composer update complete the update process

### Actual result

Composer fail with this error:
`- symfony/process[v5.0.0, ..., v5.0.8] require php ^7.2.5 -> your php version (8.1.0) does not satisfy that requirement.
    - symfony/process[v4.0.0, ..., v4.4.10] require php ^7.1.3 -> your php version (8.1.0) does not satisfy that requirement.
    - Root composer.json requires friendsofphp/php-cs-fixer ~3.8.0 -> satisfiable by friendsofphp/php-cs-fixer[v3.8.0].
    - Root composer.json requires deployer/deployer ^6.9 -> satisfiable by deployer/deployer[v6.9.0].
    - Root composer.json requires magento/product-community-edition 2.4.5 -> satisfiable by magento/product-community-edition[2.4.5].
    - Conclusion: don't install symfony/process v6.1.3 (conflict analysis result)
    - deployer/deployer v6.9.0 requires symfony/process ~2.7|~3.0|~4.0|~5.0 -> satisfiable by symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.11].
    - You can only install one version of a package, so only one of these can be installed: symfony/process[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.11, v6.0.0, ..., v6.1.3].
    - friendsofphp/php-cs-fixer v3.8.0 requires symfony/process ^5.4 || ^6.0 -> satisfiable by symfony/process[v5.4.0, ..., v5.4.11, v6.0.0, ..., v6.1.3].
    - Conclusion: don't install symfony/process v5.4.11 (conflict analysis result)`

### Additional information

****This error is caused by** wrong dependency** on package 
"friendsofphp/php-cs-fixer" or symfony/process".

friendsofphp/php-cs-fixer "~3.8.0", require a "symfony/process": "^5.4 || ^6.0",

but Magento 2.4.5 require magento/framework 103.0.5 which require "symfony/process": "~4.4.0 ",

### Temporary Solution

The **temporary solution** actually is remove "friendsofphp/php-cs-fixer" from require-dev packages
. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
We have our Composer require set to friendsofphp/php-cs-fixer": "^2.18"
Its then grabbing v2.19.3, so I guess that must be the best version that works with everything else.

**Comment by AaronONeill** [comment]
We haven't seen this issue in particular, but we have seen other "weirdisms" since the upgrade. What we did to solve what we were seeing was just to ensure composer was updated with `composer self-update` and then cleared vendor and removed the composer.lock (if they exist) - `rm -rf vendor/* composer.lock`

After that we did another `composer install`, which did the trick.

**Comment by hostep** [comment]
@antoniocarboni: I'm noticing the mention of `deployer/deployer` in your error, which is not a dependency of Magento.
Have you tried it without `deployer/deployer` already? Or tried upgrading `deployer/deployer` to 7.x ?

**Comment by devchris79** [comment]
@hostep I am guessing the 3.8.0 version has been taken [from here ](https://github.com/magento/magento2/blob/2.4-develop/composer.json)
Is there a page with the recommended 2.4.5 version constraints?

I didn't realise we were so out of date with our version of the php-cs-fixer!

**Comment by hostep** [comment]
If you just setup a new 2.4.5 project with composer, you'll get the `composer.json` file you are looking for. If you add the `--no-install` flag, it will go really quickly.

So something like this:

```
composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.5 ./some_directory
```

**Comment by engcom-Lima** [comment]
Hi @antoniocarboni ,

Thanks for yours contribution and collaboration.

Try to install Magento2 as suggested by @hostep in above [comment]
(https://github.com/magento/magento2/issues/36138#issuecomment-1249463209) .
If you are facing any issue kindly use our official [document](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html?lang=en#get-the-metapackage). 
Let us know if you are facing any issue.

Thanks

**Comment by engcom-Lima** [comment]
HI @antoniocarboni ,

Thanks for your contribution and collaboration.

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks
