### ISSUE TITLE
[GraphQL] Price and Category Aggregation Labels are not translated

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#36140]
### Preconditions and environment

- Magento version: 2.4.5
- A store view with any language thats not english

### Steps to reproduce

Execute the following graphql query:
```GRAPHQL
query searchProducts {
    products(search: "") {
        aggregations {
            label
        }
    }
}
```

This query fetches all available aggregations (filters) and the labels for them.

### Expected result

I would expect all labels to be translated into the language of the store (german in my case).
```JSON
{
  "data": {
    "products": {
      "aggregations": [
        {
          "label": "Preis"
        },
        {
          "label": "Kategorie"
        },
        {
          "label": "Farbe"
        },
        {
          "label": "..."
        },
      ]
    }
  }
}
```

### Actual result

```JSON
{
  "data": {
    "products": {
      "aggregations": [
        {
          "label": "Price"
        },
        {
          "label": "Category"
        },
        {
          "label": "Farbe"
        },
        {
          "label": "..."
        },
      ]
    }
  }
}
```

Only the label for the attribute `color` (Farbe) is translated as set in the adminhtml. The label set for the price attribute is ignored and I can't even set any label for the category attribute.

### Additional information

The problem arises because of hardcoded labels in the code:

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Category.php#L152-L156

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Category.php#L37-L42

and

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Price.php#L60-L64

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Price.php#L33-L38

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment]
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment]
I can confirm the issue on a magento vanilla instance.
I set the language for the store to german and translated the labels for the attributes price and color.
Price and category are still in english while color is in german now.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @oneserv-heuser,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 but the issue is reproducible.Price and Category Aggregation labels are not translated.kindly refer the screenshots.



Language of the Store Configured as German.

<img width="1185" alt="Screenshot 2022-09-23 at 5 51 35 PM" src="https://user-images.githubusercontent.com/51680745/191959187-217fefbc-733f-43be-b063-4729f61c7070.png">




<img width="1195" alt="Screenshot 2022-09-23 at 5 53 22 PM" src="https://user-images.githubusercontent.com/51680745/191959355-b08f6e8d-c0c5-48df-a437-12681769449d.png">





Hence Confirming the issue.


Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Hi @oneserv-heuser ,
Development team is currently working on this issue.
Thank you.
