### ISSUE TITLE
Comment added to order alters timestamp for all comments 

### ISSUE THREAD

**Issue by mihaizs** [magento/magento2#3614]
We are testing Magento2 EE and I've noticed the following beahaviour:
Adding a comment to and order sets the timestamp of all comments to the timestamp of the comment being added. 
This happens both programatically 
\Magento\Sales\Model\Order $order->addStatusHistoryComment('some text');
and in the backend.
This should be fairly easy to replicate: just create an order and add a few comments to it. You'll notice that all comments get the timestamp of the last.

**Comment by NadiyaS** [comment]
Hi @mihaizs  ,
thank you for reporting this issue.
This bug is already fixed in develop branch [87f27af](https://github.com/magento/magento2/commit/87f27afb8e581f47292303ac16c4685ca12e7f14).
Please update your code from develop branch or wait until next release.

**Comment by mihaizs** [comment]
Just out of curiosity, who is goralgen ?

**Comment by NadiyaS** [comment]
Sorry for typo
