### ISSUE TITLE
Not able to see catalog details from admin panel

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#3615]
while clicking on link product-> catalog, system is hanged, in exception log i am getting exception:

main.CRITICAL: exception 'Zend_Db_Adapter_Exception' with message 'Report ID: webapi-56ca8c9077635; Message: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)' in /var/www/html/agrihubV2/vendor/magento/framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/agrihubV2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Zend_Db_Adapter_Exception))
#1 /var/www/html/agrihubV2/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Zend_Db_Adapter_Exception))
#2 /var/www/html/agrihubV2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/agrihubV2/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/agrihubV2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/agrihubV2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by arunkasyakar** [comment]
sorry log is this one:

[2016-03-02 11:18:13] main.CRITICAL: exception 'ReflectionException' with message 'Report ID: webapi-56d6cbf5424dd; Message: Class  does not exist' in /var/www/html/agrihubV2/vendor/magento/framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/agrihubV2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(ReflectionException))
#1 /var/www/html/agrihubV2/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(ReflectionException))
#2 /var/www/html/agrihubV2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/agrihubV2/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/agrihubV2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/agrihubV2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by vzabaznov** [comment]
Hi @arunkasyakar, thank you for reporting, please check that you install all composer dependency properly.

**Comment by arunkasyakar** [comment]
that issue was from my side, it is resolved thanks

**Comment by tinelps** [comment]
hi @arunkasyakar, can you please tell me what did you do to solve this problem? what issue from your side? as i am facing the exactly same error with you right now. Please reply, thanks.
