### ISSUE TITLE
Magento 2.4.5: Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#36168]
### Preconditions and environment

- Magento version 2.4.5 CE
- Upgrade from 2.4.3 (vendor folder was deleted during upgrade)
- PHP 8.1

ERROR:
 Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given, called in /home/www/public_html/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php on line 130

### Steps to reproduce

1) Put product out of stock

2) Advanced Inventory -> Backorders -> Allow Qty Below 0 and Notify Customer

3) Enable notifications for "back to stock" (https://magefan.com/blog/magento-2-out-of-stock-notification#:~:text=To%20enable%20Magento%202%20Out,Comes%20Back%20in%20Stock%20option.)

4) Go to product page, and request to be notified about item coming back to stock.

5) Put item back in stock and check debug.log

You might need to run reindex on **cataloginventory_stock** as it's responsible for in stock / out of stock status of product.

### Expected result

Email is sent.

### Actual result

Email is not sent and error is thrown in logs:
 Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given, called in /home/www/public_html/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php on line 130

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
Something probably up the stack has triggered the error as line 130 in  ErrorEmailSender.php is an end of line.

Files that include ErrorEmailSender.php:

```
vendor/magento/module-product-alert/Model/Mailing/ErrorEmailSender.php:class ErrorEmailSender
vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php:     * @var ErrorEmailSender
vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php:     * @param ErrorEmailSender $errorEmailSender
vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php:        ErrorEmailSender $errorEmailSender
vendor/magento/module-product-alert/Model/Observer.php:     * @see \Magento\ProductAlert\Model\Mailing\ErrorEmailSender::XML_PATH_ERROR_TEMPLATE
vendor/magento/module-product-alert/Model/Observer.php:     * @see \Magento\ProductAlert\Model\Mailing\ErrorEmailSender::XML_PATH_ERROR_IDENTITY
vendor/magento/module-product-alert/Model/Observer.php:     * @see \Magento\ProductAlert\Model\Mailing\ErrorEmailSender::XML_PATH_ERROR_RECIPIENT
```

**Comment by engcom-November** [comment]
Hi @pmonosolo ,
Thank you for reporting and collaboration. Product Alert emails are not getting triggered on Magento 2.4-develop instance is an ongoing issue confirmed [here](https://github.com/magento/magento2/issues/35602). We are closing this issue as duplicate. Kindly move on to this [issue](https://github.com/magento/magento2/issues/35602) for latest updates / solutions on the same.
Thank you.
