### ISSUE TITLE
Error 500 admin panel

### ISSUE THREAD

**Issue by mohammedTBB** [magento/magento2#36165]
### Preconditions and environment

- Magento version 2.4.5
- Php version 8.1

### Steps to reproduce

go to admin panel

### Expected result

show sign in form for admin panel with no errors

### Actual result

Error 500 in admin panel.

Server error log:
[Wed Sep 14 10:26:27.629433 2022] [proxy_fcgi:error] [pid 68838:tid 140186163726080] [client [127.0.0.1:41690](http://127.0.0.1:41690/)] Premature end of script headers: index.php
[Wed Sep 14 10:26:27.629479 2022] [proxy_fcgi:error] [pid 68838:tid 140186163726080] [client [127.0.0.1:41690](http://127.0.0.1:41690/)] AH01070: Error parsing script headers
[Wed Sep 14 10:26:27.629483 2022] [proxy_fcgi:error] [pid 68838:tid 140186163726080] (22)Invalid argument: [client [127.0.0.1:41690](http://127.0.0.1:41690/)] AH01075: Error dispatching request to :

No magento log errors.

### Additional information

removing some of the whitelisted 'img-src' in csp_whitelist will solve the problem, but of course will generate security policy errors in the console (developer tools).

Is there any limit of CSPs that can be added? any limit of the data that can be recieved from external links?

we found this, maybe it helps to understand the issue:
https://konkretor.com/2022/07/07/apache-ah01070-error-parsing-script-headers/

FYI: this problem was not exist in magento 2.4.4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mohammedTBB,


Thanks for reporting and collaboration.

We are happy to assist to you.Kindly provide exact steps to reproduce and also kindly provide screenshots if required.

Kindly go through with this [document](https://devdocs.magento.com/guides/v2.4/install-gde/composer.html) for installing a  Magento Instance.


Please let us know if you are still facing any issue.


Thanks.

**Comment by mohammedTBB** [comment]
Hi [engcom-Bravo](https://github.com/engcom-Bravo)

I have tried to reproduce the error in a fresh magento 2.4.5 instance, and it is not reproducible in a local environment.

Although on a certain server setting it could be reproduced.
