### ISSUE TITLE
Rest APi Loading Issue 

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#3616]
**During the checkout process** estimate shipping based on the address , it taking more than 15 seconds to complete the response ,here is the API call
**http://www.example.com/rest/default/V1/carts/mine/estimate-shipping-methods-by-address-id**

To increase speed i have enabled the Production mode ,but still it is taking more time to load the Checkout page.

Kindly let me know if i need to do any changes in the Apache Configuration to improve the performance.

**Comment by ishakhsuvarov** [comment]
@chaluvadiswamy Thank you for reporting this issue. Which shipping methods do you have enabled and configured?

**Comment by chaluvadiswamy** [comment]
@ishakhsuvarov , I am using my setup with sample data.by default Table Rate and Flat Rate is Enabled.

**Comment by ishakhsuvarov** [comment]
@chaluvadiswamy Currently we are unable to reproduce the issue, could you please provide settings for Table Rate which you are using? How much longer estimation takes then other operations?

**Comment by chaluvadiswamy** [comment]
@ishakhsuvarov , After you said i have disable the **Table Rates Shipping method** and tested with only the **Flat Rate shipping method** .

After doing that also i am  facing the same issue.Refer the screen shot
![capture](https://cloud.githubusercontent.com/assets/7018680/13518656/57e2b3c0-e1f6-11e5-81ee-98623946a943.JPG)

**Comment by ishakhsuvarov** [comment]
@chaluvadiswamy Looking at the overall numbers I would suggest trying some of the advices listed here https://github.com/magento/magento2/issues/2669#issuecomment-163646043

**Comment by chaluvadiswamy** [comment]
@ishakhsuvarov , Thanks for update.
Already i have followed same steps as mentioned in following link : https://github.com/magento/magento2/issues/2669#issuecomment-163646043

I didn't find any difference after enabling the compile and enable Production.

**Comment by devdesco-ceo** [comment]
Same thing here

**Comment by piotrekkaminski** [comment]
@mbrinton01 please look

**Comment by stevewinni** [comment]
I also only have Flat rate shipping turned on, and we are experiencing the same issue. debug.log and exception.log throw no insights. 

Anyone got any ideas how to debug this one....
![screen shot 2016-07-26 at 11 05 51](https://cloud.githubusercontent.com/assets/2544348/17134150/efce8542-5320-11e6-85be-f584bde30e16.png)

**Comment by veloraven** [comment]
@chaluvadiswamy is this issue still actual?
If it is not please close the issue.
If it is please provide the used Magento version.
Please also provide information about your environment: versions of PHP, MySQL and web-server used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by chinthu** [comment]
Any fix for this issue ? this api is very very slow, tried disabling flatrate and other shipping methods still its taking time to load..

**Comment by devqualwebs** [comment]
@chaluvadiswamy any solution for this? Even I'm facing this issue. Rest API taking too much time.

**Comment by misha-kotov** [comment]
@devqualwebs please open a new issue and add repro steps, specify your Magento version, and whether this is reproducible on a clean instance. If not, add your enabled shipping methods and shipping configuration.
