### ISSUE TITLE
fatal error in GraphQL Types

### ISSUE THREAD

**Issue by RikvdHeijden** [magento/magento2#36170]
### Preconditions and environment

Version 2.4.5, don't know if other versions are currently affected

### Steps to reproduce

Update your local composer and run di:compile.

### Expected result

A successful di:compile

### Actual result

The message will be something like: Fatal error: Type of Magento\Framework\GraphQl\Schema\Type\StringType::$name must be string (as in class GraphQL\Type\Definition\StringType) 

### Additional information

This is caused by an dependency of magento/framework: webonyx/graphql-php which created a BC incompatible version 14.11.7.

A temporary workaround is pinning the version to 14.11.6 in the root composer.json.

An issue has already been opened in the library: https://github.com/webonyx/graphql-php/issues/1221

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tdgroot** [comment]
Can confirm, also ran into this problem on Magento 2.4.4

**Comment by Nuranto** [comment]
Same error here. Probably because of the new release of webonyx/graphql-php ?

**Comment by chrisastley** [comment]
I came across this issue earlier doing updates to an existing site. This is caused by an update earlier today to composer module webonyx/graphql-php (https://github.com/webonyx/graphql-php)

I had to downgrade by running `composer require webonyx/graphql-php:14.11.6`

**Comment by Jarzebowsky** [comment]
I came across this one on Magento 2.4.5 as well. Temporary solution given by @chrisastley does the trick.
