### ISSUE TITLE
Repost due to incorrectly closed issue #35595

### ISSUE THREAD

**Issue by NickvdMeij** [magento/magento2#36178]
### Preconditions and environment

See https://github.com/magento/magento2/issues/35595

### Steps to reproduce

See https://github.com/magento/magento2/issues/35595

### Expected result

See https://github.com/magento/magento2/issues/35595

### Actual result

See https://github.com/magento/magento2/issues/35595

### Additional information

See https://github.com/magento/magento2/issues/35595

### Release note

See https://github.com/magento/magento2/issues/35595

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Duplicate of https://github.com/magento/magento2/issues/35595
