### ISSUE TITLE
Magento2: Issue in URL rewrite

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#3617]
We can add a custom URL rewrite through the Magento back end but the URL redirection is not working properly.
Anybody please help me to solve this?

**Comment by antboiko** [comment]
Hi @vipin-eglobeits , thanks for your inquiry. 

Could you please provide more details about the issue you have? What are the steps to reproduce it?

Best,
Anton.

**Comment by vipin-eglobeits** [comment]
Please find the attached screenshot for your kind reference.
My requirement is: redirect url shop-by-brand.html?brand=4 to shop-by-brand/moldex.html.
The data is saving properly but the redirection is not working.

![seo-friendly](https://cloud.githubusercontent.com/assets/14974923/13461883/53091a58-e0aa-11e5-9890-c37a96018c18.jpeg)

**Comment by piotrekkaminski** [comment]
Such questions are better suited for community.magento.com or magento.stackexchange.com
