### ISSUE TITLE
Minify Html issue

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#36183]
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

Edit a template having a `if` condition

replace one `<?php endif ?>` with `<?php //test comment ?><?php endif ?>`

### Expected result

html file gets minified correctly

### Actual result

The `endif` is removed in minified html. The page gives a 500 result.

### Additional information

Even if it is a bad coding style, it should not fail minify.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/issues/32153
Your case already reported here

**Comment by Nuranto** [comment]
Yes sorry, I did search, however didn't find it.
