### ISSUE TITLE
Order number 000176319 show paid $1152.20, but we didn't receive the payment through Braintree, could you please advise where has the payment gone through? Thank you

### ISSUE THREAD

**Issue by DJOGlobal2022** [magento/magento2#36182]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Bravo** [comment]
Hi @DJOGlobal2022,


Thanks for reporting and collaboration.

We are happy to assist to you.Kindly provide exact steps to reproduce and also kindly provide screenshots if required.


Thanks.

**Comment by DJOGlobal2022** [comment]
Good morning

Order number  000176319 showing paid $1152.20, but we didn't receive the payment into our bank account, could you please advise where has the payment gone through. There is no payment method on the payment  information. Please see screenshot below, thank you.
***@***.***


***@***.***
If the payment information as below, we always received the payment into our bank account, thank you.
***@***.***
Regards
Jenny

Jenny Meng
ACCOUNTS RECEIVABLE ANALYST

P  1300 667 730
E  ***@***.******@***.***> or ***@***.******@***.***>


***@***.***


PO Box 6057, Frenchs Forest DC, NSW 2086
ABN 64 094 431 473

djostore.com.au
Creating Better Together(tm)

***@***.***

From: Venkata Kumar Kuntumalla ***@***.***>
Sent: Friday, September 23, 2022 9:45 PM
To: magento/magento2 ***@***.***>
Cc: Jenny Meng ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [magento/magento2] Order number 000176319 show paid $1152.20, but we didn't receive the payment through Braintree, could you please advise where has the payment gone through? Thank you (Issue #36182)

CAUTION: This email originated outside of Colfax/ESAB/DJO. IF THE SENDER IS A DJOGLOBAL EMAIL AND THIS BANNER IS PRESENT, THEN THE MAIL IS LIKELY PHISHING. Do not click links or open attachments unless you recognize the sender and know the content is safe. NEVER provide or enter your network logon credentials when asked through an external email or website. Please click on the Phish Alert button located on your Outlook toolbar to report Phishing or suspicious emails. Please feel free to forward suspicious messages to ***@***.******@***.***>


Hi @DJOGlobal2022<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDJOGlobal2022&data=05%7C01%7Cjenny.meng%40enovis.com%7Ce9a55d73c0d84fa4116d08da9d5918f1%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C637995303273662812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HH%2FIDXqVeTFkg%2B869oXas0vnFrRpiqrV2nfp1Muo4uA%3D&reserved=0>,

Thanks for reporting and collaboration.

We are happy to assist to you.Kindly provide exact steps to reproduce and also kindly provide screenshots if required.

Thanks.

-
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmagento%2Fmagento2%2Fissues%2F36182%23issuecomment-1256108765&data=05%7C01%7Cjenny.meng%40enovis.com%7Ce9a55d73c0d84fa4116d08da9d5918f1%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C637995303273662812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yJDJDb0Rp0agTaTbYzkX2ZFvdxm%2FxIQmemWpKrqiG1c%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3HJJGUOWGPRA5NJZTV7XCLV7WJ5DANCNFSM6AAAAAAQTSTLDI&data=05%7C01%7Cjenny.meng%40enovis.com%7Ce9a55d73c0d84fa4116d08da9d5918f1%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C637995303273662812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I6X%2B3n35B3R9nmiNQqbXPcF5DCqxwo5vImtZelzY4oo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Exciting news! DJO is now Enovis. Learn more here<https://www.djoglobal.com/enovis>


Confidentiality Notice: This message, together with any attachments, is intended only for the use of the individual or entity to which it is addressed and may contain confidential or privileged information. If you think you have received this message in error, please advise the sender and then delete this message and any attachments immediately.

**Comment by engcom-Bravo** [comment]
Hi @DJOGlobal2022,


Kindly provide preconditions, Steps to reproduce, Actual Result, Expected Result, and also kindly provide screenshots if required. These information will be required to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @DJOGlobal2022,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Comment by DJOGlobal2022** [comment]
Hi

May I please have a phone number to contact you, thank you.

Regards
Jenny

Jenny Meng
ACCOUNTS RECEIVABLE ANALYST

P  1300 667 730
E  ***@***.******@***.***> or ***@***.******@***.***>


***@***.***


PO Box 6057, Frenchs Forest DC, NSW 2086
ABN 64 094 431 473

djostore.com.au
Creating Better Together™

***@***.***

From: Venkata Kumar Kuntumalla ***@***.***>
Sent: Tuesday, October 11, 2022 5:11 PM
To: magento/magento2 ***@***.***>
Cc: Jenny Meng ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [magento/magento2] Order number 000176319 show paid $1152.20, but we didn't receive the payment through Braintree, could you please advise where has the payment gone through? Thank you (Issue #36182)

CAUTION: This email originated outside of Colfax/ESAB/DJO. IF THE SENDER IS A DJOGLOBAL EMAIL AND THIS BANNER IS PRESENT, THEN THE MAIL IS LIKELY PHISHING. Do not click links or open attachments unless you recognize the sender and know the content is safe. NEVER provide or enter your network logon credentials when asked through an external email or website. Please click on the Phish Alert button located on your Outlook toolbar to report Phishing or suspicious emails. Please feel free to forward suspicious messages to ***@***.******@***.***>


Hi @DJOGlobal2022<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDJOGlobal2022&data=05%7C01%7Cjenny.meng%40enovis.com%7C23ca4796125a46317a5008daab4f5130%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C638010654408120726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6NakMs2bSRPqfaSichEEbXBziUQBb%2BzsaGejdXkv1Vk%3D&reserved=0>,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmagento%2Fmagento2%2Fissues%2F36182%23issuecomment-1274133625&data=05%7C01%7Cjenny.meng%40enovis.com%7C23ca4796125a46317a5008daab4f5130%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C638010654408276973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l7l3YEQAXV9bWvTExTroe6QToAzTei12pRjXx12PGg0%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3HJJGQ7YTBK7X4WXMBIHPLWCUAF3ANCNFSM6AAAAAAQTSTLDI&data=05%7C01%7Cjenny.meng%40enovis.com%7C23ca4796125a46317a5008daab4f5130%7C02b1d92c0247477b9715ace0b8f6395f%7C0%7C0%7C638010654408276973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oK63BTMg79i%2B7AsdzJBut2mzqzRmsbvUV5COEHPCozc%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Exciting news! DJO is now Enovis. Learn more here<https://www.djoglobal.com/enovis>


Confidentiality Notice: This message, together with any attachments, is intended only for the use of the individual or entity to which it is addressed and may contain confidential or privileged information. If you think you have received this message in error, please advise the sender and then delete this message and any attachments immediately.
