### ISSUE TITLE
Magento multishipping error message incompatible with update-shopping-cart.js

### ISSUE THREAD

**Issue by iwanvanzijderveld** [magento/magento2#36184]
### Preconditions and environment

- 2.4.5
- Magento Multishipping

### Steps to reproduce

1. Login as customer.
2. Add 99 quantity of any item
3. Proceed to cart
4. Use multishipping checkout
5. Update the quantity to reach the limit for multishipping quantity
6. Submit

### Expected result

Error message to be shown:
`The requested qty exceeds the maximum qty allowed in shopping cart`

### Actual result

Site keeps loading with error in console:
`Uncaught SyntaxError: Unexpected token 'M', "Maximaal a"... is not valid JSON
    at JSON.parse (<anonymous>)
    at $.<computed>.<computed>.onError (update-shopping-cart.js:112:37)
    at $.<computed>.<computed>.onError (widget.js:132:25)
    at $.<computed>.<computed>.<anonymous> (update-shopping-cart.js:90:26)
    at fire (jquery.js:3500:50)
    at Object.fireWith [as resolveWith] (jquery.js:3630:29)
    at done (jquery.js:9796:30)
    at XMLHttpRequest.<anonymous> (jquery.js:10057:37)`

### Additional information

In update-shopping-cart.js expects a JSON object in error_message, but the checkitems call returns a string.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in Magento **2.4-develop**  &&  **2.4.5** .

**Description:** Magento multishipping error message incompatible with update-shopping-cart.js

**Pre-requisite:**
- 2.4.5 and 2.4-develop should be installed.
- Multi_shipping

**Steps to reproduce:**
1. Login as customer.
2. Add 99 quantity of any item
3. Proceed to cart
4. Use multishipping checkout
5. Update the quantity to reach the limit for multishipping quantity
6. Submit

**Expected result:** Error message to be shown:
`The requested qty exceeds the maximum qty allowed in shopping cart`

**Actual result:** 
_**Site keeps loading with error in console:**_
`Uncaught SyntaxError: Unexpected token 'M', "Maximaal a"... is not valid JSON at JSON.parse (<anonymous>) 
at $.<computed>.<computed>.onError (update-shopping-cart.js:112:37)
at $.<computed>.<computed>.onError (widget.js:132:25) 
at $.<computed>.<computed>.<anonymous> (update-shopping-cart.js:90:26) 
at fire (jquery.js:3500:50) at Object.fireWith [as resolveWith] (jquery.js:3630:29) 
at done (jquery.js:9796:30) at XMLHttpRequest.<anonymous> (jquery.js:10057:37)`

**Screenshots:**
<img width="1508" alt="Screenshot 2022-09-23 at 5 33 11 PM" src="https://user-images.githubusercontent.com/60198022/191957743-954ef00f-3040-40a4-96fa-f01303f67bfa.png">

Hence, confirming the issue.

Thanks

**Comment by rogerdz** [comment]
@magento I am working on this

**Comment by rogerdz** [comment]
@magento add to contributors team

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6744 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6744&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by mohitnavik** [comment]
I have an issue related to this and popup was not closing after clicking on the close button. So, I have updated script on the following file:

vendor/magento/module-checkout/view/frontend/web/js/action/update-shopping-cart.js
![Desktop screenshot (2)](https://user-images.githubusercontent.com/41897612/203995271-138ad403-301c-4caf-be0f-790a29693b1f.png)

May be It helps someone
