### ISSUE TITLE
cron:run gives an error message

### ISSUE THREAD

**Issue by stradd** [magento/magento2#36194]
### Preconditions and environment

CE 2.4.5

### Steps to reproduce

Install 2.4.5
setup:di:compile

### Expected result

Ran jobs by schedule.

### Actual result

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in magento/generated/metadata/global.php on line 8

### Additional information

memory_limit=-1 is set in php.ini
All other cronjobs on my server run perfectly
all mgento cli comandos setup:di:compile setup:static-content:deploy etc also run without errors.
If you delete the file global.php in generated/metadata, the cron runs without errors

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stradd** [comment]
One more addition
The cronjob will not be executed as long as the global.php is present. If you delete them, the command php bin/magento cron:remove must first be executed and then the cronjob must be reinstalled with php bin/magento cron:install --force before the cronjob works again.

**Comment by engcom-Lima** [comment]
Hi @stradd ,

Thanks for your contribution and collaboration.

It is recommended to use 2G as given in [document](https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/hardware.html#memory).
Kindly change memory limit as per our document. If you facing any issue let us know.

Thanks

**Comment by hostep** [comment]
134217728 bytes is 128 MB (134217728 / 1024 / 1024), so something is overwriting your memory_limit to 128 MB instead of 2 GB or -1. You're going to need to figure out what exactly is doing this.

**Comment by stradd** [comment]
Since I only downloaded and installed version 2.4.5 and the problem only occurs if the /generated/global.php file exists, I assumed that the problem was caused by an error in Magento itself. So I reported the bug. All other memory-intensive commands such as setup:di:compile also run perfectly. phpinfo() also confirms the memory limit of 2G.
Would you agree that the issue is with Magento?

**Comment by engcom-Lima** [comment]
Dear @stradd ,

Thanks for your contribution and collaboration.

Kindly provide us exact steps inorder to reproduce the issue as issue is not reproducible to me.

Thanks

**Comment by hostep** [comment]
> Would you agree that the issue is with Magento?

Not yet no, I agree with @engcom-Lima that we need more information. You'll need to prove somehow with a clean installation of Magento that you can trigger this problem.

But if I have to guess: some custom code is probably going to set a memory_limit to 128 MB in your instance for some reason, and it's being triggered by running the cronjobs.

Maybe try searching your custom code for it, maybe this command can tell you which file is responsible for it (no guarantees that it will find what you are looking for, but maybe it will ...):

```
find app vendor generated ! -path 'vendor/magento/*' ! -path 'vendor/tubalmartin/*' ! -path 'vendor/codeception/*' ! -path 'vendor/php-amqplib/*' ! -path 'vendor/composer/*' ! -path 'vendor/dealerdirect/*' ! -path 'vendor/rector/*' ! -path 'vendor/pdepend/*' ! -path 'vendor/monolog/*' ! -path 'vendor/symfony/*' -type f \( -iname '*.php' -or -iname '*.phtml' \) -exec grep -il 'memory_limit' {} \;
```

This is all just guessing, again: if you are convinced that this is a bug in Magento, you'll need to prove it somehow.

**Comment by hostep** [comment]
Okay, then it's an environment problem you are having somehow. As [mentioned before](https://github.com/magento/magento2/issues/36194#issuecomment-1261347927), there must be "something" that sets the memory_limit to 128 MB. Try finding what it is and figure out if you can fix that. You mentioned `php.ini`, is that the file that's being used by your php-cli? You can find out with `php --ini`.

Also good to know: running `cron:run` spawns child php processes, so even if you specify the `memory_limit=1` on your commandline, that variable will probably not be moved over to the child processes.

**Comment by stradd** [comment]
Thank you so much for your help.
That was the key clue.
in /opt/plesk/php/8.1/etc/php.ini the memory_limit was set to 128MB. I changed that to 2G and the cron runs again without errors.
