### ISSUE TITLE
Customer attribute and customer address attribute alway require when select 'Use Default' in config

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36196]
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Go Admin - Stores - Configuration - Customers - Customer Configuration
2. Untick 'Use system value' and set value Required for Show Date of Birth, Show Tax/VAT Number, Show Gender, Show Telephone, Show Company, Show Fax
3. Save config
4. Reindex and flush cache
5. Go edit 1 customer, the fields above are all required 
6. Go Admin - Stores - Configuration - Customers - Customer Configuration
7. Tick 'Use system value' for Show Date of Birth, Show Tax/VAT Number, Show Gender, Show Telephone, Show Company, Show Fax
8. Save config
9. Reindex and clear cache
10. Go edit 1 customer, the fields above are still required

### Expected result

Field  Date of Birth, Tax/VAT Number, Gender, Telephone, Company, Fax must display required based on default configuration value
![2022-09-25_21-37](https://user-images.githubusercontent.com/78783748/192149426-4884f529-3d5e-4263-857d-b9c398f5d994.png)

### Actual result

Field  Date of Birth, Tax/VAT Number, Gender, Telephone, Company, Fax still required

![2022-09-25_23-01](https://user-images.githubusercontent.com/78783748/192153210-62ceb0a9-d275-4f8e-8871-6b6284799858.png)
![2022-09-25_23-01_1](https://user-images.githubusercontent.com/78783748/192153214-d004f31a-fbeb-409a-886c-60cc6c0d701b.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello,

As per the process, all the issues have been confirmed by the Engcom team member. So @engcom-November, I request you to please go through with it and try to reproduce the issue.

Thanks

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.
![image](https://user-images.githubusercontent.com/60198231/192941102-eea45bfd-3ae1-4ca7-8de4-0cdb5d32d725.png)

**Comment by markshust** [comment]
I believe this bug also affects the checkout, as disabling the Company field using `config.xml` always previously also hid this field from checkout:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <customer>
            <address>
                <company_show>false</company_show>
...
```

<img width="737" alt="Screenshot 2022-12-26 at 11 10 45 AM" src="https://user-images.githubusercontent.com/437029/209566567-263675ad-f097-4764-8d26-7378ed55b0d8.png">
