### ISSUE TITLE
Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/vendor/magento/framework/DataObject.php on line 131

### ISSUE THREAD

**Issue by bmxmale** [magento/magento2#36192]
### Preconditions and environment

- CE 2.4.4
- PHP8.1

### Steps to reproduce

Issue related with #35602, same steps, desc copied from related issue.

Enable product alert stock in BO (Configuration > Catalog >Product Alerts > Allow Alert When Product Comes Back in Stock > Yes, Allow Alert When Product Price Changes - Yes)
Reindex and cache flush
Front end - Login as customer - Select a Product without stock - Register to a product stock alert
(Notify me when the price drops, Notify me when this product is in stock)
Add stock to that product from admin
Launch consumers

### Expected result

Alert stock email being sent

### Actual result

Emails not triggered for Product Alerts

If we have configured error email, we will receive error:

```
Product alerts cron warnings

Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/vendor/magento/framework/DataObject.php on line 131```
```
Changes from https://github.com/magento/magento2/commit/0e9b5434ea89792bae7118894ce0a412e08b2cd7 on `DataObject` not helping.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @bmxmale  ,
Thank you for reporting and collaboration. Product Alert emails are not getting triggered on Magento 2.4-develop instance is an ongoing issue confirmed https://github.com/magento/magento2/issues/35602. We are closing this issue as duplicate. Kindly move on to this https://github.com/magento/magento2/issues/35602 for latest updates / solutions on the same.
Thank you.
