### ISSUE TITLE
Multiple Store views - Admin - Category page - Sorting by Product Name issue

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#36208]
### Preconditions and environment

2.4-develop
Multi store setup
Create categories and assign products
### Steps to reproduce
1. Create Products >=12 and save
1. Change scope to "Default Store View" - Change Product Names and save
1. Change scope to other website ex: "france" - Change Product Names and save
Product Names should be different for all store views.
1. Verify Admin - Catalog - Categories - Products in Category - No issue. Product Names displayed as expected
1. Sort by Product Name - Issue: Product Names got changed to default store view Product Names

### Expected result

Product Names should be "All Store views" names after sorting
!https://user-images.githubusercontent.com/60198231/192687041-5b9bfbdb-9f67-48f9-98e6-d23757cdc855.png|width=892,height=411!
### Actual result

!https://user-images.githubusercontent.com/60198231/192687001-a875ffd9-ace2-4e3a-8fe4-1c9d55badf7a.png|width=890,height=439!
### Additional information

*No response*
### Release note

*No response*
### Triage and priority
 - < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by hostep** [comment]
@engcom-Hotel: what was the reason for closing this? Please always specify a reason when closing issues in the future, otherwise it's confusing the people who watch the ticket?
The [PR](https://github.com/magento/magento2/pull/36216) that is supposed to fix this is still open, so that can't be the reason?

/cc @sdzhepa

**Comment by engcom-Bravo** [comment]
Hello,


The internal team will deliver this fix along with automated test coverage for the same in accordance with the Definition of Done.


Thanks.
