### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by db879** [magento/magento2#36204]
### Preconditions and environment

- Magento version 2.4.1-p1
- entered search field and the system produced the error: Something went wrong with processing the default view and we have restored the filter to its original state. The page is now stuck on loading. 

### Steps to reproduce

1. navigated to sales
2. clicked in search tab, entered a name

### Expected result

search would have come up with results or no results

### Actual result

System came with error message: Something went wrong with processing the default view and we have restored the filter to its original state.
Stuck on loading 

### Additional information

Tried to log out and clear browsing cashe however this did not work. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by daiduongvo18** [comment]
Hi @db879 
Is this issue fixed?

**Comment by FadedOut** [comment]
Not sure if this could help or not (worth a shot trying) but a member found a possible solution here:

https://github.com/magento/magento2/issues/35759

The location of the error is different (adding children products to a parent product) but the actual error is the same (problem with the grid loading). I wonder if this could help be the solution to many of you having this same grid loading issue.
