### ISSUE TITLE
Order download issue through rest API

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#36213]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. download orders through this API : rest/V1/orders?searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=ASC&searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2022-09-27 00:00:00&searchCriteria[filter_groups][0][filters][0][condition_type]=gt&searchCriteria[page_size]=250&searchCriteria[current_page]=1
2. API giving error : "Internal Error. Details are available in the Magento log file. Report ID: webapi-6333f157bfbb8"
3. This is occurring for specific timestamp  between the 2022-09-26 15:20:34 and 2022-09-26 15:28:00 time frame. Although we have downloaded the data after 2022-09-26 15:28:00

### Expected result

Orders should get downloaded with all timestamp.

### Actual result

API giving error : "Internal Error. Details are available in the Magento log file. Report ID: webapi-6333f157bfbb8"
This is occurring for specific timestamp  between the 2022-09-26 15:20:34 and 2022-09-26 15:28:00 time frame. Although we have downloaded the data after 2022-09-26 15:28:00

### Additional information

Below are the request and response

Request API url: https://www.offroaddesign.com//rest/V1/orders?searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=ASC&searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2022-09-26 15:20:34&searchCriteria[filter_groups][0][filters][0][condition_type]=gt&searchCriteria[page_size]=250&searchCriteria[current_page]=1

Response: 

{
    "message": "Internal Error. Details are available in the Magento log file. Report ID: webapi-6333f157bfbb8"
}

AccessToken: b8x86ce7qrv80rlsmz8z4e13c4xv3xw4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @webgility-amazonapi ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but issue is not reproducible to me . Please clear cache and try to test it in latest 2.4-develop.
Kindly provide more information inorder to reproduce the issue.

Thanks

**Comment by engcom-Lima** [comment]
Hi @webgility-amazonapi ,

Thanks for your contribution and collaboration.

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
