### ISSUE TITLE
C# - magento 2.0.2 - service reference namespace problem

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#3621]
Hi guys,

more details here
[https://forums.asp.net/t/2085117.aspx?SOAP+Envelop+change+namespace](https://forums.asp.net/t/2085117.aspx?SOAP+Envelop+change+namespace)

I'm trying to write a wrapper for magento 2,

at the moment im encountering an issue with the soap request & response,

i have setup 2 different sites for testing purposes (magento2 & magento2_data)

after i generated the service reference when pointing to 1 of the sites, i could successfully login and get a token

but when i change the endpoint in my app.config file, i run into an error

Message = "Server returned an invalid SOAP Fault.  Please see InnerException for more details."
which the message is
"Unbound prefix used in qualified name 'rpc:ProcedureNotPresent'."

i narrowed it down to the soap envelope namespace which contains the endpoint,

```
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<integrationAdminTokenServiceV1CreateAdminAccessTokenRequest xmlns="http://mylocal:8085/magento2/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1">
<username xmlns="">some-username</username>
<password xmlns="">some-password</password>
</integrationAdminTokenServiceV1CreateAdminAccessTokenRequest>
</s:Body>
</s:Envelope>
```

```
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<integrationAdminTokenServiceV1CreateAdminAccessTokenRequest xmlns="http://mylocal:8085/magento2_data/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1">
<username xmlns="">some-username</username>
<password xmlns="">some-password</password>
</integrationAdminTokenServiceV1CreateAdminAccessTokenRequest>
</s:Body>
</s:Envelope>
```

is there a way we make magento accept what ever the xmlns="http://mylocal:8085/magento2_data/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1" in the request object

further to my quest in finding a resolution, i managed to post to a difference endpoint by adjusting the xmlns:url in the request soap

but on the response soap it also contains the xmlns='url to which ever end point i posted the data to'
problem is when the code tries to deserialise in the service reference, it crashes

this is because the endpoint i used to add the service reference in my development project differs from the endpoint i am calling

perfect scenario of why this is important would be
1. build a backend windows service to pull data from multiple (differenct url) magento 2 sites
2. when development we add the service reference using a dev url
3. when deploying the soap endpoint url is changed dynamically according to a clients website
4. call the clients website url and pull data down (customer, orders, invoices...etc...)

so the question is could we remove the namespace generation in the reference.cs file when the magento 2 classes are generated when adding the wsdl as a service reference

eg... remove 

```
[System.Xml.Serialization.XmlTypeAttribute(Namespace=@"http://mylocal:8085/magento2_data/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1.....
[System.ServiceModel.MessageBodyMemberAttribute(Namespace=@"http://mylocal:8085/magento2_data/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1....
[System.ServiceModel.ServiceContractAttribute(Namespace=@"http://mylocal:8085/magento2_data/soap/default?services=integrationAdminTokenServiceV1%2CcustomerCustomerRepositoryV1.....
```

**Comment by MaximKitsenko** [comment]
I faced with the same problem! I will try to add crutch for it.

**Comment by manhao-chen** [comment]
the only way i got around the issue is that you will have to override the soap message AfterReceiveReply & BeforeSendRequest events
do a replacement of the namespace of the soap xml

**Comment by MaximKitsenko** [comment]
Thank you!
I was going to add crutches for those methods inside custom behavior. 

@katmoon 
In previous magento versions there were no namespaces in wsdl, but in magento 2.0.2 we have namespaces linked to urls, we used for testing / developing :
`<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://127.0.0.1:7777/magento-2-0-2-0-ce-2/soap/default?services=backendModuleServiceV1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="MagentoWSDL" targetNamespace="http://127.0.0.1:7777/magento-2-0-2-0-ce-2/soap/default?services=backendModuleServiceV1">
<types>
<xsd:schema targetNamespace="http://127.0.0.1:7777/magento-2-0-2-0-ce-2/soap/default?services=backendModuleServiceV1">`

**Comment by piotrekkaminski** [comment]
@mbrinton01  please look

**Comment by magento-engcom-team** [comment]
@manhao-chen  Closing this ticket for now due to inactivity and report itself not containing required information.
Please verify with up-to-date version and update report if you still believe that the issue exists.
