### ISSUE TITLE
Quality Patches Tool

### ISSUE THREAD

**Issue by in-session** [magento/magento2#36217]
### Preconditions and environment

I would like to ask a basic question regarding the Adobe Quality Patches. 

Why are these not included directly in some cases? 
For example, MDVA-12304 - Increases the maximum number of cookies from 50 to 200.

```
diff -Nuar a/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php b/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php
index 1f454518e43..b3dcc784917 100644
--- a/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php
+++ b/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php
@@ -29,7 +29,7 @@ class PhpCookieManager implements CookieManagerInterface
      * RFC 2109 - Page 15
      * http://www.ietf.org/rfc/rfc6265.txt
      */
-    const MAX_NUM_COOKIES = 50;
+    const MAX_NUM_COOKIES = 200;
     const MAX_COOKIE_SIZE = 4096;
     const EXPIRE_NOW_TIME = 1;
     const EXPIRE_AT_END_OF_SESSION_TIME = 0;

```

Doesn't it make sense to include this in the core with such a patch?
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php#L34

### Steps to reproduce

-

### Expected result

-

### Actual result

-

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @in-session ,

Thanks for yours contribution and collaboration.

As per this [document](https://support.magento.com/hc/en-us/articles/360025675051-MDVA-12304-503-error-on-store-front-and-cookie-error) Adobe Commerce default cookies limit is set to 50 and if the client's browser hits the limit, Commerce throws an exception. The solution provided in the patch increases the cookie limit to 200.

If you are facing any issue while installing patch or facing any issues kindly provide us information.

Thanks

**Comment by in-session** [comment]
Hi @engcom-Lima ,

Thanks for the feedback, then why aren't the cookies adjusted to 200 in the core right away?

**Comment by hostep** [comment]
Because having 200 cookies on one website is kind of ridiculous, no? Even 50 is already a lot.

As to why the patch exists and hasn't been merged, no idea, maybe the core devs feel te same that 200 is a bit extreme?

**Comment by engcom-Lima** [comment]
Hi @in-session ,

Thanks for your contribution and collaboration.

I have above [comment](https://github.com/magento/magento2/issues/36217#issuecomment-1278090878) clarifies your query. Shall I close this issue?

Thanks
