### ISSUE TITLE
calendar not excluding dates

### ISSUE THREAD

**Issue by mphx2** [magento/magento2#36223]
### Preconditions and environment

- Magento 2
If an item is already "rented out" it still shows dates available on the calendar that have already been selected. You only find out that item is not available when you click "Rent" button to add item to cart. Item does not get added to cart and all you can do is to keep choosing dates until one set of dates works. Need to be able to "grey out" the dates for which items are not available to avoid customer frustration.

### Steps to reproduce

Go to catalog
choose an item
choose dates on calendar 
Choose Rent

If item is already "rented" and therefore unavailable, it kicks you back without explanation of why item is not in cart

### Expected result

If I attempt to choose a date on the calendar, I should not be able to select dates for which the item has already been rented. 

### Actual result

Customers can select dates for items when they are not available, but when they select "Rent" to place item in cart, it just kicks back to product screen, with no explanation.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @mphx2 
Thank you for reporting and collaboration. However, Rental system is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market Place](https://marketplace.magento.com/extensions.html) page
Thank you.
