### ISSUE TITLE
Scoped EAV attribute value same for all websites

### ISSUE THREAD

**Issue by TheBadong** [magento/magento2#36225]
### Preconditions and environment

- Magento Commerce 2.4.4
- Php 8.1

### Steps to reproduce

Context : We have several websites and need to have multiple street lines on only one of them
Steps to reproduce :
1. Have a magento instance with two websites
2. Make sure the 'multiline count' of the default street attribute is set to 1
3. Add a line into customer_eav_attribute_website for another website (let's call it website B), and set its multiline_count to 2
4. Clean all caches
5. Login into a customer account on website A and try to add an address, there should be only 1 street line
6. Login into a customer account on website B and try to add an address, there should be 2 street lines, but there is only 1
7. Clean caches again
8. Refresh website B, there are now 2 street lines when trying to add an address
9. Go back to customer account on website A, there are now also 2 street lines.
10. Clean the cache again and refresh website A, there is now only 1 street line

### Expected result

We shouldn't have to clear the cache to get the correct attribute value across different websites

### Actual result

We have to clear the cache each time we change website to get the correct attribute value.

### Additional information

I've tried running xdebug through vendor/magento/module-customer/Model/Metadata/AttributeMetadataCache.php and files around it, and I can see the two different cache keys, but the value is always the same without clearing the cache.

The only solution I'm seeing right now is directly fetching the value from the database, but I'd like to not have to do that.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Lima** [comment]
Hi @TheBadong ,

Thanks for your contribution and collaboration.

i would like to inform you that in current magento **2.4-develop**  'multiline count' we can't give less than 2 as range given is **2-20**.
Please refer below screenshot for your reference:

<img width="1172" alt="Screenshot 2022-10-07 at 12 48 04 PM" src="https://user-images.githubusercontent.com/60198022/194495863-51a3d37a-a9fb-4f39-a432-5347804788fe.png">

Kindly provide more information about 2nd and 3rd steps provided by you. Also please try to test this it in `2.4-develop` Magneto.

Thanks

**Comment by TheBadong** [comment]
@magento give me 2.4-develop instance

**Comment by TheBadong** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by TheBadong** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by DnD-Nibra** [comment]
[@magento](https://github.com/magento) give me 2.4-develop instance
