### ISSUE TITLE
Symlink usage for extension development breaks *some* features

### ISSUE THREAD

**Issue by loneregister** [magento/magento2#3623]
If you use sylinks to "install" your magento2 development extensions (or I suppose production as well would exhibit this behavior) - you will discover that things like .phtml files for frontend templates will fail to load and execute.

This feature should be functional or at the very least, usable in a development environment.  Alan storm has an interesting "hack" that might be the solution.  This can be viewed here:

[http://magento.stackexchange.com/questions/93067/magento-2-work-around-for-loading-static-assets-from-symlinks/95268#95268](url)

**Comment by victor-shelepen** [comment]
Related issue: https://github.com/magento/magento2/issues/3612

**Comment by andimov** [comment]
@LoneRegister, thank you for reporting.
To allow us research the issue, please, provide description according to the template.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
