### ISSUE TITLE
Reindex customer indexer error when add more custom customer attributes

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#36233]
### Preconditions and environment

- Magento 2.4.5
- MySQL 8

### Steps to reproduce

1. Create new 3 varchar customer attributes with Use in Search Options is Yes
![image](https://user-images.githubusercontent.com/88669934/193730416-e6787956-20e3-47a1-8d8e-5c1cfd82178e.png)

2. Go to cli and run command: 
`bin/magento indexer:reindex customer_grid`

### Expected result

Reindex successfully

### Actual result

**Reindex error with MySQL message**

Customer Grid index process error during indexation process:
SQLSTATE[42000]: Syntax error or access violation: 1070 Too many key parts specified; max 16 parts allowed, query was: CREATE TABLE IF NOT EXISTS `customer_grid_flat` (
  `entity_id` int UNSIGNED NOT NULL COMMENT 'Entity ID' ,
  `name` text NULL COMMENT 'Name' ,
  `email` varchar(255) NULL COMMENT 'Email' ,
  `group_id` int NULL COMMENT 'Group_id' ,
  `created_at` timestamp NULL default NULL COMMENT 'Created_at' ,
  `website_id` int NULL COMMENT 'Website_id' ,
  `confirmation` varchar(255) NULL COMMENT 'Confirmation' ,
  `created_in` text NULL COMMENT 'Created_in' ,
  `dob` date NULL COMMENT 'Dob' ,
  `gender` int NULL COMMENT 'Gender' ,
  `taxvat` varchar(255) NULL COMMENT 'Taxvat' ,
  `lock_expires` timestamp NULL default NULL COMMENT 'Lock_expires' ,
  `test_1` int NULL COMMENT 'Test_1' ,
  `test_12` int NULL COMMENT 'Test_12' ,
  `test_123` int NULL COMMENT 'Test_123' ,
  `test_1234` int NULL COMMENT 'Test_1234' ,
  `test_12345` int NULL COMMENT 'Test_12345' ,
  `test_123456` int NULL COMMENT 'Test_123456' ,
  `test_t1` varchar(255) NULL COMMENT 'Test_t1' ,
  `test_t12` varchar(255) NULL COMMENT 'Test_t12' ,
  `test_t123` varchar(255) NULL COMMENT 'Test_t123' ,
  `shipping_full` text NULL COMMENT 'Shipping_full' ,
  `billing_full` text NULL COMMENT 'Billing_full' ,
  `billing_firstname` varchar(255) NULL COMMENT 'Billing_firstname' ,
  `billing_lastname` varchar(255) NULL COMMENT 'Billing_lastname' ,
  `billing_telephone` varchar(255) NULL COMMENT 'Billing_telephone' ,
  `billing_postcode` varchar(255) NULL COMMENT 'Billing_postcode' ,
  `billing_country_id` varchar(255) NULL COMMENT 'Billing_country_id' ,
  `billing_region` varchar(255) NULL COMMENT 'Billing_region' ,
  `billing_region_id` int NULL COMMENT 'Billing_region_id' ,
  `billing_street` varchar(255) NULL COMMENT 'Billing_street' ,
  `billing_city` varchar(255) NULL COMMENT 'Billing_city' ,
  `billing_fax` varchar(255) NULL COMMENT 'Billing_fax' ,
  `billing_vat_id` varchar(255) NULL COMMENT 'Billing_vat_id' ,
  `billing_company` varchar(255) NULL COMMENT 'Billing_company' ,
  PRIMARY KEY (`entity_id`),
  INDEX `CUSTOMER_GRID_FLAT_GROUP_ID` (`group_id`),
  INDEX `CUSTOMER_GRID_FLAT_CREATED_AT` (`created_at`),
  INDEX `CUSTOMER_GRID_FLAT_WEBSITE_ID` (`website_id`),
  INDEX `CUSTOMER_GRID_FLAT_CONFIRMATION` (`confirmation`),
  INDEX `CUSTOMER_GRID_FLAT_DOB` (`dob`),
  INDEX `CUSTOMER_GRID_FLAT_GENDER` (`gender`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_1` (`test_1`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_12` (`test_12`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_123` (`test_123`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_1234` (`test_1234`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_12345` (`test_12345`),
  INDEX `CUSTOMER_GRID_FLAT_TEST_123456` (`test_123456`),
  INDEX `CUSTOMER_GRID_FLAT_BILLING_COUNTRY_ID` (`billing_country_id`),
  FULLTEXT `FTI_059BA2EF3C88ED0DA4E84A263AEFD399` (`name`, `email`, `created_in`, `taxvat`, `test_t1`, `test_t12`, `test_t123`, `shipping_full`, `billing_full`, `billing_firstname`, `billing_lastname`, `billing_telephone`, `billing_postcode`, `billing_region`, `billing_city`, `billing_fax`, `billing_company`)
) COMMENT='customer_grid_flat' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Lima** [comment]
@magento give me 2.4.5 instance with edition ee

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **`2.4-develop`** & **`2.4.5`** branch.

**Description:**
Getting sql state error while running indexer.

**Pre-requisite:**
Fresh magento `2.4-develop`  and `2.4.5` should be installed.

**Steps to reproduce:**
Followed  configuration done in screenshot.
Ran the indexer using command : 
`bin/magento indexer:reindex customer_grid`

**Expected result:**  
Reindex successfully

**Actual result:** 
Getting SQL state error.

**Screenshots:**
While running indexer command:

<img width="1498" alt="Screenshot 2022-10-04 at 5 51 32 PM" src="https://user-images.githubusercontent.com/60198022/193841303-ff15142e-f910-4f94-8705-b49b4198d953.png">

In system log:
<img width="1496" alt="Screenshot 2022-10-04 at 5 52 10 PM" src="https://user-images.githubusercontent.com/60198022/193841427-c92a3664-8d23-4d43-b77c-42c78a49f29d.png">

**Comment by engcom-Bravo** [comment]
Hi @manhtranisobar,

We got confirmation from internal team.

During customer_grid indexing, magento creates a table customer_grid_flat and apply the FULLTEXT indexes to the TEXT, VARCHAR, CHAR columns. On a clean instance of magento 2.4-develop, the default full text indexes present are as below,


<img width="1052" alt="image-2023-05-09-15-36-55-342" src="https://github.com/magento/magento2/assets/51680745/7b1afeaf-e2e4-4f42-b67c-5ac335c132ab">



Total Count being 14.
So if we try to add 2 other customer customer attribute whose data type is CHAR, VARCHAR or TEXT and with is_used_in_grid & is_searchable_in_grid to 1.

It will also be added to the list of full text indexes as in below,

<img width="1076" alt="image-2023-05-09-15-46-43-550" src="https://github.com/magento/magento2/assets/51680745/0683fd4c-e463-4fea-879c-10715e4e6c5a">


now the total count being 16. If we try to add another text attribute with is_used_in_grid & is_searchable_in_grid to 1.

Then on reindexing the following sql error is thrown.


<img width="924" alt="image-2023-05-09-15-49-19-793" src="https://github.com/magento/magento2/assets/51680745/d8e97fd3-4e17-44fc-902f-1a6045a172c1">



The reason being a mysql limitation.


<img width="997" alt="image-2023-05-09-15-56-03-430" src="https://github.com/magento/magento2/assets/51680745/9172fbcc-9f7f-4da0-a1cf-defad5f78ff6">


Hence we wont be able to have more than 16 customer attributes which are text fields with  is_used_in_grid & is_searchable_in_grid to 1 .
So if we need to add more custom customer text attribute with is_used_in_grid & is_searchable_in_grid to 1 it isn't possible unless we change some existing customer attribute's is_used_in_grid & is_searchable_in_grid value to 0.And as a workaround we can suggest to customize the grid indexer and remove the fields from indexer which customers do not want to use (e.g.: billing address fields).


Thanks.

**Comment by manhtranisobar** [comment]
Hi @engcom-Bravo 
Yes, I understand. So we may need a custom validation to prevent admin user add more attributes to searchable list.
