### ISSUE TITLE
Magento 2.4.5 How to hide duplicate pictures when the product color is switched

### ISSUE THREAD

**Issue by AngeloZou** [magento/magento2#36243]
Hi, I used to seek workarounds for magento 2.4.2 on the stackexchange that fixed this issue, but when I upgraded to magento 2.4.5, those workarounds were outdated because magento had a major upgrade.

How can I re-solve this problem, thank you all.

https://i.stack.imgur.com/dnUeW.png
https://i.stack.imgur.com/jXTtz.png
https://i.stack.imgur.com/VQclz.png

### Steps to reproduce (*)
1. Install Magento 2
2. Install Sample Data bin/magento sampledata:deploy
3. Run setup:upgrade and set deploy mode to production.
4. Go to configurable product for example: /breathe-easy-tank.html
5. Default images are shown
6. Select color swatch
7. Default images are shown and color images are shown, which are duplicates.

### Actual result (*)
Duplicate images are shown

### Expected Result: (*)
No duplicate images are shown

**Comment by jankovandeventer** [comment]
Hello,

I am experiencing the same issue with a configurable product from the sample data.
Magento 2.4.5 Open Source with Sample Data

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence updating description and confirming the issue.

**Comment by AngeloZou** [comment]
Can the problem be solved, if so, please let me know how. Thank you!

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance
