### ISSUE TITLE
docs(graphql): ConfigurableProductOptions.use_default is documented incorrectly

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#36246]
### Summary (*)

As a developer, I was reviewing the documentation for `ConfigurableProductOptions` in GraphQl and I noticed: 

### Examples (*)

```gql
type ConfigurableProductOptions @doc(description: "Defines configurable attributes for the specified product.") {
    id: Int @deprecated(reason: "Use `uid` instead.") @doc(description: "The configurable option ID number assigned by the system.")
    uid: ID! @doc(description: "The unique ID for a `ConfigurableProductOptions` object.")
    attribute_id: String @deprecated(reason: "Use `attribute_uid` instead.") @doc(description: "The ID assigned to the attribute.")
    attribute_id_v2: Int @deprecated(reason: "Use `attribute_uid` instead.") @doc(description: "The ID assigned to the attribute.")
    attribute_uid: ID! @doc(description: "The unique ID for an `Attribute` object.")
    attribute_code: String @doc(description: "A string that identifies the attribute.")
    label: String @doc(description: "A string that describes the configurable product option, which is displayed on the storefront.")
    position: Int @doc(description: "A number that indicates the order in which the attribute is displayed.")
    use_default: Boolean @doc(description: "Indicates whether the option is the default.")
    values: [ConfigurableProductOptionsValues] @doc(description: "An array that defines the `value_index` codes assigned to the configurable product.")
    product_id: Int @deprecated(reason: "`product_id` is not needed and can be obtained from its parent.") @doc(description: "This is the same as a product's `id` field.")
}
```

Specifically,

```gql
 use_default: Boolean @doc(description: "Indicates whether the option is the default.")
```

This doc is incorrect.

### Proposed solution
Change the doc to read more similarly to `ConfigurableProductOptionsValues.use_default_value` (the real purpose of the node).

```
use_default_value: Boolean @doc(description: "Indicates whether to use the default_label.")
```

As that's the actual purpose of the flag.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

cc: @keharper @cpartica @nrkapoor (in @cpartica 's absence)

Additionally, these flags are completely pointless in the schema, why are we exposing non-store-scoped labels to the client?

**Comment by engcom-November** [comment]
Hi @damienwebdev ,
Thank you for reporting and collaboration. Can you please provide more specific details about the incorrect documentation: of "use_default" here. 
Currently "use_default" returns whether the configurable option can be used as default or not and "use_default_value" returns whether values of the option can be used as default or not. Please refer the screenshot of the same
![image](https://user-images.githubusercontent.com/60198231/194290458-dcb73678-9737-4b8b-8723-1118373cb6a4.png) This is an existing behavior of Magento. If this needs to be changed please provide to what exact text of "use_default" in documentation should be changed.
Thank you.

**Comment by damienwebdev** [comment]
> Currently "use_default" returns whether the configurable option can be used as default or not and "use_default_value" returns whether values of the option can be used as default or not. 

Can you explain exactly (perhaps with examples) what:

> whether the configurable option can be used as default or not

Means?

**Comment by keharper** [comment]
@engcom-November This issue is asking for clarification of the description of a field in the GraphQL codebase. The description should be updated in the codebase. Just opening a [docs issue](https://github.com/magento/devdocs/issues/9526) is not the correct thing to do.
