### ISSUE TITLE
Custom Import - Not allowed to set "allowed error count" to 0

### ISSUE THREAD

**Issue by asim-blueprintprep** [magento/magento2#36252]
### Preconditions and environment

- Magento 2.4.2-p2
- PHP7.4

### Steps to reproduce

1. Navigate to admin
2. system -> import
3. pick any from dropdown
4. try to set allowed error count to 0
5. validation says you need to enter a number greater than 0
![Screenshot 2022-10-06 at 16 00 04](https://user-images.githubusercontent.com/85678471/194499095-52811096-e0f4-4eb6-b7a9-362c91c5a1ed.png)

### Expected result

0 is an accepted value for allowed error count.
Within the code base:

vendor/magento/module-import-export/Model/Import/ErrorProcessing/ProcessingErrorAggregator.php
`public function initValidationStrategy($validationStrategy, $allowedErrorCount = 0)
    {`

The default value for allowed error count is 0, but it is being forced higher due to admin frontend validation

### Actual result

Have to enter a value greater than 0. To work around this issue, entering 0.0001 works, as it is technically greater than 0, and the code type casts it to int, where it is rounded to 0.

### Additional information

I have submitted a PR to fix this https://github.com/magento/magento2/pull/36253

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by asim-blueprintprep** [comment]
@magento give me 2.4-develop instance

**Comment by asim-blueprintprep** [comment]
I can confirm this bug exists in vanilla

**Comment by asim-blueprintprep** [comment]
@magento I am working on this

**Comment by asim-blueprintprep** [comment]
@magento add to contributors team

**Comment by asim-blueprintprep** [comment]
@magento I am working on this

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Custom Import - Not allowed to set "allowed error count" to 0

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Navigate to admin
2. System -> import
3. Pick any from dropdown
4. Try to set `Allowed error count` to 0
5. Validation says you need to enter a number greater than 0

**Expected result:**  Zero should be accepted in Allowed error count.
**Actual result:** It is not allowing zero.
**Screenshots:**
<img width="1098" alt="Screenshot 2022-10-07 at 2 57 17 PM" src="https://user-images.githubusercontent.com/60198022/194524575-3ab1de8b-6c8f-44ed-91b4-4b097d872946.png">

Hence, confirming the issue.

**Comment by asim-blueprintprep** [comment]
@engcom-Lima I have fixed this issue in my PR, does it need anything else?

**Comment by asim-blueprintprep** [comment]
@engcom-Lima as the merge request has been merged, what's the best way to close this ticket?
