### ISSUE TITLE
Custom Layout Update (i.e. "selectable layouts") Stopped Working on v2.4.5

### ISSUE THREAD

**Issue by schizek** [magento/magento2#36250]
### Preconditions and environment

- Magento version: 2.4.5
- Trying to add [Custom Layout Updates (selectable layouts)](https://developer.adobe.com/commerce/frontend-core/guide/layouts/xml-manage/#create-selectable-layouts) no longer works as of v2.4.5 (tested and works in 2.4.4 and 2.4.3 as expected)

### Steps to reproduce

1. Setup vanilla install of Magento Open Source or Adobe Commerce 2.4.5 with sample data
2. Add the following file with an XML change... `app/design/frontend/<Namespace>/<theme>/Magento_Catalog/catalog_product_view_selectable_24-MB01_puppies.xml`
3. Clear the cache
4. Log into the admin and to go Catalog > Products and edit the product with SKU "24-MB01"
5. Expand the "Design" section and open the "Custom Layout Update" select field
6. Note that the dropdown just has "no update" instead of an additional "puppies" option

### Expected result

On product edit page "Design" section, the Custom Layout Update should have two options, "no update" and "puppies"

On version 2.4.4...
<img width="356" alt="Screen Shot 2022-10-06 at 10 12 26 AM" src="https://user-images.githubusercontent.com/5023509/194350634-29ad4f1e-4949-41a2-94b6-4607a6ce559c.png">

### Actual result

On product edit page "Design" section, the Custom Layout Update doesn't populate any additional options other than "no update"

On version 2.4.5...
<img width="361" alt="Screen Shot 2022-10-06 at 10 11 32 AM" src="https://user-images.githubusercontent.com/5023509/194350516-6d6bfe92-1590-46bb-998d-66640222139c.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @schizek,

Thanks for the contribution and collaboration!

I have a question here, have you activated the theme from the below path where you keep this file `app/design/frontend/<Namespace>/<theme>/Magento_Catalog/catalog_product_view_selectable_24-MB01_puppies.xml
`:
```
Admin Panel -> Content -> Design -> Configuration
```

Thanks

**Comment by schizek** [comment]
Yes I do have that theme activated.  I found the cause of my issue, however, for some reason that theme was set to a virtual theme so I updated that in the DB, cleared the cache and pub/static and it is now working as expected.  Whoops.  Sorry for the trouble!

```UPDATE `theme` SET `type` = 0 WHERE `theme_path` = 'FetchDesigns/base';```

`bin/magento c:c && rm -rf pub/static/*`
