### ISSUE TITLE
Multiwebsite with subfolder

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#3626]
Hi,

Its possible to setup magento 2 with multiwebsite and subfolder, like this :
http://magento-shop.com/test1 and http://magento-shop.com/test2

Any ideas ?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
