### ISSUE TITLE
Braintree payment sends incorrect currency on a authorized expired order

### ISSUE THREAD

**Issue by AdrianChungie** [magento/magento2#36264]
### Preconditions and environment

This issue happened in a production environment

- Magento version 2.4.2
- Using built in braintree extension, and no custom code on the payment side
- I am using a multi store setup with two sites, one for USD products and one for CAD products. CAD being the default store.
- Therefore, two currency merchants on braintree side as well. One for USD and one for CAD

### Steps to reproduce

To reproduce:
1. Order on the USD store and checkout via credit card using braintree. In this case lets use $100 USD
2. The payment transaction on braintree side will be in Authorized status for the $100 USD.
3. Let this expire on purpose, usually it takes 7-10 days to expire. Not sure if the braintree sandbox would allow you to switch it to Authorized expired immediate or you have to wait the 7-10 days.
4. Go to the Sales->Orders on the Magento 2 backend and go to the $100 USD order.
5. Try to invoice the order and this will make another API call to Braintree because the payment was expired. However it will not set the USD merchant in the API call. Instead it will use the default merchant which is CAD.
6. This will cause the new braintree transaction to be $100 **CAD** instead of $100 **USD**

### Expected result

I expected the Submit Invoice on the Magento 2 Order to send the USD Braintree merchant

### Actual result

It sent the default Braintree merchant, which is CAD.

### Additional information

I have the braintree extension setup correctly. All the orders have been processed correctly for USD and CAD. However, there is a bug when a order payment is "Aurthorized Expired" on braintree, and you try to Invoice it on Magento 2. It will see that it is expired, and make a new payment, but in the wrong currency.

This cause a order to be charged in the wrong currency on our production site.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by AdrianChungie** [comment]
> Hi @AdrianChungie ,
> 
> We are working with this issue magento 2.4-develop instance...Currently we are placing the order with simple product with USD currency and The payment transaction on braintree side is Authorized status ...As per your instructions we need wait for few days and we need to verify the issue once the Authorized status expired.
> 
> Screenshots: <img alt="Screenshot 2022-10-20 at 3 20 07 PM" width="1512" src="https://user-images.githubusercontent.com/60198592/196917568-2cbc9f40-f0b7-4b0f-8a69-e8c30109b84c.png">
> 
> Let us know if we missing anyhting!!!
> 
> Thanks!!! <img alt="Screenshot 2022-10-20 at 3 20 39 PM" width="1512" src="https://user-images.githubusercontent.com/60198592/196917609-29a5aab9-a864-4a85-a2b7-555f4188de2f.png">

ok great thanks so much for looking into this. Just checking did you setup that magento instance to be multi site?

This is how we have our magento sites setup:
![firefox_N4G7a1zerA](https://user-images.githubusercontent.com/1384964/196966841-d67638a7-bc3f-4e96-9fb8-da901afe294f.png)

**Comment by engcom-Dash** [comment]
Hi @AdrianChungie ,

Thanks for your information...I done the multi website setup as per you instructions.

Here i attached the screenshot for your reference:

<img width="1512" alt="Screenshot 2022-10-21 at 2 19 55 PM" src="https://user-images.githubusercontent.com/60198592/197154693-f336f2f2-68ca-4cec-bcc1-8550e2bd7773.png">

Let us know if we missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @AdrianChungie ,

Thanks For your collaboration!

 I placed order on the USD store and checkout via credit card using braintree. I used $100 USD Product…and I waited 10 days as per your instructions and the product in merchant account is expired.Again I created invoice using the expired Product…It will send the USD Braintree merchant in Sandbox Account….For your Reference I attached the screenshots Kindly refer it:
<img width="1512" alt="Screenshot 2022-11-02 at 10 21 48 AM" src="https://user-images.githubusercontent.com/60198592/199402769-291d7e15-53d2-4b96-ac6f-72e4beefc897.png">
<img width="1512" alt="Screenshot 2022-11-02 at 10 24 10 AM" src="https://user-images.githubusercontent.com/60198592/199402779-41bfcdc8-af24-4519-9eec-5aa1fd585139.png">
<img width="1512" alt="Screenshot 2022-11-02 at 10 26 30 AM" src="https://user-images.githubusercontent.com/60198592/199402782-3140d94c-99c9-415a-b1e5-78ff246b8c38.png">

Let us know if we missing anything!!!

Thanks!!!

**Comment by AdrianChungie** [comment]
> Hi @AdrianChungie ,
> 
> Thanks For your collaboration!
> 
> I placed order on the USD store and checkout via credit card using braintree. I used $100 USD Product…and I waited 10 days as per your instructions and the product in merchant account is expired.Again I created invoice using the expired Product…It will send the USD Braintree merchant in Sandbox Account….For your Reference I attached the screenshots Kindly refer it: <img alt="Screenshot 2022-11-02 at 10 21 48 AM" width="1512" src="https://user-images.githubusercontent.com/60198592/199402769-291d7e15-53d2-4b96-ac6f-72e4beefc897.png"> <img alt="Screenshot 2022-11-02 at 10 24 10 AM" width="1512" src="https://user-images.githubusercontent.com/60198592/199402779-41bfcdc8-af24-4519-9eec-5aa1fd585139.png"> <img alt="Screenshot 2022-11-02 at 10 26 30 AM" width="1512" src="https://user-images.githubusercontent.com/60198592/199402782-3140d94c-99c9-415a-b1e5-78ff246b8c38.png">
> 
> Let us know if we missing anything!!!
> 
> Thanks!!!

Thanks for looking into this, I guess the problem is not easy to replicate. I will have to check again on my end why this may have happened. If it happens again I will try to get more details. You can go ahead and close this issue for now. Thanks!

**Comment by engcom-Dash** [comment]
Hi @AdrianChungie ,
 
Thanks for your Collaboration!!!

As per your instructions we are closing the issue Now.

Thanks!!!
