### ISSUE TITLE
Initialize the AccountManagementInterface with my own class problem

### ISSUE THREAD

**Issue by cs221313** [magento/magento2#3627]
Hi, all,

I got a problem when I Initialize the `AccountManagementInterface` with my own class. I have created my own `AccountManagement` which is extended from `\Magento\Customer\Model\AccountManagement`.

``` php
namespace AiMai\MyModule\Model;

class AccountManagement extends \Magento\Customer\Model\AccountManagement implements AccountManagementInterface
{
...
}
```

I defined following statement in `di.xml` file:

``` xml
\<preference for="Magento\Customer\Api\AccountManagementInterface"
                 type="AiMai\MyModule\Model\AccountManagement" />
```

But when I run the software, it still initialize the `Magento\Customer\Model\AccountManagement` class in the following code.

``` php
class ForgotPasswordPost extends \Magento\Customer\Controller\Account\ForgotPasswordPost
{
    public function __construct(Context $context, Session $customerSession, AccountManagementInterface $customerAccountManagement, Escaper $escaper)
    {
        parent::__construct($context, $customerSession, $customerAccountManagement, $escaper);
    }
...}
```

Thanks
- David

**Comment by slavvka** [comment]
Hi, have you cleared the cache?

**Comment by cs221313** [comment]
It's long time ago. I think I have solved this problem. But I can not remember how I solved it.

**Comment by slavvka** [comment]
Okay, thank you, feel free to reopen it if it occurs again.
