### ISSUE TITLE
Unify unit and integration tests configs

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#3628]
This isn't something big, but I think it may be worth to improve both `phpunit.xml.dist` files to make them working in similar way by default. For now the biggest difference is that integration tests don't include whole `app/code` but limit code coverage only to Magento code:

```
<directory suffix=".php">../../../app/code/Magento</directory>
```

Unit tests enable everything from `app/code` by default:

```
<directory suffix=".php">../../../app/code/*</directory>
```

Another improvements may include adding logging configuration example in integration tests and adjusting nodes order.

**Comment by Vinai** [comment]
During development I commonly only run the whole integration test suite by CI, so I like having individual testsuites for non-magento modules.

**Comment by wojtekn** [comment]
@Vinai when I work on custom module I run tests only for that module eg.:

```
phpunit -c phpunit.xml.dist ../../../app/code/Vendor/Module/Test/Integration
```

I found that issue when I wanted to review code coverage. For unit tests I copied `phpunit.xml.dist` to `phpunit.xml`, commented out `logging` nodes and that was it.

For integration I did the same and it didn't work - logging nodes are not there and default filter setup doesn't cover non-Magento code. 

I would expect similar experience for both test types.

**Comment by Vinai** [comment]
Collecting coverage data for integration tests isn't that common in my experience except for maybe identifying bigger uncovered areas. Integration tests are not really meant to cover all execution paths, they are generally too expensive to write and maintain. That's what unit tests are really good at.

**Comment by wojtekn** [comment]
@Vinai thanks, I understand your point, however it still may make sense to have these configs unified.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unify-unit-and-integration-tests-configs/idi-p/45300).
