### ISSUE TITLE
Catalog price rule is applied to product even after removing the rule

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#3630]
![price_rule_removed](https://cloud.githubusercontent.com/assets/17591809/13493376/c01e61d4-e163-11e5-891c-4b9ff6705f20.png)
![catalog_price_rule_still_applies](https://cloud.githubusercontent.com/assets/17591809/13493375/c01c5966-e163-11e5-80fc-8409ae475f24.png)

Steps to repro:
1.Go to Marketing>Catalo price rule
2. Create a price rule with fixed amount discount and with no condition applied
3.Load a product in frontend and ensure price rule is applied
4.Now remove the price rule
5.Load a product in frontend 
Observation:
Price rule is applied even after catalog price rule is removed

**Comment by Deepthi57** [comment]
Hi, can i get an update on this issue. Issue persists even in 2.0.2 version

**Comment by ruby10** [comment]
I am also facing this issue , is there any update on it?

**Comment by tudn9x** [comment]
Hi, just reindex to fix issue. Did you try check notification?
![screenshot_1](https://cloud.githubusercontent.com/assets/4941829/14775195/7451a8e4-0ae7-11e6-8a15-f97b3c3b7b4b.png)

**Comment by Deepthi57** [comment]
Hi,
I even reindex and tried clearing cache too. Still it dint work out

**Comment by ruby10** [comment]
@voleye , @MomotenkoNatalia  , any update on it?

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54588

**Comment by tkacheva** [comment]
@Deepthi57 please provide detailed steps to reproduce the issue with the reference on magento version you are using. I deleted rule, ran catalog re-index and discount is no longer available on storefront.

**Comment by Deepthi57** [comment]
Thanks for checking. I will install latest version and check

**Comment by piotrekkaminski** [comment]
We were not able to reproduce on 2.1.

**Comment by kuwalpinkesh** [comment]
i have still this problem. how can solve this problem
