### ISSUE TITLE
/pub/errors/.htaccess is not Apache 2.4 compliant

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#36317]
### Preconditions and environment

- 2.4-develop

### Steps to reproduce

https://github.com/magento/magento2/blob/49bd70677e2a65755b82ac81f5b561b01f14fce1/pub/errors/.htaccess#L2-L4

### Expected result

Deny call is not valid in Apache 2.4

See other .htaccess files for reference.
https://github.com/magento/magento2/blob/49bd70677e2a65755b82ac81f5b561b01f14fce1/pub/.htaccess#L207-L215

### Actual result

Deny call is wrapped in Version calls to allow both Apache < 2.4 and Apache >= 2.4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @gwharton , Thank you for reporting and collaboration.
Verified the behavior on Magento 2.4-develop instance and is reproducible. I believe here no IfVersion checks are required  as this is not version dependant configuration. In this case Deny call is still Apache 2.4 compliant. 
https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html. Kindly recheck and confirm if we are missing anything to consider this as valid issue.
Thank you.

**Comment by gwharton** [comment]
Right,

I see. 

Given all other .htaccess files in Magento use the IfVersion call I would have thought that this one should too, to avoid having the dependency on the mod_access_compat module, which isn't listed as a requirement.

I'm not gonna die in a ditch over it, as I'll just enable the module, but there seems to have been an effort in the other .htaccess files to not require the compat module.

**Comment by engcom-November** [comment]
Thank you for the response @gwharton. We are confirming this issue as there is inconsistency among .htaccess files. Behavior should be same among all .htaccess files.
mod_access_compat module is enabled by default in httpd.conf file and is not listed as a requirement and if no version check is made (Ex: pub/errors/.htaccess), .htaccess file require mod_access_compat.

**Comment by pedromtalavera** [comment]
Hi, 

I created a PR for this #37707
