### ISSUE TITLE
Magento creates two oauth tokens for the same oauth consumer

### ISSUE THREAD

**Issue by hmolinari-attentive** [magento/magento2#36326]
### Preconditions and environment

- Magento version

2.4.4 (Adobe Commerce on cloud infrastructure)

- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create an integration (Doesn't matter if manually created through admin or installed through a module), set the callback and identity-link URLs so that messages sent to them can be seen.
2. Authorize the integration so that the pop-up window shows up, aka the callback and identity-link messages are received.
- Notice that a verifier token has been created in the `oauth_token` table.
3. Using the callback and identity-link messages obtained, perform the steps to obtain a request token.
- Notice that the verifier token has been replaced with a new request token in the `oauth_token` table, which refers to the original verifier token in the `verifier` column.
4. Authorize the integration again, so that another set of callback and identity-link messages are received.
- Notice that a new verifier token has been created in the `oauth_token` table, with a different `verifier` string.  Now there are two tokens associated with the same consumer, one that is a verifier token, the other is a request token.
5. Using the new callback and identity-link messages obtained, perform the steps to obtain a request token.

### Expected result

Request Token and secret are obtained.

### Actual result

A 401 error is received, with body `oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token`

### Additional information

This is happening in step 5, the `module-integration` code queries the database for _the_ verifier token to replace with a related request token.  It assumes that only one token is present for the consumer, and it expects it to be a verifier token.  However, there are two tokens, and it's grabbing the request token currently in the table.  This is unexpected, and it throws the 401 error because of this.

The two tokens remain in the table.  An access token also cannot be created using the request token received in step 3.  The admin user can now no longer activate the integration through the admin panel, and the integration-owner cannot rectify it either.  The admin user has to go into the database and remove the tokens associated with that consumer before attempting to authorize the integration again.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @hmolinari-attentive,

Have you had a chance to look into this comment https://github.com/magento/magento2/issues/36326#issuecomment-1827734269? 

Thanks

**Comment by engcom-Hotel** [comment]
Dear @hmolinari-attentive,

We have noticed that this issue has not been updated for a period of a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
