### ISSUE TITLE
Shipment status and shipment label?

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3634]
I'm looking at the REST API and see that there is a `shipment_status` and `shippment_label` filed available. Than I created a shipment in the backend and noticed, that I'm not able to set these fileds.

For what are these fileds or where can I set these fileds?

**Comment by NadiyaS** [comment]
Hi @mc388 , 
Fix has been delivered to develop branch 23d12c9. 
You can upgrade your code from develop branch or wait until next release.
Issue is closed as resolved.

P. S.
the same problem was reported in #3895

**Comment by piotrekkaminski** [comment]
@mc388 magento.stackexchange.com is a better place for such questions. cc @mbrinton01

**Comment by ilnytskyi** [comment]
Seems like the column `shipment_status` is not in use;
And only mentioned in tests and here 
```
\Magento\Sales\Model\Order\Shipment::STATUS_NEW
```

```
\Magento\Sales\Model\Order\Shipment::getShipmentStatus
```

In 2020 it looks like it's not in use after `Temando\Shipping` was removed from the core.
May be it's ok to use it in own modules to customize the shipment flow.
