### ISSUE TITLE
Order PDF Shipment

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3635]
I'm logged in in the backend and view an order. I select the shipment tab, check the checkbox on a shipment and choose the `PDF Shipments` above the table. The generated PDF includes all available shipments and not only the selected one.

**Comment by NadiyaS** [comment]
Hi @mc388 , 
Fix has been delivered to develop branch 23d12c9. 
You can upgrade your code from develop branch or wait until next release.
Issue is closed as resolved.

P. S.
the same problem was reported in #3895
