### ISSUE TITLE
GraphQl product aggregations return category_id instead of category_uid

### ISSUE THREAD

**Issue by jponeill** [magento/magento2#36363]
### Preconditions and environment

- Magento version 2.4.5-p1
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

The following graphQl query returns the category_id instead of category_uid in the aggregation results.

{
  products(
    search: "b"    
  ) {
    aggregations {
                label
                count
                attribute_code
                options {
                    value
                }
                position
            }
    items  {
      categories {
        uid
        id
      }
  }
    }
}

returns results of where value = 9107 which is the category_id instead of the category_uid as shown below. 

{
  "data": {
    "products": {
      "aggregations": [
        {
          "label": "Category",
          "count": 1,
          "attribute_code": "category_uid",
          "options": [
            {
              "value": "9107"
            },
          ],
        },
      ],
      "items": [
        {
          "categories": [
            {
              "uid": "OTEwNw==",
              "id": 9107
            }
          ]
        }
      ]
    }
  }
}

 

### Expected result

category_uid returned as "value" instead of cateogry_id (entity_id)

### Actual result

cateogry_id (entity_id) returned as "value"

### Additional information

Looks like it's fixed in https://venia.magento.com/search.html?query=dress&page=1

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jponeill** [comment]
Checking to see if you need more information?

**Comment by Vasudev-22** [comment]
@magento give me 2.4.5-p1 instance

**Comment by Vasudev-22** [comment]
@magento give me 2.4-develop Instance.

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by Vasudev-22** [comment]
@magento add to contributors team

**Comment by Vasudev-22** [comment]
@magento Accepted .

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by Vasudev-22** [comment]
Hi @jponeill , 

Issue is reproducible in Magento 2.4.5-p1 Instance. 

<img width="862" alt="Magento2 4 5-p1" src="https://user-images.githubusercontent.com/104893739/201322164-25b7605d-1324-4588-885a-c002a48697e5.png">

Mentioned issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base, its fixed. 
So in Upcoming release magento has a fix for the above issue.

![Magento2 4 x](https://user-images.githubusercontent.com/104893739/201322448-a1053626-cbe1-4ed3-8686-416aaa6624a4.png)

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @jponeill ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
![image](https://user-images.githubusercontent.com/60198231/201369110-42416883-2d36-447e-9e5f-74e379b82ff6.png)

Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.

**Comment by jponeill** [comment]
It looks like  @Vasudev-22 reproduced the problem in 2.4.5-p1 (thanks!) and that it's fixed in 2.4-develop.
