### ISSUE TITLE
Swatches does not work properly into Catalogsearch

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#3637]
Steps to reproduce : 
- Pick an attribute based on swatches (ie. "color" on Magento with sample datas).
- Set "Use in Search Results Layered Navigation" to "Yes".
- Go to catalogsearch result page.

=> The swatches are appearing on the DOM, but, they are not displayed properly.

This may be due to the fact that there is no layout for catalogsearch_result_index in the swatches module.

**Comment by piotrekkaminski** [comment]
Closing in favor of PR #3638
