### ISSUE TITLE
Expired cart price rule gets applied when create/renew order from Backoffice

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#36382]
### Preconditions and environment

- Magento version 2.4.5-p1

### Steps to reproduce

1. Create a shopping cart rule : Active, without coupon, any discount, Discard subsequent rules = YES, active from = 2020-01-01, active to = 2020-02-01
2. Create another shopping cart rule : Active, with coupon 'TEST', any discount
3. From backend, reorder an existing order, and try to apply coupon 'TEST'

### Expected result

Coupon 'TEST' gets applied

### Actual result

Coupon 'TEST' cannot be applied, unless we disable/delete the first expired rule (or set Discard subsequent rules to NO).

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment]
UPDATE : If we simply make action `set Discard subsequent rules to NO`, then both rules are applied to cart.

**Comment by engcom-Bravo** [comment]
Hi @Nuranto,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
