### ISSUE TITLE
Virtual types as plugins no longer work in Magento 2.4.5

### ISSUE THREAD

**Issue by pierzakp** [magento/magento2#36387]
### Preconditions and environment

- Magento version 2.4.5
- Issue occurred after upgrade to Magento 2.4.5 from Magento 2.4.3
- Occurs in situation when we have a plugin which is a virtual type

### Steps to reproduce

Perform di compile when having a plugin which is a virtual type

### Expected result

Di compile is completed successfully,
virtual type real type should be used as resolvable namespace.

### Actual result

Di compile fails, because virtual type namespace is not resolvable, which is true.

Interceptors generation... 4/9 [============>---------------]  44% 33 secs 120.0 MiBget_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given#0 /var/www/magento/vendor/magento/framework/Interception/Definition/Runtime.php(44): get_class_methods()

#1 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Generator/InterceptionConfigurationBuilder.php(205): Magento\Framework\Interception\Definition\Runtime->getMethodList()

#2 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Generator/InterceptionConfigurationBuilder.php(96): Magento\Setup\Module\Di\Code\Generator\InterceptionConfigurationBuilder->getInterceptedMethods()

#3 /var/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Interception.php(99): Magento\Setup\Module\Di\Code\Generator\InterceptionConfigurationBuilder->getInterceptionConfiguration()

#4 /var/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\Interception->doOperation()

#5 /var/www/magento/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()

#6 /var/www/magento/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()

#7 /var/www/magento/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()

#8 /var/www/magento/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()

#9 /var/www/magento/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()

#10 /var/www/magento/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()

#11 /var/www/magento/bin/magento(23): Symfony\Component\Console\Application->run()

#12 {main}

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pierzakp** [comment]
@magento I am working on it

**Comment by engcom-November** [comment]
Hi @pierzakp ,
Thank you for reporting and collaboration. As per the Magento [devdocs](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html), plugins can not be used on Virtual Types and is mentioned as limitation in the documentation. Hence this issue cannot be fixed as this is a known limitation. Please refer the document and provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment]
Hi @pierzakp ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Comment by mvaisberg** [comment]
Same issue here, did you find any solution @pierzakp

**Comment by maqlec** [comment]
@engcom-November you didn't read the description carefully. Limitation in devdocs is about to use plugins on Virtual types not use virtual type as a plugin. This is what @pierzakp meant. I have the same situation now and dont know what to do. Create concrete classes or waiting for correct interception generation.

**Comment by maqlec** [comment]
@engcom-November its better. In the same documentation there is allowance to use virtual type as a plugin
![image](https://user-images.githubusercontent.com/13941930/225609918-46ed3465-42d8-4ae1-bc3a-00d3fd42e61f.png)

**Comment by pierzakp** [comment]
> @engcom-November you didn't read the description carefully. Limitation in devdocs is about to use plugins on Virtual types not use virtual type as a plugin. This is what @pierzakp meant. I have the same situation now and dont know what to do. Create concrete classes or waiting for correct interception generation.

Correct! This is what I meant. I do not recall such limitations described in the documentation...

**Comment by pierzakp** [comment]
> Same issue here, did you find any solution @pierzakp

Created following patch as a quick workaround:
`Index: magento/setup/src/Magento/Setup/Module/Di/Code/Generator/InterceptionConfigurationBuilder.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- magento/setup/src/Magento/Setup/Module/Di/Code/Generator/InterceptionConfigurationBuilder.php
+++ magento/setup/src/Magento/Setup/Module/Di/Code/Generator/InterceptionConfigurationBuilder.php	(date 1665416658566)
@@ -13,6 +13,7 @@
 use Magento\Framework\Interception\Config\Config as InterceptionConfig;
 use Magento\Setup\Module\Di\Code\Reader\Type;
 use Magento\Framework\ObjectManager\InterceptableValidator;
+use Magento\Framework\Interception\ObjectManager\ConfigInterface;

 class InterceptionConfigurationBuilder
 {
@@ -48,25 +49,33 @@
      */
     private $interceptableValidator;

+    /**
+     * @var ConfigInterface
+     */
+    private ConfigInterface $omConfig;
+
     /**
      * @param InterceptionConfig $interceptionConfig
      * @param PluginList $pluginList
      * @param Type $typeReader
      * @param Manager $cacheManager
      * @param InterceptableValidator $interceptableValidator
+     * @param ConfigInterface $omConfig
      */
     public function __construct(
         InterceptionConfig $interceptionConfig,
         PluginList $pluginList,
         Type $typeReader,
         Manager $cacheManager,
-        InterceptableValidator $interceptableValidator
+        InterceptableValidator $interceptableValidator,
+        ConfigInterface $omConfig
     ) {
         $this->interceptionConfig = $interceptionConfig;
         $this->pluginList = $pluginList;
         $this->typeReader = $typeReader;
         $this->cacheManager = $cacheManager;
         $this->interceptableValidator = $interceptableValidator;
+        $this->omConfig = $omConfig;
     }

     /**
@@ -201,8 +210,9 @@
         foreach ($interceptionConfiguration as &$plugins) {
             $pluginsMethods = [];
             foreach ($plugins as $plugin) {
+                $realPlugin = $this->omConfig->getOriginalInstanceType($plugin);
                 $pluginsMethods = array_unique(
-                    array_merge($pluginsMethods, array_keys($pluginDefinitionList->getMethodList($plugin)))
+                    array_merge($pluginsMethods, array_keys($pluginDefinitionList->getMethodList($realPlugin)))
                 );
             }
             $plugins = $pluginsMethods;`

**Comment by davinanaya** [comment]
I applied the solution and still have the same problem. I am updating Magento to version 2.4.6

**Comment by quisse** [comment]
The patch will get overwritten on a fresh `composer install`, this because of the `magento/magento2-base` module post install shizzle. Applying this fix as a patch using `cwaegans/composer-patches` to the `magento/magento2-base` overcomes this issue.

@davinanaya  maybe that's the reason why you still have the same problem?
