### ISSUE TITLE
CartItemInterface cannot add extension_attributes

### ISSUE THREAD

**Issue by degaray** [magento/magento2#3640]
I am trying to extend CartItemInterface with custom attributes. It goes well, in most parts, but it crashes when calling `/carts/mine/payment-information`. This is the error I get:

```
  "message": "Recoverable Error: Argument 1 passed to Magento\Quote\Model\Cart\Totals\Item::setExtensionAttributes() must be an instance of Magento\Quote\Api\Data\TotalsItemExtensionInterface, instance of Magento\Quote\Api\Data\CartItemExtension given, called in /vagrant/data/magento2/lib/internal/Magento/Framework/Api/DataObjectHelper.php on line 125 and defined in /vagrant/data/magento2/app/code/Magento/Quote/Model/Cart/Totals/Item.php on line 470",
  "trace": "#0 /vagrant/data/magento2/app/code/Magento/Quote/Model/Cart/Totals/Item.php(470): 

```

**Comment by mitul69** [comment]
hey @degaray 

Have you added dependency in your di.xml file?

**Comment by ishakhsuvarov** [comment]
@degaray Thank you for reporting. We already have a similar item in our backlog (internal ticket `MAGETWO-50025`) to investigate this.

**Comment by degaray** [comment]
Thanks. Do you have a workaround?

**Comment by ishakhsuvarov** [comment]
@degaray I'm afraid we don't have one currently. We will update this ticket as soon as some more information is available.
Thank you.

**Comment by degaray** [comment]
Ok, here is what I have found so far. If you create an `extension_attribute` for `Magento\Quote\Api\Data\CartItemInterface` it works well. However when you call `/carts/mine/payment-information` Magento tries to convert the CartItemInterface into a `Magento\Quote\Model\Cart\Totals\TotalsItemInterface`. The problem is that at certain point in the conversion specifically in `Magento\Framework\Api\DataObjectHelper::_setDataValues (125)` it tries to run TotalItem's setExtensionAttribute, and it tries to set it with CartItem's `extension_attributes`. Since CartItem's `extension_attributes` has a different type than TotalItem's it gives the exception.
My best guess is you should convert the `extension_attributes` type in `Magento\Quote\Model\Cart\CartTotalRepository::get` before populateWithArray.

**Comment by ishakhsuvarov** [comment]
@degaray Closing this ticket, as the fix seems to be delivered with the linked commit. Please feel free to reopen if you have any additional questions.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69223
