### ISSUE TITLE
How to change column type from "int" to "text/varchar" using db_schema.xml?

### ISSUE THREAD

**Issue by zunsakai** [magento/magento2#36400]
### Summary

In the table `sales_shipment`. I want to change the column type `shipment_status` from `int` to `text/varchar`.
When I use `db_schema.xml`:
```
<table name="sales_shipment" resource="default" engine="innodb" comment="">
    <column xsi:type="text" name="shipment_status" nullable="true" comment="Shipment Status" />
</table>
```
An error occurred:
```
Invalid Document 
Element 'column', attribute 'unsigned': The attribute 'unsigned' is not allowed.
Line: 719

Element 'column', attribute 'identity': The attribute 'identity' is not allowed.
Line: 719
```
I guess it comes from `vendor/magento/module-sales/etc/db_schema.xml`
![Screen Shot 2022-10-31 at 18 50 42](https://user-images.githubusercontent.com/8158019/199001514-9eb1193f-a8bd-404f-ac05-84585b929520.png)

I tried using `InstallSchema` instead. It worked.
```
$connection->modifyColumn(
    'sales_shipment',
    'shipment_status',
    [
        'type' => \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
        'nullable' => true,
    ]
);
```
So, how to change the column type without using `InstallSchema`? (db_schema.xml only)

### Examples

```
<table name="sales_shipment" resource="default" engine="innodb" comment="">
    <column xsi:type="text" name="shipment_status" nullable="true" comment="Shipment Status" />
</table>
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kylepham103** [comment]
Hello, Does anyone have any comments?

**Comment by engcom-November** [comment]
Hi @kylepham103 ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance but unable to retrieve shipment_status information anywhere in UI or in DB as well.
**Steps performed:**
1. Orders placed with flat rate, UPS, FEDEX shipping methods
2. Invoiced and created shipments with (Partial and Full quantity)
3. Sent tracking Information
"shipment_status" column is always NULL in DB tables: "sales_shipment" , "sales_shipment_grid " for any order status - Pending, Processing, complete, closed.
Also there is no shipment status column in Admin UI - Shipments page or Order details page and no where mentioned in Magento [docs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/order-management/shipments.html?lang=en).
Kindly check the behavior on Magento 2.4-develop instance and define the scope of testing here. Please provide configuration details / 3rd party extensions / modules enabled if any to work on this.
Thank you.

**Comment by engcom-November** [comment]
Hi @phamdungtsx ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
