### ISSUE TITLE
Hierarchy node duplicated when changing Url key on a CMS page

### ISSUE THREAD

**Issue by csanseverinoNL** [magento/magento2#36415]
### Preconditions and environment

Magento Commerce 2.4.3

### Steps to reproduce

1. Add a new or existing CMS page to an hierarchy tree
2. Edit the CMS page Url key field
3. Check result on front-end

### Expected result

No duplicated nodes are visible in the navigation menu, the existing hierarchy node is updated with the new Url.

### Actual result

Hierarchy tree has duplicates: a new hierarchy node is created with the new Url while previous hierarchy node is still present.

### Additional information

As a temporary fix in our project we are extending \Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver as follows:

`<?php
declare(strict_types=1);

namespace OurVendor\VersionsCms\Observer\Backend;

use Magento\Cms\Model\Page;
use Magento\Framework\Event\Observer as EventObserver;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Serialize\Serializer\Json;
use Magento\Store\Model\ScopeResolver;
use Magento\VersionsCms\Api\HierarchyNodeRepositoryInterface;
use Magento\VersionsCms\Helper\Hierarchy;
use Magento\VersionsCms\Model\Hierarchy\Node as HierarchyNode;
use Magento\VersionsCms\Model\Hierarchy\NodeFactory;
use Magento\VersionsCms\Model\ResourceModel\Hierarchy\Node;
use Magento\VersionsCms\Model\ResourceModel\Hierarchy\Node\CollectionFactory;
use Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver as OriginalObserver;
use Psr\Log\LoggerInterface;

class CmsPageSaveAfterObserver extends OriginalObserver
{
    private HierarchyNodeRepositoryInterface $hierarchyNodeRepository;
    private LoggerInterface $logger;

    public function __construct(
        Hierarchy $cmsHierarchy,
        HierarchyNode $hierarchyNode,
        Node $hierarchyNodeResource,
        CollectionFactory $nodeCollectionFactory,
        ScopeResolver $scopeResolver,
        NodeFactory $nodeFactory,
        Json $jsonSerializer,
        HierarchyNodeRepositoryInterface $hierarchyNodeRepository,
        LoggerInterface $logger
    ) {
        parent::__construct($cmsHierarchy, $hierarchyNode,
            $hierarchyNodeResource, $nodeCollectionFactory, $scopeResolver,
            $nodeFactory, $jsonSerializer);
        $this->hierarchyNodeRepository = $hierarchyNodeRepository;
        $this->logger = $logger;
    }

    public function execute(EventObserver $observer): CmsPageSaveAfterObserver
    {
        /** @var Page $page */
        $page = $observer->getEvent()->getObject();

        if (!$this->cmsHierarchy->isEnabled()) {
            return $this;
        }

        if ($page->dataHasChangedFor('identifier')) {
            foreach ($page->getNodesSortOrder() as $nodeId => $value) {
                try {
                    $node = $this->hierarchyNodeRepository->getById($nodeId);

                    $this->hierarchyNodeResource->removePageFromNodes($page->getId(), [$node->getParentId()]);
                } catch (LocalizedException $e) {
                    $this->logger->error(__('Could not remove hierarchy node: ' . $e->getMessage()));
                }
            }
        }

        return parent::execute($observer);
    }
}`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alikhani97** [comment]
@magento give me 2.4-develop instance

**Comment by alikhani97** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @csanseverinoNL ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but issue is not reproducible to me.
Below are the steps I have followed:
1. Add a new CMS page from content >> Elements >> Pages
2. Edit the CMS page Url key field.
3. Cleared cache and indexers.
4. Check result on front-end

I couldn't find any duplicated one and older one not working as expected. Below is the screenshot for your reference:
**Screenshots:**
_**1. Created new test page and url key I have defined as testpage:**_

<img width="895" alt="Screenshot 2022-11-07 at 1 29 38 PM" src="https://user-images.githubusercontent.com/60198022/200258237-9bd2ead3-962a-4e88-b637-d4f7905b0fbe.png">

**_2. Updated the url key as testpage12345 ,Older page is not working as expected:_** 
     
<img width="854" alt="Screenshot 2022-11-07 at 1 32 09 PM" src="https://user-images.githubusercontent.com/60198022/200258091-bb19ded6-06ac-46b6-92b0-f913507f0b23.png">

**Page with updated url key:**
<img width="872" alt="Screenshot 2022-11-07 at 1 32 21 PM" src="https://user-images.githubusercontent.com/60198022/200260052-3f14ffb3-b125-4305-bb6f-16aa270c408b.png">

Kindly check in the latest Magento `2.4-develop` and let us know if you are facing any issue.

Thanks

**Comment by csanseverinoNL** [comment]
hello @engcom-Lima i think there's a misunderstanding: this is not an issue about routing, it affects only the way navigation menu is built and CMS pages hierarchy structure.

Your page should be in the navigation menu hierarchy because that's where the issue happens: if your test page is going to be set as a child of the "Sale" navigation menu node for instance, changing the url key afterwards should make the link "Test page" appear twice under the "Sale" dropdown in the navigation menu

**Comment by csanseverinoNL** [comment]
@engcom-Lima please also note that this is ONLY reproducible on Magento Commerce (CMS page hierarchy is not available in Magento Open Source), and therefore the Magento instance created for this issue is not useful.

**Comment by engcom-Lima** [comment]
Hi @csanseverinoNL ,

Thanks for quick reply. Kindly provide us more detailed steps to reproduce as well as screenshots.

Thanks

**Comment by engcom-Lima** [comment]
Hi @csanseverinoNL ,



We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks
