### ISSUE TITLE
Compare product limit

### ISSUE THREAD

**Issue by mitul69** [magento/magento2#3641]
Hello There, 

working in magento2 theme development, I am searching for to set the limit for the add to compare list,  right now i can add as much as i want to add in compare list, 

I would like an option in magento admin panel from where i will set the limit. 

Many thanks in advance, 

Mitul Patel

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by pboisvert** [comment]
passing to Olena as this ties to theme. Please reassign if a different PM owner for the feature request

**Comment by antboiko** [comment]
Hi @mitul69 , thanks for your inquiry. I've created internal ticket MAGETWO-52537 to track this feature and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Compare-product-limit/idi-p/46065).
