### ISSUE TITLE
Magento 2.0.2 Contact Us

### ISSUE THREAD

**Issue by Coupes** [magento/magento2#3642]
Magento 2.0.2 Contact Us form returns and error after form is submitted. 

Error is shown below which doesn't make a hell of a lot of sense to me apart from it just failing...

We can't process your request right now. Sorry, that's all we know. 

Website is... http://www.wgas.org:33/magento/contact/index/

Please help.

**Comment by mitul69** [comment]
Hello @Coupes 

I think you working on local system please check your mail configuration, 

The issue due to mail sending

**Comment by Coupes** [comment]
Tried your suggestions, all mail sending configuration is fine, sent on wide area networks and still the same error. Any other suggestions? Like does the standard Magento 2.0.2 have send option or does and extension need to be obtained? Look forward to hearing back.

**Comment by mihaimghn** [comment]
Any solution to this problem, yet? All my mail settings are ok. Using MAgento 2.0.4.

**Comment by frederic-eynaud** [comment]
I have the same answer using Magento 2.0.6

**Comment by piotrekkaminski** [comment]
if I install mailutils on local server, i'm not able to reproduce it.

**Comment by flecxie** [comment]
Might be related to this issue: https://github.com/magento/magento2/issues/6153
Try loading a template for the Contact Form e-mail as WAR.
