### ISSUE TITLE
Grunt exec command not working in magento2

### ISSUE THREAD

**Issue by xxxsf** [magento/magento2#3643]
I am following:
[http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html)

it says  grunt exec:<theme> does:

Republishes symlinks to the source files to the pub/static/frontend/Vendor/default/<locale> directory.

but that does not work and I am getting error as following:

Execution Time (2016-03-04 08:12:57 UTC)
loading tasks                217ms  ███████████████████████████ 80%
loading grunt-contrib-clean   12ms  ██ 4%
clean:blank                   41ms  ██████ 15%
Total 270ms

> > 'searchd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> > ���������ļ���
> > Processed Area: frontend, Locale: zh_Hans_CN, Theme: Magento/blank, File type: less.
> > [Magento\Framework\Exception\FileSystemException]
> >   Cannot create a symlink for "E:/Shop123/app/design/frontend/Magento/blank/w
> >   eb/css/source/_reset.less" and place it to "E:/Shop123/pub/static/frontend/
> >   Magento/blank/zh_Hans_CN/css/source/_reset.less" Warning!file_get_contents(
> >   E:\Shop123\var\cache\mage-tags\mage---0f2_INTERCEPTION): failed to open st
> >   ream: No such file or directory
> > dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
> > Exited with code: 1.
> > Warning: Task "exec:blank" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2016-03-04 08:12:56 UTC)
loading tasks  217ms  ██ 4%
exec:blank      5.8s  ██████████████████████████████████████████████ 96%
Total 6.1s

**Comment by vzaporozhets** [comment]
@allan2coder, thanks for contacting us. I would admit that Magento 2 doesn't support Windows-family operational systems. However, did you try to follow recommendation from http://magento.stackexchange.com/a/85146 ? Which version/branch are you using ?

**Comment by vzaporozhets** [comment]
Closing this issue - no reply for 2 weeks.
