### ISSUE TITLE
Undefined index in TierPriceValidator.php

### ISSUE THREAD

**Issue by clockworkgeek** [magento/magento2#36431]
### Preconditions and environment

- Magento version 2.4.5
- MariaDB 10.3.36 although that's probably irrelevant since this is normal database behaviour.

### Steps to reproduce

1. Create a customer group with a trailing space in it's name.
2. Create admin integration token using POST: ` /rest/default/V1/integration/admin/token`
3. Using the API endpoint `/rest/V1/products/tier-prices`, attempt to POST a tier price for the new customer group but without the trailing space.
Payload:
_{
  "prices": [
    {
      "price": 40,
      "price_type": "fixed",
      "website_id": 0,
      "sku": "24-MB01",
      "customer_group": "rvevgbbrrbr",
      "quantity": 1,
      "extension_attributes": {}
    }
  ]
}_

### Expected result

A tier price should not be created because the customer group's name does not match. The API should return an error message like "No such entity with Customer Group".

### Actual result

The API returns an error message like `Message: Notice: Undefined index: XXXXX in ~/public_html/vendor/magento/module-catalog/Model/Product/Price/Validation/TierPriceValidator.php on line 474"`

### Additional information

The problem occurs because the database equates the two customer group names although we know there is a single character difference. The method `TierPriceValidator::retrieveGroupValue` first assigns one name with:

    $this->customerGroupsByCode[strtolower($item->getCode())] = $item->getId();

then accesses the same array with another name and triggers an undefined index error: 

    return $this->customerGroupsByCode[$code];

There are two ways to mitigate this that I can see.

1. Sanitise your inputs by trimming whitespace, removing control characters, etc. (And it's good advice in general too)
2. Query the database with `LIKE` instead of `=` because that respects trailing spaces.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence updating the description and confirming this issue.
Issue occurred for existing customer group names having trailing space and for any other non existing customer group names given in the api request, this issue is not reproducible.
![image](https://user-images.githubusercontent.com/60198231/201077424-80b00e1a-5eb9-4356-9760-3278e0174020.png)
![image](https://user-images.githubusercontent.com/60198231/201077733-3722cabf-5fa8-4568-b134-0c10cd3d047a.png)

**Comment by quterorta** [comment]
@magento I am working on this
