### ISSUE TITLE
Custom Wysiwyg Style Formats Disappeared After Upgrade to 2.4.5-p1

### ISSUE THREAD

**Issue by eshcoleswarming** [magento/magento2#36442]
### Preconditions and environment

- Magento 2.4.5-p1

### Steps to reproduce

1. Create a custom module
2. Add custom style format according to the instructions for Extending the TinyMCE editor given in the [Magento DevDocs](https://developer.adobe.com/commerce/frontend-core/ui-components/components/wysiwyg/configure-tinymce-editor/#extending-the-tinymce-editor)
3. Clear cache and load the Wyswig in the Pagebuilder

### Expected result

Custom style format is present in the formats list

### Actual result

Custom style format is ignored and only the default formats load

### Additional information

Magento was upgraded from 2.4.0 to 2.4.5-p1. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
HI @eshcoleswarming,

Thank you for reporting and collaboration.

We have tried to reproduce this issue on Magento 2.4-develop instance and we required more information like screenshot so that we can easily reproduce this issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @eshcoleswarming,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
