### ISSUE TITLE
Product API updates to 'status' field not reflected in the admin UI

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#36443]
### Preconditions and environment

Magento 2.4.2

### Steps to reproduce

1. Go to Admin > Catalog > Inventory > Products
2. Go to a product record
3. Select Enable Product -> Yes
4. Create a REST admin api token using admin credentials and the REST `/v1/admin/token` endpoint
5. Use the token created in step 4 to send the following PUT data to the `/rest/V1/products/[sku]` endpoint:
    `{"product":{"status": 2}}`

### Expected result

1. API response contains updated status (`2`)
2. Admin UI contains updated status (`Enable Product => No`)

### Actual result

1. API response contains updated status (`2`)
2. Admin UI contains unaltered status (`Enable Product => Yes`)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nbennett25** [comment]
@magento give me 2.4-develop instance

**Comment by nbennett25** [comment]
Confirmed in 2.4-develop:

![Screen Shot 2022-11-08 at 4 38 19 PM](https://user-images.githubusercontent.com/13220124/200681463-2a9ac645-7588-4983-b30f-dc6bc575a141.png)

**Comment by Vasudev-22** [comment]
Hi @engcom-Bravo / @nbennett25 , 

API Endpoint:- **{base_url}/rest/all/V1/products/{sku}.** . This will trigger ALL Store View, and it's working fine in 2.4-develop . Attaching screenshot here.

![RestApi_Change](https://user-images.githubusercontent.com/104893739/200829447-04e5b6ed-85d2-4427-b450-8d5cc9eaf298.png)


API Endpoint:- **{base_url}/rest/V1/products/{sku}.** . This will trigger Default Store View, Please check your product in default store view, status got changed in magento ADMIN.

**Comment by nbennett25** [comment]
Thanks @engcom-Bravo - changing the endpoint works as expected. We are using single store mode, so no scope change was available in the product record.

As a design, this seems backwards: I would imagine not specifying a scope in the endpoint would set the change at the top scope, and you would need to specifically target a lower scope with the API endpoint, rather than the other way aroudn.
