### ISSUE TITLE
Cannot see the whole webpage

### ISSUE THREAD

**Issue by suggs628** [magento/magento2#36441]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Dash** [comment]
Hi @suggs628 ,

Kindly Provide preconditions,Steps to reproduce, Screenshots,Actual results,Expected results....It is easy to proceed further.

Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @suggs628 ,

We are closing this issue as there has been no latest updates on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
