### ISSUE TITLE
Cart Price Rule Update Queue Process Dies Without (known) Reason

### ISSUE THREAD

**Issue by motau** [magento/magento2#36448]
Cart Price Rule Update Queue Process Dies Without (known) Reason
### Environment: 
  - running on aws infrastructure: 
    - kubernetes cluster namespace, scalable, health check detection
    - magento2 CE 2.4.3 - PHP 7.3 (php-fpm) : pod
    - nginx: pod
    - redis: pod 
    - db: aws  
  
### Preconditions (*)

1. in adminUI we setup several magento cart price rules with 1 per user codes
2. on machine the coupon update usage cli command is running: `bin/magento queue:consumers:start sales.rule.update.coupon.usage` as separate task (parallel executed from docker entry point)
3. cron jobs cannot be used for this update to avoid the high frequency usage of same code (cron has a minimum of 1 minute)

### Steps to reproduce (*)

1. after some months the important queue runner process (`bin/magento queue:consumers:start sales.rule.update.coupon.usage`) **died unrecognized** by any of our logs or health checks
2. we cannot reproduce or force this behaviour

### Expected result (*)

1. as a store owner I must have the warranty that all business processes are running as expected
2. as developer I need a magento health check for running queues, at least I have to know how to observe the existence of running queues

### Actual result (*)

1. the died process did already lead to a fraud: an end user could pay multiple times with a one time code
2. an ERP reporting did show the fraud - much **too late**
4. after that the container was restarted an the processes are running 
5. **Important** questions remain: 
- how long will the process be stable?
- how can I detect the death of a missing queue runner?

**Comment by engcom-Hotel** [comment]
Hello @motau,

Thanks for the report and collaboration!

We have gone through the issue description and what we get with it is you are facing an issue with the cron `sales.rule.update.coupon.usage` but the reproduction steps don’t seem enough to process the issue further.

So I request you to please provide some more information on it and also with proper Expected and actual result.

Thanks

**Comment by ahacart-adexos** [comment]
@magento give me 2.4-develop instance
