### ISSUE TITLE
CMS content images missing title attribute

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#36446]
### Preconditions and environment

OS 2.4.3-p1

### Steps to reproduce

Add an image to a CMS page or block content or indeed any product or category description field.

### Expected result

Admin should be able to set both the alt (image description) and title attributes like was available in M1:

![image](https://user-images.githubusercontent.com/13659750/200789429-b51cb9b2-4fef-4ae5-819b-154207177a56.png)

### Actual result

Cannot set image title attribute:

![image](https://user-images.githubusercontent.com/13659750/200789606-8244bd30-2974-479d-aa0c-e35e70a2e018.png)

### Additional information

Workaround is to switch to HTML view and manually add the title attribute but end-users shouldn't have to do that. There was no sensible reason to drop the title tag.

### Release note

Fixed missing title attribute on content images.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adamlavery** [comment]
@magento give me 2.4-develop instance

**Comment by adamlavery** [comment]
Confirmed, no option to set image title:

![image](https://user-images.githubusercontent.com/13659750/200797231-7ee78c4f-157b-4006-bd93-48669ef932e8.png)

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @adamlavery ,

We are trying to reproduce the issue in 2.4-develop instance....we are not able to reproduce the issue.
we are getting actual result....
Steps:
1.install magento instance
2.Go to content
3.click Edit with page Builder
4.Set image and image uploaded successfully
ScreenShots:
<img width="1512" alt="Screenshot 2022-11-10 at 12 41 56 PM" src="https://user-images.githubusercontent.com/60198592/201024520-8cb3af1f-1d08-4aca-bf0a-cd7aba4dca97.png">


let us know if we missing anything!!!
Thanks!!!

**Comment by adamlavery** [comment]
Gosh, I wish you'd read information supplied properly! Nowhere does this ticket mention an issue with uploading images, The issue is with adding the Title attribute to images.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @adamlavery ,

Thanks for your  contribution !!!

1.We are confirming the issue in 2.4-develop branch..We are getting actual result.

2.Admin should be able to set both the alt (image description) and title attributes

Preconditions:
Magento version 2.4-develop
PHP 8.1

Steps We followed by:
1.open the product page which has video in product gallery
2.click on the product image to open the gallery fullscreen mode
3.click on the product video thumbnail
4.Admin can able add image description as well as tittle attributes.

So we are confirming the issue.

Let us know if we are missing anything!!!

Thanks!!!

**Comment by magentox** [comment]
Not really a bug. If you take a look at Tinymce 5 demo even the version on their website which includes Premium plugins does not have an "image title" option. 
[https://www.tiny.cloud/docs/demo/full-featured/](url)

![Capture1](https://user-images.githubusercontent.com/44047835/201482489-bf3fc077-8cb0-4e2a-881f-362d9e2891d3.jpg)


![Capture2](https://user-images.githubusercontent.com/44047835/201482493-fc0d7c57-ce57-418a-b83d-2790462def8f.jpg)

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @magentox ,

Thanks for your information...the link is not working for me which is attached in last comment...Kindly attach any other links you have...its very help to reproduce the issue again.


Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @adamlavery 

We are trying to reproduce the issue in 2.4-develop instance...We are not able to reproduce the issue.
we are getting expected results.
Admin should be able to set both the alt (image description) and title attributes.

Steps we followed:
1.Install 2.4-develop instance
2.go to content
3.Create new page
4. we are trying to add image as well as title attributes and We are able to add successfully.

Screenshots:
<img width="1512" alt="Screenshot 2022-11-22 at 3 40 58 PM" src="https://user-images.githubusercontent.com/60198592/203296659-458c534d-02a8-491b-957a-5e5df3ce0ce4.png">

Note:Please let me know which title attribute in your Expected results.

Let us know if we missing anything!!!

Thanks!!!

**Comment by adamlavery** [comment]
Can't see that this latest comment adds anything. How does that demonstrate adding a title attribute to the image? You're not testing adding a title to the page are you? If so, suggest you re-read the issue!

**Comment by adamlavery** [comment]
@magentox is correct (thanks). This was standard in M1 (TinyMCE3) but options disabled in M2 (TinyMCE4). Following restores both title and advanced image options (thanks https://meetanshi.com/blog/configure-tinymce4-toolbar-in-magento-2-3-x/ for reference)...

Create a new module or use existing:

In **etc\di.xml** add:
```
    <!-- Extend TinyMCE -->
    <type name="Magento\Ui\Component\Wysiwyg\ConfigInterface">
        <plugin name="extend_tinymce"
                type="Vendor\Module\Plugin\TinyMCEConfig"
                sortOrder="10"/>
    </type>

```
Create **Plugin\TinyMCEConfig.php** and add:
```
<?php

namespace Vendor\Module\Plugin;

class TinyMCEConfig {

    protected $activeEditor;

    public function __construct(\Magento\Ui\Block\Wysiwyg\ActiveEditor $activeEditor) {
        $this->activeEditor = $activeEditor;
    }
    public function afterGetConfig(
        \Magento\Ui\Component\Wysiwyg\ConfigInterface $configInterface,
        \Magento\Framework\DataObject $result
    ) {

        $editor = $this->activeEditor->getWysiwygAdapterPath();
        if(strpos($editor,'tinymce4Adapter')) {

            $settings = $result->getData('settings');
            if (!is_array($settings)) {
                $settings = [];
            }

            $settings['image_title'] = true;
            $settings['image_advtab'] = true;
            $result->setData('settings', $settings);
            return $result;
        } else {
            return $result;
        }
    }
}
```

**setup:di:compile** and **cache:flush** then you'll have the additional image options.
