### ISSUE TITLE
customer_address_id is null on orders and quotes

### ISSUE THREAD

**Issue by sengaigibon** [magento/magento2#3645]
Not sure if this is an issue..:
On checkout: 
Step 1, customer already has addresses, but I create a new one for shipping. 
Step 2, I chose a different billing address from the address book.
I finish the checkout without problems. 
The new address is in the table customer_address_entity, visible in the customer's address book, no problem.
But if I look into the database, tables quote_address and sales_order_address, the entry for the last billing address is there but in both cases with the field customer_address_id is equal to NULL, is this normal??
I don't think this represent a problem. In the backend if I look into the order, I can see all the details of both addresses ('cos this data doesn't come from customer_address_entity, right?).

I added custom fields 'city_id', 'district_id' and 'district' to table customer_address_entity, and only field 'district' to quote_address and sales_order_address, but I don't have problems storing the data into these tables.

**Comment by JDavidVR** [comment]
I have this issue too, its on magento2.0.2 ee, any update for this issue ?

I think this is a critical issue

thank you

**Comment by piotrekkaminski** [comment]
@JDavidVR can you provide more information how it affects you?

**Comment by pantaoran** [comment]
EDIT: I'm deleting what I wrote here before, it was not true and I was an idiot.

**Comment by koenner01** [comment]
Relates to https://github.com/magento/magento2/issues/7689

**Comment by magento-engcom-team** [comment]
@sengaigibon  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
