### ISSUE TITLE
The js error when click on video thumbnail in product gallery fullscreen mode

### ISSUE THREAD

**Issue by glevhen** [magento/magento2#36456]
### Preconditions and environment

- Magento version: 2.4.4-p2

### Steps to reproduce

1) open on the storefront the product page which has video in product gallery
2) click on the product image to open the gallery fullscreen mode
3) click on the product video thumbnail

### Expected result

the product video will autoplay and no errors in browser console

### Actual result

the js error will appear in the browser console and video will not autoplay 
```
fotorama-add-video-events.js:605 
Uncaught TypeError: this.fotoramaItem.data(...).activeFrame.$stageFrame[0].trigger is not a function
    at $.<computed>.<computed>._checkForVideo (fotorama-add-video-events.js:605:79)
    at $.<computed>.<computed>._checkForVideo (widget.js:132:25)
    at $.<computed>.<computed>._startPrepareForPlayer (fotorama-add-video-events.js:567:18)
    at $.<computed>.<computed>._startPrepareForPlayer (widget.js:132:25)
    at $.<computed>.<computed>.<anonymous> (fotorama-add-video-events.js:545:22)
    at HTMLDivElement.proxy (jquery.js:10780:23)
    at HTMLDivElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at HTMLDivElement.<anonymous> (jquery.js:8797:30)
```

### Additional information

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/16398798/201154797-f565a964-9ccc-47d2-9be4-1850805e53b7.png">

the issue is caused by changes in the commit https://github.com/magento/magento2/commit/e7a06d34dd47d079081d9f007092e35078e36012#diff-5d428affd814bd350e233104b8fc3b769544ee7e6d04a9b21a8537473876ffadR605

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @glevhen ,

we are trying to  reproduce the issue in 2.4-develop branch...But we are not able to reproduce the issue.
we got some different in console.

Steps we followed:
1.install magento instance
2.select any products
3.open the product page which has video in product gallery
4.click on the product image to open the gallery fullscreen mode
5.click on the product video thumbnail

We got js error in console.we are not able to reproduce the issue.

Screenshots:
<img width="1512" alt="Screenshot 2022-11-11 at 2 32 33 PM" src="https://user-images.githubusercontent.com/60198592/201531776-76074209-92a9-410a-877a-691d958cff51.png">


Let us know if we missing anything!!!

Thanks!!!

**Comment by glevhen** [comment]
@engcom-Dash did you upload the correct screenshot? from I see the attached screenshot is for admin product settings and not for product page gallery on the storefront, and there is no opened product video on your screenshot

**Comment by engcom-Dash** [comment]
**Hi @glevhen ,**

Thanks For your Information....Last time I uploaded wrong screenshot.
Again we worked this issue in 2.4-develop branch...We are confirming the issue.
the js error will appear in the browser console and video will not autoplay.

**Preconditions:**
Magento version : 2.4-develop
PHP :8.1

**Steps we followed:**
1.Install fresh 2.4-develop
2.Add product in Magento admin
3.Add Images and videos with respective product
4.Go to front end
5.click the Particular Product
6.Open product image page
7.Click the product image with full screen
8.Click video and check the console
9.The js error is appearing in console as per actual result and video is not autoplay.

Screenshots for your reference:
<img width="1512" alt="Screenshot 2022-11-17 at 3 50 06 PM" src="https://user-images.githubusercontent.com/60198592/202422287-9431b792-9c1c-4893-ad4e-cbee2efa844e.png">

The Actual result is 
fotorama-add-video-events.js:605 
Uncaught TypeError: this.fotoramaItem.data(...).activeFrame.$stageFrame[0].trigger is not a function
    at $.<computed>.<computed>._checkForVideo (fotorama-add-video-events.js:605:79)
    at $.<computed>.<computed>._checkForVideo (widget.js:132:25)
    at $.<computed>.<computed>._startPrepareForPlayer (fotorama-add-video-events.js:567:18)
    at $.<computed>.<computed>._startPrepareForPlayer (widget.js:132:25)
    at $.<computed>.<computed>.<anonymous> (fotorama-add-video-events.js:545:22)
    at HTMLDivElement.proxy (jquery.js:10780:23)
    at HTMLDivElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at HTMLDivElement.<anonymous> (jquery.js:8797:30)
We got same result in 2.4-develop instance,So we are confirming the issue.

Let us know if we missing anything!!!

Thanks

**Comment by rostilos** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7092 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7092&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Comment by drinkingsouls** [comment]
What was the fix for this? 
I am having this issue on Magento 2.4.6

**Comment by drinkingsouls** [comment]
Was there any solution to this?

**Comment by YoeriW** [comment]
@drinkingsouls 
Change this:

`if (this.isFullscreen && this.fotoramaItem.data('fotorama').activeFrame.i === number) {
      this.fotoramaItem.data('fotorama').activeFrame.$stageFrame[0].trigger('click');
  }`
  
  to this:
  
`if (this.isFullscreen && this.fotoramaItem.data('fotorama').activeFrame.i === number) {
      this.fotoramaItem.data('fotorama').activeFrame.$stageFrame.trigger('click');
  }`
  
  Now the Product Video will start playing when you click on the thumbnail + the error will not be shown anymore.
