### ISSUE TITLE
FedEx Update WSDL and Add New Services

### ISSUE THREAD

**Issue by jesse-thomas** [magento/magento2#36468]
I discovered that the Latest M2 is using very old FedEx wsdl files when trying to add the International Connect Plus rates (FEDEX_INTERNATIONAL_CONNECT_PLUS).

M2 is using v10 wsdl files, current FedEx wsdl files are at v31.

Are there any plans to update the core FedEx module?

**Comment by engcom-Dash** [comment]
Hi @jesse-thomas ,

We need some inputs from your side to reproduce the issue which is

1.Description
2.Preconditions
3.Environment
4.Actual Results and Expected results
5.Screenshots of the issue.

Above the informations helps to reproduce the issue...So Kindly attach above the information.

Let us know if we missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @jesse-thomas ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Comment by thomas-kl1** [comment]
Please reopen the issue. The request here is about outdated API Integration.
