### ISSUE TITLE
[2.4.5-p1] Maintenance Mode: Allow IP does not work

### ISSUE THREAD

**Issue by FadedOut** [magento/magento2#36469]
UPDATE: Anyone else having this issue and uses Cloudflare (or any reverse proxy like Cloudflare) most likely you'll have the same problem as I did and your visitor IPs are being masked. Please read my solution [HERE](https://github.com/magento/magento2/issues/36469#issuecomment-1316777083).

### Preconditions and environment

- Magento 2.4.5-p1
- PHP 8.1
- Apache 2.4.x
- I'm not on VPN

### Steps to reproduce

Enable maintenance with the following command:
```
bin/magento maintenance:enable --ip=myIPv4
```
The return response:
Set exempt IP-addresses: myip

Also tried 
```
bin/magento maintenance:enable --ip=myIPv6
```
The return response:
Set exempt IP-addresses: myip

### Expected result

Maintenance should enable for everyone but my IP.

### Actual result

Maintenance is enabled for everyone **including** me/my IP.

Excluding my IP address (IPv4 and/or IPv6) does not work.

### Additional information

I have also tried the following:
```
bin/magento maintenance:allow-ips myip
```
I have used IPv4 as well as IPv6

I followed the info here:
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/maintenance-mode.html

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magenx** [comment]
can you see your IP address in apache access log?

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @FadedOut,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="691" alt="Screenshot 2022-11-16 at 2 39 29 PM" src="https://user-images.githubusercontent.com/51680745/202157600-442885ee-6f44-4040-897f-89434d25afa3.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.
