### ISSUE TITLE
Bundle js generates a 7.9mo file

### ISSUE THREAD

**Issue by matthieusibille** [magento/magento2#3646]
hello,

I'm currently working on Magento 2.0.2 and I noticed that loading time for all pages are extremely high.

I'm running on Xampp at the moment, production mode enable, html/js/css are merged and minify, varnish is disable and i will not use it since my Web hosting can't install it on my server because it will interfer with some scripts. I use a custom theme which parent is the blank theme of Magento 2.

I tried the bundling option but it generates a 7.9mo js file which is not ideal. After changing my settings i redeployed static files and empty the cache.
edit : And without bundle js activated the total js files size is 955 ko.

Some people tried it with luma theme and it generated a 1.5mo file from what I heard.

Is there additional configuration to do or is there an issue with the blank theme ?

Thank you for your help Regards

**Comment by vkorotun** [comment]
Hi @matthieusibille 
Thank you for your question.
Please, check app/design/frontend/Magento/blank/etc/view.xml. There you'll find <exclude> section, in that section you may specify files or directories to be excluded from bundle(s) for corresponded theme.

Also, for the next Milestone backlog, we have a couple stories for improving default bundling strategy. Our goal will be to decrease size of bundle files. On of the ideas we are going to check: having multiple bundles, or better to say micro-bundles per some scope (page, or particular component).
