### ISSUE TITLE
How can Saleable Quantity be higher than physical quantity?

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#36467]
### Preconditions and environment

OS 2.4.3-p1

### Steps to reproduce

No idea how to reproduce something that should never be able to happen.

### Expected result

Saleable Quantity should never be higher than physical quantity

### Actual result

How does this happen? How can saleable quantity be 2 when physical quanity is 0?

![image](https://user-images.githubusercontent.com/13659750/201383589-0c91f89e-edc2-46ba-a0a4-4a63cdecfd4f.png)

There is just one stock source (default). Quantity is correct but where does it get saleable quantity from? That is, what database records contain the information that it is displaying for Default Stock. 

To confirm, there are no reservations for this product, which in any case should reduce saleable quantity not increase it.

### Additional information

As a result of this discrepancy that product can be purchased even though there is no stock. Until whatever has messed up in the data can be corrected, only way to deal with it is to manually set the product out of stock so it cannot be ordered.

Looking for a clue as to where this data comes from so it can be manually corrected. Given Knockout destroys any useful link between what is displayed and where it comes from, without knowing how it was put together how can we know which bit of code added that value? Yes it's a Data Provider, but which bit of code in the mass of XML and modifyData calls actually does this value?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adamlavery** [comment]
Please don't ask to reproduce this. As noted this scenario shouldn't be possible so reproducing is a non-starter. What's needed is to look at the code the generates the Saleable Quantity figure and work out how that can be wrong and cause this.

**Comment by FadedOut** [comment]
@adamlavery 

Yeah I don't think that looks right. Something might be misconfigured maybe?

A shot in the dark, but try checking the settings here:
Store Config > Catalog > Inventory > Product Stock Options (Out of Stock threshold)

Also check to make sure the indexing is running correctly (check cron.log). Maybe just re-run the reindex command just in case. Maybe also try just changing the number for "Out of Stock threshold" then run the reindex command. Because I have mine set to 30 there and the "Salable quantity" might say 100 but "Quantity" will say 130 - which is how it should be (I'm on Magento 2.4.5-p1 just for reference)

Hopefully this helps because that's a pain (to manually change the stock to in/out) and shouldn't need to be done that way. 

If the above don't help, was there an update recently then you noticed this started happening? Maybe it was an update that caused it?

**Comment by engcom-Dash** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @adamlavery ,

We are trying to reproduce the issue in 2.4-develop instance...we are not able to reproduce because we are getting Expected result.
Screenshots:
<img width="1512" alt="Screenshot 2022-11-14 at 11 17 07 AM" src="https://user-images.githubusercontent.com/60198592/201584845-374d0b18-9a64-49a4-bab9-e8af125e02cd.png">


Steps:
1.Install Magento instance
2.Go to catalog---> Products
3.saleable quantity not greater then quantity

Let us know if we are missing anything!!!

Thanks!!!

**Comment by adamlavery** [comment]
As stated at the start, this should not happen. How it's happened is anyone's guess hence being able to reproduce it is impossible. Neverthess it has happened. Question now is how can it be corrected. As far as I'm aware Saleable Quantity is **calculated** as quantity minus any reservations. There are no reservations but even if there only 0 minus a minus produces a positive result! 

We therefore need to look at the code that calculates the value that is presented on the product grid to detemnine why it is wrong. However, the complex nature of the new UI combined with Knockout makes tracking this back to source near impossible. Therefore can someone point to where this value gets put into big blob of data that knockount uses? Then perhaps with some debugging we can figure out why it is wrong.

Thanks.

**Comment by gwharton** [comment]
This is the calculation of salable qty in the code.

```
$stockItemConfig = $this->getStockItemConfiguration->execute($sku, $stockId);
return $this->getProductAvailableQty->execute($sku, $stockId)
            + $this->getReservationsQuantity->execute($sku, $stockId)
            - $stockItemConfig->getMinQty();
```
Do you have multiple stocks and multiple websites or are you using the default stock and source.

If so, check the stock levels and out of stock threshold for all websites. It could be that the "Use config settings" has become unticked for the non default store?

Out of interest, try setting out of stock threshold to -10, then check to see whether salable qty goes to 10 or 12. If it goes to 12, then the problem must be with the stock level as reservations are zero.

**Comment by adamlavery** [comment]
Thanks Graham. One website, one stock source, three store views. Checked all three store views and all using default config. 

However, setting threshold to -10 does indeed now create a saleable quantity of 12.

![image](https://user-images.githubusercontent.com/13659750/201721698-9f9ad3fc-9c6a-492d-a17c-0baae3782643.png)

I'll locate and debug that code to see if it provides any clues.

**Comment by gwharton** [comment]
Just to rule out something else, if you set out of stoick threshold to zero, instead of use config value, do you get salable qty 0 or 2.

**Comment by gwharton** [comment]
for the default stock, stock levels are taken from cataloginventory_stock_item

for non default stocks, stock levels are taken from inventory_stock_x where x is the stock id.

Locate the product in those tables and check the stock level is not 2.

**Comment by adamlavery** [comment]
We have no inventory_stock_x tables. This from cataloginventory_stock_item:

![image](https://user-images.githubusercontent.com/13659750/201736197-843b5fae-fa27-4012-91b2-09ba7618509d.png)

Everything has two entries, one for website id 0 (admin) and one for website id 2 (the default website).

**Comment by adamlavery** [comment]
Setting threshold explictly to 0 on the product still results in a saleable of 2.

**Comment by adamlavery** [comment]
All very weird! It's this bit of code returning a value of 2:

```
    public function execute(string $sku, int $stockId): float
    {
        $connection = $this->resource->getConnection();
        $reservationTable = $this->resource->getTableName('inventory_reservation');

        $select = $connection->select()
            ->from($reservationTable, [ReservationInterface::QUANTITY => 'SUM(' . ReservationInterface::QUANTITY . ')'])
            ->where(ReservationInterface::SKU . ' = ?', $sku)
            ->where(ReservationInterface::STOCK_ID . ' = ?', $stockId)
            ->limit(1);

        $reservationQty = $connection->fetchOne($select);
        if (false === $reservationQty) {
            $reservationQty = 0;
        }
        return (float)$reservationQty;
    }

```
Despite there being no records in that table for that SKU:

![image](https://user-images.githubusercontent.com/13659750/201738981-161e2804-b8b7-42ee-9211-2a27f945f5bc.png)

SKU passed in is most definitely the product with the issue:

![image](https://user-images.githubusercontent.com/13659750/201739856-53af9886-6b7f-4faa-85c9-a5cdb4321d81.png)

**Comment by gwharton** [comment]
Weird. Turn on db logging and check what the actual SQL statement that was executed.

**Comment by adamlavery** [comment]
Did that and query is as expected:

```
## 339144 ## QUERY
SQL: SELECT SUM(quantity) AS `quantity` FROM `inventory_reservation` WHERE (sku = 'TWMC0EK01S-BK-XX') AND (stock_id = 1) LIMIT 1
AFF: 1
TIME: 0.0004
```

Tried restarting MySQL and reset the query cache; no change. Tried explicting faking a reservation for that product and external query comes back as expected:

![image](https://user-images.githubusercontent.com/13659750/201891809-e10eb662-700c-4f82-8481-41d1be9dacdc.png)

But Magento query still comes back with 2!

I'll continue trying to trace but debugging Magento execution is like wading through treacle! Why use one class when 100 will do!!

**Comment by gwharton** [comment]
I'm stumped. Step through the fetchOne call. Its getting butchered somewhere in there.

**Comment by adamlavery** [comment]
Thanks for your input @FadedOut but that approach is never a good one for production websites and was impossible to reproduce on a dev site. Traditional technical debugging of the live issue is what was required here. What I needed was a point in the right direction - thanks @gwharton.

Anyhow, while in the middle of debugging it, the problem stock updated from the external system and the issue went away. I got as far as the following in vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php

```
    public function fetchColumn($col = 0)
    {
        try {
            return $this->_stmt->fetchColumn($col);
        } catch (PDOException $e) {
            #require_once 'Zend/Db/Statement/Exception.php';
            throw new Zend_Db_Statement_Exception($e->getMessage(), $e->getCode(), $e);
        }
    }

```

It was the PDOStatement::fetchColumn() that was returning a value of 2 when it should have been null. The SQL statement was correct but the response from that PDO call incorrect. That's not Magento but some issue with PHP and/or MySQL. As the problem corrected when the database was updated, I'm suspecting some kind of uninitialised variable scenario where underlying memory map changed hiding the problem again.

**Comment by adamlavery** [comment]
Not Magento - closing.
