### ISSUE TITLE
Child required modules not enabled when parent is enabled

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#36476]
### Preconditions and environment

Magento 2.4.2-p1

### Steps to reproduce

1. Create two new modules: `Vendor_One` and `Vendor_Two`
2. In the `module.xml` of `Vendor_Two`, set `Vendor_Two` to require `Vendor_One`:

```
 <module name="Vendor_Two" setup_version="1.0.0">
        <sequence>
            <module name="Vendor_One" />
        </sequence>
    </module>
```

3. Run `bin/magento module:enable Vendor_Two`

### Expected result

1. In the `app/etc/config.php`, both modules should be enabled (seeing how `Vendor_Two` requires `Vendor_One`):

```
+        'Vendor_One' => 1,
+        'Vendor_Two' => 1,
```

### Actual result

1. In the `app/etc/config.php`, only `Vendor_Two` is enabled:

```
+        'Vendor_One' => 0,
+        'Vendor_Two' => 1,
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alikhani97** [comment]
@magento give me 2.4-develop instance

**Comment by alikhani97** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
I'm not sure if the expected outcome is correct here.

The sequence in the `module.xml` file is a soft dependency and doesn't require those modules (`Vendor_One` in this case) to even be available or installed for the other module (`Vendor_Two`) to work.
It's mostly used to determine the order of certain code in modules to get loaded/executed but it's really not a hard dependency that needs to be there.

**Comment by engcom-Hotel** [comment]
Hello @nbennett25,

Thanks for the reporting and collaboration!

I agree with @hostep for this https://github.com/magento/magento2/issues/36476#issuecomment-1320919275. This is a soft dependency not hard as explained in this [document](https://developer.adobe.com/commerce/php/architecture/modules/dependencies/). 
> Example: Module A declares a dependency upon Module B. Thus, in Module A's module.xml file, Module B is listed in the <sequence> list, so that B's files are loaded before A's. Additionally, you must declare a dependency upon Module B in A's composer.json file. Furthermore, in the [deployment configuration](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/files/deployment-files.html), **Modules A and B must both be defined as enabled**.

Hence this seems to us an expected behavior.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nbennett25,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
