### ISSUE TITLE
Show category based widget content/ static block 

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#36470]
### Summary

I have created once widget as static block and add layout update for specific page --> catalog category page and layout update **before page footer** it working fine and showing block on all category pages as as excepeted. Now i want to show one block which can show when any once browser category 1 from navigation and it will be showing before block which showing on all category. can any once help to implement this kind of customisation 

### Examples

![image](https://user-images.githubusercontent.com/2478037/201634381-56a4fe4e-c966-4414-ab09-db9f75e72022.png)
below screenshot added but it always showing before footer tried with sort order but not working 
![image](https://user-images.githubusercontent.com/2478037/201634625-93363255-ede9-48d8-95e8-e16348bb4b69.png)

### Proposed solution

Can any one provide steps to achieve that

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @hemendraajmera,

Thanks for the collaboration!

We are using this board to tackle the bugs/issues facing in Magento but it seems that this is something related to a query on functionality. So I request you to please use [Magento Stackexchange](https://magento.stackexchange.com/) for these kinds of queries.

Thanks
