### ISSUE TITLE
Some errors after changing Locale Options->Locale.

### ISSUE THREAD

**Issue by AlexSeyFomin** [magento/magento2#3648]
I tried to change Local configuration in admin side. I changed this settings from English(United States) to Ukrainian(Ukraine).
![image](https://cloud.githubusercontent.com/assets/16902841/13522941/0bbe4360-e1fb-11e5-9e52-51ff08877884.png)
But I have some trouble after that. Magento don't create a folder pub/static/frontend/[vendor]/[theme]/uk_UA/. 
I got this result:
![image](https://cloud.githubusercontent.com/assets/16902841/13523133/46ca21f8-e1fc-11e5-92a6-359dd0b63805.png)
Tell me, please , why Magento does not create this folder after changing this setting and how i can fix it?
I tried to do command "setup:static-content:deploy" in command line, but this didn't help.

**Comment by katmoon** [comment]
Hi @AlexSeyFomin 

Thank you for reporting the issue.

I tried to reproduce the problem, but `uk_UA` folder has been successfully created.
Maybe there is a problem with file permissions? Please check http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

Are there any related errors in `error_log` or `magento/var/log` folder?

**Comment by AlexSeyFomin** [comment]
Thank you for your answers! I will try to fix this problem later and write here after that.

**Comment by piotrekkaminski** [comment]
Not able to reproduce. If issue persists in 2.1, please open a new issue.
