### ISSUE TITLE
Default Value being duplicated it attribute edit 

### ISSUE THREAD

**Issue by ssx** [magento/magento2#36486]
### Preconditions and environment

- 2.4.5-p1

![image](https://user-images.githubusercontent.com/254889/202429181-9cb6972d-642c-42ca-8298-485bf56ad8ca.png)

### Steps to reproduce

1. Create a text attribute
2. Run setup:upgrade
3. Edit attribute in panel
4. Two default values appear

### Expected result

Only a single default value field appears.

### Actual result

Two default value fields appear, one being a datepicker.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @ssx,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
