### ISSUE TITLE
Magento Community Edition: Version 2.4.5 - Date Picker design getting disturb

### ISSUE THREAD

**Issue by RocktechnolabsDev** [magento/magento2#36499]
### Preconditions and environment

1. Magento Community Edition 2.4.5 without sample data is installed.
2. Login into admin > Marketing > Cart Price Rules
3. Click on date picker of start column in grid, Select the date from date picker, After selecting the date "Date selector" text visible instead of calendar icon.

### Steps to reproduce

1. Login into admin > Marketing > Cart Price Rules
2. Click on date picker of start column in grid, Select the date from date picker, After selecting the date "Date selector" text visible instead of calendar icon.

![Before](https://user-images.githubusercontent.com/118173578/203019396-71dfa22e-5d1d-4e96-9bba-6cb09f6d8ef5.png)

![After](https://user-images.githubusercontent.com/118173578/203019390-b133e8f1-e72a-4b30-8a47-8217ab596bde.png)

### Expected result

After selecting date from the date picker, calendar icon should be visible over there.

### Actual result

After selecting date from the date picker, "Date selector" text visible instead of calendar icon.

### Additional information

![After](https://user-images.githubusercontent.com/118173578/203019307-ae560627-c5cd-488d-b869-baf7ec019982.png)
![Before](https://user-images.githubusercontent.com/118173578/203019315-17195fdc-a775-4836-8276-81610359b42e.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @UtsavRock1811,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to Reproduce** :

1.Login into admin > Marketing > Cart Price Rules
2.Click on date picker of start column in grid, Select the date from date picker.



After selecting date from the date picker, "Date selector" text visible instead of calendar icon.



<img width="1359" alt="Screenshot 2022-11-21 at 5 06 34 PM" src="https://user-images.githubusercontent.com/51680745/203041966-e1c9bd6e-42b4-4905-b9f9-ab89c2075c1f.png">



Hence Confirming this issue.

Thanks.

**Comment by rostilos** [comment]
@magento I am working on this

**Comment by pradeep1819** [comment]
Internal team is working on it.

**Comment by hostep** [comment]
@pradeep1819: this issue got closed without an explanation telling why? The [associated PR](https://github.com/magento/magento2/pull/36579) didn't get merged yet, so was this issue closed correctly and can you explain why it got closed?

**Comment by developerjob4** [comment]
[CalendarIconIssue.zip](https://github.com/user-attachments/files/18057732/CalendarIconIssue.zip)
this module will clear the calendar icon bug issue in magento 2.4.6 version we can use patch to clear this method also its an another way to clear this issue
