### ISSUE TITLE
B2B module in ECE - Purchase order module - Company admin not able to place the order.

### ISSUE THREAD

**Issue by Shaikh-Samir** [magento/magento2#36508]
### Preconditions and environment

Magento version 2.4.5-p1
PHP 8.1 (FPM)
Apache2.4
Ubuntu 20.04.5 LTS

### **Configuration part for B2B purchase order**
1. Login to admin panel
2. Go to "Stores >> Configuration >> General >> B2B features >> B2B features >> Enable Company(Set to **YES**)".
3. Go to "Stores >> Configuration >> General >> B2B features >> Order approval configuration >> Enable Purchase Order(Set to **YES**)".
![Image1](https://user-images.githubusercontent.com/117074683/203337294-0d4be82f-d4b0-442d-a86a-339c1663ee38.png)

### **Configuration part for Persistent shopping cart**
1. Login to admin panel
2. Go to "Stores >> Configuration >> Customers >> Persistent Shopping Cart >> Enable Persistence(Set to **YES**)".
3. Add New Integration.
4. Fill up require fields but fields "Callback URL" and "Identity link URL" leave empty and Save.
5. Now error displaying as mentioned in below attachment
![Image2](https://user-images.githubusercontent.com/117074683/203337345-2325aad9-f592-4473-9ba4-3c82e75d7b09.png)

### Expected result

Company admin should be able to place the order from its front-end account.

### Actual result

Facing error at front-end while placing an order via company admin account **"Invalid customer address id 591287"**.

![Image3](https://user-images.githubusercontent.com/117074683/203339689-2823c86b-b5db-437e-bb9d-aa6bf73a7358.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Shaikh-Samir** [comment]
Hello @engcom-Dash 

Thank you for your response.
We have prepared step-wise document to reproduce this issue with screen shots of admin configuration, company account settings, order placement flow, company admin and user accounts at store front. 
So please refer those steps to produce the PO order related error, which is currently i am facing.

[Reproduce-Step-PO-Order.pdf](https://github.com/magento/magento2/files/10081646/Reproduce-Step-PO-Order.pdf)


Thanks.

**Comment by engcom-Dash** [comment]
Hi @Shaikh-Samir ,

We worked as per the documents...we got the same results
Here I attached the screenshots for your reference.
Magento version 2.4-develop 
PHP 8.1
<img width="1512" alt="Screenshot 2022-11-30 at 9 03 35 AM" src="https://user-images.githubusercontent.com/60198592/204709190-47b20fa2-7d4d-40f4-b0c4-7ee44f02094b.png">
<img width="1512" alt="Screenshot 2022-11-30 at 9 03 41 AM" src="https://user-images.githubusercontent.com/60198592/204709232-bdd783b2-e2af-4c20-8450-edc33b4f31f7.png">
<img width="1512" alt="Screenshot 2022-11-30 at 9 04 17 AM" src="https://user-images.githubusercontent.com/60198592/204709266-ffdaff45-c8a4-49a1-aeb5-5f791ac41a41.png">
<img width="1512" alt="Screenshot 2022-11-30 at 9 06 02 AM" src="https://user-images.githubusercontent.com/60198592/204709277-d29369bb-0c62-43bd-9eed-e89f8dec2883.png">
<img width="1512" alt="Screenshot 2022-11-30 at 9 12 03 AM" src="https://user-images.githubusercontent.com/60198592/204709284-354afc05-0e92-4f6e-b324-40f074d5cc79.png">
<img width="1512" alt="Screenshot 2022-11-30 at 10 10 13 AM" src="https://user-images.githubusercontent.com/60198592/204709312-32431bd1-7c6d-47a4-8e70-d2896940e6a9.png">

**Comment by engcom-Dash** [comment]
Hi @Shaikh-Samir ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
