### ISSUE TITLE
Downloading Error in repository of Paradoxlabs Magento 2

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#36505]
### Summary

Magento Version: Magento ver. 2.3.5-p2
Paradox Current Version Installed in ProWorld: 4.5.0

![deploy-error](https://user-images.githubusercontent.com/71755795/203264095-81628acd-413c-47e2-bb07-93f8c237419d.png)

### Examples

Error:

https://repo.magento.com/archives/paradoxlabs/tokenbase/paradoxlabs-tokenbase-4.5.1.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found) 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @thinksys-dev ,
Thank you for reporting and collaboration. "paradoxlabs" is a 3rd party package / library that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Comment by thinksys-dev** [comment]
Hi Team,
Thanks for the reply.
But the zip file is trying to download from repo.magento.com https://repo.magento.com/archives/paradoxlabs/tokenbase/paradoxlabs-tokenbase-4.5.1.0.zip.

The ParadoxLabs extension is on marketplace and during composer install it pulls the zip file from Magento, which is clearly showing in the error , zip file is not available in repo.magento.com end.

Please look and suggest. Thanks
