### ISSUE TITLE
Cannot Uninstall Luma theme

### ISSUE THREAD

**Issue by bsuresh** [magento/magento2#3650]
We are in process of creating our base theme. We are looking at removing Luma theme followed the steps (http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-theme-uninstall.html)

We can't seem to un-install Luma theme, this is a fresh Magento installation on vagrant box.
`$ php bin/magento theme:uninstall frontend/Magento/luma

Unable to uninstall. Please resolve the following issues:
frontend/Magento/luma is a parent of physical theme. Parent themes cannot be uninstalled.
frontend/Magento/luma has the following dependent package(s):
    magento/product-community-edition`

**Comment by mazhalai** [comment]
@bsuresh Thank you for reporting, we have created MAGETWO-50182 to track and fix it.

**Comment by devdesco-ceo** [comment]
You have to manually remove all */Luma/* directories and then run /bin/magento setup:upgrade and redeploy all static content!

**Comment by alankent** [comment]
A part of the challenge is to make deployment simple, we have a composer metapackage that points at everything to download. This includes the Luma theme. For modules it is not a problem, because you can turn off modules (via config.php). But there currently is not a switch to turn of themes, causing problems like this. The sample data modules are optional and can be easily omitted, but the Luma theme itself is not. I suspect this is why the CLI uninstall theme command is not working - I don't think Luma is an additional optional theme added to the composer.json file, so the CLI command cannot remove it. Maybe that is the problem and solution - move the Luma theme to be an extra module, just like the sample data. Then its easy to make optional.

**Comment by devdesco-ceo** [comment]
Always keep in mind - Magento is owned by eBay :(

**Comment by devdesco-ceo** [comment]
and remove the reference entry in themes table in db

**Comment by alankent** [comment]
Not sure what you meant by "Magento is owned by eBay" exactly, but to be clear - we are NOT owned by eBay since November last year. We are Magento Commerce, a separate company. We are still going through separation efforts, but company focus is now all about Magento.

**Comment by devdesco-ceo** [comment]
Nice, good to know! I just have person affection towards eBay. :-1:

**Comment by antboiko** [comment]
@bsuresh 

Hello Suresh, sorry for the delay with response. 
Could you please verify if your created theme is inherited from Luma? If yes, then according to [DevDocs](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-theme-uninstall.html) you should first update the parent node information in theme.xml to remove references to Luma before uninstall.

Thanks,
Anton.

**Comment by slavvka** [comment]
Closing since the author didn't answered

**Comment by hostep** [comment]
This is still an issue.

If you install Magento 2.1-rc1 (sorry, haven't had a chance to play with rc2), change the settings to use the 'blank' theme, and then try to remove the luma theme:

``` sh
$ php bin/magento theme:uninstall frontend/Magento/luma
Unable to uninstall. Please resolve the following issues:
frontend/Magento/luma has the following dependent package(s):
    magento/product-community-edition
```

Although I'm not sure if you should be able to remove themes which come with Magento 2 built-in, since this command is actually removing files (if I understand the docs correctly?). And this will probably cause issues, because a Magento upgrade will put those files back into place.

So I don't think you should be able to remove built-in themes from Magento 2. If the Magento team agrees with this, you can keep the ticket closed. Otherwise, you'll have to re-open it :)

**Comment by makeagency** [comment]
still an issue in rc3. very annoying.

**Comment by ClaudiuCreanga** [comment]
still and issue in rc3. very annoying.

**Comment by 4DallasC** [comment]
Yeah, I'm with ClaudiuCreanga above, having to sit through the deployment of the Luma frontend every time I'm forced to re-deploy static after an upgrade, is very annoying.

I can see why the frontend/Magento/blank would be a dependency, but can't see why the frontend/Magento/luma is a dependency.

**Comment by MomotenkoNatalia** [comment]
Hi guys!
Looks like we already have internal task for this - MAGETWO-49510

**Comment by 4DallasC** [comment]
Hello @MomotenkoNatalia 

While you're at it. When we select the site language in the "Locale Options" in the system configurations to Locale "English (Australia)", it changes the site language to en_AU in the frontend but the admin is still in en_US. This means we need to deploy both en_AU and en_US, the en_AU for the frontend and the en_US for the backend. This takes along time, and if we can't change the backend language, why not only deploy the backend in en_US regardless of the locale setting.

Also, when changing the developer settings to minimizes the css, the delopyment process does create the css with the filename <name>.min.css, but when the site render the html <link> in the page, it has the normal filename  <name>.css. This causes problems.

**Comment by 4DallasC** [comment]
Hello @slavvka 

Also as a side note, the upgrade/deployment/compilation process can take considerable time. For production systems that also compile the code, it's taking nearly/over an hour to complete.

Can you make the deployment process to enter the developer mode rather than the maintenance mode, where the site can operated with the raw css/less and without the generated/compiled files while the deployment/compilation process is completing? 

Pulling down a production system for over an hour to update it is just too long.

**Comment by ClaudiuCreanga** [comment]
@4DallasC  you can change the locale of the admin theme quite easily with a module. I think it is desired to have a default locale for backend. I don't know why it would take that much for you, but for us it takes 10 minutes to run tests and deploy.

**Comment by quisse** [comment]
Any update on this?

**Comment by george-vlahakis** [comment]
Yeah, still there in 2.1.6. Should we be following @viktor-zhuromskyy  instructions for now?

**Comment by ChaerilM** [comment]
if someone still want to uninstall it, 
- open vendor/composer/installed.json
- remove package "magento/theme-frontend-luma": "100.1.6" inside "magento/product-community-edition" require.
- php bin/magento theme:uninstall frontend/Magento/luma

```
Enabling maintenance mode
Removing frontend/Magento/luma from database
Removing frontend/Magento/luma from Magento codebase
<warning>magento/theme-frontend-luma is not required in your composer.json and has not been removed</warning>
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing magento/theme-frontend-luma (100.1.6)
Removing Magento/ThemeFrontendLuma
<warning>Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.</warning>
Writing lock file
Generating autoload files

Cache cleared successfully.
Alert: Generated static view files were not cleared. You can clear them using the --clear-static-content option. Failure to clear static view files might cause display issues in the Admin and storefront.
Disabling maintenance mode
```

the warning pique my interest, but when i re-run the command i got unknown theme. hopefully it leave no trace 😃

**Comment by quisse** [comment]
In 2.1.7 it returns following output when running the steps from @Zabanya 
```
Enabling maintenance mode
Removing frontend/Magento/luma from database
Removing frontend/Magento/luma from Magento codebase
Command "remove" failed: <warning>You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug</warning>
<warning>magento/theme-frontend-luma is not required in your composer.json and has not been removed</warning>
Loading composer repositories with package information

Removal failed, reverting ./composer.json to its original content.


                                                                             
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  
                                                                             


remove [--dev] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [packages1] ... [packagesN]



Please disable maintenance mode after you resolved above issues
```
update -> found a workaround: after this error
* run `composer remove magento/theme-frontend-luma` manually
* (optional) `n98-magerun2 config:set design/theme/theme_id 1`
* clean cache `php -f bin/magento cache:clean`
* disable maintenance mode `php -f bin/magento maintenance:disable`

**Comment by magento-engcom-team** [comment]
@bsuresh, thank you for your report.
We've created internal ticket(s) MAGETWO-50182 to track progress on the issue.

**Comment by treii28** [comment]
also interested in this. We are using a custom theme (thus luma is just taking up space and deploy time) and the comments about production pull-down to re-deploy static content applies here also. (I also wondered why it can't do it into a separate filespace to avoid going into maintenance mode)

**Comment by hostep** [comment]
@treii28: regarding deploy time, if you have a recent Magento version, you can choose to only deploy your own custom theme and the admin theme, so you avoid deploying themes which you don't use (Magento/blank, Magento/luma), something like this should work:
```
bin/magento setup:static-content:deploy --theme Magento/backend en_US
bin/magento setup:static-content:deploy --theme Vendor/custom-theme en_US de_DE nl_NL fr_FR
```

It has the added benefit of only deploying languages you want to use for those themes (for example: we only allow English in the backend), this also helps in reducing deploy time and space it takes.

Be sure to check out all flags which you can pass to that command, maybe some other useful stuff for you is in there: `bin/magento setup:static-content:deploy --help`

**Comment by VaporFan** [comment]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
    - magento/product-community-edition 2.3.0 requires magento/module-wishlist 101.1.0 -> satisfiable by magento/module-wishlist[101.1.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - temando/module-shipping-m2 1.4.6 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - temando/module-shipping-m2 1.4.0 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - temando/module-shipping-m2 1.4.1 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - temando/module-shipping-m2 1.4.2 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - temando/module-shipping-m2 1.4.4 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - temando/module-shipping-m2 1.4.5 requires magento/module-catalog ^103.0.0 -> satisfiable by magento/module-catalog[103.0.0].
    - magento/module-catalog 103.0.0 requires magento/module-wishlist 101.1.* -> satisfiable by magento/module-wishlist[101.1.0] but these conflict with your requirements or minimum-stability.
    - Installation request for temando/module-shipping-m2 ^1.4 -> satisfiable by temando/module-shipping-m2[1.4.0, 1.4.1, 1.4.2, 1.4.4, 1.4.5, 1.4.6].

I got this

**Comment by radulff** [comment]
Has this been fixed? I'm trying to remove the theme in 2.2.6 and I'm having the same issue. 

You can see here as none of our child themes depend on Luma Theme.

![image](https://user-images.githubusercontent.com/39625379/66040288-5d124e00-e517-11e9-8c07-ab70bcb10a4f.png)

Thank you

**Comment by ericmorand** [comment]
3 years later and this bug has still not bee fixed. Isn't it just a matter of removing the dependency and add the theme as a suggestion in composer.json?

**Comment by PsmIndia** [comment]
Still same issue, when we add product it create unnecessary copy of product images in cache because of that its create disk space.

**Comment by hostep** [comment]
@PsmIndia: product images have nothing to do with the static content deployment procedure, right?

Also: what Magento version are you using? I'm pretty conviced that on the latest versions, Magento no longer generates resized product images for themes you don't use.

**Comment by PsmIndia** [comment]
i using magento 2.3.4[updated, move from m1], i have 50K products, when i try to do duplicate a products its take in infinite loop, until server crash, also its increase disk space, try to find solution but i am not, so setup it my local system and and i deleted all products, only keep 500 products, also i deleted all images too, now i try to make duplicate its successful, so now i add a product image, after than i check `pub\media\catalog\product` there in cache dir, there 18 images created+1=19 total , a single product images copies 19 time, what about 50K? i think it was becouse of unused theme that are install with setup ? right?

**Comment by hostep** [comment]
For the duplicate issue, you are probably running into https://github.com/magento/magento2/issues/9466 which is supposed to get fixed in Magento 2.4.0

You can ignore those lines in your log file, they have to do with cache invalidation which is expected and not a problem.

The 18 or 19 resized images you are noticing probably come from the `etc/view.xml` file of your custom theme, here's an example: https://github.com/magento/magento2/blob/2.3.5/app/design/frontend/Magento/blank/etc/view.xml
Magento resizes images in all the different formats specified in that file, since it needs different resized images on various parts in your shop. You can try to change those image dimensions to all use the same width and height in that file, that should reduce the amount of resized images it generates.

I'd strongly recommend to further look for help on https://magento.stackexchange.com/ or on https://community.magento.com/, because this issue you are having doesn't appear to be related to trying to remove the luma theme from a Magento installation.

Good luck! 🙂

**Comment by eduard13** [comment]
@magento I'm working on it

**Comment by eduard13** [comment]
@magento I’m working on this

**Comment by eduard13** [comment]
@magento I’m working on this

**Comment by eduard13** [comment]
@magento I am working on this

**Comment by hostep** [comment]
Untested, but you can probably remove the luma theme using a composer trick:

1. Add the following to your `composer.json` file, or merge it in the already existing `replace` section:
```json
    "replace": {
        "magento/theme-frontend-luma": "*"
    }
```
2. Run `composer update magento/theme-frontend-luma`
3. Run `bin/magento setup:upgrade`

This might work, but as mentioned above, I haven't actually tested this.

**Comment by schizek** [comment]
This is still an issue in Magento 2.4.3-p1
