### ISSUE TITLE
magento 2.0 admin panel loading slowly and the sublink buttons are not working after merging css and js files

### ISSUE THREAD

**Issue by neelimabenapally** [magento/magento2#3651]
-Smartwave porto is installed on magento 2.0 
-After the merging the css and js files in adminpanel the admin panel is loading slowly and all the sublink buttons (sales,products,customers,etc) are not working
-When checked in the apache errors log 
File does not exist: /usr/local/apache/htdocs/home/public_html/pub/static.php, referer: 
 client denied by server configuration: /home/public_html/app/etc/config.php

**Comment by matthieusibille** [comment]
Hello,
you have to redeploy static files
command : php bin/magento setup:static-content:deploy

**Comment by neelimabenapally** [comment]
Hi Matt,

I ran that command the frontend files are all deployed correctly but for
the backend only magento is being deployed the smartwave is not being
deployed for backend.

Many Thanks,
Neelima

**Comment by matthieusibille** [comment]
Check your browser debug to see which files are missing.
Also, clean/flush your cache
php bin/magento cache:clean
php bin/magento cache:flush

**Comment by neelimabenapally** [comment]
/Magento/backend/en_US/requirejs/require.min.js Failed to load resource:
the server responded 404 error and there are other 404 errors
 there are few files missing 
i redeployed the static content and flushed/cleaned the cache but still there are files missing

**Comment by npearson72** [comment]
+1

Having the same issue. When I minify merge the css, admin (and front end) run really slow. Have redeployed static content, flushed cache, etc. Still slow.

I'm on 2.0.4

**Comment by vigentocommerce** [comment]
too slow. Magento 2.0.4 on Xampp, 8GB ram, 250 GB SSD, server case.

**Comment by stevekem** [comment]
Having same issue... When merge JS/CSS are enabled, the frontend and backend are loading 10-20 times slower, 30 secs a page load (cached). Running 2.0.4 and redeployed static content, flushed cache as well.

**Comment by shashankitsoft** [comment]
+1. I am having the same issue. I have once enabled merging JS/CSS, the issue happened, too much slow, tried everything. Finally had to do reinstall fresh magento 2.0.4. Weird!

The new magento  installation worked fine for few days, never enabled js/css merging again bcoz of fear hat it may cause issue again. But now it again became too slow... checked apache error log...
These errors are coming... 
`[access_compat:error] [pid 2336:tid 1088] [client 127.0.0.1:57098] AH01797: client denied by server configuration: E:/wamp/www/mymagento/app/etc/config.php`

I am working on magento 2.0.4 on WAMP 3.0 on windows 10 Pro 32 bit, PHP 5.6.15, My SQL 5.7.9.
My localhost base url is: http://127.0.0.1:8080/mymagento/

**Comment by sbwcws** [comment]
After enabling merge javascript and css.. Magento 2.05 is extremely slow even If I try to buid static content it says time out or execution time over limit or something where as I increase the limit but same thing, Is M2 really ready for LIVE Store ???

**Comment by pboisvert** [comment]
@choukalos can you have Oleh and team check into this?

**Comment by mazhalai** [comment]
@npearson72 @vigentocommerce @stevekem @shashankitsoft @sbwcws 
- firstly, please do not post on already closed issues. 
- secondly, Magento does not support windows, only [Linux](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html).  
- for speed, have you setup [Varnish](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html) as recommended?

**Comment by npearson72** [comment]
Should we open a new ticket to respond to your questions?

Anyway, you're welcome for the feedback.

**Comment by mazhalai** [comment]
@npearson72 please open a new ticket if it is a bug. However, if you simply looking for a discussion, the proper forums are http://magento.stackexchange.com/ and https://community.magento.com/

**Comment by stevekem** [comment]
I currently have a ticket open for this same or very similar issue here:

https://github.com/magento/magento2/issues/4321

**Comment by stevekem** [comment]
Also Nexcess support confirmed this issue was a bug as they spent alot of time recently troubleshooting why our site was literally crawling when merge css was enabled.

**Comment by frshjb373** [comment]
@stevekem, what was the bug and how did it get resolved? Having same issue.

**Comment by stevekem** [comment]
@frshjb373 Yes I believe this bug was fixed here https://github.com/magento/magento2/issues/4710
