### ISSUE TITLE
SOAP API catalogProductReturnEntity.additional_attributes does not support array values

### ISSUE THREAD

**Issue by JKCode** [magento/magento2#3652]
Using magento v2 Soap API - WS-I compliance is OFF.

Client is built with .NET.
Trying to retrieve additional product attributed with catalogProductInfo:

I am unable to retrieve some attributes because the additional_attributes field is an array of associativeEntity objects. An associativeEntity can only hold one value.

However some attributes (e.g. category_id) can have more than one value. For such items the return value should be an array. If I examine the result for the category_id attribute I see a literal string "Array" instead of an actual array of category id's that a product is assigned to.

How do I obtain the correct values for mult-value attributes such as category_id?

**Comment by piotrekkaminski** [comment]
This question is a better fit for magento.stackexchange.com
