### ISSUE TITLE
Bug css cart-summary in cart

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3653]
Sometimes, there is this problem in cart

I have Magento 2.0.2
Theme Luma, not custom theme

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/13524764/8b39b488-e1fd-11e5-8c7b-38196a5427eb.jpg)

**Comment by ishakhsuvarov** [comment]
@quienti Thank you for reporting this issue.
We have already fixed it in the `develop` branch, fix will be available in the future releases.
Meanwhile you may use commit [`48d9643`](https://github.com/magento/magento2/commit/48d9643a0188807cca645e969c7752e60a7b174f) as a hotfix.

**Comment by quienti** [comment]
Oh! Sorry

Thank you for your answer
