### ISSUE TITLE
[Cart Rule] Incorrect fixed discount amount applied for bundle products

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#36532]
### Preconditions and environment

- Magento 2.4.3-p3 (not tested on newer versions)

### Steps to reproduce

1. Install Magento 2.4.3-p3 with sample data
2. Create cart rule with "Fixed amount discount" action (e.g: 10€) with or without a coupon code
3. Add a bundle product to cart (e.g: the `Sprite yoga companion kit` sample product with its default options)
4. Go to the cart
5. [OPTIONAL] If a coupon code was used in the step 2, add this coupon to the cart

### Expected result

1. The discount amount should be of 10€ only

### Actual result

1. The discount amount is applied to each product of the bundle product at the maximum limit of their original price, which, in the example bellow, is 35€ because of the amounts of the simple products that are part of the bundle (10€ for the 23€ product + 5€ for the 5€ product + 10€ for the 19€ product).

![image](https://user-images.githubusercontent.com/3015249/204014785-8c574807-b99d-4449-b370-23527a73d199.png)

### Additional information

The issue is similar to this one : https://github.com/magento/magento2/issues/30952 but the action is the "Fixed amount discount", not the "Fixed amount discount for whole cart".

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Axel29** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-November** [comment]
Hi @Axel29,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible for bundle products created with multiple options with Ship bundle Items set as "Separately" and is not reproducible for single option with multiple products.
As per magento [docs](https://docs.magento.com/user-guide/v2.3/marketing/price-rules-cart-create.html), Fixed amount discount discounts  fixed amount from the original price of each qualifying item in the cart separately. Kindly check the documentation and check the behavior on Magento 2.4-develop instance as it is having latest code base and let us know your inputs.
Thank you.

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4.2-p2 instance
