### ISSUE TITLE
Return Type Should be string, null returned Error

### ISSUE THREAD

**Issue by sprajapat770** [magento/magento2#36546]
### Summary

As Per Magento Code Written in vendor\magento\framework\Mail\MimePartInterface.php and vendor\magento\framework\Mail\MimePart.php is not appropriate.

In MimePart.php constructor magento has used null as default parameter like  ?string $disposition = null, ?string $description = null, etc but the the encapsulated functions return type is specified only for string in responsible interface and class, and that is returning return type error in case external object parameters set.

### Examples

Constructor Code that accept null type
<img width="556" alt="aa" src="https://user-images.githubusercontent.com/57035224/204358388-f7861fb3-2076-47a8-af17-d7094b344193.png">

function type that return only string type whether accept null type.

<img width="530" alt="bb" src="https://user-images.githubusercontent.com/57035224/204358474-1e600b3e-dce6-4fbc-8245-82a686429789.png">

### Proposed solution

patch 1 : 

diff --git a/vendor/magento/framework/Mail/MimePartInterface.php b/vendor/magento/framework/Mail/MimePartInterface.php
--- a/vendor/magento/framework/Mail/MimePartInterface.php
+++ b/vendor/magento/framework/Mail/MimePartInterface.php
@@ -30,21 +30,21 @@
      *
      * @return string
      */
-    public function getDisposition(): string;
+    public function getDisposition(): ?string;

     /**
      * Get description
      *
      * @return string
      */
-    public function getDescription(): string;
+    public function getDescription(): ?string;

     /**
      * Get filename
      *
      * @return string
      */
-    public function getFileName(): string;
+    public function getFileName(): ?string;

     /**
      * Get charset
@@ -58,21 +58,21 @@
      *
      * @return string
      */
-    public function getBoundary(): string;
+    public function getBoundary(): ?string;

     /**
      * Get location
      *
      * @return string
      */
-    public function getLocation(): string;
+    public function getLocation(): ?string;

     /**
      * Get language
      *
      * @return string
      */
-    public function getLanguage(): string;
+    public function getLanguage(): ?string;

     /**
      * Get Filters
@@ -86,7 +86,7 @@
      *
      * @return bool
      */
-    public function isStream(): bool;
+    public function isStream(): ?bool;

     /**
      * If this was created with a stream, return a filtered stream for reading the content. Useful for file attachment

patch 2: 

diff --git a/vendor/magento/framework/Mail/MimePart.php b/vendor/magento/framework/Mail/MimePart.php
--- a/vendor/magento/framework/Mail/MimePart.php
+++ b/vendor/magento/framework/Mail/MimePart.php
@@ -113,7 +113,7 @@
     /**
      * @inheritDoc
      */
-    public function getDisposition(): string
+    public function getDisposition(): ?string
     {
         return $this->mimePart->getDisposition();
     }
@@ -121,7 +121,7 @@
     /**
      * @inheritDoc
      */
-    public function getDescription(): string
+    public function getDescription(): ?string
     {
         return $this->mimePart->getDescription();
     }
@@ -129,7 +129,7 @@
     /**
      * @inheritDoc
      */
-    public function getFileName(): string
+    public function getFileName(): ?string
     {
         return $this->mimePart->getFileName();
     }
@@ -145,7 +145,7 @@
     /**
      * @inheritDoc
      */
-    public function getBoundary(): string
+    public function getBoundary(): ?string
     {
         return $this->mimePart->getBoundary();
     }
@@ -153,7 +153,7 @@
     /**
      * @inheritDoc
      */
-    public function getLocation(): string
+    public function getLocation(): ?string
     {
         return $this->mimePart->getLocation();
     }
@@ -161,7 +161,7 @@
     /**
      * @inheritDoc
      */
-    public function getLanguage(): string
+    public function getLanguage(): ?string
     {
         return $this->mimePart->getLanguage();
     }
@@ -177,7 +177,7 @@
     /**
      * @inheritDoc
      */
-    public function isStream(): bool
+    public function isStream(): ?bool
     {
         return $this->mimePart->isStream();
     }

### Release note

Code Corrections for Mail Event Object.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @sprajapat770,

Thanks for the reporting and collaboration!

We can see there are some changes happens in the below file:
https://github.com/magento/magento2/blob/ea0cf6395753078e45af8c4a5ddc1ea2c4d91092/lib/internal/Magento/Framework/Mail/MimePart.php#L49-L62

Can you please try to reproduce the issue in the latest 2.4-develop branch also please provide the below information also, this helps us in moving further with this issue:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results


Thanks

**Comment by sprajapat770** [comment]
@engcom-Hotel  @m2-community-project i think i have misunderstood the issue, i was explaining the functions return type should added null as well here. I was not taking about the constructor argument so please consider that as code fix issue.

**Comment by engcom-Hotel** [comment]
Hello @sprajapat770,

Thanks for the reply!

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @sprajapat770,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
