### ISSUE TITLE
[Magento 2.4.5-p1] Cannot add to cart

### ISSUE THREAD

**Issue by bernardinosousa** [magento/magento2#36545]
### Preconditions and environment

- Magento 2.4.5-p1
- Anything else that would help a developer reproduce the bug
- Using Luma/Blank theme
- Default Magento extensions.

### Steps to reproduce

  1. Navigate to storefront as a guest.
  2. Open simple product.
  3. Click “Add to Cart” on the Simple Product.
  4. Mini shopping cart doesn´t update.

### Expected result

Mini shopping cart updates and you can proceed to checkout.

### Actual result

Mini shopping cart doesn´t update and throws error 500 on console.

var/log/debug.log

[2022-11-28T17:01:01.248842+00:00] main.DEBUG: URI '/checkout/cart/add/uenc/aHR0cHM6Ly9kZXYubWFzcy5sb2NhaXMubmV0L2NoZWNrb3V0L2NhcnQvYWRkL3VlbmMvYUhSMGNITTZMeTlrWlhZdWJXRnpjeTVzYjJOaGFYTXVibVYwTDJOMWMzUnZiV1Z5TDJGalkyOTFiblF2Ykc5bmFXNHZjbVZtWlhKbGNpOWhTRkl3WTBoTk5reDVPV3RhV0ZsMVlsZEdlbU41TlhOaU1rNW9ZVmhOZFdKdFZqQk1NazVvWkVkR2MySXlZM1pqU0VwMldraFdhbVJET1RKaFYxWXpUREpzYTB4Nll6TlBSR04yU1ROS2JHUnRiR3hrZVRGdFlqTktkQzgsL3Byb2R1Y3QvNjczMC8,/product/20153/'' cannot be accessed with GET method (Magento\Checkout\Controller\Cart\Add) [] []
[2022-11-28T17:01:01.249423+00:00] main.DEBUG: Request validation failed for action "Magento\Checkout\Controller\Cart\Add\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at /var/www/html/public_html/vendor/magento/framework/App/Request/HttpMethodValidator.php:69)"} []

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bernardinosousa** [comment]
@magento give me 2.4-develop instance

**Comment by bernardinosousa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @bernardinosousa ,

we are trying to reproduce the issue in 2.4-develop instance we are not able to reproduce the issue.
we are getting expected result.
Steps:
1.Go to store front as a guest
2.add product to cart
3.proceed to check out
4.order placed successfully.
Screenshots:
<img width="1512" alt="Screenshot 2022-11-29 at 12 36 19 PM" src="https://user-images.githubusercontent.com/60198592/204462298-8fbfc974-14b7-45ba-954f-6dbcadc8c05e.png">
<img width="1512" alt="Screenshot 2022-11-29 at 12 37 34 PM" src="https://user-images.githubusercontent.com/60198592/204462338-14ccea28-6690-43e3-8620-1b037388e297.png">


Let us know if we are missing anything!

Thanks!!!

**Comment by drabikowy** [comment]
@magento give me 2.4.5 instance

**Comment by bernardinosousa** [comment]
Hi,
I realized the issue is related to my application, already tried with fresh installation and it is working.
I will be close this issue.
Thank you for the help.

**Comment by sb-bob-lessard** [comment]
@bernardinosousa - what was the issue that caused this issue? We have run into the same issue on our system.
