### ISSUE TITLE
[2.4.5-p1] Argument #1 ($fieldNode) must be of type GraphQL\\Language\\AST\\FieldNode, GraphQL\\Language\\AST\\InlineFragmentNode given

### ISSUE THREAD

**Issue by DuckThom** [magento/magento2#36544]
### Preconditions and environment

- Magento version: 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Create a product with the url key 'a-product'
2. Create a category with the url key 'a-category'
3. Run the following GraphQL query:

```graphql
fragment RouteFields on RoutableInterface {
    redirect_code
    relative_url
    type

    ... on ProductInterface {
        uid
        sku
        name
    }

    ... on CategoryInterface {
        uid
        name
    }
}

query Route {
    product: route(url: "a-product.html") {
        ...RouteFields
    }

    category: route(url: "a-category.html") {
        ...RouteFields
    }
}
```

### Expected result

The routes for the product and category are returned

### Actual result

A GraphQL error is returned along with the product data:

```
{
  "errors": [
    {
      "debugMessage": "Magento\\CatalogGraphQl\\Model\\AttributesJoiner::getQueryFields(): Argument #1 ($fieldNode) must be of type GraphQL\\Language\\AST\\FieldNode, GraphQL\\Language\\AST\\InlineFragmentNode given, called in \/Volumes\/Projects\/<redacted>\/magento\/htdocs\/vendor\/magento\/module-catalog-graph-ql\/Model\/AttributesJoiner.php on line 81",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 25,
          "column": 5
        }
      ],
      "path": [
        "category"
      ]
    }
  ],
  "data": {
    "product": {
      "redirect_code": 0,
      "relative_url": "a-product",
      "type": "PRODUCT",
      "uid": "NTg=",
      "sku": "533",
      "name": "A Product"
    },
    "category": null
  }
}
```

### Possible fix:

Replace the following line:

https://github.com/magento/magento2/blob/6dbb7fc48bd05eb2d00c9951b014aea9da7f73d7/app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php#L81

With this:

```
if ($spreadNode->kind === NodeKind::INLINE_FRAGMENT) {
    $fragmentFields[] = $this->addInlineFragmentFields($resolveInfo, $spreadNode);
} else {
    $fragmentFields[] = $this->getQueryFields($spreadNode, $resolveInfo);
}
```

I've marked it as S2 and S1 as it's critical when using GraphQL endpoints, but it's not critical when your shop doesn't make use of GraphQL.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @DuckThom,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Create a product with the url key 'a-product'
2.Create a category with the url key 'a-category'
3.Run the following GraphQL query:


<img width="1419" alt="Screenshot 2022-11-29 at 5 42 53 PM" src="https://user-images.githubusercontent.com/51680745/204540646-d901cae5-418a-45e4-9574-b213b24eade8.png">



Main Error in debug.log

<img width="1507" alt="Screenshot 2022-11-29 at 5 43 58 PM" src="https://user-images.githubusercontent.com/51680745/204540865-d92fc227-840b-4a17-9772-b402ca6b59b1.png">



Hence confirming this issue.

Thanks.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7114 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-7114&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks
