### ISSUE TITLE
Order print logo is too small

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#36548]
### Preconditions and environment

CE 2.4.3-p1

### Steps to reproduce

1. Set logos as specified in Sales > Sales > Invoice & Packing Slip Design
2. Print an order

### Expected result

Logo on PDF print is the same relative size as the logo on the HTML page used to generate the PDF:

![image](https://user-images.githubusercontent.com/13659750/204493459-9fc35c1a-c836-409c-932e-2109180ccc89.png)

### Actual result

Logo on actual PDF print is tiny:

![image](https://user-images.githubusercontent.com/13659750/204493665-2b3f6a7c-e2e5-468d-9551-d99e21485571.png)

### Additional information

Have tried using very large logo images in the config but makes no difference. Logo on the PDF print remains tiny. 

Have confirmed with dev tools that it is using the correct logo for the order print. This test with a very oversized image.

![image](https://user-images.githubusercontent.com/13659750/204494541-af0e8b22-9e78-437c-a135-8ba941d18733.png)

### Release note

Fix logo size on order print.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adamlavery** [comment]
@magento give me 2.4-develop instance

**Comment by adamlavery** [comment]
@magento give me 2.4-develop instance

**Comment by adamlavery** [comment]
Well this is poor!

**Comment by devchris79** [comment]
Hi Adam,

Have you checked that this is not theme related? The screenshot doesn't look like the Magento default layout.
I would check the theme for custom layouts:
https://magento.stackexchange.com/questions/304758/magento2-how-to-customization-of-the-invoice-pdf

**Comment by adamlavery** [comment]
Thanks @devchris79. I'm beginning to think it's the Porto theme but why I don't know. The item list format is custom for this site because of the nature of the products sold but otherwise standard.

What's confusing is using the dev tools rendering option to emulate CSS media type print it displays correctly. The rendered HTML from which the PDF is generated is correct but actually printing it then the logo shrinks as shown. Same happens when I use the default Porto logo (which is SVG). Happens in Edge, Chrome and Opera so not browser related.

Porto doesn't override print.less/css so print CSS comes from Magento core. I've added rules to accomodate the non-standard item columns and bunch the order info on one line, but that's all.

**Comment by adamlavery** [comment]
Appears this is not a Magento issue but something to do with Porto styling, but not specifically related to print styles. For anyone having the same problem with Porto, fix was to add the following to the child theme web\css\print.less:

```
    img {
        max-width: none !important;
        max-height: none !important;
    }

```

**Comment by devchris79** [comment]
Glad you have solved that.
We run Porto and its got a few "quirks", a big one is that email templates don't work in the latest version and need to be removed to fall back to Magento defaults.

**Comment by adamlavery** [comment]
Oh great - one to look forward to! Thought it was just Magento the breaks things between (even minor) releases.

Have to say, not very impressed with Porto - probably won't be using it again. Some of what they've done is a bit cowboy. Great chunks of styling in the media folder!? That's not best practice.
