### ISSUE TITLE
Customer group ID is null in the order

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#36542]
### Preconditions and environment

- Magento version 2.4.5
- php 8.1

### Steps to reproduce

1. Put some thing in the cart.
2. Complete the checkout process like anonymous user.

### Expected result

1) In the table 'sales_order_item' the field 'customer_group_id' should be 0 by default value.

### Actual result

In the table 'sales_order_item' the field 'customer_group_id' is null.

### Additional information

This is comdition always is true because $customer is object.

![image](https://user-images.githubusercontent.com/18437080/204286714-0c497cfb-093b-4612-b8e9-4d9b72852d8e.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @sgeleon,

Thank you for reporting and collaboration.

Similar Issue found here https://github.com/magento/magento2/issues/36514 .Issue is not reproducible in magento `2.4 develop`.


Kindly move on to this issue for latest updates / solutions on the same.

Hence we closing this as a duplicate.

Thanks.
