### ISSUE TITLE
Foreign key constaints cannot be updated if corresponding source column is updated within an Magento update

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#36552]
### Preconditions and environment

- Magento version 2.4.3-p2
- A `db_schema.xml` with a column that has a foreign key reference to `sales_order`:`increment_id`
- Upgrade to Magento 2.4.5-p1

### Steps to reproduce

1. Install a Magento 2.4.3-p2 demo instance
2. Create a custom module with a `db_schema.xml` with this content:
```xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
    <table name="example_table">
        <column xsi:type="varchar" name="order_increment_id" nullable="true" length="32" comment="Order ID"/>
       
        <constraint xsi:type="foreign"
                    referenceId="EXAMPLE_TABLE_ORDER_INCREMENT_ID_SALES_ORDER_INCREMENT_ID"
                    table="example_table" column="order_increment_id"
                    referenceTable="sales_order" referenceColumn="increment_id"
                    onDelete="NO ACTION"/>
    </table>
</schema>
```
3. Execute `bin/magento setup:upgrade`
4. Perform an upgrade to Magento 2.4.5-p1
5. As part of the upgrade, you change "length="32"" in the above db_schema.xml to "length="50"" as the source column in sales_order also changed from 32 to 50
6. Execute setup:upgrade

### Expected result

setup:upgrade runs through, our custom column now is varchar(50) and the foreign key also still exists

### Actual result

setup:upgrade fails with the error `Failed to add the foreign key constaint. Missing index for constraint` because the source table's (sales_order) column "increment_id" already got updated to varchar(50) but our custom table's column still is varchar(32), therefor the index cannot be updated/created.

### Additional information

If you comment out the `<constraint>`, run `bin/magento setup:upgrade`, re-add the `<constraint>` and execute `bin/magento setup:upgrade` again, everything works fine. But this scenario cannot be used on an automatic deployment system, especially if you have several environments to deploy to with different deployment schedules (or multiple developers which need to upgrade their dev instances too, whenever they want).

*Workaround (which is not satisfying at all)*: Do not use constaints to `sales_order`:`increment_id` within a time range of 1 month after the upgrade to 2.4.5-p1. After 1 month re-add the constaint. Every environment should hopefully be upgraded until then and should not trigger any errors. But without fixing this issue globally, this could happen to custom columns depending on to-be-changed core columns in future upgrades as well.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sippsolutions** [comment]
Hi @engcom-Hotel,

seems you did everything like me, but got another error (Error 2), which is strange but imo still meets the topic of the issue - that you cannot upgrade to 2.4.5-p1 without removing the foreign key first, and re-introducing it later.

When I look at Error 2 this also seems like (your instance of) Magento wanted to change AND add the constraint, which seems to be an additional bug.

Did you have a `db_schema_whitelist.json` present?

**Comment by sippsolutions** [comment]
Hi @engcom-Hotel,

the `db_schema_whitelist.json` already existed in my 2.4.3-p2 instance pre-upgrade.

**Comment by engcom-Hotel** [comment]
Hi @sippsolutions,

We have again tried to reproduce the issue by creating `db_schema_whitelist.json` before the upgrade. After upgrading we are not facing the issue mentioned in the main description.

It might be something that has been missed in the steps for reproduction.

Thanks

**Comment by engcom-Hotel** [comment]
Dear <user>,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
