### ISSUE TITLE
Mview iterator (index schedule)

### ISSUE THREAD

**Issue by vicobohdan** [magento/magento2#36557]
### Preconditions and environment

- Magento version: 2.4+

### Steps to reproduce

\Magento\Framework\Mview\View::executeAction is not optimal, main while loop iterate always over batch size (`$vsFrom += $batchSize;`). But `$walker` return uniq ids from _cl table, where ids are always duplicated multiple times. It's not a problem when there are a few products in the backlog, but if there are hundreds or thousands (in some cases...) it results in a drastic performance drop =>` $action->execute($ids)` recalculates the same product more times...

example: in backlog are 100 uniq products, but in _cl table are 10000 records: while runs 10 times and recalculate same products 10x.

```
\Magento\Framework\Mview\View::executeAction:

while ($vsFrom < $currentVersionId) {
    $walker = $this->getWalker();
    $ids = $walker->walk($this->getChangelog(), $vsFrom, $currentVersionId, $batchSize);

    if (empty($ids)) {
        break;
    }
    $vsFrom += $batchSize;
    $action->execute($ids);
}
```

### Expected result

Index recalculate one product once in one round of index recalculation.

### Actual result

Index recalculate one product more than once in one round of index recalculation (based on backlog status).

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @vicobohdan,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @vicobohdan,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
