### ISSUE TITLE
Item remove from the minicart loading effect

### ISSUE THREAD

**Issue by mitul69** [magento/magento2#3655]
Hello 

I want to show some progress bar on when user click on the Remove icon in minicart, 

Remove functionality working fine but the issue with the when i click on the remove Icon then press Ok button in conformation. I cant see any process. 

So can you please help me how can i do that.

**Comment by ishakhsuvarov** [comment]
@mitul69 There is a similar issue: #3589 We are going to implement in the future.

To develop a solution on your own you may refer to the [Magento Developer Documentation](http://devdocs.magento.com/). Technical questions are discussed on the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/). In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.
Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
Thank you.
