### ISSUE TITLE
On setup:upgrade command give error of Unable to apply data patch

### ISSUE THREAD

**Issue by psarkirav** [magento/magento2#36572]
### Summary

On setup:upgrade command give error of Unable to apply data patch
Magento\User\Setup\Patch\Data\UpgradePasswordHashes for module Magento_User. Original exception message: Warning: Undefined array key 1 in /var/www/html/atcross/new_code/vendor/magento/module-user/Setup/Patch/Data/UpgradePasswordHashes.php on line 84
I have attached the screenshot
https://nimb.ws/WVKDLH

### Examples

I have attached the screenshot
https://nimb.ws/WVKDLH

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @psarkirav ,

Thanks for your contribution and collaboration.

Tried to reproduce the issue but issue is not reproducible to me in latest Magento `2.4-develop`.
Below is the screenshot for your reference:-
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/60198022/206150425-f0711c20-5e79-477e-a249-43a787d4a04a.png">

<img width="968" alt="image" src="https://user-images.githubusercontent.com/60198022/206150621-b3ea6c17-7c89-4046-9db9-d62ccdba0542.png">

Kindly provide us more details like steps to reproduce. Also please check in latest `2.4-develop`. Let us know if you are facing any issue.

Thank you

**Comment by psarkirav** [comment]
Hello Shubham,

Actually I am doing the local setup of the one of the site from cloud 2.4.4 magento. During the setup I am facing this issue.
If you have any suggestion it will help.

Thanks,

**Comment by engcom-Lima** [comment]
Hi @psarkirav ,

Please make sure that you have PHP 8 installed for Magento 2.4. and you have given permission to all the necessary folders. Also please provide us logs.

Thanks
