### ISSUE TITLE
Unable to Create New Address: The website with id 3 that was requested wasn't found. Verify the website and try again.

### ISSUE THREAD

**Issue by fiko** [magento/magento2#36582]
### Preconditions and environment

- PHP 8.1
- MySQL V8
- Magento 2.4.4-2.4.5

### Steps to reproduce

1. Create new Store View
    - Store: Main Website Store
    - Name: ….. (Anything)
    - Code: ….. (Anything)
    - Status: Enabled
    - Sort Order: ….. (Any Number)
2. Create New Website
3. Create New Store, Assign this new store to previous created website.
4. Create New Store View, Assign this new store view to previous created store.
5. Under Stores > Settings > Configuration > Customer > Customer Configuration > Account Sharing Options > Share Customer Accounts, set this to Global.
6. Save configuration.
7. Add new customer, and assign the customer to New Website and select other Store View which is not related to current website.
<img width="844" alt="Screenshot 2022-12-08 at 4 46 09 PM" src="https://user-images.githubusercontent.com/60198022/206433613-90221f1d-957b-4f4b-8c4c-76d5ccf1a3d5.png">

8. Edit that created customer.
9. Go to Addresses (left sidebar).
10. Click Add New Address.

### Expected result

- Showing add new Address form

### Actual result

- Showing pop-up message `Something went wrong.`

<img width="1440" alt="Screenshot 2022-12-08 at 13 00 27" src="https://user-images.githubusercontent.com/32075735/206370852-bdc7928c-875d-4d91-81fb-16bdcd81817a.png">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Admin is not able to add new address of customer .

**Pre-requisite:**
1. Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Login as admin.
2. Create new Store View
3. Create New Website
4. Create New Store, Assign this new store to previous created website.
5. Create New Store View, Assign this new store view to previous created store.
6. Under Stores > Settings > Configuration > Customer > Customer Configuration > Account Sharing Options > Share Customer Accounts, set this to Global.
7. Save configuration.
8. Add new customer, and assign the customer to New Website.
9. Edit that created customer.
10. Go to Addresses (left sidebar).
11. Click Add New Address.

**Expected result:** It should show add new Address form.
**Actual result:** Getting error as _somethng went wrong._
**Screenshots:**
<img width="1507" alt="Screenshot 2022-12-08 at 12 50 46 PM" src="https://user-images.githubusercontent.com/60198022/206431644-8b821a95-5863-45c6-af35-6dce3a1562d0.png">

**Comment by DuckThom** [comment]
@engcom-Hotel  I see this fix was released in 2.4.7 but why not 2.4.6-p8 and 2.4.5-p10 as the bug is still present there.

2.4.5-p10: https://github.com/magento/magento2/blob/2.4.5-p10/app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php#L132

2.4.6-p8: https://github.com/magento/magento2/blob/2.4.6-p8/app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php#L132
