### ISSUE TITLE
Timeouts in admin Categories

### ISSUE THREAD

**Issue by ecrocombe** [magento/magento2#36588]
### Preconditions and environment

- Magento CE 2.4.5-p1
- Large catalog (~600 categories, ~250k products, 3 websites with 1 store and 1 storeview for each. all products only in 1 website)
- All products are in a single subcategory under the Root Category.
- Utilise Elasticsuite Virtual Categories for category-product assignment.
- Web server configured to timeout 30 seconds 
- Cloudflare proxy > HAProxy > varnish > nginx

### Steps to reproduce

1. Login to adminhtml
2. Click `Catalog` >> `Products`

### Expected result

Edit page for default Root Category to load.

### Actual result

Web server timeout after 30 seconds with error 520 

### Additional information

Loading the Product count on every category timeouts with a large collection. 

Loading the categories page in admin has always been slow for me, but as I am increasing the number of categories and products over the last week, I have now begun to experience timeouts, I assume I have been operating close to the timeout for a long time.

With my limited expertise in this area, I can only make a few uneducated suggestions.
- Possibly add a config setting to disable loading category product count in adminhtml? Similar to Layered Navigation on frontend?
- Utilize Search Engine for product Counts? 

I have temp fixed this for myself by modifying 
FROM
[https://github.com/magento/magento2/blob/528ed74ca84ca7c6441667d7fec46c19311555af/app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php#L262](https://github.com/magento/magento2/blob/528ed74ca84ca7c6441667d7fec46c19311555af/app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php#L262)
TO
```$this->loadProductCount($this->_items, false, false);```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ecrocombe** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ecrocombe ,

We are trying to reproduce the issue with 2.4.5 magento instance...But we are not able to reproduce the issue.
we are getting expected result.

Steps:
install magento instance
install category and products as per the description
login admin panel
go to catalog >products
Edit page for default Root Category to load.
So we are not able to reproduce the issue.

Let us know if we missing anything!!!

Thanks!!!!

**Comment by ecrocombe** [comment]
Hmm... I guess I can only assume that it may be the ElasticSuite module. Thank you very much for your time.

**Comment by engcom-Dash** [comment]
Hi @ecrocombe ,
Is there any information regarding this issue??? or Can we close the issue???

Thanks!!!

**Comment by ecrocombe** [comment]
Closing, i'll re-open if i find more information linking this issue to magento
