### ISSUE TITLE
Magento 2.4.5-p1 - Message manager not working 

### ISSUE THREAD

**Issue by jkelle62** [magento/magento2#36597]
### Preconditions and environment

- Magento 2.4.5-p1

### Steps to reproduce

1. $this->messageManager->addSuccess('Custom success message'); In a controller.
2. Go to browser console and watch the warnings: 
You can see "jQuery.Deferred exception: $.mage.cookies is undefined initialize"

### Expected result

See messages in the "messages" block...

### Actual result

No messages in the block

### Additional information

- In file "module-theme\view\frontend\web\js\view\messages.js" line 42
$.mage.cookies.set(...) must be replaced by $.cookie(...) & include addiction 'js-cookie/cookie-wrapper'

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @jkelle62,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by amenk** [comment]
@jkelle62 is this eventually to due the use of jquery-cookie which does not work anymore in 2.4.5 ? Check if you use this module.
Or were you able to solve this in another way?
