### ISSUE TITLE
GraphQL product visibility isn't handled correctly for search results

### ISSUE THREAD

**Issue by paales** [magento/magento2#36591]
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

We've got a product API testproduct 1 (sku: `API-TEST-1`) which has set Visbility: Catalog and isn't assigned to any category. This effectively means that the product isn't visible anywhere by navigating, but the product page still works.

[Run query online](https://test.kommagento.nl/api/graphql?query=%23+We%27ve+got+a+product+API+testproduct+1+%28sku%3A+API-TEST-1%29+which+has+set+Visbility+to+Catalog%0A%23+and+isn%27t+assign+to+any+category.%0A%23%0A%23+This+means+that+the+product+page+can+be+accessed+but+it+doesn%27t+show+up+anywhere.%0A%0A%23+It+shows+the+the+product%2C+while+it+shouldn%27t%0Aquery+IncorrectlyReturnsAPITEST1+%7B%0A++one%3A+products%28search%3A+%22%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+For+the+above+query+this+is+a+workaround+by+using+a+space+for+the+search+field%0Aquery+CorrectlyDoesNotReturnAPITEST1++%7B%0A++two%3A+products%28search%3A+%22+%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku+%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+Because+there+is+a+search+term+given%2C+it+correctly+uses+visibility+search+and+thus%0A%23+does+not+return+the+product%0Aquery+CorrectlyDoesNotReturnAPITEST2++%7B%0A++three%3A+products%28search%3A+%22API+testproduct+1%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku+%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+Because+there+is+a+search+term+given%2C+it+should+always+use+Visbility%3A+Search%0A%23+but+it+seems+to+be+filtering+on+Visbility%3A+Product%0Aquery+IncorrectlyReturnsAPITEST2+%7B%0A++four%3A+products%28search%3A+%22API+testproduct+1%22%2C+filter%3A+%7Bprice%3A+%7Bfrom%3A+%221%22%7D%7D%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku%0A++++%7D%0A++%7D%0A%7D)

```graphql
# It shows the the product, while it shouldn't
query IncorrectlyReturnsAPITEST1 {
  one: products(search: "") {
    items {
      name
      sku
    }
  }
}

# For the above query this is a workaround by using a space for the search field
query CorrectlyDoesNotReturnAPITEST1  {
  two: products(search: " ") {
    items {
      name
      sku 
    }
  }
}

# Because there is a search term given, it correctly uses visibility search and thus
# does not return the product
query CorrectlyDoesNotReturnAPITEST2  {
  three: products(search: "API") {
    items {
      name
      sku 
    }
  }
}

# Because there is a search term given, it should always use Visbility: Search
# but it seems to be filtering on Visbility: Product
query IncorrectlyReturnsAPITEST2 {
  four: products(search: "API", filter: {price: {from: "1"}}) {
    items {
      name
      sku
    }
  }
}
```

### Expected result

```JSON
  "data": {
    "one": {
      "items": [
        {
          "name": "DrayTek Vigor 2927F",
          "sku": "V2927F"
        },
        {
          "name": "DrayTek Web Content Filter B",
          "sku": "DrayTek Web Content Filter B"
        },
        {
          "name": "ZyXEL ZyWALL VPN100 Firewall",
          "sku": "VPN100-EU0101F"
        }
      ]
    }
  },
```

```JSON
  "data": {
    "four": {
      "items": []
    }
  },
```

### Actual result

```JSON
  "data": {
    "one": {
      "items": [
        {
          "name": "DrayTek Vigor 2927F",
          "sku": "V2927F"
        },
        {
          "name": "DrayTek Web Content Filter B",
          "sku": "DrayTek Web Content Filter B"
        },
        {
          "name": "ZyXEL ZyWALL VPN100 Firewall",
          "sku": "VPN100-EU0101F"
        },
        {
          "name": "API testproduct 1",
          "sku": "API-TEST-1"
        }
      ]
    }
  },
```

```JSON
  "data": {
    "four": {
      "items": [
        {
          "name": "API testproduct 1",
          "sku": "API-TEST-1"
        }
      ]
    }
  },
```

### Additional information

So it seems that it can use the Visbility: Search, but when any filter is provided it switches to the Visibility: Catalog

### Release note

Correctly set the visibility filer when providing a search parameter

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @paales ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
Steps performed:
Created a product with SKU: API-TEST-1 and ran all the given Graphql queries and none of the responses contained "API-TEST-1".
![image](https://user-images.githubusercontent.com/60198231/207104301-f2230990-420c-4a3b-9a26-e79e74b6ffba.png)
![image](https://user-images.githubusercontent.com/60198231/207104194-9c2b9261-2909-4eb4-9d36-0e4da8ff595f.png)
Kindly recheck the behavior on latest Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by SanctuaryMirror** [comment]
I have noticed same behavior on Magento 2.4.5 + graphql. 

Visibility catalog:
![Zrzut ekranu z 2022-12-13 09-28-14](https://user-images.githubusercontent.com/54793425/207264802-9f8c53a8-58a2-4d32-bf8f-8f440b82d1ad.png)
Index done, correct status:
![Zrzut ekranu z 2022-12-13 09-29-37](https://user-images.githubusercontent.com/54793425/207265011-0ec36fe3-48d5-48cf-be89-f373b9634508.png)
but still achieve getting result from search:
![Zrzut ekranu z 2022-12-13 09-30-32](https://user-images.githubusercontent.com/54793425/207265213-c648f97f-bdbf-4fdd-868f-0a36bfcc419f.png)
Request is post, no cache involved.

Tested on some 2.4 demos, without graphql, works as expected, but on 2.4.5 graphql it breaks. Did not check on older versions of magento + graphql, so cannot tell does older versions works good or not.

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by adarshkhatri** [comment]
Do we have ETA on this?

**Comment by chernenm** [comment]
@magento give me 2.4-develop instance
