### ISSUE TITLE
Cannot create a custom catalog rule condition in magento 2

### ISSUE THREAD

**Issue by leuterkil** [magento/magento2#36592]
### Preconditions and environment

- Magento version : 2.4

### Steps to reproduce

1. Created a custom module
2. Created the after plugin for the getNewChildSelectOptions()
3. added the type in the di.xml file
4. created a AbstractCondition child class and added the required functions in it

### Expected result

A catalog rule must added successfully with the custom condition in it.

### Actual result

The rule cannot be saved because an Exception is thrown with message "Invalid method Vendor\ModuleName\Model\Rule\Condition\LoyaltyCatalog::collectValidatedAttributes"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by leuterkil** [comment]
No it does't show any option in condition select box! I saw yesterday from my module that magento throws me an exception with message "undefined type passed in". When I went in the source code of magento i realized that in the "Magento\CatalogRule\Model\Rule\Condition\MappableConditionsProcessor" in line 70 only the combined and the product conditions passed. Thanks for your time

**Comment by engcom-Hotel** [comment]
Hello @leuterkil,

Thanks for the reply!

Sorry but unable to get you. It seems the issue has been resolved for you. Please confirm or please let us know if we have missed anything on order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @leuterkil,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
