### ISSUE TITLE
Adding new sort order for catalog by product creation day

### ISSUE THREAD

**Issue by chrom** [magento/magento2#3659]
How i can adding new ordering for product by product creation day, if in attribute set i don't see created_at?

Is it possible to do this through the admin area - Stores -> Ratings?
and how?

**Comment by katmoon** [comment]
Hi @chrom 

This feature is available in Enterprise edition. There is a similar feature in Magento 1: http://merch.docs.magento.com/ee/user_guide/catalog/visual-merchandiser.html
