### ISSUE TITLE
Magento 2.4.5-p1 - Email preview window height

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#36593]
### Preconditions and environment

- Magento version 2.4.5-p1

Email preview is shown in a short height window:

![image](https://user-images.githubusercontent.com/66754347/206771577-adda2ba4-41e7-4104-8692-57a5514954e2.png)

### Steps to reproduce

1) Go to Marketing -> Email Templates

2) Add new template

3) Load template New Invoice

4) Save template

5) Click "Preview"

### Expected result

- Full sized email template preview without scrolling

![image](https://user-images.githubusercontent.com/66754347/206772086-ab04f870-78b7-41a9-ae02-b62bf7d3e762.png)

### Actual result

Real output:

![image](https://user-images.githubusercontent.com/66754347/206771722-1f68738f-86bd-4adb-bfa2-7229cc1ddb48.png)

### Additional information

Something is going on with the Iframe resizing. Did not dig into the issue myself yet.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
There are some JS errors in the console:

`Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.load (jquery.js:10363:23)
    at (index):50:26
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at require.js:1460:36`


And

`Blocked script execution in 'http://vanillamagento.ca/admin/admin/email_template/popup/key/3861b00fe3fa9c85c88caecdd2455b6e7bb418512d4cef5b4c616f382f56d1a4/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

**Comment by ihor-sviziev** [comment]
Hi @pmonosolo,
It looks like a duplicate of https://github.com/magento/magento2/issues/35697, which was already fixed in https://github.com/magento/magento2/pull/35816, but wasn't included to any release yet

**Comment by pmonosolo** [comment]
Thanks @engcom-Bravo and @ihor-sviziev! 

Confirmed, this one already solved!

**Comment by HardeepOne** [comment]
Can someone explain how to fix that issue, as I'm also having the iframe sizing issue.
