### ISSUE TITLE
REST API /V1/carts/:cartId/selected-payment-method Internal Error

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#3660]
Hello,

I am trying to create order by REST API.

I have created cart with item. Then I created billing address and I want to select payment method

**request**
PUT /rest/V1/carts/13/selected-payment-method
{
  "method": {
    "poNumber": "25",
    "method": "cashondelivery"
  }
}

Q: what is poNumber? I put there billing address id but I have no idea what poNumber is... 

**response**
{
    "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-56d98b6cf03ca"
}

**Log**
main.CRITICAL: exception 'LogicException' with message 'Report ID: webapi-56d98b6cf03ca; Message: Property "CartId" does not have corresponding setter in class "Magento\Quote\Api\Data\PaymentInterface".' in /var/www/html/magento/vendor/magento/framework/Webapi/ErrorProcessor.php:194

We want to connect magento api to our 3rd part application... We are still finding how requests should looks because we cant find informations what params in requests/response mean.

It would be great if somebody can write us step by step what we should do if we want to create new order by REST API?

Thanks!

**Comment by sdzhepa** [comment]
Hello @RUjmiak, thank you for reporting this issue. We have created an internal ticket `MAGETWO-50192` to fix the problem. 

At this moment you can fix the problem by adding cartId into payload, example:
PUT /rest/V1/carts/6/selected-payment-method

``` json
{
    "cartId": 6,
    "method": {
        "method": "cashondelivery"
    }
}
```

"poNumber" is optional parameter, it used for some payments like "Purchase Order".
Only this payment, from default Magento 2 installation, has required field "Purchase Order Number"

**Comment by okorshenko** [comment]
@RUjmiak Thank you for reporting the issue. Fix for MAGETWO-50192 merged to develop branch.

**Comment by mukdam** [comment]
Please update http://devdocs.magento.com/swagger/index.html#/  
body parameters.
