### ISSUE TITLE
Magento 2.4.5-p1 - no output of {{layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id}}

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#36601]
### Preconditions and environment

- Magento 2.4.5-p1 CE

- Trying to send an email with Credit Memo items, but the item list is not being outputted.
- The /vendor/magento/module-sales/Block/Order/Email/Creditmemo/Items.php  getCreditmemo() does not pull out the Credit Memo object for some reason.

I'm testing with both [Yireo Email tester](https://www.yireo.com/software/magento-extensions/emailtester2) and just "SEND" button within the Credit Memo interface.

Both do not show the list of items that are being refunded.

I dont think this has ever worked since I started working on M2. 

### Steps to reproduce

1) Create an order

2) Invoice order

3) Create Credit Memo for the order that includes all the items

4) Go Credit Memo Tab within Order EDIT interface -> Click on Credit Memo -> Click SEND 

### Expected result

Email is sent with items list and tax ouput.

![image](https://user-images.githubusercontent.com/66754347/207466639-73f045cc-5efa-4fca-bbc3-5d45aeed87bd.png)

^^^ there should be Tax ouput here, but that also throws an error. 

### Actual result

No items are outputted.

### Additional information

I've tested this on my vanilla Magento 2 on Yireo email tester but had the same result. 

I'm not sure how to set up email on a vanilla Magento yet, but Yireo plugin should have outputted the items.

Might be related to: https://github.com/magento/magento2/issues/35367

The fix in that Issue does not work - I have set the values using:
{{layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id}} 

And its also not working.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
@magento give me 2.4.5-p1 instance

**Comment by pmonosolo** [comment]
Ahhhhh, cant test it without the email functionality :(

**Comment by engcom-November** [comment]
Hi @pmonosolo ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4-develop instance and 2.4-develop with enterprise edition modules enabled but the issue is not reproducible with below steps performed:
**Steps performed:**
1. Setup Mailhog in local system for emails
2. Configured Tax zone and tax rules
3. reindex and clear cache
4. Login as customer to frontend
5. Add product to cart and place order
6. Admin - Sales - Orders - View Order - Create invoice - Email triggered. No issue
7. Create Credit Memo - Email triggered as expected with tax summary. Please refer the screenshots below:
![image](https://user-images.githubusercontent.com/60198231/207566513-f73f4c6b-44e4-4ab7-a16c-37be79ce72fc.png)
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and check if the issue occurred due to 3rd party extensions enabled. Provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by devchris79** [comment]
It may be that the templates you are using are not updated to the new format.

A simple sidestep is to set the is_legacy column to 1 in the database table email_template.

**Comment by pmonosolo** [comment]
> It may be that the templates you are using are not updated to the new format.
> 
> A simple sidestep is to set the is_legacy column to 1 in the database table email_template.

Sorry, got bogged down with other issues.

I used "Load Template" funtionality to get the original Magento 2.4.5-p1 layouts - its still missing the items lines. 

I also have a Vanilla Magento without any 3rd party plugins (besides Yireo Email Tester) and it also outputs no items + tax.

**Comment by devchris79** [comment]
Are you using any themes? The latest Porto for instance has issues with email.

**Comment by pmonosolo** [comment]
> Are you using any themes? The latest Porto for instance has issues with email.

No, just basic Luma theme on my Vanilla install. 

On Production its Luma based theme, but edited a lot.

I need more time for testing, from just trying to output to logs, the credmemo object just outputting NULL.

So I dont know if it's the {{layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id}} or something else.

**Comment by pmonosolo** [comment]
Closing issue. Must be something my setup. 

I was able to set up SMTP on my vanilla site and was able to send a credit memo email and it showed the items:

![image](https://user-images.githubusercontent.com/66754347/208204041-2c0c6bcc-3b16-4a75-a853-500cc8b7a5d0.png)


Thanks everybody for checking on your side! Happy Holidays!

**Comment by ssx** [comment]
@pmonosolo did you ever track this down? I've got the same issue now and I can't seem to pinpoint it.
