### ISSUE TITLE
[HW]: Hierarchy catalog with working search

### ISSUE THREAD

**Issue by mkikets99** [magento/magento2#36616]
### Summary

It seems like `Magento_CatalogSearch` using a `Magento_Catalog/templates/product/list.phtml` for showing results of a search.
But i have a job on my side where i need to make hierarchy catalog with images up until products founded.
If i change `list.phtml` file to code like [on this page](https://magecomp.com/blog/display-subcategories-information-category-page-magento-2/) then hierarchy works but search doesn't want to work.

Is there any way to know, when search is called? OR maybe somehow change that template file should be used for showing search results?

### Examples

[Hierarchy Catalog](https://magecomp.com/blog/display-subcategories-information-category-page-magento-2/)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mkikets99** [comment]
Information about environment:
Magento: docker image from Bitnami with 2.4.4 on board

**Comment by engcom-Hotel** [comment]
Hello @mkikets99,

Thanks for the report and collaboration!

We are using this platform to address any bug/issue found in the Magento core libraries. But after reading the main description it seems that this is not related to any issue with the Magento core library.

Hence I suggest you post your query here in [Magento stack exchange](https://magento.stackexchange.com/).

Thanks
