### ISSUE TITLE
Error: Call to a member function getId() on null in magento/module-security/Model/AdminSessionsManager.php:305 

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#36610]
### Preconditions and environment

- Magento version 2.4.4

### Steps to reproduce

1. Login to the backend
2. Logout
3. Access /admin/admin/auth/logout/

I assume that this might also happen in case of double clicks on the logout or maybe in cases of several tabs opened.

### Expected result

Nothing happens we are redirected back to the login page.

### Actual result

An exception is thrown:

<pre>
Error: Call to a member function getId() on null in vendor/magento/module-security/Model/AdminSessionsManager.php:305
Stack trace:

#0 vendor/magento/module-security/Model/AdminSessionsManager.php(179): Magento\Security\Model\AdminSessionsManager->createNewSession()
#1 vendor/magento/module-security/Model/AdminSessionsManager.php(159): Magento\Security\Model\AdminSessionsManager->getCurrentSession()
#2 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Security\Model\AdminSessionsManager->processLogout()
#7 generated/code/Magento/Security/Model/AdminSessionsManager/Interceptor.php(23): Magento\Security\Model\AdminSessionsManager\Interceptor->___callPlugins()
#8 vendor/magento/module-security/Model/Plugin/Auth.php(61): Magento\Security\Model\AdminSessionsManager\Interceptor->processLogout()
#9 vendor/magento/framework/Interception/Interceptor.php(121): Magento\Security\Model\Plugin\Auth->beforeLogout()
</pre>

Note: I have removed the irrelevant stack lines

### Additional information

Potential fix:

in `magento/module-backend/Controller/Adminhtml/Auth/Logout.php`:

<pre>
    public function execute()
    {
+        if ($this->_auth->getUser()) {
             $this->_auth->logout();
             $this->messageManager->addSuccessMessage(__('You have logged out.'));   
+        }

         /** @var \Magento\Backend\Model\View\Result\Redirect $resultRedirect */
         $resultRedirect = $this->resultRedirectFactory->create();
         return $resultRedirect->setPath($this->_helper->getHomePageUrl());
    }
</pre>

This fix works but I'm not 100% sure it's the most optimal and safest.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @digitalpianism,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.We are able to redirected back to the login page.No exceptions are triggered.Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @digitalpianism,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
