### ISSUE TITLE
Fixed amount discount for whole cart not working with exclude sku condition

### ISSUE THREAD

**Issue by Kannakiraj123** [magento/magento2#36624]
### Preconditions and environment

Magento 2.4.5

### Steps to reproduce

1.Set SKU attribute 'use for promo rule conditions' true.
2.Add coupon code 20OFFER with exclude product by SKU
3.Set "Fixed amount discount for whole cart" as 20
3.Add few product in cart and apply coupon code

### Expected result

Discount should not apply if exclude sku in cart

### Actual result

Discount apply if exclude sku in cart

### Additional information

<img width="1776" alt="Screenshot 2022-12-16 at 11 52 10 AM" src="https://user-images.githubusercontent.com/88073031/208035627-f6395d39-5816-40de-b62a-d4d6454e7103.png">
<img width="1439" alt="Screenshot 2022-12-16 at 11 51 50 AM" src="https://user-images.githubusercontent.com/88073031/208035653-885eb410-497b-4119-ab18-414aef544b78.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Kannakiraj123,

Thank you for reporting and collaboration.

Similar Issue  confirmed here https://github.com/magento/magento2/issues/36528.

Hence we are closing this as a duplicate.

Thanks.
