### ISSUE TITLE
Redirects to different stores in Admin

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#3663]
I have multistore installed and running behind Nginx. Storefronts work as expected, though not without some issues, but... in admin area Magento randomly generates link urls to different store views. Setting domain name in configuration>admin does not help with the issue.

**Comment by okorshenko** [comment]
hi @devdesco-ceo could you please provide more details and steps to reproduce the issue?
Could you please use this template:

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...

Expected result
--
1. [Example] Configurable product added to the shopping cart.
2. ...

Actual result
--
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by piotrekkaminski** [comment]
Closing due to lack of response.
