### ISSUE TITLE
[Performance] Loading order through repository loads the order multiple times from DB. (ShippingBuilder)

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#36636]
### Summary

Magento 2.4.5-p1

Loading order through repository loads the order three times from DB : 

```
$this->orderRepository->get($orderId);
```
Loads the order from database, then calls setShippingAssignments() which calls TaxManagement::getShippingAssignmentBuilderDependency() which loads the order from database again.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79

and

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

### Examples

```
$this->orderRepository->get($orderId);
```

### Steps to reproduce
1. Login in frontend with the user which has atleast 1 order
2. Enable DB log
3. Add breakpoints in the below lines:
https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/OrderRepository.php#L137

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79
4. Try to access `My Account` page
5. The function `$this->orderFactory->create()->load($this->getOrderId())` is calling 3 times for order id `2`. Below is the MySQL query fetched from db.log:
```
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
```

### Proposed solution

I guess line 
`$shippingAssignments->setOrderId($order->getEntityId());`
should be replaced somehow by
`$shippingAssignments->setOrder($order);`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the report and collaboration!

We need some more information in order to reproduce the issue. As per my understanding, the method `$this->getOrderId()` is calling 3 times in the below function:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L75-L92

We can save the value of the output of `$this->getOrderId()` and use it wherever required. Am I on the same page? Or please let us know the steps to reproduce the issue.

Thanks

**Comment by Nuranto** [comment]
Hello @engcom-Hotel,

I'm not sure we're on the same page. Calling `$this->getOrderId()` is not an issue to me.

Issue is when we call `Magento\Sales\Model\OrderRepository::get()`: 

https://github.com/magento/magento2/blob/3e5be99a940ef572e1a99fee8b9258fda5be9ff4/app/code/Magento/Sales/Model/OrderRepository.php#L130-L144

You can see on line 137 that the order is loaded from database.

But line 144 is calling those two lines : 

https://github.com/magento/magento2/blob/3e5be99a940ef572e1a99fee8b9258fda5be9ff4/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79

https://github.com/magento/magento2/blob/3e5be99a940ef572e1a99fee8b9258fda5be9ff4/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

Result is that when we call `Magento\Sales\Model\OrderRepository::get()`, the order gets loaded from database 3 times instead of 1. (that's actually more than 3 times, but I've created distinct issues for each concerned modules)


I think the best thing to do is to replace `->setOrderId($order->getEntityId())` by `->setOrder($order)` here : 

https://github.com/magento/magento2/blob/3e5be99a940ef572e1a99fee8b9258fda5be9ff4/app/code/Magento/Sales/Model/OrderRepository.php#L305

and refactor `Magento\Sales\Model\Order\ShippingAssignmentBuilder` accordingly : 
- Add class property `order`
- Add `setOrder($order) { $this->order = $order; return $this; }` method
- Refactor `create` method : 
```
public function create()
    {
        $shippingAssignments = null;
        if (!$this->order && $this->getOrderId()) {
            $this->order = $this->orderFactory->create()->load($this->getOrderId());
        }
        if ($this->order) {
            /** @var ShippingAssignmentInterface $shippingAssignment */
            $shippingAssignment =  $this->shippingAssignmentFactory->create();

            $shipping = $this->shippingBuilderFactory->create();
            $shipping->setOrder($this->order);
            $shippingAssignment->setShipping($shipping->create());
            $shippingAssignment->setItems($this->order->getItems());
            $shippingAssignment->setStockId($this->order->getStockId());
            //for now order has only one shipping assignment
            $shippingAssignments = [$shippingAssignment];
        }
        return $shippingAssignments;
    }
```

and finally refactor `Magento\Sales\Model\Order\ShippingBuilder` the same way.

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the detailed explanation!

We have debugged the code via following the below steps:

1. Login in frontend with the user which has atleast 1 order
2. Enable DB log
3. Add breakpoints in the below lines:
https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/OrderRepository.php#L137

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79
4. Try to access `My Account` page
5. The function `$this->orderFactory->create()->load($this->getOrderId())` is calling 3 times for order id `2`. Below is the MySQL query fetched from db.log:
```
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
```

Hence confirming the issue.

Thanks

**Comment by o-iegorov** [comment]
The internal team start working on. the issue
