### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by mushketer888** [magento/magento2#36653]
### Preconditions and environment

- Magento version 2.4.5

Will update or close on verifying in vanilla version

### Steps to reproduce

Will update or close on verifying in vanilla version

### Expected result

Will update or close on verifying in vanilla version

### Actual result

Will update or close on verifying in vanilla version

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mushketer888** [comment]
@magento give me 2.4-develop instance

**Comment by mushketer888** [comment]
Can't log into admin 
You need to configure Two-Factor Authorization in order to proceed to your store's admin area

An E-mail was sent to you with further instructions

**Comment by mushketer888** [comment]
Closed because can't log into test env admin

**Comment by engcom-Dash** [comment]
Hi @mushketer888 ,

Thanks for Contribution with us.
Kindly provide More information about this issue its very useful to reproduce issue.
Thanks!!!
