### ISSUE TITLE
C# - magento 2.0.2 - salesOrderRepositoryV1 - shipping address missing

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#3665]
salesOrderRepositoryV1Get

does not return shipping address 

only got billing and quote addresses

**Comment by NadiyaS** [comment]
Hi @lindows-xx,
thanks for reporting this issue. It is already being tracked by MAGETWO-46720 ticket.
And scheduled for 2.0.3 patch release.
This issue will be closed as duplicate of #2628 .
