### ISSUE TITLE
Breadcrumbs not showing full path

### ISSUE THREAD

**Issue by z1nc0r3** [magento/magento2#36666]
### Preconditions and environment

- 2.4.5-p1
- Breadcrumbs not showing full path while the **Rootways Megamenu** module is enabled.
- This bug occurs on the Magento 2.4.3 version also.

### Steps to reproduce

1. Enable Rootways Megamenu module.
2. Choose a category from the menu.
3. Select any product from the product list.
4. Breadcrumbs will show only `Home > Product name` instead on `Home > Category > Sub category > Product name`

### Expected result

- Expected to show the full path to the product in the breadcrumbs.
- `Home > Category > Sub Category > Product name`

### Actual result

- Shows a path only with the `Home` link.
- `Home > Product Name`

### Additional information

- This bug happens only when the Rootways Megamenu module is enabled.
- Tried changing Megamenu settings, but not fixed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @z1nc0r3 ,

Thanks for your contribution and collaboration.

**Rootways Megamenu ** is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.

Thank you
