### ISSUE TITLE
Missing setScopeFilter method call

### ISSUE THREAD

**Issue by ovekeryk** [magento/magento2#3666]
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogInventory/Model/StockRegistryProvider.php#L150

Looks like $criteria->setScopeFilter($scopeId) method should be called.

**Comment by piotrekkaminski** [comment]
@antonkril can you look into it?

**Comment by kandy** [comment]
Thanks for the contribution, We have created ticket MAGETWO-55451 for fix issue.

**Comment by magento-engcom-team** [comment]
@ovekeryk, thank you for your report.
We've created internal ticket(s) MAGETWO-55451 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ovekeryk, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
