### ISSUE TITLE
Error "Cannot add product without stock to wishlist" while product inventory is switched off

### ISSUE THREAD

**Issue by github-chokdee-online** [magento/magento2#36671]
### Preconditions and environment

- Magento version 2.4.5
- blank theme as default

### Steps to reproduce

Switch of inventory management and switch on backorders allowed (quantity < 0 allowed)

### Expected result

Can add to wish list if logged in

### Actual result

<img width="1291" alt="Screenshot 2565-12-26 at 14 28 22" src="https://user-images.githubusercontent.com/115934862/209518195-bcd9828a-0244-4aea-ac2b-2e2ae2255650.png">

We can't add the item to Wish List right now: Cannot add product without stock to wishlist..

### Additional information

magento/module-wishlist/Model/Wishlist.php:465 

if (!$this->stockConfiguration->isShowOutOfStock($storeId) && !$product->getIsSalable()) {
      throw new StockStateException(__('Cannot add product without stock to wishlist.'));
}

Both are negative false (true).

I would expect that the check would be "if  show out of stock and NOT salable". Why it is not salable is another issue that I'm looking into. That could be something logically wrong in the config. 

The issue here is, should the check show out of stock. If I set the "cataloginventory/options/show_out_of_stock" to 1, counter intuitive I can now add to the wishlist.

No I have no inventory management, backorders are allowed, however I can only add to the wishlist if I force the "out of stock" to be shown. Doesn't make sense to me. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @github-chokdee-online ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4-develop instances with and without inventory Management enabled with backorders allowed (quantity < 0 allowed) but the issue is not reproducible.
We are able to add the out of stock product to wishlist for a logged in user from both catalog search results page and product details pages. Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/209610400-8ee0d1ee-005b-4def-8b0d-9b21214fd0fe.png)

**Comment by github-chokdee-online** [comment]
Hi Girija,

I figured it out already. 

Remember, key is the fact that stock management is switch off. So I should never get the error "cannot .. without stock". That is confusing.

In this case the product was unsalable, because the simple products in the configurable where NOT added to the current website I was in on front-end. As shown in copied above if-statement, in that case the throw will be triggered, showing the confusing error. I think a developer could easily reproduce this situation. 

I think it's a minor so I'm not going to spend time on it. See if it is important enough for you guys to revaluate the if - statement added above.

I'll close the ticket, as I now not have an issue anymore.
Thanks for your time and replying,
With kind regards,
John
