### ISSUE TITLE
Zip Code for Greece should not expect space

### ISSUE THREAD

**Issue by cptX** [magento/magento2#36676]
### Preconditions and environment

- Magento version
2.4.5

### Steps to reproduce

Go to cart or checkout, select Greece and insert postal code 12345

### Expected result

No warning

### Actual result

Zipcode gives warning

### Additional information

Solution (completely written out, just copy and paste!)

Replace zip countrycode NL with:

```
    <zip countryCode="GR">
        <codes>
            <code id="pattern_1" active="true" example="12345">^[0-9]{5}$</code>
        </codes>
    </zip>
```

in /app/code/Magento/Directory/etc/zip_codes.xml

### Release note

I'm 41 years old and I have never seen anyone write a zip code with a space in between here in Greece.
So getting an error/warning during ZIP Code input is definitely frustrating!
I have seen that several other countries face the same problem with this validation. For Greece I can ensure you that everybody writes the Zip code like this 12345 and not 123 45.
Even if you check the [wikipedia](https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%AC%CE%BB%CE%BF%CE%B3%CE%BF%CF%82_%CF%84%CE%B1%CF%87%CF%85%CE%B4%CF%81%CE%BF%CE%BC%CE%B9%CE%BA%CF%8E%CE%BD_%CE%BA%CF%89%CE%B4%CE%B9%CE%BA%CF%8E%CE%BD_%CF%84%CE%B7%CF%82_%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1%CF%82) you will see that actually there is a categorization defined by the first 2 digits and not 3, so in any case the current implementation is wrong. As far as I  know everybody writes all 5 digits together. You can check this also [here](https://www.taxidromikoskodikas.gr/tk/) which gives a list with all zip codes and they give them as continues 5 digit numbers.

I would like also to reference this issue which is similar and with the same solution.
#11898

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
**Hi @cptX ,**

We are trying to reproduce the issue in 2.4.5 Magento instance its reproducible and we are confirming the issue.
**Magento Version**:2.4.5
**PHP Version** :8.1
**Steps we Followed:**
1.Install fresh Magento instance
2.Go to front end and add simple product in to cart
3.go to checkout
4.Select country as Greece
5.Enter postal code as 12345
Warning Message is Under the Postal code text box.As per description we getting same results.So we are confirming the issue.
**For your reference attached the screenshots here:**
<img width="1479" alt="Screenshot 2022-12-28 at 8 22 27 PM" src="https://user-images.githubusercontent.com/60198592/209846756-3f51eda8-b0dc-472f-a4bf-a1ebf0dfd64f.png">

Let us know if we missing anything!!!
Thanks!!!

**Comment by cptX** [comment]
Thank you for focusing on this issue so quickly!

**Comment by Vasudev-22** [comment]
@magento I am working on this
