### ISSUE TITLE
After installing Magento 2.0.2 is very slow in loading home/admin page

### ISSUE THREAD

**Issue by kotreshnm** [magento/magento2#3667]
Hi,

I installed magento 2.0.2 on WAMP 2.5 successfully but I see home/admin page takes at least 3-4 mins to get loaded and the case is same in page navigation. Kindly help me in getting my pages loaded faster . Below are my env details

OS:Windows 7 64 bit WAMP:2.5 RAM:8GB

Early helps are appreciated .

Thanks Kotresh NM

**Comment by scholtz** [comment]
I think you will have very slow HDD or processor.. Try upgrading to SSD drive ;)

But I would like to see also response from official Magento stuff how to make it faster on older hardware.. :)

**Comment by marvincaspar** [comment]
Wrong permissions on cache folder?

**Comment by kotreshnm** [comment]
No,folders have full access .It's deployed in c/wamp/www where in it has full rights.

**Comment by kotreshnm** [comment]
No,folders have full access .It's deployed in c/wamp/www where in it has full rights.

**Comment by devhn** [comment]
I'm seeing the same slow loading on local installation (both admin and frontend):

Hardware:
- 2x 2,4 GHz Quad-Core Xeon
- 16 GB DDR3
- SSD 1TB (90% disk free)

Setup (osx):
- Bitnami Mamp stack 7.0.3.0 (apache)
- PHP 7 and MySql 5.7
- Varnish

Some scripts are loading 20+ seconds. Only thing changed within apache are virtual hosts (added local domains).

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [Hosting & Performance](https://community.magento.com/t5/Hosting-Performance/bd-p/Hosting-Performance) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
