### ISSUE TITLE
Internal server error on Category graphql query

### ISSUE THREAD

**Issue by eze86816** [magento/magento2#36675]
### Preconditions and environment

- Magento version : 2.4.4
- PHP version : 8.1

### Steps to reproduce

Run Category List Query 

```
{
	categories(filters: {}, pageSize: 1, currentPage: 2) {
		total_count
		items {
			available_sort_by
			uid
			level
			name
			path
			children_count
			canonical_url
			children_count
			custom_layout_update_file
			default_sort_by
			description
			display_mode
			filter_price_range
			image
			include_in_menu
			is_anchor
			landing_page
			level
			meta_description
			meta_keywords
			meta_title
			name
			path
			path_in_store
			position
			product_count
			redirect_code
			relative_url
			type
			uid
			url_key
			url_path
			url_suffix
			children {
				uid
				level
				name
				path
				children_count
				children {
					uid
					level
					name
					path
				}
			}
		}
		page_info {
			current_page
			page_size
			total_pages
		}
	}
}
```

### Expected result

Query should return Categories data

### Actual result

Internal server error.

 report.ERROR: Cannot return null for non-nullable field "CategoryTree.redirect_code".
 
 
![image](https://user-images.githubusercontent.com/103404320/209641280-e4999272-51d6-4497-aa55-571d57a0e729.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Getting internal server error while running category list query of graph ql.

**Pre-requisite:**
- Fresh magento `2.4-develop` should be installed.
**Steps to reproduce:**
Run below category list query of graph ql:
```
{
	categories(filters: {}, pageSize: 1, currentPage: 2) {
		total_count
		items {
			available_sort_by
			uid
			level
			name
			path
			children_count
			canonical_url
			children_count
			custom_layout_update_file
			default_sort_by
			description
			display_mode
			filter_price_range
			image
			include_in_menu
			is_anchor
			landing_page
			level
			meta_description
			meta_keywords
			meta_title
			name
			path
			path_in_store
			position
			product_count
			redirect_code
			relative_url
			type
			uid
			url_key
			url_path
			url_suffix
			children {
				uid
				level
				name
				path
				children_count
				children {
					uid
					level
					name
					path
				}
			}
		}
		page_info {
			current_page
			page_size
			total_pages
		}
	}
}


```

**Expected result:**  Query should return Categories data.
**Actual result:**  Getting internal server error in response.
**Screenshots:**
<img width="1378" alt="Screenshot 2022-12-28 at 11 52 11 AM" src="https://user-images.githubusercontent.com/60198022/209773760-3de29564-1687-4a3f-a78c-5ee8391f7979.png">

**Comment by Vasudev-22** [comment]
@magento I am working on this
