### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by Perkperk13** [magento/magento2#36672]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Bravo** [comment]
Hi @Perkperk13,

Thank you for reporting and collaboration.

To speed up the processing of this issue, please provide us with the following information:

* Summary of the issue
* Information on your environment
* Steps to reproduce
* Expected and actual results

Thanks.
