### ISSUE TITLE
2.4 installation error 

### ISSUE THREAD

**Issue by berzinskristaps** [magento/magento2#36699]
Hello,
Im struggling to install magento on my mac for 4 days now, have tried all of the versions available to install, from each version im getting a different error. Now im trieng to install 2.4 and im getting this kinde of error 

Package hoa/compiler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/consistency is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/event is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/exception is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/file is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/iterator is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/math is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/protocol is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/regex is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/stream is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ustring is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/visitor is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/zformat is abandoned, you should avoid using it. No replacement was suggested.

**Comment by FadedOut** [comment]
@berzinskristaps 

Those are not actually errors they are suggestions/information. Just a FYI. ...are you getting any other lines after trying to install? If that's it, it may have worked. It should say something like "success" then "admin URL:".

Also, I'm pretty certain in the Magento system requirements, only linux is supported, it says Windows & Mac are not. 

Here is the system requirements page: [Requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) (check under the "Operating systems (Linux x86-64)" section).

**Comment by engcom-Bravo** [comment]
@FadedOut hanks for your contribution & collaboration over here.

Hi @berzinskristaps,


Thank you for reporting and collaboration.

Kindly below follow Installation guide for installation.

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html?lang=en.


Please check your system requirements.

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html


If you are still getting an issue, kindly help us with all the step by step commands you have followed up during the installation.It will help us.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @berzinskristaps,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
