### ISSUE TITLE
wrong message "invalid form key" when max_input_vars is exceeded

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#36695]
### Preconditions and environment

- 2.4.5-p1
- PHP 8.1

### Steps to reproduce

- Set your PHP max_input_vars to a low number like 1000
- Create a product with a lot of custom options like 500. 
- Expand customizable options section
- Add any info in the fields for the custom options
- Try to save the product

### Expected result

The error is clearly shown or a descriptive message is shown

`Got error 'PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0'`

### Actual result

![image](https://user-images.githubusercontent.com/20220341/210316401-c6808e8c-5e70-4f80-a2f6-faaff0600a83.png)

### Additional information

This is a generic error message that appears in many cases and of course the reason is not that the form key is expired. Magento should handle unknown errors better than say `invalid form key`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @ioweb-gr,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance.

We got below errors.Kindly refer the screenshots.

**Steps to reproduce**

1.Set your PHP max_input_vars to a low number like 1000
2.Create a product with a lot of custom options like 500.
3.Expand customizable options section
4.Add any info in the fields for the custom options
5.Try to save the product



After creating custom options when we try to save the product got the below error.


<img width="1415" alt="Screenshot 2023-01-04 at 3 16 59 PM" src="https://user-images.githubusercontent.com/51680745/210558724-d2e6db21-a145-4ae8-8a76-ed9caa64c16a.png">


In log file we got below error.

<img width="1508" alt="Screenshot 2023-01-04 at 3 32 01 PM" src="https://user-images.githubusercontent.com/51680745/210558761-d28fd30d-a286-401f-86f4-680ce23d9210.png">



Kindly let us know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @ioweb-gr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by webcreative24** [comment]
Same here on category page
