### ISSUE TITLE
Logo, icons and product images in product pages, dont show in frontend

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3671]
Just moved a Magento 2 site from a test hosting domain to my local PC.
Everything is ok except Magento logo and icons (cart, envelope inside the email subscribe form, search icon, etc) dont show on frontend.
On backend there are no problems.

I have already flushed cache, deleted pub/static folders, run setup:static-content:deploy.

Product images in product pages dont load. However, they load ok in catalog pages.

I found that the file var/resource_config.json still points to the test domain url:
{"media_directory":"\/chroot\/home\/test.domain\/html\/pub\/media\/","allowed_resources":["css","css_secure","js","theme","favicon","email","wysiwyg","tmp","catalog","custom_options","dhl","captcha"],"update_time":"3600"}

Is it ok to edit this file manually?

(Also attached screenshot warning from browser console)
![console](https://cloud.githubusercontent.com/assets/8398744/13558547/958412aa-e3cc-11e5-9712-62acf46a19f5.jpg)

**Comment by mrkhoa99** [comment]
Hello @lgarridoj 

Delete all files under _var_ folder.You try to enable developer mode and run deploy command again.
Enable developer mode from CLI: `php bin/magento deploy:mode:set developer`
You change web base url from _core_config_data_ table?

**Comment by jibrandlr** [comment]
@mrkhoa99 should I delete all files AND folders under var folder?

**Comment by mrkhoa99** [comment]
@lgarridoj  I checked _var_ folder. We shouldn't delete _.htaccess_ file. We can delete the rest.

**Comment by jibrandlr** [comment]
I reinstalled the magento application and the problem was solved.

**Comment by jibrandlr** [comment]
I reopen the issue since it is present again after updating the installation with my catalog, images, theme, etc. This happens on a WAMP environment.
I tested the same installation in a linux virtual machine and the issue is not present.
It only happens in windows.

**Comment by jibrandlr** [comment]
Update: Logo, icon images, etc.., are visible again when changing to English (United States) locale. If I change locale to Spanish (Mexico) those images dissapear.
When this installation was on a hosting server I could change between those locale settings with no problem. Now in my local installation, the issue is present when chosing locale Spanish.

**Comment by katmoon** [comment]
Hi @lgarridoj 

Windows is not a supported platform. See http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html
I'm glad you have found a workaround to set English locale.

I'm closing the ticket since there's nothing can be done here if it happens on Windows only.
Feel free to reopen if you have any additional questions.
