### ISSUE TITLE
Admin grid actions dropdown cut off in versions after 2.4.3

### ISSUE THREAD

**Issue by schizek** [magento/magento2#36710]
### Preconditions and environment

Magento version: 2.4.5-p1

### Steps to reproduce

1. Log into admin
2. Go to **Content > Pages**
3. Click the "Select" in the Action column for the last row in the grid

### Expected result

I expect to see the whole dropdown without causing an inner scroll to reach the content.  This was last seen working correctly on version 2.4.3-p2.

<img width="328" alt="Screenshot 2023-01-06 at 8 36 42 AM" src="https://user-images.githubusercontent.com/5023509/211072003-9040e14c-3ff9-43a9-859a-b70093399816.png">

### Actual result

The dropdown that appears is cut off and only accessible if you scroll within the table's wrapping `div`.  Occurs in versions 2.4.4 and 2.4.5.

<img width="394" alt="Screenshot 2023-01-06 at 8 37 13 AM" src="https://user-images.githubusercontent.com/5023509/211071976-69653571-307d-4bb5-ba08-87a6f479a376.png">

### Additional information

This appears caused due to the `.data-grid-actions-cell` `position: relative;` that was added to the admin theme file...
vendor/magento/theme-adminhtml-backend/Magento_Ui/web/css/source/module/_data-grid.less.  Removing this appears to correct the issue.

<pre><code>.data-grid-actions-cell {
    padding-left: @data-grid-cell__padding-horizontal * 2;
    padding-right: @data-grid-cell__padding-horizontal * 2;
    <strong>position: relative;</strong>
    text-align: center;
    width: 1%;
}</code></pre>

Screenshot below shows code diff between version 2.4.5-p1 (left) and 2.4.3 (right) where the `position: relative` line was shown as not existing in 2.4.3.
<img width="1234" alt="Screenshot 2023-01-06 at 11 56 34 AM" src="https://user-images.githubusercontent.com/5023509/211072177-f8658d3c-79cf-466f-bd2e-f8d23215fe3f.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment]
This was actually supposed to be "fixed" in one of the recent changelogs (I think **for** 2.4.5) but as with many of the listed "fixes" in the changelogs, it didn't seem to actually make it in there.

It is quite annoying to have to scroll after clicking the select button. Would be nice to have it correctly fixed and stay fixed once and for all. But probably won't see a source fix till 2.4.7 now, maybe.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by schizek** [comment]
In your screenshot you would want to test the last item (in your case "Customer Service").  However, after further review it appears this issue only occurs with "Commerce" and not "Open Source"... I suspect caused during Adobe's rebranding of the admin.

**Comment by engcom-Dash** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5-p1 instance with edition b2b

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5-p1 instance b2b

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5-p1 adobe commerce instance

**Comment by FadedOut** [comment]
> In your screenshot you would want to test the last item (in your case "Customer Service"). However, after further review it appears this issue only occurs with "Commerce" and not "Open Source"... I suspect caused during Adobe's rebranding of the admin.

Nope, it does it with Open Source as well. I'm using the open source version and it was doing it but your file modification worked for me. 

@engcom-Dash with your instance of (2.4.5-p1 instance b2b) go to: Content > Pages. Click SELECT on LAST ITEM (customer service). 

Attaching an image showing it is doing it right on your instance you just requested. I outlined the admin username to show it is that instance as well. And also outlined the exact page/row to test. 

Tried with Firefox & Microsoft Edge (which is chrome based) on Windows 11.

![magento-open-source-245p1-admin-grid-actions-cut-off-example](https://user-images.githubusercontent.com/12685113/211524823-9b8008ab-8fdd-4e5a-bb07-4b8c5086c356.jpg)

**Comment by schizek** [comment]
Thank you for calling that out @FadedOut  I verified I am seeing the same thing on my end.  Although, I have a local version of the 2.4-develop branch running installed via git and this issue does not exist.  However, when I run my composer installed copy of the latest version (2.4.5-p1) the issue is present in Open Source.

**Comment by dekiakbar** [comment]
@magento I am working on this

**Comment by dekiakbar** [comment]
@magento add to contributors team

**Comment by dekiakbar** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
From my opinion remove this will bring back problem with wrong position of dropdown If you move action column to another position instead the last column

**Comment by mrtuvn** [comment]
Instead remove overflow-x property in this line 
https://github.com/magento/magento2/blob/2.4-develop/app/design/adminhtml/Magento/backend/web/css/source/forms/fields/_control-table.less#L28

**Comment by mrtuvn** [comment]
Second way to fix
Remove this property at this file 
https://github.com/magento/magento2/blob/2.4-develop/app/design/adminhtml/Magento/backend/Magento_Ui/web/css/source/module/_data-grid.less#L269

**Comment by CGLOB** [comment]
internal team is started working on it.
**@dekiakbar** Could you kindly inform me if there have been any recent updates that could assist us in moving forward?

**Comment by dekiakbar** [comment]
> @magento internal team is started working on it. **@dekiakbar** Could you kindly inform me if there have been any recent updates that could assist us in moving forward?

Hi @CGLOB there is no recent update from me, you can moving forward, Maybe the internal Magento team should double-check my code, I'm afraid there's code that doesn't comply with magento coding standard. 

Thank you

**Comment by chris-vaimo** [comment]
This appears to be fixed in 2.4.6-p2. A scroll bar now appears for the list, which allows you to scroll down for the last item.

It's not perfect, but it does make the UI usable.
