### ISSUE TITLE
Magento 2.4.5-p1 Reorder issue

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#36739]
Reorder having an issue with Custom option Product

**Preconditions (*)**
Magento version: 2.4.5-p1

**Steps to reproduce (*)**
1.  Create a simple product with a custom option
![image](https://user-images.githubusercontent.com/50168477/212248607-208a2a85-7003-4390-abae-78a1694db9b5.png)
2. Create an account on frontend then order that product
3. go to my order and click to reorder it's showing an error
![image](https://user-images.githubusercontent.com/50168477/212248632-5dd31d28-d0bd-40cc-bf04-9dde4b2105ce.png)

**Expected result (*)**
1. Need to reorder with same data

**Actual result (*)**
1. As per checked no custom option information showing in the order
![image](https://user-images.githubusercontent.com/50168477/212248794-cae25b30-986d-4dac-acd0-71657e09c74e.png)

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @niku0911,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.


**Steps to reproduce**

1.Create a simple product with a custom option
2.Create an account on frontend then order that product
3.go to my order and click to reorder it's showing an error.


We are able to reorder the same product without any error.

<img width="1412" alt="Screenshot 2023-01-13 at 1 48 40 PM" src="https://user-images.githubusercontent.com/51680745/212310950-46410e64-2aa3-4cfc-8d71-87b8c02dc7c4.png">


<img width="1457" alt="Screenshot 2023-01-13 at 1 48 27 PM" src="https://user-images.githubusercontent.com/51680745/212310991-ea8553b1-d3f9-44e6-846d-1415abe55df2.png">


<img width="1344" alt="Screenshot 2023-01-13 at 1 49 57 PM" src="https://user-images.githubusercontent.com/51680745/212311019-78f6397d-9e31-41f9-bcae-1a972a3630ed.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by FadedOut** [comment]
@niku0911 what does the log say for the error? The log will be located as a file on the server here: /public_html/var/log/system.log

For future reference, always post the log (just the error at the time though, no need to post the whole thing), it helps others help you.

**Comment by niku0911** [comment]
HI @FadedOut 
we got below error on system log

[2023-01-13T04:42:49.028492+00:00] main.CRITICAL: TypeError: Magento\Framework\DataObject::__construct(): Argument #1 ($data) must be of type array, null given, called in /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php on line 65 and defined in /home/awarenessplace/public_html/uat/vendor/magento/framework/DataObject.php:39
Stack trace:
#0 /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php(65): Magento\Framework\DataObject->__construct()
#1 /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Model/Reorder/Reorder.php(255): Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter->getInfoBuyRequest()
#2 /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Model/Reorder/Reorder.php(217): Magento\Sales\Model\Reorder\Reorder->addItemToCart()
#3 /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Model/Reorder/Reorder.php(161): Magento\Sales\Model\Reorder\Reorder->addItemsToCart()
#4 /home/awarenessplace/public_html/uat/vendor/magento/module-sales/Controller/AbstractController/Reorder.php(87): Magento\Sales\Model\Reorder\Reorder->execute()
#5 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\AbstractController\Reorder->execute()
#6 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent()
#7 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#8 /home/awarenessplace/public_html/uat/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(23): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins()
#9 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Order\Reorder\Interceptor->execute()
#10 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#11 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent()
#12 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#13 /home/awarenessplace/public_html/uat/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(32): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins()
#14 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Order\Reorder\Interceptor->dispatch()
#15 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#16 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#17 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#18 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#19 /home/awarenessplace/public_html/uat/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#21 /home/awarenessplace/public_html/uat/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#23 /home/awarenessplace/public_html/uat/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /home/awarenessplace/public_html/uat/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /home/awarenessplace/public_html/uat/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#27 /home/awarenessplace/public_html/uat/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /home/awarenessplace/public_html/uat/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#29 {main} [] []

**Comment by FadedOut** [comment]
@magento give me 2.4.5-p1 instance

**Comment by FadedOut** [comment]
@niku0911 Hmm so unfortunately, I may not be able to help - and I hate that :(. I wish I could have given you solution, I was hoping maybe it was because you had it set to 0 characters that maybe it was bugging out - but I copied your custom field exactly and it went through. I'll attach the screenshots and video of my test. And the log you posted I'm not sure why it would be throwing that. 

So you say that the order goes through the first time, but the custom field doesn't show on the order screen (as your screenshot shows)....that is odd, esp that there is no error on the frontend from the first time the order was placed and succeeded only during re-order. Is there any error in the log when you place the order (the first time - not the reorder)? I've had errors appear in the log but show no sign of an error on the UI side. 

![magento-github-topic-reorder-test-screenshot-1](https://user-images.githubusercontent.com/12685113/212460430-ba66243b-d342-48da-b3a3-f7619a57d9f9.jpg)
![magento-github-topic-reorder-test-screenshot-2](https://user-images.githubusercontent.com/12685113/212460437-e7935995-c04c-4cc0-927b-84ff46595cb7.jpg)

https://user-images.githubusercontent.com/12685113/212460444-b77d293e-5d7d-4f25-9d0b-23379a817c05.mp4

**Comment by niku0911** [comment]
Hi @FadedOut,

so might be an issue with 3rd party extension, will check this on our side on this.

**Comment by SerhiiMandrykin** [comment]
Hi. We have almost the same problem, but the log is:
```
InvalidArgumentException: Unable to unserialize value. Error: Syntax error in /magento2/vendor/magento/framework/Serialize/Serializer/Json.php:45
Stack trace:
#0 /magento2/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php(56): Magento\Framework\Serialize\Serializer\Json->unserialize('Laurine')
#1 /magento2/vendor/magento/module-sales/Model/Reorder/Reorder.php(255): Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter->getInfoBuyRequest(Object(Magento\Sales\Model\Order\Item\Interceptor))
#2 /magento2/vendor/magento/module-sales/Model/Reorder/Reorder.php(217): Magento\Sales\Model\Reorder\Reorder->addItemToCart(Object(Magento\Sales\Model\Order\Item\Interceptor), Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Catalog\Model\Product\Interceptor))
#3 /magento2/vendor/magento/module-sales/Model/Reorder/Reorder.php(161): Magento\Sales\Model\Reorder\Reorder->addItemsToCart(Object(Magento\Quote\Model\Quote\Interceptor), Array, '13')
#4 /magento2/vendor/magento/module-sales/Controller/AbstractController/Reorder.php(87): Magento\Sales\Model\Reorder\Reorder->execute('13******103', '13')
#5 /magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\AbstractController\Reorder->execute()
#6 /magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent('execute', Array)
#7 /magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}()
#8 /magento2/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(23): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins('execute', Array, Array)
#9 /magento2/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Order\Reorder\Interceptor->execute()
#10 /magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\Reorder\Interceptor->___callParent('dispatch', Array)
#12 /magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\Reorder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /magento2/generated/code/Magento/Sales/Controller/Order/Reorder/Interceptor.php(32): Magento\Sales\Controller\Order\Reorder\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /magento2/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Order\Reorder\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /magento2/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Sales\Controller\Order\Reorder\Interceptor), Object(Magento\Framework\App\Request\Http))
#16 /magento2/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Sales\Controller\Order\Reorder\Interceptor))
#17 /magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /magento2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#25 /magento2/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#27 /magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#28 {main}
```

**Comment by SerhiiMandrykin** [comment]
The thing is that in `$value = $this->serializer->unserialize($option['option_value']);` the `option_value` is not always a json string
