### ISSUE TITLE
Can not overwrite .js file if a folder with the same name exists

### ISSUE THREAD

**Issue by cartok** [magento/magento2#36730]
### Preconditions and environment

- Magento version: 2.4.4-p2

I stumbled across a problem when I tried to overwrite a file of the checkout that if the file to overwrite exists alongside a folder which the same name, files in the folder can no longer get loaded.

I do not know a workaround for this.

Can someone who is familiar with the mechanism or installation of it investigate it?

### Steps to reproduce

I tried to overwrite `Magento_Checkout/js/view/payment`:
```
const config = {
    map: {
        '*': {
            'Magento_Checkout/js/view/payment': '<Vendor_Module>/js/view/steps/payment/payment',
        }
    }
}
```

### Expected result

My file gets loaded without errors.

### Actual result

Errors when loading the files inside of `js/view/payment/` and my file is not loaded.
![image](https://user-images.githubusercontent.com/22181589/211832854-69616596-6606-432a-8eb5-ad280ea2af19.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @cartok ,

We are trying to reproduce the issue in 2.4-develop instance,But we are not able to reproduce the issue.
We are getting Expected result.

Magento Version 2.4-develop
PHP 8.1
 
We are trying change the file name of the .js file with same name exits of folder and the name is successfully changed.No error showing while changing the file name.

Screenshot:
<img width="1512" alt="Screenshot 2023-01-13 at 7 29 53 AM" src="https://user-images.githubusercontent.com/60198592/212219764-028e0017-d8da-43cb-b39c-f9bab05260fd.png">

Let us know if we are missing anything!!

Thanks!!!

**Comment by cartok** [comment]
Hey @engcom-Dash, thanks for checking. I think you did not test the right thing. Can you test it on the same module maybe? Just as documented? You tested `foo/foo.js` but the issue happens when you want to map a file using `requirejs-config.js` which exists like this:
```
foo/
foo.js
```

**Comment by engcom-Dash** [comment]
Hi @cartok ,
Thanks for collaboration with us,
We can successfully the save file name when we are using "requirejs-config.js".Kindly provide some steps to reproduce this issue...Its helps reproduce the issue faster.

Let us know if we are missing anything!!!

Thanks!!!

**Comment by cartok** [comment]
Okay, thank you. I will test it again later, maybe it's a problem with our setup. Closing it for now
