### ISSUE TITLE
Braintree Transactions Declined When 3DS Enabled

### ISSUE THREAD

**Issue by WebHostingAce** [magento/magento2#36737]
Braintree Transactions Declined with 'Merchant account does not support 3D Secure transactions for card type.' When 3DS Enabled.

Tested on both Magento 2.4.2 and Magento 2.4.3-p1 with Braintree Sandbox and Production accounts. Both Braintree accounts are 3D Secure Enrolled.

### Preconditions (*)

1. Magento 2.4.3-p1
2. Braintree Sandbox or Production account with 3D Secure Enrolled

### Steps to reproduce (*)

Configure Braintree - 

Environment - Production / Sandbox
Payment Action - Intent Sale
Merchant ID -
Public Key -
Private Key -

Enable Card Payments - Yes

Merchant Account ID -

Advanced Fraud Protection - Yes (Please make sure this is enabled on Braintree account as well)

Debug - Yes

CVV Verification - Yes

Credit Card Types - Visa and Master

3D Secure Verification - Yes
Threshold Amount - 0
Verify for Applicable Countries - All Allowed Countries

### Expected result (*)

1. Braintree transaction to go through with 3DS verification.

### Actual result (*)

1. Braintree transaction declined with,

                Braintree\Error\Validation::__set_state(array(
                   '_attribute' => 'merchantAccountId',
                   '_code' => '915131',
                   '_message' => 'Merchant account does not support 3D Secure transactions for card type.',
                )),
In the payment.log

**Comment by ed00001** [comment]
We are having exactly the same issue since yesterday 06:30AM.  Can this be prioritised as urgent?

**Comment by WebHostingAce** [comment]
After testing this issue seems to be coming from Braintree itself and Braintree seems to have fixed this issue now.

Could you please check and confirm @ed00001?

**Comment by ed00001** [comment]
> 

Yes, it was a Braintree issue, we got confirmation from them a few hours ago
