### ISSUE TITLE
error in Pag 663 from manual

### ISSUE THREAD

**Issue by VarinhoPontes** [magento/magento2#3674]
In pag 663 in  Step 2: Begin the Configuration 
1. Expand the PayPal Express Checkout section. Then, tap Configure.- and it is PayPal Payment Solutions and not " express checkout "
   ![1](https://cloud.githubusercontent.com/assets/5529234/13568573/faa7f6be-e459-11e5-88fe-2f98c80f7277.png)

**Comment by ccondra** [comment]
Hi Varinho -- The examples in the user guide are based on a Merchant Location that is set to the United States, so it actually is correct. However, the payment configuration changes slightly for different Merchant Country settings. Also, some of the PayPal payment methods change from country to country.  I'll add a note that your configuration might not exactly match the example in the user guide. -- Thanks! Claire
