### ISSUE TITLE
Braintree Settlement getting error Magento 2.4.5-p1

### ISSUE THREAD

**Issue by niranjan-gondaliya** [magento/magento2#36747]
### Preconditions and environment

- Magento 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Go to Admin Panel
2. Reports >> Sales >> Braintree Settlement

**Error :** 

```
Error: Undefined constant Braintree\PaymentInstrumentType::ANDROID_PAY_CARD in /var/www/html/canvaschamp245p1/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php:49
Stack trace:
```

### Expected result

Braintree Settlement report grid should be showing fine.

### Actual result

**Getting following error.**
```

Error: Undefined constant Braintree\PaymentInstrumentType::ANDROID_PAY_CARD in /var/www/html/canvaschamp245p1/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php:49
Stack trace:
```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by niranjan-gondaliya** [comment]
@magento I am working on this

**Comment by niranjan-gondaliya** [comment]
@magento add to contributors team

**Comment by niranjan-gondaliya** [comment]
@magento I am working on this

**Comment by niranjan-gondaliya** [comment]
Hello,

I have create form and taken clone of magento 2 repo, and setup in local but there is no  PayPal_Braintree, PayPal_BraintreeGraphQl module available.

Thanks,

**Comment by engcom-Lima** [comment]
This issue is duplicate of this [issue.](https://github.com/magento/magento2/issues/35434)

**Comment by niranjan-gondaliya** [comment]
Hello @engcom-Lima ,

Thank you...
