### ISSUE TITLE
Suddenly category product not showing and one category showing product which not assigned to that category 

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#36757]
### Summary

Preconditions:

1. Magento version 2.4.4-p1
2. Migrated data tool M1 1.9.3.2 to M2 2.4.4.-p1
3. Category product assigned into **A** not showing on frontend and category **B** showing product which are not assigned to B
4. Re index , cached all are done

Excepted result:
category show their product with pagination on frontend side

Actual result 
category pages missed-up with product which not assigned and not showing product on category page.

### Examples

Showing other category products
![image](https://user-images.githubusercontent.com/114897672/213618420-974bab41-3a5b-452d-b713-ca98fd3b2ee5.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment]
@hemendrametawolf Out of curiosity, what products show when you go to "Products > Categories" then view the category and select the "Products in category" section. Do the correct products show where they should or is it messed up there as well. 

Maybe try an export of the products and see what it shows in the exported file under categories. Hopefully it's as simple as just misconfigured product categories.

**Comment by engcom-Hotel** [comment]
Hello @hemendrametawolf,

Thanks for the report and collaboration!

For data-migration-related issues we are using the below board:

https://github.com/magento/data-migration-tool/issues

For your convenience, we have created this issue there. You can refer to the below link for the same:

https://github.com/magento/data-migration-tool/issues/909

We are closing this issue from here. Please follow the above URL for any updates on this.

Thanks

**Comment by shikhamis11** [comment]
@magento give me magento 2.4.5 instance with ee

**Comment by shikhamis11** [comment]
https://github.com/magento give me magento 2.4.5 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me magento 2.4.5 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
@magento give me 2.4.5 instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance with edition ee
