### ISSUE TITLE
Can not save Visual Swatch option with different Admin and Default Store Names

### ISSUE THREAD

**Issue by JeremyJacksonTS** [magento/magento2#36750]
### Preconditions and environment

- version: 2.4.1-p1
- If the admin and default store view names do not match then it will throw an error
`Notice: Undefined index: PGHW in /var/www/html/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 241`
This line is inside the prepareOptionLinks function. From what I can tell it is populating a name array with values from a foreach loop with ids and labels. The options array contains contains key value pairs "default store name" : id. The index being selected is from labels[0] which is the admin view name. That index does not exist in the options array. The only way to get the visual swatch to save is to have the admin and default store views match. That doesn't help me if I plan to use a sku and a user friendly label.
<img width="1153" alt="Screenshot 2023-01-16 142539" src="https://user-images.githubusercontent.com/94657155/212774331-34320a6a-cf68-4043-966a-2d60365b6b1c.png">

### Steps to reproduce

1. Create a visual swatch with atleast one option
2. The admin name and default store view names must not match.
3. Name the admin name sku code like "PGHW" and set Default Store View to "Paint Grade Hardwood"
4. the attribute will save if both names match but not if they are different. If I want a sku and separate user freindly label it will not save

### Expected result

Expect that I can save a visual swatch attribute with different admin name and default store view name

### Actual result

Does not save, renders error to page
`Notice: Undefined index: PGHW in /var/www/html/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 241`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @JeremyAtMethodMarketing ,

Thanks for the collaboration.
Verified the issue in 2.4-develop instance...the issue is not reproducible.

Magento ver.2.4-develop
PHP 8.1

Steps:
1.Install magento instance
2.Create Visual swatch with one option
3.Make it as Different admin name and default store view name
4.Try to save swatch 

Screenshots:
<img width="1512" alt="Screenshot 2023-01-17 at 1 23 08 PM" src="https://user-images.githubusercontent.com/60198592/212967111-1c639ec2-e1da-4215-af47-963e07f78eb4.png">
<img width="1512" alt="Screenshot 2023-01-17 at 1 23 27 PM" src="https://user-images.githubusercontent.com/60198592/212967155-ff11f574-3054-4ab4-a271-35fa95d01223.png">
<img width="1512" alt="Screenshot 2023-01-17 at 1 23 37 PM" src="https://user-images.githubusercontent.com/60198592/212967162-d7852516-57e0-49fd-b7ce-8a59da1f8d4f.png">

We got expected result...we can save the swatch without any issue

Let us know if we are missing anything!!!

Thanks!!!

**Comment by JeremyAtMethodMarketing** [comment]
I don't know what you are looking at but that is not what I reported. Make a visual Swatch with a different admin and default store view label and save it will throw an error.
Before I hit save
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/94657155/212969839-765c1309-e539-4bd0-808a-05cdbc3af531.png">
After I hit save 
![image](https://user-images.githubusercontent.com/94657155/212970043-2fe89bf4-0143-4c92-81d5-ea3e66473649.png)

**Comment by JeremyAtMethodMarketing** [comment]
additionally I am on 2.4.3-p1 and using PHP 7.4

**Comment by JeremyAtMethodMarketing** [comment]
@engcom-Dash I see where my original post was confusing can you please take another look at this request.
When creating or editing a Visual Swatch product attribute if both the admin swatch value and default store view swatch value do not match it throws and error. In my above photos I took a screen show of my debugging where the error happens in the code. All of the other attribute types allow for a different admin name and store front name. I am confused why there would be 2 input fields if they must be identical to not throw errors.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/94657155/213014593-fdf753d9-36ac-4b19-9be5-581fcd91b442.png">

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @JeremyAtMethodMarketing ,

Thanks for collaboration with us.
Verified the issue in 2.4-develop instance,Hence we are not able to reproduce the issue...We can save the attribute without any issue while using different admin and default store name.
 Steps:
1.Install Magento instance
2.Go to stores
3.Click on Attributes and Product
4.Create new Attribute with visual swatch
5.Provide different admin and default store name.
6.Save it
Screenshots:
<img width="1512" alt="Screenshot 2023-01-19 at 10 17 15 AM" src="https://user-images.githubusercontent.com/60198592/213359589-0a9055a4-3f3f-45a3-b82b-432813bb9bc6.png">
<img width="1512" alt="Screenshot 2023-01-19 at 10 17 25 AM" src="https://user-images.githubusercontent.com/60198592/213359608-f3e09209-064f-44b0-aa80-112289061a09.png">
 Meanwhile we will verify the issue with 2.4.3-p1 local instance will update the result [ASAP.]

Let us know if we missing anything!!!

**Comment by dverkade** [comment]
This is still an issue and I'm able to reproduce it.

**Comment by JeremyAtMethodMarketing** [comment]
I am not sure why they closed it, the person working on it said they would check on the p1 branch and get back to me. Then the bot closed it before that happened so I am having to use a work around with text swatches. Ideally I would just use a dropdown but dropdowns don't filter images on search and category pages like text and visual swatches do. I am not sure if the recommendation is to just update to a newer branch?
