### ISSUE TITLE
ResetPasswordPost Controller does not redirect, masks error messages

### ISSUE THREAD

**Issue by ehalpin-deg** [magento/magento2#36770]
### Preconditions and environment

- Magento version 2.4.5-p1
- hyva-themes/magento2-reset-theme 1.1.2
- hyva-themes/magento2-theme-module 1.1.17
- hyva-themes/magento2-default-theme 1.1.17

### Steps to reproduce

1. Create a new user account from the frontend at /customer/account/create 
2. After successful account creation, log out and enter the password reset flow by navigating to customer/account/forgotpassword/
3. generate an RP token by entering in the account email address
4. find the email sent by magento and clink on the reset password link 
5. verify that the link contains both the `id` and `token` parameters
6. In order to test this issue you need to do one of the following:
    - remove frontend password validation for character classes on a vanilla magento instance (Hyva only checks that passwords match in `Magento_Customer/form/resetforgottenpassword.phtml`) 
    - add a backend process that will throw an error during password validation (by plugging into `Magento\Customer\Api\AccountManagementInterface::resetPassword` or one of the password validation methods therein)
    - debug the `\Magento\Customer\Controller\Account\ResetPasswordPost` controller and modify the process data to generate an error
 7. Allow the controller to finish execution and handle the error. 

### Expected result

The customer is redirected back to /customer/account/resetpassword with the `id` and `token` parameters present in the redirect link.

The customer should see errors present on the page that were generated in the backend process.

### Actual result

The customer is redirected to  /customer/account/createpassword with only the `token` parameter 
The customer is then immediately redirected to the /customer/account/forgotpassword page and an error displays: `Your password reset link has expired.`

### Additional information

Our instance has additional security checks on password strength and character classes implemented in a custom module. This module will cause password validations to fail and users are never shown the password feedback messages on the frontend, which causes considerable confusion among customers. 

We have implemented a patch that fixes the redirect issue so customers are able to view error messages and attempt to create a new password again without seeing the `Your password reset link has expired.` message.

```
diff --git a/Controller/Account/ResetPasswordPost.php b/Controller/Account/ResetPasswordPost.php
--- a/Controller/Account/ResetPasswordPost.php	2023-01-23 13:50:41
+++ b/Controller/Account/ResetPasswordPost.php	2023-01-23 14:00:36
@@ -75,13 +75,13 @@

         if ($password !== $passwordConfirmation) {
             $this->messageManager->addErrorMessage(__("New Password and Confirm New Password values didn't match."));
-            $resultRedirect->setPath('*/*/createPassword', ['token' => $resetPasswordToken]);
+            $resultRedirect->setPath('*/*/createPassword', ['id' => $customerId, 'token' => $resetPasswordToken]);

             return $resultRedirect;
         }
         if (iconv_strlen($password) <= 0) {
             $this->messageManager->addErrorMessage(__('Please enter a new password.'));
-            $resultRedirect->setPath('*/*/createPassword', ['token' => $resetPasswordToken]);
+            $resultRedirect->setPath('*/*/createPassword', ['id' => $customerId, 'token' => $resetPasswordToken]);

             return $resultRedirect;
         }
@@ -123,7 +123,7 @@
         } catch (\Exception $exception) {
             $this->messageManager->addErrorMessage(__('Something went wrong while saving the new password.'));
         }
-        $resultRedirect->setPath('*/*/createPassword', ['token' => $resetPasswordToken]);
+        $resultRedirect->setPath('*/*/createPassword', ['id' => $customerId, 'token' => $resetPasswordToken]);

         return $resultRedirect;
     }

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5-p1 instance

**Comment by engcom-Hotel** [comment]
Hello @ehalpin-deg,

Thanks for the reporting and collaboration!

We are working on this issue and are stuck on the below steps. Please elaborate the below point, so that we will move forward with this:

> In order to test this issue you need to do one of the following:
> * remove frontend password validation for character classes on a vanilla magento instance (Hyva only checks that passwords match in `Magento_Customer/form/resetforgottenpassword.phtml`)
> * add a backend process that will throw an error during password validation (by plugging into `Magento\Customer\Api\AccountManagementInterface::resetPassword` or one of the password validation methods therein)
> * debug the `\Magento\Customer\Controller\Account\ResetPasswordPost` controller and modify the process data to generate an error

Thanks

**Comment by engcom-Hotel** [comment]
Dear @ehalpin-deg,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
