### ISSUE TITLE
Wysiwyg editor not working

### ISSUE THREAD

**Issue by nehadnb** [magento/magento2#36775]
### Preconditions and environment

- Magento 2.4.5-p1
- Go to Marketing > Newsletter Template > Create New Template > Template Content > Show/Hide button is not working

![image](https://user-images.githubusercontent.com/109754993/214392214-eb145f07-8882-4820-914b-2441ef956160.png)

Also View page source scripts tag look like this (Not sure why it is like that, maybe cause of issue) - 
![image](https://user-images.githubusercontent.com/109754993/215545465-4e735172-da99-4053-aa2a-fecc2d42d200.png)

### Steps to reproduce

Go to Admin >  Marketing > Newsletter Template > Create New Template > Template Content > Show/Hide button is not working

### Expected result

Show/Hide button work properly

### Actual result

Show/Hide button not working, giving console error - Uncaught ReferenceError: require is not defined 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nehadnb** [comment]
@magento give me 2.4-develop instance

**Comment by nehadnb** [comment]
It is not reproducing in Magento instance, I found same issue in Magento 2.4.5-p, 2.4.4, 2.4.3-p1 (does not have any 3rd party module which cause issue in Wysiwyg ) and issue will come if view page source "script" tag show like this - <script type="62e5490dd6e6a71921848a2a-text/javascript">

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @nehadnb ,

Verified the issue in 2.4-develop instance...We are not able reproduce the issue.
Magento version 2.4-develop
PHP 8.1

Steps:
1.Install magneto instance
2.Go to Marketting
3.Click on News letter template
4.Add new template
5.Click on Show/hide Editor button
Show/hide Editor button is Working properly without any issue.
Screenshots:
<img width="1512" alt="Screenshot 2023-02-08 at 2 59 51 PM" src="https://user-images.githubusercontent.com/60198592/217496781-adcd7aaf-9577-499e-a813-e39b108fff60.png">
<img width="1512" alt="Screenshot 2023-02-08 at 3 00 41 PM" src="https://user-images.githubusercontent.com/60198592/217496900-708439bd-5a5a-461e-839f-52704a418ff8.png">

Let us know if we missing anything
thanks!!!

**Comment by nehadnb** [comment]
Able to solve the issue, It is not magento issue,  it is cloudflare setting Rocket Loader enable is causing issue
