### ISSUE TITLE
Page has come up as presenting weird words, numbers. Not how it was earlier in the day

### ISSUE THREAD

**Issue by dawnbatten** [magento/magento2#36772]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Dnd-Bazak** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dawnbatten,


Thank you for reporting and collaboration.

To speed up the processing of this issue, please provide us with the following information:
* Summary of the issue
* Information on your environment
* Steps to reproduce
* Expected and actual results


Thanks

**Comment by engcom-Bravo** [comment]
Hi @dawnbatten,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
