### ISSUE TITLE
Related Product Rules don't work for Product Category is the Same as Matched Product Category

### ISSUE THREAD

**Issue by tomasz-mroczkowski-lingaro** [magento/magento2#36771]
### Preconditions and environment

Adobe Commerce ver. 2.4.5-p1

### Steps to reproduce

Releated products 
1. Go to the setting page - Marketing -> PROMOTIONS -> Related Products Rules
2. Create a new rule
3. In Rule Information set: 
    - Status: **Active**
    - Apply to: **Related Products**
4. In Products to Match leave empty - it should match all products
5. Products do Display - **Product Category is the Same as Matched Product Category**

The code from the responsible method **Magento\TargetRule\Model\ResourceModel\Index::_prepareRuleActionSelectBind** doesn't even try to figure out the current product category:
![Zrzut ekranu z 2023-01-24 13-07-46](https://user-images.githubusercontent.com/60344314/214288025-3c1c174d-7d61-45d3-8e36-5de638614bfe.png)
It assumes that if **Product Category** is choosen then category ids was provided as well.

### Expected result

Related products from the same category as the current should be visible.

### Actual result

No products are visible.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tomasz-mroczkowski-orba** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by waelkensy** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @tomasz-mroczkowski-orba 

Thanks for reporting the ticket.
As per described steps, we retest and found that the issue is not reproducible on instance 2.4.x Develop.
hence to understand more about your expected result kindly please help us to describe more on the use case you are trying to achieve.

**Attachment**
<img width="1333" alt="Screenshot 2023-02-17 at 12 16 51 PM" src="https://user-images.githubusercontent.com/51679138/219570918-7ca7da25-e1dd-4e72-bf75-79dd7d25c457.png">

**Comment by tomasz-mroczkowski-orba** [comment]
Hi @engcom-Alfa 

the problem exists in Adobe Commerce ver. 2.4.5-p1. As far as I see there is no Marketing -> PROMOTIONS -> Related Products Rules configuration in Magento Community version.

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions b2b/b2b

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by engcom-Alfa** [comment]
Hi @tomasz-mroczkowski-orba 

Thanks for replying to my last comment.
As per your following comment, we retested and we are still not able to reproduce the issue on instance 2.4.x Develop which is ahead instance of all the current instances. hence humbly request, please try to check this use case on the latest instance.

**Video Attachment for above**

https://user-images.githubusercontent.com/51679138/220886224-95ba33d9-c3ac-4b5b-a36f-772163dfc2d1.mp4

**Comment by tomasz-mroczkowski-orba** [comment]
Thank you @engcom-Alfa indeed, it looks like it works well on 2.4.x Develop so probably it is outdated. I will compare these versions, my Adobe Commerce ver. 2.4.5-p1 and new one 2.4.x Develop, maybe it is already fixed or maybe I was wrong, Ill check it. Thanks for the support.

**Comment by tomasz-mroczkowski-orba** [comment]
As far as it is not replicable in the 2.4.x Develop I'm closing this thread.
