### ISSUE TITLE
Price indexers make queries flood MariaDb until the site drops (Please reopen #36667)

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#36780]
Today I faced this issue again and caught it really early and briefly I noticed that the holdup came when the indexer was renaming price tables to _outdated or something like this I'm assuming to move the replica table into it's place. 

During these rename queries, the other queries started piling up and the system dropped. 

On my system the price tables are fairly large now. 

![image](https://user-images.githubusercontent.com/20220341/214559416-8ad3fff7-364a-493c-8341-c4d697bbeb08.png)

So renaming a table like this would most likely take considerable time. 

This is a followup on #36667

**Comment by ioweb-gr** [comment]
Normally rename shouldn't take that long to execute unless the table is locked. I think there are multiple locks placed on the tables during price indexing which cause deadlock and that's why rename gets stuck there. When the rename got finished, all other queries finished fast. 
Is it possible the table is locked both by the rename process and the scheduled indexers processing prices at the same time causing the deadlock? 

We're really buffled as to what is causing these random downtimes due to this and eliminated all other factors we could

**Comment by engcom-Dash** [comment]
Hi @ioweb-gr ,

Kindly Provide Additional Information About this issue...It's very easy to proceed further.So Kindly Update below information 
1.Steps to reproduce
2.Precondition
3.Actual result
4.Expected Result.

Thanks.

**Comment by ioweb-gr** [comment]
@engcom-Dash The problem is I can't find the proper steps to reproduce. Could you please provide any input as where those queries could be coming from so we can add some logs perhaps that can help us find the steps to replicate?

**Comment by engcom-Dash** [comment]
Hi @ioweb-gr ,

We are closing this issue, It seems like its a duplicate  and we are following the parent issue (https://github.com/magento/magento2/issues/36667).

Thanks.
