### ISSUE TITLE
Issue during reindex catalog_product_attribute

### ISSUE THREAD

**Issue by nbdat22** [magento/magento2#36797]
### Preconditions and environment

- Magento 2.4.5-p1

### Steps to reproduce

Run reindex catalog_product_attribute
`bin/magento indexer:reindex catalog_product_attribute`

### Expected result

The reindexing process should complete without any error

### Actual result

Reindex through error:
```
Product EAV index process error during indexation process:
There is no active transaction

Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in...
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrkhoa99** [comment]
@NguyenBaDat99 please, reset all indexes. And try to run the reindex again.

**Comment by mrkhoa99** [comment]
The issue can be multi index processes are running at the same time. We can try to show processlist from database to see related queries and kill them.

**Comment by NguyenBaDat99** [comment]
@mrkhoa99 
I have tried as you said, reset all indexes but no help.
Also, I checked the processlist, but no helpful information.

I have done some research and it seems like the issue is related to Implicit Commit - https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

The issue occurred in file `\Magento\Catalog\Model\Indexer\Product\Eav\Action\Full::syncData` 
When moving the line `$sourceTable = $indexer->getIdxTable();` outside of the transaction-commit block, the issue has gone.

That is some information from my side.

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @NguyenBaDat99 

as per the our's current limitation, we can only verify the issue on the 2.4-develop instance

**Comment by NguyenBaDat99** [comment]
@engcom-Alfa 
Thank you for your support!
Seem like the issue does not occur in another version. 

Then I will use this approach as a temporary solution until able to upgrade to the latest version or can find out the proper solution.
> The issue occurred in \Magento\Catalog\Model\Indexer\Product\Eav\Action\Full::syncData
When moving the line $sourceTable = $indexer->getIdxTable(); outside of the transaction-commit block, the issue has gone.
