### ISSUE TITLE
Shipping discount does not get included in a new invoice if earlier invoice with the discount is cancelled. 

### ISSUE THREAD

**Issue by higuhi** [magento/magento2#36792]
### Preconditions and environment

- Magento version: 2.4.5-p1 (Vanilla Magento 2 with Sample Data)
- PHP Version: 8.1.2
- Maria DB: 10.4
- Apache: 2.4.52
- Composer: 2.2.6
- ElasticSearch: 7.17.8

### Steps to reproduce

In _[app/code/Magento/Sales/Model/Order/Invoice.php](https://github.com/magento/magento2/blob/bd8634b736c1df250a288727107610ddfef963a3/app/code/Magento/Sales/Model/Order/Invoice.php#L36)_, three invoice states are defined. 

```
    /**#@+
     * Invoice states
     */
    const STATE_OPEN = 1;

    const STATE_PAID = 2;

    const STATE_CANCELED = 3;
```

And, in _[app/code/Magento/Sales/Model/Order/Invoice/Total/Discount.php](https://github.com/magento/magento2/blob/bd8634b736c1df250a288727107610ddfef963a3/app/code/Magento/Sales/Model/Order/Invoice/Total/Discount.php#L29)_, the `Discount::collect()` function checks if the shipping discount has already been invoiced with the private function `Discount::isShippingDiscount()` 

```
        /**
         * Checking if shipping discount was added in previous invoices.
         * So basically if we have invoice with positive discount and it
         * was not canceled we don't add shipping discount to this one.
         */
        if ($this->isShippingDiscount($invoice)) {
            $totalDiscountAmount = $totalDiscountAmount + $invoice->getOrder()->getShippingDiscountAmount();
            $baseTotalDiscountAmount = $baseTotalDiscountAmount +
                $invoice->getOrder()->getBaseShippingDiscountAmount();
        }
```

Then, the [function](https://github.com/magento/magento2/blob/bd8634b736c1df250a288727107610ddfef963a3/app/code/Magento/Sales/Model/Order/Invoice/Total/Discount.php#L89) loops the invoice collection if the shipping discount has been applied to earlier invoices. 

```
    private function isShippingDiscount(Invoice $invoice): bool
    {
        $addShippingDiscount = true;
        foreach ($invoice->getOrder()->getInvoiceCollection() as $previousInvoice) {
            if ($previousInvoice->getDiscountAmount()) {
                $addShippingDiscount = false;
            }
        }
        return $addShippingDiscount;
    }
```

The condition to test the discount amount should also test if the invoice is not `Canceled` in case the invoice, for some reason, has been removed because the new invoice needs to add the shipping discount which has been canceled.

So, it should be...

```
    private function isShippingDiscount(Invoice $invoice): bool
    {
        $addShippingDiscount = true;
        foreach ($invoice->getOrder()->getInvoiceCollection() as $previousInvoice) {
            if ($previousInvoice->getState() != \Magento\Sales\Model\Order\Invoice::STATE_CANCELED && $previousInvoice->getDiscountAmount()) {
                $addShippingDiscount = false;
            }
        }
        return $addShippingDiscount;
    }
```

**Steps to produce**

1. Deploy the sample data 
2. Navigate MARKETING > Cart Price Rules
3. Create a discount that applies to the shipping amount. For example, this is a discount on Shipping Fee when the order has more than 10 items: 
    - Under Conditions: Total Items Quantity equals or greater than 10, 
    - Under Actions: 
       - Apply: Percent of product price discount 
       - Discount Amount: 30
       - Apply to Shipping Amount: Yes  <--- this is important
2. Create an order to get the shipping discount
5. Make a partial invoice  (this will create an invoice with shipping & handling with the discount) 
6. Somehow change the state of the invoice to "STATE_CANCEL" (the easier way is by directly changing the state from DB)
     ```
     UPDATE sales_invoice SET state = 3 WHERE entity_id = {entity id of the invoice};
     UPDATE sales_invoice_grid SET state = 3 WHERE entity_id = {entity id of the invoice};
     ```
8. Make the invoice for the remaining (this will create an invoice without the discount on the shipping & handling fee)

NOTE: the above steps use "partial invoice" only to make the reproduction of the issue easier. It is possible to reproduce with a standard full invoice but you must somehow cancel the invoice and also revert the invoiced quantity of each product line in the order so that the order can be invoiced again. 

### Expected result

The invoice should include the discount on shipping if the earlier invoices with the discount have been canceled. 

### Actual result

The shipping discount does not get included in the subsequent invoices if the earlier "Cancelled" invoice includes the shipping discount. 

### Additional information

Although it is not possible to have an invoice with the state, STATE_CANCELED, in the vanilla Magento setup, the state is defined in the code and some payment gateways make use of the state to indicate the issue in the payment capture. 

In such cases, Magento Core should check for the state of the invoice and ignore those canceled invoices, so that the shipping discount is correctly included when the invoice for the order is re-issued.  (The comment in the code says that "So basically if we have invoice with positive discount and **it was not canceled** we don't add shipping discount to this one." )

### Release note

Additional validation of the invoice state so that a new invoice includes the shipping discount if the earlier invoices with the discount are canceled.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @higuhi,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance.Kindly refer the screenshots.

**Steps to produce**

1.Deploy the sample data
2.Navigate MARKETING > Cart Price Rules
3.Create a discount that applies to the shipping amount. For example, this is a discount on Shipping Fee when the order has more than 10 items:
    Under Conditions: Total Items Quantity equals or greater than 10,
    Under Actions:
    Apply: Percent of product price discount
    Discount Amount: 30
    Apply to Shipping Amount: Yes <--- this is important
4.Create an order to get the shipping discount
5.Make a partial invoice (this will create an invoice with shipping & handling with the discount)

<img width="970" alt="Screenshot 2023-02-15 at 6 40 38 PM" src="https://user-images.githubusercontent.com/51680745/219036852-b9095e2b-86ba-4f76-bfe9-cb0e2b1653e7.png">



6.Somehow change the state of the invoice to "STATE_CANCEL" (the easier way is by directly changing the state from DB)
```
UPDATE sales_invoice SET state = 3 WHERE entity_id = {entity id of the invoice};
UPDATE sales_invoice_grid SET state = 3 WHERE entity_id = {entity id of the invoice};
```

<img width="1079" alt="Screenshot 2023-02-15 at 6 41 04 PM" src="https://user-images.githubusercontent.com/51680745/219036734-8b080552-202e-4abc-8637-f059e21a3605.png">




7.Make the invoice for the remaining (this will create an invoice without the discount on the shipping & handling fee)


<img width="1029" alt="Screenshot 2023-02-15 at 6 41 24 PM" src="https://user-images.githubusercontent.com/51680745/219036889-e02b7fbd-76a2-4078-9a48-fca0ecd6c0cb.png">



Kindly elaborate expected and actual result.Where Shipping discount will get included in new invoice, and please let us know if we missed anything.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @higuhi,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
