### ISSUE TITLE
[2.4.5-p1] PayPal Express Checkout - Missing SKU & Full product [variation] title

### ISSUE THREAD

**Issue by FadedOut** [magento/magento2#36808]
### Preconditions and environment

- Magento 2.4.5-p1
- PHP8.1
- PayPal Express Checkout (Sandbox or Live) (the included extension)

### Steps to reproduce

1. Enable PayPal Express Checkout [sandbox or live, the result is the same so just do sandbox for this test]
2. Enable "Transfer Cart Line Items"
3. Enable "PayPal Guest Checkout"
4. Submit Order (by credit card using a test number provided [HERE](https://developer.paypal.com/api/rest/sandbox/card-testing)). It is the same end result using a PayPal personal account but for testing purposes just use a test credit card for easier testing.
5. Check PayPal transaction in PayPal sandbox account (not Magento)

### Expected result

When viewing the PayPal transaction in the PayPal account, it should say one of the following:

-Men's T-Shirt-Red, S
-Men's T-Shirt-Red, M
-Men's T-Shirt-Red, L
-Men's T-Shirt-Red, XL

For instance, it should say "SKU 12345678 | Men's T-Shirt-Red, M | QTY 5". It should also show (or have) the SKU included with the line item. 

Pretty sure WooCommerce does exactly that so I'm pretty certain PayPal is capable of taking that information.

### Actual result

Neither are there. What actually shows is this:

Men's T-Shirt QTY 5

That is it. I will attach a screenshot of what I mean. There is no SKU with the item nor is the correct/actual item listed. It simply lists the parent product (Men's T-Shirt) when it was one of it's variants that was purchased (like Red, M or Red, L, etc.). The Magento order transaction page shows all that. But it's like it's not sending it to PayPal?

I just noticed this important missing information. It's very important when it comes to transaction logs and doing taxes. As I am now just noticing this, I realize this is going to be a disaster when doing taxes as there is no real way of me knowing what the COGS was (having no SKU or proper product title I can't sync it to a costs sheet and figure out what my actual net revenue was).

![magento-245p1-paypal-missing-sku-product-title-details-screenshot-1](https://user-images.githubusercontent.com/12685113/216809066-74d732d1-8012-449e-bff8-16820c259c07.jpg)

### Additional information

I will test this on a 2.4-dev instance and see but I don't think it will change - it seems like it might have been like this for a long time now.

Thank you in advance. Hopefully someone can point me to a fix for this so I can get my transaction logs reporting correctly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment]
@magento give me 2.4-develop instance

**Comment by FadedOut** [comment]
Appears to be the same result. Will not show the SKU or variation title.

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions magento/Payment methods

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions payment methods/PayPal Express

**Comment by aasim110** [comment]
@magento I'm working on this

**Comment by FadedOut** [comment]
@aasim110 

Thank you for taking up this task. I think it's an incredible oversight not to have Magento send this information to PayPal for proper record keeping in PayPal (revenue reporting). I don't know how others work around this missing information while using PayPal.
