### ISSUE TITLE
test bots

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#36805]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

asd

### Expected result

asd

### Actual result

asd

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment]
@magento give me 2.4-develop instance

**Comment by FadedOut** [comment]
@magento give me 2.4.5-p1 instance
