### ISSUE TITLE
advanced  search shows custom attributes with search=no

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#36807]
### Preconditions and environment

- Magento version 2.4.4-p2

### Steps to reproduce

Add a custom attribute with storefront-properties:

- **use in search = no**
- compatable in storefront = true
- Visible on Catalog Pages on Storefront = true
- used for Sortinr in product listing = true

### Expected result

custom search does not offer this attribute as a search criteria

### Actual result

custom **does** not offer this attribute as a search criteria

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by YiffyToys** [comment]
@magento give me 2.4-develop instance

**Comment by YiffyToys** [comment]
I can not reproduce the issue on the test instance.
On our instance it got away for each attribute by editing and saving that attribute, then reloading cache.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @YiffyToys,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and we are not able to reproduce the issue..

**Steps to reproduce**

Add a custom attribute with storefront-properties:

1.use in search = no
2.comparable in storefront = true
3.Visible on Catalog Pages on Storefront = true
4.used for Sorting in product listing = true


https://github.com/magento/magento2/issues/36807#issuecomment-1416805124 as per the latest issue is not reproducible from your side.can you please confirm can we close this issue.

Thanks.

**Comment by YiffyToys** [comment]
Sure.
I don't know what your waiting time is, if anybody comes up witht the same issue and more information.
Feel free to close it.
