### ISSUE TITLE
Clover plugin does not show up in checkout

### ISSUE THREAD

**Issue by Jessmaxim303** [magento/magento2#36816]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Hotel** [comment]
Hello @Jessmaxim303,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by Jessmaxim303** [comment]
Thank you for your response,
I will get you this info first thing in the morning.

Thanks!
-Jess

**Comment by engcom-Hotel** [comment]
Dear @Jessmaxim303,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
