### ISSUE TITLE
Magento 2.0.2 Authorize.net DPM not working

### ISSUE THREAD

**Issue by binhton** [magento/magento2#3681]
I have upgraded my store to 2.0.2, and now the Authorize.net DPM not working.  When submitting the order in Admin interface using credit card, the "Please Wait" message keeps spinning forever.  It worked well before in 2.0.  Anyone has similar issue?

**Comment by alena-marchenko** [comment]
Hi,
Please  enable debug for Authorize.net and provide us with magento debug logs, browser console error logs for us to be able to investigate the issue.

**Comment by binhton** [comment]
Here is the debug file.  I replaced the Name/Address/Phone to test info for privacy reason.
[debug.log.txt](https://github.com/magento/magento2/files/165447/debug.log.txt)

**Comment by alena-marchenko** [comment]
The log file file doesn't contain response from Authorize.net. Please enable dev tools in your browser and provide us with browser console errors if any and observe requests to Authorize.net for errors in response in browser Network section.

**Comment by ovdev1** [comment]
a good hint is to check the response from the iframe id=authorizenet_directpost-transparent-iframe

**Comment by alena-marchenko** [comment]
Closing this issue due to no response, please reopen when you have an update.
