### ISSUE TITLE
Magento2 should have setter dependency injection

### ISSUE THREAD

**Issue by degaray** [magento/magento2#3682]
There should be a way to inject dependencies and have Magento2 call a setter. Some third party classes are done this way so it would be very good to have this feature. See [Symfony3 injection](http://symfony.com/doc/current/components/dependency_injection/types.html#setter-injection) for more idea.
## Steps to reproduce
1. Try to inject into Magento2 a Writer object set with a PNG of width and height equals to 256 using this package: [BaconQrCode](https://github.com/Bacon/BaconQrCode)
## Expected result
1. It should be a usable object ready to paste the message and get the QR. Instead I will need to create a constructor class actually extending from PNG.
## Actual result
1. Not feasible

**Comment by antonkril** [comment]
In magento 2 all objects should be ready for use immediately after instantiation. Also most of our services are immutable, they don't change state after creation. Setter injection contradicts both these concepts, so is not supported.

Setter injection leads to broken encapsulation and temporal coupling. You should not use it in your objects. If you need different instances of one class configured with different dependencies, you can use [argument configuration](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html#dep-inj-mod-type-args).

You can get more details in post by @alankent: http://alankent.me/2015/03/03/why-i-prefer-constructor-injection-over-setter-or-property-injection/

**Comment by degaray** [comment]
I agree on that, however, some already made third-party libraries use that principle and it can become handy for using such libraries.

**Comment by antonkril** [comment]
It's always a good practice to use adapters for third-party system interfaces to allow implementation substitutions and made upgrades easier.
