### ISSUE TITLE
Integration with Kingswaysoft

### ISSUE THREAD

**Issue by bhpatelsynoptek** [magento/magento2#36832]
I want to connect magento in Kingsway connection manager but i am getting error as attached.
also my demo version is showing me SSL certificate error.
![Magento](https://user-images.githubusercontent.com/124891001/217819690-85ac4581-0e4f-44ea-b79c-c4296960b527.jpg)

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Dash** [comment]
Hi @bhpatelsynoptek ,

Kindly attach details below
1.Preconditions
2.Steps to reproduce
3.Actual result
4.Expected result
Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @bhpatelsynoptek ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
