### ISSUE TITLE
Google Universal Analytics becoming obsolete

### ISSUE THREAD

**Issue by gondas33** [magento/magento2#36843]
### Preconditions and environment

Latest Magento 2 Open Source version

According to https://support.google.com/analytics/answer/11583528?hl=en , Universal Analytics will completely stop processing any hits, therefore making 'Google API' section From Configuration -> Sales, obsolete.

I believe Magento 2.4 should replace the current UA(Universal Analytics) with GTM, given that UA is becoming **obsolete**. I understand the Magento 2 Commerce already has GTM support.

### Steps to reproduce

1. Open Configuration
2.  Go to 'Sales' Section and select 'Google API'
3. First section of the menu contains Universal Analytics support

### Expected result

Replace the obsolete UA implementation with GTM support(conversions tracking, etc.)

### Actual result

Starting July 1, 2023, Universal Analytics will no longer process any hits according to https://support.google.com/analytics/answer/11583528?hl=en

### Additional information

Tracking users' behaviour is a very important necessity for any type of e-commerce platform.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by gwharton** [comment]
GA4 support is in 2.4.5

![image](https://user-images.githubusercontent.com/30697781/218155428-2e437a14-3aba-46df-9198-846395af4e76.png)

**Comment by hostep** [comment]
Yeah indeed

See the info in https://github.com/magento/magento2/issues/35204 & the fix which got included in 2.4.5: https://github.com/magento/magento2/pull/35376

**Comment by gondas33** [comment]
my bad!
