### ISSUE TITLE
Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to que

### ISSUE THREAD

**Issue by Markitgeeks** [magento/magento2#36844]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to queue.

### Steps to reproduce

Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the fil
![image](https://user-images.githubusercontent.com/125063726/218135369-e6ee0b60-d988-467e-917f-9dc3110c6605.png)
e" but nothing is added to queue.

### Expected result

![image](https://user-images.githubusercontent.com/125063726/218135387-12fc6a4b-977d-43ea-a8f6-9811179c871a.png)

Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to que

### Actual result

Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to que

### Additional information

Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to queue.

### Release note

Bug While Exporting product from Magento 2 getting a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" but nothing is added to queue.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @Markitgeeks ,

All the information of Steps to reproduce,Actual result,Expected Result , Release Notes,Additional information is same,So Kindly update correct information with respective fileds.

Thanks

**Comment by engcom-Dash** [comment]
Hi @Markitgeeks ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
