### ISSUE TITLE
Changing Base URL's causes 404 error Admin

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#3684]
## Steps to reproduce
1. Do an installation of Magento 2.0.2
2. Go to phpMyAdmin and change base URL's in core config data
3. Clear cache by emptying contents of var/cache
4. Admin login now produces a 404 error page,

**Comment by daim2k5** [comment]
@bondimedical3 what happend when you change the base_url via admin backend?

**Comment by bondimedical3** [comment]
This is a development site and it is not possible to update the base url via Admin as it redirects to the live website which is not Magento. There is also a thread on the issue. http://magento.stackexchange.com/questions/87038/magento-2-error-404-not-found-at-magento-2-admin-login-page

**Comment by piotrekkaminski** [comment]
@bondimedical3 i assume the stackexchnage answer helped. If not, please open a new issue.
