### ISSUE TITLE
No link to shipping when in payments in checkout in mobile phone view

### ISSUE THREAD

**Issue by cptX** [magento/magento2#36856]
### Preconditions and environment

- Magento version 2.4.5
- Anything else that would help a developer reproduce the bug
Luma theme

### Steps to reproduce

Use a mobile phone or mobile view in browser dev tools
1. Add an item to checkout
1. Go to checkout
1. Fill in the shipping data and click next
1. Being in payment mode there is no way to go back. There is no link to shipping. The checkout titles/links "Shipping" and "Review & Payments" are hidden from the top of the page.

### Expected result

The checkout titles/links "Shipping" and "Review & Payments" should always be visible on top of the page to help users know at which step they are and to allow corrections on the shipping when being in payments.

### Actual result

The checkout titles/links "Shipping" and "Review & Payments" are hidden from the top of the page.
If you rotate your phone or widen the screen in dev tools in browser they show up.

### Additional information

*No response*

### Release note

*No response*

### Triage and priority

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [X] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

**Comment by engcom-Dash** [comment]
Verified the issue in 2.4-develop branch. Hence we are confirming the issue.

Preconditions:
Magento version 2.4-develop
PHP 8.1

Steps To Reproduce:
Tested in mobile view in browser
Add an item to checkout
Go to checkout
Fill in the shipping data and click next
Being in payment mode there is no way to go back. There is no link to shipping. The checkout titles/links "Shipping" and "Review & Payments" are hidden from the top of the page.
Screenshots :
**Actual Result Screenshot:**
![image](https://user-images.githubusercontent.com/60198592/219031956-7637c2ae-5cd3-42a4-bcf5-859b24d36c43.png)
Expected Result Screenshot:
![image](https://user-images.githubusercontent.com/60198592/219032292-2170e571-994d-4598-9a59-2ae3e13f1813.png)
Actual result
The checkout titles/links "Shipping" and "Review & Payments" are hidden from the top of the page.

Expected result
The checkout titles/links "Shipping" and "Review & Payments" should always be visible on top of the page to help users know at which step they are and to allow corrections on the shipping when being in payments.

Thanks.

**Comment by nidhigupta13-ey** [comment]
@magento  I am working on this issue.

**Comment by cptX** [comment]
For your information, "Shipping" and "Review & Payments"  are correctly visible in blank theme. Only in Luma are gone...
Also, if you please find a solution can you please suggest a way to apply this in 2.4.6? I'm planning to update as soon the 2.4.6 get's published and I'm building a theme based on Luma so I need this to function properly...

**Comment by nidhigupta13-ey** [comment]
@cptX sure I will let you know.

**Comment by nidhigupta13-ey** [comment]
@magento I am working on this

**Comment by cptX** [comment]
Hi, this commit will be included in 2.4.6? Can you please guide us how to solve it even temporarily?

**Comment by nidhigupta13-ey** [comment]
@cptX the fix will be available in 2.4 develop branch which is upcoming release. You can take the file from this PR and replace it in your instance (2.4.6).

**Comment by cptX** [comment]
Can you please tell me if this issue is resolved in the stable release 2.4.7?
