### ISSUE TITLE
Module folders location is different in two installations

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3685]
I create a local installation using Composer and all modules are located under vendor folder.

However, I tried a Bitnami installation in the cloud, and some modules appear under app/code/Magento folder, and other under vendor folder.

Why are they located in different installations? both version 2.0.2

(attached images from the bitnami installation)

Thank you
![vendor](https://cloud.githubusercontent.com/assets/8398744/13593756/c7121496-e4c3-11e5-8eea-091327f5abdb.jpg)
![appcode](https://cloud.githubusercontent.com/assets/8398744/13593758/c87668c8-e4c3-11e5-998a-d80c2d4f94dd.jpg)

**Comment by mazhalai** [comment]
Depending of what your role is, as an SI, or a merchant, or a contributing developer, you can deploy Magento in a [number of ways](http://devdocs.magento.com/guides/v2.0/install-gde/continue.html). 

In this case, when using `composer create-project` Magento code base is in the vendor directory. But if you git clone, the file structure is different, which is what I suspect Bitnami is using. Git clone is only meant for contributing developers, i.e. developers who want to submit PRs to the magento code base. It is not recommended for production.

However, this is not really a bug, so I am closing this issue. Please feel free to open new issues if problems arise.
