### ISSUE TITLE
Instalation problems? 

### ISSUE THREAD

**Issue by thomveen** [magento/magento2#36851]
i have a servoral problems:

Your web server is set up incorrectly and allows unauthorized access to sensitive files. Please contact your hosting provider.

One or more of the Cache Types are invalidated: Configuration. Please go to [Cache Management] and refresh cache types.

One or more [indexers are invalid]. 

Make sure your [Magento cron job] is running.

What can I do with these problems.

I cant see any products

www.smarthuis.shop/magento/

**Comment by hostep** [comment]
Hi @thomveen

Github is meant for reporting bugs in Magento, not really for asking for assistance, it's better if you use https://magento.stackexchange.com/ or https://community.magento.com/ for this 🙂 
Or just try your favorite search engine, pretty sure you'll find many answers over there as well.

As for your issues:
> Your web server is set up incorrectly and allows unauthorized access to sensitive files. Please contact your hosting provider.

See https://magento.stackexchange.com/q/101469/2911, if this sounds complicated, you should contact your hosting company to help you out.

> One or more of the Cache Types are invalidated: Configuration. Please go to [Cache Management] and refresh cache types.

Well, do as being told, in the backoffice refresh your caches and you should be good

> One or more [indexers are invalid]. Make sure your [Magento cron job] is running.

Make sure your crontab is setup to run `bin/magento cron:run` every minute, if this sounds complicated, you should contact your hosting company to help you out.

If a couple minutes after setting up the crontab, your indexers are still invalid, try running `bin/magento indexer:reindex`, that should fix them.


But as I mentioned in the beginning, you shouldn't really expect more feedback here in github for such questions. It's better to first search around a bit for help and ask questions in other places.

Thanks and good luck! 🙂

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution & collaboration over here.

Hi @thomveen,

Thank you for reporting and collaboration.
Kindly follow this comment https://github.com/magento/magento2/issues/36851#issuecomment-1427026362 and let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @thomveen,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
