### ISSUE TITLE
The meta title does not exist in the meta references

### ISSUE THREAD

**Issue by gabi77** [magento/magento2#36867]
Hello,

Preconditions and environment

    Magento version 2.4.5
    PHP 8.1

In the head of the site we visualize the following code:
`<title>My title</title>`
`<meta name="title" content="My title" />`

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

This information should be removed from the file

magento/framework/View/Page/Config.php

Line 48 : public const META_TITLE = 'title';

**Comment by engcom-Hotel** [comment]
Hello @gabi77,

Thanks for the report and collaboration!

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results


Thanks

**Comment by engcom-Hotel** [comment]
Dear @gabi77,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
