### ISSUE TITLE
setup:db:status doesn't take into account mview changes

### ISSUE THREAD

**Issue by SirLyoshyk** [magento/magento2#36860]
### Preconditions and environment

- 2.4.5
- scheduled indexer mode

### Steps to reproduce

1. Add a custom entry to mview.xml
2. Flush caches
3. Check database status by command: setup:db:status

### Expected result

It must report that "Schema is not up to date"

### Actual result

It reports that "All modules are up to date."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by SirLyoshyk** [comment]
@magento give me 2.4-develop instance

**Comment by SirLyoshyk** [comment]
@magento give me ssh access

**Comment by SirLyoshyk** [comment]
@engcom-Bravo How can I confirm this issue on the 2.4-develop branch?
I need access to the ssh and the app/code folder to add the required modifications.

**Comment by engcom-Hotel** [comment]
Hello @SirLyoshyk,

Thanks for the report and collaboration!

We have gone through the description as well as the documentation here related to [Mview](https://developer.adobe.com/commerce/php/development/components/indexing/#mview).

As per the documentation, the mview.xml file is used to track database changes for a certain entity but not to track the changes of the mview.xml file. It seems to us an expected behavior.

Please let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @SirLyoshyk,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by SirLyoshyk** [comment]
Hello @engcom-Hotel ,

I think that such behavior can lead to misunderstandings.
As a user, I expect the "setup:db:status" command to show all required pending database operations. Without triggering the database upgrade process, all changes added to mview will not be applied.
Therefore, the "setup:db:status" command should notify about all pending changes, regardless of their source.

Regards,
Oleksiy.
