### ISSUE TITLE
How to change the SKU with REST API?

### ISSUE THREAD

**Issue by antsem88** [magento/magento2#3687]
Call: 
PUT /rest/V1/products/{sku}

Request:
{
  "product": {
    "sku": "modified.sku",
    "name": "modified name"
  }
}
Result:
The name has changed, but the sku is the same. How can I change the product sku?
Thanks

**Comment by choukalos** [comment]
SKU is a unique key for products, it can't be changed via the API.  Our reasons for doing this is based on feedback from partners integrating to ERP & PIM systems it was desired to have a valid key that can be used by both systems.

**Comment by springimport** [comment]
@choukalos How I can fix this via preference?
