### ISSUE TITLE
Flaky test in B2B module

### ISSUE THREAD

**Issue by hostep** [magento/magento2#36879]
### Preconditions and environment

- Magento `2.4-develop` branch

### Steps to reproduce

Run integration test for `Magento\Company\LoggingTest` around 58/59 seconds after the minute. (this is only guessing here, I just ran into this accidentally)

### Expected result

Test never fails

### Actual result

Test is flaky and seems to depend on 2 different minutes in timestamps:

```
PHPUnit 9.5.20 [44m#StandWith[0m[43mUkraine[0m

Warning:       Using a custom test suite loader is deprecated

..........................................F....II....             53 / 53 (100%)

Time: 05:29.716, Memory: 623.00 MB

There was 1 failure:

1) Magento\Company\LoggingTest::testEditCompanyActionLogging
Failed asserting that '2023-02-16 18:26:59' contains "2023-02-16 18:27".

/var/www/html/dev/tests/integration/testsuite/Magento/Company/LoggingTest.php:301
/var/www/html/dev/tests/integration/testsuite/Magento/Company/LoggingTest.php:88

FAILURES!
Tests: 53, Assertions: 134, Failures: 1, Incomplete: 2.

=== Memory Usage System Stats ===
Memory usage (OS):	787.79M (127.27% of 619.00M reported by PHP)
Estimated memory leak:	168.79M (21.43% of used memory)
```

See https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/eef3786f3239a5598253a3f3f349ee87/Integration/console-error-logs.html

### Additional information

Ran into this while working on https://github.com/magento/magento2/pull/36878

### Release note

Not important to include in release notes

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @hostep , 

Thanks for reporting and collaboration.

Verified the issue in Magento 2.4 dev b2b instance and the issue is not reproducible.

Steps to reproduce:

1.Run integration test for Magento\Company\LoggingTest
2.Verify the result

<img width="1160" alt="Screenshot 2024-04-19 at 7 37 40 PM" src="https://github.com/magento/magento2/assets/51681379/15787e51-e187-401f-818c-cf3c7b7be952">


Please check and let us know if it is reproducible at your end

**Comment by hostep** [comment]
It might depend on the exact second you run the test, it it's close to the 59th or 60th second in a minute.

But anyways, this is an old report, no clue if this still happens occasionally in the github automated test runs, but it did happen when I reported it over a year ago.

But let's close this issue then, if we accidentally see it happening again, we can re-open it again.
