### ISSUE TITLE
Deployment failing due to composer install error on package magento/composer 

### ISSUE THREAD

**Issue by sandipansaha** [magento/magento2#36873]
### Preconditions and environment

Magento version 2.4.5-p1

Since today morning we are seeing the below composer error, due to all the deployments being failed.                                                                                                                                               
  **[Exception]
  Higher matching version 1.9.0 of magento/composer was found in public repository packagist.org than 1.8.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity, please investigate and update package requirement to match the version from the private repository.**

Adobe docs have an article for this, but that is for any 3rd party modules. But how we can manage this for a Magento core module?

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/composer-plugin-against-dependency-confusion-attacks.html?lang=en

### Steps to reproduce

1. Go to magento root and run the following commands -

composer clearcache
rm -rf vendor/*
composer install

### Expected result

composer installs all required modules as per composer.lock successfully

### Actual result

Getting execption -

  **[Exception]
  Higher matching version 1.9.0 of magento/composer was found in public repository packagist.org than 1.8.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity, please investigate and update package requirement to match the version from the private repository.**

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by olehmykhalchenko** [comment]
You can add `"canonical": false` as a hotfix to your magento composer repo.

**Comment by d-afanasiev** [comment]
This problem is also relevant to us.
Please solve it as soon as possible.

**Comment by sandipansaha** [comment]
The workaround works (adobe support is recommending that as well).
But is it safe to set canonical false as in that case, it will download the latest version from the public repository? But what happens if a package is actually compromised and that leads to a security vulnerability?

But it is a Magento core package. In that case why it is not part of the repo.magento.com while it has been published in the packagist?
https://packagist.org/packages/magento/composer

**Comment by davidandersson1** [comment]
We are also facing same issue with magento version 2.4.5-p1

Please let me know once it is fixed.

**Comment by AlexGorelikov** [comment]
Magento 2.4.5 too

**Comment by hostep** [comment]
This issue was fixed a couple of hours ago.

Ticket can be closed as duplicate of https://github.com/magento/composer/issues/34

**Comment by ClintTec** [comment]
Also happening for 2.4.4-p2. Any fix for this?

**Comment by hostep** [comment]
@ClintTec: are you sure, because the issue should have been fixed about 8 to 10 hours before you posted your comment?

**Comment by engcom-Dash** [comment]
Hi @sandipansaha ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.

Steps we followed by:
1.Install Magento Instance
2.Go to the root directory
3.Run below commands
composer clearcache
rm -rf vendor/*
composer install

Screenshots:
<img width="1512" alt="Screenshot 2023-02-17 at 2 25 32 PM" src="https://user-images.githubusercontent.com/60198592/219601979-8dccd7a6-3a22-4858-991b-5f6f7e72b555.png">
<img width="1512" alt="Screenshot 2023-02-17 at 2 36 20 PM" src="https://user-images.githubusercontent.com/60198592/219602006-b7eaea04-e5a2-4dd3-980d-673669dfcdcd.png">

Above mentioned ran successfully without any issue.

Let us know if we missing anything

Thanks

**Comment by engcom-Lima** [comment]
Hi @sandipansaha ,

Thanks for your contribution and collaboration.

Please refer this [comment](https://github.com/magento/magento2/issues/36873#issuecomment-1432894530) for your reference. Please verify this issue in latest "2.4-develop" . If you are facing any issue feel free to contact us.
Closing this issue as duplicate of the https://github.com/magento/composer/issues/34

Thanks
