### ISSUE TITLE
Unable to change date range of sales reports in Vendor Dashboard, or view time &/or value of sales in graph

### ISSUE THREAD

**Issue by Aranea-dictum** [magento/magento2#36889]
### Preconditions and environment

- Magento version 2.4.2
- Unable to change date range of sales reports in Vendor Dashboard, just wont let me. Displays current month and sales value accurately, however can't change from month-week-day, or set a date range. Which is making revenue tracking a bit of a hassle.
- Also does not display date, time or value of actual sales in the graph, which would be handy.
- It is possible to download a list of sales data, which is a perfectly fine if inefficient workaround.

### Steps to reproduce

- Navigate to vendor dashboard.
- scroll down to graph
- attempt to change date range
- (store details redacted)
![magneto bug report 1](https://user-images.githubusercontent.com/125849771/220012882-58d77f36-bf6e-47d1-8a50-90ab83382932.png)
![magneto bug report 2](https://user-images.githubusercontent.com/125849771/220013615-3d47e934-891c-4ca5-ab8a-01d91c3466bd.png)
-Pressing enter or clicking a month has no effect

### Expected result

The date range would change.

### Actual result

The date range does not change.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Aranea-dictum ,
Thank you for reporting and collaboration. However, vendor dashboard is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Comment by Aranea-dictum** [comment]
> Hi @Aranea-dictum , Thank you for reporting and collaboration. However, vendor dashboard is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page Thank you.

That's a good enough lead for me, thanks
