### ISSUE TITLE
Support for multiple select in admin grids

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#369]
It would be nice to be able to filter a grid by a 'select' column using 2 or more values. For example filter the products by 2 attribute sets.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-32674
