### ISSUE TITLE
Composer project bare minimum

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3690]
composer.json like such should be enough to have fully functional M2 CE.

```
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.2"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "minimum-stability": "alpha"
}
```

However one of documented [CRON jobs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html) must execute `update/cron.php`.
`update/` directory is part of the `magento2-community-edition` library itself and obviously would not be downloaded during `composer install/update`. It seems that the only option is to have a copy of it along side Your composer.json. Having copy of it doesn't make sense because:
- they are M2 files not "Yours"
- You would need to regularly sync(copy-paste) it from original source to make sure You have latest version

Would like to understand what is the clean, bare minimum of files required to have M2 Composer based project?

**Comment by buskamuza** [comment]
@werdlv , bare minimum does not include "update" folder. "update" folder is required for Setup Wizard application, which allows upgrades via GUI. If you don't need this flow, "update" folder may be skipped. In this case the only cron that should be configured is `bin/magento cron:run`

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by VahanDrnoyan** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  v.drnoyan@gmail.com
    Domain magejet.com has exceeded the max emails per hour (202/199 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:48615)
    by server with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
    (Exim 4.87)
    (envelope-from <bounces+848413-cb49-vahan=magejet.com@sgmail.github.com>)
    id 1c1aUA-0006hn-EW
    for vahan@magejet.com; Tue, 01 Nov 2016 14:56:22 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
    h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
    s=s20150108; bh=40gu0fe/Xvnh5Ic7Yl8uCq5/YwU=; b=ZlX/HpFrZe6ZbAci
    5Uj0KwXPure7+VPsE8oQtjw4Ew7DzoTwTOe9EutVMUup7v1ks3UEoIXpWt0oRwMU
    j63XFKLNVyC9/svz7rylwJIRE8h365E8n03Csk4MyPzVbT05J+qv+v5EgNpBawjr
    uJ6paIG6h7v0HqiDffFI49BvmPE=
Received: by filter0544p1mdw1.sendgrid.net with SMTP id filter0544p1mdw1-29123-5818ACDB-1B
        2016-11-01 14:55:23.310474628 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
    by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id eSpDlnIZRY-hSLrmrAex6g
    for vahan@magejet.com; Tue, 01 Nov 2016 14:55:23.254 +0000 (UTC)
Date: Tue, 01 Nov 2016 07:55:22 -0700
