### ISSUE TITLE
Path to category image file is incorrect when using AwsS3 driver

### ISSUE THREAD

**Issue by nwcasebolt** [magento/magento2#36907]
### Preconditions and environment

- Magento version 2.4.5-p1
- Configure Magento for remote media storage using an AWS S3 bucket

### Steps to reproduce

1. Under **Catalog** > **Categories**, drill into a category and save thumbnail.

### Expected result

1. The image saves to the S3 bucket and is visible in Magento.

### Actual result

1. The category page fails to load and displays the error message: `Unable to retrieve metadata for file at location: {filename}. Unable to retrieve the last_modified for file at location: {filename}.`

![error_message](https://user-images.githubusercontent.com/55930080/220739406-1cbf3318-9cb9-4732-8374-a713e8937168.png)

### Additional information

When Magento is configured to use remote storage with an S3 bucket, the category image filename retrieved from the database is not prefixed with `media/catalog/category` before sending it to the AwsS3 driver. AWS naturally can't find the image file at the bucket's root and returns an error. We resolved this with the following patch.

```
--- FileInfo.php		2022-09-12 14:47:34.000000000 +0000
+++ FileInfo.php	        2023-02-21 16:25:54.684382001 +0000


diff --git a/vendor/magento/module-catalog/Model/Category/FileInfo.php b/vendor/magento/module-catalog/Model/Category/FileInfo.php
index asn565l4..7jd84y8v 100644
--- a/vendor/magento/module-catalog/Model/Category/FileInfo.php
+++ b/vendor/magento/module-catalog/Model/Category/FileInfo.php
@@ -123,7 +123,10 @@
     public function getMimeType($fileName)
     {
         if ($this->getMediaDirectory()->getDriver() instanceof ExtendedDriverInterface) {
-            return $this->mediaDirectory->getDriver()->getMetadata($fileName)['mimetype'];
+    	     if (!$this->isBeginsWithMediaDirectoryPath($fileName)) {
+                $fileName = 'media' . $this->getFilePath($fileName);
+            }
+	    return $this->mediaDirectory->getDriver()->getMetadata($fileName)['mimetype'];
         } else {
             return $this->mime->getMimeType(
                 $this->getMediaDirectory()->getAbsolutePath(
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bjvickers** [comment]
Many thanks - same issue on 2.4.6-p3 with AWS S3 storage. Now fixed by your patch

**Comment by engcom-Hotel** [comment]
Dear @nwcasebolt,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
