### ISSUE TITLE
Zero Subtotal Checkout leaves order on processing

### ISSUE THREAD

**Issue by M1hai** [magento/magento2#3691]
I have activated Zero Subtotal Checkout on Magento 2.0.1 and configured it with the following:
Title: No Payment Information Required
New Order Status: Processing
Automatically Invoice All Items: Yes
Payment from Applicable Countries: No
Sort Order: 1
When i place an order for a free downloadable product after the order is complete and everything done, in Magento Admin the Order Status is still: PROCESSING
If i set Automatically Invoice All Items on No and invoice the order manually the status changes from Processing to Complete

Is this a bug from Magento or have I done something wrong?

**Comment by owebia** [comment]
+1

**Comment by piotrekkaminski** [comment]
@asemenenko please check. 

For such question community.magento.com is a better place.

**Comment by safersurfing** [comment]
Anybody solved the issue? I also experience this. Seems a bug with M2 2.1.1

**Comment by SerhiyShkolyarenko** [comment]
@M1hai @owebia @safersurfing please create a new issue formatting description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
