### ISSUE TITLE
Security Error in Magento 2.4.3-p1

### ISSUE THREAD

**Issue by asiainfosolutions** [magento/magento2#36919]
### Preconditions and environment

- Magento version: 2.4.3-p1
-

### Steps to reproduce

Hi Team,

We are using Magento 2.4.3-p1 and we are seeing following error in Magento Scan report.
1- There is a chance your domain takes part in BotNets activities.Please perform appropriate actions (on the right) and Email Us to remove your domain from potential `BotNet Participants` list.

2- vulnerability found: Magento core vulnerability (APSB22-13)
In file:/var/www/share/default/magento
More info.

3- vulnerability found: Magento core vulnerability (APSB22-48)
In file:/var/www/share/default/magento
More info.

4-vulnerability found: Magento core vulnerability (APSB22-38)
In file:/var/www/share/default/magento

But we are not able to find any security patch for Magento 2.4.3-p1. Can you please help us to find patches to fix these 4 errors.

Thanks!

### Expected result

No Error while scanning website from scanning tool of adobe.

### Actual result

We have 4 errors shared above.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @asiainfosolutions ,

Thank you for reporting and collaboration. We are closing this issue as it is not recommended to report security issues in  https://github.com/magento/magento2 repository. All security issues should be reported privately via [bug bounty program](https://hackerone.com/adobe).
Thank you.
