### ISSUE TITLE
504 gateway timeout when creating configurable product on dev instance

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#36928]
### Preconditions and environment

- 2.4.x develop

### Steps to reproduce

Clone a configurable product. 
Try to create variations for 5 colors and 5 sizes. 
Add 3 images to the products. 
Click on save

### Expected result

Product is saved relatively fast 5-15 seconds

### Actual result

504 gateway timeout

### Additional information

As you can see in the following video there are multiple issues in usability. 

First of all after cloning the product there is noeasy way to disassociate the previous ones. 

Secondly while adding the new variations, with default settings there's a timeout. 

If saving a product takes so long, it's detrimental to the shop owner as he's paying his employees to just wait for Magento to save. 

Compared to other platforms Woocommerce / CsCart, Prestashop, the saving process is extremely slower. 

https://user-images.githubusercontent.com/20220341/221552550-e0a6f23d-f7e9-4ed5-ad99-30da8bad227d.mp4

The video was taken using the magento instance that the bot created but it's similar in production systems

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by ioweb-gr** [comment]
Some additional info the images I uploaded were 1200x1725 placeholder jpg images

**Comment by engcom-Dash** [comment]
**Hi @ioweb-gr ,**

Thanks for the collaboration,

We are trying to reproduce the issue in 2.4-develop instance,But the issue is not reproducible.

**Preconditions**:
1.Magento version 2.4-develop
2.PHP Version : 8.1

**Steps to reproduce:**
1.Install Magento instance
2.Create one configurable product and clone the product
3.Create configurations with 5 variations colour  and size
4.Add three images for the products
5.save the product

**Here we upload the Recorded video for your Reference:**

https://user-images.githubusercontent.com/60198592/221670809-5990cae5-580a-4e1b-8153-328e0608f10d.mp4


**Actual result:**
504 gateway timeout

**Expected result:**
Product is saved relatively fast 5-15 seconds

We are getting expected result as per the description , the product saved But,its took 5 to 15 seconds to save the products and the issue is not reproducible.

Let us know if we missing anything

Thanks.

**Comment by ioweb-gr** [comment]
Hi  do you  see the video above on the demo instance that the bot provides? 

Did you upload images as well with proper dimensions after creating the variations? 

Did you create a clone? 

Did you disassociate the previous variations? 

Did you create 25 new variations? 

Could you post a video to see what step you missed as the issue is perfectly reproducible on the 2.4 develop branch on the instance the bot provides

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
hi @ioweb-gr ,

Thanks for your inputs,

Verified the issue in 2.4-develop instance and the issue is reproducible.

Preconditions:
Magento version 2.4-develop
PHP Version 8.1

Steps to reproduce :

1.Install magento instance
2.Create one Configurable product
3.Clone the Configurable product
4.Create 5 variations in Colour and size
5.Add three  images with 1200 x 1750 px
6.Save the product.

Here we uploaded the Recorded video for your Reference:

https://user-images.githubusercontent.com/60198592/221811225-8f3c2ca7-a333-450d-a0e9-303e070da31c.mp4

We are Actual result as per the description...So we confirming the issue and its reproducible.

Thanks.

**Comment by ioweb-gr** [comment]
Thanks for confirming @engcom-Dash 

I really hope this can be improved. I've gathered a list of some usability issues in the same area of the configurable product creation which are causing data entry teams headaches daily. 

For this specific issue, please note that we have a client with a product that contains 43 colors and 10 sizes. 

It's practically impossible to create this product from the backend.

**Comment by chrisbadley** [comment]
> Thanks for confirming @engcom-Dash
> 
> I really hope this can be improved. I've gathered a list of some usability issues in the same area of the configurable product creation which are causing data entry teams headaches daily.
> 
> For this specific issue, please note that we have a client with a product that contains 43 colors and 10 sizes.
> 
> It's practically impossible to create this product from the backend.

Imo, these types of instances are killing this project, the constant need to increase max execution times and mess with other PHP settings, increase RAM allocations, spend forever trying to optimise MySQL all to compensate for the fact that Magento's performance has become atrocious and it costs a fortune to host it, or may that is their intention, to get people to convert to the SaaS version, which also cost alot. Most people will simply swap to something more affordable and better performing.

**Comment by ioweb-gr** [comment]
@engcom-Dash do you think you can do a quick inquiry with the lead developers if there is any way to mitigate the issue currently. Increasing the timeout is not solving the extreme delay in creating variations and we're suffering hard from the slowness. We have Magento 2.2 instances that are 5 times faster than 2.4.x-develop in that respect

**Comment by yogesh-valiya** [comment]
@ioweb-gr 

I was facing similar issue in past and as a workaround we added following code to the di.xml file

```
<type name="Magento\Catalog\Observer\ImageResizeAfterProductSave">
        <arguments>
            <argument name="imageResizeSchedulerFlag" xsi:type="boolean">true</argument>
        </arguments>
    </type>
```

**Comment by Alexander-Khohklov** [comment]
@magento I am working on this

**Comment by ioweb-gr** [comment]
> @ioweb-gr
> 
> I was facing similar issue in past and as a workaround we added following code to the di.xml file
> 
> ```
> <type name="Magento\Catalog\Observer\ImageResizeAfterProductSave">
>         <arguments>
>             <argument name="imageResizeSchedulerFlag" xsi:type="boolean">true</argument>
>         </arguments>
>     </type>
> ```
> 
> This will basically avoid image resizing on the product save call. Instead, it will use message queues to resize images.
> 
> Addition to this, set your indexer to `On Schedule` to make product save faster.

@yogesh-valiya I wanted to ask from which magento version this is available. For example can I use it on 2.4.1? Do you happen to know?

**Comment by yogesh-valiya** [comment]
> > @ioweb-gr
> > I was facing similar issue in past and as a workaround we added following code to the di.xml file
> > ```
> > <type name="Magento\Catalog\Observer\ImageResizeAfterProductSave">
> >         <arguments>
> >             <argument name="imageResizeSchedulerFlag" xsi:type="boolean">true</argument>
> >         </arguments>
> >     </type>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will basically avoid image resizing on the product save call. Instead, it will use message queues to resize images.
> > Addition to this, set your indexer to `On Schedule` to make product save faster.
> 
> @yogesh-valiya I wanted to ask from which magento version this is available. For example can I use it on 2.4.1? Do you happen to know?

The flag `imageResizeSchedulerFlag` was introduced introduced in 2.4.x only I think.
Here is the reference commit - https://github.com/magento/magento2/commit/066e31c7aad704e5e98dcf399951304cc1554d38

**Comment by ioweb-gr** [comment]
Thank you it's minimum 2.4.4

**Comment by yogesh-valiya** [comment]
> Thank you it's minimum 2.4.4

But you can use it on 2.4.1 as well @ioweb-gr 

By creating patch from this commit - https://github.com/magento/magento2/commit/066e31c7aad704e5e98dcf399951304cc1554d38
