### ISSUE TITLE
Edit product page: Fail to load Related Products, Up-Sells, and Cross-Sells section

### ISSUE THREAD

**Issue by ithubdeveloper** [magento/magento2#36925]
Hi Team,
Recently I updated the project from Magento 2.3.4 to Magento 2.4.5-p1, I have encountered the following issue, on the edit product page the 

- Related Products, Up-Sells, and Cross-Sells Edit tab not showing anything, and in the console, I'm getting the following errors.

[2023-02-27 09:43:55] [ERROR] Failed to load the "ui/dynamic-rows/templates/grid" template requested by "product_form.product_form.sources.assigned_sources".
ConsoleOutputHandler.show @ VM15006:4
![image](https://user-images.githubusercontent.com/12099404/221531085-f065d337-8a52-4642-86a6-645f8f1f3df8.png)

### Preconditions (*)
1. Magento ver. 2.4.5-p1
2. PHP 7.4
3. MariaDB 10.6.12 

### Steps to reproduce (*)
1. Upgrade from Magento 2.3.4 to Magento 2.4.5-p1,
2. Edit Products
3. Click on the Related Products, Up-Sells, and Cross-Sells section

### Expected result (*)
![image](https://user-images.githubusercontent.com/12099404/221533685-799248c9-8a10-4055-969f-4e5eaded10da.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/12099404/221532184-ff4c183a-611a-4ea7-830b-8ed60820b66d.png)

**Comment by engcom-Alfa** [comment]
hi @ithubdeveloper 

Thanks for reporting the concern to us.

looking at your ticket, I would suggest you to please follow the pre-requisite for 2.4.5-p1 according to the below link
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html#

as looking at the description, it is an incorrect PHP version for 2.4.5-p1.

Please try as per the link and it should be working for you with the correct dependencies.

Regards
