### ISSUE TITLE
[Import][Category] Url rewrite for new category doesn't generate correctly

### ISSUE THREAD

**Issue by thienhoangtran** [magento/magento2#36936]
### Preconditions and environment

- Magento version: 2.4.5-p1
- With sample data
- Require more than two store views (even it is not same the store group)

**Steps to reproduce:**
1. Go to Stores >> Configuration >> General >> Search Engine Optimization >> Set "Yes" in **Use Web Server Rewrites**.
2. Go to System >> Data transfer >>Import ->Import a file of products and add new category in the Category column of the file (make sure that category should not be created in the backend).
3. Now, verify the url rewrite generated for the storeview of the category in `Marketing >> Seo & Search >> Url Rewrite`.

### Expected result

The category URL rewrite is generated for all store view

### Actual result

The category URL rewrite is generated for only the default store view of the store group.

### Additional information

I found some processes after category saves to handle the URL rewrite here:

`\Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver::execute
`

In this case, the $category object doesn't have "store_id" data, so it is called a function setCategoryStoreId (line 109).

This is the note of this function 
`In case store_id is not set for category then we can assume that it was passed through product import.
Store group must have only one root category, so receiving category's path and checking if one of it parts
is the root category for store group, we can set default_store_id value from it to category. it prevents urls
duplication for different stores (“Default Category/category/sub” and “Default Category2/category/sub”)`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @thienhoangtran ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but issue is **not reproducible** to me in **2.4-develop**. Followed below steps:

**Steps to reproduce:**

1. Run the imported product, and include a new category in the import file.
2. After import success, check the url_rewrite data for the new category.

Kindly elaborate more steps to reproduce and also please provide us video (if possible). Kindly check this in **2.4-develop instance**. Let us know if you are missing anything.

Thanks

**Comment by thienhoangtran** [comment]
Hi @engcom-Lima 

Did you create a second store view for your website / store group?

If you have more than one store view, Magento only generates url_rewrite for the default store view, all good if you have only one store view.

Regards,

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @thienhoangtran ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue in latest **2.4-develop instance**. But issue is not reproducible to me.

Below is the screenshot for your reference:
<img width="1439" alt="Screenshot 2023-03-02 at 4 20 44 PM" src="https://user-images.githubusercontent.com/60198022/222408406-c12a1994-d406-41f2-ae10-ff95e4c70e64.png">

**CSV file used:** 
[catalog_product.csv](https://github.com/magento/magento2/files/10870552/catalog_product.csv)

Kindly provide us more information about the steps to reproduce. Also, please test it in latest **2.4-develop instance** and let us know if you are facing any issue.

Thanks

**Comment by thienhoangtran** [comment]
Hi @engcom-Lima 

I think we're misunderstanding here. We're discussing about url rewrite of Category, not product like your image?

In this case, can you help to show the url_rewrite of category Test1?

Regards,

**Comment by engcom-Lima** [comment]
Hi @thienhoangtran ,

Thanks for your contribution and collaboration.

Please find the attached screenshot for your reference:
<img width="1422" alt="Screenshot 2023-03-03 at 10 47 27 AM" src="https://user-images.githubusercontent.com/60198022/222663985-b0412d18-69eb-4bc9-8b57-a6c1542190e9.png">

Kindly provide us more information about the steps to reproduce. Also, please test it in latest 2.4-develop instance and let us know if you are facing any issue.

Thanks

**Comment by engcom-Lima** [comment]
Hi @thienhoangtran ,

Thanks for contribution and collaboration.

Humble request from you whenever reporting issue,Kindly provide us exact steps to reproduce (elaborate more about it),screenshot / videos so, that it wil help us to quickly reproduce the issue.

:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Url rewrite for new category in 2nd store view doesn't correctly generated when product with new category imported.

**Pre-requisite:**
-Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Create a new store view.
2. Go to Stores >> Configuration >> General >> Search Engine Optimization >> Set "Yes" in **Use Web Server Rewrites**.
3. Go to System >> Data transfer >>Import ->Import a file of products and add new category in the Category column of the file (make sure that category should not be created in the backend).
[catalog_product.csv](https://github.com/magento/magento2/files/10882084/catalog_product.csv)
 
4. Now, verify the url rewrite generated for the storeview of the category in `Marketing >> Seo & Search >> Url Rewrite`.

**Expected result:** The category URL rewrite is generated for all store view.
**Actual result:** The category URL rewrite is generated for only the default store view of the store group.
**Screenshots:**
<img width="1511" alt="Screenshot 2023-03-03 at 6 09 14 PM" src="https://user-images.githubusercontent.com/60198022/222725722-44136c9a-ad7e-485a-94f2-f0a69c6f41f2.png">

Hence, confirming the issue.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by mirceaRosmeteniuc** [comment]
The internal team already fixed this issue

**Comment by hostep** [comment]
Probably fixed by [ACP2E-1737: Category URL rewrite is not generated for all store views when importing a new category from an CSV file](https://github.com/magento/magento2/commit/96c6f2452b86ad52164df9236daf4e970d568e0a) ?

@mirceaRosmeteniuc: in the future, please do not close issues until the code is published on github and specify the ticket number and/or links to the commits that fixed it. Thanks for understanding! 🙂
