### ISSUE TITLE
Translation VAT in address renderer

### ISSUE THREAD

**Issue by vacla** [magento/magento2#36942]
### Summary

Version: Magento 2.4.5

You are unable to translate the text "VAT", "T", "F" in the address renderers.

### Examples

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/adminhtml/web/template/default-address.html#L47
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html#L20
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/shipping-address/address-renderer/default.html#L18
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/shipping-information/address-renderer/default.html#L18

### Proposed solution

Change it to `<translate args="'VAT'"></translate>` instead so you are able to translate it.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vacla** [comment]
@magento I am working on this

**Comment by vacla** [comment]
@magento add to contributors team

**Comment by vacla** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @vacla,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch and the issue seems reproducible for us. Please have a look at the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/222699377-fa05d604-bc53-4fb3-98f0-751e41db43f0.png)

Hence confirming the issue.

Thanks
