### ISSUE TITLE
Customer Sales Order Item GraphQL Resolver does not honor tax configuration

### ISSUE THREAD

**Issue by pmzandbergen** [magento/magento2#36946]
### Preconditions and environment

- Magento 2.x (including the current `2.4-develop` branch)
- Tax configured, all display settings on "Including Tax" (See Stores > Configuration > Sales > Tax)

### Steps to reproduce

1. Create a Customer
2. Create an Order as Customer, including a Product with Tax included
3. Run the following GraphQL query as this Customer:
```
query {
    customer {
        orders {
            items {
                number
                items {
                    quantity_ordered
                    product_sale_price {
                        value
                    }
                }
                total {
                    subtotal {
                        value
                    }
                    total_tax {
                        value
                    }
                    base_grand_total {
                        value
                    }
                }
            }
        }
    }
}
```

Current result:
```
{
    "data": {
        "customer": {
            "orders": {
                "items": [
                    {
                        "number": "SOME-ORDER-NUMBER",
                        "items": [
                            {
                                "quantity_ordered": 1,
                                "product_sale_price": {
                                    "value": 49.58
                                }
                            }
                        ],
                        "total": {
                            "subtotal": {
                                "value": 49.58
                            },
                            "total_tax": {
                                "value": 10.41
                            },
                            "base_grand_total": {
                                "value": 59.99
                            }
                        }
                    }
                ]
            }
        }
    }
}
```

The field `product_sale_price` should include tax, since all display settings (especially `tax/sales_display/price`) include tax.

### Expected result

The price (`product_sale_price`) should include tax with `tax/sales_display/price` set.

### Actual result

The price (`product_sale_price`) is excluding tax with `tax/sales_display/price` set.

### Additional information

The cause can be found in the DataProvider:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/SalesGraphQl/Model/OrderItem/DataProvider.php#L142

It does not honor the configuration, it simply uses `$orderItem->getPrice()`. Depending on the setting it should be either using `$orderItem->getPriceInclTax()` or `$orderItem->getPrice()`.

If required separate fields should be used, e.g.:
- `product_sale_price` (the display price as configured; existing)
- `product_sale_price_excl_tax` (the price excluding tax; new)
- `product_sale_price_incl_tax` (the price including tax; new)

However these additional fields should not be necessary in the current (known) use cases.

Note: If I have time I'll submit a PR.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Customer sales order item in GraphQl is not displaying tax properly.

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**
As given in [comment](https://github.com/magento/magento2/issues/36946#issue-1607232218).

**Expected result:** The price (`product_sale_price`) should include tax with `tax/sales_display/price set`.

**Actual result:** The price (product_sale_price) is excluding tax with tax/sales_display/price set.
**Screenshots:**
<img width="1437" alt="Screenshot 2023-03-03 at 5 08 05 PM" src="https://user-images.githubusercontent.com/60198022/222711112-b4847c8a-d291-4a12-8a6b-a0fd0d021c19.png">

**Comment by pmzandbergen** [comment]
@magento I am working on this

**Comment by pmzandbergen** [comment]
PR #36966 is ready for review

**Comment by glo23503** [comment]
Internal team is working on it.

**Comment by pmzandbergen** [comment]
> Internal team is working on it.

@glo23503 should I still add a unit test for the PR or is it already created by the internal team?

**Comment by glo23503** [comment]
Our internal team is working on the test coverage.
