### ISSUE TITLE
GZip database backup file

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3695]
Thanks for fixing the issue #2915 but would it even better if you realy gzip the database backup file to minimize the file size? If you hold >10 backups of a big database you waste disk storage and it is faster to transfer the backup to an other location.

**Comment by daim2k5** [comment]
Did you really think magento need to handle all the difficult backup topic? The next step is what happend if your Database ist 6-10 GB big ;-)

**Comment by marvincaspar** [comment]
Magento don't need to handle all difficult backup topics but a text file is a great example for compress.

**Comment by mazhalai** [comment]
@mc388 @daim2k5 we have created MAGETWO-50844 to fix this issue.

**Comment by piotrekkaminski** [comment]
You should avoid using Magento backups and use proper system level database and file backup. Text database backups are hard to restore (time consuming) and should not be used in production environment.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/GZip-database-backup-file/idi-p/46059).
