### ISSUE TITLE
reCAPTCHA placing order without user confirmation

### ISSUE THREAD

**Issue by vmartins** [magento/magento2#36952]
### Preconditions and environment

- Magento version: 2.4.5-p1
- reCAPTCHA v2 ("I am not a robot") enabled in Storefront for Checkout/Placing Order

### Steps to reproduce

1. Navigate to storefront logged.
2. Add any product to cart
3. Proceed to checkout
4. Choose any payment method and click "Place Order" without filling the reCAPTCHA
5. Wait for the following message to show up: "reCAPTCHA verification failed."
6. Fill reCAPTCHA

### Expected result

Order is placed only after user click on the "Place Order" button

### Actual result

Order is created after filling out reCaptcha, without the user having clicked on the "Place Order" button

### Additional information

https://user-images.githubusercontent.com/1051065/222725620-b65d8b47-2188-4e0a-a2d8-ad42bc835f06.mp4

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @vmartins ,

Verified the issue in 2.4-develop instance,We are not able to reproduce the issue.

**Description:**
reCAPTCHA placing order without user confirmation 
**Pre-requisite:**
Magento Version 2.4-develop
PHP version 8.1
**Actual result:**
Order is created after filling out reCaptcha, without the user having clicked on the "Place Order" button
**Expected Result:**
Order is placed only after user click on the "Place Order" button
**Steps to reproduce:**
1.Navigate to storefront logged.
2.Add any product to cart
3.Proceed to checkout
4.Choose any payment method and click "Place Order" without filling the reCAPTCHA
5.Wait for the following message to show up: "reCAPTCHA verification failed."
6.Fill reCAPTCHA
**Screenshots for your reference:**
<img width="1408" alt="recap1" src="https://user-images.githubusercontent.com/60198592/222757145-8b6603f9-228f-43bd-ae6a-77efcca5788e.png">
<img width="1111" alt="recap2" src="https://user-images.githubusercontent.com/60198592/222757183-6910c4e5-98b5-4921-a860-4b0eb562f711.png">
<img width="1431" alt="recap3" src="https://user-images.githubusercontent.com/60198592/222757186-58f3f9d0-4c79-4439-ad73-7a7603b6ef39.png">
<img width="1431" alt="recap4" src="https://user-images.githubusercontent.com/60198592/222757192-ed656475-9812-46b8-8db4-56b51e848b2e.png">
<img width="1426" alt="recap5" src="https://user-images.githubusercontent.com/60198592/222757201-efbfa460-a310-4d17-944d-735c033cfabd.png">
<img width="1497" alt="recap6" src="https://user-images.githubusercontent.com/60198592/222757212-0489d6e3-8a9e-4595-8480-9e8503274a8c.png">

**We are getting expected result...We can place the order after clicking the place order button.**

Let us know if we missing anything

Reagards,

**Comment by vmartins** [comment]
@magento give me 2.4.5-p1 instance

**Comment by vmartins** [comment]
@engcom-Dash This issue does not happen in instance 2.4-develop. I was able to reproduce on instances: 2.4.5 and 2.4.5-p1.

I think this issue is fixed in the develop version of the ReCaptcha module (https://github.com/magento/security-package).

https://github.com/magento/security-package/blob/develop/ReCaptchaCheckout/view/frontend/web/js/model/place-order-mixin.js#L34-L40
https://github.com/magento/security-package/blob/develop/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptcha.js#L46-L56
https://github.com/magento/security-package/blob/develop/ReCaptchaWebapiUi/view/frontend/web/js/webapiReCaptchaRegistry.js#L47-L54

Thanks!
