### ISSUE TITLE
UPS Rates for Shipments over 150lbs Not Working

### ISSUE THREAD

**Issue by bulldogm11** [magento/magento2#36962]
### Preconditions and environment

Vanilla Install of Magento 2.4.4-p2

UPS Rates are not displayed/returned when total weight of all items in cart exceeds 150lbs. 

UPS Shipping is configured to "Divide to equal weight (one request)"

[2023-03-03T22:43:56.961178+00:00] main.DEBUG: array (
  'request' => 
  array (
    'accept_UPS_license_agreement' => 'yes',
    '10_action' => '4',
    '13_product' => 'GNDRES',
    '14_origCountry' => 'US',
    '15_origPostal' => '85120',
    'origCity' => 'apache junction',
    '19_destPostal' => '85373',
    '22_destCountry' => 'US',
    '23_weight' => 3000.0,
    '47_rate_chart' => 'Customer Counter',
    '48_container' => '00',
    '49_residential' => '01',
    'weight_std' => 'lbs',
  ),
  'result' => '

 

UPSOnLine5%The maximum per package weight for the selected service from the selected country or territory is 150.00 pounds.%1035%

',
) [] []
[2023-03-03T22:43:56.961470+00:00] main.DEBUG: Sorry, something went wrong. Please try again or contact us and we'll try to help.: The maximum per package weight for the selected service from the selected country or territory is 150.00 pounds. [] []

### Steps to reproduce

1. Add enough products to cart to exceed 150 total lbs.
2. Checkout
3. UPS Shipping rate will not show as an option.

### Expected result

Request should divide weight to equal amounts and retrun results as seen below:

[2023-03-03 22:30:48] main.DEBUG: array (
  'request' => 
  array (
    'accept_UPS_license_agreement' => 'yes',
    '10_action' => '4',
    '13_product' => 'GNDRES',
    '14_origCountry' => 'US',
    '15_origPostal' => '85120',
    'origCity' => 'apache junction',
    '19_destPostal' => '85373',
    '22_destCountry' => 'US',
    '23_weight' => 150.0,
    '47_rate_chart' => 'Customer Counter',
    '48_container' => '00',
    '49_residential' => '01',
    'weight_std' => 'lbs',
  ),
  'result' => '

 

UPSOnLine4%1DM%85120%US%85373%US%102%150%532.39%29.00%561.39%10:00 A.M.%
4%1DA%85120%US%85373%US%102%150%497.29%29.00%526.29%12:00 P.M.%
4%1DP%85120%US%85373%US%132%150%455.94%29.00%484.94%End of Day%
4%2DA%85120%US%85373%US%202%150%298.89%29.00%327.89%End of Day%
4%3DS%85120%US%85373%US%302%150%228.03%29.00%257.03%End of Day%
4%GND%85120%US%85373%US%002%150%176.21%29.00%205.21%End of Day%

### Actual result

This is what is returned:

[2023-03-03T22:43:56.961178+00:00] main.DEBUG: array (
  'request' => 
  array (
    'accept_UPS_license_agreement' => 'yes',
    '10_action' => '4',
    '13_product' => 'GNDRES',
    '14_origCountry' => 'US',
    '15_origPostal' => '85120',
    'origCity' => 'apache junction',
    '19_destPostal' => '85373',
    '22_destCountry' => 'US',
    '23_weight' => 3000.0,
    '47_rate_chart' => 'Customer Counter',
    '48_container' => '00',
    '49_residential' => '01',
    'weight_std' => 'lbs',
  ),
  'result' => '

 

UPSOnLine5%The maximum per package weight for the selected service from the selected country or territory is 150.00 pounds.%1035%

',
) [] []
[2023-03-03T22:43:56.961470+00:00] main.DEBUG: Sorry, something went wrong. Please try again or contact us and we'll try to help.: The maximum per package weight for the selected service from the selected country or territory is 150.00 pounds. [] []

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @bulldogm11 ,

Thanks for your contribution and collaboration. Tried to reproduce the issue in Magento 2.4-develop instance (vanilla) but issue is not reproducible to me. I have followed below steps :

**Steps to reproduce:**

- Configured UPS delivery method.
- Created a product with 143 lbs weight.
- Go to the frontend and added 4 qty of the created product.
- Verified the UPS in the shipping page of FE.

**Screenshots:**
<img width="1176" alt="Screenshot 2023-03-06 at 12 45 35 PM" src="https://user-images.githubusercontent.com/60198022/223044618-2c1a30ce-c384-4734-b59a-7a01d20c6dfe.png">

Kindly provide us more information in order to reproduce the issue. Also, try to verify the issue in `2.4-develop` instance and let us know if you are facing any issue.


Thanks

**Comment by devchris79** [comment]
What is set in the maximum package weight field of the UPS shipping configuration? You should have this set to less than 150lbs:

![Untitled](https://user-images.githubusercontent.com/43850303/223162940-d720662b-9981-4c7a-bb49-e47deeda8f70.png)

**Comment by bulldogm11** [comment]
Yes, the weight is set to 150 lbs.

I will ask for a 2.4.4-p2 instance and confirm. I've installed 2.4.4-p2 on
3 servers I have access to and all have the issue.

Thanks,

Brandon

**Comment by bulldogm11** [comment]
@magento give me 2.4-develop instance

**Comment by bulldogm11** [comment]
@magento give me 2.4.4-p2-develop instance

**Comment by bulldogm11** [comment]
How do I confirm 2.4.4-p2 instance?

**Comment by bulldogm11** [comment]
@magento give me 2.4.4-p2-develop instance

**Comment by bulldogm11** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @bulldogm11,

Thanks for your update.

We have further investigated in the code base.The maximum package weight is 150 only,

Kindly check this https://www.ups.com/us/en/support/shipping-support/shipping-dimensions-weight.page#:~:text=Size%20and%20Weight%20Limits,may%20require%20freight%20shipping%20services. As per this UPS have certain size and weight limits.Packages above certain size and weight combinations may require `freight shipping services`


<img width="1378" alt="Screenshot 2023-03-08 at 6 58 06 PM" src="https://user-images.githubusercontent.com/51680745/223725378-f02c4c05-b5aa-4d42-b615-e03bf36d2395.png">


Kindly let us know if you are still facing any issue.

Thanks.

**Comment by devchris79** [comment]
Hi @engcom-Bravo I think you have misunderstood, UPS does indeed have a maximum single package limit of 150lbs, the Magento setting below should break down the total cart into multiple boxes of the maximum weight setting.
 
> What is set in the maximum package weight field of the UPS shipping configuration? You should have this set to less than 150lbs:
> 
> ![Untitled](https://user-images.githubusercontent.com/43850303/223162940-d720662b-9981-4c7a-bb49-e47deeda8f70.png)

**Comment by bulldogm11** [comment]
@devchris79 Thank you for your response! 

Yes the Maximum Package Weight is set to 150 lbs. 

You are also correct in that the problem is that with the 2.4.4-p2 Magento instance, the package is no longer divided into multiple boxes and sent to UPS for rates, then totaled. Only one request is being sent to UPS of the total combined weight of all items in the cart. If all items in the cart exceed 150 lbs, no rates are available. 

From my quick investigation, this issue started with the 2.4.4 version.

**Comment by devchris79** [comment]
@bulldogm11 
Just another thought that 2.4.4 is the[ transition point to php 8.1](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html), what version are you using?

**Comment by bulldogm11** [comment]
I've tested in 7.4., 8.0, and 8.1. I had the same thought as you initially. Unless I missed something in my PHP modules, the version had no bearing on the result. 

Plus it's been confirmed on the dev instance here. I'm assuming the dev instance would use PHP 8.1.

**Comment by engcom-Bravo** [comment]
@devchris79 @bulldogm11. Thanks for your update.


As per Magento devdocs https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/delivery/shipping-carriers/ups.html?lang=en. 


<img width="933" alt="Screenshot 2023-03-09 at 6 36 55 PM" src="https://user-images.githubusercontent.com/51680745/224032371-4cb4faca-e7e6-446d-92f1-6ddc2b2df14d.png">


`
The standard United Parcel Service type is scheduled for deprecation. For new configurations, you should use the default United Parcel Service XML type. ` We should use UPS XML Method.


Please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @bulldogm11,

Thanks for your update.

We are moving this issue to on hold, we need confirmation from PO on this issue.Will update you accordingly.


Thanks

**Comment by engcom-Bravo** [comment]
Hi @bulldogm11,

We got Reply from PO as this follows:

We should not fix the issue with the standard endpoint, this endpoint should be removed from the code in favor of XML one. We can schedule this change for 2.4.7 scope.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @bulldogm11,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by mikeshiek** [comment]
@bulldogm11 were you able to find a fix for this? We have been having this issue for months with no fix.

**Comment by bulldogm11** [comment]
@mikeshiek No I did not. According to the comments above, Magento is not interested in fixing this as they are reportedly deprecating that option. 
I don't agree with that decision.
