### ISSUE TITLE
Magento 2.0 not update lifetime new order

### ISSUE THREAD

**Issue by balack** [magento/magento2#3696]
Im create new order in admin, but after creating, it's not update to list order.
Im record video demo: https://youtu.be/JZsTWV4eVQI
Can you help me, pls?

Thanks guy !

**Comment by Mulderua** [comment]
Hi @balack, we cannot reproduce this issue on all versions. 
Please try disable third party extension, do composer update, clear cache and try to reproduce it again. 
Notice that the last Magento version is 2.0.7 so you can upgrade you system and check you scenario after that.

**Comment by piotrekkaminski** [comment]
Closing due to lack of response.
