### ISSUE TITLE
SOAP API returns wrong result

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#3697]
By default WCF generated web service throws exception since qty tag is empty. Is it possible to return 0 if item is out of stock? I know that there is ability to avoid this issues, by editing service client manually, but it is annoying to change it for all such issues. Thanks
## Steps to reproduce
1. Create new Product with sku="TestSku1", with qty=0, Stock Availability=OutOfStock
2. Call soap method "catalogInventoryStockRegistryV1" with parameter "TestSku1".
## Expected result
1. Receive corerct xml with product "TestSku1", qty=0.
## Actual result
1. Incorrect XML: ```
   <?xml version="1.0" encoding="UTF-8"?>
   <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://192.168.0.1:777/Magento-2-0-2-0-ce/soap/default?services=catalogInventoryStockRegistryV1">env:Bodyns1:catalogInventoryStockRegistryV1GetStockItemBySkuResponse<result><itemId>2</itemId><productId>2</productId><stockId>1</stockId><qty/><isInStock>false</isInStock><isQtyDecimal>false</isQtyDecimal><showDefaultNotificationMessage>false</showDefaultNotificationMessage><useConfigMinQty>true</useConfigMinQty><minQty>0</minQty><useConfigMinSaleQty>1</useConfigMinSaleQty><minSaleQty>1</minSaleQty><useConfigMaxSaleQty>true</useConfigMaxSaleQty><maxSaleQty>10000</maxSaleQty><useConfigBackorders>true</useConfigBackorders><backorders>0</backorders><useConfigNotifyStockQty>true</useConfigNotifyStockQty><notifyStockQty>1</notifyStockQty><useConfigQtyIncrements>true</useConfigQtyIncrements><qtyIncrements>0</qtyIncrements><useConfigEnableQtyInc>false</useConfigEnableQtyInc><enableQtyIncrements>false</enableQtyIncrements><useConfigManageStock>true</useConfigManageStock><manageStock>true</manageStock><lowStockDate/><isDecimalDivided>false</isDecimalDivided><stockStatusChangedAuto>1</stockStatusChangedAuto></result>/ns1:catalogInventoryStockRegistryV1GetStockItemBySkuResponse/env:Body/env:Envelope

``` .
```

**Comment by mbrinton01** [comment]
Internal issue MAGETWO-52817

**Comment by skovalenk** [comment]
We cannot reproduce Issue MAGETWO-52817 on last mainline commit
