### ISSUE TITLE
Cannot register label when region ID is blank

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3698]
In my case 'shipping/origin/region_id' in 'core_config_data' is blank. For NL we don't work with regions, even though we are in a region. We are not used to mention the region on any address information.

Basically this blocks the creation of a Label as vendor/magento/module-shipping/Model/Shipping/Labels.php at Line 125 requires a Region Code. 

I think there are more countries where this applies to.

**Comment by piotrekkaminski** [comment]
@stefandoorn can you clarify how to reproduce it? Which shipping label you try to create - any specific shipping provider?

**Comment by stefandoorn** [comment]
I was using the UPS provider. So I made an order through checkout, then tried from backend to create the shipment. I was using an NL address, so without a region (blank) and that resulted in an error telling me that region cannot be blank when creating a label (see also the line provided above). 

Does this help enough, @piotrekkaminski? 

Edit: I was using an NL address for the origin of the shipment and also for the receiver of the shipment.

**Comment by magento-engcom-team** [comment]
@stefandoorn, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by stefandoorn** [comment]
Not using M2 right now, so cannot provide the requested information, therefore closing.
