### ISSUE TITLE
catalogrule_product and catalogrule_product_price tables repopulation causes auto_increment value out of range

### ISSUE THREAD

**Issue by IceReaper** [magento/magento2#3699]
Got a single price rule which applies to several thousand articles without any filter, it simply applies to all products.
On each cronjob execution (1x per minute) the tables catalogrule_product and catalogrule_product_price are getting truncated and refilled resulting in an incredible fast expiration of the auto_increment value.
Every minute the cronjob removes all 13.000 and 37.056 entries and reinserts them into the tables, resulting in an AI increse of 18.720.000 (catalogrule_product) and 53.360.640 (catalogrule_product_price) per day.
Had to truncate the tables and reset the AI twice since shop launch some weeks ago, as the indexer cronjob starts crashing with **"Out of range value for column 'rule_product_price_id' at row 1"**

**Comment by veloraven** [comment]
@IceReaper thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
