### ISSUE TITLE
magento 2.0.2 adminpanel base url is different from frontend base url 

### ISSUE THREAD

**Issue by neelimabenapally** [magento/magento2#3700]
Hi there,
- I've installed magento CE 2.0.2(with language selected to English Ireland) and the installation was successful 
- The css wasn't loading for frontend and backend so i ran the static content deploy command ( php bin/magento setup:static-content:deploy en_IE) 
- The frontend css was loaded but the backend(admin panel) didn't load
- When I checked for the source codes the frontend base url(http://../pub/static/frontend/Magento/luma/en_IE) and the backend base url are different(http://../pub/static/adminhtml/Magento/backend/en_US)

**Comment by piotrekkaminski** [comment]
@neelimabenapally do you still have this issue? anyone else has this issue? I cannot reproduce. If you still have this issue please open a new ticket.
