### ISSUE TITLE
GRID NOT WORKING

### ISSUE THREAD

**Issue by dssjignesh** [magento/magento2#3702]
i have created admin module on my localhost its working fine but as i have uploaded server its not showing GRID

**Comment by NadiyaS** [comment]
The GitHub issue tracker is intended for technical issues only. 
There can be several causes of your problem: cache, not upgraded DB, wrong xml for your grid etc.
Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
And to not forget to provide all necessary steps to reproduce it.
Thanks.
