### ISSUE TITLE
Moving a category to a new parent does not generate 301 redirects for product URLs

### ISSUE THREAD

**Issue by hiddenmike** [magento/magento2#37039]
### Preconditions and environment

- Magento 2.4.6 and potentially all prior versions

### Steps to reproduce

1. Install any recent version of Magento (2.4.4 - 2.4.6)
2. Enable the following settings under Catalog -> Catalog -> SEO
![Screenshot 2023-03-08 at 1 16 39 PM](https://user-images.githubusercontent.com/29709680/223796939-07a994c1-81f0-40c9-a51f-a637e34e14f1.png)
3. Create two categories under the root category with one child category under the first one.
4. Create a product and assign it to the child category.
5. Enable all categories and products.
6. Using the drag & drop feature of the category tree, move the child category to be underneath the second parent you created.
7. Navigate to Marketing -> URL Rewrites, and observe that a 301 redirect was created for the original category URL, but not for the original product URL within the original parent category.

### Expected result

A 301 redirect will be created for every category / product URL path within the original parent category pointing to the new category / product path under the new parent category.
Frontend visitors will get redirected to the new product URL path if they try to access the original path.

### Actual result

A 301 redirect was created from the old category path to the new one, but no redirects were created for product URLs.
Frontend visitors receive a 404 if they try to access the original product URL path.

### Additional information

The issue appears to lie in this observer `Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteMovingObserver`.
It calls this method `$this->urlRewriteHandler->deleteCategoryRewritesForChildren($category)`, which results in the product level rewrites being deleted before this method is run `$productUrlRewriteResult = $this->urlRewriteHandler->generateProductUrlRewrites($category)`, which looks for those rewrites for the purpose of creating 301 redirects.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
Just FYI, the admin URL for the Magento Instance provided above does not work, so I can't confirm the issue yet. I have done a clean install of 2.4.6 myself and confirmed it using the provided steps though.

**Comment by hiddenmike** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
I was able to confirm the issue on the instance provided. 
1. I enabled the settings I mentioned in my original reproduction steps.
2. I created a new category called "Test Category" underneath "What's New".
3. I created a new product called "Test Product" and assigned it to "Test Category".
4. I confirmed that the product was accessible at this URL: https://b1d0d64eeb09272b3bd92ea4b2df15d6.instances-prod.magento-community.engineering/what-is-new/test-category/test-product.html.
5. I moved the "Test Category" to be underneath "Sale".
6. I checked the product URL again and it results in a 404.
7. I checked URL Rewrites in the admin and the only 301 redirect created was from "what-is-new/test-category.html" to "sale/test-category.html"

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by hiddenmike** [comment]
I did create a patch which modifies the order of operations in the observer I mentioned, which does seem to solve the problem. It may not be a 100% solution since I had an issue afterword with those 301 redirects randomly disappearing when related categories or products were saved.

[move-category-product-redirects.patch](https://github.com/magento/magento2/files/10962163/move-category-product-redirects.patch)

**Comment by Yaroslav1301** [comment]
@magento I am working on this
