### ISSUE TITLE
Frontend Login Post Page

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#3703]
## Steps to reproduce
1. Install Magento from Release Archive
2. go directly on this page .. customer/account/loginPost/
## Actual result

Warning: array_key_exists() expects parameter 2 to be array, null given in ... /vendor/magento/module-captcha/Observer/CheckUserLoginObserver.php on line 80

**Comment by shiftedreality** [comment]
Hi @artmiller 

Thank you for your submission. Internal ticket MAGETWO-50247 was created to resolve this bug.

**Comment by mazhalai** [comment]
@artmiller closing since this has been resolved in commit b72339ed343bb00bf1e73da74f8a87a2ffa84dc7
