### ISSUE TITLE
feat: support Redis v7

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#37041]
### Description

As a user, I want to keep my subsystems up to date with the latest versions.

### Expected behavior

I would like to use Redis 7.

### Benefits

Maintenance

### Additional information

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html needs to be revised if it is supported.

### Release note

feat: support redis v7

**Comment by themew** [comment]
Adobe shows Redis 7 is compatible with Magento 2.4.6 along with other updates (Mariadb, Elasticsearch, Composer etc) being released this month.

https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-6.html

**Comment by damienwebdev** [comment]
Closing as this appears solved for v2.4.6.
