### ISSUE TITLE
.htaccess not downloaded

### ISSUE THREAD

**Issue by cesarkohl** [magento/magento2#3706]
Hi everyone,

Somehow my raw Magento clone was without the /.htaccess.
## Steps to reproduce
1. git clone this repository
2. followed the Wizard Setup
## Expected result
1. Access {magento root}/contact
## Actual result
1. {magento root}/contact returns "404 Not found"
## Solution
1. Downloaded the /.htaccess from this repository.
## Doubt
1. Somehow this file wasn't downloaded via git clone.

Best,
Cesar

**Comment by daim2k5** [comment]
I tried to reproduce the error but both .htaccess files still exists after the setup via wizard. Have you tried again?

**Comment by daim2k5** [comment]
Also maybe you can tell us a little bit more about your environment

**Comment by cesarkohl** [comment]
Hi,

I did the same proccess and fortunately it worked fine. Yesterday, probably I copied and pasted all the files in the folder to another empty folder but the hidden files weren't included in it.

Thanks for the help!

**Comment by ishakhsuvarov** [comment]
@cesarkohl Looks like your issue is resolved. Closing this ticket for now. Please feel free to reopen if the issue persists.
