### ISSUE TITLE
No REST API call for Setting payment Gateway Transaction

### ISSUE THREAD

**Issue by ipragmatechadmin** [magento/magento2#3709]
We are trying to build the generic android mobile app which can be used by magento 2 owners using REST API for Magento2 and have implemented the basic features for the app. As most of the people uses paypal for the payment gateway, we planned to use the paypal Android SDK for our mobile app but the problem is that we are not able to find the REST API to submit the transactionId or PaymentId to magento2. Do we need to write our own API for this or is there any existing rest API which we can use and submit the transactionId to magento2 store? Please help us.

**Comment by mbrinton01** [comment]
Internal issue MAGETWO-52815

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/No-REST-API-call-for-Setting-payment-Gateway-Transaction/idi-p/46056).
