### ISSUE TITLE
Readiness check states that var directory is not writable

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#3711]
I try to install i fresh copy of Magento 2.0.2
- Server: Nginx 1.8.1
- PHP 7.0.4

When running the readiness check, it states that the `var`-directory is not writable, although it's set to `777` permissions. The strange thing is that `app/etc`, `pub/media` and `pub/static` are set with the same rights and they pass the test.

**Comment by mrkhoa99** [comment]
@kanduvisla you set owner ship: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by kanduvisla** [comment]
A got it! I mounted my Nginx configuration to the wrong folder in vagrant. I had mounted it to `/vagrant/public`, but my PuPHPet configuration had set the permissions to `/var/www/public` which is basically a link to the same target, only with a different user/group.
