### ISSUE TITLE
Designing issue in magento sit

### ISSUE THREAD

**Issue by tushar4monto** [magento/magento2#3712]
Hello
I found one issue in your site page http://devdocs.magento.com/guides/v2.0/comp-mgr/bk-compman-upgrade-guide.html in this code
 <li class="leaf"><a href="/guides/v2.0/mtf/mtf_introduction.html">Magento Testing Framework Guide</a></li><li class="leaf"><a href="/guides/v2.0/pattern-library/bk-pattern.html">Magento Admin Pattern Library</a></li><div class="divider"></div></li>
Here last </li> does not have open <li> this it the error in your designing HTML code

**Comment by piotrekkaminski** [comment]
@tushar4monto i'm sorry but I don't understand this report. Can you provide more details and/or screenshot of the problem?

**Comment by tushar4monto** [comment]
Hello

I found that. There is one closed </li> tag but not open tag on this code
Magento Testing Framework Guide
Magento Admin Pattern Library

http://devdocs.magento.com/guides/v2.0/comp-mgr/bk-compman-upgrade-guide.html
Currently this page display proper
