### ISSUE TITLE
magento 2.0.2 when in product grid page and order grid page show Uncaught Error: Script error for: rjsResolver

### ISSUE THREAD

**Issue by TangLiang** [magento/magento2#3714]
## Steps to reproduce
1. Download Magento2.0.2 from magento website.
2. Environment is centos 7 LNMP+Varnish.run in production mode
   3.After run magento setup:static-content:deploy everything go fine but when i go backend to check orders and products page was blocked,the loading gif is run again and again.
   Error show below:

http://www.xxx.com/static/adminhtml/Magento/backend/en_US/rjsResolver.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:141 Uncaught Error: Script error for: rjsResolver
http://requirejs.org/docs/errors.html#scripterror

I am using the google chrome,after switch browser to firefox it's come back to normal.

I think this is a bug

**Comment by mazhalai** [comment]
@TangLiang have you setup up [magento user](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and checked if file permissions are as [recommended](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)?

**Comment by TangLiang** [comment]
@mazhalai 

Yes,my environment is LNMP+magento 2.0 lastest developer mode.
1,the web server user is www groud is www
2,I adduser magento,and create a strong passwd.
3,usermod -g www magento.
4,cd /home/wwwroot/xxxx.com/(magento root folder)
5,chown -R magento:www ./
6,find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento

After i did above,i can install magento 2 from setup wizde.But when i login to backend and go to product or category page it show the error

**Comment by anton-huz** [comment]
Hi Tang,
It is hard to help you with current set of information.

Issue with _rjsResolver.js_ means that `requirejs-config.js` wasn't loaded on the page or wasn't executed. So first of all we ask to check file permissions. But if you can log in Admin area and navigate to Product list page, then Magento application _in general_ works.

I can suggest you to:
1. Navigate to _weird_ page
2. Check source code
3. Find `requirejs-config.js`. First of all it _should exist_.
4. Try to open it: it should contain valid js code and a lot of strings `var config = {`.

In case all is right you can check _Network tab_ in developer tools of your browser: look for _abandoned requests_, _50x requests_ or somethng similar.

If here you has nothing strange we will to go deeper in your environment configuration.

**Comment by piotrekkaminski** [comment]
Closing due to lack of response.
