### ISSUE TITLE
Error in Tests unit

### ISSUE THREAD

**Issue by sjauck** [magento/magento2#3715]
Hello i try to run the Unit Tests shipped in Magento 2.0.2. 
If i try to get the coverage report i get always the error message 
`Trying to @cover or @use not existing method "\Magento\Setup\Controller\Marketplace::removeAuthAction".
`
I use 
./vendor/phpunit/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist --coverage-clover ".report.xml"

Is there a bug in the Tests or i have something missed?

**Comment by mazhalai** [comment]
I think there is a problem in running phpunit with the coverage option. Have you tried running without it?
It runs fine on travis: https://travis-ci.org/magento/magento2/jobs/114887738

**Comment by Vinai** [comment]
Yes, seems like it's a bug.
The following tests have the wrong `@covers` annotation:

```
\Magento\Setup\Test\Unit\Controller\MarketplaceTest::testRemoveCredetinalsAction
\Magento\Setup\Test\Unit\Controller\MarketplaceTest::testRemoveCredentialsWithError
```

The wrong covers annotation is

```
/**
 * @covers \Magento\Setup\Controller\Marketplace::removeAuthAction
 */
```

The correct annotation would be

```
/**
 * @covers \Magento\Setup\Controller\Marketplace::removeCredentialsAction
 */
```

**Comment by sjauck** [comment]
Hi.

Yes i tried without coverage and they run to the end. 
I tried the current Github Code after posting and it run with coverage. 

**EDIT:**
The Development Branch die at 17% with 
Trying to @cover or @use not existing method "\Magento\CatalogUrlRewrite\Observer\AfterImportDataObserver::afterImportData".

**Comment by mazhalai** [comment]
We have created MAGETWO-50846 to fix this.

**Comment by sjauck** [comment]
Thx for feedback. :)

**Comment by piotrekkaminski** [comment]
The issue was fixed and delivered.
