### ISSUE TITLE
Block head.additional declared in wrong module

### ISSUE THREAD

**Issue by AndresInSpace** [magento/magento2#37151]
### Summary

2.4-develop, 2.4.5-p1
IMO the head.additional block should belong in Magento_Theme default.xml along with the rest of the base layout declarations, but is currently in Magento_Catalog default xml while referencing template from magento theme.
`vendor/magento/module-catalog/view/frontend/layout/default.xml`
`<block class="Magento\Framework\View\Element\Template" name="head.additional" as="head.additional" template="Magento_Theme::html/container.phtml"/>`

### Examples

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/layout/default.xml#L68

### Proposed solution

Declare the block in Magento_Theme  default.xml and remove from Magento_Catalog default.xml

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/pull/32576/files
I have already done with this quite long time ago

**Comment by AndresInSpace** [comment]
My apologies
I did a search , but did not see it. This can be closed.
