### ISSUE TITLE
subtotal_incl_tax returns subtotal_excl_tax in minicart.phtml

### ISSUE THREAD

**Issue by SilvanLaroo** [magento/magento2#3717]
Hi,

I'm trying to show both prices including and excluding tax in minicart.phtml, but cart().subtotal_incl_tax returns the same amount as cart().subtotal_excl_tax. Tax is correctly setup, it shows the right amounts on the cart page.
## Steps to reproduce
1. Install Magento 2.0.2
2. To debug I added an console.log(this) in the file vendor/magento/module-checkout/view/frontend/web/js/view/minicart.js on line 76. 
3. From Chrome developer tools I checked what the values of subtotal_excl_tax and subtotal_incl_tax are.

**Expected result**
cart().subtotal_incl_tax should return price incl. tax in minicart.phtml

**Actual result**
cart().subtotal_incl_tax returns same amount as cart().subtotal_excl_tax

**Comment by ishakhsuvarov** [comment]
@SLv99 Could you please let us know which tax setting you are using?
Thank you.

**Comment by SilvanLaroo** [comment]
For the **Shopping Cart** all prices are excluding tax, but it should be possible to retrieve the price including tax right?

**Comment by mikeweis** [comment]
@SLv99 Is your point that you want to _display_ prices excluding tax, but _retrieve_ the price including tax (by using custom code)?

The following configuration should be working for _display_ (and thus retrieval):
- _Shopping Cart Display Settings_ ...
  - _Display Prices_ - Including and Excluding Tax
  - _Display Subtotal_ - Including and Excluding Tax

**Comment by SilvanLaroo** [comment]
Yes, that's exactly what I'm trying to do. It works with the settings you recommended, thanks!
