### ISSUE TITLE
Can't upload image to lookbook

### ISSUE THREAD

**Issue by jlee0023** [magento/magento2#37201]
### Summary

When uploading any image under 2MB it just says image failed, tried PNG and JPG both failed.

### Examples

In the MGS manage lookbook I am unable to upload an image.

### Proposed solution

Be able to upload an image

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @jlee0023,

Thank you for reporting and collaboration. “LookBook” is a 3rd party package / library that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page


Thank you.
