### ISSUE TITLE
2.4.5-p2 Pre-Release Availability

### ISSUE THREAD

**Issue by brandontamm** [magento/magento2#37219]
### Summary

I noticed that the 2.4.5-p2 is now available on Github. The 2.4.5-p2 mentioned a pre-release date of February 28. Was the pre-release made available on that day or was there a delay?

### Examples

n/a

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Yes it was available as pre-release around 28 February, but only to the people who had the necessary access for it through repo.magento.com

Why do you open a github issue for this, this isn't a bug report or a feature request, right?

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution & collaboration over here

Hi @brandontamm,

Thank you for reporting and collaboration.

Kindly refer this https://github.com/magento/magento2/issues/37219#issuecomment-1470918298 and please let us know if you are still facing any issue.


Thanks.

**Comment by brandontamm** [comment]
This issue was not reported as a bug. This was reported as an issue to “developer experience” based on the experience my developer reported that this pre release was not available at the time. Maybe we didn’t have access then. Ok to close
