### ISSUE TITLE
Marketplace automated technical tests are not conducted on 2.4.6

### ISSUE THREAD

**Issue by julienloizelet** [magento/magento2#37220]
### Summary

The "Quality report" paragraph in a marketplace module page states that :

> All tests were conducted on the latest versions of Adobe Commerce that existed for the compatible release lines at the moment of the extension submission. Latest versions of all other software were used, as applicable.

Tests should be conducted on Magento 2.4.6 and PHP 8.2 and seem to be conducted on 2.4.5-p1 and PHP 8.1.

![varnish-test-2023-03-16 15-36-28](https://user-images.githubusercontent.com/20956510/225535236-33dd59cc-a74a-44e6-a07b-f16c72f74321.png)

### Examples

Today, I submitted a module and I saw in the report.json (Installation and Varnish test) file that test were done on Magento 2.4.5-p1 and PHP 8.1.
![varnish-test-2023-03-16 15-36-28](https://user-images.githubusercontent.com/20956510/225535010-4039e22b-f433-4f4e-8e81-1faadd3a36d3.png)

### Proposed solution

Update the automated tests

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @julienloizelet,

Thanks for the report and collaboration!

This is a known issue and the internal team is working on updating test images to resolve it.

I will keep you posted on this. Marking this issue "On hold" for now.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @julienloizelet,

We have a confirmation from the developer that this issue has been fixed.

Hence closing this issue.

Thanks
