### ISSUE TITLE
"Disable Modules Output" page does not show correct status in dropdown

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3722]
When I disable a module output, it is actually disabled, however, the "Disable Modules Output" page does not reflect the change.

That causes that every time I want to disable a module output, I need to disable again modules I have disabled before.

Regards
Jaime

**Comment by shiftedreality** [comment]
Hi, @jaimestuardo 

I can't reproduce this issue on latest develop branch. Please, add more specific steps to reproduce it.

**Comment by designhunger** [comment]
I'm facing the same problem on ver. 2.0.3 with german locale on backend. I installed Magento via composer and did not change anything to the core files. What else would you need to reproduce this issue?
Thanks!

**Comment by hshar7** [comment]
Hey guys I am not able to reproduce this. If I disable a module using cli then it will not show up on the Configurations page. If I disable it from the Configurations page then it will stay as "disable"
Screenshot:
![screen shot 2016-05-09 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/17727543/15151466/dad2d380-1696-11e6-8b25-c3aaeb754cb5.png)
