### ISSUE TITLE
Missing .htaccess Files

### ISSUE THREAD

**Issue by pconHinrichs** [magento/magento2#3723]
I've tryed the last 3 days to install Magento2 on my Webserver.

CentOS with Plesk
PHP7 and PHP5.6
MySQL5.6 (MariaDB 10)

I'll do all with the Guide: http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web.html
After the installation I fixed the .css and .js issues with this Guide: http://magento.stackexchange.com/a/96569
And after that, the Backend worked but in the Frontend I got 403 Errors The Owner and Group rights are all fine. Now I checked the Logfiles and found this message:

> [core:crit](13)Permission denied: AH00529: /var/www/vhosts/idreamelephants.de/httpdocs/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/idreamelephants.de/httpdocs/' is executable, referer: http://www.idreamelephants.de/setup/

I have looked on the FTP and found in the pub/static/\* there is no .htaccess files.

**Comment by piotrekkaminski** [comment]
This question is better suited for stackexchange.magento.com or community.magento.com
