### ISSUE TITLE
Prducts and Category url suffix duplicate slash and .html

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#3726]
I can´t manage propertly products and categories url´s. When I save a product and go to table url rewrite are all url´s are wrong. Duplicate suffix .html and slash " / "
![product_url_suffix](https://cloud.githubusercontent.com/assets/16081377/13689514/a8fc4496-e729-11e5-9172-9939ce024e88.jpg)

**Comment by voleye** [comment]
Hi @salelsol , could you please verify configuration settings in 
Store->Configuration->(Catalog)->Catalog->"Search Engine Optimization" 
- Product URL Suffix?
- Category URL Suffix?

Also, please, clarify what value of URL do you set for product?

**Comment by salelsol** [comment]
- Hi Volodomir, is Product URL Suffix is .html then duplicate suffix, if Product URL Suffix is empty then:
- I think Products URL SEO not works properly.

Best Regards
Toni

**Comment by piotrekkaminski** [comment]
I cannot reproduce this issue. If issue persists in 2.1, please open a new ticket.

**Comment by mage-dave** [comment]
This issue still is in 2.1.3. We are using the migration tool as well. All of the urls get .html.html. If we remove the SEO suffix before saving a category, the .html is removed from the rewrites and when the category is saved the .html's get added back to the rewrite/redirects.

**Comment by vikaskumra** [comment]
Hi

It seems to be magento known issue, you can use product and category after save observers to fix it until magento team provides a solutions. I can help you with this, as I have fixed double slash error in product urls for my client magento website using observers.

If you are a programmer and need code, feel free to contact me.

Thanks
Vikas
