### ISSUE TITLE
Rest API calls give 401 Unauthorized in response since Magento 2.4.6

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#37278]
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce

1. Create a product with a SKU with special characters, for example a forward slash.
2. Try to PUT or GET its stock or info through the REST API, see more info below in the comments.

### Expected result

Working REST API.

### Actual result

[Error message: 401 Unauthorized: The signature is invalid. Verify and try again.]

### Additional information

**Update 1**
After debugging I found out that because of special characters in our SKU the signature comparison fails. Read below for more info and check https://github.com/magento/magento2/issues/37278#issuecomment-1478635403

**Update 2**
It should be a special character not allowed in an URL, so for example a forward slash which gets replaced by Hex.
https://github.com/magento/magento2/issues/37278#issuecomment-1481245655

Updated above steps to be more in line with the problem.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment]
It seems its related to the products endpoint only, need further debugging to confirm.

**Comment by jorgb90** [comment]
```
grep -rnw '/home/xxx/public_html/' -e 'The signature is invalid. Verify and try again.'
/home/xxx/public_html/vendor/magento/framework/Oauth/Oauth.php:207:            throw new AuthException(new Phrase('The signature is invalid. Verify and try again.'));
```

https://github.com/magento/magento2/blob/2.4.6/lib/internal/Magento/Framework/Oauth/Oauth.php#L207

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance the issue is not reproducible. Kindly refer the screenshots.

In **Magento 2.4-develop instance**

<img width="952" alt="Screenshot 2023-03-23 at 7 16 09 PM" src="https://user-images.githubusercontent.com/51680745/227224490-eb2dae93-6680-428c-95cf-88f90f3e7c2d.png">


In **Magento 2.4.6 instance**


<img width="921" alt="Screenshot 2023-03-23 at 7 19 03 PM" src="https://user-images.githubusercontent.com/51680745/227224543-a9c026c5-ba6e-4aa4-bd49-64ede8de0cfc.png">



In Both the cases the REST API is working fine.Kindly check your authorization tokens.

Please let us know if you are still facing any issue.


Thanks.

**Comment by jorgb90** [comment]
@engcom-Bravo Your doing it wrong. The SKU should be for example "MLY33N/A" through the API as URL this becomes "MLY33N%2FA", so try to use "http://magento246.local/rest/default/V1/products/MLY33N%2FA" as URL.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance the issue is not reproducible. Kindly refer the screenshots.


We have created a product with `MLY33N/A` and slash `/` is taken as `-` for a product.


<img width="1431" alt="Screenshot 2023-03-24 at 3 05 59 PM" src="https://user-images.githubusercontent.com/51680745/227511190-bc1b2d1f-6681-4ae7-bfd8-a4bc2e5c99fe.png">



REST API is working fine using `PUT` method in both the cases.


**Magento 2.4-develop instance**


<img width="884" alt="Screenshot 2023-03-24 at 3 07 17 PM" src="https://user-images.githubusercontent.com/51680745/227511277-daa55562-37d8-4afc-aa97-c501911e7662.png">




**Magento 2.4.6 instance**

<img width="905" alt="Screenshot 2023-03-24 at 3 06 12 PM" src="https://user-images.githubusercontent.com/51680745/227511316-aee26c75-1491-4c03-890c-246c18351276.png">



Kindly recheck the issue on Magento 2.4-develop instance and Magento 2.4.6 instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance the issue is not reproducible. Kindly refer the screenshots.

We are getting `404 Not Found` Response in both the instances.


We have created a product with name `Laptop` and sku `MLY33N/A` and we are hitting a `GET` Request.

<img width="1325" alt="Screenshot 2023-03-27 at 6 48 43 PM" src="https://user-images.githubusercontent.com/51680745/227951094-749c55dd-d84b-4e76-98db-d54e10ef4bed.png">




<img width="1070" alt="Screenshot 2023-03-27 at 6 49 05 PM" src="https://user-images.githubusercontent.com/51680745/227950778-2a0603cb-ffbe-4061-a3da-6538d63b9759.png">




<img width="1088" alt="Screenshot 2023-03-27 at 6 50 54 PM" src="https://user-images.githubusercontent.com/51680745/227950794-a3861b13-63cc-42e9-92cc-24232331778d.png">



Kindly let us know if we are missing anything.

Thanks.

**Comment by jorgb90** [comment]
@engcom-Bravo I don't know if it makes a difference but your adding "default" to the endpoint. According to the Magento documentation the endpoint "/rest/V1/products/SKU" should work and definitely not give a 404 Not Found.

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thanks for your update.

We have Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance without default in the endpoint still we are getting `404 Not Found` Response in both the instances..Kindly refer the screenshots.



<img width="1108" alt="Screenshot 2023-03-28 at 11 49 47 AM" src="https://user-images.githubusercontent.com/51680745/228254045-3a9e850d-c7b4-4b55-a158-21393495631f.png">




<img width="932" alt="Screenshot 2023-03-28 at 11 50 42 AM" src="https://user-images.githubusercontent.com/51680745/228254096-7c838483-2930-406c-bfbf-da8f5690bc3e.png">



We have verified with without special characters we are getting `404 Not Found`.


<img width="883" alt="Screenshot 2023-03-28 at 7 04 49 PM" src="https://user-images.githubusercontent.com/51680745/228254468-9fd077f0-2d0a-4aab-999c-5fcc2d6f7a75.png">






AS per https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes.  if we allow slashes to decoded could potentially allow unsafe paths and security issues.use of `NoDecode` is strongly recommended as a security measure.


<img width="1354" alt="Screenshot 2023-03-28 at 7 07 02 PM" src="https://user-images.githubusercontent.com/51680745/228255637-59e0b207-2d88-4283-b0c0-1aae917405ca.png">




Kindly let us know if you are still facing any issue.


Thanks.

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thanks for your update.

We have set to `AllowEncodedSlashes NoDecode`

<img width="862" alt="Screenshot 2023-03-29 at 4 20 54 PM" src="https://user-images.githubusercontent.com/51680745/228535503-be3de982-df19-4fef-90e6-be08a99f26a2.png">

Still we are getting `404 NOT FOUND` in the response.


<img width="883" alt="Screenshot 2023-03-29 at 4 11 09 PM" src="https://user-images.githubusercontent.com/51680745/228535685-f560cd66-4bdb-42c4-9e14-a6cdb90abe78.png">


Kindly let us if we are missing anythIng and provide any missing steps.


Thanks.

**Comment by jorgb90** [comment]
@engcom-Bravo I am not an Apache expert unfortunately, but the only way to get a 404 Not found is when decoding is still active, cause then it will rewrite

`http://kumar.local/rest/V1/products/MLY33N%2FA`

as

`http://kumar.local/rest/V1/products/MLY33N/A`

And thats of course a not existing path and by that gives a 404 Not Found.

A quick Google gave me that you probably need to set it inside a <VirtualHost> container as well. I think you are now doing it in global server config?

**Comment by jorgb90** [comment]
@engcom-Bravo Thanks. Very strange though. I will look into it further. The only thing we did was an upgrade from Magento 2.4.5-p1 to 2.4.6 and then it stopped working. So it must be something with the changes made to the framework or auth.

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

Thanks for your update.

verified the issue while upgrading from 2.4.5-p1 to 2.4.6 we are not able to reproduce the issue.Kindly refer the screenshots.


<img width="1191" alt="Screenshot 2023-03-28 at 3 44 15 PM" src="https://user-images.githubusercontent.com/51680745/229727414-d03d1695-e4b0-41b0-9e70-18339f0987a6.png">


<img width="886" alt="Screenshot 2023-04-04 at 1 29 13 PM" src="https://user-images.githubusercontent.com/51680745/229727478-40a61547-b767-4fea-b87e-0a3cc1ac400c.png">




Kindly let us if still you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @jorgb90,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by hostep** [comment]
@jorgb90: I just noticed this fix in Apache 2.4.57: https://github.com/apache/httpd/blob/5e5c0286bb3bd714f5c5b97f96189ed9ba589cdc/CHANGES#L9-L11

It sounds kind of related to this issue, so maybe it wasn't a bug in Magento, but in Apache that you ran into?

**Comment by mamsincl** [comment]
@jorgb90 
```diff --git a/vendor/magento/framework/Oauth/Oauth.php b/vendor/magento/framework/Oauth/Oauth.php
index 898f70e2..af2fdc85 100644
--- a/vendor/magento/framework/Oauth/Oauth.php
+++ b/vendor/magento/framework/Oauth/Oauth.php
@@ -203,7 +203,19 @@ class Oauth implements OauthInterface
             $requestUrl
         );
 
-        if (!Security::compareStrings($calculatedSign, $params['oauth_signature'])) {
+        $calculatedSignWithEncodedPercentage = $this->_httpUtility->sign(
+            $allowedSignParams,
+            $params['oauth_signature_method'],
+            $consumerSecret,
+            $tokenSecret,
+            $httpMethod,
+            str_replace('%', '%25', $requestUrl)
+        );
+
+        if (
+            !Security::compareStrings($calculatedSign, $params['oauth_signature']) &&
+            !Security::compareStrings($calculatedSignWithEncodedPercentage, $params['oauth_signature'])
+        ) {
             throw new AuthException(new Phrase('The signature is invalid. Verify and try again.'));
         }
     }

```

a little bit less dirty than entirely passing the validation

**Comment by simonmaass** [comment]
we can confirm this issue - we are facing the exact same problem after updating to 2.4.6!

**Comment by cykolln** [comment]
Can similarly confirm - using the same endpoint `/products` to request an item by sku containing encoded `/` . Testing with the same oauth creds using another product from the same store that does not contain the slash results in a successful response. Besides adjusting core code, have any other adjustments or workarounds worked for anyone?

**Comment by jorgb90** [comment]
@engcom-Bravo Can this be reopened? Seems to be not an issue specific for us.

**Comment by jorgb90** [comment]
> The signature is invalid. Verify and try again

This works 

> @jorgb90
> 
> ```diff
> index 898f70e2..af2fdc85 100644
> --- a/vendor/magento/framework/Oauth/Oauth.php
> +++ b/vendor/magento/framework/Oauth/Oauth.php
> @@ -203,7 +203,19 @@ class Oauth implements OauthInterface
>              $requestUrl
>          );
>  
> -        if (!Security::compareStrings($calculatedSign, $params['oauth_signature'])) {
> +        $calculatedSignWithEncodedPercentage = $this->_httpUtility->sign(
> +            $allowedSignParams,
> +            $params['oauth_signature_method'],
> +            $consumerSecret,
> +            $tokenSecret,
> +            $httpMethod,
> +            str_replace('%', '%25', $requestUrl)
> +        );
> +
> +        if (
> +            !Security::compareStrings($calculatedSign, $params['oauth_signature']) &&
> +            !Security::compareStrings($calculatedSignWithEncodedPercentage, $params['oauth_signature'])
> +        ) {
>              throw new AuthException(new Phrase('The signature is invalid. Verify and try again.'));
>          }
>      }
> ```
> 
> a little bit less dirty than entirely passing the validation

This works as well. Thanks!

**Comment by jorgb90** [comment]
When does this get fixed? Next release?

**Comment by jorgb90** [comment]
Magento 2.4.7 and still got this issue.. @engcom-Bravo

**Comment by jorgb90** [comment]
2.4.7-p1 and still this issue not fixed.

**Comment by barryvdh** [comment]
I backported the changes from the OAuth namespace in 1 commit, see https://github.com/barryvdh/magento2/commit/f80894310cd02eb30482e7bb427bb35f37b38222

Composer patch could look like this for magento/framework:

<details>

```
diff --git a/Oauth/Helper/Request.php b/Oauth/Helper/Request.php
index 9342257556fea..bcdfa5cba4943 100644
--- a/Oauth/Helper/Request.php
+++ b/Oauth/Helper/Request.php
@@ -43,6 +43,11 @@ public function prepareRequest($httpRequest)
             $httpRequest->getContent(),
             $this->getRequestUrl($httpRequest)
         );
+        foreach ($oauthParams as $key => $value) {
+            if ($key !== 'oauth_signature') {
+                $oauthParams[$key] = rawurlencode($value);
+            }
+        }
         return $oauthParams;
     }

diff --git a/Oauth/Helper/Signature/Hmac.php b/Oauth/Helper/Signature/Hmac.php
new file mode 100644
index 0000000000000..bc965314dce82
--- /dev/null
+++ b/Oauth/Helper/Signature/Hmac.php
@@ -0,0 +1,40 @@
+<?php
+/**
+ * Copyright 2024 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\Oauth\Helper\Signature;
+
+use Laminas\Uri;
+use Laminas\OAuth\Signature\Hmac as HmacSignature;
+use Magento\Framework\Oauth\Helper\Uri\Http;
+
+class Hmac extends HmacSignature
+{
+    /**
+     * @inheritDoc
+     */
+    public function normaliseBaseSignatureUrl($url): string
+    {
+        $registeredHttpScheme = Uri\UriFactory::getRegisteredSchemeClass('http');
+        $registeredHttpsScheme = Uri\UriFactory::getRegisteredSchemeClass('https');
+        Uri\UriFactory::registerScheme('http', Http::class);
+        Uri\UriFactory::registerScheme('https', Http::class);
+        $uri = Uri\UriFactory::factory($url);
+        Uri\UriFactory::registerScheme('http', $registeredHttpScheme);
+        Uri\UriFactory::registerScheme('https', $registeredHttpsScheme);
+        $uri->normalize();
+        if ($uri->getScheme() == 'http' && $uri->getPort() == '80') {
+            $uri->setPort('');
+        } elseif ($uri->getScheme() == 'https' && $uri->getPort() == '443') {
+            $uri->setPort('');
+        } elseif (! in_array($uri->getScheme(), ['http', 'https'])) {
+            throw new \InvalidArgumentException('Invalid URL provided; must be an HTTP or HTTPS scheme');
+        }
+        $uri->setQuery('');
+        $uri->setFragment('');
+        return $uri->toString();
+    }
+}
diff --git a/Oauth/Helper/Uri/Http.php b/Oauth/Helper/Uri/Http.php
new file mode 100644
index 0000000000000..501e916b709b5
--- /dev/null
+++ b/Oauth/Helper/Uri/Http.php
@@ -0,0 +1,26 @@
+<?php
+/**
+ * Copyright 2024 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\Oauth\Helper\Uri;
+
+use Laminas\Uri\Http as LaminasHttp;
+
+class Http extends LaminasHttp
+{
+    /**
+     * @inheritDoc
+     */
+    protected static function normalizePath($path): string
+    {
+        return self::encodePath(
+            self::decodeUrlEncodedChars(
+                self::removePathDotSegments($path),
+                '/[' . self::CHAR_UNRESERVED . ':@&=\+\$,;%]/'
+            )
+        );
+    }
+}
diff --git a/Oauth/Helper/Utility.php b/Oauth/Helper/Utility.php
new file mode 100644
index 0000000000000..31c0e609f2718
--- /dev/null
+++ b/Oauth/Helper/Utility.php
@@ -0,0 +1,83 @@
+<?php
+/**
+ * Copyright 2024 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\Oauth\Helper;
+
+use Laminas\OAuth\Http\Utility as LaminasUtility;
+use Magento\Framework\Oauth\Helper\Signature\HmacFactory;
+
+class Utility
+{
+    /**
+     * @param LaminasUtility $httpUtility
+     * @param HmacFactory $hmacFactory
+     */
+    public function __construct(private readonly LaminasUtility $httpUtility, private readonly HmacFactory $hmacFactory)
+    {
+    }
+
+    /**
+     * Generate signature string
+     *
+     * @param array $params
+     * @param string $signatureMethod
+     * @param string $consumerSecret
+     * @param string|null $tokenSecret
+     * @param string|null $method
+     * @param string|null $url
+     * @return string
+     */
+    public function sign(
+        array  $params,
+        string $signatureMethod,
+        string $consumerSecret,
+        ?string $tokenSecret = null,
+        ?string $method = null,
+        ?string $url = null
+    ): string {
+        if ($this->isHmac256($signatureMethod)) {
+            $hmac = $this->hmacFactory->create(
+                ['consumerSecret' => $consumerSecret,
+                    'tokenSecret' => $tokenSecret,
+                    'hashAlgo' => 'sha256'
+                ]
+            );
+
+            return $hmac->sign($params, $method, $url);
+        } else {
+            return $this->httpUtility->sign($params, $signatureMethod, $consumerSecret, $tokenSecret, $method, $url);
+        }
+    }
+
+    /**
+     * Check if signature method is HMAC-SHA256
+     *
+     * @param string $signatureMethod
+     * @return bool
+     */
+    private function isHmac256(string $signatureMethod): bool
+    {
+        if (strtoupper(preg_replace('/[\W]/', '', $signatureMethod)) === 'HMACSHA256') {
+            return true;
+        }
+
+        return false;
+    }
+
+    /**
+     * Cast to authorization header
+     *
+     * @param array $params
+     * @param string|null $realm
+     * @param bool $excludeCustomParams
+     */
+    public function toAuthorizationHeader(array $params, ?string $realm = null, bool $excludeCustomParams = true)
+    {
+        $authorizationHeader = $this->httpUtility->toAuthorizationHeader($params, $realm, $excludeCustomParams);
+        return str_replace('realm="",', '', $authorizationHeader);
+    }
+}
diff --git a/Oauth/Oauth.php b/Oauth/Oauth.php
index 898f70e206a9c..c959f6d46155f 100644
--- a/Oauth/Oauth.php
+++ b/Oauth/Oauth.php
@@ -6,7 +6,7 @@

 namespace Magento\Framework\Oauth;

-use Laminas\OAuth\Http\Utility;
+use Magento\Framework\Oauth\Helper\Utility;
 use Magento\Framework\Encryption\Helper\Security;
 use Magento\Framework\Phrase;
 use Magento\Framework\Oauth\Exception as AuthException;
@@ -21,11 +21,6 @@ class Oauth implements OauthInterface
      */
     protected $_oauthHelper;

-    /**
-     * @var  Utility
-     */
-    protected $_httpUtility;
-
     /**
      * @var \Magento\Framework\Oauth\NonceGeneratorInterface
      */
@@ -36,23 +31,27 @@ class Oauth implements OauthInterface
      */
     protected $_tokenProvider;

+    /**
+     * @var Utility
+     */
+    private Utility $httpUtility;
+
     /**
      * @param Helper\Oauth $oauthHelper
      * @param NonceGeneratorInterface $nonceGenerator
      * @param TokenProviderInterface $tokenProvider
-     * @param \Zend_Oauth_Http_Utility $httpUtility
+     * @param Utility $utility
      */
     public function __construct(
         Helper\Oauth $oauthHelper,
         NonceGeneratorInterface $nonceGenerator,
         TokenProviderInterface $tokenProvider,
-        Utility $httpUtility = null
+        Utility $utility
     ) {
         $this->_oauthHelper = $oauthHelper;
         $this->_nonceGenerator = $nonceGenerator;
         $this->_tokenProvider = $tokenProvider;
-        // null default to prevent ObjectManagerFactory from injecting, see MAGETWO-30809
-        $this->_httpUtility = $httpUtility ?: new Utility();
+        $this->httpUtility = $utility;
     }

     /**
@@ -155,7 +154,7 @@ public function buildAuthorizationHeader(
             'oauth_version' => '1.0',
         ];
         $headerParameters = array_merge($headerParameters, $params);
-        $headerParameters['oauth_signature'] = $this->_httpUtility->sign(
+        $headerParameters['oauth_signature'] = $this->httpUtility->sign(
             $params,
             $signatureMethod,
             $headerParameters['oauth_consumer_secret'],
@@ -163,10 +162,8 @@ public function buildAuthorizationHeader(
             $httpMethod,
             $requestUrl
         );
-        $authorizationHeader = $this->_httpUtility->toAuthorizationHeader($headerParameters);
-        // toAuthorizationHeader adds an optional realm="" which is not required for now.
-        // http://tools.ietf.org/html/rfc2617#section-1.2
-        return str_replace('realm="",', '', $authorizationHeader);
+
+        return $this->httpUtility->toAuthorizationHeader($headerParameters);
     }

     /**
@@ -191,11 +188,8 @@ protected function _validateSignature($params, $consumerSecret, $httpMethod, $re
             );
         }

-        $allowedSignParams = $params;
-        unset($allowedSignParams['oauth_signature']);
-
-        $calculatedSign = $this->_httpUtility->sign(
-            $allowedSignParams,
+        $calculatedSign = $this->httpUtility->sign(
+            $params,
             $params['oauth_signature_method'],
             $consumerSecret,
             $tokenSecret,
diff --git a/Oauth/Test/Unit/Helper/RequestTest.php b/Oauth/Test/Unit/Helper/RequestTest.php
index d61f7c77edcde..34024761b2de7 100644
--- a/Oauth/Test/Unit/Helper/RequestTest.php
+++ b/Oauth/Test/Unit/Helper/RequestTest.php
@@ -61,7 +61,7 @@ public function testPrepareErrorResponse($exception, $expected)
     /**
      * @return array
      */
-    public function dataProviderForPrepareErrorResponseTest()
+    public static function dataProviderForPrepareErrorResponseTest()
     {
         return [
             [
@@ -105,7 +105,7 @@ public function testGetRequestUrl($url, $host)
     /**
      * @return array
      */
-    public function hostsDataProvider()
+    public static function hostsDataProvider()
     {
         return  [
             'hostWithoutPort' => [
@@ -155,7 +155,7 @@ public function testPrepareRequestOAuthHeader($authHeaderValue, $expectedParams)
     /**
      * @return array
      */
-    public function dataProviderForTestPrepareRequestOAuthHeader()
+    public static function dataProviderForTestPrepareRequestOAuthHeader()
     {
         return [
             [
diff --git a/Oauth/Test/Unit/Helper/UtilityTest.php b/Oauth/Test/Unit/Helper/UtilityTest.php
new file mode 100644
index 0000000000000..6430d15c3ac94
--- /dev/null
+++ b/Oauth/Test/Unit/Helper/UtilityTest.php
@@ -0,0 +1,96 @@
+<?php
+/**
+ * Copyright 2024 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\Oauth\Test\Unit\Helper;
+
+use Magento\Framework\Oauth\Helper\Utility as OauthUtility;
+use Laminas\OAuth\Http\Utility as LaminasUtility;
+use Magento\Framework\Oauth\Helper\Signature\Hmac;
+use Magento\Framework\Oauth\Helper\Signature\HmacFactory;
+use PHPUnit\Framework\MockObject\MockObject;
+use PHPUnit\Framework\TestCase;
+
+class UtilityTest extends TestCase
+{
+    /**
+     * @var LaminasUtility|MockObject
+     */
+    private LaminasUtility $httpUtility;
+
+    /**
+     * @var Hmac|MockObject
+     */
+    private Hmac $hmac;
+
+    /**
+     * @var HmacFactory|MockObject
+     */
+    private HmacFactory $hmacFactory;
+
+    protected function setUp(): void
+    {
+        $this->httpUtility = $this->createMock(LaminasUtility::class);
+        $this->hmac = $this->createMock(Hmac::class);
+        $this->hmacFactory = $this->createMock(HmacFactory::class);
+    }
+
+    /**
+     * @return void
+     */
+    public function testSignMethodUsesHmac256WhenSignatureMethodIsHmacSha256(): void
+    {
+        $params = ['param1' => 'value1'];
+        $signatureMethod = 'HMACSHA256';
+        $consumerSecret = 'secret';
+        $tokenSecret = 'tokenSecret';
+        $method = 'POST';
+        $url = 'http://example.com';
+
+        $expectedSignature = 'expectedSignature';
+
+        $this->hmac->expects($this->once())
+            ->method('sign')
+            ->with($params, $method, $url)
+            ->willReturn($expectedSignature);
+        $this->hmacFactory->expects($this->once())
+            ->method('create')
+            ->with(['consumerSecret' => $consumerSecret, 'tokenSecret' => $tokenSecret, 'hashAlgo' => 'sha256'])
+            ->willReturn($this->hmac);
+
+        $utility = new OauthUtility($this->httpUtility, $this->hmacFactory);
+
+        $signature = $utility->sign($params, $signatureMethod, $consumerSecret, $tokenSecret, $method, $url);
+
+        $this->assertEquals($expectedSignature, $signature);
+    }
+
+    /**
+     * @return void
+     */
+    public function testSignMethodUsesLaminasUtilityWhenSignatureMethodIsRsa(): void
+    {
+        $params = ['param1' => 'value1'];
+        $signatureMethod = 'RSA';
+        $consumerSecret = 'secret';
+        $tokenSecret = 'tokenSecret';
+        $method = 'POST';
+        $url = 'http://example.com';
+
+        $expectedSignature = 'expectedSignature';
+
+        $this->httpUtility->expects($this->once())
+            ->method('sign')
+            ->with($params, $signatureMethod, $consumerSecret, $tokenSecret, $method, $url)
+            ->willReturn($expectedSignature);
+
+        $utility = new OauthUtility($this->httpUtility, $this->hmacFactory);
+
+        $signature = $utility->sign($params, $signatureMethod, $consumerSecret, $tokenSecret, $method, $url);
+
+        $this->assertEquals($expectedSignature, $signature);
+    }
+}

```

</details>

**Comment by barryvdh** [comment]
I've tested it, and it works for the slashes, but not for all. See test script:

<details>

```php
<?php
ini_set("display_errors", 1);
error_reporting(E_ALL);

require __DIR__ .'/../vendor/autoload.php';

use GuzzleHttp\Client,
    GuzzleHttp\HandlerStack,
    GuzzleHttp\Subscriber\Oauth\Oauth1;

$stack = HandlerStack::create();

$middleware = new Oauth1([
    'consumer_key' => '',
    'consumer_secret' => '',
    'token' => '',
    'token_secret' => '',
    'signature_method' => Oauth1::SIGNATURE_METHOD_HMACSHA256,
]);
$stack->push($middleware);

$client = new Client([
    'base_uri' => 'https://elgabest.test/',
    'handler' => $stack,
    'auth' => 'oauth',
    'headers' => [
        'Content-Type' => 'application/json',
    ],
    'http_errors' => false,
]);

$skus = [
    'example',
    'example/2',
    'example\3',
    'example+4',
    'example&5',
    'example%6',
    'example:7',
    'example@8',
];
foreach ($skus as $sku) {
    $response = $client->request('POST', '/rest/V1/products', [
        'json' => [
            'product' => [
                'sku' => $sku,
                "name" => $sku,
                "attribute_set_id" => 4,
                "status" => 1,
                "visibility" => 4,
                "type_id" => "simple",
                'price' => 10
            ]
        ]
    ]);

    if ($response->getStatusCode() > 201) {
        var_dump('Error creating ' . $sku . ': ' . json_decode($response->getBody()->getContents(), true)['message']);
    }


    $response = $client->request('PUT', '/rest/V1/products/' . urlencode($sku), [
        'json' => [
            'product' => [
                'price' => 20
            ]
        ]
    ]);

    if ($response->getStatusCode() > 201) {
        var_dump('Error updating ' . $sku . ': ' . json_decode($response->getBody()->getContents(), true)['message']);
    } else {
        var_dump('Succes updating ' . $sku);
    }
}

```
</details>

Result:

```
string(23) "Succes updating example"
string(25) "Succes updating example/2"
string(25) "Succes updating example\3"
string(73) "Error updating example+4: The signature is invalid. Verify and try again."
string(73) "Error updating example&5: The signature is invalid. Verify and try again."
string(25) "Succes updating example%6"
string(73) "Error updating example:7: The signature is invalid. Verify and try again."
string(73) "Error updating example@8: The signature is invalid. Verify and try again."
```

**Comment by james-windandkite** [comment]
Thanks for the backport Barry, hugely helpful.

I had an issue with it when doing calls like this:

```
$response = $client->request('GET', '/rest/V1/orders/', [
    'query' => [
        'searchCriteria[filterGroups][0][filters][0][field]' => 'status',
        'searchCriteria[filterGroups][0][filters][0][value]' => 'pending',
        'searchCriteria[filterGroups][0][filters][0][condition_type]' => 'eq',

        'searchCriteria[filterGroups][1][filters][0][field]' => 'created_at',
        'searchCriteria[filterGroups][1][filters][0][value]' => '2024-10-25 00:00:00',
        'searchCriteria[filterGroups][1][filters][0][condition_type]' => 'gt',

        'searchCriteria[current_page]' => '1',
        'searchCriteria[page_size]' => '20'
    ]
]);
```

When we have dates with spaces this fails and we get a different error:

`The signature is invalid. Verify and try again`

This comes from `vendor/magento/framework/Oauth/Oauth.php` as the signatures do not match.

I found this to be caused by changes in `vendor/magento/framework/Oauth/Helper/Oauth.php` where the URL is encoded:

```
diff --git a/Oauth/Helper/Request.php b/Oauth/Helper/Request.php
index 9342257556fea..bcdfa5cba4943 100644
--- a/Oauth/Helper/Request.php
+++ b/Oauth/Helper/Request.php
@@ -43,6 +43,11 @@ public function prepareRequest($httpRequest)
             $httpRequest->getContent(),
             $this->getRequestUrl($httpRequest)
         );
+        foreach ($oauthParams as $key => $value) {
+            if ($key !== 'oauth_signature') {
+                $oauthParams[$key] = rawurlencode($value);
+            }
+        }
         return $oauthParams;
```

Removing this fixed that issue for me, and I'm still able to pull SKUs with `/` in them. For my use case that's all I needed, but I wonder if it might also help for SKUs with other symbols in too.

**Comment by frostitution** [comment]
> They just merged a fix for ticket with name [ACP2E-2969: REST API unable to make requests with slash (/) in SKU when using Oauth1](https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-2969&type=commits), merge commit here: [69ee14d](https://github.com/magento/magento2/commit/69ee14d68d08866149efc43799422143244a3021)
> 
> [@jorgb90](https://github.com/jorgb90): it sounds very related to this issue, do you think this could be the fix for this issue?

I see this is referenced in Magento 2.4.8 release notes. Can anyone confirm this helps resolve the issue? Can we apply this to previous Magento versions as a quality patch? We just discovered this issue ourselves after enabling 2FA and having to switch to OAuth. Our only solution right now is to disable 2FA and go back to token connection
