### ISSUE TITLE
Magento2 REST API with XML data is not working during inventory upload

### ISSUE THREAD

**Issue by utpalmaity** [magento/magento2#3727]
I am building an application which is using Magento REST API for exchanging data and I am using XML for transferring data. But during posting data in XML format I am getting an error "stock item field is required".For inventory upload I am using PUT method and URL for hitting API is like this.

http://myhost.com/Individual/XXX/magento2/index.php/rest/V1/products/Stock/stockItems/2

and XML data I am sending is below

```
<stockItem>
    <itemId>2</itemId>
    <productId>2</productId>
    <qty>10</qty>
    <isInStock>true</isInStock>
    <isQtyDecimal>true</isQtyDecimal>
    <showDefaultNotificationMessage>true</showDefaultNotificationMessage>
    <useConfigMinQty>true</useConfigMinQty>
    <minQty>0</minQty>
    <useConfigMinSaleQty>0</useConfigMinSaleQty>
    <minSaleQty>0</minSaleQty>
    <useConfigMaxSaleQty>true</useConfigMaxSaleQty>
    <maxSaleQty>0</maxSaleQty>
    <useConfigBackorders>true</useConfigBackorders>
    <backorders>0</backorders>
    <useConfigNotifyStockQty>true</useConfigNotifyStockQty>
    <notifyStockQty>0</notifyStockQty>
    <useConfigQtyIncrements>true</useConfigQtyIncrements>
    <qtyIncrements>0</qtyIncrements>
    <useConfigEnableQtyInc>true</useConfigEnableQtyInc>
    <enableQtyIncrements>true</enableQtyIncrements>
    <useConfigManageStock>true</useConfigManageStock>
    <manageStock>true</manageStock>
    <lowStockDate></lowStockDate>
    <isDecimalDivided>true</isDecimalDivided>
    <stockStatusChangedAuto>0</stockStatusChangedAuto>
</stockItem>
```

**Comment by utpalmaity** [comment]
hi @yaronish @katmoon @vzabaznov any update on this issue

**Comment by jpreed2** [comment]
That looks like JSON to me, not XML.

**Comment by maityutpal** [comment]
The data is in XML format . If there is problem in that XML please tell me where I have to change .

**Comment by jpreed2** [comment]
Sorry, you're right. I've only used JSON with the Rest API, so can’t help with XML. Are you setting the content type of your request to text/xml or application/xml?

**Comment by piotrekkaminski** [comment]
@mbrinton01 can you look into it?

**Comment by mbrinton01** [comment]
@maityutpal your XML seems to validate without errors on some online XML validation tools.  Have you set the `Content-Type` of your request?

**Comment by maityutpal** [comment]
Hi all,
Any update on this issue. And I set the content type right.

**Comment by mbrinton01** [comment]
I have created internal issue MAGETWO-55211 to research this.  I can confirm that the call works with JSON, are you able to format the body as JSON?

**Comment by maityutpal** [comment]
yes it is working in JSON format but XML is not working.

**Comment by gody01** [comment]
Hello,

is this issue resolved ?

**Comment by gody01** [comment]
Hello,

Problem is in the file:
vendor/magento/framework/Webapi/Rest/Request/Deserializer/Xml.php

        /** Data will always have exactly one element so it is safe to call reset here. */
        return reset($data);

        If I remove reset than XML input works.

        /** Data will always have exactly one element so it is safe to call reset here. */
        return ($data);

**Comment by magento-engcom-team** [comment]
@utpalmaity, thank you for your report.
We've created internal ticket(s) MAGETWO-55211 to track progress on the issue.

**Comment by sanjay-wagento** [comment]
@magento-engcom-team @okorshenko I reviewed above issue and I can not find Rest API "V1/products/Stock/stockItems" in 2.2-develop and 2.1.9
 But I can see "/V1/products/:productSku/stockItems/:itemId" Rest API and I can reproduce same error.

**Comment by ishakhsuvarov** [comment]
@gody01 @utpalmaity Does it work when enclosing whole request in `<xml>`?

**Comment by magento-engcom-team** [comment]
@utpalmaity, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
