### ISSUE TITLE
Payment information does not save

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#3729]
## Steps to reproduce
1. Install Magento from `master` branch. Version 2.0.2
2. Go to Store - Configuration - Sales - Payment Methods
3. Configure PayPal PayFlow Pro
4. Start create order process
## Expected result
1. Validate credit card number before request to PayPal. 
2. Save information cc_exp_month and cc_exp_year in 'sales_order_payment' table
## Actual result
1. can enter any chapters into credit card field 
2. cc_exp_month and cc_exp_year did not save in sales_order_payment
## Additional information

Saving cc_exp_month and cc_exp_year is important for me, because I need this information for reauthorization process. It works well in Magento 1.x. 
Maybe, this logic is missed in M2, because I can not find save process of this information like in M1.
Also I found initialization of $_canSaveCc field, but I can not find where it field using. It was use in prepareSave() method (app/code/core/Mage/Payment/Model/Method/Cc.php) in M1.

.//app/code/Magento/Braintree/Model/PaymentMethod.php:93:    protected $_canSaveCc               = false;
.//app/code/Magento/Payment/Model/Method/Cc.php:27:    protected $_canSaveCc = false;
.//app/code/Magento/Paypal/Model/Direct.php:96:    protected $_canSaveCc = false;
.//app/code/Magento/Paypal/Model/Hostedpro.php:64:    protected $_canSaveCc = false;
.//app/code/Magento/Paypal/Model/Payflowpro.php:203:    protected $_canSaveCc = false;

**Comment by OleksiyOleksiyovych** [comment]
I have tried on develop branch and cc_exp_month and cc_exp_year saved well.
But credit card field does not validate
https://www.dropbox.com/s/gj9inu4jdcvuv65/Screenshot%202016-03-11%2012.16.30.png

**Comment by piotrekkaminski** [comment]
@antboiko can you review?

**Comment by piotrekkaminski** [comment]
@asemenenko can you review?

**Comment by viktym** [comment]
Hi @OleksiyOleksiyovych 

We've created internal ticket MAGETWO-59147 regarding validation credit card number on backend.
Issue with saving information cc_exp_month and cc_exp_year in 'sales_order_payment' table was fixed in 2.1.x releases and develop branch. Also fix will be delivered in 2.0.11 patch release.

Thanks for the feedback.

**Comment by piotrekkaminski** [comment]
This issue will be moved to Ideas forum as the improvement component (validation) is not yet scheduled. The bug (not saving the CC information) was fixed and is available already.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Payment-information-does-not-save/idi-p/49585).

**Comment by Ctucker9233** [comment]
Where can I find the fix for the 2.1 branch?
