### ISSUE TITLE
ImportExport module: can't add custom file adapter

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#3730]
I tried to add a custom file format to the import and/or to override the default csv adapter and saw that the adapter is chosen in Magento\ImportExport\Model\Import\Adapter.

The problem is that the factory method present in that class is not a real Magento2 factory, so it can't be injected.

In general it seems that quite all the module is ported from Magento 1 and therefore is not expandable with Magento 2 mechanics.

**Comment by maksek** [comment]
Hi @giacmir, GitHub is for reported issues with steps to reproduce. All HowTo questions you may address in forum.
