### ISSUE TITLE
Cookie Messages is read-only and can not be manipulated

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#37308]
### Summary

Common customizations of Magento include creating a hide or close button for customer messages, and having it automatically disappear after a certain amount of seconds.

The right way to approach this is to modify the application state. In this case it would be necessary for developers to modify the messages array, which should cause the UI to be rerendered by Knockout's dual way data-binding. This is often done through a JS mixin that extends the `messages.js` UI Component.

At the moment this is not possible. The `cookieMessages` array is not an observable attribute and the UI does not react to any changes.

(Also see Example 1 in the official documentation: https://knockoutjs.com/documentation/foreach-binding.html)

My suggestion is convert the cookieMessages into an observable attribute, so that developers are able to manipulate the state causing a proper UI rerender.

### Examples

`messages-mixin.js`:

At the moment, manipulating the `cookieMesssages` attribute does not cause the UI to be updated.

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages && this.cookieMessages.length > 0) {
                    setTimeout((function () {
                        this.cookieMessages = [];
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

However, in-line with Magento philosophy, we would like the state to be reflected in the UI by using an observable instead. This is expected behaviour:

`messages-mixin.js`:

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages() && this.cookieMessages().length > 0) {
                    setTimeout((function () {
                        this.cookieMessages([]);
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

### Proposed solution

Convert cookieMessages into an observable. Unfortunately the fix for this will necessarily be backwards incompatible for merchants that have overwritten `vendor/magento/module-theme/view/frontend/templates/messages.phtml`.

I will create a PR.

edit: https://github.com/magento/magento2/pull/37309

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by erfanimani** [comment]
@magento I am working on this

**Comment by erfanimani** [comment]
Hi @engcom-Hotel, could you clarify what you mean? This is a developer/customisation/code improvement — there's no end-user issue associated with this ticket.

**Comment by engcom-Hotel** [comment]
Hi @erfanimani,

What I mean to say is, in order to confirm the issue we need some proper steps to reproduce this issue. After confirmation on this ticket, a JIRA will create, and that JIRA will process further.

Thanks

**Comment by erfanimani** [comment]
Hi @engcom-Hotel, I'm not sure how relevant the steps to reproduce are for this ticket, but it would go something like this:

Expected result:

* Developer wants to customise `cookieMessages`
* Developer creates a mixin and manipulates cookieMessages variable

Actual result:

* Developer can't manipulate cookieMessages variable and instead need to overwrite entire JS files.

As mentioned, this is not an end user bug but an internal improvement.

**Comment by ihor-sviziev** [comment]
The issue was fixed in https://github.com/magento/magento2/commit/38b8b516489a6e436177c59f61ec5903cd8552c5 (changes from https://github.com/magento/magento2/pull/37309)
