### ISSUE TITLE
Fedex service update

### ISSUE THREAD

**Issue by sanmic** [magento/magento2#37313]
### Description

I discovered that the Latest M2 is using very old FedEx wsdl files when trying to add the FEDEX_REGIONAL_ECONOMY and FEDEX_INTERNATIONAL_PRIORITY rates.

M2 is using v10 wsdl files, current FedEx wsdl files are at v31.

Are there any plans to update the core FedEx module?

### Expected behavior

Enable to get rates for FEDEX_REGIONAL_ECONOMY and FEDEX_INTERNATIONAL_PRIORITY services.

### Benefits

Be able to use full Fedex potential.

**Comment by sanmic** [comment]
@magento give me 2.4-develop instance

**Comment by jaminion** [comment]
I'd like to point out that FedEx has announced the retirement date for the SOAP web services that M2 currently uses: https://www.fedex.com/en-us/developer/announcements.html#web-services - they will be retired on May 15th, 2024. There is a much older issue, #34642, for feature request to implement the REST api but doesn't appear to have any traction. It may be more useful to push for the REST services implementation, considering how many releases we expect to see before that date there isn't that much opportunity.

It's also pretty useful to use plugins to alter the service request object before it's sent to FedEx to rate if you're looking to make particular tweaks to specific stores, I use those to make adjustments to residential indicator for our personal logic, as well as some implementation for city-state-zip-weight caching. You might use a composer patch to make adjustments to the wsdl file if you find that necessary. Good luck!

**Comment by thinksys-dev** [comment]
Hi All,

Is there any update or information on this ?

Thanks.

**Comment by andrewbess** [comment]
Hello folk
It looks like we will have FedEx Rest API from Magento 2.4.7
I see necessary changes in the 2.4.7-beta2 tag

**Comment by andrewbess** [comment]
The requested features already implemented and will be released in 100.4.5
The issue closed due to reason above

**Comment by quochuy1508** [comment]
> FEDEX_REGIONAL_ECONOMY and FEDEX_INTERNATIONAL_PRIORITY is not available in the list of options. Note that "INTERNATIONAL_PRIORITY " is not the same as "FEDEX_INTERNATIONAL_PRIORITY".
> 
> ![image](https://user-images.githubusercontent.com/5544888/228762554-db741d53-5bd3-4bfd-9d28-047129e94e46.png) ![image](https://user-images.githubusercontent.com/5544888/228762977-be48d4af-9194-43a6-82d5-aebcd85a4706.png)

I got the same error with @jaminion. Any update on this point? Thanks

**Comment by mattyl** [comment]
We have had to manually add the services which is less than ideal

**Comment by plac2** [comment]
We added the services manually.
Now I see "Regional Economy" on the backend, but not in the frontend.
Should I upgrade to 2.4.7?
I am currently on 2.4.6-p2
