### ISSUE TITLE
onclick actions in magento 2

### ISSUE THREAD

**Issue by polyakovao** [magento/magento2#3731]
Hi, I have 
`<a href="#" class="my_action_upgrade">Add caption to db</a>`
in my templates/test.phtml file 
and  
`public function upgrade() { ... }`
in my block/test.php

when i'm calling 
`
<?php  $block->upgrade(); ?> 
`
in my test.phtml it works fine, but i want my `upgrade()` function to work on click. How can i do it in magento 2 properly?

**Comment by maksek** [comment]
Hi @polyakovao , GitHub is for reported issues with steps to reproduce. All HowTo questions you may address in forum.
