### ISSUE TITLE
Revert 36041: created cyclic build graph

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#37322]
### Preconditions and environment

- Magento version (2.4-develop)

### Steps to reproduce

1. Look at v2.4-develop
2. Look at https://github.com/magento/magento2/pull/36041
3. See the modification to `module-catalog`'s composer.json
4. Consider the appropriate module dependencies.

### Expected result

No dependency on grouped-product.

### Actual result

Dependency on grouped product.

### Additional information

This is a completely ridiculous commit. It's criss-crossing packages. The entire thing needs to be reversed. The code itself is probably ok, but someone from arch needs to guide this process better (or we need a tool to protect the graph from this nonsense).

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

cc:@maghamed @sidolov

**Comment by engcom-Hotel** [comment]
Hello @damienwebdev,

Thanks for the report and collaboration!

We need some more elaboration on the issue, are you talking as mentioned below:

1. `module-catalog`'s composer.json `requires` module `magento/module-grouped-product`:
https://github.com/magento/magento2/blob/3b6828d74f44d99f6cabbab19186616762f32214/app/code/Magento/Catalog/composer.json#L35

2. And `module-group-product`'s composer.json `requires` module `magento/module-backend`:
https://github.com/magento/magento2/blob/3b6828d74f44d99f6cabbab19186616762f32214/app/code/Magento/GroupedProduct/composer.json#L11

which makes a cyclic build graph which needs to be remove. 

Are we on the same page? or please let us know if we have missed anything.

Thanks

**Comment by damienwebdev** [comment]
The cycle is much more simple.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/GroupedProduct/composer.json

Requires `module-catalog`.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/composer.json#L35

Requires `module-grouped-product`

**Comment by damienwebdev** [comment]
@sidolov @maghamed attempting to get visibility on this issue -- this can't stay in the codebase.

**Comment by engcom-Hotel** [comment]
Hello @damienwebdev,

Thanks for the reply!

We are confirming this issue as per the below comments:

https://github.com/magento/magento2/issues/37322#issuecomment-1494099102
https://github.com/magento/magento2/issues/37322#issuecomment-1494109711

Thanks

**Comment by thecodecook14** [comment]
@magento I am working on this

**Comment by ihor-sviziev** [comment]
@damienwebdev, good catch! Even more, such a circular dependency should cause test failures, so I'm shocked it got merged.
