### ISSUE TITLE
How to get product 2.0 maxSaleQty on product view page 

### ISSUE THREAD

**Issue by TangLiang** [magento/magento2#3732]
Hi All,

I want to get magento 2.0 product maxSaleQty on product view page.How can i got that?

thanks

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
