### ISSUE TITLE
Error in BrainTree PayPal after update to 2.4.6

### ISSUE THREAD

**Issue by Cupropituvanso** [magento/magento2#37325]
### Preconditions and environment

Error happens after upgrading Magento from 2.4.5-p1 to 2.4.6.
Braintree PayPal enabled.

### Steps to reproduce

1. Open any Productpage
2. Click Add To Cart

### Expected result

Item can be added to cart.

### Actual result

- Nothing happens except a forever spinning wheel on the cart.
- Error in exception.log

### Additional information

`main.CRITICAL: TypeError: PayPal\Braintree\Block\Paypal\Button::numberToString(): Argument #1 ($num) must be of type string|float, null given, called in /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php on line 519 and defined in /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php:606
Stack trace:
#0 /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php(519): PayPal\Braintree\Block\Paypal\Button->numberToString()
#1 /var/www/mcoeshop/vendor/paypal/module-braintree-core/view/frontend/templates/paypal/button.phtml(32): PayPal\Braintree\Block\Paypal\Button->getCartLineItems()
#2 /var/www/mcoeshop/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#3 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#4 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#5 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/mcoeshop/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#7 /var/www/mcoeshop/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#8 /var/www/mcoeshop/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#9 /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php(123): Magento\Framework\View\Element\Template->_toHtml()
#10 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(1095): PayPal\Braintree\Block\Paypal\Button->_toHtml()
#11 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#12 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#13 /var/www/mcoeshop/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /var/www/mcoeshop/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#15 /var/www/mcoeshop/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /var/www/mcoeshop/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /var/www/mcoeshop/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#18 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /var/www/mcoeshop/vendor/magento/module-catalog/Block/ShortcutButtons.php(100): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Catalog\Block\ShortcutButtons->_toHtml()
#21 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#22 /var/www/mcoeshop/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#23 /var/www/mcoeshop/vendor/magento/module-checkout/CustomerData/Cart.php(101): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\CustomerData\Cart->getSectionData()
#25 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\CustomerData\Cart\Interceptor->___callParent()
#26 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\CustomerData\Cart\Interceptor->Magento\Framework\Interception\{closure}()
#27 /var/www/mcoeshop/generated/code/Magento/Checkout/CustomerData/Cart/Interceptor.php(23): Magento\Checkout\CustomerData\Cart\Interceptor->___callPlugins()
#28 /var/www/mcoeshop/vendor/magento/module-customer/CustomerData/SectionPool.php(90): Magento\Checkout\CustomerData\Cart\Interceptor->getSectionData()
#29 /var/www/mcoeshop/vendor/magento/module-customer/CustomerData/SectionPool.php(60): Magento\Customer\CustomerData\SectionPool->getSectionDataByNames()
#30 /var/www/mcoeshop/vendor/magento/module-customer/Controller/Section/Load.php(78): Magento\Customer\CustomerData\SectionPool->getSectionsData()
#31 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Section\Load->execute()
#32 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Section\Load\Interceptor->___callParent()
#33 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure}()
#34 /var/www/mcoeshop/generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php(23): Magento\Customer\Controller\Section\Load\Interceptor->___callPlugins()
#35 /var/www/mcoeshop/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Section\Load\Interceptor->execute()
#36 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#37 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Section\Load\Interceptor->___callParent()
#38 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/mcoeshop/generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php(32): Magento\Customer\Controller\Section\Load\Interceptor->___callPlugins()
#40 /var/www/mcoeshop/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Section\Load\Interceptor->dispatch()
#41 /var/www/mcoeshop/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#42 /var/www/mcoeshop/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#43 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#44 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#45 /var/www/mcoeshop/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#46 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#47 /var/www/mcoeshop/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#48 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#49 /var/www/mcoeshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#50 /var/www/mcoeshop/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#51 /var/www/mcoeshop/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#52 /var/www/mcoeshop/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#53 /var/www/mcoeshop/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#54 /var/www/mcoeshop/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#55 {main} {"exception":"[object] (TypeError(code: 0): PayPal\\Braintree\\Block\\Paypal\\Button::numberToString(): Argument #1 ($num) must be of type string|float, null given, called in /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php on line 519 at /var/www/mcoeshop/vendor/paypal/module-braintree-core/Block/Paypal/Button.php:606)"} []`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by n2diving-dgx** [comment]
See https://github.com/magento/magento2/issues/37242#issue-1631254518

**Comment by Cupropituvanso** [comment]
Thanks, I close this issue and write a link in the other issue because of the error log from the server, which is not sent in the other issue.
