### ISSUE TITLE
After login backend menu on the left doesn't work

### ISSUE THREAD

**Issue by hanzels** [magento/magento2#37329]
### Preconditions and environment

- Magento 2.4.3
- Amasty updated all their extenions inour shop. I looked like it worked fine.

### Steps to reproduce

Login in our backend and see that it doesn't work

### Expected result

I would like to be able to use the menu on the right.

### Actual result

No error messages were displayed.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Bravo** [comment]
HI @hanzels,

Thank you for reporting and collaboration. “Amasty” is a 3rd party package / library that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page.


Thanks.
