### ISSUE TITLE
As a developer I want to have the pagebuilder content as an AST so that I don't have to parse the HTML to an AST to render with React.

### ISSUE THREAD

**Issue by paales** [magento/magento2#37330]
As a developer I want to have the pagebuilder content as an AST so that I don't have to parse the HTML to an AST to render with React.

Currently [PWA Studio](https://github.com/magento/pwa-studio/blob/6bfcd878249e3c969326783d31648fa0f4b07991/packages/pagebuilder/lib/parseStorageHtml.js) and [GraphCommerce](https://github.com/graphcommerce-org/graphcommerce/tree/canary/packages/magento-pagebuilder) need to build a completely custom HTML parser to extract all content from the pagebuilder pages.

I assume there already is an internal representation of the content as an AST which gets rendered to the current output. The current parser is very brittle and practically unextendable. 

### AC
* Provide the pagebuilder content as an pagebuilder_ast field which returns the ast.
* In an ideal scenario would be completely described by GraphQL, but that might be a bit difficult, so it might be acceptable to have a PagebuilderAST scalar.

**Comment by engcom-Hotel** [comment]
Hello @paales,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @paales,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by bronar** [comment]
@paales just add PageBuilder's convertBackgroundImages plugin into custom etc/graphql/di.xml config file and GraphQL will return parsed html in content field of CmsPage type.

`<type name="Magento\Framework\Filter\Template">
    <plugin name="convertBackgroundImages" type="Magento\PageBuilder\Plugin\Filter\TemplatePlugin"/>
</type>`

**Comment by paales** [comment]
Hi @bronar I'm not sure how this would solve the issue, it will still output HTML wouldn't it?
