### ISSUE TITLE
GTag not send transaction prices and totals.

### ISSUE THREAD

**Issue by Bashev** [magento/magento2#37348]
### Preconditions and environment

- Magento version: >= 2.4.5-p1, 2.4.5-p2, 2.4.6

### Steps to reproduce

1. Enable Gtag (Store - Configuration - Sales - Google API - GTag - Enable and add Gtag Key
2. Add product to cart and finish an order.
3. On success page you need capture OrderTrackingData which was send to Google Tag.

### Expected result

Currency need to be part of the order, not part of the "all" orders provided. Reference from Google Analytics docs: https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#make_a_purchase_or_issue_a_refund

![image](https://user-images.githubusercontent.com/1854269/230713701-3d4ba69a-7c8a-4aa2-a3ab-22beca7cc2c6.png)

### Actual result

![image](https://user-images.githubusercontent.com/1854269/230713395-90d2cac1-c3a2-4295-a5c6-7d9d69991f8e.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
@magento I am working on this

**Comment by Bashev** [comment]
@magento give me 2.4-develop instance

**Comment by Bashev** [comment]
@engcom-November what kind of update is required? How we can move this forward, Google stops Universal Analytics in 35 days, but GTag not send ecommerre data.

**Comment by the2003s** [comment]
I'm getting the same issue on multiple websites. versions 2.4.5-p2 & 2.4.5-p1.

**Comment by istoutjesdijk** [comment]
Same issue here, we could use a fix soon. GA4 needs to be functional by the end of the month.

**Comment by ryanisn** [comment]
You could also workaround this issue by setting default value on purchase event with a currency in GA4, if you run a single currency store.
