### ISSUE TITLE
Full page cache and currency issue (and session)

### ISSUE THREAD

**Issue by monteshot** [magento/magento2#37351]
### Preconditions and environment

- Magento version 2.4.2 and seems like newest
- Redis as session storage any non-deprecated version
- Env.php settings similar to :
` 'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => 'localhost',
            'port' => '6379',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '8',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '4',
            'max_concurrency' => '512',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000',
            'sentinel_master' => '',
            'sentinel_servers' => '',
            'sentinel_connect_retries' => '5',
            'sentinel_verify_master' => '0'
        ]
    ],  
    'lock' => [
        'provider' => 'db',
        'config' => [
            'prefix' => null
        ]
    ],  
    'cache_types' => [
        'config' => 1,
        'layout' => 1,
        'block_html' => 1,
        'collections' => 1,
        'reflection' => 1,
        'db_ddl' => 1,
        'compiled_config' => 1,
        'eav' => 1,
        'customer_notification' => 1,
        'config_integration' => 1,
        'config_integration_api' => 1,
        'full_page' => 1,
        'config_webservice' => 1,
        'translate' => 1,
        'vertex' => 1,
        'perspective_ipstack_cache' => 1
    ]  
`
- Also you need multi website and multi currency M2 instance with similar configuration to this:
-- On default config set settings as on screenshot
![image](https://user-images.githubusercontent.com/2836146/230743207-ad58e540-5845-404e-bdb7-3d0b016645ff.png)
-- On Website with bug set UAH currency(for example) as base and default display and set three others currency like EUR, USD, UAH
-- Setup the rates to rates you like the correspond page

### Steps to reproduce

Go to category page
Set the currency to UAH.
Go to the product page.
Change currency to USD.
Add a product to the cart.
Remove an item from the cart.
Pay attention to the currency in the popup.
Go to the category page.
Add a product to the cart.
Remove an item from the cart.
Pay attention to the currency in the popup.
Change the currency to UAH.
Pay attention to the currency in the header and on the catalog page.
Add an item to the cart.
Pay attention to the currency in the header and on the catalog page.

### Expected result

Currency switcher switch to target currency with enabled full page and redis and correspond to quote currency

### Actual result

Currency switcher NOT switch to target currency withenabled full page and redis and not correspond to quote currency

### Additional information

Seems like relevant to issue https://github.com/magento/magento2/issues/28204

The sympthoms is entry of error in log file:
[2023-04-04 14:04:49] .ERROR: Undefined rate from "USD-USD". [] []

Then second problem is not correct cache segment at \Magento\PageCache\Model\App\FrontController\BuiltinPlugin::aroundDispatch:
![image](https://user-images.githubusercontent.com/2836146/230743562-6f766fc4-246e-4e85-bc95-cbd8a4fced92.png)
Array with segment data uses PREVIOUS currency - X-Magento-Vary cookie incorrect at this point.

When i debug deeper and commented(and hardcoded in value in the getValue method nothing changes
![image](https://user-images.githubusercontent.com/2836146/230743653-788a099f-6473-4c9d-b2a1-a6c1993d47a7.png)
 
 BUT when i started debug step-by-step I see that incorrect currency stored in session in Redis at point of forwarding after 302 redirect from SwitchAction
 
![image](https://user-images.githubusercontent.com/2836146/230743745-3b241314-bb84-497e-ae4b-95a7f01f1f3d.png)

If i make dirty custom as delete incorrect X-Magento-Vary cookie
![image](https://user-images.githubusercontent.com/2836146/230743811-ff07b8a8-a4ac-4c0c-9d87-5c52b8fea72f.png)

 and the plugin on beforeDispatch to \Magento\Store\App\Action\Plugin\Context::beforeDispatch
![image](https://user-images.githubusercontent.com/2836146/230743828-2ff0919e-8912-43ff-a264-5a7468b8c7bd.png)
Seems like my hack the same as cacheable="false"

Also system.log may have these logs:
![image](https://user-images.githubusercontent.com/2836146/230744423-7f754c77-342d-4ae7-84a7-8351e077e317.png)

![image](https://user-images.githubusercontent.com/2836146/230744019-693bdfc7-b758-4ec7-971c-a510fb387299.png)
with log above sometimes M2 throw an error while i tried to reload the page
![image](https://user-images.githubusercontent.com/2836146/230744064-6fc58cfd-49d6-4919-80d5-3d106f329ddd.png)

Additional media with bug:
- The video with bug:

https://user-images.githubusercontent.com/2836146/230743428-2cdd0fcc-6b4b-400b-ab91-f06f7a245183.mp4

https://user-images.githubusercontent.com/2836146/230744182-21e694a7-2819-443b-953f-0b2ceb7e1f6b.mp4

https://user-images.githubusercontent.com/2836146/230744200-be2e768e-4bdf-4733-9026-39708c223c08.mp4

https://user-images.githubusercontent.com/2836146/230744241-bf6de251-2bb0-42cb-a537-cda54717c59e.mp4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @monteshot ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues on 2.4-develop instance.
Thank you.

**Comment by monteshot** [comment]
@magento give me 2.4-develop instance
