### ISSUE TITLE
Clean up Action / AbstractAction / ActionInterface

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#3736]
Magento 2 behaves inconsistently if a action controller does not extend `\Magento\Framework\App\Action\Action`, but instead directly implements `\Magento\Framework\App\ActionInterface`.

There are two key things that are missed if an action controller directly implements the interface as far as I can tell:
1. The `controller_action_predispatch*` and `controller_action_postdispatch*` events are not dispatched
2. The before/around/after plugins of `Action::dispatch()` and `AbstractAction::dispatch()`are not called.

The method `\Magento\Framework\App\FrontController::dispatch()` however correctly processes action controllers implementing the interface directly.

This is a blocker for third party developers to use the `ActionInterface`, as a lot of core functionality will be missing or broken unless `Action` is extended. Developers are forced to extend `Action` with all it's dependencies, even though most are not needed.

My question is if you would be open to evaluating a PR that attempts to resolve this with the following changes.
1. Change all core observers of the `controller_action_predispatch*` and `controller_action_postdispatch*` events into `\Magento\Framework\App\ActionInterface::execute()` plugins. The observers listening to more specific events could intercept the concrete controllers instead of the `ActionInterface`.
   - `Magento\User\Observer\Backend\ForceAdminPasswordChangeObserver`
   - `Magento\AdminNotification\Observer\PredispatchAdminActionControllerObserver`
   - `Magento\Captcha\Observer\CheckUserLoginObserver`
   - `Magento\Captcha\Observer\CheckUserCreateObserver`
   - `Magento\Captcha\Observer\CheckForgotpasswordObserver`
   - `Magento\Captcha\Observer\CheckGuestCheckoutObserver`
   - `Magento\Captcha\Observer\CheckRegisterCheckoutObserver`
   - `Magento\Captcha\Observer\CheckUserForgotPasswordBackendObserver`
   - `Magento\Captcha\Observer\CheckForgotpasswordObserver`
   - `Magento\Captcha\Observer\CheckContactUsFormObserver`
   - `Magento\Captcha\Observer\CheckUserEditObserver`
   - `Magento\Customer\Observer\Visitor\InitByRequestObserver`
   - `Magento\NewRelicReporting\Model\Observer\ReportConcurrentAdmins`
   - `Magento\NewRelicReporting\Model\Observer\ReportConcurrentAdminsToNewRelic`
   - `Magento\NewRelicReporting\Model\Observer\ReportConcurrentUsers`
   - `Magento\NewRelicReporting\Model\Observer\ReportConcurrentUsersToNewRelic`
   - `Magento\PageCache\Observer\RegisterFormKeyFromCookie`
   - `Magento\Persistent\Observer\SetRememberMeCheckedStatusObserver`
   - `Magento\Persistent\Observer\SetRememberMeStatusForAjaxLoginObserver`
   - `Magento\Persistent\Observer\SetRememberMeCheckedStatusObserver`
   - `Magento\Persistent\Observer\CustomerAuthenticatedEventObserver`
   - `Magento\Persistent\Observer\EmulateQuoteObserver`
   - `Magento\Persistent\Observer\RenewCookieObserver`
   - `Magento\Persistent\Observer\CheckExpirePersistentQuoteObserver`
   - `Magento\Persistent\Observer\EmulateCustomerObserver`
   - `Magento\Persistent\Observer\PreventExpressCheckoutObserver`
   - `Magento\Persistent\Observer\PreventClearCheckoutSessionObserver`
   - `Magento\User\Observer\Backend\ForceAdminPasswordChangeObserver`
2. Change all `\Magento\Framework\App\Action\Action::dispatch()` and `\Magento\Framework\App\Action\AbstractAction::dispatch()` plugins to intercept `\Magento\Framework\App\ActionInterface::execute()` intead.
   - `Magento\Store\App\Action\Plugin\Context`
   - `Magento\Customer\Model\App\Action\ContextPlugin`
   - `Magento\Store\App\Action\Plugin\StoreCheck`
   - `Magento\Framework\App\Action\Plugin\Design`
   - `Magento\Tax\Model\App\Action\ContextPlugin`
   - `Magento\Weee\Model\App\Action\ContextPlugin`
3. Move the dispatching of the legacy `controller_action_predispatch*` and `controller_action_postdispatch*` events into the `FrontController` or an intermediate delegate.
4. Add the `@api` annotation to `\Magento\Framework\App\ActionInterface`.

With those changes in place developers would be free to directly implement the `ActionInterface`. Design by contract would be encouraged, and the amount of Magento 1 legacy code could further be reduced.  
Backward compatibility would be retained.

Until the requirement to extend `Action` is removed, the `ActionInterface` does more harm then it helps. It serves no purpose as it should not be used anywhere. So if these changes are not embraced, I suggest marking the interface as deprecated, as to avoid confusion. At the same time `\Magento\Framework\App\Action\Action` should be blessed with the `@api` annotation since every single module with an action controller needs to depend on it.

Further reference: http://magento.stackexchange.com/questions/105575/where-is-the-design-theme-initialized-during-a-frontend-request

**Comment by piotrekkaminski** [comment]
@antonkril please review

**Comment by antonkril** [comment]
Yes, this is a blocker for ActionInterface. And we already have a fix for this. It did not get to 2.1, but is scheduled for 2.2.

Instead of redeclaring observers as plugins, we added a plugin that dispatches events. We found couple temporal dependencies, so we wanted to keep the point in time when events are triggered. 

I will close the issue. Please reopen it if you have more questions.

**Comment by Vinai** [comment]
Oh, very nice solution! Thanks for the update 👍
