### ISSUE TITLE
Add missing methods to \Magento\Framework\App\Response\HttpInterface

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#3737]
Would you be willing to evaluate a PR that adds the following methods to `\Magento\Framework\App\Response\HttpInterface`?
- `setHttpResponseCode`
- `setStatusHeader`
- `setHeader`
- `appendBody`
- `setBody`
- `setRedirect`
- `representJson`

@SchumacherFM opened the issue https://github.com/magento/magento2/issues/2038 where @antonkril correctly stated that these methods make no sense on the `\Magento\Framework\Controller\ResultInterface`. However, they do fit well into `\Magento\Framework\App\Response\HttpInterface`.  

If these methods where added then the following `AbstractResult` implementations could up-cast the `\Magento\Framework\App\ResponseInterface` to `HttpResponse` giving PHP interpreter level type safety, plus making it explicit that they do not work with any other result type.
- `\Magento\Framework\Controller\Result\Raw`
- `\Magento\Framework\View\Result\Page`
- `\Magento\Framework\View\Result\Layout`
- `\Magento\Framework\Controller\Result\Redirect`
- `\Magento\Framework\Controller\Result\Json`

This is how such an up-cast could look like:

``` php
    /**
     * @param HttpInterface $response
     * @return $this
     */
    protected function render(ResponseInterface $response)
    {
        return $this->renderHttpResponse($response);
    }

    /**
     * @param HttpInterface $response
     * @return $this
     */
    private function renderHttpResponse(HttpInterface $response)
    {
        $response->setBody($this->contents);
        return $this;
    }
```

**Comment by antonkril** [comment]
These methods make sense on HttpInterface with its current design.

**Comment by piotrekkaminski** [comment]
Closing in favor of PR #3746
