### ISSUE TITLE
Error for search phrase "0"

### ISSUE THREAD

**Issue by adrok** [magento/magento2#3738]
## Steps to reproduce
1. Install Magento 2.0.2
2. Search query "0" 
3. Error: Query quick_search_container does not exist

Example: http://magento2demo.firebearstudio.com/catalogsearch/result/?q=0

Solution:

File `vendor/magento/module-catalog-search/Model/ResourceModel/Fulltext/Collection.php`

replace
`if ($this->queryText) {`
to
`if ($this->queryText !== false) {`

**Comment by choukalos** [comment]
@adrok - could you submit a PR?

**Comment by adrok** [comment]
@rafaelstz already submit PR https://github.com/magento/magento2/pull/3741/commits/f605e2de19f5cd59c7532c07baf4fe756af1395e

**Comment by piotrekkaminski** [comment]
No longer reproducible on 2.1rc
