### ISSUE TITLE
Update symfony/console 

### ISSUE THREAD

**Issue by smiroshnyk** [magento/magento2#37386]
### Summary

It became a problem that Magento 2.4.6 requires a version of the Symfony console module ~4.4

### Examples

Hello.
It became a problem that Magento 2.4.6 requires a version of the Symfony console module ~4.4 because we can't even use the latest version of GrumPHP for Example to validate our code because it requires the symfony/console module at least 5.4.
Best regards,
Stanislav Miroshnyk.

### Proposed solution

Update symfony/console to the latest version.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @smiroshnyk,

Thanks for the report and collaboration!

As we can check in the https://github.com/phpro/grumphp/ repo they are using  `"symfony/console": "~5.4 || ~6.0"`:

https://github.com/phpro/grumphp/blob/d600fc641d23f966d525329a7d768a67328e6eda/composer.json#L31

And in Magento, we are using  `"symfony/console": "^5.4"`:

https://github.com/magento/magento2/blob/e6e2dc364b85892c6560347e75ecf8beee3d0e6b/composer.json#L84

It should work for you. Please let us know in case of any query.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @smiroshnyk,

Thanks for the update! We are closing this issue.
