### ISSUE TITLE
Wrong order amount on backend dashboard on Last orders total value

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#37389]
### Preconditions and environment

- Magento ver. 2.4.5-p1

### Steps to reproduce

1. Create Tax zone and rule, I created with Singapore tax 8 %
2. Create order with Singapore country
3. in Backend Dashboard showing the wrong total it's not included Tax and shipping price
![image](https://user-images.githubusercontent.com/50168477/232674714-d5174d52-7b8f-4190-b273-d4d5455dd440.png)
![image](https://user-images.githubusercontent.com/50168477/232674799-36b5610e-2ba7-4a78-8924-b25e4618ced5.png)
![image](https://user-images.githubusercontent.com/50168477/232674834-1fe1a46f-4e41-4f74-a050-ec40ad28a75b.png)

### Expected result

Need to show the order total like on the Order page,
![image](https://user-images.githubusercontent.com/50168477/232674913-c5479f52-9575-454a-b5b6-0ad0d0e569ff.png)
![image](https://user-images.githubusercontent.com/50168477/232674936-4145290f-6141-461a-ac27-1855378c0932.png)

### Actual result

Currently wrong total showing
![image](https://user-images.githubusercontent.com/50168477/232674714-d5174d52-7b8f-4190-b273-d4d5455dd440.png)

### Additional information

Please let me know if need to add any setting, my sale tax setting already added below,
![image](https://user-images.githubusercontent.com/50168477/232675124-64647f74-49b2-4538-be1a-3a3d00bfff0e.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
@niku0911 @engcom-Bravo On the dashboard all totals (prices) are excl. VAT.

**Comment by niku0911** [comment]
ok, is there a setting to show with incl. GST?

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@Bashev Thanks for your contribution & collaboration over here.
Hi @niku0911,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1351" alt="Screenshot 2023-04-18 at 6 25 15 PM" src="https://user-images.githubusercontent.com/51680745/232784477-d42dc5bf-4fb2-4a29-856d-03e954ad31ba.png">



In Admin dashboard it will shows us totals without tax(excluding tax).We have separate column for tax where we can find entire tax amount for the orders.

Kindly let us know if you are still facing any issue.

Thanks.

**Comment by niku0911** [comment]
Hi @engcom-Bravo

**Comment by niku0911** [comment]
hi @engcom-Bravo 

can we show the last order including tax?
![image](https://user-images.githubusercontent.com/50168477/232951472-323bb67c-c07a-495f-91bb-d3ab95c56c4b.png)
