### ISSUE TITLE
Space in editorconfig syntax breaks rule for [{composer,auth}.json]

### ISSUE THREAD

**Issue by GrimLink** [magento/magento2#37394]
### Preconditions and environment

- Magento version any version after commit -> https://github.com/magento/magento2/commit/c722790487631c0ce78d753d2dfe9d97c7606a18
- Anything else that would help a developer reproduce the bug, simple test the editorconfig in your IDEA or code editor that support the editorconfig

### Steps to reproduce

1. Open your editor, that supports the editorconfig.
2. View the composer or auth json file
3. See what the indent is for the composer and auth.json
4. See that configured size is now 2 instead of 4
5. Remove the space in the editorconfig for `[{composer, auth}.json]` to `[{composer,auth}.json]`
6. See that configured size is now 4 as intended

### Expected result

The composer and auth should have a indent of 4 spaces

### Actual result

It only has 2 spaces

### Release note

Fix syntax error in editorconfig

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @GrimLink ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance and is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/233540971-fb8de4b7-09bb-4463-b065-25c0aeab3d8f.png)

**Comment by fredden** [comment]
@engcom-November Please can you check again. The bug isn't that `composer.json` is misconfigured, but that `auth.json` is misconfigured.

I have tested this with the following script:

```sh
cd $(mktemp -d)
for f in auth.json " auth.json" composer.json other.json
do
  printf '{\n "test": true\n}\n' > "$f"
done
wget https://raw.githubusercontent.com/magento/magento2/af9ab2034450ca8fe403b4a759a75b675e1d9cd4/.editorconfig
docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker
```

![Screenshot_2023-04-21_10-09-38](https://user-images.githubusercontent.com/334786/233596246-266fc823-a127-4a99-a291-f2d9a267f691.png)

Note that the file `auth.json` is currently requires (a multiple of) two spaces and ` auth.json` requires (a multiple of four spaces).

**Comment by GrimLink** [comment]
@engcom-November this ticket is not created for the 2 files that are misconfigured but that the editorconfig does not work for both, and should.
This ticket and the PR will fix this issue.

**Comment by engcom-November** [comment]
Thank you for the response @GrimLink .
Re verified the issue again on Magento 2.4-develop instance and we are confirming this issue to fix the syntax error in .editorconfig file
