### ISSUE TITLE
getStoreId mutation in backend context

### ISSUE THREAD

**Issue by DnD-Nibra** [magento/magento2#37397]
Hello here!

In case of custom export of the customer datas into a multistore context, we have a troubleshooting with the store ID : the function `getStoreId()` usage don't return the customer **store_id**, data stored into the database, but calculate the default **store_id** based on the registering website

During my analysis, I have found a ten years old developement that cause this behavior :

[https://github.com/magento/magento2/blob/af9ab2034450ca8fe403b4a759a75b675e1d9cd4/app/code/Magento/Customer/Model/Backend/Customer.php#L15](https://github.com/magento/magento2/blob/af9ab2034450ca8fe403b4a759a75b675e1d9cd4/app/code/Magento/Customer/Model/Backend/Customer.php#L15)

So, what the cause of this behavior in the backend context? Is there a way to retrieve the correct data without usage of a `getData(CustomerInterface::STORE_ID)` or another emulation? Shouldn't this behavior ultimately be changed?

Regards

**Comment by baiciluigi** [comment]
Why does this class even need to exist? It's causing issues for us aswell

**Comment by engcom-Hotel** [comment]
Hello @DnD-Nibra,

Thank you for your report.

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results
- Screenshots if possible

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Dnd-Nibra,

We have noticed that this issue has not been updated for a period of a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
