### ISSUE TITLE
Bug with calculate changed config's which obscured

### ISSUE THREAD

**Issue by DmitrySamushchenko** [magento/magento2#37392]
### Preconditions and environment

Magento 2.4.6 EE.
Enabled module Magento_TwoFactorAuth.

### Steps to reproduce

1. Go to Admin Panel -> Stores -> Configuration -> Security -> Google reCPATCHA Admin Panel.
2. Write any text at "Google API Secret Key" and Save Config.
3. Create observer after save config:

```
<event name="admin_system_config_changed_section_recaptcha_backend">
        <observer ..../>
</event>
```

4. In observer class get changed paths by following code and write it to logs:
```
$observer->getEvent()->getData('changed_paths');
```

6. In admin panel re-save config without any changes.

### Expected result

At logs must be no changed paths's, because setting ""Google API Secret Key" was not changed.

### Actual result

At logs we see that changed path is "Google API Secret Key"

### Additional information

This happens because in the `\Magento\Config\Model\Config::isValueChanged` method there is no check for an obscure value, which, if the value has not changed, then '******' is returned and compared with the base config where it is located true value

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @DmitrySamushchenko,

Thank you for the report and collaboration!

We tried to reproduce this on 2.4-develop, but we are not able to get the Actual result.
We have followed the steps and got the below log:
<img width="507" alt="image" src="https://github.com/magento/magento2/assets/60198231/a0c3d010-4c00-4bbd-9119-49a3f473fa43">
Here we are not seeing any changed "Google API Secret Key".

Please find the custom module used to reproduce this issue, and let us know if we are missing anything.
[CapVendor.zip](https://github.com/magento/magento2/files/13278517/CapVendor.zip)

Thank you.

**Comment by engcom-November** [comment]
Hello @DmitrySamushchenko,

We have noticed that this issue has not been updated for along time. Hence we assume that this issue is fixed now, so we are closing it. Feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thank you.
