### ISSUE TITLE
404 on Admin after Data Migration.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3739]
## Hello GitHub!

I have installed Magento 2 was working fine until after Data Migration.
http://transpartswarehouse.net/magento2
I suspect that the front end is working but that I need to get to admin panel to change the theme.

This is where the **problem** arises.
http://transpartswarehouse.net/magento2/transadmin
is always redirected to:
https://transpartswarehouse.net/magento2/index.php/transadmin (Secure)
and gives a 404 error page not found error.

I have read everything I could find about this problem but it seems most things pertain to Localhost issues, which I don't believe I would be having on this live site.

I have tried:
php magento setup:static-content:deploy
php magento setup:upgrade
php magento indexer:reindex
php magento cache:clean
php magento setup:di:compile

Any help would be much appreciated!

> 404 Not Found
> The server can not find the requested page:
> 
> transpartswarehouse.net/magento2/index.php/transadmin (port 443)
> Please forward this error screen to transpartswarehouse.net's WebMaster.
> 
> Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 Server at transpartswarehouse.net Port 443

**Comment by rafaelstz** [comment]
What data migration tool you use?

**Comment by bondimedical3** [comment]
It's a bug. Some variable in the database is made wrong whenever you migrate.

**Comment by ghost** [comment]
@rafaelstz I downloaded the tool via composer
@bondimedical3 I will try a fresh install?

**Comment by bondimedical3** [comment]
I did a fresh install

**Comment by katmoon** [comment]
Hi @wlaskowsky 

Thank you for reporting the issue.

Could you please provide more details on what you have changed and how you migrated data?
Did you modify any webserver settings? 
Which webserver do you use?

Please also check `web/../base_url`, `web/secure/..` settings in `core_config_data` table. What are the settings?
You may also check `url_rewrite` table. Is there anything that could be related to the issue?

Thanks,
Kateryna.

**Comment by piotrekkaminski** [comment]
@ilol can you look into it?

**Comment by vzabaznov** [comment]
Hi, @wlaskowsky thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please create new one with proper steps, Magento versions, etc..

**Comment by gtrocks** [comment]
Hi Everyone,

I have installed fresh magento 2.3.1 and its working fine . after data migration  now i am not able to login to my admin , it always showing 404 error 


i have updated  backend 'frontname' to check but still not get any success.

please someone help me to resolve this issue

**Comment by savan13** [comment]
Same facing issue in 2.4 Magento 2 version.
Showing this error [https://prnt.sc/24r4bh3]

**Comment by Kunal-stack** [comment]
Do you guys find any solution for the problem , we did a migration and facing the same issue
