### ISSUE TITLE
A dependence package version problem occurred during installation

### ISSUE THREAD

**Issue by sunpaolo** [magento/magento2#37408]
### Summary

  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.6 -> satisfiable by magento/product-community-edition[2.4.6].
    - magento/product-community-edition 2.4.6 requires magento/magento-composer-installer >=0.4.0 -> found magento/magento-composer-installer[dev-master, 0.4.0-beta1, 0.4.x-dev] but it does not match your minimum-stability.

### Examples

composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento

### Proposed solution

Does the repository need to update?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@sunpaolo: what versions do you get when you run this inside your project?
```
composer show magento/magento-composer-installer --available
```

At the moment of writing, I'm getting this list:
```
versions : dev-master, 0.4.x-dev, * 0.4.0, 0.4.0-beta2, 0.4.0-beta1, 0.3.0, 0.3.0-beta.1, 0.2.1, 0.2.1-beta1, 0.2.0, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
```

Version 0.4.0 is part of this list, so it should work.
But in your case it sounds like it can't find this version?

**Comment by sunpaolo** [comment]
I found the problem is that I changed the repository for speed up before 
```
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
```
but it doesn't seem to keep up to date
```
https://mirrors.aliyun.com/composer/p2/magento/magento-composer-installer.json
```
I have reset and use the default repo It works well. 
```
composer config -g --unset repos.packagist
```
Thanks

**Comment by wobstyr** [comment]
i get the same error 

if i run composer show magento/magento-composer-installer --available

versions : dev-master, 0.4.x-dev, 0.4.0-beta1, * 0.3.0, 0.3.0-beta.1, 0.2.1, 0.2.1-beta1, 0.2.0, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0

its using 0.3.0 not 0.4.0

how do i upgrade it?

**Comment by wobstyr** [comment]
thank you so much for coming back to me, i apologise for being so ignorant, but how do i do that?

**Comment by hostep** [comment]
Check the `composer.json` file of your project, the `repositories` section. In there, it should at least have this section:
```json
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
```

**Comment by wobstyr** [comment]
Thank you, unfortunately, it is there and is correct, exactly as your message, but i get this error. 

 Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.6 -> satisfiable by magento/product-community-edition[2.4.6].
    - magento/product-community-edition 2.4.6 requires magento/magento-composer-installer >=0.4.0 -> found magento/magento-composer-installer[0.4.0] but it conflicts with your root composer.json require (0.3.0).

do you know how i would upgrade just the magento-composer-installer to 0.4.0?

**Comment by wobstyr** [comment]
ok i did it 
i ran "composer require magento/magento-composer-installer" and it upgraded it.
