### ISSUE TITLE
Class 'ArrayObject' is restricted - Magento2.Legacy.RestrictedCode.ArrayObjectIsRestricted

### ISSUE THREAD

**Issue by webmaiatec** [magento/magento2#37410]
### Summary

Hello there,

I have a module that is getting rejected from marketplace due to coding standard issue.

The error is -Class 'ArrayObject' is restricted in /usr/share/eqp/PhpCodeSnifferTool/tmp/work/Model/.. .php. Suggested replacement: Custom class, extended from ArrayObject with overwritten serialize/unserialize methods

I have already created a custom class that extends ArrayObject & has overwritten the methods as suggested. But now it shows error in that file.

**Here is error report from Magento,**

```
{
       "message": "Class 'ArrayObject' is restricted in /usr/share/eqp/PhpCodeSnifferTool/tmp/work/Model/ExtendedArray.php. Suggested replacement: Custom class, extended from ArrayObject with overwritten serialize/unserialize methods",
       "source": "Magento2.Legacy.RestrictedCode.ArrayObjectIsRestricted",
       "severity": 10,
       "fixable": false,
       "type": "ERROR",
       "line": 5,
       "column": 5
},
{
      "message": "Class 'ArrayObject' is restricted in /usr/share/eqp/PhpCodeSnifferTool/tmp/work/Model/ExtendedArray.php. Suggested replacement: Custom class, extended from ArrayObject with overwritten serialize/unserialize methods",
      "source": "Magento2.Legacy.RestrictedCode.ArrayObjectIsRestricted",
      "severity": 10,
      "fixable": false,
      "type": "ERROR",
      "line": 12,
      "column": 29
}
```
Is there any mistake in my code? Or Is there problem in module verification tool?

### Examples

**The code is as below**

```php
namespace Namespace\Modulename\Model;

use ArrayObject;

/**
 * This class allows objects to work as arrays.
 *
 * @author Namespace
 */
class ExtendedArray extends ArrayObject
{
    public function serialize()
    {
        return parent::serialize();
    }

    public function unserialize($data)
    {
        return parent::unserialize($data);
    }
}
``` 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by webmaiatec** [comment]
Hello there,

This issue is still there. Our module is getting rejected on Marketplace due to this issue. Can anyone please help with this?

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @webmaiatec,

We are using this board to address the bugs you are facing in the Magento core library. But it doesn’t seem the same for us. We request you to please go through with the below ticket and also you can submit a ticket there, if required:

https://marketplacesupport.magento.com/hc/en-us

Thanks
