### ISSUE TITLE
sampledata:reset has no effect since Magento 2.3.0

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#37425]
### Preconditions and environment

With Magento 2.3.0, the sample data modules were changed to work with data patches instead of legacy data upgrade scripts. But the reset command still assumes a `data_version` of the module which is not used anymore:

```
            foreach (array_keys($sampleDataPackages) as $name) {
                $moduleName = $this->packageInfo->getModuleName($name);
                if ($moduleName !== null) {
                    $this->moduleResource->setDataVersion($moduleName, '');
                }
            }
```

To reproduce in any version up to Magento 2.4.6:

### Steps to reproduce

- run `bin/magento sampledata:deploy`
- delete all products
- run `bin/magento sampledata:reset`
- run  `bin/magento setup:upgrade`

### Expected result

After `sampledata:reset`
 - patches from sample data modules are removed from `patch_list`  database table

After `setup:upgrade`
- products are recreated again

### Actual result

no change

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @schmengler,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by schmengler** [comment]
@engcom-Dash I cannot read the error message in your screenshot

**Comment by schmengler** [comment]
@engcom-Dash @engcom-Bravo But even if you follow the steps only until `run bin/magento sampledata:reset`, you will be able to verify the issue:

> ### Expected result
> 
> After `sampledata:reset`
> - patches from sample data modules are removed from `patch_list`  database table

Please reopen

**Comment by schmengler** [comment]
@engcom-Bravo @engcom-Dash the issue has not been updated for a period of 14 days :wink: 

Hence I created a new ticket at #37651
