### ISSUE TITLE
unable to opt different nav types for gallery and fullscreen views in mobile device

### ISSUE THREAD

**Issue by balachandramoui** [magento/magento2#37438]
### Preconditions and environment

- Magento version 2
- code is from view.xml file

### Steps to reproduce

<var name="breakpoints">
            <var name="mobile">
                <var name="conditions">
                    <var name="max-width">767px</var>
                </var>
                <var name="options">
                    <var name="options">
                        <var name="navdir">horizontal</var> 
                        <var name="nav">dots</var> 
                        <var name="fullscreen">
                            <var name="nav">thumbs</var>
                        </var>
                    </var>
                </var>
            </var>
        </var>

### Expected result

need to show dots on gallery view and thumbs on fullscreen for mobile device

### Actual result

when trying to opt 2 different nav types for gallery and fullscreen only nav type applied for gallery was reflecting in the mobile device.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @balachandramoui ,

Kindly provide some more information about steps to reproduces, its very useful to proceed further to reproduce the issue.

Let us know if we are missing 

Thanks!

**Comment by engcom-Dash** [comment]
Hi @balachandramoui ,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
