### ISSUE TITLE
checkout is not working

### ISSUE THREAD

**Issue by vipin12117** [magento/magento2#3743]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add Product to the cart.
3. go to checkout page - it show blank page

TypeError: window.checkout is undefined
autocomplete: window.checkout.autocomplete,

**Comment by mazhalai** [comment]
@vipin12117 can you please clean cache(magento + browser) and try again?

**Comment by stevenocta** [comment]
Hi, 
I can confirm that the error can be reproduced with Composer-based installation (Magento and Sample Data installation). 

I have cleaned up both my browser and Magento cache, they have no effect on the issue.

**Comment by piotrekkaminski** [comment]
We are not able to reproduce this issue. If you still experience it in 2.1rc, please provide more details (php version, how the environment is setup) and create a new ticket.

**Comment by muneeb456** [comment]
I've encountered the same issue on a fresh installation of community edition 2.1.2 on WAMP (Windows 10, Apache 2.4.9, MySQL 5.6.17, PHP 5.6.27). Any fixes?

**Comment by shaw-tech** [comment]
Hi,

I am encountering this issue while on the multiaddress checkout - on the billing step.

Could you advise on a resolution?

**Comment by msliman** [comment]
@shaw-tech I am facing the same problem. Do you have a solution ?

**Comment by titechnologies** [comment]
Got the same issue.
Solved by...
Update to latest version 2.1.7
Set intl.error_level to 0 in php.ini file.
