### ISSUE TITLE
[Performance] DeploymentConfig - reloadData / flattenParams

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37435]
### Preconditions and environment

- Magento version 2.4.6

### Steps to reproduce

1. Profile a frontend product page loading.

### Expected result

DeploymentConfig is only loaded once

### Actual result

Multiple call to `DeploymentConfig::reloadData`

### Additional information

![Capture d’écran 2023-04-26 à 11 47 12](https://user-images.githubusercontent.com/1633463/234538809-f828855b-59c4-4ec7-a866-f2b0a0cdb464.png)

I'm not sure to fully understand how DeploymentConfig class is working, so maybe I'm wrong and those 266 calls to `DeploymentConfig::reloadData()` are needed. In that case, we should try to optimize flattenParams which is the time consuming method here.

But if I understand it correctly, there is no reason to load that config multiple times for a single request (even if some config path is null).
In that case, I'm not sure what the best fix is, but I'm sure fixing it would improve significantly frontend pages.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment]
Note : It seems that adding 
```
    'static_content_on_demand_in_production' => 0,
    'force_html_minification' => 0,
```
to my env.php fixed the symptom. Hope it can helps those who have the same issue. However, the issue is still valid and should still be fixed.

**Comment by lykhachov** [comment]
The issue basically goes from here `vendor/magento/framework/App/DeploymentConfig.php:87`, just check what configs are missing and as a result cause to reloadData(). Adding missing configs fixed performance issue instantly

**Comment by Nuranto** [comment]
Yes, that what I figured out in my previous comment.

However, imho that is still a bug. I find it out because I was seeking for performance improvements, but I guess a lot of merchants have this problem without knowing it.
Either the required config should be mandatory (cannot run Magento without it configured) or non-vital config like those two should have a default value. (or the PR should be applied.)

Note that this intempestive reload of config has only been added for testing purposes (see PR comments).

**Comment by onlinebizsoft** [comment]
@Nuranto is the issue also happening with older versions?

**Comment by Nuranto** [comment]
@onlinebizsoft I don't know, I only tested this on 2.4.6

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Request you to please looked into this comment https://github.com/magento/magento2/pull/37436#issuecomment-1592750163

Thanks

**Comment by Nuranto** [comment]
I cannot spend more time on working hours on this, since we got a fix.
But I will check this on my free time ASAP.
