### ISSUE TITLE
Gallery jason parse error after extends

### ISSUE THREAD

**Issue by shinethazhava** [magento/magento2#3744]
When i extend Magento/Catalog/Block/product/view/gallery to my custom module then i getting jason parse error with out override any methods .

**Comment by voleye** [comment]
Hi @shinethazhava, thank you for your request!

Could you please provide the source code of class that extends "Magento/Catalog/Block/Product/View/Gallery"?

**Comment by shinethazhava** [comment]
Thanks for the update.
I just extend gallery class to my custom class i didn't override any methods. first i get template not found error when i copy gallery.phtml to my custom module then error disappear. but got new jason parse error no console. 
`<preference for="Magento\Catalog\Block\Product\View\Gallery" type="Egits\ProductGallery\Block\Product\View\Gallery" />` 

When i call parent constructor in extend class going to not found error page 

`<?php

namespace Egits\ProductGallery\Block\Product\View;

class Gallery extends \Magento\Catalog\Block\Product\View\Gallery
{

}`

**Comment by voleye** [comment]
Hi, @shinethazhava 

I have tried to implement something similar to identify the problem but can not reproduce the issue.
I have created a patch, could you please review and clarify additional conditions I missed? Or may be this patch will solve your issue.

[Egits.zip](https://github.com/magento/magento2/files/189559/Egits.zip)

**Comment by shinethazhava** [comment]
Hi, @voleye 
Thanks for the quick response. Will let you know any issue occur.

**Comment by shinethazhava** [comment]
Hi @voleye 
When i try your patch file also getting the same error.

**Comment by piotrekkaminski** [comment]
@shinethazhava please provide more detailed steps to reproduce. Please see if you still have this issues in 2.1rc.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
