### ISSUE TITLE
Magento2.4. is lacking compatibility with elasticsearch8.8 and opensearch2.x 

### ISSUE THREAD

**Issue by elizad** [magento/magento2#37445]
### Summary

Let me know when the issues are solved
PHP 8.2 compatibility
Elasticsearch 8 compatibility
Opensearch 2.6 compatibility

### Examples

Module 'Temando_ShippingRemover':
[Progress: 662 / 1331]
[Progress: 663 / 1331]
Installing search configuration...

In SearchConfig.php line 81:

  Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

..............................................................
Module 'Temando_ShippingRemover':
[Progress: 662 / 1331]
[Progress: 663 / 1331]
Installing search configuration...

In SearchConfig.php line 81:

  Could not validate a connection to the OpenSearch. No alive nodes found in your cluster

...........................

bin/magento config:set catalog/search/engine 'opensearch'
Missing required argument $engines of Magento\Search\Model\EngineResolver.

bin/magento config:set catalog/search/engine 'opensearch'
Missing required argument $engines of Magento\Search\Model\EngineResolver.
 opensearch.service - OpenSearch
     Loaded: loaded (/usr/lib/systemd/system/opensearch.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2023-04-28 15:08:10 UTC; 13s ago
       Docs: https://opensearch.org/
   Main PID: 1464917 (java)
      Tasks: 96 (limit: 203884)
     Memory: 1.3G
        CPU: 22.607s
     CGroup: /system.slice/opensearch.service
             └─1464917 /usr/share/opensearch/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 ->

......

Same for elasticsearc8 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
For ES8 you need to prep some stuff, like installing a new composer package first: https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch

For Opensearch 2.x, the [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) claim Magento 2.4.6 should work with Opensearch 2.5, I haven't tried this myself yet, but I would assume the documentation is correct...

**Comment by mcarbs** [comment]
@hostep I just checked and the default installation of opensearch 2.5.0 doesn't work as per the documentation, opensearch-security plugin needs to be removed otherwise installation fails.

**Comment by engcom-November** [comment]
Hello @elizad,
Thank you for the report and collaboration!
Thank you @mcarbs for the inputs!

In our case opensearch 2.x is working fine, currently we are using 2.11.0 and it is working without any problems.
Please let us know for which version of opensearch are you getting this issue, and also mention any third party modules if you are getting this issue in.

Thank you.

**Comment by engcom-November** [comment]
Hello @elizad,

We have noticed that this issue has not been updated for along time. Hence we assume that this issue is fixed now, so we are closing it. Feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thank you.
