### ISSUE TITLE
Create Configure Product-> Create Configuration-> "Create Product Configurations" PopUp==> Spelling mistake word "unigue".

### ISSUE THREAD

**Issue by sachinkalerws** [magento/magento2#3745]
Create Configure Product-> Create Configuration-> "Create Product Configurations" PopUp==> Spelling mistake word "unigue".

![unigue](https://cloud.githubusercontent.com/assets/17641550/13722917/e08e91f0-e87a-11e5-9ce1-dab4eee2e644.jpg)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54363

**Comment by veloraven** [comment]
Wrong internal ticket is mentioned.

**Comment by veloraven** [comment]
@sachinkalerws thank you for your report.
Please, provide the used Magento version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
