### ISSUE TITLE
Shipping fee calculation error in the case of adding an item to the cart during the checkout process

### ISSUE THREAD

**Issue by weissye** [magento/magento2#37466]
### Preconditions and environment

- Magento version 2.4.x
- Docker Desktop version on 'localhost.' 
.

### Steps to reproduce

1. Open one window and log in as a user
2. Add at least one product to the cart in the first windows
3. Open the second window and log in as the same user
4. Add some products to the cart in both windows
5. start the checkout process in the second window and check the fixed shipping method and click the 'Next' button
6. In some cases, when adding another product, by 'Add to Cart' button to the cart. At the same time, the Magento-2 between 'Next' and 'Place Order,' the shipping fee is miscalculated, resulting in an unpredictable shipping fee. 

### Expected result

The shipping fee is the number of items in the cart multiplied by 5.

### Actual result

Unpredictable shipping fee.

### Additional information

This issue is difficult to reproduce. We run it in our automatic testing tool, Provengo, which runs many Selenium activities simultaneously. 
The issues occurred in about 5% of cases we ran the same described situation.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @weissye,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
