### ISSUE TITLE
Facing issues with category in magento 2.3.7-p4

### ISSUE THREAD

**Issue by nadirflow** [magento/magento2#37475]
### Summary

I am able to create categories and assign products to them but the real issue comes with category pages which gives 404, unable add them in menu and when I create custom CMS page to get products by category not getting any in that page and also unable select categories in URL rewrite section from admin panel.

### Examples

 I tried some URL rewrite modules through command I am able to rewrite products URL but for category it shows 0.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance
