### ISSUE TITLE
Phpunit bootstrap file not generating extensionattribute methods?

### ISSUE THREAD

**Issue by rutgerrademaker** [magento/magento2#37478]
### Preconditions and environment

N.B I am not sure if this is a bug, a missing feature, or that I'm just doing something wrong

I digged a little into \Magento\Framework\TestFramework\Unit\Autoloader\ExtensionAttributesInterfaceGenerator (which seems to generate the file), but I was not yet able to see where the methods should have been added

- Magento version: 2.4.5-p2 
- Phpunit  9.6.6

phpunit.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd"
         colors="true"
         columns="max"
         bootstrap="dev/tests/unit/framework/bootstrap.php">
    <coverage>
        <include>
            <directory suffix=".php">app/code/*</directory>
        </include>
        <exclude>
            <directory>app/code/*/*/Test</directory>
        </exclude>
    </coverage>
    <testsuites>
        <testsuite name="Magento_Unit_Tests_App_Code">
            <directory>app/code/*/*/Test/Unit</directory>
        </testsuite>
    </testsuites>
    <listeners>
        <listener class="Magento\Framework\TestFramework\Unit\Listener\ReplaceObjectManager"/>
    </listeners>
</phpunit>
```

### Steps to reproduce

Add an extension attribute to e.g Magento\Sales\Api\Data\Order

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Sales\Api\Data\OrderInterface">
        <attribute code="order_intake_reference" type="string"/>
    </extension_attributes>
</config>
```

Mock the interface in a unit test

Execute phpunit

### Expected result

file `/dev/tests/unit/tmp/generated/code/Magento/Sales/Api/Data/OrderExtensionInterface.php` will have getters and setters for all extension attributes

### Actual result

File is generated without , but without any methods

```php
<?php
namespace Magento\Sales\Api\Data;

interface OrderExtensionInterface extends \Magento\Framework\Api\ExtensionAttributesInterface
{


}
```

### Additional information

When running `bin/magento setup:di:compile` the `generated/code/Magento/Sales/Api/Data/OrderExtensionInterface.php` is created and lists all the methods just fine, and unit test execute as expected

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chernenm** [comment]
@magento give me 2.4.6 instance
