### ISSUE TITLE
Admin catalog image thumbnail 404

### ISSUE THREAD

**Issue by ghostofspider** [magento/magento2#3747]
## Steps to reproduce
1. Install Magento stabel 2.0.2 in subdomain
2. Configure varnish cache.
3. Re-index and refresh cache
4. Open Products -> Catalog

Expected result
1. View image normal in Products ->Catalog list

Actual result
1. Product list Thumbail image error 404 Not found! 
![01](https://cloud.githubusercontent.com/assets/6448909/13724152/56f768fe-e884-11e5-9cc6-51ca3754b484.jpg)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54363

**Comment by piotrekkaminski** [comment]
@ghostofspider i'm not able to reproduce it on 2.1rc. If you are still experiencing this issue, please open a new ticket with detailed reproduction steps.
