### ISSUE TITLE
Pulling Magento 2 OpenAPI spec version 2.4.6 seems to contain an error

### ISSUE THREAD

**Issue by SwissMaWi** [magento/magento2#37480]
### Preconditions and environment

- 2.4.6
- OpenAPI Spec available at https://developer.adobe.com/commerce/webapi/rest/quick-reference/

### Steps to reproduce

Open the swagger.json with Swagger Online Editor

### Expected result

no errors

### Actual result

Error with a request body under a delete request

![image](https://github.com/magento/magento2/assets/46742945/7a378182-e64e-4d64-be4e-3a6978d5e99b)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @SwissMaWi ,


Verified the issue with 2.4.6 instance and issue can be reproducible,Hence we are confirming the issue.

**Preconditions :**
Magento version 2.4.6
PHP 8.1

**Steps to reproduce:**
1.Import the openAPI Specification Json [file](https://developer.adobe.com/commerce/webapi/rest/quick-reference/) for 2.4.6 in swagger editor

**Kindly Refer the below screenshots:**
<img width="1511" alt="Screenshot 2023-05-11 at 2 17 00 AM" src="https://github.com/magento/magento2/assets/60198592/0e94a8e1-0e40-4de1-9d69-f95dd71f62ac">

We are also getting actual result as per the description which is Error with a request body under a delete request.Hence we are confirming the issue


Regards,

**Comment by chernenm** [comment]
@magento give me 2.4.6 instance with edition ee

**Comment by engcom-Dash** [comment]
Hi @SwissMaWi ,

We had Internal discussion with team,Hence this issue is not related to any Magento core library and this is not the correct platform for this.So,Kindly create an issue with below repo, Hence we are closing the issue here.
https://github.com/AdobeDocs/commerce-webapi

Let us know if we are missing anything!

Regards,
