### ISSUE TITLE
Magento 2.4.6 AWS Opensearch 1.2. No Alive nodes found.

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [magento/magento2#37490]
### Preconditions and environment

- Magento 2.4.6
- AWS OpenSearch Domain 1.2

### Steps to reproduce

1. Clone version 2.4.6
2. Configure opensearch in env.php
3. Run `php bin/magento setup:install` or `php bin/magento setup:upgrade`
4. Then the error happens when it checks Opensearch

### Expected result

Magento should be able to configure the domain and use it

### Actual result

Error code displayed:
![image](https://github.com/magento/magento2/assets/45077772/6b9c5c1a-5eff-44ae-9031-f7b0e2ed8416)

### Additional information

My env.php Opensearch configuration:
![s](https://github.com/magento/magento2/assets/45077772/2bb5bbad-c3c9-4bac-921f-9e7a0b66236b)

Same machine using curl to check cluster health, everything seems ok:
![image](https://github.com/magento/magento2/assets/45077772/2857889a-ef3c-4ae2-aec4-f0b6f9f144c5)

Opensearch general information:
![image](https://github.com/magento/magento2/assets/45077772/27a8ca32-dce5-489d-b49c-2f617d77c87c)

Opensearch security config:
![image](https://github.com/magento/magento2/assets/45077772/b34791d4-df90-437f-9763-79ab5d837ba9)

Opensearch access policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:eu-west-3:<MY_ACC>:domain/magento-opensearch-dev/*"
    }
  ]
}
```

My Cluster Config:
![image](https://github.com/magento/magento2/assets/45077772/4ada2d96-eb40-4c8f-882b-d641f815f03d)
![image](https://github.com/magento/magento2/assets/45077772/b3c0ccc9-f4a8-47a6-b770-68a0234307c7)

AWS Setup:
```
VPC
|- Opensearch in private subnet
|- EC2 instance with magento in private subnet
```

AWS Support when I asked for help regarding this:
```
Warm Greetings from AWS Premium Support. Thank you for reaching out to me with your concern. My name is Risha and I will be assisting you with the case today.

From the case notes, I understand that you are getting the error "could not validate a connection in Opensearch. No alive nodes found in your cluster". 

Kindly note that I checked the cluster heath and it is "Green" and it have never been yellow or red. I observed the last 3 days Clouldwatch metrics. 

Please find below the output of "GET /_cluster/health". 
-----------------
{
    "cluster_name": "<MY_ACC>:magento-opensearch-dev",
    "status": "green",
    "timed_out": false,
    "number_of_nodes": 1,
    "number_of_data_nodes": 1,
    "discovered_master": true,
    "active_primary_shards": 1,
    "active_shards": 1,
    "relocating_shards": 0,
    "initializing_shards": 0,
    "unassigned_shards": 0,
    "delayed_unassigned_shards": 0,
    "number_of_pending_tasks": 0,
    "number_of_in_flight_fetch": 0,
    "task_max_waiting_in_queue_millis": 0,
    "active_shards_percent_as_number": 100
}
----------------

Further, I checked CPUUtilization and JVMMemoryPressure and I confirm that all the metrics are within threshold.

I also observed the nodes metric and I understand that you had 2 nodes previously, then you enabled master nodes at around 2023-05-09 20:50 UTC for 20 mins then at around 2023-05-10 10:05 UTC you have decreased one more node. At present, you have only 1 node in the cluster. 

At present, the cluster seems in a good state as of now and their is no such abnormal activities in the cluster. I also observed that your cluster is within a VPC, therefore it is possible this error would be happened on your client side or client machine due to the network limit/throttle from your client to our opensearch cluster. Since I checked your Opensearch cluster, there is no abnormal activity in the last 3 day and the cluster is in active state.

I kindly suggest you to check your client side. I hope the above assistance is helpful to you. However, if you have any other query/concern, kindly write back to me and I would be more than happy to assist you further. 

Thank you and have a nice day ahead. 
Stay safe!

We value your feedback. Please share your experience by rating this and other correspondences in the AWS Support Center. You can rate a correspondence by selecting the stars in the top right corner of the correspondence.
```

Already tried having them both on the same subnet but didn't change anything

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DEADSEC-SECURITY** [comment]
As of today 2.4-develop doesnt work too and throws the same bug

**Comment by DEADSEC-SECURITY** [comment]
Also in the SG of the Domain I tried allowing all traffic from the Instances but still same error.

**Comment by DEADSEC-SECURITY** [comment]
Tried upgrading opensearch to version 1.3 but still the same error.
```
{
  "name" : "2e3fa858fc38031da251be7d3fb8e4f2",
  "cluster_name" : "<MY_ACC>:magento-opensearch-dev",
  "cluster_uuid" : "WwEmAzkQRSCA9T0IWtYXAg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.3.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-03-22T11:53:34.141437Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by DEADSEC-SECURITY** [comment]
After investigating this issue myself, I think I ended up finding a different error related to opensearch, which is when I save the config to the env file and run install it doesn't seem to be pick up the correct hostname from the env.php file but when I run the install command with the --opensearch-host and --opensearch-port params it manages to retrieve them fine afterwards when I run upgrade for example.

Running setup:upgrade with out installing with params:
![image](https://github.com/magento/magento2/assets/45077772/10abb658-ff60-4bae-bd74-f789c40816c4)

Running it after running install with params:
![image](https://github.com/magento/magento2/assets/45077772/5a2321b0-7e10-4989-9efc-94f89a72b919)

I still have to double check this is a bug but from it looks like current it might be a bug related to my initial issue.

**Comment by DEADSEC-SECURITY** [comment]
Final thoughts on this. I managed to "fix" the issue, well its more of an workaround then a fix, but could be easily fixed in source.

So what I found out from debugging is that the function `buildOSConfig` seems to be the one that build the hostname that magento will use.
This function has 2 main issues that I noticed:

1. Like my comment before this one, the function isn't getting the information from env.php nor did the setup:install save the opensearch values to env.php
2. When I select port 443 its not defaulting to https which is weird cuz port 443 is a https standard as well as port 80 for http. By default the function if it detects one of these ports and no schema in endpoint is provided it should select the correct schema.

Solutions:

1. Make function load from env.php (I'm not exactly sure how to do this)
2. Make function, if schema not provided in hostname, if the port is 443 then default to https. OR add a new param just for selecting the schema.

Also in solution 2 I point out adding a new param for schema because the docs are a bit missleading in the sense that when we say `host` and in the description we say `host or ip` and have as example just `localhost` its intended to not include any accessories and just the raw host which could cause confusion and in case of AWS with https enabled could cause unexpected errors.
![image](https://github.com/magento/magento2/assets/45077772/ac9ff7e6-012f-429a-b350-0d2e84a10e41)

I'm probably going to open a PR for solution 2 but I would need further assitance for 1 cuz I'm not a php dev and I'm not exactly sure how to solve  it.

**Comment by DEADSEC-SECURITY** [comment]
After further digging the way to give opensearch params in env is using the system path:
```
'system' => [
        'default' => [
            'catalog' => [
                'search' => [
                    'opensearch_server_hostname' => 'https://{REPLACE_OPENSEARCH_HOSTNAME}',
                    'opensearch_server_port' => '443',
                    'opensearch_server_timeout' => '15'
                ]
            ]
        ]
    ]
```
Anyway I still think my PR is useful in mitigating the confusion I had and adding a different option for schema wouldn't be a bad idea for the reasons I refered above.

**Comment by engcom-Hotel** [comment]
Hello @DEADSEC-SECURITY,

Thanks for the detailed explanation of the issue you are facing!

We have tried to reproduce the issue with the AWS OpenSearch service and the 2.4-develop branch of Magento, but it seems we are not getting the exact error that you are facing.

We are getting the below error:

`Could not validate a connection to the OpenSearch. Unknown 400 error from OpenSearch null`

Please have a look at the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/b532f83e-00df-4567-ab07-035fcbfe3964)

And also we have tried to implement the PR changes as well, but no luck. We are getting the below error:

`Could not validate a connection to the OpenSearch. Unknown 403 error from OpenSearch null`

Please let us know if we have missed anything, in order to reproduce the issue.

Thanks
