### ISSUE TITLE
 Cart price rules - Incorrect discount amount when using fixed discount amount for whole cart

### ISSUE THREAD

**Issue by vandersonramoslybe** [magento/magento2#37496]
### Preconditions and environment

- Magento version: 2.3.*, 2.4.*

### Steps to reproduce

Create a Cart price rule:

1 - Marketing -> Promotions -> Cart Price Rules

Conditions:

![Screenshot 2023-05-12 at 15 11 48](https://github.com/magento/magento2/assets/126778703/45af7381-d7dd-4d3e-acc2-a5fa5abd057b)

2 - Actions:

![Screenshot 2023-05-12 at 15 13 27](https://github.com/magento/magento2/assets/126778703/c937e82a-97cc-4d9b-8687-de69a4343eed)

It is important to be: **Fixed amount discount for whole cart**

3 - Create a plugin **afterGetPrice** for the class **Magento\Quote\Model\Quote\Item**. method **getPrice()**

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <type name="Magento\Quote\Model\Quote\Item">
        <plugin name="my_plugin_name" type="Vendor\Module\Plugin\GetPriceFromQuoteItemPlugin" />
    </type>

</config>

EXAMPLE:

`<?php

declare(strict_types=1);

namespace Vendor\Module\Plugin;

use Magento\Quote\Model\Quote\Item as QuoteItem;

class GetPriceFromQuoteItemPlugin
{

    public function afterGetPrice(QuoteItem $subject, $result): float
    {
        // ADD THE CHANGES HERE....
        
        $result = 1070.0;

        return $result;
    }
}`

Choose a configurable product, and add it to the cart. The price will be changed to the new one, after that, apply the coupon code:

![Screenshot 2023-05-12 at 14 30 02](https://github.com/magento/magento2/assets/126778703/9a492ad5-2fa4-4c64-bd95-9b02e2ec2fb1)

Check the discount value. 

### Expected result

It should be 500.00, not 250.00

### Actual result

It is 250.00

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Chris-Kiddier** [comment]
Hi,

I've recently experience this problem after upgrading to 2.4.5. It only happens when I try and apply a Fixed amount discount coupon to a quote with a configurable product in it. 
For example, a £5 discount will amount to a £2.50 discount when applied to the configurable product.

Considering it's exactly half, my first thought was that the discount is somehow applying to both the Parent and Child product, however, as only 1 of those is taken into account when calculating row totals, it only takes into account half the discount.


More evidence for that is from a self developed module that applies loyalty points to products. Only since 2.4.5 has it started applying double the amount to configurable products, as if there were two products in 1 row.


Maybe that will help, but I'll be keeping an eye on this issue as well!

**Comment by vandersonramoslybe** [comment]
> Hi,
> 
> I've recently experience this problem after upgrading to 2.4.5. It only happens when I try and apply a Fixed amount discount coupon to a quote with a configurable product in it. For example, a £5 discount will amount to a £2.50 discount when applied to the configurable product.
> 
> Considering it's exactly half, my first thought was that the discount is somehow applying to both the Parent and Child product, however, as only 1 of those is taken into account when calculating row totals, it only takes into account half the discount.
> 
> More evidence for that is from a self developed module that applies loyalty points to products. Only since 2.4.5 has it started applying double the amount to configurable products, as if there were two products in 1 row.
> 
> Maybe that will help, but I'll be keeping an eye on this issue as well!

I tested on Magento 2.3.7 as well, same behavior.

This is the class used when we have a cart rule as a Whole cart: https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php

 

The value on line 82 $baseRuleTotals = $ruleTotals['base_items_price'] ?? 0.0;  contains the price for 2 items instead of only one as expected.  For some reason, the method isChildrenCalculated from https://github.com/magento/magento2/blob/2.4.5-p2/app/code/Magento/SalesRule/Model/Validator.php is interfering with the calculation

**Comment by Chris-Kiddier** [comment]
I had a nosey through [Validator.php](https://github.com/magento/magento2/blob/2.4.5-p2/app/code/Magento/SalesRule/Model/Validator.php). I'm not sure what constitutes a child item as 'calculated' and considering how often that method is referenced I was hesitant to change anything.

However, I added an extra line to the if statement on line 464 of the Validator class (function initTotals()) and it seems to have fixed the issue for me, calculating the fixed amount discount correctly when I go to checkout.

```
if (!$this->isValidItemForRule($item, $rule)
    || ($item->getChildren() && $item->isChildrenCalculated())
    || $item->getNoDiscount()
    || ($item->getProductType() == "simple" && $item->getParentItemId() != null) // New line added
) {
    continue;
}
```

I figured, as the statement seems to be including Simple products that are also children, they should be omitted from the calculation. 
This is not elegant by any means (and involves editing core), but it has provided some functionality back to my dev site.

I'll await any further info, currently this is staying safely away from production

**Comment by engcom-Hotel** [comment]
Hello @vandersonramoslybe,

Thanks for the report and collaboration!

We have tried to reproduce the issue with the mentioned steps in the main description. We have used the 2.4-develop branch in order to reproduce the issue. But for us, the discount amount is showing $500. Please have a look to the below screenshot for reference:

<img width="1298" alt="image" src="https://github.com/magento/magento2/assets/51681618/7c57f127-0cab-455a-8b15-a90d71ffe98c">

Please review the steps and let us know if we need to do any additional steps in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Yes @vandersonramoslybe,

Let me attach the same here for reference:

[Magz.zip](https://github.com/magento/magento2/files/11562047/Magz.zip)

Please let me know if we missed anything.

Thanks

**Comment by vandersonramoslybe** [comment]
Hi @engcom-Hotel 

Thanks, I installed your plugin. I am running a vanilla Magento 2.4.6. The issue is reproducible with Configurable products.


![Screenshot 2023-05-25 at 09 24 59](https://github.com/magento/magento2/assets/126778703/0fa514b7-f0b1-4514-b7c7-82e0664d28fc)


![Screenshot 2023-05-25 at 09 29 25](https://github.com/magento/magento2/assets/126778703/41af691c-2983-4110-9b91-8f4828c79b38)


![test-Promotions-Marketing-Magento-Admin](https://github.com/magento/magento2/assets/126778703/b6a8c43c-9634-454f-b7f2-1ff74643b760)


![Screenshot 2023-05-25 at 09 28 25](https://github.com/magento/magento2/assets/126778703/7e863939-a09e-4478-bb88-a834ed2fea43)


![Screenshot 2023-05-25 at 09 28 38](https://github.com/magento/magento2/assets/126778703/a39173c2-4540-4760-98d1-39e13d64bba8)



![Screenshot 2023-05-25 at 09 28 52](https://github.com/magento/magento2/assets/126778703/b80590fc-a25e-4d9c-9d2b-09c9100d0707)

**Comment by engcom-Hotel** [comment]
Hello @vandersonramoslybe,

Thanks for the response!

Now we are able to reproduce the issue. Please refer to the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/4961aa84-69e5-47bf-9e5c-ade94f2555c4)

Hence confirming the issue.

Thanks

**Comment by aasim110** [comment]
@magento I'm working on this
