### ISSUE TITLE
main.CRITICAL: PayPal NVP gateway errors: This transaction couldn't be completed. Please redirect your customer to PayPal (#10486: This transaction couldn't be completed)

### ISSUE THREAD

**Issue by mahmoud-abdelmalek** [magento/magento2#37495]
### Preconditions and environment

- Magento version: 2.4.4
- Trying to pay through Paypal Express Using a bad funding source doesn't redirect the customer to PayPal

### Steps to reproduce

1. Login
2. Add Products to the Cart (With Skip Review Step Enabled)
3. Checkout through Paypal Express
4. Add bad funding source on Paypal ( Ex. transaction exceeded the buyer's card limit/balance )
5. Press Confirm
6. Can't Place Order Error arises and system.log (main.CRITICAL: PayPal NVP gateway errors: This transaction couldn't be completed. Please redirect your customer to PayPal (#10486: This transaction couldn't be completed))

### Expected result

Send the customer to the PayPal page to select an alternate funding source or add a new funding source, this eliminates the need to perform another SetExpressCheckout call that reinitiates the entire transaction flow. It also helps the buyer to complete the transaction (instead of getting stuck in an endless checkout loop).

### Actual result

2.4-develop instance behavior: Page load is stuck and user is not able to perform any other operation.
2.4.4 behavior: Redirected back to Magento without asking the customer to use an alternate funding source

### Additional information

I strongly suspect that Magento 2 (as of 2.4.4) is missing the redirection that must be done on PayPal error 10486, during normal checkout and with "skip payment review" enabled. this is an error that usually originated in PayPal, due to some problem with the selected source of funds (although there are some other possible reasons...), and therefore it can be solved by the customer just by selecting another source of funds (therefore, we should really try to redirect).

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mahmoud-abdelmalek** [comment]
Unable to Reproduce the issue on the provided instance
Paypal Express needs Sandbox Credentials which I don't have at the moment and I believe this issue won't be produced on sandbox

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.
Issue: While making payment using PayPal Express checkout with buyer transaction limit exceeded, below error is displayed and page load is stuck and user is not able to perform any operation.
[2023-05-15T14:51:31.194431+00:00] main.CRITICAL: PayPal NVP gateway errors: The Buyer cannot pay with PayPal for this Transaction (#13113: Buyer Cannot Pay). Correlation ID: 8ba47a70a27ef. Version: 72.0. [] []
![image](https://github.com/magento/magento2/assets/60198231/1dfd0fca-367c-43ae-b5ed-afeddd541d3a)

**Comment by mahmoud-abdelmalek** [comment]
Check the comment from Mitxel who proposed adding a redirect 
https://magento.stackexchange.com/questions/69787/paypal-error-10486-redirected-back-to-magento-from-paypal

**Comment by roshanelate** [comment]
Is there any fix for it?

**Comment by simonrl** [comment]
Hi, does anyone have a link to PRs which fix this, and know which version this will be available in? Thanks

**Comment by dooblem** [comment]
There is no PR needed see the screencast. Paypal is proposing other payment methods, so no need of a fix in Magento. The error message will still be logged on Magento side though I think. (this is the case on our platform.)

**Comment by simonrl** [comment]
@dooblem Thanks, I can (somehow) confirm. The "transaction failed" emails are still sent, but the customers are able to continue their checkout.

**Comment by nrdevau** [comment]
Am I correct in summarising this issue as, "This is resolved, but the error will continue to log"?

I'm currently working through a bunch of payment gateway errors in the log and just wandering if this is noise or worth exploring further
