### ISSUE TITLE
Redis preloading fails when exec() returns false

### ISSUE THREAD

**Issue by LeanderFS** [magento/magento2#37509]
### Preconditions and environment

- Magento 2.x
- Redis 6.0.10 (Probably every version of Redis)
- phpredis

### Steps to reproduce

1. Install Magento 2 as normal
2. Enable Redis in env.php under cache->frontend->default
3. Make sure to set `backend` option to `Magento\\Framework\\Cache\\Backend\\Redis`
4. Set `id_prefix` and `preload_keys`
5. Run `bin/magento cache:clean`

This might not reproduce the issue in a lot of the cases because in normal scenarios there would be no issues. This issue arises as an edge-case when `\Magento\Framework\Cache\Backend\Redis::load` is being called. 
`$this->preloadedData = array_filter(array_combine($this->preloadKeys, $redis->exec()));` expects the second parameter of `array_combine` to be an array, but `$redis->exec()` can return `false` in some cases. Leading to an unexpected exception and inability to run `cache:clean` or similar commands that preload keys in Redis.

### Expected result

I expect the cache:clean command to finish without an error.

### Actual result

The following exception is thrown:
`array_combine(): Argument #2 ($values) must be of type array, bool given`

### Additional information

The issue is not immediately apparent, but makes more sense when you look into what the `\Cm_Cache_Backend_Redis` class is doing, which is the class the Magento Redis adapter extends from. The `Cm_Cache_Backend_Redis` class pipes the requested method through to `Credis_Client`, which in turn pipes the request to phpredis. The method signature for `exec()` in `Credis_Client` tells us that the return value will always be of the type `array`, but when checking the implementation in phpredis, `exec()` can return false. Causing the preloading in Magento to fail.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by LeanderFS** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @LeanderFS,

Thanks for the reporting and collaboration!

Just to confirm, you are mentioning `phpredis` below:

> but when checking the implementation in phpredis, `exec()` can return false. Causing the preloading in Magento to fail.

Are you talking about this repo https://github.com/phpredis/phpredis?

If yes, then we have gone through with the documentation of phpredis for the `exec` method and it is mentioned there that it can return `false`, please refer to the below screenshot for reference:

<img width="1107" alt="image" src="https://github.com/magento/magento2/assets/51681618/cde67328-c2cb-4ef6-aeda-2550ff6ecca6">

I have taken this screenshot from the below file:

https://github.com/phpredis/phpredis/blob/35a7cc094c6c264aa37738b074c4c54c4ca73b87/docs/Redis.html#L591

Thanks

**Comment by LeanderFS** [comment]
Hi @engcom-Hotel 

I can confirm I was talking about the phpredis/phpredis repository. I should've mentioned that in the initial message.

The documentation you've linked is exactly what I mean. The PR linked to this issue fixes the scenario where exec() would return false.

**Comment by engcom-Hotel** [comment]
Thanks @LeanderFS for the response.

We are confirming this issue by looking into the phpredis documentation.

Thanks
