### ISSUE TITLE
Show Out Of Stock on Store View level

### ISSUE THREAD

**Issue by elkalexx** [magento/magento2#37505]
### Summary

Using Magento 2.4.6:

In the Magento 2 backend under:

Stores -> Configuration -> Catalog -> Inventory -> Display Out of Stock Products => This setting is global. 

In the code at some places, I can see that it takes the SCOPE_STPRE into consideration - but this doesn't make a lot since the setting is global.

Eventually, I am trying to make the Display Out of Stock Products option on the store view level not on a global level. 

Can someone give me some direction and guidance on how to achieve this? 

### Examples

In module-catalog-ivnetnroy/Helper/Stock.php I found:

    /**
     * Add only is in stock products filter to product collection
     *
     * @param \Magento\Catalog\Model\ResourceModel\Product\Collection $collection
     * @return void
     */
    public function addIsInStockFilterToCollection($collection)
    {
        $stockFlag = 'has_stock_status_filter';
        if (!$collection->hasFlag($stockFlag)) {
            $isShowOutOfStock = $this->scopeConfig->getValue(
                \Magento\CatalogInventory\Model\Configuration::XML_PATH_SHOW_OUT_OF_STOCK,
                \Magento\Store\Model\ScopeInterface::SCOPE_STORE
            );
            $resource = $this->getStockStatusResource();
            $resource->addStockDataToCollection(
                $collection,
                !$isShowOutOfStock
            );
            $collection->setFlag($stockFlag, true);
        }
    }

Unfortunately, it seems this is deprecated:

` * @deprecated 100.3.0 Replaced with Multi Source Inventory`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @elkalexx,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and it is working as expected.As per Magento devdocs https://experienceleague.adobe.com/docs/commerce-admin/config/catalog/inventory.html?lang=en the Display out of stock products scope level is **Global**.Please refer the document.


<img width="998" alt="Screenshot 2023-05-16 at 6 04 44 PM" src="https://github.com/magento/magento2/assets/51680745/5a2e7f89-d01b-43de-abba-a5b390b5e274">


Thanks.
