### ISSUE TITLE
Save changes of virtual products taking very long

### ISSUE THREAD

**Issue by gotoarchi** [magento/magento2#37517]
### Preconditions and environment

- Magento 2.4.5-p1
- PHP 8.1
- Varnish
- 5 remote varnish hosts, in different world locations,  behind firewalls 

### Steps to reproduce

1 . Enable the Full Page Cache and Varnish
2 . Add a virtual product
3 . Enter the details of the product
4 . Press save
5 . Duplicate and save the product

### Expected result

I am expecting the save process not to take longer than 15-20 seconds maximum. 

### Actual result

Currently this process takes more than 2-3 minutes. The process may timeout and give a 504 it the php does not allow for such long process. This is related with the FPC, as when we disable it the duplication takes maximum 10 seconds.

### Additional information

Our linux engineer har added a long timeout to the php 8.1 to prevent the error 504 dur to a timeout. But something is clearly slower with 2.4.5 than it was with 2.3.7. When we disable the FPC the duplication happens in 10 seconds.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by gotoarchi** [comment]
I see that on the Magento instance above it only takes 5 seconds to create and save the virtual product, so there must be another issue in addition to the steps i mentioned in the issue. Let me try to check what is it in addition.

**Comment by gotoarchi** [comment]
However the version of the Magento is not 2.4.5-p1 as I have on my end.

**Comment by engcom-Dash** [comment]
Hi @gotoarchi ,

Thanks for collaboration and contribution!

Verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly refer the below video reference.

Steps to reproduce:
1.Install magento instance
2.Go to Catalog >Product>add virtual product
3.Save

https://github.com/magento/magento2/assets/60198592/9ca526b0-47d5-4539-a5a5-33af6012acd0

Virtual product save successfully and not to take longer than 15-20 seconds maximum.Kindly recheck the behaviour in 2.4-develop instance and please provide more details if the issue still reproducible.

Regards,

**Comment by gotoarchi** [comment]
@engcom-Dash We conducted some more tests. This error is related with the Full Page Cache and Varnish . When we disable the full page cache, or if we not select varnish as FPC in Magento the duplication of the product is done in less than 10 seconds.

**Comment by gotoarchi** [comment]
https://github.com/magento give me 2.4.5-p1 instance

**Comment by gotoarchi** [comment]
This was due 2 remote varnish servers not being reached, making this operation taking very long. It is not related with any bug,
