### ISSUE TITLE
M2 fails when saving a model on a table with multi-column primary key

### ISSUE THREAD

**Issue by Pinimichu** [magento/magento2#3752]
## Steps to reproduce
1. Reference a ressource model to a database table that has a multi-column primary key
2. Create a model object in magento and try to save it:
   `public function createModelEntry(\vendor\Module\Api\Data\MyModelInterface $modelData) 
   { 
   $modelData->save(); 
   }`
## Expected result
1. Model object should be saved to the database table or an exception should be thrown that multi-column primary keys are not supported
## Actual result
1. Saving the model object continues without exception but data is not saved to the table.
   Info: When violating sql constraints an exception is thrown.

**Comment by piotrekkaminski** [comment]
@antonkril can you look into it?

**Comment by palamar** [comment]
@Pinimichu
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
