### ISSUE TITLE
Latest MariaDB versions break compatibility with Galera Cluster, which affects magento

### ISSUE THREAD

**Issue by warp3r** [magento/magento2#37526]
### Preconditions and environment

- Magento version: 2.4.5-p2, with galera cluster enabled
- Database version: MariaDB 10.4.29

### Steps to reproduce

1. Navigate to storefront
2. Try to add something to basket (if it loads)
3. wait for cron processes to happen

### Expected result

You expect to see the site working and the cron processes to complete.

### Actual result

There is a exception in the exception log stating:

```
[2023-05-18 18:26:04] report.CRITICAL: SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)', query was: SELECT GET_LOCK(?, ?); {"exception":"[object] (Zend_Db_Statement_Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)', query was: SELECT GET_LOCK(?, ?); at /var/www/xxxxx/magento/releases/202305171141_11eb0e8a/magento/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)' at /var/www/xxxxxx/magento/releases/202305171141_11eb0e8a/magento/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

```

### Additional information

This exception happened after updating mariaDB from 10.4.28 to 10.4.29 in our regular patching schedule.

Turned out that mariadb pushed the following changes into this version

```
[Revision #b05218e08f](https://github.com/MariaDB/server/commit/b05218e08f) 2023-01-30 08:55:35 +0200

    [MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster 

[Revision #844ddb1109](https://github.com/MariaDB/server/commit/844ddb1109) 2023-01-26 14:34:12 +0200

    [MDEV-30473](https://jira.mariadb.org/browse/MDEV-30473) : Do not allow GET_LOCK() / RELEASE_LOCK() in cluster
```

Which basically break any Magento2 compatibility with mariadb + galera

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @warp3r ,
Thank you for reporting and collaboration. This issue is not related to Magento2 https://github.com/magento/magento2 repository but seems to be an issue with MariaDB Galera rather than an issue in the Magento. My advice is to check with MariaDB Galera support. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support).
Thank you.

**Comment by warp3r** [comment]
Just to provide some feedback, MariaDB has rolled back their change, so, in the meantime, it is a matter of going straight to versions that revert the change:

- 10.4.30
- 10.6.14

regards,
