### ISSUE TITLE
CMS Page && CMS Block edit save error

### ISSUE THREAD

**Issue by yihang861** [magento/magento2#37525]
### Preconditions and environment

- Magento ver. 2.4.5-p1

### Steps to reproduce

1 Go Cms page list
2 Inline Edit Select the last two or three columns , make sure the last column selected
![image](https://github.com/magento/magento2/assets/15622733/d3c0a659-9f46-482b-9959-383b59a59908)
3 open another window delete one of the three columns (not the last one column) or delete the column in database
![image](https://github.com/magento/magento2/assets/15622733/0999784c-d614-4e17-9c05-a97cbed4b0ef)
4 then save those columns will cause error
![image](https://github.com/magento/magento2/assets/15622733/e111f21d-d454-43e0-b699-2aa8cd70f392)
5 remove the error column
![image](https://github.com/magento/magento2/assets/15622733/04a20c45-1a68-4feb-a736-ff4e2f892de8)
6 save another columns (include the last one column),a loading error occurred.still loading 
![image](https://github.com/magento/magento2/assets/15622733/2940e14e-9ab6-4180-b422-5c3f3db76064)
7 the problem same happend in CMS Block with same steps
![image](https://github.com/magento/magento2/assets/15622733/f503eb2d-f163-4df8-9b22-a853529dfb56)

### Expected result

save the normal columns data success and redirct list 

### Actual result

Had been loading without redirect

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by aasim110** [comment]
@magento I'm working on this

**Comment by aasim110** [comment]
Hey @engcom-Bravo can someone help me to check this? https://github.com/magento/magento2/pull/37560/checks?check_run_id=13881652441

**Comment by aasim110** [comment]
> Hey @engcom-Bravo can someone help me to check this? https://github.com/magento/magento2/pull/37560/checks?check_run_id=13881652441

label: help needed
