### ISSUE TITLE
Bookmark views in grid

### ISSUE THREAD

**Issue by orkuncv** [magento/magento2#37531]
### Preconditions and environment

We have encountered an issue with the Filter View (bookmarks in code) in the Sales Order Grid. The problem is that when modifying a view, the filters get mixed up and sometimes are not saved.
I have tested this issue on a clean Magento EE 2.4.5-p2 installation, and the problem persists.

- Magento EE version: 2.4.5-p2 

### Steps to reproduce
- Go to admin -> Sales
1. Create 2 new filters.
2. Now you have a total of 3 views: Default View, FILTER 1, FILTER 2.
3. Add filters to FILTER 1.
4. Add filters to FILTER 2, making sure they are different from FILTER 1.
5. Save the filters.
6. Change your views to see if the filters are saved correctly.
7. Now go to FILTER 1 or FILTER 2.
8. Refresh your page.
9. Now go back to another view and you will see that the filters are not updated.
10. The Default View suddenly has a filter applied, even though it was not set.

### Expected result

That the correct filters are loaded when (bookmark) views are changed

### Actual result

The correct filters are loaded when switching views

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by Quazz** [comment]
Possibly related to: https://github.com/magento/magento2/issues/37529

**Comment by ronak-vaimo** [comment]
Hi @orkuncv 
This is issue similar to #37529?

**Comment by engcom-Bravo** [comment]
Hi @ronak-vaimo,

Thanks for your contribution & collaboration over here.

We are closing this duplicate https://github.com/magento/magento2/issues/37529.

Thanks.

**Comment by orkuncv** [comment]
Hi @engcom-Bravo and @ronak-vaimo,

This issue is indeed similar to #37529
