### ISSUE TITLE
Error message by ObjectManager should be more helpful / specific

### ISSUE THREAD

**Issue by yavery** [magento/magento2#37537]
### Summary

BadMethodCallException: Missing required argument **$engines** of **Magento\Search\Model\EngineResolver**

NOTE: variable name and class name may vary
ENV: 2.4.5
I notice this type of errors are triggered in at least 3 places
- page: Menu > Marketing > Search Synonyms
- page: Menu > Store > Configuration > Catalog > Catalog
- bin/magento command

easiest way to see is via command:
```
bin/magento module:disable Magento_Elasticsearch
bin/magento config:show
```
![error](https://github.com/magento/magento2/assets/130590250/7cf82e3e-ed73-4b29-9184-eb7e09072f79)

The error is produced by Magento ObjectManager/Factory/AbstractFactory::getResolvedArgument( ... )

### Examples

-

### Proposed solution

option 1.
IF the arguments can not be resolved and due missing a module, it would be nice to tell "Missing module support for Magento\Search\*"

For the catch block to figure out which module would fix the issue may be hard, but an informative message can be more helpful

option 2.
bin/magento can display warning if required modules are missing (but don't block, just warnings is enough)

### Release note

you may wonder if Elasticsearch module is required since 2.4.4, why would it be disabled
- companies using 2.4.3 or lower may turn off the elasticsearch, when they upgrade to 2.4.4 or later, their Elasticsearch module is not turned on automatically or be prompted while using bin/magento setup:upgrade

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @yavery,

Thanks for the report and contribution!

We have tried to reproduce this issue in the fresh installation of the 2.4-develop branch, but the issue is not reproducible for us. Please refer to the below screenshot for reference:

<img width="1390" alt="image" src="https://github.com/magento/magento2/assets/51681618/48d03f15-d4ab-44ee-a5e9-4b57b54def0f">

The `bin/magento config:show` command was completed successfully. Please let us know if we have missed anything.

Thanks
