### ISSUE TITLE
route query returns null for custom URL rewrite

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#37539]
### Preconditions and environment

- Magento version: Commerce 2.4.4-p1

### Steps to reproduce

Add these 2 custom URL rewrite:
![image](https://github.com/magento/magento2/assets/8390252/a8d3251f-dee5-4a78-bae1-e0f5fcd346ec) 
![image](https://github.com/magento/magento2/assets/8390252/2ba3143c-47f1-4484-a40e-eb73c2dd82b6)

Then run the GQL route query: https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/route/

### Expected result

Route response shouldn't be null

### Actual result

Route response is null

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment]
Response from fresh instance: 
[Link:](https://2fc083deabc34ed2656e12d6ef6c82f2.instances-prod.magento-community.engineering/graphql?query=query%20route(%20%0A%20%20%20%20%24url_key%3A%20String!%0A)%20%7B%0A%20%20route(%0A%20%20%20%20%20%20url%3A%20%24url_key%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20relative_url%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20redirect_code%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%20%20...%20on%20CategoryInterface%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20url_key%0A%20%20%20%20%20%20%20%20%20%20%20%20uid%0A%20%20%20%20%20%20%20%20%20%20%20%20canonical_url%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20...%20on%20SimpleProduct%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20url_rewrites%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20parameters%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20...%20on%20ConfigurableProduct%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20url_rewrites%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20parameters%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20...%20on%20GroupedProduct%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20url_rewrites%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20parameters%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20...%20on%20CmsPage%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20identifier%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D&variables=%7B%0A%20%20%20%20%22url_key%22%3A%20%22redirect-to-faq-cms-page%22%0A%7D)


<img width="1050" alt="Screenshot 2023-05-25 at 3 26 58 pm" src="https://github.com/magento/magento2/assets/8390252/301efe91-b15c-43a3-836f-4c6f4dc18ec4">
<img width="1037" alt="Screenshot 2023-05-25 at 3 27 26 pm" src="https://github.com/magento/magento2/assets/8390252/9d96fe50-d62b-4831-b0a5-e0a725aa61c2">

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
HI @adarshkhatri,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

Add these 2 custom URL rewrite:

<img width="1386" alt="Screenshot 2023-06-01 at 2 45 53 PM" src="https://github.com/magento/magento2/assets/51680745/3d281d5b-5b82-40bd-af8f-4c0b73414bed">

We are getting response.

<img width="1422" alt="Screenshot 2023-06-01 at 2 41 25 PM" src="https://github.com/magento/magento2/assets/51680745/4cb91d90-db57-44e6-a143-2fd51fca6ed5">


<img width="1493" alt="Screenshot 2023-06-01 at 2 44 54 PM" src="https://github.com/magento/magento2/assets/51680745/72e21c9c-46e4-4c7d-8552-b6bf26673ff9">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by adarshkhatri** [comment]
@magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment]
I can see that the issue has been fixed by this commit: https://github.com/magento/magento2/commit/b4208512bce542afc8b5b0bf3a9a551a5905ee8e#diff-8f4494cf924c5ba303d87e7e791c3e5cc644232aecef420c8df49b8c0e9298f1
