### ISSUE TITLE
New atributes do not work when filtering them on the frontend

### ISSUE THREAD

**Issue by sazo17** [magento/magento2#37555]
### Preconditions and environment

- Magento version = 2.4.6
- I am currently working on a customization and Magento but this error is happening even with Luma theme When creating a new filterable attribute in the navigation (Dropdown, MultipleSelect) this attribute is selectable in the frontend, but it does not render the products with the filter correctly

### Steps to reproduce

- Cree un nuevo atributo desplegable
- Asignar ese atributo filtrable con resultados y asigueno a productos
- En el frontend en la pagina de categoria utilice el atributo para filtrar

### Expected result

Show only products with the selected attribute in the filter

### Actual result

Muestra todos los productos en la pagina incluso con la URL parametrizada

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gagandeepcs** [comment]
@magento please give me 2.4.6 instance

**Comment by gagandeepcs** [comment]
@magento give me 2.4-develop instance

**Comment by sazo17** [comment]
I check this problem in more detail. I tried this on my production server and it worked correctly. and i replicated the development branch and it works correctly.

Please check this issue in more detail, it seems that this issue occurs if the server configuration is wrong or if there are missing configurations in the services.

I hope this can help if someone has this problem,

thanks for the support
