### ISSUE TITLE
category detail not display

### ISSUE THREAD

**Issue by tungnt1** [magento/magento2#3755]
I've installed magento 2 (clear) by composer on ubuntu 14 with nginx and php 7.
After install, category and sub can not diplayed ... (Admin page--> Products--> Categories... this not show on detail for edit and add new)
Please help me to display theme...

**Comment by TangLiang** [comment]
same errors

**Comment by robinhuy** [comment]
I have same errors, I install magento 2.1.0-rc1 on Ubuntu 16 with Nginx and PHP7. When I open browser console in categories manage page, it display error:

> knockout.js:5024 Uncaught TypeError: Unable to process binding "ifnot: function (){return element.hasAddons() }"
> Message: Unable to process binding "template: function (){return element.elementTmpl }"
> Message: Cannot read property 'name' of undefined

**Comment by piotrekkaminski** [comment]
We are not able to reproduce it. Make sure you are using correct version of PHP7 (some versions are not compatible).
