### ISSUE TITLE
Upgrade the `league/flysystem` requirement in `magento/module-remote-storage`

### ISSUE THREAD

**Issue by speller** [magento/magento2#37552]
### Preconditions and environment

- Magento version 2.4.6
- PHP 8.2

### Steps to reproduce

Generate errors with remote files

### Expected result

Errors handled properly

### Actual result

I get PHP 8.2 deprecation errors in some of the Flysystem exception classes like this:

```none
Deprecated Functionality: Using ${var} in strings is deprecated, use {$var} instead in /magento/vendor/league/flysystem/src/UnableToCheckFileExistence.php on line 14
```

I found this deprecation in the following classes:

- `UnableToCheckFileExistence`
- `UnableToCreateDirectory`

### Additional information

The v3 of the `league/flysystem` package has no this issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @speller,

Please elaborate on the below line from steps to reproduce. Do you mean we can use AWS S3 for image storage and then delete that file to generate an error?
> Generate errors with remote files

Thanks

**Comment by engcom-Hotel** [comment]
Dear @speller,

We have noticed that this issue has not been updated for a period of long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by speller** [comment]
@engcom-Hotel The usage of a package that has deprecation errors should be avoided no matter what. I don't remember exactly what was the use case. But since I've mentioned the `UnableToCheckFileExistence` class, it happens when you upload a file and then delete it and try to manipulate it (or try to manipulate a non-existent file).
