### ISSUE TITLE
[MYSQL] Mysql not supported error

### ISSUE THREAD

**Issue by eByte23** [magento/magento2#3756]
## Steps to reproduce

clone repo
install with composer
run install from bin/magento 

```
php bin/magento setup:install --db-host=localhost --db-name=<dbname> --db-user=<dbuser> --db-pass=<dbpass> --backend-frontname=manager --admin-username=<user> --admin-password=<pass> --admin-email=<email> --admin-firstname=<fname> --admin-lastname=<lname> --base-url=<url> --base-url-secure=<url> --language=en_US --currency=USD --use-rewrites=true --use-secure=true --use-secure_admin=true --cleanup-database -s
```
## Expected result

Installs properly
## Actual result

 [Magento\Setup\Exception]  
  Sorry, but we support MySQL version 5.6.0 or later.  

![screen shot 2016-03-14 at 3 35 51 pm](https://cloud.githubusercontent.com/assets/8544875/13735142/11fe1528-e9fa-11e5-8320-6a03eaaf98d0.png)

Am I doing somthing wrong?

I had mysql install go the error so updated still had error.
Then did complete backup and restore to mariadb.

**Comment by mrkhoa99** [comment]
@eByte23 you should check System Requirement before setting up Magento 2: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html. Magento 2 doesn't support your current MySQL version. Please, upgrade to 5.6.x version.

**Comment by eByte23** [comment]
@mrkhoa99 I did do exactly that I had the correct version yet it still threw errors so I read on another issue where someone said mariadb was supported so I upgrade to that and the same error message

**Comment by mrkhoa99** [comment]
Hello @eByte23,
Can you show me your current environment system? OS, PHP version, Web server, MySQL version, MariaDB version?
In my opinion, we should install Magento 2 with MySQL at the first time. For more detail about our error message, we should take a look at this file: https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L94-L103. 
We can hack the code lines and try to install with Mariadb.

**Comment by eByte23** [comment]
I found the reason it was the version of mariadb 10+ only gives off mysql versions 5.5
How ever install completes fine on mariadb 10.1 when I comment out the validator I'll do a pr for maraidb support.

Cheers

**Comment by daim2k5** [comment]
@eByte23 so i close the issue for now.
