### ISSUE TITLE
session_regenerate_id(): Cannot regenerate session id - session is not active

### ISSUE THREAD

**Issue by TangLiang** [magento/magento2#3757]
When I enabled the memcache for magento 2,I can't login admin panel any more also customer can't login frontend.

when i register customer from frontend,it shows error like blow.

1 exception(s):
Exception #0 (Exception): Warning: session_regenerate_id(): Cannot regenerate session id - session is not active in /home/wwwroot/demo.com/lib/internal/Magento/Framework/Session/SessionManager.php on line 473

after i disabled the memcache all run good.

php 7.0.4,Nginx 1.8.1

**Comment by sumeetmobiwebtech** [comment]
@TangLiang 

how did you solved ?
