### ISSUE TITLE
Unable to reorder if order is placed from other store.

### ISSUE THREAD

**Issue by raghvendra-1112** [magento/magento2#37572]
### Preconditions and environment

- Magento version - 2.4.5
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1- Place an order in Store "ar".
2- Switch to store "en" and the Run re-order GraphQl.
3- You will get the error- "Order number \"SWSG-13300015642\" doesn't belong to the current customer"

![Screenshot from 2023-06-03 13-06-33](https://github.com/magento/magento2/assets/78547604/5f65c8ef-6e9f-4c55-85b4-c2a8145e7ba4)

### Expected result

Re-Order GraphQl should run successfully and Items should be added to Cart.

### Actual result

Error in Re-Order GraphQl.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jerry32410** [comment]
Store Policies: Each store has its own policies regarding reordering and returning items. Some stores may allow you to reorder items without any issues, while others may have restrictions or limitations. It's important to review the store's policies regarding reorders and returns to understand what options are available to you.

Availability of Items: The items you wish to reorder may not be available in the other store. Different stores may carry different inventory, so it's possible that the specific items you want may not be in stock at the new store. You may need to check with the new store to verify if they have the items you want before attempting to reorder.

Payment and Refunds: If you have already placed an order [best-saddle-chairs](https://chairsexpo.com/best-saddle-chairs/) and made payment at the first store, you may need to consider the refund process before placing a new order at the second store. If the first store has already processed your payment, you may need to wait for a refund before making a new purchase elsewhere.

**Comment by engcom-Bravo** [comment]
Hi @raghvendra-1112,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
