### ISSUE TITLE
Invalid login and password

### ISSUE THREAD

**Issue by claudiumitreaa** [magento/magento2#3758]
Steps to reproduce
Upgrade magento 1.7.x to 2.0.x with migration data tool from ubertheme.

Expected result
All is ok.

Actual result
When I try to login with any customer email and password I got "Invalid login and password.", but in the old store, the same customers working perfectly.

**Comment by shuaiZend** [comment]
key Different.
vi magento1/app/etc/local.xml
find key.

look like ：
`<crypt>
            <key><![CDATA[5f02266b3f25c72cf5e812a5f26616xx]]></key>
        </crypt>
`

and find M2 key

vi magento2/app/etc/env.php

find key.

look like ：
`array (
    'key' => '13153a1888aec0d4e88734fe286369xx',
  ),`

copy M1 key Value to M2.

and login again.

**Comment by claudiumitreaa** [comment]
Thanks for your answer!
I made the changes, now in some accounts I can login but in another, still I got "Invalid login and password." .
I check the password_hash field from table customer_entity and for the accounts where I can login, the password look like "db2408d6bc4c99ea09baf9701f241886:PP:0" instead for the accounts where I can't login password look like "db2408d6bc4c99ea09baf9701f241886:0".

**Comment by shuaiZend** [comment]
PP is salt.
Here is how a password's hash is generated in Magento 2:
magento2/blob/8fd3e8/lib/internal/Magento/Framework/Encryption/Encryptor.php#L155-L162
`return implode(
    self::DELIMITER,
    [
        $this-&gt;hash($salt . $password),
        $salt,
        $version
    ]
);`

**Comment by quienti** [comment]
https://github.com/ubertheme/module-ubdatamigration/blob/master/README.md

`Upgrade Password Hash (This is optional task for more security):
In your terminal window run bellow command php -f PATH_YOUR_MAGENTO_2/bin/magento customer:hash:upgrade upgrade customer password_hash`

**Comment by claudiumitreaa** [comment]
I run your command and I got this 
Exception trace:
 () at /home/storekpiin/public_html/store/vendor/magento/module-customer/Console/Command/UpgradeHashAlgorithmCommand.php:67
 Composer\Util\ErrorHandler::handle() at /home/storekpiin/public_html/store/vendor/magento/module-customer/Console/Command/UpgradeHashAlgorithmCommand.php:67
 Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand->execute() at /home/storekpiin/public_html/store/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /home/storekpiin/public_html/store/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/storekpiin/public_html/store/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/storekpiin/public_html/store/vendor/magento/framework/Console/Cli.php:49
 Magento\Framework\Console\Cli->doRun() at /home/storekpiin/public_html/store/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/storekpiin/public_html/store/bin/magento:25

![error](https://cloud.githubusercontent.com/assets/16424213/13771777/e663800c-ea98-11e5-9470-11a7faf817f9.png)

**Comment by maksek** [comment]
This issue belongs to migration tool, not magento 2 core. Please open issue with steps in according repo - https://github.com/magento/data-migration-tool

**Comment by likhamahudda** [comment]
After migration M1 to M2 
old customer login error resole 
Please update this query in database 

**UPDATE customer_entity_varchar,customer_entity SET customer_entity_varchar.value = customer_entity.password_hash WHERE customer_entity_varchar.entity_id = customer_entity.entity_id and customer_entity_varchar.attribute_id='12'**

attribute_id means password type values id in customer_entity_varchar table 

main problem old password value and new password values not match in magneto

![login_password](https://user-images.githubusercontent.com/23294648/27685631-b625f0a6-5cec-11e7-91ec-f727caa884ce.png)

![passwordmissmtah](https://user-images.githubusercontent.com/23294648/27685820-77b09f50-5ced-11e7-92f1-dd628534ca58.png)

**Comment by Krupaly2k-zz** [comment]
Hi likhamahudda,

I have tried above solution but still I am facing same issue. I am unable to login with Magento1 customer account. I am using Magento 2.1.6 version. Please help me to resolve this issue soon.

**Comment by claudiumitreaa** [comment]
in magento 1.x the password is encrypted using md5, in magento 2 is not used md5, that is the reason you can’t log in after migration
i fixed that with some custom code, but i modified somethig in vendor
leave me your email and i’ll send you my solution, maibe it helps you

**Comment by Krupaly2k** [comment]
Hi Claudiumtreaa,

Thanks for quick response. Please send me details on krupaly2k@gmail.com

**Comment by claudiumitreaa** [comment]
Hello,
I attached a text file with the code.
After you do the changes clean the cache and you can update your modules.
Let me know if it helped you.
Sorry for my english. 

    În Marţi, 3 Octombrie 2017 8:50:40, Krupal <notifications@github.com> a scris:
 

 Hi Claudiumtreaa,Thanks for quick response. Please send me details on krupaly2k@gmail.com—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   




\vendor\magento\framework\Encryption\Encryptor.php

line 186

 public function isValidHash($password, $hash)
    {

        $this->explodePasswordHash($hash);

        $passunhashed = $password;

        foreach ($this->getPasswordVersion() as $hashVersion) {
            $password = $this->hash($this->getPasswordSalt() . $password, $hashVersion);
        }

        $password = $password."+++".md5($passunhashed);



        return Security::compareStrings(
            $password,
            $this->getPasswordHash()
        );
    }

\vendor\zendframework\zend-crypt\src\Utils.php	

line 30

 public static function compareStrings($expected, $actual)
    {
        $arr = explode("+++",$expected);


        if($arr[0] === $actual){
            $expected = $arr[0];
        }else{
            $expected = $arr[1];
        }



        $expected     = (string) $expected;
        $actual       = (string) $actual;


        if (function_exists('hash_equals')) {
            return hash_equals($expected, $actual);
        }

        $lenExpected  = strlen($expected);
        $lenActual    = strlen($actual);
        $len          = min($lenExpected, $lenActual);

        $result = 0;
        for ($i = 0; $i < $len; $i++) {
            $result |= ord($expected[$i]) ^ ord($actual[$i]);
        }
        $result |= $lenExpected ^ $lenActual;

        return ($result === 0);
    }

**Comment by likhamahudda** [comment]
Hello,

I got another solution and very quick and easy 

Just Empty the table (TRUNCATE)  **" customer_entity_varchar "**

100% sure login old customer in New  magento 2

Thanks

**Comment by mariamghalleb** [comment]
@likhamahudda how to empty that table ? whats the command please.. 

I imported users from magento 1.3 to a magento 2.2 through csv with their old password_hash that looks like this b67f0da6abeaa55560701296df7f05d7:3K

would your solution convert the passwords? thanks!
