### ISSUE TITLE
Allowed memory size exhausted due to No such entity exception

### ISSUE THREAD

**Issue by Bilalyounas1234** [magento/magento2#37594]
### Summary

After upgrading the Magento version to 2.4.3p1 we are facing (No such entity exception) issues and due to this our server goes down and then we need to restart all services. We checked some time this error occurs while product search sometimes on checkout and sometimes on any other request. 

Logs in nginx due to this issue:

 [error] 107960#107960: *3469139 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4194312 bytes) in /data/site/vendor/magento/framework/Exception/NoSuchEntityException.php on line 50" while reading response header from upstream, request: "GET /en/catalogsearch/result/?q=Prime HTTP/1.1", upstream: "fastcgi://127.0.0.1:9004", host: "site", referrer: "https://site/en/catalogsearch/result/?q=Sunscreen+"
 [error] 107960#107960: *3469131 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4194312 bytes) in /data/site/vendor/magento/framework/Exception/NoSuchEntityException.php on line 50" while reading response header from upstream, request: "GET /en/popup/ajax/addCookie/?isAjax=true&form_key=RYfvz8vlQ4fNnbG4&cookie_type=aw_popup_viewed_page&current_url=https%3A%2F%2Fsite%2Fen%2Fcms%2Findex%2Findex%2F HTTP/1.1", upstream: "fastcgi://127.0.0.1:9004", referrer: "https:/site/site/en/"

### Examples

 [error] 107960#107960: *3469139 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4194312 bytes) in /data/site/vendor/magento/framework/Exception/NoSuchEntityException.php on line 50" while reading response header from upstream, request: "GET /en/catalogsearch/result/?q=Prime HTTP/1.1", upstream: "fastcgi://127.0.0.1:9004", host: "site", referrer: "https://site/en/catalogsearch/result/?q=Sunscreen+"
 [error] 107960#107960: *3469131 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4194312 bytes) in /data/site/vendor/magento/framework/Exception/NoSuchEntityException.php on line 50" while reading response header from upstream, request: "GET /en/popup/ajax/addCookie/?isAjax=true&form_key=RYfvz8vlQ4fNnbG4&cookie_type=aw_popup_viewed_page&current_url=https%3A%2F%2Fsite%2Fen%2Fcms%2Findex%2Findex%2F HTTP/1.1", upstream: "fastcgi://127.0.0.1:9004", referrer: "https:/site/site/en/"

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Bilalyounas1234,

Thank you for reporting and collaboration.


Please try to increase size. your PHP.ini settings, in this case is the `memory_limit`


use this commands

`php -dmemory_limit=-1`

`bin/magento setup:di:compile`

`bin/magento setup:static-content:deploy`


Kindly let us know if you are still facing any issue.


Thanks.

**Comment by mohammadbharmal** [comment]
#36623

**Comment by engcom-Bravo** [comment]
Hi @Bilalyounas1234,

Please provide us latest update on this comment https://github.com/magento/magento2/issues/37594#issuecomment-1584038647 and if you are still facing any issue kindly refer this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/php-settings.html?lang=en regarding PHP settings.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @Bilalyounas1234,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
