### ISSUE TITLE
magento search

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#3760]
We are building an application using Magento-2 Rest APIs.

In the application we are implementing a search function using rest
api. The search will happen using multiple filters. By default,
magento is using "and" operator between filters for producing search
results.

However our requirement is to use "or" operator between filter so that
result matching with any of the filter will show up.

We have one more requirement where we need to display the result
matching with first filter on top and then the result matching with
second filter

kindly guide us how we can achieve this.

**Comment by choukalos** [comment]
Check out our dev docs page on search criteria ( recently renamed / moved to make it easier to find ) - [link](http://devdocs.magento.com/guides/v2.0/howdoi/webapi/search-criteria.html).
