### ISSUE TITLE
REST /configurable-products/sku/children endpoint missing media_gallery_entries

### ISSUE THREAD

**Issue by cykolln** [magento/magento2#37607]
### Preconditions and environment

- Magento version: 2.4.3

### Steps to reproduce

1. Create a new configurable product and add configurations with unique product images. 
2. Make a request in postman using the `/configurable-products/{sku}/children`. 

### Expected result

Per the [rest api docs](https://developer.adobe.com/commerce/webapi/rest/quick-reference/?query=media_gallery_entries&keywords=&index=commerce-marketplace%2Ccommerce-contributor%2Ccommerce-cloud-tools%2Ccommerce-webapi%2Ccommerce-php%2Ccommerce-services%2Ccommerce-frontend-core%2Ccommerce-admin-developer%2Ccommerce-xd-kits%2Ccommerce-pwa-studio%2Cfranklin-commerce%2Ccommerce-testing%2Ccommerce-events) there should be a `media_gallery_entries` field on the response data for each child.

### Actual result

The `media_gallery_entries` field is missing entirely. Making a request to the `/products` endpoint searching for one of the configurations you will get a response containing the `media_gallery_entries` field but for some reason it is missing from the `/children` response. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cykolln** [comment]
@engcom-Dash do we have an update here?

**Comment by engcom-Dash** [comment]
Hi @cykolln ,

verified the issue in 2.4-develop instance and its reproducible,Hence we are confirming the issue.
Magento version 2.4-develop
PHP version 8.1
Steps to reproduce:
Create a new configurable product and add configurations with unique product images.
Make a request in Swagger using` /configurable-products/{sku}/children.`
Kindly check below response body:
https://publuu.com/flip-book/183128/449076
The media_gallery_entries file is missing as per the actual result.

Thanks

**Comment by JettyRohanAditya** [comment]
@magento I am working on this
