### ISSUE TITLE
No revenue data in GA4 when using Magento_GoogleGtag extension

### ISSUE THREAD

**Issue by hewgim** [magento/magento2#37605]
### Preconditions and environment

Magento 2.4.5-p1
Google Analytics 4

### Steps to reproduce

Switch on Google Analytics 4 part of the Magento Google Gtag extension
Place an order
Wait for data to appear in Google Analytics 4
On GA4, goto Reports->Monetization-> E-commerce purchases

### Expected result

Correct revenue data is reported

### Actual result

Items purchased (quantities) are reported correctly but revenue is reported as zero.

### Additional information

If you Google the issue of revenue not showing on GA4, a common problem is that the currency is not being passed in the purchase event.

According to the Google developer documentation there ought to be (an ISO 3) currency field set in the purchase event data: see https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?sjid=1876830166853332977-EU&client_type=gtag

When I added console.log statements to vendor/magento/module-google-gtag/view/frontend/web/js/google-gtag.js, I can see that the purchaseObject data sent with the purchase event does not contain a currency field.

Probably needs an urgent fix given that the deadline for GA4 adoption is 1st July 2023

Regards

Mark

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @hewgim,

Thank you for reporting and collaboration.

“Google Analytics 4 (GA4)” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by hewgim** [comment]
Hi @engcom-Bravo,

It does seem to be part of the 2.4 develop branch...it's the Magento_GoogleGtag extension and the code in question can be found under app/code/Magento/GoogleGtag/Block/Ga.php

Regards

Mark

**Comment by hewgim** [comment]
Hi @engcom-Bravo,

I don't think this issue should be closed. It's a definite bug in the Magento GoogleGtag extension that ships with Magento. Google Analytics 4 reports will display no revenue data unless the currency field is passed in.

Regards

Mark

**Comment by istoutjesdijk** [comment]
@hewgim Thanks for the fix, works perfectly.

**Comment by ernesthernandez** [comment]
The issue is still reproducible in the 2.4.6-p3 version. Here is the patch
[GH-37688_analytics_revenue_fix.patch](https://github.com/magento/magento2/files/14531038/GH-37688_analytics_revenue_fix.patch)
