### ISSUE TITLE
swatchesRenderer: simple product price does not update on catalog page

### ISSUE THREAD

**Issue by glwstor** [magento/magento2#3761]
Prices of simple and virtual products, within a configurable product, will not be updates on catalog page.
By clicking a swatch, the new swatch image will be loaded but not the associated price.
The swatch images and prices are present in the <script> section next to the configurable product on the catalog page.
No js errors appears in the browser log.

**Comment by dafencun** [comment]
This issue was reported previously @  [#3150](https://github.com/magento/magento2/issues/3150)

**Comment by justindocanto** [comment]
Since #3150 is identical, open & active, you guys may want to close this one.

**Comment by piotrekkaminski** [comment]
Closing as duplicate.
