### ISSUE TITLE
Wrong products showed in category when "display out of stock products" is enabled.

### ISSUE THREAD

**Issue by Andreabont** [magento/magento2#37612]
### Preconditions and environment

- Magento version: 2.4.5 CE
- PHP version: 8.1.9
- Opensearch version: 1.2.4
- Mysql version: 8.0

### Steps to reproduce

1. Set option "Catalog -> Inventory -> Stock Options -> Display Out of Stock Products" to yes.
2. Create an empty category.
3. Create a simple product (A) in stock, assign to the category and set it visible only in search.
4. Create a simple product (B) in stock, assign to the category and set it visible in category and in search.
5. Reindex and clear cache

### Expected result

In the category page, the product A is hidden, and is visible only product B.

### Actual result

Both products, A and B, are visible in the category page.

### Additional information

This bug is triggered only if  the "display out of stock products" option is set to Yes and if in the category there are at least one product that are set as visibile. 

In this function there are a logic that ignore the result from OpenSearch if the "display out of stock products" is set, and search products on database, probably without the correct filters on visibility:

\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::getProductIdsBySaleability

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Andreabont** [comment]
Hi, 

I'm using Magento 2.4.5, but in the branch 2.4-develop the magento version is higher. 

I think that you already fix this bug with this ticket: [#35918](https://github.com/magento/magento2/issues/35918) linked to the commit 0e0c57ff8b3c970da23253e9611c55e547921aed named "ACP2E-748: Layered navigation filters don't work when "show out of stock" is enabled".

So, I must upgrade to Magento 2.4.6 (or maybe the 2.4.5-p3?)

Thank you
