### ISSUE TITLE
Can not install Magento 2.4.7-beta1 by composer

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#37610]
### Preconditions and environment

- Magento v2.4.7-beta1
- Composer v2.5.8

### Steps to reproduce

Install Magento 2.4.7-beta1 by composer:
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.7-beta1 magento`

### Expected result

Install process without error

### Actual result

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.7-beta1 magento
Creating a "magento/project-community-edition=2.4.7-beta1" project at "magento/"
Installing magento/project-community-edition (2.4.7-beta1)
  - Downloading magento/project-community-edition (2.4.7-beta1)
  - Installing magento/project-community-edition (2.4.7-beta1): Extracting archive
Created project in /home/magento/
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - paypal/module-braintree 4.6.0-beta1 requires paypal/module-braintree-customer-balance 4.6.0-beta1 -> could not be found in any version, there may be a typo in the package name.
    - magento/product-community-edition 2.4.7-beta1 requires adobe-commerce/os-extensions-metapackage ~1.0 -> satisfiable by adobe-commerce/os-extensions-metapackage[1.0.0-beta1].
    - adobe-commerce/os-extensions-metapackage 1.0.0-beta1 requires paypal/module-braintree ~4.6.0 -> satisfiable by paypal/module-braintree[4.6.0-beta1].
    - Root composer.json requires magento/product-community-edition 2.4.7-beta1 -> satisfiable by magento/product-community-edition[2.4.7-beta1].

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @minhluan259 ,
Thank you for reporting and collaboration. Verified the issue by trying to install Magento 2.4.7-beta1 as per Magento [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and the issue is reproducible. Hence confirming the issue.
![image](https://github.com/magento/magento2/assets/60198231/7c59bbae-f880-4586-9090-68dd8e8c67e2)

**Comment by minhluan259** [comment]
@srsathish92 the issue still like this:

> Hi @minhluan259 , Thank you for reporting and collaboration. Verified the issue by trying to install Magento 2.4.7-beta1 as per Magento [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and the issue is reproducible. Hence confirming the issue. ![image](https://user-images.githubusercontent.com/60198231/245671966-7c59bbae-f880-4586-9090-68dd8e8c67e2.png)

**Comment by srsathish92** [comment]
@minhluan259 Strange!! try "composer clear-cache" and install it again.

**Comment by ihor-sviziev** [comment]
I can confirm that it doesn't work for me.
<img width="1476" alt="image" src="https://github.com/magento/magento2/assets/1873745/7fd09162-6944-46b6-9a82-9451a218ec99">


@srsathish92, I believe your account has additional access.

Is it available for everyone, or just for some group of people?

**Comment by minhluan259** [comment]
> @minhluan259 Strange!! try "composer clear-cache" and install it again.

composer cache was cleaned

**Comment by hiren-gujarati** [comment]
I can confirm that Magento 2.4.7-beta1 installation does not work with account which normal access. It is working fine with account which have additional access.
![image](https://github.com/magento/magento2/assets/80200879/2573460e-9a54-4516-87f0-9bb8fd506c4a)

**Comment by srsathish92** [comment]
@ihor-sviziev Yes, you are right. Thanks

**Comment by engcom-November** [comment]
Hi @minhluan259 ,
Issue is resolved now. We are able to install Magento 2.4.7-beta1 using composer as per Magento [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html)

**Comment by ihor-sviziev** [comment]
I can confirm now it works fine
<img width="569" alt="image" src="https://github.com/magento/magento2/assets/1873745/d183eaea-9a5f-4b60-9af0-b060de88bef9">
