### ISSUE TITLE
normalizePath should return empty string if $path is null

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#37619]
Magento 2.4.4-p3

There is a bug in [this repo ](https://github.com/vpietri/magento2-developer-quickdevbar/issues/67 )which is caused because the method does not deal with the situation where `$path` is `null`

https://github.com/magento/magento2/blob/adc4105fcfbeee29d534482d8c6d9c5c1a193a0c/lib/internal/Magento/Framework/View/FileSystem.php#L172

It could be fixed by adding this line:

    if (empty($path)) return "";

**Comment by engcom-November** [comment]
Hello @Eddcapone,

Thank you for report and collaboration!

We have tried to reproduce this on magento 2.4-develop.
We created a custom module to print the `normalizePath()` output in the custom cms page.
Please refer to screenshots below:
<img width="1109" alt="image" src="https://github.com/magento/magento2/assets/60198231/e638f90a-f5c2-432c-bff4-7614b1b165d2">
![image](https://github.com/magento/magento2/assets/60198231/cc2ce230-f320-470b-a68b-de5780762034)


Here, when we pass `null` to `normalizePath()` we get empty string as output.
And in the `system.log` also we did not find any error regarding this.
Hence null or empty string value is being handled by the function.

Please let us know if we are missing anything.

Thank you.

**Comment by hostep** [comment]
Seems like this was fixed in https://github.com/magento/magento2/commit/7160ad6ab72241168ad66b67e58829620130d644#diff-f9f7cfc3e83ec5306ed1b89e19f0e8ca45e02b0daa2100837a42653c46a6d16a (which got included in Magento 2.4.5 and higher)
