### ISSUE TITLE
Braintree Your payment could not be taken. Please try again or use a different payment method. Authentication Required

### ISSUE THREAD

**Issue by DavaGordon** [magento/magento2#37623]
### Preconditions and environment

- Magento Version: 2.4.2-p2
- Magento Braintree Version: v2.9.5
- Chrome, Safari, Firefox, Opera, Tor

### Steps to reproduce

Setup braintree payment method with card payments and vault enabled only.

### Expected result

Customer to be redirected to the checkout success page

### Actual result

Some of our customers unable to checkout on the site, during the checkout process they fill in their details and click the place order button but nothing happens. no error or response.

```Magento2 v2.9.5: #0 /home/picsmeco/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(549): PayPal\Braintree\Gateway\Command\GatewayCommand->execute(Array)
#1 /home/picsmeco/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(451): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
#2 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 8.49)
#3 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 8.49)
#4 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(1136): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 8.49)
#5 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(458): Magento\Sales\Model\Order\Payment->authorize(true, 8.49)
#6 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order\Interceptor))
#7 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(983): Magento\Sales\Model\Order\Payment->place()
#8 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(1205): Magento\Sales\Model\Order->_placePayment()
#9 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#10 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#11 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Order/Interceptor.php(356): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#13 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place()
#14 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#15 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#16 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/Sales/Model/Service/OrderService.php(25): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#17 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\Sales\Model\Service\OrderService->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#18 /home/picsmeco/public_html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#19 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#20 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#21 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, NULL)
#22 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#23 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#24 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#25 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#26 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#27 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(68): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, Array)
#28 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#29 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder(32400, NULL)
#30 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('placeOrder', Array)
#31 /home/picsmeco/public_html/vendor/mageworx/module-giftcardsbase/Plugin/Api/ValidateGiftCardsBeforePlaceOrderPlugin.php(121): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, NULL)
#32 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): MageWorx\GiftCards\Plugin\Api\ValidateGiftCardsBeforePlaceOrderPlugin->aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), 32400)
#33 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(32400)
#34 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(50): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('placeOrder', Array, Array)
#35 /home/picsmeco/public_html/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(120): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder(32400)
#36 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#37 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#38 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/PaymentInformationManagement.php(59): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#39 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\PaymentInformationManagement->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\PaymentInformationManagement\Interceptor), Object(Closure), 32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#40 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#41 /home/picsmeco/public_html/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, NULL)
#42 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#43 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#44 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#45 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#47 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /home/picsmeco/public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#49 /home/picsmeco/public_html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /home/picsmeco/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#51 /home/picsmeco/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#52 /home/picsmeco/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#53 {main} [] []```

### Additional information

This issue only seems to be intermittent as some customers are able to place orders whereas others get this issue.

A colleague placed an order on his account then tried again using the hr account and received this issue 

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @DavaGordon ,

Verified the issue in 2.4.2-p2 Magento instance and the issue is not reproducible.Kindly refer the below screenshots:
<img width="1505" alt="Screenshot 2023-06-19 at 3 17 15 PM" src="https://github.com/magento/magento2/assets/60198592/eabfe1e3-962d-4678-ab23-4ffd8f85998d">
<img width="1505" alt="Screenshot 2023-06-19 at 3 19 45 PM" src="https://github.com/magento/magento2/assets/60198592/c0d64b9e-848f-4608-9cb7-30ba63da6271">

Steps to reproduce:
1.Install Magento instance
2.Go to Stores > Sales >Payment methods>Configure Braintree
3.Enable Valued Card payments
4.Go to Front-end Place the order through Braintree Payment

We can able to place the order successfully Kindly recheck the behaviour and Let us know if we are missing anything!

Thanks!

**Comment by DavaGordon** [comment]
@engcom-Dash As per my comment previously we noticed that this was an intermittent issue and only affected some customers. 

Steps we took. 

- Add item to the basket
- Login as customer A.
- Proceed to checkout to payment stage
- Make Payment Successful
- Logout as customer A 
- Add item to the basket
- Login as customer B. 
- Proceed to checkout to payment stage
- Enter card details (same card and address details as customer A)
- Payment fails no notification of failed payment nothing. 

After customer B fails i go into the log and we get the issue raised.


> ### Preconditions and environment
> * Magento Version: 2.4.2-p2
> * Magento Braintree Version: v2.9.5
> * Chrome, Safari, Firefox, Opera, Tor
> 
> ### Steps to reproduce
> Setup braintree payment method with card payments and vault enabled only.
> 
> ### Expected result
> Customer to be redirected to the checkout success page
> 
> ### Actual result
> Some of our customers unable to checkout on the site, during the checkout process they fill in their details and click the place order button but nothing happens. no error or response.
> 
> ```
> #1 /home/picsmeco/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(451): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
> #2 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 8.49)
> #3 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 8.49)
> #4 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(1136): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 8.49)
> #5 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(458): Magento\Sales\Model\Order\Payment->authorize(true, 8.49)
> #6 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order\Interceptor))
> #7 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(983): Magento\Sales\Model\Order\Payment->place()
> #8 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(1205): Magento\Sales\Model\Order->_placePayment()
> #9 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
> #10 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
> #11 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
> #12 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Order/Interceptor.php(356): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
> #13 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place()
> #14 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
> #15 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
> #16 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/Sales/Model/Service/OrderService.php(25): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
> #17 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\Sales\Model\Service\OrderService->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
> #18 /home/picsmeco/public_html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
> #19 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
> #20 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
> #21 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, NULL)
> #22 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
> #23 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
> #24 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
> #25 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
> #26 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
> #27 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(68): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, Array)
> #28 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
> #29 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder(32400, NULL)
> #30 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('placeOrder', Array)
> #31 /home/picsmeco/public_html/vendor/mageworx/module-giftcardsbase/Plugin/Api/ValidateGiftCardsBeforePlaceOrderPlugin.php(121): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, NULL)
> #32 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): MageWorx\GiftCards\Plugin\Api\ValidateGiftCardsBeforePlaceOrderPlugin->aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), 32400)
> #33 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(32400)
> #34 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(50): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('placeOrder', Array, Array)
> #35 /home/picsmeco/public_html/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(120): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder(32400)
> #36 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #37 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
> #38 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/PaymentInformationManagement.php(59): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #39 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\PaymentInformationManagement->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\PaymentInformationManagement\Interceptor), Object(Closure), 32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #40 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #41 /home/picsmeco/public_html/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, NULL)
> #42 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(32400, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #43 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
> #44 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
> #45 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> #46 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
> #47 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #48 /home/picsmeco/public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
> #49 /home/picsmeco/public_html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #50 /home/picsmeco/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
> #51 /home/picsmeco/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
> #52 /home/picsmeco/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
> #53 {main} [] []```
> 
> ### Additional information
> 
> This issue only seems to be intermittent as some customers are able to place orders whereas others get this issue.
> 
> A colleague placed an order on his account then tried again using the hr account and received this issue 
> 
> ### Release note
> 
> _No response_
> 
> ### Triage and priority
> 
> - [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
> - [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
> - [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
> - [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
> - [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
> ```

**Comment by engcom-Dash** [comment]
Hi @DavaGordon ,

Thanks for the inputs,

We verified the issue with latest stable version 2.4.7-beta1 and the issue is not reproducible.We can successfully place the order with both the customer.
Kindly refer the below video reference:

https://github.com/magento/magento2/assets/60198592/0e7d6d46-2075-48a7-bc94-c05e36fef35b

Thanks

**Comment by chernenm** [comment]
@magento give me 2.4-develop instance
