### ISSUE TITLE
Add Products to Group

### ISSUE THREAD

**Issue by Totarenx** [magento/magento2#3763]
## Steps to reproduce
1. Install Magento 2.0.2.
2. Backend -> Products -> Catalog -> Add Product -> Grouped Product -> Add Products to Group
3. Scroll product list
4. Try to select any

![image](https://cloud.githubusercontent.com/assets/14783879/13741106/6c74e5b4-e9e5-11e5-9234-e85c51173ff7.png)

**Comment by piotrekkaminski** [comment]
Cannot reproduce this issue in 2.1RC. If you are still experiencing issues in this version please open a new ticket with detailed steps to reproduce.
