### ISSUE TITLE
Access token auth deprecation plans

### ISSUE THREAD

**Issue by jmoskovc** [magento/magento2#37643]
### Summary

Hi,
since the token based auth using the never expiring tokens was disabled by default I was wondering if there's any plans to completely remove that option some time in future? If so is there any (rough) timelines for it?

Thank you,
-- Jiri

### Examples

N/A

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@nathanjosiah: you can probably tell more about this?

**Comment by jmoskovc** [comment]
Thank you @nathanjosiah for a quick answer! As far as I'm concerned this issue is now resolved.

**Comment by engcom-Dash** [comment]
Hi @jmoskovc ,

Are you want any further investigation regarding this issue? or If the problem is resolved shall we close the issue ???
Kindly let me know.

Thanks

**Comment by jmoskovc** [comment]
Hi @engcom-Dash ,
I've got the info I needed, so happy to close this.
