### ISSUE TITLE
Magento\Widget\Controller\Adminhtml\Widget\Index has no ADMIN_RESOURCE

### ISSUE THREAD

**Issue by mnjongerius** [magento/magento2#3764]
When I try editing a widget with a user with VERY limited permissions (only CMS paged/blocks/widgets/media) I get a 404. 

I found out this has to do with the function _isAllowed returning false.

I guess giving this class the correct ADMIN_RESOURCE could fix this?

**Comment by mnjongerius** [comment]
Same goes for BuildWidget and LoadOptions

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54359

**Comment by magento-engcom-team** [comment]
@mnjongerius, thank you for your report.
We've created internal ticket(s) MAGETWO-54359 to track progress on the issue.

**Comment by thomas-kl1** [comment]
It seems that it's already fixed by [MAGETWO-70580: Merged fixed](https://github.com/magento/magento2/commit/d2d82aca595f393cee43a46dc88520428fe4d4de)

**Comment by magento-engcom-team** [comment]
@mnjongerius Closing this issue per comment above.
@thomas-blackbird Thanks for pointing out
