### ISSUE TITLE
Error While Saving New Attribute For Product

### ISSUE THREAD

**Issue by jit17** [magento/magento2#3765]
## Steps to reproduce
1. Go to Stores >> Product 
2. Click On Add New Attribute
3. Add Label & Select Catalog input type as "Dropdown"
4. Select Value Required "YES"
5. Add Values for Default Store view & Admin in Manage Options (values of your attribute)
## Expected result

It should allow Add New Attribute in attribute records
## Actual result
1. Error message appears: "This is a required field".
2. [Screenshot, logs]
   ![2016-03-14_17-21-55](https://cloud.githubusercontent.com/assets/14104982/13743752/afa703d4-ea09-11e5-9b76-341dec667408.png)

**Comment by marvincaspar** [comment]
Same issue for customer address attributes

**Comment by Chouhada** [comment]
Currently also experiencing this on a clean install of 2.0.4

**Comment by piotrekkaminski** [comment]
I'm not able to reproduce it on 2.1RC. If you are still experiencing this issue in develop/2.1version please open a new ticket.
