### ISSUE TITLE
Private method

### ISSUE THREAD

**Issue by viet-pc** [magento/magento2#37658]
https://github.com/magento/magento2/blob/35e8e434be0b21072382b3f91c71678efc0242c1/lib/internal/Magento/Framework/Encryption/Encryptor.php#L247

I think we should change this to public method. Why private here?

**Comment by mrtuvn** [comment]
security purpose ? i think. What if can manipulate to hash string from outside class

**Comment by engcom-November** [comment]
Hello @viet-pc,

We have noticed this issue has not been updated since a long time. Hence closing the issue.
Feel free to reopen the issue if you face any issue.

Thank you.
