### ISSUE TITLE
product attributes are shown on Non assigned products

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#3766]
Hi,

On product attributes how come the one i create show the first option in the list and the attribute color made by magento is clear? So if i create a configurable product, its attaches size, numbers and letters to the product(see pic) How do i get them to be blank like color? All setting are the same as the color attribute. You should be able to remove an attribute from a product with the drop down?

![capture](https://cloud.githubusercontent.com/assets/16354206/13744479/5b1783ca-e9be-11e5-883f-18753281e78a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16354206/13744481/5e630fe0-e9be-11e5-9559-0e477fc76898.PNG)

 Thank You

**Comment by piotrekkaminski** [comment]
I'm sorry but I don't understand this report. Can you provide detailed steps how to reproduce?

**Comment by veloraven** [comment]
@zamboni084 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
