### ISSUE TITLE
PayPal Lib issue with default magento version M2.4.6

### ISSUE THREAD

**Issue by darshakkmagneto** [magento/magento2#37672]
### Preconditions and environment

- Magento version 2.4.6.
- Hi
I configured Paypal Payment method with M2.4.6 but getting error related to Paypal Lib "paypal/rest-api-sdk-php": "^1.14" it's given error related to depricated functions with PHP 8.1.

### Steps to reproduce

1. In PayPal express checkout module configure to sandbox details.
2. create an order for a subscription product in default magento2.4.6.
3. product add to cart.
4. go to the checkout page.
5. order create but showing review order and getting error PayPal express checkout not support.

### Expected result

  The order is placed successfully, the customer is not redirected to the success page. It turns to the order review page.

### Actual result

order placed but getting deprecated function error in PayPal library.

### Additional information

Hi
I configured Paypal Payment method with M2.4.6 but getting error related to Paypal Lib "paypal/rest-api-sdk-php": "^1.14" it's given error related to depricated functions with PHP 8.1.

### Release note

Hi
I configured Paypal Payment method with M2.4.6 but getting error related to Paypal Lib "paypal/rest-api-sdk-php": "^1.14" it's given error related to depricated functions with PHP 8.1.
Error: [2023-06-27T05:20:05.239048+00:00] main.CRITICAL: Exception message: Deprecated Functionality: Optional parameter $configs declared before required parameter $prefix is implicitly treated as a required parameter in /var/www/html/silhouette/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConfig.php on line 286

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @darshakkmagneto,

Thank you for reporting and collaboration.

As per Magento document https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/product-create.html?lang=en there is no such product like **subscription product** could you please provide more information how we can create using default magento.

Thanks.

**Comment by darshakkmagneto** [comment]
Hi @engcom-Bravo 
Thank you for your response.

We are using the amasty/module-recurring-payments-main module to apply the subscription to products and place orders using the recurring payment option of Magento.
Extension link: https://amasty.com/subscriptions-recurring-payments-for-magento-2.html

Here are the steps to configure the recurring payment  : 

After installing the module you can set a subscription option in the edit product.
Go to store config > Amasty extension > Subscriptions & Recurring Payments
Enter Client ID, and Client Secret and generate/enter Webhook Id in the Paypal section.

After the configuration, you can choose the subscription product from the frontend to place an order.

Thanks.

**Comment by engcom-Bravo** [comment]
HI @darshakkmagneto,

Thanks for your update.

“Amasty Extension” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
