### ISSUE TITLE
Unluckily I cannot receive Magento`s reset password email

### ISSUE THREAD

**Issue by principezinha** [magento/magento2#37673]
### Summary

Hi together,

Unfortunately I forgot my new password and didn`t save it in the password doc. So I pressed the button receive an email with to reset the password, which was yesterday.

I´m a total newbie to programming and I am just learning how to program html and css to make my shop better. It has an ecological aim.

Now the worst case has happened. 

As I haven`t got enough money to hire a developer I am the only one with a possible login. If I had known that!

Now I can only get in via the cloud terminal and I am very much afraid to destroy the shop.

Would anyone please help me out of this dilemma? Thank you so much in advance!!!

Thanks a lot,

Lisa

### Examples

![Uploading Bildschirm­foto 2023-06-27 um 12.28.12.png…]()

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
You can add a new admin user from command line, see option 4 in the guide below:

https://www.simicart.com/blog/reset-magento-admin-password/

**Comment by engcom-Bravo** [comment]
Hi @principezinha,

Thank you for reporting and collaboration.

@devchris79 Thanks for your contribution & collaboration over here.

@principezinha Kindly refer this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/admin.html regarding Create, edit, or unlock an administrator account and please let us know if you are still facing any issue.


We are able to get the password reset email successfully.

<img width="1327" alt="Screenshot 2023-06-27 at 4 44 20 PM" src="https://github.com/magento/magento2/assets/51680745/03ef0355-f9c2-44d6-8339-b3b25a3814a0">



Thanks.

**Comment by principezinha** [comment]
Thank you so much for your help!!! :o)

I just tried the address twice and extra checked it, but unfortunately it didn’t work. Now I’ll check your link. I hope I’ll get through it.

Tank you very much in advance and have a beautiful day

Bye,

Principezinha


Am 27.06.2023 um 13:16 schrieb Venkata Kumar Kuntumalla ***@***.***>:



Hi @principezinha<https://github.com/principezinha>,

Thank you for reporting and collaboration.

@devchris79<https://github.com/devchris79> Thanks for your contribution & collaboration over here.

@principezinha<https://github.com/principezinha> Kindly refer this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/admin.html regarding Create, edit, or unlock an administrator account and please let us know if you are still facing any issue.

We are able to get the password reset email successfully.

[Screenshot 2023-06-27 at 4 44 20 PM]<https://user-images.githubusercontent.com/51680745/249132406-03ef0355-f9c2-44d6-8339-b3b25a3814a0.png>

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @principezinha,

Thanks for your update.

Kindly refer either one of this document https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-admin.html


https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/admin.html



We are getting emails for reset password successfully.Please let us know if you are still facing any issue.



Thanks.

**Comment by engcom-Bravo** [comment]
Hi @principezinha,,

Please provide latest update on this comment https://github.com/magento/magento2/issues/37673#issuecomment-1610869713 if you are still facing any issue please let us know if you need more assistance on this.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @principezinha,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by principezinha** [comment]
Hi,
Thanks a lot. The issue is fixed now.

Dr. Lisa Jane Klaus-Klotz


https://books.google.de/books?id=95svDwAAQBAJ&printsec=frontcover&dq=Quantenphysik+und+Esoterik&hl=de&sa=X&redir_esc=y&pli=1#v=onepage&q=Quantenphysik%20und%20Esoterik&f=true













Am 17/07/2023 um 08:20 schrieb Venkata Kumar Kuntumalla ***@***.***>:

﻿

Closed #37673<https://github.com/magento/magento2/issues/37673> as completed.
