### ISSUE TITLE
Page title suffix is included in "title" tag but not in "meta title" tag in product pages

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37680]
### Preconditions and environment

- Magento version 2.4.6
- Anything else that would help a developer reproduce the bug
Setting Page title suffix in the theme configuration makes the system include the prefix in "title" tag but not in "meta title" tag for products. For standard pages and category pages it works correctly. Only in product pages is not included in meta title tag.

### Steps to reproduce

Go to Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix.
Then check standard pages (eg. home page, about us, contact us etc) and category pages and you will see that is correctly included both in title and meta title tags.
Now go to a product page. You will see that is included in the title tag but not in meta title tag.

### Expected result

Page Title Suffix should be included also in meta title tag in product pages.

### Actual result

Page Title Suffix is not included in meta title tag in product pages.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @cptX ,

verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-07-07 at 11 17 44 AM" src="https://github.com/magento/magento2/assets/60198592/c525761a-9c66-428c-b2c6-f77ef93e206e">
<img width="1512" alt="Screenshot 2023-07-07 at 11 17 57 AM" src="https://github.com/magento/magento2/assets/60198592/a843ca94-9973-4a85-bbcf-65861da38b68">
<img width="1512" alt="Screenshot 2023-07-07 at 11 18 07 AM" src="https://github.com/magento/magento2/assets/60198592/9c363331-4593-4fb4-823b-b80e3e0dc775">
<img width="1512" alt="Screenshot 2023-07-07 at 11 23 07 AM" src="https://github.com/magento/magento2/assets/60198592/f1cf9034-ba09-49bf-b30c-849f9cf7bf25">
<img width="1512" alt="Screenshot 2023-07-07 at 11 25 55 AM" src="https://github.com/magento/magento2/assets/60198592/e7a01345-9598-4142-bfc6-08f36ce2732a">

Step to reproduce:
1.Go to Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix.
2.Check standard pages like Home page and contact us and about as pages page title suffix with meta title present or not.

Page title suffix displaying all pages  including product pages.Kindly recheck the behaviour in 2.4-develop instance and Kindly let us know if we are missing anything!

Thanks

**Comment by cptX** [comment]
Hi @engcom-Dash,
I'm afraid you didn't understand the problem. The problem is in the meta tag title
![image](https://github.com/magento/magento2/assets/9040042/60bf5d78-a30e-4995-8cb2-d7a16d7c2c19)
It should include the title suffix in the meta tag title as it does in the title, but it's not and this happens only in the product pages. Categories and other pages work correctly!

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @cptX ,

Thanks for contribution and collaboration!
Kinldy refer the below screenshots which showing meta title tag added in all the pages including product page.
1.Product page 
<img width="1512" alt="Screenshot 2023-07-07 at 3 56 59 PM" src="https://github.com/magento/magento2/assets/60198592/1ae5b2a1-35ac-4094-9170-1fa18e0389a4">
2.Home Page
<img width="1512" alt="Screenshot 2023-07-07 at 3 51 54 PM" src="https://github.com/magento/magento2/assets/60198592/c5225dd4-91d0-4548-a0b2-43158ecd5e29">
3.About as page
<img width="1512" alt="Screenshot 2023-07-07 at 3 54 50 PM" src="https://github.com/magento/magento2/assets/60198592/2750f6a0-0c04-40d6-9252-2c2f178a23a1">
4.Contact us Page
<img width="1512" alt="Screenshot 2023-07-07 at 3 55 10 PM" src="https://github.com/magento/magento2/assets/60198592/71b9c186-1577-4fdd-b4c9-a97cd9351a67">

Thanks

**Comment by cptX** [comment]
Can you please check in a 2.4.6 production version? I have triple checked my system and indeed in product pages the meta name="title" tag doesn't include the suffix. All the rest work correctly!
I also checked in both store views greek and english.
You can check yourself here if you want: https://electrons.gr , just click on any product and check the meta tags!

**Comment by cptX** [comment]
@magento give me 2.4-develop instance

**Comment by cptX** [comment]
https://github.com/magento give me 2.4.6 instance

**Comment by cptX** [comment]
@magento give me 2.4.6 instance

**Comment by cptX** [comment]
I have tested also in the 2.4.6 magento intance provided above and it works as expected!
Can anybody give me a hint what to look to detect the problem on my production system?

**Comment by cptX** [comment]
@magento give me 2.4.6 instance

**Comment by cptX** [comment]
@engcom-Dash I finally managed to reproduce the problem in a vanilla 2.4.6 instance and it is indeed a bug!!!
If you add a custom meta title in the Search Engine Optimization settings of a product, the title will not get the Suffix. But if you leave this field empty it is autocompleted by the system with the product name/title so it includes it. The test instances we tried have this field empty in the settings so that's why they had the suffix. If you set the meta title in a product you will see that it doesn't get the suffix.
Please see here https://db3f91fb42a6887551daa9c8210b89ca.instances-prod.magento-community.engineering/joust-duffle-bag.html 

![image](https://github.com/magento/magento2/assets/9040042/ad1ced4a-7ee8-4ad7-b15b-01fd796ffea4)

**Comment by engcom-Dash** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment]
Hi @cptX ,
Verified the issue in 2.4.6  as per you last[comment](https://github.com/magento/magento2/issues/37680#issuecomment-1627094723)Kindly refer the screenshots and let us know if we are missing anything!
1.When we are leave empty  "meta title"  in Search engine optimization of product page
<img width="1512" alt="Screenshot 2023-07-10 at 1 49 41 PM" src="https://github.com/magento/magento2/assets/60198592/5b691469-8de1-4874-914c-7818b0e211e1">
<img width="1512" alt="Screenshot 2023-07-10 at 1 51 23 PM" src="https://github.com/magento/magento2/assets/60198592/7884ccec-60d4-4c4b-8742-f2499b97177c">
2.When we are add anything  "meta title" in Search engine optimization of product page
<img width="1512" alt="Screenshot 2023-07-10 at 1 50 13 PM" src="https://github.com/magento/magento2/assets/60198592/4fefef60-8f11-4fe4-bde6-3593ceee5b23">
<img width="1512" alt="Screenshot 2023-07-10 at 1 50 41 PM" src="https://github.com/magento/magento2/assets/60198592/5290f7fb-0016-4ce1-8553-ee3075b5e772">
3.When we are meta title suffix in Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix.
<img width="1512" alt="Screenshot 2023-07-10 at 1 53 56 PM" src="https://github.com/magento/magento2/assets/60198592/c943f2d5-f857-4850-b074-6c9a1c70e9b3">

Thanks!

**Comment by cptX** [comment]
@engcom-Dash To be honest I don't understand your test.
We try to prove here that the title suffix is not added on the meta name="title" when we add anything in the "meta title" in Search engine optimization of a product page.
So the test should have these steps:
1. Go to Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix. Please add it as following in order to make clear what is part of the suffix: | test_suffix
2. Then inspect the head of a product page that has nothing written in the "meta title" in Search engine optimization. You will see that the meta title will be exactly the same as the title of the page so it should include the suffix
3. Now edit this product and add the phrase "Custom meta title" in the "meta title" in Search engine optimization
4. Now inspect again the head of this product page and you will see that the meta title will show "Custom meta title" instead of "Custom meta title | test_suffix", so the suffix is not added as it should.
As I said I verified the issue in a vanilla 2.4.6 instance so I'm 100% the problem exists. It's just a matter for you to follow the same steps to reproduce it. Hope you will succeed.

**Comment by aasim110** [comment]
@magento I'm working on this
