### ISSUE TITLE
PayPal Payflow Pro not redirected to success page

### ISSUE THREAD

**Issue by chirag-taraviya** [magento/magento2#37695]
### Preconditions and environment

- Magento version -- 2.4.4

### Steps to reproduce

PayPal Payflow Pro setup 
Checkout with PayPal Payflow Pro credit card

screen loading not redirect to Successpage.

FYI response got from paypal success. 

### Expected result

Redirect to success page after successful payment

Attached log of paypal flow pro
![image](https://github.com/magento/magento2/assets/531597/91576319-6020-4ae6-89b5-a293ceb6e0da)

### Actual result

Loading screen and not redirect to success page even payment is successful 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thomas43222** [comment]
If you're experiencing issues with PayPal Payflow Pro not redirecting to the success page after a transaction, there could be a few possible causes and solutions to consider:

Configuration Issues: Double-check your integration setup and configuration for PayPal Payflow Pro. Ensure that you have provided the correct return URL or success page URL in your integration code or PayPal account settings. Verify that the integration parameters, such as the return URL or response handling, are set up correctly.

IPN (Instant Payment Notification) Configuration: PayPal Payflow Pro uses IPN to notify your system about transaction status updates. Make sure that your IPN settings are correctly configured. Check if you have set up the correct IPN URL in your PayPal account settings and that your server is able to receive and process IPN notifications.

Error Handling and Logging: Implement proper error handling and logging in your integration code. This can help you identify any errors or issues that might be occurring during the transaction process. Check your error logs to see if any errors are being logged related to the redirection to the success page [Water beads guns.](https://orbeezhit.com/)

**Comment by chirag-taraviya** [comment]
@thomas43222 we have production user account with PayPal Payflow Pro. I created new user for Test and Magento 2 development site. I am able to get proper response and status is approved. while I try test payment i got following error 
from url https://pilot-payflowlink.paypal.com/

Some required information is missing or incorrect. Please correct the fields below and try again.

      Error: Secure Token is not enabled. Please return to the website from where you started your purchase and try again.

Any Idea?

**Comment by chirag-taraviya** [comment]
Dose anyone have idea to solve this issue?

**Comment by engcom-Dash** [comment]
Hi @chirag-taraviya ,

Thanks for reporting this issue,

Verified the issue in latest stable instance 2.4.7-beta1 and the issue is not reproducible, kindly recheck the behaviour.

Steps to reproduce:
1.Install magento install
2.Setup Paypal Payflow pro payment in Sales>Payments methods>>Paypal payflow pro
3.Place the order with simple product in store front

Kindly refer the below screenshot:
<img width="642" alt="Screenshot 2023-07-20 at 6 31 57 PM" src="https://github.com/magento/magento2/assets/60198592/82b0d987-7dec-43b6-803e-e9fdefa2ac3b">
<img width="1056" alt="Screenshot 2023-07-20 at 6 35 27 PM" src="https://github.com/magento/magento2/assets/60198592/89c21b22-c18d-481f-9400-04bc5dd75e34">
We can place the order with Paypal pay-flow pro with latest magento instance.
Note:Kindly update your magento instance with latest one.

Thanks.

**Comment by HyflerSD** [comment]
Hello i'm on magento 2.4.7 and I still have customer who are having this issue of the spinning wheel. I looked at  alot of the logs and noticed very long response times. Could this be because of my server or is this to do with payflow? What happens in many of these cases is that the payflow response from the redirect is the last thing that happens, the subsequent charge request does not trigger.
`[2024-11-14T17:59:42.401747+00:00] main.DEBUG: array (
    'request' =>
array (
    'user' => '****',
    'vendor' => 'ntsecurity',
    'partner' => 'PayPal',
    'pwd' => '****',
    'verbosity' => 'HIGH',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'currency' => 'USD',
    'createsecuretoken' => 'Y',
    'securetokenid' => 'PTI3SjYfuFjTMcu2u3LKWmzq28IQRziw',
    'returnurl' => 'https://www.website.com/paypal/transparent/redirect/',
    'errorurl' => 'https://www.website.com/paypal/transparent/redirect/',
    'cancelurl' => 'https://www.website.com/paypal/transparent/redirect/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'User',
    'lastname' => 'Lastnallor',
    'street' => 'some street',
    'city' => 'Salinas',
    'state' => 'CA',
    'zip' => '93907',
    'country' => 'US',
    'email' => 'user@email.com',
    'shiptofirstname' => 'User',
    'shiptolastname' => 'Lastnallor',
    'shiptostreet' => 'some street',
    'shiptocity' => 'Salinas',
    'shiptostate' => 'CA',
    'shiptozip' => '93907',
    'shiptocountry' => 'US',
),
'result' =>
array (
    'result' => '0',
    'securetoken' => 'FqVKwTig2Ik6Sqzo7fjOe3AO4',
    'securetokenid' => 'PTI3SjYfuFjTMcu2u3LKWmzq28IQRziw',
    'respmsg' => 'Approved',
    'result_code' => '0',
),
) [] []
    [2024-11-14T17:59:50.036746+00:00] main.DEBUG: array (
    'PayPal PayflowPro redirect:' =>
array (
    'ZIP' => '93907',
    'BILLTOCOUNTRY' => 'US',
    'TRANSTIME' => '2024-11-14 09:59:46',
    'FIRSTNAME' => 'User',
    'EMAIL' => 'user@email.com',
    'ACCT' => '****',
    'STATETOSHIP' => 'CA',
    'RRN' => '9wcgrn8f',
    'SECURETOKENID' => 'PTI3SjYfuFjTMcu2u3LKWmzq28IQRziw',
    'AVSDATA' => 'YYY',
    'COUNTRY' => 'US',
    'EXPDATE' => '****',
    'LASTNAME' => 'Lastnallor',
    'VERIFICATIONID' => '9wcgrn8f',
    'SHIPTOZIP' => '93907',
    'BILLTOFIRSTNAME' => 'User',
    'ADDRESSTOSHIP' => 'some street',
    'CVV2MATCH' => 'X',
    'RESPTEXT' => 'verified',
    'SECURETOKEN' => 'FqVKwTig2Ik6Sqzo7fjOe3AO4',
    'SHIPTOCITY' => 'Salinas',
    'RESPMSG' => 'Verified',
    'BILLTOEMAIL' => 'user@email.com',
    'AMT' => '0.00',
    'TRANSACTIONID' => '9wcgrn8f',
    'NAME' => 'User Name',
    'SHIPTOCOUNTRY' => 'US',
    'BILLTONAME' => 'User Name',
    'ADDRESS' => 'some street   ',
    'PNREF' => 'BP3K9B4FDD6B',
    'BILLTOSTREET' => 'some street',
    'STATE' => 'CA',
    'AVSADDR' => 'Y',
    'BILLTOSTATE' => 'CA',
    'COUNTRYTOSHIP' => 'US',
    'AVSZIP' => 'Y',
    'BILLTOZIP' => '93907',
    'BILLTOCITY' => 'Salinas',
    'SHIPTOSTATE' => 'CA',
    'CITYTOSHIP' => 'Salinas',
    'NAMETOSHIP' => 'User Name',
    'SHIPTOSTREET' => 'some street',
    'PROCAVS' => 'Y',
    'CITY' => 'Salinas',
    'ZIPTOSHIP' => '93907',
    'BILLTOLASTNAME' => 'Lastnallor',
    'CARDTYPE' => '3',
    'RESULT' => '0',
),
) [] []
    [2024-11-14T17:59:51.206255+00:00] main.DEBUG: array (
    'PayPal PayflowPro response:' =>
array (
    'ZIP' => '93907',
    'BILLTOCOUNTRY' => 'US',
    'TRANSTIME' => '2024-11-14 09:59:46',
    'FIRSTNAME' => 'User',
    'EMAIL' => 'user@email.com',
    'ACCT' => '****',
    'STATETOSHIP' => 'CA',
    'RRN' => '9wcgrn8f',
    'SECURETOKENID' => 'PTI3SjYfuFjTMcu2u3LKWmzq28IQRziw',
    'AVSDATA' => 'YYY',
    'COUNTRY' => 'US',
    'EXPDATE' => '****',
    'LASTNAME' => 'Lastnallor',
    'VERIFICATIONID' => '9wcgrn8f',
    'SHIPTOZIP' => '93907',
    'BILLTOFIRSTNAME' => 'User',
    'ADDRESSTOSHIP' => 'some street',
    'CVV2MATCH' => 'X',
    'RESPTEXT' => 'verified',
    'SECURETOKEN' => 'FqVKwTig2Ik6Sqzo7fjOe3AO4',
    'SHIPTOCITY' => 'Salinas',
    'RESPMSG' => 'Verified',
    'BILLTOEMAIL' => 'user@email.com',
    'AMT' => '0.00',
    'TRANSACTIONID' => '9wcgrn8f',
    'NAME' => 'User Name',
    'SHIPTOCOUNTRY' => 'US',
    'BILLTONAME' => 'User Name',
    'ADDRESS' => 'some street',
    'PNREF' => 'BP3K9B4FDD6B',
    'BILLTOSTREET' => 'some street',
    'STATE' => 'CA',
    'AVSADDR' => 'Y',
    'BILLTOSTATE' => 'CA',
    'COUNTRYTOSHIP' => 'US',
    'AVSZIP' => 'Y',
    'BILLTOZIP' => '93907',
    'BILLTOCITY' => 'Salinas',
    'SHIPTOSTATE' => 'CA',
    'CITYTOSHIP' => 'Salinas',
    'NAMETOSHIP' => 'User Name',
    'SHIPTOSTREET' => 'some street',
    'PROCAVS' => 'Y',
    'CITY' => 'Salinas',
    'ZIPTOSHIP' => '93907',
    'BILLTOLASTNAME' => 'Lastnallor',
    'CARDTYPE' => '3',
    'RESULT' => '0',
),
) [] []
`
