### ISSUE TITLE
Issue with reindex for 'Catalog Search index' when bundle product exist.

### ISSUE THREAD

**Issue by mszumko** [magento/magento2#37694]
### Preconditions and environment

- Magento version: 2.4.6-p1
- Add Bundle product with 3-5 linked simple product.

### Steps to reproduce

1. Go to Catalog and create new bundle product.
2. Run in CLI action 'bin/magento indexer:reindex'.

### Expected result

Reindex end with success for all indexes.

### Actual result

For Catalog Search index error appear:
```
Catalog Search index process error during indexation process:
Magento\InventoryIndexer\Model\ResourceModel\GetStockItemData\Interceptor::execute(): Argument #1 ($sku) must be of type string, array given, called in /var/www/html/vendor/magento/module-inventory-elasticsearch/Plugin/Model/Adapter/BatchDataMapper/ProductDataMapperPlugin.php on line 74
```

### Additional information

Error is related to plugin:
vendor/magento/module-inventory-elasticsearch/Plugin/Model/Adapter/BatchDataMapper/ProductDataMapperPlugin.php

Function \Magento\InventoryIndexer\Model\ResourceModel\GetStockItemData::execute() in strict type mode require 'string' type, but for Bundle Product array is given.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mszumko,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Add Bundle product with 3-5 linked simple product.
- Go to Catalog and create new bundle product.
- Run in CLI action 'bin/magento indexer:reindex'.



![Bundleeee-Products-Inventory-Catalog-Magento-Admin](https://github.com/magento/magento2/assets/51680745/fd719bad-cdb8-4743-8e7a-a25f1361b009)


<img width="800" alt="Screenshot 2023-07-03 at 12 02 38 PM" src="https://github.com/magento/magento2/assets/51680745/fc2fdad4-4077-4820-a919-8b7920ef9030">



Reindex ended with success for all indexes.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by pawel989** [comment]
I have experienced the same issue. I believe it is directly related to the Magento 2 bundle with dynamic price enabled.

**Preconditions and environment**
Magento 2 Open Source version: 2.4.6-p1

**Steps to reproduce**
1. Add Bundle product with 1 option containing 3 items
2. Set the "Dynamic Price" to "Yes"
3. Set the "Dynamic Sku" to "Yes"
4. Run the CLI command 'bin/magento indexer:reindex'.

**Expected result**
Reindex end with success for all indexes.

**Actual result**
For Catalog Search index error appear:
`
Magento\InventoryIndexer\Model\ResourceModel\GetStockItemData\Interceptor::execute(): Argument #1 ($sku) must be of type string, array given, called in /var/www/html/vendor/magento/module-inventory-elasticsearch/Plugin/Model/Adapter/BatchDataMapper/ProductDataMapperPlugin.php on line 74
`

**Comment by mszumko** [comment]
Hi @engcom-Bravo .
After further investigation that bug is related to Amasty module Shopby. 

Thanks You for check in that issue.

**Comment by engcom-Bravo** [comment]
Hi @mszumko,

Thanks for your update.

“Amasty module Shopby” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by MartinVanVan** [comment]
@mszumko  can you tell me what the bug exactly is? I tried to comment out the plugins but still get this error.
