### ISSUE TITLE
Admin Session Lifetime not respected

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37698]
### Preconditions and environment

- Magento version 2.4.6

In Magento 2.4.6 Admin Session Lifetime in Configuration > Admin > security setting is not respected, leading to frequent data loss.
A lot of times while writing text for several minutes in categories or product pages the session ended logging me out and losing my work!
I have read several articles about this with unclear suggestions because the magento's system has changed several times.
One suggestion says to modify the parameter session.gc_maxlifetime = 1440 in php.ini but I don't like this suggestion because it affects the whole server, and I just need only the admin session to get affected.
Other suggestion for older magento versions suggests to modify the vendor/magento/module-encryption-key/etc/config.xml which is not existing in the newer versions.
Other suggestion says to configure magento to store sessions in file system, not in the database but then you need to configure a manual/cron method to clear sessions after some time...
Beyond this, I'm using Ubuntu server and I read here https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/storage/session-storage/sessions.html that "On some operating systems (Debian/Ubuntu), the default session.gc_probability directive is 0, which prevents the garbage collection handler from running."
So again I am left with the question is my system working correctly? I indeed have "session.gc_probability = 0" in my php.ini at the moment.

So at the moment I have been left without a correct solution, not knowing what to do and having lost real work and data several times due to unexpected timeout.
I'm opening here a new bug report as a previous report (https://github.com/magento/magento2/issues/10594) had been closed in my opinion without being correctly solved. I requested help there since 10/2022 but nobody responded.

I have now converted my system to store sessions in a folder but I don't know if I have to make a cron script to delete old sessions after some time. Also, as session management is such an important and complicated issue I don't want to mess with it and of course this not good for any user to mess, thus I'm opening this issue here again to urge some awareness for a complete and correct solution and of course a better documentation!

### Steps to reproduce

Go to Configuration > Admin > Security> Admin Session Lifetime and set 86400.
System ignores this setting and logs the admin out after 1440 seconds.

### Expected result

System should leave the admin logged in for the amount of time set in the corresponding setting.

### Actual result

System logs out the admin unexpectedly after a very short amount of time (1440secs) leading to data loss.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @cptX,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Go to Configuration > Admin > Security> Admin Session Lifetime and set 86400.
- System ignores this setting and logs the admin out after 1440 seconds.


It did not logout even after 1440 secs 

<img width="1512" alt="Screenshot 2023-07-31 at 6 43 52 PM (1)" src="https://github.com/magento/magento2/assets/51680745/dfdb4d08-7bc6-4b24-a1f2-ca39e305499c">


<img width="1512" alt="Screenshot 2023-07-31 at 7 18 52 PM (1)" src="https://github.com/magento/magento2/assets/51680745/c2a96692-33f8-4c0a-82f3-c8c8f44f86da">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @cptX,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by lily-PHP** [comment]
same issue problem with magento 2.4.6 .....

**Comment by antoniocarboni** [comment]
same issue :(

**Comment by GuuhBoss** [comment]
2.4.7-p2, error came to stay

**Comment by meihu** [comment]
Same issue with Magento 2.4.6-p8
