### ISSUE TITLE
Cannot create a custom LayoutProcessor

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3772]
Hello,

I don't know if this is a bug or not, but the fact is that I cannot create a LayoutProcessor. I have tried everything with no success.

This is the config.xml file for my custom module (I warn you that GITHUB has problems when trying to insert XML code)

`&lt;?xml version="1.0"?>
&lt;!--
/**
- Created by 
- Date: 16/02/2015
- Time: 16:15
  */
  -->
  &lt;config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
  &lt;preference for="Magento\Theme\Block\Html\Topmenu" type="Desytec\Theme\Block\DepasaTopmenu" />
  &lt;preference for="Magento\Checkout\Block\Checkout\LayoutProcessor" type="Desytec\Theme\Block\DepasaLayoutProcessor" />
  &lt;type name="Magento\Checkout\Block\Onepage">
      &lt;arguments>
          &lt;argument name="layoutProcessors" xsi:type="array">
              &lt;item name="addressFormAttributes" xsi:type="object">Desytec\Theme\Block\DepasaLayoutProcessor&lt;/item>
              &lt;item name="totalsSortOrder" xsi:type="object">Magento\Checkout\Block\Checkout\TotalsProcessor&lt;/item>
          &lt;/argument>
      &lt;/arguments>
  &lt;/type>  
  &lt;/config>
  `

I have copied that type node from Checkout module, but it did not work.

I am in development mode with disabled cache.

Regards
Jaime

**Comment by ishakhsuvarov** [comment]
@jaimestuardo Injecting a layout processor is done using following configuration inside module's `etc/frontend/di.xml`:

``` xml
...
<type name="Magento\Checkout\Block\Onepage">
    <arguments>
        <argument name="layoutProcessors" xsi:type="array">
            <!-- Replace with your layout processor's name and class implementing LayoutProcessorInterface -->
            <item name="customLayoutProcessorName" xsi:type="object">SampleModule\Checkout\Block\Checkout\LayoutProcessor</item>
        </argument>
    </arguments>
</type>
...
```

Also you may use technique described in the [Magento 2 Developer Documentation](http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_form.html#dynamically-defined-forms).

**Comment by ishakhsuvarov** [comment]
@jaimestuardo Closing this ticket for now, please reopen if you have any additional questions.

**Comment by emrahuyanik** [comment]
First of all, the file you mentioned is di.xml, not config.

Second, it should be under etc/frontend/, not etc folder.
