### ISSUE TITLE
Product Alert Email send for out of stock configurable product for MSI

### ISSUE THREAD

**Issue by sprajapat770** [magento/magento2#37738]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento 2.4.x

### Steps to reproduce

1. Enable product stock alert in admin configuration
2. setup email service
3. setup MSI
4. setup Configurable and children products
5. assign MSI to products
6. make default store source inventory out of stock and other source inventory in stock
7. on frontend open configurable product
8. send product stock alert
9. Either wait or send manual email with any other module help to get fast email.

### Expected result

Should not get product alert email when configurable product shows out of stock on pdp

### Actual result

Got email for out of stock configurable product due to MSI.

### Additional information

1. here in below file its just check product isSalable which wrong calculate configurable product salability 
   - vendor\magento\module-product-alert\Model\ProductSalability.php

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sprajapat770** [comment]
@engcom-Bravo any update on this issue?

**Comment by engcom-Bravo** [comment]
Hi @sprajapat770,

Thank you for reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/35602 regarding Product stock alert emails https://github.com/magento/magento2/issues/35602 this issue not fixed yet hence alert emails not triggered.in this case we cannot proceed further.

Kindly move onto this issue for latest updates / solutions on the same.

Thanks.
