### ISSUE TITLE
Missing table of created_at field when filtering BO orders grid by purchasing date

### ISSUE THREAD

**Issue by nicolaspernot** [magento/magento2#37734]
### Summary

When filtering the Order Grid in BO by Purchasing date, the request created don't prefix the created_at field by its table name, opening the way to some SQL ambiguity issues.

### Examples

On M2.4.5 when you filter orders in BO on a purchasing date, a condition is add to the where part of the request :
```
SELECT `main_table`.* FROM `sales_order_grid` AS `main_table` WHERE (`created_at` >= '2023-07-04 22:00:00')
```

The problem is the condition added don't specify on which table the `created_at` is. If for any reason, I try to join another table with a created_at field to this request, that will failed with this kind of mysql error :

```
Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT DISTINCT  `main_table`.*, IF(ss.entity_id IS NULL,0,1) AS `shipment_status` FROM `sales_order_grid` AS `main_table`
 LEFT JOIN `sales_shipment` AS `ss` ON ss.order_id = main_table.entity_id
 WHERE  (((`created_at` >= '2023-07-04 22:00:00'))) ORDER BY main_table.created_at DESC
 LIMIT 20 in /var/www/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109
```

The `created_at` condition is added is this plugin : [OrderGridCollectionFilter.php](https://github.com/magento/magento2/blob/2.4.5-p3/app/code/Magento/Sales/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php).

At some point, if I dig into history of this class, the dev thought about to prefix the field by the table name (check this [getFilterFieldsMap](https://github.com/magento/magento2/blob/032f409319dc743136b2087b46008f3523b1b47f/app/code/Magento/Sales/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php#L80) function).

But since he removed it entirely in [this commit](https://github.com/magento/magento2/commit/39121b076ceb2ebc0d4f2d223655e376ced7fe15). I don't know why...

By the way I'm not really comfortable with the fact that if indeed we want to add a created_at filter the plugin make the change and return without no call to $proceed. Meaning that breaks all the chain.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @nicolaspernot,

Thanks for the report and collaboration!

We need some more information in order to proceed with this issue. Please provide us the use case and steps to reproduce with the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @nicolaspernot,

We have noticed that this issue has not been updated for a period of long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by hans2103** [comment]
I've stumbled upon the same issue and solved it using this answer on StackExchange
https://magento.stackexchange.com/questions/190580/zend-db-statement-exception-sqlstate23000-integrity-constraint-violation
