### ISSUE TITLE
Paypal express review rendering of tax Block fails.

### ISSUE THREAD

**Issue by nobodypb** [magento/magento2#3774]
Everytime the review page trys to render it fails because in

```
// Line 42  Magento_Tax::frontend/templates/checkout/tax.phtml
<?php foreach (unserialize($block->getTotal()->getFullInfo()) as $info): ?>
```

getFullInfo() actually returns an unserialized array.

I'm running Magento 2.0.2 on php7.0.4

**Comment by mikeweis** [comment]
I was able to re-create this bug on our mainline with the following configuration settings:
- Tax Config
  - Shopping Cart Display Settings - Display Full Tax Summary - Yes
- Tax Rules
  - have at least one

Thanks for submitting this bug. I have created internal ticket MAGETWO-50557 to track this issue.

**Comment by mikeweis** [comment]
This issue has been resolved and merged to develop. Feel free to let us know if you encounter any other issues.
