### ISSUE TITLE
Google Analytics CSP Error https://region1.analytics.google.com

### ISSUE THREAD

**Issue by timpea-splat** [magento/magento2#37750]
### Preconditions and environment

- Magento version
2.4.6-p1

### Steps to reproduce

Enable Google Analytics
View Website from the EU - Inspect and view CSP console errors.

### Expected result

No CSP errors

### Actual result

[Report Only] Refused to connect to 'https://region1.analytics.google.com/g/collect?v=28****** REMOVED ********' because it violates the following Content Security Policy directive: "connect-src www.google-analytics.com www.googleadservices.com analytics.google.com www.googletagmanager.com vimeo.com www.sandbox.paypal.com www.paypalobjects.com www.paypal.com pilot-payflowlink.paypal.com *.ideal-postcodes.co.uk *.doubleclick.net *.google-analytics.com 'self' 'unsafe-inline'".

### Additional information

See update from Google:
https://support.google.com/analytics/answer/12017362?sjid=7210281846540305633-EU

> EU data is collected in the EU
> Google Analytics 4 collects all data from EU-based devices (based on IP-geo lookup) through domains and on servers based in the EU before [forwarding traffic to Analytics servers for processing](https://support.google.com/analytics/answer/11598602).
> 
> If you currently use a [Content Security Policy (CSP)](https://developers.google.com/tag-platform/tag-manager/web/csp), update your configurations (img-src and connection-src directives) to allow the following domains used by Analytics:
> 
> *.google-analytics.com
> *.analytics.google.com

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @timpea-splat .
Thanks for reporting and collaboration. Tested google analytics CSP errors for EU region and the able to reproduce the issue. Please refer the screenshot below.

<img width="1440" alt="Screenshot 2023-10-27 at 3 02 09 PM" src="https://github.com/magento/magento2/assets/60198592/b8ebb6f0-1072-408c-949c-a5c201adcab4">

**Comment by apedicdev** [comment]
Hi, I'm experiencing this issue on 2.4.7-p1 too. is there any update?

**Comment by apedicdev** [comment]
@magento I am working on this

**Comment by apedicdev** [comment]
PR open https://github.com/magento/magento2/pull/38991
