### ISSUE TITLE
When importing configurable product it does not assigned the simple products with it

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#3775]
Steps to reproduce
1. Importing Configurable Products

Expected result
1. Configurable product added with its assigned Configurations

Actual result
1. Configurable product added (No Configurations)
2. Simple products added
3. and you can't add them manually because the link only shows up if you have associated products
   ![123](https://cloud.githubusercontent.com/assets/16354206/13756902/705f7d48-e9f8-11e5-9e3f-e36c048c2487.PNG)

Thank You

**Comment by piotrekkaminski** [comment]
@ilol can you review?

**Comment by wert2all** [comment]
@zamboni084 Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
