### ISSUE TITLE
Db prefix breaks 2.4.7-beta1 install

### ISSUE THREAD

**Issue by sta1r** [magento/magento2#37756]
### Preconditions and environment

- 2.4.7-beta1
- PHP 8.2

### Steps to reproduce

1. 
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.4.7-beta1 magento-cc-2.4.7
```
2.
```
bin/magento setup:install \
--use-secure=1 \
--use-secure-admin=1 \
--base-url=http://m247cc.am:8890 \
--base-url-secure=https://m247cc.am:8890 \
--db-host=localhost \
--db-name=commerce247 \
--db-password=root \
--db-prefix=foo_ \
--backend-frontname=admin \
--admin-firstname=Foo \
--admin-lastname=Bar \
--admin-email=admin@foo.com \
--admin-user=admin \
--admin-password=password \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1 
```

### Expected result

- Magento installs correctly

### Actual result

```
Starting Magento installation:
File permissions check...
[Progress: 1 / 1911]
Required extensions check...
[Progress: 2 / 1911]
Enabling Maintenance Mode...
[Progress: 3 / 1911]
Installing deployment configuration...
[Progress: 4 / 1911]
Installing database schema:
Schema creation/updates:

There is an error in /Sites/magento-cc-2.4.7/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php at line: 253
Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder::processTable(): Return value must be of type Magento\Framework\Setup\Declaration\Schema\Dto\Table, bool returned#0 /Sites/magento-cc-2.4.7/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php(150): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->processTable(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema), Array)
#1 /Sites/magento-cc-2.4.7/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(78): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
#2 /Sites/magento-cc-2.4.7/setup/src/Magento/Setup/Model/DeclarationInstaller.php(57): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDeclarationConfig()
#3 /Sites/magento-cc-2.4.7/setup/src/Magento/Setup/Model/Installer.php(849): Magento\Setup\Model\DeclarationInstaller->installSchema(Array)
#4 /Sites/magento-cc-2.4.7/setup/src/Magento/Setup/Model/Installer.php(897): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
#5 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#6 /Sites/magento-cc-2.4.7/setup/src/Magento/Setup/Model/Installer.php(388): call_user_func_array(Array, Array)
#7 /Sites/magento-cc-2.4.7/setup/src/Magento/Setup/Console/Command/InstallCommand.php(237): Magento\Setup\Model\Installer->install(Array)
#8 /Sites/magento-cc-2.4.7/vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Sites/magento-cc-2.4.7/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Sites/magento-cc-2.4.7/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Sites/magento-cc-2.4.7/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Sites/magento-cc-2.4.7/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Sites/magento-cc-2.4.7/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}
```

### Additional information

Install works fine without supplying a table prefix.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @sta1r ,

Verified the issue in 2.4.7-beta1 magento instance and the issue is not reproducible,Kindly recheck the behaviour.
As per the [Dev Docs](https://devdocs.magento.com/guides/v2.3/install-gde/composer.html) we are 2.4.7-beta1 enterprise edition with DB prefix and its installed successfully, refer the below screenshots:
<img width="1512" alt="Screenshot 2023-07-31 at 5 50 58 PM" src="https://github.com/magento/magento2/assets/60198592/09f85836-67b8-4fa3-ae71-11535038bfb5">

**Comment by sta1r** [comment]
Strange, it works now. Sorry - I don't know what the problem was then.

**Comment by River-12** [comment]
The error was again throws in 2.4.7-beta2 

![image](https://github.com/magento/magento2/assets/147495025/d5e8c633-aa61-4dea-bd3f-da51d696bf03)

**Comment by monteshot** [comment]
I encountered the same issue described above while developing a custom shipping integration.
The main issue is the length of the table name (Max 64).
For instance:
was
perspective_novaposhta_counterparty_addresses_doors
added the "_contact_person"
And M2 handles names as 
perspective_novaposhta_counterparty_contact_person_addresses_doo
but not as described in the DB schema.
![image](https://github.com/magento/magento2/assets/2836146/8ffd8297-8db0-4c2f-b898-f9c3eba96e5b)

@engcom-Hotel @engcom-Dash I think we need to reopen the task to clarify the exception message. What do you think about it?

FYI
@River-12 @sta1r

**Comment by monteshot** [comment]
Affects all version of M2 with db_schema.xml

**Comment by nomis11uk** [comment]
We are also getting the same error trying to update from 2.4.6-p4 to 2.4.7. Does any know how to fix?

**Comment by nomis11uk** [comment]
@monteshot @sta1r did you find a fix for the issue?

**Comment by monteshot** [comment]
@nomis11uk I shortened the table name.

**Comment by devchris79** [comment]
Magento 2.4.7 adds a new table called `payment_services_order_status_data_production_submitted_hash` its a bit long at 60 characters, after our prefix of 4 characters and and underscore was added it took the length to 65 and beyond Mariadb limit of 64.

So anyone with a prefix of 5 or more characters including the underscore will see this error.

I reduced the prefix size and it thn installed fine.

**Comment by tibzoy** [comment]
In my case, installation went well using --db-prefix=m_. Hope that works for you too.

**Comment by devchris79** [comment]
This has now been fixed as pointed out by @chernenm on another thread:

> The fix for this issue has just been released in scope of a new Payment Services package version 2.5.0, the package is available at repo.magento.com
If you are already on 2.4.7 please run
composer require magento/payment-services:2.5.0 --with-all-dependencies to get the latest version.
If you are upgrading to 2.4.7 the latest package will be used automatically.

The [new version](https://experienceleague.adobe.com/en/docs/commerce-merchant-services/payment-services/release-notes) "supports [Adobe Commerce guidelines for the --db-prefix parameter](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/advanced)"
