### ISSUE TITLE
PayPal recurring payment issue with amasty subscription extension in Magento 2.4.6

### ISSUE THREAD

**Issue by darshakkmagneto** [magento/magento2#37754]
### Summary

**Preconditions and environment:**

- Magento 2.4.6
- Amasty Subscriptions & Recurring Payments Extension

**Issue:** 

When I'm trying to purchase subscription products with the Paypal payment method, I'm facing the below error on the checkout page. 
**Error:** We can't process express checkout approval.
The order is placed but the checkout page keeps loading with the error and on the admin side the order approval status is : **Disapproved**

**Steps to reproduce the issue:** 

- Enable the subscription products by editing the products and setting the subscription options.
- Configure the recurring payment in store configuration > Amasty extension > Subscriptions & Recurring Payments.
- Also configure the Paypal payment option in the sales > Payment Methods  > Paypal Configure.
- Select any subscription product and try to place an order using PayPal.

### Examples

**Payment logs :** 

[2023-07-12T11:46:24.247654+00:00] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'SetExpressCheckout' => 
  array (
    'PAYMENTACTION' => 'Sale',
    'AMT' => '805.00',
    'CURRENCYCODE' => 'USD',
    'RETURNURL' => 'http://silhouetteamerica.local/paypal/express/return/',
    'CANCELURL' => 'http://silhouetteamerica.local/paypal/express/cancel/',
    'INVNUM' => '000000129',
    'SOLUTIONTYPE' => 'Mark',
    'GIROPAYCANCELURL' => 'http://silhouetteamerica.local/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'http://silhouetteamerica.local/checkout/onepage/success/',
    'BANKTXNPENDINGURL' => 'http://silhouetteamerica.local/checkout/onepage/success/',
    'SHIPPINGAMT' => '5.00',
    'ITEMAMT' => '800.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'Test subscription',
    'L_QTY0' => 1,
    'L_AMT0' => '1000.00',
    'L_NUMBER1' => NULL,
    'L_NAME1' => 'Discount',
    'L_QTY1' => 1,
    'L_AMT1' => '-200.00',
    'BUSINESS' => 'Megneto',
    'NOTETEXT' => NULL,
    'EMAIL' => 'darshak@magneto.com',
    'FIRSTNAME' => 'Darshak',
    'LASTNAME' => 'Magneto',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'US',
    'STATE' => 'FL',
    'CITY' => 'Florida',
    'STREET' => '1498 Rockford Mountain Lane',
    'ZIP' => '54901',
    'PHONENUM' => '99878987678',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOSTATE' => 'FL',
    'SHIPTOCITY' => 'Florida',
    'SHIPTOSTREET' => '1498 Rockford Mountain Lane',
    'SHIPTOZIP' => '54901',
    'SHIPTOPHONENUM' => '99878987678',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'Darshak Magneto',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_2_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-48T4608148167813U',
    'TIMESTAMP' => '2023-07-12T11:46:24Z',
    'CORRELATIONID' => '8d39538fee2f0',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '58089711',
  ),
) [] []
[2023-07-12T11:47:06.108843+00:00] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'GetExpressCheckoutDetails' => 
  array (
    'TOKEN' => 'EC-48T4608148167813U',
    'METHOD' => 'GetExpressCheckoutDetails',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_2_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-48T4608148167813U',
    'BILLINGAGREEMENTACCEPTEDSTATUS' => '0',
    'CHECKOUTSTATUS' => 'PaymentActionNotInitiated',
    'TIMESTAMP' => '2023-07-12T11:47:05Z',
    'CORRELATIONID' => '2d664100966af',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '58089711',
    'EMAIL' => 'sb-usx8p26354641@personal.example.com',
    'PAYERID' => '7XUX22Y2MFM5S',
    'PAYERSTATUS' => 'verified',
    'FIRSTNAME' => 'John',
    'LASTNAME' => 'Doe',
    'COUNTRYCODE' => 'US',
    'SHIPTONAME' => 'Darshak Magneto',
    'SHIPTOSTREET' => '1498 Rockford Mountain Lane',
    'SHIPTOCITY' => 'Florida',
    'SHIPTOSTATE' => 'FL',
    'SHIPTOZIP' => '54901',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOPHONENUM' => '99878987678',
    'SHIPTOCOUNTRYNAME' => 'United States',
    'ADDRESSSTATUS' => 'Confirmed',
    'CURRENCYCODE' => 'USD',
    'AMT' => '805.00',
    'ITEMAMT' => '800.00',
    'SHIPPINGAMT' => '5.00',
    'HANDLINGAMT' => '0.00',
    'TAXAMT' => '0.00',
    'INVNUM' => '000000129',
    'INSURANCEAMT' => '0.00',
    'SHIPDISCAMT' => '0.00',
    'INSURANCEOPTIONOFFERED' => 'false',
    'L_NAME0' => 'Test subscription',
    'L_NAME1' => 'Discount',
    'L_QTY0' => '1',
    'L_QTY1' => '1',
    'L_TAXAMT0' => '0.00',
    'L_TAXAMT1' => '0.00',
    'L_AMT0' => '1000.00',
    'L_AMT1' => '-200.00',
    'PAYMENTREQUEST_0_CURRENCYCODE' => 'USD',
    'PAYMENTREQUEST_0_AMT' => '805.00',
    'PAYMENTREQUEST_0_ITEMAMT' => '800.00',
    'PAYMENTREQUEST_0_SHIPPINGAMT' => '5.00',
    'PAYMENTREQUEST_0_HANDLINGAMT' => '0.00',
    'PAYMENTREQUEST_0_TAXAMT' => '0.00',
    'PAYMENTREQUEST_0_INVNUM' => '000000129',
    'PAYMENTREQUEST_0_INSURANCEAMT' => '0.00',
    'PAYMENTREQUEST_0_SHIPDISCAMT' => '0.00',
    'PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID' => 'sb-khzsh1276109@business.example.com',
    'PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED' => 'false',
    'PAYMENTREQUEST_0_SHIPTONAME' => 'Darshak Magneto',
    'PAYMENTREQUEST_0_SHIPTOSTREET' => '1498 Rockford Mountain Lane',
    'PAYMENTREQUEST_0_SHIPTOCITY' => 'Florida',
    'PAYMENTREQUEST_0_SHIPTOSTATE' => 'FL',
    'PAYMENTREQUEST_0_SHIPTOZIP' => '54901',
    'PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE' => 'US',
    'PAYMENTREQUEST_0_SHIPTOPHONENUM' => '99878987678',
    'PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME' => 'United States',
    'PAYMENTREQUEST_0_ADDRESSSTATUS' => 'Confirmed',
    'L_PAYMENTREQUEST_0_NAME0' => 'Test subscription',
    'L_PAYMENTREQUEST_0_NAME1' => 'Discount',
    'L_PAYMENTREQUEST_0_QTY0' => '1',
    'L_PAYMENTREQUEST_0_QTY1' => '1',
    'L_PAYMENTREQUEST_0_TAXAMT0' => '0.00',
    'L_PAYMENTREQUEST_0_TAXAMT1' => '0.00',
    'L_PAYMENTREQUEST_0_AMT0' => '1000.00',
    'L_PAYMENTREQUEST_0_AMT1' => '-200.00',
    'PAYMENTREQUESTINFO_0_ERRORCODE' => '0',
  ),
) [] []
[2023-07-12T11:47:10.212050+00:00] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'DoExpressCheckoutPayment' => 
  array (
    'TOKEN' => 'EC-48T4608148167813U',
    'PAYERID' => '7XUX22Y2MFM5S',
    'PAYMENTACTION' => 'Sale',
    'AMT' => '805.00',
    'CURRENCYCODE' => 'USD',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'NOTIFYURL' => 'http://silhouetteamerica.local/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'SHIPPINGAMT' => '5.00',
    'ITEMAMT' => '800.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'Test subscription',
    'L_QTY0' => 1,
    'L_AMT0' => '1000.00',
    'L_NUMBER1' => NULL,
    'L_NAME1' => 'Discount',
    'L_QTY1' => 1,
    'L_AMT1' => '-200.00',
    'BUSINESS' => 'Megneto',
    'EMAIL' => 'darshak@magneto.com',
    'FIRSTNAME' => 'Darshak',
    'LASTNAME' => 'Magneto',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'US',
    'STATE' => 'FL',
    'CITY' => 'Florida',
    'STREET' => '1498 Rockford Mountain Lane',
    'ZIP' => '54901',
    'PHONENUM' => '99878987678',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOSTATE' => 'FL',
    'SHIPTOCITY' => 'Florida',
    'SHIPTOSTREET' => '1498 Rockford Mountain Lane',
    'SHIPTOZIP' => '54901',
    'SHIPTOPHONENUM' => '99878987678',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'Darshak Magneto',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-48T4608148167813U',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2023-07-12T11:47:10Z',
    'CORRELATIONID' => '3416a35123ff0',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '58089711',
    'TRANSACTIONID' => '0NV47056G03626903',
    'TRANSACTIONTYPE' => 'cart',
    'PAYMENTTYPE' => 'instant',
    'ORDERTIME' => '2023-07-12T11:47:09Z',
    'AMT' => '805.00',
    'FEEAMT' => '28.58',
    'TAXAMT' => '0.00',
    'CURRENCYCODE' => 'USD',
    'PAYMENTSTATUS' => 'Completed',
    'PENDINGREASON' => 'None',
    'REASONCODE' => 'None',
    'PROTECTIONELIGIBILITY' => 'Eligible',
    'INSURANCEOPTIONSELECTED' => 'false',
    'SHIPPINGOPTIONISDEFAULT' => 'false',
    'PAYMENTINFO_0_TRANSACTIONID' => '0NV47056G03626903',
    'PAYMENTINFO_0_TRANSACTIONTYPE' => 'cart',
    'PAYMENTINFO_0_PAYMENTTYPE' => 'instant',
    'PAYMENTINFO_0_ORDERTIME' => '2023-07-12T11:47:09Z',
    'PAYMENTINFO_0_AMT' => '805.00',
    'PAYMENTINFO_0_FEEAMT' => '28.58',
    'PAYMENTINFO_0_TAXAMT' => '0.00',
    'PAYMENTINFO_0_CURRENCYCODE' => 'USD',
    'PAYMENTINFO_0_PAYMENTSTATUS' => 'Completed',
    'PAYMENTINFO_0_PENDINGREASON' => 'None',
    'PAYMENTINFO_0_REASONCODE' => 'None',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITY' => 'Eligible',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE' => 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    'PAYMENTINFO_0_SELLERPAYPALACCOUNTID' => 'sb-khzsh1276109@business.example.com',
    'PAYMENTINFO_0_SECUREMERCHANTACCOUNTID' => 'N6FUK95TCLYL8',
    'PAYMENTINFO_0_ERRORCODE' => '0',
    'PAYMENTINFO_0_ACK' => 'Success',
  ),
) 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @darshakkmagneto,

Thank you for reporting and collaboration.

“Amasty Extension” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
