### ISSUE TITLE
Composer error when updating Magento 2.4.6 -> 2.4.6-p1

### ISSUE THREAD

**Issue by sparkable-agency** [magento/magento2#37763]
### Preconditions and environment

- Magento 2.4.6-p1
- Updating from Magento 2.4.6

### Steps to reproduce

1. Change line in composer.json to "magento/product-community-edition": "2.4.6-p1"
2. Run composer install

### Expected result

Magento 2 is updated to 2.4.6-p1 

### Actual result

Composer gives the following error:

```
composer update 
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.6-p1 -> satisfiable by magento/product-community-edition[2.4.6-p1].
    - magento/product-community-edition 2.4.6-p1 requires blueimp/jquery-file-upload 5.6.14 -> found blueimp/jquery-file-upload[dev-master, 8.8.5, 8.8.7, 8.9.0, 9.0.0, ..., v9.34.0, v10.0.0, ..., v10.32.0] but it does not match the constraint.
```

When i check the available versions of the "blueimp/jquery-file-upload" i cannot find the version needed by Magento.

```
composer show -a blueimp/jquery-file-upload|grep versions
versions : dev-master, v10.32.0, v10.31.0, v10.30.1, v10.30.0, v10.29.0, v10.28.0, v10.27.0, v10.26.0, v10.25.0, v10.24.0, v10.23.0, v10.22.0, v10.21.0, v10.20.0, v10.19.0, v10.18.0, v10.17.0, v10.16.0, v10.15.0, v10.14.0, v10.13.1, v10.13.0, v10.12.0, v10.11.0, v10.10.0, v10.9.0, v10.8.0, v10.7.0, v10.6.0, v10.5.0, v10.4.0, v10.3.0, v10.2.0, v10.1.0, v10.0.0, v9.34.0, v9.33.0, v9.32.0, v9.31.0, v9.30.0, v9.29.0, v9.28.0, v9.27.0, v9.26.0, v9.25.1, v9.25.0, v9.24.1, v9.24.0, v9.23.0, v9.22.2, v9.22.1, v9.22.0, v9.21.0, v9.20.0, v9.19.3, v9.19.2, v9.19.1, v9.19.0, v9.18.0, v9.17.0, v9.16.0, v9.15.0, v9.14.2, v9.14.1, v9.14.0, v9.13.1, v9.13.0, v9.12.6, 9.12.5, 9.12.4, 9.12.3, 9.12.2, 9.12.1, 9.12.0, 9.11.2, 9.11.1, 9.11.0, 9.10.7, 9.10.6, 9.10.5, 9.10.4, 9.10.3, 9.10.2, 9.10.1, 9.10.0, 9.9.4, 9.9.3, 9.9.2, 9.9.1, 9.9.0, 9.8.1, 9.8.0, 9.7.2, 9.7.1, 9.7.0, 9.6.0, 9.5.8, 9.5.7, 9.5.6, 9.5.5, 9.5.4, 9.5.3, 9.5.2, 9.5.1, 9.5.0, 9.4.2, 9.4.1, 9.4.0, 9.3.0, 9.2.1, 9.2.0, 9.1.0, 9.0.2, 9.0.1, 9.0.0, 8.9.0, 8.8.7, 8.8.5
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Hmm, that's strange, Magento doesn't require `blueimp/jquery-file-upload`, however, `magento/magento2-base` defines itself as a replacement of `blueimp/jquery-file-upload`, no idea why though. But this shouldn't cause your behavior.

Can you run `composer why blueimp/jquery-file-upload` and see what that outputs?
Over here it says:

```
$ composer why blueimp/jquery-file-upload
magento/magento2-base 2.4.6-p1 replaces blueimp/jquery-file-upload (5.6.14)
```

**Comment by engcom-Dash** [comment]
Hi @gerrits-ecommerce ,

Thanks for reporting this issue,

Verified the issue in 2.4.6 magento instance and the issue is not reproducible,Kindly recheck the behaviour.

Steps to reproduce:
1.Install 2.4.6- magento instance
2.Upgrade the instance from 2.4.6 to 2.4.6-p1 as per [DevDocs](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)

Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-07-20 at 6 00 19 PM" src="https://github.com/magento/magento2/assets/60198592/277fdc05-c9e8-423c-9889-e7705fe61f15">
<img width="1512" alt="Screenshot 2023-07-20 at 6 09 58 PM" src="https://github.com/magento/magento2/assets/60198592/e2f4c542-9e1d-4d14-a018-869299d5d255">
<img width="1512" alt="Screenshot 2023-07-20 at 6 10 20 PM" src="https://github.com/magento/magento2/assets/60198592/0e734043-9cf2-4f48-9b96-6c762cda2598">

We can successfully upgrading from 2.4.6 to 2.4.6-p1.

Thanks.

**Comment by devchris79** [comment]
@hostep When I run the composer why command I get the same as you from 2.4.6:
```
composer why blueimp/jquery-file-upload
magento/magento2-base 2.4.6 replaces blueimp/jquery-file-upload (5.6.14)
```
However if I run the grep command below from our installation root it results in lots of references: 

`grep -Rnwl './' -e "blueimp/jquery-file-upload"
`

So I am a bit lost if its used or not....

**Comment by gerrits-ecommerce** [comment]
See my screenshots below. I am trying to update from 2.4.6 to 2.4.6-p1 (composer.json).

![image](https://github.com/magento/magento2/assets/31535836/503abf3d-6b0e-4e4f-baa2-36ecd82b9681)

When i run:
`composer why blueimp/jquery-file-upload`

you can see in my screenshot above that i have an extra require from magento.

**Comment by hostep** [comment]
@gerrits-ecommerce: that's extremely weird. You are sure your `magento/product-community-edition` package comes from repo.magento.com and not from some other (possibly malicious) repository?

Also, can you search your `composer.lock` file for anything that mentions `blueimp/jquery-file-upload` ?

For example, like this:
```
$ grep -B40 'blueimp/jquery-file-upload' composer.lock
            "time": "2022-12-01T15:21:32+00:00"
        },
        {
            "name": "magento/magento2-base",
            "version": "2.4.6-p1",
            "dist": {
                "type": "zip",
                "url": "https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.4.6.0-patch1.zip",
                "shasum": "d4c0a28a3a7be0aa0ce5985ee608d2da07a9ec56"
            },
            "require": {
                "composer/composer": "^2.0, !=2.2.16",
                "ext-intl": "*",
                "ext-mbstring": "*",
                "laminas/laminas-code": "^4.5",
                "laminas/laminas-di": "^3.7",
                "laminas/laminas-eventmanager": "^3.5",
                "laminas/laminas-http": "^2.15",
                "laminas/laminas-i18n": "^2.17",
                "laminas/laminas-modulemanager": "^2.11",
                "laminas/laminas-mvc": "^3.3",
                "laminas/laminas-servicemanager": "^3.16",
                "laminas/laminas-soap": "^2.10",
                "laminas/laminas-stdlib": "^3.11",
                "laminas/laminas-uri": "^2.9",
                "laminas/laminas-validator": "^2.23",
                "magento/composer": "^1.9.0",
                "magento/magento-composer-installer": "*",
                "monolog/monolog": "^2.7",
                "pelago/emogrifier": "^7.0",
                "php": "~8.1.0||~8.2.0",
                "phpseclib/phpseclib": "^3.0",
                "symfony/console": "^5.4",
                "tedivm/jshrink": "^1.4",
                "tubalmartin/cssmin": "^4.1"
            },
            "conflict": {
                "gene/bluefoot": "*"
            },
            "replace": {
                "blueimp/jquery-file-upload": "5.6.14",
                "components/jquery": "1.11.0",
                "components/jqueryui": "1.10.4",
                "tinymce/tinymce": "3.4.7",
                "trentrichardson/jquery-timepicker-addon": "1.4.3",
                "twbs/bootstrap": "3.1.0"
            },
            "type": "magento2-component",
            "extra": {
                "chmod": [
                    {
                        "mask": "0755",
                        "path": "bin/magento"
                    }
                ],
                "component_paths": {
                    "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",

```

**Comment by gerrits-ecommerce** [comment]
@hostep I have checked the repo it was installed from, and this was the problem. I have now installed it from repo.magento.com and everything works as expected.

Thanks for your help :)
