### ISSUE TITLE
product export displays categories as text

### ISSUE THREAD

**Issue by justinblayney** [magento/magento2#3776]
I am writing scripts whereby I can constantly update my internal product database with he magento database.

Category tables path are imported and export as so

*_1/3/46/7777  *_
using their IDs

When exporting Products, Categories are displayed as

**Vehicle Type/Product Type/AC Hoses,Vehicle Type/Car & Light Truck/Honda/Honda CIVIC**
using their actual names

Why in the world are you not using the IDs that you are using in the category table? (have you all lost your minds??, please go back to programming 101 class). Sorry for my little rant, but it had to be said.

The main issue here is that www ever need to fix a typo to change a category name we will also need to re-import all the products (25000 in our case)

Is there some work around so I don't ever need to find myself in this situation?
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by piotrekkaminski** [comment]
@ilol  please look into it

**Comment by veloraven** [comment]
@justinblayney thank you for your report.
Is this issue still actual?
If it is, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result, not just write your description above the template.
Please, also provide the used Magento version.
If it is not, please close the issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
