### ISSUE TITLE
SMTP Host and Port are not used even though config settings available.

### ISSUE THREAD

**Issue by p3mbo** [magento/magento2#3777]
In Magento1 when running under Windows you could set the SMTP Host and SMTP Port.

In Magento 1 this is achieved by code similar to the following:

```
ini_set('SMTP', Mage::getStoreConfig('system/smtp/host'));
ini_set('smtp_port', Mage::getStoreConfig('system/smtp/port'));
```

In Magento 2 there is no reference in the source-code anywhere to `system/smtp/host` or `system/smtp/port`

**Comment by maksek** [comment]
Please use form for all questions regarding magento 2. GitHub only for reported bugs with steps to reproduce.

**Comment by p3mbo** [comment]
Hi,
This is not a question - hence there being no question mark in my original post. The setting In Magento 2 does not do anything.

Steps to reproduce:
- Install M2 on a Windows Based System
- Fill out system/smtp/host and system/smtp/port from the configuration setting.
- Try to send an email.

Expected Result:
- Email is sent.

Actual Result:
- Email is not sent because the host and port are not read.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-52707

**Comment by cspruiell** [comment]
This issue has been fixed and delivered to the develop branch.
