### ISSUE TITLE
catalog/seo/generate_category_product_rewrites changed into 2.4.6 to default to 0

### ISSUE THREAD

**Issue by stuartaware** [magento/magento2#37772]
### Preconditions and environment

- Magento version 2.4.6

### Steps to reproduce

Update to 2.4.6 

### Expected result

Product rewrites to be generated correctly. 

### Actual result

Product rewrites are not generating category paths.

### Additional information

Default config change does not appear to have been documented in the update. 

There is a warning beneath this setting.

Stores -> Config -> Catalog -> Catalog -> SEO
![Screenshot 2023-07-19 at 13 08 17](https://github.com/magento/magento2/assets/95861447/1bdecbe7-a2a6-44b9-b52b-ee1fa890bf6e)

This change has caused issues across sites which has recieved the update, rendering them unable to create new products with the correct category URLs

File in question is here

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/etc/config.xml

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @stuartaware,

Thank you for reporting and collaboration.

Kindly provide more information about from which version you have updated to Magento 2.4.6 and also elaborate steps to reproduce and also provide screenshots it will help us to reproduce the issue.


Thanks.

**Comment by hostep** [comment]
@engcom-Bravo: that's not relevant

This is about the default setting to have changed from being [enabled in 2.4.5 and earlier](https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/CatalogUrlRewrite/etc/config.xml#L12) to [disabled in 2.4.6 and later](https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/CatalogUrlRewrite/etc/config.xml#L12) .
Based on the commit message in https://github.com/magento/magento2/commit/e2ab9c01f1fda7bf62aabb1702531c9daeb16418, it looks like this was done for improved performance, which I agree with, it's much faster to have this setting disabled.

So, in my opinion, this is more a bug in the documentation, where it wasn't specified in the release notes, so it's probably better to open [an issue with the documentation team](https://github.com/AdobeDocs/commerce-operations.en/issues) to get it added to the release notes for Magento 2.4.6

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution & collaboration over here.

@stuartaware,

As per this comment https://github.com/magento/magento2/issues/37772#issuecomment-1643808398 this is not an issue in magento.Generate "category/product" URL Rewrites disabled to improve performance.it wasn't specified in the release notes

We have created issue in documentation https://github.com/AdobeDocs/commerce-operations.en/issues/102.

Hence we are closing this issue.
Thanks.
