### ISSUE TITLE
[Magento 2.4.6-p1] Bundle Products - Child Product Visibility set to "Not visible individually" doesn't get returned in GraphQl Bundle Selections

### ISSUE THREAD

**Issue by MihaiComan90** [magento/magento2#37774]
### Preconditions and environment

Magento 2.4.6-p1 Enterprise Edition.
Creating a new bundle with a child selection that has the Visibility attribute set to "Not visible individually" doesn't get returned in the product information under the options node in GraphQl Products Query, see screenshot below:

![image](https://github.com/magento/magento2/assets/47864120/7f47dc3d-2156-4e86-999f-f5f43b0d7917)

Now for some reason i saw this as core intended behaviour although it seems awfully odd, i should be able to create a product specifically for a bundle that wouldn't be visible individually.

Initial investigations led me to check the **catalog_category_product** indexer which stores the visibility information in the catalog_category_product_index_store* table, although it strips any VISIBILITY_NOT_VISIBLE products from getting added into that indexer.

Also what would happen if i decide not to assign this child product to a category, i should still be able to see it as the selection product response.

### Steps to reproduce

1. Login to the admin
2. Create a new Simple Product with random data, Enabled, and set the visibility to VISIBILITY_NOT_VISIBLE.
3. Create a new Bundle Product and assign the above product as an option.
4. Run the **catalog_category_product** indexer and check the **catalog_category_product_index_store1** table
5. Notice that the child product doesn't exist.
6. Run the **products** graphql query to get the bundle product along with options:
`options {
        id
        qty
        uid
        quantity
        position
        is_default
        price
        price_type
        can_change_quantity
        label
        product { name } 
}`
7. Notice the **label** and **product** being empty.
8. Go back to the child product created at step 2
9. Change the visibility to VISIBILITY_IN_CATALOG / VISIBILITY_BOTH and repeat step 4
10. Notice the product is added to the **catalog_category_product_index_store1** table and thus is available as the selection product
 

### Expected result

I should be able to set a child product of a bundle as VISIBILITY_NOT_VISIBLE and/or without category and still see it in the graphql selection response

### Actual result

Selection is displayed but with no label or product information, see below,

![image](https://github.com/magento/magento2/assets/47864120/0854f604-261f-4c11-98f2-996828316236)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MihaiComan90** [comment]
@magento give me 2.4-develop instance

**Comment by MihaiComan90** [comment]
Tested on the above instance and issue seems not reproducible, although if we take a look at the vendor/magento/module-catalog-graph-ql/Model/Resolver/Products/DataProvider/Product.php class, we can see the following line:

`if ($isChildSearch) {
    $visibilityIds = $isSearch
        ? $this->visibility->getVisibleInSearchIds()
        : $this->visibility->getVisibleInCatalogIds();
    $collection->setVisibility($visibilityIds);
}`

If the **$isSearch** flag is set then it returns 2,4 if not 3,4 as the visibility flags. As such, i don't know exactly what am i missing in the picture. Any help would be much appreciated.
Again, mentioning the above instance is 2.4-develop and i have the issue on 2.4.6-p1 Enterprise

**Comment by paales** [comment]
I can confirm this issue, we just ran into this as well.

**Comment by engcom-Bravo** [comment]
Hi @MihaiComan90,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.kindly refer the screenshots.


**Steps to reproduce**

- Login to the admin
- Create a new Simple Product with random data, Enabled, and set the visibility to VISIBILITY_NOT_VISIBLE.
- Create a new Bundle Product and assign the above product as an option.
- Run the catalog_category_product indexer and check the catalog_category_product_index_store1 table
- Notice that the child product doesn't exist.

<img width="551" alt="Screenshot 2023-07-21 at 1 33 01 PM" src="https://github.com/magento/magento2/assets/51680745/1dc56b2b-2231-4d29-89e0-f309455d46db">

- Run the products graphql query to get the bundle product along with options:


<img width="1414" alt="Screenshot 2023-07-21 at 1 47 58 PM" src="https://github.com/magento/magento2/assets/51680745/fb695f77-ad7f-48ba-8fce-3fc926796394">


<img width="1436" alt="Screenshot 2023-07-21 at 1 32 09 PM" src="https://github.com/magento/magento2/assets/51680745/5e5b49d9-1f07-42f9-9ee8-8978ffe042e3">




We are able to get the child products for Bundle products in the response even though when we set visibility to **Not Visible individually** child products returned in Bundle product graphql response.



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible


Thanks.

**Comment by MihaiComan90** [comment]
Hello, yes as i've mentioned in a followup comment, i have successfully managed to test this on the testing environment.
Unfortunately either it's some enterprise edition bug or our custom code. 

Thank you very much, will close this topic.

**Comment by MihaiComan90** [comment]
Hello everyone, 

Re-opening the issue as i've tested locally on a 2.4.6-p1 instance with sample data and it is reproducible see below: 
query:
`{
	products(
		filter: { sku: { eq: "24-WG080" } }
	)
	{
        items {
            sku
            name
                uid
         		name
            ... on BundleProduct {
                dynamic_sku
                items {
                    uid
                    title
                    required
                    type
                    position
                    sku
                    options {
                        uid
                        quantity
                        position
                        is_default
                        price
                        price_type
                        can_change_quantity
                        label
                        product {
                            uid
                            name
                            sku
                        }
                    }
                }
            }
        }
	}
}`
response: 
`{
    "data": {
        "products": {
            "items": [
                {
                    "sku": "24-WG080",
                    "name": "Sprite Yoga Companion Kit",
                    "uid": "NDU=",
                    "dynamic_sku": true,
                    "items": [
                        {
                            "uid": "YnVuZGxlLzE=",
                            "title": "Sprite Stasis Ball",
                            "required": true,
                            "type": "radio",
                            "position": 1,
                            "sku": "24-WG080",
                            "options": [
                                {
                                    "uid": "YnVuZGxlLzEvMS8x",
                                    "quantity": 1,
                                    "position": 1,
                                    "is_default": true,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null ## THIS IS EMPTY BECAUSE VISIBILITY IS 1
                                },
                                {
                                    "uid": "YnVuZGxlLzEvMi8x",
                                    "quantity": 1,
                                    "position": 2,
                                    "is_default": false,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null ## THIS IS EMPTY BECAUSE VISIBILITY IS 1
                                },
                                {
                                    "uid": "YnVuZGxlLzEvMy8x",
                                    "quantity": 1,
                                    "position": 3,
                                    "is_default": false,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null
                                }
                            ]
                        },
                        {
                            "uid": "YnVuZGxlLzI=",
                            "title": "Sprite Foam Yoga Brick",
                            "required": true,
                            "type": "radio",
                            "position": 2,
                            "sku": "24-WG080",
                            "options": [
                                {
                                    "uid": "YnVuZGxlLzIvNC8x",
                                    "quantity": 1,
                                    "position": 1,
                                    "is_default": true,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": "Sprite Foam Yoga Brick",
                                    "product": {
                                        "uid": "MjE=",
                                        "name": "Sprite Foam Yoga Brick",
                                        "sku": "24-WG084"
                                    }
                                }
                            ]
                        },
                        {
                            "uid": "YnVuZGxlLzM=",
                            "title": "Sprite Yoga Strap",
                            "required": true,
                            "type": "radio",
                            "position": 3,
                            "sku": "24-WG080",
                            "options": [
                                {
                                    "uid": "YnVuZGxlLzMvNS8x",
                                    "quantity": 1,
                                    "position": 1,
                                    "is_default": true,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null
                                },
                                {
                                    "uid": "YnVuZGxlLzMvNi8x",
                                    "quantity": 1,
                                    "position": 2,
                                    "is_default": false,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null
                                },
                                {
                                    "uid": "YnVuZGxlLzMvNy8x",
                                    "quantity": 1,
                                    "position": 3,
                                    "is_default": false,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": null,
                                    "product": null
                                }
                            ]
                        },
                        {
                            "uid": "YnVuZGxlLzQ=",
                            "title": "Sprite Foam Roller",
                            "required": true,
                            "type": "radio",
                            "position": 4,
                            "sku": "24-WG080",
                            "options": [
                                {
                                    "uid": "YnVuZGxlLzQvOC8x",
                                    "quantity": 1,
                                    "position": 1,
                                    "is_default": true,
                                    "price": 0,
                                    "price_type": "FIXED",
                                    "can_change_quantity": true,
                                    "label": "Sprite Foam Roller",
                                    "product": {
                                        "uid": "MjI=",
                                        "name": "Sprite Foam Roller",
                                        "sku": "24-WG088"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    }
}`

Steps to replicate:
1. Open a 2.4.6-p1 environment
2. Run the above query
3. Notice that the visibility products that are set to **1** are not appearing within the product node in the **options**

As you can see in the query above, some of the product information is NULL within the product node and only those products which have catalog visibility set to 2,4 are being retrieved in the bundle option product.

It is true that on the develop dev branch, while testing locally this was working but on 2.4.6-p1 this is not. Is there any patch related to this ?

Cheers

**Comment by MihaiComan90** [comment]
Found the culprit see class:
app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Product.php

This **if ($isChildSearch) { changed** to this **if (!$isChildSearch) {**

Which fixes the issue on dev but not on 2.4.6-p1

Official issue: [ACP2E-1315](https://github.com/magento/magento2/commit/0469d64bc6918b979805bc44f6313025e47ee266)

**Comment by engcom-Bravo** [comment]
Hi @MihaiComan90,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1315 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1315&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.Please let us know still if you are facing any issue.

Thanks.

**Comment by MihaiComan90** [comment]
Hello @engcom-Bravo ,

Yes the issue has been fixed through a patch.

This can be closed as a duplicate of the one you've mentioned.

Thank you
