### ISSUE TITLE
Missing dependency on web-token/jwt-easy?

### ISSUE THREAD

**Issue by hostep** [magento/magento2#37783]
### Preconditions and environment

- Magento version `2.4-develop`

### Steps to reproduce

1. Look at this line of code: https://github.com/magento/magento2/blob/ca30c47787db932b9431e42226bb918e95c932d9/app/code/Magento/JwtFrameworkAdapter/Model/AlgorithmProviderFactory.php#L11 (it mentions the namespace `Jose\Easy`)
2. This class (`Jose\Easy\AlgorithmProvider`) is nowhere to be found in the magento codebase after installing all composer dependencies

### Expected result

Magento should use code that's included, it shouldn't use code that's not included as this will crash.

### Actual result

Found referenced code that's not present in the codebase.

### Additional information

I suspect this happened because:

1. This code [was introduced](https://github.com/magento/magento2/commit/ea92f9b4770e77bee733b6825244f193f6d53fd6) in February 2021
2. In November 2022, the `web-token/jwt-framework` package [was updated from version v2.2.11 to 3.1.2](https://github.com/magento/magento2/commit/86d1144ce0a)
3. If we take a look at the changes between those 2 versions, we can see that the `Jose\Easy\AlgorithmProvider` [got removed](https://github.com/web-token/jwt-framework/compare/v2.2.11...3.1.2#diff-427eb928a9e65006572e87515fadad452031201c35a25d3d4ea2f812f6716659) from `web-token/jwt-framework`

Possible solution: add a requirement on `web-token/jwt-easy`, however, [that package is considered abandoned](https://packagist.org/packages/web-token/jwt-easy), so not sure if that's the best way forward here?

Also: there are probably too few automated tests for this `JwtFrameworkAdapter` magento module, otherwise this would have been catched earlier...

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @hostep,

Thank you for report and collaboration!

As you mentioned the `web-token/jwt-easy` has been abandoned and no longer being used.
But `Jose\Easy\AlgorithmProvider` has been referenced even though it is not present.

Hence we can confirm the issue.

Thanks.

**Comment by yegxr** [comment]
@magento I am working on this
