### ISSUE TITLE
Urgent: display full error message

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3778]
When an error occurs, the description is cut off with ellipsis, such as this:
#11 /home/depasa/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage), '/home/depasa/pu...', Array)

Messages like that is complete useless. How can I read the full error? I think you should modify this so that full error is shown.

**Comment by ishakhsuvarov** [comment]
@jaimestuardo Thank you for your question.
Please check error logs located inside `var/log` and `var/report` directories (relative to Magento root).

**Comment by maksek** [comment]
Closing due no feedback from creator.
