### ISSUE TITLE
Upgrading Magento resets general/region/state_required when new country with required state/region is added.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#37796]
### Summary

When a new Country is added with required states (in 2.4.6 this was Czechia). The `general/region/state_required` gets reset to the default countries with a required state (or at the very least readds all those countries).  Which means that if you had modified this configuration and have some form of custom code that assumes region is disabled. This could break your shop.

### Examples

This is the Data patch for adding the Regions of Czechia.
```
    public function apply()
    {
        /** @var DataInstaller $dataInstaller */
        $dataInstaller = $this->dataInstallerFactory->create();
        $dataInstaller->addCountryRegions(
            $this->moduleDataSetup->getConnection(),
            $this->getDataForCzechia()
        );
        
        return $this;
    }
```
And this is the DataInstaller which adds the regions as expected. But then follows this up by resetting the state required countries.
```
    public function addCountryRegions(AdapterInterface $adapter, array $data)
    {
        /**
         * Fill table directory/country_region
         * Fill table directory/country_region_name for en_US locale
         */
        foreach ($data as $row) {
            $bind = ['country_id' => $row[0], 'code' => $row[1], 'default_name' => $row[2]];
            $adapter->insert($this->resourceConnection->getTableName('directory_country_region'), $bind);
            $regionId = $adapter->lastInsertId($this->resourceConnection->getTableName('directory_country_region'));
            $bind = ['locale' => 'en_US', 'region_id' => $regionId, 'name' => $row[2]];
            $adapter->insert($this->resourceConnection->getTableName('directory_country_region_name'), $bind);
        }
        /**
         * Upgrade core_config_data general/region/state_required field.
         */
        $countries = $this->data->getCountryCollection()->getCountriesWithRequiredStates();
        $adapter->update(
            $this->resourceConnection->getTableName('core_config_data'),
            [
                'value' => implode(',', array_keys($countries))
            ],
            [
                'scope="default"',
                'scope_id=0',
                'path=?' => \Magento\Directory\Helper\Data::XML_PATH_STATES_REQUIRED
            ]
        );
    }
```

### Proposed solution

Only add the modified country to `general/region/state_required`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thedotwriter** [comment]
I'll add that `$this->data->getCountryCollection()->getCountriesWithRequiredStates()` was only returning the countries for the default website. Therefore, if this default website only allows shipping to a few countries, you won't get a complete list of countries with required states.

Anyway, with the patch below, I've completely removed the need for getCountriesWithRequiredStates() so that's not an issue anymore.

Here's the patch. This prevents losing custom required states each time regions are updated for a country.

```
--- a/vendor/magento/module-directory/Setup/DataInstaller.php
+++ b/vendor/magento/module-directory/Setup/DataInstaller.php
@@ -16,25 +16,17 @@
 class DataInstaller
 {
     /**
-     * @var \Magento\Directory\Helper\Data
-     */
-    private $data;
-
-    /**
      * @var ResourceConnection
      */
     private $resourceConnection;
 
     /**
      * DatInstaller constructor.
-     * @param \Magento\Directory\Helper\Data $data
      * @param ResourceConnection $resourceConnection
      */
     public function __construct(
-        \Magento\Directory\Helper\Data $data,
         ResourceConnection $resourceConnection
     ) {
-        $this->data = $data;
         $this->resourceConnection = $resourceConnection;
     }
 
@@ -57,14 +49,30 @@
             $bind = ['locale' => 'en_US', 'region_id' => $regionId, 'name' => $row[2]];
             $adapter->insert($this->resourceConnection->getTableName('directory_country_region_name'), $bind);
         }
+
+        // Get country ID from regions.
+        $region = reset($data);
+        $countryId = $region[0];
+
+        $select = $adapter->select()
+            ->from($this->resourceConnection->getTableName('core_config_data'), 'value')
+            ->where('path = ?', \Magento\Directory\Helper\Data::XML_PATH_STATES_REQUIRED)
+            ->where('scope = ?', 'default')
+            ->where('scope_id = ?', 0);
+        $currentRequiredStates = $adapter->fetchOne($select);
+
+        $currentRequiredStates = explode(',', $currentRequiredStates);
+        if (!in_array($countryId, $currentRequiredStates)) {
+            $currentRequiredStates[] = $countryId;
+        }
+
         /**
          * Upgrade core_config_data general/region/state_required field.
          */
-        $countries = $this->data->getCountryCollection()->getCountriesWithRequiredStates();
         $adapter->update(
             $this->resourceConnection->getTableName('core_config_data'),
             [
-                'value' => implode(',', array_keys($countries))
+                'value' => implode(',', $currentRequiredStates)
             ],
             [
                 'scope="default"',

```

**Comment by engcom-November** [comment]
Hello @Hexmage,

Thank you for the report and collaboration!

We were able to reproduce this issue on 2.4-develop.
To check wether `general/region/state_required` is being reset after adding country with required state, we removed United States from state_required.

<img width="899" alt="image" src="https://github.com/magento/magento2/assets/60198231/49483e94-c147-4a7c-ba11-f6dfa8f08a5a">

Then added Japan to state_required by using a custom module.
After upgrading magento it can be seen that Japan country code `JP` has been added to `general/region/state_required`, but it also did reset the `general/region/state_required`, by adding United States to the list.

![image](https://github.com/magento/magento2/assets/60198231/4fa17034-b0b7-4542-825c-667c587f3bca)

Please find below the custom module.
[RequiredVendor.zip](https://github.com/magento/magento2/files/12671863/RequiredVendor.zip)

Hence confirming the issue.

Thank you.

**Comment by Yaroslav1301** [comment]
@magento I am working on this

**Comment by Zwernemann** [comment]
This is still happening with magento updates. After update to 2.47.-p2 a lot of countries were set to "state is required", that were unchecked before the update. Countries like swizerland and denmark. We got a lot of complaints, because customers couldn't order.
