### ISSUE TITLE
Getting products by REST API

### ISSUE THREAD

**Issue by wozniakm** [magento/magento2#3780]
## Steps to reproduce
1. Create configurable product
2. Call REST API to get products, for example `GET /rest/V1/products?searchCriteria[page_size]=3`
## Expected result
1. Returned array should contain your added product with extension_attributes key inside
## Actual result
1. The extension_attributes is not present

In ProductRepository there is a line `$this->extensionAttributesJoinProcessor->process($collection);` which calls method responsible for extension_attributes, but despite that they are not included into product. If you request product details by calling `GET /rest/V1/products/:sku` the extension_attributes array is present.

It really makes no sense to call API once to get products, then call API to get configurable product details and then, finally, call API to get values and labels for configurable options. Is there easier way?

**Comment by mbrinton01** [comment]
Internal issue MAGETWO-52814

**Comment by skovalenk** [comment]
Done
See code sample here: 
https://github.com/magento/magento2-samples/tree/master/sample-external-links

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Getting-products-by-REST-API/idi-p/46409).
