### ISSUE TITLE
SubTotal Rounding Issue For Decimal Quantity Enabled Product

### ISSUE THREAD

**Issue by dharmesh-tukadiya** [magento/magento2#37817]
### Preconditions and environment

::: Magento version : 2.4.6 :::

::: Test Product Specification :::
-- Type : Simple
-- Price 20.67
-- Quantity : 1.5 (Enabled Decimal Quantity For Product)

::: Fixed Shipping Price :::
-- Price : 7.50 $

### Steps to reproduce

Add a product, with above defined specifications, to cart. (Now look at checkout/cart page)

After that flat rate shipping price is set to 7.50 $, place order. And check customer account => Order History (You'll find incorrect order total, it was supposed to be 38.51 but showing 30.50) => View Order (Order Item Subtotal, Sub Total & Grand Total is wrong with value of 38.50, which is supposed to be 38.51).

### Expected result

Expected result should be like 

Before Place Order
![Screenshot](https://github.com/magento/magento2/assets/140082778/310e7569-2b21-4650-b170-a29fc027ea6c)

After Place Order
![Screenshot (2)](https://github.com/magento/magento2/assets/140082778/c156ecdb-6dc5-4ab2-8dad-64fcde228c78)
![Screenshot (4)](https://github.com/magento/magento2/assets/140082778/26ecd882-0cdd-4875-8331-f6474cafdff9)
Order View Page Admin Side
![Screenshot (6)](https://github.com/magento/magento2/assets/140082778/97921f6e-ff9a-45ab-a469-d5a3d05eb456)
Invoice View Page Admin Side
![Screenshot (9)](https://github.com/magento/magento2/assets/140082778/4a3a412f-4596-4593-ba2b-75aa54742ba4)

### Actual result

Actual result is like below.
Before Place Order
![Screenshot (1)](https://github.com/magento/magento2/assets/140082778/d05a7afd-adfc-4f05-8557-8a615ba356ac)

After Placing Order
![Screenshot (3)](https://github.com/magento/magento2/assets/140082778/bc09535c-7e8e-4ed7-b11b-d5caf4145054)
![Screenshot (5)](https://github.com/magento/magento2/assets/140082778/d9463074-6b79-480d-8c5f-b541edbab247)
Order View Page Admin Side
![Screenshot (7)](https://github.com/magento/magento2/assets/140082778/1ff7a4ab-d5d4-46bb-96e6-9aa897938792)
Invoice View Page Admin Side
![Screenshot (10)](https://github.com/magento/magento2/assets/140082778/443b730e-e77b-4222-a3e7-48700c22998e)

### Additional information

This isssue is also occuring in the emails being sent after order confirmation, invoice pdf etc.. where ever the row total, subtotal and grant total is concerned. Also grantotal of the order is wrong in the history grids. This could also be an issue in api responses.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instanc

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by mohammadbharmal** [comment]
Hello @dharmesh-tukadiya,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible .Kindly refer the screenshots.

Steps to reproduce

> Log in to Magento 2.4.6 admin.
> Set one product for decimal qty allow.
> Set price 20.67
> Open product in frontend
> Add 1.5 qty in cart.

![image](https://github.com/magento/magento2/assets/73457616/b32bf80d-7e7d-4790-b7c5-40cd367f94cf)

Hence Confirming this issue.

Thanks.

**Comment by engcom-Dash** [comment]
Hi @dharmesh-tukadiya ,

verified the issue in 2.4-develop instance and the issue is reproducible,Hence we are confirming the issue
Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-07-31 at 3 45 22 PM" src="https://github.com/magento/magento2/assets/60198592/97460cf4-6053-46f4-b01c-74875e9ff267">
<img width="1512" alt="Screenshot 2023-07-31 at 3 45 38 PM" src="https://github.com/magento/magento2/assets/60198592/43856cbf-a0e6-42f7-91d2-936ff8146cab">
<img width="1512" alt="Screenshot 2023-07-31 at 3 46 46 PM" src="https://github.com/magento/magento2/assets/60198592/7d640c00-727e-4315-93b6-8f5d8d8a55cc">
<img width="1512" alt="Screenshot 2023-07-31 at 3 47 34 PM" src="https://github.com/magento/magento2/assets/60198592/70624a37-fbfc-4b07-8e78-abbade42b49b">

**Comment by dharmesh-tukadiya** [comment]
I think this issue needs to get fixed on priority as it can turn out to be a serious bug for api endpoints.

**Comment by dharmesh-tukadiya** [comment]
If anyone looking for temporary quick fix one can do it like this

```
if ($price != null) {
            $price = sprintf("%F", round($price, 2));
        }
```
Paste above code at `vendor/magento/module-directory/Model/Currency.php` : Line No. 375

This can be achieved via creating a patch file or one can create a before plugin to modify the argument of `formatTxt` function in the same file as above.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by dharmesh-tukadiya** [comment]
vendor/magento/module-directory/Model/Currency.php : Line No. 429

```
$this->numberFormatter->setAttribute(
            \NumberFormatter::ROUNDING_MODE,
            \NumberFormatter::ROUND_HALFUP
        );
```

**Comment by engcom-Bravo** [comment]
Hello,

Thanks for your Contribution and collaboration.

internal team is started working on this issue and the steps to reproduce are as below

Log in to Magento admin panel.
Set one product for decimal qty allow.
Set price 20.67
Open the same product in frontend
Add 1.5 qty in cart
Thanks.
