### ISSUE TITLE
Backend menu gets too long and not generating proper columns

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#37812]
### Preconditions and environment

- Magento version 2.4.4-p4
- Firefox
- Having a first submenu containing more than 12 items.

Example : the first submenu of the Sales menu has got 13 items.

![image](https://github.com/magento/magento2/assets/16592249/e9bc80d3-b333-4b70-bd47-3e86bef7872a)

### Steps to reproduce

1. Access the backend.

### Expected result

The system should add a column brake so the submenus are correctly displayed

### Actual result

Unable to access submenus below the 12+ submenu because the column brake isn't behaving correctly.

Attached is a screenshot of the problem. I'm already scrolled down at the very bottom of the page and there's still items below "Shipments" and "Credit memos"

![image](https://github.com/magento/magento2/assets/16592249/39f3c422-816a-41cf-b50b-472e78e081c6)

### Additional information

I have investigated and managed to fix the issue with the following code. Problem comes from the fact that if the first submenu exceeds the hardcoded 12 items limit, the next submenu does not automatically include a column brake.

```
diff --git a/magento/module-backend/Block/Menu.php b/magento/module-backend/Block/Menu.php
--- a/magento/module-backend/Block/Menu.php
+++ b/magento/module-backend/Block/Menu.php
@@ -333,10 +333,16 @@ class Menu extends \Magento\Backend\Block\Template
         }
         $result[] = ['total' => $total, 'max' => ceil($total / ceil($total / $limit))];
         $count = 0;
+        $itemCount = 0;
+        $nextColBrake = false;
         foreach ($items as $item) {
+            $itemCount++;
             $place = $this->_countItems($item->getChildren()) + 1;
             $count += $place;
-            if ($place - $result[0]['max'] > $limit - $result[0]['max']) {
+            if ($nextColBrake) {
+                $colbrake = true;
+                $count = $place;
+            } elseif ($place - $result[0]['max'] > $limit - $result[0]['max']) {
                 $colbrake = true;
                 $count = 0;
             } elseif ($count - $result[0]['max'] > $limit - $result[0]['max']) {
@@ -345,6 +351,12 @@ class Menu extends \Magento\Backend\Block\Template
             } else {
                 $colbrake = false;
             }
+
+            $nextColBrake = false;
+            if ($itemCount == 1 && $colbrake) {
+                $nextColBrake = true;
+            }
+
             $result[] = ['place' => $place, 'colbrake' => $colbrake];
         }
         return $result;
```

Test evidence after fix : 

![image](https://github.com/magento/magento2/assets/16592249/d2123aa1-bbd1-4544-aa43-0d66cd6cf903)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @digitalpianism ,

Verified the issue in 2.4-develop and the issue is not reproducible,Kindly recheck the behaviour.

Steps to reproduce:
1.Install Magento instance and access the backend

Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-07-31 at 9 48 33 AM" src="https://github.com/magento/magento2/assets/60198592/f2672898-81c3-45c9-8e9a-b2ead436deb8">

Let us know if we are missing anything!

**Comment by digitalpianism** [comment]
@engcom-Dash Hi there, I think there's a misunderstanding of the bug I reported. It has nothing to do with Amasty or any other 3rd party extension. The problem is only replicable if a first submenu contains more than 12 items. 

Simple example with a custom module with the following `adminhtml/menu.xml` file  : 

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
    <menu>
        <add id="Package_Test::test1" title="Test 1"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test2" title="Test 2"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test3" title="Test 3"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test4" title="Test 4"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test5" title="Test 5"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test6" title="Test 6"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test7" title="Test 7"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test8" title="Test 8"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Package_Test::test9" title="Test 9"
             translate="title" module="Package_Test" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
    </menu>
</config>

```


![image](https://github.com/magento/magento2/assets/16592249/128ff917-05ee-4a7d-83b5-526c390c09a6)

**Comment by engcom-November** [comment]
Hello @digitalpianism,

Thank you for report and collaboration!

We have reproduced the issue on 2.4-develop.
We can observe that it is not possible to access the rest of the menu, if there are more than 12 submenu.
Please look at the screenshot for reference.
![image](https://github.com/magento/magento2/assets/60198231/a1ce405c-c718-4920-bcaf-060410c0af2f)

Hence confirming the issue.
Thanks.

**Comment by digitalpianism** [comment]
@engcom-November thanks for confirming. Note that I have included the fix in my first comment under the Additional Information section.

**Comment by hutychivan** [comment]
@magento I am working on this

**Comment by hostep** [comment]
@engcom-November or @engcom-Dash: why did this got closed? There is no explanation. Was it fixed? Can you link to the commits that fix this?
