### ISSUE TITLE
QUESTION: Why empty values in dropdown attribute are non visible?

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#3782]
## Steps to reproduce
1. Magento 2.0.2 
2. create product attribute "test_dropdown", type=dropdown, required=NO, add this attribute to attribute set
3. go to create product page

Expected result
1. I should have ability to leave "test_dropdown" attribute empty, if it's not required.

Actual result
1. "test_dropdown" has empty option, however it is set display: none
![image](https://cloud.githubusercontent.com/assets/10142848/13771357/ce9ba9fc-ea95-11e5-9d2e-14b95a9c4134.png)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54353

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@katesuykovskaya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
