### ISSUE TITLE
Datenbank-Rollback funktioniert nicht mit Magento 2.4.5

### ISSUE THREAD

**Issue by Machcomputer** [magento/magento2#37825]
### Preconditions and environment

- Magento version 2.4.5.

![backup](https://github.com/magento/magento2/assets/140407505/adc47d41-674f-40cb-a675-b3581742908a)

### Steps to reproduce

navigiere nach system unter tools zu Backups und dann rollback

### Expected result

Ich erwartete dort das der backup installiert wird

### Actual result

Es passiert einfach nichts wenn wir auf die Rollback button klicken

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Machcomputer** [comment]
Ich weis nicht ob es hilft, aber bei die hierobengenannten zugang für engcom-Dash funktioniert den Rollback bei machcomputer.de leider noch nicht

**Comment by Machcomputer** [comment]
Guten Tag, ich bin mir nicht sicher ob sie noch informationen von mir, bezüglich das Rolbackfehler haben wollen, aber ich sehe hier keinen lösungsvorschlag !

**Comment by engcom-Dash** [comment]
Hi @Machcomputer ,

Kindly provide more information to confirm this issue,As  per [DevDocs](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/backup.html?lang=en) we are trying to reproduce and issue can be reproducible,But We need more information from your end to reproduce this issue.

Thanks

**Comment by Machcomputer** [comment]
Die webseite www.machcomputer.de, für deutschland, wurde geklont von unseren www.davin-computers.com. Die ist für die Niederlande.
Bei Machcomputer.de wurde das Backup tool aktiviert und es wurde einen backup gestellt.
Wenn ich jezt auf Rollback drucke passiert nichts.


![backup 0308](https://github.com/magento/magento2/assets/140407505/4ce1c15c-a0f3-4e46-b1a3-52488170918b)
![backup](https://github.com/magento/magento2/assets/140407505/af5e7ee5-8af4-4220-b974-fe0660cfc4db)

**Comment by Machcomputer** [comment]
welche Informationen baruchen Sie noch mehr?

**Comment by magenizr** [comment]
@Machcomputer 

Kurze Frage, warum willst du den Rollback über das Backend durchführen? Ich nehme an du willst nur ein paar Tabellen entfernen die durch Module installiert wurden?

Es gibt verschiedene Gründe warum der Rollback über das Backend nicht funktioniert. Zum Beispiel PHP MemoryLimit auf Sever Level oder wie auf https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/backup.html?lang=de beschrieben:

" _Es wird empfohlen, die Festlegung eines Werts für [pcre.recursion_limit](https://www.php.net/manual/en/pcre.configuration.php) im php.ini -Datei, da dies zu unvollständigen Rollbacks ohne Fehlermeldung führen kann._ "

**Comment by Machcomputer** [comment]
@magenizr,
Danke für deine reaktion. Ich war mit magento noch nicht bekannt. Als ich die Webseite aus den niederlande bekam, wo laut deren programmeur "NUR" noch ins deutsch übersetzt werden musste, und bevor ich anfangen wollte zu arbeiten habe ich mir einen backup gemacht. Das "mal eben" übersetzen ist natürlich mehr Arbeit und wissen als gedacht und somit brauchte ich nach 2 tagen "Experimentieren" den backup.   Das komische an die ganze Geschichte ist wohl das der backup in die Niederlande einwandfrei funktioniert wobei die dateigroße gleich ist. Vielleicht gibt es irgendein Fehler beim Klonen von die seite. Das ist wohl suchen nach einen Nadeln in ein Heuhaufen ;-)

**Comment by magenizr** [comment]
@Machcomputer 

Es gibt verschiedene Möglichkeiten das Frontend von Magento Multi-Sprachig zu machen, zum Beispiel mit Excel und über eine CSV Datei ( e.g https://magento.stackexchange.com/questions/284768/how-to-translate-magento-2-3-2-frontend-only )

Eine andere Variate ist über das Backend, dauert aber zu lange meiner Meinung nach. Falls du Hilfe brauchst, hello@magenizr.com

**Comment by Machcomputer** [comment]
@magenizr 
Ich werde mir deine Übersetzungsvorschläge heutemittag anschauen, kan mir aber Vorstellen das ich als holländicsher Laie bestimmt Hilfe brauche um schneller ans Ziel zu kommen ;-). Danke für dein Holfsangebot, ich schreibe dir nachher per mail.

**Comment by engcom-Dash** [comment]
Hi @magenizr ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.Kindly recheck the behaviour.
Kindly refer the below video reference:

https://github.com/magento/magento2/assets/60198592/88aa0da0-f733-4e32-b1ba-a4572aac1a68

After clicking the rollback the backup data stored in Var/Backup of root directory.

**Comment by Machcomputer** [comment]
@engcom-Dash
Danke für die reaktion und die Bildschirmaufnahme aber so weit wie bei Ihnen kommt es nicht. Hier meine Aufzeichnung:

https://github.com/magento/magento2/assets/140407505/68a25378-5310-47fc-b900-5274652c3e6f

Beim erstellen der Backup's sind alle drei dateinen in VAR/Backup abgelegt, vielleicht kan ich die über ZIP extrahieren?

**Comment by engcom-Dash** [comment]
Hi @Machcomputer ,

Verified the issue in 2.4-develop instance and issue is not reproducible,Kindly refer the below video reference and screenshot:

https://github.com/magento/magento2/assets/60198592/209b19ec-1546-48fc-a740-67f117f5483f
<img width="1512" alt="Screenshot 2023-08-09 at 7 15 29 PM" src="https://github.com/magento/magento2/assets/60198592/98698671-5e57-463e-9971-55d60350c58a">

**Comment by Machcomputer** [comment]
hallo Support, Das das Problem bei Ihnen nicht reproduzierbar ist habe ich verstanden und deswegen haben Sie das Problem auch nicht sondern ich als User. Danke das Sie mir 2 mal das gleiche Video schicken, es führt leider nicht zu eine Problemlösung. trotzdem danke, ich suche weiter

**Comment by engcom-Dash** [comment]
Hi @Machcomputer ,

We verified the issue in latest version 2.4-develop and the issue is not reproducible,May be the latest build issue got fixed
and Kindly upgrade with latest version, Recheck the behaviour in that. as per the [comment](https://github.com/magento/magento2/issues/37825#issuecomment-1669774623) rollback is worked in 2.4-develop and we got backup var/logs of magento root directory.

Thanks.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Machcomputer,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
