### ISSUE TITLE
Report is not working/Error message for Total Orders by Payment Type

### ISSUE THREAD

**Issue by MathildeOrbiss** [magento/magento2#37828]
### Preconditions and environment

- Magento ver. 2.4.6
- Hello, I work for Maison Kitsune Company and I used to download a report with sales by Payment Type for the last month.
- I am not able to do it anymore as I have an error message. I tried several times to download this report from July 1st to August 1st unsuccessfully.
- Please see the steps to reproduce:
- Dashboard > Reports > Advanced Reports > Store selection to maisonkitsune.com - US -EN > Click on Payment Type under Sales by > Dates selection to July 1st as start date and August 1st as end date
- An error message appears with the mention "Attention, Something went wrong" 

![bug magento](https://github.com/magento/magento2/assets/141177487/40f3e94a-a817-4b46-b28c-4accf2be9828)

### Steps to reproduce

Dashboard > Reports > Advanced Reports > Store selection to maisonkitsune.com - US -EN > Click on Payment Type under Sales by > Dates selection to July 1st as start date and August 1st as end date

### Expected result

I can download to csv the report

### Actual result

I can' t download the report as I get an error message (See above)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @MathildeOrbiss ,    
                                                                                                                                                                        
 We need more information to confirm this ticket. Please provide logs or other details for this issue.

**Comment by engcom-Bravo** [comment]
Hi @MathildeOrbiss,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
