### ISSUE TITLE
Web Setup Wizard  on admin panel 401 page

### ISSUE THREAD

**Issue by xiaoyuchen** [magento/magento2#3783]
Magento 2 success install on Debian 8

Everything is working fine, only when click  "Web Setup Wizard" menu in admin page -> system -> tools -> web setup wizard it goes to 401 unauthorized access page. with message following.

"Welcome to Magento Admin, your online store headquarters.
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard "

In my server

rewrite is enabled
allowoverwrite all is enabled

**Comment by eddielau** [comment]
Hi @xiaoyuchen, we are aware of this issue. The fix should be pushed to develop branch soon. Internal ticket # MAGETWO-50492

**Comment by mazhalai** [comment]
@xiaoyuchen This issue has been fixed in the develop branch. Closing ticket for now. Please open a new issue, if you continue to have problems.
