### ISSUE TITLE
Difference in less compilation between php & nodejs library (grunt) with complicated `calc` expressions

### ISSUE THREAD

**Issue by hostep** [magento/magento2#37841]
### Preconditions and environment

- Magento version 2.4-develop
- PHP 8.1 or 8.2
- Nodejs 16

Other things to prepare here:
1. Setup vanilla Magento install
2. Run the following:
```shell
$ cp package.json.sample package.json
$ cp Gruntfile.js.sample Gruntfile.js
$ npm install
$ bin/magento deploy:mode:set developer  # so that when compiling less via php, it's not being minified, so that comparing files is easier
```
3. In the backoffice, go to Stores >Attributes > Product, and for both `news_from_date` and `news_to_date` perform the following change:
    - Storefront Properties > Use in Search > Yes
    - Storefront Properties > Visible in Advanced Search > Yes

### Steps to reproduce

1. First run the less compilation through the less library in php:
```shell
$ rm -R var/view_preprocessed/* pub/static/*
$ bin/magento setup:upgrade # needed to be able to visit frontend without js errors
$ bin/magento setup:static-content:deploy -f en_US
```
2. Now copy the resulting files in some other directory:
```shell
$ cp -r pub/static/ /tmp/magento-scd-comparison
```
3. In one tab in your browser,  visit the frontend of the shop and click on Advanced Search in the footer and keep this open
4. Now run the less compilation through grunt (so via nodejs instead of php):
```shell
$ rm -R var/view_preprocessed/* pub/static/*
$ bin/magento setup:upgrade # needed to be able to visit frontend without js errors
$ grunt clean:luma && grunt exec:luma && grunt less:luma
```
5. Now compare the resulting files with the ones you copied before, I'm focusing here on something very specific (not all changes are relevant or important here):
```shell
$ diff -u /tmp/magento-scd-comparison/frontend/Magento/luma/en_US/css/styles-m.css pub/static/frontend/Magento/luma/en_US/css/styles-m.css  | grep -C3 calc
```
Output:
```diff
-.form.search.advanced .fields.range .field.date input,
-.form-giftregistry-edit .field.date input {
-  margin-right: 10px;
-  width: calc(100% - 33px);
+.form-giftregistry-search .fields-specific-options .datetime-picker {
+  margin-right: 10px;width: calc(100% - 23px + 10px);
 }
 .field .control._with-tooltip {
   position: relative;
 }
 .field .control._with-tooltip input {
-  margin-right: 10px;
-  width: calc(100% - 36px);
+  margin-right: 10px;width: calc(100% - 21px + 10px + 5px);
 }
 .checkout-index-index .modal-popup .field-tooltip .field-tooltip-content,
 .shipping-policy-block.field-tooltip .field-tooltip-content {
```
6. In a second tab in your browser, visit the frontend of the shop and click on Advanced Search in the footer and compare it to your first tab

### Expected result

The `width: calc` expressions are the same between the PHP less library & nodejs less library:

```
less.js:
1. width: calc(100% - 23px + 10px);
2. width: calc(100% - 21px + 10px + 5px);

less.php:
1. width: calc(100% - 23px + 10px); or width: calc(100% - 13px);
2. width: calc(100% - 21px + 10px + 5px); or width: calc(100% - 6px);
```

### Actual result

The `width: calc` expressions are different between the PHP less library & nodejs less library:

```
less.js:
1. width: calc(100% - 23px + 10px);   => simplified: width: calc(100% - 13px);
2. width: calc(100% - 21px + 10px + 5px); => simplified: width: calc(100% - 6px);

less.php:
1. width: calc(100% - 33px);
2. width: calc(100% - 36px);
```

How it looks with less.js:

<img width="702" alt="Screenshot 2023-08-03 at 17 41 03" src="https://github.com/magento/magento2/assets/85479/0db0f2d2-8efc-4898-8552-88d6c9047b71">

How it looks with less.php:

<img width="715" alt="Screenshot 2023-08-03 at 17 38 36" src="https://github.com/magento/magento2/assets/85479/c8cb60e9-315d-4689-81e1-ac6ea1f09628">

### Additional information

You may be surprised by the screenshots, but reading [the original less code (which contains a bug)](https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/design/frontend/Magento/blank/web/css/source/_extends.less#L1222), it should be rendered like the less.js result (the bug can be fixed by changing `+ @indent__s` to `- @indent__s` which makes a lot more sense)

I've tried this again but with v4 of `wikimedia/less.php` (which is being used in Magento as php library to compile less, currently v3 is being installed). And v4 fixes this problem, I'm pretty much convinced this fixed it: https://github.com/wikimedia/less.php/commit/5ca673db6b416d0cf034a9b266d4b1a716905f58
> Fix this by recognising `calc()` higher up as something that server-side LESS math should not be performed on in the first place.

So the solution for Magento is to switch from v3 to v4 of `wikimedia/less.php`. An additional benefit is that v4 is slightly faster than v3, about 1 second faster average when running `bin/magento setup:static-content:deploy` with all 3 default Magento themes.

I'm currently working on a PR that will upgrade `wikimedia/less.php` to v4, but it's more complicated, some less code in Magento is not written correctly (especially around those `calc` expressions) and we'll need to tweak it bit.
Expect a PR soon (maybe today, maybe later this week)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hello @hostep,

Thank you for the report and collaboration!

We were able to reproduced the issue on 2.4-develop.
Please take a look at the screenshot:
![image](https://github.com/magento/magento2/assets/60198231/bc5368c3-5931-4636-9ed7-694a98d72682)

We  have followed your steps, and it can be seen that `width: calc` expression are different for less js and less php.
Hence confirming the issue.

Thank you.

**Comment by engcom-Bravo** [comment]
Hi @hostep,

Internal team has started to work on it.

Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-9712 by the internal team
Related commits: b34c0a7

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
