### ISSUE TITLE
js/theme & js/responsive files in wrong requirejs-config file?

### ISSUE THREAD

**Issue by gavinlimely** [magento/magento2#3784]
Should the js/theme & js/responsive dependencies be located in the Magento_Theme requirejs-config file? I've created a new theme that doesn't extend the blank theme & Magento is still trying to include js/theme & js/responsive even though I don't require them in the theme I'm creating. 

Would it make more sense for them to be included in the blank theme?

**Comment by gavinlimely** [comment]
any updates?

**Comment by piotrekkaminski** [comment]
@elenleonova  can you look into it? is it a bug?

**Comment by minlare** [comment]
This is a bug, workaround for now is to create blank files js/responsive.js and js/theme.js in the custom theme.

**Comment by anton-huz** [comment]
Yes, it is an issue. We are going to fix it in scope of MAGETWO-56478.
Please stay in touch.

**Comment by markdavies** [comment]
Any movement on this? Running into the same problem today.

**Comment by ghost** [comment]
Does anyone know if this issue has been/will be fixed? The suggested work around isn't really viable.
