### ISSUE TITLE
Possible data corruption using the AwsS3 driver

### ISSUE THREAD

**Issue by ImanuelBertrand** [magento/magento2#37844]
### Preconditions and environment

- Magento version: 2.4.6-p1 (but previous versions, too)
- Enabled the AwsS3 driver for remote storage

### Steps to reproduce

1. Using the S3 adapter, open a (new) file and write `AAAAA` to it and close it.
2. Open the file again, with mode `w`, and write `BB` to it.

### Expected result

The expected result is that the AwsS3 driver works as a replacement for the base default implementation (File driver).
[As documented by `fopen`](https://www.php.net/manual/de/function.fopen.php) for mode `w` is that the file should truncated and thus would now contain `BB`.

### Actual result

The file contains `BBAAA`

### Additional information

The root cause is that `\Magento\AwsS3\Driver\AwsS3::fileOpen($path, $mode)` does not check the `$mode` when opening the temporary stream.
It will always fetch the current contents of the object in S3, write it to the stream and then rewind the stream.
This effectively opens all files with mode `r+`, which is unexpected.

The impact of this is somehat migitated by the fact that the most common use of the adapter is saving image files, which are only written once and never directly overwritten.
Still, for any files that are updated (like product feeds), this can and will lead to data corruption.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ImanuelBertrand** [comment]
@magento I am working on this

**Comment by ImanuelBertrand** [comment]
@magento add to contributors team

**Comment by ImanuelBertrand** [comment]
Adobe Commerce support developers have confirmed this issue (ticket #647575):

> Our support developers have confirmed this issue is reproducible on a clean instance

**Comment by engcom-Hotel** [comment]
Hello @ImanuelBertrand,

Thanks for the report and collaboration!

Can you please let us know if you are using a custom module or any third-party extension to write the files on S3, if possible please share this information with us.

Thanks

**Comment by ImanuelBertrand** [comment]
Hi @engcom-Hotel,

I came across the issue while testing the S3 storage for a client, using a custom Google product feed module.
Unfortunately, I can't share the full module, but it shouldn't be necessary.
The relevant code is this:
`$this->filesystem->getDirectoryWrite('media')->writeFile($exportFilename, $data);`

Depending on whether new file was smaller than the previous one, this would result in a broken XML file.

Regards
Imanuel

**Comment by abukatar** [comment]
@magento I am working on this

**Comment by abukatar** [comment]
An internal team is working on this issue right now (as Jira ticket `ACP2E-2147`)

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-2147  by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-2147&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta3.

Thanks
