### ISSUE TITLE
Admin-> Store-> Tax Rules-> New==> "Calculate Off Subtotal Only" effect is not display at front-end->checkout.

### ISSUE THREAD

**Issue by sachinkalerws** [magento/magento2#3785]
Admin-> Store-> Tax Rules-> New==> "Calculate Off Subtotal Only" effect is not display at front-end->checkout.

![calculated off checkout](https://cloud.githubusercontent.com/assets/17641550/13774611/d9662bc0-eac5-11e5-8f62-b69067c1564d.jpg)

**Comment by mikeweis** [comment]
@sachinkalerws If possible, please provide some additional details on your configuration.

From your situation so far, here is what seems to be your basic config:
- one tax rate at 10%
- tax is applied to products, and not to shipping
- catalog prices are supplied with prices excluding tax
- shipping is a flat $5 per item

Your cart shows:
- 2 (taxable) t-shirts priced at $11/each, for a total of $22
- the product subtotal is $22
- (non-taxed) shipping at a total of $10
- 10% tax on the (taxable) subtotal of $22 is $2.20

It seems that everything is working A-OK.   However maybe my assumptions of your configuration is wrong; please update.

**Comment by mikeweis** [comment]
We are sorry, but we not able to reproduce this problem having no response from you.  Do not hesitate to contact us later if this problem is still present and provide requested details.

**Comment by vpkharabe** [comment]
I am facing the same issue in magento 1.9. can you give some insights on that
