### ISSUE TITLE
ProductRepository is loading initializationHelper which is an Adminhtml controller 

### ISSUE THREAD

**Issue by MrBlueEyez** [magento/magento2#37864]
### Summary

The `Magento\Catalog\Model\ProductRepository` is loading the `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` in its constructor, but then continues to not use it.

This, on a first look, doesn't seem to cause any issues. However when using some third party modules which extend the `PathInfoProcessor` and that uses the productRepository this is causing some issues with loading in di.xml configurations.

When trying to use the rest-api with an oauth authorization, the `Magento\Framework\App\Http` class is triggered, which first tries to get the area code of the current url. But then the custom logic by the third party is triggered, finally loading in the productRepository. The productRepository then tries to load the above mentioned adminhtml controller, which tries to access the roleLocatorInterface, which is now not based on the webapi_rest/di.xml, but on the default app/etc/di.xml. Causing the `Magento\Framework\Authorization\RoleLocator\DefaultRoleLocator` to be loaded instead of the `Magento\Framework\Authorization\RoleLocatorInterface\WebapiRoleLocator`. This last thing causes the authorization to fail, as the `DefaultRoleLocator` returns `''` instead of executing logic like the `WebapiRoleLocator`.

There is currently no workaround for this.

### Examples

The only thing that is required to be changed for this to work is to remove the `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper $initializationHelper,` in `Magento\Catalog\Model\ProductRepository` on line 225.

Which is causing this issue, and isn't being used in the file at all.

### Proposed solution

Remove the loading of `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper $initializationHelper,` inside the `Magento\Catalog\Model\ProductRepository`.

### Release note

Removing unused `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` from `Magento\Catalog\Model\ProductRepository`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MrBlueEyez** [comment]
Just been looking back into the history:
In 2.0.18 the helper is being used.
https://github.com/magento/magento2/blob/2.0.18/app/code/Magento/Catalog/Model/ProductRepository.php

But the usage is removed in 2.1.0 and beyond:
https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Catalog/Model/ProductRepository.php

**Comment by BeggiNN** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @MrBlueEyez,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch by looking into the codebase. And it seems the issue is reproducible for us.

`$this->initializationHelper` is not in use and the scenario mentioned in the main description seems valid.

Hence confirming the issue.

Thanks
