### ISSUE TITLE
Wrong Guest Customer email when placing an order by graphql using payment "paypal_express"  

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#37882]
### Preconditions and environment

- Magento version: 2.4.5-p2
the problem happened when we use this mutation 
 setPaymentMethodOnCart(input: {
      cart_id: "{{guest_cart_id}}"
      payment_method: {
          code: "paypal_express"
          paypal_express: {
              token: "EC-********"
              payer_id: "******"
          }
      }
  }) 
after paying the order

### Steps to reproduce

using Graphql
- createEmptyCart
- addSimpleProductsToCart
- setShippingAddressesOnCart
- setShippingMethodsOnCart 
- setBillingAddressOnCart
- setGuestEmailOnCart  (use for example **paypal@magento.com**)
- setPaymentMethodOnCart
- createPaypalExpressToken
-  redirect tp Pay Pal to pay (use any buyer email except the above email EX: buyer@paypal.com)
- setPaymentMethodOnCart (the problem start in this step)
- placeOrder

### Expected result

the Order email should be Customer Email "paypal@magento.com"

### Actual result

the Customer email in the order and in the addresses is the buyer email which is not correct

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @zexperto,

Thank you for reporting and collaboration.

We have tried to reproduce the issue on Magento 2.4-develop instance.

**Steps to reproduce**

using Graphql

- createEmptyCart
- addSimpleProductsToCart
- setShippingAddressesOnCart
- setShippingMethodsOnCart
- setBillingAddressOnCart
- setGuestEmailOnCart (use for example [paypal@magento.com](mailto:paypal@magento.com))
- setPaymentMethodOnCart
- createPaypalExpressToken
- redirect tp Pay Pal to pay (use any buyer email except the above email EX: [buyer@paypal.com](mailto:buyer@paypal.com))
- setPaymentMethodOnCart (the problem start in this step)
- placeOrder



We are able to set the Payment methods

<img width="1439" alt="Screenshot 2023-09-12 at 1 04 56 PM" src="https://github.com/magento/magento2/assets/51680745/b4abd702-4583-41fe-8df7-89c3c5f82b4d">



We are not able to proceed further with placeOrder mutation could you please let us know we are missing anything.


<img width="1448" alt="Screenshot 2023-09-12 at 1 03 43 PM" src="https://github.com/magento/magento2/assets/51680745/fb813bba-dbcc-402f-8390-2e586c8d9552">




We are getting error **Unable to place order: A server error stopped your order from being placed. Please try to place your order again**.

As per this document https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/place-order/ we will get this error when we don't have products in cart but we have products in cart.

<img width="1462" alt="Screenshot 2023-09-12 at 1 12 40 PM" src="https://github.com/magento/magento2/assets/51680745/bc3b5d3e-7125-4ba2-82d8-8a1cf2fdf9ca">


Could you please help us to proceed further.


Thanks.

**Comment by sheyandckap** [comment]
Hi, I also face the same issue and my magento version is Magento ver. 2.4.5-p1. These are the steps to reproduce the issue

01.Create an Empty Cart
mutation {
  createEmptyCart
}

02. setGuestEmailOnCart

mutation {
  setGuestEmailOnCart(input: {
    cart_id: "test"
    email: "test@gmail.com"
  }) {
    cart {
      email
    }
  }
}

03.Add products

mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "test"
      cart_items: [
        {
          parent_sku: "2018-test"
          data: {
            quantity: 1
            sku: "100-test-AI"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        uid
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
          }
        }
      }
    }
  }
}

04. Cart Query

{
  cart(cart_id: "test") {
    email
    items {
      id
      product {
        name
        sku
      }
      quantity
      errors {
        code
        message
      }
    }
  }
}

05.setShippingAddressesOnCart

mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "test"
      shipping_addresses: [
        {
          address: {
            firstname: "ss"
            lastname: "sst"
            company: "Company Name"
            street: ["test"]
            city: "Los Angeles"
            region: "CA"
            region_id: 12
            postcode: "90210"
            country_code: "US"
            telephone: "123-456-0000"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        firstname
        lastname
        company
        street
        city
        region {
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
        available_shipping_methods{
          carrier_code
          carrier_title
          method_code
          method_title
        }
      }
    }
  }
}

06. setBillingAddressOnCart

mutation {
  setBillingAddressOnCart(
    input: {
      cart_id: "test"
      billing_address: {
        address: {
          firstname: "ss"
          lastname: "sst"
          company: "Company Name"
          street: ["64 Strawberry Dr", "Beverly Hills"]
          city: "Los Angeles"
          region: "CA"
          region_id: 12
          postcode: "90210"
          country_code: "US"
          telephone: "123-456-0000"
          save_in_address_book: true
        }
      }
    }
  ) {
    cart {
      billing_address {
        firstname
        lastname
        company
        street
        city
        region{
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
      }
    }
  }
}

07.setShippingMethodsOnCart

mutation {
  setShippingMethodsOnCart(input: {
    cart_id: "test"
    shipping_methods: [
      {
        carrier_code: "custom-1"
        method_code: "custom"
      }
    ]
  }) {
    cart {
      shipping_addresses {
        selected_shipping_method {
          carrier_code
          method_code
          carrier_title
          method_title
        }
      }
    }
  }
}

08.createPaypalExpressToken


mutation {
  createPaypalExpressToken(
    input: {
      cart_id: "test"
      code: "paypal_express"
      express_button: true
      urls: {
        return_url: "paypal-return"
        cancel_url: "paypal-cancel"
      }
    }
  ) {
    token
    paypal_urls {
      start
      edit
    }
  }
}

09.setPaymentMethodOnCart


mutation {
  setPaymentMethodOnCart(input: {
    cart_id: "test"
    payment_method: {
      code: "paypal_express"
      paypal_express: {
        payer_id: "test123"
        token: "VB-test"
      }
    }
  }) {
    cart {
      selected_payment_method {
        code
        title
      }
    }
  }
}

10. Place order

mutation {
  placeOrder(
    input: {
      cart_id: "test"
    }
  ) {
    order {
      order_number
    }
  }
}


Order is able to place using these process but Order email is taken as the Paypal account email address which was used to sign in.

**Comment by sheyandckap** [comment]
Found the solution and I hope this will help for all. There is a patch for this already.
https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-29/acsd-49849-customer-email-was-replaced-with-paypal-email.html?lang=en

**Comment by engcom-Bravo** [comment]
@sheyandckap Thanks for your contribution & collaboration over here

Hi @zexperto,

Kindly refer this document https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-29/acsd-49849-customer-email-was-replaced-with-paypal-email.html?lang=en there is a patch already released.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/37824

Hence we are closing this issue.

Thanks.
