### ISSUE TITLE
Not getting customer id in the brain tree transaction object response.

### ISSUE THREAD

**Issue by prajeswari** [magento/magento2#37887]
### Preconditions and environment

Magento Version : 2.4.6 EE and 2.4.6 P1 EE

I am not getting customer id in the brain tree transaction response while using Magento 2.4.6 and 2.4.6 P1 EE with PWA venia-ui store. I have verified same in Magento 2.4.5 EE and 2.4.4 EE version I am getting customer id in the response.

### Steps to reproduce

-Install PWA venia store and point it to any of Magento 2.4.6 EE instance.
-configure braintree
-And place an order with Brain Tree and verify the transaction response.

### Expected result

Customer id should be there in the response

### Actual result

Customer id is not coming in the braintree response
Response In 2.4.6
![image](https://github.com/magento/magento2/assets/78781200/c2069318-4258-4045-9b56-2ce4156fff73)

### Additional information

Posted issue on magento pwa-studio
https://github.com/magento/pwa-studio/issues/4155

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @prajeswari ,

verified the issue in 2.4.7beta 1 instance the issue got reproducible,Hence we are confirming the issue.
Kindly refer the below screenshots:
![image](https://github.com/magento/magento2/assets/60198592/128fb01d-d282-47be-bf24-08caa3d3a6c6)

Thanks.

**Comment by engcom-Dash** [comment]
Hi @prajeswari ,

As per the internal discussion we need some information from your end,Could you please tell me did the payment either in luma side with PWA setup or With Venia side with PWA setup???

Thanks.

**Comment by prajeswari** [comment]
Hi @engcom-Dash 

I did the payment with venia side with PWA setup.

Thanks

**Comment by prajeswari** [comment]
Hi @engcom-Dash ,

Any update on this issue? I have a dependency on it.

**Comment by engcom-Dash** [comment]
Hi @prajeswari 

Thanks for reporting and collaboration.

Verified the issue in PWA venia instance and the issue is reproducible.

We are not getting the customer id in the Braintree transaction object response.

Please refer the attached screenshot.
<img width="820" alt="37887-Confirmed" src="https://github.com/magento/magento2/assets/60198592/3f18a493-76a5-4155-81c7-aabf4a0c1222">
