### ISSUE TITLE
Currency code not change in New product widget

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#37898]
### Preconditions and environment

- Magento version 2.4-develop
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Setup multi currency in admin in Stores -> Configuration -> General -> Currency Setup
2. Add new product widget in homepage cms: {{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" show_pager="0" products_count="10" template="product/widget/new/content/new_grid.phtml"}} 
3. Change value attribute Set Product as New From with current date for some random product
4. In frontend change currency in header

### Expected result

Currency code product in widget displays the same as the currency selected in frontend

### Actual result

Currency code not change when change currency in frontend

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @rogerdz,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the 2.4-develop branch and it seems the issue has been reproducible for us. In the widget, the currency is not changing as per selection.

Please have a look at the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/2938b300-6e73-40e7-9e99-a9ce2392dc47)

Hence confirming the issue.

Thanks

**Comment by andrewbess** [comment]
Hello @rogerdz 
Your fixes look good for me and approved from my side.
Thank you for your contribution

cc @engcom-Hotel

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance
