### ISSUE TITLE
Product-> Configure Product-> Advance Inventory==> "Qty increments" functionality is not working.

### ISSUE THREAD

**Issue by sachinkalerws** [magento/magento2#3790]
Product-> Configure Product-> Advance Inventory==>
"Qty increments" functionality is not working.

![qty increment](https://cloud.githubusercontent.com/assets/17641550/13778419/a888533c-eadb-11e5-8da8-e80c60b30303.jpg)

**Comment by antboiko** [comment]
Hello @sachinkalerws , thanks for your inquiry. What Magento version do you use?

Could you please provide detailed steps to reproduce the issue?

Thanks,
Anton.

**Comment by piotrekkaminski** [comment]
Closing due to lack of response. If issue persist please open new ticket with detailed steps to reproduce.
