### ISSUE TITLE
Product websites are reset on update via REST API

### ISSUE THREAD

**Issue by neran** [magento/magento2#3792]
Hi,

I have 2 websites setup in Magento and products associated to both websites.
After I update a product via REST, the product is linked only to "Main Website". 
How can I update a product without changing the linked websites?

Thanks is advance!

**Comment by PingusPepan** [comment]
I have the same question.

**Comment by maksek** [comment]
Please ask questions in Forum. GitHub only for issue reporting with steps to reproduce.

**Comment by mslabko** [comment]
Hi @neran ,

I cannot reproduce this on develop branch.

Also, please check my comment, maybe it can help to solve your issue: https://github.com/magento/magento2/issues/4493#issuecomment-219752128

**Comment by slavvka** [comment]
Hi all, the fix has been delivered to mainline.
