### ISSUE TITLE
Invalid PHP 8 Notation in PHP 7.4 code

### ISSUE THREAD

**Issue by floshontay** [magento/magento2#37935]
### Preconditions and environment

- Magento version 2.4.4-p5

### Steps to reproduce

when running 
```
composer require-commerce magento/product-community-edition 2.4.4-p5 --no-update
composer update
```

with PHP 7.4 there is also PHP 8 syntax fetched.

in `vendor/paypal/module-braintree-core/Gateway/Command/GetPaymentNonceCommand.php`

there is the line
`public function execute(array $commandSubject): ArrayResult|ResultInterface|null`

which results in an exception if you run the application with PHP 7.4

### Expected result

The application should run

### Actual result

You always get an exception because of invalid syntax

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by floshontay** [comment]
OK it is definitely reproducible from 2.4.4-p2 upgrading to 2.4.4-p5 running composer with php7.4!

**Comment by andrewbess** [comment]
Hello @floshontay 
Thank you for your collaboration.
Could you please check [the system requirements document](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html).
The Magento 2.4.4 is not compatible with PHP 7.4.

I closed this issue due to reason described above.
