### ISSUE TITLE
Cart Price Rules Not Working as Intended

### ISSUE THREAD

**Issue by sgautamrave** [magento/magento2#37931]
### Preconditions and environment

- Magento version: 2.4.6-p2
- PHP - 8.1

### Steps to reproduce

Both cart price rule are without coupon code.

1) Create 1st cart rule named (Rule 1) where priority is set to 1 , conditions section have if a particular product(Joust Duffle Bag) with sku(24-MB01) have 5 or more qty in cart than 25% discount should be applied on that product and here discard subsequent rule is enable
Screenshot - https://prnt.sc/6TRdJ7R13KdD
Screenshot - https://prnt.sc/5o-v0mJY_90W

2) Create 2nd cart rule name (Rule 2) where priority is set to 2, conditions section have if subtotal is equals or greater than $50 than apply 35% on any of the product present in the cart and here discard subsequent rule is not enabled.
Screenshot - https://prnt.sc/OY6z3scgalTq
Screenshot - https://prnt.sc/qXbSD70yy54w

3) On frontend add joust duffle bag with 4 qtys and affirm water bottle with 3 qtys
Screenshot - https://prnt.sc/8Tmqb_NRnPlH

### Expected result

Product Joust Duffle Bag and Affirm Water Bottle both products will have 35% discount each.

### Actual result

Product Joust Duffle Bag doesn't get any discount and on Affirm Water Bottle we get 35% discount

### Additional information

This is the extended issue from this one - https://github.com/magento/magento2/issues/35707
From this issue I have utilised fix from id - [09384df](https://github.com/magento/magento2/commit/09384dfebbab1d98af2e3fa9ddced25830925a08) In file vendor/magento/module-sales-rule/Model/Quote/Discount.php

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by sgautamrave** [comment]
Hello @engcom-Bravo ,

The screenshots and cases which I have shared with you is tested on magento vanilla instance 2.4.6-p2 and I have applied fix on this file - vendor/magento/module-sales-rule/Model/Quote/Discount.php from this commit [09384df](https://github.com/magento/magento2/commit/09384dfebbab1d98af2e3fa9ddced25830925a08)

Can you mention any other thing I'm missing from this commit id ? It would be great help to me.

Thanks,

**Comment by engcom-Bravo** [comment]
Hi @sgautamrave,

Thanks for your update.

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1300 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1300&type=commits

After applying commits still you are facing any issue  please let us know you need more assistance.


Thanks

**Comment by sgautamrave** [comment]
Hello @engcom-Bravo ,

Thank you for sharing the commits.
I will add those fixes and check if it resolves or not.

Thanks,

**Comment by engcom-Bravo** [comment]
Hi @sgautamrave,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by sgautamrave** [comment]
Hello @engcom-Bravo ,

Yes this issue is fixed by applying given patches list.
I utilised these 2 files code for fixing the issue.
vendor/magento/module-sales-rule/Model/Quote/Discount.php
vendor/magento/module-sales-rule/Model/RulesApplier.php

Thanks,

**Comment by mohammedTBB** [comment]
@engcom-Bravo @sgautamrave Is there a patch/quality patch that can be applied?

**Comment by sgautamrave** [comment]
Hello @mohammedTBB ,

I was provided a list of files with modifications. I have created my own patches to fix this issue.
Attaching above mentioned files patches. Hope it might be helpful to you.
[cart-price-rule-patches.zip](https://github.com/magento/magento2/files/13842412/cart-price-rule-patches.zip)

**Comment by mohammedTBB** [comment]
@sgautamrave Thanks.
