### ISSUE TITLE
Magento 2 Extension API is not accessiable via integration access token

### ISSUE THREAD

**Issue by YouCanDoIt12** [magento/magento2#37948]
### Preconditions and environment

- Magento version 2.4.6
- Create any extension which have get API , make the call from postMan using access token , it will throw error below
{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Celigo_Magento2NetSuiteConnector::celigo"
    },
Even though access is given for celigo extension token

### Steps to reproduce

- Create any extension which have get API , make the call from postMan using access token , it will throw error below
{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Celigo_Magento2NetSuiteConnector::celigo"
    },
Even though access is given for celigo extension token

### Expected result

API should return the results instead if AUth error

### Actual result

{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Celigo_Magento2NetSuiteConnector::celigo"
    },

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @YouCanDoIt12,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have created a integration and we are able to get the response.


<img width="1162" alt="Screenshot 2023-09-04 at 3 16 25 PM" src="https://github.com/magento/magento2/assets/51680745/bea0c312-a367-44b4-b2ae-a65cbefe0315">




Could you please elaborate the steps to reproduce and provide for which payload you are facing the issue and also provide screenshots if possible it is helpful to reproduce the issue easily.


Thanks.

**Comment by YouCanDoIt12** [comment]
@engcom-Bravo this is working fine for native Magento 2 rest API, 
but not working for the API added via Magento2 Extension modules
Please check any API which is in custom modules

**Comment by YouCanDoIt12** [comment]
@engcom-Bravo , you can install this extension for example https://commercemarketplace.adobe.com/celigo-magento2-netsuite-connector.html
and make the GET  API call
/V1/getCeligoModuleVersion to reproduce this issue

**Comment by engcom-Bravo** [comment]
Hi @YouCanDoIt12,

Thanks for your update.

“Celigo NetSuite Connector ” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by YouCanDoIt12** [comment]
Dear @engcom-Bravo

I hope this message finds you well. I am writing to address a critical issue that pertains not only to our Extension code but, more broadly, to the Magento 2 codebase. Specifically, the problem at hand revolves around the inability to utilize Access Tokens for authorizing custom APIs—a functionality that was previously supported.

I kindly request that you consider reopening this issue, as it has far-reaching implications for our extension and the Magento 2 community as a whole. The use of Access Tokens for API authorization is a fundamental requirement in modern e-commerce development, and its absence poses significant challenges.

It is worth noting that we diligently followed the Magento 2 documentation while building the Extension functionality, which leads us to believe that the issue resides within the core Magento 2 codebase. We are committed to working collaboratively to find a resolution to this matter.

Should this concern not fall within the scope of your responsibility, I kindly ask for guidance on the appropriate channel through which to escalate this issue. As the owner of the aforementioned extension, I am dedicated to ensuring the highest standards of functionality and security for our users.

Your attention to this matter is greatly appreciated, and I look forward to your guidance or further assistance in addressing this issue promptly.

Thank you for your time and consideration.
