### ISSUE TITLE
Need configurable product price from Rest V1 Products Web API

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#3794]
We are using http://[Domain]/rest/V1/products/[SKU]

Here we are specifying SKU of configurable product but in return we are getting price value 0.
If we look into admin here in product grid configurable product price is showing and also in 'catalog_product_index_price' table we found entry for configurable product with price but price is not showing in response of API.
'<price>0</price>'

Please let me know how can we get configurable product price using Rest V1 WebAPI.

Thanks!

**Comment by wozniakm** [comment]
You should call API by `GET /V1/configurable-products/{sku}/children` to get simple products linked to your configurable product and then you will have price for each of them.

**Comment by ankursachdeva11** [comment]
Hi @wozniakm,
By calling their children, we can get price for each simple product.
but i need price of configurable product when i call API /V1/products/[SKU] here price is showing zero.
This is my concern why this price is 0.

**Comment by ankursachdeva11** [comment]
Hi, 
I have a scenario,
i have tried to load a configurable product with price 1000 in magento2 using product id in $product variable.

When we print $product->getData('price') then it shows us 1000
but when we print $product->getPrice(); then it shows us 0

please check why this is happening?

**Comment by wozniakm** [comment]
That's because of the following code:

```
public function getPrice()
    {
        if ($this->_calculatePrice || !$this->getData(self::PRICE)) {
            return $this->getPriceModel()->getPrice($this);
        } else {
            return $this->getData(self::PRICE);
        }
    }
```

If you call getPrice method returned value is calculated based on price model from configurable product bundle. The called method implementation is:

```
public function getPrice($product)
    {
        if ($product->getCustomOption('simple_product')) {
            return $product->getCustomOption('simple_product')->getProduct()->getPrice();
        } else {
            return 0;
        }
    }
```

Probably you can play around with customOption named simple_product. You have to investigate more. I think that this behavior should be expected, configurable product is just a wrapper for simple products, it should not contain price itself.

**Comment by maksek** [comment]
Please ask questions in Forum. GitHub only for issue reporting with steps to reproduce.

**Comment by msliman** [comment]
@ankursachdeva11 , Did you find a solution for this problem ? I am stuck in .
