### ISSUE TITLE
https Rabbit MQ heartbeat issues

### ISSUE THREAD

**Issue by frostblogNet** [magento/magento2#37947]
### Preconditions and environment

- Magento| Adobe Commerce 2.4.5 | 2.4.6 
- If you connect Magento a AWS RabbitMQ over https connection will be closed after about 10 minutes due to an heartbeat issue with is probably fixed in 3.5.3  see https://github.com/php-amqplib/php-amqplib/milestone/31?closed=1
- The problem only occure when https is used which is the default for aws rabbit mq.

### Steps to reproduce

Setup Magento 2.4.5 or 2.4.6 and connect it to a AWS Rabbit MQ using https. Set Stock Update to Async in the Backend. Start the consumer and send Stock update Messages to the Rest-Api. 

After about 10 minutes the consumer will stock processing  this messages. Only after a restart of the consumer he will continue processing.

### Expected result

The consumer will send proper heartbeat to the rabbit mq and will continue processing messages until we will be stopped.

### Actual result

consumer is running with a broken connection and will not process messages

### Release note

php-amqplib/php-amqplib needed update due to heartbeat issue over https

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @frostblogNet,

Thanks for the report and collaboration!

We are trying to reproduce the issue in 2.4-develop, meanwhile, we have a query, can you please let us know if you are using any third-party extension for the below step:

> Set Stock Update to Async in the Backend. Start the consumer and send Stock update Messages to the Rest-Api.

Can you please elaborate on the above point a little bit more?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @frostblogNet,

We have noticed that this issue has not been updated for a long period. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
