### ISSUE TITLE
Unable to receive mails from Magento 2

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#3800]
Steps to reproduce
1.Create a customer
Observation:
No mail sent 
2.Place an order
Observation:
no mail sent
3.Click on forget password in login page
Observation:
No mail sent

I have added the SMTP details as well 
NOTE: I receive the test email from the Magepal extension that i have used for SMTP
![mail_setting](https://cloud.githubusercontent.com/assets/17591809/13802584/6b893ebe-eb63-11e5-87c0-4431b163a7ec.png)

**Comment by troncar** [comment]
@Deepthi57 I have the same problem

**Comment by mazhalai** [comment]
@Deepthi57 @troncar Thank you for reporting, we have created MAGETWO-50850 to investigate and fix.

**Comment by arkadiych** [comment]
@Deepthi57, looks like you use 3rd party module for your purposes. 
Try to check, if it works without 3rd party module. 
- Set up email settings for your web server;
- Verify that you can send and receive email using php function "mail";
- Check Stores->Configuration-> Advanced->System->Mail Sending Settings. Email Communication is enabled.
- Check Stores->Configuration-> Sales->Sales Emails->Order . Enabled is "Yes". 
  I verified mailing process in Magento and got emails.
  Let us know with details, if you are faced with the problem without 3rd party modules.

**Comment by sshrewz** [comment]
@Deepthi57, since we have not heard back from you, we will go ahead and close this issue.  In case you have any updates, do feel free to reopen.

**Comment by deepak-netwin** [comment]
@Deepthi57 Hi, How can I set cronjob on server in Magento2?

**Comment by deepthit57** [comment]
@deepak-netwin 
Hi You can do the settings in root
1.cd /
2.sudo crontab -e
3.(Enter your cron setting as per your need)
In my case where I have named my instance as ee2.1.2
* * * * * /usr/bin/php /var/www/html/ee2.1.2/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/ee2.1.2/var/log/magento.cron.log
