### ISSUE TITLE
Error thrown while accessing customer/account/loginPost/ action directly.

### ISSUE THREAD

**Issue by rohitkundale** [magento/magento2#3801]
## Steps to reproduce
1. Install Magento ver. 2.0.2 from https://www.magentocommerce.com/download.
2. Access URL : http://magento/customer/account/loginPost/
## Expected result
1. If user logged in he/she will redirect to account dashboard page.
2. If user not logged in he/she will redirect to  login page.
## Actual result
1. Error[Warning] thrown. See screen shot.
   ![error_m2](https://cloud.githubusercontent.com/assets/10629382/13804239/55784346-eb71-11e5-960f-62b2145191f1.png)

**Comment by vzaporozhets** [comment]
@rpmkhatri - thanks for contacting us. Can you please define and use FQDN for magento server?

**Comment by rohitkundale** [comment]
@vzaporozhets 
This error is occurred in my localhost. 
Is it required to define and use FQDN?

Please elaborate.

**Comment by vzaporozhets** [comment]
@rpmkhatri It doesn't solve any problem but it's a common practice. You can easy modify your "hosts"-file with any FQDN-compatible alias what you want. But don't forget to use the same alias in base url while installing Magento.

**Comment by vzaporozhets** [comment]
@rpmkhatri Did you try my advice above? Any changes?

**Comment by rohitkundale** [comment]
Yes, I have tried. Still same error comes.

**Comment by vzaporozhets** [comment]
@rpmkhatri, thanks for providing details - I have reproduced this issue with 2.0.4. However, it works fine with "develop"-version. But I can provide you with solution which works fine for both versions: try to use URL like: "http://magento.vg/customer/account/" and your acceptance criteria will be satisfied.
I'm going to close this issue unless workaround doesn't work for you for some reason.
