### ISSUE TITLE
false-negative "Invaild template file"

### ISSUE THREAD

**Issue by tlaziuk** [magento/magento2#3802]
While using the `modman` I issued error which occurs when a module is placed somewhere outside the Magento 2 root directory. This is not the `modman`-related things because it can be reproduced to any module which is placed outside the Magento 2 root.

I found out the Magento2 fails where the template is validating against `isFile` (at `\Magento\Framework\View\Element\Template\File\Validator::isValid`).

I've also managed to fix that by changing the `\Magento\Framework\Filesystem\Directory\Read::isFile` method which is used to validate the template file. The problem is that method by default is joining the passed argument `$path` with the Magento 2 root, while the template file symlink is a resolved path to the real file.

You can preview my changes in the [`diff`](https://github.com/magento/magento2/files/175473/magento2.diff.zip) file.

## Preconditions
1. Magento 2.
## Steps to reproduce
1. Create module which is using frontend templates and place the code somewhere outside the Magento 2 root directory, but symlink the code to the place under Magento 2 project where it should be.
2. Setup your new module.
## Expected result
1. If the template file is valid, everything should be working
## Actual result
1. `system.log` message: `main.CRITICAL: Invalid template file: '/home/tlaziuk/git/Example_Module/view/frontend/templates/example.phtml' in module: 'Polcode_GoogleTagManager' block's name: 'googletagmanager' [] []`

**Comment by mazhalai** [comment]
@tlaziuk Thank you for reporting, we have created MAGETWO-50851 to investigate and fix.

**Comment by magento-engcom-team** [comment]
@tlaziuk, thank you for your report.
We've created internal ticket(s) MAGETWO-84536 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tlaziuk, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
