### ISSUE TITLE
Magento API to upload pdf file in downloadable products

### ISSUE THREAD

**Issue by nitish771** [magento/magento2#38034]
### Summary

Is there any api in magento which i can use to upload pdf file to download products ?

### Examples

I searched for official docs but couldn't find endpoint

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @nitish771,

Thank you for reporting and collaboration.

Could you please check this document https://developer.adobe.com/commerce/webapi/rest/quick-reference/

Example API :

**/rest/default/V1/products/{sku}/downloadable-links/{id}**


```
{
  "link": {
    "id": 0,
    "title": "string",
    "sort_order": 0,
    "is_shareable": 0,
    "price": 0,
    "number_of_downloads": 0,
    "link_type": "string",
    "link_file": "string",
    "link_file_content": {
      "file_data": "string",
      "name": "string",
      "extension_attributes": {}
    },
    "link_url": "string",
    "sample_type": "string",
    "sample_file": "string",
    "sample_file_content": {
      "file_data": "string",
      "name": "string",
      "extension_attributes": {}
    },
    "sample_url": "string",
    "extension_attributes": {}
  },
  "isGlobalScopeContent": true
}
```


Please let us know if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @nitish771,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
