### ISSUE TITLE
DI compile / PHPScanner aborts with Undefined array key -1 when an extension has an un-namespaced PHP class in an include-file and calls that class with new ...

### ISSUE THREAD

**Issue by bst-biwac** [magento/magento2#38044]
### Preconditions and environment

- Magento version 2.4.6-p2

- 3rd party extension that has a PHP class XYZ with no namespace in a library file and a statement "$xyz = new XYZ()" in another library file (bad practice I know)

### Steps to reproduce

3rd party extension that has a PHP class XYZ with no namespace in a library file and a statement "$xyz = new XYZ()" in another library file  (all within app/code/vendor/module/..)

CLI: run bin/magento setup:di:compile

### Expected result

DI compiled

### Actual result

Warning: Undefined array key -1 in setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php on line 227

no DI compiled

### Additional information

CLI setup:di:compile with the same 3rd extension setup, but on Magento 2.3.2, ran through

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bst-biwac** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @bst-biwac,

Thank you for reporting and collaboration.

Third Party Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
