### ISSUE TITLE
Gift Message on Guest Carts not saving

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#3804]
## Steps to reproduce
1. Configure Magento for Gift Message at Item Level
2. Add product to basket (not logged in as customer)
3. Add Gift Message details
4. Click Update
## Expected result
1. Gift Message is saved against the line item
## Actual result
1. 404 error is returned from Ajax call

Cause:
:cartId placeholder is not replaced in Url because the giftMessage js object does not have a config value of quoteId.
Key file: vendor/magento/module-gift-message/view/frontend/web/js/action/gift-options.js

**Comment by ishakhsuvarov** [comment]
@alexgoodey Thank you for reporting this issue.
Did you flush caches after applying settings?
Please let us know which Magento version you are using.

Thank you.

**Comment by alexgoodey** [comment]
Yes, all caches have been flushed.
Magento CE 2.0.2

**Comment by AndreyChorniy** [comment]
Hello guys. I have the same problem with Gift messages

**Comment by AndreyChorniy** [comment]
@ishakhsuvarov 
Hi.
Do you have any news about this issue?
Thanks.

**Comment by ishakhsuvarov** [comment]
@alexgoodey @AndreyChorniy Thank you for reporting this issue. We have investigated the problem and created an internal ticket `MAGETWO-50561` to fix it.

**Comment by AndreyChorniy** [comment]
@ishakhsuvarov Thanks.

**Comment by ishakhsuvarov** [comment]
@alexgoodey @AndreyChorniy Closing this ticket for now as the fix for this issue has been delivered to the `develop` branch with the commit linked to this issue. Please feel free to reopen if you have any additional questions.

**Comment by dexterityzx** [comment]
Still having this issue on Magento 2.0.7.
