### ISSUE TITLE
Show all values in attribute drop down/select list on configurable product page

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#38047]
### Summary

Magento version 2.4.4

Customization:
I want to do customization on configurable product page.
here are thing which i need to implement:
1. show values in every attribute select list (remove depending to select one attribute then fill another). so when page load it showing all option values for every attribute.
2. hide/ pre select if attribute have have single value in select list.
3. last one when any attribute select, it should redirect to selected attribute combination simple product page.

### Examples

implement this kind of feature using custom code 
https://magento2demo.firebearstudio.com/catalog/product/view/id/1808/s/breathe-easy-tank-l-yellow/ 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @hemendraajmera,

This platform is to report the bugs related to Magento Core. For these kinds of queries, you can raise queries on [Magento Stackexchange](https://magento.stackexchange.com/).

Thanks
