### ISSUE TITLE
Reward Points Earning Rules no longer working 

### ISSUE THREAD

**Issue by JJupi** [magento/magento2#38051]
### Preconditions and environment

Orders placed through the e-commerce store no longer assign point to signed in curstomers

### Steps to reproduce

1. Marketing
2. Promotions
3. Reward Points Earning Rules
4. X points for Y $ spent

### Expected result

X points for Y $ spent

### Actual result

no points are being assigned after placing an order

**Comment by JJupi** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @JJupi,

Thank you for reporting and collaboration.

Could you please elaborate the steps to reproduce Reward Points Earning Rules we are not able to view the option in Promotions. it will helps us to proceed further.

<img width="584" alt="Screenshot 2023-10-09 at 12 40 18 PM" src="https://github.com/magento/magento2/assets/51680745/28001e55-f52e-4720-84e9-fc4b2083fd02">


If possible please provide us screenshots and attached video.


Thanks.

**Comment by JJupi** [comment]
<img width="385" alt="Screenshot 2023-10-10 at 9 00 39 am" src="https://github.com/magento/magento2/assets/147351798/e354c168-85b1-4f11-932d-1c9343851beb">
So this is actually a function provided by Amasty. I got in touch with the team in regards to this issue but apparently, everything is fine. However, the reward points are still not working and I have to figure out why.

**Comment by engcom-Bravo** [comment]
Hi @JJupi,

Thanks for your update.

“Amasty” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
