### ISSUE TITLE
Incorrect $headers for CURLOPT_HTTPHEADER in class \Magento\Framework\HTTP\Adapter\Curl

### ISSUE THREAD

**Issue by Sgeleon2000** [magento/magento2#38058]
### Summary

Sometimes we can get incorrect $headers array for CURLOPT_HTTPHEADER in class  \Magento\Framework\HTTP\Adapter\Curl which accepts only  like this:
```
An array of HTTP header fields to set, in the format array('Content-type: text/plain', 'Content-length: 100')
```
But we can get this variable like this:
```
array('Content-type' =>  'text/plain', 'Content-length' =>  '100')
```
where key is name of header, value is param of header.

"magento/product-community-edition": "v2.4.6-p2"

### Examples

You can use this code for reproduce this bug:

```
 /** @var \Magento\Framework\HTTP\LaminasClient $client */
            $client = $this->httpClientFactory->create();

            $client->setUri($uri);
            $client->setOptions(self::CONFIG);
            $client->setMethod($method);

            if ($params) {
                $client->setRawBody(\json_encode($params));
            }

            if ($headers) {
                $client->setHeaders($headers);
            } else {
                $client->setHeaders([
                    "Content-Type" => 'application/json'
                ]);
            }

            $response = $client->send();
```

### Proposed solution

In the class Magento\Framework\HTTP\LaminasClient which implement for \Laminas\Http\Client\Client using as adapter class \Magento\Framework\HTTP\Adapter\Curl

![image](https://github.com/magento/magento2/assets/75261093/0de34dd5-4404-45be-af43-4fe6464711de)

When we are sending headers, we  are using class Laminas\Http\Headers

![image](https://github.com/magento/magento2/assets/75261093/0929190e-8309-4c00-91c2-8c83b4633d1a)

which give us array where key is name of header, value is param of header when we make request.

![image](https://github.com/magento/magento2/assets/75261093/0d112d2b-c608-4b50-af1a-3b1a5b5f1d23)

And then  in the class Magento\Framework\HTTP\Adapter\Curl we have got incorrect array of headers.

![image](https://github.com/magento/magento2/assets/75261093/bdbc095d-f123-4071-a785-2b0038875eb2)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @Sgeleon2000,

Thank you for the report and collaboration!

Please report the issue in proper format, you can refer the below link for the same, https://developer.adobe.com/commerce/contributor/guides/code-contributions/#report-an-issue
And it would be great if you could provide a screenshot or logs of the issue as well.

Thanks.

**Comment by engcom-November** [comment]
Hello @Sgeleon2000,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thabk you.
