### ISSUE TITLE
Exported products .csv file does not appear

### ISSUE THREAD

**Issue by MYC-Luuk-Tommy** [magento/magento2#38065]
### Summary

We are trying to get an export of all our products. However, we continue getting the following message: "Message is added to the queue, wait to get your file soon. Make sure your cron job is running to export the file". After multiple attempts, we haven't found anything yet. Which means that for some reason the file has not been downloaded.

Could anyone advise on how we might get this file downloaded after all?

### Examples

Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @MYC-Luuk-Tommy,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance.Kindly refer the attached video.




https://github.com/magento/magento2/assets/51680745/6399b6e4-a4b6-41d6-8944-e5784a83d1fe





After Exporting the product CSV file please try to run `bin/magento cron:run` the export file will be appeared and you can download from the list.Please let us know still if you are facing any issue.


Thanks.

**Comment by MYC-Luuk-Tommy** [comment]
Thanks for your quick reply!
However, when doing this we get the following message: "zsh: no such file or directory: bin/magento". 

Do you know what the issue is?

**Comment by engcom-Bravo** [comment]
Hi @MYC-Luuk-Tommy,

Thanks for your update.


We have to run this command `bin/magento` cron:run in Magento directory.



<img width="777" alt="Screenshot 2023-10-13 at 11 31 53 AM" src="https://github.com/magento/magento2/assets/51680745/914a42e6-8966-4c2c-8ee8-2b106e97fb78">



Please let us know if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @MYC-Luuk-Tommy,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
