### ISSUE TITLE
PDF Invoice issue

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3807]
## Steps to reproduce
1. Login into backend with your details.
2. Go to Sales  > Orders > Open any order whose invoice is generated[If not generated please generate it]
3. On order view page click on invoice tab, you can see invoice grid, tick mark on first invoice and click on PDF invoice. 
## Expected result
1. It shold contain only current invoice copy.
## Actual result

1.Generated PDF contain all orders invoice rather then current invoice copy.

**Comment by NadiyaS** [comment]
Hi @keyurshah070,

thank you for reporting this issue.
Internal ticket was created MAGETWO-50718.

**Comment by NadiyaS** [comment]
Hi @keyurshah070 ,
the fix was delivered to develop branch. This ticket is closed as resolved. 
Feel free to reopen this issue if you still can reproduce this bug.

**Comment by keyurshah070** [comment]
@NadiyaS 

Thank you for resolving this issue.
