### ISSUE TITLE
On multiple website customer doesn't display of other website on customer grid

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3808]
## Steps to reproduce
1. Create second website,store and store view from Stores > All stores
2. Create a new customer for newly created website from Customer > All Customers. 
3. After creating customer , just go to customer list from Customer > All Customers. 
## Expected result
1. It should display all customers on customer grid.
## Actual result
1. You are not able to see newly created customer, you can see customer only from main website.
2. Even On website filter you are not able to see newly customer.
3. When you access this customer from directly URL[After changing customer id on url], you can see that newly created customer

**Comment by sevos1984** [comment]
Try reindex customer grid by running "bin/magento indexer:reindex customer_grid "

**Comment by keyurshah070** [comment]
@sevos1984 Thanks its working now..you can close this bug
