### ISSUE TITLE
Cant Complete install of Magento  Latest

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#38081]
### Preconditions and environment

- Magento version
  "magento/product-community-edition": "2.4.6-p3",

- Anything else that would help a developer reproduce the bug
We had installed the magento via Composer, composer version is 2.5.5

after installing going to the browser to complete the setup process, we are getting a error like 

[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

And the domain is being redicted to site.com/pub/setup and above message is showing in Google Chrome

So we cant complet the setup

### Steps to reproduce

1. Install composer 2.5.5
2. Now Install the magneto latest via composer on root , in our case its was /home/public_html/
3. Try visit the Website via browser to complete the install
4. You will see redirect loop

### Expected result

The setup loads so that we can complete the install

### Actual result

Showing 

This page isn’t working
site.com redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ebofi** [comment]
@magento give me 2.4.6-p3

**Comment by ebofi** [comment]
@magento give me 2.4.6-p3 instance

**Comment by engcom-Bravo** [comment]
Hi @ebofi,

Thank you for reporting and collaboration.

Kindly check the system requirements https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html as per this doc Magento version 2.4.6-p3 supports with Composer 2.2.

Please try to install with Magento with the Composer 2.2 and let us know if you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @ebofi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
