### ISSUE TITLE
Modules should have their own dependencies

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3809]
I just stumbled into the fact that `module-shipping` requires zendframework/zend-http for its unit tests. So basically if I just want to do the tests of that module isolated (my module depends on that module again), I can't do that now as the requirements are not met. 

So my proposal is that every module composer.json should specify the requirements needed to use that module stand-alone (the tests e.g.). 

Probably has some impact, but it will improve module development imo.

**Comment by mazhalai** [comment]
Related internal ticket MAGETWO-31454

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Modules-should-have-their-own-dependencies/idi-p/46405).
