### ISSUE TITLE
Magento 2 customization of main and 404 page

### ISSUE THREAD

**Issue by polyakovao** [magento/magento2#3810]
Hello.
I'm trying to customise main page (home page) in magento 2 and also 404 page. Has anybody faced with the problem of adding some modules to this pages?!
Will be greatful for any suggestions.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
