### ISSUE TITLE
main.ERROR: Magento\Framework\Exception\InputException: Can not resolve reCAPTCHA parameter. in /data/web/public/vendor/magento/module-re-captcha-ui/Model/CaptchaResponseResolver.php:25

### ISSUE THREAD

**Issue by timpea-splat** [magento/magento2#38101]
### Preconditions and environment

- Magento Version: 2.4.6-p3, issue also occurred on earlier versions

### Steps to reproduce

Not found a way to reproduce the error every time.

1. Configuration > Security > Google ReCaptcha StoreFront
2. Enable reCaptcha v2 Invisible

We are receiving this error roughly 2-3 times a day.  ReCaptcha works correctly when testing with no error.

### Expected result

No error

### Actual result

```
Error in exception.log:
[2023-10-19T09:31:16.313374+00:00] main.ERROR: Magento\Framework\Exception\InputException: Can not resolve reCAPTCHA parameter. in /data/web/public/vendor/magento/module-re-captcha-ui/Model/CaptchaResponseResolver.php:25
Stack trace:
#0 /data/web/public/vendor/magento/module-re-captcha-ui/Model/RequestHandler.php(112): Magento\ReCaptchaUi\Model\CaptchaResponseResolver->resolve()
#1 /data/web/public/vendor/magento/module-re-captcha-customer/Observer/CreateCustomerObserver.php(67): Magento\ReCaptchaUi\Model\RequestHandler->execute()
#2 /data/web/public/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\ReCaptchaCustomer\Observer\CreateCustomerObserver->execute()
#3 /data/web/public/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#4 /data/web/public/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#5 /data/web/public/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#6 /data/web/public/vendor/magento/framework/App/FrontController.php(279): Magento\Framework\Event\Manager\Proxy->dispatch()
#7 /data/web/public/vendor/magento/framework/App/FrontController.php(211): Magento\Framework\App\FrontController->dispatchPreDispatchEvents()
#8 /data/web/public/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#9 /data/web/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#10 /data/web/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#11 /data/web/public/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /data/web/public/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#13 /data/web/public/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#14 /data/web/public/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#8730 /public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#16 /data/web/public/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#17 /data/web/public/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#18 /data/web/public/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#19 /data/web/public/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
```

### Additional information

Related issue: https://github.com/magento/magento2/issues/34975

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by p24-max** [comment]
Facing same issue with Magento 2.4.4-p6, is there any fix for it?

**Comment by engcom-Bravo** [comment]
Hi @timpea-splat,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by rejith7** [comment]
Hi, i've faced the same issue on  2.4.5-p4 EE and my recaptcha on frontend customer account create page fails mostly

**Comment by rejith7** [comment]
@p24-max we're you able to resolve this issue ?

**Comment by p24-max** [comment]
@rejith7 I disabled the recaptcha as its not working properly :/

**Comment by minhluan259** [comment]
@engcom-Bravo the exception.log appear when a bot attack (tool) create a post request without recaptcha param.

Here the debug info:
```
[2024-01-30T05:39:37.024093+00:00] main.INFO: createpost [] []
[2024-01-30T05:39:37.027508+00:00] main.INFO: customer [] []
[2024-01-30T05:39:37.027721+00:00] main.INFO: success_url=&error_url=&firstname=https://jmybd.blogspot.sg/ - 517610 RUB GAZPROM&lastname=https://jmybd.blogspot.sg/ - 517610 RUB GAZPROM&email=1661919960751685@facebook.com&password=d263sqeR4ha5BXr&confirmation=d263sqeR4ha5BXr&form_key=baEtSv32jdr55xaZ [] []
[2024-01-30T05:39:37.027863+00:00] main.INFO: Array
(
    [success_url] => 
    [error_url] => 
    [firstname] => https://jmybd.blogspot.sg/ - 517610 RUB GAZPROM
    [lastname] => https://jmybd.blogspot.sg/ - 517610 RUB GAZPROM
    [email] => 1661919960751685@facebook.com
    [password] => d263sqeR4ha5BXr
    [confirmation] => d263sqeR4ha5BXr
    [form_key] => baEtSv32jdr55xaZ
)
 [] []

```

**Comment by kennylawrence** [comment]
Apparently I have been getting this for some time, I just missed it in a sea of unrelated exceptions.
I am using 2.4.6-p1.  @davirs I'm also using varnish+redis

**Comment by jorgb90** [comment]
Same issue here with recaptcha enabled!

**Comment by chrisoliver90** [comment]
We have the same issue on 2.4.7-p1
It seems very intermittent in the logs and I am unable to replicate. Is this believed to be to do with customer account creation?
Seems somewhat related to [34975](https://github.com/magento/magento2/issues/34975) from a couple years ago.
Possibly to do with bots trying to create customer accounts?

**Comment by indrisepos** [comment]
I have the same problem. We are using 2.4.7-p2

**Comment by arvind-curotec** [comment]
same issue

**Comment by bolasevich** [comment]
same issue

**Comment by davirs** [comment]
> Hi @timpea-splat,
> 
> We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Thanks.

@engcom-Bravo 
Why the hell was this issue closed? We are all waiting for the solution.
Could you please point out what the solution was?

**Comment by Quazz** [comment]
If it is just bots, it should at least redirect the output to a different log file IMO.

Flooding the exception.log with this stuff hides the real errors that might require attention.

**Comment by agendartobias** [comment]
I have the same problem. We are using 2.4.7-p3

**Comment by PCodrin** [comment]
2.4.8 Same problem, any solution?

**Comment by DmitryFurs** [comment]
2.4.8-p3 same problem

**Comment by radnicm** [comment]
> Adobe has informed my team that this bug is a low priority, they don't know when the fix will be released. My team has created a custom composer patch using their commit here [magento/security-package@804dbc2](https://github.com/magento/security-package/commit/804dbc2ad49d6adc73d93795ca7ccfe5e6d5f775) as we can't wait for the eventual release.
> 
> I suggest others do the same.

I tested your patch. I didn't get a positive result. Now the reCaptcha is not visible on the login page but it doesn't allow login.
