### ISSUE TITLE
Magento 2 - Braintree Payment Method not working

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#3811]
I have enabled Braintree payment method from Stores > Configuration > Payment Methods. I cleared var/cache, var/page_cache and var/generation and tried to place a normal order with braintree, but checkout page appears blank after braintree is enabled. In my console i get following error:

```
TypeError: value is undefined
return value.length <= +params;
/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/validation/rules.js
```

So, I cleared  pub/static, var/view_preprocessed and ran the command php bin/magento setup:static-content:deploy then i ran the checkout Page URL again, but I am getting same error. I am facing this error on Ubuntu. I also checked on another Linux Mint system, in that I followed same process but Braintree is not appearing in Payment Methods list, even when it is correctly configured from backend. I am checking Braintree Sandbox Mode.

**Comment by benathey** [comment]
Looks like its a php version issue, issue already posted check #3797. Roll back to php 5.6 and re-test, that should help in the short term.

**Comment by parekhreena** [comment]
@benathey  - ok thank you

**Comment by alena-marchenko** [comment]
Hi Reena,

This issue is already resolved and https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6 fix is delivered to develop branch,

**Comment by Weltpixel** [comment]
Hi,

Until now this are the measures that we took and seams to significantly improve the transaction decline rate. After applying all 3 solutions, we didn't receive any reports of other users not being able to checkout using Braintree on our Magento 2.1 store. 

Hope this helps:
https://support.weltpixel.com/hc/en-us/articles/115007753688-How-we-solved-Braintree-Magento-2-checkout-issues-with-our-Magento-2-1-store

Regards,
WeltPixel Team
