### ISSUE TITLE
Problem with migrating customers from magento 1 to 2.4.6-p3 with their hashed password

### ISSUE THREAD

**Issue by kickandrush-ecommerce** [magento/magento2#38127]
https://www.commercers.com/blog/en/migrate-magento-customer-accounts-from-magento-1-to-magento-2-and-get-a-password/

Hi, this used to work with magento 2.4.5 but with 2.4.6-p3 apparently not anymore. I tried it couple of times now.

How can I best migrate passwords from magento 1 to 2?

**Comment by engcom-Bravo** [comment]
Hi @mcs-jonasvanderhaegen,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
