### ISSUE TITLE
SEO takes in html for meta description thus screwing up head tag in html

### ISSUE THREAD

**Issue by sachinsancheti1** [magento/magento2#3813]
Steps followed:

I created a description for a configurable product which has some font colour in it.

What happened next was that the SEO section (under basic settings) continued to use the description with the html tags. This resulted in the actual page's head tag getting screwed with an "=" sign used in the style

To check again, I went in to edit the SEO section but it fails to take in the inputs I give it to correct the issue

Production configuration SEO section
![seo page](https://cloud.githubusercontent.com/assets/6279770/13817134/210a2b74-ebb7-11e5-8ee6-bea610360933.jpg)

Website view with a header tag problem due to incorrect SEO
![website header problem](https://cloud.githubusercontent.com/assets/6279770/13817135/2137ece4-ebb7-11e5-879b-8c0c1ed0994c.jpg)

Link you may check out 

http://40.121.61.188/carpet-bins.html

**Comment by antboiko** [comment]
Hi @sachinsancheti1 , thanks for your inquiry. We have internal ticket MAGETWO-48511 to fix this.

https://github.com/magento/magento2/issues/2613

Best,
Anton.

**Comment by vzabaznov** [comment]
@sachinsancheti1 bug was fixed and delivered to develop branch, thank you for contributing, please feel free to add new issues or write, if fix doesn't help.
