### ISSUE TITLE
Message queue consumer updates the message with completely the wrong status

### ISSUE THREAD

**Issue by glenelkinsdev** [magento/magento2#38130]
### Summary

I have a custom message queue, my consumer updates the status of the operation when complete or failed, but the status in the database is always incorrect!

I am setting the status to COMPLETE and saving with entity manager, which should be integer 1 in the database, but it always either saves as status 3 or 4 in the queue_message_status table - i also don't know what the result message is for when the status table doesn't have a message column?

### Examples

```
// set the status
                $operation->setStatus(OperationInterface::STATUS_TYPE_COMPLETE)
                    ->setErrorCode(null)
                    ->setResultMessage('Export generation complete');

$this->_entityManager->save($operation);
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @glenelkinsdev,

Thank you for the report and collaboration!

As you can see in the below screenshot, status code for `MESSAGE_STATUS_COMPLETE` is 4, hence it is saving the value as 4 in the databse.
<img width="469" alt="image" src="https://github.com/magento/magento2/assets/60198231/d4853aaf-c82c-4bb1-8d8c-4a61acfca9b7">
The value 1 that you have mentioned is of `Magento\Framework\Bulk\OperationInterface`, but `queue_message_status` table uses `Magento\MysqlMq\Model\QueueManagement`.
And could you also mention the type of the `$operation` variable where you are using `setStatus` method in example.
Please let us know if this helps, or if we are missing anything.

Thank you.

**Comment by glenelkinsdev** [comment]
Hi

 

Thanks! I actually worked this out before you replied, I still don’t see anywhere in the database where it stores the status message I set though, the message_status table doesn’t have a result message column so when I use ->setResultMessage('Export generation complete'); I don’t see where it’s saving that message?

 

 

 

From: Prasanna ***@***.***>
Reply to: magento/magento2 ***@***.***>
Date: Tuesday, 31 October 2023 at 11:26
To: magento/magento2 ***@***.***>
Cc: glenelkinsdev ***@***.***>, Mention ***@***.***>
Subject: Re: [magento/magento2] Message queue consumer updates the message with completely the wrong status (Issue #38130)

 

Hello @glenelkinsdev,

Thank you for the report and collaboration!

As you can see in the below screenshot, status code for MESSAGE_STATUS_COMPLETE is 4, hence it is saving the value as 4 in the databse.

The value 1 that you have mentioned is of Magento\Framework\Bulk\OperationInterface, but queue_message_status table uses Magento\MysqlMq\Model\QueueManagement.
And could you also mention the type of the $operation variable where you are using setStatus method in example.
Please let us know if this helps, or if we are missing anything.

Thank you.
