### ISSUE TITLE
Product page Review pagination not coming when layout is page full width

### ISSUE THREAD

**Issue by karangar** [magento/magento2#38138]
### Preconditions and environment

- Magento version = 2.4.6-p3

### Steps to reproduce

1. Add Review greater than 10 and approve it from the admin
2. Check review pagination is working fine when tab is displaying.
3. Go to Admin -> Catalog -> Edit product -> Go to Design tab -> Set  Layout = Page full width
4. Check front end review section pagination is not displaying and displayed all the review.

### Expected result

When set the layout is page full width must be display the review with pagination

### Actual result

Currently When we set the layout is page full width at that review with pagination not displaying and displayed all the review.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by karangar** [comment]
I have checked on the shared Magento instance, And not displaying the pagination after layout set full width. 
**Before chage**
![image](https://github.com/magento/magento2/assets/34768419/af33d420-344f-4c80-9919-a288d292cabf)
**Change layout**
![image](https://github.com/magento/magento2/assets/34768419/3bf8b3e0-02fe-4093-bebc-ec1dd65f4db7)
**After change**
![image](https://github.com/magento/magento2/assets/34768419/ffddba73-ade0-4720-a4ad-39b6ef245f40)

**Comment by karangar** [comment]
Issue: Confirmed

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @karangar 
Thanks for reporting and collaboration.
Verified the issue on magento 2.4 instance. We are able to see pagination on product page reviews when the layout is page-fullwidth and also for product-fullwidth. Please refer the screenshots attached.
Page-Fullwidth:
<img width="1440" alt="page-fullwith" src="https://github.com/magento/magento2/assets/60198592/35481827-d086-4d45-87dc-5fc561be9e81">
Product-fullwidth

<img width="1440" alt="Product-fullwidth" src="https://github.com/magento/magento2/assets/60198592/79b6d6b0-29f8-4ea2-af67-919baff46b3f">
