### ISSUE TITLE
Magento order page freezes while loading after submitting orders with a saved credit card

### ISSUE THREAD

**Issue by Bnlawson188** [magento/magento2#38170]
### Preconditions and environment

2.3.6-p1 - Magento version

The main issue is the order page freezes while loading after the order is submitted. This happens to multiple members of our staff however the thing that triggers it seems to change person to person. For one of our employees this happens any time he uses saved credit card information in the order. Another employee only has this happen when submitting orders under specific customers. Another key trait that seems to occur no matter who is having the issue is that once the page is stuck (frozen) loading it can be re-freashed in the browser and the order will then submit with no issues. However, when the page re-fresh is done it will always jump to the credit card info section of the order submission page.  - Anything else that would help a developer reproduce the bug

### Steps to reproduce

Navigate to Sales>Orders>Create New Order> (Specific Contact triggers this for one of our employees, others it does not matter which contact is selected) Select Contact> Select Website>Fill out order form with product> Assign specific sales rep (joey)> Select Saved Credit Card Info>Select Shipping Method>Submit> Issue (Stuck Loading)

### Expected result

The order page will eternally load until the page is re-freshed or closed. 

### Actual result

No error message is ever displayed. Eternal loading is the only sign of malfunction. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bnlawson188** [comment]
Deploy vanilla Magento instance

**Comment by engcom-Bravo** [comment]
Hi @Bnlawson188,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

We are able to place the order Saved Credit Card Could you please confirm you are using any third party module.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @Bnlawson188,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38170#issuecomment-1805511831 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by Bnlawson188** [comment]
Hi Venkata,

Yes, we are still experiencing this issue. There are a few modules
installed on our website such as the Affirm Module for accepting payments,
an Ahead Works Advanced Reporting Module along with a few others. The Ahead
works module that is for our reports is long past due for an update but the
Affirm module was just recently updated though. If you would like I can
provide you with access to my specific Magento login which should allow you
to reproduce the issue. Just let me know what else I can provide you to
help. I don't think any more explanation of how we get it to occur will get
it to occur for you. I'm pretty sure it's specific to our website.

Cheers,

Ben Lawson

**Comment by engcom-Bravo** [comment]
Hi @Bnlawson188,

Thanks for your update.

“Affirm Module” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
