### ISSUE TITLE
Comma not rendering in value (textarea) using "\,"

### ISSUE THREAD

**Issue by saad-ather** [magento/magento2#38171]
### Preconditions and environment

- Magento version 1.9.0
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Try adding a value (textarea) and add comma using \, 
It will render a slash with new line.
![Screenshot 2023-11-09 at 5 13 02 PM](https://github.com/magento/magento2/assets/150070403/9e595e59-2b43-4ca4-b325-5d73bc5a176d)

### Expected result

Should render a comma

### Actual result

It will render a slash with new line.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by ananth-iyer** [comment]
@saad-ather Try to add text inside <![CDATA[MY-TEXT]]>

**Comment by engcom-Bravo** [comment]
@ananth-iyer Thanks for your contribution & collaboration over here.

Hi @saad-ather,

Thank you for reporting and collaboration.

Could you please elaborate the steps to reproduce on which scenario you are facing the issue and also please refer this comment https://github.com/magento/magento2/issues/38171#issuecomment-1805177268 and please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @saad-ather,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38171#issuecomment-1805511997 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.
