### ISSUE TITLE
Download M2 version contains update app git repo

### ISSUE THREAD

**Issue by ivanweiler** [magento/magento2#3818]
## Steps to reproduce
1. Download Magento-CE-2.0.2-2016-01-28-02-24-15.tar.gz from Magento site
2. Unpack
3. Navigate to /update/ folder
## Expected result
1. /update/.git/\* most likely shouldn't be there
## Actual result
1. /update/.git/\* is there :)
## Comment

I wasn't sure where to post this, since it's "version release problem". Anyway, why is repo of update app part of download, mistake?

Thanks,
Ivan

**Comment by mazhalai** [comment]
@ivanweiler this has been removed in 2.0.3, hence closing this issue.
