### ISSUE TITLE
Magento 2 oauth developments document step by step

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38192]
### Summary

Hello Magento Team,

We are from Webgility Inc., and We are currently in the process of implementing Magento API OAuth integration and are seeking official documentation to guide us through the process.

If possible, could you please share the relevant documentation or provide guidance on where we can access it? Additionally, if there are any specific considerations or best practices that your team recommends during the implementation process, we would greatly appreciate that information.

Thank you in advance for your prompt attention to this matter.

### Examples

if you have some request type data so can you please share with us.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance
