### ISSUE TITLE
Magento 2 additional image import issue with different url and same name.

### ISSUE THREAD

**Issue by Krishna-19-94** [magento/magento2#38203]
### Summary

Greetings!

I attempted to programmatically import additional images from third-party URLs.Working with root script. However, the URLs are different, and the names are the same. Does anyone have an idea of how we can upload all the images as additional images?

Thanks in advance.

### Examples

https:/example.com/100/abc.jpg
https:/example.com/200/abc.jpg
https:/example.com/300/abc.jpg
https:/example.com/100/xyz.jpg
https:/example.com/200/xyz.jpg

### Proposed solution

Need to upload all the additional image with same name and different urls.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @Krishna-19-94,

Thank you for the report!

As this platform is only to report issues and bugs related to core-magento, you can post these kind of queries on [Magento Stack Exchange](https://magento.stackexchange.com/).
Hence closing this issue, feel free to raise a fresh issue or reopen this if you need more assistance.

Thank you.
