### ISSUE TITLE
Listing Component sorting / filtering does not work with dynamic columns

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38204]
### Summary

Create a new CRUD Entity with two columns 

1. invoice_grand_total
2. credit_grand_total 

On your UI component add a dynamic column 

```
        <column name="calculated_total">
            <settings>
                <label translate="true">Calculated Total</label>
                <sortable>true</sortable>
            </settings>
        </column>

 ```

On your UI DataProvider in the overriden getData function

```
        foreach ($this->loadedData['items'] as &$item) {
            $item['calculated_total'] = (float)$item['grand_total'] - (float)$item['credit_grand_total'];
        }
```

This works fine and will present the column properly, however it's not able to sort or filter it as it's not part of the database. 

While collections allow for altering the select and adding aggregated or calculated columns to them and filtering, on the UI DataProvider class we have no possible way to access the underlying collection via the SearchCriteria or the SearchResults. 

This leads to an inability to use calculated or aggregated columns that will work with filtering or sorting. 

This is a serious limitation caused by the SearchCriteria / SearchResults pattern and implementation that needs to be addressed

        

### Examples

I've included the example in the summary

### Proposed solution

Give access to the underlying collection so that we can alter the query before sorting / filtering on the UI DataProvider class via the SearchCriteria or SearchResults. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment]
@ioweb-gr You are doing wrong using UI DataProvider class.
You have to use Grid Collection (new class) and add aggregation calculation to the main collection class. Then call it from Grid Collection.

Check this files for reference:
* Use **_initSelect** in your Grid Collection class:
https://github.com/magento/magento2/blob/edd599b7fb910ee0bea8f024c03cc8bf6cf0d16a/app/code/Magento/Store/Model/ResourceModel/Website/Grid/Collection.php#L18C1-L23

* Check: **joinGroupAndStore** method: adds aggregration to SQL. It is not 100% same but somewhat near to proper solution.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/ResourceModel/Website/Collection.php#L134

Regards.

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Have you got chance to check this comment https://github.com/magento/magento2/issues/38204#issuecomment-1818517051?

Let us know if you are still facing the issue.

Thanks

**Comment by ioweb-gr** [comment]
Hi I was trying to find any documentation on this to check it out thoroughly but this use case is not documented anywhere. I'm considering cases that include both sorting and filtering on dynamic columns so it's a bit harder to implement and test

**Comment by ananth-iyer** [comment]
@ioweb-gr I got your concerns and you can Google: "magento 2 add column to order grid"
You can refer to this module: https://github.com/markshust/magento2-module-ordergrid

**Comment by engcom-Hotel** [comment]
Dear @ioweb-gr,

We have noticed that this issue has not been updated for a period of a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
