### ISSUE TITLE
Magento 2 preview button throws error with query string on elasticsuit optimizer

### ISSUE THREAD

**Issue by Krishna-19-94** [magento/magento2#38206]
### Summary

I used elasticsuits and added new optimizer, when tried to preview with query string it is throwing error like

`Exception #0 (BadMethodCallException): Missing required argument $isUsingAllTokens of Smile\ElasticsuiteCore\Search\Spellchecker\Request.`

It is throwing an error related to missing required arguments. After debugging the flow, I manually added one parameter for testing purposes.

Subsequently, it threw an error for the new variable as a missing argument. Errors are also being raised for 'isUsingAllTokens', 'isUsingReference', 'isUsingEdgeNgram', etc.

When I included all the parameters, the application encountered a 500 error without displaying any error message.

Thanks in advance.

### Examples

On catalog product search option, throws error when click on preview.
![Screenshot from 2023-11-20 16-45-46](https://github.com/magento/magento2/assets/123471528/069005be-0d43-49ca-83e8-408d7a2cbf1c)

### Proposed solution

It will show preview of given query string without any error.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @Krishna-19-94,

Thank you for the report and collaboration!

In our case the Elasticsuite optimizer was working fine, and we were able to get the search results on preview.
Please take a look at the screenshot:
<img width="1419" alt="image" src="https://github.com/magento/magento2/assets/60198231/b6a01015-eac9-4464-b41c-f6cf5ec4f0b0">
As this issue is not Magento-core related, please raise this issue on respective platform.

Thank you.

**Comment by engcom-November** [comment]
Hello @Krishna-19-94,

We have noticed that this issue has not been updated for a long time. We believe your query has been resolved.
Hence closing this issue.

Thank you.
