### ISSUE TITLE
Exception is not getting handled properly while adding a product to cart in the compare product page

### ISSUE THREAD

**Issue by JasonTychons** [magento/magento2#38200]
### Preconditions and environment

- Magento version 2.4.6-p3
- PHP 8.1.18
- MySql  8.0.35-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce

- Login into the Magento using customer credentials
- Add a product to the compare list
- Got to my account page
- Click on compare
- Add the product to cart [In my case there was a Localized Exception thrown while adding it to the cart, there is a catch block in vendor/magento/module-checkout/Controller/Cart/Add.php line 164, but the exception is not caught and handled properly, instead JSON encoded page is returned]

### Expected result

The exception should be handled and a message manager message should be displayed in the controller.
![image](https://github.com/magento/magento2/assets/89189460/81ab0803-9d04-4ce8-ae55-09d79a2de80c)

### Actual result

![image](https://github.com/magento/magento2/assets/89189460/39e73e4e-46c3-4521-8f06-bc0822d41070)
The above-mentioned page is loaded with a JSON response

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JasonTychons** [comment]
@magento give me 2.4-develop instance

**Comment by JasonTychons** [comment]
@magento give me 2.4-develop instance

**Comment by JasonTychons** [comment]
https://github.com/magento/magento2/assets/89189460/a2c29396-e041-4b42-80c6-506eac16af63

I have attached a screen recorded video of replicating the bug in Magento version 2.4.6-p3

**_Issue is replicable in Magento 2.4.6-p3_**

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by JasonTychons** [comment]
Hi @engcom-Bravo ,
Were you able to replicate the issue?

**Comment by engcom-November** [comment]
Hello @JasonTychons,

Thank you for the report and collaboration!

We were able to verify this issue on 2.4-develop.
When manually throwing the LocalizedException in `addProduct` method of the class `Magento\Checkout\Model\Cart`, we got the below json response:
<img width="1503" alt="image" src="https://github.com/magento/magento2/assets/60198231/4e869fc3-7b99-4b9c-9073-7d545d6a6f68">
Hence confirming the issue.

Thank you.

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it


Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-10660 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-10660&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
