### ISSUE TITLE
Exception: Warning: Trying to access array offset in... -> Calendar.php since upgrade to ICU 74.1 (PHP Intl)

### ISSUE THREAD

**Issue by Munktells** [magento/magento2#38214]
### Preconditions and environment

Magento version 2.4.6-P3.
PHP v8.1.25.
ICU 74.1 (required by PHP Intl)
FreeBSD 13.2-RELEASE-p5

### Steps to reproduce

Install the above versions and visit either the backend or the frontend.

### Expected result

No errors in var/log/exception.log

### Actual result

Errors on each store visit in exception.log:

```
main.CRITICAL: Exception: Warning: Trying to access array offset on value of type null in /vendor/magento/framework/View/Element/Html/Calendar.php on line 114 in /vendor/magento/framework/App/ErrorHandler.php:62
```

### Additional information

Magento is using 'Swedish' as locale, and doesn't use am or pm (24 hrs). Set on Scope -> Default Config
Stores -> Configurations -> General -> Locale Options -> Locale
Magento is set up with 8 web sites, stores and views.

Line 114 in Calendar.php:

![2023-11-22 171407](https://github.com/magento/magento2/assets/57530884/18fb5467-e4b8-482b-964b-55042f34e540)
`$this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['0']));`

### Triage and priority

- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by Keivanph** [comment]
Hi,
Any updates on this error?
I am recently getting this error on
M2.4.5-p4 and php 8.1

**Comment by hostep** [comment]
Simplest way to reproduce (just tried this on latest commit from `2.4-develop` branch):
1. Setup clean Magento
2. Configure nl_NL locale: `bin/magento config:set general/locale/code nl_NL`
3. In backoffice, go to Stores > Attributes > Product
4. Find and edit the special_from_date attribute
5. Under Storefront Properties, enable both 'Use in Search' and 'Visible in Advanced Search' and save the attribute
6. Reindex & flush caches
7. In frontend click on the Advanced Search link in the footer
8. You'll see this error:
```
1 exception(s):
Exception #0 (Exception): Warning: Trying to access array offset on value of type null in lib/internal/Magento/Framework/View/Element/Html/Calendar.php on line 114

Exception #0 (Exception): Warning: Trying to access array offset on value of type null in lib/internal/Magento/Framework/View/Element/Html/Calendar.php on line 114
<pre>#1 Magento\Framework\View\Element\Html\Calendar->_toHtml() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:1117]
#2 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:1121]
#3 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:670]
#4 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [lib/internal/Magento/Framework/View/Layout.php:578]
#5 Magento\Framework\View\Layout->_renderBlock() called at [lib/internal/Magento/Framework/View/Layout.php:555]
#6 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#7 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:510]
#8 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#9 Magento\Framework\View\Layout\Interceptor->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:606]
#10 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:557]
...
```

**Comment by hostep** [comment]
After some more looking into and seeing how the ICU data changed between versions 73.2 and 74.1 (this is [the commit](https://github.com/unicode-org/icu/commit/2270c174a58)), it looks like we should use `AmPmMarkersAbbr` instead of `AmPmMarkers`.

Also, using the index as a string (`['0']`) never ever worked, it should have been used as a int (`[0]`)

So I would suggest this change now:
```diff
diff --git a/lib/internal/Magento/Framework/View/Element/Html/Calendar.php b/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
index 884488d77a7..28a59b28616 100644
--- a/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
+++ b/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
@@ -111,8 +111,8 @@ class Calendar extends \Magento\Framework\View\Element\Template
         $this->assignFieldsValues($localeData);

         // get "am" & "pm" words
-        $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['0']));
-        $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['1']));
+        $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkersAbbr'][0]));
+        $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkersAbbr'][1]));

         // get first day of week and weekend days
         $this->assign(
```

However, this code in core Magento has existed for over 9 years (was introduced [here](https://github.com/magento/magento2/commit/c292789a28644ec7d7665f4fbc60ffeb6aae1bda#diff-2c0328e6348648a2983c00a81b7181eb5064ef7e177e7a73fd3ec9c6441532a2R93)), and never worked, also the datetime picker widget only shows dates and not times, so I'm not sure if we even need that `am`/`pm` notation at all. So maybe we should just remove those two lines and be done with it?

**Comment by hostep** [comment]
I just wrote this (dirty) script to be put in `pub/test.php` and then openend via `https://base-url/test.php`, it goes over all locale's supported by Magento and outputs a table to see which locale supports which amPmMarker key:
```php
<?php

require_once('../vendor/autoload.php');

use Magento\Framework\Locale\Bundle\DataBundle as LocaleDataBundle;
use Magento\Framework\Locale\Config as LocaleConfig;

$locales = (new LocaleConfig())->getAllowedLocales();

$amPmMarkersKeys = ['AmPmMarkers', 'AmPmMarkersAbbr', 'AmPmMarkersNarrow'];

echo sprintf('<h1 style="text-align: center">ICU version: %s</h1>', getIcuVersion());

echo '<table width="100%"><thead><tr><th></th>';
foreach ($amPmMarkersKeys as $key) { echo sprintf('<th>%s</th>', $key); }
echo "</tr></thead><tbody>\n";

$countPerKey = [];

foreach ($locales as $locale) {
    echo sprintf('<tr><th>%s</th>', $locale);

    $localeData = (new LocaleDataBundle())->get($locale);

    foreach ($amPmMarkersKeys as $key) {
        $exists = $localeData['calendar']['gregorian'][$key] ? true : false;
        $values = [];
        if ($exists) {
            $count = $localeData['calendar']['gregorian'][$key]->count();
            for ($i = 0; $i < $count; ++$i) {
                $values[] = $localeData['calendar']['gregorian'][$key][$i];
            }
        }

        $output = $exists ? implode(', ', $values) : 'doesn\'t exists';
        $color = $exists ? '#c3e6cb' : '#f5c6cb';

        echo sprintf('<td bgcolor="%s">%s</td>', $color, $output);

        if ($exists) {
            if (!array_key_exists($key, $countPerKey)) {
                $countPerKey[$key] = 0;
            }
            ++$countPerKey[$key];
        }
    }

    echo "</tr>\n";
}

echo '<tr><th>Total</th>';

foreach ($amPmMarkersKeys as $key) {
    echo sprintf('<td><b>%d</b></td>', $countPerKey[$key]);
}

echo '</tr></tbody></table>';

// borrowed from https://github.com/symfony/intl/blob/5fbee19d24354bbd77b300971eb38469ddbfd7fc/Intl.php#L71-L94
function getIcuVersion(): string
{
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);

    return $matches[1];
}
```


Results with ICU 74.1:
![magento2-github baldwin_test php (1)](https://github.com/magento/magento2/assets/85479/cbfdd1da-7d5d-4d78-9239-6185c9d42738)

If somebody wants to test with older versions of ICU, feel free to do so and post the results!

Based on this, it looks like no key is supported by each locale, the key that has the most support is `AmPmMarkersAbbr` (at least with ICU 74.1), so if we keep these 2 lines of code, I vote we use that one. But add a fallback to `null` in case it doesn't exist.

So then I would propose we make this change to the core code:
```diff
diff --git a/lib/internal/Magento/Framework/View/Element/Html/Calendar.php b/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
index 884488d77a7..28a59b28616 100644
--- a/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
+++ b/lib/internal/Magento/Framework/View/Element/Html/Calendar.php
@@ -111,8 +111,8 @@ class Calendar extends \Magento\Framework\View\Element\Template
         $this->assignFieldsValues($localeData);

         // get "am" & "pm" words
-        $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['0']));
-        $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['1']));
+        $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkersAbbr'][0] ?? null));
+        $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkersAbbr'][1] ?? null));

         // get first day of week and weekend days
         $this->assign(
```

**Comment by andrewbess** [comment]
Hello @Munktells 
Thank you for your collaboration

Hello @hostep 
Thank you to your contribution here
I\ll review your PR

**Comment by engcom-Hotel** [comment]
Hello @Munktells,

Thanks for the report and collaboration!

Thanks @hostep for the updated steps to reproduce.

We have tried to reproduce the issue in the 2.4-develop branch but it seems the issue is not reproducible for us. Please refer to the below screenshots and let us know if we missed anything:

- ICU Version:
![image](https://github.com/magento/magento2/assets/51681618/ecf3e58d-a96d-49df-a2ab-21abfad1b66d)

- PHP Version: 8.1.2
- Locale: nl_NL
![image](https://github.com/magento/magento2/assets/51681618/985e3d9d-0200-4667-9152-018af0d1616c)

Marking this issue as `Needs Update` for now.

Thanks

**Comment by hostep** [comment]
@engcom-Hotel: it definitely is reproducible.

Are you 100% sure you are using ICU version 74.x ?
Can you try my dirty test script from this comment: https://github.com/magento/magento2/issues/38214#issuecomment-1898634163

It will output the ICU version used at the top.

**Comment by guvra** [comment]
FYI this also happens on Alpine 3.19 with the following versions of ICU:

```
icu-data-full-74.1-r0 x86_64 {icu} (ICU) [installed]
icu-libs-74.1-r0 x86_64 {icu} (ICU) [installed]
```

**Comment by kayintveen** [comment]
Same issue here on php 8.1 and magento 2.4.6-p3

**Comment by hostep** [comment]
@engcom-Hotel: can you please retry to reproduce? More and more people are running into the problem ...
It would be appreciated if https://github.com/magento/magento2/pull/38364 would get some more attention and gets included in Magento 2.4.7 if possible...

**Comment by engcom-Hotel** [comment]
Hello @Munktells @hostep,

We have tried to reproduce the issue with the mentioned prerequisites and the issue is reproducible for us with the below-mentioned steps:

### Manual testing scenarios (*)
1. Setup clean Magento
1. In the admin panel, go to Stores > Attributes > Product
1. Find and edit the special_from_date attribute
1. Under Storefront Properties, enable both 'Use in Search' and 'Visible in Advanced Search' and save the attribute
1. Reindex
2. Edit the file `app/code/Magento/Theme/view/frontend/templates/js/calendar.phtml` and add this line at the very bottom: `<ul><li>am: <?= $am; ?></li><li>pm: <?= $pm; ?></li></ul>`
1. Configure "lv_LV" locale: `bin/magento config:set general/locale/code lv_LV`
2. Flush the caches
1. In frontend click on the Advanced Search link in the footer
2. Expected to see "priekšpusdienā" & "pēcpusdienā" (but then escaped for JS)
2. Expected to see "null" & "null"

Please refer to the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/a2ff3abe-6469-470e-aac0-3444a28f857b)

Hence confirming the PR.

Thanks

**Comment by engcom-Hotel** [comment]
Yes @hostep,

I compiled the PHP with ICU version 74.1, and after compilation, running the below command was showing ICU version as 74.1:

`php -i | grep 'ICU version``

**Comment by webcreative24** [comment]
how to fix it?

**Comment by hostep** [comment]
@webcreative24: apply changes from https://github.com/magento/magento2/pull/38364, that works for us.

**Comment by PieterCappelle** [comment]
Same issue here... :)

```
Exception #0 (Exception): Warning: Trying to access array offset on value of type null in /vendor/magento/framework/View/Element/Html/Calendar.php on line 114
```

```
php -i | grep 'ICU version'
ICU version => 74.2
```

Create file patches/composer/github-issue-38364.diff
```
diff --git a/View/Element/Html/Calendar.php b/View/Element/Html/Calendar.php
index 884488d77a74f..cf8f2e3e789e6 100644
--- a/View/Element/Html/Calendar.php
+++ b/View/Element/Html/Calendar.php
@@ -109,10 +109,7 @@ protected function _toHtml()
         );

         $this->assignFieldsValues($localeData);
-
-        // get "am" & "pm" words
-        $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['0']));
-        $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers']['1']));
+        $this->assignAmPmWords($localeData);

         // get first day of week and weekend days
         $this->assign(
@@ -209,4 +206,23 @@ private function assignFieldsValues(\ResourceBundle $localeData): void
             $this->assign('week', $this->encoder->encode($localeData['fields']['week']['dn']));
         }
     }
+
+    /**
+     * Assign "am" & "pm" words from the ICU data
+     *
+     * @param \ResourceBundle $localeData
+     */
+    private function assignAmPmWords(\ResourceBundle $localeData): void
+    {
+        // AmPmMarkers and AmPmMarkersAbbr aren't guaranteed to exist, so fallback to null if neither exist
+        $amWord = $localeData['calendar']['gregorian']['AmPmMarkers'][0] ??
+                  $localeData['calendar']['gregorian']['AmPmMarkersAbbr'][0] ??
+                  null;
+        $pmWord = $localeData['calendar']['gregorian']['AmPmMarkers'][1] ??
+                  $localeData['calendar']['gregorian']['AmPmMarkersAbbr'][1] ??
+                  null;
+
+        $this->assign('am', $this->encoder->encode($amWord));
+        $this->assign('pm', $this->encoder->encode($pmWord));
+    }
 }
diff --git a/View/Test/Unit/Element/Html/CalendarTest.php b/View/Test/Unit/Element/Html/CalendarTest.php
index 94d3dbb660f6b..51e5834fe8507 100644
--- a/View/Test/Unit/Element/Html/CalendarTest.php
+++ b/View/Test/Unit/Element/Html/CalendarTest.php
@@ -48,6 +48,9 @@ public function localesDataProvider()
             ['en_US'],
             ['ja_JP'],
             ['ko_KR'],
+            ['lv_LV'],
+            ['sv_SE'],
+            ['de_AT'],
         ];
     }

```

Add to composer.json
```
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/framework": {
                "ICU library where AmPmMarkers": "patches/composer/github-issue-38364.diff"
            }
        }
    }
```

Many thanks to @hostep! 💯

**Comment by tuyennn** [comment]
+ 1 issue on ICU version => 74.2 & Magento 2.4.3-p3

**Comment by elburro1887** [comment]
Same issue here
Magento 2.4.0
PHP 7.4.33
ICU 74.2

**Comment by gbobts** [comment]
Fix is available on the 2.4-develop branch but ommited on the 2.4.7 branches https://github.com/magento/magento2/commit/144b491c7720a983c33c7c20b1f77ccd559c1031

Could it be possible that the fix was forgotten by the dev team ?

**Comment by hostep** [comment]
The fix was unfortunately only merged ([16 May 2024](https://github.com/magento/magento2/pull/38364#event-12839092050)) after Magento 2.4.7 was released ([9 April 2024](https://github.com/magento/magento2/releases/tag/2.4.7)), so it will be included in 2.4.8 which is to be released on [8 April 2025](https://experienceleague.adobe.com/en/docs/commerce-operations/release/planning/schedule).

**Comment by erwinromkes** [comment]
or... a public Gist 
```
"patches": {
  "magento/framework": {
      "ICU library where AmPmMarkers": "https://gist.githubusercontent.com/erwinromkes/80d4db93764bd30b232b75b3f8b780de/raw/26ef659113735ab79c1440c6e63033496fc16039/github-issue-38364.diff"
  }
}
```

**Comment by cptX** [comment]
Same problem with magento 2.4.7-p3, php 8.3 and ICU 74.2 .
Why don't they provide these fixes in -px versions?

**Comment by Nurgiel** [comment]
Same issue on Ubuntu 24.04.1 LTS.
I want to downgrade PHP to 8.2.26 to PHP 8.2.19 (php version used on adobe cloud) instead of fixing it with a patch, but:
`add-apt-repository -y ppa:ondrej/php`
`apt-cache madison php8.2` only has php 8.2.26 available

Any hints on downgrading PHP? Do I need to find php8.2.19 .deb file and install it from .deb file after apt purge or is there a better way?

**Comment by ctadlock** [comment]
Its really quite amazing that a fix that is a couple of simngle quotes takes 17 months to be released.

**Comment by hostep** [comment]
The fix for this issue got added as a patch to Magento's Quality Patches repo [in version 1.1.57](https://github.com/magento/quality-patches/commit/a31a987c3385d7d7a050a17fe1ae1e93c70c29bb) yesterday with the name `ACSD-63326` in case anybody cares :)

**Comment by mzeis** [comment]
@hostep Thanks a lot for pointing this out!

Interestingly, the Adobe team [documented](https://experienceleague.adobe.com/de/docs/commerce-operations/tools/quality-patches-tool/patches-available-in-qpt/v1-1-57/acsd-63326-fix-admin-redirection-issue-after-placing-an-order-from-the-backend) another context that creates this error ("ACSD-63326: Fix admin redirection issue after placing an order from the backend"), but as long as we can use an official patch to fix this problem, we shouldn't complain, right?

**Comment by rickbakker** [comment]
Even If I apply this ACSD-63326 patch, unfortunately, i'm still getting the error message Warning: Trying to access array offset on value of type null in vendor/magento/framework/View/Element/Html/Calendar.php on line 114. Is there any other official fix for this? Don't really want to edit core files as a 'solution'.
