### ISSUE TITLE
Magento 2 Rest API for post categories giving internal error.

### ISSUE THREAD

**Issue by shafeekbz** [magento/magento2#38216]
### Preconditions and environment

- Magento ver. 2.4.6-p2

### Steps to reproduce

As per Magento 2 Rest API collect data using method `get categories` and same data to set as body data for category and do method `post categories` will get result as `Internal Error. Details are available in Magento log file. Report ID: webapi-65604be250fa2`.
Body data is
```
{
	"category": {
		"id": 2,
		"parent_id": 1,
		"name": "Default Category",
		"is_active": true,
		"position": 1,
		"level": 1,
		"product_count": 5,
		"children_data": [
			{
				"id": 3,
				"parent_id": 2,
				"name": "Casuals",
				"is_active": true,
				"position": 1,
				"level": 2,
				"product_count": 2,
				"children_data": []
			},
			{
				"id": 4,
				"parent_id": 2,
				"name": "Footwears",
				"is_active": true,
				"position": 2,
				"level": 2,
				"product_count": 1,
				"children_data": []
			},
			{
				"id": 5,
				"parent_id": 2,
				"name": "Fruits and Vegetables",
				"is_active": true,
				"position": 3,
				"level": 2,
				"product_count": 2,
				"children_data": []
			}
		]
	}
}
```

### Expected result

need proper execution

### Actual result

{
	"message": "Internal Error. Details are available in Magento log file. Report ID: webapi-65604be250fa2"
}

### Additional information

Magento log is 
```
Next Exception: Report ID: webapi-65604be250fa2; Message: Property "ProductCount" does not have accessor method "getProductCount" in class "Magento\Catalog\Api\Data\CategoryInterface". in /bitnami/magento/vendor/magento/framework/Webapi/ErrorProcessor.php:208
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/Webapi/ErrorProcessor.php(153): Magento\Framework\Webapi\ErrorProcessor->_critical()
#1 /bitnami/magento/vendor/magento/module-webapi/Controller/Rest.php(208): Magento\Framework\Webapi\ErrorProcessor->maskException()
#2 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#3 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#4 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#5 /bitnami/magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#6 /bitnami/magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#7 /bitnami/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#8 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#9 /bitnami/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#10 {main} {"exception":"[object] (Exception(code: 0): Report ID: webapi-65604be250fa2; Message: Property \"ProductCount\" does not have accessor method \"getProductCount\" in class \"Magento\\Catalog\\Api\\Data\\CategoryInterface\". at /bitnami/magento/vendor/magento/framework/Webapi/ErrorProcessor.php:208)
[previous exception] [object] (LogicException(code: 0): Property \"ProductCount\" does not have accessor method \"getProductCount\" in class \"Magento\\Catalog\\Api\\Data\\CategoryInterface\". at /bitnami/magento/vendor/magento/framework/Reflection/NameFinder.php:103)"} []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @shafeekbz,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1215" alt="Screenshot 2023-11-28 at 12 17 34 PM" src="https://github.com/magento/magento2/assets/51680745/f1ccba51-9576-4668-969e-5b15a202ff9c">


<img width="1151" alt="Screenshot 2023-11-28 at 12 23 55 PM" src="https://github.com/magento/magento2/assets/51680745/7b6b6a1a-be23-4a22-a7c9-cd4ce6554d45">


We are able to get the Response successfully regarding both for the GET and POST request.

Could you please refer this document https://developer.adobe.com/commerce/webapi/rest/quick-reference/ for REST ENDPOINTS.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by shafeekbz** [comment]
Hi @engcom-Bravo,

Thanks for your updates. 

I didn't see `product_count` and `children_data` are not added in category body parameters in POST request. I assume that it is not allowed for POST request, am I right?

**Comment by engcom-Bravo** [comment]
Hi @shafeekbz,

Thanks for your update.

As per the document https://developer.adobe.com/commerce/webapi/rest/quick-reference/ product_count and children_data is not required in category body parameters in POST request.

<img width="1218" alt="Screenshot 2023-12-04 at 10 43 54 AM" src="https://github.com/magento/magento2/assets/51680745/2023b39c-0271-4ca6-bfee-694e934b376e">



Could you please refer the document and please let us know if you are still facing any issue.


Thanks.
