### ISSUE TITLE
Render the My Cart via Block/Link won't output anything

### ISSUE THREAD

**Issue by ddonnini** [magento/magento2#3821]
## Steps to reproduce

Render the output of a block of class Magento\Checkout\Block\Cart\Link
## Expected result

A link with "My Cart" and the number of items
## Actual result

Nothing output.
## Solution

Add "!" in the _toHtml of the file module-checkout/Block/Cart/Link.php

```
protected function _toHtml()
{
    if ($this->_moduleManager->isOutputEnabled('Magento_Checkout')) {
        return '';
    }
    return parent::_toHtml();
}
```

to 

```
protected function _toHtml()
{
    if (!$this->_moduleManager->isOutputEnabled('Magento_Checkout')) {
        return '';
    }
    return parent::_toHtml();
}
```

**Comment by ddonnini** [comment]
Am I missing something?
Otherwise, if you prefer, I can create a pull request.

Thanks in advance!

**Comment by ishakhsuvarov** [comment]
@ddonnini Thank you for reporting this issue. Looks like you are not missing anything, we would accept a PR if you wish to create one.

**Comment by piotrekkaminski** [comment]
related to internal issue MAGETWO-54244
