### ISSUE TITLE
Creating a new product through the REST API throws internal error

### ISSUE THREAD

**Issue by mamof** [magento/magento2#3822]
## Steps to reproduce

Using chrome RestClient extension.
**URL:** http://domain/magento2/rest/V1/products
**Method:** POST
**Headers:**

```
Content-Type: application/json; charset=utf-8
Accept: application/json
Authorization: Bearer fsqijfl2cdu3u9c8s7uxdrb07qqit3yb
```

**Payload:**

```
{
    "product": {
        "sku": "B201-SKU",
        "name": "B201",
        "price": 25.00,
        "status": 1,
        "type_id": "simple",
        "custom_attributes": [{
            "description": "Heavy Duty Brake Cables"
        }]
    }
}
```
## Expected result

Creates part B201.
## Actual result

{
"message": "Internal Error. Details are available in Magento log file. Report ID: webapi-56eab1fa2ee25"
}

> [2016-03-17 13:32:42] main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-56eab1fa2ee25; Message: Notice: Undefined index: value in /var/www/magento2/vendor/magento/framework/Webapi/ServiceInputProcessor.php on line 192' in /var/www/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php:194
> Stack trace:
> # 0 /var/www/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
> # 1 /var/www/magento2/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
> # 2 /var/www/magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> # 3 /var/www/magento2/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> # 4 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> # 5 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> # 6 {main} [] []

**Comment by mamof** [comment]
Any chance we could get an update on this? We're trying to finish out our integration and creating products is a big roadblock.

**Comment by eb84** [comment]
I am also running into this issue when attempting to POST a new product. Are there any updates on this issue?

**Comment by nimmneun** [comment]
In case you're still having trouble ... getting rid of any square brackets + specifying a attribute_set_id seems to work:

``` php
{
    "product": {
        "attribute_set_id": 4,
        "type_id": "simple",
        "sku": "B201-SKU",
        "name": "B201",
        "price": 25,
        "status": 1,
        "custom_attributes": {
            "description": "Heavy Duty Brake Cables",
            "meta_description": "Some describing text w00t"
        }
    }
}
```

**Comment by piotrekkaminski** [comment]
@mamof if you still have this issue and @nimmneun solution does not work for you, please open a new issue.
