### ISSUE TITLE
V1/customers/password endpoint question/issue

### ISSUE THREAD

**Issue by rit001** [magento/magento2#38238]
### Summary

Magento has an open endpoint on V1/customers/password to allow third-party integration (such as clientside js) to request a password reset for a known email address.

Such an API call being made public would seem to be problematic but as Magento via its management GUI allows limits to be placed on the number of requests per hour and the minimum time between each request there seems to be some basic controls in place.

What we are currently seeing is that the code path for the API is calling initiatePasswordReset, but this does not use/check the constraints set within the management GUI. 

PHP is not my first programming language so I may be missing something, but tests using the API allow password change requests to be processed outside of the rules defined.

I've flagged this as S1 as this could affect the functionality of a site that has the endpoint exposed. If someone was able to work out one or more valid emails defined within the system they could use the API to generate a constant stream of reset emails. The impact of knowing a single email address is likely to be a very unhappy customer. The impact of knowing many customer's emails could impact the operation of the service as it would not only cause issues with many customers but could cause the email provider to block the use of their service due to anti-spam rules.

### Examples

Sorry no code examples, but

- We have system wide values set of 
           5 Reset Requests per hour
          10 minutes minimum time between password reset requests

- Via our client App we can call the API often without the above rules kicking in. 

### Proposed solution

Linking the API to the values set within the management GUI would provide basic controls. Anything beyond this would be product refactoring and I can not really add much regarding that.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.
