### ISSUE TITLE
Running `bin/magento setup:di:compile` throws `Class "MagentoDiFactory" does not exist`

### ISSUE THREAD

**Issue by aashishgurung** [magento/magento2#38249]
### Preconditions and environment

- Magento version: 2.4.5

### Steps to reproduce

Execute `bin/magento setup:di:compile`

### Expected result

The command should run successfully.

### Actual result

<img width="673" alt="Screenshot 2566-12-07 at 12 09 24" src="https://github.com/magento/magento2/assets/101558497/94ac3c9e-64a5-4bac-af77-0fcd7067630c">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aashishgurung** [comment]
@engcom-Bravo It works on ` 2.4-develop` if I install and set up from terminal but fails when I use those same commands in  my docker compose with dockerfile setup. Weird but issue might be with my docker setup.

**Comment by engcom-Bravo** [comment]
Hi @aashishgurung,

Thanks for your update.

As per this https://github.com/magento/magento2/issues/38249#issuecomment-1851553879 the issue is not related to Magento core Hence we are closing this issue.

Please let us know if you are still facing any issue.

Thanks.
