### ISSUE TITLE
Javascript error when change options of bundle products at Firefox

### ISSUE THREAD

**Issue by serzhik** [magento/magento2#3826]
## Steps to reproduce
1. Use Firefox 44.0
2. Go to http://magento2.pulsarfour.com/sprite-yoga-companion-kit.html (clean Magento 2.0.2 install with sample data)
3. Change options
## Expected result
1. Summary chaged due to your option values
## Actual result
1. Error message appears: "TypeError: $(...).attr(...) is undefined" (pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/add-to-wishlist.js row: 94; column:31)
2. 
   ![image](https://cloud.githubusercontent.com/assets/2320879/13863519/161fcdbc-eca3-11e5-8dd3-a106332487ae.png)

**Comment by sevos1984** [comment]
Issue is in progress, internal ticket MAGETWO-50450

**Comment by slavvka** [comment]
@Serzhik, The fix has been delivered to mainline. Thank your for your contribution!
