### ISSUE TITLE
After disabling MSI all modules, adding bundle product to cart via REST API not working properly

### ISSUE THREAD

**Issue by lokborn** [magento/magento2#38267]
### Preconditions and environment

- Magento ver. 2.4.2-p2 (EE)  or (CE)
- install Magento ver. 2.4.2-p2 Enterprise edition or community edition, disable all MSI modules and try to add bundle product to cart using REST API

### Steps to reproduce

1. Create a bundle product in backend having 2 or more options and each option having single product and required.
2. Set the last product QTY of the option to more than 1.
3. Disable all MSI modules like using this command:
sudo php bin/magento module:disable Magento_Inventory Magento_InventoryAdminUi Magento_InventoryApi Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCatalog Magento_InventorySales Magento_InventoryCatalogAdminUi Magento_InventoryCatalogApi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProduct Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticsearch Magento_InventoryExportStockApi Magento_InventoryIndexer Magento_InventorySalesApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventorySourceSelectionApi Magento_InventoryCache Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryReservations Magento_InventoryReservationCli Magento_InventoryReservationsApi Magento_InventoryExportStock Magento_InventorySalesAdminUi Magento_CatalogInventoryGraphQl Magento_InventorySalesFrontendUi Magento_InventorySetupFixtureGenerator Magento_InventoryShipping Magento_InventoryShippingAdminUi Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventoryConfigurableProductAdminUi Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryBundleProductIndexer Magento_InventoryInStorePickupAdminUi Magento_InventoryInStorePickup Magento_InventoryInStorePickupQuote Magento_InventoryVisualMerchandiser Magento_InventoryInStorePickupSalesAdminUi Magento_InventoryGraphQl Magento_InventoryAdvancedCheckout Magento_InventoryCatalogFrontendUi Magento_InventoryDistanceBasedSourceSelection Magento_InventoryInStorePickupApi Magento_InventoryInStorePickupGraphQl Magento_InventoryInStorePickupSales Magento_InventoryInStorePickupShipping Magento_InventoryRequisitionList Magento_InventoryInStorePickupFrontend Magento_InventoryConfigurableProductFrontendUi Magento_InventoryBundleImportExport Magento_InventoryInStorePickupShippingApi Magento_InventoryInStorePickupQuoteGraphQl Magento_InventoryInStorePickupSalesApi Magento_InventoryInStorePickupShippingAdminUi Magento_InventorySwatchesFrontendUi Magento_InventoryWishlist Magento_InventoryInStorePickupMultishipping Magento_InventoryInStorePickupWebapiExtension

4. Example :
ENDPOINT :  /rest/V1/carts/mine/items
TYPE: POST
REQUEST:
`{
    "cartItem": {
        "qty": 1,
        "quoteId": "99264",
        "sku": "testbund2",
        "product_option": {
            "extension_attributes": {
                "bundle_options": [
                    {
                        "option_id": 9,
                        "option_qty": 1,
                        "option_selections": [
                            17
                        ]
                    },
                    {
                        "option_id": 10,
                        "option_qty": 1,
                        "option_selections": [
                            18
                        ]
                    },
                    {
                        "option_id": 11,
                        "option_qty": 2,
                        "option_selections": [
                            19
                        ]
                    }
                ]
            }
        }
    }
}`

    

### Expected result

{
    "item_id": 86590,
    "sku": "testbund2",
    **"qty": 1,**
    "name": "Bundle product 2",
    "price": 4705,
    "product_type": "bundle",
    "quote_id": "99264",
    "product_option": {
        "extension_attributes": {
            "bundle_options": [
                {
                    "option_id": 9,
                    "option_qty": 1,
                    "option_selections": [
                        17
                    ]
                },
                {
                    "option_id": 10,
                    "option_qty": 1,
                    "option_selections": [
                        18
                    ]
                },
                {
                    "option_id": 11,
                    "option_qty": 2,
                    "option_selections": [
                        19
                    ]
                }
            ]
        }
    }
}

### Actual result

{
    "item_id": 86590,
    "sku": "testbund2",
    **"qty": 2,**
    "name": "Bundle product 2",
    "price": 4705,
    "product_type": "bundle",
    "quote_id": "99264",
    "product_option": {
        "extension_attributes": {
            "bundle_options": [
                {
                    "option_id": 9,
                    "option_qty": 1,
                    "option_selections": [
                        17
                    ]
                },
                {
                    "option_id": 10,
                    "option_qty": 1,
                    "option_selections": [
                        18
                    ]
                },
                {
                    "option_id": 11,
                    "option_qty": 2,
                    "option_selections": [
                        19
                    ]
                }
            ]
        }
    }
}

### Additional information

**So, whatever the last option qty we have set, it reflect the same for main bundle product .i.e parent bundle.
In the above example, I set the last option product qty as 2, so it is adding 2 bundle product in cart.**

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @lokborn 

Thanks for reporting and collaboration.

It is not advisable to disable the MSI modules.Can you please provide the use cases for which you need to disable the MSI modules.

**Comment by lokborn** [comment]
Hi @engcom-Dash 

I have disabled all MSI modules as we do not need multiinventory setup in our case.
Also, it improves the performance of multiple APIs.

**Comment by engcom-Dash** [comment]
Hi @lokborn 

Thanks for reporting and collaboration.

As per the adobe dev docs, Disabling the Inventory Management modules can cause an unstable system and result in various issues.

Please refer the below devdocs for more information :

https://experienceleague.adobe.com/docs/commerce-admin/inventory/get-started/install-update.html

Thanks

**Comment by engcom-Dash** [comment]
Hi @lokborn 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
