### ISSUE TITLE
UPS error timeout error Magento CE 2.3.5-p2

### ISSUE THREAD

**Issue by sarveshunyscape** [magento/magento2#38271]
### Summary

Hi,

We have enabled UPS shipping method on our store but it's not showing on shipping method of checkout. When we checked the shipping log, we found the error is saying Timeout in 30 Seconds. Kindly help us.

### Examples

    'accept_UPS_license_agreement' => 'yes',
    '10_action' => '4',
    '13_product' => 'GNDRES',
    '14_origCountry' => 'US',
    '15_origPostal' => '18512',
    'origCity' => 'Throop',
    '19_destPostal' => '76115',
    '22_destCountry' => 'US',
    '23_weight' => 2.2,
    '47_rate_chart' => 'Regular Daily Pickup',
    '48_container' => '00',
    '49_residential' => '01',
    'weight_std' => 'lbs',
  ),
  'result' => 
  array (
    'error' => 'Read timed out after 30 seconds',
    'code' => 1000,
  )

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sarveshunyscape** [comment]
Hi Team,

Can anyone please look into this issue ASAP ? 

Any kind of help would be appreciated.

Thanks

**Comment by sarveshunyscape** [comment]
Hi,

Kindly update on us. Looking forward to hear from you.

Thanks

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by sarveshunyscape** [comment]
hi @engcom-Dash,

Kindly refer the screenshot, we are using magento CE 2.3.5-p2 version.
![Screenshot from 2023-12-20 15-24-01](https://github.com/magento/magento2/assets/86588672/4266b3c9-6041-4f20-bb78-8188fc38f075)

**Comment by engcom-Dash** [comment]
Hi @sarveshunyscape 

Thanks for reporting and collaboration.

Verified the issue in magento developer instance and the issue is not reproducible. 
We are able to see the UPS shipping method and able to place orders using the UPS shipping method.
Please refer the screenshots.
Please try upgrading your magento instance and let us know if you are still facing the issue. 
<img width="1440" alt="UPS_ss1" src="https://github.com/magento/magento2/assets/60198592/ad1c9abb-bfc8-4106-ab46-394770f58838">

**Comment by sarveshunyscape** [comment]
@engcom-Dash is the only option to upgrade our Magento instance to 2.4 ? UPS shipping should also work with Magento CE 2.3.5-p2 as it comes in Magneto package itself.

We tried to test it on fresh instance of magento 2.3.5 with UPS type "United Parcel Service" but we are getting the same error. 

Please suggest if something wrong with UPS account.

Thanks

**Comment by engcom-Dash** [comment]
Hi @sarveshunyscape 

Thanks for reporting and collaboration.

As of now we are not fixing functional issues related to security patches.

Please upgrade to latest version and it is recommended  to verify the issues in magento 2.4 dev instance

Thanks.

**Comment by RaguApto** [comment]
> @engcom-Dash is the only option to upgrade our Magento instance to 2.4 ? UPS shipping should also work with Magento CE 2.3.5-p2 as it comes in Magneto package itself.
> 
> We tried to test it on fresh instance of magento 2.3.5 with UPS type "United Parcel Service" but we are getting the same error.
> 
> Please suggest if something wrong with UPS account.
> 
> Thanks

@sarveshunyscape  Am also facing same issue with magento 2.4.6. Do you get any solution for this?

**Comment by sarveshunyscape** [comment]
> > @engcom-Dash is the only option to upgrade our Magento instance to 2.4 ? UPS shipping should also work with Magento CE 2.3.5-p2 as it comes in Magneto package itself.
> > We tried to test it on fresh instance of magento 2.3.5 with UPS type "United Parcel Service" but we are getting the same error.
> > Please suggest if something wrong with UPS account.
> > Thanks
> 
> @sarveshunyscape Am also facing same issue with magento 2.4.6. Do you get any solution for this?

No, they couldn't able to provide me the solution.
