### ISSUE TITLE
Internal server error - Use custom product attribute of type dropdown as sorting in Quuery Graphql Products

### ISSUE THREAD

**Issue by pjstaudt** [magento/magento2#38275]
### Preconditions and environment

- Magento version: Adobe Commerce ver. 2.4.6

### Steps to reproduce

1. Create a dropdown product attribute and check "Used for Sorting in Product Listing" = YES
![image](https://github.com/magento/magento2/assets/3769195/3d124aa5-db4d-4cc5-ad2f-210e9b3111df)
![image](https://github.com/magento/magento2/assets/3769195/e58f0650-24af-4668-ab11-296b756dd1c6)

2. Use the Products Graphql Query to search for products using the created attribute as ordering
https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/
`query Products {
    products(search: "anything", sort: { year: ASC }) {
        items {
            name
            sku
            year
            brand
        }
        aggregations {
            attribute_code
            label
            count
            options {
                label
                value
                count
            }
        }
        sort_fields {
            default
            options {
                label
                value
            }
        }
    }
}`

### Expected result

List of products sorted by year in ascending order

### Actual result

`{
    "errors": [
        {
            "message": "Internal server error",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "products"
            ],
            "extensions": {
                "debugMessage": "preg_match(): Argument #2 ($subject) must be of type string, Laminas\\Db\\Sql\\Expression given"
            }
        }
    ],
    "data": {
        "products": null
    }
}`

### Additional information

Change line 619 of the file vendor/magento/zend-db/library/Zend/Db/Select.php, temporarily fixes the problem for me

Original
![image](https://github.com/magento/magento2/assets/3769195/0c0c0709-0ea5-41fe-9036-bac1311445f7)

Adjusted
![image](https://github.com/magento/magento2/assets/3769195/96d0bbfc-0fee-403a-98e0-d54fa9797ca7)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @pjstaudt,

Thank you for reporting and collaboration.

As per this document https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#sort-attribute we can sort only with these attributes name,position,price,relevance.


![Screenshot from 2023-12-13 14-21-24](https://github.com/magento/magento2/assets/51680745/e4314f93-acff-4a56-a6a7-1590b98a01f3)


Could you please refer this document and please let us know if you are still facing any issue.

Thanks.

**Comment by pjstaudt** [comment]
Hello @engcom-Bravo! Thanks for the answer!

I believe that these attributes are Magento's native ordering attributes, but I can add a custom attribute via admin to be sortable.

Using the Luma theme I have no problem and I can order the products, but using the graphql query gives me the error.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @pjstaudt,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by guilhermemap** [comment]
this is marked as closed, but we had the same problem and fixed following this commit: https://github.com/magento/magento2-pwa/commit/a620083f6091fc0760bdf9271dca2bd98d77a3bf 
we made a custom plugin that deactivated the one with the issue from magento-eav-graph-ql-aux and activated our new one with the fixed line
