### ISSUE TITLE
Totals block cannot be moved in shopping cart page

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3827]
I am reporting this as a bug because my brain is broken trying to move the totals block bellow the product list in shopping cart.

If you see checkout_cart_index.xml, you can see this:

``` xml
<container name="checkout.cart.totals.container" as="totals" label="Shopping Cart Totals">
    <block class="Magento\Checkout\Block\Cart\Totals" name="checkout.cart.totals" template="cart/totals.phtml">
        <arguments>
            <argument name="jsLayout" xsi:type="array">....</argument>
       </arguments>
    </block>
</container>
```

The problem is that the totals appear above the product list. I need them to appear bellow the product list and above the buttons.

Whatever I did, wherever I move the container, the totals aren't displayed, They are displayed only if I keep it at the default location. If I move it, no totals are displayed at all.

The last test I did was:

Create a new container in my local checkout_cart_index.xml. Inside it, I copied the whole checkout.cart.totals.container container. Then, I changed names of the containers and the block (checkout.cart.totals.container2, checkout.cart.totals2) and even "totals" where changed to "totals2" and of course, display area where changed accordingly.

when I refresh the page, the result was: only the default totals container were shown. My copied container were not.

It is really a shame to lose several hours trying to do this simple thing.

Why when I move the block, all totals are lost but only when I display totals at default position? is it a real bug and something is hard coded inside the javascript?

Can you guide me to debug it in order to fix this problem by myself?

Thanks
Jaime

**Comment by minlare** [comment]
+1

**Comment by piotrekkaminski** [comment]
This question is a better fit for magento.stackexchange.com

**Comment by minlare** [comment]
@jaimestuardo I have managed to move the totals block below the products with the following xml

`<move element="checkout.cart.totals.container" destination="checkout.cart.items" after="checkout.cart.form"/>`

**Comment by hornofj** [comment]
This moves the whole summary
` <move element="cart.summary" destination="checkout.cart.items" after="checkout.cart.form"/>`

**Comment by BabliDey** [comment]
In my custom theme app/design/frontend/Mytheme/theme-frontend-shop/Magento_Checkout/layout/checkout_cart_index.xml 
`<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <update handle="checkout_cart_item_renderers"/>
    <body>
        <move element="cart.summary" destination="checkout.cart.container" after="checkout.cart.form"/>
    </body>
</page>`

pasted this and run php bin/magento cache:clean command. mgento version 2.1.8

**Comment by ketantambekar** [comment]
Thanks  minlare
