### ISSUE TITLE
multi-site store config broken?

### ISSUE THREAD

**Issue by miketsl** [magento/magento2#3828]
## Steps to reproduce
1. Install Magento v2.0.2
2. Stores->All Stores->create store  "test.com"
3. Stores->All Stores->create store view "test_view"
4. Edit pub/.htaccess:
       RewriteCond %{HTTP_HOST} ^(._)test.com
       RewriteRule ._ – [E=MAGE_RUN_CODE:test_view]
       RewriteCond %{HTTP_HOST} ^(._)test.com
       RewriteRule ._ – [E=MAGE_RUN_TYPE:store]
   
   ```
   SetEnvIf Host .*test.com.* MAGE_RUN_CODE=test_view
   SetEnvIf Host .*test.com.* MAGE_RUN_TYPE=store
   ```
5. Restart apache
6. Load http://test.com/
## Expected result
1. Same website as primarydomain.com, except its test.com in the browser window.
## Actual result
1. Error:  "There has been an error processing your request

Requested store is not found
Error log record number: 994532249202"

**Comment by piotrekkaminski** [comment]
@antonkril can you look into it?

**Comment by vzabaznov** [comment]
Hi @miketsl could you please provide info inside log file

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
