### ISSUE TITLE
Magento 2.4.6-p3 [InvalidArgumentException] error when installing Klarna after update

### ISSUE THREAD

**Issue by hanzels** [magento/magento2#38291]
A very good day,
We updated our shop from Magento 2.4.3 to Magento 2.4.6-p3.
Klarna has been removed from Magento and needs to be installed seperatly.
However we run into this error:

[InvalidArgumentException]
Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is
available in a stability which matches your minimum-stability (stable).

We've purchased Klarna in Marketplace, chose Magento Community in both pull downs, added login data to auth.json and ran:
php bin/magento maintenance:enable
composer require klarna/m2-klarna

How could we solve this issue?
Klarna support says it is a Magento issue. 

Any tips or help are very welcome.

Thanks in advance and best regards,

Hans

Magento version 2.4.6-p3
PHP 8.1
MySQL version 8.0.34 for Linux on x86_64

Expected result:
Klarna extensions installs.

Actual result:
Klarna doesn't install and gives this error:
[InvalidArgumentException]
Could not find a matching version of package klarna/m2-klarna. Check the package spelling, your version constraint and that the package is
available in a stability which matches your minimum-stability (stable).

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Bravo** [comment]
Hi @hanzels,

Thank you for reporting and collaboration.

“Klarna” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
