### ISSUE TITLE
Search for orders issue

### ISSUE THREAD

**Issue by MizoAhmed33** [magento/magento2#38292]
### Preconditions and environment

- Magento version 2.3.7-p4

### Steps to reproduce

the issue is , i searched for 100 orders in one time then the system stooped and i get this message ( Something went wrong with processing the default view and we have restored the filter to its original state. ) 
i can't use the system till now or search for orders 

i search from Sales --Orders 

### Expected result

ineed to search for orders andclear search area but 

### Actual result

Search area is loaded and i cannot use the system

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @MizoAhmed33,


Thank you for reporting and collaboration.

Can you please check this solution :

Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @MizoAhmed33,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
