### ISSUE TITLE
Product Search Optimization in backend retrieving set values

### ISSUE THREAD

**Issue by sangatpedas** [magento/magento2#3829]
## Steps to reproduce
1. Edit a product (in my case in a multi store view configuration, doesn't matter whether you choose default or specific store view)
2. Edit the search engine optimization meta tags
3. Save
## Expected result
1. On reload the new entered values show
## Actual result
1. The values are reset to the defaults even though the values are saved in the database and do show on the frontend.
2. When editing a product in a specific store view, the use of "Use Default Value" for URL key leads to empty URL key for that specific product in the specific store view =>  "domainname/.html"

<img width="1307" alt="before-save" src="https://cloud.githubusercontent.com/assets/5317971/13867821/7367aef2-ecf5-11e5-9986-3023b61c033a.png">
<img width="1221" alt="after-save" src="https://cloud.githubusercontent.com/assets/5317971/13867832/88076cd0-ecf5-11e5-8649-e95ef573abb2.png">

**Comment by piotrekkaminski** [comment]
@sangatpedas i'm not able to reproduce it. If you can reproduce it on latest version (2.1rc), please open a new issue.
