### ISSUE TITLE
Varnish configuration does not exclude all marketing parameters

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#38298]
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

Export the varnish configuration in the Magento admin and search for the part in the generated VCL file to determine that not all marketing parameters are excluded. 

### Expected result

All marketing parameters are excluded

### Actual result

Common marketing parameters are not excluded for instance: 

- gad_source (https://support.google.com/google-ads/answer/13327296?hl=en ) 
- srsltid (https://support.google.com/analytics/answer/11479699?hl=en ) 
- msclkid (https://help.ads.microsoft.com/apex/index/3/en/60000 )

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @dverkade,

Thank you for the report and collaboration!

We were able to verify this on 2.4-develop.
Exported the varnish configuration from the admin panel. it can be seen that `gad_source`, `srsltid `, `msclkid ` are missing from the excluded list of marketing parameters.
Please take a look at the screenshot:
<img width="1102" alt="image" src="https://github.com/magento/magento2/assets/60198231/fe3fbd0c-bb92-465c-977c-76bb1a83e7d6">

Hence confirming the issue.

Thank you.
