### ISSUE TITLE
How to get best seller product in magento 2 ON LINUX.

### ISSUE THREAD

**Issue by dohuudao** [magento/magento2#3830]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by piotrekkaminski** [comment]
Not able to reproduce. If you @dohuudao can reproduce on latest version and provide more information (logs, configuration), please open a new issue.
