### ISSUE TITLE
Bad redirect after login after a logout

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3831]
## Steps to reproduce
1. Magento 2.0.2
2. Sign in on frontend
3. After sign in, log out
4. Sign in again
## Expected result
1. Redirect customer to dashboard or current page
## Actual result
1. Redirect to logout Page
   ![sans titre 3](https://cloud.githubusercontent.com/assets/7326954/13875721/cdee3116-ecff-11e5-9ce5-f5829de70658.jpg)

**Comment by srenon** [comment]
@quienti ... What version of php are you running? 

_I'm not able to reproduce this issue on php v5.5.30 / apache v2.2.22_

**Comment by quienti** [comment]
PHP 5.5.30-1~dotdeb+7.1
Server version: Apache/2.2.22 (Debian)

**Comment by sevos1984** [comment]
Can't reproduce this issue as well, try clearing magento cache and your browser cache

**Comment by quienti** [comment]
Update to Magento 2.0.4 solve this problem
Sorry
