### ISSUE TITLE
Tax added twice if catalog prices are inclusive tax

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#3832]
Set catalog to be inclusive of tax. When visiting front-end, prices have tax added on top of that, as if it were using the prices as excl. tax.
## Steps to reproduce
1. Installed Magento 2.0.2 via composer
2. Set tax settings to catalog inclusive of tax:
   ![screenshot 2016-03-18 11 55 07](https://cloud.githubusercontent.com/assets/630320/13877100/8d58d07e-ed00-11e5-85ea-66178f0759e2.png)
3. Create a product with £100 incl tax
   ![screenshot 2016-03-18 11 55 40](https://cloud.githubusercontent.com/assets/630320/13877147/e22e6686-ed00-11e5-8b48-97dcff2e320b.png)
4. Clear cache, reindex, deploy static files, pray
5. Visit products page, add to basket
## Expected result
1. Would expect to see price of £100 on front end (or £83.33 if showing excl)
## Actual result
1. I see £120 for the product - bonus tax!

![screenshot 2016-03-18 11 55 57](https://cloud.githubusercontent.com/assets/630320/13877169/0d101ef8-ed01-11e5-86ab-931c9a5d7fdd.png)
2. This carries through to the cart where the tax is shown explicitly
![screenshot 2016-03-18 11 56 27](https://cloud.githubusercontent.com/assets/630320/13877172/1abdefd0-ed01-11e5-856d-12f8952ef778.png)

I cannot think of anything else to clear. Why is the catalog price still being treated as excluding tax?

**Comment by maderlock** [comment]
Repeated issue with latest copy of develop branch.

**Comment by heyitsroberthe** [comment]
Could you try disabling the full page cache in cache management and refresh the pages? In addition, could you also list your tax rates and rules?

**Comment by sangatpedas** [comment]
I had the same issue, I set that prices are entered including tax but either the shopping cart showed 0 tax or added tax on top of the price including tax. What I did to solve it:
1. Disable all cache and flush cache storage
2. Set "Tax calculation based on" Shipping Origin
3. Don't forget to set Shipping Origin in "Configuration -> Sales -> Shipping Settings"

After I enabled all cache (in my specific case all but FPC) and all worked as supposed to. I remember this ticket is similar to a ticket before of which I got the above solution but unfortunately I can't find that ticket anymore.

**Comment by mikeweis** [comment]
Another thought is if your indexers are on schedule, as opposed to on update, then there will be a delay in seeing your changes.  To speed things along:  bin/magento indexer:reindex

**Comment by mikeweis** [comment]
We are sorry, but we not able to reproduce this problem having no response from you.  Do not hesitate to contact us later if this problem is still present and provide requested details.

**Comment by maderlock** [comment]
Apologies for not responding to this - I wasn't getting notifications. I'll test again on the latest version..

**Comment by mikeweis** [comment]
@maderlock Thanks!

**Comment by maderlock** [comment]
I can confirm that having upgraded to 2.0.7 this issue still exists. I can reindex and I still see this:
- Price in catalog: £100
- Tax rate: 0.2
- Tax setting for catalog: Inclusive of VAT (very important - this is definitely the setting used)
- Price on front-end: £120
- Tax breakdown in checkout: £100 excl of VAT, £20 tax

**Comment by maderlock** [comment]
I've now pulled down the latest from the develop branch (2.1 rc-2) and I see the same thing.

If you are unable to reproduce this, then please ensure that you have Inclusive of VAT set and that you have a tax rule for your current location that maps standard customers and standard products to a 20% rate.

I would have expected a lot more complaints if this fundamental issue was actually buggy, but I cannot find any fault in my own logic: prices incl of VAT entered & VAT then added on top when checking out = an error, correct?

**Comment by hopinator** [comment]
I had this problem and it came down to changing a shipping setting

stores -> configuration -> sales -> shipping settings

Change Origin from United States to your country (I changed mine to Australia).

For some reason that fixed my problem. Even though in Tax -> Calculation Settings -> Tax Calculation Based On = shipping destination and not shipping origin, it was adding extra GST onto the price. 

Dont know if that is a bug or a feature.

**Comment by maderlock** [comment]
Thank you, @hopinator. That stopped the tax being added again. I think that this is a feature, as when prices are specified inclusive of tax then Magento has to make an assumption about what the default tax is. Closing as this is not an issue.

**Comment by VincentMarmiesse** [comment]
Hi @maderlock,
I have the same issue and I don't see why it's not an issue and why changing shipping origin should resolve it.

**Comment by ganedda-softfobia** [comment]
Why is this issue is closed? How could that be a solution?
What about orders that have no shipping? Ie. virtual products

**Comment by qsolutions-pl** [comment]
If anyone follows this... bug is always visible if you configurethis:
![image](https://user-images.githubusercontent.com/4256191/123960743-f3ef9100-d9af-11eb-8e14-2146d6dd93b9.png)

**Comment by mrtuvn** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
@qsolutions-pl what else the preconditions for the issue to reproduce problem ?
