### ISSUE TITLE
Indexer not working with PHP 7 (7.0.4)

### ISSUE THREAD

**Issue by jackiellowery** [magento/magento2#3833]
## Steps to reproduce
1. Install Magento `2.0.2`. (apache 2.4.18, php 7.0.4, mariadb 10.0.24)
2. Import products from Magento 1.7.x store.
3. In Magento backend, set indexes to update on schedule.
4. Run `php bin/magento indexer:reindex`.
## Expected result
1. All indexes reindexed.
## Actual result

```
[~/www/dev]# bin/magento indexer:reindex -vv



  [InvalidArgumentException]
  There are no commands defined in the "indexer" namespace.



Exception trace:
 () at /home/dev/public_html/dev/vendor/symfony/console/Symfony/Component/Console/Application.php:501
 Symfony\Component\Console\Application->findNamespace() at /home/dev/public_html/dev/vendor/symfony/console/Symfony/Component/Console/Application.php:535
 Symfony\Component\Console\Application->find() at /home/dev/public_html/dev/vendor/symfony/console/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/dev/public_html/dev/vendor/magento/framework/Console/Cli.php:49
 Magento\Framework\Console\Cli->doRun() at /home/dev/public_html/dev/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/dev/public_html/dev/bin/magento:25
```
## Workaround
1. if i run `/opt/bin/php56/bin/php bin/magento indexer:reindex` indexing succeeds.

**Comment by jackiellowery** [comment]
if i run `/opt/bin/php56/bin/php bin/magento indexer:reindex`  indexing succeeds.

**Comment by vzabaznov** [comment]
@jackiellowery maybe you have wrong permission, try to do it with **sudo**

**Comment by jackiellowery** [comment]
i tried sudo too, but it didn't work.  it only works if i specify path to php56, and i don't need to sudo with php56.

**Comment by piotrekkaminski** [comment]
@jackiellowery can you reproduce it on latest version 2.1rc or develop branch using latest PHP7? There are some issues with some versions of PHP7 but 7.0.6 should work ok. I'm not getting this error. If you are, please open a new issue.
