### ISSUE TITLE
Overwriting ObjectManager's $sharedResources leads to strange DI behaviour

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#3835]
## Steps to reproduce
1. M2 2.0.2
2. In `developer` mode (don't think it matters though), inject `\Psr\Log\LoggerInterface` into any constructor.
## Expected result
1. Logging using `\Psr\Log\LoggerInterface` should produce lines in `system.log`, `debug.log`, `exception.log` or `support_report.log`, depending on level etc.
## Actual result
1. Everything gets logged into `support_report.log`, including exceptions, layout debug info etc.
## More info

We've recently upgraded to 2.0.2 and it dawned to me that nothing but a few lines were logged into `system.xml`, `exception.log` was empty even though I had one, my debugging logging wasn't working etc.

Investigating the problem, I saw that `\Magento\Framework\Logger\Monolog` (thus `\Monolog\Logger`) was instantiated 2 times: firstly, with 2 handlers: **system** and **debug** (normal handlers), secondly, with only one handler: `Magento\Support\Model\Logger\Handler\Report`. I would expect those three handlers to be merged.

I originally thought some error had slipped when upgrading, and the ObjectManager got instantiated twice, as when searching for `\Psr\Log\LoggerInterface`, the manager couldn't find it, so it created it again, but _this time with the second handler_. 

But that wasn't the case: the manager was instantiated only once. The reason it couldn't find the original logger (with the 2 handlers) was that the `$sharedInstances` was being replaced: https://github.com/magento/magento2/blob/d50ee54534df30f732f2343e39ef90b0faf0364b/lib/internal/Magento/Framework/App/ObjectManager/Environment/Developer.php#L85.

The conclusion is that the original `$sharedInstances` which contains a logger instance is getting replaced with _another_ instance with different handlers.

Maybe it's something in our app, but it's worth some investigation, maybe? I also find this a little flaky, as between grabbing the original resources and up until the new ones are loaded, various other instances are created, which will eventually be replaced.

**Comment by antonkril** [comment]
It looks like main reason for such behavior is the way how di.xml is merged between stages.
system & debug handlers are registered in initial configuration (app/etc/di.xml)

But in global configuration of Support Module (Support/etc/di.xml) Support logger is registered. It overrides previous configuration, because arguments defined at later stages of configuration override arguments defined on previous stage of configuration. I can see, that system & debug handlers are already added in etc/di.xml of latest version of Support module.

Quick fix for you is to register them in /etc/di.xml of your module.

**Comment by adragus-inviqa** [comment]
Thanks for the quick reply, @antonkril; I'll try your suggestion.

> I can see, that system & debug handlers are already added in etc/di.xml of latest version of Support module.

Are you saying that the system and debug handlers are added _once again_ in the Support module, besides the main `app/etc/di.xml` file?

**Comment by antonkril** [comment]
Yes, because global configuration _overrides_ arguments configuration of primary configuration.

**Comment by adragus-inviqa** [comment]
Seems a bit duplicating.
But if `Support` is the module which declares the logging handlers, so be it.
Thanks.
