### ISSUE TITLE
how to upgrade a magento 2.4.x to 2.4.x(the latest one) through using GITHUB

### ISSUE THREAD

**Issue by hariprabhu-rajan** [magento/magento2#38362]
### Summary

in my case: it's already in live,

the site has two stages 
     -- 1. stagging site(for text and deploy)
     --2. production site(live)

now i want to upgrade my version for the latest one but i previous methods are not gonna work(used by composer). 

i don't know where i did wrong. 
 the steps i followed in ; 
1. clone the repo to local machine
2. backup the files 
3. start to upgrade by offical sites guidance, [here is the link](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html?lang=en)

### Examples

i need the assist to done this job. please  guide me

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @hariprabhu-rajan 
Thank you for your question, but I think your question is not relevant to this project.
I think you can request the assist in the Magento Slack (https://developer.adobe.com/open/magento/slack)

I will close this issue as not relevant
