### ISSUE TITLE
how to solve "lock file but not in remote repositories, make sure you avoid updating this package?

### ISSUE THREAD

**Issue by hryksbt** [magento/magento2#38369]
### Summary

hello folks, i tried to upgrade my magento 2.4.3-p1 version to 2.4.5-p3  via composer. i encountered some errors. 

i cloned it from the private github repo. then after i start to upgrade the version using by composer in my local machine. i got stucked in this step. only few articles avail related to this but those also don't have a answers. 

**the command i used in terminal  : composer update** 

### Examples

**error:** 

`Problem 1 - Root composer.json requires stripe/stripe-payments ^3.3.0, found stripe/stripe-payments[3.3.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.

Problem 2 - Root composer.json requires weltpixel/module-google-tag-manager ^1.10.18, found weltpixel/module-google-tag-manager[1.10.18] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.`

### Proposed solution

i need some details for understand this issue. and i wants to upgrade to preferable version

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @hryksbt 
Thank you for your question.
But I don't see the platform's problems here.
The Github project designed to eliminate bugs or problems in the platform, but not in a private project.
I would recommend you go to the Magento Slack and request help for you there.
I'll close this issue as not relevant.
