### ISSUE TITLE
Product Type changes after image upload

### ISSUE THREAD

**Issue by ivanszabo** [magento/magento2#3837]
## Steps to reproduce
1. Create a configurable product, do not include an image initially
2. Save it and go back to the products grid
3. Go back in and upload an image, Save and go back to the products grid
## Expected result
1. Image should be uploaded
2. The product type should remain as configurable
## Actual result
1. Image is uploaded
2. Product type is set to **simple**

**Comment by piotrekkaminski** [comment]
Reproducible on 2.1rc. As long as you don’t assign products (configurations), the product will show up as simple product in the list, even if you start creating it as configurable. You can edit it again, assign configurations and it will show up later as configurable. @antboiko please review if it's ok or a bug.

**Comment by antboiko** [comment]
Hi @ivanszabo , thanks for your inquiry. 

It's a correct behavior. If there are no associated configurations then product will be saved and displayed as Simple in the grid. As soon as you add at least one configuration and save the product it becomes Configurable. 

I'm closing this issue. Please feel free to reopen it if needed.

Best,
Anton.
