### ISSUE TITLE
Import History Execution Time wrong for other than en_US user locale

### ISSUE THREAD

**Issue by mihaimatei** [magento/magento2#38373]
### Preconditions and environment

- Magento Community version up to 2.4.7-beta2 and 2.4-develop
- fresh install without sample data, on ddev environment
- tested also on version 2.3.7

### Steps to reproduce

1. Access admin of vanilla instance, any version (tested from 2.3.7 to 2.4.7-beta2)
2. Change admin user locale to "German (Switzerland)" [de_CH] or "Romanian" [ro_RO] - this can be also done at any point before the Import runs (if vanilla instance with no language packs installed to affect the export)
3. Create a test product
4. System > Export > Products: CSV, Enclose fields > Export > Run Cron > Download CSV
5. System > Import > Products / Behaviour: Add/Update > Check Data > Import
6. System > Import History > Check "Execution Time" column which shows wrong time interval

<img width="1592" alt="execution-time-wrong-when-non-en_US-locale" src="https://github.com/magento/magento2/assets/7760282/8b03879d-bf51-4cd3-8739-26d31c076ead">

### Expected result

Import History shows correct execution time of the import when import is run by a user with non-en_US locale (de_CH and ro_RO tested)

### Actual result

Import History shows incorrect execution time of the import when import is run by a user with non-en_US locale (de_CH and ro_RO tested)

### Additional information

Problem appears in the [\Magento\Framework\Stdlib\DateTime\Timezone::date](https://github.com/magento/magento2/blob/75f576f6b919385f3826a1368fd1e42ac9b7c0ae/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L191) method, in the switch branch of `case (!is_numeric($date))`.

Below is a summarised stack trace with relevant dumps which I've performed to track the issue:
## IMPORT CSV - en_US locale admin user - CORRECT Execution Time
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime = 'Validation')`
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime = 'In Progress')`
\Magento\Framework\Stdlib\DateTime\Timezone::date($date = '2024-01-22 15:42:12')
- dump `$locale`: `en_US`
- dump `$timezone`: `Europe/Berlin`
- `case (!is_numeric($date))` matched
  - After switch cases before return, obtained timestamp in $date: **`1705938132`**
- dump `date('Y-m-d H:i:s', $date)`: **`'2024-01-22 15:42:12'`**
`\Magento\ImportExport\Helper\Report::getExecutionTime($time = '2024-01-22 15:42:12')`
- dump Expected format (`$this->timeZone->getDateTimeFormat(\IntlDateFormatter::SHORT)`): `M/d/yy h:mm a`
- dump Diff days ($timeDiff->days): `0`
- dump Diff full formatted (`$timeDiff->format('%Y-%m-%d %H:%I:%S')`): `'00-0-0 00:00:04'`
- Diff as returned by method (`$timeDiff->format('%H:%I:%S')`): `'00:00:04'`
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime  = '00:00:04')`

## IMPORT CSV - de_CH locale admin user - WRONG Execution Time
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime = 'Validation')`
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime = 'In Progress')`
`\Magento\Framework\Stdlib\DateTime\Timezone::date($date = '2024-01-22 15:59:51')`
 - dump `$locale`: `de_CH`
 - dump `$timezone`: `Europe/Berlin`
 - `case (!is_numeric($date))` matched
     - After switch cases before return, obtained timestamp in `$date`: **`1815832740`** <---- PROBLEM HERE 
 - dump `date('Y-m-d H:i:s', $date)`: **`'2027-07-17 13:59:00'`**
`\Magento\ImportExport\Helper\Report::getExecutionTime($time = '2027-07-17 13:59:00')`
- dump Expected format (`$this->timeZone->getDateTimeFormat(\IntlDateFormatter::SHORT)`): `dd.MM.yy HH:mm`
- dump Diff days (`$timeDiff->days`): `1271`, 
- dump Diff full formatted (`$timeDiff->format('%Y-%m-%d %H:%I:%S')`): `'03-5-25 22:58:56'`, 
- Diff as returned by method (`$timeDiff->format('%H:%I:%S')`): `'22:58:56'`
`\Magento\ImportExport\Model\History::setExecutionTime($executionTime  = '22:58:56')`

The execution time might not seem important for user triggered csv imports, but when a custom import is built over the import-export module and imports run as scheduled tasks, import history execution time might be of importance to assess the health of the import, hence the severity can be evaluated even as S2.

In case of a custom import built on top of the import-export module, workaround for getting the correct execution time would be to set locale to en_US before triggering the import methods, but this might affect other data handling in the actually imported data.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @mihaimatei 

Thanks for reporting and collaboration.

Verified the issue on both magento 2.4 dev instance and 2.4.7-beta2 instance but the issue is not reproducable.

Seeing correct import history execution time for non-en_US locale.

Please refer the screenshots attached.

<img width="1440" alt="38373_1" src="https://github.com/magento/magento2/assets/60198592/94febe14-f276-4d0a-9c76-705b18c50b84">
<img width="1440" alt="38373_2" src="https://github.com/magento/magento2/assets/60198592/58f6aed7-92f2-4234-9f11-74d045afe089">

**Comment by mihaimatei** [comment]
@magento give me 2.4-develop instance

**Comment by mihaimatei** [comment]
Hi @engcom-Dash , thank you for checking!
In your test, I see you changed the General settings locale, and this is why you probably cannot replicate.
In the Steps to reproduce, I've mentioned "Change admin user locale", without touching General settings locale, so they should be left to default (Locale: English US, Timezone: Los Angeles).

Here is the result following my Steps to reproduce, on the provided Magento instance offered by the deployment service:
<img width="1704" alt="Screenshot 2024-01-24 at 14 23 22" src="https://github.com/magento/magento2/assets/7760282/521ff0d3-3f56-4523-9923-22019000be0c">

You can also access this instance and: 
- change the admin user locale to en_us (System > Permissions > All Users > edit admin user > Interface Locale)
- run import on the same exported file and check reported execution times
- change the admin user locale to de_ch (System > Permissions > All Users > edit admin user > Interface Locale)
- run import on the same exported file and check reported execution times
- notice the wrongly calculated times

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @mihaimatei 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance and the issue is reproducable.

The import history execution time is wrong for other than en_US user locale.

Please refer the attached screenshot.

<img width="1440" alt="Screenshot 2024-01-25 at 12 39 57 PM" src="https://github.com/magento/magento2/assets/60198592/fee84b57-2340-4af0-bb87-8da72b7d32c5">

**Comment by lucafuser** [comment]
@magento give me 2.4-develop instance

**Comment by lucafuser** [comment]
Hi @engcom-Dash i verified the issue on my local Magento 2.4-develop instance and i'm not able to reproduce the issue, could you please verify?

Steps to reproduce (rif. https://github.com/magento/magento2/issues/38373#issuecomment-1908043801):
- change the admin user locale to en_us (System > Permissions > All Users > edit admin user > Interface Locale)
- run import on the same exported file and check reported execution times
- change the admin user locale to de_ch (System > Permissions > All Users > edit admin user > Interface Locale)
- run import on the same exported file and check reported execution times
- notice the wrongly calculated times

**Comment by engcom-Delta** [comment]
Hi @mihaimatei ,


Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Change admin user locale to "German (Switzerland)" [de_CH] or "Romanian" [ro_RO] - this can be also done at any point before the Import runs (if vanilla instance with no language packs installed to affect the export)
Create a test product
![image](https://github.com/user-attachments/assets/6a0ded02-e8b7-4a8a-81a3-3beaf5ff4375)

2. System > Export > Products: CSV, Enclose fields > Export > Run Cron > Download CSV
3. System > Import > Products / Behaviour: Add/Update > Check Data > Import
4. System > Import History > Check "Execution Time" column which shows wrong time interval
5. Observe , execution time is displaying as expected even after setting admin user locale to switzerland.
![image](https://github.com/user-attachments/assets/780fd74a-59ff-4256-8cb5-a1097a4cf1a5)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.
