### ISSUE TITLE
Catalog Search index process error during indexation process: Could not ping search engine: No alive nodes found in your cluster

### ISSUE THREAD

**Issue by cmyk337** [magento/magento2#38370]
### Preconditions and environment

- Magento version: 2.4.6-p3
- Anything else that would help a developer reproduce the bug: Hostmonster webhosting environment with PHP 8.2, by one click installation
After complete installation, I do not see product lists on webpage. Products are not showing even though I selected samples during installation. 

### Steps to reproduce

Catalog search engine default was opensearch. But, no catalog search is working, either opensearch nor elasticsearch 7. As I do 'test connection' catalog search in stores - configuration - catalog, 'No alive nodes found in your cluster' error massage is displayed. 

### Expected result

I want to see products. No products are displayed. 
I want to add products. Unable to add any product. 
I want to search products. Catalog search is always error, nothing is showing. 

### Actual result

Tried to reindex in SSH. As running php bin/magento indexer:reindex
Product Price index has been rebuilt successfully in 00:00:02
Catalog Search index process error during indexation process: --> Error
Could not ping search engine: No alive nodes found in your cluster --> Error 
How can I fix these issues? 

### Additional information

'No alive nodes found in your cluster' error displayed as test connection on configulation - catalog

![Capture-error](https://github.com/magento/magento2/assets/157440093/4d7a50e2-10e9-4ca6-bef3-9352367d8481)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @cmyk337 

Thanks for reporting and collaboration.

Verified the issue in mangeto 2.4 dev instance with php@8.2 opensearch 2.5.0 and elasticsearch 7 but the issue is not reproducible.

The connection is successfully, able to run reindex commands and add the products successfully.

Please refer the screenshots attached.
<img width="1440" alt="38370_1" src="https://github.com/magento/magento2/assets/60198592/b67012ae-fa34-462e-90f7-9dac71395a5a">
<img width="1440" alt="38370_2" src="https://github.com/magento/magento2/assets/60198592/1f5e8f1c-3a8c-4dfb-adb0-34b67de1540a">
<img width="1440" alt="38370_3" src="https://github.com/magento/magento2/assets/60198592/7f76fff5-2cf0-42c6-9f25-6305dc6e0e8c">

**Comment by cmyk337** [comment]
Hi engcom-Dash,
Thank you very much for your reply. I am very new here, and like a lot magento 2.4.6. 

1. What is your attached images? It seems you checked it under your local server. Again, I am very new here on this message board, and I am trying to resolve this error issue under my site that are running Hostmonster webhosting.

2. As I mentioned on my previous posting, I installed Magento 2.4.6-p3 by 1-click installation under Hostmonster webhosting c-panel. I didn't touch any thing. It went through well and gave me Admin Access of Magento 2.4.6-p3.

3. I searched whole last week to fix 'product not showing issue', and read about reindex via SSH. So, I ran it found the following error while reindex. I ran it under my webhosting Hostmonster SSH. 
![Capture-error-1](https://github.com/magento/magento2/assets/157440093/bce12f31-9705-4546-a088-268f795981a7)

Could you help me how to fix this issue under my webhosting at Hostmonster environment? Should I put some kinds of SSH command to fix? Or, change some value under Magento Back End Admin? 

4. 'No alive nodes found in your cluster' kept showing while I click 'Test Connection' under Admin - Configuration - Catalog. Could you help me how to fix this issue and use Magento 2.4.6-p3 properly under Hostmonster webhosting environment?

![Capture-error](https://github.com/magento/magento2/assets/157440093/31f353c4-2d37-42ca-8b9f-58c3770958c5)

Many many thanks.
Best,
cmyk337

**Comment by engcom-Dash** [comment]
Hi @cmyk337 

We wont be able to test the issue on your Hostmonster webhosting site.

Please check if the opensearch is working or not. If its not working , start the opensearch

This board is for issues. Any queries should be posted on https://magento.stackexchange.com/.

Please post the query on the https://magento.stackexchange.com/

**Comment by cmyk337** [comment]
Hi,

1. How can I check if the opensearch is working? As I see Store - Configuration - Catalog, the opensearch was set as default. As I test connection, No alive nodes found in your cluster just as I posted the error image. After 1-click installation under c-panel on Hostmonster, I haven't touch any thing. Every thing should be set as default mode. 

2. Is there any way to start the opensearch if it was turn off as a default mode? How can I turn it on? 

Thanks.

**Comment by engcom-Dash** [comment]
Hi @cmyk337 

This board is for issues. Any queries should be posted on https://magento.stackexchange.com/.

Please post the query on the https://magento.stackexchange.com/
