### ISSUE TITLE
ProductRepository function GetById does not create the correct cache key

### ISSUE THREAD

**Issue by MaximGns** [magento/magento2#38384]
### Preconditions and environment

- 2.4.6-p3

The ProductRepository's function `getById` does not create the correct cache key based on $editMode and $storeId.
The $storeId can be passed as string and int. But before the cache key is created, the $storeId is not parsed to an integer.

See difference with the `get` function.

`get`
```
$cacheKey = $this->getCacheKey([$editMode, $storeId === null ? $storeId : (int) $storeId]);
```

`getById`
```
$cacheKey = $this->getCacheKey([$editMode, $storeId]);
```

### Steps to reproduce

Use the product repository in a class

Retrieve the product by using the repositories method 'getById' with same parameters except the $storeId should be once string and the other time it should be and integer

```
$product = $this->productRepository->getById(1, false, '1');
$product = $this->productRepository->getById(1, false, 1);
```

Product is retrieved twice from database

### Expected result

When using the `getById` method with same store value (string or int). The second time the product should be retrieved from memory.

### Actual result

Product is retrieved twice

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @MaximGns,

Thank you for the report and collaboration!

Veified this issue on 2.4-develop.
When using `getById` first time with string and second time with integer, the product is loaded twice from the database, and not from the memory.

Hence confirming the issue.

Thank you.

**Comment by MaximGns** [comment]
@magento I am working on it

**Comment by MaximGns** [comment]
@magento add to contributors team

**Comment by MaximGns** [comment]
@magento I am working on it
