### ISSUE TITLE
Not able to open product -> catalog in admin panel 

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#3839]
I have 430 products in my magento database. when i am trying to open product -> catalog from admin panel, magento 2 is getting hanged. now i am not able to see the catalog list or add new product

**Comment by piotrekkaminski** [comment]
@arunkasyakar are you getting any errors in server error.log file? how much memory is configured for PHP and on the web server? Magento Forums (community.magento.com) might be a better place for this question.
