### ISSUE TITLE
Merging css and js produces errors on magento 

### ISSUE THREAD

**Issue by sachinsancheti1** [magento/magento2#3840]
While checking out the settings today, I found this setting where all the css and js files can be merged so that it makes it easier for a website to load. When enabling that setting, that's when things went really weird with the UI. I'm using the default luma white theme for the website at this point and not added any custom css or js files.

here are a couple of screenshots for you to check out. (JS cache flushed and rest refreshed)
![jss-css bundle merge all enabled](https://cloud.githubusercontent.com/assets/6279770/13899278/6e3b9148-ee10-11e5-8afa-32c2099858b2.jpg)

![jss-css bundle merge issue](https://cloud.githubusercontent.com/assets/6279770/13899282/78c41a86-ee10-11e5-8e12-4443fc483c30.jpg)

**Comment by der-workfloh** [comment]
You enabled the template and block hints for the storefront and admin area in the developer configuration. That's why the red blocks are appearing.

**Comment by sachinsancheti1** [comment]
Ah! got that. Thanks. I have fixed it now.
