### ISSUE TITLE
error creating catalog 

### ISSUE THREAD

**Issue by knidie** [magento/magento2#3841]
error creating catalog if save with images will return this 
Notice: A non well formed numeric value encountered in /var/www/html/magento2/vendor/magento/framework/Image/Adapter/Gd2.php on line 467

no error if without images

**Comment by piotrekkaminski** [comment]
@knidie can you provide more details how to reproduce on latest version? The exact steps? are you trying to create a product or category?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
