### ISSUE TITLE
Magento\Framework\Api\DataObjectHelper has bug

### ISSUE THREAD

**Issue by chenglinag** [magento/magento2#38423]
### Preconditions and environment

- 2.4.6

### Steps to reproduce

https://github.com/magento/magento2/issues/36723   
Version 2.4.6, this bug reappeared
I found this issue by comparing the code

### Expected result

I found this issue by comparing the code

### Actual result

I'm sorry，I found this issue by comparing the code

### Additional information

Not sure why, the 2.4.6 branch was not found on github

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
The [fix](https://github.com/magento/magento2/commit/7ca752f5a3355059aa457f1cfc03402777de0250) from https://github.com/magento/magento2/issues/36723 was not released yet, it will be released in Magento 2.4.7
So either patch it in your current installation, or wait 2 more months until Magento 2.4.7 gets released.

**Comment by chenglinag** [comment]
@hostep 

Thanks, I'm going to try to patch it with composer patch
