### ISSUE TITLE
Error: Class "Zend\Mail\Message" not found

### ISSUE THREAD

**Issue by nicholasfishjgm** [magento/magento2#38421]
### Summary

This is a heads up for other developers that may run into similar issues.

- SMTP mail extension stopped working due to referencing Zend/Mail. This previously worked on v2.4.6-p3 before a routine patch application.
- Prevents mail sending

### Examples

We are running on 2.4.6-p3. We recently applied a patch for an issue, and had to run composer update, however, this inadvertently broke our 3rd party Mail extension, throwing the following error:

```bash
Error: Class "Zend\Mail\Message" not found in /vendor/mageplaza/module-smtp/Mail/Transport.php:115
```

After debugging, this was caused by laminas/laminas-server updating from v2.16.0 to v2.17.0, which caused laminas/laminas-zendframework-bridge to be removed. This package is required by a lot of 3rd party SMTP extensions that still use Zend\Mail.

As a workaround, I have added "laminas/laminas-zendframework-bridge": "1.8.0" as a project dependancy in composer.json.

### Proposed solution

I'm not entirely sure what is best long term, should we throw deprecation notices for the use of Zend Mail?

Should Magento still require laminas-zendframework-bridge as a dependancy or lock down laminas-server to v2.16.0 until the next minor release?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Good find and explanation, also good you've specified the simple workaround, will be helpful in case other people run into a similar problem.

However, if Magento itself doens't reference any Zend code, it should not require `laminas/laminas-zendframework-bridge` in my opinion.

In your case, I think you  should also report this problem to `mageplaza/module-smtp` and have them look into how they can solve this problem.

**Comment by nicholasfishjgm** [comment]
Agreed @hostep. I was conscious of raising this as a Magento issue, but I felt it needed to be in the public domain as I can see this affecting quite a lot of people.

I have reported to mageplaza so will see what they come back with.

**Comment by hostep** [comment]
Isn't it better to introduce `laminas/laminas-zendframework-bridge` as explicit dependency instead of downgrading `laminas/laminas-server`?

**Comment by shaughnlgh** [comment]
@hostep it probably is the better approach yes.

**Comment by engcom-November** [comment]
Hello @nicholasfishjgm,
Thank you for the report and collaboration!
Thank you @hostep, @shaughnlgh for inputs!

As mentioed here https://github.com/magento/magento2/issues/38421#issuecomment-1929292827, It would be better if `laminas/laminas-zendframework-bridge` is added as explicit dependency rather then downgrading.
Hence marking this as feature request.

Thank you.

**Comment by hostep** [comment]
@engcom-November: no that's not for Magento to deal with. It's for end users or for 3rd party modules to do.

I would just close this ticket. People will still be able to find this info through search engines probably.

**Comment by idlea** [comment]
Mageplaza sent me a fix they will do a permanent fix in the next release.

**Comment by AlexandreBulete** [comment]
> Mageplaza sent me a fix they will do a permanent fix in the next release.

Hi, Can you share this fix please ?

**Comment by idlea** [comment]
> > Mageplaza sent me a fix they will do a permanent fix in the next release.
> 
> Hi @idlea , Can you share this fix please ?

I have asked Mageplaza to comment here

**Comment by nghiatt01** [comment]
hi @nicholasfishjgm,
Thanks for your contribution. We have released new version ([4.7.11](https://github.com/mageplaza/magento-2-smtp/tree/v4.7.11)) to fix this issue.

**Comment by techguysourav** [comment]
Hello, 

Mageplaza Smtp has been fixed with Laminas library.

**Comment by idlea** [comment]
> > Mageplaza sent me a fix they will do a permanent fix in the next release.
> 
> Hi @idlea , Can you share this fix please ?

they have fixed it

**Comment by techguysourav** [comment]
yes, they fixed it in a new release at github.
