### ISSUE TITLE
Unable to Add Configurable Products ( -b 2.0, -b develop )

### ISSUE THREAD

**Issue by signalprime** [magento/magento2#3842]
## Steps to reproduce
1. Install Magento from `develop` or `2.0` branch. (both were tested)
2. Add `Configurable Product` to the Catalog.
## Expected result
1. A `Create Configurations` button at the bottom of the page to add a `Configurable Product` to the Catalog.
2. A popup window for creating configurations with 4 steps.
3. Create Configurations
4. Save and Close
5. Configurable Product is Created
## Actual result
1. No `Create Configurations` button appears after selecting add `Configurable Product` in Catalog Administration.
2. A Simple Product is Created, despite the URL of the page creating the product including the word `configurable`: 
   http://127.0.0.1/admin/catalog/product/new/set/4/type/configurable/key/xxxxxxxxxxxxx/ 

Additional Notes:
Upon saving the product and viewing in the admin product grid, the newly added product type shows as `Simple Product` rather than `Configurable Product`

**Comment by piotrekkaminski** [comment]
@greg234234 i'm not able to reproduce it. If it still happens in 2.1rc or develop versions, please open a new ticket.
