### ISSUE TITLE
duplicate code normalizePath method

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#3844]
this is more of a minor design issue. I recently needed a method to normalize a file system path.

Looking at the core, I found the method(s) for this, but implemented directly in the classes where they are used:

https://github.com/magento/magento2/blob/2d82d19010a2deee42ab67e62627b84169f0ab8a/lib/internal/Magento/Framework/View/FileSystem.php#L169

https://github.com/magento/magento2/blob/2d82d19010a2deee42ab67e62627b84169f0ab8a/lib/internal/Magento/Framework/Setup/SampleData/FixtureManager.php#L62

As I did not really need any of the classes, I implemented this method (a third time) in my own class.

A good place would be maybe the Frameworks File System Class: https://github.com/magento/magento2/blob/2d82d19010a2deee42ab67e62627b84169f0ab8a/lib/internal/Magento/Framework/Filesystem.php

What do you think about it? I could start a small pull request for that

**Comment by piotrekkaminski** [comment]
@antonkril can you check it?

**Comment by antonkril** [comment]
Makes sense.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/duplicate-code-normalizePath-method/idi-p/45285).
