### ISSUE TITLE
Your license was locked. Please contact our support team for more information.

### ISSUE THREAD

**Issue by guillaumerentabilisense** [magento/magento2#38456]
### Summary

Any one knows what's it's related to?  We are using Magento ver. 2.4.1 Open Source

Revalidating doesn't do anything and  the link goes to https://www.yourwebsite.com/magento_admin/mstcore/lc/refresh/key/ebef432e8cdf811ece91a8f5b2db8e49d11e5c3914c47568b36a05530698f26e/

![image](https://github.com/magento/magento2/assets/6472569/027be031-3a0f-42b1-b273-bcccbf68df3d)

### Examples

Revalidating doesn't do anything and  the link goes to https://www.yourwebsite.com/magento_admin/mstcore/lc/refresh/key/ebef432e8cdf811ece91a8f5b2db8e49d11e5c3914c47568b36a05530698f26e/

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by guillaumerentabilisense** [comment]
@magento give me 2.4-develop instance

**Comment by devchris79** [comment]
Looks like a mirasvit extension to Magento is the issue.
This forum is for Core Magento issues, you will need to contact mirasvit for resolution.

**Comment by engcom-November** [comment]
Hello @guillaumerentabilisense,
As mentioned here https://github.com/magento/magento2/issues/38456#issuecomment-1954225685, this is a mirasvit extension issue and not magento core.
Hence closing this issue.

Thank you.
