### ISSUE TITLE
Error after installing security patch update 2.4.6-p4

### ISSUE THREAD

**Issue by RobertSokolovSW** [magento/magento2#38459]
### Preconditions and environment

- Magento version 2.4.6 Enterprise Edition

### Steps to reproduce

1. Install Magento 2.4.6-p4 using composer command `composer require-commerce magento/product-enterprise-edition:2.4.6-p4 -W`
2. Run `bin/magento setup:db:status` or `bin/magento setup:upgrade`

### Expected result

No error is shown

### Actual result

`In AbstractFactory.php line 264:`
                                                                                                                     
  `Missing required argument $environments of Magento\AdobeIoEventsClient\Model\Config\Env\EnvironmentConfigFactory.`  
                                                                                                                     

### Additional information

![Screenshot_71](https://github.com/magento/magento2/assets/111280085/8e87a500-4e93-4dc3-be64-3c09f7612f0a)
![Screenshot_69](https://github.com/magento/magento2/assets/111280085/dd1d0458-7149-4307-9907-30a9f04fd056)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @RobertSokolovSW,

Thank you for the report and collaboration!

We tried to verify this issue while upgrading from 2.4.6 to 2.4.6-p4, but in our case it's not reproducible.

Please take a look at the screenshot below:
<img width="851" alt="image" src="https://github.com/magento/magento2/assets/60198231/659560dd-dd54-4e84-b25e-228b051b90a1">
We did not get any issue while running `bin/magento setup:db:status` or `bin/magento setup:upgrade`.

Please let us know if we are missing anything.

Thank you.

**Comment by RobertSokolovSW** [comment]
Hello @engcom-November 

I am experiencing this error on a clean Magento installation. And this error also breaks the deployment pipeline on our test instance. Which means it is not something related to my machine.

I will provide you with anything you would require for reproducing this issue on your end. Right now, I don't know the reason why you can't reproduce it, but the error came with the security patch update for us.

Thank you.

**Comment by engcom-November** [comment]
Hello @RobertSokolovSW,

Could you please check if any third party module is causing this issue or is it a core issue, and give us exact steps to reproduce if applicable.

Thank you.

**Comment by RobertSokolovSW** [comment]
Hello @engcom-November 

The issue was caused by cache and was resolved by disabling Magento cache and re-enabling it afterwards.
