### ISSUE TITLE
[Performance] Linked products section loads all the collection

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38454]
### Preconditions and environment

- Magento version 2.4.6-p3

### Steps to reproduce

1. Go to the admin panel.
2. Open catalog -> products section.
3. Choose one of the product having a lot of linked children (e. g Related/Up-sells/Cross-sells).
4. Go to edit page of that product.

### Expected result

Page loads quickly.

### Actual result

Page loads for a long time.

### Additional information

This issue is same as https://github.com/magento/magento2/issues/21010.

@magento-engcom-team commented : 
```
Thank you for your report and collaboration!

The related internal Jira ticket MC-24145 was closed as Fixed.

The fix will be available with the upcoming 2.4.3 release.
```

However, It seems the fix never arrived on main branch : 
https://github.com/magento/magento2/blob/3428ebc3802a26fae9be542163579cefaa7967fa/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Related.php#L218-L224

![Capture d’écran 2024-02-19 à 15 30 22](https://github.com/magento/magento2/assets/1633463/0df23de4-3db2-45d4-a50d-3d892c90c7e2)

Can you check what happened with MC-24145 ?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Verified the issue in magento 2.4 dev instance but the issue is not reproducible.

Steps to reproduce
Go to the admin panel.
Open catalog -> products section.
Choose one of the product having a lot of linked children (e. g Related/Up-sells/Cross-sells).
Go to edit page of that product.

The page is loading quickly.

Please refer the attached video recording. let us know if we missed anything inorder to reproduce this issue.

https://github.com/magento/magento2/assets/60198592/a3778c0e-7f27-427d-95b9-474ad732e985

**Comment by Nuranto** [comment]
Maybe it's related with some third-party extensions. We ended up removing the whole link fieldset, since we do not populate them manually, and got our product page faster, so we do have the issue.

I let other users reopen an issue if they do reproduce this.
