### ISSUE TITLE
Table sales_order field store_name has 32 bytes

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#3846]
## Steps to reproduce
1. Install Magento from `develop` or `master` branch.
2. Open data base. Table sales_order. 
## Expected result
1. Field store_name should have type varchar 128 or 256 bytes or more.
## Actual result
1. Field store_name has 32 bytes. It's not enough. For example, 'Main Website\nMain Website Store\n' has 32 chapters and 'Default Store View' did not save.

**Comment by NadiyaS** [comment]
Hi @OleksiyOleksiyovych,

thanks for reporting this issue. 
Internal ticket was created MAGETWO-50717.

**Comment by magento-engcom-team** [comment]
@OleksiyOleksiyovych, thank you for your report.
We've created internal ticket(s) MAGETWO-50717 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@OleksiyOleksiyovych, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by engcom-tester** [comment]
Hello @OleksiyOleksiyovych 

Based on https://github.com/magento/magento2/pull/20204#issuecomment-500045327
The issue was fixed in commit https://github.com/magento/magento2/commit/eecedddf13acf2c59978a6817b86b7a7fe045880
