### ISSUE TITLE
Integration failing after upgrade to new version. 

### ISSUE THREAD

**Issue by daviskevinp** [magento/magento2#38467]
### Summary

I have inherited an ecommerce solution from a client. This solution involves a custom integration between Documoto and Magento. In documoto, the user has a cart and clicks checkout, kicking off a custom flow on the Documoto side to a custom Magento module. This flow was working prior to an upgrade last year to 2.4.6, but stopped working after the upgrade and no one has been able to get it working since.

The first call we make to magento is for log-in. This step logs the user in and creates a signed-in user token for the customer, which is passed back to Documoto. Documoto then sends that customer token as the bearer token on subsequent requests. The second call creates an empty cart for the customer. Except it's giving me an error message that completely masks details. "The quote could not be created". Everything I read suggests that it's failing an access check and that somehow the user is not authenticating correctly.

Clearly I don't understand something about how the authentication tokens are supposed to interact here. I have created an integration and tried passing the access token from the integration back to the client to be returned as the bearer token (checking the box to enable the access token to be used as a bearer token in the admin). No matter what I'm doing, I simply can't convince magento to let me createEmptyQuoteForCustomer.  The documentation on integration tokens is rather scarce, and amounts solely to "send the access token as the bearer token and check the checkbox and you should be good."

Those instructions are not working for me. Help!

This has cut off business orders for this entire system, and we need to get the customer back online again.

### Examples

If I knew how to replicate this issue or demonstrate it in any way, I'd know how to solve it. But this is an absolute crisis for the customer, and we need to get it fixed somehow.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @daviskevinp,

Thanks for the report and collaboration!

After reading the main description, it seems that you are using GraphQL for user authentication. Have you gone through with the mutation `generateCustomerToken`:

https://developer.adobe.com/commerce/webapi/graphql/schema/customer/mutations/generate-token/

After creating an access token, you need to pass that token with every request as a `Bearer Token`. 

Here in this board, we are handling the bugs with Magento core, you can post this query in [Magento StackExchange](https://magento.stackexchange.com/) for further things.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @daviskevinp,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
