### ISSUE TITLE
Paypal Paylater button not showing to merchant country UK with paypal express checkout

### ISSUE THREAD

**Issue by jaykgn** [magento/magento2#38479]
### Summary

in magento 2.4.5 while enabling merchant country to uk  paypal paylater is not showing.

### Examples

Enable paylater in admin configurations but button is not rendering for merchant country uk in frontend

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @jaykgn 

Thanks for reporting and collaboration.

Can you please provide steps to reproduce, expected and actual results with screenshots as that we will be able to reproduce the issue properly.

Thanks.

**Comment by marciomaciel** [comment]
@magento give me 2.4-develop instance

**Comment by jaykgn** [comment]
PreConditions:

To Show Paypal Paylater Or Paypal credit button Go To Admin > Configurations > Sales > Payment Methods > Enable Paypal paylater experience for Paypal Express Checkout, 
In Merchant Location Set Merchant Country To United States.

Button will show
https://prnt.sc/7sRdlee6NBxc

Steps To Reproduce:
Set Merchant Location From  Admin > Configurations > Sales > Payment Methods  To United Kingdom. 
https://prnt.sc/A_1Sd2y9RO5w

Paypal Credit and Paypal paylater will stop showing in frontend. account is eligible to show button on uk merchant country as well

Expected Result:
Paypal paylater button should show 

Actual Result:
Only Paypal Button will show

**Comment by jaykgn** [comment]
Hi @engcom-Dash ,
which version of 2.4.5 you have you used can you please confirm, so i can check on that ?

**Comment by engcom-Dash** [comment]
Hi @jaykgn 

We have tested the issue in the 2.4 latest dev instance. 

Please verify the issue in latest dev instance and let us know if you are still facing the issue.

<img width="1440" alt="Screenshot 2024-03-11 at 2 12 33 PM" src="https://github.com/magento/magento2/assets/60198592/911fc599-2a8d-4c3f-8014-edd2401f05e0">

Thanks.

**Comment by engcom-Dash** [comment]
Hi @jaykgn ,

We have noticed that this issue has not been updated for time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
