### ISSUE TITLE
Chinese letter appears instead of English

### ISSUE THREAD

**Issue by LGEHelena** [magento/magento2#38472]
### Preconditions and environment

- Magento version: Magento ver. 2.3.7-p4
- Anything else that would help a developer reproduce the bug 
![image](https://github.com/magento/magento2/assets/161347121/854169bc-3fa3-4b58-a375-bbdf7ee37f4c)
![err](https://github.com/magento/magento2/assets/161347121/0eef93b2-297d-4cff-92ed-94c6ed617660)

### Steps to reproduce

1. Change the menu title from Chinese to English

### Expected result

To identify the menu name correctly

### Actual result

At the moment, there is Chinese letter showing up instead of English. I am not using automatic page translator on my browser, and I have never changed it from English to Chinese. I guess this is a bug. Therefore, I would appreciate if you could solve this. This hasn't happened before

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @LGEHelena,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.We are able to identify the menu name correctly.

Kindly check the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.
