### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by gammyduck** [magento/magento2#3849]
I want to import a large CSV but it keeps getting caught on line 202. I isolated the line and still can't import it. 
![5fa0a1039d85c7c05e9e6c68b668bcf1](https://cloud.githubusercontent.com/assets/3619746/13915186/01ae51f0-ef4b-11e5-9375-ab413aa50b05.png)

Also while testing the single line I got a different error when changing the multiple field 
![65353268886c86a7c66b3af3a0ba9afc](https://cloud.githubusercontent.com/assets/3619746/13915182/f8445768-ef4a-11e5-9e32-c0fa3e0e3b0c.png)

I also dont understand also why there isn't a feature to skip headers or merge via CSV like importers for ecommerce sites

**Comment by piotrekkaminski** [comment]
@gammyduck can you provide the file you used for import?
@ilol can you look into it?

**Comment by veloraven** [comment]
@gammyduck thank you for your feedback.
Is this issue still actual?
If it is not, please close it.
If it is, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
Please also provide the line you have problems with.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
