### ISSUE TITLE
Fedex REST API for Shipping Methods on Magento 2.4.6 store not working

### ISSUE THREAD

**Issue by sithachitti** [magento/magento2#38507]
### Preconditions and environment

- Magento version - 2.4.6
- Anything else that would help a developer reproduce the bug - Configure Fedex Rest API using https://apis.fedex.com

### Steps to reproduce

1.Navigate to Magento Store ->Sales->Delivery Methods -> Fedex . Use https://apis.fedex.com under "Web-Services URL (Production)"

### Expected result

Fedex shipping methods must be listed down at checkout

### Actual result

Error:
This shipping method is currently unavailable. If you would like to ship using this shipping method, please contact us.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @sithachitti 
Thank you or your collaboration
The original module installed with Magento 2.4.6 doesn't support Fedex REST API.
To make your module compatible with Fedex REST API you need to apply patch provided by Adobe.
Please check [this link](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/fedex-shipping-method-integration-migration-soap-restful-api.html?lang=en)

**Comment by andrewbess** [comment]
Hello @engcom-Dash 
Please check my comment above

**Comment by sithachitti** [comment]
Thank you @andrewbess! This really helps. Let me work with the operations team to update the Magento version on the store.  We dont need any other plugins, correct? Also after upgrading, should we update the magento configuration to use the apis.fedex.com as the endpoint? Do we need to generate a separate meter number?  As of now the config points to Production URL:
[https://ws.fedex.com:443/web-services](https://ws.fedex.com/web-services)

**Comment by engcom-Dash** [comment]
Hi @sithachitti 

Thanks for reporting and collaboration.

As per the above comments , a patch has been provided. 

So, we are closing this issue.

If you are still facing the issue please feel free to reopen the issue again.
 
Thanks.

**Comment by verzmanoj** [comment]
> Hello @sithachitti Thank you or your collaboration The original module installed with Magento 2.4.6 doesn't support Fedex REST API. It looks like the compatible module will deliver inn Magento 2.4.7 To make your previous version of the module compatible with Fedex REST API you need to apply patch provided by Adobe. Please check [this link](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/fedex-shipping-method-integration-migration-soap-restful-api.html?lang=en)

> how to apply patch for Magento 2.3.4 ?

**Comment by tridentfly** [comment]
@sithachitti are you able to get correct negotiated rates from the updated API?
