### ISSUE TITLE
Magento trying to modify read-only property in __wakeup method of LoggerProxy

### ISSUE THREAD

**Issue by Bashev** [magento/magento2#38526]
### Summary

- Magento version 2.47-p3 change Monolog to LoggerProxy https://github.com/magento/magento2/commit/28d2a5bf4bd3588dfe6f0d3d0fc2036c6fcc9ef7 as a result we have new LoggerProxy class which have simple construct and properties which are using ObjectManager ...

### Examples

In the __wakeup method part of LoggerProxy objectManager trying to reassign value of the property https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/lib/internal/Magento/Framework/Logger/LoggerProxy.php#L69 

but the property is defined as read-only few lines above
https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/lib/internal/Magento/Framework/Logger/LoggerProxy.php#L26

### Proposed solution

Remove "read-only" from line 26

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @Bashev,

Thank you for the report and collaboration!

Verified this issue on 2.4-develop.
`$objectManager` variable is readonly, but `__wakeup` method is reassigning the value of `$this->objectManager`.
Hence this issue can be confirmed.

Thank you.

**Comment by kanevbg** [comment]
@Bashev Поздравления за хващането на този проблем колега!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11651 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11651&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
