### ISSUE TITLE
Bug with printing packing slips within orderpage

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3852]
## Steps to reproduce
1. Open an order
2. Go to shipments
3. Print one shipment
## Expected result
1. One shipment (only from the order) is printed
## Actual result
1. All packing slips are printed

**Comment by NadiyaS** [comment]
Hi @MichielTG,
thank you for reporting this issue.
It is already being tracked by MAGETWO-50718 internal ticket.
This issue will be closed as duplicate of #3807.
