### ISSUE TITLE
product cache issue

### ISSUE THREAD

**Issue by abhiramalli** [magento/magento2#38532]
### Preconditions and environment

2.4,.6 magento version
rabbitmq consumer to consume incoming product data from external system

### Steps to reproduce

create product  from consuming 
data from external system vai rabbitmq consumer
once product is create add images to same product in magento admin
again try to update product from the external system 
images are deleting
it is because consuming command instance is not getting the fresh product  instance which is edited from the admin
when again external system try to update product , already cached product from the previous call of rabbitmq is returned , not the  product instance which is edited from admin

i figured out its because of class  level cache

as queue consumer is running it will not get to know the about  product modifcation from admin

if stop and restart consumer command it will work fine

### Expected result

updated product  instance should be availble for consumer command

### Actual result

latest product modified is not availble for already running queue consumer

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
It sounds like your consumer isn't using a Factory to get the latest product data from the database before modifying the object? See https://magento.stackexchange.com/a/158098

If you do use a Factory and still have this issue, you'll have to post some code here to showcase the bug.

**Comment by engcom-Dash** [comment]
Hi @abhiramalli 

Thanks for reporting and collaboration.

Can you please more information on the preconditions - rabbitmq consumer to consume incoming product data from external system. 

Thanks.

**Comment by devchris79** [comment]
@engcom-Dash I take it you didn't mean to add the reproduced issue label...

**Comment by abhiramalli** [comment]
@hostep  I am using factories to to fetch product

**Comment by abhiramalli** [comment]
@engcom-Dash 
I have created queue known as product import quaue in rabbitmq
My external system is adding  product data in json form 
And i have built custom module to consume and create product and i also added eav attribute I'm product entity add unique id for product so that my external systems product id is matched to it, 
While updating I am checking that already product  with external system product id exists or not if exist I am fetching product from it using factory

**Comment by abhiramalli** [comment]
and one more case
when i create product from external system using consumer and custom logic
and delete same product from magento admin
again try to push the same data from the external system , magento says product doesnot exists instead of creating new product

after debuging i found

![image](https://github.com/magento/magento2/assets/85212799/8939c402-7eda-4cb7-b13f-5da53d75f57b)
 issue is becacuse when i send same data in the above code it checkes id present or not,
 if id not present it will take sku and try to fetch from get(sku) method
 when it uses get(sku) method it is returning my old product   from cache which is present before deleting ,
 my consumer instance is not getting to know  product is deleted from admin and also class level cache is not vanishing or removing(that is $this->instance[cacheKey]

**Comment by abhiramalli** [comment]
@engcom-Dash
any updates

**Comment by ananth-iyer** [comment]
@abhiramalli you can use custom attribute to save product from external system.
For example, external_product_id.
To update products from external system, match the SKU from Magento 2.

**Comment by engcom-Hotel** [comment]
Hello @abhiramalli,

I agree with @ananth-iyer here, please use the custom attribute to save the product from the external system.

And also if you are getting the same issue while updating the product even if you are using `ProductInterfaceFactory` then can you please provide us some codebase samples and screenshots to understand the issue more?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @abhiramalli,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
