### ISSUE TITLE
Do you have the rateLimit to access the REST APIs

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38534]
### Summary

Greetings Team Magneto,

We're Webgility and integrated the Magento2 APIs to streamline the process of downloading essential data such as Orders, Products, and more.

In order to ensure smooth operation and adherence to API usage policies, we would like to inquire about the existence of any rate limits associated with API calls. Additionally, could you kindly provide us with the key name in the response header that allows us to check the rate limit?

Your assistance in this matter would be greatly appreciated.

Best regards,
Webgility 

### Examples

mentioned in the summary

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @webgility-amazonapi,

Thanks for your reporting and Collaboration.

We are using this board to address the bugs you are facing in the Magento core library. But it doesn’t seem the same for us.
Please go through with this doc https://developer.adobe.com/commerce/webapi/rest/


We are Closing this issue.

Thanks.
