### ISSUE TITLE
Total qty

### ISSUE THREAD

**Issue by valentinazhuk** [magento/magento2#3853]
class Magento\Quote\Model\Quote\TotalsCollector

In the end function collectAddressTotals

```
 foreach ($this->collectorList->getCollectors($quote->getStoreId()) as $collector) {
            $collector->collect($quote, $shippingAssignment, $total);
  }
.....

$address->addData($total->getData());
```

Before line
 `$address->addData($total->getData())`
$address->getTotalQty() return qty but after this return 0

It seems problem here

class Magento\Quote\Model\Quote\Address\Total\Subtotal

function collect

```
parent::collect($quote, $shippingAssignment, $total);

$total->setTotalQty(0);

$baseVirtualAmount = $virtualAmount = 0;

 $address = $shippingAssignment->getShipping()->getAddress();
```

I think $total need to change $address:

```
$baseVirtualAmount = $virtualAmount = 0;

$address = $shippingAssignment->getShipping()->getAddress();
$address->setTotalQty(0);
```

**Comment by ishakhsuvarov** [comment]
@valentinazhuk Thank you for reporting this issue. We have created an internal ticket `MAGETWO-51545` to investigate and fix the problem.

**Comment by piotrekkaminski** [comment]
The issue is currently in QA and should be delivered shortly.

**Comment by veloraven** [comment]
This issue has been already fixed.
Closed.

**Comment by korostii** [comment]
Hi @veloraven,
The commits referencing this issue seem to be present on the `develop` branch only.
Can you please point out the version in which this fix was released?
