### ISSUE TITLE
Redirect loop when URL have uppercase

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#38538]
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Run: php bin/magento con:set web/secure/base_url https://Magento2.test/ ( or change Secure Base URL value in admin)
1. Clean cache: php bin/magento cache:clean
1. Go to homepage

### Expected result

URL should convert to lowercase

### Actual result

Redirect loop
!https://github.com/magento/magento2/assets/78783748/90e91b39-6f89-49c3-99c5-a2d2ebba718c!

### Additional information

*No response*

### Release note

*No response*

### Triage and priority

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @rogerdz 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance and the issue is not reproducable.

Steps to reproduce:

1.Run: php bin/magento con:set web/secure/base_url https://magento2.test/ ( or change Secure Base URL value in admin)
2.Clean cache: php bin/magento cache:clean
3.Go to homepage

The URL is converted to lower case.

Please check the attached screen recording and let us know if we missed anything.

https://github.com/magento/magento2/assets/60198592/11b0307e-8517-4725-b9ed-801c8e7bcd6f

**Comment by rogerdz** [comment]
@magento give me 2.4-develop instance

**Comment by rogerdz** [comment]
> Hi @rogerdz, here is your Magento Instance: https://8f2d1bd3711c2d5ff39fdba38952ed3a.instances-prod.magento-community.engineering Admin access: https://8f2d1bd3711c2d5ff39fdba38952ed3a.instances-prod.magento-community.engineering/admin_110a Login: 7230be49 Password: e96e38aa6564

Hi @engcom-Dash , I still duplicate in demo instance, changed url to https://8f2d1bd3711c2d5ff39fdba38952ed3a.instances-PROD.magento-community.engineering => redirect loop 
![image](https://github.com/magento/magento2/assets/78783748/cdda5c18-d313-406e-a702-245c5b2c0db7)
![image](https://github.com/magento/magento2/assets/78783748/70205589-32f2-4bb7-ab74-9d162828b8ba)

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance
