### ISSUE TITLE
FedEx RESTful APIs

### ISSUE THREAD

**Issue by verzmanoj** [magento/magento2#38541]
### Preconditions and environment

- Magento version : Magento ver. 2.3.4

### Steps to reproduce

Getting email from FedEx

Please be reminded that on and from 15 May 2024 our support for your connection with FedEx Web Services will end and be replaced by the new FedEx RESTful APIs. Our technical team will no longer be available to support FedEx Web Services from that day forward.

### Expected result

Let me know how update it , or available patch for it ?FedEx RESTful APIs simplify system integration, improve security, and elevate the customer experience. We are developing additional features, and all new enhancements will only be available in FedEx RESTful APIs. Get ready to serve your customers with greater ease, flexibility, and agility by upgrading your system now!

### Actual result

Let me know how update it , or available patch for it ?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @verzmanoj 

We are handling only core magento issues here. Please post this on Magento stack exchange for more help.

You can use this link [https://magento.stackexchange.com](https://magento.stackexchange.com/) for magneto stack exchange.

Hope your queries will be resolved. We are closing this ticket as its not a core magento issue.

Thanks.
