### ISSUE TITLE
Issue while placing order for Virtual Gift card in Magento Enterprise edition

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#3854]
Steps to reproduce
1.Place an order for virtual gift card from magento frontend

Expected result
Order should get placed successfully for gift card

Actual result
Page loops between Shopping cart page and Payment page
NOTE: This issue occurs for the following setting under stores>configuration>sales>giftcards
Generate Gift Card Account when Order Item is: Ordered

Repeat the steps for the following settings:
Generate Gift Card Account when Order Item is: Invoiced

Expected:
Gift card code must be generated on invoicing the order

Actual:
Error occurs on invoicing the order

NOTE: Gift card order works fine for physical card for both of the settings - ordered and invoiced

Logs attached

[virtual gift card order.txt](https://github.com/magento/magento2/files/182146/virtual.gift.card.order.txt)

**Comment by Deepthi57** [comment]
Hi, I have update Magento EE to 2.0.7 version and issue still persists. Page remains in cart even after cliking on Proceed to checkout. Kindly requesting for an update on this issue.

**Comment by piotrekkaminski** [comment]
Please raise this issue through Magento Support.

**Comment by dthampy** [comment]
@Deepthi57 An internal Jira Ticket has been created for this issue ->MAGETWO-55502 for the first part of the  issue.
However, I couldn't reproduce the issue where an error is thrown on invoicing the order.
Can you attach the screenshot of the error you were getting for the second part of this issue?

**Comment by centerax** [comment]
any feedback on this guys? still happening v2.1.2.

**Comment by maksek** [comment]
Hi @centerax, we have the issue logged into our JIRA, and it is confirmed. If you have enterprise client account - please raise the issue with enterprise support, so the issue will be expedited. At the moment it is not prioritized yet for upcoming patch releases.

**Comment by centerax** [comment]
thanks @maksek

**Comment by magento-engcom-team** [comment]
@Deepthi57  thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
