### ISSUE TITLE
Can I disable all GraphQl related modules?

### ISSUE THREAD

**Issue by cptX** [magento/magento2#38562]
### Summary

In order to make my magento 2.4.6 installation lighter I'm checking which modules are unnecessary for my usage, and I thought that all GraphQl maybe are.
I'm using a custom Luma theme and if I have understood correctly GraphQl modules are for GraphQl enabled themes...
Can somebody tell me if this is correct and what implications there will be if the GraphQl modules are disabled?

### Examples

Example modules considering to disable:
Magento_GraphQl
Magento_CmsGraphQl
Magento_EavGraphQl
Magento_CatalogRuleGraphQl
Magento_StoreGraphQl
Magento_CheckoutAgreementsGraphQl
Magento_CatalogGraphQl
Magento_CmsUrlRewriteGraphQl
Magento_CompareListGraphQl
Magento_QuoteGraphQl
Magento_CustomerGraphQl
Magento_DirectoryGraphQl
Magento_DownloadableGraphQl
Magento_CustomerDownloadableGraphQl
Magento_CatalogCustomerGraphQl
Magento_GiftMessageGraphQl
Magento_BundleGraphQl
Magento_GroupedProductGraphQl
Magento_ConfigurableProductGraphQl
Magento_InventoryInStorePickupGraphQl
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryQuoteGraphQl
Magento_CatalogInventoryGraphQl
Magento_LoginAsCustomerGraphQl
Magento_NewsletterGraphQl
Magento_GraphQlCache
Magento_PaymentGraphQl
Magento_PaypalGraphQl
Magento_ReCaptchaWebapiGraphQl
Magento_RelatedProductGraphQl
Magento_ReviewGraphQl
Magento_SalesGraphQl
Magento_UrlRewriteGraphQl
Magento_SendFriendGraphQl
Magento_InventoryGraphQl
Magento_CatalogCmsGraphQl
Magento_SwatchesGraphQl
Magento_TaxGraphQl
Magento_ThemeGraphQl
Magento_CatalogUrlRewriteGraphQl
Magento_VaultGraphQl
Magento_WishlistGraphQl
Magento_WeeeGraphQl
PayPal_BraintreeGraphQl
Smile_ElasticsuiteCatalogGraphQl

If my assumption is correct then disabling so many modules will have a very positive impact in magento!

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @cptX 
Thank you for your contribution. 
But I am sure it should not be a new issue.
I close it.

**Comment by cptX** [comment]
Where can I ask this question? I need an answer on this, please!

**Comment by andrewbess** [comment]
> Where can I ask this question? I need an answer on this, please!

Hello @cptX 
I answered for you in the Magento Slack.

**Comment by andrewbess** [comment]
> Where can I ask this question? I need an answer on this, please!

Sorry, I am sure, the questions like a:
 - 3rd-party module does not work
 - My module does not work
 - Please help me to fix my project
should not be in the platform github.

I think only bug reports, feature requests, security vulnerability reports should be here as issues.
