### ISSUE TITLE
Varnish didn't make any difference! Is it useless in 2.4.6?

### ISSUE THREAD

**Issue by cptX** [magento/magento2#38561]
### Summary

I have a server with Ubuntu 22.04, nginx, and magento 2.4.6.
The load on magento is really low, like 60 visits per day, but I wanted to make the loading times faster.
So I decided to install and use Varnish in Magento.
After configuring it I saw that only the main document (html) of every page was a hit and no other file.
Then in my vcl in the "# Static files caching" block I commented the "return (pass)" and uncommented the next three lines to check if I gain anything when caching all files! And I saw slower result.
At this point I want to say that because varnish cannot support https I have nginx in front for both http and https, and varnish on the back of nginx to provide the cached content. Nginx is really fast in providing files so caching all stuff in varnish didn't make any difference.
So I remained with the question why is all over the place recommended to use Varnish to speedup Magento, if it actually caches only the main html document of every page? What is the point of all this complexity and the problems it produces with the non-refreshed content? Am I doing something wrong? In a hit what should it have cached? What differences do you see when using Varnish? How do you handle the https issue?

### Examples

By having
```
    # Static files caching
    if (req.url ~ "^/(pub/)?(media|static)/") {
        # Static files should not be cached by default
        return (pass);

        # But if you use a few locales and don't use CDN you can enable caching static files by commenting previous line (#return (pass);) and uncommenting next 3 lines
        #unset req.http.Https;
        #unset req.http.X-Forwarded-Proto;
        #unset req.http.Cookie;
    }
```
only the main html file of every page is a hit!

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cptX** [comment]
Hi @engcom-Hotel ,
thanks for researching the subject. I don't speak about a specific page. I made tests for home page, then for a product with a lot of images and then for a category page with a lot of products. In all cases the time difference was really insignificant.
It is **very important** that as Varnish doesn't have https support you should have it behind your server not in front, otherwise the results will be different. This also is important in my report here because we cannot say that Varnish is faster if it will never be used in front of the server. Let's be realistic, today https is a necessity, so the server should be in front of Varnish to implement the encryption. So tests should be done with Varnish on the back.
In the example you are presenting here do you have Varnish listening on port 80 directly?
Also as you see in your result in the built-in cache the DOM loading took less time than with Varnish.
Finally, can you please check which files are a hit from Varnish? In my case only the main html document of the page was hit, all the rest items of the page were not.
Important is also to know what server are you using, apache or nginx? Because nginx is really fast in providing files so, it is actually faster than varnish in providing static files, so there is no need to put varnish in-between for static files.

**Comment by JonSau** [comment]
Hi @cptX 

In terms of TLS termination, we use Hitch (listening on Port 443), Varnish (Port 80) and NGINX sits behind that.
Simple to setup and Hitch is very lightweight - See: 
https://www.varnish-software.com/developers/tutorials/terminate-tls-varnish-hitch/

**Comment by cptX** [comment]
@JonSau my main target was to make the page loading faster. My server doesn't have any load so removing load from the server was not the intention. I didn't notice any difference. Installing an extra application like Hitch looks overkill to me as you can do the same thing with existing nginx in front (for TLS), varnish in the middle and nginx on the back. I'm very curious to tell me if you saw significant difference on the page loading times, not the load on the server. Also which parts is your varnish serving? Is it also serving static files?

**Comment by engcom-Hotel** [comment]
Hello @cptX,


> In the example you are presenting here do you have Varnish listening on port 80 directly?

Yes the varnish is listening on Port 80 and the Magento instance is server from port 8088

> Finally, can you please check which files are a hit from Varnish? In my case only the main html document of the page was hit, all the rest items of the page were not.

We have checked in the latest development branch ie 2.4-develop and all the pages like homepage, category page etc are HIT

> Important is also to know what server are you using, apache or nginx?

We are using Apache

**Comment by cptX** [comment]
So if your varnish is listening on port 80 is not a realistic scenario. Today all sites need to have TLS in front which of course adds some delays.
When talking about hit, I think you didn't understand my point. I'm not talking about what pages are hit, but what parts of every page is hit. For example in my tests only the actual html of the page was a hit but no other resource was (no css, no js, no fonts etc...)
Apache is slow so maybe varnish makes a difference even for static files. Nginx is very fast on delivering static files. I didn't see any differences when delivering the resources from Varnish instead of nginx. Maybe varnish was a bit slower as it was behind nginx...

**Comment by engcom-Hotel** [comment]
Hello @cptX,

> When talking about hit, I think you didn't understand my point. I'm not talking about what pages are hit, but what parts of every page is hit. For example in my tests only the actual html of the page was a hit but no other resource was (no css, no js, no fonts etc...)

Regarding the above comment, we request you to please go through with this [documentation](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cache/varnish/config-varnish#second-browser-request), according to this while sending the same browser requests the same page again, the assets are delivered from the local browser cache, as the following figure shows:

![image](https://github.com/magento/magento2/assets/51681618/aa6e1a62-e76f-4ed0-9768-36706c7938a2)

So it seems it is working as expected.

According to the same above link, there are some known issues while configuring Varnish as follows:

- Varnish does not support SSL: As an alternative, use SSL termination or an SSL termination proxy.

So it seems it is working as expected. Let us know if we missed anything.

Thanks

**Comment by cptX** [comment]
@engcom-Hotel sorry to say that but looks like you don't have much experience with varnish and caching systems. When you do varnish tests you need to have all caches DISABLED, otherwise your tests are useless!

![image](https://github.com/magento/magento2/assets/9040042/68471eeb-6d7e-4cd0-af0b-250f6e369fef)

Let's please wait for the opinion of other technical people who understand how varnish should work and how a real server is setup nowadays (TLS in front of Varnish etc...). In order for Magento documentation and implementation to be valid and useful it should take into account real world scenarios. Expecting to have varnish in front of the server nowadays is not valid as all sites should now have https (TLS).
Also, as I mentioned in previous posts having a "HIT" only for one item of a page is again very insignificant difference. Varnish should serve from its cache more items, not only 1 html per page...
Let's hope other people will come into our discussion that understand better.

**Comment by engcom-Hotel** [comment]
Dear @cptX,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
