### ISSUE TITLE
When I need copy something from grid it redirects 

### ISSUE THREAD

**Issue by Genaker** [magento/magento2#38571]
https://github.com/magento/magento2/blob/488c103401f7b04bfea0a339d25107ada11bd2da/app/code/Magento/Ui/view/base/web/js/grid/columns/actions.js#L277

Before this code, please add 
  ```              window.location.href = action.href;```
this code :
```
if (document.getSelection().type === 'Range') action.stopPropagation(); 
```
if something is selected, don't redirect and other click actions. Thanks! 

Update: also, when the redirect happens, you can't see this. MAgento 2 is so slow you need add preloader to indicate that something happening;
there is the code
```
jQuery('body').loader('show');
```

So the code must be like this

```
if (document.getSelection().type === 'Range') action.stopPropagation(); 
jQuery('body').loader('show');
window.location.href = action.href;
```

**Comment by engcom-Hotel** [comment]
Hello @Genaker,

Thanks for the report and collaboration! Please provide us more information on this issue, like on which page and action you are facing this issue, also the below points are important to mention for further processing on this issue:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Genaker,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
