### ISSUE TITLE
Customer validation ignores Backend validation

### ISSUE THREAD

**Issue by yariksheptykin** [magento/magento2#3857]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. In the database set any of the EAV-attributes for the customer to be unique. (In my case I do it in a `InstallData.php` script)
3. Now create two customers with the same value for this unique attribute in Magento Backend.
## Expected result
1. While creating the second customer with the save value for the unique attribute an error should be shown.
## Actual result
1. You will succeed creating the second customer despite the unique constraint.

I believe that this is related to a missing backend validator in [Customer/etc/validation.xml](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/etc/validation.xml#L13).
Unique validation is carried out in [AbstractBackend](https://github.com/magento/magento2/blob/develop/app/code/Magento/Eav/Model/Entity/Attribute/Backend/AbstractBackend.php#L247-L252). This validation however never gets to be executed while saving a customer. Adding the following to the `validation.xml` fixes the problem:

``` xml
<constraint alias="eav_data_validator" class="Magento\Eav\Model\Validator\Attribute\Backend" />
```

**Comment by veloraven** [comment]
@yariksheptykin thank you for your feedback.
Is this issue still actual?
If it is please specify Magento version.
If it is not please close the issue.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by yariksheptykin** [comment]
hi @veloraven ! Sorry, I could not find time to ensure this issue is reproducible in 2.1.x. This definitely was relevant in 2.0.x.
