### ISSUE TITLE
Multiple calls to getCountryInfo result in a fatal error

### ISSUE THREAD

**Issue by kristjan-h** [magento/magento2#3858]
## Steps to reproduce

Problem found during extension development.
Steps to reproduce on a very high level:
1. Use Magento 2.0.2 CE release version
2. Create a class and inject Magento\Directory\Api\CountryInformationAcquirerInterface to it
3. Create a method which uses getCountryInfo($countryId) two times with different $countryId value
## Expected result

Both calls return a country object with relevant information asked.
## Actual result

Fatal error
Uncaught Error: Call to undefined method Magento\Directory\Model\ResourceModel\Country::getCountryId()
## Background

This seems to be because initially when getCountryInfo is called, the collection gets loaded and cached into ivar with one single country object. When a second call is made, the collection is reused and the country object is not found, see Magento\Directory\Model\ResourceModel\Country\Collection::getItemById method. This results in getItemById method to create a Magento\Directory\Model\ResourceModel\Country instead, but this object is not compatible with the logic that uses it in CountryInformationAcquirer class (Magento\Directory\Model\Country is expected instead).

For me it does not make sense that getItemById returns a ResourceModel\Country object in case no Model/Country objects were not found.

Further more, CountryInformationAcquirerInterface:: getCountryInfo should always ensure data is actually asked from the DB.

**Comment by mazhalai** [comment]
@OnTapKristjan Thank you. We have created MAGETWO-51296 to investigate and fix.

**Comment by piotrekkaminski** [comment]
Issue fixed in develop branch.
