### ISSUE TITLE
Links Generation issue

### ISSUE THREAD

**Issue by amanpreetji** [magento/magento2#38581]
### Summary

We have an online store, created in the magento platform. 

In our collection of product pages, we using load more item buttons. But instead of using that option we have many pages indexed with p=2 options. 

My concern is why this happen, Please guide me as an SEO expert I am facing so many problem due to this.

### Examples

example.com/products.html?p=2

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @amanpreetji,

Thank you for the report and collaboration!

`?p=2` is appended at the end of the url for pagination, if you are using load more you must be using ajax to retrive the products implemented through a third party module, this module must be at fault.
Check whether if this module has any issue with it.

This forum is for posting bugs relating to core Magento, please post your queries on [Magento stackexchange](https://magento.stackexchange.com/).

Thank you.

**Comment by amanpreetji** [comment]
Thanks, I am getting in touch with developers for more clarification about
this. Meanwhile, you can share the positive things that can help avoid this
problem. if you have the best solution.

Once again, I am thankful to you for the help.

Amanpreet

**Comment by engcom-November** [comment]
Hello @amanpreetji,

We have noticed that this issue has not been updated for a long time. We believe your query has been resolved, hence closing this issue.
Feel free to reopen this issue or raise a fresh one if you need more assistance.

Thank you.
