### ISSUE TITLE
Invalid Date when account Local is not en-US

### ISSUE THREAD

**Issue by LCorentinL** [magento/magento2#38596]
### Preconditions and environment

- Magento versio 2.4.6-p4

### Steps to reproduce

1 - Navigate to admin
2 - Login
3 - Create a cart price rule
4 - Save account with local fr-FR

### Expected result

Cart price rule is save succefully

### Actual result

[2024-04-09T13:41:00.255619+00:00] .CRITICAL: Exception: Failed to parse time string (18/03/2024) at position 0 (1): Unexpected character in /home/vendor/magento/module-rule/Model/AbstractModel.php:400

### Additional information

Working when i put my local in en-US
It's affetcs the product also :
![image](https://github.com/magento/magento2/assets/141347050/c464dac7-7b28-40ff-a25c-d091f117c294)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by eBusinessAtlantique** [comment]
Same problem on my side, I spent a few hours to find a solution but noluck.
French local on my account too.

**Comment by eBusinessAtlantique** [comment]
@magento give me 2.4-develop instance

**Comment by eBusinessAtlantique** [comment]
Unfortunatly I can't replicate on develop instance.

But I have the same problem as @LCorentinL mentioned.

Every datepicker is writing wrong dates when user local is FRench.

**Comment by Bashev** [comment]
It's not only on French in any different format than English. Can you check your ICU version on the server?

**Comment by eBusinessAtlantique** [comment]
ICU ?

It's not only on French in any different format than English. Can you check

**Comment by LCorentinL** [comment]
It can be server settings or magento configuration because i checked my staging environment, and i have not the issue, i only have it on production

**Comment by LCorentinL** [comment]
@Bashev 

apt show libicu-dev 
-
-
Package: libicu-dev
Version: 67.1-7
Priority: optional
Section: libdevel
Source: icu
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Installed-Size: 45.3 MB
Depends: libicu67 (= 67.1-7), icu-devtools (>= 67.1-7), libc6-dev | libc-dev
Suggests: icu-doc
Breaks: icu-devtools (<< 67.1~rc-1~)
Replaces: icu-devtools (<< 67.1~rc-1~)
Homepage: http://www.icu-project.org
Tag: devel::lang:c, devel::lang:c++, devel::library, implemented-in::c,
 role::devel-lib
Download-Size: 9597 kB
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: Development files for International Components for Unicode
 ICU is a C++ and C library that provides robust and full-featured
 Unicode and locale support.  This package contains the development
 files for ICU.

it's the only reference about icu i could find on both of my server, and the version number is the same so maybe it's not that

**Comment by LCorentinL** [comment]
Do you think it can affect also the coupon report ?
I made a test with an order :
![image](https://github.com/magento/magento2/assets/141347050/9f9aeeff-ac93-4407-816f-f12f7e4d10a2)
and my report shows nothing :
![image](https://github.com/magento/magento2/assets/141347050/dd1b9616-4a2c-497c-9d78-f7a8a3f9cb1e)
I refresh both lifetime and statistics in admin and reindex

PS : when i click "show report" the datetime i enter with datepicker changes to US format : 
![image](https://github.com/magento/magento2/assets/141347050/8fea1575-d161-4860-a5aa-7d6bc851c2f0)
So i think it search from january 4th to november 11th (wrong date but in fact my coupon use is in this range so i dont understand)

**Comment by eBusinessAtlantique** [comment]
Some files removed in /lib/web/jquery when migrate to 2.4.6
My instance where I don't have the bug still have these old files as I did not remove them when I upgraded to 2.4.6. I pushed only the new files.
Is it a hint ?

**Comment by LCorentinL** [comment]
Yeah i nearly migrate to 2.4.6 from 2.4.2 , so i think it's a good hint.
Can you provide me the files you speaking about so i can check the difference between my instances on my side ?

**Comment by eBusinessAtlantique** [comment]
Compare with a tool like winmerge on your PC what is different between your linb/web folder and the one on the latest 2.4.6-p4.

**Comment by Bashev** [comment]
2.4.6-p4 also have the same issue.
2.4.6-p2 works as expected.

**Comment by eBusinessAtlantique** [comment]
> 2.4.6-p4 also have the same issue. 2.4.6-p2 works as expected.

Can you compare lib/web folders ?

**Comment by LCorentinL** [comment]
I have compare both of my lib/web and here is :
![image](https://github.com/magento/magento2/assets/141347050/311f9003-ff78-498f-8fe1-dbdc3a82de5f)

Looks perfectly the same

**Comment by Bashev** [comment]
Not from there, its generic backend issue.

@magento i am working on this

**Comment by JamesAllwood** [comment]
The issue appears to stem from an update from `"laminas/laminas-filter"`. Locking it to version `2.34.0` corrects it

**Comment by JamesAllwood** [comment]
@LCorentinL just add it in your composer.json as a required package and that will fix the version

```
"laminas/laminas-filter": "2.34.0"
```

**Comment by LCorentinL** [comment]
Ok thanks, it seems to working fine on my local instance, i'll deploy in production and update here.

**Comment by Bashev** [comment]
@JamesAllwood was right, issue comes from here:
https://github.com/laminas/laminas-filter/blob/f98ddcfe5b145d84ccfe3cddd95ba60d09231843/src/FilterChain.php#L90 

Magento method (in our case) Magento\Framework\Stdlib\DateTime\Filter\Date is not callable.

**Comment by hostep** [comment]
Upgrading `laminas/laminas-filter` to version [2.35.2](https://github.com/laminas/laminas-filter/releases/tag/2.35.2) should fix this problem.
If confirmed, this issue can be closed. Thanks everyone for all the info!

**Comment by timpea-splat** [comment]
laminas/laminas-filter 2.35.1, is also causing an "Invalid Date" error when saving a product that has an attribute with the type "Date", and the date is past the 12th day, eg. 25/03/2024 will give the error, 10/03/2024 saves fine.  It appears that "composer update" to bring laminas/laminas-filter to 2.35.2 fixes the issue.

**Comment by DegrizNet** [comment]
> Upgrading `laminas/laminas-filter` to version [2.35.2](https://github.com/laminas/laminas-filter/releases/tag/2.35.2) should fix this problem. If confirmed, this issue can be closed. Thanks everyone for all the info!

I can confirm that upgrade fixed the issues for me. Thank you!

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
It was already confirmed that the issue was fixed by updating `laminas/laminas-filterù  to the latest version, so we should close this issue, no?

**Comment by engcom-Delta** [comment]
Hi @LCorentinL ,

As per the latest comment https://github.com/magento/magento2/issues/38596#issuecomment-2049180025,  issue was fixed by updating laminas/laminas-filter to the latest version.So we are closing this issue.
Please feel free to reopen this if the issue still persists.

Thanks,
