### ISSUE TITLE
Introducing a "-latest" tag

### ISSUE THREAD

**Issue by utietze** [magento/magento2#38594]
### Summary

Currently, Magento 2 versions are tagged following a specific naming scheme, such as "2.4.5", "2.4.5-p1", "2.4.5-p2", etc., for each successive patch level. This scheme is consistent across other version lines like 2.4.4 and 2.4.6. While this method is logical for tracking version history, it creates an extra layer of complexity for developers and systems that rely on staying updated with the latest patch level. There is no straightforward way to automatically select the latest patch version of a specific Magento 2 version, necessitating manual updates and checks to ensure that the most latest version is in use.

1. **Automated Deployment Systems**: Deployment systems that automatically pull Magento versions for installation or updates have to be manually configured for each new patch release, increasing the risk of human error and the operational overhead.
2. **Dependency Management Tools**: Tools that manage dependencies and versions, such as Composer, cannot automatically update to the latest patch version without explicit instructions, potentially leaving systems running on less secure versions.
3. **Developer Experience**: Developers frequently checking for the latest patch version must navigate the release pages or repositories to find the most recent version, a process that is inefficient and error-prone.

### Examples

We built a system that checks how fast and efficiently our code runs every day. This helps us spot any problems early on. We also use an automated setup in GitLab to test our code in different ways to make sure it works well.

We ran into an issue when trying to run a specific test on Magento 2 Community Version "2.4.4" (no patch level) using PHP 7.4. The installation of the integration-test couldn't execute because it was missing a class called `Magento\Framework\ObjectManager\ResetAfterRequestInterface`, which was introduced in Magento 2.4.6. This class is used as part of the "magento/security-package", especially in the `magento/module-re-captcha-version-3-invisible`, and its absence broke the test setup. Interestingly, this class was also added in Magento "2.4.4-p6".

Having a "latest" tag for each Magento version in our setup would really help. It would make sure we always use the newest version of the code automatically, avoiding these kinds of issues and making our system work better.

### Proposed solution

Introduce a "-latest" tag for each minor version line of Magento 2, which would always point to the latest patch level of that version. For example, "2.4.5-latest" would automatically be updated to point to "2.4.5-p2" if that is the most recent patch level. This tag should be dynamically updated to reference the latest patch as new patches are released.

### Release note

It would likely be best if it also automatically connected to the latest "patch" level.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @utietze,

Thanks for the report and collaboration!

I agree with @hostep comment [here](https://github.com/magento/magento2/issues/38594#issuecomment-2045204234). Please let us know if you have any issue with this.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @utietze,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
