### ISSUE TITLE
PayPal’s Client-side only JavaScript SDK on or after 31 July 2024

### ISSUE THREAD

**Issue by olgaIskra** [magento/magento2#38591]
### Preconditions and environment

- Magento version : All
- **When will the module-paypal  be changed to meet PayPal's new requirements ? :**
- [Migration guide from Client-side only to Server-side JavaScript SDK](https://github.com/paypal-examples/paypal-sdk-server-side-integration/blob/main/docs/update-from-client-side-helpers-to-server-side.md)

### Steps to reproduce

module-paypal  : Client-side  JavaScript SDK

### Expected result

module-paypal : Server-side JavaScript SDK

### Actual result

When will the module-paypal  be changed to meet PayPal's new requirements ?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by olgaIskra** [comment]
My magento version is 2.4.5 (with vendor/magento/module-paypal : Client-side JavaScript SDK)

**Comment by olgaIskra** [comment]
Magento must integrate PayPal Checkout in another way prior to 31 July 2024.

**Comment by engcom-Hotel** [comment]
Hello @olgaIskra,

Thanks for the report and collaboration!

We need to discuss this with the PO hence moving this issue `On Hold` and sending mail to the PO for confirmation.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @olgaIskra,

Meanwhile can you please let us know for which PayPal module you are talking here and the official link for the same?

Thanks

**Comment by engcom-Hotel** [comment]
Dear <user>,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
