### ISSUE TITLE
Sales Reports are not generated

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#38590]
### Preconditions and environment

- Magento 2 version 2.4.6-p5
- Magento 2 system locale Dutch
- Magento 2 admin language english

### Steps to reproduce

Go to Sales order reports
Choose any date from and to
Click on show Report button.

### Expected result

Report should be generated

### Actual result

Report is not generated

### Additional information

In this screenshot is shown that if we use calendar we get no reports
![Scherm­afbeelding 2024-04-09 om 08 43 36](https://github.com/magento/magento2/assets/37579149/402c670f-e088-401a-870d-b388048991d0)

When we enter values manually like YYYY-m-d we get our reports
![Scherm­afbeelding 2024-04-09 om 08 44 56](https://github.com/magento/magento2/assets/37579149/fe7cb786-7bcd-40af-9aa6-7d976d83c484)

also after submitting the form the date is changed to formatted one:
![Scherm­afbeelding 2024-04-09 om 08 45 37](https://github.com/magento/magento2/assets/37579149/5dcfecaa-f85d-4a60-9756-897a798a49e1)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
Looks like related to this https://github.com/magento/magento2/issues/38596

**Comment by hostep** [comment]
Upgrading `laminas/laminas-filter` to version [2.35.2](https://github.com/laminas/laminas-filter/releases/tag/2.35.2) should fix this problem.
If confirmed, this issue can be closed. Thanks everyone for all the info!
