### ISSUE TITLE
Coupons "Times used"

### ISSUE THREAD

**Issue by marctbb** [magento/magento2#38599]
### Preconditions and environment

- Magento version 2.4.6-p3

I have a rule in the "Marketing->Cart Price Rules" section in which there are many codes created for that rule.
The problem I have detected is that when any code is used, in the "Manage Coupon Codes" section the "Times used" counter is not updated.
I checked if there was a problem of the plugin "Generate and Import Coupons from Amasty" but it dont' seem that is caused for that plugin. I tested with the Magento Blank theme to confirm that it is not a problem of my "theme" and it still didn't update. 
I would appreciate if there is some guidance on how to fix it.

### Steps to reproduce

To make it easier to understand how to reproduce it, I share a video. Basically I make a purchase with the code and the counter does not update.
https://www.dropbox.com/scl/fi/1z85aqhvhtb7nj0nu04d8/434220-consumers-2024-04-09_20.11.00.mkv?rlkey=r1qcmhauu2qk1l8m2433jvdta&dl=0

### Expected result

The expected result is that without having to run any cron, the "Times used" of the used code or coupon will be automatically updated.

### Actual result

The current result is that it does not automatically update the "Times used" of the code or coupon used.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Bashev** [comment]
I think is not good idea, to "attach" updating of coupons report data in two the order save. This will reflects negative to the speed, if we attaching everything to the checkout. 

Most of the time reports are checked after campaign ends, but not refreshing all the day. 

If you wants to have "real time" data you can adjust frequency (to every minute) of the this specific cronjob `Magento\SalesRule\Cron\AggregateSalesReportCouponsData`, in your own module, or from Amasty Cron Scheduler (i saw in the video you are using their extensions).

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by marctbb** [comment]
Hello, I attach the coupon configuration. I am performing the same steps I mentioned and that you have tried again and the "times used" still doesn't work.  Before opening a ticket to Magento, I opened a ticket to Amasty and they have tried to perform the same tests with the configuration and have been able to reproduce the error even disabling their modules, so we conclude that it is due to some problem in Magento.
![coupon](https://github.com/magento/magento2/assets/138032384/ef403631-d231-4ba8-9605-da0f8dc91bbe)
![coupon_config](https://github.com/magento/magento2/assets/138032384/05d7ce4c-db6c-45f2-b368-4dd1030cb1e5)

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @marctbb , 

Tried with multiple websites and also with new cart price rule. Still issue is not reproducible for us. After refreshing the screen the Times Used are updated.

<img width="1440" alt="Screenshot 2024-04-17 at 11 25 44 PM" src="https://github.com/magento/magento2/assets/51681379/581c04bd-e5f2-4ca9-9b1e-5d7a0a5bbe1d">

<img width="1432" alt="Screenshot 2024-04-17 at 11 26 09 PM" src="https://github.com/magento/magento2/assets/51681379/e1198735-d8e5-455b-b98d-cd1dc37252e7">

<img width="1440" alt="Screenshot 2024-04-17 at 11 28 32 PM" src="https://github.com/magento/magento2/assets/51681379/d1c6e7fc-a58a-4fa4-9dce-6d961d981811">


Let us know if you are using any more settings in magento while doing transactions.

**Comment by marctbb** [comment]
I tested the coupons' behaviour on a fresh Magento without third-party and Amasty modules. To test the case, I followed the next steps:

1. Created a new rule
2. Generated 5 coupons
3. The generation of coupons was scheduled
4. To generate them, the next command was executed: **php bin/magento queue:consumers:start codegeneratorProcessor**
5, Now the coupons exist with 0 value for the "Times Used" column
6. Placed a new order with one of these coupons
7. Flushed the Magento cache and checked the "Times Used" column. As you may see, it is still 0
8. Executed this command: **php bin/magento queue:consumers:start sales.rule.update.coupon.usage** and "Times Used" has been updated.

I checked the issue again found the next but report to Adobe: https://github.com/magento/magento2/issues/35077 where Magento developers confirm that you either need to have RabbitMQ configured or run the queue consumer (sales.rule.update.coupon.usage).

If you have any questions, please do not hesitate to ask. Thank you

![1](https://github.com/magento/magento2/assets/138032384/2e58b98d-63ab-4cdd-82e2-a563e157c4db)
![2](https://github.com/magento/magento2/assets/138032384/9431ef94-ece2-4377-9e8b-6d0088eb9838)
![3](https://github.com/magento/magento2/assets/138032384/5b7c3cc0-f2a4-48c2-84b3-b8a3e5748f2a)
![5](https://github.com/magento/magento2/assets/138032384/74e1bc0d-76ad-44e5-9883-e241eb3aef19)
![6](https://github.com/magento/magento2/assets/138032384/0d32bc1b-a82c-4874-9062-f6c37c2d5771)
![7](https://github.com/magento/magento2/assets/138032384/2cd35f6c-e886-4c88-aa91-d3d6073be417)
![8](https://github.com/magento/magento2/assets/138032384/ba177b32-e44a-45f4-b6c1-d87725f51f79)
![modules_enabled](https://github.com/magento/magento2/assets/138032384/bcc16685-4b7e-4415-afd1-ef80d1d14fb1)

**Comment by marctbb** [comment]
Hello,
I have found the source of the problem. It turns out that in my env.php file I had these lines added which blocked or prevented the execution of the consumers cron, it only executed the inidicated ones. So the solution is to remove this block and the coupon works correctly.
cron_consumers_runner' => [
        cron_run' => true,
        max_messages' => 2000,
        consumers' => [
            'product_action_attribute.update',
            'product_action_attribute.website.update',
            'exportProcessor',
            'codegeneratorProcessor'
        ]
    ],

Thanks for the support and help

**Comment by engcom-Delta** [comment]
Hi @marctbb ,

We are closing this issue as this is related to your specific instance.Please feel free to reopen if you face the issue again.

Thanks,
