### ISSUE TITLE
Magento2.4.6-p4 Order API Simple Item missing price

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#38603]
### Preconditions and environment

- Magento version: 2.4.6-p4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Create a configurable with simple item assigned. got to store front add the item to card proceed to checkout and place order.

Using your preferable tool for testing the API: 

GET URL: https://magento.com/rest/all/V1/orders/1

### Expected result

Item simple type to have price > 0 

### Actual result

Price at simple type is coming as 0
<img width="311" alt="Screenshot 2024-04-10 at 11 52 42" src="https://github.com/magento/magento2/assets/3495481/8deb4206-a00a-42c9-8e6a-95f4b783ebbd">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lano-vargas** [comment]
@magento give me 2.4-develop instance

**Comment by lano-vargas** [comment]
Reproduced on 2.4.x  on the given instance above.
<img width="826" alt="Screenshot 2024-04-10 at 12 42 10" src="https://github.com/magento/magento2/assets/3495481/15f811cb-d9ad-4204-8d2c-c2acb5af99c7">

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by digitalrisedorset** [comment]
I have looked into it, the problem seems to be on magento 2.4.5, an order item record did not store any simple product data in the order_item table. It seem develop branch stores some data for both the configurable and the simple and these simple data are faulty. I suggest a fix is to ensure the simple product is not saved on the order_items table again

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.

**Comment by engcom-Charlie** [comment]
Hi @lano-vargas,

Thank you for your contribution!

As mentioned [here](https://github.com/magento/magento2/issues/38603#issuecomment-2146772556), Internal team has analysed the issue on the stable versions 2.4.4-p9, 2.4.5-p8 and also on 2.4 develop, 2.4.6-p4 as per the suggestion by Product Owner(PO). 

The API response is same on all of the above mentioned versions, which is on placing an order using a configurable product with two attributes, we are observing that the resulting product list contains four items in API. Among these, two are original simple products displaying the actual price, while the other two are virtual products of the same type displaying price as 0. 
PFA screenshot for the reference.

This is default behaviour as per the generic code written for all the products in magento. PO has suggested for closing the ticket after the investigation, as it is not bug in this case.

Thank you!
![image-2024-06-10-15-43-43-390](https://github.com/magento/magento2/assets/51680850/29484044-52da-461c-9b3c-5c71bc2c3bf3)
![image-2024-06-10-15-43-06-295](https://github.com/magento/magento2/assets/51680850/7cef3564-5ed4-4cb5-93d9-4d53b6a87012)
![image-2024-06-10-15-45-25-999](https://github.com/magento/magento2/assets/51680850/bbeff576-45af-474a-b81f-d52fb720739a)
