### ISSUE TITLE
Directive values are not quote-escaped

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#3860]
This is still the case: http://stackoverflow.com/questions/23925826/magento-widgets-truncate-fields-containing-quotes

I can imagine why this is happening.
The fix is up to you. There are several ways to tackle this.
## Steps to reproduce
1. Search for or create a widget which has a text config/parameter.
2. Insert that widget into a CMS page/block using the editor, setting the value to `There is no "escape"!`
## Expected result
1. A directive inserted as `{{... my_text_value="There is no "escape"!"}}` <-- this looks wrong, ofc, but it's just to show you what I mean.
## Actual result
1. The directive is inserted as `{{... my_text_value="There is no "}}`
2. Sigh.

**Comment by piotrekkaminski** [comment]
reproduced. Internal issue MAGETWO-54243

**Comment by developer-lindner** [comment]
Does this fix product attributes also?

If i insert an image (in product's description) through the UI in backend i see the "right" media directive syntax, after saving there is just a mess left...

**Comment by veloraven** [comment]
Closed as has been already fixed in 3ff19bf82a c2fd29677 0859c7d3

**Comment by Ctucker9233** [comment]
@veloraven @magento-team What version of Magento will this fix be included in?

**Comment by sashas777** [comment]
@veloraven Also need some kind of escape when value is cms directive.
For example:
`
{{widget type="Custom\Custom\Block\Widget" background="{{media url="wysiwyg/14.jpg"}}" }}
`
When you click "Show/Hide Editor" at the cms page with this widget it breaks.

Need something at the: lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js

for decodeDirectives & necodeDirectives functions

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70436
