### ISSUE TITLE
Issue on Checkout page

### ISSUE THREAD

**Issue by kaustavkar** [magento/magento2#38612]
### Preconditions and environment

- Magento version - **2.4.2**
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

if you go to this page  https://purexusa.com/checkout/
login with this userid and pwd
kar.kaustav1@gmail.com  /  Kaustav9*
you can see the content is not showing https://prnt.sc/4erxinFTzrlb
no changes were made
an order was placed earlier today https://prnt.sc/2hMYs1JrgoC3

### Expected result

It should show content on left hand side of the page

### Actual result

suddenly this happened

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kaustavkar** [comment]
I had resolved the issue.

Please close the ticket


Thanks,
Kaustav Kar

**Comment by engcom-Dash** [comment]
Hi @kaustavkar 

Thanks for reporting and collaboration.

Closing the ticket as per the above comment.
