### ISSUE TITLE
Marketplace automated technical tests are not conducted on 2.4.7

### ISSUE THREAD

**Issue by julienloizelet** [magento/magento2#38614]
### Summary

The "Quality report" paragraph in a marketplace module page states that :

> All tests were conducted on the latest versions of Adobe Commerce that existed for the compatible release lines at the moment of the extension submission. Latest versions of all other software were used, as applicable.

Tests should be conducted on Magento 2.4.7 and PHP 8.3 and seem to be conducted on 2.4.6-p4 and PHP 8.2.

![image](https://github.com/magento/magento2/assets/20956510/6b56d5e2-4a45-46aa-86ac-d0a253c8fd09)

### Examples

Today, I submitted a module and I saw in the report.json (Installation and Varnish test) file that test were done on Magento 2.4.6-p4 and PHP 8.2.

![Capture d’écran du 2024-04-12 14-38-10](https://github.com/magento/magento2/assets/20956510/97e86355-2cec-404b-91d3-0932e0ece2c5)

### Proposed solution

Update the automated tests

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @julienloizelet,

Thanks for the report and collaboration!

It doesn't seems to us a Magento core issue, can you please help us in from where you get that configuration?

Thanks

**Comment by julienloizelet** [comment]
> Hello @julienloizelet,
> 
> Thanks for the report and collaboration!
> 
> It doesn't seems to us a Magento core issue, can you please help us in from where you get that configuration?
> 
> Thanks

Hello,

For information, this is exactly the same issue as this one I created for 2.4.6: https://github.com/magento/magento2/issues/37220

This is not a Magento core issue but something for the "internal team" according to [this comment.](https://github.com/magento/magento2/issues/37220#issuecomment-1473301526).

I hope this helps you understand.

> where you get that configuration?

When you submit a module to the marketplace, you can download a series of json reports at the end of the automated technical review. My screenshot is a screenshot of one of them (the Varnish installation and test).

Thanks

**Comment by engcom-Hotel** [comment]
Thanks @julienloizelet,

I am keeping this `On Hold` and will keep you posted on the updates for this.

Thanks

**Comment by hostep** [comment]
@engcom-Hotel: you closed it without specifying a reason?
