### ISSUE TITLE
magento quantity_and_stock_status.is_in_stock rest api search query 

### ISSUE THREAD

**Issue by simpy25** [magento/magento2#38613]
### Summary

`searchCriteria[filter_groups][0][filters][0][field]=quantity_and_stock_status.is_in_stock&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=0` I want to flter products where  Stock Status is out of stock. But receiving error `The "%1" attribute name is invalid. Reset the name and try again.` what am I doing wrong? 

### Examples

`searchCriteria[filter_groups][0][filters][0][field]=quantity_and_stock_status.is_in_stock&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=0` 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @simpy25,

Thanks for the report and collaboration!

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @simpy25,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
