### ISSUE TITLE
Category description WYSIWYG is empty on non default storeview

### ISSUE THREAD

**Issue by thlassche** [magento/magento2#38622]
### Preconditions and environment

- Magento version: 2.4.7
- Pagebuilder modules disabled

### Steps to reproduce

1. Edit category in the backend on storeview level
2. Untick the box 'Use default value' next to the category description field WYSWYG editor
3. Enter a description in the WYSIWYG editor
4. Save

### Expected result

Description is saved and shown in the edit form

### Actual result

WYSIWYG editor is empty after load

### Additional information

This is due to a change in `dom-observer.js` in https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f 

The `return` here now exits the loop early, which wasn't the case before, since it was inside a `_` function before: https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f#diff-844cfb7b272693bacaa64be3a0fd96a543cc145b478330777c39682cc15b5961R152

Patch that fixes the issue:

```
Index: src/vendor/magento/module-ui/view/base/web/js/lib/view/utils/dom-observer.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/view/base/web/js/lib/view/utils/dom-observer.js b/view/base/web/js/lib/view/utils/dom-observer.js
--- a/view/base/web/js/lib/view/utils/dom-observer.js	
+++ b/view/base/web/js/lib/view/utils/dom-observer.js	(date 1713248057631)
@@ -149,7 +149,7 @@
         _.each(watchers.selectors, function (listeners, selector) {
             for (let data of listeners) {
                 if (!data.ctx.contains(node) || !$(node, data.ctx).is(selector)) {
-                    break;
+                    continue;
                 }
 
                 if (data.type === 'add') {

```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thlassche** [comment]
Pull request: https://github.com/magento/magento2/pull/38623

**Comment by engcom-Bravo** [comment]
Hi @thlassche,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached screenshots.

**Steps to reproduce**

- Edit category in the backend on storeview level
- Untick the box 'Use default value' next to the category description field WYSWYG editor
- Enter a description in the WYSIWYG editor
- Save



<img width="921" alt="Screenshot 2024-04-17 at 09 56 03" src="https://github.com/magento/magento2/assets/51680745/e1d7a363-0c1d-49f8-9a49-a88bddaf161c">


WYSIWYG editor is empty after load.

Hence Confirming the issue.

Thanks.

**Comment by ShapesGraphicStudio** [comment]
Hello, has this been fixed?
I'm still getting this issue with Magento ver. 2.4.7-p3.

**Comment by teunovic** [comment]
This critical bug is still present. Please merge ASAP.
