### ISSUE TITLE
General exception error during Product Import leaves invalid data in url_rewrite table

### ISSUE THREAD

**Issue by gammyduck** [magento/magento2#3862]
There is a bug while importing product data that causes a General Exception that has been reported throughout the year.

The solution is to remove any duplicate product IDs and any categories from url_rewrite table and then try again. If it's a large CSV, you may have to do this a few times.

Quick solution for devs might be to create a check to clear invalid data in the url_rewrite table after an exception while the problem is being resolved?

**Comment by piotrekkaminski** [comment]
@gammyduck can you provide an example file that causes this issue or what kind of error in the file causes it?

**Comment by gammyduck** [comment]
I since downgraded to magento 1.9 so probably not
