### ISSUE TITLE
Category URL Path issue in multi-store

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38627]
### Preconditions and environment

- Magento version 2.4.6 & 2.4.7

### Steps to reproduce

1. Create 2 stores ( default = 1, other_store = 2), same category root assigned.
2. Create this category tree : 
    - Cat A (url key = `a` in default view. url key = `other_a` in store 2)
         -  Cat AB (url key = `b` in default view)
3. Check `catalog_category_entity_varchar` table where attribute_id = `(ID of url_path)` and category_id = `(ID of cat AB)`. You should see : `a/b` for store 0 and `other-a/b` for store 2.
4. Check frontend canonical url for store2 - AB category page. You should see `https://.../other-a/b`
5. Change url_key for cat AB, in default view, for `b2`
6. Check again `catalog_category_entity_varchar` table where attribute_id in `(ID of url_path)` and category_id = (ID of cat AB). 
7. Check again canonical url for store2 AB category page.

### Expected result

- `a/b2` for store 0 and `other-a/b2` for store 2.
- Url of category = `https://.../other-a/b2`, Canonical : `https://.../other-a/b2`

### Actual result

- `a/b2` for store 0 and `other-a/b` for store 2.
- Url of category = `https://.../other-a/b2`, Canonical : `https://.../other-a/b`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Nuranto** [comment]
I did more test, on several projects I'm working on. Also tried with all third-extensions disabled. I can reproduce the issue in all cases.
I tried to change some configuration, but cannot manage to find the missing step to reproduce :/

**Comment by engcom-Delta** [comment]
Hi @Nuranto,

Verified the issue on 2.4-develop and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

  1.Create 2 stores ( default = 1, other_store = 2), same category root assigned.
  2.Create this category tree :
  3.Cat A (url key = a in default view. url key = other_a in store 2)
       Cat AB (url key = b in default view)
  4.Check catalog_category_entity_varchar table where attribute_id = (ID of url_path) and category_id = (ID of cat AB). You 
     should see : a/b for store 0 and other-a/b for store 2.
  5.Check frontend canonical url for store2 - AB category page. You should see https://.../other-a/b
  6.Change url_key for cat AB, in default view, for b2
  7.Check again catalog_category_entity_varchar table where attribute_id in (ID of url_path) and category_id = (ID of cat AB).
  8.Check again canonical url for store2 AB category page.


Please refer the attached screenshot.

<img width="1427" alt="Screenshot 2024-04-25 at 4 06 35 PM" src="https://github.com/magento/magento2/assets/51681379/2e3d968e-ae29-40b7-a4ad-9bd395e35875">

<img width="1437" alt="Screenshot 2024-04-25 at 4 07 41 PM" src="https://github.com/magento/magento2/assets/51681379/b3b6bd11-a9d1-4e04-8a84-52563635d7cc">

<img width="1439" alt="Screenshot 2024-04-25 at 4 08 03 PM" src="https://github.com/magento/magento2/assets/51681379/54f831af-f26c-47bf-8728-26c3985a45c9">

<img width="1430" alt="Screenshot 2024-04-25 at 4 09 41 PM" src="https://github.com/magento/magento2/assets/51681379/950d79f9-9b0f-4bef-9e2a-cf789ce3ca5b">

<img width="509" alt="Screenshot 2024-04-25 at 4 10 55 PM" src="https://github.com/magento/magento2/assets/51681379/dc8f7d5c-970d-4753-bde8-13480de917dc">

<img width="494" alt="Screenshot 2024-04-25 at 3 59 41 PM" src="https://github.com/magento/magento2/assets/51681379/7cfb30d2-bebc-4e62-af52-0f8fb90de223">

<img width="1431" alt="Screenshot 2024-04-25 at 4 03 53 PM" src="https://github.com/magento/magento2/assets/51681379/7b0fe08b-9061-4977-90e8-307645e78689">

**Comment by digitalrisedorset** [comment]
@magento I am working on this

**Comment by digitalrisedorset** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks

**Comment by rustmaestro** [comment]
Hi @engcom-Bravo,

I don't think this is working as expected. An normally non-destructive action in the backend, that can cause the url_path to differ per store even though they have the same url_key seems like a bug to me.

We have experienced this very same issue where we change the url_key, but the url_path doesn't update, with no way to solve this without the use of command line tools, or editing the database to manually fix the value of the url_path attribute.
