### ISSUE TITLE
Changes in Custome theme (_theme.less) dosent reflect on UI

### ISSUE THREAD

**Issue by kaleberegaurav** [magento/magento2#3863]
Hello ,
I am new to Magento ver. 2.0.0 product. Basically i am trying to create a new theme with custom layout for my project but i am facing problem with the Custom theme (which i am trying to create). I followed http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html document .I created theme following the documentation and created _theme.less containing
@page__background-color: @color-gray56;
@sidebar__background-color: @color-gray40;
@primary__color: @color-gray80;
@border-color__base: @color-gray76;

@link__color: @color-gray56;
@link__hover__color: @color-gray60;

//  Buttons
@button__color: @color-gray20;
@button__background: @color-gray80;
@button__border: 1px solid @border-color__base;

//  Primary button
@button-primary__background: @color-orange-red1;
@button-primary__border: 1px solid @color-orange-red2;
@button-primary__color: @color-white;
@button-primary__hover__background: darken(@color-orange-red1, 5%);
@button-primary__hover__border: 1px solid @color-orange-red2;
@button-primary__hover__color: @color-white;

//  Navigation
@navigation-level0-item__color: @color-gray80;
@submenu-item__color: @color-gray80;

@navigation__background: @color-gray40;
@navigation-desktop-level0-item__color: @color-gray80;
@navigation-desktop-level0-item__hover__color: @color-gray34;
@navigation-desktop-level0-item__active__color: @navigation-desktop-level0-item__color;

//  Tabs
@tab-control__background-color: @page__background-color;

//  Forms
@form-element-input__background: @color-gray89;
@form-element-input-placeholder__color: @color-gray60;

//  Header icons
@header-icons-color: @color-gray89;
@header-icons-color-hover: @color-gray60;

registration.php containing
<?php
/**
- Copyright © 2015 Magento. All rights reserved.
- See COPYING.txt for license details.
  */

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::THEME,
    'frontend/Magento/first',
    **DIR**
);

theme.xml containing 

<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>First</title>
    <parent>Magento/blank</parent>
    <media>
        <preview_image>media/preview.jpg</preview_image>
    </media>
</theme>

When i first selected my theme the color in _theme.less file were properly displayed but when i tried to change any css property it was not reflected on UI .To be elaborate i changed
@page__background-color: @color-gray56; 
to 
@page__background-color: @color-orange-red1;
still there was on change on UI .
I flushed cache too.Am i doing something wrong?
Below is my file structure too
![capture](https://cloud.githubusercontent.com/assets/18005969/13951376/94af31b6-f056-11e5-950e-d7f7a1e8d489.PNG)

**Comment by eug123** [comment]
Hi, @kaleberegaurav

Have you tried to clean [pub/static](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html#info) folder?

**Comment by alankent** [comment]
You might find https://github.com/alankent/gsd-code-samples/tree/master/volume2-theme-web-page-assets/app/design/frontend/AlanKent/eco-warrior useful. It is a much simpler set of Less file changes, but it is a complete working example. (Shameless plug - it came from http://alankent.me/gsd.)

**Comment by kaleberegaurav** [comment]
Hello,
@eug123 yes i have deleted content of pub/static still there was no effect. I even tried php bin/magento setup:upgrade and php bin/magento indexer:reindex still no effect.

**Comment by donotdividebyzero** [comment]
do : 
php bin/magento setup:static-content:deploy (here put language code you using ex. en_US)

this will compile your less and copy every needed file to pub/static

**Comment by pynej** [comment]
In my experience you have to go to Cache Management -> Flush Static Files Cache for Less changes to show up in the front end.  I do have it in developer mode so maybe thats why i don't need to use deploy?

**Comment by BenGlassAtlas** [comment]
I'm having similar problems with 2.0.4 in developer mode, even with all caches disabled (including Varnish) I have to clear pub/static to display my CSS changes. Even then it doesn't always update, I'm finding it extremely difficult to work with. I didn't have this issue on 2.0.0
