### ISSUE TITLE
/rest/V1/products does not allow filtering on store or website, nor returns that info

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#3864]
## Steps to reproduce

1) The following examples :

```
http://magento.dev:9080/rest/V1/products/?searchCriteria[filterGroups][0][filters][0][field]=website_id&searchCriteria[filterGroups][0][filters][0][value]=1
http://magento.dev:9080/rest/V1/products/?searchCriteria[filterGroups][0][filters][0][field]=store_id&searchCriteria[filterGroups][0][filters][0][value]=1
```

2) Or request a general:

```
http://magento.dev:9080/rest/V1/products/
```
## Expected result

1) A list of products matching the given store- or website-id.
2) A list of products containing a reference to the store or website they are on. In the case of names, descriptions and prices, should match the store specified by store_id filter.
## Actual result

1) An error: 

```
<response>
    <message>Invalid attribute name: %1</message>
    <parameters>
        <item>website_id</item>
    </parameters>
</response>
```

2) Some generic product definition. If you use store definition for languages, you want products returned in the appropriate language, including description. Similar for images, prices, etc.

**Comment by piotrekkaminski** [comment]
@mbrinton01 can you look into it?

**Comment by RUjmiak** [comment]
@fvschie @maghamed 
http://<magento_host>/rest/<store_code>/schema&services=<serviceName1,serviceName2,..>

There should be possibility to filter by store_code liek rest/<store_code>/V1/products but it is not working. I think that it is bug.

This filtering working with V1/categories

**Comment by fvschie** [comment]
Actually this is working in a non-standard and undocumented way. Instead of querying products like:
`http://magento.dev:9080/rest/V1/products?searchCriteria[pageSize]=5`

You can query them via:
`http://magento.dev:9080/rest/default/V1/products?searchCriteria[pageSize]=5`

Not the 'default' in the URL. That's the code (not ID!) of the store view you want to access. While this is bass-ackwards, it does work, and should at least be documented.

**Comment by StefanRijnhart** [comment]
@fvschie very helpful, thanks!

**Comment by veloraven** [comment]
@fvschie thank you for your report.
Please, provide the used Magento version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by sergiomendonca** [comment]
Does not work the official documentation `http://<magento_host>/rest/<store_code>/schema`
(http://devdocs.magento.com/guides/v2.1/rest/generate-local.html)

Using magento v2.1.9.
The filter by store is ignored, and the json returns all info for all stores
