### ISSUE TITLE
[Graphql] Type issue in 2.4.7

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38662]
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Launch a graphql query that will use GetCustomSelectedOptionAttributes

### Expected result

No error

### Actual result

```
main.ERROR: Magento\Framework\GraphQl\Query\Uid::encode(): Argument #1 ($id) must be of type string, int given, called in /var/www/html/vendor/magento/module-customer-graph-ql/Model/Customer/GetCustomSelectedOptionAttributes.php on line 58
```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Nuranto ,

We have tried to fetch customer attributes with Graphql and we are not able reproduce the error .

Please find attached the screenshot and let us know if something is missed.

<img width="1440" alt="Screenshot 2024-05-14 at 3 37 51 PM" src="https://github.com/magento/magento2/assets/51681379/49a5b870-b9a5-4d59-965b-b65623dfa036">

**Comment by hnsr** [comment]
I ran into this issue with a third party module that added a customer attribute of type boolean with `int` backend type. Although I am not sure if this is the correct fix that covers all cases, I implemented this patch that fixes the error for us:

```Fix error on GraphQL customer query due to attribute type issue. See also https://github.com/magento/magento2/issues/38662

@package magento/module-customer-graph-ql

--- magento/module-customer-graph-ql/Model/Customer/GetCustomSelectedOptionAttributes.php.orig	2024-04-03 16:20:22
+++ magento/module-customer-graph-ql/Model/Customer/GetCustomSelectedOptionAttributes.php	2024-05-21 11:52:53
@@ -54,8 +54,11 @@
             if (!in_array($option->getValue(), $selectedValues)) {
                 continue;
             }
+            // Boolean attributes can actually give an `int` result here, so we must cast to string to avoid type error
+            // when encoding.
+            $value = (string) $option->getValue();
             $result[] = [
-                'uid' => $this->uid->encode($option->getValue()),
+                'uid' => $this->uid->encode($value),
                 'value' => $option->getValue(),
                 'label' => $option->getLabel()
             ];
```

**Comment by zexperto** [comment]
I just want to mention here that the main issue is the type of the frontend attribute, I have the same issue and I found that one of the attributes has "Magento\Eav\Model\Entity\Attribute\Source\Boolean" as soruce_model but the frontend type was "select", I have changed to "boolean" and it solved the issue
