### ISSUE TITLE
CMS Pages used in settings are not excluded from sitemap

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#38666]
### Preconditions and environment

- Magento 2.4

The error is because the settings use the following source: `Magento\Cms\Model\Config\Source\Page` which pipes the page id to the identifier. E.g:
<img width="747" alt="Capture d’écran, le 2024-04-26 à 11 31 08" src="https://github.com/magento/magento2/assets/20971693/8932ce5e-e071-48f0-b566-69137e36b94a">

So when `\Magento\Cms\Model\GetUtilityPageIdentifiers::execute` is called:
the scoped values (if not the default one provided in `vendor/magento/module-cms/etc/config.xml` is going to have this format : <identifier>|<page_id>

Which is incompatible with the query format here (used to generate the cms page sitemap):

- `\Magento\Sitemap\Model\ResourceModel\Cms\Page::getCollection`

More specifically:
```
)->where(
    'main_table.identifier NOT IN (?)',
    $this->getUtilityPageIdentifiers->execute()
)
```

It won't prevent to return the given pages because the format does not match!

### Steps to reproduce

- 2 websites (a & b) with a specific home page configured for each (e.g: home-a for global, and home-b for website b)
- Create a sitemap for each websites
- Generate the sitemap from the admin grid

### Expected result

The sitemap A does not have the home-a url
The sitemap B does not have the home-b url

### Actual result

The sitemap A does not have the home-a url (OK)
The sitemap B does have the home-b url (NOK)

### Additional information

Also true for:
- cms_home_page
- cms_no_route
- cms_no_cookies

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thomas-kl1** [comment]
@magento give me 2.4-develop instance

**Comment by thomas-kl1** [comment]
Seems it has been fixed: https://github.com/magento/magento2/issues/35001
Commit: https://github.com/magento/magento2/commit/0ce75991942a56663a4fc77b3cc8eb6e1cdddce5

**Comment by engcom-Delta** [comment]
Hi @thomas-kl1 ,

Based on your comment https://github.com/magento/magento2/issues/38666#issuecomment-2085297613 , we are closing this issue.Feel free to raise a fresh ticket or reopen this ticket if you face the same issue again.

Thanks,
