### ISSUE TITLE
Magento 2.4.x not working properly in localhost

### ISSUE THREAD

**Issue by priyankaasv** [magento/magento2#38664]
### Preconditions and environment

- Magento 2 version - 2.4.7
- OS : Windows
- Server : Xampp
- Apache with running port 8080

### Steps to reproduce

1. Installed Magento 2 in xampp windows successfully
2. Unable to login admin panel keep on loading same page without any error messages
3. Homepage in luma theme looks like blank theme there are no menu and content
4. Products search returns empty
5. Unable to create account throws Invalid Form key please refresh the page

### Expected result

Magento 2 in local should works fine

### Actual result

1. Unable to login admin panel keep on loading same page without any error messages
2. Homepage in luma theme looks like blank theme there are no menu and content
3. Products search returns empty
4. Unable to create account throws Invalid Form key please refresh the page and so on

### Additional information

[Magento 2 local issues.docx](https://github.com/magento/magento2/files/15111451/Magento.2.local.issues.docx)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by priyankaasv** [comment]
> Hi @priyankaasv. Thank you for your request. I'm working on Magento instance for you.

Thank You so much

**Comment by priyankaasv** [comment]
Hi instance is working fine for me could you please check issues in my local

Thanks in advance

**Comment by engcom-Delta** [comment]
Hi @priyankaasv ,

Thanks for reporting and collaboration.

We will not be able to check issues in your local, you may get help from Magento StackExchange.You can follow the link below.

https://magento.stackexchange.com/

Thanks,

**Comment by engcom-Delta** [comment]
Hi @priyankaasv,

Closing this ticket as this is not an issue.

Thanks,
