### ISSUE TITLE
Adding URL rewrites with an accent causes infinite loading

### ISSUE THREAD

**Issue by janssensjelle** [magento/magento2#38692]
### Preconditions and environment

- Tested on 2.4.5-p7 and 2.4.6-p4
- Vanilla Magento with sample data

### Steps to reproduce

Add a new URL Rewrite with an accent and redirect type not set to None

Example:
![Screenshot 2024-05-02 at 12 18 23](https://github.com/magento/magento2/assets/10356515/6eaa1032-0c93-464f-92f6-8005e11415d3)

### Expected result

URL Rewrite is successfully created and functioning

### Actual result

The saving will last forever 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by janssensjelle** [comment]
@magento give me 2.4-develop instance

**Comment by janssensjelle** [comment]
I can confirm this issue

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @janssensjelle ,

Verified the issue on 2.4-develop and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1.Apply transliteration for product URL configuration option to Yes in Stores > Settings > Configuration > Catalog > Catalog 
   > Search Engine Optimization 
2.Add a new URL Rewrite with an accent and redirect type not set to None


<img width="1432" alt="Screenshot 2024-05-03 at 2 24 37 PM" src="https://github.com/magento/magento2/assets/51681379/9c54b769-c2f9-4c85-a589-16f3cb83bf7b">


<img width="1440" alt="Screenshot 2024-05-03 at 3 09 33 PM" src="https://github.com/magento/magento2/assets/51681379/ae8c6162-d587-4d08-995c-0e5d83ab409a">


The saving lasts forever


French accent

<img width="1439" alt="Screenshot 2024-05-03 at 3 11 17 PM" src="https://github.com/magento/magento2/assets/51681379/c37be25a-f484-4865-be08-e822ef258411">


Portugese accent
 
<img width="1434" alt="Screenshot 2024-05-03 at 3 36 15 PM" src="https://github.com/magento/magento2/assets/51681379/0fbdfb0a-a8ca-4943-8cbd-746b5ec787d5">

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11907 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11907&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
