### ISSUE TITLE
Can't login to admin backend, since new security patch 2.4.4-p8

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#38699]
Sometimes e.g. after the weekend, we suddenly can't login into the admin area / backend of our shop, since installing this security patch: https://helpx.adobe.com/security/products/magento/apsb24-18.html

We need to delete our cookies to be able to login again.

# Error:

**Argument #1 ($datetime) must be of type string, null given in /vendor/magento/module-security/Model/AdminSessionInfo.php:136**

https://github.com/magento/magento2/blob/9721cc22eb32482d82e5e3d275fe3a0221d8b750/app/code/Magento/Security/Model/AdminSessionInfo.php#L136

This is how it used to be in *2.4-develop*:

        $lastUpdatedTime = $lastUpdatedTime === null ? 0 : strtotime($lastUpdatedTime);
        
I don't have information on how to reproduce this.

**Comment by engcom-Dash** [comment]
Hi @Eddcapone 

Thanks for reporting and collaboration.

Can you please share the details steps to reproduce the issue and screenshots in order for us to reproduce the issue accurately.

Thanks.

**Comment by Eddcapone** [comment]
@engcom-Dash As written [here](https://github.com/magento/magento2/issues/38699#issue-2280366375). I don't have informations on how to reproduce this. We just knows that it happens to us. Last time it happend after the weekend.

**Comment by engcom-Dash** [comment]
Hi @Eddcapone 

Thanks for reporting and collaboration.

We have a similar issue - [38704](https://github.com/magento/magento2/issues/38704)

Hence, we are considering this as a duplicate ticket and closing this ticket.

**Comment by Eddcapone** [comment]
@engcom-Dash Please explain how it is remotely similar? It has nothing to do with our issue.
