### ISSUE TITLE
Default Product Attribute Settings Issue

### ISSUE THREAD

**Issue by FluidGuy** [magento/magento2#38703]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento version 2.4.7 
When editing a product attribute if a default is selected there is no way of unselecting all, so there is always some default now for that option. Work around is whenever creating new parts manually turn off all attributes that are turned on by default

### Steps to reproduce

1. Go into admin view 
2. Select Stores in admin side panel 
3. Select product under attributes 

 Scenario 1:

4. Select an attribute to edit which has Catalog Input Type for Store Owner is Visual swatch or dropdown
5. If the "is default" option is selected, there is no way to set the attribute to no longer have a default option

Scenario 2:

6. Select an attribute to edit which has Catalog Input Type for Store Owner is Multiple Select
7. If you deselect the default option then save or save and continue it still is set as the default
8. If you select multiple options as default and deselect the default options then save or save and continue all the options 
    are selected as default

### Expected result

 Scenario 1: If a default is selected, there would be a way to unselect having a default set
 Scenario 2: If you deselect the default option then save or save and continue it should removed from default

### Actual result

Scenario 1: Once a default is set, there is no way to turn defaults off for that option
Scenario 2: Once a default is set, after we deselect it , its never saved

### Additional information

![image](https://github.com/magento/magento2/assets/169174477/b2bfeedb-8444-4bd9-8ca2-2eed30d5c288)
See how a default is set to the 1675 psi option, now this attribute will always have some default set and it cannot be changed to not be on by default

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FluidGuy** [comment]
@magento give me 2.4-develop instance

**Comment by FluidGuy** [comment]
The issue occurs in the vanilla version, if you deselect the default option then save or save and continue it still is set as the default

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4.7 instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @aaqtgft ,

Verified the issue on 2.4-develop, 2.4.7 and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1.Go into admin view
2.Select Stores in admin side panel
3.Select product under attributes

Scenario 1:

4.Select an attribute to edit which has Catalog Input Type for Store Owner is Visual swatch or dropdown
5.If the "is default" option is selected, there is no way to set the attribute to no longer have a default option

Scenario 2:

6.Select an attribute to edit which has Catalog Input Type for Store Owner is Multiple Select
7.If you deselect the default option then save or save and continue it still is set as the default
8.If you select multiple options as default and deselect the default options then save or save and continue all the options
   are selected as default

Go into admin view

<img width="1439" alt="Screenshot 2024-05-08 at 2 06 21 PM" src="https://github.com/magento/magento2/assets/51681379/68d8456b-bce3-4289-be6f-cf48369689c7">

Select Stores in admin side panel

<img width="1440" alt="Screenshot 2024-05-08 at 2 06 42 PM" src="https://github.com/magento/magento2/assets/51681379/4c179c80-730c-4dab-b583-e17c6c2d31b6">

Select product under attributes

<img width="1436" alt="Screenshot 2024-05-08 at 2 07 17 PM" src="https://github.com/magento/magento2/assets/51681379/c25d60bb-081d-450b-a426-608aa1c34072">

Select an attribute to edit which has Catalog Input Type for Store Owner is Multiple Select

<img width="1440" alt="Screenshot 2024-05-09 at 6 27 46 PM" src="https://github.com/magento/magento2/assets/51681379/d55cb17f-9f5d-4fa2-bcf6-1e7e25301e05">

Saved

<img width="1440" alt="Screenshot 2024-05-09 at 6 28 13 PM" src="https://github.com/magento/magento2/assets/51681379/7e4e7003-7182-4ea0-a17c-eb32d2230b8f">

If you deselect the default option then save or save and continue it still is set as the default

<img width="1440" alt="Screenshot 2024-05-09 at 6 28 21 PM" src="https://github.com/magento/magento2/assets/51681379/ace4e856-f5ad-469b-8863-d691330f3260">


<img width="1440" alt="Screenshot 2024-05-09 at 6 28 30 PM" src="https://github.com/magento/magento2/assets/51681379/4533e72d-00c1-4e9b-8054-f78ee2dcdd35">

multiple option selected as default

<img width="1172" alt="Screenshot 2024-05-09 at 6 34 01 PM" src="https://github.com/magento/magento2/assets/51681379/a4b297e0-62e7-4233-811b-60f4031793f5">

Select an attribute to edit which has Catalog Input Type for Store Owner is Visual swatch or dropdown


<img width="1428" alt="Screenshot 2024-05-09 at 6 28 55 PM" src="https://github.com/magento/magento2/assets/51681379/fb3a1e26-e90a-483d-8f46-785b815e8c9b">

If the "is default" option is selected, there is no way to set the attribute to no longer have a default option, We have to select another option to deselect another

<img width="1440" alt="Screenshot 2024-05-09 at 6 29 05 PM" src="https://github.com/magento/magento2/assets/51681379/f5a2dc73-bd88-49df-94b1-ab7be8596b32">

**Comment by rostilos** [comment]
@magento magento I am working on this

**Comment by rostilos** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @FluidGuy,

Internal team has started to work on it

Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11932 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11932&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
