### ISSUE TITLE
CSV Product Import - Permanantly hanging on "Please wait.."

### ISSUE THREAD

**Issue by gammyduck** [magento/magento2#3870]
Steps to reproduce:

I uploaded a 1.5MB CSV of 1000 products successfully this morning after using this fix #3862

However, I wanted to change the contents for all products under one of the headers and tried to reupload. I tried another file and no luck.

Now it hangs forever like this:
![b7f141526e1b8b4f60bb84bf4645103a](https://cloud.githubusercontent.com/assets/3619746/13958760/39d42574-f049-11e5-96dc-e200235c6759.gif)

**Comment by gammyduck** [comment]
After researching it appears to happen due to one of the columns data been changed from 1 to 0. I'll find the problematic header(s) tomorrow.

**Comment by Microstudioweb** [comment]
I have the same problem after migrate from magento 1.9 to magento 2.
I had follow the fix #3862, but I have truncate table.
Now I can see the product list on web site, but in admin area I have the please wait...forever page for product and costumer.

**Comment by gammyduck** [comment]
Hello
I have fixed the issue. Please add a check for duplicate headers.
@Microstudioweb make sure your CSV file is under 10MB as well

**Comment by Microstudioweb** [comment]
Hi @gammyduck , thanks
My issue was a litle bit different.
My folder group was wrong. I set the user's server to use the right group.

**Comment by kevando** [comment]
I get the same error and I see a 503 in the browser console log

validation.js:168 POST https://mymagento2store.com/admin/admin/import/validate/key/7c3d2a6d77a544f23394e62945bebd6a2f68fe828eac30ce4ad4581c7c9fe9cb/?form_key=gb1G71Sb3uFLmW2e 503 (Service Unavailable)

**Comment by Microstudioweb** [comment]
Hello.
Unfortunately the issue come back again and this time persist.
I had tried the previous method, truncate table, but this time don't get any result.

**Comment by gammyduck** [comment]
Check your headers

**Comment by kevando** [comment]
For me it was the end line encoding. Opening the CSV in the text editor and changing that setting worked for me. Would be nice if there was at least some error output here. Extremely annoying that it just hangs.

**Comment by tseven** [comment]
I agree with @kevando , a hung spinning loader is not helpful at all.

**Comment by tseven** [comment]
Discovered one culprit (Excel on Mac) and solution.

## Steps to reproduce:
1. Export products using the admin UI.
2. Edit anything in the .csv in excel on a Mac.
3. Save .csv.
4. Import into Magento

This will cause the import to hang. Browser console shows the post failed with 503.

## Solution/Workaround

In excel save as "Windows Comma Separated (.csv)"

**Comment by fhennessy** [comment]
Folder group wasn't set to be writable for the correct group! fixed my issue

**Comment by veloraven** [comment]
@gammyduck thank you for your report.
Please, provide the used Magento version. Please also provide information if it was clear install or upgrade from some previous version.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by ooples** [comment]
I'm having this issue as well

**Comment by angedevPer** [comment]
I had a similar problem and I fixed it changing on 
vendor/magento/module-catalog-import-export/Model/Import/Product/CategoryProcessor.php 
replace this code on line 80
$path[] = $collection->getItemById((int)$structure[$i])->getName();

with this 
    if($collection->getItemById($structure[$i])){
          $path[] = $collection->getItemById($structure[$i])->getName();  
    }

**Comment by ooples** [comment]
That fixed the issue for me. Can we include this in the next release?

**Comment by angedevPer** [comment]
Sure!

**Comment by truedaz** [comment]
I was having this issue on 2.1.7 and tried all the above. I was getting a 503 error in console.

After a lot of re-installing and testing, I realised that it was because I am running on a local webserver and importing a file fro the /var/import/export folder. 

It seems that It couldnt import from this location because Magento moves the file to import_history while its trying to load the file. To fix, import fro any other location (ie desktop)

**Comment by amolbhandari52** [comment]
Thanks @DarkSakura : it worked on 2.1.6 with the fix you gave. thanks verymuch.

**Comment by dilluky** [comment]
Hi All, I had the same issue. 
Changing the INDEX from admin worked for me. Check the below link.
https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Import-quot-Please-wait-quot-hang-or-UI-issues/td-p/53107

**Comment by shanenacpil** [comment]
I tried the above solutions but didn't work for me. I'm using magento v2.1.7 

Have you manage to fix your issue @truedaz?

**Comment by lipilef** [comment]
Had the same issue, tried to split my csv onto two csv's and worked fine.

The "please wait" keeps on. but it import just fine.
