### ISSUE TITLE
Adding a simple select in product attribute for dropdown type won't open options

### ISSUE THREAD

**Issue by marmureanuweb** [magento/magento2#38708]
### Summary

I'm trying to extend the product attribute option with a simple select element.
When trying to open it, it won't open due to an unknown reason.
I've tried removing the classes and adding "select","admin__control-select" but no luck. I've tried moving the select from the top of the row, but you will see the same exact issue.
![SCR-20240508-ofbd](https://github.com/magento/magento2/assets/13685130/4b4b5e46-5761-401e-b848-355e17a1a29a)

### Examples

The file where I'm trying to add the select "vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/attribute/options.phtml" > in the "<script id="row-template" type="text/x-magento-template">" in any of the ```<td>``` cells.
The element I'm trying to add ```<select name="test" class="select admin__control-select" >
                        <option value="enable" selected="selected">enable</option>
                        <option value="disable">disable</option>
                    </select>```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by marmureanuweb** [comment]
The element that I'm trying to add 
```
                    <select name="test" class="select admin__control-select">
                        <option value="1">enable</option>
                        <option value="2">disable</option>
                    </select>
```

**Comment by engcom-Hotel** [comment]
Hello @marmureanuweb,

Thanks for the report and collaboration!

Rather than modifying anything within the vendor folder, I recommend creating a custom dropdown field for an existing form in the Magento 2 Admin Panel by following these steps:

1. Create a custom module.
2. Use Magento UI Components to define the dropdown field and its behavior.

And also it doesn't seem a Magento core bug hence I suggest you refer to the [Magento Stackexchange](https://magento.stackexchange.com/).

Thanks

**Comment by engcom-Hotel** [comment]
Dear @marmureanuweb,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
