### ISSUE TITLE
Negative Salable quantity

### ISSUE THREAD

**Issue by JJupi** [magento/magento2#38700]
### Preconditions and environment

- Magento version 2.3.7-p3
- Negative salabale quantity makes it unpurchaseable by customers on the website. The stock and quantity is correct however the salable quantity is incorrect and messes with the availability of the products. Is there a way to adjust and fix the salabla quantity in magento?

### Steps to reproduce

Unable to add products to the cart. = quantity unavailable

### Expected result

<img width="801" alt="Screenshot 2024-05-07 at 3 46 27 pm" src="https://github.com/magento/magento2/assets/147351798/16e5b23e-2a1b-45e4-b137-4dfe1d0363cc">
Quantity added and 12 units in stock therefore this should not generate any errors.

### Actual result

<img width="907" alt="Screenshot 2024-05-07 at 3 44 41 pm" src="https://github.com/magento/magento2/assets/147351798/36732418-0ee8-42a7-85cd-76d7ec54bbdb">
<img width="888" alt="Screenshot 2024-05-07 at 3 44 20 pm" src="https://github.com/magento/magento2/assets/147351798/0baf4ece-5758-4b40-ac6e-41acb56984a2">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by JJupi** [comment]
> Hi @engcom-Bravo, here is your Magento Instance: https://3eb067a92136416c45ca1126c86ab48d.instances-prod.magento-community.engineering Admin access: https://3eb067a92136416c45ca1126c86ab48d.instances-prod.magento-community.engineering/admin_e9b2 Login: 5b982905 Password: d2035a4f680a

Thanks for this, but I'm still struggling with the salable quantity going into negative values and not allowing me to add products to the cart. 
<img width="1573" alt="Screenshot 2024-05-09 at 4 42 46 pm" src="https://github.com/magento/magento2/assets/147351798/bb3c588b-594c-4663-9200-991a02c3d606">
<img width="630" alt="Screenshot 2024-05-09 at 4 42 25 pm" src="https://github.com/magento/magento2/assets/147351798/d2a0f660-a1f2-4e48-9db1-bb8971f6a393">

**Comment by engcom-Bravo** [comment]
Hi @JJupi,

Thanks for your reporting and collaboration.

Kindly refer this https://magento.stackexchange.com/questions/366949/scable-qty-going-to-nagative-value regarding salable quantity and check any third party modules causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @JJupi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
