### ISSUE TITLE
getTracking() not found

### ISSUE THREAD

**Issue by skghorela** [magento/magento2#38719]
Hello Team,
Please help on this error(Magento2.4.7)

Note:- only "Flat Rate - Fixed" is giving error.

{main} {"exception":"[object] (Error(code: 0): Call to undefined method Magento\Framework\Phrase::getTracking() at /var/www/php83/ERPm247/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml:21)"} []
![Screenshot (43)](https://github.com/magento/magento2/assets/82929406/866a5d7a-a1e1-4a03-ac42-4fd6a2469eba)

**Comment by engcom-Dash** [comment]
Hi @skghorela 

Thanks for reporting and collaboration.

Can you please add detailed steps to reproduce for us to verify the issue accurately.

Thanks.

**Comment by skghorela** [comment]
Hello Team,
Thank you for your reply.
It is coming from custom module.
Thank you and I wish you a nice day.

**Comment by engcom-Hotel** [comment]
Hello @skghorela,

We are using this platform to report the Magento core library issues/bugs. If you still facing the same issue in your custom module then please raise this issue in [Magento Stackexchange](https://magento.stackexchange.com/).

Thanks
