### ISSUE TITLE
Sample Data is installed with errors. See log file for details

### ISSUE THREAD

**Issue by ghost** [magento/magento2#38716]
### Summary

Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/Users/username/bsscommerce/magento2/var/cache/" is not writable in /Users/username/bsscommerce/magento2/vendor/magento/zend-cache/library/Zend/Cache.php:209 Stack trace: #0 /Users/username/bsscommerce/magento2/vendor/magento/zend-cache/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/Use...') #1 /Users/username/bsscommerce/magento2/vendor/colinmollenhour/cache-backend-file/File.php(86): Zend_Cache_Backend_File->setCacheDir('/Users/lehongph...') #2 /Users/username/bsscommerce/magento2/vendor/magento/zend-cache/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /Users/username/bsscommerce/magento2/vendor/magento/zend-cache/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(434): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /Users/username/bsscommerce/magento2/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(45): Magento\Framework\App\Cache\Frontend\Factory->Magento\Framework\App\Cache\Frontend\{closure}() #6 /Users/username/bsscommerce/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Cache\Frontend\Adapter\Zend->__construct(Object(Closure)) #7 /Users/username/bsscommerce/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #8 /Users/username/bsscommerce/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array) #9 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(430): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array) #10 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(176): Magento\Framework\App\Cache\Frontend\Factory->createCacheWithDefaultOptions(Array) #11 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create(Array) #12 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(156): Magento\Framework\App\Cache\Frontend\Pool->_initialize() #13 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get('default') #14 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Cache/Type/Config.php(52): Magento\Framework\App\Cache\Type\FrontendPool->get('config') #15 /Users/username/bsscommerce/magento2/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend() #16 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/ObjectManager/ConfigLoader.php(73): Magento\Framework\Cache\Frontend\Decorator\Bare->load('global::DiConfi...') #17 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/ObjectManager/Environment/Developer.php(79): Magento\Framework\App\ObjectManager\ConfigLoader->load('global') #18 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/ObjectManagerFactory.php(191): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array) #19 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Bootstrap.php(212): Magento\Framework\App\ObjectManagerFactory->create(Array) #20 /Users/username/bsscommerce/magento2/vendor/magento/framework/App/Bootstrap.php(127): Magento\Framework\App\Bootstrap->__construct(Object(Magento\Framework\App\ObjectManagerFactory), '/Users/lehongph...', Array) #21 /Users/username/bsscommerce/magento2/pub/index.php(27): Magento\Framework\App\Bootstrap::create('/Users/lehongph...', Array) #22 {main} thrown in /Users/username/bsscommerce/magento2/vendor/magento/zend-cache/library/Zend/Cache.php on line 209

### Examples

version 247

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @unrealphong,

By looking into the error mentioned in the main description, it seems that the correct folder permissions are not available. Please go through the below-documentation for the same:

https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/file-system/configure-permissions

Closing this issue for now.

Thanks
