### ISSUE TITLE
Product is still visible in catalog search after setting category permission to only logged in customers in magento2.4.6

### ISSUE THREAD

**Issue by afzelarshad** [magento/magento2#38710]
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce

![Screenshot from 2024-05-10 17-23-50](https://github.com/magento/magento2/assets/49970920/a1533a97-75b9-4f9c-a446-2c548be567b4)
category permission is set to logged-in customers only, but when non-logged-in customers search for any product of this category on the front end the product is visible.

![Screenshot from 2024-05-10 17-28-18](https://github.com/magento/magento2/assets/49970920/24362db6-52dd-4279-af38-db007ed258b2)

### Expected result

if category permission is set to log-in users only then its product shouldn't be displayed for non-logged-in customers, 
if a product consists of multiple categories like one category is restricted for non-logged-in customers and one category is allowed for non-logged-in customers then it should display the product on the frontend because it consists of a category whose permission is set to allow for non-logged-in customers. front end

### Actual result

No product found matching your query something like that

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by afzelarshad** [comment]
To verify if some customization was causing this issue I Deleted all modules in the app code and changed the theme to Magento Luma. but the issue was still persistent.

**Comment by engcom-Delta** [comment]
Hi @rdk-pmis,

Verified the issue on 2.4-develop in commerce edition and it is not reproducible.

Steps to reproduce:-

1.Go to Catalog ->Categories
2.Choose a Category and Deny to not logged in customers in Category Permissions
3.Save the category and reindex 
4.Verify the behaviour for not logged in customers 


Please refer the attached screenshot and let us if we are missing something.

Catalog->Categories->Selected a category

<img width="1429" alt="Screenshot 2024-05-13 at 3 32 10 PM" src="https://github.com/magento/magento2/assets/51681379/68e92d09-b93f-4906-8d0d-08740707f204">

For Not Logged in customers it is allowed 

<img width="1440" alt="Screenshot 2024-05-13 at 3 54 01 PM" src="https://github.com/magento/magento2/assets/51681379/2bb9d05a-3711-4c13-b51f-aa29fcd67ed6">

We can see the category and product available 

<img width="1440" alt="Screenshot 2024-05-13 at 3 57 01 PM" src="https://github.com/magento/magento2/assets/51681379/78987b50-6612-498c-8b25-242a6605d637">

For Not Logged in customers it is saved as not allowed 

<img width="1440" alt="Screenshot 2024-05-13 at 3 54 50 PM" src="https://github.com/magento/magento2/assets/51681379/74f989a1-a62a-43f9-b58d-031bd003266f">

We are not able tp see the category and product available 

<img width="1436" alt="Screenshot 2024-05-13 at 6 02 47 PM" src="https://github.com/magento/magento2/assets/51681379/7c73a6a5-c629-4634-8673-a97c9d065dfa">
