### ISSUE TITLE
Slash as category URL suffix gives 404 error on all category pages

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#3872]
When I set a forward slash as the Category URL Suffix, all category pages show a 404 Not Found page. Using something like "a/" doesn't work either. I've also tried to reindex the indexes manually.

This works as expected in M1, so I guess this is a bug in M2.

**Comment by Joshua34** [comment]
I am facing the same issue entering either "/" or leaving suffix blank.
URL rewrites are being setup by the system correctly in Admin > Marketing > URL Rewrite but not functioning.

**Comment by redelschaap** [comment]
Any update on this?

**Comment by vzabaznov** [comment]
duplicate of #4876

**Comment by redelschaap** [comment]
Not really a duplicate, but as long as the category URL suffix will be fixed in #4876 as well, closing this issue is fine.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70255

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70505
