### ISSUE TITLE
Imposible to reorder configurable products with one checkbox selected custom option

### ISSUE THREAD

**Issue by RetroProgrammist** [magento/magento2#38736]
### Preconditions and environment

- Magento version 2.4.7
- clear install Magento

### Steps to reproduce

1. create Simple product (i used sampledata)
2. Create custom option:
    - Checkbox type
    - Require
    - 1 or 2 option values 
    
  ![screenshot_1](https://github.com/magento/magento2/assets/49781693/44682b84-452b-4a22-823f-fbaa5551aaa0)

3. Go to front, log in
4. Add the product to cart !!WARNING choose only 1 option value, eg. Checkbox 1 on screen above
5. Create an Order
6. Then go to Accaunt and reorder this order

### Expected result

Successful basket creation

### Actual result

We're getting an error
Could not add the product with SKU "24-MB01" to the shopping cart: Some of the selected item options are not currently available.
![screenshot_2](https://github.com/magento/magento2/assets/49781693/7ced4d3c-3500-4cbe-8588-dd7cb5304a7c)

### Additional information

I found out that the problem is that when reordering the option is taken from $buyRequest (vendor/magento/module-catalog/Model/Product/Type/AbstractType.php:583)
`$optionsFromRequest = $buyRequest->getOptions();`
However, it is not interpreted as an array, but as a scalar
![screenshot_3](https://github.com/magento/magento2/assets/49781693/6c0eb9dc-5160-4dc7-9a3c-a90d7dbb18e6)

As a result, when validating \Magento\Catalog\Model\Product\Option\Type\Select::validateUserValue 
and we get an error on line 97.

![screenshot_4](https://github.com/magento/magento2/assets/49781693/b7e151e4-436b-4734-9d8d-69fe142a1e2d)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @RetroProgrammist,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the attached screenshot.


**Steps to reproduce**

- create Simple product (i used sampledata)
- Create custom option:

    -Checkbox type
    -Require
    -1 or 2 option values

- Go to front, log in
- Add the product to cart !!WARNING choose only 1 option value, eg. Checkbox 1 on screen above
- Create an Order
- Then go to Accaunt and reorder this order




<img width="1435" alt="Screenshot 2024-05-17 at 17 08 25" src="https://github.com/magento/magento2/assets/51680745/9ce2b5cf-27be-4f1e-bb90-1942f0548ae1">


We're getting an error  Some of the selected item options are not currently available.


Hence Confirming the issue.

Thanks.

**Comment by Usmanbashir123** [comment]
Facing the same issue in Magento2.4.5p2 Cloud

**Comment by rendyep** [comment]
Confirmed in 2.4.5-p8 Enterprise with different error message.
![image](https://github.com/user-attachments/assets/69e21f88-c0d1-4a9f-a824-fb8c01509c80)

**Comment by rendyep** [comment]
These 2 lines of code fixes the issue. Tested in 2.4.5-p8.

```
diff --git a/vendor/magento/module-catalog/Model/Product/Option/Select.php b/vendor/magento/module-catalog/Model/Product/Option//Select.php
index 286fa39..b0db2f3 100644
--- a/Select.php
+++ b/Select.php
@@ -99,6 +99,8 @@ class Select extends \Magento\Catalog\Model\Product\Option\Type\DefaultType
         if (!$this->_isSingleSelection()) {
             if (is_string($value)) {
                 $value = explode(',', $value);
+            } else {
+                $value = [$value];
             }
             $valuesCollection = $option->getOptionValuesByOptionId($value, $this->getProduct()->getStoreId())->load();
             $valueCount = is_array($value) ? count($value) : 0;
```

**Comment by Usmanbashir123** [comment]
This can be fixed this Creating the Custom Patch 

```
diff --git a/vendor/magento/module-catalog/Model/Product/Option/Type/Select.php b/vendor/magento/module-catalog/Model/Product/Option/Type/Select.php
index 3ee2rd..8349152 111644
--- a/vendor/magento/module-catalog/Model/Product/Option/Type/Select.php
+++ b/vendor/magento/module-catalog/Model/Product/Option/Type/Select.php
@@ -101,7 +101,7 @@
                 $value = explode(',', $value);
             }
             $valuesCollection = $option->getOptionValuesByOptionId($value, $this->getProduct()->getStoreId())->load();
-            $valueCount = is_array($value) ? count($value) : 0;
+            $valueCount = is_array($value) ? count($value) : 1;
             if ($valuesCollection->count() != $valueCount) {
                 $this->setIsValid(false);
                 throw new LocalizedException( 
```

**Comment by lucafuser** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @RetroProgrammist,

Adobe Commerce Engineering team started working on this issue. We will reach out to you if we need more information and you will get notified once the issue is fixed. Please leave comments for any further questions. 

Thank you!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11970 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11970&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
