### ISSUE TITLE
PHP version not detecting even after changing populate_always to -1

### ISSUE THREAD

**Issue by sachinsancheti1** [magento/magento2#3874]
I am trying to run the component manager but unable to proceed further. I have already changed the value for always_populate_raw_post_data = -1 but in vain to get this running. I also tried restarting apache as well but no progress. Would appreciate your assistance.

![cron fixed but php problem](https://cloud.githubusercontent.com/assets/6279770/13978165/e8f2e74c-f0f4-11e5-98d7-ff9aa9612704.jpg)

![always_populate_raw_post_data](https://cloud.githubusercontent.com/assets/6279770/13978169/ecc04540-f0f4-11e5-8145-f34e1f20ca0e.jpg)

**Comment by mazhalai** [comment]
@sachinsancheti1 it looks to be like some other issue since the php version is also not showing up correctly. Anything in your var directory?

**Comment by sachinsancheti1** [comment]
hi Mazhalai, attached is the link to the _installdir_/php/var/ folder has 2 sub directories
- /run
- /log

I tried investigating in but permission was denied even to the root user....would phpinfo() help? Attached is the file.

[phpinfo.pdf](https://github.com/magento/magento2/files/186544/phpinfo.pdf)

**Comment by unfunco** [comment]
@sachinsancheti1 Have you tried running `composer install`? The PHP readiness check within Magento uses `Composer\Package\Version\VersionParser` and since the values aren't showing in your screenshot, it could be a result of the dependency not being installed.

**Comment by sachinsancheti1** [comment]
Hi @unfunco, thanks for the reply. As for composer, I tried the following:

I first updated composer

```
bitnami@vmdepot-magen:~$ which composer
/opt/bitnami/php/bin/composer
bitnami@vmdepot-magen:~$ sudo /opt/bitnami/php/bin/composer.phar self-update
Updating to version 95c263284a9a47c63279934b398c53f080624606.
    Downloading: 100%
Use composer self-update --rollback to return to version a8e9df55dc62d8806360be2f79ad112b8678d397
```

When I tried the `sudo composer install` i received the following warning

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

So then i ran the  following:

```
bitnami@vmdepot-magen:/opt/bitnami/apps/magento/htdocs$ sudo composer update
```

The results of the following is in the attached [link](https://raw.githubusercontent.com/sachinsancheti1/magento-error/master/composer%20update%20command.txt) and then ended up with the autoload error. How do i proceed from here?

![image](https://cloud.githubusercontent.com/assets/6279770/14065930/5b7c1596-f45a-11e5-8daa-90dd9340bb96.png)

**Comment by mazhalai** [comment]
@sachinsancheti1 how did you deploy magento? via git or via composer create-project or via zip downloaded from magento.com?

**Comment by sachinsancheti1** [comment]
Hi @mazhalai, i used the bitnami stack on azure. I realized i missed out a crontab task
   `*/1 * * * * /opt/bitnami/php/bin/php -c /opt/bitnami/php/etc/php.ini /opt/bitnami/apps/magento/htdocs/bin/magento cron:run`

thanks for the support
