### ISSUE TITLE
Non-Static Customer Custom Attribute Are Always Updated When Using Customer Repository to Save

### ISSUE THREAD

**Issue by NateSwanson7** [magento/magento2#38753]
### Preconditions and environment

- 2.4.7
- At least one non-static custom attribute for the customer entity

### Steps to reproduce

1. Create a non-static customer custom attribute (e.g. `my_custom_attribute`)
2. Set `my_custom_attribute` to any value and save
3. Enable DB profiling
4. Load up the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface`)
5. Without changing any value save the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface::save()`)
6. Check DB profiling results
7. Notice a query to insert the value that was already saved and set for your custom attribute `my_custom_attribute` even though the original value does not differ from the new value

### Expected result

DB query to insert/update the value of the custom attribute is not created or ran because the value has not changed.

### Actual result

DB query to insert/update the value of the custom attribute is created and ran even though the value does not differ.

### Additional information

This can end up causing database deadlocks when the unnecessary insert/update query is ran which locks the row. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by NateSwanson7** [comment]
@magento give me 2.4-develop instance

**Comment by NateSwanson7** [comment]
@magento I am working on this

**Comment by NateSwanson7** [comment]
@magento add to contributors team

**Comment by NateSwanson7** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Hello @NateSwanson7,

Thank you for the report and collaboration!

We followed your steps to reproduce and created a not static customer custom attribute `custom_field`, but when saving the customer without changing any value led to below query:
```
SQL: INSERT  INTO `customer_grid_flat` (`entity_id`,`name`,`email`,`group_id`,`created_at`,`website_id`,`confirmation`,`created_in`,`dob`,`gender`,`taxvat`,`lock_expires`,`custom_field`,`shipping_full`,`billing_full`,`billing_firstname`,`billing_lastname`,`billing_telephone`,`billing_postcode`,`billing_country_id`,`billing_region`,`billing_region_id`,`billing_street`,`billing_city`,`billing_fax`,`billing_vat_id`,`billing_company`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `email` = VALUES(`email`), `group_id` = VALUES(`group_id`), `created_at` = VALUES(`created_at`), `website_id` = VALUES(`website_id`), `confirmation` = VALUES(`confirmation`), `created_in` = VALUES(`created_in`), `dob` = VALUES(`dob`), `gender` = VALUES(`gender`), `taxvat` = VALUES(`taxvat`), `lock_expires` = VALUES(`lock_expires`), `custom_field` = VALUES(`custom_field`), `shipping_full` = VALUES(`shipping_full`), `billing_full` = VALUES(`billing_full`), `billing_firstname` = VALUES(`billing_firstname`), `billing_lastname` = VALUES(`billing_lastname`), `billing_telephone` = VALUES(`billing_telephone`), `billing_postcode` = VALUES(`billing_postcode`), `billing_country_id` = VALUES(`billing_country_id`), `billing_region` = VALUES(`billing_region`), `billing_region_id` = VALUES(`billing_region_id`), `billing_street` = VALUES(`billing_street`), `billing_city` = VALUES(`billing_city`), `billing_fax` = VALUES(`billing_fax`), `billing_vat_id` = VALUES(`billing_vat_id`), `billing_company` = VALUES(`billing_company`)
BIND: array (
  0 => 1,
  1 => 'test test',
  2 => 'test@mail.com',
  3 => '1',
  4 => '2024-05-28 06:21:45',
  5 => '1',
  6 => NULL,
  7 => 'Default Store View',
  8 => NULL,
  9 => '0',
  10 => NULL,
  11 => NULL,
  12 => 'test data',
  13 => '',
  14 => '',
  15 => NULL,
  16 => NULL,
  17 => NULL,
  18 => NULL,
  19 => NULL,
  20 => NULL,
  21 => NULL,
  22 => NULL,
  23 => NULL,
  24 => NULL,
  25 => NULL,
  26 => NULL,
)
AFF: 1
TIME: 0.0008
```

We did not see a DB query specific to Customer Custom Attribute.

Please find the custom module used to reproduce this issue, and let us know if we are missing anyting.
[I38753V.zip](https://github.com/magento/magento2/files/15484867/I38753V.zip)

Thank you.

**Comment by NateSwanson7** [comment]
@engcom-November I'll double check the steps I provided when I get a bit of time later this week. 

Thanks

**Comment by sdouma** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by sdouma** [comment]
@magento give me 2.4.4-p8 instance

**Comment by sdouma** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hello @NateSwanson7,

Can you give us any updates on this.

**Comment by NateSwanson7** [comment]
> Hello @NateSwanson7,
> 
> Can you give us any updates on this.

@engcom-November I can't seem to reproduce this now, feel free to close this issue.
