### ISSUE TITLE
logout issue when using Graphql

### ISSUE THREAD

**Issue by estellehuang** [magento/magento2#38761]
### Preconditions and environment

- Magento version 2.4.6-p5

### Steps to reproduce

Using Graphql
1. login on frontend
2. logout
3. login again

### Expected result

Customer could login successfully

### Actual result

The following error message display:

The current user cannot perform operations on cart "QXJscogXHdkTyJLXK0OcItaEByrGivCg"

### Additional information

I made some investigation. I found even I logged out. When calling API createEmptyCart, the userid used to create cart is the userid I loged in last time instead of guest 0. The version 2.4.4-p2 doesn't has the issue. I found there is new feature for Graphql. That is disabling session for graphql. But in admin panel, I can't find the area to config it. Graphql session is enabled in default configuration. After I disabled it by changing code, my issue could disappear. I could login and logout without any issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by estellehuang** [comment]
Hi,

Any progress on this issue?

**Comment by engcom-Delta** [comment]
Hi @estellehuang ,

Thanks for reporting and collaboration.

We have tried to verify this issue on magento 2.4-develop instance and it is not reproducible.

Steps to reproduce:-

1.login on frontend
2.logout
3.login again

Please check the video attached and let us know if we missed anything.

We are not getting any errors while logging in again.


https://github.com/magento/magento2/assets/51681379/861abee7-2321-46e4-8127-7879318d3187

**Comment by engcom-Delta** [comment]
Hi @estellehuang ,

Awaiting your reply on this issue to move further.

Thanks,

**Comment by vanmelick** [comment]
For those looking for a solution to disable graphql sessions:
bin/magento config:set graphql/session/disable 1
bin/magento cache:flush
