### ISSUE TITLE
Nested GraphQL fragments are not processed by the Catalog Attribute Joiner

### ISSUE THREAD

**Issue by pmzandbergen** [magento/magento2#38762]
### Preconditions and environment

- Magento 2.4.7

### Steps to reproduce

Using a GraphQL fragment inside another fragment does not work. Example query:
```graphql
query {
  products(filter: { sku: { eq: "example-product" } }) {
    items {
      ... on ProductInterface {
        ...ProductInterfaceFragment
      }
    }
  }
}
fragment ProductFragment on ProductInterface {
  sku
  ...AnotherProductFragment
}
fragment AnotherProductFragment on ProductInterface {
  url_key
}
```

In this case the Attribute Joiner (`Magento\CatalogGraphQl\Model\AttributesJoiner`) will return the following fields:
- `sku`
- `AnotherProductFragment` (which is not a field, its a fragment)

The result will not return a value for `url_key`, since the attribute is not queried.

### Expected result

The result will include the fields from all (nested) fragments (`sku` and `url_key` in this example).

### Actual result

The result includes only the fields from the first (not nested) fragment, `url_key` is undefined.

### Additional information

I'll create a PR fixing the Attribute Joiner to support nested fragments.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @pmzandbergen,

Thanks for your reporting and collaboration.

We have verified the issue in Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1438" alt="Screenshot 2024-05-29 at 16 10 17" src="https://github.com/magento/magento2/assets/51680745/4ce64975-3c15-490b-b632-6b791f80b53c">


The result included the fields from all (nested) fragments (sku and url_key)

Thanks.
