### ISSUE TITLE
M2.4.7 Failed to find 'integrity' attribute SHA-256

### ISSUE THREAD

**Issue by arhmart** [magento/magento2#38780]
### Preconditions and environment

- M2.4.7

### Steps to reproduce

After advanced js bundling, the browser console shows:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.example.com/static/version1717141655/frontend/Magento/luma/en_US/requirejs/require.js' with computed SHA-256 integrity '4QFGq+dSeO9OwpP9J/BwCjBNCX8o6LfiGtxseRO+0XU='. The resource has been blocked.

I googled for a long time and thought this problem might be caused by CSP.

Does anyone know how to solve it?

Thanks!

### Expected result

Everything is go well

### Actual result

Everything is go bas

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by iphigenie** [comment]
how did you solve it?

**Comment by Valueshop** [comment]
@iphigenie - Same for me, disabling minify solved the problem. Haven't looking more into it since Minify will be deprecated soon from CF anyways.
