### ISSUE TITLE
observer.customer_register_success event emits null customer object from Magento Cloud

### ISSUE THREAD

**Issue by leojlu88** [magento/magento2#38787]
### Preconditions and environment

Magento CLI 2.4.6-p5

### Steps to reproduce

We followed the steps on this page https://developer.adobe.com/commerce/extensibility/events/configure-commerce/ to set up I/O Events.  We subscribed and registered both observer.customer_register_success and observer.customer_save_commit_after events.  observer.customer_save_commit_after is working fine, but observer.customer_register_success events has null for the customer object. Here is the paylaod:
{
    "data": {
        "key": "xxx",
        "value": {},
        "source": "xxx",
        "_metadata": {
            "commerceEdition": "Adobe Commerce",
            "commerceVersion": "2.4.6-p5",
            "eventsClientVersion": "1.7.0",
            "storeId": "1",
            "websiteId": "1",
            "storeGroupId": "1"
        }
    },
    "id": "xxx",
    "source": "xx",
    "specversion": "1.0",
    "type": "com.adobe.commerce.observer.customer_register_success",
    "datacontenttype": "application/json",
    "time": "2024-06-02T07:47:04.256Z",
    "event_id": "xxx",
    "recipient_client_id": "xxx"
}

We have the ie_events.xml in app/etc
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module-commerce-events-client/etc/io_events.xsd">
    <event name="observer.customer_register_success">
        <fields>
            <field name="entity_id" />
        </fields>
    </event>
    <event name="observer.customer_save_commit_after">
        <fields>
            <field name="entity_id" />
        </fields>
    </event>
</config>

### Expected result

customer object emitted from the observer.customer_register_success event should have customer entity_id

### Actual result

customer object from the observer.customer_register_success event is null

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by naomirobichaud** [comment]
@leojlu88 team is looking into this, thanks for reporting

**Comment by engcom-Hotel** [comment]
We are moving this issue `On hold` until further updates.

**Comment by ryanjcohen** [comment]
Hi @leojlu88, we've included a fix for this issue in [commerce-eventing 1.8.0](https://developer.adobe.com/commerce/extensibility/events/release-notes/#version-180)

**Comment by engcom-Hotel** [comment]
Thanks @ryanjcohen for the information. We are closing this issue.
