### ISSUE TITLE
Customer Welcome message not showing

### ISSUE THREAD

**Issue by shinethazhava** [magento/magento2#3879]
When a user login customer welcome message on top section not showing.
After add any product to cart using  ajax cart  then showing customer full name.
`<span data-bind="text: customer().fullname"></span>`
Screenshot Error : 
![screenshot-error](https://cloud.githubusercontent.com/assets/6826291/13984432/34cda9c8-f11c-11e5-8e2c-7e7d0dbd69f8.png)
Screenshot Success : 
![screenshot-sucess](https://cloud.githubusercontent.com/assets/6826291/13984443/47917d78-f11c-11e5-89ed-3808b6585e0f.png)

**Comment by devhn** [comment]
Same as [#3572](https://github.com/magento/magento2/issues/3572)

**Comment by minhluan259** [comment]
Same issue
vendor\magento\module-theme\view\frontend\templates\html\header.phtml

```
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
            <!-- /ko -->
        </li>
```

When customer loged in , customer().fullname return false

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by nitinpawar45** [comment]
Any one solved this issue, I am facing the same problem.

**Comment by VinayJVNC** [comment]
Hi,
 I'm also facing almost the same issue. Few users are able to see their names and few are not able to.
Users who are not able to see their username are also unable to add the products to cart. Is it related anywhere to the sessions? I have debugged the entire code, but failed to get the expected result.
Can anyone help to fix this. Thanks in advance

**Comment by 91ranjan** [comment]
Any one got any solution for this yet.

**Comment by ghost** [comment]
I've faced this issue after enabling varnish. Anyone solved this issue.

**Comment by KiranLankapalli** [comment]
Hi,
Not displaying the customer name and welcome message when open hambuger menu.
Module Amasty_MegamenuLite:web/template/components/header.html

`<p class="ammenu-menu-header"
   data-bind="
        style: {
            background: color_settings.category_hover_color
        },
        scope: 'customer'">

    
        <span class="ammenu-message -welcome" data-bind="i18n: 'Welcome'"></span>
        <span class="ammenu-name" data-bind="text: customer().fullname"></span>
    

    
        <span class="ammenu-message" data-bind="i18n: $parent.welcome_message().message"></span>
    
</p>`

![Screenshot from 2021-10-19 12-33-13](https://user-images.githubusercontent.com/90908119/137860049-d8e8e03a-6efa-4568-9ac9-f1db9dcdb733.png)
