### ISSUE TITLE
Theme compilation breaks when mysql host contains port information

### ISSUE THREAD

**Issue by FilipeBicho** [magento/magento2#38799]
### Preconditions and environment

- Magento 2.4.7
- PHP 8.3

### Steps to reproduce

1. Go to `env.php`
1. Set the port information to the host in the db connection. e.g. `db<'connection']['default']['host'] = 'localhost:3306'`
1. Execute  `./magento.sh setup:static-content:deploy`

### Expected result

The theme is deployed

### Actual result

Exception: 
`Port must be configured within host parameter (like localhost:3306 in /var/www/lehner_dev/src/www/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:464`

### Additional information

Possible solution:
``{{
diff --git a/DB/Adapter/Pdo/Mysql.php b/DB/Adapter/Pdo/Mysql.php
--- a/DB/Adapter/Pdo/Mysql.php	(revision 2dc0b58888392ed5304ac6ad02e36a70e6e490a2)
<ins></ins><ins> b/DB/Adapter/Pdo/Mysql.php	(date 1717577596939)
@@ -432,6 </ins>432,11 @@
             $this->parentConnections[] = $this->_connection;
             $this->_connection = null;
             $this->pid = getmypid();
<ins>            if (isset($this->*config['port']) && !str_contains($this->*config['host'], '/')) {
</ins>                if (!str*contains($this->*config['host'], ':'))
<ins>                    $this->*config['host'] .= ':' . $this->*config['port'];
</ins>                unset($this->_config['port']);
+            }
         }
     }
}}``

### Release note

*No response*

### Triage and priority

- [ ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

**Comment by engcom-Delta** [comment]
Hi @FilipeBicho ,

Thanks for reporting and collaboration.

Verified the issue in magento 2.4-develop and 2.4.7 instance and the issue is not reproducible.

Steps to reproduce:-

1.Go to app-> etc->env.php
2.Set the port information to the host in the db connection. e.g. db['connection']['default']['host'] = 'localhost:3306'
3.Execute php bin/magento setup:static-content:deploy

Please refer the attached screenshots and let us know if we missed anything.


<img width="1439" alt="Screenshot 2024-06-07 at 12 46 00 AM" src="https://github.com/magento/magento2/assets/51681379/779c416e-9149-4c32-b02d-e93590dcdc53">

No error 

<img width="950" alt="Screenshot 2024-06-07 at 1 40 51 AM" src="https://github.com/magento/magento2/assets/51681379/00de40c9-ea95-4b96-b246-21c60d0271d5">

**Comment by engcom-Delta** [comment]
Hi @FilipeBicho  ,

Verified the issue on 2.4.7 and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1.Flush the Magento cache, e.g. bin/magento c:f
2.Go to app-> etc->env.php
3.Set the port information to the host in the db connection. e.g. db['connection']['default']['host'] = 'localhost:3306'
4.bin/magento setup:static-content:deploy --force --strategy standard --jobs 4

Flush the Magento cache

<img width="817" alt="Screenshot 2024-06-18 at 8 04 33 PM" src="https://github.com/magento/magento2/assets/51681379/6b9e51c5-41a3-4363-b4ed-d6439b53dcd5">

Set the port information to the host in the db connection. e.g. db['connection']['default']['host'] = 'localhost:3306'

<img width="1000" alt="Screenshot 2024-06-18 at 8 05 22 PM" src="https://github.com/magento/magento2/assets/51681379/b653135a-52b7-443a-bcef-f96c094fd038">

Run bin/magento setup:static-content:deploy --force --strategy standard --jobs 4

<img width="1428" alt="Screenshot 2024-06-18 at 8 06 26 PM" src="https://github.com/magento/magento2/assets/51681379/b0f43583-c8f3-4128-9575-8b78d3219c59">

**Comment by mrodespin** [comment]
I opened a PR to fix this issue -> https://github.com/magento/magento2/pull/38842

**Comment by falko100** [comment]
Encountered the same problem. PR works for me.
