### ISSUE TITLE
Instant purchase "cheapest shipping" broken for configurable products

### ISSUE THREAD

**Issue by Tomasito665** [magento/magento2#38811]
#### (1) Install magento
* Do a composer-based installation of magento 2.4.7. We need the [magento/inventory](https://github.com/magento/inventory) modules for in-store delivery, which are not part of the core magento repository but are automaticallMore colorsy included for composer-based installations.

* Deploy sample data into your Magento installation. The steps described in this issue assume this sample data to be installed. See <https://github.com/magento/magento2-sample-data> for more info.

* Install the [magento-instant-purchase-mock](https://github.com/Tomasito665/magento-instant-purchase-mock/tree/main] extension. This extension was designed specifically for this issue and does minimal surgical changes to magento's `InstantPurchase` module to enable the `Instant Purchase` button without installing and configuring [Payment Services|https://experienceleague.adobe.com/en/docs/commerce-merchant-services/payment-services/guide-overview] or [Braintree|https://experienceleague.adobe.com/en/docs/commerce-admin/stores-sales/payments/braintree), which is normally required for enabling instant purchase functionality but is not necessary for the demonstration of this bug.

#### (2) Set up in-store delivery
* Enable in-store pickup
  * In the admin page, go to Stores → Configuration → Sales → Delivery Methods → In-Store Delivery.
  * Set Enabled to Yes.

* Create in-store pickup source
  * In the admin page, go to Stores → Inventory → Sources.
  * Click on Add New Source, and fill in the following.
    * Name: ISPU source
    * Code: ispu_source
    * Is Enabled: Yes
    * Description: ISPU source
    * Latitude: 30.258726
    * Longitude: -97.753063
    * Use As Pickup Location: Yes
    * Contact Name: ISPU
    * Email: ispu_source@hotmail.com
    * Phone: 123456789
    * Country: United States
    * State/Province: Texas
    * City: Austin
    * Street: 123 Test St
    * Postcode: 78758
    * Pickup Name: ISPU
    * Frontend Description: ISPU
  * Click on Save & Continue.

* Create in-store pickup stock
  * In the admin page, go to Stores → Inventory → Stocks.
  * Click on Add New Stock, and fill in the following.
    * Name: ISPU stock
    * Websites: Main Website
    * Assign Sources: ISPU source
  * Click on Save & Continue.

#### (3) Enable products for in-store pickup
* Assign simple product to ISPU source
  * In the admin page, go to Catalog → Products.
  * Find the Joust Duffle Bag (should be the first product) and click on Edit.
  * Under Sources, click on Assign Sources.
  * Select the ISPU source and click on Done.
  * Set the ISPU source to In stock and Qty to 100.
  * Click on Save.

* Assign configurable product to ISPU source
  * In the admin page, go to Catalog → Products.
  * In the Search by keyword textbox, fill in “Chaz Kangeroo Hoodie” and press Enter.
  * Click on the checkbox in the table header and click on Select All — should select 16 records.
  * Under Actions, click on Transfer Inventory to Source, and fill in.
    * Transfer from the origin source: Default Source
    * To the destination source: ISPU source
    * Unassign the origin source from selected products after transfer: No
  * Click on Transfer Inventory.

#### (4) Configure flat rate as the cheapest option
* In the admin page, go to Stores → Configuration → Sales → Delivery Methods.
* Under Flat Rate, make sure that Enabled: Yes, and Price: 5.00 (= default values).
* Under In-Store Delivery, set Price to 6.00, i.e., more expensive than Flat Rate.

#### (5) Create a customer account
* On the frontend page, click on Create an Account to create a customer account.

* Once logged in, go to My Account → Address Book → Default Billing Address.

* Click on Edit Address and fill in the following.
  * First Name: John
  * Last Name: Smith
  * Phone Number: 123456789
  * Street Address: 123 Test St
  * Country: United States
  * State/Province: Texas
  * City: Austin
  * Zip/Postal Code: 78758

* Make sure that the address appears both as:
  * Default Billing Address
  * Default Shipping Address

* Log out and log in again to refresh instant purchase options.

#### (6) Verify that in-store delivery is available

Try purchasing a Joust Duffle Bag and a Chaz Kangeroo Hoodie through the checkout flow using in-store delivery. We assigned stock for both products to our in-store delivery source in step 3. Thus, in-store delivery should be available for both. Furthermore, we configured in-store delivery to cost 6$, which is more expensive than the 5$ flat-rate shipment method. These prices should show on the checkout page as seen in the screenshots below.
|Simple product checkout|Configurable product checkout|
|----------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
|<img width="450" alt="Step6*CheckoutSimpleProduct" src="https://github.com/magento/magento2/assets/12563382/1e958571-5559-4116-a338-d893951735db">|<img width="450" alt="Step6*CheckoutConfigurableProduct" src="https://github.com/magento/magento2/assets/12563382/beeea547-d93c-4203-ad42-e41b27229ec1">|
#### (7) Verify that instant purchase is available

Open any product detail page and ensure that the `Instant Purchase` button renders. If it does not, make sure that the [Magento_InstantPurchaseMock](https://github.com/Tomasito665/magento-instant-purchase-mock/blob/main/app/code/Magento/InstantPurchaseMock/registration.php) module is correctly installed and enabled as described in step 1. Also, the `Instant Purchase` button only renders if you are logged in as a customer and if that customer has both a default billing and a default shipping address. Make sure these addresses are properly configured as described in step 5.
|Instant Purchase button|
|-----------------------------------------------------------------------------------------------------------------------------------------------------|
|<img width="1319" alt="Step7_InstantPurchaseButton" src="https://github.com/magento/magento2/assets/12563382/5878ea5e-e4fb-41f9-8be7-b459d0ebb54f">|
### Steps to reproduce
* On the frontend page, make sure you are logged in with the previously created customer account.
* Click on the “Search entire store here…” textbook, type “Chaz Kangeroo Hoodie”, and press Enter.
* There should be only one result. Click on it to open the product details page for “Chaz Kangeroo Hoodie”.
* Click on the Instant Purchase button. You’ll see a confirmation popup with Shipping Method: Cheapest price.
* Click on OK to confirm the purchase.

### Expected result

The order is placed using the cheapest shipment method, which, as we saw in step 6, is the $5.00 Flat Rate shipment method.

<img width="1124" alt="Expected behavior" src="https://github.com/magento/magento2/assets/12563382/541e573b-0e3a-4174-b066-1f1c4f99160f"]
### Actual result

The order is placed using the $6.00 In-Store Delivery shipment method, which is NOT the cheapest shipment method.
{quote}[!NOTE]
{quote}
{quote}As seen in the screenshot, with my setup, the order placement does not finish successfully and ends with a "Quote does not have Pickup Location assigned" error. The cause of this error is irrelevant to the bug described in this issue. However, the fact that it gives *this* error in particular shows that the instant purchase flow attempts to place the order using the In-Store Delivery shipment method, which is sufficient to demonstrate the bug.
{quote}
[img width="1136" alt="ActualBehavior_2of2" src="https://github.com/magento/magento2/assets/12563382/bce0144a-5faf-4f2e-9487-4da90f8315df">
#### It works for simple products

While the "cheapest price" shipment method does not work for configurable products, it does work for simple products—see screenshots below.
|For simple products ...|... it works|
|-----------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
|<img width="1115" alt="ExpectedBehavior*1of2" src="https://github.com/magento/magento2/assets/12563382/3a1221de-0c49-4ea3-a3f0-0c73731c641b">|<img width="1138" alt="ExpectedBehavior*2of2" src="https://github.com/magento/magento2/assets/12563382/c5dedf1d-5fac-484b-b8e3-e25336a6ea6a">|
#### Flat rate counted double for configurable products 🐛

The "cheapest price" shipment method is calculated in the [CheapestMethodDeferredChooser](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/CheapestMethodDeferredChooser.php) class in the following method. The $5.00 Flat Rate shipping is not correctly identified as the cheapest option because, for reasons unclear to me, its price is doubled when performing the comparison to the $6.00 In-Store Delivery.
<https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/CheapestMethodDeferredChooser.php#L35-L50]

When debugging the instant purchase of the Joust Duffle Bag simple product, we see that the `$shippingRates` array contains the following rates.

``{{javascript
[
{_data:
```
Unable to find source-code formatter for language: "flatrate_flatrate", carrier: "flatrate", price: 5.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml{code}
, ...},
{_data:
{code}
Unable to find source-code formatter for language: "instore_pickup", carrier: "instore", price: 6.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml{code}
, ...},
{_data:
{code}
Unable to find source-code formatter for language: "tablerate_bestway", carrier: "tablerate", price: 15.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml{code}
, ...},
]
}}``

However, when debugging the instant purchase of some permutation of the Chaz Kangeroo Hoodie configurable product, we see that the `$shippingRates` array contains different rates—double flat rate price.

``{{javascript
[
{_data:
{code}
Unable to find source-code formatter for language: "instore_pickup", carrier: "instore", price: 6.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml{code}
, ...},
// twice the 5.00 flat rate shipment method item price for only 1 item 💥👇
{_data:
{code}
Unable to find source-code formatter for language: "flatrate_flatrate", carrier: "flatrate", price: 10.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml{code}
, ...},
{_data:
{code}
Unable to find source-code formatter for language: "tablerate_bestway", carrier: "tablerate", price: 15.0, .... Available languages are: actionscript, ada, applescript, bash, c, c#, c<ins></ins>, cpp, css, erlang, go, groovy, haskell, html, java, javascript, js, json, lua, none, nyan, objc, perl, php, python, r, rainbow, ruby, scala, sh, sql, swift, visualbasic, xml, yaml```
, ...},
]
}}``

In this case, Flat Rate costs not the expected $5.00 but $10.00, which is indeed not the cheapest option anymore. In that case, the $6.00 In-Store Delivery shipment is the cheapest method, which explains why the instant purchase flow attempts to place the order using in-store delivery. I believe that the crux of the issue boils down to why the price is doubled for configurable products. It clearly shouldn't. Even though for configurable products there are two items (parent and child), there is only one item shipped (= child). So, the Flat Rate item price should be $5.00, not $10.00.
### Release note

```
"magento/product-community-edition": "2.4.7"
```
### Triage and priority
 - [ ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [X] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by Tomasito665** [comment]
I found the issue. The instant purchase [PlaceOrder::placeOrder()](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/InstantPurchase/Model/PlaceOrder.php#L83-L137) method:

1. Uses the instant purchase [QuoteCreation::createQuote](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/InstantPurchase/Model/QuoteManagement/QuoteCreation.php) method to create an "empty" quote, i.e., with store id, customer, shipping address, and billing address, but without products.

https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/InstantPurchase/Model/PlaceOrder.php#L103-L108

2. Uses the instant purchase [QuoteFilling::fillQuote](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/InstantPurchase/Model/QuoteManagement/QuoteFilling.php) method to add the product to the quote.

https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/InstantPurchase/Model/PlaceOrder.php#L109-L113

3. Calls the [Quote::collectTotals()](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote.php#L2030-L2046) to compute the quote price.

https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/InstantPurchase/Model/PlaceOrder.php#L115

So far, so good. However, if we take a closer look at [QuoteCreation::createQuote](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/InstantPurchase/Model/QuoteManagement/QuoteCreation.php), we see that it assigns the shipping and billing address to the quote, but does not flag them for rate recalculation before totals collection, i.e., does not call [setCollectShippingRates(true)](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote/Address.php#L67) before [Quote::collectTotals()](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote.php#L2030-L2046). It does so, but further down the pipeline when choosing the cheapest method—after having collected the totals already.

https://github.com/magento/magento2/blob/e81f28e4e6739924594c266b011c68b08a227c2d/app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/CheapestMethodDeferredChooser.php#L21-L25

If we set [setCollectShippingRates(true)](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote/Address.php#L67) before [Quote::collectTotals()](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote.php#L2030-L2046), then shipping rates are collected correctly as part of the "collect totals" operation. Diving into the code that calculates quote address totals, we see that it sets some "magic" fields immediately before collecting shipping rates.

https://github.com/magento/magento2/blob/e81f28e4e6739924594c266b011c68b08a227c2d/app/code/Magento/Quote/Model/Quote/Address/Total/Shipping.php#L87-L92

Take the "item qty" field. The abovementioned code snippet computes the number of "sendable" items and assigns that value to the address "item qty" field. I call this a "magic" field because it is never persisted in the database. Its only purpose, as far as I can tell, is to provide a way to override the return value of [Address::getItemQty](https://github.com/magento/magento2/blob/e81f28e4e6739924594c266b011c68b08a227c2d/app/code/Magento/Quote/Model/Quote/Address.php#L719-L744), which would normally "simply" return the sum of the item quantities, regardless of whether those are sendable.

https://github.com/magento/magento2/blob/e81f28e4e6739924594c266b011c68b08a227c2d/app/code/Magento/Quote/Model/Quote/Address.php#L725-L735

This is what makes shipping rate calculation work when called within the context of collecting totals. It overrides the address item quantity with the "sendable" quantity, which is the correct quantity in the context of computing shipping rates. With instant purchase, however, the sendable quantity is not set, and rates are computed incorrectly when choosing "cheapest shipping." In summary:

1. The correct shipping rates are correctly computed as part of the call to [Quote::collectTotals()](https://github.com/magento/magento2/blob/001e5188cd59309f5de9205946ede5ddccdadaff/app/code/Magento/Quote/Model/Quote.php#L2030-L2046) but not retained as the "collect shipping rates" flags are not set at that point.

2. The [CheapestMethodDeferredChooser](https://github.com/magento/magento2/blob/e81f28e4e6739924594c266b011c68b08a227c2d/app/code/Magento/InstantPurchase/Model/ShippingMethodChoose/CheapestMethodDeferredChooser.php#L23-L25) sets the "collect shipping rates" flags and calls `collectShippingRates()` to compute the shipping rates. However, it does not specify the "sendable" items when doing so, and rates are computed incorrectly.

As a straightforward solution, I propose to:

* Set the "collect shipping rates" flag to true when creating the instant purchase quote to retain the correct rates.
* Leverage the correctly computed rates from collect totals in "cheapest method choosing".

**Comment by engcom-Bravo** [comment]
Hi,

Internal team has started to work on it 

Thanks

**Comment by engcom-Hotel** [comment]
As the internal team has started working on it, we are moving this issue to `on hold` until we receive further updates. We will provide updates on this issue as they become available.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12119 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12119-v1&type=commits

Thanks.
