### ISSUE TITLE
PHP mcrypt extension to be removed in PHP 7.1

### ISSUE THREAD

**Issue by djmattyg007** [magento/magento2#3881]
As per [this post](http://news.php.net/php.internals/91853) in the PHP internals mailing list, the vote to remove the mcrypt extension from PHP has passed. Unfortunately, Magento 2 still makes use of mcrypt, despite it long being known as being abandonware:

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Encryption/Crypt.php

How is Magento planning on handling the migration to something other than mcrypt?

**Comment by Vinai** [comment]
Suggestion: [libsodium](https://paragonie.com/book/pecl-libsodium/read/00-intro.md)
Related: [The State of Cryptography in PHP ](https://paragonie.com/blog/2015/09/state-cryptography-in-php)

**Comment by maxbucknell** [comment]
Looks like this work is now being tracked in #5701.

**Comment by kandy** [comment]
is duplicate
