### ISSUE TITLE
Grunt Less uses pub/ prefix for sourcemaps

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#38837]
### Summary

When using grunt to generate css, the associated sourcemaps use the prefix pub/ on all urls it generates. This forces the webserver config to employ a workaround to allow pub/ urls to continue to work, just for the sourcemaps. Sourcemaps should not use the pub/ prefix.

### Examples

Deploy Vanilla 2.4.7-p1
> cp Gruntfile.js.sample Gruntfile.js
> php bin/magento deploy:mode:set development
> grunt clean
> grunt exec
> grunt less
> less pub/static/frontend/Magento/luma/en_US/css/styles-l.css.map

Observe the paths include pub/static

Browse to the frontend and inspect an element in the dev console.
Check the location of the less file obtained via the sourcemap

![vDLOkBHE70](https://github.com/magento/magento2/assets/30697781/f200264b-8d35-46d7-8b0e-e5aa911a1afb)

Although this will still work if your nginx config includes the following snippet

https://github.com/magento/magento2/blob/91cb4d46834b88bb8dc9f5b06279a63d9ad0963c/nginx.conf.sample#L98C1-L104C2

But isn't the use of /pub/ urls now unsupported?

### Release note

less/css sourcemaps generated by grunt no longer use the /pub prefix for paths.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @gwharton,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop (latest development branch) and the issue is reproducible for us. Please refer to the below screenshot:

![image](https://github.com/magento/magento2/assets/51681618/f91865dd-82c0-44d3-9e41-40a6239c0750)

Hence confirming the issue.

Thanks
