### ISSUE TITLE
Should I Include Magento Core Tests in My Custom Project Pipeline or Remove the dev/tests Folder?

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#38830]
Hi guys,

I have a small question regarding the experience of running Unit, Functional, and Integration tests of Magento Core for my custom project pipeline. Should I actually include these tests in my pipeline, or are they not necessary, allowing me to remove the `dev/tests` folder to free up some space? Any advice or best practices would be greatly appreciated!

**Comment by engcom-Delta** [comment]
Hi @madonzy ,

Thanks for reporting and collaboration.

As this platform is used to post the bugs/issues related to core Magento libraries ,We can't work on this issue.You may get help from Magento StackExchange.You can follow the link below.

https://magento.stackexchange.com/

Closing this ticket as this is not an issue.

Thanks,
