### ISSUE TITLE
Could not acquire lock for cronjob: xtento_trackingimport_profile_2_cron_1

### ISSUE THREAD

**Issue by MilenV** [magento/magento2#38834]
### Preconditions and environment

Adobe Commerce ver. 2.4.5-p2

### Steps to reproduce

There's a cron job set up for the profile tracking import as xtento_trackingimport_profile_2_cron_1. It normally runs at 8.30 pm and 10.30 pm UK time once it receive the file. Ideally it used to take around 15 mins to execute it.  But we have noticed now it's taking around 1-3 hrs .While we investigated, we have noticed there is one cron error keeps on coming especially during that period as "Could not acquire lock for cron job: "xtento_trackingimport_profile_2_cron_1" which might be causing the delay for the cron job. So can this be checked on priority basis as it's affecting the production environment. 

### Expected result

xtento_trackingimport_profile_2_cron_1 completes on schedule and all files are transferred right on time.

### Actual result

xtento_trackingimport_profile_2_cron_1 does not complete on schedule and all files are NOT transferred at expected timeframe
<img width="1728" alt="Screenshot 2024-05-09 at 10 45 09 AM" src="https://github.com/magento/magento2/assets/41599684/c451d150-df81-4b6c-98a8-1848fb7762bd">
<img width="1728" alt="Screenshot 2024-05-02 at 8 42 19 PM" src="https://github.com/magento/magento2/assets/41599684/e43bc291-7775-49ff-95c1-b9a6a7879c02">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @MilenV,

Thanks for reporting and colloboration.

“xtento” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by MilenV** [comment]
Hello Team,

As far as we got this, you are unable to help us in troubleshooting process.

Regards,
Milen Velinov
