### ISSUE TITLE
"Area code not set" after update to 2.4.5-p8

### ISSUE THREAD

**Issue by dmitryp1993** [magento/magento2#38845]
### Preconditions and environment

- Magento version 2.4.5-p8 or 2.4-develop
- Deployment mode - production
- Magento_CSP module is enabled
- "dev/js/translate_strategy" is set to "embedded"

### Steps to reproduce

Enable Magento_CSP, and set "dev/js/translate_strategy" to "embedded". Than run bin/magento setup:static-content:deploy

### Expected result

Successful finish

### Actual result

Error: Area code not set

![image (12)](https://github.com/magento/magento2/assets/47088535/c642b2fd-e8f3-40ac-9bf9-edc92bd9a5a8)

### Additional information

Exception is triggered in class vendor/magento/framework/Translate.php

```
 /**
     * Initialize translation data
     *
     * @param string|null $area
     * @param bool $forceReload
     * @return $this
     */
    public function loadData($area = null, $forceReload = false)
    {
        $this->_data = [];
        if ($area === null) {
            $area = $this->_appState->getAreaCode();
        }
```

Stack trace 
![image (11)](https://github.com/magento/magento2/assets/47088535/8e1e695a-d49f-4796-a466-f9cfd53f96be)

Possible solution -  emulate area code in vendor/magento/module-deploy/Service/DeployRequireJsConfig.php

```
/**
     * @param string $areaCode
     * @param string $themePath
     * @param string $localeCode
     * @return bool true on success
     */
    public function deploy($areaCode, $themePath, $localeCode)
    {
        /** @var \Magento\Framework\View\Design\ThemeInterface $theme */
        $theme = $this->themeList->getThemeByFullPath($areaCode . '/' . $themePath);
        /** @var \Magento\Theme\Model\View\Design $design */
        $design = $this->designFactory->create()->setDesignTheme($theme, $areaCode);
        /** @var ResolverInterface $locale */
        $locale = $this->localeFactory->create();
        $locale->setLocale($localeCode);
        $design->setLocale($locale);

        $assetRepo = $this->assetRepoFactory->create(['design' => $design]);
        /** @var \Magento\RequireJs\Model\FileManager $fileManager */
        $fileManager = $this->fileManagerFactory->create(
            [
                'config' => $this->requireJsConfigFactory->create(
                    [
                        'assetRepo' => $assetRepo,
                        'design' => $design,
                    ]
                ),
                'assetRepo' => $assetRepo,
            ]
        );

        \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\App\State::class)->emulateAreaCode(
            $areaCode,
            [$fileManager, 'createRequireJsConfigAsset']
        );
        
        //$fileManager->createRequireJsConfigAsset();

        $fileManager->createMinResolverAsset();

        return true;
    }
```    
    

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dmitryp1993** [comment]
@magento give me 2.4.5-p8 instance

**Comment by dmitryp1993** [comment]
https://github.com/magento give me 2.4.5-p8 instance

**Comment by dmitryp1993** [comment]
@magento give me 2.4.5-p8 instance

**Comment by dmitryp1993** [comment]
@magento give me 2.4.5-p8 instance

**Comment by engcom-Delta** [comment]
Hi @dmitryp1993 ,

Verified the issue on 2.4-develop and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1. Enable Magento_CSP module 
2. Set"dev/js/translate_strategy" is to embedded
3. Set deployment mode to production
4. Run bin/magento setup:static-content:deploy


Magento_CSP module is enabled

<img width="771" alt="Screenshot 2024-06-21 at 6 35 16 PM" src="https://github.com/magento/magento2/assets/51681379/94ed759e-69fe-436b-b3b2-f973b4ab4bf0">

"dev/js/translate_strategy" is set to "embedded"

<img width="1434" alt="Screenshot 2024-06-21 at 6 24 05 PM" src="https://github.com/magento/magento2/assets/51681379/6e602837-e073-49de-b634-c53adcba9638">

Deployment mode - production

<img width="953" alt="Screenshot 2024-06-21 at 6 35 58 PM" src="https://github.com/magento/magento2/assets/51681379/c3cce2bc-6987-4655-b5d0-b70b5567a55b">

bin/magento setup:static-content:deploy

<img width="999" alt="Screenshot 2024-06-21 at 6 36 11 PM" src="https://github.com/magento/magento2/assets/51681379/54fd5e49-0d17-41c2-b52d-0765cd5cac60">

**Comment by quterorta** [comment]
@magento I am working on this
