### ISSUE TITLE
Magento 2.0 admin not working

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#3885]
I cannot access the admin side of the magento 2.0, there is an error "Item (Magento\Theme\Model\Theme\Data) with the same id "0" already exist". I don't know how and where to fix this one :(

Thank you,
Noel

**Comment by mazhalai** [comment]
@noprobz09 how did you deploy Magento 2.0? via git, composer or zip from magento.com? Also, please give details of your environment, like OS, web server and PHP version,

**Comment by magentotejpal** [comment]
Hi, i have install the magento 2 in my server. Front part is perfect runing . but when i go to admin part after login in admin panel js and css file not loading. show 403 error.

Can you please help me

**Comment by mrkhoa99** [comment]
@magentotejpal You can take the screenshots about your issue. Try to run deploy command: 
`php bin/magento setup:static-content:deploy`

**Comment by magentotejpal** [comment]
HI,
Thanks For Your Reply .
Right Now , show this error.

Autoload error
Vendor autoload is not found. Please run 'composer install' under application root directory.

**Comment by magentotejpal** [comment]
Hi , 
I have attach the image of the Please check.
![error-magento-2](https://cloud.githubusercontent.com/assets/18575839/14698259/a9a434a2-07aa-11e6-8566-b5fda33643eb.png)

**Comment by patrickpeng2091** [comment]
chmod 777 -R  <magento path>

**Comment by magentotejpal** [comment]
Hi i have set the permission chmod 777 -R.

But same error.

**Comment by magentotejpal** [comment]
I have attach the image please check 
![error-magento-3](https://cloud.githubusercontent.com/assets/18575839/14717397/f0922ca2-080e-11e6-9184-74abaa09e405.png)

**Comment by magentotejpal** [comment]
/pub/static/adminhtml/Magento/backend/en_GB/extjs/resources/css/ytheme-magento.css 

i have go to this path but i can't see en_GB Folder. can you please help.

**Comment by mazhalai** [comment]
@magentotejpal this means, you have permissions errors. Please see http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html and http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html

**Comment by mazhalai** [comment]
@noprobz09 @magentotejpal closing due to non-responsiveness
