### ISSUE TITLE
Object Manager not used for Magento\Csp\Model\Mode\Data\ModeConfigured

### ISSUE THREAD

**Issue by pmzandbergen** [magento/magento2#38875]
**File**
https://github.com/magento/magento2/blob/ef81f5a2f8271ea529606fcb56898eed286d46b5/app/code/Magento/Csp/Model/Mode/ConfigManager.php#L121

**Description**
The Object Manager is not being used when creating `Magento\Csp\Model\Mode\Data\ModeConfigured`. Therefore Plugins can't be used on this object.

**Comment by engcom-Hotel** [comment]
Hello @pmzandbergen,

Thanks for the report and collaboration!

I agree with your point, in the provided code from `app/code/Magento/Csp/Model/Mode/ConfigManager.php`, the `Magento\Csp\Model\Mode\Data\ModeConfigured` object is being instantiated directly using the new keyword.

When an object is created directly like this, Magento's Object Manager is bypassed, which means that any plugins (interceptors) that might be defined for that class will not be triggered.

Hence confirming the issue.

Thanks

**Comment by thecodecook14** [comment]
@magento I am working on this

**Comment by pmzandbergen** [comment]
> Hello @pmzandbergen,
> 
> Thanks for the report and collaboration!
> 
> I agree with your point, in the provided code from `app/code/Magento/Csp/Model/Mode/ConfigManager.php`, the `Magento\Csp\Model\Mode\Data\ModeConfigured` object is being instantiated directly using the new keyword.
> 
> When an object is created directly like this, Magento's Object Manager is bypassed, which means that any plugins (interceptors) that might be defined for that class will not be triggered.
> 
> Hence confirming the issue.
> 
> Thanks

Shall I create a PR with the required change?

**Comment by hostep** [comment]
> Shall I create a PR with the required changes ...

Looks like @glo24157 started working on it on this branch: https://github.com/magento/magento2/commits/issue38875/

**Comment by pmzandbergen** [comment]
PR is ready for review: https://github.com/magento/magento2/pull/38886
