### ISSUE TITLE
Creating a customer via rest api: /V1/customers/me does not work

### ISSUE THREAD

**Issue by Bbbrinks** [magento/magento2#3887]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Call /V1/customers/me rest api with (valid auth token) and body:
   {
   "email": "test@test.com",
   "firstname": "dsfsdf",
   "lastname": "sdsdf",
   "addresses": [
       {
       "firstname": "string",
       "lastname": "string"
       }
   ]
   }
## Expected result
1. The customer gets created and 200 is returned
## Actual result
1. 400 bad request
   {
   "message": "One or more input exceptions have occurred.",
   "errors": [
     {
       "message": "%fieldName is a required field.",
       "parameters": {
         "fieldName": "firstname"
       }
     },
     {
       "message": "%fieldName is a required field.",
       "parameters": {
         "fieldName": "lastname"
       }
     },
     {
       "message": "Invalid value of \"%value\" provided for the %fieldName field.",
       "parameters": {
         "fieldName": "email",
         "value": null
       }
     }
   ]
   }

**Comment by adderall** [comment]
I am having this problem also:

```curl -X POST "http://v2.designeroptics.com/index.php/rest/V1/customers" -H "Content-Type:application/json" -H "Authorization: Bearer xhfyo8cfvknpyd5dwuupe34uosh6tuhj" -d '{
  "email": "robinjhoff@sbcglobal.net",
  "firstname": "Robin",
  "lastname": "Hoff",
  "storeId": 1,
  "websiteId": 1
}' | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   204    0    83  100   121     98    143 --:--:-- --:--:-- --:--:--   143
{
   "message" : "%fieldName is a required field.",
   "parameters" : {
      "fieldName" : "customer"
   }
}```

**Comment by adderall** [comment]
Now it works with:

`curl -X POST "http://v2.website.com/index.php/rest/V1/customers" -H "Content-Type:application/json" -H "Authorization: Bearer xhfyo8cfvknpyd5dwuupe34uosh6tuhj" -d '{"customer": { "email": "person@email.net", "firstname": "First", "lastname": "Last", "storeId": 1, "websiteId": 1 }}' | json_pp`

However, can somebody help me add the default address information into this request?

**Comment by sevos1984** [comment]
Maybe this can help http://devdocs.magento.com/swagger/#!/customerAccountManagementV1/customerAccountManagementV1CreateAccountPost

**Comment by mbrinton01** [comment]
@sterfpaul Were you able to answer your question about how to create customer address information from the documentation?

**Comment by singh190** [comment]
I need to register customer via REST API. I have '**Consumer Key**','**Consumer Secret**','**Access Token**' and '**Access Token Secret**', created from Magento admin. 
Please tell me how I can generate valid token and register customer using this details?

**Comment by mbrinton01** [comment]
Hello @singh190. Please use GitHub for bug reports only. For your question about how to use the REST API, please post on the Magento 2 [Forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2).

**Comment by khatariya** [comment]
{
     "customer": {
         "email": "abc@gmail.com",
         "firstname": "Abc",
         "lastname": "Xyz"   

     },
     "password": "Abc@123456"
  }
