### ISSUE TITLE
Catalog Swatch Helper Data Access

### ISSUE THREAD

**Issue by kestraly** [magento/magento2#38887]
### Preconditions and environment

Magento 2.4.x

Accessing the catalog swatch helper data directly from templates is not possible. Is there a reason this is not possible?

### Steps to reproduce

Add $this->helper('Magento\Swatches\Helper\Data'); in a .phtml template file that is loaded on a catalog page.

Sample Code
```
$swatchHelper = $this->helper('Magento\Swatches\Helper\Data');

$color_attribute = $_product->getResource()->getAttribute('color');
$color_options = $color_attribute ? $color_attribute->getSource()->getAllOptions() : [];
$colorOptionIds = [];
foreach ($color_options as $color_option) {
    if ($color_option['value']) {
        $colorOptionIds[] = $color_option['value'];
    }
}
$swatchHelper->getSwatchesByOptionsId($colorOptionIds);

```

### Expected result

Access to Catalog Swatch Helper Data to perform tasks such as

### Actual result

main.ERROR: Magento\Swatches\Helper\Data doesn't extends Magento\Framework\App\Helper\AbstractHelper when accessing a page using the .phtml template file.

### Additional information

Possible solution for Helper
vendor/magento/module-swatches/Helper/Data.php

Update from
`class Data`

to

`class Data extends \Magento\Framework\App\Helper\AbstractHelper`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @kestraly,

Thanks for the report and collaboration!

It seems to us an expected behavior, If you still need to use the methods from `Magento\Swatches\Helper\Data` in your `.phtml` file, you should create a ViewModel and use dependency injection to get the `Magento\Swatches\Helper\Data` class. Then, you can create a method in your ViewModel that uses the methods from the helper. You can then call this method from your .phtml file.

Else please let us know your use case if you don't want to create a ViewModel.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @kestraly,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
