### ISSUE TITLE
Front end assets are loaded from different website in multi store setup with config cache disabled

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#3888]
When we have the configuration cache disabled, all stores (on different websites) load product images and assets (like JS files or Fonts) from other stores. The stores (domains) where these files are being loaded from seem random and mixed. This only happens on product pages, not on category pages.
## Steps to reproduce
1. Disable configuration cache while having a multi store set up
2. Empty all caches
3. Browse to a product page
## Expected result
1. Images and assets loaded from current website
## Actual result
1. Images and assets loaded from other website in multi store set up

**Comment by palamar** [comment]
@redelschaap
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
