### ISSUE TITLE
Cannot Get Credentials From PayPal

### ISSUE THREAD

**Issue by bulldogm11** [magento/magento2#38896]
### Preconditions and environment

Magento 2.4.6-p4

When trying to connect PayPal Express and Get Crdentials From PayPal, API Username, Password, & Signature are not retrieved. 

### Steps to reproduce

Store -> Configuration ->Sales -> Payment Methods 
Paypal Express Checkout Configure
Click Get Credentials From PayPal
Login
No crendentials are retrieved. 

### Expected result

Retrieve and populate API credentials

### Actual result

No credentials retrieved

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bulldogm11** [comment]
@magento give me 2.4-develop instance

**Comment by bulldogm11** [comment]
Issue is confirmed on vanilla Magento instance.

**Comment by engcom-Dash** [comment]
Hi @bulldogm11 

Thanks for reporting and collaboration.

Verified the issue on the Magento 2.4 dev instance.

When we click on Click Get Credentials From PayPal and try to log in to Paypal, we get "Please check your entries and try again."

Please let me know if this is the issue you are having.

Please refer to the attached screenshot.

<img width="1440" alt="Screenshot 2024-07-15 at 7 37 57 AM" src="https://github.com/user-attachments/assets/a197aae9-f77c-40aa-833d-3bc7003dbd9a">

**Comment by engcom-Dash** [comment]
Hi @bulldogm11 

We have noticed that this issue has not been updated for a long time. Hence we assume this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
