### ISSUE TITLE
Content security policy issue with 2.4.7 magento version

### ISSUE THREAD

**Issue by kunwarsingh77** [magento/magento2#38906]
### Preconditions and environment

- Magento version - 2.4.7 p1
We are experiencing issues with our custom payment gateway in Magento 2.4.7. The problems are related to the Content Security Policy (CSP) settings and reCAPTCHA timeouts.

**Steps Taken to Address the Issue -** 
Updated Content Security Policy (CSP):

I have modified the csp_whitelist.xml to include all necessary script sources such as Stripe, reCAPTCHA, and other third-party services.
Ensured all script sources mentioned in the console error were whitelisted.

**Issue Details**
Content Security Policy Error:

The initial issue was a CSP error preventing the Stripe script from loading and my custom payment method not loading at checkout.
Error message: Refused to load the script 'https://js.stripe.com/v3/' because it violates the following Content Security Policy directive...

**I have added the necessary script sources to csp_whitelist.xml to resolve this error then my payment gateway is loaded on checkout but when we select the payment gateway the stripe form is not loading and it's showing some Recaptcha error with timeout in the console and still showing a CSP error in console as well.**

**My custom payment gateway of the stripe is working properly with all previous versions of Magento but when I updated to the new 2.4.7 version I am facing this issue.**

We seek assistance in understanding if there are any additional steps or configurations required in Magento 2.4.7 to resolve this CSP, especially with custom payment gateways.

### Steps to reproduce

Install Magento 2.4.7.
Create and configure a custom payment gateway that integrates with Stripe.
Ensure the custom payment method is enabled in the Magento Admin panel.
Go to checkout with a product 
open console 
you will see you custom payment gateway is not showing and there is a CSP error in console

### Expected result

after updating the new version of Magento 2.4.7 the custom payment gateway loads properly and there will be no content security policy issue and should have no custom recaptcha issues if it is working with previous version of magentoMagento

### Actual result

after updating the new version of Magento 2.4.7 if you have a custom payment gateway then it will not load at checkout and will show a content security policy issue in console

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kunwarsingh77** [comment]
here are some screenshots of the issue after I whitelisted some URLs in the csp_whitelist file and my payment method loaded.
if see screenshot 2 there is recpatcha issue were stripe form have to load and in consle showing csp errors 
there issue is not coming in previous version and my plugin and custom payment gateway is working properly 
![Screenshot from 2024-07-05 11-49-22](https://github.com/magento/magento2/assets/168963537/ec53e724-319d-4796-9309-93a77fcfc8c1)
![Screenshot from 2024-07-05 11-54-05](https://github.com/magento/magento2/assets/168963537/e6dd70cd-b50d-44a7-abd4-8e15bb822643)

**Comment by engcom-Bravo** [comment]
Hi @kunwarsingh77,

Thanks for your reporting and collaboration.

 Stripe Payments Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by kunwarsingh77** [comment]
Hi @engcom-Bravo  
but the new Magento version is causing the content security policy issue that's why the other extension is not working properly 
could you please give us some solution or how we can support the CSP issue with the latest version to avoid or remove the CSP issue from the latest version?

**Comment by hostep** [comment]
You should contact stripe support not Magento support for this. They will be much quicker in helping you out.

It seems like their module hasn't implemented yet the needed CSP support for Magento 2.4.7

Also, if you want to see more details in the browsers console, open that arrow next to it, underneath it you should see more details (hopefully).

Also, you could setup a CSP reporting service (here's a free one: https://sansec.watch/), it should give you some feedback about any CSP violations that happen on your shop so you can keep a close watch on it.

Also, if CSP blocks you and you want it resolved urgently, you can temporarily disable it, then take your time to try to figure out a solution, implement it and then enable it again.

**Comment by kunwarsingh77** [comment]
Thanks, i have resolved the issue by following https://developer.adobe.com/commerce/php/development/security/content-security-policies/#page-specific-content-security-policies

**Comment by stevensagaar** [comment]
I have resolved these issues by following this blog article https://www.scommerce-mage.com/blog/magento2-csp-whitelisting.html

**Comment by DenisWebmer** [comment]
@magento give me 2.4.7-develop instance
