### ISSUE TITLE
Magento_MediaGalleryApi module sequences doesn't integrate Magento_MediaGallery

### ISSUE THREAD

**Issue by AlexandreBulete** [magento/magento2#38915]
### Preconditions and environment

- Magento version 2.4.6-p6
- Redis

### Steps to reproduce

Add a REDIS Connection and enable modules : 
```sql
bin/magento module:e Magento_MediaGalleryApi Magento_MediaGalleryCatalog Magento_MediaGalleryCatalogIntegration Magento_MediaGalleryCatalogUi Magento_MediaGalleryCmsUi Magento_MediaGalleryIntegration Magento_MediaGalleryMetadata Magento_MediaGalleryMetadataApi Magento_MediaGalleryRenditions Magento_MediaGalleryRenditionsApi Magento_MediaGallerySynchronization Magento_MediaGallerySynchronizationApi Magento_MediaGallerySynchronizationMetadata Magento_AdobeStockImageAdminUi Magento_MediaGalleryUiApi Magento_MediaContent Magento_MediaContentApi Magento_MediaContentCatalog Magento_MediaContentCms Magento_MediaContentSynchronization Magento_MediaContentSynchronizationApi Magento_MediaContentSynchronizationCatalog Magento_MediaContentSynchronizationCms
```
(without Magento_MediaGallery)

### Expected result

Should output a warning to prevent a bad generated/code caused due to Magento_MediaGalleryApi di.xml file.

### Actual result

Nothing, and a broken generated/code/Magento/MediaGalleryApi files generated.

### Additional information

Just need to change from
```xml
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Magento_MediaGalleryApi" />
</config>
```

to this
```xml
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Magento_MediaGalleryApi">
        <sequence>
            <module name="Magento_MediaGallery" />
        </sequence>
    </module>
</config>
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @AlexandreBulete,

Thank you for the report and collaboration!

Can you elaborate the broken files generated at generated/code/Magento/MediaGalleryApi?
