### ISSUE TITLE
Can't get store config in cms block/page

### ISSUE THREAD

**Issue by Kireall** [magento/magento2#3891]
## Steps to reproduce
1. Install Magento from `master` branch.
2. Insert in content of cms block {{config path="design/footer/copyright"}} and save block
3. Go to frontend
## Expected result
1. Config's value should be showed
## Actual result
1. Config's value is not showed

**Comment by miakusha** [comment]
Hi @Kireall, magento not allow show all configuration data on frontend. You can use only limited list of config that described in \Magento\Email\Model\Source\Variables::__construct
