### ISSUE TITLE
Nonce for Design configuration

### ISSUE THREAD

**Issue by khoannd98** [magento/magento2#38935]
### Summary

I'm currently using Magento 2.4.6-p6.
I have some configuration in the design configuration (for more specificity, it's some JS script in the Scripts and Style Sheets config).
When I'm on the homepage or category page, there's no issue with it. But when I access the checkout page, I get the error "Refused to execute inline script because it violates the following Content Security Policy directive."
I want to ask if is there any way to get the nonce and assign it dynamically to my design configuration?

### Examples

<img width="1292" alt="Screenshot 2024-07-16 at 17 02 24" src="https://github.com/user-attachments/assets/f7f23a85-e558-4699-baf4-b69d94d85f0c">

<img width="1113" alt="Screenshot 2024-07-16 at 17 09 26" src="https://github.com/user-attachments/assets/f84d0ad1-1de7-4a98-833d-e1560584eb12">

### Release note

https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-6-patches

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @khoannd98,

Thanks for the report and collaboration!

After going through the issue, it doesn't seem to be any issue/bug related to the Magento core library. I suggest you post these kinds of queries in [Magento Stackexchange](https://magento.stackexchange.com/) in the future.

And for your query below: 

> I want to ask if is there any way to get the nonce and assign it dynamically to my design configuration?

Yes, you can create the nonce and assign it to the design configuration. You may need to follow the below steps:

- Create a helper class NonceHelper in the Helper directory.
- Implement methods to generate and retrieve the nonce.
- Modify the Design Configuration:  Use the helper class in the design configuration to assign the nonce dynamically.

Thanks
