### ISSUE TITLE
Errors on the Extensions upload on the commercedeveloper.adobe.com

### ISSUE THREAD

**Issue by SantiSnow** [magento/magento2#38931]
### Preconditions and environment

- Magento 2.4.7
- The extensions review process has an error on the automated tests. It throws an exception while trying to run the `php bin/magento setup:ci:compile`. It throws the following error:

`"There is an error in /app/vendor/osaka/module-blogmodule/Api/Data/PostInterface.php at line: 7",`

That line has:
`public const int STATUS_ENABLED = 1;`

Previous to that I got another error where I had to delete constants. This type of compiling error happens on older PHP version. The tests are not running on the latests PHP version.

![image](https://github.com/user-attachments/assets/96aabdf9-cb13-44d6-95d2-f42b75aff779)

### Steps to reproduce

Go to commercedeveloper.adobe.com.
Try to publish a new extension or update it, the automated tests fails.

### Expected result

A succesfull compile.

### Actual result

Error on compilation.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @SantiSnow,

This is not the correct board to post this issue. Let me redirect you to the correct board.

Meanwhile, we are closing this issue here.

Thanks
