### ISSUE TITLE
Cart price rule created for logged in user incorrectly gets applied for not logged in user

### ISSUE THREAD

**Issue by dhruvi-prajapat1** [magento/magento2#38944]
### Preconditions (*)

1. Magento dev-2.4-develop

### Description (*)

There is a cart price rule that applies only to logged-in users, for example, a 5% discount. When the user is logged in and adds a product to the cart, the cart price rule will be applied. After that, the user is logged out automatically because the cookie lifetime has expired. 
When the user visits the shop again, the product is still present in the cart, and the cart price rule is still applied to the product, even though the user is not logged in.

Screenshot-1:
![image (1)](https://github.com/user-attachments/assets/7a90a3bc-2873-476b-b2c1-485b5b27d901)

Screenshot-2:
![image (2)](https://github.com/user-attachments/assets/546dbeba-b29b-49e0-b411-2c7022350806)

Screenshot-3:
![image (3)](https://github.com/user-attachments/assets/26b8bfd6-7eb8-4caa-a19a-a682292b5427)

Screenshot-4:
![image (4)](https://github.com/user-attachments/assets/a84ae449-56b4-4865-a36a-5db3cb364b77)

### Steps to reproduce (*)

1. In Marketing -> Cart Price Rules add rule for log in customers (select general customer group), for example 5% discount.(Shown in Screenshot - 1)
3. In Stores -> Configuration ->Customers -> Persistent Shopping Cart -> set the following configuration: Enable Persistence - Yes , Clear Persistence on Sign Out – Yes (Shown in Screenshot - 2)
4. In Stores -> Configuration -> General -> Web ->Default Cookie Settings ->Cookie Lifetime (For example 60 seconds) (Shown in Screenshot - 3)
5. In the shop, create a customer account and add a product to the cart. At this time, the cart price rule will be applied, and the user will get a discount on the product.
6. After that user will be log out according to the cookie lifetime (step – 3)
7. Open the shop, at this time user is not log in into the shop, but user can still see the product into the cart with applied discount.(Shown in Screenshot - 4)

### Expected result (*)

When user is logged out cart price rule should not applied and cart should be empty.

### Actual result (*)

Here user is logged out but still we can see the product in the cart and cart price rule is still applied.

**Comment by Mohamed-Asar** [comment]
@magento i'm working on this

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

Internal team has started to work on it

Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12541 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12541&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
