### ISSUE TITLE
TypeError: this.itemRenderer is undefined

### ISSUE THREAD

**Issue by babyasishhira** [magento/magento2#3894]
I m getting this error on minicart.. And for this minicart is not showing any items
![minicart](https://cloud.githubusercontent.com/assets/17763698/14040266/7f8e4984-f28b-11e5-89db-3827d813d0f6.png)

**Comment by babyasishhira** [comment]
Can you please tell me that is it solved or not??

**Comment by ishakhsuvarov** [comment]
@babyasishhira Thank you for reporting this issue. Please provide preconditions and steps to reproduce the issue and Magento version you are using.

**Comment by babyasishhira** [comment]
There is was made some mistake on xml.. Fixed when i copy all code from vendor folder.

**Comment by jordanbrierley** [comment]
@babyasishhira Hi, I'm having the same problem with my theme, would you be able to tell me which file you had to replace or how you solved it as I'm guessing mines a similar issue? Thanks

**Comment by babyasishhira** [comment]
Delete Mage_Checkout/layout folder from your theme

**Comment by dikshugoel786** [comment]
We can use only override  layout xml. for example :- checkout_index_index.xml  
Do not mention any extra xml, if you are not overriding
