### ISSUE TITLE
Layout action overrides order

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#38946]
### Preconditions and environment

- Latest Magento version but could be reproduced with any of them

### Steps to reproduce

Base :
- layout catalog_product_view : block : templateA
- layout default : block : templateA

Module_A :
- layout catalog_product_view : block -> action -> setTemplate(templateB)
- layout default : block -> action -> setTemplate(templateC)

Theme :
- Module_A :
 - layout catalog_product_view : block -> action -> setTemplate(templateA)
 - layout default : block -> action -> setTemplate(templateA)

### Expected result

My block have the template A

### Actual result

My block have the template B

### Additional information

Because the template A is set by action in the layout default and the layout catalog_product_view, there's a bug in the merge layout. Only the first action with same argument is processed.

The result is:

templateC
templateA
templateB

When it should be:

templateC
templateA
templateB
templateA

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @thomas-kl1,

Thanks for the report and collaboration!

But can you please elaborate more on this issue? We are unable to get it properly.

Thanks
