### ISSUE TITLE
PayPal’s Client-side only JavaScript SDK on or after 31 July 2024!

### ISSUE THREAD

**Issue by olgaIskra** [magento/magento2#38948]
### Preconditions and environment

- Magento version : 2.4.5
- Module:vendor/magento/module-paypal : Magento_Paypal/js/in-context/paypal-sdk !!!!!
- 

### Steps to reproduce

pay with PayPal

### Expected result

module-paypal : Server-side JavaScript SDK

### Actual result

module-paypal :  JavaScript SDK - client side!!!!!

### Additional information

Magento/Adobe... must change core module according to new PayPal requirements

### Release note

Magento/Adobe... must change core module according to new PayPal requirements

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
To make the issue more clear, this seems to be a response to a question asked on #38591, I would suggest we close this one and re-open #38591 again.

**Comment by olgaIskra** [comment]
OK. But Adobe/Magento must very quickly change module: vendor/magento/module-paypal
because Magento_Paypal/js/in-context/paypal-sdk  go by client side, from 30.07 must go by server side

**Comment by stkrelax** [comment]
this seems to be quite important xD any updates on this ?

**Comment by engcom-Hotel** [comment]
Hello @olgaIskra,

Thanks for the report and collaboration!

We are going through the official documentation of Paypal for [Javascript SDK](https://developer.paypal.com/sdk/js/), but it is not mentioned there. 

Please provide us with an official link for the same.

Thanks

**Comment by olgaIskra** [comment]
Hello!
1.This is link from PayPal:
https://developer.paypal.com/api/rest/sandbox/card-testing/#link-creditcardgeneratorfortesting.

2. Adobe/Magento must very quickly change module: vendor/magento/module-paypal
because Magento_Paypal/js/in-context/paypal-sdk go by client side, from 30.07 must go by server side

Please look at the core code.

Olga.

**Comment by engcom-Hotel** [comment]
Thanks @olgaIskra for the reply! 

Actually, I am expecting an official link with the date mentioned on it and saying that PayPal’s Client-side JavaScript SDK will not work after 31 July 2024.

However, I am unable to find the same in the given link. Please let us know if we missed anything there.

Thanks

**Comment by olgaIskra** [comment]
Online store owners received this message   25.01.2024:

At PayPal, one of our top priorities is to ensure both our and your customers have a safe and secure experience when making purchases or moving money online. In our commitment to enhancing the highest level of security to protect customer and transactional data, we will be discontinuing the use of PayPal’s Client-side only JavaScript SDK on or after 31 July 2024.

Our records show that your account has used Client-side only JavaScript SDK in the past 12 months for PayPal Checkout. This integration method may have been set up by using our integration guide or by copying prebuilt code and pasting it onto the pages on your website where you sell your products or services.

To avoid the interruption of service with PayPal, you must integrate PayPal Checkout in another way prior to 31 July 2024.

What do I need to do?

To avoid a discontinuation of service, we recommend merchants migrate from our Client-side only integration to our Server-side JavaScript SDK integration.

Here are some resource guides for developers:

[Migration guide from Client-side only to Server-side JavaScript SDK](https://github.com/paypal-examples/paypal-sdk-server-side-integration/blob/main/docs/update-from-client-side-helpers-to-server-side.md)
[PayPal Checkout Integration Guide](https://developer.paypal.com/docs/checkout/standard/integrate)
If you need additional support, we encourage you to contact your web hosting company, ecommerce software provider, in-house web programmer or system administrator.

**Comment by engcom-Hotel** [comment]
Thanks @olgaIskra for more information on this issue. We are moving this issue `On hold` to discuss the same with the PO.

**Comment by olgaIskra** [comment]
Thank you! I am hoping for a quick change so that there is no need to turn off PayPal from the payment methods

**Comment by stkrelax** [comment]
Any updates on this ?

**Comment by engcom-Hotel** [comment]
Hello @olgaIskra,

We have a reply from PayPal and according to them Adobe payment services already use Server Side API calls and were not impacted by this. I do not believe there is any concern or work needed.

Hence we are closing this issue.

Thanks
