### ISSUE TITLE
UPS API Change Request

### ISSUE THREAD

**Issue by SamKarmick** [magento/magento2#38952]
### Preconditions and environment

![image](https://github.com/user-attachments/assets/3fae1b8d-72e3-4d8e-94ae-4d596e37fd7f)

![image](https://github.com/user-attachments/assets/a024d171-fac1-477b-925b-af3ba97a60f3)

- Magento version 2.4.2

### Steps to reproduce

![image](https://github.com/user-attachments/assets/3fae1b8d-72e3-4d8e-94ae-4d596e37fd7f)

![image](https://github.com/user-attachments/assets/a024d171-fac1-477b-925b-af3ba97a60f3)

### Expected result

May I need to update to the current version  of magento for this UPS new authentication

### Actual result

![image](https://github.com/user-attachments/assets/3fae1b8d-72e3-4d8e-94ae-4d596e37fd7f)

![image](https://github.com/user-attachments/assets/a024d171-fac1-477b-925b-af3ba97a60f3)

- Magento version 2.4.2

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by satyashu007** [comment]
Hi, I also using same Magento version and want to know do we need to upgrade our Magento version for UPS work correctly?

**Comment by SamKarmick** [comment]
Hi @engcom-Dash , can you please suggest what to do with this new UPS changes of API

**Comment by devchris79** [comment]
Magento 2.4.2 - 2.4.6 UPS module uses a SOAP API that is due to become EOL (As you note).
[Magento 2.4.4 - 2.46 has patches to use REST API (with OATH 2.0) available here](https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/ups-shipping-method-integration-migration-from-soap-to-restful-api)
Magento 2.4.7 has the REST API built in

**Comment by engcom-Dash** [comment]
Hi @SamKarmick 

Thanks for reporting and collaboration.

It is recommended that the latest Magento instance be used. so, please upgrade your instance to the latest Magento.

Thanks.

**Comment by esteban-serfe** [comment]
Hi @satyashu007 and @SamKarmick 

As devchris79 indicated the patches for the version you have exists (he pointed the ones that need to apply). For those patches to work on 2.4.2,  you might need to adjust them a little. This is to avoid to upgrade to the latests versions, but that depends on your situation. 
Don't forget to follow the guide mentioned on https://developer.ups.com/oauth-developer-guide?loc=en_US&sp_rid=NTA5MzQ1OTE2NjEyS0&sp_mid=72989914 as you need to generate new configuration on your UPS account.

If you need further assistance don't hesitate on [contacting us as](mailto:info@serfe.com) we have been able to backport some patches to older versions before for our customers.

Regards

**Comment by engcom-Bravo** [comment]
@esteban-serfe Thanks for your Contribution!!

Hi @SamKarmick,

As per this comment https://github.com/magento/magento2/issues/38952#issuecomment-2253414030 we are closing this issue.Please feel free to reopen this issue if still you are facing any issue.

Thanks.
