### ISSUE TITLE
[BACKEND] Select action dropdown menu is not fully displayed

### ISSUE THREAD

**Issue by addison74** [magento/magento2#38956]
### Preconditions and environment

- Windows 10 + WSL + Docker + DDEV (Nginx, PHP 8.3)
- Magento version 2.4.7
- Magento Sample Data

### Steps to reproduce

1. Go to the **Backend > Customers > All Customers**
2. Edit the only customer available Veronica Costello
3. In **Customer Information** block go to the **Addresses** tab. There is only one address in the table.
4. On the last column to the right **Action** click on the **Select** link.

### Expected result

If there are few addresses in the table (e.g. 1 - 2), it must be default sized so that the dropdown menu is visible. There is also the variant for the menu to be displayed outside the table.

### Actual result

The drop own menu is not fully displayed and you have to scroll. In my opinion this is a UI/UX issue. Please see the screenshots bellow

**Before clicking the Select link**

![screenshot_1](https://github.com/user-attachments/assets/f8fe1e30-a1d2-4c7f-ba5f-9d8a47b52617)

**After clicking the Select link**

![screenshot_2](https://github.com/user-attachments/assets/dcdbc89f-0387-4271-bd0b-019b27fe4a22)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @ADDISON74,

Thanks for your reporting and collaboration.

Similar has been Confirmed here https://github.com/magento/magento2/issues/38891.

Hence we are closing this as duplicate.

Thanks.
