### ISSUE TITLE
How to Sold Out Product Auto go at the end of the Page or the last page of the Category

### ISSUE THREAD

**Issue by royalehitesh** [magento/magento2#38967]
### Description

We have an ecommerce website that is developing on Magento 2. Our product usually sold out, so when we mark it as sold out, it does not automatically go to the end of the page. They come on top in any position, so is it possible in Magento that the sold-out product auto at the end of the page or last page of the category?

### Expected behavior

We need the sold-out product auto-go at the end of the page or the last page of the category; there is no need for a manual process.

### Benefits

Due to this, the user experience will be improved, which will help in business sales.

**Comment by andrewbess** [comment]
Hello @royalehitesh 
Thank you for your collaboration.
I am not sure this issue should be the github issue.
But I am sure it would be better to use Magento slack (https://developer.adobe.com/open/magento/slack) for a similar questions.
I think your question should be asked to community via Slack but not via github
I will close this issue.
