### ISSUE TITLE
Product page error "The OTP window must be a numeric value"

### ISSUE THREAD

**Issue by dimitryfatkulin** [magento/magento2#38962]
### Preconditions and environment

Magento Commerce 2.4.7-p1

### Steps to reproduce

Open a category

### Expected result

The OTP window must be a numeric value

### Actual result

Product page

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dimitryfatkulin** [comment]
Has anyone else experienced this?

**Comment by engcom-Dash** [comment]
Hi @dimitryfatkulin 

Thanks for reporting and collaboration. 

Can you please add detailed steps to reproduce and screenshots to verify the issue?

Thanks.

**Comment by YoeriW** [comment]
> Has anyone else experienced this?

Yes, I tried to disable Magento_TwoFactorAuth locally via env.php, then run setup:upgrade and setup:di:compile.

While running setup:di:compile I recieved this error too:
`2024-07-24T07:37:03.167730+00:00] main.ERROR: The OTP window must be a numeric value. #0 /Users/X/sites/Y/vendor/magento/framework/App/Config/MetadataConfigTypeProcessor.php(133): Magento\TwoFactorAuth\Model\Config\Backend\OtpWindow->processValue(NULL) .......`
`In OtpWindow.php line 37:
  The OTP window must be a numeric value. `

The second time I run this it is gone. I hope your problem is gone too @dimitryfatkulin 

Magento version: 2.4.7-p1

**Comment by dimitryfatkulin** [comment]
Hi 
1. Open homepage
2. Open a random category
You see the error below. This only happens in Magento Commerce. I have created a temporary patch.
![Screenshot from 2024-07-24 09-38-06](https://github.com/user-attachments/assets/2cc3298d-2431-4047-b9fd-a24f4f7a27f5)
![Screenshot from 2024-07-24 09-41-44](https://github.com/user-attachments/assets/451764af-436d-4803-9a1a-7c76ffb8aafb)

Index: vendor/magento/module-two-factor-auth/Model/Config/Backend/OtpWindow.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-two-factor-auth/Model/Config/Backend/OtpWindow.php b/vendor/magento/module-two-factor-auth/Model/Config/Backend/OtpWindow.php
--- a/vendor/magento/module-two-factor-auth/Model/Config/Backend/OtpWindow.php	
+++ b/vendor/magento/module-two-factor-auth/Model/Config/Backend/OtpWindow.php	(date 1717557560000)
@@ -33,6 +33,10 @@
      */
     public function processValue($value)
     {
+        #Temporary patch until bug is fixed
+        if ($value === null) {
+            return $value;
+        }
         if (!is_numeric($value)) {
             throw new ValidatorException(__('The OTP window must be a numeric value.'));
         }

**Comment by dimitryfatkulin** [comment]
> > Has anyone else experienced this?
> 
> Yes, I tried to disable Magento_TwoFactorAuth locally via env.php, then run setup:upgrade and setup:di:compile.
> 
> While running setup:di:compile I recieved this error too: `2024-07-24T07:37:03.167730+00:00] main.ERROR: The OTP window must be a numeric value. #0 /Users/X/sites/Y/vendor/magento/framework/App/Config/MetadataConfigTypeProcessor.php(133): Magento\TwoFactorAuth\Model\Config\Backend\OtpWindow->processValue(NULL) .......` `In OtpWindow.php line 37: The OTP window must be a numeric value. `
> 
> The second time I run this it is gone. I hope your problem is gone too @dimitryfatkulin
> 
> Magento version: 2.4.7-p1

**Comment by dimitryfatkulin** [comment]
I disabled the Magento_TwoFactorAuth module.
bin/magento set:up
bin/magento set:di:com;

I enabled the Magento_TwoFactorAuth module.
bin/magento set:up
bin/magento set:di:com;

The problem persists.

**Comment by YoeriW** [comment]
> I disabled the Magento_TwoFactorAuth module. bin/magento set:up bin/magento set:di:com;
> 
> I enabled the Magento_TwoFactorAuth module. bin/magento set:up bin/magento set:di:com;
> 
> The problem persists.

Try this:

`rm -rf generated/code/*;rm -rf var/cache/*;rm -r var/view_preprocessed/*;rm -r var/page_cache/*;rm -r pub/static/*;clean`

Add this to your app/etc/env.php file:
`<?php
return [
    ... YOUR EXISTING CODE ...
    ,
    'modules' => [
        'Magento_TwoFactorAuth' => 0
    ]
];
`

Then run: `bin/magento setup:upgrade;bin/magento setup:di:compile`

You can check if the module is disabled succesfully (on your local env) but running: `bin/magento module:status`

Result:

List of disabled modules:
...
Magento_TwoFactorAuth
...

No OTP Errors

**Comment by engcom-Dash** [comment]
Hi @dimitryfatkulin 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance and 2.4.7-p1 instance but the issue is not reproducible.

Steps to reproduce:

1. Open homepage
2. Open a random category

Please refer the attached screen-recording and let us know if we missed anything.


https://github.com/user-attachments/assets/88eda3fa-f062-4975-b6ee-9b073eecce32

**Comment by dimitryfatkulin** [comment]
Hi,

I've found the cause of the issue.

smile/elasticsuite was slightly outdated at 2.11.6.

I upgraded it to 2.11.8.2 and the error is gone.

Thanks,
