### ISSUE TITLE
Advance Search Option looking for Magento 2 Website

### ISSUE THREAD

**Issue by royalehitesh** [magento/magento2#38968]
### Description

In the market, various Magento plugins are available for the website search option, but I am not sure which is good. We are looking for a Search facility like Wallsandfloors. 

### Expected behavior

Web searches need to be user-friendly. The result should be relevant to the search and even show suggested terms that are helpful for the user in finding the product. Web searches should reduce user time when it comes to finding a particular product. The search result should be beneficial for the user when deciding to find an appropriate product.

### Benefits

The search result should be beneficial for the user when deciding to find an appropriate product.

**Comment by andrewbess** [comment]
Hello @royalehitesh 
Thank you for your collaboration.
I am not sure this issue should be the github issue.
But I am sure it would be better to use Magento slack (https://developer.adobe.com/open/magento/slack) for a similar questions.
I think your question should be asked to community via Slack but not via github
I will close this issue.
