### ISSUE TITLE
Adds '--' as suffix on sku in quote item after adding item to cart.

### ISSUE THREAD

**Issue by gaurav-webbytroops** [magento/magento2#38974]
### Preconditions and environment

- Magento 2.4.6, Magento 2.4.7
- Recently we found a but with custom options in simple product.

### Steps to reproduce

1. Add 2 custom options in admin for a simple product. One option can be a dropdown type and the second option should be a checkbox.
2. You will be able to see these options on the product detail page on the frontend.
3. Select dropdown and check two checkboxes from the second custom option.
4. Click on add to cart to add the item to the cart.
5. Open the quote_item table and the item you added, you will see the SKU with the '--' suffix. For example your SKU is '**24-MB01**'. Now your SKU stored in quote_item table is **24-MB01--**.
![image](https://github.com/user-attachments/assets/6d09f68f-d017-4aa9-906f-245a6bbb4931)

### Expected result

In quote_item, SKU should be without --. If the SKU is 24-MB01 it should be **24-MB01** not **24-MB01--**

### Actual result

Right now, it is adding -- as suffix in SKU after adding item to cart.
![image](https://github.com/user-attachments/assets/0359eddf-c123-4574-a633-5ad77217a8f2)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @gaurav-webbytroops,

Thanks for your reporting and collaboration.

Similar issue has been confirmed https://github.com/magento/magento2/issues/38518.

Hence we are closing this duplicate.

Thanks.
