### ISSUE TITLE
400+ stores and try to Save configuration taking too much time and CPU spike > 100%

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#38973]
### Preconditions and environment

- Magento 2.4.6

I have 400+ stores created in single Magento instance, I have autoscaling server with different Database AWS server.

There are 200k products.

Frontend and Backend both are hosted on AWS with autoscaling ability. 

I have AWS elasticache Redis server configured in the env.php

### Steps to reproduce

1. Open Admin panel
2. Go to Stores -> Configuration
3. Just click on Save config button
4. Check CPU usage on SSH 
5. It Spike to > 100% and Frontend servers are down

### Expected result

It should not spike CPU to 100%

### Actual result

![image_2024_07_25T10_52_03_955Z](https://github.com/user-attachments/assets/920bc9d1-cfca-4046-a29b-775f5c41cc51)

### Additional information

I was trhoubleshooting this issue since month we think that it trying to clean Cache and Save cahce while saving configuration for 400 stores and that causing issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Magento 2.4.7 comes with a solution for this I believe, see the new async config feature they introduced in version 2.4.7: https://experienceleague.adobe.com/en/docs/commerce-operations/performance-best-practices/configuration#asynchronous-configuration-save

**Comment by engcom-Hotel** [comment]
Thanks @hostep for the detailed explanation, much appreciated. I agree with your point below:

> (if you have a working cronjob, then there is no reason to manually run that `bin/magento queue:consumers:start` command they recommend, it should start up automatically via the cronjob, unless [your configuration](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/message-queues/manage-message-queues#configuration) doesn't allow it)

Hello @jigar48,

I hope this resolves your issue with saving the configuration. Let us know if you still need any assistance for the same. 

Thanks
