### ISSUE TITLE
Configurable product with only one variation.

### ISSUE THREAD

**Issue by sameasterling** [magento/magento2#3898]
if a configurable product has an only one variation, this variation should be preselected.

**Comment by antboiko** [comment]
Hi @sameasterling , thanks for your inquiry. I've created internal ticket MAGETWO-51224 to cover this improvement and placed it into our backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Configurable-product-with-only-one-variation/idi-p/46402).
