### ISSUE TITLE
Built in cache, multidomainstore, first visit loads not from cache

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#38981]
### Preconditions and environment

Magento 2.4.6-p3
PHP-FPM  8.1.29  
Multidomainstore 
NGINX

### Steps to reproduce

Create a store with sample data.
Create a second storeview like:
website second -> store second -> storeview second
Assign products and Categories to the storeview second.
Enable Magento built in cache. 
Enable developer mode.
Visit a page at storeview second to load this page into cache. Reload the page look at the Header data, it should be like this:  X-Magento-Cache-Debug: HIT
Delete your cookies. Reload the page.

### Expected result

 X-Magento-Cache-Debug: HIT

### Actual result

X-Magento-Cache-Debug: MISS

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Webroju,

Thanks for your reporting and collaboration.

Similar issue has been reported here https://github.com/magento/magento2/issues/38980

Hence we are closing this as duplicate.

Thanks.

**Comment by Webroju** [comment]
@engcom-Bravo thanks for the related links, but unfortunately is this bug only reported for 2.4.7. and the provided solution does not work in Magento 2.4.6. , Do you think I get also a bug fix for Magento 2.4.6 with the upcoming release?
Thanks.
