### ISSUE TITLE
Updating Magento 2.3.5-p1 to 2.4.5 getting issue

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#38989]
### Summary

I am trying to update magento version but it showing package not installed error
![image](https://github.com/user-attachments/assets/806eb37e-31c2-4e2d-bb86-37b09bb9a6db)

### Examples

![image](https://github.com/user-attachments/assets/b7dc77ef-f2a3-482d-852a-0abc10fbad75)

### Proposed solution

it should be updated with version

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @hemendrametawolf 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4.7-p1 after upgrading the instance from 2.3.5-p1.

We can upgrade the 2.3.5-p1 instance to 2.4.7-p1 successfully without any errors.

Please refer to the attached screenshots. Let us know if we missed anything.

Before upgrading Magento 2.3.5-p1:

<img width="1440" alt="Screenshot 2024-07-31 at 1 12 40 PM" src="https://github.com/user-attachments/assets/ce24aca7-9906-4509-9e62-ff229768a70b">

After updating to 2.4.7-p1 instance:

<img width="1440" alt="Screenshot 2024-07-31 at 2 24 04 PM" src="https://github.com/user-attachments/assets/8edd40aa-65fa-4ec5-99d9-7a0c79c880f8">

<img width="1440" alt="Screenshot 2024-07-31 at 2 23 43 PM" src="https://github.com/user-attachments/assets/a8b97d81-0b95-4d0f-8d01-0f6625bf4996">

**Comment by hemendrametawolf** [comment]
> Hi @hemendrametawolf
> 
> Thanks for reporting and collaboration.
> 
> Verified the issue on Magento 2.4.7-p1 after upgrading the instance from 2.3.5-p1.
> 
> We can upgrade the 2.3.5-p1 instance to 2.4.7-p1 successfully without any errors.
> 
> Please refer to the attached screenshots. Let us know if we missed anything.
> 
> Before upgrading Magento 2.3.5-p1:
> 
> <img alt="Screenshot 2024-07-31 at 1 12 40 PM" width="1440" src="https://private-user-images.githubusercontent.com/60198592/353765956-ce24aca7-9906-4509-9e62-ff229768a70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE5MzEsIm5iZiI6MTcyMjQyMTYzMSwicGF0aCI6Ii82MDE5ODU5Mi8zNTM3NjU5NTYtY2UyNGFjYTctOTkwNi00NTA5LTllNjItZmYyMjk3NjhhNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxM2E1NzllYjhhMzU1MWIyYTlmOGIxYjkxY2U4MzIxMTY4Mjk5YTNmNTQwYmZmNTc0YWEzMjhjNGE0NDdlNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGpHPKMzIrjc6-XNKpNK3xL546hidZSSeDPUwmKrG20">
> After updating to 2.4.7-p1 instance:
> 
> <img alt="Screenshot 2024-07-31 at 2 24 04 PM" width="1440" src="https://private-user-images.githubusercontent.com/60198592/353766030-8edd40aa-65fa-4ec5-99d9-7a0c79c880f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE5MzEsIm5iZiI6MTcyMjQyMTYzMSwicGF0aCI6Ii82MDE5ODU5Mi8zNTM3NjYwMzAtOGVkZDQwYWEtNjVmYS00ZWM1LTk5ZDktN2EwYzc5Yzg4MGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNzhiNTY0NTI3YjhmMTU3MjVkNzdlYTc5MzFlZjVmNDVhYjUxNzBmOTI4NzI2NTJjZTEwMmRkY2FlZmE4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMbsEhEKa1y8f1lmF-ztZs5ZlwuBSCS_HDFjP27tDzY"> <img alt="Screenshot 2024-07-31 at 2 23 43 PM" width="1440" src="https://private-user-images.githubusercontent.com/60198592/353766010-a8b97d81-0b95-4d0f-8d01-0f6625bf4996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE5MzEsIm5iZiI6MTcyMjQyMTYzMSwicGF0aCI6Ii82MDE5ODU5Mi8zNTM3NjYwMTAtYThiOTdkODEtMGI5NS00ZDBmLThkMDEtMGY2NjI1YmY0OTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjg5ZDY1MTE3MWZhYmVhODE4ZDk1MTJkMDY2ZmVhNWVhMjU4NzdmOGVlMGIwOTQ1ZWQ3MzRlNzQzNDY3OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AnJpxxJxSkEYWKXLS5E5N0opWklWlXeg7zxk4or08B4">

Should I try to need to use 2.4.7-p1 ??

**Comment by hostep** [comment]
I would suggest you read the warning with yellow background in your screenshot and update composer v1 to v2. I'm not sure if the composer plugins shipping with Magento > 2.4.5 are still compatible with composer v1. Switching to composer v2 should hopefully give you better results.

But please, this is not a Magento bug, this is a user problem, so this ticket should be closed.
It's probably better to move the discussion to https://magento.stackexchange.com/ or https://community.magento.com/ in case you still run into problems after switching to composer v2.

**Comment by hemendrametawolf** [comment]
As suggestion i changed magento version to 2.4.7-p1 and updated composer i am getting this 
![image](https://github.com/user-attachments/assets/0c3fb3b5-c02f-40c8-b29d-08b4dbbf66ec)

**Comment by hostep** [comment]
It sounds to me that the following line in your `composer.json` file is not set to `stable`, can that be?
```json
"minimum-stability": "stable"
```

So it sounds like you're dealing with an ancient version of `composer.json` and you didn't update it properly during Magento upgrades.

I would suggest you create an empty directory and inside that directory you run the following command:
```shell
composer create-project --no-install --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.7-p1 .
```

It will ask you for authentication and after you've given it the correct username and password, you should see a clean `composer.json` file (for Magento 2.4.7-p1) in that new directory.

Use that `composer.json` file to compare it to your own and figure out the changes you need to apply to your own.
Or use that `composer.json` file as a base and append changes from your own (like added dependencies).

This should hopefully get you further.

**Comment by hostep** [comment]
It's up to you to figure it out now, sorry, github is meant for reporting bugs and feature requests, not to help out with user problems.

I think you have enough info to continue now, this ticket can be closed in my opinion @engcom-Dash

**Comment by engcom-Delta** [comment]
Hi @hostep ,

Thanks for contribution. As per your comment we are closing this issue.

@hemendrametawolf , Please feel free to reopen issue if you are still facing.
