### ISSUE TITLE
POST /V1/customers api issue

### ISSUE THREAD

**Issue by ShehzadAhm** [magento/magento2#38994]
### Preconditions and environment

- Magento version 2.4.5-P8
- Should have at least one website

### Steps to reproduce

1. Create an integration and get the access token
2. Using the token, make a call to POST /V1/customers API to create customer

### Expected result

- <https://example.magento.test>/rest/<store_code>/V1/customers api should work

### Actual result

Getting 400 Bad request error:
{
    "message": "Specified request cannot be processed."
}

<img width="851" alt="image" src="https://github.com/user-attachments/assets/75844d76-c528-4fd8-8f36-8e9772b28f43">

### Additional information

API Documentation: https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-create-customer/

But the api works if the endpoint is: <magento_url>/<store_view_code>/rest/V1/customers (client project)

<img width="851" alt="image" src="https://github.com/user-attachments/assets/800dba6b-9462-4e06-ad6b-4c7449f3737d">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ShehzadAhm** [comment]
@magento give me 2.4.5-p8 instance

**Comment by ShehzadAhm** [comment]
Tested with the provided instance:
`POST <magento-url>/rest/<store_code>/V1/customers` throws error
<img width="859" alt="image" src="https://github.com/user-attachments/assets/328a7c40-4047-4725-a323-ff7674551c02">

`POST <magento-url>/rest/<store_view_code>/V1/customers` works fine
<img width="860" alt="image" src="https://github.com/user-attachments/assets/50d267e1-4ea9-479a-bf31-63a6bde1090c">

However, the first API endpoint is given in the [documentation](https://developer.adobe.com/commerce/webapi/rest/tutorials/orders/order-create-customer/).

[NOTE: In my client project, only this endpoint is working: `<magento_url>/<store_view_code>/rest/V1/customers`!]

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @ShehzadAhm  ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and it is reproducible.
Hence, Confirming the issue.

Steps to reproduce - 
1. Create one or multiple websites.
![image](https://github.com/user-attachments/assets/8f70af8e-0bbf-4717-b2ad-81be878eaa8f)
2. Generate Access Token
3. Run Create Customer API with store code.
![image](https://github.com/user-attachments/assets/1a161598-133d-4433-9d56-6b7151b99edc)
Observe Error displays when user provide store code.
4. Now, Run Create Customer API with store view code.
![image](https://github.com/user-attachments/assets/2c77b6b1-b1a6-45a1-8fb4-8e63ce60e229)
API runs successfully with store view code but displays error with store code.

As per dev doc - 
![image](https://github.com/user-attachments/assets/2b60e782-ee53-4601-b380-6bde45518b9d)

Thanks.

**Comment by engcom-Delta** [comment]
Hi @ShehzadAhm ,

Thanks for your reporting and collaboration. We are closing the ticket as issue is related to dev docs.
You can refer https://github.com/magento/devdocs/issues/9561 to see the updates.

Thanks.
