### ISSUE TITLE
Unable to create shipping label from backend

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#3899]
There is no 'Create Shipping Label' checkbox while submitting shipping information.
## Steps to reproduce
1. Configure store information
   ![1](https://cloud.githubusercontent.com/assets/11070293/14061404/f8d8f704-f3b1-11e5-85a7-5da5ba5edf22.PNG)
2. Configure shipping method
   ![2](https://cloud.githubusercontent.com/assets/11070293/14061412/2813636a-f3b2-11e5-997e-4a3e2f19b4ac.PNG)
3. Create an order from front-end
4. Submit shipping information from backend
## Expected result
1. 'Create Shipping Label' checkbox should be available
## Actual result
1. No checkbox

![3](https://cloud.githubusercontent.com/assets/11070293/14061433/bb95e860-f3b2-11e5-9005-c4823695e7d1.PNG)

**Comment by NadiyaS** [comment]
Hi @Pakkapao ,
shipping label is not allowed for offline shipping methods. Flat Rate is offline shipping method. 
Shipping labels feature is implemented for the following shipping carriers: UPS, USPS, FedEx, DHL.
Issue is closed as not a bug.

**Comment by JuliaGosling** [comment]
I have the same issue and I feel it is a bug.  I'm using Australia Post as my carrier and I need to print shipping labels and packing slips, so I feel there should be an option to do so?!

**Comment by shashikant-wagh** [comment]
Same here, working for a client who is shipping carrier  not able to print shipping labels

**Comment by MichaelJamesParsons** [comment]
I have a client who uses fixed table rates to calculate shipping prices on his website. Behind the scenes, he ships all of his orders through USPS. He would like to create USPS shipping labels for his orders, even though the order's shipping was calculated with table rates.

Ideally, Magento would allow store owners to create their own shipping labels regardless of which vendor the customer selected.

**Comment by sanket-adhvaryu** [comment]
I guess it is a bug.
We are using FedEx for as shipping method and it is allowing Magento admin to create the shipping label.
Shipping Calculation is working fine at frontend, submitting shipment does work well but shipping label not.
