### ISSUE TITLE
Problem with Magenta services

### ISSUE THREAD

**Issue by Iambusy0504** [magento/magento2#39005]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

As a level 1 employee I am missing key functions on magenta, this includes the ability to backorder orders and the ability to email invoices to patients. 
When I go onot a patients profile by selecting a patient's profile via the edit button, their isn't a create order button on my account so I can backorder glasses incase there is an issue with the glasses. 
In addition if I select a previous order and go to the invoice their should be an option to email the invoive to the customer however their isn;t the option to

### Expected result

As a level 1 employee I am missing key functions on magenta, this includes the ability to backorder orders and the ability to email invoices to patients. 
When I go onot a patients profile by selecting a patient's profile via the edit button, their isn't a create order button on my account so I can backorder glasses incase there is an issue with the glasses. 
In addition if I select a previous order and go to the invoice their should be an option to email the invoive to the customer however their isn;t the option to.

### Actual result

As a level 1 employee I am missing key functions on magenta, this includes the ability to backorder orders and the ability to email invoices to patients. 
When I go onot a patients profile by selecting a patient's profile via the edit button, their isn't a create order button on my account so I can backorder glasses incase there is an issue with the glasses. 
In addition if I select a previous order and go to the invoice their should be an option to email the invoive to the customer however their isn;t the option to.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Iambusy0504** [comment]
Here is a screenshot of the issues I experience.
When I am on a customer's profile and I select their order or I am on their
order and select the invoice tab a pop up comes up saying 'Attention
something went wrong' after I close the pop up there is still a red bar on
the order profile stating Something went wrong with processing the default
view and we have restored the filter to its original state.

**Comment by engcom-Bravo** [comment]
Hi @Iambusy0504,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
