### ISSUE TITLE
Um ou mais indexadores são inválidos. Certifique-se que o seu Magento Cron Job está ativo.

### ISSUE THREAD

**Issue by Befer-B4am** [magento/magento2#39017]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Um ou mais [indexadores são inválidos]
Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

### Steps to reproduce

Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

### Expected result

Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

### Actual result

Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

### Additional information

Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

### Release note

Magento versão 2.4.6-p3

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Befer-B4am** [comment]
Magento versão 2.4.6-p3

**Comment by Befer-B4am** [comment]
Um ou mais [indexadores são inválidos](https://www.b4am.com.br/admin_1snjo2/indexer/indexer/list/key/62dbc9730482c988924a2b4a32707df612d7cbecb7ade681eec2d0a0a222c791/). Certifique-se que o seu [Magento Cron Job](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#create-or-remove-the-magento-crontab) está ativo.

**Comment by engcom-Bravo** [comment]
Hi @Befer-B4am,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/issues/39017#issuecomment-2272666225 please post the issue in English language so we can proceed further.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @Befer-B4am,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
