### ISSUE TITLE
Um ou mais indexadores são inválidos. Certifique-se que o seu Magento Cron Job está ativo.

### ISSUE THREAD

**Issue by Befer-B4am** [magento/magento2#39012]
Estou recebendo o erro no título e não sei como corrigi-lo. Os produtos da árvore de produtos não aparecem quando clico na aba de produtos da minha loja. 

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Befer-B4am** [comment]
Magento versão 2.4.6-p3

**Comment by Befer-B4am** [comment]
Magento version 2.4.6-p3          esta é a versão

**Comment by Befer-B4am** [comment]
@magento 2.4.6-p3

**Comment by engcom-Bravo** [comment]
Hi @Befer-B4am,

Thanks for your reporting and collaboration.

To help us process this issue we recommend that you add the following information:

- Summary of the issue,
- Information on your environment,
- Steps to reproduce,
- Expected and actual results.


Thanks.
