### ISSUE TITLE
CSP issues combined with dev/css/use_css_critical_path

### ISSUE THREAD

**Issue by jemoon** [magento/magento2#39020]
### Preconditions and environment

- Magento version: 2.4.7-p1

### Steps to reproduce

1. Enable `dev/css/use_css_critical_path` in order to facilitate critical CSS functionality
2. Add some items to cart
3. Visit checkout page

### Expected result

Checkout pages are rendered with proper css styles

### Actual result

Restricted CSP policy (introduced in 2.4.7 for checkout pages) prevents inline js to be executed so CSS files which were supposed to be loaded asynchronously are never loaded.

Dev Console gives such output:
<img width="1682" alt="Screenshot 2024-08-07 at 14 50 21" src="https://github.com/user-attachments/assets/27b5e8ef-e09f-4719-a3a6-e7a7569fbbca">

For following elements:
<img width="1319" alt="Screenshot 2024-08-07 at 14 55 20" src="https://github.com/user-attachments/assets/85c1349f-211a-4cd1-b011-064e7c2ebdec">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @jemoon,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

<img width="1420" alt="Screenshot 2024-08-09 at 12 15 19" src="https://github.com/user-attachments/assets/e36d243b-88fe-4a25-8901-75806ba74b27">

Dev Console giving an error.

Hence Confirming the issue.

Thanks.

**Comment by Mohamed-Asar** [comment]
@magento i'm working on this
