### ISSUE TITLE
Using MAGENTO_DC_{path} environment variables is only partly implemented

### ISSUE THREAD

**Issue by LeanderFS** [magento/magento2#39026]
### Summary

The comments inside `vendor/magento/framework/App/DeploymentConfig.php` seem to suggest that it should be possible to set deployment configuration using environment variables only. After testing this it seems that this only works partly, as the environment variable is only set in the `$this->flatData` array and not in the `$this->data` array. Resulting in conflicting configuration and key collisions.

### Examples

Snippet of the method responsible for loading the deployment configuration seems to suggest deployment configuration can be set using environment variables only. Note that the there are 2 arrays being created, `$this->data` and `$this->flatData`. The value of the environment variable is correctly added in `$this->flatData`, but is absent in `$this->data`. Both arrays are being used to load deployment configuration.

 `\Magento\Framework\App\DeploymentConfig::load`
```php
private function load()
{
    if (empty($this->data)) {
        $this->data = array_replace(
            $this->reader->load(),
            $this->overrideData ?? [],
            $this->getEnvOverride()
        );
        // flatten data for config retrieval using get()
        $this->flatData = $this->flattenParams($this->data);

        // allow reading values from env variables by convention
        // MAGENTO_DC_{path}, like db/connection/default/host =>
        // can be overwritten by MAGENTO_DC_DB__CONNECTION__DEFAULT__HOST
        foreach (getenv() as $key => $value) {
            if (false !== \strpos($key, self::MAGENTO_ENV_PREFIX)
                && $key !== self::OVERRIDE_KEY
            ) {
                // convert MAGENTO_DC_DB__CONNECTION__DEFAULT__HOST into db/connection/default/host
                $flatKey = strtolower(str_replace([self::MAGENTO_ENV_PREFIX, '__'], ['', '/'], $key));
                $this->flatData[$flatKey] = $value;
            }
        }
    }
}
```

`\Magento\Framework\App\DeploymentConfig::getConfigData` returns deployment configuration from the `$this->data` array.
```php
public function getConfigData($key = null)
{
    $this->load();

    if ($key !== null && !isset($this->data[$key])) {
        return null;
    }

    return $this->data[$key] ?? $this->data;
}
```

`\Magento\Framework\App\DeploymentConfig::get` returns deployment configuration from the `$this->flatData` array.
```php
public function get($key = null, $defaultValue = null)
{
    $this->load();
    if ($key === null) {
        return $this->flatData;
    }

    if (array_key_exists($key, $this->flatData) && $this->flatData[$key] === null) {
        return '';
    }

    return $this->flatData[$key] ?? $defaultValue;
}
```

### Proposed solution

If this method of setting deployment configuration is supported (as suggested by the comments), make sure the environment variable values are being propagated to both the `$this->data` and the `$this->flatData` array. On a related note, documenting this somewhere in the devDocs would be an amazing addition and would make the lives of a lot of devops engineers a lot easier working with Magento 2.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @LeanderFS,

Thanks for the report and collaboration!

We have gone through the issue description and also the file mentioned in the description https://github.com/magento/magento2/blob/6f4805f82bb7511f72935daa493d48ebda3d9039/lib/internal/Magento/Framework/App/DeploymentConfig.php#L7

But we are not able to get the comment which says the below:
> seem to suggest that it should be possible to set deployment configuration using environment variables only.

Can you please elaborate more on this?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @LeanderFS,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we assume it's been resolved and will close it. Feel free to open a new ticket or reopen this one if you need more help.

Regards
