### ISSUE TITLE
Shipping is not showing in checkout magento2?

### ISSUE THREAD

**Issue by ahamedkislakci** [magento/magento2#3902]
Hello,

Installed the Magento2 ver. 2.0.2 in my host.Added some Products for testing purpose.In front end checkout page shipping information is not showing.

![error1](https://cloud.githubusercontent.com/assets/17543370/14062937/f85e6c44-f3a9-11e5-9b7a-8ddaf922c992.jpg)

Website: [http://justpatisserie.co.uk/](http://justpatisserie.co.uk/)

Pls help me :(

**Comment by ishakhsuvarov** [comment]
@ahamedkislakci Looks like you have added a Virtual Product (product with no weight) to your shopping cart. In this case Shipping section of checkout is not shown. Please try with the different product, which has weight, and let us know if it worked.
Thank you.

**Comment by ahamedkislakci** [comment]
@ishakhsuvarov Thanks so much. Now working. Thanksssssss

**Comment by ishakhsuvarov** [comment]
@ahamedkislakci Thanks for the update. Closing this ticket for now, if you have any additional questions please feel free to reopen.

**Comment by PhilippLak** [comment]
Hi, 
I got the same problem with the shipping costs. I have tried it with one product to change the weight and it works perfectly, thanks for that.

No I need to change the weight option of all my 2.000 products.

Is there any way to do it fast, like an multiple editor?

Would appreciate your help.

Thanks in advance.

**Comment by serefatka** [comment]
I have te same issue magento 2.2.2. I changed weight to 2kg in configurable product and in virtual products and still no shipping tab in the checkout.

@PhilippLak you can export products to csv update weight and import file back to magento
System->Data Transfer-Export.

**Comment by maniecodes** [comment]
Thanks it worked

**Comment by MustafaElKhalifa** [comment]
Thanks that works well
