### ISSUE TITLE
Registered shipping rates validators are not running

### ISSUE THREAD

**Issue by kooliahmd** [magento/magento2#39039]
### Summary

Following this [documentation](https://developer.adobe.com/commerce/php/tutorials/frontend/custom-checkout/add-carrier-validation/) in order to register a custom shipping rate validator, I found out that `shipping-rates-validator.js::validateAddressData` would never execute the registered validator as long as the default validator returns true.

This is because `shipping-rates-validator.js` registers a `default-validator` and when it runs the validation it considers the rates as valid when **at least** on of the registered validators returned true.
This is problematic, as the custom validator would not even run when the default validator returns true.

### Examples

N/A

### Proposed solution

Change this function  `validateAddressData` in `module-checkout/view/frontend/web/js/model/shipping-rates-validator.js`

From:
```
        validateAddressData: function (address) {
            return validators.some(function (validator) {
                return validator.validate(address);
            });
        },
```        

To:
```
        validateAddressData: function (address) {
            return validators.forEach(function (validator) {
                return validator.validate(address);
            });
        },
    ```    

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @kooliahmd,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest 2.4-develop branch. In order to reproduce it we have made a custom module as follows:

https://github.com/engcom-Hotel/magento2/tree/issue39039/app/code/Magz/Issue39039

But we are unable to reproduce it, can you please let us know if we missed anything?

Thanks
