### ISSUE TITLE
Improvement on catalog product create/edit page

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#3903]
## Steps to reproduce
1. M 2.0.2
2. go to admin panel -> Products -> Catalog -> edit product
3. open Images and Videos tab, click on image - dialog is shown
4. open source of page
## Actual result
1. each time, when modal dialog is created, the old one isn't removed from DOM => when I choose images a lot of time, I got this  
   ![desctop screenshot](https://cloud.githubusercontent.com/assets/10142848/14062966/8eb556aa-f3bc-11e5-91d7-f2c399e8fad8.png) which makes using current / active dialog inconvenient using JS.
## Expected Result
1. I should get one dialog, or at least one dialog per chosen image - it should not be duplicated.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improvement-on-catalog-product-create-edit-page/idi-p/45281).
