### ISSUE TITLE
Failed loading Admin Sale Orders

### ISSUE THREAD

**Issue by jvpatel** [magento/magento2#3904]
## Steps to reproduce
1. Install Magento 2.0
2. Setup, and Configure a Standard PayPal checkout (SSL: Disabled, Sandbox: Yes)
3. [Example] Add any product in a cart
4. Checkout cart using PayPal
5. Transaction succeeded. Message displayed "We will email you ......"
6. Navigate into Admin > Sale > Orders (In order to view orders)
7. Failed to load, and spinner goes on.

![image](https://cloud.githubusercontent.com/assets/6893514/14063170/7ad54bc4-f392-11e5-9505-2276c9905195.png)

![image](https://cloud.githubusercontent.com/assets/6893514/14063185/443927d8-f393-11e5-8e6c-146ce755dd74.png)

http://example.com/magento/admin_1234/mui/index/render/key/2d746eec71871b2ef4b1740eb1b2cb03a7270ca52cc9c79c05e36db425766c1e/?namespace=sales_order_grid&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=actions&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true **_HTTP/1.1" 503 853_**
## Expected result
1. Error should not have been thrown. All orders should be viewable
## Actual result
1. [Example] Error message appears: "Attention. Something went wrong"

**Comment by sammarcus** [comment]
When the generic _"Attention. Something went wrong"_ appears, is there a conclusive location a more detailed error is written to a log? I am not finding it in any of the normal logs or reporting functions.

**Comment by anton-huz** [comment]
@sammarcus. Do you mean Magento App should provide more details with such type of errors?

**Comment by jvpatel** [comment]
Well, I already caught the error in a browsers network. Some kind of special characters are passed in search, this error can't be caught in logs created by Magento. I wonder, why are the strange values passed on loading a tab? It should go ahead with the default values or none. 

On switching a tab following http request is made, which contain bad values:

http://example.com/magento/admin_1234/mui/index/render/key/2d746eec71871b2ef4b1740eb1b2cb03a7270ca52cc9c79c05e36db425766c1e/?namespace=sales_order_grid& search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=actions&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true HTTP/1.1" 503 853

However, the issue seems to be happening after setting up the paypal modules from the admin panel.

Yes, Magento App should provide more details with such type of errors. Database logging would be great!

**Comment by piotrekkaminski** [comment]
We have plans to address more "something went wrong" errors in next release. Internal ticket MAGETWO-52217

**Comment by iwdjoe** [comment]
Hi.
Do you have any update on this?
Our client has this issue on Magento EE as well.
Version 2.1.0

Please advise.
Thank you!

**Comment by magento-engcom-team** [comment]
@jvpatel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by pravalitera** [comment]
Same problem here after 7 months in production and 17221 orders on a 2.1.3

I configured Varnish :
     -p http_resp_hdr_len=65536 \
     -p http_resp_size=98304 \

And increased timeout in nginx...  The loading time is horrible (~ 2 min), but it works...

That would be cool if Magento could do more testing with proper databases... It's obvious that test with "big databases" are not done.
