### ISSUE TITLE
Unable to change address in checkout and not showed correctly

### ISSUE THREAD

**Issue by LaurensGoedel** [magento/magento2#39045]
### Preconditions and environment

Magento 2.4.7-p2
Default Luma template

### Steps to reproduce

1. Sign is a customer
2. Make sure you have multiple addresses
3. Add a product to the cart
4. Proceed to checkout
5. Try to change the address to another address

### Expected result

Addresses are correctly displayed with multiple lines. And it should be possible to change to a different address for delivery.
Same for billing address

### Actual result

Address is not fully displayed and it is impossible to change to a different address

![image](https://github.com/user-attachments/assets/e155c179-3bee-47b5-914c-727bf9ea8749)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @LaurensGoedel ,

Thanks for your reporting and collaboration.
We have verified the issue in magento 2.4.7-p2, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Install magento 2.4.7-p2
![image](https://github.com/user-attachments/assets/07c315de-eb05-445c-9c1e-9081b5e4050f)

2. Access frontend
3. Signup and add multiple addresses
![image](https://github.com/user-attachments/assets/2bd5d3f7-6ade-42e5-968e-f16866d87a24)
4. Add an item to cart and navigate to checkout
5. Observe added addresses are displaying as expected
![image](https://github.com/user-attachments/assets/e171f902-67fd-421d-b8ee-c231db1fd5b0)
Add additional address in checkout and observe the view.
Addresses are aligned as expected.
Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by LaurensGoedel** [comment]
@engcom-Delta apparently our clean install wasn't so clean.. Problem was in external module.
