### ISSUE TITLE
Magento\Framework\MessageQueue\PublisherInterface::publish() should never (ever) be called from code which is inside of active DB transaction

### ISSUE THREAD

**Issue by pczerkas** [magento/magento2#39053]
### Preconditions and environment

- Magento version: any version

### Steps to reproduce

If queue message is published inside of open DB transaction, and message consumer processes it faster then DB transaction is commited, then message consumer (which is separate process from publisher) has not consistent view on data in DB, which leads to bugs.

### Expected result

Queue messages can only be published, if calling code is NOT inside of active DB transaction.

### Actual result

Queue messages ARE published, when calling code IS inside of active DB transaction. 

Example: https://github.com/magento/magento2/blob/6f4805f82bb7511f72935daa493d48ebda3d9039/app/code/Magento/AsynchronousOperations/Model/BulkManagement.php#L131
```
            $this->entityManager->save($bulkSummary);

            $this->publishOperations($operations);

            $connection->commit();
```

### Additional information

Problem can be resolved (in ideal scenario) by adding before plugin on interface Magento\Framework\MessageQueue\PublisherInterface::publish(), which checks if getTransactionLevel() on any active DB connection is not greater than 0.

This would probably be backward-incompatible change.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @pczerkas,

Thank you for the report and collaboration!

Can you let us know in which module or while calling which consumer this issue has occured.

**Comment by pczerkas** [comment]
> Can you let us know in which module or while calling which consumer this issue has occured.

Hi @engcom-November , this issue is about general design here.

We've seen that problem happening in consumer `async.operations.all` - sometimes first operation in bulk is not marked as done in DB.

**Comment by pczerkas** [comment]
@engcom-November , please look at https://github.com/magento/magento2/pull/39057 where is proposed fix. Looks like tests are passing OK.

**Comment by engcom-Hotel** [comment]
Hello @pczerkas,

Thank you for the report and your collaboration!

Your description seems valid to us. However, could you please provide details of the real-world scenario in which the flow is failing? We will try to replicate the scenario on our end to see if the issue is reproducible.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @pczerkas,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks
