### ISSUE TITLE
Design Section in Admin actually opens Search Engine Robots Section

### ISSUE THREAD

**Issue by sangatpedas** [magento/magento2#3906]
## Steps to reproduce
1. Go to Stores -> Configuration -> General -> Design
## Expected result
1. Get the screen where you can set the active theme
## Actual result
1. It opens the "Search Engine Robots" screen
   <img width="1310" alt="screen shot 2016-03-27 at 11 20 38 am" src="https://cloud.githubusercontent.com/assets/5317971/14063832/51258902-f40e-11e5-9c3c-42c05c382f3a.png">

This is actually a long time bug already but I thought it would be too obvious for me to mention.

**Comment by antboiko** [comment]
Hello @sangatpedas , thanks for your inquiry. 

Theme Management functionality was moved to Admin >> Content >> Design >> Configuration. 

I'm closing this ticket for now, please feel free to reopen if you have any additional questions.

Best,
Anton.

**Comment by chiranjit007** [comment]
hello i am new in magento and i have same problem .so what can i do..?

**Comment by chiranjit007** [comment]
pls give an idea....

**Comment by antboiko** [comment]
@chiranjit007 you can find Theme Management functionality by navigating to Admin >> Content >> Design >> Configuration.

**Comment by qrider** [comment]
You might update the documentation here => http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html 
It still references the old location.

**Comment by onotole404** [comment]
How the shitcoders from Magento fuckin head off all the developers.
Why can't they check everything mindfully first and only then do release?!
