### ISSUE TITLE
PHP 8.2.15 removed FTP extension

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#39083]
### Preconditions and environment

- Magento version >= 2.4.7
- PHP >= 8.2.15
- Configuring the FTP CSV it gives you the error below
```
details error :  Call to undefined function Magento\Framework\System\ftp_connect()
```

### Steps to reproduce

Configure CSV import via FTP using admin panel.

### Expected result

The connection is established, and we started working on importing the CSV via FTP.

### Actual result

An exception is thrown, logging the error below.
```
details error :  Call to undefined function Magento\Framework\System\ftp_connect()
```

### Additional information

*No response*

### Release note

*No response*

### Triage and priority

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [X] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

**Comment by rafaelstz** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Hello @rafaelstz,

Thank you for the report and collaboration!

This might be an issue if the vendor of the php does not include ftp as a extension by default, hence confirming the issue.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12857 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12857-v2.0&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
