### ISSUE TITLE
setup:db:status not working

### ISSUE THREAD

**Issue by sheepfy** [magento/magento2#39093]
### Preconditions and environment

- Magento version latest on mariadb default settings

I wanted to have a timestamp not null column and I am not sure if this is a bug or not, but however, setup:db:status is not up-to-date without twitching a bit mariadb.

Note that on mysql with default settings, this problem is not there as mysql do not set, by default, any defaults on not null timestamp columns.

### Steps to reproduce

Create a db_schema.xml, make a new table (or modify existing one) to add a timestamp column, not null with no defaults.

```<column name="expire_at" xsi:type="timestamp" on_update="false" nullable="false"/>```

Run setup:upgrade
run setup:db:status

### Expected result

All modules are up to date.

### Actual result

Declarative Schema is not up to date
Run 'setup:upgrade' to update your DB schema and data.

### Additional information

It seems that mariadb actually adds the DEFAULT '0000-00-00 00:00:00' on every **NOT NULL timestamp columns**.

A fix would be to turn on this setting in mariadb **explicit_defaults_for_timestamp**

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Adobe already recommends in their documentation to enable `explicit_defaults_for_timestamp`, see point 8 under the 'Configuring the database instance', [here](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/database-server/mysql#configuring-the-database-instance).

**Comment by sheepfy** [comment]
Thanks, I'll close this
