### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://magento.local/index.php/api/v2_soap/index/?wsdl=1' : failed to load external entity

### ISSUE THREAD

**Issue by yssource** [magento/magento2#3909]
On my /etc/hosts, I add 
`127.0.0.1        magento.local`

In the backend of my site, setting "Not Secure Base URL" with "http://magento.local/"
and "Secure Base URL" with "http://magento.local/" as well.

On nginx.conf, configure it 

```
server {
    listen      80;
    ...
}
```

and

```
upstream varnish {
    server 127.0.0.1:6081;
    server 127.0.0.1:8080 backup;
    keepalive 35;
}
```

On apache httpd.conf configure it
listen 8080 port

```
<VirtualHost *:8080>
...
</VirtualHost>
```
-  By browser "http://magento.local/api/v2_soap?wsdl=1", it would get the xml file successfully.
-  I try to do the soap api v2 with my script

```
<?php

$api_url_v2 = "http://magento.local/api/v2_soap/?wsdl=1";

$username = 'mobile';
$password = 'mobile123';

$cli = new SoapClient($api_url_v2);

//retreive session id from login
$session_id = $cli->login($username, $password);

//call customer.list method
$result = $cli->customerCustomerList($session_id);
```
-  But, it always gets an exception.

`SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://magento.local/index.php/api/v2_soap/index/?wsdl=1' : failed to load external entity "http://magento.local/index.php/api/v2_soap/index/?wsdl=1"`
-  After a long time research for this problem, I found it is an issue caused by port forwarding from 80 to 8080. If I set both of "Not Secure Base URL" and "Secure Base URL" with "http://magento.local:8080/" at backend. And change my script to be `$api_url_v2 = "http://magento.local:8080/api/v2_soap/?wsdl=1";`, everything is OK. 
- However, I need to use the nginx 80 port to work as reverse proxy and call the SOAP Api by script. 
- Is there any help for me?

**Comment by mazhalai** [comment]
@yssource Thank you, we have created ticket MAGETWO-51151 to investigate and fix.

**Comment by okorshenko** [comment]
@yssource Unfortunately we can not reproduce this issue. Could you please provide full config for varnish, nginx and apache.

**Comment by yssource** [comment]
It is my fault, since I have one rule in my nginx configuration file, which causes this problem to me. 
`if ($http_user_agent = "") { return 444; }`
After commenting this line out,  the script with "SOAP client" works for me now.

**Comment by okorshenko** [comment]
@yssource thank you for update.

**Comment by Puru2016** [comment]
Is there any fix for this issue?

**Comment by prakashsaran** [comment]
hi any body sugest me how to fix out this error 
Your Magento instance replied with an error when we tried to connect: 'SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://www.romoch.com/index.php/api/v2_soap/index/?wsdl=1'.
