### ISSUE TITLE
Validate V3 Recaptcha using server side

### ISSUE THREAD

**Issue by abhi0001-ch** [magento/magento2#39100]
### Summary

How we can validate V3 recaptcha with server side.

### Examples

How we can validate V3 recaptcha with server side.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @abhi0001-ch,

This is a forum to post issues or bugs related to core magento. You can raise queries as such on [magento stackexchange](https://magento.stackexchange.com/).
Hence closing this issue.

Thank you.
