### ISSUE TITLE
2.4.7 breaks child themes of blank

### ISSUE THREAD

**Issue by michaelarran** [magento/magento2#39105]
### Preconditions and environment

- Magento version: 2.4.7

### Steps to reproduce

Create / use a child theme of magento/theme-frontend-blank that overrides _extends.less.

### Expected result

The contents of _extends.less in the child theme should be included.

### Actual result

The child theme _extends.less should override the _extends.less from the blank theme.

### Additional information

This seems to be caused by a change in _sources.less of the blank theme in 2.4.7:
`@import '_extends.less';`
becomes:
`@import (reference) '_extends.less';`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @michaelarran,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we assume it's been resolved and will close it. Feel free to open a new ticket or reopen this one if you need more help.

Regards
