### ISSUE TITLE
Set Special price 0(Zero) of Last associate product of configurable product issue

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3912]
## Steps to reproduce
1. Login into the magento2 admin with your details.
2. Go to Products > Catalog > Open any configurable product(Create if you don't have a configurable product with its associate product).

3.Go to associate product Configurations from Product Details tab .. 
4. Click on the last associate product of that configurable product.
5. Set special price of that associate product to 0(Zero) and click save.
6. Open that configurable product on the front-end.
## Expected result
1. It should display 0(Zero) price on the front-end if we set zero price.
## Actual result
1. When you open that product on the front-end it gives error message like Configurable product "Chaz Kangeroo Hoodie" do not have sub-products.(Please check below screenshot)

![config_error](https://cloud.githubusercontent.com/assets/17308601/14072412/cf8d09f8-f4dd-11e5-8838-d4752d3cb3b7.png)

**Comment by mikeweis** [comment]
Thanks for submitting this bug. I have created internal ticket MAGETWO-51181 to track this issue.

**Comment by mikeweis** [comment]
This issue has been resolved and merged to develop. Feel free to let us know if you encounter any other issues.

**Comment by keyurshah070** [comment]
@mikeweis Thank you for resolving this issue.
