### ISSUE TITLE
How can i create a custom Database Trigger when install/upgrade module

### ISSUE THREAD

**Issue by ngoctai-nfq** [magento/magento2#39125]
### Summary

In my case, I want to create a custom Database trigger, that is quite complex to handle BEFORE UPDATE on a table.
For database tables, I can use the `db_schema.xml` file as well, but I don't know how to achieve the DB trigger.
I have tried to create a DataPatch file in `Setup\Patch\Data` and implement `DataPatchInterface` with raw SQL query to create a trigger. However, it got an error `DB schema cannot be in a transaction`, seems all of the migration codes are wrapped by transaction from Magento.

### Examples

Nope

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @ngoctai-nfq,

This is a forum to post issues or bugs related to core magento. You can raise queries as such on [magento stackexchange](https://magento.stackexchange.com/).
Hence closing this issue.

Thank you.
