### ISSUE TITLE
Mangento 2.4.7-p2 One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by AngeloZou** [magento/magento2#39121]
### Preconditions and environment

I installed Magento 2.4.7-p2, but the admin backend keeps prompting.
**One or more indexers are invalid. Make sure your Magento cron job is running.**
I have tried all possible solutions, but cannot find a solution.
- Ubuntu 24.04
- Magento 2.4.7-p2
- PHP 8.3
- Mysql 8.0
- elasticsearch 8.11.4
- apache2 2.4.58
- Composer 2.7.8
![Screenshot_1](https://github.com/user-attachments/assets/64c7f9f3-7165-4119-b6d8-1d19cbd10460)
![Screenshot_2](https://github.com/user-attachments/assets/2bf8e144-bdf1-4aa8-b0f6-a6512d2d52ed)
![Screenshot_3](https://github.com/user-attachments/assets/ed8752a7-932a-4a27-8ea3-0c37ccf33cc5)

### Steps to reproduce

1. Log in to the administrator backend.
2. Always remind：**One or more indexers are invalid. Make sure your Magento cron job is running.**
3. I tried all the methods, but the problem is still not solved.

### Expected result

No error message.

### Actual result

Admin backend keeps prompting
**One or more indexers are invalid. Make sure your Magento cron job is running.**
![Screenshot_1](https://github.com/user-attachments/assets/e8e3585e-47ae-4dc1-a57e-ffad3433b63a)

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @AngeloZou,

Thanks for your reporting and collaboration.

Could you please check your Elasticsearch version which will support to Magento Version.Please refer system requirements document https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements

Please let us know if you are still facing any issue.

Thanks.

**Comment by AngeloZou** [comment]
HI @engcom-Bravo 
I think it's an Elasticsearch problem. According to official requirements, I tested different versions.

I have successfully installed opensearch and solved this problem, by following this tutorial.
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/

Thank you.

**Comment by engcom-Bravo** [comment]
Hi @AngeloZou,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/39121#issuecomment-2315199053 we are closing this issue.please feel free to reopen the issue.

Thanks.
