### ISSUE TITLE
page builder was rendering for 5 seconds without releasing locks

### ISSUE THREAD

**Issue by anjali25021995** [magento/magento2#39120]
page builder was rendering for 5 seconds without releasing locks

We are getting the issue magento 2.4.7-p2, can you please anyone give me the solution

_Originally posted by @anjali25021995 in https://github.com/magento/magento2/issues/28706#issuecomment-2313224494_

**Comment by hostep** [comment]
This is a duplicate of https://github.com/magento/magento2/issues/39076, there is [a patch mentioned over there](https://github.com/magento/magento2/issues/39076#issuecomment-2306661703) you can try.

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your Contribution!!.

Hi @anjali25021995,

Thanks for your reporting and collaboration.

Please refer this comment https://github.com/magento/magento2/issues/39076#issuecomment-2306918383 and refer the commits.

Hence we are closing this as duplicte.

Thanks.

**Comment by Kishorchhugani** [comment]
Still an issue on 2.4.7-p4
I'm unable to save a block with HTML Element added via Page Builder.
sometimes products unable to save
cms pages unable to save
same error : Page Builder was rendering for 5 seconds without releasing locks.
