### ISSUE TITLE
Edit quote item with custom options will merge quote items with the same SKUs

### ISSUE THREAD

**Issue by Simonchik** [magento/magento2#39136]
### Preconditions and environment

Magento version 2.4.7-p1

### Steps to reproduce

- Add product with custom options to cart
- Add product with the same SKU but different custom options
- Go to shopping cart, where you should see the 2 different quote items
- Edit one of them

### Expected result

Only editing quote item should be changed

### Actual result

Quote items with the same SKUs will be merged to one

### Additional information

This is the commit where only SKUs are compares (ignoring the custom options): https://github.com/magento/magento2/commit/e9e80cf943e6a20b95fc155308ff487a554e225a?diff=split&w=0 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Simonchik,

Thanks for your reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/39114

Hence we are closing this as duplicate.

Thanks.
