### ISSUE TITLE
Order status change via admin does not wor for invoiced orders and custom order statusses

### ISSUE THREAD

**Issue by Tjitse-E** [magento/magento2#39141]
### Preconditions and environment

- Magento 2.4.7-p2

### Steps to reproduce

1. Go to the admin
2. Go to stores > Order status
3. Create a new order status, name it “New order status”
4. Assign the “New order status” to the state processing, make it the default status for the state processing.
5. Go to an order that’s invoiced
6. If it’s not yet on “New order status” (maybe it’s a historic order) place it on “New order status”
7. Now try to change it back to “Processing”

### Expected result

The order is changed to "Processing"

### Actual result

The order stays on "New order status" and you cannot change it.

### Additional information

Introduced in https://github.com/magento/magento2/commit/6653ce51671ef0cb7a8a1f2a64b1216972e114f2, in an attempt to fix https://github.com/magento/magento2/issues/36562.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution!!

Hi @Tjitse-E,

Thanks for your reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/38917

Hence we are closing this as duplicate.

Thanks.

**Comment by hostep** [comment]
Possibly fixed by https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c?
