### ISSUE TITLE
Create theme/child theme option

### ISSUE THREAD

**Issue by pynej** [magento/magento2#3914]
We create and customize lots of magenta systems and we would love to see a option in the Themes section to create a new theme and optionally attach it to a parent theme.  

This would just ask for the company name, theme name, and optional parent theme.  Then it would create the proper folder skeleton structure, create the registration.php and theme.xml files, and display the path to access and update it via FTP with simple instructions.  

It's somewhat overwhelming for a new admin to understand how the themes logic all works and a simplified screen to create themes like this would be helpful for new users as well.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Create-theme-child-theme-option/idi-p/44746).
