### ISSUE TITLE
Issue: Orders - Filter by Purchase Date gives an error

### ISSUE THREAD

**Issue by mc-christian** [magento/magento2#39144]
### Preconditions and environment

- Magento version: 2.4.7-p1

### Steps to reproduce

1. Go to the orders grid: Admin panel -> Sales -> Orders
2. Select Filters
3. Choose any dates for "Purchase Date" and Apply Filters

### Expected result

Magento will display orders during the selected date range

### Actual result

- Displays a warning "Attention - Something went wrong".
- Displays an error notification banner: "Something went wrong with processing the default view and we have restored the filter to its original state."

On the exception logs:
```
main.CRITICAL: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous in vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90
Stack trace:
#0 vendor/magento/framework/DB/Statement/Pdo/Mysql.php(90): PDOStatement->execute()
#1 vendor/magento/framework/DB/Statement/Pdo/Mysql.php(106): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}()
#2 vendor/magento/framework/DB/Statement/Pdo/Mysql.php(89): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute()
#3 vendor/magento/zend-db/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute()
#4 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#5 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(242): Zend_Db_Adapter_Abstract->query()
#6 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(614): Zend_Db_Adapter_Pdo_Abstract->query()
#7 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(639): Magento\Framework\DB\Adapter\Pdo\Mysql->Magento\Framework\DB\Adapter\Pdo\{closure}()
#8 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(614): Magento\Framework\DB\Adapter\Pdo\Mysql->performQuery()
#9 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(703): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#10 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#11 vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll()
#12 vendor/magento/framework/Data/Collection/AbstractDb.php(1011): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll()
#13 vendor/magento/framework/Data/Collection/AbstractDb.php(900): Magento\Framework\Data\Collection\AbstractDb->_fetchAll()
#14 vendor/magento/framework/Data/Collection/AbstractDb.php(793): Magento\Framework\Data\Collection\AbstractDb->getData()
#15 vendor/magento/framework/Data/Collection/AbstractDb.php(777): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter()
#16 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Data\Collection\AbstractDb->load()
#17 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->___callParent()
#18 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#19 generated/code/Magento/Sales/Model/ResourceModel/Order/Grid/Collection/Interceptor.php(32): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->___callPlugins()
#20 vendor/magento/framework/Data/Collection.php(340): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->load()
...
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mc-christian,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1375" alt="Screenshot 2024-09-06 at 10 56 26" src="https://github.com/user-attachments/assets/8e1a7a6e-f007-4e50-b466-150c36b91be1">


it is displaying all orders during the selected date range.

Kindly recheck the issue in latest 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by mc-christian** [comment]
@magento give me 2.4-develop instance

**Comment by mc-christian** [comment]
@engcom-Bravo thank you for looking into this.
I tried to reproduce it on the 2.4-develop instance but no success.
However, I'm still able to see the error happening on my local instance (brand new instance).
Anyway, I'm closing this issue for now.

**Comment by toantvlf** [comment]
> I am able to reproduce this error in 2.4.7-p4. The issue seems to be that the `sales_order` and `sales_order_grid` tables both have a `created_at` column in them, and the where clause does not specify which one it wants.
> 
> Here is the query from my exception log:
> 
> ```
> #54 {main} {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT `main_table`.*, `braintree_transaction_details`.`transaction_source`, `sales_order`.`dispute_status` FROM `sales_order_grid` AS `main_table`
>  LEFT JOIN `braintree_transaction_details` ON braintree_transaction_details.order_id = main_table.entity_id
>  LEFT JOIN `sales_order` ON sales_order.entity_id = main_table.entity_id WHERE  (((`created_at` >= '2025-03-10 04:00:00'))) AND (((`created_at` <= '2025-03-18 03:59:59'))) ORDER BY main_table.created_at DESC
> ```
f
fixed it in commit https://github.com/magento/magento2/commit/bc561134866637ff7841cf934b49727ee67b9339

**Comment by robbanl** [comment]
After updating to p5 (from p3) we now have double prefixes of the table.

```
...
 LEFT JOIN `sales_order` ON sales_order.entity_id = main_table.entity_id WHERE  (((`main_table`.`main_table`.`created_at` >= '2025-04-07 22:00:00'))) AND (((`main_table`.`main_table`.`created_at` <= '2025-04-22 21:59:59'))) GROUP BY `main_table`.`entity_id` ORDER BY main_table.created_at DESC
```

Reverting the change in the above commit fixes the issue.
