### ISSUE TITLE
Image Import Issue

### ISSUE THREAD

**Issue by MeJohan** [magento/magento2#3915]
I keeping getting error "Imported resource (image) could not be downloaded from external resource due to timeout or access permissions"
I'm using the google cloud platform and I upload all my images through ssh filezilla

 to opt/bitnami/apps/magento/htdocs/pub/media/import/
Also I couldn't find the solution on the net, even though other people are facing the same problems
https://community.magento.com/t5/Admin-Configuration-Questions/Unable-to-import-images/td-p/24009
It's really frustrating and painful anyway thanks in advance

**Comment by piotrekkaminski** [comment]
Forums and magento.stackexchange.com are better place for such questions. The issues we have seen so far are mostly images not existing or incorrect permissions.
