### ISSUE TITLE
Declaration compatibility issue while compilation after upgrade magento version 2.4.7-p2

### ISSUE THREAD

**Issue by kiwicommerceltd** [magento/magento2#39166]
### Preconditions and environment

- Magento version (2.4.7-p2)
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Upgrade to Magento 2.4.7-p2
PHP version 8.1.29
composer install
bin/magento setup:di:compile

### Expected result

Compile command executed successfully

### Actual result

Fatal error: Declaration of Magento\Setup\Console\Style\MagentoStyle::createProgressBar($max = 0) must be compatible with Symfony\Component\Console\Style\OutputStyle::createProgressBar(int $max = 0): Symfony\Component\Console\Helper\ProgressBar in /home/web/build/setup/src/Magento/Setup/Console/Style/MagentoStyle.php on line 322

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@kiwicommerceltd, I think your file `setup/src/Magento/Setup/Console/Style/MagentoStyle.php` is outdated. It should have `ProgressBar` declared as return type in Magento 2.4.7-p2, but that doesn't seem to be the case for you.

I suspect that the composer file marshalling failed and you are left with old files from an older Magento version in `setup/src`.

Can you try the following?
```
rm -R vendor/magento/magento2-base/
composer install
```

And see if that solves it? It should overwrite the files in `setup` with the correct files in theory.

**Comment by kiwicommerceltd** [comment]
@hostep That is not the case actually because the deployment is going through the pipeline, so while upgrading Magento the fresh code getting pulled

**Comment by hostep** [comment]
Sorry, but that's the only explanation I have, can you please double check?

This is how the file should look in 2.4.7-p2: https://github.com/magento/magento2/blob/2.4.7-p2/setup/src/Magento/Setup/Console/Style/MagentoStyle.php#L322, note that it has a return type defined `: ProgressBar`

According to your error message, your file is missing the return type definition.
Which is how the file was in for example Magento 2.4.6-p7 and earlier versions: https://github.com/magento/magento2/blob/2.4.6-p7/setup/src/Magento/Setup/Console/Style/MagentoStyle.php#L322

So please double check, I think something is going wrong in your deploy pipeline then?

**Comment by kiwicommerceltd** [comment]
@hostep The issue has been resolved now,
I completely removed the setup folder and replaced
This works for me. 
Thanks for your suggestions that helped me
