### ISSUE TITLE
GraphQl Schema Is Not Cached With Redis

### ISSUE THREAD

**Issue by m08110071** [magento/magento2#39168]
### Preconditions and environment

- Magento 2.4.7-p2
- Redis 7.2 and config requirepass 
- Config redis for cache and specific cache prefix id
- Enable all cache types

### Steps to reproduce

- Call any GraphQl query and debug to file: vendor/magento/framework/Config/Data.php:108

### Expected result

GraphQl schema is cached

### Actual result

GraphQl schema is not cached

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/86655a34-ad0e-4ee3-aa8c-c52b003ac872">

### Additional information

1.  I tried to debug and see this issue happen since below code added:

File: vendor/magento/module-catalog-graph-ql/etc/di.xml

`<virtualType name="Magento\Framework\GraphQl\Config\Data" type="Magento\Framework\Config\Data">
        <arguments>
            <argument name="cacheTags" xsi:type="array">
                
                <item name="EAV" xsi:type="string">EAV</item>
            </argument>
        </arguments>
    </virtualType>`

2. Some cases, cache is stored to file automatically

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by m08110071** [comment]
This is my PR to fix It:
https://github.com/magento/magento2/pull/39172

**Comment by engcom-November** [comment]
Hello @m08110071,

Thank you for the report and collaboration!

Not able to reproduce this on 2.4-develop with redis cache configured.
When calling the graphql query second time, the cacheId is being cached.

Please take a look at the screenshot below:
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/95e08e78-a04d-48d4-b824-681f4681f9d3">

And also the same key can be seen in redis as well:
<img width="610" alt="image" src="https://github.com/user-attachments/assets/13954030-3af2-4866-9465-a515b144cf65">

Please let us know if we are missing anything.

Thank you.

**Comment by m08110071** [comment]
Hi @engcom-November 

Please try to with Adobe Commerce 2.4.7-p2.

You can check my PR to resolve this issue to understand the issue. I debugged and see this issue happen because `EAV` is added as new Redis cache tag  at `vendor/colinmollenhour/credis/Client.php::_flattenArguments`.

**Comment by engcom-November** [comment]
Hello @m08110071,

Tried with 2.4.7-p2 community and commerce eddition with requirepass, but in both the cases this is not reproducible.
We are getting the same result:
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/3c9c77fb-bafe-4bdd-8a3d-8419740468d4">

Please let us know if there are any pre conditions required.

Thank you.

**Comment by engcom-November** [comment]
Hello @m08110071,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thank you.

**Comment by idziakjakub** [comment]
@m08110071 we have the same issue after upgrade Magento from 2.4.6-p8 to 2.4.7-p3 - all GraphQl queries take more than 7 seconds to execute because of problem with save data to Redis - there is example from New Relic:

![Image](https://github.com/user-attachments/assets/94cfd8ef-3662-4d7b-b37e-14387538bced)
![Image](https://github.com/user-attachments/assets/06de4429-1703-4170-b213-1f02a85707f6)

After applying your patch from here https://github.com/magento/magento2/pull/39172, loading time dropped to about 100ms!

![Image](https://github.com/user-attachments/assets/36e17cd8-9f41-4d45-8004-bbcbfd062d36)

I think this does not happen on every instance, you need to set the L2 cache and permanent cache settings (using an external Redis server and local per app instance): https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cache/level-two-cache

**Comment by cieslix** [comment]
@engcom-November we can also confirm the PR https://github.com/magento/magento2/pull/39172 fixes issue. To replicated this you must have REDIS in version 7.x on the version 6.x we have no issue.

**Comment by edas11** [comment]
We had this issue too. I think this issue depends on whether you have php redis extension or not. In our case it worked fine with php redis extension but without it graphql schema was not getting saved into cache.
