### ISSUE TITLE
Products not showing in category

### ISSUE THREAD

**Issue by OgreMHDW** [magento/magento2#3917]
## Steps to reproduce
1. Product is entered in Magento
2. Product is Enabled
3. Visibility set to Catalog,Search
4. Quantity set to 2
5. Inventory is In Stock
6. Product set to display on Main Website
7. Product is in a catagory
## Expected result
1. The front end category view show all products in the category.
2. The shopping options on the left shows the color of the product and when selected show the product.
3. The product is visible when using the URL key of the product.
## Actual result
1. The front end category view show shows only (1) older product.
2. The shopping options on the left shows the color of the product not shown but when selected states "We can't find products matching the selection."

![2016-03-28_173734](https://cloud.githubusercontent.com/assets/4369476/14094574/6966c37e-f50c-11e5-9df1-cbcd7c9abeeb.png)
![2016-03-28_173918](https://cloud.githubusercontent.com/assets/4369476/14094571/69624b14-f50c-11e5-9396-de20987ae72c.png)
![2016-03-28_173954](https://cloud.githubusercontent.com/assets/4369476/14094573/6965f0c0-f50c-11e5-9a70-ebcade45f4e6.png)
![2016-03-28_174024](https://cloud.githubusercontent.com/assets/4369476/14094572/6965890a-f50c-11e5-9e8d-a09a626d8375.png)
![2016-03-28_174103](https://cloud.githubusercontent.com/assets/4369476/14094570/6961e336-f50c-11e5-9963-b45d1415197b.png)
![2016-03-28_174126](https://cloud.githubusercontent.com/assets/4369476/14094569/69619b6a-f50c-11e5-82a2-1f40a12f3cd3.png)

**Comment by OgreMHDW** [comment]
This was resolved. I was able to assess that one index was stuck processing. I went into the database and found the indexer_state table. I followed the document http://magento.stackexchange.com/questions/93108/magento-ce-2-0-index-management-always-processing to set it to invalid and re-ran the indexing cron job. The site is now displaying the products.

**Comment by kartikasodariya17** [comment]
I have used new theme and when i create new product then it's not display on category page also i have do it indexing and cleaning the cache. can you please suggest me how can i resolve the issue ?

**Comment by jmxt3** [comment]
I'm with the same problem here....I have a bunch of products added to several categories and none is showing.

I'm getting the following message:
"We can't find products matching the selection."

Any idea what can be?

**Comment by mvistas** [comment]
jmachete, do you have solution already? I have the same issue here.

Thank you

**Comment by djfordz** [comment]
Having same issue
Magento 2.1.3 total products > 80,000
Having issue with product not showing in all categories, but shows oddly in category it is not assigned.

**Comment by drkaff** [comment]
I had this exact same issue. Products could be seen by going to the product page only. 

I went to the admin section and to the category and tried unassigning the products and it bugged out. 

That gave me enough info to reset permissions on my magento2 directory

"sudo chown -R :apache magento2"

Reindexed and cleared cache and everythings working!

**Comment by ghost** [comment]
Why was this issue closed ?

**Comment by dreamdev21** [comment]
The same issue here.
How can solve this issue correctly?

**Comment by kartikasodariya17** [comment]
I have solution of ur issues

**Comment by simpsonguy02** [comment]
Anyone have a solution for this? I have tried reindex and reset solutions and this did not fix issue for me?

**Comment by dynamicdreamz1** [comment]
Guys , any solution for not showing product on category page ?

**Comment by benvansteenbergen** [comment]
Hi, check out https://github.com/Itonomy/magento2-product-visibillitygrid. It will show all "conditions" for a product to show + a function to reindex it, when needed. Good luck!

**Comment by NiteshKuyate** [comment]
Same issue here also, tried reindexing after reset also.

**Comment by aneeqtariq143** [comment]
> Hi, check out https://github.com/Itonomy/magento2-product-visibillitygrid. It will show all "conditions" for a product to show + a function to reindex it when needed. Good luck!

I have installed visibilitygrid, It shows "Is visible in Category => No" for New Products. when I check  New products on Edit page, Visibilty Set to Catelog, Search. What should i do?

![Screenshot_7](https://user-images.githubusercontent.com/2074726/64909747-8e260c80-d729-11e9-91a8-72a7a6fede9f.png)

**Comment by gdesipremium1** [comment]
I'm facing the same issue. Any solution guys ?
