### ISSUE TITLE
Adding multiple products to cart with custom options GraphQL fails to compare custom options properly

### ISSUE THREAD

**Issue by dan-edan** [magento/magento2#39178]
### Preconditions and environment

Magento version 2.4.7-p2
PHP 8.3
Sample data installed via CLI
Add text field custom option to a product (I used SKU: 24-MB01)

### Steps to reproduce

1.  Send graphQL to init cart
```
mutation initCart {
  createGuestCart {
    cart {
      id
    }
  }
}
```

2.  Get the custom option UID from the product query
```
query ProductByUrl($url: String!) {
  products(filter: { url_key: { eq: $url } }, pageSize: 1) {
    items {
      uid
      name
      sku
      ... on CustomizableProductInterface {
        options {
          title
          uid
        }
      }
    }
  }
}
```
Using these variables
```
{
  "url": "joust-duffle-bag"
}
```

3.  With the cart ID from the previous command, send the graphQL to add products.  This will be the same product but with different custom options.
```
mutation AddProductsToCart($cartId: String!, $cartItems: [CartItemInput!]!) {
  addProductsToCart(cartId: $cartId, cartItems: $cartItems) {
    cart {
      items {
        product {
          name
          sku
        }
        ... on SimpleCartItem {
          customizable_options {
            customizable_option_uid
            label
            values {
              customizable_option_value_uid
              value
            }
          }
        }
        quantity
      }
    }
    user_errors {
      code
      message
    }
  }
}

``` 
Using these variables
```
{
  "cartId": "<CART-ID>",
  "cartItems": [
    {
      "sku": "24-MB01",
      "quantity": 1,
      "entered_options": [
        {
          "uid": "<CUSTOM-OPTION-ID>",
          "value": "This is a test 1"
        }
      ]
    },
    {
      "sku": "24-MB01",
      "quantity": 1,
      "entered_options": [
        {
          "uid": "<CUSTOM-OPTION-ID>",
          "value": "This is a test 2"
        }
      ]
    }
  ]
}
```

### Expected result

The cart should contain two products, each with a qty of 1, and both should have the respective custom option value.

### Actual result

The cart contains just one item with a qty of 2, and the custom option value is just that of the first item sent in the variables.

### Additional information

Adding products one at a time works as expected. However, performance suffers greatly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @dan-edan,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1433" alt="Screenshot 2024-11-18 at 10 04 39" src="https://github.com/user-attachments/assets/ff35013c-50be-4a49-8760-2affe5067b1d">



<img width="1433" alt="Screenshot 2024-11-18 at 10 05 10" src="https://github.com/user-attachments/assets/6f9c6a56-1013-419b-aa9d-8c6440008985">


The cart containing two items with a quantity of 1.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @dan-edan,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
