### ISSUE TITLE
Moving a category breaks GraphQL filter by URL path

### ISSUE THREAD

**Issue by xpoback** [magento/magento2#39183]
### Preconditions and environment

- Magento 2.4.7-p1
- Multistore setup

### Steps to reproduce

1. Create a category tree as follows:
Parent 1 (_url_path_: `parent-1`) -> Child 1 (_url_path_: `parent-1/child-1`)
Parent 2 (_url_path_: `parent-2`)

2. Send a GraphQL query (in my case with header `store: store_code`):
```graphql
query products {
  products(
    filter: {
      category_url_path: {
        eq: "parent-1/child-1"
      }
    }
  ) {
    total_count
  }
}
```
Expected and actual result: success response.

3. In admin area, move category Parent 1 into Parent 2:
Parent 2 (_url_path_: `parent-2`) -> Parent 1 (_url_path_: `parent-2/parent-1`) -> Child 1 (_url_path_: `parent-2/parent-1/child-1`)

4. Send a GraphQL query (in my case with header `store: store_code`):
```graphql
query products {
  products(
    filter: {
      category_url_path: {
        eq: "parent-2/parent-1/child-1"
      }
    }
  ) {
    total_count
  }
}
```
### Expected result

_Expected result:_
Moving a category correctly saves the saves all attributes so that everything keeps working, including GraphQL

Specifically here: a successful GraphQL response

### Actual result

**GraphQL error message** `"message": "No category with the provided `category_url_path` was found"` for a category that 

### Additional information

The reason behind this problem is that the `url_path` attribute values are correctly generated for the store but not for the default scope. 
The example for an affected category on the sample data in vanilla Magento after category "Men" was moved into "Gear":
```
[main]> select * from catalog_category_entity_varchar where value = 'gear/men/tops-men';
+----------+--------------+----------+-------------------+--------+
| value_id | attribute_id | store_id | value             | row_id |
+----------+--------------+----------+-------------------+--------+
|      330 |          120 |        1 | gear/men/tops-men |     12 |
+----------+--------------+----------+-------------------+--------+
1 row in set (0.000 sec)
```
As a result, there is a GraphQL error message. Adding a value for store 0 fixes the problem.

Here's an SQL query that shows which categories are affected after a move (has value for store ID 1 and no value for store ID 0):

```sql
SET @url_path_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code='url_path' AND entity_type_id=3);
SELECT ccev1.value
FROM catalog_category_entity AS cce
         LEFT JOIN catalog_category_entity_varchar AS ccev0
                   ON ccev0.row_id = cce.row_id AND ccev0.store_id = 0 AND ccev0.attribute_id = @url_path_id
         LEFT JOIN catalog_category_entity_varchar AS ccev1
                   ON ccev1.row_id = cce.row_id AND ccev1.store_id = 1 AND ccev1.attribute_id = @url_path_id
WHERE ccev0.value IS NULL
  AND ccev1.value IS NOT NULL;
```

Resaving the affected category (in admin area or programmatically) regenerates `url_path` and it starts working again.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @xpoback,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="577" alt="Screenshot 2024-11-06 at 10 27 35" src="https://github.com/user-attachments/assets/9ee7c219-6a36-4104-9725-ceb14f649a4d">



<img width="1390" alt="Screenshot 2024-11-06 at 10 27 46" src="https://github.com/user-attachments/assets/a7890ef6-c391-4be9-a328-2dacb905baa1">



We have moved category parent 1 into parent 2 and we got the successful response.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @xpoback,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Comment by xpoback** [comment]
@magento give me 2.4-develop instance

**Comment by xpoback** [comment]
@magento give me 2.4-develop instance

**Comment by xpoback** [comment]
@engcom-Bravo Have you passed the store header? Without the header, there is no error.

How can I get a Magento instance here? The bot doesn't seem to react on @magento give me 2.4-develop instance
