### ISSUE TITLE
FedEx Shipping unit blocked on LB

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#39187]
### Preconditions and environment

- Magento version: 2.4.7-p2
- FedEx shipping

### Steps to reproduce

1. Navigate to backend
2. Select Kilograms as Weight Unit
3. Create shipping label

### Expected result

Shipping label should be showing KG.

### Actual result

Shipping label weight unit is LB which can lead to pricing errors.

### Additional information

Our config:

<img width="806" alt="Capture d’écran 2024-09-19 à 12 08 35" src="https://github.com/user-attachments/assets/57aeb99b-1cd4-4013-9a07-056c562ddb29">

The request:

![image001](https://github.com/user-attachments/assets/97f36e6d-f13f-4ffb-a39e-7f1f3d86aa22)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Anju023** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
