### ISSUE TITLE
Limit guest user (actually all users) to use coupon only once

### ISSUE THREAD

**Issue by seansan** [magento/magento2#3918]
Request: build in simple functionality to inlcude guest users (hence their email) in the check if a coupon code is already used. @sonalagr
## Steps to reproduce
1. Suppose we set-up a coupon code that can only be used once
2. Guest users can check out with 2 orders and the coupon is still valid
## Expected result
1. Second order the coupon code is invalidated (client already ordered with that username OR e-mail
2. ...
## Actual result
1. User can use the coupon code again

Possible solution
- can be a setting in the backend to decide if we do or do ot want to include the check on email address for the count of number of times a coupon has been used

References
http://magento.stackexchange.com/questions/4785/magento-coupon-codes-only-one-coupon-guest-customer
http://magento.stackexchange.com/questions/33598/magento-coupons-limit-per-use-o-per-customer-not-working
https://github.com/magento/magento2/issues/776
https://community.magento.com/t5/Admin-Configuration-Questions/Coupon-One-Time-Use-for-Guest-User/td-p/23603
https://www.reddit.com/r/Magento/comments/2yq3vb/coupon_code_limit_1_use_per_coupon_not_working/
https://ecommerce.shopify.com/c/ecommerce-marketing/t/discount-code-limit-to-1-time-per-customer-154688

**Comment by sonalagr** [comment]
I have seen all these links but they don't provide any solution. 
What I want to check on email address for guest users,if email address already associated with any order and used the coupon code,then next time the coupon code won't be applied.

**Comment by seansan** [comment]
If you want to contribute to or report a missing feature you can do this
here. If you want other people to help you find a solution to a specific
problem and/or explain your problem and the steps you have taken to
investigate - maybe you can ask the question on stackexchange?
http://magento.stackexchange.com/.

**Comment by tkacheva** [comment]
Coupon enhancements are in the promotions backlog.  MAGETWO-51967

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Limit-guest-user-actually-all-users-to-use-coupon-only-once/idi-p/46051).

**Comment by seansan** [comment]
It was acknowledged ... and I dont believe in a FORUM being the proces and method to store important feedback and sometimes even code suggestions ... it will get lost, forgotten - the forum will be killed in 2018 or 2019 just like the previous one. I never understood why one did not open a simple uservoice account or JIRA account and log it there.
