### ISSUE TITLE
2 tables in AbstractDb

### ISSUE THREAD

**Issue by cs221313** [magento/magento2#3919]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. In Magento/Directory/Model/ResourceModel/Region.php, it has 2 tables, one is directory_country_region, another one is directory_country_region_name.
3. But when we save new region, AbstractDb only save the main table which is directory_country_region.

I guess for the current version we need to inherit the class AbstractDb and rewrite the saveNewObject method.

Is that the right way to solve this problem?

Thanks

**Comment by mazhalai** [comment]
Thank you @cs221313, we have created MAGETWO-51295 to investigate and fix.

**Comment by cs221313** [comment]
I just worked around by adding a plugin function for save of ResourceModel/Region.

**Comment by hshar7** [comment]
Hi @cs221313 which functionality in Magento allows you to add new region? Did you develop this feature? Because as far as I know the regions are added only during setup. Please give steps or use case.

**Comment by antboiko** [comment]
Hello @cs221313, kindly ask you to provide a response on comment above.

Thanks,
Anton.

**Comment by cs221313** [comment]
Hi, Anton,

Only US states was in the region table. If I want to develop the ecommerce website for Chinese company, I have to add the Chinese region at the backend.
![Uploading 1.jpg…]()

**Comment by cs221313** [comment]
Hi, Anton,

Only US states was in the region table. If I want to develop the ecommerce website for Chinese company, I have to add the Chinese region at the backend.
![image](https://cloud.githubusercontent.com/assets/8097168/15167623/fb7b1036-175c-11e6-8d9e-52bd0181be3a.jpeg)
After user click the new region, we can add new region in the following page:

![image](https://cloud.githubusercontent.com/assets/8097168/15167650/32ac9bf6-175d-11e6-90cc-cd128bfdc8c8.jpeg)

 I developed that feature. but I found when I call save function in \Magento\Directory\Model\Region. It only save the record in table region. I have wrote the plugin function as following:

di.xml

<type name="Magento\Directory\Model\ResourceModel\Region">
-        <plugin name="magento_directory_model_resource_model_region"
-                type="AiMai\ChinaRegion\Model\ResourceModel\Region"
-                sortOrder="10"
-                disabled="false"/>
  Add a comment to this line
-    </type>

AiMai/ChinaRegion/Model/ResourceModel/Region.php

<?php
/**
- Created by PhpStorm.
- User: cs221313
- Date: 3/29/16
- Time: 3:41 PM
  */

namespace AiMai\ChinaRegion\Model\ResourceModel;

class Region
{
    /**
     \* Save region name in region name table
     \* @param $subject
     \* @param $procede
     \* @param $region
     */
    public function aroundSave($subject, $procede, $region)
    {
        $result = $procede($region);
        $regionNameTable = $subject->getTable('directory_country_region_name');
        $bind = $subject->_prepareDataForTable($region, $regionNameTable);
        $this->getConnection()->insert($regionNameTable, $bind);
    }
}

The problem solved.

Thanks
- David

**Comment by hshar7** [comment]
@cs221313 could you please reupload the photo. It seems like it didn't finish uploading.

**Comment by antboiko** [comment]
@cs221313

Hello David, could you please close the issue if the problem was solved?

Also, would you be interested in making pull request for this feature?

Thanks,
Anton.

**Comment by cs221313** [comment]
Anton,

Now I solved this problem by plugin in a extension to avoid to change any code in Magento repository code. Do you mean I need to solve it in Magento repository code?

I never made a pull request. I think I need to read the code contribution part first.

Thanks

cs221313

**Comment by antboiko** [comment]
@cs221313 

Hello David. I only asked you if you're interested to make a PR for your feature for adding new region/city/district.

Could you please close the issue if your problem was solved?

Thanks,
Anton.

**Comment by cs221313** [comment]
Hi, Anton,

This feature is not 100% complete, I get problem in new shipping address part. When I select city. The option in city input will have the same text automatically. 
![Uploading image.png…]()

I implemented by following js code:

define([
    'underscore',
    'uiRegistry',
    'Magento_Ui/js/form/element/select'
], function (_, registry, Select) {
    'use strict';

```
return Select.extend({
    defaults: {
        /*imports: {
            update: '${ $.parentName }.city_id:value'
        }*/
    },

    /**
     * @param {String} value
     */
    update: function (value) {
        var city = registry.get(this.parentName + '.' + 'city_id'),
            options = city.indexedOptions,
            option;

        if (!value) {
            return;
        }

        option = options[value];

        if (!option['is_district_required']) {
            this.error(false);
            this.validation = _.omit(this.validation, 'required-entry');
        } else {
            this.validation['required-entry'] = true;
        }

        this.required(!!option['is_district_required']);

        var cityInput = registry.get(this.parentName + '.' + 'city')
        cityInput.value(option.label);
    }
});
```

});

above js file is define in checkout_index_index.xml as following:

<item name="shipping-address-fieldset" xsi:type="array">
    <item name="children" xsi:type="array">
        
        <item name="city_id" xsi:type="array">
            <item name="component" xsi:type="string">AiMai_ChinaRegion/js/form/element/regionSelect</item>
            <item name="filterBy" xsi:type="array">
                <item name="target" xsi:type="string"><![CDATA[${ $.provider }:${ $.parentScope }.region_id]]></item>
                <item name="field" xsi:type="string">region_id</item>
            </item>
        </item>
        <item name="district_id" xsi:type="array">
            <item name="component" xsi:type="string">AiMai_ChinaRegion/js/form/element/citySelect</item>
            <item name="filterBy" xsi:type="array">
                <item name="target" xsi:type="string"><![CDATA[${ $.provider }:${ $.parentScope }.city_id]]></item>
                <item name="field" xsi:type="string">city_id</item>
            </item>
        </item>
    </item>
</item>

But it doesn't work for district input. Also, how to set city, district input as display:none?

I will commit my code after the whole feature works.

Thanks

cs221313

**Comment by antboiko** [comment]
@cs221313 

Hi David, I'm closing this issue. Feel free to reopen it if needed.

Best,
Anton.
