### ISSUE TITLE
2.4.4-p10-Set indexers invalid during next immediate deployment after the key rotation 

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#39206]
### Steps to reproduce

1. Apply Patch 2.4.4-P10
2. Run Key Rotation command
3. Try to deploy again
4. Indexers will set as invalid and if the store has more than a million customer then setup:upgrade will take a lot of time

### Expected result

Setup Upgrade should complete it in few mins if there are no schema changes

### Actual result

Setup:upgrade takes more than 30 min and increase based on the number of customers

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by senthilengg** [comment]
@engcom-Hotel Thank you for working on this issue. It was taking 30-40+ mins for a 6 million customer DB. Fundamentally speaking there is no point in setting indexer invalid for this case.

More than reproducing this issue what i would suggest as part of the Key Rotation command, it should reupdate hash of indexer so the experience will be seamless given that we know no modification to the indexer schema.

Thank you

**Comment by engcom-Hotel** [comment]
Hello @senthilengg,

Thanks for the reply!

We have investigated this issue further. We ran `bin/magento indexer:status`, which does not show any index to reindex:

![image](https://github.com/user-attachments/assets/5b911169-2717-46ee-a233-24135d51e245)

After running `bin/magento encryption:key:change`, we get the same index status:
![image](https://github.com/user-attachments/assets/c8348e8d-edb6-4a8d-884c-711885fb03b0)

After that, we ran `time bin/magento setup:upgrade`, which took almost 18 mins to complete:
![image](https://github.com/user-attachments/assets/49989dbe-1cc7-498c-9aa4-83faa285ffe0)

But as the issue description, the `bin/magento encryption:key:change` command does not invalid the index status.

**Comment by engcom-Hotel** [comment]
Hello @senthilengg,

Thanks for the updates!

I can see several updates on this file in the latest development branch i.e. 2.4-develop:
https://github.com/magento/magento2/blob/6acfd6aa744c905f7694f2cddd5b0add5bf202b7/app/code/Magento/Indexer/Setup/Recurring.php#L1

And as per the process, we need to reproduce the issue in the latest development branch. So we request you to please try to reproduce the issue in the latest development branch and let us know if the issue is reproducible for you or not. 

And also we suggest you to please upgrade with the latest stable version.

Thanks

**Comment by senthilengg** [comment]
@engcom-Hotel Are you saying you are not able to reproduce with the above step after you update the encrypt key ?

**Comment by engcom-Hotel** [comment]
Yes @senthilengg, we are not able to reproduce the issue by following the steps mentioned in the main description. Please refer to this https://github.com/magento/magento2/issues/39206#issuecomment-2446558963.

Please try to reproduce the issue in the latest stable version or the latest development branch. Actually, there were many changes that happened after the 2.4.4-P10 release in the said file.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @senthilengg,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks

**Comment by senthilengg** [comment]
@engcom-Hotel  I am able to reproduce the same issue in 2.4.7-p1. 

1. Change Encryption Key from Admin
2. Remove the old encryption key from app/etc/env.php and Save
3. Check the indexer_state,  note down the updated at for all the rows
4. Run setup upgrade. You can found out that indexer status was updated and hash values are changed
5. In case of hash change customer_flat_grid data will be refreshed

Here is the indexer status from my local before and after 

<img width="819" alt="Screenshot 2025-01-10 at 11 19 54 AM" src="https://github.com/user-attachments/assets/001a30fe-bfe5-4a29-b907-a976e20a4323" />
