### ISSUE TITLE
Saving with "Use Default Value" in a store view results in null value. 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#39210]
### Preconditions and environment

- 2.4.6-p5

### Steps to reproduce

I can't find exact steps to troubleshoot or replicate this, it seems that it's happening randomly for random products. 

Basically I noticed it when I tried to save a product in a different store view other than the default, and noticed that the product name disappeared from the input field. 

I then tried to resave it with any non-empty value, and it was saving fine. 

Finally I tried to make it use the value from the default store view and unfortunately it doesn't do this. It just sets the field to null.

In the database the value for the field is null 

```
+--------+------------+--------+---------+-------------------------------+
|value_id|attribute_id|store_id|entity_id|value                          |
+--------+------------+--------+---------+-------------------------------+
|11559639|60          |0       |169442   |Wilson Team 6-Pack Tennis Bag  |
|16257373|60          |4       |169442   |null                           |
|13777274|60          |5       |169442   |Τσάντα Τένις Wilson Team 6-Pack|
|15886604|60          |11      |169442   |Τσάντα Τένις Wilson Team 6-Pack|
|15886629|60          |12      |169442   |Wilson Team 6-Pack Tennis Bag  |
|15886649|60          |13      |169442   |Wilson Team 6-Pack Tennis Bag  |
+--------+------------+--------+---------+-------------------------------+
```

https://github.com/user-attachments/assets/a2c62053-7287-4a25-b526-dae412ba5453

So basically it gets stored as null instead of being deleted. 

It should get stored as empty string '' if I wanted to delete it, but not as null. 

When it's stored as null, it's not using the default store view value, instead it's using the null value throwing errors in various areas like the breadcrumbs 

Moreover, if I delete the value in the database table, it will show correctly that it's using the default store value but on save I get the same issue again. 

I'm really buffled as to why this is happening and any assistance you can provide in order to find ways to replicate or patch it, I would greatly appreciate it. 

### Expected result

1. The fields are not getting deleted on their own unless I specifically delete the string in them
2. The "Use default value" checkbox restores the value to the default value

### Actual result

The field is blank. Even a field like the name which is "required" also gets saved as null. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @ioweb-gr ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and issue is not reproducible . Kindly refer the screenshots.

**Steps to Reproduce :**

1. Create multiple store views.
2. Create a simple product.
3. Switch the store view.
4. Unselect the default value checkbox for name.
5. Provide a different product name and save the product for respective store view.
6. Now select the default value checkbox and save the product.
7. Observe product name is not blank/null.

https://github.com/user-attachments/assets/861b1719-74a4-40ee-a22d-fb0158c4d7fc

Please let us know if any other steps are needed to be performed.

Thanks.
