### ISSUE TITLE
Editing Product Error

### ISSUE THREAD

**Issue by juliawoeste** [magento/magento2#39244]
### Preconditions and environment

- Magento version 2.4.6
- Using Brave 
![product error](https://github.com/user-attachments/assets/4d8cb413-83fc-41af-9d1b-02c5dbcd813c)

### Steps to reproduce

Navigate to home page and go to products page. Click on edit and I get "There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: bf8d45fa01bf431421a1b30707edb222d86ee117918654f61063a19009424cb2". 

### Expected result

I want to be able to edit the information about the product

### Actual result

![product error](https://github.com/user-attachments/assets/e4db37df-c4dd-4228-92b9-6bde15bfa2e9)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @juliawoeste,

Thanks for your reporting and collaboration.

Please refer this https://stackoverflow.com/questions/34629697/how-to-turn-on-error-messages-in-magento-2/34740378#34740378 it may resolves your issue.

Thanks.

**Comment by Detzler** [comment]
@juliawoeste you'll find the reason in:

var/report/bf8d45fa01bf431421a1b30707edb222d86ee117918654f61063a19009424cb2

**Comment by engcom-Bravo** [comment]
@Detzler Thanks for your Contribution!!.

Hi @juliawoeste,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
