### ISSUE TITLE
Edit of dropdown attribute with large option count changes layered nav values, breaks attribute edit/save

### ISSUE THREAD

**Issue by dnadle** [magento/magento2#3924]
I added a dropdown attribute with a little over 2,000 options and selected yes values for "Use in Layered Navigation" and "Use in Search Results Layered Navigation." Later, I edited the "Position" value and when I saved the attribute the layered navigation values were set to "No." If I edit the attribute again and attempt to change the layered navigation values back (or change any other values) the save appears to succeed but the values are not updated. I can't find any messages in the logs to explain why the save may have failed.
## Steps to reproduce
1. Add a dropdown attribute with "Use in Layered Navigation" = Filterable (With Results) and "Use in Search Results Layered Navigation" = Yes.
2. Add more than 2,000 options using the REST API.
3. Change the value of the "Position" value and save the attribute.
## Expected result

The attribute saves successfully and no values are unexpectedly changed.
## Actual result

First save:
1. "Use in Layered Navigation" and "Use in Search Results Layered Navigation" are changed to No.
2. Affirmative screen message: "You saved the product attribute."
3. No error messages in the logs.
Later saves:
1. Any changed attribute values revert to what they were before the save.
2. Affirmative screen message: "You saved the product attribute."
3. No error messages in the logs.
## Update:

I used the REST API to remove all options from the affected attribute, and this restored the ability to save edits to the attribute layered nav and position values. The bug seems to be related to having a large number of options assigned to the attribute.

**Comment by choukalos** [comment]
Created MAGETWO-51328 to track internally.

**Comment by piotrekkaminski** [comment]
It's a limit of php configuration, because config max_input_vars by default has value 1000, in this case value of max_input_vars should be 10000. After increasing to 100000 it  seems to  work fine with 2100 options.

**Comment by aasim110** [comment]
I'm getting same issue and have changed max_input_vars 100000 but still not working for me!!
Any ideas ?

_NOTE : I'm checking in magento 2.2.3 version._
