### ISSUE TITLE
CSP Module Blocks Adyen 3DS Requests in Production Environment

### ISSUE THREAD

**Issue by fnievesf** [magento/magento2#39259]
### Preconditions and environment

- Magento version: 2.4.6-p8
- Additional info:
Adyen Payment Integration with 3DS enabled
CSP (Content Security Policy) module enabled in the production environment

![imagen](https://github.com/user-attachments/assets/dec6f5fb-d315-43e8-a005-d1d4b876e202)

### Steps to reproduce

1. Navigate to checkout.
2. Try to complete the payment with a credit card that requires 3DS verification.

### Expected result

Adyen's 3DS verification URLs should load successfully, and the payment process should complete without being blocked by the CSP.

### Actual result

The payment is refused, and multiple Adyen related requests are blocked by the CSP module due to these URLs not being whitelisted.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by naseemqota** [comment]
@fnievesf  I'm upgrading magento 2.4.6 to 2.4.6-p8 i can see the issue you have reported is that something we should avoid it upgrade to **-P8** ? or we should do that

**Comment by fnievesf** [comment]
> @fnievesf I'm upgrading magento 2.4.6 to 2.4.6-p8 i can see the issue you have reported is that something we should avoid it upgrade to **-P8** ? or we should do that

It depends, in our case we had to upgrate to -p8 because of security issues, but it's happening from earlier versions. If you need to upgrade, there is a workaround which is to disable the CSP module or use the report mode

**Comment by engcom-Bravo** [comment]
Hi @fnievesf,

Thanks for your reporting and collaboration.

Adyen Payment Integration that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
