### ISSUE TITLE
ACL not defined for Magento_Backend::web

### ISSUE THREAD

**Issue by bpoiss** [magento/magento2#3925]
The resource defined in `magento/module-backend/etc/adminhtml/system.xml:440` (`Magento_Backend::web`) has no ACL. On the other hand there is an ACL defined for the resource `Magento_Config::web` that doesn't exist in `magento/module-config/etc/acl.xml:22`.  

If you give some user role permissions for "Web Section" in the backend, the Web Section will not be visible for this user group.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54158

**Comment by vherasymenko** [comment]
Steps:
1. Install Magento latest develop version
2. Go to Admin side
3. Click "System > User Roles"
4. Click "Add new Role" enter Role name
5. In left side choose Role Resources and check "Dashboard" and "Web Section"
6. Save Role
7. Click "System > All Users"
8. Click "Add new User"
9. Enter data in required fields
10. In left side click "User Role" and choose early created role.
11. Click "Save"
12. Sign out and Log in using credentials of new user
13. Click "Soters > Configuration" 

AR: Displayer error
ER: Web Section should be visible for this user

**Comment by jspoe** [comment]
Created pull request for fixing this issue.
Also changed some other similar ACL problems along the way.

[https://github.com/magento/magento2/pull/9628](https://github.com/magento/magento2/pull/9628)

**Comment by AVoskoboinikov** [comment]
Hi guys! 
Fix was delivered with this commit 686df6b33aeca5c2623215c95e119bf13558abd7

**Comment by korostii** [comment]
@AzVo, delivered to `develop` only, it seems, right?
I think it's a bit misleading and way too early to close the issue if it is still reproducible on latest stable (2.1.7 at the moment) release. Don't you agree?
