### ISSUE TITLE
issue when selecting images from gallery

### ISSUE THREAD

**Issue by mohanwbsofttech** [magento/magento2#39264]
### Summary

when selecting image in admin from gallery the window says A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### Examples

When we go in content configuration and select any them and add logo and go into select from gallery option it gives A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later. error. The system log say main.ERROR: "/pub/media/htaccess" is not a valid file path [] []

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mohanwbsofttech,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/f3c48ccb-1bec-48e3-9891-a2fbfeb32b51



We are able to select and upload the images successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still repoducible.

Thanks.

**Comment by mohanwbsofttech** [comment]
I think the issue is related to my old media library and new media library in updated version. How I can use my old media with updated version

**Comment by engcom-Bravo** [comment]
Hi @mohanwbsofttech,

Thanks for your update.

Kindly refer this devdocs https://docs.magento.com/user-guide/v2.3/cms/media-storage.html and https://developer.adobe.com/commerce/php/module-reference/module-media-gallery-synchronization/ regarding Media Gallery.

Thanks.

**Comment by mohanwbsofttech** [comment]
also I am getting 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-popup.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/js-translation.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-popup.html. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/js-translation.json. (Reason: CORS request did not succeed). Status code: (null).

Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    <anonymous> https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Translation/js/mage-translation-dictionary.js:11
    execCb https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1720
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:893
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1153
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1205
    each https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:62
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1204
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:950
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    init https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:798
    callPlugin https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:994
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1205
    each https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:62
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1204
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:950
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    init https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:798
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1028
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    loadContent https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/mage/requirejs/text.js:155
    onreadystatechange https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/mage/requirejs/text.js:122
    getContent https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/mage/requirejs/text.js:105
    loadContent https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/mage/requirejs/text.js:153
    callPlugin https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1109
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    on https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:525
    callPlugin https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:967
    fetch https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:834
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:866
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    callPlugin https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1012
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1205
    each https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:62
    emit https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1204
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:950
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    init https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:798
    callGetModule https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1219
    completeLoad https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1609
    onScriptLoad https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1742
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1974
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1709
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:844
    fetch https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:834
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:866
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1576
    callPlugin https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1112
    fetch https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:834
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:866
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1576
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1175
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    each https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:62
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1127
    init https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:798
    callGetModule https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1219
    completeLoad https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1609
    onScriptLoad https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1742
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1974
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1709
    load https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:844
    fetch https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:834
    check https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:866
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1191
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1576
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1175
    bind https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:138
    each https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:62
    enable https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1127
    init https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:798
    localRequire https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1478
    setTimeout handler*req.nextTick< https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1842
    localRequire https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1467
    configure https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1404
    requirejs https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1821
    config https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs/require.js:1832
    <anonymous> https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs-config.js:708
    <anonymous> https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs-config.js:709
    <anonymous> https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/requirejs-config.js:888
[mage-translation-dictionary.js:11:17](https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Translation/js/mage-translation-dictionary.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-slide.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-custom.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-slide.html. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.3gmobilecctv.com/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/modal/modal-custom.html. (Reason: CORS request did not succeed). Status code: (null).

in browser console when editing any static block in admin. I tried many things like 'x-frame-options' => 'CROSS-ORIGIN', and also in htaccess but nothing works.

**Comment by engcom-Bravo** [comment]
HI @mohanwbsofttech,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and there were no console errors while editing static block.Could you please check if any third party modules causing this issue.

Thanks.

**Comment by mohanwbsofttech** [comment]
I got this in firefox browser. When I edit the block and saving it it saves once. but when the page comes after saves then all these errors comes.

**Comment by engcom-Bravo** [comment]
Hi @mohanwbsofttech,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance with firefox and we are not able to reproduce the issue.Please try to reproduce the issue in Latest 2.4-develop instance and could you please check if any third party modules causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @mohanwbsofttech,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
