### ISSUE TITLE
Call to translation method is missing

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#39269]
https://github.com/magento/magento2/blob/f130be4995a2767077a102ae1a364be6a9cc3957/app/code/Magento/OfflinePayments/view/frontend/templates/info/checkmo.phtml#L12

The title is not translating. The call to `__()` is missing.

**Comment by andrewbess** [comment]
Hello @Eddcapone 
Thank you for your contribution.
I think it is unnecessary to use the Magento translation feature here.
The payment method title is configuration-dependent.
Please check the provided screenshots.
![payment-title-configuration](https://github.com/user-attachments/assets/68a6531a-888f-4229-b00f-603d51226e13)
![checkmo-payment-titles-for-diff-store-views](https://github.com/user-attachments/assets/d647c7e5-8d89-41d8-8bee-630b48de0902)
If you have some stores (websites or store views), you can change the configuration to have different (translated) titles.
I will close this issue as not reproducible.

**Comment by Eddcapone** [comment]
You are right.
