### ISSUE TITLE
Sales Rule indexer is not reindexed when duplicate cart price rule

### ISSUE THREAD

**Issue by m08110071** [magento/magento2#39260]
### Preconditions and environment

- Magento 2.4.7-p2

### Steps to reproduce

- Change Sales Rule indexer mode to Update on Save
- Create new cart price rule item without condition
- Add any product to cart => cart price rule is applied
- Duplicate above cart price rule item
- Refresh cart page

### Expected result

The duplicated cart price rule is applied

### Actual result

The duplicated cart price rule is not applied

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance but we need more information regarding Duplicate the cart price.could you please update to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
