### ISSUE TITLE
Magento\Framework\HTTP\Adapter\Curl does not format headers correctly 

### ISSUE THREAD

**Issue by RobKega** [magento/magento2#39272]
### Preconditions and environment

- 2.4.7-p3

### Steps to reproduce

- Create a Magento\Framework\HTTP\LaminasClient 
- set headers in key => value pairs, like ['Authorization' => 'Bearer SomeToken'] 
- set option CURLOPT_VERBOSE => true (to see the actual headers being sent) 
- do a request 
- see that the Authorization (and other custom headers)  is missing 

### Expected result

Custom headers are added to the request

### Actual result

Custom headers are not present in the request

### Additional information

the Laminas Curl adapter formats the key => value headers to an array of string headers for curl, the Magento\Framework\HTTP\Adapter\Curl does not do this and that is why it fails 

see : laminas-http/src/Client/Adapter/Curl.php  line 488

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by RobKega** [comment]
@engcom-November 

![image](https://github.com/user-attachments/assets/84cee9c3-499f-450f-b907-03a38f16449e)

This is the result on 2.4.7-p3 

`*   Trying 104.248.184.153:443...
* Connected to magento.requestcatcher.com (104.248.184.153) port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=requestcatcher.com
*  start date: Oct 11 19:38:38 2024 GMT
*  expire date: Jan  9 19:38:37 2025 GMT
*  subjectAltName: host "magento.requestcatcher.com" matched cert's "*.requestcatcher.com"
*  issuer: C=US; O=Let's Encrypt; CN=R11
*  SSL certificate verify ok.
> GET /test HTTP/1.1
Host: magento.requestcatcher.com
User-Agent: Laminas\Http\Client
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 21 Oct 2024 09:14:05 GMT
< Content-Length: 14
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host magento.requestcatcher.com left intact
`

**Comment by engcom-November** [comment]
@RobKega,

Thank you for the quick response!

The issue has been fixed in latest 2.4-develop branch, [here](https://github.com/magento/magento2/pull/37613) is the pr.
This will be shipped in upcoming verion.
