### ISSUE TITLE
REST API should be able to return codes outside of 400-599 range, such as 304

### ISSUE THREAD

**Issue by brendanmckeown** [magento/magento2#3927]
This code prevents me from returning any HTTP status codes outside of the 400-599 range.  I specifically would like to return a 304 NOT MODIFIED status.

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Webapi/Exception.php#L76

304 is a common return code used in RESTful API's, and should be allowed.

**Comment by vkublytskyi** [comment]
Exceptions should not be used to implement logic but only for error handling. According to HTTP specification only 4*\* and 5*\* status codes should be used for errors.

**Comment by brendanmckeown** [comment]
@vkublytskyi is it possible to return a 304 code?

**Comment by vkublytskyi** [comment]
@brendanmckeown sorry for delay with response.

You may implement after plugin on Magento\Webapi\Controller\Rest::dispatch to modify response object and set status code or caching headers appropriate for your project.

Around plugin for Magento\Webapi\Controller\Rest::dispatch may be used if you need **conditionally** replace default logic for handling requests to REST API and fill response object. If you always need perform default logic implemented in Magento\Webapi\Controller\Rest::dispatch but want to perform some actions before and after request processing then pair of before/after plugins should be used.

**Comment by brendanmckeown** [comment]
Also confirmed here: http://magento.stackexchange.com/questions/108871/return-a-304-http-response-from-within-a-rest-api-method/108891#108891
