### ISSUE TITLE
New Media-Gallery gives 404 error: Page not found.

### ISSUE THREAD

**Issue by Top-CMS** [magento/magento2#39279]
### Preconditions and environment

- Magento version - All with new Media-Gallery
- Using NGINX

### Steps to reproduce

When we go on every Magento 2 to in the Magento2 backend Content -> Media Gallery we always get a 404 error.
The system log is error: [2024-08-16T12:03:34.788407+00:00] main.ERROR: The path is not allowed: beheer/media_gallery/media/index/key/04258acb4adb1f338a433de254cfd39885c349485a90d7e9e65b3d7a42508fdc/ [] []

### Expected result

To see the media-gallery

### Actual result

 404 error: Page not found

### Additional information

It is an server issue or nginx config. Because on some other servers the same install works.,

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Top-CMS,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1333" alt="Screenshot 2024-10-18 at 14 00 17" src="https://github.com/user-attachments/assets/dd837b95-b280-4be0-9ad6-6ed13df06728">


We are able to see the Media Gallery and able to upload the images successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by Top-CMS** [comment]
As told, I don't think it is a bug, "it is an server issue or nginx config. Because on some other servers the same install works".
![image](https://github.com/user-attachments/assets/7d46c431-04e6-4a4b-a4af-2f678eea5ff1)

When use [Cloudpanel ](https://www.cloudpanel.io/docs/v2/php/applications/magento/##)I have this problem. Everything works fine, only the link to Media Gallery gives 404.
When open the media Gallery from out products, categories, blocks or pages it works fine.

I think the problem is with the url, what not will accepted by NGINX
I the url is the 'backend' -> 'frontname' missing.
Like
Normalurls in Magento-backend:

**Comment by Top-CMS** [comment]
This is how a basic vhost for NGINX is in Cloudpanel:

`server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name tes-domain.com;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
  }

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  {{settings}}

  location ~/media/ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    try_files $uri $uri/ /get.php$is_args$args;
  }

  location /static/ {
    add_header Access-Control-Allow-Origin "*";
    location ~ ^/static/version {
      rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
    }
    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2|html|json)$ {
      add_header Access-Control-Allow-Origin "*";
      expires max;
      access_log off;
      if (!-f $request_filename) {
          rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
          rewrite ^/static/(.*)$ /static.php?resource=$1 last;
      }
    }
  }

  try_files $uri $uri/ /index.php?$args;
  index index.php index.html;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS $fastcgi_https;
    fastcgi_pass 127.0.0.1:{{php_fpm_port}};
    fastcgi_param PHP_VALUE "{{php_settings}}";
  }

  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|webp|zip|swf)$ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    access_log off;
  }

  if (-f $request_filename) {
    break;
  }
}`

**Comment by Top-CMS** [comment]
Problem solved.
The default vhost from CloudPanel is with
  location ~/media/ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    try_files $uri $uri/ /get.php$is_args$args;
  }

This tilde ~ must removed, it is used for regfex-matches, than can conflict.

  location /media/ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    try_files $uri $uri/ /get.php$is_args$args;
  }
