### ISSUE TITLE
The consumer isn't authorized to access %resources. Magento 2.4.7 on staging environment with auth1.0

### ISSUE THREAD

**Issue by mohitgohel80** [magento/magento2#39289]
### Preconditions and environment

- Magento version is 2.4.7

### Steps to reproduce

URL: https://dev2.example.com/rest/V1/products/apitest
This in headers: Authorization: "Bearer <admin-token-here>"

### Expected result

Using the Token we are trying to update or delete the product, But we are getting consumer isn't authorized message. 

We tried multiple ways but could not succeed. 

### Actual result

{"message":"The consumer isn't authorized to access %resources.","parameters":{"resources":"Magento_Catalog::products"},"trace":"#0  public_html/vendor/magento/module-webapi/Controller/Rest/RequestValidator.php(92): Magento\Webapi\Controller\Rest\RequestValidator->checkPermissions(Object(Magento\Webapi\Controller\Rest\Router\Route\Interceptor))\n#1  public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\RequestValidator->validate()\n#2  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\RequestValidator\Interceptor->___callParent('validate', Array)\n#3  public_html/vendor/magento/module-re-captcha-webapi-rest/Plugin/RestValidationPlugin.php(83): Magento\Webapi\Controller\Rest\RequestValidator\Interceptor->Magento\Framework\Interception\{closure}()\n#4  public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ReCaptchaWebapiRest\Plugin\RestValidationPlugin->aroundValidate(Object(Magento\Webapi\Controller\Rest\RequestValidator\Interceptor), Object(Closure))\n#5  public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\RequestValidator\Interceptor->Magento\Framework\Interception\{closure}()\n#6  public_html/generated/code/Magento/Webapi/Controller/Rest/RequestValidator/Interceptor.php(23): Magento\Webapi\Controller\Rest\RequestValidator\Interceptor->___callPlugins('validate', Array, NULL)\n#7  public_html/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(108): Magento\Webapi\Controller\Rest\RequestValidator\Interceptor->validate()\n#8  public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()\n#9  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callParent('resolve', Array)\n#10  public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->Magento\Framework\Interception\{closure}()\n#11  public_html/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callPlugins('resolve', Array, Array)\n#12  public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->resolve()\n#13  public_html/vendor/magento/module-webapi/Controller/Rest.php(201): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))\n#14  public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))\n#15  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)\n#16  public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))\n#17  public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)\n#18  public_html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#19  public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()\n#20  public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)\n#21  public_html/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()\n#22  public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))\n#23  public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()\n#24  public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)\n#25  public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()\n#26  public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))\n#27 {main}"}

### Additional information

We have already setting this refer below snapshot for same!

![image](https://github.com/user-attachments/assets/1c15b913-d5f1-4acf-9bf3-bba616863bec)

--------------

![image](https://github.com/user-attachments/assets/ef17548f-6508-42a6-804b-e006ff6fde1a)

--------------

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mohitgohel80,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="843" alt="Screenshot 2024-11-07 at 11 11 50" src="https://github.com/user-attachments/assets/efb7aa66-b403-49f3-8936-d92cc6109fa2">



We are able to update and delete the products successfully.Could you please check the user having restricted access and also check authorization token.

Thanks.

**Comment by mohitgohel80** [comment]
Hello @engcom-Bravo

We are still facing the same issue as previously discussed. The application works correctly in our local environment but is not functioning as expected in the staging and development environments. We are using cPanel and Apache servers, and we have attempted adjustments in the .htaccess file, including enabling mod_security and cross-security configurations. 

![image](https://github.com/user-attachments/assets/beb233a6-2e02-4048-9a09-9f98cfc4f645)

Could you please suggest further server-side checks or configurations that might help resolve this?

**Comment by engcom-Bravo** [comment]
Hi @mohitgohel80,

Thanks for your update.

Could you please also check if any third party modules can causing the issue and also confirm you are using postman in browser or you have installed app.


<img width="884" alt="Screenshot 2024-11-11 at 10 05 03" src="https://github.com/user-attachments/assets/42739ae8-06dd-46ed-b2d8-adfac4edc566">



Thanks.

**Comment by engcom-Bravo** [comment]
Hi @mohitgohel80,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
