### ISSUE TITLE
how can we add configurable product and bundle product to cart using past body

### ISSUE THREAD

**Issue by akashrajguru** [magento/magento2#3928]
what will the post body to add configurable product and bundle product into cart

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by akashrajguru** [comment]
thank you Damian :)
