### ISSUE TITLE
Invoice cancel  form backend 404 error

### ISSUE THREAD

**Issue by Syamsg** [magento/magento2#39299]
### Preconditions and environment

- Magento version 2.4.7
- Try to cancel a invoice from backend .

### Steps to reproduce

Place an order and create an invoice without capturing payment. After creating the invoice, view the invoice and then attempt to cancel it from the backend.

![image](https://github.com/user-attachments/assets/ec1a8e3b-da0b-45b3-a524-21d6a0b26112)

### Expected result

Successfully invoice get cancelled

### Actual result

404 error
![image](https://github.com/user-attachments/assets/2b9354f9-f928-4f0b-9f01-06d437d5a219)

### Additional information

"This error occurred due to commit [3e637056d1031185c7c8989f7a24302cecb5b27b](https://github.com/magento/magento2/commit/3e637056d1031185c7c8989f7a24302cecb5b27b), where Magento\Framework\App\Action\HttpPostActionInterface was implemented for the controller Magento\Sales\Controller\Adminhtml\Order\Invoice\Cancel instead of Magento\Framework\App\Action\HttpGetActionInterface."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Syamsg** [comment]
Invite me to the slack work space iam not able to join by myself

**Comment by engcom-Bravo** [comment]
Hi @Syamsg,

Thanks for your reporting and collaboration.

Similar issue has been reported here https://github.com/magento/magento2/issues/39298

Hence we are closing this duplicate.

Thanks
