### ISSUE TITLE
Rest API - Retrieve Attribute Set - Fatal Error: 'Class '' not found' 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3930]
## Steps to reproduce
1. Install Magento 2.0.2 with sample data.
2. Attempt to retrieve related attributes based on given attribute set ID either via url or programmatically.
- http://domain.com/magento/rest/V1/products/attribute-sets/11/attributes
- code

`$endpoint = $server_service.'/V1/products/attribute-sets/11/attributes';`
`$ch = curl_init();                          # create new cURL resource`
`curl_setopt($ch, CURLOPT_URL, $endpoint);`
`curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");` 
`curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);`
`curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);`
`curl_setopt($ch, CURLINFO_HEADER_OUT, true);`
`$productAttributes = curl_exec($ch);`
## Expected Result

json string of attributes
## Actual result

s:140:"Fatal Error: 'Class '' not found' in '/var/www/domain/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php' on line 97";

`{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/262685811623"}]}}Array
(
    [messages] => Array
        (
            [error] => Array
                (
                    [0] => Array
                        (
                            [code] => 500
                            [message] => Server internal error. See details in report api/262685811623
                        )
                )
        )
)`

**Comment by duhon** [comment]
Can't reproduce on current version. Please try on latest version.
