### ISSUE TITLE
Want multi table rates 

### ISSUE THREAD

**Issue by vanshaldotcom** [magento/magento2#39306]
Any Body help me to make multi table rate for Magento 2.4.3

**Comment by engcom-Bravo** [comment]
Hi @vanshaldotcom,

Thanks for the report and collaboration!

To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Bravo** [comment]
Hi @vanshaldotcom,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
