### ISSUE TITLE
Wishlist total showing a maximum 3 item count when I add more than 3 items to my wishlist - magento 2.4.x

### ISSUE THREAD

**Issue by rajeshsetblue** [magento/magento2#39301]
### Preconditions and environment

- Magento 2.4.7-p2

### Steps to reproduce

Log into customer account on frontend
Go to product A and add to wishlist
Go to product B and add to wishlist
Go to product C and add to wishlist
Go to product D and add to wishlist
Go to Wishlist and check items count 

### Expected result

4 product should show in wishlist count
Wishlist count in grid toolbar should say "4 Item(s)"

### Actual result

3 product should show in wishlist count
Wishlist count in grid toolbar should say
![Captursde](https://github.com/user-attachments/assets/712d2961-6259-4658-9455-77fa7347389d)
 "4 Item(s)"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @rajeshsetblue,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1422" alt="Screenshot 2024-10-28 at 09 34 13" src="https://github.com/user-attachments/assets/fc9e1e85-c6f4-4a64-944a-64556394379b">


4 Products are showing in the Wishlist grid toolbar.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @rajeshsetblue,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
