### ISSUE TITLE
Customer Login Page is incorrectly cached with private data if Magento Captcha isn't enabled

### ISSUE THREAD

**Issue by collymore** [magento/magento2#39318]
### Preconditions and environment

- Version 2.4.7

### Steps to reproduce

- Disable the module Magento_Captcha, there is no dependancy on this module and the Magento_Customer module, so the Customer Login page should work correctly.
- Visit the Customer Account login page "/customer/account/login" with Full page cache active

### Expected result

The page returns FPC MISS. 

The customer account form is using private data e.g The current Customer Email address is output in the forms login field" and this shouldn't be cached. 

### Actual result

The page response is returned with a Full page cache HIT.

If visiting the page after a cache clear and logged in, the email will be cached on the page for all subsequent requests.

### Additional information

The only reason that the Customer Account Login page is not cached by default is the Magento_Captcha module's layout customer_account_login.xml file.

This is adding a bock name="captcha" to the container name="form.additional.info".  
That block has cacheable="false" declared which then stops the login page from being cached. 

Without this module activate nothing else is making the page non-cacheable. 

Edit : This issue actually effects every Customer Account Form

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @collymore ,

Thanks for your reporting and collaboration.
We have tried to reproduce the issue in Latest 2.4-develop instance, but we can see there is dependency in disabling Magento_Captcha module. Kindly refer the screenshots.
![image](https://github.com/user-attachments/assets/0f5a0b23-5f73-4fc0-a597-a0433fad55e7)

Can you please provide more steps that will help in replicating the issue.

Thanks.

**Comment by collymore** [comment]
Hi, 
Yes it was disabled with -f to force the disabling. Or if the child container="form.additional.info" from without the forms xml layout is removed. 

I did a loom video.
https://www.loom.com/share/427a8fa2083b48c8a940482e7acead19?sid=e06655ae-d521-4bfb-9f6d-586657f88483

**Comment by engcom-Delta** [comment]
Hi @collymore ,

Thank you for sharing the detailed steps. As you mentioned Magento_Captcha module is disabled with -f but it is not recommended approach as Magento_Captcha module is depended on various main modules. 
![image](https://github.com/user-attachments/assets/e866a779-53f0-40b1-ae75-372880cbd871)

Can you please share more steps to disable Magento_Captcha module in production environment.

Thanks.

**Comment by collymore** [comment]
Hi, 
Ok then maybe this is not an issue if there is not a direct dependancy between Magento_Captcha and Magento_Customer, but it's enforced through so many other indirect dependancies. 
I raised this ticket as it was reported that a Merchant's site was having real customers emails showing on the login page for other customers. 
They must have either disabled Magento_Captcha or removed the child block position  container="form.additional.info". 
As that's what Magento_Captcha injects it's cacheable="false" block into the page with. 

Wouldn't it make sense for the customer forms to have cacheable="false" directly on them if they are always never meant to be cached?

**Comment by engcom-Hotel** [comment]
Hello @collymore,

Thank you for highlighting this. You’re correct that while there’s no direct dependency between `Magento_Captcha` and `Magento_Customer` modules, indirect dependencies can sometimes create unexpected behaviors, particularly when customizations or cache settings are involved.

The issue you described, where real customer emails are displayed on the login page for other users, typically occurs when the Magento_Captcha module’s cacheable="false" setting is removed or altered, especially by disabling the module or modifying the form.additional.info block. This can lead to unintended caching of sensitive information.

To ensure such sensitive forms are never cached, one solution could indeed be setting cacheable="false" directly on customer-related forms as a default. This approach might help prevent similar issues when Magento_Captcha is disabled or modified. However, as each module’s behavior is tightly managed within its own scope, setting cacheable="false" globally could have performance impacts, so it would require careful consideration.

I hope I can answer your query.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @collymore,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks
