### ISSUE TITLE
Translate Inline for Admin

### ISSUE THREAD

**Issue by jonsaf** [magento/magento2#3933]
## Steps to reproduce
1. Config, Advanced, Developer
2. Translate Inline
3. Enabled for Admin to Yes
4.  Click Saved
## Expected result
1. Can not then select Customers, Any customer Edit and have the fields available for editing.
2. Ultimately trying to change the name of VAT Number
## Actual result
1. Spins with no results that appear - see screen shot.
   <img width="1395" alt="screen shot 2016-03-30 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/13703880/14158828/463b7378-f687-11e5-8c4d-77744c3ba61a.png">

**Comment by mazhalai** [comment]
@jonsaf Thank you! we have created ticket MAGETWO-41995 to investigate and fix.

**Comment by cspruiell** [comment]
This has been fixed and delivered to the develop branch.
