### ISSUE TITLE
Customer Sign In

### ISSUE THREAD

**Issue by princessfrombabylon99** [magento/magento2#39334]
### Preconditions and environment

- Magento version  Release 2.4.8-beta1

### Steps to reproduce

1. Log into an account , the top bar shows like this on homepage
2. 
![image](https://github.com/user-attachments/assets/61ace5b6-6013-4cd9-bb5d-ddf37dc27453)

### Expected result

It should Ideally show like this
![image](https://github.com/user-attachments/assets/59c4843b-920a-427f-b004-2e6befd2cca7)

### Actual result

![image](https://github.com/user-attachments/assets/61ace5b6-6013-4cd9-bb5d-ddf37dc27453)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @princessfrombabylon99,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.kindly refer the screenshots.


<img width="1397" alt="Screenshot 2024-11-07 at 12 44 07" src="https://github.com/user-attachments/assets/ec8a4e73-8e7b-482c-978e-c152b8b92edb">




 The top bar is not working fine after sign in on homepage.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @princessfrombabylon99,

The Magento core engineering team is working on the issue and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information.

Thank you once again!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-13322 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-13322&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
