### ISSUE TITLE
Incorrect Token behaviour while the admin set/unset some settings

### ISSUE THREAD

**Issue by monteshot** [magento/magento2#39343]
### Preconditions and environment

- Magento version - any (with GraphQL solution)
- "Old" users

### Steps to reproduce

Precondition:
- Set the Cookie lifetime for a big number(a year - 31536000) - you must have the user session "from the past". I mean, with an old token like "Bearer r1oz2fi2fyqehs89wvbsimndpn16ocay"
- Disable Customer token lifetime
![image](https://github.com/user-attachments/assets/e8222cb7-ac52-42a8-a3a9-edc075362ff5)
- Go to any checkout solution which works on GraphQL - you get the error. 
Because in 
\Magento\Integration\Model\OpaqueToken\Reader::read settings handle incorrectly
![image](https://github.com/user-attachments/assets/f1d4a187-3f54-4fb1-8c15-bd35e70a37f9)
![image](https://github.com/user-attachments/assets/aee1930b-e318-4dc2-9fa8-e3f68e4d9255)

### Expected result

Error not raises. New tokens not reissued seamlessly

### Actual result

Error raised. The new token works as a new

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @monteshot ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance & 2.4.8-beta1 instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Set the Cookie lifetime for a big number(a year - 31536000) - you must have the user session "from the past". I mean, with an old token like "Bearer r1oz2fi2fyqehs89wvbsimndpn16ocay"
![image](https://github.com/user-attachments/assets/34aa4a2b-3b06-4f26-bd67-f846c8e01c7b)

2. Disable Customer token lifetime
![image](https://github.com/user-attachments/assets/fd9ec97a-9e22-4239-8cee-3e37e14560df)
3. Go to any checkout solution which works on GraphQL 
4. Observe error is not displaying
![image](https://github.com/user-attachments/assets/9c818ba6-dfed-4294-87cc-2db3b71c9fbb)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @monteshot ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
