### ISSUE TITLE
CSV Product Import with NO stock changes assigns Products to default source

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#39354]
### Preconditions and environment

- Magento 2.4.6-p8

CSV file:
```
sku,custom_attribute
AD-1,attribute_value_first
AD-2,attribute_value_second
```

### Provided

1. I am logged as an Administrator with permission to update Prodcts and Inventories
2. There are **two** inventory sources: `Default` and `Online Inventory`
3. The products listed in CSV file exist and are assigned to `Online Inventory`

### Steps

1. Navigate to `System` > `Data Transfer` > `Import`
2. Set `Entity Type` to `Products`, `Import Behavior` to `Add / Update`, select CSV file to import. (see `Preconditions`)
3. Perform Import

### Expected result

The Products Inventory Source assignment should not change (should still be assigned to `Online Inventory` only.

### Actual result

The Products get assigned to the `Default` Inventory Source.

### Additional information

The problem lies in `\Magento\CatalogImportExport\Model\Import\Product::_saveStockItem`, which - regardless the Import CSV contains any Inventory changes or not - updates the Inventory.

However, instead of getting the current Inventory settings, it calls `\Magento\CatalogImportExport\Model\Import\Product::getRowExistingStockItem`, which - under the hood - creates a new inventory entry 🤯 with default Website ID and its Stock: 

https://github.com/magento/magento2/blob/0b488dd1139e413cd5711241ae767030081805f6/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L3435-L3440

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance & 2.4.8-beta1 instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Create two sources Default and Online Inventory
2. Create AD-1 and AD-2 Product and assign them to online inventory source
3. Import the csv
[prod.csv](https://github.com/user-attachments/files/17733553/prod.csv)
4. After import navigate to catalog>products>AD-1 and AD-2 Products
5. Observe both products are assigned to online inventory and not assigned to default source.
![image](https://github.com/user-attachments/assets/6400d35f-31a4-46d9-bd40-fd76019b6261)
![image](https://github.com/user-attachments/assets/ab7736c3-58a7-4435-a3ba-fd813a1b2467)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by lbajsarowicz** [comment]
The problem no longer occurs in the latest (2.4.7) version of Magento.
I'll find out what exact Commit fixed the issue and let you know in the thread.
