### ISSUE TITLE
Setting default sort order to descending in categories prevents user from changing sorting direction 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#39350]
### Summary

After upgrading to 2.4.7 we lost the ability to change the default sort order of products in the catalog to descending

To reproduce 

1. Add a catalog_category_view.xml to change default sorting direction to descending 
2. The page loads the products in descending order. 
3. Try to change direction by clicking on the arrow
4. The direction stays the same instead of changing

https://github.com/user-attachments/assets/4eb77b0c-6bbb-4ee5-8ad1-7512fe4163b3

### Examples

Previously this snippet would correctly set the default direction in 2.4.6 but in 2.4.7 it prevents changing the direction

```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <!-- set sort direction to descending -->
        <referenceBlock name="product_list_toolbar">
            <action method="setDefaultDirection">
                <argument name="dir" xsi:type="string">desc</argument>
            </action>
        </referenceBlock>
    </body>
</page>

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
I wanted to add that even changing \Magento\Catalog\Helper\Product\ProductList::DEFAULT_SORT_DIRECTION to "desc" doesn't work for me. Direction changes, but the user is unable to change it back to any other option

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Thanks for the report and collaboration!

We have tried to reproduce the issue by upgrading the Magento instance from 2.4.6 to 2.4.7-p3 but the issue is not reproducible for us. Refer to the below screenshots below:

_**Magento Instance 2.4.6**_
![Dashboard-246](https://github.com/user-attachments/assets/a3a20db4-e4ef-4572-9e05-6eb06b60ac66)

_**Category Default Sorting as Descending**_
![Category-246-desc](https://github.com/user-attachments/assets/cc5d64dc-a548-4654-a98b-ca6146fa63a2)

### After upgrading to 2.4.7-p3
_**Category Default Sorting as Descending**_
![image](https://github.com/user-attachments/assets/c723ab16-3605-4837-ae80-cc61d2ed7345)

### Code from `catalog_category_view.xml`
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
	<referenceContainer name="content">
		<referenceBlock class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list">
			<action method="setDefaultDirection">
				<argument name="dir" xsi:type="string">desc</argument>
			</action>
		</referenceBlock>
	</referenceContainer>
    </body>
</page>
```

Please let us know if we missed anything.

Thanks

**Comment by ioweb-gr** [comment]
Hello @engcom-Hotel , 
I think you missed steps 3 and 4. From the screenshots your provide it doesn't seem like you tried to change the direction to asc by clicking on the arrow link. 
Thank you for looking into this.

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

We have tried that as well. But the issue is still not reproducible for us. Please have a look at the below screencast:
[Category-2.webm](https://github.com/user-attachments/assets/7d2aeccb-2d73-4a8d-beb1-0565356d8f6f)

Let us know if we missed anything.

Thanks

**Comment by ioweb-gr** [comment]
I also tested this again on a fresh installation of 2.4.7 and it doesn't happen, so I can guess it's most likely a conflict with a third party module even though only a couple are installed. Thank you for verifying and let's close this issue
