### ISSUE TITLE
Default Store id is not matching the store id from the request path

### ISSUE THREAD

**Issue by grifx** [magento/magento2#39356]
### Preconditions and environment

- Magento version: 2.4.7

The default Store Code is not resolved from the request path

E.g: https://magento.test/admin/admin/system_config/edit/key/ed990becfa3389bf0eeccf8ccefc99f7cc2a2da4cc901848f541087d757d8e27/section/main_section/store/2

The store is resolved properly when the query parameter is set:

https://magento.test/admin/admin/system_config/edit/key/ed990becfa3389bf0eeccf8ccefc99f7cc2a2da4cc901848f541087d757d8e27/section/main_section/store/2?___store=2

### Steps to reproduce

- Case 1: https://magento.test/admin/admin/system_config/edit/key/ed990becfa3389bf0eeccf8ccefc99f7cc2a2da4cc901848f541087d757d8e27/section/main_section/store/2
- Case 2: 
https://magento.test/admin/admin/system_config/edit/key/ed990becfa3389bf0eeccf8ccefc99f7cc2a2da4cc901848f541087d757d8e27/section/main_section/store/2?___store=2

### Expected result

- Case 1: 2
- Case 2: 2

### Actual result

- Case 1: 1
- Case 2: 2

### Additional information

If this is a bug, it could be in:
- \Magento\Store\App\Request\StorePathInfoValidator::getValidStoreCode

The default store value is already incorrect from the cache in:
- \Magento\Store\Model\StoresData::getStoresData

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @grifx,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and we need more information to proceed further.Could you please elaborate the steps to reproduce and expected and actual results.


<img width="1440" alt="Screenshot 2024-11-13 at 10 31 48" src="https://github.com/user-attachments/assets/4c9b174c-13b7-4e1c-beca-da20b0b069ef">



<img width="1440" alt="Screenshot 2024-11-13 at 10 32 16" src="https://github.com/user-attachments/assets/5614819f-4bbf-4fd3-bba7-6725cc4b0385">



Thanks.

**Comment by engcom-Bravo** [comment]
Hi @grifx,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
