### ISSUE TITLE
Upgrade from 2.0.2 to 2.0.3 - Sorry, we can't take that action right now.

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#3935]
Installed Magento 2.0.2 few weeks before by downloading the ZIP file from magento website.

My System Config details are correct.

When I click the 'System Upgrade' it says *_'Sorry, we can't take that action right now.'
*_
My cron is working fine and running for every 5 minutes.

**Comment by vancoz** [comment]
Hi @malaiselvan, do you have generated public and private keys?
Have you logged in to marketplace inside Component Manager?
Please review this doc http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/were-sorry.html  I hope it will help you! Let us know if you still have this issue.

**Comment by mazhalai** [comment]
@malaiselvan also any errors in the browser?

EDIT: I got the same error when my private and public keys were not saved. Click on system config and save your private and public keys and then it should work

**Comment by malaiselvan** [comment]
@mazhalai mazhalai @vancoz 
Yes, I do got a valid private and public keys.  I saved those keys under 'System Config'.  I could able to connect to the repo via component manager.  I.e, when I click the Sync in the component manager the system able to tell the New Updates as 110.

No JS or PHP errors found on the browser screen.

Below is my composer.json

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```

Update: I guess the problem is I have the data migration repository.  This is what I see in the `.update_cronjob_status` file

```
{
    "readiness_checks": {
        "file_permissions_verified": false,
        "error": "Found non-writable path(s):<br/>/home/sitenet/public_html/var/composer_home/cache/vcs/https---github.com-magento-data-migration-tool-ce/objects/pack/pack-3d489e3a8c8d0701d46a20816c8988c5f6c28638.pack<br/>/home/sitenet/public_html/var/composer_home/cache/vcs/https---github.com-magento-data-migration-tool-ce/objects/pack/pack-3d489e3a8c8d0701d46a20816c8988c5f6c28638.idx"
    },
    "last_timestamp": 1459454046,
    "current_timestamp": 1459454046
}
```

**Comment by alankent** [comment]
2.0.3 got pulled from the site - 2.0.4 will be released shortly. Something went wrong with packaging - need to crank the handle again.

**Comment by svewap** [comment]
@malaiselvan Remove the second repository and try it again. I think it's a bug.

```
 "repositories": [
    {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
 ]
```

**Comment by vancoz** [comment]
Thank you @svewap this is good workaround.
@malaiselvan can you please use proposed workaround to upgrade Magento? Or use command line upgrade?

We created internal ticket to track and resolve this issue MAGETWO-51439

**Comment by malaiselvan** [comment]
I removed the data migration repository from the composer.json and tried the upgrade. The system able to find the 2.0.4.  But it fails on the readiness check as below.

![image](https://cloud.githubusercontent.com/assets/5956639/14216981/43512b1a-f869-11e5-8468-b6fad870bebf.png)

Any ideas?

**Comment by mazhalai** [comment]
@malaiselvan your `var/composer_home` directory is not writable.

**Comment by vancoz** [comment]
Hi @malaiselvan please check your ownership and permission setting, look at 
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html and http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html#install-perms-set

Thank you.

**Comment by malaiselvan** [comment]
My bad... Yes. I set the file permission now and the script error has gone.  But still the component dependency is throwing the error.

```
Check Component Dependency
We found conflicting component dependencies. Hide detail

For additional assistance, see component dependency help .
```

Will there be any log file where I can check???

**Comment by vancoz** [comment]
@malaiselvan have you installed some modules from this repo? 
 "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        }

If yes, I recommend you to add this repo back to root composer.json and use CLI upgrade:
1. composer require magento/product-community-edition 2.0.4 --no-update
2. composer update
3. bin/magento setup:upgrade

Thank you.

**Comment by malaiselvan** [comment]
@vancoz I never done this before.

I added the migration repository and tried the first 2 commands.  See as below

![image](https://cloud.githubusercontent.com/assets/5956639/14217904/709ba7b2-f86e-11e5-82b9-9dc2800f2711.png)

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition 2.0.4 exists as magento/product-community-edition[2.0.2, 0.42.0-beta7, 2.0.0, 2.0.1] but those are rejected by your constraint.
```

**Comment by vancoz** [comment]
@malaiselvan can you please run:
$ composer self-update 
$ composer clearchache 
and composer update again?

Thank you.

**Comment by malaiselvan** [comment]
@vancoz Now it is like below

```
mysitenet@a2ss26 [~/public_html]# composer self-update
Updating to version 1.0.0-beta2.
    Downloading: 100%
Use composer self-update --rollback to return to version cb8587cdade3cdbe00b8d6d2488458a2b6c0a592
mysitenet@a2ss26 [~/public_html]# composer clearcache
Clearing cache (cache-dir): /home/mysitenet/.composer/cache
Clearing cache (cache-files-dir): /home/mysitenet/.composer/cache/files
Clearing cache (cache-repo-dir): /home/mysitenet/.composer/cache/repo
Clearing cache (cache-vcs-dir): /home/mysitenet/.composer/cache/vcs
All caches cleared.
mysitenet@a2ss26 [~/public_html]# composer require magento/product-community-edition 2.0.4 --no-update
./composer.json has been updated
mysitenet@a2ss26 [~/public_html]# composer update
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  Invalid credentials for 'https://repo.magento.com/packages.json', aborting.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

mysitenet@a2ss26 [~/public_html]#
```

I checked the auth.json and the keys are correctly stored.
Should I update the public & private key some where else???

**Comment by vancoz** [comment]
@malaiselvan you can update keys in ~/.composer/auth.json file

**Comment by malaiselvan** [comment]
@vancoz You are great... It started upgrading... Got a quick help at the below step

```
- Updating magento/data-migration-tool dev-master (0928571 => 5417f6b)
 The package has modified files:
 D etc/ce-to-ce/1.9.1.0/config.xml.dist
 D etc/ce-to-ce/1.9.1.0/map.xml.dist
 D etc/ce-to-ce/settings.xml.dist
 Discard changes [y,n,v,d,s,?]?
```

I have some custom configuration done on the data migration tool.  I do not want to overwrite them.... What should I give here?

**Comment by vancoz** [comment]
@malaiselvan this means that you have changed files in vendor directory (I would not recommend to do it in feature btw). 
This is explanation of options:
y - discard changes and apply the update
n - abort the update and let you manually clean things up
v - view modified files
s - stash changes and try to reapply them after the update

Thank you

**Comment by malaiselvan** [comment]
@vancoz Thanks.  Since I got the backup of those files, I just gave `y` and proceeded... 

I am just waiting for the upgrade to complete for success.... Thanks for the help so far... You are very helpful.

**Comment by vancoz** [comment]
@malaiselvan thank you for choosing Magento, have a good weekend.

**Comment by malaiselvan** [comment]
@vancoz It comes to the prompt as below

```
Writing lock file
Generating autoload files
mysitenet@a2ss26 [~/public_html]#
```

I logged in at back end and I am able to see the current version as 2.0.4 (Great)....
Should I do any post upgrade steps???

**Comment by vancoz** [comment]
@malaiselvan yes, this means that you are ready to run "php bin/magento setup:upgrade"

**Comment by malaiselvan** [comment]
@vancoz Thanks.  The upgrade is complete now.  Thanks

**Comment by daim2k5** [comment]
@malaiselvan so we can close the issue?
