### ISSUE TITLE
Cannot add products after changing bundle

### ISSUE THREAD

**Issue by POleszkiewicz** [magento/magento2#3937]
## Steps to reproduce
1. Install Magento 2.0.3
2. Add a bundle product.
3. Order this bundle product using user A
4. change the bundle product (remove some simple products and add other) and save
5. Order any product using user A

Expected result
1. you can order products using user A
## Actual result
1. When ordering using user A I get the error message: " The options you selected are not available." , even when trying a simple product with no options.
2. When ordering using a new user - everything works ok.

**Comment by POleszkiewicz** [comment]
This is kind of critical, as the existing users cannot order anything else.......

**Comment by POleszkiewicz** [comment]
anything happens with this?

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54156

**Comment by SerhiyShkolyarenko** [comment]
@POleszkiewicz, it's fixed in 2.1 release and unfortunately it's not backportable to 2.0.x branch.

**Comment by piotrekkaminski** [comment]
Closing as fixed in 2.1.
