### ISSUE TITLE
Reset Password leads customer being able to log in just once and then has to wait for cutoff 

### ISSUE THREAD

**Issue by jaydainn** [magento/magento2#39388]
### Preconditions and environment

- Magento 2.4.6-p8
- Set the magento timezone to india/kolkata and server time to europe/paris time

### Steps to reproduce

1. Ask for a reset password link for a customer. 
2. Reset password then login. 
3. The time for created_at in the customer_visitor table and session_cutoff in the  customer_entity table is updated with the website's timezone.
4. Log out right away 
5. When logging back in , created_at is updated with the server time and the login request doesn't go through because of the condition in app/code/Magento/Customer/Model/Session/Validators/CutoffValidator.php
6. You then have to wait till session_cutoff is lower than created_at to be able to log in. 

### Expected result

Login should be successful on the first try.

### Actual result

Login failed and redirects to the login page with no error message. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @jaydainn ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4 develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

Steps to reproduce:
1. Ask for a reset password link for a customer.
2. Reset password then login.
3. The time for created_at in the customer_visitor table and session_cutoff in the customer_entity table is updated with the website's timezone.
customer_visitor table - 
![image](https://github.com/user-attachments/assets/e53adaa0-82dd-43aa-9d61-bc62e6d5388f)

customer_entity table - 
![image](https://github.com/user-attachments/assets/45dbfc82-4551-499d-b51e-ad8abe19ef63)
4. Log out right away
5. When logging back in , created_at is not updated with the server time 
![image](https://github.com/user-attachments/assets/b9d2bd5b-5982-4406-b6ef-57f6a8ddf059)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @jaydainn ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
