### ISSUE TITLE
2FA needs to be configured on every login when 2 providers are selected in the configuration

### ISSUE THREAD

**Issue by idziakjakub** [magento/magento2#39380]
### Preconditions and environment

Magento version 2.4.6-p8
2FA enabled for 2 providers: `Google Authenticator` and `U2F (Yubikey and others)`

### Steps to reproduce

1. Enable 2FA for 2 providers: `Google Authenticator` and `U2F (Yubikey and others)` in system configuration
2. Login first time using `Google Authenticator` authorization
3. Recieve email with link:
![Zrzut ekranu z 2024-11-18 15-18-24](https://github.com/user-attachments/assets/0aceaf05-2995-4991-9585-d14b73bf8d06)
4. Click the link and scan the QR code in Google Authenticator
5. Log in using the Authenticator code
6. After successful login, log out from the admin
7. Try to log in again
8. Receive an email with a link instead of a form for the Authenticator code

### Expected result

After the first login, the next login attempt should show a form with the option to enter an authorization code
![Zrzut ekranu z 2024-11-18 15-31-31](https://github.com/user-attachments/assets/7ba45ceb-9979-45bd-93ab-fd8e9c82af58)

### Actual result

After the first login, each login attempt sends another email with the need to activate the configuration
![Zrzut ekranu z 2024-11-18 15-18-24](https://github.com/user-attachments/assets/e36fc0bb-5297-41d9-ab5a-f642c25ec392)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by idziakjakub** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Bravo** [comment]
Hi @idziakjakub,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.


Thanks.

**Comment by codebynilay** [comment]
We are getting same issue with Magento ver. 2.4.7-p8. Kindly check and provide solution asap.
