### ISSUE TITLE
Contribution tools and help

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#3938]
I have been working with Typo3 for a while and as part of their projects they have some post commit hooks that will run tests and code sniffer and fail if your commits do not match the standards or fail tests. There is also the commit template so that you know how to format your messages.

This is a big help with multiple people contributing to open source projects.

It can be found at https://github.com/FluidTYPO3/fluidtypo3-development and you can see it being included via composer.json on https://github.com/FluidTYPO3/flux/blob/development/composer.json under require-dev.

This might be a nice feature to help and encourage people to contribute to the Magento2 project.

**Comment by avoelkl** [comment]
:+1:

**Comment by piotrekkaminski** [comment]
We do have internal commit hooks that do just that. Will see if they are deeply tied to our process or can be used in more generic way.

**Comment by piotrekkaminski** [comment]
@maksek please review and advise.

**Comment by dmanners** [comment]
So @amacgregor and I did have a go at this during the Imagine hackathon and results can be seen at https://github.com/amacgregor/magento-contributor-tools

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Contribution-tools-and-help/idi-p/44741).
