### ISSUE TITLE
How to install magento on local windows10

### ISSUE THREAD

**Issue by sunnystone85** [magento/magento2#39396]
### Summary

Hi Good day!
I am using windows10, with xampp, php8.2.12, elasticsearch7.17.25. 
When I install magento 2.4.
I got the some issues blocked me...

I use the code of 2.4 branch, when I got the errors, I performed composer update many times, but the errors still....

Thank you for your support~~~

### Examples

sometimes like Error 1:
[Progress: 445 / 896]
Installing search configuration...

There is an error in D:\xampp\htdocs\magento2\app\code\Magento\Elasticsearch7\Model\Client\Elasticsearch.php at line: 104
Class "Elasticsearch\ClientBuilder" not found#0 D:\xampp\htdocs\magento2\app\code\Magento\Elasticsearch7\Model\Client\Elasticsearch.php(117): Magento\Elasticsearch7\Model\Client\Elasticsearch->getElasticsearchClient()

sometimes like Error 2:
In PatchApplier.php line 172:

  Unable to apply data patch Magento\Theme\Setup\Patch\Data\RegisterThemes fo
  r module Magento_Theme. Original exception message: Wrong file

In Gd2.php line 70:

  Wrong file

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @sunnystone85,

Thanks for the report and collaboration!

As per written in the [official documentation](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements#operating-systems-linux-x86-64):

> Linux distributions, such as RedHat Enterprise Linux (RHEL), CentOS, Ubuntu, Debian, and similar. **Microsoft Windows and macOS are not supported.**

So please use Magento-supported operating systems.

Thanks

**Comment by sunnystone85** [comment]
Thank you...
