### ISSUE TITLE
Error del servidor en categorías y productos

### ISSUE THREAD

**Issue by comercio2024** [magento/magento2#39397]
### Preconditions and environment

- Magento version 2.4.7
- Aparece error del servidor en categorias, y productos. 

### Steps to reproduce

Catálogo, Productos, Edit Products, Categories

### Expected result

Poder seleccionar las categorías y poder personalizar los productos

### Actual result

Categorías no está visible, aparecen en blanco. En el header se encuentran pero el problema ocurre en la configuracion de productos.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Serfe-com** [comment]
Hi @comercio2024 This might be an issue with the indexing or ElasticSearch service. We had similar issues that were fixed doing a full reindex or updating the ElasticSearch service with a supported version.

**Comment by engcom-Bravo** [comment]
@Serfe-com Thanks for your Contribution!!!.

Hi @comercio2024,

Could you please refer this comment https://github.com/magento/magento2/issues/39397#issuecomment-2498300870 and please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @comercio2024,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
