### ISSUE TITLE
Mage Class used in Magento2

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#3940]
I think this line has been missed when converting from magento 1 to Magento2. Mage class has been entirely removed in magento2 but there are still some references of it in the code. It might throw an error as the code is not commented. Or is this for some sort of backward compatibility ? Here is one instance i found:

**File:** /vendor/magento/magento2-base/lib/internal/Cm/Cache/Backend/File.php

Line 64: 

```
public function __construct(array $options = array())
    {
          //some code here 
            $options['cache_dir'] = Mage::getBaseDir('cache'); 
          //some other code here
}
```

This is there in Magento 2.0.2 as well as Magento 2.0.3 .

**Comment by shiftedreality** [comment]
Hi @parekhreena 

Thank you for submission. Created internal issue MAGETWO-51633 to resolve this bug.

**Comment by parekhreena** [comment]
@shiftedreality - Thank you !!

**Comment by mazhalai** [comment]
@parekhreena this issue has been fixed and delivered to develop branch. Closing this issue. Please open a new one if problems persist.

**Comment by parekhreena** [comment]
@mazhalai - Thank you !!
