### ISSUE TITLE
Magento - Tutorial - double tittle

### ISSUE THREAD

**Issue by Lig875** [magento/magento2#39401]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Hello,

I am currently stuck on Magento, when I format my articles, two identical titles appear, one at the very top of the article and the second at the beginning of the article. Do you know how to remove the second title to keep only the H1, please? Is it possible for you to send me a tutorial with the locations I need to go to change this configuration, please?

Thank you.

Kind regards,

Liga CLUZEAU

### Expected result

-

### Actual result

-
![Magento](https://github.com/user-attachments/assets/67502881-3774-4d39-9afb-f44f9a993af2)

### Additional information

-

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Lig875,

Thanks for the report and collaboration!

Please provide us with more information on the issue, like:

- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Bravo** [comment]
Hi @Lig875,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
