### ISSUE TITLE
Widget with static block does not show on product detail page in "Main Content Top"

### ISSUE THREAD

**Issue by maile-it-solutions** [magento/magento2#39400]
### Preconditions and environment

- Magento version 2.4.5-p10

### Steps to reproduce

- Go to Content->Widgets click "Add Widget"
- In settings use Type = CMS Static Block find Desing Theme = Magento Luma
- Press Continue and set Widget Title 
- Assign the widget to All Store Views
- Add a layout Update
- Choose display on Virtual Product
- Show it for a specific product and use the container "Main Content Top"
- Under Widget Options select any block available

### Expected result

On the Product Detail Page of the selected virtual product the content of the static block is visible

### Actual result

The static block is not rendered

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maile-it-solutions** [comment]
Hi @engcom-Delta and @engcom-Hotel it is ready, but I don't have permission to change the label to "Issue: Confirmed"

**Comment by engcom-Delta** [comment]
Hi @maile-it-solutions ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4 develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**

1. Go to Content->Widgets click "Add Widget"
2. In settings use Type = CMS Static Block find Desing Theme = Magento Luma
3. Press Continue and set Widget Title
4. Assign the widget to All Store Views
5. Add a layout Update
6. Choose display on Virtual Product
7. Show it for a specific product and use the container "Main Content Top"
![image](https://github.com/user-attachments/assets/2bd4c0de-5a8a-4bf9-9e21-096c2a18b7ac)
![image](https://github.com/user-attachments/assets/67a0ebf0-8653-45ab-b9bb-d0c7f81ef35a)

8. Under Widget Options select any block available
![image](https://github.com/user-attachments/assets/e2d6da73-5f0e-468f-ae2c-9b7733482f43)
9. Navigate to virtual product and look for static block.
10. Observe static block is displaying as expected.
![image](https://github.com/user-attachments/assets/2b2c9d8f-e11c-4404-95f4-de40163e9258)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by maile-it-solutions** [comment]
Hi @engcom-Delta thanks for the details, but I am still facing this issue. The only difference I see from our instances is that I do not use page builder for the block and that I have the demo data installed.

**Comment by engcom-Delta** [comment]
Hi @maile-it-solutions ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4 develop instance with page builder disabled, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**

1. Go to Content->Widgets click "Add Widget"
2. In settings use Type = CMS Static Block find Desing Theme = Magento Luma
3. Press Continue and set Widget Title
4. Assign the widget to All Store Views
5. Add a layout Update
6. Choose display on Virtual Product
7. Show it for a specific product and use the container "Main Content Top"
![image](https://github.com/user-attachments/assets/79378006-b280-4939-82c2-9f41b28c028d)
8. Under Widget Options select any block available
![image](https://github.com/user-attachments/assets/b41ab81e-60bc-4a28-be90-5b39695e4da1)
9. Navigate to virtual product and look for static block.
Observe static block is displaying as expected.
![image](https://github.com/user-attachments/assets/070aeba9-a182-4375-a326-28b857f6fe9d)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @maile-it-solutions ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
