### ISSUE TITLE
Unable to Add Products Manually in Configurable Product

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#3942]
## Steps to reproduce
1. Install Magento 2.0.3
2. Migrate or create a Configurable Product with 300 variations, save.
3. Go back into that product, press the "add products manually"
## Expected result
1. With products with smaller variation sets the functionality works
2. I have increased the LimitRequestLine to work around 414 (Request-URI Too Large) error (per issue #3495)
3. I have not been able determine the size limit yet.
## Actual result
1. Error Message Pops: Attention Something went wrong.
2. No browser messages in console. 
3. Error in Apache Logs:

[Thu Mar 31 18:34:14.139835 2016] [proxy_fcgi:warn] [pid 4968] [client 60.225.85.XXX:37893] AH02536: couldn't encode envvar 'QUERY_STRING' in 16384 bytes, referer: http://EXAMPLE/admin/catalog/product/edit/id/3/key/81f78988e9908f8d89115a62f01eacdd8611886ce257a56bd9ec6c22d83930e6/

[Thu Mar 31 18:34:14.139840 2016] [proxy_fcgi:warn] [pid 4968] [client 60.225.85.XXX:37893] AH02536: couldn't encode envvar 'REQUEST_URI' in 16384 bytes, referer: http://EXAMPLE/admin/catalog/product/edit/id/3/key/81f78988e9908f8d89115a62f01eacdd8611886ce257a56bd9ec6c22d83930e6/
## Environment
1. PHP 7.0.4 run as FPM not MOD_PHP (unable to test with 7.0.2 or 7.0.3 to see if it is a PHP error)
2. Apache 2.4.18
3. MYSQL 5.6

**Comment by joebusby** [comment]
I have not been able to add products manually when there are many configured products since since the first version.  It's mentioned in thread #3228  and it might relate to this problem.

**Comment by rudik99** [comment]
Any short term work arounds?

**Comment by joebusby** [comment]
With the right php settings, I have been able to add up to about 400 configured products (for one configurable product) going through the "Edit Configurations" process as long as I don't add any images to the products.  You then need to put the images in manually, one by one.   If you add images during the "Edit Configurations" process, I can only get about 125 products in or it bombs.  The "Add products manually" feature has been useless for me, but I have managed to get about 2100 products in using the above method with a lot of "clicks" to add the images.  You will get good at using filters.

Related to #3154

**Comment by rudik99** [comment]
@joebusby be great if you could share your PHP tweaks ?

**Comment by joebusby** [comment]
I have:  

max_input_vars -> 5000
max_execution_time = 600
memory_limit = 2048M

but I think the max_input_vars is the most important
You can try:  

error_reporting = off

All in php.ini

I am using this on 

Debian 8 up to date
MySQL version 5.6.28
OpenVZ 6 cores
PHP 5.6.17-0+deb8u1

so it may not be the same as your php 7.0.4

**Comment by joebusby** [comment]
I have been having better luck with chrome than firefox on windows 10 for adding many configurable products

With chrome you may be able to avoid hitting the "wait" dialog by using:

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-hang-monitor

in the windows shortcut properties

**Comment by rudik99** [comment]
Is this something that will get fixed in 2.1 release?

**Comment by piotrekkaminski** [comment]
@choukalos performance use case

**Comment by piotrekkaminski** [comment]
@rkhoury82 can you provide more info on your specific use case? what type of products? what is the maximum number of products you would like to use etc?

**Comment by rudik99** [comment]
For example, I run multiple apparel store's (swimwear) 
We offer all products in all colours and sizes (some might be stocked and some are made to order) 

So configurable product:

10-15 Sizes (from Attributes)
20-30 Colours (from Attributes)

So 300-400 combinations (Simple Product), need the simple product to manage stock / inventory

**Comment by PieterCappelle** [comment]
Same problem still exists in 2.1. In my case problem was fixed updating max_input_vars to 5000 in PHP7.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-Add-Products-Manually-in-Configurable-Product/idi-p/45269).

**Comment by rudik99** [comment]
@piotrekkaminski I don't think this is a feature request. This is a bug. 
This functionality doesn't work in M2.X period; In addition the work arounds create security risks.
I think this should be re-opened;
