### ISSUE TITLE
SQL error in core code

### ISSUE THREAD

**Issue by fabotha** [magento/magento2#39431]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.7 p1

### Steps to reproduce

logon and go to sales/ orders

### Expected result

checking the Log file /var/www/vhosts/firesupport.uk/htdocs/var/log
file commerce-data-export-errors.log

shows SQL error

### Actual result

web site still works but error seen that repeats constantly
[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ORDER BY entity_id) / 100) AS `batch_number`, `t`.`entity_id` FROM (SELECT DIST' at line 1, query was: INSERT INTO `sales_order_data_exporter_cl_index_batches` (`batch_number`, `entity_id`) SELECT CEILING(ROW_NUMBER() OVER (ORDER BY entity_id) / 100) AS `batch_number`, `t`.`entity_id` FROM (SELECT DISTINCT  `v`.`entity_id` FROM `sales_order_data_exporter_cl` AS `v` WHERE (v.version_id > 83844)) AS `t` at /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109)
[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ORDER BY entity_id) / 100) AS `batch_number`, `t`.`entity_id` FROM (SELECT DIST' at line 1 at /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90)"} []

### Additional information

slows down the system

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @fabotha,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.We have checked log files and we didn't see any sql related errors.

Could you please verify if any third party modules can causing this issue.

Thanks.

**Comment by fabotha** [comment]
Hi
I have quite a few extensions, the folder with the code in looked more core magento than an extension, this is why I raised a ticket.

Any idea how I try to find the extension?

The error sql says its located here /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php

If you can point me in the right direction I can provide more info

Thanks
Frank

Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by GrassH** [comment]
Hello @fabotha,

The issue is not reproducible. I suggest you try upgrading to MySQL 8.0, as window functions are supported starting from MySQL 8.0. Please referer to https://dev.mysql.com/doc/refman/8.0/en/window-functions-usage.html.

Thanks

**Comment by engcom-Bravo** [comment]
@GrassH Thanks for your Contribution!!.

Hi @fabotha,

Please refer this https://github.com/magento/magento2/issues/39431#issuecomment-2518863275. and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @fabotha,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Comment by vandijkstef** [comment]
For anyone still ending up here; This "issue" was introduced in Mage 2.4.7-base and is indeed related to not using a modern SQL server version. Updating my dev box from MySQL 5.7 to 8.0 fixed the issue for me.
