### ISSUE TITLE
FPC Cache via Files or Redis does not still work on Magento 2.4.7 for multi-view stores

### ISSUE THREAD

**Issue by dandrikop** [magento/magento2#39439]
### Preconditions and environment

I have to open again the issue [#39221](https://github.com/magento/magento2/issues/39221) as it was closed before we try the proposed solution. We have provided our feedback within the issue [#39221](https://github.com/magento/magento2/issues/39221), but since it is closed, then no action may be taken.

Besides the Files used as the default medium for FPC, I tested Redis with Magento 2.4.7-p2 and FPC did not work. Namely it seems that cached content is stored at Files or Redis. The problem is that Magento cannot somehow identify the cached pages so it thinks that they have not been cached.

This problem is No-Go for Magento 2.4.7 for store owners with multi-domain and multi-view Magento installations, as Magento without FPC is out-of-question. It is said that the problem will be fixed at Magento 2.4.8. However, a patch should become available at Magento Quality Patches; otherwise store owners with multi-domain and multi-view Magento installations should stay at version 2.4.6 till 2.4.8 is released.

### Steps to reproduce

1. Set the multi-view store to Developer mode.
2. Visit various pages on the front-end.
3. Monitor the value of the HTTP header "X-Magento-Cache-Debug".

### Expected result

The value of the HTTP header "X-Magento-Cache-Debug" is HIT for subsequent requests of the same page.

### Actual result

The value of the HTTP header "X-Magento-Cache-Debug" is always MISS no matter how many times a page has been visited at the front-end.

### Additional information

The error depends on the implementation. My multi-store implementation has 7 websites, each website has one store, and each store has one store view. The routing at the appropriate store view is regulated by the .htaccess file with directives such as the following ones:

SetEnvIf Host fr.dlastore.com MAGE_RUN_CODE=french_dla
SetEnvIf Host fr.dlastore.com MAGE_RUN_TYPE=store

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dandrikop** [comment]
The patch ACSD-62591 was mentioned to fix the problem with the FPC on Magento 2.4.7. However, the below link mentions that the patch ACSD-62591 fixes something else:

[https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/patches-available-in-qpt/v1-1-55/overview](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexperienceleague.adobe.com%2Fen%2Fdocs%2Fcommerce-operations%2Ftools%2Fquality-patches-tool%2Fpatches-available-in-qpt%2Fv1-1-55%2Foverview&data=05%7C02%7Cglo24157%40adobe.com%7C248b6f35f34f4f8f22f908dd13eb7b9c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638688624317402779%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=nZWX5TwtRBmazHf2k0kl57bCNDMwj1kfAEns84FOM%2BM%3D&reserved=0)

In addition, I tried to install the patch on my test environment which is on Magento 2.4.7-p2 and it does not seem to be available for that version of Magento (see below screenshot). Please do not close issues before we confirm successful resolution.

![image](https://github.com/user-attachments/assets/c3afbe5d-922d-4e30-98f4-ce2bd460d3d3)

**Comment by GrassH** [comment]
Hello @dandrikop,

In **developer** Mode, the response always returns **MISS**. Please refer to the following links:
https://github.com/magento/magento2/blob/7ead0dcf0c8b50976d707a4ac3e589692b4bd408/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php#L76
https://github.com/magento/magento2/blob/7ead0dcf0c8b50976d707a4ac3e589692b4bd408/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php#L83
https://github.com/magento/magento2/blob/7ead0dcf0c8b50976d707a4ac3e589692b4bd408/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php#L114

Thanks

**Comment by dandrikop** [comment]
Hello @GrassH,

I didn't understand your message. Have you read my last comment? 

The patch ACSD-62591 was mentioned to fix the problem with the FPC on Magento 2.4.7. However, the below link mentions that the patch ACSD-62591 fixes something else:

[https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/patches-available-in-qpt/v1-1-55/overview](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexperienceleague.adobe.com%2Fen%2Fdocs%2Fcommerce-operations%2Ftools%2Fquality-patches-tool%2Fpatches-available-in-qpt%2Fv1-1-55%2Foverview&data=05%7C02%7Cglo24157%40adobe.com%7C248b6f35f34f4f8f22f908dd13eb7b9c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638688624317402779%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=nZWX5TwtRBmazHf2k0kl57bCNDMwj1kfAEns84FOM%2BM%3D&reserved=0)

In addition, I tried to install the patch on my test environment which is on Magento 2.4.7-p2 and it does not seem to be available for that version of Magento (see above screenshot).

**Comment by dandrikop** [comment]
Hello @engcom-Bravo, @engcom-Hotel,

Please check the problems mentioned with the patch ACSD-62591, and keep this very issue open till we confirm resolution.

**Comment by Webroju** [comment]
Hello @engcom-Bravo, @engcom-Hotel,

I found the patch in 2.4.7.-p3, have installed it, but this patch fix nothing.

**Comment by engcom-Hotel** [comment]
Hello @dandrikop,

I think we can close this issue on behalf of this https://github.com/magento/quality-patches/issues/129#issuecomment-2528532667. And for the issues related to the cache key, you can raise a new issue with the exact steps to reproduce, actual and expected behavior.

Thanks

**Comment by dandrikop** [comment]
Hello @engcom-Hotel,

I opened the new issue below as you recommended:

https://github.com/magento/magento2/issues/39456

**Comment by engcom-Hotel** [comment]
Thanks @dandrikop for raising the separate issue. We are closing this issue as completed.
