### ISSUE TITLE
Sending SMTP email fails Relay access denied. Not authenticated to send as sales@firesupport.uk

### ISSUE THREAD

**Issue by fabotha** [magento/magento2#39430]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.7 p1

### Steps to reproduce

settings in stores/configuratiom/advanced/mail send settings
Disable Email Communications	No
Transport	SMTP
Host	smtp.hosts.co.uk
Port (25)	465
Set Return-Path	Specified 
Return-Path Email	sales@firesupport.uk

Username	admin@firesupportuk.store
Password	••••••

Auth	LOGIN
SSL	SSL

### Expected result

send an email and have a return address of sales@firesupport.uk

I bought a domain firesupportuk.store so as to use the SMTP settings for sending the email

### Actual result

error
[2024-12-03T13:30:43.397719+00:00] main.ERROR: Laminas\Mail\Protocol\Exception\RuntimeException: Relay access denied. Not authenticated to send as sales@firesupport.uk
 in /var/www/vhosts/firesupport.uk/htdocs/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:355
Stack trace:
#0 /var/www/vhosts/firesupport.uk/htdocs/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(348): Laminas\Mail\Protocol\AbstractProtocol->_expect()
#1 /var/www/vhosts/firesupport.uk/htdocs/vendor/laminas/laminas-mail/src/Transport/Smtp.php(258): Laminas\Mail\Protocol\Smtp->mail()
#2 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-email/Model/Transport.php(183): Laminas\Mail\Transport\Smtp->send()
#3 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Transport->sendMessage()
#4 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Email\Model\Transport\Interceptor->___callParent()
#5 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage()
#7 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/vhosts/firesupport.uk/htdocs/generated/code/Magento/Email/Model/Transport/Interceptor.php(32): Magento\Email\Model\Transport\Interceptor->___callPlugins()
#9 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(75): Magento\Email\Model\Transport\Interceptor->sendMessage()
#10 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-sales/Model/Order/Email/NotifySender.php(38): Magento\Sales\Model\Order\Email\SenderBuilder->send()
#11 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-sales/Model/Order/Email/Sender/OrderCommentSender.php(100): Magento\Sales\Model\Order\Email\NotifySender->checkAndSend()
#12 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php(68): Magento\Sales\Model\Order\Email\Sender\OrderCommentSender->send()
#13 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\AddComment->execute()
#14 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callParent()
#15 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/vhosts/firesupport.uk/htdocs/generated/code/Magento/Sales/Controller/Adminhtml/Order/AddComment/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callPlugins()
#17 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->execute()
#18 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#19 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#20 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callParent()
#21 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#23 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/vhosts/firesupport.uk/htdocs/generated/code/Magento/Sales/Controller/Adminhtml/Order/AddComment/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callPlugins()
#25 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->dispatch()
#26 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#27 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#28 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#29 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#30 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/vhosts/firesupport.uk/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#32 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#33 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#34 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#35 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#36 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#37 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#38 /var/www/vhosts/firesupport.uk/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#39 /var/www/vhosts/firesupport.uk/htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#40 /var/www/vhosts/firesupport.uk/htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#41 {main} {"exception":"[object] (Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 554): Relay access denied. Not authenticated to send as sales@firesupport.uk

 at /var/www/vhosts/firesupport.uk/htdocs/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:355)"} []

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @fabotha,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and we are able to send the mails successfully.Could you please contact to the corresponding domain owners(support) of [sales@firesupport.uk](mailto:sales@firesupport.uk).

Hence we are closing this issue.

Thanks.
