### ISSUE TITLE
SOAP doesn't not work in production mode

### ISSUE THREAD

**Issue by vesan-83** [magento/magento2#3944]
## Steps to reproduce
1. Install Magento from `2.0` branch (2.0.3 version)
2. bin/magento deploy:mode:set production
3. bin/magento setup:di:compile
4. Send SOAP request
## Expected result

See expected-result.png in the attachment
## Actual result

See actual-result.png in the attachment
## Details

See line
`$soapServer = $this->_objectManager->create('SoapServer', ['wsdl' => $url, 'options' => $options]);`
It gives fatal error because object manager config Magento\Framework\ObjectManager\Config\Compiled pass invalid arguments to SoapServer class.
It works normally if instantiate SoapServer without object manager e.g.
`$soapServer = new \SoapServer($url, $options);`
Also following will work (pass arguments without keys):
`$soapServer = $this->_objectManager->create('SoapServer', [$url, $options]);`

[attachments.tar.gz](https://github.com/magento/magento2/files/197615/attachments.tar.gz)

**Comment by jamescowie** [comment]
Thanks for the report. Ive been using I will see if I can replicate. Have you looked at how it might need to be fixed ?

**Comment by vesan-83** [comment]
Yes, see the fix on the image
![selection_218](https://cloud.githubusercontent.com/assets/16537847/14199222/22febad6-f7eb-11e5-8843-3e65ef3ea8af.png)

**Comment by mazhalai** [comment]
@vesan-83 @jamescowie 
Thank you for reporting, we have created MAGETWO-51451 to investigate and fix.

**Comment by okorshenko** [comment]
@vesan-83  Thank you for reporting the issue. Fix for MAGETWO-51451 merged to develop branch.
