### ISSUE TITLE
Elasticsearch 8 configuration issue with M2.4.7-p3 

### ISSUE THREAD

**Issue by neha023** [magento/magento2#39441]
### Preconditions and environment

- Magento 2.4.7-p3 (CE)
- PHP 8.2 , Elasticsearch 8.11, Mysql 8
- Mode : Developer
- OS - Ubuntu

### Steps to reproduce

Steps : 
1. Install magento 2.4.7-p3 using composer 
2. Disable 2factor auth - php bin/magento module:disable {Magento_AdminAdobeImsTwoFactorAuth,Magento_TwoFactorAuth}
3. Enable developer mode
4. Run all magento commands 
Got error in catalog search index 

![Screenshot from 2024-12-05 14-56-34](https://github.com/user-attachments/assets/37d57cdd-43b7-4566-8dff-03ea3cd0c6a1)

**Check admin configuration but nothing given for elasticsearch8 to be configured**  
![Screenshot from 2024-12-05 14-52-38](https://github.com/user-attachments/assets/9bd86603-3c15-407b-8de1-9d441158f411)

[Screencast from 05-12-24 02:52:21 PM IST.webm](https://github.com/user-attachments/assets/5e4161ca-d2b7-4d97-b6ce-2d7947a93b3f)

### Expected result

1. Admin should show option for elasticsearch8 configuration.
2. Re-indexing should run successfully

### Actual result

The Error I have got on reindexing -
```

Catalog Search index process error during indexation process:
{"error":"no handler found for uri [/magento2_product_1_v2/document/_mapping?include_type_name=true] and method [PUT]"}
```
![Screenshot from 2024-12-05 14-55-23](https://github.com/user-attachments/assets/8d0bf953-4fc8-4a27-a710-edf269864ef2)

And no configuration in admin panel for elasticsearch 8
[Screencast from 05-12-24 02:52:21 PM IST.webm](https://github.com/user-attachments/assets/72a2ebd9-2e2f-49b5-8ced-9b99f72aed93)

### Release note

![Screenshot from 2024-12-05 15-13-51](https://github.com/user-attachments/assets/57699118-d54b-4832-81dd-2c2c19427e6d)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eikzx** [comment]
@neha023 

it looks like you are missing the elasticsearcch 8 module for magento.
You could install it like that:

`composer require magento/module-elasticsearch-8 --with-all-dependencies`

But be aware there is currently an issue with a dependency of ES 8 leading to a not working `magento set:up`
https://github.com/magento/magento2/issues/39438

**Comment by engcom-Bravo** [comment]
@Eikzx Thanks for your Contribution!!.

Hi @neha023,

Thanks for your reporting and collaboration.

Please refer this comment https://github.com/magento/magento2/issues/39441#issuecomment-2519804290 and also this comment https://github.com/magento/magento2/issues/39438#issuecomment-2545644845 fixes the elasticsearch issue.

Hence we are closing this issue.

Thanks.
