### ISSUE TITLE
tinyMCE missing font size selector in v7

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#39440]
### Preconditions and environment

- 2.4.5-p10

### Steps to reproduce

- Open any field with tinyMCE editor activated

### Expected result

- Expect font size selector next to font format (Paragraph, headings)

### Actual result

- Missing font size selector

### Additional information

This is because of update from tinyMCE v5 to v7 in the latest security update. In v6 options got renamed: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#things-we-renamed

I found two places where this is configured:
- `\Magento\PageBuilder\Model\Wysiwyg\DefaultConfigProvider::getConfig`
- https://github.com/magento/magento2/blob/2.4.5-p10/app/code/Magento/Backend/view/adminhtml/templates/widget/form/element.phtml#L101

It should be `fontsize` instead of `fontsizeselect`. Could also have other things that need to be renamed, I just noticed this one.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by PatrickWhitehouse** [comment]
@domeglic there seems to be a patch ACSD-62755 that fixes this issue, however, I have applied this and it doesn't appear to fix it for me on 2.4.5-p10.

**Comment by engcom-Bravo** [comment]
@PatrickWhitehouse  Thanks for your Contribution!!.

Hi @domeglic,

Thanks for your reporting and collaboration.

As per the Magento Release Notes https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/release-notes patch ACSD-62755 fixes the font size issue for tinyMCE 7.


<img width="1430" alt="Screenshot 2024-12-06 at 10 27 45 am" src="https://github.com/user-attachments/assets/8413f839-da41-483d-9315-4fe77f91d222">



Could you please refer the document and let us know if you are still facing any issue.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @domeglic,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Comment by cp3junior** [comment]
Hello,
I am having the same issue.
My version is Adobe Commerce 2.4.5.p10 but this patch version does not exist.

`magento/product-enterprise-edition 2.4.5-p10`

`Magento 2 Enterprise Edition, version 2.4.5.0-patch10
Next patches weren't found: ACSD-62755. Please, check with "status" command availability of these patches for the current Magento version.
Script bash patches/magento-patches.sh handling the post-install-cmd event returned with error code 1`

**Comment by norgeindian** [comment]
@PatrickWhitehouse , the patch only helps with CMS editor. When you're using pagebuilder, it might make sense to check out the latest changes at https://github.com/magento/magento2-page-builder/commits/develop/app/code/Magento/PageBuilder/Model/Wysiwyg/DefaultConfigProvider.php.
I created a patch out of that, which works fine for me:

```
--- a/vendor/magento/module-page-builder/Model/Wysiwyg/DefaultConfigProvider.php	2025-03-21 10:47:03.914385134 +0100
+++ b/vendor/magento/module-page-builder/Model/Wysiwyg/DefaultConfigProvider.php	2025-03-21 10:48:08.785801636 +0100
@@ -42,7 +42,7 @@
         $config->addData(
             [
                 'tinymce' => [
-                    'toolbar' => 'undo redo | styles | fontsizeselect | lineheight | forecolor backcolor ' .
+                    'toolbar' => 'undo redo | styles | fontfamily fontsizeinput | lineheight | forecolor backcolor ' .
                         '| bold italic underline | alignleft aligncenter alignright | numlist bullist ' .
                         '| link image table charmap',
 
```
