### ISSUE TITLE
'Insert Variable' in Hyperlinks

### ISSUE THREAD

**Issue by karlsminton** [magento/magento2#3945]
When creating or editing CMS Pages/Blocks, I use the "base unsecure url" in hyperlinks.
When I save this reopen the Page/Block the hyperlink with the variable disappears, however it works on the frontend. I do all this with the editor hidden.

As a result, every time I try editing any text I have to re-add the links to the text.

If you need any additional information, just let me know

**Comment by piotrekkaminski** [comment]
I was not able to reproduce it.

**Comment by karlsminton** [comment]
This is a poor response.
