### ISSUE TITLE
Category checkbox tree not loading deep nodes

### ISSUE THREAD

**Issue by acankar** [magento/magento2#39468]
### Preconditions and environment

Magento version 2.4.7-p2 (also reproduced in 2.4.7)

This is most likely related to the fact that extjs library was replaced with jsTree

### Steps to reproduce

- Go to Marketing → Promotions → Cart Price Rules
- Create a new rule or edit an existing one
- In the "Conditions" or "Apply the rule only to cart items ..." select the "Category" condition 
- Open the category selector by clicking on the "Open Chooser" button
- Navigate to a category which has subcategories deeper than level 3

### Expected result

The tree should be updated with nested categories like it does in the Catalog → Categories tree selector

![image](https://github.com/user-attachments/assets/45ed2036-0fca-49fe-a3da-c19b886bbbb7)

### Actual result

Nothing happens. I am unable to select categories deeper than level 3

![xdp-cart_rule_category_selector](https://github.com/user-attachments/assets/d1783836-0d13-4b5e-bbb8-d5aecb0020ec)

### Additional information

For now I think I can temporarily resolve the issue by replacing the Magento_Catalog/js/category-tree.js file with the one from Magento 2.4.6

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Yoann-D** [comment]
@acankar , 

The FIX is https://github.com/magento/magento2/issues/39008

**Comment by acankar** [comment]
@Yoann-D thank you sir

**Comment by engcom-Bravo** [comment]
@Yoann-D Thanks for your Contribution!!.

Hi @acankar,

Thanks for your reporting and collaboration.

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12692 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12692&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
