### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by OgreMHDW** [magento/magento2#3946]
On the "Web Setup Wizard" there are two places to sign in:
1) Component Manager - via "Sign In" link. 
2) System Config - via form.

Both forms ask for Public & Private Access Keys which I have generated as per the instructions here:
http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_auth-token.html

When I click "Sign In" button (on Component Manager page) or "Save Config" button (on System Config page) i get a message "Bad Credentials"

I have tried:
a) regenerating keys.
b) generating new keys.
c) generating a new magentocommerce.com account and generating new keys.

I have verified that I am copy/pasting the keys correctly, with no leading/trailing spaces, etc.

At the moment there is a critical update which I cannot update to because the System Upgrade requires a valid login for it to work.

Currently the system upgrade fails to download the file:
https://repo.magento.com/archives/magento/framework/magento-framework-100.0.5.0.zip

This upgrade failure requires a filesystem restore to fix and the installation is broken until the 'vendor/magento/framework' directory is restored.

Suggestions on how to fix the login problem please?

**Comment by Flyingmana** [comment]
can reproduce the problem, old credentials did not work, and generating new ones does also not help.

Needs probably to get fixed on magento site. For having the previous release it may be possible to use packages.magento.com, but thats a deprecated repo as far as I know.

**Comment by alankent** [comment]
Can I get a copy of your keys and email address? Email me direct at akent at magento dot com. We will have a look why they are not working for you.

**Comment by OgreMHDW** [comment]
Alan, I sent you an email with the information requested.

**Comment by OgreMHDW** [comment]
This appears resolved. Was something changed?

**Comment by elenleonova** [comment]
Hi, we have experienced the technical issues, thus, repo.magento.com wasn't available for a while. The problem should be resolved now. If doesn't please let us know by reopening the issue.

**Comment by tomster69** [comment]
I am getting the same issue with a new install of Magento 2.
