### ISSUE TITLE
Magento 2.4.7 p3 Checkout Errors

### ISSUE THREAD

**Issue by reusable8426** [magento/magento2#39474]
### Preconditions and environment

- Magento version 2.4.7 p3
- Firefox browser version 133.0.3
- Macbook
- Stripe used as payment gateway

### Steps to reproduce

1. Navigate to storefront and create an account
2. Add items to your cart
3. Proceed to checkout
4. Attempt to submit payment via Stripe

### Expected result

Customer should go through checkout without errors

### Actual result

Upon navigating to the checkout page, certain customers receive the error messages "The customer does not have an active cart" and subsequently "The order has already been placed and paid." What could be the cause of the issue? Only certain customers face these error messages at checkout, so could it be a user cache issue? If so, how do we resolve it?

We have also had an order be processed successfully via Stripe, but the customer received both of the above error messages and all of our webhooks failed (e.g., no order confirmation emails were sent to the customer, no delivery request was created via our Uber Direct API, etc.). Upon checking the Stripe logs and webhooks, no errors were found.

### Additional information

1. Error occurs for 'active' carts stored after customer logs out and back in
2. Stripe payment intent ID is storing in some cases, which may be one cause of the issue, but we still believe cache may be creating a problem

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @reusable8426,

Thanks for your reporting and collaboration.

Stripe Payment Method that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page.

Thanks.
