### ISSUE TITLE
Magento Custom Module Frontend Request Not Hitting Controller Endpoint (302 Found)

### ISSUE THREAD

**Issue by ghost** [magento/magento2#39477]
### Summary

I'm experiencing a persistent issue with my custom Magento 2 module. I have a frontend form integrated into a chat interface on my site. However, when I submit this form via a POST request, it's unexpectedly redirected to the homepage of my Magento site with a 302 Found response. This redirection prevents my custom controller logic from executing properly.

My goal is to create a message service using the OpenAI API, allowing me to send messages from the chat popup to my PHP code. This would enable me to retrieve products from the Magento website, send that data to ChatGPT, and return the response to the chat message container. Unfortunately, I'm unable to send the message and receive a response from the controller.

you can check it by your self  the responce in console: [https://magento.lahza.ma/ ](url)

The module is enabled, and the chatbot container is appearing, which confirms that the HTML, CSS, and JavaScript are functioning correctly. The only issue seems to be with the PHP code and the AJAX request implementation. I've consulted various AI resources and checked numerous tutorials, but the same issue persists. The Magento 2 website is relatively new and doesn't have any significant background in Magento development. Over the past few days, I've learned how to create a custom module, but I'm struggling to resolve this bug. Any guidance on how to fix this issue would be greatly appreciated. this is the responce. 
![chat phtml](https://github.com/user-attachments/assets/adcb3e54-f6c2-4b05-967d-d9bc245adda0)
![registrations php](https://github.com/user-attachments/assets/b63fe56a-aea2-43c0-a78e-2bd64e9c4174)
![default xml](https://github.com/user-attachments/assets/9c283ae7-cbb7-48e0-aeea-cef4cf5c815f)
![module xml](https://github.com/user-attachments/assets/d1e49c5e-3a5b-4c6c-868d-9b31b5ec2715)
![send php](https://github.com/user-attachments/assets/24edc5a3-054b-4eb0-898d-1f420a9a72c5)
![routes xml](https://github.com/user-attachments/assets/1d113d75-dfe7-4251-8a4d-d8cc63e49863)
![l](https://github.com/user-attachments/assets/6076f816-8256-4fd3-957c-06597b244714)

**Comment by engcom-Hotel** [comment]
Hello @SLdev0,

This forum is used to raise the issues/bugs related to the Magento 2 core library. The issue mentioned in the main description doesn’t seem to us related to Magento 2 core.

We suggest you to raise the issue in [Magento Stackexchange](https://magento.stackexchange.com/). We are closing this issue from here.

Thanks
