### ISSUE TITLE
Magento2 - The shopping cart items counter doesn't display 0 (zero) when there are no items in the cart after upgrade version to 2.0.2

### ISSUE THREAD

**Issue by ragum** [magento/magento2#3948]
after I update magento 2.0.0 to magento 2.0.2, mya shopping cart items counter doesn't display "0" when there's no product/item selected. But if there is an item in shopping cart, the counter is working. No errors found in console and log. 
Anyone can help? (please help me and sorry for the bad english)

**Comment by ishakhsuvarov** [comment]
@ragum Thank you for reporting.
Mini shopping cart is not designed to display "0" by default, only values greater then "0".

**Comment by moax6629** [comment]
@ishakhsuvarov How can we possible change this behaviour? i.e. to display 0 as well.

**Comment by pboisvert** [comment]
Andrii--passing this one to you (though closed) to consider the feature request
