### ISSUE TITLE
Module Uninstall not working

### ISSUE THREAD

**Issue by tony-sar** [magento/magento2#39495]
### Preconditions and environment

Magento 2.4.7 P3 . Ubuntu vps .. clean install 
I installed a module  using Composer , due to some issue , I disabled the module , i used composer remove ( module/name) . but I still have code in Vendor  folder .. 
I used module:uninstall  " MODULE NAME " 
I get the following .. 
removing module name from Database 
removing module name  from module list in deployment configuration . 
removing code from Magento codebase: 

at this stage I have no more activity .. it seems to be hanging here and not removing anything nor out putting any information .. 
this seems to only happen with modules installed using composer . 
Thanks. 

### Steps to reproduce

install module using composer . 
enable module 
upgrade 
disable module 
uninstall using bin/magento module:uninstall 

### Expected result

expected to remove module and code base from magneto 
but i can only disable the module and not remove it 

### Actual result

Disable module only . code remains in vendor/ name /

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
Composer adds and removes packages, you should be able to just do this:
```
composer remove module/name
composer update
```

**Comment by tony-sar** [comment]
Thank you . 
This actually worked. appreciate it ..

**Comment by engcom-Bravo** [comment]
@devchris79 Thanks for your Contribution!!.

Hi @tony-sar,

Thanks for your reporting and collaboration.

Since the issue has been resolved we are closing this issue.Please feel free to reopen the issue if the issue still exists.

Thanks.
