### ISSUE TITLE
RMA Authorize E-mail does not send in Magento EE 2.0.2

### ISSUE THREAD

**Issue by zengliwei** [magento/magento2#3950]
## Steps to reproduce
1. Request return for an order at front-end
2. Edit the return record at back-end, change status of item(s) to `Authorized` and save
## Expected result
1. Customer of the order will receive an Authorize E-mail.
## Actual result
1. No E-mail will be sent.

**Comment by zengliwei** [comment]
Two things cause the issue:
- The model object being used to send E-mail in `\Magento\Rma\Model\Rma\Status\History` is NOT the same one created in `\Magento\Rma\Controller\Adminhtml\Rma::execute`.
- There is a bug in the code of setting `is_send_auth_email` flag in `\Magento\Rma\Model\Rma::_createItemsCollection`

**Comment by zengliwei** [comment]
Solution:

**in `\Magento\Rma\Controller\Adminhtml\Rma\Save::execute`**

find
`$model = $this->_initModel('rma_id');`,

change to
`$model = $this->_objectManager->get( 'Magento\Rma\Api\RmaRepositoryInterface' )->get( $this->_initModel('rma_id')->getEntityId() );`

**in `\Magento\Rma\Model\Rma::_createItemsCollection`**

find
`if ($itemModel->getStatus() === \Magento\Rma\Model\Item\Attribute\Source\Status::STATE_AUTHORIZED
                    && $itemModel->getOrigData(
                        'status'
                    ) !== $itemModel->getStatus()
                ) {`

change to
`if (($itemModel->getStatus() === \Magento\Rma\Model\Item\Attribute\Source\Status::STATE_AUTHORIZED )
                    && ($itemModel->getOrigData(
                        'status'
                    ) !== $itemModel->getStatus())
                ) {`

**Comment by mazhalai** [comment]
@zengliwei PLEASE do not post EE issues here. Please use the partner portal for reporting issues.
