### ISSUE TITLE
Enterprise Edition: Split databse Issue on creating custom attribute for sales resource

### ISSUE THREAD

**Issue by shireenn-mdev** [magento/magento2#3954]
## Steps to reproduce
1. Create a new custom attribute for sales order resource through installer
## Expected result
1. The new attribute should be created in the OMS database
## Actual result
1. The new attribute is created in the main database

**Comment by mazhalai** [comment]
@shireenn2587 PLEASE do not post EE issues on github. To be properly addressed, they should be posted on the partner portal.
