### ISSUE TITLE
Enterprise Edtion : Split database issue for downloadable products orders

### ISSUE THREAD

**Issue by shireenn-mdev** [magento/magento2#3957]
## Steps to reproduce

1.Add downloadable product to cart
2.Place an order containing downloadable product
## Expected result
1. Order should be placed with no fatal errors
2. The product should be listed in my account->my dowloadable products section
3. Shipment, Invoice, Creditmemo or any actions on the order in the admin area should be done successfully
## Actual result
1. Below mentioned error is occurring on placing the order 
   _ PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`demo2`.`downloadable_link_purchased`, CONSTRAINT `DOWNLOADABLE_LINK_PURCHASED_ORDER_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE SET NUL) in /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228_
2. Order is listed in my account->my orders and admin sales order area
3. Error is occurring on performing any actions on the sales order admin area
4. My account->my downloadable products does not show any purchased downloadable products

**Comment by mazhalai** [comment]
@shireenn2587 this is for CE issues only. Please post in the partner portal.
