### ISSUE TITLE
Every readiness check is failing during update attempts

### ISSUE THREAD

**Issue by SudoCat** [magento/magento2#3958]
I am attempting to upgrade my Magento installation, currently version 2.0.2, however it is failing on every single step of the readiness check, which is very odd considering the site is running fine. 

The site is running in a Vagrant VM using VirtualBox on OS X, PHP 5.6, installed using Composer. I can't find any clues in any of my errors logs

![image](https://cloud.githubusercontent.com/assets/5414371/14203224/a1e62808-f7f4-11e5-8bbf-6dbf20099e68.png)
![image](https://cloud.githubusercontent.com/assets/5414371/14203665/581814d6-f7f7-11e5-9f9a-2a4d2a0deac4.png)

**Comment by mazhalai** [comment]
@SudoCat do you have [cron jobs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html) set up as recommended?

**Comment by robfico** [comment]
Seeing the same thing for 2.0.2 version, php and cron checks fail even though cron runs fine from command line, set up in cron, php 5.5.31 installed with intl support, etc...

**Comment by SudoCat** [comment]
I believe my cron jobs were setup correctly - they all seemed to be running as intended from CLI at least. I ended up just reinstalling everything and that seemed to fix it, however it did nothing to solve my confusion!

**Comment by ghost** [comment]
Sorry for seeing this so late. This issue is hard to reproduce. When I see it, I log out of the Admin and manually clear directories under `var` and that fixes it.

**Comment by robfico** [comment]
ok, I found that having one file in the web root that is not writable (like a manual dump file or test file) will stop the readiness checks. Saw this in the var/.update_cronjob_status file

**Comment by mazhalai** [comment]
@SudoCat any update?

**Comment by SudoCat** [comment]
Sorry - as I said, I simply gave up and reinstalled. Seems to be the only way to make anything work in this framework.

**Comment by mazhalai** [comment]
@SudoCat thank you for your update. closing this issue for now, please feel free to open a new issue if you continue to have problems.
