### ISSUE TITLE
Can't upgrade from 2.0.2 to 2.0.4 by the back-end "Web Setup Wizard"

### ISSUE THREAD

**Issue by woei66** [magento/magento2#3961]
## Steps to reproduce
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2 (I installed version 2.0.2)
2. php bin/magento setup:install --base-url=http://load-balancer-domain/ --db-host=mysqldbhost --db-name=dbname --db-user=dbuser --db-password=dbpassword --admin-firstname=Magento --admin-lastname=User --admin-email=admin@email --admin-user=admin --admin-password=adminpassword --language=en_US --currency=USD --timezone=America/Los_Angeles --use-rewrites=1
3. php bin/magento setup:config:set --http-cache-hosts=127.0.0.1:6082 (I installed varnish and it's backend port is 6082)
4. php bin/magento setup:upgrade  ==> pass without error
5. php bin/magento setup:static-content:deploy en_US  ==> pass without error
6. php bin/magento setup:di:compile ==> pass without error
7. php bin/magento indexer:reindex ==> pass without error
8. php bin/magento cache:flush ==> pass without error
9. php bin/magento cache:clean  ==> pass without error
10. varnish listen on port 80 and nginx listen on port 8000
11. I installed on AWS and enable the Load balancer and it will redirect http(80) and https(443) to http(80)
12. I visit the http://load-balancer-domain/admin_url/ and all functions works correctly except the "Web Setup Wizard".
13. I check http://load-balancer-domain/ and all front-end works correctly.
14. Today, I got the upgrade message and try to upgrade my magento 2.0.2 to 2.0.4 but I can't use the "Web Setup Wizard"
15. I tested all functions and links of front-end and back-end and all works correctly except the "Web Setup Wizard"
    Expected result
    --
16. I had read the page http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html
## Actual result

![2016-04-01 19_14_32](https://cloud.githubusercontent.com/assets/5770807/14205498/287b4b7a-f83e-11e5-8f8f-77b2c59d2418.jpg)

Ps. I tried to add " port_in_redirect off;" in nginx but it doesn't work.
Ps. I tried discussion of http://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash but failed.
Ps. I am not sure the problem is caused by nginx+vanrish or magento2 php code?
Ps. Is there a way to upgrade by command line? I can't see any guideline about this.

**Comment by mazhalai** [comment]
@woei66 do you have the recommended [cron scripts](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html) set? 

TO upgrade by command line:
1. `composer require magento/product-community-edition 2.0.4 --no-update`
2. `composer update`
3. Clean cache, and `di` and `generation` folders. 
4. `bin/magento setup:upgrade`

**Comment by ghost** [comment]
Hi @woei66 Working on documentation now. It'll be available soon; I'll let you know. Meanwhile, Maddy's steps should work.

**Comment by woei66** [comment]
@mazhalai 
it works. thank you.
I write down my steps for users who has the same issue:

composer require magento/product-community-edition 2.0.4 --no-update
composer update
rm -rf var/di var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

**Comment by blizam** [comment]
EDIT: Apologies if this is out of place/off topic... I'm inexperienced with GitHub and this was the closest thing I could find...

Trying to upgrade from 2.0.2 to 2.0.4, auth keys in place, cron set up, but my System Upgrade screen just hangs with the Checking for a new version spinner going... so I thought I'd try the CLI listed here.

When I take the above steps I get:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

.... I'm running composer from /update/vendor/composer/composer/bin/

like:

php composer <command>

**Comment by mazhalai** [comment]
@blizam have you set you repository to point to [repo.magento.com](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html)? Also, have you saved the [private and public keys](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html)?

**Comment by blizam** [comment]
/public_html/update/composer.json

has this:

```
"repositories": [
    {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
],
```

And yes, in my backend admin, System > Web Setup Wizard > System Configuration -- I've got my public and private keys to my magento.com account saved

**Comment by mazhalai** [comment]
What about in Magento's root `composer.json` file? not the one in update folder. Also, have you set cronjobs to post to a log as [recommended](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html). Any errors in these logs?

**Comment by blizam** [comment]
there is magic in the air... I think my issue is with my cron settings... after manually running the cron commands I'm now able to proceed in the Web Setup Wizard

**Comment by blizam** [comment]
and yes, the root composer.json has the correct repo URL

**Comment by mazhalai** [comment]
Closing since @woei66 and @blizam 's issues have been resolved. Please feel free to open a new one if issues arise.
