### ISSUE TITLE
jquery/jquery-storageapi.js missing (2.0.3 and 2.0.4)

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#3962]
After fresh installation of Magento 2.0.3 and also 2.0.4 javascripts in frontend do not work.

jquery/jquery-storageapi.js is missing.

http://www.domain.ch/pub/static/_requirejs/frontend/Magento/luma/de_CH/requirejs-config.js
Is there but kind of empty.

I am using PHP 7. 

![error](https://cloud.githubusercontent.com/assets/6672673/14205947/af88b884-f80f-11e5-904e-47e7b5fb93dd.gif)

**Comment by mazhalai** [comment]
@flipflap did you run `bin/magento setup:static-content:deploy`?

**Comment by flipflap** [comment]
Yes, now I am back on Magento 2.0.2 and PHP 5.6 and it works. But I am not sure if the Magento or PHP Version is the reason.

**Comment by piotrekkaminski** [comment]
Closing due to lack of updates.
