### ISSUE TITLE
Upgrade to 2.0.4 with 1100 products loses graphic files

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#3964]
## Steps to reproduce

Add 1100 configurable products with .png product pictures in Magento 2.0.2 and the upgrade to 2.0.3 worked fine, but the upgrade to 2.0.4 does not.

Expected result

Graphics should show up for products
## Actual result

No graphics appear on the new site, missing in both the frontend and backend.

All graphics that were in ./pub/media/catalog/product  are now in  ./pub/media/tmp/catalog/product  and all of the sub-directories of ./pub/media/catalog/product are now in ./pub/media/tmp/catalog/product 

I tried upgrading with the cache cleared and disabled to no avail.  Any troubleshooting ideas would be appreciated.  I will attempt to move the files to the old (before upgrade) structure and see if that helps.

Magento 2 on OpenVZ with multiple cores
Debian 8
PHP Version 5.6.17-0+deb8u1

**Comment by mazhalai** [comment]
@joebusby Have you checked file permissions of `pub/media` folder?

**Comment by joebusby** [comment]
Yes,  permissions are correct before and after the upgrade. (I will double check).  I tried both firefox and chrome also

**Comment by joebusby** [comment]
I have tried several times with correct permissions, and clearing the browser and magento caches.  No good.  It turns out I have 2100 products.  I will see if things work after removing a lot of products and post again.

**Comment by gagaxj** [comment]
I have the same issue with only 5 products.

**Comment by joebusby** [comment]
Reducing the product number did not seem to help.

Upon closer inspection,  only the product images I have added end up in /pub/media/tmp/catalog/product  all the "sample data" products end up in /pub/media/catalog/product  despite that I removed the sample products a while back.  (maybe this is normal)  Removing the product appears to not remove the images associated.  

Should we be able to upgrade from 2.0.2 to 2.0.4 directly? 

Something may have changed with the upgrade process.  I restored an old backup of 2.0.2 and it failed to upgrade to 2.0.3 despite it working the first time I attempted it when 2.0.3 was first released

**Comment by robfico** [comment]
We saw the same issue with an upgrade from 2.0.2 to 2.0.3. Original 2.0 install was with sample data. Sample products and images were originally deleted. After upgrading, all product images were missing.

**Comment by joebusby** [comment]
#robfico that's the problem I have.  I just upgraded anyway, and will re-attach the images on 2100 products one by one since generating > 150 configured products with images does not work.  See you next week. (grin).

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/4054, https://github.com/magento/magento2/issues/3951
