### ISSUE TITLE
Category view shows only 6 random products

### ISSUE THREAD

**Issue by devhn** [magento/magento2#3965]
After upgrading from 2.0.2 to 2.0.4 the category view shows only 6 products, randomly upon each refresh. For example:
- category has 200+ products
- on storefront the list shows only 6 random products after every refresh

I have disabled all the modules, refreshed all caches, disabled flat category and reindexed indexer. This happens on two M2 installations i have.

**Comment by devhn** [comment]
Any news on this?

**Comment by piotrekkaminski** [comment]
@devhn do you still have this issue on latest (2.1RC) version? do you use any custom template?

**Comment by devhn** [comment]
We are currently on 2.0.7 (upgraded few days ago) and can't reproduce this issue any more.
