### ISSUE TITLE
Cart Page asks for login even when user is already logged in(Session is NOT timed out)

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#3966]
## Steps to reproduce
1. Login with default user roni_cost@example.com
2. Add a product to cart
3. Goto cart page
4. Click on Goto Checkout button
5. It will open a login window prompting the user to login again

I refreshed the cart page twice to check whether the session has timed out. But, that was not the case. User was already logged in, session was **NOT** timed out and yet it asked to login again. 

![shopping cart 2016-04-01 17-48-58](https://cloud.githubusercontent.com/assets/11473888/14209930/47ba9fe4-f844-11e5-8ba2-cbe991c74531.png)

I am using PHP 7, Magento 2.0.2 and Ubuntu. I checked this issue on different browsers, setups and operating systems as well, and I am able to reproduce the issue on all of them.

**Comment by mazhalai** [comment]
@parekhreena thank you for reporting, we have created MAGETWO-51460 to investigate and fix.

**Comment by SerhiyShkolyarenko** [comment]
@parekhreena, is it reproducible for you on the latest version? We tried php-7.0.5, ubuntu-15.04, latest Magento CE develop branch and latest sample data, but didn't reproduce this issue.

**Comment by parekhreena** [comment]
@SerhiyShkolyarenko No it is not reproducible in magento 2.0.4.

**Comment by SerhiyShkolyarenko** [comment]
@parekhreena thank you for update.

**Comment by TechScott44401** [comment]
I am having this issue as well, and now on M2.2.2  I have been searching for an answer.  Everything works well, except the final checkout page.  The system just forgets the user is logged in, and multiple attempts must be made.  Eventually, after many reloads, I manage to place my [test] order, but this is totally unacceptable for a real-world customer.  Sometimes the checkout page just hangs indefinitely.  There seems to be very little help available for this.
