### ISSUE TITLE
Sales Order extension_attributes

### ISSUE THREAD

**Issue by jhildreth** [magento/magento2#3967]
There seems to be a problem with extension_attributes on the sales order object, as retrieved by the API. It seems that only one property is able to exist under extension_attributes for the order. I had this problem with some extensions in 2.0.2, but was able to test without any extensions added in 2.0.4.

For example:
1. Place an order, and retrieve it from the API (GET /orders/{order_id}). In 2.0.4, it has "shipping_assignments" under extension_attributes.
2. Place another order, but add a gift message for the entire order (this behavior exists even if you simply add the message to the first order). When you retrieve this order, it only has "gift_message" under extension attributes.

I would expect that both "shipping_assignments" and "gift_message" (as well as anything added by other extensions) would exist as properties under extension_attributes.

**Comment by mazhalai** [comment]
@jhildreth Thank you for reporting, we have created MAGETWO-51791 to investigate and fix.

**Comment by piotrekkaminski** [comment]
This issue is fixed in latest develop branch.
