### ISSUE TITLE
Incorrect price for wishlist item with custom options

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#3968]
## Steps to reproduce
1. magento 2.0.2
2. create bundle product, price fixed (100$), with text paid custom option (+10$)
   ![bundle product without designer with custom option](https://cloud.githubusercontent.com/assets/10142848/14210395/7a177a9c-f831-11e5-82bf-7c59c45a150f.png)
3. create simple product price=123$ with custom option (price=1$) 
   ![simple product without designer](https://cloud.githubusercontent.com/assets/10142848/14210869/ad28603e-f833-11e5-9fc0-d449f46aafc6.png)
4. add both products to wishlist with filled / checked custom options
## Expected result (simple and bundle products)
1. On wishlist index and withlist item configure pages I should see wishlist item with price = base price + custom option's price
## Actual result (bundle product)
1. On wishlist index and configure pages I see base price of bundle product ![my wish list](https://cloud.githubusercontent.com/assets/10142848/14210489/de921900-f831-11e5-8d6e-e13deaa53f9d.png), although custom option's value is saved
## Actual result (simple product)
1. On wishlist index price is correct
   ![my wish list1](https://cloud.githubusercontent.com/assets/10142848/14210783/3b76b5bc-f833-11e5-946d-8f2a0a13df2a.png)
   , but on withlist item configure is not 
   ![simple product without designer1](https://cloud.githubusercontent.com/assets/10142848/14211440/c9c80da4-f836-11e5-87ac-fe904b63b768.png)

**Comment by sevos1984** [comment]
This issue is fixed in develop branch, update your code base please

**Comment by katesuykovskaya** [comment]
thank you!
