### ISSUE TITLE
Sales Order shipping address region_code

### ISSUE THREAD

**Issue by jhildreth** [magento/magento2#3969]
The shipping address returned under extension_attributes on a sales order retrieved via the API in 2.0.4 seems to include the full state name for U.S. states in both the "region" and "region_code" properties.

I expected "region_code" to include the two-character state abbreviation ("VT" instead of "Vermont" for example).

**Comment by piotrekkaminski** [comment]
Internal ID MAGETWO-54153

**Comment by magento-engcom-team** [comment]
@jhildreth, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
