### ISSUE TITLE
NO CSS Magento 2.0.4

### ISSUE THREAD

**Issue by Lreeseg** [magento/magento2#3970]
Just updated to Magento 2.0.4....
My CSS is not loading in either my webpages OR the magento backend. Everything is only shown html.

How do I fix this?

**Comment by mazhalai** [comment]
Try `bin/magento setup:static-content:deploy`

**Comment by Lreeseg** [comment]
This is going to sound stupid.
Is this supposed to be done in a terminal?

On Apr 1, 2016, at 12:17 PM, mazhalai <notifications@github.com<mailto:notifications@github.com>> wrote:

Try bin/magento setup:static-content:deploy

**Comment by mazhalai** [comment]
Yes.

**Comment by chloeefr** [comment]
This command runs fine for me but doesn't change the output on the frontend.

This is how I updated via Composer:

`rm -rf vendor/*`
Edit composer.js file to "version": "2.0.4" , and also under "require".
`composer update`
`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`

No errors in terminal output after this ran, but same on Frontend with no CSS showing.

**Comment by mazhalai** [comment]
@chloeefr did you check your file permissions?

**Comment by chloeefr** [comment]
@mazhalai Checked and all seem correct - any specifics I need to be checking?

**Comment by mazhalai** [comment]
@chloeefr any error on browser console?

**Comment by chloeefr** [comment]
@mazhalai

"Uncaught ReferenceError: Unable to process binding "text: function (){return element.label }"
Message: element is not defined"    .. knockout.js

Have attached system.log

[system-log.txt](https://github.com/magento/magento2/files/200025/system-log.txt)

**Comment by mazhalai** [comment]
@chloeefr that means js files are not loading. Please verify that you have a user as specified [here](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and permissions are as specified [here](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html).

**Comment by mazhalai** [comment]
@chloeefr closing due to non-responsiveness.

**Comment by ghost** [comment]
Same issue on a fresh install, @mazhalai I have tried everything mentioned including setup:static-content:deploy

**Comment by maksek** [comment]
@jupiter01, most likely it is related to permission. We have documentation on devdocs how to install Magento 2.

**Comment by ghost** [comment]
@maksek you are correct, had to fix permissions again after executing setup:static-content:deploy

**Comment by lijithmg** [comment]
@jupiter01 You should run the command setup:static-content:deploy from the user were your websever can execute the files.
