### ISSUE TITLE
SQL error when setting a condition on attribute in Catalog Products List widget if Flat Catalog is enabled

### ISSUE THREAD

**Issue by cedricblondeau** [magento/magento2#3971]
## Steps to reproduce
1. Install Magento from `develop` branch or install a stable Magento version (2.0.2, 2.0.3 or 2.0.4)
2. Enable "Use Flat Catalog Product" in admin (Stores -> Configuration -> Catalog -> Catalog -> Storefront)
3. Create a product with an attribute (e.g. color)
4. Create a new block
5. Insert a "Catalog Products List" widget
6. Set a condition on an atttribute (e.g. color=Red)
7. Associate the static block to a category or a CMS page
   <img width="500" alt="widget" src="https://cloud.githubusercontent.com/assets/1479924/14212543/6f404570-f801-11e5-9cdf-f24d18134ea3.png">
## Actual result

`Error filtering template: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_color.value' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM`catalog_product_flat_1`AS`e`INNER JOIN`catalog_category_product_index`AS`cat_index`ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' INNER JOIN`catalog_product_index_price`AS`price_index`ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`at_color`.`value`, 0) = '5') ))`

<img width="500" alt="result" src="https://cloud.githubusercontent.com/assets/1479924/14212548/76849c14-f801-11e5-8578-8d1000021f4b.png">

**Comment by duhon** [comment]
Hello @cedricblondeau
Thank you for the report! We have created issue in our bugtracker system MAGETWO-54082

**Comment by duhon** [comment]
In version 2.1 the problem is solved
