### ISSUE TITLE
Update to 2.0.4 '@checkout-tooltip-icon__font-size is undefined' error, no custom CSS load

### ISSUE THREAD

**Issue by chloeefr** [magento/magento2#3972]
## Steps to reproduce

Using custom theme with Magento/blank as parent, working fine before recent update.
1. Updated to 2.0.4 using Composer
2. Cleared pub/static/frontend & var folders
3. Grunt watch

Expected result
 --
Custom theme css load ok and continue working.
## Actual result
1. "NameError: variable @checkout-tooltip-icon__font-size is undefined" error appearing twice at top of page. 
2. No styling from custom theme loading.
3. When defining '@checkout-tooltip-icon__font-size is undefined' in _extends.less in blank theme, a different "NameError: variable" shows.

![screen shot 2016-04-01 at 17 02 09](https://cloud.githubusercontent.com/assets/6740224/14212684/f21c0478-f82b-11e5-9729-faab3d1d44d4.png)

**Comment by ktomk** [comment]
IIRC from work, this issue could have happened already in 2.0.2, not 2.0.4 only. I've not checked if there are earlier reports. This is also not limited to CE edition.

**Comment by undefined-olha** [comment]
@chloeefr, thank you for reporting this issue. Internal MAGETWO-52100 ticket has been created.

**Comment by undefined-olha** [comment]
@chloeefr, could you please check if this [folder](https://github.com/magento/magento2/tree/develop/app/design/frontend/Magento/blank/Magento_Checkout/web/css/source) is not overwritten in your custom theme? Especially this this [file](https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less) which contains mentioned variable. Or could you please provide the structure of your project? I cannot reproduce the issue so far.

**Comment by MomotenkoNatalia** [comment]
Closing the issue as it cannot be reproduced and there is no response has been received from the reporter.
@chloeefr  please feel free to reopen if you feel that issue could be reproduced.
