### ISSUE TITLE
css not loading in magento admin...latest magento ce

### ISSUE THREAD

**Issue by hcanning2014** [magento/magento2#3974]
## Steps to reproduce
1. Install Magento from 2.0.4 zip CE to a subfolder 

Expected result
Expecting css to load in site.com/admin

...white page with test only

**Comment by ktomk** [comment]
- Where did you obtain the zip-file from and which checksums does it have?
- Which commands did you run to install from that zip file?
- Which operating system are you using?
- Which webserver are you using?
- Which PHP are you using? 
- How did you verify the install in the first place?

**Comment by hcanning2014** [comment]
Where did you obtain the zip-file from and which checksums does it have?
Magento.com. main download

Which commands did you run to install from that zip file?
Extracted the zip in cPanel file manager then ran setup

Which operating system are you using? Cloudlinux 6.7

Which webserver are you using?
Apache/2.2.31

Which PHP are you using?
5.6.19

How did you verify the install in the first place?
Magneto installed. Admin url had no css just text/links. I had to apply
chmod 777 to adminhtml and subfolders and got some css working. Side links
not working. Issues seem to be folder and file permission based. All
install checks passed. Tried to install multiple zip and tar downloads from
magento.com but same issues.

**Comment by hcanning2014** [comment]
Trying to install to subfolder of that matters. E.g.  mywebsite.com/magento

**Comment by ktomk** [comment]
Sounds like you did not follow the installation instructions. Doing a chmod 777 also signals a misunderstanding on how to make use of file system permissions under *nix.

Please find the step-by-step guide here: [(Easy) Install the Magento archive on your server](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/zip_install.html). This is the method of installation you've chosen (from zip-file). See especially the part about _Set file system ownership and permissions_, it also contains a complete guide and background about the permissions.

**Comment by sshrewz** [comment]
@hcanning2014, can you confirm if @ktomk's suggestion worked for you?

**Comment by issnteacher** [comment]
I tried multiple chmods 700 770 777 and it just became a pain. Stuff just didn't work. Links wouldnt work, css issues. 777 was most successful. Instling was too tedious. May try again in a month or so. Maybe create a screencast of a centos install. Thx

**Comment by piotrekkaminski** [comment]
Not able to reproduce.
