### ISSUE TITLE
 magenta 2 product import won't import images

### ISSUE THREAD

**Issue by justinblayney** [magento/magento2#3975]
Hello,

I am importing products using the built in CSV import (System - import - products)

All my data is imported fine, but i get an error
"Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in rows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10"

in my css I have written the base_image path as 
http://mywebsite.ca/pub/media/import/img/hose/jpg/Ach7938.jpg

as a test I removed my folder structure, edited the csv and tried this and got same problem, same error
http://mywebsite.ca/pub/media/import/Ach7938.jpg

I tried writing file path as so
/pub/media/import/img/hose/jpg/Ach7938.jpg

but it won't let me past the "check data" validator.

I confirmed the permissions on the folders and files is 775

I am using php 5.6, i tried 7 but it broke the whole site in many different ways, so that isn't an option

As a side note, if I run this 20 times in a row, the entire site hangs and import won't work again until I do a full system restore (whats up with that?)

Can I put the images on a different server and link to them that way?

**Comment by ktomk** [comment]
@justinblayney: Could you please elaborate which part of the error message is incomprehensible to you? I mean you write pretty much about this and that but I don't see in your analysis how that is related to HTTP connection timeouts or HTTP errors (which the error message is clearly about).

The URL you provide btw. is causing a redirect. to a non-image resource. Please check your report. If you need example URLs take the reserved domain names to create them: http://www.iana.org/domains/reserved

Are you able to obtain the requests and their response codes from your webservers access log? That should shed some light.

**Comment by piotrekkaminski** [comment]
Closing due to lack of response.
