### ISSUE TITLE
shipping address from SalesDataOrderInterface 2.0.4 ?

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#3979]
following with the shipping address not coming back for orders when calling SOAP api when 2.0.2

i'm still unable to get the shipping address after updating to 2.0.4

i still only get billing/quote addresses, using SOAP salesOrderRepositoryV1

**Comment by owenhaynes** [comment]
Shipment info is in the extension_attributes as shipping_assignments in the JSON api

**Comment by piotrekkaminski** [comment]
@mbrinton01 ? this question is a better fit for magento.stackexchange.com
