### ISSUE TITLE
2.0.4 - .Net soap endpoint references limit?

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#3981]
hi guys

i'm trying to use the following modules and and just trying to login

integrationAdminTokenServiceV1,
storeStoreRepositoryV1,
customerCustomerRepositoryV1,
salesOrderRepositoryV1,salesOrderManagementV1,
salesInvoiceRepositoryV1,
salesInvoiceCommentRepositoryV1,
salesCreditmemoRepositoryV1,
salesCreditmemoCommentRepositoryV1,
catalogInventoryStockRegistryV1,
catalogProductRepositoryV1

`<?xml version="1.0"?>
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <integrationAdminTokenServiceV1CreateAdminAccessTokenRequest xmlns="http://localhost:8085/magento2/soap/default?services=integrationAdminTokenServiceV1%2CstoreStoreRepositoryV1%2CcustomerCustomerRepositoryV1%2CsalesOrderRepositoryV1%2CsalesOrderManagementV1%2CsalesInvoiceRepositoryV1%2CsalesInvoiceCommentRepositoryV1%2CsalesCreditmemoRepositoryV1%2CsalesCreditmemoCommentRepositoryV1%2CcatalogInventoryStockRegistryV1%2CcatalogProductRepositoryV1">
      <username xmlns="">some-user</username>
      <password xmlns="">pw@1234</password>
    </integrationAdminTokenServiceV1CreateAdminAccessTokenRequest>
  </s:Body>
</s:Envelope>`

this is the return

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>WSDL</faultcode>
      <faultstring>SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://localhost:8085/magento2/soap/default?services=integrationAdminTokenServiceV1%2CstoreStoreRepositoryV1%2CcustomerCustomerRepositoryV1%2CsalesOrderRepositoryV1%2CsalesOrderManagementV1%2CsalesInvoiceRepositoryV1%2CsalesInvoiceCommentRepositoryV1%2CsalesCreditmemoRepositoryV1%2CsalesCreditmemoCommentRepositoryV1%2CcatalogInventoryStockRegistryV1%2CcatalogProductRepositoryV1&amp;wsdl=1' : Extra content at the end of the document
</faultstring>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

but when i take any 1 modules out say... catalogProductRepositoryV1 it works and i could get a token

so the question is, should there be a limit of references we could have in the url endpoint?

**Comment by ktomk** [comment]
An _"Extra content at the end of document"_ signals a parse-error of **DOMDocument** in PHP. It just means that after the document element of the XML document (the WSDL is such one) there is more data (but it should not).

You should be able to verify that by doing a HTTP GET request of the [WSDL-URI](http://localhost:8085/magento2/soap/default?services=integrationAdminTokenServiceV1%2CstoreStoreRepositoryV1%2CcustomerCustomerRepositoryV1%2CsalesOrderRepositoryV1%2CsalesOrderManagementV1%2CsalesInvoiceRepositoryV1%2CsalesInvoiceCommentRepositoryV1%2CsalesCreditmemoRepositoryV1%2CsalesCreditmemoCommentRepositoryV1%2CcatalogInventoryStockRegistryV1%2CcatalogProductRepositoryV1&wsdl=1) and inspect the response body at the according end-position of the XML document. That extra-content normally sheds some light on what happens (e.g. an error message or some other non-intended output).

**Comment by piotrekkaminski** [comment]
This problem is a better fit for magento.stackexchange.com
