### ISSUE TITLE
jquery.js:248 Uncaught Error: no such method 'activeAnchor' for tabs widget instance

### ISSUE THREAD

**Issue by shuaiZend** [magento/magento2#3982]
## Steps to reproduce
1. Composer update Magento 2.0.2 to 2.0.4.
2. click Add subcategory.
3. can' save

and Display:
jquery.js:248 Uncaught Error: no such method 'activeAnchor' for tabs widget instance

**Comment by piotrekkaminski** [comment]
unable to reproduce in 2.1RC1
