### ISSUE TITLE
admin view

### ISSUE THREAD

**Issue by nestocabrera** [magento/magento2#3985]
i have installed magento CE 2.0.4 + sample data, and the view of the admin, doesn't load well i attach an image of what is happening
![erroradminmagento](https://cloud.githubusercontent.com/assets/16739464/14230920/da5de092-f932-11e5-9f09-9306d168deca.png)

**Comment by daim2k5** [comment]
@nestocabrera please check your file permission and make sure you are following the magento installation guide (http://devdocs.magento.com/)

**Comment by ayanni** [comment]
Hi, i have the same problem, any help?

**Comment by nestocabrera** [comment]
thanks @daim2k5 i was reading the installation guide, and it says that it can happen, but the solution offered is to enable teh server rewrite module, but the path of the files is from ubuntu  or centos installation, any clue how can i solve the issue in windows?

**Comment by daim2k5** [comment]
@nestocabrera unfortunately no because i don't use windows. Also i'm not sure if magento 2 official support windows

**Comment by daim2k5** [comment]
Did you run `bin/magento setup:static-content:deploy` ?

**Comment by nestocabrera** [comment]
yes and it don't recognize as and intern or extern comand

**Comment by bh-ref** [comment]
@nestocabrera the command begins with "php" --> `php bin/magento setup:static-content:deploy` or `php.exe bin/magento setup:static-content:deploy`

It is using the php cli tool.

**Comment by mazhalai** [comment]
@nestocabrera any update?

**Comment by piotrekkaminski** [comment]
Closing due to lack of updates.
