### ISSUE TITLE
A custom CMS page to display when site is in maintenance mode(feature request)

### ISSUE THREAD

**Issue by tiwarimukesh** [magento/magento2#3987]
Can we have an option in Magento admin so that when a site is in  maintenance mode customers should see a CMS page which can be easily customized in Magento admin.

So the site owners have a flexibility to show the customized page with custom messages to the customers.

**Comment by ktomk** [comment]
@tiwarimukesh: This is already available as extension:
- [Magento 2.0 Custom Maintenance Mode Extensio](http://www.customerparadigm.com/magento-2-0-custom-maintenance-mode-extension-free/) 0$ CE/EE
- [Magento 2 Custom Maintenance Page](http://creatuity.com/magento/custom-maintenance-page-magento2.html) for 99$ CE / 299$ EE.

These should provide you an option similar to what you're asking for (I'm not affiliated with any of these).

In case you wonder how I found out about this, here is the [link to Magento Connect for Magento 2 extensions](https://www.magentocommerce.com/magento-connect/magento-2).

**Comment by tiwarimukesh** [comment]
@ktomk  I know that extensions exist for this feature but I it can be a part of magento core.It will also be helpful.

If this request seems not a good, it can be closed by Magento team.

**Comment by ktomk** [comment]
I'm sure PR's for this are welcome - at least to decide about that.

**Comment by tkacheva** [comment]
Thanks @ktomk  for the idea!
will do this in the scope of CMS update - MAGETWO-51644

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/A-custom-CMS-page-to-display-when-site-is-in-maintenance-mode/idi-p/46045).

**Comment by orlangur** [comment]
> when a site is in maintenance mode customers should see a CMS page which can be easily customized in Magento admin

Page for maintenance mode must be independent from Magento itself, so, we would have to save such CMS page into filesystem which is not good.
