### ISSUE TITLE
Bump of Copyright Year

### ISSUE THREAD

**Issue by ktomk** [magento/magento2#3988]
I've just compared 2.0.3 and 2.0.4 and it came to my attention that in files without noteworthy copyright  changes (newline at the end of file was missing - if any change at all) the year of last release has been bumped without actually having changes (and a release).

Could you please verify with your legal department that you're absolutely sure to change the copyright year without actual changes of the work?

From a developers perspective it for sure would be helpful as well to _not_ have needless changes in the headers of each file only because new year's eve has passed. Change in year does not introduce changes to the work nor does it affect copyright automatically.

**Comment by sshrewz** [comment]
Thanks for raising this question, @ktomk.  To confirm, the copyright changes have been verified with our Legal Department.

**Comment by ktomk** [comment]
@snohe; That's great to hear, but I can hardly imagine your legal department suggested to bump the copyright year w/o further modifications of the file.

In any case, and for me much more interesting, is, if you would consider the suggestion to not change each file as this causes erosion with the files and bloats the version history. Unfortunately you have not left any comment about that aspect albeit in my issue it's the major part. I'm a software developer so I'm more interested about the code than the legal side (which is interesting, too!).

**Comment by alankent** [comment]
(I am not sure, so should probably keep my mouth shut, but I could well imagine there are automated scripts involved so a single character change triggers a new release, which triggers a new copyright version number. E.g. I found a number of modules that had the copyright symbol broken (bad UTF-8 encoding), so to make things safe legally it was fixed.)  But yes I understand the pain.

**Comment by ktomk** [comment]
Hi Alan, well then hopefully it's possible to conclude that this shouldn't be necessary. Btw copyright year is the one of first release. Last time I checked, that was 2015 for Magento 2 :) . Good herding for the scripts and have fun with the Hackathon in Vegas.

**Comment by alankent** [comment]
This is where you ask lawyers and they give an opinion. Each module is downloadable separately ("distributed" separately) so needs an independent copyright notice (and date). Each patch is a new "release" and so we bump the number. I am not a lawyer, but no point paying them for an opinion and then not following it. ;-)

But we definitely should avoid unnecessary little changes in patch branches to avoid the pain here.

**Comment by ktomk** [comment]
Oh, I was not speaking against the notice in itself. Not at all. But bumping the year only because of a new release is most often done in mistake from what I've seen over the years. And I should as well not talking that much, but we normally pay lawyers not for one but for more than one opinion (: .

And great to see you in avoidance of unnecessary code erosion. Thank your for your support!
