### ISSUE TITLE
Magento 2 css not loading.

### ISSUE THREAD

**Issue by amitbala** [magento/magento2#3989]
Magento 2 is not loading properly, after fresh installation on server,
![11](https://cloud.githubusercontent.com/assets/16007533/14232817/e768a6ea-f9d3-11e5-9055-1a6ed715394d.PNG)

![12](https://cloud.githubusercontent.com/assets/16007533/14232818/ebef590c-f9d3-11e5-862a-706ffdb567ca.PNG)

**Comment by mazhalai** [comment]
@amitbala did you run `bin/magento setup:static-content:deploy`

**Comment by Richardmaximun** [comment]
]I have the same issue for backend/frontend

I did the @mazhalai suggestion but nothing happen .

You found a solution @amitbala?

Any other suggestion?

Regards

**Comment by naveenabt** [comment]
Hi,

I am also facing same issue.
And i have executed "bin/magento setup:static-content:deploy" command but issue not solved.

Thanks,

**Comment by naveenabt** [comment]
Backend:
static/adminhtml/Magento/backend/en_US/css/styles.css

Css will not load if above file not loading or not generated properly using "bin/magento setup:static-content:deploy" command.
If user and group are different it will not generate properly.
Make sure the group and user should be  "www-data"

**Comment by piotrekkaminski** [comment]
Closing as a permission issue. Permissions were update in 2.1.

**Comment by suman2061** [comment]
i am also facing same issue. 
same website work perfectly on localhost, but on server, it facing this css issue.
how to solve this???

**Comment by DanielRuf** [comment]
> i am also facing same issue.

This was about an old release. Please open a new issue and provide all details about your setup and steps.
