### ISSUE TITLE
Checkbox works incorrect for Store Credit extension

### ISSUE THREAD

**Issue by AndreyChorniy** [magento/magento2#3990]
## **Steps to reproduce**
1. Install Magento Enterprise
2. Try to update store credit balance via admin panel with email notification. 
   I get new balance. Good. But I cannot get email notification
   This checkbox doesn't work correct 
   [ https://drive.google.com/file/d/0B2vGZI5KgHsdS1l5ejBPbWVBeVE/ ]
## **Expected result**
1. Email notifications after balance update, need to be sent
## **Actual result**
1. I want to save customer information after change. I don't get email with updated balance for Store Credit when checkbox is "checked " https://drive.google.com/file/d/0B2vGZI5KgHsdYlFqM25oRllGTGM/

Please advise. Thanks.

**Comment by AndreyChorniy** [comment]
I have change "checkbox" to "select,  'yes' & 'no' " and this works  well for me. Email has been sent. But this email is empty :( And I see the next Error in admin panel https://drive.google.com/file/d/0B2vGZI5KgHsdaWRob3Zsc2hYTDQ/

Please advise. 
Thanks.

**Comment by AndreyChorniy** [comment]
Hey guys. 
Any news about it ?

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-51660

**Comment by slavvka** [comment]
Hi @AndreyChorniy, the issue has been fixed and delivered to mainline. Please see ec2d3f3.

**Comment by slavvka** [comment]
@AndreyChorniy the bug has been fixed and delivered. Please see ec2d3f3 or contact Magento Support to get a patch

**Comment by AndreyChorniy** [comment]
@slavvka 
Thank you so much.
