### ISSUE TITLE
Magento 2.0.4 Server 500 error in production mode in php 7.0.5

### ISSUE THREAD

**Issue by sabei** [magento/magento2#3991]
Magento 2.0.4 Server 500 error in production mode in php 7.0.5

nginx -v

``` bash
nginx version: nginx/1.9.13
```

php -v

``` bash
PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Switch to the mode of production

```
bin/magento deploy:mode:set production
```

When I run the command

``` bash
bin/magento deploy:mode:show
```

Results returned

``` bash
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface in /var/www/magento204/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
Stack trace:
#0 /var/www/magento204/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /var/www/magento204/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /var/www/magento204/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'filesystem', 'Magento\\Framewo...')
#3 /var/www/magento204/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#4 /var/www/magento204/vendo in /var/www/magento204/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

```

**Comment by jissereitsma** [comment]
I found this issue via google, don't have the same issue but am able to find the following: The `DriverInterface` would need a DI preference to be mapped to a real class (`Driver`). However, my own Magento 2.0.4 system does not have this preference defined, except for a dynamic mapping as part of the setup. My 50 cents.

**Comment by sabei** [comment]
Give you 50 cents :)

I'm sorry for my English.

In the "default mode" and "developer mode", everything is OK.

Only "production mode", all magento command is not available, the front-end returns a 500 error.

This problem occurs after the latest updated version of php 7.0.5/magento2.04, I have tested in the local environment and Vps environment. (Ubuntu14, nginx1.9, php7.0.5, mysql5.6, varnish)

**Comment by sabei** [comment]
I think this is a question about php 7, not a bug of magento2.

When I switch back to use php5.5, all work well. Please close this question, thank you!

**Comment by jlee-sazze** [comment]
I'm having the same issue. If I clear `var/di` directory, it works fine in production mode set.

**Comment by janghwan** [comment]
I think this issue is still valid because magento 2 is officially support php 7.

**Comment by MicroKloon** [comment]
ofcourse this is still valid, if Magento 2 supports php 7 it should work....

**Comment by daim2k5** [comment]
so i reopen the issue because @janghwan and @MicroKloon maybe can add more details?

**Comment by MicroKloon** [comment]
@daim2k5 Since I am in production I switched back to php 5.6
Sorry I can not help any further,

ps: I am a refuge from Prestashop and I am pleasantly surprised by the professialisme here. Ps tends to not care about bug-reports (and their open-source users)
Nice to know Magento does care about her users.

**Comment by patadeloso** [comment]
Hello,

We are seeing this same issue with Magento 2.0.4 and php 7.0.5. Web install breaks at around 70-78% but CLI installer works. Looks like DI compiler breaks.

**Comment by lazyguru** [comment]
This isn't a bug in Magento.  It's an issue in PHP 7.0.5:  https://bugs.php.net/bug.php?id=71914  Solution is to either downgrade to 7.0.4 or upgrade to 7.0.6

**Comment by patadeloso** [comment]
Sorry, I've been meaning to update this. Can confirm that DI compiler works on CentOS 6 with php 7.0.5-2 and Debian 8 with php 7.0.4 (looks like 7.0.6 was just released on dotdeb).

**Comment by piotrekkaminski** [comment]
Confirmed issue with 7.0.5.
