### ISSUE TITLE
Unable to select Product template attribute set for configurable products

### ISSUE THREAD

**Issue by pansys** [magento/magento2#3992]
Hello-

Installed Magento 2.0.4 today and while adding configurable product to catalog product template selection is disabled. Please find the screen shot attached.
![1](https://cloud.githubusercontent.com/assets/6678621/14246505/34d824e4-fa85-11e5-8325-a224a31d7b10.jpg)

Thanks,
Mathew

**Comment by duhon** [comment]
This is the expected result for the specified version. Unlock happens after you create the simple products for this configurable product. The current version already has the behavior you expected.
