### ISSUE TITLE
2.0.4 customer registration login issue

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#3994]
## Steps to reproduce

Hi,

In the latest version 2.0.4 after creating a customer, the customer is not logged and cannot log in with the credentials anymore. No error message is displayed. Is this a problem of the new release? on previous versions this was working?

Thanks,
Szabi

**Comment by ksz2013** [comment]
On previous versions this worked properly.

**Comment by hshar7** [comment]
@ksz2013 This could potentially be a big problem. Could you please provide more information? Did you clear cache and run
$bin/magento setup:upgrade
 and updatedb ?

**Comment by ksz2013** [comment]
Hi,

Issue is related to browser cache and cookie, It can be closed.
