### ISSUE TITLE
REST: /rest/V1/orders doesn't return orders from multiple store ids

### ISSUE THREAD

**Issue by Bbbrinks** [magento/magento2#3996]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a second store view
3. Place X orders on the default store view
4. Request  `/rest/V1/orders?searchCriteria[pageSize]=1&searchCriteria[currentPage]=2&searchCriteria[filterGroups][0][filters][0][value]=1&searchCriteria[filterGroups][0][filters][0][field]=store_id&searchCriteria[filterGroups][0][filters][0][conditionType]=eq&searchCriteria[filterGroups][0][filters][1][value]=2&searchCriteria[filterGroups][0][filters][1][field]=store_id&searchCriteria[filterGroups][0][filters][1][conditionType]=eq`
## Expected result
1. All orders from the default store view (and the second store view as well).
## Actual result
1. Empty result:

```
{
  "items": [],
  "search_criteria": null,
  "total_count": 0
}
```
## Aditional info:

When removing the second store id filter the default store id orders are returned

**Comment by mazhalai** [comment]
@sterfpaul thank you, we have created MAGETWO-51500 to investigate and fix.

**Comment by Bbbrinks** [comment]
I found a work around by using the condition type "in" and posting both ids in one filter.

`/rest/V1/orders?searchCriteria[pageSize]=10&searchCriteria[currentPage]=2&searchCriteria[filterGroups][0][filters][0][value]=1,2&searchCriteria[filterGroups][0][filters][0][field]=store_id&searchCriteria[filterGroups][0][filters][0][conditionType]=in`

**Comment by hshar7** [comment]
@sterfpaul why do you consider this to be a workaround? Is "in" not the correct conditionType?

**Comment by Bbbrinks** [comment]
@hshar7 Yeah that's true. But I still expected the other way to work as well so that might be a bug? Or is it documented that you can only have on filter per field(name) in a filtergroup.

**Comment by paliarush** [comment]
@sterfpaul Please provide more details on how to reproduce the issue. I was unable to reproduce it on the latest `develop` code base when followed these steps:
- Created second store view
- Created 2 orders in default store view, 1 order in new store view
- Copied request URL from your post, added base URL
- Added Authentication headers
- Performed request, everything works as expected
- When change one of store_id in the filter to not existing value - only values from the existing store are returned

**Comment by Bbbrinks** [comment]
@paliarush What REST request are you running?  Using an "in" or "eq" requests

**Comment by paliarush** [comment]
@sterfpaul "eq" one, that is specified in your original post.
