### ISSUE TITLE
Display "Friendly" Identifiers in Admin Panel

### ISSUE THREAD

**Issue by rtull** [magento/magento2#3998]
In the "rules" interfaces in the admin panel (see Customer Segments or Promotions) selected objects show their ID, not a friendly name. This makes it very difficult in the admin to assess what values have been selected in a rules section because the IDs shown are not comprehend-able. Without loading the full selection list / grid interface, an admin user has no idea which specific items they have selected.

For example, selecting a particular category as a filter criteria show the category ID, not the category name. An admin user would have no idea which category this is without loading the category selector - which both time-consuming and non-obvious.

Recommend displaying admin text values instead of IDs to improve human administrator comprehension and admin speed of use.

Example Screenshot: [http://files.classyllama.com/c689cb8e/mage2_admin_id.png](http://files.classyllama.com/c689cb8e/mage2_admin_id.png)

**Comment by hshar7** [comment]
Internal MAGETWO-51511 created to track this. Thanks, @rtull

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Display-quot-Friendly-quot-Identifiers-in-Admin-Panel/idi-p/46899).
