### ISSUE TITLE
When the "region" is not saved after editing shipping/billing address

### ISSUE THREAD

**Issue by DonatelloNguyen** [magento/magento2#4000]
Environment:
Installed through composer.
Magento ver. 2.0.2
## Steps to reproduce

1.) Create an order. (note you should see your state in the DB or in the order page)
2.) Edit shipping address
3.) Click save
4.) Look at the database "mage_sales_order_address" or look at the order page.

Expected:
see the state

Actual:
NULL in database and the state is missing in the order page.

Side Note: 
Whenever I edit the billing Address again, it's prepopulated the state correctly.  I'm not sure where it is getting the value from but it's not directly from the database b/c the value is NULL

**Comment by sshrewz** [comment]
Thanks for submitting this issue.  We have created MAGETWO-51582 for internal tracking.

**Comment by piotrekkaminski** [comment]
The issue will soon be merged to the repository.

**Comment by olysenko** [comment]
fixed in MAGETWO-51582

**Comment by NadiyaS** [comment]
Hi,
fix was delivered to develop branch. Issue is closed as fixed. Feel free to reopen it if you still have the same problem

**Comment by Ctucker9233** [comment]
@NadiyaS is this fix safe for a 2.1.2 version in production mode with a live site?
