### ISSUE TITLE
Fatal Error on magento/setup

### ISSUE THREAD

**Issue by DonatelloNguyen** [magento/magento2#4001]
I get an exception when trying to access the setup page.  There's another folk who experience this same problem Janurary but there's no response.

https://community.magento.com/t5/Technical-Issues/Fatal-error-magento-setup/m-p/26444#M335

ENV:
installed from composer
v2.02
## Steps to reproduce
1. Go to System >> Web Setup Wizard

Expected:
Working Page

Actual: 
Exception Page

Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /opt/lampp/htdocs/magento/vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132' in /opt/lampp/htdocs/magento/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /opt/lampp/htdocs/magento/vendor/magento/framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/opt/lampp/htdo...', 132, Array) #1 /opt/lampp/htdocs/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(84): Magento\Framework\ObjectManager\Config\Compiled->extend(Array) #2 /opt/lampp/htdocs/magento/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\ObjectManager\ObjectManager->configure(Array) #3 /opt/lampp/htdocs/magento/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): Magento\Setup\Model\ObjectManagerProvider->get() #4 [internal function]: Magento\Setup\Mvc\Bootstrap\InitParamListener->authPreDispatch(Object(Zend\Mvc\ in /opt/lampp/htdocs/magento/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by mazhalai** [comment]
@DonatelloNguyen We are having trouble reproducing this, can you please give us more details? What is your OS? How did you install M2? via web or via CLI? Is it in production mode or developer mode? etc.

**Comment by mazhalai** [comment]
@DonatelloNguyen closing since there has been no response.
