### ISSUE TITLE
iconv extension required in PHP 7

### ISSUE THREAD

**Issue by blizam** [magento/magento2#4002]
This page:

http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html

Should reference that in PHP 7 the iconv extension needs to be installed. I'm unsure if it's just defaulted in previous PHP versions but when I switched to PHP 7 recently I had to install the iconv extension for it separately in order for Magento 2 to function

**Comment by mazhalai** [comment]
@blizam Thank you for reporting, but how did you realize that `iconv` is required? did something break without it?

**Comment by blizam** [comment]
Yeah... I wished I'd saved the error...

It was something like:

Undefined constant ICONV_IMPL in /vendor/magento/framework/Stdlib/StringUtils.php on Line 160

**Comment by mazhalai** [comment]
@blizam thank you, we have created MAGETWO-51641 to fix this issue.

**Comment by mazhalai** [comment]
@blizam Did you deploy Magento via a zip from magento.com?

**Comment by blizam** [comment]
Yes

**Comment by mazhalai** [comment]
@blizam thanks for confirming. In that case, MAGETWO-51369 has already fixed this issue.  Documentation will be fixed in MAGETWO-51641

**Comment by mazhalai** [comment]
@blizam both issues have been addressed, hence closing this issue. Thank you for reporting this issue.
