### ISSUE TITLE
Status history items with same date/time

### ISSUE THREAD

**Issue by sengaigibon** [magento/magento2#4003]
## Steps to reproduce
1. Go to Backend, Sales -> Orders -> Click on an Order.
2. At the bottom, in "Order Total"/"Notes for this Order", add at least one comment.
## Expected result
1. A list of comments in the history with different date and time, according to creation time.
## Actual result
1. Same date and time on each comment added. 
2. In fact, if you reload the page you'll notice that the date and time of each comment is the current one.
## Notes

If you look at the table `sales_order_status_history`, the `created_at` field shows the right datetime.
## Suggested solution

The function `getCreatedAtDate()` does not exist but is called here:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/templates/order/view/history.phtml#L75  and next line.
Changing it for `getCreatedAt()` solves this issue.

Also, there are a couple of calls of same function here:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/templates/order/comments/view.phtml

**Comment by quienti** [comment]
Duplicate : https://github.com/magento/magento2/issues/3614 and https://github.com/magento/magento2/issues/3383
Pull request : https://github.com/magento/magento2/pull/3629

**Comment by NadiyaS** [comment]
Hi @sengaigibon ,
thank you for reporting this issue.
This bug is already fixed in develop branch [87f27af](https://github.com/magento/magento2/commit/87f27afb8e581f47292303ac16c4685ca12e7f14).
Please update your code from develop branch or wait until next release.
