### ISSUE TITLE
Newsletter Subscriber create-date not set, and change_status_at broken

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#4004]
## Steps to reproduce
1. Register a newsletter subscriber via the front-end, with no confirmation of email address needed.
2. Check database.
3. Unsubscribe user via admin interface.
4. Resubscribe user via admin interfa... oh wait, this option is missing. If you make a mistake (no confirmation dialog) you can't correct it without going into the DB.
## Expected result
1. After creation set change_status_at to creation date (confirmation of email if enabled, or just registration time if no confirmation email is sent).
2. change_status_at is set to when user is subscribed.
3. Expect change_status_at to contain the date of the status change.
## Actual result
1. I want to sync new newsletter subscribers, so I expect a datetime to filter on, to get new newsletter subscribers. This is not set.
2. change_status_at is null. It would be nice if this were initialized to the registration date.
3. User is unsubscribed, status 3, but change_status_at remains null. Integration can't detect user is unsubscribed now.

**Comment by fvschie** [comment]
Any update?

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54128

**Comment by fvschie** [comment]
Hi, what's the status on this story?

**Comment by fvschie** [comment]
And now? :-)

**Comment by fvschie** [comment]
How's about now?

**Comment by schizek** [comment]
What's the status on this?

**Comment by PaulBoss** [comment]
So, again, is there an update?

**Comment by magento-engcom-team** [comment]
@fvschie, thank you for your report.
We've created internal ticket(s) MAGETWO-54128 to track progress on the issue.

**Comment by nemesis-back** [comment]
I will work on it #SQUASHTOBERFEST 2017

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @fvschie. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by fvschie** [comment]
Awesome, I am glad to hear it! Thanks a lot. (Any chance of a backport to 2.1.x?)
