### ISSUE TITLE
Rest API for querying and updating Newsletter Subscribers missing

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#4005]
There is no API for getting or setting newsletter subscription status. Such an API is necessary for integration with third-party systems, specifically mailing platforms.

This needs to be separate from customer API of course, although adding newsletter subscription status to Customers would be a welcome addition too.

**Comment by piotrekkaminski** [comment]
@choukalos feature request for you

**Comment by qwerty7869** [comment]
Did anyone had created newsletter rest api?

**Comment by fvschie** [comment]
Hi, what's the status on this story?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-API-for-querying-and-updating-Newsletter-Subscribers/idi-p/44735).
