### ISSUE TITLE
When saving configurable products while iterating a collection, dropdown-values get saved incorrect

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#4006]
## Steps to reproduce:

Create a product collection, select no attributes, iterate and save:

```
$collection = $this->collectionFactory->create();
$collection->addFieldToFilter('type_id', array('eq' => 'configurable'));
foreach ($collection as $product) {
    $product->save();
}
```
## Expected result

That the products' dropdown values (manufacturer, color, etc) are not changed.
## Actual result

The products' dropdown values get set (or lost?) to the first value in the dropdown
## Workaround

Include all attributes when loading the collection:

```
$collection = $this->collectionFactory->create();
$collection->addFieldToFilter('type_id', array('eq' => 'configurable'));
$collection->addAttributeToSelect('*');
foreach ($collection as $product) {
    $product->save();
}
```

This only seem to happen for configurable products.

**Comment by mslabko** [comment]
hi @kanduvisla ,
It's better to use API  for save product. Please, check \Magento\Catalog\Api\ProductRepositoryInterface::save 

According to problem with save product via iteration - we will investigate it and create issue

**Comment by duhon** [comment]
Hello @kanduvisla

I couldn't reproduce the problem on current version. 
Tried steps:
- I created a product configuration with the attribute of manufactory
- launched the above code
- opened the created product on the edit

Please clarify steps to reproduce, version and installed extensions

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
