### ISSUE TITLE
Problem in Override theme layouts 

### ISSUE THREAD

**Issue by karishmadaffodil** [magento/magento2#4008]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by karishmadaffodil** [comment]
I am facing problem while overriding theme layout.
I want to override this file "vendor/magento/theme-frontend-blank/Magento_Checkout/layout/checkout_index_index.xml".
I created my theme and copied the file in following directory in my theme : "app/design/frontend/Magento/Mytheme/Magento_Checkout/layout/override/theme/Magento/Blank/checkout_index_index.xml".
I am following this tutorial : 
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-override.html
But it is rendering content from base theme not from my theme.

**Comment by piotrekkaminski** [comment]
@karishmadaffodil this question is better suited for magento.stackexchange.com. Github is for bug reports and contributions.
