### ISSUE TITLE
Currency format inconsistent

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4009]
I have the issue with currency format. First, in order to configure my currency to have no decimal numbers, I have modified 3 files in /vendor/magento/zendframework1/library/Zend/Locale/Data: es.xml, es_ES.xml and es_CL.xml (the latter just in case, because locale set is es_ES)

In es.xml I have:
               `<currencyFormats numberSystem="latn">
                        <currencyFormatLength>
                                <currencyFormat type="standard">
                                        <pattern>¤ #,##0</pattern>
                                </currencyFormat>
                                <currencyFormat type="accounting">
                                        <pattern>¤ #,##0</pattern>
                                </currencyFormat>
                        </currencyFormatLength>
                        <unitPattern count="one">{0} {1}</unitPattern>
                        <unitPattern count="other">{0} {1}</unitPattern>
                </currencyFormats>`

In both es_ES.xml and es_CL.xml I have:
               `<currencyFormats numberSystem="latn">
                        <currencyFormatLength>
                                <currencyFormat type="standard">
                                        <pattern>¤ #,##0;¤ -#,##0</pattern>
                                </currencyFormat>
                        </currencyFormatLength>
                </currencyFormats>`

I have removed /var/cache and /var/view_preprocessed, and even, removed browser cache.

The result: the number placed using JavaScript are not formatted correctly:

![image](https://cloud.githubusercontent.com/assets/9195659/14279384/52991fe6-fb03-11e5-9ce4-919c367d55d1.png)

![image](https://cloud.githubusercontent.com/assets/9195659/14279407/73dec142-fb03-11e5-8a1c-4387feec1d50.png)

![image](https://cloud.githubusercontent.com/assets/9195659/14279509/f0f82344-fb03-11e5-874f-2f36caca355c.png)

![image](https://cloud.githubusercontent.com/assets/9195659/14279719/42d821ea-fb05-11e5-9dfb-499754eea240.png)

Regards
Jaime

**Comment by mazhalai** [comment]
@jamescowie thank you reporting, we have created MAGETWO-51790 to investigate and fix.

**Comment by okorshenko** [comment]
@jaimestuardo , thank you for reporting the issue. Unfortunately, not all parts of Magento use intl php extension to get local information. Some parts still using Zend_Locale. Since you modified Zend files, you got incorrect behavior. We have a ticket in our backlog to cleanup the code and make it more consistent, but this refactoring will take some time. For now, you can pluginize method `\Magento\Framework\Locale\FormatInterface::getPriceFormat` and change in output array value of `requiredPrecision` key. Change value from 2 to 0. In this case UI behavior looks correct. 
Please let me know if this solution works for you. Thank you!

**Comment by jaimestuardo** [comment]
Hi Okorshenko,

For "pluginize" you mean I can create a class under /app/code/[MyCompany]/[MyPlugin] that implements FormatInterface and the system will automatically call my own getPriceFormat method?

**Comment by okorshenko** [comment]
Hi @jaimestuardo , here is a documentation for Magento 2 plugins. http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html 
Please, let me know if you need some help
