### ISSUE TITLE
Wrong elements in column 'Is default' when creating new attribute of the product.

### ISSUE THREAD

**Issue by xdoctordog** [magento/magento2#4014]
## Steps to reproduce
1. Magento 2.0.4 CE |  Browser Chrome
2. Go to: Stores -> Product -> Add New Attribute
3. Choose in 'Catalog Input Type for Store Owner' tab : 'Multiple Select'  
4. Click 'Add option'
5. Choose in 'Catalog Input Type for Store Owner' tab : 'Dropdown'  
6. Choose in 'Catalog Input Type for Store Owner' tab : 'Yes / No'  
7. Choose in 'Catalog Input Type for Store Owner' tab : 'Multiple Select'  
8. Choose in 'Catalog Input Type for Store Owner' tab : 'Yes / No'  
9. Choose in 'Catalog Input Type for Store Owner' tab : 'Multiple Select'  
10. Click 'Add option'
## Expected result
1. Circle labels in two fields in column 'Is default'
## Actual result
1. One square and one circle label element  ( http://dl2.joxi.net/drive/2016/04/05/0012/3455/843135/35/b1bfab1b3e.jpg )
   ![b1bfab1b3e](https://cloud.githubusercontent.com/assets/4630880/14281266/be56c03e-fb40-11e5-980b-0427697db6ef.jpg)

**Comment by duhon** [comment]
I can't reproduce on current version. You can upgrade to the latest version?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
