### ISSUE TITLE
"Go to checkout" button is not clickable

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4015]
I am having a big problem now. The fact is that the "Go to checkout" button, in both minicart and the shopping cart page is not clickable. I have tried everything, I have trying to find where the onclick event is placed, but nothing, I cannot find the solution. I have several weeks with this problem.

Please guide me to solve this problem by myself because I cannot wait for someone to solve this.

Regards
Jaime

**Comment by ishakhsuvarov** [comment]
@jaimestuardo Do you have any customizations installed on your store? Please try this scenario with the clean Magento installation.

**Comment by jaimestuardo** [comment]
Yes.. a custom template base in Luma. Button code is:

```
       `<button title="Pagar" data-role="proceed-to-checkout" type="button" class="action primary checkout">
            <span>Pagar</span>
        </button>`
```

I cannot know what is happening here. Magento is very abstract so there is a lot of hidden details, specially what is related to JavaScript.

Since the button code is the code from Luma template, why does the onlick does not work?

To patch the problem at the moment, I have just added an onclick attribute to the button. Why did not Magento do that way at first? Why to turn things more complicated by adding JavaScript at this stage?

**Comment by piotrekkaminski** [comment]
This question would better fit magento.stackexchange.com. Github is primarily for reporting issues with core code.

**Comment by s00071609** [comment]
Its due to caching - if you use CDN like cloudflare there could be the problem. Re run the code compile if you can get it to work

**Comment by ameliemelo1** [comment]
what @s00071609 said is true.
