### ISSUE TITLE
2.0.4 salesOrderRepositoryV1GetList returns always the same shipping address for all orders

### ISSUE THREAD

**Issue by tw123** [magento/magento2#4019]
The shipping address is always the same for all orders when I use getList.
Only when I fetch them individually the shipping address is correct.

Example:
Order A with Shipping address A
Order B with Shipping address B

Query for both orders returns
Order A with Shipping address A
Order B with Shipping address A(!)

**Comment by mujtaba2012** [comment]
This issue is also discussed [here](https://github.com/magento/magento2/issues/2628#issuecomment-209155333) and [here](https://github.com/magento/magento2/issues/3967). Seems to be a bug for sure.

**Comment by NadiyaS** [comment]
Thanks for reporting this issue.
Internal ticket MAGETWO-52079  was created.

**Comment by asemenenko** [comment]
Hi @tw123 

We fixed it in develop branch. Closing the ticket as resolved. Thanks all. Feel free to re-open if there any open questions for this fix.

**Comment by rwemmercksys** [comment]
I tested this issue with 2.0.6, I see that the fix hasn't been released yet.

Is there an ETA as to when this fix will be released?

**Comment by vincentwinkel** [comment]
Why this ticket is closed?
v20.14 and I also have the bug. The only workaround is to fetch orders 1 by 1. You really think we want to do this?
Please give us an update / patch / solution / viable workaround ASAP.
