### ISSUE TITLE
Sometimes the call to payment information webservice returns error  500

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4021]
Hello,

This is very annoying... sometimes payment information can generate purchase order correctly and sometimes not.

This is what firebug reports:

![image](https://cloud.githubusercontent.com/assets/9195659/14295972/4c0e5dd0-fb4e-11e5-8d7d-23d153e3eff5.png)

Since this is a WebService, I cannot show the real error. Apache does not register anything in error_log file either.

Regards
Jaime

**Comment by alena-marchenko** [comment]
Hi @jaimestuardo,

Please provide us with exact steps to reproduce the issue and specify magento version that you are using for us to be able to investigate the issue.

**Comment by maksek** [comment]
Closing due no follow up from issue creator.
