### ISSUE TITLE
Magento 2 Installation is incomplete. console log error.

### ISSUE THREAD

**Issue by alisamohanty** [magento/magento2#4024]
![magento](https://cloud.githubusercontent.com/assets/18302927/14309916/c731ff36-fbfc-11e5-9401-f03ff9d9760f.PNG)

**Comment by mazhalai** [comment]
@alisamohanty did you previously install sample-data and now you are attempting to install without sample data? If so, please make sure to clean your browser cache, and local storage and try again.

Similar issue and solution here: https://github.com/magento/magento2/issues/2891#issuecomment-173349882

**Comment by alisamohanty** [comment]
after cleaning all cache. installation is not-completing , it stuck at 3%.
![ffffffff](https://cloud.githubusercontent.com/assets/18302927/14330300/974cd636-fc5d-11e5-9d7c-438bd60de20c.PNG)

**Comment by mazhalai** [comment]
@alisamohanty this is strange. Any error in `var/log`? Can you please turn on developer mode via cli `bin/magento deploy:mode:set developer` and try again? It might show you more detailed errors.

**Comment by mazhalai** [comment]
@alisamohanty any update?

**Comment by davidalger** [comment]
Closing due to no response from OP.
