### ISSUE TITLE
Categories Not Displaying - Via Product Import

### ISSUE THREAD

**Issue by jasonacres** [magento/magento2#4026]
Categories Not Displaying on front end Via Product Import
i think this is down to being 3 levels deep not to sure.

![mag1error](https://cloud.githubusercontent.com/assets/14318474/14311330/9aac511e-fbde-11e5-8876-9ed3da43992f.png)
![mag2error](https://cloud.githubusercontent.com/assets/14318474/14311329/9aab6042-fbde-11e5-81ba-53313265496a.png)

**Comment by jasonacres** [comment]
any update on this

**Comment by piotrekkaminski** [comment]
Can you try if it still happens on latest develop branch? Can you provide more details how to reproduce - only on import? what is the file structure @jasonacres ?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
