### ISSUE TITLE
Final Price is displaying base price

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#4027]
## Steps to reproduce
1. Create a frontend observer for 'catalog_product_get_final_price' event
2. Just use setFinalPrice([0-9]+) on product on that observer
## Expected result
1. On frontend, product view, price should be as defined in setFinalPrice()
## Actual result
1. Price displayed is base price

Location of problem :  Magento\Catalog\Pricing\Price\FinalPrice;

getValue returns explicitly the basePrice (why ?)... It should return $this->product->getFinalPrice().

**Comment by mikeweis** [comment]
Thank you for submitting this bug. I have created internal ticket MAGETWO-51696 to track this issue.

**Comment by mikeweis** [comment]
upon further review, this is not a valid use for this class:
- the purpose of this class is to dynamically determine the final price, as opposed to being a pass-through to whatever final price is currently stored in the associated product. This determination is done via looking at the base price. The base price itself cycles through the price variations, and for those variations that are instances of **BasePriceInterface**, will choose the lowest price. (For example, note that a CatalogRulePrice is an instance of BasePriceInterface)
- the purpose of the 'catalog_product_get_final_price' event is to notify any observers that the **product's** final_price field has changed

**Comment by adragus-inviqa** [comment]
You should deprecate the `catalog_product_get_final_price` event (using comments) and trigger another, more properly-named event: `catalog_product_final_price_has_changed`. Makes intent more clearer.

My 2 :moneybag:

**Comment by Nuranto** [comment]
@mikeweis Ok, I tried with a new variation instance, and it is working, but only for display on product view and product listing.
When adding to cart, the base price is used again. So I still need to use catalog_product_get_final_price to modify the final price to get it work in both product & listing display AND cart amounts....
Is that normal ? I see that catalog-rule extension is doing the same (setFinalPrice in its observer of catalog_product_get_final_price)...
In that case, catalog_product_get_final_price is not for "read-only" purpose..?

Note : You used old name BasePriceInterface instead of BasePriceProviderInterface

**Comment by arijit-de93** [comment]
Hello 

I am also facing the same in Magento 2.1.
I am setting a custom price in setFinalPrice() method in catalog_product_get_final_price observer but its returning the base price in the product details page.

Any help will be appreciated.

Thanks

**Comment by arijit-de93** [comment]
Hello,

Any updates on this issue?
