### ISSUE TITLE
Rest APIs for Review and Wishlist

### ISSUE THREAD

**Issue by gzchauhan** [magento/magento2#4028]
I didn't get for rest api for review and wishlist add/get. Can you help me for this APIs?

**Comment by hshar7** [comment]
Hi @gzchauhan could you please provide more info on what you're trying to do? Having the rest call here would greatly help us, to help you :)
Meanwhile please take a look at http://devdocs.magento.com/swagger/ which contains all of our APIs and how to use them.

**Comment by gzchauhan** [comment]
i want to add product in wishlist using rest api, also add product review by customer using rest api. I try to find those APIs in given docs but didn't get.

**Comment by maksek** [comment]
Please use forum for questions.

**Comment by ghost** [comment]
Wishlist and Reviews/Rating are integral part for any eCommerce platform and We wish Magento guys would have included them in the core features. So we have taken the initiative and added these features by taking out the fork from the github. We are waiting for Magento guys to Merge our pull request. In the meanwhile you can take use the following forks for your online store:

Reviews/Rating: https://github.com/ajay-ipragmatech/magento2
WishList: https://github.com/manish-ip/magento2

Or you can download our free plugin from the following links 
Review/Rating API Plugin : http://www.ipragmatech.com/products/review-rest-api-magento/
WishList API Plugin: http://www.ipragmatech.com/products/wishlist-rest-api-magento/

**Comment by dodiya-divyarajsinh** [comment]
we have issue when we install this module. This will create log file on API call.

Next Exception: Report ID: webapi-59db0fd84dadb; Message: Class "array" does not exist. Please note that namespace must be specified. in /var/www/html/magento_2/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/html/magento_2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /var/www/html/magento_2/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /var/www/html/magento_2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento_2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento_2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/magento_2/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by LovelySetia** [comment]
0
down vote
favorite

I have successfully install this module Reviews/Rating I call this url="/V1/review/mine/post" method="POST".I don't know what data is passed in body of this URL.

**Comment by dodiya-divyarajsinh** [comment]
POST /V1/review/mine/post HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}
Content-Type: application/json

{  
    "customer_id":"int",
    "productId": "int",
    "nickname": "text",
    "title": "text",
    "detail": "text",
    "ratingValue": "int"  
}

**Comment by templatetuners** [comment]
still no rest api for wishlist? :(
