### ISSUE TITLE
Need an updated category list using REST API.

### ISSUE THREAD

**Issue by kuldeeps3** [magento/magento2#4029]
If we are getting product list with updated date then we can do that using "http://[domain]/rest/V1/products" with search filters defining updated_at field for some last updated hour or any time.

Here we need list updated categories which are updated in last hour or some specific time.

We have used this API "http://[domain]/rest/V1/categories" here we got category tree.
but when we apply any search filter to get categories by updated_at but it return same category tree with all categories.

Our question is that how can we get the list of updated categories by using rest WebAPI.

Thanks, 
Kuldeep

**Comment by hshar7** [comment]
Hi @kuldeeps3 have you had a chance to look at http://devdocs.magento.com/swagger/ ?

**Comment by kuldeeps3** [comment]
@hshar7 , but according to this we can not get the list of updated categories.

**Comment by hshar7** [comment]
What do you mean updated category? Like the name or category attributes have been updated (category name, etc..)? Or do you mean a product has been put into the category?

**Comment by kuldeeps3** [comment]
@hshar7 , Updated category means that if we have updated any category and changed the category name.
So, We want a list of categories updated in last hour or any mentioned time.

This is our scenario.
Please let me know.

**Comment by maksek** [comment]
Please use forum for questions.
