### ISSUE TITLE
Meta Description & Keywords not escaped

### ISSUE THREAD

**Issue by anvanza** [magento/magento2#4031]
## Steps to reproduce
1. Create a product
2. Add a double quote in the "Meta Description" or in "Meta Keywords" field 
3. Save the product
   <img width="942" alt="schermafbeelding 2016-04-06 om 14 59 33" src="https://cloud.githubusercontent.com/assets/2848347/14317468/bd4a850e-fc08-11e5-8798-095bf245bcb8.png">
## Expected result
1. The Meta Description en Meta keywords return an escaped text in the frontend
## Actual result
1. The text is not escaped, breaking the html tag.
   <img width="600" alt="schermafbeelding 2016-04-06 om 15 03 46" src="https://cloud.githubusercontent.com/assets/2848347/14317483/cc9fb1a0-fc08-11e5-8099-04a846de1140.png">
## Extra

It's extra fun to add scripts in there.
`no no"/><script>alert("ow no");</script><useless keywords="Cocoon hoog blauw`
## Specs

Magento CE 2.0.4
PHP7

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2295, https://github.com/magento/magento2/issues/1514

**Comment by vzabaznov** [comment]
@anvanza bug was fixed and delivered to develop branch, thank you for contributing, please feel free to add new issues or write, if fix doesn't help.

**Comment by pragya-tech** [comment]
Is there any way to change meta details order like below:

1. Meta-Title
2. Meta-Description
3. Meta-Keywords
