### ISSUE TITLE
Security Message Issue in magento admin"Your web server is set up incorrectly and allows unauthorized access to sensitive files. Please contact your hosting provider."

### ISSUE THREAD

**Issue by gg24** [magento/magento2#4032]
I am facing the issue "Your web server is set up incorrectly and allows unauthorized access to sensitive files. Please contact your hosting provider." in magento admin,
It not shown on my local system(Apache server), and not even on Apache server,but when we moove the code on AWS with nginx, this issue occurs, I think this issue is related to nginx configuration on server .Can Anybody give me suggestion to resolve this issue.

**Comment by mrkhoa99** [comment]
@gg24 You check your files permission and ownership? http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by vancoz** [comment]
Hi @gg24  please use http://magento.stackexchange.com/ for configuration or any other kinds of questions.

**Comment by gg24** [comment]
Our, IT team set file permission and ownership according the above threads, while facing the same issue.

**Comment by magenx** [comment]
this is because apache is reading .htaccess files by default in magento root and other folders, when you switch to nginx you need to configure every deny rule properly. thats it.
