### ISSUE TITLE
Switch language and notification messages breaks backend

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4034]
## Steps to reproduce
1. Switch language to Switzerland de_CH
2. After the first notification apears, in my case update to 2.0.3
## Expected result
1. Magento should still work
## Actual result
1. Magento Logins still works, but after login backend is broaken.
2. http://magento.stackexchange.com/questions/108738/magento-2-update-2-0-3-note-in-backend-fail/108977#108977

It happen already the second time just after switching the lacal settings from Englisch to de_CH.

**Comment by mazhalai** [comment]
@flipflap did you try `bin/magento cache:flush`

**Comment by flipflap** [comment]
I can't say it for 100% sure, but I spent a whole day with deleting caches and folders and setting modes before I setup the whole magento again. So I think yes. I can't try it now again as I already started to setup magento again.

**Comment by mazhalai** [comment]
@flipflap any update?

**Comment by flipflap** [comment]
No, not yet. Until now the new installation works. Maybe it will fail again when the next update notification comes in.

**Comment by mazhalai** [comment]
@flipflap OK, closing this issue for now. Please open a new issue if problems arise.
