### ISSUE TITLE
Import custom options type 'file' fails

### ISSUE THREAD

**Issue by Omitri** [magento/magento2#4035]
## Steps to reproduce

Create a product with a custom option type 'file'
Export the product
Import the CSV-file
## Expected result

Product is imported.
## Actual result

Error message appears: 1. Value for 'type' sub attribute in 'custom_options' attribute contains incorrect value, acceptable values are: 'dropdown', 'checkbox' in rows: 1

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53569

**Comment by pieal86** [comment]
any solution for this one?
