### ISSUE TITLE
Page content is causing some kind of error

### ISSUE THREAD

**Issue by AniAko** [magento/magento2#4039]
## Steps to reproduce
1. Install Magento 2.0.2 or 2.0.4
2. Add a Content Page
3. Add values to all necessary required fields in order to save the page with the exception of the content
4. Using the WYSIWYG editor, copy and past this following text into the box.

`11.          SUBMISSIONS.  If Customer or any user sends, transmits, posts, e-mails or otherwise conveys to Tyndale, whether at our request or not, any information, software, photos, video, text, graphics, music, sounds, questions, creative suggestions, messages, comments, feedback, ideas, notes, drawings, articles, stories about Customer or its users, or other materials of any kind whatsoever (collectively, the "Submissions"), those Submissions will be deemed, and will remain, the property of Tyndale.  Subject to the Tyndale Privacy Policy [INCLUDE LINK], none of the Submissions will be subject to any obligation of confidentiality on our part, nor will we be liable for the use or disclosure of any Submissions. Without limitation of the foregoing, Customer grants to Tyndale and its successors and assigns a royalty-free, perpetual, irrevocable, non-exclusive right (including any moral rights) and license (as well as consent) to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, communicate to the public, perform, display and sublicense any Submissions (in whole or in part and with or without the use of Customer's name in conjunction therewith) anywhere in the world.  Customer also grants to Tyndale and its successors and assigns the right to incorporate Submissions into other works in any form, medium or technology now known or later developed, for the full term of any copyrights, trademarks and other intellectual and proprietary rights (collectively, "Rights") that may exist in such Submissions.  Customer also warrants to Tyndale that any third party holder of any Rights has validly and irrevocably granted to Customer the right to grant the rights and licenses set forth above.  Customer further acknowledges that Tyndale and its successors and assigns will be entitled to unrestricted use of the Submissions for any purpose whatsoever, commercial or otherwise. 
`
1. Save the Page
## Expected result
1. The page saves
## Actual result
1. The page throws a 403 with the following message:

Forbidden

You don't have permission to access /admin_1a1ryf/cms/page/save/key/7d65daced65de45e0bacdaaa9434b9f4e3670e1d5902ab107abc180a514b8e29/active_tab/content_section/ on this server.

![20160406174444](https://cloud.githubusercontent.com/assets/6796234/14333951/3a603708-fc1f-11e5-90fc-fdaf6a1c7bb1.png)

[debug.txt](https://github.com/magento/magento2/files/207404/debug.txt)

[exception.txt](https://github.com/magento/magento2/files/207405/exception.txt)

[system.txt](https://github.com/magento/magento2/files/207407/system.txt)

**Comment by shiftedreality** [comment]
Hi, @AniAko 

CMS components were completely rewritten. Could you please try to reproduce your issue on latest develop branch?

**Comment by ghost** [comment]
I'm seeing the same error. Don't need to paste anything into the box - just hitting either of the Save buttons throws the same error. Using 2.0.4.

**Comment by mazhalai** [comment]
@AniAko thank you for reporting, we have created MAGETWO-51934 to investigate and fix

**Comment by shiftedreality** [comment]
Hi @AniAko 

I was not able to reproduce this bug on latest 2.0.4 branch.
Also i see a lot of exceptions from 3rd-party extension in exception.txt
Is this bug reproducible for you on clean Magento 2 installation?

**Comment by AniAko** [comment]
We had started on 2.0.2 and gone through an upgrade directly to 2.0.4.  I have however worked with an affiliate on a clean installation of 2.0.4 directly and the issue doesn't seem to be present.  Unfortunately, we have torn down our instance as we've moved away from a Magento solution (not because of this bug)  Thank you for investigating this for us.

**Comment by magentotejpal** [comment]
Hi, 
i am Creating the page in Magetno 2. 

when i go content section and click on the show/hide editor. i have put the data in this page. after see the forbidden error .You don't have permission to access /admin/cms/page/save/key

**Comment by KrystynaKabannyk** [comment]
Hello @AniAko, this issue has been fixed in Magento EE 2.1 RC2. Thank you for reporting the issue! If you have any questions or additional information you are welcome to reopen it or create another one.

**Comment by KalaiarasanSeetharaman** [comment]
Same error is coming for me in live in magento 2.0.6 . How it should be fixed
