### ISSUE TITLE
Restore config setting

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#404]
A "Restore to default" button or checkbox would be useful for the fields in `System->Configuration` that would just delete the value in the table `core_config_data` thus making Magento use the value declared in `config.xml`, or an empty value if that does not exist.  
If not all fields should be allowed to be "restored to default" maybe this can be managed  from `system.xml` with a new attribute on the `<field>` tag. Example

```<field id="list_mode" translate="label" type="select" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="0"><!--  or canRestore="1" -->
    <label>List Mode</label>
                       <source_model>Magento\Catalog\Model\Config\Source\ListMode</source_model>
</field>```

**Comment by ilol** [comment]
MAGETWO-34400

**Comment by tzyganu** [comment]
Since the PR was merged, I will close this issue.  
So after the 2.5 years that have passed since this issue was opened, I can finally make the stupid joke.  Issue #404..."Issue not found".

**Comment by shivkumarsingh7** [comment]
Very helpful information
