### ISSUE TITLE
Onepage checkout issue - address form section not always loaded.

### ISSUE THREAD

**Issue by yetket** [magento/magento2#4040]
I always have issues with checkout.
I have upgraded magento to version: 2.0.4

Steps to reproduce
1. add item(s) to cart,
2. click go to checkout.

The problem step.
The "Address Form“ section (left section) does not always loaded up properly.

The screenshot as below...

![mco](https://cloud.githubusercontent.com/assets/9208596/14337180/c9c78bdc-fcae-11e5-8063-97d00b872249.JPG)

**Comment by ishakhsuvarov** [comment]
@yetket Hi, thank you for reporting. Do you have any customizations installed? Have you tried with the clean Magento installation?

**Comment by ishakhsuvarov** [comment]
@yetket Closing this ticket for now, please reopen if the issue persists.
