### ISSUE TITLE
Add service contract API to set system configuration values

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#4041]
Before going through the work to create a PR, I wanted to ask if this feature maybe already is being developed internally.

More details:  
Currently there is no service contract API to manage the system configuration in the `core_config_data` table.  

I am aware of the `\Magento\Store\Api\StoreConfigManagerInterface` and `\Magento\Store\Api\Data\StoreConfigInterface`, but having a more generic interface to build extensions to help with deployment and provisioning of dev systems would be very useful.  

Currently the only way to do that I have found was to use direct SQL inserts into the table, or use `\Magento\Config\Model\Config` directly. In addition to not being blessed with an `@api` annotation, the public interface isn't easy to use with the PHP array it uses.

What I would like to have in the to be added service contract API would be a data object with a scope, scope_id, path and value. And a repository to save and get them.

So if this isn't already part of an internal task and you think it is a good idea, please give me a go ahead.

**Comment by adragus-inviqa** [comment]
> having a more generic interface to build extensions to help with deployment and provisioning of dev systems would be very useful

Could you give us some examples of that?

**Comment by Vinai** [comment]
Sure. For example, just a few days ago I would have liked to add a little command to `bin/magento` like

`bin/magento system:config:set system/full_page_cache/caching_application 2` (enable varnish FPC)
I also was looking for a way to set sandbox values for payment modules on an integration host in a similar fashion.  

Another useful application is setting system config values in setup scripts, so they are applied automatically with a module.  
In Magento 1 there was `\Mage_Core_Model_Resource_Setup::setConfigData()`, but that didn't make it into Magento 2 it seems. At least none of the interfaces inheriting `\Magento\Framework\Setup\SetupInterface` have it.

**Comment by mazhalai** [comment]
@Vinai Thank you for reporting, we have created MAGETWO-51781 to investigate and fix.

**Comment by adragus-inviqa** [comment]
Is `Magento\Framework\App\Config\Storage\WriterInterface` of any help?

**Comment by Vinai** [comment]
@adragus-inviqa That interface would be perfect if it had a `@api` annotation. Thanks!

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-service-contract-API-to-set-system-configuration-values/idi-p/46037).
