### ISSUE TITLE
Category view collection uses search collection, ignores store stock settings

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#4045]
## Steps to reproduce
1. Build custom theme.
2. Add Products to Category in Admin Panel.
3. Set Manage Stock to No (site wide in the Store Configuration).
4. Visit Category page.
## Expected result
1. See list of Products on Category page.
## Actual result
1. Product collection SQL shows that it's looking for stock. It also shows that it's trying to join with search results :

```
`SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='40'
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = '1' AND stock_status_index.stock_id = 1
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `search_tmp_57064a6dead701_65566546` AS `search_result` ON e.entity_id = search_result.entity_id WHERE (stock_status_index.stock_status=1) ORDER BY `cat_index`.`position` ASC LIMIT 9`
```

Removing the stock and search joins returns a result, so I know it's the cause of the products not appearing on the frontend.

**Comment by jameswithers** [comment]
On the search table being joined, it's caused by the following code in `CatalogSearch/etc/di.xml`:

```
<type name="Magento\Catalog\Model\Layer\Category">
        <arguments>
            <argument name="context" xsi:type="object">Magento\CatalogSearch\Model\Layer\Category\Context</argument>
        </arguments>
</type>
```

This means the product list on a page is a search result Product collection, not a standard Product. collection. Overriding this in my own module `di.xml` solves this problem.

Stock is added because `\Magento\CatalogInventory\Model\Plugin::beforePrepareProductCollection()` does not check the store configuration to see if stock is being managed, before it applies the stock filter. Overriding this function solves this problem.

Why is Magento not checking to see if the store is managing stock, before it applies stock logic?

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53563

**Comment by kandy** [comment]
@jameswithers, You should use "Display Out of Stock Products" setting to enable show out of stock product on store front, so I am closing this issue. Feel free to reopen issue if we missed anything.
