### ISSUE TITLE
placeOrderAction does not set order with the default status according to configuration

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4046]
I have created a new payment method. In configuration interface, I have set that the default order status is Pending Payment as the screenshot shows, however, when I call this js function, the new order is created in Processing status.

```
                        placeOrder = placeOrderAction(this.getData(), false, this.messageContainer);

                        $.when(placeOrder).fail(function () {
                            self.isPlaceOrderActionAllowed(true);

                        }).done( function(data) {                            });
```

![image](https://cloud.githubusercontent.com/assets/9195659/14352410/cc23b346-fcaa-11e5-8bbe-b3ba6b3fdc01.png)

**Comment by piotrekkaminski** [comment]
It is better to ask this on magento.stackexchange.com. If it turns out to be Magento bug - please create new issue referencing this.
