### ISSUE TITLE
No default placeholder for swatch_image type

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#4047]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add new type of image to view.xml, using swatch_image type
3. Add product without swatch_image
4. Use your new type of image somewhere on storefront
## Expected result
1. Swatch image placeholder should be visible as for other types of images
## Actual result
1. Error message appears: "Notice: getimagesize(): Read error!".
   ![2016-04-07_15h43_37](https://cloud.githubusercontent.com/assets/9566840/14353061/b57c8438-fcd7-11e5-8e88-70e161bdebc0.png)

Error is thrown because magento is looking for 'pub_dir/Magento_Catalog/images/product/placeholder/swatch_image.jpg'.

**Comment by mcspronko** [comment]
Hi @piotrekkaminski 

Any updates for this error?

Thanks,
Max

**Comment by piotrekkaminski** [comment]
@mcspronko does it happen on 2.1RC1/2?

**Comment by Bartlomiejsz** [comment]
@piotrekkaminski yes, it does on 2.1RC2

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54235

**Comment by mcspronko** [comment]
Hi @piotrekkaminski,

Thank you for internal issue reference. Any dates when this is going to be fixed?

Thanks

**Comment by okorshenko** [comment]
The issue has been fixed in develop branch
