### ISSUE TITLE
Group associated products not showing

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#4048]
## Steps to reproduce
1. Visit Grouped Product page
2. Manage Stock is set to No in Store Configuration
## Expected result
1. Show all Associated Products
## Actual result
1. No Associated Products are shown, as the collection has a stock filter added. Possibly related to https://github.com/magento/magento2/issues/4045. 

When Manage Stock is set to No, why are stock filters still being applied?

**Comment by jameswithers** [comment]
The error is only rectified when the product is set to Manage Stock, then set back to Use Config. In `cataloginventory_stock_item` all stock items show out of stock, which causes them not to display. These should be set to is_in_stock, or Magento should not be checking, if the Store Configuration has Manage Stock set to No

**Comment by jameswithers** [comment]
Using the Import tool to set stock levels imports the values, but they are not set in the `cataloginventory_stock_status` table unless you go into each simple associated product of a group and save it manually

**Comment by jameswithers** [comment]
Setting `product_websites` populates the `cataloginventory_stock_status` table

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53561

**Comment by kandy** [comment]
@jameswithers,  You should use "Display Out of Stock Products"  setting to enable show out of stock product on store front, so I am closing this issue. Feel free to reopen issue if we missed anything.
