### ISSUE TITLE
Not getting an error while trying to create shipment of already shipped item

### ISSUE THREAD

**Issue by zahmed-f3** [magento/magento2#4052]
## Steps to reproduce
1. Install Magento version `2.0.4`.
2. Create an order with single item having quantity one like below:
   ![order](https://cloud.githubusercontent.com/assets/10192530/14357291/95eafb7a-fd01-11e5-9346-fb84c29c379a.jpg)
3. Create a Shipment via Rest API like below:
   POST: /rest/V1/shipment/
   `{
   "entity" : {
       "orderId" : 5,
       "items" : [{
               "orderItemId" : 5,
               "qty" : 1
           }
       ]
   }
   }`
4. Try to create Shipment multiple times using above call with same data.
## Expected result

After creating first shipment, it should throw an exception if the quantity of the item in the order has been shipped.
## Actual result

Multiple Shipments is creating with single item having quantity one like below:
![multiple-shipments](https://cloud.githubusercontent.com/assets/10192530/14357169/148787ec-fd01-11e5-845f-df4cfe18c246.jpg)

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53558

**Comment by veloraven** [comment]
Internal ticket was closed as a duplicate.
Corresponding internal tickets are already closed as they were fixed for develop branch.
Closed.
