### ISSUE TITLE
/rest/default/V1/carts/mine/shipping-information 404

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#4057]
During checkout in Magento 2.0.2, I am getting 404 error for /rest/default/V1/carts/mine/shipping-information request and which doesn't let me go to Payment step.
Any idea about this issue?

**Comment by ishakhsuvarov** [comment]
@MagePsycho Thank you for reporting this issue. Could you please provide preconditions and steps to reproduce the issue?

**Comment by devdesco-ceo** [comment]
Same thing here.
Also on POST, https://zzz.com/rest/en_int/V1/carts/mine/estimate-shipping-methods-by-address-id
gives error 401 and redirects to dashboard.

**Comment by maksek** [comment]
steps to reproduce was not provided, closing due inactivity on the ticket from creator. @devdesco-ceo, if you can provide detailed steps and precondition, we will reopen the ticket.

**Comment by mitsprajapati** [comment]
Hi
When I try to select payment method paypal in checkout and than click place order. I see following error in ajax response.

You don't have permission to access /rest/esbrewing/V1/carts/mine/selected-payment-method
on this server.

Can any one help me how to fix this issue as I cant place order using paypal.

My magento 2 version is : 2.0.4

**Comment by vipin-eglobeits** [comment]
Hi,
I got an issue which is very similar to this in magento 2.1.
Could you please take a look at #5542.

**Comment by atsareva** [comment]
Hi,
@viktor-zhuromskyy I've faced with the same problem. Did you find any solution to fix it? Thanks.

**Comment by harshvardhanmalpani** [comment]
I turned on two modules - Web api and Webapi security
php bin/magento module:enable Magento_Webapi Magento_WebapiSecurity

and it worked.

**Comment by mattcoz** [comment]
@viktor-zhuromskyy @atsareva Any success on that problem? I posted my own issue on it but it was closed. #12119
