### ISSUE TITLE
File not repopulating when editing/reordering products with custom option in cart

### ISSUE THREAD

**Issue by fhennessy** [magento/magento2#4058]
- Create a product with a required custom option file field
- Upload a file, add to cart
- Edit cart, edit product with file
- Submit product
- Cart throws an error, saying that one or more required fields were not submitted (the file does not get resubmitted/repopulated)

-same thing happens when customer tries to reorder a product with a required custom option file field from their account

**Comment by sdzhepa** [comment]
@fhennessy Thank you for reporting this issue. We have created an internal ticket `MAGETWO-51903` to fix the problem.

**Comment by piotrekkaminski** [comment]
Issue was fixed and merged to develop branch.

**Comment by iamgurjitsingh** [comment]
How can we find code which you implemented in this problem ? @piotrekkaminski
