### ISSUE TITLE
SearchCriteria too limited in AND/OR filtering

### ISSUE THREAD

**Issue by samtay** [magento/magento2#4060]
From what I understand, filters are combined with an OR logic within a particular filter group, and filter groups are combined with AND logic within search criteria. This is unfortunately not listed in documentation, but is what users on stackoverflow have discovered.

This is very limiting. For example, it is **impossible to filter the product repository by two date intervals**: suppose I want to grab all the products that are either new or on sale. This would involve logic like so:

```
(filter['special_price_from', 'to', $now] && filter['special_price_to', 'from', $now])
|| (filter['news_from_date', 'to', $now] && filter['news_to_date', 'from', $now])
```

But this is impossible to build as searchCriteria. The outer OR would dictate that everything needs to be in one filter group, but within each interval we also need AND combinations, which are impossible within one filter group. Because of these limitations, I have been forced to use collections directly instead of using the repository abstraction layer. Please let me know if there is a more flexible way to have and/or combinations.

**Comment by pboisvert** [comment]
@choukalos can you take a look at this one Chuck?

**Comment by choukalos** [comment]
Hello @SamTay you are correct that's how search criteria works [doc link](http://devdocs.magento.com/guides/v2.0/howdoi/webapi/search-criteria.html).  

What would you like to see for search criteria? 

I've created an epic to track this request internally ( MAGETWO-53564 ).

**Comment by samtay** [comment]
Ability to specify nested and/or logic, see above example.

**Comment by choukalos** [comment]
Thanks @SamTay for the insight.  We're tracking internally.

For those on this thread, a change to search criteria would be a breaking change; how big of an impact would this be for you all?

**Comment by Ctucker9233** [comment]
@choukalos What do you mean by breaking change? If it breaks the search criteria so it doesn't work that would have a very negative impact. But maybe I don't fully understand the question you are asking.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/SearchCriteria-too-limited-in-AND-OR-filtering/idi-p/46030).
