### ISSUE TITLE
Incorrect re-order when items has different values of custom option

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#4062]
## Steps to reproduce
1. magento 2.0.2
2. create simple product with custom option, type=TextField
3. go to product page, add this product to cart twice, so there are 2 items in cart:
   3.1. with "test1" value in custom option
   3.2. with "test2" value in custom option
4. place order with authorization (to have ability to re-order)
   ![order 000000045](https://cloud.githubusercontent.com/assets/10142848/14379157/60386ca8-fd81-11e5-81fd-a29cc2313732.png)
5. go to order page, click "reorder"
   Expected result
   --
6. Cart should contain 2 items with qty=1
## Actual result
1. cart contains 1 item with qty=2. In other words custom options are ignored toidentify unique items
   ![shopping cart](https://cloud.githubusercontent.com/assets/10142848/14379208/8c2b9916-fd81-11e5-907a-1357981ba00e.png)

**Comment by NadiyaS** [comment]
Hi @Katerina1993 ,
thank you for reporting this issue. Internal ticket MAGETWO-52041 was created.

**Comment by NadiyaS** [comment]
Hi @Katerina1993,
this bug is not reproducible anymore on the latest Magento 2 code.
You can upgrade your code right now from develop branch or upgrade Magento 2 after next release.

**Comment by NadiyaS** [comment]
Hi @Katerina1993 ,
ticket is closed with resolution 'Cannot reproduce'.
