### ISSUE TITLE
zero amount being sent to paypal Payflow

### ISSUE THREAD

**Issue by lexuanchien** [magento/magento2#4063]
Hi.
i'm testing Magento 2 to upgarade my website from 1,9, but i have problem when paypal Payflow. Why zero amount being sent to paypal Payflow. Request to Paypal i received from debug.log below:

i have see on issues: https://github.com/magento/magento2/issues/3509 .  I tried different users to no avail. Does anyone have this working? Ideas?
[2016-04-08 09:26:12] main.DEBUG: array (
  'request' => 
  array (
    'user' => '***_',
    'vendor' => 'my vendor',
    'partner' => 'PayPal',
    'pwd' => '**_*',
    'verbosity' => 'HIGH',
    'BNCODE' => 'Magento_Cart_Community',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'createsecuretoken' => 'Y',
    'securetokenid' => 'f03a3646f3686a207bf5b392d1a862fc',
    'returnurl' => 'http://localhost/magento204/paypal/transparent/response/',
    'errorurl' => 'http://localhost/magento204/paypal/transparent/response/',
    'cancelurl' => 'http://localhost/magento204/paypal/transparent/cancel/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'jonh',
    'lastname' => 'ferr',
    'street' => 'ha noi',
    'city' => 'ha noi',
    'state' => NULL,
    'zip' => '3523',
    'country' => 'AU',
    'email' => 'tester@gmail.com',
    'shiptofirstname' => 'jonh',
    'shiptolastname' => 'feer',
    'shiptostreet' => 'ha noi',
    'shiptocity' => 'ha noi',
    'shiptostate' => NULL,
    'shiptozip' => '3523',
    'shiptocountry' => 'AU',
  ),

**Comment by alena-marchenko** [comment]
Hi @lexuanchien,

When you are using PayPal Payments Pro or Payflow Pro solution first request sent to PayPal intended for account verification. Account verification, also known as zero-amount authorizations, are used for verifying the validity of customer credit card information. You can find more information at [PayPal documentation](https://developer.paypal.com/webapps/developer/docs/classic/payflow/integration-guide/#submitting-account-verifications).
Closing the issue, please feel free to re-open it if further assistance needed.

**Comment by Sam-PUMP** [comment]
Hi - its still not working for me. What are the settings for silent post and silent post URL in manager ? Have a pay flow pro account and it works great in magento1 but can't get it successfully approving transactions on  Magento2. They are all declined with an authentication failed message. SSL is working and curl is newer then required vervsion. Everything is set on POST but still 
All declines. For silent post I used the same URL as return URL but I guess that is not it either. 

Thanks!

**Comment by bmzero** [comment]
Any update on this? Having the exact same issue and have tried the suggested steps to resolve.

**Comment by brijeshjp2006** [comment]
If You do payment on test mode for Paypal Payflow then go
vendor\magento\module-paypal\Model\Payflow\Service\Request\SecureToken.php

then find
$request->setAmt(0);
After you can change payment according you like
$request->setAmt(10.50);

**Comment by devantoni** [comment]
I'm getting the same issue for Magento 2.19
When contacted PayPal they say the PayPal Australia processor doesn't accept zero authorization and asked to set the amount in $request->setAmt(); 
My question here is: if PayPal Australia won't accept zero authorization why can't Magento have a configuration to make an adjustment towards PayPal Australia at least? It's annoying to modify the core file / rewrite them for the pre-built solution. Magento should take care of this sorts of issue.
I'm expecting a walk through to sort this kind of issues.
