### ISSUE TITLE
paypal does not work, 

### ISSUE THREAD

**Issue by bgabrovsek** [magento/magento2#4064]
My paypal stopped working.

I have added an paypal express account, but on the checkout page when I click "Continue to paypal", the rotating wheel appears and goes on forever.
I have tried on different browsers, OSs and even reinstalled Magento2 on a different domain, but the problem persists.

In the web console I get:

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
.process() error-processor.js:19
<anonymous> set-payment-method.js:51
jQuery.Callbacks/fire() jquery.js:3099
jQuery.Callbacks/self.fireWith() jquery.js:3211
done()  jquery.js:9312
.send/callback() 
```

Please advise!

**Comment by thomvanderboon** [comment]
I have same issue (rotating wheel) with pay.nl payment plugin..... nothing in the exception log

**Comment by alena-marchenko** [comment]
Hi @bgabrovsek 

Could you specify php version, that you are using?

**Comment by maksek** [comment]
Issue related/clone #4076. Closing as duplicate and not activity for long time.
