### ISSUE TITLE
Magento 2.0.4 Installation is incomplete with sample data 

### ISSUE THREAD

**Issue by avbinoy** [magento/magento2#4069]
## Steps to reproduce
1. Downloaded (not cloned)  https://github.com/magento/magento2-sample-data to magento2-sample-data folder
2. Change directory to /opt/lampp/htdocs
3. Downloaded latest version of magento (2.0.4) from https://www.magentocommerce.com/download (bz2 format) and extracted to /opt/lampp/htdocs/magento2 folder. After that executed php -f magento2-sample-data/dev/tools/build-sample-data.php -- --ce-source="/opt/lampp/htdocs/magento2" and it created symbolic links
4. Taken http://localhost/magento2/setup/ in browser. On last step, the process stopped at 87%.
## Expected result
1. Successful installation of magento 2 with sample data
## Actual result
1. Installation is incomplete. 
   Check the console log for errors before trying again.

Console log is given below

Starting Magento installation:
.
.
Schema post-updates:
.
.
.
Installing data...
Data install/update:
Module 'Magento_Store':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Backup':
Module 'Magento_Eav':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_AdminNotification':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Msrp':
Module 'Magento_Search':
Module 'Magento_Bundle':
Module 'Magento_Quote':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_SalesSequence':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Payment':
Module 'Magento_Downloadable':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_CatalogInventory':
Module 'Magento_SampleData':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_CatalogSearch':
Module 'Magento_CustomerImportExport':
Module 'Magento_CustomerSampleData':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_User':
Module 'Magento_ImportExport':
Module 'Magento_Sales':
Module 'Magento_CatalogRule':
Module 'Magento_Email':
Module 'Magento_EncryptionKey':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_Checkout':
Module 'Magento_GoogleAnalytics':
Module 'Magento_GoogleOptimizer':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_Tax':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Braintree':
Module 'Magento_Integration':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_MsrpSampleData':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_OfflineShipping':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_Weee':
Module 'Magento_ProductVideo':

Module 'Magento_CatalogSampleData':
[ERROR] exception 'ReflectionException' with message 'Class Magento\Catalog\Model\ResourceModel\Product\Gallery does not exist' in /opt/lampp/htdocs/magento2/vendor/magento/framework/Code/Reader/ClassReader.php:29
Stack trace:
#0 /opt/lampp/htdocs/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(29): ReflectionParameter->getClass()
#1 /opt/lampp/htdocs/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Catalog...')
#2 /opt/lampp/htdocs/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\Catalog...')
#3 /opt/lampp/htdocs/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Catalog...')
#4 /opt/lampp/htdocs/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Catalog...')

**Comment by mazhalai** [comment]
@avbinoy Since you closed this issue, can you please post how this was resolved? So that others who encounter this same issue can fix it too.

**Comment by avbinoy** [comment]
I solved the issue by downloading Full Release with Sample Data (ZIP with sample data). Earlier, I used without sample data package and I downloaded sample data package separately from github mentioned above. I think, same issue will happen again if I follow the above steps (Hope those steps are correct, I am new to magento)

**Comment by lazarenkoalexey** [comment]
Have the same issue while installing sampledata via composer or git clone. Please provide an advice how to install sample data to exist magento 2.0.4

**Comment by mazhalai** [comment]
@dzotic9 please do not post on closed issues.
to deploy sample data on an already installed instance, on command line run `bin/magento  sampledata:deploy` then `bin/magento setup:upgrade`
