### ISSUE TITLE
Connect Manager(under System) creating Class 'Magento\Autoload\Simple' not found error in admin panel.

### ISSUE THREAD

**Issue by santanu-brahma** [magento/magento2#407]
After log-in to the Magento admin panel, In case of access the Connect Manager under System tab creating Class 'Magento\Autoload\Simple' not found error.

I have checked that index.php under downloader folder creating the error. "\Magento\Autoload\Simple::register();" is written on line no 33 at index.php but it seems to be not valid over there.

![connect_manager_error](https://f.cloud.github.com/assets/3183444/1500063/2c959be0-486c-11e3-8bfa-5e0165e96a53.png)

**Comment by choukalos** [comment]
Re-assigning to Tanya since she's responsible for the install tool.

**Comment by vpelipenko** [comment]
All Connect Manager components were removed from code base. Closed as not relevant.
