### ISSUE TITLE
Added-to-cart message appears on all pages. 

### ISSUE THREAD

**Issue by saderra** [magento/magento2#4071]
## Steps to reproduce
- Installed a brand new digital ocean box with 2.0.4 / Ubuntu
- Switched to Blank Theme
- Added a simple product for testing
## Expected result
- Added the product to my cart once from the category page. Green notice of added to cart showed up. 
## Actual result
- Any page viewed after this shows the same added-to-cart message, even the account pages. 
- The issue also existed if the product was added view the product page.

**Comment by clhari** [comment]
I got the same issue in production mode, but not in developer mode.

**Comment by piotrekkaminski** [comment]
This seems related to MAGETWO-46014 (which is currently merged into develop branch) and many Github issues https://github.com/magento/magento2/issues/4336
https://github.com/magento/magento2/issues/4186
https://github.com/magento/magento2/issues/3503

If you still experience it on develop version, please open a new issue referencing this.
