### ISSUE TITLE
<!--@subject Your {{var store.getFrontendName()}} order confirmation @--> is not translated

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4072]
It is impossible at the moment to translate that message into Spanish. I think this problem exists in all other templates:

This is at order_new.html template.

That message cannot be translated using the CSV file.

**Comment by mazhalai** [comment]
@jamescowie How can we reproduce this issue?

**Comment by jaimestuardo** [comment]
just set the frontend language to Spanish and do a purchase. Then analyze the confiirmation e-mail that arrives to customer.

Besides this problem, I have found also that in CSV file, links  are written using single quote, while in code, the texts are using double quotes. The result to this, is that text containing links are not translated either.

To solve the links problem by myself, I had to use double double quotes in CSV files.

**Comment by mazhalai** [comment]
@jamescowie thank you for reporting, we have created ticket MAGETWO-51792 to investigate and fix.

**Comment by jaimestuardo** [comment]
Thanks.. I have patched it using the solution in that referenced post, but I needed to add this in es_ES.CSV file: 

"Your %store_name order confirmation","Su confirmación de pedido en %store_name"

**Comment by okorshenko** [comment]
@jaimestuardo Thank you for reporting the issue. MAGETWO-51792 merged to develop branch.
