### ISSUE TITLE
Bullets or unordered lists in description breaks luma theme header

### ISSUE THREAD

**Issue by npearson72** [magento/magento2#4073]
See screenshot:

![2016-04-08 at 8 47 pm](https://cloud.githubusercontent.com/assets/1323414/14401598/68424960-fdcb-11e5-8fc0-16e6a2986bbe.png)

**Comment by tigerx7** [comment]
This is related to the unescaped html tags that get added into the meta description block automatically when it's empty. The issue has been around for awhile (July 2015) but it seems a fix hasn't made it into any of the recent releases:

Same issue reported:
https://github.com/magento/magento2/issues/1514 https://github.com/magento/magento2/issues/2613 https://github.com/magento/magento2/issues/3090 https://github.com/magento/magento2/issues/3244 https://github.com/magento/magento2/issues/3255 https://github.com/magento/magento2/issues/3813 https://github.com/magento/magento2/issues/4031

**Comment by vzabaznov** [comment]
@npearson72 bug was fixed and delivered to develop branch, thank you for contributing, please feel free to add new issues or write, if fix doesn't help.
