### ISSUE TITLE
Configurable Products Add to Cart issue

### ISSUE THREAD

**Issue by rushvigajjarsilk** [magento/magento2#4074]
Hello,
I want to add each configurable products as separate line item. For example, if user selects any configurable products and set qty as 3 then 3 configurable products will be added into cart as separate line items with qty 1 into cart with same configuration.

To do this I have made customization in below two files as described,
vendor/magento/module-checkout/Controller/Cart/Add.php (Before Cart Save Function)

```
$getcartQty = $params['qty'];
for($i=0; $i<$getcartQty; $i++)
{
    $params['qty']=1;
    $this->cart->addProduct($product, $params);
}
```

module-quote/Model/Quote.php

```
public function getItemByProduct($product)
    {
        return false  //As I want each Item as separate line item.
        foreach ($this->getAllItems() as $item) {
            if ($item->representProduct($product)) 
            {
                return $item;
            }
        }
        return false;
    }
```

First time when i am doing this it is working fine. But when next time i will add same configurable products with different configurations or add some another configurable products it will not allow me to add. It will display error message as "Selected option(s) or their combination is not currently available.".

Could you please help me out to resolve this?

Any help would be appreciated.

Thanks.

**Comment by rushvigajjarsilk** [comment]
Hello,

Can you kindly let me know if any update on this. I need to fix this asap. Awaiting for your reply.

Thanks,

**Comment by piotrekkaminski** [comment]
The best place to ask questions like this is magento.stackexchange.com. Github is only for error reports and contributions.
