### ISSUE TITLE
Magento 2.0.0 : Notice: getimagesize(): Read error! in /home/parthv/www/magento-2-demo/vendor/magento/module-catalog/Model/Product/Image.php on line 949

### ISSUE THREAD

**Issue by parthviroja** [magento/magento2#4075]
I have install magento 2.0.0.

now  i create my new theme [ parth-theme ] and create few required directory and file.

> bin/magento deploy:mode:set developer
> 
> bin/magento setup:static-content:deploy.

open magento admin.

set [ parth-theme ] from store -> configuration -> design 

when i open any product and click on product detail page than this error is display..

**Comment by mazhalai** [comment]
@parthviroja Can you please verify your version? This has been already fixed, see https://github.com/magento/magento2/issues/2276 and related commits.

**Comment by parthviroja** [comment]
Thanks, mazhalai

**Comment by slackerzz** [comment]
i had the same error in Magento EE 2.0.7
after creating the "optional" etc/view.xml in my theme the error disappeared
