### ISSUE TITLE
Price on product view page becomes 0,00 when locale is changed to persian (iran)

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#4077]
## Steps to reproduce
1. Install Magento 2.0.2/3/4/5.
2. Go to Store->Configurations in admin
3. Change locale to Persian(iran)
4. Open any product page
## Expected result
1. [Example] price should display like [currency symbol][price].
## Actual result
1. [Example] Price is displays like [currency_symbol][price] for some time but changes to [currency_symbol]0,00 or 0,00 [currency_symbol]

![screenshot from 2016-04-09 14 46 12](https://cloud.githubusercontent.com/assets/10272277/14402958/e50673f4-fe61-11e5-9965-8536cea14495.png)

**Comment by yagneshponkiya** [comment]
Same issue also persist in magento 2.0.4

**Comment by Taral-Patoliya** [comment]
AAr

**Comment by mikeweis** [comment]
@Taral-Patoliya Thank you for reporting. I have created internal ticket MAGETWO-51908 to track this issue.

**Comment by Taral-Patoliya** [comment]
@mikeweis  Thank you for Acknowledging the issue, can i know how much time can we expect is needed to fix this issue? because we are building multi-lingual site and its about to be launched but we can't launch it until this issue fixed.

**Comment by mikeweis** [comment]
@Taral-Patoliya Unfortunately I don't have a good estimate on when this issue will be fixed.  It is in our active "to do" queue.  What is the timeframe of your desired launch?

**Comment by Taral-Patoliya** [comment]
@mikeweis We have already missed the deadline for the project, but managed to extend it till next week.

**Comment by Taral-Patoliya** [comment]
Hello @mikeweis,  it would be great to know if there is any progress in this issue, we are waiting eagerly to get the solution as we need to deliver the project ASAP.
Thank you.

**Comment by mikeweis** [comment]
@Taral-Patoliya This issue has been resolved and merged to develop. Feel free to let us know if you encounter any other issues.

**Comment by fazilpm** [comment]
i am also facing the same issue . i am using magento 2.1 version . can you please guide me how can we correct this issue.?
