### ISSUE TITLE
Issue with product quantity value and product availability in front end(Floating Number Issue)

### ISSUE THREAD

**Issue by santanu-brahma** [magento/magento2#408]
In current development version product quantity can be a floating number that means it can take decimal value on it. But my thought says that, it should be integer number.

If one of the product's stock quantity is 0.5, front end showing this product is available for purchase(In Stock) but after add to the cart showing "We don't have as many product as you have requested...", This is related to back-end stock quantity.

![product_quantity_bug](https://f.cloud.github.com/assets/3183444/1500206/842d6cee-4870-11e3-8219-b01ecc43f46b.png)

**Comment by tanya-soroka** [comment]
Agree with @tzyganu , it is not an issue. It is ability to sell 2.5 kg of the candy, as an example. 
p.s. Please verify the minimum QTY number on the shopping card.

Closed.
