### ISSUE TITLE
Admin - Cache Management Page,  Select All check box does not work as exptected 

### ISSUE THREAD

**Issue by duffner** [magento/magento2#4080]
## Steps to reproduce
1. Go to Cache Management Page 
2. Click on select all check box 
3. Browser Google Chrome Max OSX 10 
4. Firefox behaves similarly but slightly better.  
## Expected result
1. Click exactly on select all checkbox, all cache items would would be selected 
2. If you click above it, you will find it works.  but the checkbox itself should be what provides the dropdown. 
## Actual result
1. Clicking on select all button does nothing other then change the direction of the arrow 
2. See attached screen shots. 

Click inside checkbox 
<img width="382" alt="screen shot 2016-04-09 at 8 51 03 am" src="https://cloud.githubusercontent.com/assets/7387019/14404678/4af41eae-fe31-11e5-920c-58a142819e65.png">

Result 

<img width="376" alt="screen shot 2016-04-09 at 8 51 57 am" src="https://cloud.githubusercontent.com/assets/7387019/14404681/5682b83e-fe31-11e5-93a9-ae415bb0c9e9.png">

Where you have to click to get it to work now

<img width="397" alt="screen shot 2016-04-09 at 9 00 01 am" src="https://cloud.githubusercontent.com/assets/7387019/14404692/9dab94ce-fe31-11e5-8ec3-8ee86b8a8808.png">

**Comment by tseven** [comment]
Magento ver. 2.0.4
This is also the case on the Index Management page.
This bug did not exist in the older 2.0.2 version.

**Comment by mazhalai** [comment]
@duffner @tseven thank you for reporting, we have created MAGETWO-51803 to investigate and fix.

**Comment by piotrekkaminski** [comment]
Fixed internally. Will be published soon.
