### ISSUE TITLE
Sign in modal overlay in checkout page (iPad 2)

### ISSUE THREAD

**Issue by moe-kayali** [magento/magento2#4083]
**Browser(s)**: Google Chrome (43), Safari 
**OS:** IOS 8.3 (iPad 2)
**Magento Version**: 2.0.4 (stable)

---
## Description

Sign in modal overlay in checkout page prevents users from editing checkout form after opening then closing the sign in box. 
## How reproducible

Always
## Steps to reproduce
1. Add X product to cart.
2. Navigate to the checkout page. 
3. On the check out page, click on sign in button.
4. Click on close button. 
5. Try to fill out the checkout form.
## Expected result
1. Fill out your information normally.
## Actual result
1. It's impossible to fill out the checkout info, and the only way to proceed is to refresh the page.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53527

**Comment by alena-marchenko** [comment]
Hi @moe-kayali 

Closing the issue, fix has been delivered to develop branch.
