### ISSUE TITLE
New Product Block ajax add to cart not working

### ISSUE THREAD

**Issue by virani06** [magento/magento2#4084]
Using
vendor\magento\module-catalog\Block\Product\Newproduct
Block when i add product on home page ajax add to cart is not working

**Comment by piotrekkaminski** [comment]
@virani06 Could you provide more detailed steps how to reproduce it?

**Comment by andimov** [comment]
@virani06 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
