### ISSUE TITLE
Attributes not showing on product

### ISSUE THREAD

**Issue by OgreMHDW** [magento/magento2#4086]
## Steps to reproduce
1. Create attributes with product visibility.
2. Add attribute to product set.
3. Edit attribute in product.
## Expected result
1. Attribute to show on product view.
## Actual result
1. Attributes on product appear to be missing on frontend.

![2016-04-10_174810](https://cloud.githubusercontent.com/assets/4369476/14414251/cf85c5be-ff44-11e5-9639-59919e33510d.png)
![2016-04-10_174852](https://cloud.githubusercontent.com/assets/4369476/14414253/d1f12c4e-ff44-11e5-9780-ea0125ea33d6.png)
![2016-04-10_175025](https://cloud.githubusercontent.com/assets/4369476/14414255/d74764ba-ff44-11e5-9271-317973db472a.png)
![2016-04-10_175045](https://cloud.githubusercontent.com/assets/4369476/14414256/d94c273c-ff44-11e5-847c-8fc09f8dbc05.png)

**Comment by piotrekkaminski** [comment]
@OgreMHDW are you able to reproduce it on the latest version?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by raj1523** [comment]
hey i'm having same problem.....can anyone help me here?
