### ISSUE TITLE
Magento Community Edition 2.0.4 with Sample Data.tar.bz2 (204 MB) download is not working

### ISSUE THREAD

**Issue by avbinoy** [magento/magento2#4090]
Tried to download Magento Community Edition 2.0.4 with Sample Data.tar.bz2 (204 MB) (Third option of the dropdown) from https://www.magentocommerce.com/download and is not working. I tried from Chrome browser in Ubuntu. The archive downloaded with size 0.

**Comment by vancoz** [comment]
Hello @avbinoy thank you for your report, we created internal ticket MAGETWO-51779 and will address this issue soon. As workaround please download zip or tar.gz archives.

Thank you

**Comment by elenleonova** [comment]
Hi @avbinoy, thanks for reporting this issue. we have re-uploaded the archive, tested. and it works fine now. If you still see any issues, please, reopen the issue.
