### ISSUE TITLE
Product Option's value price empty only if set '0.00' - bug or feature?

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#4092]
Hi! 

Magento 2.0.2/2.0.4 - default settings.
1) I've created one product option (type is drop-down / required - yes) with two values:
One (Name) / 10 (Price) / Fixed (Price type) 
Two / 20 / Fixed 
2) Ok, now I want set price to 0 for first value (One).
If I write empty string or 0 a product save without any errors, but I don't see any changes in the option's value price.
If I write 0.00 option's value is change.

**Comment by antboiko** [comment]
Hi @sergei-sss , thanks for reporting this issue. I've created an internal ticket MAGETWO-51811 to track it.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
We've created internal ticket(s) MAGETWO-51811 to track progress on the issue.

**Comment by okorshenko** [comment]
Fixed in PR: https://github.com/magento/magento2/pull/11843

**Comment by ishakhsuvarov** [comment]
Closing now, as issue seems to be fixed with #11843
