### ISSUE TITLE
Product quantity appears even when there is no product in cart

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4093]
When I have no products in cart, mini cart component appears this way:

![image](https://cloud.githubusercontent.com/assets/9195659/14427242/2dbe57e2-ffca-11e5-9123-fae33856b39c.png)

This SPAN should not appear when no items exists in cart, or it could show a "0" in that location:

![image](https://cloud.githubusercontent.com/assets/9195659/14427292/664fd158-ffca-11e5-92a2-e184b530101f.png)

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/3713#issuecomment-194833549

**Comment by vzaporozhets** [comment]
@jaimestuardo - thanks for contacting us. I'm closing this issue as a duplicate. Please reply in related issue.
