### ISSUE TITLE
Magento\User\Model\User::loadByUsername does not set _origData

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#4094]
## Steps to reproduce

in magento 2.0.4, run the following code:

```
$model = $this->objectManager->create('Magento\User\Model\User');
$model->loadByUsername('administrator');
var_dump($model->getData('password'));
var_dump($model->getOrigData('password'));
$model->save();
var_dump($model->getData('password'));
```
## Expected result

password hash remains unchanged

```
string(99) "22461527d26dc0d919bf903134cd1077cca661892a0df11dfa3b04e42f6f52e9:jSlE4ccqKeyw1BTSuMtShZrq7kCpUgwz:1"
NULL
string(99) "22461527d26dc0d919bf903134cd1077cca661892a0df11dfa3b04e42f6f52e9:jSlE4ccqKeyw1BTSuMtShZrq7kCpUgwz:1"
```
## Actual result

password hash is hashed again

```
string(99) "22461527d26dc0d919bf903134cd1077cca661892a0df11dfa3b04e42f6f52e9:jSlE4ccqKeyw1BTSuMtShZrq7kCpUgwz:1"
NULL
string(99) "8b9e5e9a60cb5b897ee3908c092233365bab5c79d02d02ed0a0a7927f6a28860:EeMCtRCpCIcFFVMYgjgY2XKwoiB6KPH2:1"
```

the model checks `$_data` against `$_origData` to detect if the password needs to be encrypted, but loading the user through `loadByUsername()` does not populate the `$_origData` array.

**Comment by mazhalai** [comment]
@heldchen thank you for reporting, we have created MAGETWO-51783 to investigate and fix.

**Comment by okorshenko** [comment]
@heldchen Thank you for reporting the issue. MAGETWO-51783 merged to develop branch.
