### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by gamort** [magento/magento2#4099]
What is the point of setting up unit testing if you break it and do nothing to fix it?

https://travis-ci.org/magento/magento2/builds

Over 2 weeks for develop.  Sure, it's just the integration tests - but if you are going to decide not to include them to do not include them, don't leave the thing running day in and day out making the whole report useless.

**Comment by mazhalai** [comment]
The test that is failing is env specific. We test on Centos and it is fine, though travis runs on Ubuntu. We are in the process of fixing this. Related ticket MAGETWO-51715

**Comment by orlangur** [comment]
@mazhalai the problem here is that Travis builds are not properly involved in Continuous Integration loop. It's just a fancy badge in README and nobody really cares whether it is green or not.

Just don't publish changes until all tests are passed on Travis CI. That's it.

**Comment by gamort** [comment]
As an update - after trying to setup Magento I realized why it fails.  It is not due to the environment[at least the original error is not...  Once fixed it may well be a lot of roaches will be uncovered.]

The issue is due to the change made to Magento Connect to require an OAuth token in order to update/download non-commercial packages - such as all the magento modules.

It's masked by the completely stupid decision to return a 404 error to unauthorized connections instead of an unauthorized error code.

If, and this is a big if, one assumes that all the magento/\* entries in the composer config file are in this repository - then for travis you just need to make sure whatever process is used to check those packages is skipped:
https://github.com/magento/magento2/blob/develop/composer.json

**Comment by gamort** [comment]
@orlangur   I generally don't pay much attention to the Travis CI badge in the dev branch - just the release branch. 

If there are new releases of an application system being made while the unit test badge is showing red - it's a good indication that the application being released has security issues and major bugs.

Honestly, I'm content with a vendor that simple 'hides' the issue by disabling the test.  In many cases, such as this one, the initial failure was not due to a change in the code itself - but because of an issue with changes to the access policies for the magento repositories.  At least if they go to the trouble of disabling it - it means they are actually paying attention to the unit tests.  If they do not even address the issue - it means the unit tests are not really being used and are just there for marketting.

Of course, I've been coding long enough to remember when the PHP team had to make a new point release  just to fix a bug that they should have known was there.  There was a unit test for that specific issue.  The unit test results were publicly available and they clearly showed that the unit test had suddenly started failing when the release code was staged for release.  Ignoring unit test failures results in security issues and is inexcusable.

If you have false positives, then disable those tests.  Better to have fewer tests that are always checked then to test everything but ignore it.

**Comment by mazhalai** [comment]
@gamort @orlangur This is not the forum to discuss 'process', I would suggest to take it up in community.magento.com boards. This issue tracker is mainly for bugs. 

PS: Unit tests are fine on Travis, it is integration tests that are broken.

**Comment by orlangur** [comment]
Hi @mazhalai,

> This is not the forum to discuss 'process', I would suggest to take it up in community.magento.com boards. This issue tracker is mainly for bugs.

Are you trying to say that GitHub is not a right place to discuss a buggy GitHub usage process?

In my humble opinion, continuously red builds are a huge problem for developers trying to use Magento 2 and it should be solved in general. Not in reactive, always catching up way.

**Comment by mazhalai** [comment]
@gamort a fix has been merged, hence closing this ticket. Please feel free to create a new issue if problems persist.
