### ISSUE TITLE
CMS blocks are stripping 'placeholder=""' html attributes

### ISSUE THREAD

**Issue by samtay** [magento/magento2#4100]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a cms block with content `<input name="test" placeholder="THIS TEXT WILL DISAPPEAR" />`.
3. Save the block.
4. ![2016-04-11-131432_1887x907_scrot](https://cloud.githubusercontent.com/assets/7246591/14435811/aa61f106-ffe7-11e5-931e-f84072631533.png)
## Expected result
1. Content saved normally.
## Actual result
1. Placeholder text is stripped out of content.
2. 
   ![2016-04-11-131453_1895x911_scrot](https://cloud.githubusercontent.com/assets/7246591/14435826/c06e6894-ffe7-11e5-8ddc-95d75ec3d516.png)

**Comment by samtay** [comment]
Note: I believe this problem is resolved by disabling the wysiwig editor, which my team does by default, but that solution might not be viable for everyone.

**Comment by grasdaggel** [comment]
How to disable the WYSIWYG-Editor by default?

**Comment by samtay** [comment]
@kingalca Stores > Configuration > General > Content Management > WYSIWYG Options

**Comment by grasdaggel** [comment]
Thanks mate

**Comment by shiftedreality** [comment]
Hi @SamTay 

I created internal issue MAGETWO-51899
Thank you for submision

**Comment by shiftedreality** [comment]
Fix was delivered to mainline.
Closed.
