### ISSUE TITLE
REST API endpoint: GET /V1/products/attribute-sets/{attributeSetId}/attributes does not works

### ISSUE THREAD

**Issue by dmitriyse** [magento/magento2#4103]
## Steps to reproduce
1. Install Magento 2.0.4 or 2.0.2 with sample data
2. Perform valid call to the endpoint: GET /V1/products/attribute-sets/{attributeSetId}/attributes
## Expected result
1. List of attributes belongs to the specified attribute set

Actual result
![image](https://cloud.githubusercontent.com/assets/10322215/14445945/4763ac9a-0062-11e6-8387-ef7b044911bc.png)

[2016-04-11 23:54:15] main.CRITICAL: exception 'ReflectionException' with message 'Report ID: webapi-570c392788b00; Message: Class  does not exist' in /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(ReflectionException))
#1 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(ReflectionException))
#2 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by mazhalai** [comment]
@dmitriyse thank you for reporting, we have created MAGETWO-51844 to investigate and fix

**Comment by okorshenko** [comment]
@dmitriyse thank you for reporting the issue. In scope of this commit https://github.com/magento/magento2/commit/c001fb981ed36179e4a0ea409c026c112d83b6a5 described issue was fixed.
