### ISSUE TITLE
REST API - Product categories always updated, even "category_ids" attribute not specified

### ISSUE THREAD

**Issue by dmitriyse** [magento/magento2#4104]
## Steps to reproduce
1. Install Magento 2.0.4
2. Create new product and specify some categories for it.
3. Update product but without "category_ids" custom attribute
## Expected result
1. Categories of the updated products are not updated
2. ...
## Actual result
1. All categories reseted
   ![image](https://cloud.githubusercontent.com/assets/10322215/14446189/5cca0000-0064-11e6-8e5b-a10a534f6c73.png)

![image](https://cloud.githubusercontent.com/assets/10322215/14446170/33595040-0064-11e6-91e4-3e31fff0d91c.png)

---

Fix suggestion. Also add category_ids attribute to the rest/V1/products query result. It will simplify third party software integrations.

**Comment by mazhalai** [comment]
@dmitriyse Thank you for reporting, we have created ticket MAGETWO-51845

**Comment by kodmaskinen** [comment]
Related: https://github.com/magento/magento2/issues/3354

**Comment by kandy** [comment]
Updates of entity in Magento API implemented with "Replace" strategy, not "Patch". So you should send full entity.
