### ISSUE TITLE
REST API endpoint: GET /V1/categories/{categoryId}/products sometimes returns wrongly empty list

### ISSUE THREAD

**Issue by dmitriyse** [magento/magento2#4105]
## Steps to reproduce
1. Install Magento 2.0.4
2. Create Root Category from REST API
3. Bind this category to some product
4. Perform request to the endpoint:  GET /V1/categories/{categoryId}/products for created category in the second point.
## Expected result
1. List of 1 product should be received
2. ...
## Actual result
1. Empty list received

**Comment by mazhalai** [comment]
@dmitriyse thank you for reporting, we have ticket MAGETWO-51846 to investigate a fix.

**Comment by mazhalai** [comment]
@dmitriyse can you please give us more details, we haven't been able to reproduce this issue.

**Comment by mazhalai** [comment]
@dmitriyse closing as non responsive

**Comment by hemendraajmera** [comment]
This API Still not working
