### ISSUE TITLE
DHL and FedEx tracking not working

### ISSUE THREAD

**Issue by colyield** [magento/magento2#4109]
We are using FedEx shipping module to quote the shipping cost. And we did not configure the DHL module but occasionally we will ship orders by DHL.

 For the order shipped by DHL, when click "track order" link on admin, The DHL tracking always show the message below and there's no further information.
Tracking Number:    111
Carrier:    DHL
Error:  Tracking information is currently not available. 

For the order shipped by FedEx, When click "track order" link on admin, it shows error on the popup window. The error is:
"....Undefined property: stdClass::$ActualDeliveryAddress in /var/www/html/vendor/magento/module-fedex/Model/Carrier.php on line 1075";i:1;s:11684:"#0 /var/www/html/vendor/magento/module-fedex/Model/Carrier.php(1075): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/www/html...', 1075, Array)

The magento version is 2.0.4 on Centos 6 server, Apache 2.4, php5.6.  Please advise.

**Comment by colyield** [comment]
I don't know what happened, but the Fedex tracking seems work now, for both my production website and a test website. The DHL tracking is still the same problem.

**Comment by YevSent** [comment]
@colyield, thanks for your report. Can you enable debug mode for DHL and post response from DHL in this issue.

**Comment by YevSent** [comment]
Also, related to [DHL Tracking documentation](https://xmlpi-ea.dhl.com/) the `AWBNumber` should be 10 digits, you use 3 digits.

**Comment by colyield** [comment]
@joni-jones First of all, whatever the AWBnumber I input into the system, when I track the shipment, the tracking number shown on the page is always 111. I enabled debug, and here is  the error. I am not sure why the tracking shows 111. Do I have to set up the DHL shipping module in the system? As I mentioned, we did not configure the DHL module but occasionally we will ship orders by DHL.

`  'request' => '<?xml version="1.0" encoding="UTF-8"?>
<req:KnownTrackingRequest xmlns:req="http://www.dhl.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com TrackingRequestKnown.xsd"><Request xmlns=""><ServiceHeader xmlns=""><SiteID></SiteID><Password></Password></ServiceHeader></Request><LanguageCode xmlns="">EN</LanguageCode><AWBNumber xmlns="">1374618070</AWBNumber><LevelOfDetails xmlns="">ALL_CHECK_POINTS</LevelOfDetails>/req:KnownTrackingRequest
',
  'result' => '<?xml version="1.0" encoding="UTF-8"?>
<req:ShipmentTrackingErrorResponse xmlns:req="http://www.dhl.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com track-err-res.xsd">
    <Response>
        <ServiceHeader>
            <MessageTime>2016-04-21T21:50:20+01:00</MessageTime>
        </ServiceHeader>
        <Status>
            <ActionStatus>Failure</ActionStatus>
            <Condition>
                <ConditionCode>111</ConditionCode>
                <ConditionData> Error Parsing incoming request XML
                    Error: Datatype error: In element &apos;SiteID&apos;
                    : Value &apos;&apos; with length &apos;0&apos; is
                    less than minimum length facet of &apos;6&apos;.. at
                    line 2, column 237</ConditionData>
            </Condition>
        </Status>
    </Response>
/req:ShipmentTrackingErrorResponse

',
) {"is_exception":false} []`

**Comment by colyield** [comment]
It seems the DHL module have to be configured. I just applied DHL account and hopefully will get it set in a few day.s

**Comment by YevSent** [comment]
@colyield to use DHL tracking at first you must configure DHL shipping carrier in Magento Admin panel. Otherwise it will not be work.

**Comment by colyield** [comment]
Is there anyway to bypass the module configuration? I just want to track the packages. But it seems it's impossible to get a DHL account just for tracking.

**Comment by YevSent** [comment]
No, you need DHL credentials to use this module.

**Comment by alena-marchenko** [comment]
Hi @colyield 

Closing the issue, please feel free using [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for further questions.

**Comment by googelie** [comment]
We are experiencing the same problem.. always 111 as tracking id. I Think the only way would be to edit the admin customer order overview and add the tracking link and at the end the tracking id as variable
