### ISSUE TITLE
Responsive not working with Device under 480px

### ISSUE THREAD

**Issue by zin-mi** [magento/magento2#4110]
Hi Everyone.
I'm tried made Magento responsive for a device under 320 but it was not working.
here the my code:

```
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__xs) { 
  Code right here for under 320px; @screen__xxs: 320px;
}
```

Please let me know how to input code to only this device. I'm tried many time but it not success.

Many Thanks

Best Regards,
Ziven.

**Comment by zanilee** [comment]
Hi, @zivendesign!

Thank you for reporting this issue.
Internal ticket MAGETWO-51886. While the fix is delivered, you can do a quick-fix for your theme by [adding 320px breakpoint to your theme](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/responsive-web-design/rwd-breakpoints.html)

**Comment by MomotenkoNatalia** [comment]
@zivendesign Internal ticket  MAGETWO-51886 is closed and delivered to mainline. Please let us know if you still have an issue.

**Comment by zin-mi** [comment]
Hi @MomotenkoNatalia ,
Here my code and it not working in the breakpoint under 480px with Magento Breakpoint default

```
//
//  Mobile vertical
//  _____________________________________________

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__xs) {
    .minicart-wrapper .block-minicart {
        padding-top: 10px;
    }
}

//
//  Mobile
//  _____________________________________________
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__s) {
    .minicart-wrapper .block-minicart {
        padding-top: 0px;
    }
}
```

The padding still: padding-top: 0px when i switch to device under 480px.
Please let me know how to resolve it.

Best Regards,
Ziven.

**Comment by zin-mi** [comment]
@zanilee,
I'm still having problem about the breakpoint you said still not working. I'm tried much time but still not the success. 
Please let me know how to resolve or have some sample working fine. 

Many Thanks.

Best Regards,
Ziven.

**Comment by andidhouse** [comment]
hi there,
in version 2.1 this bug is present? Is this not fixed?

**Comment by zin-mi** [comment]
Yes @andidhouse.
It Still and No one tells me the Solution and Reply about it. 
Best Regards,
Ziven.

**Comment by andidhouse** [comment]
@MomotenkoNatalia 

Why is this issue closed if it is not fixed in a newer release. 
It is now over 3.5 month... Can someone pls point out a workaround or when this issue will be fixed?

Thanks!

**Comment by edwinknol-mediact** [comment]
I've added:
@media all and (min-width: @screen__xxs) {
     .media-width('min', @screen__xxs);
}

@media all and (min-width: @screen__xs) {
     .media-width('min', @screen__xs);
}

on:
line 50

to:
lib/web/css/source/lib/_responsive.less (needs to be copied to yout own theme)

And now i'm able to use @screen__xxs and @screen__xs with the "min" statement.

**Comment by kondzerau-ivan** [comment]
If we work with theme - ok, I can copied _responsive.less from lib. But when we customize module without access to the theme files, what can we do in that case with xxs, xs?
