### ISSUE TITLE
Layered navigation shows attributes within wrong categories

### ISSUE THREAD

**Issue by devhn** [magento/magento2#4111]
We are experiencing strange issue with attributes within the layered navigation. It shows all attributes in the sidebar even tho they are not be assigned to certain type of products.

What we did:
1. Installed Magento community without sample data
2. Configured product attribute sets and attributes
3. Created 1.000+ products within Magento administration
4. Imported product's pictures (admin GUI)
5. Updated product's stock with a script (attached file)
   [StockPriceUpdateCommand.php.zip](https://github.com/magento/magento2/files/214646/StockPriceUpdateCommand.php.zip)

What happend:

After these steps the layered navigation on frontend category displays all attributes in the sidebar on all categories instead showing the attributes of the products that are in the particular category. For example:
- we have categories Balls and Squares
- if we navigate to Balls the category listing displays correctly all the balls products
- in the sidebar layered navigation shows all the attributes from both Balls and Squares
- one of the attributes shown is "Square edges" which should be displayed only in the Square category. It shows N products avaliable within the Balls category
- if we click the attribute "Square edges" it filters the products from the Balls category

In the Magento administration the attribute set and product attributes are showing fine and properly organized. Each product has correct assigned attribute set. Each attribute set has correctly assigned attributes.

**Comment by devhn** [comment]
Any news on this? If it's a bug it's a major issue which should have a high priority.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53444

**Comment by vzabaznov** [comment]
Hi @devhn  issue was closed and delivered, please check latest magento version, thanks for contributing
