### ISSUE TITLE
Options missing in Configuration > General > Design

### ISSUE THREAD

**Issue by nobuttsalex** [magento/magento2#4115]
**Steps to reproduce**
I am on the develop branch with no extensions enabled, the only options under the Design menu is the Search Engine Robots section

**Expected result**
![design expected](https://cloud.githubusercontent.com/assets/9484573/14458300/25af019e-00a8-11e6-9e55-22e9fe17117d.png)

**Actual result**
![design actual](https://cloud.githubusercontent.com/assets/9484573/14458303/2839e460-00a8-11e6-956b-da04e1302141.png)

**Comment by antboiko** [comment]
Hello @nobuttsalex , thanks for your inquiry.

Theme Management functionality was moved to Admin >> Content >> Design >> Configuration.

I'm closing this ticket for now, please feel free to reopen if you have any additional questions.

Best,
Anton.
