### ISSUE TITLE
Minicart : duplicate micart cart item display in multiple project's minicart on same local server.

### ISSUE THREAD

**Issue by parthviroja** [magento/magento2#4118]
I have install 2 project (Magento-CE.2.0.0) on my local server. 

When i open **project("demo")**, and add 2 item in cart (minicart render with **2 item** perfectly).

When i open **project("test")** (minicart display **2 item** of project(demo).

I think issue with session / cache..

Anybody knows how i can fix / solve this problem ?

**Comment by ishakhsuvarov** [comment]
@parthviroja Do you have same domain for both projects? Mini cart contents are cached in browser's `localStorage` per domain.

**Comment by parthviroja** [comment]
Yes, i m working on same local server Ex: 192.168.0.100/<project 1> , 192.168.0.100/<project 2>.

Any way to solve this issue ? , i am working as magento 2 extension developer, just guide me than i will try to fix this issue..

**Comment by ishakhsuvarov** [comment]
@parthviroja Looks like you are experiencing this issue because mini cart contents are cached inside browser's localStorage per domain. Try using some local domains for each Magento installation to solve this.

**Comment by parthviroja** [comment]
Thanks @ishakhsuvarov
