### ISSUE TITLE
Support multiple currencies without conversion

### ISSUE THREAD

**Issue by FiveDigital** [magento/magento2#412]
Our customers often want to use multiple currencies within one website. With Magento 1 this is only possible with currency conversion. This makes some ugly prices in any but the default currency and our customers want to set the prices in every currency independent form the default currency. e.g. 100€ and 140$, not 100€ and automatically converted 134,62$ according to the current rate.

Are there any plans to extend Magento's handling of currencies to support multiple currencies in this way? This would give us developers the possibility to set a customer's   currency based on it's IP address or to change the currency according to the billing (or shipping) country. This features are often requested by our customers and it would be great it things become possible with Magento 2.

**Comment by choukalos** [comment]
Who else is using the Advanced Pricing module or something similar to set prices by currency for a store view?

What are the customer use cases for this - how many different currency's would one need to support?  It seems this is an ask for multiple groups of customers who speak the same language, have the same tax rules applied to them but want the flexibility to see the store pricing in their currency - is that right?  

Right now Magento allows us to change pricing (along with currency, tax configuration) at the website level ( along with define store views ).  Why wouldn't you have a website for customers using Euro and one for customers using $'s, etc?  You can even have various store views localized languages ( EU site could have German, French, English; US website could have English; etc ).

@FiveDigital, @ihor-sviziev, @akulkarni9 can you shed some light on the value for this ask?  As an alternative idea what if pricing could be changed at the store view level; would that work?

**Comment by akulkarni9** [comment]
@choukalos: Please check the magento module written by me.
https://github.com/akulkarni9/multiplecurrencies
It allows multiple currencies at product level and it is opensource module, feel free to download it and use it :+1:

**Comment by Vinai** [comment]
On a project product prices where displayed in EUR and also in USD at the same time.

**Comment by choukalos** [comment]
Thanks @akulkarni9 for the link to your module; am I correct in assuming this only displays multiple currencies for product pages?  The category, cart, orders, invoices, etc pages would show the website display currency ( set by store view ).

Questions
All
*Are these smaller merchants or merchants who's traffic is from multiple countries to one website and they're looking for an easy way to display prices in native currency for those customers?  Are those customers using the store view selector to change to their preferred language?  Does this make a big difference in conversion rate?
*What price/currency was used when product was added to cart?  Order? Invoice?
*Regardless of the displayed price what currency & tax settings is the merchant using for their accounting records - is that the website currency/tax settings?
*How many merchants have you-all created customizations or used @akulkarni9 extension or similar for this feature?
*If we were not to build this feature in core but wanted to make it easy for an extension developer to provide this functionality is there anything we should change?

Thanks,
Chuck

**Comment by FiveDigital** [comment]
In our project where we hat to build around this problem the customer has one shop (website in Magento's language) for the whole world. It was not possible to work with multiple websites because of the customer's requirements. The customer has around 200.000 orders per year. So it's not a really a small merchant ;-)

The logic behind the customer needs was that the billig address' country determines the currency. So if the customer is from the USA the $ price is displayed and if the customer is from Europe the € is displayed and so on. So setting the price on store view level won't help in this case. 

Since the tax is already based on the customer's address that was no problem at all.

**Comment by choukalos** [comment]
@FiveDigital if you've got a US customer ($'s) and a German customer (Euros) how is your tax engine configured ( I believe it's illegal to show prices that aren't final, i.e. include tax, or are not consistent across the customer's experience in Europe )?  

Asking because In the US you have to calculate tax's based on cart total - in Europe you have options ( believe there are some nuances by country though ).  

Thanks,
Chuck

**Comment by FiveDigital** [comment]
Since the project was some years ago I'm not quire sure how it was configured. But I no we had to deal with things like California sales tax and so on and perhaps we also changed the including/excluding logic, too to make it depend on the country, too.

**Comment by stefan68** [comment]
Hi guys, 
I recommend Multiple Store View Pricing Extension that will meet your need.
Check it out here: 
For Magento 1: http://bsscommerce.com/magento-multistore-pricing.html
For Magento 2: http://bsscommerce.com/magento-multiple-store-view-pricing-for-magento-2.html

Hope it helps!

**Comment by magento-engcom-team** [comment]
Hi All, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
