### ISSUE TITLE
No Error Messages displayed on /customer/account/create/

### ISSUE THREAD

**Issue by philippsander** [magento/magento2#4120]
When creating an account with an email that already exists, i should see an error message.

But the page just reloads and I don't see anything.

The message div is there. but empty.
module-customer/Controller/Account/CreatePost.php is not overriden
The Exception block which adds the error-message to the messageManger in CreatePost.php, is reached.

There's a Javascript error, when loading the page: Uncaught Error: [object Object] in customer-data.js :49

**Comment by philippsander** [comment]
It's a problem with my installation. I can't access /customer/section/load/ while logged out.

**Comment by br0k3n** [comment]
Hi, how did you solve it?

Thanks

**Comment by philippsander** [comment]
@br0k3n It was a problem with my code. I installed restricted the access to /customer/section/load/ ifyour not logged in unintenionally
