### ISSUE TITLE
File Permission Check "/var/www/html/magento/pub/static" writable directory permission.

### ISSUE THREAD

**Issue by alejduin** [magento/magento2#4122]
Hello, I've been trying to install a Magento2 theme when I upload the files to the magento server an I go to http://<my server>/magento/themesetup I can see the theme setup landing page, then it realize a Readiness Check and there is when I get the error message.

To solve this I try this:

$ sudo chmod 777  /var/www/html/magento/pub/static

$ sudo chmod 777 -R /var/www/html/magento/pub/static

but the permissions error persists.

What should I do?

**Comment by mazhalai** [comment]
@alejduin Can you please give more details? You are installing a theme first and then Magento?

**Comment by alejduin** [comment]
nop, I have a Magento2 running and then I try to install the theme, i upload the files via SFTP, then I go to  http:///magento/themesetup, there is where I see the theme landing page, but when the theme configuration checks the permissions it says: File Permission Check "/var/www/html/magento/pub/static" but i have no changed any permission.

**Comment by mazhalai** [comment]
@Not sure about this path. `http:///magento/themesetup` the right way to install a theme, is to go to `Admin->System-> Web Setup Wizard->Component Manager`  Add your credentials in "System Config", then follow instructions [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/compman-main-pg.html) to install a component(in this case theme).

**Comment by alejduin** [comment]
this is the some lines of the documentation of the theme

2.2. INSTALLING THEME AFTER MAGENTO IS PREPARED

This procedure doesn’t change core files of Magento
Step 1: Extracting file theme package on your computer and copy all files to your Magento folder. The theme folder after extracting, it should contain folders such as: app, pub.

Step 2: Using your FTP client upload all folders and files to your Magento's root directory Magento already contains the same directories - do not remove those directories. (You can upload your files to server by using Filezilla.) Directories extracted from theme package have to be merged with existing directories of Magento. If your system asks you whether you want to merge directories, you can confirm that you want to merge those directories.

Step 3: Set correct file permissions for folders as below

Step 4: Running the Setup Wizard , it is a multi-page wizard that enables you to go back and forward one page at a time.

Getting started
To install the Magento software using the Setup Wizard:

Start a web browser.
Enter the following URL in the browser’s address or location bar: http://<Magento host or IP>/<path to Magento root>/themesetup
For example, if the Magento server’s IP address is 192.0.2.10 and you installed Magento 2 in the magento2 directory relative to the web server’s docroot, and you did not configure a Virtual Host, enter: http://192.0.2.10/magento2/setup On the initial page, click Agree and Set Up Magento.

Step 5: Active our theme. Please read more details at : this link

Step 6: Set Homepage. Please read more details at : this link

Step 7: Flush Magento cache : this link

To activate and use layout which you like, you please go to content of each theme below:
1. Fashion
2. Shoes
3. Sunglasses
4. Jewelry

**Comment by mazhalai** [comment]
@alejduin where is this from?

**Comment by alejduin** [comment]
Extreme Magento Themes, it was inside the zip that I bought with the  em theme, I really thought that it would be like you wrote in the previous comment, but they documentation recommends that process. :-(

**Comment by mazhalai** [comment]
@alejduin I think you should take it up with them. Maybe they need to update their documentation.

**Comment by mazhalai** [comment]
Closing since this is not a bug.

**Comment by vtransy** [comment]
you can follow this post to set right permission for user to run Nginx and php
https://mrvts.wordpress.com/2018/08/11/how-to-develop-magento-2-with-nginx-without-sudo-chmod-777-for-var-pub-and-generation-directory/
