### ISSUE TITLE
Magento\Framework\Model\AbstractModel->save() is deprecated. What i should use instead of that?

### ISSUE THREAD

**Issue by benbor** [magento/magento2#4123]
Hi guys. Since that https://github.com/magento/magento2/commit/02b9213e4468bfa765ecc38ee55657662554fd72 commit AbstractModel->save() method is deprecated. Please someone tell me, what i should use for save it ?

**Comment by antonkril** [comment]
For now, you should use `ResourceModel->save()`. Entity should not have persistence operations, so this method was deprecated.

**Comment by benbor** [comment]
Big thanks.

**Comment by jreinke** [comment]
> Entity should not have persistence operations, so this method was deprecated.

I agree but this could have been realized before...

**Comment by JanisE** [comment]
Is there an example anywhere of how to actually use ResourceModel?

**Comment by antonkril** [comment]
Here is the example for save: https://github.com/magento/magento2/blob/2.0.0/app/code/Magento/Catalog/Model/ProductRepository.php#L609

**Comment by antonkril** [comment]
@jreinke, the approach with persistence on models was implemented 10 years ago.

**Comment by JanisE** [comment]
Still, your example uses "load" which also is deprecated: https://github.com/magento/magento2/blob/2.2.0/app/code/Magento/Catalog/Model/ProductRepository.php#L271

**Comment by JanisE** [comment]
Thanks for the example! I was looking at the (hopefully simpler) newsletter and review module cases, but they used the deprecated approach.

Still, your example uses "load" which also is deprecated: https://github.com/magento/magento2/blob/2.2.0/app/code/Magento/Catalog/Model/ProductRepository.php#L271
