### ISSUE TITLE
No images Magento Admin Panel

### ISSUE THREAD

**Issue by QuestionProGuy** [magento/magento2#4124]
i don't see any image on my Magento Admin Panel , i hope anyone knows what the problem is .
![magentoerror](https://cloud.githubusercontent.com/assets/18424218/14466355/c3ce95e6-00d6-11e6-96ae-7d16e124fed5.JPG)
![magentoerror2](https://cloud.githubusercontent.com/assets/18424218/14466361/c9646882-00d6-11e6-9c4f-a5a85bf1b8e2.JPG)

**Comment by QuestionProGuy** [comment]
Wait i solved the problem , all images are working now !

**Comment by Richardmaximun** [comment]
Hi @QuestionProGuy .

Want you share the solution? I have the same issue.

Thanks
