### ISSUE TITLE
handle custom map requirejs scripts not loading

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#4125]
``` javascript

var config = {
         map: {
                '*': {
                       "productGallery":   "Magento_Catalog/js/product-gallery",
                        "baseImage":        "Magento_Catalog/catalog/base-image-uploader"
                },
                '#mycustomcontainerdiv': {
                       "productGallery2":   "Vendor_CustomModule/js/product-gallery",
                       "baseImage":        "Vendor_CustomModule/js/base-image-uploader"
                }
         },
         paths: {

          },
          shim: {
                'productGallery2': {
                   deps: ['baseImage']
                }
        }
    };
```

Script called in PHTML like original 

``` html
<div id="mycustomcontainerdiv">
<div data-mage-init='{"productGallery2":{}}'> </div>
</div>
```

I already clear static files, caches , generation and re-deploy. After that magento still not load my script. How to make it work. Can i temporary disable original script productGallery for only in custom module?

**Comment by mrtuvn** [comment]
FIxed. Problem come from wrong permission in pub/static/.htaccess file
I already modify file `requirejs-config` to simple and clear

``` javascript
var config = {
    "map": {
        "*": {
            "productGallery2":   "Vendor_CustomModule/js/product-gallery"
    }
    }
};
```

**Comment by piotrekkaminski** [comment]
@mrtuvn can you clarify what is the error in .htaccess file?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
