### ISSUE TITLE
Confused with the Documentation in creating custom components and modules

### ISSUE THREAD

**Issue by Toltar** [magento/magento2#4126]
Hello I am excited to start learning how develop within the Magento Framework. I just started Magento and got everything installed. Now I am wanting to customize Magento to what my work wants it to do. One example of these things is to create custom Reports from the admin panel. I have very carefully read your documentation and other online sources saying though one step is stumping me and I have no idea to do it. 

[As Stated Here](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/build/required-configuration-files.html) 

that there is a directory that exists `<Magento Install Directory>/app/code/` but within my install I do not see it at all. It also mentions that while not recommended that you can develop components in the `<Magento Install Directory>/vendor/` directory. Every online tutorial goes by the `/app/code` directory(since of coarse it is the recommended method). Although one problem, I do not have such a directory. I am confused as to if Magento should have auto generated it or I have done something wrong with the installation process. I even "set up this type of environment by Cloning the Magento 2 GitHub repository."(as stated in the documentation)

So to create my custom reports module, should I create the `code` directory within `app`? Have I done anything wrong? Am I misinterpreting the documentation itself?

I hope I am posting this issue within the right place(If I am in the wrong place, please notify/point me to where I can ask). Please let me know if you need further information or assistance. I thank everyone in advance for their contributions in helping me out.

_System Specification Information_
Magento 2.X (I forgot exactly but its 2.X for sure)
Ubuntu 15.10 (I am running a VM in VirtualBox)

edit: Fixed the link text

**Comment by mazhalai** [comment]
@Toltar how did you deploy Magento2? via git? composer create-project or downloaded a zip from magento.com?  If you used any other method other than git, yes, you do have to create a `code` folder under `app`. If you deployed via git, it should already be present. 

@xcomSteveJohnson maybe documentation needs to be updated to specify that `code` needs to be created within `app`?

**Comment by Toltar** [comment]
Yes I deployed Magento2 via composer and git. Thank you @mazhalai for clarifying about the code directory. I do agree that the documentation should be updated so there is less abstractions. Would you like me to as I go through the tutorial process and write comments on the issues of the documentation as I go along? Maybe I hope I can help by bringing up issues with the documentation.

**Comment by mazhalai** [comment]
@Toltar yes! You could also submit a PR to https://github.com/magento/devdocs

**Comment by Toltar** [comment]
Great! I hope I can help make the documentation a big easier for first time users so it's attractive to more people to use. And thanks @mazhalai for the help, I hope to repay the favor. (0.0) :+1:
