### ISSUE TITLE
Fatal error when page.messages block removed from xml

### ISSUE THREAD

**Issue by mstumpf818** [magento/magento2#4127]
## Problem

A fatal error occurs on /customer/account/edit/ when page.messages block is removed from xml.  
Fatal error: Call to a member function setEscapeMessageFlag() on boolean in vendor/magento/module-customer/Controller/Account/Edit.php on line 83
## Steps to reproduce
1. Install stable Magento CE (we're using 2.0.2).
2. Remove page.messages block.  You can do this in the theme xml file app/design/frontend/{Theme Maker}/{Theme}/Magento_Theme/layout/default.xml by adding 
   `<referenceBlock name="page.messages" remove="true"/>`
3. Create user account on frontend and go to /customer/account/edit/
4. The stack trace occurs if you are in development mode, otherwise you see the white screen of death
## Expected result
1. Code doesn't crash and either fails gracefully or creates an empty block dynamically
## Actual result
1. Fatal error: Call to a member function setEscapeMessageFlag() on boolean in vendor/magento/module-customer/Controller/Account/Edit.php on line 83

**Comment by slavvka** [comment]
Hi @mstumpf818, thank you for reporting the issue. The internal ticket MAGETWO-51887 has been created.

**Comment by piotrekkaminski** [comment]
Raised priority of this issue

**Comment by slavvka** [comment]
@mstumpf818, the issue has been fixed and delivered to develop. Please see fe12b4d
