### ISSUE TITLE
"You cleared the comparison list" message does not disappear.

### ISSUE THREAD

**Issue by redinn** [magento/magento2#4128]
Preconditions
1. Magento 2.0

Steps to reproduce
1. Install Magento 2.0.4
2. Add products to compare.
3. Click "Clear All" to remove products from comprision list

Expected result
1. "You cleared the comparison list" message pop up only once.

Actual result
1. I continue to browse other pages on my site and "You cleared the comparison list" message does not disappear.

Could someone please have a look at it. Not sure if there was a similar issue in past..
Thanks.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53442

**Comment by magento-engcom-team** [comment]
@redinn, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
