### ISSUE TITLE
Shopping cart page not loading

### ISSUE THREAD

**Issue by BorysMiller** [magento/magento2#4133]
Steps to reproduce

1.Add module with sequence of 'Magento_Checkout' module.
2.Go to '/checkout/cart': page not load (white screen).

**Comment by ishakhsuvarov** [comment]
@BorysMiller Hi, thank you for reporting. Is there anything else module from step 1 does? Any changes to database schema or data? Any plugins, etc?

**Comment by BorysMiller** [comment]
@ishakhsuvarov Hi, there are no other modules from step one, no changes in database...

I have checked it with simple module, that consists only of two file: 'registration.php' and 'etc/module.xml' with following content:

``` xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="My_Checkout" setup_version="1.0.0">
        <sequence>
            <module name="Magento_Checkout"/>
        </sequence>
    </module>
</config>
```

**Comment by piotrekkaminski** [comment]
@antonkril can you look into it?

**Comment by irenelagno** [comment]
@BorysMiller . I don't have an ability to reproduce this issue on current develop branch. I created 3 files: registration.php, composer.json, and etc/module.xml. Could you provide more details about your issue?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by ravi1610** [comment]
i am facing the same issue.
