### ISSUE TITLE
Account signin popup after adding discount coupon

### ISSUE THREAD

**Issue by mjcutter** [magento/magento2#4135]
Steps to reproduce
1. Using Magento 2.02
2. Add product to cart. Go to checkout (not signed in to site)
3. Add discount coupon at first screen. Click Proceed to Checkout

Expected result
1. Arrive at next screen to enter email address and shipping address

Actual result
1. Popup modal to sign in to site or create new account if you click 'Proceed' button too quickly. 
2. If you wait about 5 seconds after adding a coupon before you click the button everything works correctly. 

Only appears to happen if you add a discount coupon - if you don't, moves on correctly. It's the waiting that gets me - I can't write a paragraph on there saying 'count to 10 before you click this button'. I'm unclear how the action changes during the waiting!

**Comment by parekhreena** [comment]
In Magento 2.0.2 it happens for me with as well as without discount. Issue details here #3966

**Comment by piotrekkaminski** [comment]
@mjcutter @parekhreena does it happen on latest version? seems the related issue is closed. If yes, please create a new issue.
