### ISSUE TITLE
product weight

### ISSUE THREAD

**Issue by MicroKloon** [magento/magento2#4137]
I have loads of products where the weight of each item is just a gram or even less. How can I add the proper weight?
Now the backend will not let me add a weight less then 10 grams.

**Comment by mbrinton01** [comment]
@MicroKloon does this answer your question about how to configure weight for your products? http://magento.stackexchange.com/questions/24659/magento-what-is-the-minimum-weight-a-product-can-weigh-and-its-corresponding-fo/

**Comment by MicroKloon** [comment]
It does answer it somewhat.
But I already found the solution, I switched to WooCommerce and everything works great.
Thank you for your kind answer.

**Comment by mbrinton01** [comment]
@MicroKloon thank you for following up, I will close this issue
