### ISSUE TITLE
Incorrect CAPTCHA by user loses form entries.

### ISSUE THREAD

**Issue by AirmanAJK** [magento/magento2#4138]
## Steps to reproduce

Turn on CAPTCHA (Stores -> Configuration -> Customers -> Customer Configuration -> CAPTCHA)
Enabled: Yes
Forms: Contact Us
Displaying Mode: Always

Visit the Contact Us page on the front end.
Spend several minutes carefully writing a detailed message for the store owner.
Entering an incorrect CAPTCHA loses all the form data.

**Comment by mazhalai** [comment]
@AirmanAJK  Thank you for reporting, we have created ticket MAGETWO-51898 to investigate and fix.

**Comment by shiftedreality** [comment]
Fix was delivered to develop branch.
Closed.
