### ISSUE TITLE
Magento 2.0.4 Multiple Items added to Cart cause 0 shipping rates

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#4139]
When adding more then 1 items or more than 1 of the same item to the cart, when visiting the checkout the shipping rates returned are $0

Steps to reproduce.
1. As a guest add an item to the cart and visit the checkout. You will see the shipping rates as Flat rate and Best Way (5 and 15 respectively).
2. Go back to the store and either add a new item to the cart or update the quantity of your original item to 2.
3. Re-visit the checkout page - you will see the shipping rates for both Flat Rate and Best Way are set to $0

**Comment by alena-marchenko** [comment]
Hi @Zaylril 
Please specify Magento version that you are using and specify type of products added to the cart for us to be able to investigate the issue further.

**Comment by piotrekkaminski** [comment]
Closing due to lack of response. If you have same issues please open a new issue.

**Comment by tylerd92vn** [comment]
I have the same problem. Is this problem fixed?

**Comment by joedin51** [comment]
I have the same problem. shipping amount flat rate & table rates go to 0 when shipping cart has more than 1 item.  I have tested running Wampx64 on Windows 10,  Several version on the community as well as cloned version on the gethub site. You would think that someone would be looking into this problem, as there are a lot of problems being reported on the Internet. I hope this will be resolved soon.  Joe

**Comment by tylerd92vn** [comment]
I solved this here @joedin51 

https://github.com/magento/magento2/issues/6414?_pjax=%23js-repo-pjax-container#issuecomment-245303669
