### ISSUE TITLE
StoreView redirect not working on url with more than one level

### ISSUE THREAD

**Issue by doppiobrodo** [magento/magento2#4143]
## Steps to reproduce
1. Install Magento 2.0.4
2. Configure more than one storeview
3. Go on a page that have more one leve in the url. example: "http://www.magentostore.com/it/level1/level2"
4. Switch storeview
   example link url: "http://www.magentostore.com/en/level1/level2?___from_store=it"
## Expected result
1. redirect to http://www.magentostore.com/en/level1en/level2en
## Actual result
1. redirect to http://www.magentostore.com/en/level1/level1en/level2en

## Temporary fix:

change vendor/magento/module-url-rewrite/Controller/Router.php 75
from: 
`return $this->redirect($request, $rewrite->getRequestPath(), OptionProvider::TEMPORARY);`
to: 
 `$redirectUrl = $this->storeManager->getStore()->getBaseUrl() . ltrim($rewrite->getRequestPath(), '/');
return $this->redirect($request, $redirectUrl, OptionProvider::TEMPORARY);`

**Comment by mktudock** [comment]
We have the same issue :(

**Comment by piotrekkaminski** [comment]
Internal issues MAGETWO-53437

**Comment by vzabaznov** [comment]
hi @doppiobrodo we cannot reproduce this issue now, can you re-check it please in fresh Magento?

**Comment by piotrekkaminski** [comment]
@mktudock please see above - we cannot reproduce. Can you reproduce it on latest (2.0.7) or 2.1RC?

**Comment by vzabaznov** [comment]
Bug closed due to author doesn't answer more than 14 days and bug is not reproducible on latest Magento version
