### ISSUE TITLE
Poor implementation of product methods

### ISSUE THREAD

**Issue by samtay** [magento/magento2#4144]
1. [Product::isInStock](https://github.com/magento/magento2/blob/072a1ae2c9b0eb4be68950d63e4e5fa1b1a0b438/app/code/Magento/Catalog/Model/Product.php#L1687-L1695) is misleading. This does **not** check if product is in stock, but just checks if enabled.
2. [Product::getQty](https://github.com/magento/magento2/blob/072a1ae2c9b0eb4be68950d63e4e5fa1b1a0b438/app/code/Magento/Catalog/Model/Product.php#L960-L968) does not look for `qty` key in the correct place. Perhaps in some parts of the app, `qty` is set on the `Product::_data` array directly, but my screenshot shows that this is not the case in the `product/price/amount/default.phtml` template. Because this is the implementation of the SaleableInterface, this is a problem for abstraction.
   ![2016-04-13-170441_979x1134_scrot](https://cloud.githubusercontent.com/assets/7246591/14509434/42128f5c-019a-11e6-8ebe-66ba9321c4a5.png)

**Comment by piotrekkaminski** [comment]
@antonkril can you take a look?

**Comment by antonkril** [comment]
In the mid term these methods will be moved from product interface.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Poor-implementation-of-product-methods/idi-p/45228).
