### ISSUE TITLE
bill-to-name missing in invoice grid in admin

### ISSUE THREAD

**Issue by jackhuang89** [magento/magento2#4148]
Order is fine. have bill to name but invoice's billing_name is missing in database table
sales_invoice_grid

the payment method is Paypal sandbox.

![img_14042016_112046](https://cloud.githubusercontent.com/assets/3734296/14517510/e2ff1c90-0240-11e6-89b5-648acda0e6ae.png)

**Comment by YevSent** [comment]
Hi @jackhuang89, could you specify what type of PayPal integration you use and attach debug logs?

**Comment by jackhuang89** [comment]
hi @joni-jones,

Type of PayPal integration:
Payments Standard
Let me check the logging when I trigger the issue.

I should trace the issue when generating invoice record.

attach the database field mentioned before. Bill-to Name in database really empty.

Table:
sales_invoice_grid
Field:
billing_name

<img width="1864" alt="screen shot 2016-04-22 at 6 37 43 pm" src="https://cloud.githubusercontent.com/assets/3734296/14739336/811bbfd6-08b9-11e6-93af-0e3602888c47.png">

**Comment by YevSent** [comment]
@jackhuang89 please, attach debug logs with PayPal response.

**Comment by jackhuang89** [comment]
debug.log and exception.log  attached.

[2016-04-27 06:56:42] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://192.168.10.197/paypal/express/return/?token=EC-281419295S584090A&PayerID=QLM2JDNU3R8S2","invalidateInfo":{"tags":["catalog_category_2","catalog_category"],"mode":"matchingAnyTag"},"is_exception":false} []

[logs.zip](https://github.com/magento/magento2/files/238083/logs.zip)

**Comment by YevSent** [comment]
Did you enable  debug mode for PayPal payment? Your debug log doesn't contain any request/response data related to PayPal.

**Comment by jackhuang89** [comment]
ok. I enabled it.
attach again. 
[log.zip](https://github.com/magento/magento2/files/238122/log.zip)

**Comment by YevSent** [comment]
Please, re-check configuration of your PayPal customer account. We parse `[BILLINGNAME]` key from PayPal response, in your case this key doesn't exists in response.

**Comment by jackhuang89** [comment]
Any hints about the [BILLINGNAME]?
I looking at 

https://developer.paypal.com/docs/classic/api/merchant/DoExpressCheckoutPayment_API_Operation_NVP/

[BILLINGNAME] not found.

After this, I google BILLINGNAME
found this:
http://stackoverflow.com/questions/16469369/getting-billing-info-express-checkout

It said 
"GetExpressCheckoutDetails returns Billing information if you had passed REQBILLINGADDRESS = 1 in SetExpressCheckout."
...

## There have BILLINGNAME...

Question:
If I set:
<img width="1124" alt="screen shot 2016-04-27 at 4 51 43 pm" src="https://cloud.githubusercontent.com/assets/3734296/14846845/5f7a5756-0c98-11e6-9128-e81e3a5d4ab1.png">

There have no BILLINGNAME response from Paypal so the invoice bill-in-name is normal case?

**Comment by twistedatrocity** [comment]
This issue exists for me in 2.1.6 regardless of payment method used.  Imported sales with data migration tool have these fields populated, but any new sales through M2 does not populate the Bill-To column in the grid. The invoice itself has no missing data when opening or printing however, it's just the grid that has the issue.

**Comment by storepeinture** [comment]
I confirm that the issue also exists for me in 2.1.7
The Bill-to-Name is populated in Order Overview. But in Invoice Overview the Bill-to-Name column is empty for all invoices.

This is definitely not the worst issue, since customer names can be found through order overview, but it should be solved for convenience and usability.

Can anybody else confirm this issue?

**Comment by harimayco** [comment]
I 'm also facing this issue in 2.1.7
but only happened when customer pay with paypal express checkout
![screenshot_20171011_105503](https://user-images.githubusercontent.com/5478980/31421656-b35300d0-ae72-11e7-862a-126ca5a8823d.png)
database
![screenshot_20171011_112409](https://user-images.githubusercontent.com/5478980/31422260-bb4a77e2-ae76-11e7-8382-80689a999ae5.png)

how to fix it?

**Comment by xanka** [comment]
I using Magento 2.1.7 someone let me know this bug to be fixed. Thanks!
