### ISSUE TITLE
Argument 1 passed to Magento\\Framework\\Config\\Scope::__construct() must be an instance of Magento\\Framework\\App\\AreaList

### ISSUE THREAD

**Issue by MicroKloon** [magento/magento2#4150]
Magento 2.0.4

after following steps from https://github.com/magefan/module-blog

composer require magefan/module-blog

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

I get the following errors, I cleaned out the pub/static directory but no results.

==> /home/mag/logs/access_log <==
x - - [14/Apr/2016:12:46:54 +0200] "GET /admin_hs5ikv/ HTTP/1.1" 500 3378 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.66 Safari/537.36"

==> /home/mag/logs/error_log <==
[Thu Apr 14 12:46:54.420719 2016] [fcgid:warn] [pid 31898] [client x:59973] mod_fcgid: stderr: PHP Catchable fatal error:  Argument 1 passed to Magento\Framework\Config\Scope::__construct() must be an instance of Magento\Framework\App\AreaList, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /home/mag/public_html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /home/mag/public_html/magento/vendor/magento/framework/Config/Scope.php on line 37

**Comment by mcjwsk** [comment]
It's a duplicate of the issue #3963

**Comment by MicroKloon** [comment]
ok, thanks. Didn't show up with my initial search.
