### ISSUE TITLE
Price on category page for "Grouped Products" is not the minimal price if there are tier prices

### ISSUE THREAD

**Issue by zolthan** [magento/magento2#4153]
## Steps to reproduce
1. Create a grouped product and assign it to a category
2. Create a Simple Product
3. Add some tier prices to the Simple Product
4. Assign the Simple Product to the Grouped Product
5. Go to the category in the frontend
## Expected result
1. The displayed price of the grouped product should be the minimal possible price. ie. the minimal tier price.
## Actual result
1. The displayed price is the minmal normal price of the assigned simple products. The tier prices are not evaluated.

**Comment by antboiko** [comment]
Hello @zolthan , tier price is applicable if quantity is not less than N, so it won't be "Starting at" price as it will apply to certain simple product only if quantity is set >=N. Total price for that simple product will be equal N*Tier_Price (obviously it will not be the min price for most cases). However if you add some tier price with Qty = 1, it will be displayed as "Starting at" price if it's really min price within grouped product.

I hope this will help. I'm closing ticket. Please feel free to reopen if you have any additional questions.

Best,
Anton.

**Comment by zolthan** [comment]
Hi @antboiko,

thanks for your reply. That doesn't seem to be correct for me and our customers. If a product normally costs $10 and can be bought for $2 if you buy 100pcs, then the starting price should be $2. As a Magento developer I know the difficulties and prerequisites in the code. But logically it would be more correct to show the real minimal price, not a price that is higher than any price I could reach within the product.

Can you follow my thoughts?

Best
Sebastian

**Comment by antboiko** [comment]
@zolthan 

Hi Sebastian, I got your point. I've created internal ticket MAGETWO-52718 for this improvement and added it to the backlog.

Best,
Anton.

**Comment by zolthan** [comment]
@antboiko 

Hi Anton, thanks for the reply. Maybe a backend config would be suitable where one can choose whether to include tier prices in the minimal price calculation.

Best Sebastian

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Price-on-category-page-for-quot-Grouped-Products-quot-is-not-the/idi-p/46884).

**Comment by daniloargentiero** [comment]
Hi all, I created a module with admin config:

https://github.com/magespecialist/m2-MSP_UseLowestPriceForTier

Bye
