### ISSUE TITLE
magenta 2.0.4 stuck during install

### ISSUE THREAD

**Issue by abdel1220** [magento/magento2#4160]
Hello,
i'm trying to install magento 2.0.4 with the web installer, but it stuck in deferent install process percentage, some time stuck at 14% other time at 7%,  other one at 10%.

server information:
web server Microsoft-IIS/7.5
php version 5.5.34
mysql version 5.6.26
max_execution_time = 18000;
max_input_time = 6000   ;
memory_limit = 728M;

any idea :)

thank you.

**Comment by mazhalai** [comment]
@akacemy Please try setting Magento [mode](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) to developer. Also, officially IIS is not supported.

**Comment by abdel1220** [comment]
Hello,
thank you for your replay.
what is the correct way to SetEnv MAGE_MODE "developer" in IIS. do have you any  idea.

thanks.

**Comment by mazhalai** [comment]
Try `bin/magento deploy:mode:set developer` on  command line.

**Comment by abdel1220** [comment]
Hello,
thank you for your replay.
i figured out the issue, it was IIS FastCGI “Activity timeout” settings (default was 70) so increased it to 3600. and the install complete successfully. 
But after the install to static content wasn't deployed so i run the command bin\magento setup:static-content:deploy. then every thing is good.

thank you for your help.
Have nice time.
