### ISSUE TITLE
sales_order_place_after not returning Order ID

### ISSUE THREAD

**Issue by forgeonline** [magento/magento2#4165]
## Steps to reproduce
1. Create an event to run in sales_order_place_after
2. What I tried to do is Create Invoice when cach on delivery method after Order is placed.
3. get Order Id to process extra functions

<code>$order = $observer->getEvent()->getOrder()->getId();</code>

This dosen't return Order Id. However it return Increment ID

<code>$observer->getEvent()->getOrder()->getIncrementId();</code>

**Comment by akaplya** [comment]
This event triggers after payment processed before the order has been saved to database. Id appears only after order was successfully saved to storage.
Please use after plugin for `Magento\Sales\Api\OrderManagementInterface::place`

**Comment by piotrekkaminski** [comment]
Closing due to lack of updates.

**Comment by edudeleon** [comment]
Do you have an example of how to implement this? and in case I want to watch an order that is beign update in the Admin Panel, what event would you suggest I can use?

**Comment by aunik** [comment]
@edudeleon here is an example I have posted https://magento.stackexchange.com/a/243747/41104
