### ISSUE TITLE
REST script does not work for multi stores or multi language.

### ISSUE THREAD

**Issue by yssource** [magento/magento2#4166]
$temporaryCredentialsRequestUrl = "http://magentohost/oauth/initiate?oauth_callback=". **// this causes 404 error code**

$temporaryCredentialsRequestUrl = "http://magentohost/**_index.php/zh_cn_**/oauth/initiate?oauth_callback=" . **// this is OK.** 
$accessTokenRequestUrl = 'http://magentohost/oauth/token'; **// this causes 404 error code**
$accessTokenRequestUrl = 'http://magentohost/**_index.php/zh_cn_**/oauth/token'; **// this is OK**

And This is the my test script.

```
<?php
/**
 * Example of products list retrieve using Customer account via Magento REST API. OAuth authorization is used
 */
$callbackUrl = "http://yourhost/oauth_customer.php";
$temporaryCredentialsRequestUrl = "http://magentohost/oauth/initiate?oauth_callback=" . urlencode($callbackUrl);
$adminAuthorizationUrl = 'http://magentohost/oauth/authorize';
$accessTokenRequestUrl = 'http://magentohost/oauth/token';
$apiUrl = 'http://magentohost/api/rest';
$consumerKey = 'yourconsumerkey';
$consumerSecret = 'yourconsumersecret';

session_start();
if (!isset($_GET['oauth_token']) && isset($_SESSION['state']) && $_SESSION['state'] == 1) {
    $_SESSION['state'] = 0;
}
try {
    $authType = ($_SESSION['state'] == 2) ? OAUTH_AUTH_TYPE_AUTHORIZATION : OAUTH_AUTH_TYPE_URI;
    $oauthClient = new OAuth($consumerKey, $consumerSecret, OAUTH_SIG_METHOD_HMACSHA1, $authType);
    $oauthClient->enableDebug();

    if (!isset($_GET['oauth_token']) && !$_SESSION['state']) {
        $requestToken = $oauthClient->getRequestToken($temporaryCredentialsRequestUrl);
        $_SESSION['secret'] = $requestToken['oauth_token_secret'];
        $_SESSION['state'] = 1;
        header('Location: ' . $adminAuthorizationUrl . '?oauth_token=' . $requestToken['oauth_token']);
        exit;
    } else if ($_SESSION['state'] == 1) {
        $oauthClient->setToken($_GET['oauth_token'], $_SESSION['secret']);
        $accessToken = $oauthClient->getAccessToken($accessTokenRequestUrl);
        $_SESSION['state'] = 2;
        $_SESSION['token'] = $accessToken['oauth_token'];
        $_SESSION['secret'] = $accessToken['oauth_token_secret'];
        header('Location: ' . $callbackUrl);
        exit;
    } else {
        $oauthClient->setToken($_SESSION['token'], $_SESSION['secret']);
        $resourceUrl = "$apiUrl/products";
        $oauthClient->fetch($resourceUrl);
        $productsList = json_decode($oauthClient->getLastResponse());
        print_r($productsList);
    }
} catch (OAuthException $e) {
    print_r($e);
}
```

It seems the `/oauth/` does not match any rewrite rules. And most like this `/{store_code}/oauth` working.
Is There a problem happens to anyone else?

**Comment by piotrekkaminski** [comment]
@mbrinton01 can you look into it?

**Comment by yssource** [comment]
I'm sorry to open this issue here. Actually, this happens under magneto v1.x.
Feel free to close it, if there is no such a similar problem for magento v2.x

**Comment by mbrinton01** [comment]
@yssource have you tried to reproduce it against M2.x?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues and bugs in Magento 2 only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and assistance.

If you can reproduce this in a clean Magento 2 installation, please open a new issue with complete details on how to reproduce. Thanks!
