### ISSUE TITLE
Magento : A customer with the same email already exists in associate website.

### ISSUE THREAD

**Issue by parthviroja** [magento/magento2#4167]
**Magento CE 2.0.0 with sample data *\* on local server ( **192.168.0.100/magento-demo**  ).

i have register as customer using below emails, passwords

customer-1 
            email : demo@gmail.com
             password : demo2016

customer-2
            email : custom@gmail.com
             password : custom2016

when i have open my account using this credential and goto [ Account Information ], when i edit my email address from  demo@gmail.com -> custom@gmail.com , then this error message display.
![bug-email](https://cloud.githubusercontent.com/assets/9655554/14551162/35d96e8c-02ed-11e6-8936-63ec44491d8a.png)

**Comment by sevos1984** [comment]
I can not reproduce this issue on latest develop, try update your code.

**Comment by parthviroja** [comment]
Thanks
