### ISSUE TITLE
Sql exception on sorting when attribute contains "."

### ISSUE THREAD

**Issue by OwenRay** [magento/magento2#4169]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create attributeset
3. Add attribute named 1.ABC (set sortable to yes)
4. Create product with attributeset
5. Go to the frontend
6. Order by attribute
## Expected result
1. Products are sorted
## Actual result
1. Sql exception (backticks are not added in ON statements)

Example output:
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `cat_index`.`position` AS `cat_index_position`, IF(101.Principe:_option_value_t2.value_id IS NULL, 101.Principe:_option_value_t1.value, 101.Principe:_option_value_t2.value) AS `101.Principe:` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(3, 4) AND cat_index.category_id='2'
 INNER JOIN `search_tmp_5710b77e1accc2_44583818` AS `search_result` ON e.entity_id = search_result.entity_id
 LEFT JOIN `catalog_product_entity_int` AS `101.Principe:_t1` ON e.entity_id=101.Principe:_t1.entity_id AND `101.Principe:_t1`.attribute_id='131' AND 101.Principe:_t1.store_id=0
 LEFT JOIN `catalog_product_entity_int` AS `101.Principe:_t2` ON e.entity_id=101.Principe:_t2.entity_id AND 101.Principe:_t2.attribute_id='131' AND 101.Principe:_t2.store_id='1'
 LEFT JOIN `eav_attribute_option_value` AS `101.Principe:_option_value_t1` ON 101.Principe:_option_value_t1.option_id=IF(101.Principe:_t2.value_id > 0, 101.Principe:_t2.value, 101.Principe:_t1.value) AND 101.Principe:_option_value_t1.store_id=0
 LEFT JOIN `eav_attribute_option_value` AS `101.Principe:_option_value_t2` ON 101.Principe:_option_value_t2.option_id=IF(101.Principe:_t2.value_id > 0, 101.Principe:_t2.value, 101.Principe:_t1.value) AND 101.Principe:_option_value_t2.store_id=1 ORDER BY `101`.`Principe:` DESC LIMIT 9

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53433

**Comment by mslabko** [comment]
Hi @OwenRay ,

I cannot reproduce this issue on develop branch. Do you have default magento2 installation without extra modules?

**Comment by OwenRay** [comment]
I didn't notice at first, but the normal way of adding attributes doesn't allow any special characters.
In this case I was creating attributes programatically. That way I was able to create an attribute with the attribute-code containing a "."
So I think it's up to you whether or not to treat this as a bug.

**Comment by mslabko** [comment]
Thank you for clarifying!

**Comment by oserediuk** [comment]
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
