### ISSUE TITLE
Magento2 Mini Cart Items Issue

### ISSUE THREAD

**Issue by wclansar** [magento/magento2#4170]
Hello , 
1. After login , i can not see items in minicart .
2. when i click on add to cart from home page widget products , mini cart not displaying add items .

Can you please help ?

Thanks

**Comment by ishakhsuvarov** [comment]
@wclansar Thank you for reporting. Could you please provide more precise steps to reproduce? Which Magento version are you using? Any errors in browser console?

**Comment by ansarhusain** [comment]
Hello i am using magento 2.0.4 

There is not error in console.

**Comment by sdzhepa** [comment]
Hello @wclansar and @ansarhusain, we tried to reproduce this issue by next case:
- Clone magento from GitHub: git clone https://github.com/magento/magento2.git (this is "develop" branch)
- Then switch branch to 2.0: git checkout -f 2.0 
- Install Magento 2 (with default values during web installation, sample data is not used)
- After installation, login to admin
- Go to Products > Catalog and click "Add Product"
- Then fill all required fields for creating simple product:
- Name = simple product
- SKU = simple product
- Price = 10
- Tax Class = Taxable Goods
- Quantity = 1
- Categories = test (click "New Category" and create category "test" as child for  "Default Category")
- Save the product(all other settings in default state)
- Go to Storefront as Guest (the same result if we use registered customer)
- Click for open "test" category
- Click "Add to Cart" button

Result: 
- Product is added to cart
- Mini cart has 1 product(simple product)
- Red Icon with number 1 is presented near mini cart

Could you pls provide more information about Your Magento 2  and server settings, like
- Which version of PHP do you use, php 7.0.4?
- Do You use Varnish or not?
- Do You use Redis or not?
- Do You use HTTPS or HTTP for Storefront and admin?
- Do You use Sample Data?
- Which Magento 2 mode do You use? (default/develop/production)
- Do You use  Definition compilation Tool  after installation?
- Do You use Static Content Deploy after installation?
- Do You use JS minification    ?
- Do You use JS Bundling?
- Do You use JS merge?
- Do You use HTML minification?
- Do You use Flat Catalog Product?
- Do You use CDN as Static Content?
- Wich browser do You use? (Firefox/Chrome/IE)
  Probably there is other specific configuration that we miss.

**Comment by longbeachjamie** [comment]
Having the same issues here - https://utilitnetworks.com/ - item added to cart, but the mini-cart is not displaying any contents.
- PHP Version 5.6.20-1+deb.sury.org~trusty+1
- No Varnish, Redis
- HTTPS only
- No Sample Data
- Current application mode is default
- No javascript bundling, merge, or minify.
- No CSS merge or minify.
- No HTML minify.
- Enabled Single Store Mode.
- No CDN
- Chrome browser.

**Comment by piotrekkaminski** [comment]
Anyone else having this issue? we are unable to replicate. Do you see any errors in the browser console or any failed AJAX requests?

**Comment by krlecarp** [comment]
Yes.  On 2.1.0-RC1, not sure what it was like on 2.0.6 as I upgraded right away.  Chrome console says the following, along with the screen capture.  Hopefully that is sorta helpful.

```
knockout.js:3012 Uncaught ReferenceError: Unable to process binding "foreach: function (){return { data:cookieMessages,as:'message'} }"
Message: cookieMessages is not defined
knockout.js:3012 Uncaught ReferenceError: Unable to process binding "css: function (){return { empty:!!getCartParam('summary_count') == false} }"
Message: getCartParam is not defined
```

![image](https://cloud.githubusercontent.com/assets/1714009/15510750/a52fc2f4-218d-11e6-9498-69ac55260da8.png)

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53432

**Comment by BeniSt** [comment]
I have the same issue:

Magento 2.0.7
PHP Version 7.0.4.
No Varnish, Redis
HTTPS only
No Sample Data
Current application mode is default
No javascript bundling, merge, or minify.
No CSS merge or minify.
No HTML minify.
Enabled Single Store Mode.
No CDN
Chrome browser.

**Comment by tkacheva** [comment]
Thanks for reporting issue. Internal ticket MAGETWO-53766

**Comment by SerhiyShkolyarenko** [comment]
@longbeachjamie, I tried it on your store and minicart worked properly.
As admin you may recheck my cart(created user with my real first and last name).

**Comment by grasdaggel** [comment]
Can confirm that this bug happens in 2.0.7. as well. We have a Magento installation where we had huge problems after update yesterday. Since then the mini cart only shows the amount of products (if it does it anyway...). MIni cart is empty, even with 20 Items in Cart. 

Maybe a Update-Bug?

**Comment by SerhiyShkolyarenko** [comment]
@kingalca, yes, it may be.
Which release you updated from?

**Comment by grasdaggel** [comment]
@SerhiyShkolyarenko we updated from 2.0.4. iirc. (So .0.4 => .0.7)

**Comment by thills03** [comment]
Just an observation, as I am having this same issue. 

Landing on /checkout/cart after adding a product from a page that doesn't use the product widget to add it, then navigating back to the home page and trying to add a product using the product widget fixes the bug until the cookies are cleared. I suspect there is some JavaScript that isn't running correctly on the home page regarding the cookie generation.

As a side note, landing on checkout/cart with no products in the cart, will not fix the bug, a product must be added from a page with (for example a category page (layout: catalog_category_view.xml)) before landing on checkout/cart.

Hopefully this information is helpful.

**Comment by BeniSt** [comment]
I can confirm this @thills03!
I Click on add-to-cart Button on Home-Site in Widget and minicart and even the red Counter stay empty. If i go to cart page, Item is added. Only if I add an item the normal way (on product or category Page) the item appears in minicart.

**Comment by wclansar** [comment]
Hello BeniSt , 

can you check is your cache disable ? 

Because it seems that issue comes when cache off .

Thanks

**Comment by grasdaggel** [comment]
We have cache on and the issue, so disabled caching can't really be the issuer here.

**Comment by BeniSt** [comment]
Yes, in my case you are right. If I enable cache, the minicart works as it should. Cool. Thanks!

**Comment by wclansar** [comment]
Welcome  Brother  BeniSt !!!!!!!!

**Comment by SerhiyShkolyarenko** [comment]
@thills03 what do you mean by words "adding a product from a page that doesn't use the product widget to add it" ?

**Comment by thills03** [comment]
I mean that if you add a product to your cart from a page with a built in product list and not a product widget added in the cms through content->pages to your home page then you navigate to yoursite/checkout/cart and then navigate back to where you do have a product widget added through content->pages to your homepage and start adding more products, the cart will work fine. Until you clear your cookies.

**Comment by SerhiyShkolyarenko** [comment]
@BeniSt @wclansar @kingalca @thills03 I cannot reproduce the issue.

**Part 1. Pure 2.0.4 installation with caching enabled.**
1. I set up 2.0.4 CE without sample data from https://www.magentocommerce.com/download release archives.
2. Installed Magento in default mode.
3. Created product on backend.
4. Added product to cart as guest from category page.

_Minicart worked properly._

**Part 2. The same 2.0.4 with disabled cache.**
1. Flushed Magento cache.
2. Disabled all cache types on backend.
3. Cleared browser lolalStorage from console: window.localStorage.clear()
4. Cleaned all cookies for the store.
5. Refreshed frontend category page by Ctrl-F5.
6. Added product to cart.

_Minicart worked properly, but much slower(because of disabled cache)_

**Part 3. Upgrage to  2.0.7(enabled cache).**
1. I backed up files app/etc/env.php and app/etc/config.php
2. Downloaded Magento 2.0.7 CE without sample data from https://www.magentocommerce.com/download
3. Removed folder with old Magento
4. Unpacked new archive to the same folder.
5. Restored files config.php and env.php
6. Ran **bin/magento setup:upgrade**
7. Cleaned var/ directory
8. Enabled cache on backend.
9. Added product to cart as guest from category page.

_Minicart worked properly._

**Part 4. CE 2.0.7 with disabled cache.**
1. Flushed Magento cache.
2. Disabled all cache types on backend.
3. Cleared browser lolalStorage from console: window.localStorage.clear()
4. Cleaned all cookies for the store.
5. Refreshed frontend category page by Ctrl-F5.
6. Added product to cart.

_Minicart worked properly, but much slower(because of disabled cache)_

What am I doing wrong? Do you have any extensions installed? Please, hint me on reproducing the issue.

**Comment by SerhiyShkolyarenko** [comment]
@thills03 sorry, i didn't understand you. Is it enough to add product from category page to reproduce the issue? If not, could you please provide a step-by-step instruction?

**Comment by thills03** [comment]
The frontend category page is not the broken page. You need to add a product list widget to your homepage via logging into admin, selecting content on the left and then pages. Find your homepage in the list and select edit. In the wysiwyg, select the widget option and add a product list widget. Save it, and make sure it appears on the homepage. Clear your cache and your cookies entirely and then ctrl f5. Once it reloads, try adding a product from the widget on your home page. 

Using a category page to add the product and then landing on site/checkout/cart is an observation that fixes the widget not updating the cart.

**Comment by BeniSt** [comment]
Hey @SerhiyShkolyarenko,

> Part 4. CE 2.0.7 with disabled cache.
> Flushed Magento cache.
> Disabled all cache types on backend.
> Cleared browser lolalStorage from console: window.localStorage.clear()
> Cleaned all cookies for the store.
> Refreshed frontend category page by Ctrl-F5.
> Added product to cart.

This is right exept the last two steps. Please go to home-site (or probably any cms-site) and click on add-to-cart-button on an inserted widget there. Then check mini-cart.

**Comment by SerhiyShkolyarenko** [comment]
@thills03 thank you! I managed to reproduce it!

**Comment by 100php** [comment]
@SerhiyShkolyarenko there is are more scenarios as below:
Case1-
1. login 
2. Add product to cart 
3. logout

MiniCart must become Empty (Expected)
MiniCart still shows 1 product but when we check cart page there is no product (Unexpected)

Case2 - 
1. in new browser login with the same user
2. Minicart do not show any product 

But when we go to cart page we see 1 product which we added earlier 

Now when we add any product to cart, minicart starts working correctly.

This issues persists in 2.0.4 , 2.0.6 and 2.0.7 +

The issues seems to be related to cookies. Can anyone help?

**Comment by thills03** [comment]
It is likely a temporary solution, but currently I have a block in my module loading a phtml file with this post request on the layout cms_index_index.xml and cms_page_view.xml and although a bit slow, it seems to help resolve the issue. I do have a lot of other code working in the background, but this snippet seems to function to refresh the minicart without having to refresh the page. 

`require(['jquery'],function($){
$(document).ready(function(){
$.post("checkout/cart/updatePost/");
});
});`

**Comment by SerhiyShkolyarenko** [comment]
@100php thank you for your updates. I've checked both cases, they have the same root as described above.

**Comment by 100php** [comment]
@thills03 , the solution u gave is loading the whole cart page, where as we are facing issue with minicart.  Can you please help us with minicart showing wrong details?

**Comment by 100php** [comment]
Ok, We have resolved the issue...To update minicart on every action we have to update "vendor/magento/module-theme/etc/frontend/sections.xml" file. This updates "messages" section on every action. Adding `<section name="cart"/>`  on line no.12 will reload the cart on every action. 

This worked for us.

**Comment by PascalBrouwers** [comment]
I face the same issue when trying to have a shared cart. Both stores will show the products in /checkout/cart but the minicart simple won't update. The information in window.checkoutConfig.quoteData is correct, but it looks like the minicart's cache is not updated or something?

**Comment by PascalBrouwers** [comment]
It seems localStorage is the issue here. Magento is not invalidating the localStorage when I have the same session for the other store.

**Comment by valibus** [comment]
Could we have an update on this bug fix please ?

**Comment by tkacheva** [comment]
The issue is fixed and waiting the PR to be merged.

**Comment by PascalBrouwers** [comment]
@tkacheva Nice, what is the Mage issue nr?

**Comment by tkacheva** [comment]
Issue MAGETWO-53766 is merged into mainline. PR #127

**Comment by Ctucker9233** [comment]
@tkacheva This link doesn't go to a pull request.

**Comment by liquidia** [comment]
same issue 2.1, no merging no minification of css js .it was working after installation but suddenly no cart content just blank white minicart box

**Comment by tkacheva** [comment]
@liquidia has you already updated with the fix?

**Comment by SerhiyShkolyarenko** [comment]
@Ctucker9233 that PR is already merged.

**Comment by liquidia** [comment]
@tkacheva what fix?

**Comment by tkacheva** [comment]
@liquidia we pushed the fix into mainline 8 days ago

**Comment by vasilii-b** [comment]
**The same issue on 2.1 after upgrading from 2.0.6.** Even with Magento Blank theme minicart is not updated when adding product to cart from detail page. Pressing 'Add to cart' button _**refreshes the entire page, not just minicart**_ as it was in 2.0.6. http://prntscr.com/c1zdk3

When pressing 'Add to cart' on category page, the minicart is updated and add-to-cart process works fine. Going back to detail page of the product and adding it to cart makes the minicart 'empty', even in /checkout/cart there are products added.

**Minicart is updated** if I go to _/checkout/cart_ manually and delete all items from there. After this adding product to cart from detail page refreshes the minicart ( but still after whole page is refreshed)...

P.s. no sample data was installed and used.
P.s.2 **no errors in console**

**UPDATE**
I get the following errors in `checkout/cart` When I press "clear/delete all items" cart button.
[checkout-cart-errors.txt](https://github.com/magento/magento2/files/403947/checkout-cart-errors.txt)

**Comment by karmalis** [comment]
Confirming this as an issue. Basically we "reproduced" the problem as described by @vasilii-b

**Comment by esilvajr** [comment]
@vasilii-b Same here, but i did a new installation, not an upgrade...

**Comment by kanduvisla** [comment]
I can also confirm what @vasilii-b describes after an upgrade from 2.1.0 to 2.1.1

Also, after refreshing the page, the session message 'You added %s to your shopping cart.' won't disappear.

**Comment by grasdaggel** [comment]
So, is there a fix if you install from scratch, but not if you upgrade?

**Comment by karmalis** [comment]
If I recall correctly, our problem was that we based our theme on base, but had altered the template for the mini cart slightly. After the upgrade quite a few functions had changed so the minicart wasn't working. Readjusting worked just fine.

**Comment by filipac** [comment]
is there a known fix for this?

**Comment by mombrea** [comment]
If you have the problem where the minicart shows a blank white box, the solution is as @karmalis mentions. You should perform a diff on your overidden minicart.phtml template and the base version you're inheriting from (e.g. Magento/blank). Magento version updates are routinely changing functions in these files without warning.

As far as the minicart not showing products you just added (always empty), we have not found the cause of this problem but as others have mentioned, enabling the Block, Page, and Layout cache seems to fix it for whatever reason.

**Comment by kanduvisla** [comment]
I have not overridden the `minicart.phtml`-template and still I have the problem:
- If I add a product to the cart, the page refreshes rather than it's done with a XHR request.
- After the page is reloaded, the minicart is not updated.
- If I go to `checkout/cart` I see my added product(s).
- If I mutate my cart here (click 'update cart', or edit qty or remove items) the minicart gets shown (after the page is reloaded of course).
- From here on, it works. So if I empty my cart, and go to the product page, I see a minicart with '0'.
- Now if I add a product, the minicart gets updated. However, still with no XHR request.
- There are no JavaScript errors in the console.

_Edit:_ If I enable the cache, above problem does not occur. Strange. Tested in M2.1.1

**Comment by mombrea** [comment]
Do you have all of the caches enabled or all of them disabled? I had this
problem when I had a mix of enabled/disabled.

**Comment by kanduvisla** [comment]
When all the cached are enabled the problem does not occur.

**Comment by bvboas** [comment]
The commit for the fix is here: 861f596371825d9e24672cd613229ae9486c635f

**Comment by rishabhrkrai** [comment]
If cache is disabled then this issue is happen in 2.1.x
- Kindly enable cache from terminal or backend and then try. This works for me.

**Comment by wojciechowskid** [comment]
> If cache is disabled then this issue is happen in 2.1.x

The same for 2.0.10

**Comment by pyyick** [comment]
@wojciechowskid I disabled the cache, but the same error happens too.

**Comment by SantoDE** [comment]
I'm encountering the same Issue with a disabled FPC as well. While manually applying the fix commit above all works out. Is there any ETA on when this is getting into a "real version"? How do you guys apply those workarounds? I mean it's fixed in this git repro code. I don't really get that.

**Comment by DRAJI** [comment]
Enable caching is working for me. Thanks @wclansar

**Comment by dambrogia** [comment]
I have found this to help me. I was having a similar problem from multiple situations (customer login/logout, reordering functionality, etc.) and this seemed to fix them all. I found this online and from what I understand (and _please_ correct me if I'm wrong) it's invalidating the minicart to force revalidation of the minicart via ko.

I added this in my .phtml file right after the html of my minicart has ended.

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            var sections = ['cart'];
            customerData.invalidate(sections);
        });
    </script>

**Comment by rafaelstz** [comment]
This issue was fixed to me when I upgrade my PHP version from 7.0.9 to 7.0.15.

**Comment by rajesh0608** [comment]
Yes,  I enable cache, the minicart works as it should.

Thanks...

**Comment by FloWord** [comment]
My Solution for refresh Problem:
https://github.com/magento/magento2/issues/5377

You simply need to change
"bindSubmit": false
to
"bindSubmit": true

**Comment by malachy-mcconnell** [comment]
Possibly related to #5946 

Regarding comments about turning on the cache fixing the problem or adding the invalidation `customerData.invalidate(sections);`, I wonder if my suggestion of Mar 22 2017 on #5946 would solve and/or help in those circumstances.

**Comment by winds1983** [comment]
Still happens on 2.1.6, how to fix this?

**Comment by Tonop** [comment]
I see it in 2.1.6 too.

**Comment by dharake** [comment]
Joining in here, tried all the fixes mentioned in this thread, all of them. Still have my issue, which is to be precise.:

Land on home page, and add to cart from products displayed from widget.
First add to cart shows nothing in cart.
Second add to cart, works, and shows product that was first added

So basically, first producted is added but minicart is not populated.

Magento 2.1.4, Porto theme, using Varnish, Redis, all caches enabled

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70218

**Comment by maderlock** [comment]
If this is being worked on, should this still be closed?
