### ISSUE TITLE
Class Magento\User\Observer\Backend\CheckAdminPasswordChangeObserver does not exist in Magento 2.0.4

### ISSUE THREAD

**Issue by cedcommerce** [magento/magento2#4171]
## Steps to reproduce
1. Open admin panel and Create new admin account
2. Edit created admin user
3. Fill "Your Password" and Click on save button
## Expected result
1. Account should be saved with success message.
## Actual result
1. Error : Class Magento\User\Observer\Backend\CheckAdminPasswordChangeObserver does not exist

**Comment by buskamuza** [comment]
@cedcommerce , do you have full exception log? Also, did you try to clean cache and `var/di`, `var/generation`?
If you had older version of Magento, some old generated class with reference to `CheckAdminPasswordChangeObserver` may still exist?

**Comment by cedcommerce** [comment]
@buskamuza   Yes you are right.
Thank You for your assistance
