### ISSUE TITLE
Nginx config pub location

### ISSUE THREAD

**Issue by jackiellowery** [magento/magento2#4176]
This is more of a question than an issue?  In this part of nginx.conf:

`location /pub {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    alias $MAGE_ROOT/pub;
    add_header X-Frame-Options "SAMEORIGIN";
}`

Shouldn't root be used instead of alias, per the official docs, since the location matches the last part of the directives value.  See here: [nginx alias](http://nginx.org/en/docs/http/ngx_http_core_module.html#alias)

Like this: 

`location /pub {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    root $MAGE_ROOT;
    add_header X-Frame-Options "SAMEORIGIN";
}`

**Comment by vrann** [comment]
Hi, @jackiellowery, trying to understand more the difference between root and alias, one good explanation is done here: http://stackoverflow.com/questions/10631933/nginx-static-file-serving-confusion-with-root-alias 
It seems to me that in our case whatever we chose result is will be the same. Are there strong arguments for one vs another?

**Comment by maksek** [comment]
closing due no response from creator. if you have more question - please create them in forum.

**Comment by devdesco-ceo** [comment]
Nginx default config file is broken.
I have made my own Nginx configuration for three servers tier and implemented all of the latest and the bestest practices for secure and fast web. Check me out at https://endohaus.com
