### ISSUE TITLE
Add to cart issue

### ISSUE THREAD

**Issue by ovekeryk** [magento/magento2#4177]
### Preconditions
1. Magento 2.1

### Steps to Reproduce
1. Set "Qty Uses Decimals" field is set to "yes" for a product
2. Add product to cart with quantity "0"

### Actual result
1. "We don't have as many "xxx" as you requested."

### Expected result
1. Product is added to the cart

### Additional informaion
Better to use value from "Minimum Qty Allowed in Shopping Cart" field of inventory module when it enabled instead of "1".

ref: https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/Quote/Item.php#L306

**Comment by heyitsroberthe** [comment]
Hi,

It looks like we can definitely make improvements to the Advanced Inventory settings with regards to quantities involving decimals. Your suggestion to the qty check makes sense as well.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53429

**Comment by ashburystudios** [comment]
Hi all, Any update on this. Need this ASAP to work on a new site and cant move forward. Thank you, Mike

**Comment by degaray** [comment]
I have the same issue.

**Comment by magento-engcom-team** [comment]
@AlexanderVekerik, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by ravihandsintechnology** [comment]
i am trying to update cart with the help of rest/v1/carts/cartid/items/itemid

the product is updating sucessfully when the stock of the product is greater than 1
but when the stock is 1 the product is not updating

it gives error
stdClass Object
(
    [message] => We don't have as many "product name" as you requested.
)
