### ISSUE TITLE
cannot run composer install

### ISSUE THREAD

**Issue by decormatters** [magento/magento2#4178]
[RuntimeException]  
  /Library/WebServer/Documents/magento2new/magento2/vendor/magento/magento-composer-installer does not exist and could not be created.

**Comment by tanya-soroka** [comment]
Hello @decormatters.
Please check you permission on this directory.

**Comment by buskamuza** [comment]
@decormatters , can you create the same directory manually from the same user?

**Comment by mazhalai** [comment]
@decormatters we are closing since as non-responsive.
