### ISSUE TITLE
Magento 2 Slow Loading Images In Firefox Mac

### ISSUE THREAD

**Issue by hannaaaaah** [magento/magento2#4180]
Hi,

I am working on a Magento 2 store, it is in production mode. I'm just using it to tinker around and decide whether I want to develop my new store on version 1.9 or 2.

It is SO much faster than 1.9, but I am having some issues with images loading on the bundle product pages. Images load perfectly on all browsers, except firefox. On firefox, the images seem to load 3-4 seconds slower. I am using Mac OSX Yosemite, with the latest version of firefox.

Just to clarify, it is a clean install, with no modules or custom code. I am not using varnish and cache is set to file system.

Is it just me?

The url is [http://www.new.hjjewellery.co.uk/bundle-silver-butterfly-disc-engraved-necklace.html](http://www.new.hjjewellery.co.uk/bundle-silver-butterfly-disc-engraved-necklace.html)

Thanks!

**Comment by piotrekkaminski** [comment]
Is anyone else experiencing this? Is the load caused by waiting for the page to load or slow request from server?

**Comment by Vinai** [comment]
Can't confirm (El Capitain with current FF).

**Comment by anton-huz** [comment]
Hi @hannaaaaah 
Could you confirm that issue still exist?
What the version of Magento do you faced with?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
