### ISSUE TITLE
"Add to Cart" Button translation partly broken

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#4181]
This is follow up to closed issue: https://github.com/magento/magento2/issues/2056

One issue still remains:"Add to Cart" Button translation is partly broken
## Steps to reproduce
1. Install Magento from `develop` branch.
2. cd <document_root>/var
3. get latest translationfile: wget http://107.170.242.99/var/Head/source_nl_NL.csv
4. cd ..
5. find . -name js-translation.json -exec rm -rf {} \;
6. php bin/magento i18n:pack --mode=replace -d var/source_nl_NL.csv nl_NL
7. php bin/magento setup:static-content:deploy en_US nl_NL
8. php bin/magento indexer:reindex
9. php bin/magento cache:clean
10. php bin/magento cache:flush
11. Change locale to nl_NL
12. Add a simple product
13. Surf to website: Go to category list or wish list, click "add to cart". The button nicely changes to the translated strings "Adding...", "Added", "Add to Cart"
14. Go to the product page: Click the translated "Add to Cart" button
## Expected result
1. Show translated strings of "Adding...", "Added", and "Add to Cart"
## Actual result
1. "Adding...", "Added", and "Add to Cart" are not translated

**Comment by mazhalai** [comment]
@thomvanderboon thank you for reporting, we have MAGETWO-51987 to investigate and fix.

**Comment by okorshenko** [comment]
@thomvanderboon Thank you for reporting the issue. Fix for MAGETWO-51987 merged to develop branch.

**Comment by thomvanderboon** [comment]
@okorshenko Thanks. Did test on latest development and I can confirm issue is fixed. Please move the i18n fixes a.s.a.p. to the stable branch Please :)

**Comment by nmallepally** [comment]
Hello Thanks for the updates, but the error messages on website and some check out steps like shipping and review payments are still in English does not translate. attaching images for reference
![checkout english](https://cloud.githubusercontent.com/assets/19605497/16773415/c83f968c-484f-11e6-9dd0-07dbef89c677.png)
![password not good enought](https://cloud.githubusercontent.com/assets/19605497/16773416/c8435c36-484f-11e6-8b1f-656efbce366e.png)
![remove_from_cart](https://cloud.githubusercontent.com/assets/19605497/16773417/c84494e8-484f-11e6-947b-cafc34c33e7f.png)
