### ISSUE TITLE
Magento 2 compile/deploy mode with multiple PHP paths stuck crons/failures in php -f

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4182]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Have a server with multiple PHP versions, say PHP-FPM with a pool on 5.4 and one on 7.0, where the default /usr/bin/php is 5.4
3. Try to deploy production mode, it will partially fail at the part where it says "php -f .... ". This is because it tries to use PHP 5.4 (or whatever is /usr/bin/php) whereas if you have a custom setup you could run the entire Magento command as /usr/bin/php70 magento deploy:mode:set production and it runs all of it BUT that part in PHP 7
## Expected result
1. Crons don't update, even when set correctly until the path for /usr/bin/php is set to php 7

Is it possible to override this without having to modify the code directly? I see this is part of vendor/magento/module-deploy/Model/Filesystem.php

**Comment by ghost** [comment]
Note this also affects numerous cron jobs even when set correctly to run with a PHP 7 binary, it tries to sue whatever the environment default is. If this cannot be changed its a problem.

**Comment by vrann** [comment]
@sylink let me confirm did I understood you correctly. You are saying that if you  run
`/bin/magento/php70 -f bin/magento deploy:mode:set production`, it will fail because at some point it runs `php -f ...` and php get resolved to php54. Is that right?

**Comment by ghost** [comment]
Yes, in this case because the server/environment has the PHP version 5.4 as the binary for /usr/bin/php.

This might not be a bug as much as its a problem in environments with multiple PHP versions for different vhosts. Is this configurable in some way as a path in Magento 2 that I'm not aware of?

**Comment by vrann** [comment]
@sylink Thanks, this is a bug. PHP has a constant which defines path to currently executed php, accessible within the script: PHP_BINARY. It should be used for any internal execution of php scripts to ensure same version of the php.

Internal ticket number: MAGETWO-51983

**Comment by ghost** [comment]
Ok, thank you! Is there any work around to this at all you can think of without modifying the code? Right now we just change out the PHP versions, which isn't a big deal so that the path it finds will always be PHP7.

**Comment by mmgr** [comment]
Hi guys, Any solution on this one.

**Comment by ghost** [comment]
This is fixed now after 2.1, at least, so this can probably be closed.
