### ISSUE TITLE
Readiness check shows missing PHP extensions and different PHP version

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#4183]
So I'm running Magento locally on my machine using Mamp Pro in OSX. I'm running PHP 7, I'm able to do everything fine, but when I want to use the component manager and run the Readiness check, it tells me that I'm missing mcrypt and intl when I have those installed, and the PHP version says 5.5.31 when I'm running 7. I was able to install Magento and during that readiness check all was fine. Not sure why it's different for components. Is this a bug?
![screen shot 2016-04-17 at 8 32 26 pm](https://cloud.githubusercontent.com/assets/17520868/14593167/e039e308-04db-11e6-877b-38e503a335d6.png)

**Comment by vancoz** [comment]
Hi @samleeiii, probably you have different version of php and extensions for your CLI.
Please check it - run "php -v" to check version and "php -m" to check installed extensions.

Thank you!

**Comment by zerobrapsgiven** [comment]
Yeap I've tried that and I get the below. So you can see it does says 7.0.0 and you can also see both mcrypt and intl in the list. It's very bizarre.

Sams-iMac:bin samsuke$ php -v
PHP 7.0.0 (cli) (built: Dec  8 2015 16:39:19) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
You have new mail in /var/mail/samsuke
Sams-iMac:bin samsuke$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by vancoz** [comment]
What about your crontab (which runs updater/cron.php and bin/magento setup:cron:run)?
Probably it points to old version of php
BTW, I recommend you to install php 7.0.4 or 7.0.5

**Comment by zerobrapsgiven** [comment]
Ok I will update the PHP version.

Regarding the cron, how do I set what php version it uses? Do I need to set an environment variable or something else?

**Comment by vancoz** [comment]
@samleeiii when you set the command in crontab you can use full path to php version, for example /local/lib/php5/bin/php /var/www/html/update/cron.php
So even if your CLI does use correct version cron can point to old one.

**Comment by zerobrapsgiven** [comment]
That did the trick, thanks!
