### ISSUE TITLE
Configurable product is not added to cart, when using "add to cart" on category page.

### ISSUE THREAD

**Issue by martins-scandiweb** [magento/magento2#4184]
In http://magento2-demo.nexcess.net/men/tops-men/jackets-men.html

if I choose size and color and then press "add to cart", then I get redirected to product detail page with message "You need to choose options for your item."

Expected result
1. Configurable product is added to cart and success message is shown and user stays on category page.

**Comment by parekhreena** [comment]
#2574

**Comment by parekhreena** [comment]
Same issue reported earlier here reference id - #2574

**Comment by piotrekkaminski** [comment]
Internal ID MAGETWO-47017

**Comment by rickwhitehead** [comment]
Any progress on this issue please? Can I help investigate?

**Comment by rickwhitehead** [comment]
Hi @piotrekkaminski can I get involved with this? It's a show stopper for me.

**Comment by rickwhitehead** [comment]
@tanya-soroka ??

**Comment by piotrekkaminski** [comment]
cc @elenleonova 
@rickwhitehead it's on our backlog but might take some time to implement.

**Comment by devhn** [comment]
Any news on this? The error messages are also missplaced by showing below the add-to-cart button instead next to non-selected attribute.

**Comment by rickwhitehead** [comment]
@piotrekkaminski @tanya-soroka how do we get involved please?

**Comment by rickwhitehead** [comment]
IS THERE A PULL REQUEST? IS ANYBODY DOING ANYTHING? PLEASE RESPOND!

**Comment by veloraven** [comment]
We are working on this issue.

**Comment by rganin** [comment]
Fixed under MAGETWO-47017 ticket.

**Comment by rickwhitehead** [comment]
Is there a pull request for this fix please?

**Comment by carlowens** [comment]
Hi,
Could anyone tell me which specific version of Magento 2 has this fix?  Has it been released yet?
Thanks

**Comment by JDavidVR** [comment]
@carlowens it works without problem on 2.1.x

**Comment by carlowens** [comment]
ah ok I am using Magento ver. 2.1.1 but it doesn't seem to be working.  Does each configurable product need it's own attribute set with a default?

**Comment by rickwhitehead** [comment]
@rganin if this issue is fixed please could you link to the pull request or advise of the fix so that people don't waste their time in this repository?

**Comment by antonkril** [comment]
@rickwhitehead, @carlowens, the issue was fixed on develop branch: https://github.com/magento/magento2/commit/e643a6760c3965b705d2d2b16c179285a3138998 

It's scheduled to be merged to 2.1.4

Sorry for the lack of info. We'll discuss issue closing report with more information.

**Comment by rganin** [comment]
ac363e400cffa85e0a2688cce8286c02f5e0e0d2

**Comment by rganin** [comment]
@rickwhitehead there is no public pull-request for this fix, it was implemented under following revisions:
27d2486, cce06d2, d8a2550, 4b96c90, 0025497, 7420329, ac363e4 in `develop` branch and merged in e643a67.

**Comment by rickwhitehead** [comment]
Thank you @rganin, @antonkril & @alankent.  
Asking for myself but also for others who might find this thread/issue: Would you advise simply cloning the current develop branch to implement this fix? or would you patch using files from those 7 commits?

**Comment by antonkril** [comment]
"Develop" branch is not stable, so you should not use it to build production stores. 

If this fix is critical for your project, you can apply the patch. But be aware that patch might be not 100% compatible with your codebase or may cause some new issues.

The most preferred way is to wait till the new Magento version with this patch included is released.

**Comment by rickwhitehead** [comment]
Hi @antonkril , thank you for your speedy response. 
I can't imagine that this bug isn't 100% critical for all but the most very basic of stores, but maybe that's just me? I highlighted this bug for a number of extension developers when I was looking for a workaround - so I'm sure this issue is a show stopper for many. However, Is there a roadmap for Magento 2 releases that we can view/track please? Obviously in particular this thread is interested in v2.1.4. Thank you.

**Comment by rickwhitehead** [comment]
@antonkril , @alankent Please could you respond with timelines/roadmap for next M2 releases?
Looking at the commits that @rganin mentioned for this fix I can already see new files that didn't exist in the last "stable" release v2.1.1, e.g. /dev/tests/functional/tests/app/Magento/Swatches/* and hunting through parent commits to see when these were added is also not that helpful. I'll be back  to either using dev branch or grabbing all 50 files from that referenced pull request?

**Comment by rickwhitehead** [comment]
@antonkril @alankent?
 on commit [0025497](https://github.com/magento/magento2/commit/0025497db036e4ba6154ba454438a79ef76d91e5) merged in [e643a67](https://github.com/magento/magento2/commit/e643a6760c3965b705d2d2b16c179285a3138998) please can I ask why we now have files in /app/code/Magento/ when /app/code doesn't exist in current stable releases 1.1.X ??? I'm busy trying to merge/patch to test this fix and of course this list of 7 commits only records

**Comment by sneakingJ** [comment]
@antonkril Are there any news on this? When will version 2.1.4 come out?

**Comment by helicops** [comment]
Is there any news about this patch?
