### ISSUE TITLE
Can't export to excel or cvs

### ISSUE THREAD

**Issue by enasibrahim** [magento/magento2#4185]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by enasibrahim** [comment]
can't export to excel or cvs, magento 2

**Comment by enasibrahim** [comment]
?

**Comment by enasibrahim** [comment]
?

**Comment by piotrekkaminski** [comment]
@enasibrahim do you still have this problem on latest version? I was not able to reproduce it. Are there any errors in the logs?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
