### ISSUE TITLE
Page messages are displayed on every page

### ISSUE THREAD

**Issue by lennartlott** [magento/magento2#4186]
The page messages are displayed on every next page. 
## For example:
1. Invalid password try
2. Error message is displayed on the login page
3. Go to hompage
4. The message is displayed again.

I tested the error on multiple devices and even on multiple websites (Official Magento Demo, Venroy, Solgirl, ...). On my installation and even on the official magento demo shop the message is displayed on every page again and again.

![ex](https://cloud.githubusercontent.com/assets/6389443/14597973/591adc72-0550-11e6-99d8-ddb7edd4c2e7.png)
![ex1](https://cloud.githubusercontent.com/assets/6389443/14597977/5b7a3238-0550-11e6-9072-8dd991b8efd5.png)
![ex2](https://cloud.githubusercontent.com/assets/6389443/14597978/5d332fbc-0550-11e6-85be-d32e445068bb.png)

**Comment by devhn** [comment]
We experienced the same issue (Magento 2.0.2 and 2.0.4).

**Comment by vkublytskyi** [comment]
@lennartlott, thank you for reporting this issue. We are currently working on resolving it. Internal ticket MAGETWO-46014

**Comment by slavvka** [comment]
Hi @lennartlott, the fixe has been delivered to mainline. See commits 541ec806cae729df118b7844f5d105cbf1a6cec6, 55a6e51296afd2c52cfe7f813a4871ae408f1afc, b4d373919489ccb48af10c5ac287ef39e3af384e, eec31f653e3783d0ba86602c8396fd6e2d159546, af2a8325930ae22e2b7ae3f6513c0068217eacd1, d97ebe56200b73e71d97ca527c99108817586a54, 3120b1e89f48ff630e796c6885aecc3e48c070c8 and 66e6ad66c028e99019c110631df4c9015af4a2ca. Thank you for your contribution to Magento 2!
