### ISSUE TITLE
How to extend layout in Custome module

### ISSUE THREAD

**Issue by kaleberegaurav** [magento/magento2#4188]
I have extended module-catalog block in Test_Catalog(Test is my vendor name and Catalog is module name,in which i am extending block of module-catalog ). I want to add small table element on product view page for which i have created catalog_product_view.xml(location : root\app\code\Test\Catalog\view\frontend\layout\catalog_product_view.xml) But still its not displaying any content from test.phtml file . I dont want to change entire look of product view ,i just want to add small table element. test.phtml contain nothing but static html 

system.log
[2016-04-18 15:03:34] main.CRITICAL: Invalid template file: 'test.phtml' in module: 'Magento_Catalog' block's name: 'content_schedule_block5' [] []

**Comment by shiftedreality** [comment]
Hi @kaleberegaurav 

You should use `<referenceContainer>` statement
Here is how it works for AdminNotification module:

https://github.com/magento/magento2/blob/develop/app/code/Magento/AdminNotification/view/adminhtml/layout/default.xml#L10

You can use before/after options to set position of your block.

**Comment by BaDos** [comment]
Hello @kaleberegaurav

You can try to use the following xml code:

```
<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="content">
            <block class="Magento\Framework\View\Element\Template" name="example" template="Magento_MyModule::test.phtml"/>
        </referenceContainer>
    </body>
</page>
```

**Comment by piotrekkaminski** [comment]
Such questions are best suited for http://magento.stackexchange.com/ or community forums. GitHub is used for issue reports only.
