### ISSUE TITLE
Tooltip position in admin incorrect with select element

### ISSUE THREAD

**Issue by mnjongerius** [magento/magento2#4190]
Before: 
<img width="552" alt="schermafbeelding 2016-04-18 om 15 07 58" src="https://cloud.githubusercontent.com/assets/4756828/14605114/632a5cb6-0577-11e6-85e2-f08e122c8c44.png">

Suggested solution: 
`.accordion .config .value.with-tooltip select + .tooltip{margin-top:-24px;}`

After solution:
<img width="535" alt="schermafbeelding 2016-04-18 om 15 08 46" src="https://cloud.githubusercontent.com/assets/4756828/14605134/7a0a062a-0577-11e6-90ef-e801cff38135.png">

**Comment by odubovyk** [comment]
Thank you for the request. In what browser do you experience the issue?

**Comment by mnjongerius** [comment]
In Google Chrome. Do you need an exact version number?

Op ma 18 apr. 2016 17:18 schreef odubovyk notifications@github.com:

**Comment by odubovyk** [comment]
Thank you, internal ticket MAGETWO-52115

**Comment by MomotenkoNatalia** [comment]
@mnjongerius Internal ticket MAGETWO-52115 is closed and delivered to mainline. Please let us know if you still have an issue.

**Comment by regularlabs** [comment]
Seems this is still an issue.
A solution could be to simply place the tooltip div before the field, so:

```
    protected function _renderValue(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        if ($element->getTooltip()) {
            $html = '<td class="value with-tooltip">';
            $html .= '<div class="tooltip"><span class="help"><span></span></span>';
            $html .= '<div class="tooltip-content">' . $element->getTooltip() . '</div></div>';
            $html .= $this->_getElementHtml($element);
        } else {
...
```

**Comment by irinikp** [comment]
This should not be closed, as it is still an issue in Google Chrome Version 59.0.3071.115
