### ISSUE TITLE
Can not change product attributes in Console\Command

### ISSUE THREAD

**Issue by bkristl** [magento/magento2#4191]
If **Google Analytics** is **enabled** and **Enable Content Experiments** is **enabled** in web administration (menu - stores->configuration->sales->Google API->Google Analytics), then you **can not change products attributes values** in Console\Command.

WHY ?

Because Google Analytics observer (**Magento\GoogleOptimizer\Observer\Product\SaveGoogleExperimentScriptObserver**) is run when an event **catalog_product_save_after** is triggered.

**Magento\GoogleOptimizer\Observer\Product\SaveGoogleExperimentScriptObserver** extends **\Magento\GoogleOptimizer\Observer\AbstractSave** in which is defined initialization request params 
**function _initRequestParams**.

But when you use **Console\Command** there is  **no HTTP request** !!!! So this observer must not run when is used CLI environment.

**Comment by mazhalai** [comment]
@bkristl thank you for reporting, we have created MAGETWO-52045 to investigate and fix.

**Comment by duhon** [comment]
@bkristl  please specify the version where you can reproduce the problem, because the function isDataAvailable is to prevent the run of _initRequestParams. You have created a custom console command?

**Comment by piotrekkaminski** [comment]
@bkristl we need your response to the question above to proceed with the fix.

**Comment by duhon** [comment]
@bkristl closing due by non-responsiveness.
