### ISSUE TITLE
The Checkout UI Components JSON is ridiculously large and also quite big

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#4217]
https://gist.github.com/adragus-inviqa/8c2496312760c122aefb390c66bf2419 (<-- your browser might crash opening this 💥 ).
That's a one liner copied from a response source and pretty-printed into 45587 lines. :trollface: 

I hope you agree that those countries _desperately_ need a **single** global object.

**Comment by antonkril** [comment]
Agree. And we have it in backlog (MAGETWO-40098). This ticket will influence the priority of the story.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/The-Checkout-UI-Components-JSON-is-ridiculously-large-and-also/idi-p/46881).
