### ISSUE TITLE
Wysiwyg can not insert more than two images

### ISSUE THREAD

**Issue by dexterityzx** [magento/magento2#4221]
Version 2.0.4
## Steps to reproduce
1. 
   ![1](https://cloud.githubusercontent.com/assets/13892193/14617780/959a4836-057d-11e6-8938-c543c2e1cafd.png)
2. 
   ![2](https://cloud.githubusercontent.com/assets/13892193/14617787/9d7c8794-057d-11e6-97bd-c6f304457211.png)
3.  insert the image
   ![3](https://cloud.githubusercontent.com/assets/13892193/14617793/a12ec730-057d-11e6-9dd0-b9a69620ff6b.PNG)
4. repeat 1-3 and the screen get frozen
## Expected result
1. Insert a picture in wysiwyg editor
## Actual result
1. screen get frozen

**Comment by mrkhoa99** [comment]
@dexteritycc There are any errors log on browser console?

**Comment by dexterityzx** [comment]
only warnings, and each time I insert the image will have two warnings, but I am able to use the wysiwyg editor again after the first two warning. The screen get frozen like below after I tried to insert the second picture.
![capture](https://cloud.githubusercontent.com/assets/13892193/14632304/f28b299e-05e5-11e6-82f2-93f0cd9e5a6d.PNG)

**Comment by shiftedreality** [comment]
Hi @dexteritycc 

Created internal ticket MAGETWO-52284 for investigation.
Thank you for submitting.

**Comment by datbunneh** [comment]
Hello @dexteritycc 

This issue is fixed and merged. Also it has to be included in 2.0.7.
