### ISSUE TITLE
How do you check if a user is logged in?

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#4222]
I've tried the following and it seemed to work but seems inconsistent. All of a sudden it stops working. Is there a better way?

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); $customerSession = $objectManager->get('Magento\Customer\Model\Session'); if($customerSession->isLoggedIn()) : ?>

Insert html here...

<?php endif ?>

**Comment by adragus-inviqa** [comment]
That seems ok to me. But just so you know ahead of time: your issue's going to be closed as "forum". You should ask questions on m2's forums or here: http://magento.stackexchange.com/

**Comment by zerobrapsgiven** [comment]
ah ok thanks!
