### ISSUE TITLE
How magento2 calculate subtotal?

### ISSUE THREAD

**Issue by AskBear** [magento/magento2#4223]
### I was tried to change `price format` to like `NT$5`(non decision) by the following way:

file path: magento_dir/vendor/magento/zendframework1/library/Zend/locale/Data/zh_Hant.xml
I was changed `¤#,##0.00` to `¤#,##0`

```
<currencyFormatLength>
    <currencyFormat type="standard">
        <pattern>¤#,##0</pattern>
    </currencyFormat>
    <currencyFormat type="accounting">
        <pattern draft="contributed">¤#,##0;(¤#,##0)</pattern>
    </currencyFormat>
</currencyFormatLength>
```
### But some pages like product detail pages or checkout sidebar, still format by `.00`.

So I also add the code like below:
file path: magento_dir/vendor/magento/framework/locale/Format.php

```
// forced precision to 0
$totalPrecision = 0;
$requiredPrecision = 0;
$result = [
    //TODO: change interface
    'pattern' => $currency->getOutputFormat(),
    'precision' => $totalPrecision,
    'requiredPrecision' => $requiredPrecision,
    'decimalSymbol' => $decimalSymbol,
    'groupSymbol' => $groupSymbol,
    'groupLength' => $group,
    'integerRequired' => $integerRequired,
];
```
### Then I get the result below:

![123](https://cloud.githubusercontent.com/assets/14832915/14627474/60895c68-0627-11e6-8278-5cae6176bc0d.png)
The subtotal doesn't calculate in rounding format.
It's actual price must be 530..
So.. How can I fix this problem?
Or.. Where may I control the subtotal calculate in rouding format.
I was tried to find the path, but I just find `$totals['subtotal']` which was already calculate.

**Comment by piotrekkaminski** [comment]
@AskBear this question is better suited for http://magento.stackexchange.com/. GitHub is only used for issue reports.
