### ISSUE TITLE
Magento 2 Direction RTL Issue

### ISSUE THREAD

**Issue by yagneshponkiya** [magento/magento2#4225]
Magento provides facility to specify different locale for each store view from the backend. my question is if i assign locale Persian, Urdu or anything (RTL Locale). does that add "dir='RTL' to HTML tag ? or if i want to do that how should i  ?

**Comment by piotrekkaminski** [comment]
@yagupatel this is a question better suited for http://magento.stackexchange.com/ or community.magento.com. Github is only used for error reports.
