### ISSUE TITLE
Stock Item collection is not a collection object.

### ISSUE THREAD

**Issue by spipu** [magento/magento2#4226]
This is a*\* technical issue*\* about **CatalogInventory Stock Item** object.

There is a model and a resource model, but there is no collection object.

And the object name ResourceModel\Stock\Item\Collection exists, but it does not extends the good class, it is more a search result than a collection :

https://github.com/magento/magento2/blob/2.0/app/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Item/Collection.php#L16

=> for specific processing, it is impossible to load a lot of specific entities without using the repository, and by using directly model and collections (for specific integration for example)

Laurent

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53361

**Comment by PascalBrouwers** [comment]
Not too mention that the repository getList function expects a \Magento\CatalogInventory\Api\StockItemCriteriaInterface instead of \Magento\Framework\Api\SearchCriteria which makes it very hard to work with.

**Comment by PascalBrouwers** [comment]
@spipu so, it is fixed?

**Comment by spipu** [comment]
no, and i think it will not :( because what they implement for stock item does not need collection. It uses a new way to manage them, by using mapper and query builder.
