### ISSUE TITLE
As Low As Pricing Removes second select option

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#4236]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add configurable product with color and size selector
3. Add variable priced configurations
4. View product with "As low as" pricing
   .
## Expected result
1. As low as pricing is active with color and size selectors visible
## Actual result
1. Only color selector is visible
2. Unable to add item to cart due to This is a required field. error on the missing size selector.

**Comment by magnetic5355** [comment]
This error does not appear to be related to as low as.

The issue is related to different options available between child  product x & y

Example x color is red and y color is blue

X has sizes S and M and Y has sizes L and XL

If we add sizes S M L and XL to both products the option to select size appears

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53358

**Comment by magento-engcom-team** [comment]
@caesarcxiv, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
