### ISSUE TITLE
How to run Multiple Magento2 setup with Nginx

### ISSUE THREAD

**Issue by nileshadiyecha** [magento/magento2#4238]
I want to configure multiple Magento2 setup (like 3 setups) with single domain name. like..

If I browser the URL as below then it should load separate directory based on Nginx request.

> test.com/m21  > /var/www/m21
> test.com/m22  > /var/www/m22
> test.com/m23  > /var/www/m23

So can anyone guide me to setup nginx virtual host configuration file which can fulfill my about requirement to load multiple Magneto2 setup over the single domain name.

Waiting for helping hand.

**Comment by maksek** [comment]
Please use forum for questions, GitHub only for bugs and PR. 
Forum link - https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2
