### ISSUE TITLE
Please combine tier pricing messages into block sentences...

### ISSUE THREAD

**Issue by hidonet** [magento/magento2#424]
Please combine tier pricing messages into block sentences...

**Comment by vpelipenko** [comment]
@hidonet, sorry for so late response, but I hope it will still useful for all. If we look at app\code\Magento\Catalog\view\base\templates\product\price\tier_prices.phtml we can see that phrase 'Buy %1 for %2 each and save %3' consists of 4 smaller phrases: 'Buy %1 for %2', 'each', 'and', 'save'. First 2 can be easy combined, but the last two are the part of template, contain HTML formatting and depend on settings. It means that the last part of phrase 'and save %3' will appear on frontend if we enable showing detailed prices in backend settings. Does it make sense for you if we combine only first to phrases and leave the rest as is?

**Comment by hidonet** [comment]
I know this file and sentences. But in some languages ( for example in Turkish ) meaningfully combining sliced sentences is very difficult. Please add single sentence for every single state.

**Comment by vpelipenko** [comment]
Internal ticket has been created: MAGETWO-33393. We'll investigate the issue and come back with our solution.

**Comment by kokoc** [comment]
@hidonet Thank you for reporting the issue. The team has processed this ticket. Code changes have just been deployed in version 0.74.0-beta11. Could you please verify the issue?
