### ISSUE TITLE
Account settings password fields missing common style

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4240]
## Steps to reproduce
1. Install Magento 2.0.4
2. Go to Account Settings
## Expected result
1. Password fields are styled as all other fields
## Actual result
1. Password fields are missing common styling - http://screencast.com/t/ucdiU6R72
2. However if You edit another user(not Your own) - password fields are styled as expected

**Comment by mazhalai** [comment]
@werdlv there is nothing in that screencast. Can you please repost?

**Comment by jsakars** [comment]
@mazhalai the image is there - double checked

**Comment by mazhalai** [comment]
@werdlv thanks, see it now! We have created MAGETWO-52177 to investigate and fix.

**Comment by mazhalai** [comment]
@werdlv this has been fixed in scope of another task, related commit https://github.com/magento/magento2/commit/f22dd6d

Closing this. Please feel free to open a new issue, if problems persist.
