### ISSUE TITLE
Not able to set time format of datetime picker to 24 hour notation

### ISSUE THREAD

**Issue by joost-florijn-kega** [magento/magento2#4243]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add Date Form field to an Admin Form with time format 'HH:mm'.
## Expected result
1. Able to select time in 24 hour notation.
## Actual result
1. The time is always converted to the 12 hour notation. 
   ![image](https://cloud.githubusercontent.com/assets/16535591/14677402/e1b2e166-0711-11e6-903d-c326d1fcaba8.png)

I have found why this is happening. In [calendar.js](https://github.com/magento/magento2/blob/develop/lib/web/mage/calendar.js#L380) at row 380 there are dateTimeFormat defined that are used to convert date and time format string. 

In the [documentation of the jquery time picker addon](http://trentrichardson.com/examples/timepicker/#input_examples) you can read that 'HH' stand for the 24 hour notation and 'hh' notation. The calendar widget forces you to use the 12 hour notation instead to leave it up the developer.

**Comment by mazhalai** [comment]
@joost-florijn-kega thank you for reporting, we have created MAGETWO-52178 to investigate and fix.

**Comment by anton-huz** [comment]
Please notice that e6f9261 doesn't fix issue. We'll deliver proper fix under MAGETWO-52590.
The main issue that on client side there is no necessity to replace `HH` to `hh`.

**Comment by anton-huz** [comment]
@joost-florijn-kega you can review issue.
52e6fd6 delivered to develop branch.
