### ISSUE TITLE
Catalog search index status is always processing

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#4244]
After running the indexer for magento 2.0.4 catalog search, it's status is still processing
![magento2_search_index](https://cloud.githubusercontent.com/assets/17834386/14678839/a7994c44-0717-11e6-96cd-d4580f6e6d9c.png)

Note: search is working though.

**Comment by neeelz** [comment]
I have the same issue. Did someon solve this problem!?

**Comment by PascalBrouwers** [comment]
I solved my issue by manually changing the status to 'valid' in the table indexer_state for catalogsearch_fulltext.

**Comment by piotrekkaminski** [comment]
@PascalBrouwers were you running it from command line on via cron?

**Comment by PascalBrouwers** [comment]
Both, but my mistake was I did not read the migration readme entirely. It states you have to run indexes BEFORE you start the migration proces. I did not do that, thus my catalogsearch_fulltext kept being in the 'processing' state.

**Comment by choukalos** [comment]
Note prior to doing a migration - need to ensure indexes are all indexed/completed.

Closing.
