### ISSUE TITLE
Warning: setcookie() expects parameter 3 to be integer, float given in

### ISSUE THREAD

**Issue by xdoctordog** [magento/magento2#4250]
## Steps to reproduce
1. Admin Area: Go to Stores -> Configuration -> Admin -> Security
2. Type really big value in Admin Session Lifetime (seconds) ( pic.1 )
3. Click 'Save Config'
## Expected result
1. Successful saving.
## Actual result
1. 'There has been an error processing your request'  page ( pic.2 )
2. In reports I see the error 'Warning: setcookie() expects parameter 3 to be integer, float given in'
3. I can't use admin area any more

![pic-1](https://cloud.githubusercontent.com/assets/4630880/14700836/9f96eb08-07aa-11e6-8313-bde611a856d3.jpg)

![pic2](https://cloud.githubusercontent.com/assets/4630880/14700740/36b6a3d0-07aa-11e6-9d11-e51efe8fcbd0.jpg)

[2049668291.magento.report.txt](https://github.com/magento/magento2/files/229364/2049668291.magento.report.txt)

**Comment by tkotosz** [comment]
I have run into the same issue previously and I had to run `update core_config_data set value=9999 where path='admin/security/session_lifetime';` to fix the admin. I just forgot to report it.

**Comment by mazhalai** [comment]
@xdoctordog  Thank you for reporting, we have created ticket MAGETWO-52245 to investigate and fix.

**Comment by bwaters** [comment]
Resolved recently fixed on develop branch

**Comment by mazhalai** [comment]
@bwaters can you please point to specific commits?

**Comment by bwaters** [comment]
Checking to limit maximum value was added here -- https://github.com/magento/magento2/commit/7cef233efaffef02df7b4e9e5b99c526f03286ec

**Comment by mazhalai** [comment]
@bwaters Thank you!
@xdoctordog thank you for reporting, we are closing, since this has already been fixed.
