### ISSUE TITLE
Missing some functions in Stores > Configuration > Design page

### ISSUE THREAD

**Issue by davidnguyen2205** [magento/magento2#4251]
First, I installed Magento 2 with sample data by cloning from git:

```
git clone https://github.com/magento/magento2.git /var/www/html
cd /var/www/html && composer install
git clone https://github.com/magento/magento2-sample-data.git
cd magento2-sample-data/dev/tools
php -f build-sample-data.php -- --ce-source="/var/www/html"
cd /var/www/html
php bin/magento setup:upgrade
```

Then it's working. However, when i go to Stores > Configuration > Design, i just see: Search Engine Robots and my Magento version is 2.0.0

After that, i setup a new Magento website with a package from https://www.magentocommerce.com/download
And i got more functions in that Design page: Design Theme, HTML Head, Header, Footer,.... with Magento's version is 2.0.4

So what is the current version Magento on Git?
And how can i change my theme in Git version?

Thanks.

**Comment by Alkar778** [comment]
All design configurations were moved to **Content -> Design -> Configuration**

**Comment by mazhalai** [comment]
@davidnguyen2205 does @Alkar778 's suggestion solve your issue?

**Comment by davidnguyen2205** [comment]
Yes, thank you so much :)
Just close this!

**Comment by weilunallen** [comment]
They should update the Documentation. I was so baffle by it.

**Comment by ghost** [comment]
I think it would be better if they started using the software they release instead, the current design area with just robots.txt is one of the many stupid things in Magento 2.
