### ISSUE TITLE
Web Setup Wizard gives 401 after upgrade

### ISSUE THREAD

**Issue by armindoPR** [magento/magento2#4252]
Hi,

i've installed Magento 2.0.2 (download it from the site and installed it on my server). and upgraded it to 2.0.4 via Web Setup Wizard.

Everything went fine and i can see on my backend the correct version, but when i try to access the Web Setup Wizard i get a 401 page

"Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard"

I've cleaned the cache, sessions, everything i can think off.

Thanks

Regads
Armindo

**Comment by mazhalai** [comment]
@armindoPR

> i try to access the Web Setup Wizard

without login in admin? Then yes, this is expected behavior. After update, sessions are expired, so you need to login to admin, and then access Web setup wizard. Also, check your file permissions.

**Comment by armindoPR** [comment]
Hi,
i've logged out on admin area and logged in again and the issue is the same.  I've tried in different browsers and the behavior is the  same.
I've checked the permissions and it seems OK.

**Comment by mazhalai** [comment]
@armindoPR any errors in var/log? what about browser? any errors there?

**Comment by armindoPR** [comment]
Hi,
no errors in the browser.
On var/log the debug.log file has the following line
[2016-04-26 14:05:58] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://#MY_URL#/gestao/admin/index/index/key/bb1efeb85c929f37fda1c0e0aab1c64bffe64e4af1a0d46524f4e7076dc9676d/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []

**Comment by mazhalai** [comment]
@armindoPR do you have entry point set as /pub?

**Comment by armindoPR** [comment]
Hi,
what do you mean by an entry point ?
The installation was the default (download the zip and install), just changed the admin URL to a different one.

**Comment by mazhalai** [comment]
There is a way to set server root to pub, in that case, setup does not work. 

Anything in server logs? Also, 401 means unauthorized error, please see this for more details: http://www.checkupdown.com/status/E401.html

We have no idea about this errors, because we cannot reproduce it.

**Comment by armindoPR** [comment]
Hi,

i've managed to solve this.
It was a missing php.ini files.

Thanks
