### ISSUE TITLE
Request: Add @api annotation to \Magento\Framework\Encryption\EncryptorInterface

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#4254]
Please bless `\Magento\Framework\Encryption\EncryptorInterface` with the `@api` annotation.  

Even though the method `\Magento\Customer\Api\AccountManagementInterface::getPasswordHash()` is marked as part of the stable `@api`, it would be great to be able to use the other methods in `\Magento\Framework\Encryption\EncryptorInterface` directly.

**Comment by mazhalai** [comment]
@Vinai we have created ticket MAGETWO-52423 to add this annotation.

**Comment by piotrekkaminski** [comment]
@Vinai we would like to first move away from mcrypt to something better maintained and only then mark it as stable. I'm closing this request for now and it was merged into requirements for mcrypt replacement MAGETWO-38939.

**Comment by Vinai** [comment]
@piotrekkaminski Thank you for the feedback!
I don't see what is mcrypt specific on the interface, but if some work in that area is bundled in the internal ticket you mentioned then that is great. Looking forward to seeing the results!
