### ISSUE TITLE
Retrieving the current quote requires use of non-@api methods.

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#4257]
## Steps to reproduce
1. Create a class with a dependency on `\Magento\Quote\Api\Data\CartInterface`
2. Add a product to the cart
3. Execute the code within the same session
## Expected result
1. The `CartInterface` instance represents the current quote
2. `\Magento\Quote\Api\Data\CartInterface::getItems` returns the items in the cart
## Actual result

The injected `CartInterface` instance is empty.
To retrieve the current quote items `\Magento\Checkout\Model\Session::getQuote()` has to be used.
This is problematic since neither `\Magento\Checkout\Model\Session` nor `\Magento\Quote\Model\Quote` are blessed with the `@api` interface.

The alternative would be to use `\Magento\Quote\Model\GuestCart\GuestCartRepository::get()` or `\Magento\Quote\Api\CartManagementInterface::getCartForCustomer`, but for guests that would require having the masked cart id.  
It is quite common for customizations to require access to the current cart contents. It would be nice if that could be handled with a simple dependency on `CartInterface`.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53269

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Retrieving-the-current-quote-requires-use-of-non-api-methods/idi-p/46395).
