### ISSUE TITLE
Can't upgrade from 2.0.2 to 2.0.4 by the back-end "Web Setup Wizard"

### ISSUE THREAD

**Issue by kgvconsulting** [magento/magento2#4260]
Can't upgrade to v2.0.4 with Web Wizard. System Upgrade version PASS - showing current and new versions

Readiness
![screenshot 2016-04-21 10 34 17](https://cloud.githubusercontent.com/assets/11282348/14712829/b7ce3440-07ac-11e6-8b63-13e9b48b7795.png)
 check fail
- HOWEVER all Cron's are setup and run without issues

xxxxxxx@flowersvibe.com [~/folder/bin]# php magento cron:run
Ran jobs by schedule.
xxxxxxx@flowersvibe.com [~/folder/bin]# php magento cron:run
Ran jobs by schedule.
xxxxxxx@flowersvibe.com [~/folder/bin]# php magento cron:run
Ran jobs by schedule.
xxxxxxx@flowersvibe.com [~/folder/bin]#
- PHP version is current as well

xxxxxxx@flowersvibe.com [~/folder]# php -v
PHP 5.6.20 (cli) (built: Apr 19 2016 22:31:46)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

No Magento reports or Log errors found

Could you please help?

**Comment by mazhalai** [comment]
@kgvconsulting there are additional crons (total of 3) that need to be setup, please read http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html

**Comment by kgvconsulting** [comment]
Hello @mazhalai Thank you for your respond, I have those 3 setup and running as well

Current Cron Jobs
Minute  Hour    Day Month   Weekday Command Actions
*/1 \*   \*   \*   \*   /xxx/bin/php -c /xxx/xxxx/bin/php.ini /xxxx/xxxxx/xxxx/bin/magento cron:run > /xxxx/xxxx/xxxxx/var/log/magento.cron.log&     Edit      Delete
*/1 \*   \*   \*   \*   /xxx/bin/php -c /xxx/xxxx/bin/php.ini /xxxx/xxxxx/xxxx//update/cron.php > /xxxx/xxxx/xxxxx/var/log/update.cron.log&  Edit      Delete
*/1 \*   \*   \*   \*   /xxx/bin/php -c /xxx/xxxx/bin/php.ini /xxxx/xxxxx/xxxx/bin/magento setup:cron:run > /xxx/xxxx/xxxx/var/log/setup.cron.log&

All cron's are up and running,

**Comment by kgvconsulting** [comment]
also here is my composer.json

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\Framework\": "lib/internal/Magento/Framework/",
            "Magento\Setup\": "setup/src/Magento/Setup/",
            "Magento\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\Sniffs\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\Tools\": "dev/tools/Magento/Tools/",
            "Magento\Tools\Sanity\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\TestFramework\Inspection\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\TestFramework\Utility\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

**Comment by colyield** [comment]
I got the same problem before. It seems sometimes the cron task will not run automatically. I ran the command manually and the problem was gone.

**Comment by kgvconsulting** [comment]
Thank you @colyield , I did that a couple of times, unfortunately don't work still don't recognize that the cron is running. Really cant figure out what to do?

**Comment by mazhalai** [comment]
@kgvconsulting anything in you var directory? Any files beginning with `.`

**Comment by colyield** [comment]
Are you using the root account to run the command? You need to use the web user to run it and I think something wrong with file permission.

**Comment by kgvconsulting** [comment]
Hi @mazhalai 

yes:

1st file - .update_cronjob_status
- text/x-generic .update_cronjob_status ( ASCII text )

{
    "readiness_checks": {
        "file_permissions_verified": true
    },
    "last_timestamp": 1461269403,
    "current_timestamp": 1461269463
}

2nd file - .htaccess

.htaccess ( ASCII text )

Order deny,allow
Deny from all

@colyield  - yes I run the cron jobs sign as account user not root

**Comment by mazhalai** [comment]
@kgvconsulting there needs to be another file called `.setup_cronjob_status` did `bin/magento setup:cron:run` run successfully?

**Comment by kgvconsulting** [comment]
Ok I did it now the file show in /var

.setup_cronjob_status ( ASCII English text, with very long lines )

{
    "readiness_checks": {
        "db_write_permission_verified": true
    },
    "php_checks": {
        "php_version_verified": {
            "responseType": "success",
            "data": {
                "required": "~5.5.0|~5.6.0|~7.0.0",
                "current": "5.6.20"
            }
        },
        "php_extensions_verified": {
            "responseType": "success",
            "data": {
                "required": {
                    "0": "curl",
                    "1": "dom",
                    "2": "hash",
                    "3": "openssl",
                    "4": "simplexml",
                    "5": "xmlwriter",
                    "8": "gd",
                    "10": "iconv",
                    "11": "mcrypt",
                    "14": "spl",
                    "15": "xsl",
                    "16": "intl",
                    "17": "mbstring",
                    "18": "ctype",
                    "34": "zip"
                },
                "missing": []
            }
        },
        "php_settings_verified": {
            "responseType": "success",
            "data": {
                "always_populate_raw_post_data": {
                    "message": "Your PHP Version is 5.6.20, but always_populate_raw_post_data = -1.\n \t        $HTTP_RAW_POST_DATA is deprecated from PHP 5.6 onwards and will be removed in PHP 7.0.\n \t        This will stop the installer from running.\n\t        Please open your php.ini file and set always_populate_raw_post_data to -1.\n \t        If you need more help please call your hosting provider.",
                    "helpUrl": "http://php.net/manual/en/ini.core.php#ini.always-populate-settings-data",
                    "error": false
                }
            }
        }
    },
    "current_timestamp": 1461270505
}

**Comment by mazhalai** [comment]
Do you still have an error in websetup wizard readiness check? is your cron user in same group as the webserver user?

**Comment by kgvconsulting** [comment]
No the error is gone. the readiness check PASS, and the back up to now waiting for the update to go trough

**Comment by kgvconsulting** [comment]
![screenshot 2016-04-21 16 32 38](https://cloud.githubusercontent.com/assets/11282348/14723461/3feb40f2-07df-11e6-8e92-8a889bd61eca.png)

The update is currently running ....

**Comment by colyield** [comment]
So, any idea that why we need to run the scheduled cron command manually?

**Comment by kgvconsulting** [comment]
Nope I did that once after the install and setting up the cron jobs, dont have idea why

**Comment by kgvconsulting** [comment]
I'm still having this screen, but notting is changing at least the browser dont show 
![screenshot 2016-04-21 16 44 02](https://cloud.githubusercontent.com/assets/11282348/14723698/6598b8d8-07e0-11e6-89fb-0cf10bade0a8.png)

Is that OK, how long should take the upgrade?

**Comment by colyield** [comment]
Sometimes the cron jobs won't work and I have to reindex manually too. I think the magento2 is not good as magento 1.9. And the backend always take time to load the data. 

The update will take time to process. Just wait.

**Comment by kgvconsulting** [comment]
ok thanks

**Comment by mazhalai** [comment]
@kgvconsulting as long as it says it is "running" it is good.

**Comment by kgvconsulting** [comment]
OK :)

**Comment by mazhalai** [comment]
@colyield only if you haven't setup a magento user as recommended.  http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html

**Comment by kgvconsulting** [comment]
OK thank you I did that from beginning

**Comment by colyield** [comment]
@mazhalai Actually, I did. I use apache account to run the cron jobs. I will figure it out later.

**Comment by kgvconsulting** [comment]
it still showing the same upgrade screen, do i need to refresh the browser?

**Comment by mazhalai** [comment]
it takes time, since it depends on composer, and composer is downloading all the packages and unzipping etc... As long as there is no error, it should be fine. You can check var/ if there is any indication of an error.

**Comment by kgvconsulting** [comment]
ok thank you

**Comment by kgvconsulting** [comment]
@mazhalai  - It still display the same

https://cloud.githubusercontent.com/assets/11282348/14723698/6598b8d8-07e0-11e6-89fb-0cf10bade0a8.png

 like 4 hours no changes in /var folder the last file update/change was 4:35 PM like 3 hours ago. No errors that I can see reported there, the cron's files are running and update regularly, Just want to ask how long usually take, could it take more than 3-4 hours for upgrade? maybe more?

**Comment by mazhalai** [comment]
whats in `var/.update_status.log` or `.update_status.txt`?

**Comment by colyield** [comment]
I suggest you run all the three cron jobs manually again.

**Comment by kgvconsulting** [comment]
it is last recorder 4:35PM

 .update_status.txt ( ASCII text )

[2016-04-21 20:35:02 UTC] Job "maintenance_mode {"enable":true}" has been started
[2016-04-21 20:35:02 UTC] Magento maintenance mode is enabled.
[2016-04-21 20:35:02 UTC] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-04-21 20:35:02 UTC] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.4"}]}" has been started
[2016-04-21 20:35:02 UTC] Starting composer update...
[2016-04-21 20:35:02 UTC] ./composer.json has been updated

**Comment by kgvconsulting** [comment]
no changes after that
 the crons are updating regularly the last file change was 8:04 PM a minute ago

**Comment by colyield** [comment]
How about just run manually again? Last time I did this couple times. The cron jobs seem running but the update did not process until I ran the command manually.

**Comment by kgvconsulting** [comment]
the log file state:

update.cron.log ( ASCII text, with CRLF line terminators )

X-Powered-By: PHP/5.6.20
Content-type: text/html; charset=UTF-8

Cron is already in progress...

**Comment by kgvconsulting** [comment]
.update_cronjob_status ( ASCII text )

{
    "readiness_checks": {
        "file_permissions_verified": true
    },
    "last_timestamp": 1461283803,
    "current_timestamp": 1461283863
}

.setup_cronjob_status ( ASCII English text, with very long lines )

{
    "readiness_checks": {
        "db_write_permission_verified": true
    },
    "php_checks": {
        "php_version_verified": {
            "responseType": "success",
            "data": {
                "required": "~5.5.0|~5.6.0|~7.0.0",
                "current": "5.6.20"
            }
        },
        "php_extensions_verified": {
            "responseType": "success",
            "data": {
                "required": {
                    "0": "curl",
                    "1": "dom",
                    "2": "hash",
                    "3": "openssl",
                    "4": "simplexml",
                    "5": "xmlwriter",
                    "8": "gd",
                    "10": "iconv",
                    "11": "mcrypt",
                    "14": "spl",
                    "15": "xsl",
                    "16": "intl",
                    "17": "mbstring",
                    "18": "ctype",
                    "34": "zip"
                },
                "missing": []
            }
        },
        "php_settings_verified": {
            "responseType": "success",
            "data": {
                "always_populate_raw_post_data": {
                    "message": "Your PHP Version is 5.6.20, but always_populate_raw_post_data = -1.\n \t        $HTTP_RAW_POST_DATA is deprecated from PHP 5.6 onwards and will be removed in PHP 7.0.\n \t        This will stop the installer from running.\n\t        Please open your php.ini file and set always_populate_raw_post_data to -1.\n \t        If you need more help please call your hosting provider.",
                    "helpUrl": "http://php.net/manual/en/ini.core.php#ini.always-populate-settings-data",
                    "error": false
                }
            }
        }
    },
    "current_timestamp": 1461270505
}

**Comment by kgvconsulting** [comment]
Also here are:

 .update_queue.json ( empty ) - no content

composer.json ( ASCII text )

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.4",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\Framework\": "lib/internal/Magento/Framework/",
            "Magento\Setup\": "setup/src/Magento/Setup/",
            "Magento\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\Sniffs\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\Tools\": "dev/tools/Magento/Tools/",
            "Magento\Tools\Sanity\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\TestFramework\Inspection\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\TestFramework\Utility\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

**Comment by kgvconsulting** [comment]
@mazhalai still no result does not upgrade continue to stay the same, any advise?

**Comment by colyield** [comment]
Delete all the files in ./var/ folder except the .htaccess file. And try to upgrade again. 

Also, try to run the cron jobs manually. That is what I did last time.

**Comment by kgvconsulting** [comment]
@colyield Ok I will give a try, by the way I did run the cron manually earlier but didn't help at all

**Comment by kgvconsulting** [comment]
hi @colyield , just want to be certain that im deleting the correct content, following is the content of the /var/ folder located in magento folder

 ./
../
backups/
cache/
composer_home/
composer.json
generation/
.htaccess
install_composer_packages.json
log/
page_cache/
report/
resource_config.json
.setup_cronjob_status
tmp/
.type.json
update_composer_packages.json
.update_cronjob_status
.update_queue.json
update_status.log*
.update_status.txt*
view_preprocessed/

So you are advising me to delete all if the above content except - .htaccess?

Thank you

**Comment by kgvconsulting** [comment]
@mazhalai 
@colyield , 

also could you please advise the proper order of tasks:

1st delete the ./var content except .htaccess file
2nd - run cron's manually that would be: bin/magento cron:run
and what about: bin/magento setup:cron:run?

I'm a bit confuse because I found this for upgrading using command line from @mazhalai #3961:

TO upgrade by command line:
1. composer require magento/product-community-edition 2.0.4 --no-update
2. composer update
3. Clean cache, and di and generation folders. 
4. bin/magento setup:upgrade

However I don't have var/di folder???? 

this is the content of var/ 

/
../
backups/
cache/
composer_home/
composer.json
generation/
.htaccess
install_composer_packages.json
log/
page_cache/
report/
resource_config.json
.setup_cronjob_status
tmp/
.type.json
update_composer_packages.json
.update_cronjob_status
.update_queue.json
update_status.log*
.update_status.txt*
view_preprocessed/

Could you give me tip about the process

Thank you in advance

**Comment by colyield** [comment]
I set magento to developer mode. Actually those files will be generated automatically again if you delete them except the .htaccess file. And make sure to backup the files in "backups" folder. When you delete the .update_cronjob_status, .setup_cronjob_status, the current upgrade will stop and you can run the upgrade again. 

IMO, everything is about the file permissions and the cron jobs. If something does not work, first check  the file permissions, then run the cron jobs manually, as apache user. I have webmin installed, so I ran the jobs from there as apache user.

bin/magento cron:run  
update/cron.php  
/bin/magento setup:cron:run

Before doing this, I suggest you backup the magento to make sure if you screw up the update, you can always rollback to the previous state. I think the ./var/di folder will only appear when you set the magento mode to production. Correct me if I am wrong.

**Comment by mazhalai** [comment]
@kgvconsulting as @colyield said,  you dont have to delete `di` if it doesn't exist.
Those steps you quoted from #3961 should work. All should be executed in Magento root folder.

**Comment by kgvconsulting** [comment]
@mazhalai Thank you does the following looks correct:

composer require magento/product-community-edition 2.0.4 --no-update
composer update
rm -rf var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

**Comment by mazhalai** [comment]
You only need di:compile if you are in production mode, but there is no harm in running it on other modes. Other wise everything looks correct.

**Comment by kgvconsulting** [comment]
@mazhalai - before i started with command I gave one last try on web wizard update this is the new change i got

![screenshot 2016-04-22 14 46 07](https://cloud.githubusercontent.com/assets/11282348/14751686/15347ecc-0899-11e6-91c8-bb8922b5fd74.png)

Could you please advise?

**Comment by mazhalai** [comment]
@kgvconsulting this usually means, there is an error, in either running crons, or something else. Check contents of var directory for more details. Also, is there any error in browser's console log?

**Comment by kgvconsulting** [comment]
also the ~/var/report folder have file with error

a:4:{i:0;s:27:"No such entity with id = 18";i:1;s:11277:"#0 /xxxx/vendor/magento/module-catalog/Model/CategoryRepository.php(118):

**Comment by kgvconsulting** [comment]
this is the only new file I see can you advise which file to look?

**Comment by kgvconsulting** [comment]
When I install Magento I didn't install the samples just the bare framework

**Comment by kgvconsulting** [comment]
@mazhalai It i very weird, no the screen change on its own to:

![screenshot 2016-04-22 15 02 33](https://cloud.githubusercontent.com/assets/11282348/14752113/58c4fbec-089b-11e6-850a-c05efe9395e8.png)

Really stuck?

**Comment by colyield** [comment]
Did you just try to Run the three cron jobs manually at this time?

**Comment by kgvconsulting** [comment]
Yes I gave a try couldn't see anything else for reported errors that is

**Comment by kgvconsulting** [comment]
actually the screen change shortly after I run the cron jobs manually

**Comment by kgvconsulting** [comment]
At least Magento could place a task percentage indicator during the upgrade or even better showing the stages that pass and if they are OK or failed That would be much more useful to get where is the fail

**Comment by colyield** [comment]
I told you. That's the trick.

**Comment by kgvconsulting** [comment]
but still is hanging there I decided to give last chance on the web wizard, if does not work will try command line

**Comment by colyield** [comment]
It does take time to upgrade. Wait half hour to see what will happen. Run the jobs again if it's still not moving.

**Comment by kgvconsulting** [comment]
Ok I will I'm waiting 2 hours till now give or take almost that time, the problem is that noting show if someting is running at all will see Thank you

**Comment by kgvconsulting** [comment]
OK still is showing the same screen I did run manually the crons again so far no other changes, do I need to wait more or to proceed with command line upgrade?

**Comment by mazhalai** [comment]
Did you setup cron with logs as [suggested](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html), anything in those logs?

**Comment by kgvconsulting** [comment]
nope noting all is clean running as started

**Comment by kgvconsulting** [comment]
do you want me to look in particular file?

**Comment by kgvconsulting** [comment]
@mazhalai @colyield 

OK the command line took 15 minutes still dont get it why Magento insist to use web wizard is totally not functional, any how all the processes run without errors however when log in in admin side on the bottom continue to display v 2.0.2 So don't really know what is going on is very time waist process

![screenshot 2016-04-22 17 05 22](https://cloud.githubusercontent.com/assets/11282348/14754992/029935fa-08ad-11e6-9f56-436e07d0a9e0.png)

![screenshot 2016-04-22 17 06 30](https://cloud.githubusercontent.com/assets/11282348/14755015/2e6f5146-08ad-11e6-9f8f-c405c2c3752f.png)

![screenshot 2016-04-22 17 13 35](https://cloud.githubusercontent.com/assets/11282348/14755078/a78dda98-08ad-11e6-844d-50119aea4c60.png)

![screenshot 2016-04-22 17 13 57](https://cloud.githubusercontent.com/assets/11282348/14755085/aefeaeec-08ad-11e6-9cfe-79c056a5fbfd.png)

**Comment by mazhalai** [comment]
@kgvconsulting Web Setup is recommended for those on shared hosting, and dont have access to command line. All others should use command line.

**Comment by kgvconsulting** [comment]
Ok thank you, any idea about why the admin side show v2.0.2 on the bottom right? Even after the upgrade went trough

**Comment by mazhalai** [comment]
I think there is an existing bug about that. if you check your root composer.json
it should say

```
 "require": {
        "magento/product-community-edition": "2.0.4",
```

**Comment by kgvconsulting** [comment]
"name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.4",
        "composer/composer": "@alpha"

**Comment by kgvconsulting** [comment]
OK i think this should be end of all. Thank you again @mazhalai and @colyield for your patience and support.

**Comment by mazhalai** [comment]
@kgvconsulting you're welcome. Please report a new issue if you have any additional problems.

**Comment by kgvconsulting** [comment]
Thanks Sure

**Comment by kgvconsulting** [comment]
Hi @mazhalai 

After the update, front and back of magento works fine except one issue, following described. I found other articles about the same however there was no answer from Magento about that. Could you please advise?

other reported issues for that same error:

https://github.com/magento/magento2/issues/4001
https://community.magento.com/t5/Technical-Issues/Fatal-error-magento-setup/m-p/26444#M335

Issue with web wizard setup page: I tried to access the web wizard setup page from admin back side and got this error

Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132' in /xxxx/xxxx/magento_root/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/xxxx/xxxx/...', 132, Array) #1 /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/ObjectManager.php(84): Magento\Framework\ObjectManager\Config\Compiled->extend(Array) #2 /xxxx/xxxx/magento_root/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\ObjectManager\ObjectManager->configure(Array) #3 /xxxx/xxxx/magento_root/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): Magento\Setup\Model\ObjectManagerProvider->get() #4 [internal function]: Magento\Setup\Mvc\Bootstrap\InitParamListener->authPreDispatch(Object(Zen in /xxxx/xxxx/magento_root/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by mazhalai** [comment]
Please clean you var/generation and var/di folder.

**Comment by kgvconsulting** [comment]
Great thank you now works!

**Comment by kgvconsulting** [comment]
@mazhalai 

I did upgrade with SSH to the new v2.0.5 as we did before and encounter the same issue with WebSetup access so I did follow the same instructions to clean the var/generation unfortunately after that the whole magento stop working front and back end reporting this error:


Warning: ltrim() expects parameter 1 to be string, object given in /xxxx/xxxxx/xxxx/vendor/magento/framework/Code/Generator/EntityAbstract.php on line 152

Notice: Uninitialized string offset: 0 in /xxxx/xxxxx/xxxxx/vendor/magento/framework/Autoload/ClassLoaderWrapper.php on line 81

Notice: Uninitialized string offset: 0 in /xxxx/xxxx/xxxx/vendor/composer/ClassLoader.php on line 317

Notice: Uninitialized string offset: 0 in /xxxx/xxxx/xxxxx/vendor/composer/ClassLoader.php on line 349
An error has happened during application run. See exception log for details.

exception log:

2016-05-01 17:34:52] main.CRITICAL: exception 'Magento\Framework\Exception\LocalizedException' with message 'Source class "" for "Magento\Framework\App\Response\Http\Interceptor" generation does not exist.' in /xxxxx/xxxxx/xxxxx/vendor/magento/framework/Code/Generator.php:171

Please advise

**Comment by mazhalai** [comment]
@kgvconsulting Thank you for reporting, closing this issue.

**Comment by kgvconsulting** [comment]
hi @mazhalai 

I cant get the new upgraded version to show up, Is there a way to verify if the upgrade really went trough?

Thanks

**Comment by kgvconsulting** [comment]
![screenshot 2016-05-27 01 01 28](https://cloud.githubusercontent.com/assets/11282348/15598300/a4a62c9a-23a6-11e6-8bda-24e1cc8a3b7d.png)

Even I did try to upgrade using SSH up to 2.0.5 Does not show that?

**Comment by mazhalai** [comment]
@kgvconsulting please do not post on closed issues.

This shows you have the latest 2.1.0-rc1. It should show up in the lower right hand side when you login to admin. Also, it should be in your root composer.json file's require section as `"magento/product-community-edition": "2.1.0-rc1",`

**Comment by kgvconsulting** [comment]
@mazhalai Im sorry but I have the same issue I don't think the upgrade went trough, the bottom right of the admin show v 2.0.2

and yes in the web system update is showing what versions are available but the lowest one in the bottom v 2.02 state - (CURRENT)

![screenshot 2016-05-27 09 54 13](https://cloud.githubusercontent.com/assets/11282348/15610085/773adca6-23f1-11e6-8d00-a738db7d95d6.png)

And also for whatever reason I no longer am able to perform back up from Admin the screenshot above show all back ups no longer are displayed nor when I try to make back up is responding I press on the OK button but there is no reaction at all see the following screenshot

![screenshot 2016-05-27 10 00 47](https://cloud.githubusercontent.com/assets/11282348/15610185/f42aae94-23f1-11e6-9482-b464e619c1a0.png)

**Comment by mazhalai** [comment]
@kgvconsulting But this is a new issue, please start a new thread.

**Comment by kgvconsulting** [comment]
@mazhalai OK I did #4747
