### ISSUE TITLE
v2.0.4 Invoice amount for an order has wrong currency code

### ISSUE THREAD

**Issue by snez** [magento/magento2#4264]
## Steps to reproduce
1. Create a store view with a currency that is different from the base currency.
2. Place an order using a payment method that can capture() a payment.
3. View the created invoice for the order in the admin area.
## Expected result

The invoice amount should have the currency symbol of the currency used on the store view.
## Actual result

The base currency symbol is used with the store amount, giving a false impression of the amount captured.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53267

**Comment by alena-marchenko** [comment]
Closing the issue, fix has been delivered to develop branch.
