### ISSUE TITLE
GET REST API requests with JSON body

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#4265]
Have you considered adding the ability to add information in a `GET`request's _body_? 
I'm thinking about that `searchCriteria` GET param here (e.g. for `GET /V1/products` or `GET /V1/orders`).

```
GET https://shop.com/rest/us/V1/orders?searchCriteria[filterGroups][0][filters][0][field]=store_id&searchCriteria[filterGroups][0][filters][0][value]=3&searchCriteria[filterGroups][0][filters][1][field]=status&searchCriteria[filterGroups][0][filters][1][value]=processing
```

_(fugly, innit?)_

vs

```
GET https://shop.com/rest/us/V1/orders

{"searchCriteria":{"filterGroups":[{"filters":[{"field":"store_id","value":3},{"field":"status","value":"processing"}]}]}}
```

I do understand that a GET body is not standard, but it's not an error, neither. Having a GET body will permit more complex API queries, looks nicer, maybe even avoid some request length problems.

I got this idea trying to use Postman with M2: https://github.com/postmanlabs/postman-app-support/issues/131.

But I'm guessing it's too late now, huh? Something to consider, though.

**Comment by mazhalai** [comment]
@adragus-inviqa thank you for reporting, we have created MAGETWO-52425 to investigate and fix.

**Comment by hshar7** [comment]
Hi @adragus-inviqa early on Magento architects decided this was done because we didn’t want to add payload to a GET request and we didn’t want to make this search feature a POST request because it would violate RESTful principles. But you are right it is hard on the eyes :v:

**Comment by adragus-inviqa** [comment]
👍

**Comment by gilles6** [comment]
@adragus-inviqa You can do it with the combination of json_decode() and http_build_query().

```
<?php

$token = "xxxxxxxxxxxxxxxxxx";
$api = "/V1/customers/search";

$json = '
{
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "email",
                        "value": "%",
                        "condition_type": "like"
                    }
                ]
            }
        ]
    }
}
';
$j = json_decode($json);
$get_params = http_build_query($j);

$ch = curl_init("http://my.website.com/index.php/rest".$api."?".$get_params);

curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
  "Content-Type: application/json", 
  "Authorization: Bearer ".$token,
));

$result = curl_exec($ch);
$result = json_decode($result, 1);
print_r($result);

?>
```
