### ISSUE TITLE
After deleting files under 'view_preprocessed' folder they dont appear again when reloading site

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#4267]
I'm testing some small LESS changes in my theme. After every change I delete the contents inside:

**pub/static/frontend/mytheme** and **var/view_preprocessed**

Then I reload my site but the contents of var/view_processed (css and source folders) are not created so the new LESS changes aren't applied. However the site loads fine displaying elements using the previous LESS values.

After visiting 10-15 pages the css and source folders are created again and I can see my changes finally.

I constantly delete the Magento cache so thats not the issue. I've also set Firefox and Chrome to not save cookies, history, etc. I even set permissions to 777 to discard that cause.

Why dont the contents of var/view_preprocessed folder get created right after the first reloading of my site?

I'm doing my LESS modifications on a custom theme which inherits from Blank.
Magento 2.0.4
Ubuntu 14

**Comment by rganin** [comment]
Magento Full Page Cache caches the whole pages. Try to clean FPC along with view_preprocessed folder. Some changes like changes in layout update and/or DI may require full cache cleanup that can be done by running `php -f bin/magento cache:clean` or manually from admin panel System -> Cache Management.
For development purposes you can turn on the development mode in `.htaccess` by uncommenting the corresponding SetEnv directive and turn off caching in System -> Cache Management.

**Comment by jibrandlr** [comment]
@rganin All cache types are disabled from backend, do I still need to turn on development mode in .htaccess?

**Comment by ntoombs19** [comment]
@lgarridoj Static assets are only automatically generated in develop mode. In production mode you must run `bin/magento setup:static-content:deploy` when you want static assets to be deployed.

**Comment by lgarridoj** [comment]
I've changed to develop mode but got the same results. I have to reload the site many times or visit more pages until I can see my css changes
