### ISSUE TITLE
Issue while Importing Currency Rates - GBP

### ISSUE THREAD

**Issue by Victor4G** [magento/magento2#4268]
I needs to use three currency for my store GBP, EUR, USD. 
I have set the allowed currency from config.
Now when i try to import rates it only fetch Euro rates not GBP and when i click on SAVE CURRENCY RATES button, it shows blank value for GBP field and error like: 
"Please correct the input data for USD => GBP rate"

We have tested on 2 to 3 projects with latest magento 2.0.4 but all have the same problem.

so, Please guide us to resolve this issue, meanwhile we setup fix GBP rate.

![screenshot from 2016-04-22 12 44 40](https://cloud.githubusercontent.com/assets/6058016/14734591/2181a4e4-0889-11e6-8e44-8f4789dbbf5a.png)

**Comment by mazhalai** [comment]
@Victor4G thank you for reporting, we have created MAGETWO-52243 to investigate and fix.

**Comment by arkadiych** [comment]
@Victor4G, Webservicex is out of order. 
Fixer.io as additional currency converter service has been added in scope of https://github.com/magento/magento2/issues/2757
Future releases should have yet one an additional currency service into Magento2.
