### ISSUE TITLE
Varnish Cache Plus support?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#4271]
Hi,

This supports SSL, normal Varnish doesn't.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by cscd98** [comment]
bah humbug
