### ISSUE TITLE
v2.0.4 Credit memos with adjustment fees cannot be fully refunded with a second credit memo

### ISSUE THREAD

**Issue by snez** [magento/magento2#4272]
## Steps to reproduce
1. With USD as the base currency, create a second store with a GBP store view currency
2. Set the GBP currency rate of that store to 0.6
3. Place an order in the GBP store
4. Issue a credit memo from the admin area, setting an Adjustment Fee of $1
5. Try to create a second credit memo to refund the remaining $1 and completely close the order
   ![Example adjustment fee](http://i.cubeupload.com/u1rbrV.png)
## Expected result

The second credit memo should allow us to refund the remaining $1
## Actual result

The credit memo has a total due amount of $0 and cannot fully refund the order
![Example of the issue](http://i.cubeupload.com/pxg74d.png)

**Comment by snez** [comment]
As a side note to this, when the credit memo is accessed from the payment method in the called cancel() method, it seems to be missing some key data, see **store_to_base_rate** and **store_to_order_rate** below:

```
[creditmemo (Magento\Sales\Model\Order\Creditmemo)] => Array
    (
        [order_id] => 37
        [store_id] => 2
        [customer_id] => 2
        [billing_address_id] => 74
        [shipping_address_id] => 73
        [global_currency_code] => USD
        [base_currency_code] => USD
        [store_currency_code] => USD
        [order_currency_code] => GBP
        [store_to_base_rate] => 0.0000
        [store_to_order_rate] => 0.0000
        [base_to_global_rate] => 1.0000
        [base_to_order_rate] => 0.6000
```

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53264

**Comment by vherasymenko** [comment]
Steps to reproduce:

1. Install Magento latest develop version
2. Go to Admin side
3. Click "Stores > All Stores"
4. Click "Add new store view"
5. Enter name and code, set status "Enabled" and click "Save"
6. Click "Stores > Configuration"
7. In header side choose created Store View
8. Click "General > Currency Setup"
9. "Default Display Currency" set "British Pound Sterling"
10. "Allowed Currencies" set "British Pound Sterling" then click "Save"
11. Click "Stores > Currency rates"
12. In row GPB enter 0.6 and click "Save"
13. Place order on "GB" store view"
14. Go to Admin side "Sales > Orders"
15. Receive Invoice and after that click "Credit Memo"
16. Scroll page down and enter in field "Adjustment Fee" 1$ then click "Refund"
17. Click "Credit Memo" again and scroll page down
18. Pay attention on "Subtotal" in Refund Totals table.

AR: Displayed 0$
ER: Should be displayed $1

**Comment by mcspronko** [comment]
@ishakhsuvarov @maksek Can you please assign this one on me? I will work on it. Thanks.

**Comment by ishakhsuvarov** [comment]
Closing, as issue is fixed in the `develop` branch with the linked PR and commits.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69378
