### ISSUE TITLE
/admin/customer/index/index/ report on fresh install "Magento ver. 2.0.4" without sample data

### ISSUE THREAD

**Issue by victorchiriac89** [magento/magento2#4273]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by mazhalai** [comment]
@victorchiriac89 can you please add the screenshots and logs?

**Comment by mazhalai** [comment]
@victorchiriac89 closing due to non-responsiveness
