### ISSUE TITLE
Category page of configured products takes 1 min to load on first load - preventing production rollout

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#4276]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add swatch attribute with use product image and 1500 options
3. Add 1000 configured products mapped to 5000 simple products
## Expected result
1. Page load time is similar to non configured product category < 1s

This is an urgent issue for us as it is preventing a production rollout. Any guidance would be helpful.
## Actual result
1. 1 min page load time
2. attached is a profiler log

[profiler.xlsx](https://github.com/magento/magento2/files/232555/profiler.xlsx)

**Comment by urielbeaupre** [comment]
We had some similar issues with our project.

Are you using nginx or apache?
Php 5 or 7?
Is the page in developer mode?

**Comment by magnetic5355** [comment]
Php7 + nginx

We may have tracked part of the issue down to thumbnail creation when the products are new. We are performing further tests and will update. 

Issue is not apparent on category pages with simple products.

**Comment by magnetic5355** [comment]
Also we tested in production mode

**Comment by piotrekkaminski** [comment]
@caesarcxiv can you provide a sample site that has this issue? what kind of products are you selling that have so many attributes? 

cc @choukalos for a possible use case

**Comment by magnetic5355** [comment]
@piotrekkaminski - the dev site is currently only internal. 

Fashion products that vary by color attribute is the use case. Manufacturers use names such as sunset or desert tangerine which both are different shades of orange for the same product. This requires the usage of the manufacturer name as the attribute value.

Multiply this by 100's of manufacturers and thousands of products you have a massive color list for configurable products.

We are 99% sure that the issue is related to the thumbnail/swatch generation on first load of the category page when there are new products. Our image file sizes are 5-8MB and we use the product image for the swatch.

Is there a way to generate all thumbnails/swatches via CLI?

**Comment by veloraven** [comment]
@caesarcxiv could you please provide used Magento version?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
