### ISSUE TITLE
Unable to customize the navigation menu by extending one variable from navigation.less file

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#4277]
Not sure whether this is an issue but I've not found an answer anywhere.

I've created a new theme which inherits from Blank.
I want to add a border to the navigation menu so I created the file `_navigation_extend.less` which contain this line:
`@navigation__border: 3px solid blue;`

But does not work.

Is`@navigation__border: ' '` variable the right one to edit in order to add a border?
This variable can be found in `navigation.less` file (line 11)

I can only add the border by including this code in my `_navigation_extend.less` file:
`.navigation { border: 3px solid blue; }` but I'd prefer to style it by extending an existing variable from the navigation menu (if it exists)

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
