### ISSUE TITLE
PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table_catalogsearch_fulltext_scope1' doesn't exist

### ISSUE THREAD

**Issue by PaddlePop** [magento/magento2#4280]
I installed Magento 2.0.4 on my shared hosting though CPanel and Softaculous. I have 2 problems currently. 
1. I cannot add new products. It gave me error message - **'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table_catalogsearch_fulltext_scope1' doesn't exist'.**
2. I can only view my webpage(product categories with no products) when I disabled all the cache types under the cache management. Whenever I enable it, it will give me this error - 

**"There has been an error processing your request**

**Exception printing is disabled by default for security reasons.**

**Error log record number: 1112151317950"**

I went to check the error and on the report it says **"Query catalog_view_container does not exist"**. 

Anyone knows how I can solve it?

Thanks in advance :)

**Comment by daim2k5** [comment]
@PaddlePop regaring point one it look like the database is not created? did you run the indexer?

**Comment by PaddlePop** [comment]
Hi, 

Yes I have. Currently I have 3 cron jobs. 

2 added by softaculous
~   php /home/admin/public_html/Store/bin/magento cron:run > /dev/null
~      /usr/local/cpanel/3rdparty/bin/php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli.php --backup --auto=1 --insid=545_59569

And the last one I added it myself because magento gave me a system error - "one or more indexer is invalid". So I added this ~ php-cli -q /home/admin/public_html/Store/bin/magento indexer:reindex > /dev/null 2>&1 

Not too sure if I added correctly though. If not please guide me. Thanks

**Comment by piotrekkaminski** [comment]
@PaddlePop do you still have this issue?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by r-martins** [comment]
I was having this problem locally, and solved by disabling full_page cache.

> bin/magento cache:disable full_page
