### ISSUE TITLE
Connection "default" is not defined

### ISSUE THREAD

**Issue by xplodeart** [magento/magento2#4281]
Fresh Magento installation on vagrant fails using the web setup or the CLI. The database is fine and it connects fine as well.

Magento version 2.0.4 downloaded from the official ZIP repo.

[ERROR] exception 'DomainException' with message 'Connection "default" is not defined' in /vagrant/www/vendor/magento/framework/App/ResourceConnection.php:115

Anybody seen this before?

**Comment by gewaechshaus** [comment]
https://community.magento.com/t5/Installing-Magento-2/Connection-quot-default-quot-is-not-defined/m-p/35526/highlight/false#M1313

**Comment by mazhalai** [comment]
@xplodeart are you using HHVM?

**Comment by gewaechshaus** [comment]
https://github.com/magento/magento2/issues/3583#issuecomment-216261351

**Comment by mazhalai** [comment]
@xplodeart we are closing this as non-responsive

**Comment by netorica** [comment]
this happens even not using HHVM with magento 2.3.1 

I followed the instructions here https://devdocs.magento.com/guides/v2.3/install-gde/composer.html

and I am currently using PHP 7.2.16-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:29) ( NTS )

here's my installation setup

```
php bin/magento setup:install --base-url=http://magepwa.test --db-host=localhost --db-name=magepwa --db-user=root --db-password=pass --backend-frontname=admin --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=xxxx --language=en_US --currency=USD --timezone=UTC --use-rewrites=1
```

my php PDO Setup is 
pdo_mysql.default_socket | /var/run/mysqld/mysqld.sock | /var/run/mysqld/mysqld.sock

and this socket file exist 

Referenced to new issue https://github.com/magento/magento2/issues/22198

**Comment by ianrushton88** [comment]
Check that you have an env.php file in your app/etc folder and that your DB details are defined correctly
