### ISSUE TITLE
Issue with blank theme search input

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4282]
Steps to reproduce
## Using Blank Theme.
1. Click inside search.
2. Click to hide search.
3. Click to show search.
## Expected result
1. Search input displays and stays on the screen.
## Actual result
1. Search input disappears due to input already being active.

**Comment by BenGlassAtlas** [comment]
I can also replicate in the Luma theme (using a mobile).

**Comment by BenGlassAtlas** [comment]
As a quick workaround without editing core files I used this jQuery (with require.js), this stops the previous toggle from firing then we toggle the active class. 

``` js
require(['jquery'], function($) {
    var searchLabel = $('#search_mini_form .label');

    searchLabel.on('click', function(event) {
        event.preventDefault();
        searchLabel.toggleClass('active');
    });
});
```

**Comment by ghost** [comment]
Thank you Ben, I thought I was being a bit lame reporting such a small issue... but it really counts - especially on a serious release.

**Comment by daim2k5** [comment]
Here a small video to see the error https://drive.google.com/file/d/0B3kBFTm6f_Kab09EemZRZmg1X0U/view?usp=sharing

**Comment by BenGlassAtlas** [comment]
@daim2k5 That seems a bit different to the issue I'm having, here is a gif of the problem on Luma mobile. When I click on the search icon the search bar opens then immediately closes, this is on a demo store using the Luma theme (no customisations). I can also replicate on a local environment which uses a custom theme and Luma as a parent.

![luma](https://cloud.githubusercontent.com/assets/8895777/14786741/233c0d62-0af8-11e6-97f1-eeb8c82030ff.gif)

@xAvarice Which is the issue you're having? If mine is different I will create a new ticket for it.

**Comment by ghost** [comment]
@BenSpace48 I'm having that exact same issue as you. Thank you for the gif. I don't see any problem at all with Daim's video - I figure compared to this issue I don't have to look closely to compare.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53263

**Comment by daim2k5** [comment]
@BenSpace48 @xAvarice looks like i had a different bug, thanks for the gif

**Comment by alena-marchenko** [comment]
Closing the issue, fix has been delivered to develop branch.
