### ISSUE TITLE
Wrong regex in sales rule

### ISSUE THREAD

**Issue by Sanuch** [magento/magento2#4283]
Hi

You are trying to parse attributes from rule condition by old regex [Rule.php#L351](https://github.com/magento/magento2/blob/develop/app/code/Magento/SalesRule/Model/ResourceModel/Rule.php#L351)
but now condition looks differently `a:7:{s:4:"type";s:46:"Magento\SalesRule\Model\Rule\Condition\Combine";s:9:"attribute";N;s:8:"operator";N;s:5:"value";s:1:"1";s:18:"is_value_processed";N;s:10:"aggregator";s:3:"all";s:10:"conditions";a:1:{i:0;a:7:{s:4:"type";s:52:"Magento\SalesRule\Model\Rule\Condition\Product\Found";s:9:"attribute";N;s:8:"operator";N;s:5:"value";s:1:"1";s:18:"is_value_processed";N;s:10:"aggregator";s:3:"all";s:10:"conditions";a:1:{i:0;a:5:{s:4:"type";s:46:"Magento\SalesRule\Model\Rule\Condition\Product";s:9:"attribute";s:5:"color";s:8:"operator";s:2:"==";s:5:"value";s:2:"53";s:18:"is_value_processed";b:0;}}}}}`

**Comment by daim2k5** [comment]
@Sanuch thanks for your bug report. Can you give us maybe more information. What Rule did you try to apply? Did you use magento 2.0.4?

**Comment by Sanuch** [comment]
Hi @daim2k5 

I tried to create cart price rule which should base on a product attribute.
I think it's customer's specific case and I cannot reproduce it on v2.0.4

**Comment by piotrekkaminski** [comment]
@Sanuch if you are able to reproduce, please open a new ticket. I will close this ticket for now.
