### ISSUE TITLE
Customer cannot edit any of his addresses

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4284]
M2 2.0.4
A customer cannot edit any of his addresses anywhere in frontend - dashboard, address book, checkout, etc.
When trying to edit an address, it always redirects to customer dashboard!
No errors, no nothing is logged.

**Comment by daim2k5** [comment]
@devdesco-ceo I can't repoduce this behaivour. Can you tell us some more details

**Comment by devdesco-ceo** [comment]
I do not know what to say. No error messages, nothing. In developer mode it works, but not in production mode.

**Comment by sevos1984** [comment]
Have you tried clearing browser cache?

**Comment by devdesco-ceo** [comment]
Yes, all caches flushed, including browser cache. Tried in different browsers. You can try yourself at https://endohaus.com
