### ISSUE TITLE
Error installing sample data after magento 2 setup

### ISSUE THREAD

**Issue by nikul** [magento/magento2#4288]
## Steps to reproduce
1. Installed Magento by downloading zip package.
2. Run bin/magento sampleadata:deploy
3. Tried to run bin/magento setup:upgrade
## Expected result

Magento site working with sample data
## Actual result

'Magento_BundleSampleData' component already exists

**Comment by mazhalai** [comment]
@nikul did you download the zip package with sample data? Then this result is expected. Also, did you start on a clean database? Did you previously have sample data installed?

**Comment by nikul** [comment]
1. I first did install magento 2.0.4 then downloaded sampledata zip from https://github.com/magento/magento2-sample-data and unzipped on root of magento 2 setup.
2. I also tried like unzip files of sampledata on magento root before install and then started installation.
3. Then i tried with install magento first and used command line (ie. bin/magento sampledata:deploy then bin/magento setup:upgrade). 

In 2nd case I got an error during installation like "Class Magento\Catalog\Model\ResourceModel\Product\Gallery does not exist"

in 1st and 3rd cases i got error like "Autoload error: Magento_BundleSampleData" component already exists" after finishing processes.

**Comment by mazhalai** [comment]
So you got sample data modules 2 ways, once via zip and once via `bin/magento sampleadata:deploy`, thats why the error was thrown. 
These steps should work
1. Download zip without sample data and install magento
2. Run `bin/magento sampleadata:deploy`
3. Run `bin/magento setup:uppgrade`, 

Make sure your database is clean before you begin.

**Comment by nikul** [comment]
Ok.
And how to install sample data using zip if already downloaded without CLI?

**Comment by mazhalai** [comment]
If you have Magento installed already, you can go to admin->System->Web Setup Wizard-> Component Manager (you will have to enter your connect credentials and sync) List of sample data should be available if you click the "install" and select the samples you want and proceed with the steps.
However, this means that you do not require the samples zip that you downloaded.

**Comment by nikul** [comment]
Ok thanks. Finally I did installed using command line.

One more thing, after installed sampledata my site becomes too much slow in front and back ends. Taking more than 5 mins to load any page.
Anything am I missing?

I am using windows os and xampp.

**Comment by mazhalai** [comment]
Windows is not officially supported, only Ubuntu and Centos.
Also, try setting up [varnish cache](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html). But not sure how to configure that on windows.

Closing, since this issue has been resolved. Please open a new issue if problems persist.

**Comment by nikul** [comment]
Thanks for the guide!

**Comment by alankent** [comment]
Just a note that 5 mins to load every page is certainly not normal. I would be checking to make sure your machine or any processes are not thrashing etc. (Not sure if "5 mins" is an exaggeration. If accurate, no, that is not normal.)

**Comment by nikul** [comment]
Yes @alankent . It is taking time for first time in every page load. Please check attached screen for home page. Though sometimes page loads quickly within 15-20 seconds after surfing different pages of site.

![home-page](https://cloud.githubusercontent.com/assets/266397/14809314/ca4309a6-0ba9-11e6-8fa3-de5d67931a78.PNG)
