### ISSUE TITLE
Category with subcategory having product not display in layered navigation.

### ISSUE THREAD

**Issue by RakeshJesadiya** [magento/magento2#4289]
Categories in layered navigation are only rendered if Category in has no children.

I am having categories structure for 4th level. If any 3rd categories having sub categories along with products - then it isn't showing at layered navigation.

![gsfko](https://cloud.githubusercontent.com/assets/18594535/14775137/664cca56-0ada-11e6-891b-9355a1bf8011.png)

In above category structure, Arrow with red mark are not display inside layered navigation. if we remove its subcategory product then its display inside layered navigation.

I have checked inside magento fresh installation and its not working. If we remove the subcategory products then its display in layered navigation OR only display category in layered if category no subcategory.

**Comment by psol7** [comment]
https://github.com/magento/magento2/issues/2121
Same problem never resolved.
No one seems to want to address the issue, but definitively a major magento 2 bug.
Yet to see 1 instance out there demo or live with layered category showing subcategory that are anchored.
Magento 2 is not viable for stores with more than a hand full of products and categories.
 if you have hundred of nested categories and counting on a working layered category filter, as of today, I am afraid you are out of luck.
Mag 1.9 layered navigation is working so beautifully, what gives?

**Comment by choukalos** [comment]
I'm marking this as a bug and closing as it is a dup of #2121 .  I've linked an internal issue to track resolution - please see #2121 .

**Comment by LdannieL** [comment]
And #2121 is also closed as a non-issue when in fact this is never resolved!?

Layered Navigation doesn't work with 2nd level categories, not even in Magento 2.2.3 version!?

**Comment by devamitbera** [comment]
Issue at logical implementation at  [\Magento\Catalog\Model\Layer\Filter\AbstractFilter](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Layer/Filter/AbstractFilter.php#L394)

Current condition `$optionCount < $totalSize;` should be  `$optionCount  =< $totalSize;`

## Modified Method is 

> protected function isOptionReducesResults($optionCount, $totalSize)
>     {
>         return $optionCount  =< $totalSize;
>     }

**Comment by nareshphp1** [comment]
@devamitbera I try but it gave me following error:
Parse error: syntax error, unexpected '<' in /vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php on line 394

**Comment by navneetDots** [comment]
> @devamitbera I try but it give following error:
> Parse error: syntax error, unexpected '<' in /vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php on line 394
> I am getting this error on frontend. Any other solution?

Please use like this:
protected function isOptionReducesResults($optionCount, $totalSize)
{
return $optionCount <= $totalSize;
}

**Comment by nareshphp1** [comment]
@navneetDots thanks for reply. Actually I have already fixed this issue.

**Comment by nareshphp1** [comment]
> > @devamitbera I try but it give following error:
> > Parse error: syntax error, unexpected '<' in /vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php on line 394
> > I am getting this error on frontend. Any other solution?
> 
> Please use like this:
> protected function isOptionReducesResults($optionCount, $totalSize)
> {
> return $optionCount <= $totalSize;
> }

@navneetDots thanks for reply. Actually I have already fixed this issue.
