### ISSUE TITLE
Unable to translate inline for checkout

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4290]
Still having the same issues with parts that cannot be translated. When translating them inline, and clearing cache storage the entered translations do not appear.
Using Magento 2.0.2
![2016-04-25_14h51_12](https://cloud.githubusercontent.com/assets/13572447/14784955/7025f71e-0af8-11e6-8c03-4c09883f11b0.png)

Isues in step 2 of checkout
![2016-04-25_15h01_50](https://cloud.githubusercontent.com/assets/13572447/14784960/76d8c3c0-0af8-11e6-99f5-b0be9d09ee1d.png)

Same issues on checkout step 2

**Comment by SidneyBilliet** [comment]
wa unable to reopen ticket 2652. Some translate bugs were resolved, but not those mentioned above

**Comment by thomvanderboon** [comment]
@SidneyBilliet These issues have all already been resolved in latest **development** branch. Problem still persists in 2.0.4. 

I know of only one remaining translation issue on development branch: https://github.com/magento/magento2/issues/4181

You can check it on my development test site: http://devshop.vdb.nl

**Comment by BenGlassAtlas** [comment]
I'm having problems translating some text in 2.0.4, in particular:

```
"Cart Subtotal","Subtotal"
"Remove","Delete"
"Go to Checkout", "Checkout"
"View and edit cart", "View bag"
```

**Comment by SidneyBilliet** [comment]
![2016-05-12_11h29_52](https://cloud.githubusercontent.com/assets/13572447/15210260/e81a6cf6-1835-11e6-9943-6e3a221e8eb1.png)

Still not able to translate these fields

**Comment by piotrekkaminski** [comment]
@SidneyBilliet did you try on the develop branch? 
@antboiko please check

**Comment by SidneyBilliet** [comment]
@piotrekkaminski , no Piotr, I did not try on develop branch. I tried on 2.0.5.
I don't know how to test on develop branch.

**Comment by thomvanderboon** [comment]
@SidneyBilliet This issue has already been resolved in "development branch" about a month ago. I have just rechecked and it works OK on "development branch"
@antboiko Pls close issue as it has already been resolved in "development branch".
@piotrekkaminski See e-mail :)

**Comment by kanduvisla** [comment]
Is this issue already fixed in 2.0.7?

**Comment by jibrandlr** [comment]
I just upgraded to 2.1.0 and this issue has been fixed

**Comment by Gorkyman** [comment]
@davidalger @thomvanderboon  can we get a commit # for this fix?
