### ISSUE TITLE
Customer Import - Gender is not imported

### ISSUE THREAD

**Issue by zinittest** [magento/magento2#4293]
## Steps to reproduce
1. Create CSV file for customer import with gender fields filled with valid values (Male, Female, ...). 
2. Choose "Customers Main File", "Add/Update Complex Data" options. 
3. Import data.
## Expected result
1. Gender data is properly saved.
## Actual result
1. None of imported customers have gender info saved. DB fields in `customer_entity`.`gender` column are filed with zeroes or nulls. 

P. S. Probably error occurs because gender data are not replaced with corresponding constant values on data preparation step (https://github.com/magento/magento2/blob/develop/app/code/Magento/CustomerImportExport/Model/Import/Customer.php#L403), so system is trying to insert string values to DB column of integer type. I was able to import gender data with following ugly piece of code inserted before new customer check https://github.com/magento/magento2/blob/develop/app/code/Magento/CustomerImportExport/Model/Import/Customer.php#L406: 

if (false !== strpos($entityRow['gender'], 'Male')) {
    $entityRow['gender'] = 1;
} elseif (false !== strpos($entityRow['gender'], 'Female')) {
    $entityRow['gender'] = 2;
} else {
    $entityRow['gender'] = 3;
}

Of course it requires more proper fix.

**Comment by piotrekkaminski** [comment]
The export file includes same numerical values so it is consistent. @ilol what do you think?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Customer-Import-Gender-is-not-imported/idi-p/45159).
