### ISSUE TITLE
Shipping address validation error without Region defined

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4296]
I am getting PHP error when shipping address validation is performed at either shopping cart or checkout if shipping address is without region entered, lets say Ukraine.

Here is the trace:
`[2016-04-25 15:54:36] main.CRITICAL: Exception: Report ID: webapi-571e3dbc692ab; Message: Recoverable Error: Object of class Magento\Customer\Model\Data\Region could not be converted to string in /var/data/mfs/www/magento/lib/internal
/Magento/Framework/DB/Adapter/Pdo/Mysql.php on line 2903 in /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/data/mfs/www/magento/app/code/Magento/Webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/data/mfs/www/magento/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/data/mfs/www/magento/pub/index.php(54): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []
`

**Comment by klec** [comment]
I have pretty same issue with Magento\Directory\Model\Region.php when I'm passing the checkout as a Guest

**Comment by alena-marchenko** [comment]
Hi @devdesco-ceo 

Is this case reproducible on develop branch? Could you also specify Magento version that you are using for us to be able to investigate the issue further?

**Comment by devdesco-ceo** [comment]
2.0.5

**Comment by alena-marchenko** [comment]
Hi @devdesco-ceo 

Please provide us with debug.log and details regarding 502/404 errors. Are you able to reproduce the issue on the develop branch?

**Comment by alena-marchenko** [comment]
Closing this issue due to no response, please reopen when you have an update.

**Comment by ankitce** [comment]
[Reproducible error](https://github.com/magento/magento2/issues/4187#issuecomment-255071297)

**Comment by friimaind** [comment]
Reopened https://github.com/magento/magento2/issues/12436
