### ISSUE TITLE
About Shipping method

### ISSUE THREAD

**Issue by davidbilly** [magento/magento2#4297]
Hi guys, i need a shipping method with min weight(KGS). 

if a user order an item below 5KG then shipping method will hidden. otherwise it will show.

i tried with UPS, this not working due to always show "Carrier with such method not found: null, ups" 

<img width="1353" alt="screen shot 2016-04-26 at 1 17 50 am" src="https://cloud.githubusercontent.com/assets/3938103/14792444/c9974f9c-0b4c-11e6-80fe-dafbd1571ee3.png">

<img width="912" alt="screen shot 2016-04-26 at 1 19 07 am" src="https://cloud.githubusercontent.com/assets/3938103/14792492/08d41cbc-0b4d-11e6-9e4b-5aded38bac78.png">

please help :(

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by davidalger** [comment]
@davidbilly Could you let us know what version of M2 you installed, how you installed it, what version of PHP / MySql you are using, and if you have any 3rd party modules installed? Trying to collect more info here so the team can try and reproduce the issue. I don't believe 'null' should ever show up in that message on the front, so there is something going awry, that I know ;)

**Comment by davidbilly** [comment]
Hi @davidalger , My setup : 
Magento2 : 2.0.4 CE
PHP : 5.6.20-1+deb.sury.org~trusty+1
MYSQL : 5.6.30-0ubuntu0.14.04.1
3rd party module : MagePal_GmailSmtpApp and Plumrocket_SocialLoginFree only

Thanks, hope can someone can assist me :)

**Comment by YevSent** [comment]
@davidbilly hi, did you configure UPS module? Seems UPS gateway url is missed related on your screenshot. Also, why you has empty shipping address?

**Comment by davidbilly** [comment]
@joni-jones Hi, im using http://www.ups.com/using/services/rave/qcostcgi.cgi for gateway url. 

It's seem cant get the method name. on screenshot the method name is blank. Can i hard code it or something? 

Actually i just need its max and min weight condition, not going use the UPS services :)

Still not working :(

For empty shipping address , i use photoshop remove it. due to its personal address :)

**Comment by YevSent** [comment]
Please, attach debug or exception log, I've tried for different cases, UPS is works.

**Comment by davidbilly** [comment]
@joni-jones how about this log?

<img width="1904" alt="screen shot 2016-04-26 at 8 39 09 pm" src="https://cloud.githubusercontent.com/assets/3938103/14818323/12ec7fee-0bef-11e6-8ddb-10ce27c4ffb9.png">

<img width="1463" alt="screen shot 2016-04-26 at 8 39 31 pm" src="https://cloud.githubusercontent.com/assets/3938103/14818328/17903e64-0bef-11e6-8457-03850e3b6dce.png">

Thanks for reply :)

**Comment by YevSent** [comment]
Sorry, but this log says nothing about your problem, message from this response you got on frontend. Please, attach application debug|exception log.

**Comment by davidbilly** [comment]
@joni-jones sorry , may i know where i can get those log? i search log from nginx cant find those magento error :(

**Comment by YevSent** [comment]
By default application logs located in `%application_path%/var/log`, also you need to enable debug mode for UPS.

**Comment by davidbilly** [comment]
@joni-jones how about this: i got it from debug.log 

[2016-04-26 13:56:09] main.DEBUG: array (
  'request' => 
  array (
    'accept_UPS_license_agreement' => 'yes',
    '10_action' => '4',
    '13_product' => 'GNDCOM',
    '14_origCountry' => 'MY',
    '15_origPostal' => '81100',
    'origCity' => 'Johor Bahru',
    '19_destPostal' => '81100',
    '22_destCountry' => 'MY',
    '23_weight' => 150,
    '47_rate_chart' => 'Customer Counter',
    '48_container' => '00',
    '49_residential' => '02',
    'weight_std' => 'kgs',
  ),
  'result' => 'UPSOnLine5%Unsupported country specified%6920
',
) {"is_exception":false} []
[2016-04-26 13:56:09] main.DEBUG: Sorry, something went wrong. Please try again or contact us and we'll try to help.: Unsupported country specified {"is_exception":false} []

Seem like not support my country code :( 

There's any module that support shipping method with min weight ? Thanks!

Edit: 
I manage pass-by UPS checking by : 
$params = [
            'accept_UPS_license_agreement' => 'yes',
            '10_action' => $rowRequest->getAction(),
            '13_product' => $rowRequest->getProduct(),
            '14_origCountry' => 'US',// $rowRequest->getOrigCountry(),
            '15_origPostal' => '10005',//$rowRequest->getOrigPostal(),
            'origCity' => 'New York',//$rowRequest->getOrigCity(),
            '19_destPostal' => '10005',//$destPostal,
            '22_destCountry' => 'US',//$rowRequest->getDestCountry(),
            '23_weight' => '10',//$rowRequest->getWeight(),
            '47_rate_chart' => $rowRequest->getPickup(),
            '48_container' => $rowRequest->getContainer(),
            '49_residential' => $rowRequest->getDestType(),
            'weight_std' => strtolower($rowRequest->getUnitMeasure()),
        ];

But UPS Minimum Package Weight is not working, i was set min 500KG then order item with 1KG. 
Still can process to payment page :( any idea?

**Comment by YevSent** [comment]
The `UPS` carrier (based on cgi) allows to ship only if origin country is `USA`, your origin country is `Malaysia`, that's why you get this error. You can use `UPS XML` type instead.

**Comment by davidbilly** [comment]
@joni-jones but i'm actually not using the UPS shipping service. Just need validate the total order is above min weight. Now the problem is  Minimum Package Weight is not working :( We using our own lorry to send goods :)

**Comment by YevSent** [comment]
If you not use UPS, please, disable it and attach new screenshot with your problem.

**Comment by davidbilly** [comment]
@joni-jones, noted. will open new issue. Thanks for help.
