### ISSUE TITLE
ExtJS - Update to latest version

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#430]
For now we using ExtJS version 1.1 Beta 1 (https://github.com/magento/magento2/blob/master/pub/lib/extjs/ext-core.js).
Why we use really old lib? For now latest ExtJS version - 4.2.1!

**Comment by tkacheva** [comment]
@ihor-sviziev We are working on consistent usage of JS libraries in Magento 2. Follow the updates. Thank you.

**Comment by mcspronko** [comment]
MAGETWO-25946

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/ExtJS-Update-to-latest-version/idi-p/46846).
