### ISSUE TITLE
Error in unittests for Magento\Setup\Controller\Session

### ISSUE THREAD

**Issue by chris-brabender** [magento/magento2#4300]
It appears there is another (https://github.com/magento/magento2/issues/3715) issue with the coverage on unit tests.

```
Trying to @cover or @use not existing method "\Magento\Setup\Controller\Session::testUnloginAction"
```

Looks like setup/src/Magento/Setup/Test/Unit/Controller/SessionTest.php:39 and vendor/magento/magento2-base/setup/src/Magento/Setup/Test/Unit/Controller/SessionTest.php:39 should be updated from 

```
     * @covers \Magento\Setup\Controller\Session::testUnloginAction
```

to

```
     * @covers \Magento\Setup\Controller\Session::unloginAction
```

**Comment by mazhalai** [comment]
This has already been fixed in scope of #3715 and MAGETWO-50846. Will be merged to develop soon. Closing as duplicate.
