### ISSUE TITLE
Upgrade Magento 2.0.1

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#4303]
Hi All,

I trying to upgrade Magento 2.0.1 to 2.0.4, via ystem > Tools > Web Setup Wizard

But im get error on section Check Component Dependency when start process Readlines Check

Error : 
- The requested package magento/product-enterprise-edition could not be found in any version, there may be a typo in the package name.

Any ideas ?

Regards,
Ivan

**Comment by mazhalai** [comment]
Please do not post enterprise related issues here. Use the partner portal.
