### ISSUE TITLE
Success message not disappearing when changing customer information twice

### ISSUE THREAD

**Issue by philippsander** [magento/magento2#4307]
## Steps to reproduce
1. log in as customer
2. change account information
3. change account information again
## Expected result
1. a success message appears
2. when navigating to another site the success message does not show again
## Actual result
1. a success message appears
2. when navigating to another site the success message never disappears

**Comment by philippsander** [comment]
when using `addNotice` instead it's working.

**Comment by sevos1984** [comment]
This is a known problem, internal ticket id is MAGETWO-46014, magento team is working on it.

**Comment by slavvka** [comment]
Hi @philippsander, the fixe has been delivered to mainline. See commits 541ec80, 55a6e51, b4d3739, eec31f6, af2a832, d97ebe5, 3120b1e and 66e6ad6. Thank you for your contribution to Magento 2!
