### ISSUE TITLE
WHERE duplicates for filters in listings (adminhtml)

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#4308]
### Preconditions

1. Magento 2
2. Some products created.
3. Debug enabled.

### Steps to reproduce

1. Go to Admin -> Catalog ->Products.
2. Add a breakpoint at return statement of \Magento\Catalog\Model\ResourceModel\Product\Collection::load method.
3. In Products Grid open filter, set some values to ID "from" and "to", apply filter.
4. After code execution is stopped at breakpoint, evaluate expression "(string)$this->getSelect()|"

### Expected result

All expressions "WHERE" clause are unique.

### Actual result

Repetitive expressions in "WHERE"  clause.

I have set up break point in `\Magento\Catalog\Model\ResourceModel\Product\Collection::load()` on `return $this;` then I have filtered "Products / Catalog" listing by ID (from 21 to 124354) in adminhtml (/index.php/admin/catalog/product/). 

![image](https://cloud.githubusercontent.com/assets/5052385/14815170/77785678-0bb2-11e6-995c-048e96d2d375.png)

The "where" clause (_$this->_select->_parts->where_) that is generated by Magento 2 is on screenshot. There are a lot of duplicates in the "where" condition. I suppose every column in the grid adds one duplicate to the selection statement.

![image](https://cloud.githubusercontent.com/assets/5052385/14815115/2bcf7ecc-0bb2-11e6-83b4-3931606c5623.png)

This is SQL for the statement:

```
SELECT
  `e`.*,
  SUM(qty) AS `qty`
FROM `catalog_product_entity` AS `e`
  LEFT JOIN `cataloginventory_stock_item`
    ON (cataloginventory_stock_item.product_id = e.entity_id)
WHERE (`e`.`entity_id` >= '21')
AND (`e`.`entity_id` <= '124354')
AND (`e`.`entity_id` >= '21')
AND (`e`.`entity_id` <= '124354')
...
    (the last 2 rows are repeated 11 times) 
    ...
GROUP BY `e`.`entity_id`
ORDER BY `e`.`entity_id` ASC LIMIT 20
```

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-52833

**Comment by magento-engcom-team** [comment]
@flancer64, thank you for your report.
We've created internal ticket(s) MAGETWO-84487 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@flancer64, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
