### ISSUE TITLE
Bundle Products - error with quotation mark in product option name.

### ISSUE THREAD

**Issue by creatuitydevelopers** [magento/magento2#4309]
## Hello All,

While migrating products from Magento to Magento 2 we’ve encountered an error related to Bundle Products. 
## Steps to reproduce
1. Go to Magento admin panel.
2. Crate a bundle product with quotation mark in it's name.
3. Go to frontend and check if the quotation marks appears in product options dropdown, on bundle product page.
## Expected result
1. Quotation marks will stay unchanged for bundle options names. 
2. Example: **Test Product 11” x 15”**

Screenshot:

![magento2_issue_1](https://cloud.githubusercontent.com/assets/14896152/14812596/14b01332-0b9e-11e6-88a9-4237fd31f6e4.png)
## Actual result
1. Quotation marks are being translated into HTML Entity & quot; 
2. Example: **Test Product 11 & quot; x 14 & quot;**

Screenshot:

![magento2_issue_2](https://cloud.githubusercontent.com/assets/14896152/14812595/14ae19d8-0b9e-11e6-9f25-01f290f4b63e.png)

**Comment by piotrekkaminski** [comment]
Can you try in develop branch? A very similar issue was fixed with https://github.com/magento/magento2/issues/4309

internal ticket MAGETWO-52832

**Comment by creatuitydevelopers** [comment]
@piotrekkaminski thank you for your feedback. We will test issue on develop branch and post the results.

**Comment by creatuitydevelopers** [comment]
I can confirm that on develop branch this error is not visible.

**Comment by veloraven** [comment]
This issue has been fixed already.
Closed.
