### ISSUE TITLE
Missing argument 4 for Magento\GiftRegistry\Model\Plugin\QuoteItem::aroundConvert

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#4311]
Magento: EE 2.0.4.
Extension: GiftRegistry

Reproduce: I don't know how to reproduce this in standard Magento. But in our custom extension we are using following code for convert quote item to order item

`/**@var \Magento\Quote\Model\Quote\Item\ToOrderItem */`
`protected $quoteItemToOrderItem;`
`...`
`$orderItem = $this->quoteItemToOrderItem->convert($quoteItem);`

It worked in 2.0.2, but after update to 2.0.4 it generate warring:
`Warning: Missing argument 4 for Magento\GiftRegistry\Model\Plugin\QuoteItem::aroundConvert() in ..../vendor/magento/module-gift-registry/Model/Plugin/QuoteItem.php on line 24`

File: vendor/magento/module-gift-registry/Model/Plugin/QuoteItem.php
Function: aroundConvert

Please, change 
`public function aroundConvert(
        \Magento\Quote\Model\Quote\Item\ToOrderItem $subject,
        \Closure $proceed,
        \Magento\Quote\Model\Quote\Item\AbstractItem $item,
        $additional
    ) {`

to

`public function aroundConvert(
        \Magento\Quote\Model\Quote\Item\ToOrderItem $subject,
        \Closure $proceed,
        \Magento\Quote\Model\Quote\Item\AbstractItem $item,
        $additional = []
    ) {`

Thank you.

**Comment by mazhalai** [comment]
Please do not post EE issues here. Please post on the partner portal. 
@ishakhsuvarov @MomotenkoNatalia Closing this issue since this is EE.
