### ISSUE TITLE
VIrtual Products and Bulk Changing to simple product 

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4313]
## Steps to reproduce
1. Add a new product 
2. set "has weight" radio to "no"
3. Save the product (a virtual product is created automatically)
4. Reopen the product and add configurations (ex. color)
5. Save the product and it's variants
6. Now your original virtual product has been changed to a configurable product with to VIRTUAL product variants associated (because the original product was a virtial product)

Say you would like to change this associated virtual products in bulk by adding has weight=yes and adding a weight value...
1. Select the virtual associated products in the product grid
2. Select "actions" --> "update attributes"
3. go to the "has weight" attribute in the window
## Expected result
1. I would expect to be able to check the "change" checkbox
2. I would excpect to be able to add a weight value
3. I would expect to have converted the virtual products to simple products when saving this bulk operation 
## Actual result
1. I cannot check the "change checkbox" in FIrefox or Chrome

![2016-04-26_16h09_46](https://cloud.githubusercontent.com/assets/13572447/14821233/4371b74e-0bca-11e6-82cf-396e98242f57.png)
1. However i 'am able to check it in INternet explorer and add a weight value
   ![2016-04-26_16h14_52](https://cloud.githubusercontent.com/assets/13572447/14821299/7f9e5952-0bca-11e6-8028-562df6ad78c6.png)
2. When saving both products have NOT been converted to simple products

![2016-04-26_16h15_30](https://cloud.githubusercontent.com/assets/13572447/14821344/aee6bc22-0bca-11e6-83c7-3fc8f530e7ce.png)

When opening the product page in the backend i can see that a weight value has been added but "has weight" was not saved:
![2016-04-26_16h16_44](https://cloud.githubusercontent.com/assets/13572447/14821388/d71b5766-0bca-11e6-9b3a-2dd96d8345b4.png)

**Comment by vil11** [comment]
@SidneyBilliet 

Hi, Sidney!
Thanks for a detailed report. We've already fixed this & delivered fix to mainline. See details [here](https://github.com/magento/magento2/issues/3361). Please let us know if you won't be able to change Product Attributes via mass actions after the Magento version update.

![05-05-2016 18-49-34](https://cloud.githubusercontent.com/assets/5585456/15048767/901038ca-12f3-11e6-8f94-8b26c37e00d6.jpg)

## 

:sunny: dima vilchynskyi, M2 QA engineer.

**Comment by nizzac** [comment]
Although you can change the weight value on multiple virtual products, the option "This product has no weight" remains the same.

It should be converted to a simple product and "This product has weight" should be set.

Keeping it as a virtual product means that it's weight value isn't taking into consideration when shipping costs are calculated.

**Comment by sello30** [comment]
Hello, could you please help me, how I can bulk change on woocommerce all products to virtual products?

I did not find the weight "yes / no" button.

Thanks in advance.
