### ISSUE TITLE
Export / Import 

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4315]
## Steps to reproduce
1. Export all product from your Magento installation using the backend feature
2. Select "products"
3. Select continue
4. Save the CSV file to your computer
5. Open it, choose any sku and change any value (for example change a qty)
6. Save the file in UTF-8 mode as required
7. Go to system/import
8. select "products"
9. Import Behavior = add / udpdate
10. Select the file you have changed
11. Clikc check data
    ![2016-04-26_16h34_29](https://cloud.githubusercontent.com/assets/13572447/14822049/479bab06-0bcd-11e6-96e6-12dad0bed6ec.png)
## Expected result
1. I would expect nit getting so much errors when I have only changed one single record ...
## Actual result

155 errors when not even changing ONE single record...
![2016-04-26_16h39_28](https://cloud.githubusercontent.com/assets/13572447/14822269/4728205e-0bce-11e6-8077-6c65005c44ba.png)

**Comment by melnikovi** [comment]
Please make sure that your editor doesn't change format of the file. Try to import file with out making any changes and let me know if it works. Thank you

**Comment by SidneyBilliet** [comment]
Hi Igor
It doesn't!
Export a file and reimport it before even opening it in any program and you wil get errors.

**Comment by SidneyBilliet** [comment]
Any news on this issue?

Kind regards,

**Comment by SidneyBilliet** [comment]
Hello??

**Comment by asemenenko** [comment]
@melnikovi please update the ticket.

@SidneyBilliet can you send a file (you can delete all sensitive data there)? Also please use mention function otherwise no notification will be read.

**Comment by SidneyBilliet** [comment]
@melnikovi 

[catalog_product_20160513_091248.zip](https://github.com/magento/magento2/files/262870/catalog_product_20160513_091248.zip)

No need to delete any data. The customer should be able to export everything he has inside his catalog to be able to change prices and stock easily. But we are not able to reimport. It seems strange that it is impossible to re-import a file you have just exported without even changing a single record.
If the attribute accepts the data in the store backend, why is it not possible to import it after having exported it....

Kind regards,

**Comment by piotrekkaminski** [comment]
I wasn't able to reproduce this specific issue but importing back file without modification resulted in different error. Internal issue: MAGETWO-52831

**Comment by yaronish** [comment]
Fixed.
