### ISSUE TITLE
Can't save a shipment with comments using POST via API

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4319]
## Steps to reproduce
1. Install Magento 2.0.4.
2. Add an order.
3. Via API attempt to post a shipment containing a comment.
## Expected result
1. Shipment will save properly with comment viewable in the shipment via Admin.
## Actual result
1. API returns error: 
   {
   "message": "Could not save shipment",
   "trace": "#0 [internal function]: Magento\Sales\Model\Order\ShipmentRepository->save(Object(Magento\Sales\Model\Order\Shipment))\n#1 \/opt\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(265): call_user_func_array(Array, Array)\n#2 \/opt\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(160): Magento\Webapi\Controller\Rest->processApiRequest()\n#3 \/opt\/magento2\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))\n#4 \/opt\/magento2\/vendor\/magento\/framework\/App\/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#5 \/opt\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\Framework\App\Http->launch()\n#6 \/opt\/magento2\/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))\n#7 {main}"
   }

**Comment by YevSent** [comment]
Hi, @jim5359, please attach example of your API request. I've tested on latest develop branch, all works. Your request should looks like this example:

``` json
{
  "entity": {
    "order_id": 1,
    "customer_id": 1,
    "shipping_address_id": 1,
    "total_qty": 1,
    "billing_address_id": 2,
    "increment_id": "000000003",
    "items": [{
        "product_id": 1,
        "order_item_id": 1,
        "sku": "exists sku",
        "name": "exists name"
    }],
    "comments": [{
        "comment": "this is 1-st comment"
    }, {
        "comment": "this is 2-nd comment"
    }]
  }
}
```

**Comment by jpreed2** [comment]
Here's my request based on the documentation:

```
"entity": {
  "order_id": 1,
  "billing_address_id": 2,
  "shipping_address_id": 2,
  "total_qty": 1,
  "comments": [
    {
      "comment": "This is a test comment"
    }
  ],
  "items": [
    {
      "name": "TESTSKU",
      "order_item_id": 1,
      "price": 10,
      "product_id": 1,
      "qty": 1,
      "sku": "TESTSKU",
      "weight": 1
    }
  ]
}
```

Does this work for you in v2.0.4?  Perhaps it was fixed in the develop branch.  If I remove the comments then it saves the shipment fine.

**Comment by YevSent** [comment]
Your request also works on the latest develop, could you try create shipment with comment on the latest develop?

**Comment by jpreed2** [comment]
I've confirmed this is working now in the develop branch.  Thanks.

**Comment by asemenenko** [comment]
Closing the ticket as resolved. Thanks to all!
