### ISSUE TITLE
[Feature request] Make reindex for specific store view

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#432]
As example for now we should make reindex Products flat for all websites. When we have many products(10000+) and we copied added all products to new website, reindex process is really very slow. Should be great have ability reindex flat data for specific store/website.

**Comment by kokoc** [comment]
@ihor-sviziev Great idea. Appropriate item is placed into internal backlog - MAGETWO-33513.

@iw2 Magento already supports asynchronous reindex. Currently it's called "update when scheduled" mode. You can find these settings in "indexers" grid.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Make-reindex-for-specific-store-view/idi-p/46842).
