### ISSUE TITLE
Adding a shipping comment via API does not send an email to the customer

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4320]
## Steps to reproduce
1. Install Magento 2.0.4.
2. Create an order.
3. Create a shipment for the order.
4. Via the API, post a comment with the is_customer_notified set to 1.
## Expected result
1. The comment will be added to the shipment and an email will be sent to the customer with the comment.
## Actual result
1. The comment is added to the order and is visible in Admin showing that Customer was notified, but no email gets sent to the customer.

I've tried emailing the shipment to the customer.  The email is sent but the comments are not displayed.  So there seems no way via the API to send a shipping comment to the customer, as there is from Admin.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-52830

**Comment by ddeppner** [comment]
Would love to see this fixed.  These little glitches in the API present challenges for larger businesses that need to integrate with other systems, and particularly B2B firms.

This impacts our site now that we've launched, and we're forced to work around this limitation by sending these emails from other systems (with other limitations) until this is addressed.

**Comment by gediminaskv** [comment]
I think it lacks {"notify": true} parameter which new shipment document has when creating via REST API. For now it displays new comment on frontend, but you can't email it to customer...

**Comment by magento-engcom-team** [comment]
@jim5359 We are closing this ticket and will keep track of the issue in #11207 as it's description seems to be more clear.
Thank you.
