### ISSUE TITLE
Minify JavaScript Files causes product images to not load on product pages

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#4322]
## Steps to reproduce
1. Install Magento 2.0.4
2. Go to Admin > Stores > Configuration > Advanced > Developer
3. Enable "Minify JavaScript Files"
## Expected result
1. JavaScript files will be minified and site will load faster.
## Actual result
1. Product images do not load on product pages using Luma Theme.
2. Images return when setting is disabled.

**Comment by Pakkapao** [comment]
#2938

**Comment by anton-huz** [comment]
Currently not reproducible on Magento 2.0.5. 
Was retested with
- enabled "Minify JavaScript Files"
- enabled "Minify JavaScript Files" + "Enable JavaScript Bundling"

I'm closing the issue.

@ @stevekem, @adzminz  
if you can still observe issue, please try to flush your browser cache or run it in Privacy mode. If you will still faced issue please provide a little bit more details about environment where it occurs. 

Great thanks for your attention.
