### ISSUE TITLE
Sales Order Totals Base grandtotal

### ISSUE THREAD

**Issue by jackhuang89** [magento/magento2#4323]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add Product to the cart.
3. Setup Paypal Standard Sandbox
4. Setup one more currency
5. Setup Email
6. Sign up account
7. Switch to different currency
8. Buy a product
9. Checkout with PayPal
10. Check order confirm email
11. View the Grand Total to be charged 
## Expected result
1. Grand Total to be charged is base currency format and value
## Actual result
1. Grand Total to be charged is not base currency format and value
## What I done
1. Modify Totals.php
   /var/www/magento2/vendor/magento/module-sales/Block/Order/Totals.php

Git link:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Block/Order/Totals.php

around line 160:
/**
         \* Base grandtotal
         */
        if ($this->getOrder()->isCurrencyDifferent()) {
            $this->_totals['base_grandtotal'] = new \Magento\Framework\DataObject(
                [
                    'code' => 'base_grandtotal',
                    //'value' => $this->getOrder()->formatPrice($source->getGrandTotal()),
                    'value' => $this->getOrder()->formatBasePrice($source->getBaseGrandTotal()),
                    'label' => __('Grand Total to be Charged'),
                    'is_formated' => true,
                ]
            );
        }

**Comment by piotrekkaminski** [comment]
Internal ticket MAGETWO-52829

**Comment by alena-marchenko** [comment]
Hi @jackhuang89 

Fix is already delivered to develop branch, closing the issue.
