### ISSUE TITLE
Something went wrong with the subscription.

### ISSUE THREAD

**Issue by serajin** [magento/magento2#4325]
I am having the same issue as Issue# 1157.

Upon adding an email to the subscription list, it gives an error:
![image](https://cloud.githubusercontent.com/assets/10015495/14844812/1f3cdbca-0c28-11e6-9955-33f08204bb47.png)

The previous issue states it was fixed with an update, however it appears to be back, at least for me.

I am currently on Magento Community Edition V 2.0.4, on a clean install of Magento2.

**Comment by lanken** [comment]
Could you, please, provide an error from Magento exception log and check whether email is configured on your server.

**Comment by mazhalai** [comment]
@serajin closing this as non-responsive.

**Comment by bonsdawende** [comment]
Hello, 
I have this same problem with subscription of newsletter. Please, how have you resolved this issue ? Thanks

**Comment by chong1227** [comment]
me too .... same issue~

**Comment by pboisvert** [comment]
@chong1227 @bonsdawende this issue is closed. If you are having this issue please reopen and provide full information regarding version (clean install or upgrade) and steps to reproduce.

**Comment by serzhik** [comment]
Relates to #1157
I have same issue on 2.0.4 EE. Subscription do not work for registered users.

**Comment by bonsdawende** [comment]
@Serzhik, when you configure your smtp in your Magento 2 ( Stores > Configuration>Advanced > System), try to fill these settings : 
Authentication method : Login
SSL Type: TLS

It works for me !

**Comment by abhijitbanik2016** [comment]
I installed Magento 2.1 in a domain www.craftallure.com

Then configured magento SMTP with following credential
Authentication method: Login
SSL type: SSL
Port: 465
SMTP Host: smtp.gmail.com	
Username: info@dotkiwis.com
Password: ************

Then after doing these steps but finding error:

Step 1: Open this URL: https://www.craftallure.com/

Step 2: Fill any email address in subscription form footer and click subscribe.

Step 3: Then this error will be visible in red error note. 
"Something went wrong with the subscription."


![image](https://cloud.githubusercontent.com/assets/20184139/21966548/7117b1ca-db9b-11e6-8dab-9afe648fa855.png)

Is there anyone got any proper update on it? 
If any update it will be great help.

`This is exception error message I copied here. It might can give some light

[2017-01-07 20:47:11] main.CRITICAL: Exception message: Could not open socket
Trace: #0 /home/craftallure/public_html/vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php(124): Magento\Newsletter\Model\Subscriber->subscribe('abhijitindesign...')
#1 /home/craftallure/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#2 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#4 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'contextPlugin')
#5 /home/craftallure/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'storeCheck')
#8 /home/craftallure/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'customer-app-ac...')
#11 /home/craftallure/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'tax-app-action-...')
#14 /home/craftallure/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'weee-app-action...')
#17 /home/craftallure/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /home/craftallure/public_html/var/generation/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(26): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /home/craftallure/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#24 /home/craftallure/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 /home/craftallure/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#30 /home/craftallure/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#33 /home/craftallure/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/craftallure/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /home/craftallure/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/craftallure/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /home/craftallure/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))`

Any update will be highly helpful.

**Comment by oldcompilerharris** [comment]
> @serzhik, when you configure your smtp in your Magento 2 ( Stores > Configuration>Advanced > System), try to fill these settings :
> Authentication method : Login
> SSL Type: TLS
> 
> It works for me !

Thanks a lot @bonsdawende, Your reply helped me. And my bugs got fixed.
I just changed the "Disable Email Communications" to yes in Magento 2 ( Stores > Configuration > Advanced > System > Mail Sending Settings > Disable Email Communications).

**Comment by NickeGilbert** [comment]
Hi!

Have anyone found a solution to this problem? 
I tried the "Disable Email Communications" to yes in Magento 2 ( Stores > Configuration > Advanced > System > Mail Sending Settings > Disable Email Communications). But without success. 

I'm sending my bug report. Hope that anyone can find a solution to this. 

`
Trace: <pre>#1 Magento\Newsletter\Model\Subscriber\Interceptor->subscribe('niklas.johns...') called at [vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php:156] [vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php:156]
#2 Magento\Newsletter\Controller\Subscriber\NewAction->execute() called at [generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php:24]
#3 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#4 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#5 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#6 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [app/code/Aheadworks/Ca/Plugin/Controller/FrontActionPlugin.php:97]
#7 Aheadworks\Ca\Plugin\Controller\FrontActionPlugin->aroundDispatch(&Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor#00000000553be799000000004912d0c6#, &Closure#00000000553be7f7000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#8 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#), array(array('storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php:39]
#10 Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/App/FrontController.php:159]
#11 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#, &Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor#00000000553be799000000004912d0c6#) called at [vendor/magento/framework/App/FrontController.php:98]
#12 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#15 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000553be5e5000000004912d0c6#, &Closure#00000000553be5cc000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#17 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000553be5e5000000004912d0c6#, &Closure#00000000553be5cc000000004912d0c6#, &Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#20 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#00000000553be408000000004912d0c6#) called at [vendor/magento/framework/App/Http.php:137]
#21 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#22 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#23 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000553be467000000004912d0c6#) called at [index.php:40]

[2020-06-24 14:15:49] main.DEBUG: cache_invalidate:  {"method":"POST","url":"root/newsletter/manage/save/","invalidateInfo":{"identifier":"notification_update_customer_session_215"}} []`
