### ISSUE TITLE
StockItemCriteria::setProductsFilter doesn't work with array of ids

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#4328]
In `StockItemCriteriaInterface` method `setProductsFilter` accepts a single integer or an array of integers, but if you use an array of ids and use the resulting criteria to get a list from `StockItemRepository` you only get a single item. I was expecting to obtain as many elements as the ids I passed to the filter.

I can't say if this is the expected behaviour or not, but I suppose it is not. In the core that method is never used with arrays and is not covered by test units.

**Comment by piotrekkaminski** [comment]
@antonkril can you look into it?

**Comment by delyriand** [comment]
Hi,

As a workaround, you can put your product id array in another array : 
`->setProductFilter([$productIds])`.

The origin of the problem is the use of `call_user_func_array` in the method `map` of the class `Magento\Framework\DB\AbstractMapper`. If not encapsulate product ids array into another array, sending multiple parameter to the method instead of a single.

**Comment by veloraven** [comment]
@giacmir is this issue still actual?
If it is please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
Please note that GitHub issue tracker is intended for technical issues only and refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
