### ISSUE TITLE
admin stuck on " It's time to change your password."

### ISSUE THREAD

**Issue by ran2345** [magento/magento2#4331]
## Steps to reproduce

![untitled-5](https://cloud.githubusercontent.com/assets/16897820/14871854/64a97306-0cde-11e6-9d69-3b083ebd131d.jpg)
login in to admin after 4 months from installation opened the my account/Account information page with the title “It's time to change your password.”
I changed my password and pressed “Save Account”
## Expected result

That I will receive the dashboard page and start working
## Actual result

I received the same page (my account/Account information) with the same “It's time to change your password.” Title.
I tried to log out and log back in and I received the same page
I cleared the cache and cookies and then log in and received the same page 

![untitled-5](https://cloud.githubusercontent.com/assets/16897820/14871854/64a97306-0cde-11e6-9d69-3b083ebd131d.jpg)

**Comment by andyworkbase** [comment]
have the same issue on ME 2

**Comment by ntoombs19** [comment]
I had this happen to me today as well. You can avoid this happening in the future by going to **STORES -> CONFIGURATION -> ADVANCED -> ADMIN -> SECURITY -> PASSWORD CHANGE** and setting that field to **Recommended**. If you have direct access to the database you can run this query to set that field to recommended directly

``` mysql
UPDATE `core_config_data` SET `value` = '0' WHERE `path` = 'admin/security/password_is_forced';
```

Or if you have [n98-magerun2](https://github.com/netz98/n98-magerun2) installed, you can run this command

`n98-magerun2.phar config:set admin/security/password_is_forced 0`

**Comment by mazhalai** [comment]
@ran2345 thank you for reporting, we have created MAGETWO-52437 to investigate and fix.

**Comment by erikhansen** [comment]
@mazhalai I just experienced this on a project. More and more merchants are going to run into this over the coming weeks as the _Password Lifetime (days)_ value defaults to 90 days, so merchants who installed Magento 2 90 days prior will run into this issue. In fact, every merchant that has installed Magento 2 up to this point is going to run into this issue, so this is a pretty big issue that should be addressed ASAP. I would recommend fast-tracking a solution to this and including it in your next release.

**Comment by piotrekkaminski** [comment]
It is fixed in develop branch and should be released in a patch release. cc @elenleonova  for more information.

**Comment by srqdeveloper** [comment]
I was unable to fix the issue with the database script provided by @ntoombs19, but running the following script on the admin_passwords table worked:

`UPDATE admin_passwords SET expires = <<some future timestamp>> WHERE user_id = <<admin_user_id>>;`

**Comment by erikhansen** [comment]
@srqdeveloper I used the MySQL script from @ntoombs19 on a CE and EE installation and it worked fine. Maybe you didn't flush the cache afterwards?

**Comment by FoxtrotOscar2** [comment]
This issue apparently still exists in 2.0.7.

**Comment by tecjam** [comment]
I can confirm that this issue still exists in 2.0.7

**Comment by Manashvi** [comment]
Yes this issue still continue to exist in the version 2.0.7

**Comment by alexbartsch** [comment]
@srqdeveloper For me, the query from @ntoombs19 also didn't work. I figured out, that this is because there is no row with `path = 'admin/security/password_is_forced'`. 

Run this query instead:

``` sql
INSERT INTO `core_config_data` SET `value` = '0', `path` = 'admin/security/password_is_forced';
```

**Comment by MaximKitsenko** [comment]
@alexbartsch @srqdeveloper 
script from comment above works : `UPDATE admin_passwords SET expires = <<some future timestamp>> WHERE user_id = <<admin_user_id>>;`
if it doesn't work that means
1. you use too small `<<some future timestamp>>`  (for me 1999999998 works)or incorrect `<<admin_user_id>>`. Don't forget that sometimes there are alot of users represented in this table, i prefer to change all lines in the table (=> to impact on all users)
2. your cache holds old data.  I suggest to clean browser cache and coockies

but for me it is more simple to use MySQL UI client, and edit all rows in table admin_passwords. just insert some big value, f.e. 1999999998 into expired column

http://stackoverflow.com/questions/38743317/magento-stuck-on-its-time-to-change-your-password/38743436#38743436

**Comment by giacmir** [comment]
Still present in 2.0.9

**Comment by camdixon** [comment]
Also have this problem.  Not only is a 90 day timing annoying by default (PCI compliance?), as the issue states it is not updating the time value properly when a successful password change event happens.

**Comment by vanderlee** [comment]
Neither the `UPDATE admin_passwords` hack nor the `UPDATE core_config_data` hack worked for me.
My CMS shows the `It's time to change your password.` message three times and is stuck on this screen, no matter what I do.

![image](https://cloud.githubusercontent.com/assets/649240/19646137/679917ae-99f8-11e6-9288-5ed088dc0dd8.png)

**Comment by itapandroid** [comment]
Run the query:

`UPDATE \`core_config_data\` SET \`value\` = '0' WHERE \`path\` = 'admin/security/password_is_forced';`

then clear the cache by running `php magento cahce:flush` from your bin directory then try to log back in. You will land on the dashboard page.

**Comment by bondgax** [comment]
I've still got this issue.  I've been through all the suggestions above but nothing has worked.

My database doesn't have a line 'admin/security/password_is_forced'
nor do I have an 'admin_passwords' table in my database

Anybody got any suggestions how to resolve this issue please?

**Comment by nntoan** [comment]
Instead of updating value `admin/security/password_is_forced`, you can try to insert new record like this:

```SQL
INSERT INTO core_config_data (`path`, `value`) VALUES ('admin/security/password_lifetime', NULL) ON DUPLICATE KEY UPDATE `value` = VALUES (`value`);
```

If password lifetime is set to empty then this feature will be disabled.

**Comment by jonpday** [comment]
@nntoan this sounds like a really bad idea, and breaks a key PCI security requirement regarding password rotation. @piotrekkaminski can the above reply be removed or otherwise flagged as inappropriate?

**Comment by nntoan** [comment]
@jonpday The author want a solution, then I gave him a solution to log back in. He obviously can change the password lifetime to whatever he want after that. Your comment is ridiculous, I don't want to fight with you. So have fun.

**Comment by veloraven** [comment]
This issue has already been fixed for both: 2.0 and 2.1.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by korostii** [comment]
Hi @veloraven,
Can you please point out the exact versions in which this fix was released? Or at least please reference the particular corresponding commits.

**Comment by veloraven** [comment]
It was fixed in ver. 2.0.10, commits: ddf959866c5d3545167de04f7d8ec7d1d28f9006, 1c4e5e8817d3a23cef70a5488e8e6ecaac5e2cee, 35e9f37ceafc4d0335291fb598ff80b25dee816b

**Comment by korostii** [comment]
Thanks a lot, however I am using 2.1.x branch.
It seems that on 2.1 branch the code was corrected even earlier in scope of different task (see 00059a49 for example), so the issue probably wasn't even present on 2.1.0. Good to know.

**Comment by archae0pteryx** [comment]
Has anyone got this figured out yet?

**Comment by sammarcus** [comment]
Still experiencing this on a fresh install of 2.1.7

@archae0pteryx you can try these steps as a (temporary) workaround: http://mccormicky.com/2056/trying-to-login-to-magento-2-dashboard-but-get-stuck-on-its-time-to-change-your-password-page/

**Comment by victortodoran** [comment]
@erikhansen It's 2019 and this still happens in 2.2.3.

**Comment by ghost** [comment]
Magento 2.3.2 Going from production to Develop and back to production triggers this Password reset loop. Anny solution without making any permanent changes to the database? Or a Patch?

**Comment by harifkv** [comment]
@koopjesboom did you get any solution?

**Comment by giacmir** [comment]
This is still happening with 2.3, I'm reopening this.

**Comment by engcom-Echo** [comment]
Hello All

Magento 2.4-develop.
Set "Change Password" from "Forced" to "Recommended" and increase the "Password Expiration Date" in the admin panel to avoid this problem.
(Stores -> Configuration -> Admin -> Security section)
![Screenshot_7](https://user-images.githubusercontent.com/51681435/70532172-2e3fd600-1b5f-11ea-9afc-51d59f59ac40.png)
So I have to close it.
Thank you!

**Comment by giacmir** [comment]
Hi @engcom-Echo,

your solution is a workaround, what is described here is that, even if the admin changes password, the change request is always present and can't be dismissed. I don't think this should be closed.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**
1. Log into admin  
2. Change the date in the database
(if it’s now 12/21/2019, then change it to 06/21/2019)
`UPDATE admin_passwords SET last_updated = <some time stamp here> WHERE user_id = 1;`
3. Log out and log in to the admin
4. See "It's time to change your password." message.
5. It's impossible to go to other page
6. Change the password and Save

**Result**
Magento works fine. It's possible to go other page inside admin panel. The same behavior is on 2.3.3 version.
![Peek 2019-12-11 17-58](https://user-images.githubusercontent.com/51681435/70637643-3ae82b00-1c40-11ea-80d1-b7a511f98a7f.gif)

**Note**
Timestamp Converter is [here](https://www.unixtimestamp.com/index.php)

**Comment by xAvarice** [comment]
You fucking morons.

**Comment by tecjam** [comment]
@xAvarice Do you kiss your mother with that mouth? How about explain your problem exactly. And what does it have to do with lastpass? 

I think you should first learn how to communicate.

**Comment by PivitParkour94** [comment]
Yeah changing the password with password managers gets tricky. I too got locked out of a few production sites... Now I know make an old password field in the password item, then copy the old, then generate a new, update it, use old in the "Your password" section, and you should be good. Definitely not an issue by Magento, but I understand how it can be done

**Comment by adamzero1** [comment]
We got this after upgrading to 2.4.3, when the session for the admin wasn't large enough https://stackoverflow.com/a/70087594/13338443

**Comment by dlabsnl** [comment]
Hello,

I have the same problem now with 2.4.6-p3. I got the notification that i need to change my password but when I press save the loading is forever. I can't change the password with another admin also..
