### ISSUE TITLE
Page messages (notifications) are not displayed on proper page

### ISSUE THREAD

**Issue by Raysharr** [magento/magento2#4336]
**Magento EE 2.0.4, Mac os x (el capitan)**
## The page messages are displayed wrongly on random pages:

For example:
1. I tried to login with wrong credentials on login page. Notification message "Invalid login or password", should appear, but it didn't happen.
2. Next I went to product page and after that I added a product to cart and notification from "Sign in" page appeared. You can notice that kind of behavior on attached screen shot.

![notification_from_login_on_product_page](https://cloud.githubusercontent.com/assets/2451948/14882579/bac21b16-0d39-11e6-8863-333863eadfe9.png)

**Comment by sevos1984** [comment]
This is a known issue MAGETWO-46014

**Comment by Raysharr** [comment]
Is that ticket number MAGETWO-46014 is your Magento 2 devs internal one, because I can't find this ticket number anywhere? @sevos1984

**Comment by cedricblondeau** [comment]
#4186

**Comment by cedricblondeau** [comment]
#4186 #3503

**Comment by slavvka** [comment]
Hi @Raysharr, the fixe has been delivered to mainline. See commits 541ec806cae729df118b7844f5d105cbf1a6cec6, 55a6e51296afd2c52cfe7f813a4871ae408f1afc, b4d373919489ccb48af10c5ac287ef39e3af384e, eec31f653e3783d0ba86602c8396fd6e2d159546, af2a8325930ae22e2b7ae3f6513c0068217eacd1, d97ebe56200b73e71d97ca527c99108817586a54, 3120b1e89f48ff630e796c6885aecc3e48c070c8 and 66e6ad66c028e99019c110631df4c9015af4a2ca. Thank you for your contribution to Magento 2!
