### ISSUE TITLE
magento 2.0.4 CE email send issue

### ISSUE THREAD

**Issue by adianghel** [magento/magento2#4339]
Any email send attempts (newsletter, order notification etc) results in an error and logs show this error:
main.CRITICAL: Broken reference: No element found with ID 'customer'

**Comment by mazhalai** [comment]
@adianghel thank you for reporting, we have created MAGETWO-52426 to investigate and fix

**Comment by hshar7** [comment]
Hi @adianghel I used 2.0.4 CE to send an order notification email without getting this error. I recommend checking if you modified any templates which could cause this error.
