### ISSUE TITLE
i try to change my admin password from the database table but it not work

### ISSUE THREAD

**Issue by jaatr** [magento/magento2#4341]
i try to change my admin password from database  table choosing md5  but i cannot login my admin by that password and i also use retrive password link not send may be i m working on localhost

**Comment by ghost** [comment]
If you have command-line access you have a couple of options:
-  Try to unlock the Admin account: `magento admin:user:unlock {user name}`
- Create a new Admin account: `magento admin:user:create`

See [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-admin.html) for details

**Comment by jaatr** [comment]
<path_to_magento>/bin/magento admin:user:create [--admin-user="..."] [--admin-password="..."] [--admin-email="..."] [--admin-firstname="..."] [--admin-lastname="..."] also run this command but cannot get sucess

**Comment by piotrekkaminski** [comment]
@jaatr create new account with full access from command line, reset the account from admin. You should not directly edit the database.

**Comment by jaatr** [comment]
i have done all  those method still showing this in admin login .You did not sign in correctly or your account is temporarily disabled.
