### ISSUE TITLE
Magento2 is very slow

### ISSUE THREAD

**Issue by nikunj1990** [magento/magento2#4345]
its very slow, and after adding new extension on localhost it takes ages to create new slider etc.

also after installing on live server it shows 404 css,js errors on frontend

**Comment by stevekem** [comment]
I had this problem before (live server), it was a permissions issue for me... Try running the following commands:

find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \; && chmod u+x bin/magento
sed -i 's/0770/0775/' vendor/magento/framework/Filesystem/DriverInterface.php
php bin/magento cache:flush

**Comment by stevekem** [comment]
Regarding the slow issue.... Do you have the following setting set to "Yes" in admin?

Admin > Stores > Configuration > Advanced > Developer > Merge CSS files

**Comment by gewaechshaus** [comment]
Also js merge minify bundle totally freezes cpu in Magento 2.0.5 in our case...

**Comment by maksek** [comment]
Closing issue since doesn't report bug in codebase. Use form for discussion regarding configuration and env settings.

**Comment by GauravTiwari0801** [comment]
in my system magento 2.3.0 is working very slow & products is only showing in admin panel-not in home page.
luma theme i m using and products is not adding.
