### ISSUE TITLE
Updating products with Multiple Select Attribute 

### ISSUE THREAD

**Issue by afavata** [magento/magento2#4346]
I installed Magento2 from scratch downloading the source from Magento web site. 
Version installed is the most recent at 2.0.4

I'm facing an issue updating products using "update attribute" (under action menu in catalog panel).
When the attribute to update is a "multiple select" type, this attribuite is not updated at all.

**Comment by afavata** [comment]
Same behaviour on Magento 2.0.5.

**Comment by afavata** [comment]
same behaviour on a fresh installation of Magento 2.0.5 with sample data.
The multi selection attributes as "activity", "style bags", "material", etc won't be updated.

**Comment by bh-ref** [comment]
can confirm: https://github.com/magento/magento2/issues/4312

**Comment by afavata** [comment]
I do confirm all points described on issue  #4312. I have tested them on Magento 2.0.5.

Thanks bh-ref!

**Comment by piotrekkaminski** [comment]
Internal ticket MAGETWO-52775

**Comment by oserediuk** [comment]
Hello! We have fixed this issue. Thanks for the report! If you reproduce this issue, please, reopen issue.
