### ISSUE TITLE
Handing problem with store view swicher in backend for large number of websites/store views

### ISSUE THREAD

**Issue by mbloss-dotsource** [magento/magento2#4347]
Hi,

I added 20 websites (each website with one store and store view).
Now I want to change the configuration settings for certain store views, but the dropdown for the store view switcher is to long an does not fit into the screen. When I scroll down to select one of the last entries, the dropdown disappears, so I can not select all store views.
Same problem with store view switcher exists also on dashboard.

Tested in Firefox, IE, Crome (Screen resolution: 1920 x 1080) with Magento CE 2.0.4 and CE 2.0.5
## Steps to reproduce
1. Add a lot of Websites, Stores and Storeviews (about 20)
2. Go to "Stores -> Configuration"
3. Open Dropdown to select Storeview for configuration

![storeview-switcher-bug](https://cloud.githubusercontent.com/assets/12656438/14917043/543e86b0-0e1d-11e6-901f-9231bf99edf1.png)
## Expected result
1. Last Website/Storeview in dropdown should be selectable
## Actual result
1. Storeview dropdown disappears when scrolling to the end of the dropdown

**Comment by sjauck** [comment]
Is there a solution for this problem?

**Comment by piotrekkaminski** [comment]
Internal issue: MAGETWO-52774

**Comment by arkadiych** [comment]
@mbloss-dotsource,  seems it was fixed in https://github.com/magento/magento2/issues/2896

**Comment by vzaporozhets** [comment]
Yes, this problem is fixed by adding scrollbar. Closing this ticket.
