### ISSUE TITLE
HTML Entities in Attribute options incorrectly displayed and handled

### ISSUE THREAD

**Issue by Part-A** [magento/magento2#4351]
When certain characters are entered as part of an Attribute Option, returning to the Attribute to amend the options list, displays the HTML entity name rather than the character. For example " is displayed as `&quot;`

This can be confusing for users who are not familiar with Entity names.

Present in Magento 2.0.4

**Comment by adragus-inviqa** [comment]
relevant SO: http://magento.stackexchange.com/questions/114347/how-to-retain-double-quotation-marks-on-product-attributes

**Comment by piotrekkaminski** [comment]
internal ticket MAGETWO-52772

**Comment by piotrekkaminski** [comment]
This is already fixed in develop branch and will be released as part of 2.1, possibly earlier with a patch release as well.

**Comment by piotrekkaminski** [comment]
Ticket with fix: MAGETWO-50144

**Comment by ranjithtsims** [comment]
Hey Guys,
I'm facing the same issue on 2.1.12 after upgrading the site from 2.1.9. Any clue what's the fix and where I can find it?

**Comment by rdwaugaman** [comment]
The same problem exists in 2.1.14 after upgrading the site from 2.1.9. Same question as above.
