### ISSUE TITLE
Suggestions for Magento 2 missing a basic customer support ticket system

### ISSUE THREAD

**Issue by raykai** [magento/magento2#4352]
General suggestions for Magento 2.

Magento 2 is missing A basic customer support ticket system that keeps everything connected to a customer's account. Something that would allow for admin to respond directly from the backoffice and would be notified whenever there was a ticket opened or overdue. This or integration with something like osTicket which is open source  would be great.

osTicket: http://osticket.com

**Comment by piotrekkaminski** [comment]
@elenleonova  can you respond to that?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Suggestions-for-Magento-2-missing-a-basic-customer-support/idi-p/44733).
