### ISSUE TITLE
Docblock tags are incorrectly generated if longer than 80 characters

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#4353]
## Steps to reproduce
1. Create a **concrete class** with an 81+ chars long FQCN (or a really long name), like `Omg\Since\When\Zf\Harcodes\The\Word\Wrap\Length\Strategy\Proxy\GoodLuckProviderInterface` (it **has** to be longer than 80 characters long).
2. Inject it as a proxy somewhere - `<that-long-class-above>\Proxy` - so that it may be auto-generated by M2.
3. Check the generated code of that proxy.
## Expected result
1. Valid docblocks.
2. The `@return` tag of the Proxy's `_getSubject()` is correct, in one line.
## Actual result
1. The `@return` value is dropped one line, basically _stopping auto-completion from functioning correctly_ (IDE's now assuming `@return null`):

``` php
/**
 * Get proxied instance
 *
 * @return
 * \Omg\Since\When\Zf\Harcodes\The\Word\Wrap\Length\Strategy\Proxy\GoodLuckProviderInterface\Proxy
 */
```

I think the culprit is [ZF\Code](https://github.com/zendframework/zend-code/blob/e3b32fa0fa358643aa6880b04944650981208c20/src/Generator/DocBlockGenerator.php#L261).

By the looks of that thing, **every 81+ char docblock tag** is going to have the same fate. That means `@param`, `@throws` etc.

Since it's generated code - thus not subject to static analysis or code sniffing - I don't think we should wrap the code, regardless of length.

I would put `$docBlockObject->setWordWrap(false);` above [this line](https://github.com/magento/magento2/blob/c7906703dd8b5b824fdc240699e41da05e8287fc/lib/internal/Magento/Framework/Code/Generator/ClassGenerator.php#L90), but I don't know how well that sits with you.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-52768

**Comment by joanhe** [comment]
This issue has been fixed in the scope of MAGETWO-49585
