### ISSUE TITLE
Date of Birth field in Frontend is empty

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4360]
Date of Birth field in Frontend in Customer account edit section appears to be empty, though in backend (hence in DB) the DOB entered either in backend or frontend is present, and if customer does change his DOB in frontend, it is correctly changed in DB, but there is no way it is populating the form field in the frontend, when loading account information page!!!

**Comment by sevos1984** [comment]
This is a known issue (internal ticket MAGETWO-51413), magento team is working on it.

**Comment by devdesco-ceo** [comment]
As I see in dob.phtml file, there is no callout to get customer data from database, just the field. Also, trying to use the suggested widget code in the comment lines in the file did produce 500 error.

**Comment by piotrekkaminski** [comment]
@devdesco-ceo we run into performance issues while fixing MAGETWO-51413 so we need to resolve that first. 

Can you elaborate a little more on the steps to reproduce the 500 error?

**Comment by vzaporozhets** [comment]
Fix for MAGETWO-51413 is already merged into develop. @devdesco-ceo - please, reply if you can reproduce this issue with latest M2 code.
