### ISSUE TITLE
Multishipping discount coupons use applies wrong amounts

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [magento/magento2#4361]
Let's say a customer checks out his order via Multishipping/Multi-address interface.

He applies system generated coupon with 5% discount. The total before discount is $1000. When going through standard checkout, he will receive 5% off his $1000 which is $50.

Via Multishipping, let's say the customer checks out with three addresses, 1# - $400, 2# - 350, 3# - $250. 
The applied coupon with 5% off will apply the $50 to each of the split orders, generating a wrong discount of $150, instead of $50 as supposed.

I am shutting down multi-shipping until this issue is fixed.

**Comment by piotrekkaminski** [comment]
Issue id MAGETWO-5489

**Comment by magento-engcom-team** [comment]
@viktor-zhuromskyy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
