### ISSUE TITLE
2.0.5 - html minification is broken on frontend

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4365]
2.0.5 html minification is broken on frontend

![image 2016-05-01 14 52 16](https://cloud.githubusercontent.com/assets/8983883/14943978/afccb3b8-0fac-11e6-92fe-16d9f8d737f5.png)

**Comment by chris-brabender** [comment]
I'm seeing this issue also in a slightly different area.

    <a href="<?php /* @escapeNotVerified */ echo 'http://www.facebook.com/sharer.php?s=100&' . $_u; ?>" target="_blank" title="<?php /* @escapeNotVerified */ echo __('Share on Facebook') ?>"  class="action share">

becomes:

    <a href="<?php /* @escapeNotVerified */ echo 'http: <i class="icon icon-facebook-square"></i> <span><?php /* @escapeNotVerified */ echo __('Facebook') ?></span></a></li> 

It appears the "fix" to help with commented lines beginning with // has broken anything with a http:// reference too.

**Comment by piotrekkaminski** [comment]
internal ticket MAGETWO-52766

**Comment by guz-anton** [comment]
Hi @devdesco-ceo ,
Could you show examples of _what was before_ and _what was after_?

Also side nodes: you can place your css assets via xml `<css />` tag. Could it be suitable for you?

**Comment by devdesco-ceo** [comment]
Руку you go. Before and after turning HTML Minification on. That is definitely a bug, since 2.0.0 had no issue with minification of HTML.
![image 2016-05-16 22 53 03](https://cloud.githubusercontent.com/assets/8983883/15310799/45dfce0e-1bb9-11e6-8968-b104a9288b5d.png)
![Uploading Image 2016-05-16 22 53 59.png…]()

**Comment by guz-anton** [comment]
Hi @devdesco-ceo ,
I want to say thanks for found none trivial case in Magento's Template minifying feature! We are appreciate.
I've found some roots of the issue. And next step is to produce and deliver proper fix.

I have question to you: *do you expect fix in 2.0.x release?*

Also my question is still valid: can you use `<css />` tag instead of place `<link />` inside templates? It should be more convenient.

**Comment by devdesco-ceo** [comment]
None of my theme's .xml files have the <link but <css tag.
What appears to be causing the problem with minification is the .phtml file that has <link elements in it. I guess it's a M2 Core bug, since it worked fine on earlier versions of M2.

![image 2016-05-18 13 21 55](https://cloud.githubusercontent.com/assets/8983883/15370216/95248354-1cfb-11e6-8281-bed33aa71e6b.png)

**Comment by chris-brabender** [comment]
Another example is the footer of the admin panel as outlined in 
Also related to https://github.com/magento/magento2/issues/4490

    <a class="link-copyright" href="http: Copyright&copy; 2016 Magento Commerce Inc. All rights reserved.</p><div class="footer-legal-system col-m-6">

This was introduced in 2.0.5 when the minify html was fixed for issue https://github.com/magento/magento2/issues/3893

**Comment by PieterCappelle** [comment]
Any update on this?

**Comment by devdesco-ceo** [comment]
Looks like with every new 2.0.x update more and more of new bugs are being introduced :-1:

**Comment by cspruiell** [comment]
hi @devdesco-ceo -- can you provide the source you were minifying in your first example?

**Comment by devdesco-ceo** [comment]
`<?php 
    $_helper = $this->helper('Smartwave\Porto\Helper\Cssconfig');
    $page_layout = $this->getConfig('porto_settings/general/layout');
    if($page_layout == "full_width") {
        $page_layout = "layout-fullwidth";
    } else if($page_layout == "1170") {
        $page_layout = "layout-1170";
    } else if($page_layout == "1280") {
        $page_layout = "layout-1280";
    }
    $boxed = $this->getConfig('porto_settings/general/boxed');
?>
<?php //Include Google fonts character subsets (such as extended latin, cyrillic)
    $d = $this->getConfig('porto_design');
    $charSubset = "";
    if (isset($d['font']['char_latin_ext']) && $d['font']['char_latin_ext']==1 )
        $charSubset .= ',latin-ext';
    if (isset($d['font']['char_subset']) && $d['font']['char_subset'])
        $charSubset .= ','.$d['font']['char_subset'];
    $font_sizes = "%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic";
?>
<?php if (isset($d['font']['custom']) && $d['font']['custom'] && $d['font']['font_family'] == 'google'): ?>
<link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['google_font_family']).$font_sizes; echo $charSubset; ?>' type='text/css' />
<?php else: ?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php endif;?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getDesignFile()?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getSettingsFile()?>">
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $("body").addClass("<?php echo $page_layout; ?>");
    $("body").addClass("<?php echo $boxed; ?>");
});
</script>
`

**Comment by piotrekkaminski** [comment]
This issue was resolved internally and will be published soon.

**Comment by PieterCappelle** [comment]
Works perfectly in 2.1.0-rc3. Thank you!

**Comment by KrystynaKabannyk** [comment]
Hello @devdesco-ceo, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by jmtakahashi** [comment]
Hi, i am experience issues on my 2.1.2 Magento installation installed through Softaculous.  Minifying html in production mode causes catalog product pages to throw a blank white page.  If this bug was fixed, which file needs updating in my installation?

After setting Minify HTML to "NO" in production mode, the page shows again.

**Comment by ooples** [comment]
This is what I see when I enable html minify
![html_minify_error](https://cloud.githubusercontent.com/assets/3075685/21035519/58c68774-bd85-11e6-84ee-2e21184e6732.png)
