### ISSUE TITLE
Widget Banner Rotator has JS error

### ISSUE THREAD

**Issue by egor-volozhanin** [magento/magento2#4368]
## Steps to reproduce
1. add two or more of the banners
2.  add them into the widget banner rotator
3.  make one of them inactive
## Expected result
1.  the widget works without this banner.
## Actual result
1. JS error

![banner-widget-error](https://cloud.githubusercontent.com/assets/19146248/14949905/6fb6f5f4-1056-11e6-8f88-6e5e4414c827.png)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-52765

**Comment by piotrekkaminski** [comment]
The issue was fixed in scope of internal issue MAGETWO-52440 and will be released as part of 2.1 release. Please report Enterprise Edition issues through support to ensure faster resolution.
