### ISSUE TITLE
Missing Items information in Returns EE REST API.

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#4373]
Create a Return from the customer login. Make a call to get the Returns using the REST API GET:/V1/returns/1. This will be giving the the following response which is missing the items related information.

{
  "increment_id": "4000000001",
  "entity_id": 1,
  "order_id": 62,
  "order_increment_id": "4000000024",
  "store_id": 4,
  "customer_id": 27,
  "date_requested": "2016-05-02 08:35:09",
  "customer_custom_email": null,
  "items": null,
  "status": "authorized",
  "comments": null,
  "tracks": null
}

There is no alternative way to retrieve the items information present on this RMA.

When the RMA Search criteria also seems to be not working as it doesn't result in any data for any search criteria.
ex: search API
GET: V1/returns?searchCriteria[pageSize]=2
Even though there are two RMA created(pending and Authorized) none of the RMA were found in response. 

Please let me know how to work around to make Search API work for the RMAs

Thanks in Advanced

**Comment by mazhalai** [comment]
@srinivasanithin please do not post EE related items on github. Please post on the partner portal.

**Comment by centerax** [comment]
Hello, We are facing the issue still.

Was this ever solved?

Thanks.

**Comment by Garusch** [comment]
Hello,

we got the same issue.

Was this problem solved ?
Items, Comments and Tracks are null.

Kind regards

**Comment by centerax** [comment]
@Garusch 2.2.6 includes the fix. Otherwise, Magento can send you a patch if you open a ticket with them.
