### ISSUE TITLE
Error :: Some product variation fields are not valid when creatin configurations

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4374]
## Steps to reproduce
1. try making variants from a simple product that has a "set new from" and "set new to date" set to a past date
## Expected result
1. You should still be able to make product variants (convert this product to a configurable product with associated simple products)
## Actual result

1.You get error "Some product variation fields are not valid"
![2016-05-02_13h50_00](https://cloud.githubusercontent.com/assets/13572447/14953800/44eff5c0-106d-11e6-86b7-285c6d9ba1ec.png)

**Comment by chong1227** [comment]
same error....  did you fix it ?

**Comment by piotrekkaminski** [comment]
@tanya-soroka  can you review and file an issue?

**Comment by veloraven** [comment]
@SidneyBilliet thank you for your report.
Is this issue still valid?
If it is, please provide Magento version used.
If it is not, please close this issue.

**Comment by NetAssoPro** [comment]
I use magento 2.0.7 and i have the same problem. 
Impossible to create a configurable product, in all the case (not only with "set new to date") i have this message ant no more information. The attribute set are the same (mother & children products). I really doesn't understand. How to have more information about it (logs seems to show nothing)
I have more information about it, i debug the code in the file \vendor\magento\module-configurable-product\Model\Product\Validator\Plugin.php and method aroundValidate(),$validationResult display this information : 
`array (size=2)
  'variations-matrix-8-category_ids' => string 'The value of attribute "category_ids" must be set' (length=49)
  'variations-matrix-5-category_ids' => string 'The value of attribute "category_ids" must be set' (length=49)`
An idea ?

**Comment by NetAssoPro** [comment]
Solved from my part, it was due to category field mandatory option. I set it to off and it works. Sorry for the disturb.

**Comment by andimov** [comment]
@NetAssoPro 
Ok, thank you!
