### ISSUE TITLE
Integration tests don't work after checkout

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#4375]
## 
1. Install Magento via composer per composer install, in my example EE 2.0.5
2. cd into the installation directory, e.g.  `cd www`
3. Make the magento CLI binary executable, e.g. `chmod +x bin/magento`
4. Export the bin subdirectory of installation directory into the path, e.g. `export PATH="$PATH:$(pwd -P)/bin"`
5. Enable the developer module as called for in the docs, e.g. `magento module:enable Magento_Developer` (as the docs say, you might need to use force: `magento module:enable --force Magento_Developer`).
6. List all tests via `magento dev:tests:run --help`
## Expected result
1. List all tests incl. integration
## Actual result
1. [InvalidArgumentException]  
   There are no commands defined in the "dev:tests" namespace.

**Comment by mazhalai** [comment]
@tkn98 you mentioned composer install, but did you install magento? via CLI or Web?

**Comment by tkn98** [comment]
Via the command line interface and composer install. The git checkout was done first containing a composer.json requiring the magento package. Composer install then took care to fetch all requirements and do the file-copying (e.g. of the testsuite into the dev folder).

I then wanted to invoke the integration testsuite as it is my understanding that it will take the code-base and do an install of it's own.

**Comment by mazhalai** [comment]
@tkn98 we have created MAGETWO-52652 to investigate and fix.

**Comment by mazhalai** [comment]
@tkn98 do you get a stack trace if you add the `-vvv` option when running the command.

**Comment by tkn98** [comment]
@mazhalai: I tried to reproduce clean but now I get an earlier failure. When running the first bin/magento command (_module:enable_) there is a `require()` failure:

```
$ php -f bin/magento -- -vvv module:enable Magento_Developer
PHP Warning:  require(/path/to/magento2-4375/clone/www/vendor/composer/../../../vendor/autoload.php): failed to open stream: No such file or directory in /path/to/magento2-4375/clone/www/vendor/composer/autoload_real.php on line 71
PHP Fatal error:  require(): Failed opening required '/path/to/magento2-4375/clone/www/vendor/composer/../../../vendor/autoload.php' (include_path='/path/to/magento2-4375/clone/www/vendor/phpseclib/phpseclib/phpseclib:/path/to/magento2-4375/clone/www/vendor/magento/zendframework1/library:/path/to/magento2-4375/clone/www/vendor/phpunit/php-file-iterator:/path/to/magento2-4375/clone/www/vendor/phpunit/phpunit:/path/to/magento2-4375/clone/www/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear:') in /path/to/magento2-4375/clone/www/vendor/composer/autoload_real.php on line 71
```

So I can't provide the -vvv output. I perhaps need to reven more simplify the reproduction case.

/e: While we're at it: the file `bin/magento` is not with executable bits checked in in the repository, that's why I use `php -f bin/magento -- [...]`.

**Comment by mazhalai** [comment]
@tkn98 this failure is due to not running `composer install`

**Comment by mazhalai** [comment]
@tkn98 For now, workaround will be to run installation, before running tests. We are working on this issue, but it is of low priority.

**Comment by tkn98** [comment]
@mazhalai Thanks for the update. Do you have an example on how to trigger the install of the integration test store _only_? Perhaps this is possible with very little efforts.

**Comment by orlangur** [comment]
Obviously it is not possible to run integration tests without application installation, please check http://devdocs.magento.com/guides/v2.2/test/integration/integration_test_execution.html.
