### ISSUE TITLE
Problem when exporting customers

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4376]
The re seems to eb a problem when exporting customers to csv file.
We believe the problem is in the paging ...
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Make sure you have more than 20 customers in your database
   3.go to "all customers" and export to csv
   ![magento-issue1-blurred](https://cloud.githubusercontent.com/assets/13572447/17634792/87fd3172-60d4-11e6-98df-928185022e58.png)
3. you now have a csv file (that should hold all 547 selected customers, see screenshot)
4. Open the csv file 
## Expected result
1. csv file should contain ALL selected customers
## Actual result
1. Csv file always contains a maximum of 20 customers
   ![magento-issue2-blurred](https://cloud.githubusercontent.com/assets/13572447/17634798/90f84ec4-60d4-11e6-9bd1-cfc3559d6889.png)

**Comment by tigerx7** [comment]
Similar issue to: https://github.com/magento/magento2/issues/2961 It affects all admin grids.

**Comment by Krapulat** [comment]
I have the same problem.

**Comment by piotrekkaminski** [comment]
The resolution will be tracked in more generic issue https://github.com/magento/magento2/issues/2961

**Comment by piotrekkaminski** [comment]
Tracked in internal issue MAGETWO-52673

**Comment by piotrekkaminski** [comment]
This is already fixed in developer branch. Should be actually working properly in version 2.0.5.

**Comment by SidneyBilliet** [comment]
@piotrekkaminski  Just tested this in version 2.0.7 and still I get only 21 exported records of the 578 in total.

**Comment by SidneyBilliet** [comment]
@piotrekkaminski 
[export.zip](https://github.com/magento/magento2/files/337222/export.zip)
just tested this in version 2.0.7 and still I get only 21 exported records of the 578 in total. 

![2016-06-28_16h21_49](https://cloud.githubusercontent.com/assets/13572447/16419171/0fd3b202-3d4d-11e6-992b-6bc897b6951e.png)

**Comment by PiotrSiejczuk** [comment]
M2 EE 2.0.7 also confirmed. Issue still remains in the Core
