### ISSUE TITLE
Hardcoded database ids used by Magento2 are broken when auto_increment does not start with 1

### ISSUE THREAD

**Issue by wienczny** [magento/magento2#4377]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Deploy database schema
3. Run "INSERT INTO eav_attribute_set
   (attribute_set_id, entity_type_id, attribute_set_name, sort_order)
   VALUES(1, 0, 'Default', 1);"
4. Deploy database data
## Expected result

Database deploy should either fail or update the value 1. I would suggest the former.
## Actual result

The database is privisoned with entity types with uncommon ids that have hardcoded referenced from code.

The first hardcoded reference that caused problems to us was:

CustomerMetadataInterface::ATTRIBUTE_SET_ID_CUSTOMER = 1

We found this issue when trying to install Magento 2 on a Galera cluster. There new ids are divided between the cluster members there is no guarantee for certain ids. So the database contained entries with ids like 2,4,6,8 etc.
Magento2 should refrain from using hard coded id's in code or at least create those database entries without auto_increment but a defined primary key.

**Comment by mazhalai** [comment]
@wienczny can you specify exact steps, it is confusing since you say step #1 is install and #2 is deploy db schema. etc. Also, did you install via web or CLI?

**Comment by wienczny** [comment]
Step one is install the files only. I used the cli but that should not make any difference.
The problem is that Magento2 uses the Mysql's auto_increment for entries that require a certain id. auto_increment does NOT guarantee neither 1 as starting point nor that the increment is 1. This is perfectly fine if you don't have constants referring to database entries in your code. We are experiencing this with a Mysql Galera multi master cluster. The problem can be avoided by installing on a single database and exporting the result to the cluster. If you really want to have database ids as constants in your code you should use inserts with those ids when creating the data entries.

**Comment by piotrekkaminski** [comment]
We are aware of this issue. Will provide updates in near future.

**Comment by piotrekkaminski** [comment]
@wienczny it should be fixed in 2.0.5 patch, as part of MAGETWO-50224. Can you check if you still have this issue on 2.0.5? We are using Galera ourselves.

**Comment by vrann** [comment]
@piotrekkaminski correct ticket number is MAGETWO-52448 scheduled for 2.0.7

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by bst2002git** [comment]
reference to my post #5873, i'v installed 2.0.1 and updated to 2.1.2 Magento (via composer)...
which tables and entries must be change in Accordance to the hardcoded ATTRIBUTE IDs.
Changing IDs in PHP Code is not so good, i must remember doing this after every Update, bad Idea.
So setting right IDs into tables is i think the best aproach?

By the way updating via composer to 2.1.2 does this include all patches since Version 2.0.1?

**Comment by mavr1982** [comment]
any other suggestion?

It doesn´t work in our environment.

**Comment by Tomasz-Silpion** [comment]
It would be far better to rely on entity_type_code instead entity_type_id in CustomerMetadataInterface
