### ISSUE TITLE
[Feature request] Price slider

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#438]
In another content management systems we have price slider after shop installation.
Also should be great have ability use slider for other numeric attributes.

**Comment by tkacheva** [comment]
Story is in the backlog MAGETWO-43011

**Comment by piotrekkaminski** [comment]
MAGETWO-33402 @tkacheva  seems to be incorrectly referenced as it is closed story for product video, nothing to do with sliders. 

The relevant epic is MAGETWO-43193 but is it not currently scheduled.

**Comment by tkacheva** [comment]
Updated with MAGETWO-43011

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Price-slider/idi-p/46252).
