### ISSUE TITLE
MassAction abstract class refactoring

### ISSUE THREAD

**Issue by ldusan84** [magento/magento2#4380]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a class that extends `Magento\Sales\Controller\Adminhtml\Order\AbstractMassAction`.
3. Use that mass action from dropdown.
## Expected result
1. No errors.
## Actual result
1. PHP Fatal error:  Call to a member function create() on null in /var/www/html/magento2/app/code/Magento/Sales/Controller/Adminhtml/Order/AbstractMassAction.php on line 54

There is a hidden dependency in https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Order/AbstractMassAction.php#L54 

It is not obvious that the child class requires collectionFactory to be injected so it's not transparent which objects are needed for this class to work. 

I tried to create a PR for this, by moving the collection factory to constructor, but the problem is that for example this class:

https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Pdfinvoices.php

Requires `Magento\Sales\Model\ResourceModel\Order\Collection` and this one:

https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Shipment/AbstractShipment/Pdfshipments.php

Requires `Magento\Sales\Model\ResourceModel\Order\Shipment\CollectionFactory`

These two don't have the same parent class or interface, so it seems that it's not possible to type hint.

Any thoughts?

**Comment by piotrekkaminski** [comment]
@maksek please redirect to proper person

**Comment by NadiyaS** [comment]
Hi @ldusan84 ,
thank you for reporting this issue. Internal ticket was created MAGETWO-52955 to consider this problem.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/MassAction-abstract-class-refactoring/idi-p/46391).
