### ISSUE TITLE
Cannot add product with customOptions = "File" to cart with REST API

### ISSUE THREAD

**Issue by wq9** [magento/magento2#4381]
## Steps to reproduce
1. Create a product with Custom Options - Input type: `File` with `Required` set to true.
2. Create a guest-cart with 
   `POST http://example.com/rest/V1/guest-carts`
3. Add that product to the cart with 
   `POST http://example.com/rest/V1/guest-carts/1f285a847c0220210d11be4a629bac61/items`

``` json
{
  "cartItem": {
    "sku": "1",
    "qty": 1,
    "quoteId": "1f285a847c0220210d11be4a629bac61",
    "productOption": {
      "extensionAttributes": {
        "customOptions": [
          {
            "optionId": "1",
            "optionValue": "image.jpg",
            "extensionAttributes": {
              "fileInfo": {
                "base64EncodedData": "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWtJREFUeNpi/P//P8NgBkwMgxyMOnDUgTDAyMhIDNYF4vNA/B+IDwCxHLoakgEoFxODiQRXQUYi4e3k2gfDjMRajsP3zED8F8pmA+JvUDEYeArEMugOpFcanA/Ef6A0CPwC4uNoag5SnAjJjGI2tKhkg4rLAfFGIH4IxEuBWIjSKKYkDfZCHddLiwChVhokK8YGohwEZYy3aBmEKmDEhOCgreomo+VmZHxsMEQxIc2MAx3FO/DI3RxMmQTZkI9ALDCaSUYdOOrAIeRAPzQ+PxCHUM2FFDb5paGNBPRa5C20bUhxc4sSB4JaLnvxVHWHsbVu6OnACjyOg+HqgXKgGRD/JMKBoD6LDb0dyAPE94hwHAw/hGYcujlwEQmOg+EV9HJgLBmOg+FMWjsQVKR8psCBoDSrQqoDSSmoG6Hpj1wA6ju30LI9+BBX4UsC+Ai0T4BWVd1EIL5PgeO+APECmoXgaGtm1IE0AgABBgAJAICuV8dAUAAAAABJRU5ErkJggg==",
                "type": "image/jpg",
                "name": "image.jpg"
              }
            }
          },
          {
            "optionId": "2",
            "optionValue": "1"
          }
        ]
      }
    }
  }
}
```
## Expected result

The product should be added to cart and returned in the API response.
## Actual result

Error message appears: 

``` json
{
"message": "Please specify product's required option(s)."
}
```

I tried with `image/png` in the json request body as well. It still shows the same error.

Removing the `Required` to the File option allows the item to be added to cart, but the attached image is not saved.

**Comment by mazhalai** [comment]
Thank you for reporting, we have created MAGETWO-52550 to investigate and fix.

**Comment by cspruiell** [comment]
@wq9 - when specifying a file as a custom option, the `optionValue` must be "file". The `fileInfo` section should also be corrected to specify the `type` as "image/png" and the `name` with the .png extension. After making those changes you should see the item added to the cart and the image saved.

**Comment by manish-pragma** [comment]
Is there any solution for this problem ??

**Comment by pboisvert** [comment]
@manish-ip there is no fix as the ticket was closed as not a bug. Please see last explanation for how to format to prevent the error. If you are using that and still see an issue, please open a new ticket rather than commenting on closed tickets

**Comment by manish-pragma** [comment]
Thanks for your valuable feedback. Sorry, accidently I have commented on the closed ticket.
