### ISSUE TITLE
Error composer install on EE 2.0.5, MAGETWO-52431

### ISSUE THREAD

**Issue by tkn98** [magento/magento2#4383]
I'm getting the following deprecation notice on installing Magento EE via comoser:

> Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onNewCodeEvent declared at /path/to/name-of-package/www/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

The `composer.json` for this report is:

```
{
    "name": "name-of-package",
    "authors": [
        {
            "name": "Jane Does",
            "email": "info@example.com"
        }
    ],

    "require": {
        "n98/ext.magento2.n98.testframework": "dev-develop",
        "magento/product-enterprise-edition": "2.0.5",
        "composer/composer": "@alpha"
    },

    "repositories": [
        { "type": "composer", "url": "https://repo.magento.com/" },
        { "type": "composer", "url": "https://packages.netz98.de/" }
    ],

    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "2.3.*",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },

    "config": {
        "use-include-path": true
    },

    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "../src/app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php",
            "../vendor/autoload.php"
        ]
    },

    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/"
        }
    },

    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by mazhalai** [comment]
@tkn98 Please do not post EE issues on github. Use the partner portal please.
We are aware of this on latest version of composer, we have an internal task for it. MAGETWO-52431

**Comment by tkn98** [comment]
@mazhalai: If you look closer, this is not a genuine EE issue. Even my report cites it, the component this report is about is MagentoHackathon/Composer that is incorporated in the Magento 2 project. Do you think it's still worth to open an issue in the partner portal?

**Comment by mazhalai** [comment]
@tkn98  I agree with you, however, we do not want to encourage posting of EE issues on Github. Especially posting code, no matter how insignificant. Also, this is not an error, just a Deprecation Notice, do it does not break anything yet.

**Comment by mazhalai** [comment]
@tkn98 fixed in https://github.com/magento/magento-composer-installer/releases/tag/0.1.8
