### ISSUE TITLE
Unable to capture invoice via API "V1/invoices/{id}/capture"  and from Magento2 back-end UI 

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#4385]
Hi there,

Scenario here is we have created an invoice in "pending" status for an order(with payment method as "Credit Card") . On expanding invoice we see an option of "capture" , on clicking it , it says it has been captured but invoice still stays in "pending" state. Same issue is faced when try capturing via provided magento2 API "V1/invoices/{id}/capture"  on page "http://devdocs.magento.com/swagger/index.html#/",
 it is returning "true" on making POST call but there is no change in invoice status, it continues to be  "pending".

**Comment by karanbhomiagit** [comment]
I am also facing the same issue. The invoice status does not change when making a V1/invoices/{id}/capture API call.

**Comment by srinivasanithin** [comment]
Hi 

I see that payment is getting settled in payment gateway (braintree sandbox) when capture rest api call is made but it is not changing the status of the invoice in Magento. It remains in pending status. Can you guys please fix it?

**Comment by mlogvin** [comment]
Hi, internal ticket MAGETWO-52552 created

**Comment by mujtaba2012** [comment]
This is also discussed [here](https://github.com/magento/magento2/issues/2655). Team, any updates on this?

**Comment by alena-marchenko** [comment]
Closing the issue, fix has been delivered to develop branch.
