### ISSUE TITLE
"magento/framework" version 100.0.7 has a bugged code.

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#4386]
I have installed Magento 2.0.5 using composer. Module "magento/framework" is downloaded from
https://repo.magento.com/archives/magento/framework/magento-framework-100.0.7.0.zip

There is an error in `\Magento\Framework\Translate\Inline\Proxy`:

```
protected $subject;
protected $isShared;

public function __sleep()
{
    return ['_subject', '_isShared'];
}
```

The same method from this repo has right [code](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Translate/Inline/Proxy.php#L60):

```
public function __sleep()
{
    return ['subject', 'isShared'];
}
```

**Comment by benbor** [comment]
@flancer64 Hi. All right! The same method from this repo **for 2.0.5 tag** has wrong  [code](https://github.com/magento/magento2/blob/2.0.5/lib/internal/Magento/Framework/Translate/Inline/Proxy.php). I think you can use develop branch or wait one more patch version.

**Comment by flancer64** [comment]
I'll wait.

**Comment by flancer64** [comment]
Hello, guys!

Version [2.0.6](https://github.com/magento/magento2/blob/2.0.6/lib/internal/Magento/Framework/Translate/Inline/Proxy.php) has the same bug. Please, correct.

Thanks.

**Comment by flancer64** [comment]
Version 2.1.0 RC1 has not this bug.
