### ISSUE TITLE
Web Setup Wizard Circular Reference

### ISSUE THREAD

**Issue by OgreMHDW** [magento/magento2#4391]
## Steps to reproduce
1. Install Magento.
2. Select System > Tools > Web Setup Wizard

Expected result
Display Web Setup Wizard

Actual result
Display: 
Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard

![2016-05-03_171317](https://cloud.githubusercontent.com/assets/4369476/15002093/68a57414-1152-11e6-9fc9-38f07820ae51.png)

**Comment by mazhalai** [comment]
@OgreMHDW What version of Magento, OS, webserver? Also, did you deploy via git, composer create-project or downloaded a zip from magento.com?

**Comment by OgreMHDW** [comment]
I have tested this on Magento 2.0.4 and 2.0.5. The OS is CentOS 7 running Apache2. The deploy was done with Composer.

**Comment by mazhalai** [comment]
@OgreMHDW Thank you, we have created MAGETWO-52489 to investigate and fix

**Comment by alex-parra** [comment]
I'm experiencing this also.

**Comment by mazhalai** [comment]
@OgreMHDW  @alex-parra any errors on browser's console log?

**Comment by alex-parra** [comment]
Went to check again.
My /setup/ screen (browser) now is blank and the following error on error_log.

[04-May-2016 14:50:57 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /home/m2bysoftag/public_html/vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132' in /home/m2bysoftag/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /home/m2bysoftag/public_html/vendor/magento/framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/m2bysofta...', 132, Array)
#1 /home/m2bysoftag/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(84): Magento\Framework\ObjectManager\Config\Compiled->extend(Array)
#2 /home/m2bysoftag/public_html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\ObjectManager\ObjectManager->configure(Array)
#3 /home/m2bysoftag/public_html/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): Magento\Setup\Model\ObjectManagerProvider->get()
#4 [internal function]: Magento\Setup\Mvc\Bootstrap\InitParamListener->authPreDispatc in /home/m2bysoftag/public_html/vendor/magento/framework/App/ErrorHandler.php on line 61

I have run setup:di:compile but error still occurs. Running developer mode.

**Comment by mazhalai** [comment]
@alex-parra can you please clean your var/di and var/generation folder and try again.

**Comment by alex-parra** [comment]
Hi @mazhalai. rm -rf var/di and var/generation.
Got the circular reference screen posted by @OgreMHDW.
The browser console log displays:
"NetworkError: 401 Unauthorized - http://magento2.bysoftag.com/setup/index.php/session/unlogin"
Tried a few times... With Firefox v45 and Chrome v50

**Comment by mazhalai** [comment]
@alex-parra Any errors in server log? Does your var directory have correct permissions?

**Comment by alex-parra** [comment]
Server:
- CLOUDLINUX 6.7
- Apache/2.2.29

Magento 2 Cookies Config:
- Cookie Lifetime: 3600
- Cookie Path: /
- Cookie Domain: magento2.bysoftag.com
- HTTP Only: Yes

**Comment by alex-parra** [comment]
error_log is empty now.
- var and subfolders 770, files 660

**Comment by mazhalai** [comment]
@OgreMHDW @alex-parra cannot reproduce this issue. I urge you to check file/folder groups and  permissions again, especially `var/session`(of course assuming session is stored in files and not in redis). I checked on Cento 7.0-64, Apache 2.4, Magento 2.0.5 and cannot reproduce this issue.

**Comment by OgreMHDW** [comment]
File permissions appear normal as the system is creating session files properly. I am also using Centos 7. Apache 2.4 and Magento 2.0.5. There are no errors in the error log. What logs can I check to determine the cause?

**Comment by mazhalai** [comment]
@OgreMHDW any errors in Apache's [access log](https://httpd.apache.org/docs/2.4/logs.html#accesslog) or [error log](https://httpd.apache.org/docs/2.4/logs.html#errorlog)?

**Comment by alex-parra** [comment]
I've been testing but haven't found a solution...
Permissions make no change;
Cookie settings either;
I'll keep trying to figure it out and publish here any findings.
PS: The strange thing is that earlier today, I deleted env.php to trigger reinstall.
Setup kick-in without issues, installation took about 1 or 2 minutes...

**Comment by mazhalai** [comment]
@alex-parra why is that strange? Also, please post here if you have any update regarding original issue.

**Comment by alex-parra** [comment]
@mazhalai Well, if the issue were permissions, setup should not work since I only delete the env.php file.
After install, setup no longer works...
I'm performing a clean install now to see if I get past this.
Thank you.

**Comment by mazhalai** [comment]
@alex-parra Please see [this comment](https://github.com/magento/magento2/issues/4391#issuecomment-218213226) and check both access and error logs.

**Comment by alex-parra** [comment]
Hi @mazhalai 
The clean reinstall solved it for me.
I deleted all files and folders and did a clean install.
For now at least, it's solved for me.
Thanks for your support!

**Comment by OgreMHDW** [comment]
There are no errors in access_log or error_log.

**Comment by mazhalai** [comment]
@OgreMHDW have you setup up these log files in your apache `.conf` file?

**Comment by OgreMHDW** [comment]
Yes, the files are showing normal activity, no errors. In the access_log shows the normal get commands. Shows backendapp/redirect/app and backendapp/redirect/key followed by getting the unlogin URL.

**Comment by mazhalai** [comment]
@OgreMHDW anything in the browser console log?

**Comment by OgreMHDW** [comment]
Just this:
GET https://www.domain.com/setup/index.php/session/unlogin 401 (Unauthorized)
Navigated to https://www.domain.com/setup/index.php/session/unlogin

**Comment by rou9e** [comment]
Got the same problem, any clue ?

**Comment by oshmyheliuk** [comment]
Hi @nowayyy36 
Is this issue still reproduce? 
If so, please write information about magento version and OS you used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Additionally there is a duplicate issue #4687.

**Comment by rrains** [comment]
I found the same on one of my builds, but only one and I noticed the setup url was plain insecure http and the backend session was created in https, so I just changed the protocol 
and reloaded with: https://www.domain.com/setup and it works.

Maybe related to the fact that this build is set to use https everywhere, but I have not tested this. Hope it helps.
