### ISSUE TITLE
When updating, bad PHP version is reported

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4392]
When trying to update with Web Setup Wizard, and running readiness check, it is reported PHP version 5.6.20. when I execute <?php phpinfo() ?>, reported version is 5.6.13. The latter is correct. Why the wizard detects 5.6.20 and how can I  fix it?

**Comment by thaiphan** [comment]
Are you running <?php phpinfo() ?> on the same server as Magento?

**Comment by jaimestuardo** [comment]
of course

**Comment by mazhalai** [comment]
@jamescowie is this after installation? during upgrade or update? This php version is the CLI version, ie the php version that cron uses. Please update your CLI PHP to be the same as the one used by web.

**Comment by mazhalai** [comment]
@jaimestuardo can you please post screenshot of your error?

**Comment by ghost** [comment]
@jaimestuardo Did the PHP readiness check fail? (Working on a documentation update.)

**Comment by foxer-zt** [comment]
@jaimestuardo, readiness check detects PHP version by parsing composer.lock, so you can just regenerate it.

**Comment by jaimestuardo** [comment]
I have removed composer.lock but I get this error now:

"Sorry, we can't take that action right now."

**Comment by mazhalai** [comment]
@jaimestuardo please recreate it by running `composer install` in your magento root folder

**Comment by jaimestuardo** [comment]
I am in magento root folder, however, the .json file is trying to be located in another location.

[root@vps-1128921-x /home/depasa/public_html] # composer install
X-Powered-By: PHP/5.6.13
Content-type: text/html; charset=UTF-8

Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Composer could not find a composer.json file in /usr/local/bin
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
[root@vps-1128921-x /home/depasa/public_html] #

**Comment by jaimestuardo** [comment]
I have solved the problem about PHP CLI, but now when running composer install, authentication is required for repo.magento.com. I have used my same credential of MarketPlace, but it did not work.

**Comment by ikruchynskyi** [comment]
@jaimestuardo, please, look here for solution http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html.

**Comment by jaimestuardo** [comment]
I have finally updated, however, this is shown at the end:

Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onNewCodeEvent declared at /home/depasa/public_html/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

On the other hand, system was upgraded to version 2.0.4, instead of 2.0.5

**Comment by mazhalai** [comment]
@jamescowie we are working on fixing that deprecation notice. Ticket MAGETWO-52431

**Comment by ghost** [comment]
@jaimestuardo To help with the PHP readiness check, we just published [this topic](http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/php-version.html). Please let us know if you think it's useful.

**Comment by jaimestuardo** [comment]
I have followed instructions in that page,  but it did not help at all. These are the commands I issued in console:

```
[root@vps-1128921-x /home/depasa/public_html] # service httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
[root@vps-1128921-x /home/depasa/public_html] # echo $PATH
/usr/pgsql-9.4/bin/:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/.wp-cli/bin
[root@vps-1128921-x /home/depasa/public_html] # which php
/usr/bin/php
[root@vps-1128921-x /home/depasa/public_html] # /usr/bin/php -v
PHP 5.6.13 (cli) (built: Sep  9 2015 08:30:12)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
[root@vps-1128921-x /home/depasa/public_html] # php -i | grep "PHP Version"
PHP Version => 5.6.13
PHP Version => 5.6.13
[root@vps-1128921-x /home/depasa/public_html] #

```

phpinfo page shows this:

![image](https://cloud.githubusercontent.com/assets/9195659/15047051/57e10d24-12b9-11e6-8dc1-89b1bcf5c123.png)

![image](https://cloud.githubusercontent.com/assets/9195659/15047035/4986e906-12b9-11e6-9021-ffa7215880af.png)

![image](https://cloud.githubusercontent.com/assets/9195659/15047211/43a93ccc-12ba-11e6-97bf-ce0a38ce0728.png)

**Comment by jaimestuardo** [comment]
Maybe it would help if you tell me what component or module or whatever is ran to detect PHP version. Maybe I could troubleshoot the problem by myself

**Comment by mazhalai** [comment]
@jaimestuardo it is not a module, it is within setup/ if you want to investigate.

**Comment by ghost** [comment]
@jaimestuardo Did you resolve this? I am facing the same issue.

Using PHP 5.6.20 and "always_populate_raw_post_data" is set to -1 in the php.ini being used for cron. I removed .setup_cronjob_status magento2/var/ and every time it gets regenerated it throws the error "Your PHP Version is 5.6.20, but always_populate_raw_post_data = 0.".

**Comment by piotrekkaminski** [comment]
@crtsl @jaimestuardo please make sure you use the same setting for CLI and for Web. This message you are seeing is generating using cron process, which uses command line version of PHP. In SOME systems, command line PHP uses different INI file. What you can do to check is to SSH to the server, run php -i | grep ini and see which ini files are loaded, then make sure the setting is correct.

**Comment by ghost** [comment]
@piotrekkaminski Even if I run the cron with the -c argument specifying which php.ini file to use(which knowingly has always_populate_raw_post_data = -1), the error still comes back. Is there something else that could be causing this?

**Comment by jaimestuardo** [comment]
When issuing "php -i | grep ini" command I get this:

```
Configuration File (php.ini) Path => /opt/php5-6/lib
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
user_ini.cache_ttl => 300 => 300
user_ini.filename => .user.ini => .user.ini
init_command_executed_count => 0
init_command_failed_count => 0
com_init_db => 0

```

However, there is no php.ini file in that folder.

**Comment by mazhalai** [comment]
@jamescowie deprecation notice has been fixed in https://github.com/magento/magento-composer-installer/releases/tag/0.1.8 Hence closing issue.
