### ISSUE TITLE
Minimum Order Amount doesn't work at the checkout page

### ISSUE THREAD

**Issue by kozhemyakin** [magento/magento2#4395]
## **Steps to reproduce**
1. Go to Configuration -> Sales: enable "Minimum Order Amount" and set some value in "Minimum Amount" _(e.g. Minimum Amount = 40$)_
2. Go to Marketing -> Cart Price Rules: create some code with fixed amount discount _(e.g. Discount = 20$)_
3. Go to frontend: add some product, which has price more than Minimum Amount _(e.g. Product Price = 45$)_ to cart and go to the checkout page
4. Apply code at the checkout page _(now order total equals 25$. It's less than set Minimum Amount)_
5. Place order
## **Expected result**
1. Unable to place order, that has total less than set Minimum Amount
## **Actual result**
1. Order is placed successfully, although order total was less than set Minimum Amount
## 

_Additional info: all works fine at shopping cart page_

**Comment by ishakhsuvarov** [comment]
@kozhemyakin Thank you for reporting this issue. We have tried to reproduce it with the installation from the `develop` branch but with no luck. Which version are you using?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by 24rtj** [comment]
fc497da
