### ISSUE TITLE
Custom address attribute not getting saved in sales order address (Enterprise Magento ver. 2.0.2)

### ISSUE THREAD

**Issue by abhilashac** [magento/magento2#4397]
## Steps to reproduce
1. Create an address attribute from stores >> Attribute >> Customer address.
2. Set the attribute input type as Text Field
3. Set show in Frontend and show in Customer Address Registration and Customer Account Address forms.
4. The new text field will show up in forms.
5. Add an address in Customer >> Address Book >> Add new address, also input some value in the new attribute field.
6. Also, update the address template in Admin Section >> Stores >> Configuration >> Customer Configuration >> Address Templates by adding that attribute.
7. Place an order using that address.

Expected result
1. In checkout process, the address should be displayed in the right hand side along with the customer attribute.
2. The attribute along with the address should show up in admin >> Sales >> Orders >> Order details of the order.

Actual result
1 - In checkout process, the address does not have the custom address attribute in the right hand side.
2 - The newly created attribute does not get saved in order section.

**Comment by vkublytskyi** [comment]
This issue have been already fixed in 2.0.5.
@abhilashac Please do not post EE related issues on github. Please use partner portal for such reports.

**Comment by mazhalai** [comment]
Closing since this an EE issue.
