### ISSUE TITLE
Deploy Static files - backend only or specific module

### ISSUE THREAD

**Issue by alex-parra** [magento/magento2#4398]
First time here, so apologies if not the right place for this.

I've search and could not find a way to deploy static files for the backend only.
Is this possible, planned or would cause issues?
Or is it possible to deploy static files for a specific module?

When we run bin/magento setup:static-content:deploy it goes through all themes. 
And it takes too long (about 2 minutes) considering the only files that need updating are two from one module and backend only.
I've read that it's supposed to create symlinks in developer mode but that's not happening in my case.
- Developer mode confirmed;
- Deleted two files;
- Reload page;
- 404 for those two files;

Or I'm missing something?
Thanks

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
