### ISSUE TITLE
Render product options with template instead of directly with block

### ISSUE THREAD

**Issue by paales** [magento/magento2#4399]
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Block/Product/View/Options/Type/Select.php

It currently renders the HTML in the block, would be nice if is rendered in a template. That would make customization a lot easier.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Render-product-options-with-template-instead-of-directly-with/idi-p/45131).
