### ISSUE TITLE
Visual Swatch for Custom Options

### ISSUE THREAD

**Issue by sameasterling** [magento/magento2#4401]
We seriously need visual swatches for custom options.

**Comment by rafaelstz** [comment]
I see it as necessary, if the customer does not manage inventory, but has variations like configurable.

**Comment by antboiko** [comment]
Hello @sameasterling , thanks for your inquiry. We've created internal ticket MAGETWO-52691 for this feature and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Visual-Swatch-for-Custom-Options/idi-p/46019).
