### ISSUE TITLE
Rest API: JSON Response for Orders showing incorrect shipping address

### ISSUE THREAD

**Issue by rwemmercksys** [magento/magento2#4402]
## Steps to reproduce
1. Create at least 2 Orders in Magento 2.0.5
2. Execute a REST call to retrieve orders using GET Method
   a. Example URL: http://192.168.1.9/magento/index.php/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=status&searchCriteria[filter_groups][0][filters][0][value]=Processing
3. If you use my url, be sure to change the order statuses to processing for both orders.
## Expected result
1. If you navigate down these nodes in the JSON response: extension_attributes -> shipping_assignments -> shipping -> address, I expected the address to show the correct shipping address information.
## Actual result
1. The first order's shipping address is actually the second order's shipping address.
2. Attached, an example of the JSON response.
   [Rest-Orders-json-response.txt](https://github.com/magento/magento2/files/249181/Rest-Orders-json-response.txt)
3. Please note that the attached document has 2 orders. The first is incorrect, the second is correct.

**Comment by YevSent** [comment]
Hi @rwemmercksys, thanks for your reporting. We created internal ticket MAGETWO-52554.

**Comment by YevSent** [comment]
Duplicate for #4019

**Comment by asemenenko** [comment]
Hi @rwemmercksys 
#4019 is already resolved on develop branch. Closing this one as duplicate.
