### ISSUE TITLE
New 2.0.5 does not compile theme created for 2.0.2

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#4403]
## Steps to reproduce
1. Install Magento CE or EE.
2. Use theme created to 2.0.2 in 2.0.5.
3. This theme must have the folder `web/css/source`.
4. Remove files in `var/*` and `pub/static/*`.
5. Run this command in terminal `php bin/magento setup:static-content:deploy`.
## Expected result
1. The static files are generated without errors in the terminal.
2. Apparently everything works normally.
## Actual result
1. When you open in browser, their modifications in `web/css/source` were not applied and layout is broken.
2. You can see the main difference in the width of DIV `.header.content`

**Comment by magento-engcom-team** [comment]
@rafaelstz, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
