### ISSUE TITLE
Visual Swatch and Filterable (no results) not displaying swatches correctly

### ISSUE THREAD

**Issue by jonsaf** [magento/magento2#4404]
## Steps to reproduce
1. If you have visual swatches as a selection for attribute with Filterable (no results) setting, and that attribute is being used to create a configurable product, the swatches displayed do not confirm with what is expected from other attributes with the same settings.  
## Expected result
1. Filterable (no results) means that what should display is all the results pertaining to the selected products in the category.  
## Actual result
1. However, Visual Swatch Filterable (no results) is displaying every color swatch, even the ones with no selection.  This does not work with 400+ colors and 85% being null.

See attached pics.  As a visual swatch how it is displayed and as a dropdown how it is displayed.
<img width="240" alt="screen shot 2016-03-18 at 5 01 39 pm" src="https://cloud.githubusercontent.com/assets/13703880/15028360/6838ce62-11fd-11e6-9330-d9611e6b090e.png">
<img width="259" alt="screen shot 2016-03-18 at 5 00 15 pm" src="https://cloud.githubusercontent.com/assets/13703880/15028359/68385c5c-11fd-11e6-9420-c0405df7a308.png">

**Comment by tkacheva** [comment]
@jonsaf Filterable (no results) means that Magento shows all the product attribute values that are configured to be used in layered nav (even if there is NO_RESULT in product grid)
Please use  Filterable (with results) to achieve what you want.  Filterable (with results) means that swatches will only appear for values where the number of results (the number in parentheses next to each value) is greater than zero
