### ISSUE TITLE
Can anybody tell me how to install/add an extension from extension key in Magento 2 stepwise?

### ISSUE THREAD

**Issue by agjalpm** [magento/magento2#4406]

**Comment by gewaechshaus** [comment]
https://firebearstudio.com/blog/how-to-install-magento-2-modules-extensions.html

**Comment by mazhalai** [comment]
@agjalpm this is only for bug reporting. Please post your question on [stack exchange](http://magento.stackexchange.com/) or [Magento community forums](https://community.magento.com)
