### ISSUE TITLE
system ram requirement

### ISSUE THREAD

**Issue by raykai** [magento/magento2#4407]
just wondering what it minimum Ram and the recommended Ram would be as in the system requirement is missing this info.

**Comment by gewaechshaus** [comment]
You can't give an exact value how much RAM is needed cause it depends on what you want to do with the system, how many transactions it should be able to handle, how much data does innodb hold and so on... 

F.e. - in some cases it makes sense to split the db and app servers. A DB-Server normally needs more RAM than an APP-Server which needs more CPU to handle php processes etc.

If you would go for a single server solution, i would recommend 8GB+ at least, keep the focus on the cpu as usually php is the bottleneck in magento. Put varnish in front, use opcode caching and/or memcache/redis. If u decide to save sessions as files, go for ssd.

**Comment by vancoz** [comment]
Hi @raykai we have not added php memory limit requirements on installation readiness check. But some operations can require more memory, for example compilation process requires 756M of memory and we added this as requirement in Setup Wizard Readiness Check step. Also Setup Wizard needs more memory to complete Upgrade/Install process(based on Composer), so we recommend to have at least 2G for this. I believe this check and warning will be part of 2.1.0 release.
