### ISSUE TITLE
Cant checkout with Paypal PayFlow Pro

### ISSUE THREAD

**Issue by pynej** [magento/magento2#4408]
We have everything configured and can see the approval response from PayFlow in the debug log, but the fronted/spiny wheel never goes away an no order is ever created.

No errors or the logs or in the browser console.

Here is the approval response in the log:

```
'request' => 
  array (
    'user' => '****',
    'vendor' => '****',
    'partner' => '****',
    'pwd' => '****',
    'verbosity' => 'HIGH',
    'BNCODE' => 'Magento_Cart_Community',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'createsecuretoken' => 'Y',
    'securetokenid' => '108d7c2cecc18c90046869377181****',
    'returnurl' => 'https://crowehorwath.superior.org/paypal/transparent/response/',
    'errorurl' => 'https://crowehorwath.superior.org/paypal/transparent/response/',
    'cancelurl' => 'https://crowehorwath.superior.org/paypal/transparent/cancel/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'Jeremy',
    'lastname' => 'Pyne',
    'street' => '****',
    'city' => 'Kentwood',
    'state' => 'MI',
    'zip' => '49512',
    'country' => 'US',
    'email' => 'jpyne@****',
    'shiptofirstname' => 'Jeremy',
    'shiptolastname' => 'Pyne',
    'shiptostreet' => '****',
    'shiptocity' => 'Kentwood',
    'shiptostate' => 'MI',
    'shiptozip' => '49512',
    'shiptocountry' => 'US',
  ),
  'result' => 
  array (
    'result' => '0',
    'securetoken' => 'Plgu0x5uu60Krhc0Km3IL****',
    'securetokenid' => '108d7c2cecc18c90046869377181****',
    'respmsg' => 'Approved',
    'result_code' => '0',
  ),
```

I'v tried in test and production, with precompiled code and without, in developer mode and production. No luck and no errors anywhere.

Running Magento 2.0.4, Apache 2.4, PHP 5.6.20.

**Comment by dkvashninbay** [comment]
Hi @pynej ,
May your issue be related to this one https://github.com/magento/magento2/issues/3509 ?

**Comment by pynej** [comment]
Hrm.  I'm not sure.  Now that you mention it I notice that the `amt` in the log is 0 but the cart actually had a total sale of $2.  But it also comes back and says approved.  So maybe it is approved but for the wrong amount so nothing happens.  

I do have Payment Action set to Authorization so maybe that is causing the issue?  I will read through some of the documentation links in that other bug can see if I can get different results. 

Regardless the system should generate some sort of error or logs instead of nothing at all witch is what is is doing :(

**Comment by nes710** [comment]
I had the same issue took me weeks to get it to work.

Set Payment Action to Sale not Authorization or you will not get payment.  In PayPal Manager set URL Method to POST instead of GET.  Make sure secure token is checked.  Also be sure you're not using the same user as the PayPal Manager, create a user under it for Magento.

**Comment by pynej** [comment]
We have went with another solution.  It does appear that this authorization was the issue.  The problem is that our business process(not in my control) if to do authorizations and manually approval so we couldn't just use Sale.

Anyway, that aside I feel that these payment modules should generate actually error messages in the logs.  Basically every payment and shipping module doesn't generate any sort of logging when configured incorrectly so I as the administrator and left doing trial and error and then trying another order.  Very time consuming and some simple and basic level of error logging would solve more problems in a few minutes.  Even when i turn on the Debug option on most the modules, that just makes them dump the XML request, but still no actually error or informational logs.  Please fix Oo

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Cant-checkout-with-Paypal-PayFlow-Pro/idi-p/45126).

**Comment by mvaisberg** [comment]
I have the issue where payflow stuck on loading after place order. The ResquestSecureToken response is approved but after that nothing happend. 

![selection_069](https://user-images.githubusercontent.com/4543889/38562691-8644c272-3cb1-11e8-987a-a80ae4c1d706.jpg)
![selection_068](https://user-images.githubusercontent.com/4543889/38562694-8669e85e-3cb1-11e8-839e-6c547c8a629b.jpg)
![selection_070](https://user-images.githubusercontent.com/4543889/38562738-a1a0b346-3cb1-11e8-9a7b-54797d2b545c.jpg)


Someone have any clue?

**Comment by abude** [comment]
is this fixed or not? i'm having the exact same issue on magento 2.3.2

**Comment by abude** [comment]
@mvaisberg did you manage to solve this ? Thanks!

**Comment by rupesh-tangible** [comment]
@abude  i'm having the exact same issue on magento 2.3.5-p1. Here sandbox details is working fine. I placed an order in sandbox mode. 
But site goes live we change it to live mode and put actual details that time spiny wheel never goes away an no order is ever created.

I got below log message
[2020-11-11 10:07:04] main.DEBUG: array (
  'request' => 
  array (
    'user' => '****',
    'vendor' => 'XXXXX',
    'partner' => 'VSA',
    'pwd' => '****',
    'verbosity' => 'HIGH',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'currency' => 'AUD',
    'createsecuretoken' => 'Y',
    'securetokenid' => 'WDfsdffQCLXo9HIwhxgihWwPlRFmC9dD6',
    'returnurl' => 'https://mysite/paypal/transparent/redirect/',
    'errorurl' => 'https://mysite/transparent/redirect/',
    'cancelurl' => 'https://mysite/paypal/transparent/redirect/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'C',
    'lastname' => 'D',
    'street' => 'Bentleigh East',
    'city' => 'BENTLEIGH EAST',
    'state' => 'VIC',
    'zip' => '3165',
    'country' => 'AU',
    'email' => 'myemail@xyx.com.au',
    'shiptofirstname' => 'name',
    'shiptolastname' => 'D',
    'shiptostreet' => 'Bentleigh East',
    'shiptocity' => 'BENTLEIGH EAST',
    'shiptostate' => 'VIC',
    'shiptozip' => '3165',
    'shiptocountry' => 'AU',
  ),
  'result' => 
  array (
    'result' => '0',
    'securetoken' => 'Wsdfdsfksh2kCqvZf4xBaiPAK1',
    'securetokenid' => 'VerwLXo9HIwhxgihWwPlRFmC9dD6',
    'respmsg' => 'Approved',
    'result_code' => '0',
  ),
) [] []
