### ISSUE TITLE
Magento 2 problem on Godaddy VPS Stylesheel not loaded...

### ISSUE THREAD

**Issue by palmultimedia** [magento/magento2#4410]
I have created VPS on godaddy and install Magento 2 CE 2.0.5 successfully. After installation when I try to open front page or admin page it comes like without style sheet loaded...like in plain text only.
Contacted Godaddy saveral time and have no satisfied answer.
mod_rewrite - checked and working...!
here is domain name 
www.hyperretail.co.uk

Can any one guide me where is the problem?

**Comment by palmultimedia** [comment]
I have created VPS on godaddy and install Magento 2 CE 2.0.5 successfully. After installation when I try to open front page or admin page it comes like without style sheet loaded...like in plain text only.
Contacted Godaddy saveral time and have no satisfied answer.
mod_rewrite - checked and working...!
here is domain name 
www.hyperretail.co.uk

Can any one guide me where is the problem?

**Comment by stamster** [comment]
Which web server in particular do you use? What HTTP status code do you get from web server while tying to load styles? 404 is expected, but can be also 500. 
It must be some issue with your configuration of pub or var dirs, and/or static content not deployed. 
Run  cache:clean, cache:flush, setup:di:compile, setup:static-content:deploy from command line using magento CLI app ("binary"). 
example:
`magento setup:di:compile`

EDIT: I just visited your site. Forget about first two questions then :) So, I would guess that you need to run commands:
`magento setup:di:compile && magento setup:static-content:deploy`
Also, check your $MAGE_ROOT variable.

**Comment by palmultimedia** [comment]
I am new here,, where can I run command? can I run in SSH? Please give me some steps to I can understand..

**Comment by palmultimedia** [comment]
How to check $MAGE_ROOT??

**Comment by stamster** [comment]
Yes, you need SSH/terminal access. There are other ways to achieve this by custom PHP script / exec(), but SSH is preferred.

Your $MAGE_ROOT is set in web server VHOST configuration.

Your Magento is now broken:

There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 577738707933

Check report log in var/reports with the generated ID.

*_For your convenience, I published shell script I created for easy Magento2 operations: *_

https://gist.github.com/stamster/21c9c518f2fd6ac3521b5d671db58449

**Comment by maksek** [comment]
@palmultimedia please use forum and documentation for setup related questions. This issues doesn't describe particular bug in magento 2 codebase, so closing it.
