### ISSUE TITLE
Unable to extend primary config

### ISSUE THREAD

**Issue by adamzero1** [magento/magento2#4412]
Hi,

I'm struggling to see a way to extend primary configuration, without copying files outside of the vendor folder. (which I see as bad practise, though this may be wrong?)

I am trying to extend the the model Magento\Framework\Setup\BackupRollback to change the functionality of the method: getCodeBackupIgnorePaths() (to alter the exclude paths - as they aren't configurable)

So I was hoping I could simply add a "preference" in a di.xml however the only di.xml used by the object manager when constructing this object is in app/etc/di.xml
This is because when the "primary" config loader searches for config files, it is forced to look in the location: [Magento base dir]/app/etc/ with a pattern of: "_di.xml,_/*di.xml" this can be seen at: vendor/magento/framework/Setup/BackupRollback.php:259

Which excludes any di.xml files in the vendor folder, is there a reason for this?

I can see two good approaches (though I'm sure there are others that I have missed)
- submit a pull request that contains code the allow the exclude paths to be configured
- submit a pull request that allows "primary" config files to be declared in the vendor directory

Could you please suggest what you think is best.

Many thanks
Adam

**Comment by veloraven** [comment]
@adamzero1 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by kassner** [comment]
@veloraven some configurations are impossible to overwrite without editing `app/etc/di.xml` directly, so I see this as a technical issue. Can you explain further why is not?

**Comment by kassner** [comment]
@veloraven ping
