### ISSUE TITLE
Magento 2.0.5 product import giving 

### ISSUE THREAD

**Issue by nes710** [magento/magento2#4413]
## Steps to reproduce
1. Upgrade to Magento 2.0.5
2. Run product import, even export/import sample data
## Expected result
1. Products import
## Actual result
1. "General system exception happened"

Had no issues importing same file with 2.0.2 and 2.0.4.  Have tried redownloading sample product upload file from 2.0.5 and re-uploading it and still get same error.

**Comment by dexterityzx** [comment]
Try to use UTF-8 encoding for your csv file.

**Comment by BaDos** [comment]
Hi @nes710 

Thank you for reporting.

I cannot reproduce this issue.
Please, link import file for reproducing that you use.
Do you have the same problem on 2.0.9 or 2.1?

**Comment by samgranger** [comment]
I am no longer experiencing this issue (2.1).

**Comment by nes710** [comment]
I no longer have this issue on Magento 2.1.
