### ISSUE TITLE
Gift Message not returned via API on getList

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4414]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Call API GET /V1/orders?searchCriteria=
## Expected result
1. Result contains list of all orders including [extension_attributes][gift_message] object.
## Actual result
1. gift_message object is not returned.

When retrieving a specific id using:
GET /V1/orders/xxx

The [extension_attributes][gift_message] object is returned.  The documentation states it should be returned for getList also.

**Comment by pboisvert** [comment]
Mark--can you have the team validate if this is reproducible?

**Comment by ishakhsuvarov** [comment]
@jim5359 Thank you for reporting the issue. We have created an internal ticket `MAGETWO-53362` to investigate and fix.

**Comment by KrystynaKabannyk** [comment]
Hello @jim5359, this issue has been fixed in Magento EE 2.1 RC2, that's why I'm closing it. Thank you for reporting the issue! If you have any questions or additional information you are welcome to reopen it or create another one.

**Comment by tvainisi** [comment]
Hello @KrystynaKabannyk The gift message seems to me to be not included in the json response in 2.1.1 CE.
