### ISSUE TITLE
Help link, links to Magento Community Edition, 1.9.2.4 getting started guide

### ISSUE THREAD

**Issue by enochrod** [magento/magento2#4415]
## Steps to reproduce
1. Go to stores > configuration
2. Click on help icon with question mark
## Expected result
1. Should go to help page for Magento 2
## Actual result
1. Goes to Magento Community Edition, 1.9.2.4 getting started page
   http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#configuration/scope.html

**Comment by ghost** [comment]
Thanks for letting us know. Forwarding to the merchant documentation team.

**Comment by ghost** [comment]
@enochrod Sorry for the delay. This appears to be an issue in CE/EE 2.0.x but not in 2.1.0. What version are you using? Do you still see the issue?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
