### ISSUE TITLE
Associating simple products with configs programmaticaly fails

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#4418]
## Steps to reproduce

Using magento 2.0.5
Created 1 config product and 3 simple products.
All having same attribute set.

Now trying to associate

...

```
$configProduct->setCanSaveConfigurableAttributes(true);
                $configProduct->getTypeInstance()->setUsedProductAttributeIds(
                    [$configAttribute->getAttributeId()], $configProduct

                );
                $configProduct->setNewVariationsAttributeSetId($configProduct->getAttributeSetId());
                $configProduct
                    ->setAssociatedProductIds($associatedProductIds)
                    ->setConfigurableAttributesData(
                        [
                            [
                                'attribute_id' => $configAttribute->getId(),
                                'attribute_code' => $configAttribute->getAttributeCode(),
                                'frontend_label' => $configAttribute->getDefaultFrontendLabel(),
                                'values' => $attributeValues,
                            ],
                        ]
                    );
```

and now problematic part

```
$this->productRepository->save($configProduct);
```
## Expected result
1. I would expect that 3 simple products will be associated with config
## Actual result
1. No errors logged
2. Configurable product has no child / associated simple products

What I found working is to save model directly not using product repository

```
$configProduct->save();
```

Can't explain why it works and also there is no good example in the framework how to do it correctly

**Comment by pboisvert** [comment]
@antboiko Anton--can you confirm if expected or an issue and take next action as appropriate?

**Comment by antboiko** [comment]
Hello @redboxmarcins , please refer to this link https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/ConfigurableProduct/_files/product_configurable.php and check the way you can associate simple products with configurable.

Best,
Anton.

**Comment by antboiko** [comment]
I'm closing this issue due to no response. Feel free to reopen if you have an update.

**Comment by electricBonfire** [comment]
The link above is out of date
