### ISSUE TITLE
Configurable product disabling lowest price associated product still shows its price

### ISSUE THREAD

**Issue by shayanhusaini** [magento/magento2#4419]
## Steps to reproduce
1. Create a configurable product and associate simple products with it.
2. Disable the lowest price simple product
## Expected result
1. It should display the price of lowest enabled product
## Actual result
1. Displays the price of lowest disabled product
   ![1](https://cloud.githubusercontent.com/assets/9675791/15072510/a77df132-13ac-11e6-9799-9e5b1b5bc98e.png)
   ![2](https://cloud.githubusercontent.com/assets/9675791/15072509/a77dd5e4-13ac-11e6-96d2-882c638f3b00.png)
   ![3](https://cloud.githubusercontent.com/assets/9675791/15072511/a77e389a-13ac-11e6-9d3b-85da686b5c65.png)

After setting the price of disabled product to 0 works perfectly and displays the correct price.

**Comment by shayanhusaini** [comment]
Any update on this issue?

**Comment by pboisvert** [comment]
@antboiko can you have the team validate this issue and file a ticket if confirmed

**Comment by antboiko** [comment]
Hi @shayanhusaini, thanks for reporting this issue. We've created internal ticket MAGETWO-52717 to fix this.

Best,
Anton.

**Comment by shayanhusaini** [comment]
How soon is it going to be resolved???

**Comment by Cacasapo** [comment]
In 2.1, setting the disabled product's price to 0 does not fix this. I had to set the disabled products' price to the lowest enabled product price as a workaround.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 as of today.
