### ISSUE TITLE
OpenID Support

### ISSUE THREAD

**Issue by SmthDiff** [magento/magento2#442]
I don't know if someone else has already opened an issue about this or if it's already a work in progress, but I would really like to see OpenID implemented in Magento2 for the backend users. I'm not entirely sure if it would also be a good idea for frontend users but for the backend it would help a lot. For example for big agencies making a Magento Webpage for a Client. It is easier for employees to use their existing OpenIDs on every project. No need to have a centralized password database. Everyone knows their logins and it simply works. I would really like that.
Apart from that I really like how Magento2 is coming along and hope it's released soonish :)

**Comment by ilol** [comment]
@SmthDiff hi,
Very interesting suggestion. We are thinking about Single Sign On, but I can`t say about implementation date. The main reason is that the several popular extensions are existing. You could find them on Connect or via internet search.
And welcome to contribute to Magento 2 and to create new extension. Thank you for your activity and let me close this issue. I could reopen it anytime on your request.

**Comment by joshdifabio** [comment]
This would save agencies a lot of time and effort.

**Comment by pitbulk** [comment]
I implemented a SAML extension for the frontend and is available on the marketplace:
https://marketplace.magento.com/sixtomartin-onelogin-module-saml2.html

but found some problems when implementing the backend and don't found an elegant way to solve them. The main one is that all admin urls are protected by the admin authentication, so I'm not able to define my SAML endpoints:
http://magento.stackexchange.com/questions/107294/magento2-how-make-public-a-backend-route

If there are potential customers interested in OpenID Support I think I'm able to implement it.
@SmthDiff  @joshdifabio are you still interested on that feature?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/OpenID-Support/idi-p/44954).
