### ISSUE TITLE
Usage of Magento\Framework\Stdlib\DateTime isn't normalized in the source

### ISSUE THREAD

**Issue by riversy** [magento/magento2#4420]
Please open following classes:
\Magento\Eav\Model\Entity\Attribute\Backend\Time\Updated
\Magento\Eav\Model\Entity\Attribute\Backend\Time\Created

We can see that in both of classes \Magento\Framework\Stdlib\DateTime\DateTime is injected but never used. 
![cool](https://cloud.githubusercontent.com/assets/773002/15072770/cab4aa7e-139d-11e6-981e-8a5c02242fe6.png)

**Comment by mazhalai** [comment]
@riversy thank you for reporting, we have created ticket MAGETWO-52598 to investigate and fix.

**Comment by ishakhsuvarov** [comment]
@riversy Closing, as the fix for this issue has been delivered to the `develop` branch in the scope of the linked commit.
Thank you for contribution. Please reopen if you have any additional questions.
