### ISSUE TITLE
Admin username  is not case sensitive   during login

### ISSUE THREAD

**Issue by devamitbera** [magento/magento2#4423]
Hi Magento,

created an username is Amit ,password: paas1234 for backend at default Magento 2.0.5.

Whenever I have to try to login at  admin , then   enabled to log in with Username **amit** but My username: **Amit** . A is the uppercase letter. 
 I have  also tried different 3 magento2 instance and  something occur to  all the instances.

As  per as,my concern it should case sensitive

Thanks

Amit Bera

**Comment by rafaelstz** [comment]
with **amit** is ok? And **Amit** not?

**Comment by devamitbera** [comment]
My Username is **Amit**. I _enable login with_ both **Amit** and **amit** username and at my system username  **amit** does not exist. User should not log in  with **amit** and it  should  be case sensitive always.

**Comment by avoelkl** [comment]
I don't think this is a bug.
That's the same behavior as in Magento 1:

The setting in Magento 2 can be found here:
Stores > Configuration > Advanced > Admin > Security
Login is Case Sensitive: No (=default)

**Comment by devamitbera** [comment]
Ya, @avoelkl ,it is my mistake. I have  found that setting  as you mentioned ... Sorry for such foolish question

**Comment by davidalger** [comment]
@devamitbera No worries…there are no foolish questions! It's how one learns :)

Going ahead and marking this one as closed.
