### ISSUE TITLE
Remove some fields on checkout page.

### ISSUE THREAD

**Issue by mrkhoa99** [magento/magento2#4425]
**Steps to reproduce**

When customizing checkout page, we want to remove some fields (e.g company). There is a question on StackExchange: http://magento.stackexchange.com/questions/113992/how-to-remove-company-field-from-checkout-process-in-magento-2/

**Expected result**

Can remove these fields via layout or template.

Any guide how to remove these fields via layout or template?

**Comment by pboisvert** [comment]
Andrii--can you have the team validate this one?

**Comment by veloraven** [comment]
@mrkhoa99 thank you for your feedback.
Is this issue still actual?
If it is, please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
If it is not valid anymore, please close it.

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by nickmarx12345678** [comment]
I too am interested in how to do this, although my use case would be to remove the tooltip next to the phone number field

**Comment by payam427** [comment]
Hi @nickmarx12345678, 

I am interested too. 
Have you figured out how to remove the tooltip? (without hiding it through CSS)

**Comment by nickmarx12345678** [comment]
@payam427 I'll tell you what I can.

So basically magento makes this giant JSON blob that configures the checkout page via JS and ui components.
That JSON blob comes from defaults that are in code and also in the layout XML. To remove things, you basically need to find them in the json, and unset them before they are returned to the frontend. This can be done by making a plugin, and unsetting certain fields in the json array. Checkout the following link for more context. I'll add some code at the bottom for how I removed my tooltip.

http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_customize.html#remove-a-component

Why this is the core supported way of doing this, I do not understand, but it is.

```php
class CheckoutLayoutProcessorPlugin
{
    public function aroundProcess(\Magento\Checkout\Block\Checkout\LayoutProcessor $subject, \Closure $proceed, $jsLayout)
    {
        $ret = $proceed($jsLayout);
        unset($ret['components']['checkout']['children']['steps']['children']['billing-step']['children']['payment']['children']['payments-list']['children']['cryozonic_stripe-form']['children']['form-fields']['children']['telephone']['config']['tooltip']);
        unset($ret['components']['checkout']['children']['steps']['children']['billing-step']['children']['payment']['children']['payments-list']['children']['free-form']['children']['form-fields']['children']['telephone']['config']['tooltip']);
        return $ret;
    }
}
```

Hope that helps, and be aware there may be more tooltip things to unset, these are the ones that did it for me. To figure this array structure out I literally printed the entire thing and grep'd for telephone and/or tooltip.

**Comment by payam427** [comment]
@nickmarx12345678, Thanks for sharing it. 

However, I am still struggling to make it work. I need to remove it form shipping address, and this is the my Plugin, based on what you suggested:

```
class LayoutProcessorPlugin
{
    public function aroundProcess(\Magento\Checkout\Block\Checkout\LayoutProcessor $subject, \Closure $proceed, $jsLayout)
    {
        $ret = $proceed($jsLayout);
        unset($ret['components']['checkout']['children']['steps']['children']['shipping-step']['children']['shippingAddress']['children']['shipping-address-fieldset']['children']['telephone']['config']['tooltip']);
        return $ret;
    }
}
```

**Comment by nickmarx12345678** [comment]
@payam427 have you checked your plugin is in fact running on page load? also if you have any custom checkout_index_index.xml, I would look in those for a tooltip field and comment it out to be sure

**Comment by nickmarx12345678** [comment]
maybe try adding
`unset($ret['components']['checkout']['children']['steps']['children']['billing-step']['children']['payment']['children']['payments-list']['children']['free-form']['children']['form-fields']['children']['telephone']['config']['tooltip']);`

that did it for me at one point

**Comment by payam427** [comment]
@nickmarx12345678 

Your unset code seems to be valid for billing step, but I need to remove it from shipping one.  

> maybe try adding
> unset($ret['components']['checkout']['children']['steps']['children']['billing-step']['children']['payment']['children']['payments-list']['children']['free-form']['children']['form-fields']['children']['telephone']['config']['tooltip']);
> 
> that did it for me at one point

I confirm that there are no other checkout_index_index.xml with tooltip.

I am not quite sure but it seems like that the plugin is not applying at all. How can I check if the plugin is running or not?

Thanks,

**Comment by nickmarx12345678** [comment]
It's pretty crude but throw a `die("I EXECUTED")` in the "aroundProcess", if the page doesn't work, it's probably getting executed. Alternatively you could also throw in a logger (inject a \Psr\Log\LoggerInterface in the constructor to get access to it) or similar. basically just confirm those lines are in fact being executed

**Comment by payam427** [comment]
Awsome! It works perfectly. The plugin was not working because of a silly typo :)

Thanks @nickmarx12345678 :+1:

**Comment by nickmarx12345678** [comment]
@payam427  hey heyyyyy glad to hear it

**Comment by lfritsche** [comment]
Hi there,

I just upgraded from 2.0.12 to 2.1.5 and am facing the issue above in the checkout process.
Unfortunately I'm not familiar with writing plugins, and although I've read the devdocs to this topic I couldn't manage it on my own...

I've used this checkout_index_index.xml in 2.0.12:
```
<referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="steps" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="shipping-step" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="shippingAddress" xsi:type="array">
                                                    <item name="children" xsi:type="array">
                                                        <item name="shipping-address-fieldset" xsi:type="array">
                                                            <item name="children" xsi:type="array">
                                                                <item name="region_id" xsi:type="array">
                                                                    <item name="visible" xsi:type="boolean">false</item>
                                                                    <item name="validation" xsi:type="array">
                                                                        <item name="validate-select" xsi:type="string">false</item>
                                                                    </item>
                                                                </item>
                                                                <item name="region" xsi:type="array">
                                                                    <item name="visible" xsi:type="boolean">false</item>
                                                                    <item name="validation" xsi:type="array">
                                                                        <item name="validate-select" xsi:type="string">false</item>
                                                                    </item>
                                                                </item>
                                                                <item name="country_id" xsi:type="array">
                                                                    <item name="visible" xsi:type="boolean">false</item>
                                                                    <item name="validation" xsi:type="array">
                                                                        <item name="validate-select" xsi:type="string">false</item>
                                                                    </item>
                                                                </item>
                                                                <item name="telephone" xsi:type="array">
                                                                    <item name="validation" xsi:type="array">
                                                                        <item name="validate-select" xsi:type="string">false</item>
                                                                    </item>
                                                                </item>
                                                                <item name="prefix" xsi:type="array">
                                                                    <item name="visible" xsi:type="boolean">false</item>
                                                                </item>
                                                                <item name="care_of" xsi:type="array">
                                                                    <item name="visible" xsi:type="boolean">false</item>
                                                                </item>
                                                                <item name="postcode" xsi:type="array">
                                                                    <item name="sortOrder" xsi:type="string">70</item>
                                                                </item>
                                                            </item>
                                                        </item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>```

Could one of you provide me a sample module.zip with etc/di.xml & Plugin file?
I struggle especially on the di.xml file.

Thank you!

**Comment by ghost** [comment]
@lfritsche If you remove fields from this file, you'll get an error in checkout because Magento searches for the fields you removed. The only solution is make the plugin, but where is it supposed to be inserted?? in di.xml?? and how you determine the path to disable company and postcode??@nickmarx12345678
Indeed, is incredible how Magento turn the simplest tasks in the hardest.
I hope someone can help me with this.
