### ISSUE TITLE
SEO/HEAD - Meta title is null when breadcrumb section is removed via XML

### ISSUE THREAD

**Issue by mstumpf818** [magento/magento2#4427]
## Steps to reproduce
1. Install Magento 2.0.2
2. Add 
   `<referenceBlock name="breadcrumbs" remove="true"/>` to app/design/frontend/[VendorName]/[ThemeName]/Magento_Theme/layout/default.xml
## Expected result
1. Breadcrumb section should be removed from all pages
## Actual result
1. Meta title in <head> disappears with breadcrumb section.  Meta title prefix and suffix (set in the admin panel) still appear.
2. addConfigValues() title is null in vendor/magento/framework/View/Page/Title.php

**Comment by slackerzz** [comment]
this bug is still present in M2 2.1.2 (both CE & EE)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67614

**Comment by magento-engcom-team** [comment]
Hi @mstumpf818 
Looks like the issue is already fixed in `2.1.8` with the PR magento/magento2#9324.
Closing this ticket for now. Please reopen if issue persists.

**Comment by realchriswells** [comment]
Bit of an old ticket, but I'm having the same thing happen in 2.3.4.
