### ISSUE TITLE
Flat Products issue in 2.0.5

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4429]
I have Catalog rules applied to different user groups, and when "Use Flat Catalog Product" is on, the Catalog rules do not get applied, prices do not change for each individual user. With the "Use Flat Catalog Product" OFF everything works fine.

So, I just have "Use Flat Catalog Category" ON and it works fine.

**Comment by choukalos** [comment]
Did you get a notification to flush the cache/did you flush the cache after changing the settings?

**Comment by devdesco-ceo** [comment]
Everything is flushed.

**Comment by andimov** [comment]
@devdesco-ceo 
Sorry for late reply!
Is this issue still actual for you?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
