### ISSUE TITLE
New Review via Admin bug

### ISSUE THREAD

**Issue by alex-parra** [magento/magento2#4434]
## Steps to reproduce
1. On Admin, go to Marketing › User Content › Reviews
2. Click "New Review" button
## Expected result
1. Review form
## Actual result
1. Review form shows for 1 or 2 seconds and is replaced by an unpaginated list of ALL products.

**Comment by maksek** [comment]
@alex-parra, can you provide version where you are experiencing the issue. Also if there are additional extensions installed?

**Comment by alex-parra** [comment]
Hi @maksek 
I've just made a clean install and was about to check this issue again.
It's still happening...
- Magento 2.0.5
- No additional modules

**Comment by maksek** [comment]
@alex-parra, thank you. Our team will try to reproduce and will back with results

**Comment by alex-parra** [comment]
Hi @maksek 
I went to check this again, and I found out that I did not understand the screen.
The product list I say appears, makes sense, it's so we can choose the product for the new review.
Did not get it... Maybe a small phrase at the top of the list would make it clear.
After clicking a product on the list, the New Review Form shows up, as expected.

Pagination does not seem to be implemented on this product selection grid.
At least for me, the list shows all 350 products. No performance issues with this amount but for several thousands may cause issues...

Anyway, please close this issue.

**Comment by choukalos** [comment]
Converting to a performance bug; internal tracking - MAGETWO-53547

**Comment by KrystynaKabannyk** [comment]
Hello @alex-parra, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
