### ISSUE TITLE
The cron setting `use_separate_process` is not actually parallelized

### ISSUE THREAD

**Issue by samtay** [magento/magento2#4435]
I can see from the wording in [comments](https://github.com/magento/magento2/blob/f10c7c83a93628122a929949b97e08faa13ce652/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L28-L32) and variable naming that the expected [ShellInterface virtual type](https://github.com/magento/magento2/blob/f10c7c83a93628122a929949b97e08faa13ce652/app/code/Magento/Cron/etc/di.xml#L22-L31) passed to the `\Magento\Cron\Observer\ProcessCronQueueObserver` is supposed to execute commands in the background as a parallel process, so as to not block the current script execution.

I was trying to figure out why this wasn't happening for me when I came across a random [SO answer](http://stackoverflow.com/a/46008) explaining that later versions of php binary conflict with bash in a way that prevents `exec` or `system` commands to run background processes.

Instead, you need to use the `proc_close` and `proc_open` commands.

This isn't a huge deal, but you should fix this in the case that you ever add daemon process support and expect it to work using the methodology from the `Magento_Cron` module. I only found this out because I am currently writing bin/magento commands to spawn daemon consumers for a rabbitMQ integration. I will have to write a new ShellInterface implementation to support actual background processes.

**Comment by hshar7** [comment]
Thanks for reporting this. Internal ticket MAGETWO-52621 created to investigate.

**Comment by cspruiell** [comment]
This issue has been fixed and delivered to the develop branch.
