### ISSUE TITLE
Creating Online Refund- Feature request

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#4436]
Feature Request

Currently there is no way to create credit memo to refund the amount online via API. can this ability to refund a transaction online for while creating credit memo be provided? Any many people want to control this from ERP connected to eCommerce websites.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Creating-Online-Refund-Feature-request/idi-p/44732).
