### ISSUE TITLE
Custom options (admin) will not load using Firefox

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#4437]
## Preconditions
1. Install Magento 2.0.4

## Steps to reproduce
1. Use Firefox browser to access Admin.
2. Go to Admin > Products > Catalog > (Select any product) > Advanced Settings > Custom Options
3. Click "Import Options" or "Add New Option"
## Expected result
1. Custom options "New Option" box will load for you to select option title and input type.
## Actual result
1. Nothing happens, box will not load.
2. If options are assigned to product using Chrome or IE browser and then you try to access "Admin > Products > Catalog > (Select any product) > Advanced Settings > Custom Options" to edit those options, it will appear in Admin as no options are assigned but options are really there and available to view in other browsers.
3. Tested using Windows 7 (64-bit) OS using Firefox 45 & 46.0.1

![options](https://cloud.githubusercontent.com/assets/18691038/15128758/beeb2e82-160b-11e6-8e38-36ee113e13a5.jpg)

**Comment by magento-engcom-team** [comment]
@stevekem, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
