### ISSUE TITLE
email inlinecss by extension module does not work

### ISSUE THREAD

**Issue by kevinjavitz** [magento/magento2#4438]
## Steps to reproduce
1. Install Magento 
2. Make a custom module with a custom email template. Use markup like this: {{inlinecss file="Company_ModuleName::css/custom-inline.css"}}
## Expected result
1. Should apply the custom inline css, this is possible according to vendor/magento/module-email/Model/Template/Filter.php:814 Usage: {{inlinecss file="Magento_Sales::css/filename.css"}} - Load file from module directory or module directory in theme
## Actual result
1. Gives error about compilation source because it does not look in the module directory, instead it still tries to get it from the theme. Compilation from source: 
   frontend/Magento/luma/en_US/Company_ModuleName/css/custom-inline.less Cannot read contents from file

**Comment by palamar** [comment]
@kjavitz 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by pratikmage** [comment]
i have same issue when i add custom css file in email template.   [http://magento.stackexchange.com/questions/134160/magento-2-add-css-file-in-custom-module-email-template]

**Comment by LiamFielding** [comment]
I have the same issue.
