### ISSUE TITLE
Wishlist My Account Dashboard wishlist sidebar do not show price just after logged in 

### ISSUE THREAD

**Issue by gayankt** [magento/magento2#4439]
Steps to reproduce
01. Add some products to wishlist (at the time you add to wishlist the account dashboard wish list slider get updated with price)
02. Now log out and clear browser cache also.
03. Then re log in to my account.
In dashboard wishlist items do not show the price values.

![wishlist-no-price](https://cloud.githubusercontent.com/assets/654973/15135655/7542a720-1696-11e6-8357-0e8a0888e503.png)

**Comment by duhon** [comment]
I can't reproduce bug on current version. Which version are you using?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by i-com-davidwalsh** [comment]
I'm also getting the same issue 

Magento version 2.1 using Luma theme

**Steps**
1. Add a product to your wish list
2. Create account

The product appears on the wishlist page but its does not synchronize the mage-cache-storage to display in the info in the sidebar wishlist.  

On top of this, if you then add the product to your cart from the wishlist this also doesn't update the mage-cache-storage, and doesn't appear in the basket.  

However adding a product by going through the catalog does update local storage and then displays the wishlist.  Subsequent additions to wishlist then also update as expected after the local cache storage has been sync'd

**Comment by duhon** [comment]
Hello @davidwalsh 

Please create a separate ticket for other issues and provide detailed steps
