### ISSUE TITLE
Backend image Preview icon button does not show

### ISSUE THREAD

**Issue by xiangkundavis** [magento/magento2#4441]
1. I create a new customer attribute using backend UI and this attribute is Image type
2. at the backend customer edit page, I upload a image for this attribute and save
3. There is no preview image for this attribute

**Comment by xiangkundavis** [comment]
![1](https://cloud.githubusercontent.com/assets/998396/15140311/142fd2be-16cd-11e6-88e7-89951ee66b82.png)
![2](https://cloud.githubusercontent.com/assets/998396/15140312/142fe01a-16cd-11e6-97e7-ebcac3d0de91.png)

**Comment by xiangkundavis** [comment]
![3](https://cloud.githubusercontent.com/assets/998396/15140487/e8baa752-16cd-11e6-8fd1-6b7f2de7ce20.png)

**Comment by slavvka** [comment]
@davissuperman, thank you for reporting it. There's an internal ticket MAGETWO-42954

**Comment by xiangkundavis** [comment]
HI, What is  the url of MAGETWO-42954, I try to check this ticket but can not find it.

**Comment by slavvka** [comment]
As I mentioned it is an internal ticket. Once it is fixed this issue will be closed

**Comment by xiangkundavis** [comment]
Got it.  May I ask when this issue will be fixed, because my project need this feature ASAP. Or is there a temporary quick fix?
Many Thanks!

**Comment by ilol** [comment]
Hope the fix will be delivered as a part of 2.1 release

**Comment by xiangkundavis** [comment]
is there a temporary quick fix?

**Comment by xiangkundavis** [comment]
Hi, I do not see any changes about this issue at the release note http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC3EE.html
May I confirm this issue will be fixed at 2.1 release?

**Comment by ilol** [comment]
Hey, @davissuperman. Unfortunately, we have faced with additional efforts to fix this issue and fix will not be released in 2.1

**Comment by slavvka** [comment]
@davissuperman, the issue has been fixed. Please see 0be746b, 6258496, 3fb5616, c43fc5e and 6fc4dd3.
