### ISSUE TITLE
Special Price From date cannot be cleared.

### ISSUE THREAD

**Issue by gayankt** [magento/magento2#4443]
## Steps to reproduce
1. Add Special Price to a product with a specific from date and save
2. Now delete the special price from date, and save
3. it will now set the current date as from date, you cannot clear it at all
   ![specialprice-fromdate](https://cloud.githubusercontent.com/assets/654973/15135428/8d2251f4-1693-11e6-9554-23d466da83a5.png)
## Expected result

1.If from date removed it should be cleared

**Comment by antboiko** [comment]
Hi @gayankt , could you please describe the need of setting this field as empty?

Thanks,
Anton.

**Comment by katmoon** [comment]
The issue is reproducible on develop branch

**Comment by miakusha** [comment]
Hi @gayankt, thank you for your report.
We created internal issue MAGETWO-58761 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@gayankt, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
