### ISSUE TITLE
Multiple Success Messages appear in some pages

### ISSUE THREAD

**Issue by gayankt** [magento/magento2#4444]
Sometimes the success message not appear but later in some other page it appears as multiple success messages

May be knockut js getting delayed and the messages we added to the queue and appears at onces in some other page. 

![multiple-success](https://cloud.githubusercontent.com/assets/654973/15135512/ac1a5858-1694-11e6-9a14-a8e19400c97d.png)

**Comment by zaranapatel** [comment]
Have you got any solution for this issue?

**Comment by maksek** [comment]
@gayankt can you provide steps for reproduce? Also do you use custom developed code or it is reproducible on vanilla magento 2 code, which version?

**Comment by gayankt** [comment]
[messages2.mkv.zip](https://github.com/magento/magento2/files/269873/messages2.mkv.zip)

**Comment by gayankt** [comment]
2.0.4 / 2.0.5

**Comment by piotrekkaminski** [comment]
The fix has been delivered to mainline. See commits 541ec80, 55a6e51, b4d3739, eec31f6, af2a832, d97ebe5, 3120b1e and 66e6ad6.
