### ISSUE TITLE
Bundle Products - while Bundle Item option has only one product added the price calculation fails

### ISSUE THREAD

**Issue by creatuitydevelopers** [magento/magento2#4446]
## Hello All,

We have encountered an error related to bundle product pages - if bundle product has Bundle Items with only one product added to each option the price is not updated. 
## Steps to reproduce
1. Go to Magento admin panel.
2. Crate a bundle product with various prices for few (ex. 3) different products options and only one required option.
3. Go to newly created product on frontend.
4. Click on "Customize and add to cart".
5. You should see the price for your product below "Add to Cart" button.
6. The price is not updated
7. If you will add second product to each option the price calculation will work properly.
## Expected result
1. Bundle product's price will be calculated correctly even if only one product will be added to "Option".
## Actual result
1. Bundle product's price is not being calculated correctly if there is only one product added to "Option"

Screenshot:

![bundle](https://cloud.githubusercontent.com/assets/1653168/15142418/2ab85aba-16a5-11e6-855a-af53214e4775.png)

**Comment by pboisvert** [comment]
@antboiko can you have the team verify this issue and file a ticket?

**Comment by heyitsroberthe** [comment]
I will try to reproduce this on EE.

**Comment by heyitsroberthe** [comment]
Update:
I believe the problem is caused when the 'User Defined' checkbox is selected for each of the different product options. This allows the user to choose a custom quantity instead of the default quantity. However, when user changes the quantity field, the price is not recomputed. I will open an internal ticket for this.

**Comment by quynhvv** [comment]
@guys,
I get this issues too in my context: Magento 2 CE 2.0.7
And the changing of qty for each option only applied when you have 2+ products and after you have at least one change for each option (after click to change option at least one).
Regards,
quynhvv.

**Comment by rganin** [comment]
Fixed in 4f807b1.

**Comment by Ctucker9233** [comment]
@magento-engcom-team This fix is not in 2.1.10. What release might it be in?
