### ISSUE TITLE
Login link appears for logged customer when we switch from https page to http link

### ISSUE THREAD

**Issue by satishashilwar** [magento/magento2#4448]
## Steps to reproduce
1. Set admin configurations for secure URL (https).
2. Browser home page (http) page.
3. Click on login link and logged in with customer email id & password.
4. Land on myaccount pages ( any https page ) 
5. From https page click on logo ( home page ) link.
## Expected result

In header section my account link will be populate in dropdown 
## Actual result

1.Sign In link appears for logged user.

**Comment by sevos1984** [comment]
Can't reproduce on latest develop. Try update your code base please
