### ISSUE TITLE
knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.

### ISSUE THREAD

**Issue by dennesabing** [magento/magento2#4449]
## Steps to reproduce
1. Go to Admin and launch Catalog or Catalog Category or maybe Customers
2. When page is loaded, a loader appear and just keep on loading, and in the console tab, an error is:
   uncaught Error: You cannot apply bindings multiple times to the same element.

knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.

![magentoknockoutissue](https://cloud.githubusercontent.com/assets/1753139/15145064/06910bc8-16e6-11e6-9307-b0acf9fcd707.JPG)

**Comment by maksek** [comment]
@dennesabing, did you try to clean browser cache and reload?

**Comment by dennesabing** [comment]
Hi, It has something to do with the server hosting since I am using an IP address while doing an installation. something like ModSecurity.
Thank you very much.

**Comment by anton-huz** [comment]
Hi @dennesabing ,
If you found issue root it would be great if you share here few notes.

**Comment by ferluk** [comment]
it happend too on frontend page
fresh installation 2.1.0-rc1 with no sample data

**Comment by cmuench** [comment]
I have the same issue in Admin area on Product-List and Order-List.
-> EE 2.1.0-rc1

I can reproduce the issue in Google Chrome 49.
In a Firefox 41.0.2 i have no problems.

**Comment by peec** [comment]
I encountered this problem as well. Magento 2.1-RC3. Things where not clickable many places, js basically screwed on frontend.

I used http://192.168.1.200/magento2/web as the path to my magento.

Fixed it by adding a alias in the hosts file 

```
192.168.1.200 magento2.dev
```

... and then visiting:

http://magento2.dev/magento2/web/

fixed it. No more bindings errors (and probably other things fixed also).

**Comment by mhauri** [comment]
Having the same issue after upgrading from 2.0.7 to 2.1.0, any news?

**Comment by attheCube** [comment]
Same Error after Upgrade from CE 2.0.7 to CE 2.1.0 Admin area. (Problem in Google Chrome 51; OK in FF 47)
All pages where grids are loaded via Ajax seem to be affected.

**Comment by rou9e** [comment]
Same thing over here : 
CE Edition : 2.0.7 -> 2.1.0 no sample data.
Backend grids doesn't work anymore.

Anyone figured out ?

**Comment by d-gerken** [comment]
Same here.
EE 2.0.7 to EE 2.1.0 

Backend is working fine, but frontend shows the error.

**Comment by mhauri** [comment]
@d-gerken did you try to load the catalog products, that's where I have it too in the backend

**Comment by jreinke** [comment]
Same here after upgrade 2.0.7 => 2.1.0 (sample data installed).

EDIT: clearing browser cache fixed the problem for me

**Comment by rou9e** [comment]
Mmh, if I test the exact same backend pages from a private instance of my browser (FF 47.0.1), the problem disappears. So I just cleared my whole browser data (cache, session, cookies, etc), then logged in again, and all the grids are working fine...

Problem solved for me, but some clues would be nice. In my case, the magento2 is a dev environnement, so that's fine but I would not want to ask each of my clients to purge their browser..

**Comment by amanuni** [comment]
Hi Guys,

Getting same issue i have purged my browser cache checked in private browser also but getting same above error.

**Comment by kfaer** [comment]
same issue also in chrome and i've noticed that the welcome msg is not showing also minicart is always empty. v2.1.0

**Comment by anton-huz** [comment]
Hi guys,
We created an issue for investigation. MAGETWO-55348
We are going to retest and review different combinations with upgrade.

Please stay in touch.

**Comment by amanuni** [comment]
Hi,

Thanks for update i am getting same same issue with magento admin product, order and customer grids also please take a look also.

![image](https://cloud.githubusercontent.com/assets/2352740/16807718/5c4871a4-48ce-11e6-8e91-cb24361d59c9.png)

**Comment by adnan-jamil** [comment]
i changed base url from Stores->Configuration->General->Web https to http. it is working fine.

**Comment by kfaer** [comment]
@adnan-jamil , no relation , even my site running on http only and issue remain, 2.1.0 is not stable application and we should not trust to use it to sell our products.

**Comment by JerVoo** [comment]
I think this issue really needs a status update. Lots of people are currently waiting for this issue to be resolved, but there is no status whatsoever.

**Comment by grasdaggel** [comment]
Can confirm that this Bug appears on our installation, too. We also are using a Dev Env.

**Comment by PRAKASHSIVASANKAR** [comment]
I Fix this issue,

just add the below code your .htaccess file

`<IfModule pagespeed_module> ModPagespeed off </IfModule>`

**Comment by JerVoo** [comment]
@PRAKASHSIVASANKAR
That would be a fix if the problem only existed on servers using Apache, however the problem also arises on nginx.

@guz-anton
Any progress on the investigation or this still broken in Magento 2.1.1?

**Comment by daanggc** [comment]
@PRAKASHSIVASANKAR
Works for me, thanks!

```
<IfModule pagespeed_module>
    ModPagespeed off
</IfModule>
```

@JerVoo
I have it on a 2.1.1 installation, so it is still present.

The solution from @PRAKASHSIVASANKAR is not a permanent solution, so this really needs to be looked at!

**Comment by anton-huz** [comment]
Does anybody investigate what does `ModPagespeed on` do so special, that it breaks Magento?

The solution of @PRAKASHSIVASANKAR looks like local medicine. Why do you need to switch off module that does not installed by default? Why it should break Magento installation?

For example PageSpeed [can eliminate html comments](https://developers.google.com/speed/pagespeed/module/filter-comment-remove). For now, it can cause breakages, because Magento JS app relies on HTML comments. Related issue is already created #2697.

So general notice is if you get issues with RequireJS or Knockout in browser console you should:
- Regenerate static assets (in production mode `rm -rf pub/static/* && setup:static-content:deploy`, in default/developer modes just empty static folder  `rm -rf pub/static/*`).
- Clean browser cache (In Google Chrome -> F12 -> Application -> Clear storage)

If you still faced with the same issue, please, add to your report: Magento's version, way of install/upgrade, environment configuration (php, apache, mysql with versions and additional modules), browser version. Thanks.

**Comment by wingsoul** [comment]
Same problem. I have try those method you guys mentioned but still faced with the same issue.

my environment:
php:  7.0.10
nginx:  1:1.10
OS: Amazon linux(feels like centos 6.8)
chrome: 53.0.2785.143

Thanks

**Comment by anton-huz** [comment]
@wingsoul 
My current environment: 
PHP 7.0.10
nginx 1.10.0
Ubuntu 16.04.1 LTS
Latest Chrome/Firefox/MS Edge.

I don't faced with _same problem_. But I really want to help you. So could you so kind and describe: 
- What version of Magento?
- How did you install it? Was it an update? How you do an update?
- Was your browser in private mode?
- What is exactly the problem you faced with?

**Comment by wingsoul** [comment]
my magento2 is 2.1.0 upgraded from 2.0.8
Using private mode, it seems no errors.
However, i have the following error message when using normal mode
`knockout.js:3012 Uncaught ReferenceError: Unable to process binding "css: function (){return { empty:!!getCartParam('summary_count') == false} }"
Message: getCartParam is not defined`

**Comment by amooabeebadesina** [comment]
Upon installing an external theme on magento 2.0.11, I had this issue. what can I do to it please
![mag](https://cloud.githubusercontent.com/assets/19835966/22656516/e2abdaec-ec93-11e6-93b8-4d440bbdb60f.PNG)

**Comment by dmitrii-fediuk** [comment]
[How to fix the «**You cannot apply bindings multiple times to the same element**» issue](https://mage2.pro/t/topic/3505).

**Comment by magento-engcom-team** [comment]
@dennesabing, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@dennesabing, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@dennesabing, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Jeeva-Rathinam** [comment]
Clear cache solve the issue....
