### ISSUE TITLE
Save dates in UTC (like in Magento 1)

### ISSUE THREAD

**Issue by aleron75** [magento/magento2#4452]
Hi,
this is not something which doesn't work but something that doesn't work as expected, so feel free to take it more as a suggestion than as a bug.

As stated in the title, I expected dates saved in UTC just like in Magento 1 but it doesn't seem to work this way in Magento 2.

What's more, the `\Magento\Eav\Model\Entity\Attribute\Backend\Time\Created` and `\Magento\Eav\Model\Entity\Attribute\Backend\Time\Updated` attribute backend models don't seem to have the same logic implemented (even if I don't think that any default attribute use them at date).

You can read some considerations and suggestions here: http://magento.stackexchange.com/questions/114706/magento-2-best-practice-to-get-current-date

Thank you

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Save-dates-in-UTC-like-in-Magento-1/idi-p/48460).
