### ISSUE TITLE
Magento 2.0.4 Warning: getimagesize - Product\Image.php on line 949

### ISSUE THREAD

**Issue by MattDeanCS** [magento/magento2#4453]
I can see this issue has arisen before and is down as fixed but I'm getting this issue on 2.0.4 on product and category pages. Cache is off. Thanks

**Comment by maksek** [comment]
@MattDeanCS, there is not enough information. Log must be more extended, warning on call getimagesize must follow with trace logs. Please provide full log around the call.

**Comment by MattDeanCS** [comment]
Full error message is;

Warning: getimagesize(E:/dev/www/magento2/): failed to open stream: No such file or directory in E:\dev\www\magento2\app\code\Magento\Catalog\Model\Product\Image.php on line 949
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'getimagesize(E:...', 'E:\dev\www\mage...', 949, Array)
#1 E:\dev\www\magento2\app\code\Magento\Catalog\Model\Product\Image.php(949): getimagesize('E:/dev/www/mage...')
#2 E:\dev\www\magento2\app\code\Magento\Catalog\Helper\Image.php(541): Magento\Catalog\Model\Product\Image->getResizedImageInfo()
#3 E:\dev\www\magento2\app\code\Magento\Catalog\Block\Product\ImageBuilder.php(132): Magento\Catalog\Helper\Image->getResizedImageInfo()
#4 E:\dev\www\magento2\app\code\Magento\Catalog\Block\Product\AbstractProduct.php(507): Magento\Catalog\Block\Product\ImageBuilder->create()
#5 [internal function]: Magento\Catalog\Block\Product\AbstractProduct->getImage(Object(Magento\Catalog\Model\Product\Interceptor), 'product_base_im...', Array)
#6 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Interceptor.php(144): call_user_func_array(Array, Array)
#7 E:\dev\www\magento2\var\generation\Magento\Catalog\Block\Product\View\Interceptor.php(455): Magento\Catalog\Block\Product\View\Interceptor->___callPlugins('getImage', Array, Array)
#8 E:\dev\www\magento2\app\code\Magento\Catalog\view\frontend\templates\product\view\opengraph\general.phtml(14): Magento\Catalog\Block\Product\View\Interceptor->getImage(Object(Magento\Catalog\Model\Product\Interceptor), 'product_base_im...')
#9 E:\dev\www\magento2\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('E:\dev\www\mage...')
#10 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), 'E:/dev/www/mage...', Array)
#11 E:\dev\www\magento2\var\generation\Magento\Catalog\Block\Product\View\Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('E:/dev/www/mage...')
#12 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('E:/dev/www/mage...')
#13 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#14 E:\dev\www\magento2\var\generation\Magento\Catalog\Block\Product\View\Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#16 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('opengraph.gener...')
#17 E:\dev\www\magento2\var\generation\Foundation\ContainerExtend\View\LayoutUpdate\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('opengraph.gener...')
#18 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Layout.php(472): Foundation\ContainerExtend\View\LayoutUpdate\Interceptor->renderNonCachedElement('opengraph.gener...')
#19 E:\dev\www\magento2\var\generation\Foundation\ContainerExtend\View\LayoutUpdate\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('opengraph.gener...', true)
#20 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(501): Foundation\ContainerExtend\View\LayoutUpdate\Interceptor->renderElement('opengraph.gener...', true)
#21 E:\dev\www\magento2\app\code\Magento\Theme\view\frontend\templates\html\container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#22 E:\dev\www\magento2\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('E:\dev\www\mage...')
#23 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), 'E:/dev/www/mage...', Array)
#24 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('E:/dev/www/mage...')
#25 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#26 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Result\Page.php(234): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 E:\dev\www\magento2\lib\internal\Magento\Framework\View\Result\Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#28 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#29 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#30 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#31 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#32 E:\dev\www\magento2\app\code\Magento\PageCache\Model\Controller\Result\VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#33 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#34 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(68):a call_user_func_array(Array, Array)
#35 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#36 E:\dev\www\magento2\app\code\Magento\PageCache\Model\Controller\Result\BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#37 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#38 E:\dev\www\magento2\lib\internal\Magento\Framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#39 E:\dev\www\magento2\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#40 E:\dev\www\magento2\lib\internal\Magento\Framework\App\Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#41 E:\dev\www\magento2\lib\internal\Magento\Framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#42 E:\dev\www\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#43 {main}

Thanks

**Comment by rganin** [comment]
The product image was not uploaded. Verify that httpd has access rights to uploads directory of your instance and the filesize limit in server configuration allows images of size you are uploading.

**Comment by MattDeanCS** [comment]
@rganin 
The image is showing in the backend and is at /pub/media/catalog/product/ 
Is it different for the frontend?
Thanks
