### ISSUE TITLE
No theme updates working

### ISSUE THREAD

**Issue by aaronsturm** [magento/magento2#4458]
I created a new theme based on the blank theme. It loads correctly with no issues. I've tried a myriad of examples to try and change the theme (to learn), but nothing is having any effect.

To keep it simple, I used [http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-manage.html#layout_markup_css) and added a fake named script to make it easy to search and see errors in the Chrome console. But no script tag is added.

Here is a Gist of my files, with dashes replacing the / for the folder structure since Gist doesn't allow slashes.
https://gist.github.com/aaronsturm/4e9cb397a8277b716b8e5c78db057f9b

For my setup, I'm using a local Docker image and only mounting the theme directory in the container. I did this because it increases the speed dramatically.

Let me know if I missed some detail that you need to know. After several hours, I could really use a second (or more) pair of eyes. Thanks!

**Comment by palamar** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by aaronsturm** [comment]
For future reference, in case anyone else has the same issue, I had to delete all of the rows in the `theme`table that weren't default Magento themes. Meaning, I left `Magento/blank`, `Magento/luma`, and `Magento/backend` and deleted the others. Once I did that, it started working as expected again.
