### ISSUE TITLE
Could not install new components

### ISSUE THREAD

**Issue by bhavinrshah** [magento/magento2#4459]
## Steps to reproduce
1. Login into admin area.
2. Select System -> Web Setup Wizard
3. Select Component Manager
4. Enable new component
5. Click on Readiness Check
6. It gives PHP version and extension issue.

I have checked PHP version and extension as per documentation are enabled.
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by mazhalai** [comment]
@bhavinrshah do you have the required [crons](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html) setup?
And why is expected result related to shopping cart?

**Comment by mazhalai** [comment]
@bhavinrshah closing as non-responsive.
