### ISSUE TITLE
rounding different in order to original quote calculation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#446]
When retrieving calculatedTaxes here

https://github.com/magento/magento2/blob/master/app/code/Magento/Tax/Helper/Data.php#L897

```
$taxClassAmount[$taxClassId]['tax_amount']      += $price * $percent / 100;
```

the amounts are not rounded leading to different results to the original quote calculation.

Magento should be able to reconstruct the complete taxation on the order and produce the same results as the original quote (irrespective of any setting changes).

**Comment by seansan** [comment]
Was this bug also fixed in m1? or is there a solution somewhere?
