### ISSUE TITLE
Custom Options 'Required' Checkbox issue

### ISSUE THREAD

**Issue by wittness87** [magento/magento2#4462]
## Steps to reproduce
1. Install Magento 2.0.4
2. Add a custom option attribute with dropdown box.
## Expected result
1. Product page shows custom option attribute with dropdown options (NOT REQUIRED).
## Actual result
1. Custom options are required for selection.
2. Upon removing the required checkbox in custom options and saving, the checkbox is still ticked and the custom option still required for selection on the product page.

**Comment by pboisvert** [comment]
Anton--can you check this one with the team if expected or not and open an issue if not expected.

**Comment by antboiko** [comment]
Hi @wittness87 , thanks for your inquiry. We've created internal ticket MAGETWO-52971 to investigate this issue.

Best,
Anton.

**Comment by vincentwinkel** [comment]
Hi, still the same problem on 2.0.9 CE.

**Comment by magento-engcom-team** [comment]
@wittness87, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by vincentwinkel** [comment]
"We were not able to reproduce this issue. We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9"

Are you kidding ? This ticket is tagged for 2.0, we don't care about 2.1, 2.2 and 2.3.
Stop to close tickets all the time and assume the platform you created.
