### ISSUE TITLE
Theme languages will be ignored after installation of language packages

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4463]
## Steps to reproduce
1. Personal theme translations in file ch_DE at app/design/frontend/name/name/i18n (works before installing the language package)
2. Installing language package at app/i18n/name/ch_DE
## Expected result
1. Personal theme translation should overwrite language package
2. Language package should show up
## Actual result
1. **Personal theme translations are ignored**
2. Language package show up well

**Comment by hshar7** [comment]
Hi @flipflap I just tried this out by installing community language pack splendidinternet/mage2-locale-de-de and inserting a phrase into my theme's etc/de_DE.csv file. The theme translation is not ignored, instead it is lower priority than the language pack. If I remove the phrase from the language pack, the translation uses the theme's phrase.

**Comment by hshar7** [comment]
This is not a bug as you can see in lib/internal/Magento/Framework/Translate.php:180 we are defining the priority of these translations.

**Comment by flipflap** [comment]
Hi hshar7
Ok thanks!
The path to the translate.php seems wrong. There is no Magento folder in my /lib/internal/

**Comment by hshar7** [comment]
Then that's probably because you have a composer installation. Look in the github or under vendor/ directory.

**Comment by schmengler** [comment]
This issue has been resolved in #7142. The priorities are now defined in a reasonable way.
