### ISSUE TITLE
Pager variable for catalog - question

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#4464]
## Steps to reproduce
1. Install Magento 2.0.5 with sample data.
2. In the class Magento\Theme\Block\Html\Pager change $_pageVarName to 'z'.
   (analog of using setPageVarName() public method)
3. Go to the category .../women-custom/tops-women.html and click page 2 in the toolbar. 
   URL is .../women-custom/tops-women.html?z=2 now and you can see in toolbar that page 2 is active.
## Expected result
1. You see list of products are different than page 1.
## Actual result
1. The list of products doesn't differ from page 1.
## Reason
1. For catalog toolbar you use duplicative constant, which doesn't interact with the theme module:
   Magento\Catalog\Model\Product\ProductList 
   const PAGE_PARM_NAME = 'p';

Is It  any sense to use two parallel methods (variable & constant) for one goal - change var name on the category pages?

**Comment by pboisvert** [comment]
Anton--can you have the team look into this issue and take next steps as appropriate?

**Comment by antboiko** [comment]
Hi @sergei-sss , thanks for reporting this issue. I've created internal ticket MAGETWO-52797 to investigate it.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
We've created internal ticket(s) MAGETWO-52797 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @sergei-sss

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@sergei-sss thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
