### ISSUE TITLE
Magento 2: Want to have custom options of simple product on configurable product detail page on change of options

### ISSUE THREAD

**Issue by priyankagarg8** [magento/magento2#4466]
Magento 2: Want to have custom options of simple product on configurable product detail page on change of options

**Comment by antboiko** [comment]
Hi @priyankagarg8 , thanks for your inquiry. Could you please provide detailed steps to reproduce the issue you have? Some screenshots will be helpful as well.

Thanks,
Anton.

**Comment by katmoon** [comment]
@priyankagarg8 I cannot reproduce the issue on develop branch.

Could you provide more info about your environment and any non-default settings that you used?

Does it happen 
- only  for a specific configurable product
- for all configurable products
- for all products including simple products?

Thanks,
Kateryna.

**Comment by priyankagarg8** [comment]
Thanks for the response guys ...)

This is not issue.This is what I want to implement in magento2.

**Magento 2: Want to have custom options of simple product on configurable product detail page on change of options**

If any suggestion,how can i do it?

Much appreciated..:)

**Comment by pboisvert** [comment]
@priyankagarg8  Github is intended for reporting issues and submitting pull requests. If you have n issue please provide detailed steps to reproduce what is wrong (the bug). Your question seems to be a "how do I" question better suited to StackExchange.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
