### ISSUE TITLE
Varien_Data_Collection does not support Pagination

### ISSUE THREAD

**Issue by tkdb** [magento/magento2#447]
The class `Varien_Data_Collection` implements pagination methods like `setPageSize` and `setCurPage` but the implementation of IteratorAggregate does not reflect when pagination has been enabled. It always returns an ArrayIterator over all items, not reflecting the pagination (no provider for pagination).

See as well: http://stackoverflow.com/questions/20197518/varien-data-collection-pagination-not-working

This (https://gist.github.com/tkdb/de651ce0dbc4a2682b39) is untested if extending classes expect getIterator to not do so, which might be a reason why this non-abstract base-class contains such non-working boilerplate pagination code.

Reproduced with code of 1.5.0.x (the other bug-tracker seems broken, I'm unable to report), the code/problem remains the same in master:

https://github.com/magento/magento2/blob/master/lib/Magento/Data/Collection.php#L772

**Comment by ahofstetter** [comment]
class Pageable_Varien_Data_Collection extends Varien_Data_Collection
{
    /**
     * Load data
     *
     * @param   bool $printQuery
     * @param   bool $logQuery
     *
     * @return  Pageable_Varien_Data_Collection
     */
    public function load($printQuery = false, $logQuery = false)
    {
        if ($this->isLoaded()) {
            return $this;
        }
        $this->_renderLimit();
        $this->_setIsLoaded();
        return $this;
    }
    /**
     * @return  Pageable_Varien_Data_Collection
     */
    protected function _renderLimit()
    {
        if ($this->_pageSize) {
            $currentPage = $this->getCurPage();
            $pageSize = $this->_pageSize;
            $firstItem = (($currentPage - 1) * $pageSize + 1);
            $lastItem = $firstItem + $pageSize;
            $iterator = 1;
            foreach ($this->getItems() as $key => $item) {
                $pos = $iterator;
                $iterator++;
                if ($pos >= $firstItem && $pos <= $lastItem) {
                    continue;
                }
                $this->removeItemByKey($key);
            }
        }
        return $this;
    }
    /**
     * Retrieve collection all items count
     *
     * @return int
     */
    public function getSize()
    {
        if (is_null($this->_totalRecords)) {
            $this->_totalRecords = count($this->getItems());
        }
        return intval($this->_totalRecords);
    }
    /**
     * Retrieve collection items
     *
     * @return array
     */
    public function getItems()
    {
        return $this->_items;
    }
}
