### ISSUE TITLE
Unable to update links in CatalogImportExport

### ISSUE THREAD

**Issue by mirkocesaro** [magento/magento2#4471]
Hi,
I tried to import a products csv file but I received a "foreign key constraint fails" during the execution of **_saveLinks** method of _Magento\CatalogImportExport\Model\Import\Product_.

The constraint is on _catalog_product_link_attribute_int_ table named CAT_PRD_LNK_ATTR_INT_LNK_ID_CAT_PRD_LNK_LNK_ID. 

When **insertOnDuplicate** method updates the primary key in catalog_product_link table, the foreign key will be missing raising the error.

I saw this [#1728](https://github.com/magento/magento2/issues/1728) but I suppose for this and all kind of relations like this we need to use ON UPDATE CASCADE to fix they.
## Steps to reproduce
1. Install Magento 2 with sample data.
2. Edit product with id 1
3. Set the position inside some up-sells products 
4. Save the product (so will be created some rows inside catalog_product_link_attribute_int)
5. Export a csv with the edited product (sku 24-MB01)
6. Try to import the csv 
## Expected result
1. The product will be updated
## Actual result
1. Error message appears: "General system exception happened
   Additional data: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`magento`.`catalog_product_link_attribute_int`, CONSTRAINT `CAT_PRD_LNK_ATTR_INT_LNK_ID_CAT_PRD_LNK_LNK_ID` FOREIGN KEY (`link_id`) REFERENCES `catalog_product_link` (`link_id`) ON DELETE CASC), query was: INSERT INTO `catalog_product_link` (`link_id`,`product_id`,`linked_product_id`,`link_type_id`) VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `link_id` = VALUES(`link_id`)"

**Comment by BaDos** [comment]
Hi @mirkocesaro 

I cannot reproduce this bug on latest develop branch.
What version of Magento are you using?

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed.

**Comment by yoosefi** [comment]
This is on 2.2

https://github.com/magento/magento2/issues/12793
