### ISSUE TITLE
Order grid: not returning to previous page when clicking back on order view page

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4472]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Make sure you have more than 20 orders so you have at least two pages in the order grid
3. go to page 2 (or 3, or 4...) and open an order by clicking 'view'
4. Click the "back" button on the order view page
## Expected result
1. You should be redirected to the page 2 (or 3, or 4...) of the order grid (where you opened the order)
## Actual result
1. Instead you are always redirected to page 1 of the order grid

**Comment by antboiko** [comment]
Hi @SidneyBilliet , thanks for your inquiry. We have internal ticket MAGETWO-52733 for this improvement in our backlog.

Best,
Anton.

**Comment by SidneyBilliet** [comment]
@antboiko , hello, any news on this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Order-grid-not-returning-to-previous-page-when-clicking-back-on/idi-p/46387).
