### ISSUE TITLE
Discouraging GitHub description

### ISSUE THREAD

**Issue by aude** [magento/magento2#4476]
The used GitHub description is not very welcoming:

> All Submissions you make to Magento Inc. (“Magento") through GitHub are subject to the following terms and conditions: (1) You grant Magento a perpetual, worldwide, non-exclusive, no charge, royalty free, irrevocable license under your applicable copyrights and patents to reproduce, prepare derivative works of, display, publically perform, subli… http://www.magento.com

What about some message explaining what Magento is, and possibly also note that it is open source so you can build whatever you'd like with it?

**Comment by maksek** [comment]
@aude please use form for suggestion, github only for bugs and PR.
