### ISSUE TITLE
WEBAPI: bug in catalogProductLinkRepositoryV1SaveRequest doesnt assign item to grouped product if this linked item has no stock

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#4477]
If we send an XML message like this:

`<?xml` version="1.0" encoding="utf-8"?>
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://localhost/magento205/soap/default?services=catalogProductLinkRepositoryV1">
`  soap:Body
`<def:catalogProductLinkRepositoryV1SaveRequest>
`     <entity>
 `<sku>1120</sku>
`       <linkedProductSku>1001</linkedProductSku>
 `<linkedProductType>simple</linkedProductType>
`       <position>3</position>
 `<linkType>associated</linkType>
`       <extensionAttributes>
 `<qty>1</qty>
`        </extensionAttributes>
 `</entity>
`   /def:catalogProductLinkRepositoryV1SaveRequest
 `</soap:Body>
`/soap:Envelope

We receive a true as response, but in the backend the item is not linked, reason is that the linked item is out of stock. if we set the item to in_stcok the item will be proper linked

**Comment by duhon** [comment]
Hello @tinxit 

To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
