### ISSUE TITLE
Order State select box (Assign Order Status to State) shown wrong

### ISSUE THREAD

**Issue by toniyecla** [magento/magento2#4478]
## Steps to reproduce

1/ Create 2 New Status
2/ Assign Status to State
3/ Assign Status to State again
## Expected result
1. Order State dropbox showing "New"
## Actual result
1. Order State dropbox shows "the name of the status created before"
## Final consideration

After all, If we choose it, works fine (aesthetic bug)

**Comment by Mulderua** [comment]
Hi @toniyecla ,
thank you for reporting this issue. Internal ticket was created MAGETWO-52892.

**Comment by magento-engcom-team** [comment]
@toniyecla, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by robertkent** [comment]
This is definitely an issue in 2.2.2
