### ISSUE TITLE
Report -> By customers -> Base table or view not found

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#4480]
Magento ver. 2.0.5
## Steps to reproduce
1. Report
2. By costomers

Actual result

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer_entity' doesn't exist, query was: SELECT COUNT(DISTINCT detail.customer_id) FROM`mag2_review`AS`main_table`
 INNER JOIN`mag2_review_detail`AS`detail`ON main_table.review_id = detail.review_id
 INNER JOIN`customer_entity`AS`customer` ON customer.entity_id = detail.customer_id
#0 C:\xampp\htdocs\magento2\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\xampp\htdocs\magento2\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 C:\xampp\htdocs\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\xampp\htdocs\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(DI...', Array)
#4 C:\xampp\htdocs\magento2\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(DI...', Array)
#5 C:\xampp\htdocs\magento2\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query(Object(Magento\Framework\DB\Select), Array)
#6 C:\xampp\htdocs\magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 C:\xampp\htdocs\magento2\vendor\magento\framework\Data\Collection\AbstractDb.php(217): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#8 C:\xampp\htdocs\magento2\vendor\magento\module-backend\view\adminhtml\templates\widget\grid.phtml(51): Magento\Framework\Data\Collection\AbstractDb->getSize()
#9 C:\xampp\htdocs\magento2\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), 'C:/xampp/htdocs...', Array)
#11 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/xampp/htdocs...')
#12 C:\xampp\htdocs\magento2\vendor\magento\module-backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#13 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#14 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.block...')
#16 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.block...')
#17 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.block...')
#18 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.block...', true)
#19 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(497): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.block...', true)
#20 C:\xampp\htdocs\magento2\vendor\magento\module-backend\Block\Widget\Grid\Container.php(118): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid')
#21 C:\xampp\htdocs\magento2\vendor\magento\module-backend\view\adminhtml\templates\widget\grid\container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#22 C:\xampp\htdocs\magento2\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\xampp\htdocs...')
#23 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Reports\Block\Adminhtml\Review\Customer), 'C:/xampp/htdocs...', Array)
#24 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/xampp/htdocs...')
#25 C:\xampp\htdocs\magento2\vendor\magento\module-backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#26 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#27 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.repor...')
#29 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.repor...')
#30 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.repor...')
#31 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.repor...', true)
#32 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.repor...')
#33 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#34 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#35 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#36 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#37 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#38 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#39 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#40 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#41 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#42 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#43 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#44 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#45 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#46 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#47 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#48 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#49 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#50 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#51 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#52 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#53 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#54 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#55 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#56 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#57 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#58 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#59 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#60 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#61 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#62 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#63 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#64 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#65 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#66 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#67 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#68 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#69 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#70 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#71 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#72 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#73 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#74 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Result\Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#75 C:\xampp\htdocs\magento2\vendor\magento\framework\View\Result\Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#76 C:\xampp\htdocs\magento2\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 C:\xampp\htdocs\magento2\vendor\magento\framework\App\View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 C:\xampp\htdocs\magento2\vendor\magento\module-reports\Controller\Adminhtml\Report\Review\Customer.php(25): Magento\Framework\App\View->renderLayout()
#79 C:\xampp\htdocs\magento2\var\generation\Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor.php(25): Magento\Reports\Controller\Adminhtml\Report\Review\Customer->execute()
#80 C:\xampp\htdocs\magento2\vendor\magento\framework\App\Action\Action.php(102): Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor->execute()
#81 C:\xampp\htdocs\magento2\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#82 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#83 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#84 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor->___callParent('dispatch', Array)
#85 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Reports...', 'dispatch', Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Array, 'adminAuthentica...')
#86 C:\xampp\htdocs\magento2\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#87 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#88 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#89 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Reports...', 'dispatch', Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Array, 'designLoader')
#90 C:\xampp\htdocs\magento2\vendor\magento\framework\App\Action\Plugin\Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#91 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#92 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#93 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Reports...', 'dispatch', Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Array, 'adminMassaction...')
#94 C:\xampp\htdocs\magento2\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#95 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#96 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#97 C:\xampp\htdocs\magento2\var\generation\Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor.php(53): Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor->___callPlugins('dispatch', Array, Array)
#98 C:\xampp\htdocs\magento2\vendor\magento\framework\App\FrontController.php(55): Magento\Reports\Controller\Adminhtml\Report\Review\Customer\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#99 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#100 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#101 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#102 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#103 C:\xampp\htdocs\magento2\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#104 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#105 C:\xampp\htdocs\magento2\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#106 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#107 C:\xampp\htdocs\magento2\vendor\magento\framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#108 C:\xampp\htdocs\magento2\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#109 C:\xampp\htdocs\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#110 {main}`

**Comment by maksek** [comment]
@Dayssam, you have issue with DB, and error is clear stated in log. Check you DB and reinstall Magento 2.

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer_entity' doesn't exist
