### ISSUE TITLE
Can't see pictures in controlpanel

### ISSUE THREAD

**Issue by GPetrova** [magento/magento2#4482]
[bug](https://cloud.githubusercontent.com/assets/1122604/15225302/91c9474a-1886-11e6-960b-87da815493ce.jpg)

**Comment by maksek** [comment]
@GPetrova. It may be due file permissions, please follow devdocs to resolve this.

**Comment by jtrimm007** [comment]
Please explain what a "devdoc" is.....

**Comment by jsakars** [comment]
@jtrimm007 [devdocs](http://devdocs.magento.com/)

**Comment by dexterityzx** [comment]
@GPetrova Can you try "bin/magneto setup:static-content:deploy" in command line under the magento root?
You might need to check the permission after the system deploys the static content.

**Comment by GPetrova** [comment]
I solved mu problem with this solution
https://www.envisionecommerce.com/magento-2-admin-links-not-working-on-localhost-easy-solution/

2016-05-16 19:34 GMT+03:00 Tim notifications@github.com:

> @GPetrova https://github.com/GPetrova Can you try "bin/magneto
> setup:static-content:deploy" in command line under the magento root?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/4482#issuecomment-219474025

## 

Поздрави!
Габриела Петрова

http://about.me/gpetrova#
