### ISSUE TITLE
403 on images in wysiwyg when using a non-administrator role 

### ISSUE THREAD

**Issue by jchesko** [magento/magento2#4484]
Magento 2.0.5
1. Created a "Content Manager" role to give to users who will be managing content.  Assigned all role resources under and including the Content role.
2. Edit a content page using the WYSIWYG editor and inserting an image the image will not display in either the image selector in the editor once the image is inserted.    The URL of the image is resulting in a 403 error.  Note that if logged in as an admin user it works fine.

Example URL:
https://mysite.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvRVhGT0hvbWVQYW5lbC5qcGcifX0,/key/7a138e56b180751c70ffae9afbcffd76c0564155dda650e123757ad16541c9a1/

module-cms/Controller/Adminhtml/Wysiwyg/Directive.php does not have an isAllowed check in it.  In this instance is it defaulting to requiring Administrators permission?

**Comment by oserediuk** [comment]
Hello @jchesko ! I have checked your case on our current code version and I have not got 403 error. Image have been displayed successfully. So, try to update code and reproduce one more time.

**Comment by OLTC-fperrin** [comment]
Hello,

I am using Magento 2.0.7 and I'm having the same issue.
I have users with `Magento_Cms::media_gallery` permissions (these users have `Magento_Backend::content` permissions) but images in the wysiwyg won't show.
After looking at the directive Controller I can see it's extending `\Magento\Backend\App\Action` which checks for `Magento_Backend::admin` (makes sense).

After adding the following to the Directive controller:

```
protected function _isAllowed() {
    return $this->_authorization->isAllowed('Magento_Cms::media_gallery');
}
```

It work just fine. It might not be the best resource to check the ACL against)

Hope this helps

**Comment by oserediuk** [comment]
So, can I close this issue?

**Comment by OLTC-fperrin** [comment]
I haven't seen any fix for this even in the latest sources so I wouldn't think so

**Comment by tkacheva** [comment]
@jchesko I checked on Magento  2.1.0-rc2 and issue doesn't exist. User with manager role has access to previously uploaded images. Wait for Magento 2.1 release coming soon
![wysiwyg](https://cloud.githubusercontent.com/assets/5603216/15962172/edea79da-2f11-11e6-8bd2-b996df189cda.png)

closing the issue. if you come across it again, reopen it
