### ISSUE TITLE
Magento 2.0.5 "Specified url key is already exist in rows"

### ISSUE THREAD

**Issue by pen65978** [magento/magento2#4487]
after updating to magento 2.0.5 i am receiving the following error on mass product upload:

Specified url key is already exist in rows

the url key column of the csv file is empty and the file uploaded fine in 2.0.4... also i am having this problem with an empty catalog and have re-indexed prior to importing.

system running CentOS 7, CPanel, PHP 7

**Comment by gamort** [comment]
See https://github.com/magento/magento2/issues/4430 for a potential workaround until this is fixed

**Comment by duhon** [comment]
To allow us to research the issue, please, provide description according to the template.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by sumitgithub** [comment]
I am using 2.1.1 and still getting this error.

**Comment by pyyick** [comment]
2.0.10 also

**Comment by duyleekun** [comment]
2.0.5 here. Happened when reupload the product and choose Add/Update behavior
