### ISSUE TITLE
Admin customer grid exports only 20 rows

### ISSUE THREAD

**Issue by rbncha** [magento/magento2#4488]
# Magento ver. 2.0.2 export only 20 rows of customer records no matter selected some/all or none in csv/excel format.

**Comment by ilol** [comment]
Registered MAGETWO-52673

**Comment by slavvka** [comment]
Hi @rbncha. This bug ins't reproduce on the latest mainline. Please check.

**Comment by Bartlomiejsz** [comment]
Do you know which commit fixed it?
