### ISSUE TITLE
WEBAPI: missing assigning item to multiple websites in catalogProductRepositoryV1SaveRequest

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#4493]
In the webservice catalogProductRepositoryV1SaveRequest I miss a section for websites, right now it is not possible to assign a product to multiples websites. Can you bring this back again? I would expect a section called `<websites><item>1</item><item>2</item></websites>`

**Comment by pboisvert** [comment]
Mark--can you investigate this item and take next steps as appropriate?

**Comment by mbrinton01** [comment]
#3792 is similar issue

Tracking as internal issue MAGETWO-52812

**Comment by mslabko** [comment]
Hi @tinxit,

At the moment we do not have ability to modify websites with catalogProductRepositoryV1SaveRequest. 
But you can use catalogProductWebsiteLinkRepositoryV1 for assign product to website, e.g
POST /V1/products/product-sku/websites
{
  "productWebsiteLink": {
    "sku": "product-sku",
    "websiteId": 1
  }
}

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by slavvka** [comment]
Hi all, the fix has been delivered to mainline.
