### ISSUE TITLE
Adding Product to cart From wishlist

### ISSUE THREAD

**Issue by ankitambekar08** [magento/magento2#4494]
For configurable product , When i add product to cart from wishlist the page it redirects to, gives attributes as dropdown instead of giving attributes as swatches to select.

**Comment by pboisvert** [comment]
Andrii--can you investigate or reassign if this is more Olena's area?

**Comment by mcspronko** [comment]
Hi @pboisvert and @asemenenko 

Do you have any update regarding this issue?

Thanks,
Max

**Comment by asemenenko** [comment]
@ankitambekar08 @mcspronko the issue should be fixed now, can you check it on the latest version?

**Comment by veloraven** [comment]
We will close this issue as not updated more than 2 weeks.
If this issue still reproducible please feel free to create the new one.
