### ISSUE TITLE
Create cart with rest API

### ISSUE THREAD

**Issue by icenero** [magento/magento2#4495]
## Steps to reproduce
1. Install Magento Community Edition (v 2.0.5) and configure multiple stores.
2. Create a customer on a specific store (using API or web UI)
3. Get an authorization token using API "rest/V1/integration/customer/token" with previous created customer
4. Create a cart using "V1/carts/mine" using authorization token from previous call
## Expected result
1.  Cart is created with customer address and customer's store id
## Actual result
1. Cart is created with default store id (from default website)

I'm new to Magento 2 and API but it looks like the API are not working as espected.

Because the cart a with default storeid will report wrong prices and wrong stock.

Moreover, working with guest cart i have the same issue, in this case we are working with an anonymous customer and during cart creation could be right to take a default store.
Do i have a way to change the storeid in cart calling an API method ?

We are delivering a multi store e.commerce site integrated with a c# application and we have no way to place order on the right store.

Thanks

**Comment by mbrinton01** [comment]
Please provide the call you are using in Step 4 to help us troubleshoot your issue.

**Comment by icenero** [comment]
Hi Mark

sorry for late response.

The call i use is "V1/carts/mine" to create a cart for a given customer.
Now we upgraded Magento to 2.0.7 version and this call gives me always this error "customerId is a required field" but in documentation i see no customer parameter.

Can you give me any hint to create a  cart for a customer and place an order for it and then assign the order to a specific store (we have a multi store environment) ?

Thanks.

**Comment by povesma** [comment]
icenero, "customerId is a required field" - that must be a typo. correct parameter name - customer_id .

**Comment by bhavinwebdesk** [comment]
@icenero are you able to get customer_id by any rest api?

**Comment by smoskaluk** [comment]
Internal ticket was created MAGETWO-70471

**Comment by keevitaja** [comment]
I am having the same issue. A cart for the specific user will be created into the default store always.
If it not a bug, then something is undocumented

![screenshot_2017-07-13_16-58-29](https://user-images.githubusercontent.com/158787/28170029-c02ebc26-67ec-11e7-8e63-4c4f2bd193ff.png)

EDIT: but user can see the order in the correct store!

**Comment by magento-engcom-team** [comment]
@icenero, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by archonkulis** [comment]
@magento-engcom-team 

I'm still able to reproduce the issue. The exact steps from the initial author of the ticket. Create quote through API using /carts/mine POST endpoint passing customer id.

To reproduce it, set some store as a default one. And create the quote for the customer who is assigned to different store.

In the end you will see that it ends up in the following place:

`vendor/magento/module-quote/Model/QuoteRepository.php::loadQuote(...)`

And there is the line:

`$quote->$loadMethod($identifier)->setStoreId($this->storeManager->getStore()->getId());`

Which obviously isn't getting the store id from the customer.

Could you please re-check this? I don't believe you can't reproduce this as even by checking the code you can clearly see where is the error.

Cheers
