### ISSUE TITLE
Flat category urls for SEO

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#4500]
Hi there,

i do not know if this is a bug or a missing feature.
I can find no option to change category url structure:

Normal category urls structure:
domain.com/category
domain.com/category/subcategory
domain.com/category/subcategory/subsubcategory

We need the category urls "flat":
domain.com/category
domain.com/subcategory
domain.com/subsubcategory

This is really a basic basic seo setting but i can´t find this anywhere in the backend. We also had a developer on this writing a module but this causes problems with the url rewrites :-/.

You can adjust this easy in the backend in other cms and shop systems like wordpress, shopify, shopware etc. etc. but not in magento m2?

Also we could not manage to find a clean solution to solve this.
Anybody any suggestions here?

Thanks!

**Comment by maksek** [comment]
Hi @andidhouse, GitHub issues only for bugs with steps to reproduce. Please ask how to questions in forums.
