### ISSUE TITLE
Encryptor.php / Braintree payment module activation crashes backend

### ISSUE THREAD

**Issue by liquidia** [magento/magento2#4502]
## **Steps to reproduce**

1.Install magento 2.05 
2. Try to activate Braintree payment module in using sandbox mode 
3. Backend crashes when trying to save settings

**Magento Report** :
a:4:{i:0;s:41:"Init vector must be a string of 32 bytes.";i:1;s:11866:"#0 /var/www/mysite.com/htdocs/vendor/magento/framework/Encryption/Encryptor.php(401): 

**Temporary Fix:** Remove Line number  401  `return new Crypt($key, $cipher, $mode, $initVector);`
or disable module with following  shell command: `php bin/magento module:disable Magento_Braintree`

**Server Environment:** Nginx / php7 / SSL / HTTP/2

**Comment by pboisvert** [comment]
Andrii--can you have the team investigate?

**Comment by YevSent** [comment]
@liquidia, this is known issue and already fixed in the develop branch.

You can you latest develop branch or apply code from this commit https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6

**Comment by zaietsv** [comment]
There is the same error on magento 2.5 -> 2.6 upgrade http://screenshots.collabstar.com/vza/8a59c378.png

**Comment by SebastienTolron** [comment]
Having same issue here when upgrading from 2.5 to 2.6 

  [Magento\Framework\Exception\LocalizedException]  
  Init vector must be a string of 32 bytes.

**Comment by zaietsv** [comment]
I really haven't any time to extend this "ready-to-use" product with patches. I only want to update it without problems or brainstorms.

**Comment by vipashavivi** [comment]
Having same issue here when upgrading from 2.5 to 2.6

[Magento\Framework\Exception\LocalizedException]
Init vector must be a string of 32 bytes.

**Comment by sakbari** [comment]
Having same issue here when upgrading from 2.5 to 2.6

**Comment by kolaente** [comment]
Ping @magento-engcom-team

**Comment by ArjenMiedema** [comment]
I know it's not a real fix, but I got around the error when disabling Magento_Braintree in my app/etc/config.php manually. After that it all ran as usual.

**Comment by zaietsv** [comment]
Afterwards it happens other interesting thing with less compilation http://screenshots.collabstar.com/vza/b4673abb.png

**Comment by kolaente** [comment]
@zaietsv That seems unrelated to this issue, but it could be related to the magento update.

**Comment by webspeaks** [comment]
@magento-engcom-team Any update? We cant upgrade to 2.2.6 :(

**Comment by webspeaks** [comment]
In my case it turned out to be Redis cache. 
For those who are facing this error:
1. SSH to your server
2. `$ redis-cli`
3. `flushall`

Clear redis cache and it should be solved.

**Comment by kolaente** [comment]
@webspeaks That worked for me, thanks!

**Comment by zaietsv** [comment]
Oh, currently I know what you need to do. It is not a Magento_Braintree or other module impact, but only cache effect. So, all you ned to do is to disable cache before update procedures.
1. Check a cache status by a console command 
> bin/magento cache:status
`Current status:
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
                           eav: 1
         customer_notification: 1
            config_integration: 1
        config_integration_api: 1
                     full_page: 1
                 amasty_shopby: 1
             config_webservice: 1
                     translate: 1
`

2. Disable all caches before update procedures by

> bin/magento cache:disable
`Changed cache status:
                        config: 1 -> 0
                        layout: 1 -> 0
                    block_html: 1 -> 0
                   collections: 1 -> 0
                    reflection: 1 -> 0
                        db_ddl: 1 -> 0
                           eav: 1 -> 0
         customer_notification: 1 -> 0
            config_integration: 1 -> 0
        config_integration_api: 1 -> 0
                     full_page: 1 -> 0
                 amasty_shopby: 1 -> 0
             config_webservice: 1 -> 0
                     translate: 1 -> 0
`

3. If it is too late, and you have errors and unable to perform above mentioned commands, please, edit you env.php and set zeros to all cache types

> nano app/etc/env.php
`'cache_types' => [
        'config' => 0,
        'layout' => 0,
        'block_html' => 0,
        'collections' => 0,
        'reflection' => 0,
        'db_ddl' => 0,
        'eav' => 0,
        'customer_notification' => 0,
        'config_integration' => 0,
        'config_integration_api' => 0,
        'full_page' => 0,
        'translate' => 0,
        'config_webservice' => 0,
        'compiled_config' => 0,
        'amasty_shopby' => 0
    ],
`
After that you will be able to check cache status as it was described at point 1

4. Run upgrade routines in usual way. For example, i use this complex command
`bin/magento cron:remove;
crontab -l;
bin/magento maintenance:enable;
composer update
rm -Rf var/cache/* var/di/* var/generation/* var/page_cache/* var/view_preprocessed/* pub/static/* generated/code/* generated/metadata/*;
bin/magento cache:clean -v;
bin/magento setup:upgrade -v;
bin/magento setup:di:compile -v;
bin/magento setup:static-content:deploy -fv de_CH en_US; #NOTE: Manual static content deployment is not required in "default" and "developer" modes.
bin/magento cache:clean -v;
bin/magento indexer:reindex -v;
bin/magento cache:clean -v;
bin/magento maintenance:disable;
bin/magento cron:install;
crontab -l;`

5. Check magento version by a command bin/magento without params

> bin/magento
`Magento CLI version 2.2.6`

6. Don't forget to turn cache on again to avoid of a system overloading

> bin/magento cache:enable
