### ISSUE TITLE
REST API: Message: No region found within the locale 'en

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#4503]
## Steps to reproduce
1. Install Magento from `develop` branch.
   M2.0.5
2. Add Configurable Product to the cart.
   call a customer api
3. throw exception: Message: No region found within the locale 'en
## Expected result

1.No error found
## Actual result
1. Error message appears: "Cannot save quote".

**Comment by andimov** [comment]
@sheldonli999 thank you! Could you please remove template data from description and leave here only points according this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
