### ISSUE TITLE
Web Setup Wizard error in magento 2

### ISSUE THREAD

**Issue by SuffixtreeTechnologies** [magento/magento2#4504]
I am clicking the Web Setup Wizard in magento 2. Its not opening . I am getting an error like "This site can’t be reached" or "the connection has timed out."

**Comment by mazhalai** [comment]
@venkatesansuffixtree is this after installation? Can you please give more details, how did you initially deploy? Also, if you have installed, is your document root pointing to pub?

**Comment by mazhalai** [comment]
@venkatesansuffixtree closing due to non-responsiveness.
