### ISSUE TITLE
Can't set group pricing (now tier pricing) with higher price than item price

### ISSUE THREAD

**Issue by frangopr** [magento/magento2#4505]
## Steps to reproduce
1. Create Simple Product, fill details and set price to $10.
2. Go to Advanced Settings > Advanced Pricing > Tier Price
3. Set Tier Price for customer group "NOT LOGGED IN", qty "1", price $15.
   *point is to set tier pricing higher than regular price
4. Flush cache
5. Visit front end store
## Expected result
1.  See price for "NOT LOGGED IN" users as $15
## Actual result
1. Price appears as $10 for "NOT LOGGED IN" users
## 

This function is important due to the removal of the group pricing feature. For B2B stores this is a simple feature that would prevent the need for additional extensions for managing different pricing for different groups.

This would of course mean adjusting the logic of how pricing is shown in the front end, to only show that price and not do a crazy: $10, as low as $15 in the front end.

**Comment by benchmarky** [comment]
Found a workaround.

Set item price to $0 and work all pricing on advanced pricing > tier pricing. Not normal for B2C but really standard procedure for B2B sites.

**Comment by zhaomingliang** [comment]


**Comment by antboiko** [comment]
Hi @benchmarky , what version of Magento are you running?

Thanks,
Anton.

**Comment by frangopr** [comment]
Hi @antboiko,

Running ver 2.0.5

Good day,
Fran

**Comment by antboiko** [comment]
Hi @benchmarky , we've created internal ticket MAGETWO-52912 to investigate this issue.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Can-t-set-group-pricing-now-tier-pricing-with-higher-price-than/idi-p/46381).
