### ISSUE TITLE
Compare Products not working in v2.0.5

### ISSUE THREAD

**Issue by jason-vivid** [magento/magento2#4509]
When we go to a product page or category view and click on bar graph icon (hovering over the link shows the URL equal to the page with a # at the end.  IE  example.com/t-shirt.html#

Console Shows this for jquery.js:
mixed Content: The page at 'https://example.com/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://example.com/catalog/product_compare/add/'. This endpoint should be made available over a secure connection.

To clarify all http requests are Redirected to https server side.

**Comment by jamespauljacob3** [comment]
same issue with price alert. using v2.0.6

**Comment by pboisvert** [comment]
@tkacheva please have the team check into this

**Comment by nadshez** [comment]
The issue of compare link not working was also in v2.0.4 and not working in v2.0.6 either.  It is strange that such major functionality is impaired and not fixed in upcoming versions. If anyone has a manual fix, please do share here. Thanks.

**Comment by tkacheva** [comment]
Internal ticket MAGETWO-53313

**Comment by JDavidVR** [comment]
@tkacheva cool! I'm facing same problem in develop branch.

Hope It is fixed soon :)

**Comment by MirkoHuf** [comment]
Hello,
any news about this? I have the same problem in 2.1.2
Compare functionality is not working. 

The products are in the table catalog_compare_item after pressing the "add to the compare list" button in the shop.
I get the message "You added product xyz to the comparison list.".
But the frontend told me "You have no items to compare."

How can I fix this?

**Comment by nadshez** [comment]
Re[2]: [magento/magento2] Compare Products not working in v2.0.5 (#4509)



Hi,

The solution that I found was unbelievable. 

Enable your cache to make it work. If the cache is disabled (as it is in dev mode) the link may not work.

Hope this helps. Thank you.

-- 
Best regards,
Nadeem

Friday, November 18, 2016, 2:43:07 AM, you wrote:

Hello,
any news about this? I have the same problem in 2.1.2
Compare functionality is not working. 
The products are in the table catalog_compare_item after pressing the "add to the compare list" button in the shop.
I get the message "You added product xyz to the comparison list.".
But the frontend told me "You have no items to compare."
How can I fix this?

**Comment by magento-engcom-team** [comment]
@jason-vivid, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by shaikhmasud147** [comment]
Compare Add Product Issue

Console Shows this for jquery.js:
mixed Content: The page at 'https://example.com/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://example.com/catalog/product_compare/add/'. This endpoint should be made available over a secure connection.

To clarify all HTTP requests are Redirected to HTTPS server side.

The same issue facing in Magento 2.0.17. 

How is it solve?

**Comment by bhargav-rupapara** [comment]
Hello, 

I'm also facing this same error, once I click on add to compare link, I can see product is added in report_compared_product_index and catalog_compare_item tables. 

I checked in getItems function of \Magento\Catalog\Block\Product\Compare\ListCompare class, it's showing item count there but, item count in Magento_Catalog/templates/product/compare/list.phtml is showing zero. 

I tried with basic solutions like enable / disable cache, reindex, still on the page http://abc.com/catalog/product_compare/index keep showing this message : "You have no items to compare."

How can I resolve this issue ??

Thanks,
Bhargav

**Comment by bhargav-rupapara** [comment]
> Hello,
> 
> I'm also facing this same error, once I click on add to compare link, I can see product is added in report_compared_product_index and catalog_compare_item tables.
> 
> I checked in getItems function of \Magento\Catalog\Block\Product\Compare\ListCompare class, it's showing item count there but, item count in Magento_Catalog/templates/product/compare/list.phtml is showing zero.
> 
> I tried with basic solutions like enable / disable cache, reindex, still on the page http://abc.com/catalog/product_compare/index keep showing this message : "You have no items to compare."
> 
> How can I resolve this issue ??
> 
> Thanks,
> Bhargav

I'm using magento version 2.1.13
