### ISSUE TITLE
Minify JavaScript Files creating wrong reference for Braintree Module

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#4510]
## Steps to reproduce
1. Install Magento from `main` branch.  Version 2.0.5 version
2. Use inbuilt braintree payment module, with any combination of settings.
3. goto Configuration, Advanced, Developer, JavaScript Settings, Set Minify JavaScript Files to YES. 
## Expected result
1. Braintree payment method should appear and be usable.  
## Actual result
1. Braintree payment method NOT shown on checkout.
2. When minify is enable it creates the reference to a 3rd party code (hosted on braintree) that includes .min.js extension. for example: https://js.braintreegateway.com/v2/braintree.min.js  SHOULD BE: https://js.braintreegateway.com/v2/braintree.js 
   3.The solution in the interim is to turn off Javascript minifcation. 

<img width="976" alt="screen shot 2016-05-15 at 5 53 02 pm" src="https://cloud.githubusercontent.com/assets/9780829/15272734/0bac1204-1ac6-11e6-95f0-4228b0b8ce5c.png">

Different issue to #3811

**Comment by YevSent** [comment]
This issue duplicated to https://github.com/magento/magento2/issues/3916 and already resolved in the develop branch.
Closing this issue, please feel free contacting us if you have any further issues.

**Comment by rudik99** [comment]
Thanks, sorry for the duplicate
