### ISSUE TITLE
What is this? points to wrong internet resources

### ISSUE THREAD

**Issue by addison74** [magento/magento2#4513]
In Magento Backend clicking on ? icon (What's this). A new page is opening in browser but with wrong results. For example clicking on ? in a product page you will get home page from Magento 1 help. This is the link:

http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#configuration/scope.html

**Comment by katmoon** [comment]
@ADDISON74 

Which Magento version do you use?
I see correctly links on develop branch pointing to http://docs.magento.com/m2/ee/user_guide/configuration/scope.html

**Comment by addison74** [comment]
This is Magento CE 2.0.5.

**Comment by duhon** [comment]
Hello @addison74

the solution to the problem tries the latest version

**Comment by katmoon** [comment]
I'm closing the ticket since the issue is fixed in 2.1. Please feel free to reopen if you have additional questions.

And thank you for reporting the issue!
