### ISSUE TITLE
Categories show static blocks in frontend even you did not set them up

### ISSUE THREAD

**Issue by addison74** [magento/magento2#4514]
This is Magento 2.0.5 with sample pack. I wanted to see what CMS blocks are set for every category. 

1) Go in frontend and visit Mens category. You will see this screenshot. Mens category has a CMS Block set up only.

![frontend_block](https://cloud.githubusercontent.com/assets/8360474/15275261/6d0763ba-1acf-11e6-88f0-c82cb204d92b.jpg)

2) Now go to backend and visit Mens category. As you can see from this screenshot there is no CMS Block set up for this category! It is still "Please select a static block".

![backed_block](https://cloud.githubusercontent.com/assets/8360474/15275262/7146003a-1acf-11e6-874c-a2852943bc26.jpg)

<strong>How is Magento able to set up in frontend CMS blocks which are not set in backend?</strong>

<strong>Please click on [Save] button. Your category will be saved even you did not set up the CMS block. An error should be visible in this case. You cannot set to static blocks without selecting a block.</strong>

**Comment by Harrington77** [comment]
@ADDISON74 
The category in question is using the widget feature to place the static block content; see attachment. I hope this is helpful.
![screen shot 2016-08-11 at 4 23 47 pm](https://cloud.githubusercontent.com/assets/17125403/17605364/b43f8c80-5fdf-11e6-8ce2-86dfc48f9b15.png)

**Comment by veloraven** [comment]
@ADDISON74  the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please feel free to report new GitHub issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
