### ISSUE TITLE
Magento 2 Admin panel not working 

### ISSUE THREAD

**Issue by vcpawate** [magento/magento2#4515]
I am using Magento 2.0.5 and Data migration tool to migration from 1.9.0.1

**Problem**:
When tried to access admin page on Chrome and Firefox:
After entering successful credentials for admin page, I can see same admin page. All credentials are correct, and I can see Dashboard on the browser Title, and suddenly, it shows same page.

After installation for the first use, it allows to login to admin page, and when you logout, when you try to login, above behaviour is noted,

I tried to open in IE, it says **Hmm, we can’t reach this page**., **I have tried all options available online, referred to different tickets in github relating to it, but still it shows consistently page not found** 

http://ec2-52-_-_-*.ap-southeast-1.compute.amazonaws.com/admin/admin/index/index/key/78f305c73c48603be6d53ac01dbe3294a185160c3e045dd770c2eb412a0222e0/

Please help

**Comment by vcpawate** [comment]
please help

**Comment by vcpawate** [comment]
please help Remainder 2

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
