### ISSUE TITLE
Magento\Framework\DB\Adapter\Pdo\Mysql getColumnCreateByDescribe returns wrong column length

### ISSUE THREAD

**Issue by paales** [magento/magento2#4517]
When inputting a `mediumtext` column a `text` definition returns but with length `null`, should be `2M`.

I'm trying to copy a table to a new table, but the newly generated table is different than the existing table.

**Comment by paales** [comment]
Somewhat related, but don't know if it is a bug:

`Zend_Db_Adapter_Pdo_Mysql::describeTable` doesn't return the column lengths of int fields. It mentiones the following:

> The optional argument of a MySQL int type is not precision or length; it is only a hint for display width.

Worked around it for now, but it is somewhat odd that describeTable doesn't describe the table..

**Comment by paales** [comment]
It also improperly escapes `CURRENT_TIMESTAMP`, it returns it as `'CURRENT_TIMESTAMP'`. It should return a constant `Magento\Framework\DB\Ddl\Table::TIMESTAMP_UPDATE` in that case.

In an ideal case, it should use some logic used in `_getColumnDefinition`

**Comment by duhon** [comment]
To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version of Magento and MySQL. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
