### ISSUE TITLE
Google Fonts are not applied on frontend

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#4518]
Added a Google Font to my custom theme `default_head_blocks.xml` file:

`<link src="https://fonts.googleapis.com/css?family=Lato" src_type="url"/>`

Then added the following line to my `_typography_extend.less` file:

`@font-family__sans-serif: Lato;`

After clearing cache, deleting files under `pub/static` and `var/view_preprocessed`, and reloading site, the font Lato is not applied by default because there is an **"Open Sans"** font in the first place:

From Firebug:

```
font-family: 'Open Sans', Lato;
```

If I delete 'Open Sans' on that line directly on firebug, then the google font (Lato) is applied successfully.

Where is the 'Open Sans' font coming from? How can I delete/disable that font?

**Comment by ghost** [comment]
Hello @lgarridoj !
To change the base font family you should overwrite `@font-family-name__base` variable. You can find original declaration in `app\design\frontend\Magento\blank\web\css\source\_variables.less` and it looks like this: 

```
@font-family__base: @font-family-name__base, @font-family__sans-serif;
```

**Comment by jibrandlr** [comment]
thank you, im closing this issue
