### ISSUE TITLE
Frontend Theming Feature Request

### ISSUE THREAD

**Issue by theskillwithin** [magento/magento2#4520]
Hello,

I am a frontend developer, and well working in Magento 2 frontend is well... a pain because while building out your styles you hit save and it can take 6+ seconds just to refresh the page(must have caching off as you know to work in, I have a very very expensive computer as well which doesn't seem to help when it comes to php ie no multithread).  As opposed to my workflow outside of Magento takes less than a second.   This is just how the cookie crumbles really however: 

I propose making  a tool that allows you to work on some of the frontend code outside of Magento.  I have a few ideas of how this would work, however it would take someone really smart to implement.   You would need to generate some dummy html that does not get updated and you view that when you edit your styles outside of Magento, then later import you theme back into vendor or wherever.  The quality of front-end code this would allow me to create would be much superior and my clients have high standards.

Or perhaps this can also be expanded to template files as well by making it refer to some static source instead of db for quick page reload.

Cheers,
Austin

**Comment by tkacheva** [comment]
Hi @theskillwithin,
there are different options to generate css in Magento (http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.htm)
Please provide more details on what you are using

What is your vision on how to make the styles generated outside of magento considering all of magento fallbacks?

**Comment by theskillwithin** [comment]
Details on what I am using currently:
https://github.com/SnowdogApps/magento2-frontools
https://github.com/SnowdogApps/magento2-theme-blank-sass  (I copied this theme to use for my new theme)

and well as you probably expected I use the npm,gulp, bower kind of workflow.  sass, autoprefixer, sourcemaps, something to concat my js, some sort of minifier, etc 
I am on mac so I have the advantage of tail -f /log/logfile and it will print log file details on my terminal as they are added, I am thinking of doing this automatically in gulp using https://www.npmjs.com/package/tail which also has the benefit of my windows coworkers to use tail as well. 

browsersync, I also use this a lot, however it is so slow when u hit save and refresh that this tool I don't even use anymore on magento2, as it just takes so long to refresh that this tools benefits gets watered down so to speak. 

So yes there is a developer mode, possibly there could be a frontend mode.  Now yes this is theoretical so implementation is a whole different thing.  So instead of refreshing the cache every time you change a phtml or less/scss file the fallbacks would be cached so you can quickly refresh.  perhaps even a js method can be made to hot refresh elements or styles on the current page that the watcher detected changes on.   I get it, its a half baked idea and there are a lot of problems however keeping an open mind about this would just be amazing.

To be honest though I am having a hard time with layout at the moment so I I'd like to figure that out first before pretending to have good ideas haha.  Perhaps at that time I could make a proper pull request.   I am working on my first Magento 2 theme and while I am a master at css and such the XML layout I am still figuring out so I'm still figuring out the small things here sinking a lot of time into it and there are a lot of people who have given up but I intend to figure it out.  For some reason in Magento 1 it was a lot more phtml edits but it will be good for me to learn anyways.  Perhaps Ill even make a screencast video on it to help others out when I get there. 

Thank you @tkacheva  I honestly didn't expect anyone to listen.

**Comment by tkacheva** [comment]
Hi @theskillwithin,
since you use sass here is the great news for you https://alankent.me/2016/05/21/magento-2-community-project-moving-from-less-to-sass/
SNOW.DOG will be leading community for this effort so you can contact them to incorporate your ideas

**Comment by piotrekkaminski** [comment]
@theskillwithin additionally you shouldn't have to disable all caches doing front-end changes. Our internal developers work with all caches on and clear them as needed. You can also look at https://github.com/SnowdogApps/magento2-frontools for workflow optimization ideas.

**Comment by tkacheva** [comment]
Closing the ticket as the question seems answered. Reopen if needed.
