### ISSUE TITLE
Address area in invoice shows template instead of address

### ISSUE THREAD

**Issue by jniebuhr** [magento/magento2#4521]
## Steps to reproduce
1. Install Magento from `2.0.5` branch.
2. Create a customer with addresses
3. Create an order for this customer
4. See template instead of address
## Expected result
1. You should be able to see the address
## Actual result
1. Template language is shown

![magento_bug_1](https://cloud.githubusercontent.com/assets/2579336/15279725/cd53d61a-1b27-11e6-8099-a66791da6acc.png)

**Comment by Mulderua** [comment]
Hi @joni-jones, we cannot reproduce this bug on 2.0.5 and 2.0.7. Please try to run composer update, disable all third party extensions and do this scenario again.

**Comment by NadiyaS** [comment]
the issue is closed since there is no response from reporter more than 2 weeks.
