### ISSUE TITLE
AddressMetadataInterface has a wrong attribute set id

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#4523]
## Steps to reproduce
1. AddressMetadataInterface, 
2. ATTRIBUTE_SET_ID_ADDRESS = 2
3. ...
## Expected result
1. ATTRIBUTE_SET_ID_ADDRESS should be 4
2. ...
## Actual result
1. ATTRIBUTE_SET_ID_ADDRESS = 2
2. as a result, all address fields are empty.
3. ...

**Comment by slavvka** [comment]
Hi @sheldonli999, If you can look into the database (eav_attribute_group, eav_attribute_set, eav_entity_attribute and customer_eav_attribute), you can see that 1 stands for customer attribute set, 2 is for customer address attribute set and proposed 4 stands for product attributes. Could you please check that and give us more detailed information and issue description. Thank you!

**Comment by sheldonli999** [comment]
Hi:  it looks like 2.0.6 has fixed the issue.  Thanks.  Have a different question: When I make a restful call, I consistently get an error message: message":"No region found within the locale 'en’.  Do you have any advise?  I tried to set the store properly via Admin UI.  The region is set to California, etc...  Thanks

**Comment by slavvka** [comment]
Could you please create another ticket for this problem?
