### ISSUE TITLE
Proxy class does not include the methods from overridden class

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#4524]
I have overridden the  class`\Magento\Catalog\Model\Product\Link` and added 2 methods, but these methods are not included in the proxy class `Magento\Catalog\Model\Product\Link\Proxy` how can i inject my methods to this class?

**Comment by antonkril** [comment]
How did you override the class? Extend from it and substitute with preference? Proxy of original class will not contain your methods. Only Proxy of your class will. You have to configure your class proxy everywhere the proxy of original class is requested/configured.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
