### ISSUE TITLE
Webapi GET /V1/categories does not return all the categories created by UI

### ISSUE THREAD

**Issue by karanbhomiagit** [magento/magento2#4525]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create multiple categories and sub-categories for products.
3. Make a REST api call GET /V1/categories, with or without search Criteria.
## Expected result
1.  The GET call should return json response with all the categories created from UI.
## Actual result
1. Only 1 category and it's sub-categories are returned in the json response.
2. Sample response : 
   `{
   "id": 2,
   "parent_id": 1,
   "name": "Default Category",
   "is_active": true,
   "position": 1,
   "level": 1,
   "product_count": 28,
   "children_data": [
     {
       "id": 3,
       "parent_id": 2,
       "name": "Bike",
       "is_active": true,
       "position": 1,
       "level": 2,
       "product_count": 29,
       "children_data": [
         {
           "id": 6,
           "parent_id": 3,
           "name": "Helmets",
           "is_active": true,
           "position": 1,
           "level": 3,
           "product_count": 25,
           "children_data": []
         }
       ]
     },
     {
       "id": 4,
       "parent_id": 2,
       "name": "Petrol components",
       "is_active": true,
       "position": 2,
       "level": 2,
       "product_count": 8,
       "children_data": []
     },
     {
       "id": 5,
       "parent_id": 2,
       "name": "Services",
       "is_active": true,
       "position": 3,
       "level": 2,
       "product_count": 13,
       "children_data": []
     }
   ]
   }`

![categorybug](https://cloud.githubusercontent.com/assets/14216430/15291635/9582c352-1b9c-11e6-8c59-6c10ea8e2789.JPG)

**Comment by ruby10** [comment]
@katmoon , would you please tell which release will be having fix for it?

**Comment by srinivasanithin** [comment]
@katmoon : Can we have a update on this issue as well? 

Is it intended to have single root category and have other actual categories as subcategories to root category? I remember we were have multiple root categories in Magento1 as different product lines (apparels, toys) have different category lines.

**Comment by katmoon** [comment]
Hi all

Thank you for reporting the issue!
I've created internal ticket `MAGETWO-53152` to fix it.

Thanks,
Kateryna.

**Comment by vzabaznov** [comment]
Hi @karanbhomiagit , thanks for reporting, issue was fixed and will be delivered in next release under cc99eda and 8e58508 commits, if you think that bug is reproducible, please open this, or create new one.
