### ISSUE TITLE
Rest api POST /V1/products/ and PUT /V1/products/:sku calls do not update some fields on the UI.

### ISSUE THREAD

**Issue by karanbhomiagit** [magento/magento2#4527]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Try creating a product through rest api call POST /V1/products/
3. The product gets created but some of the fields do not show the values that were provided.
4. Try updating the product through PUT /V1/products/:sku api call.
5. The product still does not show any values for those fields.
6. Fields which are not getting updated are : 
    a) Description 
    b) Special Price From Date / To Date  
    c) Tax Class  
    d) Meta-Description / Meta-Title / Meta - Keywords  
    e) Custom Design / Custom Design From Date  
    f) **Any custom attribute that I created manually from the UI**.(and assigned to the attribute set that  I am using to create the product)
## Expected result
1. All the fields in UI should show the values provided in the request json body, on both POST and PUT calls.
## Actual result
1. Fields in UI do not show the values which were given during creation/updation of the product.
2. A peculiar observation : If I make a GET call on the product, the json response body contains the correct values. But the values do not show up on the UI.
## Sample JSON requests and UI screenshots

1) **## Scenario 1 : Creation of product**
a) POST /V1/products/

Sample request : `{
    "product": {
        "sku": "Item-10012",
        "name": "Item-10012",
        "attribute_set_id": 4,
        "price": 14,
        "status": 1,
        "visibility": 4,
        "type_id": "simple",
        "weight": 1,
        "extension_attributes": {
            "stock_item": {
                "stock_id": 1,
                "is_in_stock": true,
                "is_qty_decimal": true,
                "show_default_notification_message": false,
                "use_config_min_qty": true,
                "min_qty": 0,
                "use_config_min_sale_qty": 1,
                "min_sale_qty": 1,
                "use_config_max_sale_qty": true,
                "max_sale_qty": 10000,
                "use_config_backorders": true,
                "backorders": 0,
                "use_config_notify_stock_qty": true,
                "notify_stock_qty": 1,
                "use_config_qty_increments": true,
                "qty_increments": 0,
                "use_config_enable_qty_inc": false,
                "enable_qty_increments": false,
                "use_config_manage_stock": true,
                "manage_stock": true,
                "low_stock_date": null,
                "is_decimal_divided": false,
                "stock_status_changed_auto": 0
            }
        },
        "product_links": [
            {
                "sku": "Item-10012",
                "link_type": "related",
                "linked_product_sku": "Helmet-Hulk-Red",
                "linked_product_type": "simple",
                "position": 0,
                "extension_attributes": []
            }
        ],
        "options": [

```
    ],
    "media_gallery_entries": [],
    "tier_prices": [
        {
            "customer_group_id": 0,
            "qty": 10,
            "value": 12
        },
        {
            "customer_group_id": 2,
            "qty": 100,
            "value": 8
        }
    ],
    "custom_attributes": [
        {
            "attribute_code": "special_price",
            "value": "3.0000"
        },
        {
            "attribute_code": "special_from_date",
            "value": "2016-04-18 00:00:00"
        },
        {
            "attribute_code": "special_to_date",
            "value": "2016-05-12 00:00:00"
        },
        {
            "attribute_code": "meta_title",
            "value": "Item-10012"
        },
        {
            "attribute_code": "meta_keyword",
            "value": "Item-10012"
        },
        {
            "attribute_code": "description",
            "value": "<p>Item-10012 description</p>"
        },
        {
            "attribute_code": "news_from_date",
            "value": "2016-04-18 00:00:00"
        },
        {
            "attribute_code": "custom_design",
            "value": "1"
        },
        {
            "attribute_code": "custom_design_from",
            "value": "2016-04-18 00:00:00"
        },
        {
            "attribute_code": "custom_design_to",
            "value": "2016-05-06 00:00:00"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "4",
                "5"
            ]
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "required_options",
            "value": "1"
        },
        {
            "attribute_code": "has_options",
            "value": "1"
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        }
    ]
}
```

}`
Response : 200 OK

b) GET /V1/products/item-10012

Response : `{
  "id": 49,
  "sku": "Item-10012",
  "name": "Item-10012",
  "attribute_set_id": 4,
  "price": 14,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "created_at": "2016-05-16 14:21:20",
  "updated_at": "2016-05-16 14:21:20",
  "weight": 1,
  "extension_attributes": {
    "stock_item": {
      "item_id": 47,
      "product_id": 49,
      "stock_id": 1,
      "qty": null,
      "is_in_stock": false,
      "is_qty_decimal": true,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": false,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": true,
      "low_stock_date": "2016-05-16 14:21:20",
      "is_decimal_divided": false,
      "stock_status_changed_auto": 1
    }
  },
  "product_links": [
    {
      "sku": "Item-10012",
      "link_type": "related",
      "linked_product_sku": "Helmet-Hulk-Red",
      "linked_product_type": "simple",
      "position": 0,
      "extension_attributes": []
    }
  ],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [
    {
      "customer_group_id": 0,
      "qty": 10,
      "value": 12
    },
    {
      "customer_group_id": 2,
      "qty": 100,
      "value": 8
    }
  ],
  "custom_attributes": [
    {
      "attribute_code": "description",
      "value": "<p>Item-10012 description</p>"
    },
    {
      "attribute_code": "special_price",
      "value": "3.0000"
    },
    {
      "attribute_code": "special_from_date",
      "value": "2016-04-18 00:00:00"
    },
    {
      "attribute_code": "special_to_date",
      "value": "2016-05-12 00:00:00"
    },
    {
      "attribute_code": "meta_title",
      "value": "Item-10012"
    },
    {
      "attribute_code": "meta_keyword",
      "value": "Item-10012"
    },
    {
      "attribute_code": "news_from_date",
      "value": "2016-04-18 00:00:00"
    },
    {
      "attribute_code": "custom_design",
      "value": "1"
    },
    {
      "attribute_code": "custom_design_from",
      "value": "2016-04-18 00:00:00"
    },
    {
      "attribute_code": "custom_design_to",
      "value": "2016-05-06 00:00:00"
    },
    {
      "attribute_code": "category_ids",
      "value": [
        "4",
        "5"
      ]
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "required_options",
      "value": "0"
    },
    {
      "attribute_code": "has_options",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "item-10012"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    }
  ]
}`

c) UI Screenshots : 
![post0](https://cloud.githubusercontent.com/assets/14216430/15292472/d9952338-1ba0-11e6-9a1b-8ef3e38145e8.JPG)
![post1](https://cloud.githubusercontent.com/assets/14216430/15292478/e1b95bba-1ba0-11e6-9a59-c2bea2dd722f.JPG)
**Please note that "Something" is a custom attribute created by me using the UI.**
![post2](https://cloud.githubusercontent.com/assets/14216430/15292499/fd18d7f0-1ba0-11e6-981c-bfc60647906b.JPG)
![post3](https://cloud.githubusercontent.com/assets/14216430/15292504/010e3daa-1ba1-11e6-9708-6e21e33209d4.JPG)
![post4](https://cloud.githubusercontent.com/assets/14216430/15292508/051b81dc-1ba1-11e6-801f-10171dacc11a.JPG)

2) **## Scenario 2 : Updation of product**
a) PUT /V1/products/item-10012

Sample request : `{
    "product": {
  "id": 49,
  "sku": "Item-10012",
  "name": "Item-10012",
  "attribute_set_id": 4,
  "price": 14,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "weight": 1,
  "extension_attributes": {
    "stock_item": {
      "item_id": 47,
      "product_id": 49,
      "stock_id": 1,
      "qty": null,
      "is_in_stock": false,
      "is_qty_decimal": true,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": false,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": true,
      "low_stock_date": "2016-05-16 14:21:20",
      "is_decimal_divided": false,
      "stock_status_changed_auto": 1
    }
  },
  "product_links": [
    {
      "sku": "Item-10012",
      "link_type": "related",
      "linked_product_sku": "Helmet-Hulk-Red",
      "linked_product_type": "simple",
      "position": 0,
      "extension_attributes": []
    }
  ],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [
    {
      "customer_group_id": 0,
      "qty": 10,
      "value": 12
    },
    {
      "customer_group_id": 2,
      "qty": 100,
      "value": 8
    }
  ],
  "custom_attributes": [
    {
      "attribute_code": "description",
      "value": "<p>Item-10012 updated description</p>"
    },
    {
      "attribute_code": "special_price",
      "value": "3.0000"
    },
    {
      "attribute_code": "special_from_date",
      "value": "2016-05-18 00:00:00"
    },
    {
      "attribute_code": "special_to_date",
      "value": "2016-06-12 00:00:00"
    },
    {
      "attribute_code": "meta_title",
      "value": "Item-10012 updated"
    },
    {
      "attribute_code": "meta_keyword",
      "value": "Item-10012 updated"
    },
    {
      "attribute_code": "news_from_date",
      "value": "2016-04-18 00:00:00"
    },
    {
      "attribute_code": "custom_design",
      "value": "1"
    },
    {
      "attribute_code": "custom_design_from",
      "value": "2016-05-18 00:00:00"
    },
    {
      "attribute_code": "custom_design_to",
      "value": "2016-06-06 00:00:00"
    },
    {
      "attribute_code": "category_ids",
      "value": [
        "4",
        "5"
      ]
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "required_options",
      "value": "0"
    },
    {
      "attribute_code": "has_options",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "item-10012-up"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    }
  ]
}
}`
Response : 200 OK

b) GET /V1/products/item-10012

Response : `{
  "id": 49,
  "sku": "item-10012",
  "name": "Item-10012",
  "attribute_set_id": 4,
  "price": 14,
  "status": 1,
  "visibility": 4,
  "type_id": "simple",
  "created_at": "2016-05-16 14:21:20",
  "updated_at": "2016-05-16 14:30:42",
  "weight": 1,
  "extension_attributes": {
    "stock_item": {
      "item_id": 47,
      "product_id": 49,
      "stock_id": 1,
      "qty": null,
      "is_in_stock": false,
      "is_qty_decimal": true,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": false,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": true,
      "low_stock_date": "2016-05-16 14:30:42",
      "is_decimal_divided": false,
      "stock_status_changed_auto": 1
    }
  },
  "product_links": [
    {
      "sku": "item-10012",
      "link_type": "related",
      "linked_product_sku": "Helmet-Hulk-Red",
      "linked_product_type": "simple",
      "position": 0,
      "extension_attributes": []
    }
  ],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [
    {
      "customer_group_id": 0,
      "qty": 10,
      "value": 12
    },
    {
      "customer_group_id": 2,
      "qty": 100,
      "value": 8
    }
  ],
  "custom_attributes": [
    {
      "attribute_code": "description",
      "value": "<p>Item-10012 updated description</p>"
    },
    {
      "attribute_code": "special_price",
      "value": "3.0000"
    },
    {
      "attribute_code": "special_from_date",
      "value": "2016-05-18 00:00:00"
    },
    {
      "attribute_code": "special_to_date",
      "value": "2016-06-12 00:00:00"
    },
    {
      "attribute_code": "meta_title",
      "value": "Item-10012 updated"
    },
    {
      "attribute_code": "meta_keyword",
      "value": "Item-10012 updated"
    },
    {
      "attribute_code": "news_from_date",
      "value": "2016-04-18 00:00:00"
    },
    {
      "attribute_code": "custom_design",
      "value": "1"
    },
    {
      "attribute_code": "custom_design_from",
      "value": "2016-05-18 00:00:00"
    },
    {
      "attribute_code": "custom_design_to",
      "value": "2016-06-06 00:00:00"
    },
    {
      "attribute_code": "category_ids",
      "value": [
        "4",
        "5"
      ]
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "required_options",
      "value": "0"
    },
    {
      "attribute_code": "has_options",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "item-10012-up"
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    }
  ]
}`

c) UI Screenshots : 
Exactly same as above.

**Comment by ruby10** [comment]
Hi @katmoon , failure of these two API's are acting as blockers for integration of Magento2 Items. Please let me know if there is any update on it?

**Comment by srinivasanithin** [comment]
Hi 

I am also facing issue. Is it already resolved ? can you let me know how you guys resolved it? It will be really helpful.

Thanks in advance

**Comment by karanbhomiagit** [comment]
@katmoon : Any updates on this issue?

**Comment by srinivasanithin** [comment]
@katmoon : 
can you please let us know your findings in this issue?

**Comment by pboisvert** [comment]
@mbrinton01 can you have the team take a look at this issue?

**Comment by karanbhomiagit** [comment]
Any updates on this guys? @pboisvert @mbrinton01

**Comment by karanbhomiagit** [comment]
Sorry, closed it by mistake.

**Comment by mslabko** [comment]
Hi @karanbhomiagit , @srinivasanithin
This issue already fixed in develop branch and will be available in 2.1 release.
For find out the release date, please, follow up marketing updates.

Please, try to update your code base and if you still have any issues reopen this one.

**Comment by vaimeo** [comment]
is their any patch we can apply to fix this issue?

**Comment by geon** [comment]
Still seeing exactly this in 2.1.2

I set

    "custom_attributes":[{"attribute_code":"description","value":"foo"}]

It is not updated in the GUI. But I get the new values via the GET request to the REST API.

Both the old and new values are stored in the database:

```
mysql> select * from catalog_product_entity_text ; 
+----------+--------------+----------+-----------+------------+
| value_id | attribute_id | store_id | entity_id | value |
+----------+--------------+----------+-----------+------------+
|        1 |           75 |        0 |         1 | foo                                                                                                                                                                                                          |
|        2 |           76 |        0 |         1 | bar                                                                                                                                                                                                          |
|        3 |           75 |        1 |         1 | bazffffff                                                                                                                                                                                                    |
|        4 |           76 |        1 |         1 | fooooooo |
+----------+--------------+----------+-----------+------------+
4 rows in set (0.00 sec)

```

value_id 1 and 2 are the originally created description and short_description. value_id 3 and 4 are the updated values.

Notice how store_id is 0 for the original values. Weird. Ids usually start on 1, and I only have one store.

**Comment by eyesoverrun** [comment]
Hi, I have the same problem with version 2.1.5.
When I update the special rate with PUT, the records are saved in the database with the "STORE_ID" = 1 and the date it does not appear in the backend and frontend.

**Comment by HoloShaii** [comment]
Hey, Same issue still present in version 2.1.7.
Updating the description of a product with a value using the rest api, it will be saved to the database, and be available with the GET command, but it won't show up on the GUI.

**Comment by poveu** [comment]
This still seems to be an issue in 2.2.6 - I have set the custom attribute value via REST API (PUT/POST) and I can see this attribute when GETting the product info, but it is not visible on frontend/backend.

Is #18867 a related fix?

//Edit - it is indeed.
