### ISSUE TITLE
New Simple Product automatically converts into Virtual Product

### ISSUE THREAD

**Issue by jusemjo** [magento/magento2#4533]
Hi Community,

since a couple of days I'm not able to set up a simple product any more. Any attempt to create a "Simpel Product" in the backend leads to a new "Virtual Product". Futher more the virtal product is not visible in the shops frontend.

Currently I'm running Magento 2.05

Looking forward to your solutions, regards Jule

**Comment by espradley** [comment]
I'm seeing the same thing -- Was on EE 2.0.4, tried upgrading to 2.0.5 to no avail.   We are running php 7.0.5 and this occurred both in Firefox and Chrome.

**Comment by espradley** [comment]
@jusemjo Just dug into the code and when creating a simple, if you select "no" for "does product have weight," it will type convert it into a virtual product.   Try creating the product with a weight and see if that solves the problem.

**Comment by espradley** [comment]
More info for anyone looking.   I found the code doing this: 

\Magento\Catalog\Model\Product\TypeTransitionManager\

```
    /**
     * Process given product and change its type if needed
     *
     * @param \Magento\Catalog\Model\Product $product
     * @return void
     */
    public function processProduct(Product $product)
    {
        if (in_array($product->getTypeId(), $this->compatibleTypes)) {
            $product->setTypeInstance(null);
            $productTypeId = $this->weightResolver->resolveProductHasWeight($product)
                ? Type::TYPE_SIMPLE
                : Type::TYPE_VIRTUAL;
            $product->setTypeId($productTypeId);
        }
    }
}
```

**Comment by jusemjo** [comment]
Thanks a lot! Sometimes it's that easy - sorry for not testing it beforehand!
Great answer @espradley  - appreciate it a lot!

**Comment by mbrinton01** [comment]
@espradley, thank you for helping with this issue!  Closing the issue as resolved

**Comment by medinadato** [comment]
If someone interested on the solution for this one, I've put together an article about the issue https://blog.mdnsolutions.com/magento-2-missing-weight-field-on-backend-and-wrong-virtual-product-types/ . Cheers, Renato.
