### ISSUE TITLE
Bug when go to Content -> Page in admin panel Magento2

### ISSUE THREAD

**Issue by kayl1234** [magento/magento2#4534]
When i try to go to CONTENT -> Page to manage the cms homepage or CONTENT -> Blocks to manage static block, this bug occur. Anyone know about this bug, please help me. Many thanks
DateTimeZone::__construct(): Unknown or bad timezone ()

**Comment by chonny** [comment]
Same problem when i visit product list at admin panel. Magento 2.1 EE.

**Comment by veloraven** [comment]
@kayl1234 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by akosglue** [comment]
@chonny Try to verify the locale settings under Stores / Configuration / General / General / Locale options -> **for each** of your scopes like Default config, Default Store view etc. etc.
After that setup:upgrade and setup:static-content:deploy, cache:clean and cache:flush
This might help hopefully.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by mrkhoa99** [comment]
Here is one solution for this issue: https://magento.stackexchange.com/a/155554/33057
