### ISSUE TITLE
Block cachable attribute not working

### ISSUE THREAD

**Issue by devhn** [magento/magento2#4538]
**Using:** Magento 2.0.5, custom theme, custom simple testing module.

**Question:** How to set a block to be non cacheable properly?

**Actual result:** Attribute `cacheable="false"` doesn't work when setting it to a custom block. Currently the block gets cached and producing errors within page-cache.js, which we could avoid by uncaching the custom block (we are including async javascript which shouldn't be cached within Magento mechanism).

**Error in console:** `Uncaught TypeError: element.prop is not a function`

**The layout:** 
`<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="before.body.end">
            <block class="Magento\Framework\View\Element\Template" name="test" template="Vendor_test::default.phtml" cacheable="false" after="-"/>
        </referenceContainer>
    </body>
</page>`

**Comment by joanhe** [comment]
@devhn When layout is changed, please make sure layouts cache type is refreshed. Please let me know if this helps.

**Comment by devhn** [comment]
Yes, cache was fully cleared (both Magento and browser).

p.s. Also tried with redeploying files (altough this process shouldn't influence the xml changes).

**Comment by PascalBrouwers** [comment]
Hi @devhn ,

I had the same issue. See my comments here on how to fix it: https://github.com/magento/magento2/issues/6818

**Comment by devhn** [comment]
@PascalBrouwers thanks, we applied this fix also within the page-cache.js as we had issues with Live Chat like you.

**Comment by veloraven** [comment]
I'm closing this issue as the issue was resolved.
If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
