### ISSUE TITLE
 The start date of the report is greater than the end date validation problem ！

### ISSUE THREAD

**Issue by huabiao** [magento/magento2#4539]
## Steps to reproduce

1.to the Sales Report
2. select from date as 5/17/16
3.select  to date as 5/1/16
--result--
 No date range verified

**Comment by katmoon** [comment]
Hi @huabiao 

Thank you for reporting the issue!
The issue is reproducible and logged internally as `MAGETWO-53039`

Thanks,
Kateryna.

**Comment by magento-engcom-team** [comment]
@huabiao, thank you for your report.
We've created internal ticket(s) MAGETWO-53039 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@huabiao, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
