### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by jksimoniii** [magento/magento2#4542]
## Steps to reproduce
1. Install Magento 2.0.5 via composer
2. Run composer install (composer version 1.2-dev)
## Expected result
1. Clean installation output
## Actual result

```
Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onNewCodeEvent declared at /home/jim/Sites/RDS/webroot/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

```

**Comment by mazhalai** [comment]
Thank you for reporting, we have already fixed it internally. Please see #4383 and https://github.com/magento/magento2/issues/4392#issuecomment-217151684 Closing as duplicate.

**Comment by jksimoniii** [comment]
Apologies for the duplicate

**Comment by mazhalai** [comment]
@jksimoniii this has been fixed in https://github.com/magento/magento-composer-installer/releases/tag/0.1.8
