### ISSUE TITLE
Flush Static Files Cache deletes app folder

### ISSUE THREAD

**Issue by Jasonb11** [magento/magento2#4543]
## Steps to reproduce
1. Navigate to system > cache management
2. When clicking this button: https://gmkr.io/s/573b60434ed9c6dd04b67d62/0 static files located in the app folder are deleted  
## Expected result
1. Clear the static files without deleting the app folder 
## Actual result
1. App Folder is deleted from server and all of the extensions and css styles are dropped.

---

 *Currently we dont have a screenshot because we are doing a large import of data
 *Logs screenshots will be shared once imports are done.

**Comment by choukalos** [comment]
Internal ticket - MAGETWO-52922

**Comment by dsikkema-magento** [comment]
Can you give an example of some files that got deleted? I went through the steps, and nothing under magento-root/app seems to have been deleted.

**Comment by dsikkema-magento** [comment]
Closing this as unreproducible, but please let us know the additional details if you still experience the problem

**Comment by braindigitalis** [comment]
I just managed to reproduce this by accident. It deleted my entire site, and i had to restore from a backup. I'm unwilling to try again though, this was a live site!

**Comment by key-dev** [comment]
Hi there,
I am having this issue in 2.2.5.
I just hit setup:upgrade and then flush cache. Front-end gets broken and when i check web/css in my child theme actual file gets removed.
Please help.

**Comment by DanielRuf** [comment]
@key-dev this is probably some other issue. Did you clear all caches in the backend and regenerate the static content?

**Comment by patrick-yi-82** [comment]
we just had this issue. app folder and lib folder is gone after clicking that button on the admin. We need to re-make the site. (we didn't have a running backup on the development server)

**Comment by DanielRuf** [comment]
@patrick-yi-82 you should probably use Git in the future.

Can you provide detailed details so se can reproduce this locally?
