### ISSUE TITLE
RequireJS sucks

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4544]
RequireJS sucks. That is my conclusion.
No way to use minified scripts that have been obfuscated or shrunk, only as is. By obfuscating JavaScript modules/scripts/whatever, we are saving up to 90% of JavaScript size, load time, you name it.

Even the bundled JS file, that is coming up at whopping 13MB, after obfuscating weighs just 1.9MB, but there is no way the damn RequireJS dig into obfuscated code!

Why didn't you choose Browserify or Webpack, or something more flexible than RequireJS?

Comparison: https://webpack.github.io/docs/comparison.html

**Comment by guz-anton** [comment]
Good conclusion. +5

Php sucks.
No way to write on JavaScript. By using nodejs we are saving up to 90% server resources.

**Comment by guz-anton** [comment]
RequireJS as a library solves just one simple task: deliver JavaScript modules to browser. Delivery without source code modification. It solves task well enough. 

Webpack is more complex tool. It allows to _preprocess_ source JavaScript code on server side before delivery to browser. And has bunch of possibilities out-of-the-box. But with nodejs on server. So you are ready include +1 tool in development process?

**Comment by devdesco-ceo** [comment]
Sure, NodeJS + Webpack would solve bunch of issues with concurrent loading of JS, JS minifications (concatenation, shrinking, obfuscating, etc).

Since M2 requires composer, which means you need shell access, and in most cases dedicated servers are used for deploying of M2, I don't see it as a problem to have extra stuff installed such as NodeJS...

With my latest experiment on server-side minification of CSS, JS and static HTML files via Perl scripting under Nginx, I was able to bring my M2 installation to a mark of 97 in Google PageSpeed ranking, and 85 points in YSlow, BWT... no matter whether I use JS Bundling along with JS Merging, or not, it still loads 120+ JavaScript files adding a huge overhead to total page load time (https://gtmetrix.com/reports/endohaus.com/HvLwlt4D).

No matter how good and/or advanced the M2 is comparing to other Open Source solutions, the top things that matter nowadays are the UX experience and site load speed. So far I've implemented all known web technologies server side (as I know), but still... lots of work has to be dome in this regard.

**Comment by andreymoskvenkov** [comment]
NodeJS is already required deployment tool of Magento 2 projects, because PHP LESS complier does not compile Javascript parts of LESS code, which is allowed by LESS documentation. So another words: Magento 2 LESS compiler does NOT compile LESS. The only one tool, which compiles LESS is - "grunt less" task, which uses NodeJS.

**Comment by DanielRuf** [comment]
Also you can always download the binaries for the server OS and put it in the PATH and use it on demand. It also works on managed hosting.

**Comment by DanielRuf** [comment]
So a compile step to run webpack build is not that hard.
CMS? Magento is a ecommerce solution (I would never call it CMS).

**Comment by DanielRuf** [comment]
Also see https://github.com/niutech/node.php
