### ISSUE TITLE
Upgraded from 2.05 to 2.06 and now can't access Web Setup Wizard

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4546]
## Steps to reproduce
1. Installed Magento 2.00 from archive.
2. Updated to 2.05 a few days ago successfully using Web Setup Wizard
3. Updated to 2.06 today using Web Setup Wizard
## Expected result
1. Ability to access System > Web Setup Wizard 
## Actual result
1. Trying to access System > Web Setup Wizard, but getting a blank page/screen
2. [Screenshot, logs] nothing logs, screenshot is a totally blank page (view source code returns 0bits)

thanks for looking into this guys

**Comment by pboisvert** [comment]
Tanya--can you have the team test this scenario?

**Comment by TClilMouse** [comment]
I am getting the error at Component Manager

**console**
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
xxx.com/setup/index.php/componentGrid/components

**PHP error log**

[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /var/www/vhosts/xxx.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73"
[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "Stack trace:"
[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "#0 /var/www/vhosts/xxx.com/httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Zend\ServiceMan...')"
[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "#1 /var/www/vhosts/xxx.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Zend\ServiceMan...')"
[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "#2 /var/www/vhosts/xxx.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Zend\ServiceMan...', NULL, 'serviceLocator', 'Magento\Setup\M...')"
[18-May-2016 00:54:32] WARNING: [pool xxx.com] child 23168 said into stderr: "#3 /var/www/vhosts/xxx.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Fr..."

**Comment by commcad** [comment]
Thanks Magento

For what its worth, I had time to restore virtual machines with 2.00, 2.01, 2.02, 2.03, 2.04, 2.05, and tried to upgrade one by one up to 2.06 and getting the same "blank page" on Web Setup Wizard upon completion for each of those.

There is however no problems upgrading any of those up to 2.05 so I'll stay there and wait for 2.07. No worries at all from this end.

Small glitch for you guys I hope :/ Anything I can do to try to help let me know here. 

Luck with the dev

**Comment by commcad** [comment]
This is Ubuntu 14.1, Apache 2.4.10, PHP5.6

Perms given to M2/*

$ chown -R :www-data .
$ find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento
$ chmod -R g+w  pub
$ chmod -R g+w  var
$ chmod go-w  app/etc

**Comment by andidhouse** [comment]
@commcad 
We also had problems using the web setup wizard to update from 2.0.5 to 2.0.6

We then changed the composer.json where 2.0.5 is to 2.0.6 saved it and run:
- composer update
- php/bin magento:upgrade
- php bin/magento setup:di:compile

and then refreshed all by with this command:

rm -rf /var/cache/nginx/\* && php bin/magento setup:static-content:deploy de_DE && php bin/magento setup:static-content:deploy && php bin/magento indexer:reindex && php bin/magento cache:clean && php bin/magento cache:flush && chown -R :www-data . && find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento

Maybe this helps.

**Comment by mazhalai** [comment]
@commcad any error on your browser's dev console?

**Comment by commcad** [comment]
Its actually installing the update just fine. No 'on-screen' errors whatsoever if upgraded in both default and developer modes and no trace in the /var/log/

Below are the last console lines:

`Please re-run Magento compile command
[2016-05-18 14:52:06 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
[2016-05-18 14:52:06 UTC] Job "setup:static:regenerate []" has started
[2016-05-18 14:52:06 UTC] Cleaning generated files...
[2016-05-18 14:52:06 UTC] Clearing cache...
[2016-05-18 14:52:06 UTC] Cleaning static view files
[2016-05-18 14:52:06 UTC] Job "setup:static:regenerate []" has been successfully completed`

Once completed, it redirect my firefox browser to:
https://www.domain.com/setup/index.php#/updater-success

Firefox console output:
`<html>
    <hread></head>
    <body></body>
</html>`

I can flush, clean, rm all of the static, reboot, and regenerate, etc etc and still getting that blank page.

Tried upgrading to 2.06 from each 2.00~2.05 also, same results. Only 2.06 bugs up my marketplace :/  loll

No worries, and thanks for trying your best to help so quick. Nice, (Go Go Magento)

**Comment by andidhouse** [comment]
We updated the way described above (our post).
I think all is good at frontend and backend except the component manager. If we click on component manager a spinning wheel is shown which never ends. Browser dev console shows the errors attached.

If we click on the error message we get redirected to this url:
http://www.ourdomain.com/setup/index.php/componentGrid/components
and this page shows:

An error occurred during execution; please try again later.

Additional information:

ErrorException

File:
/var/www/html/magento2/setup/src/Magento/Setup/Model/DateTime/TimezoneProvider.php:35
Message:
Argument 1 passed to Magento\Setup\Model\DateTime\TimezoneProvider::__construct() must be an instance of Magento\Setup\Model\ObjectManagerProvider, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Model/DateTime/TimezoneProvider.php(35): Composer\Util\ErrorHandler::handle(4096, 'Argument 1 pass...', '/var/www/html/m...', 35, Array)
#1 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): Magento\Setup\Model\DateTime\TimezoneProvider->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#2 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Setup\M...', Array)
#3 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Setup\M...')
#4 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ComponentGrid.php(90): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Setup\M...')
#5 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ComponentGrid.php(251): Magento\Setup\Controller\ComponentGrid->getTimezone()
#6 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ComponentGrid.php(237): Magento\Setup\Controller\ComponentGrid->formatSyncDate('1463574527')
#7 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ComponentGrid.php(165): Magento\Setup\Controller\ComponentGrid->formatLastSyncData(Array, Array)
#8 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/html/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/html/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#19 {main}
![screen2](https://cloud.githubusercontent.com/assets/16196483/15363997/04eeffc4-1d1b-11e6-86dc-1916160a2b9b.png)
![screen1](https://cloud.githubusercontent.com/assets/16196483/15363999/0515a78c-1d1b-11e6-9b41-f0c543435d53.png)

**Comment by commcad** [comment]
I'm following your update proc right now. Takes forever... blame google's vms for the slow net :/

Dwloading and compiling can take up to 10min sometimes lollll does it all the time but slow

Will report back

**Comment by mazhalai** [comment]
@commcad i tried on Centos and 2.0.5 to 2.0.6 has no issues. I am able to access setup wizard. What mode are you in? default, developer or production?

**Comment by mazhalai** [comment]
@andidhouse please clean your cache, and var/generation and var/di folders and try again.

**Comment by commcad** [comment]
@andidhouse , update/recompiling as per-your didn't worked here. Getting the same blank page.

@mazhalai , tried with developer & default modes only. Should I try in production mode? I'm happy to give it a go if this is what you need there

I'll rm the cache & di and see if this helps

**Comment by mazhalai** [comment]
@commcad on the blank page, are there any errors in browser console? FWIW I tried default mode, and it worked with no issues

**Comment by commcad** [comment]
Nothing at all, no errors. Just blank page, nothing compiles back-end (no cpu/nothing)

mystery... when is 2.07 coming out?!

**Comment by commcad** [comment]
Restoring vm atm, will try a last time in both default mode, and prod mode. The only mode I haven;t tried is production mode. Fingers crossed! I will report back in a few min

thx again :)

**Comment by mazhalai** [comment]
@commcad anything in your server logs? Please check both access as well error log.

**Comment by commcad** [comment]
k, will do

**Comment by ghost** [comment]
@commcad I tried the upgrade using the same environment as you and had no issues. Upgrade was successful and I could render Setup Wizard after the upgrade.

**Comment by commcad** [comment]
Inspiring ;) we'll sort it out, always did, always will!

@mazhalai - updating default mode atm. I'll get the logs screened out for anything of interest and report back in a few min.

**Comment by mazhalai** [comment]
@andidhouse please check if you auth in system config is saved, it is also in `var/composer_home/auth.json`

**Comment by andidhouse** [comment]
@mazhalai yes it is saved. 

```
{
    "http-basic": {
        "repo.magento.com": {
            "username": "c2505****",
            "password": "00808****"
        }
    }
}
```

**Comment by commcad** [comment]
@mazhalai I swear I didn't see this in developer mode. This is coming out of the 'default' mode. 

Have I broken anything?!
/var/log/system.log

`[2016-05-18 15:57:33] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3c470299521325284ed2f872fb317d47b: Please correct the XML data and try again.  [] []
[2016-05-18 15:57:33] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_331b80c99f1d265b3f83441bdff2abf85: Please correct the XML data and try again.  [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'global_notices' element cannot be added as child to 'global.notices', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'logo' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'global.search' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'user' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'menu' element cannot be added as child to 'page.menu', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'breadcrumbs' element cannot be added as child to 'page.breadcrumbs', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'formkey' element cannot be added as child to 'page.formkey', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'page.title' element cannot be added as child to 'main.top', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'messages' element cannot be added as child to 'page.messages', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'page.actions.toolbar' element cannot be added as child to 'page.main.actions', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'legal' element cannot be added as child to 'footer', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'system_messages' element cannot be added as child to 'notifications', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'unread_system_messages' element cannot be added as child to 'notifications', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'notification_window' element cannot be added as child to 'notifications', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'notification.messages' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'header.inner.left' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'header.inner.right' element cannot be added as child to 'header', because the latter doesn't exist [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'logo' tries to reorder itself towards '', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'logo', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'user' tries to reorder itself towards '', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'page.actions.toolbar' tries to reorder itself towards '', but their parents are different: 'page.main.actions' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'system_messages' tries to reorder itself towards '', but their parents are different: 'notifications' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'unread_system_messages' tries to reorder itself towards 'system_messages', but their parents are different: 'notifications' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'header.inner.left' tries to reorder itself towards '', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'header.inner.right' tries to reorder itself towards 'header.inner.left', but their parents are different: 'header' and '' respectively. [] []
[2016-05-18 15:57:33] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and '' respectively. [] []
`

**Comment by TClilMouse** [comment]
@mazhalai  
I have the same error like @andidhouse
https://github.com/magento/magento2/issues/4546#issuecomment-219925464
All cache clean/flush
rm var/di, var/generation, pub/static, var/view_preprocessed
still the same error message.

**Comment by mazhalai** [comment]
@commcad those are css/related errors. shouldn't be related to upgrade issues.

**Comment by commcad** [comment]
I'm not all that worried if the problem is on my side. The Business Plan is still stuck in a word document and I have yet received the full funding from the investors (theres some bigger bugs)

We are going LIVE on July 1st however. Gives us time here to get things squared server side. We'll re-install a fully func M2 before that anyway so... 

Was sure I FOUND a bug lollllll

I'll play with it and see if I can find what's wrong and report back here if I find anything at my end. Love 2.05 plenty btw, we're testing 3 extensions atm with it and so far so good. 

THANK YOU MAGENTO (for everything)

**Comment by commcad** [comment]
@mazhalai - I quit!!! Gave up looking for my blank page and instead re-installed Magento 2.06 from scratch. Its working fine. Apologies if this is very unhelpful in finding solution(s) to problem(s). Faster for me that way (shellfish I know)

Same problem as @seavenger and @andidhouse however. > Press SYNC and the wheel is spinning forever. Creds are in there, cache flushed, etc etc etc

We all lost our Marketplace. You guys NEED to fix this before mid June please lolll

Tc and thanks again all, mazhalai, and Magento

**Comment by piotrekkaminski** [comment]
@commcad can you let me know how much memory the server has? I've seen somewhat similar effect when running out of memory, which happened on 1GB instances.

**Comment by commcad** [comment]
@piotrekkaminski 
1vCPU with 3.75GB of memory, 25Gig SSD
Google Cloud's. Toasting the competition ;)
1. Fresh install Magento 2.06 (cleaned up both var/www/ and re-created the dB)
2. perms as follow:
- from the var/www/ folder:
- composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition domain.com
- sudo find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
- sudo find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \;
- sudo chmod u+x bin/magento
- sudo chown -R magento_user /var/www/domain.com
1. Web Setup, no sample data, (using the 'default mode' I'm assuming)
2. Set the Public and private key > Saved > Cleaned cache/di/flush all
3. Logoff/log back in
4. System > Component Manager > Sync > wheel spinning continuously

(7. We'll give this another go again tomorrow, no rush at all from this end)

**Comment by robfico** [comment]
Upgraded from 2.0.4 to 2.0.6, Component Manager page just spins, this error is output:
`PHP Fatal error:  Cannot instantiate interface Zend\\ServiceManager\\ServiceLocatorInterface`

16 GB RAM, PHP memory limit 2048 MB, PHP 5.5.31, MySQL 5.6, Apache 2.2, php-fpm

**Comment by sakamotz** [comment]
plane new install 2.0.6(Magento-CE-2.0.6-2016-05-17-03-11-27.zip),enter Component Manager page, to click [Sync] button then just spins, this error is output:

Apache error log as follows,

> PHP Fatal error:  Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /[path/to/magento2]/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73, referer: http://[myhost]/setup/index.php

Operation Browser(Chrome) Console log.

> http://[myhost]/setup/index.php/componentGrid/sync 500 (Internal Server Error)

2 GB RAM, PHP memory limit 1024 MB, PHP 5.6.20, MySQL 5.6, Apache 2.4,

**Comment by commcad** [comment]
@robfico and @sakamotz 

Issue #4575 was recently opened and is directly referenced to the spinning wheel issue that few of us are having. Might worth subscribing to this ticket for follow-up.

https://github.com/magento/magento2/issues/4575

**Comment by mazhalai** [comment]
@commcad  @robfico  @sakamotz the spinning wheel issue has been fixed in 2.1.0-rc1. Have you had a chance to try it out?

**Comment by robinhuy** [comment]
I have same errors, in Setup Wizard I cannot click to anything except Home button. I see log in browser:
- Component manager: 
  `angular.js:7715 GET localhost/setup/index.php/component-grid 500 (Internal Server Error)`
- System upgrade: 
  `angular.js:7715 GET localhost/setup/index.php/select-version 500 (Internal Server Error)`
- System config, when save config: 
  `angular.js:7715 POST localhost/setup/index.php/marketplace/save-auth-json 500 (Internal Server Error)`

I use Magento 2.0.6 install from Github, server Ubuntu 14.04, php5.5.9 + mysql 5.6.30.

I tried Magento 2.1.0-rc1 from Github but require php > 5.5.20, so I install on Ubuntu 16.04 + php7.0. Then I can go to Component Manager but I cannot pass the Readiness Check (I passed all Readiness Check when install Magento but when install extension it cannot check anything)

**Comment by nigelcopley** [comment]
Had this issue on 2.0.6 and just upgraded to 2.07 and the same issue.
- Keep getting 500 internal server error on /setup/index.php/componentGrid/sync
- Also get an angular warning on /setup/index.php/component-grid
-  -  The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

When checking error_log in setup folder i'm also getting a zend error, although it doesnlt seem to directly relate to this as the timings are different 
- Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in xxx/xxx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

Site runs on centos, mem is 2048m, everything else running great

**Comment by mazhalai** [comment]
@robinhuy what errors in Readiness check.
@caleoroco these issues have been fixed in 2..1.0-RC1

**Comment by nigelcopley** [comment]
@mazhalai thanks.  is 2.1.0 rc1 ready for a production site?

**Comment by mazhalai** [comment]
@caleoroco no not yet.

**Comment by nigelcopley** [comment]
@mazhalai OK, thanks again.  Is there a workaround for now on the current version?

**Comment by mazhalai** [comment]
@caleoroco unfortunately significant changes have been made within [setup](https://github.com/magento/magento2/tree/develop/setup)

**Comment by robinhuy** [comment]
@mazhalai when I install magento 2.1.0-rc1,
I pass all Readiness Check (step 1 of installation)

> PHP Version Check
> Your PHP version is correct (7.0.4-7ubuntu2).
> 
> PHP Settings Check *
> Your PHP settings are correct.
> 
> PHP Extensions Check
> You meet 14 out of 14 PHP extensions requirements. Show detail
> 
> File Permission Check
> You meet 4 out of 4 writable file permission requirements. Show detail

But Readiness Check before Install Component (all fail except Check Component Dependency)

> Check Updater Application Availability
> Updater application is not available. Hide detail
> 
> Download and install the updater.
> 
> For additional assistance, see updater application help.
> 
> Check Cron Scripts
> Cron script readiness check failed. Hide detail
> 
> Error from Setup Application Cron Script:
> Cron job has not been configured yet
> Other checks will fail as a result (PHP version, PHP settings, and PHP extensions)
> 
> Error from Updater Application Cron Script:
> Cron job has not been configured yet
> 
> For additional assistance, see cron scripts help.
> 
> Check Component Dependency
> We found conflicting component dependencies. Hide detail
> 
> For additional assistance, see component dependency help .
> 
> Need Help?
> PHP Documentation
> PHP Version Check
> Your PHP version is . The required PHP version is . Hide detail
> 
> Download and install PHP from www.php.net using this PHP Documentation.
> 
> For additional assistance, contact your hosting provider.
> 
> PHP Settings Check *
> For additional assistance, see PHP settings check help .
> 
> Need Help?
> PHP Extension Help
> PHP Extensions Check
> missing PHP extensions. Hide detail
> 
> The best way to resolve this is to install the correct missing extensions. The exact fix depends on our server, your host, and other system variables. 
> Our PHP extension help can get you started.

Here is warning from Chrome console:

> The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

**Comment by mazhalai** [comment]
@robinhuy looks like you do not have the crons setup, Please see http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html

We need these crons for upgrading magento, enabling/disabling/installing/uninstalling modules etc.

**Comment by commcad** [comment]
@mazhalai 

Confirmed, the Marketplace works beautifully in 2.1.0rc, super cool. I mean: SUPER COOL! Thanks 

Now if you can personally push out Magento 2.1 before mid-June I promise I'll send you as many gift vouchers from your favourite website :) Go Go Magento!

**Comment by TClilMouse** [comment]
@mazhalai 
I still have the spinning wheel issue after upgrade to M2.1. No error message in browser console. 

rm -rf var/di
rm -rf var/generation
rm -rf pub/static/_requirejs
rm -rf var/view_preprocessed
rm -rf pub/static/frontend
rm -rf pub/static/adminhtml
find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento

**Comment by micwallace** [comment]
Issue still exists in version 2.1.1. So far Magento 2 isn't inspiring confidence :-(

**Comment by hocomadvies** [comment]
Hi,

I experience the spinning wheel issue with a 2.0.9 install. Is there any chance to get that fixed? So I can use the sync option in the Component Manager?
I'm getting 
http://my_magento2.com/setup/index.php/componentGrid/sync 500 Internal Server error angular.min.js (line 77) 
Is there a way to fix this?

**Comment by jpcsguru** [comment]
Issue is in 2.1.2 as well

**Comment by hocomadvies** [comment]
In 2.1.2 I had it working fine. Until I added a module using the CLI after that it stopped working and giving the spinning-wheel again.

**Comment by CallumBrankin** [comment]
Added module, spinning-wheel.

**Comment by kevinjavitz** [comment]
ya same issue here, the component manager needs to fail more gracefully or not fail at all if some module is installed via cli (or perhaps the module has some missing package information in composer.json that the component manager doesn't like?)

posted issue here: http://magento.stackexchange.com/questions/145498/magento-2-component-manager-wont-load-componentgrid-components-times-out

**Comment by ghost** [comment]
Same with ver. 2.1.4. Stopped working after I added a modulo using the CLI.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by PGLDK** [comment]
Same error magento 2.1.4 Web setup wizard returns 500 internal server error and blank screen.

**Comment by amansrivastava** [comment]
do we have any fix for this ? Web setup gets 500 response, error looks like "Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface"

**Comment by bnymn** [comment]
I am getting the following error when I run `bin/magento setup:upgrade`.

```
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /var/www/magento2.2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/magento2.2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Zend\\ServiceMan...')
#1 /var/www/magento2.2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Zend\\ServiceMan...')
#2 /var/www/magento2.2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(232): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Zend\\ServiceMan...', NULL, 'serviceLocator', 'Magento\\Setup\\M...')
#3 /var/www/magento2.2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Setup\\M...', Array, Array)
#4 /var/www/magent in /var/www/magento2.2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

**Comment by brideo** [comment]
This seems to be related to instantiating the `Magento\Setup\Model\Installer` or `Magento\Setup\Model\InstallerFactory` class for me.

You can see in the construct of `InstallerFactory` it depends on the class `ServiceLocatorInterface`.

I don't really want to spend time debugging the internals of the Magento_Setup module so have just switched my dependency.

**Comment by grago** [comment]
Hi, i am being unable to access Extension Manager, url `/setup/index.php/extensionGrid/extensions` keeps loading forever and extensions won't show up. What can i do? Thanks in advance.
