### ISSUE TITLE
Setup:upgrade does not work with custom mysql port

### ISSUE THREAD

**Issue by pixelplant** [magento/magento2#4548]
Hello

There's a blocking issue when you use a **custom mysql port** and run **php bin/magento setup:upgrade**

The schema install/update part calls on the DbValidator's **checkDatabaseConnection** method which does not pass the custom mysql port defined in app/etc/env.php so the update schema will fail.
It only happens when Magento tries to call the "information_schema" database. The connection to the Magento database works fine.

The call is done in this file, https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php
in the method checkDatabaseConnection

As you can see, there is no port passed to the call so using a custom one will not work.

```
        // establish connection to information_schema view to retrieve information about user and table privileges
        $connection = $this->connectionFactory->create([
            ConfigOptionsListConstants::KEY_NAME => 'information_schema',
            ConfigOptionsListConstants::KEY_HOST => $dbHost,
            ConfigOptionsListConstants::KEY_USER => $dbUser,
            ConfigOptionsListConstants::KEY_PASSWORD => $dbPass,
            ConfigOptionsListConstants::KEY_ACTIVE => true,
        ]);
```

Hardcoding the port directly in this call allowed us to proceed with the upgrade. The same issue is present in the Enterprise version of Magento (at least version 2.0.2 as I have not been able to upgrade yet).

Thanks,
  Radu

**Comment by mazhalai** [comment]
@pixelplant could be related to #4275 and #2735, however created ticket MAGETWO-52981 to investigate and fix.

**Comment by pixelplant** [comment]
@mazhalai Yes, it's related mostly to #2735, so we need a way to either allow the usage of the 'port' config for both the site and the updater and prevent it being specified in the 'host' config, or allow it only in the 'host' config (in the format 'host:port') and throw an error if the 'port' option is also specified.

**Comment by piotrekkaminski** [comment]
related https://github.com/magento/magento2/issues/3529

**Comment by KrystynaKabannyk** [comment]
Hello @pixelplant, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by tkn98** [comment]
@KrystynaKabannyk: Can you share the references in the repository regarding this fix changes?

**Comment by nicoflemming** [comment]
Same issue with ssl_ca parameter. So when you are using mysql-ssl connection setup:upgrade wont work, because while connecting to information_schema the ssl_ca parameter is omitted.

**Comment by nicoflemming** [comment]
@magento-cicd2 can you also fix that?
