### ISSUE TITLE
Base image placeholder issue

### ISSUE THREAD

**Issue by Bravarg** [magento/magento2#4549]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. In admin panel Stores -> configuration ->  Catalog -> Catalog -> Product Image Placeholders. Attach new picture for "base image".
## Expected result
1. New product image placeholder should be new uploaded image.
## Actual result
1. There are still old placeholder.
2. On frontend catalog product page there are still basic placeholder 
   ![screenshot_32](https://cloud.githubusercontent.com/assets/11926404/15349942/fa3f65e6-1cde-11e6-9806-eddf7959f422.png) But take a look, that in meta data there are correct new placeholder path 
   ![screenshot_148](https://cloud.githubusercontent.com/assets/11926404/15349955/0aa1a70a-1cdf-11e6-96bd-4f4274b8781a.png)
   Looks like there is an issue in method Magento\Catalog\Helper\Image::getPlaceholder($placeholder) that handle the placeholder path from 'Magento_Catalog::images/product/placeholder/' . $placeholder . '.jpg'.

**Comment by katmoon** [comment]
Hi @rawick 

Thank you for such a good issue description. I could easily reproduce the bug and created `MAGETWO-53036` ticket to fix it.

Thanks,
Kateryna.

**Comment by ghost** [comment]
This issue appeared to be resolved in 2.1.2 but is back in 2.1.3.

**Comment by TClilMouse** [comment]
Confirmed issue in 2.1.3

**Comment by tac2catdev** [comment]
I'm getting it on 2.1.2

**Comment by simonrl** [comment]
I am also getting it on 2.1.2;
my v 2.1.2 was installed on October 6th with composer, but still has the old lines as seen in the fix in vendor/magento/Block/Product/View/Gallery.php

**Comment by tac2catdev** [comment]
So looks like getDefaultPlaceholderUrl() is also called in the getUrl() function of Magento/Catalog/Helper/Image.php on Line 519.  

May or may not be the core issue, and not sure what the submission process is, so just posting here.

**Comment by siliconalchemy** [comment]
For whatever reason this fix was pushed to develop branch but never made it into the 2.1 branch.

**Comment by JesseEnd** [comment]
This is still an issue in 2.1.4

**Comment by tadhgbowe** [comment]
Thanks for the update in this folks. I can confirm the product page does not work in CE v2.1.4. Other pages like the category page will work. So for now what we've done is overwrite the base placeholder images themselves in our theme. So create this folder path:

app/design/frontend/[VENDOR]/[THEME]/Magento_Catalog/web/images/product/placeholder

Then in the placeholder folder you need:
image.jpg
small_image.jpg
thumbnail.jpg

Obviously to overwrite base via the Admin Panel > Stores > Configuration > Catalog would be ideal but at least we have a workaround for now.

It's such a shame we don't get to see where all these tickets end up. For example where is MAGETWO-53036? It sometimes feels like we're getting to the final hurdle but somehow not reaching the finish line.

Laters.
Tadhg :-)

**Comment by petertindemans** [comment]
Thanks for sharing the workaround tadhgbowe!

**Comment by jonathan-martz** [comment]
This is still an issue in 2.1.7

**Comment by mattgreenfield** [comment]
Me too, as this fix has been sat in 'develop' since 25 July, do we have any idea when it will go live?

**Comment by Gammatesting123** [comment]
This is still an issue in 2.1.8

**Comment by magento-engcom-team** [comment]
@OlehWolf thank you for your report.
The fix for this issue is already fixed in 2.2.0 release

**Comment by aruntilak2** [comment]
exception(s):
Exception #0 (Magento\Framework\View\Asset\File\NotFoundException): Unable to resolve the source file for 'frontend/Aumika/default/en_US/Magento_Catalog/images/product/placeholder/.jpg'
