### ISSUE TITLE
final price does not include swatch prices

### ISSUE THREAD

**Issue by luukskeur** [magento/magento2#4551]
My first issue,
## Steps to reproduce
1. Create a customizable product;
2. Add some different configurations with different prices;
3. Add customizable options with different prices;
4. Move (in xml layout) final price render block outside of form (name="product.price.final").
## Expected result
1. Final price including all custom options prices and swatch prices.
## Actual result
1. Final price without swatch prices.

I used the code below to show the price on a different location outside of the form (on single-product view page). It does change when I select different options (customizable options) but the price does not change when I choose another swatch which did work when I used this block inside the form.

`<block class="Magento\Catalog\Pricing\Render" name="product.price.final" after="columns">
                <arguments>
                    <argument name="price_render" xsi:type="string">product.price.render.default</argument>
                    <argument name="price_type_code" xsi:type="string">final_price</argument>
                    <argument name="zone" xsi:type="string">item_view</argument>
                </arguments>
            </block>`

This is the exact same result I get when I use the FinalPrice class in `Magento\Catalog\Pricing\Price\FinalPrice`

**Comment by antboiko** [comment]
Hi @luukScheur , could you please advise me what Magento version are you running?

Thanks,
Anton.

**Comment by luukskeur** [comment]
Hi @antboiko, I'm using version 2.0.5.

**Comment by magento-engcom-team** [comment]
@luukScheur, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
