### ISSUE TITLE
In multiple website when create invoice mail send from default website email and default website sender name 

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#4552]
In multiple website when create invoice and shipment for other website order (not default website) that time tick "Email Copy of Invoice", so mail send that take default website sender name and sender email address.

Also issue when click in "Send Email" button,adding comment and update order status mail send.

**Comment by NadiyaS** [comment]
Hi @pareshe,
described bug is not reproducible on 2.0.7 version. Please upgrade your version to 2.0.7 (if you have lower version) or provide more details to reproduce it.

Thanks

**Comment by pareshe** [comment]
I have updated comment please test like that.

**Comment by veloraven** [comment]
@pareshe is this issue still actual?
If it is, please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.
Please close this issue if it is not valid anymore.

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
