### ISSUE TITLE
In multiple website Sale order grid column "Grand Total (Base)","Grand Total (Purchased)" display default website currency not store or website currency

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#4553]
In multiple website Sale order grid column "Grand Total (Base)","Grand Total (Purchased)" display default website currency not store or website currency

**Comment by NadiyaS** [comment]
Hi @pareshe ,
thanks for reporting this issue. It is already being tracked by MAGETWO-54384 ticket.
We added additional case from your description.
This issue will be closed as duplicate of  #4980.

**Comment by Gorkyman** [comment]
@NadiyaS was this issue resolved in 2.1.2? Because we can still see it in 2.1.1.

**Comment by maderlock** [comment]
Possible cause and fix in #5036
