### ISSUE TITLE
Desktop spelling - Desctop

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4557]
Desktop has been spelt 'Desctop' a few times. 

![screen shot 2016-05-18 at 16 05 37](https://cloud.githubusercontent.com/assets/8895777/15363912/600acb94-1d12-11e6-866f-ef0a826764f1.png)

I will create a pull request once I've got my forked branch sorted.

**Comment by MomotenkoNatalia** [comment]
Hi @BenSpace48 !
Thanks for pointing on this issue. We are waiting for your Pull Request.

**Comment by BenGlassAtlas** [comment]
@MomotenkoNatalia I have created a pull request for the files in lib - https://github.com/magento/magento2/pull/4583 

I couldn't replicate the spelling in the blank theme so I presume these have been fixed recently.

**Comment by MomotenkoNatalia** [comment]
@BenSpace48 thanks for pull request. I am going to close this issue and create the internal task to process your PR.
