### ISSUE TITLE
Cannot edit customer address data.

### ISSUE THREAD

**Issue by crantron** [magento/magento2#4558]
When one imports user data via a spreadsheet and specific fields aren't included you cannot edit those specific fields in the admin or user account. 

Example: Imported data via a csv for many clients and State (regarding Address) was not included. Now when the user or admin tries to add the state in web interface a red box around the state input is displayed with the error message
![screen shot 2016-05-17 at 2 45 33 pm](https://cloud.githubusercontent.com/assets/3859969/15366253/4e707f58-1cd8-11e6-911c-305c80178eec.png)

If this wasn't enough detail please let me know.

**Comment by sevos1984** [comment]
This is a known issue (internal ticket MAGETWO-53134), thanks for posting

**Comment by slavvka** [comment]
@crantron, the issue has been fixed and delivered into develop. Please see c105a16

**Comment by crantron** [comment]
@slavvka thanks man! we are upgrading at lunch!
