### ISSUE TITLE
Cannot update Magento 2 EE from 2.0.5 to 2.0.6

### ISSUE THREAD

**Issue by micheese** [magento/magento2#4561]
This is the error I got : 

_Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 Problem 1
- The requested package magento/product-enterprise-edition 2.0.6 exists as magento/product-enterprise-edition[2.0.5] but these are rejected by your constraint._

**Comment by micheese** [comment]
{
    "name": "magento/project-enterprise-edition",
    "description": "eCommerce Platform for Growth (Enterprise Edition)",
    "type": "project",
    "version": "2.0.5",
    "license": [
        "proprietary"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-enterprise-edition": "2.0.6",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "2.3.*",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\Framework\": "lib/internal/Magento/Framework/",
            "Magento\Setup\": "setup/src/Magento/Setup/",
            "Magento\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\Sniffs\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\Tools\": "dev/tools/Magento/Tools/",
            "Magento\Tools\Sanity\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\TestFramework\Inspection\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\TestFramework\Utility\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\ToolkitFramework\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

**Comment by mazhalai** [comment]
@michiz05000 is this on web setup wizard?

**Comment by haricl** [comment]
I am getting the same error, when I run from command line.

**Comment by micheese** [comment]
@mazhalai , it's with the command line interface.

**Comment by mazhalai** [comment]
@michiz05000 and @haricl Please do not post EE issues on github. Please use the partner portal. When you do, please post what steps did you do to upgrade.

`composer require magento/product-enterprise-edition 2.0.6 --no-update` and `composer update` should work.

**Comment by c-moyer** [comment]
I got the same error.  Anyone have a solution for this or know where to look

**Comment by mboukhanoufa** [comment]
Hello,
I got the same error for the CE. Anyone have a solution?

**Comment by patrickpeng2091** [comment]
hello ,  i got the same error for the magento 2.0.6 to magento 2.0.7 .

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/magento2ce 2.0.6 -> satisfiable by magento/magento2ce[2.0.6].
    - magento/product-community-edition 2.0.7 requires magento/framework 100.0.9 -> satisfiable by magento/framework[100.0.9].
    - don't install magento/framework 100.0.9|remove magento/magento2ce 2.0.6
    - Installation request for magento/product-community-edition 2.0.7 -> satisfiable by magento/product-community-edition[2.0.7].

**Comment by patrickpeng2091** [comment]
I downloaded magento version : https://github.com/magento/magento2/archive/2.0.6.zip .

Can not  update ?

**Comment by mazhalai** [comment]
@admin-it  @mboukhanoufa @patrick4u please do not post on closed issues. 

For EE versions, please post on the partner portal.
