### ISSUE TITLE
Onepage checkout doesn't show full content after reutrning from PayPal

### ISSUE THREAD

**Issue by hugh-optoma** [magento/magento2#4563]
This issue is reproducible in 2.0.6.
## Steps to reproduce

[Complete Steps]
1. Enable Onepage Checkout
2. Enable Paypal Express Checkout
3. Checkout through Onepage Checkout and get redirected to PayPal
4. Cancel and return to store. (Get redirected to Cart page)
5. Click "Proceed to Checkout" to Onepage Checkout
## Expected result
1. Onepage Checkout page should show full content including progress bar and shipping address form.
## Actual result
1. Progress bar and shipping address from do show show as expected.

**Comment by pboisvert** [comment]
@asemenenko can you have the team investigate?

**Comment by alena-marchenko** [comment]
Hi @hugh-optoma 

Please provide us with screenshot of the issue. Do you check out as a guest or registered customer? Are you able to reproduce the same issue on the develop branch?

**Comment by hugh-optoma** [comment]
I cannot reproduce this issue in my latest development environment. Please feel free to close this issue.
