### ISSUE TITLE
Topmenu template is not loaded from the original module

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#4564]
## Steps to reproduce
1. Install Magento from `2.0` branch.
2. Create a module with a preference for the `Magento\Theme\Block\Html\Topmenu`

`<preference for="Magento\Theme\Block\Html\Topmenu" type="MyCompany\Theme\Block\Html\Topmenu" />`
1. Create your custom class:

```
<?php

namespace MyCompany\Theme\Block\Html;

class Topmenu extends \Magento\Theme\Block\Html\Topmenu
{
    protected function _addSubMenu($child, $childLevel, $childrenWrapClass, $limit)
    {
        // my stuff
    }
}
```
1. Reload your page.
## Expected result
1. Custom class is used
2. No error
## Actual result
1. Custom class is used
2. An error is triggered: 

> main.CRITICAL: Invalid template file: 'html/topmenu.phtml' in module: 'MyCompany_Theme' block's name: 'catalog.topnav' [] []
## Cause

The template of this block is not prefixed with the module name: https://github.com/magento/magento2/blob/develop/app/code/Magento/Theme/view/frontend/layout/default.xml#L69

Instead of : 

`<block class="Magento\Theme\Block\Html\Topmenu" name="catalog.topnav" template="html/topmenu.phtml" ttl="3600" before="-"/>`

It should be:

`<block class="Magento\Theme\Block\Html\Topmenu" name="catalog.topnav" template="Magento_Theme::html/topmenu.phtml" ttl="3600" before="-"/>`

Could you please confirm that is a bug so I can make a PR to fix that.

The bug was discovered in this Magento SE post: http://magento.stackexchange.com/questions/115988/are-we-forced-to-rewrite-a-template-in-magento2-when-rewritting-a-block

**Comment by digitalpianism** [comment]
Thanks to @fooman here's a PR that is fixing the issue: https://github.com/magento/magento2/pull/1895/files

**Comment by vkorotun** [comment]
If someone interested in the subject, please join the discussion here: http://magento.stackexchange.com/questions/115988/are-we-forced-to-rewrite-a-template-in-magento2-when-rewritting-a-block/

**Comment by magento-engcom-team** [comment]
Closing, as issue seems to be fixed.
