### ISSUE TITLE
Products must have weight set to be added to cart.

### ISSUE THREAD

**Issue by peec** [magento/magento2#4566]
If you add products with no weight to cart and go to checkout (check "Product has no weight"), Shipping step from the Checkout wizard is gone. 
This is really bad if you for example forget to add weight to a product. Weight should not be needed for a product to be shipped. Such conditions should be handled within the shipping method. Weight is not always the way to calculate e.g. shipping so it should not be a requirement to add it to checkout.

Tested in: 2.0.6
## Steps to reproduce
1. In admin: Add a new product, say that the product have no weight, or skip filling in weight.
2. In frontend: Try to add this product to cart ( not any other products with weight ).
3. When product is added to cart, go to checkout.
## Expected result
1. Get into "Shipping" step in checkout wizard OR get an error that products with no weight can not be added to checkout.
## Actual result
1. Hops right to "Review & Payments". Not possible to fill in address fields. Shipping step from the wizard is gone and not visible!

**Comment by mbrinton01** [comment]
@peec please review against this other issue and let us know if you are seeing the same result.  Virtual products do not require shipping. Can you verify the product type?  https://github.com/magento/magento2/issues/4533

**Comment by peec** [comment]
Aha.
If i check "This product has no weight". The product is converted to "Virtual product". If i let weight be empty it's a "Simple product".

Still, if you add it to cart and go into checkout, the same bug happens as described above.

![image](https://cloud.githubusercontent.com/assets/131546/15669191/482fce0e-271f-11e6-89bf-17f9406b5092.png)

**Comment by peec** [comment]
I think is is expcted since products with no weight should not be possbile to ship to a shipping address. So closing this.
