### ISSUE TITLE
Can't cancel the order

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4567]
## Steps to reproduce
1. Install Magento 2.0.6
2. Place an order
3. Try to cancel it via admin
## Expected result
1. Order is cancelled
## Actual result
1. Error is shown: "You have not canceled the item."

There is no button or anything else to cancel item(s) ordered. How should order normally be cancelled?

**Comment by NadiyaS** [comment]
Hi @werdlv ,
This bug is not reproducible neither on 2.0.6 nor on 2.0.7 versions.
Please provide more detailed steps to reproduce. E.g. ordered product type, shipping method, payment method, etc.

**Comment by jsakars** [comment]
@NadiyaS there isn't much to add really - simple product, any of standard shipping, payment option. I am not able to reproduce it on 2.0.7

**Comment by NadiyaS** [comment]
@werdlv ,
so if this bug does not exist on latest Magento version then we can close this issue.
Feel free to reopen this issue if you think you have encountered a bug on latest Magento version.

**Comment by romeof1980** [comment]
hi @werdlv  ,
we were able to reproduce it in Magento 2.1.2
It's not really an issue, because you probably tried to cancel an order with status "processing".
you can indeed cancel an order with status "pending" but not with status processing, because that means you've probably already printed some docs (i.e. the invoice) or there has been a transaction.

try to check if that can be the problem. It's a normal behaviour.

cheers!

**Comment by franciskim** [comment]
I've been able to reproduce it in 2.1.7 and have recorded it as an animated gif here: [Magento 2 Issue – Can’t Cancel Orders](https://franciskim.co/magento-2-issue-cant-cancel-orders/)

**Comment by germaike** [comment]
@franciskim Did you get an answer on your problem. Having the same issue on my install as well. It is also a 2.1.7.

**Comment by LiamKarlMitchell** [comment]
Still happening. Magento 2.2.0
Trying to cancel a Processing order. (Same if it's Held).
User does have cancel permission.

If it helps any.
Order is in processing stage, to be canceled.
Payment Method: Paystation

**Comment by MLucaciu** [comment]
Still happening on Magento 2.2.5

**Comment by sarfarazbheda** [comment]
Also facing the same issue.
Order status: Processing
Cart price rule was applied while placing an order.

When tried to cancel the order from the Mass action, Magento throws below error:

-- SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`production`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DELET), query was: INSERT INTO `salesrule_customer` () VALUES ()

When tried to cancel the order from the order detail page, showing below error:
-- You have not canceled the item.

Temporary solution:
Deleted applied_rule_ids field's data from sales_order table and canceled order.

Please look into this and resolve it.

Thanks.

**Comment by ghost** [comment]
@sarfarazbheda, could you provide more details? Which Magento version do you use? How did you set up  cart price rules? Please provide verbal description or at least screenshots.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by sarfarazbheda** [comment]
Using Magento Version: 2.2.5 [Upgraded from Magento 2.1.8]

Find the screenshots for reference:
![screenshot2018-12-14at10 40 20am](https://user-images.githubusercontent.com/30382023/50397096-07dd2b00-0794-11e9-9539-af2e439f2c1e.png)
![cart-price-rule](https://user-images.githubusercontent.com/30382023/50397206-cbf69580-0794-11e9-94b3-8dc289555f2e.png)

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-4567-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-4567-2-3-0.instances.magento-community.engineering/admin](https://i-4567-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-4567-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-4567-2-2-7.instances.magento-community.engineering/admin](https://i-4567-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@sarfarazbheda, thank you for details that you provided. Unfortunately, I was not able to reproduce it on 2.3.0.

**Comment by LiamKarlMitchell** [comment]
@magento-engcom-team give me 2.2.0 instance

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell. Thank you for your request. I'm working on Magento 2.2.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell, here is your [Magento instance](https://i-4567-2-2-0.instances.magento-community.engineering).
Admin access: [https://i-4567-2-2-0.instances.magento-community.engineering/admin](https://i-4567-2-2-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LiamKarlMitchell** [comment]
"One or more indexers are invalid. Make sure your Magento cron job is running."
How can I add a product to the home page?

**Comment by LiamKarlMitchell** [comment]
@magento-engcom-team How can I add a processing status to the order and partial payment?
Is there a way to install plugins or access the DB?

**Comment by elioermini** [comment]
I've recently had the same issue on 2.2.7 when a promo rule was applied and the order was in processing status, deleting the value in the sales_order table as suggested by @sarfarazbheda fixed it but of course, should be fixed the issue in the code.

**Comment by ghost** [comment]
HI @elioermini this is expected behavior, if you have order in status processing, please do the credit memo.
note: also not able to reproduce on 2.2-develop and 2.3-develop branches

**Comment by elioermini** [comment]
@engcom-backlog-nazar looks like this issue has been fixed here, thanks https://github.com/magento/magento2/issues/19230

**Comment by juharintanen** [comment]
![image](https://user-images.githubusercontent.com/16240211/73822906-d5f42000-47ff-11ea-8975-69644e9d7205.png)

Mage 2.3.4

**Comment by adarshkhatri** [comment]
It happened in 2.3.3-p1 too. 

The order had invoice and the invoice was in pending mode. I could cancel the invoice then the "Cancel" button was populated for that order. Then I hit the cancel button then the above error thrown. In `exception.log` I see this:

> [2020-05-20 23:29:38] report.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`torna_bahadur_kc_dici_tmp2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_), query was: INSERT INTO `salesrule_customer` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`torna_bahadur_kc_dici_tmp2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_), query was: INSERT INTO `salesrule_customer` () VALUES () at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`torna_bahadur_kc_dici_tmp2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_) at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []


Upon checking the `sales_order` table, I see that `applied_rule_ids` had 25. Upon checking in the system for any catalog rule or cart rule with that ID, it looks like it's already deleted.

**Also,** I see that 25 does exist in `sequence_salesrule` table. Is this mean when deleting the `cart/catalog rule` it supposed to delete from `sequence_salesrule` table too?

**Comment by adarshkhatri** [comment]
It happened in 2.3.3-p1 too. 

The order had invoice and the invoice was in pending mode. I could cancel the invoice then the "Cancel" button was populated for that order. Then I hit the cancel button then the above error thrown. In `exception.log` I see this:

> [2020-05-20 23:29:38] report.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_), query was: INSERT INTO `salesrule_customer` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_), query was: INSERT INTO `salesrule_customer` () VALUES () at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_) at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []


Upon checking the `sales_order` table, I see that `applied_rule_ids` had 25. Upon checking in the system for any catalog rule or cart rule with that ID, it looks like it's already deleted.

**Also,** I see that 25 does exist in `sequence_salesrule` table. Is this mean when deleting the `cart/catalog rule` it supposed to delete from `sequence_salesrule` table too?
