### ISSUE TITLE
Magento_ConfigurableSampleData causing issues on Magento 2.0.6

### ISSUE THREAD

**Issue by stamster** [magento/magento2#4568]
Please refer to:
## Actual result

https://github.com/magento/magento2-sample-data/issues/19

**Comment by andimov** [comment]
@stamster
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by stamster** [comment]
@andimov 
This is just a link to original issue, that's why it is missing text desc.

https://github.com/magento/magento2-sample-data/issues/19

**Comment by veloraven** [comment]
@stamster please fill description according to the template. It will allow other users to find this issue easily.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-66682
