### ISSUE TITLE
UI Library documentation not loading/including any JavaScript

### ISSUE THREAD

**Issue by matt-bailey** [magento/magento2#4569]
I'm not sure if I'm missing something here, but when I browse the UI library (i.e. /pub/static/frontend/Magento/blank/en_US/css/docs/index.html) none of the components that depend on JavaScript work?

What I mean by that is, clicking on the Dropdown component does nothing, clicking on one of the tabs in the Tabs component does nothing.

Viewing the source code and Network tab in Chrome Dev Tools confirms the problem, there are no JavaScript dependencies being loaded.

Is this just 'how it is' (what is the UI library documentation for then?), or is the documentation not being compiled correctly by styledocco?

**Comment by zanilee** [comment]
Hi @matt-bailey!

This is known issue and it is present in library documentation only.
The documentation issue will be fixed in MAGETWO-34178

**Comment by magento-engcom-team** [comment]
@matt-bailey, thank you for your report.
We've created internal ticket(s) MAGETWO-82332 to track progress on the issue.

**Comment by matt-bailey** [comment]
1 year 5 months later? Oh Magento...

**Comment by magento-engcom-team** [comment]
Hi @matt-bailey

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@matt-bailey, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
