### ISSUE TITLE
Backend fail after update message comes up

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4570]
Same again, **I really need help**... I can not set up all again. To much is done already.
https://github.com/magento/magento2/issues/4034#event-622530346

I tried already:
./bin/magento indexer:reindex
./bin/magento setup:static-content:deploy
./bin/magento cache:flush
## Steps to reproduce
1. Update message ist coming
2. Backend fails
## Expected result
1. Backend should not fail

Actual result
-- https://www.dropbox.com/s/9e6p1v3nzchgrjh/error.jpg?dl=0

**Comment by katmoon** [comment]
@flipflap could you please update the issue title?

Thanks,
Kateryna.

**Comment by stamster** [comment]
Try running `magento setup:upgrade`

**Comment by flipflap** [comment]
Thanks stamster, but didn't help.

The backend loaded after login doesn't include html header and other code, it is only the notification message without anything else. Is there a way to turn off  notification messages without using the backend?

**Comment by mazhalai** [comment]
@flipflap can you please post image else where, cannot access dropbox. Also, what is your latest version of Magento, OS, PHP version, etc.

**Comment by flipflap** [comment]
The screen is here:
http://webgarten.ch/error.jpg

I found a temporary solution. I removed all code between containers in:
- adminhtml_notification_block.xml
- adminhtml_notification_index.xml
- default.xml

Path:
"vendor/magento/module-admin-notification/view/adminhtml/layout"

Then the backend works again.

**Comment by stamster** [comment]
Here's a shell script I built for easy Magento2 management, if you need it.

http://stamster.github.io/magento2-commander.sh

Save in Magento root dir, and give execute permission with `chmod +x magento2-commander.sh`

**Comment by flipflap** [comment]
Thanks. I can use that for other things. 
But this seems to be a bug in the module-admin-notification

**Comment by mazhalai** [comment]
We have created MAGETWO-53101 to investigate and fix. @flipflap can you please give more details about OS, webserver and version, PHP version, etc.

**Comment by flipflap** [comment]
Here are the Server Information:

Apache-Version  2.4.18
PHP-Version 5.5.33
MySQL-Version   5.6.30
Architektur x86_64
Betriebssystem  linux
Perl-Version    5.10.1
Kernel-Version  2.6.32-531.23.3.lve1.3.6.el6.x86_64

**Comment by flipflap** [comment]
Hurra, the problem is solved after changing the time zone setting :-)

**Comment by cspruiell** [comment]
@flipflap its sounds like you fixed the problem with your environment. Closing this issue.
