### ISSUE TITLE
Calculation error on tax while usinge discount code

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#4571]
Hello,

we had setup german tax and also tax on shipping cost. If we try to use a discount who will reach the full amount of shopping cart discount not working for shipping cost tax. It always display shipping tax on shopping cart... could anyone help?

It seems that disocunt wont apply to shipping cost tax. Only tax... :(

I had also attach all settings.
So we had setting the tax page:
![bildschirmfoto 2016-05-19 um 13 56 42](https://cloud.githubusercontent.com/assets/1537343/15392781/ae36862a-1dc9-11e6-975a-33dbecd327a2.png)

the shipping page:
![bildschirmfoto 2016-05-19 um 13 56 56](https://cloud.githubusercontent.com/assets/1537343/15392782/ae36b0d2-1dc9-11e6-9409-0e63a5edf254.png)

setup a discount:
![bildschirmfoto 2016-05-19 um 13 57 18](https://cloud.githubusercontent.com/assets/1537343/15392784/ae3a5d7c-1dc9-11e6-82f5-cc7b44063c06.png)

screen of checkout:
![bildschirmfoto 2016-05-19 um 13 57 34](https://cloud.githubusercontent.com/assets/1537343/15392783/ae36d0b2-1dc9-11e6-8fb1-7f607b20c187.png)
Here you can see it will use discount but the tax from shipping cost cant discount ...and i dont know why?

**Comment by klarlichter** [comment]
Hello, get someone any idea? I am looking maybe 6 hours since now but cant find out what going wrong...:(
Please anwer on that issue:  #4581

**Comment by choukalos** [comment]
Stack exchange is probably a better forum to ask this question on.

Hey @piotrekkaminski  looks like this is an M1 question / potential issue.  I'm closing and tagging you so you can slot/follow up if it's in M1.x mainline.

**Comment by klarlichter** [comment]
Hello, it is a bug on magento2 too. So could anyone help? Because it is a mistake on calculation.
