### ISSUE TITLE
Updating store specific product data causes product to de-associate with other stores

### ISSUE THREAD

**Issue by joates-ldg** [magento/magento2#4573]
## Steps to reproduce
1. Install Magento from `2.0.4` tag.
2. Setup three websites, stores and views
3. Create a product and associate the product to all three stores
4. Post an update to a view specific api endpoint updating the title of the product
   /rest/{view}/V1/products

{"product":{"name":"{title}","sku":"{sku}"},"saveOptions":true}
## Expected result
1. The product should title should update for that store and remain associated to all 3 websites.
## Actual result
1. The product updates but is only associated with the store the product was updated via.

**Comment by joates-ldg** [comment]
Any feedback on this?

**Comment by duhon** [comment]
Hello @joatesTS 

This issue has not reproduced in develop branch. Try to update your code base (2.1-rc, e.g.) and if you still have any issue, please reopen this one
