### ISSUE TITLE
Category's products count issue in all store view scope

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#4574]
## Steps to reproduce

Steps to reproduce the issue:

1.We have two web sites (website1,website2) in single instance.

website1-store1-storeview1

website2-store2-storeview2

2.Create 2 simple products:

product1 (assigned to website1),

product2 (assigned to website2)

3.create category in website2 & assign product2 for that category.

4.Now select all store view scope.the count in left side will be 1 and in category products grid will be 0.

expected result should be both side 1.

It is an bug or default behavior?
![m2](https://cloud.githubusercontent.com/assets/7636894/15392480/f2bd880a-1de4-11e6-8a94-24073b782943.png)

**Comment by katmoon** [comment]
Hi @sivajik34 

Thank you for reporting the issue and separate thanks for such a good description.
I've created internal ticket `MAGETWO-53046` to process this issue.

Thanks
Kateryna.

**Comment by sivajik34** [comment]
I think we need to modify following lines of code in  file path: Magento\VisualMerchandiser\Model\Category\Products

/*\* @var \Magento\Catalog\Model\ResourceModel\Product\Collection $collection */
        $collection = $this->getFactory()->create()
            ->getCollection()
            ->addAttributeToSelect([
                'sku',
                'name',
                'price',
                'small_image'
            ]);
        if ($store) {
            $collection->addStoreFilter($store);
        }

Can you give me your feedback?

**Comment by katmoon** [comment]
Hi @sivajik34 

Your assumption is correct. 
The issue has been fixed in the end of last year in `MAGETWO-47465` and should be available in develop branch.

Thanks,
Kateryna.
