### ISSUE TITLE
Error when clicking "view" in "Orders"

### ISSUE THREAD

**Issue by Rickverweij** [magento/magento2#4576]
I use Magento 2.0.6.

I get the following error when i click on "view" in the "Order" tab:

*The stars is my domain.

Fatal error: Uncaught Error: Call to undefined method Magento\Sales\Api\Data\OrderExtension::setShippingAssignments() in /home/deb87338/domains/********_/public_html/dev/vendor/magento/module-sales/Model/OrderRepository.php:171 Stack trace: #0 /home/deb87338/domains/**_*****_/public_html/dev/vendor/magento/module-sales/Model/OrderRepository.php(85): Magento\Sales\Model\OrderRepository->setShippingAssignments(Object(Magento\Sales\Model\Order)) #1 [internal function]: Magento\Sales\Model\OrderRepository->get('9') #2 /home/deb87338/domains/**_*****_/public_html/dev/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array) #3 /home/deb87338/domains/**_*****_/public_html/dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array) #4 /home/deb87338/domains/**_*****_/public_html/dev/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext in /home/deb87338/domains/**_******/public_html/dev/vendor/magento/module-sales/Model/OrderRepository.php on line 171

**Comment by NadiyaS** [comment]
Hi @Rickverweij ,
looks like you have old generation files. 
Please upgrade your magento by using next command `php bin/magento setup:upgrade`.
And if you still have this problem please provide more detailed steps to reproduce.

**Comment by Rickverweij** [comment]
Easy but good solution. Worked for me. Thanks!
