### ISSUE TITLE
Catalog & cart price rule conditions - no longer can filter by attributes

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4577]
## Steps to reproduce
1. Upgrade from Magento 2.0.5 to 2.0.6
2. Try to add catalog or cart price rule
## Expected result
1. User can set different conditions - category, color, manufacturer etc. the same as it was possible in earlier M2 releases
## Actual result
1. User can set **only** product category and attribute set conditions

This seems like a bug - otherwise it's backwards incompatible. Not sure whether it was like this in 2.0.5 and 2.0.4 but it sure wasn't in e.g. 2.0.2

**Comment by voleye** [comment]
Hi @werdlv, I have just checked out v2.0.2 and observe the same behavior.

**Comment by katmoon** [comment]
Hi @werdlv 

You can add more attributes to be used for catalog or price rules in attribute settings:
Admin > Stores > Attributes > Product > the attribute > Storefront Properties > Use for Promo Rule Conditions
Please check that this property is set to Yes.

Thanks,Kateryna.

**Comment by jsakars** [comment]
@katmoon that's correct. Weird that most of the product attributes were available in conditions select in early M2 version.
