### ISSUE TITLE
Ups shipping method CNY vs RMB currencycode problem

### ISSUE THREAD

**Issue by tgoeminne** [magento/magento2#4578]
## Steps to reproduce
1. Use UPS shipping method set origin country to China
2. [Example] shipping settings origin country = China
3. UPS price not working it is not showing up, in debug can see that prices are collected but currencycode used by ups in china is RMB

I added the following line of code in Carrier.php

protected function _parseXmlResponse($xmlResponse) ....

....
$responseCurrencyCode = (string)$shipElement->TotalCharges->CurrencyCode;

 if($responseCurrencyCode == "RMB"){
                        $responseCurrencyCode = "CNY";
}

After adding this line and override the currency code it works and prices are shown..

**Comment by alena-marchenko** [comment]
Hi @tgoeminne 

We've created MAGETWO-53795 internal ticket regarding this issue.
Thank you

**Comment by alena-marchenko** [comment]
Hi @tgoeminne 

Closing the issue, the fix has been delivered to develop branch.
