### ISSUE TITLE
Country of Manufacture drop down is limited

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#4579]
Magento v2.0.5 / PHP 7
## Steps to reproduce
1. Configure M2 config to only sell to 1 (or 2 or 3 etc) countries.
2. Click on "country of manufacture" drop-down in product profile.
## Expected result
1. A list of all countries (regardless of which countries we want to sell to) should be displayed
## Actual result
1. Country list is restricted to the "Allowed Countries" list, as per the site configuration.

This above problem does not manifest in Magento 1 - it works as expected (i.e.: even if we have configured the site only to sell to "France", we can configure a product to be manufactured by _any_ country).

Cheers

Elliot

**Comment by antboiko** [comment]
Hello @hgpit , thanks for reporting this issue. We've created internal ticket MAGETWO-53159 to fix this.

Best,
Anton.

**Comment by hgpit** [comment]
We have just downloaded Magento v2.1 with the expectation that this fix would have been in - unfortunately it was not.

Considering the sizeable fees charged for EE, how can this fix not have found its way into v2.1? This is such a ridiculous bug/oversight it renders the entire platform useless to any merchant wishing to use "country of manufacture" product options. Are we missing something here?

Regards

**Comment by spyrule** [comment]
As of version 2.1.3, this problem still exists.  Why someone thought that Country of Manufacture should have anything to do with selling region is beyond me. Stores sell products which are manufactured if MANY other countries then where they sell it. ><  This should just be a list of every country in the world.

**Comment by matin73** [comment]
problem still existt in 2.1.5 . - please fix this problem!

**Comment by afavata** [comment]
Issue is still present in 2.1.7.... please provide urgent update or work around.
Thanks

**Comment by matin73** [comment]
realy many bad bugs in magento 2 and nobody of core team is fixing it ... this is soooooooo bad!

**Comment by spyrule** [comment]
@matin73 M1.0 went through a lot of teething problems too. I do agree that a monthly patch cycle would be more beneficial until 2.2 or 2.3 stable.

**Comment by seanscott49** [comment]
Having the same issue and googled and found this. I am going to create my own country of manufacturer attribute and add in only the countries I need.

**Comment by matin73** [comment]
@spyrule: there are some realy major bugs in magento 2 - most of them known für more than 1 year! and it seems magento core team is ignoring most of them. i have already lost 2 customers and have bad reputation because they say i am selling rubish. Can i recommend magento 2? no, not at all ...

**Comment by fxdegroot** [comment]
This problem is fixed in version 2.2.

In the meantime you can easily fix it yourself by making a preference of the source model class (Magento\Catalog\Model\Product\Attribute\Source\Countryofmanufacture) and replace loadByStore() by load().

**Comment by Yan-Studio-WEB** [comment]
> In the meantime you can easily fix it yourself by making a preference of the source model class (Magento\Catalog\Model\Product\Attribute\Source\Countryofmanufacture) and replace loadByStore() by load().> 

@fxdegroot 
Can you please be more specific how can i do that my Magento is 2.1.9 the steps i mean

**Comment by magento-engcom-team** [comment]
@hgpit thank you for your report.
The fix for this issue is already fixed in 2.2.0 release

**Comment by magento-engcom-team** [comment]
@hgpit, thank you for your report.
The issue is already fixed in 2.2.0
