### ISSUE TITLE
Magento 1.0.5. - Discount on shipping cost tax conflict

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#4581]
Hello,
it seems if we are using any discount code that discount will working but it will not working on shipping tax ... it seems that shipping tax need to pay because discount not working on shipping tax and I dont know why :(

Please review example image.
![bildschirmfoto 2016-05-19 um 13 57 34](https://cloud.githubusercontent.com/assets/1537343/15397993/52e47340-1de2-11e6-8a6a-c2b3b4d58824.png)

**Comment by pboisvert** [comment]
Chuck--not sure this is you or Andrii (for checkout)

**Comment by klarlichter** [comment]
Hello, anyone know a solution? :?
More details I also post there...:  #4571

**Comment by choukalos** [comment]
Per discussion with @cpartica this is really a question or potential issue for Magento 1.x.  CC'ing @piotrekkaminski
