### ISSUE TITLE
Calculation issue on Checkout while using discount

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#4585]
Hello,

I don't understand why you had close my ticket 
#4571 and #4581

Because it not only related to magento 1.  It also cause on magento 2 and I really like to know how we can solve that. 
Because if we try use full discount shipping tax will not subtract. Customer had to pay only shipping tax. Why ? Could you help to solve please ?:(

@cpartica it is also a magento2 issue. But I don't know how we can solve. Could you maybe help?

**Comment by klarlichter** [comment]
Hello, we had review and had found that magento2 also had that tax calc bug. but we had still solved and found a great solution.

**Comment by flancer64** [comment]
Probably I had the same issue - wrong tax when shipping discount is used. Magento v 2.1.0 is still affected. My fix is in https://github.com/magento/magento2/pull/5858

**Comment by veloraven** [comment]
@klarlichter thank you for your feedback.
Please, provide the used Magento version.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
