### ISSUE TITLE
Notifications Section - Please fix links in Actions column

### ISSUE THREAD

**Issue by addison74** [magento/magento2#4586]
See the screenshot from bellow. Go to Notifications Section in your backend. In Actions column there are three links which are one after other. Please use a list in html code in order to get every link as a row. It is a visual bug.

![links](https://cloud.githubusercontent.com/assets/8360474/15409842/5c537df8-1e1f-11e6-8903-ab2cb2a1057d.jpg)

**Comment by MomotenkoNatalia** [comment]
@ADDISON74 Thanks for reporting this issue! Internal ticket MAGETWO-53318

**Comment by MomotenkoNatalia** [comment]
@ADDISON74  Internal ticket MAGETWO-53318 is closed and delivered to mainline. Please let us know if you still have an issue
