### ISSUE TITLE
get storeview on list.phtml

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#4587]
Hello,

how it is possible to get the storeview on list.phtml via little php code in list.phtml

Hope someone could help.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
