### ISSUE TITLE
Prices of related products on PDP changes according to product custom options.

### ISSUE THREAD

**Issue by ant-workaholic** [magento/magento2#4588]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Need add custom options (with some extra prices) to some product, also add some related products to the product.
3. Visit the product page.
4. Specify some custom option.
5. Refresh page.
6. Specify some option again and look to prices of related products.
   For me this  reproduces after flushing cache in my browser (in Chrome after Shift+F5)
## Expected result
1. When customer specify custom option, only the product price should change.
## Actual result
1. Now, changes all prices for related products too.

**Comment by pboisvert** [comment]
Anton--please have the team check this issue?

**Comment by katmoon** [comment]
Hi @ant-workaholic 

Thank you for the comprehensive description of the issue. This is a very good find! 
I've created internal ticket `MAGETWO-53135` to fix the issue.

Thanks,
Kateryna.

**Comment by chiragayartops** [comment]
It is solved?

**Comment by chiragayartops** [comment]
I use magento2
I have same issue please give me reply.

**Comment by katmoon** [comment]
Hi,

The issue is in progress now.

Thanks,
Kateryna.

**Comment by xmav** [comment]
Issue has been fixed

**Comment by slavvka** [comment]
The issue has been also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by janeblonde** [comment]
The solution above works but the files are located:
/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml
/vendor/magento/module-catalog/view/frontend/templates/product/view/options.phtml

**Comment by elenleonova** [comment]
The issue has been delivered to 2.1.3 and 2.0.11 today.

**Comment by SolRey** [comment]
/module-catalog/view/frontend/templates/product/view/form.phtml
**Changed**
var priceBoxes = $('[data-role=priceBox]');
**To**
var priceBoxes = $('.product-info-price [data-role=priceBox]');

This worked for me. It selects only product priceBox in priceBoxes rather than all priceBoxs on the page.

**Comment by Puru2016** [comment]
I am using Magento ver. 2.1.7, and I have followed above changes but still my issue is not fixed.
In my case related products price showing the main product price on product details page.

Please advice on this.

**Comment by Puru2016** [comment]
@magento-engcom-team: I am not able to get you here. please explain more

**Comment by Puru2016** [comment]
Thanks to fix this issue, but what should I do to add these changes in my Magento ver. 2.1.7?

**Comment by Puru2016** [comment]
Awaiting your response on the above issue

**Comment by magento-engcom-team** [comment]
The issue has been fixed in 2.1.8 Please check this commit: https://github.com/magento/magento2ce/commit/dbfa7b8f7d7107ab178d3f6c6af773777197cadf

**Comment by Puru2016** [comment]
Thanks magento team 👍

After update the  below two files from magento 2.1.8 to 2.1.7, my problem is solved:-
/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml
/vendor/magento/module-catalog/view/frontend/templates/product/view/options.phtml

thanks again

**Comment by BezV8** [comment]
I seem to be experiencing this issue on 2.2.2
The prices of all products listed on the page are the same as the main product, and changing the option selected updates the price of all products on the page.

This does not happen with Simple Products, only configurable.

I tried the fix suggested by SolRey, but while this fixed the price duplication it also prevented me from selecting any options for the product.

**Comment by roma-glushko** [comment]
Got the same on Magento 2.2.5

**Comment by haljeshi** [comment]
I have the same issue at 2.2.6

**Comment by Muhamann** [comment]
I have this issue at 2.3.5p

On PDP, when selecting a size / simple-product in configurable-select, it changes all prices on the page, including upselling and related products.

How can i fix this?

**Comment by OkropNick** [comment]
I have the same issue on version 2.4.2
