### ISSUE TITLE
Minicart showing blank value till products are not added in cart

### ISSUE THREAD

**Issue by qwerty7869** [magento/magento2#4591]
In 2.0.6 magento version also, minicart shows blank value till products are not added in the cart.

Steps to reproduce
1. Open home page and you will see the issue as described in below image
![miniccart_issue](https://cloud.githubusercontent.com/assets/2813660/15417336/57c6e268-1e72-11e6-9d79-ef1b6e170d64.png)

Expected Result
1. Minicart value should be 0 instead of blank value.

Please help to resolve this issue.

**Comment by qwerty7869** [comment]
If anyone has the fix for this issue than please help it.

**Comment by ishakhsuvarov** [comment]
@qwerty7869 Thank you for reporting. This issue is already fixed in the `develop` branch, could you please check and report if it works fine for you?

**Comment by qwerty7869** [comment]
Can you please tell me in which commit the issue was fixed?

**Comment by ishakhsuvarov** [comment]
@qwerty7869 You may try to cherry-pick commit [`eec3cf1`](https://github.com/magento/magento2/commit/eec3cf17bc5deae71c83c797d1339de46cf6905f), it should fix some of the mini-cart issues.

**Comment by qwerty7869** [comment]
@ishakhsuvarov  - On merging commit eec3cf1 in my setup getting error as TypeError: _.each is not a function. Please help me out to resolve this problem.

**Comment by erikhansen** [comment]
I'm also experiencing similar issues, so I'd be curious to hear the full solution for this.

**Comment by JDavidVR** [comment]
i'm having sale problem with magento 2.0.7, my php versión is 7.0.x

**Comment by magento-engcom-team** [comment]
@qwerty7869, thank you for your report.
The fix for this issue is already available in the 2.1, 2.2 and develop branch. See commit https://github.com/magento/magento2/commit/eec3cf17bc5deae71c83c797d1339de46cf6905f for reference (it is not compatible with future versions).
