### ISSUE TITLE
get some variable on product detail page

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#4592]
Hello,
we try to fetch some information on product detail page...
We try to get a attribute from product with:

`$labelDeliveryTime = $_product->getResource()->getAttribute('delivery_time')->getStoreLabel();
`
but that wont work...:(

We also try to get product price
with tax:

`$_product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();`

and product price without tax:

`$_product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();`

but also wont work.
Could anyone let me know how it is possible?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
