### ISSUE TITLE
Paypal Website Payments Pro Hosted Solution iframe 

### ISSUE THREAD

**Issue by karmalis** [magento/magento2#4595]
## Steps to reproduce
1. Install Magento from `2.0.6` (and/or previous) release.
2. Setup Paypal Website Payments Pro Hosted Solution (using a sandbox account)
3. Add any product to cart
4. Attempt a checkout using a "test" card
## Expected result
1. Magento opens an iframe where you can enter the card details
## Actual result
1. The iframe opens in the actual window with the following message coming in from Paypal:
   "Paypal This transaction can't be processed. Please pay with another card."

Magento itself seems to be working fine (it creates the order, contacts Paypal and receives an iframe link properly), however it is extremely difficult to debug and figure out on when and why the iframe is opened on the main window and automatically submitted.

Is this something that would rather be pushed to Paypal?

**Comment by pboisvert** [comment]
@asemenenko can you take a look at this one? Seems like PayPal issue entirely but perhaps you can easily confirm.

**Comment by alena-marchenko** [comment]
Hi @karmalis 

It seems that test card, that you are using is rejected by PayPal and you should contact them regarding the card that can be used for test purchase. Please ensure that Debug option is enabled for PayPal Website Payments Pro Hosted Solution and provide us with debug.log, that contains response from PayPal for us to be able to investigate this further.

**Comment by alena-marchenko** [comment]
Closing this issue due to no response, please reopen when you have an update.

**Comment by harshadgoswami** [comment]
I have same issue received same response "Paypal This transaction can't be processed. Please pay with another card."

My debug.log output as follow, please help me.

[debug.log.txt](https://github.com/magento/magento2/files/628799/debug.log.txt)
