### ISSUE TITLE
PUT doesn't UPDATE Cart item price

### ISSUE THREAD

**Issue by mPanasiewicz** [magento/magento2#4596]
HI,
I've got a problem while PUT the card item. WHat I am doing:
1) FInd all products of the cart: # GET: http://my_host.dev/index.php/rest/V1/carts/8/items ( I don't know yet how to find client cartId....) I found correct number by increasing the number from 1.
2) the answer was: 

> [
> {
> "item_id": 11,
> "sku": "MH07-M-Green",
> "qty": 1,
> "name": "Hero Hoodie",
> "price": 54,
> "product_type": "configurable",
> "quote_id": "8",
> "product_option":{
> "extension_attributes":{
> "configurable_item_options":[{"option_id": "90", "option_value": 53 }, {"option_id": "138",…]
> }
> }
> }
> ]

2) Update cart item price by:

> {
>   "cartItem": {
>     "itemId": 11,
>     "sku": "MH07-M-Green",
>     "qty": 2,
>     "name": "Hero Hoodie",
>     "price": 1000,
>     "productType": "configurable  ",
>     "quoteId": "8"
>   }
> }

3) I get not Updated item price in cart. My response is the same as in point 1). I have to say also that I can delete Items from cart. 
Any solution for this?

Thank you

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
