### ISSUE TITLE
"Price vs Destination" value for "Condition" field in "Table Rate " Shipping method is not working.

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#4597]
Hi there, 

For "Table Rate" shipping method on setting "condition" field as "Price vs Destination" and later after importing csv file with correct values to a website doesn't display correct shipping prices for table rate method while creating new order, it will always display first shipping price value. 
Here I have attached screenshot for csv I have imported for a website shipping methods.
![p19](https://cloud.githubusercontent.com/assets/12557241/15423850/06b2832a-1e9d-11e6-924f-fdac983f74d7.PNG)

Here in all cases it shows shipping cost as "2.5"

**Comment by karanbhomiagit** [comment]
Facing the same issue myself.
Please look into this and acknowledge it as a bug.

**Comment by alena-marchenko** [comment]
Hy @ruby10 

We've created MAGETWO-53773 internal ticket regarding this issue

**Comment by alena-marchenko** [comment]
Hi @ruby10 

Closing the issue, the fix has been delivered to develop branch.
