### ISSUE TITLE
The Responsive not working device under 480px

### ISSUE THREAD

**Issue by zin-mi** [magento/magento2#4598]
Here my code and it not working in the breakpoint under 480px with Magento Breakpoint default

```
//
//  Mobile vertical
//  _____________________________________________

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__xs) {
    .minicart-wrapper .block-minicart {
        padding-top: 10px;
    }
}

//
//  Mobile
//  _____________________________________________
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__s) {
    .minicart-wrapper .block-minicart {
        padding-top: 0px;
    }
}
```

The padding still: padding-top: 0px when i switch to device under 480px.
Please let me know how to resolve it.

Best Regards,
Ziven.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
