### ISSUE TITLE
Left navigation not appeared after change In Anchor for category

### ISSUE THREAD

**Issue by gorillagroup** [magento/magento2#4600]
## Steps to reproduce
1. Install Magento from 2.0.6 tag
2. Create new Sub-category
3. Set In Anchor = No
4. Add products to Category and save category
5. Change In Anchor = Yes and save category
## Expected result
1. Left navigation for category appears on frontend
## Actual result
1. No left navigation for this category

**Comment by pboisvert** [comment]
@gorillagroup Please file tickets in the Partner portal so we have formal tracking and follow up
