### ISSUE TITLE
Error page on  Backend->System->Scheduled Imports/Exports tryzens->Add Scheduled Import

### ISSUE THREAD

**Issue by manaftryzens** [magento/magento2#4601]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Login to Admin
   3.Go to System->Scheduled Imports/Exports tryzens->Add Scheduled Import
## Expected result
1. New form showed up to add scheduled import
## Actual result
1. Error message appears: "Notice: Use of undefined constant FTP_BINARY - assumed 'FTP_BINARY' in /var/www/html/vendor/magento/module-scheduled-import-export/Model/Scheduled/Operation/Data.php on line 103".

**Comment by manaftryzens** [comment]
This is happening on v2.0.4 & v2.0.5

**Comment by BaDos** [comment]
Hi @manaftryzens 

Thank you for your reporting.
The public Github is only for CE version of Magento. To solve your problem, please, create a ticket via [EE support](https://magento.com/support/enterprise-edition).
