### ISSUE TITLE
Convert attribute (dropdown) to visual swatches with a lot of options

### ISSUE THREAD

**Issue by piatrouski** [magento/magento2#4602]
## Steps to reproduce
1. Add into attribute (dropdown type) through Web API more than 200 options.
2. Save this attribute as Visual Swatch. 
## Actual result
1. Error message appears: "Notice: Undefined offset: 131 in /chroot/data/stage/_SERVER_/html/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 178".
2. [Screenshot](http://piatrouski.xyz/screenshots/clip-2016-05-20-14-01-12-84877899.png)

**Comment by oserediuk** [comment]
Hello @piatrouski ! Could you clarify steps to reproduce? Which version code do you use?

**Comment by redboxmarcins** [comment]
Same here

**Comment by piatrouski** [comment]
@oserediuk Please, close this issue. Shortly, need increase memory_limit & max_input_vars. It was my first step (like as Magento 1) but unfortunately, my hosting provider doesn't support .htaccess directives for overwriting PHP values (it was surprising for me).
