### ISSUE TITLE
Issue: In overriding of SwatchRenderer.js

### ISSUE THREAD

**Issue by priyankagarg8** [magento/magento2#4604]
Want to override SwatchRenderer.js in my module.

I have done below implementation for it.

->putted SwatchRenderer.js in mymodule 'view/frontend/web/js' folder 
->created file 'requirejs-config.js' in /view/frontend and wrote below code:

```
var config = {
     map: {
    '*': {
        swatchRenderer: 'Ds_Sdcp/js/SwatchRenderer'
        }
    }
}
```

My Module SwatchRenderer.js works if I remove core SwatchRenderer.js

But when I put core js SwatchRenderer.js again module js does not work.

Please help!

My module is stuck due to this problem.

Thanks in advance!

**Comment by Vinai** [comment]
The github issue tracker is for reporting bugs or technical issues only. Please ask "how do I" of "why" type of questions on [Magento SE](http://magento.stackexchange.com/) or the official [community forum](http://community.magento.com/).  
Magento is keeping an eye on those sites, too, and you will often find core team members responding, in addition to the many community contributors.

**Comment by xmasti** [comment]
zzzz
