### ISSUE TITLE
magento 2, custom widget parameter type = "textarea"

### ISSUE THREAD

**Issue by mvistas** [magento/magento2#4606]
I create my custom widget and I want one parameter to be a textarea.
If I define my parameter as a textarea, like this:

```
<parameter name="text" xsi:type="textarea"  visible="true" sort_order="3" >
   <label translate="true">Text</label>
</parameter>
```

I got this error:"Element 'parameter', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'textarea' of the xsi:type attribute does not resolve to a type definition."

How can I use a text area in a custom field? Thank you

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
