### ISSUE TITLE
Add blur event on pincode text-box in shipping address field on checkout page

### ISSUE THREAD

**Issue by pratiksonawadekar** [magento/magento2#4607]
Hi,

I am newbie to magento 2.0 . Currently  I want to add an 'on blur' event in the shipping address pincode tab on checkout page. Can any one help me out here

**Comment by pboisvert** [comment]
The github issue tracker is for reporting bugs or technical issues only. Please ask "how do I" of "why" type of questions on Magento SE or the official community forum.

**Comment by pratiksonawadekar** [comment]
How do I add an 'on blur' event to an input box on checkout page. Because I got to learn that there are 10 Interactive bindings in magento 2.0  which are as follows.

```
click: <method>—Call a View Model method when the element is clicked.
value: <property>—Link a form element’s value to a View Model property.
event: <object>—Call a method when a user-initiated event occurs.
submit: <method>—Call a method when a form is submitted.
enable: <property>—Enable a form element based on a certain condition.
disable: <property>—Disable a form element based on a certain condition.
checked: <property>—Link a radio button or check box to a View Model property.
options: <array>—Define a <select> element with a View Model array.
selectedOptions: <array>—Define the active elements in a <select> field.
hasfocus: <property>—Define whether or not the element is focused.
```

How do I use blur event? Please help.

**Comment by pboisvert** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the Community Forums or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.
