### ISSUE TITLE
SOAP API salesShipmentRepositoryV1GetListRequest returns the first order only

### ISSUE THREAD

**Issue by ohornyak** [magento/magento2#4608]
## Steps to reproduce
1. Installed Magento 2.0.4
2. Created 6 sample orders
3. Implemented the following SOAP call

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="http://localhost/magento2/soap/default?services=salesShipmentRepositoryV1">
    <x:Header/>
    <x:Body>
        <def:salesShipmentRepositoryV1GetListRequest>
            <def:searchCriteria>
                <def:pageSize>0</def:pageSize>
                <def:currentPage>0</def:currentPage>
            </def:searchCriteria>
        </def:salesShipmentRepositoryV1GetListRequest>
    </x:Body>
</x:Envelope>
```
## Expected result

It should list all the 6 orders. It used to work with 3 orders then I shipped order#000000001 and everything ceased to function
## Actual result

It lists only order 000000001

If I try to get order#000000006 explicitly like 

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="http://localhost/magento2/soap/default?services=salesShipmentRepositoryV1">
    <x:Header/>
    <x:Body>
        <def:salesShipmentRepositoryV1GetRequest>
            <def:id>000000006</def:id>
        </def:salesShipmentRepositoryV1GetRequest>
    </x:Body>
</x:Envelope>
```

it returns 
"Requested entity doesn't exist" error

In phpmyadmin SELECT `increment_id` FROM `sales_order` shows all my orders, so they are definitely there

000000006
000000005
000000004
000000003
000000002
000000001

**Comment by jonathanribas** [comment]
@ohornyak, in order to have the 6 orders in your "salesShipmentRepositoryV1GetListRequest" API call you must invoice and ship all 6 orders.

Right now you have just ship 1 order, that's why only one of them appear.

**Comment by ohornyak** [comment]
Thanks.

Is there a documentation somewhere about the shipping soap API ?
What are the mandatory fields for salesShipmentRepositoryV1SaveRequest ?
Can I do partial shipment, in other words only some of the items to ship ?
Is there a query to get carrier codes ?
`<tracks><item><carrierCode>dhl</carrierCode>`

**Comment by pboisvert** [comment]
closing as not an issue. Please consult [devdocs.magento.com](devdocs.magento.com) for documentation of SOAP API.

**Comment by ohornyak** [comment]
Shipping is not working here for magento 2.0.4, I have exactly the same message as reported in 
https://github.com/magento/magento2/issues/4319

The error message "Could not save shipment" does not provide any help

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="http://localhost/magento2/soap/default?services=salesShipmentRepositoryV1">
    <x:Header/>
    <x:Body>
        <def:salesShipmentRepositoryV1SaveRequest>
            <def:entity>
                <def:billingAddressId>8</def:billingAddressId>
                <def:customerId>1</def:customerId>
                <def:incrementId>000000004</def:incrementId>
                <def:orderId>4</def:orderId>
                <def:shippingAddressId>2</def:shippingAddressId>
                <def:totalQty>1</def:totalQty>
                <def:items>
                    <def:item>
                        <def:name>SanDisk 64GB</def:name>
                        <def:orderItemId>5</def:orderItemId>
                        <def:productId>1</def:productId>
                        <def:sku>SanDisk 64GB</def:sku>
                    </def:item>
                </def:items>
                <def:comments>
                    <def:item>
                        <def:comment>This is a test comment</def:comment>
                    </def:item>
                </def:comments>
            </def:entity>
        </def:salesShipmentRepositoryV1SaveRequest>
    </x:Body>
</x:Envelope>
```

**Comment by ohornyak** [comment]
> closing as not an issue. Please consult devdocs.magento.com for documentation of SOAP API.

Wrong link. I did search for SOAP API documentation but all what I found was the list of wsdl endpoints

**Comment by TomashKhamlai** [comment]
I cannot reproduce this on the latest 2.2.0 (branch develop).

Steps to reproduce:
1.  Create an order from admin.
2.  Create an invoice from admin.
3.  Send SOAP request to /soap/default?services=salesInvoiceRepositoryV1
with this body:
```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="{{replace to your magento_base_url}}/soap/default?services=salesInvoiceRepositoryV1">
    <x:Header/>
    <x:Body>
        <def:salesInvoiceRepositoryV1GetListRequest>
            <def:searchCriteria>
                <def:pageSize>10</def:pageSize>
            </def:searchCriteria>
        </def:salesInvoiceRepositoryV1GetListRequest>
    </x:Body>
</x:Envelope>
```
I saved data from the response and used it for the next request
4.  Send SOAP request to /soap/default?services=salesShipmentRepositoryV1
with body:
```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="{{replace to your magento_base_url}}/soap/default?services=salesShipmentRepositoryV1">
    <x:Header/>
    <x:Body>
        <def:salesShipmentRepositoryV1SaveRequest>
            <def:entity>
                <def:billingAddressId>2</def:billingAddressId>
                <def:customerId>1</def:customerId>
                <def:incrementId>000000001</def:incrementId>
                <def:orderId>3</def:orderId>
                <def:shippingAddressId>1</def:shippingAddressId>
                <def:totalQty>2</def:totalQty>
                <def:items>
                    <def:item>
                        <def:name>video</def:name>
                        <def:orderItemId>3</def:orderItemId>
                        <def:productId>1</def:productId>
                        <def:sku>video</def:sku>
                    </def:item>
                </def:items>
                <def:comments>
                    <def:item>
                        <def:comment>This is a test comment!!!!!</def:comment>
                    </def:item>
                </def:comments>
            </def:entity>
        </def:salesShipmentRepositoryV1SaveRequest>
    </x:Body>
</x:Envelope>
```

All done! The shipment was created and comment is present in shipment details.

If this issue is still actual I can try to reproduce it on Magento 2.0.4. Is this problem still actual for you?

**Comment by ohornyak** [comment]
> Is this problem still actual for you?
Don't bother with that. I gave up with Magento 2.0.4
