### ISSUE TITLE
Gallery Widget some of the options don't work

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#4609]
http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_gallery.html#gallery_minwidth

I followed this guide, and while some of the options for the gallery do work, particularly the ones listed in the view.xml file under /etc, ones like "thumbwidth" and "thumbheight" don't work. Also fotoroma supports options like "thumbmargin" but I had to go to fotorama.js and hand edit the js on line 973 where it has a value for "thumbmargin". Some better support for this would be nice I'm sure other developers would agree.

**Comment by ghost** [comment]
@samleeiii 
https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/luma/etc/view.xml#L84

``` xml
            <image id="product_page_image_small" type="thumbnail">
                <width>88</width>
                <height>400</height>
            </image>
```

You must change it. It works. 
https://github.com/magento/magento2/blob/develop/lib/web/fotorama/fotorama.js#L511
btw you can find all default options of gallery on 487-531 lines.

**Comment by anton-huz** [comment]
Hi @samleeiii 
Was suggestion from @uharbachou helpful for you?
