### ISSUE TITLE
Possible to autoplay product videos?

### ISSUE THREAD

**Issue by zerobrapsgiven** [magento/magento2#4610]
I added some videos to a product (YouTube). Right now you have to hit the play button after arriving at the video in the product media gallery. Is it possible to have it autoplay?

**Comment by pboisvert** [comment]
The github issue tracker is for reporting bugs or technical issues only. Please ask "how do I" of "why" type of questions on [Magento SE](http://magento.stackexchange.com/) or the official [community forum](https://community.magento.com/).
