### ISSUE TITLE
Order Status goes straight to Complete

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#4611]
Placed a test order and status was "Pending". Pressed the "Invoice" button, status was immediately changed to "Complete" however there are no orders under "Shipments". Invoice email was sent to account holder but no shipment email?

**Comment by jonathanribas** [comment]
@bondimedical3, I can't reproduce this with a simple product. When I invoice the order, it goes to "processing" status.

**Comment by srinivasanithin** [comment]
@bondimedical3 : This scenario appears to be related to virtual products? Can you check the product type if that was virtual/downloadable item on that order?

**Comment by bondimedical3** [comment]
Yes. The issue is with virtual/downloadable products.

**Comment by pboisvert** [comment]
Anton--assume no shipping status as nothing to ship given virtual but would like you to confirm.

**Comment by antboiko** [comment]
Hello @bondimedical3 

Correct. If order includes only downloadable/virtual products there is a notice "You don't need to select a shipping address." below Shipping Address and "You don't need to select a shipping method." below Shipping Method, so no Shipment is being created for such orders.

Best,
Anton.

**Comment by antboiko** [comment]
Hello @bondimedical3 

Correct. If order includes only downloadable/virtual products there is a notice "You don't need to select a shipping address." below Shipping Address and "You don't need to select a shipping method." below Shipping Method, so no Shipment is being created for such orders.

Best,
Anton.

**Comment by antboiko** [comment]
Hello @bondimedical3 

Correct. If order includes only downloadable/virtual products there is a notice "You don't need to select a shipping address." below Shipping Address and "You don't need to select a shipping method." below Shipping Method, so no Shipment is being created for such orders.

Best,
Anton.

**Comment by antboiko** [comment]
Hi @bondimedical3 , according to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

Thanks,
Anton.
