### ISSUE TITLE
Bug with Merge/Minify CSS

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#4612]
When you select the option to Merge and Minify CSS in the Developer section of the Admin the whole website slows down. Every page takes at least 5 minutes to load?

**Comment by pynej** [comment]
Dupe of https://github.com/magento/magento2/issues/4710
Related to merge-css generating 15MB css file.

**Comment by mslabko** [comment]
https://github.com/magento/magento2/issues/4710 is closed
@bondimedical3 please reopen it, if you still have any issues.
