### ISSUE TITLE
Magento ver. 2.1.0-rc1 - ouch

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4614]
Ouch... as in; you guys have just disintegrated the competition! THANKS for sharing this so ahead of time btw ;)

We've just imported 15,000 test products from a beaten up catalog_product.csv file and gave it a go. It didn't complain a kbit. It is blazing fast(er) and I am not getting any errors 'anywhere' while running this on a little Linux 15.10, Apache 2.4 and php 5.6 (1vCPU, 4g RAM, 1SSD). Can only imagine this thing running on a proper system lolll

Hilariously fun and exciting. Thanks to Magento and the community! Nothing of interest that I can contribute technically sadly but I'll sure tell everyone I know, at business meetings/seminars, etc.

Repeat: No errors, not even a slight CSS glitch. Run flawlessly-here anyway. Now that Magento Studios is what I call some top quality work. Essential for any serious entrepreneur out there (go ask them!)

Just wow. Grateful here

(thought a share like this would relief from seeing f n bugs reports all day long)

**Comment by adragus-inviqa** [comment]
Glad it worked for you. 
But I'm pretty sure 2.0.6 broke almost every 3rd party payment method implementation relying on additional data. Thought I share this as well.

**Comment by commcad** [comment]
i know, I saw that, pretty amazing in fact. Haven't personally tried or even sandbox'ed payment as I run this RC on a partner's key but I can clearly picture the future scene. Ecomm As It Should Be - Kudos

We're sold here. Signing this Monday morning at our partner's

**Comment by commcad** [comment]
For the curious... see highlights

http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1EE.html

**Comment by davidalger** [comment]
@commcad I'm sure everyone at Magento appreciates the positive feedback. :) Since this does not appear to be a technical issue, I am going to go ahead and mark it as closed, but thank you for sharing!
