### ISSUE TITLE
Valid PHP versions for 2.1 RC1

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#4615]
The [release note](http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1EE.html) says

> Our technology stack is built on PHP and MySQL. Magento 2.1 Release Candidate 1 (RC1) supports PHP **5.6**, **7.0.2**, and **7.0.6**. It supports MySQL 5.6.
> 
> **We do not support PHP 5.5.** 

But the [current composer.json](https://github.com/magento/magento2/blob/b366da3aee0155ffabb4772ea63f76e6e13f877e/composer.json#L11) (of 2.1 RC1) disagrees: `"php": "~5.5.22|~5.6.0|~7.0.0"`

Am I missing something here?

/cc https://github.com/magento/magento2/issues/1047

**Comment by stamster** [comment]
This is really annoying. The entire purpose of Composer is to manage dependencies. If you fail to update composer with proper information, then the entire purpose of managing dependencies is lost.

**Comment by veloraven** [comment]
Closed as this issue is already fixed - internal ticket MAGETWO-53293.
