### ISSUE TITLE
Error getting orders via REST API that returns 1+ items

### ISSUE THREAD

**Issue by samuellinde** [magento/magento2#4616]
I'm trying to fetch orders via the REST API, in this example orders with a `grand_total` within a certain span.

This is the request: `/rest/V1/orders?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=grand_total&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=80&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bfield%5D=grand_total&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bvalue%5D=90&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bcondition_type%5D=lt`

In my system, there's only one order that fits the criteria (i.e. a `grand_total` between 80 and 90). The expected data is returned for that single order, no problem there. But if I change the criteria to, say 80 to 300 which would fetch more order items, the system returns the following error:

`{"message":"Notice: Array to string conversion in \/var\/www\/html\/magento\/vendor\/magento\/framework\/Reflection\/TypeCaster.php on line 34","trace":"#0 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Reflection\/TypeCaster.php(34): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Array to string...', '\/var\/www\/html\/m...', 34, Array)\n#1 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Reflection\/DataObjectProcessor.php(115): Magento\\Framework\\Reflection\\TypeCaster->castValueToType(Array, 'string')\n#2 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Reflection\/DataObjectProcessor.php(107): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Sales\\Model\\Order\\Payment), '\\Magento\\Sales\\...')\n#3 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Reflection\/DataObjectProcessor.php(113): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Sales\\Model\\Order), '\\Magento\\Sales\\...')\n#4 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Webapi\/ServiceOutputProcessor.php(107): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Sales\\Model\\ResourceModel\\Order\\Collection), '\\Magento\\Sales\\...')\n#5 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Webapi\/ServiceOutputProcessor.php(59): Magento\\Framework\\Webapi\\ServiceOutputProcessor->convertValue(Object(Magento\\Sales\\Model\\ResourceModel\\Order\\Collection), '\\Magento\\Sales\\...')\n#6 \/var\/www\/html\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(270): Magento\\Framework\\Webapi\\ServiceOutputProcessor->process(Object(Magento\\Sales\\Model\\ResourceModel\\Order\\Collection), 'Magento\\Sales\\A...', 'getList')\n#7 \/var\/www\/html\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(160): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#8 \/var\/www\/html\/magento\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/magento\/vendor\/magento\/framework\/App\/Http.php(115): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/magento\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#11 \/var\/www\/html\/magento\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#12 {main}"}`

Issue #1578 seem to reference something similar, but when I compare the code to the current one (2.0.6), it seems to be fixed.

**Comment by choukalos** [comment]
Which version are you on?

**Comment by NadiyaS** [comment]
Hi @samuellinde ,
this issue is not reproducible on 2.0.7 version. Please upgrade your code to this version and if you still have encountered this problem, please, provide more detailed steps to reproduce.

**Comment by samuellinde** [comment]
Hi,

I can only assume that something happened in the process of migrating from 1.9.2.2. We decided to start with a clean install and import data manually instead, and now we don't have any issues anymore.
