### ISSUE TITLE
Redundant Composer Module Repository

### ISSUE THREAD

**Issue by ryantfowler** [magento/magento2#4619]
In light of [Issue 4617](https://github.com/magento/magento2/issues/4617), it would appear that either the addition of a redundant repository or some form of high availability solution (possibly a location that caches modules, so that the modules are static and not effected with any potential issues with the main repository; the cached modules could be updated as updates are made to the main repository...this would be something that could be automated, of course) would be in order. Having a single point of failure is a high liability.

Thoughts?

Thank you for your time and consideration.

**Comment by ryantfowler** [comment]
Bump. Issue is happening again. Single point of failure for the whole community is a liability.

**Comment by IvanChepurnyi** [comment]
Just use Toran proxy for synchronization for it. it is free for personal use. Very helpful for agencies to have the local setup with it. It is 5 minutes to setup and you can create a full mirror of the repository, that automatically gets updated by cron.

The same issue is happening when you use packagist packages, as GitHub might be down from time to time. Toran Proxy serves me well for this purpose.

**Comment by ryantfowler** [comment]
@Ivan, thanks for the suggestion. I think I will do that. Now what about others who don't want to do that for their individual reasons?  I don't see why Magento can't set up something similar. That way all requests for packages are being read from a mirror.

**Comment by IvanChepurnyi** [comment]
@ryantfowler I agree that Magento must build highly redundant system, but even in this cases there can be network outages near your server and you might experience downtime from your region. I just suggesting you a solution, so next time you will drink a 🍺  while repo.magento.com is down and your delivery pipeline still works as expected.

**Comment by ryantfowler** [comment]
Lol. Thank you for your suggestion. I agree with your points regarding what could lead to downtime as well. And I'll take a look at Toran, but I was mainly thinking of others. Thanks again

**Comment by tanya-soroka** [comment]
Issue has been resolved.  Please verify if you can sync with repo.magento.com 

@IvanChepurnyi we will work on the backup on the downtime issues. Thanks

**Comment by hostep** [comment]
@tanya-soroka: maybe also consider building a status page which shows if the repository is down or not (it should be automated to work properly and don't require manual work to update the status obviously).

Because right now, if the service is down, it's sometimes hard to figure out if something is wrong on our own end, or if something is wrong with the repository. If you have a status page, we can always first verify if it's a known issue.

Also: if you are going to perform maintenance to the repository and it will go down, you can announce it beforehand on the status page for example.

**Comment by tanya-soroka** [comment]
Thanks for the suggestions.  We will definitely review it.

**Comment by veloraven** [comment]
@hostep if your proposition is still actual could you please transfer it to  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests)? (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
