### ISSUE TITLE
Applying theme breaks multistore catalog navigation

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#4623]
## Steps to reproduce
1. Fresh install of Magento 2 from CPanel
2. Create 2nd root category with subcategories
3. Create 2nd website, store and store view
   Note: At this point I could visit my base url and see no categories (I didn't add and categories to the default root category) then go to my new url which didn't have styles applied to it and see my categories and subcategories.
4. Apply magento blank theme to new store view
## Expected result

New url has selected theme applied and catalog navigation shows categories with subcategories
## Actual result

New url shows the default theme (luma) and catalog navigation does not appear (remember, no subcategories in the default root category)

**Comment by vil11** [comment]
Hi @Ctucker9233 !

> Create 2nd website, store and store view

Have you configured multiple Websites with [Apache](http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_apache.html) or [Nginx](http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_nginx.html)?

> Apply magento blank theme to new store view

Have you flushed Magento cache after switching the Theme?

## 

:sunny: D Vilchynskyi, M2 QA

**Comment by Ctucker9233** [comment]
Configured with Apache and Magento cache completely flushed.

**Comment by Ctucker9233** [comment]
Any thoughts on this issue? I was able to get it working simply by including the store name in the url and disabling the "route to base url" option. I'd prefer to set it up in the way the documentation says to so that nothing could possibly break in the future.

**Comment by sshrewz** [comment]
Hi @Ctucker9233, thanks for reporting this.  We have created internal ticket MAGETWO-53774 for updating our documentation.

**Comment by Ctucker9233** [comment]
Thanks @snohe.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Applying-theme-breaks-multistore-catalog-navigation/idi-p/48453).

**Comment by Ctucker9233** [comment]
@piotrekminski seeing as this was a lack of clear documentation, this shouldn't need the improvement label. I was not requesting an improvement to Magento code. If there is a lack of clear documentation, that should be taken as seriously as a bug IMHO. Moving this to the forums will virtually guarantee that it will be forgotten about if it hasn't been fixed already.

**Comment by pboisvert** [comment]
@Ctucker9233 an internal ticket has been created for the documentation task. @xcomSteveJohnson is the owner on the ticket and will complete that task based on the documentation backlog. There is no chance that the issue being closed here will have any impact on the task in his backlog. We agree that unclear or missing documentation needs to be addressed.

**Comment by Ctucker9233** [comment]
@pboisvert Thank you for taking this seriously.
