### ISSUE TITLE
magento version 2.1.0-rc1 When i try to edit cms page at admin panel - i get 404 for rjsResolver.js 

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#4626]
all the rest js/css files  are loaded properly

at a result - the loader not present the cms page for edit 

also try 
deploy content file+flush cache

**Comment by refaelgold** [comment]
same with blocks and every time the loader gif is present

**Comment by robinhuy** [comment]
When I go Content (or Products), I get same errors (in Chrome console)
`Uncaught TypeError: Cannot read property 'provider' of undefined`
`require.js:166 Uncaught Error: Script error for: rjsResolver`

**Comment by refaelgold** [comment]
can you edit the cms page? @robinhuy  

i guess if they not answer my question so its a bug

**Comment by robinhuy** [comment]
@refaelgold no sir, I can't edit products page too.
So I'm trying with magento 2.0.7

**Comment by oserediuk** [comment]
Hello! To allow us research the issue, please, provide description according to the template.
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
