### ISSUE TITLE
bin/magento setup:upgrade fail with magento 2.0.6 to 2.1.0-RC1

### ISSUE THREAD

**Issue by quienti** [magento/magento2#4627]
## Steps to reproduce
1. composer require magento/product-community-edition 2.1.0-rc1 --no-update
2. composer update
3. bin/magento setup:upgrade
## Expected result
1. Upgrade work fine
## Actual result
1. SQL Duplicate error
   ![sans titre 3](https://cloud.githubusercontent.com/assets/7326954/15463097/54974cfc-20c7-11e6-8c88-f053d43c8e7a.jpg)

**Comment by mazhalai** [comment]
@quienti I am confused about your steps and title, did you mean `composer require magento/product-community-edition 2.1.0-rc1 --no-update`  instead? Also, did you have sample data?

**Comment by quienti** [comment]
Oops, sorry !
Bad copy / paste

I have upgrade Magento 2.0.6 to 2.1.0 RC1
After update, when I use `bin/magento setup:upgrade`, I have this error

**Comment by mazhalai** [comment]
Haven't been able to reproduce this error. Also, cannot figure out where `4-Images` is coming from. Do you have sample data or some other 3rd party modules?

**Comment by quienti** [comment]
I have a lot of customs modules, but any work with eav_attribut_group
I did not found `4-Images` in my database too

I succeed to upgrade after commenting this
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Setup/UpgradeData.php#L241-247

But not really a solution

**Comment by quienti** [comment]
Close because this is not a Magento bug apparently
