### ISSUE TITLE
Magento 2.1.0 RC1 : Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by quienti** [magento/magento2#4634]
## Steps to reproduce
1. Update 2.0.6 to 2.1.0 RC1
2. Go to Admin -> Sales -> Orders
## Expected result
1. Show Order list
## Actual result
1. Allowed memory size of 134217728 bytes exhausted
   ![sans titre 7](https://cloud.githubusercontent.com/assets/7326954/15466205/9f00a26e-20d8-11e6-9742-f8b4f75f818d.jpg)

**Comment by sergei-sss** [comment]
You php memory_limit setting is 128 Mb.
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone

> Increase the PHP memory limit to at least 768MB for normal operation or 2GB for testing.

**Comment by quienti** [comment]
I must have missed that part of the documentation , thank you !
