### ISSUE TITLE
Magento 2.1.0 RC1 : HTTPS instabilities

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4635]
## Steps to reproduce
1. Install Magento 2.1 RC1 from develop branch (Composer install)
2. Stores > Configuration > Web >  Base URL (Secure)
3. Use Secure URLs on Storefront > Set to YES
4. Use Secure URLs in Admin > Set to YES
5. Save
6. Clear cache

PS: I've also tried:
- Enable HTTP Strict Transport Security (HSTS) > YES
- Upgrade Insecure Requests > YES

Either ways I am getting the same resutls
## Expected result
1. Ability to have the backend serving using HTTPS. 
   (For inf, this only affect the backend, frontend works perfectly)
## Actual result
1. Forms are not fully loading, wheel spinning (Add New Category, Add New Products, Add New Customers to name a few)

Note 1: Everything is working beautifully in http mode. 
Note 2: The problem is only noticeable on RC1. 
Note 3: Everything is fine on all 2.0.x release versions using the same HTTPS setings
## Environment

Ubuntu 15.10 - Apache 2.4.10 - PHP 5.6 - Domain.com SSL certificate from Comodo - Firefox
Logs: Nothing complains

**Comment by mazhalai** [comment]
@commcad we have created MAGETWO-53408 to investigate and fix.

**Comment by paliarush** [comment]
@commcad Thank you for reporting the issue. However it is not reproducible on my environment : Ubuntu 14.04, Apache 2.4, PHP 7.0.6, self-signed certificate, Firefox on OSX.

I have seen the same behavior as you are describing when I had outdated JS cached by the browser (basically you updated your code base, and JS parts on the server and in the browser diverged). Could you please confirm the issue is still reproducible after browser cache is cleared?

**Comment by commcad** [comment]
@paliarush @mazhalai 

I apologize for the late reply. This github reporting tool is great but things piles up rather quickly in gmail (tabs hides the content and often goes un noticed). Again, my apologies.

You are 100% correct. Clearing the browser cache did the trick, I've reproduced this an hour ago to confirm that this was the case. Have a few vm still sitting on 2.0.6 here

I.e. When upgrading from any 2.0.6 to 2.1.0rc, the browser cache needs a desperate cleanup otherwise, yes, those please_wait wheels get pretty static ;)

Top man, pro stuff thanks bud, appreciated

 (for closure -sorry)
