### ISSUE TITLE
sampledata:deploy/remove when custom module located app/code has no composer.json

### ISSUE THREAD

**Issue by andrew-smart** [magento/magento2#4636]
## Steps to reproduce
1. Install Magento
2. Create a custom module (without composer file).
3. Try installing the sample data (bin/magento sampledata:deploy)

[ErrorException]
file_get_contents([path]/app/code/[Vendor]/[ModuleName]/composer.json): failed to open stream: No such file or directory

Although in most cases you would have a composer file it seems a trivial task to just check if the composer file exists in [app/code/Magento/SampleData/Model/Dependency.php](https://github.com/magento/magento2/blob/develop/app/code/Magento/SampleData/Model/Dependency.php#L90)

Happy to send a pull request if this is not intended behaviour to force people to create composer files though

**Comment by oserediuk** [comment]
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by robfico** [comment]
2.1.1 store, tried to remove sample data, same result:
bin/magento sampledata:remove

Warning: file_get_contents(/home/XXX/www/app/code/Smartwave/Porto/composer.json): failed to open stream: No such file or directory in /home/XXX/www/vendor/magento/module-sample-data/Model/Dependency.php on line 109

**Comment by thdoan** [comment]
I'm getting a similar error when running `magento sampledata:deploy` on Magento 2.1.1:

```
 [Exception]
  Warning: file_get_contents(path/to/app/code/Vendor/SomeModule/composer.json): failed to open stream: No such file or directory in path/to/vendor/magento/module-sample-data/Model/Dependency.php on line 109
```

The only solution I could find was https://mage2.pro/t/topic/327.

UPDATE: I just applied the patch from above and can confirm that it works :). The only difference is I modified this file: `vendor/magento/module-sample-data/Model/Dependency.php`.
