### ISSUE TITLE
Layout xml update breaks minicart.

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#4637]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Move or place Cart\Sidebar (Minicart?) block in another container through Magento_checkout_layout_default.xml. I chose header.panel.
## Expected result
1. Minicart moved but works exactly the same way.
## Actual result
1. Minicart breaks, fails to show products in dropdown, template broken.
2. Error message appears: 

```
Uncaught TypeError: Unable to process binding "if: function (){return cart().summary_count }"
Message: Unable to process binding "foreach: function (){return { data:cart().items,as:'item'} }"
Message: Unable to process binding "foreach: function (){return $parent.getRegion($parent.getItemRenderer(item.product_type)) }"
Message: Cannot read property 'simple' of undefined
```

![erro](https://cloud.githubusercontent.com/assets/19282144/15468929/ec85c1b2-20de-11e6-9aba-4734eab4d4f9.JPG)

**Comment by ishakhsuvarov** [comment]
@LiamFielding Thank you for reporting the issue. `cart().summary_count` is not used anymore in the `develop` branch, could you please update and recheck?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by jan-dh** [comment]
Have the same issue from the 2.1. master branch, any updates on this?

**Comment by hbhardik** [comment]
Having the same issue still using magento 2.1 Enterprise version. any update on this issue? That is happening when we create custom theme

**Comment by jigar48** [comment]
Having the same issue I am seeing.

I have installed the Magento 2.1.0 

I have made the custom theme and move the mini cart to custom header.

After Adding the product to cart. 

In console this error is coming 
http://prntscr.com/cqu1cd

Mini cart is display this content
http://prntscr.com/cqu1fj

Cache is enabled only mini cart dispplay totoal items

**Comment by blackworm** [comment]
I also have same problem but on Magento version: 2.0.7
http://prntscr.com/cy4lkj
Cart display:
http://prntscr.com/cy4lmx

**Comment by noprobz09** [comment]
I also have problem regarding on creating custom theme, Im using Magento 2.1.1 version.
Screenshots: 
http://screencast.com/t/Zc9phqMMQ
http://screencast.com/t/S8cETnk84

**Comment by domdambrogia** [comment]
+1

**Comment by davinanaya** [comment]
I also have problem, Im using Magento 2.1.3 version.

http://www.screencast.com/t/AN3xRUGU

**Comment by orlangur** [comment]
@jan-dh @hbhardik @jigar48 @blackworm @noprobz09 @davinanaya to bring attention just open new issue, properly formatted, stating it is for 2.1 version, referring to this one and mentioning fix is present in `develop` branch.

I see new boards dedicated for 2.0 and 2.1 came into sight recently: https://github.com/magento/magento2/projects They may help with issues in stable releases management, but it is obviously NOT possible to manage closed issues.

Another option could be to monitor comments in closed issues and reopening when necessary but we cannot rely on this until such process is established and announced. From my personal experience with various bug tracking systems reopening is only good within short amount of time, like 2-3 sprints, after that it is better to report a new issue referring to old one even if we have exactly the same steps.

**Comment by dambrogia** [comment]
@hbhardik @noprobz09 @jigar48 

I had experienced trouble with moving the minicart in a custom theme. I had the same problem and fixed it. 

The problem (for me) was I was only including the `jsLayout` argument from `app/code/Magento/Checkout/view/frontend/layout/default.xml`. I had deleted the minicart block in my xml and then tried to copy and paste the minicart block declaration from the previously mentioned `default.xml` file into another xml file I had created. But if you look around inside other files in the `app/code/Magento/Checkout/view/frontend/layout` directory, you'll find more files that prepend data to the `jsLayout` argument. In my situation, I was not including that extra data from the other files. 

The easiest way I found to include the entire `jsLayout` argument was to move the minicart in your xml before it got deleted it. 

`app/code/<My_Vendor>/Theme/view/frontend/layout/default.xml`

    <move element="minicart" destination="<my desired header container>" />
    
    <referenceContainer name="header.container" remove="true" />


The block is availble to output within my customer header:
`app/code/<My_Vendor>/Theme/view/frontend/templates/html/header.phtml`

    ....
    echo $this->getLayout()->getBlock('minicart')->toHtml();
    ....

This fixed it for me, but one last thing to note, that might be of help to some.

Inside `app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml` you can see [here](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml#L51) where the `jsLayout` argument gets rendered into json to load all of the neccessary javascript components. It might be helpful to compare the data of what magento outputs by default and what your custom theme is outputting.

**Comment by voquockhanh** [comment]
@dambrogia Thank you. It was help me a lot :D
