### ISSUE TITLE
theme settings missing in  Magento ver. 2.1.0-rc1

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#4638]
![b1](https://cloud.githubusercontent.com/assets/7636894/15471135/1a9f621e-2112-11e6-83fc-9904dca83777.png)

**Comment by sivajik34** [comment]
![b2](https://cloud.githubusercontent.com/assets/7636894/15471462/ab077e1c-2113-11e6-92ea-9869b0a4bff4.png)

**Comment by nobuttsalex** [comment]
It's now under Content > Design instead of Stores > Configuration

**Comment by sivajik34** [comment]
I seen but still layout design disturbed for product edit,theme edit etc.

**Comment by sivajik34** [comment]
i think this is new layout design.in first shot not able to digest.

**Comment by developer-lindner** [comment]
2.1.0 : Tried to change theme back to Luma -> can't even save.
