### ISSUE TITLE
Typo in module-tax/view/frontend/web/template/checkout/minicart/subtotal/totals.html

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#4640]
The variable name should be `display_cart_subtotal_incl_tax` not `display_subtotal_incl_tax` . This will show js error when you enable totoals including tax from backend.

**Comment by ishakhsuvarov** [comment]
@bgkavinga Thank you for reporting. Looks like this issue is already fixed in the `develop` branch. Could you please verify?

**Comment by bgkavinga** [comment]
Yes, it is fixed. Thank you.
