### ISSUE TITLE
search_tmp_* tables don't exist after mifrating magento to another server

### ISSUE THREAD

**Issue by lazarenkoalexey** [magento/magento2#4643]
## Steps to reproduce
1. Install Magento with sample data.
2. Move magento server ROOT folder and mysql dump to another server.
## Expected result
1. Shop works fine.
## Actual result
1. Works only home page.
   Other pages show error:
   a:4:{i:0;s:874:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.search_tmp_57430d1a62c414_37330237' doesn't exist

**Comment by stamster** [comment]
_tmp tables are defined as of type 'MEMORY', i.e. they're lost after server reboot/shutdown which is likely your case - moving to another host.

Run `indexer:reindex` from magento CLI.

**Comment by lazarenkoalexey** [comment]
Hi,
thank fo your answering!!
But while reindexing I have another error:
General error: 1366 Incorrect integer value: '' for column 'from_time' at row 1, query was: INSERT INTO `catalogrule_product`
I think is relate to wrong format column. Am I right?
Can you help with it?
Thanks

**Comment by stamster** [comment]
You can try to run my custom script: http://stamster.github.io/magento2-commander.sh
Put it in your magento root dir, and `chmod +x` it before running.

**Comment by davidalger** [comment]
@dzotic9 What is the MySql version on each of the two servers? Are they the same? Did you have any errors/warnings/notices when you imported the database onto the new server?

Nothing you've said here so far indicates there is a bug with Magento, but something getting messed up in the database migration. I've personally migrated databases from one environment multiple times (for sites which are now in production) without issue.

**Comment by lazarenkoalexey** [comment]
@**stamster** Thanks for sharing your script. It is very useful to learn order of magento cli commands

@**davidalger** Yes, I had imported from MySQL 5.7 into MySQL 5.6 but wasn't a root cause.
I use two db instances with replication. That's why an error occur with indexing. Now I solved this problem.
Thanks everybody for help :)

**Comment by wenfei158** [comment]
@dzotic9 
Can you tell me how you resolve the problem. I have encountered the same problem. I use two db instances with replication, too. Thanks.

**Comment by rempar** [comment]
@lazarenkoalexey can you share an information on how you solved this problem? I have the same issue
