### ISSUE TITLE
Use multiple template modifiers

### ISSUE THREAD

**Issue by kassner** [magento/magento2#4649]
Hi,

I have an email template with this:

```
<strong>Comments:</strong> {{var comments|nl2br}}
```

So, if the user adds an HTML tag, it is not escaped in the email template. The thing is that is not possible to combine `escape` and `nl2br` at the same time. Is there a way to achieve this without a plugin?

Thanks!

**Comment by vkorotun** [comment]
Unfortunately, no. 
Internal ticket: MAGETWO-56374

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Use-multiple-template-modifiers/idi-p/46345).
