### ISSUE TITLE
Quick question: .json suggestions of (new-to-me) packages

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4650]
I am getting an exhausting wishlist of things to get today! Can someone help me out to chose; what would make Magento 2.0.1 super happy to run reliably on a vm instance (Ubuntu preferably)? Just so we can prepare here. We have everything else (I mean mysql and php lolll)

Json is suggesting me to get below. Me think he is out of his mind lol

Do I (really really) need to install all of that to meet the baseline of Magento's?

Thanks

`magento/framework suggests installing ext-imagick (Use Image Magick >=3.0.0 as an optional alternative image processing library)

phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
phpseclib/phpseclib suggests installing pear-pear/PHP_Compat (Install PHP_Compat to get phpseclib working on PHP < 4.3.3.)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-resources (Translations of validator messages)
zendframework/zend-validator suggests installing zendframework/zend-session (Zend\Session component)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 0.5.\* to handle lazy initialization of services)
zendframework/zend-log suggests installing ext-mongo (*)
zendframework/zend-log suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-log suggests installing zendframework/zend-mail (Zend\Mail component)
zendframework/zend-math suggests installing ext-gmp (If using the gmp functionality)
zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
zendframework/zend-code suggests installing doctrine/common (Doctrine\Common >=2.1 for annotation features)
zendframework/zend-form suggests installing zendframework/zend-captcha (Zend\Captcha component)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
zendframework/zend-view suggests installing zendframework/zend-authentication (Zend\Authentication component)
zendframework/zend-view suggests installing zendframework/zend-feed (Zend\Feed component)
zendframework/zend-view suggests installing zendframework/zend-navigation (Zend\Navigation component)
zendframework/zend-view suggests installing zendframework/zend-paginator (Zend\Paginator component)
zendframework/zend-view suggests installing zendframework/zend-permissions-acl (Zend\Permissions\Acl component)
zendframework/zend-i18n suggests installing zendframework/zend-cache (Zend\Cache component)
zendframework/zend-i18n suggests installing zendframework/zend-resources (Translation resources)
zendframework/zend-mvc suggests installing zendframework/zend-authentication (Zend\Authentication component for Identity plugin)
zendframework/zend-mvc suggests installing zendframework/zend-session (Zend\Session component for FlashMessenger, PRG, and FPRG plugins)
zendframework/zend-mvc suggests installing zendframework/zend-version (Zend\Version component)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
sjparkinson/static-review suggests installing sensiolabs/security-checker (Required for ComposerSecurityReview.)
lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)`

**Comment by mazhalai** [comment]
Those are just `suggests` from the various packages that we depend on. TO read more about suggests : https://getcomposer.org/doc/04-schema.md#suggest 

Closing since this is not really a bug.
