### ISSUE TITLE
Cant set HtmlTag to "nav" (backport to 2.0 branch)

### ISSUE THREAD

**Issue by leoquijano** [magento/magento2#4651]
Hi,

I see that in #2549 an issue with using nav as an HtmlTag was fixed in the develop branch. However, when upgrading to v2.0.6, I see it still has that issue. 

Is there any chance that the fix is backported to the 2.0 stable branch? It's not a backward compatibility breaking change, and it would help some theme developers.

Thanks

**Comment by refaelgold** [comment]
waiting for solution also

**Comment by shiftedreality** [comment]
Hi @leoquijano. Thank you for your submission.

This fix will be delivered with 2.1.0 release.
Currently we don't have plans to release it with 2.0.\* patch.
If you still have any questions - feel free to reopen this ticket ore create new one.
Closed.

**Comment by leoquijano** [comment]
Hi @shiftedreality , yes, I have a question: what would it take to include it with 2.0.\* patch? It's a one line change.

**Comment by shiftedreality** [comment]
Whole development and management teams are mainly focused on delivery of 2.1.
Integration of existing fixes into 2.0.\* patches requires additional resources and marked with lower priority then delivery of stable release.
Btw, after your request we've added  it to "Patch candidates" list and it will be integrated in future patches.

**Comment by leoquijano** [comment]
Thanks!
