### ISSUE TITLE
Fatal error on newsletter

### ISSUE THREAD

**Issue by hyturkyilmaz** [magento/magento2#4652]
## Steps to reproduce
1. Use magento 2.0.6.
2. [Example] Follow panel>marketing>newsletter>add new template.
## Expected result
1. [Example] Adding new newsletter template.
## Actual result
1. [Example] Error message appears: "Fatal error: Call to a member function getId() on string in /home/bumbabic/public_html/vendor/magento/module-google-optimizer/Observer/Block/Category/AddGoogleExperimentFieldsObserver.php on line 45".
2. [Screenshot, logs]

**Comment by mslabko** [comment]
Hello @hyturkyilmaz 
This issue already fixed in 2.1-rc. Try to update your code base and if you still have any issue, please reopen this one. 
Please, follow up marketing updates
