### ISSUE TITLE
Mannually run Cron, Error

### ISSUE THREAD

**Issue by dv8nate** [magento/magento2#4654]
I've executed your crons manually,

This is the error :-
/usr/local/cpanel/bin/jailshell: -c: line 0: unexpected EOF while looking for matching `''
/usr/local/cpanel/bin/jailshell: -c: line 1: syntax error: unexpected end of file

**Comment by slopukhov** [comment]
@dv8nate thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by vzabaznov** [comment]
Hi @dv8nate , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue
