### ISSUE TITLE
Web Wizard update - Failed

### ISSUE THREAD

**Issue by dv8nate** [magento/magento2#4655]
Utilizing web wizard update, fails on Component Dependancy 

We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- magento/module-wishlist-sample-data 100.0.2 requires magento/module-wishlist 100.0.\* -> satisfiable by magento/module-wishlist[100.0.2, 100.0.3, 100.0.4, 100.0.5].
- magento/module-wishlist-sample-data 100.0.3 requires magento/module-wishlist 100.0.\* -> satisfiable by magento/module-wishlist[100.0.2, 100.0.3, 100.0.4, 100.0.5].
- magento/module-wishlist-sample-data 100.0.4 requires magento/module-wishlist 100.0.\* -> satisfiable by magento/module-wishlist[100.0.2, 100.0.3, 100.0.4, 100.0.5].
- magento/module-wishlist-sample-data 100.0.5 requires magento/module-wishlist 100.0.\* -> satisfiable by magento/module-wishlist[100.0.2, 100.0.3, 100.0.4, 100.0.5].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.2].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.3].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.4].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.5].
- magento/product-community-edition 2.1.0-rc1 requires magento/module-wishlist 100.1.0-rc1 -> satisfiable by magento/module-wishlist[100.1.0-rc1].
- Installation request for magento/product-community-edition 2.1.0-rc1 -> satisfiable by magento/product-community-edition[2.1.0-rc1].
- Installation request for magento/module-wishlist-sample-data 100.0.\* -> satisfiable by magento/module-wishlist-sample-data[100.0.2, 100.0.3, 100.0.4, 100.0.5].

**Comment by krlecarp** [comment]
Was just there myself @dv8nate .  See  #4625 .  One thing I left out at the end, make sure you reset permissions and clean the caches.

**Comment by dv8nate** [comment]
Thaks Mate,

I know how to clear the caches, How can I reset the permissions without SSH?

**Comment by krlecarp** [comment]
That's one for the bosses.  I'm sure you are already aware of their [permission document](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html), but it doesn't cover non-CLI (SSH) environments.  There has been a fair amount of discussion on non-cli, but I'm not sure where it stands to date.  

Honestly, it may be best to uninstall sample data, or reinstall using the non-sample-data version, or wait until the next release comes out when sample data will likely be supported.  My 2 cents.

**Comment by dv8nate** [comment]
I have just had my hosting provider reset permission via SSH, I have cleared the caches, with no luck. 

Looks like ill have to reinstall without sample data, which then leads to my issues logged on [#4654](https://github.com/magento/magento2/issues/4654) and [#4653](https://github.com/magento/magento2/issues/4653)

If you have any advice it would be great, unfortunately, I will need to look at another solution to meet my needs as I need a fully operational site by June 15th 

Ps I really dont want to do that I like Magento 1 im sure once the kinks are ironed out of 2 it would be a great solution.

**Comment by ghost** [comment]
@dv8nate I am pretty sure we didn't publish sample data for RC1 and I'm not sure why it shows up in the component list. The fact your versions show a mix of RC1 and 100.\* versions indicates what you can is to either:
-  Not upgrade to RC1; it's probably less stable than 2.0.7
-  During System Upgrade, set the version of each sample data component to the largest number that is _not_ RC1. I did such an upgrade that today and it worked.

@krlecarp is incorrect; the permissions documentation covers both ways to install, upgrade, and use Magento (Setup Wizard and CLI).

Please let us know if this helped.

**Comment by ghost** [comment]
Could be a [permissions issue on ping itself](http://ubuntuforums.org/showthread.php?t=2079091) or [possibly this](http://serverfault.com/questions/696281/ping-icmp-open-socket-operation-not-permitted-in-vserver), or it could be a firewall or something like that. Have you checked your firewall settings?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
