### ISSUE TITLE
Errors while editing CMS in grid with Google Analytics Experiments enabled

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#4657]
With Google Analytics Experiments enabled, CMS page settings can't be edited from the grid directly. 

When editing a page which is (already) actived for all store views, the error `[Page ID: ##] Wrong request parameters` is given. See the attached image. When editing a page which is activated for a single store view, I got a JSON error with a message saying something like `unexpected token ">"`.

Editing CMS pages from the grid does work with Google Analytics Experiments disabled in the store config.

![m2 cms grid error](https://cloud.githubusercontent.com/assets/6915990/15497759/842979ba-219c-11e6-927e-33b9f62d596b.png)

**Comment by shiftedreality** [comment]
Hi @redelschaap 

Thank you for creating this issue. 
We have created internal ticket MAGETWO-53388 to investigate it.

**Comment by shiftedreality** [comment]
Hi @redelschaap 

I was unable to reproduce this issue on latest **develop** branch.
If you still facing with it-please add more steps to reproduce, your configuration, browser version and reopen current ticket.
Closed.
