### ISSUE TITLE
product price index update by schedule not working as expected

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#4658]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Change product price index mode to `update by schedule`
3. update any product price
## Expected result
1. Now status should be re-index required
## Actual result

1.status is still ready instead of re-index required

note: catalog_product_price_cl table contains entries of product (version_id,product_id)

**Comment by katmoon** [comment]
Hi,

This is exactly how Update on Schedule mode should work. Please read more at http://devdocs.magento.com/guides/v2.0/extension-dev-guide/indexing.html

I'm closing the ticket. Please feel free to reopen if you have additional questions.

**Comment by sivajik34** [comment]
@katmoon i red the documentation.based on that it should change index status to invalid.
![index_indexers_flow](https://cloud.githubusercontent.com/assets/7636894/15683118/68d23656-277e-11e6-9d47-20ba9f071304.png)

**Comment by katmoon** [comment]
@sivajik34  Thank you for attracting attention to this diagram.

@dshevtsov This is an incorrect diagram. In Update on Schedule mode indexer does not become 'Invalid' after a single change. Instead a single change is recorded in 'change log', Status remains 'READY', changes from 'change log' are applied on schedule when cron runs.
Indexer status changes to 'Invalid' only on major changes, e.g creating a new website/store/store view that affect all products.

**Comment by sivajik34** [comment]
thank you  for your explanation.
