### ISSUE TITLE
Unable to upgrade EE from 2.0.2

### ISSUE THREAD

**Issue by luciodiri** [magento/magento2#4661]
## Steps to reproduce
1. Magento EE 2.0.2 is installed. 
2. Go to Admin->System Wizard-> System Upgrade 
3. Open version dropdown
## Expected result
1. Magento EE newer versions exist in dropdown (i.e. 2.0.6)
## Actual result
1. Only current version (2.0.2) exists in dropdown

**Comment by mazhalai** [comment]
@luciodiri please do not post EE issues here. That's what partner portal is for.
Please check if your `var/composer_home/auth.json` has the correct keys.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
