### ISSUE TITLE
Impossible to override or extend the them's etc/view.xml file from a module

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#4663]
Recently I needed to add the image sizes to re-size the product images to a certain size in a module, which i found impossible because the sizes are defined in the them/etc/view.xml.I could not find any other way to get the sizes from any other source. There should be a way to override or define a file containing all these parameters for the context of the module. so we do not have to depend on them's view.xml file.

**Comment by andimov** [comment]
@Taral-Patoliya thank you for reporting this issue.
To allow us research the issue, please, provide description according to the template.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by ronakchauhan** [comment]
Should provide proper solution for this or mention clearly that it's not possible avvording to magento standards
