### ISSUE TITLE
Cannot run web setup wizard

### ISSUE THREAD

**Issue by woakley** [magento/magento2#4664]
## Steps to reproduce
1. Click "Web Setup wizard"
## Expected result
1. Open Web Setup Wizard!
## Actual result
1. redirects to /setup/index.php/session/unlogin

**Comment by mazhalai** [comment]
@woakley what version of magento, OS and PHP? Also, can you please clear your var (everything except composer_home) and try again?

**Comment by woakley** [comment]
Magento 2.05
CentOS
PHP 5.6

Clearing var did not help.

**Comment by mazhalai** [comment]
@woakley there have been some fixes in 2.1.0-rc1 version. Can you check if it is working fine using that?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
