### ISSUE TITLE
Fail after changing value of attributes

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4665]
**Info: It happen only to attribute with time from to**
## Steps to reproduce
1. Change Value New or Spiecial Price from / to of a product
## Expected result
1. Save and change value
## Actual result
1. Product fail and can't be edited anymore

![error-attribute](https://cloud.githubusercontent.com/assets/6672673/15502144/7580c7fe-21b2-11e6-926a-77a342d2a3ff.gif)

**Comment by flipflap** [comment]
It works now after I changed time settings.

**Comment by mslabko** [comment]
Hi @flipflap ,
Could you please clarify steps if it still actual?

**Comment by flipflap** [comment]
Hi mslabko, I had to choose Central European Standard Time (Europe/Berlin) instead of GTM (Europe/Busingen). After changing this it works all well.

**Comment by mslabko** [comment]
I've tested  with different time zones (Configuration -> General -> Locale Options -> Timezone) - all work as expected. Please reopen issue if you still have issue with it
