### ISSUE TITLE
Order export process generates CSV file containing 20 records only

### ISSUE THREAD

**Issue by creatuitydevelopers** [magento/magento2#4666]
## Hello All,

We have encountered an error related to the order export process – CSV file always generates 20 records only, despite the fact that the actual number of exported records was higher.

The issue occurs on Magento EE 2.0.6.
## Steps to reproduce
1. Go to Magento Admin Panel.
2. Create more than 20 orders.
3. Go to Sales -> Orders grid.
4. Select all orders.
5. Click on Export CSV file.
6. You should see CSV file with only 20 records.
## Expected result
1. Orders CSV file should contain all selected orders.
## Actual result
1. Orders CSV file contains only 20 records.

**Comment by NadiyaS** [comment]
Hi @creatuitydevelopers ,
thank you for reporting this issue. This bug is already fixed and fix will be merged soon. Internal ticket is MAGETWO-42062

**Comment by NadiyaS** [comment]
Hi @creatuitydevelopers ,
Fix has been delivered to develop branch [23d12c9](https://github.com/magento/magento2/commit/23d12c9b1d4a161f3070a97eb85f7e1f3b6c11d4). 
You can upgrade your code from develop branch or wait until next release.
Issue is closed as resolved.
