### ISSUE TITLE
Conflicting component dependencies 2.0.6 to 2.1.0-rc1

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#4668]
## Steps to reproduce
1. Upgrade Magento to 2.0.6 using PHP 7.0.5. Remove var/di/relations.ser as per #4070 
2. Try to upgrade to RC.
## Expected result
1. Magento 2 upgraded to RC
## Actual result
1. 

We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for magento/product-community-edition 2.1.0-rc1 -> satisfiable by magento/product-community-edition[2.1.0-rc1].
- magento/module-wishlist-sample-data 100.0.5 requires magento/module-wishlist 100.0.\* -> satisfiable by magento/module-wishlist[100.0.2, 100.0.3, 100.0.4, 100.0.5].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.2].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.3].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.4].
- Can only install one of: magento/module-wishlist[100.1.0-rc1, 100.0.5].
- magento/product-community-edition 2.1.0-rc1 requires magento/module-wishlist 100.1.0-rc1 -> satisfiable by magento/module-wishlist[100.1.0-rc1].
- Installation request for magento/module-wishlist-sample-data 100.0.5 -> satisfiable by magento/module-wishlist-sample-data[100.0.5].

**Comment by mazhalai** [comment]
@miguelbalparda we already have a ticket for this internally. This issue is present only in versions using sample data. 

Internal ticket MAGETWO-52502

**Comment by miguelbalparda** [comment]
@mazhalai got it, I experienced the same issue with Magento 2.0.6 using PHP 5.6. Thank you!

**Comment by hb-github** [comment]
I have experienced the same issue  with Magento 2.0.6 , can we have any alternate solution for the same ?

**Comment by mazhalai** [comment]
@miguelbalparda  @hb-github can you please give more details steps you followed to upgrade?

**Comment by miguelbalparda** [comment]
I was using the web utility to upgrade, Magento 2 was installed using the web installer.

**Comment by mazhalai** [comment]
@miguelbalparda and every time it was with sample data correct?

**Comment by miguelbalparda** [comment]
Correct @mazhalai

**Comment by buskamuza** [comment]
@miguelbalparda , on the very first page of "Setup Upgrade", did you try to select "Other Components"?
It should allow upgrade of all additional packages, including your sample data. Or did this approach also failed?
Thanks.

**Comment by magento-engcom-team** [comment]
@miguelbalparda @ajpevers thank you for your report.
The fix for this issue is already available in release 2.1
