### ISSUE TITLE
Warning always_populate_raw_post_data should be -1 but it is already -1

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4670]
## Steps to reproduce
1. Using Update Wizard in Magento 2.0.2
## Expected result
1. Doing the Update
## Actual result
1. Warning that always_populate_raw_post_data should be -1 but it is already on -1 
   ![populate-1](https://cloud.githubusercontent.com/assets/6672673/15505254/ee90747c-21c2-11e6-8c53-e51086d6b18b.gif)
   ![populate-2](https://cloud.githubusercontent.com/assets/6672673/15505259/f2780410-21c2-11e6-8873-8cc5008eb5a8.gif)

**Comment by mazhalai** [comment]
@flipflap can you verify that no other ini files override this value?

**Comment by flipflap** [comment]
Yes, no other ini files override this value.

**Comment by mazhalai** [comment]
@flipflap we have created MAGETWO-53407 to investigate and fix, however, can you please give more details about your env? What is your OS and webserver?

**Comment by flipflap** [comment]
Servername  srv19
cPanel-Version  56.0 (build 18)
Design  paper_lantern
Apache-Version  2.4.18
PHP-Version 5.5.33
MySQL-Version   5.6.30
Architektur x86_64
Betriebssystem  linux
Pfad zu Sendmail    /usr/sbin/sendmail
Pfad zu Perl    /usr/bin/perl
Perl-Version    5.10.1
Kernel-Version  2.6.32-531.23.3.lve1.3.6.el6.x86_64

**Comment by flipflap** [comment]
Where can I find MAGETWO-53407?

**Comment by pboisvert** [comment]
This is a reference an an internal Jira ticket for us to track the fix. These are not viewable externally.

**Comment by flipflap** [comment]
Ok I see, thanks

**Comment by ghost** [comment]
If you use Apache, you can try adding this to `.htaccess`. I have never tried it but it might work:

```
php_value always_populate_raw_post_data -1;
```

Let us know if it helps.

**Comment by flipflap** [comment]
I tried to add this to .htaccess and now it works:

`php_flag always_populate_raw_post_data -1`

**Comment by veloraven** [comment]
I'm closing this issue since the problem has been solved.
