### ISSUE TITLE
"cc_type" is not coming with payment info in order data 

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#4676]
Hey there,

I am facing this issue while retrieving order data using api "/rest/V1/orders/{orderId}" ,field "cc_type" is missing in payment block . I have  used payment gateway "braintree" for this order.  Sample payment block which I am getting with order data is provided below.Please have a look and let me know if it's a bug or enhancement ,  also when solution will be out, as it acting as major blocker while developing integration when payment needs to be exported outside magento? 

"payment": {
        "account_status": null,
        "additional_information": [
            "M",
            "M",
            "M",
            "GR7X6P",
            "1000",
            "Approved"
        ],
        "amount_authorized": 45,
        "amount_ordered": 45,
        "base_amount_authorized": 45,
        "base_amount_ordered": 45,
        "base_shipping_amount": 15,
        "cc_last4": "1111",
        "cc_trans_id": "6jczhc",
        "entity_id": 43,
        "last_trans_id": "6jczhc",
        "method": "braintree",
        "parent_id": 44,
        "shipping_amount": 15
    }

**Comment by karanbhomiagit** [comment]
Hi, I am facing a similar issue while making a GET call on "/rest/V1/orders/" api.
The field "cc_type" is missing from the response json.

**Comment by srinivasanithin** [comment]
Hi

We need this field cc_type to know which type of card was used in order information this gives us way to merchants to assign appropriate accounts for this transaction in ERP system integrated with Magento.

This field was available in Magento 1x and now i see this field value is not getting populating when using braintree.

can you please looking and let us know if feature is removed ( i  see that field in db table available but it is not getting populated with value)?

**Comment by asemenenko** [comment]
Added to MAGETWO-53493

**Comment by viktym** [comment]
This issue is not reproducible on 2.0.7 and current develop branch

**Comment by alena-marchenko** [comment]
Hi @ruby10 

Closing the issue, please feel free to reopen it with detailed steps to reproduce it it still persist
