### ISSUE TITLE
Advanced Modules Configurations during installation produces JS error

### ISSUE THREAD

**Issue by fooman** [magento/magento2#4678]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Run composer install
3. Start Web UI installer
4. Progress to Step 4
5. Click on "Advanced Modules Configurations"
## Expected result
1. Advanced Modules Configurations expands
## Actual result
1. JS error in console Firefox 41:

Error: $scope.store.allModules is undefined
$state.loadModules@http://local.example.com/m2-comp-test/setup/pub/magento/setup/customize-your-store.js:78:21
$scope.updateOnExpand@http://local.example.com/m2-comp-test/setup/pub/magento/setup/customize-your-store.js:92:13
ab.prototype.functionCall/<@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:174:380
ic[c]</<.compile/</</<@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:191:390
Yd/this.$get</h.prototype.$eval@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:110:369
Yd/this.$get</h.prototype.$apply@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:111:116
ic[c]</<.compile/</<@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:191:370
ne/c/<@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:31:30
q@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:7:402
ne/c@http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js:31:14

http://local.example.com/m2-comp-test/setup/pub/angular/angular.min.js
Line 91

**Comment by fooman** [comment]
The Next button also doesn't work - no error message - tried with 2.1.0-rc1

**Comment by mazhalai** [comment]
@fooman, it takes a while to read the file system and load all modules. What OS are you on?

**Comment by fooman** [comment]
It's on x86_64 GNU/Linux (3.16.7-24-desktop) - trying to continue hours later is still the same with no visual feedback.

**Comment by mazhalai** [comment]
Did you try cleaning browser cache and localstorage for that specific url?

**Comment by fooman** [comment]
I was able to pass that step with a fresh browser session now. Will close this one for now but currently investigating why it got stuck on the last step.

**Comment by pardeep7387** [comment]
Yes, Absolutely Right @fooman . Open Another browser window. As i was working in chrome so i opened Mozila Browser to restart my installation and then didn't get any error. Try again clear cache and closing browser and start again.
