### ISSUE TITLE
Product Custom Option Value is cut off in /admin/sales/order/view/

### ISSUE THREAD

**Issue by wq9** [magento/magento2#4680]
## Steps to reproduce
1. Create a product with Custom Option, `Input Type` = `Field`
2. Enter a string longer than 55 characters, for example `https://media.example.com/2c013ce0c4c207e8cf648d55f054bdd3.jpg`
3. Order the item.
4. View the order in the admin interface
## Expected result

In the Items Ordered section, the custom option value should display in full, or at least display in full when you hover on the value.
## Actual result

In the Items Ordered section, the custom option value is cut off to 55 characters and does not show the full value.

https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/templates/items/column/name.phtml

**Comment by vil11** [comment]
Looks like a reproducible bug. Internal ticket **MAGETWO-53668**.

## 

:sunny: dvilchynskyi, M2 QA engineer.

**Comment by galahadl** [comment]
Any progress on this? We have a client currently experiencing major fulfilment issues due to this

**Comment by magento-engcom-team** [comment]
@wq9, thank you for your report.
We've created internal ticket(s) MAGETWO-53668 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@wq9, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by shibey** [comment]
So is magento not fixing this one? we have been waiting for a fix on this one.

**Comment by korostii** [comment]
Apparently not.
I wonder if they could clarify their criteria for "much attention" though
IMO right now the dialogue I'm seeing in these "triaged" issues looks a bit comical if not absurd:
```
Users: Here's a bug in your software, please fix it.
Magento: Oh yeah, it's a bug, I've reproduced it.

------< one year later >-------

Users: Any progress on this?

------< one year later >-------

Magento: Hmm, it doesn't seem like you really want us to fix this bug. 
         We will just close this ticket now. 
         Thank you for collaboration.
```

**Comment by tonyr101** [comment]
I'm also affected by this BUG but I am using "textarea" not "field" - the fact is that customers are entering text into a textarea when ordering a product and although all their text is recorded in the DB it's cut off in the admin and emails so it's useless...

PLEASE FIX THIS

**Comment by adamstapley** [comment]
Did anybody ever find a fix for this or work around? We have a site that personalises gifts and can't see what text people want on items if they enter more than 50 characters.

**Comment by akssaiyad** [comment]
I have solved it 

In the Items Ordered section, the custom option value is cut off to 55 characters and does not show the full value.

https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/templates/items/column/name.phtml

You have to need comment below code in line no. 34


`<?php //$_option = $block->getFormattedOption($_option['value']); ?>`

After All content display in admin also

**Comment by adamstapley** [comment]
Thanks, seemed to work for me on Magento 2.3. It was line 33 in my file.
