### ISSUE TITLE
Magento RC 1: Static Cache Files have an Unacceptable Performance Regression

### ISSUE THREAD

**Issue by astorm** [magento/magento2#4681]
The performance of the initial hit/file-generation of static files (i.e. javascript, css, etc. files served from `/pub/static/...` or `/static/...`) has degraded significantly in Magento 2.1-RC1 release candidate. 

**Note:** the `curl-format.txt` file used in the following examples in included at the end of this issue.

For example, in a Magento 2.0.4 system, if (with developer mode enabled) I remove the `wishlist.js` file from the static folder, and then download the file twice, the first request takes `.296` seconds, and the subsequent requests take less than a hundredth, sometimes a thousandth of a second. 

```
$ rm /path/to/magento-2-0-4/pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js
$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-0-4.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.086
           time_connect:     0.086
        time_appconnect:     0.000
       time_pretransfer:     0.086
          time_redirect:     0.000
     time_starttransfer:     0.296
                        ----------
             time_total:  0.296

$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-0-4.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.032
           time_connect:     0.032
        time_appconnect:     0.000
       time_pretransfer:     0.032
          time_redirect:     0.000
     time_starttransfer:     0.034
                        ----------
             time_total:  0.034

$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-0-4.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.001
           time_connect:     0.001
        time_appconnect:     0.000
       time_pretransfer:     0.001
          time_redirect:     0.000
     time_starttransfer:     0.003
                        ----------
             time_total:  0.003
```

This is consistent with the initial request creating the file or symlink, and the subsequent requests being able to serve the file directly without additional PHP processing. 

However, the same test with the release candidate produces the following results. 

```
$ rm /path/to/magento-2-0-4/pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js
$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-1-rc1.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.000
       time_pretransfer:     0.004
          time_redirect:     0.000
     time_starttransfer:     3.228
                        ----------
             time_total:  3.228

$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-1-rc1.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.002
           time_connect:     0.002
        time_appconnect:     0.000
       time_pretransfer:     0.002
          time_redirect:     0.000
     time_starttransfer:     0.003
                        ----------
             time_total:  0.003

$ curl -w "@curl-format.txt" -o /dev/null -s http://magento-2-1-rc1.dev/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.002
           time_connect:     0.002
        time_appconnect:     0.000
       time_pretransfer:     0.002
          time_redirect:     0.000
     time_starttransfer:     0.003
                        ----------
             time_total:  0.003
```

That is, the creation of the asset takes over `3.228` seconds.  This is a **crazy** amount of time for generating an asset, and an unacceptable performance degradation. 

While this is bad enough in isolation, when considered in the context of a standard Magento HTML page request when dozens of these asset files are loaded, it creates an unacceptable burden on even a powerful developer machine.  Simple page requests bring on a fan, complex page request sometimes "brick" my standard apache process.  

From a developer experience and adoption point of view, as well as a technically savvy merchant point of view, this sort of performance bottleneck/regression (in an official, non-RC release) is a deal killer.  Even though this only happens during asset generation (i.e. subsequent requests may not trigger 3 seconds \* the number of javascript files page load times), regeneration of assets is common during standard feature, module, and integration development work cycles. Additionally, the first impression a merchant will have trying this out is pretty bad, and you never get a second chance to make a first impression. 

Finally, this behavior makes it very hard to actually use the application in acceptance testing, which makes testing modules almost impossible.  

**Expected Behavior**: The performance of the static asset application does not degrade between releases and is officially monitored via automated tests to ensure this sort of performance degradation does not happen. Additionally, that immediately after installing the application it is, if slow, useable. 

**Actual Behavior**: After installing Magento 2 initial page and asset hits are much slower that in previous releases, and the application itself is unusable until assets have been generated via multiple page loads or via a manual process.  
## curl Configuration

The above rough benchmarking was done via a `curl-format.txt` that looks like this.  Those are literal `\n`'s in the file, not malformed line endings. 

```
\n
           time_namelookup:  %{time_namelookup}\n
           time_connect:     %{time_connect}\n
        time_appconnect:     %{time_appconnect}\n
       time_pretransfer:     %{time_pretransfer}\n
          time_redirect:     %{time_redirect}\n
     time_starttransfer:     %{time_starttransfer}\n
                        ----------\n
             time_total:  %{time_total}\n
```

**Comment by pboisvert** [comment]
@choukalos passing to you to take up with the performance team

**Comment by redboxmarcins** [comment]
@astorm I cannot replicate it

My testing environment is
php7 with fpm
nginx
ssd drive samsung 850 Pro

```
PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.10.5, https://blackfire.io, by Blackfireio Inc.
```

Steps I took
1. Cloned fresh 2.1RC repository
2. Created database
3. Ran composer install
4. Installed using CLI
5. Prepared vhost for nginx (added ssl as well)

Then 

Enabled developer mode

```
$ bin/magento deploy:mode:set developer
Enabled developer mode.
```

Cache is on by default after installation

```
$ bin/magento cache:status
Current status:
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
                           eav: 1
         customer_notification: 1
                     full_page: 1
            config_integration: 1
        config_integration_api: 1
                     translate: 1
             config_webservice: 1
```

Here are actual tests:

```
$ rm pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js
$ ls pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js
ls: cannot access 'pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js': No such file or directory
$ curl --insecure -w "@curl-format.txt" -o /dev/null -s https://m21.loc/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.128
       time_pretransfer:     0.128
          time_redirect:     0.000
     time_starttransfer:     0.302
                        ----------
             time_total:  0.302
$ curl --insecure -w "@curl-format.txt" -o /dev/null -s https://m21.loc/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.128
       time_pretransfer:     0.128
          time_redirect:     0.000
     time_starttransfer:     0.128
                        ----------
             time_total:  0.128
$ curl --insecure -w "@curl-format.txt" -o /dev/null -s https://m21.loc/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.128
       time_pretransfer:     0.128
          time_redirect:     0.000
     time_starttransfer:     0.128
                        ----------
             time_total:  0.128
```

Can you advice how to replicate your slowness?

**Comment by redboxmarcins** [comment]
@astorm actually after disabling cache, 

```
$ bin/magento cache:disable
Changed cache status:
                        config: 1 -> 0
                        layout: 1 -> 0
                    block_html: 1 -> 0
                   collections: 1 -> 0
                    reflection: 1 -> 0
                        db_ddl: 1 -> 0
                           eav: 1 -> 0
         customer_notification: 1 -> 0
                     full_page: 1 -> 0
            config_integration: 1 -> 0
        config_integration_api: 1 -> 0
                     translate: 1 -> 0
```

see results

```
$ rm pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js
$ curl --insecure -w "@curl-format.txt" -o /dev/null -s https://m21.loc/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.132
       time_pretransfer:     0.132
          time_redirect:     0.000
     time_starttransfer:     2.065
                        ----------
             time_total:  2.065
$ curl --insecure -w "@curl-format.txt" -o /dev/null -s https://m21.loc/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.133
       time_pretransfer:     0.133
          time_redirect:     0.000
     time_starttransfer:     0.133
                        ----------
             time_total:  0.133
```

**Comment by tkacheva** [comment]
Internal issue MAGETWO-53458

**Comment by choukalos** [comment]
Hey @astorm  can you email me with Skype / Slack / Hipchat info?  We need more info on your setup/environment and I'd like to pass your contact info to the engineer assigned to this issue.  I'm cchoukalos at magento.com .  Thanks!

**Comment by dsikkema-magento** [comment]
What I'm seeing is that, yes, there can be a kind of slowdown that makes the initial request take ~2-4 seconds. But it's not per each static asset request, it's about initialization of different cache content that's used by the PHP application. So one static asset request, for an asset that's not in pub/static/, will take 2-4s, while a subsequent static asset request that also gets generated by the PHP application will go back to taking ~0.2-0.4s.

So in my console below, I clear the cache (application cache, not that static asset cache that's under pub/static) and request the asset (slow, a couple seconds), then delete the asset and re-request it (expected asset generation time, ~0.2-0.4s), then to sanity test I clear the cache and delete the asset again to see that it's requested slowly again. Then, to give myself confidence that this multi-second delay won't be applied to every static asset request, I request a second non-generated static asset, to see that, because application cache is not cleared, it's a reasonable time (~0.2-0.4s).

Does that agree with what you've found in your analysis? If so, then knowing that it's not multiple seconds per request but rather a few seconds to generate the application cache (assuming you cleared the whole application cache) followed by tenths of a second per subsequent requests, do you think that's still as problematic? 

Importantly, the results look statistically identical for 2.0.4 and rc1, which makes me wonder if you got the better numbers in 2.0.4 because application caching was not cleared, and then you cleared var when upgrading to rc1.

```
vagrant@m2:/vagrant/m2$ rm -rf var/cache
vagrant@m2:/vagrant/m2$ curl -w "@curl-format.txt" -o /dev/null -s http://m2.dev/pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.004
        time_appconnect:     0.000
       time_pretransfer:     0.005
          time_redirect:     0.000
     time_starttransfer:     4.962
                        ----------
             time_total:  4.962
vagrant@m2:/vagrant/m2$ rm pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js
vagrant@m2:/vagrant/m2$ curl -w "@curl-format.txt" -o /dev/null -s http://m2.dev/pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.005
           time_connect:     0.006
        time_appconnect:     0.000
       time_pretransfer:     0.006
          time_redirect:     0.000
     time_starttransfer:     0.236
                        ----------
             time_total:  0.236
vagrant@m2:/vagrant/m2$ rm -rf var/cache
vagrant@m2:/vagrant/m2$ rm pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js
vagrant@m2:/vagrant/m2$ curl -w "@curl-format.txt" -o /dev/null -s http://m2.dev/pub/static/frontend/Magento/luma/en_GB/Magento_Catalog/js/view/compare-products.js

           time_namelookup:  0.004
           time_connect:     0.005
        time_appconnect:     0.000
       time_pretransfer:     0.005
          time_redirect:     0.000
     time_starttransfer:     3.166
                        ----------
             time_total:  3.166
vagrant@m2:/vagrant/m2$ ls pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js
ls: cannot access pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js: No such file or directory
vagrant@m2:/vagrant/m2$ curl -w "@curl-format.txt" -o /dev/null -s http://m2.dev/pub/static/frontend/Magento/luma/en_US/Magento_Wishlist/js/view/wishlist.js

           time_namelookup:  0.005
           time_connect:     0.005
        time_appconnect:     0.000
       time_pretransfer:     0.005
          time_redirect:     0.000
     time_starttransfer:     0.295
                        ----------
             time_total:  0.295
```

**Comment by astorm** [comment]
@choukalos Thanks for the quick response. Let's keep the conversation in GitHub -- it's well designed for conversations about code/performance/software, and keeping it public means everyone gets a record of what sort of information the team needs for these sorts of issues.

OS/Software versions as follows

```
OS X (10.11.3)

$ httpd -v
Server version: Apache/2.4.16 (Unix)
Server built:   Jul 31 2015 15:53:26

$ mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 894
Server version: 5.6.22 MySQL Community Server (GPL)

$ php -v
PHP 5.6.19 (cli) (built: Mar 10 2016 14:12:41) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

MySQL dump is attached.

Magento was installed using the composer `create-project` method, and then with the `setup:install` command.

```
php bin/magento setup:install --admin-email astorm@alanstorm.com --admin-firstname Alan --admin-lastname Storm --admin-password fakepassword --admin-user astorm --backend-frontname admin --base-url http://magento-2-1-rc1.dev --db-host 127.0.0.1 --db-name magento_2_1_rc1 --db-password ididit27 --db-user root --session-save files --use-rewrites 1 --use-secure 0 -vvv
```

If you need more information please let me know.

**Comment by astorm** [comment]
@dsikkema @redboxmarcins Ah ha, thank you!  When I had installed previous versions of Magento the cached defaulted to being on.  I assumed the same was true of RC1, but it looks like the caches default to being off (at least after using the `create-project`/`setup:install` method). 

@piotrekkaminski -- I think this is your territory (if not, please pass it on to whomever's it is) -- is there a compelling reason to have cache **off** after the initial installation?  The application is near unusable when its in that state.  If there isn't a compelling reason, or that reason is less is less important than initial impressions, it seems like defaulting to having the caches on would be the right move. 

@dsikkema @redboxmarcins @piotrekkaminski Re: _do you think that's still as problematic?_ -- with cache on the performance of RC1's static asset generator is more in line with the behavior I'm seeing with 2.0.x.  That said -- multiple seconds for serving a static file, even in an uncached state, seems like a target rich enviornment for performance improvement.  Most other PHP applications and systems I work with, even those that have caches similar to Magento, can perform OK in an uncached state. Right now Magento 2 (be it RC1 or the 2.0.x branch) can't.  From the outside looking in that seems like something you'd want to fix if you're interested in new outside developers and third parties adopting the platform.

**Comment by dsikkema** [comment]
Are caches enabled?

**Comment by astorm** [comment]
@choukalos Trying the MySQL dump again. 
[magento_2_1_rc1_2016-05-25.sql.gz](https://github.com/magento/magento2/files/282696/magento_2_1_rc1_2016-05-25.sql.gz)

**Comment by dsikkema-magento** [comment]
I'm going to go ahead and close this ticket as unreproducible since it just needed caches enabled -- however -- Regarding caches being enabled or disabled by default, I just installed rc1 from both github and composer and saw caches enabled. @astorm if caches aren't enabled, I think that's no good - could you please raise a separate issue for that (so others who might have the same issue can see that as the issue title) and describe the exact create-project command (and also install command even though I see you posted that in this thread already)?
