### ISSUE TITLE
Magento 2.1 RC1 > no changelog

### ISSUE THREAD

**Issue by aoldoni** [magento/magento2#4683]
Magento 2.1 doesn't contain a changelog describing the changes.
https://github.com/magento/magento2/blob/2.1.0-rc1/CHANGELOG.md

This is more of a documentation issue, but part of this repository. Please advise if this should be reported somewhere else?

I know we have these release notes: http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1CE.html - but we expect the changelogs to be more detailed and technical? Or is it just a matter of having these release notes copied accross to the changelog?

Thanks.

**Comment by pboisvert** [comment]
Hi Alisson--fine to report this one here. Partners though should log issues in the partner portal so we have formal tracking. Agree with the feedback that change log should provide more guidance on the nature of changes.

**Comment by aoldoni** [comment]
Hi @pboisvert 

Thanks for the response.
- This is just a general comment for the community version, not actually expecting a partner-like service level or anything on this.
- I guess I decided to create the issue since there was no Changelog on the 2.1 RC1 tag, and wanted to validate my expectation was correct.
- Happy with the previous level of detail on the previous Changelogs - it was simply the case that 2.1 RC1 didn't have one.

Again, thanks!

**Comment by pboisvert** [comment]
ok--no problem Alisson. Understand why it was posted as an issue.

**Comment by Sergeacc** [comment]
Thank you for your submission. Your question indicates a need to improve Magento 2 documentation. We have reassigned your submission as a Developer Documentation request.

**Comment by okorshenko** [comment]
Hi @aoldoni starting with release 2.1.0 we decided to do not duplication information from the release notes and changelog. So we stopped adding this information.
But with release 2.1.8+ we decided to keep only Community Changelog in the code base (fixed issues and PRs by the community). Release notes will have both: core fixes + community.
So this was done by agreement.
Closing as non-issue
