### ISSUE TITLE
Magento 2.0.2 Upgrade: Sorry, we can't take that action right now.

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4686]
## Steps to reproduce
1. Try to update Magento 2.0.2
2. Cronjobs works, no migration tool
3. Repositories already in composer.json file and no data migration tool
4. Logged in and key saved
## Expected result
1. Start update.
## Actual result
1. Sorry, we can't take that action right now.

**Comment by mazhalai** [comment]
@flipflap where are your keys saved? Make sure they are available in `var/composer_home/auth.json`

**Comment by flipflap** [comment]
That auth.json file was missing, now I added it but is still doesn't work.

```
{
    "http-basic": {
        "repo.magento.com": {
            "username": "my pub key",
            "password": "my priv key"
        }
    }
}
```

**Comment by ark99** [comment]
@flipflap, can you please post the root composer.json's "repositories" : [ ] section?

**Comment by mazhalai** [comment]
@flipflap can you confirm that repo.magento.com is the only repo within composer.json?

**Comment by flipflap** [comment]
I don't know, this is in my root composer.json:

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by ghost** [comment]
Looks like @flipflap 's `composer.json` is correct. There is only one thing in the `repositories` section. @mazhalai is correct that the most typical reason for that error is missing auth keys.

You might also have an issue reaching `repo.magento.com` from your Magento server. Can you verify it's reachable by pinging it and also posting the result of `nslookup repo.magento.com`?

**Comment by flipflap** [comment]
@xcomStefeJohnson how can I send a ping? nslookup repo.magento.com tells me command not found in the shell. Thanks.

**Comment by ghost** [comment]
ping repo.magento.com

It appears that on CentOS anyway, `nslookup` is not installed if you selected the minimal option when you installed the OS. Try installing it and trying the command again.

**Comment by flipflap** [comment]
Ping works, but lookup is never ending:
![lookup](https://cloud.githubusercontent.com/assets/6672673/15817605/2129ff78-2bd9-11e6-8349-9b301de6b1e1.png)

**Comment by ghost** [comment]
It doesn't look to me as if ping works. It should return results if it's working.

**Comment by flipflap** [comment]
Ok thanks, I sent the screenshot to my hoster. I hope they can help me.

**Comment by flipflap** [comment]
The ping doesn't work on all Servers, we also tried it on Servers the update wizzard works well. So this can't be the reason why I can't update.
![ping](https://cloud.githubusercontent.com/assets/6672673/15849551/7390333a-2c93-11e6-8b35-9335848e2ea0.png)

**Comment by veloraven** [comment]
@flipflap is this issue still actual?
It seems to be not Magento issue but rather environment configuration problem.

**Comment by flipflap** [comment]
@veloraven I think the problem is still there, I couldn't solve it. But instead I use composer and comand line to update now.

**Comment by BaDos** [comment]
Hi @flipflap 

Do you have the same problem with other versions of Magento?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
