### ISSUE TITLE
Web Setup Wizard not reachable with varnish caching active

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#4687]
Magento 2.0.6
Varnish installed version 4.2

Configuration made according to magento guideline.

Problem:
When clicking on the Web Wizard from the backend the site gets redirected to:

http://www.domain.com:8080/setup/

And a blank white screen is shown.
When reloading the site we get redirected to http://www.domain.com:8080/setup/index.php/session/unlogin with this message:

Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard

**Comment by mazhalai** [comment]
@andidhouse can you please clean your `var/session` folder and try again?

**Comment by afavata** [comment]
Magento 2.0.7 - Varnish 4.1.2 - Same behavior.... web setup wizard shows a white page and url shown is http://www.mywebsite.com:8080/setup/

**Comment by oshmyheliuk** [comment]
Hi @afavata 
Is this issue still reproduces? 
Please try to clean varnish cache, or restart varnish process

**Comment by afavata** [comment]
Hi @oshmyheliuk

Yes.... issue is still reproduced. 
The only way to upgrade is by command line.
No way to access to the Web setup wizard

Thank you

Alessandro

**Comment by mitulispace** [comment]
Magento ver. 2.1.1

**Comment by BaDos** [comment]
Hi, guys!

Cannot reproduce it.
Do you have the same issue on Magento 2.0.10?
Please, provide information about your environment (php, web server, OS, etc).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by afavata** [comment]
Please reopen this issue.
Every time I do try to access to "Web Setup Wizard" a blank page is shown and an error is recorded in apache2 error.log file as follow: 

``[Sun Nov 27 19:45:06.821946 2016] [:error] [pid 9725] [client 5.94.205.45:56698] PHP Fatal error:  Uncaught Exception: Warning: SessionHandler::write(): open(localhost:11211/sess_lpnfenaaqpg7qv0hno08bqbtc7, O_RDWR) failed: No such file or directory (2) in /var/www/mywebsite/vendor/magento/framework/Session/SaveHandler.php on line 105 in /var/www/mywebsite/vendor/magento/framework/App/ErrorHandler.php:61\nStack trace:\n#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'SessionHandler:...', '/var/www/mywebs...', 105, Array)\n#1 /var/www/mywebsite/vendor/magento/framework/Session/SaveHandler.php(105): SessionHandler->write('lpnfenaaqpg7qv0...', '')\n#2 [internal function]: Magento\\Framework\\Session\\SaveHandler->write('lpnfenaaqpg7qv0...', '')\n#3 {main}\n  thrown in /var/www/mywebsite/vendor/magento/framework/App/ErrorHandler.php on line 61, referer: http://www.mywebsite.com/admin_121271/admin/dashboard/index/key/86014be1ec65cdde4f61861e9772e234f0d233d3696e0769894ba2af14935986/``

**Comment by treii28** [comment]
I'm running into this on 2.2.2 with a varnish cache setup

**Comment by jonathan-nielsen** [comment]
I'm having the same issue on 2.2.2 with varnish active

**Comment by botlinkd** [comment]
i am using Magento ver. 2.2.4

and i try my best but unable to fix the issue please help thank you

Welcome to Magento Admin, your online store headquarters.
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard
