### ISSUE TITLE
Why customerRepository take too long to save a single customer with addresses?

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#4689]
Hi,

I'm wondering why customer repository always cost me from 7 ~ 15s to save a single customer (with addresses).

Do you have any idea to optimise the method (save) or just simply had better idea?

Thanks.

**Comment by sevos1984** [comment]
Is your problem for customer entity only? What about other entites?

**Comment by slavvka** [comment]
Closing as the author didn't respond

**Comment by nntoan** [comment]
Hello there,
I do apologise for my late response, I didn't notice to this.
My problem happened while try to save both of customer and customer address entities.

I tried to separate it, save customer entity and then save the customer address. But the time still go around 7 ~ 15, even 1 minutes for a record.

If you need further information, please let me know.
Thank you.
