### ISSUE TITLE
bug require js

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#4691]
I have added code to file "requirejs-config.js":

var config = {
    map: {
        '*': {
            'owlcarousel/js': 'Loadjs/js/owl-carousel/owl.carousel',
            'owlcarousel/minjs': 'Loadjs/js/owl-carousel/owl.carousel.min'
        }
    }
};

code add to content:
require(["jquery", "owlcarousel/js"], function($){
    $("#owlslide").owlCarousel({
        ....
    });
});

It's can show owl slider but sometimes it doesn't show slider and have bug js(owlCarousel not a function). Do you have any idea? Thanks you.

**Comment by anton-huz** [comment]
Hi @duongquyet ,
You miss `shim` option. The root issue is in how OwlCarousel handle own dependencies. It requires _jQuery_. But RequerJS doesn't know about this dependency. And can load `owl.carousel.js` earlier (especially it has smaller file size).

So your example could looks like:

```
var config = {
    "shim": {
        "<Brand>_<Module>/js/owl-carousel/owl.carousel": {
            "deps": ["jquery"],
            "exports": "jQuery.fn.owlCarousel"
        }
    }
};
```

and in template place:

```
<script type="text/x-magento-init">
{
    "#owlslide": {
        "<Brand>_<Module>/js/owl-carousel/owl.carousel": { ... object with settings }
    }
}
</script>
```

update: its handy to have _return_ value for widgets/plugins.

**Comment by duongquyet** [comment]
Hi @guz-anton ,
We try change it and it seem like work for me. Thanks you.

```
var config = {
    // dependency order if applicable
    "shim": {
        "owlcarousel/minjs": ["jquery"]
    },
    'paths': {
        'owlcarousel/minjs': 'Loadjs/js/owl-carousel/owl.carousel.min'
    }
};

    require([
    "jquery",
    "owlcarousel/minjs"
], function($,owlCarousel){
    $("#owl").owlCarousel({
                   ..............
           });
});
```
