### ISSUE TITLE
Catalog New Products List widget shows out of stock products

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4692]
## Steps to reproduce
1. Install Magento 2.0.7
2. Set `Display Out of Stock Products` config parameter to `No`
3. Insert `Catalog New Products List` widget into a CMS page
4. Open CMS page
## Expected result
1. Only products that are in stock are shown
## Actual result
1. Also out of stock products are shown

P.S. Category view works fine and respects `Display Out of Stock Products` config value

**Comment by mslabko** [comment]
Hello @werdlv 
This issue is not reproduced yet in develop branch. Try to update your code base (2.1-rc, e.g.) and if you still have any issue, please reopen this one

**Comment by jsakars** [comment]
@mslabko quote from Magento2 release notes for version 2.1 - `This release candidate build is not intended for production purposes`. We use 2.0.7 (latest stable) in production environment and there is a bug. Regarding develop branch - hard to argue; I assume develop branch is pretty unstable and can't be trusted. Anyway - what's the point of stating issue steps to reproduce if bugs are being checked against develop branch?

**Comment by mslabko** [comment]
@werdlv , Yes, 2.1-rc it just release candidate. 
Patch  for 2.0.\* will be provided in https://github.com/magento/magento2/issues/4108.
