### ISSUE TITLE
Extension Attributes and Integration Tests

### ISSUE THREAD

**Issue by sjauck** [magento/magento2#4693]
I used extensions Attributes to add an additionall attribute to coupons. 
With den Command Line setup:di:compile command i can generate the new Interfaces. 
If i run the phpunit Command on Command Line it fail because the Interface isn´t generated. 
## Steps to reproduce
1. Install Magento EE 2.0.4
2. Add an extension Attribute with complex type to the Magento Sales Rule Coupon.
   3.1 Generate the di with magento setup:di:compile
     => var/generation/Magento/SalesRule/ApiData/\* is generated
   3.2 Run PHPUnit in the integration tests folder with phpunit -c phpunit.xml --filter <TestName>
    => dev/tests/integration/tmp/sandbox_/var/generation/Magento/SalesRule/Api/_ isn´t generated
         only Model folder is generated

I tried:
- Drop Database
- Delete Sandbox
- Clean Cache

**Edit:** Now i found the integration tests split the generation. If there is a var/generation folder, they take this generations and only generate the missing classes in sandbox. If there is noch var generation folder it generate all under sandbox. Please set only one directory. Its confusing if there are two places.

**Comment by andimov** [comment]
@sjauck, thank you for reporting this issue!
Could you add **Expected** and **Actual** result points according to the template. It's clarify your problem and expectation for us.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
