### ISSUE TITLE
Magento 2.1 - Can't update custom attribute value for customer (account edit form)

### ISSUE THREAD

**Issue by tanghia** [magento/magento2#4694]
Magento 2.0.2 -> 2.0.6 update value of custom attributes on account edit page successfully, but magento 2.1 can't update (no error message or javascript error).
### Steps to reproduce
1. Create account with custom attributes successfully
2. Login
3. Edit account information 
### Expected result
1. Value of custom attributes changed
### Actual result
1. New values is not update.

Magento also hardcode some attribute_set_id in: CustomerMetadataInterface and AddressMetadataInterface (1 and 2). Magento 2.1 also change js and some template files (account page) which is not compatible with extensions and theme of old versions.

**Comment by ravichandrarv** [comment]
i have created custom attributes for customer and product......now i want to make them read only  for some user and for some user make it editable.......

**Comment by wert2all** [comment]
Thanks for reporting. Internal ticket MAGETWO-56126 was created.

**Comment by antboiko** [comment]
Hi @tanghia , please let me inform you, this issue has been already fixed in a mainline and will be also available in one of the future patches.

I'm closing this ticket. Please feel free to reopen or create a new one.

Best,
Anton.
