### ISSUE TITLE
Magento 2.1 RC1: product catalog in backend cannot be displayed

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#4695]
## Steps to reproduce
1. Install Magento Magento 2.1 RC1.
2. In backend, go to Product -> Catalog.
## Expected result
1. List of products appears.
## Actual result
1. The following error appears:
   `Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : CData section too big found in /magento/lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Template.php on line 60`
2. I dumped the content into a file, it took 27 MB of disk space. If DOMDocumentFragment::appendXML() is using libxml2, then it may be the problem that XML_MAX_TEXT_LENGTH is usually compiled to around 10 MB as this suggests: http://php.net/manual/de/domdocument.loadxml.php#113676

![image](https://cloud.githubusercontent.com/assets/15156912/15540288/c6b58e00-2286-11e6-9b5c-4714b66d2080.png)

**Comment by bh-ref** [comment]
Sorry, seems to be a problem with an extension (I just disabled all non-Magento modules and the problem is gone).

**Comment by ghost** [comment]
What extensions are you running. I had this issue after I ran the migration script.

Currently I have 
        "sjparkinson/static-review": "~4.1",
        "classyllama/module-avatax": "^0.3.3",
        "subscribepro/subscribepro-magento2-ext": "^1.0",
        "magefan/module-login-as-customer": "^2.1",
        "ibnab/magento2-delete-orders": "*",
        "customerparadigm/ordercomments": "^100.0",
        "amasty/base": "^1.0",
        "amasty/module-mass-order-actions": "^1.0",
        "amasty/preorder": "^1.0",
        "magento/data-migration-tool": "2.1.3",
        "weltpixel/maxmind": "^1.0",
        "weltpixel/m2-weltpixel-backend": "^1.0",
        "magestore/giftvoucher-magento2": "^1.0",
        "magestore/rewardpoints-magento2": "^1.0"

**Comment by bh-ref** [comment]
As far as I can see, the only matching extension which was activated at that time was "amasty/base".

Maybe it helps to disable all the extension, let the list of products appear, and then reenable the extension (maybe one by one)?

**Comment by joshspivey** [comment]
I removed all amasty plugins same issue. I also tried seeing if it was weird chars by adding 
$invalid_characters = '/[^\x9\xa\x20-\xD7FF\xE000-\xFFFD]/';
$feedXml = preg_replace($invalid_characters, '', $content );
$newFragment->appendXML($feedXml);

no luck with that either...

**Comment by ghost** [comment]
I tried removing all my extensions and no luck I didn't have this issue until I did a migration from mage 1. I had all my extensions installed before I migrated over.

**Comment by joshspivey** [comment]
Just noticed that the load method is using zend framework so that parse huge usage wont work... Working on figuring the zend way of doing this. I have a 25mb xml file due to extra fields being added to products on the migration. The 10mb limit is definitely the issue.

**Comment by joshspivey** [comment]
that error is coming from appendXML not loadXML so I cant use that constant.

In the actual extension on the server its coming from parse cdata method.

I am not sure why its not getting the constant from the loader. Any other ideas of where or how to pass that in to make it compatible with appendXML?

xmlParseCDSect(xmlParserCtxtPtr ctxt) {
    xmlChar *buf = NULL;
    int len = 0;
    int size = XML_PARSER_BUFFER_SIZE;
    int r, rl;
    int	s, sl;
    int cur, l;
    int count = 0;

    /* Check 2.6.0 was NXT(0) not RAW */
    if (CMP9(CUR_PTR, '<', '!', '[', 'C', 'D', 'A', 'T', 'A', '[')) {
	SKIP(9);
    } else
        return;

    ctxt->instate = XML_PARSER_CDATA_SECTION;
    r = CUR_CHAR(rl);
    if (!IS_CHAR(r)) {
	xmlFatalErr(ctxt, XML_ERR_CDATA_NOT_FINISHED, NULL);
	ctxt->instate = XML_PARSER_CONTENT;
        return;
    }
    NEXTL(rl);
    s = CUR_CHAR(sl);
    if (!IS_CHAR(s)) {
	xmlFatalErr(ctxt, XML_ERR_CDATA_NOT_FINISHED, NULL);
	ctxt->instate = XML_PARSER_CONTENT;
        return;
    }
    NEXTL(sl);
    cur = CUR_CHAR(l);
    buf = (xmlChar *) xmlMallocAtomic(size * sizeof(xmlChar));
    if (buf == NULL) {
	xmlErrMemory(ctxt, NULL);
	return;
    }
    while (IS_CHAR(cur) &&
           ((r != ']') || (s != ']') || (cur != '>'))) {
	if (len + 5 >= size) {
	    xmlChar *tmp;

            if ((size > XML_MAX_TEXT_LENGTH) &&
                ((ctxt->options & XML_PARSE_HUGE) == 0)) {
                xmlFatalErrMsgStr(ctxt, XML_ERR_CDATA_NOT_FINISHED,
                             "CData section too big found", NULL);
                xmlFree (buf);
                return;
            }
	    tmp = (xmlChar *) xmlRealloc(buf, size * 2 * sizeof(xmlChar));
	    if (tmp == NULL) {
	        xmlFree(buf);
		xmlErrMemory(ctxt, NULL);
		return;
	    }
	    buf = tmp;
	    size *= 2;
	}
	COPY_BUF(rl,buf,len,r);
	r = s;
	rl = sl;
	s = cur;
	sl = l;
	count++;
	if (count > 50) {
	    GROW;
            if (ctxt->instate == XML_PARSER_EOF) {
		xmlFree(buf);
		return;
            }
	    count = 0;
	}
	NEXTL(l);
	cur = CUR_CHAR(l);
    }
    buf[len] = 0;
    ctxt->instate = XML_PARSER_CONTENT;
    if (cur != '>') {
	xmlFatalErrMsgStr(ctxt, XML_ERR_CDATA_NOT_FINISHED,
	                     "CData section not finished\n%.50s\n", buf);
	xmlFree(buf);
        return;
    }
    NEXTL(l);

    /*
     * OK the buffer is to be consumed as cdata.
     */
    if ((ctxt->sax != NULL) && (!ctxt->disableSAX)) {
	if (ctxt->sax->cdataBlock != NULL)
	    ctxt->sax->cdataBlock(ctxt->userData, buf, len);
	else if (ctxt->sax->characters != NULL)
	    ctxt->sax->characters(ctxt->userData, buf, len);
    }
    xmlFree(buf);
}

**Comment by bh-ref** [comment]
I tried to raise the limit for appendXML() back then as well. Without success, too. Maybe you can create a copy of your database, delete half of the products, check, and if the problem still exist, create another copy and delete the other half of the products. If one half of the products produces the error, continue to half the products further until you manage to find the product which produces this issue (if it is a product which produces the issue). Just my guess, I really do not know what to do else, I am sorry. Maybe the best idea is to open a new ticket?

**Comment by ghost** [comment]
Well I am wondering why the xml is even needed it's just holding a json object. 

```<script type="text/x-magento-init"><![CDATA[{"*": [{"junk":"25mb of junk"}]}]]></script>```

There is allot of junk code wrapping this. I think the proper solution would be to make this a literal object. Its just a ton of unneeded bloat causing a performance bottle kneck for what? To make this break after to many records?

```
<script>
var tmpObject = {"*": [{"junk":"25mb of junk"}]};
</script>
```

**Comment by joshspivey** [comment]
Found this also https://community.magento.com/t5/Hosting-Performance/Import-of-many-Configurations/m-p/57091

**Comment by ghost** [comment]
I created this ticket.
https://github.com/magento/magento2/issues/8084

**Comment by joshspivey** [comment]
I have a temp fix for this.
Install this plugin https://github.com/mattador/tde-sales-grid
on Collection.php line 87 add in.
$this->getSelect()->limit(1000);

**Comment by ghost** [comment]
@bh-ref check out my link I made a grid that works! on ticket 8084

**Comment by bh-ref** [comment]
@joshspivey cool, I am glad you found a working solution / fix! I just realize now that you have problems with the sales/order grid, whereas I was having trouble with the product grid. But maybe your fix is easily applicable for that as well. In my installation, the problem is not appearing anymore, but it sure is good to know there is an alternative available.

**Comment by ghost** [comment]
@bh-ref yah you have to much product data. If its making a XML file over 10mb you will have this issue. All the grids on Mage 2 load all XML at once which is not good if you have allot of data on any part of the site. I chose to use backbone grid because the knockout grids didn't have anything close the functionality as backgrid and I don't want to spend months working on a fix for something that takes a couple days to make. The grid script built in mage 2 looked like they tried to roll there own and was very minimal at best. It needs a lot of functionality.

You can change it out to products in a couple of hours.

in https://github.com/joshspivey/magento2-sales-grid/blob/master/Controller/Adminhtml/Orders/OrderList.php

just swap out \Magento\Sales\Api\OrderRepositoryInterface $orderRepository, to product repo and SortOrderBuilder to SortProductBuilder

Then in https://github.com/joshspivey/magento2-sales-grid/blob/master/view/adminhtml/web/js/magentoGrid.js

update your columns to match the data
```
 var processGrid = {
            columns: [
	            {

	                name: 'entity_id',
	                label: 'Order ID',
	                editable: false,
	                cell: Backgrid.IntegerCell.extend({
		                orderSeparator: ''
		            })
	            }, 
				{
	                name: 'increment_id',
	                label: 'Increment ID',
	                editable: false,
					cell: Backgrid.IntegerCell.extend({
		                orderSeparator: ''
		            })
	            },
	            {
	                name: 'status',
	                label: 'Status',
	                editable: false,
	                cell: 'string'
	            }, 
	            {
	                name: 'created_at',
	                label: 'Created At',
	                editable: false,
	                cell: timeDateFormat
	            },
				{
	                name: 'updated_at',
	                label: 'Updated At',
	                editable: false,
	                cell: timeDateFormat
	            },
	            {
	                name: 'base_grand_total',
	                label: 'Base Grand Total',
	                editable: false,
	                cell: 'string'
	            },
	            {
	                name: 'base_total_paid',
	                label: 'Base Total Paid',
	                editable: false,
	                cell: 'string'
	            }, 
	            {
	                name: 'customer_email',
	                label: 'Customer Email',
	                editable: false,
	                cell: 'string'
	            }
            ]
        };
```
There are some other minor tweaks needed.

Then to get it to show up on the product menu 

edit 
https://github.com/joshspivey/magento2-sales-grid/blob/master/etc/adminhtml/menu.xml

change Magento_Sales::sales_operation to the products section

**Comment by ecomwise** [comment]
We had same a problem with orders grid. It contained around 15000 records. Issue occured when sales_order_grid.xml massAction component was extended in our custom Module.
So if third party module is adding custom mass action to gird and grid has a lot of records, probably this error will appear.
In our example in order grid, without custom mass action CData was 52Kb.
When custom mass action enabled, CData raised to 22Mb
