### ISSUE TITLE
Admin product search - Pressing enter does not submit

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4696]
## Steps to reproduce
1. Login to the admin
2. Go to `products > catalog`
3. Click on filters
4. Enter some text in the name field
5. Press enter on your keyboard
## Expected result
1. Pressing enter should submit the form (good UX)
## Actual result
1. Nothing happens
## Notes
- I am currently on version 2.0.4 so apologies if this has recently been fixed, I'm unable to update the Magento version at the moment.
- This has briefly been mentioned in [this issue](https://github.com/magento/magento2/issues/3575) but I think it has been missed or buried amongst the other requests.

![screen shot 2016-05-25 at 14 30 15](https://cloud.githubusercontent.com/assets/8895777/15541629/434cd010-2285-11e6-851c-1a1adc6e9ec1.png)

**Comment by choukalos** [comment]
We were not able to apply the new data grid in it's entirety to the admin/product grid.  We're tracking this internally as ( MAGETWO-37743 )

**Comment by Frits1980** [comment]
Is this still work in progress? Because it has been quiet for a while now.

**Comment by magento-engcom-team** [comment]
@BenSpace48, thank you for your report.
We've created internal ticket(s) MAGETWO-81749 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @BenSpace48 the issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by ishakhsuvarov** [comment]
Hi @BenSpace48. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1197 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - 0be044e478bac94b79ffaa7b3b2699a744321316

The fix will be available with the upcoming patch release.

**Comment by Ctucker9233** [comment]
@ishakhsuvarov I see this issue is acknowledged for 2.1.x, so any idea when this will be backported?
