### ISSUE TITLE
Magento 2.1.0 RC1 : cannot install sample data 

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#4699]
## Steps to reproduce
1. Install Magento from `2.1.0 RC1` branch.
2. Run `bin/magento sampledata:deploy`
## Expected result
1. composer.json is updated
2. sample data is downloaded
## Actual result
1. Composer error

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/module-widget-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package magento/module-theme-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package magento/module-offline-shipping-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package magento/module-tax-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package magento/module-bundle-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package magento/module-catalog-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package magento/module-wishlist-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package magento/module-cms-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package magento/module-customer-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package magento/module-sales-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package magento/module-swatches-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package magento/module-configurable-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package magento/module-product-links-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 14
    - The requested package magento/module-review-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 15
    - The requested package magento/module-msrp-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 16
    - The requested package magento/module-grouped-product-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 17
    - The requested package magento/module-sales-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 18
    - The requested package magento/module-catalog-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 19
    - The requested package magento/sample-data-media could not be found in any version, there may be a typo in the package name.
  Problem 20
    - The requested package magento/module-downloadable-sample-data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
There is an error during sample data deployment. Composer file will be reverted
```

**Comment by mazhalai** [comment]
Sample data packages for 2.1 have not been published yet.

**Comment by redboxmarcins** [comment]
That explains, can I use https://github.com/magento/magento2-sample-data/tree/2.1

**Comment by mazhalai** [comment]
Yes you should be able to do that.

**Comment by mazhalai** [comment]
@redboxmarcins any update?

**Comment by redboxmarcins** [comment]
I can only install by hand

**Comment by paalsoberg** [comment]
I seem to have managed to get it working - had 2.0.6 with sample data installed and upgraded to 2.1RC1 -- lots of issues at the start due to the sample data.. but running these commands seems to have sorted most of it:
php bin/magento sampledata:remove
php bin/magento sampledata:deploy

And then obviously cache:clean etc...

Only one issue remaining and the product grid is not loading - just spinning wheel - seems like some of the product data is corrupt in admin - shows up fine on front end

**Comment by paalsoberg** [comment]
Got the product grid working as well - just had to export and then import the product data again!

**Comment by veloraven** [comment]
@redboxmarcins is this issue still actual?

**Comment by ytorbyk** [comment]
Hi @veloraven . Yes, the issue is still replicable. Magento repository has to be added by hand for sample data deploying (by `sampledata:deploy` command).

**Comment by oshmyheliuk** [comment]
Hi @veloraven 
What version did you install?
I tried to reproduce this issue on version 2.1.0 , but everything worked fine.

**Comment by ytorbyk** [comment]
I use 2.1.1 (2.1 branch)

**Comment by JustinWang24** [comment]
I find a way:
1: composer config repositories.magento composer https://repo.magento.com/packages.json
2: Update composer.json, change the minimum-stability to beta
3: composer update ( Need to input your mage market username and password)
4: magento sampledata:deploy
5: magento setup:upgrade

It works for me.

**Comment by cmutz** [comment]
It works for magento 2.1.2 (2.1 branch).

**Comment by hyperfocus1337** [comment]
This issue is still replicable on 2.1.8

**Comment by magento-engcom-team** [comment]
`bin/magento sampledata:deploy ` is designed for composer based installation. or add repo to your composer.json file

**Comment by jimul** [comment]
Still issue persist with magento 2.2 EE

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/module-gift-card-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package magento/module-customer-balance-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package magento/module-target-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package magento/module-gift-registry-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package magento/module-multiple-wishlist-sample-data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by benmarks** [comment]
@jimul It's working for me. Did you update minimum stability to `beta`?

**Comment by jimul** [comment]
Yes, I tried with "minimum-stability": "beta", and cleared composer cache, same issue

**Comment by shahrukh-alizai** [comment]
This issue is still replicable on 2.1.10

**Comment by titechnologies** [comment]
Still getting the issue in 2.2.3

**Comment by rafaelcalero** [comment]
Still getting in 2.2.3

It works following the steps of @JustinWang24 but you have to skip the step of editing the composer.json (beta, now isn't necesary), it would be like that:

1: composer config repositories.magento composer https://repo.magento.com/packages.json
2: composer update ( Need to input your mage market username and password)
3: magento sampledata:deploy
4: magento setup:upgrade

**Comment by rochaaa** [comment]
Still getting in 2.2.5

**Solution above** by @rafaelcalero and @JustinWang24 works like a charm.

**Comment by genii6** [comment]
2.3.4
