### ISSUE TITLE
Notifications Actions - missing carriage return

### ISSUE THREAD

**Issue by toniyecla** [magento/magento2#4701]
## Steps to reproduce
1. Login Admin. Go to Notifications section.
## Expected result

Read
Details
Mark as Read
Remove
## Actual result
1. ReadDetailsMark as ReadRemove

(all on the same line)

**Comment by MomotenkoNatalia** [comment]
@toniyecla thanks for reporting this issue! I am going to close it as duplicate - https://github.com/magento/magento2/issues/4586
