### ISSUE TITLE
Magento\Framework\Session\SessionManager breaks contract of Magento\Framework\Session\StorageInterface

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#4704]
[Here](https://github.com/magento/magento2/blob/a5fa3af3b16bb03dcc01068aed0c58d8993fd092/lib/internal/Magento/Framework/Session/SessionManager.php#L157), [here](https://github.com/magento/magento2/blob/a5fa3af3b16bb03dcc01068aed0c58d8993fd092/lib/internal/Magento/Framework/Session/SessionManager.php#L240), [here](https://github.com/magento/magento2/blob/a5fa3af3b16bb03dcc01068aed0c58d8993fd092/lib/internal/Magento/Framework/Session/SessionManager.php#L242) and [here](https://github.com/magento/magento2/blob/a5fa3af3b16bb03dcc01068aed0c58d8993fd092/lib/internal/Magento/Framework/Session/SessionManager.php#L314), the implementator _assumes_ `Magento\Framework\Session\StorageInterface` as being `Magento\Framework\DataObject`. Which incidentally is, but that's not in the contract.

Maybe there is a BC-friendly way of refactoring this, but I can't think of one. Ideally, `Magento\Framework\Session\StorageInterface` should have all those `addData`, `unsetData` etc. I'd really like it to NOT rely on magic, so I would rather have `setData`, `unsetData`, `hasData` and `getData` as interface methods. Makes it easier and obvious that the session/storage has this behaviour.

**Comment by mazhalai** [comment]
@adragus-inviqa thank you for reporting, we have created MAGETWO-53472 to fix.

**Comment by magento-engcom-team** [comment]
@adragus-inviqa, thank you for your report.
We've created internal ticket(s) MAGETWO-84470 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @adragus-inviqa

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@adragus-inviqa thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
