### ISSUE TITLE
CMS page is loosing routes on multiple edit

### ISSUE THREAD

**Issue by krejcif** [magento/magento2#4706]
## Steps to reproduce
1. Install Magento Enteprise 2.0.6
2. Create more CMS pages eg. four
3. Check more of them and edit multiple http://prntscr.com/b8ddgp
4. Change for example layout column
5. Apply 
6. Save Edits 
## Expected result

CMS Pages will be still available on their URL keys 
## Actual result

CMS pages lost routes (probably url rewrites) but URL keys is still the same in CMS page edit form.

Error: Front controller reached 100 router match iterations

**Comment by krejcif** [comment]
It can't be fixed by re-saving CMS page. Page has to be removed and created again.

**Comment by shiftedreality** [comment]
Hi @magexo 

Thank you for reporting. 
Internal ticket MAGETWO-53495 was created to resolve this issue.

**Comment by BaDos** [comment]
Hi @magexo 
I cannot reproduce this bug on 2.0.6, 2.0.7 and latest develop branch.

How many store views do you have?
What version php do you use?
Please write more information about your environment.
Do you use additional modules or components?

Thanks.

**Comment by BaDos** [comment]
Closed because it isn't reproduced.

If you still facing with it, please add more steps to reproduce, your configuration, browser version and reopen the current ticket.
