### ISSUE TITLE
CI - Build failed

### ISSUE THREAD

**Issue by DavidBelicza** [magento/magento2#4708]
Develop branch does not pass CI tests on Travis-CI, all branches came from develop. So it looks like the whole development flow stuck, this unreliable for me. This should be fixed?

The Travis-CI test result gives: Cannot modify header information - headers already sent by (output started at /home/travis/build/magento/magento2/vendor/phpunit/phpunit/src/Util/Printer.php:172

Develop branch is broken for 12 days.

Details: https://travis-ci.org/magento/magento2/jobs/132895836

**Comment by duhon** [comment]
Hello @DoveID 

At the moment everything is fine.
