### ISSUE TITLE
magento 2.0.7 / Set deployment mode to production fails

### ISSUE THREAD

**Issue by yuklia** [magento/magento2#4709]
**Env**
php 7
magento 2.0.7
Ubuntu GNU/Linux
current mode: developer

**Steps to reproduce**
1 removed contents from: `var/generation, var/di, var/cache, var/view_preprocessed, pub/static`
2 run `php bin/magento deploy:mode:set production`

**Expected result**
`Current application mode: production.`
**Actual result**

```
Command returned non-zero exit code:
`php -f /var/www/bin/magento setup:di:compile-multi-tenant 2>&1`
```

**If i run separately** `php -d memory_limit=1G -f /var/www/bin/magento setup:di:compile-multi-tenant 2>&1`
**i get** `On *nix systems, verify the Magento application has permissions to modify files created by the compiler in the "var" directory. For instance, if you run the Magento application using Apache, the owner of the files in the "var" directory should be the Apache user (example command: "chown -R www-data:www-data <MAGENTO_ROOT>/var" where MAGENTO_ROOT is the Magento root directory).`

After run `chown -R www-data:www-data <MAGENTO_ROOT>/var` nothing was changed

**Comment by piotrekkaminski** [comment]
Note that compile multi tenant mode was removed in new versions. Can you provide more information as which user you run the command from command line?

**Comment by yuklia** [comment]
@piotrekkaminski from www-data. 
By the way, where "Note that compile multi tenant mode was removed in new versions" was mentioned ?
i have a brand new version of Magento  2.0.7

**Comment by stamster** [comment]
I have 2.0.7 too, and this works fine.

**Comment by shiftedreality** [comment]
Hi @yuklia 

I was unable to reproduce your error.
To be correct: This notice you get is not an error itself.
Also, I would like to ask you to increase `memory_limit` in `php.ini` file and try again `setup:di:compile-multi-tenant` on latest 2.0.9 version.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
