### ISSUE TITLE
MAGE_MODE not respected after v2.0.7 fresh install

### ISSUE THREAD

**Issue by stamster** [magento/magento2#4712]
## Steps to reproduce
1. Install Magento from `2.0` branch (2.0.7 release) 
2. [nginx configuration] set $MAGE_MODE developer;  fastcgi_param  MAGE_MODE $MAGE_MODE;
3. `magento deploy:mode:show`
## Expected result

`Current application mode: developer.`
## Actual result

`Current application mode: default.`

When I change it manually with:
`magento deploy:mode:set developer`
it works.

**Comment by danny-balance** [comment]
@stamster The CLI doesn't load Nginx configuration, so it can't read your env variable. See my issue #4304

**Comment by stamster** [comment]
Well, 
the exact same setup is on my other instances, the only difference being older Magento 2.0.6. and 2.0.5.
magento deploy:mode:show on that other (older) instances shows correct "developer" mode.

**Comment by stamster** [comment]
I have installed fresh instance - and this issue is present, i.e. I was able to reproduce it in a same manner.

**Comment by danny-balance** [comment]
@stamster As far as I'm aware CLI will never read the nginx configuration (nginx is a webserver, CLI is not a web interface) so this is expected behaviour. `deploy:mode:set` will adjust your `app/etc/env.php` file, check your other instances for this file.

**Comment by stamster** [comment]
I stated that CLI reported correct mode even though I did not set it from CLI, but only on a web server level (MAGE_MODE).
Anyway, if that's what it is, then it should be noted on official documentation. OR to make setup define mode for you during installation, OR change mode from admin panel like a regular option. 
Otherwise, this is just a fraction of a bad design.
