### ISSUE TITLE
Braintree js.braintreegateway is not excluded from minify 

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#4713]
Since the Braintree js.braintreegateway js in not excluded in minify, it fails to load Braintree in checkout when js minification is enabled.
Quick fix: Add following to one of config.xml

```
 <default>
        <dev>
            <js>
                <merge_files>0</merge_files>
                <minify_files>0</minify_files>
                <minify_exclude>/js.braintreegateway.com/</minify_exclude>
            </js>
        </dev>
    </default>
```

**Comment by YevSent** [comment]
This issue duplicated to #3916 and already resolved in the develop branch.
Closing this issue, please feel free contacting us if you have any further issues.
