### ISSUE TITLE
2.1 RC - Custom options not draggable from page to page

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4715]
## Steps to reproduce
1. Edit product with custom options with more than 20 options
## Expected result
1. Options draggable
## Actual result
1. Can't drag options between pages

<img width="1266" alt="screen shot 2016-05-26 at 15 28 09" src="https://cloud.githubusercontent.com/assets/710612/15574533/97142398-2356-11e6-84d1-aed71e4d283b.png">

**Comment by antboiko** [comment]
Hi @rasmuswikman , thanks for your inquiry. We've created internal ticket MAGETWO-53590 for this improvement and added it to the backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/2-1-RC-Custom-options-not-draggable-from-page-to-page/idi-p/46334).
