### ISSUE TITLE
Admin ajax request when profiler is enabled - Magento 2.0.7

### ISSUE THREAD

**Issue by AymericJoubert** [magento/magento2#4717]
When profiler is enabled, the admin ajax calls fails and return error 500.
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Enable MAGE_PROFILER
3. Go to Store / Configuration / General / General / Store Information
4. Choose a Country in the list and Save Config
## Expected result
1. Country value is stored in core_config_data table and visible in admin
## Actual result
1. We are redirected on the admin dashboard page
2. Country value isn't stored

If we manually store the information in the table via setup, we cannot access Store / Configuration page anymore, we are always redirected on dashboard page.

**Comment by duhon** [comment]
Please clarify you are using version 2.0.7 or latest version from branch develop?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
