### ISSUE TITLE
[2.0.7] Force Sign-In => This user has no tokens.

### ISSUE THREAD

**Issue by peec** [magento/magento2#4718]
Version: 2.0.7
## Steps to reproduce
1. Click on a signed in user
2. Click on Force Sign In
## Expected result
1. Logged in user gets signed out.
## Actual result
1. Error message. "This user has no tokens."

**Comment by sevos1984** [comment]
This is expected behavior, this button used for revoking customer tokens if there are any generated.

**Comment by stasleo** [comment]
What kind of tokens can customer have? I could not understand how this option works and what it does. I thought that it is kinda "Login as Customer", but it's not, apparently.
