### ISSUE TITLE
Cron when defined in db has no name property

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#4719]
## Steps to reproduce
1. As example I use xtento product feed generator, but it doesn't matter as any will do
2. In core_config_data table there are entries:

```
|       262 | default |        0 | crontab/default/jobs/xtento_productexport_profile_1_cron/schedule/cron_expr | 0 * * * *                                 |
|       263 | default |        0 | crontab/default/jobs/xtento_productexport_profile_1_cron/run/model          | Xtento\ProductExport\Cron\Export::execute |

```
1. When \Magento\Cron\Model\Config::getJobs() is executed - array of the jobs from database will not have name property as xml ones.
2. This f.e. will break n98magerun sys:cron:list as it expects name to be set - https://github.com/netz98/n98-magerun2/blob/master/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php#L67
## Expected result
1. Consistent array of cron jobs with same properties

```
Array
(
    [schedule] => "0 * * * *"
    [instance] => "Xtento\ProductExport\Cron\Export"
    [method] => "execute"
    [name] => "something here"
)
```
## Actual result
1. Cronjobs from database have no name

```
Array
(
    [schedule] => "0 * * * *"
    [instance] => "Xtento\ProductExport\Cron\Export"
    [method] => "execute"
)
```

Fix:

in Magento\Cron\Model\Config\Converter\Db _extractParams() method should have process name method f.e.

``` php
    protected function _extractParams(array $cronTab)
    {
        $result = [];
        foreach ($cronTab as $groupName => $groupConfig) {
            $jobs = $groupConfig['jobs'];
            foreach ($jobs as $jobName => $value) {
                $result[$groupName][$jobName] = $value;

                if (isset($value['schedule']) && is_array($value['schedule'])) {
                    $this->_processConfigParam($value, $jobName, $result[$groupName]);
                    $this->_processScheduleParam($value, $jobName, $result[$groupName]);
                }

                $this->_processRunModel($value, $jobName, $result[$groupName]);
                $this->_processName($value, $jobName, $result[$groupName]);
            }
        }
        return $result;
    }

    /**
     * @param array $jobConfig
     * @param       $jobName
     * @param array $result
     */
    protected function _processName(array $jobConfig, $jobName, array &$result)
    {
        $result[$jobName]['name'] = strtolower($jobName);
    }
```

**Comment by wert2all** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
