### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '.', expecting ')' in /path/UpdateLoggerFactory.php on line 31

### ISSUE THREAD

**Issue by watermark** [magento/magento2#4722]
## Steps to reproduce
1. Fresh install of 2.0.7 on PHP 5.5.x
2. Complete install process via web browser
3. Run a cron script, ie 'php -f update/cron.php'
## Expected result
1. It to run without issue
## Actual result
1. PHP Parse error:  syntax error, unexpected '.', expecting ')' in /home/user/public_html/update/app/code/Magento/Update/UpdateLoggerFactory.php on line 31
## Fix

This is a PHP 5.5 specific issue.  New features to function defaults were added in 5.6.  http://php.net/migration56.new-features#migration56.new-features.const-scalar-exprs

**Comment by mazhalai** [comment]
@watermark we are going to drop support for 5.5 in future releases. http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1CE.html
I would suggest you to upgrade your php version.

**Comment by watermark** [comment]
@mazhalai I appreciate the information.  I believe 2.0.x intended to support php 5.5?

**Comment by dsikkema-magento** [comment]
@watermark, yes, 2.0.x supports 5.5, but there will be future Magento 2.x  releases which won't support 5.5.

**Comment by mazhalai** [comment]
@watermark we have created MAGETWO-53524 to investigate and fix.

**Comment by elenleonova** [comment]
Hi @watermark, thanks for reporting the issue. We have acknowledged that and provided the patch that can fix the issue on PHP 5.5. You can find more details here: http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_207-upgrade.html
In case of any issues, feel free to reopen this issue or open a new one.
