### ISSUE TITLE
LocalStorage of the setup installer is not restricted by path

### ISSUE THREAD

**Issue by fooman** [magento/magento2#4723]
## Steps to reproduce
1. Install Magento any 2.x version into a subfolder ie into `http://example.com/m2-205/` using the Web Setup Installer
2. Install any other Magento version into a subfolder of the same domain ie into `http://example.com/m2-210-rc1/` using the Web Setup installer
## Expected result
1. The installer should not have any knowledge of the installation values of the first install
## Actual result
1. Values during the second install are populated taking information from the first installation

**Comment by mazhalai** [comment]
Thank you @fooman we have created MAGETWO-53546 to investigate and fix.

**Comment by bwaters** [comment]
@fooman -- having a little trouble reproducing.  Did you unzip the second installation version straight over the old version or did you unzip them each in their own subdirectories?

**Comment by fooman** [comment]
thanks @bwaters for looking into it. Yes I unzipped into separate subdirectories.

**Comment by bwaters** [comment]
I was not able to reproduce unpacking from separate folders.  None of my form fields were poplulated from first install.  Did you use a different database or database prefix for second install?  Which values were being carried across?  Can you give me a step by step to duplicate?

**Comment by dsikkema-magento** [comment]
@fooman also couldn't reproduce. I do notice that on the database page on both site1 and site2, root and localhost are populated but that's not from site info bleeding between sites but rather just they are defaults.

Now, to clarify, do you mean there are autocomplete suggestions, or field values get values actually get inserted? I think you mean the latter, but I'm asking because I also don't see it.

Also - which browser?

**Comment by dsikkema-magento** [comment]
I can reproduce now - I have to stop the installation flow for site1 at Step 6, without actually installing. After I install, all the LocalStorage gets wiped away, but if I start installing site2 before site1 completes install then form data bleeds over. Can you confirm that behavior, or are you actually seeing a failure to wipe out local storage after the install finishes?

**Comment by fooman** [comment]
@dsikkema I think you are right that the first install might not have finished. If I am not mistaken one other scenario is to completely finish the install and then go the Web Setup Wizard to for example install an additional extension, and then start a separate install.

**Comment by dsikkema-magento** [comment]
web setup wizard doesn't have the same fields as the web setup installer does it? Which fields could bleed together between those two?

Just for anyone browsing this thread, the workaround would be to go into developer mode of the browser on delete entries inside of "local storage" under the Magento domain.

**Comment by fooman** [comment]
I currently have Setup Installer displaying

"We're making sure your server environment is ready for /var/www/m2/vendor/fooman/sameorderinvoicenumber-m2/composer.json to be installed."

instead of

"We're making sure your server environment is ready for Magento to be installed."

on the Readiness Check Step. Please note that this is in the folder /var/www/m2-inte.

So maybe it's only `ngStorage-titles` that's shared or maybe it's coming from `ngStorage-moduleName`.

**Comment by dsikkema-magento** [comment]
Got it, will add to internal bug description

**Comment by magento-engcom-team** [comment]
@fooman, thank you for your report.
We've created internal ticket(s) MAGETWO-53546 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
