### ISSUE TITLE
Admin product enabled/disabled UI is not obvious

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#4724]
The admin toggle that demonstrates whether a product is enabled is easy to miss, especially on a wide screen:

![magento admin-zamqk](https://cloud.githubusercontent.com/assets/129031/15587086/35a93584-234d-11e6-99b2-06f80fc7fdd8.png)

I'd recommend moving it and making the disabled state red:

![8 -vdmxz](https://cloud.githubusercontent.com/assets/129031/15587147/8fad327e-234d-11e6-8bc5-62a09ae6f328.png)

And then change the enabled state to green:

![8 -uj3w4](https://cloud.githubusercontent.com/assets/129031/15587194/c1bfa508-234d-11e6-8392-2327ef36ce5f.png)

At the very least, the colors should change to red/green. But I think moving it would also make it easier to spot.

**Comment by pboisvert** [comment]
thanks Erik for the suggestion

@antboiko can you run this one by the UX team for their view and if valid file a Jira ticket and close this issue

**Comment by erikhansen** [comment]
@pboisvert For what it's worth, I had a tech-savvy client spend a good amount of time yesterday, trying to figure out why a product wasn't showing on the frontend. She checked all of the settings she knew to check (visibility, in stock, assigned to correct website, etc), but had to come to me for help when it still wasn't showing. Turns out the product was "Offline" (aka, disabled), but she didn't notice the toggle.

And she is not the first person I've seen miss that toggle.

**Comment by antboiko** [comment]
@erikhansen 

Hello Erik, thank you for the suggestion.

Please let me show you how this option will look in 2.1
![enable product - yes](https://cloud.githubusercontent.com/assets/15442705/15612304/df89ff18-2436-11e6-8a86-8fb5b6dbf43a.png)
![enable product - no](https://cloud.githubusercontent.com/assets/15442705/15612310/e7658df6-2436-11e6-815e-8ac3be812f44.png)

"Enable Product" is more visible now, it's aligned with other labels and is set to "Yes" (green state of toggle) by default during product creation.

Please let me know your thoughts on this.

Thanks,
Anton.

**Comment by erikhansen** [comment]
@antboiko I think the UI in Magento 2.1 is much better! My only suggestion would to be change the disabled state of the toggle from grey to red, as it will make the state of the toggle more clear. Green/red are pretty well-established colors for on/off.

**Comment by antboiko** [comment]
@erikhansen 

Hello Erik, thank you once again for your suggestion. I've added internal ticket MAGETWO-53794 to the backlog to have it considered by the UX team.

I'm closing the ticket. Please feel free to reopen if you have additional questions.

Best,
Anton.

**Comment by erikhansen** [comment]
@antboiko Thanks! I appreciate your team's willingness to accept UI feedback from the community.

**Comment by erikhansen** [comment]
@antboiko After playing around with the Magento 2.1 interface a little bit more, I'm actually going to retract my recommendation to change to red for the disabled state, as I think grey works well. So feel free to close MAGETWO-53794. 

![image](https://cloud.githubusercontent.com/assets/129031/16313531/3cb839d0-393f-11e6-86fd-054bf3a5ea62.png)

**Comment by antboiko** [comment]
Hello @erikhansen , thanks for your feedback.

Best,
Anton.
