### ISSUE TITLE
Static files are not generated for custom theme

### ISSUE THREAD

**Issue by OgreMHDW** [magento/magento2#4725]
## Steps to reproduce
1. The theme is installed in app/design
2. The theme in set in store configuration
## Expected result
1. Running php bin/magento setup:static-content:deploy should deploy theme to pub/static folder
2. Site should read normally.
## Actual result
1. php bin/magento setup:static-content:deploy only deploys the Magento/blank and Magento/luma themes to the pub/static folder.
2. Custom theme is not present in pub/static
3. JS and CSS files report 404 because they cannot be found in pub/static/frontend/Vendor/Themename/en_US/css/ folder

**Comment by crantron** [comment]
What is your parent theme?

**Comment by wert2all** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by crantron** [comment]
@wert2all i like how people post and never check up on it...waste of time.

**Comment by developer-lindner** [comment]
Almost similiar to #5393. @OgreMHDW missed to configure themes.js

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by PascalBrouwers** [comment]
I had the same thing. For anyone who also has this. Adding an empty less file to web/css fixed it for me.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72253
