### ISSUE TITLE
Access Token & Access Token Secret getting cleared

### ISSUE THREAD

**Issue by JaggedJax** [magento/magento2#4727]
### Preconditions
Magento 2.0.7

## Steps to reproduce
1. Complete oAuth connection and acquire access token and secret
## Expected result
1. Access token and secret last indefinitely 
## Actual result
1. If the Access token has not been used in Approx 1-2 hours, Magento2 deletes the Access token and Access Token Secret under the Integration Details so API calls no longer work.

What could be causing this? Magento2 docs says this access token should last indefinitely.

I know it's the actual Access token that's disappearing (and not the Request token) because the one I have matches the one listed in Magento (until it disappears), and it's the token I get after making the following calls (using the same oAuth library Magento uses):

```
    $credentials = new \OAuth\Common\Consumer\Credentials($consumerKey, $consumerSecret, $url);
    $client = new OauthClient($credentials, $url);
    $requestToken = $client->requestRequestToken();

    $accessToken = $client->requestAccessToken(
        $requestToken->getRequestToken(),
        $oauthVerifier,
        $requestToken->getRequestTokenSecret()
    );
```

**Comment by magento-engcom-team** [comment]
Hi @JaggedJax 
Token Lifetime can be change in Config > Services > OAuth >Access Token Expiration

**Comment by magento-engcom-team** [comment]
@JaggedJax, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by JaggedJax** [comment]
According to this page:

- http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-token.html

the "Access Token Expiration" page is for Token-based authentication, but I was using oAuth-based authentication. If there is a limit that also applies to oAuth access tokens, can you please update these documentation pages with that information? 

- http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html
- http://devdocs.magento.com/guides/v2.1/get-started/authentication/gs-authentication-oauth.html
- http://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication-oauth.html

That page specifically says:

> Access tokens are long-lived and will not expire unless the merchant revokes access to the extension.

It's possible this was an issue with a specific version of Magento 2 and is no longer an issue, as we have many current Magento2 connections without this issue and it's been so long I don't remember which account had this problem.

**Comment by magento-engcom-team** [comment]
@JaggedJax, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
