### ISSUE TITLE
Shipping notification email missing product info

### ISSUE THREAD

**Issue by JaggedJax** [magento/magento2#4728]
## Steps to reproduce
1. Fresh install of Magento 2.0.7
2. Create a shipment for an order via the API and add tracking
3. Generate a customer shipment notification email using: POST /V1/shipment/{id}/emails
## Expected result
1. Email sent to customer listing tracking info and products shipped
## Actual result
1. Email contains all the correct information, except where it lists the products, the product names and skus are blank.

The items used in my test did have SKUs setup for them. One item was a simple product and one was configurable.

Screenshot of email missing product information. The default email templates were not modified at all: 
![image](https://cloud.githubusercontent.com/assets/553588/15595317/c983038c-2372-11e6-80f9-f8876336cbc5.png)

**Comment by ruby10** [comment]
This issue is coming for the shipments created via Magento2 API "V1/shipment", for shipments created from admin panel email is containing item sku and other related data, Please do provide update on this issue

**Comment by NadiyaS** [comment]
Hi @JaggedJax ,
thank you for reporting this issue. Internal ticket MAGETWO-53810 was created.

**Comment by ruby10** [comment]
@NadiyaS  , do we have any news on it?

**Comment by rugirl** [comment]
Hi @NadiyaS, @ruby10, @JaggedJax,
Do you have an update about this issue yet?

**Comment by kilis** [comment]
Any update this issue?

**Comment by magento-engcom-team** [comment]
@JaggedJax, thank you for your report.
We've created internal ticket(s) MAGETWO-53810 to track progress on the issue.

**Comment by keyurshah070** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by NikZh** [comment]
This issue is coming for the shipments created via Magento2 API "V1/shipment",
You can create shipment with POST "/V1/order/:orderId/ship" API call
Then send email via POST "/V1/shipment/{id}/emails" with all correct information

**Comment by marciowebjump** [comment]
#Imagine2018

**Comment by magento-engcom-team** [comment]
@marciowebjump thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by marciowebjump** [comment]
Can't reproduce the issue in 2.1.X and 2.2.X
Steps I have made trying to reproduce the error:

1. Create a simple product;
2. Create a configurable product with 3 associated simple products using 2 configurable attributes (Size and Color);
3. Make an order in frontend with these 2 items and qty = 1 for each one;
4. Create the manually invoice for order;
5. Create the shipment to order and added tracking with using the request below:
POST: http://STORE_URL/rest/default/V1/order/:order_id/ship
`{
  "items": [
    {
       "order_item_id": 1,
       "qty": 1
     },
     {
            "order_item_id": 2,
            "qty": 1
          }
  ],
  "notify": false,
  "appendComment": false,
  "tracks": [
    {
      "track_number": "1Y-9876543210",
      "title": "United Parcel Service",
      "carrier_code": "custom"
    }
  ]
}`
6. After that, send the shipment email using the request below:
POST https://STORE_URL/rest/default/V1/shipment/:shipment_id/emails

Screenshot of result email:
![image](https://user-images.githubusercontent.com/36997404/39089910-6a28242c-45a7-11e8-9020-3029cdd94545.png)

**Comment by ishakhsuvarov** [comment]
Thank you @marciowebjump for investigation.
We are closing this now per your comment

**Comment by niksjethva** [comment]
I have faced the same issue(Order Email not showing items list) after migrations from Magento 1 to Magento 2.3. 

**You can make the following changes to get resolved from this issue :**
I am sure, this happens almost in 2.3.5 AND 2.3.5-p1

`The solution is open 'email_template' table from database, find column 'is_legacy' and set is_legacy = 1.`

I hope it will helpful to you.

Thanks!
