### ISSUE TITLE
error when run exec php file

### ISSUE THREAD

**Issue by tranductrong92** [magento/magento2#4732]
Magento\Framework\Exception\LocalizedException: The specified "/var/www/magento2module/var/generation/Magento/Catalog/Model/Product/Action/Interceptor.php.14051" file could not be written Warning!file_put_contents(/var/www/magento2module/var/generation/Magento/Catalog/Model/Product/Action/Interceptor.php.14051): failed to open stream: Permission denied in /var/www/magento2module/vendor/magento/framework/Code/Generator.php:103
Stack trace:
#0 /var/www/magento2module/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\Catalog...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\Catalog...')
#2 [internal function]: spl_autoload_call('Magento\Catalog...')
#3 /var/www/magento2module/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\Catalog...')
#4 /var/www/magento2module/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Catalog...')
#5 /var/www/magento2module/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\Catalog...')
#6 /var/www/magento2module/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Catalog...')
#7 /var/www/magento2module/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Catalog...')
#8 /var/www/magento2module/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Catalog...', NULL, 'productAction', 'WiseRobot\Chann...')
#9 /var/www/magento2module/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('WiseRobot\Chann...', Array, Array)
#10 /var/www/magento2module/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('WiseRobot\Chann...', Array)
#11 /var/www/magento2module/channeladvisorapi/execUploadImportApp.php(54): Magento\Framework\ObjectManager\ObjectManager->create('WiseRobot\Chann...')
#12 /var/www/magento2module/vendor/magento/framework/App/Bootstrap.php(258): execUploadImportApp->launch()
#13 /var/www/magento2module/channeladvisorapi/execUploadImport.php(21): Magento\Framework\App\Bootstrap->run(Object(execUploadImportApp))
#14 {main} [] []

**Comment by yssource** [comment]
Files Permission denied, try to `sudo chmod 777 -R .` as a workaround
