### ISSUE TITLE
Catalog data disappears in the store front after admin user role creation and admin login with new role

### ISSUE THREAD

**Issue by jmackiol-dotsource** [magento/magento2#4734]
## Steps to reproduce
1. Install Magento EE 2.0.0 or 2.0.7 using composer.
2. Add new catalog root category
3. Create new website
4. Create new store with website from step 3 and root category from step 2
5. Create new store view for store from step 4
6. Create admin user role with limited access to the website from step 3
7. Create new admin user with role from step 6
8. Logout with current admin user
9. Login with admin user from step 7
10. Load any store front site
## Expected result

Existing categories and products are Visible
## Actual result

All products and categories are not visible

**Comment by oleg-onufer** [comment]
Hi @jmackiol-dotsource.
This issue can be actual for Enterprise Edition only, please address it to Magento Support.
