### ISSUE TITLE
indexes missing from admin panel

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#4735]
```
<indexer id="catalog_product_flat" view_id="catalog_product_flat" class="Magento\Catalog\Model\Indexer\Product\Flat">
        <title translate="true">Product Flat Data</title>
        <description translate="true">Reorganize EAV product structure to flat structure</description>
    </indexer>
    <indexer id="catalog_category_flat" view_id="catalog_category_flat" class="Magento\Catalog\Model\Indexer\Category\Flat">
        <title translate="true">Category Flat Data</title>
        <description translate="true">Reorganize EAV category structure to flat structure</description>
    </indexer>
```

In admin panel both  catalog_product_flat ,catalog_category_flat indexes are missing.

![indexes](https://cloud.githubusercontent.com/assets/7636894/15604616/eca68710-241e-11e6-8297-5e0c8f68e446.png)

**Comment by sivajik34** [comment]
i think this is not an issue  but still confusion.why its not listed in the grid ? how to use these two indexes?

**Comment by katmoon** [comment]
Hi @sivajik34 

Flat indexers can be turned on in Stores > Configuration > Catalog > Catalog > Storefront > Use Flat Catalog Category/Product = Yes

Does this answers your question?

Thanks,
Kateryna.

**Comment by sivajik34** [comment]
Thank you.sorry for silly question/ raising an issue.
