### ISSUE TITLE
Magento 2 project files in "/dev/tests/integration/etc/" are removed by "composer update" with new Magento 2 release

### ISSUE THREAD

**Issue by jmackiol-dotsource** [magento/magento2#4736]
## Steps to reproduce
1. install Magento 2 EE (version 2.0.5 / 2.0.6) with composer.json created by "composer create-project"
2. add project specific files to the project root and "/dev/tests/integration/etc/install-config-mysql.php"
3. Run "composer create-project"
4. Check if the file  "/dev/tests/integration/etc/install-config-mysql.php" exists is positive 
5. Update the Magento 2 version in composer.json to 2.0.6 / 2.0.7 (e.g. "require": {"magento/product-enterprise-edition": "2.0.7"})
6. Run "composer update"
## Expected result

Check if the file  "/dev/tests/integration/etc/install-config-mysql.php" exists remains positive 
## Actual result

Check if the file  "/dev/tests/integration/etc/install-config-mysql.php" exists is negative - file is removed
## Note

Clean Install with any version retains the file and upgrade from any recent EE to another EE removes the file. Update from CE 2.0.5 to EE 2.0.5 keeps the file. 
Other project files are not touched by the upgrade between versions

**Comment by Vinai** [comment]
Thanks for the report, closing due to duplicate existing issue https://github.com/magento/magento2/issues/3249
