### ISSUE TITLE
CSS files missing on dashboard

### ISSUE THREAD

**Issue by BeppeT** [magento/magento2#4740]
I updated Magento CE to the version 2.0.7 by composer

Now (only) in dashboard page the CSS files are missing

**Comment by BeppeT** [comment]
I have encountered the same problem in other pages

**Comment by wert2all** [comment]
Please, provide the version of Magento which you update from.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
