### ISSUE TITLE
Use database of 2.0.4 in 2.0.7

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#4744]
I need to know if is it feasible to use database of 2.0.4 in 2.0.7? i have downloaded the latest version i.e. 2.0.7 and i am having trouble in importing (https://github.com/magento/magento2/issues/4743) the products from 2.0.4 to 2.0.7, so i am considering this option.

**Comment by mazhalai** [comment]
@Taral-Patoliya you should get 2.0.4 code base and migrate from your existing db to the new one after install. Then you can perform upgrade to 2.0.7 via [CLI](http://devdocs.magento.com/guides/v2.0/comp-mgr/cli/cli-upgrade.html) (preferred if you have access to CLI) or [Web](http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html).

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
