### ISSUE TITLE
Missing styles for section in Reports

### ISSUE THREAD

**Issue by fpsthirty** [magento/magento2#4746]
Magento v2.0.6
Sections: Ordered, Order Total, Order Count, New
Shortcoming: mistakenly missing styles for drop-down list: http://joxi.ru/V2VR3MQI04nJ72.jpg
Elements ID: gridProductsSold_report_period, gridTotalsCustomer_report_period, gridAccounts_report_period
**Expected class**: admin__control-select

Sections: Views, Bestsellers, Orders, Tax, Invoiced, Shipping, Refunds, Coupons
Shortcoming: mistakenly missing styles for input http://joxi.ru/E2pWpJRHBqkDVm.jpg
Elements ID: sales_report_from, sales_report_to
**Expected class**: admin__control-text

**Comment by MomotenkoNatalia** [comment]
@fpsthirty Thanks for reporting this issue! Which Magento version do you use?

**Comment by fpsthirty** [comment]
@MomotenkoNatalia , v2.0.6

**Comment by vil11** [comment]
@fpsthirty 
Hi Alexander!
Described issues aren't reproducible on current develop branch.

## 

:sunny: dvilchynskyi, M2 QA.

**Comment by andimov** [comment]
@fpsthirty 
Do you have any updates for this issue?
Could you please provide more information? Like versions of PHP, MySQL and web server.
Also, it can be helpful if you describe settings of your Magento instance: was it the fresh install or upgrade from the previous version?
Do you have many store views? Maybe some other settings.

**Comment by andimov** [comment]
@fpsthirty 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
