### ISSUE TITLE
Emoji: mistaken user registration with a blank firstname and lastname from phone.

### ISSUE THREAD

**Issue by fpsthirty** [magento/magento2#4748]
## Magento v2.0.6, Steps to reproduce:
1. From mobile phone fill in the fields Name and surname only emoji-symbols: http://joxi.ru/VrwWzjgHKQqxnr.jpg
2. Fill in all other fields valid data.
3. Click "Create an Account".
## Expected result:

After click "Create an Account" see message: "This is a required field.".
## Actual result:

User was created, in admin panel firstname and lastname are empty for this user: http://joxi.ru/Dr8WPw0Hk1bVdA

**Comment by sevos1984** [comment]
Created internal issue MAGETWO-53548, thanks for reporting!

**Comment by magento-engcom-team** [comment]
@fpsthirty, thank you for your report.
We've created internal ticket(s) MAGETWO-53548 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@fpsthirty, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
