### ISSUE TITLE
Pressing enter in SKU field under related products saves the product instead of entering the SKU number

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#4751]
## Steps to reproduce
1. Edit product
2. Go to related products tab
3. Reset filter to show all products
4. Type in a sku number in the sku field
5. Hit enter
## Expected result

The system searches for that sku number and displays it.
## Actual result

Product gets saved and returns to main catalog screen. SKU search only works if search button is pressed.

This is not a big issue just more of an inconvenience. Logically, if a sku number is typed and then enter is hit, the sku search would run instead of the save function.

**Comment by Ctucker9233** [comment]
It is still present in 2.0.7. Is this issue better suited as a pull request?

**Comment by smoskaluk** [comment]
Internal ticket created MAGETWO-70054

**Comment by magento-engcom-team** [comment]
@Ctucker9233, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Ctucker9233** [comment]
@magento-engcom-team I confirm it has been fixed.
