### ISSUE TITLE
Default Country (for address) at checkout is always United States

### ISSUE THREAD

**Issue by wittness87** [magento/magento2#4753]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. All settings in backend have been changed so default country and default shipping country are United Kingdom.
3. Add product to cart and proceed to checkout.
## Expected result
1. Add product to cart and proceed to checkout, United Kingdom should be the default shipping country (for address)
## Actual result
1. Install Magento from `develop` branch.
2. All settings in backend have been changed so default country and default shipping country are United Kingdom.
3. Add product to cart and proceed to checkout, United States is the default shipping country
4. This also affects the calculated shipping costs at the shopping cart page as it assumes the shipping country (for address) is United States.  We are a UK based company.

**Comment by iogavin** [comment]
any update on this? we have the same problem.

**Comment by wittness87** [comment]
Turns out it was something very straightforward!

If you go to Sales > Tax you will find that the default country is United States. 

Change that and you should be okay!

**Comment by iogavin** [comment]
Ahh brilliant, thanks very much for your quick reply.

**Comment by pboisvert** [comment]
seems like the issue has been resolved by changing the default country option so closing this issue. Please reopen if this is not the case.
