### ISSUE TITLE
Theme update selection missing in 2.1 Branch

### ISSUE THREAD

**Issue by duffner** [magento/magento2#4754]
## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Went to Stores -> Design ->  Looked for themes (Nothing Found)
## Expected result
1. Have the admin ability to change the theme
## Actual result
1. Only robot settings displaying in Design Tab 
   <img width="1245" alt="screen shot 2016-05-27 at 3 47 08 pm" src="https://cloud.githubusercontent.com/assets/7387019/15620832/4e2f7e9e-2422-11e6-9d39-0f4117f1607d.png">

**Comment by sivajik34** [comment]
@duffner go to content ->design->configuration .you can find there.

**Comment by martins-scandiweb** [comment]
@sivajik34 Hi, I created 2 new store views, but they do not appear under content ->design->configuration

I logged in, logged out from admin, refreshed caches, but still did not appear. They should appear after creation, right ?

Can't assign theme to new store views after 2.1 update. I guess will need to do in db manually.

**Comment by s00071609** [comment]
Did anyone find solution to this?? 
![capture-missinghtml](https://cloud.githubusercontent.com/assets/19631643/16922706/1e81344c-4d5a-11e6-8921-a18196db262d.PNG)
Same issue here - only Robot section showing after update to magento 2.1. Everything else is missing. I also have multi website and need to change the html tag and other seo stuff but the section does not exist. I did everything i could, cleared all cache, generation, full page cache, admin html content, ran compiler, static deply, no help. 

Not sure how to edit sections for multi store from db, but few things in 2.1 are quite troubling.

Not sure if anyone noticed - if you check your bundle products - the section to display bundle option in Product is also missing.

**Comment by pboisvert** [comment]
@s00071609  content has been moved as noted in this comment https://github.com/magento/magento2/issues/4754#issuecomment-222294334 

if you have other issues please check for existing issues and if not found please file a new issue following the requested format.

**Comment by devdesco-ceo** [comment]
The Design section in 2.1.x is completely screwed up.
