### ISSUE TITLE
Magento 2.0.7 Component Manager Problem (Please wait loading), Checking Component Dependency Problem

### ISSUE THREAD

**Issue by neoshd** [magento/magento2#4756]
Hi,
i installed magento 2.0.7
The problem is that, when i am in the Component Maganer, and i Sync my account, it showns an infinite "please wait" loading, and i can't install any extension at all. (see photo)

So i decided to upgrade to the latest version of magento 2.1 rc1, but i have this problem (see photo)
and can't continue.

How can i resolve this iusses, i can't do anything.
Thank you.

![loading](https://cloud.githubusercontent.com/assets/19625383/15628366/67d062ae-24ff-11e6-9f12-6fe753411c70.png)
![can t upgrade](https://cloud.githubusercontent.com/assets/19625383/15628367/67d1b640-24ff-11e6-9aaa-07909c8828b3.png)

**Comment by ghost** [comment]
I advise against upgrading because RC1 is probably less stable than 2.0.7.

From your Magento server, can you ping `repo.magento.com`? What does `nslookup` tell you?

**Comment by neoshd** [comment]
it shows me "ping: icmp open socket: Operation not permitted"
how can i solve it?
`

**Comment by ghost** [comment]
Same problem here. I upgraded from setup wizard from 2.0.6. I can get to system upgrade and system config. I've tried with cache disabled and enabled. Any help?
![image](https://cloud.githubusercontent.com/assets/18555775/15630292/47d266b6-24e9-11e6-97b3-49a8569be450.png)

**Comment by neoshd** [comment]
i set to 755 the permissions of public_html folder, and the Checking Component Dependency problem is gone.
But now i have another problem:
i have to disable the checkout module of magento, and in the readiness check i have the Checking Component Dependency problem again.

**Comment by ghost** [comment]
Try running the [module dependency report](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-depen.html#config-cli-depend-rpt-run) and disable the other modules that checkout depends on.

**Comment by neoshd** [comment]
i resolved the checkout module problem, but remains the most important problem:
can't sync the profile and installing the extensions..

**Comment by mazhalai** [comment]
@neoshd  @Jeff7306 have you entered your keys under `System config`

**Comment by ghost** [comment]
@mazhalai yes i have entered the keys. I was able to log into Component Manager with 2.0.6.. I can get to "system config" and "system upgrade"
Thanks

**Comment by neoshd** [comment]
@mazhalai yes i did, still not working

**Comment by mazhalai** [comment]
@nagno any errors on brower's console?

**Comment by nagno** [comment]
@mazhalai you might wanted to ask @neoshd about the issue...

**Comment by mazhalai** [comment]
@nagno thank you! 
@neoshd any errors on browser console?

**Comment by neoshd** [comment]
![1](https://cloud.githubusercontent.com/assets/19625383/15715731/ddefd014-281f-11e6-9aff-b5a4f500dd71.png)

**Comment by mazhalai** [comment]
@neoshd Can you please check what is causing the 500 error on that ajax call?
You can copy paste the url and open it in a new tab.

**Comment by neoshd** [comment]
![q](https://cloud.githubusercontent.com/assets/19625383/15721046/78fcd57c-2837-11e6-9dba-32d81553d482.png)

**Comment by mazhalai** [comment]
@neoshd do you not have a favicon.ico file? What is the permission on it?

**Comment by neoshd** [comment]
i have it in the frontend and backend,it's weird, i don't why it doesn't load it in this url.
i'm on a shared hosting so i put the write permissions for:
vendor
app/etc
lib
pub/static

**Comment by mazhalai** [comment]
@neoshd What is the permission for favicon.ico?

**Comment by neoshd** [comment]
664, as the magento standard permission for the files.

**Comment by V0IDNIL** [comment]
I am also having the same problem with the component manager being unable to sync.

The error 500 message for http://example.com/setup/index.php/component-grid/sync is

Fatal error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /home/example/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

**Comment by ycherfan** [comment]
@neoshd @mazhalai I'm facing the exactly same issue here. I can't sync dependencies and I can't upgrade to 2.1 version. Any suggestions?

My current Magento version is 2.0.7.

**Comment by ycherfan** [comment]
That problem is even worse because response body has no content, so i don't no where to start to figure out the root cause of it.

Is there any place where I can see error logs? I suppose that internal server errors (500) is logged in some place.

**Comment by ycherfan** [comment]
"i set to 755 the permissions of public_html folder, and the Checking Component Dependency problem is gone."

It didn't work for me. "Check Component Dependency" continues to throw internal server error (500) with no response body.

![screen shot 2016-06-02 at 1 53 10 pm](https://cloud.githubusercontent.com/assets/499073/15753595/40064a44-28ca-11e6-8e1a-2c7d5576a37b.png)

**Comment by piotrekkaminski** [comment]
@ycherfan  can you provide the error message from web server logs (something like /var/log/apache2/error.log)? 
can you provide output of command line php -i?

**Comment by neoshd** [comment]
@ycherfan
while i was testing, i understood that this problem was a permission issue, so:
 1)i re-entered the cron jobs:
- \* \* \* \* <path_to_binary> -c <ini_file_path> <magento_dir>/bin/magento cron:run | grep -v "Ran jobs by schedule" >> <magento_dir>/var/log/magento.cron.log
- \* \* \* \* <path_to_binary> -c <ini_file_path> <magento_dir>/update/cron.php >> <magento_dir>/var/log/update.cron.log
- \* \* \* \* <path_to_binary> -c <ini_file_path> <magento_dir>/bin/magento setup:cron:run >> <magento_dir>/var/log/setup.cron.log

2)checked permissions (i am on a shared hosting):
write permissions for
vendor 
app/etc
lib
pub/static

3)done a reindex 
with php bin/magento index:reindex

and it's gone.

**Comment by zaghloul2** [comment]
@neoshd 
made all the steps still facing the problem !!
what permission number ?

**Comment by neoshd** [comment]
770

**Comment by zaghloul2** [comment]
still having the Check Component Dependency error

**Comment by ark99** [comment]
@zaghloul2, do you see any errors in browser console or in apache error log?

**Comment by zaghloul2** [comment]
i have tried everything 
cant solve the problem !!

**Comment by mhadianfard** [comment]
Having the same problem here. I think @nantokakantoka nailed it down. Ajax error boils down to a fatal error:

```
Fatal error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73
```

![image](https://cloud.githubusercontent.com/assets/5615108/16095766/2238bd0e-3314-11e6-9fc4-05da0321b608.png)

**Comment by ycherfan** [comment]
Hi all,

I solved that problem setting the memory_limit variable to 1024M and putting a copy of the php.ini inside the folder setup too. 
Also, I have upgraded PHP to version 7.

I hope that it helps you. 

Thanks all!

**Comment by tanya-soroka** [comment]
All could you please tell us if the increasing memory_limit has resolved this problem for you?

**Comment by abhijitbanik2016** [comment]
Magento 2.0.7 Installed through INSTALLATRON App in Easy apache 4 Server with a configuration of php 5.6 and mysql 5.6

After installation Magento market place connected with system config with marketplace key.

Now when I am trying to get sync in component Manager then showing "please wait" and nothing is happening. If I check the error in browser development mode I found 2 error

Error 1: angular.js:8581The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

Error:2 http://www.craftallure.com/setup/index.php/componentGrid/sync 500 (Internal Server Error)(anonymous function)

image

And in the "system upgrade" finding an error

Sorry, we can't take that action right now.
image

error in browser development mode is in below The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

I checked magento Dev site and I settled down Magento Prerequisite With Cronjob and other updates.

In apache error log I found below error [Wed Jun 29 04:23:33.872640 2016] [access_compat:error] [pid 15439] [client 97.74.233.23:36187] AH01797: client denied by server configuration: /home/craftallure/public_html/app/etc/config.php

Its an worst problem I ever found. I consulted with Cpanel Specialist and they are saying there in no error with server. Its my last try or else I have to surrender. 

All solution tried but not working
Please provide some solution.

**Comment by andimov** [comment]
@mhadianfard 
Looks like you have different issue. Do you have any update for it?
@abhijitbanik2016
try to enable developer mode in .htaccess and look at the errors in the response.
Please, also recheck solution https://github.com/magento/magento2/issues/4756#issuecomment-223439006

**Comment by mhadianfard** [comment]
My issue seems to be fixed as of 2.1.0 @andimov

**Comment by veloraven** [comment]
@neoshd is this issue still actual?
If you have any other problems which differ from the originally described one please create separate issues for them.

**Comment by TClilMouse** [comment]
My Component Manager stops working in Magento 2.0.7.
Still not work after upgrade to Magento 2.1, but no error message in console
But getting the following error message after upgrade to 2.1.1

angular.js:8581 The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

solution #4756 doesn't work

**Comment by veloraven** [comment]
@abhijitbanik2016 , @seavenger ,
Could you try to clean Magento cache, browser cache and browser's local storage,  and try again?
If your problem still reproduces please create separate issue for it as it seems to be different problem than originally described in this issue.
Note, to clean browser cache and local storage you can click Ctrl+Shift+Del and select Cache, Offline Website Data, cookies.

**Comment by Sam2k** [comment]
@veloraven , @andimov 

Hi everyone,
I've same issue like @seavenger , @abhijitbanik2016 , @Jeff7306 , @neoshd 
**System Upgrade** works fine but not **Component Manager** ("_Please wait_" message and infinite spinning Wheel).

My config : 
- Debian 8.4, PHP 5.6.24, MySQL MariaDB 10.0.26
- Magento 2.1.1 C.E.

I've tried everything : 
- Clean browser caches
- Reapply file perms (like it's described in Magento Docs)
- Clean and flush Magento cache
- Reindex Magento
- Remove **pub/static** folders and files + deploy static content
- Remove **var/di** **var/generation** **var/cache** **var/page_cache** + recompile

But, nothing work !

If **Component Manager** doesn't want to work via Backend GUI, do you think I can enable/disable modules directly in **app/etc/config.php** ? (and after, do a "setup:upgrade" command, of course)

Thank you for all help you give to me (and to the Mage community).

Regards

**Comment by henrynw** [comment]
Same issue. Any solutions?

**Comment by mitulispace** [comment]
![e7fa7f84-824a-11e6-9df8-44e3809bb1d9](https://cloud.githubusercontent.com/assets/16436069/18823450/cf36288e-83d7-11e6-993b-1c646fce6e6f.PNG)

Same Issue Any Solution....  @ycherfan @mazhalai @veloraven @nagno @MomotenkoNatalia

**Comment by donniesg** [comment]
I just setup a new installation using Magento CE 2.1.1 using PHP 7.0.11 on siteground. I successfully setup the link to marketplace and installed the 1st extension. All seems normal but after the installation, my Component Manager and system config etc, all went into this forever loop. 

I have tried flushing cache and reindex. No effect at all.

Just this morning, when I click back button on the browser during the "forever looping" System Config page, that allows me to click reset to log out. When I key in the private key again to resync, it successfully connects once and shows the message that it is not able to determine the version of one of the modules that was installed earlier. Going to Component Manager after reconnection still end up in the forever looping problem. 

I reset the connection again and check the Component Manager on the reported module with no version. True enough that module does not have a version reflected. Perhaps some syncing issues here because the extension installed created 2 modules and the marketplace side was expecting only one. 

![component manager](https://cloud.githubusercontent.com/assets/22439364/18823733/382d58fa-83ef-11e6-8942-93fb50a87c10.jpeg)

**Comment by ikim-incipio** [comment]
Any update on this issue?
I'm having the same problem with component manager using 2.1.1
I tried every single suggestion but still having issue.
I made sure i have proper permissions and version showing up for each module.

After tinkering with code, I was able to narrow it down to a single function that's causing infinite spinning wheel:

/setup/src/Magento/Setup/Model/PackagesData.php
private function **getPackageAvailableVersions**($package)

I'm gonna keep digging into code but any help is appreciated.

**Comment by erik-augustin** [comment]
increase mem setting  php solved my problem

**Comment by kornblumenapotheke** [comment]
increase mem did not work for me :(
now at 2048M, still in that loop.

**Comment by Sam2k** [comment]
Hi everybody !

Upgrading to Magento 2.1.2 CE and still have the same problem (infinite spinning Wheel).
PHP memory already set at 2048M ...

@donniesg : trying to reset connection and checking again, but still have this damned Wheel

@ikim-incipio : good luck for exploring Magento code, I can't help you for this hard task

I believe somewhere someone must have solution ... Waiting for this.

Thanks

**Comment by prop-physics** [comment]
same problem here on a fresh 2.1.2 composer install

it worked for a bit, installed a few modules from the marketplace and the next day this problem arose

**Comment by kornblumenapotheke** [comment]
Hi,

now installed 2.1.2 CE from tar, mem 1024.

Component Manager works and shows all components from Marketplace, but 
now full of unmet dependencies.
i think I give up on Magento and give oscommerce a try.

Regards,
Gunther

Am 17.10.2016 um 00:22 schrieb Sam2k:

**Comment by benj4m** [comment]
Hi all,

I think I'm having the same issue. Relatively new to Magento. Have installed via cpanel on a godaddy VPS. I've increased PHP memory limit to 2048M, I've deleted all the files, cleared all the caches it's been recommended I clear etc.

When I try and sync the marketplace account, the "please wait" wheel spins indefinitely. So the solution is to upgrade? When I try to upgrade, I get:

Check Component Dependency
We found conflicting component dependencies. Hide detail

For additional assistance, see component dependency help .

Which is the least helpful error message ever to be honest. Anyone have any suggestions, even a stab in the dark, at what I can do now?

Thanks in advance, willing to try anything really to get this working!

Ben.

**Comment by cod3gen** [comment]
Hi All,

Ive had the same issue since the very first release. First i logon to admin then go to Setup Wizard. Press sign in, and add my credentials to Magento and then that famous "please wait" wheel spins indefinitely. Okey, checking error log which shows this:
`AH01797: client denied by server configuration: /home/admin/domains/example.com/public_html/app/etc/config.php`

Then, the whole Magento Installations seems to be almost on freeze when please wait wheel spins indefinitely. Server load is also increasing. To remove this i usually delete all sessions in var, and then do a reset of php-fpm. Then back to admin and login. At this point, my credentials are actually registered, however im not able to "Sync", by doing this, yet again the famous "please wait" wheel spins indefinitely. However, i can go to "System Upgrade" and upgrade my Magento version with Sucess.

It does not mather wheter it is a brand new installation or a older one with third-party modules.

My Server is setup with;
Directadmin CP
CentOS 7.2 (Also tried on Debian, same error.)
PHP 7.0.11
MariaDB 10.1.17
Reverse Proxyied nginx 1.10.1 - apache 2.4.23

I have tried things like 777 on the whole installation, but no changes with that. Is magento trying to access some information outside its Map? Im thinking like tmp folder or similiar that could disallow that user access. AH01797 is a permission error..

**Comment by oshmyheliuk** [comment]
Hi All,

The problem with infinite spinning on components page can appear when you have multiple repositories in composer.json file.
Please open your composer.json file and move to "repositories" section, and left only one repository, 
like shown below.

```
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
```

As for me, it's work pretty fast, but it's a temporary fix and may cause some other problem.
This issue is known and will be fixed in future releases.

**Comment by Sam2k** [comment]
@oshmyheliuk 

Thanks to trying to help us, but for me it's not working at all.
Checking my "composer.json" and already have only one entry in "repositories" (exactly the same in your example).
Thank you Oleksandr.

Regards

**Comment by nau88xj** [comment]
@oshmyheliuk Your solution of removing extra repositories fixed my problem.  Thank you!

**Comment by oshmyheliuk** [comment]
@Sam2k 

If this solution doesn't help probably you have some error on ajax request.
Please try to enable developer mode in .htaccess and look at the xhr requests in the network section.
If there are some errors, please paste them here.
![screenshot_3](https://cloud.githubusercontent.com/assets/18550571/20339970/d6fdc396-abe7-11e6-999e-799a04cb6b4d.png)
.

**Comment by benj4m** [comment]
@Sam2k I found a solution to my issue at least, I removed the "require-dev" section from composer.json and it worked! It might not work for anyone else, but it's certainly worth a try if you're still having an issue!

**Comment by AgenturSchroeder** [comment]
Hi There,

I can't remove this section becouse i need it for some code.
I have the same problem and the following error code:

`Error: data.lastSyncData is undefined
@http://subdomain.domain.de/setup/pub/magento/setup/component-grid.js:15:20
r/h.success/<@http://subdomain.domain.de/setup/pub/angular/angular.min.js:71:82
ze/e/l.promise.then/D@http://subdomain.domain.de/setup/pub/angular/angular.min.js:98:513
ze/e/l.promise.then/D@http://subdomain.domain.de/setup/pub/angular/angular.min.js:98:513
ze/g/<.then/<@http://subdomain.domain.de/setup/pub/angular/angular.min.js:100:173
Yd/this.$get</h.prototype.$eval@http://subdomain.domain.de/setup/pub/angular/angular.min.js:110:369
Yd/this.$get</h.prototype.$digest@http://subdomain.domain.de/setup/pub/angular/angular.min.js:107:460
Yd/this.$get</h.prototype.$apply@http://subdomain.domain.de/setup/pub/angular/angular.min.js:111:171
f@http://subdomain.domain.de/setup/pub/angular/angular.min.js:71:335
x@http://subdomain.domain.de/setup/pub/angular/angular.min.js:76:181
ve/</v.onreadystatechange@http://subdomain.domain.de/setup/pub/angular/angular.min.js:77:224`

**Comment by Jimgitsit** [comment]
Modifying "repositories" in composer.json fixed this issue for me (worked around it anyway).

Before:
```
"repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool"
        }
}
```

After:
```
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
]
```

**Comment by Passelewe** [comment]
As  @oshmyheliuk said. My problem is an error with the ajax request. Can somebody help? I'm using
- Magento 2.0.10
- Ubuntu 16.10
- Apache 2.4.18
- PHP 7.0.8

![2016-11-28 16_15_22-root serverg01_ _var_www_sample](https://cloud.githubusercontent.com/assets/10777938/20673594/fbef3804-b585-11e6-969c-a51740d74765.png)

**Comment by neko-in-space** [comment]
Removing extra repositories in composer.json worked for me as well! @oshmyheliuk Thanks a lot! Are you able to explain why this has worked and why default magento composer.json has got two repositories?

**Comment by jufpv** [comment]
Thank you so much !
composer.json worked for me too

**Comment by iamkerly** [comment]
composer.json worked for me

    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],

**Comment by fwolfst** [comment]
Wow, composer.json editing brought me one step further. Am now at getting a `500` for `/setup/index.php/componentGrid/components`. Tedious.

**Comment by fwolfst** [comment]
@Passelewe Klick on "Antwort" on the 500 to see the response that MIGHT contain helpul information.

**Comment by getsolvedUG** [comment]
Same problem here, but I am using CE 2.1.7. Nothing worked so far.

**Comment by delidiscount** [comment]
Still no solution, how come? Is so weird that a functionality is not working. I tried almost everything but still just a spinning wheel on my component manager.

**Comment by onlineous** [comment]
I know this might be considered a bump of an old(er) topic, but I solved this problem in a way I haven't read before.

When viewing the server logs I noticed the time was one hour off. I'm in the GMT + 1 region. It seems like Magenta does something weird with servertime (something like adding GMT + 1 (servertime) and GMT + 1 (magento time)). Using the GMT timezone in Magento immediately fixed the problem.

**Comment by Sam2k** [comment]
After a long time, here is my final answer.

I tried all the solutions with the composer.json file but none worked, still had infinite spinning Wheel.
Finally I updated Magento to 2.1.13 and now the setup wizard work fine !
My server use Apache 2.4.10 / PHP 7.0.30
Thanks for your help.

Regards

**Comment by magento-engcom-team** [comment]
Closing, based on multiple reports that setup wizard works fine.

**Comment by deloenzien** [comment]
version magento 2.2.6. I just run into the same problem?
25 november 2018 wheel keeps spinning... please wait ... 

I read al the above but did not try anything. Just wondering what is the solution to fix? sinds this is still a problem from may 2016 till today.

how to fix?

**Comment by deloenzien** [comment]
Just removed the sync keys from marketplace and created new keys with differente name.
Added those keys in my magento backend. While wheel was spinning I did refresh in browser(F5) and then I could add new keys. After this it works again for me.
