### ISSUE TITLE
order product options doesn't display

### ISSUE THREAD

**Issue by mengento** [magento/magento2#4759]
My php version is 7.0.6
magento version is 2.0.7
I Submit Invoice after,
order product options doesn't display
![20160529181622](https://cloud.githubusercontent.com/assets/10205547/15632616/3265c844-25cb-11e6-8898-59e08e53a7ba.png)

![20160529181700](https://cloud.githubusercontent.com/assets/10205547/15632661/11ff4674-25cc-11e6-9fb4-c56579640fc1.png)

![20160529181851](https://cloud.githubusercontent.com/assets/10205547/15632618/379fe308-25cb-11e6-8353-b36dbce6125d.png)

**Comment by NadiyaS** [comment]
Hi @mengento ,
thank you for reporting this issue. The same issue was reported in #4618.
It really exists on 2.0.7 version. But develop branch does not have this bug.
You can upgrade your code from develop branch or wait until next release.
This issue is closed as duplicate.
