### ISSUE TITLE
Install magento 2.1 with sampledata, progress 62% and never done

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#4760]
## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Add sampledata  2.1

Ubuntu, nginx, php 7

Install log

Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema... 

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing schema... 

Module 'Magento_Theme':
Installing schema... 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing schema... 

Module 'Magento_Customer':
Installing schema... Upgrading schema... 

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':
Installing schema... 

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Installing schema... 

Module 'Magento_Cms':
Installing schema... Upgrading schema... 

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':
Installing schema... 

Module 'Magento_Rule':

Module 'Magento_Catalog':
Installing schema... Upgrading schema... 

Module 'Magento_Search':
Installing schema... Upgrading schema... 

Module 'Magento_Bundle':
Installing schema... Upgrading schema... 

Module 'Magento_Quote':
Installing schema... Upgrading schema... 

Module 'Magento_CatalogUrlRewrite':
Installing schema... 

Module 'Magento_Widget':
Installing schema... 

Module 'Magento_SalesSequence':
Installing schema... 

Module 'Magento_CheckoutAgreements':
Installing schema... Upgrading schema... 

Module 'Magento_Payment':

Module 'Magento_Downloadable':
Installing schema... 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CatalogInventory':
Installing schema... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':
Installing schema... 

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':
Installing schema... 

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':
Installing schema... 

Module 'Magento_Sales':
Installing schema... 

Module 'Magento_ImportExport':
Installing schema... Upgrading schema... 

Module 'Magento_User':
Installing schema... Upgrading schema... 

Module 'Magento_Tax':
Installing schema... 

Module 'Magento_Email':
Installing schema... 

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':
Installing schema... 

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':
Installing schema... 

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Weee':
Installing schema... 

Module 'Magento_DownloadableImportExport':

Module 'Magento_CatalogRule':
Installing schema... Upgrading schema... 

Module 'Magento_Security':
Installing schema... Upgrading schema... 

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogSampleData':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Installing schema... 

Module 'Magento_Newsletter':
Installing schema... 

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing schema... Upgrading schema... 

Module 'Magento_OfflineShipping':
Installing schema... 

Module 'Magento_PageCache':

Module 'Magento_Captcha':
Installing schema... 

Module 'Magento_Vault':
Installing schema... 

Module 'Magento_Persistent':
Installing schema... 

Module 'Magento_ProductAlert':
Installing schema... 

Module 'Magento_BundleSampleData':

Module 'Magento_ProductVideo':
Installing schema... 

Module 'Magento_DownloadableSampleData':

Module 'Magento_Reports':
Installing schema... 

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing schema... 

Module 'Magento_ConfigurableSampleData':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_Paypal':
Installing schema... 

Module 'Magento_ThemeSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Integration':
Installing schema... Upgrading schema... 

Module 'Magento_SendFriend':
Installing schema... 

Module 'Magento_Shipping':

Module 'Magento_Sitemap':
Installing schema... 

Module 'Magento_NewRelicReporting':
Installing schema... 

Module 'Magento_Swagger':

Module 'Magento_Swatches':
Installing schema... 

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':
Installing schema... 

Module 'Magento_GoogleOptimizer':
Installing schema... 

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':
Installing schema... 

Module 'Magento_GroupedProductSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':
Installing schema... 

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_ReviewSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':
Installing schema... 

Module 'Magento_WishlistSampleData':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':

Module 'Magento_Rule':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Search':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_Quote':
Running schema recurring...

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Sales':
Running schema recurring...

Module 'Magento_ImportExport':

Module 'Magento_User':

Module 'Magento_Tax':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_DownloadableImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogSampleData':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_BundleSampleData':

Module 'Magento_ProductVideo':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_Paypal':

Module 'Magento_ThemeSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_NewRelicReporting':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_ReviewSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_WishlistSampleData':

Installing user configuration...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[collections] => 1
[reflection] => 1
[db_ddl] => 1
[eav] => 1
[customer_notification] => 1
[full_page] => 1
[config_integration] => 1
[config_integration_api] => 1
[translate] => 1
[config_webservice] => 1
)

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing data... 

Module 'Magento_Theme':
Installing data... Upgrading data... 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing data... 

Module 'Magento_Customer':
Installing data... Upgrading data... 

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Installing data... 

Module 'Magento_Cms':
Installing data... Upgrading data... 

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':
Installing data... 

Module 'Magento_Rule':

Module 'Magento_Catalog':
Installing data... Upgrading data... 

Module 'Magento_Search':

Module 'Magento_Bundle':
Installing data... Upgrading data... 

Module 'Magento_Quote':
Installing data... 

Module 'Magento_CatalogUrlRewrite':
Installing data... 

Module 'Magento_Widget':
Installing data... 

Module 'Magento_SalesSequence':
Installing data... 

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':
Installing data... 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CatalogInventory':
Installing data... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':
Installing data... 

Module 'Magento_SampleData':
Installing data... 

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':
Installing data... 

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':
Installing data... 

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':
Installing data... 

Module 'Magento_Authorization':
Installing data... 

Module 'Magento_Sales':
Installing data... Upgrading data... 

Module 'Magento_ImportExport':

Module 'Magento_User':
Upgrading data... 

Module 'Magento_Tax':
Installing data... Upgrading data... 

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':
Installing data... 

Module 'Magento_GiftMessage':
Installing data... Upgrading data... 

Module 'Magento_Checkout':
Installing data... 

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':
Installing data... 

Module 'Magento_Weee':
Installing data... 

Module 'Magento_DownloadableImportExport':

Module 'Magento_CatalogRule':
Installing data... 

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogSampleData':
Installing data...

**Comment by ghost** [comment]
My understanding is that Release Candidate 1 sample data wasn't published. In any case, we [advise against](http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1EE.html) trying it. Sorry for your trouble.

**Comment by mazhalai** [comment]
@minhluan259 are you using a git based installation?

**Comment by minhluan259** [comment]
I have download zip from git and use installation wizard.

**Comment by andimov** [comment]
@minhluan259 
Thank you for reporting!
Looks like you have known issue with resource limits.
Please, check this:
 [Setup Wizard installation stops at about 70%](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_70pct.html) and let me know if your problem been solved.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
