### ISSUE TITLE
Plugin does not work for getJsonConfig() of Configurable-Block

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#4761]
## Steps to reproduce
1. Use the following plugin:

```
<type name="Magento\ConfigurableProduct\Block\Product\View\Type\Configurable">
    <plugin name="my_plugin" type="Vendor\MyModule\Model\Plugin\ConfigurablePrice" />
</type>
```

```
<?php

namespace Vendor\MyModule\Model\Plugin;

class ConfigurablePrice
{
    public function afterGetJsonConfig(\Magento\ConfigurableProduct\Block\Product\View\Type\Configurable $subject, $json)
    {
        die('test');
    }
}
```
1. Load configurable product on the frontend
## Expected result
1. The plugin gets executed
## Actual result
1. The plugin does **not** get executed
2. The Configurable block gets called from a template `Magento_Swatches::product/view/renderer.phtml` and it seems that there is no interceptor for the block which could call the plugin
3. According to the limitations of the [documentation](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html) this should definitely work as it is a public function

**Comment by kandy** [comment]
At which area the plugin is registered?

**Comment by sydekumf** [comment]
Global area

**Comment by kandy** [comment]
Can you review that in your installation do not registered other plugins for this class?
Also can you check that your module is enabled  and cache and generated files was cleaned?
And please disable page cache and block cache.
