### ISSUE TITLE
Download link in order confirmation email

### ISSUE THREAD

**Issue by ankitce** [magento/magento2#4762]
## **Steps to reproduce**
1. Create order of downloadable product in admin panel with "Send email.." option ticked.
2. Check the order confirmation email and click/tap on the 'Download' link.
## **Expected result**

It should redirect to download link on frontend.
## **Actual result**

It redirects to 'Admin panel' and also reveals the admin URL key. 

So, it's _functional_ as well as _security_ issue.

Please do the needful as soon as possible. I'll test it from frontend and share the result if it's other than expected.

**Comment by antboiko** [comment]
Hi @ankitce , thanks for reporting this issue. We've created Internal ticket MAGETWO-53678 to investigate.

Thanks,
Anton.

**Comment by vzabaznov** [comment]
Hi @ankitce , thanks for reporting, issue was fixed and will be delivered in next release under 8b5a1d6 commit, if you think that bug is reproducible, please open this, or create new one.

**Comment by ankitce** [comment]
Thanks @antboiko @okorshenko @vzabaznov
