### ISSUE TITLE
Categories not showing on home page but showing on all other pages

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#4763]
1. Installed Magento successfully with no issues,  logged into admin after and checked frontend without any errors
2. Created sample category
3. Refreshed cache
4. Navigated to home page and no categories, then navigated to sign in and category displayed, same with create an account but when navigating to home page then the categories do not show.

No errors in log in relation to this.

Please assist.

**Comment by ghost** [comment]
Do you have "full page cache enabled"? What build?

**Comment by GlobalOutsourcing** [comment]
No, I have changed it to Varnish. I got Magento 2.0.7 from composer and installed through setup wizard without any issues.

Web rewrites enabled, https by default and added a product also and no issues but the categories are not showing on homepage only on fresh installation. Reindex also. Another installation environment I indtalled of Magento 2.0.6, 2 days ago is fine and showing categories on homepage after they are cteated with fresh ibstalltion magento but this installtion of 2.0.7 is not.

No idea why this is.

**Comment by ghost** [comment]
The biggest problem I've had in the past was "folder-file" permissions setting on the server. After 3 different host, I found one that understands Magento 2. No issues on the frontend at all.

**Comment by GlobalOutsourcing** [comment]
Permissions are fine as I have followed magento official documentation and adoing the owmer to the specities grouP and rinning installtation through it. Tested checkout, uploads etc. Am on a dedicated server so powerful enough to handle the application. Hosting is not the issue for me nor am looking for another provider, rather want to find out exactly what the issue with this installation is for not showing categories solely on the home page as it makes no sense.

Someone please advise on potential work around. 

Thanking you in advance.

**Comment by commcad** [comment]
Jeff is correct, perms. Had to deal with this more than once now and found out that the virtual host's root folder needed permission more than anywhere else. Just brute force it:
- note the sudo everywhere

$ cd /var/www/  (i.e. in front of your vhost root)
$ sudo chown -R youruser:www-data .
$ sudo chgrp -R www-data .
$ sudo chmod -R ug+rw .

$ cd in your var/www/magento2folder
$ sudo find . -type d -exec chmod 755 {} \; && sudo find . -type f -exec chmod 644 {} \;
$ sudo find var pub/media pub/static -type d -exec chmod g+ws {} \;
$ sudo find var pub/media pub/static -type f -exec chmod g+w {} \;
$ sudo find -L vendor/bin -type f -exec chmod u+x {} \;
$ sudo chmod g+w app/etc
$ sudo chmod u+x bin/magento

Redeploying and all that stuff may also help. Run those same perms above when done :/
e.g
php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento indexer:reindex && php bin/magento cache:clean && php bin/magento cache:flush

**Comment by GlobalOutsourcing** [comment]
Hi commcad,

Thank you very much for the detailed instructions.

I have followed it to the latter but unfortunately no joy with the categories appearing in the homepage.

I have checked the system.log and noticed this at the end after following the above:

`[2016-05-30 08:08:13] main.CRITICAL: Invalid template file: 'Magento_Catalog::js/components.phtml' in module: '' block's name: 'catalog_category_page_head_components' [] []
[2016-05-30 08:08:16] main.CRITICAL: Invalid template file: 'Magento_Catalog::js/components.phtml' in module: '' block's name: 'catalog_category_page_head_components' [] []
[2016-05-30 08:08:24] main.CRITICAL: Invalid template file: 'Magento_Catalog::js/components.phtml' in module: '' block's name: 'catalog_category_page_head_components' [] []
[2016-05-30 08:09:08] main.CRITICAL: Invalid template file: 'Magento_Catalog::js/components.phtml' in module: '' block's name: 'catalog_category_page_head_components' [] []`

I have seen this link with the reported issue [https://github.com/magento/magento2/issues/2591](url), I have followed the resolve at [https://github.com/magento/magento2/commit/2d0775e215a98c14010fae67e85880a664dbe594](url) but no idea if the no show of categories only on homepage but visible everywhere else is related to the above solution but have created the directories anyway and placed the code in the said file.

Any other work around for this would be great.

Appreciate your help thus far.

Thanks.

**Comment by GlobalOutsourcing** [comment]
I have reinstalled 2.0.6, upgraded through Magento 2 system to 2.0.7 and no issue now so no idea what went wrong but all is well now.

Thanks for all those that attempted to help.

**Comment by franckgarnier21** [comment]
I reproduced your problem in Magento 2-2 EE. Try to clear the browser cache (with local storage), reindex, flush magento cache. It should works then.
