### ISSUE TITLE
2.1.0-rc1 - Web Setup clean-up scripts (cache type not supported)

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4765]
## Steps to reproduce
1. Installed Magento 2.0.7 and upgraded to 2.1.0rc using Web setup (All good, thank you!)
2. From 2.1.0rc; using the WebSetup wiz > Sync > install extension
3. Proceed to install steps
## Expected result
1. To become millionaire overnight so I can quit working forever ;)
## Actual result
1. Although the extension installed flawlessly and works without a glitch, I did receive an error from the Web Setup Wizard just prior the redirect to Success page (see grab).
2. Fix: simply need to refresh the backend and all is back to normal.

Small glitch I assume. Worth mentioning if relevant to those scripts that mage runs after new installations.

![4magebugreport](https://cloud.githubusercontent.com/assets/19387951/15635627/76e677d4-2616-11e6-85b8-58cd97cbcc7e.jpg)

**Comment by commcad** [comment]
Others: Notice the diff of time zones in the log (screengrab above). Time traveling!

**Comment by commcad** [comment]
Ubuntu 16.04
NGINX 1.10.0
MariaDB 10.0.24
PHP 7.0.4
PhpRedis Extension
REDIS 3.2.0 (for session & page cache)

**Comment by mazhalai** [comment]
@commcad we have created MAGETWO-53730 to investigate and fix. Also, are you on production mode?

**Comment by commcad** [comment]
Mazhalai, default mode.

all the best 2uguys there

**Comment by dsikkema-magento** [comment]
Hello @commcad. I tried a few times to reproduce this without any luck, so I have two questions. Can you share what extension you were trying to install? And how many times did you see this error? As you pointed out, there's a weird timestamp inconsistency in the log, and one hypothesis (although it's a stretch) is that a previous run of the updater left behind some artifacts that are contaminating subsequent runs of the updater. If you run `rm -rf .type.json .update_* .setup_*` in `var` do you get the problem still?

**Comment by commcad** [comment]
@dsikkema 

**/var/www/mydomain.com/var$ rm -rf .type.json .update_\* .setup_***

Ran above I am not getting the missing cache type error anymore and the setup goes right up to where it should (success!). However timezones are still fuzzy a tad. Goes up and down as it scroll the console/log. 

One could say it it supposed to be as such ;) 

Extension name listed in the log below, as requested;

[2016-06-06 05:38:36 CST] Composer update completed successfully
[2016-06-06 05:38:36 CST] Job "update {"components":[{"name":"zero1/theme-fashionista-theme","version":"1.0.0"}]}" has successfully completed
[2016-06-05 21:39:04 UTC] Job "setup:cache:enable ["config layout block_html coll.................//
