### ISSUE TITLE
Get img or css file absolute path

### ISSUE THREAD

**Issue by 2007lf** [magento/magento2#4768]
I have a question, help someone can help me.
This is my website path, I create new theme, now I want get the file a.jpg absolute path, how should I write code?
/var/www/magento2/app/design/frontend/Test/Ttheme/web/images/a.jpg

**Comment by 2007lf** [comment]
When I use magento1, I write code like this, 

```
<?php if(file_exists(Mage::getDesign()->getSkinBaseDir().DS.'a.jpg')): ?>
...do something
<?php endif ?>
```

**Comment by zanilee** [comment]
Hi, @2007lf!

To get the absolute path of a theme image in template use

``` php
<?php if ($block->getUrl('', ['_direct' => 'core/index/notFound']) != $block->getViewFileUrl('/images/cat.gif')): ?>
        ...do something
<?php endif; ?>
```

Please let us known if it works for you.

**Comment by MomotenkoNatalia** [comment]
@2007lf  let us know if this works for you

**Comment by 2007lf** [comment]
Hi, @zanilee  I can't understand what you mean, its not my question answer. But thank you post. :)

**Comment by zanilee** [comment]
Hi, @2007lf!

Maybe this can help: 
including image:
`<img src=<?php echo $block->getViewFileUrl('/images/a.jpg')?>/>`

**Comment by 2007lf** [comment]
@zanilee Thank you, but its not my mean, now I has used this code.

``` php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$filesystem = $objectManager->get('Magento\Framework\Filesystem');
$reader = $filesystem->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::APP);
$imgurl = $this->getViewFileUrl('images/a.jpg');

if(file_exists($reader->getAbsolutePath('design/frontend/Test/Ttheme/web/images/a.jpg'))){
    echo '<img src="'.$imgurl.'" width="20" height="20"/>';
}
```

Looks very stupid, but its work, Its my mean.

**Comment by zanilee** [comment]
@2007lf, glad you found a solution that fits you. 
Do you have any other questions?

**Comment by 2007lf** [comment]
@zanilee But its looks not right method, I think have good method, so long time past, just you comment. Magento2 is difficult to understand than magento1. :(
Thanks.
