### ISSUE TITLE
To call a phtml file in cms page

### ISSUE THREAD

**Issue by DRAJI** [magento/magento2#4769]
I have googled "How to add a phtml file to cms". I got an answer like below 

**{{block class="Magento\Framework\View\Element\Template" name="test_file" template="Magento_Theme::html/test.phtml"}}**

But it doesn't work for me. It returns an empty page & generates 500 internal server error. 

How should i call phtml file in cms page? I'm using Magento 2.0.5 version

**Comment by pboisvert** [comment]
The github issue tracker is for reporting bugs or technical issues only. Please ask "how do I" of "why" type of questions on [Magento SE](http://magento.stackexchange.com/) or the official [community forum](https://community.magento.com/).
