### ISSUE TITLE
/lib/web/css/docs/dropdowns.html examples are broken

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#4770]
Visit http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/dropdowns.html
(as far as i know this should be the "official" frontend demo) and try to see a dropdown, i couldn't.

**Comment by slackerzz** [comment]
i've found that also [tabs](http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/sections.html) and [popup](http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/popups.html) examples are broken

**Comment by zanilee** [comment]
Hi @slackerzz!

This is known issue and it is present in library documentation only.
The documentation issue will be fixed in MAGETWO-34178

**Comment by magento-engcom-team** [comment]
@slackerzz, thank you for your report.
We've created internal ticket(s) MAGETWO-82332 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@slackerzz, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
