### ISSUE TITLE
Checkout edit address functionality missing

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#4771]
Hello,

I am login as customer and i have 5 address in my account.

I am on checkout page now, i want to edit shipping address on checkout page but there is no functionality for same.

**Comment by sunilit42** [comment]
Below file contain some code for edit address:

Magento\Customer\view\frontend\web\js\model\customer\address.js

 getCacheKey: function() {
                return this.getKey();
            },
            isEditable: function() {
                return false;
            },
            canUseForBilling: function() {
                return true;
            }

in magento 2 given fixed value for edit: return false.

**Comment by asemenenko** [comment]
Hi @sunilit42 we do not have a functionality that allows to edit an existing address during checkout. You can add only a new one during the checkout and modify it, but not the existing one. I added it to the feature requests.

**Comment by sunilit42** [comment]
it is very good feature it must need to add that.

**Comment by vpodorozh** [comment]
Hi @asemenenko , when do you expect to develop this feature?

**Comment by andyworkbase** [comment]
Any updates on this feature?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Checkout-edit-address-functionality-missing/idi-p/44726).

**Comment by rakeshvora** [comment]
Hello,

I have one question. Why magento does not allow to edit an existing address during checkout?

Thanks
Rakesh Vora
