### ISSUE TITLE
Save Address on checkout not working

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#4772]
Hello,

I am login as customer and i want to add new address on checkout page, Magento 2 provide that, but in that popup showing save address in address book checkbox but that is not working.

**Comment by ishakhsuvarov** [comment]
@sunilit42 We have tried and could not reproduce the issue as described with the clean installations from `develop` and `2.0` branches. Please provide more detailed preconditions, steps to reproduce and Magento version you are using.
Thank you.

**Comment by sunilit42** [comment]
Already explain here:

https://mage2.pro/t/topic/1673
