### ISSUE TITLE
Fixed Product Taxes (FPT) are not used from simple products

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#4774]
## Steps to reproduce
1. Create a configurable product
2. Give it's child-products different FPT values
3. Add the product to the cart
## Expected result
1. That the product in the cart has the FPT applied of the child product
## Actual result
1. The FPT of the parent product (configurable) is applied instead.

**Comment by choukalos** [comment]
Hi @kanduvisla,

Our FPT/WEEE implementation is pretty simple.  We only look at the product's attribute for what the WEEE fee is.  That means for meta-products, such as configurable, bundled, grouped, we only see the meta-product's fee and not a roll up of the children's fee.

Internally I'm tracking this as a feature request (MAGETWO-53828).

**Comment by kanduvisla** [comment]
Is this feature going to be implemented in 2.1?

**Comment by choukalos** [comment]
No, it's way out there - buried in icebox; unless there's a massive deluge of interest/need for this it's likely to stay there.  

On the other hand if some one wants to give us a PR we'd love to take it into mainline.

**Comment by kanduvisla** [comment]
I try to figure it out myself. Any pointers on where to look to manipulate FPT? Any events or plugin suggestions?

**Comment by kanduvisla** [comment]
I think I figured out a way to do this with only one plugin and one rewrite, but I'm not sure if it's solid enough. Anyway, I'll leave the link on how I did this here for future developers who might encounter the same situtation (untill Magento decides to take this feature request out of the icebox): https://gielberkers.com/properly-calculate-fptweee-configurable-products-magento-2/

**Comment by jaykobi** [comment]
This really needs to get a bug label. I can choose a tax rate for child products. But it is not used.

@kanduvisla I will try using your code and will post here if it works for me.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Fixed-Product-Taxes-FPT-are-not-used-from-simple-products/idi-p/45981).
