### ISSUE TITLE
Failed login alert message are not shown when the error occured

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4775]
This is happening to me always. Currently, I have 2.0.6 version.

In frontend, when I enter bad login information, no error mesage appears in the page. It just does not login.

when I finally do a successful login and cause a message to appear, for example, by adding a product to shopping cart, the login failed error appears, together with the new alert.

If, for example, do 5 failed login attempts, 5 error alerts are shown.

This is an screenshot of the problem:

![image](https://cloud.githubusercontent.com/assets/9195659/15651080/9c4f0472-2653-11e6-8ae2-4dad84af2ddd.png)

**Comment by sevos1984** [comment]
This was already fixed. See commits 541ec806cae729df118b7844f5d105cbf1a6cec6, 55a6e51296afd2c52cfe7f813a4871ae408f1afc, b4d373919489ccb48af10c5ac287ef39e3af384e, eec31f653e3783d0ba86602c8396fd6e2d159546, af2a8325930ae22e2b7ae3f6513c0068217eacd1, d97ebe56200b73e71d97ca527c99108817586a54, 3120b1e89f48ff630e796c6885aecc3e48c070c8 and 66e6ad66c028e99019c110631df4c9015af4a2ca. Thanks
