### ISSUE TITLE
Changing the default sorting on category overview

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4776]
We want to change the order of the products on the category page. Right now its not really clear how its sorted. We want to have the most new and latest products on top left (Pos 0 for example), the second-latest product on Pos 1, and so on. 

Its not very clear how Magento2 sorts the products by default, but its not ascending, and we want it ASC. How can we achieve this? 

Or is it anywhere documented?

**Comment by hostep** [comment]
Possible duplicate: https://github.com/magento/magento2/issues/1266

**Comment by grasdaggel** [comment]
Seems like an identical problem here. I also think that #1266 is a duplicate. However, its been a long time that someone touched #1266!

**Comment by katmoon** [comment]
Hi,

Smart sorting in catalog is a Magento Enterprise feature.
So I'm closing this issue since nothing will be done regarding this issue in CE. Feel free to reopen the issue if you still have any questions.

Thanks, Kateryna.
