### ISSUE TITLE
Sorting configurable products by price doesn't work when simple product has special_price

### ISSUE THREAD

**Issue by Fdec** [magento/magento2#4778]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Edit a simple product (which is a variation of a configurable product)
3. Add special_price
4. Go in catalog product list
## Expected result
1. sorting by price based on min_price of a simple product 
## Actual result

![capture du 2016-05-30 17 08 44](https://cloud.githubusercontent.com/assets/5850723/15652972/3440b498-268a-11e6-9f1c-b14b6fce9a8b.png)

**Comment by antboiko** [comment]
Hello @Fdec , thanks for reporting this issue. We've created internal ticket MAGETWO-53675.

Best,
Anton.

**Comment by NisaKH** [comment]
any update on this issue?

**Comment by sergiojovanig** [comment]
Hi, I can reproduce this bug in Magento 2.1.2. Any temporal workaround? I think this is critical...

**Comment by vipinroy** [comment]
Can we use the below commits to solve this issue?
Please help..

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
It also was fixed for ver. 2.1 and will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment]
@Fdec, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by maderlock** [comment]
Will this get a fix for 2.1?

**Comment by DePalmo** [comment]
Still reproducible in v2.2.3 ...

**Comment by ktsixit** [comment]
![Untitled-1](https://user-images.githubusercontent.com/2758872/61609938-4b334580-ac60-11e9-93d3-a306777af1e4.jpg)

I have this issue in 2.3.This should have been fixed, right? What should I check?

**Comment by antoniocarboni** [comment]
Still reproducible in 2.4.6.
