### ISSUE TITLE
Simple products not working properly when child product has custom options set in database

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#4779]
I have this strange situation in a clients' installation: I have a configurable product (ID=111) and it has 2 simples attached (ID 112 & 113). Now when I save it in the backend, the following happens:
- In my 'configurations' section there is only one product. This is wrong.
- In my databases' `catalog_product_super_link` there are 2 relations (as expected).
- In my databases' `catalog_product_relation` there are also 2 relations (as expected).
- On the frontend, I can only choose 1 option from the dropdown.

When I try to re-save the relation in the backend (because it only shows one, my client tries to manually add a product and re-selects the product), I get the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '112-111' for key 'CATALOG_PRODUCT_SUPER_LINK_PRODUCT_ID_PARENT_ID', query was: INSERT INTO `catalog_product_super_link` (`product_id`,`parent_id`) VALUES (?, ?)
```

This of course makes sense, because the relation already exists in the database. But for some reason it's not working in the backend or the frontend.

Anyone got a clue where it might be going wrong?

**Comment by kanduvisla** [comment]
I found it!

For reasons unknown, in `catalog_product_entity` the values `has_options` and `required_options` were set to `1`, even though that when I edit the product there were no options visible. So a couple of questions arise here:
- How did `has_options` and `required_options` got set to `1`? Did the client add options? If so, why weren't they set to `0` when the custom options were deleted?
- Why did the product show up in the grid where I can select the child-products (when I want to add them manually). This list should exclude products that have custom options.
- I also used custom code to get the used product collection (`$product->getTypeInstance()->getUsedProductCollection($product);`). This code did return all linked child products, also the ones that were 'broken'.

**Comment by kanduvisla** [comment]
Just tested saving a product with custom options and then remove the options and re-save it. The database was cleaned up nicely. So it's strange where in my project it went wrong. Perhaps sometimes somewhere in a fatal error or something ...

Needless to say, I still think that this issue requires some attention. Especially in the product grid when adding configurations manually.

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
