### ISSUE TITLE
Web Setup Wizard needs better error messaging

### ISSUE THREAD

**Issue by fooman** [magento/magento2#4781]
## Steps to reproduce
1. Install Magento 2.0.x from zip
2. Go to System > Web Setup Wizard
3. Go to System Upgrade (without ever signing in or creating an auth.json file for repo.magento.com)
4. Go to Component Manager, sign in with repo.magento.com credentials and hit Sync (configure php to have less than the recommended memory size for composer to work)
## Expected result
1. A meaningful error message is displayed
## Actual result
1. Error message "Sorry, we can't take that action right now." (step 3) / Endless spinning wheel animations (javascript error in relation to setup/pub/magento/setup/component-grid.js data.lastSyncData.lastSyncDate) (step 4)

**Comment by mazhalai** [comment]
@fooman this has been fixed in 2.1.0-rc1? Have you tried it with that version?

**Comment by fooman** [comment]
Installation from zip is not available for 2.1.0-rc1 yet, unless I missed something.

But for example here https://github.com/magento/magento2/blob/2.1.0-rc1/setup/pub/magento/setup/component-grid.js#L15 if index.php/componentGrid/components spits out something like `PHP: Fatal Error: Allowed Memory Size of 134217728 Bytes Exhausted` data.lastSyncData won't exist and this line `if(typeof data.lastSyncData.lastSyncDate === "undefined") {` will throw a JS error.

**Comment by mazhalai** [comment]
@fooman if you have access to command line,  you cant try `composer create-project magento/project-community-edition=2.1.0-rc1 --repository-url=https://repo.magento.com`

**Comment by fooman** [comment]
@mazhalai using `composer create-project` already needs to communicate with `repo.magento.com` so will not be able to replicate the issue in step 3.

**Comment by mazhalai** [comment]
@fooman then you will just have to wait for 2.1 GA.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
