### ISSUE TITLE
Magento 2 - Checkout shipping form:  region translations not shown

### ISSUE THREAD

**Issue by alentsch** [magento/magento2#4782]
Magento 2.0.6 
Shipping form in the checkout

After creating regions for Japan in the table `directory_country_region` and the translations in table `directory_country_region_name` the **translated region names are NOT shown** in the checkout **shipping form** (only the untranslated names from table `directory_country_region`). This is a "show stopper" for our current effort to use Magento 2 for our Japanese store. All other translation obstacles are pretty much cleared. 

I would highly appreciate, if the issue could be solved. 
Thanks a lot in advance!

PS: For comparison, the region translations are **shown correctly** in other forms such as e.g. the address form in the customer module.

**Comment by alentsch** [comment]
Just upgraded to Magento 2.0.7 and the problem is still there.

**Comment by okobchenko** [comment]
Team will fix reported issue in scope of internal ticket MAGETWO-53811

**Comment by SerhiyShkolyarenko** [comment]
Fix was delivered to develop branch. Closing the issue.

**Comment by irenelagno** [comment]
This issue was delivered in the scope of 7164d34b9561

**Comment by Ctucker9233** [comment]
@irenelagno can this fix be integrated into a 2.1.1 production environment or is there a patch being created for it?

**Comment by irenelagno** [comment]
@Ctucker9233, as I can see this fix was delivered to 2.1 release. If this issue still exists, please let us know.
To 2.0.x release this issue will be delivered in the scope MAGETWO-58871
