### ISSUE TITLE
DOB blank when saved, customer group resets following save.

### ISSUE THREAD

**Issue by FoxtrotOscar2** [magento/magento2#4786]
We have DOB required for customers; we also have customer groups. When a customer is assigned to any special group, this status is reset (to "General") when the customer enters DOB again from the customer front-end.
## Steps to reproduce
1. Install "stable" Magento from magento main 
2. Enable DOB (required) in customer settings
3. In admin create new customer group  (Store -> Other Settings -> Customer group)
4. Customer creates account (by default it's general) and enters DOB
5. Admin assigns customer to any special group created in step 3
6. Customer logs in to -> Account Information; DOB is blank even though it exists in DB and admin backend.
7. Enter DOB again, save account
## Expected result
1. DOB should show when saved
2. Account group should not be reset  to default customer group.
## Actual result
1. DOB shows blank after saving account
2. Customer account reset to "General" or default customer group.

Happens on 2 dev servers (1 with vanilla installation of M 2.0.6 (tarbz ball), 1 is M2.0.7 upgraded from M 2.0.1 through latest through composer) and on main production server (2.0.6). Actual servers are latest/stable LAMP.

**Comment by jonathansayag** [comment]
+1 for blank DOB.

You can see the error in `Magento\Customer\Block\Widget\Dob::getFieldHtml()` :

``` php
$this->dateElement->setData([
    'name' => $this->getHtmlId(),
    'id' => $this->getHtmlId(),
    'class' => $this->getHtmlClass(),
    'value' => $this->getValue(), // <== here is the problem
    'date_format' => $this->getDateFormat(),
    'image' => $this->getViewFileUrl('Magento_Theme::calendar.png'),
]);
```

If we check`$_data`, we can see this :

```
_data = {array} [4]
    type = "Magento\Customer\Block\Widget\Dob"
    time = 594950400
    date = "1988-11-08"
    module_name = "Magento_Customer"
```

There is no `value`defined in `$_data` and `$this->getValue()` is not a function, so it willl always returns `null` if you don't define it in template.

So, logically, we need to return `$this->getDate()` ?

**Comment by FoxtrotOscar2** [comment]
Jonathan - that fixes the Dob display issue! I'm finishing up a solution for the customer group reset on save and will post later this week when I get back.

Edit notes: upon saving value supplied triggers an error ("We can't save the customer.Invalid date") so I'll still have to find what's causing this. At this point it just seems like a formatting issue dd/mm/yyyy vs dd-mm-yyyy with jQuery.

**Comment by sevos1984** [comment]
Dob issue is fixed in latest develop code, issue with customer group is fixed in MAGETWO-42954 and soon will be delivered to develop

**Comment by slavvka** [comment]
@FoxtrotOscar2, the issue has been fixed. Please see 0be746b, 6258496, 3fb5616, c43fc5e and 6fc4dd3.
