### ISSUE TITLE
Authorize net payment not working in magento 2.0.7

### ISSUE THREAD

**Issue by magesh7j** [magento/magento2#4787]
In Magento 2.0.7, Authorize net test mode not working, if we place the order on checkout, Nonstop spinner loading. how to fix this issue. even i have checked , to changing the php version 5.5.32 to 7.0.7 , please help me

**Comment by pboisvert** [comment]
may be duplicate of https://github.com/magento/magento2/issues/4777

**Comment by alena-marchenko** [comment]
Hi @mageshdeveloper ,

Please specify if there are any extensions installed, provide us with debug.log located in var/log of Magento root folder (ensure that Debug option set to Yes), exception.log if available, screenshot of Authorize.net configuration in Magento admin. Please also enable dev tools in your browser and provide us with browser console errors if any and observe requests to Authorize.net for errors in response in browser Network section.

**Comment by magesh7j** [comment]
Hai @alena-marchenko i near install any extensions and its default only, then i traced it till now i could not find out any reason for spinner, then i moved to paypal method. thanks @alena-marchenko. replied for my issue ! thanks alot

**Comment by magesh7j** [comment]
Hai @alena-marchenko 
I am using paypal method, in that there is no issue. till now i didnt find out the reason for not stop spinner loading. Thanks you @alena-marchenko for your reply,
