### ISSUE TITLE
Tags from head in body, and title appearing visibly on page

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#4789]
![headbody](https://cloud.githubusercontent.com/assets/19282144/15667280/6105a49c-270d-11e6-8e2d-4683351b11e7.JPG)

So far from what I have seen this only shows on _some_ product pages.

**Comment by LiamFielding** [comment]
No response?

**Comment by LiamFielding** [comment]
I've merely added a product with attributes.

**Comment by wert2all** [comment]
To allow us research the issue, please, provide description according to the template.

Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
