### ISSUE TITLE
Less compilation error: variable @field-date-icon--color is undefined in Magento/backend theme

### ISSUE THREAD

**Issue by hostep** [magento/magento2#4799]
## Steps to reproduce
1. Install Magento 2.0.7 using composer
2. Install a module which allows you to compile the less files using the native node.js less compiler (I'm working on such a module, but it isn't finished yet, I'm planning on releasing it as an open source module, teaser: it works over twice as fast as the php compiler)
3. Run `bin/magento setup:static-content:deploy`
## Expected result
1. Every less file gets compiled correctly
## Actual result
1. Error message appears:

```
...

=== adminhtml -> Magento/backend -> en_US ===
........................................................................................................................................................................................................................................................................................................................................................................................................................................
Compilation from source:
adminhtml/Magento/backend/en_US/css/styles-old.less
NameError: variable @field-date-icon--color is undefined in var/view_preprocessed/css/adminhtml/Magento/backend/en_US/css/styles-old.less on line 1055, column 36:
1054                 @_icon-font-position: after,
1055                 @_icon-font-color: @field-date-icon--color
1056                 );
>

```
## Extra info

I can see the the variable `@field-date-icon--color` being defined in: `vendor/magento/theme-adminhtml-backend/Magento_Ui/web/css/source/_module-old.less` but in the file `vendor/magento/theme-adminhtml-backend/web/css/styles-old.less` the import of the first file is commented out.

Other question: since those two are named `*-old.less` I assume they will be removed in the future, right? I can see in the Magento 2.1.0-rc1 version they still exists, is this correct?

Thanks!

**Comment by hostep** [comment]
i'm going to close this, this is a non-issue.

I was using the flag `--strict-imports` which only allows `@import` statements to be defined at the top of the less file and not somewhere in the middle or in media queries. This was the cause of the error. I now removed it and everything works perfectly fine.

Sorry for the noise!

**Comment by sshymko** [comment]
@hostep,
How did you configure whether to pass the flag `--strict-imports` to the LESS compiler or not?

**Comment by hostep** [comment]
@sshymko: This was while writing a module to use less.js instead of less.php to improve the performance during deploys. See: https://github.com/baldwin-agency/magento2-module-less-js-compiler/blob/adf7781e4698289150f06cd8ad96707080acddeb/Css/PreProcessor/Adapter/Less/Processor.php#L141

So this had nothing to do with core Magento, was my mistake.
