### ISSUE TITLE
Magento 2.0.7 DownloadableImportExport broken?

### ISSUE THREAD

**Issue by SantoDE** [magento/magento2#4800]
## Preconditions
1. Install Magento 2.0.7 via composer

## Steps to reproduce
1. run magento dev:test:run unit

## Expected result
1. Test result ok

## Actual result
1. Fatal error: Uncaught TypeError: Argument 3 passed to Magento\DownloadableImportExport\Helper\Data::fillExistOptions() must be of the type array, null given, called in /var/www/html/vendor/magento/module-downloadable-import-export/Model/Import/Product/Type/Downloadable.php on line 554 and defined in /var/www/html/vendor/magento/module-downloadable-import-export/Helper/Data.php:51
   Stack trace:
   #0 /var/www/html/vendor/magento/module-downloadable-import-export/Model/Import/Product/Type/Downloadable.php(554): Magento\DownloadableImportExport\Helper\Data->fillExistOptions(Array, Array, NULL)
   #1 /var/www/html/vendor/magento/module-downloadable-import-export/Model/Import/Product/Type/Downloadable.php(696): Magento\DownloadableImportExport\Model\Import\Product\Type\Downloadable->fillDataLink(Array, Array)
   #2 /var/www/html/vendor/magento/module-downloadable-import-export/Model/Import/Product/Type/Downloadable.php(662): Magento\DownloadableImportExport\Model\Import\Product\Type\Downloadable->saveLinkOptions()
   #3 /var/www/html/vendo in /var/www/html/vendor/magento/module-downloadable-import-export/Helper/Data.php on line 51

Anyone knows about that? :) Thanks!

**Comment by mazhalai** [comment]
@SantoDE thank you for reporting we have created MAGETWO-53775 to investigate and fix.

**Comment by magento-engcom-team** [comment]
@SantoDE, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
