### ISSUE TITLE
Can't install Magento-CE-2.0.7-2016-05-24-12-06-54 

### ISSUE THREAD

**Issue by SoonSooon** [magento/magento2#4804]
Hello, 
I'm sorry if this was reported before but I couldn't find the exact same issue on google.
I'm trying to install **Magento-CE-2.0.7-2016-05-24-12-06-54** on my **Ubuntu 14.04** 64bit running **nginx 1.4.6**, **hhvm 3.13.1** and **mysql  15.1** with **MariaDB 10.0.25**. 

**Folders** permissions are **755** and **files** permissions are **644**. With same user and group for nginx and hhvm (www_data).

Error log:
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
[ERROR] exception 'Magento\Setup\Exception' with message 'Can't run this operation: configuration for DB connection is absent.' in /var/www/magento/setup/src/Magento/Setup/Model/Installer.php:861
Stack trace:
#0 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(750): Magento\Setup\Model\Installer->assertDbConfigExists()
#1 (): Magento\Setup\Model\Installer->installSchema()
#2 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(333): call_user_func_array()
#3 /var/www/magento/setup/src/Magento/Setup/Controller/Install.php(103): Magento\Setup\Model\Installer->install()
#4 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#5 (): Zend\Mvc\Controller\AbstractActionController->onDispatch()
#6 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func()
#7 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners()
#8 /var/www/magento/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger()
#9 /var/www/magento/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch()
#10 (): Zend\Mvc\DispatchListener->onDispatch()
#11 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func()
#12 /var/www/magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners()
#13 /var/www/magento/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger()
#14 /var/www/magento/setup/index.php(31): Zend\Mvc\Application->run()
#15 {main}

**Comment by mazhalai** [comment]
@SoonSooon is your db up and running?

**Comment by SoonSooon** [comment]
Nginx, hhvm, and mariadb are all up and running and their error logs are empty.

**Comment by mazhalai** [comment]
HHVM has issues, please see https://github.com/magento/magento2/issues/3583#issuecomment-216257449
Do you know if the issue mentioned has been resolved in your version of HHVM?

**Comment by SoonSooon** [comment]
That issue with hhvm should have been resolved since v3.6.  Anyways, I tried the workaround for that issue but I still have the same issue.

**Comment by SoonSooon** [comment]
Switching to php7 solved the problem. It was an hhvm issue after all.

**Comment by captainkallaje** [comment]
I do not know whether it is a specific hhvm issue, but I got around it by using a env.php, which has the values that I enter in the web, except for the install date...

After installations I have had no problems running magento on hhvm.

I am running latest hhvm version HipHop VM 3.14.2 (rel)

**Comment by unixversal** [comment]
I could get it to work using both mazhalai comment and adding a symlink. Following steps got it to work for me:

1. Add / edit php.ini (/etc/hhvm/php.ini)
`hhvm.mysql.socket = /var/run/mysqld/mysqld.sock`
`pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock`

2. Create a symlink
`ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock`
