### ISSUE TITLE
REST api Bundle Product Issues - Price, Option Content

### ISSUE THREAD

**Issue by Spittal** [magento/magento2#4807]
Hello,

Me and my company are developing an Angular site for a client that communicates with Magento2 over Magento's build in REST api.

One of the requirements for the client is the use of lots of bundled products. However this doesn't seem to be implemented into the REST api very well.

We're having particular problems with price. The REST api does not communicate the lowest or highest price. infact it just computes as 0.

Using the endpoint 
`{{API_URL}}/rest/{{STORE_VIEW_CODE}}/V1/products/{{BUNDLE_PRODUCT_SKU}}`
I get this information

``` javascript
{
  "id": 90,
  "sku": "M10",
  "name": "Expedition Classic",
  "attribute_set_id": 11,
  "price": 0, // Notice price is 0
  "status": 1,
  "visibility": 4, // No matter the state of the product this NEVER changes
  "type_id": "bundle",
  "created_at": "2016-03-28 19:47:04",
  "updated_at": "2016-05-31 21:08:06",
  "weight": 0, // Weight is set, not communicating
  "extension_attributes": {
    "bundle_product_options": [
      {
        "option_id": 1,
        "title": "Hammock",
        "required": true,
        "type": "select",
        "position": 0,
        "sku": "M10",
        "product_links": [
          {
            "id": "1",
            "sku": "P15", // Not getting any information here
            "option_id": 1,
            "qty": 1,
            "position": 0,
            "is_default": true,
            "price": null,
            "price_type": null,
            "can_change_quantity": 0
          }
        ]
      },
      // More options here ...
    ]
  },
  "product_links": [
    //...
  ],
  "options": [],
  "media_gallery_entries": [
    //...
  ],
  "tier_prices": [],
  "custom_attributes": [
    //...
  ]
}
```

The things to note here are:

The Price is always 0, no matter what
The bundle options and their respective product links don't send with any media gallery entries which makes it very hard to update the UI with bundle choices without making a lot of API calls.
No matter what I do. I can't get the price to calculate. What I have been doing is querying every single default option SKU individually to get their price and then add them up at the end. This leads to a really slow experience when I'm trying to display price on a page like the catalog.

Is there any better way to get bundle product information from the API?

**Comment by veloraven** [comment]
@Spittal is this issue still actual?
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue which requires fixing please format this issue according to  the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
