### ISSUE TITLE
Bundled Product - Wishlist console error

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4809]
I've noticed this error in the console when viewing a bundled products. I can still add the product to wishlist so it doesn't appear to be a big problem.

This is on Magento 2.0.5 and it's a site using Luma without any customisation (it's a demo site). It's also using sample data so you should be able to replicate by going by loading the Luma theme and sample data and going to http://URL-HERE.COM/sprite-yoga-companion-kit.html

Apparently it's this line causing the problem:

``` js
elementName = $(element).attr('id').replace(/[^_]+/, 'options').replace(/_(\d+)/g, '[$1]'),
```
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Install the sample data
3. Ensure the site is using the luma theme (not sure if it also occurs on the blank theme)
4. Navigate to a bundled product such as sprite-yoga-companion-kit.html
5. Check the console, you should see `add-to-wishlist.js:94 Uncaught TypeError: Cannot read property 'replace' of undefined` 
## Expected result
1. No errors in the console
## Actual result
1.  `add-to-wishlist.js:94 Uncaught TypeError: Cannot read property 'replace' of undefined` 
## Screenshot

![screen shot 2016-06-01 at 09 22 21](https://cloud.githubusercontent.com/assets/8895777/15702894/6117db1c-27da-11e6-9d76-43c5bdbe0368.png)

**Comment by sevos1984** [comment]
Issue is not reproducible with latest code and latest sample data, try update your code base
