### ISSUE TITLE
Moving blocks can cause a 404 error

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4810]
**The problem**

I noticed that when I move the `bundle.options.container` block to certain destinations bundled products no longer load and I get a 404 page. I suspect it was done on purpose as moving that block could break the customisation functionality, but surely it would be better to return an error instead of a 404. I was confused as to why the product has suddenly vanished.

**My expectation**

I have the below in my exception log which is great but I feel it would be more obvious and more consistent to display the error on the front-end (in dev mode not production) in a similar fashion to the invalid block type error. It seems inconsistent to show some XML related errors on the front-end and some only in the log. Less experienced developers might not think to use or be aware of the exception log.

**Exception Log**

> [2016-06-01 09:03:06] report.CRITICAL: Magento\Framework\Exception\LocalizedException: The 'bundle.options.container' is a parent of 'product.info' recursively, therefore 'bundle.options.container' cannot be set as child to it. in /var/www/vhosts/partyshowroom/production/htdocs/vendor/magento/framework/Data/Structure.php:310

I'm running 2.0.5 in production mode, using the Luma theme and sample data.
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Install the sample data
3. Go to a bundled product page, e.g `sprite-yoga-companion-kit.html` - All is fine
4. Create `app/design/frontend/*VENDOR*/*THEME*/Magento_Bundle/layout/catalog_product_view_type_bundle.xml`
5. Add the XML pasted below point 6 to the XML file.
6. Now load the bundled product again, you should see a 404 page.

**XML**

``` xml
<?xml version="1.0" ?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <move element="bundle.options.container" destination="product.info" />
    </body>
</page>
```
## Expected result
1. I would either expect the error to be shown on the front-end similar to the invalid block type error
## Actual result
1. 404 page

**Comment by odubovyk** [comment]
BenSpace48, thank you for reporting.
We went through your steps and could not reproduce the issue. 
The exception that you've provided appears when set destination="product.info"
Could it be the case that you've provided correct XML file here (destination="product.info.main"), but in your actual code "destination" is set to "product.info"?

**Comment by BenGlassAtlas** [comment]
Interesting, that may be the case. I will double check and let you know.

**Comment by BenGlassAtlas** [comment]
@odubovyk Well that's slightly embarrassing, you are right and I had provided the working XML.

I've updated my steps with the XML that causes the 404 page:

``` xml
<move element="bundle.options.container" destination="product.info" />
```

> [2016-06-03 07:05:37] report.CRITICAL: Magento\Framework\Exception\LocalizedException: The 'bundle.options.container' is a parent of 'product.info' recursively, therefore 'bundle.options.container' cannot be set as child to it. in /var/www/vhosts/partyshowroom/production/htdocs/vendor/magento/framework/Data/Structure.php:310

![screen shot 2016-06-03 at 08 09 00](https://cloud.githubusercontent.com/assets/8895777/15771410/73fcb11a-2962-11e6-88c3-451441477768.png)

**Comment by odubovyk** [comment]
In this case we do not have 404 page, here must be exception page. Please see screenshot attached:
![exceptiion](https://cloud.githubusercontent.com/assets/15216670/15781943/07e034a8-29b1-11e6-995a-203934f54a85.png)
Try to clean all cashes and "var"s if you haven't. Also Check the steps, maybe you've missed something there. And let us know if you have this issue

**Comment by wert2all** [comment]
@BenSpace48 can You reproduce a bug on current develop branch now?

**Comment by BenGlassAtlas** [comment]
Is develop the same as 2.0.7? I have had to set up a new environment and it's installed via composer so I'm not sure how to sync it with develop. But it is 2.0.7.

**Comment by BenGlassAtlas** [comment]
@wert2all ^^

**Comment by wert2all** [comment]
ok, is a bug still actual?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
