### ISSUE TITLE
Overriding Magento backend theme isn't working

### ISSUE THREAD

**Issue by jabrware** [magento/magento2#4811]
After you moved content of app/design/adminhtml/Magento/backend theme to vendor/theme-adminhtml-backend, putting any overriding files in app/design/adminhtml/Magento/backend isn't processed at all
and isn't deployed to pub/static/...

Why?
And how to override backend theme without touching the core files?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
