### ISSUE TITLE
Bundled Products - Quantity does not always update in the summary

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4812]
Using Luma and the sample data, the customisation summary doesn't always update. As these screenshots at the bottom of this comment show.

This is on 2.0.5 in production mode, it's using the Luma theme with sample data. No customisations.

Using this bundled product from the sample data - sprite-yoga-companion-kit.html
## Preconditions
1. Install Magento from `develop` branch.
2. Install the sample data
3. Switch to the Luma theme (not sure if it also happens on the blank theme)

## Steps to reproduce
1. Go to this bundled product - sprite-yoga-companion-kit.html
2. Click on 'Customize and add to cart'
3. Customise the quantity of the bottom 3 products, the summary does not update.

## Expected result
1. Summary updates and reflects the actual price

## Actual result
1. Summary does not update and does not match the actual price when added to cart.

## Screenshots

**Note that all products are set to a quantity of 1, price @ £23.00**
![screen shot 2016-06-01 at 10 35 57](https://cloud.githubusercontent.com/assets/8895777/15704913/a6fbad70-27e4-11e6-832a-79ae09092fc8.png)

**Now I've set some products to a quantity of 10, the summary remains the same price @ £23.00**
![screen shot 2016-06-01 at 10 37 22](https://cloud.githubusercontent.com/assets/8895777/15704947/d6afc88a-27e4-11e6-98da-1da8a5a3d653.png)

**When I add it to the cart, the minicart displays the correct price @ £403.00:**
![screen shot 2016-06-01 at 10 37 05](https://cloud.githubusercontent.com/assets/8895777/15704938/cd967b54-27e4-11e6-999b-c864a3b75689.png)

**Comment by surfer190** [comment]
@BenSpace48 @palamar @rgoncharuk Hey guys, did you take a look at this issue yet?
I see an issue on magento side has not been created.

**Comment by BenGlassAtlas** [comment]
@surfer190 Fortunately I haven't worked on any projects that use this product configuration yet so I'm not aware of any workarounds or fixes sorry. 

I'm surprised to see Magento haven't even acknowledged this yet almost a year later.

**Comment by surfer190** [comment]
I think I have an update on this issue @BenSpace48. Sub products with more than 1 options actually do update. If the sub product only has a single option it does not update.

See the screenshot below:

![screenshot from 2017-05-18 11-21-03](https://cloud.githubusercontent.com/assets/3285222/26195468/36c18e20-3bbc-11e7-9d00-9726fa48404c.png)

**Comment by BenGlassAtlas** [comment]
Interesting, thanks for the info. What version are you running?

**Comment by magento-engcom-team** [comment]
@BenSpace48, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
