### ISSUE TITLE
pdf generation errors

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#4817]
If in Stores / Configuration / Sales/ Pdf Printouts  the Display Order ID in Header is set to No in the generated pdf's the order details and date are overlapping. See image: http://pix.toile-libre.org/?img=1464786723.png

Best regards,

**Comment by NadiyaS** [comment]
Hi @ksz2013 ,
thank you for reporting this issue.
Internal ticket MAGETWO-54002 was created.

**Comment by zanilee** [comment]
Hi, @ksz2013!
The issue was fixed on develop in cccfa21 and 04b6840 commits

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko Any idea what version of Magento this fix will be released in?

**Comment by Ctucker9233** [comment]
@magento-engcom-team It looks like this has been fixed and released in 2.1.11. Can you confirm that?
