### ISSUE TITLE
Wrong products limit on category page (view mode = list)

### ISSUE THREAD

**Issue by KrendiL101** [magento/magento2#4818]
Module "Module-Catalog".
In file Module-Catalog\Helper\Product\ProductList.php const VIEW_MODE_LIST = 'view', not 'list'.
When on frontend i change category view mode to "list", products limit automaticly change to 10, ignoring catalog config.

**Comment by mslabko** [comment]
Hi @KrendiL101 ,

Thank you for reporting! Internal issue created: MAGETWO-54076

**Comment by piotrekkaminski** [comment]
Issue is fixed internally and should be included in 2.1
