### ISSUE TITLE
Error during migration from CE-1.9.2.2 to CE-2.0.5

### ISSUE THREAD

**Issue by nikul** [magento/magento2#4819]
Hello,

Steps Followed:
I have installed magento 2.0.5 and starting migration of my magento 1.9.2.2. Following steps I have made
- Downloaded data-migration-tool using git repository. 
- Made version and crypt key changes in config.xml for 1.9.2.2 in data-migration-tool folder.
- Copied settings.xml with no change
- Executed bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml

Expected Results:
Migration Completed

Actual Results:
Getting error while running command "bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml"
Error is...
[InvalidArgumentException]
There are no commands defined in the "migrate" namespace.

![migration-error](https://cloud.githubusercontent.com/assets/266397/15712586/85720234-2830-11e6-8618-a018e464d42f.PNG)

**Comment by mazhalai** [comment]
@nikul please post migration issues here. https://github.com/magento/data-migration-tool/issues

**Comment by nikul** [comment]
Thanks @mazhalai . Please refer issue here https://github.com/magento/data-migration-tool/issues/91

**Comment by arjunpmhlc** [comment]
Please try with this

composer config repositories.magento composer https://repo.magento.com
composer require magento/data-migration-tool:<version>
Your version (2.1.3). Replace <version> with 1.2.3

**Comment by shekhar162** [comment]
If you followed the doc instruction properly, then this issue can be resolve by removing 
var/cache 
and 
var/generation folders

**Comment by hansa-webmavens** [comment]
I got this error bcz I did not specify crypt key properly
