### ISSUE TITLE
Cms pages meta title

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#482]
Please add separate fields for Internal title and meta title for cms pages. It is getting hard to manage them if the title is used as a meta title.  
Here is a small example. 
Let's say you have to store views, each one with it's separate homepage. I cannot set the title to "Homepage" for SEO reasons and when I see the Meta title in the grid is kind of hard to figure out which one is the homepage.  
Also, some pege meta titles need to be a little longer and in this case the grid looks ugly. An internal title would solve this issue.

**Comment by tkacheva** [comment]
Scheduled to be done in the scope of MAGETWO-22739

**Comment by tzyganu** [comment]
I will close this issue since the PR was merged.  Thank you.
