### ISSUE TITLE
Css changes reflect only after deploy command in magento2

### ISSUE THREAD

**Issue by devishreebalasubramanian** [magento/magento2#4820]
Now i have created custom theme in magento2.Every time i wrote css it doesn't reflect immediately.I have changed mode to "developer".And also disable cache in backend.I have given the following commands to reflect my custom css.

**rm -f var/\* -R**

**rm -f pub/static -R**

**php bin/magento setup:static-content:deploy**

**chmod 0777 var -R**

**chmod 0777 pub/static -R**

It takes too much time to do my design work.So please anyone help on this.

**Comment by stamster** [comment]
First off,
if you believe you have enabled "developer" mode in Magento - think again. Someone was that smart to assume that you'll develop only modules etc (code, business logic) and not themes / styling in developer mode.
The thing is, even in a developer mode, Magento2 still has many levels of cache enabled. I have never saw such architecture. 
So your best shot during theme development would be to disable completely:
- Layouts
- Blocks HTML output
-  Page Cache 

In System -> Cache management.

P.S. you should be aware of 777 permissions - that is just awful way of solving issues and making your entire instance insecure.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Css-changes-reflect-only-after-deploy-command-in-magento2/idi-p/45221).
