### ISSUE TITLE
Multi-select for Product edit not saving values other than first selection on Save

### ISSUE THREAD

**Issue by synzhu** [magento/magento2#4822]
I am experiencing an issue similar to issue #4346. If I try to select multiple items for a multi select attribute from the product edit view (in this case, the attribute is Bolt Pattern), only the first one is actually saved to database when I press Save. 
<img width="1425" alt="screen shot 2016-06-01 at 4 02 32 pm" src="https://cloud.githubusercontent.com/assets/14226557/15728593/4e7cfe1e-2812-11e6-9fd6-60a220c99b7f.png">
However, if I go to the database and manually add the value for the attribute in the `catalog_product_entity_varchar` table, it shows up correctly when I reload the page in admin panel

<img width="754" alt="screen shot 2016-06-01 at 4 09 52 pm" src="https://cloud.githubusercontent.com/assets/14226557/15728745/5a695e42-2813-11e6-9957-f599c13a49ec.png">
<img width="294" alt="screen shot 2016-06-01 at 4 11 17 pm" src="https://cloud.githubusercontent.com/assets/14226557/15728776/856fd634-2813-11e6-940d-3dede809a303.png">

 but if I press Save, again it only selects the first one and all the others are removed from database as well.

<img width="261" alt="screen shot 2016-06-01 at 4 12 49 pm" src="https://cloud.githubusercontent.com/assets/14226557/15728814/d4a083ac-2813-11e6-84e7-dda27c04694c.png">
<img width="775" alt="screen shot 2016-06-01 at 4 13 27 pm" src="https://cloud.githubusercontent.com/assets/14226557/15728837/ef66ea78-2813-11e6-9efd-d0cdfa378425.png">

**Comment by sunilit42** [comment]
have you created attribute using script or backed?

**Comment by synzhu** [comment]
It was migrated from Magento 1. I have not checked if this problem exists with new attributes created in Magento 2.

**Comment by sunilit42** [comment]
may be it problem with migration Plase check source model and backend model for same.

**Comment by salelsol** [comment]
Fixed, go to eav_attribute table, search you multiselect attribute and change in "backend_model" column NULL value with this value: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend, clear cache and reindex and ty.

**Comment by mitcht** [comment]
I'm seeing this problem too, albeit with Customer.. Created using a script properly. Can include source if requested.  I'm using the Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend method.  No values are persisting for me, but the attribute is saving the option_id to the database in the customer_entity_<type> table.  I've tried text and varchar. Both save but will not populate the dropdown.

**Comment by palamar** [comment]
@simon-zhu 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by mitcht** [comment]
I am using Magento 2.1.x RC3

**Comment by salelsol** [comment]
Hi Simon, used version is: Magento 2.0.7, PHP 5.6 and now multiselect works fine. This issue is coming  afther migrate customers, order, etc from Magento 1.9 to Magento 2.

**Comment by jvreeken** [comment]
I was having the same problem.  Migrated a site from 1.9.x to 2 and multiselect attributes have null for backend_model.  saving the attributes would not change the values.

SQL to change would be:
`UPDATE`eav_attribute`SET`backend_model`= 'Magento\\Eav\\Model\\Entity\\Attribute\\Backend\\ArrayBackend' WHERE`attribute_code`= ‘your_attribute_code';`

Replace "your_attribute_code" with the attribute code of the attribute that is giving you trouble.

**Comment by smokygeek17** [comment]
Magento 2.1.3 still reproducible. Multi-select attribute not being saved. Although 
backend_type = varchar
backend_model  = Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

**Comment by AbdulKadir-Agoliya** [comment]
Fixed For me magento2.1.0, go to eav_attibute table, search you multiselect attibute and change in "backend_model" column NULL value with this value: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend, clear cache and reindex and ty.

**Comment by smokygeek17** [comment]
@AbdulKadir-Agoliya I tried that, but didn't help. The only workaround I found is to use the Mass action attributes update. Then it saves the change of multi-select attribute

**Comment by Szymon-GP** [comment]
2.1.4 and the problem still exist

**Comment by daniel-ifrim** [comment]
I have this issue on not saving multiselect in a product.
I see this issue reported here. It could be various reasons but also it can be the same issue:
https://github.com/magento/magento2/issues/7646
https://github.com/magento/magento2/issues/5445

This happens to me if I have 1 configurable product from other attribute set that does not have this attribute in it.
Actually I'm doing more tests and I see that only if I have 1 configurable product (and doesn't matter if i have the multiselect in the second attribute set or not) in related products it will not save the attribute.
It happens only for multiselect. I've tested with dropdown and boolean and the issue is not there. I've tested it on CE 2.1.6 with sample data too.
Are you in the same case ? Do you have a configurable product in related, cross or up-sell products like my case ?

**Comment by AlexWorking** [comment]
Hello, @simon-zhu.  We were not able to reproduce Your on neither of develop versions for Magento2. (2.0.15, 2.1.7, 2.2.0). Please if You still can reproduce this issue on either of versions let us know. Thanks for Your reporting.

**Comment by AgentGod** [comment]
Hello Magento Team,
I had similar problem, but only sometime. After some investigation I found:
1. Can not save multiselect attributes if there is related product attached.
2. If I have any product attached to related, when I try to change options in multiselect attributes, I was not able to save with the new selection set. 
3. On the same products when I remove the product attached to related, everything worked as expected.
So if I have any product with multiselect which needs change, I had to remove related products, make changes to multiselect options and save. After saving all atributes are saved correctly and then add the related products and save again. 
Tested on Magento 2.2

**Comment by duckchip** [comment]
Tested on 2.1.9

I'm having the same issue. Even when creating a new product attribute of type multiselect in the backend, the problem occurs: when selecting an option in the multiselect on a product, the value doesn't get saved. 

As @AgentGod explained, there's a detour of making this to work:
1. remove all upsells, cross-sells and related products. 
2. save the product
3. make changes to the multiselect attribute on the product
4. save the product
5. add all the upsells, ...

**Comment by duckchip** [comment]
after further digging i found that when you have a configurable product in your up-sells/cross-sells, the price becomes 0, explained in issue magento/magento2/issues/8960 
When removing this configurable product from the up-sells/cross-sells/... The mulit-select attribute works just fine.

**Comment by AbdulKadir-Agoliya** [comment]
@duckchip 
Fixed For me magento2.1.0, go to eav_attibute table, search you multiselect attibute and change in "backend_model" column NULL value with this value: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend, clear cache and reindex .

**Comment by AbdulKadir-Agoliya** [comment]
hello @duckchip 
Fixed For me magento2.1.0, go to eav_attibute table, search you multiselect attibute and change in "backend_model" column NULL value with this value: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend, clear cache and reindex .

**Comment by duckchip** [comment]
Hi @AbdulKadir-Agoliya 
I'm running on 2.1.9 and this fix is already included, unfortunately it's still not working.
I think it has to do with a problem relating to configurable products as cross-sells/up-sells/....

**Comment by vseager** [comment]
Still having the problem on 2.1.11

**Comment by vseager** [comment]
Update: This was fixed by...

https://github.com/magento/magento2/issues/4822#issuecomment-253877404

**Comment by imanasmage** [comment]
I have this exact issue on Magento 2.2.5

**Comment by A-1A** [comment]
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this
**Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Please check this Url
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444

**Comment by mariamghalleb** [comment]
same issue, magento 2.2.4

**Comment by AbdulKadir-Agoliya** [comment]
hello #mariamghalleb
Fixed For me magento2.1.0, go to eav_attibute table, search you multiselect attibute and change in "backend_model" column NULL value with this value: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend, clear cache and reindex .

**Comment by collinanderson** [comment]
I had to change `backend_type` from `varchar` to `text` to get it to work.

**Comment by mariamghalleb** [comment]
@AbdulKadir-Agoliya that column is not NULL by default it has Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend.

**Comment by U12358** [comment]
getData($key) and getData()[$key] return different values, scalar vs array

My fix
![screenshot from 2018-07-20 17-33-40](https://user-images.githubusercontent.com/813985/43008202-15f5dc0e-8c43-11e8-9893-7ad7676d0d46.png)

**Comment by PetmePant** [comment]
> @AbdulKadir-Agoliya that column is not NULL by default it has Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend.

Same here. I still have to delete my related products in order to make it work

**Comment by insaneCreations** [comment]
I still have the problem in 2.1.9 and this is beginneng to get frustrated.

> I had to change `backend_type` from `varchar` to `text` to get it to work.

This works only then the dropdown in the frond-end goes away.

The solutions of changing the "backend_model" does not work for me, but is there someone who can help me with a solution

**Comment by insaneCreations** [comment]
> Magento 2.1.3 still reproducible. Multi-select attribute not being saved. Although
> backend_type = varchar
> backend_model = Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

Dit you find a solution? Because i'm in 2.1.15 and i've tried all these methods and nothing works

**Comment by saminforca** [comment]
same issue.

Magento 2.2.6  Multi-select attribute not being saved. Although
backend_type = varchar
backend_model = Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

I also don't have any related products but still facing an issue

**Comment by saminforca** [comment]
After long hind and seek with database, I came to know that it was the migration issue from m1 to Magento 2.

The following list of items has fixed the issue for me.

backend_type = text
backend_model = Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

php bin/magento c:c

php bin/magento c:f

Hope this will fix it out for you.

**Comment by darrenf-fisheye** [comment]
> After long hind and seek with database, I came to know that it was the migration issue from m1 to Magento 2.
> 
> The following list of items has fixed the issue for me.
> 
> backend_type = text
> backend_model = Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend
> 
> php bin/magento c:c
> 
> php bin/magento c:f
> 
> Hope this will fix it out for you.

You also need to reindex
