### ISSUE TITLE
"Catalog Products List" includes "Out of Stock" products when "Quantity is In Stock" is a required condition of the widget and the products are given the quantity "Out of Stock" from within admin

### ISSUE THREAD

**Issue by ankitambekar08** [magento/magento2#4825]
When i save the block giving Quantity is In Stock" is a required condition of the widget for Home page i get the following error.

Error filtering template: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_quantity_and_stock_status.value' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_flat_1` AS `e` INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`at_quantity_and_stock_status`.`value`, 0) = '1') ))

**Comment by veloraven** [comment]
@ankitambekar08 ,
- please provide description according to the template: with steps, actual result and expected result;
- please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
