### ISSUE TITLE
Region Code showing the value of Region Name when downloading Sales Order data using REST API

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#4826]
## Steps to reproduce
1. Install Magento latest version.
2. Place an Order.
3. Pull the order using REST API
4. Have a look at the address section.
## Expected result

1.region_code contains the value of region_code.
## Actual result
1. region_code contains the value of region_name.
2. ![sales1](https://cloud.githubusercontent.com/assets/16597334/15737369/4bf8854e-28c3-11e6-9ca3-99c6429e083a.png)

**Comment by oserediuk** [comment]
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by arijit-de93** [comment]
Hello @oserediuk thanks for giving time on this.

What I observer in the latest build 2.1 is that if it gets region_code for that region, it will give  the value of region_code and if not it will return region name.

But can please tell why you are returning region name when region_code not found? Is there any particular reason for that?

Thanks

**Comment by RomanKrut** [comment]
@arijit-insync Hi, i was tried to reproduce your issue and i got this result
![screenshot_1](https://user-images.githubusercontent.com/27814479/27836593-bdd73d28-60e8-11e7-9e88-2c00d269fc7a.png)
You can try to get information about country by V1/directory/countries/US request and you will see which id,code and name should be on your region.
![screenshot_2](https://user-images.githubusercontent.com/27814479/27836710-57172174-60e9-11e7-8794-3911d75ada6e.png)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
