### ISSUE TITLE
Inconsistent cms block validation and save methods

### ISSUE THREAD

**Issue by vovayatsyuk** [magento/magento2#4831]
### Additional information

The issue was reopened on 16 July 2019. 
The reopening reason is that current behavior(after fixes) brings new issues. [See comment for details](https://github.com/magento/magento2/issues/4831#issuecomment-510763579)

> 1. Currently, I have to re-save an existing block (select every store view except one manually) and only after that, I can finally create a block for a specific store view.
> 2. Previously, I could add a new block and it just works. Magento correctly used the fallback mechanism to show the correct block at every store view.
> 
> Additionally, when using a new approach, if I'll create a new store view I have to open cms block again and select newly created store view in store views combo box. Previously all work flawlessly because I always had a default block saved with "All store views" selected.

## Preconditions
Magento develop branch

## Steps to reproduce
1. Install Magento from `develop` branch.
2. Make sure that you have only one store view and `SingleStoreMode` option in disabled
3. Create cms block `example` for `All Store views`
4. Create another cms block `example` for first store view only
## Expected result
1. Block should be saved for selected store view
## Actual result
1. An exception will be thrown:
   
   ```
   A block identifier with the same properties already exists in the selected store.
   ```
## Propose

Validator should validate actual block data, so we can remove the following check completely:

``` php
if ($this->_storeManager->hasSingleStore()) {
    $stores = [Store::DEFAULT_STORE_ID];
}
```

https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Model/ResourceModel/Block.php#L186-L188

**OR**

this logic should be moved to `_beforeSave` and slightly modified, to check `SingleStoreMode` option:

``` php
if ($this->_storeManager->getSingleStoreMode()) {
    $object->setData('stores', [Store::DEFAULT_STORE_ID]);
}
```

**Comment by IlnitskiyArtem** [comment]
@vovayatsyuk, Thanks for the feedback.
I reproduced it on last Magento 2 develop branch. Also i tried to create CMS Blocks with same identifiers at first for the Default Store View, and just then for All. In such way it worked. 
The logic is that when you create it for All Sore Views at first with Single Store mode disabled, CMS Block identifier Is for all stores and cannot be duplicated. In other way, when you create it for a particular Store View, it checks just certain area where it is already created.
That functional with disable Single Store is not a bug.

**Comment by vovayatsyuk** [comment]
Thanks, I know why it shows an error and I wrote a proposed solution that will fix this behavior.

If you'll dig into this a little more, you'll see that validation and save methods are inconsistent:

Save method uses data from the request, while validation [does not](https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Model/ResourceModel/Block.php#L187). Validation put a `[Store::DEFAULT_STORE_ID]` into $stores variable but the actual stores are left in the object and will be saved as well if validation will return true.

And that is a bug, I think. It's not a valid behavior when validation checks data that will not be saved actually.

**Comment by magento-engcom-team** [comment]
@vovayatsyuk thank you for your bug report.
We've created internal ticket MAGETWO-75216 to track progress on the issue.

**Comment by thiagolima-bm** [comment]
I am working on it at #mm17es

**Comment by thiagolima-bm** [comment]
this was fixed already #11805

**Comment by okorshenko** [comment]
Hi @vovayatsyuk 
The issue has been fixed in  #11805
@thiagolima-bm thank you for your contribution! 👍

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17603`, `MC-17604` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @vovayatsyuk and @orlangur 

All internal Jira tickets(`MC-17604`, `MC-17603`) related to this issue were closed by Magento team with resolution `Not a Bug`.
Because of the quote:
> it's expected behavior, that we can't save block with the same identifier for specific store view if it's already saved for all store views.

It was fixed intentionally.
Additional information:
- GitHub issue https://github.com/magento/magento2/issues/8236 with original report
-  PR: https://github.com/magento/magento2/pull/11802 to fix it

 Also additional bug related to this issue was fixed by internal team in the scop of `MAGETWO-91559` 
 - 1f743bd7fdf8147a80630fbd8f37a2cd53ee4d49
 - 78a9a737a2c64c7deece3fa4708a57c23cf4d314
 - e61b23a8e506576974cf37f12929c7b2c8053614
 - 8b4c1fa781ef14b2f1b9d3ae46be5b932cf108a6

**Comment by vovayatsyuk** [comment]
I strongly disagree with this quote:

> it's expected behavior, that we can't save block with the same identifier for specific store view if it's already saved for all store views.

Let's work on it together to allow to do that and fix all possible issues (if any).

Let me explain:

1. Currently, I have to re-save an existing block (select every store view except one manually) and only after that, I can finally create a block for a specific store view.
2. Previously, I could add a new block and it just works. Magento correctly used the fallback mechanism to show the correct block at every store view.

Additionally, when using a new approach, if I'll create a new store view I have to open cms block again and select newly created store view in store views combo box. Previously all work flawlessly because I always had a default block saved with "All store views" selected.

p.s. The issue you are referring to (https://github.com/magento/magento2/issues/8236) is about saving block with the same store_id while we are talking about different store_ids.

**Comment by sdzhepa** [comment]
Hello @vovayatsyuk 

Thank you for your feedback and collaboration!

I am reopening this issue. 
It seems important part/cases were missed and we should consider it again

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18224` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sergey-solo** [comment]
https://github.com/magento/magento2/pull/23255

**Comment by PascalBrouwers** [comment]
@sdzhepa please revert and allow same identifier for specific store view.

**Comment by engcom-Charlie** [comment]
Hello @vovayatsyuk

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided scenario.
**Precondition**: 

- _only one store view_
- _SingleStoreMode_ option in disabled

**Steps**
1. Install Magento from latest _2.4-develop_ branch.
3. Create cms block _example_ for All Store views
4. Create another cms block _example_ for first store view only

**AR**: Block saved successfully

Could You take a look?

**Comment by vovayatsyuk** [comment]
Looks like it was fixed in this commit: https://github.com/magento/magento2/commit/c8baed5750f705531e75573ac8a1977dd6fe7d5f

**Comment by engcom-Charlie** [comment]
So we have to close it.
