### ISSUE TITLE
Terminal:   There are no commands defined in the "setup" namespace.  

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4832]
Since upgrading to 2.0.7 (which failed) we cannot use php bin/magento anymore.

We get: There are no commands defined in the "setup" namespace. 

How can we get rid of this? We need the Terminal function!

**Comment by grasdaggel** [comment]
A invalid module was the problem. Deleting the module fixed the problem.

However, now setup:static-content:deploy is super slow. Need more then 20 minutes to finishes the task. Before this matter it went trough in a few seconds (<30 seconds).

Any way to check how long a task needs until its finished?

**Comment by stamster** [comment]
In general, there's no way to predict time needed to complete your CLI tasks. Static content deployment does lot's of disk I/O, which can also slow things down on a system with low IOPS or a busy underlying I/O subsystem.

**Comment by adragus-inviqa** [comment]
This one needs better handling of the exceptions thrown in `\Magento\Framework\Console\Cli::doRun()`.

Something like 

``` php
        try {
            $exitCode = parent::doRun($input, $output);
        } catch (\Exception $e) {
            $output->writeln($e->getTraceAsString());
        }
```

This will get you the _real_ exception.

**Comment by grasdaggel** [comment]
Thanks for that snippet.

We are using SSD Hosting with extremely fast storage I/O and as told, normally the process needs about 30 seconds up to 1 minute, NEVER more. 

Thanks for the clarification anyway, would have been nice to trace the time, but for what do I have an iPhone? 💨 

What seems odd is that if you add multiple lines, i.e. "asdf","asdf" to your lang_LANG.csv-file it slows down the process of generating the new content. Maybe devs can check this and optimize it, if needed.

**Comment by benmarks** [comment]
> if you add multiple lines, i.e. "asdf","asdf" to your lang_LANG.csv-file it slows down the process of generating the new content

I _think_ this is a known issue, but I'll check.

**Comment by grasdaggel** [comment]
Of course it gets slowed down if you rm -rf pub/static/\* beforehand. Just in case somebody has the same problem but deleting the static content before. If you do this, obviously things will take more time. However, this is _not_ the problem that I have in this ticket.

**Comment by palamar** [comment]
@grasdaggel could you please, provide additional information:
- Magento version before upgrade
- module that cause problem
- etc.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
