### ISSUE TITLE
Gateway payment module not showing on checkout page 

### ISSUE THREAD

**Issue by alexcrz** [magento/magento2#4836]
Hi , I just enabled a payment gateway module , https://github.com/Inchoo/magento2-Inchoo_Stripe , I got the module in the backend , added the api and enabled it , but I can't see nothing in the front end on the checkout page.

**Comment by antonlazarchenko** [comment]
I've already left comments for you here http://magento.stackexchange.com/questions/118078/payment-gateway-inchoo-doesnt-show-up-on-checkout-page-magento-2#comment160526_118078
Specify some details.

**Comment by alexcrz** [comment]
Ok , I've replyed you there !

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
