### ISSUE TITLE
Category and Brand SEO url not working after data migration using data migration tool

### ISSUE THREAD

**Issue by akshoysaha** [magento/magento2#4837]
We are migrating from Magento 1.7.x to 2.0.5. We have used Data Migration Tool to import all data; all categories, products, orders, brands came fine and we can see in admin. But the main problem we found with SEO url of categories and brand pages. 

http://www.goplaces.co.uk/luggage/ is the old website. On the new website, it should be http://wiseroi.co.uk/luggage.html (urk key is set as "luggage") but no SEO url was working - it was returning 404 page. http://wiseroi.co.uk/catalog/category/view/s/luggage/id/4/ is the URL of luggage category; if you browse through brands and categories you can see similar URL pattern.

We  have created a new test category from Magento admin to test if there is any issue with Magento installation but SEO url working fine for new category.

SEO URL doesn't exist for imported products - all products have SEO URL working fine.

Another issue we noticed, when trying to Flush Cache from Cache Management, Magento shows "There has been an error processing your request. Exception printing is disabled by default for security reasons." error.

**Comment by duhon** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
