### ISSUE TITLE
Category Page Sort By and Ascending/Descending options added to query string by order clicked (bad for full page cache)

### ISSUE THREAD

**Issue by AirmanAJK** [magento/magento2#4838]
## Steps to reproduce
1. Visit a category page with products.
2. First Sort By Price, then Sort by Descending Order (arrow icon should face down)
3. The query string will read as follows: "?product_list_order=price&product_list_dir=desc"
4. Remove both sorting filters, then add them in the opposite order (first Descending Order, then Price)
5. The query string will read as follows: "?product_list_dir=desc&product_list_order=price"

As with filterable attributes, query string parameters should be added in a deterministic way since the full page cache relies on URLs for the same page to be identical. The same page now needs to be cached twice.

This oversight greatly increases the number of pages that need to be cached as it applies to every single category page with all combinations of filters.

**Comment by palamar** [comment]
@AirmanAJK 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
