### ISSUE TITLE
Cannot update Manage Inventory in the admin panel

### ISSUE THREAD

**Issue by pizzachip** [magento/magento2#4839]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Upload a catalog of more than 1000 products including complex products while
3. Navigate to Stores > Configuration > Catalog > Inventory
4. Change Manage Stock option to 'No'
## Expected result

1.Setting should change to NO
## Actual result
1. SQL error and returns to main Stores > Configuration page
   ![screen shot 2016-06-02 at 6 37 20 pm](https://cloud.githubusercontent.com/assets/12566929/15764536/1d9a87fa-28f1-11e6-8bca-294e7514f92a.jpg)

**Comment by oserediuk** [comment]
Hello @pizzachip ! I cannot reproduce your case. Which code version do you use?

**Comment by pizzachip** [comment]
2.0.7

**Comment by mhabou** [comment]
@pizzachip : Did you use database prefix ?

**Comment by andimov** [comment]
@pizzachip
Do you have any updates for this issue?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
