### ISSUE TITLE
Magento 2.1 Release Canidate:  PHP Fatal error:  Undefined class constant 'VERSION'

### ISSUE THREAD

**Issue by astorm** [magento/magento2#4840]
In Magento 2.0.0, the `Magento\Framework\AppInterface` interface contained the following constant

```
/**
 * Magento version
 */
const VERSION = '2.0.0';
```

The release candidate removed this constant, which results in the following error if extensions or custom system integrator code took advantage of this constant.

> PHP Fatal error:  Undefined class constant 'VERSION'

This is not a theoretical problem -- this change will break at least two real world extensions ported from Magento 1.  The use case is a series of custom API endpoints for a Magento 2 system that fill gaps not provided by Magento's stock API endpoints.  These API endpoints include the system information (including version) to help the extension vendor troubleshoot problems for users in a proactive way.  
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a Magento module with a controller, command line entry point, or other place to write PHP code in a Magento bootstrapped enviornment
3. Add the following PHP code `$test = Magento\Framework\AppInterface::VERSION`
4. Run the code added in #3 
## Expected result
1. Code executes without error
## Actual result
1. Code fails with `PHP Fatal error:  Undefined class constant 'VERSION'`

**Comment by orlangur** [comment]
Please read the http://devdocs.magento.com/guides/v2.0/architecture/backward-compatibility.html carefully. As I understand it, `Magento\Framework\AppInterface::VERSION` constant must not be retained in 2.1 as it is not marked with `@api`.

So, if some extension rely on internals, it should specify dependency properly like `"magento/customer": "~2.0.0"` and then tested when minor version is changed before changing dependency.

But a couple of things make me sad and I believe they can and must be solved for good:
- https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/App/ProductMetadataInterface.php is not marked with `@api`, so, something can be broken in 2.2 again
- It's quite vague for things like constants or method signatures not marked as `@api` in which version they are marked as `@deprecated` if necessary and when they can be removed

**Comment by sivaschenko** [comment]
Use those [two lines](https://github.com/magento/magento2/blob/e46a3cfeccae6f8fcd1eb408719f48d2e039c433/bin/magento#L23-L24) as workaround.
