### ISSUE TITLE
Custom EAV textarea and Image for customer not save

### ISSUE THREAD

**Issue by quienti** [magento/magento2#4843]
## Preconditions
1. Magento 2.1.0RCI

## Steps to reproduce
1. Magento 2.1.0RCI
2. I use this code for my attribute in installdata (for my custom module)

For textarea :

`$customerSetup->addAttribute(Customer::ENTITY, 'company_description', [
    'type' => 'text',
    'label' => 'Compagny Description',
    'input' => 'textarea',
    'required' => true,
    'visible' => true,
    'user_defined' => true,
    'sort_order' => 1000,
    'position' => 1000,
    'system' => 0,
    'adminhtml_only' => 1,
]);`

For Image :

`$customerSetup->addAttribute(Customer::ENTITY, 'company_logo', [
    'type' => 'varchar',
    'label' => 'Compagny Logo',
    'input' => 'image',
    'backend' => 'Magento\Catalog\Model\Category\Attribute\Backend\Image',
    'required' => false,
    'visible' => true,
    'user_defined' => true,
    'sort_order' => 1001,
    'position' => 1001,
    'system' => 0,
    'adminhtml_only' => 1,
]);`
1. Create a new or edit a customer
2. Save
## Expected result
1. Save my news attributes
## Actual result
1. I get this error
   ![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/15772875/090437cc-2974-11e6-9797-fb9963a8ba62.jpg)
   ![sans titre 3](https://cloud.githubusercontent.com/assets/7326954/15772881/0fcbe712-2974-11e6-9367-8c8c5164d9b9.jpg)
   ![sans titre 5](https://cloud.githubusercontent.com/assets/7326954/15772878/0bff6ab4-2974-11e6-9ec7-71fb163895bf.jpg)
2. If I remove `required` for my attriblute, my attribute is not saved. 
   ![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/15772883/13984f84-2974-11e6-87b8-c7b321181f68.jpg)
   ![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/15772888/1c3b8b24-2974-11e6-956c-2597b837e3e9.jpg)

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.
We've created internal ticket(s) MAGETWO-80692 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
