### ISSUE TITLE
M2.1 SOAP WSDL Xml Entities double escaped

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#4847]
## Preconditions
1. Install Magento from `2.1` branch.

## Steps to reproduce
1. Install Magento from `2.1` branch.
2. Call http://magento_host/soap/default?wsdl_list=1

## Expected result

...

``` xml
<item>
    <wsdl_endpoint>http://magento_host/soap/default?wsdl&amp;services=0</wsdl_endpoint>
  </item>
```

...

## Actual result

the '&' is double escaped
...

``` xml
<item>
    <wsdl_endpoint>http://magento_host/soap/default?wsdl&amp;amp;services=0</wsdl_endpoint>
  </item>
```

...

might be a duplicate of https://github.com/magento/magento2/issues/2206 
if so, will this be fixed in the next 2.1 release?

**Comment by magento-engcom-team** [comment]
@davidverholen, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
