### ISSUE TITLE
Customer Groups NOT LOGGED IN & TAX CLASS not editable?

### ISSUE THREAD

**Issue by MisterMcJohn** [magento/magento2#4849]
Magento ver. 2.0.7
## 
1. When try to change the TAX CLASS for group name "NOT LOGGED IN"  in to another TAX CLASS from Dropdown menu
## Expected result
1. It shoot accept the change and confirm and set to the new chosen TAX CLASS
## Actual result

When save this new chosen TAX CLASS, Magento error say's:  code is a required field. When save the field is empty. And even if it empty now, I cannot fill in a GROUP NAME because it's grayed out?
1. [Example] Error message appears: "code is a required field.".

![taxclassgrouperror01](https://cloud.githubusercontent.com/assets/19727868/15775523/920204d8-2982-11e6-8298-cdfea1f11ca5.jpg)
![taxclassgrouperror02](https://cloud.githubusercontent.com/assets/19727868/15775524/92025438-2982-11e6-9d9e-d1299a3f5427.jpg)
![taxclassgrouperror03](https://cloud.githubusercontent.com/assets/19727868/15775522/92021842-2982-11e6-8a80-c90f59fd8463.jpg)

**Comment by mikeweis** [comment]
@MisterMcJohn Thank you for reporting. We have created internal ticket MAGETWO-53916 to track this issue.

**Comment by mikeweis** [comment]
- This issue has been resolved and merged to develop. Feel free to let us know if you encounter any other issues.
- note: the fix was supplied via internal ticket MAGETWO-53194

**Comment by alcantera** [comment]
i got the same problems and i like to now where i can find the sollution?
