### ISSUE TITLE
Issue with creating OAuth app

### ISSUE THREAD

**Issue by foray1010** [magento/magento2#4851]
## Steps to reproduce
1. Install Magento 2.0.4
2. Create an integration and save
3. click activate
4. mostly it will said customer key is expired when we use the response from store to get response token

I was trying to create an apps, that create integration immediately after user install the app, but as the expire time start counting once the integration created, 5 seconds (default value) is not enough to let the user to navigate to integration page => click `activate` => let my server to get the request/access token
[That also make me wonder why the consumer key is not generated when user click `activate`, because it means users need to rush to activate within 5 seconds, and also consider my server needs time to process]

Yes, we can ask the user to create the integration on his/her own but that require user to input the name, endpoint url, etc and click `Save & Activate` which is not user friendly

So, I am wondering if there is any method that can create oauth app with better user experience (without taking so much step precisely)
For example, is there any way to create integration and activate immediately?

**Comment by choukalos** [comment]
Hi @foray1010 - Please try upgrading to 2.0.6; this issue should be addressed in that patch version.  Please let me know if it still persists.

**Comment by pboisvert** [comment]
closing issue as this should be resolved in latest version. Please reopen if the issue persists after upgrade
