### ISSUE TITLE
Two Page Printout Invoices for customers

### ISSUE THREAD

**Issue by Jasonb11** [magento/magento2#4858]
## Steps to reproduce
1. Login to customer account
2. Go to my orders > choose any order > view order
   http://screencast.com/t/e4nN3cQmq
3. Go to Invoices tab or click print order
   http://screencast.com/t/UNBfCvXpAUc
## Expected result
1. Print One page similar to the invoice on the backend
   http://screencast.com/t/dl3VmJbN2N
## Actual result
1. Two page layout that looks horrible and is wasteful if printed.
   http://screencast.com/t/Mv0951bzD7Z

**Can this be changed somehow? How?
Are there any extensions that anyone can recommend that will change this?**

**Comment by pboisvert** [comment]
classifying as an improvement. This is not a bug. How to questions should be asked on Stack Exchange for the Magento Community forum.
