### ISSUE TITLE
adding configurable product to cart does not show the image of the simple product

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#4859]
Adding a configurable product with specific options does show a different image on the product page, but this product is not shown on the cart or checkout page.

For example, use the sample data. 
- Add the Mona Pullover Hoodlie in your cart with Color Orange and Size S.
- In your cart you will see the image from the configurable and not from the simple product.

Tested in magento 2.0.7

**Comment by PascalBrouwers** [comment]
Seems to be going wrong in Magento\Catalog\Helper\Image::initBaseFile()

This line: $model->setBaseFile($this->getProduct()->getData($model->getDestinationSubdir()));
tries to get the thumbnail of the image but it's not returning it.
If I do $model->setBaseFile($this->getProduct()->getImage()); it seems to get the correct image, although it's the full image instead of a thumnail.

**Comment by paales** [comment]
Version: 2.1.0

### Steps to reproduce

Create a configurable product with multiple color tshirts and related images.

### Expected result

The product image should be the image of the underlying simple product 'Carolina Azul' in the cart, like it is on the product page.

![schermafbeelding 2016-06-24 om 11 58 11](https://cloud.githubusercontent.com/assets/1244416/16334734/f39ef9e0-3a02-11e6-8dee-da020613edc8.png)

### Actual result

![schermafbeelding 2016-06-24 om 11 56 42](https://cloud.githubusercontent.com/assets/1244416/16334694/c295b5c8-3a02-11e6-8a9a-7dd044681fb5.png)

**Comment by PascalBrouwers** [comment]
Found out this is now a setting in the backend:
Configuration->Checkout->Shoppin Cart->Configurable Product Image = Product Thumbnail itself
