### ISSUE TITLE
Admin page missing CSS - just displays in plain text.

### ISSUE THREAD

**Issue by commalex** [magento/magento2#4860]
Tried all the google solutions...just have no ideas.  Front end is working perfectly at www.3signs.co.uk

Can anyone help me?

**Comment by commalex** [comment]
Some odd things that I noticed in cache management:
Page Cache  Full page caching.  FPC Invalidated ???

also noticed in inxeder:
Catalog Product Rule    Indexed product/rule association    Update on Save  Processing  Nov 20, 2015, 2:11:19 AM

**Comment by pboisvert** [comment]
@commalex can you provide more system info here. What version are you seeing this issue?

**Comment by commalex** [comment]
Version 2.0.7

Kind Regards,
Alex Smith

stika.co
alex@stika.co
07921 909844

twitter.com/stikaco
facebook.com/stika-co

**Comment by commalex** [comment]
The error problem happened immediately after I removed the sample attribute sets in the admin backend.

Kind Regards,
Alex Smith

stika.co
alex@stika.co
07921 909844

twitter.com/stikaco
facebook.com/stika-co

**Comment by commalex** [comment]
So the error occurs when removing the demo 'Attribute Sets' in the Admin backend.
