### ISSUE TITLE
Page Cache Invalidation fails for CMS entities when changing options in the "design" tab 

### ISSUE THREAD

**Issue by jmackiol-dotsource** [magento/magento2#4862]
## Steps to reproduce
1. Install Magento 2.0.7 EE using composer.
2. Go to Admin > Content > Pages
3. Create a new page with content and design related changes
4. Open the new page in frontend
5. Edit the created page and only change options in the design tab
6. Open the edited page in the frontend
## Expected result
1. Changes are visible
## Actual result
1. Changes are not visible
   The entire cache needs to be flushed in order to activate the changes.
   Changes in other sections will invalidate the respective page cache and changes are visible.

**Comment by choukalos** [comment]
Unable to reproduce in mainline.
