### ISSUE TITLE
Knockout.js fails if there are cart messages

### ISSUE THREAD

**Issue by gamort** [magento/magento2#4865]
If there are issues with items in the shopping cart that result in warning messages being generated, knockout.js fails to update any of the dynamic blocks on the page - leaving them in their default state.

We discovered this specifically with the following combination:
Magento 2.0.7
Enable inventory management for the website/store
Add/enable the wishlist block to product listing pages
Add multiple items to the wishlist.
Add multiple valid items to the cart[valid meaning the quantity is less then the inventory]

**At this point the cart icon displays the number of items in the cart.  The sidebar cart displays the items in the cart[when clicking on the cart icon].  The wishlist in the sidebar displays products from the wishlist.**

Add an invalid item to the cart[quantity added > available inventory]
Go to the cart page: all the items are in the cart, there will be a warning note at the top of the page regarding the item that cannot be fully ordered.

Go to a product listing page.
The cart icon/sidebar cart does not display the number of items in the cart
The sidebar cart[when expanding it by clicking on the cart icon] does not display any items in the cart.
The wishlist displays the "no items in your wishlist" message.

Clarification:
What is being displayed in each of those dynamic blocks is the default html for those blocks.  That html is supposed to be modified by knockout.js after the page is loaded.

Potential Cause:
My assumption is that the customer data generated by Magento in json format is somehow corrupted by the warning message being generated for the item which is invalid.   This issue is difficult to troubleshoot because the customer data json was generated when the invalid item was added to the cart and then cached.  Since the data is loaded from the website with Ajax, processed, and then cached somewhere in the web browser and only refreshed when it changes - it is not possible to use the chrome developer tools to actually view the json that was generated and it is extremely difficult to locate the cached data in the web browser - **and that cached data does not match the data generated by the server.**

**Comment by orlangur** [comment]
>  then cached somewhere in the web browser and only refreshed when it changes - it is not possible to use the chrome developer tools to actually view the json that was generated and it is extremely difficult to locate the cached data in the web browser - and that cached data does not match the data generated by the server.

I didn't read all of the text carefully, just did a quick overview.
It's pretty convenient to see all JSON responses in Network tab with "Preserve log" checkbox checked and some filters (XHR?).
If you're talking about browser cache, it just can be disabled, also, customer data is stored in localStorage. You can remove some section at any moment to force it's reload from server side.

**Comment by gamort** [comment]
> It's pretty convenient to see all JSON responses in Network tab with "Preserve log" checkbox checked and some filters (XHR?).

I did not think of enabling the preserve log checkbox.  Thanks!  That will be a great help in troubleshooting knockout.js issues!

**Comment by wert2all** [comment]
@gamort is this issue still actual?

**Comment by gamort** [comment]
Thanks, I'll retest for the latest release and update

**Comment by veloraven** [comment]
@gamort if this issue is still actual please format it  according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
If it is not actual anymore please close it.

**Comment by andimov** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
