### ISSUE TITLE
Newsletter queue don't start, don't send emails, don't save the start time

### ISSUE THREAD

**Issue by kgvconsulting** [magento/magento2#4866]
v Magento 2.0.6

Newsletter Queue, after placing newsletter template to queue and select the start date and time, and press button save newsletter, the selected start time is changed and return by 4 hours:
![screenshot 2016-06-03 10 54 35](https://cloud.githubusercontent.com/assets/11282348/15782850/c2ce2276-2979-11e6-8662-6ce85c4d994e.png)
![screenshot 2016-06-03 10 54 51](https://cloud.githubusercontent.com/assets/11282348/15782851/c5133dd2-2979-11e6-8222-81772cf3e108.png)
![screenshot 2016-06-03 10 55 09](https://cloud.githubusercontent.com/assets/11282348/15782854/c807ad7a-2979-11e6-8925-18b25be6b21e.png)
![screenshot 2016-06-03 10 55 18](https://cloud.githubusercontent.com/assets/11282348/15782856/cb4178d6-2979-11e6-9290-5967471f3e41.png)

The Newsletter queue does not start to send even if I select time that is in the future so the start time return changes that magento is doing on its own don't affect the queue and place the start time in the past.

No errors are reported nor recorded any were in magento about issue with the newsletter queue, It just don't work

All other emails, from subscription confirmation, orders, reviews and any other email automatically send from magento application work without any issues

**Comment by oserediuk** [comment]
Hello! Please, use issue template to report the issue. Look here https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by jeredmilla** [comment]
Is there solution for this?
