### ISSUE TITLE
Javascript Bundling breaks custom role resource tick boxes

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#4875]
## Steps to reproduce
1. Install Magento 2.0.6 Community Edition
2. Stores > Configuration > Advanced: Developer > JavaScript Settings: Enable Javascript Bundling - set this to yes
3. Clear all caches, static files etc.
## Expected result
1. System > User Roles > Open Role > Role Resources > Resource Access: Custom - each resource should show a tick box next to it
## Actual result
1. System > User Roles > Open Role > Role Resources > Resource Access: Custom - all tick boxes are missing.

NOTE: I then changed the store view to apply Javascript Bundling to the frontend only, however the issue persisted. This leads me to believe that the Javascript Bundling setting was not applying to the frontend only, otherwise the admin issue should not have re-appeared.

![roles](https://cloud.githubusercontent.com/assets/19744729/15798656/4b786e56-2a83-11e6-9def-8a388cfb7cae.jpg)

**Comment by oserediuk** [comment]
Hello @atIOCrON ! I cannot reproduce this issue on my instance. Try to update your code and reproduce its again.

**Comment by southerncomputer** [comment]
I can confirm this happens when Nginx.conf is not properly parsing /static/ or .htaccess is missing from pub/static/ when using apache! Just spent a day working this out with nginx!

**Comment by southerncomputer** [comment]
Also with nginx and php 7.0.7 the opcache being enabled causes static.php to return randomly garbled .js files back! You can watch f12 developer mode when loading the pages to see the errors randomly appear about every other load - internal note to myself - this might cause many other javascript errors in production mode.

**Comment by southerncomputer** [comment]
Upgraded to 2.1.0-rc2 and this problem is gone, bundles0.js .. bundle5.js (5) are created without error!

**Comment by oserediuk** [comment]
Good news! Thank for the report!
