### ISSUE TITLE
Design configuration page keep loading

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#4878]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by antboiko** [comment]
Hi @kfaer , please provide more details to reproduce this issue.

Thanks,
Anton.

**Comment by kfaer** [comment]
This issue is because that a third party theme is installed, i do not think
it is magento issue.

Regards,

**Comment by antboiko** [comment]
@kfaer 

I'm closing the issue. Please feel free to reopen if you have additional questions.

Best,
Anton.

**Comment by kfaer** [comment]
Hi,

could you please help on issue
#4879
