### ISSUE TITLE
Visible on Catalog Pages on Storefront not changing with Visual Switch in attribute v 2.0.7

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#4879]
In attribute when select Visual Switch changing the status of the Visible on Catalog Pages on Storefront is not posiable.
installed version 2.0.7 
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by antboiko** [comment]
Hi @kfaer , thanks for reporting. Internal ticket MAGETWO-53929.

Best,
Anton.

**Comment by magento-engcom-team** [comment]
@kfaer, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
