### ISSUE TITLE
Searchable dropdown list for admin product pages

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#4880]
## Feature Request

I have about 100 values of same attribute and managing them is sometimes very difficult. 
This is my suggestions to make it easier.
## Steps to reproduce
1. Create lots of similar values for some attribute (dropdown or swatch).
2. Create new product and try to choose right value of an attribute for this product.
## Solution

Searchable dropdown list. 

This is a nice example:
http://semantic-ui.com/modules/dropdown.html
It has tiny flaw, search works just by first word (United St..., but not Sta...).
Anyway it would be very helpfull.
## Priority

Low

**Comment by antboiko** [comment]
Hello @RG-1 , thanks for your suggestion. We have internal ticket MAGETWO-50589 in our backlog to cover this improvement.

I'm closing the issue. Please feel free to reopen if you have additional questions.

Best,
Anton.
