### ISSUE TITLE
validate attribute values

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#4881]
## Steps to reproduce
1. Go to Stores > Product Attributes
2. Create new or edit any existing attribute (types: dropdown, swatches or multiple select)
3. Add few identical attribute values
## Expected result
1. Error - it should not allow to create identical attribute values for "admin"
## Actual result
1. No errors

**Comment by antboiko** [comment]
Hi @RG-1 , thanks for your inquiry. Could you please provide some specific use cases why attribute should not be saved if user added non-unique values to it?

Thanks,
Anton.

**Comment by RG-1** [comment]
Hello Anton, 

Dropdown list and swatches are used in configurable products and layered navigation, so values should be precise. Otherwise, it may create confusion and wrong assignment. When dropdown is used just to create additional information, then it doesn't matter much.

**Configurable products**
Creating Product Configurations [Products > Catalog > Add product or Edit] allow to select same values and generate simple products from attribute like this:
![red](https://cloud.githubusercontent.com/assets/17853402/15931806/7d7f14fc-2e59-11e6-8624-bd35c8d2119c.png)
![red2](https://cloud.githubusercontent.com/assets/17853402/15931888/cc4fcb94-2e59-11e6-9fef-a85243ddea9a.png)

It looks like this on front-end product page:
![red1](https://cloud.githubusercontent.com/assets/17853402/15931823/922b2e0e-2e59-11e6-92b2-e4140f02ebd4.png)

I tried to import products form csv file, similar to this:

| sku | product_type | additional_attributes | configurable_variations |
| --- | --- | --- | --- |
| s1 | simple | color=red |  |
| s2 | simple | color=black |  |
| s3 | simple | color=red |  |
| c | configurable |  | sku=s1,color=red&#124;sku=s2,color=black&#124;sku=s3,color=red |

Produsts are imported, but only s1 and s2 are used in configuration, s3 is skipped (without any error).

**Management** 
It is hard to manage attributes with a lot of values. Let's assume that we have about 100 values of a color attribute and there is a need to add 100 new colors. It is possible to check it manually, but it would not be the smart way.

Best

**Comment by antboiko** [comment]
Hi @RG-1 , sorry for the delayed response. I've created internal ticket MAGETWO-54780 to track this issue on our side.

Thanks,
Anton.

**Comment by andimov** [comment]
@RG-1 
This issue has been fixed and delivered to mainline.

**Comment by elenleonova** [comment]
The issue has been delivered to 2.1.3 and 2.0.11
