### ISSUE TITLE
Button Insert Image - only insert one image - Magento 2.1

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#4884]
Magento 2.1
![insertimage](https://cloud.githubusercontent.com/assets/7834473/15813777/e9038ca0-2beb-11e6-95a2-e1f688d4b16a.png)

**Comment by katmoon** [comment]
Hi @ 

Thank you for reporting the issue. It is reported as `MAGETWO-57181` internally.

Thanks,
Kateryna.

**Comment by russelllogozar** [comment]
@katmoon - Any update on MAGETWO-57181?  This appears to still be an issue in 2.1.4 CE and EE.

**Comment by slackerzz** [comment]
i've just opened a pull request to fix this issue. The fix is quite simple, open `/lib/web/mage/adminhtml/browser.js`, search for line 34 (in current develop branch line number is 54)

```if (this.modal) {```

inside function ```openDialog``` and change to

```if (this.modal && options !== undefined) {```

**Comment by veloraven** [comment]
Internal ticket for ver. 2.1 - MAGETWO-63824.
The issue was fixed and the fix will be available in one of the next releases.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67044

**Comment by magento-engcom-team** [comment]
@minhluan259 thank you for report. The issue already fixed in 2.2.0 release
