### ISSUE TITLE
How can i  add a new adapter for import functionality in m2?

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#4886]
I need to fetch products from a third party ERP's api, and import them in my m2 nstallation, i have used m2 api for that, bu it is too slow to import products in bulk, so i am thinking about m2's native import functionality with a different adapter which fetches the data from the REST api of the ERP and pass it to the import model

**Comment by NadiyaS** [comment]
Hi @Taral-Patoliya,
the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.  Feel free to create new issue if you think you have encountered a bug in Magento 2.
