### ISSUE TITLE
Status order comments wrong date

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#4887]
The comments in the history of a order are showing the current time.

There is a missing method in the model Magento\Sales\Model\Order\Status\History.
That existed in the Magento\Rma\Model\Rma\Status\History.
So i copied the method for the model Magento\Sales\Model\Order\Status\History.

**Comment by basselalaraaj** [comment]
Fixed in https://github.com/magento/magento2/pull/4888/commits/fbb407584171459641e1a563c610f96531214c9e

**Comment by NadiyaS** [comment]
Hi @basselalaraaj,
 please provide Magento version where you encountered this issue and do not forget to provide all steps to reproduce this bug. Develop branch does not have this issue, comments are displayed with correct time.

**Comment by basselalaraaj** [comment]
@NadiyaS I am using magento 2.0.5, i see that it has been fixed in the develop branch in the template instead of in the model.
I saw in the module Magento_Rma, that it has been fixed in the module, the same way as my pull request.

**Comment by meetvora69** [comment]
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 23

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 36

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 36

Parse error: parse error in C:\wamp\www\magento\index.php on line 36 
please solve my problem....

**Comment by NadiyaS** [comment]
@basselalaraaj , as this bug does not exist on the latest Magento version this issue will be closed. Also, please, close your PR.
@meetvora69 , if you have encountered a bug please create additional issue.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
Also be sure that you have correct PHP version, see [System requirements](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html)
