### ISSUE TITLE
Sample data installation error

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#4889]
## Steps to reproduce
1. Install EasyPHP-Devserver-16.1.1-setup.exe from http://www.easyphp.org/.
2. Follow the instructions on https://blog.amasty.com/how-to-install-magento-2-php7-localhost/ (I have a Windows 7 32-bit system, so I downloaded the Magento-CE-2.0.7+sample_data-2016-05-24-01-28-33.tar.bz2 file).
3. Go to http://127.0.0.1:8888/magento2/ to start the setup process.
## Expected result
1. Success with no errors.
## Actual result
1. Success with the following error:

_Something went wrong while installing sample data. Please check var/log/system.log for details. You can retry installing the data now or just start using Magento._

The `var/log/system.log` contains the following error:

```
[2016-06-06 10:28:33] main.ERROR: Sample Data error: Error in data structure: entity values are mixed [] []
[2016-06-06 10:28:39] main.ERROR: Sample Data error: Validation is failed. [] []
```

**Comment by mslabko** [comment]
Hello @thdoan ,

This issue already fixed in develop branch, could you please test on 2.1-rc branch?

**Comment by lussari** [comment]
Same error here:
1. Install EasyPHP-Devserver-16.1.1-setup.exe from http://www.easyphp.org/.
2. Follow the instructions on https://blog.amasty.com/how-to-install-magento-2-php7-localhost/ ( Magento-CE-2.1.0_sample_data-2016-06-23-02-32-34.zip )
3. Start the setup process.

```
main.ERROR: Sample Data error: Error in data structure: entity values are mixed [] []
main.ERROR: Sample Data error: Validation is failed. [] []
```

**Comment by thdoan** [comment]
@mslabko I cannot update at the moment, but it seems @lussari is using 2.1 and facing the same issue.

**Comment by andimov** [comment]
@thdoan 
Thank you for reporting! Please check the solution from
https://github.com/magento/magento2/issues/2400#issuecomment-162648646

**Comment by sIiiS** [comment]
Same issue with Magento 2.1.1 !

**Comment by oshmyheliuk** [comment]
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).
