### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by meetvora69** [magento/magento2#4890]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by meetvora69** [comment]
i have run magento but some issue like
Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 23

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 36

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in C:\wamp\www\magento\index.php on line 36

Parse error: parse error in C:\wamp\www\magento\index.php on line 36
so please solve my error fast...

**Comment by NadiyaS** [comment]
@meetvora69 , 
please be careful when you create issue and provide concrete steps to reproduce, not leave them from sample. 
Also remember that the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
Also be sure that you have correct PHP version, see [System requirements](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html)
