### ISSUE TITLE
System tab is not working in admin panel

### ISSUE THREAD

**Issue by skandamallapa** [magento/magento2#4892]
## Steps to reproduce
1. Install Magento on XAMPP(Local server)
   2.Login to admin panel.
   3.Click on System Tab, it doesn't show you any option.

Why System Tab is not working..?

**Comment by meetvora69** [comment]
but i have install on wamp..this is possible?

**Comment by skandamallapa** [comment]
Which version did you installed...?
I have installed magento 2.0.

In admin panel,only dashbord is working.
All other menu's like sales,products,customer,marketing,content...etc are not opening....

**Comment by cpartica** [comment]
what version of XAMPP did you installed? or what version of PHP do you use? note that Magento 2.0 only supports versions upper than 5.5.x and 2.1 supports php 7.x
You might have an exception there somewhere if you look in var/log/debug.log

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
