### ISSUE TITLE
Magento 2.0 API Issue in Attribute Set

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#4894]
## Steps to reproduce

GET /V1/products/attribute-sets/{attributeSetId}/attributes
## Expected result

Return all the attributes related to that attribute set
## Actual result

Error:
{
“message”: “Internal Error. Details are available in Magento log file. Report ID: webapi-574ed41d7eb6e”
}
![restapi](https://cloud.githubusercontent.com/assets/17869716/15821169/bbec73f6-2c0b-11e6-916c-1b8e8ea92067.PNG)

**Comment by vzabaznov** [comment]
Hi @routbiplab can you please show what are in webapi-574ed41d7eb6e log?

**Comment by routbiplab** [comment]
I found this in the log file : 
main.CRITICAL: exception 'ReflectionException' with message 'Report ID: webapi-574ed41d7eb6e ; Message: Class  does not exist' in -vendor/magento/framework/Webapi/ErrorProcessor.php:194

Stack trace:
#0 -vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(ReflectionException))
#1 -vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(ReflectionException))
#2 -var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 -vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 -vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 -index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by routbiplab** [comment]
Hey I got one solution and it worked for me.
Go to
/vendor/magento/module-eav/Model/Entity/Attribute/ AbstractAttribute.php
Search for _getDefaultSourceModel() and Just comment/remove the original code and replace it with:
return $this->getEntityType()->getEntity()->getDefaultAttributeSourceModel();

**Comment by oleg-onufer** [comment]
Hi @routbiplab.
I could not reproduce the issue. Can you check your problem on the latest version of Magento 2?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
