### ISSUE TITLE
2.1.0-rc1 - dropdown attribute required even when selected

### ISSUE THREAD

**Issue by 5zymon** [magento/magento2#4899]
1. I've created new attribute with type of "dropdown".
2. I've assigned this attribute to a configurable product and created simple product variations with it. 
3. I am not able to put product into the cart. Swatch attribute type works, only dropdown doesn't work, even when value is selected. 

![ladies_size_product_attributes_attributes_stores_magento_admin_-_2016-06-06_14 33 35](https://cloud.githubusercontent.com/assets/3308234/15822113/2a5acdc8-2bf4-11e6-9e3a-ed516673d331.png)
![stellar_solar_jacket_-_2016-06-06_14 34 56](https://cloud.githubusercontent.com/assets/3308234/15822112/2a579f04-2bf4-11e6-9957-8050ed8a9e4e.png)

**Comment by antboiko** [comment]
Hi @5zymon , thanks for reporting. We've created internal ticket MAGETWO-54043 to investigate this issue.

Best,
Anton.

**Comment by KrystynaKabannyk** [comment]
Hello @5zymon, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
