### ISSUE TITLE
Configurable Product : display require field message when we click on save.

### ISSUE THREAD

**Issue by parthviroja** [magento/magento2#4908]
1 : i have create configured product.
2 : create custom attribute "size" , type : text-switcher , ex: [ 10,20,30,110ml,200ml,300ml ]
3 : now i have added 1 virtual product with quantity and weight and select size.
4 : default "Size" field is display in configures product , when click on [ save ] display message

![demo](https://cloud.githubusercontent.com/assets/9655554/15846161/3a571c00-2c98-11e6-90b2-e8d8766f614c.png)

5 : virtual product of this configure product working perfect.

**Comment by antboiko** [comment]
Hi @parthviroja , thanks for you inquiry.

What Magento version you are using?

Could you please provide more detailed steps so we would be able to try reproducing your issue? Especially:  
- Did you use your custom attribute "size" for creating Configurable product?
- "Size" attribute has option "Values Required = Yes"?
- Was it added to the same Attribute Set you have chosen for your Configurable Product?

Thanks,
Anton.

**Comment by parthviroja** [comment]
I have using Magento2 CE 2.0.7 without sample data.

> i have create new attribute from : `store\attributes\product`
> 
> create custom attribute set : `store\attributes\attribute set`
> 
> create simple product : `products\catalog -> Simple Product`
> 
> i can see [ size ] attribute visible and enable : now i have select anyone option from dropdown
> 
> now i have add 3 more product using : `Configurations -> Create Configuration` [ from bottom tab ]
> 
> select [ size ] attribute and set weight also.
> 
> now all product visible and working perfect on product listing and detail page.
> 
> now when i open configure product than this issue happen  [ size ] dropdown is disable, when i am click on save , this message display

**Comment by antboiko** [comment]
Hi @parthviroja , thanks for the details.

I cannot reproduce the issue on develop branch. The configurable product has been saved without error message. 

The fix is already in develop branch and will be available in 2.1 release.

I'm closing the issue. Feel free to reopen it if needed.

Best,
Anton.

**Comment by parthviroja** [comment]
Its ok, and thanks @antboiko
