### ISSUE TITLE
Multiple invoices are getting generated for a single order using REST Api

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#4909]
## Steps to reproduce
1. Install Magento 2.
2. Create Order
3. Create invoice for that order using REST Api
## Expected result
1. One invoice for that order
2. ...
## Actual result
1. Multiple invoices are being created.

**Comment by cpartica** [comment]
Based on this payload, it only creates one invoice, can you tell us what's your payload?

> {
>   "entity": {
>     "orderId": 1,
>     "storeId": 1,
>     "billingAddressId": 1,
>     "shippingAddressId": 1,
>     "totalQty": "1",
>     "items": [
>       {
>         "orderItemId": 1,
>         "productId": 6,
>         "sku": "simple_product_with_special_price_and_category1638941617",
>         "name": "Simple with Special Price 1$ off 1638941617",
>         "qty": "1",
>         "price": "9.00".
>         "row_total": "9.00"
>       }
>     ]
>   }
> }

**Comment by arijit-de93** [comment]
@cpartica Thanks for looking into the issue.

I am getting the same error using the below payload.
Below is the payload, I am using:
{
"entity": {
"orderId": 1,
"storeId": 1,
"totalQty": "1",
"items": [
{
"orderItemId": 1,
"sku": "Test01",
"qty": "1",
"price": "122.00",
"row_total":"122.00"
}
]
}
}
I am not using billing address id and shipping address id and also product id and sku as they are not mandatory fields.

Any help will be appreciated.

Thanks.

**Comment by routbiplab** [comment]
I really had to brainstorm about it and later came up by creating a new custom module that will help to create invoice using api that will resolve your issue.

Considering You know how to create a new module.Start by creating a new module: Lets say we have  a namespace: "ABC" and module "Customapi" 

Inside ABC/Customapi/etc : create a webapi.xml and do the following 

```
   <?xml version="1.0"?>
 <!--
 /**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
 <routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Webapi:etc/webapi.xsd">
 <route url="/V1/customInvoices" method="POST">
    <service class="ABC\Customapi\Api\InvoiceRepositoryInterface" method="save"/>
    <resources>
         <resource ref="Magento_Sales::sales" />
    </resources>
   </route>

 <route url="/V1/customInvoices/:id" method="GET">
    <service class="ABC\Customapi\Api\InvoiceRepositoryInterface" method="get"/>
    <resources>
         <resource ref="Magento_Sales::sales" />
    </resources>
 </route>

 </routes>
```

This is where you declare your routes.

Now we need to declare the interface and its corresponding class containing the repository where we will be defining our methods.

So inside ABC/Customapi/etc : create a di.xml and do the following 

```
<?xml version="1.0"?>
<!--
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
   <preference for="ABC\Customapi\Api\InvoiceRepositoryInterface" type="ABC\Customapi\Model\Order\InvoiceRepository"/>

 </config>
```

Now we will be declaring the interface for our api. Under ABC/Customapi/Api : create InvoiceRepositoryInterface.php

```
<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
namespace ABC\Customapi\Api;

/**
* Order repository interface.
*
* An order is a document that a web store issues to a customer. Magento     generates a sales order that lists the product
* items, billing and shipping addresses, and shipping and payment  methods. A corresponding external document, known as
 * a purchase order, is emailed to the customer.
 * @api
  */
 interface InvoiceRepositoryInterface
 { 
/**
 * Loads a specified invoice.
 *
 * @param int $id The invoice ID.
 * @return \Magento\Sales\Api\Data\InvoiceInterface Invoice interface.
 */
public function get($id);


/**
 * Performs persist operations for a specified invoice.
 *
 * @param \Magento\Sales\Api\Data\InvoiceInterface $entity The invoice.
 * @return \Magento\Sales\Api\Data\InvoiceInterface Invoice interface.
 */
 public function save(\Magento\Sales\Api\Data\InvoiceInterface $entity);
 }
```

All required methods for the API are called in this file which are defined in the InvoiceRepository.php file under ABC\Customapi\Model\Order.

So our InvoiceRepository.php will have all the methods that will be called accordingly, based on the api route.

```
 public function get($id)
{
    if (!$id) {
        throw new \Magento\Framework\Exception\InputException(__('ID required'));
    }
    if (!isset($this->registry[$id])) {
        $entity = $this->_objectManager->get('Magento\Sales\Model\Order\Invoice')->load($id);
        if (!$entity->getEntityId()) {
            throw new NoSuchEntityException(__('Requested entity doesn\'t exist'));
        }
        $this->registry[$id] = $entity;
    }
    return $this->registry[$id];
}

 public function save(\Magento\Sales\Api\Data\InvoiceInterface $entity)

{

    $invoiceItems=array();

    foreach ($entity->getItems() as $val){
        $quantity=$val->getQty();
        $orderItemId=$val->getOrderItemId();
        $invoiceItems[$orderItemId]=$quantity;
    }       
    $orderId=$entity->getOrderId();

    $order = $this->_objectManager->get('Magento\Sales\Model\Order')->load($orderId);


    if (!$order->getId()) {
        throw new \Magento\Framework\Exception\LocalizedException(__('The order no longer exists.'));
    }

    if (!$order->canInvoice()) {
        throw new \Magento\Framework\Exception\LocalizedException(
                __('The order does not allow an invoice to be created.')
        );
    }

    $invoice = $this->invoiceService->prepareInvoice($order, $invoiceItems);

    if (!$invoice) {
        throw new \Magento\Framework\Exception\LocalizedException(__('We can\'t save the invoice right now.'));
    }

    if (!$invoice->getTotalQty()) {
        throw new \Magento\Framework\Exception\LocalizedException(
                __('You can\'t create an invoice without products.')
        );
    }


     $invoice->register();
    $invoice->getOrder()->setIsInProcess(true);

    $transactionSave = $this->_objectManager->create(
            'Magento\Framework\DB\Transaction'
    )->addObject(
            $invoice
    )->addObject(
            $invoice->getOrder()
    );

    $transactionSave->save();

    $incrementId = $invoice->getIncrementId();

    $invoiceId = $invoice->getEntityId();

     return $this->get($invoiceId);

}
```

Hope this will work for you as well. Do comment if you have any query

**Comment by veloraven** [comment]
@arijit-insync thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by LovelySetia** [comment]
> Based on this payload, it only creates one invoice, can you tell us what's your payload?
> 
> > {
> > "entity": {
> > "orderId": 1,
> > "storeId": 1,
> > "billingAddressId": 1,
> > "shippingAddressId": 1,
> > "totalQty": "1",
> > "items": [
> > {
> > "orderItemId": 1,
> > "productId": 6,
> > "sku": "simple_product_with_special_price_and_category1638941617",
> > "name": "Simple with Special Price 1$ off 1638941617",
> > "qty": "1",
> > "price": "9.00".
> > "row_total": "9.00"
> > }
> > ]
> > }
> > }

 routbiplab What arguments is passed in body for V1/customapi.

**Comment by LovelySetia** [comment]
Suppose i have 2 items in order,one is simple and other is bundle.When i call POST V1/customInvoices api,and pass {"entity": {   "orderId": "325",   "totalQty": "1","items": [ {"order_item_id":1199, "qty": 1}],  "comments": [], "extensionAttributes": {}  }}.Here items": [ {"order_item_id":1199, "qty": 1} this is simple product item id.This api is give response as detail about simple product and also parent_item details of bundle product.What is issue in this api,please help me @routbiplab .
