### ISSUE TITLE
Product Attribute empty option values

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#4910]
## Steps to reproduce
1. Creating New Product in Magento 2.
2. Can't able to set the empty value for attributes while saving the product.
## Expected result
1. Example: No need to choose the color attribute for the product.
## Actual result
1. [Example] For color, It will take the default value which is stored while creating the attribute values.
2. Please have a look at the screenshot
   ![color product attributes attributes stores magento admin](https://cloud.githubusercontent.com/assets/16077771/15848413/7ce45850-2caa-11e6-8c66-4ae14640e114.png)
   ![new product products inventory products magento admin](https://cloud.githubusercontent.com/assets/16077771/15848414/7d107066-2caa-11e6-8126-bb849a741de3.png)

**Comment by mslabko** [comment]
Hi @sasilinux ,
Thank you for reporting! We have already similar issue in our backlog: MAGETWO-50123

**Comment by sasilinux** [comment]
when checking this bug, we believe the problem is in styles.css. If we remove this it works properly. Why you write this in css.
option:empty {
    display: none;
}

**Comment by mslabko** [comment]
According to screenshot you are using 2.0.1 version.  In  2.1 last mentioned issue will be fixed, so please follow up marketing update.

**Comment by elenleonova** [comment]
This issue has been fixed in 2.2.0

**Comment by Ctucker9233** [comment]
@elenleonova Is this issue going to be backported?

**Comment by adeelmughal4u** [comment]
Any fix, I am facing same issue on Magento EE ver. 2.3.5-p2

Field type is Text - custom attribute not saving empty, and always 0
