### ISSUE TITLE
Magento template hints 'removes' part of Luma theme? [Magento 2+]

### ISSUE THREAD

**Issue by AngelsDustz** [magento/magento2#4913]
## Steps to reproduce
1. Install Magento 2.0.0
2. Select the Luma theme
3. Turn on template hints
## Expected result
1. The theme with all of its elements being displayed with template hints
## Actual result
1. Some elements dissapear (? They exist, but are not find-able/shown?)
2. See [img](http://i.imgur.com/V8do2ex.png), this is the normal Luma theme.
3. When you turn on template hints, you see the header missing data. (See [img](http://i.imgur.com/BaVZc6a.png))

In the source code you can even see a part of the code missing? (See [img](http://i.imgur.com/cgbjNva.png))

For unkown reasons the find tool finds 'check in' twice but only shows once in code?

**Comment by zanilee** [comment]
Hi, @AngelsDustz!

Can't reproduce this issue neither on Magento 2.0.0, nor on the latest Magento2. 
Have you tried to flush all caches?

**Comment by AngelsDustz** [comment]
It has been flushed, cleared and even rm -rf'd multiple times to no avail.
From using the admin panel to CLI to straight up *nix commands.

**Comment by AngelsDustz** [comment]
Also happens on the latest version 2.1.0-rc2
PhP Version: 7.0.6
Apache2 Version: 2.4.18

Maby a better explanation of the issue:
1. Make a new page.
2. Select 'Empty' layout.
3. Select theme as Luma.

Then just open 2 pages 1 with path hinting and 1 without.
And boom content is gone.

**Comment by lorenaramonda** [comment]
I agree. In my case, for example, the main menu navigation is not shown to screen but available in source code.
For this particular case, it depends on a display none on the navigation:

<img width="1427" alt="schermata 2017-04-28 alle 11 10 30" src="https://cloud.githubusercontent.com/assets/4409084/25522742/548a7b14-2c04-11e7-92b6-3df92b0db511.png">

**Comment by magento-engcom-team** [comment]
@AngelsDustz, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
