### ISSUE TITLE
Apache error AH01797 with trow to white screen server error 500

### ISSUE THREAD

**Issue by kgvconsulting** [magento/magento2#4914]
I'm getting the following Apache error from Magento configuration with trowing the Magento application to white screen server error 500

"[Mon Jun 06 22:20:40.350560 2016] [access_compat:error] [pid 11470] [client xxx.xxx.xxx.xxx:36636] AH01797: client denied by server configuration: /home/xxxxxx/public_html/app/etc/config.php"

As per Apache documentation, this error is related to the new Apache version 2.4 and the mixing of old and new directives used for htaccess file

"Mixing old directives like Order, Allow or Deny with new ones like Require is technically possible but discouraged. mod_access_compat was created to support configurations containing only old directives to facilitate the 2.4 upgrade. Please check the examples below to get a better idea about issues that might arise."

http://httpd.apache.org/docs/2.4/upgrading.html

Does Magento have a version of htaccess file that comply with the new directives for Apache v 2.4? How to fix that issue?

**Comment by stamster** [comment]
Have you tried to remove deprecated syntax? It's not that hard.

Otherwise just use Nginx, even though Magento is designed in a very wrong way from ground up to actually respect your web server.

**Comment by kgvconsulting** [comment]
@stamster 

I can remove the deprecated syntax, however with the way Magento "work" better verify first, don't want to end up with breaking down because of the syntax change. Do you had experience with this? Does Magento work with the new Apache directives?

**Comment by stamster** [comment]
I don't know since I only use Nginx in both dev and prod environments, and for problems you're having that's why I'd recommend you to try with Nginx.
P.S. Magento2 ships with default nginx configuration which has syntax bug, so you need to fix this manually by closing server block with an ending bracket `}`

I had similar issues with Apache in the past though, and for 2.4 solution would be as simple to remove each deprecated directive and to use only new syntax.

**Comment by kgvconsulting** [comment]
@stamster I did think the same, but found this about Magento htaccess stoping to work if the Apache directives are upgraded - #1491

So decided to double check first, as you say better if changes are needed to be done once I may move to  Nginx instead to spend days fixing bugs ....
