### ISSUE TITLE
Order emails are broken when inline translations are turned on

### ISSUE THREAD

**Issue by MidnightDesign** [magento/magento2#4917]
## Steps to reproduce
1. Enable inline translations in admin
2. Order something in the frontend
## Expected result

I get a confirmation email with my order data.
## Actual result

I get an email with placeholders (`{{var ...}}`, etc.).

**Comment by choukalos** [comment]
Tracking internally as MAGETWO-54108

**Comment by KrystynaKabannyk** [comment]
Hello @MidnightDesign, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
