### ISSUE TITLE
PayPal Express checkout review page UI needs improvement

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#4922]
The PayPal Express review page has typically always been lacking in its UI. Here is a screenshot of a live M2 review page with some suggestions for improvement (note: this theme is based on the Magento/blank theme):

![19-31-15 review order 21st century task seating-6tdv1](https://cloud.githubusercontent.com/assets/129031/15879106/959fb542-2ce6-11e6-86a5-ca8bc4f47075.png)

As a point of reference, here is a Magento 1 site that has a better UI, in my opinion:

![19-30-04 smocked auctions-2bbx6](https://cloud.githubusercontent.com/assets/129031/15879075/4bbb0dbe-2ce6-11e6-90e1-2556027f6bb7.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/PayPal-Express-checkout-review-page-UI-needs-improvement/idi-p/45125).
