### ISSUE TITLE
Inlinetranslation breaks frontend submits

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4925]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to backend
3. Stores -> Configuration -> Advanced -> developer
4. Translate inline -> enabled for storefront -> yes
## Expected result
1. Frontend account login works.
## Actual result
1. Error message appears on route `https://shopdomain.abc/customer/account/loginPost/`
2. Error : `Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/vendor/magento/module-captcha/Observer/CheckUserLoginObserver.php on line 80`

Reason:

Inline translation causes html input field to be corrupted, so the post request failed `CheckUserLoginObserver.php`

_HTML EXAMPLE_

```
<input data-translate="[{" shown":"passwort","translated":"passwort","original":"password","location":"tag="" attribute="" (alt,="" title,="" etc.)"}]"name="login[password]" type="password" autocomplete="off" class="input-text" id="pass" title="Passwort" data-validate="{required:true, 'validate-password':true}" aria-required="true">
```

**Comment by mslabko** [comment]
Hi @xhallix ,
Thank you for reporting! Internal ticket for this issue: MAGETWO-54051

**Comment by okorshenko** [comment]
@xhallix Thank you for reporting the issue. MAGETWO-54051 merged to develop branch
