### ISSUE TITLE
Mass-Selection checkbox not functioning properly

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#4928]
I realized that the mass-selection checkbox is disfunctional. Take for instance the Notification screen:

![selectall](https://cloud.githubusercontent.com/assets/9464641/15893417/e81fdc9a-2d7f-11e6-9bd9-75488d616402.gif)
## Steps to reproduce
1. Install Magento 2.0.7.
2. Open any screen in the admin with a mass-selection header and click the arrow / box
## Expected result
1. See the dropdown list of options (on clicking the arrow)
2. Selecting all elements (on clicking in the empty checkbox)
## Actual result
1. The checkbox(arrow) keeps glitching, half-animating
2. If you click in the top-left corner of the checkbox it does open the menu
3. If you check any individual item, the mass-selection box gets updated with a dash, and it's easier clickable then

I've looked at the HTML of the box and how it changes on actions, and I saw that sometimes the complete `class="action-select-multiselect"` was missing, after you select anything (the mass-selector or an individual item) the class does get added. However if the class exists or not, it doesn't seem to change the behaviour.

**Comment by southerncomputer** [comment]
What do you see in (f12) developer mode debug/console errors?

**Comment by Asitis** [comment]
Nothing, actually. I've checked the /log/ folder and the console, but none relating to this.
Edit: I've since updated to 2.1.0rc2 and haven't been able to reproduce the issue

**Comment by palamar** [comment]
@Asitis could you please, provide additional information about environment:
- browser and it version
- operation system
- list of plugins installed to browser

**Comment by Asitis** [comment]
As I said before I haven't been able to reproduce the problem. Just checked again the 2.0.7 installation in Chrome51 without plugins on OSX10.11, and no faults to be seen.

**Comment by andimov** [comment]
@Asitis
Thank you for reporting!
So, this issue is not reproduced for now with the same steps and environment?
Is it reasonable to close a ticket as 'non-reproduced'?

**Comment by Asitis** [comment]
I think it is now :) a lot has changed since I opened it. As I said before; haven't been able to reproduce it since the updates, so it's either fixed or not a problem anymore.
