### ISSUE TITLE
Installation is incomplete at 73%

### ISSUE THREAD

**Issue by jatin222** [magento/magento2#4929]
I am trying to install brand new magento
But got error in console log

Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':

Module 'Magento_Rule':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':

Module 'Magento_Widget':

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Quote':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_SalesSequence':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_Email':

Module 'Magento_User':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogInventory':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Authorizenet':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_Paypal':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_NewRelicReporting':

Module 'Magento_OfflineShipping':

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':

Module 'Magento_CatalogSearch':

Module 'Magento_Integration':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_Captcha':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':

Module 'Magento_Rule':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Quote':
Running schema recurring...

Module 'Magento_CmsUrlRewrite':

Module 'Magento_SalesSequence':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_Email':

Module 'Magento_User':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Authorizenet':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Magento_Paypal':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_NewRelicReporting':

Module 'Magento_OfflineShipping':

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':

Module 'Magento_CatalogSearch':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_Captcha':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':
Running schema recurring...

Installing user configuration...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[collections] => 1
[reflection] => 1
[db_ddl] => 1
[eav] => 1
[customer_notification] => 1
[full_page] => 1
[config_integration] => 1
[config_integration_api] => 1
[translate] => 1
[config_webservice] => 1
)

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':

Module 'Magento_CatalogImportExport':

Module 'Magento_Config':

Module 'Magento_Rule':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':

Module 'Magento_Widget':

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Quote':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_SalesSequence':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_Email':

Module 'Magento_User':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogInventory':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Authorizenet':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_Paypal':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_NewRelicReporting':

Module 'Magento_OfflineShipping':

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':

Module 'Magento_CatalogSearch':

Module 'Magento_Integration':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_Captcha':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Installing data...
[ERROR] PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'base_weee_tax_applied_row_amnt' in /var/www/html/magecom/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/magecom/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/html/magecom/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/html/magecom/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/html/magecom/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/html/magecom/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `qu...', Array)
#5 /var/www/html/magecom/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(452): Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `qu...', Array)
#6 /var/www/html/magecom/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(507): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('ALTER TABLE `qu...', Array)
#7 /var/www/html/magecom/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(370): Magento\Framework\DB\Adapter\Pdo\Mysql->query('ALTER TABLE `qu...')
#8 /var/www/html/magecom/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(879): Magento\Framework\DB\Adapter\Pdo\Mysql->rawQuery('ALTER TABLE `qu...')
#9 /var/www/html/magecom/app/code/Magento/Quote/Setup/QuoteSetup.php(116): Magento\Framework\DB\Adapter\Pdo\Mysql->addColumn('quote_item', 'base_weee_tax_a...', 'decimal(12,4) N...')
#10 /var/www/html/magecom/app/code/Magento/Quote/Setup/QuoteSetup.php(93): Magento\Quote\Setup\QuoteSetup->_addFlatAttribute('quote_item', 'base_weee_tax_a...', Array)
#11 /var/www/html/magecom/app/code/Magento/Weee/Setup/InstallData.php(63): Magento\Quote\Setup\QuoteSetup->addAttribute('quote_item', 'base_weee_tax_a...', Array)
#12 /var/www/html/magecom/setup/src/Magento/Setup/Model/Installer.php(843): Magento\Weee\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#13 /var/www/html/magecom/setup/src/Magento/Setup/Model/Installer.php(795): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#14 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#15 /var/www/html/magecom/setup/src/Magento/Setup/Model/Installer.php(344): call_user_func_array(Array, Array)
#16 /var/www/html/magecom/setup/src/Magento/Setup/Controller/Install.php(107): Magento\Setup\Model\Installer->install(Array)
#17 /var/www/html/magecom/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#18 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/html/magecom/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/magecom/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/html/magecom/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/html/magecom/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/html/magecom/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /var/www/html/magecom/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/html/magecom/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /var/www/html/magecom/setup/index.php(31): Zend\Mvc\Application->run()
#28 {main}

**Comment by oserediuk** [comment]
Hello @jatin222 ! Looks like you tried to install to non-empty DB. Try to create one more new empty DB and start install again

**Comment by jldmn** [comment]
Did you set the right options in your php.ini?

I needed the following options for installation:

```
max_execution_time = 180000
memory_limit = 2G
always_populate_raw_post_data = -1
asp_tags = off
```

And always start with a clean DB when installation failed.

**Comment by andimov** [comment]
@jldmn 
Please, check this troubleshoot doc:
 [Setup Wizard installation stops at about 70%](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_70pct.html) and let me know if your problem been solved.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by hubaig** [comment]
Hi,

My magento 2 install keeps on getting stuck at 73%. I have the following limits set.

    php_value memory_limit 2048M
    php_value max_execution_time 18000

This is on a dedicated server with 24 gb ram and 24 cpus.

Not sure why this is happening.

Any help should be apprecaited.

**Comment by SouthRibbleTech** [comment]
I am getting the same problem.

Installation stops at 73%

12GB RAM
Dedicated Server
Software Raid 6 4 x 1.5TB Disks
Debian 8, Apache2, PHP5.6, MySQL 5.7

PHP Modified as above.

Not funny anymore, I have sat here now 3 times each time for 10 minutes only for it to crash.

**Comment by hubaig** [comment]
If you read above, I had the same problem. For me it turned out to be file permission problems. Make sure your permissions are set properly.

**Comment by SouthRibbleTech** [comment]
@hubaig I can't see anything above relating to permissions. Can you be more specific, or post a link to the permissions issue. Thanks

**Comment by bentalexanderhaase** [comment]
Same issue here.

`PHP 7.0.13-0ubuntu0.16.04.1`
`Magento-CE-2.1.4`
`Composer version 1.3.2`
`mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

![image](https://cloud.githubusercontent.com/assets/5788982/22857736/0b2a3868-f0ab-11e6-9656-fad8544af42d.png)

**Comment by hubaig** [comment]
After some struggle with this I figured out that it was due to my permissions on the files/directories. I fixed the permissions and it fixed the problem. Refer to your server logs and you will see the exact error that is causing this.

**Comment by bentalexanderhaase** [comment]
In my case, the solution was raising the limits in `/etc/php/7.0/fpm/php.ini` (I am using php7.0 from [this ppa](https://launchpad.net/~ondrej/+archive/ubuntu/php)):

```
[...]
max_execution_time = 600
max_input_time = 600
memory_limit = 768M
[...]
```

After saving the file, `service php7.0-fpm restart`

Made the installer go through slow, but smooth!

**Comment by EmmanuelBeziat** [comment]
Here’s the problem I had

> [Fri Apr 21 14:28:35 2017] [error] [client ::1] FastCGI: incomplete headers (0 bytes) received from server "/Applications/MAMP/fcgi-bin/php7.0.8.fcgi", referer: http://magento.idem/setup/

There’s really too much trouble installing Magento. You shouldn’t have to do special config tricks to be able to install a CMS.

**Comment by paginasweb** [comment]
im on Magento 2.2.6, same issue centos 7 php 7.1 WHM

![image](https://user-images.githubusercontent.com/2107317/47129244-24238f80-d25a-11e8-94b7-88feb903dd0a.png)
