### ISSUE TITLE
Minify as standart library.

### ISSUE THREAD

**Issue by SKovbel** [magento/magento2#493]
https://code.google.com/p/minify/

What do you think about adding Minify as standard library?
It is alive project with very powerful functionality for minify HTML, Css, JavaScript
Has BSD license.

**Comment by pboisvert** [comment]
Olena--can you have the team investigate this suggestion and file a ticket if desired or answer and close if not desirable.

**Comment by tkacheva** [comment]
@vkorotun could you look into it?

**Comment by vkorotun** [comment]
Sure, we have a couple other related issues here for awhile. The internal ticket is in Front-end development team backlog and will start execution pretty soon. 
"Minify" library is in the middle of our sight, so far, but as alternative solution we are looking also for the option to switch to NodeJS tools for the purpose of minification of static assets. I still believe, PHP libraries will never get to  far reaches as NodeJS front-end development tools just today is.

**Comment by tkacheva** [comment]
@SKovbel does this answer your question?

**Comment by MomotenkoNatalia** [comment]
@SKovbel 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
