### ISSUE TITLE
Avoid explicitly putting .htaccess and Grunt theme config in place

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#4930]
The following two files (at least) are put in place by the Composer install process, and therefore on each environment where an M2 site is deployed and the install run, any site-specific modifications are overwritten with a vanilla version of the file:
- pub/.htaccess
- dev/tools/grunt/configs/themes.js

However, both of these files are likely to need legitimate site-specific modifications (such as site-specific rewrite rules, or the addition of other themes to the Grunt config), and so it's undesirable for them to be overwritten during Composer install.  

These files should likely be replaced with versions suffixed with ".sample", and the process of putting the real version in place should be part of a site setup.

**Comment by hostep** [comment]
There were already some similar tickets:
- https://github.com/magento/magento2/pull/1982
- https://github.com/magento/magento2/issues/4697
- https://github.com/magento/magento2/issues/4823

Although the .htaccess file wasn't mentioned in those.

The problem I see with the .htaccess file, is that this is a file which is actually used in a production environment (in contrary to those other files) and if Magento fixes a security hole somewhere and needs to add some lines to the .htaccess to prevent this security issue, you might miss it when upgrading.

If you modify the .htaccess file yourself, you should definitely put it into your version control system, and upon upgrade you'll notice it has changed that file, so you should check it out and manually figure out what to do with the changes.

**Comment by anton-huz** [comment]
Just a notice: internal ticket MAGETWO-55345 has been created.

**Comment by anton-huz** [comment]
The issue with `theme.js` is solved. See [#1981](https://github.com/magento/magento2/pull/1982#issuecomment-244759040) for details.
The issue about `.htaccess` is a topic of another investigation. I'm closing in flavor of #6419.
