### ISSUE TITLE
"/rest/default/schema" or "/rest/schema" ? (2.1.0 RC2)

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#4931]
Hello,

[devdocs](http://devdocs.magento.com/guides/v2.0/rest/generate-local.html):

```
http://<magento_host>/rest/default/schema
```

but for 2.1.0 RC2 this address returns:

```
<response>
<message>Request does not match any route.</message>
<trace/>
</response>
```

Right address for schema is `http://<magento_host>/rest/schema`.

Please, change docs or code.

Thanks.

**Comment by keharper** [comment]
Both paths are working on our internal builds.

**Comment by mslabko** [comment]
Hi @flancer64 ,
It's working on 2.1.0 rc-2. "default" means "Store View code"
Please sure, that you still have Store View with "default" code.  This Store View exists by default in Magento instance.

**Comment by flancer64** [comment]
Oh! Thanks, this is the reason! I have no "default" store/storeView in my development configuration.
