### ISSUE TITLE
Template path hints doesn't show the surrounding templates?

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#4932]
I'm using magento 2.0.7.

It looks like the template path hints only show paths to smaller templates on a page. Not the surrounding ones. For example blank seems to use not a single template file. Instead it seems to be based on vendor/magento/module-theme. And in there seems to be the most top remplate root.phtml. How would I implement that template into my theme directory? I tried several paths but it seems to not be taken. I'm in dev mode.

Besides, I want to build my theme on twitter bootstrap. Would I run in troubles when I try to do it with templates only or would it be practically needed to use design files? I'm wondering what the most work would be. It seems there are a ALOT of designfiles. So building from scratch would mean building all those from scratch too. But adjusting each page to bootstrap would probably mean a lot of work too. Any advice?

Thanks!

**Comment by cpartica** [comment]
So there is a how to build your theme in M2 with twitter bootstrap on stack exchange
You can consult it at [this link](http://magento.stackexchange.com/questions/104461/how-to-develop-theme-using-twitter-bootstrap-in-magento-2)
You will have to do code on each block though, because each block will play it's part on the construction of the page

I suggest enabling the block names from the System -> Configuration -> Developer -> Debug  to show on page what you have to modify

**Comment by Onkovat** [comment]
Thanks for the tip. I will check it out... Unfortunately it is only how to implement bootstrap less files into magento. It works with the normal css files too so I do not yet bother about less files.

I already found out how to implement bootstrap though it is really hard since you might be able to add it in layout and page configuration files but it goes deeper too. Template files and now even php files that I need to edit.

I have problems with the last one yet since I did not yet find out how to do that with php files coming from module-theme.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
