### ISSUE TITLE
How to make multiple depends parameter

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#4933]
In widget.xml

```
<parameter name="navigation_prev" xsi:type="text"  visible="true">
    <label translate="true">Prev Navigation</label>
    <description translate="true">Prev navigation text</description>
    <depends>
        <parameter name="navigation" value="1" />
        <parameter name="scroll" value="1" />
    </depends>
</parameter>
```

It's not work.
`Element 'parameter': This element is not expected.`

**Comment by minhluan259** [comment]
One more thing, how to make depends for multiple values of select option type?

```
    <depends>
        <parameter name="scroll" value="1" />
        <parameter name="scroll" value="2" />
    </depends>
```

**Comment by andimov** [comment]
@minhluan259 thank you for reporting!
If you think it is a bug, please follow the template to describe it. It's allow us to research the issue.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
