### ISSUE TITLE
Class 'Magento\Framework\Data\Form\Filter\2016-05-01' not found On customer save Magento2 Migration

### ISSUE THREAD

**Issue by ruturamani** [magento/magento2#4936]
I have done migration from 1.9.2 to 2.0.x many times. Last I did was in 2.0.6. But I am having same error every time. The error I am getting is in saving customer. I am unable to Edit migrated as well as newly added customers after migration. I am getting the following error:

 Class 'Magento\Framework\Data\Form\Filter\2016-05-01' not found in D:\wamp\www<magento_root>\vendor\magento\module-customer\Model\Metadata\Form\AbstractData.php on line 214.

I have tried the following solution.  

Going into the database, I found in table customer_eav_attribute the column input_filter. Changing varchar to date. But this didnt solved the problem.

One more issue I am facing is that my "billing" and shipping address are not correctly coming on customer edit page, orders page in both frontend and backend.

Here are some screenshots for the above issue.

![untitled](https://cloud.githubusercontent.com/assets/19835337/15925497/04e31af6-2e55-11e6-8870-e4f78d384ebb.png)

Can any one please help me to get out of it... I am seriously got rid of this issue.

Thanks !

**Comment by ruturamani** [comment]
This is one more screenshot of order view page... after migration. Here also I am not getting the billing and shipping address.

![untitled2](https://cloud.githubusercontent.com/assets/19835337/15925725/f4a2eeb8-2e55-11e6-914a-cd05c70cda2e.png)

Thanks !

**Comment by mslabko** [comment]
Hi @ruturamani ,
Thank you for reporting! We will take care about your issue, but please use this repo https://github.com/magento/code-migration/issues for similar issues

**Comment by milanstojanov** [comment]
I can confirm this issue! Happens after I have upgraded from 1.7.0.2 to 2.1.0. Any solutions so far?

**Comment by milanstojanov** [comment]
The solution: https://github.com/magento/magento2/issues/5873

**Comment by ilol** [comment]
Registered MAGETWO-54115

**Comment by magento-engcom-team** [comment]
Hi @ruturamani 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by aniruddh-capital** [comment]
I had the same issue on 2.3 but not related to the migration 
here is the solution which worked for me for anyone still having this issue on 2.3
replace this file /vendor/magento/module-paypal/Model/Express/Checkout.php
with latest of magento version 2.2.4

the update is in this function
_setExportedAddressData

and as its a bug in core file you're fine to replace the core file

**Comment by hackronshins** [comment]
Hi, My recent upgrade is 2.3.1 as Magento moves we are upgrading one by one, 
But we are having an issue which is on Paypal orders we are getting variable prefixes in billing address as email template format in admin side back end.
**Admin Dashboard -> Sales -> Operations -> Orders -> View Order** 

_Is there any fix relates to its?_

> I tried all above solutions who got fixed, In database also I checked it is perfect. But why it is not fixed yet. We didn't touched anything in code.

**Please help me to get a best solution for this.
Please find the attachment**

![14](https://user-images.githubusercontent.com/23425297/59678977-53284180-91eb-11e9-92a3-ee6054137500.PNG)
