### ISSUE TITLE
Feature Request - Varnish Cache Plus support

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#4938]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Install Varnish
3. Switch Magento to HTTPs. Varnish is bypassed.

Please consider support for Varnish Cache Plus for HTTPS connections:

https://www.varnish-software.com/plus/ssl-tls-support

**Comment by choukalos** [comment]
Hi @craigcarnell VarnishPlus pricing starts at $31k US for a 3 node cluster is this something that merchants would be willing to pay over using Nginx for SSL termination -> Varnish -> Nginx FPM or Apache type of system architecture?  What about [Hitch](https://www.varnish-software.com/community/hitch) instead?

**Comment by commcad** [comment]
^^^ No thanks lolll

NGINX on **HTTP2** with the full TLS1.2 and HSTS implemetation + running REDIS 3.5 on unix socket.

= makes varnish almost as popular as the built-in firefox's cache ;)

< 0.75sec page load. Read; nearly instant 

(Magento 2.1rc2 pffffff!!!)

**Comment by cscd98** [comment]
@commcad do you have a link to more information?
@choukalos definitively no!

**Comment by choukalos** [comment]
@commcad very cool; I'm carrying an epic to modularize/make it easy to change out caching engine (MAGETWO-40094)

Thanks for the feedback.  Have either of you checked out Hitch - wondering your thoughts there?

**Comment by cscd98** [comment]
@choukalos Configured nginx with http2/tls 1.2 + HSTS with Redis 3.2.1 for cache and session

Varnish is running for HTTP requests.

The basket take 12 seconds to load, with a single SKU in the basket. Not exactly earth shattering 2 second load time!

This is on a 2GB Intel + SSD cloud instance on Rackspace.

On my home page, non-HTTPS I am seeing the html return in 26ms using Varnish.

This is on Magento 2.0

**Comment by commcad** [comment]
@choukalos - haven't checked on Hitch. No point, the ootb kit works more than perfectly for us ;) Nice work bud

@craigcarnell - get rid of varnish all at once mate. No need. Attaching my config below for nginx & REDIS. That is for HTTPS only (no http, again, no need). Lightning fast and stable, compared to the other one anyway. And yes I've tried Varnish, nothing but trouble (bug reports RE varnish/magento speaks tons). Should be exterminated if you ask me lolll 

here it goes, have fun

[nginx.conf.txt](https://github.com/magento/magento2/files/333066/nginx.conf.txt)

[nginx_sites-enabled-default.txt](https://github.com/magento/magento2/files/333067/nginx_sites-enabled-default.txt)

[env.php.txt](https://github.com/magento/magento2/files/333068/env.php.txt)

**NOTE**: REDIS is configured to run on unix socket for max performance. You can find info related tot changing this online. Also, logging is disabled in NGINX.

That Magento 2.1.0GA with the backend above kills

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Varnish-Cache-Plus-support/idi-p/45974).
