### ISSUE TITLE
Dropdown menu attribute value not filtering quote character in admin

### ISSUE THREAD

**Issue by webdezign** [magento/magento2#4939]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a new attribute with dropdown menu type, enter values with " or '
3. Assign this attribute to default attribute set.

Expected result
![bug](https://cloud.githubusercontent.com/assets/18737251/15928504/2f47030e-2e3f-11e6-8fb6-9f4c67d4c959.png)
## Actual result

The values inside dropdown menu should filter &quot; as "

**Comment by IlnitskiyArtem** [comment]
@webdezign, Thanks for reporting this issue.
We've created internal ticket MAGETWO-70375 to address this issue.

**Comment by magento-engcom-team** [comment]
@webdezign, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
