### ISSUE TITLE
Response when adding products to cart should be changed

### ISSUE THREAD

**Issue by mackelito** [magento/magento2#4940]
## Steps to reproduce
1. Add items to the cart thru the rest API and inspect the result of the xhr
## Expected result
1. Response should be the cart. Same as when requesting '/rest/V1/guest-carts/29c8ee939e3a6146518e7340dfef75eb/totals'
## Actual result
1. The response is the product that we just added. eg:
   `{"item_id":52,"sku":"MH01-XS-Black","qty":1,"name":"Chaz Kangeroo Hoodie-XS-Black","price":52,"product_type":"simple","quote_id":"569"}`
## 

If we don´t get the totals as response we need to make twice as many requests..
- One for adding item to the cart and then
- One to get the cart totals.

It would be way smoother to get the cart totals as the response when adding to the cart.

**Comment by choukalos** [comment]
Assigning @mbrinton01 and marking as desired improvement.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Response-when-adding-products-to-cart-should-be-changed/idi-p/45109).
