### ISSUE TITLE
New Simple Products are not displayed in the frontend - Magento ver. 2.0.6

### ISSUE THREAD

**Issue by Talisa85** [magento/magento2#4944]
Hi Community,

since a couple of days I'm not able to set up a simple product which is display in the frontend. Any attempt to make it visible in the frontend leads to no result.

Currently I'm running Magento 2.06

Looking forward to your solutions, regards Talisa

**Comment by orlangur** [comment]
2.0.6 could not break I believe, are you sure not using 2.1-rc? In 2.1 I noticed product are wrongly saved as Out of Stock if do not specify quantity.

There are not a lot of things which can go wrong to lead to result you observe. Could you specify exact steps maybe? So, to get displayed product needs to be In Stock, with proper Visibility (Catalog, Search is default), caches and indexes needs to be green.

**Comment by Talisa85** [comment]
![image](https://cloud.githubusercontent.com/assets/19840780/15940968/96cd31bc-2e7e-11e6-8185-3bd16ab4b672.png)

![image](https://cloud.githubusercontent.com/assets/19840780/15941296/c47b8b94-2e7f-11e6-9d12-7446d569f7a3.png)

Hi Orlangur,
thanks for feedback. I just double checked. I'm using 2.0.6 and the products are in stock. Cache and index are clear and green.

I set up the new products exactly like the products before, but this time they aren't visible in the front. Maybe the upgrade to 2.0.6 is the problem?

**Comment by antboiko** [comment]
Hi @Talisa85 , how many Websites do you have? Could you please also check Websites tab on Product form?

Thanks,
Anton.

**Comment by Talisa85** [comment]
Hi Anton,
i just have one Site. Do mean this Tab?
![image](https://cloud.githubusercontent.com/assets/19840780/15957251/2866a616-2eee-11e6-992e-c4a6da5420fd.png)

I spend 3 days and have still no solution for this problem. Can anybody help me.

**Comment by Talisa85** [comment]
Update on 2.0.7 didn´t resolve the problem :-(

**Comment by slopukhov** [comment]
@Talisa85 thank you for your feedback.
Please, recheck it on the latest 2.0 or 2.1 version of Magento (with configured cron job)

**Comment by vzabaznov** [comment]
Hi @Talisa85 , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Comment by lpkapil** [comment]
Hi It still does not show in front end category view. I have cofigured a simple product in backend. Using magento 2.2.1 version.

**Comment by LeorentKelmendi** [comment]
This framework, its shit. I am so tired of crashing all the time.
