### ISSUE TITLE
Facing issue magento 2.0.7 http://ip- address/magento/admin/admin/index/index/key/44645c3100b53cd5ae070f164109438496abb028e7d4bf38ed63168ebafd86bf/

### ISSUE THREAD

**Issue by ranjith2512** [magento/magento2#4947]
I try following but not resolved

1.php bin/magento setup:static-content:deploy
2.chmod -R 777 *
3.vi /etc/httpd/conf/httpd.conf
If i edit to override all it means admin page reflect 500 error

Please help

**Comment by crantron** [comment]
There is so much wrong with what you're doing, this ticket should be closed. Ask this question in stackoverflow. 

_to get you in the right direction_ 
- never chmod 777 , modSecurity is probably hating you.
- read the permissions section in magento 2 set up in the docs. 
- you've obviously not set the base url.

Godspeed.

**Comment by duhon** [comment]
Hello @ranjith2512

Did you try to apply  the solution which has been proposed by @cranton?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
