### ISSUE TITLE
Compiler improvement

### ISSUE THREAD

**Issue by nextend** [magento/magento2#4949]
It would be great if you could add extend the setup:di:compile command with hooks to be able to exclude specific directories in our extensions. My extension is a crossplatform application and the compiler always fails as it uses custom autoloader and lot of special things. With the current Magento 2 compiler I can not release it. 

As far as I see the test folders excluded only and there is no hooks anywhere to intercept the excludes and place mine in place. 

Related stackexchange question: http://magento.stackexchange.com/questions/119967/magento2-custom-autoloader

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Compiler-improvement/idi-p/45108).
