### ISSUE TITLE
Invalid return type - urgent

### ISSUE THREAD

**Issue by usn0545** [magento/magento2#4950]
Invalid return type
#0 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#1 /var/www/html/magento2/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#2 {main}

Can some one tell me why I'm getting this issue.

**Comment by mrkhoa99** [comment]
@usn0545 you can reproduce step by step your issue?

**Comment by davidalger** [comment]
@usn0545 To allow the core team to evaluate this as a bug, please provide complete details on your environment setup / configuration (such as software used, versions, etc), and also complete steps to reproduce it. Thanks!

**Comment by kumatozz** [comment]
I have the same issue, can someone help to get rid of it? Thanks in advance!

**Comment by andimov** [comment]
@usn0545 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
@kumatozz
You can create new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
