### ISSUE TITLE
Configurable Product - Edit Configurations changes names of simple products to SKU

### ISSUE THREAD

**Issue by bpoiss** [magento/magento2#4951]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a configurable product with at least 1 associated product and save it
3. Reopen edit page
4. Click "Edit Configuration"
5. In Step 2 select an additional attribute value so that a new simple product is generated
6. Finish the wizzard, click generate products
## Expected result
1. In the grid of associated products, the names of the already existing products should not change
## Actual result
1. The names of the already existing products in the grid of associated products change to their SKUs

**Comment by antboiko** [comment]
Hi @bpoiss , thanks for reporting this issue. Internal ticket MAGETWO-54222.

Best,
Anton.

**Comment by mslabko** [comment]
Hi @bpoiss 
Issue was fixed and will be available on 2.1 release. Thank you for reporting!
