### ISSUE TITLE
Help Doc Link 404

### ISSUE THREAD

**Issue by stevewinni** [magento/magento2#4954]
Steps to reproduce
1. Marketing > Promotions > Cart Price Rules > Lables
2. Click on Help Icon for Store View Specific Labels

Expected result
1. http://www.magentocommerce.com/knowledge-base/entry/understanding-store-scopes

Actual result
1. 404

**Comment by ghost** [comment]
@stevewinni  Hi, we'll take responsibility for this. It might take some time but we should be able to resolve it for you. Thanks for bringing it to our attention.

**Comment by ccondra** [comment]
The M1 user guides have been moved from merchdocs to the docs.magento.com subdomain, but there's a redirect in place that should take care of any existing links. If the redirect isn't working, we'll have to fix it.

**Comment by ghost** [comment]
Created internal issue MAGETWO-58340 to track.

**Comment by magento-engcom-team** [comment]
@stevewinni, thank you for your report.
The issue is already fixed in 2.1.0
