### ISSUE TITLE
Feature request - Export for site content (static blocks / pages)

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#4956]
Would it be possible to make the import/export function also available for all the static pages and blocks? Nowadays webshops are barely just products, but also consist of a lot of static content, but migrating it is a real headache. It is doable by exporting/importing database tables but it's a hassle to set all the correct storeviews, ID's and pages. Plus in a combination of static blocks tied to widgets in a certain theme, this is horrific.

It would be nice to see some WordPress functionality here, if you export stuff from WordPress and import it in another you get a screen with all the variables (like author and such) and you can select to create that author, or adding that content to another existing author. The same could be in Magento;

**How it could work**
If you import Pages and/or Blocks, it could be mapped to all storeview by default, or (like WordPress) show the option to add the missing storeviews or add them to an exisiting.

Adding Widgets would ask for input about which theme, storeview and block it would be assigned to, or leave the block open (and import is as inactive) to add the blocks at a later stage after the import

**Comment by giacmir** [comment]
We developed a module to do that. It exports from interface and then reimports from cli.

https://github.com/magespecialist/MSP_CmsImportExport

**Comment by Asitis** [comment]
Nice to see a module for it, but functionality like this seems better in the core I think. Though I saw that there were "extended CMS options" planned for the 2.3 release. Maybe something like this is in there

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Export-for-site-content-static-blocks-pages/idi-p/44723).
