### ISSUE TITLE
Fatal error when adding newsletter template

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#4957]
## Steps to reproduce

Navigate to the **Marketing>Newsletter Template** section from your main admin dashboard. Then, Click on the **Add New Template**

Will throw below error

**Fatal error:** Call to a member function getId() on string in [magento root]/vendor/magento/module-google-optimizer/Observer/Block/Category/AddGoogleExperimentFieldsObserver.php on line 45

**Comment by mslabko** [comment]
Hi @shivkumarsingh7 
This issue is similar to https://github.com/magento/magento2/issues/4652

It already fixed in 2.1-rc. Try to update your code base and if you still have any issue, please reopen this one. 
Please, follow up marketing updates
