### ISSUE TITLE
redirecting to dashboard 

### ISSUE THREAD

**Issue by shivkumarsingh7** [magento/magento2#4959]
## Steps to reproduce
1. you will need to navigate to Content>Blocks in magento admin.
2. click on select in action for any available block and click on detail.

It will redirect to admin dashboard.

**Comment by wert2all** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by hostep** [comment]
Duplicate - https://github.com/magento/magento2/issues/2375
