### ISSUE TITLE
[2.1-RC2] Different admin language breaks admin GUI

### ISSUE THREAD

**Issue by peec** [magento/magento2#4960]
PHP version: 7.0.3
Magento: Magento 2.1-RC2

Just did upgrade from 2.0.7 to 2.1.0-RC2
## Steps to reproduce
1. Change the language of admin interface in the upper right corner ("Account settings (admin") and chose another language.
2. Clear cache
3. E.g. Try to edit a product.
4. You will see errors and the editing GUI is not functional.

There is numerous errors, not only on product edit. Also category page. 
## Expected result
1. Product page renders cleanly with no JS errors.

![image](https://cloud.githubusercontent.com/assets/131546/15962158/7f4e4b94-2f09-11e6-9a82-4fe48547889d.png)
## Actual result

Product edit page:

![image](https://cloud.githubusercontent.com/assets/131546/15962337/c549297e-2f0a-11e6-9648-a489ffd49781.png)

Category page:

![image](https://cloud.githubusercontent.com/assets/131546/15962367/ecc6990a-2f0a-11e6-942f-af0d7931f6d2.png)

**Comment by peec** [comment]
Totally unrelated to the admin language but ( another error when I press save on a product ):
Edit created #4962 for this issue.

**Comment by ludwig-gramberg** [comment]
yep, and we use another language than en_US as the default, but you can't even register without en_US being available, you would have to change the users language within the database

the interface should only allow for languages which are availble in pub/static

**Comment by peec** [comment]
This seems to be fixed in Magento 2.1-RC3. Closing.
