### ISSUE TITLE
static-deploy does not generate all static files: _requirejs only generated on demand

### ISSUE THREAD

**Issue by ludwig-gramberg** [magento/magento2#4961]
this should be fixed, if I deploy my static code to production the command should trigger the creation of the files in pub/static/_requirejs and pub/static/_requirejs/secure as well

**Comment by hostep** [comment]
Nice find @ludwig-gramberg!

I just tested this using Magento CE 2.1.1 with the following configurations:
- secure url's enabled (https)
- js minifying enabled
- js bundling enabled

These files are created at deploy time:
- pub/static/_requirejs/frontend/{Vendor}/{theme}/{locale}/requirejs-config.min.js
- pub/static/frontend/{Vendor}/{theme}/{locale}/Magento_Cookie/js/require-cookie.min.js
- pub/static/frontend/{Vendor}/{theme}/{locale}/requirejs/require.min.js
- pub/static/frontend/{Vendor}/{theme}/{locale}/requirejs-min-resolver.min.js

These files are created on the first request:
- pub/static/_requirejs/frontend/{Vendor}/{theme}/{locale}/secure/requirejs-config.min.js
- pub/static/frontend/{Vendor}/{theme}/{locale}/secure/requirejs-min-resolver.min.js

So only the **secure** assets aren't created at deployment time.

I stumbled upon this workaround (which I haven't tested yet) which might get us around this "problem" for now: https://github.com/davidalger/capistrano-magento2/issues/21

**Comment by ludwig-gramberg** [comment]
still an issue in 2.1.2

**Comment by magento-engcom-team** [comment]
@ludwig-gramberg, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual  result, and the expected result.
Please, add the following information:
- [ ] Preconditions: Magento version
- [ ] Steps to reproduce
- [ ] Expected result
- [ ] Actual result

**Comment by hostep** [comment]
I believe this got fixed in Magento 2.1.8, I tested it a couple of weeks ago, so this issue can probably be closed?

From the [release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html):
> Static content deployment now generates secure content, whether content included secure or non-secure URLs.

**Comment by magento-engcom-team** [comment]
Hi @hostep 
Thank you for the update.
