### ISSUE TITLE
[2.1-RC2]  Impossible to save product / category due to JS error. $.validator not defined

### ISSUE THREAD

**Issue by peec** [magento/magento2#4962]
## Steps to reproduce
1. Install Magento 2.1-RC2
2. Edit a product / category and quite possiblity other things too.
3. Click on the save button, you will notice that nothing happens when you click save.
4. Open console, you see error message ("TypeError: $.validator.validateSingleElement is not a function")

$.validator seems to be undefined.
## Expected result
1. Possible to save the product.
## Actual result
1. Error message `TypeError: $.validator.validateSingleElement is not a function` in browser console.

**Comment by chelevich** [comment]
I have met the same issue. Default en-US setup, no other languages, sample data, upgraded from 2.0.5 to 2.1-rc2. 
I was trying to save a simple visible product "Joust Duffle Bag" ID=1. 
Firefox47, Ubuntu 14. Non-reproducible in Chrome51.

**Comment by southerncomputer** [comment]
Are you in production mode or developer mode? Have you tried clearing pub/static/\* (not the .htaccess though) and service php-fpm restart ? 

Have you tried disabling all minification/merging of javascript in store->config->developer ?

**Comment by chelevich** [comment]
I am in a developer mode. I have removed pub/static/adminhtml and _requirejs folders, they were successfully regenerated on page reload. I have reloaded the page bypassing browser's assets cache Ctrl-F5. That did not help. The same error.
Merge and minification are disabled. I am pretty sure that PHP-FPM restart is not related anyhow to the issue, because there is no JS error in other browsers.

**Comment by southerncomputer** [comment]
PHP-FPM will cache existence of files with default settings but Magento Production reccomends disabling this feature. I suggest restarting php-fpm any time you muck with those directories, have you done php bin/magento setup:di:compile and setup:static-content:deploy after you have rm -rf var/di var/generation var/view_preprocessed and everything in pub/static except .htaccess? Also have you disabled the cache? 

I had this problem with 2.0.7 until I clean installed 2.1-RC2 where the minifier/shrinker would throw random translation garbage into the pub/static/_cache generated files causing many javascript issues like what you have noted!

Are you using NGINX and php-fpm 7.0.6? If so I'd suggest enabled store->config->developer Sign static files where it dynamically changes pub/static to pub/static123546 to separate cached elements.

I typically service restart nginx and php-fpm when changing any setup/cache/deploy/static-content to ensure there is no caching going on at the web/php level!

**Comment by southerncomputer** [comment]
I suggest disabling MERGE Javascript files and Minify Javascript files as well to ensure you are using the static-content bundle(0..5).js - I believe the error is due to php-fpm path caching conflict - using the bundle0..5.js will ensure they are deployed in production mode statically rather than dynamically via web processes which can step on themselves with php path/file_validation caching!

**Comment by chelevich** [comment]
MERGE and Minify are disabled. I have restarted PHP-FPM, removed subfolders from pub/static. With no luck, the same JS error while saving a product. I use nginx and php-fpm 7.0.6 with Zend Opcache enabled. Magento cache is disabled.
I disabled opcache for php-fpm in its php.ini, but that did not help as well.

**Comment by southerncomputer** [comment]
can you post a screenshot of your firefox developer mode -> Network showing the scripts being loaded?

**Comment by chelevich** [comment]
Once I set "Sign Static Files: Yes" the issue has gone. I am able to save products. 
Then I set it to "No", removed all subfolders under pub/static and the issue came back.
I noticed `js_translation.json` is empty. Are you still sure it is a translation issue?
![selection_044](https://cloud.githubusercontent.com/assets/1791881/16152630/7f0ec4ea-34ab-11e6-90f5-e6cb24530204.png)

**Comment by southerncomputer** [comment]
Are you using the suggested nginx.conf.sample ? Signing the pub/static##### is primarily to avoid caching issues on your browser/varnish/page_cache/web server path like putting a random?SID=123456 at the tail of each image file.

It is possible that you have caching issues from browser->nginx->php-fpm->varnish/page_cache!

Trust me i saw this same problem from 2.0.5 to 2.0.7 until I cleanly upgraded to 2.1-RC2 and verbatim applied the nginx.conf.sample from here!

here is my 10-opcache.ini from /etc/php.d -> This does not attempt to validate changes in files! I found that to be unreliable of magento2's ability to generate cache files on demand - some sort of race condition of the validate_timestamps and positive/negative caching before the files were complete. It caused reload's while monitoring network in developer mode to show changed results!

So I do a service php-fpm restart after any file changes!

zend_extension=opcache.so
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 1256
opcache.interned_strings_buffer = 12
opcache.max_accelerated_files = 86000
opcache.max_wasted_percentage = 5
opcache.use_cwd = 1
opcache.validate_timestamps = 0 ; disables checking for changed files
;opcache.revalidate_freq = 0
;opcache.file_update_protection = 2
;opcache.revalidate_path = 0
opcache.save_comments = 1
opcache.load_comments = 1
;opcache.fast_shutdown = 0
opcache.enable_file_override = 1
;opcache.optimization_level = 0xffffffff
;opcache.inherited_hack = 1
;opcache.blacklist_filename=/etc/php.d/opcache-default.blacklist
;opcache.max_file_size = 0
;opcache.consistency_checks = 0
;opcache.force_restart_timeout = 60
;opcache.error_log = "/var/log/php5/php5-opcache.error.log"
;opcache.log_verbosity_level = 3
;opcache.preferred_memory_model = ""
;opcache.protect_memory = 0
;;opcache.mmap_base = ""

**Comment by southerncomputer** [comment]
rm -rf pub/static/adminhtml/ pub/static/_cache/ pub/static/frontend/ pub/static/_requirejs/
rm -rf var/di var/generation var/page_cache var/cache var/view_preprocessed/
php -q bin/magento cache:clean
service php-fpm restart
 php -q bin/magento deploy:mode:set developer
 php -q bin/magento setup:static-content:deploy

here is my configuration on developer mode:
![capture01a](https://cloud.githubusercontent.com/assets/6178967/16154424/cd7f0c3a-3478-11e6-8206-3607cdc3e996.PNG)
![capture01b](https://cloud.githubusercontent.com/assets/6178967/16154426/d17f2fcc-3478-11e6-9763-ae04d3efe38e.PNG)

**Comment by southerncomputer** [comment]
After that I might do :+1: 
service php-fpm restart
 php -q bin/magento deploy:mode:set production
service varnish restart
service httpd restart (or nginx)
service php-fpm restart

Now in production mode if I set Merge Javascript Files & Minify javascript files: as soon as I hit save I get : [2016-06-17 15:14:24] main.CRITICAL: Magento\Framework\Exception\FileSystemException: Cannot read contents from file "/home/asdf/public_html/pub/static/adminhtml/Magento/backend/en_US/js/bundle/bundle0.min.js" Warning!file_get_contents(/home/asdf/public_html/pub/static/adminhtml/Magento/backend/en_US/js/bundle/bundle0.min.js): failed to open stream: No such file or directory in /home/asdf/public_html/lib/internal/Magento/Framework/Filesystem/Driver/File.php:149

which I then go through the rm -rf .. service restarts, php -q bin/magento deploy:mode:set:production and the whole rigaramole again!

**Comment by southerncomputer** [comment]
Which goes to 1st production mode: no merge/minify Javascript:
![capture01c](https://cloud.githubusercontent.com/assets/6178967/16155642/3948c19a-347e-11e6-86a8-62c08cb701a9.PNG)

to 2nd production mode with merge/minify Javascript:
![capture01d](https://cloud.githubusercontent.com/assets/6178967/16155646/4523b22c-347e-11e6-9fdb-0ccd58f2115b.PNG)

And yeah json_translation.js should be blank or {} unless you are using translations? not for me!

**Comment by peec** [comment]
Hm, I managed to get this working in Magento 2.1-RC3.

Either it's becaused i switched from `192.168.1.100` as my base url in magento2 to `magento2.dev` . ( With alias in hosts file, seems like some security issues in browsers? ) . 

Or just because of upgrading to RC3.

**Comment by ignaciomella** [comment]
I'm experiencing this issue in Magento 2.1.0 

Uploaded products via csv import, but when I try to save one of the products, I get:
![capture](https://cloud.githubusercontent.com/assets/9328631/16360172/46a9f8ee-3b28-11e6-9809-b8a10e5ff079.JPG)

**Comment by andimov** [comment]
@ignaciomella 
Did you try to reload services?
https://github.com/magento/magento2/issues/4962#issuecomment-226798155

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
