### ISSUE TITLE
Poor REST API documentation

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#4963]
It is necessary to finish REST API documentation. Right now it is frustrating to create request from current swagger documentation.

What is missing?
- how to create request as logged customer (for example how to create cart as logged customer)
- POST V1/carts/mine - missing parameters model schema

I will add here all missing information which missing in current docs.

**Comment by RUjmiak** [comment]
GET /V1/customers/me

with header Authorization Bearer <token>

respond is 400 Bad request

{
    "message": "%fieldName is a required field.",
    "parameters": {
        "fieldName": "customerId"
    }
}

**Comment by ghost** [comment]
@RUjmiak You should consider making your requests on the [devdocs GitHub repo](https://github.com/magento/devdocs/issues)
