### ISSUE TITLE
White login page (404 errors) if setup:static-content:deploy is used wrong

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4964]
We need to delete the whole pub/static/frontend-folder if we want to have CSS changes and stuff available on the site. 

So we do the following:
$ rm -rf var/cache/\* var/generation/\* var/page_cache/\* pub/static/*
$ php-cli bin/magento setup:upgrade
$ php-cli bin/magento setup:static-content:deploy de_DE

Here comes the problem. If you delete the backend folder in pub/static Magento tries to allocate the requested URL (i.e. login page for backend) for the en_US language, even if the only user in the backend has selected that his main language is de_DE. 

Magento simply tries to access files that are not there and that are not needed to be compiled (in our case: German). There should be an setting in the backend that sets the main language for the whole store to a specific language which get then called by default. This prevents unnecessary white pages.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/White-login-page-404-errors-if-setup-static-content-deploy-is/idi-p/45107).
