### ISSUE TITLE
Installing a custom module after throwing a table value out of the database triggers an stacktrace

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4965]
We created a custom module. We installed it with setup:upgrade. Since the module didn't did what we expected I deleted its value out of the setup_module table in order to use setup:upgrade again. The problem: this time data_version didn't got set (it stayed on NULL) whilst the schema_version got re-set to 2.0.0. 

I'm not sure if this is intended.

Exact way to reproduce:
- create a module with all nessecary files
- $ php bin/magento setup:upgrade
- $ php bin/magento setup:static-content:deploy xx_XX
- delete the corresponding value out of the database (setup_module)
- again $ php bin/magento setup:upgrade
- again $ php bin/magento setup:static-content:deploy xx_XX
- now theres an empty table in setup_module, which leads to an error

Magento 2.0.7

**Comment by BaDos** [comment]
Hi, @grasdaggel!

Thank you for your feedback.

Cannot reproduce this issue on 2.0.7 and latest 2.0.10 version.
Do you have the same issue with some Magento module, for example, Magento_Sitemap?
Please, provide module.xml from your module.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
