### ISSUE TITLE
getDescription(); and getShortDescription(); suddently stopped working

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4967]
Not sure how this could happen. We made some template and module changes recently and often used setup:upgrade and setup:static-content:compile. 

We made some changes on the Magento_Catalog/templates/product/view/list.phtml and form.phtml, but both contain the same stuff as before (its just the order of the elements), also there are three different ways where we use <?php $_product->getShortDescription(); ?>. However, it stopped working and we don't even have the long description in the tabs anymore. 

What could cause this? How could I fix this? Seems super odd to me! 

In the backend we didn't touched the description and short_description attributes. Those are at the default settings, which worked before. Also the description is not hidden trough CSS. 

Thanks in advance.

**Comment by mrkhoa99** [comment]
Please, post your issue to http://magento.stackexchange.com/

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
