### ISSUE TITLE
swatch renderer block for configurable products has no name in layout

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#4968]
In the file `vendor/magento/module-swatches/view/frontend/layout/catalog_category_view.xml` the swatch renderer is inserted as child block to the `category.product.type.details.renderers` block. However the swatch renderer block is given no name. As such it's impossible to remove it in a custom layout.

Of course it's possible to remove the parent block `category.product.type.details.renderers` since it seems like the swatch renderer is currently its only child block. But that is not a minimally invasive solution. Shouldn't all blocks be given names as a matter of good style?

**Comment by palamar** [comment]
@ktruehl
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ktruehl** [comment]
@palamar
Version 2.0.7.

**Comment by ktruehl** [comment]
@palamar 
OK. Now we're on 2.1 and the problem still persists. The swatch renderer block still has no name.

**Comment by palamar** [comment]
Thanks

**Comment by magento-engcom-team** [comment]
@ktruehl, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by ktruehl** [comment]
Really? The requested change takes like 10 seconds and can't break anything. This rather looks like you're drowning in issues and have to prioritize heavily. Why not consolidate what you have instead of breaking everything with every new release and pissing everyone off in the process?
