### ISSUE TITLE
minicart not cleared after order completion

### ISSUE THREAD

**Issue by rajesh2590** [magento/magento2#4969]
I'm facing the issue of minicart not cleared after order completion using our custom payment method.

This is the same issue as:
[Cart Items are not deleted after success checkout #1461](https://github.com/magento/magento2/issues/1461)

As we're creating extension for payment method, we've limitation to not to override, modify or inject our content to any view or layout (like onepage/success) after order completion.
i.e; all the process is working on server end in our action controller.

**Comment by orlangur** [comment]
Please describe your issue as a separate question rather than a comment to a http://magento.stackexchange.com/questions/100615/magento-2-how-can-refresh-minicart-cache-after-clear-cart-session-and-place-orde so that it can be answered.

GitHub is not a right place for this sort of things.

**Comment by commcad** [comment]
@orlangur 

I also, among another guy I know of, are having the same bug in 2.1.0RC2 where the cart does not empty after a successful purchase. The items that the customer purchase remain active in the shopping cart (minicart).

## Steps to reproduce
1. Upgrade Magento from 2.0.7 to 2.1.0rc2
2. Customer carry out a purchase on the store using PayPal for instance
3. The customer receives a "Order have been created" success message, email confirmation and all. 

## Expected result
1. the shopping cart clearing itself of the latest purchase.

## Actual result
1. Items remains in the shopping cart, does not clear itself after a successful transaction.

## 

@orlangur RE your comment  > _GitHub is not a right place for this sort of things._ I think it is buddy. We are not reporting these bugs for pure pleasure and entertainment, instead we are trying to contribute in the success of this eCommerce platform. Get it ?!

**Comment by orlangur** [comment]
Hi @commcad, did you read http://magento.stackexchange.com/a/120407 actually? So @rajesh2590 reported the problem he met with his custom implementation both here on GitHub and there on StackExchange (but as a comment to older question which is misuse of StackExchange).

Your report contains proper steps for core functionality but you didn't report a separate issue on GitHub but commented in two existed issues. This is misuse of GitHub I believe :)

As I explained in https://github.com/magento/magento2/issues/4114#issuecomment-209656012, this type of issue should be pretty easy to debug and fix. So, just go all over the scenario and note which action did not invalidate customer data (a.k.a localStorage) while it have to.

**Comment by codelogn** [comment]
Thanks, the code for the fix worked for my custom checkout module too.

**Comment by andimov** [comment]
@rajesh2590 
Thank you for reporting!
This is a duplicate issue. I'm closing this one. Please, try to use #5807 or wait for MAGETWO-52593.
