### ISSUE TITLE
Will it be possible to track changes in the history of the price of goods?

### ISSUE THREAD

**Issue by chrom** [magento/magento2#497]

**Comment by loneregister** [comment]
_Removed by moderator_

**Comment by davidalger** [comment]
@LoneRegister Please do not post self-promoting links. This is a channel for reporting technical issues and tracking feature requests, not for advertising!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Will-it-be-possible-to-track-changes-in-the-history-of-the-price/idi-p/44944).
