### ISSUE TITLE
Error IDs - REST API

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#4970]
It would be great to have not just message as response when request is not successful.

For example adding product to cart

response **400 Bad request** and message "You need to choose options for your item."
or **400 Bad request** and message "This product is out of stock."
or **400 Bad request** and message "We don't have as many \"Chaz Kangeroo Hoodie-XS-Gray\" as you requested."

Compare messages to identify error is not good approach... even when you want to connect to more magento websites with different languages...

Did you think about it?

Thanks

**Comment by choukalos** [comment]
Hi @RUjmiak yes we thought about enabling that level of error responses but for security reasons stuck to just error code in default and production mode.  In developer mode you should see something similar to what you're requesting*.  Our framework will detect missing fields but I think the reply could be improved further to make it easier to debug/etc.

**Comment by RUjmiak** [comment]
Thanks @choukalos for your reply. When I want to use API I want to use it on production mode and right now its really pain with this error messages. So in production mode is just error code?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Error-IDs-REST-API/idi-p/44720).
