### ISSUE TITLE
2.1.0-rc2 superficial change breaks extensions with sales order grid massactions

### ISSUE THREAD

**Issue by fooman** [magento/magento2#4972]
This line of code here
https://github.com/magento/magento2/commit/e81257235a89109012fdf5e2f038bf95272ad771#diff-f479129e7d10b50309fc7c8773e636cbL34

changes the `listing_top` from a `container` to a `listingToolbar`. However `listingToolbar` is defined in the `ui_configuration.xsd`  as

```
<xs:complexType name="listingToolbarConfiguration">
    <xs:complexContent>
        <xs:extension base="containerConfiguration"/>
    </xs:complexContent>
</xs:complexType>
```

currently to me this change looks to be absolutely superficial - it doesn't provide any additional value, however has the effect of breaking any extension that has previously added a massaction to the sales order grid dropdown in Magento 2.0.x.

**Comment by fooman** [comment]
2.1.0 was released with this change still in https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml

**Comment by matthew-muscat** [comment]
Not sure why this was closed - confirming this affects v2.1.0 (CE / EE).

As @fooman mentioned, this breaks extensions which used "container" to add massactions to the sales order grid, which works in the 2.0.x release, but now requires "listingToolbar" in 2.1.x

**Comment by fooman** [comment]
@matthew-muscat I closed this since the release went ahead with the change in there. So if this was reverted this would only be in 2.1.1 which would make compatibility even worse going forward.

**Comment by shahabhameed** [comment]
@fooman  
Is there a way to support backward compatibility in an extension, or should we release two versions (for magento 2.0.x and magento 2.1.x)  of the extension which are adding mass actions on sales order grid ?

**Comment by fooman** [comment]
@shahabhameed we went the two separate releases approach
