### ISSUE TITLE
Print options from the Orders grid should be available when looking at a single order.

### ISSUE THREAD

**Issue by pynej** [magento/magento2#4975]
## Steps to reproduce
1. Install Magento from `2.0.7` branch.
2. Generic store data
3. Create and order
4. Open the order in Sales->Orders
## Expected result

It would be nice if there was a Print dropdown or a Print All button on the main order page similar to the index page so that we don't have to click  down into Invoice or Shipping and do multiple Print operations on an order.

**Comment by pynej** [comment]
Ok, maybe less of an issue that I thought.  I did find that I can get it my going to Invoices and then checking the Invoice box and selecting PDF Invoice.  Still 4 clicks but the user doesn't have to search for the order.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Print-options-from-the-Orders-grid-should-be-available-when/idi-p/44719).
