### ISSUE TITLE
Transaction Fetch: Incorrect Method Call

### ISSUE THREAD

**Issue by sw45859** [magento/magento2#4976]
Currently it is using the transaction entity id in the method call to load the order when it should be using the order id when fetching transaction information on the admin transaction details page.

Magento CE version 2.0.7
## Steps to reproduce
1. Attempt to fetch transaction results for any payment from payment transaction view
## Fix:

vendor\magento\module-sales\Controller\Adminhtml\Transactions\Fetch.php line 29
change $txn->getId() to $txn->getOrderId()

**Comment by oserediuk** [comment]
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by sw45859** [comment]
it is in magento CE version 2.0.7

**Comment by SerhiyShkolyarenko** [comment]
We need more information about this issue in order to successfully investigate potential fixes. Please use our issue tracking template to format your description. Specify the **exact steps** you used, the expected result of your actions, and the actual results.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by OleksiyOleksiyovych** [comment]
Please, reopen this bug.

Sorry, but I have this bug too. I believe it's typo issue.
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Transactions/Fetch.php#L36

`$this->orderPaymentRepository->get($txn->getId())`
shoud be changed to 
`$this->orderPaymentRepository->get($txn->getPaymentId())`

I create a custom payment method and find this issue when I try to create logic for fetch transaction info. I think, you do not need steps to reproduce for fix it, please, review code and fix this typo error. Now Magento load order payment object by transaction id, but it must be loaded by payment id.

Also, you should rewrite this class  (Magento\Sales\Controller\Adminhtml\Transactions\Fetch) with Magento standards: change deprecated methods and do not use object manager.
