### ISSUE TITLE
Wrong currency in invoice grid view

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#4980]
I have tested in magento CE-2.0.7 . Base currency USD - Default display currency VND (Vietnam Dong)
![screenshot 2016-06-11 10 14 47](https://cloud.githubusercontent.com/assets/1908873/15982858/1a6e4dae-2fbe-11e6-9846-8b99b178bffa.png)

**Comment by NadiyaS** [comment]
Hi @mrtuvn ,
thank you for reporting this issue. 
Internal ticket MAGETWO-54384 was created to track this issue.

**Comment by Gorkyman** [comment]
@NadiyaS this is still an issue in 2.1.1. Any update on when this might get fixed? If you need any more info about our DB, let me know.

**Comment by olysenko** [comment]
Hi,  @Gorkyman. I cannot reproduce the issue using such steps
STEPS
1. Fresh install magento 2.1.2
2. Create simple product
3. In menu Stores->Configuration->General->Currency Setup->Currency Options set Default Display Currency to Vietnamese Dong and in Allowed currency set Vietnamese Dong
4. Configure Rates in Stores->Currency Rates
5. Save Configuration
6. Reindex
7. Place order with simple product
8. Create invoice
9. Check invoice tab in order management
RESULT
Price in  Vietnamese Dong

So, please provide your custom steps in order to reproduce this issue

**Comment by maderlock** [comment]
See my comment in #5036 - this is reproducible with multiple currencies on multiple sites.

**Comment by olysenko** [comment]
Hi, @Gorkyman. I cannot reproduce the issue using such steps with multiple currencies on multiple sites.
STEPS
1. Fresh install magento 2.1.2
2. In Configuration > Gatalog > Catalog > Price, set up the "Catalog Price Scope" as "Website"
3. Create second website  with second store and store view. Configure base url for second website
4. Create simple product. Assigns it to Default and Second websites  
5. In menu Stores->Configuration->General->Currency Setup->Currency Options
Change scope to Second Website 
6. Set Base Currency, Default Display Currency and Allowed Currencies to  Vietnamese Dong
--So we have in all currency options Vietnamese Dong for second website scope and US Dollar for default Config scope--
7. Configure Rates in Stores->Currency Rates
8.  Reindex indexes, clear cache
9. Place order with simple product on front-end 
10.  Create invoice in admin
11.   Check invoice tab in order management
RESULT
    Price in Vietnamese Dong

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by wescey** [comment]
Im running a 2.2.2 installation with 5 multiple websites with each own currency. In the Sales > Orders grid (grand total base), it's only displaying one currency that is based on default value.
