### ISSUE TITLE
jquery 3 integration with magento 2 

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#4981]
Hey , 

jQuery 3 has been release :) 

Can i use jquery 3 on magento 2 ?

**Comment by orlangur** [comment]
Let's talk on this in http://magento.stackexchange.com/questions/120482/jquery-version-update-at-m2/120484

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
