### ISSUE TITLE
System messages  One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by hutsanon** [magento/magento2#4982]
Please help 
Please tell me what is this.

![snap 2016-06-11 at 18 17 17](https://cloud.githubusercontent.com/assets/19837095/15984771/dfcc7818-3000-11e6-92d4-22242ed1b256.png)

**Comment by ghost** [comment]
It means cron isn't running. To fix it, set up a [crontab](http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-config.html#post-install-cron) for your [Magento file system owner](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-sys-perms-over.html).

You can also [run cron from the command line](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-group-run) but every time you make a change that requires reindexing, you'll have to do it again. Best to set up crontab.

**Comment by hutsanon** [comment]
@xcomSteveJohnson 
Please tell me about the details.

**Comment by ghost** [comment]
There's not much to say. In Magento 2, indexers are updated by a cron job.
You can [update indexers from the command line](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex) but again, you'd have to do it every time you made a change that invalidated them. Set up a cron job to do it automatically.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by hutsanon** [comment]
@davidalger 
I don't understand you.
What are you talking about.
I can not ask this question ?

**Comment by davidalger** [comment]
@hutsanon What I mean is that GitHub is for bug reports only, not technical questions, assistance on setting up, configuring, customizing, etc. Those questions are better suited to the forums and SE site (both of which I provided links to above), and keep the issue tracker uncluttered enabling Magento to process through bug reports faster by limiting what they have to filter through.

Relating to your question though, as Steve originally said though, there isn't really much to say beyond the three pages of documentation he sent you. The message means exactly what it says: You need to configure the cron jobs for Magento 2 so indexers will run. If you don't know how to do that, follow the instructions at the link he gave you or post a question on the forums or SE site (links above) if you need further assistance doing so.
