### ISSUE TITLE
Magento 2.0.7 - Product filters using Obeserver Event

### ISSUE THREAD

**Issue by hitumca** [magento/magento2#4983]
## Steps to reproduce

I am trying to create one observer for apply additional filters to product collection.

So i use magento 2 event :catalog_product_collection_load_after
i also try with override block \Magento\Catalog\Block\Product\ListProduct product collection filter 
But below code working fine with product collection, but showing wrong pagination and product count

Observer code is :
 public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $collection = $observer->getEvent()->getCollection();
        //echo count($collection);exit;
        $collection->addAttributeToFilter('shopartikel',1)
                   ->addAttributeToFilter('geloescht',0)
                   ->addAttributeToFilter('gesperrt',0);
        $this->_eventManager->dispatch(
        'catalog_product_collection_before_add_count_to_categories',
        ['collection' => $this]);  
        return $this;  
    }

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
