### ISSUE TITLE
Please add Success/any message in "forget password" feature

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#4985]
## Steps to reproduce
1. Install Magento 2.0.7 from release archive
2. Frontend. Customer Forget Password page.
3. just try recovery your password  
## Expected result

some customers little confused when they trying to recovery password, please add any notify..

Actual result
right now just redirect to login page and no message about what we did..

**Comment by cpartica** [comment]
Created internal issue MAGETWO-54589 that will be discussed with product as this is more of a feature
If they consider that this is a bug then I will update this ticket

**Comment by magento-engcom-team** [comment]
@magecodenet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
