### ISSUE TITLE
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance

### ISSUE THREAD

**Issue by woei66** [magento/magento2#4987]
## Steps to reproduce
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2 (\* 2.0.6)
2. composer diagnose
## Expected result
1. no error message
## Actual result
1. Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
2. require.composer/composer : unbound version constraints (@alpha) should be avoided
   ![2016-06-13 1 58 24](https://cloud.githubusercontent.com/assets/5770807/15998201/efba63e2-316e-11e6-8578-b2f43fc9691e.png)

**Comment by shiftedreality** [comment]
Hi @woei66 

Thank you for reporting.
We've created an internal ticket MAGETWO-58096 to resolve this issue.

**Comment by magento-engcom-team** [comment]
@woei66, thank you for your report.
We've created internal ticket(s) MAGETWO-58096 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@woei66, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
