### ISSUE TITLE
Incorrect preview thumbnail when adding an image of the same filename to a duplicated product

### ISSUE THREAD

**Issue by blizam** [magento/magento2#4988]
Mage 2.0.7

Create a simple product with image.jpg

Save + Duplicate

Now add a different image of the same image.jpg file name to the newly duplicated product... 

the preview thumbnail rendered for your new image will be identical to the first image... however, the right file is still being referenced/attached... saving the product will then show the correct preview thumb

**Comment by jabrware** [comment]
I've experienced the same problem
     + the thumbnails is no longer generated after cleaning cache
     + the product thumbnail placeholder path is wrong, it misses the image name in the end of the path

**Comment by wert2all** [comment]
maybe a copy of #3484

**Comment by magento-engcom-team** [comment]
@blizam, thank you for your report.
We've created internal ticket(s) MAGETWO-82387 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@blizam, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
