### ISSUE TITLE
'URL key for specified store already exists.' during product import with multiple store view

### ISSUE THREAD

**Issue by delyriand** [magento/magento2#4989]
I have the same problem 'URL key for specified store already exists.'. My problem is not related to the categories but a duplication of my product:
During the validation of the multi-store catalog import, the product is in two different bunch into `importexport_importdata` table. My "main" line product is a bunch and my declination for the "my_store" is in a second bunch.
And during import, it creates the product two times for the same sku.

I think the problem is because the sku is not preserved between two bunch. So the product - in the second bunch - also goes into creation instead of an update.

cf https://github.com/magento/magento2/blob/2.0.6/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L1439
The variable `$entityRowsIn` is reset each loop and my product sku isn't into `$this->_oldSku`

**Comment by veloraven** [comment]
@delyriand thank you for your report.
Please specify used Magento version and provide description according to the template: with steps, actual result and expected result.

**Comment by delyriand** [comment]
### Preconditions
1. Magento 2.0.6
2. PHP 5.6.20

### Steps to reproduce
1. Create a Product CSV file with multiple store data :
   - Add X products rows (X = config value import/format_v2/bunch_size)
   - And X+1 row, add an existing product in X rows with different store.
2. Go to System > Import
3. Launch product import

### Expected result
1. Products imported without error
2. Product with different data depending on store

### Actual result
1. During import, the error message `URL key for specified store already exists.` is displayed

**Comment by delyriand** [comment]
I think we have the same problem in Magento 2.1. Look at the comment below:
[1471#issuecomment-240306446](https://github.com/magento/magento2/issues/1471#issuecomment-240306446)

**Comment by BaDos** [comment]
Hi @delyriand 

Thank you for reporting.

This issue was fixed in [#1471](https://github.com/magento/magento2/issues/1471#issuecomment-246671265) and I cannot reproduce it now.
Please, reopen if you still can reproduce this issue.

**Comment by qbo-tech** [comment]
It can be reproduced by having 2 products with a blank name under the same category.

The problem in this case, is likely that you have 2 or more products with the same name under the same category path and you try to save the category or add a new product with that same duplicated name.

In our case, there where 2 products with a EMPTY name (you can find those on the product grid by sorting by name), **deleting/disabling/changing those duplicated products fixes the problem.**

This isnt particularly a bug, its more like a quite specific scenario where Magento tries to generate a URL like: category1/category2/.html-1 or something like that. Code should validate and throw a more proper error message, or even add a different suffix to the generated url key.

The correct approach would be to make the NAME attribute input mandatory by default.

**Comment by kbrakband** [comment]
I'm having this issue as well, but there aren't 2 products with a blank name under the same category in my import and there are also not 2 products with the same name under the same category.

Are you sure this is not a bug?

**Comment by orlangur** [comment]
> The correct approach would be to make the NAME attribute input mandatory by default.

It is mandatory in fact :)

**Comment by sadeeshmca** [comment]
This Magento 2 bug you can directy fix is changing file

File Path :vendor/magento/module-url-rewrite/Model/Storage/DbStorage.php

Orginal Code:
-------------
 from

    protected function doReplace($urls)
    {
        foreach ($this->createFilterDataBasedOnUrls($urls) as $type => $urlData) {
            $urlData[UrlRewrite::ENTITY_TYPE] = $type;
            $this->deleteByData($urlData);
        }
        $data = [];
        foreach ($urls as $url) {
            $data[] = $url->toArray();
        }
        $this->insertMultiple($data);
    }

 into

    protected function doReplace($urls)
    {
        foreach ($this->createFilterDataBasedOnUrls($urls) as $type => $urlData) {
            $urlData[UrlRewrite::ENTITY_TYPE] = $type;
            $this->deleteByData($urlData);
        }
        $data = [];
        foreach ($urls as $url) {
            $data[] = $url->toArray();
        }

         /* Add this line : Get rid of rewrite for root Magento category to unduplicate things
        foreach($data as $key =>$info){
                if(isset($info['target_path']) && stristr($info['target_path'],'/category/1') && $info['entity_type']=='product'){
                        unset($data[$key]);
                }
        }

        $this->insertMultiple($data);
    }

After insert this line clear cache.

**Comment by orlangur** [comment]
@sadeeshmca best way to put your patch for evaluation is submitting a PR ;)
