### ISSUE TITLE
Update stops at "composer hast been updated"

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#4990]
## Steps to reproduce
1. Using Update Wizzard
2. Update Magento 2.0.2 to 2.0.7
3. crons are installed like this:

```
*/1 *   *   *   * /usr/local/bin/php -c /opt/alt/php56/etc/php.ini /home/preview1/public_html/bin/magento cron:run >> /home/preview1/public_html/var/log/magento.cron.log&

*/1 *   *   *   * /usr/local/bin/php -c /opt/alt/php56/etc/php.ini /home/preview1/public_html/update/cron.php >> /home/preview1/public_html/var/log/update.cron.log&

*/1 *   *   *   * /usr/local/bin/php -c /opt/alt/php56/etc/php.ini /home/preview1/public_html/bin/magento setup:cron:run >> /home/preview1/public_html/var/log/setup.cron.log&
```
## Expected result
1. Update will finish
## Actual result
1. The update stops at "composer has been updated"

![update](https://cloud.githubusercontent.com/assets/6672673/16000491/092efb98-314d-11e6-9eea-138826a8f97b.png)

**Comment by ghost** [comment]
What is in your cron logs? Have you tried enabling logging in `php.ini`? Is there a Magento `var/log/exception.log`?
What is the value of `memory_limit` in `php.ini`?

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
