### ISSUE TITLE
[2.1.0-RC-1 and 2] page Content-> Configuration in adminpanel doesn't load.

### ISSUE THREAD

**Issue by Gelgersma** [magento/magento2#4992]
## Steps to reproduce

Go to admin panel page Content -> configuration. 
## Expected result

The loaded page where I can change themes.
## Actual result

Magento's own loading wheel just keeps spinning.
Inspect element in google chrome gives the following error: knockout.js:2908 Uncaught Error: You cannot apply bindings multiple times to the same element.

**Comment by itaymesh** [comment]
Also happens on other pages like catalog > category and catalog > products
Seems like the symlink pub/static/adminhtml/Magento/backend/en_US/mage/adminhtml/wysiwyg/tiny_mce/html5-schema.js is missing....

**Comment by Gelgersma** [comment]
Still not working in RC-3

**Comment by Gelgersma** [comment]
I've found the cause of the issue. I had the caches all off for dev purposes and this brought the cpu usage to 100% which Magento didn't like. Reversed the settings and all is good now.
