### ISSUE TITLE
[Feature request] Backend usability for Quick Edit

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#4994]
Personally I found it a bit strange that when I click any item in a table in the backend, it opens a 'Quick Edit' in stead of the expected single-view-screen for that item (like how the WordPress admin functions).
But I can get used to it.

What I think would improve the usability tons is adding two little tweaks to the Quick Edit screen;
- Add an "Edit" (and maybe "Delete") link on the right side (the same as in the "Actions" dropdown)
- Bind the Enter key to the Save button for quicker inline editing

It's quite bothersome that if I want to edit or delete an item, I have to click open a submenu and if I don't click completely right the first time, I have to 'deselect' the item to get out of the Quick Edit and try again. It would be logical to add the same functionalities of the "Actions" submenu to the Quick Edit screen.

![mg2](https://cloud.githubusercontent.com/assets/9464641/16002709/4d498350-3159-11e6-9402-b53ae39471c7.jpg)

**Comment by antboiko** [comment]
Hi @Asitis Alex, thanks for your suggestions.

We already have the ticket MAGETWO-44703 in our backlog to cover improvements for in-line editing. I added your suggestion "to bind Enter key to the Save button" into it.

Thanks,
Anton.

**Comment by robinhuy** [comment]
About Quick Edit, I found that it does not check user's permission like Edit page.
Example, I don't have **Magento_Cms::save** permission but I can Edit the page in Quick Edit.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-request-Backend-usability-for-Quick-Edit/idi-p/45970).
