### ISSUE TITLE
No more User Role after update to 2.0.7

### ISSUE THREAD

**Issue by Talisa85** [magento/magento2#4995]
Hey guys,

i updated my magento to 2.0.7 today and try to create an knew User role after that. 
I can´t select anything ..... 
Anybody with same problems?

![image](https://cloud.githubusercontent.com/assets/19840780/16003040/12a59e62-315b-11e6-8fba-fdc01153cd13.png)

**Comment by ClaudiuCreanga** [comment]
what is your php version? if 7, it should be minimum 7.0.2 and not 7.0.5

**Comment by Talisa85** [comment]
php 5.5.9

**Comment by hoangphanbc** [comment]
we had the same issue with PHP 7.0.7

**Comment by stamster** [comment]
Check your file-system permissions.
If you upgraded via web tool, it is possible that your web server user took ownership of some files.

**Comment by wert2all** [comment]
@Talisa85 to allow us research the issue, please, provide concrete steps for reproducing a bug.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
