### ISSUE TITLE
V1/products API not work for filter website products

### ISSUE THREAD

**Issue by gzchauhan** [magento/magento2#4996]
rest/V1/products?searchCriteria[filterGroups][][filters][][field]=website_id&searchCriteria[filterGroups][][filters][][value]=1&searchCriteria[filterGroups][][filters][][conditionType]=eq 
I try this API code but it gave 
{
"message": "Invalid attribute name: %1"
"parameters": [1]
0:  "website_id"
}

how I filter products by webiste ?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
