### ISSUE TITLE
Customer group is changed when user edits his account info

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#4997]
## Steps to reproduce
1. Magento 2.0.7
2. create a customer with group for ex. Wholesale (not default general) https://drive.google.com/a/interiorwebdesign.com/file/d/0BzTvZltZJMLla19la2lNZTA2dFE/view?usp=drivesdk
3. log in on frontend using customer credentials, go to My Account -> Account Dashboard -> click Edit under Account Information
4. On this page click Save, not necessary to change data
## Expected result
1. customer group should remain the same
## Actual result
1. after customer saved the data, his group is changed to General https://drive.google.com/a/interiorwebdesign.com/file/d/0BzTvZltZJMLlR0s4WEpwZWZMNGc/view?usp=drivesdk

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-54326, thanks for posting

**Comment by mhabou** [comment]
@katesuykovskaya 
I confirm the issue

**Comment by skovalenk** [comment]
Hi @katesuykovskaya  This issue was fixed and delivered to mainline under MAGETWO-42954. Please let us know if you still have an issue

**Comment by ajaykrshukla** [comment]
Hello Sereban,

I am having the same issue in Magento 2.1.2 version.

So can you please suggest?

Thanks
