### ISSUE TITLE
All subcategories not showing up properly in dashboard

### ISSUE THREAD

**Issue by gtshows7** [magento/magento2#4998]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by katmoon** [comment]
Hi @gtshows7 
Could you provide reproducible steps for your issue?

Thanks,
Kateryna.

**Comment by pboisvert** [comment]
closing issue as this is the default issue template text and not a unique issue. If you meant to create a unique issue please provide full steps to reproduce
