### ISSUE TITLE
Plural support

### ISSUE THREAD

**Issue by alexdrupal** [magento/magento2#500]
Hi Folks!

Does magento has plural support for translations?
If no, I think it should be added to the todo list of Magento2 team.

At least, Zend framework having plural support since 1.6
Thanks!

**Comment by tanya-soroka** [comment]
Ticket number is MAGETWO-21570 in Magento 2 project.

**Comment by piotrekkaminski** [comment]
This proposal makes sense but is currently not our priority. It was added to backlog and will be handled with other i18n/l10n issues.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Plural-support/idi-p/46805).

**Comment by andkirby** [comment]
Any updates about that?

**Comment by celorodovalho** [comment]
@alexdrupal @andkirby 

This is possible by using `MessageFormatter` annotation:
```php
__('{0, plural, =0{0 cats} one{1 cat} other{# cats}}', 0)->render();
//0 cats
__('{0, plural, =0{0 cats} one{1 cat} other{# cats}}', 1)->render();
//1 cat
__('{0, plural, =0{0 cats} one{1 cat} other{# cats}}', 2)->render();
//2 cats
```
