### ISSUE TITLE
2.0.7 doesn't work with php 7.0.0, no di folder created

### ISSUE THREAD

**Issue by ClaudiuCreanga** [magento/magento2#5000]
## Steps to reproduce
1. have php 7.0.0
2. Install Magento with composer 
3. upgrade to 2.0.7
4. run setup:di:compile
## Expected result
1. compiling magento and creating di folder
## Actual result
1. stops at 14% with transmission error

This issue affects only php 7.0.0.Magento does not compile properly, no di folder created in var (no permission issues, checked them) and js errors on frontend. 

However when using php 7.0.6 everything is fine. 

If I downgrade back to 2.0.6 then it works with php 7.0.0

**Comment by ghost** [comment]
Check [system requirements](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html). The minimum supported PHP 7 version is 7.0.2

**Comment by ClaudiuCreanga** [comment]
Thanks. Those system requirements changed recently. Should have thrown errors when upgrading and magento make public on main forums when system requirements change. I've seen more people having issues, basically everyone who uses mamp. You shouldn't need to check system requirements every time you run a composer update. Lots of hours lost because of poor communictaion skills.
