### ISSUE TITLE
Add \Magento\Framework\App\Cli class implementing \Magento\Framework\AppInterface

### ISSUE THREAD

**Issue by aleron75** [magento/magento2#5001]
This is a _nice to have_ requirement born from poking with Magento 2 runtime: there isn't an `AppInterface` implementation for PHP scripts using Magento runtime.

Indeed the `bin/magento` is a `SymfonyApplication` and doesn't implement the `AppInterface`.

Here is the article which originated this thought: http://aleron75.com/2016/06/10/let-s-poke-with-magento-2-runtime/

Thank you!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-Magento-Framework-App-Cli-class-implementing-Magento/idi-p/45105).
