### ISSUE TITLE
How to set the locale (en_US") of Magento2 by using command line.

### ISSUE THREAD

**Issue by kmoguls** [magento/magento2#5005]
I have installed magento 2.0.7 with CentoOS 7 / Apache 2.4.6 / PHP 7 / MariaDB 10. 
After applying the Japanese locale to "Interface Locale" under Account Setting (refer the link below), I get "HTTP ERROR 500" for accessing the admin console.

Link: http://magento.stackexchange.com/questions/113847/magento-2-how-do-i-change-the-locale-of-admin-backend

I found out that the Japanese locale installation was incomplete. Consequently, I need a help for restoring the "en_US" locale by updating DB or Code (coding). 

Please help me to resolve this issue by providing the steps to change the locale with using command line.
Many thanks in advance.

**Comment by veloraven** [comment]
@kmoguls 
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
