### ISSUE TITLE
Select All Dropdown in Admin Glitchy

### ISSUE THREAD

**Issue by loomdecor** [magento/magento2#5006]
## Steps to reproduce
1. go to Cache Management (I believe it's happening on all pages with lists though
2. Try to click on the far left column with the dropdown box (e.g. where you would "select all"
3. If you click directly on the dropdown box itself, you will see it doesn't actually open the dropdown
4. If you click around enough (e.g. on the black part of the header for example), I usually can eventually get it to open
## Expected result
1. You should be able to click on the dropdown in the far right column to "select all" and certainly clicking the dropdown box itself should pull up the menu.  Ideally it would be anywhere in that column header black space OR the dropdown box (just in case you are on tablet) to give some room for error though.

**Comment by MomotenkoNatalia** [comment]
@loomdecor Thanks for reporting this issue! 
I am going to close it as duplicate - https://github.com/magento/magento2/issues/3580
