### ISSUE TITLE
Category Layered Navigation breaks when 2nd subcategory is added

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5009]
Mage 2.0.7

When I create a New Category and add products to it via the Category Products tab then the category layered navigation renders on the front end for that Category.

If I then add 1 Subcategory, assign it some products in the same manner... everything is fine... parent layered navigation for category working and single sub-category layered navigation working

As soon as I add a second subcategory, assign it some products, and save then the parent Category disappears from Layered Navigation all together. The subcategories' respective category layered navigation all works... if I route to the same Parent category view page I see both sub-cats in the Category layered navigation... but one level up that same Parent category is absent from the Category layered navigation... I have to delete the category (and child cats) and recreate it to get it back in Layered Navigation.

Yes, at all times Is Anchor = Yes

EDIT: I only have to delete both sub-cats to get the Parent cat to show back up in the Layered Navigation

**Comment by blizam** [comment]
EDIT: This shouldn't matter... I tried it with and without unique sub-category URL keys

My other variable is that my sub-category names aren't unique... they're the same names that other Parent categories have their subs named

Unique Parent Alpha
-subA
-subB

Unique Parent Beta
-subA
-subB

Unique Parent Gamma
-subA
-subB

**Comment by blizam** [comment]
In playing around with trying to get a workaround I found that if I create subA and subB cats first, each with assigned Products, THEN I create the Unique Parent cat, save and then drag in subA and subB to be beneath it in the tree on the Category admin page that it _sort_ of works... my Parent Cats will now render in the Category Layered nav BUT only one sub cat is now working/displayed under each parent... seems random which one it is too... despite both being configured in the backend

**Comment by blizam** [comment]
issue is the same whether I have unique URL keys or not on my sub-cats... have to have unique on the parent cats obviously... issue is persistent even if I set one of the sub cats to Is Anchor = No... once the 2nd sub cat is created the ONLY way to get the Parent Cat Layered Navigation showing back up is to delete both sub cats

**Comment by ghost** [comment]
I am experiencing the same issue(also posted in #2121) All my categories have unique names but do not all show under the category section in the layered navigation.

I have some categories with sub categories showing under the parent category and some not. Same with categories without sub categories.

There doesn't seem to really be a pattern to it that I can see.

**Comment by maghamed** [comment]
Internal issue created - MAGETWO-54383

**Comment by JamboMedia** [comment]
Same issue over here. The layered navigation is not showing categories at some cases.

**Comment by pboisvert** [comment]
@choukalos Chuck--can you have the team check into this one? Seems like a couple reports.

**Comment by BilleFash** [comment]
Also having this issue. Are their any fixes?

**Comment by ghost** [comment]
@BilleFash It works properly in 2.1.0.

**Comment by btwq** [comment]
I'm in 2.1.3 and seeing the same problem. Random display of sub-categories in Layered navigation. Help!

**Comment by btwq** [comment]
Further to my comment above, discovered it was due to a core Elasticsearch bug see https://github.com/magento/magento2/issues/7017

**Comment by magento-engcom-team** [comment]
@blizam, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by ci2014** [comment]
I'm experiencing that problem in Magento 2.2
