### ISSUE TITLE
Can't load js for first run web,or no cache browser!

### ISSUE THREAD

**Issue by phamquoctoan8013** [magento/magento2#5011]
`Uncaught TypeError: $(...).owlCarousel is not a function`
In cms blcok i call js file by   require. But first run web,or no cache browser! Can't load js. firebug return message: `Uncaught TypeError: $(...).owlCarousel is not a function`. so slide is missing on site. 
But 2nd run I see worked fine ! Only when the browser does not cache
`<script type="text/javascript">
   require([
        'jquery',
        'owl.carousel/owl.carousel.min'
    ], function ($) {
       $("#banner-slider-demo-1").owlCarousel({
           items: 1,
            autoplay: true,
            autoplayTimeout: 2000,
            autoplayHoverPause: true,
            dots: false,
            nav: true,
            navRewind: true,
            animateIn: 'fadeIn',
            animateOut: 'fadeOut',
            loop: true,
            navText: ["<em class='basetheme-icon-chevron-left'></em>","<em class='basetheme-icon-chevron-right'></em>"]
        });
    });
</script>`

**Comment by mrkhoa99** [comment]
@phamquoctoan8013 you should post on http://magento.stackexchange.com/ or https://community.magento.com/. 
**PS**: I have done a tutorial about Owl Carousel here: http://www.boolfly.com/magento-2-slider-with-owl-carousel/

**Comment by vkorotun** [comment]
Closing this one. 
@phamquoctoan8013 If you still have this issue, please proceed as suggested by @mrkhoa99 
Thank you.
