### ISSUE TITLE
Rupee symbol not working

### ISSUE THREAD

**Issue by prasanthnatrajan** [magento/magento2#5012]
**Rupee symbol not viewing**

Rupee symbol not viewing in my entire site

**Comment by pboisvert** [comment]
The issue template is pre-filled with information to help investigate issues. We need details such as at a minimum which version was the issue seen in and if there have been any customizations in order to investigate. Please provide more info to aid in the investigation of issues.

**Comment by prasanthnatrajan** [comment]
It occurs in Magento ver. 2.0.7 !

**Comment by antboiko** [comment]
@prasanthnatrajan could you please provide the detailed steps to reproduce the issue? 
What exact currency are you setting? Indian, Nepalese, Sri Lankan?

Thanks,
Anton.

**Comment by prasanthnatrajan** [comment]
@antboiko its Indian! Now its working! i didn't install the rupee font in my windows! Thankyou!

**Comment by antboiko** [comment]
Hi @prasanthnatrajan , thanks for the update. 

I'm closing this issue. Please feel free to reopen if it's needed.

Best,
Anton.
