### ISSUE TITLE
Typo error in Magento/Catalog/Block/Adminhtml/Product/Edit/Tabs

### ISSUE THREAD

**Issue by juanangel123** [magento/magento2#5016]
I checked out the develop branch and it is still wrong.

The error is in the alias of the class Magento\Backend\Block\Widget\Tabs (line 11), it should be WidgetTabs.

**Comment by davidalger** [comment]
@juanangel123 Thanks for reporting this. If you would like to resolve this issue (if it even still exists given how long it's been since this was originally opened), please submit a PR with the change. Closing for now. Thanks!
