### ISSUE TITLE
Product added to cart -> cart is empty, minicart is filled 

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5018]
Magento 2.0.4.
PHP7

If we add a product to the cart, its in the minicart, but not in the normal cart.

**Comment by orlangur** [comment]
I really doubt such scenario was not tested, most likely it is even a part of automated functional test suite.

Maybe there is something more specific with the steps or your instance?

**Comment by grasdaggel** [comment]
Seemed like it was a failure on our end. 

If something happens ever to you, just do the following:
rm -rf var/cache var/page_cache var/view_preprocessed var/generation pub/static/\* 
php bin/magento cache:flush
php bin/magento setup:static-content:deploy en_US de_DE ...

=> solved the problem. Weird!
