### ISSUE TITLE
No option to upload video in product import process

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#5019]
Hi mates,
Anybody please tell me, is there any option to include video/video_id at the time of product import process from the Magento backend. I exported a csv file of the product which have a video url, but in that csv they are not mentioning anything about product video.

**Comment by pboisvert** [comment]
@vipin-eglobeits this is a question best suited for the Magento Stack Exchange site or the Community forum. Git Hub is intended solely for reporting of issues. Closing the issue. Please reopen if you are reporting an issue.

**Comment by shinethazhava** [comment]
It's OK but didn't mention about video import anywhere in the documentation
that's why people ask about it.

**Comment by pboisvert** [comment]
i'll pass this ticket over to our head of merchant documentation so she can update the documentation.

**Comment by vipin-eglobeits** [comment]
@pboisvert This is an issue of Magento 2 that they didn't include any provision to upload videos when we add multiple products together. Otherwise please tell me the solution for the below scenario:
- I'm adding hundred products together through the backend using a csv import process.
- I have different videos for all of these products to show on the product detail page.

I did a research on this and found that Magento2 is not taking video ids at the time of product import/export.

**Comment by vinaysikarwar** [comment]
@vipin-eglobeits 

Did you get any solution to import product videos in Bulk product import process.

**Comment by rhino-corey** [comment]
Why is this closed? The product import is still missing the video data option in 2.2.

**Comment by medinadato** [comment]
We definitely need this feature implemented.

**Comment by ibecmattb** [comment]
Any update on this? Seems this feature is still not available? When exporting a product with a video attached to it, it does not show anywhere in the export csv. I am not able to create an import CSV with video urls either.

Any help? Thanks!

**Comment by skapin** [comment]
poke
