### ISSUE TITLE
Automatically Invoice All Items option does not appear for Zero Subtotal Checkout

### ISSUE THREAD

**Issue by truesilveruk** [magento/magento2#5024]
## Steps to reproduce

Go to the Magento 2.0.7 CE dashboard
Click Stores > Configuration > Sales > Payment Methods
Scroll to Zero Subtotal Checkout.
Option on http://docs.magento.com/m2/ce/user_guide/payment/zero-subtotal-checkout.html to **Automatically Invoice All Items** does not show. This option is mentioned in the text explanation but also does not show on the screenshot.
## Expected result

Should be able to set Automatically Invoice All Items to prevent delays to customers being able to download their products.
## Actual result

Option to Automatically Invoice All Items does not appear and cannot set the status to complete automatically either meaning manually having to invoice each order.

Please advise. 

Many thanks

L

**Comment by asemenenko** [comment]
Hi @truesilveruk , you need to set "New Order Status" to "Processing" and it will appear in the configuration.

**Comment by rav-redchamps** [comment]
Hi @truesilveruk 

This can only invoice orders with Zero subtotal. But what about a free product ordered with another product and order total is non-zero.

We at RedChamps has extension for this called "Auto Invoice Free Product"

https://redchamps.com/auto-invoice-free-product-magento-2-extension.html

**Comment by Hav7979** [comment]
![image](https://user-images.githubusercontent.com/87767509/126506201-a29a83d2-72cb-4d9a-a6e5-cd19c11da34c.png)
I do not have an option for processing. Only pending and fraud? and I do not have an option to   Automatically Invoice All Items does not show
