### ISSUE TITLE
Widget conditions 

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5026]
Hi, When i am trying add a widget of type catalog products list on pages with the conditions using sku of products to display. if i choose two sku of that particular products, it does not show. It does not show anything. it does not even display products even i choose different conditions as well. Is there any bug associated with this?
I am attaching images as well for reference.
![properties](https://cloud.githubusercontent.com/assets/19605497/16050763/c3679cba-3254-11e6-9fde-9fe9411a0952.png)
![widget opt](https://cloud.githubusercontent.com/assets/19605497/16050764/c3697ff8-3254-11e6-9999-ccd169e34340.png)
![widget options](https://cloud.githubusercontent.com/assets/19605497/16050765/c36bd6ea-3254-11e6-9db3-57e4c999c025.png)

**Comment by mslabko** [comment]
Hi @nmallepally 
For display products with sku1 or sku2 or ...  you can use condition "is one of" (it terms of SQL it: sku IN ('sku1', 'sku2' ...)
Condition "is" used for strict equals (in terms of SQL: sku = 'sku1')

Could you please clarify your business case - you want to show products if ALL products with mentioned SKUs are available?

**Comment by nmallepally** [comment]
Yes, It worked when used ANY or is one of condition. I wanted to show products based on their sku. It can be 2,3 or any (Just selecting configurable product and simple product sku's and displaying them on a particular container on the page.).
I was also wondering Does magento 2 also displays Sub categories on a category page (instead of displaying products of child categories). Like if I click on any sub category(which has child categories) of the main category, it displays products of child category rather than displaying the child categories. Can you give me some insight on this?.

**Comment by mslabko** [comment]
It depends on category display settings. Please check documentation: 
http://docs.magento.com/m2/ce/user_guide/catalog/categories-display-settings.html

If you have any questions or need technical assistance, please refer to the Community Forums or Magento Stack Exchange site for technical questions.

**Comment by nmallepally** [comment]
Thank you.

**Comment by mslabko** [comment]
You are welcome!
