### ISSUE TITLE
Free Shipping selectable for cart  total less than minimum order amount.

### ISSUE THREAD

**Issue by jason-vivid** [magento/magento2#5027]
Version 2.0.5

Steps to reproduce
1. Add product to cart less than the amount eligible for free shipping.
2. Proceed to checkout and select free shipping.
3. Free shipping is displayed and carried through to checkout.

Expected:
Option shouldn't be displayed or possible.

**Comment by alena-marchenko** [comment]
Hi @jason-vivid 

We've created MAGETWO-54464 internal ticket regarding this issue.
Thank you.

**Comment by jason-vivid** [comment]
Thanks

Jason

**Comment by dyushkin** [comment]
Hi @jason-vivid,

Issue is not reproducible on 2.0.5, not on develop branch.
It was tested with following settings:
- Free shipping field "Minimum Order Amount" was set to $30
- Simple product $10 was created

Maybe you can provide more specific settings?

regards,

**Comment by elenleonova** [comment]
Hi @jason-vivid - can you please take some to help us reproduce this issue? maybe some additional steps or configurations?

**Comment by alena-marchenko** [comment]
Closing this issue due to no response, please reopen when you have an update.

**Comment by Cacasapo** [comment]
I'm having this same exact issue with 2.1 upgraded from 2.08, along with another free shipping issue which I'll open a ticket for.

**Comment by komsitr** [comment]
I have the same problem with version 2.1

**Comment by licentia** [comment]
I'm having this issue to. 

It seems it happens when you satisfied the rule, but if you then remove an item from the cart, you are still getting free shipping.

**Comment by pboisvert** [comment]
all--this ticket is closed so not being actively investigated. If you are having an issue please file a new issue with full steps to reproduce.

**Comment by TommyKolkman** [comment]
@pboisvert This issue for me still persists in 2.1.7. Can this be opened up and investigated again?
