### ISSUE TITLE
Getting strange result querying carts API using multiple search filter groups

### ISSUE THREAD

**Issue by ipekerti** [magento/magento2#5030]
Reproducable steps:

1) Successful POST to search for abandoned carts with a simple 1 filter group (updated_at greater than equal 2016-06-14):
## https://devsvr.mydomain.com/index.php/rest/V1/carts/search?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2016-06-14&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq

Result of Step 1:
Assumed result is correct, it fetched 6 carts (3 Active, 3 InActive).  Actual result response data is in attached file 1FilterGroupResult.txt.
## [1FilterGroup-Result.txt](https://github.com/magento/magento2/files/314665/1FilterGroup-Result.txt)

2) Now perform a second query, adding an additional filter to narrow down the result (+ is_active equals true)
## https://devsvr.mydomain.com/index.php/rest/V1/carts/search?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2016-06-14&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&searchCriteria[filter_groups][1][filters][0][field]=is_active&searchCriteria[filter_groups][1][filters][0][value]=true&searchCriteria[filter_groups][1][filters][0][condition_type]=eq

Result of Step 2:
Although POST transaction was successful, it fetched the exact opposite of what's expeted, it returned the 3 carts whose is_active flags are false.  Actual result response data is in attached file 2FilterGroups-Result-isActiveTRUE.txt.
## [2FilterGroups-Result-isActiveTRUE.txt](https://github.com/magento/magento2/files/314664/2FilterGroups-Result-isActiveTRUE.txt)

3) Changing the is_active filter value from true to false yielded the same 3 records whose is_active flags are FALSE (presumably generating a set of correct results).  Actual result response data is in attached file 2FilterGroups-Result-isActiveFALSE.txt.

[2FilterGroups-Result-isActiveFALSE.txt](https://github.com/magento/magento2/files/314666/2FilterGroups-Result-isActiveFALSE.txt)

---

Why did the the filter condition is_active eq true generate the wrong set of results?

**Comment by veloraven** [comment]
@ipekerti , please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ipekerti** [comment]
Huh, I thought I had included it.  Sorry.

I'm using v2.0.6 community.

**Comment by magento-engcom-team** [comment]
@ipekerti, thank you for your report.
We've created internal ticket(s) MAGETWO-84956 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ipekerti, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
