### ISSUE TITLE
Missing required argument $routerList of Magento\Framework\App\RouterList.

### ISSUE THREAD

**Issue by mhauri** [magento/magento2#5031]
## Steps to reproduce
1. Install Magento the [Integrator](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html) way.
2. Copy a working env.php to app/etc/
3. Import an working database dump into mysql.
4. Open the Site in the Browser
## Expected result
1. The Site is shown as expected
## Actual result
1. Error message appears: "Missing required argument $routerList of Magento\Framework\App\RouterList.".

```
Missing required argument $routerList of Magento\Framework\App\RouterList.
#0 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#1 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#2 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#3 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'routerList', 'Magento\\Framewo...')
#4 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#5 /Volumes/workspace/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#6 /Volumes/workspace/magento2/vendor/magento/framework/App/Http.php(114): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#7 /Volumes/workspace/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#8 /Volumes/workspace/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}
```

This is quite a pitty as the same procedure was working in Magento 1.

**Comment by davidalger** [comment]
@mhauri Do you have a working app/etc/config.php file present? If either that or env.php are missing, Magento 2 will not consider itself installed as the config.php is used to know which modules are enabled, etc.

**Comment by mhauri** [comment]
@davidalger Thank you, that was it. 
The error message isn't really helpful then, would be great to throw an clear exception if the config is missing. I've expected that the config.php would be generated based on the values in the database. 
But thank you for clarifying.

**Comment by davidalger** [comment]
@mhauri The config.php file is generated when you run through the installation procedure, and it's expected that the file be there after installation. So I'm not sure if it makes sense to give an uninstalled error when the app is in a partially setup state (i.e. env.php is there but config.php is not).

**Comment by davidalger** [comment]
Glad you got it working! :)

**Comment by PavanKumarCh** [comment]
Thanks a lot... This solution worked for me too. In my case, config.php is missing.. After taking the same from colleague, it started working fine.

**Comment by jatasya** [comment]
I'm getting this error. I'm trying to install a fresh setup of magento. can anyone give me any guidance.

**Comment by PavanKumarCh** [comment]
check ur config.xml is exists or not.

Regards
PavanKumar Chamarthi
+91-8861733311

**Comment by jatasya** [comment]
In which folder?

**Comment by awviraj** [comment]
run 
bin/magento module:enable --all
bin/magento setup:di:compile
