### ISSUE TITLE
Magento admin multistore redirects to store url

### ISSUE THREAD

**Issue by aidin3000** [magento/magento2#5033]
Installed Magento 2 locally successfully locally on MAMP. Added a second store and edited .htaccess and index.php accordingly for a multistore environment.

I then edited the Base URL and Secure Base URL for store 1 to the new url and the admin now goes in a redirect loop.
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add a secondary store or even default store
3. Edit index.php and .htaccess
4. Edit Base Url / Secure URL to new domain
## Expected result
1. Admin is accessible to add more stores, products, etc.. and functions as expected
## Actual result
1. Admin is not accessible and redirects to new store Base URL

**Comment by andimov** [comment]
Please, provide used version in format 2.x.x(-rcx). If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by aidin3000** [comment]
The version that was used was Magento-CE-2.0.7-2016-05-24-12-06-54. It wasn't downloaded from here but rather magento download page.

**Comment by serzhik** [comment]
Same issue on 2.0.2EE

**Comment by sintsov** [comment]
My case for this bug Magento 2.1. 

website 1: domain.com (default)
website 2: domain2.com

1 base, the same code. 
For website 1 `web/unsecure/base_url`, `web/secure/base_url`, `web/unsecure/base_link_url`, `web/secure/base_link_url` set **domain.com**
For website 2  `web/unsecure/base_url`, `web/secure/base_url`, `web/unsecure/base_link_url`, `web/secure/base_link_url` set  **domain2.com**

In _domain.com/pub/index.php_

```
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'doman_cn';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
```

In _domain2.com/pub/index.php_ 

```
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'doman_dev';
$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
```

Then open https://domain.com/admin - that's ok. The i try open https://domain2.com/admin i get redirect to  https://domain.com/admin

Then i look at the code i see code 

```
/**
     * Retrieve config value by path and scope
     *
     * @param string $path
     * @param string $scope
     * @param null|string $scopeCode
     * @return mixed
     */
    public function getValue(
        $path = null,
        $scope = ScopeConfigInterface::SCOPE_TYPE_DEFAULT,
        $scopeCode = null
    ) {
        return $this->_scopePool->getScope($scope, $scopeCode)->getValue($path);
    }
```

Where  $scopeCode = 'admin'
return default `web/secure/base_link_url` for doman.com

**Comment by IlnitskiyArtem** [comment]
Hi, @aidin3000.
Internal ticket MAGETWO-70600, which tracks this GitHub issue, is in our issue backlog.

**Comment by magento-engcom-team** [comment]
@aidin3000, thank you for your report.
We've created internal ticket(s) MAGETWO-70600 to track progress on the issue.

**Comment by avra911** [comment]
This module fixed it for us: `METMEER/magento2-multi-store-fix`!

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
